OpenASIP: AddFUFromHDBDialog.cc File Reference
AddFUFromHDBDialog.cc File Reference
#include <sstream>
#include <boost/format.hpp>
#include <wx/statline.h>
#include <wx/listctrl.h>
#include <wx/dir.h>
#include <wx/textctrl.h>
#include <wx/imaglist.h>
#include <wx/srchctrl.h>
#include "AddFUFromHDBDialog.hh"
#include "Model.hh"
#include "Machine.hh"
#include "WxConversion.hh"
#include "WidgetTools.hh"
#include "HDBManager.hh"
#include "FUArchitecture.hh"
#include "FunctionUnit.hh"
#include "HWOperation.hh"
#include "WarningDialog.hh"
#include "ErrorDialog.hh"
#include "MapTools.hh"
#include "Environment.hh"
#include "FileSystem.hh"
#include "FUPort.hh"
#include "ExecutionPipeline.hh"
#include "HDBRegistry.hh"
#include "ObjectState.hh"
#include "ProDeConstants.hh"
Typedefs
typedef long int wxIntPtr
Functions
int wxCALLBACK FUListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
int wxCALLBACK FUListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Detailed Description
Implementation of AddFUFromHDBDialog class.
Author
Veli-Pekka Jääskeläinen 2006 (vjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file AddFUFromHDBDialog.cc.
Typedef Documentation
wxIntPtr
typedef long int wxIntPtr
Definition at line 64 of file AddFUFromHDBDialog.cc.
Function Documentation
FUListCompareASC()
int wxCALLBACK FUListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 86 of file AddFUFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid1->latency - lid2->latency;
    } else if (sortColumn == 1) {
        return lid1->operations.Cmp(lid2->operations);
    } else if (sortColumn == 3) {
        return lid1->hdbId - lid2->hdbId;
    } else if (sortColumn == 4) {
        return lid1->path.Cmp(lid2->path);
    }
    return 0;
}
References ListItemData::hdbId, ListItemData::latency, ListItemData::operations, and ListItemData::path.
Referenced by AddFUFromHDBDialog::loadHDB(), and AddFUFromHDBDialog::onColumnClick().
FUListCompareDESC()
int wxCALLBACK FUListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 106 of file AddFUFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid2->latency - lid1->latency;
    } else if (sortColumn == 1) {
        return lid2->operations.Cmp(lid1->operations);
    } else if (sortColumn == 3) {
        return lid2->hdbId - lid1->hdbId;
    } else if (sortColumn == 4) {
        return lid2->path.Cmp(lid1->path);
    }
    return 0;
}
References ListItemData::hdbId, ListItemData::latency, ListItemData::operations, and ListItemData::path.
Referenced by AddFUFromHDBDialog::onColumnClick().