OpenASIP: AddIUFromHDBDialog.cc File Reference
AddIUFromHDBDialog.cc File Reference
#include <boost/format.hpp>
#include <wx/statline.h>
#include <wx/listctrl.h>
#include <wx/dir.h>
#include <wx/imaglist.h>
#include "AddIUFromHDBDialog.hh"
#include "Model.hh"
#include "Machine.hh"
#include "WxConversion.hh"
#include "WidgetTools.hh"
#include "HDBManager.hh"
#include "HDBRegistry.hh"
#include "RFArchitecture.hh"
#include "WarningDialog.hh"
#include "MapTools.hh"
#include "Environment.hh"
#include "FileSystem.hh"
#include "Conversion.hh"
#include "ProDeConstants.hh"
Typedefs
typedef long int wxIntPtr
Functions
int wxCALLBACK IUListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
int wxCALLBACK IUListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Detailed Description
Implementation of AddIUFromHDBDialog class.
Author
Veli-Pekka Jääskeläinen 2006 (vjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file AddIUFromHDBDialog.cc.
Typedef Documentation
wxIntPtr
typedef long int wxIntPtr
Definition at line 55 of file AddIUFromHDBDialog.cc.
Function Documentation
IUListCompareASC()
int wxCALLBACK IUListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 80 of file AddIUFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid1->width - lid2->width;
    } else if (sortColumn == 1) {
        return lid1->size - lid2->size;
    } else if (sortColumn == 2) {
        return lid1->readPorts - lid2->readPorts;
    } else if (sortColumn == 3) {
        return lid1->latency - lid2->latency;
    } else if (sortColumn == 4) {
        return lid1->hdbId - lid2->hdbId;
    } else if (sortColumn == 5) {
        return lid1->path.Cmp(lid2->path);
    }
    return 0;
}
References ListItemData::hdbId, ListItemData::latency, ListItemData::path, ListItemData::readPorts, ListItemData::size, and ListItemData::width.
Referenced by AddIUFromHDBDialog::loadHDB(), and AddIUFromHDBDialog::onColumnClick().
IUListCompareDESC()
int wxCALLBACK IUListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 104 of file AddIUFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid2->width - lid1->width;
    } else if (sortColumn == 1) {
        return lid2->size - lid1->size;
    } else if (sortColumn == 2) {
        return lid2->readPorts - lid1->readPorts;
    } else if (sortColumn == 3) {
        return lid2->latency - lid1->latency;
    } else if (sortColumn == 4) {
        return lid2->hdbId - lid1->hdbId;
    } else if (sortColumn == 5) {
        return lid2->path.Cmp(lid1->path);
    }
    return 0;
}
References ListItemData::hdbId, ListItemData::latency, ListItemData::path, ListItemData::readPorts, ListItemData::size, and ListItemData::width.
Referenced by AddIUFromHDBDialog::onColumnClick().