OpenASIP: AddRFFromHDBDialog.cc File Reference
AddRFFromHDBDialog.cc File Reference
#include <boost/format.hpp>
#include <wx/statline.h>
#include <wx/listctrl.h>
#include <wx/dir.h>
#include <wx/imaglist.h>
#include "AddRFFromHDBDialog.hh"
#include "Model.hh"
#include "Machine.hh"
#include "WxConversion.hh"
#include "WidgetTools.hh"
#include "HDBManager.hh"
#include "RFArchitecture.hh"
#include "WarningDialog.hh"
#include "MapTools.hh"
#include "Environment.hh"
#include "FileSystem.hh"
#include "HDBRegistry.hh"
#include "Conversion.hh"
#include "ProDeConstants.hh"
Typedefs
typedef long int wxIntPtr
Functions
int wxCALLBACK RFListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
int wxCALLBACK RFListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Detailed Description
Implementation of AddRFFromHDBDialog class.
Author
Veli-Pekka Jääskeläinen 2006 (vjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file AddRFFromHDBDialog.cc.
Typedef Documentation
wxIntPtr
typedef long int wxIntPtr
Definition at line 55 of file AddRFFromHDBDialog.cc.
Function Documentation
RFListCompareASC()
int wxCALLBACK RFListCompareASC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 77 of file AddRFFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid1->width - lid2->width;
    } else if (sortColumn == 1) {
        return lid1->size - lid2->size;
    } else if (sortColumn == 2) {
        return lid1->readPorts - lid2->readPorts;
    } else if (sortColumn == 3) {
        return lid1->writePorts - lid2->writePorts;
    } else if (sortColumn == 4) {
        return lid1->bidirPorts - lid2->bidirPorts;
    } else if (sortColumn == 5) {
        return lid1->maxReads - lid2->maxReads;
    } else if (sortColumn == 6) {
        return lid1->maxWrites - lid2->maxWrites;
    } else if (sortColumn == 7) {
        return lid1->hdbId - lid2->hdbId;
    } else if (sortColumn == 8) {
        return lid1->path.Cmp(lid2->path);
    }
    return 0;
}
References ListItemData::bidirPorts, ListItemData::hdbId, ListItemData::maxReads, ListItemData::maxWrites, ListItemData::path, ListItemData::readPorts, ListItemData::size, ListItemData::width, and ListItemData::writePorts.
Referenced by AddRFFromHDBDialog::loadHDB(), and AddRFFromHDBDialog::onColumnClick().
RFListCompareDESC()
int wxCALLBACK RFListCompareDESC (wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData)
Definition at line 107 of file AddRFFromHDBDialog.cc.
{
    ListItemData* lid1 = (ListItemData*)item1;
    ListItemData* lid2 = (ListItemData*)item2;
    int sortColumn = (int)sortData;
    if (sortColumn == 0) {
        return lid2->width - lid1->width;
    } else if (sortColumn == 1) {
        return lid2->size - lid1->size;
    } else if (sortColumn == 2) {
        return lid2->readPorts - lid1->readPorts;
    } else if (sortColumn == 3) {
        return lid2->writePorts - lid1->writePorts;
    } else if (sortColumn == 4) {
        return lid2->bidirPorts - lid1->bidirPorts;
    } else if (sortColumn == 5) {
        return lid2->maxReads - lid1->maxReads;
    } else if (sortColumn == 6) {
        return lid2->maxWrites - lid1->maxWrites;
    } else if (sortColumn == 7) {
        return lid2->hdbId - lid1->hdbId;
    } else if (sortColumn == 8) {
        return lid2->path.Cmp(lid1->path);
    }
    return 0;
}
References ListItemData::bidirPorts, ListItemData::hdbId, ListItemData::maxReads, ListItemData::maxWrites, ListItemData::path, ListItemData::readPorts, ListItemData::size, ListItemData::width, and ListItemData::writePorts.
Referenced by AddRFFromHDBDialog::onColumnClick().