OpenASIP: BuildOpset.cc File Reference
BuildOpset.cc File Reference
#include <string>
#include <iostream>
#include <vector>
#include "BuildOpset.hh"
#include "FileSystem.hh"
#include "CmdLineOptions.hh"
#include "Environment.hh"
#include "Conversion.hh"
#include "tce_config.h"
#include "OperationBuilder.hh"
Functions
int main (int argc, char *argv[])
Variables
const string SCHEMA_FILE_NAME = "Operation_Schema.xsd"
Detailed Description
Program that builds operation behavior module and locates them to the target directory.
Author
Jussi Nyk채nen 2004 (nykanen-no.spam-cs.tut.fi)
Pekka J채채skel채inen 2013
Note
rating: red
Definition in file BuildOpset.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Main program.
Searches for XML file given to it as a parameter. Then searches for a corresponding operation behavior source file and compiles it.
Definition at line 124 of file BuildOpset.cc.
{
    Application::initialize(argc, argv);
    try {
        OperationBuilder& builder = OperationBuilder::instance();
        BuildOpsetOptions *options = new BuildOpsetOptions;
        options->parse(argv, argc);
        Application::setCmdLineOptions(options);
        int arguments = options->numberOfArguments();
        string module = "";
        // first argument is XML data file
        if (arguments == 0 || arguments > 1) {
            options->printHelp();
            return EXIT_FAILURE;
        } else {
            module = options->argument(1);
        }
        // get the path for the files
        if (!FileSystem::isAbsolutePath(module)) {
            module = FileSystem::currentWorkingDir()
                + FileSystem::DIRECTORY_SEPARATOR + module;
        }
        string path = FileSystem::directoryOfPath(module);
        // get the base name of the module
        string moduleName = FileSystem::fileOfPath(module);
        // get the path for the behavior file
        string behaviorPath = options->sourceDir();
        if (behaviorPath == "") {
            behaviorPath = path;
        }
        // verify that the operation properties file is legal
        if (!builder.verifyXML(module + ".opp")) {
            return EXIT_FAILURE;
        }
        // find the behavior source file and check if it should be ignored
        // if it's not found
        string behFile = builder.behaviorFile(moduleName, behaviorPath);
        if (behFile == "" && !options->ignore()) {
            string errorMessage = "Behavior source file '";
            errorMessage += behaviorPath + FileSystem::DIRECTORY_SEPARATOR
                + moduleName + ".cc" + "' not found";
            cerr << errorMessage << endl;
            return EXIT_FAILURE;
        }
        // build and install the behavior module
        vector<string> output;
        builder.buildObject(moduleName, behFile, path, output);
        if (output.size() > 0) {
            cerr << "Error building shared objects:" << endl;
            for (size_t i = 0; i < output.size(); i++) {
                cerr << output[i] << endl;
            }
            return EXIT_FAILURE;
        }
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& i) {
        cerr << i.errorMessage() << endl;
        return EXIT_FAILURE;
    } catch (const Exception& e) {
        string linenum = Conversion::toString(e.lineNum());
        cerr << "Exception thrown: " << e.fileName() << ": "
             << linenum << ": " << e.procedureName() << ": "
             << e.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
References OperationBuilder::behaviorFile(), OperationBuilder::buildObject(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::directoryOfPath(), Exception::errorMessage(), Exception::fileName(), FileSystem::fileOfPath(), Application::initialize(), OperationBuilder::instance(), FileSystem::isAbsolutePath(), Exception::lineNum(), CmdLineParser::numberOfArguments(), options, CmdLineOptions::parse(), MachInfoCmdLineOptions::printHelp(), Exception::procedureName(), Application::setCmdLineOptions(), Conversion::toString(), and OperationBuilder::verifyXML().
Variable Documentation
SCHEMA_FILE_NAME
const string SCHEMA_FILE_NAME = "Operation_Schema.xsd"
Definition at line 53 of file BuildOpset.cc.