OpenASIP: BusDialog.cc File Reference
BusDialog.cc File Reference
#include <wx/wx.h>
#include <wx/listctrl.h>
#include <wx/radiobox.h>
#include <wx/spinctrl.h>
#include <boost/format.hpp>
#include "BusDialog.hh"
#include "Bus.hh"
#include "Segment.hh"
#include "Guard.hh"
#include "Conversion.hh"
#include "WxConversion.hh"
#include "WarningDialog.hh"
#include "ErrorDialog.hh"
#include "InformationDialog.hh"
#include "Machine.hh"
#include "MachineTester.hh"
#include "UserManualCmd.hh"
#include "ProDeConstants.hh"
#include "FUPort.hh"
#include "RFGuardDialog.hh"
#include "FUGuardDialog.hh"
#include "ModelConstants.hh"
#include "WidgetTools.hh"
#include "GUITextGenerator.hh"
#include "ProDeTextGenerator.hh"
Functions
int wxCALLBACK ListCompareFunction (long item1, long item2, long WXUNUSED(sortData))
Detailed Description
Definition of BusDialog class.
Author
Veli-Pekka Jääskeläinen 2004 (vjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file BusDialog.cc.
Function Documentation
ListCompareFunction()
int wxCALLBACK ListCompareFunction (long item1, long item2, long WXUNUSEDsortData)
Defines how SortItems() does comparison between two items to sort the list.
Order: names in ascending order. Within same name, index numbers in ascending order. Within same name and index number, non-inverted guard comes before inverted.
Definition at line 375 of file BusDialog.cc.
{
    // items are set with SetItemData to contain pointers to the rf guards
    RegisterGuard* rfGuard1 = (RegisterGuard*) item1;
    RegisterGuard* rfGuard2 = (RegisterGuard*) item2;
    assert (rfGuard1 != NULL);
    assert (rfGuard2 != NULL);
    string name1 = rfGuard1->registerFile()->name();
    int index1 = rfGuard1->registerIndex();
    bool inverted1 = rfGuard1->isInverted();
    string name2 = rfGuard2->registerFile()->name();
    int index2 = rfGuard2->registerIndex();
    bool inverted2 = rfGuard2->isInverted();
    if (name1 < name2) {
        return -1;
    } else if (name1 > name2) {
        return 1;
    } else if (index1 < index2) {
        return -1;
    } else if (index1 > index2) {
        return 1;
    } else if (!inverted1 && inverted2) {
        return -1;
    } else if (inverted1 && !inverted2) {
        return 1;
    }
    return 0;
}
References assert, TTAMachine::Guard::isInverted(), TTAMachine::Component::name(), TTAMachine::RegisterGuard::registerFile(), and TTAMachine::RegisterGuard::registerIndex().
Referenced by BusDialog::updateGuardLists().