OpenASIP: InfoRegistersCommand Class Reference
InfoRegistersCommand Class Reference
Public Member Functions
InfoRegistersCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoRegistersCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Static Public Member Functions
static std::string registerDescription (const std::string &regName, const SimValue &value)
Detailed Description
Implementation of "info registers".
Definition at line 92 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoRegistersCommand()
InfoRegistersCommand::InfoRegistersCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 98 of file InfoCommand.cc.
                                                                   :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoRegistersCommand()
virtual InfoRegistersCommand::~InfoRegistersCommand () inline virtual
Destructor.
Definition at line 105 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoRegistersCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info registers" command.
"info registers regfile regname" prints the value of register regname in register file regfile, where regfile is the name of a register file of the target processor, and regname is the name of a register that belongs to the specified register file. If regname is omitted, values of all registers of the specified register file are displayed.
Parameters
arguments Arguments to the command, including "info registers".
Returns
true in case execution was successful.
Implements SimControlLanguageSubCommand.
Definition at line 120 of file InfoCommand.cc.
{
        if (!parent().checkProgramLoaded()) {
            return false;
        }
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 1, 2)) {
            return false;
        }
        std::string registerFile = "";
        std::string registerName = "";
        std::string registerString = "";
        int registerIndex = -1;
        if (argumentCount == 1) {
            // 'ra' is treated as a special case
            if (StringTools::ciEqual(registerString, "ra")) {
                StateData& data =
                    parent().simulatorFrontend().state(registerString);
                parent().interpreter()->setResult(
                    registerDescription(registerString, data.value()));
                return true;
            }
            registerFile = arguments[2].stringValue();
            try {
                parent().interpreter()->setResult(
                    parent().simulatorFrontend().registerFileValue(registerFile));
            } catch (const InstanceNotFound&) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_REGISTER_NOT_FOUND).str());
                return false;
            }
            return true;
        } else if (argumentCount == 2) {
            // prints out the register in the given register file
            if (!parent().checkPositiveIntegerArgument(arguments[3])) {
                return false;
            }
            registerFile = arguments[2].stringValue();
            registerIndex = arguments[3].integerValue();
            registerName =
                registerFile + "." + Conversion::toString(registerIndex);
        } else {
            abortWithError("Illegal count of arguments.");
        }
        // print a single register value
        try {
            parent().interpreter()->setResult(
                parent().simulatorFrontend().registerFileValue(
                    registerFile, registerIndex));
            return true;
        } catch (const InstanceNotFound&) {
            parent().interpreter()->setError(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_REGISTER_NOT_FOUND).str());
            return false;
        }
        return true;
    }
References abortWithError, StringTools::ciEqual(), CustomCommand::interpreter(), SimControlLanguageSubCommand::parent(), registerDescription(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::state(), SimulatorToolbox::textGenerator(), Conversion::toString(), Texts::TXT_REGISTER_NOT_FOUND, and ReadableState::value().
registerDescription()
static std::string InfoRegistersCommand::registerDescription (const std::string & regName, const SimValue & value) inline static
Helper function to get register description in correct format.
Parameters
regName The name of the register to print.
value The current value of the register.
Definition at line 195 of file InfoCommand.cc.
{
        return regName + " " + value.hexValue() + " " +
            Conversion::toString(value.sLongWordValue());
    }
References SimValue::hexValue(), SimValue::sLongWordValue(), and Conversion::toString().
Referenced by execute(), InfoImmediatesCommand::execute(), and InfoPortsCommand::execute().
The documentation for this class was generated from the following file:
InfoCommand.cc