OpenASIP: HDLGenerator::BinaryOp Class Reference
HDLGenerator::BinaryOp Class Reference
#include <BinaryOps.hh>
Public Member Functions
BinaryOp (const LHSValue &lhs, const LHSValue &rhs, std::string VHDLOperator, std::string VerilogOperator)
Public Member Functions inherited from HDLGenerator::LHSValue
LHSValue ()
void hdl (std::ostream &stream, Language lang, int level)
void hdl (std::ostream &stream, Language lang)
void writeSignals (std::unordered_set< std::string > &readList) const
std::string vhdl () const
std::string verilog () const
LHSValue operator|| (LHSValue rhs)
LHSValue operator| (LHSValue rhs)
LHSValue operator&& (LHSValue rhs)
LHSValue operator& (LHSValue rhs)
LHSValue operator^ (LHSValue rhs)
LHSValue operator! ()
LHSValue operator~ ()
Additional Inherited Members
Protected Attributes inherited from HDLGenerator::LHSValue
std::unordered_set< std::string > readList_
std::string vhdl_
std::string verilog_
Detailed Description
Definition at line 37 of file BinaryOps.hh.
Constructor & Destructor Documentation
BinaryOp()
HDLGenerator::BinaryOp::BinaryOp (const LHSValue & lhs, const LHSValue & rhs, std::string VHDLOperator, std::string VerilogOperator) inline
Definition at line 39 of file BinaryOps.hh.
{
            vhdl_ = "(" + lhs.vhdl() + " " + VHDLOperator
                        + " " + rhs.vhdl() + ")";
            verilog_ = "(" + lhs.verilog() + " " + VerilogOperator + " "
                           + rhs.verilog() + ")";
            lhs.writeSignals(readList_);
            rhs.writeSignals(readList_);
        }
References HDLGenerator::LHSValue::readList_, HDLGenerator::LHSValue::verilog(), HDLGenerator::LHSValue::verilog_, HDLGenerator::LHSValue::vhdl(), HDLGenerator::LHSValue::vhdl_, and HDLGenerator::LHSValue::writeSignals().
The documentation for this class was generated from the following file:
BinaryOps.hh