OpenASIP: ImmediateSlotDialog Class Reference
ImmediateSlotDialog Class Reference
#include <ImmediateSlotDialog.hh>
Public Member Functions
ImmediateSlotDialog (wxWindow *parent, TTAMachine::Machine *machine)
virtual ~ImmediateSlotDialog ()
Private Types
enum {
ID_SLOT_LIST = 10000 , ID_NAME , ID_LABEL_NAME , ID_LABE_NAME ,
ID_ADD_SLOT , ID_DELETE_SLOT , ID_LINE , ID_HELP
}
Private Member Functions
virtual bool TransferDataToWindow ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void updateSlotList ()
void onAddSlot (wxCommandEvent &event)
void onDeleteSlot (wxCommandEvent &event)
void onSlotName (wxCommandEvent &event)
void onSlotSelection (wxListEvent &event)
void setTexts ()
Private Attributes
TTAMachine::Machine * machine_
Parent machine of the immediate slots.
wxListCtrl * slotList_
Immediate slot list widget.
wxString slotName_
Text in the slot name widget.
Detailed Description
Dialog for modifying immediate slots in a machine.
Definition at line 47 of file ImmediateSlotDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_SLOT_LIST
ID_NAME
ID_LABEL_NAME
ID_LABE_NAME
ID_ADD_SLOT
ID_DELETE_SLOT
ID_LINE
ID_HELP
Definition at line 69 of file ImmediateSlotDialog.hh.
         {
    ID_SLOT_LIST = 10000,
    ID_NAME,
    ID_LABEL_NAME,
    ID_LABE_NAME,
    ID_ADD_SLOT,
    ID_DELETE_SLOT,
    ID_LINE,
    ID_HELP
    };
Constructor & Destructor Documentation
ImmediateSlotDialog()
ImmediateSlotDialog::ImmediateSlotDialog (wxWindow * parent, TTAMachine::Machine * machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Parent Machine of the immediate slots.
Definition at line 67 of file ImmediateSlotDialog.cc.
                      :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    machine_(machine) {
    createContents(this, true, true);
    slotList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_SLOT_LIST));
    FindWindow(ID_NAME)->SetValidator(
    wxTextValidator(wxFILTER_ASCII, &slotName_));
    // Disable conditional buttons.
    FindWindow(ID_ADD_SLOT)->Disable();
    FindWindow(ID_DELETE_SLOT)->Disable();
    setTexts();
}
~ImmediateSlotDialog()
ImmediateSlotDialog::~ImmediateSlotDialog () virtual
The Destructor.
Definition at line 91 of file ImmediateSlotDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ImmediateSlotDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Returns
Top level sizer of the dialog contents.
Definition at line 276 of file ImmediateSlotDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_SLOT_LIST, wxDefaultPosition, wxSize(300,200), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item3->Add( item4, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item8 = new wxButton( parent, ID_ADD_SLOT, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item9 = new wxButton( parent, ID_DELETE_SLOT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item3->Add( item7, 0, wxALIGN_CENTER, 5 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item10 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item10, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item11 = new wxGridSizer( 2, 0, 0 );
    wxButton *item12 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALL, 5 );
    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item14 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item15 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    item11->Add( item13, 0, 0, 5 );
    item0->Add( item11, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_SLOT, ID_DELETE_SLOT, ID_HELP, ID_LABEL_NAME, ID_LINE, ID_NAME, and ID_SLOT_LIST.
onAddSlot()
void ImmediateSlotDialog::onAddSlot (wxCommandEvent & event) private
Adds a new slot to the machine when "Add" button is pressed.
Definition at line 193 of file ImmediateSlotDialog.cc.
{
    if (!TransferDataFromWindow()) {
    return;
    }
    string trimmedName =
    WxConversion::toString(slotName_.Trim(false).Trim(true));
    // Check name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format message =
        prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
    InformationDialog warning(
        this, WxConversion::toWxString(message.str()));
    warning.ShowModal();
    return;
    }
    if (machine_->immediateSlotNavigator().hasItem(trimmedName)) {
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format message =
        prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
    message % trimmedName;
    message % prodeTexts->text(ProDeTextGenerator::COMP_AN_IMM_SLOT).str();
    message % prodeTexts->text(ProDeTextGenerator::COMP_MACHINE).str();
    message % prodeTexts->text(ProDeTextGenerator::COMP_IMM_SLOT).str();
    WarningDialog warning(this, WxConversion::toWxString(message.str()));
    warning.ShowModal();
    return;
    }
    // Buses share namespace with immediate slots. Check that a bus with the
    // same name does not exist.
    if (machine_->busNavigator().hasItem(trimmedName)) {
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format message =
        prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
    message % trimmedName;
    message % prodeTexts->text(ProDeTextGenerator::COMP_A_BUS).str();
    message % prodeTexts->text(ProDeTextGenerator::COMP_MACHINE).str();
    message % prodeTexts->text(ProDeTextGenerator::COMP_IMM_SLOT).str();
    WarningDialog warning(this, WxConversion::toWxString(message.str()));
    warning.ShowModal();
    return;
    }
    new ImmediateSlot(trimmedName, *machine_);
    slotName_ = _T("");
    TransferDataToWindow();
}
References TTAMachine::Machine::busNavigator(), ProDeTextGenerator::COMP_A_BUS, ProDeTextGenerator::COMP_AN_IMM_SLOT, ProDeTextGenerator::COMP_IMM_SLOT, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateSlotNavigator(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), machine_, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, slotName_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), and TransferDataToWindow().
onDeleteSlot()
void ImmediateSlotDialog::onDeleteSlot (wxCommandEvent & event) private
Deletes the selected immediate slot.
Definition at line 167 of file ImmediateSlotDialog.cc.
{
    // Check which slot is selected.
    long item = -1;
    item = slotList_->GetNextItem(
    item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item < 0) {
    return;
    }
    ImmediateSlot* slot =
    machine_->immediateSlotNavigator().item(item);
    delete slot;
    TransferDataToWindow();
    wxListEvent dummy;
    onSlotSelection(dummy);
}
References dummy, TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, onSlotSelection(), slotList_, and TransferDataToWindow().
onSlotName()
void ImmediateSlotDialog::onSlotName (wxCommandEvent & event) private
Enables and disables the "Add" button when text is entered in the slot name widget.
Definition at line 252 of file ImmediateSlotDialog.cc.
{
    if (!TransferDataFromWindow()) {
    return;
    }
    wxString trimmedName = slotName_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
    FindWindow(ID_ADD_SLOT)->Disable();
    } else {
    FindWindow(ID_ADD_SLOT)->Enable();
    }
}
References ID_ADD_SLOT, and slotName_.
onSlotSelection()
void ImmediateSlotDialog::onSlotSelection (wxListEvent & event) private
Enables and disables the delete button according to slot list selection.
Definition at line 154 of file ImmediateSlotDialog.cc.
{
    if (slotList_->GetSelectedItemCount() == 1) {
    FindWindow(ID_DELETE_SLOT)->Enable();
    } else {
    FindWindow(ID_DELETE_SLOT)->Disable();
    }
}
References ID_DELETE_SLOT, and slotList_.
Referenced by onDeleteSlot().
setTexts()
void ImmediateSlotDialog::setTexts () private
Sets widget texts.
Definition at line 99 of file ImmediateSlotDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title.
    format fmt = prodeTexts->text(
    ProDeTextGenerator::TXT_IMMEDIATE_SLOT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // Buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
              GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
              GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
              GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_SLOT),
              GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_SLOT),
              GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_NAME),
              ProDeTextGenerator::TXT_LABEL_NAME);
    format fmtCol = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    slotList_->InsertColumn(0, WxConversion::toWxString(fmtCol.str()),
                wxLIST_FORMAT_LEFT, 300);
}
References ID_ADD_SLOT, ID_DELETE_SLOT, ID_HELP, ID_NAME, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), slotList_, Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_IMMEDIATE_SLOT_DIALOG_TITLE, and ProDeTextGenerator::TXT_LABEL_NAME.
TransferDataToWindow()
bool ImmediateSlotDialog::TransferDataToWindow () private virtual
Transfers data from the machine model to the dialog widgets.
Definition at line 134 of file ImmediateSlotDialog.cc.
{
    // update slot list
    slotList_->DeleteAllItems();
    const Machine::ImmediateSlotNavigator navigator =
    machine_->immediateSlotNavigator();
    for (int i = 0; i < navigator.count(); i++) {
    slotList_->InsertItem(
        i, WxConversion::toWxString(navigator.item(i)->name()));
    }
    return wxDialog::TransferDataToWindow();
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, slotList_, and WxConversion::toWxString().
Referenced by onAddSlot(), and onDeleteSlot().
updateSlotList()
void ImmediateSlotDialog::updateSlotList () private
Member Data Documentation
machine_
TTAMachine::Machine* ImmediateSlotDialog::machine_ private
Parent machine of the immediate slots.
Definition at line 63 of file ImmediateSlotDialog.hh.
Referenced by onAddSlot(), onDeleteSlot(), and TransferDataToWindow().
slotList_
wxListCtrl* ImmediateSlotDialog::slotList_ private
Immediate slot list widget.
Definition at line 65 of file ImmediateSlotDialog.hh.
Referenced by onDeleteSlot(), onSlotSelection(), setTexts(), and TransferDataToWindow().
slotName_
wxString ImmediateSlotDialog::slotName_ private
Text in the slot name widget.
Definition at line 67 of file ImmediateSlotDialog.hh.
Referenced by onAddSlot(), and onSlotName().
The documentation for this class was generated from the following files:
ImmediateSlotDialog.hh
ImmediateSlotDialog.cc