OpenASIP: LLVMTCECmdLineOptions Class Reference
LLVMTCECmdLineOptions Class Reference
#include <LLVMTCECmdLineOptions.hh>
Public Member Functions
LLVMTCECmdLineOptions ()
~LLVMTCECmdLineOptions ()
virtual FunctionNameList * primaryFunctions () const
bool isStandardEmulationLibDefined () const
std::string standardEmulationLib () const
bool isOptLevelDefined () const
int optLevel () const
bool isVerboseSwitchDefined () const
bool debugFlag () const
bool conservativePreRAScheduler () const
bool saveBackendPlugin () const
bool useBUScheduler () const
bool useTDScheduler () const
bool useBubbleFish2Scheduler () const
bool useOldBackendSources () const
bool disableDelaySlotFiller () const
bool isWorkItemAAFileDefined () const
std::string workItemAAFile () const
bool analyzeInstructionPatterns () const
std::string backendCacheDir () const
TCEString tempDir () const
virtual std::string getLLVMargv () const
virtual bool dumpDDGsDot () const
virtual bool dumpDDGsXML () const
virtual bool disableLLVMAA () const
bool useVectorBackend () const
bool isInitialStackPointerValueSet () const
uint64_t initialStackPointerValue () const
bool isDataStartAddressSet (TTAMachine::AddressSpace &aSpace) const
uint64_t dataStartAddress (TTAMachine::AddressSpace &aSpace) const
bool printInlineAsmWarnings () const
bool generatePluginOnly () const
bool disableAddressSpaceAA () const
bool disableHWLoops () const
bool assumeADFStackAlignment () const
virtual void printVersion () const
Public Member Functions inherited from SchedulerCmdLineOptions
SchedulerCmdLineOptions ()
virtual ~SchedulerCmdLineOptions ()
virtual bool isMachineFileDefined () const
virtual std::string machineFile () const
virtual bool isOutputFileDefined () const
virtual std::string outputFile () const
virtual int schedulingWindowSize () const
virtual bool useRestrictedAliasAnalyzer () const
virtual bool renameRegisters () const
bool enableStackAA () const
bool enableOffsetAA () const
bool printResourceConstraints () const
virtual int ifConversionThreshold () const
virtual bool dumpIfConversionCFGs () const
virtual int lowMemModeThreshold () const
virtual bool isLoopOptDefined () const
virtual int bypassDistance () const
virtual int noDreBypassDistance () const
virtual int operandShareDistance () const
virtual bool killDeadResults () const
virtual FunctionNameList * noaliasFunctions () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Static Private Attributes
static const std::string SWL_EMULATION_LIB = "emulation"
static const std::string SWS_EMULATION_LIB = "e"
static const std::string SWL_DEBUG_FLAG = "debug"
static const std::string SWL_OPT_LEVEL = "optimize"
static const std::string SWS_OPT_LEVEL = "O"
static const std::string SWL_PRIMARY_FUNCTIONS
static const std::string SWS_PRIMARY_FUNCTIONS = "p"
static const std::string SWL_EXPERIMENTAL_REGALLOC
static const std::string VERBOSE_SWITCH = "verbose"
Switch for verbose output listing scheduler modules.
static const std::string DISABLE_LLVMAA = "disable-llvmaa"
static const std::string CONSERVATIVE_PRE_RA_SCHEDULER
static const std::string LLVM_USER_ARGS = "llvm-args"
static const std::string DISABLE_DSF = "disable-dsf"
static const std::string DISABLE_ADDRESS_SPACE_AA = "disable-as-aa"
static const std::string SWL_DUMP_DDGS_DOT = "dump-ddgs-dot"
static const std::string SWL_DUMP_DDGS_XML = "dump-ddgs-xml"
static const std::string SWL_SAVE_BACKEND_PLUGIN
static const std::string SWL_BU_SCHEDULER
static const std::string SWL_BUBBLEFISH2_SCHEDULER
static const std::string SWL_TD_SCHEDULER = "td-scheduler"
static const std::string SWL_USE_OLD_BACKEND_SOURCES
static const std::string SWL_TEMP_DIR = "temp-dir"
static const std::string SWL_ENABLE_VECTOR_BACKEND
static const std::string SWL_WORK_ITEM_AA_FILE
static const std::string SWL_ANALYZE_INSTRUCTION_PATTERNS
static const std::string SWL_BACKEND_CACHE_DIR
static const std::string SWL_INIT_SP = "init-sp"
static const std::string SWL_DATA_START = "data-start"
static const std::string USAGE
static const std::string SWL_PRINT_INLINE_ASM_WARNINGS
static const std::string SWL_GEN_PLUGIN_ONLY
static const std::string SWL_DISABLE_HWLOOPS
static const std::string SWL_ASSUME_ADF_STACKALIGNMENT
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line options class for the llvm-tce compiler CLI.
Definition at line 51 of file LLVMTCECmdLineOptions.hh.
Constructor & Destructor Documentation
LLVMTCECmdLineOptions()
LLVMTCECmdLineOptions::LLVMTCECmdLineOptions ()
Constructor.
Definition at line 98 of file LLVMTCECmdLineOptions.cc.
{
    addOption(
        new StringCmdLineOptionParser(
            SWL_EMULATION_LIB, "Emulation library bitcode file.",
            SWS_EMULATION_LIB));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_OPT_LEVEL, "Optimization level (0-2)",
            SWS_OPT_LEVEL));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DEBUG_FLAG, "Print LLVM debug data."));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_PRIMARY_FUNCTIONS,
            "List of function names that should be scheduled with "
            "the primary scheduler config (-c). Other functions are scheduled "
            "with the secondary config (-s).",
            SWS_PRIMARY_FUNCTIONS));
    addOption(
        new BoolCmdLineOptionParser(
            VERBOSE_SWITCH, "The verbose switch", "v"));
    addOption(
        new BoolCmdLineOptionParser(
            DISABLE_LLVMAA, "Disable use of LLVM Alias Analysis", DISABLE_LLVMAA));
    addOption(
        new BoolCmdLineOptionParser(
            DISABLE_ADDRESS_SPACE_AA,
            "Disable use of Address Space Alias Analysis",
            DISABLE_ADDRESS_SPACE_AA));
    addOption(
        new BoolCmdLineOptionParser(
            DISABLE_DSF, "Disable post-pass delay slot filler optimizer.",
            DISABLE_DSF));
    addOption(
        new BoolCmdLineOptionParser(
            CONSERVATIVE_PRE_RA_SCHEDULER,
            "Conservative pre-ra-scheduler. May decrease register usage but "
            "limit ILP. good for machines with low amount of registers."));
    addOption(new StringCmdLineOptionParser(
        LLVM_USER_ARGS, "Parameters to pass to LLVM"));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DUMP_DDGS_DOT,
            "Dump DDGs in dot format before and after scheduling."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DUMP_DDGS_XML,
            "Dump DDGs in XML format before and after scheduling."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_SAVE_BACKEND_PLUGIN,
            "Save the generated backend plugin for the architecture. "
            "This avoid the regeneration of the backend plugin when calling "
            "tcecc for the same architecture."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_BU_SCHEDULER,
            "Use an experiment Bottom Up scheduler."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_BUBBLEFISH2_SCHEDULER,
            "Use an experimental Bubblefish instructionscheduler v2."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_TD_SCHEDULER,
            "Use the old top-down instruction scheduler(previous default)."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_USE_OLD_BACKEND_SOURCES,
            "Use the existing backend sources from the given temporary directory."));
    addOption(
        new StringCmdLineOptionParser(
            SWL_TEMP_DIR,
            "The temporary directory to use for files needed during the code generation."));
    addOption(
        new StringCmdLineOptionParser(
            SWL_WORK_ITEM_AA_FILE,
            "The filename with Work Item Alias Analysis - this is filled automatically "
            "if tcecc finds path to installed pocl."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_ENABLE_VECTOR_BACKEND,
            "Enable backend support for vector registers split between multiple RF's"));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_ANALYZE_INSTRUCTION_PATTERNS,
            "Analyze the instruction patterns after instruction selection."));
    addOption(
        new StringCmdLineOptionParser(
            SWL_BACKEND_CACHE_DIR,
            "The directory to use for caching LLVM backend plugins."));
    addOption(
        new UnsignedIntegerCmdLineOptionParser(
            SWL_INIT_SP,
            "Initialize the stack pointer of the program to the given value."));
    addOption(new StringListCmdLineOptionParser(
        SWL_DATA_START, "Override the global data start address."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_PRINT_INLINE_ASM_WARNINGS,
            "Prints warnings from inline assembly parsing. Default is off."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_GEN_PLUGIN_ONLY,
            "Generates LLVM backend plugin for target machine without tpef "
            "generation."));
    addOption(new BoolCmdLineOptionParser(
        SWL_DISABLE_HWLOOPS,
        "Do not use hardware loops even though the processor supports them."));
    addOption(
    new BoolCmdLineOptionParser(
            SWL_ASSUME_ADF_STACKALIGNMENT,
            "Assume size of stackalignment based on biggest memory operations in the adf."));
}
References CmdLineParser::addOption(), CONSERVATIVE_PRE_RA_SCHEDULER, DISABLE_ADDRESS_SPACE_AA, DISABLE_DSF, DISABLE_LLVMAA, LLVM_USER_ARGS, SWL_ANALYZE_INSTRUCTION_PATTERNS, SWL_ASSUME_ADF_STACKALIGNMENT, SWL_BACKEND_CACHE_DIR, SWL_BU_SCHEDULER, SWL_BUBBLEFISH2_SCHEDULER, SWL_DATA_START, SWL_DEBUG_FLAG, SWL_DISABLE_HWLOOPS, SWL_DUMP_DDGS_DOT, SWL_DUMP_DDGS_XML, SWL_EMULATION_LIB, SWL_ENABLE_VECTOR_BACKEND, SWL_GEN_PLUGIN_ONLY, SWL_INIT_SP, SWL_OPT_LEVEL, SWL_PRIMARY_FUNCTIONS, SWL_PRINT_INLINE_ASM_WARNINGS, SWL_SAVE_BACKEND_PLUGIN, SWL_TD_SCHEDULER, SWL_TEMP_DIR, SWL_USE_OLD_BACKEND_SOURCES, SWL_WORK_ITEM_AA_FILE, SWS_EMULATION_LIB, SWS_OPT_LEVEL, SWS_PRIMARY_FUNCTIONS, and VERBOSE_SWITCH.
~LLVMTCECmdLineOptions()
LLVMTCECmdLineOptions::~LLVMTCECmdLineOptions ()
Destructor.
Definition at line 242 of file LLVMTCECmdLineOptions.cc.
{
}
Member Function Documentation
analyzeInstructionPatterns()
bool LLVMTCECmdLineOptions::analyzeInstructionPatterns () const
Definition at line 414 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_ANALYZE_INSTRUCTION_PATTERNS)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_ANALYZE_INSTRUCTION_PATTERNS.
assumeADFStackAlignment()
bool LLVMTCECmdLineOptions::assumeADFStackAlignment () const
Definition at line 511 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_ASSUME_ADF_STACKALIGNMENT)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_ASSUME_ADF_STACKALIGNMENT.
Referenced by LLVMBackend::compile().
backendCacheDir()
std::string LLVMTCECmdLineOptions::backendCacheDir () const
Definition at line 419 of file LLVMTCECmdLineOptions.cc.
{
    if (findOption(SWL_BACKEND_CACHE_DIR)->isDefined())
        return findOption(SWL_BACKEND_CACHE_DIR)->String();
    return Environment::llvmtceCachePath();
}
References CmdLineParser::findOption(), Environment::llvmtceCachePath(), CmdLineOptionParser::String(), and SWL_BACKEND_CACHE_DIR.
Referenced by LLVMBackend::LLVMBackend().
conservativePreRAScheduler()
bool LLVMTCECmdLineOptions::conservativePreRAScheduler () const
Definition at line 339 of file LLVMTCECmdLineOptions.cc.
{
    if (findOption(CONSERVATIVE_PRE_RA_SCHEDULER)->isDefined() &&
        findOption(CONSERVATIVE_PRE_RA_SCHEDULER)->isFlagOn()) {
        return true;
    }
    return false;
}
References CONSERVATIVE_PRE_RA_SCHEDULER, and CmdLineParser::findOption().
Referenced by llvm::TCETargetLowering::TCETargetLowering().
dataStartAddress()
uint64_t LLVMTCECmdLineOptions::dataStartAddress (TTAMachine::AddressSpace & aSpace) const
Definition at line 462 of file LLVMTCECmdLineOptions.cc.
{
    CmdLineOptionParser* opts = findOption(SWL_DATA_START);
    if (opts->isDefined()) {
        int size = opts->listSize();
        if (size == 1) {
            uint64_t tmp = Conversion::toUnsignedLong(opts->String(1));
            return tmp;
        }
        if (size % 2 != 0) {
            abortWithError(
                "ERROR: Data-start option must be either just the start"
                " of the default address space (unsigned integer),"
                " or a list consisting of pairs:"
                " <Address-Space Name>,<Address-Space Start>")
        }
        for (int i = 1; i <= size; i += 2) {
            TCEString as_name = opts->String(i);
            if (as_name == aSpace.name()) {
                return Conversion::toUnsignedLong(opts->String(i + 1));
            }
        }
    }
    abortWithError(
        "ERROR: Failed parsing the data-start-option."
        " Data-start option must be either just the start"
        " of the default address space (unsigned integer),"
        " or a list consisting of pairs:"
        " <Address-Space Name>,<Address-Space Start>")
}
References abortWithError, CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), CmdLineOptionParser::listSize(), TTAMachine::Component::name(), CmdLineOptionParser::String(), SWL_DATA_START, and Conversion::toUnsignedLong().
Referenced by llvm::LLVMTCEBuilder::dataEnd().
debugFlag()
bool LLVMTCECmdLineOptions::debugFlag () const
Returns true if the debug flag option was given.
Returns
True, if debug mode switch was given.
Definition at line 303 of file LLVMTCECmdLineOptions.cc.
{
    if (findOption(SWL_DEBUG_FLAG)->isDefined() &&
        findOption(SWL_DEBUG_FLAG)->isFlagOn()) {
        return true;
    }
    return false;
}
References CmdLineParser::findOption(), and SWL_DEBUG_FLAG.
disableAddressSpaceAA()
bool LLVMTCECmdLineOptions::disableAddressSpaceAA () const
Definition at line 319 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(DISABLE_ADDRESS_SPACE_AA)->isDefined();
}
References DISABLE_ADDRESS_SPACE_AA, CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
Referenced by DataDependenceGraphBuilder::memoryCategory().
disableDelaySlotFiller()
bool LLVMTCECmdLineOptions::disableDelaySlotFiller () const
Definition at line 324 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(DISABLE_DSF)->isDefined();
}
References DISABLE_DSF, CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
Referenced by llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder().
disableHWLoops()
bool LLVMTCECmdLineOptions::disableHWLoops () const
Definition at line 506 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_DISABLE_HWLOOPS)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_DISABLE_HWLOOPS.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
disableLLVMAA()
bool LLVMTCECmdLineOptions::disableLLVMAA () const virtual
Definition at line 314 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(DISABLE_LLVMAA)->isDefined();
}
References DISABLE_LLVMAA, CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
Referenced by DataDependenceGraphBuilder::DataDependenceGraphBuilder(), and DataDependenceGraphBuilder::DataDependenceGraphBuilder().
dumpDDGsDot()
bool LLVMTCECmdLineOptions::dumpDDGsDot () const virtual
Definition at line 359 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_DUMP_DDGS_DOT)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_DUMP_DDGS_DOT.
Referenced by BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BBSchedulerController::handleProcedure(), BF2Scheduler::scheduleDDG(), and BasicBlockScheduler::scheduleOperation().
dumpDDGsXML()
bool LLVMTCECmdLineOptions::dumpDDGsXML () const virtual
Definition at line 364 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_DUMP_DDGS_XML)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_DUMP_DDGS_XML.
Referenced by BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BBSchedulerController::handleProcedure(), and BF2Scheduler::scheduleDDG().
generatePluginOnly()
bool LLVMTCECmdLineOptions::generatePluginOnly () const
Definition at line 500 of file LLVMTCECmdLineOptions.cc.
{
    return (findOption(SWL_GEN_PLUGIN_ONLY)->isDefined() &&
        findOption(SWL_GEN_PLUGIN_ONLY)->isFlagOn());
}
References CmdLineParser::findOption(), and SWL_GEN_PLUGIN_ONLY.
getLLVMargv()
std::string LLVMTCECmdLineOptions::getLLVMargv () const virtual
Definition at line 348 of file LLVMTCECmdLineOptions.cc.
{
    if (!findOption(LLVM_USER_ARGS)->isDefined()) {
        return "llvm-tce --no-stack-coloring";
    } else {
        std::string argv = "llvm-tce --no-stack-coloring " +
                           findOption(LLVM_USER_ARGS)->String();
        return argv;
    }
}
References CmdLineParser::findOption(), LLVM_USER_ARGS, and CmdLineOptionParser::String().
initialStackPointerValue()
uint64_t LLVMTCECmdLineOptions::initialStackPointerValue () const
Definition at line 431 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_INIT_SP)->unsignedInteger();
}
References CmdLineParser::findOption(), SWL_INIT_SP, and CmdLineOptionParser::unsignedInteger().
Referenced by LLVMBackend::compile().
isDataStartAddressSet()
bool LLVMTCECmdLineOptions::isDataStartAddressSet (TTAMachine::AddressSpace & aSpace) const
Definition at line 436 of file LLVMTCECmdLineOptions.cc.
{
    CmdLineOptionParser* opts = findOption(SWL_DATA_START);
    if (opts->isDefined()) {
        int size = opts->listSize();
        if (size == 1) {
            return true;
        }
        if (size % 2 != 0) {
            abortWithError(
                "ERROR: Data-start option must be either just the start"
                " of the default address space (unsigned integer),"
                " or a list consisting of pairs:"
                " <Address-Space Name>,<Address-Space Start>")
        }
        for (int i = 1; i <= size; i += 2) {
            TCEString as_name = opts->String(i);
            if (as_name == aSpace.name()) {
                return true;
            }
        }
    }
    return false;
}
References abortWithError, CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), CmdLineOptionParser::listSize(), TTAMachine::Component::name(), CmdLineOptionParser::String(), and SWL_DATA_START.
Referenced by llvm::LLVMTCEBuilder::dataEnd().
isInitialStackPointerValueSet()
bool LLVMTCECmdLineOptions::isInitialStackPointerValueSet () const
Definition at line 426 of file LLVMTCECmdLineOptions.cc.
{
   return findOption(SWL_INIT_SP)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_INIT_SP.
Referenced by LLVMBackend::compile().
isOptLevelDefined()
bool LLVMTCECmdLineOptions::isOptLevelDefined () const
Returns true if optimization level switch was given.
Returns
True, if optimization level was given on command line.
Definition at line 281 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWS_OPT_LEVEL)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWS_OPT_LEVEL.
isStandardEmulationLibDefined()
bool LLVMTCECmdLineOptions::isStandardEmulationLibDefined () const
Definition at line 271 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWS_EMULATION_LIB)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWS_EMULATION_LIB.
isVerboseSwitchDefined()
bool LLVMTCECmdLineOptions::isVerboseSwitchDefined () const virtual
Return true if the verbose switch was defined in the command line.
Returns
True if the verbose switch was defined in the command line.
Reimplemented from CmdLineOptions.
Definition at line 334 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(VERBOSE_SWITCH)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and VERBOSE_SWITCH.
isWorkItemAAFileDefined()
bool LLVMTCECmdLineOptions::isWorkItemAAFileDefined () const
Definition at line 404 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_WORK_ITEM_AA_FILE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_WORK_ITEM_AA_FILE.
Referenced by LLVMBackend::compile().
optLevel()
int LLVMTCECmdLineOptions::optLevel () const
Returns optimization level defined with the -O switch.
Returns
Optimization level.
Definition at line 292 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWS_OPT_LEVEL)->integer();
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWS_OPT_LEVEL.
Referenced by llvm::LLVMTCEIRBuilder::writeMachineFunction().
primaryFunctions()
FunctionNameList * LLVMTCECmdLineOptions::primaryFunctions () const virtual
Returns the list of "primary functions" that should be scheduled with the primary scheduling conf.
Rest of the functions are scheduled with the scheduling config given with -s.
Definition at line 254 of file LLVMTCECmdLineOptions.cc.
{
    FunctionNameList* funcs = new FunctionNameList();
    CmdLineOptionParser* opt = findOption(SWS_PRIMARY_FUNCTIONS);
    if (opt == NULL)
        return funcs;
    for (int i = 1; i <= opt->listSize(); ++i) {
        funcs->insert(opt->String(i));
    }
    return funcs;
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), CmdLineOptionParser::String(), and SWS_PRIMARY_FUNCTIONS.
Referenced by llvm::LLVMTCEIRBuilder::isHotFunction().
printInlineAsmWarnings()
bool LLVMTCECmdLineOptions::printInlineAsmWarnings () const
Definition at line 494 of file LLVMTCECmdLineOptions.cc.
{
    return (findOption(SWL_PRINT_INLINE_ASM_WARNINGS)->isDefined() &&
        findOption(SWL_PRINT_INLINE_ASM_WARNINGS)->isFlagOn());
}
References CmdLineParser::findOption(), and SWL_PRINT_INLINE_ASM_WARNINGS.
Referenced by llvm::LLVMTCEBuilder::emitInlineAsm().
printVersion()
virtual void LLVMTCECmdLineOptions::printVersion () const inline virtual
Print the version of the user interface.
Reimplemented from SchedulerCmdLineOptions.
Definition at line 110 of file LLVMTCECmdLineOptions.hh.
{
        std::cout
            << "llvm-tce - TCE LLVM code generator "
            << Application::TCEVersionString()
            << std::endl;
    }
References Application::TCEVersionString().
saveBackendPlugin()
bool LLVMTCECmdLineOptions::saveBackendPlugin () const
Definition at line 369 of file LLVMTCECmdLineOptions.cc.
{
    return !(findOption(SWL_SAVE_BACKEND_PLUGIN)->isDefined() &&
             !findOption(SWL_SAVE_BACKEND_PLUGIN)->isFlagOn());
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), CmdLineOptionParser::isFlagOn(), and SWL_SAVE_BACKEND_PLUGIN.
Referenced by LLVMBackend::compile().
standardEmulationLib()
std::string LLVMTCECmdLineOptions::standardEmulationLib () const
Definition at line 266 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWS_EMULATION_LIB)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWS_EMULATION_LIB.
tempDir()
TCEString LLVMTCECmdLineOptions::tempDir () const
Definition at line 394 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_TEMP_DIR)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_TEMP_DIR.
useBubbleFish2Scheduler()
bool LLVMTCECmdLineOptions::useBubbleFish2Scheduler () const
Definition at line 379 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_BUBBLEFISH2_SCHEDULER)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_BUBBLEFISH2_SCHEDULER.
Referenced by BBSchedulerController::handleBasicBlock().
useBUScheduler()
bool LLVMTCECmdLineOptions::useBUScheduler () const
Definition at line 374 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_BU_SCHEDULER)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_BU_SCHEDULER.
Referenced by BBSchedulerController::handleBasicBlock().
useOldBackendSources()
bool LLVMTCECmdLineOptions::useOldBackendSources () const
Definition at line 389 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_USE_OLD_BACKEND_SOURCES)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_USE_OLD_BACKEND_SOURCES.
Referenced by LLVMBackend::createPlugin().
useTDScheduler()
bool LLVMTCECmdLineOptions::useTDScheduler () const
Definition at line 384 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_TD_SCHEDULER)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_TD_SCHEDULER.
Referenced by BBSchedulerController::handleBasicBlock().
useVectorBackend()
bool LLVMTCECmdLineOptions::useVectorBackend () const
Definition at line 399 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_ENABLE_VECTOR_BACKEND)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_ENABLE_VECTOR_BACKEND.
workItemAAFile()
std::string LLVMTCECmdLineOptions::workItemAAFile () const
Definition at line 409 of file LLVMTCECmdLineOptions.cc.
{
    return findOption(SWL_WORK_ITEM_AA_FILE)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_WORK_ITEM_AA_FILE.
Referenced by LLVMBackend::compile().
Member Data Documentation
CONSERVATIVE_PRE_RA_SCHEDULER
const std::string LLVMTCECmdLineOptions::CONSERVATIVE_PRE_RA_SCHEDULER static private
Initial value:
=
    "conservative-pre-ra-scheduler"
Definition at line 130 of file LLVMTCECmdLineOptions.hh.
Referenced by conservativePreRAScheduler(), and LLVMTCECmdLineOptions().
DISABLE_ADDRESS_SPACE_AA
const std::string LLVMTCECmdLineOptions::DISABLE_ADDRESS_SPACE_AA = "disable-as-aa" static private
Definition at line 133 of file LLVMTCECmdLineOptions.hh.
Referenced by disableAddressSpaceAA(), and LLVMTCECmdLineOptions().
DISABLE_DSF
const std::string LLVMTCECmdLineOptions::DISABLE_DSF = "disable-dsf" static private
Definition at line 132 of file LLVMTCECmdLineOptions.hh.
Referenced by disableDelaySlotFiller(), and LLVMTCECmdLineOptions().
DISABLE_LLVMAA
const std::string LLVMTCECmdLineOptions::DISABLE_LLVMAA = "disable-llvmaa" static private
Definition at line 129 of file LLVMTCECmdLineOptions.hh.
Referenced by disableLLVMAA(), and LLVMTCECmdLineOptions().
LLVM_USER_ARGS
const std::string LLVMTCECmdLineOptions::LLVM_USER_ARGS = "llvm-args" static private
Definition at line 131 of file LLVMTCECmdLineOptions.hh.
Referenced by getLLVMargv(), and LLVMTCECmdLineOptions().
SWL_ANALYZE_INSTRUCTION_PATTERNS
const std::string LLVMTCECmdLineOptions::SWL_ANALYZE_INSTRUCTION_PATTERNS static private
Initial value:
=
    "analyze-instruction-patterns"
Definition at line 144 of file LLVMTCECmdLineOptions.hh.
Referenced by analyzeInstructionPatterns(), and LLVMTCECmdLineOptions().
SWL_ASSUME_ADF_STACKALIGNMENT
const std::string LLVMTCECmdLineOptions::SWL_ASSUME_ADF_STACKALIGNMENT static private
Initial value:
=
    "assume-adf-stackalignment"
Definition at line 152 of file LLVMTCECmdLineOptions.hh.
Referenced by assumeADFStackAlignment(), and LLVMTCECmdLineOptions().
SWL_BACKEND_CACHE_DIR
const std::string LLVMTCECmdLineOptions::SWL_BACKEND_CACHE_DIR static private
Initial value:
=
    "backend-cache-dir"
Definition at line 145 of file LLVMTCECmdLineOptions.hh.
Referenced by backendCacheDir(), and LLVMTCECmdLineOptions().
SWL_BU_SCHEDULER
const std::string LLVMTCECmdLineOptions::SWL_BU_SCHEDULER static private
Initial value:
=
    "bottom-up-scheduler"
Definition at line 137 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and useBUScheduler().
SWL_BUBBLEFISH2_SCHEDULER
const std::string LLVMTCECmdLineOptions::SWL_BUBBLEFISH2_SCHEDULER static private
Initial value:
=
    "bubblefish2-scheduler"
Definition at line 138 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and useBubbleFish2Scheduler().
SWL_DATA_START
const std::string LLVMTCECmdLineOptions::SWL_DATA_START = "data-start" static private
Definition at line 147 of file LLVMTCECmdLineOptions.hh.
Referenced by dataStartAddress(), isDataStartAddressSet(), and LLVMTCECmdLineOptions().
SWL_DEBUG_FLAG
const std::string LLVMTCECmdLineOptions::SWL_DEBUG_FLAG = "debug" static private
Definition at line 121 of file LLVMTCECmdLineOptions.hh.
Referenced by debugFlag(), and LLVMTCECmdLineOptions().
SWL_DISABLE_HWLOOPS
const std::string LLVMTCECmdLineOptions::SWL_DISABLE_HWLOOPS static private
Initial value:
=
    "disable-hwloops"
Definition at line 151 of file LLVMTCECmdLineOptions.hh.
Referenced by disableHWLoops(), and LLVMTCECmdLineOptions().
SWL_DUMP_DDGS_DOT
const std::string LLVMTCECmdLineOptions::SWL_DUMP_DDGS_DOT = "dump-ddgs-dot" static private
Definition at line 134 of file LLVMTCECmdLineOptions.hh.
Referenced by dumpDDGsDot(), and LLVMTCECmdLineOptions().
SWL_DUMP_DDGS_XML
const std::string LLVMTCECmdLineOptions::SWL_DUMP_DDGS_XML = "dump-ddgs-xml" static private
Definition at line 135 of file LLVMTCECmdLineOptions.hh.
Referenced by dumpDDGsXML(), and LLVMTCECmdLineOptions().
SWL_EMULATION_LIB
const std::string LLVMTCECmdLineOptions::SWL_EMULATION_LIB = "emulation" static private
Definition at line 119 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions().
SWL_ENABLE_VECTOR_BACKEND
const std::string LLVMTCECmdLineOptions::SWL_ENABLE_VECTOR_BACKEND static private
Initial value:
=
    "vector-backend"
Definition at line 142 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and useVectorBackend().
SWL_EXPERIMENTAL_REGALLOC
const std::string LLVMTCECmdLineOptions::SWL_EXPERIMENTAL_REGALLOC static private
Definition at line 126 of file LLVMTCECmdLineOptions.hh.
SWL_GEN_PLUGIN_ONLY
const std::string LLVMTCECmdLineOptions::SWL_GEN_PLUGIN_ONLY static private
Initial value:
=
    "gen-plugin-only"
Definition at line 150 of file LLVMTCECmdLineOptions.hh.
Referenced by generatePluginOnly(), and LLVMTCECmdLineOptions().
SWL_INIT_SP
const std::string LLVMTCECmdLineOptions::SWL_INIT_SP = "init-sp" static private
Definition at line 146 of file LLVMTCECmdLineOptions.hh.
Referenced by initialStackPointerValue(), isInitialStackPointerValueSet(), and LLVMTCECmdLineOptions().
SWL_OPT_LEVEL
const std::string LLVMTCECmdLineOptions::SWL_OPT_LEVEL = "optimize" static private
Definition at line 122 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions().
SWL_PRIMARY_FUNCTIONS
const std::string LLVMTCECmdLineOptions::SWL_PRIMARY_FUNCTIONS static private
Initial value:
=
    "primary-functions"
Definition at line 124 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions().
SWL_PRINT_INLINE_ASM_WARNINGS
const std::string LLVMTCECmdLineOptions::SWL_PRINT_INLINE_ASM_WARNINGS static private
Initial value:
=
    "print-inline-asm-warnings"
Definition at line 149 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and printInlineAsmWarnings().
SWL_SAVE_BACKEND_PLUGIN
const std::string LLVMTCECmdLineOptions::SWL_SAVE_BACKEND_PLUGIN static private
Initial value:
=
    "save-backend-plugin"
Definition at line 136 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and saveBackendPlugin().
SWL_TD_SCHEDULER
const std::string LLVMTCECmdLineOptions::SWL_TD_SCHEDULER = "td-scheduler" static private
Definition at line 139 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and useTDScheduler().
SWL_TEMP_DIR
const std::string LLVMTCECmdLineOptions::SWL_TEMP_DIR = "temp-dir" static private
Definition at line 141 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and tempDir().
SWL_USE_OLD_BACKEND_SOURCES
const std::string LLVMTCECmdLineOptions::SWL_USE_OLD_BACKEND_SOURCES static private
Initial value:
=
    "use-old-backend-src"
Definition at line 140 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and useOldBackendSources().
SWL_WORK_ITEM_AA_FILE
const std::string LLVMTCECmdLineOptions::SWL_WORK_ITEM_AA_FILE static private
Initial value:
=
    "wi-aa-filename"
Definition at line 143 of file LLVMTCECmdLineOptions.hh.
Referenced by isWorkItemAAFileDefined(), LLVMTCECmdLineOptions(), and workItemAAFile().
SWS_EMULATION_LIB
const std::string LLVMTCECmdLineOptions::SWS_EMULATION_LIB = "e" static private
Definition at line 120 of file LLVMTCECmdLineOptions.hh.
Referenced by isStandardEmulationLibDefined(), LLVMTCECmdLineOptions(), and standardEmulationLib().
SWS_OPT_LEVEL
const std::string LLVMTCECmdLineOptions::SWS_OPT_LEVEL = "O" static private
Definition at line 123 of file LLVMTCECmdLineOptions.hh.
Referenced by isOptLevelDefined(), LLVMTCECmdLineOptions(), and optLevel().
SWS_PRIMARY_FUNCTIONS
const std::string LLVMTCECmdLineOptions::SWS_PRIMARY_FUNCTIONS = "p" static private
Definition at line 125 of file LLVMTCECmdLineOptions.hh.
Referenced by LLVMTCECmdLineOptions(), and primaryFunctions().
USAGE
const std::string LLVMTCECmdLineOptions::USAGE static private
Initial value:
=
    "Usage: llvm-tce [OPTION]... BYTECODE\n"
    "Compile LLVM bytecode for target TCE architecture.\n"
Definition at line 148 of file LLVMTCECmdLineOptions.hh.
VERBOSE_SWITCH
const std::string LLVMTCECmdLineOptions::VERBOSE_SWITCH = "verbose" static private
Switch for verbose output listing scheduler modules.
Definition at line 128 of file LLVMTCECmdLineOptions.hh.
Referenced by isVerboseSwitchDefined(), and LLVMTCECmdLineOptions().
The documentation for this class was generated from the following files:
LLVMTCECmdLineOptions.hh
LLVMTCECmdLineOptions.cc