OpenASIP: ProximRFDetailsCmd Class Reference
ProximRFDetailsCmd Class Reference
#include <ProximRFDetailsCmd.hh>
Public Member Functions
ProximRFDetailsCmd (const TTAMachine::RegisterFile &rf)
virtual ~ProximRFDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::RegisterFile & rf_
Register file to display.
Detailed Description
Command for displaying register file details in the machine window component details pane.
Definition at line 46 of file ProximRFDetailsCmd.hh.
Constructor & Destructor Documentation
ProximRFDetailsCmd()
ProximRFDetailsCmd::ProximRFDetailsCmd (const TTAMachine::RegisterFile & rf)
The Constructor.
Parameters
rf Register file to display.
Definition at line 54 of file ProximRFDetailsCmd.cc.
                                                                       :
    ComponentCommand(), rf_(rf) {
}
~ProximRFDetailsCmd()
ProximRFDetailsCmd::~ProximRFDetailsCmd () virtual
The Destructor.
Definition at line 62 of file ProximRFDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximRFDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 69 of file ProximRFDetailsCmd.cc.
                       {
    string rfName = rf_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    MachineState& machineState = ProximToolbox::frontend()->machineState();
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_RF_LABEL);
    machineWin->appendDetails(rfName + "\n\n");
    // Append registers to the details widget.
    machineWin->appendDetails(
        ProximConstants::MACH_WIN_REGISTERS_TITLE + "\n");
    RegisterFileState& rfState = machineState.registerFileState(rfName);
    for (unsigned i = 0; i < rfState.registerCount(); i++) {
        machineWin->appendDetails("  " + Conversion::toString(i) + ":\t");
        int registerValue = rfState.registerState(i).value().unsignedValue();
        machineWin->appendDetails(Conversion::toString(registerValue) + "\n");
    }
    // Append register access statistics to the utilization widget.
    machineWin->appendUtilizationData("Register access statistics:\n\n");
    int usedRegCount = 0;
    for (unsigned i = 0; i < rfState.registerCount(); i++) {
        ClockCycleCount readCount = stats.registerReads(rfName, i);
        ClockCycleCount writeCount = stats.registerWrites(rfName, i);
        if (readCount > 0 || writeCount > 0) {
            usedRegCount++;
        }
        machineWin->appendUtilizationData(
            Conversion::toString(i) +  + ":  " +
            Conversion::toString(readCount) + " reads, " +
            Conversion::toString(writeCount) + " writes.\n");
    }
    machineWin->appendUtilizationData(
        "\nTotal of " + Conversion::toString(usedRegCount) +
        " registers used.");
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximMachineStateWindow::appendUtilizationData(), ProximToolbox::frontend(), ProximConstants::MACH_WIN_REGISTERS_TITLE, ProximConstants::MACH_WIN_RF_LABEL, SimulatorFrontend::machineState(), ProximToolbox::machineStateWindow(), TTAMachine::Component::name(), RegisterFileState::registerCount(), MachineState::registerFileState(), UtilizationStats::registerReads(), RegisterFileState::registerState(), UtilizationStats::registerWrites(), rf_, Conversion::toString(), SimValue::unsignedValue(), SimulatorFrontend::utilizationStatistics(), and RegisterState::value().
Member Data Documentation
rf_
const TTAMachine::RegisterFile& ProximRFDetailsCmd::rf_ private
Register file to display.
Definition at line 53 of file ProximRFDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximRFDetailsCmd.hh
ProximRFDetailsCmd.cc