OpenASIP: OptionsDialog Class Reference
OptionsDialog Class Reference
#include <OptionsDialog.hh>
Classes
struct Shortcut
Public Member Functions
OptionsDialog (wxWindow *parent, GUIOptions &options, CommandRegistry &commandRegisry)
virtual ~OptionsDialog ()
Protected Member Functions
void addPage (wxPanel *page, const wxString &title)
virtual void readOptions ()
virtual void writeOptions ()
Protected Attributes
wxNotebook * notebook_
Notebook containing dialog pages.
Private Types
enum {
ID_NOTEBOOK = 10000 , ID_HELP , ID_BROWSE , ID_KB_SC_LIST ,
ID_EDIT_KB_SC , ID_DELETE_KB_SC , ID_TOOLBAR_LIST , ID_TOOL_DOWN ,
ID_TOOL_UP , ID_TOOL_INSERT , ID_TOOL_REMOVE , ID_COMMAND_LIST ,
ID_TOOLBAR_CONTENTS , ID_TEXT , ID_LABEL_TOOLBAR_CONTENTS
}
Private Member Functions
virtual wxSizer * createContents (wxWindow *parent, bool callFit, bool set_sizer)
void readCommands ()
void initialize ()
void onShortcutSelection (wxListEvent &event)
void onToolbarSelection (wxListEvent &event)
void onCommandSelection (wxListEvent &event)
void onDeleteShortcut (wxCommandEvent &event)
void onActivateShortcut (wxListEvent &event)
void onEditShortcut (wxCommandEvent &event)
void onShortcutRightClick (wxListEvent &event)
void onInsertTool (wxCommandEvent &event)
void onRemoveTool (wxCommandEvent &event)
void onMoveTool (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void setTexts ()
virtual bool TransferDataToWindow ()
wxSizer * createKBShortcutPage (wxWindow *parent, bool callFit, bool set_sizer)
wxSizer * createToolbarPage (wxWindow *parent, bool callFit, bool set_sizer)
Shortcut * selectedShortcut ()
Private Attributes
wxWindow * parent_
parent window of the dialog
GUIOptions & options_
current editor options
wxListCtrl * shortcutList_
Keyboard shortcut list control.
wxListCtrl * toolbarList_
Toolbar buttons list control.
wxListCtrl * commandList_
List control for commands not in the toolbar.
int choice_
std::vector< Shortcut * > shortcuts_
Keyboard shortcuts.
std::vector< std::string > toolbar_
Toolbar buttons and separators.
CommandRegistry & commandRegistry_
Command registry containing available commands for shortcuts.
Static Private Attributes
static const wxString COMMAND_COLUMN_TITLE = _T("Command")
Title of the keyboard shortcut list command name column.
static const wxString SHORTCUT_COLUMN_TITLE = _T("Shortcut")
Title of the keyboard shortcut list shortcut column.
static const wxString TOOLBAR_BUTTONS_COLUMN_TITLE = _T("Toolbar")
Title of the toolbar tab toolbar button list.
static const wxString AVAILABLE_COMMANDS_COLUMN_TITLE = _T("Commands")
Title of the toolbar tab available commands list.
static const wxString CONTENTS_ICONS = _T("Icons")
Text fot the toolbar contents choicer icon-mode item.
static const wxString CONTENTS_BOTH = _T("Both")
Text for the toolbar contents choicer icon&text mode item.
static const wxString CONTENTS_TEXT = _T("Text")
Text for the toolbar contents choicer text-mode item.
static const wxString EDIT_BUTTON_LABEL = _T("Edit...")
Label for Edit-button.
static const wxString DELETE_BUTTON_LABEL = _T("Delete")
Label for delete-button.
Detailed Description
Dialog for editing GUIOptions.
This class allows modification of options in the GUIOptions class. If an application uses custom options class derived from the GUIOptions class, this class can be used as a base class for the application specific options dialog. To customize the derived dialog, override readOptions and writeOptions. Controls for modifying the application specific options can be added by creating a wxPanel containing the controls, and adding it to the dialog as a tab using the addPage method.
Definition at line 60 of file OptionsDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NOTEBOOK
ID_HELP
ID_BROWSE
ID_KB_SC_LIST
ID_EDIT_KB_SC
ID_DELETE_KB_SC
ID_TOOLBAR_LIST
ID_TOOL_DOWN
ID_TOOL_UP
ID_TOOL_INSERT
ID_TOOL_REMOVE
ID_COMMAND_LIST
ID_TOOLBAR_CONTENTS
ID_TEXT
ID_LABEL_TOOLBAR_CONTENTS
Definition at line 141 of file OptionsDialog.hh.
         {
        ID_NOTEBOOK = 10000,
        ID_HELP,
        ID_BROWSE,
        ID_KB_SC_LIST,
        ID_EDIT_KB_SC,
        ID_DELETE_KB_SC,
        ID_TOOLBAR_LIST,
        ID_TOOL_DOWN,
        ID_TOOL_UP,
        ID_TOOL_INSERT,
        ID_TOOL_REMOVE,
        ID_COMMAND_LIST,
        ID_TOOLBAR_CONTENTS,
        ID_TEXT,
        ID_LABEL_TOOLBAR_CONTENTS
    };
Constructor & Destructor Documentation
OptionsDialog()
OptionsDialog::OptionsDialog (wxWindow * parent, GUIOptions & options, CommandRegistry & commandRegistry)
The Constructor.
Parameters
parent Parent window of the dialog.
options Options to be modified.
commandRegistry Command registry containing available commands.
Definition at line 118 of file OptionsDialog.cc.
                                     :
    wxDialog(parent, -1, _T(""), wxDefaultPosition, wxSize(500, 300),
             (wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)),
    parent_(parent), options_(options), shortcutList_(NULL),
    toolbarList_(NULL), commandList_(NULL), commandRegistry_(commandRegistry) {
    initialize();
    readCommands();
    readOptions();
    SetMinSize(wxSize(420, 300));
    notebook_ = dynamic_cast<wxNotebook*>(FindWindow(ID_NOTEBOOK));
}
~OptionsDialog()
OptionsDialog::~OptionsDialog () virtual
The Destructor.
Definition at line 140 of file OptionsDialog.cc.
{
#ifdef KB_SC_EDITING
    // delete shortcut list
    vector<Shortcut*>::iterator i = shortcuts_.begin();
    for (; i != shortcuts_.end(); i++) {
        delete (*i);
    }
    shortcuts_.clear();
#endif
}
References shortcuts_.
Member Function Documentation
addPage()
void OptionsDialog::addPage (wxPanel * page, const wxString & title) protected
Adds a new tab to the options dialog.
This function can be used to add tabs for modifying application specific options.
Parameters
page Tab to add.
title Title of the tab.
Definition at line 756 of file OptionsDialog.cc.
{
    page->Reparent(notebook_);
    notebook_->InsertPage(0, page, title, true);
}
References notebook_.
createContents()
wxSizer * OptionsDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private virtual
Creates the dialog contents.
This function was initially generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 772 of file OptionsDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxNotebook *item2 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxSize(570,-1), 0 );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item1 = new wxNotebookSizer( item2 );
#else
    wxWindow *item1 = item2;
#endif
#ifdef KB_SC_EDITING
    wxPanel *item4 = new wxPanel( item2, -1 );
    OptionsDialog::createKBShortcutPage( item4, true, true );
    item2->AddPage( item4, wxT("Keyboard Shortcuts") );
#endif
    wxPanel *item5 = new wxPanel( item2, -1 );
    OptionsDialog::createToolbarPage( item5, true, true );
    item2->AddPage( item5, wxT("Toolbar") );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item6 = new wxGridSizer( 2, 0, 0 );
    wxButton *item7 = new wxButton( parent, ID_HELP, wxT("&Help..."), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item6->Add( item8, 0, wxALL, 5 );
    item0->Add( item6, 0, wxGROW|wxLEFT|wxRIGHT, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References createKBShortcutPage(), createToolbarPage(), ID_HELP, and ID_NOTEBOOK.
Referenced by initialize().
createKBShortcutPage()
wxSizer * OptionsDialog::createKBShortcutPage (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the 'Keyboard Shotcut' page for the dialog.
This function was initially generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 836 of file OptionsDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_KB_SC_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item3 = new wxButton( parent, ID_EDIT_KB_SC, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_DELETE_KB_SC, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer) {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DELETE_KB_SC, ID_EDIT_KB_SC, and ID_KB_SC_LIST.
Referenced by createContents().
createToolbarPage()
wxSizer * OptionsDialog::createToolbarPage (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the 'Toolbar' page for the dialog.
This function was generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 877 of file OptionsDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 3, 0, 0 );
    item1->AddGrowableCol( 0 );
    item1->AddGrowableCol( 2 );
    item1->AddGrowableRow( 0 );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 1, 0, 0 );
    item2->AddGrowableCol( 0 );
    item2->AddGrowableRow( 0 );
    wxListCtrl *item3 = new wxListCtrl( parent, ID_TOOLBAR_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item2->Add( item3, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item5 = new wxButton( parent, ID_TOOL_UP, wxT("&Up"), wxDefaultPosition, wxSize(50,-1), 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, ID_TOOL_DOWN, wxT("&Down"), wxDefaultPosition, wxSize(50,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxVERTICAL );
    wxButton *item8 = new wxButton( parent, ID_TOOL_INSERT, wxT("&Insert"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item9 = new wxButton( parent, ID_TOOL_REMOVE, wxT("&Remove"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxFlexGridSizer *item10 = new wxFlexGridSizer( 1, 0, 0 );
    item10->AddGrowableCol( 0 );
    item10->AddGrowableRow( 0 );
    wxListCtrl *item11 = new wxListCtrl( parent, ID_COMMAND_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item10->Add( item11, 0, wxGROW|wxALL, 5 );
    item1->Add( item10, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxLEFT|wxRIGHT|wxTOP, 5 );
    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item13 = new wxStaticText( parent, ID_LABEL_TOOLBAR_CONTENTS, wxT("Contents:"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs14 = (wxString*) NULL;
    wxChoice *item14 = new wxChoice( parent, ID_TOOLBAR_CONTENTS, wxDefaultPosition, wxSize(150,-1), 0, strs14, 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );
    item0->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_COMMAND_LIST, ID_LABEL_TOOLBAR_CONTENTS, ID_TOOL_DOWN, ID_TOOL_INSERT, ID_TOOL_REMOVE, ID_TOOL_UP, ID_TOOLBAR_CONTENTS, and ID_TOOLBAR_LIST.
Referenced by createContents().
initialize()
void OptionsDialog::initialize () private
Initializes the dialog widgets.
Definition at line 156 of file OptionsDialog.cc.
{
    createContents(this, true, true);
    toolbarList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_TOOLBAR_LIST));
    commandList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_COMMAND_LIST));
    shortcutList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_KB_SC_LIST));
#ifdef KB_SC_EDITING
    // Create keyboard shortcut list columns.
    wxListCtrl* shortcutList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_KB_SC_LIST));
    shortcutList->InsertColumn(
        0, COMMAND_COLUMN_TITLE, wxLIST_FORMAT_LEFT, 190);
    shortcutList_->InsertColumn(
        1, SHORTCUT_COLUMN_TITLE, wxLIST_FORMAT_LEFT, 150);
#endif
    // Create toolbar buttons list column.
    wxListCtrl* toolbarList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_TOOLBAR_LIST));
    toolbarList->InsertColumn(
        0, TOOLBAR_BUTTONS_COLUMN_TITLE, wxLIST_FORMAT_LEFT, 180);
    // Create available buttons list column.
    wxListCtrl* commandList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_COMMAND_LIST));
    commandList->InsertColumn(
        0, AVAILABLE_COMMANDS_COLUMN_TITLE, wxLIST_FORMAT_LEFT, 180);
    FindWindow(ID_TOOL_DOWN)->Disable();
    FindWindow(ID_TOOL_UP)->Disable();
    FindWindow(ID_TOOL_INSERT)->Disable();
    FindWindow(ID_TOOL_REMOVE)->Disable();
#ifdef KB_SC_EDITING
    FindWindow(ID_EDIT_KB_SC)->Disable();
    FindWindow(ID_DELETE_KB_SC)->Disable();
#endif
    wxChoice* contentsChoicer =
        dynamic_cast<wxChoice*>(FindWindow(ID_TOOLBAR_CONTENTS));
    // choicer texts
    contentsChoicer->Append(CONTENTS_ICONS);
    contentsChoicer->Append(CONTENTS_BOTH);
    contentsChoicer->Append(CONTENTS_TEXT);
}
References AVAILABLE_COMMANDS_COLUMN_TITLE, COMMAND_COLUMN_TITLE, commandList_, CONTENTS_BOTH, CONTENTS_ICONS, CONTENTS_TEXT, createContents(), ID_COMMAND_LIST, ID_DELETE_KB_SC, ID_EDIT_KB_SC, ID_KB_SC_LIST, ID_TOOL_DOWN, ID_TOOL_INSERT, ID_TOOL_REMOVE, ID_TOOL_UP, ID_TOOLBAR_CONTENTS, ID_TOOLBAR_LIST, SHORTCUT_COLUMN_TITLE, shortcutList_, TOOLBAR_BUTTONS_COLUMN_TITLE, and toolbarList_.
onActivateShortcut()
void OptionsDialog::onActivateShortcut (wxListEvent & event) private
Handles left mouse button double click on the shortcut list.
Definition at line 474 of file OptionsDialog.cc.
{
    wxCommandEvent dummy;
    onEditShortcut(dummy);
}
References dummy, and onEditShortcut().
onCommandSelection()
void OptionsDialog::onCommandSelection (wxListEvent & event) private
Disables and enables 'Insert' button in the 'Toolbar' page
If a command is selected, button is enabled. If no command is selected the button is disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 706 of file OptionsDialog.cc.
{
    if (commandList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_TOOL_INSERT)->Disable();
        return;
    }
    FindWindow(ID_TOOL_INSERT)->Enable();
    event.Skip();
}
References commandList_, and ID_TOOL_INSERT.
onDeleteShortcut()
void OptionsDialog::onDeleteShortcut (wxCommandEvent & event) private
Removes keyboard shortcut for the selected command.
Definition at line 454 of file OptionsDialog.cc.
{
    vector<Shortcut*>::iterator iter = shortcuts_.begin();
    for (int i = 0; i < shortcutList_->GetItemCount(); i++) {
        if (shortcutList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            // delete selected shortcut
            delete (*iter)->shortcut;
            (*iter)->shortcut = NULL;
            TransferDataToWindow();
            return;
        }
        iter++;
    }
    assert(false);
}
References assert, shortcutList_, shortcuts_, and TransferDataToWindow().
onEditShortcut()
void OptionsDialog::onEditShortcut (wxCommandEvent & event) private
Prompts for a new keyboard shortcut for the selected command with ShortcutDialog.
Definition at line 502 of file OptionsDialog.cc.
{
    bool newShortcut = false;
    Shortcut* selected = selectedShortcut();
    if (selected == NULL) {
        return;
    }
    // edit selected shortcut
    KeyboardShortcut* shortcut = selected->shortcut;
    if (shortcut == NULL) {
        newShortcut = true;
        shortcut = new KeyboardShortcut(
            selected->name, 0, false, false, char(0));
    }
    KeyboardShortcutDialog dialog(this, shortcut);
    if (dialog.ShowModal() == wxID_OK) {
        vector<Shortcut*>::iterator di = shortcuts_.begin();
        for (; di != shortcuts_.end(); di++) {
            if ((*di)->name == selected->name) {
                (*di)->shortcut = shortcut;
            } else if (((*di)->shortcut != NULL) &&
                       ((*di)->shortcut->equals(*shortcut))) {
                // Shortcut with the same key-combination exists, delete it.
                delete (*di)->shortcut;
                (*di)->shortcut = NULL;
            }
        }
        TransferDataToWindow();
    } else if (newShortcut) {
        // Shortcut adding cancelled.
        delete shortcut;
    }
    return;
}
References OptionsDialog::Shortcut::name, selectedShortcut(), OptionsDialog::Shortcut::shortcut, shortcuts_, and TransferDataToWindow().
Referenced by onActivateShortcut().
onHelp()
void OptionsDialog::onHelp (wxCommandEvent & event) private
Opens the help for the dialog from the user manual.
Definition at line 742 of file OptionsDialog.cc.
{
}
onInsertTool()
void OptionsDialog::onInsertTool (wxCommandEvent & event) private
Adds a toolbar button for the command selected in the command list.
Definition at line 548 of file OptionsDialog.cc.
{
    // search for the selected command and add it to the toolbar
    for (int i = 0; i < commandList_->GetItemCount(); i++) {
        if (commandList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            string selected =
                WxConversion::toString(commandList_->GetItemText(i));
            toolbar_.push_back(selected);
        }
    }
    TransferDataToWindow();
}
References commandList_, toolbar_, WxConversion::toString(), and TransferDataToWindow().
onMoveTool()
void OptionsDialog::onMoveTool (wxCommandEvent & event) private
Moves selected tool up or down in the toolbar button list.
Definition at line 585 of file OptionsDialog.cc.
{
    int selected = -1;
    // search the selected command in the toolbar button list
    for (int i = 0; i < toolbarList_->GetItemCount(); i++) {
        if (toolbarList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            selected = i;
        }
    }
    assert(selected != -1);
    // move tool up
    if (event.GetId() == ID_TOOL_UP) {
        if (selected == 0) {
            // tool already at the top
            return;
        }
        string above = toolbar_[selected-1];
        toolbar_[selected-1] = toolbar_[selected];
        toolbar_[selected] = above;
    }
    // move tool down
    if (event.GetId() == ID_TOOL_DOWN) {
        if (selected == int(toolbar_.size())-1) {
            // toolbar already at the bottom
            return;
        }
        string below = toolbar_[selected+1];
        toolbar_[selected+1] = toolbar_[selected];
        toolbar_[selected] = below;
    }
    TransferDataToWindow();
    long setItem = -1;
    if (event.GetId() == ID_TOOL_UP) {
        setItem = selected - 1;
    } else if (event.GetId() == ID_TOOL_DOWN) {
        setItem = selected + 1;
    }
    toolbarList_->SetItemState(setItem, wxLIST_STATE_SELECTED,
                               wxLIST_STATE_SELECTED);
    toolbarList_->EnsureVisible(setItem);
}
References assert, ID_TOOL_DOWN, ID_TOOL_UP, toolbar_, toolbarList_, and TransferDataToWindow().
onOK()
void OptionsDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the options.
Definition at line 722 of file OptionsDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    writeOptions();
    EndModal(wxID_OK);
}
References writeOptions().
onRemoveTool()
void OptionsDialog::onRemoveTool (wxCommandEvent & event) private
Removes the selected toolbar button from the toolbar button list.
Definition at line 566 of file OptionsDialog.cc.
{
    vector<string>::iterator iter = toolbar_.begin();
    for (int i = 0; i < toolbarList_->GetItemCount(); i++) {
        // search selected list item
        if (toolbarList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            toolbar_.erase(iter);
            break;
        }
        assert(iter != toolbar_.end());
        iter++;
    }
    TransferDataToWindow();
}
References assert, toolbar_, toolbarList_, and TransferDataToWindow().
onShortcutRightClick()
void OptionsDialog::onShortcutRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed.
Parameters
event Information about right mouse click event.
Definition at line 661 of file OptionsDialog.cc.
{
    shortcutList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    contextMenu->Append(ID_EDIT_KB_SC, EDIT_BUTTON_LABEL);
    contextMenu->Append(ID_DELETE_KB_SC, DELETE_BUTTON_LABEL);
    shortcutList_->PopupMenu(contextMenu, event.GetPoint());
}
References DELETE_BUTTON_LABEL, EDIT_BUTTON_LABEL, ID_DELETE_KB_SC, ID_EDIT_KB_SC, and shortcutList_.
onShortcutSelection()
void OptionsDialog::onShortcutSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the keyboard shortcut.
If a shortcut is selected, buttons are enabled. If no shortcut is selected the buttons are disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 643 of file OptionsDialog.cc.
{
    if (shortcutList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_KB_SC)->Disable();
        FindWindow(ID_EDIT_KB_SC)->Disable();
        return;
    }
    FindWindow(ID_DELETE_KB_SC)->Enable();
    FindWindow(ID_EDIT_KB_SC)->Enable();
    event.Skip();
}
References ID_DELETE_KB_SC, ID_EDIT_KB_SC, and shortcutList_.
onToolbarSelection()
void OptionsDialog::onToolbarSelection (wxListEvent & event) private
Disables and enables Up, Down and Remove buttons in the 'Toolbar' page.
If a toolbar item is selected, buttons are enabled. If no item is selected the buttons are disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 683 of file OptionsDialog.cc.
{
    if (toolbarList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_TOOL_UP)->Disable();
        FindWindow(ID_TOOL_DOWN)->Disable();
        FindWindow(ID_TOOL_REMOVE)->Disable();
        return;
    }
    FindWindow(ID_TOOL_UP)->Enable();
    FindWindow(ID_TOOL_DOWN)->Enable();
    FindWindow(ID_TOOL_REMOVE)->Enable();
    event.Skip();
}
References ID_TOOL_DOWN, ID_TOOL_REMOVE, ID_TOOL_UP, and toolbarList_.
readCommands()
void OptionsDialog::readCommands () private
Adds available commands to the keyboard shortcut list and toolbar tool list.
Reads commands fromt the command registry.
Definition at line 351 of file OptionsDialog.cc.
{
    GUICommand* command = commandRegistry_.firstCommand();
    while (command != NULL) {
        Shortcut* shortcut = new Shortcut;
        shortcut->id = command->id();
        shortcut->name = command->name();
        shortcut->shortcut = NULL;
        shortcuts_.push_back(shortcut);
        command = commandRegistry_.nextCommand();
    }
}
References commandRegistry_, CommandRegistry::firstCommand(), GUICommand::id(), OptionsDialog::Shortcut::id, GUICommand::name(), OptionsDialog::Shortcut::name, CommandRegistry::nextCommand(), OptionsDialog::Shortcut::shortcut, and shortcuts_.
readOptions()
void OptionsDialog::readOptions () protected virtual
Reads the options in options_ to dialog attributes.
Definition at line 208 of file OptionsDialog.cc.
{
    // read and set the toolbar layout
    wxChoice* contentsChoice =
        dynamic_cast<wxChoice*>(FindWindow(ID_TOOLBAR_CONTENTS));
    if (options_.toolbarLayout() == GUIOptions::TEXT) {
        contentsChoice->SetStringSelection(CONTENTS_TEXT);
    } else if (options_.toolbarLayout() == GUIOptions::ICON) {
        contentsChoice->SetStringSelection(CONTENTS_ICONS);
    } else if (options_.toolbarLayout() == GUIOptions::BOTH) {
        contentsChoice->SetStringSelection(CONTENTS_BOTH);
    } else {
        assert(false);
    }
#ifdef KB_SC_EDITING
    // read keyboard shortcuts
    KeyboardShortcut* shortcut = options_.firstShortcut();
    while (shortcut != NULL) {
        // find the shortcut list item for the command
        Shortcut* listItem = NULL;
        vector<Shortcut*>::iterator i = shortcuts_.begin();
        for (; i != shortcuts_.end(); i++) {
            if ((*i)->name == shortcut->action()) {
                listItem = (*i);
            }
        }
        if (listItem == NULL) {
            wxString message = _T("Unknown command in options:\n");
            message.Append(WxConversion::toWxString(shortcut->action()));
            ErrorDialog dialog(this, message);
            dialog.ShowModal();
        } else {
            listItem->shortcut = new KeyboardShortcut(*shortcut);
        }
        shortcut = options_.nextShortcut();
    }
#endif
    bool found = true;
    int slot = 0;
    // read toolbar buttons and separators
    while (found) {
        found = false;
        // check if a toolbar button exists for the slot
        ToolbarButton* tool = options_.firstToolbarButton();
        while (tool != NULL) {
            if (tool->slot() == slot) {
                // button found for the slot, add it
                toolbar_.push_back(tool->action());
                found = true;
            }
            tool = options_.nextToolbarButton();
        }
        // check if a separator exists for the slot
        int separator = options_.firstSeparator();
        while (separator != -1) {
            if (separator == slot) {
                // separator found for the slot, add it
                toolbar_.push_back(GUIOptions::TOOLBAR_SEPARATOR);
                found = true;
            }
            separator = options_.nextSeparator();
        }
        slot++;
    }
}
References KeyboardShortcut::action(), ToolbarButton::action(), assert, GUIOptions::BOTH, CONTENTS_BOTH, CONTENTS_ICONS, CONTENTS_TEXT, GUIOptions::firstSeparator(), GUIOptions::firstShortcut(), GUIOptions::firstToolbarButton(), GUIOptions::ICON, ID_TOOLBAR_CONTENTS, GUIOptions::nextSeparator(), GUIOptions::nextShortcut(), GUIOptions::nextToolbarButton(), options_, OptionsDialog::Shortcut::shortcut, shortcuts_, ToolbarButton::slot(), GUIOptions::TEXT, toolbar_, GUIOptions::TOOLBAR_SEPARATOR, GUIOptions::toolbarLayout(), and WxConversion::toWxString().
selectedShortcut()
OptionsDialog::Shortcut * OptionsDialog::selectedShortcut () private
Returns pointer to the shortcut selected in the shortcut list.
Returns
NULL if no shortcut is selected.
Definition at line 486 of file OptionsDialog.cc.
{
    vector<Shortcut*>::iterator iter = shortcuts_.begin();
    for (int i = 0; i < shortcutList_->GetItemCount(); i++) {
        if (shortcutList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            return (*iter);
        }
        iter++;
    }
    return NULL;
}
References shortcutList_, and shortcuts_.
Referenced by onEditShortcut().
setTexts()
void OptionsDialog::setTexts () private
TransferDataToWindow()
bool OptionsDialog::TransferDataToWindow () private virtual
Transfers data from dialog attributes to controls in the dialog.
Returns
False if the transfer failed.
Definition at line 370 of file OptionsDialog.cc.
{
    toolbarList_->DeleteAllItems();
    commandList_->DeleteAllItems();
    vector<Shortcut*>::iterator i = shortcuts_.begin();
#ifdef KB_SC_EDITING
    shortcutList_->DeleteAllItems();
    // Update keyboard shortcut list.
    for (; i != shortcuts_.end(); i++) {
        shortcutList_->InsertItem(
            shortcutList_->GetItemCount(),
            WxConversion::toWxString((*i)->name));
        // add shortcut to the second column if one exists
        if ((*i)->shortcut != NULL) {
            string keyName = "";
            // set the name of the key
            if ((*i)->shortcut->key() > 32 && (*i)->shortcut->key() < 127) {
                // character key
                keyName = Conversion::toString((*i)->shortcut->key());
            } else if ((*i)->shortcut->key() == 127) {
                // delete key
                keyName = "DEL";
            } else if ((*i)->shortcut->fKey() != 0) {
                // function key
                keyName = "F"+Conversion::toString((*i)->shortcut->fKey());
            }
            wxString key = WxConversion::toWxString(keyName);
            if ((*i)->shortcut->alt()) {
                key.Prepend(_T("ALT - "));
            }
            if ((*i)->shortcut->ctrl()) {
                key.Prepend(_T("CTRL - "));
            }
            shortcutList_->SetItem(shortcutList_->GetItemCount()-1,
                                   1, key);
        }
    }
#endif
    // Update toolbar button lists.
    vector<string>::iterator iter = toolbar_.begin();
    for (; iter != toolbar_.end(); iter++) {
        toolbarList_->InsertItem(toolbarList_->GetItemCount(),
                                 WxConversion::toWxString((*iter)));
    }
    // update commands list
    commandList_->InsertItem(
        0, WxConversion::toWxString(GUIOptions::TOOLBAR_SEPARATOR));
    bool inToolbar;
    i = shortcuts_.begin();
    for (; i != shortcuts_.end(); i++) {
        inToolbar = false;
        // check if command is already in the toolbar
        iter = toolbar_.begin();
        for (; iter != toolbar_.end(); iter++) {
            if ((*i)->name == (*iter)) {
                inToolbar = true;
            }
        }
        // add command to the list if it wasn't in the toolbar
        if (!inToolbar) {
            commandList_->InsertItem(commandList_->GetItemCount(),
                                     WxConversion::toWxString((*i)->name));
        }
    }
    return true;
}
References commandList_, shortcutList_, shortcuts_, toolbar_, GUIOptions::TOOLBAR_SEPARATOR, toolbarList_, Conversion::toString(), and WxConversion::toWxString().
Referenced by onDeleteShortcut(), onEditShortcut(), onInsertTool(), onMoveTool(), and onRemoveTool().
writeOptions()
void OptionsDialog::writeOptions () protected virtual
Writes the options from dialog attributes to the current options object.
Definition at line 286 of file OptionsDialog.cc.
{
    // set the toolbar layout
    wxChoice* contentsChoice =
        dynamic_cast<wxChoice*>(FindWindow(ID_TOOLBAR_CONTENTS));
    if (contentsChoice->GetStringSelection() == CONTENTS_TEXT) {
        options_.setToolbarLayout(GUIOptions::TEXT);
    } else if (contentsChoice->GetStringSelection() == CONTENTS_ICONS) {
        options_.setToolbarLayout(GUIOptions::ICON);
    } else if (contentsChoice->GetStringSelection() == CONTENTS_BOTH) {
        options_.setToolbarLayout(GUIOptions::BOTH);
    } else {
        assert(false);
    }
#ifdef KB_SC_EDITING
    // delete all old shortcuts
    while (options_.firstShortcut() != NULL) {
        options_.deleteKeyboardShortcut(options_.firstShortcut());
    }
#endif
    // delete all old toolbar buttons
    while (options_.firstToolbarButton() != NULL) {
        options_.deleteToolbarButton(options_.firstToolbarButton());
    }
    // delete all old toolbar separators
    while (options_.firstSeparator() != -1) {
        options_.deleteSeparator(options_.firstSeparator());
    }
#ifdef KB_SC_EDITING
    // add all keyboard shortcuts and toolbar buttons
    vector<Shortcut*>::iterator i = shortcuts_.begin();
    for (; i != shortcuts_.end(); i++) {
        if ((*i)->shortcut != NULL) {
            options_.addKeyboardShortcut((*i)->shortcut);
        }
    }
#endif
    // add all toolbar buttons and separators
    int slot = 0;
    vector<string>::iterator iter = toolbar_.begin();
    for (; iter != toolbar_.end(); iter++) {
        if ((*iter) == GUIOptions::TOOLBAR_SEPARATOR) {
            options_.addSeparator(slot);
        } else {
            ToolbarButton* button = new ToolbarButton(slot, (*iter));
            options_.addToolbarButton(button);
        }
        slot++;
    }
}
References GUIOptions::addKeyboardShortcut(), GUIOptions::addSeparator(), GUIOptions::addToolbarButton(), assert, GUIOptions::BOTH, CONTENTS_BOTH, CONTENTS_ICONS, CONTENTS_TEXT, GUIOptions::deleteKeyboardShortcut(), GUIOptions::deleteSeparator(), GUIOptions::deleteToolbarButton(), GUIOptions::firstSeparator(), GUIOptions::firstShortcut(), GUIOptions::firstToolbarButton(), GUIOptions::ICON, ID_TOOLBAR_CONTENTS, options_, GUIOptions::setToolbarLayout(), shortcuts_, GUIOptions::TEXT, toolbar_, and GUIOptions::TOOLBAR_SEPARATOR.
Referenced by onOK(), and ProDeOptionsDialog::onOK().
Member Data Documentation
AVAILABLE_COMMANDS_COLUMN_TITLE
const wxString OptionsDialog::AVAILABLE_COMMANDS_COLUMN_TITLE = _T("Commands") static private
Title of the toolbar tab available commands list.
Definition at line 166 of file OptionsDialog.hh.
Referenced by initialize().
choice_
int OptionsDialog::choice_ private
Definition at line 130 of file OptionsDialog.hh.
COMMAND_COLUMN_TITLE
const wxString OptionsDialog::COMMAND_COLUMN_TITLE = _T("Command") static private
Title of the keyboard shortcut list command name column.
Definition at line 160 of file OptionsDialog.hh.
Referenced by initialize().
commandList_
wxListCtrl* OptionsDialog::commandList_ private
List control for commands not in the toolbar.
Definition at line 128 of file OptionsDialog.hh.
Referenced by initialize(), onCommandSelection(), onInsertTool(), and TransferDataToWindow().
commandRegistry_
CommandRegistry& OptionsDialog::commandRegistry_ private
Command registry containing available commands for shortcuts.
Definition at line 138 of file OptionsDialog.hh.
Referenced by readCommands().
CONTENTS_BOTH
const wxString OptionsDialog::CONTENTS_BOTH = _T("Both") static private
Text for the toolbar contents choicer icon&text mode item.
Definition at line 170 of file OptionsDialog.hh.
Referenced by initialize(), readOptions(), and writeOptions().
CONTENTS_ICONS
const wxString OptionsDialog::CONTENTS_ICONS = _T("Icons") static private
Text fot the toolbar contents choicer icon-mode item.
Definition at line 168 of file OptionsDialog.hh.
Referenced by initialize(), readOptions(), and writeOptions().
CONTENTS_TEXT
const wxString OptionsDialog::CONTENTS_TEXT = _T("Text") static private
Text for the toolbar contents choicer text-mode item.
Definition at line 172 of file OptionsDialog.hh.
Referenced by initialize(), readOptions(), and writeOptions().
DELETE_BUTTON_LABEL
const wxString OptionsDialog::DELETE_BUTTON_LABEL = _T("Delete") static private
Label for delete-button.
Definition at line 177 of file OptionsDialog.hh.
Referenced by onShortcutRightClick().
EDIT_BUTTON_LABEL
const wxString OptionsDialog::EDIT_BUTTON_LABEL = _T("Edit...") static private
Label for Edit-button.
Definition at line 175 of file OptionsDialog.hh.
Referenced by onShortcutRightClick().
notebook_
wxNotebook* OptionsDialog::notebook_ protected
Notebook containing dialog pages.
Definition at line 75 of file OptionsDialog.hh.
Referenced by addPage().
options_
GUIOptions& OptionsDialog::options_ private
current editor options
Definition at line 122 of file OptionsDialog.hh.
Referenced by readOptions(), and writeOptions().
parent_
wxWindow* OptionsDialog::parent_ private
parent window of the dialog
Definition at line 120 of file OptionsDialog.hh.
SHORTCUT_COLUMN_TITLE
const wxString OptionsDialog::SHORTCUT_COLUMN_TITLE = _T("Shortcut") static private
Title of the keyboard shortcut list shortcut column.
Definition at line 162 of file OptionsDialog.hh.
Referenced by initialize().
shortcutList_
wxListCtrl* OptionsDialog::shortcutList_ private
Keyboard shortcut list control.
Definition at line 124 of file OptionsDialog.hh.
Referenced by initialize(), onDeleteShortcut(), onShortcutRightClick(), onShortcutSelection(), selectedShortcut(), and TransferDataToWindow().
shortcuts_
std::vector<Shortcut*> OptionsDialog::shortcuts_ private
Keyboard shortcuts.
Definition at line 133 of file OptionsDialog.hh.
Referenced by onDeleteShortcut(), onEditShortcut(), readCommands(), readOptions(), selectedShortcut(), TransferDataToWindow(), writeOptions(), and ~OptionsDialog().
toolbar_
std::vector<std::string> OptionsDialog::toolbar_ private
Toolbar buttons and separators.
Definition at line 135 of file OptionsDialog.hh.
Referenced by onInsertTool(), onMoveTool(), onRemoveTool(), readOptions(), TransferDataToWindow(), and writeOptions().
TOOLBAR_BUTTONS_COLUMN_TITLE
const wxString OptionsDialog::TOOLBAR_BUTTONS_COLUMN_TITLE = _T("Toolbar") static private
Title of the toolbar tab toolbar button list.
Definition at line 164 of file OptionsDialog.hh.
Referenced by initialize().
toolbarList_
wxListCtrl* OptionsDialog::toolbarList_ private
Toolbar buttons list control.
Definition at line 126 of file OptionsDialog.hh.
Referenced by initialize(), onMoveTool(), onRemoveTool(), onToolbarSelection(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
OptionsDialog.hh
OptionsDialog.cc