OpenASIP: OperationNode Class Reference
OperationNode Class Reference
#include <OperationNode.hh>
Public Member Functions
OperationNode (Operation &operation)
OperationNode (const OperationNode &other)
virtual GraphNode * clone () const
virtual ~OperationNode ()
Operation & referencedOperation () const
virtual std::string toString () const
Public Member Functions inherited from OperationDAGNode
virtual ~OperationDAGNode ()
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
int nodeID () const
virtual std::string dotString () const
Private Attributes
Operation * referencedOperation_
Detailed Description
One operation node of the operation DAG.
Definition at line 47 of file OperationNode.hh.
Constructor & Destructor Documentation
OperationNode() [1/2]
OperationNode::OperationNode (Operation & op)
Constructor.
Parameters
Definition at line 44 of file OperationNode.cc.
                                          :
    OperationDAGNode(), referencedOperation_(&op) {
}
OperationNode() [2/2]
OperationNode::OperationNode (const OperationNode & other)
Definition at line 48 of file OperationNode.cc.
                                                       :
    OperationDAGNode(), referencedOperation_(&(other.referencedOperation())) {
}
~OperationNode()
virtual OperationNode::~OperationNode () inline virtual
Definition at line 54 of file OperationNode.hh.
{}
Member Function Documentation
clone()
GraphNode * OperationNode::clone () const virtual
Clones node. Needed for dynamic binding, when copying instances through the base class.
Returns
Dynamically allocated copy of the node.
Reimplemented from GraphNode.
Definition at line 60 of file OperationNode.cc.
{
    return new OperationNode(*this);
}
referencedOperation()
Operation & OperationNode::referencedOperation () const
Returns operation that is referred from current node.
Returns
Operation that is referred from current node.
Definition at line 70 of file OperationNode.cc.
{
    assert(referencedOperation_ != NULL);
    return *referencedOperation_;
}
References assert, and referencedOperation_.
Referenced by OperationDAGBehavior::canBeSimulated(), ProGeTools::canGenerateFromDAG(), Automagic::canGenerateFromDAG(), OperationDAGBuilder::connectOperandToNode(), OperationDAGSelector::countUnknownOperations(), TDGen::dagNodeToString(), TDGen::emulatingOpNodeLLVMName(), OperationDAGSelector::findDags(), MemoryAliasAnalyzer::findTwoPartAddressOperands(), TDGen::immediateOperandNameForEmulatedOperation(), MemoryAliasAnalyzer::mausOfOperation(), ProGeTools::nodeLatency(), Automagic::nodeLatency(), OperationDAGBehavior::OperationDAGBehavior(), TDGen::operationDAGCanBeMatched(), TDGen::operationNodeToString(), FUGen::scheduleOperations(), FUGen::subOpName(), and OperationDAGConverter::writeNode().
toString()
std::string OperationNode::toString () const virtual
Returns a node description as a string.
Used for printing graph into .dot file. This is used for a label in the default dotString() implementation.
Returns
The node ID as a string.
Reimplemented from GraphNode.
Definition at line 76 of file OperationNode.cc.
{
    return referencedOperation_->name();
}
References Operation::name(), and referencedOperation_.
Referenced by OperationDAGBuilder::connectOperandToNode().
Member Data Documentation
referencedOperation_
Operation* OperationNode::referencedOperation_ private
Definition at line 60 of file OperationNode.hh.
Referenced by referencedOperation(), and toString().
The documentation for this class was generated from the following files:
OperationNode.hh
OperationNode.cc