OpenASIP: CmdRegister Class Reference
CmdRegister Class Reference
#include <TestOsal.hh>
Public Member Functions
CmdRegister ()
CmdRegister (const CmdRegister &cmd)
virtual ~CmdRegister ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Static Public Attributes
static const std::string REGISTER_PROGRAM_COUNTER = "programcounter"
static const std::string REGISTER_RETURN_ADDRESS = "returnaddress"
Detailed Description
Custom command for showing register values.
There are currently two register values which can asked: program counter and return address.
Definition at line 145 of file TestOsal.hh.
Constructor & Destructor Documentation
CmdRegister() [1/2]
CmdRegister::CmdRegister ()
Constructor.
Definition at line 616 of file TestOsal.cc.
                         : CustomCommand("register") {
}
CmdRegister() [2/2]
CmdRegister::CmdRegister (const CmdRegister & cmd) explicit
Copy constructor.
Parameters
cmd Command to be copied.
Definition at line 624 of file TestOsal.cc.
                                               : CustomCommand(cmd) {
}
~CmdRegister()
CmdRegister::~CmdRegister () virtual
Destructor.
Definition at line 630 of file TestOsal.cc.
{
}
Member Function Documentation
execute()
bool CmdRegister::execute (const std::vector< DataObject > & arguments) virtual
Executes the command.
Output is the value of given register.
Parameters
arguments Arguments for the command.
Returns
True if the execution is successful, false otherwise.
Exceptions
NumberFormatException If DataObject conversion fails.
Implements CustomCommand.
Definition at line 643 of file TestOsal.cc.
{
    ScriptInterpreter* scriptInterp = interpreter();
    OsalInterpreter* interp = dynamic_cast<OsalInterpreter*>(scriptInterp);
    assert(interp != NULL);
    DataObject* result = new DataObject();
    if (arguments.size() != 2) {
        result->setString("wrong number of arguments");
        interp->setResult(result);
        return false;
    }
    string registerValue = arguments[1].stringValue();
    TesterContext& context =
        *(dynamic_cast<TesterContext*>(&interp->context()));
    string output = "";
    if (registerValue == REGISTER_PROGRAM_COUNTER) {
        InstructionAddress& addr = context.programCounter();
        SimValue value(64);
        value = addr;
        output = context.toOutputFormat(&value);
    } else if (registerValue == REGISTER_RETURN_ADDRESS) {
        SimValue& addr = context.returnAddress();
        SimValue value(64);
        value = addr;
        output = context.toOutputFormat(&value);
    } else {
        result->setString("illegal register name \"" +
                          registerValue + "\"");
        interp->setResult(result);
        return false;
    }
    result->setString(output);
    interp->setResult(result);
    return true;
}
References assert, CustomCommand::context(), SimpleScriptInterpreter::context(), CustomCommand::interpreter(), REGISTER_PROGRAM_COUNTER, REGISTER_RETURN_ADDRESS, ScriptInterpreter::setResult(), and DataObject::setString().
helpText()
string CmdRegister::helpText () const virtual
Returns the help text of the command.
Returns
The help text.
Implements CustomCommand.
Definition at line 690 of file TestOsal.cc.
{
    return
        "Prints the contents of the register. Register is one of the "
        "following:\n{" +
        REGISTER_PROGRAM_COUNTER + "|" +
        REGISTER_RETURN_ADDRESS + "}";
}
References REGISTER_PROGRAM_COUNTER, and REGISTER_RETURN_ADDRESS.
Member Data Documentation
REGISTER_PROGRAM_COUNTER
const string CmdRegister::REGISTER_PROGRAM_COUNTER = "programcounter" static
Definition at line 148 of file TestOsal.hh.
Referenced by execute(), and helpText().
REGISTER_RETURN_ADDRESS
const string CmdRegister::REGISTER_RETURN_ADDRESS = "returnaddress" static
Definition at line 149 of file TestOsal.hh.
Referenced by execute(), and helpText().
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc