OpenASIP: DisassemblyInstruction Class Reference
DisassemblyInstruction Class Reference
#include <DisassemblyInstruction.hh>
Public Member Functions
DisassemblyInstruction ()
~DisassemblyInstruction ()
Word moveCount () const
void addMove (DisassemblyInstructionSlot *move)
DisassemblyInstructionSlot & move (Word index) const
Word longImmediateCount () const
void addLongImmediate (DisassemblyImmediateAssignment *longImm)
DisassemblyImmediateAssignment & longImmediate (Word index) const
std::string toString () const
DisassemblyAnnotation & annotation (int index) const
void addAnnotation (DisassemblyAnnotation *annotation)
int annotationCount () const
Private Types
typedef std::vector< DisassemblyInstructionSlot * > MoveTable
Vector of DisassemblyMoves.
typedef std::vector< DisassemblyImmediateAssignment * > LongImmediateTable
Vector of DisassemblyMoves.
Private Member Functions
DisassemblyInstruction (const DisassemblyInstruction &)
Copying not allowed.
DisassemblyInstruction operator= (const DisassemblyInstruction &)
Assignment not allowed.
Private Attributes
MoveTable moves_
List of instruction moves.
LongImmediateTable longImmediates_
List of instruction long immediates.
std::vector< DisassemblyAnnotation * > annotations_
Annotationes of instruction itself.
Detailed Description
Represents an instruction in the disassembler.
Definition at line 46 of file DisassemblyInstruction.hh.
Member Typedef Documentation
LongImmediateTable
typedef std::vector<DisassemblyImmediateAssignment*> DisassemblyInstruction::LongImmediateTable private
Vector of DisassemblyMoves.
Definition at line 70 of file DisassemblyInstruction.hh.
MoveTable
typedef std::vector<DisassemblyInstructionSlot*> DisassemblyInstruction::MoveTable private
Vector of DisassemblyMoves.
Definition at line 67 of file DisassemblyInstruction.hh.
Constructor & Destructor Documentation
DisassemblyInstruction() [1/2]
DisassemblyInstruction::DisassemblyInstruction ()
Constructor.
Definition at line 39 of file DisassemblyInstruction.cc.
{
}
~DisassemblyInstruction()
DisassemblyInstruction::~DisassemblyInstruction ()
Destructor.
Definition at line 46 of file DisassemblyInstruction.cc.
{
    // Delete all moves of the instruction.
   SequenceTools::deleteAllItems(moves_);
}
References SequenceTools::deleteAllItems(), and moves_.
DisassemblyInstruction() [2/2]
DisassemblyInstruction::DisassemblyInstruction (const DisassemblyInstruction &) private
Copying not allowed.
Member Function Documentation
addAnnotation()
void DisassemblyInstruction::addAnnotation (DisassemblyAnnotation * annotation)
Adds an annotation to instruction.
Parameters
annotation Annotation to add.
Definition at line 175 of file DisassemblyInstruction.cc.
{
    annotations_.push_back(annotation);
}
References annotation(), and annotations_.
Referenced by TPEFDisassembler::createInstruction().
addLongImmediate()
void DisassemblyInstruction::addLongImmediate (DisassemblyImmediateAssignment * longImm)
Adds a long immediate to the instruction.
Parameters
longImm Immediate to be added.
Definition at line 96 of file DisassemblyInstruction.cc.
{
    longImmediates_.push_back(longImm);
}
References longImmediates_.
Referenced by POMDisassembler::createInstruction(), TPEFDisassembler::createInstruction(), and POMDisassembler::disassemble().
addMove()
void DisassemblyInstruction::addMove (DisassemblyInstructionSlot * move)
Adds a move to the instruction.
Parameters
move Move to be added.
Definition at line 58 of file DisassemblyInstruction.cc.
{
    moves_.push_back(move);
}
References move(), and moves_.
Referenced by POMDisassembler::createInstruction(), TPEFDisassembler::createInstruction(), and POMDisassembler::disassemble().
annotation()
DisassemblyAnnotation & DisassemblyInstruction::annotation (int index) const
Returns annotation of requested index.
Parameters
index Index of annotation to return.
Returns
Annotation of requested index.
Definition at line 165 of file DisassemblyInstruction.cc.
{
    return *(annotations_.at(index));
}
References annotations_.
Referenced by addAnnotation(), and toString().
annotationCount()
int DisassemblyInstruction::annotationCount () const
Returns the number of annotationes stored for the instruction.
Returns
The number of annotationes stored for the instruction.
Definition at line 185 of file DisassemblyInstruction.cc.
{
    return static_cast<int>(annotations_.size());
}
References annotations_.
Referenced by toString().
longImmediate()
DisassemblyImmediateAssignment & DisassemblyInstruction::longImmediate (Word index) const
Returns the long immediate at a given index.
Parameters
index Index of the long immediate.
Returns
The long immediate at the index.
Exceptions
OutOfRange If the give index is out of range.
Definition at line 122 of file DisassemblyInstruction.cc.
{
    if (index >= longImmediateCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return *longImmediates_[index];
}
References __func__, longImmediateCount(), and longImmediates_.
Referenced by DisassemblyGridTable::GetValue(), and toString().
longImmediateCount()
Word DisassemblyInstruction::longImmediateCount () const
Returns number of long immediates in the instruction.
Returns
Instruction's long immediate count.
Definition at line 109 of file DisassemblyInstruction.cc.
{
    return longImmediates_.size();
}
References longImmediates_.
Referenced by DisassemblyGridTable::GetValue(), longImmediate(), and toString().
move()
DisassemblyInstructionSlot & DisassemblyInstruction::move (Word index) const
Returns the isntruction move at a given index.
Parameters
index Index of the move.
Returns
The move at the index.
Exceptions
OutOfRange If the give index is out of range.
Definition at line 82 of file DisassemblyInstruction.cc.
{
    if (index >= moveCount()) {
    std::string procName = "DisassemblyInstruction::move";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *moves_[index];
}
References moveCount(), and moves_.
Referenced by addMove(), DisassemblyGridTable::GetValue(), and toString().
moveCount()
Word DisassemblyInstruction::moveCount () const
Returns number of moves in the instruction.
Returns
Instruction move count.
Definition at line 69 of file DisassemblyInstruction.cc.
{
    return moves_.size();
}
References moves_.
Referenced by move(), and toString().
operator=()
DisassemblyInstruction DisassemblyInstruction::operator= (const DisassemblyInstruction &) private
Assignment not allowed.
toString()
std::string DisassemblyInstruction::toString () const
Returns disassembly of the instruction.
Returns
Disassembly of the instruction as a string.
Definition at line 135 of file DisassemblyInstruction.cc.
{
    std::string disassembly;
    for (Word i = 0; i < moveCount(); i++) {
        if (i > 0) {
            disassembly = disassembly + ", ";
        }
        disassembly = disassembly + move(i).toString();
    }
    for (Word i = 0; i < longImmediateCount(); i++) {
        disassembly = disassembly + " " + longImmediate(i).toString();
    }
    for (int i = 0; i < annotationCount(); i++) {
        disassembly += annotation(i).toString();
    }
    disassembly = disassembly + " ;";
    return disassembly;
}
References annotation(), annotationCount(), longImmediate(), longImmediateCount(), move(), moveCount(), DisassemblyAnnotation::toString(), DisassemblyImmediateAssignment::toString(), and DisassemblyInstructionSlot::toString().
Referenced by POMDisassembler::disassemble(), and TPEFDumper::section().
Member Data Documentation
annotations_
std::vector<DisassemblyAnnotation*> DisassemblyInstruction::annotations_ private
Annotationes of instruction itself.
Definition at line 84 of file DisassemblyInstruction.hh.
Referenced by addAnnotation(), annotation(), and annotationCount().
longImmediates_
LongImmediateTable DisassemblyInstruction::longImmediates_ private
List of instruction long immediates.
Definition at line 81 of file DisassemblyInstruction.hh.
Referenced by addLongImmediate(), longImmediate(), and longImmediateCount().
moves_
MoveTable DisassemblyInstruction::moves_ private
List of instruction moves.
Definition at line 78 of file DisassemblyInstruction.hh.
Referenced by addMove(), move(), moveCount(), and ~DisassemblyInstruction().
The documentation for this class was generated from the following files:
DisassemblyInstruction.hh
DisassemblyInstruction.cc