OpenASIP: AboutCmd Class Reference
AboutCmd Class Reference
#include <AboutCmd.hh>
Public Member Functions
AboutCmd ()
virtual ~AboutCmd ()
virtual bool Do ()
virtual int id () const
virtual AboutCmd * create () const
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing connections.
Definition at line 40 of file AboutCmd.hh.
Constructor & Destructor Documentation
AboutCmd()
AboutCmd::AboutCmd ()
The Constructor.
Definition at line 41 of file AboutCmd.cc.
                  :
    EditorCommand(ProDeConstants::CMD_NAME_ABOUT) {
}
Referenced by create().
~AboutCmd()
AboutCmd::~AboutCmd () virtual
The Destructor.
Definition at line 50 of file AboutCmd.cc.
{}
Member Function Documentation
create()
AboutCmd * AboutCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 79 of file AboutCmd.cc.
                       {
    return new AboutCmd();
}
References AboutCmd().
Do()
bool AboutCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 59 of file AboutCmd.cc.
             {
    AboutDialog about(parentWindow());
    about.ShowModal();
    return true;
}
References GUICommand::parentWindow().
icon()
string AboutCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 99 of file AboutCmd.cc.
                     {
    return ProDeConstants::CMD_ICON_ABOUT;
}
References ProDeConstants::CMD_ICON_ABOUT.
id()
int AboutCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 70 of file AboutCmd.cc.
                   {
    return ProDeConstants::COMMAND_ABOUT;
}
References ProDeConstants::COMMAND_ABOUT.
isEnabled()
bool AboutCmd::isEnabled () virtual
This command is always executable.
Returns
Always true.
Reimplemented from EditorCommand.
Definition at line 90 of file AboutCmd.cc.
                    {
    return true;
}
The documentation for this class was generated from the following files:
AboutCmd.hh
AboutCmd.cc