OpenASIP: NullFUPortCode Class Reference
NullFUPortCode Class Reference
#include <NullFUPortCode.hh>
Static Public Member Functions
static NullFUPortCode & instance ()
Private Member Functions
NullFUPortCode ()
virtual ~NullFUPortCode ()
Static Private Attributes
static NullFUPortCode instance_
The only instance.
static SocketCodeTable socketCodes_
The parent socket code table.
static BinaryEncoding bem_
The parent binary encoding.
Additional Inherited Members
Public Member Functions inherited from FUPortCode
FUPortCode (const std::string &fu, const std::string &port, unsigned int encoding, unsigned int extraBits, SocketCodeTable &parent)
FUPortCode (const std::string &fu, const std::string &port, const std::string &operation, unsigned int encoding, unsigned int extraBits, SocketCodeTable &parent)
FUPortCode (const ObjectState *state, SocketCodeTable &parent)
virtual ~FUPortCode ()
std::string portName () const
std::string operationName () const
bool hasOperation () const
virtual ObjectState * saveState () const
Public Member Functions inherited from PortCode
virtual ~PortCode ()
std::string unitName () const
bool hasEncoding () const
unsigned int encoding () const
unsigned int extraBits () const
int width () const
int encodingWidth () const
int indexWidth () const
void setMaxIndex (unsigned regIndex)
bool isMaxIndexSet () const
unsigned maxIndex () const
SocketCodeTable * parent () const
Static Public Attributes inherited from FUPortCode
static const std::string OSNAME_FU_PORT_CODE = "fu_port_code"
ObjectState name for FU port code.
static const std::string OSKEY_PORT_NAME = "port"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_OPERATION_NAME = "operation"
ObjectState attribute key for the name of the operation.
Static Public Attributes inherited from PortCode
static const std::string OSNAME_PORT_CODE = "port_code"
ObjectState name for PortCode.
static const std::string OSKEY_UNIT_NAME = "unit_name"
ObjectState attribute key for the name of the unit.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_INDEX_WIDTH = "index_width"
ObjectState attribute key for the widht of register index.
static const std::string OSKEY_MAX_INDEX = "max-index"
ObjectState attribute key for the max-index attribute.
Protected Member Functions inherited from PortCode
PortCode (const std::string &unitName, unsigned int encoding, unsigned int extraBits, int indexWidth)
PortCode (const std::string &unitName, int indexWidth)
PortCode (const ObjectState *state)
void setParent (SocketCodeTable *parent)
Detailed Description
A null version of FUPortCode class.
Definition at line 44 of file NullFUPortCode.hh.
Constructor & Destructor Documentation
NullFUPortCode()
NullFUPortCode::NullFUPortCode () private
The constructor.
Definition at line 44 of file NullFUPortCode.cc.
                               :
    FUPortCode("NULL", "NULL", 0, false, socketCodes_) {
}
~NullFUPortCode()
NullFUPortCode::~NullFUPortCode () private virtual
The destructor.
Definition at line 52 of file NullFUPortCode.cc.
{
}
Member Function Documentation
instance()
NullFUPortCode & NullFUPortCode::instance () static
Returns the only instance of NullFUPortCode.
Returns
The only instance.
Definition at line 62 of file NullFUPortCode.cc.
{
    return instance_;
}
References instance_.
Referenced by SocketCodeTable::fuPortCode(), SocketCodeTable::fuPortCode(), SocketCodeTable::hasFUPortCode(), and SocketCodeTable::hasFUPortCode().
Member Data Documentation
bem_
BinaryEncoding NullFUPortCode::bem_ static private
The parent binary encoding.
Definition at line 57 of file NullFUPortCode.hh.
instance_
NullFUPortCode NullFUPortCode::instance_ static private
The only instance.
Definition at line 53 of file NullFUPortCode.hh.
Referenced by instance().
socketCodes_
SocketCodeTable NullFUPortCode::socketCodes_ static private
The parent socket code table.
Definition at line 55 of file NullFUPortCode.hh.
The documentation for this class was generated from the following files:
NullFUPortCode.hh
NullFUPortCode.cc