OpenASIP: SocketBusConnFactory Class Reference
SocketBusConnFactory Class Reference
#include <SocketBusConnFactory.hh>
Public Member Functions
SocketBusConnFactory ()
virtual ~SocketBusConnFactory ()
virtual EditPart * createConnection (EditPart *source, EditPart *target) const
Public Member Functions inherited from ConnectionFactory
ConnectionFactory ()
virtual ~ConnectionFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
SocketBusConnFactory & operator= (SocketBusConnFactory &old)
Assignment not allowed.
SocketBusConnFactory (SocketBusConnFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from Factory
Factory ()
Detailed Description
Factory for creating connection EditParts for socket-to-bus connections.
Definition at line 45 of file SocketBusConnFactory.hh.
Constructor & Destructor Documentation
SocketBusConnFactory() [1/2]
SocketBusConnFactory::SocketBusConnFactory ()
The Constructor.
Definition at line 46 of file SocketBusConnFactory.cc.
                                          : ConnectionFactory() {
}
~SocketBusConnFactory()
SocketBusConnFactory::~SocketBusConnFactory () virtual
The Destructor.
Definition at line 52 of file SocketBusConnFactory.cc.
{
}
SocketBusConnFactory() [2/2]
SocketBusConnFactory::SocketBusConnFactory (SocketBusConnFactory & old) private
Copying not allowed.
Member Function Documentation
createConnection()
EditPart * SocketBusConnFactory::createConnection (EditPart * socket, EditPart * segment) const virtual
Specialized factory function that returns an EditPart corresponding to a socket-bus connection.
Note
Source and target does not imply a direction.
Parameters
socket Source (socket) of the connection.
segment Target (segment) of the connection.
Returns
An EditPart corresponding to a socket-bus connection.
Reimplemented from ConnectionFactory.
Definition at line 65 of file SocketBusConnFactory.cc.
{
    ConnectionEditPart* conn = new ConnectionEditPart();
    SocketBusConnFigure* connFig = new SocketBusConnFigure();
    conn->setFigure(connFig);
    conn->setSource(socket);
    conn->setTarget(segment);
    return conn;
}
References EditPart::setFigure(), ConnectionEditPart::setSource(), and ConnectionEditPart::setTarget().
Referenced by SegmentFactory::createEditPart().
operator=()
SocketBusConnFactory & SocketBusConnFactory::operator= (SocketBusConnFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
SocketBusConnFactory.hh
SocketBusConnFactory.cc