OpenASIP: AddBreakpointDialog Class Reference
AddBreakpointDialog Class Reference
#include <AddBreakpointDialog.hh>
Public Member Functions
AddBreakpointDialog (wxWindow *parent, wxWindowID id)
virtual ~AddBreakpointDialog ()
Private Types
enum { ID_LABEL_NEW_BP , ID_ADDRESS , ID_LINE }
Widget IDs.
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Detailed Description
Dialog for adding new breakpoints.
Definition at line 41 of file AddBreakpointDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_LABEL_NEW_BP
ID_ADDRESS
ID_LINE
Definition at line 50 of file AddBreakpointDialog.hh.
         {
        ID_LABEL_NEW_BP,
        ID_ADDRESS,
        ID_LINE
    };
Constructor & Destructor Documentation
AddBreakpointDialog()
AddBreakpointDialog::AddBreakpointDialog (wxWindow * parent, wxWindowID id)
The Constructor.
@paran parent Parent window of the dialog.
Parameters
id Identifier of the window.
Definition at line 55 of file AddBreakpointDialog.cc.
                                                                        :
  wxDialog(parent, id, _T("Add Breakpoint"), wxDefaultPosition) {
    createContents(this, true, true);
}
~AddBreakpointDialog()
AddBreakpointDialog::~AddBreakpointDialog () virtual
The Destructor.
Definition at line 64 of file AddBreakpointDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * AddBreakpointDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 99 of file AddBreakpointDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxStaticText *item1 = new wxStaticText( parent, ID_LABEL_NEW_BP, wxT("Set Breakpoint at"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item2 = new wxTextCtrl( parent, ID_ADDRESS, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item3 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item3, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item4 = new wxGridSizer( 2, 0, 0 );
    wxButton *item5 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADDRESS, ID_LABEL_NEW_BP, and ID_LINE.
onOK()
void AddBreakpointDialog::onOK (wxCommandEvent & event) private
Event handler for the OK-button.
Adds a breakpoint at the address defined in the address field.
Definition at line 74 of file AddBreakpointDialog.cc.
{
    wxString addressString =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_ADDRESS))->GetValue();
    unsigned address = 0;
    try {
        address =
            Conversion::toUnsignedInt(WxConversion::toString(addressString));
    } catch (NumberFormatException& e) {
        wxString message = _T("Invalid address");
        ErrorDialog errorDialog(this, message);
        errorDialog.ShowModal();
        return;
    }
    std::string command = ProximConstants::SCL_SET_BREAKPOINT + " " +
        Conversion::toString(address);
    ProximToolbox::lineReader().input(command);
    EndModal(wxID_OK);
}
References ID_ADDRESS, ProximLineReader::input(), ProximToolbox::lineReader(), ProximConstants::SCL_SET_BREAKPOINT, Conversion::toString(), WxConversion::toString(), and Conversion::toUnsignedInt().
The documentation for this class was generated from the following files:
AddBreakpointDialog.hh
AddBreakpointDialog.cc