OpenASIP: TDGenerator::ValueType Class Reference
TDGenerator::ValueType Class Reference
#include <TDGen.hh>
Public Member Functions
ValueType (int subwWidth, int subwCount, bool isFloat)
ValueType (const TCEString &vtStr)
ValueType (const Operand &opnd)
ValueType (const ValueType &other)
ValueType & operator= (const ValueType &other)
bool isSupportedByLLVM () const
int width () const
int subwordWidth () const
int subwordCount () const
bool isFloat () const
bool isVector () const
Operand::OperandType operandType () const
TCEString valueTypeStr () const
Static Public Member Functions
static TCEString valueTypeStr (const Operand &operand)
static ValueType valueType (const TCEString &vtStr)
static ValueType valueType (const Operand &operand)
static std::vector< ValueType > vectorTypesOfWidth (int width, bool onlyInts=false)
static std::vector< ValueType > vectorTypesOfSubwordWidth (int subwordWidth, bool onlyInt=false)
Public Attributes
int subwWidth_
Subword width of the value type.
int subwCount_
Subword count of the value type.
bool isFloat_
If true, the value type is a floating point type.
Static Public Attributes
static const std::set< TCEString > SUPPORTED_LLVM_VALUE_TYPES
Contains all supported LLVM value types (<ValueType>).
Detailed Description
Represents an LLVM value type to express different value types.
Definition at line 694 of file TDGen.hh.
Constructor & Destructor Documentation
ValueType() [1/4]
ValueType::ValueType (int subwWidth, int subwCount, bool isFloat)
Constructor.
Parameters
subwWidth Subword width.
subwCount Subword count.
isFloat True, if is a floating point type.
Definition at line 8702 of file TDGen.cc.
    : subwWidth_(subwWidth), subwCount_(subwCount), isFloat_(isFloat) {
    assert(subwWidth > 0 && "Invalid value type.");
    assert(subwCount > 0 && "Invalid value type.");
}
References assert.
ValueType() [2/4]
ValueType::ValueType (const TCEString & vtStr)
Constructor.
Parameters
vtStr Value type string in LLVM format.
Definition at line 8713 of file TDGen.cc.
{
    ValueType vt = valueType(vtStr);
    this->subwWidth_ = vt.subwWidth_;
    this->subwCount_ = vt.subwCount_;
    this->isFloat_ = vt.isFloat_;
}
References isFloat_, subwCount_, subwWidth_, and valueType().
ValueType() [3/4]
ValueType::ValueType (const Operand & opnd)
Constructor.
Parameters
opnd Operand to be converted to ValueType.
Definition at line 8725 of file TDGen.cc.
{
    ValueType vt = valueType(opnd);
    this->subwWidth_ = vt.subwWidth_;
    this->subwCount_ = vt.subwCount_;
    this->isFloat_ = vt.isFloat_;
}
References isFloat_, subwCount_, subwWidth_, and valueType().
ValueType() [4/4]
ValueType::ValueType (const ValueType & other)
Copy constructor.
Parameters
other Value to be copied.
Definition at line 8737 of file TDGen.cc.
    : subwWidth_(other.subwWidth_),
      subwCount_(other.subwCount_),
      isFloat_(other.isFloat_) {}
Member Function Documentation
isFloat()
bool ValueType::isFloat () const
Tells whether ValueType is a floating point type or not.
Returns
True, is ValueType is a float type.
Definition at line 8806 of file TDGen.cc.
{
    return isFloat_;
}
References isFloat_.
isSupportedByLLVM()
bool ValueType::isSupportedByLLVM () const
Tells whether ValueType is supported by LLVM or not.
Returns
True, if ValueType is supported by LLVM.
Definition at line 8762 of file TDGen.cc.
{
    if (SUPPORTED_LLVM_VALUE_TYPES.find(valueTypeStr()) !=
        SUPPORTED_LLVM_VALUE_TYPES.end()) {
        return true;
    }
    return false;
}
References SUPPORTED_LLVM_VALUE_TYPES, and valueTypeStr().
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), TDGen::genTCETargetLoweringSIMD_getSetCCResultVT(), vectorTypesOfSubwordWidth(), and vectorTypesOfWidth().
isVector()
bool ValueType::isVector () const
Tells whether ValueType is a vector type or not.
Returns
True, is ValueType is a vector type.
Definition at line 8816 of file TDGen.cc.
{
    return subwCount_ > 1;
}
References subwCount_.
operandType()
Operand::OperandType ValueType::operandType () const
Returns the Operand::OperandType of ValueType.
Returns
OperandType of ValueType.
Definition at line 8826 of file TDGen.cc.
{
    if (!isFloat_ && subwWidth_ == 1) {
        return Operand::BOOL;
    } else if (isFloat_ && subwWidth_ == 16) {
        return Operand::HALF_FLOAT_WORD;
    } else if (isFloat_ && subwWidth_ == 32) {
        return Operand::FLOAT_WORD;
    } else if (!isFloat_) {
        return Operand::UINT_WORD;
    }
    return Operand::UINT_WORD;
}
References Operand::BOOL, Operand::FLOAT_WORD, Operand::HALF_FLOAT_WORD, isFloat_, subwWidth_, and Operand::UINT_WORD.
Referenced by TDGen::writeOperationDefUsingGivenOperandTypes().
operator=()
ValueType & ValueType::operator= (const ValueType & other)
Value assignment.
Parameters
other Value to be assigned.
Returns
Reference with the assigned values.
Definition at line 8749 of file TDGen.cc.
{
    this->subwWidth_ = other.subwWidth_;
    this->subwCount_ = other.subwCount_;
    this->isFloat_ = other.isFloat_;
    return *this;
}
References isFloat_, subwCount_, and subwWidth_.
subwordCount()
int ValueType::subwordCount () const
Returns ValueType's subword count.
Returns
ValueType's subword count.
Definition at line 8796 of file TDGen.cc.
{
    return subwCount_;
}
References subwCount_.
subwordWidth()
int ValueType::subwordWidth () const
Returns ValueType's subword bitwidth.
Returns
ValueType's subword bitwidth.
Definition at line 8786 of file TDGen.cc.
{
    return subwWidth_;
}
References subwWidth_.
Referenced by vectorTypesOfSubwordWidth().
valueType() [1/2]
ValueType ValueType::valueType (const Operand & operand) static
Returns given Operand as a value type object.
Parameters
operand Operand to be converted to ValueType.
Returns
ValueType presentation of the Operand.
Definition at line 8927 of file TDGen.cc.
{
    return valueType(valueTypeStr(operand));
}
References valueType(), and valueTypeStr().
valueType() [2/2]
ValueType ValueType::valueType (const TCEString & vtStr) static
Returns given LLVM value type string (e.g. "v2i32") as ValueType.
Parameters
vtStr LLVM value type string to be converted to ValueType.
Returns
ValueType object of the LLVM value type string.
Definition at line 8891 of file TDGen.cc.
{
    assert(vtStr.size() > 1);
    // Check if the value type is a scalar.
    if (vtStr[0] != 'v') {
        int subwWidthStr = Conversion::toInt(vtStr.substr(1));
        if (vtStr[0] == TDGen::OT_REG_FP) {
            return ValueType(subwWidthStr, 1, true);
        } else {
            return ValueType(subwWidthStr, 1, false);
        }
    }
    // The value type is a vector, find float/integer type ("f"/"i")
    // indicator.
    size_t vtI = vtStr.length() - 1;
    while (vtI > 0 && std::isdigit(vtStr[vtI])) --vtI;
    int subwCount = Conversion::toInt(vtStr.substr(1, vtI - 1));
    int subwWidth = Conversion::toInt(vtStr.substr(vtI + 1));
    if (vtStr[vtI] == TDGen::OT_REG_FP) {
        return ValueType(subwWidth, subwCount, true);
    } else {
        return ValueType(subwWidth, subwCount, false);
    }
}
References assert, TDGen::OT_REG_FP, and Conversion::toInt().
Referenced by valueType(), ValueType(), and ValueType().
valueTypeStr() [1/2]
TCEString ValueType::valueTypeStr () const
Returns ValueType in LLVM value type string format, e.g. "v2i32".
Returns
Value type string in LLVM format.
Definition at line 8846 of file TDGen.cc.
{
    const TCEString subwWidthStr = Conversion::toString(subwWidth_);
    // Check if the value type is a scalar.
    if (subwCount_ == 1) {
        if (isFloat_) {
            return "f" + subwWidthStr;
        } else {
            return "i" + subwWidthStr;
        }
    }
    // The value type is a vector.
    if (isFloat_) {
        return "v" + Conversion::toString(subwCount_) + "f" + subwWidthStr;
    } else {
        return "v" + Conversion::toString(subwCount_) + "i" + subwWidthStr;
    }
}
References isFloat_, subwCount_, subwWidth_, and Conversion::toString().
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), TDGen::associatedVectorRegisterClass(), TDGen::createSelectPatterns(), TDGen::genGeneratedTCEPlugin_getVectorImmediateOpcode(), TDGen::genTCETargetLoweringSIMD_addVectorRegisterClasses(), TDGen::hasRegisterClassSupport(), TDGen::hasRegisterClassSupport(), isSupportedByLLVM(), valueType(), valueTypeStr(), TDGen::writeScalarOperationExploitations(), TDGen::writeScalarToVectorDefs(), TDGen::writeVectorBitwiseOperationDefs(), TDGen::writeVectorImmediateWriteDefs(), TDGen::writeVectorRegisterClasses(), TDGen::writeVectorRegisterMoveDefs(), and TDGen::writeVectorTruncStoreDefs().
valueTypeStr() [2/2]
TCEString ValueType::valueTypeStr (const Operand & operand) static
Returns Operand in LLVM value type string format, e.g. "v2i32".
Parameters
operand Operand that will be transformed to value type string.
Returns
Value type string in LLVM format.
Definition at line 8873 of file TDGen.cc.
{
    if (operand.type() == Operand::FLOAT_WORD ||
        operand.type() == Operand::HALF_FLOAT_WORD) {
        ValueType vt(operand.elementWidth(), operand.elementCount(), true);
        return vt.valueTypeStr();
    } else {
        ValueType vt(operand.elementWidth(), operand.elementCount(), false);
        return vt.valueTypeStr();
    }
}
References Operand::elementCount(), Operand::elementWidth(), Operand::FLOAT_WORD, Operand::HALF_FLOAT_WORD, Operand::type(), and valueTypeStr().
vectorTypesOfSubwordWidth()
std::vector< ValueType > ValueType::vectorTypesOfSubwordWidth (int subwordWidth, bool onlyInts = false) static
Returns a list of vector value types that match the given subword width.
Currently filters out unsupported LLVM value types.
Parameters
subwordWidth The subword width of the desired value types.
onlyInts If true, floating point types are not included to output.
Returns
Value types for given subword width in a container.
Definition at line 8977 of file TDGen.cc.
{
    std::vector<ValueType> vts;
    int subwCount = 2;
    int subwWidth = subwordWidth;
    int MAX_SUBW_COUNT = SIMD_WORD_WIDTH / BYTE_BITWIDTH;
    while (subwWidth * subwCount <= SIMD_WORD_WIDTH &&
           subwCount <= MAX_SUBW_COUNT) {
        ValueType intVt(subwWidth, subwCount, false);
        if (intVt.isSupportedByLLVM()) {
            vts.push_back(intVt);
        }
        if (!onlyInts) {
            ValueType floatVt(subwWidth, subwCount, true);
            if (floatVt.isSupportedByLLVM()) {
                vts.push_back(floatVt);
            }
        }
        subwCount *= 2;
    }
    return vts;
}
References BYTE_BITWIDTH, isSupportedByLLVM(), SIMD_WORD_WIDTH, and subwordWidth().
vectorTypesOfWidth()
std::vector< ValueType > ValueType::vectorTypesOfWidth (int width, bool onlyInts = false) static
Returns a list of vector value types that match the given width.
Currently filters out unsupported LLVM value types.
Parameters
width The width of the desired value types.
onlyInts If true, floating point types are not included to output.
Returns
Value types for given width in a container.
Definition at line 8941 of file TDGen.cc.
{
    std::vector<ValueType> vts;
    int subwCount = 2;
    int subwWidth = width / subwCount;
    while (subwWidth > 0) {
        ValueType intVt(subwWidth, subwCount, false);
        if (intVt.isSupportedByLLVM()) {
            vts.push_back(intVt);
        }
        if (!onlyInts) {
            ValueType floatVt(subwWidth, subwCount, true);
            if (floatVt.isSupportedByLLVM()) {
                vts.push_back(floatVt);
            }
        }
        subwWidth /= 2;
        subwCount *= 2;
    }
    return vts;
}
References isSupportedByLLVM(), and width().
Referenced by TDGen::writeScalarOperationExploitations(), and TDGen::writeVectorBitwiseOperationDefs().
width()
int ValueType::width () const
Returns ValueType's whole bitwidth.
Returns
ValueType's whole bitwidth.
Definition at line 8776 of file TDGen.cc.
                       {
    return subwWidth_ * subwCount_;
}
References subwCount_, and subwWidth_.
Referenced by TDGen::associateRegistersWithVectorRegisterClasses(), TDGen::createVectorRVDRegNums(), TDGen::genGeneratedTCEPlugin_getVectorImmediateOpcode(), TDGen::genTCERegisterInfo_setReservedVectorRegs(), TDGenerator::RegisterClass::RegisterClass(), vectorTypesOfWidth(), TDGen::writeCallingConv(), TDGen::writeVectorBitConversions(), TDGen::writeVectorImmediateWriteDefs(), TDGen::writeVectorLoadStoreOperationExploitations(), and TDGen::writeVectorRegisterClasses().
Member Data Documentation
isFloat_
bool TDGenerator::ValueType::isFloat_
If true, the value type is a floating point type.
Definition at line 727 of file TDGen.hh.
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), isFloat(), operandType(), operator=(), ValueType(), ValueType(), valueTypeStr(), and TDGen::writeVectorBitwiseOperationDefs().
subwCount_
int TDGenerator::ValueType::subwCount_
Subword count of the value type.
Definition at line 725 of file TDGen.hh.
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), isVector(), operator=(), subwordCount(), ValueType(), ValueType(), valueTypeStr(), width(), TDGen::writeOperationDefUsingGivenOperandTypes(), and TDGen::writeScalarToVectorDefs().
subwWidth_
int TDGenerator::ValueType::subwWidth_
Subword width of the value type.
Definition at line 723 of file TDGen.hh.
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), operandType(), operator=(), subwordWidth(), ValueType(), ValueType(), valueTypeStr(), width(), and TDGen::writeOperationDefUsingGivenOperandTypes().
SUPPORTED_LLVM_VALUE_TYPES
const std::set< TCEString > ValueType::SUPPORTED_LLVM_VALUE_TYPES static
Initial value:
=
    list_of
    ("v2i1")   ("v4i1")   ("v8i1")   ("v16i1")
    ("v2i8")   ("v4i8")   ("v8i8")   ("v16i8")  ("v32i8")
    ("v2i16")  ("v4i16")  ("v8i16")  ("v16i16")
    ("v1i32")  ("v2i32")  ("v4i32")  ("v8i32")  ("v16i32")
    ("v2f16")  ("v4f16")  ("v8f16")
    ("v2f32")  ("v4f32")  ("v8f32") ("v16f32")
    ("v32i1")  ("v64i1")
    ("v64i8")
    ("v32i16")
    ("v512i1") ("v1024i1") ("v128i8") ("v256i8")
    ("v64i16") ("v128i16") ("v32i32") ("v64i32")
    ("v128i1")
    ("v2048i1")
    ("v256i8")
Contains all supported LLVM value types (<ValueType>).
Definition at line 730 of file TDGen.hh.
Referenced by TDGen::genTCETargetLoweringSIMD_addVectorRegisterClasses(), and isSupportedByLLVM().
The documentation for this class was generated from the following files:
TDGen.hh
TDGen.cc