OpenASIP: ProximNewPortWindowCmd Class Reference
ProximNewPortWindowCmd Class Reference
#include <ProximNewPortWindowCmd.hh>
Public Member Functions
ProximNewPortWindowCmd ()
virtual ~ProximNewPortWindowCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximNewPortWindowCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening a new port window in Proxim.
Definition at line 41 of file ProximNewPortWindowCmd.hh.
Constructor & Destructor Documentation
ProximNewPortWindowCmd()
ProximNewPortWindowCmd::ProximNewPortWindowCmd ()
The Constructor.
Definition at line 41 of file ProximNewPortWindowCmd.cc.
                                              :
    GUICommand(ProximConstants::COMMAND_NAME_NEW_PORT_WINDOW, NULL) {
    }
Referenced by create().
~ProximNewPortWindowCmd()
ProximNewPortWindowCmd::~ProximNewPortWindowCmd () virtual
The Destructor.
Definition at line 49 of file ProximNewPortWindowCmd.cc.
{
}
Member Function Documentation
create()
ProximNewPortWindowCmd * ProximNewPortWindowCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 97 of file ProximNewPortWindowCmd.cc.
{
    return new ProximNewPortWindowCmd();
}
References ProximNewPortWindowCmd().
Do()
bool ProximNewPortWindowCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 57 of file ProximNewPortWindowCmd.cc.
{
    ProximPortWindow* portWindow =
        new ProximPortWindow(ProximToolbox::mainFrame(), -1);
    ProximToolbox::addFramedWindow(
        portWindow, _T("Ports"), false, wxSize(270, 200));
    portWindow->GetParent()->SetSize(270, 300);
    return true;
}
References ProximToolbox::addFramedWindow(), and ProximToolbox::mainFrame().
icon()
std::string ProximNewPortWindowCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 77 of file ProximNewPortWindowCmd.cc.
{
    return "window_new.png";
}
id()
int ProximNewPortWindowCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 86 of file ProximNewPortWindowCmd.cc.
{
    return ProximConstants::COMMAND_NEW_PORT_WINDOW;
}
References ProximConstants::COMMAND_NEW_PORT_WINDOW.
isEnabled()
bool ProximNewPortWindowCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 108 of file ProximNewPortWindowCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximNewPortWindowCmd.hh
ProximNewPortWindowCmd.cc