OpenASIP: SetHistoryFilename Class Reference
SetHistoryFilename Class Reference
Static Public Member Functions
static bool execute (SimulatorInterpreter &interpreter, SimulatorFrontend &, const std::string &newValue)
static const DataObject & defaultValue ()
static bool warnOnExistingProgramAndMachine ()
Detailed Description
Setting action that sets the command history file name.
Definition at line 442 of file SettingCommand.cc.
Member Function Documentation
defaultValue()
static const DataObject & SetHistoryFilename::defaultValue () inline static
Returns the default value of this setting.
Returns
The default value.
Definition at line 472 of file SettingCommand.cc.
{
        static const DataObject defaultValue_(SIM_DEFAULT_COMMAND_LOG);
        return defaultValue_;
    }
References SIM_DEFAULT_COMMAND_LOG.
execute()
static bool SetHistoryFilename::execute (SimulatorInterpreter & interpreter, SimulatorFrontend & , const std::string & newValue) inline static
Sets the command history file name.
Parameters
interpreter To set the history file name for.
newValue Value to set.
Returns
True if setting was successful.
Definition at line 452 of file SettingCommand.cc.
{
        if (!(FileSystem::fileIsCreatable(newValue) ||
              FileSystem::fileIsWritable(newValue)) ||
            FileSystem::fileIsDirectory(newValue)) {
            interpreter.lineReader()->outputStream()
                << "Could not open file for writing." << std::endl;
            return false;
        }
        interpreter.lineReader()->setInputHistoryLog(newValue);
        return true;
    }
References FileSystem::fileIsCreatable(), FileSystem::fileIsDirectory(), FileSystem::fileIsWritable(), ScriptInterpreter::lineReader(), LineReader::outputStream(), and LineReader::setInputHistoryLog().
warnOnExistingProgramAndMachine()
static bool SetHistoryFilename::warnOnExistingProgramAndMachine () inline static
Should the action warn if program & machine exist and value was changed
Returns
boolean value on whether or not to warn
Definition at line 482 of file SettingCommand.cc.
{
        return false;
    }
The documentation for this class was generated from the following file:
SettingCommand.cc