OpenASIP: TPEF::ReferenceManager::SectionOffsetKey Class Reference
TPEF::ReferenceManager::SectionOffsetKey Class Reference
#include <ReferenceKey.hh>
Public Member Functions
SectionOffsetKey (SectionId sectionId, SectionOffset offset)
virtual ~SectionOffsetKey ()
SectionId sectionId () const
SectionOffset offset () const
bool operator== (const SectionOffsetKey &other) const
bool operator!= (const SectionOffsetKey &other) const
bool operator< (const SectionOffsetKey &other) const
Public Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
virtual ~ReferenceKey ()
Private Attributes
SectionId sectionId_
Identification code of the section that contains the element this key points to.
SectionOffset offset_
Byte offset relative to section start to the element this key points to.
Additional Inherited Members
Protected Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
ReferenceKey ()
Detailed Description
With this type of keys one can identify objects by means of a section identification code and a byte offset in the section.
Definition at line 93 of file ReferenceKey.hh.
Constructor & Destructor Documentation
SectionOffsetKey()
TPEF::ReferenceManager::SectionOffsetKey::SectionOffsetKey (SectionId sectionId, SectionOffset offset)
The constructor.
Parameters
sectionId Identification code of the section.
offset Offset of the element in section.
Definition at line 87 of file ReferenceKey.cc.
                                                                            :
    ReferenceKey(), sectionId_(sectionId), offset_(offset) {
}
~SectionOffsetKey()
TPEF::ReferenceManager::SectionOffsetKey::~SectionOffsetKey () virtual
The destructor.
Definition at line 94 of file ReferenceKey.cc.
{
}
Member Function Documentation
offset()
SectionOffset TPEF::ReferenceManager::SectionOffsetKey::offset () const
Referenced by TPEF::ReferenceManager::HashFunctions::operator()(), TPEF::TPEFASpaceSectionReader::readData(), TPEF::ReferenceManager::SafePointer::resolve(), and TPEF::SectionOffsetReplacer::tryToReplace().
operator!=()
bool TPEF::ReferenceManager::SectionOffsetKey::operator!= (const SectionOffsetKey & other) const
operator<()
bool TPEF::ReferenceManager::SectionOffsetKey::operator< (const SectionOffsetKey & other) const
operator==()
bool TPEF::ReferenceManager::SectionOffsetKey::operator== (const SectionOffsetKey & other) const
sectionId()
SectionId TPEF::ReferenceManager::SectionOffsetKey::sectionId () const
Referenced by TPEF::ReferenceManager::HashFunctions::operator()(), and TPEF::ReferenceManager::SafePointer::resolve().
Member Data Documentation
offset_
SectionOffset TPEF::ReferenceManager::SectionOffsetKey::offset_ private
Byte offset relative to section start to the element this key points to.
Definition at line 111 of file ReferenceKey.hh.
sectionId_
SectionId TPEF::ReferenceManager::SectionOffsetKey::sectionId_ private
Identification code of the section that contains the element this key points to.
Definition at line 108 of file ReferenceKey.hh.
The documentation for this class was generated from the following files:
ReferenceKey.hh
ReferenceKey.cc