OpenASIP: BlocksConnectICCmd Class Reference
BlocksConnectICCmd Class Reference
#include <BlocksConnectICCmd.hh>
Public Member Functions
BlocksConnectICCmd ()
virtual ~BlocksConnectICCmd ()
virtual bool Do ()
virtual int id () const
virtual BlocksConnectICCmd * create () const
virtual bool isEnabled ()
virtual std::string shortName () const
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for calling BlocksConnectIC explorer plugin.
Definition at line 41 of file BlocksConnectICCmd.hh.
Constructor & Destructor Documentation
BlocksConnectICCmd()
BlocksConnectICCmd::BlocksConnectICCmd ()
Definition at line 50 of file BlocksConnectICCmd.cc.
    : EditorCommand(ProDeConstants::CMD_NAME_BLOCKS_CONNECT_IC) {}
Referenced by create().
~BlocksConnectICCmd()
BlocksConnectICCmd::~BlocksConnectICCmd () virtual
Definition at line 53 of file BlocksConnectICCmd.cc.
{}
Member Function Documentation
create()
BlocksConnectICCmd * BlocksConnectICCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 119 of file BlocksConnectICCmd.cc.
{
    return new BlocksConnectICCmd();
}
References BlocksConnectICCmd().
Do()
bool BlocksConnectICCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 61 of file BlocksConnectICCmd.cc.
                       {
    assert(view() != NULL);
    TTAMachine::Machine* machine =
        dynamic_cast<MDFDocument*>(view()->GetDocument())
            ->getModel()
            ->getMachine();
    Model* model =
        dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel();
    model->pushToStack();
    // open up a temporary dsdb
    const std::string dsdbFile = "tmp.dsdb";
    FileSystem::removeFileOrDirectory(dsdbFile);
    DSDBManager* dsdb = DSDBManager::createNew(dsdbFile);
    RowID archID = dsdb->addArchitecture(*machine);
    DSDBManager::MachineConfiguration confIn(archID, false, ILLEGAL_ROW_ID);
    RowID confID = dsdb->addConfiguration(confIn);
    // load BlocksConnectIC explorer plugin
    DesignSpaceExplorer explorer;
    DesignSpaceExplorerPlugin* plugin =
        explorer.loadExplorerPlugin("BlocksConnectIC", dsdb);
    plugin->setDSDB(*dsdb);
    try {
        std::vector<RowID> result = plugin->explore(confID, 0);
        // store the new machine
        TTAMachine::Machine& newMachine =
            *dsdb->architecture(confID + result.size());
        machine->copyFromMachine(newMachine);
    } catch (Exception const& e) {
        std::cerr << "Could not create Blocks Connect IC" << std::endl;
        FileSystem::removeFileOrDirectory(dsdbFile);
        model->popFromStack();
        return false;
    }
    FileSystem::removeFileOrDirectory(dsdbFile);
    model->notifyObservers();
    return true;
}
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::architecture(), assert, TTAMachine::Machine::copyFromMachine(), DSDBManager::createNew(), DesignSpaceExplorerPlugin::explore(), ILLEGAL_ROW_ID, DesignSpaceExplorer::loadExplorerPlugin(), machine, Model::notifyObservers(), Model::popFromStack(), Model::pushToStack(), FileSystem::removeFileOrDirectory(), DesignSpaceExplorer::setDSDB(), and EditorCommand::view().
id()
int BlocksConnectICCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 111 of file BlocksConnectICCmd.cc.
{
    return ProDeConstants::COMMAND_BLOCKS_CONNECT_IC;
}
References ProDeConstants::COMMAND_BLOCKS_CONNECT_IC.
isEnabled()
bool BlocksConnectICCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 139 of file BlocksConnectICCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    wxView* view = manager->GetCurrentView();
    if (view == NULL) {
        return false;
    }
    Model* model =
        dynamic_cast<MDFDocument*>(view->GetDocument())->getModel();
    if (model == NULL) {
        return false;
    }
    return true;
}
References EditorCommand::view().
shortName()
std::string BlocksConnectICCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 127 of file BlocksConnectICCmd.cc.
{
    return ProDeConstants::CMD_SNAME_BLOCKS_CONNECT_IC;
}
References ProDeConstants::CMD_SNAME_BLOCKS_CONNECT_IC.
The documentation for this class was generated from the following files:
BlocksConnectICCmd.hh
BlocksConnectICCmd.cc