OpenASIP: ProgramGraph Class Reference
ProgramGraph Class Reference
#include <ProgramGraph.hh>
Public Member Functions
ProgramGraph (TTAProgram::Program &program, const TTAMachine::Machine &mach)
virtual ~ProgramGraph ()
TTAProgram::Program & generateProgram () const
MoveNode & nodeOf (const TTAProgram::Move &) const
int graphCount () const
ProgramDependenceGraph * graphAt (int)
ProgramDependenceGraph * graph (const std::string)
Private Member Functions
void clear ()
ProgramGraph (const ProgramGraph &)
Copying forbidden.
ProgramGraph & operator= (const ProgramGraph &)
Assignment forbidden.
Private Attributes
TTAProgram::Program & program_
Original program.
std::vector< ControlFlowGraph * > cfgs_
Vector of CFG's for each procedure.
std::vector< ControlDependenceGraph * > cdgs_
Vector of CDG's for each procedure.
std::vector< DataDependenceGraph * > ddgs_
Vector of DDG's for each procedure.
std::vector< ProgramDependenceGraph * > pdgs_
Vector of PDG's for each procedure.
Detailed Description
Definition at line 60 of file ProgramGraph.hh.
Constructor & Destructor Documentation
ProgramGraph() [1/2]
ProgramGraph::ProgramGraph (TTAProgram::Program & program, const TTAMachine::Machine & mach)
Constructor.
Creates a new ProgramGraph from Program
Parameters
program Program in POM
Definition at line 54 of file ProgramGraph.cc.
    : program_(program){
    try {
        for (int i = 0; i < program.procedureCount(); i++) {
            ControlFlowGraph* cfg = NULL;
            cfg = new ControlFlowGraph(program.procedure(i));
            cfgs_.push_back(cfg);
            ControlDependenceGraph* cdg = NULL;
            try {
                cdg = new ControlDependenceGraph(*cfg);
                cdgs_.push_back(cdg);
            } catch (const InvalidData& e) {
                delete cdg;
                continue;
            }
            DataDependenceGraphBuilder builder;
            DataDependenceGraph* ddg = NULL;
            ddg = builder.build(*cfg, DataDependenceGraph::ALL_ANTIDEPS,mach);
            ddgs_.push_back(ddg);
            ProgramDependenceGraph* pdg = NULL;
            pdg = new ProgramDependenceGraph(*cdg, *ddg);
            pdgs_.push_back(pdg);
        }
    } catch (Exception&) {
        clear();
        throw;
    }
}
References DataDependenceGraph::ALL_ANTIDEPS, DataDependenceGraphBuilder::build(), cdgs_, cfgs_, clear(), ddgs_, pdgs_, and program.
~ProgramGraph()
ProgramGraph::~ProgramGraph () virtual
Destructor.
Removes the graphs.
Definition at line 99 of file ProgramGraph.cc.
{
    clear();
}
References clear().
ProgramGraph() [2/2]
ProgramGraph::ProgramGraph (const ProgramGraph &) private
Copying forbidden.
Member Function Documentation
clear()
void ProgramGraph::clear () private
Deletes all graphs owned by this.
Definition at line 87 of file ProgramGraph.cc.
{
    SequenceTools::deleteAllItems(pdgs_);
    SequenceTools::deleteAllItems(ddgs_);
    SequenceTools::deleteAllItems(cdgs_);
    SequenceTools::deleteAllItems(cfgs_);
}
References cdgs_, cfgs_, ddgs_, SequenceTools::deleteAllItems(), and pdgs_.
Referenced by ProgramGraph(), and ~ProgramGraph().
generateProgram()
TTAProgram::Program & ProgramGraph::generateProgram () const
Convert Program Graph to Program Object Model and returns POM
Returns
POM
TODO: convert PDG to POM this is basically scheduling
Definition at line 109 of file ProgramGraph.cc.
{
    ///TODO: convert PDG to POM
    /// this is basically scheduling
    return TTAProgram::NullProgram::instance();
}
References TTAProgram::NullProgram::instance().
graph()
ProgramDependenceGraph * ProgramGraph::graph (const std::string name)
Returns a PDG for procedure identified by procedure name.
Parameters
name name of a procedure
Returns
PDG for given procedure
Definition at line 157 of file ProgramGraph.cc.
{
    for (int i = 0; i < graphCount(); i++) {
        if (pdgs_.at(i)->name() == name) {
            return pdgs_.at(i);
        }
    }
    throw InvalidData(__FILE__, __LINE__, __func__, "Can not find graph of "
        "procedure " + name);
}
References __func__, graphCount(), and pdgs_.
graphAt()
ProgramDependenceGraph * ProgramGraph::graphAt (int i)
Returns a PDG for procedure identified by index.
Parameters
i index of a procedure
Returns
PDG for given procedure
Definition at line 143 of file ProgramGraph.cc.
{
    if (i < 0 || i >= graphCount()){
        throw InvalidData(__FILE__, __LINE__, __func__, "Trying to access"
            " graph out of a scope!");
    }
    return pdgs_.at(i);
}
References __func__, graphCount(), and pdgs_.
graphCount()
int ProgramGraph::graphCount () const
Returns number of PDG's in a program graph, equals number of procedures in program.
Returns
number of PDG's in a graph
Definition at line 133 of file ProgramGraph.cc.
{
    return pdgs_.size();
}
References pdgs_.
Referenced by graph(), and graphAt().
nodeOf()
MoveNode & ProgramGraph::nodeOf (const TTAProgram::Move &) const
Returns MoveNode of program representation corresponding to Move of POM.
Parameters
move move from POM
Returns
MoveNode corresponding to move
TODO: find a move and return corresponding MoveNode
Definition at line 122 of file ProgramGraph.cc.
{
    ///TODO: find a move and return corresponding MoveNode
    return *(new MoveNode());
}
operator=()
ProgramGraph & ProgramGraph::operator= (const ProgramGraph &) private
Assignment forbidden.
Member Data Documentation
cdgs_
std::vector<ControlDependenceGraph*> ProgramGraph::cdgs_ private
Vector of CDG's for each procedure.
Definition at line 86 of file ProgramGraph.hh.
Referenced by clear(), and ProgramGraph().
cfgs_
std::vector<ControlFlowGraph*> ProgramGraph::cfgs_ private
Vector of CFG's for each procedure.
Definition at line 84 of file ProgramGraph.hh.
Referenced by clear(), and ProgramGraph().
ddgs_
std::vector<DataDependenceGraph*> ProgramGraph::ddgs_ private
Vector of DDG's for each procedure.
Definition at line 88 of file ProgramGraph.hh.
Referenced by clear(), and ProgramGraph().
pdgs_
std::vector<ProgramDependenceGraph*> ProgramGraph::pdgs_ private
Vector of PDG's for each procedure.
Definition at line 90 of file ProgramGraph.hh.
Referenced by clear(), graph(), graphAt(), graphCount(), and ProgramGraph().
program_
TTAProgram::Program& ProgramGraph::program_ private
Original program.
Definition at line 81 of file ProgramGraph.hh.
The documentation for this class was generated from the following files:
ProgramGraph.hh
ProgramGraph.cc