OpenASIP: DCMFUResourceConflictDetector Class Reference
DCMFUResourceConflictDetector Class Reference
#include <DCMFUResourceConflictDetector.hh>
Public Member Functions
DCMFUResourceConflictDetector (const TTAMachine::FunctionUnit &fu)
virtual ~DCMFUResourceConflictDetector ()
virtual bool issueOperation (OperationID id)
virtual bool advanceCycle ()
virtual void reset ()
bool issueOperationInline (OperationID id)
bool advanceCycleInline ()
virtual OperationID operationID (const TCEString &operationName) const
Public Member Functions inherited from FUResourceConflictDetector
FUResourceConflictDetector ()
virtual ~FUResourceConflictDetector ()
virtual void endClock ()
virtual void advanceClock ()
virtual bool isIdle ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Private Attributes
FUCollisionMatrixIndex collisionMatrices_
The reservation tables of operations.
CollisionMatrix globalCollisionMatrix_
The global collision matrix.
const TTAMachine::FunctionUnit & fu_
The modeled FU.
Additional Inherited Members
Public Types inherited from FUResourceConflictDetector
typedef int OperationID
Type for identifying operations in the conflict detector interface.
Protected Attributes inherited from FUResourceConflictDetector
OperationIDIndex * operationIndices_
Map for finding indices for operations quickly.
Detailed Description
A Dynamic Collision Matrix (DCM) implementation of an FU resource conflict detector.
Definition at line 55 of file DCMFUResourceConflictDetector.hh.
Constructor & Destructor Documentation
DCMFUResourceConflictDetector()
DCMFUResourceConflictDetector::DCMFUResourceConflictDetector (const TTAMachine::FunctionUnit & fu)
Constructor.
Parameters
fu The function unit to detect conflicts for.
Exceptions
InvalidData If the model could not be built from the given FU.
Definition at line 47 of file DCMFUResourceConflictDetector.cc.
    : collisionMatrices_(fu),
      globalCollisionMatrix_(
          collisionMatrices_.at(0).columnCount(),
          collisionMatrices_.at(0).rowCount(), false),
      fu_(fu) {}
~DCMFUResourceConflictDetector()
DCMFUResourceConflictDetector::~DCMFUResourceConflictDetector () virtual
Destructor.
Definition at line 58 of file DCMFUResourceConflictDetector.cc.
{
}
Member Function Documentation
advanceCycle()
bool DCMFUResourceConflictDetector::advanceCycle () virtual
Simulates a cycle advance and reports a conflict if detected.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 79 of file DCMFUResourceConflictDetector.cc.
{
    return advanceCycleInline();
}
References advanceCycleInline().
advanceCycleInline()
bool DCMFUResourceConflictDetector::advanceCycleInline ()
Referenced by advanceCycle().
issueOperation()
bool DCMFUResourceConflictDetector::issueOperation (OperationID id) virtual
Issues an operation and reports a conflict if detected.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 69 of file DCMFUResourceConflictDetector.cc.
{
    return issueOperationInline(id);
}
References issueOperationInline().
issueOperationInline()
bool DCMFUResourceConflictDetector::issueOperationInline (OperationID id)
Referenced by issueOperation().
operationID()
DCMFUResourceConflictDetector::OperationID DCMFUResourceConflictDetector::operationID (const TCEString & operationName) const virtual
Returns an operation id for the given operation.
Operation IDs are used in the interface for optimizing the access. This method converts OSAL Operations to operation IDs.
Parameters
operation The OSAL Operation to find ID for.
Returns
The operation ID.
Reimplemented from FUResourceConflictDetector.
Definition at line 93 of file DCMFUResourceConflictDetector.cc.
{
    // find the index of the operation in the FU, it corresponds to the
    // operation ID
    for (int i = 0; i < fu_.operationCount(); ++i) {
        if (StringTools::ciEqual(fu_.operation(i)->name(), operationName)) {
            return i;
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, __func__, "Operation not found.");
}
References __func__, StringTools::ciEqual(), fu_, TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), and TTAMachine::FunctionUnit::operationCount().
reset()
void DCMFUResourceConflictDetector::reset () virtual
Sets the state of the detector to its initial state.
This means that the FU state is assumed to be what it is in powerup.
Reimplemented from FUResourceConflictDetector.
Definition at line 112 of file DCMFUResourceConflictDetector.cc.
{
    globalCollisionMatrix_.setAllToZero();
}
References globalCollisionMatrix_, and BitMatrix::setAllToZero().
Member Data Documentation
collisionMatrices_
FUCollisionMatrixIndex DCMFUResourceConflictDetector::collisionMatrices_ private
The reservation tables of operations.
Definition at line 72 of file DCMFUResourceConflictDetector.hh.
fu_
const TTAMachine::FunctionUnit& DCMFUResourceConflictDetector::fu_ private
The modeled FU.
Definition at line 76 of file DCMFUResourceConflictDetector.hh.
Referenced by operationID().
globalCollisionMatrix_
CollisionMatrix DCMFUResourceConflictDetector::globalCollisionMatrix_ private
The global collision matrix.
Definition at line 74 of file DCMFUResourceConflictDetector.hh.
Referenced by reset().
The documentation for this class was generated from the following files:
DCMFUResourceConflictDetector.hh
DCMFUResourceConflictDetector.cc