OpenASIP: RFPortImplementationDialog Class Reference
RFPortImplementationDialog Class Reference
#include <RFPortImplementationDialog.hh>
Public Member Functions
RFPortImplementationDialog (wxWindow *parent, wxWindowID id, HDB::RFPortImplementation &implementation)
virtual ~RFPortImplementationDialog ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_NAME , ID_LABEL_LOAD_PORT , ID_LOAD_PORT ,
ID_LABEL_OPCODE_PORT , ID_OPCODE_PORT , ID_LABEL_OPCODE_PORT_WIDTH , ID_OPCODE_PORT_WIDTH ,
ID_DIRECTION , ID_LINE
}
Enumerated IDs for dialog widgets.
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Creates the dialog contents.
Private Attributes
HDB::RFPortImplementation & port_
FU port implementation to modify.
wxString name_
wxString loadPort_
wxString opcodePort_
wxString opcodePortWidth_
int direction_
Detailed Description
Dialog for editing register file port implementations.
Definition at line 45 of file RFPortImplementationDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerated IDs for dialog widgets.
Enumerator
ID_LABEL_NAME
ID_NAME
ID_LABEL_LOAD_PORT
ID_LOAD_PORT
ID_LABEL_OPCODE_PORT
ID_OPCODE_PORT
ID_LABEL_OPCODE_PORT_WIDTH
ID_OPCODE_PORT_WIDTH
ID_DIRECTION
ID_LINE
Definition at line 57 of file RFPortImplementationDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_NAME,
        ID_LABEL_LOAD_PORT,
        ID_LOAD_PORT,
        ID_LABEL_OPCODE_PORT,
        ID_OPCODE_PORT,
        ID_LABEL_OPCODE_PORT_WIDTH,
        ID_OPCODE_PORT_WIDTH,
        ID_DIRECTION,
        ID_LINE
    };
Constructor & Destructor Documentation
RFPortImplementationDialog()
RFPortImplementationDialog::RFPortImplementationDialog (wxWindow * parent, wxWindowID id, HDB::RFPortImplementation & implementation)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog window.
port RF port implementation to modify.
Definition at line 53 of file RFPortImplementationDialog.cc.
                                                                 :
    wxDialog(parent, id, _T("Register File Port Implementation")),
    port_(port) {
    createContents(this, true, true);
    name_ = WxConversion::toWxString(port_.name());
    loadPort_ = WxConversion::toWxString(port_.loadPort());
    opcodePort_ = WxConversion::toWxString(port_.opcodePort());
    opcodePortWidth_ =
        WxConversion::toWxString(port_.opcodePortWidthFormula());
    direction_ = port_.direction();
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_LOAD_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &loadPort_));
    FindWindow(ID_OPCODE_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &opcodePort_));
    FindWindow(ID_OPCODE_PORT_WIDTH)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &opcodePortWidth_));
    FindWindow(ID_DIRECTION)->SetValidator(wxGenericValidator(&direction_));
    TransferDataToWindow();
}
References WxConversion::toWxString().
~RFPortImplementationDialog()
RFPortImplementationDialog::~RFPortImplementationDialog () virtual
The Destructor.
Definition at line 83 of file RFPortImplementationDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * RFPortImplementationDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Creates the dialog contents.
Definition at line 128 of file RFPortImplementationDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_LOAD_PORT, wxT("Load port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_LOAD_PORT, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item6, 0, wxGROW|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_OPCODE_PORT, wxT("Opcode port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALL, 5 );
    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_OPCODE_PORT, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_LABEL_OPCODE_PORT_WIDTH, wxT("Opcode port width formula:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_OPCODE_PORT_WIDTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item10, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxString strs11[] =
    {
        wxT("In"),
        wxT("Out"),
        wxT("Bidirectional")
    };
    wxRadioBox *item11 = new wxRadioBox( parent, ID_DIRECTION, wxT("Direction:"), wxDefaultPosition, wxDefaultSize, 3, strs11, 1, wxRA_SPECIFY_COLS );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item12 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item12, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item14 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item15 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item13, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DIRECTION, ID_LABEL_LOAD_PORT, ID_LABEL_NAME, ID_LABEL_OPCODE_PORT, ID_LABEL_OPCODE_PORT_WIDTH, ID_LINE, ID_LOAD_PORT, ID_NAME, ID_OPCODE_PORT, and ID_OPCODE_PORT_WIDTH.
onOK()
void RFPortImplementationDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 90 of file RFPortImplementationDialog.cc.
{
    TransferDataFromWindow();
    name_ = name_.Trim(true).Trim(false);
    loadPort_ = loadPort_.Trim(true).Trim(false);
    opcodePort_ = opcodePort_.Trim(true).Trim(false);
    opcodePortWidth_ = opcodePortWidth_.Trim(true).Trim(false);
    if (name_.IsEmpty()) {
        wxString message = _T("Name field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    port_.setName(WxConversion::toString(name_));
    port_.setLoadPort(WxConversion::toString(loadPort_));
    port_.setOpcodePort(WxConversion::toString(opcodePort_));
    port_.setOpcodePortWidthFormula(WxConversion::toString(opcodePortWidth_));
    if (direction_ == 0) {
        port_.setDirection(IN);
    } else if (direction_ == 1) {
        port_.setDirection(OUT);
    } else if (direction_ == 2) {
        port_.setDirection(BIDIR);
    } else {
        assert(false);
    }
    EndModal(wxID_OK);
}
References assert, HDB::BIDIR, direction_, HDB::IN, loadPort_, name_, opcodePort_, opcodePortWidth_, HDB::OUT, port_, HDB::RFPortImplementation::setDirection(), HDB::PortImplementation::setLoadPort(), HDB::PortImplementation::setName(), HDB::RFPortImplementation::setOpcodePort(), HDB::RFPortImplementation::setOpcodePortWidthFormula(), and WxConversion::toString().
Member Data Documentation
direction_
int RFPortImplementationDialog::direction_ private
Definition at line 80 of file RFPortImplementationDialog.hh.
Referenced by onOK().
loadPort_
wxString RFPortImplementationDialog::loadPort_ private
Definition at line 77 of file RFPortImplementationDialog.hh.
Referenced by onOK().
name_
wxString RFPortImplementationDialog::name_ private
Definition at line 76 of file RFPortImplementationDialog.hh.
Referenced by onOK().
opcodePort_
wxString RFPortImplementationDialog::opcodePort_ private
Definition at line 78 of file RFPortImplementationDialog.hh.
Referenced by onOK().
opcodePortWidth_
wxString RFPortImplementationDialog::opcodePortWidth_ private
Definition at line 79 of file RFPortImplementationDialog.hh.
Referenced by onOK().
port_
HDB::RFPortImplementation& RFPortImplementationDialog::port_ private
FU port implementation to modify.
Definition at line 74 of file RFPortImplementationDialog.hh.
Referenced by onOK().
The documentation for this class was generated from the following files:
RFPortImplementationDialog.hh
RFPortImplementationDialog.cc