OpenASIP: UnitPortFactory Class Reference
UnitPortFactory Class Reference
#include <UnitPortFactory.hh>
Public Member Functions
UnitPortFactory (EditPolicyFactory &editPolicyFactory)
virtual ~UnitPortFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
UnitPortFactory & operator= (UnitPortFactory &old)
Assignment not allowed.
UnitPortFactory (UnitPortFactory &old)
Copying not allowed.
void addSocket (EditPart *portEditPart, TTAMachine::MachinePart *socket) const
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating port EditParts corresponding to a given Machine port object.
Definition at line 45 of file UnitPortFactory.hh.
Constructor & Destructor Documentation
UnitPortFactory() [1/2]
UnitPortFactory::UnitPortFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 54 of file UnitPortFactory.cc.
                                                                    :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new SocketFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~UnitPortFactory()
UnitPortFactory::~UnitPortFactory () virtual
The Destructor.
Definition at line 63 of file UnitPortFactory.cc.
{
}
UnitPortFactory() [2/2]
UnitPortFactory::UnitPortFactory (UnitPortFactory & old) private
Copying not allowed.
Member Function Documentation
addSocket()
void UnitPortFactory::addSocket (EditPart * portEditPart, TTAMachine::MachinePart * socket) const private
Creates an EditPart of a socket and adds it as a child to the given EditPart.
Parameters
socket Socket of which to create the EditPart.
portEditPart Port in which to add the socket as a child.
Definition at line 136 of file UnitPortFactory.cc.
{
    EditPart* socketEditPart = NULL;
    vector<Factory*>::const_iterator i = factories_.begin();
    while (socketEditPart == NULL && i != factories_.end()) {
    socketEditPart = (*i)->createEditPart(socket);
    i++;
    }
    assert(socketEditPart != NULL);
    SocketPortConnFactory connFactory;
    socketEditPart->addChild(
    connFactory.createConnection(
        portEditPart, socketEditPart));
    portEditPart->addChild(socketEditPart);
}
References EditPart::addChild(), assert, SocketPortConnFactory::createConnection(), and EditPartFactory::factories_.
Referenced by createEditPart().
createEditPart()
EditPart * UnitPortFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a port.
Parameters
component Port of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the Port class.
Implements Factory.
Definition at line 73 of file UnitPortFactory.cc.
{
    Port* port = dynamic_cast<Port*>(component);
    EditPart* portEditPart = NULL;
    if (port != NULL) {
    portEditPart = new EditPart();
    portEditPart->setModel(port);
        Figure* fig = NULL;
        FUPort* fuPort = dynamic_cast<FUPort*>(component);
        if (fuPort != NULL && fuPort->isTriggering()) {
            fig = new TriggeringPortFigure(port->name(), port->width());
        } else {
            fig = new UnitPortFigure(port->name(), port->width());
        }
    portEditPart->setFigure(fig);
    if (port->inputSocket() != NULL) {
        addSocket(portEditPart, port->inputSocket());
    }
    if (port->outputSocket() != NULL) {
        addSocket(portEditPart, port->outputSocket());
    }
    // number of possible unconnected sockets
    int unconnectedSockets = 2 - portEditPart->childCount();
    while (unconnectedSockets > 0) {
        if (port->unconnectedSocket(unconnectedSockets - 1) != NULL) {
        addSocket(
            portEditPart,
            port->unconnectedSocket(unconnectedSockets - 1));
        }
        unconnectedSockets--;
    }
    } else {
    return NULL;
    }
    portEditPart->setSelectable(true);
    // Install editpolicy common to all ports.
    EditPolicy* editPolicy = editPolicyFactory_.createPortEditPolicy();
    if (editPolicy != NULL) {
    portEditPart->installEditPolicy(editPolicy);
    }
    return portEditPart;
}
References addSocket(), EditPart::childCount(), EditPolicyFactory::createPortEditPolicy(), EditPartFactory::editPolicyFactory_, TTAMachine::Port::inputSocket(), EditPart::installEditPolicy(), TTAMachine::FUPort::isTriggering(), TTAMachine::Port::name(), TTAMachine::Port::outputSocket(), EditPart::setFigure(), EditPart::setModel(), EditPart::setSelectable(), TTAMachine::Port::unconnectedSocket(), and TTAMachine::Port::width().
operator=()
UnitPortFactory & UnitPortFactory::operator= (UnitPortFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
UnitPortFactory.hh
UnitPortFactory.cc