OpenASIP: OSEdOptionsSerializer Class Reference
OSEdOptionsSerializer Class Reference
#include <OSEdOptionsSerializer.hh>
Public Member Functions
OSEdOptionsSerializer ()
virtual ~OSEdOptionsSerializer ()
virtual void writeState (const ObjectState *state)
virtual ObjectState * readState ()
void setSourceFile (const std::string &fileName)
void setDestinationFile (const std::string &fileName)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Private Member Functions
OSEdOptionsSerializer (const OSEdOptionsSerializer &)
Copying not allowed.
OSEdOptionsSerializer & operator= (const OSEdOptionsSerializer &)
Assignment not allowed.
Private Attributes
XMLSerializer serializer_
Instance of XMLSerializer.
Detailed Description
Constructs the ObjectState tree that represents the options of OSEd.
Definition at line 44 of file OSEdOptionsSerializer.hh.
Constructor & Destructor Documentation
OSEdOptionsSerializer() [1/2]
OSEdOptionsSerializer::OSEdOptionsSerializer ()
Constructor.
Definition at line 40 of file OSEdOptionsSerializer.cc.
                                             : Serializer() {
}
~OSEdOptionsSerializer()
OSEdOptionsSerializer::~OSEdOptionsSerializer () virtual
Destructor.
Definition at line 46 of file OSEdOptionsSerializer.cc.
{
}
OSEdOptionsSerializer() [2/2]
OSEdOptionsSerializer::OSEdOptionsSerializer (const OSEdOptionsSerializer &) private
Copying not allowed.
Member Function Documentation
operator=()
OSEdOptionsSerializer & OSEdOptionsSerializer::operator= (const OSEdOptionsSerializer &) private
Assignment not allowed.
readState()
ObjectState * OSEdOptionsSerializer::readState () virtual
Reads the options file and returns the corresponding ObjectState tree.
Returns
The read ObjectState tree.
Implements TCETools::Serializer.
Definition at line 71 of file OSEdOptionsSerializer.cc.
{
    ObjectState* root = NULL;
    try {
        root = serializer_.readState();
    } catch (const Exception& e) {
        string method = "OSEdOptionsSerializer::readState()";
        string msg = "Problems reading the state: " + e.errorMessage();
        throw SerializerException(__FILE__, __LINE__, method, msg);
    }
    return root;
}
References Exception::errorMessage(), XMLSerializer::readState(), and serializer_.
Referenced by OSEd::OnInit().
setDestinationFile()
void OSEdOptionsSerializer::setDestinationFile (const std::string & fileName)
Sets the destination file.
Parameters
fileName The name of the file.
Definition at line 99 of file OSEdOptionsSerializer.cc.
{
    serializer_.setDestinationFile(fileName);
}
References serializer_, and XMLSerializer::setDestinationFile().
Referenced by OSEd::createDefaultOptions(), and OSEdOptionsDialog::onSave().
setSchemaFile()
void OSEdOptionsSerializer::setSchemaFile (const std::string & fileName)
Sets the schema file.
Parameters
fileName The name of the file.
Definition at line 109 of file OSEdOptionsSerializer.cc.
{
    serializer_.setSchemaFile(fileName);
}
References serializer_, and XMLSerializer::setSchemaFile().
setSourceFile()
void OSEdOptionsSerializer::setSourceFile (const std::string & fileName)
Sets the source file.
Parameters
fileName The name of the file.
Definition at line 89 of file OSEdOptionsSerializer.cc.
{
    serializer_.setSourceFile(fileName);
}
References serializer_, and XMLSerializer::setSourceFile().
Referenced by OSEd::OnInit().
setUseSchema()
void OSEdOptionsSerializer::setUseSchema (bool useSchema)
Modifies the usage of schema file (yes/no).
Parameters
useSchema True or false, depending on if schema should be used or not.
Definition at line 119 of file OSEdOptionsSerializer.cc.
{
    serializer_.setUseSchema(useSchema);
}
References serializer_, and XMLSerializer::setUseSchema().
writeState()
void OSEdOptionsSerializer::writeState (const ObjectState * state) virtual
Writes the object state tree to XML file.
Parameters
state State to be written.
Implements TCETools::Serializer.
Definition at line 55 of file OSEdOptionsSerializer.cc.
{
    try {
        serializer_.writeState(state);
    } catch (const Exception& e) {
        string method = "OSEdOptionsSerializer::writeState()";
        string msg = "Problems writing the state: " + e.errorMessage();
        throw SerializerException(__FILE__, __LINE__, method, msg);
    }
}
References Exception::errorMessage(), serializer_, and XMLSerializer::writeState().
Referenced by OSEd::createDefaultOptions(), and OSEdOptionsDialog::onSave().
Member Data Documentation
serializer_
XMLSerializer OSEdOptionsSerializer::serializer_ private
Instance of XMLSerializer.
Definition at line 64 of file OSEdOptionsSerializer.hh.
Referenced by readState(), setDestinationFile(), setSchemaFile(), setSourceFile(), setUseSchema(), and writeState().
The documentation for this class was generated from the following files:
OSEdOptionsSerializer.hh
OSEdOptionsSerializer.cc