OpenASIP: TPEF::TPEFDataSectionReader Class Reference
TPEF::TPEFDataSectionReader Class Reference
#include <TPEFDataSectionReader.hh>
Protected Member Functions
TPEFDataSectionReader (bool reg=true)
virtual ~TPEFDataSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFDataSectionReader (const TPEFDataSectionReader &)
Copying not allowed.
TPEFDataSectionReader & operator= (TPEFDataSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFDataSectionReader proto_
Prototype instance of TPEFDataSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads string section from TPEF binary file.
Definition at line 46 of file TPEFDataSectionReader.hh.
Constructor & Destructor Documentation
TPEFDataSectionReader() [1/2]
TPEF::TPEFDataSectionReader::TPEFDataSectionReader (bool reg = true) protected
Constructor.
Registers itself to SectionReader.
Definition at line 55 of file TPEFDataSectionReader.cc.
                                                     : TPEFSectionReader() {
    if (reg)
        SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFDataSectionReader()
TPEF::TPEFDataSectionReader::~TPEFDataSectionReader () protected virtual
Destructor.
Definition at line 63 of file TPEFDataSectionReader.cc.
{
}
TPEFDataSectionReader() [2/2]
TPEF::TPEFDataSectionReader::TPEFDataSectionReader (const TPEFDataSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFDataSectionReader & TPEF::TPEFDataSectionReader::operator= (TPEFDataSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFDataSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads data section of TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 89 of file TPEFDataSectionReader.cc.
{
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    DataSection* dataSection = dynamic_cast<DataSection*>(section);
    assert(dataSection != NULL);
    // check that link section is defined properly
    assert(header().linkId == 0);
    if (!section->noBits()) {
        while (stream.readPosition() <
               header().bodyOffset + header().bodyLength) {
            dataSection->addByte(stream.readByte());
        }
        dynamic_cast<TPEFReader*>(
            parent())->addSectionSize(section, header().bodyLength);
    }
}
References TPEF::DataSection::addByte(), assert, TPEF::TPEFSectionReader::Header::bodyLength, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::TPEFSectionReader::parent(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), and TPEF::BinaryStream::readPosition().
type()
Section::SectionType TPEF::TPEFDataSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Reimplemented in TPEF::TPEFLEDataSectionReader.
Definition at line 72 of file TPEFDataSectionReader.cc.
{
    return Section::ST_DATA;
}
References TPEF::Section::ST_DATA.
Member Data Documentation
proto_
TPEFDataSectionReader TPEF::TPEFDataSectionReader::proto_ static private
Prototype instance of TPEFDataSectionReader to be registered to SectionReader.
Definition at line 63 of file TPEFDataSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFDataSectionReader.hh
TPEFDataSectionReader.cc