OpenASIP: RunCommand Class Reference
RunCommand Class Reference
#include <RunCommand.hh>
Public Member Functions
RunCommand ()
virtual ~RunCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "run" command of the Simulator Control Language.
Definition at line 47 of file RunCommand.hh.
Constructor & Destructor Documentation
RunCommand()
RunCommand::RunCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 47 of file RunCommand.cc.
                       : SimControlLanguageCommand("run") {
}
~RunCommand()
RunCommand::~RunCommand () virtual
Destructor.
Does nothing.
Definition at line 55 of file RunCommand.cc.
{
}
Member Function Documentation
execute()
bool RunCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "run" command.
Starts the simulation.
Parameters
arguments No arguments needed.
Returns
Always true.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 69 of file RunCommand.cc.
{
    if (!checkSimulationNotAlreadyRunning() ||
        !checkSimulationInitialized()) {
        return false;
    }
    simulatorFrontend().run();
    printStopInformation();
    return true;
}
References SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationNotAlreadyRunning(), SimControlLanguageCommand::printStopInformation(), SimulatorFrontend::run(), and SimControlLanguageCommand::simulatorFrontend().
helpText()
std::string RunCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 92 of file RunCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_RUN).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_RUN.
The documentation for this class was generated from the following files:
RunCommand.hh
RunCommand.cc