OpenASIP: TTAProgram::DataDefinition Class Reference
TTAProgram::DataDefinition Class Reference
#include <DataDefinition.hh>
Public Member Functions
DataDefinition (Address start, int size, bool littleEndian, MinimumAddressableUnit *initData=NULL, bool allZeros=false)
DataDefinition (Address start, const std::vector< MinimumAddressableUnit > &initData, bool littleEndian)
virtual ~DataDefinition ()
virtual Address startAddress () const
virtual void setStartAddress (Address start)
virtual bool isInitialized () const
virtual MinimumAddressableUnit MAU (int index) const
virtual int size () const
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual Address destinationAddress () const
virtual void setDestinationAddress (Address dest)
virtual DataDefinition * copy () const
bool isLittleEndian () const
Private Attributes
Address start_
Start address of definition.
int size_
Size of uninitialized data definition.
std::vector< MinimumAddressableUnit > * data_
Init data of definition.
bool allZeros_
Is all the data zeros? (In this case data_ is null)
bool littleEndian_
Detailed Description
Describes characteristics of an initialized or uninitialized memory area.
Definition at line 52 of file DataDefinition.hh.
Constructor & Destructor Documentation
DataDefinition() [1/2]
TTAProgram::DataDefinition::DataDefinition (Address start, int size, bool littleEndian, MinimumAddressableUnit * initData = NULL, bool allZeros = false)
Creates data area definition.
Parameters
start Starting address of definition.
size Number of MAUs that area represents.
initData Table of initialization data if initialized definition.
Exceptions
OutOfRange In case the initialization data contains data that do not fit in a MAU.
Definition at line 52 of file DataDefinition.cc.
    : start_(start),
      size_(size),
      allZeros_(allZeros),
      littleEndian_(littleEndian) {
    if (initData != NULL) {
        data_ = new std::vector<MinimumAddressableUnit>(size);
        for (int i = 0 ; i < size; i++) {
            const int mauBits = start.space().width();
            const MinimumAddressableUnit mau = initData[i];
            if (MathTools::requiredBits(mau) > mauBits) {
                if (MathTools::requiredBitsSigned(mau) > mauBits) {
                    throw OutOfRange(
                        __FILE__, __LINE__, __func__,
                        "The given value does not fit to the MAU of address "
                        "space.");
                }
            }
            (*data_)[i] = mau;
        }
    } else {
        data_ = NULL;
    }
}
References __func__, data_, MathTools::requiredBits(), MathTools::requiredBitsSigned(), size(), TTAProgram::Address::space(), and TTAMachine::AddressSpace::width().
DataDefinition() [2/2]
TTAProgram::DataDefinition::DataDefinition (Address start, const std::vector< MinimumAddressableUnit > & initData, bool littleEndian)
Creates initialized data area definition.
Parameters
start Starting address of definition.
initData Initialization data.
Exceptions
OutOfRange In case the initialization data contains data that do not fit in a MAU.
Definition at line 89 of file DataDefinition.cc.
    : start_(start), allZeros_(false), littleEndian_(littleEndian) {
    // check that the MAUs are not too large for the address space
    for (std::size_t i = 0 ; i < initData.size(); i++) {
        const int mauBits = start.space().width();
        const MinimumAddressableUnit mau = initData[i];
        if (MathTools::requiredBits(mau) > mauBits) {
            if (MathTools::requiredBitsSigned(mau) > mauBits) {
                throw OutOfRange(
                    __FILE__, __LINE__, __func__,
                    "The given value does not fit to the MAU of address "
                    "space.");
            }
        }
    }
    data_ = new std::vector<MinimumAddressableUnit>(initData);
    size_ = data_->size();
}
References __func__, data_, MathTools::requiredBits(), MathTools::requiredBitsSigned(), size_, TTAProgram::Address::space(), and TTAMachine::AddressSpace::width().
~DataDefinition()
TTAProgram::DataDefinition::~DataDefinition () virtual
Frees all the init data if there is any.
Definition at line 116 of file DataDefinition.cc.
{
    if (data_ != NULL) {
        delete data_;
        data_ = NULL;
    }
}
References data_.
Member Function Documentation
copy()
DataDefinition * TTAProgram::DataDefinition::copy () const virtual
POM style copy constructor, which supports dynamic binding.
Returns
Copy of the object.
Reimplemented in TTAProgram::DataAddressDef, and TTAProgram::DataInstructionAddressDef.
Definition at line 262 of file DataDefinition.cc.
{
    DataDefinition* newDef = NULL;
    if (allZeros_) {
        newDef = new DataDefinition(start_, size_, littleEndian_, NULL, true);
    } else if (isInitialized()) {
        newDef = new DataDefinition(start_, *data_, littleEndian_);
    } else {
        newDef = new DataDefinition(start_, size_, littleEndian_);
    }
    return newDef;
}
References allZeros_, data_, isInitialized(), littleEndian_, size_, and start_.
Referenced by TTAProgram::DataMemory::copy(), and TTAProgram::Program::copyDataMemoriesFrom().
destinationAddress()
Address TTAProgram::DataDefinition::destinationAddress () const virtual
Returns address where to initialization data refers.
Returns
Address where to initialization data refers.
Reimplemented in TTAProgram::DataAddressDef, and TTAProgram::DataInstructionAddressDef.
Definition at line 241 of file DataDefinition.cc.
{
    throw WrongSubclass(
        __FILE__, __LINE__, __func__,
        "Data definition does not contain an address reference.");
}
References __func__.
Referenced by ControlFlowGraph::computeLeadersFromRelocations(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::ProgramWriter::createDataSections(), llvm::LLVMTCEBuilder::deleteDeadProcedures(), MAU(), and TTAProgram::Program::replaceUniversalAddressSpaces().
isAddress()
bool TTAProgram::DataDefinition::isAddress () const virtual
Returns true if init data of definition contains an address.
Returns
True if init data of definition contains an address.
Reimplemented in TTAProgram::DataAddressDef, and TTAProgram::DataInstructionAddressDef.
Definition at line 221 of file DataDefinition.cc.
{
    return false;
}
Referenced by TTAProgram::ProgramWriter::createDataSections(), MAU(), and TTAProgram::Program::replaceUniversalAddressSpaces().
isInitialized()
bool TTAProgram::DataDefinition::isInitialized () const virtual
Returns true if data definition contains initialization data.
Returns
True if data definition contains initialization data.
Reimplemented in TTAProgram::DataAddressDef, and TTAProgram::DataInstructionAddressDef.
Definition at line 144 of file DataDefinition.cc.
{
    return allZeros_ || (data_ != NULL);
}
References allZeros_, and data_.
Referenced by copy(), TTAProgram::ProgramWriter::createDataSections(), POMDisassembler::dataDefDescription(), SimulatorFrontend::initializeDataMemories(), main(), and MAU().
isInstructionAddress()
bool TTAProgram::DataDefinition::isInstructionAddress () const virtual
Returns true if init data of definition contains an instruction address.
Returns
True if init data of definition contains an instruction address.
Reimplemented in TTAProgram::DataInstructionAddressDef.
Definition at line 231 of file DataDefinition.cc.
{
    return false;
}
Referenced by ControlFlowGraph::computeLeadersFromRelocations(), TTAProgram::Program::copyDataMemoriesFrom(), and TTAProgram::Program::replaceUniversalAddressSpaces().
isLittleEndian()
bool TTAProgram::DataDefinition::isLittleEndian () const inline
Definition at line 78 of file DataDefinition.hh.
{ return littleEndian_; }
References littleEndian_.
Referenced by TTAProgram::DataAddressDef::copy().
MAU()
MinimumAddressableUnit TTAProgram::DataDefinition::MAU (int index) const virtual
Returns one MAU of initialization values from requested index.
Parameters
index Index of the MAU whic is returned.
Returns
One MAU of initialization values from requested index.
Definition at line 155 of file DataDefinition.cc.
{
    assert(index < size());
    if (isAddress()) {
        if (littleEndian_) {
            index = size() - index -1;
        }
        MinimumAddressableUnit retVal = destinationAddress().location();
        // how many bits should be masked out
        int maskBits = index * startAddress().space().width();
        // how many bits is the whole area definition
        int totalAreaDefBits = size() * startAddress().space().width();
        // how many bits of the data definition should not be masked out
        int remainingBits = totalAreaDefBits - maskBits;
        // how many bits is value that is stored as a address
        int addressBits = sizeof(retVal) * BYTE_BITWIDTH;
        // how many bits will be masked from start of address
        int addressMaskBits = addressBits - remainingBits;
        // mask out bits if needed
        if (addressMaskBits >= 0) {
            retVal = retVal << addressMaskBits;
        } else {
            retVal = retVal >> (-addressMaskBits);
        }
        // align MAU bits to right
        retVal = retVal >> (addressBits - startAddress().space().width());
        // return MAU
        return retVal;
    } else if(allZeros_) {
        return 0;
    } else if (isInitialized()) {
        return (*data_)[index];
    } else {
        throw NotAvailable(
            __FILE__, __LINE__, __func__,
            "Definition does not contain initialisation data.");
    }
}
References __func__, allZeros_, assert, BYTE_BITWIDTH, data_, destinationAddress(), isAddress(), isInitialized(), littleEndian_, TTAProgram::Address::location(), size(), TTAProgram::Address::space(), startAddress(), and TTAMachine::AddressSpace::width().
Referenced by TTAProgram::ProgramWriter::createDataSections(), POMDisassembler::dataDefDescription(), SimulatorFrontend::initializeDataMemories(), and main().
setDestinationAddress()
void TTAProgram::DataDefinition::setDestinationAddress (Address dest) virtual
Set new destination address for the data definition.
Reimplemented in TTAProgram::DataAddressDef.
Definition at line 251 of file DataDefinition.cc.
{
    throw WrongSubclass(
        __FILE__, __LINE__, __func__,
        "Data definition does not refer to a data address.");
}
References __func__.
Referenced by TTAProgram::Program::replaceUniversalAddressSpaces().
setStartAddress()
void TTAProgram::DataDefinition::setStartAddress (Address start) virtual
Definition at line 134 of file DataDefinition.cc.
{
    start_ = start;
}
References start_.
Referenced by TTAProgram::DataMemory::setAddressSpace().
size()
int TTAProgram::DataDefinition::size () const virtual
Returns the number of MAUs represented by definition.
Returns
The number of MAUs represented by definition.
Definition at line 211 of file DataDefinition.cc.
{
    return size_;
}
References size_.
Referenced by StaticProgramAnalyzer::addProgram(), TTAProgram::DataAddressDef::copy(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), llvm::LLVMTCEBuilder::createFPDataDefinition(), llvm::LLVMTCEBuilder::createGlobalValueDataDefinition(), llvm::LLVMTCEBuilder::createIntDataDefinition(), POMDisassembler::dataDefDescription(), TTAProgram::DataMemory::dataDefinition(), DataDefinition(), TTAProgram::DataMemory::dataDefinitionCount(), TTAProgram::DataMemory::dataDefinitionsEnd(), SimulatorFrontend::initializeDataMemories(), main(), and MAU().
startAddress()
Address TTAProgram::DataDefinition::startAddress () const virtual
Returns start address of data definition.
Returns
Start address of data definition.
Definition at line 129 of file DataDefinition.cc.
{
    return start_;
}
References start_.
Referenced by TTAProgram::DataMemory::addDataDefinition(), StaticProgramAnalyzer::addProgram(), TTAProgram::DataAddressDef::copy(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::DataMemory::dataDefinition(), TTAProgram::DataMemory::dataDefinitionsEnd(), POMDisassembler::disassembleProgram(), SimulatorFrontend::initializeDataMemories(), main(), MAU(), and TTAProgram::DataMemory::setAddressSpace().
Member Data Documentation
allZeros_
bool TTAProgram::DataDefinition::allZeros_ private
Is all the data zeros? (In this case data_ is null)
Definition at line 91 of file DataDefinition.hh.
Referenced by copy(), isInitialized(), and MAU().
data_
std::vector<MinimumAddressableUnit>* TTAProgram::DataDefinition::data_ private
Init data of definition.
Definition at line 88 of file DataDefinition.hh.
Referenced by copy(), DataDefinition(), DataDefinition(), isInitialized(), MAU(), and ~DataDefinition().
littleEndian_
bool TTAProgram::DataDefinition::littleEndian_ private
Definition at line 93 of file DataDefinition.hh.
Referenced by copy(), isLittleEndian(), and MAU().
size_
int TTAProgram::DataDefinition::size_ private
Size of uninitialized data definition.
Definition at line 85 of file DataDefinition.hh.
Referenced by copy(), DataDefinition(), and size().
start_
Address TTAProgram::DataDefinition::start_ private
Start address of definition.
Definition at line 82 of file DataDefinition.hh.
Referenced by copy(), setStartAddress(), and startAddress().
The documentation for this class was generated from the following files:
DataDefinition.hh
DataDefinition.cc