OpenASIP: AddRFCmd Class Reference
AddRFCmd Class Reference
#include <AddRFCmd.hh>
Public Member Functions
AddRFCmd ()
virtual bool Do ()
virtual int id () const
virtual AddRFCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new register files to the Machine.
Displays a register file dialog and creates a new register file according to the dialog output.
Definition at line 43 of file AddRFCmd.hh.
Constructor & Destructor Documentation
AddRFCmd()
AddRFCmd::AddRFCmd ()
The Constructor.
Definition at line 54 of file AddRFCmd.cc.
                   :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_RF) {
}
Referenced by create().
Member Function Documentation
create()
AddRFCmd * AddRFCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 126 of file AddRFCmd.cc.
                       {
    return new AddRFCmd();
}
References AddRFCmd().
Do()
bool AddRFCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file AddRFCmd.cc.
             {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    // Generate name for the new RF.
    Machine::RegisterFileNavigator navigator =
        model->getMachine()->registerFileNavigator();
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_RF;
    int i = 1;
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_RF +
            Conversion::toString(i);
        i++;
    }
    RegisterFile* rf = new RegisterFile(
        newName, ModelConstants::DEFAULT_RF_SIZE,
        ModelConstants::DEFAULT_WIDTH,
        ModelConstants::DEFAULT_RF_MAX_READS,
        ModelConstants::DEFAULT_RF_MAX_WRITES,
        ModelConstants::DEFAULT_RF_GUARD_LATENCY, RegisterFile::NORMAL);
    rf->setMachine(*(model->getMachine()));
    RFDialog dialog(parentWindow(), rf);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    // register file creation was cancelled
    model->popFromStack();
    return false;
    }
}
References assert, ProDeConstants::COMP_NEW_NAME_PREFIX_RF, ModelConstants::DEFAULT_RF_GUARD_LATENCY, ModelConstants::DEFAULT_RF_MAX_READS, ModelConstants::DEFAULT_RF_MAX_WRITES, ModelConstants::DEFAULT_RF_SIZE, ModelConstants::DEFAULT_WIDTH, Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::RegisterFile::NORMAL, Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), TTAMachine::Machine::registerFileNavigator(), TTAMachine::Unit::setMachine(), Conversion::toString(), and EditorCommand::view().
id()
int AddRFCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 115 of file AddRFCmd.cc.
                   {
    return ProDeConstants::COMMAND_ADD_RF;
}
References ProDeConstants::COMMAND_ADD_RF.
isEnabled()
bool AddRFCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 149 of file AddRFCmd.cc.
                    {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddRFCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 136 of file AddRFCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_RF;
}
References ProDeConstants::CMD_SNAME_ADD_RF.
The documentation for this class was generated from the following files:
AddRFCmd.hh
AddRFCmd.cc