OpenASIP: ProximCmdHistoryWindow Class Reference
ProximCmdHistoryWindow Class Reference
#include <ProximCmdHistoryWindow.hh>
Public Member Functions
ProximCmdHistoryWindow (ProximMainFrame *parent, wxWindowID id, ProximLineReader &lineReader)
virtual ~ProximCmdHistoryWindow ()
Public Member Functions inherited from ProximSimulatorWindow
virtual void reset ()
Private Types
enum { ID_LIST = 10000 , ID_SAVE , ID_CLOSE , ID_LINE }
Private Member Functions
void onSimulatorCommand (SimulatorEvent &event)
void updateCommandList ()
wxSizer * createContents (wxWindow *parent, bool set_sizer, bool call_fit)
void onClose (wxCommandEvent &event)
void onSave (wxCommandEvent &event)
void onCommandDClick (wxCommandEvent &event)
Private Attributes
ProximLineReader & lineReader_
Line reader storing the command history.
wxListBox * cmdList_
ListBox widget displaying the command history.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Window for browsing Proxim command history.
Definition at line 47 of file ProximCmdHistoryWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LIST
ID_SAVE
ID_CLOSE
ID_LINE
Definition at line 65 of file ProximCmdHistoryWindow.hh.
         {
        ID_LIST = 10000,
        ID_SAVE,
        ID_CLOSE,
        ID_LINE
    };
Constructor & Destructor Documentation
ProximCmdHistoryWindow()
ProximCmdHistoryWindow::ProximCmdHistoryWindow (ProximMainFrame * parent, wxWindowID id, ProximLineReader & lineReader)
The Constructor.
Parameters
parent Proxim main frame.
lineReader Line reader handling the command history.
Definition at line 58 of file ProximCmdHistoryWindow.cc.
                                                                         :
    ProximSimulatorWindow(parent, id),
    lineReader_(lineReader) {
    createContents(this, true, true);
    cmdList_ = dynamic_cast<wxListBox*>(FindWindow(ID_LIST));
    updateCommandList();
}
~ProximCmdHistoryWindow()
ProximCmdHistoryWindow::~ProximCmdHistoryWindow () virtual
The Destructor.
Definition at line 73 of file ProximCmdHistoryWindow.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ProximCmdHistoryWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the window widgets.
Code generated by wxDesigner. Do not edit manually.
Parameters
parent Parent window of the window contents.
call_fit If true, resize the parent window to fit the created contents.
set_sizer If true, sets the created sizer as parent window contents.
Definition at line 177 of file ProximCmdHistoryWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxString *strs1 = (wxString*) NULL;
    wxListBox *item1 = new wxListBox( parent, ID_LIST, wxDefaultPosition, wxSize(300,300), 0, strs1, wxLB_SINGLE );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item2 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item2, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item4 = new wxButton( parent, ID_SAVE, wxT("&Save"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item5 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(-1,20), wxLI_VERTICAL );
    item3->Add( item5, 0, wxGROW|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, ID_CLOSE, wxT("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CLOSE, ID_LINE, ID_LIST, and ID_SAVE.
onClose()
void ProximCmdHistoryWindow::onClose (wxCommandEvent & event) private
Handles the Close button events.
Closes the window.
Definition at line 111 of file ProximCmdHistoryWindow.cc.
{
    GetParent()->Close();
}
onCommandDClick()
void ProximCmdHistoryWindow::onCommandDClick (wxCommandEvent & event) private
Event handler for the command list double clicks.
Sends the double clicked command to the linereader input.
Parameters
event Event of the item dclick.
Definition at line 123 of file ProximCmdHistoryWindow.cc.
{
    std::string command = WxConversion::toString(event.GetString());
    lineReader_.input(command);
}
References ProximLineReader::input(), lineReader_, and WxConversion::toString().
onSave()
void ProximCmdHistoryWindow::onSave (wxCommandEvent & event) private
Displays dialog for saving command history to a file.
Definition at line 132 of file ProximCmdHistoryWindow.cc.
{
    wxString title = _T("Save Command History");
    wxString filters = _T("Command history logs (*.log)|*.log|All files|*.*");
    wxFileDialog dialog(
        this, title, _T(""), _T("commands.log"), filters, wxSAVE);
    if (dialog.ShowModal() == wxID_CANCEL) {
        return;
    }
    std::string filename = WxConversion::toString(dialog.GetPath());
    std::ofstream file(filename.c_str());
    if (file.bad()) {
        wxString message = _T("Error saving file '.");
        message.Append(dialog.GetPath());
        message.Append(_T("'."));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    size_t cmdCount = lineReader_.inputsInHistory();
    for (size_t i = 0; i < cmdCount; i++) {
        std::string command =
            lineReader_.inputHistoryEntry(cmdCount - 1 - i);
        file << command << std::endl;
    }
    file.close();
}
References LineReader::inputHistoryEntry(), LineReader::inputsInHistory(), lineReader_, and WxConversion::toString().
onSimulatorCommand()
void ProximCmdHistoryWindow::onSimulatorCommand (SimulatorEvent & event) private
Calls history list update when a simulator event of a completed command is received.
Definition at line 99 of file ProximCmdHistoryWindow.cc.
{
    updateCommandList();
    event.Skip();
}
References updateCommandList().
updateCommandList()
void ProximCmdHistoryWindow::updateCommandList () private
Updates the command history list.
Definition at line 81 of file ProximCmdHistoryWindow.cc.
{
    cmdList_->Clear();
    for (size_t i = 0; i < lineReader_.inputsInHistory(); i++) {
        std::string command = lineReader_.inputHistoryEntry(i);
        cmdList_->Insert(WxConversion::toWxString(command), 0);
    }
    if (cmdList_->GetCount() > 0) {
        FindWindow(ID_SAVE)->Enable();
    } else {
        FindWindow(ID_SAVE)->Disable();
    }
}
References cmdList_, ID_SAVE, LineReader::inputHistoryEntry(), LineReader::inputsInHistory(), lineReader_, and WxConversion::toWxString().
Referenced by onSimulatorCommand().
Member Data Documentation
cmdList_
wxListBox* ProximCmdHistoryWindow::cmdList_ private
ListBox widget displaying the command history.
Definition at line 75 of file ProximCmdHistoryWindow.hh.
Referenced by updateCommandList().
lineReader_
ProximLineReader& ProximCmdHistoryWindow::lineReader_ private
Line reader storing the command history.
Definition at line 73 of file ProximCmdHistoryWindow.hh.
Referenced by onCommandDClick(), onSave(), and updateCommandList().
The documentation for this class was generated from the following files:
ProximCmdHistoryWindow.hh
ProximCmdHistoryWindow.cc