OpenASIP: DisassemblyMove Class Reference
DisassemblyMove Class Reference
#include <DisassemblyMove.hh>
Public Member Functions
DisassemblyMove (DisassemblyElement *source, DisassemblyElement *destination, DisassemblyGuard *guard=NULL)
virtual ~DisassemblyMove ()
virtual std::string toString () const
Public Member Functions inherited from DisassemblyInstructionSlot
virtual ~DisassemblyInstructionSlot ()
DisassemblyAnnotation & annotation (int index) const
void addAnnotation (DisassemblyAnnotation *annotation)
int annotationCount () const
Private Member Functions
DisassemblyMove (const DisassemblyMove &)
Coying not allowed.
DisassemblyMove & operator= (const DisassemblyMove &)
Assignment not allowed.
Private Attributes
DisassemblyElement * source_
The source of the move.
DisassemblyElement * destination_
The destination of the move.
DisassemblyGuard * guard_
Possible guard of the move.
Additional Inherited Members
Protected Member Functions inherited from DisassemblyInstructionSlot
DisassemblyInstructionSlot ()
Detailed Description
Represents a move in the disassembler.
Definition at line 44 of file DisassemblyMove.hh.
Constructor & Destructor Documentation
DisassemblyMove() [1/2]
DisassemblyMove::DisassemblyMove (DisassemblyElement * source, DisassemblyElement * destination, DisassemblyGuard * guard = NULL)
Creates disassembler of a move.
Parameters
source The source element of the move.
destination The destination element of the move.
guard Move guard, or NULL if the move is not guarded.
Definition at line 44 of file DisassemblyMove.cc.
                            :
    DisassemblyInstructionSlot(),
    source_(source), destination_(destination), guard_(guard) {
}
~DisassemblyMove()
DisassemblyMove::~DisassemblyMove () virtual
The destructor.
Definition at line 57 of file DisassemblyMove.cc.
{
    delete source_;
    delete destination_;
    if (guard_ != NULL) {
        delete guard_;
        guard_ = NULL;
    }
}
References destination_, guard_, and source_.
DisassemblyMove() [2/2]
DisassemblyMove::DisassemblyMove (const DisassemblyMove &) private
Coying not allowed.
Member Function Documentation
operator=()
DisassemblyMove & DisassemblyMove::operator= (const DisassemblyMove &) private
Assignment not allowed.
toString()
std::string DisassemblyMove::toString () const virtual
Disassembles the move.
Returns
Disassembled move as a string.
Implements DisassemblyInstructionSlot.
Definition at line 73 of file DisassemblyMove.cc.
{
    std::string disassembly;
    if (guard_ != NULL) {
        disassembly = guard_->toString();
    }
    disassembly =
        disassembly + source_->toString() + " -> " + destination_->toString();
    for (int i = 0; i < annotationCount(); i++) {
        disassembly += annotation(i).toString();
    }
    return disassembly;
}
References DisassemblyInstructionSlot::annotation(), DisassemblyInstructionSlot::annotationCount(), destination_, guard_, source_, DisassemblyAnnotation::toString(), DisassemblyGuard::toString(), and DisassemblyElement::toString().
Referenced by POMDisassembler::disassemble().
Member Data Documentation
destination_
DisassemblyElement* DisassemblyMove::destination_ private
The destination of the move.
Definition at line 63 of file DisassemblyMove.hh.
Referenced by toString(), and ~DisassemblyMove().
guard_
DisassemblyGuard* DisassemblyMove::guard_ private
Possible guard of the move.
Definition at line 65 of file DisassemblyMove.hh.
Referenced by toString(), and ~DisassemblyMove().
source_
DisassemblyElement* DisassemblyMove::source_ private
The source of the move.
Definition at line 61 of file DisassemblyMove.hh.
Referenced by toString(), and ~DisassemblyMove().
The documentation for this class was generated from the following files:
DisassemblyMove.hh
DisassemblyMove.cc