OpenASIP: ArrayProgramImageWriter Class Reference
ArrayProgramImageWriter Class Reference
#include <ArrayProgramImageWriter.hh>
Public Member Functions
ArrayProgramImageWriter (const InstructionBitVector &bits)
virtual ~ArrayProgramImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from ArrayImageWriter
ArrayImageWriter (const BitVector &bits, int rowLength)
virtual ~ArrayImageWriter ()
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
A program image writer that writes the program as an array. It can be copied to a VHDL file to initialize an array, for example.
Definition at line 44 of file ArrayProgramImageWriter.hh.
Constructor & Destructor Documentation
ArrayProgramImageWriter()
ArrayProgramImageWriter::ArrayProgramImageWriter (const InstructionBitVector & bits)
The constructor.
Parameters
bits The program image to write.
Definition at line 42 of file ArrayProgramImageWriter.cc.
                                      : ArrayImageWriter(bits, 0) {
}
~ArrayProgramImageWriter()
ArrayProgramImageWriter::~ArrayProgramImageWriter () virtual
The destructor.
Definition at line 50 of file ArrayProgramImageWriter.cc.
{
}
Member Function Documentation
writeImage()
void ArrayProgramImageWriter::writeImage (std::ostream & stream) const virtual
Writes the program image to the given output stream.
Parameters
stream The output stream.
Reimplemented from ArrayImageWriter.
Reimplemented in VhdlProgramImageWriter.
Definition at line 60 of file ArrayProgramImageWriter.cc.
{
    const BitVector& bits = this->bits();
    const InstructionBitVector* programBits =
        dynamic_cast<const InstructionBitVector*>(&bits);
    assert(programBits != NULL);
    unsigned int previousBoundary(0);
    for (unsigned int i = 1; i < programBits->instructionCount(); i++) {
        unsigned int instructionBoundary =
            programBits->instructionStartingPoint(i);
        stream << "\"";
        writeSequence(stream, instructionBoundary - previousBoundary);
        stream << "\"," << std::endl;
        previousBoundary = instructionBoundary;
    }
    stream << "\"";
    writeSequence(stream, bits.size() - previousBoundary);
    stream << "\"";
}
References assert, AsciiImageWriter::bits(), InstructionBitVector::instructionCount(), InstructionBitVector::instructionStartingPoint(), and AsciiImageWriter::writeSequence().
Referenced by VhdlProgramImageWriter::writeImage().
The documentation for this class was generated from the following files:
ArrayProgramImageWriter.hh
ArrayProgramImageWriter.cc