OpenASIP: SelectionFigure Class Reference
SelectionFigure Class Reference
#include <SelectionFigure.hh>
Public Member Functions
SelectionFigure (Figure *selection)
virtual ~SelectionFigure ()
void setSelection (Figure *selection)
virtual wxRect bounds () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
Private Member Functions
SelectionFigure & operator= (SelectionFigure &old)
Assignment not allowed.
SelectionFigure (SelectionFigure &old)
Copying not allowed.
Private Attributes
Figure * selection_
Selected part figure.
Static Private Attributes
static const int SELECT_BOX_MARGIN = 4
Width of the margin between the part figure and selection box.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a component selection.
Definition at line 45 of file SelectionFigure.hh.
Constructor & Destructor Documentation
SelectionFigure() [1/2]
SelectionFigure::SelectionFigure (Figure * selection)
The Constructor.
Parameters
selection Figure of the selected EditPart.
Definition at line 47 of file SelectionFigure.cc.
                                                 :
    Figure(), selection_(selection) {
}
~SelectionFigure()
SelectionFigure::~SelectionFigure () virtual
The Destructor.
Definition at line 54 of file SelectionFigure.cc.
{
}
SelectionFigure() [2/2]
SelectionFigure::SelectionFigure (SelectionFigure & old) private
Copying not allowed.
Member Function Documentation
bounds()
wxRect SelectionFigure::bounds () const virtual
Returns the Figure's bounding rectangle.
Returns
Figure's bounding rectangle.
Reimplemented from Figure.
Definition at line 111 of file SelectionFigure.cc.
{
    if (selection_ == NULL) {
        return wxRect(0, 0, 0, 0);
    }
    wxRect bounds = selection_->bounds();
    bounds.Offset(SELECT_BOX_MARGIN * -2, SELECT_BOX_MARGIN);
    bounds.Inflate(SELECT_BOX_MARGIN * 4);
    return bounds;
}
References Figure::bounds(), bounds(), SELECT_BOX_MARGIN, and selection_.
Referenced by bounds(), and drawSelf().
drawSelf()
void SelectionFigure::drawSelf (wxDC * dc) protected virtual
Draws the selection's figure on the given device context.
Reimplemented from Figure.
Definition at line 61 of file SelectionFigure.cc.
{
    // wxWidgets implementation of SVGFileDC doesnt support dashed lines, so
    // we draw solid blue line when some item is selected when saving to *.svg
    bool isSVGcontext = false;
#if wxCHECK_VERSION(3, 0, 0)
    if (dynamic_cast<wxSVGFileDC*> (dc)) {
        isSVGcontext = true;
    }
#endif
    // Draw blue rectangles around selected EditParts figures.
    if (selection_ != NULL) {
        wxPen pen = wxPen(wxColour(0,0,255), 2, wxSHORT_DASH);
        if (isSVGcontext) {
            pen.SetStyle(wxSOLID);
        }
        wxBrush brush = wxBrush(wxColor(0,0,0), wxTRANSPARENT);
        dc->SetBrush(brush);
        dc->SetPen(pen);
        wxRect bounds = selection_->bounds();
        dc->DrawRectangle(
            bounds.GetX()-SELECT_BOX_MARGIN,
            bounds.GetY()-SELECT_BOX_MARGIN,
            bounds.GetWidth() + 2*SELECT_BOX_MARGIN,
            bounds.GetHeight() + 2*SELECT_BOX_MARGIN);
    }
}
References Figure::bounds(), bounds(), SELECT_BOX_MARGIN, and selection_.
operator=()
SelectionFigure & SelectionFigure::operator= (SelectionFigure & old) private
Assignment not allowed.
setSelection()
void SelectionFigure::setSelection (Figure * selection)
Set the selected figure.
Selection figure will be drawn around the selected figure.
Parameters
selection Figure of the selected part.
Definition at line 100 of file SelectionFigure.cc.
{
    selection_ = selection;
}
References selection_.
Referenced by SelectTool::leftClick().
Member Data Documentation
SELECT_BOX_MARGIN
const int SelectionFigure::SELECT_BOX_MARGIN = 4 static private
Width of the margin between the part figure and selection box.
Definition at line 65 of file SelectionFigure.hh.
Referenced by bounds(), and drawSelf().
selection_
Figure* SelectionFigure::selection_ private
Selected part figure.
Definition at line 62 of file SelectionFigure.hh.
Referenced by bounds(), drawSelf(), and setSelection().
The documentation for this class was generated from the following files:
SelectionFigure.hh
SelectionFigure.cc