OpenASIP: TTAMachine::NullAddressSpace Class Reference
TTAMachine::NullAddressSpace Class Reference
#include <NullAddressSpace.hh>
Public Member Functions
virtual int width () const
virtual ULongWord start () const
virtual ULongWord end () const
virtual TCEString name () const override
virtual void setName (const std::string &name) override
virtual void setWidth (int width) override
virtual void setAddressBounds (ULongWord start, ULongWord end) override
virtual void setMachine (Machine &mach) override
virtual void unsetMachine ()
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::AddressSpace
AddressSpace (const std::string &name, int width, ULongWord minAddress, ULongWord maxAddress, Machine &owner)
AddressSpace (const ObjectState *state, Machine &owner)
virtual ~AddressSpace ()
virtual void addNumericalId (unsigned id)
virtual bool hasNumericalId (unsigned id) const
std::set< unsigned > numericalIds () const
bool setNumericalIds (const std::set< unsigned > &ids)
virtual void setShared (bool shared)
virtual bool isShared () const
bool operator== (const AddressSpace &other) const
bool operator!= (const AddressSpace &other) const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static NullAddressSpace & instance ()
Private Member Functions
NullAddressSpace ()
virtual ~NullAddressSpace ()
Static Private Attributes
static NullAddressSpace instance_
The only instance of NullAddressSpace.
static Machine machine_
Machine to which the null address space is registered.
Additional Inherited Members
Static Public Attributes inherited from TTAMachine::AddressSpace
static const std::string OSNAME_ADDRESS_SPACE = "adress_space"
ObjectState name for AddressSpace.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for the bit width.
static const std::string OSKEY_MIN_ADDRESS = "min_a"
ObjectState attribute key for minimum address.
static const std::string OSKEY_MAX_ADDRESS = "max_a"
ObjectState attribute key for maximum address.
static const std::string OSKEY_SHARED_MEMORY = "shared-memory"
static const std::string OSKEY_NUMERICAL_ID = "numerical-id"
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
A singleton class which represents a null AddressSpace.
All the methods abort the program.
Definition at line 45 of file NullAddressSpace.hh.
Constructor & Destructor Documentation
NullAddressSpace()
TTAMachine::NullAddressSpace::NullAddressSpace () private
The constructor.
Definition at line 44 of file NullAddressSpace.cc.
                                   :
    AddressSpace("NULL", 1, 0, 1, machine_) {
}
~NullAddressSpace()
TTAMachine::NullAddressSpace::~NullAddressSpace () private virtual
The destructor.
Definition at line 52 of file NullAddressSpace.cc.
{
}
Member Function Documentation
end()
ULongWord TTAMachine::NullAddressSpace::end () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 97 of file NullAddressSpace.cc.
{
    abortWithError("end()");
    return 0;
}
References abortWithError.
ensureRegistration()
void TTAMachine::NullAddressSpace::ensureRegistration (const Component & component) const virtual
Aborts the program with error message.
Exceptions
IllegalRegistration Never thrown.
Reimplemented from TTAMachine::Component.
Definition at line 183 of file NullAddressSpace.cc.
{
    abortWithError("ensureRegistration()");
}
References abortWithError.
instance()
NullAddressSpace & TTAMachine::NullAddressSpace::instance () static
Returns the only instance of NullAddressSpace.
Returns
The only instance of NullAddressSpace.
Definition at line 62 of file NullAddressSpace.cc.
{
    return instance_;
}
References instance_.
Referenced by SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::setMemoryAddress(), and TTAProgram::NullAddress::space().
isRegistered()
bool TTAMachine::NullAddressSpace::isRegistered () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 193 of file NullAddressSpace.cc.
{
    abortWithError("isRegistered()");
    return false;
}
References abortWithError.
loadState()
void TTAMachine::NullAddressSpace::loadState (const ObjectState * state) virtual
Aborts the program with error message.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 217 of file NullAddressSpace.cc.
{
    abortWithError("loadState()");
}
References abortWithError.
machine()
Machine * TTAMachine::NullAddressSpace::machine () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 171 of file NullAddressSpace.cc.
{
    abortWithError("machine()");
    return NULL;
}
References abortWithError.
name()
TCEString TTAMachine::NullAddressSpace::name () const override virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 109 of file NullAddressSpace.cc.
{
    abortWithError("name()");
    return "";
}
References abortWithError.
saveState()
ObjectState * TTAMachine::NullAddressSpace::saveState () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 205 of file NullAddressSpace.cc.
{
    abortWithError("saveState()");
    return NULL;
}
References abortWithError.
setAddressBounds()
void TTAMachine::NullAddressSpace::setAddressBounds (ULongWord start, ULongWord end) override virtual
Aborts the program with error message.
Exceptions
OutOfRange Never thrown.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 142 of file NullAddressSpace.cc.
{
    abortWithError("setAddressBounds()");
}
References abortWithError.
setMachine()
void TTAMachine::NullAddressSpace::setMachine (Machine & mach) override virtual
Aborts the program with error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 152 of file NullAddressSpace.cc.
{
    abortWithError("setMachine()");
}
References abortWithError.
setName()
void TTAMachine::NullAddressSpace::setName (const std::string & name) override virtual
Aborts the program with error message.
Exceptions
ComponentAlreadyExists Never thrown.
InvalidName Never thrown.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 122 of file NullAddressSpace.cc.
{
    abortWithError("setName()");
}
References abortWithError.
setWidth()
void TTAMachine::NullAddressSpace::setWidth (int width) override virtual
Aborts the program with error message.
Exceptions
OutOfRange Never thrown.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 132 of file NullAddressSpace.cc.
{
    abortWithError("setWidth()");
}
References abortWithError.
start()
ULongWord TTAMachine::NullAddressSpace::start () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 85 of file NullAddressSpace.cc.
{
    abortWithError("start()");
    return 0;
}
References abortWithError.
unsetMachine()
void TTAMachine::NullAddressSpace::unsetMachine () virtual
Aborts the program with error message.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 160 of file NullAddressSpace.cc.
{
    abortWithError("unsetMachine()");
}
References abortWithError.
width()
int TTAMachine::NullAddressSpace::width () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::AddressSpace.
Definition at line 73 of file NullAddressSpace.cc.
{
    abortWithError("width()");
    return 0;
}
References abortWithError.
Member Data Documentation
instance_
NullAddressSpace TTAMachine::NullAddressSpace::instance_ static private
The only instance of NullAddressSpace.
Definition at line 72 of file NullAddressSpace.hh.
Referenced by instance().
machine_
Machine TTAMachine::NullAddressSpace::machine_ static private
Machine to which the null address space is registered.
Definition at line 74 of file NullAddressSpace.hh.
The documentation for this class was generated from the following files:
NullAddressSpace.hh
NullAddressSpace.cc