OpenASIP: BEMSerializer Class Reference
BEMSerializer Class Reference
#include <BEMSerializer.hh>
Public Member Functions
BEMSerializer ()
virtual ~BEMSerializer ()
virtual ObjectState * readState ()
virtual void writeState (const ObjectState *state)
BinaryEncoding * readBinaryEncoding ()
void writeBinaryEncoding (const BinaryEncoding &bem)
Public Member Functions inherited from XMLSerializer
XMLSerializer ()
virtual ~XMLSerializer ()
void setSourceFile (const std::string &fileName)
void setSourceString (const std::string &source)
void setDestinationFile (const std::string &fileName)
void setDestinationString (std::string &destination)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
void setXMLNamespace (std::string nsUri)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Static Private Member Functions
static ObjectState * convertToOMFormat (const ObjectState *fileState)
static ObjectState * convertToFileFormat (const ObjectState *omState)
static void convertZeroEncExtraBits (ObjectState *os)
static ObjectState * socketCodeTableToFile (const ObjectState *scTable)
static ObjectState * longImmTagToFile (const ObjectState *immTag)
static ObjectState * moveSlotToFile (const ObjectState *slotState)
static ObjectState * guardFieldToFile (const ObjectState *gFieldState)
static ObjectState * sourceFieldToFile (const ObjectState *sFieldState)
static ObjectState * destinationFieldToFile (const ObjectState *dFieldState)
static ObjectState * slotFieldToFile (const ObjectState *sFieldState)
static ObjectState * immediateSlotToFile (const ObjectState *slotState)
static ObjectState * longImmDstRegisterFieldToFile (const ObjectState *omState)
static ObjectState * socketCodeTableToOM (const ObjectState *scTable)
static ObjectState * longImmTagToOM (const ObjectState *fileTag)
static ObjectState * moveSlotToOM (const ObjectState *fileSlot)
static ObjectState * guardFieldToOM (const ObjectState *fileGuard)
static ObjectState * sourceFieldToOM (const ObjectState *fileSource)
static ObjectState * destinationFieldToOM (const ObjectState *fileDestination)
static ObjectState * slotFieldToOM (const ObjectState *fileSlot)
static ObjectState * immediateSlotToOM (const ObjectState *fileSlot)
static ObjectState * longImmDstRegFieldToOM (const ObjectState *fileField)
static void readRegisterFilePortCode (const ObjectState *filePortCode, ObjectState *omPortCode)
Additional Inherited Members
Protected Member Functions inherited from XMLSerializer
std::string sourceFile () const
Detailed Description
BEMSerializer reads and writes BEM (Binary Encoding Map) files.
Definition at line 43 of file BEMSerializer.hh.
Constructor & Destructor Documentation
BEMSerializer()
BEMSerializer::BEMSerializer ()
The constructor.
Definition at line 164 of file BEMSerializer.cc.
                             : XMLSerializer() {
    setSchemaFile(Environment::schemaDirPath(BEM_SCHEMA_FILE));
    setUseSchema(true);
}
References BEM_SCHEMA_FILE, Environment::schemaDirPath(), XMLSerializer::setSchemaFile(), and XMLSerializer::setUseSchema().
~BEMSerializer()
BEMSerializer::~BEMSerializer () virtual
The destructor.
Definition at line 173 of file BEMSerializer.cc.
{
}
Member Function Documentation
convertToFileFormat()
ObjectState * BEMSerializer::convertToFileFormat (const ObjectState * state) static private
Converts the ObjectState tree that represent the BEM object model to an ObjectState tree that represents the BEM file format.
Parameters
omState ObjectState tree that represents BEM object model (returned by BinaryEncoding::saveState()).
Returns
ObjectState tree representing BEM file.
Definition at line 327 of file BEMSerializer.cc.
{
    ObjectState* fileState = new ObjectState(ADF_ENCODING);
    const string version = "1.5";
    const string requiredVersion = "1.5";
    fileState->setAttribute(BEM_VERSION_STR, version);
    fileState->setAttribute(REQUIRED_VERSION, requiredVersion);
    // create socket code tables
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == SocketCodeTable::OSNAME_SOCKET_CODE_TABLE) {
            fileState->addChild(socketCodeTableToFile(child));
        }
    }
    // create long immediate tag
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() ==
            ImmediateControlField::OSNAME_IMM_CONTROL_FIELD) {
            fileState->addChild(longImmTagToFile(child));
        }
    }
    // create long immediate destination register fields
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() ==
            LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD) {
            fileState->addChild(longImmDstRegisterFieldToFile(child));
        }
    }
    // create move slots
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == MoveSlot::OSNAME_MOVE_SLOT) {
            fileState->addChild(moveSlotToFile(child));
        }
    }
    // create immediate slots
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() ==
            ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD) {
            fileState->addChild(immediateSlotToFile(child));
        }
    }
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == InstructionFormat::OSNAME_INSTRUCTION_FORMAT) {
            ObjectState* newChild = new ObjectState(*child);
            fileState->addChild(newChild);
        }
    }
    // template extra bits: copy OS tree
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS) {
            fileState->addChild(new ObjectState(*child));
        }
    }
    return fileState;
}
References ObjectState::addChild(), ADF_ENCODING, BEM_VERSION_STR, ObjectState::child(), ObjectState::childCount(), immediateSlotToFile(), longImmDstRegisterFieldToFile(), longImmTagToFile(), moveSlotToFile(), ObjectState::name(), ImmediateControlField::OSNAME_IMM_CONTROL_FIELD, ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD, InstructionFormat::OSNAME_INSTRUCTION_FORMAT, LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD, MoveSlot::OSNAME_MOVE_SLOT, SocketCodeTable::OSNAME_SOCKET_CODE_TABLE, BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS, REQUIRED_VERSION, ObjectState::setAttribute(), and socketCodeTableToFile().
Referenced by writeState().
convertToOMFormat()
ObjectState * BEMSerializer::convertToOMFormat (const ObjectState * fileState) static private
Converts the given ObjectState tree that represents a BEM file to an ObjectState tree that can be loaded by BinaryEncoding.
Parameters
fileState ObjectState tree that represents a BEM file.
Returns
A newly created ObjectState tree that can be loaded by BinaryEncoding.
Definition at line 287 of file BEMSerializer.cc.
{
    ObjectState* bem = new ObjectState(BinaryEncoding::OSNAME_BEM);
    for (int i = 0; i < fileState->childCount(); i++) {
        ObjectState* child = fileState->child(i);
        if (child->name() == SOCKET_CODE_TABLE) {
            bem->addChild(socketCodeTableToOM(child));
        } else if (child->name() == SLOT) {
            bem->addChild(moveSlotToOM(child));
        } else if (child->name() == IMMEDIATE_SLOT) {
            bem->addChild(immediateSlotToOM(child));
        } else if (child->name() == LONG_IMMEDIATE_TAG) {
            bem->addChild(longImmTagToOM(child));
        } else if (child->name() == IMM_REG_FIELD) {
            bem->addChild(longImmDstRegFieldToOM(child));
        } else if (child->name() == INSTRUCTION_FORMAT) {
            ObjectState* newChild = new ObjectState(*child);
            bem->addChild(newChild);
        } else if (
            child->name() == BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS) {
            bem->addChild(new ObjectState(*child));
        } else {
            assert(false);
        }
    }
    return bem;
}
References ObjectState::addChild(), assert, ObjectState::child(), ObjectState::childCount(), IMM_REG_FIELD, IMMEDIATE_SLOT, immediateSlotToOM(), INSTRUCTION_FORMAT, LONG_IMMEDIATE_TAG, longImmDstRegFieldToOM(), longImmTagToOM(), moveSlotToOM(), ObjectState::name(), BinaryEncoding::OSNAME_BEM, BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS, SLOT, SOCKET_CODE_TABLE, and socketCodeTableToOM().
Referenced by readState().
convertZeroEncExtraBits()
void BEMSerializer::convertZeroEncExtraBits (ObjectState * os) static private
Recursively convert all encodings with zero encodings to have one more extra bit.
Definition at line 214 of file BEMSerializer.cc.
{
    if (os->name() == MAP) {
        if (os->intValue() == 0 && os->hasAttribute(EXTRA_BITS)) {
            int extraBits = os->intAttribute(EXTRA_BITS);
            os->setAttribute(EXTRA_BITS, extraBits + 1);
        }
    }
    if (os->name() == FU_PORT_CODE &&
        os->hasChild(EXTRA_BITS) &&
        os->hasChild(FU_PORT_CODE_ENCODING)) {
        if (os->childByName(FU_PORT_CODE_ENCODING)->intValue() == 0) {
            ObjectState* eb = os->childByName(EXTRA_BITS);
            eb ->setValue(eb->intValue()+1);
        }
    }
    // call recursively for children
    for (int i = 0; i < os->childCount(); i++) {
        ObjectState* child = os->child(i);
        convertZeroEncExtraBits(child);
    }
}
References ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), convertZeroEncExtraBits(), EXTRA_BITS, FU_PORT_CODE, FU_PORT_CODE_ENCODING, ObjectState::hasAttribute(), ObjectState::hasChild(), ObjectState::intAttribute(), ObjectState::intValue(), MAP, ObjectState::name(), ObjectState::setAttribute(), and ObjectState::setValue().
Referenced by convertZeroEncExtraBits(), and readState().
destinationFieldToFile()
ObjectState * BEMSerializer::destinationFieldToFile (const ObjectState * dFieldState) static private
Converts the given ObjectState tree that represents a destination field in object model to BEM file format.
Parameters
dFieldState The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 784 of file BEMSerializer.cc.
{
    ObjectState* destination = slotFieldToFile(dFieldState);
    destination->setName(SLOT_DESTINATION);
    return destination;
}
References ObjectState::setName(), SLOT_DESTINATION, and slotFieldToFile().
Referenced by moveSlotToFile().
destinationFieldToOM()
ObjectState * BEMSerializer::destinationFieldToOM (const ObjectState * fileDestination) static private
Converts the given ObjectState tree that represents a destination element in BEM file to an ObjectState tree that can be loaded by DestinationField.
Parameters
fileDestination An ObjectState tree that represents a destination element in a BEM file.
Returns
The newly created ObjectState tree.
Definition at line 1222 of file BEMSerializer.cc.
{
    ObjectState* destinationField = slotFieldToOM(fileDestination);
    destinationField->setName(DestinationField::OSNAME_DESTINATION_FIELD);
    return destinationField;
}
References DestinationField::OSNAME_DESTINATION_FIELD, ObjectState::setName(), and slotFieldToOM().
Referenced by moveSlotToOM().
guardFieldToFile()
ObjectState * BEMSerializer::guardFieldToFile (const ObjectState * gFieldState) static private
Converts the given ObjectState tree that represents a guard field in object model to BEM file format.
Parameters
gFieldState The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 608 of file BEMSerializer.cc.
{
    ObjectState* guard = new ObjectState(SLOT_GUARD);
    ObjectState* position = new ObjectState(SLOT_GUARD_POSITION);
    guard->addChild(position);
    position->setValue(
        gFieldState->stringAttribute(GuardField::OSKEY_POSITION));
    ObjectState* extraBits = new ObjectState(SLOT_GUARD_EXTRA_BITS);
    guard->addChild(extraBits);
    extraBits->setValue(
        gFieldState->stringAttribute(GuardField::OSKEY_EXTRA_BITS));
    // add register guard encodings
    for (int i = 0; i < gFieldState->childCount(); i++) {
        ObjectState* child = gFieldState->child(i);
        if (child->name() == GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING) {
            ObjectState* regGuard = new ObjectState(REG_GUARD_CODE);
            guard->addChild(regGuard);
            regGuard->setAttribute(
                REG_GUARD_CODE_RF,
                child->stringAttribute(GPRGuardEncoding::OSKEY_RF_NAME));
            regGuard->setAttribute(
                REG_GUARD_CODE_INDEX,
                child->stringAttribute(
                    GPRGuardEncoding::OSKEY_REGISTER_INDEX));
            string inverted = child->boolAttribute(
                GPRGuardEncoding::OSKEY_INVERTED) ? TRUE : FALSE;
            regGuard->setAttribute(REG_GUARD_CODE_INVERTED, inverted);
            regGuard->setValue(
                child->stringAttribute(GPRGuardEncoding::OSKEY_ENCODING));
        }
    }
    // add port guard encodings
    for (int i = 0; i < gFieldState->childCount(); i++) {
        ObjectState* child = gFieldState->child(i);
        if (child->name() == FUGuardEncoding::OSNAME_FU_GUARD_ENCODING) {
            ObjectState* fuGuard = new ObjectState(PORT_GUARD_CODE);
            guard->addChild(fuGuard);
            fuGuard->setAttribute(
                PORT_GUARD_CODE_FU,
                child->stringAttribute(FUGuardEncoding::OSKEY_FU_NAME));
            fuGuard->setAttribute(
                PORT_GUARD_CODE_PORT,
                child->stringAttribute(FUGuardEncoding::OSKEY_PORT_NAME));
            string inverted = child->boolAttribute(
                FUGuardEncoding::OSKEY_INVERTED) ? TRUE : FALSE;
            fuGuard->setAttribute(PORT_GUARD_CODE_INVERTED, inverted);
            fuGuard->setValue(
                child->stringAttribute(FUGuardEncoding::OSKEY_ENCODING));
        }
    }
    // add unconditional always-true-guard encoding
    for (int i = 0; i < gFieldState->childCount(); i++) {
        ObjectState* child = gFieldState->child(i);
        if (child->name() ==
            UnconditionalGuardEncoding::
            OSNAME_UNCONDITIONAL_GUARD_ENCODING &&
            !child->boolAttribute(
                UnconditionalGuardEncoding::OSKEY_INVERTED)) {
            ObjectState* ucGuard = new ObjectState(ALWAYS_TRUE_GUARD_CODE);
            guard->addChild(ucGuard);
            ucGuard->setValue(
                child->stringAttribute(
                    UnconditionalGuardEncoding::OSKEY_ENCODING));
        }
    }
    // add always-false-guard encoding
    for (int i = 0; i < gFieldState->childCount(); i++) {
        ObjectState* child = gFieldState->child(i);
        if (child->name() ==
            UnconditionalGuardEncoding::OSNAME_UNCONDITIONAL_GUARD_ENCODING
            && child->boolAttribute(
                UnconditionalGuardEncoding::OSKEY_INVERTED)) {
            ObjectState* ucGuard = new ObjectState(ALWAYS_FALSE_GUARD_CODE);
            guard->addChild(ucGuard);
            ucGuard->setValue(
                child->stringAttribute(
                    UnconditionalGuardEncoding::OSKEY_ENCODING));
        }
    }
    return guard;
}
References ObjectState::addChild(), ALWAYS_FALSE_GUARD_CODE, ALWAYS_TRUE_GUARD_CODE, ObjectState::boolAttribute(), ObjectState::child(), ObjectState::childCount(), FALSE, ObjectState::name(), GuardEncoding::OSKEY_ENCODING, InstructionField::OSKEY_EXTRA_BITS, FUGuardEncoding::OSKEY_FU_NAME, GuardEncoding::OSKEY_INVERTED, FUGuardEncoding::OSKEY_PORT_NAME, InstructionField::OSKEY_POSITION, GPRGuardEncoding::OSKEY_REGISTER_INDEX, GPRGuardEncoding::OSKEY_RF_NAME, FUGuardEncoding::OSNAME_FU_GUARD_ENCODING, GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING, UnconditionalGuardEncoding::OSNAME_UNCONDITIONAL_GUARD_ENCODING, PORT_GUARD_CODE, PORT_GUARD_CODE_FU, PORT_GUARD_CODE_INVERTED, PORT_GUARD_CODE_PORT, REG_GUARD_CODE, REG_GUARD_CODE_INDEX, REG_GUARD_CODE_INVERTED, REG_GUARD_CODE_RF, ObjectState::setAttribute(), ObjectState::setValue(), SLOT_GUARD, SLOT_GUARD_EXTRA_BITS, SLOT_GUARD_POSITION, ObjectState::stringAttribute(), and TRUE.
Referenced by moveSlotToFile().
guardFieldToOM()
ObjectState * BEMSerializer::guardFieldToOM (const ObjectState * fileGuard) static private
Converts the given ObjectState tree that represents a guard element of BEM file to a new ObjectState tree that can be loaded by GuardField.
Parameters
fileGuard An ObjectState tree that represents a guard element of BEM file.
Returns
The newly created ObjectState tree.
Definition at line 1076 of file BEMSerializer.cc.
{
    ObjectState* guardField = new ObjectState(
        GuardField::OSNAME_GUARD_FIELD);
    ObjectState* pos = fileGuard->childByName(SLOT_GUARD_POSITION);
    guardField->setAttribute(GuardField::OSKEY_POSITION, pos->stringValue());
    ObjectState* extraBits = fileGuard->childByName(SLOT_GUARD_EXTRA_BITS);
    guardField->setAttribute(
        GuardField::OSKEY_EXTRA_BITS, extraBits->stringValue());
    // add guard encodings
    for (int i = 0; i < fileGuard->childCount(); i++) {
        ObjectState* child = fileGuard->child(i);
        if (child->name() == REG_GUARD_CODE) {
            ObjectState* guardCode = new ObjectState(
                GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING);
            guardField->addChild(guardCode);
            string regFile = child->stringAttribute(REG_GUARD_CODE_RF);
            guardCode->setAttribute(
                GPRGuardEncoding::OSKEY_RF_NAME, regFile);
            int regIndex = child->intAttribute(REG_GUARD_CODE_INDEX);
            guardCode->setAttribute(
                GPRGuardEncoding::OSKEY_REGISTER_INDEX, regIndex);
            string inverted = child->stringAttribute(
                REG_GUARD_CODE_INVERTED);
            if (inverted == TRUE) {
                guardCode->setAttribute(
                    GPRGuardEncoding::OSKEY_INVERTED, true);
            } else if (inverted == FALSE) {
                guardCode->setAttribute(
                    GPRGuardEncoding::OSKEY_INVERTED, false);
            } else {
                assert(false);
            }
            guardCode->setAttribute(
                GPRGuardEncoding::OSKEY_ENCODING, child->stringValue());
        } else if (child->name() == PORT_GUARD_CODE) {
            ObjectState* guardCode = new ObjectState(
                FUGuardEncoding::OSNAME_FU_GUARD_ENCODING);
            guardField->addChild(guardCode);
            string fu = child->stringAttribute(PORT_GUARD_CODE_FU);
            guardCode->setAttribute(FUGuardEncoding::OSKEY_FU_NAME, fu);
            string port = child->stringAttribute(PORT_GUARD_CODE_PORT);
            guardCode->setAttribute(FUGuardEncoding::OSKEY_PORT_NAME, port);
            string inverted = child->stringAttribute(
                PORT_GUARD_CODE_INVERTED);
            if (inverted == TRUE) {
                guardCode->setAttribute(
                    FUGuardEncoding::OSKEY_INVERTED, true);
            } else if (inverted == FALSE) {
                guardCode->setAttribute(
                    FUGuardEncoding::OSKEY_INVERTED, false);
            } else {
                assert(false);
            }
            guardCode->setAttribute(
                FUGuardEncoding::OSKEY_ENCODING, child->stringValue());
        } else if (child->name() == ALWAYS_TRUE_GUARD_CODE ||
                   child->name() == ALWAYS_FALSE_GUARD_CODE) {
            ObjectState* guardCode = new ObjectState(
                UnconditionalGuardEncoding::
                OSNAME_UNCONDITIONAL_GUARD_ENCODING);
            guardField->addChild(guardCode);
            guardCode->setAttribute(
                UnconditionalGuardEncoding::OSKEY_ENCODING,
                child->stringValue());
            if (child->name() == ALWAYS_TRUE_GUARD_CODE) {
                guardCode->setAttribute(
                    UnconditionalGuardEncoding::OSKEY_INVERTED, false);
            } else {
                guardCode->setAttribute(
                    UnconditionalGuardEncoding::OSKEY_INVERTED, true);
            }
        }
    }
    return guardField;
}
References ObjectState::addChild(), ALWAYS_FALSE_GUARD_CODE, ALWAYS_TRUE_GUARD_CODE, assert, ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), FALSE, ObjectState::intAttribute(), ObjectState::name(), GuardEncoding::OSKEY_ENCODING, InstructionField::OSKEY_EXTRA_BITS, FUGuardEncoding::OSKEY_FU_NAME, GuardEncoding::OSKEY_INVERTED, FUGuardEncoding::OSKEY_PORT_NAME, InstructionField::OSKEY_POSITION, GPRGuardEncoding::OSKEY_REGISTER_INDEX, GPRGuardEncoding::OSKEY_RF_NAME, FUGuardEncoding::OSNAME_FU_GUARD_ENCODING, GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING, GuardField::OSNAME_GUARD_FIELD, PORT_GUARD_CODE, PORT_GUARD_CODE_FU, PORT_GUARD_CODE_INVERTED, PORT_GUARD_CODE_PORT, REG_GUARD_CODE, REG_GUARD_CODE_INDEX, REG_GUARD_CODE_INVERTED, REG_GUARD_CODE_RF, ObjectState::setAttribute(), SLOT_GUARD_EXTRA_BITS, SLOT_GUARD_POSITION, ObjectState::stringAttribute(), ObjectState::stringValue(), and TRUE.
Referenced by moveSlotToOM().
immediateSlotToFile()
ObjectState * BEMSerializer::immediateSlotToFile (const ObjectState * slotState) static private
Converts the given ObjectState instance that represents an ImmediateSlotField instance to BEM file format.
Parameters
slotState The ObjectState instance that represents an ImmediateSlotField instance.
Returns
The newly created ObjectState tree.
Definition at line 870 of file BEMSerializer.cc.
{
    ObjectState* immSlot = new ObjectState(IMMEDIATE_SLOT);
    immSlot->setAttribute(
        IMMEDIATE_SLOT_NAME,
        slotState->stringAttribute(ImmediateSlotField::OSKEY_NAME));
    ObjectState* pos = new ObjectState(IMMEDIATE_SLOT_POS);
    immSlot->addChild(pos);
    pos->setValue(
        slotState->stringAttribute(ImmediateSlotField::OSKEY_POSITION));
    ObjectState* width = new ObjectState(IMMEDIATE_SLOT_WIDTH);
    immSlot->addChild(width);
    width->setValue(
        slotState->stringAttribute(ImmediateSlotField::OSKEY_WIDTH));
    return immSlot;
}
References ObjectState::addChild(), IMMEDIATE_SLOT, IMMEDIATE_SLOT_NAME, IMMEDIATE_SLOT_POS, IMMEDIATE_SLOT_WIDTH, ImmediateSlotField::OSKEY_NAME, InstructionField::OSKEY_POSITION, ImmediateSlotField::OSKEY_WIDTH, ObjectState::setAttribute(), ObjectState::setValue(), and ObjectState::stringAttribute().
Referenced by convertToFileFormat().
immediateSlotToOM()
ObjectState * BEMSerializer::immediateSlotToOM (const ObjectState * fileSlot) static private
Converts the given ObjectState tree that represents immediate-slot element of BEM file to an ObjectState instance that can be loaded by ImmediateSlotField instance.
Parameters
fileSlot ObjectState tree that represents immediate-slot element of BEM file.
Returns
The newly created ObjectState instance.
Definition at line 1312 of file BEMSerializer.cc.
{
    ObjectState* immSlotField = new ObjectState(
        ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD);
    string name = fileSlot->stringAttribute(IMMEDIATE_SLOT_NAME);
    immSlotField->setAttribute(ImmediateSlotField::OSKEY_NAME, name);
    string width = fileSlot->childByName(IMMEDIATE_SLOT_WIDTH)->
        stringValue();
    immSlotField->setAttribute(ImmediateSlotField::OSKEY_WIDTH, width);
    string pos = fileSlot->childByName(IMMEDIATE_SLOT_POS)->stringValue();
    immSlotField->setAttribute(ImmediateSlotField::OSKEY_POSITION, pos);
    immSlotField->setAttribute(ImmediateSlotField::OSKEY_EXTRA_BITS, 0);
    return immSlotField;
}
References ObjectState::childByName(), IMMEDIATE_SLOT_NAME, IMMEDIATE_SLOT_POS, IMMEDIATE_SLOT_WIDTH, InstructionField::OSKEY_EXTRA_BITS, ImmediateSlotField::OSKEY_NAME, InstructionField::OSKEY_POSITION, ImmediateSlotField::OSKEY_WIDTH, ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD, ObjectState::setAttribute(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by convertToOMFormat().
longImmDstRegFieldToOM()
ObjectState * BEMSerializer::longImmDstRegFieldToOM (const ObjectState * fileField) static private
Converts the given ObjectState tree that represents a long immediate destination register field in BEM file to an ObjectState tree that can be loaded by LImmDstRegisterField instance.
Parameters
fileField The ObjectState tree that represents long immediate destination register field in BEM file.
Returns
The newly created ObjectState tree.
Definition at line 1337 of file BEMSerializer.cc.
{
    ObjectState* omState = new ObjectState(
        LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD);
    omState->setAttribute(LImmDstRegisterField::OSKEY_EXTRA_BITS, 0);
    omState->setAttribute(
        LImmDstRegisterField::OSKEY_POSITION,
        fileField->childByName(IMM_REG_FIELD_POS)->stringValue());
    omState->setAttribute(
        LImmDstRegisterField::OSKEY_WIDTH,
        fileField->childByName(IMM_REG_FIELD_WIDTH)->stringValue());
    for (int i = 0; i < fileField->childCount(); i++) {
        ObjectState* child = fileField->child(i);
        if (child->name() == IMM_REG_FIELD_ITEMP) {
            ObjectState* iuDst = new ObjectState(
                LImmDstRegisterField::OSNAME_IU_DESTINATION);
            omState->addChild(iuDst);
            iuDst->setAttribute(
                LImmDstRegisterField::OSKEY_ITEMP,
                child->stringAttribute(IMM_REG_FIELD_ITEMP_NAME));
            iuDst->setAttribute(
                LImmDstRegisterField::OSKEY_DST_IU,
                child->child(0)->stringValue());
        }
    }
    return omState;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), IMM_REG_FIELD_ITEMP, IMM_REG_FIELD_ITEMP_NAME, IMM_REG_FIELD_POS, IMM_REG_FIELD_WIDTH, ObjectState::name(), LImmDstRegisterField::OSKEY_DST_IU, InstructionField::OSKEY_EXTRA_BITS, LImmDstRegisterField::OSKEY_ITEMP, InstructionField::OSKEY_POSITION, LImmDstRegisterField::OSKEY_WIDTH, LImmDstRegisterField::OSNAME_IU_DESTINATION, LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD, ObjectState::setAttribute(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by convertToOMFormat().
longImmDstRegisterFieldToFile()
ObjectState * BEMSerializer::longImmDstRegisterFieldToFile (const ObjectState * omState) static private
Converts the given ObjectState tree that represent a long immediate destination register field in BEM object model to BEM file format.
Parameters
omState The ObjectState tree.
Returns
The newly create ObjectState tree.
Definition at line 895 of file BEMSerializer.cc.
{
    ObjectState* fileState = new ObjectState(IMM_REG_FIELD);
    ObjectState* posElem = new ObjectState(IMM_REG_FIELD_POS);
    fileState->addChild(posElem);
    posElem->setValue(
        omState->stringAttribute(LImmDstRegisterField::OSKEY_POSITION));
    ObjectState* widthElem = new ObjectState(IMM_REG_FIELD_WIDTH);
    fileState->addChild(widthElem);
    widthElem->setValue(
        omState->stringAttribute(LImmDstRegisterField::OSKEY_WIDTH));
    for (int i = 0; i < omState->childCount(); i++) {
        ObjectState* child = omState->child(i);
        assert(child->name() == LImmDstRegisterField::OSNAME_IU_DESTINATION);
        ObjectState* iTempElem = new ObjectState(IMM_REG_FIELD_ITEMP);
        fileState->addChild(iTempElem);
        iTempElem->setAttribute(
            IMM_REG_FIELD_ITEMP_NAME,
            child->stringAttribute(LImmDstRegisterField::OSKEY_ITEMP));
        ObjectState* regIndexElem = new ObjectState(
            IMM_REG_FIELD_ITEMP_REG_INDEX);
        iTempElem->addChild(regIndexElem);
        regIndexElem->setValue(
            child->stringAttribute(LImmDstRegisterField::OSKEY_DST_IU));
    }
    return fileState;
}
References ObjectState::addChild(), assert, ObjectState::child(), ObjectState::childCount(), IMM_REG_FIELD, IMM_REG_FIELD_ITEMP, IMM_REG_FIELD_ITEMP_NAME, IMM_REG_FIELD_ITEMP_REG_INDEX, IMM_REG_FIELD_POS, IMM_REG_FIELD_WIDTH, ObjectState::name(), LImmDstRegisterField::OSKEY_DST_IU, LImmDstRegisterField::OSKEY_ITEMP, InstructionField::OSKEY_POSITION, LImmDstRegisterField::OSKEY_WIDTH, LImmDstRegisterField::OSNAME_IU_DESTINATION, ObjectState::setAttribute(), ObjectState::setValue(), and ObjectState::stringAttribute().
Referenced by convertToFileFormat().
longImmTagToFile()
ObjectState * BEMSerializer::longImmTagToFile (const ObjectState * immTag) static private
Converts the given ObjectState tree that represents immediate control field in object model format to BEM file file format.
Parameters
immTag The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 524 of file BEMSerializer.cc.
{
    ObjectState* fileTag = new ObjectState(LONG_IMMEDIATE_TAG);
    ObjectState* position = new ObjectState(LIMM_TAG_POSITION);
    fileTag->addChild(position);
    position->setValue(
        immTag->stringAttribute(ImmediateControlField::OSKEY_POSITION));
    ObjectState* extraBits = new ObjectState(LIMM_TAG_EXTRA_BITS);
    fileTag->addChild(extraBits);
    extraBits->setValue(
        immTag->stringAttribute(ImmediateControlField::OSKEY_EXTRA_BITS));
    // create map elements
    for (int i = 0; i < immTag->childCount(); i++) {
        ObjectState* child = immTag->child(i);
        assert(child->name() == ImmediateControlField::OSNAME_TEMPLATE_MAP);
        ObjectState* map = new ObjectState(LIMM_TAG_MAP);
        fileTag->addChild(map);
        map->setAttribute(
            LIMM_TAG_MAP_NAME,
            child->stringAttribute(
                ImmediateControlField::OSKEY_TEMPLATE_NAME));
        map->setValue(
            child->stringAttribute(ImmediateControlField::OSKEY_ENCODING));
    }
    return fileTag;
}
References ObjectState::addChild(), assert, ObjectState::child(), ObjectState::childCount(), LIMM_TAG_EXTRA_BITS, LIMM_TAG_MAP, LIMM_TAG_MAP_NAME, LIMM_TAG_POSITION, LONG_IMMEDIATE_TAG, ObjectState::name(), ImmediateControlField::OSKEY_ENCODING, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, ImmediateControlField::OSKEY_TEMPLATE_NAME, ImmediateControlField::OSNAME_TEMPLATE_MAP, ObjectState::setAttribute(), ObjectState::setValue(), and ObjectState::stringAttribute().
Referenced by convertToFileFormat().
longImmTagToOM()
ObjectState * BEMSerializer::longImmTagToOM (const ObjectState * immTag) static private
Converts the given ObjectState tree that represents a long-immediate-tag element of BEM file to ObjectState tree that can be loaded by ImmediateControlField.
Parameters
fileTag An ObjectState tree that represents a long-immediate-tag element.
Returns
The newly created ObjectState tree.
Definition at line 995 of file BEMSerializer.cc.
{
    ObjectState* immControlField =
        new ObjectState(ImmediateControlField::OSNAME_IMM_CONTROL_FIELD);
    ObjectState* pos = immTag->childByName(LIMM_TAG_POSITION);
    immControlField->setAttribute(
        ImmediateControlField::OSKEY_POSITION, pos->stringValue());
    ObjectState* extraBits = immTag->childByName(LIMM_TAG_EXTRA_BITS);
    immControlField->setAttribute(
        ImmediateControlField::OSKEY_EXTRA_BITS, extraBits->stringValue());
    // add template mappings
    for (int i = 0; i < immTag->childCount(); i++) {
        ObjectState* child = immTag->child(i);
        if (child->name() == LIMM_TAG_MAP) {
            ObjectState* mapping = new ObjectState(
                ImmediateControlField::OSNAME_TEMPLATE_MAP);
            immControlField->addChild(mapping);
            mapping->setAttribute(
                ImmediateControlField::OSKEY_TEMPLATE_NAME,
                child->stringAttribute(LIMM_TAG_MAP_NAME));
            mapping->setAttribute(
                ImmediateControlField::OSKEY_ENCODING, child->stringValue());
        }
    }
    return immControlField;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), LIMM_TAG_EXTRA_BITS, LIMM_TAG_MAP, LIMM_TAG_MAP_NAME, LIMM_TAG_POSITION, ObjectState::name(), ImmediateControlField::OSKEY_ENCODING, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, ImmediateControlField::OSKEY_TEMPLATE_NAME, ImmediateControlField::OSNAME_IMM_CONTROL_FIELD, ImmediateControlField::OSNAME_TEMPLATE_MAP, ObjectState::setAttribute(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by convertToOMFormat().
moveSlotToFile()
ObjectState * BEMSerializer::moveSlotToFile (const ObjectState * slotState) static private
Converts the given ObjectState tree that represents a move slot in object model format to BEM file format.
Parameters
slotState The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 562 of file BEMSerializer.cc.
{
    ObjectState* slot = new ObjectState(SLOT);
    slot->setAttribute(
        SLOT_NAME, slotState->stringAttribute(MoveSlot::OSKEY_BUS_NAME));
    ObjectState* position = new ObjectState(SLOT_POSITION);
    slot->addChild(position);
    position->setValue(slotState->stringAttribute(MoveSlot::OSKEY_POSITION));
    ObjectState* extraBits = new ObjectState(SLOT_EXTRA_BITS);
    slot->addChild(extraBits);
    extraBits->setValue(
        slotState->stringAttribute(MoveSlot::OSKEY_EXTRA_BITS));
    // add guard field
    if (slotState->hasChild(GuardField::OSNAME_GUARD_FIELD)) {
        ObjectState* guardField = slotState->childByName(
            GuardField::OSNAME_GUARD_FIELD);
        slot->addChild(guardFieldToFile(guardField));
    }
    // add source field
    if (slotState->hasChild(SourceField::OSNAME_SOURCE_FIELD)) {
        ObjectState* sourceField = slotState->childByName(
            SourceField::OSNAME_SOURCE_FIELD);
        slot->addChild(sourceFieldToFile(sourceField));
    }
    // add destination field
    if (slotState->hasChild(DestinationField::OSNAME_DESTINATION_FIELD)) {
        ObjectState* destinationField = slotState->childByName(
            DestinationField::OSNAME_DESTINATION_FIELD);
        slot->addChild(destinationFieldToFile(destinationField));
    }
    return slot;
}
References ObjectState::addChild(), ObjectState::childByName(), destinationFieldToFile(), guardFieldToFile(), ObjectState::hasChild(), MoveSlot::OSKEY_BUS_NAME, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, DestinationField::OSNAME_DESTINATION_FIELD, GuardField::OSNAME_GUARD_FIELD, SourceField::OSNAME_SOURCE_FIELD, ObjectState::setAttribute(), ObjectState::setValue(), SLOT, SLOT_EXTRA_BITS, SLOT_NAME, SLOT_POSITION, sourceFieldToFile(), and ObjectState::stringAttribute().
Referenced by convertToFileFormat().
moveSlotToOM()
ObjectState * BEMSerializer::moveSlotToOM (const ObjectState * fileSlot) static private
Converts the given ObjectState tree that represents a slot element of BEM file to ObjectState tree that can be loaded by MoveSlot.
Parameters
fileSlot The ObjectState tree that represents a slot element.
Returns
The newly created ObjectState tree.
Definition at line 1032 of file BEMSerializer.cc.
{
    ObjectState* moveSlot = new ObjectState(MoveSlot::OSNAME_MOVE_SLOT);
    string busName = fileSlot->stringAttribute(SLOT_NAME);
    moveSlot->setAttribute(MoveSlot::OSKEY_BUS_NAME, busName);
    ObjectState* pos = fileSlot->childByName(SLOT_POSITION);
    moveSlot->setAttribute(MoveSlot::OSKEY_POSITION, pos->stringValue());
    ObjectState* extraBits = fileSlot->childByName(SLOT_EXTRA_BITS);
    moveSlot->setAttribute(
        MoveSlot::OSKEY_EXTRA_BITS, extraBits->stringValue());
    // add guard field
    if (fileSlot->hasChild(SLOT_GUARD)) {
        ObjectState* guard = fileSlot->childByName(SLOT_GUARD);
        moveSlot->addChild(guardFieldToOM(guard));
    }
    // add source field
    if (fileSlot->hasChild(SLOT_SOURCE)) {
        ObjectState* source = fileSlot->childByName(SLOT_SOURCE);
        moveSlot->addChild(sourceFieldToOM(source));
    }
    // add destination field
    if (fileSlot->hasChild(SLOT_DESTINATION)) {
        ObjectState* destination = fileSlot->childByName(SLOT_DESTINATION);
        moveSlot->addChild(destinationFieldToOM(destination));
    }
    return moveSlot;
}
References ObjectState::addChild(), ObjectState::childByName(), destinationFieldToOM(), guardFieldToOM(), ObjectState::hasChild(), MoveSlot::OSKEY_BUS_NAME, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, MoveSlot::OSNAME_MOVE_SLOT, ObjectState::setAttribute(), SLOT_DESTINATION, SLOT_EXTRA_BITS, SLOT_GUARD, SLOT_NAME, SLOT_POSITION, SLOT_SOURCE, sourceFieldToOM(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by convertToOMFormat().
readBinaryEncoding()
BinaryEncoding * BEMSerializer::readBinaryEncoding ()
Reads the BEM file and creates a BinaryEncoding instance from it.
Returns
The newly created BinaryEncoding instance.
Definition at line 258 of file BEMSerializer.cc.
{
    ObjectState* omState = readState();
    BinaryEncoding* bem = new BinaryEncoding(omState);
    delete omState;
    return bem;
}
References readState().
Referenced by loadBEM(), ProGe::ProGeUI::loadBinaryEncoding(), ProGe::ProGeUI::loadProcessorConfiguration(), main(), and GenerateProcessorDialog::onBrowseBEMLoad().
readRegisterFilePortCode()
void BEMSerializer::readRegisterFilePortCode (const ObjectState * filePortCode, ObjectState * omPortCode) static private
Reads rf-port-code or iu-port-code element from an ObjectState tree that represents BEM file and adds the data to the given ObjectState instance to make it loadable by RFPortCode or IUPortCode.
Parameters
filePortCode ObjectState tree representing rf-port-code or iu-port-code element of BEM file.
omPortCode The ObjectState instance to which the data is added.
Definition at line 1377 of file BEMSerializer.cc.
{
    string unit;
    if (filePortCode->name() == RF_PORT_CODE) {
        unit = filePortCode->stringAttribute(RF_PORT_CODE_RF);
    } else if (filePortCode->name() == IU_PORT_CODE) {
        unit = filePortCode->stringAttribute(IU_PORT_CODE_IU);
    } else {
        assert(false);
    }
    omPortCode->setAttribute(PortCode::OSKEY_UNIT_NAME, unit);
    omPortCode->setAttribute(
        PortCode::OSKEY_INDEX_WIDTH,
        filePortCode->stringAttribute(RF_PORT_CODE_INDEX_WIDTH));
    if (filePortCode->hasChild(RF_PORT_CODE_ENCODING)) {
        ObjectState* encoding = filePortCode->childByName(
            RF_PORT_CODE_ENCODING);
        omPortCode->setAttribute(
            PortCode::OSKEY_ENCODING, encoding->stringValue());
        ObjectState* extraBits = filePortCode->childByName(
                RF_PORT_CODE_EXTRA_BITS);
        omPortCode->setAttribute(
            PortCode::OSKEY_EXTRA_BITS, extraBits->stringValue());
    }
}
References assert, ObjectState::childByName(), ObjectState::hasChild(), IU_PORT_CODE, IU_PORT_CODE_IU, ObjectState::name(), PortCode::OSKEY_ENCODING, PortCode::OSKEY_EXTRA_BITS, PortCode::OSKEY_INDEX_WIDTH, PortCode::OSKEY_UNIT_NAME, RF_PORT_CODE, RF_PORT_CODE_ENCODING, RF_PORT_CODE_EXTRA_BITS, RF_PORT_CODE_INDEX_WIDTH, RF_PORT_CODE_RF, ObjectState::setAttribute(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by socketCodeTableToOM().
readState()
ObjectState * BEMSerializer::readState () virtual
Reads the BEM file and returns an ObjectState tree that can be loaded by BinaryEncoding.
Returns
An ObjectState tree that can be loaded by BinaryEncoding.
Exceptions
SerializerException If an error occurs while reading the BEM file.
Reimplemented from XMLSerializer.
Definition at line 186 of file BEMSerializer.cc.
{
    ObjectState* fileState = XMLSerializer::readState();
    double version = fileState->doubleAttribute(BEM_VERSION_STR);
    if (fileState->hasAttribute(REQUIRED_VERSION)) {
        double requiredVersion = fileState->doubleAttribute(REQUIRED_VERSION);
        if (requiredVersion > 1.5) {
            THROW_EXCEPTION(
                SerializerException,
                "Cannot parse the file. "
                "The file requests parser version of " +
                    fileState->stringAttribute(REQUIRED_VERSION) +
                    ". "
                    "The version of the parser is 1.5.");
        }
    }
    if (version < 1.2) {
        convertZeroEncExtraBits(fileState);
    }
    ObjectState* omState = convertToOMFormat(fileState);
    delete fileState;
    return omState;
}
References BEM_VERSION_STR, convertToOMFormat(), convertZeroEncExtraBits(), ObjectState::doubleAttribute(), ObjectState::hasAttribute(), XMLSerializer::readState(), REQUIRED_VERSION, ObjectState::stringAttribute(), and THROW_EXCEPTION.
Referenced by readBinaryEncoding().
slotFieldToFile()
ObjectState * BEMSerializer::slotFieldToFile (const ObjectState * sFieldState) static private
Converts the given ObjectState tree that represents either source or destination in BEM object model to BEM file format.
Parameters
sFieldState The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 798 of file BEMSerializer.cc.
{
   ObjectState* srcOrDst = new ObjectState(SLOT_SOURCE);
   ObjectState* position = new ObjectState(SRC_DST_POSITION);
   srcOrDst->addChild(position);
   position->setValue(
       sFieldState->stringAttribute(SlotField::OSKEY_POSITION));
   ObjectState* extraBits = new ObjectState(SRC_DST_EXTRA_BITS);
   srcOrDst->addChild(extraBits);
   extraBits->setValue(
       sFieldState->stringAttribute(SlotField::OSKEY_EXTRA_BITS));
   ObjectState* encodingPos = new ObjectState(SRC_DST_ID_POS);
   srcOrDst->addChild(encodingPos);
   if (sFieldState->intAttribute(SlotField::OSKEY_COMPONENT_ID_POSITION) ==
       BinaryEncoding::LEFT) {
       encodingPos->setValue(ID_POS_LEFT);
   } else {
       encodingPos->setValue(ID_POS_RIGHT);
   }
   // add socket elements
   for (int i = 0; i < sFieldState->childCount(); i++) {
       ObjectState* child = sFieldState->child(i);
       if (child->name() == SocketEncoding::OSNAME_SOCKET_ENCODING) {
           ObjectState* socket = new ObjectState(SOCKET);
           srcOrDst->addChild(socket);
           socket->setAttribute(
               SOCKET_NAME,
               child->stringAttribute(SocketEncoding::OSKEY_SOCKET_NAME));
           ObjectState* map = new ObjectState(SOCKET_MAP);
           socket->addChild(map);
           map->setAttribute(
               SOCKET_MAP_EXTRA_BITS,
               child->stringAttribute(SocketEncoding::OSKEY_EXTRA_BITS));
           if (child->hasAttribute(SocketEncoding::OSKEY_SC_TABLE)) {
               map->setAttribute(
                   SOCKET_MAP_CODES,
                   child->stringAttribute(SocketEncoding::OSKEY_SC_TABLE));
           }
           map->setValue(
               child->stringAttribute(SocketEncoding::OSKEY_ENCODING));
       }
   }
   // add move no-operation element
   if (sFieldState->hasChild(NOPEncoding::OSNAME_NOP_ENCODING)) {
       ObjectState* nopEncoding = sFieldState->childByName(
           NOPEncoding::OSNAME_NOP_ENCODING);
       ObjectState* noOperation = new ObjectState(SRC_DST_NO_OPERATION);
       srcOrDst->addChild(noOperation);
       ObjectState* map = new ObjectState(SRC_DST_NO_OPERATION_MAP);
       noOperation->addChild(map);
       map->setAttribute(
           SRC_DST_NO_OPERATION_MAP_EXTRA_BITS,
           nopEncoding->stringAttribute(NOPEncoding::OSKEY_EXTRA_BITS));
       map->setValue(
           nopEncoding->stringAttribute(NOPEncoding::OSKEY_ENCODING));
   }
   return srcOrDst;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::hasAttribute(), ObjectState::hasChild(), ID_POS_LEFT, ID_POS_RIGHT, ObjectState::intAttribute(), BinaryEncoding::LEFT, ObjectState::name(), SlotField::OSKEY_COMPONENT_ID_POSITION, Encoding::OSKEY_ENCODING, Encoding::OSKEY_EXTRA_BITS, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, SocketEncoding::OSKEY_SC_TABLE, SocketEncoding::OSKEY_SOCKET_NAME, NOPEncoding::OSNAME_NOP_ENCODING, SocketEncoding::OSNAME_SOCKET_ENCODING, ObjectState::setAttribute(), ObjectState::setValue(), SLOT_SOURCE, SOCKET, SOCKET_MAP, SOCKET_MAP_CODES, SOCKET_MAP_EXTRA_BITS, SOCKET_NAME, SRC_DST_EXTRA_BITS, SRC_DST_ID_POS, SRC_DST_NO_OPERATION, SRC_DST_NO_OPERATION_MAP, SRC_DST_NO_OPERATION_MAP_EXTRA_BITS, SRC_DST_POSITION, and ObjectState::stringAttribute().
Referenced by destinationFieldToFile(), and sourceFieldToFile().
slotFieldToOM()
ObjectState * BEMSerializer::slotFieldToOM (const ObjectState * fileSlot) static private
Converts the given ObjectState tree that represents either source or destination element of BEM file to an ObjectState tree that can be loaded by SlotField.
Parameters
fileSlot An ObjectState tree representing source or destination field.
Returns
The newly created ObjectState tree.
Definition at line 1239 of file BEMSerializer.cc.
{
    ObjectState* slotField = new ObjectState(SlotField::OSNAME_SLOT_FIELD);
    ObjectState* pos = fileSlot->childByName(SRC_DST_POSITION);
    slotField->setAttribute(
        SlotField::OSKEY_POSITION, pos->stringValue());
    ObjectState* extraBits = fileSlot->childByName(SRC_DST_EXTRA_BITS);
    slotField->setAttribute(
        SlotField::OSKEY_EXTRA_BITS, extraBits->stringValue());
    if (fileSlot->childByName(SRC_DST_ID_POS)->stringValue() ==
        ID_POS_RIGHT) {
        slotField->setAttribute(
            SlotField::OSKEY_COMPONENT_ID_POSITION, BinaryEncoding::RIGHT);
    } else {
        assert(
            fileSlot->childByName(SRC_DST_ID_POS)->stringValue() ==
            ID_POS_LEFT);
        slotField->setAttribute(
            SlotField::OSKEY_COMPONENT_ID_POSITION, BinaryEncoding::LEFT);
    }
    // read socket elements
    for (int i = 0; i < fileSlot->childCount(); i++) {
        ObjectState* child = fileSlot->child(i);
        if (child->name() == SOCKET) {
            ObjectState* socketEncoding = new ObjectState(
                SocketEncoding::OSNAME_SOCKET_ENCODING);
            slotField->addChild(socketEncoding);
            socketEncoding->setAttribute(
                SocketEncoding::OSKEY_SOCKET_NAME,
                child->stringAttribute(SOCKET_NAME));
            ObjectState* map = child->childByName(SOCKET_MAP);
            socketEncoding->setAttribute(
                SocketEncoding::OSKEY_ENCODING, map->stringValue());
            socketEncoding->setAttribute(
                SocketEncoding::OSKEY_EXTRA_BITS,
                map->stringAttribute(SOCKET_MAP_EXTRA_BITS));
            if (map->hasAttribute(SOCKET_MAP_CODES)) {
                socketEncoding->setAttribute(
                    SocketEncoding::OSKEY_SC_TABLE,
                    map->stringAttribute(SOCKET_MAP_CODES));
            }
        }
    }
    // read NOP encoding
    if (fileSlot->hasChild(SRC_DST_NO_OPERATION)) {
        ObjectState* nopEncoding = new ObjectState(
            NOPEncoding::OSNAME_NOP_ENCODING);
        slotField->addChild(nopEncoding);
        ObjectState* map = fileSlot->childByName(SRC_DST_NO_OPERATION)->
            child(0);
        nopEncoding->setAttribute(
            NOPEncoding::OSKEY_ENCODING, map->stringValue());
        nopEncoding->setAttribute(
            NOPEncoding::OSKEY_EXTRA_BITS,
            map->stringAttribute(SRC_DST_NO_OPERATION_MAP_EXTRA_BITS));
    }
    return slotField;
}
References ObjectState::addChild(), assert, ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::hasAttribute(), ObjectState::hasChild(), ID_POS_LEFT, ID_POS_RIGHT, BinaryEncoding::LEFT, ObjectState::name(), SlotField::OSKEY_COMPONENT_ID_POSITION, Encoding::OSKEY_ENCODING, Encoding::OSKEY_EXTRA_BITS, InstructionField::OSKEY_EXTRA_BITS, InstructionField::OSKEY_POSITION, SocketEncoding::OSKEY_SC_TABLE, SocketEncoding::OSKEY_SOCKET_NAME, NOPEncoding::OSNAME_NOP_ENCODING, SlotField::OSNAME_SLOT_FIELD, SocketEncoding::OSNAME_SOCKET_ENCODING, BinaryEncoding::RIGHT, ObjectState::setAttribute(), SOCKET, SOCKET_MAP, SOCKET_MAP_CODES, SOCKET_MAP_EXTRA_BITS, SOCKET_NAME, SRC_DST_EXTRA_BITS, SRC_DST_ID_POS, SRC_DST_NO_OPERATION, SRC_DST_NO_OPERATION_MAP_EXTRA_BITS, SRC_DST_POSITION, ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by destinationFieldToOM(), and sourceFieldToOM().
socketCodeTableToFile()
ObjectState * BEMSerializer::socketCodeTableToFile (const ObjectState * omTable) static private
Converts the given ObjectState tree that represents a socket code table in the object model format to BEM file format.
Returns
The newly created ObjectState tree.
Definition at line 404 of file BEMSerializer.cc.
{
    ObjectState* scTable = new ObjectState(SOCKET_CODE_TABLE);
    scTable->setAttribute(
    SC_TABLE_NAME, omTable->stringAttribute(
            SocketCodeTable::OSKEY_NAME));
    // create extra-bits element
    ObjectState* extraBits = new ObjectState(SC_TABLE_EXTRA_BITS);
    scTable->addChild(extraBits);
    extraBits->setValue(
    omTable->intAttribute(SocketCodeTable::OSKEY_EXTRA_BITS));
    // create fu-port-code elements
    for (int i = 0; i < omTable->childCount(); i++) {
        ObjectState* portCode = omTable->child(i);
        if (portCode->name() == FUPortCode::OSNAME_FU_PORT_CODE) {
            ObjectState* fuPortCode = new ObjectState(FU_PORT_CODE);
            scTable->addChild(fuPortCode);
            fuPortCode->setAttribute(
                FU_PORT_CODE_PORT,
                portCode->stringAttribute(FUPortCode::OSKEY_PORT_NAME));
            fuPortCode->setAttribute(
                FU_PORT_CODE_FU,
                portCode->stringAttribute(FUPortCode::OSKEY_UNIT_NAME));
            if (portCode->hasAttribute(FUPortCode::OSKEY_OPERATION_NAME)) {
                fuPortCode->setAttribute(
                    FU_PORT_CODE_OPERATION,
                    portCode->stringAttribute(
                        FUPortCode::OSKEY_OPERATION_NAME));
            }
            ObjectState* encoding = new ObjectState(FU_PORT_CODE_ENCODING);
            fuPortCode->addChild(encoding);
            encoding->setValue(
                portCode->stringAttribute(FUPortCode::OSKEY_ENCODING));
            ObjectState* extraBits = new ObjectState(FU_PORT_CODE_EXTRA_BITS);
            fuPortCode->addChild(extraBits);
            extraBits->setValue(
                portCode->stringAttribute(FUPortCode::OSKEY_EXTRA_BITS));
        }
    }
    // create rf-port-code elements
    for (int i = 0; i < omTable->childCount(); i++) {
        ObjectState* portCode = omTable->child(i);
        if (portCode->name() == RFPortCode::OSNAME_RF_PORT_CODE) {
            ObjectState* rfPortCode = new ObjectState(RF_PORT_CODE);
            scTable->addChild(rfPortCode);
            rfPortCode->setAttribute(
                RF_PORT_CODE_RF,
                portCode->stringAttribute(RFPortCode::OSKEY_UNIT_NAME));
            rfPortCode->setAttribute(
                RF_PORT_CODE_INDEX_WIDTH,
                portCode->stringAttribute(RFPortCode::OSKEY_INDEX_WIDTH));
            if (portCode->hasAttribute(PortCode::OSKEY_MAX_INDEX))
                rfPortCode->setAttribute(
                    RF_PORT_CODE_MAX_INDEX,
                    portCode->stringAttribute(PortCode::OSKEY_MAX_INDEX));
            if (portCode->hasAttribute(RFPortCode::OSKEY_ENCODING)) {
                ObjectState* encoding = new ObjectState(
                    RF_PORT_CODE_ENCODING);
                rfPortCode->addChild(encoding);
                encoding->setValue(
                    portCode->stringAttribute(RFPortCode::OSKEY_ENCODING));
                ObjectState* extraBits = new ObjectState(
                    RF_PORT_CODE_EXTRA_BITS);
                rfPortCode->addChild(extraBits);
                extraBits->setValue(
                    portCode->stringAttribute(RFPortCode::OSKEY_EXTRA_BITS));
            }
        }
    }
    // create iu-port-code elements
    for (int i = 0; i < omTable->childCount(); i++) {
        ObjectState* portCode = omTable->child(i);
        if (portCode->name() == IUPortCode::OSNAME_IU_PORT_CODE) {
            ObjectState* iuPortCode = new ObjectState(IU_PORT_CODE);
            scTable->addChild(iuPortCode);
            iuPortCode->setAttribute(
                IU_PORT_CODE_IU,
                portCode->stringAttribute(IUPortCode::OSKEY_UNIT_NAME));
            iuPortCode->setAttribute(
                RF_PORT_CODE_INDEX_WIDTH,
                portCode->stringAttribute(IUPortCode::OSKEY_INDEX_WIDTH));
            if (portCode->hasAttribute(PortCode::OSKEY_MAX_INDEX))
                iuPortCode->setAttribute(
                    RF_PORT_CODE_MAX_INDEX,
                    portCode->stringAttribute(PortCode::OSKEY_MAX_INDEX));
            if (portCode->hasAttribute(IUPortCode::OSKEY_ENCODING)) {
                ObjectState* encoding = new ObjectState(
                    RF_PORT_CODE_ENCODING);
                iuPortCode->addChild(encoding);
                encoding->setValue(
                    portCode->stringAttribute(IUPortCode::OSKEY_ENCODING));
                ObjectState* extraBits = new ObjectState(
                    RF_PORT_CODE_EXTRA_BITS);
                iuPortCode->addChild(extraBits);
                extraBits->setValue(
                    portCode->stringAttribute(IUPortCode::OSKEY_EXTRA_BITS));
            }
        }
    }
    return scTable;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childCount(), FU_PORT_CODE, FU_PORT_CODE_ENCODING, FU_PORT_CODE_EXTRA_BITS, FU_PORT_CODE_FU, FU_PORT_CODE_OPERATION, FU_PORT_CODE_PORT, ObjectState::hasAttribute(), ObjectState::intAttribute(), IU_PORT_CODE, IU_PORT_CODE_IU, ObjectState::name(), PortCode::OSKEY_ENCODING, PortCode::OSKEY_EXTRA_BITS, SocketCodeTable::OSKEY_EXTRA_BITS, PortCode::OSKEY_INDEX_WIDTH, PortCode::OSKEY_MAX_INDEX, SocketCodeTable::OSKEY_NAME, FUPortCode::OSKEY_OPERATION_NAME, FUPortCode::OSKEY_PORT_NAME, PortCode::OSKEY_UNIT_NAME, FUPortCode::OSNAME_FU_PORT_CODE, IUPortCode::OSNAME_IU_PORT_CODE, RFPortCode::OSNAME_RF_PORT_CODE, RF_PORT_CODE, RF_PORT_CODE_ENCODING, RF_PORT_CODE_EXTRA_BITS, RF_PORT_CODE_INDEX_WIDTH, RF_PORT_CODE_MAX_INDEX, RF_PORT_CODE_RF, SC_TABLE_EXTRA_BITS, SC_TABLE_NAME, ObjectState::setAttribute(), ObjectState::setValue(), SOCKET_CODE_TABLE, and ObjectState::stringAttribute().
Referenced by convertToFileFormat().
socketCodeTableToOM()
ObjectState * BEMSerializer::socketCodeTableToOM (const ObjectState * scTable) static private
Converts the given ObjectState tree that represents a socket code table in BEM file to an ObjectState tree that can be loaded by SocketCodeTable.
Parameters
scTable The ObjectState tree.
Returns
The newly created ObjectState tree that can be loaded by SocketCodeTable.
Definition at line 934 of file BEMSerializer.cc.
{
    ObjectState* omTable = new ObjectState(
        SocketCodeTable::OSNAME_SOCKET_CODE_TABLE);
    string name = scTable->stringAttribute(SC_TABLE_NAME);
    omTable->setAttribute(SocketCodeTable::OSKEY_NAME, name);
    int extraBits = scTable->childByName(SC_TABLE_EXTRA_BITS)->intValue();
    omTable->setAttribute(
        SocketCodeTable::OSKEY_EXTRA_BITS, extraBits);
    // add port codes
    for (int i = 0; i < scTable->childCount(); i++) {
        ObjectState* child = scTable->child(i);
        if (child->name() == FU_PORT_CODE) {
            ObjectState* fuPortCode = new ObjectState(
                FUPortCode::OSNAME_FU_PORT_CODE);
            omTable->addChild(fuPortCode);
            string portName = child->stringAttribute(FU_PORT_CODE_PORT);
            string fuName = child->stringAttribute(FU_PORT_CODE_FU);
            fuPortCode->setAttribute(FUPortCode::OSKEY_UNIT_NAME, fuName);
            fuPortCode->setAttribute(FUPortCode::OSKEY_PORT_NAME, portName);
            if (child->hasAttribute(FU_PORT_CODE_OPERATION)) {
                string opName = child->stringAttribute(
                    FU_PORT_CODE_OPERATION);
                fuPortCode->setAttribute(
                    FUPortCode::OSKEY_OPERATION_NAME, opName);
            }
            fuPortCode->setAttribute(
                FUPortCode::OSKEY_ENCODING,
                child->childByName(FU_PORT_CODE_ENCODING)->stringValue());
            fuPortCode->setAttribute(
                FUPortCode::OSKEY_EXTRA_BITS,
                child->childByName(FU_PORT_CODE_EXTRA_BITS)->stringValue());
        } else if (child->name() == RF_PORT_CODE) {
            ObjectState* rfPortCode = new ObjectState(
                RFPortCode::OSNAME_RF_PORT_CODE);
            omTable->addChild(rfPortCode);
            readRegisterFilePortCode(child, rfPortCode);
        } else if (child->name() == IU_PORT_CODE) {
            ObjectState* iuPortCode = new ObjectState(
                IUPortCode::OSNAME_IU_PORT_CODE);
            omTable->addChild(iuPortCode);
            readRegisterFilePortCode(child, iuPortCode);
        }
    }
    return omTable;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), FU_PORT_CODE, FU_PORT_CODE_ENCODING, FU_PORT_CODE_EXTRA_BITS, FU_PORT_CODE_FU, FU_PORT_CODE_OPERATION, FU_PORT_CODE_PORT, ObjectState::hasAttribute(), ObjectState::intValue(), IU_PORT_CODE, ObjectState::name(), PortCode::OSKEY_ENCODING, PortCode::OSKEY_EXTRA_BITS, SocketCodeTable::OSKEY_EXTRA_BITS, SocketCodeTable::OSKEY_NAME, FUPortCode::OSKEY_OPERATION_NAME, FUPortCode::OSKEY_PORT_NAME, PortCode::OSKEY_UNIT_NAME, FUPortCode::OSNAME_FU_PORT_CODE, IUPortCode::OSNAME_IU_PORT_CODE, RFPortCode::OSNAME_RF_PORT_CODE, SocketCodeTable::OSNAME_SOCKET_CODE_TABLE, readRegisterFilePortCode(), RF_PORT_CODE, SC_TABLE_EXTRA_BITS, SC_TABLE_NAME, ObjectState::setAttribute(), ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by convertToOMFormat().
sourceFieldToFile()
ObjectState * BEMSerializer::sourceFieldToFile (const ObjectState * sFieldState) static private
Converts the given ObjectState tree that represents a source field in object model to BEM file format.
Parameters
sFieldState The ObjectState tree.
Returns
The newly created ObjectState tree.
Definition at line 704 of file BEMSerializer.cc.
{
    ObjectState* source = slotFieldToFile(sFieldState);
    source->setName(SLOT_SOURCE);
    // add immediate element in front of socket elements, it has to be done
    // by removing the socket elements
    if (sFieldState->hasChild(ImmediateEncoding::OSNAME_IMM_ENCODING)) {
        std::vector<ObjectState*> socketElems;
        for (int i = 0; i < source->childCount();) {
            ObjectState* child = source->child(i);
            if (child->name() == SOCKET) {
                socketElems.push_back(child);
                source->removeChild(child);
            } else {
                i++;
            }
        }
        ObjectState* immediate = new ObjectState(SOURCE_IMMEDIATE);
        source->addChild(immediate);
        ObjectState* encodingState = sFieldState->childByName(
            ImmediateEncoding::OSNAME_IMM_ENCODING);
        immediate->setAttribute(
            SOURCE_IMMEDIATE_WIDTH,
            encodingState->stringAttribute(
                ImmediateEncoding::OSKEY_IMM_WIDTH));
        ObjectState* map = new ObjectState(SOURCE_IMMEDIATE_MAP);
        immediate->addChild(map);
        map->setAttribute(SOURCE_IMMEDIATE_MAP_EXTRA_BITS,
                          encodingState->stringAttribute(
                              ImmediateEncoding::OSKEY_EXTRA_BITS));
        map->setValue(
            encodingState->stringAttribute(
                ImmediateEncoding::OSKEY_ENCODING));
        // add the socket elements
        for (vector<ObjectState*>::const_iterator iter = socketElems.begin();
             iter != socketElems.end(); iter++) {
            source->addChild(*iter);
        }
    }
    // add bridge elements
    for (int i = 0; i < sFieldState->childCount(); i++) {
        ObjectState* child = sFieldState->child(i);
        if (child->name() == BridgeEncoding::OSNAME_BRIDGE_ENCODING) {
            ObjectState* bridge = new ObjectState(SOURCE_BRIDGE);
            source->addChild(bridge);
            bridge->setAttribute(
                SOURCE_BRIDGE_NAME,
                child->stringAttribute(BridgeEncoding::OSKEY_BRIDGE_NAME));
            ObjectState* map = new ObjectState(SOURCE_BRIDGE_MAP);
            bridge->addChild(map);
            map->setAttribute(
                SOURCE_BRIDGE_MAP_EXTRA_BITS,
                child->stringAttribute(BridgeEncoding::OSKEY_EXTRA_BITS));
            map->setValue(
                child->stringAttribute(BridgeEncoding::OSKEY_ENCODING));
        }
    }
    // move the no-operation element to the end
    if (source->hasChild(SRC_DST_NO_OPERATION)) {
        ObjectState* nop = source->childByName(SRC_DST_NO_OPERATION);
        source->removeChild(nop);
        source->addChild(nop);
    }
    return source;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::hasChild(), ObjectState::name(), BridgeEncoding::OSKEY_BRIDGE_NAME, Encoding::OSKEY_ENCODING, Encoding::OSKEY_EXTRA_BITS, ImmediateEncoding::OSKEY_IMM_WIDTH, BridgeEncoding::OSNAME_BRIDGE_ENCODING, ImmediateEncoding::OSNAME_IMM_ENCODING, ObjectState::removeChild(), ObjectState::setAttribute(), ObjectState::setName(), ObjectState::setValue(), SLOT_SOURCE, slotFieldToFile(), SOCKET, SOURCE_BRIDGE, SOURCE_BRIDGE_MAP, SOURCE_BRIDGE_MAP_EXTRA_BITS, SOURCE_BRIDGE_NAME, SOURCE_IMMEDIATE, SOURCE_IMMEDIATE_MAP, SOURCE_IMMEDIATE_MAP_EXTRA_BITS, SOURCE_IMMEDIATE_WIDTH, SRC_DST_NO_OPERATION, and ObjectState::stringAttribute().
Referenced by moveSlotToFile().
sourceFieldToOM()
ObjectState * BEMSerializer::sourceFieldToOM (const ObjectState * fileSource) static private
Converts the given ObjectState tree that represents a source element in BEM file to an ObjectState tree that can be loaded by SourceField.
Parameters
fileSource An ObjectState tree that represents a source element in a BEM file.
Returns
The newly created ObjectState tree.
Definition at line 1167 of file BEMSerializer.cc.
{
    ObjectState* sourceField = slotFieldToOM(fileSource);
    sourceField->setName(SourceField::OSNAME_SOURCE_FIELD);
    // add immediate encoding
    if (fileSource->hasChild(SOURCE_IMMEDIATE)) {
        ObjectState* immEncoding = new ObjectState(
            ImmediateEncoding::OSNAME_IMM_ENCODING);
        sourceField->addChild(immEncoding);
        immEncoding->setAttribute(
            ImmediateEncoding::OSKEY_IMM_WIDTH,
            fileSource->childByName(SOURCE_IMMEDIATE)->stringAttribute(
                SOURCE_IMMEDIATE_WIDTH));
        ObjectState* map = fileSource->childByName(SOURCE_IMMEDIATE)->
            child(0);
        immEncoding->setAttribute(
            ImmediateEncoding::OSKEY_ENCODING, map->stringValue());
        immEncoding->setAttribute(
            ImmediateEncoding::OSKEY_EXTRA_BITS,
            map->stringAttribute(SOURCE_IMMEDIATE_MAP_EXTRA_BITS));
    }
    // add bridge encodings
    for (int i = 0; i < fileSource->childCount(); i++) {
        ObjectState* child = fileSource->child(i);
        if (child->name() == SOURCE_BRIDGE) {
            ObjectState* bridgeEncoding = new ObjectState(
                BridgeEncoding::OSNAME_BRIDGE_ENCODING);
            sourceField->addChild(bridgeEncoding);
            bridgeEncoding->setAttribute(
                BridgeEncoding::OSKEY_BRIDGE_NAME,
                child->stringAttribute(SOURCE_BRIDGE_NAME));
            ObjectState* map = child->childByName(SOURCE_BRIDGE_MAP);
            bridgeEncoding->setAttribute(
                BridgeEncoding::OSKEY_EXTRA_BITS,
                map->stringAttribute(SOURCE_BRIDGE_MAP_EXTRA_BITS));
            bridgeEncoding->setAttribute(
                BridgeEncoding::OSKEY_ENCODING, map->stringValue());
        }
    }
    return sourceField;
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::hasChild(), ObjectState::name(), BridgeEncoding::OSKEY_BRIDGE_NAME, Encoding::OSKEY_ENCODING, Encoding::OSKEY_EXTRA_BITS, ImmediateEncoding::OSKEY_IMM_WIDTH, BridgeEncoding::OSNAME_BRIDGE_ENCODING, ImmediateEncoding::OSNAME_IMM_ENCODING, SourceField::OSNAME_SOURCE_FIELD, ObjectState::setAttribute(), ObjectState::setName(), slotFieldToOM(), SOURCE_BRIDGE, SOURCE_BRIDGE_MAP, SOURCE_BRIDGE_MAP_EXTRA_BITS, SOURCE_BRIDGE_NAME, SOURCE_IMMEDIATE, SOURCE_IMMEDIATE_MAP_EXTRA_BITS, SOURCE_IMMEDIATE_WIDTH, ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by moveSlotToOM().
writeBinaryEncoding()
void BEMSerializer::writeBinaryEncoding (const BinaryEncoding & bem)
Writes the given binary encoding to a BEM file.
Parameters
bem The binary encoding.
Exceptions
SerializerException If the destination file cannot be written.
Definition at line 272 of file BEMSerializer.cc.
{
    ObjectState* omState = bem.saveState();
    writeState(omState);
    delete omState;
}
References BinaryEncoding::saveState(), and writeState().
Referenced by main(), and GenerateProcessorDialog::onOK().
writeState()
void BEMSerializer::writeState (const ObjectState * state) virtual
Writes the given ObjectState tree that represents a BEM object model to a BEM file.
Parameters
state ObjectState tree obtained by calling BinaryEncoding::saveState().
Exceptions
SerializerException If the destination file cannot be written.
Reimplemented from XMLSerializer.
Definition at line 246 of file BEMSerializer.cc.
{
    ObjectState* fileState = convertToFileFormat(state);
    XMLSerializer::writeState(fileState);
    delete fileState;
}
References convertToFileFormat(), and XMLSerializer::writeState().
Referenced by writeBinaryEncoding().
The documentation for this class was generated from the following files:
BEMSerializer.hh
BEMSerializer.cc