OpenASIP: SimulatorSettingsDialog Class Reference
SimulatorSettingsDialog Class Reference
#include <SimulatorSettingsDialog.hh>
Public Member Functions
SimulatorSettingsDialog (wxWindow *parent, wxWindowID id, SimulatorFrontend &simulator, ProximLineReader &lineReader)
virtual ~SimulatorSettingsDialog ()
Private Types
enum {
ID_EXEC_TRACE = 10000 , ID_BUS_TRACE , ID_PT_TRACKING , ID_RF_TRACKING ,
ID_FU_CONFLICT_DETECTION , ID_LABEL_HISTORY_SIZE , ID_PROFILE_DATA_SAVING , ID_UTILIZATION_DATA_SAVING ,
ID_NEXT_INSTRUCTION_PRINTING , ID_SIMULATION_TIME_STATISTICS , ID_HISTORY_SIZE , ID_SAVE_HISTORY ,
ID_HISTORY_FILE , ID_LINE
}
Widget IDs.
Private Member Functions
virtual bool TransferDataToWindow ()
wxSizer * createContents (wxWindow *parent, bool set_sizer, bool call_fit)
void onOK (wxCommandEvent &event)
Private Attributes
SimulatorFrontend & simulator_
Frontend of the simulator to configure.
ProximLineReader & lineReader_
Line reader to configure.
bool execTrace_
Execution trace enabled/disabled.
bool busTrace_
Bus trace enabled/disabled.
bool ptTrace_
Procedure transfer tracing enabled/disabled.
bool rfTrace_
Register file access tracing enabled/disabled.
bool fuConflictDetection_
FU conflict detection enabled/disabled.
bool profileDataSaving_
Profile data saving enabled/disabled.
bool utilizationDataSaving_
Utilization data saving enabled/disabled.
bool nextInstructionPrinting_
Next instruction printing enabled/disabled.
bool simulationTimeStatistics_
Profile data saving enabled/disabled.
bool historySave_
Input history log file enabled/disabled.
int historySize_
History log max size.
wxString historyFile_
History log file name.
Detailed Description
Dialog for modifying simulator settings.
Definition at line 44 of file SimulatorSettingsDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_EXEC_TRACE
ID_BUS_TRACE
ID_PT_TRACKING
ID_RF_TRACKING
ID_FU_CONFLICT_DETECTION
ID_LABEL_HISTORY_SIZE
ID_PROFILE_DATA_SAVING
ID_UTILIZATION_DATA_SAVING
ID_NEXT_INSTRUCTION_PRINTING
ID_SIMULATION_TIME_STATISTICS
ID_HISTORY_SIZE
ID_SAVE_HISTORY
ID_HISTORY_FILE
ID_LINE
Definition at line 59 of file SimulatorSettingsDialog.hh.
         {
        ID_EXEC_TRACE = 10000,
        ID_BUS_TRACE,
        ID_PT_TRACKING,
        ID_RF_TRACKING,
        ID_FU_CONFLICT_DETECTION,
        ID_LABEL_HISTORY_SIZE,
        ID_PROFILE_DATA_SAVING,
        ID_UTILIZATION_DATA_SAVING,
        ID_NEXT_INSTRUCTION_PRINTING,
        ID_SIMULATION_TIME_STATISTICS,
        ID_HISTORY_SIZE,
        ID_SAVE_HISTORY,
        ID_HISTORY_FILE,
        ID_LINE
    };
Constructor & Destructor Documentation
SimulatorSettingsDialog()
SimulatorSettingsDialog::SimulatorSettingsDialog (wxWindow * parent, wxWindowID id, SimulatorFrontend & simulator, ProximLineReader & lineReader)
The Constructor.
Parameters
parent Parent window of the dialog.
id Dialog window identifier.
simulator Simulator frontend to configure.
Definition at line 54 of file SimulatorSettingsDialog.cc.
                                  :
  wxDialog(parent, id, _T("Simulator Settings"), wxDefaultPosition),
    simulator_(simulator), lineReader_(lineReader) {
    createContents(this, true, true);
    FindWindow(ID_EXEC_TRACE)->SetValidator(wxGenericValidator(&execTrace_));
    FindWindow(ID_BUS_TRACE)->SetValidator(wxGenericValidator(&busTrace_));
    FindWindow(ID_PT_TRACKING)->SetValidator(wxGenericValidator(&ptTrace_));
    FindWindow(ID_RF_TRACKING)->SetValidator(wxGenericValidator(&rfTrace_));
    FindWindow(ID_FU_CONFLICT_DETECTION)->SetValidator(
        wxGenericValidator(&fuConflictDetection_));
    FindWindow(ID_PROFILE_DATA_SAVING)->SetValidator(
        wxGenericValidator(&profileDataSaving_));
    FindWindow(ID_UTILIZATION_DATA_SAVING)->SetValidator(
        wxGenericValidator(&utilizationDataSaving_));
    FindWindow(ID_NEXT_INSTRUCTION_PRINTING)->SetValidator(
        wxGenericValidator(&nextInstructionPrinting_));
    FindWindow(ID_SIMULATION_TIME_STATISTICS)->SetValidator(
        wxGenericValidator(&simulationTimeStatistics_));
    FindWindow(ID_SAVE_HISTORY)->SetValidator(
        wxGenericValidator(&historySave_));
    FindWindow(ID_HISTORY_FILE)->SetValidator(
        wxGenericValidator(&historyFile_));
    FindWindow(ID_HISTORY_SIZE)->SetValidator(
        wxGenericValidator(&historySize_));
}
~SimulatorSettingsDialog()
SimulatorSettingsDialog::~SimulatorSettingsDialog () virtual
The Destructor.
Definition at line 91 of file SimulatorSettingsDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * SimulatorSettingsDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Source code generated by wxDesigner. Do not modify by hand!
Parameters
parent Parent dialog of the widgets.
call_fit If true, resize the dialog to fit the widgets.
set_sizer If true, set the created widgets as the dialog contents.
Returns
Top level sizer of the dialog contents.
Definition at line 237 of file SimulatorSettingsDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxStaticBox *item2 = new wxStaticBox( parent, -1, wxT("Tracing:") );
    wxStaticBoxSizer *item1 = new wxStaticBoxSizer( item2, wxVERTICAL );
    wxCheckBox *item3 = new wxCheckBox( parent, ID_EXEC_TRACE, wxT("Write basic execution trace."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALL, 5 );
    wxCheckBox *item4 = new wxCheckBox( parent, ID_BUS_TRACE, wxT("Write bus trace."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALL, 5 );
    wxCheckBox *item19 = new wxCheckBox( parent, ID_PT_TRACKING, wxT("Procedure transfer tracking."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item19, 0, wxALL, 5 );
    wxCheckBox *item5 = new wxCheckBox( parent, ID_RF_TRACKING, wxT("Concurrent register file access tracking."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item5, 0, wxALL, 5 );
    wxCheckBox *item6 = new wxCheckBox( parent, ID_FU_CONFLICT_DETECTION, wxT("Function unit resouce conflict detection."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALL, 5 );
    wxCheckBox *profiledata = new wxCheckBox( parent, ID_PROFILE_DATA_SAVING, wxT("Profile data saving."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( profiledata, 0, wxALL, 5 );
    wxCheckBox *utildata = new wxCheckBox( parent, ID_UTILIZATION_DATA_SAVING, wxT("Utilization data saving."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( utildata, 0, wxALL, 5 );
    wxCheckBox *nextinstr = new wxCheckBox( parent, ID_NEXT_INSTRUCTION_PRINTING, wxT("Next instruction printing."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( nextinstr, 0, wxALL, 5 );
    wxCheckBox *timestat = new wxCheckBox( parent, ID_SIMULATION_TIME_STATISTICS, wxT("Simulation time statistics."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( timestat, 0, wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item8 = new wxStaticBox( parent, -1, wxT("Command history:") );
    wxStaticBoxSizer *item7 = new wxStaticBoxSizer( item8, wxVERTICAL );
    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item10 = new wxStaticText( parent, ID_LABEL_HISTORY_SIZE, wxT("Maximum size of command history:"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item11 = new wxSpinCtrl( parent, ID_HISTORY_SIZE, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item7->Add( item9, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item12 = new wxBoxSizer( wxVERTICAL );
    wxCheckBox *item13 = new wxCheckBox( parent, ID_SAVE_HISTORY, wxT("Save command history to file:"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALL, 5 );
    wxTextCtrl *item14 = new wxTextCtrl( parent, ID_HISTORY_FILE, wxT(""), wxDefaultPosition, wxSize(300,-1), 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    item7->Add( item12, 0, wxGROW|wxALL, 5 );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item15 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item15, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item17 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALL, 5 );
    wxButton *item18 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item16, 0, 0, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BUS_TRACE, ID_EXEC_TRACE, ID_FU_CONFLICT_DETECTION, ID_HISTORY_FILE, ID_HISTORY_SIZE, ID_LABEL_HISTORY_SIZE, ID_LINE, ID_NEXT_INSTRUCTION_PRINTING, ID_PROFILE_DATA_SAVING, ID_PT_TRACKING, ID_RF_TRACKING, ID_SAVE_HISTORY, ID_SIMULATION_TIME_STATISTICS, and ID_UTILIZATION_DATA_SAVING.
onOK()
void SimulatorSettingsDialog::onOK (wxCommandEvent & event) private
Updates the simulator settings and closes the dialog when the OK-button is pressed.
Definition at line 127 of file SimulatorSettingsDialog.cc.
{
    TransferDataFromWindow();
    std::string command;
    std::string historyFile =
        WxConversion::toString(historyFile_.Trim(false).Trim(true));
    if (simulator_.executionTracing() != execTrace_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_EXEC_TRACE + " ";
        command += Conversion::toString(execTrace_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.busTracing() != busTrace_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_BUS_TRACE + " ";
        command += Conversion::toString(busTrace_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.procedureTransferTracing() != ptTrace_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_PROCEDURE_TRANSFER_TRACE + " ";
        command += Conversion::toString(ptTrace_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.rfAccessTracing() != rfTrace_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_RF_TRACE + " ";
        command += Conversion::toString(rfTrace_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.fuResourceConflictDetection() != fuConflictDetection_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_FU_CONFLICT_DETECTION + " ";
        command += Conversion::toString(fuConflictDetection_);
        command += ProximConstants::SCL_DELIM;
    }
    if (lineReader_.saveInputHistoryToFile() != historySave_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_HISTORY_SAVE + " ";
        command += Conversion::toString(historySave_);
        command += ProximConstants::SCL_DELIM;
    }
    if (lineReader_.inputHistoryMaxLength() != (size_t)historySize_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_HISTORY_SIZE + " ";
        command += Conversion::toString(historySize_);
        command += ProximConstants::SCL_DELIM;
    }
    if (lineReader_.inputHistoryFilename() != historyFile) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_HISTORY_FILE + " ";
        command += historyFile;
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.profileDataSaving() != profileDataSaving_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_PROFILE_DATA_SAVING + " ";
        command += Conversion::toString(profileDataSaving_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.utilizationDataSaving() != utilizationDataSaving_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_UTILIZATION_DATA_SAVING + " ";
        command += Conversion::toString(utilizationDataSaving_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.nextInstructionPrinting() != nextInstructionPrinting_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_NEXT_INSTRUCTION_PRINTING + " ";
        command += Conversion::toString(nextInstructionPrinting_);
        command += ProximConstants::SCL_DELIM;
    }
    if (simulator_.simulationTimeStatistics() != simulationTimeStatistics_) {
        command += ProximConstants::SCL_SET + " ";
        command += ProximConstants::SCL_SETTING_SIMULATION_TIME_STATISTICS + " ";
        command += Conversion::toString(simulationTimeStatistics_);
        command += ProximConstants::SCL_DELIM;
    }
    lineReader_.input(command);
    EndModal(wxID_OK);
}
References busTrace_, SimulatorFrontend::busTracing(), execTrace_, SimulatorFrontend::executionTracing(), fuConflictDetection_, SimulatorFrontend::fuResourceConflictDetection(), historyFile_, historySave_, historySize_, ProximLineReader::input(), ProximLineReader::inputHistoryFilename(), LineReader::inputHistoryMaxLength(), lineReader_, SimulatorFrontend::nextInstructionPrinting(), nextInstructionPrinting_, SimulatorFrontend::procedureTransferTracing(), SimulatorFrontend::profileDataSaving(), profileDataSaving_, ptTrace_, SimulatorFrontend::rfAccessTracing(), rfTrace_, LineReader::saveInputHistoryToFile(), ProximConstants::SCL_DELIM, ProximConstants::SCL_SET, ProximConstants::SCL_SETTING_BUS_TRACE, ProximConstants::SCL_SETTING_EXEC_TRACE, ProximConstants::SCL_SETTING_FU_CONFLICT_DETECTION, ProximConstants::SCL_SETTING_HISTORY_FILE, ProximConstants::SCL_SETTING_HISTORY_SAVE, ProximConstants::SCL_SETTING_HISTORY_SIZE, ProximConstants::SCL_SETTING_NEXT_INSTRUCTION_PRINTING, ProximConstants::SCL_SETTING_PROCEDURE_TRANSFER_TRACE, ProximConstants::SCL_SETTING_PROFILE_DATA_SAVING, ProximConstants::SCL_SETTING_RF_TRACE, ProximConstants::SCL_SETTING_SIMULATION_TIME_STATISTICS, ProximConstants::SCL_SETTING_UTILIZATION_DATA_SAVING, SimulatorFrontend::simulationTimeStatistics(), simulationTimeStatistics_, simulator_, Conversion::toString(), WxConversion::toString(), SimulatorFrontend::utilizationDataSaving(), and utilizationDataSaving_.
TransferDataToWindow()
bool SimulatorSettingsDialog::TransferDataToWindow () private virtual
Transfers settings data from the simulator frontend to the dialog widgets.
Definition at line 99 of file SimulatorSettingsDialog.cc.
{
    execTrace_ = simulator_.executionTracing();
    busTrace_ = simulator_.busTracing();
    ptTrace_ = simulator_.procedureTransferTracing();
    rfTrace_ = simulator_.rfAccessTracing();
    profileDataSaving_ = simulator_.profileDataSaving();
    utilizationDataSaving_ = simulator_.utilizationDataSaving();
    nextInstructionPrinting_ = simulator_.nextInstructionPrinting();
    simulationTimeStatistics_ = simulator_.simulationTimeStatistics();
    fuConflictDetection_ = simulator_.fuResourceConflictDetection();
    historySave_ = lineReader_.saveInputHistoryToFile();
    historySize_ = lineReader_.inputHistoryMaxLength();
    historyFile_ = WxConversion::toWxString(
        lineReader_.inputHistoryFilename());
    return wxDialog::TransferDataToWindow();
}
References busTrace_, SimulatorFrontend::busTracing(), execTrace_, SimulatorFrontend::executionTracing(), fuConflictDetection_, SimulatorFrontend::fuResourceConflictDetection(), historyFile_, historySave_, historySize_, ProximLineReader::inputHistoryFilename(), LineReader::inputHistoryMaxLength(), lineReader_, SimulatorFrontend::nextInstructionPrinting(), nextInstructionPrinting_, SimulatorFrontend::procedureTransferTracing(), SimulatorFrontend::profileDataSaving(), profileDataSaving_, ptTrace_, SimulatorFrontend::rfAccessTracing(), rfTrace_, LineReader::saveInputHistoryToFile(), SimulatorFrontend::simulationTimeStatistics(), simulationTimeStatistics_, simulator_, WxConversion::toWxString(), SimulatorFrontend::utilizationDataSaving(), and utilizationDataSaving_.
Member Data Documentation
busTrace_
bool SimulatorSettingsDialog::busTrace_ private
Bus trace enabled/disabled.
Definition at line 84 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
execTrace_
bool SimulatorSettingsDialog::execTrace_ private
Execution trace enabled/disabled.
Definition at line 82 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
fuConflictDetection_
bool SimulatorSettingsDialog::fuConflictDetection_ private
FU conflict detection enabled/disabled.
Definition at line 90 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
historyFile_
wxString SimulatorSettingsDialog::historyFile_ private
History log file name.
Definition at line 106 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
historySave_
bool SimulatorSettingsDialog::historySave_ private
Input history log file enabled/disabled.
Definition at line 102 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
historySize_
int SimulatorSettingsDialog::historySize_ private
History log max size.
Definition at line 104 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
lineReader_
ProximLineReader& SimulatorSettingsDialog::lineReader_ private
Line reader to configure.
Definition at line 79 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
nextInstructionPrinting_
bool SimulatorSettingsDialog::nextInstructionPrinting_ private
Next instruction printing enabled/disabled.
Definition at line 97 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
profileDataSaving_
bool SimulatorSettingsDialog::profileDataSaving_ private
Profile data saving enabled/disabled.
Definition at line 93 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
ptTrace_
bool SimulatorSettingsDialog::ptTrace_ private
Procedure transfer tracing enabled/disabled.
Definition at line 86 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
rfTrace_
bool SimulatorSettingsDialog::rfTrace_ private
Register file access tracing enabled/disabled.
Definition at line 88 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
simulationTimeStatistics_
bool SimulatorSettingsDialog::simulationTimeStatistics_ private
Profile data saving enabled/disabled.
Definition at line 99 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
simulator_
SimulatorFrontend& SimulatorSettingsDialog::simulator_ private
Frontend of the simulator to configure.
Definition at line 77 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
utilizationDataSaving_
bool SimulatorSettingsDialog::utilizationDataSaving_ private
Utilization data saving enabled/disabled.
Definition at line 95 of file SimulatorSettingsDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
SimulatorSettingsDialog.hh
SimulatorSettingsDialog.cc