OpenASIP: DisassembleCommand Class Reference
DisassembleCommand Class Reference
#include <DisassembleCommand.hh>
Public Member Functions
DisassembleCommand ()
virtual ~DisassembleCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "disassemble" command of the Simulator Control Language.
Definition at line 48 of file DisassembleCommand.hh.
Constructor & Destructor Documentation
DisassembleCommand()
DisassembleCommand::DisassembleCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 58 of file DisassembleCommand.cc.
                                       :
    SimControlLanguageCommand("disassemble") {
}
~DisassembleCommand()
DisassembleCommand::~DisassembleCommand () virtual
Destructor.
Does nothing.
Definition at line 67 of file DisassembleCommand.cc.
{
}
Member Function Documentation
execute()
bool DisassembleCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "disassemble" command.
Prints a range of meory addresses as machine instructions. When two arguments addr1, addr2 are given, addr1 specifies the first address of the range to display, and addr2 specifies the last address (not displayed). If only one argument, addr1, is given, then the function that contains addr1 is disassembled. If no argument is given, the default memory range is the function surrounding the program counter of the selected frame.
Parameters
arguments The range of instruction memory to disassemble.
Returns
Always true if arguments are valid.
Implements CustomCommand.
Definition at line 84 of file DisassembleCommand.cc.
{
    assert(interpreter() != NULL);
    if (!checkArgumentCount(arguments.size() - 1, 0, 2)) {
        return false;
    }
    if (!checkProgramLoaded()) {
        return false;
    }
    SimulatorInterpreterContext& interpreterContext =
        dynamic_cast<SimulatorInterpreterContext&>(interpreter()->context());
    SimulatorFrontend& simFront = interpreterContext.simulatorFrontend();
    int firstAddress = -1;
    int lastAddress = -1;
    const int programLastAddress =
        simFront.program().lastProcedure().endAddress().location() - 1;
    if (arguments.size() > 1) {
        try {
            firstAddress = parseInstructionAddressExpression(
                arguments[1].stringValue());
            if (arguments.size() == 3) {
                lastAddress = parseInstructionAddressExpression(
                    arguments[2].stringValue());
            }
        } catch (const IllegalParameters&) {
            return false;
        }
    }
    if (firstAddress > programLastAddress) {
        firstAddress = programLastAddress;
    }
    for (auto addr : { firstAddress, lastAddress }) {
        try {
            if (addr != -1)
                simFront.program().instructionAt(addr);
        } catch (KeyNotFound& e) {
            interpreter()->setError("No instruction at address "
                + std::to_string(addr) + ".");
            return false;
        }
    }
    if (firstAddress == -1 && lastAddress == -1) {
        firstAddress = simFront.currentProcedure().startAddress().location();
        lastAddress =
            simFront.currentProcedure().lastInstruction().address().location();
    } else if (firstAddress != -1 && lastAddress == -1) {
        const Procedure& procedureAtAddress =
            dynamic_cast<const Procedure&>(
                simFront.program().instructionAt(firstAddress).parent());
        firstAddress = procedureAtAddress.startAddress().location();
        lastAddress =
            procedureAtAddress.lastInstruction().address().location();
    }
    if (lastAddress < 0) {
        lastAddress = 0;
    }
    if (lastAddress > programLastAddress) {
        lastAddress = programLastAddress;
    }
    if (lastAddress < firstAddress) {
        lastAddress = firstAddress;
    }
    try {
        for (; firstAddress <= lastAddress; firstAddress +=
            simFront.program().instructionAt(firstAddress).size()) {
            outputStream() << simFront.disassembleInstruction(firstAddress)
                           << std::endl;
        }
    } catch (KeyNotFound& e) {
        interpreter()->setError("No instruction at address "
            + std::to_string(firstAddress) + ".");
        return false;
    }
    return true;
}
References TTAProgram::Instruction::address(), assert, CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkProgramLoaded(), ScriptInterpreter::context(), SimulatorFrontend::currentProcedure(), SimulatorFrontend::disassembleInstruction(), TTAProgram::CodeSnippet::endAddress(), TTAProgram::Program::instructionAt(), CustomCommand::interpreter(), TTAProgram::CodeSnippet::lastInstruction(), TTAProgram::Program::lastProcedure(), TTAProgram::Address::location(), SimControlLanguageCommand::outputStream(), TTAProgram::Instruction::parent(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimulatorFrontend::program(), ScriptInterpreter::setError(), SimulatorInterpreterContext::simulatorFrontend(), TTAProgram::Instruction::size(), and TTAProgram::CodeSnippet::startAddress().
helpText()
std::string DisassembleCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 185 of file DisassembleCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_DISASSEMBLE).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_DISASSEMBLE.
The documentation for this class was generated from the following files:
DisassembleCommand.hh
DisassembleCommand.cc