OpenASIP: FixedRegisters Class Reference
FixedRegisters Class Reference
#include <FixedRegisters.hh>
Public Member Functions
FixedRegisters ()
virtual ~FixedRegisters ()
SimValue & stackPointer () const
SimValue & integerArgumentRegister (int index) const
SimValue & floatArgumentRegister (int index) const
SimValue & integerReturnValue () const
SimValue & floatReturnValue () const
void setStackPointer (SimValue &value)
void addIntegerArgumentRegister (SimValue &value)
void addFloatArgumentRegister (SimValue &value)
void setIntegerReturnValue (SimValue &value)
void setFloatReturnValue (SimValue &value)
Private Member Functions
FixedRegisters (const FixedRegisters &)
Copying not allowed.
FixedRegisters & operator= (const FixedRegisters)
Assignment not allowed.
Private Attributes
SimValue * stackPointer_
Stack pointer.
std::vector< SimValue * > integerArgs_
Integer argument registers.
std::vector< SimValue * > floatArgs_
Floating point argument registers.
SimValue * intReturnValue_
Integer return value.
SimValue * floatReturnValue_
Floating point return value.
Detailed Description
Contains all the registers that are assigned to special purpose.
Definition at line 44 of file FixedRegisters.hh.
Constructor & Destructor Documentation
FixedRegisters() [1/2]
FixedRegisters::FixedRegisters ()
Constructor.
Definition at line 39 of file FixedRegisters.cc.
                               :
    stackPointer_(NULL), intReturnValue_(NULL), floatReturnValue_(NULL) {
}
~FixedRegisters()
FixedRegisters::~FixedRegisters () virtual
Destructor.
Definition at line 46 of file FixedRegisters.cc.
{
}
FixedRegisters() [2/2]
FixedRegisters::FixedRegisters (const FixedRegisters &) private
Copying not allowed.
Member Function Documentation
addFloatArgumentRegister()
void FixedRegisters::addFloatArgumentRegister (SimValue & value)
Adds new float argument register.
Parameters
value New float argument register value.
Definition at line 144 of file FixedRegisters.cc.
{
    floatArgs_.push_back(&value);
}
References floatArgs_.
addIntegerArgumentRegister()
void FixedRegisters::addIntegerArgumentRegister (SimValue & value)
Adds new integer argument register.
Parameters
value New integer argument register value.
Definition at line 134 of file FixedRegisters.cc.
{
    integerArgs_.push_back(&value);
}
References integerArgs_.
floatArgumentRegister()
SimValue & FixedRegisters::floatArgumentRegister (int index) const
Returns float argument register with a given index.
If index is out of range, returns NullSimValue.
Returns
Float argument register with a given index.
Definition at line 85 of file FixedRegisters.cc.
{
    if (index < 0 || index > static_cast<int>(floatArgs_.size()) - 1) {
        return NullSimValue::instance();
    }
    return *floatArgs_[index];
}
References floatArgs_, and NullSimValue::instance().
floatReturnValue()
SimValue & FixedRegisters::floatReturnValue () const
Returns float return value.
Returns
Float return value.
Definition at line 111 of file FixedRegisters.cc.
{
    if (floatReturnValue_ == NULL) {
        return NullSimValue::instance();
    }
    return *floatReturnValue_;
}
References floatReturnValue_, and NullSimValue::instance().
integerArgumentRegister()
SimValue & FixedRegisters::integerArgumentRegister (int index) const
Returns integer argument with a given index.
If index is out of range, returns NullSimValue.
Returns
Integer argument with a given index.
Definition at line 70 of file FixedRegisters.cc.
{
    if (index < 0 || index > static_cast<int>(integerArgs_.size()) - 1) {
        return NullSimValue::instance();
    }
    return *integerArgs_[index];
}
References NullSimValue::instance(), and integerArgs_.
integerReturnValue()
SimValue & FixedRegisters::integerReturnValue () const
Returns integer return value.
Returns
Integer return value.
Definition at line 98 of file FixedRegisters.cc.
{
    if (intReturnValue_ == NULL) {
        return NullSimValue::instance();
    }
    return *intReturnValue_;
}
References NullSimValue::instance(), and intReturnValue_.
operator=()
FixedRegisters & FixedRegisters::operator= (const FixedRegisters) private
Assignment not allowed.
setFloatReturnValue()
void FixedRegisters::setFloatReturnValue (SimValue & value)
Sets float return value to new value.
Parameters
value New value.
Definition at line 164 of file FixedRegisters.cc.
{
    floatReturnValue_ = &value;
}
References floatReturnValue_.
setIntegerReturnValue()
void FixedRegisters::setIntegerReturnValue (SimValue & value)
Sets integer return value to new value.
Parameters
value New value.
Definition at line 154 of file FixedRegisters.cc.
{
    intReturnValue_ = &value;
}
References intReturnValue_.
setStackPointer()
void FixedRegisters::setStackPointer (SimValue & value)
Sets stack pointer to new value.
Parameters
value New value.
Definition at line 124 of file FixedRegisters.cc.
{
    stackPointer_ = &value;
}
References stackPointer_.
stackPointer()
SimValue & FixedRegisters::stackPointer () const
Returns the stack pointer value.
Returns
Stack pointer value.
Definition at line 55 of file FixedRegisters.cc.
{
    if (stackPointer_ == NULL) {
        return NullSimValue::instance();
    }
    return *stackPointer_;
}
References NullSimValue::instance(), and stackPointer_.
Member Data Documentation
floatArgs_
std::vector<SimValue*> FixedRegisters::floatArgs_ private
Floating point argument registers.
Definition at line 72 of file FixedRegisters.hh.
Referenced by addFloatArgumentRegister(), and floatArgumentRegister().
floatReturnValue_
SimValue* FixedRegisters::floatReturnValue_ private
Floating point return value.
Definition at line 76 of file FixedRegisters.hh.
Referenced by floatReturnValue(), and setFloatReturnValue().
integerArgs_
std::vector<SimValue*> FixedRegisters::integerArgs_ private
Integer argument registers.
Definition at line 70 of file FixedRegisters.hh.
Referenced by addIntegerArgumentRegister(), and integerArgumentRegister().
intReturnValue_
SimValue* FixedRegisters::intReturnValue_ private
Integer return value.
Definition at line 74 of file FixedRegisters.hh.
Referenced by integerReturnValue(), and setIntegerReturnValue().
stackPointer_
SimValue* FixedRegisters::stackPointer_ private
Stack pointer.
Definition at line 68 of file FixedRegisters.hh.
Referenced by setStackPointer(), and stackPointer().
The documentation for this class was generated from the following files:
FixedRegisters.hh
FixedRegisters.cc