OpenASIP: BridgeEncoding Class Reference
BridgeEncoding Class Reference
#include <BridgeEncoding.hh>
Public Member Functions
BridgeEncoding (const std::string &name, unsigned int encoding, unsigned int extraBits, SourceField &parent)
BridgeEncoding (const ObjectState *state, SourceField &parent)
virtual ~BridgeEncoding ()
SourceField * parent () const
std::string bridgeName () const
virtual int bitPosition () const
virtual ObjectState * saveState () const
Public Member Functions inherited from Encoding
virtual ~Encoding ()
InstructionField * parent () const
unsigned int encoding () const
unsigned int extraBits () const
virtual int width () const
Static Public Attributes
static const std::string OSNAME_BRIDGE_ENCODING = "bridge_encoding"
ObjectState name for bridge encoding.
static const std::string OSKEY_BRIDGE_NAME = "bridge_name"
ObjectState attribute key for the name of the bridge.
Static Public Attributes inherited from Encoding
static const std::string OSNAME_ENCODING = "encoding"
ObjectState name for Encoding class.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Private Attributes
std::string bridge_
Name of the bridge.
Additional Inherited Members
Protected Member Functions inherited from Encoding
Encoding (unsigned int encoding, unsigned int extraBits, InstructionField *parent)
Encoding (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
void setEncoding (unsigned int encoding, unsigned int extraBits)
Detailed Description
Class BridgeEncoding maps a bridge to a binary encoding.
Definition at line 47 of file BridgeEncoding.hh.
Constructor & Destructor Documentation
BridgeEncoding() [1/2]
BridgeEncoding::BridgeEncoding (const std::string & name, unsigned int encoding, unsigned int extraBits, SourceField & parent)
The constructor.
Creates an encoding for the given bridge and registers it into the given source field.
Parameters
name Name of the bridge.
encoding The encoding.
extraBits The number of extra (zero) bits in the encoding.
parent The parent source field.
Exceptions
ObjectAlreadyExists If the parent source field has an encoding for this bridge already or if the encoding is ambiguous with some other encoding.
Definition at line 60 of file BridgeEncoding.cc.
    : Encoding(encoding, extraBits, NULL), bridge_(name) {
    parent.addBridgeEncoding(*this);
    setParent(&parent);
}
References SourceField::addBridgeEncoding(), parent(), and Encoding::setParent().
BridgeEncoding() [2/2]
BridgeEncoding::BridgeEncoding (const ObjectState * state, SourceField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent source field.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the parent source field has an encoding for this bridge already or if the encoding is ambiguous with some other encoding.
Definition at line 81 of file BridgeEncoding.cc.
    : Encoding(state, NULL), bridge_("") {
    const string procName = "BridgeEncoding::BridgeEncoding";
    if (state->name() != OSNAME_BRIDGE_ENCODING) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
    bridge_ = state->stringAttribute(OSKEY_BRIDGE_NAME);
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
    parent.addBridgeEncoding(*this);
    setParent(&parent);
}
References SourceField::addBridgeEncoding(), bridge_, Exception::errorMessage(), ObjectState::name(), OSKEY_BRIDGE_NAME, OSNAME_BRIDGE_ENCODING, parent(), Encoding::setParent(), and ObjectState::stringAttribute().
~BridgeEncoding()
BridgeEncoding::~BridgeEncoding () virtual
The destructor.
Definition at line 103 of file BridgeEncoding.cc.
{
    SourceField* parent = this->parent();
    setParent(NULL);
    parent->removeBridgeEncoding(*this);
}
References parent(), SourceField::removeBridgeEncoding(), and Encoding::setParent().
Member Function Documentation
bitPosition()
int BridgeEncoding::bitPosition () const virtual
Returns the position of the bridge encoding within the source field.
Returns
The position.
Implements Encoding.
Definition at line 145 of file BridgeEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::RIGHT) {
        return 0;
    } else {
        return parent()->width() - parent()->extraBits() - width();
    }
}
References InstructionField::extraBits(), parent(), BinaryEncoding::RIGHT, Encoding::width(), and SourceField::width().
bridgeName()
std::string BridgeEncoding::bridgeName () const
Returns the name of the bridge.
Returns
The name of the bridge.
Definition at line 134 of file BridgeEncoding.cc.
{
    return bridge_;
}
References bridge_.
Referenced by SourceField::addBridgeEncoding(), SourceField::bridgeEncoding(), SourceField::hasBridgeEncoding(), printSourceFieldEncodings(), and saveState().
parent()
SourceField * BridgeEncoding::parent () const
Returns the parent source field.
Returns
The parent source field.
Definition at line 116 of file BridgeEncoding.cc.
{
    InstructionField* parent = Encoding::parent();
    if (parent != NULL) {
        SourceField* sField = dynamic_cast<SourceField*>(parent);
        assert(sField != NULL);
        return sField;
    } else {
        return NULL;
    }
}
References assert, parent(), and Encoding::parent().
Referenced by SourceField::addBridgeEncoding(), bitPosition(), BridgeEncoding(), BridgeEncoding(), parent(), SourceField::removeBridgeEncoding(), and ~BridgeEncoding().
saveState()
ObjectState * BridgeEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from Encoding.
Definition at line 160 of file BridgeEncoding.cc.
{
    ObjectState* state = Encoding::saveState();
    state->setName(OSNAME_BRIDGE_ENCODING);
    state->setAttribute(OSKEY_BRIDGE_NAME, bridgeName());
    return state;
}
References bridgeName(), OSKEY_BRIDGE_NAME, OSNAME_BRIDGE_ENCODING, Encoding::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by SourceField::saveState().
Member Data Documentation
bridge_
std::string BridgeEncoding::bridge_ private
Name of the bridge.
Definition at line 68 of file BridgeEncoding.hh.
Referenced by BridgeEncoding(), and bridgeName().
OSKEY_BRIDGE_NAME
const std::string BridgeEncoding::OSKEY_BRIDGE_NAME = "bridge_name" static
ObjectState attribute key for the name of the bridge.
Definition at line 64 of file BridgeEncoding.hh.
Referenced by BridgeEncoding(), saveState(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
OSNAME_BRIDGE_ENCODING
const std::string BridgeEncoding::OSNAME_BRIDGE_ENCODING = "bridge_encoding" static
ObjectState name for bridge encoding.
Definition at line 62 of file BridgeEncoding.hh.
Referenced by BridgeEncoding(), SourceField::loadState(), saveState(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
The documentation for this class was generated from the following files:
BridgeEncoding.hh
BridgeEncoding.cc