OpenASIP: BackTraceCommand Class Reference
BackTraceCommand Class Reference
#include <BackTraceCommand.hh>
Public Member Functions
BackTraceCommand ()
virtual ~BackTraceCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the back trace command of the Simulator Control Language.
Definition at line 47 of file BackTraceCommand.hh.
Constructor & Destructor Documentation
BackTraceCommand()
BackTraceCommand::BackTraceCommand ()
Definition at line 40 of file BackTraceCommand.cc.
                                   : SimControlLanguageCommand("bt") {
}
~BackTraceCommand()
BackTraceCommand::~BackTraceCommand () virtual
Definition at line 43 of file BackTraceCommand.cc.
{
}
Member Function Documentation
execute()
bool BackTraceCommand::execute (const std::vector< DataObject > & arguments) virtual
Implements CustomCommand.
Definition at line 47 of file BackTraceCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 0, 0)) {
        return false;
    }
    if (!checkSimulationStopped()) {
        return false;
    }
    SimulatorInterpreterContext& interpreterContext =
        dynamic_cast<SimulatorInterpreterContext&>(interpreter()->context());
    SimulatorFrontend& simulatorFrontend =
        interpreterContext.simulatorFrontend();
    if (simulatorFrontend.callHistoryLength() == 0) {
        setErrorMessage(
            "Call history logging not enabled.\n"
            "Use 'setting call_history_length' to enable.");
        return false;
    }
    const CallPathTracker& cpt = simulatorFrontend.callPathTracker();
#if 0
    // move this to a separate call_path command or similar
    const CallPathTracker::ProcedureTransferQueue& callHistory =
        cpt.transfers();
    for (CallPathTracker::ProcedureTransferQueue::const_iterator i =
             callHistory.begin(); i != callHistory.end(); ++i) {
        CallPathTracker::ProcedureTransfer tr = *i;
        TCEString procName =
            dynamic_cast<const TTAProgram::Procedure&>(
                simulatorFrontend.program().instructionAt(tr.address).
                parent()).name();
        if (tr.isEntry) {
            outputStream()
                << "called ";
        } else {
            outputStream()
                << "returned to ";
        }
        outputStream()
            << procName << "@" << tr.sourceAddress << std::endl;
    }
#endif
    const CallPathTracker::ProcedureTransferQueue& calls =
        cpt.backTrace();
    int callLevel = 0;
    CallPathTracker::ProcedureTransferQueue::const_iterator i =
        calls.begin();
    for (; i != calls.end(); ++i) {
        CallPathTracker::ProcedureTransfer tr = *i;
        TCEString procName =
            dynamic_cast<const TTAProgram::Procedure&>(
                simulatorFrontend.program().instructionAt(tr.address).
                parent()).name();
        assert(tr.isEntry);
        outputStream()
            << "#" << callLevel << " called "
            << procName << "@" << tr.sourceAddress << std::endl;
        ++callLevel;
    }
    return true;
}
References CallPathTracker::ProcedureTransfer::address, assert, CallPathTracker::backTrace(), SimulatorFrontend::callHistoryLength(), SimulatorFrontend::callPathTracker(), CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkSimulationStopped(), ScriptInterpreter::context(), TTAProgram::Program::instructionAt(), CustomCommand::interpreter(), CallPathTracker::ProcedureTransfer::isEntry, CustomCommand::name(), SimControlLanguageCommand::outputStream(), SimulatorFrontend::program(), SimControlLanguageCommand::setErrorMessage(), SimControlLanguageCommand::simulatorFrontend(), SimulatorInterpreterContext::simulatorFrontend(), CallPathTracker::ProcedureTransfer::sourceAddress, and CallPathTracker::transfers().
helpText()
std::string BackTraceCommand::helpText () const virtual
Implements CustomCommand.
Definition at line 117 of file BackTraceCommand.cc.
{
    return std::string(
        "Prints the current call stack (back trace).\n"
        "Requires call history saving to be on.\n"
        "See 'setting call_history_length'.");
}
The documentation for this class was generated from the following files:
BackTraceCommand.hh
BackTraceCommand.cc