OpenASIP: GPRGuardEncoding Class Reference
GPRGuardEncoding Class Reference
#include <GPRGuardEncoding.hh>
Public Member Functions
GPRGuardEncoding (const std::string &regFile, int index, bool inverted, unsigned int encoding, GuardField &parent)
GPRGuardEncoding (const ObjectState *state, GuardField &parent)
virtual ~GPRGuardEncoding ()
std::string registerFile () const
int registerIndex () const
virtual ObjectState * saveState () const
Public Member Functions inherited from GuardEncoding
virtual ~GuardEncoding ()
GuardField * parent () const
bool isGuardInverted () const
unsigned int encoding () const
Static Public Attributes
static const std::string OSNAME_GPR_GUARD_ENCODING
ObjectState name for GPR guard encoding.
static const std::string OSKEY_RF_NAME = "rf_name"
ObjectState attribute key for the name of the register file.
static const std::string OSKEY_REGISTER_INDEX = "reg_index"
ObjectState attribute key for register index.
Static Public Attributes inherited from GuardEncoding
static const std::string OSNAME_GUARD_ENCODING = "guard_encoding"
ObjectState name for guard encoding.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for invert flag.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for encoding.
Private Attributes
std::string regFile_
Name of the register file.
int index_
Register index.
Additional Inherited Members
Protected Member Functions inherited from GuardEncoding
GuardEncoding (bool inverted, unsigned int encoding)
GuardEncoding (const ObjectState *state)
void setParent (GuardField *parent)
Detailed Description
The GPRGuardEncoding class maps a guard expression with general purpose register term to a control code.
Instances of this class are always registered to a guard field.
Definition at line 47 of file GPRGuardEncoding.hh.
Constructor & Destructor Documentation
GPRGuardEncoding() [1/2]
GPRGuardEncoding::GPRGuardEncoding (const std::string & regFile, int index, bool inverted, unsigned int encoding, GuardField & parent)
The constructor.
Creates a guard encoding and Registers it into the given guard field automatically. The guard expression is identified by the name of register file, the index of the GPR and the "invert" flag, all given as parameters.
Parameters
regFile Name of the register file.
index The index the GPR.
inverted The "invert" flag.
encoding The control code of the guard expression.
parent The parent guard field.
Exceptions
ObjectAlreadyExists If the guard expression is already encoded in the parent field, or if the given control code is already assigned to another guard expression.
Definition at line 63 of file GPRGuardEncoding.cc.
    : GuardEncoding(inverted, encoding), regFile_(regFile), index_(index) {
    parent.addGuardEncoding(*this);
    setParent(&parent);
}
References GuardField::addGuardEncoding(), GuardEncoding::parent(), and GuardEncoding::setParent().
GPRGuardEncoding() [2/2]
GPRGuardEncoding::GPRGuardEncoding (const ObjectState * state, GuardField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent guard field.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the guard expression is already encoded in the parent field, or if the given control code is already assigned to another guard expression.
Definition at line 85 of file GPRGuardEncoding.cc.
    : GuardEncoding(state), regFile_(""), index_(0) {
    const string procName = "GPRGuardEncoding::GPRGuardEncoding";
    if (state->name() != OSNAME_GPR_GUARD_ENCODING) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
    regFile_ = state->stringAttribute(OSKEY_RF_NAME);
    index_ = state->intAttribute(OSKEY_REGISTER_INDEX);
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
    parent.addGuardEncoding(*this);
    setParent(&parent);
}
References GuardField::addGuardEncoding(), Exception::errorMessage(), index_, ObjectState::intAttribute(), ObjectState::name(), OSKEY_REGISTER_INDEX, OSKEY_RF_NAME, OSNAME_GPR_GUARD_ENCODING, GuardEncoding::parent(), regFile_, GuardEncoding::setParent(), and ObjectState::stringAttribute().
~GPRGuardEncoding()
GPRGuardEncoding::~GPRGuardEncoding () virtual
The destructor.
Definition at line 108 of file GPRGuardEncoding.cc.
{
    GuardField* parent = this->parent();
    setParent(NULL);
    parent->removeGuardEncoding(*this);
}
References GuardEncoding::parent(), GuardField::removeGuardEncoding(), and GuardEncoding::setParent().
Member Function Documentation
registerFile()
std::string GPRGuardEncoding::registerFile () const
Returns the name of the register file that contains the GPR of this guard expression.
Returns
The name of the register file.
Definition at line 122 of file GPRGuardEncoding.cc.
{
    return regFile_;
}
References regFile_.
Referenced by GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), GuardField::gprGuardEncoding(), GuardField::hasGPRGuardEncoding(), printGuardFieldEncodings(), and saveState().
registerIndex()
int GPRGuardEncoding::registerIndex () const
Returns the index of the GPR of this guard expression.
Returns
The index of the GPR.
Definition at line 133 of file GPRGuardEncoding.cc.
{
    return index_;
}
References index_.
Referenced by GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), GuardField::gprGuardEncoding(), GuardField::hasGPRGuardEncoding(), printGuardFieldEncodings(), and saveState().
saveState()
ObjectState * GPRGuardEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from GuardEncoding.
Definition at line 144 of file GPRGuardEncoding.cc.
{
    ObjectState* state = GuardEncoding::saveState();
    state->setName(OSNAME_GPR_GUARD_ENCODING);
    state->setAttribute(OSKEY_RF_NAME, registerFile());
    state->setAttribute(OSKEY_REGISTER_INDEX, registerIndex());
    return state;
}
References OSKEY_REGISTER_INDEX, OSKEY_RF_NAME, OSNAME_GPR_GUARD_ENCODING, registerFile(), registerIndex(), GuardEncoding::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by GuardField::saveState().
Member Data Documentation
index_
int GPRGuardEncoding::index_ private
Register index.
Definition at line 71 of file GPRGuardEncoding.hh.
Referenced by GPRGuardEncoding(), and registerIndex().
OSKEY_REGISTER_INDEX
const std::string GPRGuardEncoding::OSKEY_REGISTER_INDEX = "reg_index" static
ObjectState attribute key for register index.
Definition at line 65 of file GPRGuardEncoding.hh.
Referenced by GPRGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSKEY_RF_NAME
const std::string GPRGuardEncoding::OSKEY_RF_NAME = "rf_name" static
ObjectState attribute key for the name of the register file.
Definition at line 63 of file GPRGuardEncoding.hh.
Referenced by GPRGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSNAME_GPR_GUARD_ENCODING
const std::string GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING static
Initial value:
=
    "gpr_guard_enc"
ObjectState name for GPR guard encoding.
Definition at line 61 of file GPRGuardEncoding.hh.
Referenced by GPRGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), GuardField::loadState(), and saveState().
regFile_
std::string GPRGuardEncoding::regFile_ private
Name of the register file.
Definition at line 69 of file GPRGuardEncoding.hh.
Referenced by GPRGuardEncoding(), and registerFile().
The documentation for this class was generated from the following files:
GPRGuardEncoding.hh
GPRGuardEncoding.cc