OpenASIP: SetRFArchitectureCmd Class Reference
SetRFArchitectureCmd Class Reference
#include <SetRFArchitectureCmd.hh>
Public Member Functions
SetRFArchitectureCmd ()
virtual ~SetRFArchitectureCmd ()
virtual bool Do ()
virtual int id () const
virtual SetRFArchitectureCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for setting architecture of a RFEntry.
Definition at line 41 of file SetRFArchitectureCmd.hh.
Constructor & Destructor Documentation
SetRFArchitectureCmd()
SetRFArchitectureCmd::SetRFArchitectureCmd ()
The Constructor.
Definition at line 48 of file SetRFArchitectureCmd.cc.
                                           :
    GUICommand(HDBEditorConstants::COMMAND_NAME_SET_RF_ARCH, NULL) {
}
Referenced by create().
~SetRFArchitectureCmd()
SetRFArchitectureCmd::~SetRFArchitectureCmd () virtual
The Destructor.
Definition at line 56 of file SetRFArchitectureCmd.cc.
{
}
Member Function Documentation
create()
SetRFArchitectureCmd * SetRFArchitectureCmd::create () const virtual
Creates and returns a new instance of the command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 132 of file SetRFArchitectureCmd.cc.
{
    return new SetRFArchitectureCmd();
}
References SetRFArchitectureCmd().
Do()
bool SetRFArchitectureCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 63 of file SetRFArchitectureCmd.cc.
{
    HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    const RFEntry* entry = manager->rfByID(
        wxGetApp().mainFrame().browser()->selectedRFEntry());
    wxString rfs[1000];
    const std::set<RowID> rfIDs = manager->rfArchitectureIDs();
    std::set<RowID>::iterator iter = rfIDs.begin();
    int i = 0;
    for (;iter != rfIDs.end(); iter++) {
        rfs[i] = WxConversion::toWxString(*iter);
        i++;
    }
    wxSingleChoiceDialog choicer(
        parentWindow(), _T("Choose Architecture"), _T("Choose Architecture"),
        i, rfs);
    if (choicer.ShowModal() != wxID_OK) {
        return false;
    }
    std::string archID = WxConversion::toString(choicer.GetStringSelection());
    RowID rowID = Conversion::toInt(archID);
    manager->unsetArchitectureForRF(entry->id());
    manager->setArchitectureForRF(entry->id(), rowID);
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectRFEntry(entry->id());
    return true;
}
References HDB::HDBEntry::id(), GUICommand::parentWindow(), HDB::HDBManager::rfArchitectureIDs(), HDB::HDBManager::setArchitectureForRF(), Conversion::toInt(), WxConversion::toString(), WxConversion::toWxString(), and HDB::HDBManager::unsetArchitectureForRF().
icon()
std::string SetRFArchitectureCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 109 of file SetRFArchitectureCmd.cc.
{
    return "";
}
id()
int SetRFArchitectureCmd::id () const virtual
Returns the command id.
Returns
Command identifier for this command.
Implements GUICommand.
Definition at line 121 of file SetRFArchitectureCmd.cc.
{
    return HDBEditorConstants::COMMAND_SET_RF_ARCH;
}
References HDBEditorConstants::COMMAND_SET_RF_ARCH.
isEnabled()
bool SetRFArchitectureCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 142 of file SetRFArchitectureCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    if (!wxGetApp().mainFrame().browser()->isRFEntrySelected()) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
SetRFArchitectureCmd.hh
SetRFArchitectureCmd.cc