OpenASIP: Evaluate Class Reference
Evaluate Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Evaluates and/or estimates a configuration.")
Evaluate ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual std::vector< RowID > explore (const RowID &configurationID, const unsigned int &)
void readParameters ()
bool createConfig (const std::string &adf, const std::string &idf, DSDBManager &dsdb, DSDBManager::MachineConfiguration &conf)
void printEstimates (const CostEstimates &estimates, const DSDBManager::MachineConfiguration &configuration)
Private Attributes
std::string adf_
name of the adf file to evaluate
std::string idf_
name of the idf file to evaluate
bool print_
print evaluation results
Static Private Attributes
static const std::string adfPN_
static const std::string idfPN_
static const std::string printPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual bool requiresApplication () const
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that evaluates a configuration and estimates it if the configuration has an implementation.
Definition at line 59 of file Evaluate.cc.
Constructor & Destructor Documentation
Evaluate()
Evaluate::Evaluate () inline private
Definition at line 62 of file Evaluate.cc.
              : DesignSpaceExplorerPlugin(),
        adf_(""),
        idf_(""),
        print_(true) {
        // compulsory parameters
        // no compulsory parameters
        // parameters that have a default value
        addParameter(adfPN_, STRING, false, adf_);
        addParameter(idfPN_, STRING, false, idf_);
        addParameter(printPN_, BOOL, false, Conversion::toString(print_));
    }
References DesignSpaceExplorerPlugin::addParameter(), adf_, adfPN_, BOOL, idf_, idfPN_, print_, printPN_, STRING, and Conversion::toString().
Member Function Documentation
createConfig()
bool Evaluate::createConfig (const std::string & adf, const std::string & idf, DSDBManager & dsdb, DSDBManager::MachineConfiguration & conf) inline private
Load adf and idf from files and store to given dsdb and config.
Parameters
adf Path of architecture definition file.
idf Path of implementation definition file.
dsdb Database where to store adf and idf.
conf Configuration for adf/idf ids.
Returns
True if creating config succeeded, else false.
Definition at line 174 of file Evaluate.cc.
{
        assert(adf != "");
        IDF::MachineImplementation* idfo = NULL;
        TTAMachine::Machine* mach = NULL;
        try {
            if (adf != "") {
                mach = TTAMachine::Machine::loadFromADF(adf);
                conf.architectureID = dsdb.addArchitecture(*mach);
            } else {
                return false;
            }
            if (idf != "") {
                idfo = IDF::MachineImplementation::loadFromIDF(idf);
                conf.implementationID =
                    dsdb.addImplementation(*idfo, 0,0);
                conf.hasImplementation = true;
            } else {
                conf.hasImplementation = false;
            }
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error loading the adf/idf." << std::endl;
            verboseLog(msg.str());
            delete mach;
            return false;
        }
        delete mach;
        return true;
    }
References DSDBManager::addArchitecture(), DSDBManager::addImplementation(), DSDBManager::MachineConfiguration::architectureID, assert, DSDBManager::MachineConfiguration::hasImplementation, DSDBManager::MachineConfiguration::implementationID, TTAMachine::Machine::loadFromADF(), IDF::MachineImplementation::loadFromIDF(), and verboseLog.
Referenced by explore().
explore()
virtual std::vector< RowID > Evaluate::explore (const RowID & startPointConfigurationID, const unsigned int & maxIter) inline private virtual
Explores the design space from the starting point machine and returns best exploring results as configuration IDs.
Exploring creates new machine configurations (architecture, implementation) that are ordered so that the best results are first in the result vector.
Parameters
startPoint Starting point machine configuration for the plugin.
maxIter Maximum number of design space points the plugin is allowed to explore. Default value for maxIter is zero when the iteration number is not taken into account. In that case the exploration runs indefinetly or stops at a point defined by the algorithm.
Returns
Ordered vector of IDs of the best machine configurations where the target programs can be successfully run. The IDs of the best machine configurations are first in the result vector. Returns an empty vector if does not find any possible machine configurations.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 82 of file Evaluate.cc.
{
        readParameters();
        std::vector<RowID> result;
        // make params for adf and idf, so no configuration needed
        if (configurationID == 0 && adf_ == "") {
            std::ostringstream msg(std::ostringstream::out);
            msg << "No configuration nor adf defined. Use -s <confID> to "
                << "define the configuration to be optimized or give adf "
                << "as plugin parameter." << endl;
            verboseLog(msg.str());
            return result;
        }
        DSDBManager& dsdb = db();
        DSDBManager::MachineConfiguration conf;
        // load adf/idf from file if no configuration was given
        if (configurationID == 0) {
            if (!createConfig(adf_, idf_, dsdb, conf)) {
               return result;
            }
        } else {
            // if starting configuration given load it
            conf = dsdb.configuration(configurationID);
        }
        CostEstimates estimates;
        bool estimate = (conf.hasImplementation ? true : false);
        try {
            if (!evaluate(conf, estimates, estimate)) {
                verboseLog(std::string("Evaluate failed."))
                return result;
            }
        } catch (const Exception& e) {
            debugLog(std::string("Error in Evaluate plugin: ")
                    + e.errorMessage() + std::string(" ")
                    + e.errorMessageStack());
            return result;
        }
        verboseLogC(std::string("Evalution OK, ")
                + (estimate ? "with" : "without") + " estimation.",1)
        if (print_ && estimate) {
            printEstimates(estimates, conf);
        }
        // add new configuration to the database
        if (configurationID == 0) {
            RowID newConfID = addConfToDSDB(conf);
            if (newConfID != 0) {
                result.push_back(newConfID);
            }
        }
        return result;
    }
References DesignSpaceExplorer::addConfToDSDB(), adf_, DSDBManager::configuration(), createConfig(), DesignSpaceExplorer::db(), debugLog, Exception::errorMessage(), Exception::errorMessageStack(), DesignSpaceExplorer::evaluate(), DSDBManager::MachineConfiguration::hasImplementation, idf_, print_, printEstimates(), readParameters(), verboseLog, and verboseLogC.
PLUGIN_DESCRIPTION()
Evaluate::PLUGIN_DESCRIPTION ("Evaluates and/or estimates a configuration.") private
printEstimates()
void Evaluate::printEstimates (const CostEstimates & estimates, const DSDBManager::MachineConfiguration & configuration) inline private
Print estimates
Parameters
estimates The cost estimates to be printed.
Definition at line 216 of file Evaluate.cc.
{
        std::ostream& log = std::cout;
        log.flags(std::ios::left);
        int fw = 27;
        log << setw(fw) << "Area: " << estimates.area() << endl;
        log << setw(fw) << "Longest path delay: " <<
            estimates.longestPathDelay() << endl;
        for (int i = 0; i < estimates.energies(); ++i) {
            log << "application " << i << setw(14) << " energy: " <<
                estimates.energy(i) << endl;
        }
        std::vector<ClockCycleCount> cycleCounts =
            db().cycleCounts(configuration);
        for (int i = 0; i < (int)cycleCounts.size(); ++i) {
            log << "application " << i << " cycle count: " <<
                cycleCounts.at(i) << endl;
        }
    }
References CostEstimates::area(), DSDBManager::cycleCounts(), DesignSpaceExplorer::db(), CostEstimates::energies(), CostEstimates::energy(), and CostEstimates::longestPathDelay().
Referenced by explore().
producesArchitecture()
virtual bool Evaluate::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 77 of file Evaluate.cc.
{ return false; }
readParameters()
void Evaluate::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 157 of file Evaluate.cc.
{
        // optional parameters
        readOptionalParameter(adfPN_, adf_);
        readOptionalParameter(idfPN_, idf_);
        readOptionalParameter(printPN_, print_);
    }
References adf_, adfPN_, idf_, idfPN_, print_, printPN_, and DesignSpaceExplorerPlugin::readOptionalParameter().
Referenced by explore().
requiresHDB()
virtual bool Evaluate::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 78 of file Evaluate.cc.
{ return false; }
requiresSimulationData()
virtual bool Evaluate::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 79 of file Evaluate.cc.
{ return true; }
requiresStartingPointArchitecture()
virtual bool Evaluate::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 76 of file Evaluate.cc.
{ return false; }
Member Data Documentation
adf_
std::string Evaluate::adf_ private
name of the adf file to evaluate
Definition at line 148 of file Evaluate.cc.
Referenced by Evaluate(), explore(), and readParameters().
adfPN_
const std::string Evaluate::adfPN_ static private
Definition at line 142 of file Evaluate.cc.
Referenced by Evaluate(), and readParameters().
idf_
std::string Evaluate::idf_ private
name of the idf file to evaluate
Definition at line 150 of file Evaluate.cc.
Referenced by Evaluate(), explore(), and readParameters().
idfPN_
const std::string Evaluate::idfPN_ static private
Definition at line 143 of file Evaluate.cc.
Referenced by Evaluate(), and readParameters().
print_
bool Evaluate::print_ private
print evaluation results
Definition at line 152 of file Evaluate.cc.
Referenced by Evaluate(), explore(), and readParameters().
printPN_
const std::string Evaluate::printPN_ static private
Definition at line 144 of file Evaluate.cc.
Referenced by Evaluate(), and readParameters().
The documentation for this class was generated from the following file:
Evaluate.cc