OpenASIP: SOPCBuilderFileGenerator Class Reference
SOPCBuilderFileGenerator Class Reference
#include <SOPCBuilderFileGenerator.hh>
Public Member Functions
SOPCBuilderFileGenerator (TCEString toplevelEntity, const PlatformIntegrator *integrator)
virtual ~SOPCBuilderFileGenerator ()
virtual void writeProjectFiles ()
Public Member Functions inherited from ProjectFileGenerator
ProjectFileGenerator (TCEString coreEntity, const PlatformIntegrator *integrator)
virtual ~ProjectFileGenerator ()
void addHdlFile (const TCEString &file)
void addHdlFiles (const std::vector< TCEString > &files)
void addMemInitFile (const TCEString &memInit)
void addSignalMapping (const PlatInt::SignalMapping &mapping)
Private Member Functions
int countAvalonMMMasters () const
void createInterfaces ()
bool handleAvalonSignal (const ProGe::NetlistPort &port)
void exportSignal (const ProGe::NetlistPort &port)
void writeModuleProperties (std::ostream &stream)
void writeGenerics (std::ostream &stream)
void writeFileList (std::ostream &stream)
void writeInterfaces (std::ostream &stream) const
AvalonMMMasterInterface * getMaster (const TCEString &fuName)
Private Attributes
SOPCInterface * clock_
SOPCInterface * export_
std::map< TCEString, AvalonMMMasterInterface * > masters_
Static Private Attributes
static const TCEString HDB_AVALON_PREFIX = "avalon_d_"
static const TCEString SOPC_COMPONENT_FILE_TYPE
static const TCEString TTA_CLOCK_NAME = "clk"
static const TCEString TTA_RESET_NAME = "rstx"
static const TCEString SOPC_CLOCK_NAME = "clk"
static const TCEString SOPC_RESET_NAME = "reset_n"
static const TCEString SOPC_DEFAULT_GROUP = "User Logic"
static const TCEString SOPC_DEFAULT_VHDL_LIBS
static const TCEString SOPC_SET_MODULE_PROPERTY
static const TCEString SOPC_ADD_FILE
static const TCEString PI_DEVICE_FAMILY_GENERIC
Additional Inherited Members
Protected Member Functions inherited from ProjectFileGenerator
const std::vector< TCEString > & hdlFileList () const
const std::vector< TCEString > & memInitFileList () const
const PlatformIntegrator * integrator () const
TCEString coreEntity () const
TCEString toplevelEntity () const
int signalMappingCount () const
const PlatInt::SignalMapping * signalMapping (int index) const
TCEString extractFUName (const TCEString &port, const TCEString &delimiter) const
Detailed Description
Definition at line 45 of file SOPCBuilderFileGenerator.hh.
Constructor & Destructor Documentation
SOPCBuilderFileGenerator()
SOPCBuilderFileGenerator::SOPCBuilderFileGenerator (TCEString toplevelEntity, const PlatformIntegrator * integrator)
Definition at line 70 of file SOPCBuilderFileGenerator.cc.
                                         :
    ProjectFileGenerator(toplevelEntity, integrator),
    clock_(new SOPCInterface(
               SOPCInterface::SOPC_CLOCK_INT_NAME,
               SOPCInterface::SOPC_CLOCK_INT_DECLR)),
    export_(new SOPCInterface(
                SOPCInterface::SOPC_EXPORT_INT_NAME,
                SOPCInterface::SOPC_EXPORT_INT_DECLR)) {
    clock_->setProperty("ptfSchematicName", "\"\"");
    clock_->setPort(TTA_CLOCK_NAME, SOPC_CLOCK_NAME, ProGe::IN, 1);
    clock_->setPort(TTA_RESET_NAME, SOPC_RESET_NAME, ProGe::IN, 1);
    export_->setProperty(
        SOPCInterface::SOPC_ASSOCIATED_CLOCK, clock_->name());
}
References clock_, export_, ProGe::IN, SOPCInterface::name(), SOPCInterface::setPort(), SOPCInterface::setProperty(), SOPCInterface::SOPC_ASSOCIATED_CLOCK, SOPC_CLOCK_NAME, SOPC_RESET_NAME, TTA_CLOCK_NAME, and TTA_RESET_NAME.
~SOPCBuilderFileGenerator()
SOPCBuilderFileGenerator::~SOPCBuilderFileGenerator () virtual
Definition at line 90 of file SOPCBuilderFileGenerator.cc.
{
    if (clock_ != NULL) {
        delete clock_;
    }
    if (export_ != NULL) {
        delete export_;
    }
    MapTools::deleteAllValues(masters_);
}
References clock_, MapTools::deleteAllValues(), export_, and masters_.
Member Function Documentation
countAvalonMMMasters()
int SOPCBuilderFileGenerator::countAvalonMMMasters () const private
Counts how many Avalon MM Master interfaces toplevel netlis block has.
Avalon MM interface is recognised by the address port. Address signal in first of the 2 mandatory signals in Avalon MM interface. Direction of the address port determines whether it belongs to a master or slave interface.
Returns
Number of found Avalon MM Master interfaces
Definition at line 147 of file SOPCBuilderFileGenerator.cc.
{
    const ProGe::NetlistBlock& top = integrator()->toplevelBlock();
    TCEString addressPortName =
        HDB_AVALON_PREFIX + AvalonMMMasterInterface::AVALON_MM_ADDRESS;
    int found = 0;
    for (size_t i = 0; i < top.portCount(); i++) {
        TCEString portName = top.port(i).name();
        if (portName.find(addressPortName) != TCEString::npos) {
            if (top.port(i).direction() == ProGe::OUT) {
                found++;
            }
        }
    }
    return found;
}
References AvalonMMMasterInterface::AVALON_MM_ADDRESS, ProGe::NetlistPort::direction(), HDB_AVALON_PREFIX, ProjectFileGenerator::integrator(), ProGe::NetlistPort::name(), ProGe::OUT, ProGe::NetlistBlock::port(), ProGe::NetlistBlock::portCount(), and PlatformIntegrator::toplevelBlock().
Referenced by writeProjectFiles().
createInterfaces()
void SOPCBuilderFileGenerator::createInterfaces () private
Definition at line 246 of file SOPCBuilderFileGenerator.cc.
{
    const ProGe::NetlistBlock& top = integrator()->toplevelBlock();
    for (size_t i = 0; i < top.portCount(); i++) {
        TCEString portName = top.port(i).name();
        bool needToExport = true;
        if (portName == TTA_CLOCK_NAME || portName == TTA_RESET_NAME) {
            continue;
        } else if (portName.find(HDB_AVALON_PREFIX) != TCEString::npos) {
            needToExport = !handleAvalonSignal(top.port(i));
        }
        if (needToExport) {
            exportSignal(top.port(i));
        }
    }
}
References exportSignal(), handleAvalonSignal(), HDB_AVALON_PREFIX, ProjectFileGenerator::integrator(), ProGe::NetlistPort::name(), ProGe::NetlistBlock::port(), ProGe::NetlistBlock::portCount(), PlatformIntegrator::toplevelBlock(), TTA_CLOCK_NAME, and TTA_RESET_NAME.
Referenced by writeProjectFiles().
exportSignal()
void SOPCBuilderFileGenerator::exportSignal (const ProGe::NetlistPort & port) private
Definition at line 299 of file SOPCBuilderFileGenerator.cc.
{
    int width = 32;
    if (port.realWidthAvailable()) {
        width = port.realWidth();
    }
    TCEString intPortName = SOPCInterface::SOPC_EXPORT_NAME;
    export_->setPort(port.name(), intPortName, port.direction(), width);
}
References ProGe::NetlistPort::direction(), export_, ProGe::NetlistPort::name(), ProGe::NetlistPort::realWidth(), ProGe::NetlistPort::realWidthAvailable(), SOPCInterface::setPort(), and SOPCInterface::SOPC_EXPORT_NAME.
Referenced by createInterfaces().
getMaster()
AvalonMMMasterInterface * SOPCBuilderFileGenerator::getMaster (const TCEString & fuName) private
Definition at line 334 of file SOPCBuilderFileGenerator.cc.
{
    std::map<TCEString, AvalonMMMasterInterface*>::iterator iter =
        masters_.find(fuName);
    assert(iter != masters_.end());
    return iter->second;
}
References assert, and masters_.
Referenced by handleAvalonSignal().
handleAvalonSignal()
bool SOPCBuilderFileGenerator::handleAvalonSignal (const ProGe::NetlistPort & port) private
Definition at line 267 of file SOPCBuilderFileGenerator.cc.
{
    TCEString fuName = extractFUName(port.name(), HDB_AVALON_PREFIX);
    if (fuName.empty()) {
        TCEString msg = "Failed to extract FU name from: " + port.name();
        InvalidData exc(__FILE__, __LINE__, "SOPCBuilderFileGenerator", msg);
        throw exc;
    }
    if (!MapTools::containsKey(masters_ ,fuName)) {
        TCEString interfaceName =
            fuName + SOPCInterface::SOPC_MASTER_INT_NAME;
        TCEString declr = SOPCInterface::SOPC_MASTER_INT_DECLR;
        masters_[fuName] = new AvalonMMMasterInterface(
            interfaceName, declr, HDB_AVALON_PREFIX, *clock_);
    }
    AvalonMMMasterInterface* master = getMaster(fuName);
    bool isAvalonPort = false;
    if (!master->isValidPort(port)) {
        isAvalonPort = false;
    } else {
        master->addPort(port);
        isAvalonPort = true;
    }
    return isAvalonPort;
}
References AvalonMMMasterInterface::addPort(), clock_, MapTools::containsKey(), ProjectFileGenerator::extractFUName(), getMaster(), HDB_AVALON_PREFIX, AvalonMMMasterInterface::isValidPort(), masters_, ProGe::NetlistPort::name(), SOPCInterface::SOPC_MASTER_INT_DECLR, and SOPCInterface::SOPC_MASTER_INT_NAME.
Referenced by createInterfaces().
writeFileList()
void SOPCBuilderFileGenerator::writeFileList (std::ostream & stream) private
Definition at line 230 of file SOPCBuilderFileGenerator.cc.
{
    stream << "# module hdl files" << endl;
    for (unsigned int i = 0; i < hdlFileList().size(); i++) {
        stream << SOPC_ADD_FILE << " " << hdlFileList().at(i)
               << " {SYNTHESIS SIMULATION}" << endl;
    }
    for (unsigned int i = 0; i < memInitFileList().size(); i++) {
        stream << SOPC_ADD_FILE << " " << memInitFileList().at(i)
               << " {SYNTHESIS SIMULATION}" << endl;
    }
    stream << endl;
}
References ProjectFileGenerator::hdlFileList(), ProjectFileGenerator::memInitFileList(), and SOPC_ADD_FILE.
Referenced by writeProjectFiles().
writeGenerics()
void SOPCBuilderFileGenerator::writeGenerics (std::ostream & stream) private
Definition at line 198 of file SOPCBuilderFileGenerator.cc.
{
    const ProGe::NetlistBlock& top = integrator()->toplevelBlock();
    if (top.parameterCount() == 0) {
        return;
    }
    stream << "# toplevel parameters" << endl;
    for (size_t i = 0; i < top.parameterCount(); i++) {
        TCEString line;
        line << "add_parameter " << top.parameter(i).name() << " ";
        if (top.parameter(i).type().lower() == "string") {
            line << "STRING ";
            if (!top.parameter(i).value().startsWith("\"")) line << "\"";
            line << top.parameter(i).value();
            if (!top.parameter(i).value().endsWith("\"")) line << "\"";
        } else if (top.parameter(i).type().lower() == "integer") {
            line << "INTEGER " << top.parameter(i).value();
        } else {
            // unknown type, ignore
            continue;
        }
        stream << line << endl;
        if (top.parameter(i).name().lower() == PI_DEVICE_FAMILY_GENERIC) {
            stream << "set_parameter_property " << PI_DEVICE_FAMILY_GENERIC
                   << " DISPLAY_NAME \"Device family (change if necessary)\""
                   << endl;
        }
    }
    stream << endl;
}
References TCEString::endsWith(), ProjectFileGenerator::integrator(), TCEString::lower(), ProGe::Parameter::name(), ProGe::NetlistBlock::parameter(), ProGe::BaseNetlistBlock::parameterCount(), PI_DEVICE_FAMILY_GENERIC, TCEString::startsWith(), PlatformIntegrator::toplevelBlock(), ProGe::Parameter::type(), and ProGe::Parameter::value().
Referenced by writeProjectFiles().
writeInterfaces()
void SOPCBuilderFileGenerator::writeInterfaces (std::ostream & stream) const private
Definition at line 311 of file SOPCBuilderFileGenerator.cc.
{
    clock_->writeInterface(stream);
    std::map<TCEString, AvalonMMMasterInterface*>::const_iterator iter =
        masters_.begin();
    while (iter != masters_.end()) {
        AvalonMMMasterInterface* master = iter->second;
        if (master->hasPorts()) {
            master->writeInterface(stream);
        }
        iter++;
    }
    if (export_->hasPorts()) {
        export_->writeInterface(stream);
    }
}
References clock_, export_, SOPCInterface::hasPorts(), masters_, AvalonMMMasterInterface::writeInterface(), and SOPCInterface::writeInterface().
Referenced by writeProjectFiles().
writeModuleProperties()
void SOPCBuilderFileGenerator::writeModuleProperties (std::ostream & stream) private
Definition at line 166 of file SOPCBuilderFileGenerator.cc.
{
    TCEString property = SOPC_SET_MODULE_PROPERTY;
    stream
        << "# Module properties" << endl
        << property << " NAME " << toplevelEntity() << endl
        << property << " VERSION 1.0" << endl
        << property << " GROUP \"" << SOPC_DEFAULT_GROUP << "\"" << endl
        << property << " DISPLAY_NAME " << toplevelEntity() << endl
        << property << " LIBRARIES {" << SOPC_DEFAULT_VHDL_LIBS;
    if (integrator()->toplevelBlock().netlist().parameterCount() > 0) {
        stream << " work." << toplevelEntity() << "_params.all";
    }
    stream << "}" << endl;
    TCEString toplevelFile =
        integrator()->outputFilePath(toplevelEntity() + ".vhdl");
    stream
        << property << " TOP_LEVEL_HDL_FILE " << toplevelFile << endl
        << property << " TOP_LEVEL_HDL_MODULE " << toplevelEntity() << endl
        << property << " INSTANTIATE_IN_SYSTEM_MODULE true" << endl
        << property << " EDITABLE false" << endl
        << property << " SIMULATION_MODEL_IN_VERILOG false" << endl
        << property << " SIMULATION_MODEL_IN_VHDL false" << endl
        << property << " SIMULATION_MODEL_HAS_TULIPS false" << endl
        << property << " SIMULATION_MODEL_IS_OBFUSCATED false" << endl
        << endl;
}
References ProjectFileGenerator::integrator(), PlatformIntegrator::outputFilePath(), SOPC_DEFAULT_GROUP, SOPC_DEFAULT_VHDL_LIBS, SOPC_SET_MODULE_PROPERTY, and ProjectFileGenerator::toplevelEntity().
Referenced by writeProjectFiles().
writeProjectFiles()
void SOPCBuilderFileGenerator::writeProjectFiles () virtual
Implements ProjectFileGenerator.
Definition at line 103 of file SOPCBuilderFileGenerator.cc.
{
    int masterInterfaces = countAvalonMMMasters();
    if (masterInterfaces == 0) {
        TCEString msg = "Couldn't find any Avalon MM Master interfaces.";
        InvalidData exc(__FILE__, __LINE__, "SOPCBuilderFileGenerator", msg);
        throw exc;
    }
    createInterfaces();
    TCEString outputFileName = toplevelEntity() + SOPC_COMPONENT_FILE_TYPE;
    ofstream output;
    output.open(outputFileName.c_str());
    if (!output) {
        TCEString msg =
            "Couldn't open file " + outputFileName + " for writing";
        IOException exc(__FILE__, __LINE__, "SOPCBuilderFileGenerator", msg);
        throw exc;
    }
    output << "# Generated by SOPCBuilderGenerator" << endl << endl;
    writeModuleProperties(output);
    writeGenerics(output);
    writeFileList(output);
    writeInterfaces(output);
    output.close();
}
References countAvalonMMMasters(), createInterfaces(), outputFileName(), SOPC_COMPONENT_FILE_TYPE, ProjectFileGenerator::toplevelEntity(), writeFileList(), writeGenerics(), writeInterfaces(), and writeModuleProperties().
Member Data Documentation
clock_
SOPCInterface* SOPCBuilderFileGenerator::clock_ private
Definition at line 75 of file SOPCBuilderFileGenerator.hh.
Referenced by handleAvalonSignal(), SOPCBuilderFileGenerator(), writeInterfaces(), and ~SOPCBuilderFileGenerator().
export_
SOPCInterface* SOPCBuilderFileGenerator::export_ private
Definition at line 76 of file SOPCBuilderFileGenerator.hh.
Referenced by exportSignal(), SOPCBuilderFileGenerator(), writeInterfaces(), and ~SOPCBuilderFileGenerator().
HDB_AVALON_PREFIX
const TCEString SOPCBuilderFileGenerator::HDB_AVALON_PREFIX = "avalon_d_" static private
Definition at line 80 of file SOPCBuilderFileGenerator.hh.
Referenced by countAvalonMMMasters(), createInterfaces(), and handleAvalonSignal().
masters_
std::map<TCEString, AvalonMMMasterInterface*> SOPCBuilderFileGenerator::masters_ private
Definition at line 77 of file SOPCBuilderFileGenerator.hh.
Referenced by getMaster(), handleAvalonSignal(), writeInterfaces(), and ~SOPCBuilderFileGenerator().
PI_DEVICE_FAMILY_GENERIC
const TCEString SOPCBuilderFileGenerator::PI_DEVICE_FAMILY_GENERIC static private
Initial value:
=
    "dev_family_g"
Definition at line 93 of file SOPCBuilderFileGenerator.hh.
Referenced by writeGenerics().
SOPC_ADD_FILE
const TCEString SOPCBuilderFileGenerator::SOPC_ADD_FILE static private
Initial value:
=
    "add_file"
Definition at line 91 of file SOPCBuilderFileGenerator.hh.
Referenced by writeFileList().
SOPC_CLOCK_NAME
const TCEString SOPCBuilderFileGenerator::SOPC_CLOCK_NAME = "clk" static private
Definition at line 85 of file SOPCBuilderFileGenerator.hh.
Referenced by SOPCBuilderFileGenerator().
SOPC_COMPONENT_FILE_TYPE
const TCEString SOPCBuilderFileGenerator::SOPC_COMPONENT_FILE_TYPE static private
Initial value:
=
    "_hw.tcl"
Definition at line 81 of file SOPCBuilderFileGenerator.hh.
Referenced by writeProjectFiles().
SOPC_DEFAULT_GROUP
const TCEString SOPCBuilderFileGenerator::SOPC_DEFAULT_GROUP = "User Logic" static private
Definition at line 88 of file SOPCBuilderFileGenerator.hh.
Referenced by writeModuleProperties().
SOPC_DEFAULT_VHDL_LIBS
const TCEString SOPCBuilderFileGenerator::SOPC_DEFAULT_VHDL_LIBS static private
Initial value:
=
    "std.standard.all ieee.std_logic_1164.all ieee.std_logic_arith.all "
    "work.globals.all work.util.all work.imem_mau.all"
Definition at line 89 of file SOPCBuilderFileGenerator.hh.
Referenced by writeModuleProperties().
SOPC_RESET_NAME
const TCEString SOPCBuilderFileGenerator::SOPC_RESET_NAME = "reset_n" static private
Definition at line 86 of file SOPCBuilderFileGenerator.hh.
Referenced by SOPCBuilderFileGenerator().
SOPC_SET_MODULE_PROPERTY
const TCEString SOPCBuilderFileGenerator::SOPC_SET_MODULE_PROPERTY static private
Initial value:
=
    "set_module_property"
Definition at line 90 of file SOPCBuilderFileGenerator.hh.
Referenced by writeModuleProperties().
TTA_CLOCK_NAME
const TCEString SOPCBuilderFileGenerator::TTA_CLOCK_NAME = "clk" static private
Definition at line 83 of file SOPCBuilderFileGenerator.hh.
Referenced by createInterfaces(), and SOPCBuilderFileGenerator().
TTA_RESET_NAME
const TCEString SOPCBuilderFileGenerator::TTA_RESET_NAME = "rstx" static private
Definition at line 84 of file SOPCBuilderFileGenerator.hh.
Referenced by createInterfaces(), and SOPCBuilderFileGenerator().
The documentation for this class was generated from the following files:
SOPCBuilderFileGenerator.hh
SOPCBuilderFileGenerator.cc