OpenASIP: MemoryProxy Class Reference
MemoryProxy Class Reference
#include <MemoryProxy.hh>
Public Types
typedef std::pair< Word, int > MemoryAccess
Public Types inherited from Memory
typedef MinimumAddressableUnit MAU
typedef MAU * MAUTable
Public Member Functions
MemoryProxy (SimulatorFrontend &frontend, Memory *memory)
virtual ~MemoryProxy ()
virtual void advanceClock ()
virtual void reset ()
virtual void write (ULongWord address, MAU data) override
virtual Memory::MAU read (ULongWord address) override
virtual void write (ULongWord address, int size, ULongWord data)
virtual void read (ULongWord address, int size, ULongWord &data)
virtual void fillWithZeros ()
unsigned int readAccessCount () const
unsigned int writeAccessCount () const
MemoryAccess readAccess (unsigned int idx) const
MemoryAccess writeAccess (unsigned int idx) const
Public Member Functions inherited from Memory
Memory (ULongWord start, ULongWord end, ULongWord MAUSize, bool littleEndian_)
virtual ~Memory ()
virtual void writeBE (ULongWord address, int size, ULongWord data)
virtual void writeLE (ULongWord address, int size, ULongWord data)
void write (ULongWord address, int size, ULongWord data)
virtual void writeDirectlyBE (ULongWord address, int size, ULongWord data)
virtual void writeDirectlyLE (ULongWord address, int size, ULongWord data)
void write (ULongWord address, FloatWord data)
void write (ULongWord address, DoubleWord data)
void read (ULongWord address, int size, ULongWord &data)
void read (ULongWord address, DoubleWord &data)
void read (ULongWord address, FloatWord &data)
virtual void writeBE (ULongWord address, FloatWord data)
virtual void writeBE (ULongWord address, DoubleWord data)
virtual void writeLE (ULongWord address, FloatWord data)
virtual void writeLE (ULongWord address, DoubleWord data)
virtual void readBE (ULongWord address, int size, ULongWord &data)
virtual void readLE (ULongWord address, int size, ULongWord &data)
virtual void readBE (ULongWord address, FloatWord &data)
virtual void readBE (ULongWord address, DoubleWord &data)
virtual void readLE (ULongWord address, FloatWord &data)
virtual void readLE (ULongWord address, DoubleWord &data)
virtual ULongWord start ()
virtual ULongWord end ()
virtual ULongWord MAUSize ()
bool isLittleEndian ()
Private Member Functions
MemoryProxy (const MemoryProxy &)
Copying not allowed.
MemoryProxy & operator= (const MemoryProxy &)
Assignment not allowed.
Private Attributes
SimulatorFrontend & frontend_
Memory * memory_
Wrapped memory.
std::vector< MemoryAccess > reads_
List of initiated reads on the last cycle.
std::vector< MemoryAccess > writes_
List of initiated writes on the last cycle.
std::vector< MemoryAccess > newReads_
List of initiated reads.
std::vector< MemoryAccess > newWrites_
List of initiated writes.
Additional Inherited Members
Protected Member Functions inherited from Memory
void packBE (const Memory::MAUTable data, int size, ULongWord &value)
void unpackBE (const ULongWord &value, int size, Memory::MAUTable data)
void packLE (const Memory::MAUTable data, int size, ULongWord &value)
void unpackLE (const ULongWord &value, int size, Memory::MAUTable data)
Protected Attributes inherited from Memory
bool littleEndian_
Detailed Description
MemoryProxy is a memory access tracker for simulator.
MemoryProxy tracks calls to reads and writes. Memory accesses on the last clock cycle can be listed with readAccessCount(), readAccess(idx), writeAccessCount() and writeAccess(idx) functions. Memory access information is stored for only one cycle. Tracks only single memory accesses, not those made with the block methods.
Definition at line 53 of file MemoryProxy.hh.
Member Typedef Documentation
MemoryAccess
typedef std::pair<Word, int> MemoryProxy::MemoryAccess
Definition at line 56 of file MemoryProxy.hh.
Constructor & Destructor Documentation
MemoryProxy() [1/2]
MemoryProxy::MemoryProxy (SimulatorFrontend & frontend, Memory * memory)
The Constructor.
MemoryProxy takes ownership of the wrapped Memory instance.
Parameters
memory Tracked memory.
Definition at line 46 of file MemoryProxy.cc.
                                                                    :
    Memory(memory->start(), memory->end(), memory->MAUSize(),
           memory->isLittleEndian()),
    frontend_(frontend), memory_(memory) {
}
~MemoryProxy()
MemoryProxy::~MemoryProxy () virtual
The Destructor.
Deletes the tracked memory instance.
Definition at line 58 of file MemoryProxy.cc.
{
    delete memory_;
}
References memory_.
MemoryProxy() [2/2]
MemoryProxy::MemoryProxy (const MemoryProxy &) private
Copying not allowed.
Member Function Documentation
advanceClock()
void MemoryProxy::advanceClock () virtual
Resets the memory access information for the last cycle when wrapped memory clock is advanced.
Reimplemented from Memory.
Definition at line 98 of file MemoryProxy.cc.
{
    writes_ = newWrites_;
    reads_ = newReads_;
    newWrites_.clear();
    newReads_.clear();
    memory_->advanceClock();
}
References Memory::advanceClock(), memory_, newReads_, newWrites_, reads_, and writes_.
fillWithZeros()
virtual void MemoryProxy::fillWithZeros () inline virtual
Fills the whole memory with zeros.
This is needed due to some buggy simulated programs which expect uninitialized data to be zero. The default implementation is a slow for-loop which can be overridden with a faster one depending on the storage used.
Reimplemented from Memory.
Definition at line 72 of file MemoryProxy.hh.
{ memory_->fillWithZeros(); }
References Memory::fillWithZeros(), and memory_.
operator=()
MemoryProxy & MemoryProxy::operator= (const MemoryProxy &) private
Assignment not allowed.
read() [1/2]
Memory::MAU MemoryProxy::read (ULongWord address) override virtual
Tracks read calls.
Passes the call to the wrapped memory.
Implements Memory.
Definition at line 68 of file MemoryProxy.cc.
{
    frontend_.eventHandler().handleEvent(
        SimulationEventHandler::SE_MEMORY_ACCESS);
    newReads_.push_back(std::make_pair(address, 1));
    return memory_->read(address);
}
References SimulatorFrontend::eventHandler(), frontend_, Informer::handleEvent(), memory_, newReads_, Memory::read(), and SimulationEventHandler::SE_MEMORY_ACCESS.
read() [2/2]
virtual void MemoryProxy::read (ULongWord address, int size, ULongWord & data) inline virtual
Definition at line 69 of file MemoryProxy.hh.
        { memory_->write(address, size, data); }
References memory_, and Memory::write().
readAccess()
MemoryProxy::MemoryAccess MemoryProxy::readAccess (unsigned int idx) const
Returns information of the given memory read access.
Parameters
idx Index of the read access.
Exceptions
OutOfRange If the index is invalid.
Definition at line 133 of file MemoryProxy.cc.
{
    if (idx > reads_.size()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return reads_[idx];
}
References __func__, and reads_.
Referenced by ProximMemoryWindow::onSimulationStop().
readAccessCount()
unsigned int MemoryProxy::readAccessCount () const
Returns number of read accesses on the last cycle.
Definition at line 122 of file MemoryProxy.cc.
{
    return reads_.size();
}
References reads_.
Referenced by ProximMemoryWindow::onSimulationStop().
reset()
void MemoryProxy::reset () virtual
Resets all memory access information when the wrapped memory is reset.
Reimplemented from Memory.
Definition at line 110 of file MemoryProxy.cc.
                   {
    reads_.clear();
    writes_.clear();
    newReads_.clear();
    newWrites_.clear();
    memory_->reset();
}
References memory_, newReads_, newWrites_, reads_, Memory::reset(), and writes_.
write() [1/2]
virtual void MemoryProxy::write (ULongWord address, int size, ULongWord data) inline virtual
Definition at line 67 of file MemoryProxy.hh.
        { memory_->write(address, size, data); }
References memory_, and Memory::write().
write() [2/2]
void MemoryProxy::write (ULongWord address, MAU data) override virtual
Tracks write calls.
Passes the call to the wrapped memory.
Implements Memory.
Definition at line 83 of file MemoryProxy.cc.
{
    frontend_.eventHandler().handleEvent(
        SimulationEventHandler::SE_MEMORY_ACCESS);
    newWrites_.push_back(std::make_pair(address, 1));
    memory_->write(address, data);
}
References SimulatorFrontend::eventHandler(), frontend_, Informer::handleEvent(), memory_, newWrites_, SimulationEventHandler::SE_MEMORY_ACCESS, and Memory::write().
writeAccess()
MemoryProxy::MemoryAccess MemoryProxy::writeAccess (unsigned int idx) const
Returns information of the given memory write access.
Parameters
idx Index of the write access.
Exceptions
OutOfRange If the index is invalid.
Definition at line 157 of file MemoryProxy.cc.
{
    if (idx > writes_.size()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return writes_[idx];
}
References __func__, and writes_.
Referenced by ProximMemoryWindow::onSimulationStop().
writeAccessCount()
unsigned int MemoryProxy::writeAccessCount () const
Returns number of write accesses on the last cycle.
Definition at line 145 of file MemoryProxy.cc.
{
    return writes_.size();
}
References writes_.
Referenced by ProximMemoryWindow::onSimulationStop().
Member Data Documentation
frontend_
SimulatorFrontend& MemoryProxy::frontend_ private
Definition at line 82 of file MemoryProxy.hh.
Referenced by read(), and write().
memory_
Memory* MemoryProxy::memory_ private
Wrapped memory.
Definition at line 85 of file MemoryProxy.hh.
Referenced by advanceClock(), fillWithZeros(), read(), read(), reset(), write(), write(), and ~MemoryProxy().
newReads_
std::vector<MemoryAccess> MemoryProxy::newReads_ private
List of initiated reads.
Definition at line 96 of file MemoryProxy.hh.
Referenced by advanceClock(), read(), and reset().
newWrites_
std::vector<MemoryAccess> MemoryProxy::newWrites_ private
List of initiated writes.
Definition at line 98 of file MemoryProxy.hh.
Referenced by advanceClock(), reset(), and write().
reads_
std::vector<MemoryAccess> MemoryProxy::reads_ private
List of initiated reads on the last cycle.
Definition at line 92 of file MemoryProxy.hh.
Referenced by advanceClock(), readAccess(), readAccessCount(), and reset().
writes_
std::vector<MemoryAccess> MemoryProxy::writes_ private
List of initiated writes on the last cycle.
Definition at line 94 of file MemoryProxy.hh.
Referenced by advanceClock(), reset(), writeAccess(), and writeAccessCount().
The documentation for this class was generated from the following files:
MemoryProxy.hh
MemoryProxy.cc