OpenASIP: AddIUFromHDBDialog Class Reference
AddIUFromHDBDialog Class Reference
#include <AddIUFromHDBDialog.hh>
Public Member Functions
AddIUFromHDBDialog (wxWindow *parent, Model *model)
virtual ~AddIUFromHDBDialog ()
Private Types
enum { ID_LIST = 10000 , ID_ADD , ID_CLOSE , ID_LINE }
Private Member Functions
virtual bool TransferDataToWindow ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onListSelectionChange (wxListEvent &event)
void onAdd (wxCommandEvent &event)
void onClose (wxCommandEvent &event)
bool loadHDB (const std::string &path)
void onColumnClick (wxListEvent &event)
void setColumnImage (int col, int image)
Private Attributes
Model * model_
Model of the current adf file.
wxListCtrl * list_
Immediate slot list widget.
std::map< int, HDB::RFArchitecture * > iuArchitectures_
Map of iu architectures displayed in the dialog list.
int sortColumn_
bool sortASC_
Static Private Attributes
static const int DEFAULT_SIZE = 1
Default size for the IU, if the size is parameterized in the HDB.
static const int DEFAULT_WIDTH = 32
Default width for the IU, if the size is parameterized in the HDB.
static const TTAMachine::Machine::Extension DEFAULT_EXTENSION_MODE
Default extension mode for the immediate unit.
static const wxString HDB_FILE_FILTER = _T("*.hdb")
File filter for HDB files.
Detailed Description
Dialog for adding immediate unit architectures directly from HDB to the current machine.
Definition at line 61 of file AddIUFromHDBDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LIST
ID_ADD
ID_CLOSE
ID_LINE
Definition at line 86 of file AddIUFromHDBDialog.hh.
         {
        ID_LIST = 10000,
        ID_ADD,
        ID_CLOSE,
        ID_LINE
    };
Constructor & Destructor Documentation
AddIUFromHDBDialog()
AddIUFromHDBDialog::AddIUFromHDBDialog (wxWindow * parent, Model * model)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Parent Machine of the immediate slots.
Definition at line 133 of file AddIUFromHDBDialog.cc.
                  :
    wxDialog(
        parent, -1, _T("HDB Immediate Units"),
        wxDefaultPosition, wxDefaultSize,
        wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    model_(model), sortColumn_(0), sortASC_(true) {
    createContents(this, true, true);
    SetSize(400, 300);
    list_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    list_->InsertColumn(0, _T("Width"), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE);
    list_->InsertColumn(1, _T("Size"), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE);
    list_->InsertColumn(2, _T("Read ports"), wxLIST_FORMAT_LEFT, 100);
    //list_->InsertColumn(5, _T("Max Reads"));
    //list_->InsertColumn(6, _T("Max RW"));
    list_->InsertColumn(3, _T("Latency"), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE);
    list_->InsertColumn(4, _T("ID"), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE);
    list_->InsertColumn(5, _T("HDB"), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE);
    string iconPath =
        Environment::iconDirPath() + FileSystem::DIRECTORY_SEPARATOR;
    wxImageList* imageList = new wxImageList(13, 17);
    imageList->Add(wxIcon(
        WxConversion::toWxString(iconPath + ProDeConstants::ICON_SORT_DESC)));
    imageList->Add(wxIcon(
        WxConversion::toWxString(iconPath + ProDeConstants::ICON_SORT_ASC)));
    list_->SetImageList(imageList, wxIMAGE_LIST_SMALL);
    // Disable conditional buttons.
    FindWindow(ID_ADD)->Disable();
}
References createContents(), FileSystem::DIRECTORY_SEPARATOR, ProDeConstants::ICON_SORT_ASC, ProDeConstants::ICON_SORT_DESC, Environment::iconDirPath(), ID_ADD, ID_LIST, list_, and WxConversion::toWxString().
~AddIUFromHDBDialog()
AddIUFromHDBDialog::~AddIUFromHDBDialog () virtual
The Destructor.
Definition at line 174 of file AddIUFromHDBDialog.cc.
{
    MapTools::deleteAllValues(iuArchitectures_);
}
References MapTools::deleteAllValues(), and iuArchitectures_.
Member Function Documentation
createContents()
wxSizer * AddIUFromHDBDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Returns
Top level sizer of the dialog contents.
Definition at line 402 of file AddIUFromHDBDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_LIST, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxButton *item2 = new wxButton( parent, ID_ADD, wxT("&Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxStaticLine *item3 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item3, 0, wxGROW|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_CLOSE, wxT("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer) {
        parent->SetSizer( item0 );
        if (call_fit) {
            item0->SetSizeHints( parent );
        }
    }
    return item0;
}
References ID_ADD, ID_CLOSE, ID_LINE, and ID_LIST.
Referenced by AddIUFromHDBDialog().
loadHDB()
bool AddIUFromHDBDialog::loadHDB (const std::string & path) private
Loads immediate units from a HDB to the dialog list.
Parameters
path Full path to the HDB file to load.
Returns
True, if the HDB was succesfully loaded.
Definition at line 241 of file AddIUFromHDBDialog.cc.
{
    HDBManager* manager = NULL;
    try {
        manager = &HDBRegistry::instance().hdb(path);
    } catch (Exception& e) {
        wxString message = _T("Unable to open HDB '");
        message.Append(WxConversion::toWxString(path));
        message.Append(_T("':'"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        WarningDialog dialog(this, message);
        dialog.ShowModal();
        return false;
    }
    const std::set<RowID> rfArchIDs = manager->rfArchitectureIDs();
    std::set<RowID>::iterator iter = rfArchIDs.begin();
    // Read properties of all immediate units in the HDB and append
    // data in the list widget.
    for (; iter != rfArchIDs.end(); iter++) {
        RFArchitecture* arch = manager->rfArchitectureByID(*iter);
        if (arch->writePortCount() != 1 ||
            arch->bidirPortCount() != 0) {
            // Register file architecture must contain one read port and
            // no bidirectional ports or it's not listed as an immediate
            // unit architecture.
            continue;
        }
        iuArchitectures_.insert(
            std::pair<int, RFArchitecture*>(list_->GetItemCount(), arch));
        ListItemData* lid = new ListItemData;
        if (arch->hasParameterizedWidth()) {
            list_->InsertItem(0, _T("param"));
            lid->width = 0;
        } else {
            list_->InsertItem(0, WxConversion::toWxString(arch->width()));
            lid->width = arch->width();
        }
        if (arch->hasParameterizedSize()) {
            list_->SetItem(0, 1, _T("param"));
            lid->size = 0;
        } else {
            list_->SetItem(0, 1, WxConversion::toWxString(arch->size()));
            lid->size = arch->size();
        }
        list_->SetItem(0, 2, WxConversion::toWxString(arch->readPortCount()));
        lid->readPorts = arch->readPortCount();
        list_->SetItem(0, 3, WxConversion::toWxString(arch->latency()));
        lid->latency = arch->latency();
        list_->SetItem(0, 4, WxConversion::toWxString(*iter));
        lid->hdbId = *iter;
        list_->SetItem(0, 5, WxConversion::toWxString(path));
        lid->path = WxConversion::toWxString(path);
        lid->id = list_->GetItemCount() - 1;
        list_->SetItemData(0, (long)lid);
    }
    // default sorting column is "Width"
    list_->SortItems(IUListCompareASC, 0);
    setColumnImage(0, sortASC_);
    return true;
}
References HDB::RFArchitecture::bidirPortCount(), Exception::errorMessage(), HDB::RFArchitecture::hasParameterizedSize(), HDB::RFArchitecture::hasParameterizedWidth(), HDB::HDBRegistry::hdb(), ListItemData::hdbId, ListItemData::id, HDB::HDBRegistry::instance(), iuArchitectures_, IUListCompareASC(), HDB::RFArchitecture::latency(), ListItemData::latency, list_, ListItemData::path, HDB::RFArchitecture::readPortCount(), ListItemData::readPorts, HDB::HDBManager::rfArchitectureByID(), HDB::HDBManager::rfArchitectureIDs(), setColumnImage(), HDB::RFArchitecture::size(), ListItemData::size, sortASC_, WxConversion::toWxString(), HDB::RFArchitecture::width(), ListItemData::width, and HDB::RFArchitecture::writePortCount().
Referenced by TransferDataToWindow().
onAdd()
void AddIUFromHDBDialog::onAdd (wxCommandEvent & event) private
Adds a new register file to the machine when "Add" button is pressed.
Definition at line 330 of file AddIUFromHDBDialog.cc.
{
    long item = -1;
    item = list_->GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if ( item == -1 ) return;
    ListItemData* lid = (ListItemData*)list_->GetItemData(item);
    int id = lid->id;
    const RFArchitecture* arch =
        MapTools::valueForKey<RFArchitecture*>(iuArchitectures_, id);
    Machine* machine = model_->getMachine();
    // Set size and width.
    int size = DEFAULT_SIZE;
    int width = DEFAULT_WIDTH;
    if (!arch->hasParameterizedWidth()) {
        size = arch->width();
    }
    if (!arch->hasParameterizedSize()) {
        size = arch->size();
    }
    // Generate name for the new immediate unit.
    string name =
        "IU_" + Conversion::toString(size) + "x" + Conversion::toString(width);
    string iuName = name;
    int idx = 1;
    while (machine->immediateUnitNavigator().hasItem(iuName)) {
        iuName = name + "_" + Conversion::toString(idx);
        idx++;
    }
    int maxReads = arch->maxReads();
    int guardLatency = arch->guardLatency();
    // Create an immediate unit object and attach it to the machine.
    ImmediateUnit* iu = new ImmediateUnit(
        iuName, size, width, maxReads, guardLatency, DEFAULT_EXTENSION_MODE);
    for (int i = 0; i < arch->readPortCount(); i++) {
        string name = "r" + Conversion::toString(i);
        new RFPort(name, *iu);
    }
    model_->pushToStack();
    machine->addImmediateUnit(*iu);
    model_->notifyObservers();
}
References TTAMachine::Machine::addImmediateUnit(), DEFAULT_EXTENSION_MODE, DEFAULT_SIZE, DEFAULT_WIDTH, Model::getMachine(), HDB::RFArchitecture::guardLatency(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), HDB::RFArchitecture::hasParameterizedSize(), HDB::RFArchitecture::hasParameterizedWidth(), ListItemData::id, TTAMachine::Machine::immediateUnitNavigator(), iuArchitectures_, MapTools::keyForValue(), list_, machine, HDB::RFArchitecture::maxReads(), model_, Model::notifyObservers(), Model::pushToStack(), HDB::RFArchitecture::readPortCount(), HDB::RFArchitecture::size(), Conversion::toString(), and HDB::RFArchitecture::width().
onClose()
void AddIUFromHDBDialog::onClose (wxCommandEvent & event) private
Closes the dialog when the close button is pressed.
Definition at line 388 of file AddIUFromHDBDialog.cc.
{
    Close();
}
onColumnClick()
void AddIUFromHDBDialog::onColumnClick (wxListEvent & event) private
Sorts HDB IU list according to clicked column.
Definition at line 436 of file AddIUFromHDBDialog.cc.
{
    int clickedColumn = event.GetColumn();
    if (clickedColumn == sortColumn_) {
        sortASC_ = !sortASC_;
    } else {
        sortASC_ = true;
        setColumnImage(sortColumn_, -1);    // removes arrow from old column
        sortColumn_ = clickedColumn;
    }
    setColumnImage(clickedColumn, sortASC_);
    if (sortASC_) {
        list_->SortItems(IUListCompareASC, clickedColumn);
    } else {
        list_->SortItems(IUListCompareDESC, clickedColumn);
    }
}
References IUListCompareASC(), IUListCompareDESC(), list_, setColumnImage(), sortASC_, and sortColumn_.
onListSelectionChange()
void AddIUFromHDBDialog::onListSelectionChange (wxListEvent & event) private
Enables and disables the delete button according to slot list selection.
Definition at line 317 of file AddIUFromHDBDialog.cc.
{
    if (list_->GetSelectedItemCount() == 1) {
        FindWindow(ID_ADD)->Enable();
    } else {
        FindWindow(ID_ADD)->Disable();
    }
}
References ID_ADD, and list_.
setColumnImage()
void AddIUFromHDBDialog::setColumnImage (int col, int image) private
Sets sorting arrow image on selected column
Parameters
col Column index to set the image
image Image index in wxImageList
Definition at line 465 of file AddIUFromHDBDialog.cc.
{
    wxListItem item;
    item.SetMask(wxLIST_MASK_IMAGE);
    item.SetImage(image);
    list_->SetColumn(col, item);
}
References list_.
Referenced by loadHDB(), and onColumnClick().
TransferDataToWindow()
bool AddIUFromHDBDialog::TransferDataToWindow () private virtual
Transfers data from the HDBs to the dialog list.
Returns
True, if the the data transfer was succesful.
Definition at line 185 of file AddIUFromHDBDialog.cc.
{
    MapTools::deleteAllValues(iuArchitectures_);
    list_->DeleteAllItems();
    const std::vector<string> hdbPaths = Environment::hdbPaths();
    std::vector<string>::const_iterator hdbIter = hdbPaths.begin();
    wxString paths;
    bool hdbsFound = false;
    // Read all hdb files found in the search directories.
    for(; hdbIter != hdbPaths.end(); hdbIter++) {
        wxString file;
        wxString hdbPath = WxConversion::toWxString(*hdbIter);
        paths.Append(hdbPath);
        paths.Append(_T("\n"));
        wxDir dir;
        if (dir.Exists(hdbPath) &&
            dir.Open(hdbPath) &&
            dir.GetFirst(&file, HDB_FILE_FILTER)) {
            do {
                string path = *hdbIter + FileSystem::DIRECTORY_SEPARATOR +
                    WxConversion::toString(file);
                if (loadHDB(path)) {
                    hdbsFound = true;
                }
            } while (dir.GetNext(&file));
        }
    }
    if (!hdbsFound) {
        wxString message = _T("No HDBs found in HDB search paths:\n");
        message.Append(paths);
        WarningDialog dialog(this, message);
        dialog.ShowModal();
    }
    list_->SetColumnWidth(5, wxLIST_AUTOSIZE);
    return wxDialog::TransferDataToWindow();
}
References MapTools::deleteAllValues(), FileSystem::DIRECTORY_SEPARATOR, HDB_FILE_FILTER, Environment::hdbPaths(), iuArchitectures_, list_, loadHDB(), WxConversion::toString(), and WxConversion::toWxString().
Member Data Documentation
DEFAULT_EXTENSION_MODE
const Machine::Extension AddIUFromHDBDialog::DEFAULT_EXTENSION_MODE static private
Initial value:
=
    Machine::ZERO
Default extension mode for the immediate unit.
Definition at line 98 of file AddIUFromHDBDialog.hh.
Referenced by onAdd().
DEFAULT_SIZE
const int AddIUFromHDBDialog::DEFAULT_SIZE = 1 static private
Default size for the IU, if the size is parameterized in the HDB.
Definition at line 94 of file AddIUFromHDBDialog.hh.
Referenced by onAdd().
DEFAULT_WIDTH
const int AddIUFromHDBDialog::DEFAULT_WIDTH = 32 static private
Default width for the IU, if the size is parameterized in the HDB.
Definition at line 96 of file AddIUFromHDBDialog.hh.
Referenced by onAdd().
HDB_FILE_FILTER
const wxString AddIUFromHDBDialog::HDB_FILE_FILTER = _T("*.hdb") static private
File filter for HDB files.
Definition at line 100 of file AddIUFromHDBDialog.hh.
Referenced by TransferDataToWindow().
iuArchitectures_
std::map<int, HDB::RFArchitecture*> AddIUFromHDBDialog::iuArchitectures_ private
Map of iu architectures displayed in the dialog list.
Definition at line 81 of file AddIUFromHDBDialog.hh.
Referenced by loadHDB(), onAdd(), TransferDataToWindow(), and ~AddIUFromHDBDialog().
list_
wxListCtrl* AddIUFromHDBDialog::list_ private
Immediate slot list widget.
Definition at line 79 of file AddIUFromHDBDialog.hh.
Referenced by AddIUFromHDBDialog(), loadHDB(), onAdd(), onColumnClick(), onListSelectionChange(), setColumnImage(), and TransferDataToWindow().
model_
Model* AddIUFromHDBDialog::model_ private
Model of the current adf file.
Definition at line 77 of file AddIUFromHDBDialog.hh.
Referenced by onAdd().
sortASC_
bool AddIUFromHDBDialog::sortASC_ private
Definition at line 84 of file AddIUFromHDBDialog.hh.
Referenced by loadHDB(), and onColumnClick().
sortColumn_
int AddIUFromHDBDialog::sortColumn_ private
Definition at line 83 of file AddIUFromHDBDialog.hh.
Referenced by onColumnClick().
The documentation for this class was generated from the following files:
AddIUFromHDBDialog.hh
AddIUFromHDBDialog.cc