OpenASIP: BFEarlyGuardBypass Class Reference
BFEarlyGuardBypass Class Reference
#include <BFEarlyGuardBypass.hh>
Public Member Functions
BFEarlyGuardBypass (BF2Scheduler &sched, MoveNode &mn)
void undoOnlyMe () override
bool operator() () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & mn_
MoveNode * src_
const TTAMachine::Guard * originalGuard_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 7 of file BFEarlyGuardBypass.hh.
Constructor & Destructor Documentation
BFEarlyGuardBypass()
BFEarlyGuardBypass::BFEarlyGuardBypass (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 10 of file BFEarlyGuardBypass.hh.
                                                          :
        BFOptimization(sched), mn_(mn) {}
Member Function Documentation
operator()()
bool BFEarlyGuardBypass::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 12 of file BFEarlyGuardBypass.cc.
{
    src_ = ddg().onlyRegisterRawSource(mn_, 1);
    if (!src_) {
        return false;
    }
    ProgramOperationPtr po = src_->sourceOperationPtr();
    const Operation& op = po->operation();
    auto dPorts = MachineConnectivityCheck::findPossibleDestinationPorts(
        targetMachine(), mn_);
    // TODO: this is not deterministic as this uses pointer as the key!
    std::set<const TTAMachine::Bus*> buses;
    for (auto p: dPorts) {
        MachineConnectivityCheck::appendConnectedSourceBuses(*p, buses);
    }
    for (auto bus: buses) {
        for (int i = 0; i < bus->guardCount(); i++) {
            const TTAMachine::Guard* guard = bus->guard(i);
            const TTAMachine::PortGuard* pg =
                dynamic_cast<const TTAMachine::PortGuard*>(guard);
            if (pg == NULL || pg->isInverted() != mn_.move().guard().isInverted()) {
                continue;
            }
            const TTAMachine::FUPort* port = pg->port();
            const TTAMachine::FunctionUnit* gfu = port->parentUnit();
            if (gfu->hasOperation(op.name()) &&
                po->outputIndexFromGuard(*pg) ==
                src_->move().source().operationIndex()) {
                if (!po->isLegalFU(*gfu)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    std::cerr << "\t\t\tFU: " << gfu->name() << " not allowed for operation: " << po->toString() << std::endl;
#endif
                    continue;
                }
                originalGuard_ = &mn_.move().guard().guard();
                // TODO: backup old guard.
                mn_.move().setGuard(new TTAProgram::MoveGuard(*guard));
                ddg().guardConverted(*src_, mn_);
                return true;
            }
        }
    }
    return false;
}
References MachineConnectivityCheck::appendConnectedSourceBuses(), BFOptimization::ddg(), MachineConnectivityCheck::findPossibleDestinationPorts(), TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), DataDependenceGraph::guardConverted(), TTAMachine::FunctionUnit::hasOperation(), TTAMachine::Guard::isInverted(), TTAProgram::MoveGuard::isInverted(), mn_, MoveNode::move(), TTAMachine::Component::name(), Operation::name(), DataDependenceGraph::onlyRegisterRawSource(), TTAProgram::Terminal::operationIndex(), originalGuard_, TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), TTAProgram::Move::setGuard(), TTAProgram::Move::source(), MoveNode::sourceOperationPtr(), src_, and BFOptimization::targetMachine().
undoOnlyMe()
void BFEarlyGuardBypass::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 64 of file BFEarlyGuardBypass.cc.
{
    ddg().guardRestored(*src_, mn_);
    mn_.move().setGuard(new TTAProgram::MoveGuard(*originalGuard_));
}
References BFOptimization::ddg(), DataDependenceGraph::guardRestored(), mn_, MoveNode::move(), originalGuard_, TTAProgram::Move::setGuard(), and src_.
Member Data Documentation
mn_
MoveNode& BFEarlyGuardBypass::mn_ private
Definition at line 16 of file BFEarlyGuardBypass.hh.
Referenced by operator()(), and undoOnlyMe().
originalGuard_
const TTAMachine::Guard* BFEarlyGuardBypass::originalGuard_ private
Definition at line 18 of file BFEarlyGuardBypass.hh.
Referenced by operator()(), and undoOnlyMe().
src_
MoveNode* BFEarlyGuardBypass::src_ private
Definition at line 17 of file BFEarlyGuardBypass.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFEarlyGuardBypass.hh
BFEarlyGuardBypass.cc