OpenASIP: EditBusOrderCmd Class Reference
EditBusOrderCmd Class Reference
#include <EditBusOrderCmd.hh>
Public Member Functions
EditBusOrderCmd ()
virtual ~EditBusOrderCmd ()
virtual bool Do ()
virtual int id () const
virtual EditBusOrderCmd * create () const
virtual bool isEnabled ()
virtual std::string shortName () const
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for editing order of transport buses in a machine.
Definition at line 41 of file EditBusOrderCmd.hh.
Constructor & Destructor Documentation
EditBusOrderCmd()
EditBusOrderCmd::EditBusOrderCmd ()
The Constructor.
Definition at line 50 of file EditBusOrderCmd.cc.
                                :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_BUS_ORDER) {
}
Referenced by create().
~EditBusOrderCmd()
EditBusOrderCmd::~EditBusOrderCmd () virtual
The Destructor.
Definition at line 58 of file EditBusOrderCmd.cc.
{}
Member Function Documentation
create()
EditBusOrderCmd * EditBusOrderCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 103 of file EditBusOrderCmd.cc.
{
    return new EditBusOrderCmd();
}
References EditBusOrderCmd().
Do()
bool EditBusOrderCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 67 of file EditBusOrderCmd.cc.
                    {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    ProDeBusOrderDialog dialog(parentWindow(), *model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, address spaces are not modified.
    model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
id()
int EditBusOrderCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 94 of file EditBusOrderCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_BUS_ORDER;
}
References ProDeConstants::COMMAND_EDIT_BUS_ORDER.
isEnabled()
bool EditBusOrderCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 125 of file EditBusOrderCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string EditBusOrderCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 112 of file EditBusOrderCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_ADDRESS_SPACES;
}
References ProDeConstants::CMD_SNAME_EDIT_ADDRESS_SPACES.
The documentation for this class was generated from the following files:
EditBusOrderCmd.hh
EditBusOrderCmd.cc