OpenASIP: ImmInfo Class Reference
ImmInfo Class Reference
#include <ImmInfo.hh>
Public Member Functions
ImmInfo ()=default
virtual ~ImmInfo ()=default
size_t count (const ImmInfoKey &key) const
size_t count (const Operation &operation, const Operand &operand) const
size_t count (const Operation &operation, int inputOperandId) const
const ImmInfoValue & widestImmediate (const ImmInfoKey &key) const
const ImmInfoValue & widestImmediate (const Operation &operation, const Operand &operand) const
const ImmInfoValue & widestImmediate (const Operation &operation, int inputOperandId) const
const ImmInfoValue & narrowestImmediate (const ImmInfoKey &key) const
std::pair< int64_t, int64_t > immediateValueBounds (const ImmInfoKey &key, int destWidth) const
std::pair< int64_t, int64_t > immediateValueBounds (const Operation &operation, const Operand &operand, int destWidth) const
std::pair< int64_t, int64_t > immediateValueBounds (const Operation &operation, int inputOperandId, int destWidth) const
bool canTakeImmediate (const Operation &operation, int inputOperandId, int64_t value, int destWidth)
bool canTakeImmediateByWidth (const Operation &operation, int inputOperandId, int bitWidth)
Static Public Member Functions
static ImmInfoKey key (const Operation &operation, int inputOperandId)
static ImmInfoKey key (const Operation &operation, const Operand &operand)
static int registerImmediateLoadWidth (const TTAMachine::RegisterFile &targetRF, bool allowSignExtension=false)
Detailed Description
Definition at line 82 of file ImmInfo.hh.
Constructor & Destructor Documentation
ImmInfo()
ImmInfo::ImmInfo () default
~ImmInfo()
virtual ImmInfo::~ImmInfo () virtual default
Member Function Documentation
canTakeImmediate()
bool ImmInfo::canTakeImmediate (const Operation & operation, int inputOperandId, int64_t value, int destWidth)
Definition at line 252 of file ImmInfo.cc.
           {
    auto unsignedReqBits = MathTools::requiredBits(value);
    auto signedReqBits = MathTools::requiredBitsSigned(value);
    auto theKey = key(operation, inputOperandId);
    const_iterator it_begin = lower_bound(theKey);
    const_iterator it_end = upper_bound(theKey);
    const_iterator it;
    for (it = it_begin; it != it_end; it++) {
        const ImmInfoValue& imm = it->second;
        if ((imm.signExtending() && signedReqBits <= imm.width()) ||
            (unsignedReqBits <= imm.width())) {
            return true;
        }
    }
    return false;
}
References key(), MathTools::requiredBits(), MathTools::requiredBitsSigned(), ImmInfoValue::signExtending(), and ImmInfoValue::width().
Referenced by TDGen::getLLVMPatternWithConstants().
canTakeImmediateByWidth()
bool ImmInfo::canTakeImmediateByWidth (const Operation & operation, int inputOperandId, int bitWidth)
Definition at line 275 of file ImmInfo.cc.
                  {
    auto theKey = key(operation, inputOperandId);
    const_iterator it_begin = lower_bound(theKey);
    const_iterator it_end = upper_bound(theKey);
    const_iterator it;
    for (it = it_begin; it != it_end; it++) {
        const ImmInfoValue& info = it->second;
        if (bitWidth <= info.width()) return true;
    }
    return false;
}
References key(), and ImmInfoValue::width().
Referenced by TDGen::getLLVMPatternWithConstants().
count() [1/3]
size_t ImmInfo::count (const ImmInfoKey & key) const inline
Definition at line 87 of file ImmInfo.hh.
{
        return std::multimap<ImmInfoKey, ImmInfoValue>::count(key);
    }
References key().
Referenced by TDGen::areImmediateOperandsLegal(), count(), OperationDAGSelector::findDags(), and TDGen::writeIntegerImmediateDefs().
count() [2/3]
size_t ImmInfo::count (const Operation & operation, const Operand & operand) const
Returns the entry count for operation, operand pair (key).
Definition at line 70 of file ImmInfo.cc.
{
    return std::multimap<ImmInfoKey, ImmInfoValue>::count(
        key(operation, operand));
}
References key().
count() [3/3]
size_t ImmInfo::count (const Operation & operation, int inputOperandId) const
Returns the entry count for operation, operand pair (key).
Definition at line 80 of file ImmInfo.cc.
{
    return count(operation, operation.operand(inputOperandId));
}
References count(), and Operation::operand().
immediateValueBounds() [1/3]
std::pair< int64_t, int64_t > ImmInfo::immediateValueBounds (const ImmInfoKey & key, int destWidth) const
Returns smallest and largest number that can be transported to operation operand.
The bounds are merged from multiple immediate sources. For example, if immediates can be transported from two different sources, where the one is 4 bits zero extending and the another is 3 bits sign extending, the resulting bound is [-4, 15].
if destination bit width is specified, then the bounds are ...TODO
Parameters
destWidth The destination width, where the immediates are transported to. By default it is unspecified/unlimited.
Returns
std::pair, where the first is smallest value and second is largest. If no immediate can be transported, (0, 0) is returned.
Definition at line 219 of file ImmInfo.cc.
{
    std::pair<int64_t, int64_t> result{ 0, 0 };
    const_iterator it_begin = lower_bound(key);
    const_iterator it_end = upper_bound(key);
    const_iterator it;
    for (it = it_begin; it != it_end; it++) {
        if (destWidth > 0) {
            if (it->second.width() >= destWidth) {
                return { (-(1ll << (destWidth-1))), ((1ll << destWidth)-1) };
            }
        }
        int64_t currLowerBound = 0;
        int64_t currUpperBound = 0;
        if (it->second.signExtending()) {
            currLowerBound = -(1ll << (it->second.width()-1));
            currUpperBound = (1ll << (it->second.width()-1))-1;
        } else {
            currUpperBound = (1ll << (it->second.width()))-1;
        }
        result.first = std::min(result.first, currLowerBound);
        result.second = std::max(result.second, currUpperBound);
    }
    return result;
}
References key().
Referenced by TDGen::createConstantMaterializationPatterns(), immediateValueBounds(), immediateValueBounds(), and TDGen::writeIntegerImmediateDefs().
immediateValueBounds() [2/3]
std::pair< int64_t, int64_t > ImmInfo::immediateValueBounds (const Operation & operation, const Operand & operand, int destWidth) const
Same as immediateValueBounds(const ImmInfoKey& key).
Definition at line 296 of file ImmInfo.cc.
{
    return immediateValueBounds(key(operation, operand), destWidth);
}
References immediateValueBounds(), and key().
immediateValueBounds() [3/3]
std::pair< int64_t, int64_t > ImmInfo::immediateValueBounds (const Operation & operation, int inputOperandId, int destWidth) const
Same as immediateValueBounds(const ImmInfoKey& key).
Definition at line 309 of file ImmInfo.cc.
{
    return immediateValueBounds(
        operation, operation.operand(inputOperandId), destWidth);
}
References immediateValueBounds(), and Operation::operand().
key() [1/2]
ImmInfoKey ImmInfo::key (const Operation & operation, const Operand & operand) static
Definition at line 61 of file ImmInfo.cc.
{
    return std::make_pair(operation.name().upper(), operand.index());
}
References Operand::index(), Operation::name(), and TCEString::upper().
key() [2/2]
ImmInfoKey ImmInfo::key (const Operation & operation, int inputOperandId) static
Returns key for ImmInfo data structure.
Definition at line 57 of file ImmInfo.cc.
{
    return std::make_pair(operation.name().upper(), inputOperandId);
}
References Operation::name(), and TCEString::upper().
Referenced by canTakeImmediate(), canTakeImmediateByWidth(), count(), count(), TDGen::dagNodeToString(), TDGen::immediateOperandNameForEmulatedOperation(), immediateValueBounds(), immediateValueBounds(), narrowestImmediate(), TDGen::patInputs(), widestImmediate(), widestImmediate(), and TDGen::writeIntegerImmediateDefs().
narrowestImmediate()
const ImmInfoValue & ImmInfo::narrowestImmediate (const ImmInfoKey & key) const
returns narrowest (non-zero width) immediate bit width by the key.
Definition at line 140 of file ImmInfo.cc.
{
    if (std::multimap<ImmInfoKey, ImmInfoValue>::count(key)) {
        const_iterator it;
        const_iterator it_largest = lower_bound(key);
        const_iterator it_begin = it_largest;
        it_begin++;
        const_iterator it_end = upper_bound(key);
        for (it = it_begin; it != it_end; it++) {
            if (*it < *it_largest) {
                it_largest = it;
            }
        }
        assert(it_largest != it_end);
        return it_largest->second;
    } else {
        THROW_EXCEPTION(InstanceNotFound,
            "No immediate info found for the key.");
    }
}
References assert, key(), and THROW_EXCEPTION.
registerImmediateLoadWidth()
int ImmInfo::registerImmediateLoadWidth (const TTAMachine::RegisterFile & targetRF, bool allowSignExtension = false) static
Returns maximum immediate in bit width which can be transported to the RF.
Parameters
targetRF The target register file.
allowSignExtension If representation of the transported immediate should not change set it to false (default).
Definition at line 326 of file ImmInfo.cc.
{
    using namespace TTAMachine;
    using MCC = MachineConnectivityCheck;
    int result = 0;
    assert(targetRF.machine());
    const Machine& mach = *targetRF.machine();
    for (const Bus* bus : mach.busNavigator()) {
        if (MCC::busConnectedToRF(*bus, targetRF)) {
            int immWidth = bus->immediateWidth();
            if (!allowSignExtension && bus->signExtends()) {
                immWidth -= 1;
            }
            result = std::max(result, immWidth);
        }
    }
    for (auto* iu : mach.immediateUnitNavigator()) {
        for (auto* it : mach.instructionTemplateNavigator()) {
            int supportedWidth = it->supportedWidth(*iu);
            if (!allowSignExtension && iu->signExtends()) {
                supportedWidth -= 1;
            }
            result = std::max(result, supportedWidth);
        }
    }
    return result;
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), and TTAMachine::Component::machine().
Referenced by llvm::TCETargetMachine::calculateSupportedImmediates().
widestImmediate() [1/3]
const ImmInfoValue & ImmInfo::widestImmediate (const ImmInfoKey & key) const
Returns the entry count by the key.
Definition at line 89 of file ImmInfo.cc.
{
    if (std::multimap<ImmInfoKey, ImmInfoValue>::count(key)) {
        const_iterator it;
        const_iterator it_largest = this->lower_bound(key);
        const_iterator it_begin = it_largest;
        it_begin++;
        const_iterator it_end = this->upper_bound(key);
        for (it = it_begin; it != it_end; it++) {
            if (*it > *it_largest) {
                it_largest = it;
            }
        }
        assert(it_largest != it_end);
        return it_largest->second;
    } else {
        THROW_EXCEPTION(InstanceNotFound, "No immediate info for key found.");
    }
}
References assert, key(), and THROW_EXCEPTION.
Referenced by widestImmediate(), and widestImmediate().
widestImmediate() [2/3]
const ImmInfoValue & ImmInfo::widestImmediate (const Operation & operation, const Operand & operand) const
returns widest immediate bit width by the key.
Parameters
operation The operation as the part of the key.
inputOperandId The input operand of the operation as the of the key.
Definition at line 116 of file ImmInfo.cc.
{
    return widestImmediate(key(operation, operand));
}
References key(), and widestImmediate().
widestImmediate() [3/3]
const ImmInfoValue & ImmInfo::widestImmediate (const Operation & operation, int inputOperandId) const
returns widest immediate bit width by the key.
Parameters
operation The operation as the part of the key.
inputOperandId The input operand id of the operation as the of the key.
Definition at line 130 of file ImmInfo.cc.
{
    return widestImmediate(operation, operation.operand(inputOperandId));
}
References Operation::operand(), and widestImmediate().
The documentation for this class was generated from the following files:
ImmInfo.hh
ImmInfo.cc