OpenASIP: HDB::FUEntry Class Reference
HDB::FUEntry Class Reference
#include <FUEntry.hh>
Public Member Functions
FUEntry ()
virtual ~FUEntry ()
virtual bool hasImplementation () const
FUImplementation & implementation () const
void setImplementation (FUImplementation *implementation)
virtual bool hasArchitecture () const
FUArchitecture & architecture () const
void setArchitecture (FUArchitecture *architecture)
Public Member Functions inherited from HDB::HDBEntry
virtual ~HDBEntry ()
bool hasID () const
void setID (RowID id)
RowID id () const
bool hasCostFunction () const
CostFunctionPlugin & costFunction () const
void setCostFunction (CostFunctionPlugin *costFunction)
std::string hdbFile () const
void setHDBFile (const std::string &file)
Private Attributes
FUArchitecture * architecture_
Architecture of the entry.
FUImplementation * implementation_
Implementation of the entry.
Additional Inherited Members
Protected Member Functions inherited from HDB::HDBEntry
HDBEntry ()
Detailed Description
Represents an FU entry in HDB.
Definition at line 49 of file FUEntry.hh.
Constructor & Destructor Documentation
FUEntry()
HDB::FUEntry::FUEntry ()
The constructor.
Creates an FU entry without ID, implementation, architecture and cost function.
Definition at line 50 of file FUEntry.cc.
                 :
    HDBEntry(), architecture_(NULL), implementation_(NULL) {
}
~FUEntry()
HDB::FUEntry::~FUEntry () virtual
The destructor.
Definition at line 58 of file FUEntry.cc.
                  {
    if (hasArchitecture()) {
        delete architecture_;
    }
    if (hasImplementation()) {
        delete implementation_;
    }
}
References architecture_, hasArchitecture(), hasImplementation(), and implementation_.
Member Function Documentation
architecture()
FUArchitecture & HDB::FUEntry::architecture () const
Returns the architecture of the entry.
Returns
Architecture of the entry.
Exceptions
NotAvailable If the entry doesn't have architecture.
Definition at line 129 of file FUEntry.cc.
{
    if (!hasArchitecture()) {
        const string procName = "FUEntry::architecture";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    return *architecture_;
}
References architecture_, and hasArchitecture().
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), CostDatabase::buildFunctionUnits(), ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), AddFUImplementationCmd::Do(), HDBEditorModifyCmd::Do(), HDBToHtml::fuEntryToHtml(), ImplementationTester::fuFullyPipelined(), ImplementationTester::fuHasMemoryAccess(), FUTestbenchGenerator::generateTestbench(), ProGe::NetlistGenerator::isParameterizable(), BlockImplementationDialog::onHDBSelection(), ProGe::NetlistGenerator::opcodePortWidth(), setArchitecture(), and HDBBrowserWindow::update().
hasArchitecture()
bool HDB::FUEntry::hasArchitecture () const virtual
Tells whether the entry contains architecture data.
Returns
True if the entry contains architecture data, otherwise false.
Implements HDB::HDBEntry.
Definition at line 117 of file FUEntry.cc.
{
    return architecture_ != NULL;
}
References architecture_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), architecture(), CostDatabase::buildFunctionUnits(), ImplementationTester::canTestFU(), HDBToHtml::fuEntryToHtml(), AddFUImplementationCmd::isEnabled(), ProGe::NetlistGenerator::opcodePortWidth(), setArchitecture(), HDBBrowserWindow::update(), and ~FUEntry().
hasImplementation()
bool HDB::FUEntry::hasImplementation () const virtual
Tells whether the entry contains implementation data.
Returns
True if the entry contains implementation data, otherwise false.
Implements HDB::HDBEntry.
Definition at line 74 of file FUEntry.cc.
{
    return implementation_ != NULL;
}
References implementation_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), ImplementationTester::canTestFU(), ProGe::BlockSourceCopier::copyShared(), HDBEditorModifyCmd::Do(), HDBToHtml::fuEntryToHtml(), implementation(), AddFUImplementationCmd::isEnabled(), PlatformIntegrator::loadFUExternalPorts(), BlockImplementationDialog::onHDBSelection(), ProGe::NetlistGenerator::opcodePortWidth(), HDB::HDBManager::setArchitectureForFU(), setImplementation(), HDB::HDBManager::unsetArchitectureForFU(), HDBBrowserWindow::update(), and ~FUEntry().
implementation()
FUImplementation & HDB::FUEntry::implementation () const
Returns the implementation of the entry.
Returns
The implementation.
Exceptions
NotAvailable If there is no implementation of the entry.
Definition at line 86 of file FUEntry.cc.
{
    if (!hasImplementation()) {
        const string procName = "FUEntry::implementation";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    return *implementation_;
}
References hasImplementation(), and implementation_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::BlockSourceCopier::copyShared(), HDBEditorModifyCmd::Do(), HDBToHtml::fuEntryToHtml(), ImplementationTester::fuHasExternalPorts(), ImplementationTester::fuHasOnePort(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUTestbenchGenerator::generateTestbench(), ProGeScriptGenerator::getBlockOrder(), ProGe::NetlistGenerator::isParameterizable(), PlatformIntegrator::loadFUExternalPorts(), BlockImplementationDialog::onHDBSelection(), ProGe::NetlistGenerator::opcodePortWidth(), setImplementation(), HDBBrowserWindow::update(), and ImplementationTester::validateFU().
setArchitecture()
void HDB::FUEntry::setArchitecture (FUArchitecture * architecture)
Sets architecture of the entry.
Deletes the old architecture if one exists.
Parameters
architecture The new architecture.
Definition at line 146 of file FUEntry.cc.
{
    if (hasArchitecture()) {
        delete architecture_;
    }
    architecture_ = architecture;
}
References architecture(), architecture_, and hasArchitecture().
Referenced by HDB::HDBManager::fuByEntryID().
setImplementation()
void HDB::FUEntry::setImplementation (FUImplementation * implementation)
Sets the given implementation for the entry.
Deletes old implementation if one exists.
Parameters
implementation The implementation.
Definition at line 103 of file FUEntry.cc.
{
    if (hasImplementation()) {
        delete implementation_;
    }
    implementation_ = implementation;
}
References hasImplementation(), implementation(), and implementation_.
Referenced by AddFUImplementationCmd::Do(), and HDB::HDBManager::fuByEntryID().
Member Data Documentation
architecture_
FUArchitecture* HDB::FUEntry::architecture_ private
Architecture of the entry.
Definition at line 64 of file FUEntry.hh.
Referenced by architecture(), hasArchitecture(), setArchitecture(), and ~FUEntry().
implementation_
FUImplementation* HDB::FUEntry::implementation_ private
Implementation of the entry.
Definition at line 66 of file FUEntry.hh.
Referenced by hasImplementation(), implementation(), setImplementation(), and ~FUEntry().
The documentation for this class was generated from the following files:
FUEntry.hh
FUEntry.cc