OpenASIP: BinaryEncoding Class Reference
BinaryEncoding Class Reference
#include <BinaryEncoding.hh>
Public Types
enum Position { LEFT , RIGHT }
Public Member Functions
BinaryEncoding ()
BinaryEncoding (const ObjectState *state)
virtual ~BinaryEncoding ()
int moveSlotCount () const
MoveSlot & moveSlot (int index) const
bool hasMoveSlot (const std::string &name) const
MoveSlot & moveSlot (const std::string &name) const
void addMoveSlot (MoveSlot &slot)
void removeMoveSlot (MoveSlot &slot)
int immediateSlotCount () const
ImmediateSlotField & immediateSlot (int index) const
bool hasImmediateSlot (const std::string &name) const
ImmediateSlotField & immediateSlot (const std::string &name) const
void addImmediateSlot (ImmediateSlotField &slot)
void removeImmediateSlot (ImmediateSlotField &slot)
bool hasImmediateControlField () const
ImmediateControlField & immediateControlField () const
void setImmediateControlField (ImmediateControlField &field)
void unsetImmediateControlField ()
int longImmDstRegisterFieldCount () const
LImmDstRegisterField & longImmDstRegisterField (int index) const
LImmDstRegisterField & longImmDstRegisterField (const std::string &iTemp, const std::string &dstUnit) const
void addLongImmDstRegisterField (LImmDstRegisterField &field)
void removeLongImmDstRegisterField (LImmDstRegisterField &field)
int instructionFormatCount () const
bool hasInstructionFormat (const std::string &name) const
InstructionFormat & instructionFormat (int index) const
InstructionFormat * instructionFormat (const std::string &name) const
void addInstructionFormat (InstructionFormat &format)
void removeInstructionFormat (InstructionFormat &format)
int socketCodeTableCount () const
SocketCodeTable & socketCodeTable (int index) const
SocketCodeTable & socketCodeTable (const std::string &name) const
void addSocketCodeTable (SocketCodeTable &table)
void removeSocketCodeTable (SocketCodeTable &table)
int longestTemplateExtraBits () const
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
virtual int width (const TCEString &templateName) const
virtual int width () const
void setTemplateExtraBits (const TCEString &templateName, int bitCount)
int templateExtraBits (const TCEString &templateName) const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_BEM = "bem"
ObjectState name for binary encoding.
static const std::string OSNAME_FU_OPCODE
static const std::string OSNAME_TEMPLATE_EXTRA_BITS
static const std::string OSNAME_TEMPLATE_EXTRA_BIT_COUNT
static const std::string OSNAME_TEMPLATE_NAME = "template"
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Types
typedef std::vector< MoveSlot * > MoveSlotContainer
Container type for MoveSlots.
typedef std::vector< ImmediateSlotField * > ImmediateSlotContainer
Container type for ImmediateSlotFields.
typedef std::vector< SocketCodeTable * > SocketCodeTableContainer
Container type for SocketCodeTables.
typedef std::vector< LImmDstRegisterField * > LImmDstRegisterFieldContainer
Container type for LImmDstRegisterFields.
typedef std::vector< InstructionFormat * > InstructionFormatContainer
Container type for InstructionFormats.
typedef std::map< TCEString, int > TemplateExtraBitCountMap
Template extra bit count container.
Private Member Functions
bool hasSocketCodeTable (const std::string &name) const
void deleteMoveSlots ()
void deleteImmediateSlots ()
void deleteLongImmDstRegisterFields ()
void deleteSocketCodes ()
void deleteInstructionFormats ()
Private Attributes
InstructionFormatContainer instructionFormats_
A container for instruction formats.
MoveSlotContainer moveSlots_
A container for move slots.
ImmediateSlotContainer immediateSlots_
A container for immediate slots.
SocketCodeTableContainer socketCodes_
A container for socket code tables.
ImmediateControlField * immediateField_
The immediate control field.
LImmDstRegisterFieldContainer longImmDstRegFields_
A container for long immediate register fields.
TemplateExtraBitCountMap extraTemplateBits_
Extra (padding) bits per instruction template.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
BinaryEncoding is the root class in the object model of the binary encoding map.
An instance of this class is sufficient to access all the information pertaining a binary encoding map, so an object can be passed to clients whenever a full description of the encoding map is required. BinaryEncoding is mostly a specialized container of objects of other classes.
Definition at line 61 of file BinaryEncoding.hh.
Member Typedef Documentation
ImmediateSlotContainer
typedef std::vector<ImmediateSlotField*> BinaryEncoding::ImmediateSlotContainer private
Container type for ImmediateSlotFields.
Definition at line 137 of file BinaryEncoding.hh.
InstructionFormatContainer
typedef std::vector<InstructionFormat*> BinaryEncoding::InstructionFormatContainer private
Container type for InstructionFormats.
Definition at line 143 of file BinaryEncoding.hh.
LImmDstRegisterFieldContainer
typedef std::vector<LImmDstRegisterField*> BinaryEncoding::LImmDstRegisterFieldContainer private
Container type for LImmDstRegisterFields.
Definition at line 141 of file BinaryEncoding.hh.
MoveSlotContainer
typedef std::vector<MoveSlot*> BinaryEncoding::MoveSlotContainer private
Container type for MoveSlots.
Definition at line 135 of file BinaryEncoding.hh.
SocketCodeTableContainer
typedef std::vector<SocketCodeTable*> BinaryEncoding::SocketCodeTableContainer private
Container type for SocketCodeTables.
Definition at line 139 of file BinaryEncoding.hh.
TemplateExtraBitCountMap
typedef std::map<TCEString, int> BinaryEncoding::TemplateExtraBitCountMap private
Template extra bit count container.
Definition at line 145 of file BinaryEncoding.hh.
Member Enumeration Documentation
Position
enum BinaryEncoding::Position
Enumerator
LEFT
RIGHT
Definition at line 63 of file BinaryEncoding.hh.
                  {
        LEFT,
        RIGHT
    };
Constructor & Destructor Documentation
BinaryEncoding() [1/2]
BinaryEncoding::BinaryEncoding ()
The constructor.
Creates an empty BEM.
Definition at line 65 of file BinaryEncoding.cc.
                               :
    InstructionField(NULL), immediateField_(NULL) {
}
BinaryEncoding() [2/2]
BinaryEncoding::BinaryEncoding (const ObjectState * state)
The constructor.
Loads the state of the object from the given ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 78 of file BinaryEncoding.cc.
    : InstructionField(NULL), immediateField_(NULL) {
    loadState(state);
}
References loadState().
~BinaryEncoding()
BinaryEncoding::~BinaryEncoding () virtual
The destructor.
Definition at line 86 of file BinaryEncoding.cc.
{
    if (hasImmediateControlField()) {
        delete immediateField_;
    }
    deleteMoveSlots();
    deleteImmediateSlots();
    deleteLongImmDstRegisterFields();
    deleteSocketCodes();
    deleteInstructionFormats();
}
References deleteImmediateSlots(), deleteInstructionFormats(), deleteLongImmDstRegisterFields(), deleteMoveSlots(), deleteSocketCodes(), hasImmediateControlField(), and immediateField_.
Member Function Documentation
addImmediateSlot()
void BinaryEncoding::addImmediateSlot (ImmediateSlotField & slot)
Adds the given immediate slot to the encoding map.
This method is to be called from the constructor of ImmediateSlotField.
Parameters
slot The immediate slot to be added.
Exceptions
ObjectAlreadyExists If the encoding map contains an immediate slot with the same name already.
Definition at line 300 of file BinaryEncoding.cc.
{
    // verify that this is called from MoveSlot constructor
    assert(slot.parent() == NULL);
    if (hasImmediateSlot(slot.name())) {
        const string procName = "BinaryEncoding::addImmediateSlot";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    immediateSlots_.push_back(&slot);
}
References assert, hasImmediateSlot(), immediateSlots_, ImmediateSlotField::name(), and ImmediateSlotField::parent().
Referenced by ImmediateSlotField::ImmediateSlotField(), and ImmediateSlotField::ImmediateSlotField().
addInstructionFormat()
void BinaryEncoding::addInstructionFormat (InstructionFormat & format)
Adds the given instruction format to the encoding map.
Parameters
format The instruction format to be added.
Exceptions
ObjectAlreadyExists If the encoding map already contains a a socket code table with the same name as the given table.
Definition at line 557 of file BinaryEncoding.cc.
{
    // verify that this is called from InstructionFormat constructor
    assert(format.parent() == NULL);
    if (hasInstructionFormat(format.name())) {
        const string procName = "BinaryEncoding::addInstructionFormat";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    instructionFormats_.push_back(&format);
}
References assert, hasInstructionFormat(), instructionFormats_, InstructionFormat::name(), and InstructionFormat::parent().
addLongImmDstRegisterField()
void BinaryEncoding::addLongImmDstRegisterField (LImmDstRegisterField & field)
Adds the given long immediate destination register field to the instruction format.
This method is to be called from the constructor of LImmDstRegisterField only!
Parameters
field The field to add.
Definition at line 459 of file BinaryEncoding.cc.
{
    assert(field.parent() == NULL);
    longImmDstRegFields_.push_back(&field);
}
References assert, longImmDstRegFields_, and LImmDstRegisterField::parent().
Referenced by LImmDstRegisterField::LImmDstRegisterField(), and LImmDstRegisterField::LImmDstRegisterField().
addMoveSlot()
void BinaryEncoding::addMoveSlot (MoveSlot & slot)
Adds the given move slot to the encoding map.
This method is to be called from the constructor of MoveSlot.
Parameters
slot The move slot to be added.
Exceptions
ObjectAlreadyExists If the encoding map contains a slot with the same name already.
Definition at line 183 of file BinaryEncoding.cc.
{
    // verify that this is called from MoveSlot constructor
    assert(slot.parent() == NULL);
    if (hasMoveSlot(slot.name())) {
        const string procName = "BinaryEncoding::addMoveSlot";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    moveSlots_.push_back(&slot);
}
References assert, hasMoveSlot(), moveSlots_, MoveSlot::name(), and MoveSlot::parent().
Referenced by MoveSlot::MoveSlot(), and MoveSlot::MoveSlot().
addSocketCodeTable()
void BinaryEncoding::addSocketCodeTable (SocketCodeTable & table)
Adds the given socket code table to the encoding map.
This method is to be called from the constructor of SocketCodeTable.
Parameters
table The socket code table to be added.
Exceptions
ObjectAlreadyExists If the encoding map already contains a socket code table with the same name as the given table.
Definition at line 644 of file BinaryEncoding.cc.
{
    // verify that this is called from SocketCodeTable constructor
    assert(table.parent() == NULL);
    if (hasSocketCodeTable(table.name())) {
        const string procName = "BinaryEncoding::addSocketCodeTable";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    socketCodes_.push_back(&table);
}
References assert, hasSocketCodeTable(), SocketCodeTable::name(), SocketCodeTable::parent(), and socketCodes_.
Referenced by SocketCodeTable::SocketCodeTable(), and SocketCodeTable::SocketCodeTable().
childField()
InstructionField & BinaryEncoding::childField (int position) const virtual
Returns the child instruction field at the given relative position.
Returns a NullInstructionField instance if there is no child field at the given position. This is, however, not possible if the object model is in consistent state.
Parameters
position The relative position.
Returns
The instruction field at the given relative position.
Exceptions
OutOfRange If the given position is negative or not smaller than the number of child fields.
Reimplemented from InstructionField.
Definition at line 723 of file BinaryEncoding.cc.
{
    if (position < 0 || position >= childFieldCount()) {
        const string procName = "BinaryEncoding::childField";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    if (hasImmediateControlField() &&
        immediateControlField().relativePosition() == position) {
        return immediateControlField();
    }
    int moveSlots = moveSlotCount();
    for (int i = 0; i < moveSlots; i++) {
        MoveSlot& slot = moveSlot(i);
        if (slot.relativePosition() == position) {
            return slot;
        }
    }
    int immediateSlots = immediateSlotCount();
    for (int i = 0; i < immediateSlots; i++) {
        ImmediateSlotField& slot = immediateSlot(i);
        if (slot.relativePosition() == position) {
            return slot;
        }
    }
    int limmDstRegFields = longImmDstRegisterFieldCount();
    for (int i = 0; i < limmDstRegFields; i++) {
        LImmDstRegisterField& field = longImmDstRegisterField(i);
        if (field.relativePosition() == position) {
            return field;
        }
    }
    return NullInstructionField::instance();
}
References childFieldCount(), hasImmediateControlField(), immediateControlField(), immediateSlot(), immediateSlotCount(), NullInstructionField::instance(), longImmDstRegisterField(), longImmDstRegisterFieldCount(), moveSlot(), moveSlotCount(), and InstructionField::relativePosition().
Referenced by CodeCompressorPlugin::bemInstructionBits(), and printInstructionLayout().
childFieldCount()
int BinaryEncoding::childFieldCount () const virtual
Returns the number of immediate child fields (move slots + immediate slots + immediate control field).
Returns
The number of child fields.
Implements InstructionField.
Definition at line 700 of file BinaryEncoding.cc.
{
    int count = moveSlotCount() + immediateSlotCount() +
        longImmDstRegisterFieldCount();
    if (hasImmediateControlField()) {
        count++;
    }
    return count;
}
References hasImmediateControlField(), immediateSlotCount(), longImmDstRegisterFieldCount(), and moveSlotCount().
Referenced by childField(), and printInstructionLayout().
deleteImmediateSlots()
void BinaryEncoding::deleteImmediateSlots () private
Deletes all the immediate slots contained by the encoding map.
Definition at line 980 of file BinaryEncoding.cc.
{
    SequenceTools::deleteAllItems(immediateSlots_);
}
References SequenceTools::deleteAllItems(), and immediateSlots_.
Referenced by ~BinaryEncoding().
deleteInstructionFormats()
void BinaryEncoding::deleteInstructionFormats () private
Deletes all the instruction formats contained by the encoding map.
Definition at line 1007 of file BinaryEncoding.cc.
{
    SequenceTools::deleteAllItems(instructionFormats_);
}
References SequenceTools::deleteAllItems(), and instructionFormats_.
Referenced by ~BinaryEncoding().
deleteLongImmDstRegisterFields()
void BinaryEncoding::deleteLongImmDstRegisterFields () private
Deletes all the long immediate destination register fields contained by the encoding map.
Definition at line 990 of file BinaryEncoding.cc.
{
    SequenceTools::deleteAllItems(longImmDstRegFields_);
}
References SequenceTools::deleteAllItems(), and longImmDstRegFields_.
Referenced by ~BinaryEncoding().
deleteMoveSlots()
void BinaryEncoding::deleteMoveSlots () private
Deletes all the move slots contained by the encoding map.
Definition at line 971 of file BinaryEncoding.cc.
{
    SequenceTools::deleteAllItems(moveSlots_);
}
References SequenceTools::deleteAllItems(), and moveSlots_.
Referenced by ~BinaryEncoding().
deleteSocketCodes()
void BinaryEncoding::deleteSocketCodes () private
Deletes all the socket code tables contained by the encoding map.
Definition at line 999 of file BinaryEncoding.cc.
{
    SequenceTools::deleteAllItems(socketCodes_);
}
References SequenceTools::deleteAllItems(), and socketCodes_.
Referenced by ~BinaryEncoding().
hasImmediateControlField()
bool BinaryEncoding::hasImmediateControlField () const
Tells whether the instruction word has an immediate control field.
Returns
True if the instruction word has an immediate control field, otherwise false.
Definition at line 334 of file BinaryEncoding.cc.
{
    return immediateField_ != NULL;
}
References immediateField_.
Referenced by BEMValidator::checkImmediateControlField(), childField(), childFieldCount(), CodeCompressorPlugin::firstMoveSlotIndex(), immediateControlField(), DefaultDecoderGenerator::instructionTemplateCondition(), printImmediateControlField(), saveState(), setImmediateControlField(), unsetImmediateControlField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeLongImmediateTagSignal(), DefaultDecoderGenerator::writeLongImmediateWriteProcess(), and ~BinaryEncoding().
hasImmediateSlot()
bool BinaryEncoding::hasImmediateSlot (const std::string & name) const
Tells whether the encoding map contains an immediate slot with the given name.
Parameters
name The name of the immediate slot.
Returns
True if there is an immediate slot with the given name, otherwise false.
Definition at line 252 of file BinaryEncoding.cc.
{
    for (ImmediateSlotContainer::const_iterator iter =
             immediateSlots_.begin(); iter != immediateSlots_.end();
         iter++) {
        ImmediateSlotField* slot = *iter;
        if (slot->name() == name) {
            return true;
        }
    }
    return false;
}
References immediateSlots_, and ImmediateSlotField::name().
Referenced by addImmediateSlot(), and BEMValidator::checkImmediateSlot().
hasInstructionFormat()
bool BinaryEncoding::hasInstructionFormat (const std::string & name) const
Tells whether the binary encoding has an instruction format with the given name.
Parameters
name The name.
Returns
True if the ecoding map contains an instruction format with the given name, otherwise false.
Definition at line 502 of file BinaryEncoding.cc.
{
    return std::find_if(
               instructionFormats_.begin(), instructionFormats_.end(),
               [name](const InstructionFormat* it) {
                   return it->name() == name;
               }) != instructionFormats_.end();
}
References instructionFormats_.
Referenced by addInstructionFormat().
hasMoveSlot()
bool BinaryEncoding::hasMoveSlot (const std::string & name) const
Tells whether the encoding map contains a move slot with the given (bus) name.
Parameters
name The bus name.
Returns
True if there is a move slot with the given name, otherwise false.
Definition at line 138 of file BinaryEncoding.cc.
{
    for (MoveSlotContainer::const_iterator iter = moveSlots_.begin();
         iter != moveSlots_.end(); iter++) {
        MoveSlot* slot = *iter;
        if (slot->name() == name) {
            return true;
        }
    }
    return false;
}
References moveSlots_, and MoveSlot::name().
Referenced by addMoveSlot(), BEMValidator::checkMoveSlot(), DefaultDecoderGenerator::writeSquashSignalGenerationProcess(), and DefaultDecoderGenerator::writeSquashSignals().
hasSocketCodeTable()
bool BinaryEncoding::hasSocketCodeTable (const std::string & name) const private
Tells whether the encoding map contains a socket code table with the given name.
Parameters
name The name.
Returns
True if the encoding map contains a socket code table with the given name, otherwise false.
Definition at line 954 of file BinaryEncoding.cc.
{
    for (SocketCodeTableContainer::const_iterator iter = socketCodes_.begin();
         iter != socketCodes_.end(); iter++) {
        SocketCodeTable* table = *iter;
        if (table->name() == name) {
            return true;
        }
    }
    return false;
}
References SocketCodeTable::name(), and socketCodes_.
Referenced by addSocketCodeTable().
immediateControlField()
ImmediateControlField & BinaryEncoding::immediateControlField () const
Returns the immediate control field of the instruction word, if one exists.
Returns a NullImmediateControlField instance otherwise (a single-template instruction).
Returns
The immediate control field.
Definition at line 348 of file BinaryEncoding.cc.
{
    if (hasImmediateControlField()) {
        return *immediateField_;
    } else {
        return NullImmediateControlField::instance();
    }
}
References hasImmediateControlField(), immediateField_, and NullImmediateControlField::instance().
Referenced by BEMValidator::checkImmediateControlField(), childField(), CodeCompressorPlugin::firstMoveSlotIndex(), DefaultDecoderGenerator::instructionTemplateCondition(), printImmediateControlField(), saveState(), unsetImmediateControlField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeLongImmediateTagSignal(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
immediateSlot() [1/2]
ImmediateSlotField & BinaryEncoding::immediateSlot (const std::string & name) const
Returns the immediate slot of the given name.
Parameters
name The name of the immediate slot.
Returns
The immediate slot.
Exceptions
InstanceNotFound If the encoding map does not contain an immediate slot with the given name.
Definition at line 276 of file BinaryEncoding.cc.
{
    for (ImmediateSlotContainer::const_iterator iter =
             immediateSlots_.begin(); iter != immediateSlots_.end();
         iter++) {
        ImmediateSlotField* slot = *iter;
        if (slot->name() == name) {
            return *slot;
        }
    }
    const string procName = "BinaryEncoding::immediateSlot";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
}
References immediateSlots_, and ImmediateSlotField::name().
immediateSlot() [2/2]
ImmediateSlotField & BinaryEncoding::immediateSlot (int index) const
Returns the immediate slot at given index.
The index does not have to reflect the actual order within the TTA instruction word.
Parameters
index The index.
Returns
The immediate slot at given index.
Exceptions
OutOfRange If the index is negative or is not smaller than the number of immediate slots in the TTA instruction word.
Definition at line 234 of file BinaryEncoding.cc.
{
    if (index < 0 || index >= immediateSlotCount()) {
        const string procName = "BinaryEncoding::immediateSlot";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *immediateSlots_[index];
}
References immediateSlotCount(), and immediateSlots_.
Referenced by BEMValidator::checkImmediateSlot(), childField(), saveState(), width(), DefaultDecoderGenerator::writeImmediateSlotSignals(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeInstructionTemplateProcedures().
immediateSlotCount()
int BinaryEncoding::immediateSlotCount () const
Returns the number of immediate slots in the instruction.
Returns
The number of immediate slots.
Definition at line 216 of file BinaryEncoding.cc.
{
    return immediateSlots_.size();
}
References immediateSlots_.
Referenced by childField(), childFieldCount(), immediateSlot(), saveState(), width(), DefaultDecoderGenerator::writeImmediateSlotSignals(), and DefaultDecoderGenerator::writeInstructionDismembering().
instructionFormat() [1/2]
InstructionFormat * BinaryEncoding::instructionFormat (const std::string & name) const
Returns the instruction format with the given name.
Parameters
name The name of the format.
Returns
The instruction format, null if not found
Definition at line 536 of file BinaryEncoding.cc.
{
    InstructionFormat* format = NULL;
    for (int f = 0; f < instructionFormatCount(); f++) {
        if (instructionFormat(f).name() == name) {
            format = &instructionFormat(f);
            break;
        }
    }
    return format;
}
References instructionFormat(), instructionFormatCount(), and InstructionFormat::name().
instructionFormat() [2/2]
InstructionFormat & BinaryEncoding::instructionFormat (int index) const
Returns the instruction format with the given index.
Parameters
index The index.
Returns
The instruction format
Exceptions
OutOfRange If the given index is negative or not smaller than the number of instruction formats in the encoding map.
Definition at line 521 of file BinaryEncoding.cc.
{
    if (index < 0 || index >= instructionFormatCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return *instructionFormats_[index];
}
References __func__, instructionFormatCount(), and instructionFormats_.
Referenced by RISCVTDGen::findCustomOps(), llvm::LLVMTCERISCVIntrinsicsLowering::findRFormat(), ProGe::RV32MicroCodeGenerator::initializeOperations(), and instructionFormat().
instructionFormatCount()
int BinaryEncoding::instructionFormatCount () const
Returns the number of instruction formats in the in binary encoding.
Returns
The number of instruction formats.
Definition at line 488 of file BinaryEncoding.cc.
{
    return instructionFormats_.size();
}
References instructionFormats_.
Referenced by llvm::LLVMTCERISCVIntrinsicsLowering::findRFormat(), ProGe::RV32MicroCodeGenerator::initializeOperations(), instructionFormat(), instructionFormat(), and saveState().
loadState()
void BinaryEncoding::loadState (const ObjectState * state) virtual
Loads the state of the binary encoding map from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Definition at line 826 of file BinaryEncoding.cc.
{
    if (state->name() != OSNAME_BEM) {
        const string procName = "BinaryEncoding::loadState";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    // create socket code tables at first
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == SocketCodeTable::OSNAME_SOCKET_CODE_TABLE) {
            new SocketCodeTable(child, *this);
        }
    }
    // create subfields in the correct order
    ObjectState* newState = new ObjectState(*state);
    reorderSubfields(newState);
    for (int i = 0; i < newState->childCount(); i++) {
        ObjectState* child = newState->child(i);
        if (child->name() == MoveSlot::OSNAME_MOVE_SLOT) {
            new MoveSlot(child, *this);
        } else if (child->name() ==
                   ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD) {
            new ImmediateSlotField(child, *this);
        } else if (child->name() ==
                   ImmediateControlField::OSNAME_IMM_CONTROL_FIELD) {
            new ImmediateControlField(child, *this);
        } else if (child->name() ==
                   LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD) {
            new LImmDstRegisterField(child, *this);
        } else if (
            child->name() == BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS) {
            setTemplateExtraBits(
                child->childByName(BinaryEncoding::OSNAME_TEMPLATE_NAME)
                    ->stringValue(),
                child
                    ->childByName(
                        BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BIT_COUNT)
                    ->intValue());
        }
    }
    delete newState;
}
References ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::intValue(), ObjectState::name(), OSNAME_BEM, ImmediateControlField::OSNAME_IMM_CONTROL_FIELD, ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD, LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD, MoveSlot::OSNAME_MOVE_SLOT, SocketCodeTable::OSNAME_SOCKET_CODE_TABLE, OSNAME_TEMPLATE_EXTRA_BIT_COUNT, OSNAME_TEMPLATE_EXTRA_BITS, OSNAME_TEMPLATE_NAME, InstructionField::reorderSubfields(), setTemplateExtraBits(), and ObjectState::stringValue().
Referenced by BinaryEncoding().
longestTemplateExtraBits()
int BinaryEncoding::longestTemplateExtraBits () const
Returns the extra template bit amount in the largest template in the machine. Needed for instructionField's bitPosition-method.
Returns
The extra padding bits in the longest instruction template.
Definition at line 676 of file BinaryEncoding.cc.
{
    if (immediateField_ == NULL) return 0;
    TCEString longestTemplate = "";
    int maxWidth = 0;
    for (int i = 0; i < immediateField_->templateCount(); ++i) {
        TCEString iTemplate = immediateField_->instructionTemplate(i);
        int w = width(iTemplate);
        if (w > maxWidth) {
            maxWidth = w;
            longestTemplate = iTemplate;
        }
    }
    return templateExtraBits(longestTemplate);
}
References immediateField_, ImmediateControlField::instructionTemplate(), ImmediateControlField::templateCount(), templateExtraBits(), and width().
longImmDstRegisterField() [1/2]
LImmDstRegisterField & BinaryEncoding::longImmDstRegisterField (const std::string & iTemp, const std::string & dstUnit) const
Returns the long immediate destination register field that gives the destination register of the given immediate unit in the given instruction template.
Parameters
iTemp Name of the instruction template.
dstUnit Name of the immediate unit.
Returns
The long immediate destination register field.
Exceptions
InstanceNotFound If there is no such field.
Definition at line 434 of file BinaryEncoding.cc.
{
    int fields = longImmDstRegisterFieldCount();
    for (int i = 0; i < fields; i++) {
        LImmDstRegisterField& field = longImmDstRegisterField(i);
        if (field.usedByInstructionTemplate(iTemp)) {
            if (field.immediateUnit(iTemp) == dstUnit) {
                return field;
            }
        }
    }
    throw InstanceNotFound(__FILE__, __LINE__, __func__);
}
References __func__, LImmDstRegisterField::immediateUnit(), longImmDstRegisterField(), longImmDstRegisterFieldCount(), and LImmDstRegisterField::usedByInstructionTemplate().
longImmDstRegisterField() [2/2]
LImmDstRegisterField & BinaryEncoding::longImmDstRegisterField (int index) const
Returns a long immediate destination register field by the given index.
Parameters
index The index.
Returns
The field.
Exceptions
OutOfRange If the index is negative or not smaller than the number of long immediate destination register fields.
Definition at line 415 of file BinaryEncoding.cc.
{
    if (index < 0 || index >= longImmDstRegisterFieldCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return *longImmDstRegFields_[index];
}
References __func__, longImmDstRegFields_, and longImmDstRegisterFieldCount().
Referenced by BEMValidator::checkLImmDstRegisterFields(), childField(), CodeCompressorPlugin::firstMoveSlotIndex(), longImmDstRegisterField(), printBEMInfo(), saveState(), width(), and DefaultDecoderGenerator::writeInstructionTemplateProcedures().
longImmDstRegisterFieldCount()
int BinaryEncoding::longImmDstRegisterFieldCount () const
Returns the number of long immediate destination register fields in the instruction.
Returns
The number of fields.
Definition at line 400 of file BinaryEncoding.cc.
{
    return longImmDstRegFields_.size();
}
References longImmDstRegFields_.
Referenced by BEMValidator::checkLImmDstRegisterFields(), childField(), childFieldCount(), CodeCompressorPlugin::firstMoveSlotIndex(), longImmDstRegisterField(), longImmDstRegisterField(), printBEMInfo(), saveState(), and width().
moveSlot() [1/2]
MoveSlot & BinaryEncoding::moveSlot (const std::string & name) const
Returns the move slot that programs the bus identified by the given name.
Parameters
The bus name.
Returns
The move slot.
Exceptions
InstanceNotFound If the encoding map does not contain a move slot with the given name.
Definition at line 160 of file BinaryEncoding.cc.
{
    for (MoveSlotContainer::const_iterator iter = moveSlots_.begin();
         iter != moveSlots_.end(); iter++) {
        MoveSlot* slot = *iter;
        if (slot->name() == name) {
            return *slot;
        }
    }
    const string procName = "BinaryEncoding::moveSlot";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
}
References moveSlots_, and MoveSlot::name().
moveSlot() [2/2]
MoveSlot & BinaryEncoding::moveSlot (int index) const
Returns the move slot at given index.
The index does not have to reflect the actual order within the TTA instruction word.
Parameters
index The index.
Returns
The move slot at given index.
Exceptions
OutOfRange If the index is negative or is not smaller than the number of move slots of the TTA instruction word.
Definition at line 121 of file BinaryEncoding.cc.
{
    if (index < 0 || index >= moveSlotCount()) {
        const string procName = "BinaryEncoding::moveSlot";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *moveSlots_[index];
}
References moveSlotCount(), and moveSlots_.
Referenced by BEMValidator::checkDestinationField(), BEMValidator::checkGuardField(), BEMValidator::checkSourceField(), childField(), DestinationField::DestinationField(), ProGe::RV32MicroCodeGenerator::findBusWidths(), BEMGenerator::generate(), CodeCompressorPlugin::moveSlotWidth(), printBEMInfo(), saveState(), SourceField::SourceField(), width(), DefaultDecoderGenerator::writeBusControlRulesOfOutputSocket(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), DefaultDecoderGenerator::writeControlRulesOfRFWritePort(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeInstructionTemplateProcedures(), DefaultDecoderGenerator::writeMoveFieldSignals(), DefaultDecoderGenerator::writeSimmDataSignal(), DefaultDecoderGenerator::writeSquashSignalGenerationProcess(), DefaultDecoderGenerator::writeSquashSignals(), and SocketCodeTable::~SocketCodeTable().
moveSlotCount()
int BinaryEncoding::moveSlotCount () const
Returns the number of move slots in the instruction.
Returns
The number of move slots.
Definition at line 104 of file BinaryEncoding.cc.
{
    return moveSlots_.size();
}
References moveSlots_.
Referenced by childField(), childFieldCount(), DestinationField::DestinationField(), ProGe::RV32MicroCodeGenerator::findBusWidths(), BEMGenerator::generate(), moveSlot(), CodeCompressorPlugin::moveSlotCount(), printBEMInfo(), saveState(), SourceField::SourceField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), and SocketCodeTable::~SocketCodeTable().
removeImmediateSlot()
void BinaryEncoding::removeImmediateSlot (ImmediateSlotField & slot)
Removes the given immediate slot from the encoding map.
This method is to be called from the destructor of ImmediateSlotField.
Parameters
slot The immediate slot to be removed.
Definition at line 320 of file BinaryEncoding.cc.
{
    // verify that this is called from ImmediateSlotField destructor.
    assert(slot.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(immediateSlots_, &slot));
}
References assert, immediateSlots_, ImmediateSlotField::parent(), and ContainerTools::removeValueIfExists().
Referenced by ImmediateSlotField::~ImmediateSlotField().
removeInstructionFormat()
void BinaryEncoding::removeInstructionFormat (InstructionFormat & format)
Removes the given instruction format from the encoding map. This method is to be called from the destructor Instruction Format.
Parameters
format The instruction format to be removed.
Definition at line 577 of file BinaryEncoding.cc.
{
    assert(format.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(instructionFormats_, &format));
}
References assert, instructionFormats_, InstructionFormat::parent(), and ContainerTools::removeValueIfExists().
removeLongImmDstRegisterField()
void BinaryEncoding::removeLongImmDstRegisterField (LImmDstRegisterField & field)
Removes the given long immediate destination register field from the instruction format.
This method is to be called from the destructor of LImmDstRegisterField only!
Parameters
field The field to remove.
Definition at line 475 of file BinaryEncoding.cc.
{
    assert(field.parent() == NULL);
    assert(
        ContainerTools::removeValueIfExists(longImmDstRegFields_, &field));
}
References assert, longImmDstRegFields_, LImmDstRegisterField::parent(), and ContainerTools::removeValueIfExists().
Referenced by LImmDstRegisterField::~LImmDstRegisterField().
removeMoveSlot()
void BinaryEncoding::removeMoveSlot (MoveSlot & slot)
Removes the given move slot from the encoding map.
This method is to be called from the destructor of MoveSlot.
Parameters
slot The move slot to be removed.
Definition at line 203 of file BinaryEncoding.cc.
{
    // verify that this is called from MoveSlot destructor.
    assert(slot.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(moveSlots_, &slot));
}
References assert, moveSlots_, MoveSlot::parent(), and ContainerTools::removeValueIfExists().
Referenced by MoveSlot::~MoveSlot().
removeSocketCodeTable()
void BinaryEncoding::removeSocketCodeTable (SocketCodeTable & table)
Removes the given socket code table from the encoding map.
This method is to be called from the destructor of SocketCodeTable.
Parameters
table The socket code table to be removed.
Definition at line 664 of file BinaryEncoding.cc.
{
    assert(table.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(socketCodes_, &table));
}
References assert, SocketCodeTable::parent(), ContainerTools::removeValueIfExists(), and socketCodes_.
Referenced by SocketCodeTable::~SocketCodeTable().
saveState()
ObjectState * BinaryEncoding::saveState () const virtual
Saves the state of the binary encoding map to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from InstructionField.
Definition at line 877 of file BinaryEncoding.cc.
{
    ObjectState* bem = new ObjectState(OSNAME_BEM);
    // add move slots
    int moveSlots = moveSlotCount();
    for (int i = 0; i < moveSlots; i++) {
        MoveSlot& slot = moveSlot(i);
        bem->addChild(slot.saveState());
    }
    // add immediate slots
    int immediateSlots = immediateSlotCount();
    for (int i = 0; i < immediateSlots; i++) {
        ImmediateSlotField& slot = immediateSlot(i);
        bem->addChild(slot.saveState());
    }
    // add long immediate destination register fields
    int limmDstRegFields = longImmDstRegisterFieldCount();
    for (int i = 0; i < limmDstRegFields; i++) {
        LImmDstRegisterField& field = longImmDstRegisterField(i);
        bem->addChild(field.saveState());
    }
    // add socket code tables
    int tableCount = socketCodeTableCount();
    for (int i = 0; i < tableCount; i++) {
        SocketCodeTable& table = socketCodeTable(i);
        bem->addChild(table.saveState());
    }
    // add immediate control field
    if (hasImmediateControlField()) {
        bem->addChild(immediateControlField().saveState());
    }
    for (TemplateExtraBitCountMap::const_iterator
             i = extraTemplateBits_.begin(),
             e = extraTemplateBits_.end();
         i != e; ++i) {
        TCEString templateName = (*i).first;
        int bitCount = (*i).second;
        ObjectState* root =
            new ObjectState(BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS);
        ObjectState* templateNameObj =
            new ObjectState(BinaryEncoding::OSNAME_TEMPLATE_NAME);
        templateNameObj->setValue(templateName);
        ObjectState* bitCountObj =
            new ObjectState(BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BIT_COUNT);
        bitCountObj->setValue(bitCount);
        root->addChild(templateNameObj);
        root->addChild(bitCountObj);
        bem->addChild(root);
    }
    for (int i = 0; i < instructionFormatCount(); i++) {
        bem->addChild(instructionFormats_.at(i)->saveState());
    }
    return bem;
}
References ObjectState::addChild(), extraTemplateBits_, hasImmediateControlField(), immediateControlField(), immediateSlot(), immediateSlotCount(), instructionFormatCount(), instructionFormats_, longImmDstRegisterField(), longImmDstRegisterFieldCount(), moveSlot(), moveSlotCount(), OSNAME_BEM, OSNAME_TEMPLATE_EXTRA_BIT_COUNT, OSNAME_TEMPLATE_EXTRA_BITS, OSNAME_TEMPLATE_NAME, saveState(), ImmediateSlotField::saveState(), LImmDstRegisterField::saveState(), MoveSlot::saveState(), SocketCodeTable::saveState(), ObjectState::setValue(), socketCodeTable(), and socketCodeTableCount().
Referenced by ProGe::ProGeUI::loadBinaryEncoding(), saveState(), and BEMSerializer::writeBinaryEncoding().
setImmediateControlField()
void BinaryEncoding::setImmediateControlField (ImmediateControlField & field)
Adds the given immediate control field to the instruction word.
This method is to be called from the constructor of ImmediateControlField.
Parameters
field The immediate control field to be added.
Exceptions
ObjectAlreadyExists If the instruction word already has an immediate control field.
Definition at line 367 of file BinaryEncoding.cc.
{
    // verify that this is called from ImmediateControlField constructor
    assert(field.parent() == NULL);
    if (hasImmediateControlField()) {
        const string procName = "BinaryEncoding::setImmediateControlField";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    immediateField_ = &field;
}
References assert, hasImmediateControlField(), immediateField_, and ImmediateControlField::parent().
Referenced by ImmediateControlField::ImmediateControlField(), and ImmediateControlField::ImmediateControlField().
setTemplateExtraBits()
void BinaryEncoding::setTemplateExtraBits (const TCEString & templateName, int bitCount)
Sets the extra padding bit count for an instruction template
Definition at line 1014 of file BinaryEncoding.cc.
{
    extraTemplateBits_[templateName] = bitCount;
}
References extraTemplateBits_.
Referenced by loadState().
socketCodeTable() [1/2]
SocketCodeTable & BinaryEncoding::socketCodeTable (const std::string & name) const
Returns the socket code table which has the given name.
Returns a NullSocketCodeTable instance if there is no such table.
Parameters
name Name of the table.
Returns
The socket code table.
Definition at line 620 of file BinaryEncoding.cc.
{
    for (int i = 0; i < socketCodeTableCount(); i++) {
        SocketCodeTable& table = socketCodeTable(i);
        if (table.name() == name) {
            return table;
        }
    }
    return NullSocketCodeTable::instance();
}
References NullSocketCodeTable::instance(), SocketCodeTable::name(), socketCodeTable(), and socketCodeTableCount().
socketCodeTable() [2/2]
SocketCodeTable & BinaryEncoding::socketCodeTable (int index) const
Returns the socket code table at the given index.
Parameters
index The index.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of socket code tables in the encoding map.
Definition at line 602 of file BinaryEncoding.cc.
{
    if (index < 0 || index >= socketCodeTableCount()) {
        const string procName = "BinaryEncoding::socketCodeTable";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *socketCodes_[index];
}
References socketCodes_, and socketCodeTableCount().
Referenced by SocketCodeTable::hasParentSCTable(), saveState(), socketCodeTable(), and SocketEncoding::SocketEncoding().
socketCodeTableCount()
int BinaryEncoding::socketCodeTableCount () const
Returns the number of socket code tables contained by the encoding map.
Returns
The number of socket code tables.
Definition at line 588 of file BinaryEncoding.cc.
{
    return socketCodes_.size();
}
References socketCodes_.
Referenced by SocketCodeTable::hasParentSCTable(), saveState(), socketCodeTable(), and socketCodeTable().
templateExtraBits()
int BinaryEncoding::templateExtraBits (const TCEString & templateName) const
Definition at line 1020 of file BinaryEncoding.cc.
{
    TemplateExtraBitCountMap::const_iterator pos =
        extraTemplateBits_.find(templateName);
    if (pos == extraTemplateBits_.end()) return 0;
    return (*pos).second;
}
References extraTemplateBits_.
Referenced by longestTemplateExtraBits(), and width().
unsetImmediateControlField()
void BinaryEncoding::unsetImmediateControlField ()
Removes the immediate control field.
This method is to be called from the destructor of ImmediateControlField.
Definition at line 385 of file BinaryEncoding.cc.
{
    // verify that this is called from ImmediateControlField destructor
    assert(hasImmediateControlField());
    assert(immediateControlField().parent() == NULL);
    immediateField_ = NULL;
}
References assert, hasImmediateControlField(), immediateControlField(), immediateField_, and InstructionField::parent().
Referenced by ImmediateControlField::~ImmediateControlField().
width() [1/2]
int BinaryEncoding::width () const virtual
Returns the bit width of the maximum width instruction word defined by this encoding map.
Parameters
If set, returns the instruction width of the given instruction template, otherwise the maximum.
Returns
The bit width of the instruction word.
Implements InstructionField.
Definition at line 770 of file BinaryEncoding.cc.
{
    if (immediateField_ == NULL) return width("");
    int maxWidth = 0;
    for (int i = 0; i < immediateField_->templateCount(); ++i) {
        TCEString iTemplate = immediateField_->instructionTemplate(i);
        int w = width(iTemplate);
        if (w > maxWidth) maxWidth = w;
    }
    return maxWidth;
}
References immediateField_, ImmediateControlField::instructionTemplate(), ImmediateControlField::templateCount(), and width().
Referenced by longestTemplateExtraBits(), width(), and width().
width() [2/2]
int BinaryEncoding::width (const TCEString & templateName) const virtual
Returns the bit width of the instruction word defined by an instruction template in this encoding map.
Definition at line 787 of file BinaryEncoding.cc.
{
    int moveSlots = moveSlotCount();
    int immediateSlots = immediateSlotCount();
    int limmDstRegFields = longImmDstRegisterFieldCount();
    int width = 0;
    for (int i = 0; i < moveSlots; i++) {
        MoveSlot& slot = moveSlot(i);
        width += slot.width();
    }
    for (int i = 0; i < immediateSlots; i++) {
        ImmediateSlotField& slot = immediateSlot(i);
        width += slot.width();
    }
    for (int i = 0; i < limmDstRegFields; i++) {
        LImmDstRegisterField& field = longImmDstRegisterField(i);
        width += field.width();
    }
    if (hasImmediateControlField()) {
        width += immediateControlField().width();
    }
    width += templateExtraBits(templateName);
    width += extraBits();
    return width;
}
References InstructionField::extraBits(), hasImmediateControlField(), immediateControlField(), immediateSlot(), immediateSlotCount(), longImmDstRegisterField(), longImmDstRegisterFieldCount(), moveSlot(), moveSlotCount(), templateExtraBits(), width(), ImmediateControlField::width(), ImmediateSlotField::width(), LImmDstRegisterField::width(), and MoveSlot::width().
Referenced by CodeCompressorPlugin::bemBits(), BEMValidator::checkImemMauWidth(), InstructionDictionary::createDictionary(), InstructionDictionary::generateDecompressor(), ProgramImageGenerator::generateProgramImage(), main(), printBEMInfo(), MoveSlotDictionary::printDetails(), ProGe::ProGeUI::readImemParameters(), CodeCompressorPlugin::setMachine(), MachineCanvas::updateMachine(), and DefaultICDecoderGenerator::writeGlobalDefinitions().
Member Data Documentation
extraTemplateBits_
TemplateExtraBitCountMap BinaryEncoding::extraTemplateBits_ private
Extra (padding) bits per instruction template.
Definition at line 167 of file BinaryEncoding.hh.
Referenced by saveState(), setTemplateExtraBits(), and templateExtraBits().
immediateField_
ImmediateControlField* BinaryEncoding::immediateField_ private
The immediate control field.
Definition at line 163 of file BinaryEncoding.hh.
Referenced by hasImmediateControlField(), immediateControlField(), longestTemplateExtraBits(), setImmediateControlField(), unsetImmediateControlField(), width(), and ~BinaryEncoding().
immediateSlots_
ImmediateSlotContainer BinaryEncoding::immediateSlots_ private
A container for immediate slots.
Definition at line 159 of file BinaryEncoding.hh.
Referenced by addImmediateSlot(), deleteImmediateSlots(), hasImmediateSlot(), immediateSlot(), immediateSlot(), immediateSlotCount(), and removeImmediateSlot().
instructionFormats_
InstructionFormatContainer BinaryEncoding::instructionFormats_ private
A container for instruction formats.
Definition at line 155 of file BinaryEncoding.hh.
Referenced by addInstructionFormat(), deleteInstructionFormats(), hasInstructionFormat(), instructionFormat(), instructionFormatCount(), removeInstructionFormat(), and saveState().
longImmDstRegFields_
LImmDstRegisterFieldContainer BinaryEncoding::longImmDstRegFields_ private
A container for long immediate register fields.
Definition at line 165 of file BinaryEncoding.hh.
Referenced by addLongImmDstRegisterField(), deleteLongImmDstRegisterFields(), longImmDstRegisterField(), longImmDstRegisterFieldCount(), and removeLongImmDstRegisterField().
moveSlots_
MoveSlotContainer BinaryEncoding::moveSlots_ private
A container for move slots.
Definition at line 157 of file BinaryEncoding.hh.
Referenced by addMoveSlot(), deleteMoveSlots(), hasMoveSlot(), moveSlot(), moveSlot(), moveSlotCount(), and removeMoveSlot().
OSNAME_BEM
const std::string BinaryEncoding::OSNAME_BEM = "bem" static
ObjectState name for binary encoding.
Definition at line 127 of file BinaryEncoding.hh.
Referenced by BEMSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_FU_OPCODE
const std::string BinaryEncoding::OSNAME_FU_OPCODE static
Definition at line 128 of file BinaryEncoding.hh.
OSNAME_TEMPLATE_EXTRA_BIT_COUNT
const std::string BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BIT_COUNT static
Initial value:
=
    "bit-count"
Definition at line 130 of file BinaryEncoding.hh.
Referenced by loadState(), and saveState().
OSNAME_TEMPLATE_EXTRA_BITS
const std::string BinaryEncoding::OSNAME_TEMPLATE_EXTRA_BITS static
Initial value:
=
    "template-extra-bits"
Definition at line 129 of file BinaryEncoding.hh.
Referenced by BEMSerializer::convertToFileFormat(), BEMSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_TEMPLATE_NAME
const std::string BinaryEncoding::OSNAME_TEMPLATE_NAME = "template" static
Definition at line 131 of file BinaryEncoding.hh.
Referenced by loadState(), and saveState().
socketCodes_
SocketCodeTableContainer BinaryEncoding::socketCodes_ private
A container for socket code tables.
Definition at line 161 of file BinaryEncoding.hh.
Referenced by addSocketCodeTable(), deleteSocketCodes(), hasSocketCodeTable(), removeSocketCodeTable(), socketCodeTable(), and socketCodeTableCount().
The documentation for this class was generated from the following files:
BinaryEncoding.hh
BinaryEncoding.cc