OpenASIP: TPEF::TPEFDebugSectionReader Class Reference
TPEF::TPEFDebugSectionReader Class Reference
#include <TPEFDebugSectionReader.hh>
Protected Member Functions
TPEFDebugSectionReader ()
virtual ~TPEFDebugSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFDebugSectionReader (const TPEFDebugSectionReader &)
Copying not allowed.
TPEFDebugSectionReader & operator= (TPEFDebugSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFDebugSectionReader proto_
Prototype instance of TPEFDebugSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads debug section from TPEF binary file.
Definition at line 46 of file TPEFDebugSectionReader.hh.
Constructor & Destructor Documentation
TPEFDebugSectionReader() [1/2]
TPEF::TPEFDebugSectionReader::TPEFDebugSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 59 of file TPEFDebugSectionReader.cc.
                                               : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFDebugSectionReader()
TPEF::TPEFDebugSectionReader::~TPEFDebugSectionReader () protected virtual
Destructor.
Definition at line 66 of file TPEFDebugSectionReader.cc.
{
}
TPEFDebugSectionReader() [2/2]
TPEF::TPEFDebugSectionReader::TPEFDebugSectionReader (const TPEFDebugSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFDebugSectionReader & TPEF::TPEFDebugSectionReader::operator= (TPEFDebugSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFDebugSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read value were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 92 of file TPEFDebugSectionReader.cc.
{
    // size taken by fields common to any type of debug section element
    const std::size_t BASE_ELEM_SIZE = 10;
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    DebugSection* debugSection =
        dynamic_cast<DebugSection*>(section);
    assert(debugSection != NULL);
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // start of first element
        SectionOffset currElement = header().bodyOffset;
        while (currElement < header().bodyOffset + header().bodyLength) {
            HalfWord type = stream.readHalfWord();
            Word stringOffset = stream.readWord();
            Word size = stream.readWord();
            std::vector<Byte> data;
            for (unsigned i = 0; i < size; i++) {
                data.push_back(stream.readByte());
            }
            DebugElement* newElem = NULL;
            switch (static_cast<DebugElement::ElementType>(type)) {
            case DebugElement::DE_STAB:
                newElem = new DebugStabElem(data);
                break;
            default:
                throw UnexpectedValue(
                    __FILE__, __LINE__, __func__,
                    "Unknown debug element type: " +
                    Conversion::toString(type));
            }
            // set name string for element
            SectionOffsetKey sOffKey(header().linkId, stringOffset);
            newElem->setDebugString(CREATE_SAFEPOINTER(sOffKey));
            section->addElement(newElem);
            currElement += size + BASE_ELEM_SIZE;
            stream.setReadPosition(currElement);
        }
    }
}
References __func__, TPEF::Section::addElement(), assert, TPEF::TPEFSectionReader::Header::bodyOffset, TPEF::DebugElement::DE_STAB, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::DebugElement::setDebugString(), TPEF::BinaryStream::setReadPosition(), Conversion::toString(), and type().
type()
Section::SectionType TPEF::TPEFDebugSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 75 of file TPEFDebugSectionReader.cc.
{
    return Section::ST_DEBUG;
}
References TPEF::Section::ST_DEBUG.
Referenced by readData().
Member Data Documentation
proto_
TPEFDebugSectionReader TPEF::TPEFDebugSectionReader::proto_ static private
Prototype instance of TPEFDebugSectionReader to be registered to SectionReader.
Definition at line 63 of file TPEFDebugSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFDebugSectionReader.hh
TPEFDebugSectionReader.cc