OpenASIP: ImplementationSimulator Class Reference
ImplementationSimulator Class Reference abstract
#include <ImplementationSimulator.hh>
Public Member Functions
ImplementationSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
virtual ~ImplementationSimulator ()
virtual bool compile (std::vector< std::string > &errors)=0
virtual bool simulate (std::vector< std::string > &errors)=0
Protected Member Functions
virtual std::string createWorkDir ()
void setWorkDir (std::string dir)
std::string workDir () const
std::string tbDirectory () const
std::string tbFile () const
int hdlFileCount () const
std::string file (int index) const
bool verbose ()
void parseErrorMessages (std::vector< std::string > &inputMsg, std::vector< std::string > &errors)
Private Member Functions
ImplementationSimulator ()
Private Attributes
std::string tbFile_
Testbench file name with path.
std::vector< std::string > hdlFiles_
Vector containing other vhdl files needed to compile testbench.
std::string baseDir_
Directory path of testbench file.
std::string workDir_
Working directory where testbench is compiled and simulated.
std::string oldCwd_
Old current working directory (before changing to workDir_)
bool verbose_
Enable verbose output.
bool leaveDirty_
Don't delete work dir.
Detailed Description
Definition at line 39 of file ImplementationSimulator.hh.
Constructor & Destructor Documentation
ImplementationSimulator() [1/2]
ImplementationSimulator::ImplementationSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
Definition at line 42 of file ImplementationSimulator.cc.
                    :
    tbFile_(tbFile),
    hdlFiles_(hdlFiles), baseDir_(""), workDir_(""), oldCwd_(""),
    verbose_(verbose), leaveDirty_(leaveDirty) {
    baseDir_ = FileSystem::directoryOfPath(tbFile);
    oldCwd_ = FileSystem::currentWorkingDir();
}
References baseDir_, FileSystem::currentWorkingDir(), FileSystem::directoryOfPath(), oldCwd_, and tbFile().
~ImplementationSimulator()
ImplementationSimulator::~ImplementationSimulator () virtual
Definition at line 55 of file ImplementationSimulator.cc.
{
    if (!workDir_.empty() && FileSystem::fileExists(workDir_)) {
        if (!leaveDirty_) {
            FileSystem::removeFileOrDirectory(workDir_);
        }
    }
    if (!oldCwd_.empty()) {
        FileSystem::changeWorkingDir(oldCwd_);
    }
}
References FileSystem::changeWorkingDir(), FileSystem::fileExists(), leaveDirty_, oldCwd_, FileSystem::removeFileOrDirectory(), and workDir_.
ImplementationSimulator() [2/2]
ImplementationSimulator::ImplementationSimulator () private
Member Function Documentation
compile()
virtual bool ImplementationSimulator::compile (std::vector< std::string > & errors) pure virtual
Implemented in GhdlSimulator, and ModelsimSimulator.
Referenced by ImplementationTester::simulateTestbench().
createWorkDir()
std::string ImplementationSimulator::createWorkDir () protected virtual
Reimplemented in ModelsimSimulator.
Definition at line 66 of file ImplementationSimulator.cc.
{
    string work = baseDir_ + FileSystem::DIRECTORY_SEPARATOR + "work";
    if (!FileSystem::createDirectory(work)) {
        work = "";
    }
    workDir_ = work;
    return workDir_;
}
References baseDir_, FileSystem::createDirectory(), FileSystem::DIRECTORY_SEPARATOR, and workDir_.
Referenced by GhdlSimulator::compile().
file()
std::string ImplementationSimulator::file (int index) const protected
Definition at line 95 of file ImplementationSimulator.cc.
{
    return hdlFiles_.at(index);
}
References hdlFiles_.
Referenced by GhdlSimulator::compile(), ModelsimSimulator::compile(), ModelsimSimulator::compileOneFile(), and GhdlSimulator::importFile().
hdlFileCount()
int ImplementationSimulator::hdlFileCount () const protected
Definition at line 91 of file ImplementationSimulator.cc.
{
    return hdlFiles_.size();
}
References hdlFiles_.
Referenced by GhdlSimulator::compile(), and ModelsimSimulator::compile().
parseErrorMessages()
void ImplementationSimulator::parseErrorMessages (std::vector< std::string > & inputMsg, std::vector< std::string > & errors) protected
Definition at line 104 of file ImplementationSimulator.cc.
{
    string tag = "TCE Assert";
    for (unsigned int i = 0; i < inputMsg.size(); i++) {
        string::size_type loc = inputMsg.at(i).find(tag, 0);
        if (loc != string::npos) {
            string errorMsg = FileSystem::fileOfPath(tbFile_) + ": "
                + inputMsg.at(i);
            errors.push_back(errorMsg);
        }
    }
}
References FileSystem::fileOfPath(), and tbFile_.
Referenced by GhdlSimulator::simulate(), and ModelsimSimulator::simulate().
setWorkDir()
void ImplementationSimulator::setWorkDir (std::string dir) protected
Definition at line 75 of file ImplementationSimulator.cc.
{
    workDir_ = dir;
}
References workDir_.
Referenced by ModelsimSimulator::createWorkDir().
simulate()
virtual bool ImplementationSimulator::simulate (std::vector< std::string > & errors) pure virtual
Implemented in GhdlSimulator, and ModelsimSimulator.
Referenced by ImplementationTester::simulateTestbench().
tbDirectory()
std::string ImplementationSimulator::tbDirectory () const protected
Definition at line 83 of file ImplementationSimulator.cc.
{
    return baseDir_;
}
References baseDir_.
Referenced by GhdlSimulator::compile(), ModelsimSimulator::compile(), ModelsimSimulator::createWorkDir(), and GhdlSimulator::simulate().
tbFile()
std::string ImplementationSimulator::tbFile () const protected
Definition at line 87 of file ImplementationSimulator.cc.
{
    return tbFile_;
}
References tbFile_.
Referenced by GhdlSimulator::compile(), ModelsimSimulator::compile(), and ImplementationSimulator().
verbose()
bool ImplementationSimulator::verbose () protected
Definition at line 99 of file ImplementationSimulator.cc.
{
    return verbose_;
}
References verbose_.
Referenced by GhdlSimulator::compileDesign(), ModelsimSimulator::compileOneFile(), ModelsimSimulator::createWorkDir(), GhdlSimulator::importFile(), GhdlSimulator::simulate(), and ModelsimSimulator::simulate().
workDir()
std::string ImplementationSimulator::workDir () const protected
Definition at line 79 of file ImplementationSimulator.cc.
{
    return workDir_;
}
References workDir_.
Referenced by GhdlSimulator::compile(), ModelsimSimulator::compile(), GhdlSimulator::compileDesign(), GhdlSimulator::importFile(), and GhdlSimulator::simulate().
Member Data Documentation
baseDir_
std::string ImplementationSimulator::baseDir_ private
Directory path of testbench file.
Definition at line 82 of file ImplementationSimulator.hh.
Referenced by createWorkDir(), ImplementationSimulator(), and tbDirectory().
hdlFiles_
std::vector<std::string> ImplementationSimulator::hdlFiles_ private
Vector containing other vhdl files needed to compile testbench.
Definition at line 80 of file ImplementationSimulator.hh.
Referenced by file(), and hdlFileCount().
leaveDirty_
bool ImplementationSimulator::leaveDirty_ private
Don't delete work dir.
Definition at line 90 of file ImplementationSimulator.hh.
Referenced by ~ImplementationSimulator().
oldCwd_
std::string ImplementationSimulator::oldCwd_ private
Old current working directory (before changing to workDir_)
Definition at line 86 of file ImplementationSimulator.hh.
Referenced by ImplementationSimulator(), and ~ImplementationSimulator().
tbFile_
std::string ImplementationSimulator::tbFile_ private
Testbench file name with path.
Definition at line 78 of file ImplementationSimulator.hh.
Referenced by parseErrorMessages(), and tbFile().
verbose_
bool ImplementationSimulator::verbose_ private
Enable verbose output.
Definition at line 88 of file ImplementationSimulator.hh.
Referenced by verbose().
workDir_
std::string ImplementationSimulator::workDir_ private
Working directory where testbench is compiled and simulated.
Definition at line 84 of file ImplementationSimulator.hh.
Referenced by createWorkDir(), setWorkDir(), workDir(), and ~ImplementationSimulator().
The documentation for this class was generated from the following files:
ImplementationSimulator.hh
ImplementationSimulator.cc