OpenASIP: TestApplication Class Reference
TestApplication Class Reference
#include <TestApplication.hh>
Public Types
typedef double Runtime
typedef int ClockCycles
Public Member Functions
TestApplication (const std::string &testApplicationPath)
virtual ~TestApplication ()
std::vector< std::string > description () const
bool hasApplication () const
bool hasSetupSimulation () const
bool hasSimulateTTASim () const
bool hasCorrectOutput () const
bool hasVerifySimulation () const
bool hasCleanupSimulation () const
bool hasFunctionsOfInterest () const
bool isValid () const
const std::string applicationPath () const
void setupSimulation () const
std::istream * simulateTTASim () const
const std::string correctOutput () const
bool verifySimulation () const
void cleanupSimulation () const
ClockCycles cycleCount () const
Runtime maxRuntime () const
const std::vector< TCEString > & functionsOfInterest () const
Private Attributes
const std::string testApplicationPath_
Path of the test application directory.
Runtime maxRuntime_
Maximum runtime of the test appication in nano seconds.
std::vector< TCEString > functionsOfInterest_
The names of the functions of interest (in terms of cycle count).
Static Private Attributes
static const std::string DESCRIPTION_FILE_NAME_ = "description.txt"
File name of the description text for the application.
static const std::string APPLICATION_BASE_FILE_NAME_ = "program"
Name of the sequential program file. Base name of the file that contains the fully linked program. The actual file name will be formed by appending either .bc or .ll, whichever is found first.
static const std::string SETUP_FILE_NAME_ = "setup.sh"
Name of the file that contains setup script.
static const std::string SIMULATE_TTASIM_FILE_NAME_ = "simulate.ttasim"
Name of the file that runs the simulation.
static const std::string CORRECT_OUTPUT_FILE_NAME_
Name of the correct simulation output file.
static const std::string VERIFY_FILE_NAME_ = "verify.sh"
Name of the verify script file.
static const std::string CLEANUP_FILE_NAME_ = "cleanup.sh"
Name of the clean up file.
static const std::string FUNCTIONS_OF_INTEREST_FILE_NAME_
Name of the file that has a comma separated list of functions of interest for the cycle count measurements in the given app. The exclusive profile of these functions will be used as the cycle count in evaluation.
static const std::string MAX_RUNTIME_ = "max_runtime"
Name of the file that contains maximum runtime.
static const int MAX_LINE_LENGTH_ = 512
Maximum line length in a file.
Detailed Description
Class for handling files in test application directory.
Definition at line 47 of file TestApplication.hh.
Member Typedef Documentation
ClockCycles
typedef int TestApplication::ClockCycles
Definition at line 50 of file TestApplication.hh.
Runtime
typedef double TestApplication::Runtime
Definition at line 49 of file TestApplication.hh.
Constructor & Destructor Documentation
TestApplication()
TestApplication::TestApplication (const std::string & testApplicationPath)
Constructor.
Parameters
testApplicationPath Path of the test application directory.
Definition at line 62 of file TestApplication.cc.
    : testApplicationPath_(testApplicationPath), maxRuntime_(0) {
    string maxRuntimeFile = testApplicationPath_
        + FileSystem::DIRECTORY_SEPARATOR
        + MAX_RUNTIME_;
    if (FileSystem::fileExists(maxRuntimeFile)) {
        char line[MAX_LINE_LENGTH_];
        FILE* file = fopen(maxRuntimeFile.c_str(), "r");
        if (fgets(line, MAX_LINE_LENGTH_, file) == NULL)
            abort();
        try {
            maxRuntime_ = Conversion::toDouble(line);
        } catch (const NumberFormatException& exception) {
            fclose(file);
            throw IOException(
                __FILE__, __LINE__, __func__, exception.errorMessage());
        }
        fclose(file);
    }
    if (hasFunctionsOfInterest()) {
        std::ifstream f(
            testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
            FUNCTIONS_OF_INTEREST_FILE_NAME_);
        std::string str(
            (std::istreambuf_iterator<char>(f)),
            std::istreambuf_iterator<char>());
        functionsOfInterest_ = TCEString(str).split(",");
    }
}
References __func__, FileSystem::DIRECTORY_SEPARATOR, Exception::errorMessage(), FileSystem::fileExists(), FUNCTIONS_OF_INTEREST_FILE_NAME_, functionsOfInterest_, hasFunctionsOfInterest(), MAX_LINE_LENGTH_, MAX_RUNTIME_, maxRuntime_, TCEString::split(), testApplicationPath_, and Conversion::toDouble().
~TestApplication()
TestApplication::~TestApplication () virtual
Destructor.
Definition at line 96 of file TestApplication.cc.
{
}
Member Function Documentation
applicationPath()
const std::string TestApplication::applicationPath () const
Returns the application path in the test application directory.
If the file 'sequential_program' does not exists returns an empty string.
Returns
The path of the 'sequential_program' file.
Definition at line 335 of file TestApplication.cc.
{
    if (hasApplication()) {
        string applicationBCFile =
            testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
            APPLICATION_BASE_FILE_NAME_ + ".bc";
        string applicationLLFile =
            testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
            APPLICATION_BASE_FILE_NAME_ + ".ll";
        // prioritize the .ll file as it's more portable across
        // LLVM versions than the bitcode
        if (FileSystem::fileExists(applicationLLFile)) {
            return applicationLLFile;
        }
        if (FileSystem::fileExists(applicationBCFile)) {
            return applicationBCFile;
        }
    }
    return "";
}
References APPLICATION_BASE_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), hasApplication(), and testApplicationPath_.
Referenced by DesignSpaceExplorer::evaluate(), and SimpleICOptimizer::explore().
cleanupSimulation()
void TestApplication::cleanupSimulation () const
Cleans up the previous simulation run.
Uses 'cleanup.sh' script if it exists.
Definition at line 220 of file TestApplication.cc.
{
    string cleanupFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        CLEANUP_FILE_NAME_;
    if (FileSystem::fileExists(cleanupFile)) {
        FileSystem::runShellCommand(cleanupFile);
    }
}
References CLEANUP_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), FileSystem::runShellCommand(), and testApplicationPath_.
correctOutput()
const std::string TestApplication::correctOutput () const
Returns the correct output from file 'correct_simulation_output' as string.
Returns
Correct output as string.
Definition at line 152 of file TestApplication.cc.
{
    string correctOutputFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        CORRECT_OUTPUT_FILE_NAME_;
    if (!FileSystem::fileExists(correctOutputFile)) {
        return "";
    }
    std::string buf;
    std::string line;
    std::ifstream in(correctOutputFile.c_str());
    if (std::getline(in,line)) {
        buf += line;
    }
    while(std::getline(in,line)) {
        buf += "\n";
        buf += line;
    }
    return buf;
}
References CORRECT_OUTPUT_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and testApplicationPath_.
Referenced by DesignSpaceExplorer::evaluate().
cycleCount()
ClockCycles TestApplication::cycleCount () const
description()
std::vector< std::string > TestApplication::description () const
Returns the test application description.
The description is given in the description.txt file of the test application directory.
Returns
The test application description. Returns an empty vector if the desctription.txt file was not found.
Definition at line 109 of file TestApplication.cc.
{
    std::vector<string> description;
    string descriptionFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        DESCRIPTION_FILE_NAME_;
    if (FileSystem::fileExists(descriptionFile)) {
        char line[MAX_LINE_LENGTH_];
        FILE* file = fopen(descriptionFile.c_str(), "r");
        while (fgets(line, MAX_LINE_LENGTH_, file)) {
            description.push_back(line);
        }
        fclose(file);
    }
    return description;
}
References description(), DESCRIPTION_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), MAX_LINE_LENGTH_, and testApplicationPath_.
Referenced by description().
functionsOfInterest()
const std::vector< TCEString > & TestApplication::functionsOfInterest () const inline
Definition at line 78 of file TestApplication.hh.
{
        return functionsOfInterest_;
    }
References functionsOfInterest_.
Referenced by DesignSpaceExplorer::evaluate().
hasApplication()
bool TestApplication::hasApplication () const
Returns true if 'sequential_program' file is in the test application directory.
Definition at line 242 of file TestApplication.cc.
{
    string applicationBCFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        APPLICATION_BASE_FILE_NAME_ + ".bc";
    string applicationLLFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        APPLICATION_BASE_FILE_NAME_ + ".ll";
    return FileSystem::fileExists(applicationBCFile) ||
        FileSystem::fileExists(applicationLLFile);
}
References APPLICATION_BASE_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and testApplicationPath_.
Referenced by applicationPath(), and isValid().
hasCleanupSimulation()
bool TestApplication::hasCleanupSimulation () const
Returns true if 'cleanup.sh' file is in the test application directory.
Definition at line 308 of file TestApplication.cc.
{
    string cleanupFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        CLEANUP_FILE_NAME_;
    return FileSystem::fileExists(cleanupFile);
}
References CLEANUP_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and testApplicationPath_.
hasCorrectOutput()
bool TestApplication::hasCorrectOutput () const
Returns true if 'correct_simulation_output' file is in the test application directory.
Definition at line 284 of file TestApplication.cc.
{
    string correctOutputFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        CORRECT_OUTPUT_FILE_NAME_;
    return FileSystem::fileExists(correctOutputFile);
}
References CORRECT_OUTPUT_FILE_NAME_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and testApplicationPath_.
Referenced by DesignSpaceExplorer::evaluate(), and isValid().
hasFunctionsOfInterest()
bool TestApplication::hasFunctionsOfInterest () const
Returns
true if 'functions_of_interest' file is found in the application directory.
Definition at line 321 of file TestApplication.cc.
{
    return FileSystem::fileIsReadable(
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        FUNCTIONS_OF_INTEREST_FILE_NAME_);
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileIsReadable(), FUNCTIONS_OF_INTEREST_FILE_NAME_, and testApplicationPath_.
Referenced by DesignSpaceExplorer::evaluate(), and TestApplication().
hasSetupSimulation()
bool TestApplication::hasSetupSimulation () const
Returns true if 'setup.sh' file is in the test application directory.
Definition at line 259 of file TestApplication.cc.
{
    string setupFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        SETUP_FILE_NAME_;
    return FileSystem::fileExists(setupFile);
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), SETUP_FILE_NAME_, and testApplicationPath_.
hasSimulateTTASim()
bool TestApplication::hasSimulateTTASim () const
Returns true if 'simulate.ttasim' file is in the test application directory.
Definition at line 271 of file TestApplication.cc.
{
    string simulateFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        SIMULATE_TTASIM_FILE_NAME_;
    return FileSystem::fileExists(simulateFile);
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), SIMULATE_TTASIM_FILE_NAME_, and testApplicationPath_.
Referenced by DesignSpaceExplorer::simulate(), and simulateTTASim().
hasVerifySimulation()
bool TestApplication::hasVerifySimulation () const
Returns true if 'verify.sh' file is in the test application directory.
Definition at line 296 of file TestApplication.cc.
{
    string verifyFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        VERIFY_FILE_NAME_;
    return FileSystem::fileExists(verifyFile);
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), testApplicationPath_, and VERIFY_FILE_NAME_.
Referenced by isValid().
isValid()
bool TestApplication::isValid () const inline
Definition at line 64 of file TestApplication.hh.
{
        return hasApplication() &&
            (hasCorrectOutput() || hasVerifySimulation());
    }
References hasApplication(), hasCorrectOutput(), and hasVerifySimulation().
Referenced by main().
maxRuntime()
TestApplication::Runtime TestApplication::maxRuntime () const
Returns the maximum runtime that is set in file "max_runtime".
Definition at line 233 of file TestApplication.cc.
{
    return maxRuntime_;
}
References maxRuntime_.
Referenced by FrequencySweepExplorer::fastEnough(), and MinimizeMachine::minimizeMachine().
setupSimulation()
void TestApplication::setupSimulation () const
Set up the simulation run.
Uses 'setup.sh' to set up the simulation run.
Definition at line 180 of file TestApplication.cc.
{
    string setupFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        SETUP_FILE_NAME_;
    if (FileSystem::fileExists(setupFile)) {
        FileSystem::runShellCommand(setupFile);
    }
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), FileSystem::runShellCommand(), SETUP_FILE_NAME_, and testApplicationPath_.
Referenced by DesignSpaceExplorer::simulate().
simulateTTASim()
std::istream * TestApplication::simulateTTASim () const
Returns a istream to 'simulate.ttasim' file.
Client takes responsibility of destroying the stream.
Returns
istream to 'simulate.ttasim' file.
Definition at line 198 of file TestApplication.cc.
{
    std::ifstream* ifStream = new std::ifstream;
    if (!hasSimulateTTASim()) {
        return ifStream;
    }
    delete ifStream;
    ifStream = NULL;
    string simulateFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        SIMULATE_TTASIM_FILE_NAME_;
    return new std::ifstream(simulateFile.c_str());
}
References FileSystem::DIRECTORY_SEPARATOR, hasSimulateTTASim(), SIMULATE_TTASIM_FILE_NAME_, and testApplicationPath_.
Referenced by DesignSpaceExplorer::simulate().
verifySimulation()
bool TestApplication::verifySimulation () const
Verifies the previous simulation run.
Uses 'verify.sh' to verify the previous simulation run.
Returns
True if the simulation result was verified as correct.
Definition at line 134 of file TestApplication.cc.
{
    string verifyFile =
        testApplicationPath_ + FileSystem::DIRECTORY_SEPARATOR +
        VERIFY_FILE_NAME_;
    if (FileSystem::fileExists(verifyFile)) {
        return FileSystem::runShellCommand(verifyFile);
    }
    return false;
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), FileSystem::runShellCommand(), testApplicationPath_, and VERIFY_FILE_NAME_.
Member Data Documentation
APPLICATION_BASE_FILE_NAME_
const string TestApplication::APPLICATION_BASE_FILE_NAME_ = "program" static private
Name of the sequential program file. Base name of the file that contains the fully linked program. The actual file name will be formed by appending either .bc or .ll, whichever is found first.
Definition at line 96 of file TestApplication.hh.
Referenced by applicationPath(), and hasApplication().
CLEANUP_FILE_NAME_
const string TestApplication::CLEANUP_FILE_NAME_ = "cleanup.sh" static private
Name of the clean up file.
Definition at line 106 of file TestApplication.hh.
Referenced by cleanupSimulation(), and hasCleanupSimulation().
CORRECT_OUTPUT_FILE_NAME_
const string TestApplication::CORRECT_OUTPUT_FILE_NAME_ static private
Initial value:
=
    "correct_simulation_output"
Name of the correct simulation output file.
Definition at line 102 of file TestApplication.hh.
Referenced by correctOutput(), and hasCorrectOutput().
DESCRIPTION_FILE_NAME_
const string TestApplication::DESCRIPTION_FILE_NAME_ = "description.txt" static private
File name of the description text for the application.
Definition at line 91 of file TestApplication.hh.
Referenced by description().
FUNCTIONS_OF_INTEREST_FILE_NAME_
const string TestApplication::FUNCTIONS_OF_INTEREST_FILE_NAME_ static private
Initial value:
=
    "functions_of_interest"
Name of the file that has a comma separated list of functions of interest for the cycle count measurements in the given app. The exclusive profile of these functions will be used as the cycle count in evaluation.
Definition at line 111 of file TestApplication.hh.
Referenced by hasFunctionsOfInterest(), and TestApplication().
functionsOfInterest_
std::vector<TCEString> TestApplication::functionsOfInterest_ private
The names of the functions of interest (in terms of cycle count).
Definition at line 88 of file TestApplication.hh.
Referenced by functionsOfInterest(), and TestApplication().
MAX_LINE_LENGTH_
const int TestApplication::MAX_LINE_LENGTH_ = 512 static private
Maximum line length in a file.
Definition at line 115 of file TestApplication.hh.
Referenced by description(), and TestApplication().
MAX_RUNTIME_
const string TestApplication::MAX_RUNTIME_ = "max_runtime" static private
Name of the file that contains maximum runtime.
Definition at line 113 of file TestApplication.hh.
Referenced by TestApplication().
maxRuntime_
Runtime TestApplication::maxRuntime_ private
Maximum runtime of the test appication in nano seconds.
Definition at line 86 of file TestApplication.hh.
Referenced by maxRuntime(), and TestApplication().
SETUP_FILE_NAME_
const string TestApplication::SETUP_FILE_NAME_ = "setup.sh" static private
Name of the file that contains setup script.
Definition at line 98 of file TestApplication.hh.
Referenced by hasSetupSimulation(), and setupSimulation().
SIMULATE_TTASIM_FILE_NAME_
const string TestApplication::SIMULATE_TTASIM_FILE_NAME_ = "simulate.ttasim" static private
Name of the file that runs the simulation.
Definition at line 100 of file TestApplication.hh.
Referenced by hasSimulateTTASim(), and simulateTTASim().
testApplicationPath_
const std::string TestApplication::testApplicationPath_ private
Path of the test application directory.
Definition at line 84 of file TestApplication.hh.
Referenced by applicationPath(), cleanupSimulation(), correctOutput(), description(), hasApplication(), hasCleanupSimulation(), hasCorrectOutput(), hasFunctionsOfInterest(), hasSetupSimulation(), hasSimulateTTASim(), hasVerifySimulation(), setupSimulation(), simulateTTASim(), TestApplication(), and verifySimulation().
VERIFY_FILE_NAME_
const string TestApplication::VERIFY_FILE_NAME_ = "verify.sh" static private
Name of the verify script file.
Definition at line 104 of file TestApplication.hh.
Referenced by hasVerifySimulation(), and verifySimulation().
The documentation for this class was generated from the following files:
TestApplication.hh
TestApplication.cc