OpenASIP: TTAProgram::TerminalAddress Class Reference
TTAProgram::TerminalAddress Class Reference
#include <TerminalAddress.hh>
Public Member Functions
TerminalAddress (SimValue value, const TTAMachine::AddressSpace &space)
virtual ~TerminalAddress ()
virtual bool isAddress () const
virtual Address address () const
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
Public Member Functions inherited from TTAProgram::TerminalImmediate
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
virtual SimValue value () const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isInstructionAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Private Member Functions
TerminalAddress & operator= (const TerminalAddress &)
Assignment not allowed.
Private Attributes
const TTAMachine::AddressSpace & space_
Address space of the address.
Additional Inherited Members
Protected Attributes inherited from TTAProgram::TerminalImmediate
SimValue value_
Value of the inline immediate.
Detailed Description
Represents an inline immediate that refers to a data address.
Definition at line 48 of file TerminalAddress.hh.
Constructor & Destructor Documentation
TerminalAddress()
TTAProgram::TerminalAddress::TerminalAddress (SimValue value, const TTAMachine::AddressSpace & space)
Constructor. Creates a terminal address from a given immediate value and a reference to an address space.
Parameters
value Value of the address of the location.
space Address space of the address.
Definition at line 47 of file TerminalAddress.cc.
    : TerminalImmediate(value), space_(space) {
}
~TerminalAddress()
TTAProgram::TerminalAddress::~TerminalAddress () virtual
The destructor.
Definition at line 56 of file TerminalAddress.cc.
{
}
Member Function Documentation
address()
Address TTAProgram::TerminalAddress::address () const virtual
Returns the address carried by this terminal.
Returns
An address.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 77 of file TerminalAddress.cc.
{
    return Address(value_.unsignedValue(), space_);
}
References space_, SimValue::unsignedValue(), and TTAProgram::TerminalImmediate::value_.
Referenced by equals().
copy()
Terminal * TTAProgram::TerminalAddress::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 87 of file TerminalAddress.cc.
{
    return new TerminalAddress(TerminalImmediate::value(), space_);
}
References space_, and TTAProgram::TerminalImmediate::value().
equals()
bool TTAProgram::TerminalAddress::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 98 of file TerminalAddress.cc.
{
    if (other.isAddress() != true) {
        return false;
    }
    return (address().location() == other.address().location() &&
            address().space().name() == other.address().space().name());
}
References TTAProgram::Terminal::address(), address(), TTAProgram::Terminal::isAddress(), TTAProgram::Address::location(), TTAMachine::Component::name(), and TTAProgram::Address::space().
isAddress()
bool TTAProgram::TerminalAddress::isAddress () const virtual
Tells whether the terminal is an inline immediate that refers to an address.
Returns
true always.
Reimplemented from TTAProgram::Terminal.
Definition at line 66 of file TerminalAddress.cc.
{
    return true;
}
operator=()
TerminalAddress & TTAProgram::TerminalAddress::operator= (const TerminalAddress &) private
Assignment not allowed.
Member Data Documentation
space_
const TTAMachine::AddressSpace& TTAProgram::TerminalAddress::space_ private
Address space of the address.
Definition at line 61 of file TerminalAddress.hh.
Referenced by address(), and copy().
The documentation for this class was generated from the following files:
TerminalAddress.hh
TerminalAddress.cc