OpenASIP: OSEdPropertiesCmd Class Reference
OSEdPropertiesCmd Class Reference
#include <OSEdPropertiesCmd.hh>
Public Member Functions
OSEdPropertiesCmd ()
virtual ~OSEdPropertiesCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdPropertiesCmd (const OSEdPropertiesCmd &)
Copying not allowed.
OSEdPropertiesCmd & operator= (const OSEdPropertiesCmd &)
Assignment not allowed.
Detailed Description
Executes the command when operation is modified.
Definition at line 43 of file OSEdPropertiesCmd.hh.
Constructor & Destructor Documentation
OSEdPropertiesCmd() [1/2]
OSEdPropertiesCmd::OSEdPropertiesCmd ()
Constructor.
Definition at line 62 of file OSEdPropertiesCmd.cc.
                                     :
    GUICommand(OSEdConstants::CMD_NAME_PROPERTIES, NULL) {
}
Referenced by create().
~OSEdPropertiesCmd()
OSEdPropertiesCmd::~OSEdPropertiesCmd () virtual
Destructor.
Definition at line 69 of file OSEdPropertiesCmd.cc.
{
}
OSEdPropertiesCmd() [2/2]
OSEdPropertiesCmd::OSEdPropertiesCmd (const OSEdPropertiesCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdPropertiesCmd::create () const virtual
Creates a new command.
Returns
The created command.
Implements GUICommand.
Definition at line 88 of file OSEdPropertiesCmd.cc.
{
    return new OSEdPropertiesCmd();
}
References OSEdPropertiesCmd().
Do()
bool OSEdPropertiesCmd::Do () virtual
Executes the command.
Returns
True if execution is successful, false otherwise.
Implements GUICommand.
Definition at line 98 of file OSEdPropertiesCmd.cc.
                      {
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTreeView* treeView = mainFrame->treeView();
    Operation* op = treeView->selectedOperation();
    string opName = op->name();
    wxTreeItemId opId = treeView->selectedOperationId();
    string modName = treeView->moduleOfOperation(opId);
    wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
    string pathName = treeView->pathOfModule(modId);
    OperationModule& module = OperationContainer::module(pathName, modName);
    assert(&module != &NullOperationModule::instance());
    if (!FileSystem::fileIsWritable(module.propertiesModule())) {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_CAN_NOT_MODIFY);
        ErrorDialog error(parentWindow(), WxConversion::toWxString(fmt.str()));
        error.ShowModal();
        delete op;
        return false;
    } else {
        OperationPropertyDialog dialog(parentWindow(), op, module, pathName);
        ObjectState* orig = op->saveState();
        if (dialog.ShowModal() == wxID_OK) {
            ObjectState* mod = op->saveState();
            if (*mod != *orig) {
                // write operation properties to file
                OperationSerializer& serializer =
                    OperationContainer::operationSerializer();
                serializer.setSourceFile(module.propertiesModule());
                ObjectState* root = NULL;
                try {
                    root = serializer.readState();
                    for (int i = 0; i < root->childCount(); i++) {
                        ObjectState* child = root->child(i);
                        if (child->stringAttribute("name") == opName) {
                            root->replaceChild(child, op->saveState());
                            break;
                        }
                    }
                    serializer.setDestinationFile(module.propertiesModule());
                    serializer.writeState(root);
                } catch (const Exception& s) {
                    format fmt =
                        texts.text(OSEdTextGenerator::TXT_ERROR_CAN_NOT_MODIFY);
                    ErrorDialog eDialog(
                        parentWindow(), WxConversion::toWxString(fmt.str()));
                    eDialog.ShowModal();
                }
                delete root;
                // update the tree.
                if (opName != op->name()) {
                    OperationIndex& index = OperationContainer::operationIndex();
                    index.refreshModule(pathName, modName);
                    treeView->changeText(opId, op->name());
                }
                treeView->update();
            }
            delete mod;
        }
        delete orig;
        delete op;
        return true;
    }
    assert(false);
    return false;
}
References assert, OSEdTreeView::changeText(), ObjectState::child(), ObjectState::childCount(), FileSystem::fileIsWritable(), NullOperationModule::instance(), OSEdTextGenerator::instance(), OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::moduleOfOperation(), Operation::name(), OperationContainer::operationIndex(), OperationContainer::operationSerializer(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OperationSerializer::readState(), OperationIndex::refreshModule(), ObjectState::replaceChild(), Operation::saveState(), OSEdTreeView::selectedOperation(), OSEdTreeView::selectedOperationId(), OperationSerializer::setDestinationFile(), OperationSerializer::setSourceFile(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdMainFrame::treeView(), OSEdTextGenerator::TXT_ERROR_CAN_NOT_MODIFY, OSEdTreeView::update(), and OperationSerializer::writeState().
icon()
string OSEdPropertiesCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 194 of file OSEdPropertiesCmd.cc.
{
    return "";
}
id()
int OSEdPropertiesCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 78 of file OSEdPropertiesCmd.cc.
{
    return OSEdConstants::CMD_PROPERTIES;
}
References OSEdConstants::CMD_PROPERTIES.
isEnabled()
bool OSEdPropertiesCmd::isEnabled () virtual
Returns true, if command is enabled.
Returns
True, if command is enabled.
Implements GUICommand.
Definition at line 177 of file OSEdPropertiesCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    Operation* op = treeView->selectedOperation();
    if (op != NULL) {
        delete op;
        return true;
    } else {
        return false;
    }
}
References OSEdTreeView::selectedOperation().
operator=()
OSEdPropertiesCmd & OSEdPropertiesCmd::operator= (const OSEdPropertiesCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdPropertiesCmd.hh
OSEdPropertiesCmd.cc