OpenASIP: FUGuardDialog Class Reference
FUGuardDialog Class Reference
#include <FUGuardDialog.hh>
Public Member Functions
FUGuardDialog (wxWindow *parent, TTAMachine::Bus *bus, TTAMachine::PortGuard *guard=NULL)
virtual ~FUGuardDialog ()
virtual bool TransferDataToWindow ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_LABEL_PORT , ID_FU_NAME , ID_FU_PORT ,
ID_INVERTED , ID_HELP , ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onFUChoice (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
TTAMachine::FunctionUnit * selectedFU () const
TTAMachine::FUPort * selectedPort () const
void setTexts ()
Private Attributes
wxChoice * nameChoice_
Choice widget for the function unit selection.
wxChoice * portChoice_
Choice widget for the port selection.
wxCheckBox * invertedBox_
Checkbox widget for the inverted flag.
bool inverted_
Inverted flag for the guard.
bool newInverted_
Modified inverted flag.
TTAMachine::FUPort * port_
Port of the guard.
TTAMachine::Bus * bus_
Parent bus of the guard.
bool adding_
True if a new guard is being added, false otherwise.
Detailed Description
Dialog for editing function unit port guard properties.
Definition at line 47 of file FUGuardDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LABEL_NAME
ID_LABEL_PORT
ID_FU_NAME
ID_FU_PORT
ID_INVERTED
ID_HELP
ID_LINE
Definition at line 84 of file FUGuardDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_LABEL_PORT,
        ID_FU_NAME,
        ID_FU_PORT,
        ID_INVERTED,
        ID_HELP,
        ID_LINE
    };
Constructor & Destructor Documentation
FUGuardDialog()
FUGuardDialog::FUGuardDialog (wxWindow * parent, TTAMachine::Bus * bus, TTAMachine::PortGuard * guard = NULL)
The Constructor.
Parameters
parent Parent window of the dialog.
guard Port guard to edit.
Definition at line 65 of file FUGuardDialog.cc.
                      :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    inverted_(false),
    newInverted_(false),
    port_(NULL),
    bus_(bus),
    adding_(false) {
    if (guard == NULL) {
        // adding a new guard
        adding_ = true;
        Machine::FunctionUnitNavigator navigator =
            bus_->machine()->functionUnitNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            if (navigator.item(i)->operationPortCount() > 0) {
                port_ = navigator.item(i)->operationPort(0);
                break;
            }
        }
        assert(port_ != NULL);
    } else {
        // editing an old guard
        port_ = guard->port();
        inverted_ = guard->isInverted();
        newInverted_ = inverted_;
        bus_ = guard->parentBus();
        // The guard is temporarily deleted to simplify legality checks.
        delete guard;
        guard = NULL;
    }
    createContents(this, true, true);
    // set pointers to the dialog widgets
    nameChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_FU_NAME));
    portChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_FU_PORT));
    invertedBox_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_INVERTED));
    invertedBox_->SetValidator(wxGenericValidator(&newInverted_));
    // set widget texts.
    setTexts();
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::count(), and TTAMachine::Machine::Navigator< ComponentType >::item().
~FUGuardDialog()
FUGuardDialog::~FUGuardDialog () virtual
The Destructor.
Definition at line 122 of file FUGuardDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FUGuardDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window.
Code generated with wxDesigner.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 320 of file FUGuardDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxGridSizer *item1 = new wxGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Function Unit Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxChoice *item3 = new wxChoice( parent, ID_FU_NAME, wxDefaultPosition, wxSize(100,-1), 0, strs3, 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_PORT, wxT("Port Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_FU_PORT, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxCheckBox *item6 = new wxCheckBox( parent, ID_INVERTED, wxT("Inverted"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item6, 0, wxALL, 5 );
    wxStaticLine *item7 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_FU_NAME, ID_FU_PORT, ID_HELP, ID_INVERTED, ID_LABEL_NAME, ID_LABEL_PORT, and ID_LINE.
onCancel()
void FUGuardDialog::onCancel (wxCommandEvent & event) private
Cancels the dialog effects by creating the original port guard.
Closes the Dialog.
Definition at line 301 of file FUGuardDialog.cc.
{
    if (adding_ == false) {
        new PortGuard(inverted_, *port_, *bus_);
    }
    EndModal(wxID_CANCEL);
}
References adding_, bus_, inverted_, and port_.
onFUChoice()
void FUGuardDialog::onFUChoice (wxCommandEvent & event) private
Updates the port choice when the function unit selection is changed.
Definition at line 208 of file FUGuardDialog.cc.
{
    wxString selection = portChoice_->GetStringSelection();
    portChoice_->Clear();
    FunctionUnit* fu = selectedFU();
    for (int i = 0; i < fu->portCount(); i++) {
        wxString name = WxConversion::toWxString(fu->port(i)->name());
        portChoice_->Append(name);
    }
    if (portChoice_->FindString(selection) >= 0) {
        portChoice_->SetStringSelection(selection);
    } else {
        portChoice_->SetSelection(0);
    }
}
References TTAMachine::Port::name(), TTAMachine::FunctionUnit::port(), portChoice_, TTAMachine::Unit::portCount(), selectedFU(), and WxConversion::toWxString().
onOK()
void FUGuardDialog::onOK (wxCommandEvent & event) private
Updates the guard object when the OK-button is pressed.
Closes the dialog.
Definition at line 266 of file FUGuardDialog.cc.
{
    FUPort* port = selectedPort();
    if (port == NULL) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message = prodeTexts->text(ProDeTextGenerator::MSG_ERROR);
        InformationDialog dialog(
            this, WxConversion::toWxString(
                message.str() + "Select a port.\n"));
        dialog.ShowModal();
        return;
    }
    TransferDataFromWindow();
    try {
        new PortGuard(newInverted_, *port, *bus_);
    } catch (ComponentAlreadyExists& e) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_GUARD_EXISTS);
        InformationDialog dialog(
            this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
        return;
    }
    EndModal(wxID_OK);
}
References bus_, ProDeTextGenerator::instance(), ProDeTextGenerator::MSG_ERROR, ProDeTextGenerator::MSG_ERROR_GUARD_EXISTS, newInverted_, selectedPort(), Texts::TextGenerator::text(), and WxConversion::toWxString().
selectedFU()
FunctionUnit * FUGuardDialog::selectedFU () const private
Returns a pointer to the selected function unit.
Returns
Pointer to the selected function unit.
Definition at line 234 of file FUGuardDialog.cc.
{
    string name = WxConversion::toString(nameChoice_->GetStringSelection());
    Machine::FunctionUnitNavigator navigator =
        bus_->machine()->functionUnitNavigator();
    FunctionUnit* fu = navigator.item(name);
    return fu;
}
References bus_, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), nameChoice_, and WxConversion::toString().
Referenced by onFUChoice(), and selectedPort().
selectedPort()
FUPort * FUGuardDialog::selectedPort () const private
Returns a pointer to the selected function unit port.
Returns
Pointer to the selected function unit port.
Definition at line 249 of file FUGuardDialog.cc.
{
    string name = WxConversion::toString(portChoice_->GetStringSelection());
    if (name == "") {
        return NULL;
    }
    FUPort* port = selectedFU()->operationPort(name);
    return port;
}
References TTAMachine::FunctionUnit::operationPort(), portChoice_, selectedFU(), and WxConversion::toString().
Referenced by onOK().
setTexts()
void FUGuardDialog::setTexts () private
Sets texts for widgets.
Definition at line 130 of file FUGuardDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_FU_GUARD_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_FU_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_PORT),
                          ProDeTextGenerator::TXT_LABEL_PORT_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_INVERTED),
                          ProDeTextGenerator::TXT_LABEL_INVERTED);
}
References ID_HELP, ID_INVERTED, ID_LABEL_NAME, ID_LABEL_PORT, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_FU_GUARD_DIALOG_TITLE, ProDeTextGenerator::TXT_LABEL_FU_NAME, ProDeTextGenerator::TXT_LABEL_INVERTED, and ProDeTextGenerator::TXT_LABEL_PORT_NAME.
TransferDataToWindow()
bool FUGuardDialog::TransferDataToWindow () virtual
Transfers data from the guard object to the dialog widgets.
Returns
true, if the transfer was succesful, false otherwise.
Definition at line 167 of file FUGuardDialog.cc.
{
    nameChoice_->Clear();
    portChoice_->Clear();
    Machine::FunctionUnitNavigator navigator =
        bus_->machine()->functionUnitNavigator();
    // add function units and set selection
    for (int i = 0; i < navigator.count(); i++) {
        wxString name = WxConversion::toWxString(navigator.item(i)->name());
        nameChoice_->Append(name);
    }
    nameChoice_->SetStringSelection(
        WxConversion::toWxString(port_->parentUnit()->name()));
    // add function unit ports and set selection
    for (int i = 0; i < port_->parentUnit()->portCount(); i++) {
        // port must be output port
        if (port_->parentUnit()->port(i)->outputSocket() == NULL) {
            continue;
        }
        wxString name =
            WxConversion::toWxString(port_->parentUnit()->port(i)->name());
        portChoice_->Append(name);
    }
    portChoice_->SetStringSelection(WxConversion::toWxString(port_->name()));
    // set inverted checkbox
    invertedBox_->SetValue(newInverted_);
    return wxDialog::TransferDataToWindow();
}
References bus_, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), invertedBox_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::Port::name(), nameChoice_, newInverted_, TTAMachine::Port::outputSocket(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::FunctionUnit::port(), port_, portChoice_, and WxConversion::toWxString().
Member Data Documentation
adding_
bool FUGuardDialog::adding_ private
True if a new guard is being added, false otherwise.
Definition at line 81 of file FUGuardDialog.hh.
Referenced by onCancel().
bus_
TTAMachine::Bus* FUGuardDialog::bus_ private
Parent bus of the guard.
Definition at line 79 of file FUGuardDialog.hh.
Referenced by onCancel(), onOK(), selectedFU(), and TransferDataToWindow().
inverted_
bool FUGuardDialog::inverted_ private
Inverted flag for the guard.
Definition at line 73 of file FUGuardDialog.hh.
Referenced by onCancel().
invertedBox_
wxCheckBox* FUGuardDialog::invertedBox_ private
Checkbox widget for the inverted flag.
Definition at line 70 of file FUGuardDialog.hh.
Referenced by TransferDataToWindow().
nameChoice_
wxChoice* FUGuardDialog::nameChoice_ private
Choice widget for the function unit selection.
Definition at line 66 of file FUGuardDialog.hh.
Referenced by selectedFU(), and TransferDataToWindow().
newInverted_
bool FUGuardDialog::newInverted_ private
Modified inverted flag.
Definition at line 75 of file FUGuardDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
port_
TTAMachine::FUPort* FUGuardDialog::port_ private
Port of the guard.
Definition at line 77 of file FUGuardDialog.hh.
Referenced by onCancel(), and TransferDataToWindow().
portChoice_
wxChoice* FUGuardDialog::portChoice_ private
Choice widget for the port selection.
Definition at line 68 of file FUGuardDialog.hh.
Referenced by onFUChoice(), selectedPort(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
FUGuardDialog.hh
FUGuardDialog.cc