OpenASIP: CostDBEntry Class Reference
CostDBEntry Class Reference
#include <CostDBEntry.hh>
Public Member Functions
CostDBEntry (CostDBEntryKey *key)
CostDBEntry (const CostDBEntry &entry1, const CostDBEntry &entry2, const EntryKeyField &weighter)
virtual ~CostDBEntry ()
CostDBEntry * copy () const
EntryKeyField keyFieldOfType (const EntryKeyFieldProperty &type) const
EntryKeyField keyFieldOfType (std::string type) const
const EntryKeyProperty * type () const
void replaceField (EntryKeyField *newField)
int fieldCount () const
const EntryKeyField & field (int index) const
bool isEqualKey (const CostDBEntry &entry) const
void addStatistics (CostDBEntryStats *newStats)
int statisticsCount () const
const CostDBEntryStats & statistics (int index) const
Private Types
typedef std::vector< CostDBEntryStats * > StatsTable
Type definition for a table of statistics.
Private Member Functions
CostDBEntry (const CostDBEntry &)
Copying not allowed.
CostDBEntry & operator= (const CostDBEntry &)
Assignment not allowed.
Private Attributes
CostDBEntryKey * entryKey_
Key of the entry.
StatsTable entryStats_
Statistics of the entry.
Detailed Description
Represents an entry containing a key and statistics.
Key means the properties of an entry that are used as a search key.
Definition at line 52 of file CostDBEntry.hh.
Member Typedef Documentation
StatsTable
typedef std::vector<CostDBEntryStats*> CostDBEntry::StatsTable private
Type definition for a table of statistics.
Definition at line 77 of file CostDBEntry.hh.
Constructor & Destructor Documentation
CostDBEntry() [1/3]
CostDBEntry::CostDBEntry (CostDBEntryKey * key)
Constructor.
Parameters
key An entry key.
Definition at line 44 of file CostDBEntry.cc.
                                            :
    entryKey_(key) {
}
CostDBEntry() [2/3]
CostDBEntry::CostDBEntry (const CostDBEntry & entry1, const CostDBEntry & entry2, const EntryKeyField & weighter)
Constructor.
Combines two entries into one using weighter as a weighting factor on interpolating the statistics. Also replacing weighter field in entry key.
Parameters
entry1 First entry.
entry2 Second entry.
weighter A field.
Definition at line 59 of file CostDBEntry.cc.
{
    EntryKeyField field1 = entry1.keyFieldOfType(*weighter.type());
    EntryKeyField field2 = entry2.keyFieldOfType(*weighter.type());
    double coefficient = weighter.coefficient(field1, field2);
    entryKey_ = entry1.entryKey_->copy();
    entryKey_->replaceField(new EntryKeyField(weighter));
    for (StatsTable::const_iterator i = entry1.entryStats_.begin();
         i != entry1.entryStats_.end(); i++) {
        for (StatsTable::const_iterator j = entry2.entryStats_.begin();
             j != entry2.entryStats_.end(); j++) {
            // newStats cannot be base class type if stats are for FU or RF
            if (dynamic_cast<CostDBEntryStatsRF*>(*i) &&
                dynamic_cast<CostDBEntryStatsRF*>(*j)) {
                CostDBEntryStatsRF* newStats = new CostDBEntryStatsRF(
                    *dynamic_cast<CostDBEntryStatsRF*>(*i),
                    *dynamic_cast<CostDBEntryStatsRF*>(*j), coefficient);
                addStatistics(newStats);
            } else if (dynamic_cast<CostDBEntryStatsFU*>(*i) &&
                       dynamic_cast<CostDBEntryStatsFU*>(*j)) {
                CostDBEntryStatsFU* newStats = new CostDBEntryStatsFU(
                    *dynamic_cast<CostDBEntryStatsFU*>(*i),
                    *dynamic_cast<CostDBEntryStatsFU*>(*j), coefficient);
                addStatistics(newStats);
            } else { // if the entry is Bus or Socket
                CostDBEntryStats* newStats =
                    new CostDBEntryStats(*(*i), *(*j), coefficient);
                addStatistics(newStats);
            }
        }
    }
}
References addStatistics(), EntryKeyField::coefficient(), CostDBEntryKey::copy(), entryKey_, entryStats_, keyFieldOfType(), CostDBEntryKey::replaceField(), and EntryKeyField::type().
~CostDBEntry()
CostDBEntry::~CostDBEntry () virtual
Destructor.
Definition at line 99 of file CostDBEntry.cc.
{
    assert(entryKey_ != NULL);
    delete entryKey_;
    entryKey_ = NULL;
    for (StatsTable::iterator i = entryStats_.begin();
         i != entryStats_.end(); i++) {
        assert(*i != NULL);
        delete *i;
    }
}
References assert, entryKey_, and entryStats_.
CostDBEntry() [3/3]
CostDBEntry::CostDBEntry (const CostDBEntry &) private
Copying not allowed.
Member Function Documentation
addStatistics()
void CostDBEntry::addStatistics (CostDBEntryStats * newStats)
Add new statistics into this entry.
Parameters
newStats Statistics to be added.
Definition at line 213 of file CostDBEntry.cc.
{
    entryStats_.push_back(newStats);
}
References entryStats_.
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), copy(), and CostDBEntry().
copy()
CostDBEntry * CostDBEntry::copy () const
Copies the entry.
Client is responsible of deallocating the memory reserved for the returned object.
Returns
A copy of the entry.
Definition at line 120 of file CostDBEntry.cc.
{
    CostDBEntry* newEntry = new CostDBEntry(entryKey_->copy());
    for (StatsTable::const_iterator i = entryStats_.begin();
         i != entryStats_.end(); i++) {
        newEntry->addStatistics((*i)->copy());
    }
    return newEntry;
}
References addStatistics(), CostDBEntryKey::copy(), entryKey_, and entryStats_.
field()
const EntryKeyField & CostDBEntry::field (int index) const
Returns the field found on the given index.
The index must be between 0 and the number of entry key - 1.
Parameters
index Index.
Returns
The field found on the given index.
Definition at line 182 of file CostDBEntry.cc.
{
    return entryKey_->field(index);
}
References entryKey_, and CostDBEntryKey::field().
Referenced by Matcher::onlyThisFieldDiffers().
fieldCount()
int CostDBEntry::fieldCount () const
Returns the number of fields in an entry.
Returns
The number of fields in an entry.
Definition at line 169 of file CostDBEntry.cc.
{
    return entryKey_->fieldCount();
}
References entryKey_, and CostDBEntryKey::fieldCount().
Referenced by Matcher::onlyThisFieldDiffers().
isEqualKey()
bool CostDBEntry::isEqualKey (const CostDBEntry & entry) const
Checks whether two entries have equal key.
Parameters
entry Database entry to compare with.
Returns
True if two entries have equal key, false otherwise.
Definition at line 203 of file CostDBEntry.cc.
{
    return entryKey_->isEqual(*entry.entryKey_);
}
References entryKey_, and CostDBEntryKey::isEqual().
keyFieldOfType() [1/2]
EntryKeyField CostDBEntry::keyFieldOfType (const EntryKeyFieldProperty & type) const
Returns demanded field of the entry.
Parameters
type Type of the field.
Returns
Demanded entry field.
Definition at line 148 of file CostDBEntry.cc.
{
    return entryKey_->keyFieldOfType(type);
}
References entryKey_, CostDBEntryKey::keyFieldOfType(), and type().
Referenced by CostDBEntry(), and Matcher::onlyThisFieldDiffers().
keyFieldOfType() [2/2]
EntryKeyField CostDBEntry::keyFieldOfType (std::string type) const
Returns demanded field of the entry.
Parameters
type Type of the field.
Returns
Demanded entry field.
Definition at line 159 of file CostDBEntry.cc.
{
    return entryKey_->keyFieldOfType(type);
}
References entryKey_, CostDBEntryKey::keyFieldOfType(), and type().
operator=()
CostDBEntry & CostDBEntry::operator= (const CostDBEntry &) private
Assignment not allowed.
replaceField()
void CostDBEntry::replaceField (EntryKeyField * newField)
Replaces certain field of the entry.
Parameters
newField A field.
Definition at line 192 of file CostDBEntry.cc.
{
    entryKey_->replaceField(newField);
}
References entryKey_, and CostDBEntryKey::replaceField().
statistics()
const CostDBEntryStats & CostDBEntry::statistics (int index) const
Returns the statistics according to given index.
Parameters
index The index of the statistics.
Returns
The statistics according to given index.
Exceptions
OutOfRange Index is out of bounds.
Definition at line 236 of file CostDBEntry.cc.
{
    if (index < 0 || index >= statisticsCount()) {
    throw OutOfRange(__FILE__, __LINE__, "CostDBEntry::statistics");
    }
    return *entryStats_[index];
}
References entryStats_, and statisticsCount().
Referenced by CostDatabase::insertEntry().
statisticsCount()
int CostDBEntry::statisticsCount () const
Returns the number of statistics in the entry.
Returns
Number of statistics in the entry.
Definition at line 224 of file CostDBEntry.cc.
{
    return entryStats_.size();
}
References entryStats_.
Referenced by CostDatabase::insertEntry(), and statistics().
type()
const EntryKeyProperty * CostDBEntry::type () const
Returns type of the entry.
Returns
Type.
Definition at line 137 of file CostDBEntry.cc.
{
    return entryKey_->type();
}
References entryKey_, and CostDBEntryKey::type().
Referenced by CostDatabase::insertEntry(), keyFieldOfType(), and keyFieldOfType().
Member Data Documentation
entryKey_
CostDBEntryKey* CostDBEntry::entryKey_ private
Key of the entry.
Definition at line 80 of file CostDBEntry.hh.
Referenced by copy(), CostDBEntry(), field(), fieldCount(), isEqualKey(), keyFieldOfType(), keyFieldOfType(), replaceField(), type(), and ~CostDBEntry().
entryStats_
StatsTable CostDBEntry::entryStats_ private
Statistics of the entry.
Definition at line 82 of file CostDBEntry.hh.
Referenced by addStatistics(), copy(), CostDBEntry(), statistics(), statisticsCount(), and ~CostDBEntry().
The documentation for this class was generated from the following files:
CostDBEntry.hh
CostDBEntry.cc