OpenASIP: ControlDependenceGraphPass Class Reference
ControlDependenceGraphPass Class Reference abstract
#include <ControlDependenceGraphPass.hh>
Public Member Functions
ControlDependenceGraphPass (InterPassData &data)
virtual ~ControlDependenceGraphPass ()
virtual void handleControlDependenceGraph (ControlDependenceGraph &cdg, const TTAMachine::Machine &targetMachine)=0
Public Member Functions inherited from SchedulerPass
SchedulerPass (InterPassData &data)
virtual ~SchedulerPass ()
InterPassData & interPassData ()
virtual std::string shortDescription () const =0
virtual std::string longDescription () const
Detailed Description
Interface for scheduler passes that handle control dependence graphs.
Definition at line 55 of file ControlDependenceGraphPass.hh.
Constructor & Destructor Documentation
ControlDependenceGraphPass()
ControlDependenceGraphPass::ControlDependenceGraphPass (InterPassData & data)
Constructor.
Definition at line 47 of file ControlDependenceGraphPass.cc.
                                                                          :
    SchedulerPass(data) {
}
~ControlDependenceGraphPass()
ControlDependenceGraphPass::~ControlDependenceGraphPass () virtual
Destructor.
Definition at line 54 of file ControlDependenceGraphPass.cc.
{
}
Member Function Documentation
handleControlDependenceGraph()
void ControlDependenceGraphPass::handleControlDependenceGraph (ControlDependenceGraph & cdg, const TTAMachine::Machine & targetMachine) pure virtual
Handles a single control dependence graph.
The pass should work with any kind of control dependence graph, it should not assume the CDG represents a whole procedure, for example.
Parameters
cdg The control dependence graph to handle.
machine The target machine if any. (NullMachine::instance() if target machine is irrelevant).
Exceptions
In case handling is unsuccesful for any reason (cdg might still get modified).
Definition at line 70 of file ControlDependenceGraphPass.cc.
{
    //Trivial handling so far, just compute analysis info for serialization
    // Throws exception in case there is indirect jump
    cdg.nodeCount();
    try {
        cdg.analyzeCDG();
    } catch (const InvalidData& e) {
        // CFG had indirect jump
    } catch (const Exception& e) {
        throw ModuleRunTimeError(
            __FILE__, __LINE__, __func__, e.errorMessageStack());
    }
    targetMachine.machineTester();
}
References __func__, ControlDependenceGraph::analyzeCDG(), Exception::errorMessageStack(), TTAMachine::Machine::machineTester(), and BoostGraph< GraphNode, GraphEdge >::nodeCount().
The documentation for this class was generated from the following files:
ControlDependenceGraphPass.hh
ControlDependenceGraphPass.cc