OpenASIP: TTAMachine::Machine::Navigator< ComponentType > Class Template Reference
TTAMachine::Machine::Navigator< ComponentType > Class Template Reference
#include <Machine.hh>
Public Types
typedef Machine::ComponentContainer< ComponentType >::const_iterator const_iterator
Public Member Functions
Navigator (const Machine::ComponentContainer< ComponentType > &container)
~Navigator ()
Navigator (const Navigator &old)
Navigator & operator= (const Navigator &old)
ComponentType * item (int index) const
ComponentType * item (const std::string &name) const
bool hasItem (const std::string &name) const
int count () const
const_iterator begin () const noexcept
const_iterator end () const noexcept
Private Attributes
const Machine::ComponentContainer< ComponentType > * container_
The container which this navigator handles.
Detailed Description
template<typename ComponentType>
class TTAMachine::Machine::Navigator< ComponentType >
A template class which is a handle to a ComponentContainer.
An instance of this class is intended to return outside the Machine class to allow clients to access individual components in Machine.
Definition at line 186 of file Machine.hh.
Member Typedef Documentation
const_iterator
template<typename ComponentType > typedef Machine::ComponentContainer<ComponentType>::const_iterator TTAMachine::Machine::Navigator< ComponentType >::const_iterator
Definition at line 202 of file Machine.hh.
Constructor & Destructor Documentation
Navigator() [1/2]
template<typename ComponentType > TTAMachine::Machine::Navigator< ComponentType >::Navigator (const Machine::ComponentContainer< ComponentType > & container)
~Navigator()
template<typename ComponentType > TTAMachine::Machine::Navigator< ComponentType >::~Navigator ()
Navigator() [2/2]
template<typename ComponentType > TTAMachine::Machine::Navigator< ComponentType >::Navigator (const Navigator< ComponentType > & old)
Member Function Documentation
begin()
template<typename ComponentType > const_iterator TTAMachine::Machine::Navigator< ComponentType >::begin () const noexcept
Referenced by MachineResourceModifier::removeNotConnectedSockets().
count()
template<typename ComponentType > int TTAMachine::Machine::Navigator< ComponentType >::count () const
Referenced by ADFCombiner::addAddressSpaces(), ADFCombiner::addAllGuardsToConnectionBuses(), ADFCombiner::addBuses(), llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), BEMGenerator::addEncodings(), ADFCombiner::addFunctionUnits(), DefaultDecoderGenerator::addGlockPortToDecoder(), DefaultICGenerator::addICToNetlist(), DefaultDecoderGenerator::addLockReqPortToDecoder(), BEMGenerator::addLongImmDstRegisterFields(), ADFCombiner::addRegisterFiles(), ComponentAdder::addRegisterFiles(), TTAMachine::AddressSpace::AddressSpace(), llvm::LLVMTCEBuilder::addressSpaceById(), BEMGenerator::addSocketCodeTables(), ImmediateGenerator::addSplitInsTemplate(), BEMGenerator::addTopLevelFields(), TTAMachine::Bridge::adjustChainDirection(), MachineResourceModifier::analyzeBuses(), MachineResourceModifier::analyzeFunctionUnits(), TDGen::analyzeMachineRegisters(), ResourceConstraintAnalyzer::analyzeMoveNode(), TDGen::analyzeRegisters(), MachineResourceModifier::analyzeRegisters(), FullyConnectedCheck::attachSocketToAllBusses(), SimulationController::buildFUResourceConflictDetectors(), MachineStateBuilder::buildMachineState(), ControlFlowGraph::buildMBBFromBB(), MinimalOpSetCheck::buildMinimalOpSet(), BusBroker::buildResources(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), InputPSocketBroker::buildResources(), ITemplateBroker::buildResources(), IUBroker::buildResources(), OutputFUBroker::buildResources(), OutputPSocketBroker::buildResources(), MachineConnectivityCheck::busConnectedToAnyFU(), DefaultICDecoderEstimator::busParameters(), MachineInfo::canEncodeImmediateInteger(), FullyConnectedCheck::canFix(), RegisterQuantityCheck::canFixIntRegs(), MachineConnectivityCheck::canWriteAllImmediates(), FullyConnectedCheck::check(), AddressSpaceCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), RFPortCheck::check(), MinimalOpSetCheck::check(), MinimalOpSetCheck::check(), ProgrammabilityValidator::checkBooleanRegister(), RemoveUnconnectedComponents::checkBuses(), MachineValidator::checkFUConnections(), IDFValidator::checkFUImplementations(), RemoveUnconnectedComponents::checkFUPorts(), BEMValidator::checkImmediateControlField(), IDFValidator::checkIUImplementations(), ProGe::ProcessorGenerator::checkIULatencies(), BEMValidator::checkLImmDstRegisterFields(), MachineValidator::checkOperandBindings(), IDFValidator::checkRFImplementations(), RemoveUnconnectedComponents::checkRFPorts(), BEMValidator::checkSourceField(), MinimalOpSetCheck::checkWithIgnore(), TTAMachine::FunctionUnit::cleanupGuards(), TTAMachine::FUPort::cleanupGuards(), SimulatorFrontend::compareState(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), ADFCombiner::connectRegisterFiles(), ADFCombiner::connectVectorLSU(), BasicBlockPass::copyRMToBB(), RegisterQuantityCheck::countIntRegisters(), BlocksConnectIC::createBus(), VLIWConnectIC::createBus(), BlocksTranslator::CreateConnection(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::TPEFProgramFactory::createInstruction(), POMDisassembler::createInstruction(), ProgramDependenceGraph::createJump(), DefaultICGenerator::createSignalsForIC(), MachineInfo::defaultDataAddressSpace(), BlocksTranslator::Deinitialize(), TTAMachine::RegisterFile::deleteGuards(), AddFUArchFromADFCmd::Do(), AddBridgeCmd::Do(), llvm::LLVMTCEBuilder::emitLongjmp(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCEBuilder::emitSetjmp(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), InfoImmediatesCommand::execute(), InfoRegFilesCommand::execute(), InfoIunitsCommand::execute(), InfoBussesCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), SimulatorFrontend::findBooleanRegister(), findBooleanRegisterFile(), RegisterRenamer::findConnectedRFs(), ProgrammabilityValidator::findConnections(), AutoSelectImplementationsDialog::findFUImplementations(), ProgrammabilityValidator::findGlobalConnectionRegister(), RegisterQuantityCheck::findGuardRegisters(), ADFCombiner::findGuards(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), AutoSelectImplementationsDialog::findIUImplementations(), MachineInfo::findLockUnits(), AlmaIFIntegrator::findMemories(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), ProGe::RV32MicroCodeGenerator::findRF(), AutoSelectImplementationsDialog::findRFImplementations(), RegisterCopyAdder::findTempRegisters(), BasicBlockScheduler::findTrigger(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), MinimalOpSetCheck::fix(), RegisterQuantityCheck::fixIntRegs(), FUGuardDialog::FUGuardDialog(), ProGeTestBenchGenerator::generate(), CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateFUOutputUpdater(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProgramImageGenerator::generateProgramImage(), DefaultICGenerator::generateSocketsAndMuxes(), MachineEditPartFactory::getBusChains(), DisassemblyGridTable::GetColLabelValue(), getFunctionUnit(), DisassemblyGridTable::GetNumberCols(), MachineInfo::getOpset(), MachineInfo::getPortBindingsOfOperation(), getRegisterFile(), MachineEditPartFactory::getSockets(), BasicBlockScheduler::getTriggerOperand(), MachineEditPartFactory::getUnits(), DisassemblyGridTable::GetValue(), DefaultDecoderGenerator::glockPortWidth(), DefaultDecoderGenerator::glockRequestWidth(), BusTracker::handleEvent(), llvm::LLVMTCEBuilder::hasAmbiguousASpaceRefs(), MachineConnectivityCheck::hasConditionalMoves(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), TTAMachine::Machine::hasOperation(), MachineResourceModifier::hasSlot(), AlmaIFIntegrator::initAlmaifBlock(), llvm::LLVMTCEBuilder::initDataSections(), AddWatchDialog::initialize(), SimulatorFrontend::initializeMemorySystem(), MachineResourceManager::initResourceSection(), CodeCompressorPlugin::instructionTemplate(), AddressSpaceDialog::isFreeId(), TTAMachine::Machine::isRISCVMachine(), TTAMachine::RegisterFile::isUsedAsGuard(), ProgrammabilityValidator::listConnections(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), TTAMachine::Machine::loadState(), MachineInfo::longestGuardLatency(), CostEstimator::Estimator::longestPath(), MachineAnalysis::MachineAnalysis(), main(), ProGe::RV32MicroCodeGenerator::mapFunctionUnit(), TTAMachine::Machine::maximumLatency(), CompiledSimCodeGenerator::maxLatency(), BEMGenerator::maxLongImmSlotWidth(), MachineInfo::maxMemoryAlignment(), MinimizeMachine::minimizeBuses(), MinimizeMachine::minimizeFunctionUnits(), MinimizeMachine::minimizeRegisterFiles(), MinimalOpSetCheck::missingOperations(), DisasmExecPercentageAttrProvider::moveCellAttr(), MachineInfo::numberOfRegisters(), BusDialog::onAddFUGuard(), BusDialog::onAddRFGuard(), TemplateListDialog::onAddSlot(), ProDeBusOrderDialog::onBusSelectionChanged(), ProDeBusOrderDialog::onDown(), BridgeDialog::onInputBus(), BusDialog::onOK(), SocketDialog::onOK(), AddressSpaceDialog::onOK(), FUDialog::onOK(), GCUDialog::onOK(), IUDialog::onOK(), RFDialog::onOK(), OTAFormatListDialog::onOTAFormatName(), PlatformIntegrator::parseDataMemories(), TTAMachine::Bus::position(), BF2Scheduler::preAllocateFunctionUnitsInner(), ImmediateGenerator::printImmediateTemplates(), printLatexAddressSpaceDescription(), printLatexFunctionUnitDescription(), MachineResourceModifier::reduceBuses(), llvm::LLVMTCEIRBuilder::registerFileName(), ProximPortWindow::reinitialize(), ProximRegisterWindow::reinitialize(), BF2Scheduler::releasePortForOp(), SimpleICOptimizer::removeAllConnections(), MachineResourceModifier::removeBuses(), ImmediateGenerator::removeInsTemplate(), MachineResourceModifier::removeNotConnectedSockets(), RemoveUnconnectedComponents::removeUnconnectedFUs(), ADFCombiner::renameExtraUnits(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ProGe::RV32MicroCodeGenerator::RV32MicroCodeGenerator(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), TTAMachine::Bridge::setFirstOfChain(), DataDependenceGraph::setMachine(), TTAMachine::AddressSpace::setNumericalIds(), IUBroker::setupResourceLinks(), ProximMachineStateWindow::setUtilizationHighlights(), FullyConnectedCheck::socketAttachedToAllBusses(), BEMGenerator::sourceBridge(), BEMGenerator::sourceBridgeCount(), TTAMachine::InstructionTemplate::supportedWidth(), TemplateSlotDialog::TemplateSlotDialog(), MachineInfo::templatesUsesSlot(), MachineInfo::templatesUsingSlot(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), CostEstimator::Estimator::totalEnergyOfRegisterFiles(), FUGuardDialog::TransferDataToWindow(), ImmediateSlotDialog::TransferDataToWindow(), OTAFormatListDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), RFGuardDialog::TransferDataToWindow(), TemplateListDialog::TransferDataToWindow(), TemplateSlotDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), TTAMachine::AddressSpace::unsetMachine(), TTAMachine::Bus::unsetMachine(), TTAMachine::ImmediateSlot::unsetMachine(), TTAMachine::ImmediateUnit::unsetMachine(), ProximRegisterWindow::update(), FUDialog::updateAddressSpaceChoice(), GCUDialog::updateAddressSpaceChoice(), AddressSpacesDialog::updateASList(), BridgeDialog::updateBusChoices(), ProDeBusOrderDialog::updateBusList(), SocketDialog::updateConnected(), CompiledSimCodeGenerator::updateDeclaredSymbolsList(), ProcessorImplementationWindow::updateImplementationLists(), TemplateListDialog::updateSlotList(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), IUDialog::updateTemplateList(), BEMValidator::validate(), DefaultICGenerator::verifyCompatibility(), TTAMachine::ImmediateSlot::width(), TDGen::writeBackendCode(), DefaultICGenerator::writeBusDumpCode(), DefaultICGenerator::writeBustraceExportCode(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeFUCntrlSignals(), TDGen::writeInstrInfo(), DefaultDecoderGenerator::writeInstructionTemplateProcedures(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeLongImmediateWriteProcess(), DefaultDecoderGenerator::writeRFCntrlSignals(), DefaultDecoderGenerator::writeRFSRAMDecodingProcess(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), DefaultDecoderGenerator::writeSocketCntrlSignals(), DefaultDecoderGenerator::writeSquashSignalGenerationProcesses(), and DefaultDecoderGenerator::writeSquashSignals().
end()
template<typename ComponentType > const_iterator TTAMachine::Machine::Navigator< ComponentType >::end () const noexcept
Referenced by MachineResourceModifier::percentualFUIncrease(), and MachineResourceModifier::percentualRegisterIncrease().
hasItem()
template<typename ComponentType > bool TTAMachine::Machine::Navigator< ComponentType >::hasItem (const std::string & name) const
Referenced by MemorySystem::addAddressSpace(), ADFCombiner::addAddressSpaces(), CodeCompressorPlugin::addBitsForImmediateSlot(), CodeCompressorPlugin::addBitsForMoveSlot(), MachineResourceModifier::addBusesByAmount(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), ADFCombiner::addFunctionUnits(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addIUToNetlist(), ComponentAdder::addRegisterFiles(), ProGe::NetlistGenerator::addRFToNetlist(), BEMGenerator::addSubfields(), UniversalMachine::booleanRegisterFile(), TTAMachine::Bridge::Bridge(), TTAProgram::TPEFProgramFactory::build(), IDFValidator::checkFUImplementations(), IDFValidator::checkIUImplementations(), IDFValidator::checkRFImplementations(), BEMValidator::checkSocketCodeTable(), ADFCombiner::connectRegisterFiles(), ADFCombiner::connectVectorLSU(), ADFCombiner::createPortsAndSockets(), FullyConnectedCheck::createSocket(), llvm::LLVMTCEBuilder::createTerminalRegister(), UniversalMachine::dataAddressSpace(), AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), PasteComponentCmd::Do(), UniversalMachine::doubleRegisterFile(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCEBuilder::emitSPInitialization(), InfoImmediatesCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), VectorLSGenerator::explore(), TTAProgram::TPEFProgramFactory::findAddressSpace(), TTAProgram::TPEFProgramFactory::findBus(), MachineResourceManager::findDataAddressSpace(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), BlocksTranslator::FindOutputSocket(), SimulatorFrontend::findRegister(), TTAProgram::TPEFProgramFactory::findRegisterFile(), MachineResourceManager::functionUnitPortResource(), ProgramImageGenerator::generateDataImage(), TTAMachine::ImmediateSlot::ImmediateSlot(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), MachineResourceManager::indexResource(), UniversalMachine::instructionAddressSpace(), UniversalMachine::integerRegisterFile(), TTAMachine::Machine::isRISCVMachine(), TTAMachine::FunctionUnit::loadState(), TTAMachine::RegisterGuard::loadState(), BEMValidator::needsSocketCodeTable(), BEMValidator::needsSourceField(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddressSpacesDialog::onAdd(), AddRFFromHDBDialog::onAdd(), OTAFormatListDialog::onAddOTAFormat(), ImmediateSlotDialog::onAddSlot(), TemplateListDialog::onAddTemplate(), BridgeDialog::onOK(), BusDialog::onOK(), GCUDialog::onOK(), TemplateSlotDialog::onOK(), MachineResourceModifier::percentualFUIncrease(), MachineResourceModifier::percentualRegisterIncrease(), IDFValidator::removeUnknownImplementations(), AddressSpacesDialog::selectedAS(), TTAMachine::Machine::setGlobalControl(), TTAMachine::ImmediateSlot::setName(), UniversalMachine::specialRegisterFile(), UniversalMachine::universalBus(), UniversalMachine::universalFunctionUnit(), and DefaultDecoderGenerator::writeInstructionTemplateProcedures().
item() [1/2]
template<typename ComponentType > ComponentType * TTAMachine::Machine::Navigator< ComponentType >::item (const std::string & name) const
item() [2/2]
template<typename ComponentType > ComponentType * TTAMachine::Machine::Navigator< ComponentType >::item (int index) const
Referenced by ADFCombiner::addAddressSpaces(), ADFCombiner::addAllGuardsToConnectionBuses(), CodeCompressorPlugin::addBitsForImmediateSlot(), CodeCompressorPlugin::addBitsForMoveSlot(), ADFCombiner::addBuses(), llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), SimpleICOptimizer::addConnections(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), ADFCombiner::addFunctionUnits(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), DefaultDecoderGenerator::addGlockPortToDecoder(), DefaultICGenerator::addICToNetlist(), ProGe::NetlistGenerator::addIUToNetlist(), DefaultDecoderGenerator::addLockReqPortToDecoder(), BEMGenerator::addLongImmDstRegisterFields(), ADFCombiner::addRegisterFiles(), TTAMachine::AddressSpace::AddressSpace(), llvm::LLVMTCEBuilder::addressSpaceById(), ProGe::NetlistGenerator::addRFToNetlist(), TTAMachine::InstructionTemplate::addSlot(), BEMGenerator::addSocketCodeTables(), ImmediateGenerator::addSplitInsTemplate(), BEMGenerator::addSubfields(), BEMGenerator::addTopLevelFields(), TTAMachine::Bridge::adjustChainDirection(), MachineResourceModifier::analyzeBuses(), MachineResourceModifier::analyzeFunctionUnits(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), MachineResourceModifier::analyzeRegisters(), TTAMachine::Port::attachSocket(), FullyConnectedCheck::attachSocketToAllBusses(), UniversalMachine::booleanRegisterFile(), TTAProgram::TPEFProgramFactory::build(), SimulationController::buildFUResourceConflictDetectors(), MachineStateBuilder::buildMachineState(), ControlFlowGraph::buildMBBFromBB(), MinimalOpSetCheck::buildMinimalOpSet(), BusBroker::buildResources(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), InputPSocketBroker::buildResources(), ITemplateBroker::buildResources(), IUBroker::buildResources(), OutputFUBroker::buildResources(), OutputPSocketBroker::buildResources(), MachineConnectivityCheck::busConnectedToAnyFU(), DefaultICDecoderEstimator::busParameters(), MachineInfo::canEncodeImmediateInteger(), RegisterQuantityCheck::canFixIntRegs(), MachineConnectivityCheck::canWriteAllImmediates(), FullyConnectedCheck::check(), AddressSpaceCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), RFPortCheck::check(), MinimalOpSetCheck::check(), MinimalOpSetCheck::check(), ProgrammabilityValidator::checkBooleanRegister(), RemoveUnconnectedComponents::checkBuses(), MachineValidator::checkFUConnections(), IDFValidator::checkFUImplementations(), RemoveUnconnectedComponents::checkFUPorts(), BEMValidator::checkImmediateControlField(), IDFValidator::checkIUImplementations(), ProGe::ProcessorGenerator::checkIULatencies(), BEMValidator::checkLImmDstRegisterFields(), MachineValidator::checkOperandBindings(), IDFValidator::checkRFImplementations(), RemoveUnconnectedComponents::checkRFPorts(), BEMValidator::checkSocketCodeTable(), BEMValidator::checkSourceField(), MinimalOpSetCheck::checkWithIgnore(), TTAMachine::FunctionUnit::cleanupGuards(), TTAMachine::FUPort::cleanupGuards(), SimulatorFrontend::compareState(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), ADFCombiner::connectPorts(), ADFCombiner::connectRegisterFiles(), ADFCombiner::connectVectorLSU(), ADFCombiner::copyGuards(), RegisterQuantityCheck::countIntRegisters(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::TPEFProgramFactory::createInstruction(), POMDisassembler::createInstruction(), ProgramDependenceGraph::createJump(), ADFCombiner::createPortsAndSockets(), DefaultICGenerator::createSignalsForIC(), llvm::LLVMTCEBuilder::createTerminalRegister(), TTAProgram::CodeGenerator::createTerminalRegister(), UniversalMachine::dataAddressSpace(), MachineInfo::defaultDataAddressSpace(), BlocksTranslator::Deinitialize(), TTAMachine::RegisterFile::deleteGuards(), AddFUArchFromADFCmd::Do(), AddBridgeCmd::Do(), PasteComponentCmd::Do(), UniversalMachine::doubleRegisterFile(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitLongjmp(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCEBuilder::emitSetjmp(), llvm::LLVMTCEBuilder::emitSPInitialization(), CodeCompressorPlugin::encodeMove(), UniversalFunctionUnit::ensureInputPorts(), UniversalFunctionUnit::ensureOutputPorts(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), InfoRegFilesCommand::execute(), InfoIunitsCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), BlocksConnectIC::explore(), VectorLSGenerator::explore(), VLIWConnectIC::explore(), CodeSectionCreator::finalize(), TTAProgram::TPEFProgramFactory::findAddressSpace(), CostEstimator::Estimator::findAllICPaths(), findBooleanGuard(), SimulatorFrontend::findBooleanRegister(), findBooleanRegisterFile(), TTAProgram::TPEFProgramFactory::findBus(), findBus(), MachineResourceManager::findBusWidth(), RegisterRenamer::findConnectedRFs(), ProgrammabilityValidator::findConnections(), MachineResourceManager::findDataAddressSpace(), RegisterRenamer::findFreeRegisters(), AutoSelectImplementationsDialog::findFUImplementations(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), findFunctionUnit(), ProgrammabilityValidator::findGlobalConnectionRegister(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), RegisterQuantityCheck::findGuardRegisters(), ADFCombiner::findGuards(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), AutoSelectImplementationsDialog::findIUImplementations(), MachineInfo::findLockUnits(), AlmaIFIntegrator::findMemories(), BlocksTranslator::FindOutputSocket(), RegisterRenamer::findPartiallyUsedRegistersAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersBeforeCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFBeforeCycle(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), TTAProgram::TPEFProgramFactory::findRegisterFile(), findRegisterFile(), ProGe::RV32MicroCodeGenerator::findRF(), AutoSelectImplementationsDialog::findRFImplementations(), RegisterCopyAdder::findTempRegisters(), BasicBlockScheduler::findTrigger(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), MinimalOpSetCheck::fix(), RegisterQuantityCheck::fixIntRegs(), FUGuardDialog::FUGuardDialog(), CompiledSimulation::FUMemory(), CompiledSimulation::functionUnit(), MachineResourceManager::functionUnitPortResource(), ProGeTestBenchGenerator::generate(), CompiledSimCodeGenerator::generateConstructorCode(), ProgramImageGenerator::generateDataImage(), CompiledSimCodeGenerator::generateFUOutputUpdater(), ProGe::ProcessorGenerator::generateGlobalsPackage(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), DefaultICGenerator::generateSocketsAndMuxes(), MachineEditPartFactory::getBusChains(), DisassemblyGridTable::GetColLabelValue(), getFunctionUnit(), llvm::TCETargetMachine::getLoadOpcode(), MachineInfo::getOpset(), MachineInfo::getPortBindingsOfOperation(), getRegisterFile(), MachineEditPartFactory::getSockets(), BasicBlockScheduler::getTriggerOperand(), MachineEditPartFactory::getUnits(), DefaultDecoderGenerator::glockPortWidth(), DefaultDecoderGenerator::glockRequestWidth(), BusTracker::handleEvent(), ProcessorImplementationWindow::handleSelectFUImplementation(), ProcessorImplementationWindow::handleSelectIUImplementation(), ProcessorImplementationWindow::handleSelectRFImplementation(), llvm::LLVMTCEBuilder::hasAmbiguousASpaceRefs(), MachineConnectivityCheck::hasConditionalMoves(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), TTAMachine::Machine::hasOperation(), MachineResourceModifier::hasSlot(), CompiledSimulation::immediateUnitRegisterValue(), MachineResourceManager::indexResource(), AlmaIFIntegrator::initAlmaifBlock(), llvm::LLVMTCEBuilder::initDataSections(), AddWatchDialog::initialize(), SimulatorFrontend::initializeMemorySystem(), MachineResourceManager::initResourceSection(), UniversalMachine::instructionAddressSpace(), CodeCompressorPlugin::instructionTemplate(), UniversalMachine::integerRegisterFile(), AddressSpaceDialog::isFreeId(), TTAMachine::RegisterFile::isUsedAsGuard(), ProgrammabilityValidator::listConnections(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), TTAMachine::Bridge::loadState(), TTAMachine::FunctionUnit::loadState(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::Socket::loadState(), MachineInfo::longestGuardLatency(), CostEstimator::Estimator::longestPath(), MachineAnalysis::MachineAnalysis(), main(), ProGe::RV32MicroCodeGenerator::mapFunctionUnit(), TTAMachine::Machine::maximumLatency(), CompiledSimCodeGenerator::maxLatency(), BEMGenerator::maxLongImmSlotWidth(), MachineInfo::maxMemoryAlignment(), MinimizeMachine::minimizeFunctionUnits(), MinimizeMachine::minimizeRegisterFiles(), MinimalOpSetCheck::missingOperations(), DisasmExecPercentageAttrProvider::moveCellAttr(), BEMValidator::needsSocketCodeTable(), BEMValidator::needsSourceField(), MachineInfo::numberOfRegisters(), BusDialog::onAddFUGuard(), TemplateListDialog::onAddSlot(), AddWatchDialog::onASChoice(), ImmediateSlotDialog::onDeleteSlot(), ProDeBusOrderDialog::onDown(), AddWatchDialog::onFUChoice(), BridgeDialog::onInputBus(), BridgeDialog::onOK(), BusDialog::onOK(), SocketDialog::onOK(), AddressSpaceDialog::onOK(), FUDialog::onOK(), GCUDialog::onOK(), IUDialog::onOK(), IUPortDialog::onOK(), RFDialog::onOK(), TemplateSlotDialog::onOK(), AddWatchDialog::onRFChoice(), FUDialog::onSetAddressSpace(), FUPortDialog::onSocketChoice(), RFPortDialog::onSocketChoice(), SRPortDialog::onSocketChoice(), ProDeBusOrderDialog::onUp(), PlatformIntegrator::parseDataMemories(), TTAMachine::Bus::position(), BF2Scheduler::preAllocateFunctionUnitsInner(), ImmediateGenerator::printImmediateTemplates(), printLatexAddressSpaceDescription(), printLatexFunctionUnitDescription(), MachineResourceModifier::reduceBuses(), MachineResourceManager::registerFileIndexReference(), llvm::LLVMTCEIRBuilder::registerFileName(), CompiledSimulation::registerFileValue(), CompiledSimController::registerFileValue(), SimulationController::registerFileValue(), ProximPortWindow::reinitialize(), ProximRegisterWindow::reinitialize(), BF2Scheduler::releasePortForOp(), SimpleICOptimizer::removeAllConnections(), MachineResourceModifier::removeBuses(), ConnectionSweeper::removeConnection(), ImmediateGenerator::removeInsTemplate(), MachineResourceModifier::removeNotConnectedSockets(), RemoveUnconnectedComponents::removeUnconnectedFUs(), ADFCombiner::renameExtraUnits(), BFRenameLiveRange::renameLiveRange(), RegisterRenamer::renameLiveRange(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), MachineResourceManager::rFPortOrFUIndexReference(), ProGe::RV32MicroCodeGenerator::RV32MicroCodeGenerator(), SocketDialog::segment(), AddressSpacesDialog::selectedAS(), FUGuardDialog::selectedFU(), OTAFormatListDialog::selectedOTAFormat(), RFGuardDialog::selectedRF(), TemplateListDialog::selectedTemplate(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), TTAMachine::Bridge::setFirstOfChain(), DataDependenceGraph::setMachine(), TTAMachine::AddressSpace::setNumericalIds(), BFRenameLiveRange::setTerminals(), IUBroker::setupResourceLinks(), ProximMachineStateWindow::setUtilizationHighlights(), MemorySystem::shareMemoriesWith(), FullyConnectedCheck::socketAttachedToAllBusses(), BEMGenerator::sourceBridge(), BEMGenerator::sourceBridgeCount(), UniversalMachine::specialRegisterFile(), TTAMachine::InstructionTemplate::supportedWidth(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), TemplateSlotDialog::TemplateSlotDialog(), MachineInfo::templatesUsesSlot(), MachineInfo::templatesUsingSlot(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), MachineConnectivityCheck::totalConnectionCount(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), CostEstimator::Estimator::totalEnergyOfRegisterFiles(), FUGuardDialog::TransferDataToWindow(), ImmediateSlotDialog::TransferDataToWindow(), OTAFormatListDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), RFGuardDialog::TransferDataToWindow(), TemplateListDialog::TransferDataToWindow(), TemplateSlotDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), UniversalMachine::universalBus(), UniversalMachine::universalFunctionUnit(), TTAMachine::AddressSpace::unsetMachine(), TTAMachine::Bus::unsetMachine(), TTAMachine::ImmediateSlot::unsetMachine(), TTAMachine::ImmediateUnit::unsetMachine(), ProximPortWindow::update(), ProximRegisterWindow::update(), FUDialog::updateAddressSpaceChoice(), GCUDialog::updateAddressSpaceChoice(), AddressSpacesDialog::updateASList(), BridgeDialog::updateBusChoices(), ProDeBusOrderDialog::updateBusList(), SocketDialog::updateConnected(), CompiledSimCodeGenerator::updateDeclaredSymbolsList(), ProcessorImplementationWindow::updateImplementationLists(), TemplateListDialog::updateSlotList(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), IUDialog::updateTemplateList(), BEMValidator::validate(), DefaultICGenerator::verifyCompatibility(), TTAMachine::ImmediateSlot::width(), TDGen::writeBackendCode(), DefaultICGenerator::writeBusDumpCode(), DefaultICGenerator::writeBustraceExportCode(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeFUCntrlSignals(), TDGen::writeInstrInfo(), DefaultDecoderGenerator::writeInstructionTemplateProcedures(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeLongImmediateWriteProcess(), DefaultDecoderGenerator::writeRFCntrlSignals(), DefaultDecoderGenerator::writeRFSRAMDecodingProcess(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), DefaultDecoderGenerator::writeSocketCntrlSignals(), DefaultDecoderGenerator::writeSquashSignalGenerationProcesses(), and DefaultDecoderGenerator::writeSquashSignals().
operator=()
template<typename ComponentType > Navigator & TTAMachine::Machine::Navigator< ComponentType >::operator= (const Navigator< ComponentType > & old)
Member Data Documentation
container_
template<typename ComponentType > const Machine::ComponentContainer<ComponentType>* TTAMachine::Machine::Navigator< ComponentType >::container_ private
The container which this navigator handles.
Definition at line 209 of file Machine.hh.
The documentation for this class was generated from the following file:
Machine.hh