OpenASIP: ControlDependenceNode Class Reference
ControlDependenceNode Class Reference
#include <ControlDependenceNode.hh>
Public Types
enum NodeType {
CDEP_NODE_REGION , CDEP_NODE_PREDICATE , CDEP_NODE_BB , CDEP_NODE_LOOPENTRY ,
CDEP_NODE_LOOPCLOSE
}
typedef std::set< ControlDependenceNode * > NodesInfo
Storage type for other nodes of same graph needed to define some non graph relations. Duplicit type compared to NodeSet, but that is defined in Graph class.
Public Member Functions
ControlDependenceNode (const NodeType type=CDEP_NODE_BB, BasicBlockNode *bblock=NULL)
virtual ~ControlDependenceNode ()
bool isControlDependenceNode () const
bool isRegionNode () const
bool isPredicateNode () const
bool isBBNode () const
bool isEntryNode () const
bool isExitNode () const
bool isLoopEntryNode () const
bool isLoopEntryNode (int component) const
bool isLoopCloseNode () const
void setLoopEntryNode (int component)
void setComponent (int component)
int component () const
void setLastNode ()
LastNode marks node that must be ordered last compared to it's sibling nodes - Close node of loop.
bool isLastNode () const
int instructionCount () const
TTAProgram::Instruction & instruction (int index) const
BasicBlockNode * basicBlockNode () const
NodeType type () const
std::string toString () const
void addToRegion (ControlDependenceNode &node)
const NodesInfo & region ()
void addToEEC (ControlDependenceNode &node)
const NodesInfo & eec ()
void addToPseudoPredicateEEC (ControlDependenceNode &node)
const NodesInfo & pseudoPredicateEEC ()
void printRelations () const
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
virtual GraphNode * clone () const
int nodeID () const
virtual std::string dotString () const
Private Attributes
NodeType type_
BasicBlockNode * code_
NodesInfo region_
Stores "region" information for computing serialization information.
NodesInfo eec_
Stores "eec" information for computing serialization information.
NodesInfo pseudoPredicateEEC_
Stores "shadow" eec information for predicate basic blocks which can be then copied into PDG for nodes of basic blocks that are not actuall predicate node.
int component_
Number of strong component the node belongs to, if any.
bool lastNode_
Indicated that the node should be scheduled last from it's siblings Case when node is predicate or region, has close node in it's subgraph and ancestor which is loop entry node.
Detailed Description
Node of the control dependence graph. Each node represents one basic block or region node.
A basic block is defined as an ordered sequence of adjacent instructions in which only the first can be target of jump and ony the last one (save jump delay slots) can contain jumps.
Note
Instructions that contain function calls are control flow bariers also. For now they split basic blocks into two, with special type of edge connecting them.
Definition at line 61 of file ControlDependenceNode.hh.
Member Typedef Documentation
NodesInfo
typedef std::set<ControlDependenceNode*> ControlDependenceNode::NodesInfo
Storage type for other nodes of same graph needed to define some non graph relations. Duplicit type compared to NodeSet, but that is defined in Graph class.
Definition at line 73 of file ControlDependenceNode.hh.
Member Enumeration Documentation
NodeType
enum ControlDependenceNode::NodeType
Enumerator
CDEP_NODE_REGION
CDEP_NODE_PREDICATE
CDEP_NODE_BB
CDEP_NODE_LOOPENTRY
CDEP_NODE_LOOPCLOSE
Definition at line 63 of file ControlDependenceNode.hh.
                  {
        CDEP_NODE_REGION, // Region nodes of CDG
        CDEP_NODE_PREDICATE, // Predicate nodes of CDG
        CDEP_NODE_BB,   // Basic block nodes containing code snippets
        CDEP_NODE_LOOPENTRY, // Region that is loop entry node
        CDEP_NODE_LOOPCLOSE // Region that is loop entry node
    };
Constructor & Destructor Documentation
ControlDependenceNode()
ControlDependenceNode::ControlDependenceNode (const NodeType type = CDEP_NODE_BB, BasicBlockNode * bblock = NULL) inline
Definition at line 74 of file ControlDependenceNode.hh.
                                       :
        type_(type), code_(bblock), component_(-1), lastNode_(false) {}
~ControlDependenceNode()
ControlDependenceNode::~ControlDependenceNode () virtual
Destructor.
Definition at line 44 of file ControlDependenceNode.cc.
{
    region_.clear();
    eec_.clear();
    pseudoPredicateEEC_.clear();
}
References eec_, pseudoPredicateEEC_, and region_.
Member Function Documentation
addToEEC()
void ControlDependenceNode::addToEEC (ControlDependenceNode & node)
Add CDG node to "eec" set for computing serialization information
Parameters
node Control Dependence Node to add to the set
Definition at line 232 of file ControlDependenceNode.cc.
{
    eec_.insert(&node);
}
References eec_.
Referenced by ControlDependenceGraph::computeEECInfo().
addToPseudoPredicateEEC()
void ControlDependenceNode::addToPseudoPredicateEEC (ControlDependenceNode & node)
Add CDG node to "pseduo eec" set for computing serialization information case node is predicate basic block. Only actuall predicate move will have predicate eec, rest of moves of basic block needs regular 'leaf' eec computation
Parameters
node Control Dependence Node to add to the set
Definition at line 257 of file ControlDependenceNode.cc.
{
    pseudoPredicateEEC_.insert(&node);
}
References pseudoPredicateEEC_.
addToRegion()
void ControlDependenceNode::addToRegion (ControlDependenceNode & node)
Add CDG node to "region" set for computing serialization information
Parameters
node Control Dependence Node to add to the set
Definition at line 212 of file ControlDependenceNode.cc.
{
    region_.insert(&node);
}
References region_.
Referenced by ControlDependenceGraph::computeRegionInfo(), and ControlDependenceGraph::regionHelper().
basicBlockNode()
BasicBlockNode * ControlDependenceNode::basicBlockNode () const
Returns a basic block refered by the control dependence node
Returns
the Basic block
Definition at line 116 of file ControlDependenceNode.cc.
{
    if (isBBNode() || isPredicateNode()) {
        return code_;
    }
    std::string msg = "Trying to read from non basic block node!";
    throw InvalidData(__FILE__, __LINE__, __func__, msg);
    return NULL;
}
References __func__, code_, isBBNode(), and isPredicateNode().
Referenced by ProgramDependenceGraph::ProgramDependenceGraph().
component()
int ControlDependenceNode::component () const inline
Definition at line 91 of file ControlDependenceNode.hh.
{ return component_;}
References component_.
Referenced by ProgramDependenceGraph::copyRegionEECComponent(), isLoopEntryNode(), setComponent(), and setLoopEntryNode().
eec()
const ControlDependenceNode::NodesInfo & ControlDependenceNode::eec ()
Returns the "eec" set for given node
Returns
the "eec" set for given node
Definition at line 243 of file ControlDependenceNode.cc.
{
    return eec_;
}
References eec_.
Referenced by ControlDependenceGraph::compareSiblings(), ControlDependenceGraph::computeEECInfo(), and ProgramDependenceGraph::copyRegionEECComponent().
instruction()
TTAProgram::Instruction & ControlDependenceNode::instruction (int index) const
Returns instruction at given index in basic block.
Parameters
index Index of instruction in basic block
Returns
The instruction at given index
Definition at line 56 of file ControlDependenceNode.cc.
{
    if (!isBBNode()) {
        std::string msg =
            "Trying to read from non basic block node" + toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    return code_->basicBlock().instructionAtIndex(index);
}
References __func__, BasicBlockNode::basicBlock(), code_, TTAProgram::CodeSnippet::instructionAtIndex(), isBBNode(), and toString().
instructionCount()
int ControlDependenceNode::instructionCount () const
Returns number of instructions in basic block
Returns
number of instructions
Definition at line 130 of file ControlDependenceNode.cc.
{
    if (isBBNode()) {
        return code_->basicBlock().instructionCount();
    }
    std::string msg = "Trying to read from non basic block node!";
    throw InvalidData(__FILE__, __LINE__, __func__, msg);
    return 0;
}
References __func__, BasicBlockNode::basicBlock(), code_, TTAProgram::CodeSnippet::instructionCount(), and isBBNode().
isBBNode()
bool ControlDependenceNode::isBBNode () const
Predicate nodes are BB which ends with conditional jump in CFG
Definition at line 155 of file ControlDependenceNode.cc.
{
    /// Predicate nodes are BB which ends with conditional jump in CFG
    return (type_ == CDEP_NODE_BB) || isPredicateNode();
}
References CDEP_NODE_BB, isPredicateNode(), and type_.
Referenced by basicBlockNode(), ControlDependenceGraph::compareSiblings(), instruction(), instructionCount(), and toString().
isControlDependenceNode()
bool ControlDependenceNode::isControlDependenceNode () const
Definition at line 140 of file ControlDependenceNode.cc.
{
    return true;
}
isEntryNode()
bool ControlDependenceNode::isEntryNode () const
Definition at line 161 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_BB && code_->isEntryBB();
}
References CDEP_NODE_BB, code_, BasicBlockNode::isEntryBB(), and type_.
Referenced by ControlDependenceGraph::computeDependence(), ControlDependenceGraph::entryNode(), ProgramDependenceGraph::ProgramDependenceGraph(), ControlDependenceGraph::regionHelper(), setLoopEntryNode(), and toString().
isExitNode()
bool ControlDependenceNode::isExitNode () const
Definition at line 166 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_BB && code_->isExitBB();
}
References CDEP_NODE_BB, code_, BasicBlockNode::isExitBB(), and type_.
Referenced by ControlDependenceGraph::computeDependence(), and toString().
isLastNode()
bool ControlDependenceNode::isLastNode () const inline
Definition at line 95 of file ControlDependenceNode.hh.
{ return lastNode_;}
References lastNode_.
Referenced by ControlDependenceGraph::compareSiblings(), ProgramDependenceGraph::copyRegionEECComponent(), ProgramDependenceGraph::ProgramDependenceGraph(), and toString().
isLoopCloseNode()
bool ControlDependenceNode::isLoopCloseNode () const
Definition at line 181 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_LOOPCLOSE;
}
References CDEP_NODE_LOOPCLOSE, and type_.
Referenced by ControlDependenceGraph::compareSiblings(), ProgramDependenceGraph::ProgramDependenceGraph(), ControlDependenceGraph::regionHelper(), ProgramDependenceGraph::removeGuardedJump(), and toString().
isLoopEntryNode() [1/2]
bool ControlDependenceNode::isLoopEntryNode () const
Definition at line 171 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_LOOPENTRY;
}
References CDEP_NODE_LOOPENTRY, and type_.
Referenced by ControlDependenceGraph::compareSiblings(), ProgramDependenceGraph::ProgramDependenceGraph(), ControlDependenceGraph::regionHelper(), ProgramDependenceGraph::removeGuardedJump(), and toString().
isLoopEntryNode() [2/2]
bool ControlDependenceNode::isLoopEntryNode (int component) const
Definition at line 176 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_LOOPENTRY && component == component_;
}
References CDEP_NODE_LOOPENTRY, component(), component_, and type_.
isPredicateNode()
bool ControlDependenceNode::isPredicateNode () const
Definition at line 150 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_PREDICATE;
}
References CDEP_NODE_PREDICATE, and type_.
Referenced by basicBlockNode(), ControlDependenceGraph::compareSiblings(), ProgramDependenceGraph::copyRegionEECComponent(), isBBNode(), ControlDependenceGraph::regionHelper(), and toString().
isRegionNode()
bool ControlDependenceNode::isRegionNode () const
Definition at line 145 of file ControlDependenceNode.cc.
{
    return type_ == CDEP_NODE_REGION;
}
References CDEP_NODE_REGION, and type_.
Referenced by ControlDependenceGraph::compareSiblings(), ProgramDependenceGraph::ProgramDependenceGraph(), ControlDependenceGraph::regionHelper(), ProgramDependenceGraph::removeGuardedJump(), setLoopEntryNode(), and toString().
printRelations()
void ControlDependenceNode::printRelations () const
Definition at line 273 of file ControlDependenceNode.cc.
{
    Application::logStream() << "Relations: ";
    for (NodesInfo::const_iterator iter = region_.begin();
        iter != region_.end();
        iter ++) {
        Application::logStream() << (*iter)->toString() << ", ";
    }
    Application::logStream() << std::endl;
    Application::logStream() << "EEC: ";
    for (NodesInfo::const_iterator iter = eec_.begin();
        iter != eec_.end();
        iter ++) {
        Application::logStream() << (*iter)->toString() << ", ";
    }
    Application::logStream() << std::endl;
}
References eec_, Application::logStream(), and region_.
pseudoPredicateEEC()
const ControlDependenceNode::NodesInfo & ControlDependenceNode::pseudoPredicateEEC ()
Returns the "pseudo eec" set for given node, applicable for predicate nodes
Returns
the "eec" set for given node
Definition at line 268 of file ControlDependenceNode.cc.
{
    return pseudoPredicateEEC_;
}
References pseudoPredicateEEC_.
Referenced by ProgramDependenceGraph::copyRegionEECComponent().
region()
const ControlDependenceNode::NodesInfo & ControlDependenceNode::region ()
Returns the "region" set for given node
Returns
the "region" set for given node
Definition at line 222 of file ControlDependenceNode.cc.
{
    return region_;
}
References region_.
Referenced by ProgramDependenceGraph::copyRegionEECComponent(), and ControlDependenceGraph::regionHelper().
setComponent()
void ControlDependenceNode::setComponent (int component) inline
Definition at line 90 of file ControlDependenceNode.hh.
{ component_ = component;}
References component(), and component_.
Referenced by ControlDependenceGraph::detectStrongComponents().
setLastNode()
void ControlDependenceNode::setLastNode () inline
LastNode marks node that must be ordered last compared to it's sibling nodes - Close node of loop.
Definition at line 94 of file ControlDependenceNode.hh.
{ lastNode_ = true; }
References lastNode_.
setLoopEntryNode()
void ControlDependenceNode::setLoopEntryNode (int component)
In case node was previously in other component as regular region, mark it as loop entry of current component
Definition at line 186 of file ControlDependenceNode.cc.
{
    if (!isRegionNode() && !isEntryNode()) {
        TCEString msg = "Loop entry node \'" + toString();
        msg += "\' is not a Region node!";
        throw InvalidData(
            __FILE__, __LINE__, __func__, msg);
    } else {
        type_ = CDEP_NODE_LOOPENTRY;
    }
    /// In case node was previously in other component as regular
    /// region, mark it as loop entry of current component
    if (component_ != component) {
        component_ = component;
    }
}
References __func__, CDEP_NODE_LOOPENTRY, component(), component_, isEntryNode(), isRegionNode(), toString(), and type_.
toString()
std::string ControlDependenceNode::toString () const virtual
Returns the type of basic block as string.
Note
Used in writting graph to .dot file.
Returns
The type of basic block
Reimplemented from GraphNode.
Definition at line 72 of file ControlDependenceNode.cc.
{
   TCEString result = "";
   if (isRegionNode()) {
      result += "Region " + Conversion::toString(nodeID());
      if (isLastNode()) {
          result += "_LAST";
      }
      return result;
   }
   if (isLoopEntryNode()) {
      result += "Loop Entry " + Conversion::toString(nodeID());
      return result;
   }
   if (isEntryNode()) {
      result += "Entry";
      return result;
   }
   if (isLoopCloseNode()) {
      result += "Close " + Conversion::toString(nodeID());
      return result;
   }
   if (isExitNode()) {
      result += "Exit";
      return result;
   }
   if (isPredicateNode()) {
      result += "Predicate(" + code_->toString() +")";
      if (isLastNode()) {
          result += "_LAST";
      }
      return result;
   }
   if (isBBNode()) {
      return code_->toString();
   }
    return result;
}
References code_, isBBNode(), isEntryNode(), isExitNode(), isLastNode(), isLoopCloseNode(), isLoopEntryNode(), isPredicateNode(), isRegionNode(), GraphNode::nodeID(), BasicBlockNode::toString(), and Conversion::toString().
Referenced by ControlDependenceGraph::computeDependence(), ControlDependenceGraph::computeEECInfo(), ControlDependenceGraph::detectStrongComponents(), instruction(), ControlDependenceGraph::processRegion(), ControlDependenceGraph::regionHelper(), setLoopEntryNode(), and ProgramDependenceNode::toString().
type()
ControlDependenceNode::NodeType ControlDependenceNode::type () const
Definition at line 202 of file ControlDependenceNode.cc.
{
    return type_;
}
References type_.
Member Data Documentation
code_
BasicBlockNode* ControlDependenceNode::code_ private
Definition at line 116 of file ControlDependenceNode.hh.
Referenced by basicBlockNode(), instruction(), instructionCount(), isEntryNode(), isExitNode(), and toString().
component_
int ControlDependenceNode::component_ private
Number of strong component the node belongs to, if any.
Definition at line 126 of file ControlDependenceNode.hh.
Referenced by component(), isLoopEntryNode(), setComponent(), and setLoopEntryNode().
eec_
NodesInfo ControlDependenceNode::eec_ private
Stores "eec" information for computing serialization information.
Definition at line 120 of file ControlDependenceNode.hh.
Referenced by addToEEC(), eec(), printRelations(), and ~ControlDependenceNode().
lastNode_
bool ControlDependenceNode::lastNode_ private
Indicated that the node should be scheduled last from it's siblings Case when node is predicate or region, has close node in it's subgraph and ancestor which is loop entry node.
Definition at line 130 of file ControlDependenceNode.hh.
Referenced by isLastNode(), and setLastNode().
pseudoPredicateEEC_
NodesInfo ControlDependenceNode::pseudoPredicateEEC_ private
Stores "shadow" eec information for predicate basic blocks which can be then copied into PDG for nodes of basic blocks that are not actuall predicate node.
Definition at line 124 of file ControlDependenceNode.hh.
Referenced by addToPseudoPredicateEEC(), pseudoPredicateEEC(), and ~ControlDependenceNode().
region_
NodesInfo ControlDependenceNode::region_ private
Stores "region" information for computing serialization information.
Definition at line 118 of file ControlDependenceNode.hh.
Referenced by addToRegion(), printRelations(), region(), and ~ControlDependenceNode().
type_
NodeType ControlDependenceNode::type_ private
Definition at line 115 of file ControlDependenceNode.hh.
Referenced by isBBNode(), isEntryNode(), isExitNode(), isLoopCloseNode(), isLoopEntryNode(), isLoopEntryNode(), isPredicateNode(), isRegionNode(), setLoopEntryNode(), and type().
The documentation for this class was generated from the following files:
ControlDependenceNode.hh
ControlDependenceNode.cc