OpenASIP: RealCmdLineOptionParser Class Reference
RealCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
RealCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~RealCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual double real () const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual unsigned unsignedInteger (int index=0) const
virtual std::string String (int index=0) const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
virtual int listSize () const
Private Member Functions
RealCmdLineOptionParser (const RealCmdLineOptionParser &)
Copying not allowed.
RealCmdLineOptionParser & operator= (const RealCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
double value_
The value of the option.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that has a real value.
Definition at line 246 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
RealCmdLineOptionParser() [1/2]
RealCmdLineOptionParser::RealCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 507 of file CmdLineOptionParser.cc.
                     :
    CmdLineOptionParser(name, desc, alias), value_(0) {
}
~RealCmdLineOptionParser()
RealCmdLineOptionParser::~RealCmdLineOptionParser () virtual
Destructor.
Definition at line 517 of file CmdLineOptionParser.cc.
{
}
RealCmdLineOptionParser() [2/2]
RealCmdLineOptionParser::RealCmdLineOptionParser (const RealCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * RealCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 529 of file CmdLineOptionParser.cc.
{
    RealOptionValue* copy = new RealOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
operator=()
RealCmdLineOptionParser & RealCmdLineOptionParser::operator= (const RealCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool RealCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of option.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine If the argument is erronous.
Implements CmdLineOptionParser.
Definition at line 543 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for real option";
        string method = "RealCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    // string must not contain anything else than numbers and a dot.
    if (arguments == "") {
        string msg = "Missing value for real option.";
        string method = "RealCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    istringstream istream(arguments);
    if((!(istream >> value_)) || istream.peek() != EOF) {
        string msg = "Format of " + longName() + " option value was wrong: "
            + arguments;
        string method = "RealCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    setDefined();
    return true;
}
References CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and value_.
real()
double RealCmdLineOptionParser::real () const virtual
Returns the real value.
Returns
The real value.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 576 of file CmdLineOptionParser.cc.
{
    return value_;
}
References value_.
Member Data Documentation
value_
double RealCmdLineOptionParser::value_ private
The value of the option.
Definition at line 266 of file CmdLineOptionParser.hh.
Referenced by copy(), parseValue(), and real().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc