OpenASIP: TBPCommand Class Reference
TBPCommand Class Reference
#include <TBPCommand.hh>
Public Member Functions
TBPCommand ()
virtual ~TBPCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "tbp" command of the Simulator Control Language.
Definition at line 47 of file TBPCommand.hh.
Constructor & Destructor Documentation
TBPCommand()
TBPCommand::TBPCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 48 of file TBPCommand.cc.
                       : SimControlLanguageCommand("tbp") {
}
~TBPCommand()
TBPCommand::~TBPCommand () virtual
Destructor.
Does nothing.
Definition at line 56 of file TBPCommand.cc.
{
}
Member Function Documentation
execute()
bool TBPCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "tbp" command.
Sets a temporary breakpoint, which is automatically deleted after the first time it stops the simulation. The arguments args are the same as for the bp command.
Parameters
arguments The address (and condition of the breakpoint).
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 71 of file TBPCommand.cc.
{
    Breakpoint breakpoint(simulatorFrontend(), 0);
    if (!parseBreakpoint(arguments, breakpoint)) {
        return false;
    }
    breakpoint.setDeletedAfterTriggered(true);
    StopPointManager& stopPointManager =
        simulatorFrontend().stopPointManager();
    return printBreakpointInfo(stopPointManager.add(breakpoint));
}
References StopPointManager::add(), SimControlLanguageCommand::parseBreakpoint(), SimControlLanguageCommand::printBreakpointInfo(), StopPoint::setDeletedAfterTriggered(), SimControlLanguageCommand::simulatorFrontend(), and SimulatorFrontend::stopPointManager().
helpText()
std::string TBPCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 91 of file TBPCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_TBREAK).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_TBREAK.
The documentation for this class was generated from the following files:
TBPCommand.hh
TBPCommand.cc