OpenASIP: SimControlLanguageSubCommand Class Reference
SimControlLanguageSubCommand Class Reference abstract
#include <SimControlLanguageCommand.hh>
Public Member Functions
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)=0
virtual SimControlLanguageCommand & parent ()
Private Attributes
SimControlLanguageCommand & parentCommand_
the main command
Detailed Description
Base class for classes that implement subcommands of Simulator Control Language.
Definition at line 122 of file SimControlLanguageCommand.hh.
Constructor & Destructor Documentation
SimControlLanguageSubCommand()
SimControlLanguageSubCommand::SimControlLanguageSubCommand (SimControlLanguageCommand & parentCommand)
Constructor.
Parameters
parentCommand The main command this is a subcommand for.
minArgs The minimum count of arguments this command should receive.
maxArgs The maximum count of arguments this command should receive.
Definition at line 824 of file SimControlLanguageCommand.cc.
                                              :
    parentCommand_(parentCommand) {
}
~SimControlLanguageSubCommand()
SimControlLanguageSubCommand::~SimControlLanguageSubCommand () virtual
Destructor.
Definition at line 833 of file SimControlLanguageCommand.cc.
{
}
Member Function Documentation
execute()
virtual bool SimControlLanguageSubCommand::execute (const std::vector< DataObject > & arguments) pure virtual
Implemented in InfoRegistersCommand, InfoImmediatesCommand, InfoRegFilesCommand, InfoIunitsCommand, InfoBussesCommand, InfoPortsCommand, InfoSegmentsCommand, InfoFunitsCommand, InfoProcCommand, InfoStatsCommand, InfoProgramCommand, and InfoBreakpointsCommand.
Referenced by InfoCommand::execute().
parent()
SimControlLanguageCommand & SimControlLanguageSubCommand::parent () virtual
Returns the parent command.
Returns
the parent command.
Definition at line 842 of file SimControlLanguageCommand.cc.
{
    return parentCommand_;
}
References parentCommand_.
Referenced by InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoRegFilesCommand::execute(), InfoIunitsCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), and InfoBreakpointsCommand::execute().
Member Data Documentation
parentCommand_
SimControlLanguageCommand& SimControlLanguageSubCommand::parentCommand_ private
the main command
Definition at line 130 of file SimControlLanguageCommand.hh.
Referenced by parent().
The documentation for this class was generated from the following files:
SimControlLanguageCommand.hh
SimControlLanguageCommand.cc