OpenASIP: TPEF::TPEFStringSectionReader Class Reference
TPEF::TPEFStringSectionReader Class Reference
#include <TPEFStringSectionReader.hh>
Protected Member Functions
TPEFStringSectionReader ()
virtual ~TPEFStringSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFStringSectionReader (const TPEFStringSectionReader &)
Copying not allowed.
TPEFStringSectionReader & operator= (TPEFStringSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFStringSectionReader proto_
Prototype instance of TPEFStringSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads string section from TPEF binary file.
Definition at line 46 of file TPEFStringSectionReader.hh.
Constructor & Destructor Documentation
TPEFStringSectionReader() [1/2]
TPEF::TPEFStringSectionReader::TPEFStringSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 55 of file TPEFStringSectionReader.cc.
                                                 : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFStringSectionReader()
TPEF::TPEFStringSectionReader::~TPEFStringSectionReader () protected virtual
Destructor.
Definition at line 62 of file TPEFStringSectionReader.cc.
{
}
TPEFStringSectionReader() [2/2]
TPEF::TPEFStringSectionReader::TPEFStringSectionReader (const TPEFStringSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFStringSectionReader & TPEF::TPEFStringSectionReader::operator= (TPEFStringSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFStringSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 88 of file TPEFStringSectionReader.cc.
{
    // base classes implementation must be called
    TPEFSectionReader::readData(stream, section);
    StringSection* stringSection = dynamic_cast<StringSection*>(section);
    assert(stringSection != NULL);
    // check that link section is defined properly
    assert(header().linkId == 0);
    if (!section->noBits()) {
        while (stream.readPosition() <
               header().bodyOffset + header().bodyLength) {
            stringSection->addByte(stream.readByte());
        }
        assert(stringSection->byte(stringSection->chunk(0)) == 0);
    }
    // if nobits flag was set, add zero string to start of section to make
    // references valid (many sections needs string section
    // e.g. symbol section).
    if (stringSection->empty()) {
        stringSection->addByte(0);
    }
}
References TPEF::DataSection::addByte(), assert, TPEF::DataSection::byte(), TPEF::RawSection::chunk(), TPEF::RawSection::empty(), TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), and TPEF::BinaryStream::readPosition().
type()
Section::SectionType TPEF::TPEFStringSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 71 of file TPEFStringSectionReader.cc.
{
    return Section::ST_STRTAB;
}
References TPEF::Section::ST_STRTAB.
Member Data Documentation
proto_
TPEFStringSectionReader TPEF::TPEFStringSectionReader::proto_ static private
Prototype instance of TPEFStringSectionReader to be registered to SectionReader.
Definition at line 63 of file TPEFStringSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFStringSectionReader.hh
TPEFStringSectionReader.cc