OpenASIP: llvm::LLVMTCEScheduler Class Reference
llvm::LLVMTCEScheduler Class Reference
#include <LLVMTCEScheduler.hh>
Public Member Functions
LLVMTCEScheduler ()
virtual ~LLVMTCEScheduler ()
virtual bool runOnMachineFunction (MachineFunction &MF)
Static Public Attributes
static char ID = 0
Private Member Functions
virtual bool doInitialization (Module &m)
Private Attributes
TTAMachine::Machine * tceMachine_
LLVMTCEIRBuilder * tceIRBuilder_
InterPassData * interPassData_
llvm::Module * mod_
Detailed Description
Definition at line 47 of file LLVMTCEScheduler.hh.
Constructor & Destructor Documentation
LLVMTCEScheduler()
llvm::LLVMTCEScheduler::LLVMTCEScheduler ()
Definition at line 79 of file LLVMTCEScheduler.cc.
                                   :
    MachineFunctionPass(ID), tceIRBuilder_(NULL), interPassData_(NULL) {
    try {
        tceMachine_ = TTAMachine::Machine::loadFromADF(ADFLocation);
    } catch (const Exception& e) {
        Application::logStream()
            << "TCE: unable to load the ADF:" << std::endl
            << e.errorMessage() << std::endl;
    }
    // By default Application::cmdLineOptions returns NULL.
    // If we want to pass dump-ddg options we need to create new one.
    // Add also -O3 flag, otherwise the -O0 is used and Sequential Scheduler
    // called.
    LLVMTCECmdLineOptions* options = new LLVMTCECmdLineOptions;
    std::vector<std::string> args;
    args.push_back("llc");
    args.push_back("-O3");
    if (DumpDDG) {
        args.push_back("--dump-ddgs-dot");
        args.push_back("--dump-ddgs-xml");
    } else if (DumpDDGDot) {
        args.push_back("--dump-ddgs-dot");
    } else if (DumpDDGXML) {
        args.push_back("--dump-ddgs-xml");
    }
    if (DisableLLVMAA) {
        args.push_back("--disable-llvmaa");
    }
    try {
        options->parse(args);
        Application::setCmdLineOptions(options);
    } catch (const IllegalCommandLine& e) {
        std::cerr << e.errorMessageStack() << std::endl;
    }
}
References llvm::ADFLocation(), llvm::DisableLLVMAA(), llvm::DumpDDG(), llvm::DumpDDGDot(), llvm::DumpDDGXML(), Exception::errorMessage(), Exception::errorMessageStack(), TTAMachine::Machine::loadFromADF(), Application::logStream(), options, CmdLineOptions::parse(), Application::setCmdLineOptions(), and tceMachine_.
~LLVMTCEScheduler()
virtual llvm::LLVMTCEScheduler::~LLVMTCEScheduler () inline virtual
Definition at line 51 of file LLVMTCEScheduler.hh.
{}
Member Function Documentation
doInitialization()
bool llvm::LLVMTCEScheduler::doInitialization (Module & m) private virtual
Definition at line 116 of file LLVMTCEScheduler.cc.
{
    mod_ = &m;
    return false;
}
References mod_.
runOnMachineFunction()
bool llvm::LLVMTCEScheduler::runOnMachineFunction (MachineFunction & MF) virtual
Definition at line 121 of file LLVMTCEScheduler.cc.
{
    OperationPool::setLLVMTargetInstrInfo(
        MF.getTarget().getSubtargetImpl(MF.getFunction())->getInstrInfo());
    AliasAnalysis* AA = nullptr;
    AAResultsWrapperPass* AARWPass =
        getAnalysisIfAvailable<AAResultsWrapperPass>();
    if (AARWPass)
        AA = &AARWPass->getAAResults();
    if (tceIRBuilder_ == NULL) {
        interPassData_ = new InterPassData();
        tceIRBuilder_ =  new LLVMTCEIRBuilder(
            MF.getTarget(), tceMachine_, *interPassData_, AA, true, true);
        tceIRBuilder_->doInitialization(*mod_);
    }
    tceIRBuilder_->writeMachineFunction(MF);
    return false;
}
References llvm::LLVMTCEIRBuilder::doInitialization(), interPassData_, mod_, OperationPool::setLLVMTargetInstrInfo(), tceIRBuilder_, tceMachine_, and llvm::LLVMTCEIRBuilder::writeMachineFunction().
Member Data Documentation
ID
char llvm::LLVMTCEScheduler::ID = 0 static
Definition at line 49 of file LLVMTCEScheduler.hh.
interPassData_
InterPassData* llvm::LLVMTCEScheduler::interPassData_ private
Definition at line 57 of file LLVMTCEScheduler.hh.
Referenced by runOnMachineFunction().
mod_
llvm::Module* llvm::LLVMTCEScheduler::mod_ private
Definition at line 58 of file LLVMTCEScheduler.hh.
Referenced by doInitialization(), and runOnMachineFunction().
tceIRBuilder_
LLVMTCEIRBuilder* llvm::LLVMTCEScheduler::tceIRBuilder_ private
Definition at line 56 of file LLVMTCEScheduler.hh.
Referenced by runOnMachineFunction().
tceMachine_
TTAMachine::Machine* llvm::LLVMTCEScheduler::tceMachine_ private
Definition at line 55 of file LLVMTCEScheduler.hh.
Referenced by LLVMTCEScheduler(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
LLVMTCEScheduler.hh
LLVMTCEScheduler.cc