OpenASIP: ProximAboutCmd Class Reference
ProximAboutCmd Class Reference
#include <ProximAboutCmd.hh>
Public Member Functions
ProximAboutCmd ()
virtual ~ProximAboutCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximAboutCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for displaying Proxim about dialog.
Definition at line 42 of file ProximAboutCmd.hh.
Constructor & Destructor Documentation
ProximAboutCmd()
ProximAboutCmd::ProximAboutCmd ()
The Constructor.
Definition at line 41 of file ProximAboutCmd.cc.
                              :
    GUICommand(ProximConstants::COMMAND_NAME_ABOUT, NULL) {
}
Referenced by create().
~ProximAboutCmd()
ProximAboutCmd::~ProximAboutCmd () virtual
The Destructor.
Definition at line 49 of file ProximAboutCmd.cc.
{
}
Member Function Documentation
create()
ProximAboutCmd * ProximAboutCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 91 of file ProximAboutCmd.cc.
{
    return new ProximAboutCmd();
}
References ProximAboutCmd().
Do()
bool ProximAboutCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 57 of file ProximAboutCmd.cc.
                   {
    assert(parentWindow() != NULL);
    ProximAboutDialog dialog(parentWindow());
    dialog.ShowModal();
    return true;
}
References assert, and GUICommand::parentWindow().
icon()
std::string ProximAboutCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 71 of file ProximAboutCmd.cc.
{
    return "about.png";
}
id()
int ProximAboutCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 80 of file ProximAboutCmd.cc.
{
    return ProximConstants::COMMAND_ABOUT;
}
References ProximConstants::COMMAND_ABOUT.
isEnabled()
bool ProximAboutCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 102 of file ProximAboutCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximAboutCmd.hh
ProximAboutCmd.cc