OpenASIP: HDLGenerator::HDLOperation Class Reference
HDLGenerator::HDLOperation Class Reference
#include <HDLGenerator.hh>
Public Member Functions
HDLOperation ()
HDLOperation (std::string name, std::deque< std::string > impl, Language lang)
HDLOperation & operator<< (const std::string &rhs)
HDLOperation & operator<< (const std::string &&rhs)
void build () override
void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::deque< std::string > impl_
std::vector< std::string > readList_
Language lang_
Detailed Description
Represents VHDL operation snippet.
Definition at line 141 of file HDLGenerator.hh.
Constructor & Destructor Documentation
HDLOperation() [1/2]
HDLGenerator::HDLOperation::HDLOperation () inline
Definition at line 143 of file HDLGenerator.hh.
: SequentialStatement("no-op") {}
HDLOperation() [2/2]
HDLGenerator::HDLOperation::HDLOperation (std::string name, std::deque< std::string > impl, Language lang) inline
Definition at line 144 of file HDLGenerator.hh.
            : SequentialStatement(name), impl_(std::move(impl)), lang_(lang) {}
Member Function Documentation
build()
void HDLGenerator::HDLOperation::build () inline override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 158 of file HDLGenerator.hh.
{
            Generatable::build();
            for (auto&& r : readList_) {
                reads(r);
            }
        }
References HDLGenerator::Generatable::build(), readList_, and HDLGenerator::Generatable::reads().
hdl()
void HDLGenerator::HDLOperation::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 165 of file HDLGenerator.hh.
{
            if (lang != lang_)
                throw std::runtime_error(__PRETTY_FUNCTION__);
            for (auto&& line : impl_) {
                stream << StringTools::indent(level) <<  line << "\n";
            }
        }
References impl_, StringTools::indent(), and lang_.
operator<<() [1/2]
HDLOperation & HDLGenerator::HDLOperation::operator<< (const std::string && rhs) inline
Definition at line 153 of file HDLGenerator.hh.
{
            readList_.emplace_back(rhs);
            return *this;
        }
References readList_.
operator<<() [2/2]
HDLOperation & HDLGenerator::HDLOperation::operator<< (const std::string & rhs) inline
Definition at line 148 of file HDLGenerator.hh.
{
            readList_.emplace_back(rhs);
            return *this;
        }
References readList_.
Member Data Documentation
impl_
std::deque<std::string> HDLGenerator::HDLOperation::impl_ private
Definition at line 175 of file HDLGenerator.hh.
Referenced by hdl().
lang_
Language HDLGenerator::HDLOperation::lang_ private
Definition at line 177 of file HDLGenerator.hh.
Referenced by hdl().
readList_
std::vector<std::string> HDLGenerator::HDLOperation::readList_ private
Definition at line 176 of file HDLGenerator.hh.
Referenced by build(), operator<<(), and operator<<().
The documentation for this class was generated from the following file:
HDLGenerator.hh