OpenASIP: ConflictDetectionCodeGenerator Class Reference
ConflictDetectionCodeGenerator Class Reference
#include <ConflictDetectionCodeGenerator.hh>
Public Member Functions
ConflictDetectionCodeGenerator (const TTAMachine::Machine &machine, const CompiledSimSymbolGenerator &, bool conflictDetectionEnabled=false)
virtual ~ConflictDetectionCodeGenerator ()
std::string includes ()
std::string symbolDeclaration (const TTAMachine::FunctionUnit &fu)
std::string extraInitialization ()
std::string notifyOfConflicts ()
std::string updateSymbolDeclarations ()
std::string advanceClockCode ()
std::string detectConflicts (const TTAMachine::HWOperation &op)
bool conflictDetectionEnabled () const
Private Types
typedef std::map< std::string, std::string > ConflictDetectorObjectNameMap
1=fu.name(), 2=conflict detector object name
Private Member Functions
ConflictDetectionCodeGenerator (const ConflictDetectionCodeGenerator &)
Copying not allowed.
ConflictDetectionCodeGenerator & operator= (const ConflictDetectionCodeGenerator &)
Assignment not allowed.
Private Attributes
const TTAMachine::Machine & machine_
The machine.
bool conflictDetectionEnabled_
True, if the conflict detection is enabled.
std::string conflictDetectorType_
The FU resource conflict detector used, empty string if disabled.
std::string conflictDetectorMethod_
The method in the resource conflict detector used to detect conflicts, empty string if disabled.
std::string conflictDetectorAdvanceCycle_
The method to be called on the conflict detector on cycle advance.
std::string conflictDetectorExtraInitMethod_
A method to be called on the conflict detector for initialization, empty if none.
ConflictDetectorObjectNameMap conflictDetectors_
The resource conflict detector object name for each FU if any.
const CompiledSimSymbolGenerator & symbolGen_
Symbol generator.
Detailed Description
A class that generates C/C++ code for FU conflict detection cases
Used for the compiled simulation
Definition at line 67 of file ConflictDetectionCodeGenerator.hh.
Member Typedef Documentation
ConflictDetectorObjectNameMap
typedef std::map<std::string, std::string> ConflictDetectionCodeGenerator::ConflictDetectorObjectNameMap private
1=fu.name(), 2=conflict detector object name
Definition at line 109 of file ConflictDetectionCodeGenerator.hh.
Constructor & Destructor Documentation
ConflictDetectionCodeGenerator() [1/2]
ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator (const TTAMachine::Machine & machine, const CompiledSimSymbolGenerator & symbolGenerator, bool conflictDetectionEnabled = false)
The constructor.
Gets the conflict detection settings and initializes the generator
Parameters
machine The machine model
Definition at line 57 of file ConflictDetectionCodeGenerator.cc.
                                   :
    machine_(machine), conflictDetectionEnabled_(conflictDetectionEnabled),
    symbolGen_(symbolGenerator) {
    if (!conflictDetectionEnabled) {
        return;
    }
    string conflictDetectionSetting;
    std::string SETTING =
        Environment::environmentVariable("TTASIM_CONFLICT_DETECTOR");
    if (SETTING == "") {
        conflictDetectionSetting = "AFSA"; // by default
    } else {
        conflictDetectionSetting = SETTING;
    }
    if (conflictDetectionSetting == "CRT") {
        conflictDetectorType_ = "ReservationTableFUResourceConflictDetector";
        conflictDetectorMethod_ = "issueOperationInline";
        conflictDetectorAdvanceCycle_ = "advanceCycle";
        conflictDetectorExtraInitMethod_ = "";
    } else if (conflictDetectionSetting == "AFSA") {
        conflictDetectorType_ = "FSAFUResourceConflictDetector";
        conflictDetectorMethod_ = "issueOperationInline";
        conflictDetectorAdvanceCycle_ = "advanceCycle";
        conflictDetectorExtraInitMethod_ = "initializeAllStates";
    } else if (conflictDetectionSetting == "LFSA") {
        conflictDetectorType_ = "FSAFUResourceConflictDetector";
        conflictDetectorMethod_ = "issueOperationLazyInline";
        conflictDetectorAdvanceCycle_ = "advanceCycle";
        conflictDetectorExtraInitMethod_ = "";
    } else if (conflictDetectionSetting == "DCM") {
        conflictDetectorType_ = "DCMFUResourceConflictDetector";
        conflictDetectorMethod_ = "issueOperationInline";
        conflictDetectorAdvanceCycle_ = "advanceCycle";
        conflictDetectorExtraInitMethod_ = "";
    } else {
        Application::logStream()
            << "Unknown CONFLICT_DETECTION_SETTING: '"
            << conflictDetectionSetting << "'" << endl;
        conflictDetectionEnabled_ = false;
        return;
    }
    // initialize the detectors
    Application::logStream()
        << "Using conflict detector " << conflictDetectorType_ << std::endl;
    const Machine::FunctionUnitNavigator& fus =
        machine_.functionUnitNavigator();
    for (int i = 0; i < fus.count(); ++i) {
        const FunctionUnit& fu = *fus.item(i);
        if (!fu.needsConflictDetection()) { // no need for conflict detection?
            continue;
        } else {
            conflictDetectors_[fu.name()] =
                symbolGen_.conflictDetectorSymbol(fu);
        }
    }
    // No conflict detection is needed
    if (conflictDetectors_.empty()) {
        conflictDetectionEnabled_ = false;
    }
}
References conflictDetectionEnabled(), conflictDetectionEnabled_, conflictDetectorAdvanceCycle_, conflictDetectorExtraInitMethod_, conflictDetectorMethod_, conflictDetectors_, CompiledSimSymbolGenerator::conflictDetectorSymbol(), conflictDetectorType_, TTAMachine::Machine::Navigator< ComponentType >::count(), Environment::environmentVariable(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), Application::logStream(), machine_, TTAMachine::Component::name(), TTAMachine::FunctionUnit::needsConflictDetection(), and symbolGen_.
~ConflictDetectionCodeGenerator()
ConflictDetectionCodeGenerator::~ConflictDetectionCodeGenerator () virtual
The destructor
Definition at line 131 of file ConflictDetectionCodeGenerator.cc.
{
}
ConflictDetectionCodeGenerator() [2/2]
ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator (const ConflictDetectionCodeGenerator &) private
Copying not allowed.
Member Function Documentation
advanceClockCode()
string ConflictDetectionCodeGenerator::advanceClockCode ()
Generates code for a function that advances clocks of each conflict detector
Returns
A std::string containing generated code for the clock advances
Definition at line 234 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_)
        return "";
    std::stringstream ss;
    // advance clock of all conflict detection models
    for (ConflictDetectorObjectNameMap::const_iterator i =
        conflictDetectors_.begin(); i != conflictDetectors_.end(); ++i) {
        ss << "\t" << (*i).second << "."
           << conflictDetectorAdvanceCycle_ << "();" << endl;
    }
    return ss.str();
}
References conflictDetectionEnabled_, conflictDetectorAdvanceCycle_, and conflictDetectors_.
Referenced by CompiledSimCodeGenerator::generateAdvanceClockCode().
conflictDetectionEnabled()
bool ConflictDetectionCodeGenerator::conflictDetectionEnabled () const
Returns a boolean describing if the conflict detection is enabled or not
Returns
True if the conflict detection is enabled
Definition at line 288 of file ConflictDetectionCodeGenerator.cc.
{
    return conflictDetectionEnabled_;
}
References conflictDetectionEnabled_.
Referenced by ConflictDetectionCodeGenerator(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), and CompiledSimCodeGenerator::generateInstruction().
detectConflicts()
string ConflictDetectionCodeGenerator::detectConflicts (const TTAMachine::HWOperation & op)
Generates code for detecting an FU pipeline resource conflicts.
Parameters
op the triggered operation
Returns
A std::string containing generated code for the operation call
Definition at line 257 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_)
        return "";
    const TTAMachine::FunctionUnit& fu = *op.parentUnit();
    if (conflictDetectors_.find(fu.name()) == conflictDetectors_.end())
        return ""; // no conflict detection for the FU of the given operation
    int operationID = -1;
    for (int i = 0; i < fu.operationCount(); ++i) {
        if (fu.operation(i)->name() == op.name()) {
            operationID = i;
            break;
        }
    }
    std::stringstream ss;
    std::string detector = conflictDetectors_[fu.name()];
    ss << "engine.conflictDetected_ |= !engine." << detector << "."
       << conflictDetectorMethod_ << "(" << operationID << ");" << endl;
    return ss.str();
}
References conflictDetectionEnabled_, conflictDetectorMethod_, conflictDetectors_, TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), and TTAMachine::HWOperation::parentUnit().
Referenced by CompiledSimCodeGenerator::generateInstruction().
extraInitialization()
string ConflictDetectionCodeGenerator::extraInitialization ()
Generates exra initialization call for conflict detectors that require a one
Returns
The generated code for extra initialization call
Definition at line 174 of file ConflictDetectionCodeGenerator.cc.
{
    std::stringstream ss;
    if (conflictDetectionEnabled_ && conflictDetectorExtraInitMethod_ != "") {
        for (ConflictDetectorObjectNameMap::const_iterator i =
            conflictDetectors_.begin(); i != conflictDetectors_.end(); ++i) {
                ss << "\t" << i->second << "."
                   << conflictDetectorExtraInitMethod_ << "();" << std::endl;
        }
    }
    return ss.str();
}
References conflictDetectionEnabled_, conflictDetectorExtraInitMethod_, and conflictDetectors_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode().
includes()
string ConflictDetectionCodeGenerator::includes ()
Generates code for including the conflict detectors
Returns
The generated code for including the conflict detectors
Definition at line 139 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_)
        return "";
    std::stringstream ss;
    ss << "#include \"FSAFUResourceConflictDetector.hh\"" << endl << endl;
    return ss.str();
}
References conflictDetectionEnabled_.
Referenced by CompiledSimCodeGenerator::generateHeaderAndMainCode().
notifyOfConflicts()
string ConflictDetectionCodeGenerator::notifyOfConflicts ()
Generates code for notifying of detected conflicts
Returns
Generated code for notifying of detected conflicts
Definition at line 192 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_)
        return "";
    std::stringstream ss;
    ss << endl
       << "\tif (conflictDetected_) {" << endl
       << "\thaltSimulation(__FILE__, __LINE__, __FUNCTION__,"
       << "\"Conflict detected!\");" << endl
       << "\t}" << endl;
    return ss.str();
}
References conflictDetectionEnabled_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode().
operator=()
ConflictDetectionCodeGenerator & ConflictDetectionCodeGenerator::operator= (const ConflictDetectionCodeGenerator &) private
Assignment not allowed.
symbolDeclaration()
string ConflictDetectionCodeGenerator::symbolDeclaration (const TTAMachine::FunctionUnit & fu)
Creates symbol declaration code for the given FU's conflict detectors
Parameters
fu FU to create the conflict detector for
Returns
The generated symbol declaration code
Definition at line 156 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_ || !fu.needsConflictDetection())
        return "";
    std::stringstream ss;
    ss << "\t" << conflictDetectorType_ << " "
       << symbolGen_.conflictDetectorSymbol(fu) << ";" << endl;
    return ss.str();
}
References conflictDetectionEnabled_, CompiledSimSymbolGenerator::conflictDetectorSymbol(), conflictDetectorType_, TTAMachine::FunctionUnit::needsConflictDetection(), and symbolGen_.
Referenced by CompiledSimCodeGenerator::generateHeaderAndMainCode().
updateSymbolDeclarations()
string ConflictDetectionCodeGenerator::updateSymbolDeclarations ()
Generates code for notifying of detected conflicts
Returns
Generated code for notifying of detected conflicts
Definition at line 213 of file ConflictDetectionCodeGenerator.cc.
{
    if (!conflictDetectionEnabled_)
        return "";
    std::stringstream ss;
    for (ConflictDetectorObjectNameMap::const_iterator i =
        conflictDetectors_.begin(); i != conflictDetectors_.end(); ++i) {
    ss << "\t," << i->second
       << "(functionUnit(\"" << i->first << "\"))"
       << endl;
    }
    return ss.str();
}
References conflictDetectionEnabled_, and conflictDetectors_.
Referenced by CompiledSimCodeGenerator::updateDeclaredSymbolsList().
Member Data Documentation
conflictDetectionEnabled_
bool ConflictDetectionCodeGenerator::conflictDetectionEnabled_ private
True, if the conflict detection is enabled.
Definition at line 95 of file ConflictDetectionCodeGenerator.hh.
Referenced by advanceClockCode(), ConflictDetectionCodeGenerator(), conflictDetectionEnabled(), detectConflicts(), extraInitialization(), includes(), notifyOfConflicts(), symbolDeclaration(), and updateSymbolDeclarations().
conflictDetectorAdvanceCycle_
std::string ConflictDetectionCodeGenerator::conflictDetectorAdvanceCycle_ private
The method to be called on the conflict detector on cycle advance.
Definition at line 103 of file ConflictDetectionCodeGenerator.hh.
Referenced by advanceClockCode(), and ConflictDetectionCodeGenerator().
conflictDetectorExtraInitMethod_
std::string ConflictDetectionCodeGenerator::conflictDetectorExtraInitMethod_ private
A method to be called on the conflict detector for initialization, empty if none.
Definition at line 106 of file ConflictDetectionCodeGenerator.hh.
Referenced by ConflictDetectionCodeGenerator(), and extraInitialization().
conflictDetectorMethod_
std::string ConflictDetectionCodeGenerator::conflictDetectorMethod_ private
The method in the resource conflict detector used to detect conflicts, empty string if disabled.
Definition at line 101 of file ConflictDetectionCodeGenerator.hh.
Referenced by ConflictDetectionCodeGenerator(), and detectConflicts().
conflictDetectors_
ConflictDetectorObjectNameMap ConflictDetectionCodeGenerator::conflictDetectors_ private
The resource conflict detector object name for each FU if any.
Definition at line 111 of file ConflictDetectionCodeGenerator.hh.
Referenced by advanceClockCode(), ConflictDetectionCodeGenerator(), detectConflicts(), extraInitialization(), and updateSymbolDeclarations().
conflictDetectorType_
std::string ConflictDetectionCodeGenerator::conflictDetectorType_ private
The FU resource conflict detector used, empty string if disabled.
Definition at line 98 of file ConflictDetectionCodeGenerator.hh.
Referenced by ConflictDetectionCodeGenerator(), and symbolDeclaration().
machine_
const TTAMachine::Machine& ConflictDetectionCodeGenerator::machine_ private
The machine.
Definition at line 92 of file ConflictDetectionCodeGenerator.hh.
Referenced by ConflictDetectionCodeGenerator().
symbolGen_
const CompiledSimSymbolGenerator& ConflictDetectionCodeGenerator::symbolGen_ private
Symbol generator.
Definition at line 114 of file ConflictDetectionCodeGenerator.hh.
Referenced by ConflictDetectionCodeGenerator(), and symbolDeclaration().
The documentation for this class was generated from the following files:
ConflictDetectionCodeGenerator.hh
ConflictDetectionCodeGenerator.cc