OpenASIP: UnitFigure Class Reference
UnitFigure Class Reference
#include <UnitFigure.hh>
Public Member Functions
UnitFigure ()
virtual ~UnitFigure ()
void setName (const wxString &name)
void setInfo (const wxString &info)
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layout (wxDC *)
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
virtual void drawSelf (wxDC *)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
Private Member Functions
UnitFigure & operator= (UnitFigure &old)
Assignment not allowed.
UnitFigure (UnitFigure &old)
Copying not allowed.
Private Attributes
wxString type_
Type identifier of the unit.
wxString name_
Name of the unit.
wxString info_
Extra information string describing the unit.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(0, 0, 0)
Default colour for the figure.
static const wxColour DEFAULT_BG_COLOUR = wxColour(255, 255, 255)
Default background colour for the figure.
static const wxColour DEFAULT_INFO_TEXT_COLOUR = wxColour(150, 150, 150)
Default info string colour for the figure.
static const int MARGIN = 5
Top and bottom margin in pixels.
static const int SPACING = 5
Space between text rows in pixels.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a unit.
Definition at line 46 of file UnitFigure.hh.
Constructor & Destructor Documentation
UnitFigure() [1/2]
UnitFigure::UnitFigure ()
The Constructor.
Definition at line 60 of file UnitFigure.cc.
                      : Figure() {
    minSize_ = wxSize(
        MachineCanvasLayoutConstraints::UNIT_WIDTH,
        MachineCanvasLayoutConstraints::UNIT_HEIGHT);
    size_ = minSize_;
}
References Figure::minSize_, Figure::size_, MachineCanvasLayoutConstraints::UNIT_HEIGHT, and MachineCanvasLayoutConstraints::UNIT_WIDTH.
~UnitFigure()
UnitFigure::~UnitFigure () virtual
The Destructor.
Definition at line 70 of file UnitFigure.cc.
{
}
UnitFigure() [2/2]
UnitFigure::UnitFigure (UnitFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void UnitFigure::drawSelf (wxDC * dc) protected virtual
Draws the function unit's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from Figure.
Definition at line 80 of file UnitFigure.cc.
{
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    dc->SetPen(pen);
    wxBrush brush = wxBrush(DEFAULT_BG_COLOUR, wxSOLID);
    if (highlighted_) {
        brush = wxBrush(highlight_, wxSOLID);
    }
    dc->SetBrush(brush);
    const bool drawInfoRow =
        (options() != NULL &&
         options()->optionValue(
             MachineCanvasOptions::SHOW_UNIT_INFO_STRING).isFlagOn());
    if (type_ == _T("FU:")) {
        if (!highlighted_) {
            if (info_.StartsWith(_T("{ AS:"))) {
                dc->SetBrush(wxBrush(wxColour(170,255,170),wxSOLID));
            } else {
                dc->SetBrush(wxBrush(wxColour(205,205,255),wxSOLID));
            }
        } else {
            if (info_.StartsWith(_T("{ AS:"))) {
                dc->SetBrush(wxBrush(wxColour((53+highlight_.Red()*2)/3,
                                              (82+highlight_.Green()*2)/3,
                                              (53+highlight_.Blue()*2)/3),
                                     wxSOLID));
            } else {
                dc->SetBrush(wxBrush(wxColour((68+highlight_.Red()*2)/3,
                                              (68+highlight_.Green()*2)/3,
                                              (82+highlight_.Blue()*2)/3),
                                     wxSOLID));
            }
        }
        dc->DrawRoundedRectangle(
            location_.x, location_.y, size_.GetWidth(),
            size_.GetHeight(), size_.GetHeight()*0.25);
    } else if (type_ == _T("GCU:")) {
        dc->SetBrush(wxBrush(wxColour(250,145,255), wxSOLID));
        dc->DrawRoundedRectangle(
            location_.x, location_.y, size_.GetWidth(),
            size_.GetHeight(), size_.GetHeight()*0.4);
    } else if (type_ == _T("IMM:")) {
        dc->SetBrush(wxBrush(wxColour(255,168,140),wxSOLID));
        wxPoint points[4];
        points[0] = wxPoint(size_.GetWidth()/2-10, size_.GetHeight());
        points[1] = wxPoint(size_.GetWidth()/2+10, size_.GetHeight());
        points[2] = wxPoint(size_.GetWidth(),0);
        points[3] = wxPoint(0,0);
        dc->DrawPolygon(
            4, points,
            location_.x, location_.y,
            wxODDEVEN_RULE);
    } else { // register file
        dc->SetBrush(wxBrush(wxColour(240,230,150),wxSOLID));
        dc->DrawRectangle(
            location_.x, location_.y, size_.GetWidth(),
            size_.GetHeight());
    }
    dc->SetBackgroundMode(wxTRANSPARENT);
    dc->SetTextForeground(DEFAULT_COLOUR);
    int typeWidth = 0;
    int typeHeight = 0;
    if (drawInfoRow) {
        dc->GetTextExtent(type_, &typeWidth, &typeHeight);
        int typeX = location_.x + size_.GetWidth() / 2 - typeWidth / 2;
        int typeY = location_.y + MARGIN;
        dc->DrawText(type_, typeX, typeY);
    }
    int nameWidth;
    int nameHeight;
    wxFont oldFont = dc->GetFont();
    if (!drawInfoRow) {
        // In case we do not write the details (operation set) to the unit,
        // print the name of the unit larger.
        dc->SetFont(wxFont(16, wxDEFAULT, wxNORMAL, wxNORMAL));
    }
    dc->GetTextExtent(name_, &nameWidth, &nameHeight);
    int nameX = location_.x + size_.GetWidth() / 2 - nameWidth / 2;
    int nameY = location_.y + MARGIN + typeHeight + SPACING;
    dc->DrawText(name_, nameX, nameY);
    if (!drawInfoRow) {
        dc->SetFont(oldFont);
    }
    if (drawInfoRow) {
        int infoWidth;
        int infoHeight;
        dc->GetTextExtent(info_, &infoWidth, &infoHeight);
        int infoX = location_.x + size_.GetWidth() / 2 - infoWidth / 2;
        int infoY =
            location_.y + MARGIN + typeHeight + SPACING + nameHeight + SPACING;
        dc->SetTextForeground(DEFAULT_INFO_TEXT_COLOUR);
        dc->DrawText(info_, infoX, infoY);
    }
}
References DEFAULT_BG_COLOUR, DEFAULT_COLOUR, DEFAULT_INFO_TEXT_COLOUR, Figure::highlight_, Figure::highlighted_, info_, OptionValue::isFlagOn(), Figure::location_, MARGIN, name_, Figure::options(), Options::optionValue(), MachineCanvasOptions::SHOW_UNIT_INFO_STRING, Figure::size_, SPACING, and type_.
layout()
void UnitFigure::layout (wxDC * dc) protected virtual
Lays the figure out.
Figure of the unit is laid out before it's children, so that the port Y-coordinate can be set correctly when laying out the ports.
Parameters
dc Device cotnext to lay the figure out on.
Reimplemented from Figure.
Definition at line 336 of file UnitFigure.cc.
{
    layoutSelf(dc);
    layoutChildren(dc);
    laidOut_ = true;
}
References Figure::laidOut_, layoutChildren(), and layoutSelf().
layoutChildren()
void UnitFigure::layoutChildren (wxDC * dc) protected virtual
Lays out the ports to the bottom of the fu's Figure, spaced evenly.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 196 of file UnitFigure.cc.
{
    // Sort port child figures to containers based on port directions.
    // Map with portname, figure pairs is used so that the ports
    // are automatically ordered by the port name.
    map<std::string, Figure*> inputPorts;
    map<std::string, Figure*> outputPorts;
    map<std::string, Figure*> bidirPorts;
    map<std::string, Figure*> trigPorts;
    map<std::string, Figure*> nodirPorts;
    vector<Figure*>::iterator i = children_.begin();
    for(; i != children_.end(); i++) {
        UnitPortFigure* fig = dynamic_cast<UnitPortFigure*>(*i);
        assert(fig != NULL);
        bool input = false;
        bool output = false;
        for (int j = 0; j < (fig->childCount()); j++) {
            Figure* socketFig = fig->child(j);
            if (dynamic_cast<InputSocketFigure*>(socketFig) != NULL) {
                input = true;
            } else if (dynamic_cast<OutputSocketFigure*>(socketFig) != NULL) {
                output = true;
            }
        }
        if (input && dynamic_cast<TriggeringPortFigure*>(fig) != NULL) {
            trigPorts[fig->name()] = fig;
        } else if (input && output) {
            bidirPorts[fig->name()] =  fig;
        } else if (input) {
            inputPorts[fig->name()]  = fig;
        } else if (output) {
            outputPorts[fig->name()] = fig;
        } else {
            nodirPorts[fig->name()] = fig;
        }
    }
    int portX = location_.x + MachineCanvasLayoutConstraints::PORT_SPACE;
    int portY = location_.y + size_.GetHeight();
    // if only single port, put it to middle.
    if (children_.size() == 1) {
        portX = location_.x + (size_.GetWidth()- children_[0]->bounds().GetWidth()) / 2;
    }
    // Layout input ports.
    map<std::string, Figure*>::iterator inIter = inputPorts.begin();
    for (; inIter != inputPorts.end(); inIter++) {
        portY -= (*inIter).second->bounds().GetHeight()/2;
        (*inIter).second->setLocation(wxPoint(portX, portY));
        (*inIter).second->layout(dc);
        portY = location_.y + size_.GetHeight();
        portX += (*inIter).second->bounds().GetWidth() +
            MachineCanvasLayoutConstraints::PORT_SPACE;
    }
    // Layout triggering ports.
    map<std::string, Figure*>::iterator trigIter = trigPorts.begin();
    for (; trigIter != trigPorts.end(); trigIter++) {
        portY -= (*trigIter).second->bounds().GetHeight()/2;
        (*trigIter).second->setLocation(wxPoint(portX, portY));
        (*trigIter).second->layout(dc);
        portY = location_.y + size_.GetHeight();
        portX += (*trigIter).second->bounds().GetWidth() +
            MachineCanvasLayoutConstraints::PORT_SPACE;
    }
    // Layout bidirectional ports.
    map<std::string, Figure*>::iterator bdIter = bidirPorts.begin();
    for (; bdIter != bidirPorts.end(); bdIter++) {
        portY -= (*bdIter).second->bounds().GetHeight()/2;
        (*bdIter).second->setLocation(wxPoint(portX, portY));
        (*bdIter).second->layout(dc);
        portY = location_.y + size_.GetHeight();
        portX += (*bdIter).second->bounds().GetWidth() +
            MachineCanvasLayoutConstraints::PORT_SPACE;
    }
    // Layout output ports.
    map<std::string, Figure*>::iterator outIter = outputPorts.begin();
    for (; outIter != outputPorts.end(); outIter++) {
        portY -= (*outIter).second->bounds().GetHeight()/2;
        (*outIter).second->setLocation(wxPoint(portX, portY));
        (*outIter).second->layout(dc);
        portY = location_.y + size_.GetHeight();
        portX += (*outIter).second->bounds().GetWidth() +
            MachineCanvasLayoutConstraints::PORT_SPACE;
    }
    // Layout ports w/ no direction.
    map<std::string, Figure*>::iterator ndIter = nodirPorts.begin();
    for (; ndIter != nodirPorts.end(); ndIter++) {
        portY -= (*ndIter).second->bounds().GetHeight()/2;
        (*ndIter).second->setLocation(wxPoint(portX, portY));
        (*ndIter).second->layout(dc);
        portY = location_.y + size_.GetHeight();
        portX += (*ndIter).second->bounds().GetWidth() +
            MachineCanvasLayoutConstraints::PORT_SPACE;
    }
}
References assert, Figure::bounds(), Figure::child(), Figure::childCount(), Figure::children_, Figure::location_, UnitPortFigure::name(), MachineCanvasLayoutConstraints::PORT_SPACE, and Figure::size_.
Referenced by layout().
layoutSelf()
void UnitFigure::layoutSelf (wxDC * dc) protected virtual
Calculates and sets the size of the unit.
Depends on its name and the amount of ports.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 350 of file UnitFigure.cc.
{
    bool showInfo = (options() != NULL) && options()->optionValue(
        MachineCanvasOptions::SHOW_UNIT_INFO_STRING).isFlagOn();
    int portsWidth = 0;
    vector<Figure*>::const_iterator i = children_.begin();
    for (; i != children_.end(); i++) {
        portsWidth += (*i)->bounds().GetWidth();
    }
    portsWidth +=
        (children_.size()+1) * MachineCanvasLayoutConstraints::PORT_SPACE;
    int nameWidth = 0;
    int nameHeight = 0;
    int infoWidth = 0;
    int infoHeight = 0;
    int typeWidth = 0;
    int typeHeight = 0;
    dc->GetTextExtent(name_, &nameWidth, &nameHeight);
    dc->GetTextExtent(type_, &typeWidth, &typeHeight);
    if (showInfo) {
        dc->GetTextExtent(info_, &infoWidth, &infoHeight);
    }
    nameWidth += MARGIN * 4;
    typeWidth += MARGIN * 4;
    infoWidth += MARGIN * 4;
    int maxWidth = MachineCanvasLayoutConstraints::MAX_UNIT_NAME_WIDTH;
    if (portsWidth > maxWidth) {
        maxWidth = portsWidth;
    }
    if ((nameWidth + 2 * MARGIN) > maxWidth) {
        unsigned int chars = 0;
        int charsExtent = 0;
        while ((charsExtent + 2 * MARGIN) < maxWidth) {
            int charWidth = 0;
            int charHeight = 0;
            dc->GetTextExtent(name_.GetChar(chars), &charWidth, &charHeight);
            charsExtent += charWidth;
            chars++;
            if (chars > name_.Len()) {
                break;
            }
        }
        name_.Truncate(chars - 5);
        name_.Append(_T("..."));
        dc->GetTextExtent(name_, &nameWidth, &nameHeight);
        nameWidth += 4 * MARGIN;
    }
    if (showInfo && (infoWidth + 2 * MARGIN) > maxWidth) {
        unsigned int chars = 0;
        int charsExtent = 0;
        while ((charsExtent + 2 * MARGIN) < maxWidth) {
            int charWidth = 0;
            int charHeight = 0;
            dc->GetTextExtent(info_.GetChar(chars), &charWidth, &charHeight);
            charsExtent += charWidth;
            chars++;
            if (chars > info_.Len()) {
                break;
            }
        }
        info_.Truncate(chars - 5);
        info_.Append(_T("..."));
        dc->GetTextExtent(info_, &infoWidth, &infoHeight);
        infoWidth += 4 * MARGIN;
    }
    if (infoWidth > size_.GetWidth() &&
        infoWidth >= nameWidth && infoWidth > portsWidth) {
        size_.SetWidth(infoWidth);
    } else if (nameWidth > size_.GetWidth() &&
               nameWidth > infoWidth && nameWidth > portsWidth) {
        size_.SetWidth(nameWidth);
    } else if (portsWidth > size_.GetWidth()) {
        size_.SetWidth(portsWidth);
    }
    // Set figure height.
    int height = 2 * MARGIN +  SPACING +  nameHeight +
        (MachineCanvasLayoutConstraints::PORT_WIDTH / 2);
    if (showInfo) {
        height += typeHeight + SPACING + infoHeight;
    }
    if (height > minSize_.GetHeight()) {
        size_.SetHeight(height);
    }
}
References Figure::children_, info_, OptionValue::isFlagOn(), MARGIN, MachineCanvasLayoutConstraints::MAX_UNIT_NAME_WIDTH, Figure::minSize_, name_, Figure::options(), Options::optionValue(), MachineCanvasLayoutConstraints::PORT_SPACE, MachineCanvasLayoutConstraints::PORT_WIDTH, MachineCanvasOptions::SHOW_UNIT_INFO_STRING, Figure::size_, SPACING, and type_.
Referenced by layout().
operator=()
UnitFigure & UnitFigure::operator= (UnitFigure & old) private
Assignment not allowed.
setInfo()
void UnitFigure::setInfo (const wxString & info)
Sets the information string of the unit.
Parameters
info New info string..
Definition at line 323 of file UnitFigure.cc.
{
    info_ = info;
}
References info_.
Referenced by FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), and RFFactory::createEditPart().
setName()
void UnitFigure::setName (const wxString & name)
Sets the name of the unit.
Parameters
name New name.
Definition at line 304 of file UnitFigure.cc.
{
    int index = name.Find(':');
    if (index == -1) {
        type_ = _T("Unit:");
        name_ = name;
    } else {
        type_ = name.Mid(0, index + 1);
        type_.Trim();
        name_ = name.Mid(index + 2);
        name_.Trim();
    }
}
References name_, and type_.
Referenced by FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), and RFFactory::createEditPart().
Member Data Documentation
DEFAULT_BG_COLOUR
const wxColour UnitFigure::DEFAULT_BG_COLOUR = wxColour(255, 255, 255) static private
Default background colour for the figure.
Definition at line 76 of file UnitFigure.hh.
Referenced by drawSelf().
DEFAULT_COLOUR
const wxColour UnitFigure::DEFAULT_COLOUR = wxColour(0, 0, 0) static private
Default colour for the figure.
Definition at line 74 of file UnitFigure.hh.
Referenced by drawSelf().
DEFAULT_INFO_TEXT_COLOUR
const wxColour UnitFigure::DEFAULT_INFO_TEXT_COLOUR = wxColour(150, 150, 150) static private
Default info string colour for the figure.
Definition at line 78 of file UnitFigure.hh.
Referenced by drawSelf().
info_
wxString UnitFigure::info_ private
Extra information string describing the unit.
Definition at line 71 of file UnitFigure.hh.
Referenced by drawSelf(), layoutSelf(), and setInfo().
MARGIN
const int UnitFigure::MARGIN = 5 static private
Top and bottom margin in pixels.
Definition at line 80 of file UnitFigure.hh.
Referenced by drawSelf(), and layoutSelf().
name_
wxString UnitFigure::name_ private
Name of the unit.
Definition at line 69 of file UnitFigure.hh.
Referenced by drawSelf(), layoutSelf(), and setName().
SPACING
const int UnitFigure::SPACING = 5 static private
Space between text rows in pixels.
Definition at line 82 of file UnitFigure.hh.
Referenced by drawSelf(), and layoutSelf().
type_
wxString UnitFigure::type_ private
Type identifier of the unit.
Definition at line 67 of file UnitFigure.hh.
Referenced by drawSelf(), layoutSelf(), and setName().
The documentation for this class was generated from the following files:
UnitFigure.hh
UnitFigure.cc