OpenASIP: Conversion Class Reference
Conversion Class Reference
#include <Conversion.hh>
Static Public Member Functions
template<typename T >
static std::string toString (const T &source)
static std::string toString (double source, unsigned precision)
static std::string toString (bool source)
static std::string XMLChToString (const XMLCh *source)
static XMLCh * toXMLCh (const std::string &string)
template<typename T >
static int toInt (const T &source)
template<typename T >
static SLongWord toLong (const T &source)
static int toInt (const double &source)
static SLongWord toLong (const double &source)
template<typename T >
static unsigned int toUnsignedInt (const T &source)
template<typename T >
static ULongWord toUnsignedLong (const T &source)
template<typename T >
static double toDouble (const T &source)
template<typename T >
static float toFloat (const T &source)
static std::string toBinString (int source)
static std::string toBinString (double source)
static std::string toBinary (unsigned int source, unsigned int stringWidth=0)
template<typename T >
static std::string toHexString (T source, std::size_t digits=0, bool include0x=true)
static std::string floatToHexString (float source, bool include0x=true)
static std::string doubleToHexString (double source, bool include0x=true)
static void toRawData (const std::string &hexSource, unsigned char *target)
Static Private Member Functions
template<typename SourceType , typename DestType , bool destIsNumeric>
static void convert (const SourceType &source, DestType &dest)
static bool restWhiteSpace (std::istream &str)
Detailed Description
Definition at line 52 of file Conversion.hh.
Member Function Documentation
convert()
template<typename SourceType , typename DestType , bool destIsNumeric> static void Conversion::convert (const SourceType & source, DestType & dest) static private
doubleToHexString()
std::string Conversion::doubleToHexString (double source, bool include0x = true) static
Specialized version of toHexString() for double type with fixed digit count (16).
Definition at line 260 of file Conversion.cc.
{
    unsigned char* bytes = (unsigned char*) &source;
    std::stringstream str;
    if (include0x) {
        str << "0x";
    }
    for (size_t i = 0; i < sizeof(double); i++) {
#if HOST_BIGENDIAN == 1
        unsigned int value = (unsigned int)bytes[i];
#else
        unsigned int value = (unsigned int)bytes[sizeof(double)-i-1];
#endif
        value &= 0xff;
        str << std::setfill('0') << std::setw(2) << std::hex << value;
    }
    return std::string(str.str());
}
floatToHexString()
std::string Conversion::floatToHexString (float source, bool include0x = true) static
Specialized version of toHexString() for float type with fixed digit count (8).
Definition at line 231 of file Conversion.cc.
{
    union {
        float f;
        int i;
    } conv;
    conv.f = source;
    std::stringstream str;
    str << std::setw(8) << std::setfill('0') << std::right << std::hex
        << conv.i;
    std::string result = "";
    str >> result;
    if (include0x) {
        result.insert(0, "0x");
    }
    return result;
}
restWhiteSpace()
bool Conversion::restWhiteSpace (std::istream & str) static private
Returns true if rest of the stream is only white space.
Given stream is read, that is, it is not in the same state as it was before the function call.
Parameters
str The stream to check.
Returns
True if there's no garbage in stream.
Definition at line 57 of file Conversion.cc.
{
    string temp = "";
    str >> temp;
    if (!str.fail()) {
        // if the stream contains non-white-space characters, the
        // stream will not fail in the next read
        return false;
    }
    return true;
}
toBinary()
std::string Conversion::toBinary (unsigned int source, unsigned int stringWidth = 0) static
Converts an integer to the string which is in binary format.
The width of the returned string is given too. If the width is greater than required, the number is zero-extended. If the width is smaller than required, the most significant bits are reduced. If '0' is given in stringWidth, the binary string is not extended, nor reduced. This is the default value.
Parameters
source An integer to be converted into a binary string.
stringWidth The width of the returned string.
Returns
The binary string.
Definition at line 155 of file Conversion.cc.
{
    std::string result = "";
    for (unsigned int i = 0; i < sizeof(unsigned int) * 8; i++) {
        if ((source & 0x80000000) != 0) {
            result.append("1");
        } else {
            result.append("0");
        }
        source <<= 1;
    }
    if (stringWidth == 0) {
        string::size_type firstOne = result.find("1");
        if (firstOne != string::npos) {
            result = result.substr(firstOne, string::npos);
        } else {
            result = "0";
        }
    } else {
        if (result.length() > stringWidth) {
            result = result.substr(
                result.length() - stringWidth, string::npos);
        } else if (result.length() < stringWidth) {
            int zerosToAdd = stringWidth - result.length();
            for (int i = 0; i < zerosToAdd; i++) {
                result.insert(0, "0");
            }
        }
    }
    return result;
}
Referenced by SimValue::binaryValue(), FUTestbenchGenerator::createStimulusArrays(), SimValue::dump(), DefaultICGenerator::generateInputMux(), MemoryGridTable::memoryContents(), MemoryValueDialog::onOK(), portCodeBits(), printGuardFieldEncodings(), printImmediateControlField(), printSlotFieldEncodings(), printSourceFieldEncodings(), toBinString(), and TestbenchGenerator::writeStimulusArray().
toBinString() [1/2]
string Conversion::toBinString (double source) static
Converts a double to binary representation.
Parameters
source Double to be converted.
Returns
Double as binary string.
Definition at line 95 of file Conversion.cc.
{
    union castUnion {
        double d;
        struct {int w1; int w2;} s;
    };
    castUnion cast;
    cast.d = source;
    std::string result = "";
    for (unsigned int i = 0; i < sizeof(int) * 8; i++) {
        if ((cast.s.w1 & 0x80000000) != 0) {
            result.append("1");
        } else {
            result.append("0");
        }
        cast.s.w1 <<= 1;
    }
    for (unsigned int i = 0; i < sizeof(int) * 8; i++) {
        if ((cast.s.w2 & 0x80000000) != 0) {
            result.append("1");
        } else {
            result.append("0");
        }
        cast.s.w2 <<= 1;
    }
    string::size_type firstOne = result.find("1");
    if (firstOne != string::npos) {
        result = result.substr(firstOne, string::npos);
    } else {
        result = "0";
    }
    result.append("b");
    return result;
}
toBinString() [2/2]
std::string Conversion::toBinString (int source) static
Converts and integer to the string which is in binary format.
Binary format includes a 'b' character at the end of the string.
Parameters
source An integer to be converted into a binary string.
Returns
Returns the binary string.
Definition at line 81 of file Conversion.cc.
{
    string result = toBinary(source);
    result.append("b");
    return result;
}
References toBinary().
Referenced by SimulateDialog::formattedValue(), ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), NumberControl::update(), and ProximPortWindow::update().
toDouble()
template<typename T > static double Conversion::toDouble (const T & source) static
Referenced by MachineResourceModifier::analyzeBuses(), MachineResourceModifier::analyzeFunctionUnits(), MachineResourceModifier::analyzeRegisters(), ObjectState::doubleAttribute(), DataObject::doubleValue(), OperationSimulator::initializeSimValue(), NumberControl::onText(), and TestApplication::TestApplication().
toFloat()
template<typename T > static float Conversion::toFloat (const T & source) static
Referenced by ConfigurationFile::checkSemantics(), DataObject::floatValue(), ConfigurationFile::floatValue(), OperationSimulator::initializeSimValue(), and NumberControl::onText().
toHexString()
template<typename T > static std::string Conversion::toHexString (T source, std::size_t digits = 0, bool include0x = true) static
Referenced by ProximFUPortDetailsCmd::Do(), SimValue::dump(), InfoProcCommand::execute(), MemDumpCommand::execute(), TPEFDumper::fileArchString(), TPEFDumper::fileTypeString(), SimulateDialog::formattedValue(), MemoryGridTable::GetColLabelValue(), MemoryGridTable::GetRowLabelValue(), TTAMachine::Machine::hash(), SimValue::hexValue(), ProximRegisterWindow::loadImmediateUnit(), ProximMemoryWindow::loadMemory(), ProximRegisterWindow::loadRegisterFile(), DataDependenceGraphBuilder::memoryCategory(), MemoryGridTable::memoryContents(), LLVMBackend::pluginFilename(), TPEFDumper::relocTypeString(), TPEFDumper::resourceIdString(), TPEFDumper::resourceTypeString(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TPEFDumper::sectionTypeString(), TPEFDumper::symbolBindString(), TPEFDumper::symbolTypeString(), NumberControl::update(), and ProximPortWindow::update().
toInt() [1/2]
static int Conversion::toInt (const double & source) static
toInt() [2/2]
template<typename T > static int Conversion::toInt (const T & source) static
Referenced by MachineResourceModifier::analyzeBuses(), MachineResourceModifier::analyzeFunctionUnits(), MachineResourceModifier::analyzeRegisters(), ObjectState::boolAttribute(), ControlFlowGraph::buildMBBFromBB(), CostDatabase::buildRegisterFiles(), ConfigurationFile::checkSemantics(), CompiledSimCompiler::CompiledSimCompiler(), TPEFDisassembler::createDisassemblyElement(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), TTAProgram::TPEFProgramFactory::createTerminal(), createTerminalFUPort(), TTAProgram::CodeGenerator::createTerminalRegister(), SetFUArchitectureCmd::Do(), SetRFArchitectureCmd::Do(), EPSDC::DoGetTextExtent(), BlockImplementationDialog::doOK(), CmdMem::execute(), TPEF::AOutSymbolSectionReader::finalize(), findFUPort(), TTAProgram::TPEFProgramFactory::findGuard(), SimulatorFrontend::findPort(), DataDependenceGraphBuilder::findStaticRegisters(), TDGen::getLLVMPatternWithConstants(), ProGe::NetlistTools::getUniqueInstanceName(), TTAProgram::TPEFResourceUpdater::initCache(), ObjectState::intAttribute(), DataObject::integerValue(), TTAProgram::ProgramAnnotation::intValue(), ConfigurationFile::intValue(), Operand::loadState(), MachineInfo::maxMemoryAlignment(), numbersToAscending(), InputOperandDialog::onAddSwap(), OperationDialog::onBindOperand(), OperationPropertyDialog::onDeleteInputOperand(), OperationDialog::onDeleteOperand(), OperationPropertyDialog::onDeleteOutputOperand(), InputOperandDialog::onDeleteSwap(), MemoryControl::onGoTo(), OperationPropertyDialog::onModifyInputOperand(), OperationPropertyDialog::onModifyOutputOperand(), OperationPropertyDialog::onMoveInputDown(), OperationPropertyDialog::onMoveInputUp(), OperationPropertyDialog::onMoveOutputDown(), OperationPropertyDialog::onMoveOutputUp(), CostEstimationDataDialog::onOK(), OperationDialog::onOperandSelection(), OperationPropertyDialog::onSelection(), NumberControl::onText(), SimulateDialog::onUpdateValue(), MemoryControl::onWriteMemory(), HDBBrowserWindow::openLink(), MachineResourceModifier::percentualFUIncrease(), MachineResourceModifier::percentualRegisterIncrease(), ProGe::VerilogNetlistWriter::portSignalType(), ProGe::VHDLNetlistWriter::portSignalType(), ProGe::NetlistPort::resolveRealWidth(), InlineAsmParser::substituteAsmString(), ConfigurationFile::timeStampValue(), toRawData(), OperationPropertyDialog::updateSwapLists(), TDGenerator::ValueType::valueType(), ProGe::VHDLNetlistWriter::writeComponentDeclarations(), ProGe::VerilogNetlistWriter::writePortDeclaration(), and ProGe::VHDLNetlistWriter::writePortDeclaration().
toLong() [1/2]
static SLongWord Conversion::toLong (const double & source) static
toLong() [2/2]
template<typename T > static SLongWord Conversion::toLong (const T & source) static
Referenced by OperationSimulator::initializeSimValue(), TokenizerData::Token::intValue(), and DataObject::longValue().
toRawData()
void Conversion::toRawData (const std::string & hexSource, unsigned char * target) static
Converts bytes of a string hexadecimal value to target buffer.
Hex value can be in "0x" format or without the prefix. Caller is responsible for checking that the target buffer has enough allocated memory for conversion.
Parameters
source Hex value.
target Buffer where hex value bits are converted to.
Definition at line 201 of file Conversion.cc.
{
    std::string hexValue = hexSource;
    std::stringstream hexStream;
    hexStream << hexSource;
    char first = hexStream.get();
    char second = hexStream.get();
    if (first == '0' && second == 'x') {
        hexValue = hexSource.substr(2); // remove "0x"
    }
    // if number of hex numbers is uneven (e.g "12345FA"), insert additional
    // 0 to the front so that the hex numbers form N full bytes
    if (hexValue.size() % 2 == 1) {
        hexValue.insert(0, "0");
    }
    // start filling the input parameter 2 hex numbers (byte) at a time to
    // the data buffer
    for (size_t i = 0; i < hexValue.size(); i=i+2) {
        *target = toInt("0x" + hexValue.substr(i, 2));
        ++target;
    }
}
References toInt().
Referenced by SimValue::setValue().
toString() [1/3]
static std::string Conversion::toString (bool source) static
toString() [2/3]
template<typename T > static std::string Conversion::toString (const T & source) static
Referenced by AddFUFromHDBDialog::acceptToList(), ProGe::NetlistGenerator::addBaseRFToNetlist(), ExecutionTrace::addBusActivity(), HDB::HDBManager::addBusCostEstimationData(), ADFCombiner::addBuses(), MachineResourceModifier::addBusesByAmount(), ExecutionTrace::addBusWriteCount(), ExecutionTrace::addConcurrentRegisterFileAccessCount(), DSDBManager::addConfiguration(), HDB::HDBManager::addCostEstimationData(), DSDBManager::addCycleCount(), DSDBManager::addEnergyEstimate(), ControlFlowGraph::addExit(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUCostEstimationData(), HDB::HDBManager::addFUExternalPortsToImplementation(), HDB::HDBManager::addFUImplementation(), ExecutionTrace::addFunctionUnitOperationTriggerCount(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addGCUToNetlist(), DefaultDecoderGenerator::addGlockPortToDecoder(), DefaultICGenerator::addICToNetlist(), DSDBManager::addImplementation(), ExecutionTrace::addInstructionExecutionCount(), ProGe::ProcessorWrapperBlock::addInstructionMemory(), DefaultDecoderGenerator::addLockReqPortToDecoder(), AlteraMemGenerator::addMemory(), CodeSectionCreator::addMove(), VectorLSGenerator::addOperation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), AlmaIFIntegrator::addPortToAlmaIFBlock(), ExecutionTrace::addProcedureAddressRange(), ComponentAdder::addRegisterFiles(), MemorySystem::addressSpace(), TPEFDumper::addressSpaceString(), HDB::HDBManager::addRFArchitecture(), HDB::HDBManager::addRFCostEstimationData(), HDB::HDBManager::addRFExternalPortsToImplementation(), HDB::HDBManager::addRFImplementation(), HDB::HDBManager::addSocketCostEstimationData(), ExecutionTrace::addSocketWriteCount(), ADFCombiner::ADFCombiner(), TDGen::analyzeMachineRegisters(), TDGen::analyzeMachineVectorRegisterClasses(), DSDBManager::applicationPath(), DSDBManager::archConfigurationIDs(), DSDBManager::architectureString(), DSDBManager::areaEstimate(), IUResource::assign(), SimpleBrokerDirector::assign(), ExecutionPipelineResource::assignDestination(), ObjectState::attribute(), AlmaIFIntegrator::axiAddressWidth(), CompiledSimSymbolGenerator::basicBlockSymbol(), DefaultICGenerator::busAltSignal(), DefaultDecoderGenerator::busCntrlSignalPinOfSocket(), HDB::HDBManager::busCostEstimationData(), HDB::HDBManager::busCostEstimationDataIDs(), HDB::HDBManager::busCostEstimationDataList(), HDB::HDBManager::busEntryByIDQuery(), DefaultICGenerator::busMuxDataPort(), DefaultICGenerator::busWidthGeneric(), HDB::HDBManager::canRemoveFUArchitecture(), HDB::HDBManager::canRemoveRFArchitecture(), POMValidator::checkCompiledSimulatability(), POMValidator::checkConnectivity(), CopyingDelaySlotFiller::checkImmediatesAfter(), POMValidator::checkLongImmediates(), RegisterQuantityCheck::checkPredRegs(), POMValidator::checkSimulatability(), ObjectState::child(), CopyingDelaySlotFiller::collectMoves(), Assembler::compile(), CompiledSimulation::compileAndLoadFunction(), CompiledSimCompiler::compileDirectory(), DefaultDecoderGenerator::completeDecoderBlock(), ComponentAdder::ComponentAdder(), DSDBManager::configuration(), AlmaIFIntegrator::connectCoreMemories(), OperationDAGBuilder::connectOperandToNode(), ADFCombiner::connectRegisterFiles(), ADFCombiner::connectVectorLSU(), TDGen::constantNodeString(), DataDependenceGraphBuilder::constructIndividualBB(), DataDependenceGraphBuilder::constructIndividualFromInlineAsmBB(), HDB::HDBManager::containsFUArchitecture(), HDB::HDBManager::containsRFArchitecture(), GUIOptionsSerializer::convertToConfigFileFormat(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::costEstimationDataValue(), HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginDataIDs(), TTAProgram::ProgramWriter::createBinary(), BlocksConnectIC::createBus(), VLIWConnectIC::createBus(), TTAProgram::ProgramWriter::createCodeSection(), TDGen::createConstantMaterializationPatterns(), ControlFlowGraph::createControlFlowEdge(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::createCostFunctionOfFU(), HDB::HDBManager::createCostFunctionOfRF(), OperationDAGConverter::createDAG(), BBSchedulerController::createDDGFromBB(), TPEFDisassembler::createDisassemblyElement(), TPEF::Section::createSection(), FullyConnectedCheck::createSocket(), TTAProgram::TPEFProgramFactory::createTerminal(), VectorLSGenerator::createVectorLSU(), DSDBManager::cycleCount(), TDGen::dagNodeToString(), TTAProgram::DataMemory::dataDefinition(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), TTAProgram::Program::dataMemory(), DefaultICGenerator::dataWidthGeneric(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::delayOfSocket(), SchedulingResource::dependentResource(), Breakpoint::description(), StopPoint::description(), determineLongest(), POMDisassembler::disassemble(), SimulatorFrontend::disassembleInstruction(), ProximBusDetailsCmd::Do(), ProximFUDetailsCmd::Do(), ProximIUDetailsCmd::Do(), ProximRFDetailsCmd::Do(), ProximSocketDetailsCmd::Do(), AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), SimValue::dump(), OperationPimpl::emulationFunctionName(), DSDBManager::energyEstimate(), UniversalFunctionUnit::ensureInputPorts(), UniversalFunctionUnit::ensureOutputPorts(), InterpolatingRFEstimator::estimateEnergy(), StrictMatchRFEstimator::estimateEnergy(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), Evaluate::Evaluate(), Exception::Exception(), InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoProcCommand::execute(), CmdMem::execute(), ADFCombiner::explore(), GrowMachine::explore(), VLIWConnectIC::explore(), FrequencySweepExplorer::explore(), IPXactModel::extractSignals(), TPEFDumper::fileHeaders(), LabelManager::finalize(), OperationDAGBuilder::finalize(), TTAProgram::TPEFProgramFactory::findAddressSpace(), OperationDAGSelector::findDags(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), TTAProgram::TPEFProgramFactory::findPort(), TTAProgram::ProgramWriter::findSection(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), SimulateDialog::formattedValue(), FrequencySweepExplorer::FrequencySweepExplorer(), HDB::HDBManager::fuArchitectureByIDQuery(), HDB::HDBManager::fuArchitectureID(), HDBBrowserWindow::fuArchLabel(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuCostEstimationData(), HDB::HDBManager::fuCostEstimationDataIDs(), HDB::HDBManager::fuEntriesByArchitecture(), HDB::HDBManager::fuEntryByIDQuery(), HDB::HDBManager::fuEntryHasArchitecture(), HDB::HDBManager::fuEntryIDOfImplementation(), HDB::HDBManager::fuExternalPortsByIDQuery(), HDB::HDBManager::fuImplementationByIDQuery(), HDB::HDBManager::fuImplementationDataPortsByIDQuery(), HDB::HDBManager::fuImplementationParametersByIDQuery(), MachineResourceManager::functionUnitPortResource(), HDB::HDBManager::fuPortBindingByNameQuery(), HDB::HDBManager::fuPortsAndBindingsByIDQuery(), CompiledSimulation::FUPortValue(), HDB::HDBManager::fuSourceFilesByIDQuery(), ProGeTestBenchGenerator::generate(), DefaultICDecoderGenerator::generate(), CompiledSimCodeGenerator::generateLoadTrigger(), CostDBEntryStatsRF::generateReadWriteString(), CompiledSimSymbolGenerator::generateTempVariable(), CompiledSimCodeGenerator::generateTriggerCode(), TDGen::genTCETargetLoweringSIMD_getSetCCResultVT(), OperationDAGBuilder::getBinding(), DisassemblyGridTable::GetColLabelValue(), ProDeBusEditPolicy::getCommand(), ProDeIUEditPolicy::getCommand(), ProDeRFEditPolicy::getCommand(), ADFCombiner::getNodeComponentName(), CompiledSimulation::getSimulateFunction(), ProGe::NetlistTools::getUniqueInstanceName(), OperationDAGBuilder::getVariableName(), GrowMachine::GrowMachine(), CompiledSimSymbolGenerator::guardBoolSymbol(), CompiledSimCodeGenerator::guardPipelineTopSymbol(), DefaultDecoderGenerator::guardPortName(), DataDependenceGraph::guardRenamed(), DOMBuilderErrorHandler::handleError(), ProcessorConfigurationFile::handleError(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), DSDBManager::hasApplication(), DSDBManager::hasArchitecture(), DSDBManager::hasConfiguration(), HDB::HDBManager::hasCostEstimationDataByID(), HDB::HDBManager::hasCostFunctionPluginByID(), DSDBManager::hasCycleCount(), DSDBManager::hasEnergyEstimate(), DSDBManager::hasImplementation(), TTAProgram::Instruction::immediate(), ImmediateGenerator::ImmediateGenerator(), TDGen::immediatePredicate(), TTAProgram::Instruction::immediatePtr(), CompiledSimulation::immediateUnitRegisterValue(), DSDBManager::implementationString(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), AlmaIFIntegrator::initAlmaifBlock(), TclInterpreter::initialize(), DefaultICGenerator::inputMuxEntityName(), DefaultICGenerator::inputSocketBusPort(), TTAProgram::Program::instructionAt(), TTAProgram::CodeSnippet::instructionAt(), DefaultDecoderGenerator::instructionTemplateCondition(), HDB::HDBManager::ioUsageDataByIDQuery(), DSDBManager::isUnschedulable(), CompiledSimSymbolGenerator::jumpTargetSetterSymbol(), POMDisassembler::label(), TTAMachine::RegisterGuard::loadState(), DSDBManager::longestPathDelayEstimate(), main(), llvm::LLVMTCEBuilder::mbbName(), Memory::Memory(), MemorySystem::memory(), MemoryGridTable::memoryContents(), MinimalOpSet::MinimalOpSet(), MinimizeMachine::MinimizeMachine(), HDB::HDBManager::modifyCostEstimationData(), HDB::HDBManager::modifyCostFunctionPlugin(), TTAProgram::Instruction::move(), TTAProgram::Program::moveAt(), CompiledSimSymbolGenerator::moveOperandSymbol(), TTAProgram::Instruction::movePtr(), DataDependenceGraph::nodeOfMove(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddressSpacesDialog::onAdd(), AddRFFromHDBDialog::onAdd(), GCUDialog::onAddFUPort(), FUDialog::onAddOperation(), GCUDialog::onAddOperation(), FUDialog::onAddPort(), IUDialog::onAddPort(), RFDialog::onAddPort(), GCUDialog::onAddSRPort(), AddBreakpointDialog::onOK(), AddWatchDialog::onOK(), BreakpointPropertiesDialog::onOK(), SimulatorSettingsDialog::onOK(), WatchPropertiesDialog::onOK(), ProximDisassemblyWindow::onRightClick(), ProximDisassemblyWindow::onRunUntil(), ProximDisassemblyWindow::onSetBreakpoint(), ProximDisassemblyWindow::onSetTempBp(), HDB::HDBManager::opcodesByIDQuery(), TTAProgram::TPEFResourceUpdater::operand(), operandBindingsString(), TDGen::operandToString(), TDGen::operationNodeToString(), TCEString::operator+(), TCEString::operator<<(), DefaultICGenerator::outputSocketBusPort(), DefaultICGenerator::outputSocketDataPort(), DefaultICGenerator::outputSocketDataPort(), DefaultICGenerator::outputSocketEntityName(), ProGe::Parameter::Parameter(), MachineResourceModifier::percentualFUIncrease(), MachineResourceModifier::percentualRegisterIncrease(), ProGe::BaseNetlistBlock::portBy(), DefaultDecoderGenerator::portCodeCondition(), ProGe::VerilogNetlistWriter::portSignalName(), ProGe::VerilogNetlistWriter::portSignalType(), ProGe::NetlistVisualization::portWidthToString(), TTAProgram::Program::procedure(), DataDependenceGraphBuilder::processGuard(), ProgramDependenceGraph::processRegion(), SimulatorFrontend::programLocationDescription(), TPEF::TPEFDebugSectionReader::readData(), InfoRegistersCommand::registerDescription(), MachineResourceManager::registerFileIndexReference(), CompiledSimulation::registerFileValue(), CompiledSimController::registerFileValue(), SimulationController::registerFileValue(), SchedulingResource::relatedResource(), DSDBManager::removeApplication(), HDB::HDBManager::removeBusEntry(), DSDBManager::removeConfiguration(), HDB::HDBManager::removeCostEstimationData(), HDB::HDBManager::removeCostFunctionPlugin(), HDB::HDBManager::removeFUArchitecture(), HDB::HDBManager::removeFUEntry(), HDB::HDBManager::removeFUImplementation(), HDB::HDBManager::removeRFArchitecture(), HDB::HDBManager::removeRFEntry(), HDB::HDBManager::removeRFImplementation(), HDB::HDBManager::removeSocketEntry(), RemoveUnconnectedComponents::RemoveUnconnectedComponents(), Texts::TextGenerator::replaceText(), TTAProgram::Program::replaceUniversalAddressSpaces(), CompiledSimController::reset(), DataSectionCreator::resolveDataAreaSizesAndLabelAddresses(), LabelManager::resolveExpressionValue(), MachineResourceManager::resourceID(), TPEF::TPEFTools::resourceName(), HDB::HDBManager::resourceUsageDataByIDQuery(), HDB::HDBManager::rfArchitectureByIDQuery(), HDB::HDBManager::rfArchitectureID(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfCostEstimationData(), HDB::HDBManager::rfCostEstimationDataIDs(), HDB::HDBManager::rfEntriesByArchitecture(), HDB::HDBManager::rfEntryByIDQuery(), HDB::HDBManager::rfEntryHasArchitecture(), HDB::HDBManager::rfEntryIDOfImplementation(), HDB::HDBManager::rfExternalPortsByIDQuery(), HDB::HDBManager::rfImplementationByIDQuery(), HDB::HDBManager::rfImplementationByIDQuery2(), HDB::HDBManager::rfImplementationDataPortsByIDQuery(), HDB::HDBManager::rfImplementationParametersByIDQuery(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), MachineResourceManager::rFPortOrFUIndexReference(), HDB::HDBManager::rfSourceFilesByIDQuery(), DataDependenceEdge::saveState(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TPEFDumper::sectionString(), HDB::HDBManager::setArchitectureForFU(), HDB::HDBManager::setArchitectureForRF(), DSDBManager::setAreaEstimate(), ObjectState::setAttribute(), ObjectState::setAttribute(), ObjectState::setAttribute(), ObjectState::setAttribute(), ObjectState::setAttribute(), TPEF::DataSection::setByte(), HDB::HDBManager::setCostFunctionPluginForFU(), HDB::HDBManager::setCostFunctionPluginForRF(), TTAProgram::ProgramAnnotation::setIntValue(), DSDBManager::setLongestPathDelayEstimate(), SOPCInterface::setProperty(), ExecutionTrace::setSimulatedCycleCount(), llvm::TCETargetMachine::setTargetMachinePlugin(), DSDBManager::setUnschedulable(), SimpleICOptimizer::SimpleICOptimizer(), HDB::HDBManager::socketCostEstimationData(), HDB::HDBManager::socketCostEstimationDataIDs(), HDB::HDBManager::socketCostEstimationDataList(), DefaultDecoderGenerator::socketEncodingCondition(), HDB::HDBManager::socketEntryByIDQuery(), DefaultICGenerator::socketFileName(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), FiniteStateAutomaton::stateName(), DataObject::stringValue(), TPEFDumper::symbolString(), TDGen::tceOperationPattern(), Texts::TextGenerator::text(), FiniteStateAutomaton::toDotString(), TesterContext::toOutputFormat(), IndexTerm::toString(), EntryKeyDataInt::toString(), EntryKeyDataDouble::toString(), ControlDependenceNode::toString(), DataDependenceEdge::toString(), ProgramDependenceNode::toString(), GraphEdge::toString(), GraphNode::toString(), TTAMachine::ResourceVector::toString(), ConstantNode::toString(), OperationDAGEdge::toString(), TerminalNode::toString(), DisassemblyFPRegister::toString(), DisassemblyFUOperand::toString(), DisassemblyImmediate::toString(), DisassemblyImmediateAssignment::toString(), DisassemblyImmediateRegister::toString(), DisassemblyIntRegister::toString(), DisassemblyOperand::toString(), MoveNode::toString(), ProgramOperation::toString(), DataDependenceEdge::toString(), WxConversion::toWxString(), WxConversion::toWxString(), WxConversion::toWxString(), WxConversion::toWxString(), WxConversion::toWxString(), WxConversion::toWxString(), WxConversion::toWxString(), KeyboardShortcutDialog::TransferDataToWindow(), OptionsDialog::TransferDataToWindow(), BusResource::unassign(), ExecutionPipelineResource::unassignDestination(), HDB::HDBManager::unsetArchitectureForFU(), HDB::HDBManager::unsetArchitectureForRF(), HDB::HDBManager::unsetCostFunctionPluginForFU(), HDB::HDBManager::unsetCostFunctionPluginForRF(), NumberControl::update(), FUImplementationDialog::update(), TTAMachine::FUPort::updateBindingString(), CompiledSimCodeGenerator::updateDeclaredSymbolsList(), OperationPropertyDialog::updateOperands(), FUDialog::updatePortList(), GCUDialog::updatePortList(), OperationPropertyDialog::updateSwapLists(), GUIOptions::validate(), TDGenerator::ValueType::valueTypeStr(), VectorLSGenerator::VectorLSGenerator(), DefaultDecoderGenerator::verifyCompatibility(), DefaultICDecoderGenerator::verifyCompatibility(), TDGen::write16bitRegisterInfo(), TDGen::write1bitRegisterInfo(), TDGen::write32bitRegisterInfo(), TDGen::write64bitRegisterInfo(), DefaultICGenerator::writeBusDumpCode(), ProGe::VHDLNetlistWriter::writeConnection(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfRFWritePort(), DataSectionCreator::writeDataLineToTPEF(), DefaultDecoderGenerator::writeGlockMapping(), DefaultDecoderGenerator::writeInstructionDecoder(), TDGen::writeIntegerImmediateDefs(), DefaultICGenerator::writeInterconnectionNetwork(), OperationDAGConverter::writeNode(), ProGe::VHDLNetlistWriter::writePortMappings(), ProGe::VerilogNetlistWriter::writeSignalAssignments(), DataDependenceGraph::writeToXMLFile(), ProGe::CUOpcodeGenerator::WriteVerilogOpcodePackage(), ProGe::CUOpcodeGenerator::WriteVhdlOpcodePackage(), and XilinxBlockRamGenerator::XilinxBlockRamGenerator().
toString() [3/3]
static std::string Conversion::toString (double source, unsigned precision) static
toUnsignedInt()
template<typename T > static unsigned int Conversion::toUnsignedInt (const T & source) static
Referenced by DefaultICDecoderGenerator::busTraceStartingCycle(), TPEFDisassembler::createDisassemblyElement(), DataObject::integerValue(), DefaultICDecoderGenerator::lockTraceStartingCycle(), AddBreakpointDialog::onOK(), NumberControl::onText(), SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::parseInstructionAddressExpression(), PRegionMarkerAnalyzer::parsePregionID(), and ObjectState::unsignedIntAttribute().
toUnsignedLong()
template<typename T > static ULongWord Conversion::toUnsignedLong (const T & source) static
Referenced by ProgramImageGenerator::dataStartAddress(), LLVMTCECmdLineOptions::dataStartAddress(), DataObject::longValue(), and ObjectState::uLongAttribute().
toXMLCh()
static XMLCh * Conversion::toXMLCh (const std::string & string) static
Referenced by XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), and XMLSerializer::initializeParser().
XMLChToString()
static std::string Conversion::XMLChToString (const XMLCh * source) static
Referenced by XMLSerializer::createState(), and DOMBuilderErrorHandler::handleError().
The documentation for this class was generated from the following files:
Conversion.hh
Conversion.cc