OpenASIP: AddIUFromHDBCmd Class Reference
AddIUFromHDBCmd Class Reference
#include <AddIUFromHDBCmd.hh>
Public Member Functions
AddIUFromHDBCmd ()
virtual ~AddIUFromHDBCmd ()
virtual bool Do ()
virtual int id () const
virtual AddIUFromHDBCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for opening a dialog for adding immediate units from a HDB.
Definition at line 41 of file AddIUFromHDBCmd.hh.
Constructor & Destructor Documentation
AddIUFromHDBCmd()
AddIUFromHDBCmd::AddIUFromHDBCmd ()
The Constructor.
Definition at line 48 of file AddIUFromHDBCmd.cc.
                                :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_IU_FROM_HDB) {
}
Referenced by create().
~AddIUFromHDBCmd()
AddIUFromHDBCmd::~AddIUFromHDBCmd () virtual
The Destructor.
Definition at line 56 of file AddIUFromHDBCmd.cc.
{}
Member Function Documentation
create()
AddIUFromHDBCmd * AddIUFromHDBCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 94 of file AddIUFromHDBCmd.cc.
{
    return new AddIUFromHDBCmd();
}
References AddIUFromHDBCmd().
Do()
bool AddIUFromHDBCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file AddIUFromHDBCmd.cc.
                    {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    AddIUFromHDBDialog dialog(parentWindow(), model);
    dialog.ShowModal();
    return true;
}
References assert, GUICommand::parentWindow(), and EditorCommand::view().
icon()
string AddIUFromHDBCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 104 of file AddIUFromHDBCmd.cc.
{
    return ProDeConstants::CMD_ICON_DEFAULT;
}
References ProDeConstants::CMD_ICON_DEFAULT.
id()
int AddIUFromHDBCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 85 of file AddIUFromHDBCmd.cc.
{
    return ProDeConstants::COMMAND_ADD_IU_FROM_HDB;
}
References ProDeConstants::COMMAND_ADD_IU_FROM_HDB.
isEnabled()
bool AddIUFromHDBCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 126 of file AddIUFromHDBCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddIUFromHDBCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 113 of file AddIUFromHDBCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_IU_FROM_HDB;
}
References ProDeConstants::CMD_SNAME_ADD_IU_FROM_HDB.
The documentation for this class was generated from the following files:
AddIUFromHDBCmd.hh
AddIUFromHDBCmd.cc