OpenASIP: ProximDisassemblyWindow Class Reference
ProximDisassemblyWindow Class Reference
#include <ProximDisassemblyWindow.hh>
Public Member Functions
ProximDisassemblyWindow (ProximMainFrame *parent, int id)
virtual ~ProximDisassemblyWindow ()
virtual void reset ()
void loadProgram (const TTAProgram::Program &program)
void showAddress (unsigned address)
void setMoveAttrProvider (ProximDisasmAttrProvider *attrProvider)
Private Types
enum { MENU_ID_SET_BP = 10000 , MENU_ID_SET_TEMP_BP , MENU_ID_RUN_UNTIL , MENU_ID_FIRST_MAPPED }
Context menu command IDs.
Private Member Functions
void initialize ()
void resetGrid ()
void onProgramLoaded (const SimulatorEvent &event)
void onSimulatorStop (const SimulatorEvent &event)
void onSimulatorCommand (SimulatorEvent &event)
void onRightClick (wxGridEvent &event)
void onSetBreakpoint (wxCommandEvent &event)
void onSetTempBp (wxCommandEvent &event)
void onRunUntil (wxCommandEvent &event)
void onMappedMenuCommand (wxCommandEvent &event)
Private Attributes
wxGrid * codeGrid_
The grid disapleying the disassembly.
ProximDisassemblyGridTable * codeTable_
Grid table which handles on-the-fly disassembly of the loaded program.
std::map< unsigned, std::string > menuCommand_
A map which contains command strings for context menu items.
Static Private Attributes
static const unsigned INFO_COLUMN_WIDTH = 30
Width of the column displaying the arrow pointign current instruction.
static const unsigned ADDRESS_COLUMN_WIDTH = 60
Width of the instruction address column.
static const unsigned BP_COLUMN_WIDTH = 80
Width of the breakpoint info column.
static const unsigned DISASSEMBLY_COLUMN_WIDTH = 400
Width of the instruction disassembly column.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
A window which can be utilized to display disassembly of a program object model.
This class listens to SimulatorEvents and updates the window information automatically.
Definition at line 58 of file ProximDisassemblyWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Context menu command IDs.
Enumerator
MENU_ID_SET_BP
MENU_ID_SET_TEMP_BP
MENU_ID_RUN_UNTIL
MENU_ID_FIRST_MAPPED
Definition at line 97 of file ProximDisassemblyWindow.hh.
         {
    MENU_ID_SET_BP = 10000,
        MENU_ID_SET_TEMP_BP,
        MENU_ID_RUN_UNTIL,
    MENU_ID_FIRST_MAPPED // Keep this as the last menu item.
    };
Constructor & Destructor Documentation
ProximDisassemblyWindow()
ProximDisassemblyWindow::ProximDisassemblyWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 84 of file ProximDisassemblyWindow.cc.
                                    :
    ProximSimulatorWindow(parent, id),
    codeGrid_(NULL),
    codeTable_(NULL) {
    initialize();
}
~ProximDisassemblyWindow()
ProximDisassemblyWindow::~ProximDisassemblyWindow () virtual
Destructor.
Definition at line 97 of file ProximDisassemblyWindow.cc.
{
}
Member Function Documentation
initialize()
void ProximDisassemblyWindow::initialize () private
Creates the window contents.
Definition at line 105 of file ProximDisassemblyWindow.cc.
{
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    SetSizer(sizer);
}
loadProgram()
void ProximDisassemblyWindow::loadProgram (const TTAProgram::Program & program)
Loads a program model to the window.
Parameters
program Program to load.
Definition at line 179 of file ProximDisassemblyWindow.cc.
{
    assert(codeTable_ == NULL);
    codeTable_ = new ProximDisassemblyGridTable();
    codeTable_->loadProgram(program);
    resetGrid();
    codeTable_->setCurrentInstruction(0);
    codeTable_->showPCArrow();
    StopPointManager& bpManager =
        ProximToolbox::frontend()->stopPointManager();
    codeTable_->setStopPointManager(bpManager);
}
References assert, codeTable_, ProximToolbox::frontend(), DisassemblyGridTable::loadProgram(), program, resetGrid(), ProximDisassemblyGridTable::setCurrentInstruction(), ProximDisassemblyGridTable::setStopPointManager(), ProximDisassemblyGridTable::showPCArrow(), and SimulatorFrontend::stopPointManager().
Referenced by onProgramLoaded().
onMappedMenuCommand()
void ProximDisassemblyWindow::onMappedMenuCommand (wxCommandEvent & event) private
Event handler for breakpoint submenus of the context menu.
Parameters
event Menu event to handle.
Definition at line 373 of file ProximDisassemblyWindow.cc.
{
    if (!AssocTools::containsKey(menuCommand_, event.GetId())) {
    // Menu item ID doesn't have command associated, the event is skipped.
    event.Skip();
    }
    string command = menuCommand_[event.GetId()];
    wxGetApp().simulation()->lineReader().input(command);
}
References AssocTools::containsKey(), and menuCommand_.
onProgramLoaded()
void ProximDisassemblyWindow::onProgramLoaded (const SimulatorEvent & event) private
Updates disassembly window when a program is loaded to the simulator.
Definition at line 198 of file ProximDisassemblyWindow.cc.
{
    loadProgram(ProximToolbox::program());
}
References loadProgram(), and ProximToolbox::program().
onRightClick()
void ProximDisassemblyWindow::onRightClick (wxGridEvent & event) private
Handles RMB clicks on the disassembly window.
A context menu is displayed at the cursor location.
Definition at line 209 of file ProximDisassemblyWindow.cc.
{
    codeGrid_->SelectRow(event.GetRow());
    wxMenu* contextMenu = new wxMenu();
    Word address = codeTable_->addressOfRow(event.GetRow());
    contextMenu->Append(MENU_ID_SET_BP, _T("Set breakpoint"));
    contextMenu->Append(
        MENU_ID_SET_TEMP_BP, _T("Set temporary breakpoint"));
    contextMenu->AppendSeparator();
    contextMenu->Append(MENU_ID_RUN_UNTIL, _T("Run until"));
    contextMenu->AppendSeparator();
    menuCommand_.clear();
    StopPointManager& bpManager =
        ProximToolbox::frontend()->stopPointManager();
    // Create submenu for each breakpoint at the selected line.
    unsigned itemID = MENU_ID_FIRST_MAPPED;
    for (unsigned i = 0; i < bpManager.stopPointCount(); i++) {
    unsigned handle = bpManager.stopPointHandle(i);
    const Breakpoint* bp = dynamic_cast<const Breakpoint*>(
                &bpManager.stopPointWithHandleConst(handle));
        if (bp != NULL) {
            unsigned bpAddress = bp->address();
            if (bpAddress == address) {
                wxMenu* bpSubMenu = new wxMenu();
                string handleStr = Conversion::toString(handle);
                // Info menuitem.
                menuCommand_[itemID] = "info breakpoints " + handleStr;
                wxString infoLabel = _T("info");
                bpSubMenu->Append(itemID, infoLabel);
                itemID++;
                // Delete menuitem.
                menuCommand_[itemID] = "deletebp " + handleStr;
                wxString deleteLabel = _T("delete");
                bpSubMenu->Append(itemID, deleteLabel);
                itemID++;
                // Enable/disable menuitem.
                if (bp->isEnabled()) {
                    menuCommand_[itemID] =
                        "disablebp " + handleStr;
                    wxString disableLabel = _T("disable");
                    bpSubMenu->Append(itemID, disableLabel);
                } else {
                    menuCommand_[itemID] =
                        "enablebp " + handleStr;
                    wxString enableLabel = _T("enable");
                    bpSubMenu->Append(itemID, enableLabel);
                }
                itemID++;
                wxString menuLabel =
                    _T("breakpoint ") + WxConversion::toWxString(handle);
                contextMenu->Append(0, menuLabel, bpSubMenu);
            }
        }
    }
    PopupMenu(contextMenu, event.GetPosition());
}
References Breakpoint::address(), DisassemblyGridTable::addressOfRow(), codeGrid_, codeTable_, ProximToolbox::frontend(), StopPoint::isEnabled(), MENU_ID_FIRST_MAPPED, MENU_ID_RUN_UNTIL, MENU_ID_SET_BP, MENU_ID_SET_TEMP_BP, menuCommand_, StopPointManager::stopPointCount(), StopPointManager::stopPointHandle(), SimulatorFrontend::stopPointManager(), StopPointManager::stopPointWithHandleConst(), Conversion::toString(), and WxConversion::toWxString().
onRunUntil()
void ProximDisassemblyWindow::onRunUntil (wxCommandEvent & event) private
Handles the context menu "run until" clicks.
Definition at line 314 of file ProximDisassemblyWindow.cc.
{
    unsigned address =
        codeTable_->addressOfRow(codeGrid_->GetSelectedRows().Item(0));
    string command = ProximConstants::SCL_RUN_UNTIL + " " +
        Conversion::toString(address);
    wxGetApp().simulation()->lineReader().input(command);
}
References DisassemblyGridTable::addressOfRow(), codeGrid_, codeTable_, ProximConstants::SCL_RUN_UNTIL, and Conversion::toString().
onSetBreakpoint()
void ProximDisassemblyWindow::onSetBreakpoint (wxCommandEvent & event) private
Handles the event of adding new breakpoint with the context menu.
Definition at line 286 of file ProximDisassemblyWindow.cc.
{
    unsigned address =
        codeTable_->addressOfRow(codeGrid_->GetSelectedRows().Item(0));
    string command = ProximConstants::SCL_SET_BREAKPOINT + " " +
        Conversion::toString(address);
    wxGetApp().simulation()->lineReader().input(command);
}
References DisassemblyGridTable::addressOfRow(), codeGrid_, codeTable_, ProximConstants::SCL_SET_BREAKPOINT, and Conversion::toString().
onSetTempBp()
void ProximDisassemblyWindow::onSetTempBp (wxCommandEvent & event) private
Handles the event of adding new temporary breakpoint with the context menu.
Definition at line 300 of file ProximDisassemblyWindow.cc.
{
    unsigned address =
        codeTable_->addressOfRow(codeGrid_->GetSelectedRows().Item(0));
    string command = ProximConstants::SCL_SET_TEMP_BP + " " +
        Conversion::toString(address);
    wxGetApp().simulation()->lineReader().input(command);
}
References DisassemblyGridTable::addressOfRow(), codeGrid_, codeTable_, ProximConstants::SCL_SET_TEMP_BP, and Conversion::toString().
onSimulatorCommand()
void ProximDisassemblyWindow::onSimulatorCommand (SimulatorEvent & event) private
Updates the disassembly window when a command is executed.
Parameters
event Event of a command execution.
Definition at line 346 of file ProximDisassemblyWindow.cc.
{
    if (codeGrid_ != NULL) {
        codeGrid_->ForceRefresh();
    }
    event.Skip();
}
References codeGrid_.
onSimulatorStop()
void ProximDisassemblyWindow::onSimulatorStop (const SimulatorEvent & event) private
Updates the arrow displaying the current instruction when the simulation stops.
Definition at line 328 of file ProximDisassemblyWindow.cc.
{
    Word pc = wxGetApp().simulation()->frontend()->programCounter();
    if (codeTable_->moveCellAttrProvider() != NULL) {
        codeTable_->moveCellAttrProvider()->update();
    }
    codeTable_->setCurrentInstruction(pc);
    codeGrid_->SelectRow(pc);
    codeGrid_->MakeCellVisible(pc, 1);
    codeGrid_->ForceRefresh();
}
References codeGrid_, codeTable_, ProximDisassemblyGridTable::moveCellAttrProvider(), ProximDisassemblyGridTable::setCurrentInstruction(), and ProximDisasmAttrProvider::update().
reset()
void ProximDisassemblyWindow::reset () virtual
Called when the simulator program, machine and memory models are deleted.
Reimplemented from ProximSimulatorWindow.
Definition at line 155 of file ProximDisassemblyWindow.cc.
{
    wxSizer* sizer = GetSizer();
    if (codeGrid_ != NULL) {
        sizer->Detach(codeGrid_);
        sizer->Layout();
        codeGrid_->Destroy();
        codeGrid_ = NULL;
    }
    if (codeTable_ != NULL) {
        delete codeTable_;
        codeTable_ = NULL;
    }
}
References codeGrid_, and codeTable_.
resetGrid()
void ProximDisassemblyWindow::resetGrid () private
Resets the grid. This function has to be called if a new program is loaded to the window.
Definition at line 117 of file ProximDisassemblyWindow.cc.
{
    wxSizer* sizer = GetSizer();
    if (codeGrid_ != NULL) {
        sizer->Detach(codeGrid_);
        sizer->Layout();
        codeGrid_->Destroy();
    }
    codeGrid_ = new wxGrid(this, -1, wxDefaultPosition, wxDefaultSize);
    codeGrid_->SetTable(codeTable_);
    codeGrid_->EnableEditing(false);
    codeGrid_->DisableCellEditControl();
    codeGrid_->SetSelectionMode(wxGrid::wxGridSelectRows);
    codeGrid_->DisableDragGridSize();
    codeGrid_->DisableDragRowSize();
    codeGrid_->EnableGridLines(false);
    codeGrid_->SetDefaultColSize(200);
    codeGrid_->SetColSize(0, 100);
    codeGrid_->SetColSize(1, 80);
    codeGrid_->SetDefaultCellFont(*wxSMALL_FONT);
    codeGrid_->SetGridCursor(0, 0);
    sizer->Add(codeGrid_, 1, wxGROW);
    Layout();
}
References codeGrid_, and codeTable_.
Referenced by loadProgram().
setMoveAttrProvider()
void ProximDisassemblyWindow::setMoveAttrProvider (ProximDisasmAttrProvider * attrProvider)
Sets the move cell attribute provider.
Parameters
attrProvider New attribute provider.
Definition at line 391 of file ProximDisassemblyWindow.cc.
{
    codeTable_->setMoveCellAttrProvider(attrProvider);
}
References codeTable_, and ProximDisassemblyGridTable::setMoveCellAttrProvider().
Referenced by ClearDisassemblyHighlightCmd::Do(), HighlightExecPercentageCmd::Do(), and HighlightTopExecCountsCmd::Do().
showAddress()
void ProximDisassemblyWindow::showAddress (unsigned address)
Selects the instruction at given address.
Parameters
address Address of the isntruction to show.
Definition at line 359 of file ProximDisassemblyWindow.cc.
{
    unsigned row = codeTable_->rowOfAddress(address);
    codeGrid_->SelectRow(row);
    codeGrid_->MakeCellVisible(row, 0);
}
References codeGrid_, codeTable_, and DisassemblyGridTable::rowOfAddress().
Referenced by ProximBreakpointWindow::onBreakpointLookup(), FindWindow::onFindNext(), FindWindow::onFindPrev(), FindWindow::onInputText(), and DisasmExecCountFrame::onSelection().
Member Data Documentation
ADDRESS_COLUMN_WIDTH
const unsigned ProximDisassemblyWindow::ADDRESS_COLUMN_WIDTH = 60 static private
Width of the instruction address column.
Definition at line 90 of file ProximDisassemblyWindow.hh.
BP_COLUMN_WIDTH
const unsigned ProximDisassemblyWindow::BP_COLUMN_WIDTH = 80 static private
Width of the breakpoint info column.
Definition at line 92 of file ProximDisassemblyWindow.hh.
codeGrid_
wxGrid* ProximDisassemblyWindow::codeGrid_ private
The grid disapleying the disassembly.
Definition at line 80 of file ProximDisassemblyWindow.hh.
Referenced by onRightClick(), onRunUntil(), onSetBreakpoint(), onSetTempBp(), onSimulatorCommand(), onSimulatorStop(), reset(), resetGrid(), and showAddress().
codeTable_
ProximDisassemblyGridTable* ProximDisassemblyWindow::codeTable_ private
Grid table which handles on-the-fly disassembly of the loaded program.
Definition at line 82 of file ProximDisassemblyWindow.hh.
Referenced by loadProgram(), onRightClick(), onRunUntil(), onSetBreakpoint(), onSetTempBp(), onSimulatorStop(), reset(), resetGrid(), setMoveAttrProvider(), and showAddress().
DISASSEMBLY_COLUMN_WIDTH
const unsigned ProximDisassemblyWindow::DISASSEMBLY_COLUMN_WIDTH = 400 static private
Width of the instruction disassembly column.
Definition at line 94 of file ProximDisassemblyWindow.hh.
INFO_COLUMN_WIDTH
const unsigned ProximDisassemblyWindow::INFO_COLUMN_WIDTH = 30 static private
Width of the column displaying the arrow pointign current instruction.
Definition at line 88 of file ProximDisassemblyWindow.hh.
menuCommand_
std::map<unsigned, std::string> ProximDisassemblyWindow::menuCommand_ private
A map which contains command strings for context menu items.
Definition at line 85 of file ProximDisassemblyWindow.hh.
Referenced by onMappedMenuCommand(), and onRightClick().
The documentation for this class was generated from the following files:
ProximDisassemblyWindow.hh
ProximDisassemblyWindow.cc