OpenASIP: TTAProgram::TerminalInstructionReference Class Reference
TTAProgram::TerminalInstructionReference Class Reference
#include <TerminalInstructionReference.hh>
Public Member Functions
TerminalInstructionReference (InstructionReference ref)
virtual ~TerminalInstructionReference ()
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual void setInstructionReference (InstructionReference ref)
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
Public Member Functions inherited from TTAProgram::TerminalInstructionAddress
TerminalInstructionAddress ()
virtual ~TerminalInstructionAddress ()
bool isInstructionAddress () const
SimValue value () const
Public Member Functions inherited from TTAProgram::TerminalImmediate
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Private Member Functions
TerminalInstructionAddress & operator= (const TerminalInstructionAddress &)
Assignment not allowed.
Private Attributes
InstructionReference ref_
Referred instruction.
Additional Inherited Members
Protected Attributes inherited from TTAProgram::TerminalImmediate
SimValue value_
Value of the inline immediate.
Detailed Description
Represents an inline immediate that refers to an (absolute) instruction address via the InstructionReference indirection.
Definition at line 48 of file TerminalInstructionReference.hh.
Constructor & Destructor Documentation
TerminalInstructionReference()
TTAProgram::TerminalInstructionReference::TerminalInstructionReference (InstructionReference ref)
The constructor.
Parameters
value The value of the inline immediate (the address).
space The address space of the address the immediate refers to.
ref The instruction this address refers to.
Definition at line 51 of file TerminalInstructionReference.cc.
                              : TerminalInstructionAddress(), ref_(ref) {
}
~TerminalInstructionReference()
TTAProgram::TerminalInstructionReference::~TerminalInstructionReference () virtual
The destructor.
Definition at line 58 of file TerminalInstructionReference.cc.
{
}
Member Function Documentation
address()
Address TTAProgram::TerminalInstructionReference::address () const virtual
Returns the value of the immediate (instruction address).
Returns
The value of the immediate (instruction address).
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 67 of file TerminalInstructionReference.cc.
{
    return ref_.instruction().address();
}
References TTAProgram::Instruction::address(), TTAProgram::InstructionReference::instruction(), and ref_.
copy()
Terminal * TTAProgram::TerminalInstructionReference::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 111 of file TerminalInstructionReference.cc.
{
    return new TerminalInstructionReference(ref_);
}
References ref_.
equals()
bool TTAProgram::TerminalInstructionReference::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 122 of file TerminalInstructionReference.cc.
{
    const TerminalBasicBlockReference* otherBBRef =
        dynamic_cast<const TerminalBasicBlockReference*>(&other);
    if (otherBBRef) {
        const BasicBlock& bb = otherBBRef->basicBlock();
        return &ref_.instruction() == &(bb.firstInstruction());
    }
    const TerminalInstructionReference* otherInsRef =
        dynamic_cast<const TerminalInstructionReference*>(&other);
    if (otherInsRef) {
        return otherInsRef->instructionReference() ==
            ref_;
    }
    return false;
}
References TTAProgram::TerminalBasicBlockReference::basicBlock(), TTAProgram::CodeSnippet::firstInstruction(), TTAProgram::InstructionReference::instruction(), instructionReference(), and ref_.
Referenced by ControlFlowGraph::sanitize().
instructionReference() [1/2]
InstructionReference & TTAProgram::TerminalInstructionReference::instructionReference () virtual
Returns a reference to the instruction to which the immediate points.
Returns
A reference to the instruction to which the immediate points.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 89 of file TerminalInstructionReference.cc.
{
    return ref_;
}
References ref_.
instructionReference() [2/2]
const InstructionReference & TTAProgram::TerminalInstructionReference::instructionReference () const virtual
Returns a reference to the instruction to which the immediate points.
Returns
A reference to the instruction to which the immediate points.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 78 of file TerminalInstructionReference.cc.
{
    return ref_;
}
References ref_.
Referenced by ControlFlowGraph::createBBEdges(), TTAProgram::TerminalBasicBlockReference::equals(), equals(), and ControlFlowGraph::removeJumpToTarget().
operator=()
TerminalInstructionAddress & TTAProgram::TerminalInstructionReference::operator= (const TerminalInstructionAddress &) private
Assignment not allowed.
setInstructionReference()
void TTAProgram::TerminalInstructionReference::setInstructionReference (InstructionReference ref) virtual
Set a new referred instruction.
Parameters
ref The new instruction reference.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 100 of file TerminalInstructionReference.cc.
{
    ref_ = ref;
}
References ref_.
Referenced by CopyingDelaySlotFiller::updateJumpsAndCfg().
Member Data Documentation
ref_
InstructionReference TTAProgram::TerminalInstructionReference::ref_ private
Referred instruction.
Definition at line 64 of file TerminalInstructionReference.hh.
Referenced by address(), copy(), equals(), instructionReference(), instructionReference(), and setInstructionReference().
The documentation for this class was generated from the following files:
TerminalInstructionReference.hh
TerminalInstructionReference.cc