OpenASIP: SetCostFunctionPluginCmd Class Reference
SetCostFunctionPluginCmd Class Reference
#include <SetCostFunctionPluginCmd.hh>
Public Member Functions
SetCostFunctionPluginCmd ()
virtual ~SetCostFunctionPluginCmd ()
virtual bool Do ()
virtual int id () const
virtual SetCostFunctionPluginCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for setting cost function plugin for HDB entries.
Definition at line 41 of file SetCostFunctionPluginCmd.hh.
Constructor & Destructor Documentation
SetCostFunctionPluginCmd()
SetCostFunctionPluginCmd::SetCostFunctionPluginCmd ()
The Constructor.
Definition at line 48 of file SetCostFunctionPluginCmd.cc.
                                                   :
    GUICommand(HDBEditorConstants::COMMAND_NAME_SET_COST_PLUGIN, NULL) {
}
Referenced by create().
~SetCostFunctionPluginCmd()
SetCostFunctionPluginCmd::~SetCostFunctionPluginCmd () virtual
The Destructor.
Definition at line 56 of file SetCostFunctionPluginCmd.cc.
{
}
Member Function Documentation
create()
SetCostFunctionPluginCmd * SetCostFunctionPluginCmd::create () const virtual
Creates and returns a new instance of the command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 164 of file SetCostFunctionPluginCmd.cc.
{
    return new SetCostFunctionPluginCmd();
}
References SetCostFunctionPluginCmd().
Do()
bool SetCostFunctionPluginCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 63 of file SetCostFunctionPluginCmd.cc.
{
    HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow& browser =  *wxGetApp().mainFrame().browser();
    const std::set<RowID> pluginIDs = manager->costFunctionPluginIDs();
    wxString plugins[100];
    std::map<int, RowID> rowIDs;
    std::set<RowID>::iterator iter = pluginIDs.begin();
    plugins[0] = _T("NONE");
    int i = 1;
    // Append plugin names to an array for the choicer dialog.
    for (;iter != pluginIDs.end(); iter++) {
        const CostFunctionPlugin* plugin =
            manager->costFunctionPluginByID(*iter);
        plugins[i] = WxConversion::toWxString(plugin->name());
        delete plugin;
        plugin = NULL;
        rowIDs[i] = *iter;
        i++;
    }
    // Display single choice dialog of cost function plugins.
    wxSingleChoiceDialog dialog(
        parentWindow(), _T("Choose Cost Function Plugin"),
        _T("Choose Cost Function Pluhin"),
        i, plugins);
    if (dialog.ShowModal() != wxID_OK) {
        return false;
    }
    // Set the selected plugin as the entry plugin.
    if (browser.isFUEntrySelected()) {
        // FU entry.
        int entryID = browser.selectedFUEntry();
        if (dialog.GetSelection() > 0) {
            manager->setCostFunctionPluginForFU(
                entryID, rowIDs[dialog.GetSelection()]);
        } else {
            manager->unsetCostFunctionPluginForFU(entryID);
        }
        wxGetApp().mainFrame().update();
        browser.selectFUEntry(entryID);
        return true;
    } else if (browser.isRFEntrySelected()) {
        // RF entry.
        int entryID = browser.selectedRFEntry();
        if (dialog.GetSelection() > 0) {
            manager->setCostFunctionPluginForRF(
                entryID, rowIDs[dialog.GetSelection()]);
        } else {
            manager->unsetCostFunctionPluginForRF(entryID);
        }
        wxGetApp().mainFrame().update();
        browser.selectRFEntry(entryID);
        return true;
    }
    return false;
}
References HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginIDs(), HDBBrowserWindow::isFUEntrySelected(), HDBBrowserWindow::isRFEntrySelected(), HDB::CostFunctionPlugin::name(), GUICommand::parentWindow(), HDBBrowserWindow::selectedFUEntry(), HDBBrowserWindow::selectedRFEntry(), HDBBrowserWindow::selectFUEntry(), HDBBrowserWindow::selectRFEntry(), HDB::HDBManager::setCostFunctionPluginForFU(), HDB::HDBManager::setCostFunctionPluginForRF(), WxConversion::toWxString(), HDB::HDBManager::unsetCostFunctionPluginForFU(), and HDB::HDBManager::unsetCostFunctionPluginForRF().
icon()
std::string SetCostFunctionPluginCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 141 of file SetCostFunctionPluginCmd.cc.
{
    return "";
}
id()
int SetCostFunctionPluginCmd::id () const virtual
Returns the command id.
Returns
Command identifier for this command.
Implements GUICommand.
Definition at line 153 of file SetCostFunctionPluginCmd.cc.
{
    return HDBEditorConstants::COMMAND_SET_COST_PLUGIN;
}
References HDBEditorConstants::COMMAND_SET_COST_PLUGIN.
isEnabled()
bool SetCostFunctionPluginCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 174 of file SetCostFunctionPluginCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (browser->isFUEntrySelected() ||
        browser->isRFEntrySelected()) {
        return true;
    }
    return false;
}
References HDBBrowserWindow::isFUEntrySelected(), and HDBBrowserWindow::isRFEntrySelected().
The documentation for this class was generated from the following files:
SetCostFunctionPluginCmd.hh
SetCostFunctionPluginCmd.cc