OpenASIP: TTAMachine::PortGuard Class Reference
TTAMachine::PortGuard Class Reference
#include <Guard.hh>
Public Member Functions
PortGuard (bool inverted, FUPort &port, Bus &parentBus)
PortGuard (const ObjectState *state, Bus &parentBus)
virtual ~PortGuard ()
bool isEqual (const Guard &guard) const
bool isOpposite (const Guard &guard) const
FUPort * port () const
virtual void copyTo (Bus &parentBus) const
ObjectState * saveState () const
void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Guard
virtual ~Guard ()
virtual Bus * parentBus () const
virtual void setParentBus (Bus *parentBus)
virtual bool isInverted () const
virtual bool isMoreRestrictive (const Guard &guard) const
virtual bool isLessRestrictive (const Guard &guard) const
virtual bool isDisjoint (const Guard &guard) const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_PORT_GUARD = "portguard"
ObjectState name for PortGuard ObjectState.
static const std::string OSKEY_FU = "fu"
ObjectState attribute key for function unit name.
static const std::string OSKEY_PORT = "port"
ObjectState attribute key for port name.
Static Public Attributes inherited from TTAMachine::Guard
static const std::string OSNAME_GUARD = "guard"
ObjectState name for guard.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for inverted feature.
Private Attributes
FUPort * port_
Port from which the condition term is taken.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Guard
Guard (bool inverted, Bus *parentBus)
Guard (const ObjectState *state, Bus &parentBus)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Guard where the condition term is taken from the value of an output port of a FunctionUnit.
Definition at line 99 of file Guard.hh.
Constructor & Destructor Documentation
PortGuard() [1/2]
TTAMachine::PortGuard::PortGuard (bool inverted, FUPort & port, Bus & parentBus)
Constructor.
Parameters
inverted Incates whether the condition term is inverted.
port Port from which the condition term is taken.
parentBus Parent bus component of the guard.
Exceptions
IllegalRegistration If the given port is not registered to the same machine as the given parent bus.
ComponentAlreadyExists If the parent bus already has an equal guard.
Definition at line 196 of file Guard.cc.
    : Guard(inverted, &parentBus), port_(&port) {
    FunctionUnit* unit = port.parentUnit();
    parentBus.ensureRegistration(*unit);
    parentBus.addGuard(*this);
}
References TTAMachine::Bus::addGuard(), TTAMachine::Component::ensureRegistration(), TTAMachine::Guard::parentBus(), TTAMachine::BaseFUPort::parentUnit(), and port().
PortGuard() [2/2]
TTAMachine::PortGuard::PortGuard (const ObjectState * state, Bus & parentBus)
Constructor.
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
parentBus Parent bus of the guard.
Exceptions
ObjectStateLoadingException If the reference to the function unit port cannot be resolved or if the given ObjectState instance is invalid.
Definition at line 215 of file Guard.cc.
    : Guard(state, parentBus) {
    loadState(state);
    try {
        parentBus.addGuard(*this);
    } catch (const ComponentAlreadyExists&) {
        const string procName = "PortGuard::PortGuard";
        MOMTextGenerator textGen;
        format errorMsg = textGen.text(
            MOMTextGenerator::TXT_EQUAL_PORT_GUARDS);
        errorMsg % port()->name() % port()->parentUnit()->name() %
            parentBus.name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    }
}
References TTAMachine::Bus::addGuard(), loadState(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::Guard::parentBus(), TTAMachine::BaseFUPort::parentUnit(), port(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_EQUAL_PORT_GUARDS.
~PortGuard()
TTAMachine::PortGuard::~PortGuard () virtual
Destructor.
Definition at line 235 of file Guard.cc.
                      {
}
Member Function Documentation
copyTo()
virtual void TTAMachine::PortGuard::copyTo (Bus & parentBus) const inline virtual
Implements TTAMachine::Guard.
Definition at line 109 of file Guard.hh.
{
        new PortGuard(isInverted(), *port_, parentBus);
    }
References TTAMachine::Guard::isInverted(), TTAMachine::Guard::parentBus(), and port_.
isEqual()
bool TTAMachine::PortGuard::isEqual (const Guard & guard) const virtual
Returns true if the guard is equal with the given guard.
Parameters
guard The other guard.
Returns
True if the guard is equal with the given guard.
Implements TTAMachine::Guard.
Definition at line 246 of file Guard.cc.
{
    const PortGuard* portGuard = dynamic_cast<const PortGuard*>(&guard);
    if (portGuard == NULL) {
        return false;
    } else {
        if (port() == portGuard->port() &&
            isInverted() == portGuard->isInverted()) {
            return true;
        } else {
            return false;
        }
    }
}
References TTAMachine::Guard::isInverted(), and port().
isOpposite()
bool TTAMachine::PortGuard::isOpposite (const Guard & guard) const virtual
Returns true if the guard is opposite with the given guard, ie. always if one is executed, another is not executed.
Parameters
guard The other guard.
Returns
True if the guard is opposite with the given guard.
Implements TTAMachine::Guard.
Definition at line 268 of file Guard.cc.
{
    const PortGuard* portGuard = dynamic_cast<const PortGuard*>(&guard);
    if (portGuard == NULL) {
        return false;
    } else {
        if (port() == portGuard->port() &&
            isInverted() != portGuard->isInverted()) {
            return true;
        } else {
            return false;
        }
    }
}
References TTAMachine::Guard::isInverted(), and port().
loadState()
void TTAMachine::PortGuard::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if the reference to the function unit port cannot be resolved.
Reimplemented from TTAMachine::Guard.
Definition at line 312 of file Guard.cc.
{
    string procName = "PortGuard::loadState";
    MOMTextGenerator textGenerator;
    if (state->name() != OSNAME_PORT_GUARD) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Guard::loadState(state);
    try {
        string fuName = state->stringAttribute(OSKEY_FU);
        string portName = state->stringAttribute(OSKEY_PORT);
        Machine* mach = parentBus()->machine();
        if (mach == NULL) {
            format text = textGenerator.text(MOMTextGenerator::
                                             TXT_GUARD_REF_LOAD_ERR);
            text % parentBus()->name();
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              text.str());
        }
        Machine::FunctionUnitNavigator fuNav = mach->functionUnitNavigator();
        FunctionUnit* fu = NULL;
        FUPort* port = NULL;
        try {
            fu = fuNav.item(fuName);
        } catch (InstanceNotFound& e) {
            format text = textGenerator.text(MOMTextGenerator::
                                             TXT_GUARD_REF_LOAD_ERR_FU);
            text % parentBus()->name() % fuName;
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              text.str());
        }
        try {
            port = fu->operationPort(portName);
        } catch (InstanceNotFound& e) {
            format text = textGenerator.text(MOMTextGenerator::
                                             TXT_GUARD_REF_LOAD_ERR_PORT);
            text % parentBus()->name() % portName % fuName;
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              text.str());
        }
        port_ = port;
    } catch (Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
}
References Exception::errorMessage(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Guard::loadState(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ObjectState::name(), TTAMachine::FunctionUnit::operationPort(), OSKEY_FU, OSKEY_PORT, OSNAME_PORT_GUARD, TTAMachine::Guard::parentBus(), port(), port_, ObjectState::stringAttribute(), and Texts::TextGenerator::text().
Referenced by PortGuard().
port()
FUPort * TTAMachine::PortGuard::port () const
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), MachineStateBuilder::buildMachineState(), UtilizationStats::calculateForInstruction(), BEMValidator::checkGuardField(), TTAMachine::FunctionUnit::cleanupGuards(), TTAMachine::FUPort::cleanupGuards(), DefaultDecoderGenerator::completeDecoderBlock(), DefaultDecoderGenerator::containsSimilarGuard(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), MachineConnectivityCheck::findPossibleDestinationPorts(), ProgramOperation::fuFromOutMove(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), DefaultDecoderGenerator::guardPortName(), ProgramOperation::hwopFromOutMove(), isEqual(), isOpposite(), loadState(), BFLateBypassGuard::operator()(), BFEarlyGuardBypass::operator()(), ProgramOperation::outputIndexFromGuard(), PortGuard(), PortGuard(), MachineResourceManager::rFPortOrFUIndexReference(), MachineInfo::supportsPortGuardedJump(), and BusDialog::updateGuardLists().
saveState()
ObjectState * TTAMachine::PortGuard::saveState () const virtual
Saves the contents to an ObjectState object.
Returns
The created tree ObjectState object.
Reimplemented from TTAMachine::Guard.
Definition at line 289 of file Guard.cc.
{
    ObjectState* guardState = Guard::saveState();
    guardState->setName(OSNAME_PORT_GUARD);
    FunctionUnit* unit = port_->parentUnit();
    guardState->setAttribute(OSKEY_FU, unit->name());
    guardState->setAttribute(OSKEY_PORT, port_->name());
    return guardState;
}
References TTAMachine::Component::name(), TTAMachine::Port::name(), OSKEY_FU, OSKEY_PORT, OSNAME_PORT_GUARD, TTAMachine::BaseFUPort::parentUnit(), port_, TTAMachine::Guard::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Member Data Documentation
OSKEY_FU
const string TTAMachine::PortGuard::OSKEY_FU = "fu" static
ObjectState attribute key for function unit name.
Definition at line 119 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadState(), and saveState().
OSKEY_PORT
const string TTAMachine::PortGuard::OSKEY_PORT = "port" static
ObjectState attribute key for port name.
Definition at line 121 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadState(), and saveState().
OSNAME_PORT_GUARD
const string TTAMachine::PortGuard::OSNAME_PORT_GUARD = "portguard" static
ObjectState name for PortGuard ObjectState.
Definition at line 117 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Bus::loadState(), loadState(), and saveState().
port_
FUPort* TTAMachine::PortGuard::port_ private
Port from which the condition term is taken.
Definition at line 125 of file Guard.hh.
Referenced by copyTo(), loadState(), and saveState().
The documentation for this class was generated from the following files:
Guard.hh
Guard.cc