OpenASIP: NumberControl Class Reference
NumberControl Class Reference
#include <NumberControl.hh>
Classes
union Value
Public Member Functions
NumberControl (wxWindow *parent, wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=(MODE_HEXADECIMAL|MODE_BINARY|MODE_INT|MODE_UNSIGNED|MODE_FLOAT), int initial=0, const wxString &name=_T("NumberControl"))
virtual ~NumberControl ()
int intValue () const
unsigned int unsignedValue () const
float floatValue () const
double doubleValue () const
ULongWord uLongValue () const
long mode () const
void setBinMode ()
void setHexMode ()
void setIntMode ()
void setUnsignedMode ()
void setFloatMode ()
void setDoubleMode ()
void setValue (const ULongWord value)
void setValue (const unsigned int value)
void setValue (const int value)
void setValue (const float value)
void setValue (const double value)
Static Public Attributes
static const long MODE_BINARY = 1
Style flag for binary mode availability.
static const long MODE_INT = 4
Style flag for signed integer mode availablity.
static const long MODE_UNSIGNED = 8
Style flag for unsigned integer mode availability.
static const long MODE_HEXADECIMAL = 2
Style flag for hexadecimal mode availability.
static const long MODE_FLOAT = 16
Style flag for float mode availability.
static const long MODE_DOUBLE = 32
Style flag for double mode availability.
static const long NO_MODE_CHOICER = 64
Style flag for base choicer visibility.
Private Types
enum { ID_BASE = 20000 , ID_TEXT }
IDs for the subwidgets.
Private Member Functions
void create (const wxSize &size)
void update ()
void onModeChoice (wxCommandEvent &event)
void onText (wxCommandEvent &event)
Private Attributes
FocusTrackingTextCtrl * text_
Text field widget.
wxChoice * modeChoice_
Mode choicer widget.
long style_
Current style flags of the widget.
Value value_
Current value of the widget.
wxString stringValue_
Dummy value string for the validators.
long mode_
Current mode of the widget.
wxTextValidator * binValidator_
Binary input validator.
wxTextValidator * hexValidator_
Hexadecimal input validator.
wxTextValidator * intValidator_
Signed integer input validator.
wxTextValidator * unsignedValidator_
Unsigned integer input validator.
wxTextValidator * floatValidator_
Float input validator.
Static Private Attributes
static const wxString MODE_STRING_BIN = _T("bin")
Choicer item string for the binary mode.
static const wxString MODE_STRING_HEX = _T("hex")
Choicer item string for the hexadecimal mode.
static const wxString MODE_STRING_INT = _T("int")
Choicer item string for the integer mode.
static const wxString MODE_STRING_UNSIGNED = _T("unsigned")
Choicer item string for the unsigned mode.
static const wxString MODE_STRING_FLOAT = _T("float")
Choicer item string for the float mode.
static const wxString MODE_STRING_DOUBLE = _T("double")
Choicer item string for the double mode.
static const int CHOICER_WIDTH = 100
Mode choicer width.
Detailed Description
Text field widget for numeric value input.
The widget value can be modified in hexadecimal, binary, int, unsigned int and floating point format. The widget value is always the same four bytes of memory, and the bit pattern is interpreted depending on the selected mode. Text field mode can be selected using an optional mode choicer. Available modes for the choicer are selected by passing the following style flags to the constructor: MODE_HEXADECIMAL, MODE_BINARY, MODE_INT, MODE_UNSIGNED, MODE_FLOAT and MODE_DOUBLE
Note that the extra bits in the double value is ignored when the mode is changed from double to any of the other modes.
The mode choicer widget can be disabled by using NO_MODE_CHOICER style flag.
Definition at line 59 of file NumberControl.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
IDs for the subwidgets.
Enumerator
ID_BASE
ID_TEXT
Definition at line 166 of file NumberControl.hh.
         {
        ID_BASE = 20000,
        ID_TEXT
    };
Constructor & Destructor Documentation
NumberControl()
NumberControl::NumberControl (wxWindow * parent, wxWindowID id = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = (MODE_HEXADECIMAL | MODE_BINARY | MODE_INT | MODE_UNSIGNED | MODE_FLOAT), int initial = 0, const wxString & name = _T("NumberControl"))
The Constructor.
Parameters
window Parent window of the widget.
id ID of the widget.
pos Position of the widget.
size Size of the widget.
style Style flags for the widget, see class comment for list of available flags.
value Initial value of the input.
name Name identifier for the widget.
Exceptions
OutOfRange If the value is out of the range.
InvalidData If the minimum value is higher than the maximum.
Definition at line 83 of file NumberControl.cc.
                          :
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL, name),
    text_(NULL),
    modeChoice_(NULL),
    style_(style),
    stringValue_(_T("")),
    mode_(0),
    binValidator_(NULL),
    hexValidator_(NULL),
    intValidator_(NULL),
    unsignedValidator_(NULL),
    floatValidator_(NULL) {
    value_.unsignedValue =initial;
    // Create subwidgets.
    create(size);
}
References unsignedValue().
~NumberControl()
NumberControl::~NumberControl () virtual
The destructor.
Definition at line 113 of file NumberControl.cc.
{
    if (binValidator_ != NULL) {
        delete binValidator_;
    }
    if (hexValidator_ != NULL) {
        delete hexValidator_;
    }
    if (intValidator_ != NULL) {
        delete intValidator_;
    }
    if (unsignedValidator_ != NULL) {
        delete unsignedValidator_;
    }
    if (floatValidator_ != NULL) {
        delete floatValidator_;
    }
}
References binValidator_, floatValidator_, hexValidator_, intValidator_, and unsignedValidator_.
Member Function Documentation
create()
void NumberControl::create (const wxSize & size) private
Creates the textfield and optional base choicer subwidgets for the control.
Definition at line 136 of file NumberControl.cc.
{
    wxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
    int textWidth = size.GetWidth();
    if ((style_ & NO_MODE_CHOICER) == 0) {
        textWidth = textWidth - CHOICER_WIDTH;
        if (textWidth < 20) {
            textWidth = 20;
        }
    }
    // Create text field widget.
    text_ =
        new FocusTrackingTextCtrl(this, ID_TEXT, _T(""), wxDefaultPosition,
                                  wxSize(textWidth, -1));
    sizer->Add(text_, 0, wxALIGN_CENTER_VERTICAL);
    if ((style_ & NO_MODE_CHOICER) == 0) {
        // Create base choicer.
        modeChoice_ = new wxChoice(this, ID_BASE, wxDefaultPosition,
                                   wxSize(CHOICER_WIDTH, -1));
        // append base choices
        if ((style_ & MODE_BINARY) != 0) {
            modeChoice_->Append(MODE_STRING_BIN);
        }
        if ((style_ & MODE_HEXADECIMAL) != 0) {
            modeChoice_->Append(MODE_STRING_HEX);
        }
        if ((style_ & MODE_INT) != 0) {
            modeChoice_->Append(MODE_STRING_INT);
        }
        if ((style_ & MODE_UNSIGNED) != 0) {
            modeChoice_->Append(MODE_STRING_UNSIGNED);
        }
        if ((style_ & MODE_FLOAT) != 0) {
            modeChoice_->Append(MODE_STRING_FLOAT);
        }
        if ((style_ & MODE_DOUBLE) != 0) {
            modeChoice_->Append(MODE_STRING_DOUBLE);
        }
        sizer->Add(modeChoice_, 0, wxALIGN_CENTER_VERTICAL);
        // set initial mode
        if ((style_ & MODE_INT) != 0) {
            setIntMode();
        } else if ((style_ & MODE_UNSIGNED) != 0) {
            setUnsignedMode();
        } else if ((style_ & MODE_FLOAT) != 0) {
            setFloatMode();
        } else if ((style_ & MODE_HEXADECIMAL) != 0) {
            setHexMode();
        } else if ((style_ & MODE_BINARY) != 0) {
            setBinMode();
        } else if ((style_ & MODE_DOUBLE) != 0) {
            setDoubleMode();
        } else {
            assert(false);
        }
    }
    SetSizer(sizer);
    Fit();
}
References assert, CHOICER_WIDTH, ID_BASE, ID_TEXT, MODE_BINARY, MODE_DOUBLE, MODE_FLOAT, MODE_HEXADECIMAL, MODE_INT, MODE_STRING_BIN, MODE_STRING_DOUBLE, MODE_STRING_FLOAT, MODE_STRING_HEX, MODE_STRING_INT, MODE_STRING_UNSIGNED, MODE_UNSIGNED, modeChoice_, NO_MODE_CHOICER, setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), setUnsignedMode(), style_, and text_.
doubleValue()
double NumberControl::doubleValue () const
Returns the current value.
Returns
Current value of the widget as double.
Definition at line 450 of file NumberControl.cc.
{
    return value_.doubleValue;
}
References NumberControl::Value::doubleValue, and value_.
Referenced by MemoryValueDialog::doubleValue(), and SimulateDialog::onUpdateValue().
floatValue()
float NumberControl::floatValue () const
Returns the current value.
Returns
Current value of the widget as float.
Definition at line 439 of file NumberControl.cc.
{
    return value_.floatValue;
}
References NumberControl::Value::floatValue, and value_.
intValue()
int NumberControl::intValue () const
Returns the current value.
Returns
Current value of the widget as int.
Definition at line 417 of file NumberControl.cc.
{
    return value_.intValue;
}
References NumberControl::Value::intValue, and value_.
Referenced by MemoryValueDialog::intValue(), and SimulateDialog::onUpdateValue().
mode()
long NumberControl::mode () const
Returns the widget mode style flag.
Returns
Current mode of the widget.
Definition at line 764 of file NumberControl.cc.
{
    return mode_;
}
References mode_.
Referenced by MemoryValueDialog::mode(), and SimulateDialog::onUpdateValue().
onModeChoice()
void NumberControl::onModeChoice (wxCommandEvent & event) private
Event handler for the mode choicer.
Updates text field according to the selected mode.
Definition at line 327 of file NumberControl.cc.
{
    // Udate the value from the textfield input.
    wxCommandEvent dummy;
    onText(dummy);
    // Set the selected mode.
    if (modeChoice_->GetStringSelection() == MODE_STRING_BIN) {
        setBinMode();
    }else if (modeChoice_->GetStringSelection() == MODE_STRING_HEX) {
        setHexMode();
    } else if (modeChoice_->GetStringSelection() == MODE_STRING_INT) {
        setIntMode();
    } else if (modeChoice_->GetStringSelection() == MODE_STRING_UNSIGNED) {
        setUnsignedMode();
    } else if (modeChoice_->GetStringSelection() == MODE_STRING_FLOAT) {
        setFloatMode();
    } else if (modeChoice_->GetStringSelection() == MODE_STRING_DOUBLE) {
        setDoubleMode();
    } else {
        assert(false);
    }
}
References assert, dummy, MODE_STRING_BIN, MODE_STRING_DOUBLE, MODE_STRING_FLOAT, MODE_STRING_HEX, MODE_STRING_INT, MODE_STRING_UNSIGNED, modeChoice_, onText(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), and setUnsignedMode().
onText()
void NumberControl::onText (wxCommandEvent & event) private
Event handler, which validates the text field value and transfers data from the text field to the value variable.
This event handler is called when user has input new value to the text field.
Definition at line 270 of file NumberControl.cc.
{
    string stringValue = WxConversion::toString(text_->GetValue());
    if (stringValue == "") {
        value_.intValue = 0;
        update();
        wxCommandEvent textEvent(wxEVT_COMMAND_TEXT_UPDATED, GetId());
        GetParent()->GetEventHandler()->AddPendingEvent(textEvent);
        return;
    }
    try {
        if (mode_ == MODE_INT) {
            // int mode
            value_.intValue = Conversion::toInt(stringValue);
        } else if (mode_ == MODE_BINARY) {
            // binary mode
            stringValue = stringValue + "b";
            value_.intValue = Conversion::toInt(stringValue);
        } else if (mode_ == MODE_HEXADECIMAL) {
            // hexadecimal mode
            stringValue = "0x" + stringValue;
            value_.intValue = Conversion::toInt(stringValue);
        } else if (mode_ == MODE_UNSIGNED) {
            // unsigned mode
            value_.unsignedValue = Conversion::toUnsignedInt(stringValue);
        } else if (mode_ == MODE_FLOAT) {
            // float mode
            value_.floatValue = Conversion::toFloat(stringValue);
        } else if (mode_ == MODE_DOUBLE) {
            // double mode
            value_.doubleValue = Conversion::toDouble(stringValue);
        } else {
            assert(false);
        }
    } catch (NumberFormatException& e) {
        // invalid input in the text field
        value_.intValue = 0;
    }
    wxCommandEvent textEvent(wxEVT_COMMAND_TEXT_UPDATED, GetId());
    GetParent()->GetEventHandler()->AddPendingEvent(textEvent);
    if (text_->IsModified()) {
        update();
    }
}
References assert, NumberControl::Value::doubleValue, NumberControl::Value::floatValue, NumberControl::Value::intValue, mode_, MODE_BINARY, MODE_DOUBLE, MODE_FLOAT, MODE_HEXADECIMAL, MODE_INT, MODE_UNSIGNED, text_, Conversion::toDouble(), Conversion::toFloat(), Conversion::toInt(), WxConversion::toString(), Conversion::toUnsignedInt(), NumberControl::Value::unsignedValue, update(), and value_.
Referenced by onModeChoice().
setBinMode()
void NumberControl::setBinMode ()
Sets the widget to binary mode.
Exceptions
NotAvailable If the MODE_BINARY style was not specified to the contructor.
Definition at line 493 of file NumberControl.cc.
{
    // Check that the binary mode is available.
    if ((style_ & MODE_BINARY) == 0) {
        // Binary mode not available.
        string procName = "NubmerControl::setBinMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create binary input validator if necessary.
    if (binValidator_ == NULL) {
        binValidator_ =
            new wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST, &stringValue_);
#if wxCHECK_VERSION(2, 5, 4)
        wxArrayString includes;
        includes.Add(_T("0"));
        includes.Add(_T("1"));
        binValidator_->SetIncludes(includes);
#else
        binValidator_->SetIncludeList(
            wxStringList(_T("0"), _T("1"), NULL));
#endif
    }
    // Set the binary validator and update the widget.
    text_->SetValidator(*binValidator_);
    mode_ = MODE_BINARY;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_BIN) {
        modeChoice_->SetStringSelection(MODE_STRING_BIN);
    }
    update();
}
References binValidator_, mode_, MODE_BINARY, MODE_STRING_BIN, modeChoice_, stringValue_, style_, text_, and update().
Referenced by create(), and onModeChoice().
setDoubleMode()
void NumberControl::setDoubleMode ()
Sets the widget to double mode.
Exceptions
NotAvailable If the MODE_DOUBLE style was not specified to the constructor.
Definition at line 709 of file NumberControl.cc.
{
    // Check that the double mode is available.
    if ((style_ & MODE_DOUBLE) == 0) {
        // Double mode not available.
        string procName = "NubmerControl::setDoubleMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create float/double input validator if necessary.
    if (floatValidator_ == NULL) {
        floatValidator_ =
            new wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST, &stringValue_);
#if wxCHECK_VERSION(2, 5, 4)
        wxArrayString includes;
        includes.Add(_T("0"));
        includes.Add(_T("1"));
        includes.Add(_T("2"));
        includes.Add(_T("3"));
        includes.Add(_T("4"));
        includes.Add(_T("5"));
        includes.Add(_T("6"));
        includes.Add(_T("7"));
        includes.Add(_T("8"));
        includes.Add(_T("9"));
        includes.Add(_T("e"));
        includes.Add(_T("."));
        includes.Add(_T("-"));
        includes.Add(_T("+"));
        floatValidator_->SetIncludes(includes);
#else
        floatValidator_->SetIncludeList(
            wxStringList(_T("0"), _T("1"), _T("2"), _T("3"), _T("4"),
             _T("5"), _T("6"), _T("7"), _T("8"), _T("9"),
                         _T("e"), _T("."), _T("-"), _T("+"), NULL));
#endif
    }
    // Set the float/double validator and update the widget.
    text_->SetValidator(*floatValidator_);
    mode_ = MODE_DOUBLE;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_DOUBLE) {
        modeChoice_->SetStringSelection(MODE_STRING_DOUBLE);
    }
    update();
}
References floatValidator_, mode_, MODE_DOUBLE, MODE_STRING_DOUBLE, modeChoice_, stringValue_, style_, text_, and update().
Referenced by create(), and onModeChoice().
setFloatMode()
void NumberControl::setFloatMode ()
Sets the widget to float mode.
Exceptions
NotAvailable If the MODE_FLOAT style was not specified to the constructor.
Definition at line 653 of file NumberControl.cc.
{
    // Check that the float mode is available.
    if ((style_ & MODE_FLOAT) == 0) {
        // Float mode not available.
        string procName = "NubmerControl::setFloatMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create float input validator if necessary.
    if (floatValidator_ == NULL) {
        floatValidator_ =
            new wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST, &stringValue_);
#if wxCHECK_VERSION(2, 5, 4)
        wxArrayString includes;
        includes.Add(_T("0"));
        includes.Add(_T("1"));
        includes.Add(_T("2"));
        includes.Add(_T("3"));
        includes.Add(_T("4"));
        includes.Add(_T("5"));
        includes.Add(_T("6"));
        includes.Add(_T("7"));
        includes.Add(_T("8"));
        includes.Add(_T("9"));
        includes.Add(_T("e"));
        includes.Add(_T("."));
        includes.Add(_T("-"));
        includes.Add(_T("+"));
        floatValidator_->SetIncludes(includes);
#else
        floatValidator_->SetIncludeList(
            wxStringList(_T("0"), _T("1"), _T("2"), _T("3"), _T("4"),
             _T("5"), _T("6"), _T("7"), _T("8"), _T("9"),
                         _T("e"), _T("."), _T("-"), _T("+"), NULL));
#endif
    }
    // Set the float validator and update the widget.
    text_->SetValidator(*floatValidator_);
    mode_ = MODE_FLOAT;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_FLOAT) {
        modeChoice_->SetStringSelection(MODE_STRING_FLOAT);
    }
    update();
}
References floatValidator_, mode_, MODE_FLOAT, MODE_STRING_FLOAT, modeChoice_, stringValue_, style_, text_, and update().
Referenced by create(), and onModeChoice().
setHexMode()
void NumberControl::setHexMode ()
Sets the widget to hexadecimal mode.
Exceptions
NotAvailable If the MODE_HEXADECIMAL was not specified to the constructor.
Definition at line 536 of file NumberControl.cc.
{
    // Check that the hexadecimal mode is available.
    if ((style_ & MODE_HEXADECIMAL) == 0) {
        // Hexadecimal mode not available.
        string procName = "NubmerControl::setHexMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create hexadecimal input validator if necessary.
    if (hexValidator_ == NULL) {
        hexValidator_ =
            new wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST, &stringValue_);
#if wxCHECK_VERSION(2, 5, 4)
        wxArrayString includes;
        includes.Add(_T("0"));
        includes.Add(_T("1"));
        includes.Add(_T("2"));
        includes.Add(_T("3"));
        includes.Add(_T("4"));
        includes.Add(_T("5"));
        includes.Add(_T("6"));
        includes.Add(_T("7"));
        includes.Add(_T("8"));
        includes.Add(_T("9"));
        includes.Add(_T("a"));
        includes.Add(_T("b"));
        includes.Add(_T("c"));
        includes.Add(_T("d"));
        includes.Add(_T("e"));
        includes.Add(_T("f"));
        includes.Add(_T("A"));
        includes.Add(_T("B"));
        includes.Add(_T("C"));
        includes.Add(_T("D"));
        includes.Add(_T("E"));
        includes.Add(_T("F"));
        hexValidator_->SetIncludes(includes);
#else
        hexValidator_->SetIncludeList(
            wxStringList(_T("0"), _T("1"), _T("2"), _T("3"), _T("4"), _T("5"),
             _T("6"), _T("7"), _T("8"), _T("9"),
                         _T("a"), _T("b"), _T("c"), _T("d"), _T("e"), _T("f"),
             _T("A"), _T("B"), _T("C"), _T("D"),
                         _T("E"), _T("F"), NULL));
#endif
    }
    // Set the hexadecimal validator and update the widget.
    text_->SetValidator(*hexValidator_);
    mode_ = MODE_HEXADECIMAL;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_HEX) {
        modeChoice_->SetStringSelection(MODE_STRING_HEX);
    }
    update();
}
References hexValidator_, mode_, MODE_HEXADECIMAL, MODE_STRING_HEX, modeChoice_, stringValue_, style_, text_, and update().
Referenced by create(), and onModeChoice().
setIntMode()
void NumberControl::setIntMode ()
Sets the widget to int mode.
Exceptions
NotAvailable If the MODE_INT style was not specified to the constructor.
Definition at line 462 of file NumberControl.cc.
{
    // Check that the int mode is available.
    if ((style_ & MODE_INT) == 0) {
        // Int mode not available.
        string procName = "NubmerControl::setIntMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create decimal input validator if necessary.
    if (intValidator_ == NULL) {
        intValidator_ = new wxTextValidator(wxFILTER_NUMERIC, &stringValue_);
    }
    // Set the decimal validator and update the widget.
    text_->SetValidator(*intValidator_);
    mode_ = MODE_INT;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_INT) {
        modeChoice_->SetStringSelection(MODE_STRING_INT);
    }
    update();
}
References intValidator_, mode_, MODE_INT, MODE_STRING_INT, modeChoice_, stringValue_, style_, text_, and update().
Referenced by create(), and onModeChoice().
setUnsignedMode()
void NumberControl::setUnsignedMode ()
Sets the widget to unsigned int mode.
Exceptions
NotAvailable If the MODE_UNSIGNED style was not specified to the constructor.
Definition at line 602 of file NumberControl.cc.
{
    // Check that the unsigned mode is available.
    if ((style_ & MODE_UNSIGNED) == 0) {
        // Unsigned mode not available.
        string procName = "NubmerControl::setUnsignedMode";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    // Create decimal input validator if necessary.
    if (unsignedValidator_ == NULL) {
        unsignedValidator_ =
            new wxTextValidator(wxFILTER_INCLUDE_CHAR_LIST, &stringValue_);
#if wxCHECK_VERSION(2, 5, 4)
        wxArrayString includes;
        includes.Add(_T("0"));
        includes.Add(_T("1"));
        includes.Add(_T("2"));
        includes.Add(_T("3"));
        includes.Add(_T("4"));
        includes.Add(_T("5"));
        includes.Add(_T("6"));
        includes.Add(_T("7"));
        includes.Add(_T("8"));
        includes.Add(_T("9"));
        unsignedValidator_->SetIncludes(includes);
#else
        unsignedValidator_->SetIncludeList(
            wxStringList(_T("0"), _T("1"), _T("2"), _T("3"), _T("4"), _T("5"),
             _T("6"), _T("7"), _T("8"), _T("9"), NULL));
#endif
    }
    // Set the decimal validator and update the widget.
    text_->SetValidator(*unsignedValidator_);
    mode_ = MODE_UNSIGNED;
    if (modeChoice_ != NULL &&
        modeChoice_->GetStringSelection() != MODE_STRING_UNSIGNED) {
        modeChoice_->SetStringSelection(MODE_STRING_UNSIGNED);
    }
    update();
}
References mode_, MODE_STRING_UNSIGNED, MODE_UNSIGNED, modeChoice_, stringValue_, style_, text_, unsignedValidator_, and update().
Referenced by create(), and onModeChoice().
setValue() [1/5]
void NumberControl::setValue (const double value)
Sets the value on the widget.
Parameters
value Double value to set.
Definition at line 405 of file NumberControl.cc.
{
    value_.doubleValue = value;
    update();
}
References NumberControl::Value::doubleValue, update(), and value_.
setValue() [2/5]
void NumberControl::setValue (const float value)
Sets the value on the widget.
Parameters
value Float value to set.
Definition at line 393 of file NumberControl.cc.
{
    value_.floatValue = value;
    update();
}
References NumberControl::Value::floatValue, update(), and value_.
setValue() [3/5]
void NumberControl::setValue (const int value)
Sets the value on the widget.
Parameters
value Unsigned value to set.
Definition at line 358 of file NumberControl.cc.
{
    value_.intValue = value;
    update();
}
References NumberControl::Value::intValue, update(), and value_.
setValue() [4/5]
void NumberControl::setValue (const ULongWord value)
Sets the value on the widget.
Parameters
value Integer value to set.
Definition at line 381 of file NumberControl.cc.
{
    value_.uLongValue = value;
    update();
}
References NumberControl::Value::uLongValue, update(), and value_.
Referenced by AddressSpaceDialog::onBitWidth(), AddressSpaceDialog::onMaxAddress(), AddressSpaceDialog::onMinAddress(), MemoryValueDialog::setValue(), and AddressSpaceDialog::TransferDataToWindow().
setValue() [5/5]
void NumberControl::setValue (const unsigned int value)
Sets the value on the widget.
Parameters
value Integer value to set.
Definition at line 370 of file NumberControl.cc.
{
    value_.unsignedValue = value;
    update();
}
References NumberControl::Value::unsignedValue, update(), and value_.
uLongValue()
ULongWord NumberControl::uLongValue () const
unsignedValue()
unsigned int NumberControl::unsignedValue () const
Returns the current value.
Returns
Current value of the widget as unsigned int
Definition at line 428 of file NumberControl.cc.
{
    return value_.unsignedValue;
}
References NumberControl::Value::unsignedValue, and value_.
Referenced by NumberControl(), AddressSpaceDialog::onMaxAddress(), AddressSpaceDialog::onMinAddress(), and AddressSpaceDialog::onOK().
update()
void NumberControl::update () private
Updates the value on the text field according to the selected mode.
Definition at line 209 of file NumberControl.cc.
                      {
    // binary mode
    if (mode_ == MODE_BINARY) {
        string binString = Conversion::toBinString(value_.intValue);
        // Strip trailing 'b' from the binary string.
        binString = binString.substr(0, binString.length() - 1);
        text_->SetValue(WxConversion::toWxString(binString));
        return;
    }
    // hexadecimal mode
    if (mode_ == MODE_HEXADECIMAL) {
        string hexString = Conversion::toHexString(value_.intValue);
        // Strip '0x' from the begining of the hexstring.
        hexString = hexString.substr(2, hexString.length() - 2);
        text_->SetValue(WxConversion::toWxString(hexString));
        return;
    }
    // int mode
    if (mode_ == MODE_INT) {
        string intString = Conversion::toString(value_.intValue);
        text_->SetValue(WxConversion::toWxString(intString));
        return;
    }
    // unsigned mode
    if (mode_ == MODE_UNSIGNED) {
        string unsignedString = Conversion::toString(value_.unsignedValue);
        text_->SetValue(WxConversion::toWxString(unsignedString));
        return;
    }
    // float mode
    if (mode_ == MODE_FLOAT) {
        string floatString = Conversion::toString(value_.floatValue);
        text_->SetValue(WxConversion::toWxString(floatString));
        return;
    }
    // float mode
    if (mode_ == MODE_DOUBLE) {
        string doubleString = Conversion::toString(value_.doubleValue);
        text_->SetValue(WxConversion::toWxString(doubleString));
        return;
    }
    // Error: no mode selected.
    assert(false);
}
References assert, NumberControl::Value::doubleValue, NumberControl::Value::floatValue, NumberControl::Value::intValue, mode_, MODE_BINARY, MODE_DOUBLE, MODE_FLOAT, MODE_HEXADECIMAL, MODE_INT, MODE_UNSIGNED, text_, Conversion::toBinString(), Conversion::toHexString(), Conversion::toString(), WxConversion::toWxString(), NumberControl::Value::unsignedValue, and value_.
Referenced by onText(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), setUnsignedMode(), setValue(), setValue(), setValue(), setValue(), and setValue().
Member Data Documentation
binValidator_
wxTextValidator* NumberControl::binValidator_ private
Binary input validator.
Definition at line 155 of file NumberControl.hh.
Referenced by setBinMode(), and ~NumberControl().
CHOICER_WIDTH
const int NumberControl::CHOICER_WIDTH = 100 static private
Mode choicer width.
Definition at line 152 of file NumberControl.hh.
Referenced by create().
floatValidator_
wxTextValidator* NumberControl::floatValidator_ private
Float input validator.
Definition at line 163 of file NumberControl.hh.
Referenced by setDoubleMode(), setFloatMode(), and ~NumberControl().
hexValidator_
wxTextValidator* NumberControl::hexValidator_ private
Hexadecimal input validator.
Definition at line 157 of file NumberControl.hh.
Referenced by setHexMode(), and ~NumberControl().
intValidator_
wxTextValidator* NumberControl::intValidator_ private
Signed integer input validator.
Definition at line 159 of file NumberControl.hh.
Referenced by setIntMode(), and ~NumberControl().
mode_
long NumberControl::mode_ private
Current mode of the widget.
Definition at line 137 of file NumberControl.hh.
Referenced by mode(), onText(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), setUnsignedMode(), and update().
MODE_BINARY
const long NumberControl::MODE_BINARY = 1 static
Style flag for binary mode availability.
Definition at line 94 of file NumberControl.hh.
Referenced by create(), MemoryValueDialog::createContents(), SimulateDialog::createContents(), onText(), setBinMode(), and update().
MODE_DOUBLE
const long NumberControl::MODE_DOUBLE = 32 static
Style flag for double mode availability.
Definition at line 104 of file NumberControl.hh.
Referenced by create(), SimulateDialog::createContents(), onText(), SimulateDialog::onUpdateValue(), MemoryControl::onWriteMemory(), setDoubleMode(), and update().
MODE_FLOAT
const long NumberControl::MODE_FLOAT = 16 static
Style flag for float mode availability.
Definition at line 102 of file NumberControl.hh.
Referenced by create(), MemoryValueDialog::createContents(), SimulateDialog::createContents(), onText(), setFloatMode(), and update().
MODE_HEXADECIMAL
const long NumberControl::MODE_HEXADECIMAL = 2 static
Style flag for hexadecimal mode availability.
Definition at line 100 of file NumberControl.hh.
Referenced by create(), MemoryValueDialog::createContents(), SimulateDialog::createContents(), AddressSpaceDialog::createContents(), onText(), setHexMode(), and update().
MODE_INT
const long NumberControl::MODE_INT = 4 static
Style flag for signed integer mode availablity.
Definition at line 96 of file NumberControl.hh.
Referenced by create(), SimulateDialog::createContents(), onText(), setIntMode(), and update().
MODE_STRING_BIN
const wxString NumberControl::MODE_STRING_BIN = _T("bin") static private
Choicer item string for the binary mode.
Definition at line 140 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setBinMode().
MODE_STRING_DOUBLE
const wxString NumberControl::MODE_STRING_DOUBLE = _T("double") static private
Choicer item string for the double mode.
Definition at line 150 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setDoubleMode().
MODE_STRING_FLOAT
const wxString NumberControl::MODE_STRING_FLOAT = _T("float") static private
Choicer item string for the float mode.
Definition at line 148 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setFloatMode().
MODE_STRING_HEX
const wxString NumberControl::MODE_STRING_HEX = _T("hex") static private
Choicer item string for the hexadecimal mode.
Definition at line 142 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setHexMode().
MODE_STRING_INT
const wxString NumberControl::MODE_STRING_INT = _T("int") static private
Choicer item string for the integer mode.
Definition at line 144 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setIntMode().
MODE_STRING_UNSIGNED
const wxString NumberControl::MODE_STRING_UNSIGNED = _T("unsigned") static private
Choicer item string for the unsigned mode.
Definition at line 146 of file NumberControl.hh.
Referenced by create(), onModeChoice(), and setUnsignedMode().
MODE_UNSIGNED
const long NumberControl::MODE_UNSIGNED = 8 static
Style flag for unsigned integer mode availability.
Definition at line 98 of file NumberControl.hh.
Referenced by create(), MemoryValueDialog::createContents(), SimulateDialog::createContents(), AddressSpaceDialog::createContents(), onText(), setUnsignedMode(), and update().
modeChoice_
wxChoice* NumberControl::modeChoice_ private
Mode choicer widget.
Definition at line 117 of file NumberControl.hh.
Referenced by create(), onModeChoice(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), and setUnsignedMode().
NO_MODE_CHOICER
const long NumberControl::NO_MODE_CHOICER = 64 static
Style flag for base choicer visibility.
Definition at line 106 of file NumberControl.hh.
Referenced by create().
stringValue_
wxString NumberControl::stringValue_ private
Dummy value string for the validators.
Definition at line 134 of file NumberControl.hh.
Referenced by setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), and setUnsignedMode().
style_
long NumberControl::style_ private
Current style flags of the widget.
Definition at line 120 of file NumberControl.hh.
Referenced by create(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), and setUnsignedMode().
text_
FocusTrackingTextCtrl* NumberControl::text_ private
Text field widget.
Definition at line 115 of file NumberControl.hh.
Referenced by create(), onText(), setBinMode(), setDoubleMode(), setFloatMode(), setHexMode(), setIntMode(), setUnsignedMode(), and update().
unsignedValidator_
wxTextValidator* NumberControl::unsignedValidator_ private
Unsigned integer input validator.
Definition at line 161 of file NumberControl.hh.
Referenced by setUnsignedMode(), and ~NumberControl().
value_
Value NumberControl::value_ private
Current value of the widget.
Definition at line 131 of file NumberControl.hh.
Referenced by doubleValue(), floatValue(), intValue(), onText(), setValue(), setValue(), setValue(), setValue(), setValue(), unsignedValue(), and update().
The documentation for this class was generated from the following files:
NumberControl.hh
NumberControl.cc