OpenASIP: CallPathTracker Class Reference
CallPathTracker Class Reference
#include <CallPathTracker.hh>
Classes
struct ProcedureTransfer
Public Types
typedef std::deque< ProcedureTransfer > ProcedureTransferQueue
Public Member Functions
CallPathTracker (SimulatorFrontend &subject, unsigned, int historyLength)
virtual ~CallPathTracker ()
virtual void addProcedureTransfer (ClockCycleCount cycle, InstructionAddress address, InstructionAddress sourceAddress, bool isEntry)
const ProcedureTransferQueue & transfers () const
const ProcedureTransferQueue backTrace () const
Public Member Functions inherited from ProcedureTransferTracker
ProcedureTransferTracker (SimulatorFrontend &subject, ExecutionTrace &traceDB)
ProcedureTransferTracker (SimulatorFrontend &subject)
virtual ~ProcedureTransferTracker ()
virtual void handleEvent ()
Public Member Functions inherited from Listener
Listener ()
virtual ~Listener ()
virtual void handleEvent (int event)
Private Attributes
std::size_t historyLength_
max number of last calls/returns to store
ProcedureTransferQueue transfers_
the transfers are stored in a queue of which size is kept under historyLength_
Detailed Description
Tracks procedure transfers in the simulated program and stores them in memory for quick viewing during simulation/debugging.
There should be one instance of this tracker for each tracked core.
Definition at line 51 of file CallPathTracker.hh.
Member Typedef Documentation
ProcedureTransferQueue
typedef std::deque<ProcedureTransfer> CallPathTracker::ProcedureTransferQueue
Definition at line 60 of file CallPathTracker.hh.
Constructor & Destructor Documentation
CallPathTracker()
CallPathTracker::CallPathTracker (SimulatorFrontend & subject, unsigned , int historyLength) inline
Definition at line 62 of file CallPathTracker.hh.
                           :
        ProcedureTransferTracker(subject),
        historyLength_(historyLength) {}
~CallPathTracker()
virtual CallPathTracker::~CallPathTracker () inline virtual
Definition at line 68 of file CallPathTracker.hh.
{}
Member Function Documentation
addProcedureTransfer()
void CallPathTracker::addProcedureTransfer (ClockCycleCount cycle, InstructionAddress address, InstructionAddress sourceAddress, bool isEntry) virtual
This function is called to record a procedure transfer (call or return).
The default implementation stores the transfer to a TraceDB.
Reimplemented from ProcedureTransferTracker.
Definition at line 33 of file CallPathTracker.cc.
                  {
    if (transfers_.size() > historyLength_)
        transfers_.pop_front();
    ProcedureTransfer transfer;
    transfer.cycle = cycle;
    transfer.address = address;
    transfer.sourceAddress = sourceAddress;
    transfer.isEntry = isEntry;
    transfers_.push_back(transfer);
}
References CallPathTracker::ProcedureTransfer::address, CallPathTracker::ProcedureTransfer::cycle, historyLength_, CallPathTracker::ProcedureTransfer::isEntry, CallPathTracker::ProcedureTransfer::sourceAddress, and transfers_.
backTrace()
const CallPathTracker::ProcedureTransferQueue CallPathTracker::backTrace () const
Returns the history in a "back trace form" with calls and returns not contributing to the current call path stripped out.
Definition at line 54 of file CallPathTracker.cc.
{
    ProcedureTransferQueue allTransfers = transfers();
    ProcedureTransferQueue bt;
    int callsToSkip = 0;
    CallPathTracker::ProcedureTransferQueue::const_reverse_iterator i =
        allTransfers.rbegin();
    // Define end iterator as an explilcit variable to avoid compiling
    // bug under Mac OS X.
    CallPathTracker::ProcedureTransferQueue::const_reverse_iterator e =
        allTransfers.rend();
    for (; i != e; ++i) {
        CallPathTracker::ProcedureTransfer tr = *i;
        if (!tr.isEntry) {
            ++callsToSkip;
            continue;
        }
        if (callsToSkip == 0) {
            bt.push_back(tr);
        } else {
            callsToSkip--;
        }
    }
    return bt;
}
References CallPathTracker::ProcedureTransfer::isEntry, and transfers().
Referenced by BackTraceCommand::execute().
transfers()
const ProcedureTransferQueue & CallPathTracker::transfers () const inline
Definition at line 76 of file CallPathTracker.hh.
{ return transfers_; }
References transfers_.
Referenced by backTrace(), and BackTraceCommand::execute().
Member Data Documentation
historyLength_
std::size_t CallPathTracker::historyLength_ private
max number of last calls/returns to store
Definition at line 82 of file CallPathTracker.hh.
Referenced by addProcedureTransfer().
transfers_
ProcedureTransferQueue CallPathTracker::transfers_ private
the transfers are stored in a queue of which size is kept under historyLength_
Definition at line 85 of file CallPathTracker.hh.
Referenced by addProcedureTransfer(), and transfers().
The documentation for this class was generated from the following files:
CallPathTracker.hh
CallPathTracker.cc