OpenASIP: BFUpdateMoveOnBypass Class Reference
BFUpdateMoveOnBypass Class Reference
#include <BFUpdateMoveOnBypass.hh>
Public Member Functions
BFUpdateMoveOnBypass (BF2Scheduler &sched, MoveNode &src, MoveNode &mn)
bool operator() () override
virtual ~BFUpdateMoveOnBypass ()
TCEString reg ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
void undoOnlyMe () override
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Private Attributes
MoveNode & src_
MoveNode & dst_
bool force_
TCEString reg_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 41 of file BFUpdateMoveOnBypass.hh.
Constructor & Destructor Documentation
BFUpdateMoveOnBypass()
BFUpdateMoveOnBypass::BFUpdateMoveOnBypass (BF2Scheduler & sched, MoveNode & src, MoveNode & mn) inline
Definition at line 44 of file BFUpdateMoveOnBypass.hh.
                                       :
        BFOptimization(sched), src_(src), dst_(mn) {}
~BFUpdateMoveOnBypass()
virtual BFUpdateMoveOnBypass::~BFUpdateMoveOnBypass () inline virtual
Definition at line 49 of file BFUpdateMoveOnBypass.hh.
{}
Member Function Documentation
operator()()
bool BFUpdateMoveOnBypass::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 41 of file BFUpdateMoveOnBypass.cc.
{
    auto& dm = dst_.move();
    auto& sm = src_.move();
    // update the move
    dm.setSource(sm.source().copy());
    if (!src_.isSourceOperation()) {
        return true;
    }
    ProgramOperationPtr srcOp = src_.sourceOperationPtr();
    srcOp->addOutputNode(dst_);
    dst_.setSourceOperationPtr(srcOp);
    // set fu annotations
    for (int j = 0; j < sm.annotationCount(); j++) {
        TTAProgram::ProgramAnnotation anno = sm.annotation(j);
        if (anno.id() == ProgramAnnotation::ANN_ALLOWED_UNIT_SRC) {
            dm.addAnnotation(
                ProgramAnnotation(
                    ProgramAnnotation::ANN_ALLOWED_UNIT_SRC,
                    anno.payload()));
        }
        if (anno.id() ==
            ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC) {
            dm.addAnnotation(
                ProgramAnnotation(
                    ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC,
                    anno.payload()));
        }
        if (anno.id() ==
            ProgramAnnotation::ANN_REJECTED_UNIT_SRC) {
            dm.addAnnotation(
                ProgramAnnotation(
                    ProgramAnnotation::ANN_REJECTED_UNIT_SRC,
                    anno.payload()));
        }
    }
    return true;
}
References dst_, TTAProgram::ProgramAnnotation::id(), MoveNode::isSourceOperation(), MoveNode::move(), TTAProgram::ProgramAnnotation::payload(), TTAProgram::Move::setSource(), MoveNode::setSourceOperationPtr(), MoveNode::sourceOperationPtr(), and src_.
reg()
TCEString BFUpdateMoveOnBypass::reg () inline
Definition at line 50 of file BFUpdateMoveOnBypass.hh.
{ return reg_; }
References reg_.
undoOnlyMe()
void BFUpdateMoveOnBypass::undoOnlyMe () override protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 84 of file BFUpdateMoveOnBypass.cc.
{
        // unset programoperation from bypassed
    if (dst_.isSourceOperation()) {
        ProgramOperation& srcOp = dst_.sourceOperation();
        srcOp.removeOutputNode(dst_);
        dst_.unsetSourceOperation();
        // unset fu annotations
        dst_.move().removeAnnotations(
            TTAProgram::ProgramAnnotation::ANN_ALLOWED_UNIT_SRC);
        dst_.move().removeAnnotations(
            TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC);
        dst_.move().removeAnnotations(
            TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_SRC);
    }
    // do the actual unmerge by returning source to original register.
    dst_.move().setSource(src_.move().destination().copy());
}
References TTAProgram::ProgramAnnotation::ANN_ALLOWED_UNIT_SRC, TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC, TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_SRC, TTAProgram::Terminal::copy(), TTAProgram::Move::destination(), dst_, MoveNode::isSourceOperation(), MoveNode::move(), TTAProgram::AnnotatedInstructionElement::removeAnnotations(), ProgramOperation::removeOutputNode(), TTAProgram::Move::setSource(), MoveNode::sourceOperation(), src_, and MoveNode::unsetSourceOperation().
Member Data Documentation
dst_
MoveNode& BFUpdateMoveOnBypass::dst_ private
Definition at line 55 of file BFUpdateMoveOnBypass.hh.
Referenced by operator()(), and undoOnlyMe().
force_
bool BFUpdateMoveOnBypass::force_ private
Definition at line 56 of file BFUpdateMoveOnBypass.hh.
reg_
TCEString BFUpdateMoveOnBypass::reg_ private
Definition at line 57 of file BFUpdateMoveOnBypass.hh.
Referenced by reg().
src_
MoveNode& BFUpdateMoveOnBypass::src_ private
Definition at line 54 of file BFUpdateMoveOnBypass.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFUpdateMoveOnBypass.hh
BFUpdateMoveOnBypass.cc