OpenASIP: TTAMachine::ImmediateUnit Class Reference
TTAMachine::ImmediateUnit Class Reference
#include <ImmediateUnit.hh>
Public Member Functions
ImmediateUnit (const std::string &name, unsigned int size, unsigned int width, unsigned int maxReads, unsigned int guardLatency, Machine::Extension extension)
ImmediateUnit (const ObjectState *state)
~ImmediateUnit ()
virtual void setMaxWrites (int maxWrites)
virtual void setName (const std::string &name)
bool signExtends () const
bool zeroExtends () const
virtual Machine::Extension extensionMode () const
virtual int latency () const
virtual void setExtensionMode (Machine::Extension mode)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::RegisterFile
RegisterFile (const std::string &name, unsigned int size, unsigned int width, unsigned int maxReads, unsigned int maxwrites, unsigned int guardLatency, Type type, bool zeroRegister=false)
RegisterFile (const ObjectState *state)
virtual ~RegisterFile ()
virtual RegisterFile * copy () const
virtual int maxReads () const
virtual int maxWrites () const
virtual RegisterFile::Type type () const
virtual bool isNormal () const
virtual bool isVolatile () const
virtual bool isReserved () const
virtual void setMaxReads (int maxReads)
virtual void setType (RegisterFile::Type type)
virtual void setNumberOfRegisters (int registers)
virtual int guardLatency () const
virtual void setGuardLatency (int latency)
virtual bool isArchitectureEqual (const RegisterFile &rf) const
virtual bool isUsedAsGuard () const
virtual bool zeroRegister () const
virtual void setZeroRegister (const bool &value)
Port * firstReadPort () const
Port * firstWritePort () const
Public Member Functions inherited from TTAMachine::BaseRegisterFile
virtual ~BaseRegisterFile ()
virtual int numberOfRegisters () const
virtual int width () const
virtual int size () const
virtual void setWidth (int width)
virtual RFPort * port (const std::string &name) const
virtual RFPort * port (int index) const
Public Member Functions inherited from TTAMachine::Unit
virtual ~Unit ()
virtual bool hasPort (const std::string &name) const
virtual int portCount () const
virtual int outputPortCount (bool countBidir=false) const
virtual int inputPortCount (bool countBidir=false) const
virtual int bidirPortCount () const
virtual void setMachine (Machine &mach)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_IMMEDIATE_UNIT
ObjectState name for ImmediateUnit.
static const std::string OSKEY_EXTENSION = "extension"
ObjectState attribute key for the extension mode.
static const std::string OSVALUE_SIGN = "sign"
ObjectState attribute value for sign extension.
static const std::string OSVALUE_ZERO = "zero"
ObjectState attribute value for zero extension.
static const std::string OSKEY_LATENCY = "latency"
ObjectState attribute key for latency.
Static Public Attributes inherited from TTAMachine::RegisterFile
static const std::string OSNAME_REGISTER_FILE = "reg_file"
ObjectState name for RegisterFile.
static const std::string OSKEY_TYPE = "type"
ObjectState attribute key for register file type.
static const std::string OSVALUE_NORMAL = "normal"
ObjectState attribute value for normal register file type.
static const std::string OSVALUE_RESERVED = "reserved"
ObjectState attribute value for reserved register file type.
static const std::string OSVALUE_VOLATILE = "volatile"
ObjectState attribute value for volatile register file type.
static const std::string OSKEY_MAX_READS = "max_r"
ObjectState attribute key for maximum simultaneous readers.
static const std::string OSKEY_MAX_WRITES = "max_w"
ObjectState attribute key for maximum simultaneous writers.
static const std::string OSKEY_GUARD_LATENCY = "g_latency"
ObjectState attribute key for the guard latency.
static const std::string OSKEY_ZERO_REGISTER = "zero_register"
ObjectState attribute key for zero register flag.
Static Public Attributes inherited from TTAMachine::BaseRegisterFile
static const std::string OSNAME_BASE_REGISTER_FILE = "baseregfile"
ObjectState name for BaseRegisterFile.
static const std::string OSKEY_SIZE = "size"
ObjectState attribute key for the number of registers.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bit width of the registers.
Static Public Attributes inherited from TTAMachine::Unit
static const std::string OSNAME_UNIT = "unit"
ObjectState name for Unit.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Member Functions
virtual void setLatency (int latency)
void loadStateWithoutReferences (const ObjectState *state)
Private Attributes
Machine::Extension extension_
int latency_
Additional Inherited Members
Public Types inherited from TTAMachine::RegisterFile
enum Type { NORMAL , RESERVED , VOLATILE }
Type of the register file indicates how the RF is used.
Protected Member Functions inherited from TTAMachine::BaseRegisterFile
BaseRegisterFile (const std::string &name, int size, int width)
BaseRegisterFile (const ObjectState *state)
Protected Member Functions inherited from TTAMachine::Unit
Unit (const std::string &name)
Unit (const ObjectState *state)
virtual void removePort (Port &port)
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represent a immediate unit in the machine.
Definition at line 50 of file ImmediateUnit.hh.
Constructor & Destructor Documentation
ImmediateUnit() [1/2]
TTAMachine::ImmediateUnit::ImmediateUnit (const std::string & name, unsigned int size, unsigned int width, unsigned int maxReads, unsigned int guardLatency, Machine::Extension extension)
Constructor.
Parameters
name Name of the immediate unit.
size Number of immediate registers in the immediate unit.
width Bit width of the long immediate registers in the immediate unit.
extension Extension mode applied to the long immediate when it is narrower than the immediate register, see Machine::Extension.
latency Number of cycles needed between the encoding of a long immediate and its earliest transport on a data bus. The value "0" indicates that the long immediate can be read onto a bus in the same cycle in which the instruction that encodes it is executed.
Exceptions
OutOfRange If the given size or width is invalid.
InvalidName If the given name is not a valid name for a component.
Definition at line 74 of file ImmediateUnit.cc.
    : RegisterFile(
          name, size, width, maxReads, MAX_WRITES, guardLatency,
          RegisterFile::NORMAL),
      extension_(extension),
      latency_(LATENCY) {
    RegisterFile::setNumberOfRegisters(size);
    setWidth(width);
}
References TTAMachine::RegisterFile::setNumberOfRegisters(), TTAMachine::BaseRegisterFile::setWidth(), TTAMachine::BaseRegisterFile::size(), and TTAMachine::BaseRegisterFile::width().
ImmediateUnit() [2/2]
TTAMachine::ImmediateUnit::ImmediateUnit (const ObjectState * state)
Constructor.
Loads the state of the immediate unit from the given ObjectState instance. Does not load references to other components.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if connections to other machine parts cannot be made.
Definition at line 98 of file ImmediateUnit.cc.
                                                     : RegisterFile(state) {
    loadStateWithoutReferences(state);
}
References loadStateWithoutReferences().
~ImmediateUnit()
TTAMachine::ImmediateUnit::~ImmediateUnit ()
Destructor.
Definition at line 105 of file ImmediateUnit.cc.
{
    unsetMachine();
}
References unsetMachine().
Member Function Documentation
extensionMode()
Machine::Extension TTAMachine::ImmediateUnit::extensionMode () const virtual
Returns the extension mode of the immediate unit.
Returns
The extension mode of the immediate unit.
Definition at line 143 of file ImmediateUnit.cc.
{
    return extension_;
}
References extension_.
Referenced by ITemplateBroker::assignImmediate(), IUBroker::buildResources(), POMValidator::checkLongImmediates(), ITemplateBroker::findITemplates(), MachineConnectivityCheck::findPossibleSourcePorts(), ProDeIUEditPolicy::getCommand(), IUDialog::TransferDataToWindow(), and DefaultDecoderGenerator::writeInstructionTemplateProcedures().
latency()
int TTAMachine::ImmediateUnit::latency () const virtual
Returns the minimum number of cycles needed between the encoding of a long immediate and its earliest transport on a data bus.
Returns
Latency of the immediate unit.
Definition at line 155 of file ImmediateUnit.cc.
{
    return latency_;
}
References latency_.
Referenced by IUBroker::buildResources(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), CopyingDelaySlotFiller::checkImmediatesAfter(), CopyingDelaySlotFiller::collectMoves(), CopyingDelaySlotFiller::findJumpImmediate(), ControlFlowGraph::findLimmWrite(), BlockImplementationDialog::onHDBSelection(), LoopPrologAndEpilogBuilder::optimizeProlog(), setLatency(), IUDialog::TransferDataToWindow(), and CopyingDelaySlotFiller::tryToAssignNodes().
loadState()
void TTAMachine::ImmediateUnit::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if the connections to other machine parts cannot be made.
Reimplemented from TTAMachine::RegisterFile.
Definition at line 261 of file ImmediateUnit.cc.
{
    loadStateWithoutReferences(state);
    RegisterFile::loadState(state);
}
References TTAMachine::RegisterFile::loadState(), and loadStateWithoutReferences().
Referenced by TTAMachine::Machine::loadState().
loadStateWithoutReferences()
void TTAMachine::ImmediateUnit::loadStateWithoutReferences (const ObjectState * state) private
Loads the state of the immediate unit without references to other components.
Parameters
state The ObjectState instance from which the state is loaded.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 275 of file ImmediateUnit.cc.
{
    const string procName = "ImmediateUnit::loadStateWithoutReferences";
    if (state->name() != OSNAME_IMMEDIATE_UNIT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        string extension = state->stringAttribute(OSKEY_EXTENSION);
        if (extension == OSVALUE_SIGN) {
            setExtensionMode(Machine::SIGN);
        } else if (extension == OSVALUE_ZERO) {
            setExtensionMode(Machine::ZERO);
        } else {
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
        }
        setLatency(state->intAttribute(OSKEY_LATENCY));
        assert(latency_ >= 0);
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
}
References assert, Exception::errorMessage(), ObjectState::intAttribute(), latency_, ObjectState::name(), OSKEY_EXTENSION, OSKEY_LATENCY, OSNAME_IMMEDIATE_UNIT, OSVALUE_SIGN, OSVALUE_ZERO, setExtensionMode(), setLatency(), TTAMachine::Machine::SIGN, ObjectState::stringAttribute(), and TTAMachine::Machine::ZERO.
Referenced by ImmediateUnit(), and loadState().
saveState()
ObjectState * TTAMachine::ImmediateUnit::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::RegisterFile.
Definition at line 233 of file ImmediateUnit.cc.
{
    ObjectState* iUnit = RegisterFile::saveState();
    iUnit->setName(OSNAME_IMMEDIATE_UNIT);
    // set extension mode
    if (extension_ == Machine::SIGN) {
        iUnit->setAttribute(OSKEY_EXTENSION, OSVALUE_SIGN);
    } else {
        iUnit->setAttribute(OSKEY_EXTENSION, OSVALUE_ZERO);
    }
    iUnit->setAttribute(OSKEY_LATENCY, latency_);
    return iUnit;
}
References extension_, latency_, OSKEY_EXTENSION, OSKEY_LATENCY, OSNAME_IMMEDIATE_UNIT, OSVALUE_SIGN, OSVALUE_ZERO, TTAMachine::RegisterFile::saveState(), ObjectState::setAttribute(), ObjectState::setName(), and TTAMachine::Machine::SIGN.
setExtensionMode()
void TTAMachine::ImmediateUnit::setExtensionMode (Machine::Extension mode) virtual
Sets the extension mode for the immediate unit.
Parameters
mode The new extension mode.
Definition at line 185 of file ImmediateUnit.cc.
{
    extension_ = mode;
}
References extension_.
Referenced by loadStateWithoutReferences(), and IUDialog::onOK().
setLatency()
void TTAMachine::ImmediateUnit::setLatency (int latency) private virtual
Sets the latency of the immediate unit.
Parameters
latency The new latency.
Exceptions
OutOfRange If the given latency is less than zero.
Definition at line 197 of file ImmediateUnit.cc.
{
    if (latency != LATENCY) {
        string procName = "ImmediateUnit::setLatency";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    latency_ = latency;
}
References LATENCY, latency(), and latency_.
Referenced by loadStateWithoutReferences().
setMaxWrites()
void TTAMachine::ImmediateUnit::setMaxWrites (int maxWrites) virtual
Sets the maximum number of ports that can write a register all in the same cycle.
For immediate unit the value is fixed to 1.
Parameters
writes Maximum number of ports.
Exceptions
OutOfRange If the given number of maximum writes is out of range.
Reimplemented from TTAMachine::RegisterFile.
Definition at line 171 of file ImmediateUnit.cc.
{
    if (maxWrites != MAX_WRITES) {
        std::string procName = "ImmediateUnit::setMaxWrites";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    RegisterFile::setMaxWrites(maxWrites);
}
References MAX_WRITES, TTAMachine::RegisterFile::maxWrites(), and TTAMachine::RegisterFile::setMaxWrites().
setName()
void TTAMachine::ImmediateUnit::setName (const std::string & name) virtual
Sets the name of the immediate unit.
Parameters
name Name of the immediate unit.
Exceptions
ComponentAlreadyExists If an immediate unit with the given name is already in the same machine.
InvalidName If the given name is not a valid name for a component.
Reimplemented from TTAMachine::RegisterFile.
Definition at line 120 of file ImmediateUnit.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->immediateUnitNavigator().hasItem(name)) {
            string procName = "ImmediateUnit::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References machine, TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by IUDialog::onOK().
signExtends()
bool TTAMachine::ImmediateUnit::signExtends () const inline
Definition at line 62 of file ImmediateUnit.hh.
{ return extension_ == Machine::SIGN; }
References extension_, and TTAMachine::Machine::SIGN.
Referenced by ITemplateBroker::assign(), MachineConnectivityCheck::canWriteAllImmediates(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createImmediateAssignment(), TTAProgram::TPEFProgramFactory::createInstruction(), and CompiledSimCodeGenerator::generateInstruction().
unsetMachine()
void TTAMachine::ImmediateUnit::unsetMachine () virtual
Removes the immediate unit from machine.
Reimplemented from TTAMachine::RegisterFile.
Definition at line 209 of file ImmediateUnit.cc.
{
    Machine* mach = machine();
    if (mach == NULL) {
        return;
    }
    Machine::InstructionTemplateNavigator itNav =
        mach->instructionTemplateNavigator();
    Machine::BusNavigator busNav = mach->busNavigator();
    for (int itIndex = 0; itIndex < itNav.count(); itIndex++) {
        InstructionTemplate* it = itNav.item(itIndex);
        it->removeSlots(*this);
    }
    BaseRegisterFile::unsetMachine();
    mach->removeImmediateUnit(*this);
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, TTAMachine::Machine::removeImmediateUnit(), TTAMachine::InstructionTemplate::removeSlots(), and TTAMachine::Component::unsetMachine().
Referenced by ~ImmediateUnit().
zeroExtends()
bool TTAMachine::ImmediateUnit::zeroExtends () const inline
Definition at line 63 of file ImmediateUnit.hh.
{ return extension_ == Machine::ZERO; }
References extension_, and TTAMachine::Machine::ZERO.
Referenced by TTAProgram::TPEFProgramFactory::findInstrTemplate().
Member Data Documentation
extension_
Machine::Extension TTAMachine::ImmediateUnit::extension_ private
Extension mode applied to the long immediate when it is narrower than the immediate register.
Definition at line 93 of file ImmediateUnit.hh.
Referenced by extensionMode(), saveState(), setExtensionMode(), signExtends(), and zeroExtends().
latency_
int TTAMachine::ImmediateUnit::latency_ private
Minimum number of cycles needed between the encoding of a long immediate and its earliest transport on a data bus.
Definition at line 99 of file ImmediateUnit.hh.
Referenced by latency(), loadStateWithoutReferences(), saveState(), and setLatency().
OSKEY_EXTENSION
const string TTAMachine::ImmediateUnit::OSKEY_EXTENSION = "extension" static
ObjectState attribute key for the extension mode.
Definition at line 77 of file ImmediateUnit.hh.
Referenced by ADFSerializer::immediateUnitToMDF(), loadStateWithoutReferences(), saveState(), and ADFSerializer::setIUExtensionMode().
OSKEY_LATENCY
const string TTAMachine::ImmediateUnit::OSKEY_LATENCY = "latency" static
ObjectState attribute key for latency.
Definition at line 83 of file ImmediateUnit.hh.
Referenced by ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), loadStateWithoutReferences(), and saveState().
OSNAME_IMMEDIATE_UNIT
const string TTAMachine::ImmediateUnit::OSNAME_IMMEDIATE_UNIT static
Initial value:
=
    "immediate-unit"
ObjectState name for ImmediateUnit.
Definition at line 75 of file ImmediateUnit.hh.
Referenced by ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), ADFSerializer::immediateUnitToMachine(), TTAMachine::Machine::loadState(), loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), and saveState().
OSVALUE_SIGN
const string TTAMachine::ImmediateUnit::OSVALUE_SIGN = "sign" static
ObjectState attribute value for sign extension.
Definition at line 79 of file ImmediateUnit.hh.
Referenced by loadStateWithoutReferences(), saveState(), and ADFSerializer::setIUExtensionMode().
OSVALUE_ZERO
const string TTAMachine::ImmediateUnit::OSVALUE_ZERO = "zero" static
ObjectState attribute value for zero extension.
Definition at line 81 of file ImmediateUnit.hh.
Referenced by loadStateWithoutReferences(), saveState(), and ADFSerializer::setIUExtensionMode().
The documentation for this class was generated from the following files:
ImmediateUnit.hh
ImmediateUnit.cc