OpenASIP: Informer Class Reference
Informer Class Reference
#include <Informer.hh>
Public Member Functions
Informer ()
virtual ~Informer ()
void handleEvent (int event)
virtual bool registerListener (int event, Listener *listener)
virtual bool unregisterListener (int event, Listener *listener)
Private Types
typedef std::vector< std::pair< int, Listener * > > ListenerList
Private Member Functions
std::size_t findListenerSlot (int event, Listener *listener)
Private Attributes
ListenerList eventListeners_
Detailed Description
The Informer class delivers notifications of events (represented by integers) to Listeners.
A Listener can register to be notified of certain event(s) and will thereafter receive a notification every time the event takes place. Naturally, a Listener can also be unregistered to not receive any more notifications of the event.
Definition at line 52 of file Informer.hh.
Member Typedef Documentation
ListenerList
typedef std::vector<std::pair<int, Listener*> > Informer::ListenerList private
Definition at line 64 of file Informer.hh.
Constructor & Destructor Documentation
Informer()
Informer::Informer ()
Constructor.
Definition at line 44 of file Informer.cc.
                   {
}
~Informer()
Informer::~Informer () virtual
Destructor.
Definition at line 51 of file Informer.cc.
                    {
}
Member Function Documentation
findListenerSlot()
std::size_t Informer::findListenerSlot (int event, Listener * listener) inline private
Finds the event slot for the given listener listening to the given event.
In case the listener is not found, it's added to the list and index of it is returned.
Parameters
event Event the listener is listening to.
listener The listener.
Returns
The index of the event slot.
Definition at line 65 of file Informer.cc.
{
    for (std::size_t i = 0; i < eventListeners_.size(); ++i) {
        if (eventListeners_.at(i).first == event &&
            eventListeners_.at(i).second == listener) {
            return i;
        }
    }
    eventListeners_.push_back(std::make_pair(event, listener));
    return eventListeners_.size() - 1;
}
References eventListeners_.
Referenced by registerListener(), and unregisterListener().
handleEvent()
void Informer::handleEvent (int event)
Referenced by CompiledSimulation::cycleEnd(), TracedSimulatorFrontend::killSimulation(), TracedSimulatorFrontend::loadMachine(), TracedSimulatorFrontend::loadProgram(), CompiledSimController::next(), SimulationController::next(), TracedSimulatorFrontend::next(), MemoryProxy::read(), SimulatorFrontend::reportSimulatedProgramError(), CompiledSimController::run(), SimulationController::run(), TracedSimulatorFrontend::run(), CompiledSimController::runUntil(), SimulationController::runUntil(), TracedSimulatorFrontend::runUntil(), OTASimulationController::simulateCycle(), SimulationController::simulateCycle(), CompiledSimController::step(), SimulationController::step(), TracedSimulatorFrontend::step(), and MemoryProxy::write().
registerListener()
bool Informer::registerListener (int event, Listener * listener) virtual
Adds the given Listener to the list of listeners of the given event.
After this function has been called, the listener will be notified every time the event occurs.
Parameters
event The code identifying the event.
listener The Listener that should be added.
Returns
'True' if adding of the listener succeeds, 'false' otherwise.
Definition at line 87 of file Informer.cc.
{
    findListenerSlot(event, listener);
    return true;
}
References findListenerSlot().
Referenced by StopPointManager::add(), BusTracker::BusTracker(), BusTracker::BusTracker(), ExecutionTracker::ExecutionTracker(), ProximSimulationThread::initialize(), ProcedureTransferTracker::ProcedureTransferTracker(), ProcedureTransferTracker::ProcedureTransferTracker(), ProximRuntimeErrorHandler::ProximRuntimeErrorHandler(), SimpleSimulatorFrontend::registerEventListener(), RFAccessTracker::RFAccessTracker(), RuntimeErrorReporter::RuntimeErrorReporter(), and RFAccessTracker::~RFAccessTracker().
unregisterListener()
bool Informer::unregisterListener (int event, Listener * listener) virtual
Removes the given Listener from the list of listeners of the given event.
After this function has been called, the listener will not be notified that the event has occurred.
Parameters
event The code identifying the event.
listener The Listener that should be removed.
Returns
'True' if removing the listener succeeds, 'false' otherwise.
Definition at line 104 of file Informer.cc.
{
    std::size_t index = findListenerSlot(event, listener);
    ListenerList::iterator i = eventListeners_.begin() + index;
    eventListeners_.erase(i);
    return true;
}
References eventListeners_, and findListenerSlot().
Referenced by StopPointManager::deleteStopPoint(), SimpleSimulatorFrontend::unregisterEventListener(), BusTracker::~BusTracker(), ExecutionTracker::~ExecutionTracker(), ProcedureTransferTracker::~ProcedureTransferTracker(), ProximRuntimeErrorHandler::~ProximRuntimeErrorHandler(), RFAccessTracker::~RFAccessTracker(), and RuntimeErrorReporter::~RuntimeErrorReporter().
Member Data Documentation
eventListeners_
ListenerList Informer::eventListeners_ private
Definition at line 65 of file Informer.hh.
Referenced by findListenerSlot(), and unregisterListener().
The documentation for this class was generated from the following files:
Informer.hh
Informer.cc