OpenASIP: SimulatorToolbox Class Reference
SimulatorToolbox Class Reference
#include <SimulatorToolbox.hh>
Static Public Member Functions
static OperationPool & operationPool ()
static SimulatorTextGenerator & textGenerator ()
static boost::regex fuPortRegex ()
Protected Member Functions
SimulatorToolbox ()
Instantiation not allowed.
Private Member Functions
SimulatorToolbox (const SimulatorToolbox &)
Copying not allowed.
SimulatorToolbox & operator= (const SimulatorToolbox &)
Assignment not allowed.
Static Private Attributes
static OperationPool * pool_
Global instance of OperationPool.
static SimulatorTextGenerator textGenerator_
Global instance of SimulatorTextGenerator.
Detailed Description
Class that offers global services to Simulator classes.
Services provided by this utility class are provided as singleton instances. None of the returned data are simulation specific, thus the instances can be shared by multiple parallel simulations.
Definition at line 56 of file SimulatorToolbox.hh.
Constructor & Destructor Documentation
SimulatorToolbox() [1/2]
SimulatorToolbox::SimulatorToolbox () protected
Instantiation not allowed.
Constructor.
Definition at line 53 of file SimulatorToolbox.cc.
{
}
SimulatorToolbox() [2/2]
SimulatorToolbox::SimulatorToolbox (const SimulatorToolbox &) private
Copying not allowed.
Member Function Documentation
fuPortRegex()
boost::regex SimulatorToolbox::fuPortRegex () static
Returns a regular expression to parse a FU port string.
Returns
The regular expression.
Definition at line 85 of file SimulatorToolbox.cc.
{
    return boost::regex("(.*)\\.(.*)");
}
Referenced by SimulatorFrontend::state().
operationPool()
OperationPool & SimulatorToolbox::operationPool () static
Returns the instance of OperationPool.
Returns
The instance of OperationPool.
Definition at line 62 of file SimulatorToolbox.cc.
{
    if (pool_ == NULL) {
        pool_ = new OperationPool();
    }
    return *pool_;
}
References pool_.
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), MachineStateBuilder::bindPortsToOperands(), and MachineStateBuilder::buildMachineState().
operator=()
SimulatorToolbox & SimulatorToolbox::operator= (const SimulatorToolbox &) private
Assignment not allowed.
textGenerator()
SimulatorTextGenerator & SimulatorToolbox::textGenerator () static
Returns the instance of SimulatorTextGenerator.
Returns
The instance of SimulatorTextGenerator.
Definition at line 75 of file SimulatorToolbox.cc.
{
    return textGenerator_;
}
References textGenerator_.
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), MachineStateBuilder::bindPortsToOperands(), MachineStateBuilder::buildMachineState(), SimControlLanguageCommand::checkProgramLoaded(), SimControlLanguageCommand::checkSimulationEnded(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationNotAlreadyRunning(), SimControlLanguageCommand::checkSimulationStopped(), CompiledSimSettingCommand::CompiledSimSettingCommand(), ConditionCommand::execute(), ConfCommand::execute(), DeleteBPCommand::execute(), HelpCommand::execute(), IgnoreCommand::execute(), InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), InfoCommand::execute(), KillCommand::execute(), MachCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), ProgCommand::execute(), SettingCommand::execute(), BPCommand::helpText(), CommandsCommand::helpText(), ConditionCommand::helpText(), ConfCommand::helpText(), DeleteBPCommand::helpText(), DisableBPCommand::helpText(), DisassembleCommand::helpText(), EnableBPCommand::helpText(), HelpCommand::helpText(), IgnoreCommand::helpText(), InfoCommand::helpText(), KillCommand::helpText(), MachCommand::helpText(), MemDumpCommand::helpText(), MemWriteCommand::helpText(), NextiCommand::helpText(), ProgCommand::helpText(), QuitCommand::helpText(), ResumeCommand::helpText(), RunCommand::helpText(), SettingCommand::helpText(), StepiCommand::helpText(), TBPCommand::helpText(), UntilCommand::helpText(), WatchCommand::helpText(), SimulatorFrontend::initializeDataMemories(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadProcessorConfiguration(), SimulatorFrontend::loadProgram(), main(), SimControlLanguageCommand::parseBreakpoint(), SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimControlLanguageCommand::printBreakpointInfo(), SimulatorCmdLineOptions::printHelp(), SimControlLanguageCommand::printStopReasons(), SimProgramBuilder::processBidirTerminal(), SimProgramBuilder::processInstruction(), SimProgramBuilder::processMove(), SimProgramBuilder::processSourceTerminal(), SimControlLanguageCommand::setMemoryPointer(), SettingCommand::SettingCommand(), SimulatorFrontend::SimulatorFrontend(), and SimControlLanguageCommand::verifyBreakpointHandles().
Member Data Documentation
pool_
POP_CLANG_DIAGS OperationPool * SimulatorToolbox::pool_ static private
Global instance of OperationPool.
Definition at line 75 of file SimulatorToolbox.hh.
Referenced by operationPool().
textGenerator_
SimulatorTextGenerator SimulatorToolbox::textGenerator_ static private
Global instance of SimulatorTextGenerator.
Definition at line 77 of file SimulatorToolbox.hh.
Referenced by textGenerator().
The documentation for this class was generated from the following files:
SimulatorToolbox.hh
SimulatorToolbox.cc