OpenASIP: InfoIunitsCommand Class Reference
InfoIunitsCommand Class Reference
Public Member Functions
InfoIunitsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoIunitsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info iunits".
Definition at line 359 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoIunitsCommand()
InfoIunitsCommand::InfoIunitsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 364 of file InfoCommand.cc.
                                                                :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoIunitsCommand()
virtual InfoIunitsCommand::~InfoIunitsCommand () inline virtual
Destructor.
Definition at line 371 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoIunitsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info iunits" command.
"info iunits" prints the names of all the immediate units in the machine.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 383 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 0, 0)) {
            return false;
        }
        if (!parent().checkMachineLoaded()) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        const TTAMachine::Machine::ImmediateUnitNavigator& nav =
            mach.immediateUnitNavigator();
        std::string result = "";
        bool isFirst = true;
        for (int i = 0; i < nav.count(); ++i) {
            if (!isFirst)
                result += "\n";
            result += nav.item(i)->name();
            isFirst = false;
        }
        parent().interpreter()->setResult(result);
        return true;
    }
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateUnitNavigator(), CustomCommand::interpreter(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), SimControlLanguageSubCommand::parent(), ScriptInterpreter::setResult(), and SimControlLanguageCommand::simulatorFrontend().
The documentation for this class was generated from the following file:
InfoCommand.cc