OpenASIP: SimulationInfoDialog Class Reference
SimulationInfoDialog Class Reference
#include <SimulationInfoDialog.hh>
Public Member Functions
SimulationInfoDialog (wxWindow *parent, OperationContext *context)
virtual ~SimulationInfoDialog ()
virtual void handleEvent (OSEdInformer::EventId id)
Public Member Functions inherited from OSEdListener
OSEdListener ()
virtual ~OSEdListener ()
Private Types
enum { ID_LISTCTRL }
Private Member Functions
SimulationInfoDialog (const SimulationInfoDialog &)
Copying not allowed.
SimulationInfoDialog & operator= (const SimulationInfoDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void setTexts ()
void updateList ()
Private Attributes
wxListCtrl * infoList_
List for showing simulation statistics.
SimulateDialog * parent_
Parent window.
OperationContext * context_
Operation context for retrieving simulation data.
Detailed Description
Dialog that holds additional information about simulation.
Definition at line 48 of file SimulationInfoDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_LISTCTRL
Definition at line 69 of file SimulationInfoDialog.hh.
         {
        ID_LISTCTRL
    };
Constructor & Destructor Documentation
SimulationInfoDialog() [1/2]
SimulationInfoDialog::SimulationInfoDialog (wxWindow * parent, OperationContext * context)
Constructor.
Parameters
parent Parent window.
context Operation context.
Definition at line 55 of file SimulationInfoDialog.cc.
                               :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_SIMULATION_INFO),
             wxSize(400, 150), wxRESIZE_BORDER), context_(context) {
    createContents(this, false, true);
    parent_ = dynamic_cast<SimulateDialog*>(parent);
    infoList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LISTCTRL));
    infoList_->InsertColumn(0, _T(""), wxLIST_FORMAT_LEFT,
                           OSEdConstants::DEFAULT_COLUMN_WIDTH);
    infoList_->InsertColumn(1, _T(""), wxLIST_FORMAT_LEFT,
                           OSEdConstants::DEFAULT_COLUMN_WIDTH);
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_LABEL_PC);
    infoList_->InsertItem(0, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_LABEL_RA);
    infoList_->InsertItem(1, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_LABEL_SYS_CALL_HANDLER);
    infoList_->InsertItem(2, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_LABEL_SYS_CALL_NUMBER);
    infoList_->InsertItem(3, WxConversion::toWxString(fmt.str()));
    setTexts();
}
References createContents(), OSEdConstants::DEFAULT_COLUMN_WIDTH, ID_LISTCTRL, infoList_, OSEdTextGenerator::instance(), parent_, setTexts(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_LABEL_PC, OSEdTextGenerator::TXT_LABEL_RA, OSEdTextGenerator::TXT_LABEL_SYS_CALL_HANDLER, and OSEdTextGenerator::TXT_LABEL_SYS_CALL_NUMBER.
~SimulationInfoDialog()
SimulationInfoDialog::~SimulationInfoDialog () virtual
Destructor.
Definition at line 108 of file SimulationInfoDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_SIMULATION_INFO, point);
}
References DialogPosition::DIALOG_SIMULATION_INFO, and DialogPosition::setPosition().
SimulationInfoDialog() [2/2]
SimulationInfoDialog::SimulationInfoDialog (const SimulationInfoDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * SimulationInfoDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
NOTE! This function was generated by wxDesigner.
Parameters
parent Parent window.
call_fit If true fits the contenst inside the dialog.
set_sizer If true sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 192 of file SimulationInfoDialog.cc.
                     {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_LISTCTRL, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxLC_NO_HEADER|wxSUNKEN_BORDER );
    item0->Add( item1, 1, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_LISTCTRL.
Referenced by SimulationInfoDialog().
handleEvent()
void SimulationInfoDialog::handleEvent (OSEdInformer::EventId id) virtual
Updates the list which contains information about simulation.
This method is called when trigger button is pushed in parent dialog (SimulateDialog).
Parameters
id The id of the event.
Implements OSEdListener.
Definition at line 166 of file SimulationInfoDialog.cc.
{
    switch (id) {
    case OSEdInformer::EVENT_REGISTER:
        updateList();
        break;
    case OSEdInformer::EVENT_RESET:
        context_->programCounter() = 0;
        context_->returnAddress() = 0;
        updateList();
        break;
    default:
        break;
    }
}
References context_, OSEdInformer::EVENT_REGISTER, OSEdInformer::EVENT_RESET, OperationContext::programCounter(), OperationContext::returnAddress(), and updateList().
operator=()
SimulationInfoDialog & SimulationInfoDialog::operator= (const SimulationInfoDialog &) private
Assignment not allowed.
setTexts()
void SimulationInfoDialog::setTexts () private
Sets the texts for the widgets.
Definition at line 93 of file SimulationInfoDialog.cc.
{
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt =
        osedText.text(OSEdTextGenerator::TXT_SIMULATION_INFO_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
}
References OSEdTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), and OSEdTextGenerator::TXT_SIMULATION_INFO_DIALOG_TITLE.
Referenced by SimulationInfoDialog().
TransferDataToWindow()
bool SimulationInfoDialog::TransferDataToWindow () private virtual
Transfer data to dialog.
Returns
True if transfer is successful.
Definition at line 121 of file SimulationInfoDialog.cc.
{
    updateList();
    return wxWindow::TransferDataToWindow();
}
References updateList().
updateList()
void SimulationInfoDialog::updateList () private
Updates the list of information.
Definition at line 130 of file SimulationInfoDialog.cc.
{
#if 0
    if (&context_->programCounter() == &NullSimValue::instance()) {
        infoList_->SetItem(0, 1, WxConversion::toWxString(0));
    } else {
        SimValue& value = context_->programCounter();
        string valueString = parent_->formattedValue(&value);
        infoList_->SetItem(0, 1, WxConversion::toWxString(valueString));
    }
#endif
    infoList_->SetItem(
        0, 1, WxConversion::toWxString(context_->programCounter()));
#if 0
    if (&context_->returnAddress() == &NullSimValue::instance()) {
        infoList_->SetItem(1, 1, WxConversion::toWxString(0));
    } else {
        SimValue& value = context_->returnAddress();
        string valueString = parent_->formattedValue(&value);
        infoList_->SetItem(1, 1, WxConversion::toWxString(valueString));
    }
#endif
    infoList_->SetItem(
        1, 1,
        WxConversion::toWxString(context_->returnAddress().uIntWordValue()));
}
References context_, SimulateDialog::formattedValue(), infoList_, NullSimValue::instance(), parent_, OperationContext::programCounter(), OperationContext::returnAddress(), WxConversion::toWxString(), and SimValue::uIntWordValue().
Referenced by handleEvent(), and TransferDataToWindow().
Member Data Documentation
context_
OperationContext* SimulationInfoDialog::context_ private
Operation context for retrieving simulation data.
Definition at line 78 of file SimulationInfoDialog.hh.
Referenced by handleEvent(), and updateList().
infoList_
wxListCtrl* SimulationInfoDialog::infoList_ private
List for showing simulation statistics.
Definition at line 74 of file SimulationInfoDialog.hh.
Referenced by SimulationInfoDialog(), and updateList().
parent_
SimulateDialog* SimulationInfoDialog::parent_ private
Parent window.
Definition at line 76 of file SimulationInfoDialog.hh.
Referenced by SimulationInfoDialog(), and updateList().
The documentation for this class was generated from the following files:
SimulationInfoDialog.hh
SimulationInfoDialog.cc