OpenASIP: SocketBusConnToolFigure Class Reference
SocketBusConnToolFigure Class Reference
#include <SocketBusConnToolFigure.hh>
Public Member Functions
SocketBusConnToolFigure (bool creating)
virtual ~SocketBusConnToolFigure ()
Public Member Functions inherited from SocketBusConnFigure
SocketBusConnFigure ()
virtual ~SocketBusConnFigure ()
Public Member Functions inherited from ConnectionFigure
virtual ~ConnectionFigure ()
void setSource (Figure *figure)
void setTarget (Figure *figure)
Figure * source () const
Figure * target () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from SocketBusConnFigure
virtual void drawConnection (wxDC *dc)
virtual void layoutSelf (wxDC *dc)
Protected Member Functions inherited from ConnectionFigure
ConnectionFigure ()
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutChildren (wxDC *)
Private Member Functions
SocketBusConnToolFigure & operator= (SocketBusConnToolFigure &old)
Assignment not allowed.
SocketBusConnToolFigure (SocketBusConnToolFigure &old)
Copying not allowed.
Private Attributes
wxColor color_
Current color of the connection figure.
Static Private Attributes
static const wxColor LINE_COLOR_RED = wxColor(255, 0, 0)
Figure color for connections being removed.
static const wxColor LINE_COLOR_GREEN = wxColor(0, 200, 0)
Figure color for connections being removed.
Additional Inherited Members
Protected Attributes inherited from ConnectionFigure
Figure * source_
Source of connection.
Figure * target_
Target of connection.
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a socket-to-bus connection for the connection tool.
Definition at line 45 of file SocketBusConnToolFigure.hh.
Constructor & Destructor Documentation
SocketBusConnToolFigure() [1/2]
SocketBusConnToolFigure::SocketBusConnToolFigure (bool creating)
The Constructor.
Definition at line 43 of file SocketBusConnToolFigure.cc.
                                                             :
    SocketBusConnFigure() {
    if (creating) {
        color_ = LINE_COLOR_GREEN;
    } else {
        color_ = LINE_COLOR_RED;
    }
}
References color_, LINE_COLOR_GREEN, and LINE_COLOR_RED.
~SocketBusConnToolFigure()
SocketBusConnToolFigure::~SocketBusConnToolFigure () virtual
The Destructor.
Definition at line 56 of file SocketBusConnToolFigure.cc.
{
}
SocketBusConnToolFigure() [2/2]
SocketBusConnToolFigure::SocketBusConnToolFigure (SocketBusConnToolFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void SocketBusConnToolFigure::drawSelf (wxDC * dc) protected virtual
Draws the connection's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from SocketBusConnFigure.
Definition at line 65 of file SocketBusConnToolFigure.cc.
{
    assert(source_ != NULL && target_ != NULL);
    wxPen pen = wxPen(color_, 1, wxSOLID);
    wxBrush brush = wxBrush(color_, wxSOLID);
    dc->SetPen(pen);
    dc->SetBrush(brush);
    drawConnection(dc);
}
References assert, color_, SocketBusConnFigure::drawConnection(), ConnectionFigure::source_, and ConnectionFigure::target_.
operator=()
SocketBusConnToolFigure & SocketBusConnToolFigure::operator= (SocketBusConnToolFigure & old) private
Assignment not allowed.
Member Data Documentation
color_
wxColor SocketBusConnToolFigure::color_ private
Current color of the connection figure.
Definition at line 65 of file SocketBusConnToolFigure.hh.
Referenced by drawSelf(), and SocketBusConnToolFigure().
LINE_COLOR_GREEN
const wxColor SocketBusConnToolFigure::LINE_COLOR_GREEN = wxColor(0, 200, 0) static private
Figure color for connections being removed.
Definition at line 62 of file SocketBusConnToolFigure.hh.
Referenced by SocketBusConnToolFigure().
LINE_COLOR_RED
const wxColor SocketBusConnToolFigure::LINE_COLOR_RED = wxColor(255, 0, 0) static private
Figure color for connections being removed.
Definition at line 60 of file SocketBusConnToolFigure.hh.
Referenced by SocketBusConnToolFigure().
The documentation for this class was generated from the following files:
SocketBusConnToolFigure.hh
SocketBusConnToolFigure.cc