OpenASIP: RFDialog Class Reference
RFDialog Class Reference
#include <RFDialog.hh>
Public Member Functions
RFDialog (wxWindow *parent, TTAMachine::RegisterFile *registerFile)
virtual ~RFDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_TYPE , ID_SIZE , ID_WIDTH ,
ID_MAX_READS , ID_MAX_WRITES , ID_GUARD_LATENCY , ID_PORT_LIST ,
ID_ADD_PORT , ID_EDIT_PORT , ID_DELETE_PORT , ID_HELP ,
ID_LABEL_NAME , ID_LABEL_SIZE , ID_LABEL_WIDTH , ID_LABEL_TYPE ,
ID_LABEL_MAX_READS , ID_LABEL_MAX_WRITES , ID_LABEL_GUARD_LATENCY , ID_ZERO_REGISTER
}
enumerated IDs for the dialog controls
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
TTAMachine::Port * selectedPort () const
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void onPortSelection (wxListEvent &event)
void onPortRightClick (wxListEvent &event)
void onAddPort (wxCommandEvent &event)
void onActivatePort (wxListEvent &event)
void onEditPort (wxCommandEvent &event)
void onDeletePort (wxCommandEvent &event)
void updateWidgets ()
void updatePortList ()
void setTexts ()
Private Attributes
wxStaticBoxSizer * portsSizer_
Sizer containing the port list and associated buttons.
TTAMachine::RegisterFile * registerFile_
Register file to modify.
wxString name_
Name of the register file.
int size_
Number of registers.
int width_
Width.
int maxReads_
Max reads.
int maxWrites_
Maximum writes.
int guardLatency_
Guard latency.
bool zeroRegister_
Zero register.
wxListCtrl * portListCtrl_
Port list control.
wxChoice * typeChoice_
Opcode choice control.
Detailed Description
Dialog for editing register file parameters.
Definition at line 47 of file RFDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for the dialog controls
Enumerator
ID_NAME
ID_TYPE
ID_SIZE
ID_WIDTH
ID_MAX_READS
ID_MAX_WRITES
ID_GUARD_LATENCY
ID_PORT_LIST
ID_ADD_PORT
ID_EDIT_PORT
ID_DELETE_PORT
ID_HELP
ID_LABEL_NAME
ID_LABEL_SIZE
ID_LABEL_WIDTH
ID_LABEL_TYPE
ID_LABEL_MAX_READS
ID_LABEL_MAX_WRITES
ID_LABEL_GUARD_LATENCY
ID_ZERO_REGISTER
Definition at line 95 of file RFDialog.hh.
         {
        ID_NAME = 10000,
        ID_TYPE,
        ID_SIZE,
        ID_WIDTH,
        ID_MAX_READS,
        ID_MAX_WRITES,
        ID_GUARD_LATENCY,
        ID_PORT_LIST,
        ID_ADD_PORT,
        ID_EDIT_PORT,
        ID_DELETE_PORT,
        ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_SIZE,
        ID_LABEL_WIDTH,
        ID_LABEL_TYPE,
        ID_LABEL_MAX_READS,
        ID_LABEL_MAX_WRITES,
        ID_LABEL_GUARD_LATENCY,
        ID_ZERO_REGISTER
    };
Constructor & Destructor Documentation
RFDialog()
RFDialog::RFDialog (wxWindow * parent, TTAMachine::RegisterFile * registerFile)
The Constructor.
Parameters
parent Parent window of the dialog.
registerFile Register file to add/edit.
Definition at line 82 of file RFDialog.cc.
                               :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    registerFile_(registerFile),
    name_(_T("")),
    size_(1),
    width_(ModelConstants::DEFAULT_WIDTH),
    maxReads_(0),
    maxWrites_(0),
    zeroRegister_(false),
    portListCtrl_(NULL),
    typeChoice_(NULL) {
    //registerFile_->updateMaxReadsAndWrites();
    createContents(this, true, true);
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_EDIT_PORT)->Disable();
    FindWindow(ID_DELETE_PORT)->Disable();
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    portListCtrl_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    typeChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_TYPE));
    // Set widget validators.
    FindWindow(ID_WIDTH)->SetValidator(wxGenericValidator(&width_));
    FindWindow(ID_SIZE)->SetValidator(wxGenericValidator(&size_));
    FindWindow(ID_GUARD_LATENCY)->SetValidator(
        wxGenericValidator(&guardLatency_));
    FindWindow(ID_ZERO_REGISTER)->SetValidator(
        wxGenericValidator(&zeroRegister_));
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
~RFDialog()
RFDialog::~RFDialog () virtual
The Destructor.
Definition at line 127 of file RFDialog.cc.
                    {
}
Member Function Documentation
createContents()
wxSizer * RFDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 536 of file RFDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_TYPE, wxT("Type:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_TYPE, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_SIZE, wxT("Size:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item7 = new wxSpinCtrl( parent, ID_SIZE, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item1->Add( item7, 0, wxGROW|wxALL, 5 );
    wxStaticText *item8 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item8, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item9 = new wxSpinCtrl( parent, ID_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item1->Add( item9, 0, wxGROW|wxALL, 5 );
    wxStaticText *item10 = new wxStaticText( parent, ID_LABEL_MAX_READS, wxT("Max-Reads:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item10, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_MAX_READS, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0);
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    wxStaticText *item12 = new wxStaticText( parent, ID_LABEL_MAX_WRITES, wxT("Max-Writes:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item12, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxStaticText *item13 = new wxStaticText( parent, ID_MAX_WRITES, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0);
    item1->Add( item13, 0, wxGROW|wxALL, 5 );
    wxStaticText *item14 = new wxStaticText( parent, ID_LABEL_GUARD_LATENCY, wxT("Guard Latency:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item14, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item15 = new wxSpinCtrl( parent, ID_GUARD_LATENCY, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 1, 0 );
    item1->Add( item15, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item17 = new wxStaticBox( parent, -1, wxT("Ports:") );
    wxStaticBoxSizer *item16 = new wxStaticBoxSizer( item17, wxVERTICAL );
    portsSizer_ = item16;
    wxListCtrl *item18 = new wxListCtrl( parent, ID_PORT_LIST, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item16->Add( item18, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item20 = new wxButton( parent, ID_ADD_PORT, wxT("&Add.."), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item21 = new wxButton( parent, ID_EDIT_PORT, wxT("&Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item22 = new wxButton( parent, ID_DELETE_PORT, wxT("&Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    item16->Add( item19, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT, 5 );
    item0->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item24 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item25 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item26 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    wxCheckBox *item27 = new wxCheckBox( parent, ID_ZERO_REGISTER, wxT("Zero register"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add( item27, 0, wxALIGN_CENTER_VERTICAL|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_PORT, ID_DELETE_PORT, ID_EDIT_PORT, ID_GUARD_LATENCY, ID_HELP, ID_LABEL_GUARD_LATENCY, ID_LABEL_MAX_READS, ID_LABEL_MAX_WRITES, ID_LABEL_NAME, ID_LABEL_SIZE, ID_LABEL_TYPE, ID_LABEL_WIDTH, ID_MAX_READS, ID_MAX_WRITES, ID_NAME, ID_PORT_LIST, ID_SIZE, ID_TYPE, ID_WIDTH, ID_ZERO_REGISTER, and portsSizer_.
onActivatePort()
void RFDialog::onActivatePort (wxListEvent & event) private
Handles left mouse button double clicks on the port list.
Definition at line 455 of file RFDialog.cc.
{
    wxCommandEvent dummy;
    onEditPort(dummy);
}
References dummy, and onEditPort().
onAddPort()
void RFDialog::onAddPort (wxCommandEvent & event) private
Creates and shows an empty RFPortDialog for adding ports.
Definition at line 412 of file RFDialog.cc.
{
    // Generate name for the new port.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
        Conversion::toString(i);
    while (registerFile_->hasPort(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
            Conversion::toString(i);
        i++;
    }
    RFPort* port = new RFPort(newName, *registerFile_);
    RFPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_OK) {
        updatePortList();
    } else {
        delete port;
    }
    updateWidgets();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_PORT, TTAMachine::Unit::hasPort(), registerFile_, Conversion::toString(), updatePortList(), and updateWidgets().
onDeletePort()
void RFDialog::onDeletePort (wxCommandEvent & event) private
Deletes selected port from the port list.
Definition at line 441 of file RFDialog.cc.
{
    Port* selected = selectedPort();
    assert(selected != NULL);
    delete selected;
    updatePortList();
    updateWidgets();
}
References assert, selectedPort(), updatePortList(), and updateWidgets().
onEditPort()
void RFDialog::onEditPort (wxCommandEvent & event) private
Handles the 'Edit Port' button event.
Opens a RFPortDialog with the selected port's attributes set.
Definition at line 467 of file RFDialog.cc.
{
    Port* port = selectedPort();
    if (port == NULL) {
        // No port selected.
        return;
    }
    RFPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_OK) {
        updatePortList();
    }
}
References selectedPort(), and updatePortList().
Referenced by onActivatePort().
onHelp()
void RFDialog::onHelp (wxCommandEvent & event) private
onName()
void RFDialog::onName (wxCommandEvent & event) private
Checks whether name field is empty and disables OK button of the dialog if it is.
Definition at line 373 of file RFDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void RFDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the RegisterFile.
Definition at line 285 of file RFDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (registerFile_->name() != trimmedName) {
        Machine::RegisterFileNavigator navigator =
            registerFile_->machine()->registerFileNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            RegisterFile* rf = navigator.item(i);
            if (trimmedName == rf->name()) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_rf =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_REGISTER_FILE);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format rf =
                    prodeTexts->text(ProDeTextGenerator::COMP_REGISTER_FILE);
                message % trimmedName % a_rf.str() % machine.str() % rf.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    try {
        registerFile_->setName(trimmedName);
        registerFile_->setWidth(width_);
        registerFile_->setNumberOfRegisters(size_);
        registerFile_->setGuardLatency(guardLatency_);
        registerFile_->setZeroRegister(zeroRegister_);
    } catch (Exception& e) {
        InformationDialog dialog(
            this, WxConversion::toWxString(e.errorMessage()));
        dialog.ShowModal();
        return;
    }
    // set register file type
    switch (typeChoice_->GetSelection()) {
    case 0:
        registerFile_->setType(RegisterFile::NORMAL);
        break;
    case 1:
        registerFile_->setType(RegisterFile::RESERVED);
        break;
    case 2:
        registerFile_->setType(RegisterFile::VOLATILE);
        break;
    default:
        assert(false);
    }
    //registerFile_->updateMaxReadsAndWrites();
    EndModal(wxID_OK);
}
References assert, ProDeTextGenerator::COMP_A_REGISTER_FILE, ProDeTextGenerator::COMP_MACHINE, ProDeTextGenerator::COMP_REGISTER_FILE, TTAMachine::Machine::Navigator< ComponentType >::count(), Exception::errorMessage(), guardLatency_, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::RegisterFile::NORMAL, registerFile_, TTAMachine::Machine::registerFileNavigator(), TTAMachine::RegisterFile::RESERVED, TTAMachine::RegisterFile::setGuardLatency(), TTAMachine::RegisterFile::setName(), TTAMachine::RegisterFile::setNumberOfRegisters(), TTAMachine::RegisterFile::setType(), TTAMachine::BaseRegisterFile::setWidth(), TTAMachine::RegisterFile::setZeroRegister(), size_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), typeChoice_, TTAMachine::RegisterFile::VOLATILE, width_, and zeroRegister_.
onPortRightClick()
void RFDialog::onPortRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed.
Parameters
event Information about right mouse click event.
Definition at line 505 of file RFDialog.cc.
{
    portListCtrl_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_PORT, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_PORT, WxConversion::toWxString(button.str()));
    portListCtrl_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_PORT, ID_EDIT_PORT, ProDeTextGenerator::instance(), portListCtrl_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onPortSelection()
void RFDialog::onPortSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the port list.
If a port is selected, buttons are enabled. If no port is selected the buttons will be disabled.
Definition at line 488 of file RFDialog.cc.
{
    if (portListCtrl_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_PORT)->Disable();
        FindWindow(ID_EDIT_PORT)->Disable();
        return;
    }
    FindWindow(ID_DELETE_PORT)->Enable();
    FindWindow(ID_EDIT_PORT)->Enable();
}
References ID_DELETE_PORT, ID_EDIT_PORT, and portListCtrl_.
selectedPort()
Port * RFDialog::selectedPort () const private
Returns pointer to the port which is selected on the port list.
Returns
Pointer to the port which is selected on the port list.
Definition at line 392 of file RFDialog.cc.
{
    long item = -1;
    item = portListCtrl_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    string portName =
        WxConversion::toString(portListCtrl_->GetItemText(item));
    return registerFile_->port(portName);
}
References TTAMachine::BaseRegisterFile::port(), portListCtrl_, registerFile_, and WxConversion::toString().
Referenced by onDeletePort(), and onEditPort().
setTexts()
void RFDialog::setTexts () private
Sets texts for widgets.
Definition at line 135 of file RFDialog.cc.
                   {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_RF_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_PORT),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_PORT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_PORT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_TYPE),
                          ProDeTextGenerator::TXT_LABEL_TYPE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_SIZE),
                          ProDeTextGenerator::TXT_LABEL_SIZE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_MAX_READS),
                          ProDeTextGenerator::TXT_LABEL_MAX_READS);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_MAX_WRITES),
                          ProDeTextGenerator::TXT_LABEL_MAX_WRITES);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_GUARD_LATENCY),
                          ProDeTextGenerator::TXT_LABEL_GUARD_LATENCY);
    // choicer texts
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RF_TYPE_NORMAL);
    typeChoice_->Append(WxConversion::toWxString(fmt.str()));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RF_TYPE_RESERVED);
    typeChoice_->Append(WxConversion::toWxString(fmt.str()));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RF_TYPE_VOLATILE);
    typeChoice_->Append(WxConversion::toWxString(fmt.str()));
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RF_PORTS_BOX);
    WidgetTools::setWidgetLabel(portsSizer_, fmt.str());
    // Create port list column.
    wxListCtrl* portList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    portList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 200);
}
References ID_ADD_PORT, ID_DELETE_PORT, ID_EDIT_PORT, ID_HELP, ID_LABEL_GUARD_LATENCY, ID_LABEL_MAX_READS, ID_LABEL_MAX_WRITES, ID_LABEL_NAME, ID_LABEL_SIZE, ID_LABEL_TYPE, ID_LABEL_WIDTH, ID_PORT_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), portsSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_LABEL_GUARD_LATENCY, ProDeTextGenerator::TXT_LABEL_MAX_READS, ProDeTextGenerator::TXT_LABEL_MAX_WRITES, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_SIZE, ProDeTextGenerator::TXT_LABEL_TYPE, ProDeTextGenerator::TXT_LABEL_WIDTH, ProDeTextGenerator::TXT_RF_DIALOG_TITLE, ProDeTextGenerator::TXT_RF_PORTS_BOX, ProDeTextGenerator::TXT_RF_TYPE_NORMAL, ProDeTextGenerator::TXT_RF_TYPE_RESERVED, ProDeTextGenerator::TXT_RF_TYPE_VOLATILE, and typeChoice_.
TransferDataToWindow()
bool RFDialog::TransferDataToWindow () private virtual
Transfers data from the RegisterFile object to the dialog widgets.
Returns
false, if an error occured in the transfer.
Definition at line 210 of file RFDialog.cc.
{
    updateWidgets();
    return wxWindow::TransferDataToWindow();
}
References updateWidgets().
updatePortList()
void RFDialog::updatePortList () private
Updates the port list widget.
Definition at line 269 of file RFDialog.cc.
{
    portListCtrl_->DeleteAllItems();
    for (int i=0; i < registerFile_->portCount(); i++) {
        wxString name =
            WxConversion::toWxString(registerFile_->port(i)->name());
        portListCtrl_->InsertItem(i, name);
    }
}
References TTAMachine::Port::name(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), portListCtrl_, registerFile_, and WxConversion::toWxString().
Referenced by onAddPort(), onDeletePort(), onEditPort(), and updateWidgets().
updateWidgets()
void RFDialog::updateWidgets () private
Reads data form the RegisterFile and updates GUI.
Definition at line 223 of file RFDialog.cc.
{
    //registerFile_->updateMaxReadsAndWrites();
    name_ = WxConversion::toWxString(registerFile_->name());
    size_ = registerFile_->numberOfRegisters();
    width_ = registerFile_->width();
    maxReads_ = registerFile_->maxReads();
    maxWrites_ = registerFile_->maxWrites();
    guardLatency_ = registerFile_->guardLatency();
    zeroRegister_ = registerFile_->zeroRegister();
    switch (registerFile_->type()) {
    case RegisterFile::NORMAL:
        typeChoice_->SetSelection(0);
        break;
    case RegisterFile::RESERVED:
        typeChoice_->SetSelection(1);
        break;
    case RegisterFile::VOLATILE:
        typeChoice_->SetSelection(2);
        break;
    default:
        assert(false);
    }
    updatePortList();
    // wxWidgets GTK1 version seems to bug with spincontrol validators.
    // The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_SIZE))->SetValue(size_);
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_WIDTH))->SetValue(width_);
    dynamic_cast<wxStaticText*>(FindWindow(ID_MAX_READS))->SetLabel(
            WxConversion::toWxString(maxReads_));
    dynamic_cast<wxStaticText*>(FindWindow(ID_MAX_WRITES))->SetLabel(
            WxConversion::toWxString(maxWrites_));
    dynamic_cast<wxSpinCtrl*>(
        FindWindow(ID_GUARD_LATENCY))->SetValue(guardLatency_);
    dynamic_cast<wxCheckBox*>(
    FindWindow(ID_ZERO_REGISTER))->SetValue(zeroRegister_);
}
References assert, TTAMachine::RegisterFile::guardLatency(), guardLatency_, ID_GUARD_LATENCY, ID_MAX_READS, ID_MAX_WRITES, ID_SIZE, ID_WIDTH, ID_ZERO_REGISTER, TTAMachine::RegisterFile::maxReads(), maxReads_, TTAMachine::RegisterFile::maxWrites(), maxWrites_, TTAMachine::Component::name(), name_, TTAMachine::RegisterFile::NORMAL, TTAMachine::BaseRegisterFile::numberOfRegisters(), registerFile_, TTAMachine::RegisterFile::RESERVED, size_, WxConversion::toWxString(), TTAMachine::RegisterFile::type(), typeChoice_, updatePortList(), TTAMachine::RegisterFile::VOLATILE, TTAMachine::BaseRegisterFile::width(), width_, TTAMachine::RegisterFile::zeroRegister(), and zeroRegister_.
Referenced by onAddPort(), onDeletePort(), and TransferDataToWindow().
Member Data Documentation
guardLatency_
int RFDialog::guardLatency_ private
Guard latency.
Definition at line 85 of file RFDialog.hh.
Referenced by onOK(), and updateWidgets().
maxReads_
int RFDialog::maxReads_ private
Max reads.
Definition at line 81 of file RFDialog.hh.
Referenced by updateWidgets().
maxWrites_
int RFDialog::maxWrites_ private
Maximum writes.
Definition at line 83 of file RFDialog.hh.
Referenced by updateWidgets().
name_
wxString RFDialog::name_ private
Name of the register file.
Definition at line 75 of file RFDialog.hh.
Referenced by onName(), onOK(), and updateWidgets().
portListCtrl_
wxListCtrl* RFDialog::portListCtrl_ private
Port list control.
Definition at line 90 of file RFDialog.hh.
Referenced by onPortRightClick(), onPortSelection(), selectedPort(), and updatePortList().
portsSizer_
wxStaticBoxSizer* RFDialog::portsSizer_ private
Sizer containing the port list and associated buttons.
Definition at line 70 of file RFDialog.hh.
Referenced by createContents(), and setTexts().
registerFile_
TTAMachine::RegisterFile* RFDialog::registerFile_ private
Register file to modify.
Definition at line 73 of file RFDialog.hh.
Referenced by onAddPort(), onOK(), selectedPort(), updatePortList(), and updateWidgets().
size_
int RFDialog::size_ private
Number of registers.
Definition at line 77 of file RFDialog.hh.
Referenced by onOK(), and updateWidgets().
typeChoice_
wxChoice* RFDialog::typeChoice_ private
Opcode choice control.
Definition at line 92 of file RFDialog.hh.
Referenced by onOK(), setTexts(), and updateWidgets().
width_
int RFDialog::width_ private
Width.
Definition at line 79 of file RFDialog.hh.
Referenced by onOK(), and updateWidgets().
zeroRegister_
bool RFDialog::zeroRegister_ private
Zero register.
Definition at line 87 of file RFDialog.hh.
Referenced by onOK(), and updateWidgets().
The documentation for this class was generated from the following files:
RFDialog.hh
RFDialog.cc