OpenASIP: HighlightTopExecCountsCmd Class Reference
HighlightTopExecCountsCmd Class Reference
#include <HighlightTopExecCountsCmd.hh>
Public Member Functions
HighlightTopExecCountsCmd ()
virtual ~HighlightTopExecCountsCmd ()
virtual bool Do ()
virtual int id () const
virtual HighlightTopExecCountsCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for highlighting instructions with top execution counts in the disassembly window.
Definition at line 42 of file HighlightTopExecCountsCmd.hh.
Constructor & Destructor Documentation
HighlightTopExecCountsCmd()
HighlightTopExecCountsCmd::HighlightTopExecCountsCmd ()
The Constructor.
Definition at line 44 of file HighlightTopExecCountsCmd.cc.
                                                    :
    GUICommand("Highlight Top Execution Counts", NULL) {
    }
Referenced by create().
~HighlightTopExecCountsCmd()
HighlightTopExecCountsCmd::~HighlightTopExecCountsCmd () virtual
The Destructor.
Definition at line 52 of file HighlightTopExecCountsCmd.cc.
{
}
Member Function Documentation
create()
HighlightTopExecCountsCmd * HighlightTopExecCountsCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 101 of file HighlightTopExecCountsCmd.cc.
{
    return new HighlightTopExecCountsCmd();
}
References HighlightTopExecCountsCmd().
Do()
bool HighlightTopExecCountsCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file HighlightTopExecCountsCmd.cc.
{
    ProximDisassemblyWindow* window = ProximToolbox::disassemblyWindow();
    assert(window != NULL);
    DisasmTopCountAttrProvider* attrProvider =
        new DisasmTopCountAttrProvider(*ProximToolbox::frontend(), 10);
    if (ProximToolbox::frontend()->isProgramLoaded()) {
        attrProvider->update();
    }
    window->setMoveAttrProvider(attrProvider);
    window->Refresh();
    return true;
}
References assert, ProximToolbox::disassemblyWindow(), ProximToolbox::frontend(), ProximDisassemblyWindow::setMoveAttrProvider(), and DisasmTopCountAttrProvider::update().
icon()
std::string HighlightTopExecCountsCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 81 of file HighlightTopExecCountsCmd.cc.
{
    return "clear_console.png";
}
id()
int HighlightTopExecCountsCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 90 of file HighlightTopExecCountsCmd.cc.
{
    return ProximConstants::COMMAND_HIGHLIGHT_TOP_EXEC_COUNTS;
}
References ProximConstants::COMMAND_HIGHLIGHT_TOP_EXEC_COUNTS.
isEnabled()
bool HighlightTopExecCountsCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
True if the console window exists.
Implements GUICommand.
Definition at line 112 of file HighlightTopExecCountsCmd.cc.
{
    if (ProximToolbox::frontend()->isProgramLoaded()) {
    return true;
    } else {
    return false;
    }
}
References ProximToolbox::frontend().
The documentation for this class was generated from the following files:
HighlightTopExecCountsCmd.hh
HighlightTopExecCountsCmd.cc