OpenASIP: BFRenameSource Class Reference
BFRenameSource Class Reference
#include <BFRenameSource.hh>
Public Member Functions
BFRenameSource (BF2Scheduler &sched, MoveNode &mn, int originalDDGLC, int targetCycle)
virtual bool operator() ()
virtual ~BFRenameSource ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Attributes
MoveNode & mn_
int originalDDGLC_
int targetCycle_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 42 of file BFRenameSource.hh.
Constructor & Destructor Documentation
BFRenameSource()
BFRenameSource::BFRenameSource (BF2Scheduler & sched, MoveNode & mn, int originalDDGLC, int targetCycle)
Definition at line 44 of file BFRenameSource.cc.
                                                                   :
    BFOptimization(sched), mn_(mn),
    originalDDGLC_(originalDDGLC),
    targetCycle_(targetCycle) {}
~BFRenameSource()
virtual BFRenameSource::~BFRenameSource () inline virtual
Definition at line 49 of file BFRenameSource.hh.
{}
Member Function Documentation
operator()()
bool BFRenameSource::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 51 of file BFRenameSource.cc.
{
    if (sched_.renamer() == nullptr) {
        return false;
    }
    // not yet working with loop scheduling
    if (ii()) {
        return false;
    }
    TTAProgram::Move& m = mn_.move();
    TTAProgram::Terminal& t = m.source();
    if (!t.isGPR()) {
        return false;
    }
    std::shared_ptr<LiveRange> liveRange(ddg().findLiveRange(mn_, false, false));
    if (liveRange->writes.size() != 1 ||
        liveRange->reads.empty() ||
        !liveRange->guards.empty()) {
        return false;
    }
    for (auto i: liveRange->writes) {
        if (i->isScheduled()) {
            return false;
        }
    }
    // for reads.
    for (auto i: liveRange->reads) {
        if (i->isScheduled()) {
            return false;
        }
    }
    // for reads.
    for (auto i: liveRange->guards) {
        if (i->isScheduled()) {
            return false;
        }
    }
    return runPreChild(new BFRenameLiveRange(sched_, liveRange, targetCycle_));
}
References BFOptimization::ddg(), BFOptimization::ii(), TTAProgram::Terminal::isGPR(), mn_, MoveNode::move(), BF2Scheduler::renamer(), Reversible::runPreChild(), BFOptimization::sched_, TTAProgram::Move::source(), and targetCycle_.
Member Data Documentation
mn_
MoveNode& BFRenameSource::mn_ protected
Definition at line 52 of file BFRenameSource.hh.
Referenced by operator()().
originalDDGLC_
int BFRenameSource::originalDDGLC_ protected
Definition at line 53 of file BFRenameSource.hh.
targetCycle_
int BFRenameSource::targetCycle_ protected
Definition at line 54 of file BFRenameSource.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFRenameSource.hh
BFRenameSource.cc