OpenASIP: Application Class Reference
Application Class Reference
#include <Application.hh>
Classes
class UnixSignalHandler
Static Public Member Functions
static void initialize (int argc, char *argv[])
static void initialize ()
static void finalize ()
static void writeToErrorLog (const std::string fileName, const int lineNumber, const std::string functionName, const std::string message, const int neededVerbosity=0)
static void exitProgram (const int status=EXIT_SUCCESS)
static void abortProgram () __attribute__((noreturn))
static void unexpectedExceptionHandler ()
static bool shellCommandsExists (const std::string &commands)
static int runShellCommandSilently (const std::string &command)
static int runShellCommandAndGetOutput (const std::string &command, std::vector< std::string > &outputLines, std::size_t maxOutputLines=DEFAULT_MAX_OUTPUT_LINES, bool includeStdErr=false)
static std::ostream & logStream ()
static std::ostream & warningStream ()
static std::ostream & errorStream ()
static int verboseLevel ()
static bool increasedVerbose ()
static bool spamVerbose ()
static void setVerboseLevel (const int level=VERBOSE_LEVEL_DEFAULT)
static void setCmdLineOptions (CmdLineOptions *options_)
static CmdLineOptions * cmdLineOptions ()
static int argc ()
static char ** argv ()
static bool isInstalled ()
static std::string installationDir ()
static void setSignalHandler (int signalNum, UnixSignalHandler &handler)
static UnixSignalHandler * getSignalHandler (int signalNum)
static void restoreSignalHandler (int signalNum)
static std::string TCEVersionString ()
Static Public Attributes
static const int VERBOSE_LEVEL_DEFAULT = 0
Default verbose level - do not print anything unnecessary.
static const int VERBOSE_LEVEL_INCREASED = 1
Increased verbose level - print information about modules etc.
static const int VERBOSE_LEVEL_SPAM = 2
More Increased verbose level - spam about ddg heights of loops.
static const bool LOOP_OPT_DEFAULT = false
Use Loop Optimizations.
Static Private Member Functions
static void signalRedirector (int data, siginfo_t *info, void *context)
Static Private Attributes
static bool initialized_ = false
True when initialize() is called. Ensures that initialization is done only once.
static std::ostream * logStream_ = NULL
The stream for debug logging.
static std::ostream * errorStream_ = NULL
The stream for user error notifications.
static std::ostream * warningStream_ = NULL
The stream for user error notifications.
static std::map< int, UnixSignalHandler * > signalHandlers_
Signal handlers in a map associated by their signal numbers.
static int verboseLevel_ = Application::VERBOSE_LEVEL_DEFAULT
Verbose level directs how much output will be printed to console.
static CmdLineOptions * cmdLineOptions_ = NULL
Holds command line options passed to program.
static int argc_
The original argc and argv given to the main program, if applicable.
static char ** argv_
static std::string installationRoot_ = ""
Path to the TCE installation root.
Detailed Description
Definition at line 144 of file Application.hh.
Member Function Documentation
abortProgram()
void Application::abortProgram () static
Exit the program in an abnormal situation.
Definition at line 266 of file Application.cc.
{
    abort();
}
Referenced by UniversalMachine::addAddressSpace(), UniversalMachine::addBridge(), UniversalMachine::addBus(), UniversalMachine::addFunctionUnit(), UniversalMachine::addImmediateUnit(), UniversalMachine::addInstructionTemplate(), UniversalFunctionUnit::addPipelineElement(), UniversalMachine::addRegisterFile(), UniversalMachine::addSocket(), UniversalFunctionUnit::addSupportedOperation(), TTAMachine::Socket::attachBus(), SmartHWOperation::bindPort(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Socket::connection(), UniversalMachine::construct(), TTAProgram::TPEFProgramFactory::createTerminal(), UniversalMachine::deleteAddressSpace(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), initialize(), SmartHWOperation::loadState(), UnboundedRegisterFile::loadState(), UniversalFunctionUnit::loadState(), UniversalFUPort::loadState(), UniversalMachine::loadState(), ADFSerializer::machinePipeline(), ADFSerializer::machineSRPort(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), UniversalMachine::removeBus(), UniversalMachine::removeFunctionUnit(), UniversalMachine::removeRegisterFile(), UniversalMachine::removeSocket(), UniversalMachine::setGlobalControl(), ADFSerializer::setIUExtensionMode(), UnboundedRegisterFile::setMaxReads(), UnboundedRegisterFile::setMaxWrites(), SmartHWOperation::setName(), UnboundedRegisterFile::setName(), UniversalFUPort::setName(), UnboundedRegisterFile::setNumberOfRegisters(), UniversalFUPort::setOpcodeSetting(), UniversalFUPort::setTriggering(), UnboundedRegisterFile::setType(), UnboundedRegisterFile::setWidth(), UniversalFUPort::setWidth(), SmartHWOperation::unbindPort(), TTAMachine::Port::unconnectedSocket(), unexpectedExceptionHandler(), and UniversalMachine::unsetGlobalControl().
argc()
static int Application::argc () inline static
Definition at line 192 of file Application.hh.
{ return argc_; }
References argc_.
Referenced by initialize(), and SimulatorCLI::SimulatorCLI().
argv()
static char ** Application::argv () inline static
Definition at line 193 of file Application.hh.
{ return argv_; }
References argv_.
Referenced by initialize(), and SimulatorCLI::SimulatorCLI().
cmdLineOptions()
CmdLineOptions * Application::cmdLineOptions () static
Definition at line 397 of file Application.cc.
{
    return cmdLineOptions_;
}
References cmdLineOptions_.
Referenced by llvm::TCEPassConfig::addPreISel(), BasicBlockScheduler::BasicBlockScheduler(), BBSchedulerController::BBSchedulerController(), BF2Scheduler::BF2Scheduler(), BF2Scheduler::BF2Scheduler(), BFEarlyBypasser::BFEarlyBypasser(), BFLateBypasses::BFLateBypasses(), BFShareOperands::BFShareOperands(), BFShareOperandsLate::BFShareOperandsLate(), BUBasicBlockScheduler::BUBasicBlockScheduler(), llvm::LLVMTCEIRBuilder::compileOptimized(), llvm::TCETargetMachine::createMachine(), CycleLookBackSoftwareBypasser::CycleLookBackSoftwareBypasser(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), llvm::TCERegisterInfo::eliminateFrameIndex(), llvm::TCERegisterInfo::getReservedRegs(), BBSchedulerController::handleBasicBlock(), SimpleIfConverter::handleControlFlowGraph(), PreOptimizer::handleProcedure(), BBSchedulerController::handleProcedure(), llvm::LLVMTCEBuilder::initMembers(), llvm::TCETTIImpl::isHardwareLoopProfitable(), LLVMBackend::LLVMBackend(), DataDependenceGraphBuilder::memoryCategory(), DesignSpaceExplorer::schedule(), SimpleBrokerDirector::SimpleBrokerDirector(), SimpleIfConverter::SimpleIfConverter(), SimulatorCLI::SimulatorCLI(), llvm::TCETargetLowering::TCETargetLowering(), and llvm::LLVMTCEIRBuilder::~LLVMTCEIRBuilder().
errorStream()
std::ostream & Application::errorStream () static
Stream where error messages that should be printed immediately to the user should be written.
Errors are fatal which means the action performed could not be finished.
Usage example: errorStream() << "Compilation error: "...
Returns
A reference to the error stream.
Definition at line 171 of file Application.cc.
{
    initialize();
    return *errorStream_;
}
References errorStream_, and initialize().
Referenced by BlocksConnectIC::explore(), VLIWConnectIC::explore(), main(), ConstantTransformer::runOnMachineFunction(), and writeCustomOpMacros().
exitProgram()
void Application::exitProgram (const int status = EXIT_SUCCESS) static
Exits the program in a normal situation.
This method must be used when the program terminates due to nominal conditions without returning from main().
Parameters
status Program's status of exit.
Definition at line 258 of file Application.cc.
{
    exit(status);
}
Referenced by ComponentAdder::addRegisterFiles().
finalize()
void Application::finalize () static
Cleans up the state data used by the application services.
This method is called automatically when program is terminated.
Definition at line 199 of file Application.cc.
                      {
    if (!initialized_) {
        return;
    }
    if (logStream_ != &cerr && logStream_ != &cout && logStream_ != NULL) {
        logStream_->flush();
        delete logStream_;
        logStream_ = NULL;
    }
    delete cmdLineOptions_;
    cmdLineOptions_ = NULL;
    initialized_ = false;
}
References cmdLineOptions_, initialized_, and logStream_.
Referenced by initialize().
getSignalHandler()
Application::UnixSignalHandler * Application::getSignalHandler (int signalNum) static
Returns a pointer to the signal's current handler
In platforms which do not support signals this method always returns NULL.
Returns
a pointer to the signal's current handler
Exceptions
InstanceNotFound if the signal has not been set a custom handler
Definition at line 445 of file Application.cc.
{
    std::map<int, UnixSignalHandler*>::iterator it =
        signalHandlers_.find(signalNum);
    if (it != signalHandlers_.end()) {
        return it->second;
    } else {
        throw InstanceNotFound(__FILE__, __LINE__, __FUNCTION__);
    }
}
References signalHandlers_.
Referenced by signalRedirector().
increasedVerbose()
static bool Application::increasedVerbose () inline static
Definition at line 179 of file Application.hh.
{
        return verboseLevel() > VERBOSE_LEVEL_DEFAULT;
    }
References VERBOSE_LEVEL_DEFAULT, and verboseLevel().
Referenced by DesignSpaceExplorer::evaluate(), and ProGe::ProGeUI::generateIDF().
initialize() [1/2]
void Application::initialize () static
Initializes the state data needed by the application services.
Definition at line 99 of file Application.cc.
{
    // ensure that initialization is done only once per application
    if (initialized_) {
        return;
    }
    // if this is a developer version, we can output debug messages to
    // cerr, in 'distributed version', we'll output the debug messages to
    // a file
    if (Environment::developerMode()) {
        logStream_ = &cerr;
    } else {
        ofstream* fileLog = new ofstream;
        fileLog->open(Environment::errorLogFilePath().c_str(), ios::app);
        if (!fileLog->is_open()) {
            logStream_ = &cerr;
        } else {
            logStream_ = fileLog;
        }
    }
    installationRoot_ = installationDir();
    errorStream_ = &cerr;
    warningStream_ = &cerr;
    // set the unexpected exception callback
    set_unexpected(Application::unexpectedExceptionHandler);
    // register finalization function to be called when exit() is called
    // so Application is finalized automatically on program exit
    if (atexit(Application::finalize) != 0) {
        writeToErrorLog(__FILE__, __LINE__, __FUNCTION__,
            "Application initialization failed.");
        abortProgram();
    }
    initialized_ = true;
}
References abortProgram(), Environment::developerMode(), Environment::errorLogFilePath(), errorStream_, finalize(), initialized_, installationDir(), installationRoot_, logStream_, unexpectedExceptionHandler(), warningStream_, and writeToErrorLog().
Referenced by errorStream(), Script::execute(), initialize(), logStream(), main(), OSEd::OnInit(), Proxim::OnInit(), HDBEditor::OnInit(), ProDe::OnInit(), warningStream(), and writeToErrorLog().
initialize() [2/2]
void Application::initialize (int argc, char * argv[]) static
Definition at line 141 of file Application.cc.
{
    Application::initialize();
    argc_ = argc;
    argv_ = argv;
}
References argc(), argc_, argv(), argv_, and initialize().
installationDir()
string Application::installationDir () static
Returns the path to TCE installation root
Installation root can be one created by 'make install' or .deb package unpacked to homedir for example. Environment variable TCE_INSTALL_DIR should be set in the second case pointing to that dir where .deb was installed or tce installation manually copied/moved to.
Returns
Path to TCE installation root
Definition at line 537 of file Application.cc.
{
    if (installationRoot_ != "") {
        return installationRoot_;
    }
    string userRoot = Environment::environmentVariable("TCE_INSTALL_DIR");
    // .deb check: check if envvar TCE_INSTALL_DIR is set
    // and that dir exists ("icons" dir in our case)
    if (userRoot != "" && FileSystem::fileExists(
        userRoot + "/share/openasip/data/icons")) {
        return userRoot;
    }
    return string(TCE_INSTALLATION_ROOT);
}
References Environment::environmentVariable(), FileSystem::fileExists(), and installationRoot_.
Referenced by OperationBuilder::buildObject(), Environment::codeCompressorPaths(), Environment::confPath(), LLVMBackend::createPlugin(), Environment::defaultSchedulerConf(), Environment::estimatorPluginPaths(), Environment::explorerPluginPaths(), Environment::hdbPaths(), Environment::icDecoderPluginPaths(), Environment::implementationTesterTemplatePaths(), Environment::includeDirPaths(), initialize(), Environment::initialize(), Environment::longHDBPath(), Environment::minimalADF(), Environment::oldGccSchedulerConf(), Environment::osalPaths(), Environment::pdfManual(), Environment::schedulerPluginPaths(), Environment::shortHDBPath(), Environment::tceCompiler(), and Environment::vhdlPaths().
isInstalled()
bool Application::isInstalled () static
Returns true if the application is running from an install path.
Since there is no reliable way to detect this from the binary name or such since TCE can be used as a library, we just assume we are using an installed TCE in case the developer mode is not set.
Definition at line 522 of file Application.cc.
{
    return !Environment::developerMode();
}
References Environment::developerMode().
Referenced by OperationBuilder::buildObject(), and main().
logStream()
std::ostream & Application::logStream () static
Allows writing to the log stream with stream operators.
Usage example: logStream() << "Debug output" << i << endl;
Returns
A reference to the log stream.
Definition at line 155 of file Application.cc.
                       {
    initialize();
    return *logStream_;
}
References initialize(), and logStream_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), LoopPrologAndEpilogBuilder::addEpilogFromRM(), ControlFlowGraph::addExit(), ProgramDependenceGraph::addLeafEdges(), RegisterCopyAdder::addMinimumRegisterCopies(), llvm::LLVMTCEBuilder::addPointerAnnotations(), LoopPrologAndEpilogBuilder::addPrologFromRM(), RegisterCopyAdder::addRegisterCopies(), RegisterCopyAdder::addRegisterCopiesToRRMove(), llvm::LLVMTCEBuilder::addressSpaceById(), MultiLatencyOperationExecutor::advanceClock(), ResourceConstraintAnalyzer::analyze(), PRegionAliasAnalyzer::analyze(), ControlDependenceGraph::analyzeCDG(), TDGen::analyzeMachineRegisters(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), TDGen::analyzeRegisters(), SimpleResourceManager::assign(), MachineInstrDDG::assignPhysReg(), DataDependenceGraphBuilder::build(), LoopPrologAndEpilogBuilder::build(), MoveNodeGroupBuilder::build(), ControlFlowGraph::buildMBBFromBB(), OperationBuilder::buildObject(), llvm::LLVMTCEIRBuilder::buildTCECFG(), SimpleResourceManager::canAssign(), SimpleBrokerDirector::canAssign(), SimpleIfConverter::canConvert(), DataDependenceGraphBuilder::checkAndCreateMemDep(), ProgramDependenceGraph::compareSiblings(), LLVMBackend::compile(), CompiledSimCompiler::compileDirectory(), CompiledSimCompiler::compileFile(), ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), BasicBlockPass::copyRMToBB(), ControlFlowGraph::createControlFlowEdge(), TTAProgram::ProgramWriter::createDataSections(), InstructionDictionary::createDictionary(), ProgramDependenceGraph::createJump(), llvm::LLVMTCEIRBuilder::createMBBReference(), LLVMBackend::createPlugin(), DataDependenceGraphBuilder::createRegisterDeps(), llvm::createTCESchedulerPass(), TTAProgram::TPEFProgramFactory::createTerminal(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), BasicBlockPass::ddgSnapshot(), llvm::LLVMTCEBuilder::deleteDeadProcedures(), ProgramDependenceGraph::disassemble(), MoveNodeGroup::earliestCycle(), SimpleResourceManager::earliestCycle(), SimpleResourceManager::earliestCycle(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEBuilder::emitWriteSP(), StrictMatchRFEstimator::estimateArea(), InterpolatingRFEstimator::estimateArea(), StrictMatchFUEstimator::estimateArea(), InterpolatingFUEstimator::estimateArea(), InterpolatingRFEstimator::estimateEnergy(), StrictMatchRFEstimator::estimateEnergy(), InterpolatingFUEstimator::estimateEnergy(), StrictMatchFUEstimator::estimateEnergy(), StrictMatchRFEstimator::estimateMaximumComputationDelay(), InterpolatingRFEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimateMaximumComputationDelay(), InterpolatingFUEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimatePortReadDelay(), InterpolatingFUEstimator::estimatePortReadDelay(), StrictMatchRFEstimator::estimatePortReadDelay(), InterpolatingRFEstimator::estimatePortReadDelay(), StrictMatchFUEstimator::estimatePortWriteDelay(), InterpolatingFUEstimator::estimatePortWriteDelay(), StrictMatchRFEstimator::estimatePortWriteDelay(), InterpolatingRFEstimator::estimatePortWriteDelay(), DesignSpaceExplorer::evaluate(), BasicBlockPass::executeDDGPass(), BBSchedulerController::executeDDGPass(), ProgramPass::executeProcedurePass(), CodeSectionCreator::finalize(), CostEstimator::Estimator::findAllICPaths(), CompiledSimCodeGenerator::findBasicBlocks(), ProgramImageGenerator::generateProgramImage(), BBSchedulerController::handleBasicBlock(), CallsToJumps::handleControlFlowGraph(), SimpleIfConverter::handleControlFlowGraph(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), llvm::LLVMTCEBuilder::handleMemoryCategoryInfo(), BBSchedulerController::handleProcedure(), BasicBlockScheduler::handleRemovedResultMoves(), CostEstimator::Estimator::icArea(), llvm::LLVMTCEBuilder::initDataSections(), StopPoint::isConditionOK(), SimpleResourceManager::largestCycle(), SimpleResourceManager::latestCycle(), SimpleResourceManager::latestCycle(), llvm::LLVMTCERISCVIntrinsicsLowering::LLVMTCERISCVIntrinsicsLowering(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), CostEstimator::Estimator::longestPath(), MachineInstrDDG::MachineInstrDDG(), main(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), CompiledSimulation::msg(), VirtRegIndependenceGraph::newFalseDepsFromAssign(), BlockImplementationFileDialog::onOK(), MoveSlotDictionary::printDetails(), ControlDependenceNode::printRelations(), ProgramDependenceNode::printRelations(), ControlDependenceGraph::processRegion(), ProgramDependenceGraph::processRegion(), ADFCombiner::readParameters(), ProgramDependenceGraph::removeGuardedJump(), CompiledSimController::reset(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), DataDependenceGraphBuilder::searchRegisterDeaths(), ProgramDependenceGraph::serializePDG(), SimpleIfConverter::SimpleIfConverter(), SimpleResourceManager::smallestCycle(), MultiLatencyOperationExecutor::startOperation(), SimpleIfConverter::successors(), llvm::TCETargetLowering::TCETargetLowering(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), SimpleResourceManager::unassign(), TTAProgram::InstructionReferenceManager::validate(), TDGen::verbose(), VirtRegIndependenceGraph::VirtRegIndependenceGraph(), TDGen::writeInstrInfo(), llvm::LLVMTCEBuilder::writeMachineFunction(), llvm::LLVMTCEIRBuilder::writeMachineFunction(), TDGen::writeOperationDef(), and FiniteStateAutomaton::~FiniteStateAutomaton().
restoreSignalHandler()
void Application::restoreSignalHandler (int signalNum) static
Restores to the signal its original handler
Note in platforms which do not support signals (e.g. Windows), this function does nothing.
Parameters
signalNum signal number
Definition at line 471 of file Application.cc.
{
    signal(signalNum, SIG_DFL);
    signalHandlers_.erase(signalNum);
}
References signalHandlers_.
Referenced by main().
runShellCommandAndGetOutput()
int Application::runShellCommandAndGetOutput (const std::string & command, std::vector< std::string > & outputLines, std::size_t maxOutputLines = DEFAULT_MAX_OUTPUT_LINES, bool includeStdErr = false) static
Runs a shell command and captures its output (stdout) in the given vector.
Assumes that the executed program does not block and wait for input.
Parameters
command Command to execute.
outputLines Vector to which put the output lines.
maxOutputLines Maximum lines to capture.
Returns
The return value of the program. -1 if some weird error occured.
Definition at line 338 of file Application.cc.
{
    char line[MAX_OUTPUT_LINE_LENGTH];
    // flush all streams to avoid: "...the output from a
    // command opened for writing may become intermingled with that of
    // the original process." (man popen)
    fflush(NULL);
    string shellCommand = command;
    if (includeStdErr) {
        shellCommand += " 2>1";
    }
    FILE* pipe = popen(shellCommand.c_str(), "r");
    while (fgets(line, MAX_OUTPUT_LINE_LENGTH, pipe) == line) {
        if (outputLines.size() < maxOutputLines) {
            outputLines.push_back(string(line));
        }
    }
    int exitStatus = pclose(pipe);
    // see man wait4 for info about macros WIFEXITED and WEXITSTATUS
    if (WIFEXITED(exitStatus)) {
        return WEXITSTATUS(exitStatus);
    }
    return -1;
}
References MAX_OUTPUT_LINE_LENGTH, WEXITSTATUS, and WIFEXITED.
Referenced by OperationBuilder::buildObject(), CompileTools::compileAsC(), GhdlSimulator::compileDesign(), ModelsimSimulator::compileOneFile(), ModelsimSimulator::createWorkDir(), GhdlSimulator::importFile(), DesignSpaceExplorer::schedule(), GhdlSimulator::simulate(), and ModelsimSimulator::simulate().
runShellCommandSilently()
int Application::runShellCommandSilently (const std::string & command) static
Runs a shell command and redirects all output to /dev/null
Parameters
command Command to execute.
Returns
The return value of the program. -1 if some weird error occurred.
Definition at line 301 of file Application.cc.
{
    char line[MAX_OUTPUT_LINE_LENGTH];
    // flush all streams to avoid: "...the output from a
    // command opened for writing may become intermingled with that of
    // the original process." (man popen)
    fflush(NULL);
    std::string fullCommand = command + " 2>&1 ";
    FILE* pipe = popen(fullCommand.c_str(), "r");
    while (fgets(line, MAX_OUTPUT_LINE_LENGTH, pipe) == line) {
        // Drain stdout and stderr data.
    }
    int exitStatus = pclose(pipe);
    // see man wait4 for info about macros WIFEXITED and WEXITSTATUS
    if (WIFEXITED(exitStatus)) {
        return WEXITSTATUS(exitStatus);
    }
    return -1;
}
References MAX_OUTPUT_LINE_LENGTH, WEXITSTATUS, and WIFEXITED.
Referenced by CompileTools::compileAsLLVM(), and shellCommandsExists().
setCmdLineOptions()
void Application::setCmdLineOptions (CmdLineOptions * options) static
Set the command line options instance for the application.
The object becomes owned by Application class. It should be fully built (parsed) before passed to Application.
Definition at line 381 of file Application.cc.
{
    // delete the possible old instance first
    delete cmdLineOptions_;
    cmdLineOptions_ = options;
    if (options->isVerboseSwitchDefined()) {
        setVerboseLevel(Application::VERBOSE_LEVEL_INCREASED);
    }
    if (options->isVerboseSpamSwitchDefined()) {
        setVerboseLevel(Application::VERBOSE_LEVEL_SPAM);
    }
}
References cmdLineOptions_, CmdLineOptions::isVerboseSpamSwitchDefined(), CmdLineOptions::isVerboseSwitchDefined(), options, setVerboseLevel(), VERBOSE_LEVEL_INCREASED, and VERBOSE_LEVEL_SPAM.
Referenced by llvm::LLVMTCEScheduler::LLVMTCEScheduler(), and main().
setSignalHandler()
void Application::setSignalHandler (int signalNum, UnixSignalHandler & handler) static
Sets a new signal handler for the given signal
Note in platforms which do not support signals (e.g. Windows), this function does nothing.
Parameters
signalNum signal number
handler The handler to be set
Definition at line 417 of file Application.cc.
{
    signalHandlers_[signalNum] = &handler;
    struct sigaction action;
    action.sa_flags = SA_SIGINFO;
    action.sa_sigaction = signalRedirector;
    // valgrind complains if this is uninitialized
    sigemptyset(&action.sa_mask);
    sigaction(signalNum, &action, NULL);
}
References signalHandlers_, and signalRedirector().
Referenced by main().
setVerboseLevel()
static void Application::setVerboseLevel (const int level = VERBOSE_LEVEL_DEFAULT) inline static
Definition at line 186 of file Application.hh.
{
        verboseLevel_ = level;
    }
References verboseLevel_.
Referenced by GenerateProcessor::generateProcessor(), main(), and setCmdLineOptions().
shellCommandsExists()
bool Application::shellCommandsExists (const std::string & commands) static
Returns true if all commands separated by space are found.
Otherwise return false;
Definition at line 290 of file Application.cc.
{
    return runShellCommandSilently(std::string("type ") + commands) == 0;
}
References runShellCommandSilently().
signalRedirector()
void Application::signalRedirector (int data, siginfo_t * info, void * context) static private
Redirects the signal received to the current signal handler
Note in platforms which do not support signals (e.g. Windows), this function does nothing.
Parameters
data Data from the signal.
info signal information struct
context signal context
Definition at line 494 of file Application.cc.
{
    UnixSignalHandler* handler = getSignalHandler(info->si_signo);
    assert(handler != NULL);
    handler->execute(data, info);
}
References assert, Application::UnixSignalHandler::execute(), and getSignalHandler().
Referenced by setSignalHandler().
spamVerbose()
static bool Application::spamVerbose () inline static
Definition at line 182 of file Application.hh.
{
        return verboseLevel() > VERBOSE_LEVEL_INCREASED;
    }
References VERBOSE_LEVEL_INCREASED, and verboseLevel().
Referenced by ProGe::ProcessorGenerator::generateProcessor(), and InlineAsmParser::substituteAsmString().
TCEVersionString()
std::string Application::TCEVersionString () static
Returns the version string of the TCE build.
This string includes the version control revision (if available), automatically generated during build. This cannot be in headers as it would induce a (almost) complete build of TCE on every revision change.
Definition at line 510 of file Application.cc.
{
    return TCE_VERSION_STRING;
}
Referenced by RISCVTDGen::dumpClassDefinitions(), Proxim::OnInit(), LLVMBackend::pluginFilename(), ExplorerCmdLineOptions::printVersion(), LLVMTCECmdLineOptions::printVersion(), SchedulerCmdLineOptions::printVersion(), SimulatorCmdLineOptions::printVersion(), AsmCmdLineOptions::printVersion(), BEMViewerCmdLineOptions::printVersion(), DisasmCmdLineOptions::printVersion(), DictionaryToolCmdLineOptions::printVersion(), DumperCmdLineOptions::printVersion(), EstimatorCmdLineOptions::printVersion(), BuildOpsetOptions::printVersion(), OsalCmdLineOptions::printVersion(), CreateHDBCmdLineOptions::printVersion(), TestHDBCmdLineOptions::printVersion(), MachInfoCmdLineOptions::printVersion(), ProGeCmdLineOptions::printVersion(), and TTAUnitTesterCmdLineOptions::printVersion().
unexpectedExceptionHandler()
void Application::unexpectedExceptionHandler () static
Default callback for unexpected exceptions.
Definition at line 274 of file Application.cc.
{
    *logStream_
        << std::endl
        << "Program aborted because of leaked unexpected exception. "
        << std::endl << std::endl <<
        "Information of the last thrown TCE exception: " << std::endl
        << Exception::lastExceptionInfo() << std::endl;
    abortProgram();
}
References abortProgram(), Exception::lastExceptionInfo(), and logStream_.
Referenced by initialize().
verboseLevel()
static int Application::verboseLevel () inline static
Definition at line 176 of file Application.hh.
{
        return verboseLevel_;
    }
References verboseLevel_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), LoopPrologAndEpilogBuilder::addEpilogFromRM(), ControlFlowGraph::addExit(), LoopPrologAndEpilogBuilder::addPrologFromRM(), LoopPrologAndEpilogBuilder::addPrologIntoCfg(), LoopAnalyzer::analyze(), ControlDependenceGraph::analyzeCDG(), TDGen::analyzeMachineRegisters(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), TDGen::analyzeRegisters(), LoopPrologAndEpilogBuilder::build(), OperationBuilder::buildObject(), FrequencySweepExplorer::callPlugin(), LLVMBackend::compile(), MoveSlotDictionary::compress(), BasicBlockPass::copyRMToBB(), ControlFlowGraph::createControlFlowEdge(), InstructionDictionary::createDictionary(), LLVMBackend::createPlugin(), DataDependenceGraphBuilder::createRegisterDeps(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), llvm::LLVMTCEBuilder::deleteDeadProcedures(), BasicBlockPass::executeDDGPass(), BBSchedulerController::executeDDGPass(), ProgramPass::executeProcedurePass(), GrowMachine::explore(), FrequencySweepExplorer::explore(), LoopAnalyzer::findInitAndUpdate(), ProgramImageGenerator::generateProgramImage(), BBSchedulerController::handleBasicBlock(), SimpleIfConverter::handleControlFlowGraph(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BBSchedulerController::handleProcedure(), CostEstimator::Estimator::icArea(), increasedVerbose(), llvm::LLVMTCEBuilder::initDataSections(), llvm::TCETargetLowering::LowerBuildVector(), llvm::TCETargetLowering::LowerConstant(), llvm::TCETargetLowering::LowerGLOBALADDRESS(), main(), BasicBlockScheduler::printStats(), ControlDependenceGraph::processRegion(), ProgramDependenceGraph::processRegion(), MachineConnectivityCheck::raConnected(), ProgramDependenceGraph::removeGuardedJump(), ConstantTransformer::runOnMachineFunction(), DesignSpaceExplorer::schedule(), BF2ScheduleFront::scheduleFrontFromMove(), DataDependenceGraphBuilder::searchRegisterDeaths(), ProgramDependenceGraph::serializePDG(), SimpleIfConverter::SimpleIfConverter(), spamVerbose(), llvm::TCETargetLowering::TCETargetLowering(), MachineConnectivityCheck::tempRegisterFiles(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), TDGen::verbose(), TDGen::writeInstrInfo(), llvm::LLVMTCEBuilder::writeMachineFunction(), llvm::LLVMTCEIRBuilder::writeMachineFunction(), and TDGen::writeOperationDef().
warningStream()
std::ostream & Application::warningStream () static
Stream where warning messages that should be printed immediately to the user should be written.
Warnings are non-fatal notifications to the user. The action performed might still be able to be finished.
Usage example: warningStream() << "warning: uninitialized thing "...
Returns
A reference to the warning stream.
Definition at line 188 of file Application.cc.
{
    initialize();
    return *warningStream_;
}
References initialize(), and warningStream_.
Referenced by MachineStateBuilder::addPortToFU(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), and CostEstimator::Estimator::totalAreaOfRegisterFiles().
writeToErrorLog()
void Application::writeToErrorLog (const std::string fileName, const int lineNumber, const std::string functionName, const std::string message, const int neededVerbosity = 0) static
Records a message into the error log.
Parameters
fileName Source file of the code where the error occurred.
lineNumber Source line where the error occurred.
functionName Function where the error occurred.
message The error message.
Definition at line 224 of file Application.cc.
{
    if (neededVerbosity > verboseLevel_) {
        return;
    }
    if (!initialized_) {
        initialize();
    }
    *logStream_ << fileName << ":" << lineNumber << ": ";
    if (functionName != UNKNOWN_FUNCTION) {
        *logStream_ <<  "In function \'" << functionName << "\': ";
    }
    *logStream_ << message << endl;
}
References initialize(), initialized_, logStream_, UNKNOWN_FUNCTION, and verboseLevel_.
Referenced by UniversalMachine::addAddressSpace(), UniversalMachine::addBridge(), UniversalMachine::addBus(), UniversalMachine::addFunctionUnit(), UniversalMachine::addImmediateUnit(), UniversalMachine::addInstructionTemplate(), UniversalFunctionUnit::addPipelineElement(), UniversalMachine::addRegisterFile(), UniversalMachine::addSocket(), UniversalFunctionUnit::addSupportedOperation(), TTAMachine::Socket::attachBus(), SmartHWOperation::bindPort(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Socket::connection(), UniversalMachine::construct(), FileSystem::currentWorkingDir(), UniversalMachine::deleteAddressSpace(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), initialize(), SmartHWOperation::loadState(), UnboundedRegisterFile::loadState(), UniversalFunctionUnit::loadState(), UniversalFUPort::loadState(), UniversalMachine::loadState(), ADFSerializer::machinePipeline(), ADFSerializer::machineSRPort(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), UniversalMachine::removeBus(), UniversalMachine::removeFunctionUnit(), UniversalMachine::removeRegisterFile(), UniversalMachine::removeSocket(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), UniversalMachine::setGlobalControl(), ADFSerializer::setIUExtensionMode(), UnboundedRegisterFile::setMaxReads(), UnboundedRegisterFile::setMaxWrites(), SmartHWOperation::setName(), UnboundedRegisterFile::setName(), UniversalFUPort::setName(), UnboundedRegisterFile::setNumberOfRegisters(), UniversalFUPort::setOpcodeSetting(), UniversalFUPort::setTriggering(), UnboundedRegisterFile::setType(), UnboundedRegisterFile::setWidth(), UniversalFUPort::setWidth(), SmartHWOperation::unbindPort(), TTAMachine::Port::unconnectedSocket(), UniversalMachine::unsetGlobalControl(), ExecutionTrace::~ExecutionTrace(), ScriptInterpreter::~ScriptInterpreter(), and SQLiteQueryResult::~SQLiteQueryResult().
Member Data Documentation
argc_
int Application::argc_ static private
The original argc and argv given to the main program, if applicable.
Definition at line 257 of file Application.hh.
Referenced by argc(), and initialize().
argv_
char ** Application::argv_ static private
Definition at line 258 of file Application.hh.
Referenced by argv(), and initialize().
cmdLineOptions_
CmdLineOptions * Application::cmdLineOptions_ = NULL static private
Holds command line options passed to program.
Definition at line 254 of file Application.hh.
Referenced by cmdLineOptions(), finalize(), and setCmdLineOptions().
errorStream_
std::ostream * Application::errorStream_ = NULL static private
The stream for user error notifications.
Definition at line 242 of file Application.hh.
Referenced by errorStream(), and initialize().
initialized_
bool Application::initialized_ = false static private
True when initialize() is called. Ensures that initialization is done only once.
Definition at line 236 of file Application.hh.
Referenced by finalize(), initialize(), and writeToErrorLog().
installationRoot_
string Application::installationRoot_ = "" static private
Path to the TCE installation root.
Definition at line 261 of file Application.hh.
Referenced by initialize(), and installationDir().
logStream_
std::ostream * Application::logStream_ = NULL static private
The stream for debug logging.
Definition at line 239 of file Application.hh.
Referenced by finalize(), initialize(), logStream(), unexpectedExceptionHandler(), and writeToErrorLog().
LOOP_OPT_DEFAULT
const bool Application::LOOP_OPT_DEFAULT = false static
Use Loop Optimizations.
Definition at line 229 of file Application.hh.
signalHandlers_
std::map< int, Application::UnixSignalHandler * > Application::signalHandlers_ static private
Signal handlers in a map associated by their signal numbers.
Definition at line 248 of file Application.hh.
Referenced by getSignalHandler(), restoreSignalHandler(), and setSignalHandler().
VERBOSE_LEVEL_DEFAULT
const int Application::VERBOSE_LEVEL_DEFAULT = 0 static
Default verbose level - do not print anything unnecessary.
Definition at line 222 of file Application.hh.
Referenced by TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), OperationBuilder::buildObject(), DataDependenceGraphBuilder::createRegisterDeps(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), increasedVerbose(), DataDependenceGraphBuilder::searchRegisterDeaths(), TDGen::verbose(), TDGen::writeInstrInfo(), and TDGen::writeOperationDef().
VERBOSE_LEVEL_INCREASED
const int Application::VERBOSE_LEVEL_INCREASED = 1 static
Increased verbose level - print information about modules etc.
Definition at line 224 of file Application.hh.
Referenced by GenerateProcessor::generateProcessor(), main(), setCmdLineOptions(), and spamVerbose().
VERBOSE_LEVEL_SPAM
const int Application::VERBOSE_LEVEL_SPAM = 2 static
More Increased verbose level - spam about ddg heights of loops.
Definition at line 226 of file Application.hh.
Referenced by GenerateProcessor::generateProcessor(), and setCmdLineOptions().
verboseLevel_
int Application::verboseLevel_ = Application::VERBOSE_LEVEL_DEFAULT static private
Verbose level directs how much output will be printed to console.
Definition at line 251 of file Application.hh.
Referenced by setVerboseLevel(), verboseLevel(), and writeToErrorLog().
warningStream_
std::ostream * Application::warningStream_ = NULL static private
The stream for user error notifications.
Definition at line 245 of file Application.hh.
Referenced by initialize(), and warningStream().
The documentation for this class was generated from the following files:
Application.hh
Application.cc