OpenASIP: SequenceTools Class Reference
SequenceTools Class Reference
#include <SequenceTools.hh>
Static Public Member Functions
template<typename SequenceType >
static void deleteAllItems (SequenceType &aSequence)
Detailed Description
Definition at line 38 of file SequenceTools.hh.
Member Function Documentation
deleteAllItems()
template<typename SequenceType > static void SequenceTools::deleteAllItems (SequenceType & aSequence) static
Referenced by LabelManager::cleanup(), TTAProgram::Program::cleanup(), ProGe::NetlistPortGroup::clear(), ProgramGraph::clear(), LongImmediateUnitState::clear(), MachineState::clear(), OperationPimpl::clear(), IUResource::clear(), SourceField::clearBridgeEncodings(), LabelManager::clearLastRelocations(), MachineCanvas::clearMoves(), SlotField::clearSocketEncodings(), IDF::MachineImplementation::clearState(), GUIOptions::deleteAllKeyboardShortcuts(), TTAMachine::InstructionTemplate::deleteAllSlots(), GUIOptions::deleteAllToolbarButtons(), GuardField::deleteFUGuardEncodings(), SocketCodeTable::deleteFUPortCodes(), GuardField::deleteGPRGuardEncodings(), BinaryEncoding::deleteImmediateSlots(), BinaryEncoding::deleteInstructionFormats(), SocketCodeTable::deleteIUPortCodes(), BinaryEncoding::deleteLongImmDstRegisterFields(), BinaryEncoding::deleteMoveSlots(), SocketCodeTable::deleteRFPortCodes(), BinaryEncoding::deleteSocketCodes(), SimulatorFrontend::finishSimulation(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadMachine(), SimulatorFrontend::next(), SimulateDialog::onFormatChanged(), SimulateDialog::onTrigger(), SimulatorFrontend::run(), SimulatorFrontend::runUntil(), TTAProgram::GlobalScope::setDataLabelAddressSpace(), SimulatorFrontend::setupCallHistoryTracking(), SimulatorFrontend::step(), BusBroker::~BusBroker(), DataDependenceGraphBuilder::~DataDependenceGraphBuilder(), DisassemblyInstruction::~DisassemblyInstruction(), EditPartFactory::~EditPartFactory(), ExecutableInstruction::~ExecutableInstruction(), FUCollisionMatrixIndex::~FUCollisionMatrixIndex(), HDB::FUImplementation::~FUImplementation(), FUReservationTableIndex::~FUReservationTableIndex(), FUState::~FUState(), TTAProgram::GlobalScope::~GlobalScope(), HDB::HWBlockImplementation::~HWBlockImplementation(), IUResource::~IUResource(), MachineCheckSuite::~MachineCheckSuite(), ProGe::NetlistPortGroup::~NetlistPortGroup(), ObjectState::~ObjectState(), OperationIndex::~OperationIndex(), OperationPropertyLoader::~OperationPropertyLoader(), RegisterFileState::~RegisterFileState(), ResourceBuildDirector::~ResourceBuildDirector(), HDB::RFImplementation::~RFImplementation(), SimulateDialog::~SimulateDialog(), SimulationController::~SimulationController(), and SimulatorFrontend::~SimulatorFrontend().
The documentation for this class was generated from the following file:
SequenceTools.hh