OpenASIP: HDB::RFEntry Class Reference
HDB::RFEntry Class Reference
#include <RFEntry.hh>
Public Member Functions
RFEntry ()
virtual ~RFEntry ()
virtual bool hasImplementation () const
void setImplementation (RFImplementation *implementation)
RFImplementation & implementation () const
virtual bool hasArchitecture () const
void setArchitecture (RFArchitecture *architecture)
RFArchitecture & architecture () const
Public Member Functions inherited from HDB::HDBEntry
virtual ~HDBEntry ()
bool hasID () const
void setID (RowID id)
RowID id () const
bool hasCostFunction () const
CostFunctionPlugin & costFunction () const
void setCostFunction (CostFunctionPlugin *costFunction)
std::string hdbFile () const
void setHDBFile (const std::string &file)
Private Attributes
RFArchitecture * architecture_
Architecture of the entry.
RFImplementation * implementation_
Implementation of the entry.
Additional Inherited Members
Protected Member Functions inherited from HDB::HDBEntry
HDBEntry ()
Detailed Description
Represents an RF entry in HDB.
Definition at line 47 of file RFEntry.hh.
Constructor & Destructor Documentation
RFEntry()
HDB::RFEntry::RFEntry ()
The constructor.
Creates an empty RF entry without ID, architecture, implementation and cost function.
Definition at line 50 of file RFEntry.cc.
                 :
    HDBEntry(), architecture_(NULL), implementation_(NULL) {
}
~RFEntry()
HDB::RFEntry::~RFEntry () virtual
The destructor.
Definition at line 58 of file RFEntry.cc.
                  {
    if (hasArchitecture()) {
        delete architecture_;
    }
    if (hasImplementation()) {
        delete implementation_;
    }
}
References architecture_, hasArchitecture(), hasImplementation(), and implementation_.
Member Function Documentation
architecture()
RFArchitecture & HDB::RFEntry::architecture () const
Returns the architecture of the entry.
Returns
The architecture.
Exceptions
NotAvailable If the entry doesn't have an architecture.
Definition at line 145 of file RFEntry.cc.
{
    if (!hasArchitecture()) {
        const string procName = "RFEntry::architecture";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    return *architecture_;
}
References architecture_, and hasArchitecture().
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), ProGe::ProcessorGenerator::checkIULatencies(), RFTestbenchGenerator::generateTestbench(), BlockImplementationDialog::onHDBSelection(), HDBToHtml::rfEntryToHtml(), setArchitecture(), and HDBBrowserWindow::update().
hasArchitecture()
bool HDB::RFEntry::hasArchitecture () const virtual
Tells whether the RF entry has an architecture.
Returns
True if the RF entry has an architecture, otherwise false.
Implements HDB::HDBEntry.
Definition at line 117 of file RFEntry.cc.
{
    return architecture_ != NULL;
}
References architecture_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), architecture(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), ProGe::ProcessorGenerator::checkIULatencies(), AddRFImplementationCmd::isEnabled(), HDBToHtml::rfEntryToHtml(), setArchitecture(), HDB::HDBManager::setArchitectureForRF(), HDBBrowserWindow::update(), and ~RFEntry().
hasImplementation()
bool HDB::RFEntry::hasImplementation () const virtual
Tells whether the entry has a hardware implementation.
Returns
True if the entry has a hardware implementation, otherwise false.
Implements HDB::HDBEntry.
Definition at line 74 of file RFEntry.cc.
{
    return implementation_ != NULL;
}
References implementation_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFImplementation(), ImplementationTester::canTestRF(), ProGe::BlockSourceCopier::copyBaseRFFiles(), HDBEditorModifyCmd::Do(), implementation(), AddRFImplementationCmd::isEnabled(), BlockImplementationDialog::onHDBSelection(), HDBToHtml::rfEntryToHtml(), setImplementation(), HDBBrowserWindow::update(), and ~RFEntry().
implementation()
RFImplementation & HDB::RFEntry::implementation () const
Returns the implementation of the entry.
Returns
The implementation.
Exceptions
NotAvailable If there is no implementation.
Definition at line 102 of file RFEntry.cc.
{
    if (!hasImplementation()) {
        const string procName = "RFEntry::implementation";
        throw NotAvailable(__FILE__, __LINE__, procName);
    }
    return *implementation_;
}
References hasImplementation(), and implementation_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::BlockSourceCopier::copyBaseRFFiles(), HDBEditorModifyCmd::Do(), RFTestbenchGenerator::generateTestbench(), ProGeScriptGenerator::getBlockOrder(), BlockImplementationDialog::onHDBSelection(), HDBToHtml::rfEntryToHtml(), HDBToHtml::rfImplToHtml(), DefaultDecoderGenerator::sacEnabled(), setImplementation(), HDBBrowserWindow::update(), and ImplementationTester::validateRF().
setArchitecture()
void HDB::RFEntry::setArchitecture (RFArchitecture * architecture)
Sets new architecture for the entry.
Deletes the old architecture if one exists.
Parameters
architecture The new architecture.
Definition at line 130 of file RFEntry.cc.
{
    if (hasArchitecture()) {
        delete architecture_;
    }
    architecture_ = architecture;
}
References architecture(), architecture_, and hasArchitecture().
Referenced by HDB::HDBManager::rfByEntryID().
setImplementation()
void HDB::RFEntry::setImplementation (RFImplementation * implementation)
Sets implementation for the entry.
Deletes the old implementation if one exists.
Parameters
implementation The new implementation.
Definition at line 87 of file RFEntry.cc.
{
    if (hasImplementation()) {
        delete implementation_;
    }
    implementation_ = implementation;
}
References hasImplementation(), implementation(), and implementation_.
Referenced by HDB::HDBManager::rfByEntryID().
Member Data Documentation
architecture_
RFArchitecture* HDB::RFEntry::architecture_ private
Architecture of the entry.
Definition at line 62 of file RFEntry.hh.
Referenced by architecture(), hasArchitecture(), setArchitecture(), and ~RFEntry().
implementation_
RFImplementation* HDB::RFEntry::implementation_ private
Implementation of the entry.
Definition at line 64 of file RFEntry.hh.
Referenced by hasImplementation(), implementation(), setImplementation(), and ~RFEntry().
The documentation for this class was generated from the following files:
RFEntry.hh
RFEntry.cc