OpenASIP: TDGen Class Reference
TDGen Class Reference
#include <TDGen.hh>
Classes
struct RegInfo
struct TerminalDef
Public Member Functions
TDGen (const TTAMachine::Machine &mach, bool initialize=true)
virtual ~TDGen ()
virtual void generateBackend (const std::string &path) const
virtual std::string generateBackend () const
Static Public Attributes
static const char OT_REG_BOOL = 'b'
static const char OT_REG_INT = 'r'
static const char OT_REG_LONG = 's'
static const char OT_REG_FP = 'f'
static const char OT_REG_HFP = 'h'
static const char OT_REG_DOUBLE = 'd'
static const char OT_IMM_BOOL = 'j'
static const char OT_IMM_INT = 'i'
static const char OT_IMM_FP = 'k'
static const char OT_IMM_HFP = 'l'
static const char OT_IMM_LONG = 'a'
static const char OT_VREG_BOOL = 'a'
static const char OT_VREG_INT8 = 'q'
static const char OT_VREG_INT16 = 't'
static const char OT_VREG_INT32 = 'u'
static const char OT_VREG_FP = 'e'
static const char OT_VREG_HFP = 'g'
Protected Types
enum RegType { GPR = 0 , RESERVED , ARGUMENT , RESULT }
enum RegsToProcess { ALL_REGISTERS , ONLY_EXTRAS , ONLY_LANES , ONLY_NORMAL }
typedef std::map< std::string, std::vector< std::string > > RegClassMap
Protected Member Functions
bool writeRegisterInfo (std::ostream &o)
void writeStartOfRegisterInfo (std::ostream &o)
void writeOperandDefs (std::ostream &o)
void writeIntegerImmediateDefs (std::ostream &o, const ImmInfo &iivis)
void writeMoveImmediateDefs (std::ostream &o)
void writeInstrInfo (std::ostream &o)
void writeBackendCode (std::ostream &o)
void writeTopLevelTD (std::ostream &o)
void writeInstrFormats (std::ostream &o)
bool checkRequiredRegisters ()
void analyzeRegisters ()
void analyzeRegisterFileClasses ()
void analyzeRegisters (RegsToProcess regsToProcess)
void gatherAllMachineOperations ()
void analyzeMachineVectorRegisterClasses ()
void analyzeMachineRegisters ()
void associateRegistersWithVectorRegisterClasses ()
void orderEqualWidthRegistersToRoundRobin ()
void verbose (const TCEString &msg) const
bool isVectorLoadOperation (const Operation &op) const
bool isVectorStoreOperation (const Operation &op) const
bool isWrongEndianessVectorOp (const Operation &op) const
bool isVectorBitwiseOperation (const Operation &op) const
bool hasRawOperands (const Operation &op) const
int subwordWidthOfRawData (const Operation &op) const
bool hasRegisterClassSupport (const Operation &op) const
bool hasRegisterClassSupport (const TDGenerator::ValueType &vt) const
TCEString associatedVectorRegisterClass (const Operand &operand) const
void writePatternReplacement (std::ostream &o, const TCEString &origPat, const TCEString &replacerPat) const
void writeOperationDefUsingGivenOperandTypes (std::ostream &o, Operation &op, bool skipPattern, std::vector< TDGenerator::ValueType > inputs, std::vector< TDGenerator::ValueType > outputs, TCEString instrSuffix="")
void writeRegisterDef (std::ostream &o, const RegInfo &reg, const std::string regName, const std::string regTemplate, const std::string aliases, RegType type)
void write64bitRegisterInfo (std::ostream &o)
void write32bitRegisterInfo (std::ostream &o)
void write16bitRegisterInfo (std::ostream &o)
void write8bitRegisterInfo (std::ostream &o)
void write1bitRegisterInfo (std::ostream &o)
void writeRARegisterInfo (std::ostream &o)
void writeGuardRegisterClassInfo (std::ostream &o)
void writeVectorRegisterBaseClasses (std::ostream &o) const
void writeVectorRegisterNames (std::ostream &o)
void writeVectorRegisterClasses (std::ostream &o) const
void writeVectorOperationDefs (std::ostream &o, Operation &op, bool skipPattern)
void writeVectorOperationDef (std::ostream &o, Operation &op, TCEString valueTypes, const TCEString &attributes, bool skipPattern)
void saveAdditionalVectorOperationInfo (const Operation &op, const TCEString &valueTypes, bool isRegisterOp)
void writeVectorMemoryOperationDefs (std::ostream &o, Operation &op, bool skipPattern)
void writeVectorBitwiseOperationDefs (std::ostream &o, Operation &op, bool skipPattern)
void writeVectorRegisterMoveDefs (std::ostream &o)
void writeVectorTruncStoreDefs (std::ostream &o) const
void writeScalarToVectorDefs (std::ostream &o) const
void writeVectorBitConversions (std::ostream &o) const
void writeScalarOperationExploitations (std::ostream &o)
void writeVectorLoadStoreOperationExploitations (std::ostream &o)
void writeWiderVectorOperationExploitations (std::ostream &o)
void genGeneratedTCEPlugin_getStore (std::ostream &o) const
void genGeneratedTCEPlugin_getLoad (std::ostream &o) const
void genGeneratedTCEPlugin_isVectorRegisterMove (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorValueType (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorBroadcastOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorPackOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorSelectOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorShuffle1Opcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorShuffle2Opcode (std::ostream &o) const
void genGeneratedTCEPlugin_getConstantVectorShuffleOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getExtractElemOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorShlSameOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorShrSameOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorShruSameOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorAndSameOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorIorSameOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorXorSameOpcode (std::ostream &o) const
void genTCETargetLoweringSIMD_addVectorRegisterClasses (std::ostream &o) const
void genTCETargetLoweringSIMD_associatedVectorRegClass (std::ostream &o) const
void genTCETargetLoweringSIMD_getSetCCResultVT (std::ostream &o) const
void genTCEInstrInfoSIMD_copyPhysVectorReg (std::ostream &o) const
void genGeneratedTCEPlugin_getVectorImmediateOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getGatherOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getLoadOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getAddOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getShlOpcode (std::ostream &o) const
void genGeneratedTCEPlugin_getIorOpcode (std::ostream &o) const
void writeVectorImmediateWriteDefs (std::ostream &instrInfoTD)
void createMinMaxDef (const TCEString &opName, const TCEString &valueName, std::ostream &os)
void createVectorMinMaxDef (const TCEString &opName, int bits, char llvmTypeChar, const TCEString &postFix, std::ostream &os)
void writeOperationDefs (std::ostream &o, Operation &op, bool skipPattern)
void writeOperationDef (std::ostream &o, Operation &op, const std::string &operandTypes, const std::string &attrs, bool skipPattern, std::string backendPrefix="")
std::string emulatingOpNodeLLVMName (const Operation &op, const OperationDAG &dag, const OperationNode &node, const std::string &operandTypes)
void writeEmulationPattern (std::ostream &o, const Operation &op, const OperationDAG &dag)
void write64bitMoveDefs (std::ostream &o)
void writeControlFlowInstrDefs (std::ostream &os)
void writeCondBranchDefs (std::ostream &os)
void writeCallDef (std::ostream &o)
void writeHWLoopDef (std::ostream &o)
virtual void writeCallDefRegs (std::ostream &o)
void writeRegisterClasses (std::ostream &o)
virtual TCEString llvmOperationPattern (const Operation &op, char operandType=' ') const
virtual TCEString llvmOperationName (const TCEString &opName) const
bool operationCanBeMatched (const Operation &op, std::set< std::string > *recursionCycleCheck=NULL, bool recursionHasStore=false)
bool operationDAGCanBeMatched (const OperationDAG &op, std::set< std::string > *recursionCycleCheck=NULL, bool recursionHasStore=false)
const OperationDAG * getMatchableOperationDAG (const Operation &op)
const std::vector< OperationDAG * > getMatchableOperationDAGs (const Operation &op)
std::string tceOperationPattern (const Operation &op)
std::string patOutputs (const Operation &op, const std::string &oprTypes)
std::string patInputs (const Operation &op, const std::string &oprTypes)
virtual std::string operandToString (const Operand &operand, bool match, char operandType, const std::string &immDefName="")
std::string operationNodeToString (const Operation &op, const OperationDAG &dag, const OperationNode &node, bool emulationPattern, const std::string &operandTypes)
std::string constantNodeString (const Operation &op, const OperationDAG &dag, const ConstantNode &node, const std::string &operandTypes, const OperationDAGNode *successor=nullptr)
std::string dagNodeToString (const Operation &op, const OperationDAG &dag, const OperationDAGNode &node, bool emulationPattern, const std::string &operandTypes, const Operation *emulatingOp=nullptr, const OperationDAGNode *successor=nullptr)
std::string operationPattern (const Operation &op, const OperationDAG &dag, const std::string &operandTypes)
virtual char operandChar (Operand &operand)
std::string createDefaultOperandTypeString (const Operation &op)
void writeVectorStoreDefs (std::ostream &o, const TCEString &opName, const TCEString &opNameSuffix, bool addrImm, const TCEString &dataType, bool writePredicatedVersions)
void genTCEInstrInfo_copyPhys64bitReg (std::ostream &o) const
void writeArgRegsArray (std::ostream &os)
virtual void createSelectPatterns (std::ostream &os)
void writeAddressingModeDefs (std::ostream &o)
void createByteExtLoadPatterns (std::ostream &os)
void createShortExtLoadPatterns (std::ostream &os)
void create32BitExtLoadPatterns (std::ostream &os)
void createEndiannesQuery (std::ostream &os)
void createConstantMaterializationQuery (std::ostream &os)
void createConstShiftPatterns (std::ostream &os)
void writeOperationDefs (std::ostream &o, Operation &op, const std::string &operandTypes, const std::string &attrs, bool skipPattern, std::string backendPrefix="")
void writeVectorStoreDefs (std::ostream &o, Operation &op, int vectorLen)
void writeVectorTruncStoreDefs (std::ostream &o, Operation &op, int bitsize, int vectorLen)
void createGetMaxMemoryAlignment (std::ostream &os) const
void writeVectorAnyextPattern (std::ostream &o, Operation &op, const TCEString &loadPatternName, int vectorLen)
void writeVectorLoadDefs (std::ostream &o, const TCEString &opName, const TCEString &opNameSuffix, bool addrImm, const TCEString &resultType, const TCEString &loadPatternName, bool writePredicatedVersions)
virtual void writeImmediateDef (std::ostream &o, const std::string &defName, const std::string &operandType, const std::string &predicate)
void writeInstrDef (std::ostream &o, const std::string &instrDefName, const std::string &outs, const std::string &ins, const std::string &asmString, const std::string &pattern)
void writeVectorLoadDefs (std::ostream &o, Operation &op, const TCEString &loadPatternName, int vectorLen)
void writeBooleanStorePatterns (std::ostream &os)
std::string immediatePredicate (int64_t lowerBoundInclusive, uint64_t upperBoundInclusive)
std::string immediateOperandNameForEmulatedOperation (const OperationDAG &, const Operand &operand)
bool areImmediateOperandsLegal (const Operation &operation, const std::string &operandTypes) const
void writeBroadcastDefs (std::ostream &o, Operation &op, int vectorLen)
bool writePortGuardedJumpDefPair (std::ostream &os, const TCEString &tceop1, const TCEString &tceop2, bool fp=false)
std::string subPattern (const Operation &op, const OperationDAG &dag)
OperationDAG * createTrivialDAG (Operation &op)
bool canBeImmediate (const OperationDAG &dag, const TerminalNode &node)
virtual void createMinMaxGenerator (std::ostream &os)
void writeCallSeqStart (std::ostream &os)
void writeMiscPatterns (std::ostream &o)
void generateLoadStoreCopyGenerator (std::ostream &os)
void createParamDRegNums (std::ostream &os)
virtual void createVectorRVDRegNums (std::ostream &os)
void writeCallingConv (std::ostream &os)
void writeCallingConvLicenceText (std::ostream &os)
void writeConstShiftPat (std::ostream &os, const TCEString &nodeName, const TCEString &opNameBase, int i)
void createBoolAndHalfLoadPatterns (std::ostream &os)
virtual void createConstantMaterializationPatterns (std::ostream &os)
void createBranchAnalysis (std::ostream &os)
void genTCERegisterInfo_setReservedVectorRegs (std::ostream &os) const
void writeGetPointerAdjustmentQuery (std::ostream &os) const
bool canBePredicated (Operation &op, const std::string &operandTypes)
TCEString getLLVMPatternWithConstants (const Operation &op, const std::string &operandTypes, const std::string &operand0, const std::string &operand1) const
std::string operandTypesToRegisters (const std::string &opdTypes) const
char operandTypeToRegister (const char &opdType) const
TCEString getMovePattern (const char &opdType, const std::string &inputPattern) const
void initializeBackendContents ()
Static Protected Member Functions
static std::vector< std::string > supportedStackAccessOperations (const TTAMachine::Machine &mach)
Protected Attributes
std::map< ImmInfoKey, std::string > immOperandDefs_
Maps (operation, operand) pairs to i32 immediate operand definition names.
const TTAMachine::Machine & mach_
ImmInfo * immInfo_
unsigned dregNum_
std::string registerInfo_
std::string addressingModeDefs_
std::string operandDefs_
std::string instrInfo_
std::string instrFormats_
std::string callingConv_
std::string argRegsArray_
std::string backendCode_
std::string topLevelTD_
OperationDAGSelector::OperationSet allOpNames_
Contains all operation names in upper case.
std::map< TCEString, Operation * > scalarOps_
Contains all scalar operations (<Name, Operation>).
std::map< TCEString, Operation * > vectorOps_
Contains all vector operations (<Name, Operation>).
std::map< int, TCEString > baseClasses_
Contains vector base classes for register files (<Width, Name>).
std::map< int, std::vector< TDGenerator::RegisterInfo > > registers_
Contains registers fit for being vector registers (<Width, Registers>).
std::map< TCEString, TDGenerator::RegisterClass > vRegClasses_
Contains required vector register classes (<ValueType, RegClass>).
std::map< TCEString, TDGenerator::InstructionInfo > registerStores_
All register store operations (<ValueType, InstrInfo>).
std::map< TCEString, TDGenerator::InstructionInfo > registerLoads_
All register load operations (<ValueType, InstrInfo>).
std::map< TCEString, TDGenerator::InstructionInfo > immediateStores_
All immediate store operations (<ValueType, InstrInfo>).
std::map< TCEString, TDGenerator::InstructionInfo > immediateLoads_
All immediate load operations (<ValueType, InstrInfo>).
std::map< TCEString, TCEString > packOperations_
Contains machine's PACK instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > vbcastOperations_
Contains machine's VBCAST instructions (<ValueType, InstrName>).
std::vector< std::pair< const Operation *, TCEString > > truncOperations_
Contains machine's TRUNCxx/CFH instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > vselectOperations_
Contains machine's VSELECT instructions (<instrName, ValueType>).
std::map< TCEString, TCEString > vshuffle1Operations_
Contains machine's VSHUFFLE1 instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > vshuffle2Operations_
Contains machine's VSHUFFLE2 instructions (<ValueType, InstrName>).
std::map< std::pair< TCEString, std::vector< int > >, TCEString > vcshuffleOperations_
Contains machine's VCSHUFFLE instructions (<<ValueType, ConstantSelects>, InstrName>).
std::map< TCEString, TCEString > extractElemOperations_
Contains machine's EXTRACTELEM instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > shlSameOperations_
Contains machine's SHLSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > shrSameOperations_
Contains machine's SHRSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > shruSameOperations_
Contains machine's SHRUSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > andSameOperations_
Contains machine's ANDSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > iorSameOperations_
Contains machine's IORSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > xorSameOperations_
Contains machine's XORSAME instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > gatherOperations_
Contains machine's GATHER instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > addOperations_
Contains machine's add instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > shlOperations_
Contains machine's shl instructions (<ValueType, InstrName>).
std::map< TCEString, TCEString > iorOperations_
Contains machine's shl instructions (<ValueType, InstrName>).
std::set< TCEString > movOperations_
Contains all moves between register classes (<InstrName>).
std::vector< RegInfo > regs1bit_
std::vector< RegInfo > regs8bit_
std::vector< RegInfo > regs16bit_
std::vector< RegInfo > regs32bit_
std::vector< RegInfo > regs64bit_
std::vector< std::string > llvmGuardRegs_
The LLVM register defs used as guards.
std::map< std::string, RegInfo > regs_
Map of generated llvm register names to physical register in the machine.
std::vector< std::string > argRegNames_
std::vector< std::string > resRegNames_
std::vector< std::string > gprRegNames_
std::map< std::string, std::string > opNames_
std::map< std::string, std::string > truePredOps_
std::map< std::string, std::string > falsePredOps_
int maxVectorSize_
int highestLaneInt_
int highestLaneBool_
bool hasExBoolRegs_
bool hasExIntRegs_
bool hasSelect_
bool hasConditionalMoves_
int maxScalarWidth_
bool littleEndian_
unsigned int argRegCount_
unsigned int requiredI32Regs_
Minimum number of 32 bit registers.
unsigned int requiredI64Regs_
bool prebypassStackIndeces_
bool use64bitForFP_
std::set< RegInfo > guardedRegs_
List of register that are associated with a guard on a bus.
std::set< const TTAMachine::RegisterFile *, TTAMachine::MachinePart::Comparator > tempRegFiles_
Register files whose last reg reserved for temp reg copies.
RegClassMap regsInClasses_
All registers in certain group.
RegClassMap regsInRFClasses_
std::vector< std::string > constantMaterializationPredicates_
All predicates used in constant materialization patterns.
Static Protected Attributes
static const int FP_SUBW_WIDTH
Float type subword width.
static const int HFP_SUBW_WIDTH
Half float type subword width.
static const int BOOL_SUBW_WIDTH
Bool type subword width.
static const int MAX_SCALAR_WIDTH = 64
Distincts wide vs scalar registers.
static const int MAX_SUBW_COUNT = SIMD_WORD_WIDTH / BYTE_BITWIDTH
Maximum number of subwords that any SIMD operation can have.
static const bool EXPLOIT_BIGGER_REGISTERS = true
If set to true, smaller vector value types can be stored to larger register files, e.g. v4i8 vectors can be stored to registers that are over 32 bits in size.
static const std::map< TCEString, TCEString > OPERATION_PATTERNS_
Contains <BaseOpName, OpPattern> key-value pairs.
static const std::string guardRegTemplateName = "Guard"
Detailed Description
TCE Backend plugin source code and .td definition generator.
Generates files for building target architecture plugin for LLVM-TCE backend. This version generates the backend files for the "RISC instruction set style" output and provides useful methods.
Definition at line 77 of file TDGen.hh.
Member Typedef Documentation
RegClassMap
typedef std::map<std::string, std::vector<std::string> > TDGen::RegClassMap protected
Definition at line 643 of file TDGen.hh.
Member Enumeration Documentation
RegsToProcess
enum TDGen::RegsToProcess protected
Enumerator
ALL_REGISTERS
ONLY_EXTRAS
ONLY_LANES
ONLY_NORMAL
Definition at line 127 of file TDGen.hh.
                       {
        ALL_REGISTERS,
        ONLY_EXTRAS,
        ONLY_LANES,
        ONLY_NORMAL
    };
RegType
enum TDGen::RegType protected
Enumerator
GPR
RESERVED
ARGUMENT
RESULT
Definition at line 97 of file TDGen.hh.
                 {
        GPR = 0,
        RESERVED,
        ARGUMENT,
        RESULT
    };
Constructor & Destructor Documentation
TDGen()
TDGen::TDGen (const TTAMachine::Machine & mach, bool initialize = true)
Constructor.
Parameters
mach Machine to generate plugin for.
Definition at line 341 of file TDGen.cc.
                                                           :
    mach_(mach), immInfo_(NULL), dregNum_(0), maxVectorSize_(0),
    highestLaneInt_(-1), highestLaneBool_(-1),
    hasExBoolRegs_(false), hasExIntRegs_(false), hasSelect_(false),
    littleEndian_(mach.isLittleEndian()),
    argRegCount_(1),
    requiredI32Regs_(0), requiredI64Regs_(0), prebypassStackIndeces_(false),
    use64bitForFP_(false) {
    // These are TTA-specific, which we don't want to run for other targets
    if (initialize) {
        tempRegFiles_ = MachineConnectivityCheck::tempRegisterFiles(mach);
        prebypassStackIndeces_ = false;
        if (mach.is64bit()) {
            std::set<int> scalarWidths { 1, 32 };
            hasConditionalMoves_ =
                MachineConnectivityCheck::hasConditionalMoves(mach_, scalarWidths);
            // TODO: this does not make sense! requires more!
            requiredI64Regs_ = 0;
            requiredI64Regs_ += argRegCount_;
        } else {
            std::set<int> scalarWidths { 1, 32 };
            hasConditionalMoves_ =
                MachineConnectivityCheck::hasConditionalMoves(mach_, scalarWidths);
            // TODO: this does not make sense! requires more!
            requiredI32Regs_ = 0;
            requiredI32Regs_ += argRegCount_;
        }
        immInfo_ = ImmediateAnalyzer::analyze(mach_);
        maxScalarWidth_ = mach.is64bit() ? 64 : 32;
        initializeBackendContents();
    }
}
References ImmediateAnalyzer::analyze(), argRegCount_, MachineConnectivityCheck::hasConditionalMoves(), hasConditionalMoves_, immInfo_, initializeBackendContents(), TTAMachine::Machine::is64bit(), mach_, maxScalarWidth_, prebypassStackIndeces_, requiredI32Regs_, requiredI64Regs_, tempRegFiles_, and MachineConnectivityCheck::tempRegisterFiles().
~TDGen()
TDGen::~TDGen () virtual
Destructor.
Definition at line 383 of file TDGen.cc.
              {
    if (immInfo_ != NULL) {
        delete immInfo_;
    }
}
References immInfo_.
Member Function Documentation
analyzeMachineRegisters()
void TDGen::analyzeMachineRegisters () protected
Groups all registers in the machine by register width.
Goes through register files and sorts all real machine registers into <Width, vector<Register>> groups. A base class for each Width is also created.
Todo:
Apparently TDGen does not write information of 8 bit registers -> can't add them.
Definition at line 1478 of file TDGen.cc.
{
    const TTAMachine::Machine::RegisterFileNavigator nav =
        mach_.registerFileNavigator();
    std::map<int, std::vector<RegisterInfo>>::iterator it;
    // Go through every register file in the machine.
    for (int i = 0; i < nav.count(); i++) {
        const TTAMachine::RegisterFile* rf = nav.item(i);
        assert(rf != NULL);
        // Check that the registerfile has both input and output ports.
        bool hasInput = false;
        bool hasOutput = false;
        for (int p = 0; p < rf->portCount(); p++) {
            if (rf->port(p)->isInput()) hasInput = true;
            if (rf->port(p)->isOutput()) hasOutput = true;
        }
        if (!hasInput) {
            if (Application::verboseLevel() >
                Application::VERBOSE_LEVEL_DEFAULT) {
                Application::logStream()
                    << "Warning: Skipping register file '"
                    << rf->name()
                    << "': no input ports."
                    << std::endl;
            }
            continue;
        }
        if (!hasOutput) {
            if (Application::verboseLevel() >
                Application::VERBOSE_LEVEL_DEFAULT) {
                Application::logStream()
                << "Warning Skipping register file '"
                << rf->name()
                << "': no output ports."
                << std::endl;
            }
            continue;
        }
        int rfWidth = rf->width();
        // If there is no entry for the width of the registers, create one.
        if (registers_.find(rfWidth) == registers_.end()) {
            registers_.insert(
                std::make_pair(rfWidth, std::vector<RegisterInfo>()));
        }
        it = registers_.find(rfWidth);
        std::vector<RegisterInfo>& registers = it->second;
        // Skip scalar size registers, they have been listed in TDGen.
        if (rfWidth > MAX_SCALAR_WIDTH) {
            // Kludge fix: Machines with >32 bit regs but without any vector
            // operations generates register info td file with 64 bit register
            // definition which are not associated to any register class.
            // This triggers assertion in LLVM side.
            if (vRegClasses_.empty()) continue;
            int lastIdx = rf->size();
            bool isTempRegRf = AssocTools::containsKey(tempRegFiles_, rf);
            if (isTempRegRf) {
                // If the machine is not enough connected,
                // preserve last register
                // of all register files for routing values.
                lastIdx--;
            }
            // Associate register file's registers with the width.
            for (int index = 0; index < lastIdx; ++index) {
                TCEString regName(
                    rf->name() + "_" + Conversion::toString(index));
                RegisterInfo reg(regName, rf->name(), index, rfWidth);
                registers.push_back(reg);
            }
        }
    }
    orderEqualWidthRegistersToRoundRobin();
    // TDGen has hardcoded register name definitions, some
    // inspection needs to be done to create correct register names.
    std::vector<RegisterInfo> regs1bit;
    for (size_t i = 0; i < regs1bit_.size(); ++i) {
        RegisterInfo reg(
            "B" + Conversion::toString(i),
            regs1bit_[i].rf,
            regs1bit_[i].idx,
            1);
        regs1bit.push_back(reg);
    }
    registers_[1] = regs1bit;
    /// @todo Apparently TDGen does not write information of  8 bit
    /// registers -> can't add them.
    std::vector<RegisterInfo> regs16bit;
    for (size_t i = 0; i < regs16bit_.size(); ++i) {
        RegisterInfo reg(
            "H" + Conversion::toString(i),
            regs16bit_[i].rf,
            regs16bit_[i].idx,
            16);
        if (i == 0) {
            reg.regName_ = "HIRES0";
        }
        regs16bit.push_back(reg);
    }
    registers_[16] = regs16bit;
    std::vector<RegisterInfo> regs32bit;
    for (size_t i = 0; i < regs32bit_.size(); ++i) {
        RegisterInfo reg(
            "I" + Conversion::toString(i),
            regs32bit_[i].rf,
            regs32bit_[i].idx,
            32);
        if (!mach_.is64bit()) {
            if (i == 0) {
                reg.regName_ = "SP";
            } else if (i == 1) {
                reg.regName_ = "IRES0";
            } else if (i == 2) {
                reg.regName_ = "FP";
            } else if (i == 3) {
                reg.regName_ = "KLUDGE_REGISTER";
            } else if (i < argRegCount_ + 3) {
                reg.regName_ = "A" + Conversion::toString(i);
            }
        }
        regs32bit.push_back(reg);
    }
    registers_[32] = regs32bit;
    std::vector<RegisterInfo> regs64bit;
    for (size_t i = 0; i < regs64bit_.size(); ++i) {
        RegisterInfo reg(
            "L" + Conversion::toString(i),
            regs64bit_[i].rf,
            regs64bit_[i].idx,
            64);
        if (mach_.is64bit()) {
            if (i == 0) {
                reg.regName_ = "SP";
            } else if (i == 1) {
                reg.regName_ = "IRES0";
            } else if (i == 2) {
                reg.regName_ = "FP";
            } else if (i == 3) {
                reg.regName_ = "KLUDGE_REGISTER";
            } else if (i < argRegCount_ + 3) {
                reg.regName_ = "A" + Conversion::toString(i);
            }
        }
        regs64bit.push_back(reg);
    }
    registers_[64] = regs64bit;
    // Create base classes for different register widths.
    for (it = registers_.begin(); it != registers_.end(); ++it) {
        int width = it->first;
        if (width > MAX_SCALAR_WIDTH) {
            baseClasses_.insert(
                std::make_pair(width, "VR" + Conversion::toString(width)));
        } else {
            baseClasses_.insert(
                std::make_pair(width, "R" + Conversion::toString(width)));
        }
    }
}
References argRegCount_, assert, baseClasses_, AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::is64bit(), TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), TTAMachine::Machine::Navigator< ComponentType >::item(), Application::logStream(), mach_, MAX_SCALAR_WIDTH, TTAMachine::Component::name(), orderEqualWidthRegistersToRoundRobin(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), TTAMachine::Machine::registerFileNavigator(), registers_, TDGenerator::RegisterInfo::regName_, regs16bit_, regs1bit_, regs32bit_, regs64bit_, TTAMachine::BaseRegisterFile::size(), tempRegFiles_, Conversion::toString(), Application::VERBOSE_LEVEL_DEFAULT, Application::verboseLevel(), vRegClasses_, and TTAMachine::BaseRegisterFile::width().
Referenced by writeRegisterInfo().
analyzeMachineVectorRegisterClasses()
void TDGen::analyzeMachineVectorRegisterClasses () protected
Creates vector register classes required by the machine.
The function goes through all operations and lists all different vector operand value types, after which a register class is created for each vector value type to support the vector value type.
Definition at line 1282 of file TDGen.cc.
{
    OperationPool opPool;
    // Has all vector value types (e.g. "v4i32", "v16i8", "v2f16", "v8f32")
    // that can be found among all the operands present in the machine.
    // Register classes will be defined based on these vector value types.
    std::set<TCEString> reqRegClassTypes;
    // List all existing vector value types in the machine.
    OperationDAGSelector::OperationSet::iterator opnIt;
    for (opnIt = allOpNames_.begin(); opnIt != allOpNames_.end(); ++opnIt) {
        Operation& op = opPool.operation((*opnIt).c_str());
        if (&op == &NullOperation::instance()) {
            continue;
        }
        // Go through every operand of the operation.
        for (int i = 1; i <= op.operandCount(); ++i) {
            Operand& operand = op.operand(i);
            // We are only interested in vector operands, skip otherwise.
            if (!operand.isVector()) {
                continue;
            }
            TCEString vtStr = ValueType::valueTypeStr(operand);
            if (vRegClasses_.find(vtStr) == vRegClasses_.end()) {
                reqRegClassTypes.insert(vtStr);
            }
            // If operand type is "raw" and vector subword width matches
            // float or half float width, list it also.
            if (operand.type() == Operand::RAW_DATA &&
                (operand.elementWidth() == FP_SUBW_WIDTH ||
                 operand.elementWidth() == HFP_SUBW_WIDTH)) {
                ValueType vt(operand);
                vt.isFloat_ = true;
                const TCEString floatVtStr = vt.valueTypeStr();
                if (vRegClasses_.find(floatVtStr) == vRegClasses_.end()) {
                    reqRegClassTypes.insert(floatVtStr);
                }
            }
        }
    }
    // Now we have listed all differend vector value types from the machine.
    // Create a register class for every LLVM supported vector value type.
    std::set<TCEString>::iterator it;
    for (it = reqRegClassTypes.begin(); it != reqRegClassTypes.end(); ++it) {
        const TCEString& vtStr = *it;
        const ValueType vt(vtStr);
        if (vt.isSupportedByLLVM()) {
            TCEString name = "V" + Conversion::toString(vt.subwCount_);
            if ((vt.isFloat_ && vt.subwWidth_ == FP_SUBW_WIDTH) ||
                (vt.isFloat_ && vt.subwWidth_ == HFP_SUBW_WIDTH)) {
                name += "F";
            } else {
                name += "I";
            }
            name += Conversion::toString(vt.subwWidth_) + "Regs";
            RegisterClass newRegClass(vt, name);
            vRegClasses_.insert(std::make_pair(vtStr, newRegClass));
        } else {
            verbose("Warning: RegisterClass not created for type: " + vtStr);
        }
    }
}
References allOpNames_, Operand::elementWidth(), FP_SUBW_WIDTH, HFP_SUBW_WIDTH, NullOperation::instance(), TDGenerator::ValueType::isFloat_, TDGenerator::ValueType::isSupportedByLLVM(), Operand::isVector(), Operation::operand(), Operation::operandCount(), OperationPool::operation(), Operand::RAW_DATA, TDGenerator::ValueType::subwCount_, TDGenerator::ValueType::subwWidth_, Conversion::toString(), Operand::type(), TDGenerator::ValueType::valueTypeStr(), verbose(), and vRegClasses_.
Referenced by writeRegisterInfo().
analyzeRegisterFileClasses()
void TDGen::analyzeRegisterFileClasses () protected
analyzeRegisters() [1/2]
void TDGen::analyzeRegisters () protected
Iterates through all registers in the machine and adds register information to the register sets.
Definition at line 838 of file TDGen.cc.
{
    const TTAMachine::Machine::BusNavigator busNav =
        mach_.busNavigator();
    // Check which registers have guards and put their info in
    // guardedRegs_ set.
    for (int i = 0; i < busNav.count(); i++) {
        const TTAMachine::Bus& bus = *busNav.item(i);
        for (int g = 0; g < bus.guardCount(); g++) {
            const TTAMachine::RegisterGuard* rg =
                dynamic_cast<const TTAMachine::RegisterGuard*>(bus.guard(g));
            if (rg != NULL) {
                RegInfo reg = {
                    rg->registerFile()->name(),
                    (unsigned)rg->registerIndex() };
                guardedRegs_.insert(reg);
            }
        }
    }
    const TTAMachine::Machine::RegisterFileNavigator nav =
        mach_.registerFileNavigator();
    bool regsFound = true;
    int currentIdx = 0;
    while (regsFound) {
        regsFound = false;
        for (int i = 0; i < nav.count(); i++) {
            const TTAMachine::RegisterFile* rf = nav.item(i);
            // Skip definition for registers that are marked as 'reserved'
            if (rf->isReserved()) continue;
            // Skip the 0th index of a register file with zero register flag
            if (currentIdx == 0 && rf->zeroRegister()) {
                regsFound = true;
                continue;
            }
            // Check that the registerfile has both input and output ports.
            bool hasInput = false;
            bool hasOutput = false;
            for (int p = 0; p < rf->portCount(); p++) {
                if (rf->port(p)->isInput()) hasInput = true;
                if (rf->port(p)->isOutput()) hasOutput = true;
            }
            if (!hasInput) {
                if (Application::verboseLevel() >
                    Application::VERBOSE_LEVEL_DEFAULT) {
                    Application::logStream()
                        << "Warning: Skipping register file '"
                        << rf->name()
                        << "': no input ports."
                        << std::endl;
                }
                continue;
            }
            if (!hasOutput) {
                if (Application::verboseLevel() >
                    Application::VERBOSE_LEVEL_DEFAULT) {
                    Application::logStream()
                        << "Warning Skipping register file '"
                        << rf->name()
                        << "': no output ports."
                        << std::endl;
                }
                continue;
            }
            unsigned width = rf->width();
            std::vector<RegInfo>* ri = NULL;
            if (width == 64) ri = &regs64bit_;
            else if (width == 32) ri = &regs32bit_;
            //else if (width == 16) ri = &regs16bit_;
            else if (width == 8) ri = &regs8bit_;
            else if (width == 1) ri = &regs1bit_;
            else {
                continue;
            }
            int lastIdx = rf->size();
            // todo: find a good solution to use just one big rf for this.
            bool isTempRegRf = AssocTools::containsKey(tempRegFiles_, rf);
            if (isTempRegRf) {
                // If the machine is not enough connected,
                // preserve last register
                // of all register files for routing values.
                lastIdx--;
            }
            // leave some 32bit regs unallocated for the post pass scheduler's
            // register renamer
            if (width == 32) {
                int renamerRegs = rf->size() * REG_RENAMER_PART / 100;
                lastIdx -= renamerRegs;
            }
            if (currentIdx < lastIdx) {
                RegInfo reg = {rf->name(), (unsigned)currentIdx};
                if (!(width == 32 &&
                    guardedRegs_.find(reg) != guardedRegs_.end())) {
                    ri->push_back(reg);
                }
                regsFound = true;
            }
        }
        currentIdx++;
    }
}
References TTAMachine::Machine::busNavigator(), AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), guardedRegs_, TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), TTAMachine::RegisterFile::isReserved(), TTAMachine::Machine::Navigator< ComponentType >::item(), Application::logStream(), mach_, TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), REG_RENAMER_PART, TTAMachine::RegisterGuard::registerFile(), TTAMachine::Machine::registerFileNavigator(), TTAMachine::RegisterGuard::registerIndex(), regs1bit_, regs32bit_, regs64bit_, regs8bit_, TTAMachine::BaseRegisterFile::size(), tempRegFiles_, Application::VERBOSE_LEVEL_DEFAULT, Application::verboseLevel(), TTAMachine::BaseRegisterFile::width(), and TTAMachine::RegisterFile::zeroRegister().
Referenced by writeRegisterInfo().
analyzeRegisters() [2/2]
void TDGen::analyzeRegisters (RegsToProcess regsToProcess) protected
areImmediateOperandsLegal()
bool TDGen::areImmediateOperandsLegal (const Operation & operation, const std::string & operandTypes) const protected
Checks if the operation can have the specified immediate operands.
Definition at line 7617 of file TDGen.cc.
{
    assert(static_cast<int>(operandTypes.size()) >= operation.operandCount());
    for (int i = 0 ; i < operation.numberOfInputs(); i++) {
        if (operandTypes.at(i + operation.numberOfOutputs()) != OT_IMM_INT) {
            continue;
        }
        const Operand& operand = operation.operand(i+1);
        // Kludge fix for ADDri/MEMri operands. LLVM wants some times to select
        // store/load instruction, where the address operand is immediate.
        // However, the machine may not have capability to directly transport
        // immediate to the address operand. Considering the case as illegal
        // will reject operation definitions using ADDri/MEMri operands and
        // breaks the instruction selection later on. Temporarily accept
        // ADDri/MEMri operands until the issue is fixed.
        if (operand.isAddress()) {
            continue;
        }
        if (immInfo_->count(operation, operand) == 0) {
            for (int swappableWith : operand.swap()) {
                const Operand& otherOperand = operation.operand(swappableWith);
                if (immInfo_->count(operation, otherOperand)
                    && operation.name() != "EQ"
                    && operation.name() != "NE") {
                    // ^ EQ and NE are not commutative in LLVM
                    return true;
                }
            }
            return false;
        }
    }
    return true;
}
References assert, ImmInfo::count(), immInfo_, Operand::isAddress(), Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), Operation::operandCount(), OT_IMM_INT, and Operand::swap().
Referenced by writeOperationDef().
associatedVectorRegisterClass()
TCEString TDGen::associatedVectorRegisterClass (const Operand & operand) const protected
Returns the name of the vector class that supports given operand.
Parameters
operand Checked if any register class supports value type of this.
Returns
Name of the register class that supports operand's value type.
Definition at line 1842 of file TDGen.cc.
{
    std::map<TCEString, RegisterClass>::const_iterator it =
        vRegClasses_.find(ValueType::valueTypeStr(operand));
    if (it == vRegClasses_.end()) {
        // Shouldn't get here because any operation whose operands are not
        // supported will not get created.
        assert(false);
    }
    const RegisterClass& regClass = it->second;
    return regClass.name();
}
References assert, TDGenerator::RegisterClass::name(), TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
Referenced by operandToString().
associateRegistersWithVectorRegisterClasses()
void TDGen::associateRegistersWithVectorRegisterClasses () protected
Attaches proper register groups to register files.
Definition at line 1709 of file TDGen.cc.
{
    std::map<TCEString, RegisterClass>::iterator rcIt;
    for (rcIt = vRegClasses_.begin(); rcIt != vRegClasses_.end(); ++rcIt) {
        RegisterClass& regClass = rcIt->second;
        // Go through all register groups (they are in ascending order by
        // width -> starts from the smallest width always towards wider ones).
        std::map<int, std::vector<RegisterInfo>>::iterator regsIt =
            registers_.begin();
        bool found = false;
        while (!found && regsIt != registers_.end()) {
            int regsWidth = regsIt->first;
            size_t amountOfRegs = (regsIt->second).size();
            // If can find a group of registers which satisfies the
            // register class width requirement, choose those registers.
            if (regsWidth >= regClass.valueType().width() &&
                amountOfRegs > 0) {
                const std::vector<RegisterInfo>& regs = regsIt->second;
                regClass.addRegisters(regs);
                found = true;
            }
            ++regsIt;
        }
        // If bigger register exploitation is desired, append all the rest
        // of the registers, because there are only wider registers left.
        if (EXPLOIT_BIGGER_REGISTERS) {
            while (regsIt != registers_.end()) {
                const std::vector<RegisterInfo>& biggerRegs = regsIt->second;
                regClass.addRegisters(biggerRegs);
                ++regsIt;
            }
        }
    }
}
References TDGenerator::RegisterClass::addRegisters(), EXPLOIT_BIGGER_REGISTERS, registers_, TDGenerator::RegisterClass::valueType(), vRegClasses_, and TDGenerator::ValueType::width().
Referenced by writeRegisterInfo().
canBeImmediate()
bool TDGen::canBeImmediate (const OperationDAG & dag, const TerminalNode & node) protected
Returns true if the operand corresponding to the given TerminalNode in an OperationDAG can be immediate in the llvm pattern.
Parameters
dag DAG of the whole operation.
node TerminalNode corresponding to the operand queried.
Definition at line 6123 of file TDGen.cc.
{
    if (dag.inDegree(node) != 0) {
        return false;
    }
    for (int i = 0; i < dag.outDegree(node); i++) {
        const OperationDAGEdge& edge = dag.outEdge(node, i);
        const OperationDAGNode& dstNode = dag.headNode(edge);
        const OperationNode* opNode =
            dynamic_cast<const OperationNode*>(&dstNode);
        if (opNode == NULL) {
            return false;
        }
    }
    return true;
}
References BoostGraph< GraphNode, GraphEdge >::headNode(), BoostGraph< GraphNode, GraphEdge >::inDegree(), BoostGraph< GraphNode, GraphEdge >::outDegree(), and BoostGraph< GraphNode, GraphEdge >::outEdge().
Referenced by dagNodeToString().
canBePredicated()
bool TDGen::canBePredicated (Operation & op, const std::string & operandTypes) protected
Returns true if the instruction can be predicated.
TODO
Definition at line 7665 of file TDGen.cc.
{
    // Predicating operands with immediates can currently lead to
    // unschedulable code in case there's no bus that has both the
    // predicate and the immediate transfer capability. Disable
    // generating the predicated versions for immediate operand
    // patterns for now.
    if (operandTypes.find(OT_IMM_INT) != std::string::npos) return false;
    if (hasConditionalMoves_) return true;
    return false;
}
References hasConditionalMoves_, and OT_IMM_INT.
Referenced by writeOperationDef().
checkRequiredRegisters()
bool TDGen::checkRequiredRegisters () protected
Checks that the target machine has required registers to build a usable plugin.
Returns
True if required registers were found, false if not.
Definition at line 3336 of file TDGen.cc.
{
    if (!mach_.is64bit() && regs32bit_.size() < requiredI32Regs_) {
        std::string msg =
            (boost::format(
                "Architecture doesn't meet the minimal requirements.\n"
                "Only %d 32-bit general purpose registers found. At least %d\n"
                "needed.")
                % regs32bit_.size() % requiredI32Regs_)
            .str();
        if (tempRegFiles_.size() > 0) {
            msg += "Your machine is not fully connected, thus one register\n"
                "from each register file are reserved for temp moves and\n"
                "not used as general purpose registers.";
        }
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
        return false;
    }
    if (regs64bit_.size() < requiredI64Regs_) {
        std::string msg =
            (boost::format(
                "Architecture doesn't meet the minimal requirements.\n"
                "Only %d 64-bit general purpose registers found. At least %d\n"
                "needed. ")
             % regs64bit_.size() % requiredI64Regs_)
            .str();
        if (tempRegFiles_.size() > 0) {
            msg += "Your machine is not fully connected, thus one register\n"
                "from each register file is reserved for temp moves and\n"
                "not used as general purpose registers.";
        }
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
        return false;
    }
    return true;
}
References __func__, TTAMachine::Machine::is64bit(), mach_, regs32bit_, regs64bit_, requiredI32Regs_, requiredI64Regs_, and tempRegFiles_.
Referenced by writeRegisterInfo().
constantNodeString()
std::string TDGen::constantNodeString (const Operation & op, const OperationDAG & dag, const ConstantNode & node, const std::string & operandTypes, const OperationDAGNode * successor = nullptr) protected
Definition at line 5611 of file TDGen.cc.
{
    assert(dag.inDegree(node) == 0);
    assert(dag.outDegree(node) == 1 || successor);
    const OperationDAGNode& succ = successor ?
        *successor : dag.headNode(dag.outEdge(node,0));
    const OperationNode* opn = dynamic_cast<const OperationNode*>(&succ);
    OperationDAG::NodeSet siblings = dag.predecessors(*opn);
    for (OperationDAG::NodeSet::iterator i = siblings.begin();
         i!= siblings.end(); i++) {
        const TerminalNode* tNode = dynamic_cast<const TerminalNode*>(*i);
        if (tNode != NULL) {
            const Operand& operand = op.operand(tNode->operandIndex());
            assert(operand.isInput());
            char operandType =
                operandTypes[operand.index()-1 + op.numberOfOutputs()];
            // Retrieve largest short immediate for the operand.
            switch (operandType) {
            case OT_REG_BOOL:
            case OT_IMM_BOOL:
                return "(i1 " + Conversion::toString(node.value()) + ")";
            case OT_REG_DOUBLE:
                return "(f64 " + Conversion::toString(node.value()) +")";
            case OT_REG_HFP:
                return "(f16 " + Conversion::toString(node.value()) + ")";
                // TODO: f16 vectors not yet implemented
            case OT_REG_FP:
            case OT_IMM_FP:
                return "(f32 " + Conversion::toString(node.value()) + ")";
            case OT_REG_LONG:
            case OT_IMM_LONG:
                return "(i64 " + Conversion::toString(node.value()) + ")";
            case OT_REG_INT:
            case OT_IMM_INT:
                return mach_.is64bit() ?
                    "(i64 " + Conversion::toString(node.value()) + ")":
                    "(i32 " + Conversion::toString(node.value()) + ")";
            default:
                break;
            }
        }
    }
    // TODO: Declaring without type specifier is not valid?
    // The constnode would return this if it is the outer most op in the dag
    return mach_.is64bit() ?
                    "(i64 " + Conversion::toString(node.value()) + ")":
                    "(i32 " + Conversion::toString(node.value()) + ")";
}
References assert, BoostGraph< GraphNode, GraphEdge >::headNode(), BoostGraph< GraphNode, GraphEdge >::inDegree(), Operand::index(), TTAMachine::Machine::is64bit(), Operand::isInput(), mach_, Operation::numberOfOutputs(), Operation::operand(), TerminalNode::operandIndex(), OT_IMM_BOOL, OT_IMM_FP, OT_IMM_INT, OT_IMM_LONG, OT_REG_BOOL, OT_REG_DOUBLE, OT_REG_FP, OT_REG_HFP, OT_REG_INT, OT_REG_LONG, BoostGraph< GraphNode, GraphEdge >::outDegree(), BoostGraph< GraphNode, GraphEdge >::outEdge(), BoostGraph< GraphNode, GraphEdge >::predecessors(), Conversion::toString(), and ConstantNode::value().
Referenced by dagNodeToString().
create32BitExtLoadPatterns()
void TDGen::create32BitExtLoadPatterns (std::ostream & os) protected
Definition at line 6808 of file TDGen.cc.
{
    TCEString load = "LD32";
    const TCEString uload = "LDU32";
    TCEString ZXOP = "ZXW64";
    TCEString ZXOPC = "ZXW64ss";
    if (mach_.hasOperation(load)) {
        if (!mach_.hasOperation(uload)) {
            if (!mach_.hasOperation(ZXOP)) {
                // emulate zero ext with sing-ext and and
                os << "def : Pat<(i64 (zextloadi32 ADDRrr:$addr)), "
                   << "(AND64ssa (LD32ss ADDRrr:$addr),"
                   << "0xffffffff)>;" << std::endl;
                os << "def : Pat<(i64 (zextloadi32 ADDRri:$addr)), "
                   << "(AND64ssa (LD32sa ADDRri:$addr),"
                   << "0xffffffff)>;" << std::endl;
            } else {
                // use zxw64 instr for zext
                os << "def : Pat<(i64 (zextloadi32 ADDRrr:$addr)), "
                   << "(" << ZXOPC << " (LD32ss ADDRrr:$addr))>;" <<std::endl;
                os << "def : Pat<(i64 (zextloadi32 ADDRri:$addr)), "
                   << "(" << ZXOPC << " (LD32sa ADDRri:$addr))>;" <<std::endl;
            }
        }
    } else {
        if (!mach_.hasOperation(uload)) {
            std::cerr << "Warning: The architecture is missing any 16-bit loads."
                      << std::endl;
            return;
        }
        load = uload;
        if (mach_.hasOperation("SXW64")) {
            // use zextload + sext for sextload
            os << "def : Pat<(i64 (sextloadi32 ADDRrr:$addr)), "
               << "(SXW64ss (LDU32ss ADDRrr:$addr))>;" << std::endl;
            os << "def : Pat<(i64 (sextloadi32 ADDRri:$addr)), "
               << "(SXW64ss (LDU32sa ADDRri:$addr))>;" << std::endl;
        } else {
            std::cerr << "Warning: no sign-extending 32-bit loads or"
                      << " 32-bit sign extension instruction!"
                      << " in the processor. All code may not compile!"
                      << std::endl;
        }
    }
    // anyext.
    os << "def : Pat<(i64 (extloadi32 ADDRrr:$src)), "
       << "(" << load << "ss ADDRrr:$src)>;" << std::endl
       << "def : Pat<(i64 (extloadi32 ADDRri:$src)), "
       << "(" << load << "sa ADDRrr:$src)>;" << std::endl;
}
References TTAMachine::Machine::hasOperation(), and mach_.
Referenced by writeInstrInfo().
createBoolAndHalfLoadPatterns()
void TDGen::createBoolAndHalfLoadPatterns (std::ostream & os) protected
Definition at line 8608 of file TDGen.cc.
{
    // TODO: what about true/false versions of these ops?
    TCEString load = littleEndian_ ? "LD8" : "LDQ";
    TCEString uload = littleEndian_ ? "LDU8" : "LDQU";
    TCEString wload = littleEndian_ ?
        (mach_.is64bit() ? "LD64" : "LD32") : "LDW";
    if (mach_.hasOperation(load)) {
        os << "def " << load
           << "Br : InstTCE<(outs R1Regs:$op2), (ins MEMrr:$op1), \"\", "
           << "[(set R1Regs:$op2, (sextloadi1 ADDRrr:$op1))]>;" << std::endl
           << "def " << load
           << "Bi : InstTCE<(outs R1Regs:$op2), (ins MEMri:$op1), \"\", "
           << "[(set R1Regs:$op2, (sextloadi1 ADDRri:$op1))]>; " << std::endl;
        opNames_[load + "Br"] = load;
        opNames_[load + "Bi"] = load;
    }
    if (mach_.hasOperation(uload)) {
        os << "def " << uload
           << "Br : InstTCE<(outs R1Regs:$op2), (ins MEMrr:$op1), \"\", "
           << "[(set R1Regs:$op2, (zextloadi1 ADDRrr:$op1))]>;" << std::endl
           << "def " << uload
           << "Bi : InstTCE<(outs R1Regs:$op2), (ins MEMri:$op1), \"\", "
           << "[(set R1Regs:$op2, (zextloadi1 ADDRri:$op1))]>;" << std::endl;
        opNames_[uload + "Br"] = uload;
        opNames_[uload + "Bi"] = uload;
        os << "def : Pat<(i1 (load ADDRrr:$addr)), ("
           << uload << "Br ADDRrr:$addr)>;" << std::endl;
        os << "def : Pat<(i1 (load ADDRri:$addr)), ("
           << uload << "Bi ADDRri:$addr)>;" << std::endl;
    } else {
        if (mach_.hasOperation(load)) {
            os << "def : Pat<(i1 (load ADDRrr:$addr)), ("
               << load << "Br ADDRrr:$addr)>;" << std::endl;
            os << "def : Pat<(i1 (load ADDRri:$addr)), ("
               << load << "Bi ADDRri:$addr)>;" << std::endl;
        }
    }
    // if no 8-bit loads, create 32/64-bit loads for stack access but
    // no patterns for isel as only the stack is 32/64-bit aligned.
    // 1- and 8-bit loads on isel will be handled by lowering.
    if (!mach_.hasOperation(load) &&
        !mach_.hasOperation(uload) &&
        mach_.hasOperation(wload)) {
        os << "def " << wload
           << "Br : InstTCE<(outs R1Regs:$op2), (ins MEMrr:$op1), \"\", "
           << "[]>;" << std::endl
        << "def " << wload
        << "Bi : InstTCE<(outs R1Regs:$op2), (ins MEMri:$op1), \"\", "
        << "[]>;" << std::endl;
        opNames_[wload + "Br"] = wload;
        opNames_[wload + "Bi"] = wload;
    }
    TCEString halfLoad = littleEndian_ ? "LD16" : "LDH";
    if (!mach_.hasOperation(halfLoad)) {
        TCEString halfULoad = littleEndian_ ? "LDU16" : "LDHU";
        if (mach_.hasOperation(halfULoad)) {
            halfLoad = halfULoad;
        } else {
            return;
        }
    }
    os << "def " << halfLoad << "hr : InstTCE<(outs HFPRegs:$op2), "
       << "(ins MEMrr:$op1), \"\", [(set HFPRegs:$op2, "
       << "(load ADDRrr:$op1))]>;" << std::endl;
    os << "def " << halfLoad << "hi : InstTCE<(outs HFPRegs:$op2), "
       << "(ins MEMri:$op1), \"\", [(set HFPRegs:$op2, "
       << "(load ADDRri:$op1))]>;" << std::endl;
    opNames_[halfLoad + "hr"] = halfLoad;
    opNames_[halfLoad + "hi"] = halfLoad;
    // TODO: what about 32-bit?
}
References TTAMachine::Machine::hasOperation(), TTAMachine::Machine::is64bit(), littleEndian_, mach_, and opNames_.
Referenced by writeInstrInfo().
createBranchAnalysis()
void TDGen::createBranchAnalysis (std::ostream & os) protected
Definition at line 7970 of file TDGen.cc.
{
    os << "bool GeneratedTCEPlugin::analyzeCCBranch(" << std::endl
       << "\tllvm::MachineInstr& i," << std::endl
       << "\tllvm::SmallVectorImpl<llvm::MachineOperand>& cond) const {"
       << std::endl
       << std::endl;
    if (!MachineInfo::supportsBoolRegisterGuardedJumps(mach_) &&
        MachineInfo::supportsPortGuardedJumps(mach_)) {
        os << "\tif (i.getOpcode() == TCE::EQ_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(2));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        os << "\tif (i.getOpcode() == TCE::NE_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(3));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        os << "\tif (i.getOpcode() == TCE::GT_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(4));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        os << "\tif (i.getOpcode() == TCE::LE_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(5));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        os << "\tif (i.getOpcode() == TCE::GTU_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(6));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        os << "\tif (i.getOpcode() == TCE::LEU_JUMP) {" << std::endl
           << "\t\tcond.push_back(i.getOperand(0));" << std::endl
           << "\t\tcond.push_back(i.getOperand(1));" << std::endl
           << "\t\tcond.push_back(MachineOperand::CreateImm(7));"
           << std::endl
           << "\t\treturn false; }" << std::endl;
        if (opNames_.find("EQF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::EQF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(8));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
        if (opNames_.find("NEF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::NEF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(9));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
        if (opNames_.find("LEF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::LEF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(10));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
        if (opNames_.find("GEF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::GEF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(10));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
        if (opNames_.find("LTF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::LTF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(12));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
        if (opNames_.find("GTF_JUMP") != opNames_.end()) {
            os << "\tif (i.getOpcode() == TCE::GTF_JUMP) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(13));"
               << std::endl
               << "\t\treturn false; }" << std::endl;
        }
    }
    if (!MachineInfo::supportsBoolRegisterGuardedJumps(mach_) &&
        !MachineInfo::supportsPortGuardedJumps(mach_)) {
        if (opNames_.count("TCEBREQrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBREQrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(2));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBREQri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(102));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRNErr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRNErr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(3));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRNEri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(103));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRGTrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRGTrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(4));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRGTri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(104));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRGTUrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRGTUrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(6));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRGTUri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(106));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRLTrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRLTrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(14));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRLTri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(114));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRLTUrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRLTUrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(15));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRLTUri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(115));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRLErr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRLErr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(5));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRLEri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(105));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRLEUrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRLEUrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(7));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRLEUri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(107));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRGErr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRGErr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(16));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRGEri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(116));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
        if (opNames_.count("TCEBRGEUrr")) {
            os << "\tif (i.getOpcode() == TCE::TCEBRGEUrr) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(17));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
            os << "\tif (i.getOpcode() == TCE::TCEBRGEUri) {" << std::endl
               << "\t\tcond.push_back(i.getOperand(0));" << std::endl
               << "\t\tcond.push_back(i.getOperand(1));" << std::endl
               << "\t\tcond.push_back(MachineOperand::CreateImm(117));"
               << std::endl
               << "\t\treturn false;" << std::endl
               << "\t}" << std::endl;
        }
    }
    os << "\treturn true;"
       << "}" << std::endl << std::endl;
    // insert branch
    os << "#include <llvm/CodeGen/MachineInstrBuilder.h>" << std::endl
       << std::endl;
    os << "void TCEInstrInfo::insertCCBranch( " << std::endl
       << "\tMachineBasicBlock& mbb," << std::endl
       << "\tMachineBasicBlock& tbb," << std::endl
       << "\tArrayRef<MachineOperand> cond," << std::endl
       << "const DebugLoc& dl) const {" << std::endl
       << "\tassert(cond.size() == 3);" << std::endl;
    os << "\tint opcode;" << std::endl;
    if (!MachineInfo::supportsBoolRegisterGuardedJumps(mach_) &&
        MachineInfo::supportsPortGuardedJumps(mach_)) {
        os << "\tswitch (cond[2].getImm()) {" << std::endl
           << "\t\tcase 2: opcode = TCE::EQ_JUMP;break;" << std::endl
           << "\t\tcase 3: opcode = TCE::NE_JUMP;break;" << std::endl
           << "\t\tcase 4: opcode = TCE::GT_JUMP;break;" << std::endl
           << "\t\tcase 5: opcode = TCE::LE_JUMP;break;" << std::endl
           << "\t\tcase 6: opcode = TCE::GTU_JUMP;break;" << std::endl
           << "\t\tcase 7: opcode = TCE::LEU_JUMP;break;" << std::endl;
        if (opNames_.find("EQF_JUMP") != opNames_.end()) {
            os << "\t\tcase 8: opcode = TCE::EQF_JUMP;break;" << std::endl;
        }
        if (opNames_.find("NEF_JUMP") != opNames_.end()) {
            os << "\t\tcase 9: opcode = TCE::NEF_JUMP;break;" << std::endl;
        }
        if (opNames_.find("LEF_JUMP") != opNames_.end()) {
            os << "\t\tcase 10: opcode = TCE::LEF_JUMP;break;" << std::endl;
        }
        if (opNames_.find("GEF_JUMP") != opNames_.end()) {
            os << "\t\tcase 11: opcode = TCE::GEF_JUMP;break;" << std::endl;
        }
        if (opNames_.find("LTF_JUMP") != opNames_.end()) {
            os << "\t\tcase 12: opcode = TCE::LTF_JUMP;break;" << std::endl;
        }
        if (opNames_.find("GEF_JUMP") != opNames_.end()) {
            os << "\t\tcase 13: opcode = TCE::GTF_JUMP;break;" << std::endl;
        }
        os << "\t\tdefault: assert(false && \"Unknown condition code\");}"
           << std::endl;
    } else if (!MachineInfo::supportsBoolRegisterGuardedJumps(mach_) &&
               !MachineInfo::supportsPortGuardedJumps(mach_)) {
        os << "\tswitch (cond[2].getImm()) {" << std::endl;
        if (opNames_.count("TCEBREQrr")) {
            os << "\t\tcase 2: opcode = TCE::TCEBREQrr; break;" << std::endl
               << "\t\tcase 102: opcode = TCE::TCEBREQri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRNErr")) {
            os << "\t\tcase 3: opcode = TCE::TCEBRNErr; break;" << std::endl
               << "\t\tcase 103: opcode = TCE::TCEBRNEri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRGTrr")) {
            os << "\t\tcase 4: opcode = TCE::TCEBRGTrr; break;" << std::endl
               << "\t\tcase 104: opcode = TCE::TCEBRGTri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRGTUrr")) {
            os << "\t\tcase 6: opcode = TCE::TCEBRGTUrr; break;" << std::endl
               << "\t\tcase 106: opcode = TCE::TCEBRGTUri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRLTrr")) {
            os << "\t\tcase 14: opcode = TCE::TCEBRLTrr; break;" << std::endl
               << "\t\tcase 114: opcode = TCE::TCEBRLTri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRLTUrr")) {
            os << "\t\tcase 15: opcode = TCE::TCEBRLTUrr; break;" << std::endl
               << "\t\tcase 115: opcode = TCE::TCEBRLTUri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRLErr")) {
            os << "\t\tcase 5: opcode = TCE::TCEBRLErr; break;" << std::endl
               << "\t\tcase 105: opcode = TCE::TCEBRLEri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRLEUrr")) {
            os << "\t\tcase 7: opcode = TCE::TCEBRLEUrr; break;" << std::endl
               << "\t\tcase 107: opcode = TCE::TCEBRLEUri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRGErr")) {
            os << "\t\tcase 16: opcode = TCE::TCEBRGErr; break;" << std::endl
               << "\t\tcase 116: opcode = TCE::TCEBRGEri; break;"
               << std::endl;
        }
        if (opNames_.count("TCEBRGEUrr")) {
            os << "\t\tcase 17: opcode = TCE::TCEBRGEUrr; break;" << std::endl
               << "\t\tcase 117: opcode = TCE::TCEBRGEUri; break;"
               << std::endl;
        }
        os << "\t\tdefault: assert(false && \"Unknown condition code\");}"
           << std::endl;
    } else {
        os << "\tassert(false && \"Unknown condition code\");" << std::endl;
    }
    os << "\tif (cond[1].isReg()) {" << std::endl
       << "\t\tBuildMI(&mbb, dl, get(opcode)).addReg(cond[0].getReg())"
       << std::endl
       << "\t\t       .addReg(cond[1].getReg()).addMBB(&tbb);" << std::endl
       << "\t} else {" << std::endl
       << "\t\tBuildMI(&mbb, dl, get(opcode)).addReg(cond[0].getReg())"
       << std::endl
       << "\t\t        .addImm(cond[1].getImm()).addMBB(&tbb);" << std::endl
       << "\t}" << std::endl;
    os << "}";
}
References mach_, opNames_, MachineInfo::supportsBoolRegisterGuardedJumps(), and MachineInfo::supportsPortGuardedJumps().
Referenced by writeBackendCode().
createByteExtLoadPatterns()
void TDGen::createByteExtLoadPatterns (std::ostream & os) protected
Definition at line 6531 of file TDGen.cc.
{
    TCEString load = littleEndian_ ? "LD8" : "LDQ";
    TCEString uload = littleEndian_ ? "LDU8" : "LDQU";
    TCEString destSize = mach_.is64bit() ? "64" : "32";
    int bits = mach_.is64bit() ? 64 : 32;
    TCEString ANDIMM = mach_.is64bit() ? "AND64ssa" : "ANDrri";
    TCEString ANDREG = mach_.is64bit() ? "AND64sss" : "ANDrrr";
    TCEString SUBIMM = mach_.is64bit() ? "SUB64sas" : "SUBrir";
    TCEString EXTOP = mach_.is64bit() ? "SXQ64" : "SXQW";
    TCEString EXTOPC = mach_.is64bit() ? "SXQ64sr" : "SXQWrr";
    TCEString SHL = mach_.is64bit() ? "SHL" : "SHL64";
    TCEString SHR = mach_.is64bit() ? "SHR" : "SHR64";
    TCEString SHRU = mach_.is64bit() ? "SHRU" : "SHRU64ssa";
    TCEString SHLOPC = mach_.is64bit() ? "SHLrri" : "SHL64ssa";
    TCEString SHROPC = mach_.is64bit() ? "SHRrri" : "SHR64ssa";
    TCEString SHRUOPC = mach_.is64bit() ? "SHRUrri" : "SHRU64ssa";
    TCEString SHL4 = mach_.is64bit() ? "SHL4_32" : "SHL4_64";
    TCEString SHR4 = mach_.is64bit() ? "SHR4_32" : "SHR4_64";
    TCEString SHRU4 = mach_.is64bit() ? "SHRU4_32" : "SHRU4_64ssa";
    TCEString regSrcChar = mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    TCEString dstTypeChar = OT_REG_INT;
    TCEString immSrcChar = mach_.is64bit() ? OT_IMM_LONG : OT_IMM_INT;
    TCEString loadOpcReg = load + dstTypeChar + regSrcChar;
    TCEString loadOpcImm = load + dstTypeChar + immSrcChar;
    if (mach_.hasOperation(load)) {
        if (!mach_.hasOperation(uload)) {
            // emulate zero ext with sing-ext and and
            os << "def : Pat<(i" << destSize << " (zextloadi8 ADDRrr:$addr)), "
               << "(" << ANDIMM << " ("
               << loadOpcReg << " ADDRrr:$addr), 255)>;"
               << std::endl;
            os << "def : Pat<(i" << destSize << " (zextloadi8 ADDRri:$addr)), "
               << "(" << ANDIMM << " ("
               << loadOpcImm << " ADDRri:$addr), 255)>;"
               << std::endl;
        }
    } else {
        // if no sign ext load, try zero ext load
        if (!mach_.hasOperation(uload)) {
            std::cerr << "Warning: The architecture is missing any 8-bit loads."
                      << " All code may not compile!"
                      << std::endl;
            return;
        }
        loadOpcReg = uload + dstTypeChar + regSrcChar;
        loadOpcImm = uload + dstTypeChar + immSrcChar;
        if (mach_.hasOperation(EXTOP)) {
            // use zextload + sext for sextload
            os << "def : Pat<(i" << destSize
               << " (sextloadi8 ADDRrr:$addr)), "
               << "(" << EXTOPC << " ("
               << loadOpcReg << " ADDRrr:$addr))>;" << std::endl;
            os << "def : Pat<(i" << destSize
               << " (sextloadi8 ADDRri:$addr)), "
               << "(" << EXTOPC << " ("
               << loadOpcImm << " ADDRri:$addr))>;" << std::endl;
        } else {
            if (mach_.hasOperation(SHL) && mach_.hasOperation(SHR)) {
                int sb = bits -8;
                os << "def : Pat<(i" << destSize
                   << " (sextloadi16 ADDRrr:$addr)), "
                   << "(" << SHROPC << " (" << SHLOPC << " ("
                   << load << "rr ADDRrr:$addr), "
                   << sb << "), " << sb << ")>;" << std::endl;
                os << "def : Pat<(i" << destSize
                   << " (sextloadi16 ADDRri:$addr)), "
                   << "(" << SHROPC << " (" << SHLOPC << " ("
                   << load << "ri ADDRri:$addr), "
                   << sb << "), " << sb << ")>;" << std::endl;
            } else if (mach_.hasOperation(SHL4) &&
                       mach_.hasOperation(SHR4)) {
                if (!mach_.is64bit()) {
                    os << "def : Pat<(i32 (sextloadi8 ADDRrr:$addr)), "
                       << "(SHR4_32rr (SHR4_32rr (SHR4_32rr (SHR4_32rr "
                       << "(SHR4_32rr (SHR4_32rr "
                       << "(SHL4_32rr (SHL4_32rr (SHL4_32rr (SHL4_32rr "
                       << "(SHL4_32rr (SHL4_32rr ("
                       << load << "rr ADDRrr:$addr)))))))))))))>;"
                       << std::endl;
                    os << "def : Pat<(i32 (sextloadi8 ADDRri:$addr)), "
                       << "(SHR4_32rr (SHR4_32rr (SHR4_32rr (SHR4_32rr "
                       << "(SHR4_32rr (SHR4_32rr "
                       << "(SHL4_32rr (SHL4_32rr (SHL4_32rr (SHL4_32rr "
                       << "(SHL4_32rr (SHL4_32rr ("
                       << load << "ri ADDRri:$addr)))))))))))))>;"
                       << std::endl;
                } else {
                    os << "def : Pat<(i64 (sextloadi8 ADDRrr:$addr)), "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss ("
                       << load << "rr ADDRrr:$addr)))))))))))))>;"
                       << std::endl;
                    os << "def : Pat<(i64 (sextloadi8 ADDRri:$addr)), "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss ("
                       << load << "ri ADDRri:$addr)))))))))))))>;"
                       << std::endl;
                }
            } else {
                std::cerr << "Warning: no sign-extending 8-bit loads,"
                          << " 8-bit sign extension instruction or suitable"
                          << " shifts for sext-emulation in the processor."
                          << " All code may not compile!" << std::endl;
            }
        }
    }
    // TODO: is there a more capable version of this code
    // commented out above???
    os << "def : Pat<(i" << destSize << " (zextloadi1 ADDRrr:$addr)), ("
       << loadOpcReg << " ADDRrr:$addr)>;"
       << std::endl
       << "def : Pat<(i" << destSize << " (zextloadi1 ADDRri:$addr)), ("
       << loadOpcImm << " ADDRri:$addr)>;"
       << std::endl;
    os << "def : Pat<(i" << destSize << " (sextloadi1 ADDRrr:$addr)), "
       << "(" << SUBIMM << " 0, "
       << "(" << ANDREG << " ("
       << loadOpcReg << " ADDRrr:$addr), 1))>;"
       << std::endl
       << "def : Pat<(i" << destSize << " (sextloadi1 ADDRri:$addr)), "
       << "(" << SUBIMM << " 0, "
       <<  "(" << ANDREG << " ("
       << loadOpcImm << " ADDRri:$addr), 1))>;"
       << std::endl
       << "// anyextloads" << std::endl;
    os << "def : Pat<(i" << destSize << " (extloadi1 ADDRrr:$src)), ("
       << loadOpcReg << " ADDRrr:$src)>;" << std::endl
       << "def : Pat<(i" << destSize << " (extloadi1 ADDRri:$src)), ("
       << loadOpcImm << " ADDRri:$src)>;" << std::endl
       << "def : Pat<(i" << destSize << " (extloadi8 ADDRrr:$src)), ("
       << loadOpcReg << " ADDRrr:$src)>;" << std::endl
       << "def : Pat<(i" << destSize << " (extloadi8 ADDRri:$src)), ("
       << loadOpcImm << " ADDRri:$src)>;" << std::endl
       << std::endl;
}
References TTAMachine::Machine::hasOperation(), TTAMachine::Machine::is64bit(), littleEndian_, mach_, OT_IMM_INT, OT_IMM_LONG, OT_REG_INT, OT_REG_LONG, and SUBIMM.
Referenced by writeInstrInfo().
createConstantMaterializationPatterns()
void TDGen::createConstantMaterializationPatterns (std::ostream & os) protected virtual
Generates llvm patterns for constants which are not supported directly as immediates by the target machine.
For example, if a target does not sign extending immediates, a pattern is generated that transforms negative constants C to (SUB 0, -C).
Definition at line 7458 of file TDGen.cc.
{
    // TODO: this is used when when not needed!
    // creating unnecessary NEG operations!
    // LLVM XForm fragments //
    // Transformation functions definitions that creates new constants
    // from unsupported constants.
    os << std::endl << "// Arithmetic negation XForm fragment."
       << std::endl << "def aneg_xform : SDNodeXForm<imm, [{"
       << std::endl << "    return CurDAG->getTargetConstant("
       << std::endl << "        -(N->getZExtValue()), SDLoc(N), MVT::i32);"
       << std::endl << "}]>;"
       << std::endl << std::endl;
    // Constant select operand definitions //
    // Used in Constant materialization patterns to select the constant values
    // that are valid for the pattern transformation. The predicate must
    // test that the original constant can be accepted by the materialization
    // pattern itself and test that the resulted constants by XForms are
    // supported too by the target machine.
    // Negative constant materialization: C -> NEG(-C) or C -> SUB(0, -C)
    // selecting the cheapest.
    std::vector<std::string> ops;
    if (opNames_.count("NEGri")) ops.push_back("NEG");
    if (opNames_.count("SUBrri")) ops.push_back("SUB");
    for (auto op : ops) {
        // Predicate that accepts the negative constants
        std::string predicate = "Imm < 0";
        std::pair<int64_t, int64_t> tmp = immInfo_->immediateValueBounds(
            ImmInfoKey{op , 1} , 32);
        if (tmp.second < 2) continue;
        predicate += " && Imm >= -" + Conversion::toString(tmp.second-1);
        writeImmediateDef(os, "minus_i32imm", "i32", predicate);
        // store predicates for the materialization queries by ISelLowering,
        // where decisions to bail unsupported constants to constant pool are
        // made. The stored predicates are written to Backend.inc later on.
        constantMaterializationPredicates_.push_back(predicate);
        os << std::endl << "def : Pat<(i32 minus_i32imm:$imm)," << std::endl;
        if (op == "NEG") {
            os << "          (NEGri (aneg_xform imm:$imm))>;";
        } else if (op == "SUB") {
            os << "          (SUBrri (MOVI32ri 0), (aneg_xform imm:$imm))>;";
        }
        os << std::endl;
        break; // We need only the cheapest materialization pattern.
    }
}
References constantMaterializationPredicates_, ImmInfo::immediateValueBounds(), immInfo_, opNames_, Conversion::toString(), and writeImmediateDef().
Referenced by writeInstrInfo().
createConstantMaterializationQuery()
void TDGen::createConstantMaterializationQuery (std::ostream & os) protected
Creates query function for TCEISelLowering for testing if otherwise unsupported constant as immediate can be materialized instead of converting it to constant pool load.
Definition at line 6501 of file TDGen.cc.
{
    if (constantMaterializationPredicates_.empty()) {
        os << "bool GeneratedTCEPlugin::canMaterializeConstant("
           << "const ConstantInt&) const { " << std::endl
           << "    return false;" << std::endl
           << "};" << std::endl;
        return;
    }
    os << "bool GeneratedTCEPlugin::canMaterializeConstant("
       << "const ConstantInt& ci) const {"
       << std::endl
       << "    int64_t Imm = ci.getSExtValue();" << std::endl
       << "    if (";
    bool first = true;
    for (auto& predicate : constantMaterializationPredicates_) {
        if (!first) {
            os << std::endl << "        || ";
        }
        os << "(" << predicate << ")";
        first = false;
    }
    os << ") {"
       << "        return true;" << std::endl
       << "    }" << std::endl
       << "    return false;" << std::endl
       << "}" << std::endl;
}
References constantMaterializationPredicates_.
Referenced by writeBackendCode().
createConstShiftPatterns()
void TDGen::createConstShiftPatterns (std::ostream & os) protected
Definition at line 8599 of file TDGen.cc.
{
    int bits = mach_.is64bit() ? 64: 32;
    for (int i = 1; i < bits; i++) {
        writeConstShiftPat(os, "TCESRAConst", "SHR", i);
        writeConstShiftPat(os, "TCESRLConst", "SHRU", i);
        writeConstShiftPat(os, "TCESHLConst", "SHL", i);
    }
}
References TTAMachine::Machine::is64bit(), mach_, and writeConstShiftPat().
Referenced by writeInstrInfo().
createDefaultOperandTypeString()
std::string TDGen::createDefaultOperandTypeString (const Operation & op) protected
Definition at line 5439 of file TDGen.cc.
{
    std::string operandTypes;
    int inputs = op.numberOfInputs();
    int outputs = op.numberOfOutputs();
    for (int i = 0; i < outputs; i++) {
        Operand& operand = op.operand(i + inputs +1);
        operandTypes += operandChar(operand);
    }
    for (int i = 0; i < inputs ; i++) {
        Operand& operand = op.operand(i +1);
        operandTypes += operandChar(operand);
    }
    return operandTypes;
}
References Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), and operandChar().
Referenced by subPattern(), writeOperationDefs(), and writeOperationDefUsingGivenOperandTypes().
createEndiannesQuery()
void TDGen::createEndiannesQuery (std::ostream & os) protected
Definition at line 6487 of file TDGen.cc.
{
    bool is64bit = mach_.is64bit();
    os << "bool GeneratedTCEPlugin::isLittleEndian() const {" << std::endl;
    os << "return " << littleEndian_ << "; }" << std::endl;
    os << "bool GeneratedTCEPlugin::is64bit() const {" << std::endl;
    os << "return " << is64bit << "; }" << std::endl;
}
References TTAMachine::Machine::is64bit(), littleEndian_, and mach_.
Referenced by writeBackendCode().
createGetMaxMemoryAlignment()
void TDGen::createGetMaxMemoryAlignment (std::ostream & os) const protected
Definition at line 7048 of file TDGen.cc.
{
    if (mach_.is64bit()) {
        os << std::endl
           << "unsigned GeneratedTCEPlugin::getMaxMemoryAlignment() const {"
           << std::endl
           << "\treturn 8;"
           << std::endl << "}" << std::endl;
    } else {
        os << std::endl
           << "unsigned GeneratedTCEPlugin::getMaxMemoryAlignment() const {"
           << std::endl
           << "\treturn 4;"
           << std::endl << "}" << std::endl;
    }
}
References TTAMachine::Machine::is64bit(), and mach_.
createMinMaxDef()
void TDGen::createMinMaxDef (const TCEString & opName, const TCEString & valueName, std::ostream & os) protected
Definition at line 6370 of file TDGen.cc.
{
    if (opNames_.find(opName) != opNames_.end()) {
    os << "\tif (vt == MVT::" << valueName << ") return TCE::"
       << opName << ";" << std::endl;
    }
}
References opNames_.
Referenced by createVectorMinMaxDef().
createMinMaxGenerator()
void TDGen::createMinMaxGenerator (std::ostream & os) protected virtual
Definition at line 6398 of file TDGen.cc.
{
    bool is64bit = mach_.is64bit();
    // MIN
    os  << "int GeneratedTCEPlugin::getMinOpcode(SDNode* n) const {" << std::endl
        << "\tEVT vt = n->getOperand(1).getValueType();" << std::endl;
    if (!is64bit) {
        if (opNames_.find("MINrrr") != opNames_.end()) {
            os << "if (vt == MVT::i32) return TCE::MINrrr;" << std::endl;
        }
    } else {
        if (opNames_.find("MIN64sss") != opNames_.end()) {
            os << "if (vt == MVT::i64) return TCE::MIN64sss;" << std::endl;
        }
    }
    if (opNames_.find("MINFfff") != opNames_.end()) {
        os << "if (vt == MVT::f32) return TCE::MINFfff;" << std::endl;
    }
    createVectorMinMaxDef("MINH", 16, 'f', "ggg", os);
    createVectorMinMaxDef("MINF", 32, 'f', "eee", os);
    createVectorMinMaxDef("MIN", 32, 'i', "uuu", os);
    createVectorMinMaxDef("MIN", 16, 'i', "ttt", os);
    os << "\treturn -1; " << std::endl << "}" << std::endl;
    // MAX
    os  << "int GeneratedTCEPlugin::getMaxOpcode(SDNode* n) const {" << std::endl
        << "\tEVT vt = n->getOperand(1).getValueType();" << std::endl;
    if (!is64bit) {
        if (opNames_.find("MAXrrr") != opNames_.end()) {
            os << "if (vt == MVT::i32) return TCE::MAXrrr;" << std::endl;
        }
    } else {
        if (opNames_.find("MAX64sss") != opNames_.end()) {
            os << "if (vt == MVT::i64) return TCE::MAX64sss;" << std::endl;
        }
    }
    if (opNames_.find("MAXFfff") != opNames_.end()) {
        os << "if (vt == MVT::f32) return TCE::MAXFfff;" << std::endl;
    }
    createVectorMinMaxDef("MAXH", 16, 'f', "ggg", os);
    createVectorMinMaxDef("MAXF", 32, 'f', "eee", os);
    createVectorMinMaxDef("MAX", 32, 'i', "uuu", os);
    createVectorMinMaxDef("MAX", 16, 'i', "ttt", os);
    os << "\treturn -1; " << std::endl << "}" << std::endl;
    // MINU
    os  << "int GeneratedTCEPlugin::getMinuOpcode(SDNode* n) const {" << std::endl;
    os << "\tEVT vt = n->getOperand(1).getValueType();" << std::endl;
    if (!is64bit) {
        if (opNames_.find("MINUrrr") != opNames_.end()) {
            os << "if (vt == MVT::i32) return TCE::MINUrrr;" << std::endl;
        }
    } else {
        if (opNames_.find("MINU64sss") != opNames_.end()) {
            os << "if (vt == MVT::i64) return TCE::MINU64sss;" << std::endl;
        }
    }
    createVectorMinMaxDef("MINU", 32, 'i', "uuu", os);
    createVectorMinMaxDef("MINU", 16, 'i', "ttt", os);
    os << "\treturn -1; " << std::endl << "}" << std::endl;
    // MAXU
    os  << "int GeneratedTCEPlugin::getMaxuOpcode(SDNode* n) const {" << std::endl;
    os << "\tEVT vt = n->getOperand(1).getValueType();" << std::endl;
    if (!is64bit) {
        if (opNames_.find("MAXUrrr") != opNames_.end()) {
            os << "if (vt == MVT::i32) return TCE::MAXUrrr;" << std::endl;
        }
    } else {
        if (opNames_.find("MAXU64sss") != opNames_.end()) {
            os << "if (vt == MVT::i64) return TCE::MAXU64sss;" << std::endl;
        }
    }
    createVectorMinMaxDef("MAXU", 32, 'i', "uuu", os);
    createVectorMinMaxDef("MAXU", 16, 'i', "ttt", os);
    os << "\treturn -1; " << std::endl << "}" << std::endl;
}
References createVectorMinMaxDef(), TTAMachine::Machine::is64bit(), mach_, and opNames_.
Referenced by writeBackendCode().
createParamDRegNums()
void TDGen::createParamDRegNums (std::ostream & os) protected
Definition at line 7010 of file TDGen.cc.
{
    os <<
        "std::vector<unsigned>" << std::endl <<
        "GeneratedTCEPlugin::getParamDRegNums() const {" << std::endl <<
        "std::vector<unsigned> res;" << std::endl;
    for (unsigned int i = 4; i < argRegCount_ + 3; i++) {
        os << "res.push_back(TCE::A" << i << ");" << std::endl;
    }
    os << "return res;}" << std::endl;
}
References argRegCount_.
Referenced by writeBackendCode().
createSelectPatterns()
void TDGen::createSelectPatterns (std::ostream & os) protected virtual
Definition at line 7065 of file TDGen.cc.
{
    os << "// Creating select patterns. " << std::endl;
    if (!hasSelect_) {
        os << "// Does not have select instr. " << std::endl;
        if (!hasConditionalMoves_) {
            std::string NEG = mach_.is64bit() ? "NEG64" : "NEG";
            std::string NEGOPC = mach_.is64bit() ? "NEG64ss" : "NEGrr";
            std::string gprRegs = mach_.is64bit() ? "R64IRegs" : "R32IRegs";
            std::string typeStr = mach_.is64bit() ? "ssa" : "rri";
            std::string typeStrInv = mach_.is64bit() ? "sas" : "rir";
            const char* sub = mach_.is64bit() ? "SUB64" : "SUB";
            const char* iand = mach_.is64bit() ? "AND64" : "AND";
            std::string ior = mach_.is64bit() ? "IOR64" : "IOR";
            std::string defType = mach_.is64bit() ? "i64" : "i32";
            std::string andReg = mach_.is64bit() ? "AND64sss" : "ANDrrr";
            std::string iorReg = mach_.is64bit() ? "IOR64sss" : "IORrrr";
            std::string iorBool = mach_.is64bit() ? "IOR64bbb" : "IORbbb";
            std::string andBool = mach_.is64bit() ? "AND64bbb" : "ANDbbb";
            std::string xorBooli = mach_.is64bit() ? "XOR64bbj" : "XORbbj";
            bool hasNeg = opNames_.count("NEGrr");
            std::string condRC = regs1bit_.empty() ? gprRegs : "R1Regs";
            std::string truncOp = regs1bit_.empty() ? std::string(iand) + typeStr : "ANDext";
            OperationPool opPool;
            std::string truncPattern = regs1bit_.empty()
                ? std::string("$c")
                : std::string("(") + truncOp + " " + condRC + ":$c" + ", 1)";
            std::string falseMask = getLLVMPatternWithConstants(
                opPool.operation(sub), typeStr, truncPattern, "1");
            std::string trueMask = hasNeg ?
                std::string("(" + NEGOPC + " ") + truncPattern +
                std::string(")")
                : getLLVMPatternWithConstants(
                    opPool.operation(sub), typeStrInv, "0", truncPattern);
            std::string applyTrueMaskOnImm = getLLVMPatternWithConstants(
                opPool.operation(iand), typeStr, trueMask, "imm:$t");
            std::string applyFalseMaskOnImm = getLLVMPatternWithConstants(
                opPool.operation(iand), typeStr, falseMask, "imm:$f");
#if 0 // TODO: why is this commented out???
            if (mach_.is64bit()) {
            os << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, R64Regs:$t, R64Regs:$f)), "
               << "(IOR64sss (AND64sss R32Regs:$t, (SUB64sas 0, (ANDext R1Regs:$c, 1))),"
               << "(AND64sss R32Regs:$f, (SUB64ssa (ANDext R1Regs:$c, 1), 1)))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, (i64 imm:$t),(i64 imm:$f))),"
               << "(IOR64sss (AND64ssa (SUB64sas 0, (ANDext R1Regs:$c, 1)), imm:$t),"
               << "(AND64ssa (SUB64ssa (ANDext R1Regs:$c, 1), 1), imm:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, R64Regs:$t, (i64 imm:$f))),"
               << "(IOR64sss (AND64sss (SUB64sas 0, (ANDext R1Regs:$c, 1)), R32Regs:$t),"
               << "(AND64ssa (SUB64ssa (ANDext R1Regs:$c, 1), 1), imm:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, (i64 imm:$t), R64Regs:$f)),"
               << "(IOR64sss (AND64ssa (SUB64sas 0, (ANDext R1Regs:$c, 1)), imm:$t),"
               << "(AND64sss (SUB64ssa (ANDext R1Regs:$c, 1), 1), R32Regs:$f))>;"
               << std::endl << std::endl;
             os << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, R64Regs:$t, R64Regs:$f)), "
               << "(IOR64sss (AND64sss R64Regs:$t, (SUB64sas 0, (ANDext R1Regs:$c, 1))),"
               << "(AND64sss R64Regs:$f, (SUB64ssa (ANDext R1Regs:$c, 1), 1)))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, (i64 imm:$t),(i64 imm:$f))),"
               << "(IOR64sss (AND64ssa (SUB64sas 0, (ANDext R1Regs:$c, 1)), imm:$t),"
               << "(AND64ssa (SUB64ssa (ANDext R1Regs:$c, 1), 1), imm:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, R64Regs:$t, (i64 imm:$f))),"
               << "(IOR64sss (AND64sss (SUB64sas 0, (ANDext R1Regs:$c, 1)), R64Regs:$t),"
               << "(AND64ssa (SUB64ssa (ANDext R1Regs:$c, 1), 1), imm:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i64 (select R1Regs:$c, (i64 imm:$t), R64Regs:$f)),"
               << "(IOR64sss (ANDssa (SUB64sas 0, (ANDext R1Regs:$c, 1)), imm:$t),"
               << "(ANDsss (SUBssa (ANDext R1Regs:$c, 1), 1), R64Regs:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$t, R1Regs:$f)),"
               << "(IOR64bbb (AND64bbb R1Regs:$c, R1Regs:$t), "
               << "(AND64bbb (XOR64bbj R1Regs:$c, 1), R1Regs:$f))>;"
               << std::endl << std::endl
               << "def : Pat<(i1 (select R1Regs:$c, (i1 0), R1Regs:$f)),"
               << "(AND64bbb (XOR64bbj R1Regs:$c, 1), R1Regs:$f)>;"
               << std::endl << std::endl
               << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$t, (i1 -1))),"
               << "(IOR64bbb (AND64bbb R1Regs:$c, R1Regs:$t),"
               << "(XOR64bbj R1Regs:$c, 1))>;"
               << std::endl << std::endl;
            } //else {
#endif
            if (mach_.is64bit()) {
                // optimize select with zero.
                os << "def : Pat<(i64 (select "
                   << condRC << ":$c, R64Regs:$t, (i64 0)))," << std::endl
                   << "          (AND64sss "
                   << trueMask << ", R64Regs:$t)>;"
                   << std::endl << std::endl
                   << "def : Pat<(i64 (select "
                   << condRC << ":$c, (i64 0), R64Regs:$f))," << std::endl
                   << "(AND64sss " << falseMask << ", R64Regs:$f)>;"
                   << std::endl << std::endl;
                // also select with zero and some other imm
                os << "def : Pat<(i64 (select "
                   << condRC << ":$c, (i64 imm:$t),(i64 0)))," << std::endl
                   << "         " << applyTrueMaskOnImm << ">;"
                   << std::endl << std::endl;
                os << "def : Pat<(i64 (select "
                   << condRC << ":$c, (i64 0),(i64 imm:$f)))," << std::endl
                   << "         " << applyFalseMaskOnImm << ">;"
                   << std::endl << std::endl;
            } else {
                // optimize select with zero.
                os << "def : Pat<(i32 (select "
                   << condRC << ":$c, R32Regs:$t, (i32 0)))," << std::endl
                   << "          (ANDrrr "
                   << trueMask << ", R32Regs:$t)>;"
                   << std::endl << std::endl
                   << "def : Pat<(i32 (select "
                   << condRC << ":$c, (i32 0), R32Regs:$f))," << std::endl
                   << "(ANDrrr " << falseMask << ", R32Regs:$f)>;"
                   << std::endl << std::endl;
                // also select with zero and some other imm
                os << "def : Pat<(i32 (select "
                   << condRC << ":$c, (i32 imm:$t),(i32 0)))," << std::endl
                   << "         " << applyTrueMaskOnImm << ">;"
                   << std::endl << std::endl;
                os << "def : Pat<(i32 (select "
                   << condRC << ":$c, (i32 0),(i32 imm:$f)))," << std::endl
                   << "         " << applyFalseMaskOnImm << ">;"
                   << std::endl << std::endl;
            }
            // TODO: similar patterns could be made with -1, avoiding one AND?
            // then the more generic ones
            os << std::endl
               << "def : Pat<(" << defType << " (select "
               << condRC << ":$c, " << gprRegs << ":$t, " << gprRegs << ":$f)), " << std::endl
               << "          (" << iorReg << " (" << andReg << " " << gprRegs << ":$t, "
               << trueMask << "),"
               << "(" << andReg << " " << gprRegs << ":$f, " << falseMask << "))>;"
               << std::endl << std::endl
               << "def : Pat<(" << defType << " (select "
               << condRC << ":$c, (" << defType << " imm:$t),(" << defType << " imm:$f)))," << std::endl
               << "          (" << iorReg << " " << applyTrueMaskOnImm << ","
               << applyFalseMaskOnImm << ")>;"
               << std::endl << std::endl
               << "def : Pat<(" << defType << " (select "
               << condRC << ":$c, " << gprRegs << ":$t, (" << defType << " imm:$f)))," << std::endl
               << "          (" << iorReg << " (" << andReg << " "
               << trueMask << ", " << gprRegs << ":$t)," << applyFalseMaskOnImm << ")>;"
               << std::endl << std::endl
               << "def : Pat<(" << defType << " (select "
               << condRC << ":$c, (" << defType << " imm:$t), " << gprRegs << ":$f))," << std::endl
               << "          (" << iorReg << " " << applyTrueMaskOnImm << ","
               << "(" << andReg << " " << falseMask << ", " << gprRegs << ":$f))>;"
               << std::endl << std::endl;
            if (!regs1bit_.empty()) {
                os << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$t, R1Regs:$f)),"
                   << std::endl
                   << "          (" << iorBool << " (" << andBool << " R1Regs:$c, R1Regs:$t), "
                   << "(" << andBool << " (" << xorBooli << " R1Regs:$c, 1), R1Regs:$f))>;"
                   << std::endl << std::endl
                   << "def : Pat<(i1 (select R1Regs:$c, (i1 0), R1Regs:$f)),"
                   << std::endl
                   << "          (" << andBool << " (" << xorBooli << " R1Regs:$c, 1), R1Regs:$f)>;"
                   << std::endl << std::endl
                   << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$t, (i1 -1))),"
                   << std::endl
                   << "          (" << iorBool << " (" << andBool << " R1Regs:$c, R1Regs:$t),"
                   << "(" << xorBooli << " R1Regs:$c, 1))>;"
                   << std::endl << std::endl;
            }
            os << "def : Pat<(f32 (select " << condRC << ":$c, "
                  "FPRegs:$t,FPRegs:$f))," << std::endl
               << "          (IORfff (ANDfff FPRegs:$t, (SUBfir 0, "
               << truncPattern << ")),"
               << "(ANDfff FPRegs:$f, (SUBfri "
               << truncPattern << ",1)))>;"
               << std::endl << std::endl
               << "def : Pat<(f16 (select " << condRC << ":$c, "
                  "R32HFPRegs:$t, R32HFPRegs:$f))," << std::endl
               << "          (IORhhh (ANDhhh R32HFPRegs:$t, (SUBhir 0, "
               << truncPattern << ")),"
               << "(ANDhhh R32HFPRegs:$f, (SUBhri "
               << truncPattern << ",1)))>;"
               << std::endl << std::endl;
//            }
        } else {  // has conditional moves.
            opNames_["SELECT_I1bb"] = "CMOV_SELECT";
            opNames_["SELECT_I1bj"] = "CMOV_SELECT";
            opNames_["SELECT_I1jb"] = "CMOV_SELECT";
            opNames_["SELECT_I1jj"] = "CMOV_SELECT";
            opNames_["SELECT_I32rr"] = "CMOV_SELECT";
            opNames_["SELECT_I32ir"] = "CMOV_SELECT";
            opNames_["SELECT_I32ri"] = "CMOV_SELECT";
            opNames_["SELECT_I32ii"] = "CMOV_SELECT";
            opNames_["SELECT_F32"] = "CMOV_SELECT";
            opNames_["SELECT_F16"] = "CMOV_SELECT";
        // TODO: why does this break??
        os << " let isSelect = 1 in {" << std::endl;
            if (mach_.is64bit()) {
                opNames_["SELECT_I64rr"] = "CMOV_SELECT";
                opNames_["SELECT_I64ir"] = "CMOV_SELECT";
                opNames_["SELECT_I64ri"] = "CMOV_SELECT";
                opNames_["SELECT_I64ii"] = "CMOV_SELECT";
                opNames_["SELECT_F64"] = "CMOV_SELECT";
                os  << "def SELECT_I64rr : InstTCE<(outs R64IRegs:$dst),"
                    << "(ins R1Regs:$c, R64IRegs:$T, R64IRegs:$F),"
                    << "\"# SELECT_I64 PSEUDO!\","
                    << "[(set R64IRegs:$dst,"
                    << "(select R1Regs:$c, R64IRegs:$T, R64IRegs:$F))]>;"
                    << std::endl << std::endl
                    << "def SELECT_I64ri : InstTCE<(outs R64IRegs:$dst),"
                    << "(ins R64IRegs:$c, R64IRegs:$T, i64imm:$F),"
                    << "\"# SELECT_I64 PSEUDO!\","
                    << "[(set R64IRegs:$dst,"
                    << "(select R64IRegs:$c, R64IRegs:$T, (i64 imm:$F)))]>;"
                    << std::endl << std::endl
                    << "def SELECT_I64ir : InstTCE<(outs R64IRegs:$dst),"
                    << "(ins R64IRegs:$c, i64imm:$T, R64IRegs:$F),"
                    << "\"# SELECT_I64 PSEUDO!\","
                    << "[(set R64IRegs:$dst,"
                    << "(select R64IRegs:$c, (i64 imm:$T), R64IRegs:$F))]>;"
                    << std::endl << std::endl
                    << "def SELECT_I64ii : InstTCE<(outs R64IRegs:$dst),"
                    << "(ins R64IRegs:$c, i64imm:$T, i64imm:$F),"
                    << "\"# SELECT_I64 PSEUDO!\","
                    << "[(set R64IRegs:$dst,"
                    << "(select R64IRegs:$c, (i64 imm:$T), (i64 imm:$F)))]>;"
                    << std::endl << std::endl
                    << "def SELECT_F64 : InstTCE<(outs R64DFPRegs:$dst),"
                    << "(ins R1Regs:$c, R64DFPRegs:$T, R64DFPRegs:$F),"
                    << "\"# SELECT_F64 PSEUDO!\","
                    << "[(set R64DFPRegs:$dst,"
                    << "(select R1Regs:$c, R64DFPRegs:$T, R64DFPRegs:$F))]>;"
                    << std::endl << std::endl;
            }
            os << "def SELECT_I1bb : InstTCE<(outs R1Regs:$dst),"
               << "(ins GuardRegs:$c, R1Regs:$T, R1Regs:$F),"
               << "\"# SELECT_I1 PSEUDO!\","
               << " [(set R1Regs:$dst,"
               << "(select GuardRegs:$c, R1Regs:$T, R1Regs:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_I1bj : InstTCE<(outs R1Regs:$dst),"
               << " (ins GuardRegs:$c, R1Regs:$T, i1imm:$F),"
               << "\"# SELECT_I1 PSEUDO!\","
               << "[(set R1Regs:$dst,"
               << "(select GuardRegs:$c, R1Regs:$T, (i1 imm:$F)))]>;"
               << std::endl << std::endl
               << "def SELECT_I1jb : InstTCE<(outs R1Regs:$dst),"
               << "(ins GuardRegs:$c, i1imm:$T, R1Regs:$F),"
               << "\"# SELECT_I1 PSEUDO!\","
               << "[(set R1Regs:$dst,"
               << "(select GuardRegs:$c, (i1 imm:$T), R1Regs:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_I1jj : InstTCE<(outs R1Regs:$dst),"
               << "(ins GuardRegs:$c, i1imm:$T, i1imm:$F),"
               << "\"# SELECT_I1 PSEUDO!\","
               << "[(set R1Regs:$dst,"
               << "(select GuardRegs:$c, (i1 imm:$T), (i1 imm:$F)))]>;"
               << std::endl << std::endl
               << "def SELECT_I32rr : InstTCE<(outs R32IRegs:$dst),"
               << "(ins GuardRegs:$c, R32IRegs:$T, R32IRegs:$F),"
               << "\"# SELECT_I32 PSEUDO!\","
               << "[(set R32IRegs:$dst,"
               << "(select GuardRegs:$c, R32IRegs:$T, R32IRegs:$F))]>;"
               << std::endl << std::endl
// select with the cond in an i32 (produced by expanded vselects with i32 cond vectors)
               << "def SELECT_I32ri : InstTCE<(outs R32IRegs:$dst),"
               << "(ins R32IRegs:$c, R32IRegs:$T, i32imm:$F),"
               << "\"# SELECT_I32 PSEUDO!\","
               << "[(set R32IRegs:$dst,"
               << "(select R32IRegs:$c, R32IRegs:$T, i32MoveImm:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_I32ir : InstTCE<(outs R32IRegs:$dst),"
               << "(ins R32IRegs:$c, i32imm:$T, R32IRegs:$F),"
               << "\"# SELECT_I32 PSEUDO!\","
               << "[(set R32IRegs:$dst,"
               << "(select R32IRegs:$c, i32MoveImm:$T, R32IRegs:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_I32ii : InstTCE<(outs R32IRegs:$dst),"
               << "(ins R32IRegs:$c, i32imm:$T, i32imm:$F),"
               << "\"# SELECT_I32 PSEUDO!\","
               << "[(set R32IRegs:$dst,"
               << "(select R32IRegs:$c, i32MoveImm:$T, i32MoveImm:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_F32 : InstTCE<(outs FPRegs:$dst),"
               << "(ins GuardRegs:$c, FPRegs:$T, FPRegs:$F),"
               << "\"# SELECT_F32 PSEUDO!\","
               << "[(set FPRegs:$dst,"
               << "(select GuardRegs:$c, FPRegs:$T, FPRegs:$F))]>;"
               << std::endl << std::endl
               << "def SELECT_F16 : InstTCE<(outs HFPRegs:$dst),"
               << "(ins GuardRegs:$c, HFPRegs:$T, HFPRegs:$F),"
               << "\"# SELECT_F16 PSEUDO!\","
               << "[(set HFPRegs:$dst, "
               << "(select GuardRegs:$c, HFPRegs:$T, HFPRegs:$F))]>;"
               << std::endl << std::endl;
        os << "}" << std::endl << std::endl;
        if (mach_.is64bit()) {
        os << "def : Pat<(i64 (select R64IRegs:$c, R64IRegs:$T, R64IRegs:$F)),"
           << "(SELECT_I64rr (MOVI64I1ss R64Regs:$c),"
           << "R64IRegs:$T, R64IRegs:$F)>;"
           << std::endl << std::endl;
        }
            os << "def : Pat<(i32 (select R32IRegs:$c, R32IRegs:$T, R32IRegs:$F)),"
               << "(SELECT_I32rr (MOVI32I1rr R32Regs:$c),"
               << "R32IRegs:$T, R32IRegs:$F)>;"
               << std::endl << std::endl;
        }
    } else {
        os << "// Has select instr!. " << std::endl;
    }
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        TCEString regClassName = regClass.name();
        ValueType valType = regClass.valueType();
        TCEString valTypeName = valType.valueTypeStr();
        os << "def SELECT_" << valTypeName << " : InstTCE<(outs "
           << regClassName << ":$dst), (ins R1Regs:$c, " << regClassName
           << ":$T, " << regClassName << ":$F), \"\","
           << "[(set " << regClassName << ":$dst,"
           << "(select R1Regs:$c, " << regClassName << ":$T, " << regClassName
           << ":$F))]>;" << std::endl
           << std::endl;
        opNames_["SELECT_" + valTypeName] = "CMOV_SELECT";
    }
}
References getLLVMPatternWithConstants(), hasConditionalMoves_, hasSelect_, TTAMachine::Machine::is64bit(), mach_, TDGenerator::RegisterClass::name(), OperationPool::operation(), opNames_, regs1bit_, sub, TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
Referenced by writeInstrInfo().
createShortExtLoadPatterns()
void TDGen::createShortExtLoadPatterns (std::ostream & os) protected
Definition at line 6691 of file TDGen.cc.
{
    TCEString load = littleEndian_ ? "LD16" : "LDH";
    TCEString destSize = mach_.is64bit() ? "64" : "32";
    int bits = mach_.is64bit() ? 64 : 32;
    TCEString ANDOPC = mach_.is64bit() ? "AND64ssa" : "ANDrri";
    TCEString uload = littleEndian_ ? "LDU16" : "LDHU";
    TCEString EXTOP = mach_.is64bit() ? "SXH64" : "SXHW";
    TCEString EXTOPC = mach_.is64bit() ? "SXH64sr" : "SXHWrr";
    TCEString regSrcChar = mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    TCEString dstTypeChar = OT_REG_INT;
    TCEString immSrcChar = mach_.is64bit() ? OT_IMM_LONG : OT_IMM_INT;
    TCEString loadOpcReg = load + dstTypeChar + regSrcChar;
    TCEString loadOpcImm = load + dstTypeChar + immSrcChar;
    TCEString SHL = mach_.is64bit() ? "SHL" : "SHL64";
    TCEString SHR = mach_.is64bit() ? "SHR" : "SHR64";
    TCEString SHRU = mach_.is64bit() ? "SHRU" : "SHRU64ssa";
    TCEString SHLOPC = mach_.is64bit() ? "SHLrri" : "SHL64ssa";
    TCEString SHROPC = mach_.is64bit() ? "SHRrri" : "SHR64ssa";
    TCEString SHRUOPC = mach_.is64bit() ? "SHRUrri" : "SHRU64ssa";
    TCEString SHL4 = mach_.is64bit() ? "SHL4_32" : "SHL4_64";
    TCEString SHR4 = mach_.is64bit() ? "SHR4_32" : "SHR4_64";
    TCEString SHRU4 = mach_.is64bit() ? "SHRU4_32" : "SHRU4_64ssa";
    if (mach_.hasOperation(load)) {
        if (!mach_.hasOperation(uload)) {
            // emulate zero ext with sing-ext and and
            os << "def : Pat<(i" << destSize
               << " (zextloadi16 ADDRrr:$addr)), "
               << "(" << ANDOPC << " (" << loadOpcReg
               << " ADDRrr:$addr), 65535)>;" << std::endl;
            os << "def : Pat<(i" << destSize
               << " (zextloadi16 ADDRri:$addr)), "
               << "(" << ANDOPC << " ("
               << loadOpcImm << " ADDRri:$addr), 65535)>;" << std::endl;
        }
    } else {
        if (!mach_.hasOperation(uload)) {
            std::cerr << "Warning: The architecture is missing any 16-bit loads."
                      << std::endl;
            return;
        }
        loadOpcReg = uload + dstTypeChar + regSrcChar;
        loadOpcImm = uload + dstTypeChar + immSrcChar;
        if (mach_.hasOperation(EXTOP)) {
            // use zextload + sext for sextload
            os << "def : Pat<(i" << destSize
               << " (sextloadi16 ADDRrr:$addr)), "
               << "(" << EXTOPC
               << " (" << loadOpcReg << " ADDRrr:$addr))>;" << std::endl;
            os << "def : Pat<(i" << destSize
               << " (sextloadi16 ADDRri:$addr)), "
               << "(" << EXTOPC
               << " (" << loadOpcImm << " ADDRri:$addr))>;" << std::endl;
        } else {
            if (mach_.hasOperation(SHL) && mach_.hasOperation(SHR)) {
                int sb = bits -16;
                os << "def : Pat<(i" << destSize
                   << " (sextloadi16 ADDRrr:$addr)), "
                   << "(" << SHROPC << " (" << SHLOPC << " ("
                   << load << "rr ADDRrr:$addr), "
                   << sb << "), " << sb << ")>;" << std::endl;
                os << "def : Pat<(i" << destSize
                   << " (sextloadi16 ADDRri:$addr)), "
                   << "(" << SHROPC << " (" << SHLOPC << " ("
                   << load << "ri ADDRri:$addr), "
                   << sb << "), " << sb << ")>;" << std::endl;
            } else if (mach_.hasOperation(SHL4) &&
                       mach_.hasOperation(SHR4)) {
                if (!mach_.is64bit()) {
                    os << "def : Pat<(i32 (sextloadi16 ADDRrr:$addr)), "
                       << "(SHR4_32rr (SHR4_32rr (SHR4_32rr (SHR4_32rr "
                       << "(SHL4_32rr (SHL4_32rr (SHL4_32rr (SHL4_32rr ("
                       << load << "rr ADDRrr:$addr)))))))))>;" << std::endl;
                    os << "def : Pat<(i32 (sextloadi16 ADDRri:$addr)), "
                       << "(SHR4_32rr (SHR4_32rr (SHR4_32rr (SHR4_32rr "
                       << "(SHL4_32rr (SHL4_32rr (SHL4_32rr (SHL4_32rr ("
                       << load << "ri ADDRri:$addr)))))))))>;" << std::endl;
                } else {
                    os << "def : Pat<(i64 (sextloadi8 ADDRrr:$addr)), "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss ("
                       << load << "rr ADDRrr:$addr)))))))))))))>;"
                       << std::endl;
                    os << "def : Pat<(i64 (sextloadi8 ADDRri:$addr)), "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHR4_64ss (SHR4_64ss (SHR4_64ss (SHR4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss "
                       << "(SHL4_64ss (SHL4_64ss (SHL4_64ss (SHL4_64ss ("
                       << load << "ri ADDRri:$addr)))))))))))))>;"
                       << std::endl;
                }
            } else {
                std::cerr << "Warning: no sign-extending 16-bit loads,"
                          << " 16-bit sign extension instruction or suitable"
                          << " shifts for sext-emulation in the processor."
                          << " All code may not compile!" << std::endl;
            }
        }
    }
    // anyext
    os << "def : Pat<(i" << destSize << " (extloadi16 ADDRrr:$src)), ("
       << loadOpcReg << " ADDRrr:$src)>;" << std::endl
       << "def : Pat<(i" << destSize << " (extloadi16 ADDRri:$src)), ("
       << loadOpcImm << " ADDRri:$src)>;" << std::endl;
}
References TTAMachine::Machine::hasOperation(), TTAMachine::Machine::is64bit(), littleEndian_, mach_, OT_IMM_INT, OT_IMM_LONG, OT_REG_INT, and OT_REG_LONG.
Referenced by writeInstrInfo().
createTrivialDAG()
OperationDAG * TDGen::createTrivialDAG (Operation & op) protected
Creates a dummy dag for an OSAL operation.
Parameters
op Operation to create OperationDAG for.
Returns
OperationDAG consisting of only one operation node referencing the given operation.
Definition at line 6093 of file TDGen.cc.
{
    OperationDAG* dag = new OperationDAG(op.impl());
    OperationNode* opNode = new OperationNode(op);
    dag->addNode(*opNode);
    for (int i = 0; i < op.numberOfInputs() + op.numberOfOutputs(); i++) {
        const Operand& operand = op.operand(i + 1);
        TerminalNode* t = new TerminalNode(operand.index());
        dag->addNode(*t);
        if (operand.isInput()) {
            OperationDAGEdge* e = new OperationDAGEdge(1, operand.index());
            dag->connectNodes(*t, *opNode, *e);
        } else {
            OperationDAGEdge* e = new OperationDAGEdge(operand.index(), 1);
            dag->connectNodes(*opNode, *t, *e);
        }
    }
    return dag;
}
References BoostGraph< GraphNode, GraphEdge >::addNode(), BoostGraph< GraphNode, GraphEdge >::connectNodes(), Operation::impl(), Operand::index(), Operand::isInput(), Operation::numberOfInputs(), Operation::numberOfOutputs(), and Operation::operand().
Referenced by writeOperationDef(), and RISCVTDGen::writePatternDefinition().
createVectorMinMaxDef()
void TDGen::createVectorMinMaxDef (const TCEString & opName, int bits, char llvmTypeChar, const TCEString & postFix, std::ostream & os) protected
Definition at line 6380 of file TDGen.cc.
                    {
    for (int elemCount=2; elemCount <= 1024; elemCount<<=1) {
    TCEString opName = baseOpName;
    opName << bits << "X" << elemCount << postFix;
    TCEString vecType = "v";
    vecType << elemCount << (TCEString)(llvmTypeChar) << bits;
    createMinMaxDef(opName, vecType, os);
    }
}
References createMinMaxDef().
Referenced by createMinMaxGenerator().
createVectorRVDRegNums()
void TDGen::createVectorRVDRegNums (std::ostream & os) protected virtual
Definition at line 7022 of file TDGen.cc.
{
    os <<
        "std::vector<unsigned>" << std::endl <<
        "GeneratedTCEPlugin::getVectorRVDRegNums() const {" << std::endl <<
        "std::vector<unsigned> res;" << std::endl;
    std::set<TCEString> processedRegs;
    for (auto rcIt : vRegClasses_) {
        const RegisterClass& regClass = rcIt.second;
        int width = regClass.valueType().width();
        if (regClass.numberOfRegisters() > 0) {
            const TCEString& name = regClass.registerInfo(0).regName_;
            if (processedRegs.find(name) == processedRegs.end() &&
                width > maxScalarWidth_) {
                processedRegs.insert(name);
                os << "res.push_back(TCE::" << name << ");" << std::endl;
            }
        }
    }
    os << "return res;}" << std::endl;
}
References maxScalarWidth_, TDGenerator::RegisterClass::numberOfRegisters(), TDGenerator::RegisterClass::registerInfo(), TDGenerator::RegisterInfo::regName_, TDGenerator::RegisterClass::valueType(), vRegClasses_, and TDGenerator::ValueType::width().
Referenced by writeBackendCode().
dagNodeToString()
std::string TDGen::dagNodeToString (const Operation & op, const OperationDAG & dag, const OperationDAGNode & node, bool emulationPattern, const std::string & operandTypes, const Operation * emulatingOp = nullptr, const OperationDAGNode * successor = nullptr) protected
Converts single OperationDAG node to llvm pattern fragment string.
Parameters
op Operation that the whole DAG is for.
dag Whole operation DAG.
node DAG node to return string for.
immOp Index of an operand to define as an immediate or 0 if none.
emulationPattern True, if the returned string should be in emulation pattern format.
Returns
DAG node as a llvm .td string.
Definition at line 5506 of file TDGen.cc.
{
    const OperationNode* oNode = dynamic_cast<const OperationNode*>(&node);
    if (oNode != NULL) {
        assert(
            dag.inDegree(*oNode) ==
            oNode->referencedOperation().numberOfInputs());
        return operationNodeToString(
            op, dag, *oNode, emulationPattern, operandTypes);
    }
    const TerminalNode* tNode = dynamic_cast<const TerminalNode*>(&node);
    if (tNode != NULL) {
        const Operand& operand = op.operand(tNode->operandIndex());
        if (dag.inDegree(*tNode) == 0) {
            // Input operand for the whole operation.
            assert(operand.isInput());
            char operandType =
                operandTypes[operand.index()-1 + op.numberOfOutputs()];
            bool imm =  (operandType == OT_IMM_INT ||
                         operandType == OT_IMM_BOOL);
            if (imm && !canBeImmediate(dag, *tNode)) {
                std::string msg =
                    "Invalid immediate operand for " + op.name() +
                    " operand #" + Conversion::toString(tNode->operandIndex());
                throw InvalidData(__FILE__, __LINE__, __func__, msg);
            }
            if (emulationPattern) {
                assert(emulatingOp != nullptr);
                return operandToString(operand, false, operandType,
                    immOperandDefs_[ImmInfo::key(
                        *emulatingOp, operand)]);
            } else {
                return operandToString(operand, false, operandType,
                    immOperandDefs_[ImmInfo::key(op, operand)]);
            }
        } else {
            // Output operand for the whole operation.
            assert(dag.inDegree(*tNode) == 1);
            assert(op.operand(tNode->operandIndex()).isOutput());
            assert(operand.isOutput());
            int globalOperandIndex =
                tNode->operandIndex() - op.numberOfInputs();
            assert(globalOperandIndex == 1);
            const OperationDAGEdge& edge = dag.inEdge(node, 0);
            const OperationDAGNode& srcNode = dag.tailNode(edge);
            // Multiple-output operation nodes not supported in the middle
            // of dag:
            assert(dag.outDegree(srcNode) == 1);
            std::string dnString =
                dagNodeToString(
                    op, dag, srcNode, emulationPattern, operandTypes,
                    emulatingOp, successor);
            bool needTrunc = (operandTypes[globalOperandIndex-1] ==
                              OT_REG_BOOL &&
                              operandTypes[1] != OT_REG_BOOL &&
                              operandTypes[1] != OT_IMM_BOOL);
            // handle setcc's without trunc
            // also loads and extends.
            if (needTrunc) {
                if (dnString.substr(0,4) == "(set" ||
                    dnString.substr(0,5) == "(zext" ||
                    dnString.substr(0,5) == "(load") {
                    needTrunc = false;
                }
            }
            if (needTrunc) {
                std::string pattern =
                    "(set " + operandToString(
                        operand, emulationPattern, operandTypes[0])
                    + ", (trunc " + dnString + "))";
                return pattern;
            } else {
                std::string pattern =
                    "(set " + operandToString(
                        operand, emulationPattern, operandTypes[0])
                    + ", " + dnString + ")";
                return pattern;
            }
        }
    }
    // Constant values.
    const ConstantNode* cNode = dynamic_cast<const ConstantNode*>(&node);
    if (cNode != NULL) {
        return constantNodeString(op, dag, *cNode, operandTypes, successor);
    }
    abortWithError("Unknown OperationDAG node type.");
    return "";
}
References __func__, abortWithError, assert, canBeImmediate(), constantNodeString(), dagNodeToString(), immOperandDefs_, BoostGraph< GraphNode, GraphEdge >::inDegree(), Operand::index(), BoostGraph< GraphNode, GraphEdge >::inEdge(), Operand::isInput(), Operand::isOutput(), ImmInfo::key(), Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), TerminalNode::operandIndex(), operandToString(), operationNodeToString(), OT_IMM_BOOL, OT_IMM_INT, OT_REG_BOOL, BoostGraph< GraphNode, GraphEdge >::outDegree(), OperationNode::referencedOperation(), BoostGraph< GraphNode, GraphEdge >::tailNode(), and Conversion::toString().
Referenced by dagNodeToString(), operationNodeToString(), operationPattern(), subPattern(), and writeEmulationPattern().
emulatingOpNodeLLVMName()
std::string TDGen::emulatingOpNodeLLVMName (const Operation & op, const OperationDAG & dag, const OperationNode & node, const std::string & operandTypes) protected
Returns an llvm name for an operation node in an emulation dag.
Parameters
op the operation being emulated.
dag dag of the emulated operation
node node whose name is being asked
operandTypes string containing oeprand types for the emulated op.
Definition at line 5674 of file TDGen.cc.
{
    const Operation& operation = node.referencedOperation();
    std::string operationName = StringTools::stringToUpper(operation.name());
    int inputs = operation.numberOfInputs();
    // Look at outgoing nodes. If operand goes to another op,
    // the value is in register.
    // if it's terminal, get the type from the paramete string.
    for (int i = 1 ; i < operation.numberOfOutputs() + 1; i++) {
        char c = 0;
        for (int e = 0; e < dag.outDegree(node); e++) {
            const OperationDAGEdge& edge = dag.outEdge(node, e);
            int dst = edge.srcOperand();
            if (dst == i + operation.numberOfInputs()) {
                TerminalNode* t =
                    dynamic_cast<TerminalNode*>(
                        &(dag.headNode(edge)));
                if (t != NULL) {
                    int strIndex = t->operandIndex() -1 -
                        op.numberOfInputs();
                    assert((int)operandTypes.length() > strIndex &&
                           strIndex >= 0);
                    if (c != 0 && c != operandTypes[strIndex]) {
                        throw InvalidData(__FILE__,__LINE__,__func__,
                                          "conflicting output types!");
                    }
                    c = operandTypes[strIndex];
                } else {
                    Operand &operand =
                        operation.operand(i+operation.numberOfInputs());
                    char type = operandChar(operand);
                    if (c != 0 && c!= type) {
                        throw InvalidData(__FILE__,__LINE__,__func__,
                                              "conflicting output types!");
                    }
                    c = type;
                }
            }
        }
        if (c == 0) {
            throw InvalidData(__FILE__,__LINE__,__func__,"output not found.");
        }
        operationName += c;
    }
    // Look at incoming nodes. If operand comes from another op,
    // the value is in register. If operand comes from constant,
    // it's immediate.
    // if it's terminal, get the type from the parm string.
    for (int i = 1; i < inputs + 1; i++) {
        Operand &operand = operation.operand(i);
        for (int e = 0; e < dag.inDegree(node); e++) {
            const OperationDAGEdge& edge = dag.inEdge(node, e);
            int dst = edge.dstOperand();
            if (dst == i) {
                if (dynamic_cast<OperationNode*>(&(dag.tailNode(edge)))) {
                    operationName += operandChar(operand);
                } else {
                    if (dynamic_cast<ConstantNode*>(
                            &(dag.tailNode(edge)))) {
                        if (operand.type() == Operand::SINT_WORD ||
                            operand.type() == Operand::UINT_WORD) {
                            operationName += OT_IMM_INT;
                        } else if (operand.type() == Operand::RAW_DATA ||
                                   operand.type() == Operand::SLONG_WORD ||
                                   operand.type() == Operand::ULONG_WORD) {
                            operationName += mach_.is64bit() ?
                                OT_IMM_LONG : OT_IMM_INT;
                        }
                    } else {
                        TerminalNode* t =
                            dynamic_cast<TerminalNode*>(
                                &(dag.tailNode(edge)));
                        assert (t != NULL);
                        int strIndex = t->operandIndex() -1 +
                            op.numberOfOutputs();
                        if ((int)operandTypes.length() <= strIndex ||
                            strIndex <= 0) {
                            std::cerr << "Invalid operand types length or"
                                      << "strIndex in operation:"
                                      << operation.name()
                                      << " OperandTypes string is: "
                                      << operandTypes
                                      << " strIndex is: " << strIndex
                                      << std::endl;
                            assert(false);
                        }
                        operationName += operandTypes[strIndex];
                    }
                }
            }
        }
    }
    return operationName;
}
References __func__, assert, OperationDAGEdge::dstOperand(), BoostGraph< GraphNode, GraphEdge >::headNode(), BoostGraph< GraphNode, GraphEdge >::inDegree(), BoostGraph< GraphNode, GraphEdge >::inEdge(), TTAMachine::Machine::is64bit(), mach_, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), operandChar(), TerminalNode::operandIndex(), OT_IMM_INT, OT_IMM_LONG, BoostGraph< GraphNode, GraphEdge >::outDegree(), BoostGraph< GraphNode, GraphEdge >::outEdge(), Operand::RAW_DATA, OperationNode::referencedOperation(), Operand::SINT_WORD, Operand::SLONG_WORD, OperationDAGEdge::srcOperand(), StringTools::stringToUpper(), BoostGraph< GraphNode, GraphEdge >::tailNode(), Operand::type(), Operand::UINT_WORD, and Operand::ULONG_WORD.
Referenced by operationNodeToString().
gatherAllMachineOperations()
void TDGen::gatherAllMachineOperations () protected
Gathers all machine op names and sorts them to vector and scalar operations.
Definition at line 997 of file TDGen.cc.
{
    // Get all operation names to one container.
    allOpNames_ = MachineInfo::getOpset(mach_);
    OperationPool opPool;
    OperationDAGSelector::OperationSet::const_iterator it;
    for (it = allOpNames_.begin(); it != allOpNames_.end(); ++it) {
        TCEString opName = *it;
        Operation* op = &opPool.operation(opName.c_str());
        if (op != &NullOperation::instance()) {
            if (op->isVectorOperation()) {
                vectorOps_.insert(std::make_pair(opName, op));
            } else {
                scalarOps_.insert(std::make_pair(opName, op));
            }
        }
    }
}
References allOpNames_, MachineInfo::getOpset(), NullOperation::instance(), Operation::isVectorOperation(), mach_, OperationPool::operation(), scalarOps_, and vectorOps_.
Referenced by writeRegisterInfo().
generateBackend() [1/2]
std::string TDGen::generateBackend () const virtual
Writes tce backend plugin code into a single string. Used for hash generation.
Reimplemented in RISCVTDGen.
Definition at line 486 of file TDGen.cc.
{
    const std::string buffer = registerInfo_ + addressingModeDefs_
        + operandDefs_ + instrInfo_ + instrFormats_ + callingConv_
        + argRegsArray_ + backendCode_ + topLevelTD_;
    return buffer;
}
References addressingModeDefs_, argRegsArray_, backendCode_, callingConv_, instrFormats_, instrInfo_, operandDefs_, registerInfo_, and topLevelTD_.
generateBackend() [2/2]
void TDGen::generateBackend (const std::string & path) const virtual
Generates all files required to build a tce backend plugin (excluding static plugin code included from include/llvm/TCE/).
Reimplemented in RISCVTDGen.
Definition at line 431 of file TDGen.cc.
{
    std::ofstream regTD;
    regTD.open((path + "/GenRegisterInfo.td").c_str());
    regTD << registerInfo_;
    regTD.close();
    std::ofstream instrTD0;
    instrTD0.open((path + "/GenInstrInfo0.td").c_str());
    instrTD0 << addressingModeDefs_;
    instrTD0.close();
    std::ofstream operandTD;
    operandTD.open((path + "/GenOperandInfo.td").c_str());
    operandTD << operandDefs_;
    operandTD.close();
    std::ofstream instrTD;
    instrTD.open((path + "/GenInstrInfo.td").c_str());
    instrTD << instrInfo_;
#ifdef DEBUG_TDGEN
    writeInstrInfo(std::cerr);
#endif
    instrTD.close();
    std::ofstream formatTD;
    formatTD.open((path + "/GenTCEInstrFormats.td").c_str());
    formatTD << instrFormats_;
    formatTD.close();
    std::ofstream ccTD;
    ccTD.open((path + "/GenCallingConv.td").c_str());
    ccTD << callingConv_;
    ccTD.close();
    std::ofstream argArr;
    argArr.open((path + "/ArgRegs.hh").c_str());
    argArr << argRegsArray_;
    argArr.close();
    std::ofstream pluginInc;
    pluginInc.open((path + "/Backend.inc").c_str());
    pluginInc << backendCode_;
    pluginInc.close();
    std::ofstream topLevelTD;
    topLevelTD.open((path + "/TCE.td").c_str());
    topLevelTD << topLevelTD_;
    topLevelTD.close();
}
References addressingModeDefs_, argRegsArray_, backendCode_, callingConv_, instrFormats_, instrInfo_, operandDefs_, registerInfo_, topLevelTD_, and writeInstrInfo().
Referenced by LLVMBackend::createPlugin(), and LLVMBackend::pluginFilename().
generateLoadStoreCopyGenerator()
void TDGen::generateLoadStoreCopyGenerator (std::ostream & os) protected
Generates implementations of getLoad() and getStore() to Backend.inc file.
Parameters
os Output stream to the file.
Definition at line 6365 of file TDGen.cc.
{
    genGeneratedTCEPlugin_getStore(os);
    genGeneratedTCEPlugin_getLoad(os);
}
References genGeneratedTCEPlugin_getLoad(), and genGeneratedTCEPlugin_getStore().
Referenced by writeBackendCode().
genGeneratedTCEPlugin_getAddOpcode()
void TDGen::genGeneratedTCEPlugin_getAddOpcode (std::ostream & o) const protected
Definition at line 3285 of file TDGen.cc.
{
    o << endl
      << "// Returns correct vector ADD opcode" << endl
      << "int GeneratedTCEPlugin::getAddOpcode("
      << "const EVT& vt) const {" << endl;
    for (auto it = addOperations_.begin(); it != addOperations_.end(); ++it) {
        o << "\tif (vt == MVT::" << it->first
          << ") return TCE::" << it->second << ";" << endl;
    }
    o << "\treturn -1;" << endl << "}" << endl;
}
References addOperations_.
Referenced by writeBackendCode().
genGeneratedTCEPlugin_getConstantVectorShuffleOpcode()
void TDGen::genGeneratedTCEPlugin_getConstantVectorShuffleOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getExtractElemOpcode()
void TDGen::genGeneratedTCEPlugin_getExtractElemOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getGatherOpcode()
void TDGen::genGeneratedTCEPlugin_getGatherOpcode (std::ostream & o) const protected
Definition at line 3255 of file TDGen.cc.
{
    o << endl
      << "// Returns correct vector GATHER opcode" << endl
      << "int GeneratedTCEPlugin::getGatherOpcode("
      << "const EVT& vt) const {" << endl;
    for (auto it = gatherOperations_.begin(); it != gatherOperations_.end();
         ++it) {
        o << "\tif (vt == MVT::" << it->first
          << ") return TCE::" << it->second << ";" << endl;
    }
    o << "\treturn -1;" << endl << "}" << endl;
}
References gatherOperations_.
genGeneratedTCEPlugin_getIorOpcode()
void TDGen::genGeneratedTCEPlugin_getIorOpcode (std::ostream & o) const protected
Definition at line 3315 of file TDGen.cc.
{
    o << endl
      << "// Returns correct vector SHL opcode" << endl
      << "int GeneratedTCEPlugin::getIorOpcode("
      << "const EVT& vt) const {" << endl;
    for (auto it = iorOperations_.begin(); it != iorOperations_.end(); ++it) {
        o << "\tif (vt == MVT::" << it->first
          << ") return TCE::" << it->second << ";" << endl;
    }
    o << "\treturn -1;" << endl << "}" << endl;
}
References iorOperations_.
Referenced by writeBackendCode().
genGeneratedTCEPlugin_getLoad()
void TDGen::genGeneratedTCEPlugin_getLoad (std::ostream & o) const protected
Generates implementation of getLoad() function.
Definition at line 2939 of file TDGen.cc.
{
    TCEString prefix = "&"; // Address of -operator.
    TCEString rcpf = "RegsRegClass";
    TCEString rapf = "TCE::RARegRegClass";
    TCEString loadB = littleEndian_ ? "LD8" : "LDQ";
    if (!mach_.hasOperation(loadB)) {
        loadB = littleEndian_ ? "LDU8" : "LDQU";
        if (!mach_.hasOperation(loadB)) {
            loadB="";
        }
    }
    TCEString loadW = littleEndian_ ? "LD32" : "LDW";
    TCEString loadH = littleEndian_ ? "LD16" : "LDH";
    TCEString loadL = "LD64";
    if (!mach_.hasOperation(loadH)) {
        loadH = littleEndian_ ? "LDU16;" : "LDHU";
        if (!mach_.hasOperation(loadH)) {
            loadH="";
        }
    }
    o << "int GeneratedTCEPlugin::getLoad(const TargetRegisterClass *rc)"
      << " const {" << endl;
    o << "\tif (rc == " << prefix << rapf << ") return TCE::"
      << loadW << "RAr;" << endl;
    if (!mach_.hasOperation(loadW) && mach_.hasOperation("LDU32")) {
        loadW = "LDU32";
    }
    for (RegClassMap::const_iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        if ((ri->first.find("R1") == 0 ||
             ri->first.find(TDGen::guardRegTemplateName) == 0) &&
            ri->first.find("R16") != 0 && loadB != "") {
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << rcpf <<") return TCE::" << loadB << "Br;" << endl;
        }
        if (ri->first.find("R32") == 0) {
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << rcpf << ") return TCE::" << loadW << "rr;" << endl;
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << "I" << rcpf << ") return TCE::" << loadW << "rr;" << endl;
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << "FP" << rcpf << ") return TCE::" << loadW << "fr;" << endl;
            if (loadH != "") {
                o << "\tif (rc == " << prefix << "TCE::" << ri->first
                  << "HFP" << rcpf << ") return TCE::" << loadH << "hr;" << endl;
            }
        }
        if (mach_.is64bit()) {
            if (ri->first.find("R64") == 0) {
                o << "\tif (rc == " << prefix << "TCE::" << ri->first
                  << rcpf << ") return TCE::" << loadL << "ss;" << endl;
                o << "\tif (rc == " << prefix << "TCE::" << ri->first
                  << "I" << rcpf << ") return TCE::" << loadL << "ss;" << endl;
                o << "\tif (rc == " << prefix << "TCE::" << ri->first
                  << "DFP" << rcpf << ") return TCE::" << loadL << "ds;" << endl;
            }
        }
    }
    if (use64bitForFP_) {
        o << "\tif (rc == &TCE::FPRegsRegClass) return TCE::LD64fs;"
          << std::endl;
        o << "\tif (rc == &TCE::HFPRegsRegClass) return TCE::LD64hs;"
           << std::endl;
    } else {
        o << "\tif (rc == &TCE::FPRegsRegClass) return TCE::"
          << loadW << "fr;" << std::endl;
        o << "\tif (rc == &TCE::HFPRegsRegClass) return TCE::"
          << loadW << "hr;" << std::endl;
    }
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString& vtStr = it->first;
        const RegisterClass& regClass = it->second;
        std::map<TCEString, InstructionInfo>::const_iterator loadIt =
            registerLoads_.find(vtStr);
        if (loadIt != registerLoads_.end()) {
            o << "\tif (rc == &TCE::" << regClass.name() << "RegClass) "
              << "return TCE::" << (loadIt->second).instrName_ << ";" << endl;
        } else {
            verbose("Warning: no load generated for RegisterClass " +
                    regClass.name() + " to GeneratedTCEPlugin::getLoad");
        }
    }
    o  << "\tprintf(\"regclass of size %d \\n\", rc->MC->RegsSize);" << std::endl
      << "\tassert(0&&\"loading from stack to given regclass not supported."
      << " Bug in backend?\");"
      << endl
      << "} " << endl
      << endl;
}
References guardRegTemplateName, TTAMachine::Machine::hasOperation(), TTAMachine::Machine::is64bit(), littleEndian_, mach_, TDGenerator::RegisterClass::name(), registerLoads_, regsInClasses_, use64bitForFP_, verbose(), and vRegClasses_.
Referenced by generateLoadStoreCopyGenerator().
genGeneratedTCEPlugin_getLoadOpcode()
void TDGen::genGeneratedTCEPlugin_getLoadOpcode (std::ostream & o) const protected
Definition at line 3271 of file TDGen.cc.
{
    o << endl
      << "// Returns correct load opcode" << endl
      << "int GeneratedTCEPlugin::getLoadOpcode("
      << "const EVT& vt) const {" << endl;
    for (auto it = registerLoads_.begin(); it != registerLoads_.end(); ++it) {
        o << "\tif (vt == MVT::" << it->first
          << ") return TCE::" << it->second.instrName_ << ";" << endl;
    }
    o << "\treturn -1;" << endl << "}" << endl;
}
References registerLoads_.
Referenced by writeBackendCode().
genGeneratedTCEPlugin_getShlOpcode()
void TDGen::genGeneratedTCEPlugin_getShlOpcode (std::ostream & o) const protected
Definition at line 3300 of file TDGen.cc.
{
    o << endl
      << "// Returns correct vector SHL opcode" << endl
      << "int GeneratedTCEPlugin::getShlOpcode("
      << "const EVT& vt) const {" << endl;
    for (auto it = shlOperations_.begin(); it != shlOperations_.end(); ++it) {
        o << "\tif (vt == MVT::" << it->first
          << ") return TCE::" << it->second << ";" << endl;
    }
    o << "\treturn -1;" << endl << "}" << endl;
}
References shlOperations_.
Referenced by writeBackendCode().
genGeneratedTCEPlugin_getStore()
void TDGen::genGeneratedTCEPlugin_getStore (std::ostream & o) const protected
Generates implementation of getStore() function.
Definition at line 2839 of file TDGen.cc.
{
    TCEString prefix = "&"; // Address of -operator.
    TCEString rcpf = "RegsRegClass";
    TCEString rapf = "TCE::RARegRegClass";
    TCEString storeB = littleEndian_ ? "ST8Brb;" : "STQBrb;";
    TCEString storeW = littleEndian_ ? "ST32" : "STW";
    TCEString storeH = littleEndian_ ? "ST16" : "STH";
    TCEString storeL = "ST64";
    o << "#include <stdio.h>" << endl
      << "int GeneratedTCEPlugin::getStore(const TargetRegisterClass *rc)"
      << " const {" << endl;
    o << "\tif (rc == " << prefix << rapf
      << ") return TCE::STWRArr;"
      << endl;
    for (RegClassMap::const_iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        if ((ri->first.find("R1") == 0 ||
             ri->first.find(TDGen::guardRegTemplateName) == 0) &&
            ri->first.find("R16") != 0) {
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << rcpf << ") return TCE::" << storeB << endl;
        }
        if (ri->first.find("R32") == 0) {
            o << "\tif (rc == " << prefix << "TCE::" << ri->first
              << rcpf << ") return TCE::" << storeW << "rr;" << endl;
            o << "\tif (rc == " << prefix << "TCE::"  << ri->first
              << "I" << rcpf << ") return TCE::" << storeW << "rr;" << endl;
            o << "\tif (rc == " << prefix << "TCE::"  << ri->first
              << "FP" << rcpf << ") return TCE::" << storeW << "fr;" << endl;
            o << "\tif (rc == " << prefix << "TCE::"  << ri->first
              << "HFP" << rcpf << ") return TCE::" << storeH << "hr;" << endl;
        }
        if (mach_.is64bit()) {
            if (ri->first.find("R64") == 0) {
                o << "\tif (rc == " << prefix << "TCE::" << ri->first
                  << rcpf << ") return TCE::" << storeL << "ss;" << endl;
                o << "\tif (rc == " << prefix << "TCE::"  << ri->first
                  << "I" << rcpf << ") return TCE::" << storeL << "ss;"
                  << endl;
                o << "\tif (rc == " << prefix << "TCE::"  << ri->first
                  << "DFP" << rcpf << ") return TCE::" << storeL << "ds;"
                  << endl;
            }
                // TODO: double support here?
        }
    }
    if (use64bitForFP_) {
        o << "\tif (rc == &TCE::FPRegsRegClass) return TCE::ST64fs;"
          << std::endl;
        o << "\tif (rc == &TCE::HFPRegsRegClass) return TCE::ST64hs;"
          << std::endl;
    } else {
        o << "\tif (rc == &TCE::FPRegsRegClass) return TCE::"
          << storeW << "fr;" << std::endl;
        o << "\tif (rc == &TCE::HFPRegsRegClass) return TCE::"
          << storeW << "hr;" << std::endl;
    }
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString& vtStr = it->first;
        const RegisterClass& regClass = it->second;
        std::map<TCEString, InstructionInfo>::const_iterator storeIt =
            registerStores_.find(vtStr);
        if (storeIt != registerStores_.end()) {
            o << "\tif (rc == &TCE::" << regClass.name() << "RegClass) "
              << "return TCE::" << (storeIt->second).instrName_ << ";" << endl;
        } else {
            verbose("Warning: no store generated for RegisterClass " +
                    regClass.name() + " to GeneratedTCEPlugin::getStore");
        }
    }
    o << "\tstd::cerr << \"regclass id:\" <<rc->getID() << \"of size \" "
      << "<<rc->MC->RegsSize<< std::endl;" << std::endl;
    o  << "\tassert(0&&\"Storing given regclass to stack not supported. "
       << "Bug in backend?\");"
       << endl
       << "} " << endl
       << endl;
}
References guardRegTemplateName, TTAMachine::Machine::is64bit(), littleEndian_, mach_, TDGenerator::RegisterClass::name(), registerStores_, regsInClasses_, use64bitForFP_, verbose(), and vRegClasses_.
Referenced by generateLoadStoreCopyGenerator().
genGeneratedTCEPlugin_getVectorAndSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorAndSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorBroadcastOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorBroadcastOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorImmediateOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorImmediateOpcode (std::ostream & o) const protected
Definition at line 3235 of file TDGen.cc.
{
    backendCode << "int GeneratedTCEPlugin::getVectorImmediateOpcode(const "
                   "EVT& vt) const {"
                << std::endl;
    for (auto it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        TCEString regClassName = regClass.name();
        ValueType valType = regClass.valueType();
        TCEString valTypeName = valType.valueTypeStr();
        if (valType.width() <= 32) {
            TCEString opName = "MOVI" + valTypeName;
            backendCode << "\tif (vt == MVT::" << valTypeName
                        << ") return TCE::" << opName << ";" << std::endl;
        }
    }
    backendCode << "\treturn -1;\n}" << endl;
}
References TDGenerator::RegisterClass::name(), TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), vRegClasses_, and TDGenerator::ValueType::width().
genGeneratedTCEPlugin_getVectorIorSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorIorSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorPackOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorPackOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorSelectOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorSelectOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorShlSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorShlSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorShrSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorShrSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorShruSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorShruSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorShuffle1Opcode()
void TDGen::genGeneratedTCEPlugin_getVectorShuffle1Opcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorShuffle2Opcode()
void TDGen::genGeneratedTCEPlugin_getVectorShuffle2Opcode (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorValueType()
void TDGen::genGeneratedTCEPlugin_getVectorValueType (std::ostream & o) const protected
genGeneratedTCEPlugin_getVectorXorSameOpcode()
void TDGen::genGeneratedTCEPlugin_getVectorXorSameOpcode (std::ostream & o) const protected
genGeneratedTCEPlugin_isVectorRegisterMove()
void TDGen::genGeneratedTCEPlugin_isVectorRegisterMove (std::ostream & o) const protected
genTCEInstrInfo_copyPhys64bitReg()
void TDGen::genTCEInstrInfo_copyPhys64bitReg (std::ostream & o) const protected
Definition at line 8396 of file TDGen.cc.
{
    o << std::endl
      << "#include <llvm/CodeGen/MachineInstrBuilder.h>" << std::endl
      << "// copies 64-bit reg to a another" << std::endl
      << "bool TCEInstrInfo::copyPhys64bitReg(" << std::endl
      << "\tMachineBasicBlock& mbb," << std::endl
      << "\tMachineBasicBlock::iterator mbbi," << std::endl
      <<  "const DebugLoc& dl," << std::endl
      << "\tunsigned destReg, unsigned srcReg," << std::endl
      << "\tbool killSrc) const {" << std::endl
      << std::endl;
    if (mach_.is64bit()) {
        o << "\tif (TCE::R64RegsRegClass.contains(destReg, srcReg)) {\n"
          << "\t\tBuildMI(mbb, mbbi, dl, get(TCE::MOV64rr), destReg)\n"
          << "\t\t\t.addReg(srcReg, getKillRegState(killSrc));" << std::endl
          << "\t\treturn true;" << std::endl
          << "}" << std::endl;
    }
    o << "\treturn false;" << std::endl
      << "}";
}
References TTAMachine::Machine::is64bit(), and mach_.
genTCEInstrInfoSIMD_copyPhysVectorReg()
void TDGen::genTCEInstrInfoSIMD_copyPhysVectorReg (std::ostream & o) const protected
Generates implementation of copyPhysVectorReg().
Only the previously created vector register classes are added to the implementation to make LLVM compilation flow work.
Definition at line 3187 of file TDGen.cc.
{
    o << endl
      << "#include <llvm/CodeGen/MachineInstrBuilder.h>" << endl
      << "// Copies a vector register to another" << endl
      << "bool TCEInstrInfo::copyPhysVectorReg(" << endl
      << "\tMachineBasicBlock& mbb," << endl
      << "\tMachineBasicBlock::iterator mbbi," << endl
      << "const DebugLoc& dl," << endl
      << "\tMCRegister destReg, MCRegister srcReg," << endl
      << "\tbool killSrc) const {" << endl
      << endl;
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        o << "\tif (TCE::" << regClass.name()
          << "RegClass.contains(destReg, srcReg)) {" << endl
          << "\t\tBuildMI(mbb, mbbi, dl, get(TCE::"
          << "MOV" << regClass.name() << "), destReg)" << endl
          << "\t\t.addReg(srcReg, getKillRegState(killSrc));" << endl
          << "\t\treturn true;" << endl
          << "\t}" << endl;
    }
    o << "\treturn false;" << endl << "}" << endl;
}
References TDGenerator::RegisterClass::name(), and vRegClasses_.
Referenced by writeBackendCode().
genTCERegisterInfo_setReservedVectorRegs()
void TDGen::genTCERegisterInfo_setReservedVectorRegs (std::ostream & os) const protected
Definition at line 4203 of file TDGen.cc.
{
    os << "void TCERegisterInfo::setReservedVectorRegs("
       << "llvm::BitVector& reserved) const {" << std::endl;
    std::set<TCEString> processedRegs;
    for (auto rcIt : vRegClasses_) {
        const RegisterClass& regClass = rcIt.second;
        int width = regClass.valueType().width();
        if (regClass.numberOfRegisters() > 0) {
            const TCEString& name = regClass.registerInfo(0).regName_;
            if (processedRegs.find(name) == processedRegs.end() &&
                width > maxScalarWidth_) {
                processedRegs.insert(name);
                os << "reserved.set(TCE::" << name << ");" << std::endl;
            }
        }
    }
    os << "}" << std::endl;
}
References maxScalarWidth_, TDGenerator::RegisterClass::numberOfRegisters(), TDGenerator::RegisterClass::registerInfo(), TDGenerator::RegisterInfo::regName_, TDGenerator::RegisterClass::valueType(), vRegClasses_, and TDGenerator::ValueType::width().
Referenced by writeBackendCode().
genTCETargetLoweringSIMD_addVectorRegisterClasses()
void TDGen::genTCETargetLoweringSIMD_addVectorRegisterClasses (std::ostream & o) const protected
Generates a function that adds existing register classes in lowering phase.
Definition at line 3053 of file TDGen.cc.
{
    o << endl << "// Adds all vector classes to backend" << endl
      << "void TCETargetLowering::addVectorRegisterClasses() {" << endl;
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        o << "\taddRegisterClass("
          << "MVT::" << regClass.valueType().valueTypeStr() << ", "
          << "&TCE::" << regClass.name() << "RegClass);"
          << endl;
    }
    o << "}" << endl;
    o << endl << "// Sets build and extract lowering" << endl
      << "void TCETargetLowering::addVectorLowerings() {" << endl;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        o << "\tsetOperationAction(ISD::BUILD_VECTOR,"
          << "MVT::" << regClass.valueType().valueTypeStr() << ", "
          << "Custom);" << endl;
        o << "\tsetOperationAction(ISD::EXTRACT_SUBVECTOR,"
          << "MVT::" << regClass.valueType().valueTypeStr() << ", "
          << "Expand);" << endl;
        for (auto vt : ValueType::SUPPORTED_LLVM_VALUE_TYPES) {
            if (vRegClasses_.find(vt) == vRegClasses_.end()) {
                o << "\tsetTruncStoreAction(MVT::"
                  << regClass.valueType().valueTypeStr()
                  << ", MVT::" << vt << ", Expand);" << endl;
            }
        }
    }
    o << "}" << endl;
}
References TDGenerator::RegisterClass::name(), TDGenerator::ValueType::SUPPORTED_LLVM_VALUE_TYPES, TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
Referenced by writeBackendCode().
genTCETargetLoweringSIMD_associatedVectorRegClass()
void TDGen::genTCETargetLoweringSIMD_associatedVectorRegClass (std::ostream & o) const protected
Generates a function that returns correct reg class for a value type.
Definition at line 3098 of file TDGen.cc.
{
    o << endl << "// Returns vector register class for given value type"
      << endl
      << "std::pair<unsigned, const TargetRegisterClass*> "
      << "TCETargetLowering::associatedVectorRegClass(const EVT& vt) "
      << "const {"
      << endl;
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString& vtStr = it->first;
        const RegisterClass& regClass = it->second;
        o << "\tif (vt == MVT::" << vtStr << ") "
          << "return std::make_pair(0U, &TCE::"
          << regClass.name() << "RegClass);" << endl;
    }
    o << "\treturn std::make_pair(0U, (TargetRegisterClass*)0);" << endl
      << "}" << endl;
}
References TDGenerator::RegisterClass::name(), and vRegClasses_.
Referenced by writeBackendCode().
genTCETargetLoweringSIMD_getSetCCResultVT()
void TDGen::genTCETargetLoweringSIMD_getSetCCResultVT (std::ostream & o) const protected
Generates a function that returns correct return value type for comparisons.
In LLVM vector comparison operations result into boolean vectors, which have the same subword count as input vectors.
Definition at line 3128 of file TDGen.cc.
{
    o << endl
      << "llvm::EVT TCETargetLowering::getSetCCResultVT(const EVT& vt) "
      << "const {"
      << endl;
    int subwCount = 2;
    while (subwCount <= MAX_SUBW_COUNT) {
        TCEString boolVecVtStr = "v" + Conversion::toString(subwCount) + "i1";
        ValueType boolVecVt(boolVecVtStr);
        if (!boolVecVt.isSupportedByLLVM()) {
            break;
        }
        o << "\tif (vt.getVectorElementCount().getKnownMinValue() == "
          << Conversion::toString(subwCount) << ") return llvm::MVT::"
          << boolVecVtStr << ";" << endl;
        subwCount *= 2;
    }
    o << "\treturn llvm::MVT::INVALID_SIMPLE_VALUE_TYPE;" << endl
      << "}" << endl;
}
References TDGenerator::ValueType::isSupportedByLLVM(), MAX_SUBW_COUNT, and Conversion::toString().
Referenced by writeBackendCode().
getLLVMPatternWithConstants()
TCEString TDGen::getLLVMPatternWithConstants (const Operation & op, const std::string & operandTypes, const std::string & operand0, const std::string & operand1) const protected
Returns LLVM pattern for the expression with constant value(s) supported by target machine.
For example, for pattern (SUBrri (foo ...), 123) the method returns (SUBrrr (foo ...), (MOVI32ri 123)) if the target machine can not supply the constant "123" as an immediate.
The method should be called after all operation definitions have been created (after all calls to writeOperationDef()).
Return empty string if the given pattern can not be handled because:
Operation is not supported by target machine.
Parameters
op The operation.
operandTypes The preferred operand types.
operand0 The pattern for the first operand or constant indicated by operandTypes.
operand1 The pattern for the second operand or constant indicated by operandTypes.
Definition at line 7756 of file TDGen.cc.
{
    //TODO If operation is not supported, try to replace it with an emulation
    //     pattern first and then deal with the new patterns with constant
    //     operands (and take account possible infinite recursion).
    //TODO Cache the calculated results?
    assert(op.numberOfInputs() == 2);
    auto makePattern = [](
        const std::string& opc,
        const std::string& opdTypes,
        const std::string& operand0,
        const std::string& operand1) -> TCEString {
            return std::string("(") + opc + opdTypes + " " + operand0
            + ", " + operand1 + ")";
        };
    std::string opc = StringTools::stringToUpper(op.name());
    const std::string outputOpdTypes = operandTypes.substr(
        0, op.numberOfOutputs());
    const std::string inputOpdTypes = operandTypes.substr(
        op.numberOfOutputs());
    assert(inputOpdTypes.size() == 2);
    const auto regOperandsOnly = operandTypesToRegisters(operandTypes);
    if (!opNames_.count(opc + regOperandsOnly)) {
        // Operation is not supported at all by the target machine.
        return "";
    }
    if (opNames_.count(opc + operandTypes)) {
        // Supported as is.
        return makePattern(opc, operandTypes, operand0, operand1);
    }
    std::vector<std::string> supportedOperandTypes;
    for (auto i = 0u; i < inputOpdTypes.size(); i++) {
        std::string oneInputChanged = inputOpdTypes;
        oneInputChanged[i] = operandTypeToRegister(oneInputChanged[i]);
        if (oneInputChanged == inputOpdTypes) continue;
        if (opNames_.count(opc + outputOpdTypes + oneInputChanged)) {
            supportedOperandTypes.push_back(oneInputChanged);
        }
    }
    supportedOperandTypes.push_back(regOperandsOnly);
    std::vector<const std::string*> inputOpdValues{&operand0, &operand1};
    // Now legalize pattern by changing unsupported immediate operands with
    // immediate moves.
    for (const auto& supportedOpdType : supportedOperandTypes) {
        // Loop throught immediate opd types. Check if constant is encodable
        // for the operation.
        bool isSupported = true;
        for (auto i = 0u; i < supportedOpdType.size(); i++) {
            auto& opdType = supportedOpdType.at(i);
            auto osalOpdIdx = i - op.numberOfInputs() + 1;
            bool ok = false;
            switch (opdType) {
                default:
                    ok = true; // Ok. Not immediate type.
                    break;
                case OT_IMM_INT: {
                    bool isOperandReference =
                        inputOpdValues.at(i)->find(":$") != std::string::npos;
                    if (isOperandReference) {
                        // Size of the constant is not known, must expect the
                        // worst.
                        ok = false;
                        break;
                    }
                    int64_t value = Conversion::toInt(
                        *inputOpdValues.at(i));
                    ok = immInfo_->canTakeImmediate(op, osalOpdIdx, value,
                                                    32);
                }
                    break;
                case OT_IMM_FP:
                    ok = immInfo_->canTakeImmediateByWidth(
                        op, osalOpdIdx, 32);
                    break;
                case OT_IMM_HFP:
                    ok = immInfo_->canTakeImmediateByWidth(
                        op, osalOpdIdx, 16);
                    break;
                case OT_IMM_BOOL:
                    ok = immInfo_->canTakeImmediateByWidth(
                        op, osalOpdIdx, 1);
                    break;
            }
            if (!ok) {
                isSupported = false;
                break;
            }
        }
        if (!isSupported) continue;
        std::string result = std::string("(") + opc + outputOpdTypes
            + supportedOpdType + " ";
        if (supportedOpdType.at(0) == inputOpdTypes.at(0)) {
            result += *inputOpdValues.at(0);
        } else {
            result += getMovePattern(
                inputOpdTypes.at(0), *inputOpdValues.at(0));
        }
        for (auto i = 1u; i < supportedOpdType.size(); i++) {
            result += ", ";
            if (supportedOpdType.at(i) == inputOpdTypes.at(i)) {
                result += *inputOpdValues.at(i);
            } else {
                result += getMovePattern(
                    inputOpdTypes.at(i), *inputOpdValues.at(i));
            }
        }
        result += ")";
        return result;
    }
    return "";
}
References assert, ImmInfo::canTakeImmediate(), ImmInfo::canTakeImmediateByWidth(), getMovePattern(), immInfo_, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), operandTypesToRegisters(), operandTypeToRegister(), opNames_, OT_IMM_BOOL, OT_IMM_FP, OT_IMM_HFP, OT_IMM_INT, StringTools::stringToUpper(), and Conversion::toInt().
Referenced by createSelectPatterns().
getMatchableOperationDAG()
const OperationDAG * TDGen::getMatchableOperationDAG (const Operation & op) protected
Returns first operation DAG that can be used in LLVM pattern.
Operation DAGs are traversed in the order of trigger-semantics in the first .opp file found in path that defines the Operation.
This method does not transfer ownership.
Returns
The matchable operation DAG. Nullptr if could not find.
Definition at line 5361 of file TDGen.cc.
{
    // check if one of dags of operation is ok
    for (int i = 0; i < op.dagCount(); i++) {
        OperationDAG& dag = op.dag(i);
        if (op.dagError(i) != "") {
            std::cerr << "Broken dag in operation " << op.name()
                      << op.dagCode(i) << std::endl;
            assert(0);
        }
        if (operationDAGCanBeMatched(dag)) {
            return &dag;
        }
    }
    return nullptr;
}
References assert, Operation::dag(), Operation::dagCode(), Operation::dagCount(), Operation::dagError(), Operation::name(), and operationDAGCanBeMatched().
Referenced by operationNodeToString(), and writeOperationDef().
getMatchableOperationDAGs()
const std::vector< OperationDAG * > TDGen::getMatchableOperationDAGs (const Operation & op) protected
Returns a vector of DAGs that can be used in LLVM pattern.
Operation DAGs are traversed in the order of trigger-semantics in the first .opp file found in path that defines the Operation.
This method does not transfer ownership.
Returns
The matchable operation DAGs. Empty if could not find.
Definition at line 5391 of file TDGen.cc.
{
    std::vector<OperationDAG*> matchableDAGs;
    for (int i = 0; i < op.dagCount(); i++) {
        OperationDAG& dag = op.dag(i);
        if (op.dagError(i) != "") {
            std::cerr << "Broken dag in operation " << op.name()
                      << op.dagCode(i) << std::endl;
            continue;
        }
        if (operationDAGCanBeMatched(dag)) {
            matchableDAGs.push_back(&dag);
        }
    }
    return matchableDAGs;
}
References Operation::dag(), Operation::dagCode(), Operation::dagCount(), Operation::dagError(), Operation::name(), and operationDAGCanBeMatched().
Referenced by RISCVTDGen::writePatternDefinition().
getMovePattern()
TCEString TDGen::getMovePattern (const char & opdType, const std::string & inputPattern) const protected
Definition at line 7909 of file TDGen.cc.
{
    TCEString pat = "(MOV";
    // Note: This listing is incomplete.
    switch (opdType) {
    case OT_IMM_INT: // Integer immediate.
        pat += std::string("I32") + operandTypeToRegister(opdType) + opdType;
        break;
    case OT_REG_INT: // Integer register.
        pat += std::string("I32") + operandTypeToRegister(opdType) + opdType;
        break;
    case OT_IMM_BOOL: // Boolean immediate.
        pat += "I1ri";  //TODO: this is inconsistent
        break;
    case OT_REG_BOOL: // Boolean register.
        pat += "I1rr"; //TODO: this is inconsistent
        break;
    case OT_IMM_FP: // Single precision floating point immediate.
    case OT_REG_FP: // -||- register.
        pat += std::string("F32") + operandTypeToRegister(opdType) + opdType;
        break;
    case OT_IMM_HFP: // Half precision floating point immediate.
    case OT_REG_HFP: // -||- register.
        pat += std::string("F16") + operandTypeToRegister(opdType) + opdType;
        break;
        // TODO: vector register and immediate types.
    default:
        assert(false && "Handling for a type not implemented");
        break;
    }
    pat += " " + inputPattern + ")";
    return pat;
}
References assert, operandTypeToRegister(), OT_IMM_BOOL, OT_IMM_FP, OT_IMM_HFP, OT_IMM_INT, OT_REG_BOOL, OT_REG_FP, OT_REG_HFP, and OT_REG_INT.
Referenced by getLLVMPatternWithConstants().
hasRawOperands()
bool TDGen::hasRawOperands (const Operation & op) const protected
Checks if operation has operands of raw type.
Parameters
op Operation to be checked.
Returns
True, if operation has at least one operand of raw type.
Definition at line 1755 of file TDGen.cc.
{
    for (int i = 1; i <= op.operandCount(); ++i) {
        const Operand& operand = op.operand(i);
        if (operand.type() == Operand::RAW_DATA && operand.isVector()) {
            return true;
        }
    }
    return false;
}
References Operand::isVector(), Operation::operand(), Operation::operandCount(), Operand::RAW_DATA, and Operand::type().
hasRegisterClassSupport() [1/2]
bool TDGen::hasRegisterClassSupport (const Operation & op) const protected
Checks if all operands of the operation have a supporting register class.
Parameters
op Operation whose operands will be checked.
Returns
True, if all operands are supported by register classes.
Definition at line 1805 of file TDGen.cc.
{
    for (int i = 1; i <= op.operandCount(); ++i) {
        const Operand& operand = op.operand(i);
        if (operand.isVector()) {
            TCEString vtStr = ValueType::valueTypeStr(operand);
            if (vRegClasses_.find(vtStr) == vRegClasses_.end()) {
                return false;
            }
        }
    }
    return true;
}
References Operand::isVector(), Operation::operand(), Operation::operandCount(), TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
Referenced by writeScalarOperationExploitations(), writeVectorBitwiseOperationDefs(), and writeVectorOperationDef().
hasRegisterClassSupport() [2/2]
bool TDGen::hasRegisterClassSupport (const TDGenerator::ValueType & vt) const protected
Checks if the ValueType has a supporting register class.
Parameters
vt ValueType to be checked.
Returns
True, if the value type is supported by a register class.
Definition at line 1827 of file TDGen.cc.
{
    if (vRegClasses_.find(vt.valueTypeStr()) == vRegClasses_.end()) {
        return false;
    }
    return true;
}
References TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
immediateOperandNameForEmulatedOperation()
std::string TDGen::immediateOperandNameForEmulatedOperation (const OperationDAG & dag, const Operand & operand) protected
Returns corresponding immediate operand name for the emulated operation.
Parameters
dag The emulation code of the emulated operation.
operand The operand.
Returns
The operand immediate name if found. Otherwise return empty string.
Definition at line 7584 of file TDGen.cc.
{
    for (const auto& sourceNode : dag.rootNodes()) {
        const TerminalNode* sourceTerminal =
            dynamic_cast<TerminalNode*>(sourceNode);
        if (sourceTerminal == nullptr) continue;
        for (const auto& destEdge : dag.outEdges(*sourceTerminal)) {
            const OperationNode* opNode =
                dynamic_cast<OperationNode*>(&dag.headNode(*destEdge));
            assert(opNode != nullptr &&
                "TerminalNode points to other than OperandNode.");
            const Operation& operation = opNode->referencedOperation();
            ImmInfoKey key = ImmInfo::key(operation, operand);
            if (immOperandDefs_.count(key)) {
                return immOperandDefs_.at(key);
            } else {
                return "";
            }
        }
    }
    return "";
}
References assert, BoostGraph< GraphNode, GraphEdge >::headNode(), immOperandDefs_, ImmInfo::key(), BoostGraph< GraphNode, GraphEdge >::outEdges(), OperationNode::referencedOperation(), and BoostGraph< GraphNode, GraphEdge >::rootNodes().
Referenced by writeEmulationPattern().
immediatePredicate()
std::string TDGen::immediatePredicate (int64_t lowerBoundInclusive, uint64_t upperBoundInclusive) protected
Returns llvm predicate expression for short immediate constraint.
Definition at line 7560 of file TDGen.cc.
{
    // If can transport any 64-bit imm, no need for any checks.
    if (upperBoundInclusive == UINT64_MAX ||
        lowerBoundInclusive == INT64_MIN) {
        return std::string("(true)");
    }
    return std::string("(")
        + Conversion::toString(lowerBoundInclusive) + "ll"
        + " <= Imm && Imm <= "
        + Conversion::toString(upperBoundInclusive) + "ll)";
}
References Conversion::toString().
Referenced by writeIntegerImmediateDefs(), and writeMoveImmediateDefs().
initializeBackendContents()
void TDGen::initializeBackendContents () protected
Definition at line 394 of file TDGen.cc.
{
    std::ostringstream registerInfoBuffer;
    std::ostringstream addressingModeDefsBuffer;
    std::ostringstream operandDefsBuffer;
    std::ostringstream instrInfoBuffer;
    std::ostringstream instrFormatsBuffer;
    std::ostringstream callingConvBuffer;
    std::ostringstream argRegsArrayBuffer;
    std::ostringstream backendCodeBuffer;
    std::ostringstream topLevelTDBuffer;
    writeRegisterInfo(registerInfoBuffer);
    writeAddressingModeDefs(addressingModeDefsBuffer);
    writeOperandDefs(operandDefsBuffer);
    writeInstrInfo(instrInfoBuffer);
    writeInstrFormats(instrFormatsBuffer);
    writeCallingConv(callingConvBuffer);
    writeArgRegsArray(argRegsArrayBuffer);
    writeBackendCode(backendCodeBuffer);
    writeTopLevelTD(topLevelTDBuffer);
    registerInfo_ = registerInfoBuffer.str();
    addressingModeDefs_ = addressingModeDefsBuffer.str();
    operandDefs_ = operandDefsBuffer.str();
    instrInfo_ = instrInfoBuffer.str();
    instrFormats_ = instrFormatsBuffer.str();
    callingConv_ = callingConvBuffer.str();
    argRegsArray_ = argRegsArrayBuffer.str();
    backendCode_ = backendCodeBuffer.str();
    topLevelTD_ = topLevelTDBuffer.str();
}
References addressingModeDefs_, argRegsArray_, backendCode_, callingConv_, instrFormats_, instrInfo_, operandDefs_, registerInfo_, topLevelTD_, writeAddressingModeDefs(), writeArgRegsArray(), writeBackendCode(), writeCallingConv(), writeInstrFormats(), writeInstrInfo(), writeOperandDefs(), writeRegisterInfo(), and writeTopLevelTD().
Referenced by TDGen().
isVectorBitwiseOperation()
bool TDGen::isVectorBitwiseOperation (const Operation & op) const protected
Checks if the given operation is a bitwise operation.
Parameters
op Operation which is checked.
Returns
True, if operation is a bitwise operation.
Definition at line 1995 of file TDGen.cc.
{
    abortWithError("WiP");
    return false;
}
References abortWithError.
Referenced by writeInstrInfo().
isVectorLoadOperation()
bool TDGen::isVectorLoadOperation (const Operation & op) const protected
Checks if the given operation is a vector load memory operation.
Parameters
op Operation which is checked.
Returns
True, if operation is a vector load memory operation.
Definition at line 1965 of file TDGen.cc.
{
    abortWithError("WiP");
    return false;
}
References abortWithError.
Referenced by writeInstrInfo().
isVectorStoreOperation()
bool TDGen::isVectorStoreOperation (const Operation & op) const protected
Checks if the given operation is a vector store memory operation.
Parameters
op Operation which is checked.
Returns
True, if operation is a vector store memory operation.
Definition at line 1977 of file TDGen.cc.
{
    abortWithError("WiP");
    return false;
}
References abortWithError.
Referenced by writeInstrInfo().
isWrongEndianessVectorOp()
bool TDGen::isWrongEndianessVectorOp (const Operation & op) const protected
Definition at line 1983 of file TDGen.cc.
{
    abortWithError("WiP");
    return false;
}
References abortWithError.
llvmOperationName()
TCEString TDGen::llvmOperationName (const TCEString & operationName) const protected virtual
Returns llvm operation name for the given OSAL operation name, if any.
Definition at line 5109 of file TDGen.cc.
{
    TCEString opName = StringTools::stringToLower(operationName);
    if (opName == "add") return "add";
    if (opName == "sub") return "sub";
    if (opName == "mul") return "mul";
    if (opName == "div") return "sdiv";
    if (opName == "divu") return "udiv";
    if (opName == "mod") return "srem";
    if (opName == "modu") return "urem";
    if (opName == "add64") return "add";
    if (opName == "sub64") return "sub";
    if (opName == "mul64") return "mul";
    if (opName == "div64") return "sdiv";
    if (opName == "divu64") return "udiv";
    if (opName == "mod64") return "srem";
    if (opName == "modu64") return "urem";
    if (opName == "shl") return "shl";
    if (opName == "shr") return "sra";
    if (opName == "shru") return "srl";
    if (opName == "rotl") return "rotl";
    if (opName == "rotr") return "rotr";
    if (opName == "shl64") return "shl";
    if (opName == "shr64") return "sra";
    if (opName == "shru64") return "srl";
    if (opName == "rotl64") return "rotl";
    if (opName == "rotr64") return "rotr";
    if (opName == "and") return "and";
    if (opName == "ior") return "or";
    if (opName == "xor") return "xor";
    if (opName == "and64") return "and";
    if (opName == "ior64") return "or";
    if (opName == "xor64") return "xor";
    if (opName == "eq") return "seteq";
    if (opName == "eq64") return "seteq";
    if (opName == "ne") return "setne";
    if (opName == "ne64") return "setne";
    if (opName == "lt") return "setlt";
    if (opName == "lt64") return "setlt";
    if (opName == "le") return "setle";
    if (opName == "le64") return "setle";
    if (opName == "gt") return "setgt";
    if (opName == "gt64") return "setgt";
    if (opName == "ge") return "setge";
    if (opName == "ltu") return "setult";
    if (opName == "ltu64") return "setult";
    if (opName == "leu") return "setule";
    if (opName == "leu64") return "setule";
    if (opName == "gtu") return "setugt";
    if (opName == "gtu64") return "setugt";
    if (opName == "geu") return "setuge";
    if (opName == "geu64") return "setuge";
    if (opName == "eqf" || opName == "eqd") return "setoeq";
    if (opName == "nef" || opName == "ned") return "setone";
    if (opName == "ltf" || opName == "ltd") return "setolt";
    if (opName == "lef" || opName == "led") return "setole";
    if (opName == "gtf" || opName == "gtd") return "setogt";
    if (opName == "gef" || opName == "ged") return "setoge";
    if (opName == "equf" || opName == "equd") return "setueq";
    if (opName == "neuf" || opName == "neud") return "setune";
    if (opName == "ltuf" || opName == "ltud") return "setult";
    if (opName == "leuf" || opName == "leud") return "setule";
    if (opName == "gtuf" || opName == "gtud") return "setugt";
    if (opName == "geuf" || opName == "geud") return "setuge";
    if (opName == "ordf" || opName =="ordd") return "seto";
    if (opName == "uordf" || opName == "uordd") return "setuo";
    if (opName == "addf") return "fadd";
    if (opName == "subf") return "fsub";
    if (opName == "mulf") return "fmul";
    if (opName == "divf") return "fdiv";
    if (opName == "absf") return "fabs";
    if (opName == "negf") return "fneg";
    if (opName == "sqrtf") return "fsqrt";
    if (opName == "cif") return "sint_to_fp";
    if (opName == "cfi") return "fp_to_sint";
    if (opName == "cifu") return "uint_to_fp";
    if (opName == "cfiu") return "fp_to_uint";
    if (opName == "cfh") return "fpround";
    if (opName == "chf") return "fpextend";
    if (littleEndian_) {
        if (opName == "ld8") return "sextloadi8";
        if (opName == "ldu8") return "zextloadi8";
        if (opName == "ld16") return "sextloadi16";
        if (opName == "ldu16") return "zextloadi16";
        if (mach_.is64bit()) {
            if (opName == "ld32") return "sextloadi32";
            if (opName == "ldu32") return "zextloadi32";
        } else {
            if (opName == "ld32" || opName =="ldu32") return "load";
        }
        if (opName == "ld64") return "load";
        //if (opName == "ldd") return "load";
        if (opName == "st8") return "truncstorei8";
        if (opName == "st16") return "truncstorei16";
        if (opName == "st32") {
            if (mach_.is64bit()) {
                return "truncstorei32";
            } else {
                return "store";
            }
        }
        if (opName == "st32") return "store";
        if (opName == "st64") return "store";
        //if (opName == "std") return "load";
    } else { // big-endian
        if (opName == "ldq") return "sextloadi8";
        if (opName == "ldqu") return "zextloadi8";
        if (opName == "ldh") return "sextloadi16";
        if (opName == "ldhu") return "zextloadi16";
        if (opName == "ldw") return "load";
        //if (opName == "ldd") return "load";
        if (opName == "stq") return "truncstorei8";
        if (opName == "sth") return "truncstorei16";
        if (opName == "stw") return "store";
        //if (opName == "std") return "load";
    }
    if (opName.length() >2 && opName.substr(0,2) == "sx") {
        return "sext_inreg";
    }
    if (opName == "truncwh" || opName == "truncwb" || opName == "trunchb")
        return "trunc";
    if (opName == "neg") return "ineg";
    if (opName == "not") return "not";
    if (opName == "cas") return "atomic_cmp_swap_32";
    if (opName == "select") return "select";
    // Unknown operation name.
    return "";
}
References TTAMachine::Machine::is64bit(), littleEndian_, mach_, and StringTools::stringToLower().
Referenced by writePortGuardedJumpDefPair().
llvmOperationPattern()
TCEString TDGen::llvmOperationPattern (const Operation & op, char operandType = ' ') const protected virtual
Returns LLVM operation pattern for given OSAL operation.
Parameters
op Operation for which the LLVM pattern should be returned.
Returns
Operation pattern in llvm.
Definition at line 4895 of file TDGen.cc.
{
    TCEString opName = StringTools::stringToLower(op.name());
    if (opName == "add") return "add %1%, %2%";
    if (opName == "add64") return "add %1%, %2%";
    if (opName == "sub") return "sub %1%, %2%";
    if (opName == "sub64") return "sub %1%, %2%";
    if (opName == "mul") return "mul %1%, %2%";
    if (opName == "mul64") return "mul %1%, %2%";
    if (opName == "div") return "sdiv %1%, %2%";
    if (opName == "divu") return "udiv %1%, %2%";
    if (opName == "div64") return "sdiv %1%, %2%";
    if (opName == "divu64") return "udiv %1%, %2%";
    if (opName == "mod") return "srem %1%, %2%";
    if (opName == "modu") return "urem %1%, %2%";
    if (opName == "mod64") return "srem %1%, %2%";
    if (opName == "modu64") return "urem %1%, %2%";
    if (opName == "shl") return "shl %1%, %2%";
    if (opName == "shr") return "sra %1%, %2%";
    if (opName == "shru") return "srl %1%, %2%";
    if (opName == "rotl") return "rotl %1%, %2%";
    if (opName == "rotr") return "rotr %1%, %2%";
    if (opName == "shl64") return "shl %1%, %2%";
    if (opName == "shr64") return "sra %1%, %2%";
    if (opName == "shru64") return "srl %1%, %2%";
    if (opName == "rotl64") return "rotl %1%, %2%";
    if (opName == "rotr64") return "rotr %1%, %2%";
    if (opName == "and") return "and %1%, %2%";
    if (opName == "ior") return "or %1%, %2%";
    if (opName == "xor") return "xor %1%, %2%";
    if (opName == "and64") return "and %1%, %2%";
    if (opName == "ior64") return "or %1%, %2%";
    if (opName == "xor64") return "xor %1%, %2%";
    if (opName == "eq") return "seteq %1%, %2%";
    if (opName == "eq64") return "seteq %1%, %2%";
    if (opName == "ne") return "setne %1%, %2%";
    if (opName == "ne64") return "setne %1%, %2%";
    if (opName == "lt") return "setlt %1%, %2%";
    if (opName == "lt64") return "setlt %1%, %2%";
    if (opName == "le") return "setle %1%, %2%";
    if (opName == "le64") return "setle %1%, %2%";
    if (opName == "gt") return "setgt %1%, %2%";
    if (opName == "gt64") return "setgt %1%, %2%";
    if (opName == "ge") return "setge %1%, %2%";
    if (opName == "ge64") return "setge %1%, %2%";
    if (opName == "ltu") return "setult %1%, %2%";
    if (opName == "ltu64") return "setult %1%, %2%";
    if (opName == "leu") return "setule %1%, %2%";
    if (opName == "leu64") return "setule %1%, %2%";
    if (opName == "gtu") return "setugt %1%, %2%";
    if (opName == "gtu64") return "setugt %1%, %2%";
    if (opName == "geu") return "setuge %1%, %2%";
    if (opName == "geu64") return "setuge %1%, %2%";
    if (opName == "eqf" || opName == "eqd") return "setoeq %1%, %2%";
    if (opName == "nef" || opName == "ned") return "setone %1%, %2%";
    if (opName == "ltf" || opName == "ltd") return "setolt %1%, %2%";
    if (opName == "lef" || opName == "led") return "setole %1%, %2%";
    if (opName == "gtf" || opName == "gtd") return "setogt %1%, %2%";
    if (opName == "gef" || opName == "ged") return "setoge %1%, %2%";
    if (opName == "equf" || opName == "equd") return "setueq %1%, %2%";
    if (opName == "neuf" || opName == "neud") return "setune %1%, %2%";
    if (opName == "ltuf" || opName == "ltud") return "setult %1%, %2%";
    if (opName == "leuf" || opName == "leud") return "setule %1%, %2%";
    if (opName == "gtuf" || opName == "gtud") return "setugt %1%, %2%";
    if (opName == "geuf" || opName == "geud") return "setuge %1%, %2%";
    if (opName == "ordf" || opName == "ordd") return "seto %1%, %2%";
    if (opName == "uordf"|| opName == "uordd")return "setuo %1%, %2%";
    if (opName == "addf" || opName == "addd") return "fadd %1%, %2%";
    if (opName == "subf" || opName == "subd") return "fsub %1%, %2%";
    if (opName == "mulf" || opName == "muld") return "fmul %1%, %2%";
    if (opName == "divf" || opName == "divd") return "fdiv %1%, %2%";
    if (opName == "absf" || opName == "absd") return "fabs %1%";
    if (opName == "negf" || opName == "negd") return "fneg %1%";
    if (opName == "sqrtf"|| opName == "sqrtd")return "fsqrt %1%";
    if (opName == "cif") return "sint_to_fp %1%";
    if (opName == "cfi") return "fp_to_sint %1%";
    if (opName == "cifu") return "uint_to_fp %1%";
    if (opName == "cfiu") return "fp_to_uint %1%";
    if (opName == "cld") return "sint_to_fp %1%";
    if (opName == "cdl") return "fp_to_sint %1%";
    if (opName == "cldu") return "uint_to_fp %1%";
    if (opName == "cdlu") return "fp_to_uint %1%";
    if (opName == "cfh" || opName == "cdf") return "fpround %1%";
    if (opName == "chf") return "f32 (fpextend %1%)";
    if (opName == "cfd") return "f64 (fpextend %1%)";
    if (opName == "cih") return "sint_to_fp %1%";
    if (opName == "chi") return "i32 (fp_to_sint %1%)";
    if (opName == "cihu") return "uint_to_fp %1%";
    if (opName == "chiu") return "i32 (fp_to_uint %1%)";
    if (opName == "neuh") return "setune %1%, %2%";
    if (opName == "eqh") return "setoeq %1%, %2%";
    if (opName == "neh") return "setone %1%, %2%";
    if (opName == "lth") return "setolt %1%, %2%";
    if (opName == "leh") return "setole %1%, %2%";
    if (opName == "gth") return "setogt %1%, %2%";
    if (opName == "geh") return "setoge %1%, %2%";
    if (opName == "ordh") return "seto %1%, %2%";
    if (opName == "uordh") return "setuo %1%, %2%";
    if (opName == "addh") return "fadd %1%, %2%";
    if (opName == "subh") return "fsub %1%, %2%";
    if (opName == "mulh") return "fmul %1%, %2%";
    if (opName == "divh") return "fdiv %1%, %2%";
    if (opName == "absh") return "fabs %1%";
    if (opName == "negh") return "fneg %1%";
    if (opName == "sqrth") return "fsqrt %1%";
    if (opName == "cih") return "sint_to_fp %1%";
    if (opName == "chi") return "fp_to_sint %1%";
    if (opName == "cihu") return "uint_to_fp %1%";
    if (opName == "chiu") return "fp_to_uint %1%";
    if (opName == "csh") return "sint_to_fp %1%";
    if (opName == "cshu") return "uint_to_fp %1%";
    if (opName == "chs") return "fp_to_sint %1%";
    if (opName == "chsu") return "fp_to_uint %1%";
    if (littleEndian_) {
        if (opName == "ld8") return "sextloadi8 %1%";
        if (opName == "ldu8") return "zextloadi8 %1%";
        if (opName == "ld16") return "sextloadi16 %1%";
        if (opName == "ldu16") return "zextloadi16 %1%";
        if (mach_.is64bit()) {
            if (opName == "ld32") return "sextloadi32 %1%";
            if (opName == "ldu32") return "zextloadi32 %1%";
        } else {
            if (opName == "ld32" || opName == "ldu32") return "load %1%";
        }
        if (opName == "ld64") return "load %1%";
        //if (opName == "ldd") return "load";
        if (opName == "st8") return "truncstorei8 %2%, %1%";
        if (opName == "st16") return "truncstorei16 %2%, %1%";
        if (mach_.is64bit()) {
            if (opName == "st32") return "truncstorei32 %2%, %1%";
        } else {
            if (opName == "st32") return "store %2%, %1%";
        }
        if (opName == "st64") return "store %2%, %1%";
    } else {
        if (opName == "ldq") return "sextloadi8 %1%";
        if (opName == "ldqu") return "zextloadi8 %1%";
        if (opName == "ldh") return "sextloadi16 %1%";
        if (opName == "ldhu") return "zextloadi16 %1%";
        if (opName == "ldw") return "load %1%";
        //if (opName == "ldd") return "load";
        if (opName == "stq") return "truncstorei8 %2%, %1%";
        if (opName == "sth") return "truncstorei16 %2%, %1%";
        if (opName == "stw") return "store %2%, %1%";
        //if (opName == "std") return "load";
    }
    if (opName == "sxw64") {
        return "sext_inreg %1%, i32";
    }
    if (opName == "sxb64") {
        return "sext_inreg %1%, i1";
    }
    if (opName == "sxq64") {
        return "sext_inreg %1%, i8";
    }
    if (opName == "sxh64") {
        return "sext_inreg %1%, i16";
    }
    if (opName == "sxhw") {
      return "sext_inreg %1%, i16";
    }
    if (opName == "sxqw") {
      return "sext_inreg %1%, i8";
    }
    if (opName == "sxw")
        return mach_.is64bit() ? "sext_inreg %1%, i64": "sext_inreg %1%, i32";
    if (opName == "sxbw") return "sext_inreg %1%, i1";
    if (opName == "truncwh" || opName == "truncwb" || opName == "trunchb")
        return "trunc %1%";
    if (opName == "neg") return "ineg %1%";
    if (opName == "not") return "not %1%";
    if (opName == "cas") return "atomic_cmp_swap_32 %1%, %2%, %3%";
    if (opName == "select") return "select %3%, %1%, %2%";
    // Unknown operation name.
    return "";
}
References TTAMachine::Machine::is64bit(), littleEndian_, mach_, Operation::name(), and StringTools::stringToLower().
Referenced by operationCanBeMatched(), operationNodeToString(), writeEmulationPattern(), writeOperationDef(), and RISCVTDGen::writePatternDefinition().
operandChar()
char TDGen::operandChar (Operand & operand) protected virtual
Returns corresponding character for given operand type.
Parameters
operand Operand under inspection.
Returns
Corresponding character of operand type.
Definition at line 4755 of file TDGen.cc.
{
    if (operand.isVector()) {
        if (operand.type() == Operand::BOOL) {
            return OT_VREG_BOOL;
        } else if (operand.type() == Operand::HALF_FLOAT_WORD) {
            return OT_VREG_HFP;
        } else if (operand.type() == Operand::FLOAT_WORD) {
            return OT_VREG_FP;
        } else {
            if (operand.elementWidth() == 1) {
                return OT_VREG_BOOL;
            } else if (operand.elementWidth() == 8) {
                return OT_VREG_INT8;
            } else if (operand.elementWidth() == 16) {
                return OT_VREG_INT16;
            } else {
                return OT_VREG_INT32;
            }
        }
    }
    if (operand.type() == Operand::BOOL) {
        return OT_REG_BOOL;
    } else if (operand.type() == Operand::HALF_FLOAT_WORD) {
        return OT_REG_HFP;
    } else if (operand.type() == Operand::ULONG_WORD ||
               operand.type() == Operand::SLONG_WORD ||
               operand.type() == Operand::RAW_DATA) {
        return mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    } else if (operand.type() != Operand::UINT_WORD &&
               operand.type() != Operand::SINT_WORD) {
        return OT_REG_FP;
    } else {
        return OT_REG_INT;
    }
}
References Operand::BOOL, Operand::elementWidth(), Operand::FLOAT_WORD, Operand::HALF_FLOAT_WORD, TTAMachine::Machine::is64bit(), Operand::isVector(), mach_, OT_REG_BOOL, OT_REG_FP, OT_REG_HFP, OT_REG_INT, OT_REG_LONG, OT_VREG_BOOL, OT_VREG_FP, OT_VREG_HFP, OT_VREG_INT16, OT_VREG_INT32, OT_VREG_INT8, Operand::RAW_DATA, Operand::SINT_WORD, Operand::SLONG_WORD, Operand::type(), Operand::UINT_WORD, and Operand::ULONG_WORD.
Referenced by createDefaultOperandTypeString(), emulatingOpNodeLLVMName(), operationCanBeMatched(), writeEmulationPattern(), writeOperationDef(), and RISCVTDGen::writePatternDefinition().
operandToString()
std::string TDGen::operandToString (const Operand & operand, bool match, char operandType, const std::string & immDefName = "") protected virtual
Returns LLVM .td format string for an operand.
Parameters
operand Operand to return string for.
match True, if the string should be in the matching pattern format.
operandType Character that identifies the type of the operand.
Returns
Operand string to be used in a llvm .td pattern.
Todo:
Vector of pointers once supported. Change operand types for GATHER and SCATTER to be mem-data and mem-address, because that will direct the address operand into this if-clause.
Definition at line 5870 of file TDGen.cc.
{
    int idx = operand.index();
    if (operand.isVector() && !operand.isAddress()) {
        switch (operandType) {
            case OT_VREG_BOOL:
            case OT_VREG_INT8:
            case OT_VREG_INT16:
            case OT_VREG_INT32:
            case OT_VREG_FP:
            case OT_VREG_HFP: {
                TCEString regClass = associatedVectorRegisterClass(operand);
                return regClass + ":$op" + Conversion::toString(idx);
            }
        }
    }
    // from TDGenSIMD: if (operand.isVector && operand.isAddress()
    /// @todo Vector of pointers once supported. Change operand types
    /// for GATHER and SCATTER to be mem-data and mem-address, because
    /// that will direct the address operand into this if-clause.
    if (operand.isAddress()) {
        switch (operandType) {
        case OT_IMM_INT:
        case OT_IMM_LONG:
            if (match) {
                return "MEMri:$op" + Conversion::toString(idx);
            } else {
                return "ADDRri:$op" + Conversion::toString(idx);
            }
        case OT_REG_INT:
        case OT_REG_LONG:
            if (match) {
                return  "MEMrr:$op" + Conversion::toString(idx);
            } else {
                return  "ADDRrr:$op" + Conversion::toString(idx);
            }
        default:
            std::string msg =
                "invalid operation type for mem operand:";
            msg += operandType;
            throw InvalidData(__FILE__, __LINE__, __func__, msg);
        }
    } else if (operand.type() == Operand::SINT_WORD ||
               operand.type() == Operand::UINT_WORD ||
               operand.type() == Operand::RAW_DATA ||
               operand.type() == Operand::BOOL) {
        // imm
        switch (operandType) {
        case OT_IMM_LONG:
            if (match) {
                return "i64imm:$op" + Conversion::toString(idx);
            } else {
                return "(i64 imm:$op" + Conversion::toString(idx) + ")";
            }
        case OT_IMM_INT:
            assert(!immDefName.empty() &&
                "No immediate operand defined for the operand.");
            return immDefName + ":$op" + Conversion::toString(idx);
        case OT_IMM_BOOL:
            if (match) {
                return "i1imm:$op" + Conversion::toString(idx);
            } else {
                return "(i1 imm:$op" + Conversion::toString(idx) + ")";
            }
        case OT_REG_INT:
            return mach_.is64bit() ?
                "R64IRegs:$op" + Conversion::toString(idx):
                "R32IRegs:$op" + Conversion::toString(idx);
        case OT_REG_LONG:
            return "R64IRegs:$op" + Conversion::toString(idx);
        case OT_REG_BOOL:
            return "R1Regs:$op" + Conversion::toString(idx);
        case OT_REG_FP:
            if (operand.type() == Operand::RAW_DATA) {
                return "FPRegs:$op" + Conversion::toString(idx);
            }
            /* fall through */
        case OT_REG_HFP:
            if (operand.type() == Operand::RAW_DATA) {
                return "HFPRegs:$op" + Conversion::toString(idx);
            }
            /* fall through */
        default:
            std::string msg =
                "invalid operation type for integer operand:";
            msg += operandType;
            throw InvalidData(__FILE__, __LINE__, __func__, msg);
        }
    } else if (operand.type() == Operand::FLOAT_WORD ) {
        switch (operandType) {
        case OT_IMM_INT:
        case OT_IMM_FP:
            if (match) {
                return "f32imm:$op" + Conversion::toString(idx);
            } else {
                return "(f32 fpimm:$op" + Conversion::toString(idx) + ")";
            }
            case OT_REG_INT:
        case OT_REG_FP:
            return "FPRegs:$op" + Conversion::toString(idx);
        default:
            std::string msg =
                "invalid operation type for float operand:";
            msg += operandType;
            throw InvalidData(__FILE__, __LINE__, __func__, msg);
        }
    } else if (operand.type() == Operand::HALF_FLOAT_WORD) {
        switch (operandType) {
        case OT_IMM_INT:
        case OT_IMM_FP:
        case OT_IMM_HFP:
            if (match) {
                return "f16imm:$op" + Conversion::toString(idx);
            } else {
                return "(f16 fpimm:$op" + Conversion::toString(idx) + ")";
            }
        case OT_REG_INT:
        case OT_REG_HFP:
            return "HFPRegs:$op" + Conversion::toString(idx);
        default:
            std::string msg =
                "invalid operation type for half operand:";
            msg += operandType;
            throw InvalidData(__FILE__, __LINE__, __func__, msg);
        }
    } else if (operand.type() == Operand::DOUBLE_WORD) {
        // TODO: immediate check??
        return "R64DFPRegs:$op" + Conversion::toString(idx);
    } else if (operand.type() == Operand::SLONG_WORD ||
               operand.type() == Operand::ULONG_WORD) {
        if (operandType == OT_REG_BOOL) {
            return "R1Regs:$op" + Conversion::toString(idx);
        }
        if (operandType == OT_IMM_BOOL) {
            if (match) {
                return "i1imm:$op" + Conversion::toString(idx);
            } else {
                return "(i1 imm:$op" + Conversion::toString(idx) + ")";
            }
        }
        if (operandType == OT_IMM_LONG) {
            return match ?
                "i64imm:$op" + Conversion::toString(idx) :
                "(i64 imm:$op" + Conversion::toString(idx) + ")";
        }
        return mach_.is64bit() ?
            "R64IRegs:$op" + Conversion::toString(idx):
            "R32IRegs:$op" + Conversion::toString(idx);
    } else {
        std::cerr << "Unknown operand type: " << operandType << std::endl;
        assert(false && "Unknown operand type.");
    }
    abortWithError("Unknown operand type on osal? Should not get here.");
    return "";
}
References __func__, abortWithError, assert, associatedVectorRegisterClass(), Operand::BOOL, Operand::DOUBLE_WORD, Operand::FLOAT_WORD, Operand::HALF_FLOAT_WORD, Operand::index(), TTAMachine::Machine::is64bit(), Operand::isAddress(), Operand::isVector(), mach_, OT_IMM_BOOL, OT_IMM_FP, OT_IMM_HFP, OT_IMM_INT, OT_IMM_LONG, OT_REG_BOOL, OT_REG_FP, OT_REG_HFP, OT_REG_INT, OT_REG_LONG, OT_VREG_BOOL, OT_VREG_FP, OT_VREG_HFP, OT_VREG_INT16, OT_VREG_INT32, OT_VREG_INT8, Operand::RAW_DATA, Operand::SINT_WORD, Operand::SLONG_WORD, Conversion::toString(), Operand::type(), Operand::UINT_WORD, and Operand::ULONG_WORD.
Referenced by dagNodeToString(), patInputs(), patOutputs(), and writeEmulationPattern().
operandTypesToRegisters()
std::string TDGen::operandTypesToRegisters (const std::string & opdTypes) const protected
Definition at line 7885 of file TDGen.cc.
{
    std::string result(opdTypes);
    for (char& type : result) {
        type = operandTypeToRegister(type);
    }
    return result;
}
References operandTypeToRegister().
Referenced by getLLVMPatternWithConstants().
operandTypeToRegister()
char TDGen::operandTypeToRegister (const char & opdType) const protected
Definition at line 7894 of file TDGen.cc.
{
    switch (opdType) {
        case OT_IMM_INT: return OT_REG_INT; // Integer immediate.
        case OT_IMM_BOOL: return OT_REG_BOOL; // Boolean immediate.
        case OT_IMM_FP: return OT_REG_FP; // 32-bit floating point immediate.
        case OT_IMM_HFP: return OT_REG_HFP; // 15-bi floating point immediate.
        // TODO: vector immediate types.
        default:
            break;
    }
    return opdType; // Return as is (should be register type).
}
References OT_IMM_BOOL, OT_IMM_FP, OT_IMM_HFP, OT_IMM_INT, OT_REG_BOOL, OT_REG_FP, OT_REG_HFP, and OT_REG_INT.
Referenced by getLLVMPatternWithConstants(), getMovePattern(), and operandTypesToRegisters().
operationCanBeMatched()
bool TDGen::operationCanBeMatched (const Operation & op, std::set< std::string > * recursionCycleCheck = NULL, bool recursionHasStore = false) protected
Check if operation can be matched with llvm pattern.
Check if operation has llvmOperationPatters or one of it's DAGs contain only operations, which can be matched.
Definition at line 5281 of file TDGen.cc.
{
    // LLVM does not support operations with >255 inputs.
    if (op.numberOfInputs() > 255) {
        return false;
    }
    // TODO: this should have been changed?
    char operandChar = mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    // if operation has llvm pattern
    if (llvmOperationPattern(op,operandChar) != "") {
        return true;
    }
    std::set<std::string> useSet;
    if (recursionCycleCheck != NULL) {
        useSet = *recursionCycleCheck;
    }
    useSet.insert(op.name());
    // check if one of dags of operation is ok
    for (int i = 0; i < op.dagCount(); i++) {
        OperationDAG& dag = op.dag(i);
        if (operationDAGCanBeMatched(dag, &useSet, recursionHasStore)) {
            return true;
        }
    }
    return false;
}
References Operation::dag(), Operation::dagCount(), TTAMachine::Machine::is64bit(), llvmOperationPattern(), mach_, Operation::name(), Operation::numberOfInputs(), operandChar(), operationDAGCanBeMatched(), OT_REG_INT, and OT_REG_LONG.
Referenced by operationDAGCanBeMatched(), writeInstrInfo(), and RISCVTDGen::writePatternDefinition().
operationDAGCanBeMatched()
bool TDGen::operationDAGCanBeMatched (const OperationDAG & op, std::set< std::string > * recursionCycleCheck = NULL, bool recursionHasStore = false) protected
Definition at line 5315 of file TDGen.cc.
{
    bool hasStore = false;
    for (int j = 0; j < opDag.nodeCount(); j++) {
        OperationNode* opNode = dynamic_cast<OperationNode*>(&opDag.node(j));
        if (opNode) {
            Operation& refOp = opNode->referencedOperation();
            if (refOp.writesMemory()) {
                if (recursionHasStore || hasStore) {
                    return false;
                } else {
                    hasStore = true;
                }
            }
            // check that the same operation is not used recursively
            if (recursionCycleCheck &&
                recursionCycleCheck->count(refOp.name()) != 0) {
                return false;
            }
            // check if referenced op can be matched
            if (!operationCanBeMatched(refOp, recursionCycleCheck,
                                       hasStore)) {
                return false;
            }
        }
    }
    return true;
}
References Operation::name(), BoostGraph< GraphNode, GraphEdge >::node(), BoostGraph< GraphNode, GraphEdge >::nodeCount(), operationCanBeMatched(), OperationNode::referencedOperation(), and Operation::writesMemory().
Referenced by getMatchableOperationDAG(), getMatchableOperationDAGs(), and operationCanBeMatched().
operationNodeToString()
std::string TDGen::operationNodeToString (const Operation & op, const OperationDAG & dag, const OperationNode & node, bool emulationPattern, const std::string & operandTypes) protected
Converts OSAL dag operation node to llvm .td pattern fragment string.
Parameters
op Operation which this operation node is part of.
dag Parent DAG of the operation node.
node Node to convert to string.
immOp Index of an operand to define as immediate or 0 if none.
emulationPattern True, if the string should be in emulation pattern format.
Definition at line 5785 of file TDGen.cc.
{
    const Operation& operation = node.referencedOperation();
    std::string operationPat;
    if (emulationPattern) {
        operationPat = emulatingOpNodeLLVMName(
            op, dag, node, operandTypes);
        for (int i = 0; i < operation.numberOfInputs(); i++) {
            if (i > 0) {
                operationPat += ", ";
            } else {
                operationPat += " ";
            }
            operationPat =
                operationPat + "%" + Conversion::toString(i + 1) + "%";
        }
    } else {
        operationPat = llvmOperationPattern(operation, operandTypes[0]);
        // generate pattern for operation if not llvmOperation (can match
        // custom op patterns)
        if (operationPat == "") {
            auto* dagToUse = getMatchableOperationDAG(operation);
            if (dagToUse) {
                return subPattern(operation, *dagToUse);
            } else {
                operationPat = tceOperationPattern(operation);
            }
        }
    }
    if (operationPat == "") {
        std::string msg("Unknown operation node in dag: " +
                        std::string(operation.name()));
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    boost::format pattern(operationPat);
    int inputs = operation.numberOfInputs();
#ifndef NDEBUG
    int outputs =
#endif
    operation.numberOfOutputs();
    assert(outputs == 0 || outputs == 1);
    for (int i = 1; i < inputs + 1; i++) {
        for (int e = 0; e < dag.inDegree(node); e++) {
            const OperationDAGEdge& edge = dag.inEdge(node, e);
            int dst = edge.dstOperand();
            if (dst == i) {
                const OperationDAGNode& in = dag.tailNode(edge);
                std::string dagNodeString =  dagNodeToString(
                    op, dag, in, emulationPattern, operandTypes,
                    &operation, &node);
                try {
                    pattern % dagNodeString;
                } catch(...) {
                    TCEString msg = "Boost format threw exception! ";
                    msg << "Input format: " << operationPat;
                    throw InvalidData(__FILE__, __LINE__, __func__, msg);
                }
            }
        }
    }
    return std::string("(") + pattern.str() + ")";
}
References __func__, assert, dagNodeToString(), OperationDAGEdge::dstOperand(), emulatingOpNodeLLVMName(), getMatchableOperationDAG(), BoostGraph< GraphNode, GraphEdge >::inDegree(), BoostGraph< GraphNode, GraphEdge >::inEdge(), llvmOperationPattern(), Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), OperationNode::referencedOperation(), subPattern(), BoostGraph< GraphNode, GraphEdge >::tailNode(), tceOperationPattern(), and Conversion::toString().
Referenced by dagNodeToString().
operationPattern()
std::string TDGen::operationPattern (const Operation & op, const OperationDAG & dag, const std::string & operandTypes) protected
Returns operation pattern in llvm .td format.
Parameters
op Operation to return pattern for.
dag Operation pattern's DAG.
immOp Index of an operand to define as an immediate operand, or 0, if all operands should be in registers.
Returns
Pattern string.
Definition at line 5421 of file TDGen.cc.
{
    std::string retVal;
    for (OperationDAG::NodeSet::iterator i = dag.endNodes().begin();
         i != dag.endNodes().end(); ++i) {
        if (i != dag.endNodes().begin()) {
            retVal += ",";
        }
        const OperationDAGNode& res = **(i);
        retVal += dagNodeToString(op, dag, res, false, operandTypes);
    }
    return retVal;
}
References dagNodeToString(), and OperationDAG::endNodes().
Referenced by writeOperationDef(), and RISCVTDGen::writePatternDefinition().
orderEqualWidthRegistersToRoundRobin()
void TDGen::orderEqualWidthRegistersToRoundRobin () protected
Sets registers to use round robin order in register allocation.
Starting from register index number 0, all same width registers having the same index number are pushed to a vector. Then, index is increased by one and same action is performed, index increased etc., until all registers of same width are pushed to the vector. Then, the vector is used to replace old register order.
For example, two register files R64_1 (register indices 0, 1, 2 and 3) and R64_2 (register indices 0, 1) are ordered as: R64_1(0), R64_2(0), R64_1(1), R64_2(1), R64_1(2), R64_1(3), and LLVM register allocator will use this order to allocate the registers.
Definition at line 1674 of file TDGen.cc.
{
    std::vector<RegisterInfo> roundRobinOrder;
    // Loop through every different group of register widths.
    std::map<int, std::vector<RegisterInfo>>::iterator it;
    for (it = registers_.begin(); it != registers_.end(); ++it) {
        roundRobinOrder.clear();
        std::vector<RegisterInfo>& registers = it->second;
        unsigned i = 0;
        unsigned idx = 0;
        // Loop until all registers of same width are reordered.
        while (roundRobinOrder.size() != registers.size()) {
            RegisterInfo& info = registers[i];
            if (info.regIndex_ == idx) {
                roundRobinOrder.push_back(info);
            }
            if (i == registers.size() - 1) {
                i = 0;
                ++idx;
            } else {
                ++i;
            }
        }
        registers = roundRobinOrder;
    }
}
References TDGenerator::RegisterInfo::regIndex_, and registers_.
Referenced by analyzeMachineRegisters().
patInputs()
std::string TDGen::patInputs (const Operation & op, const std::string & inputTypes) protected
Returns llvm input definition list for an operation.
Parameters
op Operation to define inputs for.
Returns
String defining operation inputs in llvm .td format.
Definition at line 6043 of file TDGen.cc.
{
    std::string ins;
    for (int i = 0; i < op.numberOfInputs(); i++) {
        if (i > 0) {
            ins += ", ";
        }
        char inputType = inputTypes[i + op.numberOfOutputs()];
        std::string immDef("");
        // NOTE: !op.operand(i+1).isAddress() is kludge fix for MEMri/ADDri
        // operands. They do not have immediate operand definitions (yet).
        if (inputType == OT_IMM_INT && !op.operand(i+1).isAddress()) {
            assert(immOperandDefs_.count(
                ImmInfo::key(op, op.operand(i+1)))
                && "Missing immediate operand definition for the operand.");
            immDef = immOperandDefs_[ImmInfo::key(op, op.operand(i+1))];
        }
        ins += operandToString(op.operand(i + 1), true, inputType, immDef);
    }
    return ins;
}
References assert, immOperandDefs_, Operand::isAddress(), ImmInfo::key(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), operandToString(), and OT_IMM_INT.
Referenced by writeOperationDef().
patOutputs()
std::string TDGen::patOutputs (const Operation & op, const std::string & operandTypes) protected
Returns llvm output definition list for an operation.
Parameters
op Operation to define outputs for.
Returns
String defining operation outputs in llvm .td format.
Definition at line 6074 of file TDGen.cc.
{
    std::string outs;
    for (int i = 0; i < op.numberOfOutputs(); i++) {
        assert(op.operand(op.numberOfInputs() + 1 + i).isOutput());
        outs += (i > 0) ? (",") : (" ");
        outs += operandToString(
            op.operand(op.numberOfInputs() + 1 + i), true, operandTypes[i]);
    }
    return outs;
}
References assert, Operand::isOutput(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), and operandToString().
Referenced by writeOperationDef().
saveAdditionalVectorOperationInfo()
void TDGen::saveAdditionalVectorOperationInfo (const Operation & op, const TCEString & valueTypes, bool isRegisterOp) protected
Saves information of some operations.
Additional information of some operations is needed later, and thus, they need to be saved for later reference.
Parameters
op Vector operation.
valueTypes Operand value type identifier characters.
isRegisterOp If false, operation has immediate operands.
Definition at line 2246 of file TDGen.cc.
{
    abortWithError("WiP");
}
References abortWithError.
Referenced by writeVectorOperationDef().
subPattern()
std::string TDGen::subPattern (const Operation & op, const OperationDAG & dag) protected
Return operation pattern is llvm .td format without outputs.
This pattern can be used as sub-pattern of bigger pattern. The operation must have only one output.
Parameters
op Operation to return pattern for.
dag Operation pattern's DAG.
Returns
Pattern string.
Definition at line 5468 of file TDGen.cc.
{
    if (dag.endNodes().size() != 1) {
    throw InvalidData(
        __FILE__,__LINE__,__func__,
        "Cannot create subpattern: not exactly 1 end node!");
    }
    OperationDAG::NodeSet::iterator i = dag.endNodes().begin();
    const OperationDAGNode& res = **(i);
    OperationDAG::NodeSet preds = dag.predecessors(res);
    if (preds.size() != 1) {
        throw InvalidData(
            __FILE__,__LINE__,__func__,
            "Cannot create subpattern: not single data source for end node.");
    }
    std::string operandTypes = createDefaultOperandTypeString(op);
    // TODO: what about immediate operands?
    // TODO: size of the operand string?
    return dagNodeToString(
        op, dag, **(preds.begin()), false, operandTypes);
}
References __func__, createDefaultOperandTypeString(), dagNodeToString(), OperationDAG::endNodes(), and BoostGraph< GraphNode, GraphEdge >::predecessors().
Referenced by operationNodeToString().
subwordWidthOfRawData()
int TDGen::subwordWidthOfRawData (const Operation & op) const protected
Returns subword width of vector operands of "raw" type.
Note
This function chooses the subword width based on subword width of the WIDEST "raw" data operand that can be found from the operation, since that approach works for current SIMD operation definitions. If this approach doesn't work for your operation, modify the function properly to fulfil your needs.
Parameters
op Operation that has raw operands.
Returns
Subword width of the raw vector operands.
Definition at line 1778 of file TDGen.cc.
{
    int widestWidth = -1;
    int widestRawOperandIndex = -1;
    for (int i = 1; i <= op.operandCount(); ++i) {
        const Operand& operand = op.operand(i);
        if (operand.type() == Operand::RAW_DATA && operand.isVector()) {
            if (operand.width() > widestWidth) {
                widestWidth = operand.width();
                widestRawOperandIndex = i;
            }
        }
    }
    if (widestRawOperandIndex >= 0) {
        return op.operand(widestRawOperandIndex).elementWidth();
    }
    assert(false && "Invalid input operation.");
}
References assert, Operand::elementWidth(), Operand::isVector(), Operation::operand(), Operation::operandCount(), Operand::RAW_DATA, Operand::type(), and Operand::width().
supportedStackAccessOperations()
std::vector< std::string > TDGen::supportedStackAccessOperations (const TTAMachine::Machine & mach) static protected
Returns OSAL operation names valid for stack accesses.
Parameters
mach The target machine.
Definition at line 7685 of file TDGen.cc.
{
    using namespace TTAMachine;
    std::vector<std::string> opcodes;
    auto collectMemoryOps = [](
        std::vector<std::string>& newOpcodes,
        const FunctionUnit& fu) -> void {
        for (int i = 0; i < fu.operationCount(); i++) {
            const Operation& op = MachineInfo::osalOperation(*fu.operation(i));
            if (!op.readsMemory() && !op.writesMemory()) {
                continue;
            }
            newOpcodes.push_back(StringTools::stringToUpper(op.name()));
        }
    };
    std::map<const AddressSpace*, std::set<const FunctionUnit*>>
       addrSpaceLsuMap;
    for (const FunctionUnit* fu : mach.functionUnitNavigator()) {
        if (fu->hasAddressSpace()) {
            addrSpaceLsuMap[fu->addressSpace()].insert(fu);
        }
    }
    const int stackAddressSpaceId = 0;
    if (addrSpaceLsuMap.size() == 1) {
        // Only one data address space. Stack resides there.
        for (auto lsu : addrSpaceLsuMap.begin()->second) {
            collectMemoryOps(opcodes, *lsu);
        }
    } else {
        // Multiple data address spaces. Find LSUs having the stack address
        // space ID.
        for (auto asLsusPair : addrSpaceLsuMap) {
            if (asLsusPair.first->hasNumericalId(stackAddressSpaceId)) {
                for (auto lsu : asLsusPair.second) {
                    collectMemoryOps(opcodes, *lsu);
                }
                break;
            }
        }
    }
    return opcodes;
}
References TTAMachine::Machine::functionUnitNavigator(), Operation::name(), MachineInfo::osalOperation(), Operation::readsMemory(), StringTools::stringToUpper(), and Operation::writesMemory().
Referenced by writeBackendCode().
tceOperationPattern()
std::string TDGen::tceOperationPattern (const Operation & op) protected
Pattern for tce generated custom op patterns.
Definition at line 5266 of file TDGen.cc.
{
    std::string opList = "";
    for (int i = 0; i < op.numberOfInputs(); i++) {
        opList += " %" + Conversion::toString(i+1) + "%";
    }
    return op.name() + opList;
}
References Operation::name(), Operation::numberOfInputs(), and Conversion::toString().
Referenced by operationNodeToString().
verbose()
void TDGen::verbose (const TCEString & msg) const protected
Prints debugging information if verbose switch is used.
Parameters
msg Debug message.
Definition at line 1862 of file TDGen.cc.
{
    if (Application::verboseLevel() > Application::VERBOSE_LEVEL_DEFAULT) {
        Application::logStream() << msg << endl;
    }
}
References Application::logStream(), Application::VERBOSE_LEVEL_DEFAULT, and Application::verboseLevel().
Referenced by analyzeMachineVectorRegisterClasses(), genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), writeCallingConv(), and writeVectorOperationDef().
write16bitRegisterInfo()
void TDGen::write16bitRegisterInfo (std::ostream & o) protected
Writes 16-bit register definitions to the output stream.
Definition at line 1211 of file TDGen.cc.
{
    // --- Hardcoded reserved registers. ---
    writeRegisterDef(o, regs16bit_[0], "HIRES0", "R16", "", RESULT);
    // -------------------------------------
    for (unsigned i = 1; i < regs16bit_.size(); i++) {
        std::string regName = "H" + Conversion::toString(i);
        writeRegisterDef(o, regs16bit_[i], regName, "R16", "", GPR);
    }
    o << std::endl;
    // All 16-bit regs.
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 1-bit RF classes
        if (ri->first.find("R16") == 0) {
            o << "def " << ri->first
              << "Regs : RegisterClass<\"TCE\", [i16], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    o << std::endl;
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 1-bit RF classes
        if (ri->first.find("R16") == 0) {
            o << "def " << ri->first
              << "IRegs : RegisterClass<\"TCE\", [i16], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    o << std::endl;
    // floating-point-versions of these
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 1-bit RF classes
        if (ri->first.find("R16") == 0) {
            o << "def " << ri->first
              << "FPRegs : RegisterClass<\"TCE\", [f16], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    o << std::endl;
}
References GPR, regs16bit_, regsInClasses_, RESULT, Conversion::toString(), and writeRegisterDef().
write1bitRegisterInfo()
void TDGen::write1bitRegisterInfo (std::ostream & o) protected
Writes 1-bit register definitions to the output stream.
Definition at line 961 of file TDGen.cc.
{
    if (regs1bit_.size() < 1) {
        RegInfo reg = {"dummy1", 0};
        std::string name = "I1DUMMY";
        writeRegisterDef(o, reg, name, "R1", "", RESERVED);
    } else {
        for (unsigned i = 0; i < regs1bit_.size(); i++) {
            std::string regName = "B" + Conversion::toString(i);
            writeRegisterDef(o, regs1bit_[i], regName, "R1", "", GPR);
        }
    }
    int stackSize = mach_.is64bit() ? 64 : 32;
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 1-bit RF classes
        if (ri->first.find("R1") == 0) {
            o << std::endl
              << "def " << ri->first << "Regs : RegisterClass<\"TCE\", [i1]"
              << ", " << stackSize << ", (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")> {" << std::endl
              << " let Size=" << stackSize << ";" << std::endl
              << "}" << std::endl;
        }
    }
}
References GPR, TTAMachine::Machine::is64bit(), mach_, regs1bit_, regsInClasses_, RESERVED, Conversion::toString(), and writeRegisterDef().
Referenced by writeRegisterInfo().
write32bitRegisterInfo()
void TDGen::write32bitRegisterInfo (std::ostream & o) protected
Definition at line 1021 of file TDGen.cc.
{
    std::string i32regs;
    size_t i = 0;
    if (!mach_.is64bit()) {
        // --- Hardcoded reserved registers. ---
        writeRegisterDef(o, regs32bit_[0], "SP", "R32", "", RESERVED);
        writeRegisterDef(o, regs32bit_[1], "IRES0", "R32", "", RESULT);
        writeRegisterDef(o, regs32bit_[2], "FP", "R32", "", RESERVED);
        if (prebypassStackIndeces_) {
            writeRegisterDef(
                o, regs32bit_[3], "KLUDGE_REGISTER", "R32", "", GPR);
        } else {
            writeRegisterDef(
                o, regs32bit_[3], "KLUDGE_REGISTER", "R32", "", RESERVED);
        }
        i32regs = "SP, IRES0, FP, KLUDGE_REGISTER";
        //after the loop, i will have the index of first non-special reg.
        for (i = 4;
             i < std::min((size_t)argRegCount_ + 3, regs32bit_.size());
             i++) {
            std::string regName = "A" + Conversion::toString(i);
            writeRegisterDef(o, regs32bit_[i], regName, "R32", "", ARGUMENT);
            i32regs += ", ";
            i32regs += regName;
        }
    }
    if (regs32bit_.size() < 1) {
        RegInfo reg = { "dummy32", 0 };
        writeRegisterDef(o, reg, "dummy32", "R64", "", RESERVED);
        o << "def R32Regs : RegisterClass<\"TCE\", [i32,f32,f16,i1], 32, (add dummy32)>;"
          << std::endl;
        o << "def R32IRegs : RegisterClass<\"TCE\", [i32], 32, (add dummy32)>;"
          << std::endl;
        o << "def R32FPRegs : RegisterClass<\"TCE\", [f32], 32, (add dummy32)>;"
          << std::endl;
        o << "def R32HFPRegs : RegisterClass<\"TCE\", [f16], 32, (add dummy32)>;"
          << std::endl;
    }
    // Generate data structure that contain registers grouped by their
    // physical RFs
    for (; i < regs32bit_.size(); i++) {
        std::string regName = "I" + Conversion::toString(i);
        writeRegisterDef(o, regs32bit_[i], regName, "R32", "", GPR);
        if (!regsInRFClasses_.count(regs32bit_[i].rf)) {
            regsInRFClasses_[regs32bit_[i].rf] = std::vector<std::string>();
        }
        i32regs += ", ";
        i32regs += regName;
        regsInRFClasses_[regs32bit_[i].rf].push_back(regName);
    }
    o << std::endl;
    if (!mach_.is64bit()) {
        // Bypass registers
        for (size_t j = 0; j < 256; ++j) {
            std::string regName = "BP" + Conversion::toString(j);
            o << "def " << regName << " : "
              << "R32<\"ByPass_Regs"
              << "\", []>, DwarfRegNum<"
              << "[" << dregNum_++ << "]>;"
              << std::endl;
        }
        // Bypass register class
        o << "def R32_ByPass_Regs : RegisterClass<\"TCE\", [i32,f32,f16], 32, (add ";
        for (size_t j = 0; j < 256; ++j) {
            std::string regName = "BP" + Conversion::toString(j);
            if (j != 0) {
                o << ", ";
            }
            o << regName;
        }
        o << ")>;" << std::endl;
    }
    for (RegClassMap::iterator
        it = regsInRFClasses_.begin(); it != regsInRFClasses_.end(); ++it) {
        o << "def R32_"
          << it->first
          << "_Regs : RegisterClass<\"TCE\", [i32,f32,f16], 32, (add ";
        for (std::vector<std::string>::iterator r = it->second.begin();
             r != it->second.end(); ++r) {
            if (r != it->second.begin()) {
                o << ", ";
            }
            o << *r;
        }
        o << ")>;" << std::endl;
    }
    o << std::endl;
    // Register classes for all 32-bit registers.
    // TODO: why are these needed? same as integer classes below?
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 1-bit RF classes
        if (ri->first.find("R32") == 0) {
            o << "def " << ri->first << "Regs : RegisterClass<\"TCE\", [i32,f32,f16,i1], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    o << std::endl;
    // Integer register classes for 32-bit registers
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 32-bit RF classes
        if (ri->first.find("R32") == 0) {
            o << "def " << ri->first << "IRegs : RegisterClass<\"TCE\", [i32], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    o << std::endl;
    // Floating point register classes for 32-bit registers
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 32-bit RF classes
        if (ri->first.find("R32") == 0) {
            o << "def " << ri->first << "FPRegs : RegisterClass<\"TCE\", [f32], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
    // Half-float register classes for 32-bit registers (TODO: 16-bit registers also?)
    for (RegClassMap::iterator ri = regsInClasses_.begin();
         ri != regsInClasses_.end(); ri++) {
        // go through all 32-bit RF classes
        if (ri->first.find("R32") == 0) {
            o << "def " << ri->first << "HFPRegs : RegisterClass<\"TCE\", [f16], 32, (add ";
            o << ri->second[0];
            for (unsigned i = 1; i < ri->second.size(); i++) {
                o << " , " << ri->second[i];
            }
            o << ")>;" << std::endl;
        }
    }
//        if (regs32bit_.size() <3) {
    if (mach_.is64bit()) { // for now. later try to use 32-b it regs for float.
        use64bitForFP_ = true;
    }
    if (!use64bitForFP_) {
        o  << "def FPRegs : RegisterClass<\"TCE\", [f32], 32, (add "
           << i32regs << ")>;" << std::endl;
        o  << "def HFPRegs : RegisterClass<\"TCE\", [f16], 32, (add "
           << i32regs << ")>;" << std::endl;
    }
    o << std::endl;
}
References argRegCount_, ARGUMENT, dregNum_, GPR, TTAMachine::Machine::is64bit(), mach_, prebypassStackIndeces_, regs32bit_, regsInClasses_, regsInRFClasses_, RESERVED, RESULT, Conversion::toString(), use64bitForFP_, and writeRegisterDef().
Referenced by writeRegisterInfo().
write64bitMoveDefs()
void TDGen::write64bitMoveDefs (std::ostream & o) protected
Definition at line 8378 of file TDGen.cc.
{
    o << std::endl << "// 64-bit register->register move definitions."
      << std::endl << "let isAsCheapAsAMove = 1 in {" << std::endl;
    o << "def MOV64rr : InstTCE<(outs R64Regs:$dst), (ins R64Regs:$src),"
      << "             \"$src -> $dst;\", []>;" << std::endl;
    o << "def PRED_TRUE_MOV64rr : InstTCE<(outs R64Regs:$dst), "
      << "(ins R1Regs:$pred, R64Regs:$src), \"$src -> $dst;\", []>;"
      << std::endl;
    o << "def PRED_FALSE_MOV64rr : InstTCE<(outs R64Regs:$dst), "
      << "(ins R1Regs:$pred, R64Regs:$src), \"$src -> $dst;\", []>;"
      << std::endl;
    o << "} // end of is as cheap as move" << std::endl;
}
write64bitRegisterInfo()
void TDGen::write64bitRegisterInfo (std::ostream & o) protected
Writes 64-bit register definitions to the output stream.
Definition at line 1363 of file TDGen.cc.
{
    // --- Hardcoded reserved registers. ---
    std::string i64regs;
    std::string f64regs;
    size_t i  = 0;
    if (mach_.is64bit()) {
        // --- Hardcoded reserved registers. ---
        writeRegisterDef(o, regs64bit_[0], "SP", "R64", "", RESERVED);
        writeRegisterDef(o, regs64bit_[1], "IRES0", "R64", "", RESULT);
        writeRegisterDef(o, regs64bit_[2], "FP", "R64", "", RESERVED);
        writeRegisterDef(
            o, regs64bit_[3], "KLUDGE_REGISTER", "R64", "", RESERVED);
        i64regs = "SP, IRES0, FP, KLUDGE_REGISTER";
        //after the loop, i will have the index of first non-special reg.
        for (i = 4;
             i < std::min(argRegCount_ + 3, (unsigned int)regs64bit_.size());
             i++) {
            std::string regName = "A" + Conversion::toString(i);
            writeRegisterDef(o, regs64bit_[i], regName, "R64", "", ARGUMENT);
            i64regs += ", ";
            i64regs += regName;
        }
    } else {
        if (regs64bit_.size() < 1) {
            RegInfo reg = { "DUMMY64", 0 };
            writeRegisterDef(o, reg, "DUMMY64", "R64", "", RESERVED);
            i64regs = "DUMMY64";
        }
    }
    // i already contains the correct starting index.
    for (; i < regs64bit_.size(); i++) {
        std::string intRegName = "L" + Conversion::toString(i);
        if (i != 0)
            i64regs += ", ";
        i64regs += intRegName;
        writeRegisterDef(o, regs64bit_[i], intRegName, "R64", "", GPR);
    }
    if (mach_.is64bit()) {
        // Bypass registers
        for (size_t j = 0; j < 256; ++j) {
            std::string regName = "BP" + Conversion::toString(j);
            o << "def " << regName << " : "
              << "R64<\"ByPass_Regs"
              << "\", []>, DwarfRegNum<"
              << "[" << dregNum_++ << "]>;"
              << std::endl;
        }
        // Bypass register class
        o << "def R64_ByPass_Regs : RegisterClass<\"TCE\", [i64,i32,f64,f32,f16], 64, (add ";
        for (size_t j = 0; j < 256; ++j) {
            std::string regName = "BP" + Conversion::toString(j);
            if (j != 0) {
                o << ", ";
            }
            o << regName;
        }
        o << ")>;" << std::endl;
    }
    TCEString dataTypes64 = use64bitForFP_ ?
        "[i64,f64,f32,f16]" :
        "[i64,f64]";
    o << std::endl
      << "def R64Regs : RegisterClass<\"TCE\", " << dataTypes64
      << ", 64, (add " << i64regs << ")> ;"
      << std::endl;
    o << std::endl
      << "def R64IRegs : RegisterClass<\"TCE\", [i64], 64, (add "
      << i64regs << ")> ;"
      << std::endl;
    o << std::endl
      << "def R64FPRegs : RegisterClass<\"TCE\", [f32], 64, (add "
      << i64regs << ")>;" << std::endl;
    o << std::endl
      << "def R64HFPRegs : RegisterClass<\"TCE\", [f16], 64, (add "
      << i64regs << ")>;" << std::endl;
    o << std::endl
      << "def R64DFPRegs : RegisterClass<\"TCE\", [f64], 64, (add "
      << i64regs << ")>;" << std::endl << std::endl;
    if (use64bitForFP_) {
        o  << "def FPRegs : RegisterClass<\"TCE\", [f32], 64, (add "
           << i64regs << ")>;" << std::endl << std::endl;
        o  << "def HFPRegs : RegisterClass<\"TCE\", [f16], 64, (add "
           << i64regs << ")>;" << std::endl << std::endl;
    }
}
References argRegCount_, ARGUMENT, dregNum_, GPR, TTAMachine::Machine::is64bit(), mach_, regs64bit_, RESERVED, RESULT, Conversion::toString(), use64bitForFP_, and writeRegisterDef().
Referenced by writeRegisterInfo().
write8bitRegisterInfo()
void TDGen::write8bitRegisterInfo (std::ostream & o) protected
writeAddressingModeDefs()
void TDGen::writeAddressingModeDefs (std::ostream & o) protected
Definition at line 8419 of file TDGen.cc.
{
    if (!mach_.is64bit()) {
        o << std::endl
          << "// Addressing modes." << std::endl
          << "def ADDRrr : ComplexPattern<i32, 2, \"SelectADDRrr\", [], []>;" << std::endl
          << "def ADDRri : ComplexPattern<i32, 2, \"SelectADDRri\", [frameindex], []>;" << std::endl
          << std::endl
          << "// Address operands" << std::endl
          << "def MEMrr : Operand<i32> {" << std::endl
          << "let PrintMethod = \"printMemOperand\";" << std::endl
          << "let MIOperandInfo = (ops R32IRegs, R32IRegs);" << std::endl
          << "}" << std::endl
          << "def MEMri : Operand<i32> {" << std::endl
          << "let PrintMethod = \"printMemOperand\";" << std::endl
          << "let MIOperandInfo = (ops R32IRegs, i32imm);" << std::endl
          << "}" << std::endl
          << std::endl
          << "// Branch targets have OtherVT type." << std::endl
          << "def brtarget : Operand<OtherVT>; " << std::endl
          << "def calltarget : Operand<i32>;" << std::endl;
        o << "def SDT_TCECall    : SDTypeProfile<0, 1, [SDTCisVT<0, i32>]>;" << std::endl;
    } else {
        o << std::endl
          << "// Addressing modes." << std::endl
          << "def ADDRrr : ComplexPattern<i64, 2, \"SelectADDRrr\", [], []>;" << std::endl
          << "def ADDRri : ComplexPattern<i64, 2, \"SelectADDRri\", [frameindex], []>;" << std::endl
          << std::endl
          << "// Address operands" << std::endl
          << "def MEMrr : Operand<i64> {" << std::endl
          << "let PrintMethod = \"printMemOperand\";" << std::endl
          << "let MIOperandInfo = (ops R64IRegs, R64IRegs);" << std::endl
          << "}" << std::endl
          << "def MEMri : Operand<i64> {" << std::endl
          << "let PrintMethod = \"printMemOperand\";" << std::endl
          << "let MIOperandInfo = (ops R64IRegs, i64imm);" << std::endl
          << "}" << std::endl
          << std::endl
          << "// Branch targets have OtherVT type." << std::endl
          << "def brtarget : Operand<OtherVT>; " << std::endl
          << "def calltarget : Operand<i64>;" << std::endl;
        o << "def SDT_TCECall    : SDTypeProfile<0, 1, [SDTCisVT<0, i64>]>;" << std::endl;
    }
}
References TTAMachine::Machine::is64bit(), and mach_.
Referenced by initializeBackendContents().
writeArgRegsArray()
void TDGen::writeArgRegsArray (std::ostream & os) protected
Definition at line 6996 of file TDGen.cc.
{
    os << "#ifndef ARGREGS_HH" << std::endl
       << "#define ARGREGS_HH" << std::endl << std::endl
       << "static const unsigned ArgRegs[] = { TCE::IRES0" << std::endl;
    for (unsigned int i = 4; i < (3 + argRegCount_); i++) {
        os << ",TCE::A" << i;
    }
    os << "};" << std::endl;
    os << "static const int argRegCount = " << argRegCount_ <<";" << std::endl
       << "#endif" << std::endl;
}
References argRegCount_.
Referenced by initializeBackendContents().
writeBackendCode()
void TDGen::writeBackendCode (std::ostream & o) protected
Generates required function definitions for the backend plugin.
Parameters
o Output stream to write the c++ code to.
Definition at line 3997 of file TDGen.cc.
{
    // Register & operation info table initialization
    o << "void" << std::endl
      << "GeneratedTCEPlugin::initialize() {" << std::endl;
    // operation names
    std::map<std::string, std::string>::const_iterator iter =
        opNames_.begin();
    for (; iter != opNames_.end(); iter++) {
        o << "    opNames_[TCE::" << (*iter).first
          << "] = \"" << (*iter).second
          << "\";" << std::endl;
    }
    for (iter = truePredOps_.begin(); iter != truePredOps_.end(); iter++) {
    o << "    truePredOps_[TCE::" << (*iter).first
      << "] = TCE::" << (*iter).second
      << ";" << std::endl;
    }
    for (iter = falsePredOps_.begin(); iter != falsePredOps_.end(); iter++) {
    o << "    falsePredOps_[TCE::" << (*iter).first
      << "] = TCE::" << (*iter).second
      << ";" << std::endl;
    }
    // Register names & indices
    std::map<std::string, RegInfo>::const_iterator rIter = regs_.begin();
    rIter = regs_.begin();
    for (; rIter != regs_.end(); rIter++) {
        const RegInfo& regInfo = rIter->second;
        o << "    regNames_[TCE::" << (*rIter).first
          << "] = \"" << regInfo.rf
          << "\";" << std::endl;
        o << "    regIndices_[TCE::" << (*rIter).first
          << "] = " << regInfo.idx
          << ";" << std::endl;
        TCEString ttaRegName = regInfo.rf + "." + std::to_string(regInfo.idx);
        o << "    ttallvmRegMap_[\"" << ttaRegName << "\"] = "
          << "TCE::" << (*rIter).first << ";" << std::endl;
    }
    // Supported stack access opcodes
    o << std::endl;
    for (std::string opName : supportedStackAccessOperations(mach_)) {
        o << "    validStackAccessOperations_.insert(\"" << opName << "\");"
          << std::endl;
    }
    // data address space
    const TTAMachine::Machine::FunctionUnitNavigator& nav =
        mach_.functionUnitNavigator();
    std::string asName = "";
    for (int i = 0; i < nav.count(); i++) {
        if (nav.item(i) != mach_.controlUnit() &&
            nav.item(i)->addressSpace() != NULL) {
            asName = nav.item(i)->addressSpace()->name();
        }
    }
    if (asName == "") {
        std::string msg = "Couldn't determine data address space.";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    o << "    dataASName_ = \"" << asName << "\";" << std::endl;
    o << "}" << std::endl;
    bool hasSDIV = false;
    bool hasUDIV = false;
    bool hasSREM = false;
    bool hasUREM = false;
    bool hasMUL = false;
    bool hasROTL = false;
    bool hasROTR = false;
    bool hasSXHW = false;
    bool hasSXQW = false;
    bool hasSQRTF = false;
    bool hasSHR = false;
    bool hasSHRU = false;
    bool hasSHL = false;
    bool has8bitLoads = false;
    bool has16bitLoads = false;
//    bool has32bitLoads = false; // used only for 64-bit system
    const TTAMachine::Machine::FunctionUnitNavigator fuNav =
        mach_.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        const TTAMachine::FunctionUnit* fu = fuNav.item(i);
        for (int o = 0; o < fu->operationCount(); o++) {
            const std::string opName =
                StringTools::stringToLower(fu->operation(o)->name());
            if (mach_.is64bit()) {
                if (opName == "div64") hasSDIV = true;
                if (opName == "divu64") hasUDIV = true;
                if (opName == "mod64") hasSREM = true;
                if (opName == "modu64") hasUREM = true;
                if (opName == "mul64") hasMUL = true;
                if (opName == "rotl64") hasROTL = true;
                if (opName == "rotr64") hasROTR = true;
                if (opName == "sxh64") hasSXHW = true;
                if (opName == "sxq64") hasSXQW = true;
                if (opName == "shr64") hasSHR = true;
                if (opName == "shru64") hasSHRU = true;
                if (opName == "shl64") hasSHL = true;
            } else {
                if (opName == "div") hasSDIV = true;
                if (opName == "divu") hasUDIV = true;
                if (opName == "mod") hasSREM = true;
                if (opName == "modu") hasUREM = true;
                if (opName == "mul") hasMUL = true;
                if (opName == "rotl") hasROTL = true;
                if (opName == "rotr") hasROTR = true;
                if (opName == "sxhw") hasSXHW = true;
                if (opName == "sxqw") hasSXQW = true;
                if (opName == "shr") hasSHR = true;
                if (opName == "shru") hasSHRU = true;
                if (opName == "shl") hasSHL = true;
            }
                if (opName == "sqrtf") hasSQRTF = true;
            if (littleEndian_) {
                if (opName == "ld16" || opName == "ldu16") {
                    has16bitLoads = true;
                } else if(opName == "ld8" || opName == "ldu8") {
                    has8bitLoads = true;
//                } else if (opName == "ld32" || opName == "ldu32") {
//                    has32bitLoads = true;
                }
            } else {
                if (opName == "ldh" || opName == "ldhu") {
                    has16bitLoads = true;
                } else if (opName == "ldq" || opName == "ldqu") {
                    has8bitLoads = true;
//                } else if (opName == "ldw") {
//                    has32bitLoads = true;
                }
           }
        }
    }
    o << "bool GeneratedTCEPlugin::hasSDIV() const { return "
      << hasSDIV << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasUDIV() const { return "
      << hasUDIV << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSREM() const { return "
      << hasSREM << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasUREM() const { return "
      << hasUREM << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasMUL() const { return "
      << hasMUL << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasROTL() const { return "
      << hasROTL << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasROTR() const { return "
      << hasROTR << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSXHW() const { return "
      << hasSXHW << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSXQW() const { return "
      << hasSXQW << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSQRTF() const { return "
      << hasSQRTF << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSHR() const { return "
      << hasSHR << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSHL() const { return "
      << hasSHL << "; }" << std::endl
      << "bool GeneratedTCEPlugin::hasSHRU() const { return "
      << hasSHRU << ";}" << std::endl
      << "bool GeneratedTCEPlugin::has8bitLoads() const { return "
      << has8bitLoads << ";}" << std::endl
      << "bool GeneratedTCEPlugin::has16bitLoads() const { return "
      << has16bitLoads << ";}" << std::endl;
//      << "bool GeneratedTCEPlugin::has32bitLoads() const { return "
//      << has32bitLoads << ";}" << std::endl
    o << "int GeneratedTCEPlugin::maxVectorSize() const { return "
      << maxVectorSize_ << "; }" << std::endl;
    // create dummy version here
    genTCERegisterInfo_setReservedVectorRegs(o);
    generateLoadStoreCopyGenerator(o);
    createMinMaxGenerator(o);
    createParamDRegNums(o);
    createVectorRVDRegNums(o);
    createEndiannesQuery(o);
    createConstantMaterializationQuery(o);
    writeGetPointerAdjustmentQuery(o);
    createBranchAnalysis(o);
    genTCETargetLoweringSIMD_addVectorRegisterClasses(o);
    genTCETargetLoweringSIMD_associatedVectorRegClass(o);
    genTCETargetLoweringSIMD_getSetCCResultVT(o);
    genTCEInstrInfoSIMD_copyPhysVectorReg(o);
    genGeneratedTCEPlugin_getLoadOpcode(o);
    genGeneratedTCEPlugin_getAddOpcode(o);
    genGeneratedTCEPlugin_getShlOpcode(o);
    genGeneratedTCEPlugin_getIorOpcode(o);
}
References __func__, TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), createBranchAnalysis(), createConstantMaterializationQuery(), createEndiannesQuery(), createMinMaxGenerator(), createParamDRegNums(), createVectorRVDRegNums(), falsePredOps_, TTAMachine::Machine::functionUnitNavigator(), generateLoadStoreCopyGenerator(), genGeneratedTCEPlugin_getAddOpcode(), genGeneratedTCEPlugin_getIorOpcode(), genGeneratedTCEPlugin_getLoadOpcode(), genGeneratedTCEPlugin_getShlOpcode(), genTCEInstrInfoSIMD_copyPhysVectorReg(), genTCERegisterInfo_setReservedVectorRegs(), genTCETargetLoweringSIMD_addVectorRegisterClasses(), genTCETargetLoweringSIMD_associatedVectorRegClass(), genTCETargetLoweringSIMD_getSetCCResultVT(), TDGen::RegInfo::idx, TTAMachine::Machine::is64bit(), TTAMachine::Machine::Navigator< ComponentType >::item(), littleEndian_, mach_, maxVectorSize_, TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), opNames_, regs_, TDGen::RegInfo::rf, StringTools::stringToLower(), supportedStackAccessOperations(), truePredOps_, and writeGetPointerAdjustmentQuery().
Referenced by initializeBackendContents().
writeBooleanStorePatterns()
void TDGen::writeBooleanStorePatterns (std::ostream & os) protected
Writes special store patterns for i1 types.
Definition at line 4568 of file TDGen.cc.
{
    std::string storeOp("");
    auto storeOps = littleEndian_
                        ? std::vector<std::string>{"ST8ri", "ST8rr"}
                        : std::vector<std::string>{"STQri", "STQrr"};
    for (auto op : storeOps) {
        if (opNames_.count(op)) {
            storeOp = op;
            break;
        }
    }
    if (storeOp.empty()) return;
    // TODO: is this 32 correct for 64-bit ADFs?
    auto storeConstBit = [=](const std::string& bitVal) -> std::string {
        return std::string("(") + storeOp + " ADDRrr:$addr, " +
               (storeOp.back() == 'i' ? "(i32 " : "(MOVI32ri ") + bitVal +
               "))";
    };
    // Patterns to avoid i1 "true" values to be emitted as -1, which breaks
    // on, for example, BZ and BNZ if the condition is loaded later, inverted
    // using XOR and finally the result is bypassed: this results the -1 to be
    // converted to -2, which is interpreted still as true.
    os << "def : Pat<(store (i1 -1), ADDRrr:$addr), " << std::endl
       << "          " << storeConstBit("1") << ">;" << std::endl;
    os << "def : Pat<(store (i1 1), ADDRrr:$addr), " << std::endl
       << "          " << storeConstBit("1") << ">;" << std::endl;
    os << "def : Pat<(store (i1 0), ADDRrr:$addr), " << std::endl
       << "          " << storeConstBit("0") << ">;" << std::endl;
}
References littleEndian_, and opNames_.
Referenced by writeInstrInfo().
writeBroadcastDefs()
void TDGen::writeBroadcastDefs (std::ostream & o, Operation & op, int vectorLen) protected
writeCallDef()
void TDGen::writeCallDef (std::ostream & o) protected
Writes .td pattern for the call instruction(s) to the output stream.
Definition at line 3955 of file TDGen.cc.
{
    o << "let ";
    if (!argRegNames_.empty()) {
        o << "Uses = [";
        for (unsigned i = 0; i < argRegNames_.size(); i++) {
            if (i > 0) o << ", ";
            o << argRegNames_[i];
        }
        o << "],";
    }
    o << "hasDelaySlot = 1, isCall = 1,";
    o << "Defs = [";
    writeCallDefRegs(o);
    o << "] in {" << std::endl;
    o << "def CALL : InstTCE<(outs), (ins calltarget:$dst),";
    o << "\"$dst -> call.1;\", []>;" << std::endl;
    o << "def CALL_MEMrr : InstTCE<(outs), (ins MEMrr:$ptr),";
    o << "\"$ptr -> call.1;\", [(call ADDRrr:$ptr)]>;" << std::endl;
    o << "def CALL_MEMri : InstTCE<(outs), (ins MEMri:$ptr),";
    o << "\"$ptr -> call.1;\", [(call ADDRri:$ptr)]>;" << std::endl;
    o << "}" << std::endl;
    o << "def : Pat<(call tglobaladdr:$dst), (CALL tglobaladdr:$dst)>;"
      << std::endl;
    o << "def : Pat<(call texternalsym:$dst), (CALL texternalsym:$dst)>;"
      << std::endl;
}
References argRegNames_, and writeCallDefRegs().
Referenced by writeControlFlowInstrDefs().
writeCallDefRegs()
void TDGen::writeCallDefRegs (std::ostream & o) protected virtual
Definition at line 3580 of file TDGen.cc.
{
    for (unsigned i = 0; i < resRegNames_.size(); i++) {
        if (i > 0) o << ", ";
        o << resRegNames_[i];
    }
    for (unsigned i = 0; i < gprRegNames_.size(); i++) {
        o << ", " << gprRegNames_[i];
    }
    // call dest may call others which may mess up these
    for (unsigned i = 0; i < argRegNames_.size(); i++) {
        o << ", " << argRegNames_[i];
    }
    std::map<int, std::vector<RegisterInfo>>::const_iterator it;
    for (it = registers_.begin(); it != registers_.end(); ++it) {
        int regsWidth = it->first;
        const std::vector<RegisterInfo>& regs = it->second;
        TCEString baseClass = baseClasses_.find(regsWidth)->second;
        for (size_t i = 0; i < regs.size(); ++i) {
            // Don't declare <=32b registers again, it has been done in TDGen.
            if (regsWidth > maxScalarWidth_) {
                RegisterInfo reg = regs[i];
                o << ", " << reg.regName_;
            }
        }
    }
}
References argRegNames_, baseClasses_, gprRegNames_, maxScalarWidth_, registers_, TDGenerator::RegisterInfo::regName_, and resRegNames_.
Referenced by writeCallDef().
writeCallingConv()
void TDGen::writeCallingConv (std::ostream & os) protected
Writes details about function arguments and returns values.
Parameters
o Output stream to the file.
Definition at line 6870 of file TDGen.cc.
{
    writeCallingConvLicenceText(os);
    int bits = mach_.is64bit() ? 64 : 32;
    int bytes = mach_.is64bit() ? 8 : 4;
    // Function return value types.
    os << "// Function return value types." << endl;
    os << "def RetCC_TCE : CallingConv<[" << endl;
    if (mach_.is64bit()) {
        os << "  CCIfType<[i1], CCPromoteToType<i64>>," << endl
           << "  CCIfType<[i32], CCPromoteToType<i64>>," << endl
           << "  CCIfType<[i64], CCAssignToReg<[IRES0]>>," << endl
           << "  CCIfType<[f64], CCAssignToReg<[IRES0]>>," << endl << endl;
    } else {
        os << "  CCIfType<[i1], CCPromoteToType<i32>>," << endl;
        os << "  CCIfType<[i32], CCAssignToReg<[IRES0]>>," << endl;
    }
    os << "  CCIfType<[f16], CCAssignToReg<[IRES0]>>," << endl
       << "  CCIfType<[f32], CCAssignToReg<[IRES0]>>," << endl << endl;
    os << "  // Vector value types." << endl;
    std::map<TCEString, RegisterClass>::const_iterator rcIt;
    for (rcIt = vRegClasses_.begin(); rcIt != vRegClasses_.end(); ++rcIt) {
        const TCEString& vtStr = rcIt->first;
        const RegisterClass& regClass = rcIt->second;
        if (regClass.numberOfRegisters() > 0) {
            os << "  CCIfType<[" << vtStr << "], CCAssignToReg<[";
            if (regClass.valueType().width() <= bits) {
                os << "IRES0";
            } else {
                os << regClass.registerInfo(0).regName_;
            }
            os << "]>>," << endl;
        } else {
            verbose("ValueType " + vtStr + " can not be a return value");
        }
    }
    os << "  CCAssignToStack<" << bytes << ", " << bytes << ">" << endl
       << "]>;" << endl << endl;
    // Function argument value types.
    os << "// Function argument value types." << endl;
    os << "def CC_TCE : CallingConv<[" << endl;
    if (mach_.is64bit()) {
        os << "  CCIfType<[i1, i8, i16, i32], CCPromoteToType<i64>>," << endl
           << "  CCIfType<[i64], CCAssignToReg<[IRES0]>>," << endl << endl;
        for (unsigned int i = 4; i < (3 + argRegCount_); i++) {
            os << "  CCIfType<[i64], CCAssignToReg<[A" << i << "]>>," << endl;
        }
    } else {
        os << "  CCIfType<[i1, i8, i16], CCPromoteToType<i32>>," << endl
           << "  CCIfType<[i32], CCAssignToReg<[IRES0]>>," << endl << endl;
        for (unsigned int i = 4; i < (3 + argRegCount_); i++) {
            os << "  CCIfType<[i32], CCAssignToReg<[A" << i << "]>>," << endl;
        }
    }
    if (mach_.is64bit()) {
        os << "  // 64-bit integer values get stored in stack slots that are"
           << endl
           << "  // 8 bytes insize and 8-byte aligned." << endl
           << "  CCIfType<[i64, f64, f32], CCAssignToStack<8, 8>>,"
           << endl << endl;
    } else {
        os << "  // Integer values get stored in stack slots that are" << endl
           << "  // 4 bytes insize and 4-byte aligned." << endl
           << "  CCIfType<[i32, f32], CCAssignToStack<4, 4>>," << endl << endl;
    }
    os << "  // Double values get stored in stack slots that are" << endl
       << "  // 8 bytes in size and 8-byte aligned." << endl
       << "  CCIfType<[f64], CCAssignToStack<8, 8>>";
    if (vRegClasses_.size() > 0) {
        os << ",";
    }
    os << endl << endl;
    os << "  // Vector value types." << endl;
    for (rcIt = vRegClasses_.begin(); rcIt != vRegClasses_.end(); ++rcIt) {
        const TCEString& vtStr = rcIt->first;
        const RegisterClass& regClass = rcIt->second;
        int byteAlignment = regClass.alignment() / 8;
        if (byteAlignment < bytes) {
            byteAlignment = bytes;
        }
        os << "  CCIfType<[" << vtStr << "], CCAssignToStack<"
               << byteAlignment << ", " << byteAlignment << ">>";
        if (rcIt != --vRegClasses_.end()) {
            os << ",";
        }
        os << endl;
    }
    os << "]>;" << endl;
}
References TDGenerator::RegisterClass::alignment(), argRegCount_, TTAMachine::Machine::is64bit(), mach_, TDGenerator::RegisterClass::numberOfRegisters(), TDGenerator::RegisterClass::registerInfo(), TDGenerator::RegisterInfo::regName_, TDGenerator::RegisterClass::valueType(), verbose(), vRegClasses_, TDGenerator::ValueType::width(), and writeCallingConvLicenceText().
Referenced by initializeBackendContents().
writeCallingConvLicenceText()
void TDGen::writeCallingConvLicenceText (std::ostream & os) protected
Definition at line 6975 of file TDGen.cc.
{
    os << "//===- GenCallingConv.td - Calling Conventions TCE ---------*- "
       << "tablegen -*-===//" << std::endl
       << "// " << std::endl
       << "//                     The LLVM Compiler Infrastructure" << std::endl
       << "//" << std::endl
       << "// This file is distributed under the University of "
       << "Illinois Open Source" << std::endl
       << "// License. See LICENSE.TXT for details." << std::endl
       << "// " << std::endl
       << "//===--------------------------------------------------------"
       << "--------------===//" << std::endl
       << "//" << std::endl
       << "// This describes the calling conventions for the TCE "
       << "architectures." << std::endl
       << "//" << std::endl
       << "//===--------------------------------------------------------"
       << "--------------===//" << std::endl << std::endl;
}
Referenced by writeCallingConv().
writeCallSeqStart()
void TDGen::writeCallSeqStart (std::ostream & os) protected
Definition at line 7944 of file TDGen.cc.
{
    bool is64bit = mach_.is64bit();
  if (!is64bit) {
      os << "def SDT_TCECallSeqStart : SDCallSeqStart<[ SDTCisVT<0, i32>,"
         << "SDTCisVT<1, i32> ]>;" << std::endl << std::endl;
  } else {
      os << "def SDT_TCECallSeqStart : SDCallSeqStart<[ SDTCisVT<0, i64>,"
         << "SDTCisVT<1, i64> ]>;" << std::endl << std::endl;
  }
  os << "def callseq_start : SDNode<\"ISD::CALLSEQ_START\", "
     << "SDT_TCECallSeqStart, [SDNPHasChain, SDNPOutGlue]>;" << std::endl
     << std::endl
     << "let Defs = [SP], Uses = [SP] in {" << std::endl
     << "def ADJCALLSTACKDOWN : Pseudo<(outs),";
  if (!is64bit) {
      os << "(ins i32imm:$amt1, i32imm:$amt2),";
  } else {
      os << "(ins i64imm:$amt1, i64imm:$amt2),";
  }
  os << "\"# ADJCALLSTACKDOWN $amt1, $amt2\","
     << "[(callseq_start timm:$amt1, timm:$amt2)]>;}"
     << std::endl << std::endl;
}
References TTAMachine::Machine::is64bit(), and mach_.
Referenced by writeInstrInfo().
writeCondBranchDefs()
void TDGen::writeCondBranchDefs (std::ostream & os) protected
Writes instructions definitions and patterns for conditional branches.
Definition at line 3661 of file TDGen.cc.
{
    auto cuOpset = MachineInfo::getOpset(*mach_.controlUnit());
    if (MachineInfo::supportsBoolRegisterGuardedJumps(mach_)) {
        os << std::endl << "let isTerminator = 1, isBranch = 1 in {" << std::endl;
        if (cuOpset.count("JUMP") && opNames_.count("TCEBRCOND") == 0) {
            writeInstrDef(os, "TCEBRCOND", "",
                          "GuardRegs:$gr, brtarget:$dst",
                          "? $gr $dst -> jump.1;",
                          "(brcond GuardRegs:$gr, bb:$dst)");
            os << std::endl;
            opNames_["TCEBRCOND"] = "?jump";
        }
        if (cuOpset.count("JUMP") && opNames_.count("TCEBRICOND") == 0) {
            writeInstrDef(os, "TCEBRICOND", "",
                          "GuardRegs:$gr, brtarget:$dst",
                          "! $gr $dst -> jump.1;",
                          "(brcond (not GuardRegs:$gr), bb:$dst)");
            opNames_["TCEBRICOND"] = "!jump";
        }
        os << "}" << std::endl;
        // generate brcc pseudo jumps. these are split in llvmtcebuilder into
        // separate comparison and jump.
    } else if (MachineInfo::supportsPortGuardedJumps(mach_)) {
        if  (!writePortGuardedJumpDefPair(os, "EQ", "NE")) {
            abortWithError("Required eq/ne op not found. please add to adf.");
        }
        if (!writePortGuardedJumpDefPair(os, "GT", "LE")) {
            abortWithError("Required gt/le op not found. please add to adf.");
        }
        if (!writePortGuardedJumpDefPair(os, "GTU", "LEU")) {
            abortWithError("Required gtu/leu op not found. please add to adf.");
        }
        // floating point ops are optional.
        writePortGuardedJumpDefPair(os, "EQF", "NEF", true);
        writePortGuardedJumpDefPair(os, "LEF", "GTF", true);
        writePortGuardedJumpDefPair(os, "LTF", "GEF", true);
        if (MachineInfo::supportsPortGuardedJump(mach_, false, "AND")) {
            writeInstrDef(os, "AND_JUMP", "",
                          "R32IRegs:$cmp1, R32IRegs:$cmp2, brtarget:$dst", "",
                          "(brcond (and R32IRegs:$cmp1, R32IRegs:$cmp2), bb:$dst)");
        } else {
            std::cerr << "Missing AND operation as true-guard source to jump." << std::endl;
            assert(false);
        }
        if (MachineInfo::supportsPortGuardedJump(mach_, false, "IOR")) {
            writeInstrDef(os, "IOR_JUMP", "",
                          "R32IRegs:$cmp1, R32IRegs:$cmp2, brtarget:$dst", "",
                          "(brcond (or R32IRegs:$cmp1, R32IRegs:$cmp2), bb:$dst)");
        } else {
            std::cerr << "Missing IOR operation as true-guard source to jump." << std::endl;
            assert(false);
        }
        os << std::endl << "let isTerminator = 1, isBranch = 1 in {" << std::endl;
        // dummy br(i)cond ops
        writeInstrDef(os, "TCEBRCOND", "",
                      "GuardRegs:$gr, brtarget:$dst",
                      "? $gr $dst -> jump.1;",
                      "");
        os << std::endl;
        writeInstrDef(os, "TCEBRICOND", "",
                      "GuardRegs:$gr, brtarget:$dst",
                      "? $gr $dst -> jump.1;",
                      "");
        os << std::endl;
        os << "}" << std::endl;
        os << "def: Pat<(brcc SETLT, R32IRegs:$cmp1, R32IRegs:$cmp2, bb:$dst),"
           << " (GT_JUMP R32IRegs:$cmp2, R32IRegs:$cmp1, brtarget:$dst)>;" << std::endl;
        os << "def: Pat<(brcc SETGE, R32IRegs:$cmp1, R32IRegs:$cmp2, bb:$dst),"
           << " (LE_JUMP R32IRegs:$cmp2, R32IRegs:$cmp1, brtarget:$dst)>;" << std::endl;
        os << "def: Pat<(brcc SETULT, R32IRegs:$cmp1, R32IRegs:$cmp2, bb:$dst),"
           << " (GTU_JUMP R32IRegs:$cmp2, R32IRegs:$cmp1, brtarget:$dst)>;" << std::endl;
        os << "def: Pat<(brcc SETUGE, R32IRegs:$cmp1, R32IRegs:$cmp2, bb:$dst),"
           << " (LEU_JUMP R32IRegs:$cmp2, R32IRegs:$cmp1, brtarget:$dst)>;" << std::endl;
        opNames_["AND_JUMP"] = "and+?jump";
        opNames_["IOR_JUMP"] = "ior+?jump";
        // conditional jumps without guard.
    } else {
        os << std::endl << "let isTerminator = 1, isBranch = 1 in {" << std::endl;
        if (cuOpset.count("BNZ1")) {
            // TODO: Check if has R1 regs or not!
            writeInstrDef(os, "TCEBRCOND", "", "R32IRegs:$gr, brtarget:$dst",
                "", "(brcond R32IRegs:$gr, bb:$dst)");
            os << std::endl;
            opNames_["TCEBRCOND"] = "BNZ1";
        } else {
            if (cuOpset.count("BNZ")) {
                writeInstrDef(os, "TCEBRCOND", "", "R32IRegs:$gr, brtarget:$dst",
                              "", "(brcond R32IRegs:$gr, bb:$dst)");
                os << std::endl;
                opNames_["TCEBRCOND"] = "BNZ";
            } else {
                std::cerr << "Does not have guarded jumps or neither bnz or bnz1" << std::endl;
            }
        }
        if (cuOpset.count("BZ1")) {
            // TODO: Check if has R1 regs or not!
            writeInstrDef(os, "TCEBRICOND", "", "R32IRegs:$gr, brtarget:$dst",
                "", "(brcond (not R32IRegs:$gr), bb:$dst)");
            os << std::endl;
            opNames_["TCEBRICOND"] = "BZ1";
        } else {
            if (cuOpset.count("BZ")) {
                writeInstrDef(os, "TCEBRICOND", "", "R32IRegs:$gr, brtarget:$dst",
                              "", "(brcond (not R32IRegs:$gr), bb:$dst)");
                os << std::endl;
                opNames_["TCEBRICOND"] = "BZ";
            } else {
                std::cerr << "Does not have guarded jumps or neither bz or bz1" << std::endl;
            }
        }
        if (cuOpset.count("BEQ")) {
            writeInstrDef(os, "TCEBREQrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (seteq R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBREQrr"] = "BEQ";
            writeInstrDef(os, "TCEBREQri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (seteq R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBREQri"] = "BEQ";
        }
        if (cuOpset.count("BNE")) {
            writeInstrDef(os, "TCEBRNErr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setne R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRNErr"] = "BNE";
            writeInstrDef(os, "TCEBRNEri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setne R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRNEri"] = "BNE";
        }
        if (cuOpset.count("BGT")) {
            writeInstrDef(os, "TCEBRGTrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setgt R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRGTrr"] = "BGT";
            writeInstrDef(os, "TCEBRGTri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setgt R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRGTri"] = "BGT";
        }
        if (cuOpset.count("BGTU")) {
            writeInstrDef(os, "TCEBRGTUrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setugt R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRGTUrr"] = "BGTU";
            writeInstrDef(os, "TCEBRGTUri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setugt R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRGTUri"] = "BGTU";
        }
        if (cuOpset.count("BLT")) {
            writeInstrDef(os, "TCEBRLTrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setlt R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRLTrr"] = "BLT";
            writeInstrDef(os, "TCEBRLTri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setlt R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRLTri"] = "BLT";
        }
        if (cuOpset.count("BLTU")) {
            writeInstrDef(os, "TCEBRLTUrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setult R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRLTUrr"] = "BLTU";
            writeInstrDef(os, "TCEBRLTUri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setult R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRLTUri"] = "BLTU";
        }
        if (cuOpset.count("BLE")) {
            writeInstrDef(os, "TCEBRLErr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setle R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRLErr"] = "BLE";
            writeInstrDef(os, "TCEBRLEri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setle R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRLEri"] = "BLE";
        }
        if (cuOpset.count("BLEU")) {
            writeInstrDef(os, "TCEBRLEUrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setule R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRLEUrr"] = "BLEU";
            writeInstrDef(os, "TCEBRLEUri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setule R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRLEUri"] = "BLEU";
        }
        if (cuOpset.count("BGE")) {
            writeInstrDef(os, "TCEBRGErr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setge R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRGErr"] = "BGE";
            writeInstrDef(os, "TCEBRGEri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setge R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRGEri"] = "BGE";
        }
        if (cuOpset.count("BGEU")) {
            writeInstrDef(os, "TCEBRGEUrr", "", "R32IRegs:$c1, R32IRegs:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setuge R32IRegs:$c1, R32IRegs:$c2)), bb:$dst)");
            opNames_["TCEBRGEUrr"] = "BGEU";
            writeInstrDef(os, "TCEBRGEUri", "", "R32IRegs:$c1, i32imm:$c2, brtarget:$dst",
                          "", "(brcond (i32 (setuge R32IRegs:$c1, i32MoveImm:$c2)), bb:$dst)");
            opNames_["TCEBRGEUri"] = "BGEU";
        }
        os << "}" << std::endl;
    }
}
References abortWithError, assert, TTAMachine::Machine::controlUnit(), MachineInfo::getOpset(), mach_, opNames_, MachineInfo::supportsBoolRegisterGuardedJumps(), MachineInfo::supportsPortGuardedJump(), MachineInfo::supportsPortGuardedJumps(), writeInstrDef(), and writePortGuardedJumpDefPair().
Referenced by writeControlFlowInstrDefs().
writeConstShiftPat()
void TDGen::writeConstShiftPat (std::ostream & os, const TCEString & nodeName, const TCEString & opNameBase, int i) protected
Definition at line 8577 of file TDGen.cc.
{
    if (!mach_.is64bit()) {
        TCEString opName = opNameBase; opName << i << "_32rr";
        if (opNames_.find(opName) != opNames_.end()) {
            os << "def : Pat<(i32 (" << nodeName
               << " R32IRegs:$val, (i32 " << i << "))), ("
               << opName << " R32IRegs:$val)>;" << std::endl;
        }
    } else {
        TCEString opName = opNameBase; opName << i << "_64rr";
        if (opNames_.find(opName) != opNames_.end()) {
            os << "def : Pat<(i64 (" << nodeName
               << " R64IRegs:$val, (i64 " << i << "))), ("
               << opName << " R64IRegs:$val)>;" << std::endl;
        }
    }
}
References TTAMachine::Machine::is64bit(), mach_, and opNames_.
Referenced by createConstShiftPatterns().
writeControlFlowInstrDefs()
void TDGen::writeControlFlowInstrDefs (std::ostream & os) protected
Writes control flow instructions definitions and patterns
Definition at line 3616 of file TDGen.cc.
{
    writeCondBranchDefs(os);
    writeCallDef(os);
}
References writeCallDef(), and writeCondBranchDefs().
Referenced by writeInstrInfo().
writeEmulationPattern()
void TDGen::writeEmulationPattern (std::ostream & o, const Operation & op, const OperationDAG & dag) protected
Writes operation emulation pattern in .td format to an output stream.
Parameters
o Output stream to write the definition to.
op Emulated operation.
dag Emulation pattern.
Definition at line 4800 of file TDGen.cc.
{
    char operandCh = mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    const OperationDAGNode* res = *(dag.endNodes().begin());
    if (dag.endNodes().empty()) {
        std::cerr << "end nodes of dag for operation: " << op.name()
                  << " is empty!" << std::endl;
        assert(false);
    }
    const OperationNode* opNode = dynamic_cast<const OperationNode*>(res);
    if (opNode == NULL) {
        assert(dag.inDegree(*res) ==  1);
        const OperationDAGEdge& edge = dag.inEdge(*res, 0);
        res = dynamic_cast<OperationNode*>(&dag.tailNode(edge));
        assert(res != NULL);
    }
    int inputCount = op.numberOfInputs();
    bool ok = true;
    std::string llvmPat = llvmOperationPattern(op, operandCh);
    if (llvmPat == "") {
        std::cerr << "unknown op: " << op.name() << std::endl;
    }
    assert(llvmPat != "" && "Unknown operation to emulate.");
    boost::format match1(llvmPat);
    int outputs = op.numberOfOutputs();
    std::string operandTypes;
    for (int i = 0; i < outputs; i++) {
        operandTypes += operandChar(op.operand(i+inputCount + 1));
    }
    for (int i = 0; i < op.numberOfInputs(); i++) {
        char inputType = operandChar(op.operand(i+1));
        std::string immDef = immediateOperandNameForEmulatedOperation(
            dag, op.operand(i + 1));
        operandTypes += inputType;
        match1 % operandToString(op.operand(i + 1), false, inputType, immDef);
    }
    if (ok) {
        o << "def : Pat<(" << match1.str() << "), "
            << dagNodeToString(op, dag, *res, true, operandTypes)
            << ">;" << std::endl;
        // need to generate emulation patterns for boolean out
        // for these comparison operations.
        if (op.name() == "LTF" || op.name() == "LTUF" ||
            op.name() == "EQF" || op.name() == "EQUF" ||
            op.name() == "GEF" || op.name() == "GEUF" ||
            op.name() == "LEF" || op.name() == "LEUF" ||
            op.name() == "GTF" || op.name() == "GTUF" ||
            op.name() == "NEF" || op.name() == "NEUF" ||
            op.name() == "EQ" || op.name() == "NE" ||
            op.name() == "EQ64" || op.name() == "NE64" ||
            op.name() == "GE" ||op.name() == "GEU" ||
            op.name() == "GE64" ||op.name() == "GEU64" ||
            op.name() == "GT" || op.name() == "GTU" ||
            op.name() == "GT64" || op.name() == "GTU64" ||
            op.name() == "LE" || op.name() == "LEU" ||
            op.name() == "LE64" || op.name() == "LEU64" ||
            op.name() == "LT" || op.name() == "LTU" ||
            op.name() == "LT64" || op.name() == "LTU64" ||
            op.name() == "LTD" || op.name() == "LTUD" ||
            op.name() == "EQD" || op.name() == "EQUD" ||
            op.name() == "GED" || op.name() == "GEUD" ||
            op.name() == "LED" || op.name() == "LEUD" ||
            op.name() == "GTD" || op.name() == "GTUD" ||
            op.name() == "NED" || op.name() == "NEUD" ||
            op.name() == "ORDD" || op.name() == "UORDD" ||
            op.name() == "ORDF" || op.name() == "UORDF") {
            std::string boolOperandTypes = operandTypes;
            boolOperandTypes[0] = 'b';
            o << "def : Pat<(" << match1.str() << "), "
              << dagNodeToString(op, dag, *res, true, boolOperandTypes)
              << ">;" << std::endl;
        }
    }
}
References assert, dagNodeToString(), OperationDAG::endNodes(), immediateOperandNameForEmulatedOperation(), BoostGraph< GraphNode, GraphEdge >::inDegree(), BoostGraph< GraphNode, GraphEdge >::inEdge(), TTAMachine::Machine::is64bit(), llvmOperationPattern(), mach_, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), operandChar(), operandToString(), OT_REG_INT, OT_REG_LONG, and BoostGraph< GraphNode, GraphEdge >::tailNode().
Referenced by writeInstrInfo().
writeGetPointerAdjustmentQuery()
void TDGen::writeGetPointerAdjustmentQuery (std::ostream & os) const protected
Writes query method for retrieving LLVM instruction for pointer adjustment and suitable offset value.
Some machines may not SUBrri definition (second operand can not take an immediate) and, therefore, pointer adjustments must use other operation for it.
Definition at line 7522 of file TDGen.cc.
{
    TCEString ADDIMM = mach_.is64bit() ? "ADD64ssa" : "ADDrri";
    TCEString SUBIMM = mach_.is64bit() ? "SUB64ssa" : "SUBrri";
    boost::format queryTmpl(
        "// <MI opcode, adjusted offset>\n"
        "std::tuple<int, int> GeneratedTCEPlugin::getPointerAdjustment(\n"
        "    int offset) const {\n"
        "    if (offset > 0)  // Adjust pointer up.\n"
        "        return std::make_tuple(TCE::%1%, offset);\n"
        "    else\n"
        "        return std::make_tuple(TCE::%2%, %3%);\n"
        "}\n");
    // Prefer non-negative offset
    if (opNames_.count(SUBIMM)) {
        os << queryTmpl % ADDIMM % SUBIMM % "-offset" << std::endl;
        return;
    } else if (opNames_.count("ADDrri")) {
        os << queryTmpl % ADDIMM % ADDIMM % "offset" << std::endl;
        return;
    }
    THROW_EXCEPTION(
        InvalidData,
        "The machine is missing ADD or SUB operation with direct\n"
        "immediate source for pointer adjustment operations.");
    return;
}
References ADDIMM, TTAMachine::Machine::is64bit(), mach_, opNames_, SUBIMM, and THROW_EXCEPTION.
Referenced by writeBackendCode().
writeGuardRegisterClassInfo()
void TDGen::writeGuardRegisterClassInfo (std::ostream & o) protected
Writes register class for registers usable as guard.
Call this after all regular register definitions are written (after all calls to writeRegisterDef());
Definition at line 2008 of file TDGen.cc.
{
    int bits = mach_.is64bit() ? 64 : 32;
    o << std::endl
      << "// #################################" << std::endl
      << "// Register class definitions for guards" << std::endl;
    if (llvmGuardRegs_.empty()) {
        o << "// No guard registers in this machine" << std::endl;
        RegInfo reg = {"noGuardReg", 0};
        std::string name = "NOGUARD";
        writeRegisterDef(o, reg, name, "R1", "", RESERVED);
        o << "def " << guardRegTemplateName
          << "Regs : RegisterClass<\"TCE\", [i1], " << bits << ", (add "
          << name << ")>;" << std::endl;
        return;
    }
    o << "def " << guardRegTemplateName
      << "Regs : RegisterClass<\"TCE\", [i1], " << bits << ", (add ";
    bool firstItem = true;
    for (auto& regDef : llvmGuardRegs_) {
        if (firstItem) {
            o << regDef;
            firstItem = false;
            continue;
        }
        o << ", " << regDef;
    }
    o << ")> {" << std::endl;
    o << "    let Size=" << bits << ";" << std::endl;
    o << "}" << std::endl;
    o << "// #################################" << std::endl << std::endl;
}
References guardRegTemplateName, TTAMachine::Machine::is64bit(), llvmGuardRegs_, mach_, RESERVED, and writeRegisterDef().
Referenced by writeRegisterInfo().
writeHWLoopDef()
void TDGen::writeHWLoopDef (std::ostream & os) protected
Writes hwloop instructions and patterns.
Definition at line 3627 of file TDGen.cc.
{
    os << std::endl << "// Hardware loop instructions" << std::endl;
    if (mach_.controlUnit()->hasOperation("hwloop")) {
        os << "let isTerminator=1 in {" << std::endl
           << "  def HWLOOPii : InstTCE<(outs), (ins i32imm0:$rIter, "
              "i32imm0:$rInstr), \"\", []>;"
           << std::endl
           << "  def HWLOOPri : InstTCE<(outs), (ins i32imm0:$rIter, "
              "i32imm0:$rInstr), \"\", []>;"
           << std::endl
           << "}" << std::endl
           << "def : Pat<(int_set_loop_iterations i32imm0:$rIter), "
              "(HWLOOPii i32imm0:$rIter, 0)>;"
           << std::endl
           << "def : Pat<(int_set_loop_iterations R32IRegs:$rIter), "
              "(HWLOOPri R32IRegs:$rIter, 0)>;"
           << std::endl;
        opNames_["HWLOOPii"] = "hwloop";
        opNames_["HWLOOPri"] = "hwloop";
    }
    // Write loop jump pseudo
    os << "let isTerminator = 1 in {" << std::endl
       << "  def LJUMP : InstTCE<(outs), (ins brtarget:$dst), \"\", []>;"
       << std::endl
       << "}" << std::endl
       << std::endl;
    opNames_["LJUMP"] = "PSEUDO";
}
References TTAMachine::Machine::controlUnit(), TTAMachine::FunctionUnit::hasOperation(), mach_, and opNames_.
Referenced by writeInstrInfo().
writeImmediateDef()
void TDGen::writeImmediateDef (std::ostream & o, const std::string & defName, const std::string & operandType, const std::string & predicate) protected virtual
Writes single immediate operand definitions to the stream.
Parameters
o The output stream.
defName The name of the immediate operand definition.
operandType The target type (i.e "i32").
predicate The predicate expression without return statement or ';' at the end.
Definition at line 4610 of file TDGen.cc.
{
    o << "def " << defName << " : Operand<" << operandType
      << "> , ImmLeaf<" << operandType << ", [{" << std::endl
      << "    return " << predicate << ";}]>;" << std::endl;
}
Referenced by createConstantMaterializationPatterns(), writeIntegerImmediateDefs(), and writeMoveImmediateDefs().
writeInstrDef()
void TDGen::writeInstrDef (std::ostream & o, const std::string & instrDefName, const std::string & outs, const std::string & ins, const std::string & asmString, const std::string & pattern) protected
Writes LLVM instruction definition in TCE format to the stream.
Definition at line 4626 of file TDGen.cc.
{
    o << "def " << instrDefName << " : InstTCE<" << std::endl
      << "    (outs " << outs << ")," << std::endl
      << "    (ins " << ins << ")," << std::endl
      << "    \"" << asmString << "\", " << std::endl
      << "    [" << pattern << "]>;" << std::endl;
}
Referenced by writeCondBranchDefs(), and writePortGuardedJumpDefPair().
writeInstrFormats()
void TDGen::writeInstrFormats (std::ostream & o) protected
Writes details about instruction formatting
Parameters
o Output stream to the file.
Definition at line 4255 of file TDGen.cc.
{
    o << "//" << endl;
    o << "// TCE Instruction formats." << endl;
    o << "//" << endl;
    o << "// Only one simple format is currently available" << endl;
    o << "//" << endl;
    o << "// Automatically generated file, do not edit!" << endl;
    o << "//" << endl;
    o << "" << endl;
    o << "class InstTCE<dag outOps, dag inOps, string asmstr," << endl;
    o << "              list<dag> pattern = []," << endl;
    o << "              InstrItinClass itin = IT_FU>" << endl;
    o << "             : Instruction {" << endl;
    o << "    let Namespace = \"TCE\";" << endl;
    o << "    dag InOperandList = inOps;" << endl;
    o << "    dag OutOperandList = outOps;" << endl;
    o << "    let AsmString = asmstr;" << endl;
    o << "    let Pattern = pattern;" << endl;
    o << "    let Itinerary = itin;" << endl;
    o << "}" << endl;
    o << "" << endl;
    o << "class Pseudo<dag outOps, dag inOps," << endl;
    o << "             string asmstr, list<dag> pattern>" << endl;
    o << "   : InstTCE<outOps, inOps, asmstr, pattern>;" << endl;
}
Referenced by initializeBackendContents().
writeInstrInfo()
void TDGen::writeInstrInfo (std::ostream & os) protected
Writes all machine instructions to instruction info .td file.
Parameters
os Output stream to the file.
Note
This todo marking is from TDGenSIMD
Definition at line 3384 of file TDGen.cc.
{
    writeCallSeqStart(os);
    OperationDAGSelector::OperationSet opNames;
    OperationDAGSelector::OperationSet requiredOps =
        LLVMBackend::llvmRequiredOpset(true, littleEndian_, mach_.is64bit());
    const TTAMachine::Machine::FunctionUnitNavigator fuNav =
        mach_.functionUnitNavigator();
    OperationPool opPool;
    for (int i = 0; i < fuNav.count(); i++) {
        const TTAMachine::FunctionUnit* fu = fuNav.item(i);
        for (int o = 0; o < fu->operationCount(); o++) {
            const std::string opName = fu->operation(o)->name();
            opNames.insert(StringTools::stringToUpper(opName));
        }
    }
    if (littleEndian_) {
        if (mach_.is64bit()) {
            opNames_["ST64fa"] = "ST64";
            opNames_["ST64fs"] = "ST64";
            opNames_["ST64ha"] = "ST64";
            opNames_["ST64hs"] = "ST64";
            opNames_["ST64da"] = "ST64";
            opNames_["ST64ds"] = "ST64";
            opNames_["LD64fa"] = "LD64";
            opNames_["LD64fs"] = "LD64";
            opNames_["LD64ha"] = "LD64";
            opNames_["LD64hs"] = "LD64";
            opNames_["LD64da"] = "LD64";
            opNames_["LD64ds"] = "LD64";
        }
        if (mach_.hasOperation("LD32")) {
            opNames_["LD32fr"] = "LD32";
            opNames_["LD32fi"] = "LD32";
            opNames_["LD32hr"] = "LD32";
            opNames_["LD32hi"] = "LD32";
        } else if (mach_.hasOperation("LDU32")) {
            opNames_["LD32fr"] = "LDU32";
            opNames_["LD32fi"] = "LDU32";
            opNames_["LD32hr"] = "LDU32";
            opNames_["LD32hi"] = "LDU32";
        }
        opNames_["ST32fr"] = "ST32";
        opNames_["ST32fi"] = "ST32";
        opNames_["ST32hr"] = "ST32";
        opNames_["ST32hi"] = "ST32";
        opNames_["ST16hr"] = "ST16";
        opNames_["ST16hi"] = "ST16";
    } else {
        opNames_["LDWfr"] = "LDW";
        opNames_["LDWfi"] = "LDW";
        opNames_["LDWhr"] = "LDW";
        opNames_["LDWhi"] = "LDW";
        opNames_["STWfr"] = "STW";
        opNames_["STWfi"] = "STW";
        opNames_["STWhr"] = "STW";
        opNames_["STWhi"] = "STW";
        opNames_["STHhr"] = "STH";
        opNames_["STHhi"] = "STH";
    }
    // Some global/address immediate if conversion fails
    // so commented out.
    // TODO: ^ up-to-date comment? ^
    if (hasConditionalMoves_) {
        if (mach_.is64bit()) {
            truePredOps_["MOV64ss"] = "PRED_TRUE_MOV64ss";
            falsePredOps_["MOV64ss"] = "PRED_FALSE_MOV64ss";
        }
        truePredOps_["MOVI32rr"] = "PRED_TRUE_MOVI32rr";
        falsePredOps_["MOVI32rr"] = "PRED_FALSE_MOVI32rr";
        truePredOps_["MOVI1rr"] = "PRED_TRUE_MOVI1rr";
        falsePredOps_["MOVI1rr"] = "PRED_FALSE_MOVI1rr";
    }
    OperationDAGSelector::OperationSet::const_iterator iter = opNames.begin();
    for (; iter != opNames.end(); iter++) {
        OperationDAGSelector::OperationSet::iterator r =
            requiredOps.find(*iter);
        if (r != requiredOps.end()) {
            requiredOps.erase(r);
        }
        Operation& op = opPool.operation((*iter).c_str());
        bool skipPattern = false;
        if (&op == &NullOperation::instance()) {
            continue;
        }
        // TODO: Allow multioutput (remove last or)
        if (!operationCanBeMatched(op)) {
            // TODO: write opeation def without graphs
            if (&op != &NullOperation::instance()) {
                skipPattern = true;
                if (Application::verboseLevel() > 0) {
                    Application::logStream()
                        << "Skipped writing operation pattern for "
                        << op.name() << endl;
                }
            } else {
                // NULL op - ignore
                continue;
            }
        }
        // TODO: remove this. For now MIMO operation patterns are not
        // supported by tablegen.
        if (op.numberOfOutputs() > 1) {
            skipPattern = true;
            continue;
        }
        if (op.isVectorOperation()) {
            if (isVectorLoadOperation(op) || isVectorStoreOperation(op)) {
                writeVectorMemoryOperationDefs(os, op, skipPattern);
            } else if (isVectorBitwiseOperation(op)) {
                writeVectorBitwiseOperationDefs(os, op, skipPattern);
            } else {
                writeVectorOperationDefs(os, op, skipPattern);
            }
        } else {
            writeOperationDefs(os, op, skipPattern);
        }
    }
    writeVectorRegisterMoveDefs(os);
    writeScalarToVectorDefs(os);
    writeVectorBitConversions(os);
    writeScalarOperationExploitations(os);
    writeVectorLoadStoreOperationExploitations(os);
    writeVectorTruncStoreDefs(os);
    writeVectorImmediateWriteDefs(os);
    // Call operations.
    writeControlFlowInstrDefs(os);
    // Hardware loop instructions
    writeHWLoopDef(os);
    // Emulated operations.
    for (iter = requiredOps.begin(); iter != requiredOps.end(); iter++) {
        const Operation& op = opPool.operation((*iter).c_str());
        if (&op == &NullOperation::instance()) {
            std::string msg = "Required OP '" + *iter + "' not found.";
            throw InvalidData(__FILE__, __LINE__, __func__, msg);
        }
        const OperationDAGSelector::OperationDAGList emulationDAGs =
            OperationDAGSelector::findDags(op.name(), allOpNames_, immInfo_);
        if (emulationDAGs.empty()) {
            if (Application::verboseLevel() >
                Application::VERBOSE_LEVEL_DEFAULT) {
                Application::logStream() << "Warning: Operation '" << *iter
                                         << "' not supported." << endl;
            }
        } else {
            /// @note This todo marking is from TDGenSIMD
            // TODO: write all dags of operation (first as normal, the rest
            // as pattern)
            writeEmulationPattern(os, op, emulationDAGs.smallestNodeCount());
        }
    }
    createByteExtLoadPatterns(os);
    createShortExtLoadPatterns(os);
    if (mach_.is64bit()) {
        create32BitExtLoadPatterns(os);
    }
    writeBooleanStorePatterns(os);
    writeMiscPatterns(os);
    createSelectPatterns(os);
    createConstantMaterializationPatterns(os);
    createConstShiftPatterns(os);
    createBoolAndHalfLoadPatterns(os);
}
References __func__, allOpNames_, TTAMachine::Machine::Navigator< ComponentType >::count(), create32BitExtLoadPatterns(), createBoolAndHalfLoadPatterns(), createByteExtLoadPatterns(), createConstantMaterializationPatterns(), createConstShiftPatterns(), createSelectPatterns(), createShortExtLoadPatterns(), falsePredOps_, OperationDAGSelector::findDags(), TTAMachine::Machine::functionUnitNavigator(), hasConditionalMoves_, TTAMachine::Machine::hasOperation(), immInfo_, NullOperation::instance(), TTAMachine::Machine::is64bit(), isVectorBitwiseOperation(), isVectorLoadOperation(), Operation::isVectorOperation(), isVectorStoreOperation(), TTAMachine::Machine::Navigator< ComponentType >::item(), littleEndian_, LLVMBackend::llvmRequiredOpset(), Application::logStream(), mach_, TTAMachine::HWOperation::name(), Operation::name(), Operation::numberOfOutputs(), OperationPool::operation(), TTAMachine::FunctionUnit::operation(), operationCanBeMatched(), TTAMachine::FunctionUnit::operationCount(), opNames_, OperationDAGSelector::OperationDAGList::smallestNodeCount(), StringTools::stringToUpper(), truePredOps_, Application::VERBOSE_LEVEL_DEFAULT, Application::verboseLevel(), writeBooleanStorePatterns(), writeCallSeqStart(), writeControlFlowInstrDefs(), writeEmulationPattern(), writeHWLoopDef(), writeMiscPatterns(), writeOperationDefs(), writeScalarOperationExploitations(), writeScalarToVectorDefs(), writeVectorBitConversions(), writeVectorBitwiseOperationDefs(), writeVectorImmediateWriteDefs(), writeVectorLoadStoreOperationExploitations(), writeVectorMemoryOperationDefs(), writeVectorOperationDefs(), writeVectorRegisterMoveDefs(), and writeVectorTruncStoreDefs().
Referenced by generateBackend(), and initializeBackendContents().
writeIntegerImmediateDefs()
void TDGen::writeIntegerImmediateDefs (std::ostream & o, const ImmInfo & iivs) protected
Writes unique immediate operands (ImmLeafs) for all operations that can have short immediates to transported to theirs operands.
The names of the immediate operands are stored in i32immOperandDefs_ map. Note: operations, that can not have short immediates to be trasported at all, do not entry in the map.
Parameters
o The output stream.
iivs The immediate info.
Definition at line 649 of file TDGen.cc.
{
    TCEString immDefBaseName = mach_.is64bit() ? "i64imm" : "i32imm";
    TCEString immDefType = mach_.is64bit() ? "i64" : "i32";
    int bits = mach_.is64bit() ? 64 : 32;
    using ImmBounds = std::pair<int64_t, int64_t>;
    OperationPool opPool;
    std::set<const Operation*> opset;
    for (auto& iiv : iivs) {
        const Operation& op = opPool.operation(iiv.first.first.c_str());
        if (&op == &NullOperation::instance())
            continue;
        opset.insert(&op);
    }
    std::map<ImmBounds, std::string> immediateClasses;
    int immId = 0;
    for (auto op : opset) {
        // Divide input operands into groups that can be swapped together.
        // Commutative instructions with immediate operands in the patterns
        // are defined having the immediate operands as last operands
        // (e.g. ADDrri). For these a combined ImmLeaf is created (union of
        // each of ImmLeaf of the inputs).
        std::vector<std::set<int>> inputGroups;
        for (int opdIdx = 1; opdIdx < op->numberOfInputs() + 1; opdIdx++) {
            const Operand& opd = op->operand(opdIdx);
            bool alreadyGrouped = false;
            for (auto& group : inputGroups) {
                if (group.count(opdIdx)) {
                    alreadyGrouped = true;
                    break;
                }
            }
            if (alreadyGrouped) continue;
            inputGroups.push_back(std::set<int>());
            inputGroups.back().insert(opdIdx);
            for (int otherOpdIdx : opd.swap()) {
                inputGroups.back().insert(otherOpdIdx);
            }
        }
        // For each input operand group assign an ImmLeaf operand definition.
        // The names of ImmLeaf definitions are stored in immOperandDefs_,
        // which is accessed using operation and operand as the key.
        for (auto group : inputGroups) {
            ImmBounds widestImmBound;
            for (auto idx : group) {
                // Determine max transportable immediate value range.
                if (iivs.count(*op, idx)) {
                    // perform union
                    ImmBounds immBound = iivs.immediateValueBounds(
                        *op, idx, bits);
                    widestImmBound.first = std::min(
                        widestImmBound.first, immBound.first);
                    widestImmBound.second = std::max(
                        widestImmBound.second, immBound.second);
                }
                // Can not transport immediates at all.
                if (widestImmBound == ImmBounds()) continue;
                // immediateClasses stores unique encountered immediate value
                // ranges.
                if (immediateClasses.count(widestImmBound) == 0) {
                    std::string immDefName = std::string("i32imm")
                        + Conversion::toString(immId);
                    if (!mach_.is64bit()) {
                        immediateClasses[widestImmBound] = immDefName;
                    }
                    writeImmediateDef(
                        o, immDefName, "i32", immediatePredicate(
                        widestImmBound.first, widestImmBound.second));
                    immDefName = std::string("i64imm")
                        + Conversion::toString(immId);
                    if (mach_.is64bit()) {
                        immediateClasses[widestImmBound] = immDefName;
                    }
                    writeImmediateDef(
                        o, immDefName, "i64", immediatePredicate(
                        widestImmBound.first, widestImmBound.second));
                    immId++;
                }
                immOperandDefs_[ImmInfo::key(*op, idx)] =
                    immediateClasses.at(widestImmBound);
            }
        }
    }
}
References ImmInfo::count(), immediatePredicate(), ImmInfo::immediateValueBounds(), immOperandDefs_, NullOperation::instance(), TTAMachine::Machine::is64bit(), ImmInfo::key(), mach_, OperationPool::operation(), Operand::swap(), Conversion::toString(), and writeImmediateDef().
Referenced by writeOperandDefs().
writeMiscPatterns()
void TDGen::writeMiscPatterns (std::ostream & o) protected
Definition at line 8465 of file TDGen.cc.
{
    if (!mach_.is64bit()) {
        o << "// zero extending moves used in some patterns" << std::endl
          << "def ANDext : InstTCE<(outs R32IRegs:$dst), (ins R1Regs:$src, i32imm:$val), \"\", []>;" << std::endl
          << "def PRED_TRUE_ANDext : InstTCE<(outs R32IRegs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i32imm:$val), \"\", []>;" << std::endl
          << "def PRED_FALSE_ANDext : InstTCE<(outs R32IRegs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i32imm:$val),\"\", []>;" << std::endl
          << "def XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$src, i32imm:$val), \"\", []>;" << std::endl
          << "def PRED_TRUE_XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i32imm:$val), \"\", []>;" << std::endl
          << "def PRED_FALSE_XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i32imm:$val), \"\", []>;" << std::endl;
        o << "def: Pat <(i32 (anyext R1Regs:$src)), (ANDext R1Regs:$src, 1)>;" << std::endl
          << "def: Pat <(i32 (zext R1Regs:$src)), (ANDext R1Regs:$src, 1)>;" << std::endl;
        o << "// select of 1 or 0." << std::endl
          << "def : Pat<(i32 (select R1Regs:$c, (i32 1), (i32 0))),"
          << " (ANDext R1Regs:$c, 1)>;" << std::endl;
        o << std::endl
          << "def: Pat <(i32 (sext R1Regs:$src)), (SUBrir 0,(ANDext R1Regs:$src, 1))>;"
          << std::endl;
        o << "// ------ Shift (emulation) patterns. " << std::endl
          << "def: Pat <(i32 (shl R32IRegs:$val, (i32 1))),"
          << " (ADDrrr R32Regs:$val, R32Regs:$val)>;" << std::endl
          << "def: Pat <(i32 (TCESHLConst R32IRegs:$val, (i32 1))),"
          << " (ADDrrr R32IRegs:$val, R32IRegs:$val)>;" << std::endl;
        o << "// ----- Global addresses, constant pool entries ------" << std::endl
          << "def TCEGlobalAddr : SDNode<\"TCEISD::GLOBAL_ADDR\", SDTIntUnaryOp>;" << std::endl
          << "def TCEConstPool : SDNode<\"TCEISD::CONST_POOL\", SDTIntUnaryOp>;" << std::endl
          << "def : Pat<(TCEGlobalAddr tglobaladdr:$in), (MOVI32ri tglobaladdr:$in)>;" << std::endl
          << "def : Pat<(TCEGlobalAddr tconstpool:$in), (MOVI32ri tconstpool:$in)>;" << std::endl
          << "def : Pat<(TCEConstPool tglobaladdr:$in), (MOVI32ri tglobaladdr:$in)>;" << std::endl
          << "def : Pat<(TCEConstPool tconstpool:$in), (MOVI32ri tconstpool:$in)>;" << std::endl;
        o << "// some peephole patterns." << std::endl
          << "// 1-bit select with imm values - xor or mov." << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 0), (i1 -1))), (XORbbj R1Regs:$c, 1)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 -1), (i1 0))), (MOVI1rr R1Regs:$c)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 -1), R1Regs:$F)), (IORbbb R1Regs:$c, R1Regs:$F)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$T, (i1 0))), (ANDbbb R1Regs:$c, R1Regs:$T)>;" << std::endl;
        o <<  "// 1-bit comparison between booleans - xor or xnor(implemented with 2 xors)" << std::endl
          << "def : Pat<(i1 (setne R1Regs:$op1, R1Regs:$op2)), (XORbbb R1Regs:$op1, R1Regs:$op2)>;" << std::endl
          << "// TODO: should the temp values be converted to i32? usually more i32 regs." << std::endl
          << "def : Pat<(i1 (seteq R1Regs:$op1, R1Regs:$op2)), (XORbbj (XORbbb R1Regs:$op1, R1Regs:$op2), 1)>;" << std::endl;
        o << "def TCEBlockAddress : SDNode<\"TCEISD::BLOCK_ADDR\", SDTIntUnaryOp>;" << std::endl
          << "def : Pat<(TCEBlockAddress tblockaddress:$src1), (MOVI32ri tblockaddress:$src1)>;" << std::endl;
    } else {
        o << "// zero extending moves used in some patterns" << std::endl
          << "def ANDext : InstTCE<(outs R64IRegs:$dst),"
          << " (ins R1Regs:$src, i64imm:$val), \"\", []>;" << std::endl
          << "def PRED_TRUE_ANDext : InstTCE<(outs R64IRegs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i64imm:$val), \"\", []>;" << std::endl
          << "def PRED_FALSE_ANDext : InstTCE<(outs R64IRegs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i64imm:$val),\"\", []>;" << std::endl
          << "def XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$src, i64imm:$val), \"\", []>;" << std::endl
          << "def PRED_TRUE_XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i64imm:$val), \"\", []>;" << std::endl
          << "def PRED_FALSE_XORbicmp: InstTCE<(outs R1Regs:$dst),"
          << " (ins R1Regs:$pred, R1Regs:$src, i64imm:$val), \"\", []>;" << std::endl;
        o << "def: Pat <(i64 (anyext R1Regs:$src)), (ANDext R1Regs:$src, 1)>;" << std::endl
          << "def: Pat <(i64 (zext R1Regs:$src)), (ANDext R1Regs:$src, 1)>;" << std::endl;
        o << "// select of 1 or 0." << std::endl
          << "def : Pat<(i64 (select R1Regs:$c, (i64 1), (i64 0))), (ANDext R1Regs:$c, 1)>;" << std::endl;
        o << std::endl
          << "def: Pat <(i64 (sext R1Regs:$src)), (SUB64sas 0,(ANDext R1Regs:$src, 1))>;"
          << std::endl;
        o << "// ------ Shift (emulation) patterns. " << std::endl
          << "def: Pat <(i64 (shl R64IRegs:$val, (i64 1))),"
          << " (ADD64sss R64Regs:$val, R64Regs:$val)>;" << std::endl
          << "def: Pat <(i64 (TCESHLConst R64IRegs:$val, (i64 1))),"
          << " (ADD64sss R64IRegs:$val, R64IRegs:$val)>;" << std::endl;
        o << "// ----- Global addresses, constant pool entries ------" << std::endl
          << "def TCEGlobalAddr : SDNode<\"TCEISD::GLOBAL_ADDR\", SDTIntUnaryOp>;" << std::endl
          << "def TCEConstPool : SDNode<\"TCEISD::CONST_POOL\", SDTIntUnaryOp>;" << std::endl
          << "def : Pat<(TCEGlobalAddr tglobaladdr:$in), (MOVI64sa tglobaladdr:$in)>;" << std::endl
          << "def : Pat<(TCEGlobalAddr tconstpool:$in), (MOVI64sa tconstpool:$in)>;" << std::endl
          << "def : Pat<(TCEConstPool tglobaladdr:$in), (MOVI64sa tglobaladdr:$in)>;" << std::endl
          << "def : Pat<(TCEConstPool tconstpool:$in), (MOVI64sa tconstpool:$in)>;" << std::endl;
        o << "// some peephole patterns." << std::endl
          << "// 1-bit select with imm values - xor or mov." << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 0), (i1 -1))), (XOR64bbj R1Regs:$c, 1)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 -1), (i1 0))), (MOVI1rr R1Regs:$c)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, (i1 -1), R1Regs:$F)), (IOR64bbb R1Regs:$c, R1Regs:$F)>;" << std::endl
          << "def : Pat<(i1 (select R1Regs:$c, R1Regs:$T, (i1 0))), (AND64bbb R1Regs:$c, R1Regs:$T)>;" << std::endl;
        o <<  "// 1-bit comparison between booleans - xor or xnor(implemented with 2 xors)" << std::endl
          << "def : Pat<(i1 (setne R1Regs:$op1, R1Regs:$op2)), (XOR64bbb R1Regs:$op1, R1Regs:$op2)>;" << std::endl
          << "// TODO: should the temp values be converted to i64? usually more i64 regs." << std::endl
          << "def : Pat<(i1 (seteq R1Regs:$op1, R1Regs:$op2)), (XOR64bbj (XOR64bbb R1Regs:$op1, R1Regs:$op2), 1)>;" << std::endl;
        o << "def TCEBlockAddress : SDNode<\"TCEISD::BLOCK_ADDR\", SDTIntUnaryOp>;" << std::endl
          << "def : Pat<(TCEBlockAddress tblockaddress:$src1), (MOVI64sa tblockaddress:$src1)>;" << std::endl;
    }
}
References TTAMachine::Machine::is64bit(), and mach_.
Referenced by writeInstrInfo().
writeMoveImmediateDefs()
void TDGen::writeMoveImmediateDefs (std::ostream & o) protected
Writes immediate operand definitions that are used for MOV instructions.
Creates immediate operand definitions for immediate to register instructions (MOVI), that only accept supported immediate values.
Note
Implemented currently only for i32 registers.
Definition at line 756 of file TDGen.cc.
{
    using MCC = MachineConnectivityCheck;
    TCEString immDefBaseName = mach_.is64bit() ? "i64imm" : "i32imm";
    TCEString immDefType = mach_.is64bit() ? "i64" : "i32";
    int bits = mach_.is64bit() ? 64 : 32;
    std::pair<int64_t, uint64_t> moveImm{ 0, 0 };
    for (auto& rf : mach_.registerFileNavigator()) {
        if (rf->width() != bits) continue;
        for (auto& bus : mach_.busNavigator()) {
            if (!MCC::busConnectedToRF(*bus, *rf)
                || bus->immediateWidth() == 0) {
                continue;
            }
            if (bus->immediateWidth() >= bits) {
                moveImm.first = -(1ll << (bits-1));
                moveImm.second = (1ll << bits)-1;
                break;
            } else {
                std::pair<int64_t, uint64_t> imm =
                    MathTools::bitsToIntegerRange<int64_t, uint64_t>(
                        bus->immediateWidth(),
                        bus->signExtends());
                moveImm.first = std::min(moveImm.first, imm.first);
                moveImm.second = std::max(moveImm.second, imm.second);
            }
        }
    }
    for (auto& iu : mach_.immediateUnitNavigator()) {
        for (auto& it : mach_.instructionTemplateNavigator()) {
            int supportedWidth = it->supportedWidth(*iu);
            if (supportedWidth >= bits) {
                moveImm.first = -(1ll << (bits-1));
                moveImm.second = (1ll << bits)-1;
                break;
            } else {
                std::pair<int64_t, uint64_t> imm =
                    MathTools::bitsToIntegerRange<int64_t, uint64_t>(
                        supportedWidth, iu->signExtends());
                moveImm.first = std::min(moveImm.first, imm.first);
                moveImm.second = std::max(moveImm.second, imm.second);
            }
        }
    }
    writeImmediateDef(o, "i32MoveImm", "i32", immediatePredicate(
                          moveImm.first, moveImm.second));
    writeImmediateDef(o, "i64MoveImm", "i64", immediatePredicate(
                          moveImm.first, moveImm.second));
}
References TTAMachine::Machine::busNavigator(), immediatePredicate(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::is64bit(), mach_, TTAMachine::Machine::registerFileNavigator(), and writeImmediateDef().
Referenced by writeOperandDefs().
writeOperandDefs()
void TDGen::writeOperandDefs (std::ostream & o) protected
Writes all short immediate definitions to the stream.
Parameters
o The output stream.
Definition at line 621 of file TDGen.cc.
{
    assert(immInfo_ != nullptr
        && "Short immediate analysis results are not available!");
    o << "// Immediate definitions for TCE instructions." << std::endl;
    writeIntegerImmediateDefs(o, *immInfo_);
    o << std::endl;
    o << "// Immediate definitions for immediate to register moves."
      << std::endl;
    writeMoveImmediateDefs(o);
    o << std::endl;
}
References assert, immInfo_, writeIntegerImmediateDefs(), and writeMoveImmediateDefs().
Referenced by initializeBackendContents().
writeOperationDef()
void TDGen::writeOperationDef (std::ostream & o, Operation & op, const std::string & operandTypes, const std::string & attrs, bool skipPattern, std::string backendPrefix = "") protected
Writes a single operation def for single operation.
Parameters
o Output stream to write the definition to.
op Operation to write definition for.
operandTypes value types of operands.
Definition at line 4649 of file TDGen.cc.
{
    assert (operandTypes.size() > 0);
    // Skip definition if the operation has immediate to operand which the
    // machine can not transport short immediates to.
    if (!areImmediateOperandsLegal(op, operandTypes)) {
        if (Application::verboseLevel() >
        Application::VERBOSE_LEVEL_DEFAULT) {
            Application::logStream()
                << "Skipped writing operation pattern for: "
                << op.name() + operandTypes
                << ": Can not have immediate operand."
                << std::endl;
        }
        return;
    }
    char operandChar = mach_.is64bit() ? OT_REG_LONG : OT_REG_INT;
    std::string outputs, inputs, asmstr, pattern;
    outputs = "(outs" + patOutputs(op, operandTypes) + ")";
    inputs = "(ins " + patInputs(op, operandTypes) + ")";
    std::string predicatedInputs =
    "(ins GuardRegs:$pred, " +patInputs(op, operandTypes)+ ")";
    asmstr = "\"\"";
    if (!skipPattern) {
        if (llvmOperationPattern(op, operandChar) != "" ||
            op.dagCount() == 0) {
            OperationDAG* trivial = createTrivialDAG(op);
            pattern = operationPattern(op, *trivial, operandTypes);
            delete trivial;
        } else {
            auto* dagToUse = getMatchableOperationDAG(op);
            if (dagToUse)
                pattern = operationPattern(op, *dagToUse, operandTypes);
        }
    }
    if (attrs != "") {
        o << "let" << attrs << " in { " << std::endl;
    }
    std::string opcEnum =
        StringTools::stringToUpper(op.name()) + operandTypes;
    o << "def " << opcEnum << " : "
      << "InstTCE<"
      << outputs << ", "
      << inputs << ", "
      << asmstr << ", " ;
    if(operandTypes[0] == 'b') { //instruction can be used for comparison
    o  << "[" << pattern << "]>"
       << std::endl
       << "{ let isCompare = 1;}" << std::endl;
    } else {
    o  << "[" << pattern << "]>;"
       << std::endl;
    }
    bool opCanBePredicated = canBePredicated(op, operandTypes);
    if (opCanBePredicated) {
        // write predicated versions
        o << "def PRED_TRUE_" << opcEnum << " : "
          << "InstTCE<"
          << outputs << ", "
          << predicatedInputs << ", "
          << asmstr << ", "
          << "[]>;"
          << std::endl;
        // write predicated versions
        o << "def PRED_FALSE_" << opcEnum << " : "
          << "InstTCE<"
          << outputs << ", "
          << predicatedInputs << ", "
          << asmstr << ", "
          << "[]>;"
          << std::endl;
    }
    if (attrs != "") {
        o << "}" << std::endl;
    }
    opNames_[opcEnum] = backendPrefix + op.name();
    if (opCanBePredicated) {
        opNames_["PRED_TRUE_" + opcEnum] = "?" + backendPrefix + op.name();
        opNames_["PRED_FALSE_" + opcEnum] = "!" + backendPrefix + op.name();
        truePredOps_[opcEnum] = "PRED_TRUE_" + opcEnum;
        falsePredOps_[opcEnum] = "PRED_FALSE_" + opcEnum;
    }
}
References areImmediateOperandsLegal(), assert, canBePredicated(), createTrivialDAG(), Operation::dagCount(), falsePredOps_, getMatchableOperationDAG(), TTAMachine::Machine::is64bit(), llvmOperationPattern(), Application::logStream(), mach_, Operation::name(), operandChar(), operationPattern(), opNames_, OT_REG_INT, OT_REG_LONG, patInputs(), patOutputs(), StringTools::stringToUpper(), truePredOps_, Application::VERBOSE_LEVEL_DEFAULT, and Application::verboseLevel().
Referenced by writeOperationDefs(), writeOperationDefs(), and writeVectorOperationDef().
writeOperationDefs() [1/2]
void TDGen::writeOperationDefs (std::ostream & o, Operation & op, bool skipPattern) protected
Writes scalar operation definition(s).
Parameters
o Output stream to write the definition to.
op Operation to write definition for.
skipPattern True, if skip pattern generation.
Note
This todo marking is from TDGen.
This todo marking is from TDGen.
Definition at line 4312 of file TDGen.cc.
                      {
    std::string attrs;
    // These white listed operations have mayLoad/mayStore flag
    // inferred from the llvm pattern and declaring it
    // explicitly will display warning in tablegen.
    if (op.name() != "LDQ" && op.name() != "LDQU" &&
        op.name() != "LDH" && op.name() != "LDHU" &&
        op.name() != "LDW" && op.name() != "LDD" &&
        op.name() != "STQ" && op.name() != "STH" &&
        op.name() != "STW" && op.name() != "STD" &&
        op.name() != "ALDQ" && op.name() != "ALDQU" &&
        op.name() != "ALDH" && op.name() != "ALDHU" &&
        op.name() != "ALDW" && op.name() != "ALDD" &&
        op.name() != "ASTQ" && op.name() != "ASTH" &&
        op.name() != "ASTW" && op.name() != "ASTD" &&
        op.name() != "LD8" && op.name() != "LDU8" &&
        op.name() != "LD16" && op.name() != "LDU16" &&
        op.name() != "LD32" && op.name() != "LDU32" &&
        op.name() != "LD64" &&
        op.name() != "ST8" && op.name() != "ST16" &&
        op.name() != "ST32" && op.name() != "ST64" &&
        op.name() != "ALD8" && op.name() != "ALDU8" &&
        op.name() != "ALD16" && op.name() != "ALDU16" &&
        op.name() != "ALD32" && op.name() != "ALDU32" &&
        op.name() != "ALD64" &&
        op.name() != "AST8" && op.name() != "AST16" &&
        op.name() != "AST32" && op.name() != "AST64" &&
        op.name() != "CAS") {
        if (op.readsMemory()) attrs += " mayLoad = 1";
        if (op.readsMemory() && op.writesMemory()) attrs += ", ";
        if (op.writesMemory()) attrs += " mayStore = 1";
    }
    // no bool outs for some operatios
    if (op.name() == "CFI" || op.name() == "CFIU") {
        writeOperationDef(o, op, "rf", attrs, skipPattern);
        return;
    }
    if (op.name() == "CDL" || op.name() == "CDLU") {
        writeOperationDef(o, op, "sd", attrs, skipPattern);
        return;
    }
    if (op.name() == "CLD" || op.name() == "CLDU") {
        writeOperationDef(o, op, "ds", attrs, skipPattern);
        return;
    }
        // no bool outs for some operatios
    if (op.name() == "CFD") {
        writeOperationDef(o, op, "df", attrs, skipPattern);
        return;
    }
    // no bool outs for some operatios
    if (op.name() == "CDF") {
        writeOperationDef(o, op, "fd", attrs, skipPattern);
        return;
    }
    // rotations are allways n x n -> n bits.
    if (op.name() == "ROTL" || op.name() == "ROTR" ||
        op.name() == "SHL" || op.name() == "SHR" || op.name() == "SHRU") {
        writeOperationDefs(o, op, "rrr", attrs, skipPattern);
        return;
    }
    if (op.name() == "SXHW" || op.name() == "SXQW") {
        writeOperationDef(o, op, "rr", attrs, skipPattern);
        return;
    }
    if (op.name() == "SXW64" || op.name() == "ZXW64") {
        writeOperationDef(o, op, "ss", attrs, skipPattern);
        return;
    }
    // these can have 1-bit inputs
    // TODO: this is lacking some 64-bit ops??
    if (op.name() == "XOR" || op.name() == "IOR" || op.name() == "AND" ||
        op.name() == "ANDN" || op.name() == "ADD" || op.name() == "SUB" ||
        op.name() == "XOR64" || op.name() == "IOR64" || op.name() == "AND64") {
        writeOperationDefs(o, op, "bbb", attrs, skipPattern);
    }
    if (op.name() == "SELECT") {
        if (!hasConditionalMoves_) {
            writeOperationDef(o, op, "rrrb", attrs, skipPattern);
            writeOperationDef(o, op, "riib", attrs, skipPattern);
            writeOperationDef(o, op, "rrib", attrs, skipPattern);
            writeOperationDef(o, op, "rirb", attrs, skipPattern);
            writeOperationDef(o, op, "bbbb", attrs, skipPattern);
            writeOperationDef(o, op, "bjjb", attrs, skipPattern);
            writeOperationDef(o, op, "bjbb", attrs, skipPattern);
            writeOperationDef(o, op, "bbjb", attrs, skipPattern);
            // TODO: what about floating-point values?
            writeOperationDef(o, op, "fffb", attrs, skipPattern);
            writeOperationDef(o, op, "hhhb", attrs, skipPattern);
            // ADFs with boolan values in GPRs
            writeOperationDef(o, op, "rrrr", attrs, skipPattern);
            writeOperationDef(o, op, "riir", attrs, skipPattern);
            writeOperationDef(o, op, "rrir", attrs, skipPattern);
            writeOperationDef(o, op, "rirr", attrs, skipPattern);
            writeOperationDef(o, op, "bbbr", attrs, skipPattern);
            writeOperationDef(o, op, "bjjr", attrs, skipPattern);
            writeOperationDef(o, op, "bjbr", attrs, skipPattern);
            writeOperationDef(o, op, "bbjr", attrs, skipPattern);
            // TODO: what about floating-point values?
            writeOperationDef(o, op, "fffr", attrs, skipPattern);
            writeOperationDef(o, op, "hhhr", attrs, skipPattern);
            hasSelect_ = true;
            return;
        } else {
            std::cerr << "The target architecture has both"
                      << "conditional moves and select instruction."
                      << "Ignoring select and using conditional moves instead"
                      <<  std::endl;
            return;
        }
    }
    // store likes this. store immediate to immediate address
    if (op.numberOfInputs() == 2 && op.numberOfOutputs() == 0) {
        Operand& operand1 = op.operand(1);
        Operand& operand2 = op.operand(2);
        /// @note This todo marking is from TDGen.
        // TODO: add an else branch here for float immediates
        if ((operand1.type() == Operand::UINT_WORD ||
             operand1.type() == Operand::SINT_WORD ||
             operand1.type() == Operand::RAW_DATA) &&
           (operand2.type() == Operand::UINT_WORD ||
            operand2.type() == Operand::SINT_WORD ||
            operand2.type() == Operand::RAW_DATA)) {
            if (mach_.is64bit()) {
                writeOperationDef(o, op, "aa", attrs, skipPattern);
            } else {
                writeOperationDef(o, op, "ii", attrs, skipPattern);
            }
        }
    }
    std::string operandTypes = createDefaultOperandTypeString(op);
    // this the ordinary def
    // then try with immediates.
    /// @note This todo marking is from TDGen.
    // TODO: this should be 2^n loop instead of n loop, to get
    // all permutations.
    writeOperationDefs(o, op, operandTypes, attrs, skipPattern);
    // then with boolean outs, and vector versions.
    if (op.numberOfOutputs() == 1 && !op.readsMemory()) {
        Operand& outOperand = op.operand(op.numberOfInputs()+1);
        if (outOperand.type() == Operand::UINT_WORD ||
            outOperand.type() == Operand::SINT_WORD ||
            outOperand.type() == Operand::ULONG_WORD ||
            outOperand.type() == Operand::SLONG_WORD) {
            // 32/64 to 1-bit operations
            operandTypes[0] = OT_REG_BOOL;
            writeOperationDefs(o, op, operandTypes, attrs, skipPattern);
        }
        // create vector versions.
    }
}
References createDefaultOperandTypeString(), hasConditionalMoves_, hasSelect_, TTAMachine::Machine::is64bit(), mach_, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), OT_REG_BOOL, Operand::RAW_DATA, Operation::readsMemory(), Operand::SINT_WORD, Operand::SLONG_WORD, Operand::type(), Operand::UINT_WORD, Operand::ULONG_WORD, writeOperationDef(), writeOperationDefs(), and Operation::writesMemory().
Referenced by writeInstrInfo(), and writeOperationDefs().
writeOperationDefs() [2/2]
void TDGen::writeOperationDefs (std::ostream & o, Operation & op, const std::string & operandTypes, const std::string & attrs, bool skipPattern, std::string backendPrefix = "") protected
Writes operation defs for single operation, with different immediate params.
Parameters
o Output stream to write the definition to.
op Operation to write definition for.
operandTypes value types of operands.
Definition at line 4516 of file TDGen.cc.
{
    // first without imms.
    writeOperationDef(o, op, operandTypes, attrs, skipPattern, backendPrefix);
    for (int i = 0; i < op.numberOfInputs(); i++) {
        bool canSwap = false;
        // those ops SHOULD be can-swap but are not. kludge-fix.
        // consider making them can-swap.
        if (op.name() == "ALDQ" || op.name() == "ALDQU" ||
            op.name() == "ALDH" || op.name() == "ALDHU" ||
            op.name() == "ALDW" || op.name() == "ALDD" ||
            op.name() == "ASTQ" || op.name() == "ASTH" ||
            op.name() == "ASTW" || op.name() == "ASTD" ||
            op.name() == "ALD8" || op.name() == "ALDU8" ||
            op.name() == "ALD16"|| op.name() == "ALDU16" ||
            op.name() == "ALD32"|| op.name() == "ALD64" ||
            op.name() == "AST8" || op.name() == "AST16" ||
            op.name() == "AST32"|| op.name() == "AST64") {
            canSwap = true;
        }
        for (int j = i+1 ; j < op.numberOfInputs(); j++) {
            if (op.canSwap(i+1, j+1)) {
                canSwap = true;
                break;
            }
        }
        // setcc of LLVM is not commutative and get confused if we don't generate
        // a pattern with immediate elsewhere than the last operand
        canSwap = canSwap && !(op.name().upper() == "EQ" || op.name().upper() == "NE");
        if (!canSwap) {
            std::string opTypes = operandTypes;
            char& c = opTypes[i + op.numberOfOutputs()];
            c = regOperandCharToImmOperandChar(c);
            if (c) {
                writeOperationDef(o, op, opTypes, attrs, skipPattern, backendPrefix);
            }
        }
    }
}
References Operation::canSwap(), Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), regOperandCharToImmOperandChar(), TCEString::upper(), and writeOperationDef().
writeOperationDefUsingGivenOperandTypes()
void TDGen::writeOperationDefUsingGivenOperandTypes (std::ostream & o, Operation & op, bool skipPattern, std::vector< TDGenerator::ValueType > inputs, std::vector< TDGenerator::ValueType > outputs, TCEString instrSuffix = "") protected
Writes operation definition using given operand types.
Changes the operands to match the provided ones, after which a definition is written. Finally, original operands are restored.
Parameters
o Output stream.
op Operation used to create new operation definitions.
skipPattern If true, operation pattern writing is skipped.
inputs Input operand types for the new operation.
outputs Output operand types for the new operation.
instrSuffix Optional suffix that will be added to instruction name.
Definition at line 1896 of file TDGen.cc.
{
    assert(
        inputs.size() == static_cast<size_t>(op.numberOfInputs()) &&
        "Given input operand count doesn't match operation's count.");
    assert(
        outputs.size() == static_cast<size_t>(op.numberOfOutputs()) &&
        "Given output operand count doesn't match operation's count.");
    std::vector<ValueType> oldInputs;
    std::vector<ValueType> oldOutputs;
    // Change operands to match the provided ones.
    for (int i = 0; i < op.numberOfInputs(); ++i) {
        Operand& input = op.input(i);
        oldInputs.push_back(ValueType(input));
        ValueType vt = inputs[i];
        input.setType(vt.operandType());
        input.setElementWidth(vt.subwWidth_);
        input.setElementCount(vt.subwCount_);
    }
    for (int i = 0; i < op.numberOfOutputs(); ++i) {
        Operand& output = op.output(i);
        oldOutputs.push_back(ValueType(output));
        ValueType vt = outputs[i];
        output.setType(vt.operandType());
        output.setElementWidth(vt.subwWidth_);
        output.setElementCount(vt.subwCount_);
    }
    // Write new operation definition.
    TCEString types = createDefaultOperandTypeString(op) + instrSuffix;
    writeVectorOperationDef(o, op, types, "", skipPattern);
    // Restore old operands.
    for (int i = 0; i < op.numberOfInputs(); ++i) {
        Operand& input = op.input(i);
        ValueType vt = oldInputs[i];
        input.setType(vt.operandType());
        input.setElementWidth(vt.subwWidth_);
        input.setElementCount(vt.subwCount_);
    }
    for (int i = 0; i < op.numberOfOutputs(); ++i) {
        Operand& output = op.output(i);
        ValueType vt = oldOutputs[i];
        output.setType(vt.operandType());
        output.setElementWidth(vt.subwWidth_);
        output.setElementCount(vt.subwCount_);
    }
}
References assert, createDefaultOperandTypeString(), Operation::input(), Operation::numberOfInputs(), Operation::numberOfOutputs(), TDGenerator::ValueType::operandType(), Operation::output(), Operand::setElementCount(), Operand::setElementWidth(), Operand::setType(), TDGenerator::ValueType::subwCount_, TDGenerator::ValueType::subwWidth_, and writeVectorOperationDef().
Referenced by writeScalarOperationExploitations(), writeVectorBitwiseOperationDefs(), and writeVectorLoadStoreOperationExploitations().
writePatternReplacement()
void TDGen::writePatternReplacement (std::ostream & o, const TCEString & origPat, const TCEString & replacerPat) const protected
Writes a pattern fragment definition.
Parameters
origPat Pattern that instruction selector should replace.
replacerPat Pattern that will replace the original pattern.
Definition at line 1875 of file TDGen.cc.
{
    o << "def : Pat<(" << origPat << "), (" << replacerPat << ")>;" << endl;
}
Referenced by writeScalarToVectorDefs(), writeVectorBitConversions(), and writeVectorTruncStoreDefs().
writePortGuardedJumpDefPair()
bool TDGen::writePortGuardedJumpDefPair (std::ostream & os, const TCEString & tceop1, const TCEString & tceop2, bool fp = false) protected
Definition at line 3897 of file TDGen.cc.
{
    TCEString llvmop1 = TDGen::llvmOperationName(tceop1).upper();
    TCEString llvmop2 = TDGen::llvmOperationName(tceop2).upper();
    TCEString regclass = fp ? "R32FPRegs" : "R32IRegs";
    if (MachineInfo::supportsPortGuardedJump(mach_, false, tceop1) ||
        MachineInfo::supportsPortGuardedJump(mach_, true, tceop2)) {
        os << std::endl << "let isTerminator = 1, isBranch = 1 in {" << std::endl;
        writeInstrDef(os, tceop1+"_JUMP", "",
                      regclass + ":$cmp1, "+ regclass + ":$cmp2, brtarget:$dst", "",
                      "(brcc "+ llvmop1 +", "+ regclass + ":$cmp1, " + regclass + ":$cmp2, bb:$dst)");
        os << "}" << std::endl;
        if (MachineInfo::supportsPortGuardedJump(mach_, false, tceop1)) {
            opNames_[tceop1 + "_JUMP"] = tceop1 + "+?jump";
        } else {
            opNames_[tceop1 + "_JUMP"] = tceop2 + "+!jump";
        }
    } else {
        std::cerr << "Missing "<< tceop1 << " operation as true-guard source"
                  << " or " << tceop2 << " operation as invarted guard source to jump." << std::endl;
        return false;
    }
    if (MachineInfo::supportsPortGuardedJump(mach_, true, tceop1) ||
        MachineInfo::supportsPortGuardedJump(mach_, false, tceop2)) {
        os << std::endl << "let isTerminator = 1, isBranch = 1 in {" << std::endl;
        writeInstrDef(os, tceop2+"_JUMP", "",
                      regclass + ":$cmp1, "+ regclass + ":$cmp2, brtarget:$dst", "",
                      "(brcc "+ llvmop2 +", "+ regclass + ":$cmp1, " + regclass + ":$cmp2, bb:$dst)");
        os << "}" << std::endl;
        if (MachineInfo::supportsPortGuardedJump(mach_, false, tceop2)) {
            opNames_[tceop2 + "_JUMP"] = tceop2 + "+?jump";
        } else {
            opNames_[tceop2 + "_JUMP"] = tceop1 + "+!jump";
        }
    } else {
        std::cerr << "Missing " << tceop2 << " operation as true-guard source"
                  << " or " << tceop1 << " operation as inverted guard source to jump."
                  << std::endl;
        return false;
    }
    return true;
}
References llvmOperationName(), mach_, opNames_, MachineInfo::supportsPortGuardedJump(), TCEString::upper(), and writeInstrDef().
Referenced by writeCondBranchDefs().
writeRARegisterInfo()
void TDGen::writeRARegisterInfo (std::ostream & o) protected
Writes return address register definition to the output stream.
Definition at line 3157 of file TDGen.cc.
{
    o << "class Rra<string n> : TCEReg<n, []>;" << std::endl;
    o << "def RA : Rra<\"return-address\">, ";
    o << "DwarfRegNum<[" << dregNum_++ << "]>;";
    o << std::endl;
    if (mach_.is64bit()) {
        o << "def RAReg : RegisterClass<\"TCE\", [i64], 64, (add RA)>;" <<
            std::endl;
    } else {
        o << "def RAReg : RegisterClass<\"TCE\", [i32], 32, (add RA)>;" <<
            std::endl;
    }
}
References dregNum_, TTAMachine::Machine::is64bit(), and mach_.
Referenced by writeRegisterInfo().
writeRegisterClasses()
void TDGen::writeRegisterClasses (std::ostream & o) protected
Definition at line 816 of file TDGen.cc.
{
    o << "class R1<string n, list<Register> aliases> : TCEReg<n, aliases> {"
      << "}" << std::endl;
    o << "class R32<string n, list<Register> aliases> : TCEReg<n, aliases> {"
      << "}" << std::endl;
    o << "class R64<string n, list<Register> aliases> : TCEReg<n, aliases> {"
      << "}" << std::endl;
    o << "class R16<string n, list<Register> aliases> : TCEReg<n, aliases> {"
      << "}" << std::endl;
}
Referenced by writeRegisterInfo().
writeRegisterDef()
void TDGen::writeRegisterDef (std::ostream & o, const RegInfo & reg, const std::string regName, const std::string regTemplate, const std::string aliases, RegType type) protected
Writes .td definition of a single register to the output stream.
Parameters
o Output stream to write the definition to.
reg Information about the physical register.
regName Name for the register in the llvm framework.
regTemplate Base class for the register.
aliases Comma-separated list of aliases for this register.
Definition at line 503 of file TDGen.cc.
                  {
    std::string templ = regTemplate;
    o << "def " << regName << " : " << templ
      << "<\"" << reg.rf << "." << reg.idx
      << "\", [" << aliases << "]>, DwarfRegNum<"
      << "[" << dregNum_ << "]>;"
      << std::endl;
    if (type == GPR) {
        gprRegNames_.push_back(regName);
    } else if (type == ARGUMENT) {
        argRegNames_.push_back(regName);
    } else if (type == RESULT) {
        argRegNames_.push_back(regName);
        resRegNames_.push_back(regName);
    } else {
        assert(type == RESERVED);
    }
    regs_[regName] = reg;
    regsInClasses_[regTemplate].push_back(regName);
    if (guardedRegs_.find(reg) != guardedRegs_.end()) {
        llvmGuardRegs_.push_back(regName);
        regsInClasses_[guardRegTemplateName].push_back(regName);
    }
    dregNum_++;
}
References argRegNames_, ARGUMENT, assert, dregNum_, GPR, gprRegNames_, guardedRegs_, guardRegTemplateName, TDGen::RegInfo::idx, llvmGuardRegs_, regs_, regsInClasses_, RESERVED, resRegNames_, RESULT, and TDGen::RegInfo::rf.
Referenced by write16bitRegisterInfo(), write1bitRegisterInfo(), write32bitRegisterInfo(), write64bitRegisterInfo(), writeGuardRegisterClassInfo(), and writeVectorRegisterNames().
writeRegisterInfo()
bool TDGen::writeRegisterInfo (std::ostream & o) protected
Writes .td definitions of all registers in the machine to an output stream.
Parameters
o Output stream for the .td definitions.
Returns
True, if the definitions were succesfully generated.
Definition at line 551 of file TDGen.cc.
{
    analyzeRegisters();
    if (!checkRequiredRegisters()) {
        return false;
    }
    assert(regs32bit_.size() >= requiredI32Regs_);
    // Write scalar register information without old vector backend registers.
    writeStartOfRegisterInfo(o);
    writeRegisterClasses(o);
    writeRARegisterInfo(o);
    write1bitRegisterInfo(o);
//    write16bitRegisterInfo(o); // currently not supported properly
    write32bitRegisterInfo(o);
    write64bitRegisterInfo(o);
    // Gather and separate all operations to vector and scalar containers.
    gatherAllMachineOperations();
    // Create register classes for vector operands.
    analyzeMachineVectorRegisterClasses();
    // Group registers by width.
    analyzeMachineRegisters();
    // Associate register groups properly with register classes.
    associateRegistersWithVectorRegisterClasses();
    // Write register related information to the .td file.
    writeVectorRegisterBaseClasses(o);
    writeVectorRegisterNames(o);
    writeVectorRegisterClasses(o);
    writeGuardRegisterClassInfo(o);
    return true;
}
References analyzeMachineRegisters(), analyzeMachineVectorRegisterClasses(), analyzeRegisters(), assert, associateRegistersWithVectorRegisterClasses(), checkRequiredRegisters(), gatherAllMachineOperations(), regs32bit_, requiredI32Regs_, write1bitRegisterInfo(), write32bitRegisterInfo(), write64bitRegisterInfo(), writeGuardRegisterClassInfo(), writeRARegisterInfo(), writeRegisterClasses(), writeStartOfRegisterInfo(), writeVectorRegisterBaseClasses(), writeVectorRegisterClasses(), and writeVectorRegisterNames().
Referenced by initializeBackendContents().
writeScalarOperationExploitations()
void TDGen::writeScalarOperationExploitations (std::ostream & o) protected
This function writes scalar operation exploitations.
Some scalar operations can be exploited to execute vector operations. For instance, bitwise logical operations are same for any operand width. A 32-bit scalar XOR operation can execute bitwise exclusive OR operation for v32i1, v4i8 and v2i16 vector operands similarly as it does for i32 type.
Definition at line 2475 of file TDGen.cc.
{
    o << endl
      << endl
      << "// Scalar operations exploited to execute small vector operations."
      << endl;
    // Use minimal architecture NOT/AND/IOR/XOR 32-bit operations to execute
    // bitwise vector operations with operands of 32 bits or lower width.
    OperationPool opPool;
    std::vector<Operation*> scalarBitwiseOps;
    scalarBitwiseOps.push_back(&opPool.operation("NOT"));
    scalarBitwiseOps.push_back(&opPool.operation("AND"));
    scalarBitwiseOps.push_back(&opPool.operation("IOR"));
    scalarBitwiseOps.push_back(&opPool.operation("XOR"));
    scalarBitwiseOps.push_back(&opPool.operation("NOT64"));
    scalarBitwiseOps.push_back(&opPool.operation("AND64"));
    scalarBitwiseOps.push_back(&opPool.operation("IOR64"));
    scalarBitwiseOps.push_back(&opPool.operation("XOR64"));
    for (size_t opI = 0; opI < scalarBitwiseOps.size(); ++opI) {
        Operation& op = *scalarBitwiseOps[opI];
        if (&op == &NullOperation::instance() ||
            !mach_.hasOperation(op.name())) {
            continue;
        }
        int width = 2;
        while (width <= op.output(0).width()) {
            // Get vector value types for the current width, e.g v4i8, v2i16
            // and v32i1 value types for width 32.
            std::vector<ValueType> intVecVts =
                ValueType::vectorTypesOfWidth(width, true);
            for (size_t i = 0; i < intVecVts.size(); ++i) {
                ValueType& vecVt = intVecVts[i];
                const TCEString vecVtStr = vecVt.valueTypeStr();
                if (hasRegisterClassSupport(vecVt)) {
                    std::vector<ValueType> inputs;
                    std::vector<ValueType> outputs;
                    for (int i = 0; i < op.numberOfInputs(); ++i) {
                        inputs.push_back(vecVt);
                    }
                    for (int i = 0; i < op.numberOfOutputs(); ++i) {
                        outputs.push_back(vecVt);
                    }
                    writeOperationDefUsingGivenOperandTypes(
                        o, op, false, inputs, outputs, vecVtStr);
                }
            }
            width *= 2;
        }
    }
    // Use LDQ/LDH/LDW and STQ/STH/STW operations to create memory access
    // operations for vector operands of 32-bit or lower width.
    int memDataOpndWidth = 2;
    const char* defaultType = mach_.is64bit() ? "i64" : "i32";
    while (memDataOpndWidth <= MAX_SCALAR_WIDTH) {
        std::vector<ValueType> vecVts =
            ValueType::vectorTypesOfWidth(memDataOpndWidth);
        for (size_t i = 0; i < vecVts.size(); ++i) {
            const ValueType& dataOpndVt = vecVts[i];
            const TCEString dataOpndVtStr = dataOpndVt.valueTypeStr();
            if (hasRegisterClassSupport(dataOpndVt)) {
                Operation* op = NULL;
                if (memDataOpndWidth <= 8) {
                    if (littleEndian_) {
                        op = &opPool.operation("LD8");
                    } else {
                        op = &opPool.operation("LDQ");
                    }
                } else if (memDataOpndWidth <= 16) {
                    if (littleEndian_) {
                        op = &opPool.operation("LD16");
                    } else {
                        op = &opPool.operation("LDH");
                    }
                } else if (memDataOpndWidth <= 32){
                    if (littleEndian_) {
                        op = &opPool.operation("LD32");
                    } else {
                        op = &opPool.operation("LDW");
                    }
                } else {
                    if (littleEndian_) {
                        op = &opPool.operation("LD64");
                    } else {
                        op = &opPool.operation("LDD");
                        std::cerr << "Warning: SIMD support with "
                                  << "big-endian adf is deprecated" << std::endl;
                    }
                }
                std::vector<ValueType> inputs;
                std::vector<ValueType> outputs;
                // Address operand 32 or 64 bits
                inputs.push_back(ValueType(defaultType));
                // Data operand.
                outputs.push_back(dataOpndVt);
                writeOperationDefUsingGivenOperandTypes(
                    o, *op, false, inputs, outputs, dataOpndVtStr);
            }
        }
        for (size_t i = 0; i< vecVts.size(); ++i) {
            const ValueType& dataOpndVt = vecVts[i];
            const TCEString dataOpndVtStr = dataOpndVt.valueTypeStr();
            if (hasRegisterClassSupport(dataOpndVt)) {
            Operation* op = NULL;
            if (memDataOpndWidth <= 8) {
                if (littleEndian_) {
                    op = &opPool.operation("ST8");
                } else {
                    op = &opPool.operation("STQ");
                }
            } else if (memDataOpndWidth <= 16) {
                if (littleEndian_) {
                    op = &opPool.operation("ST16");
                } else {
                    op = &opPool.operation("STH");
                }
            } else if (memDataOpndWidth <= 32) {
                if (littleEndian_) {
                    op = &opPool.operation("ST32");
                } else {
                    op = &opPool.operation("STW");
                }
            } else {
                if (littleEndian_) {
                    op = &opPool.operation("ST64");
                } else {
                    op = &opPool.operation("STD");
                    std::cerr << "Warning: SIMD support with "
                              << "big-endian adf is deprecated" << std::endl;
                }
            }
            std::vector<ValueType> inputs;
            std::vector<ValueType> outputs;
            // Address operand 32 or 64 bits.
            inputs.push_back(ValueType(defaultType));
            inputs.push_back(dataOpndVt);
            // There is no output operands for store.
            writeOperationDefUsingGivenOperandTypes(
                o, *op, false, inputs, outputs, dataOpndVtStr);
            }
        }
        memDataOpndWidth *= 2;
    }
}
References TTAMachine::Machine::hasOperation(), hasRegisterClassSupport(), NullOperation::instance(), TTAMachine::Machine::is64bit(), littleEndian_, mach_, MAX_SCALAR_WIDTH, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), OperationPool::operation(), Operation::output(), TDGenerator::ValueType::valueTypeStr(), TDGenerator::ValueType::vectorTypesOfWidth(), Operand::width(), and writeOperationDefUsingGivenOperandTypes().
Referenced by writeInstrInfo().
writeScalarToVectorDefs()
void TDGen::writeScalarToVectorDefs (std::ostream & o) const protected
Writes scalar_to_vector patterns for vector value types.
Todo:
Add i8 and i16 subword support once those types have RegisterClass support. For now, just skip generation for them.
Definition at line 2388 of file TDGen.cc.
{
    o << endl << "// Scalar to vector definitions." << endl;
    std::map<TCEString, TCEString>::const_iterator it;
    for (it = vbcastOperations_.begin(); it != vbcastOperations_.end();
         ++it) {
        const TCEString& vtStr = it->first;
        const TCEString& vbcastInstr = it->second;
        ValueType scalarVt(vtStr);
        scalarVt.subwCount_ = 1;  // Change vector type to scalar.
        TCEString scalarVtStr = scalarVt.valueTypeStr();
        /// @todo Add i8 and i16 subword support once those types have
        /// RegisterClass support. For now, just skip generation for them.
        if (scalarVtStr == "f16" || scalarVtStr == "f32" ||
            scalarVtStr == "i32") {
            TCEString originalPattern =
                vtStr + " (scalar_to_vector " + scalarVtStr + ":$in)";
            TCEString replacerPattern =
                vbcastInstr + " " + scalarVtStr + ":$in";
            writePatternReplacement(o, originalPattern, replacerPattern);
        }
    }
}
References TDGenerator::ValueType::subwCount_, TDGenerator::ValueType::valueTypeStr(), vbcastOperations_, and writePatternReplacement().
Referenced by writeInstrInfo().
writeStartOfRegisterInfo()
void TDGen::writeStartOfRegisterInfo (std::ostream & o) protected
Writes static register info to the beginning of register info .td file.
Parameters
o Output stream to the file.
Definition at line 594 of file TDGen.cc.
{
    o << "//" << endl;
    o << "// This file is generated automatically!" << endl;
    o << "// Do not edit." << endl;
    o << "//" << endl;
    o << endl;
    o << "class TCEReg<string n, list<Register> aliases> : "
      << "Register<n> {"
      << endl;
    o << "   let Namespace = \"TCE\";" << endl;
    o << "   let Aliases = aliases;" << endl;
    o << "}" << endl;
    o << "class TCEVectorReg<string n, list<Register> subregs> : "
      << "RegisterWithSubRegs<n, subregs> {"
      << endl
      << "    let Namespace = \"TCE\";" << endl
      << "}\n" << endl;
}
Referenced by writeRegisterInfo().
writeTopLevelTD()
void TDGen::writeTopLevelTD (std::ostream & o) protected
Writes a top level TCE.td file which includes generated .td definitions.
Parameters
o Output stream to the file.
Definition at line 4231 of file TDGen.cc.
{
    o << "include \"Target.td\"" << std::endl;
    o << "include \"TCEItinerary.td\"" << std::endl;
    o << "include \"GenRegisterInfo.td\"" << std::endl;
    o << "include \"GenTCEInstrFormats.td\"" << std::endl;
    o << "include \"TCEInstrInfo.td\"" << std::endl;
    o << "include \"GenCallingConv.td\"" << std::endl;
    o << "def TCEInstrInfo : InstrInfo { }" << std::endl;
    o << "class Proc<string Name, SchedMachineModel Model,";
    o << "                        list<SubtargetFeature> Features>";
    o << "  : ProcessorModel<Name, Model, Features>;";
    o << std::endl;
    o << "def  : Proc<\"generic\", TCEModelV0,[]>;";
    o << std::endl;
    o << "def TCE : Target { let InstructionSet = TCEInstrInfo; }"
      << std::endl;
}
Referenced by initializeBackendContents().
writeVectorAnyextPattern()
void TDGen::writeVectorAnyextPattern (std::ostream & o, Operation & op, const TCEString & loadPatternName, int vectorLen) protected
writeVectorBitConversions()
void TDGen::writeVectorBitConversions (std::ostream & o) const protected
Writes bit conversion patterns.
Definition at line 2418 of file TDGen.cc.
{
    o << endl << "// Bit conversions between vector types." << endl;
    std::map<TCEString, RegisterClass>::const_iterator it1;
    for (it1 = vRegClasses_.begin(); it1 != vRegClasses_.end(); ++it1) {
        const TCEString& vtStr1 = it1->first;
        const RegisterClass& regClass1 = it1->second;
        std::map<TCEString, RegisterClass>::const_iterator it2;
        for (it2 = vRegClasses_.begin(); it2 != vRegClasses_.end(); ++it2) {
            const TCEString& vtStr2 = it2->first;
            const RegisterClass& regClass2 = it2->second;
            if (regClass1.valueType().width() !=
                    regClass2.valueType().width() ||
                vtStr1 == vtStr2) {
                continue;
            }
            const TCEString originalPattern = vtStr2 + " (bitconvert (" +
                                              vtStr1 + " " +
                                              regClass1.name() + ":$src))";
            const TCEString replacerPattern =
                vtStr2 + " " + regClass2.name() + ":$src";
            writePatternReplacement(o, originalPattern, replacerPattern);
        }
    }
    o << endl << "// Bit conversions to/from i32." << endl;
    // Write i32 -> same size vector type bit conversions.
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString& vtStr = it->first;
        const RegisterClass& regClass = it->second;
        if (regClass.valueType().width() == 32 && vtStr != "i32") {
            TCEString originalPattern = "i32 (bitconvert (" + vtStr + " " +
                                        regClass.name() + ":$src))";
            TCEString replacerPattern = "i32 R32IRegs:$src";
            writePatternReplacement(o, originalPattern, replacerPattern);
            originalPattern = vtStr + " (bitconvert (i32 R32IRegs:$src))";
            replacerPattern = vtStr + " " + regClass.name() + ":$src";
            writePatternReplacement(o, originalPattern, replacerPattern);
        }
    }
}
References TDGenerator::RegisterClass::name(), TDGenerator::RegisterClass::valueType(), vRegClasses_, TDGenerator::ValueType::width(), and writePatternReplacement().
Referenced by writeInstrInfo().
writeVectorBitwiseOperationDefs()
void TDGen::writeVectorBitwiseOperationDefs (std::ostream & o, Operation & op, bool skipPattern) protected
Writes bitwise NOT/AND/IOR/XOR operation definitions for vector operations.
For 32-bit or less vector widths, 32-bit base operation is used. For bitwise bool vector operations wider than 32 bits, corresponding bitwise operation is searched from the machine, and used to create operation definitions if it exists.
Parameters
o Output stream.
op Operation used to create bitwise operations.
skipPattern If true, operation pattern writing is skipped.
Definition at line 2657 of file TDGen.cc.
{
    o << endl;
    if (op.numberOfOutputs() == 0) {
        assert(false && "Bitwise operation has 0 outputs.");
    }
    int opWidth = op.output(0).width();
    std::vector<ValueType> vts = ValueType::vectorTypesOfWidth(opWidth);
    for (size_t i = 0; i < vts.size(); ++i) {
        const ValueType& vecVt = vts[i];
        const TCEString vecVtStr = vecVt.valueTypeStr();
        // Only integer value types are used in bitwise operations.
        if (!vecVt.isFloat_ && hasRegisterClassSupport(vecVt)) {
            std::vector<ValueType> inputs;
            std::vector<ValueType> outputs;
            for (int i = 0; i < op.numberOfInputs(); ++i) {
                inputs.push_back(vecVt);
            }
            for (int i = 0; i < op.numberOfOutputs(); ++i) {
                outputs.push_back(vecVt);
            }
            writeOperationDefUsingGivenOperandTypes(
                o, op, skipPattern, inputs, outputs, vecVtStr);
        }
    }
    o << endl;
}
References assert, hasRegisterClassSupport(), TDGenerator::ValueType::isFloat_, Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::output(), TDGenerator::ValueType::valueTypeStr(), TDGenerator::ValueType::vectorTypesOfWidth(), Operand::width(), and writeOperationDefUsingGivenOperandTypes().
Referenced by writeInstrInfo().
writeVectorImmediateWriteDefs()
void TDGen::writeVectorImmediateWriteDefs (std::ostream & instrInfoTD) protected
Definition at line 3216 of file TDGen.cc.
{
    for (auto it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        TCEString regClassName = regClass.name();
        ValueType valType = regClass.valueType();
        TCEString valTypeName = valType.valueTypeStr();
        if (valType.width() <= 32) {
            TCEString opName = "MOVI" + valTypeName;
            instrInfoTD << "def " << opName << " : InstTCE<(outs "
                        << regClassName
                        << ":$dst), (ins i32imm:$val), \"\",[]>;"
                        << std::endl;
            opNames_[opName] = "MOVE";
        }
    }
}
References TDGenerator::RegisterClass::name(), opNames_, TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), vRegClasses_, and TDGenerator::ValueType::width().
Referenced by writeInstrInfo().
writeVectorLoadDefs() [1/2]
void TDGen::writeVectorLoadDefs (std::ostream & o, const TCEString & opName, const TCEString & opNameSuffix, bool addrImm, const TCEString & resultType, const TCEString & loadPatternName, bool writePredicatedVersions) protected
writeVectorLoadDefs() [2/2]
void TDGen::writeVectorLoadDefs (std::ostream & o, Operation & op, const TCEString & loadPatternName, int vectorLen) protected
writeVectorLoadStoreOperationExploitations()
void TDGen::writeVectorLoadStoreOperationExploitations (std::ostream & o) protected
Attaches load and store operations to vector types that don't have them.
Checks first which vector value types don't have load and store operations for memory accessing. After collecting the value types without load/store, the function tries to search existing load/store instructions whose data operand width matches the vector value type that doesn't have a load/store operation. If the function can find matching memory instructions, it creates new memory instructions for the vector value types by exploiting existing matching memory instructions.
Definition at line 2704 of file TDGen.cc.
                   {
    const char* defaultTypeStr = mach_.is64bit() ? "i64" : "i32";
    // Value type string of the register class.
    std::set<TCEString> withoutLoadOperation;
    std::set<TCEString> withoutStoreOperation;
    // Collect all vector value types that are without load or store
    // operation support for memory accessing.
    std::map<TCEString, RegisterClass>::iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString vtStr = it->first;
        const ValueType vt(vtStr);
        // 32-bit and smaller vectors are covered by LDQ/LDH/LDW/STQ/STH/STW.
        // TODO: shoudl this have 64 also for 32-bit ADFs?
        if (vt.width() > maxScalarWidth_) {
            if (registerLoads_.find(vtStr) == registerLoads_.end()) {
                withoutLoadOperation.insert(vtStr);
            }
            if (registerStores_.find(vtStr) == registerStores_.end()) {
                withoutStoreOperation.insert(vtStr);
            }
        }
    }
    o << endl << "// Define memory operations for vector operands without"
      << endl << "// load or store operation definition by exploiting"
      << endl << "// existing memory operations of proper width."  << endl;
    OperationPool opPool;
    std::set<TCEString>::const_iterator wLoadIt;
    for (wLoadIt = withoutLoadOperation.begin();
         wLoadIt != withoutLoadOperation.end(); ++wLoadIt) {
        const TCEString& dataOpndVtStr = *wLoadIt;
        const ValueType vt(dataOpndVtStr);
        bool foundExploitable = false;
        std::map<TCEString, InstructionInfo>::const_iterator loadIt =
            registerLoads_.begin();
        // Try to find any machine load instruction that is able to load
        // equal amount of bytes from memory as the ValueType is wide.
        while (!foundExploitable && loadIt != registerLoads_.end()) {
            const ValueType loadInstrVt(loadIt->first);
            // If found a match, remove the last two characters of the
            // load instruction name to get the OSAL operation name.
            if (vt.width() == loadInstrVt.width()) {
                foundExploitable = true;
                const TCEString opName = (loadIt->second).osalOpName_;
                Operation& op = opPool.operation(opName.c_str());
                std::vector<ValueType> inputs;
                std::vector<ValueType> outputs;
                // Address operand always 32 or 64 bits.
                inputs.push_back(ValueType(defaultTypeStr));
                // Data operand.
                outputs.push_back(dataOpndVtStr);
                writeOperationDefUsingGivenOperandTypes(
                    o, op, false, inputs, outputs, dataOpndVtStr);
            }
            ++loadIt;
        }
    }
    std::set<TCEString>::const_iterator wStoreIt;
    for (wStoreIt = withoutStoreOperation.begin();
         wStoreIt != withoutStoreOperation.end(); ++wStoreIt) {
        const TCEString& dataOpndVtStr = *wStoreIt;
        const ValueType vt(dataOpndVtStr);
        bool foundExploitable = false;
        std::map<TCEString, InstructionInfo>::const_iterator storeIt =
            registerStores_.begin();
        // Try to find any machine store instruction that is able to store
        // equal amount of bytes to memory as the ValueType is wide.
        while (!foundExploitable && storeIt != registerStores_.end()) {
            const ValueType storeInstrVt(storeIt->first);
            // If found a match, remove the last two characters of the
            // store instruction name to get the OSAL operation name.
            if (vt.width() == storeInstrVt.width()) {
                foundExploitable = true;
                const TCEString opName = (storeIt->second).osalOpName_;
                Operation& op = opPool.operation(opName.c_str());
                std::vector<ValueType> inputs;
                std::vector<ValueType> outputs;
                // Address operand always i32 or 64 bits.
                inputs.push_back(ValueType(defaultTypeStr));
                inputs.push_back(dataOpndVtStr);
                // There is no output operands for store.
                writeOperationDefUsingGivenOperandTypes(
                    o, op, false, inputs, outputs, dataOpndVtStr);
            }
            ++storeIt;
        }
    }
    o << endl;
}
References TTAMachine::Machine::is64bit(), mach_, maxScalarWidth_, OperationPool::operation(), registerLoads_, registerStores_, vRegClasses_, TDGenerator::ValueType::width(), and writeOperationDefUsingGivenOperandTypes().
Referenced by writeInstrInfo().
writeVectorMemoryOperationDefs()
void TDGen::writeVectorMemoryOperationDefs (std::ostream & o, Operation & op, bool skipPattern) protected
Writes instruction definitions for memory vector operations.
Subword aligned LDQ/LDH/LDW/STQ/STH/STQ vector operations can be passed directly to writing vector operation definitions, but vector aligned LOAD and STORE operations can be used for several different vector types of the same width, thus, all the different vector types need to be covered and separate memory instruction have to be made for them.
Definition at line 2261 of file TDGen.cc.
{
    abortWithError("WiP");
}
References abortWithError.
Referenced by writeInstrInfo().
writeVectorOperationDef()
void TDGen::writeVectorOperationDef (std::ostream & o, Operation & op, TCEString valueTypes, const TCEString & attributes, bool skipPattern) protected
Writes instruction of the vector operation to the .td file.
Creates register version and possibly an immediate version of the vector operation in case there are any scalar operands.
Parameters
o Output stream to the file.
op Operation to be written as an instruction to the .td file.
valueTypes Operand value type identifier characters.
attributes Operation attributes.
skipPattern True, if skip pattern creation.
Definition at line 2181 of file TDGen.cc.
{
    // Make sure operation's operands are fully supported by
    // vector register classes.
    if (!hasRegisterClassSupport(op)) {
        verbose(
            "Warning: " + op.name() + valueTypes +
            " was not created due to unsupported operands.");
        return;
    }
    // Write register version of the operation.
    TDGen::writeOperationDef(o, op, valueTypes, attributes, skipPattern);
    // Information of some operations is needed later, save it if needed.
    saveAdditionalVectorOperationInfo(op, valueTypes, true);
    // Create the same instruction with immediate inputs if there are
    // any input operands that are scalars.
    bool scalarsFound = false;
    for (int i = op.numberOfOutputs(); i < op.operandCount(); ++i) {
        char& c = valueTypes[i];
        switch (c) {
            case OT_REG_BOOL:
                c = OT_IMM_BOOL;
                scalarsFound = true;
                break;
            case OT_REG_INT:
                c = OT_IMM_INT;
                scalarsFound = true;
                break;
            case OT_REG_FP:
                c = OT_IMM_FP;
                scalarsFound = true;
                break;
            case OT_REG_HFP:
                c = OT_IMM_HFP;
                scalarsFound = true;
                break;
            default:
                continue;
        }
    }
    if (scalarsFound) {
        // Write immediate version of the operation.
        TDGen::writeOperationDef(o, op, valueTypes, attributes, skipPattern);
        // Information of some immediate versions are needed also.
        saveAdditionalVectorOperationInfo(op, valueTypes, false);
    }
}
References hasRegisterClassSupport(), Operation::name(), Operation::numberOfOutputs(), Operation::operandCount(), OT_IMM_BOOL, OT_IMM_FP, OT_IMM_HFP, OT_IMM_INT, OT_REG_BOOL, OT_REG_FP, OT_REG_HFP, OT_REG_INT, saveAdditionalVectorOperationInfo(), verbose(), and writeOperationDef().
Referenced by writeOperationDefUsingGivenOperandTypes().
writeVectorOperationDefs()
void TDGen::writeVectorOperationDefs (std::ostream & o, Operation & op, bool skipPattern) protected
Writes needed defitinion(s) of the vector operation to the .td file.
Creates 4 differend instructions of the operation at most:
Integer version (register)
Integer version (immediate)
Float/half float version (register)
Float/half float version (immediate)
Parameters
o Output stream to the .td file.
op Vector operation of which the definitions will be created.
skipPattern True, if skip pattern creation.
Definition at line 2164 of file TDGen.cc.
{
    abortWithError("WiP");
}
References abortWithError.
Referenced by writeInstrInfo().
writeVectorRegisterBaseClasses()
void TDGen::writeVectorRegisterBaseClasses (std::ostream & o) const protected
Writes base class definitions to the .td file.
Definition at line 2047 of file TDGen.cc.
{
    o << endl
      << "// #################################" << endl
      << "// Vector register base class definitions" << endl;
    std::map<int, TCEString>::const_iterator bcIt;
    for (bcIt = baseClasses_.begin(); bcIt != baseClasses_.end(); ++bcIt) {
        int width = bcIt->first;
        if (width > MAX_SCALAR_WIDTH) {
            TCEString baseClassName = bcIt->second;
            o << "class " << baseClassName
              << "<string n, list<Register> aliases> : "
              << "TCEVectorReg<n, aliases> {}" << endl;
        }
    }
    o << "// #################################" << endl;
}
References baseClasses_, and MAX_SCALAR_WIDTH.
Referenced by writeRegisterInfo().
writeVectorRegisterClasses()
void TDGen::writeVectorRegisterClasses (std::ostream & o) const protected
Writes register class definitions to the .td file.
Definition at line 2102 of file TDGen.cc.
{
    o << endl
      << "// #################################" << endl
      << "// Register class definitions for vector registers" << endl;
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const TCEString& vtStr = it->first;
        const RegisterClass& regClass = it->second;
        if (regClass.numberOfRegisters() == 0) {
            std::string msg =
                std::string("The machine is missing registers for ") +
                regClass.valueType().valueTypeStr() + " operands" +
                " required by some operation(s).";
            std::cerr << "Error: Illegal machine: " << msg << std::endl;
            THROW_EXCEPTION(IllegalMachine, msg);
        }
        o << "def " << regClass.name() << " : "
          << "RegisterClass<\"TCE\", "
          << "[" << vtStr << "], " << regClass.alignment() << ", (add ";
        // Add registers to the register class.
        for (size_t i = 0; i < regClass.numberOfRegisters(); ++i) {
            const RegisterInfo& reg = regClass.registerInfo(i);
            o << reg.regName_;
            if (i != regClass.numberOfRegisters() - 1) {
                o << ", ";
            }
        }
        o << ")> ";
        // Register classes below 8 bit of total width need to be set as
        // "8 bit of size" so that when they are spilled to stack, the
        // byte size of the register class is at least 1.
        if (regClass.valueType().width() < 8) {
            o << "{" << endl << "    let Size=8;" << endl << "}" << endl;
        } else {
            o << ";" << endl;
        }
    }
    o << "// #################################" << endl;
}
References TDGenerator::RegisterClass::alignment(), TDGenerator::RegisterClass::name(), TDGenerator::RegisterClass::numberOfRegisters(), TDGenerator::RegisterClass::registerInfo(), TDGenerator::RegisterInfo::regName_, THROW_EXCEPTION, TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), vRegClasses_, and TDGenerator::ValueType::width().
Referenced by writeRegisterInfo().
writeVectorRegisterMoveDefs()
void TDGen::writeVectorRegisterMoveDefs (std::ostream & o) protected
Writes MOV instructions between vector register classes.
Definition at line 2270 of file TDGen.cc.
{
    o << endl
      << "// Vector register->register move definitions." << endl
      << "let isAsCheapAsAMove = 1 in {" << endl;
    std::map<TCEString, RegisterClass>::const_iterator it;
    for (it = vRegClasses_.begin(); it != vRegClasses_.end(); ++it) {
        const RegisterClass& regClass = it->second;
        const TCEString opcode = "MOV" + regClass.name();
        const TCEString vtStr = regClass.valueType().valueTypeStr();
        const TCEString outs = "(outs " + regClass.name() + ":$dst), ";
        const TCEString ins = "(ins " + regClass.name() + ":$src), ";
        const TCEString insPred =
            "(ins GuardRegs:$pred, " + regClass.name() + ":$src), ";
        const TCEString asmOp = "\"$src -> $dst;\", []";
        o << "def " << opcode << " : "
          << "InstTCE<" << outs << ins << asmOp << ">;" << endl;
        opNames_[opcode] = opcode;
        movOperations_.insert(opcode);
        if (hasConditionalMoves_) {
            o << "def PRED_TRUE_" << opcode << " : "
              << "InstTCE<" << outs << insPred << asmOp << ">;" << endl;
            o << "def PRED_FALSE_" << opcode << " : "
              << "InstTCE<" << outs << insPred << asmOp << ">;" << endl;
            opNames_["PRED_TRUE_" + opcode] = "?" + opcode;
            opNames_["PRED_FALSE_" + opcode] = "!" + opcode;
            truePredOps_[opcode] = "PRED_TRUE_" + opcode;
            falsePredOps_[opcode] = "PRED_TRUE_" + opcode;
            movOperations_.insert("PRED_TRUE_" + opcode);
            movOperations_.insert("PRED_FALSE_" + opcode);
        }
    }
    o << "}" << endl;
}
References falsePredOps_, hasConditionalMoves_, movOperations_, TDGenerator::RegisterClass::name(), opNames_, truePredOps_, TDGenerator::RegisterClass::valueType(), TDGenerator::ValueType::valueTypeStr(), and vRegClasses_.
Referenced by writeInstrInfo().
writeVectorRegisterNames()
void TDGen::writeVectorRegisterNames (std::ostream & o) protected
Writes register definitions to the .td file.
Definition at line 2070 of file TDGen.cc.
{
    o << endl
      << "// #################################" << endl
      << "// Register name definitions for vector registers" << endl;
    std::set<TCEString> declaredRegNames;
    std::map<int, std::vector<RegisterInfo>>::const_iterator it;
    for (it = registers_.begin(); it != registers_.end(); ++it) {
        int regsWidth = it->first;
        const std::vector<RegisterInfo>& regs = it->second;
        TCEString baseClass = baseClasses_.find(regsWidth)->second;
        for (size_t i = 0; i < regs.size(); ++i) {
            // Don't declare <=32b registers again, it has been done in TDGen.
            if (regsWidth > MAX_SCALAR_WIDTH) {
                RegisterInfo reg = regs[i];
                RegInfo oldRegInfo = {reg.regFileName_, reg.regIndex_};
                writeRegisterDef(
                    o, oldRegInfo, reg.regName_, baseClass, "", RESERVED);
                declaredRegNames.insert(reg.regName_);
            }
        }
    }
    o << "// #################################" << endl;
}
References baseClasses_, MAX_SCALAR_WIDTH, TDGenerator::RegisterInfo::regFileName_, TDGenerator::RegisterInfo::regIndex_, registers_, TDGenerator::RegisterInfo::regName_, RESERVED, and writeRegisterDef().
Referenced by writeRegisterInfo().
writeVectorStoreDefs() [1/2]
void TDGen::writeVectorStoreDefs (std::ostream & o, const TCEString & opName, const TCEString & opNameSuffix, bool addrImm, const TCEString & dataType, bool writePredicatedVersions) protected
writeVectorStoreDefs() [2/2]
void TDGen::writeVectorStoreDefs (std::ostream & o, Operation & op, int vectorLen) protected
writeVectorTruncStoreDefs() [1/2]
void TDGen::writeVectorTruncStoreDefs (std::ostream & o) const protected
Writes truncstore patterns for vector value types.
Definition at line 2318 of file TDGen.cc.
{
    o << endl << "// Vector truncstore definitions, needed below." << endl;
    // Create truncstore definitions for vector value types, there has to
    // exist store operations for the same value type that the TRUNC
    // operation has. For example, in order to create truncstore using
    // TRUNCWH16X4, there has to be store operations in the machine that
    // supports storing v4i16 value type.
    std::map<TCEString, RegisterClass>::const_iterator rcIt;
    for (rcIt = vRegClasses_.begin(); rcIt != vRegClasses_.end(); ++rcIt) {
        o << "def truncstore" << rcIt->first << " : "
          << "PatFrag<(ops node:$val, node:$ptr),"
          << "(truncstore node:$val, node:$ptr), "
          << "[{return cast<StoreSDNode>(N)->getMemoryVT() == "
          << "MVT::" << rcIt->first << ";}]>;" << endl;
    }
    // Create patterns which will replace "truncstore" pattern with separate
    // TRUNC and then STORE operations.
    o << endl << "// Pattern definitions for truncstores." << endl;
    std::vector<std::pair<const Operation*, TCEString>>::const_iterator it;
    for (it = truncOperations_.begin(); it != truncOperations_.end(); ++it) {
        const TCEString& truncInstr = it->second;
        const TCEString& vtFromStr =
            ValueType::valueTypeStr(it->first->input(0));
        const TCEString targetVtStr =
            ValueType::valueTypeStr(it->first->output(0));
        std::map<TCEString, InstructionInfo>::const_iterator regStoreIt =
            registerStores_.find(targetVtStr);
        // Use register version of store operations.
        if (regStoreIt != registerStores_.end()) {
            const TCEString& regStoreInstr = (regStoreIt->second).instrName_;
            const TCEString originalPattern = "truncstore" + targetVtStr +
                                              " " + vtFromStr +
                                              ":$op2, ADDRrr:$op1";
            const RegisterClass& regClass =
                vRegClasses_.find(vtFromStr)->second;
            const TCEString replacerPattern =
                regStoreInstr + " ADDRrr:$op1, (" + truncInstr + " " +
                regClass.name() + ":$op2)";
            writePatternReplacement(o, originalPattern, replacerPattern);
        }
        std::map<TCEString, InstructionInfo>::const_iterator immStoreIt =
            immediateStores_.find(targetVtStr);
        // Use immediate version of store operations.
        if (immStoreIt != immediateStores_.end()) {
            const TCEString& immStoreInstr = (immStoreIt->second).instrName_;
            const TCEString originalPattern = "truncstore" + targetVtStr +
                                              " " + vtFromStr +
                                              ":$op2, ADDRri:$op1";
            const RegisterClass& regClass =
                vRegClasses_.find(vtFromStr)->second;
            const TCEString replacerPattern =
                immStoreInstr + " ADDRri:$op1, (" + truncInstr + " " +
                regClass.name() + ":$op2)";
            writePatternReplacement(o, originalPattern, replacerPattern);
        }
    }
}
References immediateStores_, TDGenerator::RegisterClass::name(), registerStores_, truncOperations_, TDGenerator::ValueType::valueTypeStr(), vRegClasses_, and writePatternReplacement().
Referenced by writeInstrInfo().
writeVectorTruncStoreDefs() [2/2]
void TDGen::writeVectorTruncStoreDefs (std::ostream & o, Operation & op, int bitsize, int vectorLen) protected
writeWiderVectorOperationExploitations()
void TDGen::writeWiderVectorOperationExploitations (std::ostream & o) protected
Writes vector operation definitions that exploit bigger vector operations.
Exploited vector operands are written in ascending order by their subword count, meaning that e.g. ADD32X16, ADD32X32, and ADD32X4 operation exploitations are listed so that ADD32X4 are written first, then ADD32X16, and then ADD32X32. This way the instruction selection will first use ADD32X4 to execute vector addition for v2i32 vector operand types, and thus, is more optimal solution than executing the same v2i32 addition with ADD32X16 (though ADD32X4 would be also available in the machine).
Definition at line 2831 of file TDGen.cc.
{
    abortWithError("WiP");
}
References abortWithError.
Member Data Documentation
addOperations_
std::map<TCEString, TCEString> TDGen::addOperations_ protected
Contains machine's add instructions (<ValueType, InstrName>).
Definition at line 579 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getAddOpcode().
addressingModeDefs_
std::string TDGen::addressingModeDefs_ protected
Definition at line 470 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
allOpNames_
OperationDAGSelector::OperationSet TDGen::allOpNames_ protected
Contains all operation names in upper case.
Definition at line 520 of file TDGen.hh.
Referenced by analyzeMachineVectorRegisterClasses(), gatherAllMachineOperations(), and writeInstrInfo().
andSameOperations_
std::map<TCEString, TCEString> TDGen::andSameOperations_ protected
Contains machine's ANDSAME instructions (<ValueType, InstrName>).
Definition at line 571 of file TDGen.hh.
argRegCount_
unsigned int TDGen::argRegCount_ protected
Definition at line 628 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), createParamDRegNums(), TDGen(), write32bitRegisterInfo(), write64bitRegisterInfo(), writeArgRegsArray(), and writeCallingConv().
argRegNames_
std::vector<std::string> TDGen::argRegNames_ protected
Definition at line 605 of file TDGen.hh.
Referenced by writeCallDef(), writeCallDefRegs(), and writeRegisterDef().
argRegsArray_
std::string TDGen::argRegsArray_ protected
Definition at line 475 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
backendCode_
std::string TDGen::backendCode_ protected
Definition at line 476 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
baseClasses_
std::map<int, TCEString> TDGen::baseClasses_ protected
Contains vector base classes for register files (<Width, Name>).
Definition at line 529 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), writeCallDefRegs(), writeVectorRegisterBaseClasses(), and writeVectorRegisterNames().
BOOL_SUBW_WIDTH
const int TDGen::BOOL_SUBW_WIDTH static protected
Initial value:
=
    Operand::defaultElementWidth(Operand::BOOL)
Bool type subword width.
Definition at line 484 of file TDGen.hh.
callingConv_
std::string TDGen::callingConv_ protected
Definition at line 474 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
constantMaterializationPredicates_
std::vector<std::string> TDGen::constantMaterializationPredicates_ protected
All predicates used in constant materialization patterns.
Definition at line 649 of file TDGen.hh.
Referenced by createConstantMaterializationPatterns(), and createConstantMaterializationQuery().
dregNum_
unsigned TDGen::dregNum_ protected
Definition at line 468 of file TDGen.hh.
Referenced by write32bitRegisterInfo(), write64bitRegisterInfo(), writeRARegisterInfo(), and writeRegisterDef().
EXPLOIT_BIGGER_REGISTERS
const bool TDGen::EXPLOIT_BIGGER_REGISTERS = true static protected
If set to true, smaller vector value types can be stored to larger register files, e.g. v4i8 vectors can be stored to registers that are over 32 bits in size.
Definition at line 493 of file TDGen.hh.
Referenced by associateRegistersWithVectorRegisterClasses().
extractElemOperations_
std::map<TCEString, TCEString> TDGen::extractElemOperations_ protected
Contains machine's EXTRACTELEM instructions (<ValueType, InstrName>).
Definition at line 563 of file TDGen.hh.
falsePredOps_
std::map<std::string, std::string> TDGen::falsePredOps_ protected
Definition at line 612 of file TDGen.hh.
Referenced by writeBackendCode(), writeInstrInfo(), writeOperationDef(), and writeVectorRegisterMoveDefs().
FP_SUBW_WIDTH
const int TDGen::FP_SUBW_WIDTH static protected
Initial value:
=
    Operand::defaultElementWidth(Operand::FLOAT_WORD)
Float type subword width.
Definition at line 480 of file TDGen.hh.
Referenced by analyzeMachineVectorRegisterClasses().
gatherOperations_
std::map<TCEString, TCEString> TDGen::gatherOperations_ protected
Contains machine's GATHER instructions (<ValueType, InstrName>).
Definition at line 577 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getGatherOpcode().
gprRegNames_
std::vector<std::string> TDGen::gprRegNames_ protected
Definition at line 607 of file TDGen.hh.
Referenced by writeCallDefRegs(), and writeRegisterDef().
guardedRegs_
std::set<RegInfo> TDGen::guardedRegs_ protected
List of register that are associated with a guard on a bus.
Definition at line 636 of file TDGen.hh.
Referenced by analyzeRegisters(), and writeRegisterDef().
guardRegTemplateName
const std::string TDGen::guardRegTemplateName = "Guard" static protected
Definition at line 651 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), writeGuardRegisterClassInfo(), and writeRegisterDef().
hasConditionalMoves_
bool TDGen::hasConditionalMoves_ protected
Definition at line 623 of file TDGen.hh.
Referenced by canBePredicated(), createSelectPatterns(), TDGen(), writeInstrInfo(), writeOperationDefs(), and writeVectorRegisterMoveDefs().
hasExBoolRegs_
bool TDGen::hasExBoolRegs_ protected
Definition at line 619 of file TDGen.hh.
hasExIntRegs_
bool TDGen::hasExIntRegs_ protected
Definition at line 620 of file TDGen.hh.
hasSelect_
bool TDGen::hasSelect_ protected
Definition at line 621 of file TDGen.hh.
Referenced by createSelectPatterns(), and writeOperationDefs().
HFP_SUBW_WIDTH
const int TDGen::HFP_SUBW_WIDTH static protected
Initial value:
=
    Operand::defaultElementWidth(Operand::HALF_FLOAT_WORD)
Half float type subword width.
Definition at line 482 of file TDGen.hh.
Referenced by analyzeMachineVectorRegisterClasses().
highestLaneBool_
int TDGen::highestLaneBool_ protected
Definition at line 617 of file TDGen.hh.
highestLaneInt_
int TDGen::highestLaneInt_ protected
Definition at line 616 of file TDGen.hh.
immediateLoads_
std::map<TCEString, TDGenerator::InstructionInfo> TDGen::immediateLoads_ protected
All immediate load operations (<ValueType, InstrInfo>).
Definition at line 544 of file TDGen.hh.
immediateStores_
std::map<TCEString, TDGenerator::InstructionInfo> TDGen::immediateStores_ protected
All immediate store operations (<ValueType, InstrInfo>).
Definition at line 542 of file TDGen.hh.
Referenced by writeVectorTruncStoreDefs().
immInfo_
ImmInfo* TDGen::immInfo_ protected
Definition at line 465 of file TDGen.hh.
Referenced by areImmediateOperandsLegal(), createConstantMaterializationPatterns(), getLLVMPatternWithConstants(), TDGen(), writeInstrInfo(), writeOperandDefs(), and ~TDGen().
immOperandDefs_
std::map<ImmInfoKey, std::string> TDGen::immOperandDefs_ protected
Maps (operation, operand) pairs to i32 immediate operand definition names.
Definition at line 436 of file TDGen.hh.
Referenced by dagNodeToString(), immediateOperandNameForEmulatedOperation(), patInputs(), and writeIntegerImmediateDefs().
instrFormats_
std::string TDGen::instrFormats_ protected
Definition at line 473 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
instrInfo_
std::string TDGen::instrInfo_ protected
Definition at line 472 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
iorOperations_
std::map<TCEString, TCEString> TDGen::iorOperations_ protected
Contains machine's shl instructions (<ValueType, InstrName>).
Definition at line 583 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getIorOpcode().
iorSameOperations_
std::map<TCEString, TCEString> TDGen::iorSameOperations_ protected
Contains machine's IORSAME instructions (<ValueType, InstrName>).
Definition at line 573 of file TDGen.hh.
littleEndian_
bool TDGen::littleEndian_ protected
Definition at line 627 of file TDGen.hh.
Referenced by createBoolAndHalfLoadPatterns(), createByteExtLoadPatterns(), createEndiannesQuery(), createShortExtLoadPatterns(), genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), llvmOperationName(), llvmOperationPattern(), writeBackendCode(), writeBooleanStorePatterns(), writeInstrInfo(), and writeScalarOperationExploitations().
llvmGuardRegs_
std::vector<std::string> TDGen::llvmGuardRegs_ protected
The LLVM register defs used as guards.
Definition at line 599 of file TDGen.hh.
Referenced by writeGuardRegisterClassInfo(), and writeRegisterDef().
mach_
const TTAMachine::Machine& TDGen::mach_ protected
Definition at line 463 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeRegisters(), checkRequiredRegisters(), constantNodeString(), create32BitExtLoadPatterns(), createBoolAndHalfLoadPatterns(), createBranchAnalysis(), createByteExtLoadPatterns(), createConstShiftPatterns(), createEndiannesQuery(), createGetMaxMemoryAlignment(), createMinMaxGenerator(), createSelectPatterns(), createShortExtLoadPatterns(), emulatingOpNodeLLVMName(), gatherAllMachineOperations(), genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), genTCEInstrInfo_copyPhys64bitReg(), llvmOperationName(), llvmOperationPattern(), operandChar(), operandToString(), operationCanBeMatched(), TDGen(), write1bitRegisterInfo(), write32bitRegisterInfo(), write64bitRegisterInfo(), writeAddressingModeDefs(), writeBackendCode(), writeCallingConv(), writeCallSeqStart(), writeCondBranchDefs(), writeConstShiftPat(), writeEmulationPattern(), writeGetPointerAdjustmentQuery(), writeGuardRegisterClassInfo(), writeHWLoopDef(), writeInstrInfo(), writeIntegerImmediateDefs(), writeMiscPatterns(), writeMoveImmediateDefs(), writeOperationDef(), writeOperationDefs(), RISCVTDGen::writePatternDefinition(), writePortGuardedJumpDefPair(), writeRARegisterInfo(), writeScalarOperationExploitations(), and writeVectorLoadStoreOperationExploitations().
MAX_SCALAR_WIDTH
const int TDGen::MAX_SCALAR_WIDTH = 64 static protected
Distincts wide vs scalar registers.
Definition at line 486 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), writeScalarOperationExploitations(), writeVectorRegisterBaseClasses(), and writeVectorRegisterNames().
MAX_SUBW_COUNT
const int TDGen::MAX_SUBW_COUNT = SIMD_WORD_WIDTH / BYTE_BITWIDTH static protected
Maximum number of subwords that any SIMD operation can have.
Definition at line 488 of file TDGen.hh.
Referenced by genTCETargetLoweringSIMD_getSetCCResultVT().
maxScalarWidth_
int TDGen::maxScalarWidth_ protected
Definition at line 625 of file TDGen.hh.
Referenced by createVectorRVDRegNums(), genTCERegisterInfo_setReservedVectorRegs(), TDGen(), writeCallDefRegs(), and writeVectorLoadStoreOperationExploitations().
maxVectorSize_
int TDGen::maxVectorSize_ protected
Definition at line 614 of file TDGen.hh.
Referenced by writeBackendCode().
movOperations_
std::set<TCEString> TDGen::movOperations_ protected
Contains all moves between register classes (<InstrName>).
Definition at line 586 of file TDGen.hh.
Referenced by writeVectorRegisterMoveDefs().
operandDefs_
std::string TDGen::operandDefs_ protected
Definition at line 471 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
OPERATION_PATTERNS_
const std::map< TCEString, TCEString > TDGen::OPERATION_PATTERNS_ static protected
Contains <BaseOpName, OpPattern> key-value pairs.
Definition at line 517 of file TDGen.hh.
opNames_
std::map<std::string, std::string> TDGen::opNames_ protected
Definition at line 609 of file TDGen.hh.
Referenced by createBoolAndHalfLoadPatterns(), createBranchAnalysis(), createConstantMaterializationPatterns(), createMinMaxDef(), createMinMaxGenerator(), createSelectPatterns(), getLLVMPatternWithConstants(), writeBackendCode(), writeBooleanStorePatterns(), writeCondBranchDefs(), writeConstShiftPat(), writeGetPointerAdjustmentQuery(), writeHWLoopDef(), writeInstrInfo(), writeOperationDef(), writePortGuardedJumpDefPair(), writeVectorImmediateWriteDefs(), and writeVectorRegisterMoveDefs().
OT_IMM_BOOL
const char TDGen::OT_IMM_BOOL = 'j' static
Definition at line 503 of file TDGen.hh.
Referenced by constantNodeString(), dagNodeToString(), getLLVMPatternWithConstants(), getMovePattern(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), and writeVectorOperationDef().
OT_IMM_FP
const char TDGen::OT_IMM_FP = 'k' static
Definition at line 505 of file TDGen.hh.
Referenced by constantNodeString(), getLLVMPatternWithConstants(), getMovePattern(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), and writeVectorOperationDef().
OT_IMM_HFP
const char TDGen::OT_IMM_HFP = 'l' static
Definition at line 506 of file TDGen.hh.
Referenced by getLLVMPatternWithConstants(), getMovePattern(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), and writeVectorOperationDef().
OT_IMM_INT
const char TDGen::OT_IMM_INT = 'i' static
Definition at line 504 of file TDGen.hh.
Referenced by areImmediateOperandsLegal(), canBePredicated(), constantNodeString(), createByteExtLoadPatterns(), createShortExtLoadPatterns(), dagNodeToString(), emulatingOpNodeLLVMName(), getLLVMPatternWithConstants(), getMovePattern(), operandToString(), operandTypeToRegister(), patInputs(), regOperandCharToImmOperandChar(), and writeVectorOperationDef().
OT_IMM_LONG
const char TDGen::OT_IMM_LONG = 'a' static
Definition at line 507 of file TDGen.hh.
Referenced by constantNodeString(), createByteExtLoadPatterns(), createShortExtLoadPatterns(), emulatingOpNodeLLVMName(), operandToString(), and regOperandCharToImmOperandChar().
OT_REG_BOOL
const char TDGen::OT_REG_BOOL = 'b' static
Definition at line 497 of file TDGen.hh.
Referenced by constantNodeString(), dagNodeToString(), getMovePattern(), operandChar(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), writeOperationDefs(), and writeVectorOperationDef().
OT_REG_DOUBLE
const char TDGen::OT_REG_DOUBLE = 'd' static
Definition at line 502 of file TDGen.hh.
Referenced by constantNodeString().
OT_REG_FP
const char TDGen::OT_REG_FP = 'f' static
Definition at line 500 of file TDGen.hh.
Referenced by constantNodeString(), getMovePattern(), operandChar(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), TDGenerator::ValueType::valueType(), and writeVectorOperationDef().
OT_REG_HFP
const char TDGen::OT_REG_HFP = 'h' static
Definition at line 501 of file TDGen.hh.
Referenced by constantNodeString(), getMovePattern(), operandChar(), operandToString(), operandTypeToRegister(), regOperandCharToImmOperandChar(), and writeVectorOperationDef().
OT_REG_INT
const char TDGen::OT_REG_INT = 'r' static
Definition at line 498 of file TDGen.hh.
Referenced by constantNodeString(), createByteExtLoadPatterns(), createShortExtLoadPatterns(), getMovePattern(), operandChar(), operandToString(), operandTypeToRegister(), operationCanBeMatched(), regOperandCharToImmOperandChar(), writeEmulationPattern(), writeOperationDef(), RISCVTDGen::writePatternDefinition(), and writeVectorOperationDef().
OT_REG_LONG
const char TDGen::OT_REG_LONG = 's' static
Definition at line 499 of file TDGen.hh.
Referenced by constantNodeString(), createByteExtLoadPatterns(), createShortExtLoadPatterns(), operandChar(), operandToString(), operationCanBeMatched(), regOperandCharToImmOperandChar(), writeEmulationPattern(), writeOperationDef(), and RISCVTDGen::writePatternDefinition().
OT_VREG_BOOL
const char TDGen::OT_VREG_BOOL = 'a' static
Definition at line 508 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
OT_VREG_FP
const char TDGen::OT_VREG_FP = 'e' static
Definition at line 512 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
OT_VREG_HFP
const char TDGen::OT_VREG_HFP = 'g' static
Definition at line 513 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
OT_VREG_INT16
const char TDGen::OT_VREG_INT16 = 't' static
Definition at line 510 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
OT_VREG_INT32
const char TDGen::OT_VREG_INT32 = 'u' static
Definition at line 511 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
OT_VREG_INT8
const char TDGen::OT_VREG_INT8 = 'q' static
Definition at line 509 of file TDGen.hh.
Referenced by operandChar(), and operandToString().
packOperations_
std::map<TCEString, TCEString> TDGen::packOperations_ protected
Contains machine's PACK instructions (<ValueType, InstrName>).
Definition at line 547 of file TDGen.hh.
prebypassStackIndeces_
bool TDGen::prebypassStackIndeces_ protected
Definition at line 632 of file TDGen.hh.
Referenced by TDGen(), and write32bitRegisterInfo().
registerInfo_
std::string TDGen::registerInfo_ protected
Definition at line 469 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
registerLoads_
std::map<TCEString, TDGenerator::InstructionInfo> TDGen::registerLoads_ protected
All register load operations (<ValueType, InstrInfo>).
Definition at line 540 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getLoadOpcode(), and writeVectorLoadStoreOperationExploitations().
registers_
std::map<int, std::vector<TDGenerator::RegisterInfo> > TDGen::registers_ protected
Contains registers fit for being vector registers (<Width, Registers>).
Definition at line 532 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), associateRegistersWithVectorRegisterClasses(), orderEqualWidthRegistersToRoundRobin(), writeCallDefRegs(), and writeVectorRegisterNames().
registerStores_
std::map<TCEString, TDGenerator::InstructionInfo> TDGen::registerStores_ protected
All register store operations (<ValueType, InstrInfo>).
Definition at line 538 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getStore(), writeVectorLoadStoreOperationExploitations(), and writeVectorTruncStoreDefs().
regs16bit_
std::vector<RegInfo> TDGen::regs16bit_ protected
Definition at line 593 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), and write16bitRegisterInfo().
regs1bit_
std::vector<RegInfo> TDGen::regs1bit_ protected
Definition at line 589 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeRegisters(), createSelectPatterns(), and write1bitRegisterInfo().
regs32bit_
std::vector<RegInfo> TDGen::regs32bit_ protected
Definition at line 595 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeRegisters(), checkRequiredRegisters(), write32bitRegisterInfo(), and writeRegisterInfo().
regs64bit_
std::vector<RegInfo> TDGen::regs64bit_ protected
Definition at line 597 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeRegisters(), checkRequiredRegisters(), and write64bitRegisterInfo().
regs8bit_
std::vector<RegInfo> TDGen::regs8bit_ protected
Definition at line 591 of file TDGen.hh.
Referenced by analyzeRegisters().
regs_
std::map<std::string, RegInfo> TDGen::regs_ protected
Map of generated llvm register names to physical register in the machine.
Definition at line 603 of file TDGen.hh.
Referenced by writeBackendCode(), and writeRegisterDef().
regsInClasses_
RegClassMap TDGen::regsInClasses_ protected
All registers in certain group.
Definition at line 645 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), write16bitRegisterInfo(), write1bitRegisterInfo(), write32bitRegisterInfo(), and writeRegisterDef().
regsInRFClasses_
RegClassMap TDGen::regsInRFClasses_ protected
Definition at line 647 of file TDGen.hh.
Referenced by write32bitRegisterInfo().
requiredI32Regs_
unsigned int TDGen::requiredI32Regs_ protected
Minimum number of 32 bit registers.
Definition at line 630 of file TDGen.hh.
Referenced by checkRequiredRegisters(), TDGen(), and writeRegisterInfo().
requiredI64Regs_
unsigned int TDGen::requiredI64Regs_ protected
Definition at line 631 of file TDGen.hh.
Referenced by checkRequiredRegisters(), and TDGen().
resRegNames_
std::vector<std::string> TDGen::resRegNames_ protected
Definition at line 606 of file TDGen.hh.
Referenced by writeCallDefRegs(), and writeRegisterDef().
scalarOps_
std::map<TCEString, Operation*> TDGen::scalarOps_ protected
Contains all scalar operations (<Name, Operation>).
Definition at line 523 of file TDGen.hh.
Referenced by gatherAllMachineOperations().
shlOperations_
std::map<TCEString, TCEString> TDGen::shlOperations_ protected
Contains machine's shl instructions (<ValueType, InstrName>).
Definition at line 581 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getShlOpcode().
shlSameOperations_
std::map<TCEString, TCEString> TDGen::shlSameOperations_ protected
Contains machine's SHLSAME instructions (<ValueType, InstrName>).
Definition at line 565 of file TDGen.hh.
shrSameOperations_
std::map<TCEString, TCEString> TDGen::shrSameOperations_ protected
Contains machine's SHRSAME instructions (<ValueType, InstrName>).
Definition at line 567 of file TDGen.hh.
shruSameOperations_
std::map<TCEString, TCEString> TDGen::shruSameOperations_ protected
Contains machine's SHRUSAME instructions (<ValueType, InstrName>).
Definition at line 569 of file TDGen.hh.
tempRegFiles_
std::set< const TTAMachine::RegisterFile*, TTAMachine::MachinePart::Comparator> TDGen::tempRegFiles_ protected
Register files whose last reg reserved for temp reg copies.
Definition at line 641 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeRegisters(), checkRequiredRegisters(), and TDGen().
topLevelTD_
std::string TDGen::topLevelTD_ protected
Definition at line 477 of file TDGen.hh.
Referenced by generateBackend(), generateBackend(), and initializeBackendContents().
truePredOps_
std::map<std::string, std::string> TDGen::truePredOps_ protected
Definition at line 611 of file TDGen.hh.
Referenced by writeBackendCode(), writeInstrInfo(), writeOperationDef(), and writeVectorRegisterMoveDefs().
truncOperations_
std::vector<std::pair<const Operation*, TCEString> > TDGen::truncOperations_ protected
Contains machine's TRUNCxx/CFH instructions (<ValueType, InstrName>).
Definition at line 551 of file TDGen.hh.
Referenced by writeVectorTruncStoreDefs().
use64bitForFP_
bool TDGen::use64bitForFP_ protected
Definition at line 633 of file TDGen.hh.
Referenced by genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), write32bitRegisterInfo(), and write64bitRegisterInfo().
vbcastOperations_
std::map<TCEString, TCEString> TDGen::vbcastOperations_ protected
Contains machine's VBCAST instructions (<ValueType, InstrName>).
Definition at line 549 of file TDGen.hh.
Referenced by writeScalarToVectorDefs().
vcshuffleOperations_
std::map<std::pair<TCEString, std::vector<int> >, TCEString> TDGen::vcshuffleOperations_ protected
Contains machine's VCSHUFFLE instructions (<<ValueType, ConstantSelects>, InstrName>).
Definition at line 561 of file TDGen.hh.
vectorOps_
std::map<TCEString, Operation*> TDGen::vectorOps_ protected
Contains all vector operations (<Name, Operation>).
Definition at line 526 of file TDGen.hh.
Referenced by gatherAllMachineOperations().
vRegClasses_
std::map<TCEString, TDGenerator::RegisterClass> TDGen::vRegClasses_ protected
Contains required vector register classes (<ValueType, RegClass>).
Definition at line 535 of file TDGen.hh.
Referenced by analyzeMachineRegisters(), analyzeMachineVectorRegisterClasses(), associatedVectorRegisterClass(), associateRegistersWithVectorRegisterClasses(), createSelectPatterns(), createVectorRVDRegNums(), genGeneratedTCEPlugin_getLoad(), genGeneratedTCEPlugin_getStore(), genGeneratedTCEPlugin_getVectorImmediateOpcode(), genTCEInstrInfoSIMD_copyPhysVectorReg(), genTCERegisterInfo_setReservedVectorRegs(), genTCETargetLoweringSIMD_addVectorRegisterClasses(), genTCETargetLoweringSIMD_associatedVectorRegClass(), hasRegisterClassSupport(), hasRegisterClassSupport(), writeCallingConv(), writeVectorBitConversions(), writeVectorImmediateWriteDefs(), writeVectorLoadStoreOperationExploitations(), writeVectorRegisterClasses(), writeVectorRegisterMoveDefs(), and writeVectorTruncStoreDefs().
vselectOperations_
std::map<TCEString, TCEString> TDGen::vselectOperations_ protected
Contains machine's VSELECT instructions (<instrName, ValueType>).
Definition at line 553 of file TDGen.hh.
vshuffle1Operations_
std::map<TCEString, TCEString> TDGen::vshuffle1Operations_ protected
Contains machine's VSHUFFLE1 instructions (<ValueType, InstrName>).
Definition at line 555 of file TDGen.hh.
vshuffle2Operations_
std::map<TCEString, TCEString> TDGen::vshuffle2Operations_ protected
Contains machine's VSHUFFLE2 instructions (<ValueType, InstrName>).
Definition at line 557 of file TDGen.hh.
xorSameOperations_
std::map<TCEString, TCEString> TDGen::xorSameOperations_ protected
Contains machine's XORSAME instructions (<ValueType, InstrName>).
Definition at line 575 of file TDGen.hh.
The documentation for this class was generated from the following files:
TDGen.hh
TDGen.cc