OpenASIP: OSEdInformer Class Reference
OSEdInformer Class Reference
#include <OSEdInformer.hh>
Public Types
enum EventId { EVENT_REGISTER , EVENT_RESET , EVENT_MEMORY }
Public Member Functions
OSEdInformer ()
virtual ~OSEdInformer ()
void handleEvent (EventId event)
void registerListener (EventId event, OSEdListener *listener)
void unregisterListener (EventId event, OSEdListener *listener)
Private Types
typedef std::map< EventId, std::vector< OSEdListener * > > ListenerContainer
Container for mapping event ids to Listener objects.
Private Member Functions
OSEdInformer (const OSEdInformer &)
Copying not allowed.
OSEdInformer & operator= (const OSEdInformer &)
Assignment not allowed.
Private Attributes
ListenerContainer listeners_
All listeners.
Detailed Description
Notifies listeners that a certain event has occurred.
Listeners are OSEdListener objects that are interested on events.
Definition at line 47 of file OSEdInformer.hh.
Member Typedef Documentation
ListenerContainer
typedef std::map<EventId, std::vector<OSEdListener*> > OSEdInformer::ListenerContainer private
Container for mapping event ids to Listener objects.
Definition at line 67 of file OSEdInformer.hh.
Member Enumeration Documentation
EventId
enum OSEdInformer::EventId
All possible events.
Enumerator
EVENT_REGISTER
Event when register value might change.
EVENT_RESET
Event when operation is reseted.
EVENT_MEMORY
Event when memory may be changed.
Definition at line 52 of file OSEdInformer.hh.
                 {
        EVENT_REGISTER,    ///< Event when register value might change.
        EVENT_RESET,       ///< Event when operation is reseted.
        EVENT_MEMORY       ///< Event when memory may be changed.
    };
Constructor & Destructor Documentation
OSEdInformer() [1/2]
OSEdInformer::OSEdInformer ()
Constructor.
Definition at line 41 of file OSEdInformer.cc.
{
}
~OSEdInformer()
OSEdInformer::~OSEdInformer () virtual
Destructor.
Definition at line 47 of file OSEdInformer.cc.
{
}
OSEdInformer() [2/2]
OSEdInformer::OSEdInformer (const OSEdInformer &) private
Copying not allowed.
Member Function Documentation
handleEvent()
void OSEdInformer::handleEvent (EventId event)
Handles event of given id.
If no such id exists, nothing is done.
Parameters
event Event to be handled.
Definition at line 58 of file OSEdInformer.cc.
{
    ListenerContainer::iterator iter = listeners_.find(event);
    if (iter != listeners_.end()) {
        for (size_t i = 0; i < (*iter).second.size(); i++) {
            (*iter).second[i]->handleEvent(event);
        }
    }
}
References listeners_.
Referenced by SimulateDialog::onAdvanceClock(), SimulateDialog::onFormatChanged(), SimulateDialog::onReset(), and SimulateDialog::onTrigger().
operator=()
OSEdInformer & OSEdInformer::operator= (const OSEdInformer &) private
Assignment not allowed.
registerListener()
void OSEdInformer::registerListener (EventId event, OSEdListener * listener)
Registers listener to informers data base.
Parameters
event Event of which given listener is interested in.
listener Listener to be registered.
Definition at line 74 of file OSEdInformer.cc.
{
    ListenerContainer::iterator iter = listeners_.find(event);
    if (iter != listeners_.end()) {
        (*iter).second.push_back(listener);
    } else {
        vector<OSEdListener*> newListenerContainer;
        newListenerContainer.push_back(listener);
        listeners_[event] = newListenerContainer;
    }
}
References listeners_.
Referenced by MemoryDialog::MemoryDialog(), and SimulateDialog::SimulateDialog().
unregisterListener()
void OSEdInformer::unregisterListener (EventId event, OSEdListener * listener)
Unregisters listener from the informer.
Parameters
event Event for which given listener is registered to listen.
listener Listener to be unregistered.
Definition at line 92 of file OSEdInformer.cc.
{
    ListenerContainer::iterator iter = listeners_.find(event);
    if (iter != listeners_.end()) {
        vector<OSEdListener*>::iterator vecIter = (*iter).second.begin();
        while (vecIter != (*iter).second.end()) {
            if (*vecIter == listener) {
                (*iter).second.erase(vecIter);
                return;
            }
            vecIter++;
        }
    }
}
References listeners_.
Referenced by SimulateDialog::onClose(), MemoryDialog::onClose(), and SimulateDialog::onOK().
Member Data Documentation
listeners_
ListenerContainer OSEdInformer::listeners_ private
All listeners.
Definition at line 75 of file OSEdInformer.hh.
Referenced by handleEvent(), registerListener(), and unregisterListener().
The documentation for this class was generated from the following files:
OSEdInformer.hh
OSEdInformer.cc