OpenASIP: SocketDialog Class Reference
SocketDialog Class Reference
#include <SocketDialog.hh>
Public Member Functions
SocketDialog (wxWindow *parent, TTAMachine::Socket *socket)
virtual ~SocketDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_ATTACHED_LIST , ID_DETACHED_LIST , ID_ATTACH ,
ID_DETACH , ID_HELP , ID_DIRECTION , ID_LABEL_NAME ,
ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
TTAMachine::Segment * segment (wxListCtrl *listCtrl, int index)
void onOK (wxCommandEvent &)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &)
void onAttach (wxCommandEvent &)
void onDetach (wxCommandEvent &)
void onAttachedSelection (wxListEvent &)
void onDetachedSelection (wxListEvent &)
void onDirection (wxCommandEvent &)
void updateConnected ()
void updateDirection ()
virtual bool TransferDataToWindow ()
void setTexts ()
Private Attributes
TTAMachine::Socket * socket_
Socket to modify.
wxString name_
Name of the socket.
MachineTester * tester_
MachineTester which does sanity checks for the target machine.
wxRadioBox * directionBox_
Radio box for direction.
wxListCtrl * connectedListCtrl_
List control for connected (bus, segment) pairs.
wxListCtrl * segmentListCtrl_
List control for all (bus, segment) pairs.
wxStaticBoxSizer * attachedSizer_
Static boxsizer containing the list of attached buses.
wxStaticBoxSizer * detachedSizer_
Static boxsizer containing the list of detached buses.
Detailed Description
Dialog for modifying socket attributes.
Definition at line 50 of file SocketDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NAME
ID_ATTACHED_LIST
ID_DETACHED_LIST
ID_ATTACH
ID_DETACH
ID_HELP
ID_DIRECTION
ID_LABEL_NAME
ID_LINE
Definition at line 88 of file SocketDialog.hh.
         {
        ID_NAME = 10000,
        ID_ATTACHED_LIST,
        ID_DETACHED_LIST,
        ID_ATTACH,
        ID_DETACH,
        ID_HELP,
        ID_DIRECTION,
        ID_LABEL_NAME,
        ID_LINE
    };
Constructor & Destructor Documentation
SocketDialog()
SocketDialog::SocketDialog (wxWindow * parent, TTAMachine::Socket * socket)
The Constructor.
Parameters
parent Parent window of the dialog.
socket Socket to be modified with the dialog.
Definition at line 90 of file SocketDialog.cc.
                   :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    socket_(socket),
    directionBox_(NULL),
    connectedListCtrl_(NULL),
    segmentListCtrl_(NULL),
    attachedSizer_(NULL),
    detachedSizer_(NULL) {
    createContents(this, true, true);
    tester_ = new MachineTester(*socket_->machine());
    name_ = WxConversion::toWxString(socket_->name());
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_ATTACH)->Disable();
    FindWindow(ID_DETACH)->Disable();
    // Set widget pointers.
    directionBox_ = dynamic_cast<wxRadioBox*>(FindWindow(ID_DIRECTION));
    connectedListCtrl_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_ATTACHED_LIST));
    segmentListCtrl_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_DETACHED_LIST));
    // Set widget validators.
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    // sets labels for widgets
    setTexts();
    TransferDataToWindow();
}
References WxConversion::toWxString().
~SocketDialog()
SocketDialog::~SocketDialog () virtual
The Destructor.
Definition at line 130 of file SocketDialog.cc.
{
    delete tester_;
}
References tester_.
Member Function Documentation
createContents()
wxSizer * SocketDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was initially generated with wxDesigner, code will be cleaned up later.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 567 of file SocketDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxGridSizer *item1 = new wxGridSizer( 2, 0, 0 );
    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxString strs5[] =
    {
        wxT("Input"),
        wxT("Output")
    };
    wxRadioBox *item5 = new wxRadioBox( parent, ID_DIRECTION, wxT("Direction:"), wxDefaultPosition, wxDefaultSize, 2, strs5, 1, wxRA_SPECIFY_COLS );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item8 = new wxStaticBox( parent, -1, wxT("Attached buses:") );
    wxStaticBoxSizer *item7 = new wxStaticBoxSizer( item8, wxVERTICAL );
    attachedSizer_ = item7;
    wxListCtrl *item9 = new wxListCtrl( parent, ID_ATTACHED_LIST, wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item6->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item10 = new wxBoxSizer( wxVERTICAL );
    wxButton *item11 = new wxButton( parent, ID_ATTACH, wxT("&Attach"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item12 = new wxButton( parent, ID_DETACH, wxT("&Detach"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    item6->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticBox *item14 = new wxStaticBox( parent, -1, wxT("Detached buses:") );
    wxStaticBoxSizer *item13 = new wxStaticBoxSizer( item14, wxVERTICAL );
    detachedSizer_ = item13;
    wxListCtrl *item15 = new wxListCtrl( parent, ID_DETACHED_LIST, wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    item6->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item6, 0, wxALIGN_CENTER, 5 );
    wxStaticLine *item16 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item16, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item17 = new wxGridSizer( 2, 0, 0 );
    wxButton *item18 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALL, 5 );
    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item20 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item21 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );
    item17->Add( item19, 0, wxALL, 5 );
    item0->Add( item17, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References attachedSizer_, detachedSizer_, ID_ATTACH, ID_ATTACHED_LIST, ID_DETACH, ID_DETACHED_LIST, ID_DIRECTION, ID_HELP, ID_LABEL_NAME, ID_LINE, and ID_NAME.
onAttach()
void SocketDialog::onAttach (wxCommandEvent &) private
Attaches selected segments on the segment list to the socket.
Definition at line 364 of file SocketDialog.cc.
{
    long item = -1;
    item = segmentListCtrl_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    // Socket state is saved, so it can be restored if the socket can't
    // be connected to all selected segments.
    ObjectState* savedState = socket_->saveState();
    MachineTester tester(*socket_->machine());
    // Try to connect socket to all selected segments.
    while (item != -1) {
        Segment* seg = segment(segmentListCtrl_, item);
        assert(seg != NULL);
        if (!tester.canConnect(*socket_, *seg)) {
            // Socket couldn't be connected to all selected segments.
            std::string error =
                MachineTestReporter::socketSegmentConnectionError(
                    *socket_, *seg, tester);
            wxString message = WxConversion::toWxString(error);
            InformationDialog dialog(this, message);
            dialog.ShowModal();
            socket_->loadState(savedState);
            break;
        }
        socket_->attachBus(*seg);
        item = segmentListCtrl_->GetNextItem(
            item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    }
    delete savedState;
    savedState = NULL;
    updateConnected();
    updateDirection();
    // Select the first item in the segment list (if possible) to improve
    // the dialog usability.
    if (segmentListCtrl_->GetItemCount() > 0) {
        segmentListCtrl_->SetItemState(
            0, wxLIST_STATE_SELECTED | wxLIST_STATE_FOCUSED,
            wxLIST_STATE_SELECTED | wxLIST_STATE_FOCUSED);
    }
    wxListEvent dummy;
    onDetachedSelection(dummy);
}
References assert, TTAMachine::Socket::attachBus(), MachineTester::canConnect(), dummy, TTAMachine::Socket::loadState(), TTAMachine::Component::machine(), onDetachedSelection(), TTAMachine::Socket::saveState(), segment(), segmentListCtrl_, socket_, MachineTestReporter::socketSegmentConnectionError(), WxConversion::toWxString(), updateConnected(), and updateDirection().
onAttachedSelection()
void SocketDialog::onAttachedSelection (wxListEvent &) private
Disables and enables Detach button under the connected list.
If a (bus, segment) pair is selected, button is enabled. If no (bus, segment) pair is selected the button will be disabled.
Definition at line 530 of file SocketDialog.cc.
{
    if (connectedListCtrl_->GetSelectedItemCount() < 1) {
        FindWindow(ID_DETACH)->Disable();
        return;
    }
    FindWindow(ID_DETACH)->Enable();
}
References connectedListCtrl_, and ID_DETACH.
Referenced by onDetach().
onDetach()
void SocketDialog::onDetach (wxCommandEvent &) private
Detaches selected segments on the connection list from the socket.
Definition at line 419 of file SocketDialog.cc.
{
    long item = -1;
    item = connectedListCtrl_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    // Detach socket from all selected segments.
    while (item != -1) {
        Segment* seg = segment(connectedListCtrl_, item);
        assert(seg != NULL);
        socket_->detachBus(*seg);
        item = connectedListCtrl_->GetNextItem(
            item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    }
    updateConnected();
    updateDirection();
    wxListEvent dummy;
    onAttachedSelection(dummy);
}
References assert, connectedListCtrl_, TTAMachine::Socket::detachBus(), dummy, onAttachedSelection(), segment(), socket_, updateConnected(), and updateDirection().
onDetachedSelection()
void SocketDialog::onDetachedSelection (wxListEvent &) private
Disables and enables Attach button under the connected list.
If a (bus, segment) pair is selected, button is enabled. If no (bus, segment) pair is selected the button will be disabled.
Definition at line 546 of file SocketDialog.cc.
{
    if (segmentListCtrl_->GetSelectedItemCount() < 1) {
        FindWindow(ID_ATTACH)->Disable();
        return;
    }
    FindWindow(ID_ATTACH)->Enable();
}
References ID_ATTACH, and segmentListCtrl_.
Referenced by onAttach().
onDirection()
void SocketDialog::onDirection (wxCommandEvent &) private
Checks whether socket direction can be changed.
Due to the port connections to the sockets it might be impossible. If the socket is connected to the port already containing a connection to socket of this direction, changing the direction is not allowed.
Definition at line 315 of file SocketDialog.cc.
{
    wxString direction = directionBox_->GetStringSelection();
    if (direction.IsSameAs(ProDeConstants::SOCKET_DIRECTION_INPUT) &&
        !tester_->canSetDirection(*socket_, Socket::INPUT)) {
        // It wasn't legal to change the direction to input,
        // display an error message.
        string message =
            MachineTestReporter::socketDirectionSettingError(
                *socket_, Socket::INPUT, *tester_);
        WarningDialog dialog(this, WxConversion::toWxString(message));
        dialog.ShowModal();
        directionBox_->SetStringSelection(
            ProDeConstants::SOCKET_DIRECTION_OUTPUT);
    } else if(direction.IsSameAs(ProDeConstants::SOCKET_DIRECTION_OUTPUT) &&
        !tester_->canSetDirection(*socket_, Socket::OUTPUT)) {
        // It wasn't legal to change the direction to output,
        // display an error message.
        string message =
            MachineTestReporter::socketDirectionSettingError(
                *socket_, Socket::OUTPUT, *tester_);
        WarningDialog dialog(this, WxConversion::toWxString(message));
        dialog.ShowModal();
        directionBox_->SetStringSelection(
            ProDeConstants::SOCKET_DIRECTION_INPUT);
    }
    direction = directionBox_->GetStringSelection();
    if (direction.IsSameAs(ProDeConstants::SOCKET_DIRECTION_INPUT)) {
        socket_->setDirection(Socket::INPUT);
    }
    if (direction.IsSameAs(ProDeConstants::SOCKET_DIRECTION_OUTPUT)) {
        socket_->setDirection(Socket::OUTPUT);
    }
}
References MachineTester::canSetDirection(), directionBox_, TTAMachine::Socket::INPUT, TTAMachine::Socket::OUTPUT, TTAMachine::Socket::setDirection(), socket_, ProDeConstants::SOCKET_DIRECTION_INPUT, ProDeConstants::SOCKET_DIRECTION_OUTPUT, MachineTestReporter::socketDirectionSettingError(), tester_, and WxConversion::toWxString().
onHelp()
void SocketDialog::onHelp (wxCommandEvent & event) private
onName()
void SocketDialog::onName (wxCommandEvent &) private
Enables and disables OK button based on input in the socket name.
Definition at line 293 of file SocketDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void SocketDialog::onOK (wxCommandEvent &) private
Validates input in the controls, and updates the Socket.
Definition at line 236 of file SocketDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (trimmedName != socket_->name()) {
        Machine::SocketNavigator navigator =
            socket_->machine()->socketNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            Socket* socket = navigator.item(i);
            if (trimmedName == socket->name()) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_soc =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_SOCKET);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format soc =
                    prodeTexts->text(ProDeTextGenerator::COMP_SOCKET);
                message %
                    trimmedName % a_soc.str() % machine.str() % soc.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    socket_->setName(trimmedName);
    EndModal(wxID_OK);
}
References ProDeTextGenerator::COMP_A_SOCKET, ProDeTextGenerator::COMP_MACHINE, ProDeTextGenerator::COMP_SOCKET, TTAMachine::Machine::Navigator< ComponentType >::count(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::Socket::setName(), socket_, TTAMachine::Machine::socketNavigator(), Texts::TextGenerator::text(), WxConversion::toString(), and WxConversion::toWxString().
segment()
Segment * SocketDialog::segment (wxListCtrl * listCtrl, int index) private
Returns pointer to a segment with given index on a list.
Parameters
listCtrl List containing the segment.
index List index of the segment.
Returns
Pointer to the segment.
Definition at line 449 of file SocketDialog.cc.
{
    wxListItem busItem;
    busItem.SetId(index);
    busItem.SetColumn(0);
    listCtrl->GetItem(busItem);
    string busName = WxConversion::toString(busItem.GetText());
    wxListItem segItem;
    segItem.SetId(index);
    segItem.SetColumn(1);
    listCtrl->GetItem(segItem);
    string segmentName = WxConversion::toString(segItem.GetText());
    Machine::BusNavigator navigator = socket_->machine()->busNavigator();
    Segment* segment = navigator.item(busName)->segment(segmentName);
    return segment;
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), segment(), socket_, and WxConversion::toString().
Referenced by onAttach(), onDetach(), segment(), and updateConnected().
setTexts()
void SocketDialog::setTexts () private
Sets texts for widgets.
Definition at line 139 of file SocketDialog.cc.
                       {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_SOCKET_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_ATTACH),
                          ProDeTextGenerator::TXT_BUTTON_ATTACH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_DETACH),
                          ProDeTextGenerator::TXT_BUTTON_DETACH);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_DIRECTION),
                          ProDeTextGenerator::TXT_LABEL_DIRECTION);
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_SOCKET_ATTACHED_BOX);
    WidgetTools::setWidgetLabel(attachedSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_SOCKET_DETACHED_BOX);
    WidgetTools::setWidgetLabel(detachedSizer_, fmt.str());
    // Create list columns.
    wxListCtrl* attachedList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_ATTACHED_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_BUS);
    attachedList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_SEGMENT);
    attachedList->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 80);
    wxListCtrl* detachedList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_DETACHED_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_BUS);
    detachedList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_SEGMENT);
    detachedList->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 80);
    // Radio button labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_DIRECTION_INPUT);
    directionBox_->SetString(0, WxConversion::toWxString(fmt.str()));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_DIRECTION_OUTPUT);
    directionBox_->SetString(1, WxConversion::toWxString(fmt.str()));
}
References attachedSizer_, detachedSizer_, directionBox_, ID_ATTACH, ID_ATTACHED_LIST, ID_DETACH, ID_DETACHED_LIST, ID_DIRECTION, ID_HELP, ID_LABEL_NAME, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_BUTTON_ATTACH, GUITextGenerator::TXT_BUTTON_CANCEL, ProDeTextGenerator::TXT_BUTTON_DETACH, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_BUS, ProDeTextGenerator::TXT_COLUMN_SEGMENT, ProDeTextGenerator::TXT_LABEL_DIRECTION, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_RADIO_DIRECTION_INPUT, ProDeTextGenerator::TXT_RADIO_DIRECTION_OUTPUT, ProDeTextGenerator::TXT_SOCKET_ATTACHED_BOX, ProDeTextGenerator::TXT_SOCKET_DETACHED_BOX, and ProDeTextGenerator::TXT_SOCKET_DIALOG_TITLE.
TransferDataToWindow()
bool SocketDialog::TransferDataToWindow () private virtual
Transfers data from the socket object to the dialog widgets.
Definition at line 208 of file SocketDialog.cc.
{
    // Socket direction.
    updateDirection();
    updateConnected();
    return wxDialog::TransferDataToWindow();
}
References updateConnected(), and updateDirection().
updateConnected()
void SocketDialog::updateConnected () private
Updates connected list elements.
Definition at line 474 of file SocketDialog.cc.
{
    connectedListCtrl_->DeleteAllItems();
    segmentListCtrl_->DeleteAllItems();
    // update connections list
    for (int i = 0; i < socket_->segmentCount(); i++) {
        Segment* segment = socket_->segment(i);
        wxString segmentName =
            WxConversion::toWxString(segment->name());
        wxString busName =
            WxConversion::toWxString(segment->parentBus()->name());
        connectedListCtrl_->InsertItem(i, busName);
        connectedListCtrl_->SetItem(i, 1, segmentName);
    }
    // update list of segments available for connection
    Machine::BusNavigator navigator = socket_->machine()->busNavigator();
    int segments = 0;
    for (int i = 0; i < navigator.count(); i++) {
        Bus* bus = navigator.item(i);
        for (int j = 0; j < bus->segmentCount(); j++) {
            Segment* segment = bus->segment(j);
            if (tester_->canConnect(*socket_, *segment)) {
                wxString segmentName =
                    WxConversion::toWxString(segment->name());
                wxString busName =
                    WxConversion::toWxString(segment->parentBus()->name());
                segmentListCtrl_->InsertItem(segments, busName);
                segmentListCtrl_->SetItem(segments, 1, segmentName);
                segments++;
            }
        }
    }
    // Disable the direction control if the socket is not
    // connected to a bus.
    if (socket_->segmentCount() > 0) {
        FindWindow(ID_DIRECTION)->Enable();
    } else {
        FindWindow(ID_DIRECTION)->Disable();
    }
}
References TTAMachine::Machine::busNavigator(), MachineTester::canConnect(), connectedListCtrl_, TTAMachine::Machine::Navigator< ComponentType >::count(), ID_DIRECTION, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::Segment::name(), TTAMachine::Segment::parentBus(), TTAMachine::Bus::segment(), TTAMachine::Socket::segment(), segment(), TTAMachine::Bus::segmentCount(), TTAMachine::Socket::segmentCount(), segmentListCtrl_, socket_, tester_, and WxConversion::toWxString().
Referenced by onAttach(), onDetach(), and TransferDataToWindow().
updateDirection()
void SocketDialog::updateDirection () private
Updates the direction choicer.
Definition at line 220 of file SocketDialog.cc.
{
    if (socket_->direction() == Socket::INPUT) {
        directionBox_->SetStringSelection(
            ProDeConstants::SOCKET_DIRECTION_INPUT);
    } else if (socket_->direction() == Socket::OUTPUT) {
        directionBox_->SetStringSelection(
            ProDeConstants::SOCKET_DIRECTION_OUTPUT);
    }
}
References TTAMachine::Socket::direction(), directionBox_, TTAMachine::Socket::INPUT, TTAMachine::Socket::OUTPUT, socket_, ProDeConstants::SOCKET_DIRECTION_INPUT, and ProDeConstants::SOCKET_DIRECTION_OUTPUT.
Referenced by onAttach(), onDetach(), and TransferDataToWindow().
Member Data Documentation
attachedSizer_
wxStaticBoxSizer* SocketDialog::attachedSizer_ private
Static boxsizer containing the list of attached buses.
Definition at line 84 of file SocketDialog.hh.
Referenced by createContents(), and setTexts().
connectedListCtrl_
wxListCtrl* SocketDialog::connectedListCtrl_ private
List control for connected (bus, segment) pairs.
Definition at line 80 of file SocketDialog.hh.
Referenced by onAttachedSelection(), onDetach(), and updateConnected().
detachedSizer_
wxStaticBoxSizer* SocketDialog::detachedSizer_ private
Static boxsizer containing the list of detached buses.
Definition at line 86 of file SocketDialog.hh.
Referenced by createContents(), and setTexts().
directionBox_
wxRadioBox* SocketDialog::directionBox_ private
Radio box for direction.
Definition at line 78 of file SocketDialog.hh.
Referenced by onDirection(), setTexts(), and updateDirection().
name_
wxString SocketDialog::name_ private
Name of the socket.
Definition at line 74 of file SocketDialog.hh.
Referenced by onName(), and onOK().
segmentListCtrl_
wxListCtrl* SocketDialog::segmentListCtrl_ private
List control for all (bus, segment) pairs.
Definition at line 82 of file SocketDialog.hh.
Referenced by onAttach(), onDetachedSelection(), and updateConnected().
socket_
TTAMachine::Socket* SocketDialog::socket_ private
Socket to modify.
Definition at line 72 of file SocketDialog.hh.
Referenced by onAttach(), onDetach(), onDirection(), onOK(), segment(), updateConnected(), and updateDirection().
tester_
MachineTester* SocketDialog::tester_ private
MachineTester which does sanity checks for the target machine.
Definition at line 76 of file SocketDialog.hh.
Referenced by onDirection(), updateConnected(), and ~SocketDialog().
The documentation for this class was generated from the following files:
SocketDialog.hh
SocketDialog.cc