OpenASIP: TPEF::RawSection Class Reference
TPEF::RawSection Class Reference
#include <Section.hh>
Public Member Functions
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
virtual void assureInSection (SectionOffset offset) const
virtual ~RawSection ()
bool empty () const
virtual void setLengthInMAUs (Word length)
virtual Word lengthInMAUs () const
virtual void setDataLength (Word length)
virtual Word length () const
virtual Word bytesToMAUs (Word byteCount) const
virtual Word MAUsToBytes (Word mauCount) const
virtual Word chunkToMAUIndex (const Chunk *chunk) const
Word referredChunkCount () const
Chunk * referredChunk (Word index) const
bool belongsToSection (const Chunk *chunk) const
Public Member Functions inherited from TPEF::Section
virtual SectionType type () const =0
Returns SectioType of actual section instance.
virtual ~Section ()
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
RawSection ()
Protected Member Functions inherited from TPEF::Section
virtual Section * clone () const =0
Creates clone of instance.
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Types
typedef std::map< SectionOffset, Chunk * > ChunkMap
Type of map that contains chunks.
Private Member Functions
RawSection (const RawSection &)
Private Attributes
Word length_
The length of raw data section.
ChunkMap dataChunks_
Container for already created chunks.
std::vector< Chunk * > referredChunksCache_
Table containing all the chunks that are requested from section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Abstract base class for sections that stores raw data.
These sections are chunkable, that is they can create elements (chunks) on demand. These chunks point (using offsets) to section's raw data.
Definition at line 196 of file Section.hh.
Member Typedef Documentation
ChunkMap
typedef std::map<SectionOffset, Chunk*> TPEF::RawSection::ChunkMap private
Type of map that contains chunks.
Definition at line 234 of file Section.hh.
Constructor & Destructor Documentation
~RawSection()
TPEF::RawSection::~RawSection () virtual
Destructor.
Definition at line 186 of file Section.cc.
{
    MapTools::deleteAllValues(dataChunks_);
}
References dataChunks_, and MapTools::deleteAllValues().
RawSection() [1/2]
TPEF::RawSection::RawSection () protected
Constructor.
Definition at line 180 of file Section.cc.
                       : Section(), length_(0) {
}
RawSection() [2/2]
TPEF::RawSection::RawSection (const RawSection &) private
Member Function Documentation
assureInSection()
void TPEF::RawSection::assureInSection (SectionOffset offset) const virtual
Checks that section is not indexed out of bounds.
If section is indexed out of bounds, exception is thrown.
Parameters
offset The offset being checked that it is in the area of section.
Exceptions
OutOfRange if not in area of section.
Definition at line 354 of file Section.cc.
{
    if (offset >= length())
        throw OutOfRange(__FILE__, __LINE__, __func__);
}
References __func__, and length().
Referenced by chunk().
belongsToSection()
bool TPEF::RawSection::belongsToSection (const Chunk * chunk) const
Returns true if the chunk in parameter belongs to this section.
Parameters
chunk Chunk that is checked.
Returns
True if the chunk in parameter belongs to this section.
Definition at line 238 of file Section.cc.
{
    if (MapTools::containsKey(dataChunks_, chunk->offset())) {
        return dataChunks_[chunk->offset()] == chunk;
    }
    return false;
}
References chunk(), MapTools::containsKey(), dataChunks_, and TPEF::Chunk::offset().
Referenced by TTAProgram::TPEFProgramFactory::createDataMemories(), and TPEFDumper::section().
bytesToMAUs()
Word TPEF::RawSection::bytesToMAUs (Word bytes) const virtual
Returns how many MAUs is amount of bytes described in parameter.
Parameters
bytes Number of bytes to convert.
Returns
Number of MAUs.
Definition at line 296 of file Section.cc.
{
    assert(aSpace() != NULL);
    if (aSpace()->MAU() == 0) {
        abortWithError("MAU of address space can't be zero.");
    }
    Word mauSize = static_cast<Word>(
        ceil(static_cast<double>(aSpace()->MAU()) /
             static_cast<double>(BYTE_BITWIDTH)));
    // must be even
    assert ((bytes % mauSize) == 0);
    return bytes / mauSize;
}
References abortWithError, TPEF::Section::aSpace(), assert, and BYTE_BITWIDTH.
Referenced by chunkToMAUIndex(), TTAProgram::TPEFProgramFactory::createLabels(), and lengthInMAUs().
chunk()
Chunk * TPEF::RawSection::chunk (SectionOffset offset) const virtual
Returns a chunk object to data in the section at a given offset.
Checks that there is something in the section before returning chunk. In the other words, Chunks can not be given from outside of section's data.
Parameters
offset The offset of wanted data chunk.
Returns
Chunk pointing data.
Exceptions
NotChunkable If called on a section that is not RawSection.
Reimplemented from TPEF::Section.
Definition at line 212 of file Section.cc.
{
    Chunk* newChunk = NULL;
    try {
        assureInSection(offset);
    } catch (const OutOfRange& e) {
        throw NotChunkable(__FILE__, __LINE__, __func__, e.errorMessage());
    }
    if (!MapTools::containsKey(dataChunks_, offset)) {
        newChunk = new Chunk(offset);
        dataChunks_[offset]  = newChunk;
        referredChunksCache_.clear();
    } else {
        newChunk = dataChunks_[offset];
    }
    return newChunk;
}
References __func__, assureInSection(), MapTools::containsKey(), dataChunks_, Exception::errorMessage(), and referredChunksCache_.
Referenced by TPEF::TPEFDataSectionWriter::actualWriteData(), TPEF::TPEFStringSectionWriter::actualWriteData(), belongsToSection(), TPEF::DataSection::byte(), TPEF::StringSection::chunk2String(), chunkToMAUIndex(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TPEF::TPEFUDataSectionWriter::createKeys(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::createSymbolWithReference(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutStringSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), TPEF::TPEFTools::sectionOfElement(), TPEF::StringSection::string2Chunk(), and DataSectionCreator::writeDataLineToTPEF().
chunkToMAUIndex()
Word TPEF::RawSection::chunkToMAUIndex (const Chunk * chunk) const virtual
Returns MAU index to given chunk.
Parameters
chunk Chunk whose MAU index should be found.
Returns
MAU index to data referred by the chunk.
Definition at line 341 of file Section.cc.
{
    return bytesToMAUs(chunk->offset());
}
References bytesToMAUs(), chunk(), and TPEF::Chunk::offset().
Referenced by TTAProgram::TPEFProgramFactory::createDataMemories(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), and TPEFDumper::section().
empty()
bool TPEF::RawSection::empty () const
Referenced by TPEF::TPEFStringSectionReader::readData().
isChunkable()
bool TPEF::RawSection::isChunkable () const virtual
Returns true if section is chunkable.
Returns
True if section is chunkable.
Reimplemented from TPEF::Section.
Definition at line 196 of file Section.cc.
{
    return true;
}
length()
Word TPEF::RawSection::length () const virtual
Returns length of data inside section.
Returns
Length of data inside section.
Reimplemented in TPEF::DataSection.
Definition at line 275 of file Section.cc.
{
    return length_;
}
References length_.
Referenced by assureInSection(), lengthInMAUs(), TPEF::TPEFTools::sectionOfElement(), setDataLength(), setLengthInMAUs(), and TPEF::TPEFUDataSectionWriter::writeSize().
lengthInMAUs()
Word TPEF::RawSection::lengthInMAUs () const virtual
Returns length of data section in MAUs.
Returns
Length of data inside sect.
Definition at line 285 of file Section.cc.
{
    return bytesToMAUs(length());
}
References bytesToMAUs(), and length().
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), and TPEFDumper::section().
MAUsToBytes()
Word TPEF::RawSection::MAUsToBytes (Word maus) const virtual
Returns how many bytes some amount of MAUs are.
Parameters
maus Number of MAUs to convert.
Returns
Number of bytes that are needed for storing some amount of MAUs.
Definition at line 320 of file Section.cc.
{
    assert(aSpace() != NULL);
    if (aSpace()->MAU() == 0) {
        abortWithError("MAU of address space can't be zero for this method.");
    }
    Word mauSize = static_cast<Word>(
        ceil(static_cast<double>(aSpace()->MAU()) /
             static_cast<double>(BYTE_BITWIDTH)));
    return maus * mauSize;
}
References abortWithError, TPEF::Section::aSpace(), assert, and BYTE_BITWIDTH.
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::createSymbolWithReference(), LabelManager::finalize(), TPEF::DataSection::MAU(), setLengthInMAUs(), DataSectionCreator::writeDataLineToTPEF(), TPEF::DataSection::writeValue(), TPEF::LEDataSection::writeValue(), TPEF::DataSection::writeValue(), and TPEF::LEDataSection::writeValue().
referredChunk()
Chunk * TPEF::RawSection::referredChunk (Word index) const
Returns chunks that is requested from section before.
Parameters
Index of chunk to return.
Returns
Chunk to return.
Definition at line 378 of file Section.cc.
{
    if (referredChunksCache_.empty()) {
    ChunkMap::iterator iter = dataChunks_.begin();
    while (iter != dataChunks_.end()) {
        referredChunksCache_.push_back((*iter).second);
        iter++;
    }
    }
    return referredChunksCache_[index];
}
References dataChunks_, and referredChunksCache_.
Referenced by TPEF::TPEFUDataSectionWriter::createKeys().
referredChunkCount()
Word TPEF::RawSection::referredChunkCount () const
Returns number of chunks that are requested from section.
Returns
Number of requested chunks.
Definition at line 366 of file Section.cc.
{
    return dataChunks_.size();
}
References dataChunks_.
Referenced by TPEF::TPEFUDataSectionWriter::createKeys().
setDataLength()
void TPEF::RawSection::setDataLength (Word length) virtual
Sets the length of section's data.
Parameters
length bytes of data in section.
Reimplemented in TPEF::DataSection.
Definition at line 253 of file Section.cc.
{
    // should this method be overrided to throw exception if
    // called with DataSection or StringSection classes
    length_ = length;
}
References length(), and length_.
Referenced by TPEF::AOutReader::readData(), TPEF::TPEFUDataSectionReader::readData(), and setLengthInMAUs().
setLengthInMAUs()
void TPEF::RawSection::setLengthInMAUs (Word length) virtual
Sets the length of section's data.
Parameters
length Section length in MAUs.
Definition at line 265 of file Section.cc.
{
    setDataLength(MAUsToBytes(length));
}
References length(), MAUsToBytes(), and setDataLength().
Referenced by TTAProgram::ProgramWriter::createDataSections(), and DataSectionCreator::finalize().
Member Data Documentation
dataChunks_
ChunkMap TPEF::RawSection::dataChunks_ mutable private
Container for already created chunks.
Definition at line 237 of file Section.hh.
Referenced by belongsToSection(), chunk(), referredChunk(), referredChunkCount(), and ~RawSection().
length_
Word TPEF::RawSection::length_ private
The length of raw data section.
Definition at line 231 of file Section.hh.
Referenced by length(), and setDataLength().
referredChunksCache_
std::vector<Chunk*> TPEF::RawSection::referredChunksCache_ mutable private
Table containing all the chunks that are requested from section.
Definition at line 240 of file Section.hh.
Referenced by chunk(), and referredChunk().
The documentation for this class was generated from the following files:
Section.hh
Section.cc