OpenASIP: SimulatorEvent Class Reference
SimulatorEvent Class Reference
#include <SimulatorEvent.hh>
Public Member Functions
SimulatorEvent (WXTYPE eventType, std::string data="")
virtual ~SimulatorEvent ()
virtual wxEvent * Clone (void) const
std::string data () const
Static Public Attributes
static const wxEventType EVT_SIMULATOR_COMMAND = wxNewEventType()
Command received from the GUI.
static const wxEventType EVT_SIMULATOR_COMMAND_DONE
Command execution completed.
static const wxEventType EVT_SIMULATOR_TERMINATED = wxNewEventType()
Simulator thread terminated.
static const wxEventType EVT_SIMULATOR_OUTPUT = wxNewEventType()
Textual output event from simulator interpreter.
static const wxEventType EVT_SIMULATOR_ERROR = wxNewEventType()
Simulator error event.
static const wxEventType EVT_SIMULATOR_RUNTIME_ERROR
Runtime error event.
static const wxEventType EVT_SIMULATOR_RUNTIME_WARNING
Runtime warning event.
static const wxEventType EVT_SIMULATOR_START = wxNewEventType()
Simulation started.
static const wxEventType EVT_SIMULATOR_STOP = wxNewEventType()
Simulation stopped.
static const wxEventType EVT_SIMULATOR_RUN = wxNewEventType()
Simulation ran/resumed.
static const wxEventType EVT_SIMULATOR_LOADING_MACHINE
Machine loading started.
static const wxEventType EVT_SIMULATOR_MACHINE_LOADED
Machine loaded event.
static const wxEventType EVT_SIMULATOR_LOADING_PROGRAM
Program loading started.
static const wxEventType EVT_SIMULATOR_PROGRAM_LOADED
Program loaded event.
static const wxEventType EVT_SIMULATOR_RESET = wxNewEventType()
Sent before program,machine or memory model is destroyed.
Private Attributes
std::string data_
Detailed Description
A custom wxEvent class for passing simulator events to Proxim windows.
Definition at line 42 of file SimulatorEvent.hh.
Constructor & Destructor Documentation
SimulatorEvent()
SimulatorEvent::SimulatorEvent (WXTYPE eventType, std::string data = "")
The Constructor.
Parameters
eventType Event type ID.
data String data associated with the event.
Definition at line 66 of file SimulatorEvent.cc.
                                                               :
    wxEvent(0, eventType), data_(data) {
}
~SimulatorEvent()
SimulatorEvent::~SimulatorEvent () virtual
The Destructor.
Definition at line 75 of file SimulatorEvent.cc.
{
}
Member Function Documentation
Clone()
virtual wxEvent * SimulatorEvent::Clone (void) const inline virtual
Definition at line 46 of file SimulatorEvent.hh.
{ return new SimulatorEvent(*this); }
data()
std::string SimulatorEvent::data () const
Returns string data of the event.
Returns
String data associated with the event.
Definition at line 85 of file SimulatorEvent.cc.
{
    return data_;
}
References data_.
Referenced by ProximMainFrame::onSimulatorEvent().
Member Data Documentation
data_
std::string SimulatorEvent::data_ private
Definition at line 89 of file SimulatorEvent.hh.
Referenced by data().
EVT_SIMULATOR_COMMAND
const wxEventType SimulatorEvent::EVT_SIMULATOR_COMMAND = wxNewEventType() static
Command received from the GUI.
Definition at line 53 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::Entry(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_COMMAND_DONE
const wxEventType SimulatorEvent::EVT_SIMULATOR_COMMAND_DONE static
Initial value:
=
    wxNewEventType()
Command execution completed.
Definition at line 55 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::Entry(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_ERROR
const wxEventType SimulatorEvent::EVT_SIMULATOR_ERROR = wxNewEventType() static
Simulator error event.
Definition at line 62 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::Entry().
EVT_SIMULATOR_LOADING_MACHINE
const wxEventType SimulatorEvent::EVT_SIMULATOR_LOADING_MACHINE static
Initial value:
=
    wxNewEventType()
Machine loading started.
Definition at line 77 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_LOADING_PROGRAM
const wxEventType SimulatorEvent::EVT_SIMULATOR_LOADING_PROGRAM static
Initial value:
=
    wxNewEventType()
Program loading started.
Definition at line 81 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_MACHINE_LOADED
const wxEventType SimulatorEvent::EVT_SIMULATOR_MACHINE_LOADED static
Initial value:
=
    wxNewEventType()
Machine loaded event.
Definition at line 79 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_OUTPUT
const wxEventType SimulatorEvent::EVT_SIMULATOR_OUTPUT = wxNewEventType() static
Textual output event from simulator interpreter.
Definition at line 60 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::Entry(), and ProximLineReader::output().
EVT_SIMULATOR_PROGRAM_LOADED
const wxEventType SimulatorEvent::EVT_SIMULATOR_PROGRAM_LOADED static
Initial value:
=
    wxNewEventType()
Program loaded event.
Definition at line 83 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_RESET
const wxEventType SimulatorEvent::EVT_SIMULATOR_RESET = wxNewEventType() static
Sent before program,machine or memory model is destroyed.
Definition at line 85 of file SimulatorEvent.hh.
Referenced by ProximMainFrame::reset().
EVT_SIMULATOR_RUN
const wxEventType SimulatorEvent::EVT_SIMULATOR_RUN = wxNewEventType() static
Simulation ran/resumed.
Definition at line 73 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_RUNTIME_ERROR
const wxEventType SimulatorEvent::EVT_SIMULATOR_RUNTIME_ERROR static
Initial value:
=
    wxNewEventType()
Runtime error event.
Definition at line 64 of file SimulatorEvent.hh.
Referenced by ProximRuntimeErrorHandler::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_RUNTIME_WARNING
const wxEventType SimulatorEvent::EVT_SIMULATOR_RUNTIME_WARNING static
Initial value:
=
    wxNewEventType()
Runtime warning event.
Definition at line 66 of file SimulatorEvent.hh.
Referenced by ProximRuntimeErrorHandler::handleEvent(), and ProximMainFrame::onSimulatorEvent().
EVT_SIMULATOR_START
const wxEventType SimulatorEvent::EVT_SIMULATOR_START = wxNewEventType() static
Simulation started.
Definition at line 69 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent().
EVT_SIMULATOR_STOP
const wxEventType SimulatorEvent::EVT_SIMULATOR_STOP = wxNewEventType() static
Simulation stopped.
Definition at line 71 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::handleEvent(), ProximSimulationThread::killSimulation(), and ProximSimulationThread::requestStop().
EVT_SIMULATOR_TERMINATED
const wxEventType SimulatorEvent::EVT_SIMULATOR_TERMINATED = wxNewEventType() static
Simulator thread terminated.
Definition at line 57 of file SimulatorEvent.hh.
Referenced by ProximSimulationThread::Entry().
The documentation for this class was generated from the following files:
SimulatorEvent.hh
SimulatorEvent.cc