OpenASIP: TTAProgram::TerminalImmediate Class Reference
TTAProgram::TerminalImmediate Class Reference
#include <TerminalImmediate.hh>
Public Member Functions
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
virtual SimValue value () const
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Protected Attributes
SimValue value_
Value of the inline immediate.
Private Member Functions
TerminalImmediate & operator= (const TerminalImmediate &)
Assignment not allowed.
Detailed Description
Represents an inline immediate.
Definition at line 44 of file TerminalImmediate.hh.
Constructor & Destructor Documentation
TerminalImmediate()
TTAProgram::TerminalImmediate::TerminalImmediate (SimValue value)
The constructor.
Parameters
value The value of the inline immediate.
Definition at line 48 of file TerminalImmediate.cc.
                                                  :
    value_(value) {
}
~TerminalImmediate()
TTAProgram::TerminalImmediate::~TerminalImmediate () virtual
The destructor.
Definition at line 55 of file TerminalImmediate.cc.
{
}
Member Function Documentation
copy()
Terminal * TTAProgram::TerminalImmediate::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Implements TTAProgram::Terminal.
Reimplemented in TTAProgram::TerminalAddress, TTAProgram::TerminalBasicBlockReference, TTAProgram::TerminalInstructionReference, TTAProgram::TerminalLaneIDImmediate, TTAProgram::TerminalProgramOperation, TTAProgram::TerminalSymbolReference, and TTAProgram::TerminalInstructionAddress.
Definition at line 85 of file TerminalImmediate.cc.
{
    return new TerminalImmediate(value_);
}
References value_.
Referenced by TTAProgram::Immediate::copy().
equals()
bool TTAProgram::TerminalImmediate::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Implements TTAProgram::Terminal.
Reimplemented in TTAProgram::TerminalAddress, TTAProgram::TerminalBasicBlockReference, TTAProgram::TerminalInstructionReference, TTAProgram::TerminalLaneIDImmediate, TTAProgram::TerminalProgramOperation, TTAProgram::TerminalSymbolReference, and TTAProgram::TerminalInstructionAddress.
Definition at line 96 of file TerminalImmediate.cc.
{
    if (other.isImmediate() != true) {
        return false;
    }
    if (typeid(*this) != typeid(other)) {
        return false;
    }
    return value() == other.value();
}
References TTAProgram::Terminal::isImmediate(), TTAProgram::Terminal::value(), and value().
isImmediate()
bool TTAProgram::TerminalImmediate::isImmediate () const virtual
Tells whether the terminal is an inline immediate value.
Returns
true always.
Reimplemented from TTAProgram::Terminal.
Definition at line 64 of file TerminalImmediate.cc.
{
    return true;
}
operator=()
TerminalImmediate & TTAProgram::TerminalImmediate::operator= (const TerminalImmediate &) private
Assignment not allowed.
toString()
TCEString TTAProgram::TerminalImmediate::toString () const virtual
Implements TTAProgram::Terminal.
Reimplemented in TTAProgram::TerminalLaneIDImmediate, and TTAProgram::TerminalSymbolReference.
Definition at line 108 of file TerminalImmediate.cc.
{
    DisassemblyImmediate* disasm =
        POMDisassembler::createInlineImmediate(*this, false);
    TCEString dis = disasm->toString();
    delete disasm;
    return dis;
}
References POMDisassembler::createInlineImmediate(), and DisassemblyImmediate::toString().
Referenced by MachineConnectivityCheck::requiredImmediateWidth().
value()
SimValue TTAProgram::TerminalImmediate::value () const virtual
Returns the value of the inline immediate.
Returns
The value of the inline immediate.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Reimplemented in TTAProgram::TerminalBasicBlockReference, TTAProgram::TerminalInstructionAddress, TTAProgram::TerminalLaneIDImmediate, and TTAProgram::TerminalSymbolReference.
Definition at line 75 of file TerminalImmediate.cc.
{
    return value_;
}
References value_.
Referenced by ITemplateBroker::assign(), TTAProgram::TPEFProgramFactory::build(), POMValidator::checkLongImmediates(), TTAProgram::TerminalAddress::copy(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createImmediateAssignment(), CodeCompressorPlugin::encodeLongImmediate(), equals(), CompiledSimCodeGenerator::generateInstruction(), ProgramImageGenerator::generateProgramImage(), BUBasicBlockScheduler::handleLoopDDG(), ITemplateBroker::isImmediateInTemplate(), main(), SimProgramBuilder::processInstruction(), MachineConnectivityCheck::requiredImmediateWidth(), and BasicBlockScheduler::scheduleMove().
Member Data Documentation
value_
SimValue TTAProgram::TerminalImmediate::value_ protected
Value of the inline immediate.
Definition at line 62 of file TerminalImmediate.hh.
Referenced by TTAProgram::TerminalAddress::address(), copy(), and value().
The documentation for this class was generated from the following files:
TerminalImmediate.hh
TerminalImmediate.cc