OpenASIP: TTASimulatorCLI Class Reference
TTASimulatorCLI Class Reference
#include <TTASimulatorCLI.hh>
Public Member Functions
TTASimulatorCLI ()=delete
TTASimulatorCLI (SimulatorFrontend &frontend)
virtual ~TTASimulatorCLI ()
Public Member Functions inherited from SimulatorCLI
SimulatorCLI ()=delete
SimulatorCLI (SimulatorFrontend &frontend)
virtual ~SimulatorCLI ()
virtual void run ()
virtual void interpreteAndPrintResults (const TCEString &scriptString)
SimulatorInterpreter & interpreter ()
Additional Inherited Members
Protected Attributes inherited from SimulatorCLI
SimulatorFrontend & simFront_
SimulatorInterpreterContext * context_
LineReader * reader_
SimulatorInterpreter * interpreter_
SimulatorCmdLineOptions * options_
RuntimeErrorReporter * errorReporter_
Detailed Description
Definition at line 38 of file TTASimulatorCLI.hh.
Constructor & Destructor Documentation
TTASimulatorCLI() [1/2]
TTASimulatorCLI::TTASimulatorCLI () delete
TTASimulatorCLI() [2/2]
TTASimulatorCLI::TTASimulatorCLI (SimulatorFrontend & frontend)
Definition at line 40 of file TTASimulatorCLI.cc.
    : SimulatorCLI(frontend) {
    // check if there is an initialization file in user's home dir and
    // execute it
    const std::string personalInitScript =
        FileSystem::homeDirectory() + DIR_SEPARATOR + SIM_INIT_FILE_NAME;
    if (FileSystem::fileExists(personalInitScript)) {
        interpreter_->processScriptFile(personalInitScript);
    }
    // check if there is an initialization file in the current dir and
    // execute it
    const std::string currentDirInitScript =
        FileSystem::currentWorkingDir() + DIR_SEPARATOR + SIM_INIT_FILE_NAME;
    if (FileSystem::fileExists(currentDirInitScript)) {
        interpreter_->processScriptFile(currentDirInitScript);
    }
}
References FileSystem::currentWorkingDir(), FileSystem::fileExists(), FileSystem::homeDirectory(), SimulatorCLI::interpreter_, TclInterpreter::processScriptFile(), and SIM_INIT_FILE_NAME.
~TTASimulatorCLI()
TTASimulatorCLI::~TTASimulatorCLI () virtual
Definition at line 60 of file TTASimulatorCLI.cc.
{
}
The documentation for this class was generated from the following files:
TTASimulatorCLI.hh
TTASimulatorCLI.cc