OpenASIP: MoveNode Class Reference
MoveNode Class Reference
#include <MoveNode.hh>
Public Member Functions
MoveNode (std::shared_ptr< TTAProgram::Move > newMove)
MoveNode (std::shared_ptr< TTAProgram::Immediate > imm)
virtual ~MoveNode ()
MoveNode * copy ()
bool isSourceOperation () const
bool isGuardOperation () const
bool isDestinationOperation () const
unsigned int destinationOperationCount () const
bool isOperationMove () const
bool isSourceVariable () const
bool isSourceConstant () const
bool isSourceRA () const
bool isSourceImmediateRegister () const
bool isDestinationVariable () const
bool isBypass () const
bool isRegisterMove () const
bool inSameOperation (const MoveNode &other) const
bool isPlaced () const
bool isAssigned () const
bool isScheduled () const
void setCycle (const int newcycle)
void unsetCycle ()
int cycle () const
int earliestResultReadCycle () const
int latestTriggerWriteCycle () const
int guardLatency () const
Scope & scope ()
ProgramOperation & sourceOperation () const
ProgramOperation & guardOperation () const
ProgramOperation & destinationOperation (unsigned int index=0) const
ProgramOperationPtr guardOperationPtr () const
ProgramOperationPtr sourceOperationPtr () const
ProgramOperationPtr destinationOperationPtr (unsigned int index=0) const
std::shared_ptr< TTAProgram::Move > movePtr ()
std::shared_ptr< const TTAProgram::Move > movePtr () const
std::shared_ptr< TTAProgram::Immediate > immediatePtr ()
std::shared_ptr< const TTAProgram::Immediate > immediatePtr () const
TTAProgram::Move & move ()
const TTAProgram::Move & move () const
TTAProgram::Immediate & immediate ()
const TTAProgram::Immediate & immediate () const
void addDestinationOperationPtr (ProgramOperationPtr po)
void setSourceOperationPtr (ProgramOperationPtr po)
void setGuardOperationPtr (ProgramOperationPtr po)
void clearDestinationOperation ()
void removeDestinationOperation (const ProgramOperation *po)
void unsetSourceOperation ()
void unsetGuardOperation ()
void finalize ()
bool isFinalized () const
void setIsInFrontier (bool inFrontier=true)
bool isInFrontier () const
bool isLastUnscheduledMoveOfDstOp () const
int type ()
std::string toString () const
std::string dotString () const
bool isMove () const
bool isImmediate () const
bool isSourceReg (const std::string &reg) const
MoveNode ()
Node can be entry node.
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
virtual GraphNode * clone () const
int nodeID () const
Private Member Functions
MoveNode (const MoveNode &)
Copying forbidden. Use copy() for a deep copy.
MoveNode & operator= (const MoveNode &)
Assignment forbidden.
Private Attributes
const std::shared_ptr< TTAProgram::Move > move_
Pointer to Move this node represents, Node itself do not change move.
const std::shared_ptr< TTAProgram::Immediate > immediate_
Pointer to Immediate this node represents, Node itself do not change move.
std::vector< ProgramOperationPtr > dstOps_
ProgramOperationPtr srcOp_
ProgramOperationPtr guardOp_
int cycle_
Cycle in which the node is placed. Each cycle uniquely identifies an instruction slot within the current scheduling scope.
bool placed_
True when the node placed (is given a cycle in program).
bool finalized_
The movenode cannot be unscheduled anymore, fixed in place.
bool isInFrontier_
This is in scheduling frontier(used in Bubblefish scheduler)
Detailed Description
Node of the program representation.
A MoveNode represents one move of a TTA program.
Definition at line 65 of file MoveNode.hh.
Constructor & Destructor Documentation
MoveNode() [1/4]
MoveNode::MoveNode (std::shared_ptr< TTAProgram::Move > newMove) explicit
Constructor.
Creates a new node with a smart pointer to the given Move.
Parameters
newmove the Move this node refers to.
Definition at line 75 of file MoveNode.cc.
                                                        :
    move_(newMove), immediate_(nullptr), srcOp_(nullptr), guardOp_(nullptr),
    cycle_(0), placed_(false), finalized_(false), isInFrontier_(false) {
}
MoveNode() [2/4]
MoveNode::MoveNode (std::shared_ptr< TTAProgram::Immediate > imm) explicit
Constructor.
Creates a new node with a smart pointer to the given immediate.
Parameters
imm the long immediate this node refers to.
Definition at line 87 of file MoveNode.cc.
                                                         :
    move_(nullptr), immediate_(imm),  srcOp_(nullptr), guardOp_(nullptr),
    cycle_(0), placed_(false), finalized_(false), isInFrontier_(false) {
}
~MoveNode()
MoveNode::~MoveNode () virtual
Destructor.
Deletes the owned Move instance. Does not unregister this movenode from ProgramOperations.
Definition at line 110 of file MoveNode.cc.
                    {
    if (isSourceOperation()) {
        sourceOperation().removeOutputNode(*this);
    }
    if (isGuardOperation()) {
        guardOperation().removeGuardOutputNode(*this);
    }
    if (isDestinationOperation()) {
        for (unsigned int i = 0; i < destinationOperationCount(); i++) {
            destinationOperation(i).removeInputNode(*this);
        }
    }
}
References destinationOperation(), destinationOperationCount(), guardOperation(), isDestinationOperation(), isGuardOperation(), isSourceOperation(), ProgramOperation::removeGuardOutputNode(), ProgramOperation::removeInputNode(), ProgramOperation::removeOutputNode(), and sourceOperation().
MoveNode() [3/4]
MoveNode::MoveNode ()
Node can be entry node.
Constructor.
Creates a new node to be entry node.
Definition at line 99 of file MoveNode.cc.
                   :
    move_(nullptr), immediate_(nullptr), srcOp_(nullptr), guardOp_(nullptr),
    cycle_(0), placed_(false), finalized_(false), isInFrontier_(false) {
}
Referenced by copy().
MoveNode() [4/4]
MoveNode::MoveNode (const MoveNode &) private
Copying forbidden. Use copy() for a deep copy.
Member Function Documentation
addDestinationOperationPtr()
void MoveNode::addDestinationOperationPtr (ProgramOperationPtr po)
Set a destination of MoveNode to ProgramOperation
Parameters
po Program operation that is destination of MoveNode
Definition at line 533 of file MoveNode.cc.
{
    dstOps_.push_back(po);
}
References dstOps_.
Referenced by Peel2BBLoops::appendBB(), SimpleIfConverter::appendBB(), MoveNodeGroupBuilder::build(), copy(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::CodeGenerator::createForLoopBufferInit(), llvm::LLVMTCEIRBuilder::createMoveNode(), TTAProgram::CodeGenerator::createWhileLoopBufferInit(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), DataDependenceGraph::mergeAndKeepSource(), BFShareOperand::operator()(), DataDependenceGraphBuilder::processOperand(), DataDependenceGraphBuilder::processTriggerPO(), BFCopyRegWithOp::splitMove(), and BFShareOperand::undoOnlyMe().
clearDestinationOperation()
void MoveNode::clearDestinationOperation ()
Unsets destination operation.
Does not ask the ProgramOperation to remove this MoveNode from it's input moves.
Definition at line 730 of file MoveNode.cc.
{
    dstOps_.clear();
}
References dstOps_.
copy()
MoveNode * MoveNode::copy ()
Creates a deep copy of MoveNode.
Sets the source and destination operation of the copy to the same as original. Does not copy the cycle.
Returns
return copy of MoveNode.
Definition at line 135 of file MoveNode.cc.
               {
    MoveNode* newNode = NULL;
    if (move_ != NULL) {
        newNode = new MoveNode(move_->copy());
    } else {
        if (immediate_) {
            newNode = new MoveNode(immediate_->copy());
        } else {
            newNode = new MoveNode;
        }
    }
    if (isSourceOperation()) {
        sourceOperation().addOutputNode(*newNode);
        newNode->setSourceOperationPtr(sourceOperationPtr());
    }
    if (isDestinationOperation()) {
        for (unsigned int i = 0; i < destinationOperationCount(); i++) {
            destinationOperation(i).addInputNode(*newNode);
            newNode->addDestinationOperationPtr(destinationOperationPtr());
        }
    }
    return newNode;
}
References addDestinationOperationPtr(), ProgramOperation::addInputNode(), ProgramOperation::addOutputNode(), destinationOperation(), destinationOperationCount(), destinationOperationPtr(), immediate_, isDestinationOperation(), isSourceOperation(), move_, MoveNode(), setSourceOperationPtr(), sourceOperation(), and sourceOperationPtr().
Referenced by LoopPrologAndEpilogBuilder::build().
cycle()
int MoveNode::cycle () const
Returns the cycle (index) assigned to the node.
Returns
The cycle in which the node is placed.
Exceptions
InvalidData if the node is not placed.
Definition at line 421 of file MoveNode.cc.
                      {
    if (!isPlaced()){
        std::string msg = "MoveNode was not placed yet: " + toString();
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    } else {
        return cycle_;
    }
}
References __func__, cycle_, isPlaced(), and toString().
Referenced by ResourceConstraintAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), SimpleBrokerDirector::assign(), LoopPrologAndEpilogBuilder::build(), CycleLookBackSoftwareBypasser::bypass(), BUBasicBlockScheduler::bypassNode(), CycleLookBackSoftwareBypasser::bypassNode(), BFEarlyBypasser::bypassSourceLatestCycle(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignSource(), CopyingDelaySlotFiller::checkIncomingDeps(), ExecutionPipelineResource::checkOperandAllowed(), BFOptimization::checkPrologDDG(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), ResourceConstraintAnalyzer::dumpGraphWithStats(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), earliestResultReadCycle(), ExecutionPipelineResource::exclusiveMoves(), CopyingDelaySlotFiller::fillDelaySlots(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterKill(), DataDependenceGraph::firstScheduledRegisterRead(), DataDependenceGraph::firstScheduledRegisterReads(), DataDependenceGraph::firstScheduledRegisterWrite(), DataDependenceGraph::firstScheduledRegisterWrites(), BasicBlockScheduler::handleRemovedResultMoves(), IUResource::immediateValue(), IUResource::immediateWriteCycle(), BFOptimization::jumpGuardAvailableCycle(), DataDependenceGraph::largestCycle(), DataDependenceGraph::lastGuardDefMove(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), DataDependenceGraph::lastScheduledRegisterKill(), DataDependenceGraph::lastScheduledRegisterRead(), DataDependenceGraph::lastScheduledRegisterReads(), DataDependenceGraph::lastScheduledRegisterWrites(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), DataDependenceGraph::movesAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandsOverwritten(), ExecutionPipelineResource::operandTooLate(), BFEarlyBypasser::operator()(), BFLateBypass::operator()(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepsDown::operator()(), BFPushDepsUp::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultClose::operator()(), BFRescheduleResultsClose::operator()(), BFShareOperandLate::operator()(), BFShareOperandsLate::operator()(), BFShareOperandWithScheduled::operator()(), BFPostpassBypass::operator()(), BFRemoveGuardFromSucc::operator()(), BFRemoveGuardsFromSuccs::operator()(), BUBasicBlockScheduler::ltstr::operator()(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), BF2ScheduleFront::prefResultCycle(), LiveRangeData::registersAlive(), ExecutionPipelineResource::resultReadyCycle(), BasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperand(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleResultReadTempMoves(), BasicBlockScheduler::scheduleRRTempMoves(), BUBasicBlockScheduler::scheduleRRTempMoves(), AssignmentPlan::setRequest(), DataDependenceGraph::smallestCycle(), ExecutionPipelineResource::testTriggerResult(), toString(), ExecutionPipelineResource::triggerTooEarly(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToDelayOperands(), BasicBlockScheduler::tryToOptimizeWaw(), IUResource::unassign(), BFOptimization::unassign(), BusBroker::unassign(), InputFUBroker::unassign(), InputPSocketBroker::unassign(), ITemplateBroker::unassign(), IUBroker::unassign(), OutputFUBroker::unassign(), OutputPSocketBroker::unassign(), SimpleBrokerDirector::unassign(), ExecutionPipelineResource::unassignSource(), BFShareOperandLate::undoOnlyMe(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), and DataDependenceGraph::writeToXMLFile().
destinationOperation()
ProgramOperation & MoveNode::destinationOperation (unsigned int index = 0) const
Referenced by InputFUBroker::allAvailableResources(), BF2ScheduleFront::allNodesOfSameOperation(), ResourceConstraintAnalyzer::analyzeMoveNode(), Peel2BBLoops::appendBB(), BFOptimization::assign(), BFOptimization::assignCopyToPrologEpilog(), ExecutionPipelineResource::assignDestination(), MachineConnectivityCheck::busConnectedToAnyFU(), BusResource::canAssign(), BFOptimization::canAssign(), ExecutionPipelineResource::canAssignDestination(), BFOptimization::canBeSpeculated(), DataDependenceGraphBuilder::checkAndCreateMemDep(), PreOptimizer::checkGuardReversalAllowed(), ExecutionPipelineResource::checkOperandAllowed(), CopyingDelaySlotFiller::collectMoves(), copy(), DataDependenceGraph::dotString(), dotString(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeDuplicator::duplicateMove(), MoveNodeDuplicator::duplicateMoveNode(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromDestination(), FUBroker::findDstFUOfMove(), BF2ScheduleFront::findInducingBypassSource(), MachineConnectivityCheck::findPossibleDestinationPorts(), BF2Scheduler::getDstUnit(), CopyingDelaySlotFiller::getMove(), BFOptimization::getSisterTrigger(), DataDependenceGraphBuilder::hasEarlierMemWriteToSameAddressWithSameGuard(), BFOptimization::immCountPreventsScheduling(), inSameOperation(), PreOptimizer::inverseGuardsOfHeads(), ExecutionPipelineResource::isDestOpOfMN(), isLastUnscheduledMoveOfDstOp(), ExecutionPipelineBroker::isMoveTrigger(), BF2Scheduler::isTrigger(), DataDependenceGraphBuilder::isTriggering(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), DataDependenceGraphBuilder::memoryCategory(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), DataDependenceGraph::moveFUDependenciesToTrigger(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandsOverwritten(), ExecutionPipelineResource::operandTooLate(), BFPushMoveUp::operator()(), BFRemoveLoopChecksAndJump::operator()(), BFScheduleBU::operator()(), BFShareOperandLate::operator()(), BFShareOperands::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), BF2Scheduler::preAllocateFunctionUnits(), DataDependenceGraph::predecessorsReady(), DataDependenceGraphBuilder::processMemWrite(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BFShareOperandLate::revert(), BFOptimization::RFReadPortCountPreventsScheduling(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), DataDependenceGraph::successorsReady(), ExecutionPipelineResource::testTriggerResult(), ExecutionPipelineResource::triggerTooEarly(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfDestOps(), ExecutionPipelineResource::unassignDestination(), BFLateBypass::undoOnlyMe(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), DataDependenceGraph::writeToXMLFile(), and ~MoveNode().
destinationOperationCount()
unsigned int MoveNode::destinationOperationCount () const inline
Referenced by BF2ScheduleFront::allNodesOfSameOperation(), ExecutionPipelineResource::assignDestination(), BFSwapOperands::BFSwapOperands(), BusResource::canAssign(), ExecutionPipelineResource::checkOperandAllowed(), copy(), MoveNodeDuplicator::duplicateMoveNode(), ExecutionPipelineBroker::earliestFromDestination(), FUBroker::findDstFUOfMove(), BF2ScheduleFront::findInducingBypassSource(), CopyingDelaySlotFiller::getMoveNode(), inSameOperation(), ExecutionPipelineResource::isDestOpOfMN(), isLastUnscheduledMoveOfDstOp(), ExecutionPipelineBroker::isMoveTrigger(), ExecutionPipelineBroker::latestFromDestination(), BUMoveNodeSelector::mightBeReady(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), BFRemoveLoopChecksAndJump::operator()(), BFShareOperand::operator()(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfDestOps(), BF2ScheduleFront::tryToScheduleMoveOuter(), ExecutionPipelineResource::unassignDestination(), BFLateBypass::undoOnlyMe(), and ~MoveNode().
destinationOperationPtr()
ProgramOperationPtr MoveNode::destinationOperationPtr (unsigned int index = 0) const
Referenced by BFSwapOperands::BFSwapOperands(), copy(), DataDependenceGraph::createSubgraph(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), DataDependenceGraph::mergeAndKeepSource(), BFDropPreShared::operator()(), BFRemoveLoopChecksAndJump::operator()(), BFShareOperand::operator()(), BFRemoveLoopChecksAndJump::queueAliveMove(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), and BFRemoveLoopChecksAndJump::removePoFromQueue().
dotString()
std::string MoveNode::dotString () const virtual
Returns Dot representation of the node.
Prints the disassembly of the move and sets the color of the node to red in case it's scheduled.
Returns
The string with node ID.
Reimplemented from GraphNode.
Definition at line 602 of file MoveNode.cc.
{
    std::string contents = GraphNode::dotString();
    if (isOperationMove()) {
        unsigned operationId = 0;
        // make the outline of the moves that belong to the same operation
        // of the same color to aid in schedule debugging
        if (isSourceOperation())
            operationId = sourceOperation().poId();
        else
            operationId = destinationOperation().poId();
        // hash the colors so that they are easy to separate/recognise.
        // srand();rand() pair only used as a hash function,
        // this needs to be deterministic.
        srand(operationId);
        int operationColor = rand() / (RAND_MAX>>24);
        contents +=
            (boost::format(
                ",color=\"#%.6x\"") % operationColor).str();
    }
    if (isScheduled()) {
        if (isFinalized()) {
            contents += ",shape=hexagon";
        } else {
            contents += ",shape=box";
        }
    } else {
        if (!isInFrontier_) {
            contents += ",shape=ellipse";
        } else {
            contents += ",shape=diamond";
        }
    }
    return contents;
}
References destinationOperation(), GraphNode::dotString(), isFinalized(), isInFrontier_, isOperationMove(), isScheduled(), isSourceOperation(), ProgramOperation::poId(), and sourceOperation().
Referenced by DataDependenceGraph::dotString(), and ResourceConstraintAnalyzer::dumpGraphWithStats().
earliestResultReadCycle()
int MoveNode::earliestResultReadCycle () const
Returns the cycle the given result move can be scheduled earliest, taking in the account the latency of the operation.
In case the trigger move has not been scheduled yet, returns INT_MAX.
Exceptions
IllegalObject if this MoveNode is not a result read.
Definition at line 652 of file MoveNode.cc.
{
    const ProgramOperation* po;
    int outputIndex;
    if (isSourceOperation()) {
        po = &sourceOperation();
        outputIndex = move_->source().operationIndex();
    } else {
        if (!isGuardOperation())
            throw IllegalParameters(
                __FILE__, __LINE__, __func__, "Not a result read move.");
        po = &guardOperation();
        outputIndex = po->outputIndexOfMove(*this);
    }
    try {
        MoveNode* trigger = po->triggeringMove();
        if (trigger == NULL || !trigger->isScheduled()) {
            return INT_MAX;
        }
        // find the latency of the operation output we are reading
        const TTAMachine::HWOperation& hwop =
            *trigger->move().destination().functionUnit().operation(
                po->operation().name());
        return trigger->cycle() + hwop.latency(outputIndex);
    } catch (const InvalidData& id) {
        // triggeringMove() throws if the triggering move cannot be resolved
        // again ignore this. causd by either
        // incorrect scheduling order ( in RM tests) or
        // broken machine ( catched by machinecheck now)
    } catch (const Exception& e) {
        abortWithError(e.errorMessageStack());
    }
    return INT_MAX;
}
References __func__, abortWithError, cycle(), TTAProgram::Move::destination(), Exception::errorMessageStack(), TTAProgram::Terminal::functionUnit(), guardOperation(), isGuardOperation(), isScheduled(), isSourceOperation(), TTAMachine::HWOperation::latency(), move(), move_, Operation::name(), ProgramOperation::operation(), TTAMachine::FunctionUnit::operation(), ProgramOperation::outputIndexOfMove(), sourceOperation(), and ProgramOperation::triggeringMove().
Referenced by ExecutionPipelineResource::canAssignSource(), ExecutionPipelineBroker::earliestFromSource(), ExecutionPipelineBroker::latestFromSource(), BasicBlockScheduler::scheduleMove(), and SequentialScheduler::scheduleResultReads().
finalize()
void MoveNode::finalize ()
guardLatency()
int MoveNode::guardLatency () const
Returns the total guard latency of the guard of given move, or 0 if the move is unconditional.
Definition at line 779 of file MoveNode.cc.
{
    if (!isMove()) {
        return 0;
    }
    return move_->guardLatency();
}
References isMove(), and move_.
Referenced by SimpleBrokerDirector::assign(), CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), CopyingDelaySlotFiller::checkIncomingDeps(), CopyingDelaySlotFiller::collectMoves(), DataDependenceGraph::earliestCycle(), DataDependenceGraph::edgeLatency(), DataDependenceGraph::edgeWeight(), CopyingDelaySlotFiller::fillDelaySlots(), DataDependenceGraph::latestCycle(), BFLateBypassGuard::operator()(), BFPushAntidepsDown::operator()(), BFRemoveGuardsFromSuccs::operator()(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::tryToOptimizeWaw(), and SimpleBrokerDirector::unassign().
guardOperation()
ProgramOperation & MoveNode::guardOperation () const
Returns the instance of operation in the program whose output is the guard of this node.
Returns
A program operation.
Exceptions
InvalidData if the given node does not read an operation output.
Definition at line 479 of file MoveNode.cc.
{
    return *guardOperationPtr().get();
}
References guardOperationPtr().
Referenced by OutputFUBroker::allAvailableResources(), BF2ScheduleFront::allNodesOfSameOperation(), OutputFUBroker::assign(), ExecutionPipelineResource::assignSource(), ExecutionPipelineResource::canAssignSource(), MoveNodeDuplicator::duplicateMoveNode(), earliestResultReadCycle(), MachineConnectivityCheck::findPossibleDestinationPorts(), OutputFUBroker::isAlreadyAssigned(), ExecutionPipelineBroker::latestFromSource(), ExecutionPipelineResource::nextResultCycle(), ExecutionPipelineResource::testTriggerResult(), OutputFUBroker::unassign(), ExecutionPipelineResource::unassignSource(), and ~MoveNode().
guardOperationPtr()
ProgramOperationPtr MoveNode::guardOperationPtr () const
Definition at line 484 of file MoveNode.cc.
{
    if (!isGuardOperation()){
        std::string msg =
            (boost::format(
                "MoveNode: '%s' guard is not Operation.") % toString()).
            str();
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    } else {
        return guardOp_;
    }
}
References __func__, guardOp_, isGuardOperation(), and toString().
Referenced by CopyingDelaySlotFiller::collectMoves(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), guardOperation(), CopyingDelaySlotFiller::tryToAssignNodes(), and CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp().
immediate() [1/2]
TTAProgram::Immediate & MoveNode::immediate ()
Definition at line 838 of file MoveNode.cc.
{
    return *immediate_;
}
References immediate_.
Referenced by ITemplateBroker::assign(), ITemplateBroker::isAlreadyAssigned(), and ITemplateBroker::unassign().
immediate() [2/2]
const TTAProgram::Immediate & MoveNode::immediate () const
Definition at line 842 of file MoveNode.cc.
{
    return *immediate_;
}
References immediate_.
immediatePtr() [1/2]
std::shared_ptr< TTAProgram::Immediate > MoveNode::immediatePtr ()
Definition at line 846 of file MoveNode.cc.
{
    return immediate_;
}
References immediate_.
Referenced by ITemplateBroker::allAvailableResources(), ITemplateBroker::assign(), and ITemplateBroker::unassign().
immediatePtr() [2/2]
std::shared_ptr< const TTAProgram::Immediate > MoveNode::immediatePtr () const
inSameOperation()
bool MoveNode::inSameOperation (const MoveNode & other) const
Returns true if this MoveNode is in the same ProgramOperation as the given MoveNode.
Returns
True if both MoveNodes belong to the same ProgramOperation.
Definition at line 306 of file MoveNode.cc.
{
    if (other.isRegisterMove() || this->isRegisterMove())
        return false;
    unsigned int dopCount1 = destinationOperationCount();
    unsigned int dopCount2 = other.destinationOperationCount();
    if (isSourceOperation()) {
        if (other.isSourceOperation()) {
            if (&sourceOperation() == &other.sourceOperation()) {
                return true;
            }
        }
        for (unsigned int i = 0; i < dopCount2; i++) {
            if (&other.destinationOperation(i) == &sourceOperation()) {
                return true;
            }
        }
    }
    for (unsigned int i = 0; i < dopCount1; i++) {
        const ProgramOperation* dop = &destinationOperation(i);
        if (other.isSourceOperation()) {
            if (dop == &other.sourceOperation()) {
                return true;
            }
        }
        for (unsigned int j = 0; j < dopCount2; j++) {
            if (&other.destinationOperation(j) == dop) {
                return true;
            }
        }
    }
    return false;
}
References destinationOperation(), destinationOperationCount(), isRegisterMove(), isSourceOperation(), and sourceOperation().
Referenced by DataDependenceGraph::earliestCycle(), DataDependenceGraph::edgeLatency(), DataDependenceGraph::latestCycle(), BUMoveNodeSelector::notifyScheduled(), and CriticalPathBBMoveNodeSelector::notifyScheduled().
isAssigned()
bool MoveNode::isAssigned () const
Tells whether the node is fully assigned.
A node is fully assigned when all the resources of the target processor necessary to carry out the transport it specifies are assigned to it.
Returns
True if all required scheduling resources of target machine are assigned to the node.
Machine found is NOT UniversalMachine - we are happy
Definition at line 367 of file MoveNode.cc.
{
    if (immediate_ != NULL) {
        TTAProgram::Instruction* parent = immediate_->parent();
        return parent != NULL &&
            &parent->instructionTemplate() !=
            &NullInstructionTemplate::instance();
    }
    if (move_ == NULL) {
        // probably a dummy ENTRYNODE or something
        return false;
    }
    /// Machine found is NOT UniversalMachine - we are happy
    if (!move_->bus().machine()->isUniversalMachine()) {
        if ((isSourceOperation() ||
            isSourceVariable() ||
            isSourceImmediateRegister()) &&
            (move_->source().port().parentUnit()->machine() !=
             move_->bus().machine())) {
            return false;
        }
        if ((isDestinationOperation() || isDestinationVariable()) &&
            (move_->destination().port().parentUnit()->machine() !=
             move_->bus().machine())) {
            return false;
        }
        return true;
    }
    return false;
}
References immediate_, TTAMachine::NullInstructionTemplate::instance(), TTAProgram::Instruction::instructionTemplate(), isDestinationOperation(), isDestinationVariable(), isSourceImmediateRegister(), isSourceOperation(), isSourceVariable(), move_, and TTAProgram::Instruction::parent().
Referenced by ProgramOperation::areInputsAssigned(), ProgramOperation::areOutputsAssigned(), ProgramOperation::isAnyInputAssigned(), ProgramOperation::isAnyNodeAssigned(), ProgramOperation::isAnyOutputAssigned(), ProgramOperation::isAssigned(), isScheduled(), and DataDependenceEdge::latencySt().
isBypass()
bool MoveNode::isBypass () const
Tells whether the node is a `‘software bypass’' - both its source and its destination belong to operations.
Returns
True if both source and destination of the node are operation terminals.
Definition at line 280 of file MoveNode.cc.
{
    return isSourceOperation() && isDestinationOperation();
}
References isDestinationOperation(), and isSourceOperation().
Referenced by CycleLookBackSoftwareBypasser::bypass(), and ResourceConstraintAnalyzer::dumpGraphWithStats().
isDestinationOperation()
bool MoveNode::isDestinationOperation () const inline
Referenced by InputFUBroker::allAvailableResources(), CopyingDelaySlotFiller::allowedToSpeculate(), ResourceConstraintAnalyzer::analyzeMoveNode(), BFOptimization::assign(), BFOptimization::assignCopyToPrologEpilog(), ExecutionPipelineResource::assignDestination(), CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), BFOptimization::canAssign(), ExecutionPipelineResource::canAssignDestination(), BFOptimization::canBeSpeculated(), PreOptimizer::checkGuardReversalAllowed(), CopyingDelaySlotFiller::collectMoves(), copy(), DataDependenceGraph::createSubgraph(), DataDependenceGraph::dotString(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeDuplicator::duplicateMove(), MoveNodeDuplicator::duplicateMoveNode(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromDestination(), MachineConnectivityCheck::findPossibleDestinationPorts(), BF2Scheduler::getDstUnit(), CopyingDelaySlotFiller::getMove(), CopyingDelaySlotFiller::getMoveNode(), CopyingDelaySlotFiller::getProgramOperationPtr(), BFOptimization::getSisterTrigger(), BFOptimization::hasAmbiguousResources(), BFOptimization::immCountPreventsScheduling(), BUMoveNodeSelector::initializeReadylist(), CriticalPathBBMoveNodeSelector::initializeReadylist(), isAssigned(), isBypass(), ExecutionPipelineBroker::isMoveTrigger(), isOperationMove(), isRegisterMove(), DataDependenceGraph::latestCycle(), latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), DataDependenceGraphBuilder::memoryCategory(), DataDependenceGraph::mergeAndKeepSource(), CriticalPathBBMoveNodeSelector::mightBeReady(), DataDependenceGraph::moveFUDependenciesToTrigger(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandPort(), BFPushMoveUp::operator()(), BFRemoveLoopChecksAndJump::operator()(), BFScheduleBU::operator()(), BFPostpassBypass::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), DataDependenceGraph::predecessorsReady(), BF2ScheduleFront::prefResultCycle(), BFRemoveLoopChecksAndJump::queueAliveMove(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), BFRemoveLoopChecksAndJump::removePoFromQueue(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BFOptimization::RFReadPortCountPreventsScheduling(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), BFOptimization::setPrologDstFUAnno(), DataDependenceGraph::successorsReady(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToDelayOperands(), ExecutionPipelineResource::unassignDestination(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), DataDependenceGraph::writeToXMLFile(), and ~MoveNode().
isDestinationVariable()
bool MoveNode::isDestinationVariable () const
Tells whether the node (move) writes a program variable or, if assigned, a GPR.
Returns
True if the destination of the node is a variable or GPR.
Definition at line 264 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return move_->destination().isGPR();
}
References move_.
Referenced by BUBasicBlockScheduler::bypassNode(), CycleLookBackSoftwareBypasser::bypassNode(), BUBasicBlockScheduler::finalizeSchedule(), isAssigned(), BF2Scheduler::isDestinationUniversalReg(), CriticalPathBBMoveNodeSelector::mightBeReady(), BFRescheduleResultsClose::operator()(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), BFEarlyBypass::operator()(), and BF2ScheduleFront::tryToScheduleMoveOuter().
isFinalized()
bool MoveNode::isFinalized () const
Referenced by dotString(), and BF2ScheduleFront::requeueOtherMovesOfSameOp().
isGuardOperation()
bool MoveNode::isGuardOperation () const
Tells whether the guard of the MoveNode (move) is a port guard from op.
Returns
True if the source of the MoveNode is an operation output.
Definition at line 181 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return guardOp_.get() != NULL;
}
References guardOp_, and move_.
Referenced by BF2ScheduleFront::allNodesOfSameOperation(), OutputFUBroker::assign(), ExecutionPipelineResource::canAssignSource(), MoveNodeDuplicator::duplicateMoveNode(), earliestResultReadCycle(), MachineConnectivityCheck::findPossibleDestinationPorts(), CopyingDelaySlotFiller::getMoveNode(), guardOperationPtr(), OutputFUBroker::isAlreadyAssigned(), BFOptimization::jumpGuardAvailableCycle(), ExecutionPipelineBroker::latestFromSource(), ExecutionPipelineResource::nextResultCycle(), BFLateBypass::operator()(), ExecutionPipelineResource::resultPort(), ExecutionPipelineResource::testTriggerResult(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), OutputFUBroker::unassign(), and ~MoveNode().
isImmediate()
bool MoveNode::isImmediate () const inline
Definition at line 143 of file MoveNode.hh.
{ return immediate_ != nullptr; }
References immediate_.
Referenced by ITemplateBroker::allAvailableResources(), ITemplateBroker::assign(), ITemplateBroker::isAlreadyAssigned(), isSourceConstant(), and ITemplateBroker::unassign().
isInFrontier()
bool MoveNode::isInFrontier () const
Referenced by BFEarlyBypasser::bypassSourceLatestCycle().
isLastUnscheduledMoveOfDstOp()
bool MoveNode::isLastUnscheduledMoveOfDstOp () const
Definition at line 817 of file MoveNode.cc.
{
    for (unsigned int i = 0; i < destinationOperationCount(); i++) {
        const ProgramOperation& po = destinationOperation(i);
        // ignore ops with just one input
        if (po.inputMoveCount() == 1) {
            continue;
        }
        bool fail = false;
        for (int j = 0; j < po.inputMoveCount(); j++) {
            MoveNode& inputNode = po.inputMove(j);
            if (&inputNode != this && !inputNode.isScheduled()) {
                fail = true;
                break;
            }
        }
        if (!fail)
            return true;
    }
    return false;
}
References destinationOperation(), destinationOperationCount(), ProgramOperation::inputMove(), ProgramOperation::inputMoveCount(), and isScheduled().
isMove()
bool MoveNode::isMove () const inline
Referenced by DataDependenceGraph::addNode(), ITemplateBroker::allAvailableResources(), PRegionAliasAnalyzer::analyze(), SimpleBrokerDirector::assign(), IUResource::canAssign(), SimpleBrokerDirector::canAssign(), CopyingDelaySlotFiller::checkIncomingDeps(), DataDependenceGraph::createSubgraph(), DataDependenceGraph::createSubgraph(), DataDependenceGraph::dotString(), DataDependenceGraph::edgeWeight(), DataDependenceGraph::exclusingGuards(), ExecutionPipelineResource::exclusiveMoves(), BF2Scheduler::findJump(), ResourceConstraintAnalyzer::findResourceConstrainedParent(), ConstantAliasAnalyzer::getConstantAddress(), StackAliasAnalyzer::getStackOffset(), guardLatency(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BusBroker::isApplicable(), OutputPSocketBroker::isApplicable(), OutputFUBroker::isApplicable(), InputFUBroker::isApplicable(), IUBroker::isApplicable(), InputPSocketBroker::isApplicable(), isSourceReg(), DataDependenceGraph::mergeAndKeepAllowed(), ProgramDependenceGraph::processRegion(), ProgramDependenceGraph::ProgramDependenceGraph(), RegisterRenamer::renameDestinationRegister(), RegisterRenamer::renameSourceRegister(), DataDependenceGraph::resultUsed(), DataDependenceGraph::sameGuards(), DataDependenceEdge::saveState(), ITemplateBroker::unassign(), SimpleBrokerDirector::unassign(), DataDependenceGraph::updateRegWrite(), MoveNodeGroup::writesJumpGuard(), and DataDependenceGraph::writeToXMLFile().
isOperationMove()
bool MoveNode::isOperationMove () const
Tells whether the move belongs to an operation execution.
Returns
True if the the node belongs to an operation.
Definition at line 253 of file MoveNode.cc.
{
    return isSourceOperation() || isDestinationOperation();
}
References isDestinationOperation(), and isSourceOperation().
Referenced by DataDependenceGraph::dotString(), dotString(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleLoopDDG(), and BUBasicBlockScheduler::handleLoopDDG().
isPlaced()
bool MoveNode::isPlaced () const
Tells whether is placed in the program representation, that is, has a cycle assigned to it.
Returns
True if a cycle is assigned to the node.
Definition at line 352 of file MoveNode.cc.
{
    return placed_;
}
References placed_.
Referenced by SimpleBrokerDirector::assign(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignSource(), ExecutionPipelineResource::checkOperandAllowed(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), cycle(), DataDependenceGraph::earliestCycle(), ExecutionPipelineResource::exclusiveMoves(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterKill(), DataDependenceGraph::firstScheduledRegisterRead(), DataDependenceGraph::firstScheduledRegisterReads(), DataDependenceGraph::firstScheduledRegisterWrite(), DataDependenceGraph::firstScheduledRegisterWrites(), isScheduled(), DataDependenceGraph::largestCycle(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), DataDependenceGraph::lastScheduledRegisterKill(), DataDependenceGraph::lastScheduledRegisterRead(), DataDependenceGraph::lastScheduledRegisterReads(), DataDependenceGraph::lastScheduledRegisterWrites(), DataDependenceGraph::latestCycle(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), DataDependenceGraph::movesAtCycle(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandsOverwritten(), ExecutionPipelineResource::operandTooLate(), DataDependenceGraph::otherSuccessorsScheduled(), DataDependenceGraph::predecessorsReady(), DataDependenceGraph::regRawSuccessorCount(), AssignmentPlan::resetAssignments(), ExecutionPipelineResource::resultReadyCycle(), DataDependenceGraph::scheduledMoves(), DataDependenceGraph::scheduledNodeCount(), AssignmentPlan::setRequest(), DataDependenceGraph::smallestCycle(), DataDependenceGraph::successorsReady(), ExecutionPipelineResource::testTriggerResult(), toString(), ExecutionPipelineResource::triggerTooEarly(), SimpleBrokerDirector::unassign(), BasicBlockScheduler::unschedule(), SequentialScheduler::unschedule(), DataDependenceGraph::unscheduledMoves(), and DataDependenceGraph::writeToXMLFile().
isRegisterMove()
bool MoveNode::isRegisterMove () const
Tells whether the node is a register move, thus not belong to any particular ProgramOperation.
It's either an immediate move to an register or a register to register copy.
Returns
True if the move is a register to register copy.
Definition at line 294 of file MoveNode.cc.
{
    return !isSourceOperation() && !isDestinationOperation();
}
References isDestinationOperation(), and isSourceOperation().
Referenced by inSameOperation().
isScheduled()
bool MoveNode::isScheduled () const
Tells whether the node is completely scheduled.
A node is completely scheduled only if it is assigned to a program cycle and the necessary resources of the target processor are assigned to it.
Returns
True if the node is placed and assigned.
Definition at line 409 of file MoveNode.cc.
{
    return isPlaced() && isAssigned();
}
References isAssigned(), and isPlaced().
Referenced by BFSwapOperands::BFSwapOperands(), CycleLookBackSoftwareBypasser::bypass(), BUBasicBlockScheduler::bypassNode(), CycleLookBackSoftwareBypasser::bypassNode(), BFEarlyBypasser::bypassSourceLatestCycle(), SimpleBrokerDirector::canAssign(), CopyingDelaySlotFiller::checkIncomingDeps(), BFOptimization::checkPrologDDG(), BUBasicBlockScheduler::clearRemovedNodes(), MoveNodeDuplicator::disposeMoveNode(), dotString(), MoveNodeDuplicator::duplicateMove(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), earliestResultReadCycle(), BF2Scheduler::finalizeSchedule(), BUBasicBlockScheduler::finalizeSchedule(), BUBasicBlockScheduler::findBypassDestinations(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), BF2Scheduler::getDstUnit(), BF2ScheduleFront::getMoveNodeFromFrontBU(), BUBasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleRemovedResultMoves(), BFOptimization::immCountPreventsScheduling(), isLastUnscheduledMoveOfDstOp(), ExecutionPipelineBroker::isMoveTrigger(), BFOptimization::jumpGuardAvailableCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), CopyingDelaySlotFiller::loseCopies(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), BUMoveNodeSelector::notifyScheduled(), CriticalPathBBMoveNodeSelector::notifyScheduled(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), RegisterCopyAdder::operandsScheduled(), BFDRELate::operator()(), BFEarlyBypasser::operator()(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepsDown::operator()(), BFPushDepsUp::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultsClose::operator()(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), BFEarlyBypass::operator()(), BFPostpassBypass::operator()(), BFRemoveGuardsFromSuccs::operator()(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), BUBasicBlockScheduler::precedingTempMove(), BF2ScheduleFront::prefResultCycle(), LiveRangeData::registersAlive(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), RegisterCopyAdder::resultsScheduled(), BFOptimization::RFReadPortCountPreventsScheduling(), BF2Scheduler::scheduleDDG(), BasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperand(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleResultReadTempMoves(), BasicBlockScheduler::scheduleRRTempMoves(), BUBasicBlockScheduler::scheduleRRTempMoves(), BasicBlockScheduler::succeedingTempMove(), toString(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::undoBypass(), BFRegCopy::undoDDG(), BFDRELoop::undoOnlyMe(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), BFScheduleMove::undoOnlyMe(), BFScheduleTD::undoOnlyMe(), BasicBlockScheduler::unschedule(), SequentialScheduler::unschedule(), and BUBasicBlockScheduler::unscheduleAllNodes().
isSourceConstant()
bool MoveNode::isSourceConstant () const
Tells whether the source of the node (move) is a program constant. If assigned, the constant is an in-line immediate.
Returns
True if the source of the node is a constant.
Definition at line 238 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return move_->source().isImmediate();
}
References isImmediate(), and move_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), OffsetAliasAnalyzer::analyze(), CycleLookBackSoftwareBypasser::bypassNode(), BusResource::canAssign(), MachineConnectivityCheck::canBypass(), MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), ResourceConstraintAnalyzer::dumpGraphWithStats(), LoopAnalyzer::findEndCond(), LoopAnalyzer::findInitAndUpdate(), MachineConnectivityCheck::findPossibleSourcePorts(), StackAliasAnalyzer::getStackOffset(), BFOptimization::hasAmbiguousResources(), ProgramOperation::hasConstantOperand(), OutputPSocketBroker::isAlreadyAssigned(), OutputPSocketBroker::isApplicable(), IUBroker::isApplicable(), CriticalPathBBMoveNodeSelector::mightBeReady(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), PreOptimizer::tryToPrecalcConstantAdd(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), and ITemplateBroker::unassign().
isSourceImmediateRegister()
bool MoveNode::isSourceImmediateRegister () const
Tells whether the node (move) reads a Immediate Register
Returns
True if the source of the node is Immediate register.
Definition at line 223 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return move_->source().isImmediateRegister();
}
References move_.
Referenced by SimpleBrokerDirector::assign(), ITemplateBroker::assign(), BFOptimization::assignCopyToPrologEpilog(), BFOptimization::canAssign(), IUBroker::immediateValue(), IUBroker::immediateWriteCycle(), IUBroker::isApplicable(), isAssigned(), BFOptimization::rmEC(), BFOptimization::rmLC(), and SimpleBrokerDirector::unassign().
isSourceOperation()
bool MoveNode::isSourceOperation () const
Tells whether the source of the MoveNode (move) belongs to an operation.
Returns
True if the source of the MoveNode is an operation output.
Definition at line 168 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return srcOp_.get() != NULL;
}
References move_, and srcOp_.
Referenced by OutputFUBroker::allAvailableResources(), BF2ScheduleFront::allNodesOfSameOperation(), CopyingDelaySlotFiller::allowedToSpeculate(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), BFOptimization::assign(), OutputFUBroker::assign(), ExecutionPipelineResource::assignSource(), CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), BFEarlyBypasser::bypassSourceLatestCycle(), ExecutionPipelineResource::canAssignSource(), CopyingDelaySlotFiller::collectMoves(), copy(), TTAProgram::CodeGenerator::createForLoopBufferInit(), DataDependenceGraph::createSubgraph(), MemoryAliasAnalyzer::detectConstantScale(), DataDependenceGraph::dotString(), dotString(), MoveNodeDuplicator::duplicateMove(), MoveNodeDuplicator::duplicateMoveNode(), MoveNodeGroup::earliestCycle(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromSource(), earliestResultReadCycle(), DataDependenceGraph::edgeLatency(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), BF2ScheduleFront::findInducingBypassSource(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), ConstantAliasAnalyzer::getConstantAddress(), CopyingDelaySlotFiller::getMove(), CopyingDelaySlotFiller::getMoveNode(), CopyingDelaySlotFiller::getProgramOperationPtr(), StackAliasAnalyzer::getStackOffset(), BFOptimization::hasAmbiguousResources(), inSameOperation(), OffsetAliasAnalyzer::isAddressTraceable(), isAssigned(), isBypass(), isOperationMove(), isRegisterMove(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), DataDependenceGraph::mergeAndKeepUser(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), ExecutionPipelineResource::nextResultCycle(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushDepsUp::operator()(), BFPushMoveUp2::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFScheduleTD::operator()(), BFPostpassBypass::operator()(), BFUpdateMoveOnBypass::operator()(), ProgramOperation::outputIndexOfMove(), DataDependenceGraph::predecessorsReady(), BF2ScheduleFront::prefResultCycle(), BFRemoveLoopChecksAndJump::queueAliveMove(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), BFRemoveLoopChecksAndJump::removePoFromQueue(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), SequentialScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BFOptimization::setPrologSrcFUAnno(), sourceOperationPtr(), DataDependenceGraph::successorsReady(), ExecutionPipelineResource::testTriggerResult(), PreOptimizer::tryToRemoveEq(), LoopAnalyzer::tryTrackCommonAncestor(), ExecutionPipelineResource::unassignSource(), BFUpdateMoveOnBypass::undoOnlyMe(), DataDependenceGraph::unMergeUser(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), and ~MoveNode().
isSourceRA()
bool MoveNode::isSourceRA () const
Tells whether the node (move) reads the return address port. GPR.
Returns
True if the source of the node is the return address port.
Definition at line 210 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return move_->source().isRA();
}
References move_.
Referenced by DataDependenceGraph::mergeAndKeepUser(), and BFMergeAndKeepUser::updateEdges().
isSourceReg()
bool MoveNode::isSourceReg (const std::string & reg) const
Checks if the source of the movenode is the given reg.
This method assumes incoming reg name is in correct rf.number format, and does not check it, due performance reasons.
Parameters
reg register to check against source of the movenode
Returns
true if the source of the movenode is the given reg. false if some other reg or not reg.
Definition at line 798 of file MoveNode.cc.
{
    if (!isMove()) {
        return false;
    }
    if (!move().source().isGPR()) {
        return false;
    }
    // try to do as quickly as possible,
    // compare the reg in string and reg in terminalregister.
    size_t dotPlace = reg.find('.');
    const std::string& rfName = move().source().registerFile().name();
    if (reg.compare(0, dotPlace, rfName) != 0) {
        return false;
    }
    return atoi(reg.c_str()+dotPlace+1) == move().source().index();
}
References TTAProgram::Terminal::index(), isMove(), move(), TTAMachine::Component::name(), TTAProgram::Terminal::registerFile(), and TTAProgram::Move::source().
Referenced by StackAliasAnalyzer::getStackOffset().
isSourceVariable()
bool MoveNode::isSourceVariable () const
Tells whether the node (move) reads a program variable or, if assigned, a GPR.
Returns
True if the source of the node is a variable or GPR.
Definition at line 196 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return false;
    }
    return move_->source().isGPR();
}
References move_.
Referenced by CopyingDelaySlotFiller::allowedToSpeculate(), LoopAnalyzer::analyze(), BUBasicBlockScheduler::bypassNode(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), BUBasicBlockScheduler::finalizeSchedule(), LoopAnalyzer::findEndCond(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleSourcePorts(), ConstantAliasAnalyzer::getConstantAddress(), StackAliasAnalyzer::getStackOffset(), isAssigned(), BF2Scheduler::isSourceUniversalReg(), DataDependenceGraph::mergeAndKeepUser(), CriticalPathBBMoveNodeSelector::mightBeReady(), BFScheduleBU::operator()(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), PreOptimizer::tryToPrecalcConstantAdd(), DataDependenceGraph::unMergeUser(), and BFMergeAndKeepUser::updateEdges().
latestTriggerWriteCycle()
int MoveNode::latestTriggerWriteCycle () const
Returns the lates cycle the given trigger move can be scheduled at, taking in the account the latency of the operation results.
In case the none of the result moves has been scheduled yet, returns INT_MAX.
Exceptions
IllegalObject if this MoveNode is not a result read.
Definition at line 698 of file MoveNode.cc.
{
    if (!isDestinationOperation())
        throw IllegalParameters(
            __FILE__, __LINE__, __func__, "Not a result read move.");
    const ProgramOperation& po = destinationOperation();
    int latestTrigger = INT_MAX;
    for (int i = 0; i < po.outputMoveCount(); i++){
        MoveNode& result = po.outputMove(i);
        if (!result.isScheduled()) {
            continue;
        }
        // find the latency of the operation output we are testing
        const TTAMachine::HWOperation& hwop =
            *result.move().source().functionUnit().operation(
                po.operation().name());
        // find the OSAL id of the operand of the output we are testing
        const int outputIndex = result.move().source().operationIndex();
        int latency = hwop.latency(outputIndex);
        latestTrigger = std::min(latestTrigger, result.cycle() - latency);
    }
    return latestTrigger;
}
References __func__, cycle(), destinationOperation(), TTAProgram::Terminal::functionUnit(), isDestinationOperation(), isScheduled(), TTAMachine::HWOperation::latency(), move(), Operation::name(), ProgramOperation::operation(), TTAMachine::FunctionUnit::operation(), TTAProgram::Terminal::operationIndex(), ProgramOperation::outputMove(), ProgramOperation::outputMoveCount(), and TTAProgram::Move::source().
Referenced by BUBasicBlockScheduler::scheduleMove(), and BUBasicBlockScheduler::scheduleOperandWrites().
move() [1/2]
TTAProgram::Move & MoveNode::move ()
Referenced by RegisterCopyAdder::addCandidateSetAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), ProgramOperation::addInputNode(), BFOptimization::addJumpGuardIfNeeded(), DataDependenceGraph::addNode(), ProgramOperation::addNode(), ProgramOperation::addOutputNode(), InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), IUBroker::allAvailableResources(), CopyingDelaySlotFiller::allowedToSpeculate(), ResourceConstraintAnalyzer::analyze(), LoopAnalyzer::analyze(), PRegionAliasAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), annotateAllInputs(), annotateAllOutputs(), IUResource::assign(), OutputPSocketResource::assign(), IUResource::assign(), BFOptimization::assign(), SimpleBrokerDirector::assign(), InputPSocketBroker::assign(), ITemplateBroker::assign(), OutputPSocketBroker::assign(), IUBroker::assign(), BFOptimization::assignCopyToPrologEpilog(), ExecutionPipelineResource::assignDestination(), BFSwapOperands::BFSwapOperands(), LoopPrologAndEpilogBuilder::build(), LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), MachineConnectivityCheck::busConnectedToAnyFU(), MachineConnectivityCheck::busConnectedToDestination(), CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), InputPSocketResource::canAssign(), OutputPSocketResource::canAssign(), PSocketResource::canAssign(), BusResource::canAssign(), IUResource::canAssign(), BFOptimization::canAssign(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), MachineConnectivityCheck::canBypass(), MachineConnectivityCheck::canBypassOpToDst(), MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), BusBroker::canTransportImmediate(), DataDependenceGraphBuilder::checkAndCreateMemAntideps(), ExecutionPipelineResource::checkOperandAllowed(), CopyingDelaySlotFiller::collectMoves(), MachineConnectivityCheck::copyOpFUs(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), BF2Scheduler::countLoopInvariantValueUsages(), RegisterCopyAdder::createAntidepsForReg(), BFRegCopy::createAntidepsForReg(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::CodeGenerator::createForLoopBufferInit(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), DataDependenceGraph::createSubgraph(), DataDependenceGraph::createSubgraph(), DataDependenceGraphBuilder::createTriggerDependencies(), BFOptimization::destinationFU(), DataDependenceGraph::destRenamed(), MemoryAliasAnalyzer::detectConstantScale(), MoveNodeDuplicator::disposeMoveNode(), DataDependenceGraph::dotString(), MoveNodeDuplicator::duplicateMoveNode(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), earliestResultReadCycle(), DataDependenceGraph::edgeWeight(), DataDependenceGraph::exclusingGuards(), ExecutionPipelineResource::exclusiveMoves(), BUBasicBlockScheduler::finalizeSchedule(), BUBasicBlockScheduler::findBypassDestinations(), FUBroker::findDstFUOfMove(), LoopAnalyzer::findEndCond(), RegisterRenamer::findGuardRegisters(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), BF2Scheduler::findJump(), DataDependenceGraph::findLiveRange(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterKill(), DataDependenceGraph::firstScheduledRegisterRead(), DataDependenceGraph::firstScheduledRegisterReads(), DataDependenceGraph::firstScheduledRegisterWrite(), DataDependenceGraph::firstScheduledRegisterWrites(), ConstantAliasAnalyzer::getConstantAddress(), BF2Scheduler::getDstUnit(), CopyingDelaySlotFiller::getMoveNode(), BF2ScheduleFront::getPreferredLimits(), StackAliasAnalyzer::getStackOffset(), DataDependenceGraph::guardRenamed(), DataDependenceGraph::guardRestored(), DataDependenceGraph::guardsAllowBypass(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BasicBlockScheduler::handleRemovedResultMoves(), BFOptimization::hasAmbiguousResources(), ProgramOperation::hasMoveNodeForMove(), BFOptimization::immCountPreventsScheduling(), IUResource::immediateValue(), IUResource::immediateWriteCycle(), RegisterRenamer::initializeFreeRegisters(), BUMoveNodeSelector::initializeReadylist(), CriticalPathBBMoveNodeSelector::initializeReadylist(), PreOptimizer::inverseGuardsOfHeads(), OffsetAliasAnalyzer::isAddressTraceable(), RegisterCopyAdder::isAllowedUnit(), OutputPSocketBroker::isAlreadyAssigned(), DataDependenceGraphBuilder::isAlwaysDifferentFU(), OutputPSocketBroker::isApplicable(), IUBroker::isApplicable(), BF2Scheduler::isDestinationUniversalReg(), ProgramOperation::isLegalFU(), ExecutionPipelineBroker::isMoveTrigger(), DataDependenceGraph::isNotAvoidable(), CriticalPathBBMoveNodeSelector::isReadyToBeScheduled(), isSourceReg(), BF2Scheduler::isSourceUniversalReg(), BF2Scheduler::isTrigger(), DataDependenceGraphBuilder::isTriggering(), BF2Scheduler::jumpGuard(), BFOptimization::jumpGuardAvailableCycle(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), DataDependenceGraph::lastScheduledRegisterKill(), DataDependenceGraph::lastScheduledRegisterRead(), DataDependenceGraph::lastScheduledRegisterReads(), DataDependenceGraph::lastScheduledRegisterWrites(), DataDependenceEdge::latencySt(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), latestTriggerWriteCycle(), DataDependenceGraphBuilder::memoryCategory(), DataDependenceGraph::mergeAndKeepSource(), DataDependenceGraph::mergeAndKeepUser(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), ProgramOperation::moveNode(), BF2Scheduler::mustBeTrigger(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), BFDropPreShared::operator()(), BFLateBypass::operator()(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepDown::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRegCopy::operator()(), BFRemoveLoopChecksAndJump::operator()(), BFRenameSource::operator()(), BFRescheduleResultClose::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFSchedulePreLoopShared::operator()(), BFScheduleTD::operator()(), BFShareOperand::operator()(), BFShareOperandLate::operator()(), BFShareOperands::operator()(), BFShareOperandsLate::operator()(), BFShareOperandWithScheduled::operator()(), BFEarlyGuardBypass::operator()(), BFPostpassBypass::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardFromSucc::operator()(), BFRemoveGuardsFromSuccs::operator()(), BFTryRemoveGuard::operator()(), BFUpdateMoveOnBypass::operator()(), RLBUPriorityCriticalPath::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), ProgramOperation::outputIndexFromGuardOfMove(), ProgramOperation::outputIndexOfMove(), ExecutionPipelineResource::poConflictsWithInputPort(), BF2Scheduler::possibleTempRegRFs(), BF2Scheduler::preAllocateFunctionUnits(), BUBasicBlockScheduler::precedingTempMove(), BF2ScheduleFront::prefResultCycle(), DataDependenceGraphBuilder::processDestination(), DataDependenceGraphBuilder::processGuard(), DataDependenceGraphBuilder::processMemWrite(), DataDependenceGraphBuilder::processOperand(), ProgramDependenceGraph::processPredicate(), ProgramDependenceGraph::processRegion(), DataDependenceGraphBuilder::processRegWrite(), DataDependenceGraphBuilder::processResultRead(), DataDependenceGraphBuilder::processSource(), DataDependenceGraphBuilder::processTriggerMemoryAndFUStates(), DataDependenceGraphBuilder::processTriggerPO(), DataDependenceGraphBuilder::processTriggerRegistersAndOperations(), ProgramDependenceGraph::ProgramDependenceGraph(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), ProgramDependenceGraph::removeGuardedJump(), ProgramOperation::removeInputNode(), ProgramOperation::removeOutputNode(), RegisterRenamer::renameDestinationRegister(), RegisterRenamer::renameLiveRange(), RegisterRenamer::renameSourceRegister(), AssignmentPlan::resetAssignments(), ExecutionPipelineResource::resourcesAllowTrigger(), ExecutionPipelineResource::resultAllowedAtCycle(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), DataDependenceGraph::resultUsed(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BF2Scheduler::revertBBLiveRangeBookkeepingForDestination(), BF2Scheduler::revertBBLiveRangeBookkeepingForSource(), BFOptimization::RFReadPortCountPreventsScheduling(), BFOptimization::rmEC(), BFOptimization::rmLC(), DataDependenceGraph::rWawRawEdgesOutUncond(), DataDependenceGraph::sameGuards(), DataDependenceGraph::sanityCheck(), DataDependenceEdge::saveState(), BF2ScheduleFront::scheduleFrontFromMove(), BasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperand(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleRRMove(), BasicBlockScheduler::scheduleRRTempMoves(), BUBasicBlockScheduler::scheduleRRTempMoves(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), BFOptimization::setJumpGuard(), ProgramOperation::setOperation(), BFOptimization::setPrologDstFUAnno(), BFOptimization::setPrologSrcFUAnno(), BFOptimization::sourceFU(), DataDependenceGraph::sourceRenamed(), BFCopyRegWithOp::splitMove(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), BasicBlockScheduler::succeedingTempMove(), ProgramOperation::switchInputs(), ExecutionPipelineResource::testTriggerResult(), ProgramOperation::triggeringMove(), ExecutionPipelineResource::triggerTooEarly(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToDelayOperands(), PreOptimizer::tryToOptimizeAddressReg(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveEq(), PreOptimizer::tryToRemoveGuardInversingOp(), PreOptimizer::tryToRemoveXor(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), LoopAnalyzer::tryTrackCommonAncestor(), IUResource::unassign(), ITemplateBroker::unassign(), OutputFUBroker::unassign(), SimpleBrokerDirector::unassign(), ExecutionPipelineResource::unassignDestination(), BUBasicBlockScheduler::undoBypass(), BFLateBypassGuard::undoOnlyMe(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), BFScheduleTD::undoOnlyMe(), BFEarlyGuardBypass::undoOnlyMe(), BFRemoveGuard::undoOnlyMe(), BFRemoveGuardFromSucc::undoOnlyMe(), BFUpdateMoveOnBypass::undoOnlyMe(), BFCopyRegWithOp::undoSplit(), BFRegCopyAfter::undoSplit(), BFRegCopyBefore::undoSplit(), DataDependenceGraph::unMergeUser(), BF2Scheduler::unreservePreallocatedFUs(), BasicBlockScheduler::unschedule(), SequentialScheduler::unschedule(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), BFOptimization::unsetJumpGuard(), BFMergeAndKeepUser::updateEdges(), BFOptimization::usePrologMove(), MoveNodeGroup::writesJumpGuard(), and DataDependenceGraph::writeToXMLFile().
move() [2/2]
const TTAProgram::Move & MoveNode::move () const
movePtr() [1/2]
std::shared_ptr< TTAProgram::Move > MoveNode::movePtr ()
Referenced by ITemplateBroker::allAvailableResources(), ITemplateBroker::assign(), LoopPrologAndEpilogBuilder::build(), ProgramDependenceGraph::processPredicate(), ProgramDependenceGraph::processRegion(), and ITemplateBroker::unassign().
movePtr() [2/2]
std::shared_ptr< const TTAProgram::Move > MoveNode::movePtr () const
operator=()
MoveNode & MoveNode::operator= (const MoveNode &) private
Assignment forbidden.
removeDestinationOperation()
void MoveNode::removeDestinationOperation (const ProgramOperation * ptr)
Unsets destination operation.
Does not ask the ProgramOperation to remove this MoveNode from it's input moves.
Definition at line 741 of file MoveNode.cc.
{
    for (std::vector<ProgramOperationPtr>::iterator i = dstOps_.begin();
         i != dstOps_.end(); i++) {
        if (((*i).get()) == ptr) {
            dstOps_.erase(i);
            return;
        }
    }
    std::string msg = "Removed destination op not found in MoveNode";
    throw InvalidData(__FILE__, __LINE__, __func__, msg);
}
References __func__, and dstOps_.
Referenced by BFShareOperand::operator()(), BFShareOperand::undoOnlyMe(), BFCopyRegWithOp::undoSplit(), and ProgramOperation::~ProgramOperation().
scope()
Scope & MoveNode::scope ()
Returns the enclosing scheduling scope of the node.
Returns
A scheduling scope.
TODO: Intentionally falsified code Class Scope does not exists so far in real
Definition at line 436 of file MoveNode.cc.
               {
    ///TODO: Intentionally falsified code
    /// Class Scope does not exists so far in real
    Scope* ns = new Scope;
    return *ns;
}
setCycle()
void MoveNode::setCycle (const int newcycle)
Set cycle for a node, also sets placed_
Parameters
newcycle Cycle to which node is placed_
Exceptions
InvalidData If node is already placed in cycle different from newcycle
Definition at line 503 of file MoveNode.cc.
{
    if (placed_ == true && cycle_ != newcycle) {
        std::string msg = "MoveNode is already placed in cycle ";
        msg += cycle_;
        msg += ".";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    cycle_ = newcycle;
    placed_ = true;
}
References __func__, cycle_, and placed_.
Referenced by LoopPrologAndEpilogBuilder::build(), SimpleBrokerDirector::canAssign(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), AssignmentPlan::setRequest(), and AssignmentPlan::tryCachedAssignment().
setGuardOperationPtr()
void MoveNode::setGuardOperationPtr (ProgramOperationPtr po)
Set a guard src of MoveNode to ProgramOperation
Parameters
po Program operation that is source of MoveNode
Definition at line 550 of file MoveNode.cc.
{
    guardOp_ = po;
}
References guardOp_.
Referenced by CopyingDelaySlotFiller::collectMoves(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), and DataDependenceGraph::guardConverted().
setIsInFrontier()
void MoveNode::setIsInFrontier (bool inFrontier = true)
Referenced by BF2ScheduleFront::requeueOtherMovesOfSameOp().
setSourceOperationPtr()
void MoveNode::setSourceOperationPtr (ProgramOperationPtr po)
Set a source of MoveNode to ProgramOperation
Parameters
po Program operation that is source of MoveNode
Definition at line 541 of file MoveNode.cc.
{
    srcOp_ = po;
}
References srcOp_.
Referenced by Peel2BBLoops::appendBB(), SimpleIfConverter::appendBB(), MoveNodeGroupBuilder::build(), copy(), TTAProgram::CodeGenerator::createForLoopBufferInit(), llvm::LLVMTCEIRBuilder::createMoveNode(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), DataDependenceGraph::mergeAndKeepUser(), BFUpdateMoveOnBypass::operator()(), DataDependenceGraphBuilder::processResultRead(), and BFCopyRegWithOp::splitMove().
sourceOperation()
ProgramOperation & MoveNode::sourceOperation () const
Returns the instance of operation in the program whose output is the source of this node.
Returns
A program operation.
Exceptions
InvalidData if the given node does not read an operation output.
Definition at line 453 of file MoveNode.cc.
{
    return *sourceOperationPtr().get();
}
References sourceOperationPtr().
Referenced by OutputFUBroker::allAvailableResources(), BF2ScheduleFront::allNodesOfSameOperation(), CopyingDelaySlotFiller::allowedToSpeculate(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), BFOptimization::assign(), ExecutionPipelineResource::assignSource(), BFEarlyBypasser::bypassSourceLatestCycle(), ExecutionPipelineResource::canAssignSource(), copy(), MemoryAliasAnalyzer::detectConstantScale(), DataDependenceGraph::dotString(), dotString(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeDuplicator::duplicateMove(), MoveNodeDuplicator::duplicateMoveNode(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromSource(), earliestResultReadCycle(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), BF2ScheduleFront::findInducingBypassSource(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), CopyingDelaySlotFiller::getMove(), DataDependenceGraph::guardRestored(), inSameOperation(), OffsetAliasAnalyzer::isAddressTraceable(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), ExecutionPipelineResource::nextResultCycle(), BFLateBypassGuard::operator()(), BFPushMoveUp2::operator()(), ProgramOperation::outputIndexOfMove(), DataDependenceGraph::predecessorsReady(), BF2ScheduleFront::prefResultCycle(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), DataDependenceGraph::successorsReady(), ExecutionPipelineResource::testTriggerResult(), PreOptimizer::tryToRemoveEq(), LoopAnalyzer::tryTrackCommonAncestor(), ExecutionPipelineResource::unassignSource(), BFUpdateMoveOnBypass::undoOnlyMe(), DataDependenceGraph::unMergeUser(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), ~MoveNode(), and ProgramOperation::~ProgramOperation().
sourceOperationPtr()
ProgramOperationPtr MoveNode::sourceOperationPtr () const
Definition at line 458 of file MoveNode.cc.
{
    if (!isSourceOperation()){
        std::string msg =
            (boost::format(
                "MoveNode: '%s' source is not Operation.") % toString()).
            str();
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    } else {
        return srcOp_;
    }
}
References __func__, isSourceOperation(), srcOp_, and toString().
Referenced by copy(), DataDependenceGraph::createSubgraph(), MoveNodeDuplicator::duplicateMoveNode(), CopyingDelaySlotFiller::getMoveNode(), DataDependenceGraph::guardConverted(), DataDependenceGraph::mergeAndKeepUser(), BFEarlyGuardBypass::operator()(), BFUpdateMoveOnBypass::operator()(), BFRemoveLoopChecksAndJump::queueAliveMove(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), BFRemoveLoopChecksAndJump::removePoFromQueue(), and sourceOperation().
toString()
std::string MoveNode::toString () const virtual
Returns string with ID of the MoveNode.
Not yet used anywhere except printing graph in .dot file. Returns the disassembly of the move along with its id.
Returns
The string with node ID.
Reimplemented from GraphNode.
Definition at line 576 of file MoveNode.cc.
{
    if (move_ == NULL) {
        return "-1:\tENTRYNODE";
    }
#ifdef PRINT_ID
    std::string content = Conversion::toString(nodeID()) + " ";
#else
    std::string content;
#endif
    content +=  (isPlaced() ? Conversion::toString(cycle()) + " " :
                 std::string()) + POMDisassembler::disassemble(*move_);
    if (isScheduled()) {
        content += " Bus: " + move_->bus().name();
    }
    return content;
}
References cycle(), POMDisassembler::disassemble(), isPlaced(), isScheduled(), move_, GraphNode::nodeID(), and Conversion::toString().
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), RegisterCopyAdder::addRegisterCopies(), RegisterCopyAdder::addRegisterCopiesToRRMove(), OutputFUBroker::allAvailableResources(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), BFOptimization::assign(), SimpleResourceManager::assign(), SimpleBrokerDirector::assign(), IUBroker::assign(), BFOptimization::assignCopyToPrologEpilog(), ExecutionPipelineResource::assignDestination(), BFSwapOperands::BFSwapOperands(), LoopPrologAndEpilogBuilder::build(), MoveNodeGroupBuilder::build(), BUBasicBlockScheduler::bypassNode(), BFEarlyBypasser::bypassSourceLatestCycle(), BFOptimization::canAssign(), SimpleResourceManager::canAssign(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), BUMoveNodeSelector::candidates(), ExecutionPipelineResource::checkOperandAllowed(), BFOptimization::checkPrologDDG(), DataDependenceGraph::copyDepsOver(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), BF2Scheduler::countLoopInvariantValueUsages(), cycle(), MoveNodeDuplicator::disposeMoveNode(), DataDependenceGraph::dotString(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeGroup::earliestCycle(), SimpleResourceManager::earliestCycle(), SimpleResourceManager::earliestCycle(), BF2Scheduler::finalizeSchedule(), BUBasicBlockScheduler::finalizeSchedule(), LoopAnalyzer::findEndCond(), LoopAnalyzer::findInitAndUpdate(), MachineConnectivityCheck::findPossibleDestinationPorts(), DataDependenceGraph::getBasicBlockNode(), DataDependenceGraph::getBasicBlockNode(), BF2Scheduler::getDstUnit(), BF2ScheduleFront::getMoveNodeFromFrontBU(), BF2ScheduleFront::getPreferredLimits(), guardOperationPtr(), SequentialScheduler::handleBasicBlock(), BBSchedulerController::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleRemovedResultMoves(), BUMoveNodeSelector::initializeReadylist(), BF2Scheduler::jumpGuard(), BFOptimization::jumpGuardAvailableCycle(), SimpleResourceManager::latestCycle(), SimpleResourceManager::latestCycle(), ExecutionPipelineBroker::latestFromSource(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), DataDependenceGraphBuilder::memoryCategory(), DataDependenceGraph::mergeAndKeepAllowed(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandOverwritten(), BFDRELate::operator()(), BFDRELoop::operator()(), BFDropPreShared::operator()(), BFEarlyBypasser::operator()(), BFLateBypass::operator()(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepDown::operator()(), BFPushAntidepsDown::operator()(), BFPushDepsUp::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultClose::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFSchedulePreLoopShared::operator()(), BFScheduleTD::operator()(), BFShareOperand::operator()(), BFShareOperandLate::operator()(), BFShareOperands::operator()(), BFShareOperandsLate::operator()(), BFShareOperandWithScheduled::operator()(), BF2ScheduleFront::operator()(), BFEarlyBypass::operator()(), BFPostpassBypass::operator()(), BFPostpassLoopDRE::operator()(), BFRemoveEdge::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardFromSucc::operator()(), BFRemoveGuardsFromSuccs::operator()(), BF2Scheduler::possibleTempRegRFs(), BF2Scheduler::preAllocateFunctionUnits(), BF2ScheduleFront::prefResultCycle(), DataDependenceGraphBuilder::processDestination(), DataDependenceGraphBuilder::processGuard(), BFRemoveLoopChecksAndJump::queueAliveMove(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), DataDependenceGraph::removeRAWEdges(), RegisterRenamer::renameLiveRange(), ExecutionPipelineResource::resultAllowedAtCycle(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BFShareOperandLate::revert(), BF2Scheduler::revertBBLiveRangeBookkeepingForDestination(), BF2Scheduler::revertBBLiveRangeBookkeepingForSource(), BFOptimization::rmEC(), BFOptimization::rmLC(), DataDependenceGraph::sanityCheck(), BF2Scheduler::scheduleDDG(), BF2ScheduleFront::scheduleFrontFromMove(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), SequentialScheduler::scheduleMove(), BF2ScheduleFront::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleRRTempMoves(), BFOptimization::setJumpGuard(), BFOptimization::setPrologDstFUAnno(), BFOptimization::setPrologSrcFUAnno(), AssignmentPlan::setRequest(), sourceOperationPtr(), BFRegCopyAfter::splitMove(), ExecutionPipelineResource::testTriggerResult(), ProgramDependenceNode::toString(), MoveNodeGroup::toString(), ExecutionPipelineResource::triggerTooEarly(), BF2ScheduleFront::tryRevertEarlierBypass(), BF2ScheduleFront::tryToScheduleMoveOuter(), BFOptimization::unassign(), IUBroker::unassign(), SimpleBrokerDirector::unassign(), SimpleResourceManager::unassign(), BFOptimization::unassignCopyFromPrologEpilog(), ExecutionPipelineResource::unassignDestination(), BUBasicBlockScheduler::undoBypass(), BFRegCopy::undoDDG(), BFDropPreShared::undoOnlyMe(), BFLateBypass::undoOnlyMe(), BFLateBypassGuard::undoOnlyMe(), BFRemoveLoopChecksAndJump::undoOnlyMe(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), BFScheduleMove::undoOnlyMe(), BFSchedulePreLoopShared::undoOnlyMe(), BFScheduleTD::undoOnlyMe(), BFShareOperand::undoOnlyMe(), BFShareOperandWithScheduled::undoOnlyMe(), BFPostpassBypass::undoOnlyMe(), BFRemoveEdge::undoOnlyMe(), BFRemoveGuardFromSucc::undoOnlyMe(), BFRegCopyAfter::undoSplit(), BasicBlockScheduler::unschedule(), SequentialScheduler::unschedule(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), BFOptimization::unsetJumpGuard(), and DataDependenceGraph::writeToXMLFile().
type()
int MoveNode::type ()
Returns type of the MoveNode.
Not yet used anywhere and types not decided so current dummy implementation returns -1
Returns
type of the node
Definition at line 563 of file MoveNode.cc.
               {
    return -1;
}
unsetCycle()
void MoveNode::unsetCycle ()
Unset cycle from nodes
Exceptions
InvalidData If node is not placed
Definition at line 519 of file MoveNode.cc.
                     {
    if (placed_ == false ) {
        std::string msg = "MoveNode is not placed.";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    cycle_ = 0;
    placed_ = false;
}
References __func__, cycle_, and placed_.
Referenced by AssignmentPlan::resetAssignments(), AssignmentPlan::resetAssignments(), and AssignmentPlan::tryCachedAssignment().
unsetGuardOperation()
void MoveNode::unsetGuardOperation ()
Unsets guard operation.
Does not ask the ProgramOperation to remove this MoveNode from it's output moves.
Definition at line 771 of file MoveNode.cc.
{
    guardOp_ = ProgramOperationPtr();
}
References guardOp_.
Referenced by DataDependenceGraph::guardRestored(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), and ProgramOperation::~ProgramOperation().
unsetSourceOperation()
void MoveNode::unsetSourceOperation ()
Unsets source operation.
Does not ask the ProgramOperation to remove this MoveNode from it's output moves.
Definition at line 760 of file MoveNode.cc.
{
    srcOp_ = ProgramOperationPtr();
}
References srcOp_.
Referenced by PreOptimizer::tryToPrecalcConstantAdd(), BFUpdateMoveOnBypass::undoOnlyMe(), BFCopyRegWithOp::undoSplit(), DataDependenceGraph::unMergeUser(), and ProgramOperation::~ProgramOperation().
Member Data Documentation
cycle_
int MoveNode::cycle_ private
Cycle in which the node is placed. Each cycle uniquely identifies an instruction slot within the current scheduling scope.
Definition at line 168 of file MoveNode.hh.
Referenced by cycle(), setCycle(), and unsetCycle().
dstOps_
std::vector<ProgramOperationPtr> MoveNode::dstOps_ private
Definition at line 160 of file MoveNode.hh.
Referenced by addDestinationOperationPtr(), clearDestinationOperation(), and removeDestinationOperation().
finalized_
bool MoveNode::finalized_ private
The movenode cannot be unscheduled anymore, fixed in place.
Definition at line 174 of file MoveNode.hh.
guardOp_
ProgramOperationPtr MoveNode::guardOp_ private
Definition at line 164 of file MoveNode.hh.
Referenced by guardOperationPtr(), isGuardOperation(), setGuardOperationPtr(), and unsetGuardOperation().
immediate_
const std::shared_ptr<TTAProgram::Immediate> MoveNode::immediate_ private
Pointer to Immediate this node represents, Node itself do not change move.
Definition at line 158 of file MoveNode.hh.
Referenced by copy(), immediate(), immediate(), immediatePtr(), isAssigned(), and isImmediate().
isInFrontier_
bool MoveNode::isInFrontier_ private
This is in scheduling frontier(used in Bubblefish scheduler)
Definition at line 177 of file MoveNode.hh.
Referenced by dotString().
move_
const std::shared_ptr<TTAProgram::Move> MoveNode::move_ private
Pointer to Move this node represents, Node itself do not change move.
Definition at line 155 of file MoveNode.hh.
Referenced by copy(), earliestResultReadCycle(), guardLatency(), isAssigned(), isDestinationVariable(), isGuardOperation(), isSourceConstant(), isSourceImmediateRegister(), isSourceOperation(), isSourceRA(), isSourceVariable(), and toString().
placed_
bool MoveNode::placed_ private
True when the node placed (is given a cycle in program).
Definition at line 171 of file MoveNode.hh.
Referenced by isPlaced(), setCycle(), and unsetCycle().
srcOp_
ProgramOperationPtr MoveNode::srcOp_ private
Definition at line 162 of file MoveNode.hh.
Referenced by isSourceOperation(), setSourceOperationPtr(), sourceOperationPtr(), and unsetSourceOperation().
The documentation for this class was generated from the following files:
MoveNode.hh
MoveNode.cc