OpenASIP: DOMBuilderErrorHandler Class Reference
DOMBuilderErrorHandler Class Reference
#include <DOMBuilderErrorHandler.hh>
Public Member Functions
DOMBuilderErrorHandler ()
virtual ~DOMBuilderErrorHandler ()
bool handleError (const DOMError &domError)
int errorCount () const
std::string errorLog () const
Private Attributes
int errorCount_
Number of errors handled.
std::string errorLog_
Error log.
Detailed Description
Error handler used when validating XML files by XMLSerializer.
Definition at line 47 of file DOMBuilderErrorHandler.hh.
Constructor & Destructor Documentation
DOMBuilderErrorHandler()
DOMBuilderErrorHandler::DOMBuilderErrorHandler ()
Constructor.
Definition at line 42 of file DOMBuilderErrorHandler.cc.
                                               :
    errorCount_(0), errorLog_("") {
}
~DOMBuilderErrorHandler()
DOMBuilderErrorHandler::~DOMBuilderErrorHandler () virtual
Destructor.
Definition at line 50 of file DOMBuilderErrorHandler.cc.
{
}
Member Function Documentation
errorCount()
int DOMBuilderErrorHandler::errorCount () const
Returns the number of errors handled.
Returns
Number of errors handled.
Definition at line 91 of file DOMBuilderErrorHandler.cc.
{
    return errorCount_;
}
References errorCount_.
Referenced by XMLSerializer::readFile(), and XMLSerializer::readString().
errorLog()
string DOMBuilderErrorHandler::errorLog () const
Returns the error log.
Returns
The error log.
Definition at line 102 of file DOMBuilderErrorHandler.cc.
{
    return errorLog_;
}
References errorLog_.
Referenced by XMLSerializer::readFile(), and XMLSerializer::readString().
handleError()
bool DOMBuilderErrorHandler::handleError (const DOMError & domError)
Handler function to process errors that occur while building DOM documents.
Stores information to locate the error (URI, line number, column, diagnostic message) passed by a DOM builder to an error log. Called by DOMBuilder::parseURI.
Parameters
domError Error generated by DOM builder.
Returns
Always Boolean value 'true'.
Definition at line 66 of file DOMBuilderErrorHandler.cc.
{
    errorCount_++;
    DOMLocator* locator = domError.getLocation();
    errorLog_ += "Error at file ";
    errorLog_ += Conversion::XMLChToString(locator->getURI());
    errorLog_ += ", line ";
    errorLog_ += Conversion::toString(locator->getLineNumber());
    errorLog_ += ", column ";
    errorLog_ += Conversion::toString(locator->getColumnNumber());
    errorLog_ += "\n    Message: ";
    errorLog_ += Conversion::XMLChToString(domError.getMessage());
    errorLog_ += "\n";
    return true;
}
References errorCount_, errorLog_, Conversion::toString(), and Conversion::XMLChToString().
Member Data Documentation
errorCount_
int DOMBuilderErrorHandler::errorCount_ private
Number of errors handled.
Definition at line 58 of file DOMBuilderErrorHandler.hh.
Referenced by errorCount(), and handleError().
errorLog_
std::string DOMBuilderErrorHandler::errorLog_ private
Error log.
Definition at line 60 of file DOMBuilderErrorHandler.hh.
Referenced by errorLog(), and handleError().
The documentation for this class was generated from the following files:
DOMBuilderErrorHandler.hh
DOMBuilderErrorHandler.cc