OpenASIP: HDBEditorDeleteCmd Class Reference
HDBEditorDeleteCmd Class Reference
#include <HDBEditorDeleteCmd.hh>
Public Member Functions
HDBEditorDeleteCmd ()
virtual ~HDBEditorDeleteCmd ()
virtual bool Do ()
virtual int id () const
virtual HDBEditorDeleteCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
bool confirmDeletion (const wxString &component)
Detailed Description
Command for deleting entries from the HDB.
Definition at line 41 of file HDBEditorDeleteCmd.hh.
Constructor & Destructor Documentation
HDBEditorDeleteCmd()
HDBEditorDeleteCmd::HDBEditorDeleteCmd ()
The Constructor.
Definition at line 46 of file HDBEditorDeleteCmd.cc.
                                       :
    GUICommand(HDBEditorConstants::COMMAND_NAME_DELETE, NULL) {
}
Referenced by create().
~HDBEditorDeleteCmd()
HDBEditorDeleteCmd::~HDBEditorDeleteCmd () virtual
The Destructor.
Definition at line 54 of file HDBEditorDeleteCmd.cc.
{
}
Member Function Documentation
confirmDeletion()
bool HDBEditorDeleteCmd::confirmDeletion (const wxString & component) private
Creates a dialog box to confirm deletion.
Parameters
component Type of component to be deleted.
Returns
true if Yes was pressed, false otherwise.
Definition at line 252 of file HDBEditorDeleteCmd.cc.
{
    wxString message = _T("Are you sure you want to delete this ");
    message.Append(component);
    message.Append(_T("?"));
    MessageDialog dialog(parentWindow(), _T("Confirm deletion"), message,
        wxYES_DEFAULT | wxYES_NO);
    return dialog.ShowModal() == wxID_YES;
}
References GUICommand::parentWindow().
Referenced by Do().
create()
HDBEditorDeleteCmd * HDBEditorDeleteCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 206 of file HDBEditorDeleteCmd.cc.
{
    return new HDBEditorDeleteCmd();
}
References HDBEditorDeleteCmd().
Do()
bool HDBEditorDeleteCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 61 of file HDBEditorDeleteCmd.cc.
                       {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().browser();
    if (browser->isFUArchitectureSelected()) {
        int id = browser->selectedFUArchitecture();
        if (manager->canRemoveFUArchitecture(id)) {
            if (confirmDeletion(_T("FU Architecture"))) {
                manager->removeFUArchitecture(id);
            } else {
                return false;
            }
        } else {
            wxString message = _T("FU Architecture ");
            message.Append(WxConversion::toWxString(id));
            message.Append(_T(" cannot be removed,\n"));
            message.Append(_T("because it has an implementation."));
            InformationDialog dialog(parentWindow(), message);
            dialog.ShowModal();
            return false;
        }
    } else if (browser->isRFArchitectureSelected()) {
        int id = browser->selectedRFArchitecture();
        if (manager->canRemoveRFArchitecture(id)) {
            if (confirmDeletion(_T("RF Architecture"))) {
                manager->removeRFArchitecture(id);
            } else {
                return false;
            }
        } else {
            wxString message = _T("RF Architecture ");
            message.Append(WxConversion::toWxString(id));
            message.Append(_T(" cannot be removed,\n"));
            message.Append(_T("because it has an implementation."));
            InformationDialog dialog(parentWindow(), message);
            dialog.ShowModal();
            return false;
        }
    } else if (browser->isFUImplementationSelected()) {
        if (confirmDeletion(_T("FU Implementation"))) {
            int id = manager->fuEntryIDOfImplementation(
                browser->selectedFUImplementation());
            manager->removeFUEntry(id);
        } else {
            return false;
        }
    } else if (browser->isRFImplementationSelected()) {
        if (confirmDeletion(_T("RF Implementation"))) {
            int id = manager->rfEntryIDOfImplementation(
                browser->selectedRFImplementation());
            manager->removeRFEntry(id);
        } else {
            return false;
        }
    } else if (browser->isCostFunctionPluginSelected()) {
        if (confirmDeletion(_T("Cost Function Plugin"))) {
            int id = browser->selectedCostFunctionPlugin();
            manager->removeCostFunctionPlugin(id);
        } else {
            return false;
        }
    } else if (browser->isFUEntrySelected()) {
        if (confirmDeletion(_T("FU Entry"))) {
            int id = browser->selectedFUEntry();
            manager->removeFUEntry(id);
        } else {
            return false;
        }
    } else if (browser->isRFEntrySelected()) {
        if (confirmDeletion(_T("RF Entry"))) {
            int id = browser->selectedRFEntry();
            manager->removeRFEntry(id);
        } else {
            return false;
        }
    } else if (browser->isBusEntrySelected()) {
        if (confirmDeletion(_T("Bus Entry"))) {
            int id = browser->selectedBusEntry();
            manager->removeBusEntry(id);
        } else {
            return false;
        }
    } else if (browser->isSocketEntrySelected()) {
        if (confirmDeletion(_T("Socket Entry"))) {
            int id = browser->selectedSocketEntry();
            manager->removeSocketEntry(id);
        } else {
            return false;
        }
    } else if (browser->isOperationImplementationSelected()) {
        if (confirmDeletion(_T("Operation Implementation"))) {
            int id = browser->selectedOperationImplementation();
            manager->removeOperationImplementation(id);
        } else {
            return false;
        }
    } else if (browser->isOperationImplementationResourceSelected()) {
        if (confirmDeletion(_T("Operation Implementation Resource"))) {
            int id = browser->selectedOperationImplementationResource();
            manager->removeOperationImplementationResource(id);
        } else {
            return false;
        }
    } else {
        return false;
    }
    wxGetApp().mainFrame().update();
    return true;
}
References HDB::HDBManager::canRemoveFUArchitecture(), HDB::HDBManager::canRemoveRFArchitecture(), confirmDeletion(), HDB::HDBManager::fuEntryIDOfImplementation(), HDBBrowserWindow::isBusEntrySelected(), HDBBrowserWindow::isCostFunctionPluginSelected(), HDBBrowserWindow::isFUArchitectureSelected(), HDBBrowserWindow::isFUEntrySelected(), HDBBrowserWindow::isFUImplementationSelected(), HDBBrowserWindow::isOperationImplementationResourceSelected(), HDBBrowserWindow::isOperationImplementationSelected(), HDBBrowserWindow::isRFArchitectureSelected(), HDBBrowserWindow::isRFEntrySelected(), HDBBrowserWindow::isRFImplementationSelected(), HDBBrowserWindow::isSocketEntrySelected(), GUICommand::parentWindow(), HDB::HDBManager::removeBusEntry(), HDB::HDBManager::removeCostFunctionPlugin(), HDB::HDBManager::removeFUArchitecture(), HDB::HDBManager::removeFUEntry(), HDB::HDBManager::removeOperationImplementation(), HDB::HDBManager::removeOperationImplementationResource(), HDB::HDBManager::removeRFArchitecture(), HDB::HDBManager::removeRFEntry(), HDB::HDBManager::removeSocketEntry(), HDB::HDBManager::rfEntryIDOfImplementation(), HDBBrowserWindow::selectedBusEntry(), HDBBrowserWindow::selectedCostFunctionPlugin(), HDBBrowserWindow::selectedFUArchitecture(), HDBBrowserWindow::selectedFUEntry(), HDBBrowserWindow::selectedFUImplementation(), HDBBrowserWindow::selectedOperationImplementation(), HDBBrowserWindow::selectedOperationImplementationResource(), HDBBrowserWindow::selectedRFArchitecture(), HDBBrowserWindow::selectedRFEntry(), HDBBrowserWindow::selectedRFImplementation(), HDBBrowserWindow::selectedSocketEntry(), and WxConversion::toWxString().
icon()
std::string HDBEditorDeleteCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 184 of file HDBEditorDeleteCmd.cc.
{
    return "";
}
id()
int HDBEditorDeleteCmd::id () const virtual
Returns the command id.
Returns
Command identifier of this command.
Implements GUICommand.
Definition at line 195 of file HDBEditorDeleteCmd.cc.
{
    return HDBEditorConstants::COMMAND_DELETE;
}
References HDBEditorConstants::COMMAND_DELETE.
isEnabled()
bool HDBEditorDeleteCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 217 of file HDBEditorDeleteCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().browser();
    if (browser->isFUArchitectureSelected() ||
        browser->isRFArchitectureSelected() ||
        browser->isFUImplementationSelected() ||
        browser->isRFImplementationSelected() ||
        browser->isCostFunctionPluginSelected() ||
        browser->isFUEntrySelected() ||
        browser->isRFEntrySelected() ||
        browser->isBusEntrySelected() ||
        browser->isSocketEntrySelected() ||
        browser->isOperationImplementationSelected() ||
        browser->isOperationImplementationResourceSelected()
        ) {
        return true;
    }
    return false;
}
References HDBBrowserWindow::isBusEntrySelected(), HDBBrowserWindow::isCostFunctionPluginSelected(), HDBBrowserWindow::isFUArchitectureSelected(), HDBBrowserWindow::isFUEntrySelected(), HDBBrowserWindow::isFUImplementationSelected(), HDBBrowserWindow::isOperationImplementationResourceSelected(), HDBBrowserWindow::isOperationImplementationSelected(), HDBBrowserWindow::isRFArchitectureSelected(), HDBBrowserWindow::isRFEntrySelected(), HDBBrowserWindow::isRFImplementationSelected(), and HDBBrowserWindow::isSocketEntrySelected().
The documentation for this class was generated from the following files:
HDBEditorDeleteCmd.hh
HDBEditorDeleteCmd.cc