OpenASIP: TTAProgram::DataAddressDef Class Reference
TTAProgram::DataAddressDef Class Reference
#include <DataAddressDef.hh>
Public Member Functions
DataAddressDef (Address start, int size, Address dest, bool littleEndian)
virtual ~DataAddressDef ()
virtual bool isInitialized () const
virtual bool isAddress () const
virtual Address destinationAddress () const
virtual void setDestinationAddress (Address dest)
DataDefinition * copy () const
Public Member Functions inherited from TTAProgram::DataDefinition
DataDefinition (Address start, int size, bool littleEndian, MinimumAddressableUnit *initData=NULL, bool allZeros=false)
DataDefinition (Address start, const std::vector< MinimumAddressableUnit > &initData, bool littleEndian)
virtual ~DataDefinition ()
virtual Address startAddress () const
virtual void setStartAddress (Address start)
virtual MinimumAddressableUnit MAU (int index) const
virtual int size () const
virtual bool isInstructionAddress () const
bool isLittleEndian () const
Private Attributes
Address dest_
Destination address of a data area.
Detailed Description
Describes characteristics of a memory area containing an address.
Definition at line 45 of file DataAddressDef.hh.
Constructor & Destructor Documentation
DataAddressDef()
TTAProgram::DataAddressDef::DataAddressDef (Address start, int size, Address dest, bool littleEndian)
Creates data area definition containing address.
Parameters
start Starting address of definition.
size Number of MAUs that area represents.
dest Address where to data definition refers.
Definition at line 44 of file DataAddressDef.cc.
                                                  :
    DataDefinition(start, size, littleEndian), dest_(dest) {
}
~DataAddressDef()
TTAProgram::DataAddressDef::~DataAddressDef () virtual
Nothing to free.
Definition at line 53 of file DataAddressDef.cc.
{
}
Member Function Documentation
copy()
DataDefinition * TTAProgram::DataAddressDef::copy () const virtual
POM style copy constructor, which supports dynamic binding.
Returns
Copy of the object.
Reimplemented from TTAProgram::DataDefinition.
Definition at line 102 of file DataAddressDef.cc.
{
    DataAddressDef* newDef = new DataAddressDef(
        startAddress(), size(), destinationAddress(), isLittleEndian());
    return newDef;
}
References destinationAddress(), TTAProgram::DataDefinition::isLittleEndian(), TTAProgram::DataDefinition::size(), and TTAProgram::DataDefinition::startAddress().
destinationAddress()
Address TTAProgram::DataAddressDef::destinationAddress () const virtual
Returns destination address, where to intialization value refers.
Returns
Destination address of initialized data area.
Reimplemented from TTAProgram::DataDefinition.
Definition at line 82 of file DataAddressDef.cc.
{
    return dest_;
}
References dest_.
Referenced by copy().
isAddress()
bool TTAProgram::DataAddressDef::isAddress () const virtual
Returns true, class contains always address reference.
Returns
Always true.
Reimplemented from TTAProgram::DataDefinition.
Definition at line 72 of file DataAddressDef.cc.
{
    return true;
}
isInitialized()
bool TTAProgram::DataAddressDef::isInitialized () const virtual
Returns true, class defines always initialized data area.
Returns
Always true.
Reimplemented from TTAProgram::DataDefinition.
Definition at line 62 of file DataAddressDef.cc.
{
    return true;
}
setDestinationAddress()
void TTAProgram::DataAddressDef::setDestinationAddress (Address dest) virtual
Set new destination address for the data definition.
Parameters
dest New destination address.
Reimplemented from TTAProgram::DataDefinition.
Definition at line 92 of file DataAddressDef.cc.
{
    dest_ = dest;
}
References dest_.
Member Data Documentation
dest_
Address TTAProgram::DataAddressDef::dest_ private
Destination address of a data area.
Definition at line 60 of file DataAddressDef.hh.
Referenced by destinationAddress(), and setDestinationAddress().
The documentation for this class was generated from the following files:
DataAddressDef.hh
DataAddressDef.cc