OpenASIP: Breakpoint Class Reference
Breakpoint Class Reference
#include <Breakpoint.hh>
Public Member Functions
Breakpoint (SimulatorFrontend &frontend, InstructionAddress address)
virtual ~Breakpoint ()
virtual bool isTriggered () const
virtual std::string description () const
virtual StopPoint * copy () const
virtual InstructionAddress address () const
virtual void setAddress (InstructionAddress newAddress)
Public Member Functions inherited from StopPoint
StopPoint ()
virtual ~StopPoint ()
virtual void setEnabled (bool flag)
virtual bool isEnabled () const
virtual void setDisabledAfterTriggered (bool flag)
virtual bool isDisabledAfterTriggered () const
virtual void setDeletedAfterTriggered (bool flag)
virtual bool isDeletedAfterTriggered () const
virtual void setCondition (const ConditionScript &condition)
virtual void removeCondition ()
virtual const ConditionScript & condition () const
virtual bool isConditional () const
virtual void setIgnoreCount (unsigned int count)
virtual unsigned int ignoreCount () const
virtual bool isConditionOK ()
virtual void decreaseIgnoreCount ()
Private Member Functions
Breakpoint (const Breakpoint &source)
Static copying not allowed (should use copy()).
Private Attributes
InstructionAddress address_
The address of the breakpoint. A breakpoint is fired when PC equals this address.
SimulatorFrontend & frontend_
The simulator frontend which is used to fetch the current PC.
Additional Inherited Members
Protected Attributes inherited from StopPoint
bool enabled_
Tells whether the breakpoint is enabled or disabled.
bool disabledAfterTriggered_
Tells if the breakpoint is disabled after it is triggered the next time.
bool deletedAfterTriggered_
Tells if the breakpoint is deleted after it is triggered the next time.
bool conditional_
Tells whether the breakpoint is conditional or not.
ConditionScript * condition_
The condition which is used to determine whether the breakpoint should be fired or not.
unsigned int ignoreCount_
The number of times the condition is to be ignored before enabling the breakpoint.
Detailed Description
Represents a breakpoint in simulation.
Breakpoint stops simulation when simulation has reached the user set instruction address and general condition for stopping is true.
Definition at line 50 of file Breakpoint.hh.
Constructor & Destructor Documentation
Breakpoint() [1/2]
Breakpoint::Breakpoint (SimulatorFrontend & frontend, InstructionAddress address)
Constructor.
Parameters
address The address.
Definition at line 47 of file Breakpoint.cc.
                                :
    StopPoint(), address_(address), frontend_(frontend) {
}
~Breakpoint()
Breakpoint::~Breakpoint () virtual
Destructor.
Definition at line 56 of file Breakpoint.cc.
{
}
Breakpoint() [2/2]
Breakpoint::Breakpoint (const Breakpoint & source) private
Static copying not allowed (should use copy()).
Member Function Documentation
address()
InstructionAddress Breakpoint::address () const virtual
Returns the address the breakpoint is watching.
Returns
The address.
Definition at line 86 of file Breakpoint.cc.
{
    return address_;
}
References address_.
Referenced by ProximDisassemblyGridTable::GetValue(), ProximBreakpointWindow::onBreakpointLookup(), ProximDisassemblyWindow::onRightClick(), and ProximBreakpointWindow::refreshStopPoints().
copy()
StopPoint * Breakpoint::copy () const virtual
Copy method for dynamically bound copies.
Implements StopPoint.
Definition at line 63 of file Breakpoint.cc.
                       {
    StopPoint* aCopy = new Breakpoint(frontend_, address_);
    if (conditional_) {
        assert(condition_ != NULL);
        ConditionScript* conditionCopy = condition_->copy();
        assert(conditionCopy != NULL);
        aCopy->setCondition(*conditionCopy);
    } else {
        aCopy->removeCondition();
    }
    aCopy->setEnabled(enabled_);
    aCopy->setDisabledAfterTriggered(disabledAfterTriggered_);
    aCopy->setDeletedAfterTriggered(deletedAfterTriggered_);
    aCopy->setIgnoreCount(ignoreCount_);
    return aCopy;
}
References address_, assert, StopPoint::condition_, StopPoint::conditional_, ConditionScript::copy(), StopPoint::deletedAfterTriggered_, StopPoint::disabledAfterTriggered_, StopPoint::enabled_, frontend_, StopPoint::ignoreCount_, StopPoint::removeCondition(), StopPoint::setCondition(), StopPoint::setDeletedAfterTriggered(), StopPoint::setDisabledAfterTriggered(), StopPoint::setEnabled(), and StopPoint::setIgnoreCount().
description()
std::string Breakpoint::description () const virtual
Prints the description string of the stop point.
Each subclass overrides this method to construct a descripting string of itself.
Implements StopPoint.
Definition at line 120 of file Breakpoint.cc.
{
    return std::string("at address ") + Conversion::toString(address_) +
        std::string(" ") + StopPoint::description();
}
References address_, StopPoint::description(), and Conversion::toString().
isTriggered()
bool Breakpoint::isTriggered () const virtual
Returns true in case this break point is triggered.
In case the current program counter is the address this break point is watching, and the general condition is ok, this method returns true.
Returns
The status of the breakpoint.
Implements StopPoint.
Definition at line 109 of file Breakpoint.cc.
{
    return frontend_.programCounter() == address_;
}
References address_, frontend_, and SimulatorFrontend::programCounter().
setAddress()
void Breakpoint::setAddress (InstructionAddress newAddress) virtual
Sets the address the breakpoint is watching.
Parameters
newAddress The address.
Definition at line 96 of file Breakpoint.cc.
{
    address_ = newAddress;
}
References address_.
Referenced by SimControlLanguageCommand::parseBreakpoint().
Member Data Documentation
address_
InstructionAddress Breakpoint::address_ private
The address of the breakpoint. A breakpoint is fired when PC equals this address.
Definition at line 67 of file Breakpoint.hh.
Referenced by address(), copy(), description(), isTriggered(), and setAddress().
frontend_
SimulatorFrontend& Breakpoint::frontend_ private
The simulator frontend which is used to fetch the current PC.
Definition at line 69 of file Breakpoint.hh.
Referenced by copy(), and isTriggered().
The documentation for this class was generated from the following files:
Breakpoint.hh
Breakpoint.cc