OpenASIP: OperationContext Class Reference
OperationContext Class Reference
#include <OperationContext.hh>
Public Types
typedef std::map< std::string, OperationState * > StateRegistry
Type of state registry.
Public Member Functions
OperationContext ()
OperationContext (const TCEString &name)
OperationContext (Memory *memory, InstructionAddress &programCounter, SimValue &returnAddress, int delayCycles)
OperationContext (const OperationContext &)
OperationState & state (const char *name) const
void setStateRegistry (StateRegistry &stateRegistry)
void unsetStateRegistry ()
StateRegistry & stateRegistry ()
virtual ~OperationContext ()
Memory & memory ()
const Memory & memory () const
void setMemory (Memory *memory)
int contextId () const
InstructionAddress & programCounter ()
const InstructionAddress & programCounter () const
void setUpdateProgramCounter (bool value)
bool updateProgramCounter () const
void setSaveReturnAddress (bool value)
bool saveReturnAddress ()
SimValue & returnAddress ()
const SimValue & returnAddress () const
void advanceClock ()
bool isEmpty () const
bool hasMemoryModel () const
const TCEString & functionUnitName () const
int branchDelayCycles () const
void registerState (OperationState *state)
void unregisterState (const char *name)
CycleCount cycleCount () const
void setCycleCountVariable (CycleCount &cycleCount)
Private Member Functions
OperationContext & operator= (const OperationContext &)
Assignment not allowed.
Private Attributes
OperationContextPimpl * pimpl_
Implementation in separate source file to speed up compiling.
Detailed Description
OperationContext is used to store any implementation and context dependent data that may affect the result of an operation.
In typical client applications, operation implementations are related to a function unit.
Definition at line 56 of file OperationContext.hh.
Member Typedef Documentation
StateRegistry
typedef std::map<std::string, OperationState*> OperationContext::StateRegistry
Type of state registry.
Definition at line 72 of file OperationContext.hh.
Constructor & Destructor Documentation
OperationContext() [1/4]
OperationContext::OperationContext ()
Constructor for contexts suitable for basic operations.
Definition at line 48 of file OperationContext.cc.
                                   : pimpl_(new OperationContextPimpl(DEFAULT_FU_NAME)) {
}
OperationContext() [2/4]
OperationContext::OperationContext (const TCEString & name)
Constructor for basic operations in simulation – FU name passed.
Definition at line 54 of file OperationContext.cc.
                                                        : pimpl_(new OperationContextPimpl(name)) {
}
OperationContext() [3/4]
OperationContext::OperationContext (Memory * memory, InstructionAddress & programCounter, SimValue & returnAddress, int delayCycles)
Constructor for contexts suitable for any kinds of operations.
Parameters
memory The memory model instance.
programCounter The program counter register.
returnAddress The return address register.
Definition at line 65 of file OperationContext.cc.
                     :
    pimpl_(new OperationContextPimpl(
               DEFAULT_FU_NAME, memory, programCounter,
               returnAddress, delayCycles)) {
}
OperationContext() [4/4]
OperationContext::OperationContext (const OperationContext & context)
A copy constructor that performs a deep copy for the pimpl_
Parameters
context OperationContext
Definition at line 80 of file OperationContext.cc.
                                                                  :
    pimpl_(new OperationContextPimpl(*context.pimpl_)) {
}
~OperationContext()
OperationContext::~OperationContext () virtual
Destructor. Deletes the pimpl object
Definition at line 87 of file OperationContext.cc.
{
    delete pimpl_;
    pimpl_ = NULL;
}
References pimpl_.
Member Function Documentation
advanceClock()
void OperationContext::advanceClock ()
Advances the internal clock of each registered operation state object.
Definition at line 108 of file OperationContext.cc.
{
    pimpl_->advanceClock(*this);
}
References OperationContextPimpl::advanceClock(), and pimpl_.
Referenced by FUState::advanceClock(), GCUState::advanceClock(), and SimulateDialog::onAdvanceClock().
branchDelayCycles()
int OperationContext::branchDelayCycles () const
Returns the amount of pipeline delay cycles.
Definition at line 308 of file OperationContext.cc.
{
    return pimpl_->branchDelayCycles();
}
References OperationContextPimpl::branchDelayCycles(), and pimpl_.
Referenced by OperationDAGBehavior::areValid().
contextId()
int OperationContext::contextId () const
Returns the unique id of the OperationContext instance.
Returns
The unique id for the OperationContext instance.
Definition at line 266 of file OperationContext.cc.
{
    return pimpl_->contextId();
}
References OperationContextPimpl::contextId(), and pimpl_.
cycleCount()
CycleCount OperationContext::cycleCount () const
Returns the elapsed time since the beginning of simulation.
Can be used to implement real time timer operations, etc. Uses the simulator's cycle count, if available, otherwise uses internal cycle counter that is incremented with the advanceClock();
Definition at line 288 of file OperationContext.cc.
{
    return pimpl_->cycleCount();
}
References OperationContextPimpl::cycleCount(), and pimpl_.
Referenced by setCycleCountVariable().
functionUnitName()
const TCEString & OperationContext::functionUnitName () const
Returns the FU name of the OperationContext instance.
Returns
The FU name for the OperationContext instance.
Definition at line 276 of file OperationContext.cc.
{
    return pimpl_->functionUnitName();
}
References OperationContextPimpl::functionUnitName(), and pimpl_.
hasMemoryModel()
bool OperationContext::hasMemoryModel () const
isEmpty()
bool OperationContext::isEmpty () const
Returns true if there are no operation state objects stored in the context.
Returns
True if there are no operation state objects stored in the context.
Definition at line 224 of file OperationContext.cc.
{
    return pimpl_->isEmpty();
}
References OperationContextPimpl::isEmpty(), and pimpl_.
Referenced by FUState::advanceClock().
memory() [1/2]
Memory & OperationContext::memory ()
Returns a reference to a Memory Module wrapper instance.
This instance can be accessed by the function unit and behavior simulation methods to simulate memory access.
Returns
The Memory instance.
Definition at line 251 of file OperationContext.cc.
{
    return pimpl_->memory();
}
References OperationContextPimpl::memory(), and pimpl_.
Referenced by setMemory().
memory() [2/2]
const Memory & OperationContext::memory () const
Definition at line 256 of file OperationContext.cc.
{
    return pimpl_->memory();
}
References OperationContextPimpl::memory(), and pimpl_.
operator=()
OperationContext & OperationContext::operator= (const OperationContext &) private
Assignment not allowed.
programCounter() [1/2]
InstructionAddress & OperationContext::programCounter ()
Returns a reference to the current value of the program counter register.
The value of the program counter can be changed through this reference. This is used to implement control transfer operations like jumps and calls to subroutines.
Returns
The program counter value as a reference.
Definition at line 152 of file OperationContext.cc.
{
    return pimpl_->programCounter();
}
References pimpl_, and OperationContextPimpl::programCounter().
Referenced by OperationDAGBehavior::areValid(), CmdTrigger::execute(), SimulationInfoDialog::handleEvent(), TesterContext::programCounter(), TransportPipeline::startOperation(), and SimulationInfoDialog::updateList().
programCounter() [2/2]
const InstructionAddress & OperationContext::programCounter () const
Definition at line 157 of file OperationContext.cc.
{
    return pimpl_->programCounter();
}
References pimpl_, and OperationContextPimpl::programCounter().
registerState()
void OperationContext::registerState (OperationState * stateToRegister)
Registers the operation state for given name.
Called in the createState() of the custom OperationBehavior classes. If state with given identifier is already found in the context, program is aborted. This method is only for internal use. Used by the macro definitions of OSAL.hh.
Parameters
name The identifier for the registered state instance.
stateToRegister The state instance.
Definition at line 124 of file OperationContext.cc.
{
    pimpl_->registerState(stateToRegister);
}
References pimpl_, and OperationContextPimpl::registerState().
returnAddress() [1/2]
SimValue & OperationContext::returnAddress ()
Returns a reference to the current value of the return address register.
The value of the return address can be changed through this reference. This is used in implementing calls to subroutines.
Returns
The return address value as a reference.
Definition at line 207 of file OperationContext.cc.
{
    return pimpl_->returnAddress();
}
References pimpl_, and OperationContextPimpl::returnAddress().
Referenced by OperationDAGBehavior::areValid(), CmdTrigger::execute(), SimulationInfoDialog::handleEvent(), TesterContext::returnAddress(), TransportPipeline::startOperation(), and SimulationInfoDialog::updateList().
returnAddress() [2/2]
const SimValue & OperationContext::returnAddress () const
Definition at line 212 of file OperationContext.cc.
{
    return pimpl_->returnAddress();
}
References pimpl_, and OperationContextPimpl::returnAddress().
saveReturnAddress()
bool OperationContext::saveReturnAddress ()
Returns true if RA should saved before executing next control flow operation.
Returns
The return address value as a reference.
Definition at line 194 of file OperationContext.cc.
{
    return pimpl_->saveReturnAddress();
}
References pimpl_, and OperationContextPimpl::saveReturnAddress().
Referenced by CmdTrigger::execute(), and TransportPipeline::startOperation().
setCycleCountVariable()
void OperationContext::setCycleCountVariable (CycleCount & cycleCount)
Sets the variable that contains the current simulation cycle count at the best possible accuracy.
Used by real time operations to track simulation time during simulations.
Definition at line 300 of file OperationContext.cc.
{
    pimpl_->setCycleCountVariable(cycleCount);
}
References cycleCount(), pimpl_, and OperationContextPimpl::setCycleCountVariable().
Referenced by SimulationController::SimulationController().
setMemory()
void OperationContext::setMemory (Memory * memory)
Sets the reference to a Memory Module instance.
This instance can be accessed by the function unit and behavior simulation methods to simulate memory access.
Parameters
memory The Memory instance.
Definition at line 238 of file OperationContext.cc.
{
    pimpl_->setMemory(memory);
}
References memory(), pimpl_, and OperationContextPimpl::setMemory().
Referenced by main(), MemoryAccessingFUState::MemoryAccessingFUState(), and MemoryAccessingFUState::MemoryAccessingFUState().
setSaveReturnAddress()
void OperationContext::setSaveReturnAddress (bool value)
Makes the return address to be saved in the RA register.
This is used by CALL instruction to save the RA before jumping.
Parameters
value Value to set to.
Returns
The return address value as a reference.
Definition at line 183 of file OperationContext.cc.
{
    pimpl_->setSaveReturnAddress(value);
}
References pimpl_, and OperationContextPimpl::setSaveReturnAddress().
Referenced by TransportPipeline::startOperation().
setStateRegistry()
void OperationContext::setStateRegistry (StateRegistry & stateRegistry)
Definition at line 313 of file OperationContext.cc.
{
    pimpl_->setStateRegistry(stateRegistry);
}
References pimpl_, OperationContextPimpl::setStateRegistry(), and stateRegistry().
Referenced by TransportPipeline::TransportPipeline().
setUpdateProgramCounter()
void OperationContext::setUpdateProgramCounter (bool value)
Definition at line 162 of file OperationContext.cc.
{
    pimpl_->setUpdateProgramCounter(value);
}
References pimpl_, and OperationContextPimpl::setUpdateProgramCounter().
Referenced by TransportPipeline::startOperation().
state()
OperationState & OperationContext::state (const char * name) const
Looks up the (concrete) operation state identified by the string name.
Parameters
name The state identifier.
Returns
The found operation state instance.
Exceptions
KeyNotFound If state by name couldn't be found.
Definition at line 100 of file OperationContext.cc.
{
    return pimpl_->state(name);
}
References pimpl_, and OperationContextPimpl::state().
stateRegistry()
OperationContext::StateRegistry & OperationContext::stateRegistry ()
Definition at line 323 of file OperationContext.cc.
{
    return pimpl_->stateRegistry();
}
References pimpl_, and OperationContextPimpl::stateRegistry().
Referenced by setStateRegistry(), and TransportPipeline::TransportPipeline().
unregisterState()
void OperationContext::unregisterState (const char * name)
Unregisters the operation state of given name.
This method is only for internal use. Used by the macro definitions of OSAL.hh.
Called in deleteState() of the custom OperationBehavior classes. Aborts if there's no state with given identifier in the context.
Definition at line 138 of file OperationContext.cc.
{
    pimpl_->unregisterState(name);
}
References pimpl_, and OperationContextPimpl::unregisterState().
unsetStateRegistry()
void OperationContext::unsetStateRegistry ()
Definition at line 318 of file OperationContext.cc.
{
    pimpl_->unsetStateRegistry();
}
References pimpl_, and OperationContextPimpl::unsetStateRegistry().
Referenced by TransportPipeline::~TransportPipeline().
updateProgramCounter()
bool OperationContext::updateProgramCounter () const
Definition at line 169 of file OperationContext.cc.
{
    return pimpl_->updateProgramCounter();
}
References pimpl_, and OperationContextPimpl::updateProgramCounter().
Referenced by TransportPipeline::startOperation().
Member Data Documentation
pimpl_
OperationContextPimpl* OperationContext::pimpl_ private
Implementation in separate source file to speed up compiling.
Definition at line 113 of file OperationContext.hh.
Referenced by advanceClock(), branchDelayCycles(), contextId(), cycleCount(), functionUnitName(), isEmpty(), memory(), memory(), programCounter(), programCounter(), registerState(), returnAddress(), returnAddress(), saveReturnAddress(), setCycleCountVariable(), setMemory(), setSaveReturnAddress(), setStateRegistry(), setUpdateProgramCounter(), state(), stateRegistry(), unregisterState(), unsetStateRegistry(), updateProgramCounter(), and ~OperationContext().
The documentation for this class was generated from the following files:
OperationContext.hh
OperationContext.cc