OpenASIP: SetFUArchitectureCmd Class Reference
SetFUArchitectureCmd Class Reference
#include <SetFUArchitectureCmd.hh>
Public Member Functions
SetFUArchitectureCmd ()
virtual ~SetFUArchitectureCmd ()
virtual bool Do ()
virtual int id () const
virtual SetFUArchitectureCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for setting architecture of a FUEntry.
Definition at line 41 of file SetFUArchitectureCmd.hh.
Constructor & Destructor Documentation
SetFUArchitectureCmd()
SetFUArchitectureCmd::SetFUArchitectureCmd ()
The Constructor.
Definition at line 48 of file SetFUArchitectureCmd.cc.
                                           :
    GUICommand(HDBEditorConstants::COMMAND_NAME_SET_FU_ARCH, NULL) {
}
Referenced by create().
~SetFUArchitectureCmd()
SetFUArchitectureCmd::~SetFUArchitectureCmd () virtual
The Destructor.
Definition at line 56 of file SetFUArchitectureCmd.cc.
{
}
Member Function Documentation
create()
SetFUArchitectureCmd * SetFUArchitectureCmd::create () const virtual
Creates and returns a new instance of the command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 131 of file SetFUArchitectureCmd.cc.
{
    return new SetFUArchitectureCmd();
}
References SetFUArchitectureCmd().
Do()
bool SetFUArchitectureCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 63 of file SetFUArchitectureCmd.cc.
{
    HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    const FUEntry* entry = manager->fuByID(
        wxGetApp().mainFrame().browser()->selectedFUEntry());
    wxString fus[1000];
    const std::set<RowID> fuIDs = manager->fuArchitectureIDs();
    std::set<RowID>::iterator iter = fuIDs.begin();
    int i = 0;
    for (;iter != fuIDs.end(); iter++) {
        fus[i] = WxConversion::toWxString(*iter);
        i++;
    }
    wxSingleChoiceDialog choicer(
        parentWindow(), _T("Choose Architecture"), _T("Choose Architecture"),
        i, fus);
    if (choicer.ShowModal() != wxID_OK) {
        return false;
    }
    std::string archID = WxConversion::toString(choicer.GetStringSelection());
    RowID rowID = Conversion::toInt(archID);
    manager->unsetArchitectureForFU(entry->id());
    manager->setArchitectureForFU(entry->id(), rowID);
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectFUEntry(entry->id());
    return true;
}
References HDB::HDBManager::fuArchitectureIDs(), HDB::HDBEntry::id(), GUICommand::parentWindow(), HDB::HDBManager::setArchitectureForFU(), Conversion::toInt(), WxConversion::toString(), WxConversion::toWxString(), and HDB::HDBManager::unsetArchitectureForFU().
icon()
std::string SetFUArchitectureCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 108 of file SetFUArchitectureCmd.cc.
{
    return "";
}
id()
int SetFUArchitectureCmd::id () const virtual
Returns the command id.
Returns
Command identifier for this command.
Implements GUICommand.
Definition at line 120 of file SetFUArchitectureCmd.cc.
{
    return HDBEditorConstants::COMMAND_SET_FU_ARCH;
}
References HDBEditorConstants::COMMAND_SET_FU_ARCH.
isEnabled()
bool SetFUArchitectureCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 141 of file SetFUArchitectureCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (!browser->isFUEntrySelected() ||
        manager->fuByID(browser->selectedFUEntry())->hasArchitecture()) {
        return false;
    }
    return true;
}
References HDBBrowserWindow::isFUEntrySelected(), and HDBBrowserWindow::selectedFUEntry().
The documentation for this class was generated from the following files:
SetFUArchitectureCmd.hh
SetFUArchitectureCmd.cc