OpenASIP: ProDeIUEditPolicy Class Reference
ProDeIUEditPolicy Class Reference
#include <ProDeIUEditPolicy.hh>
Public Member Functions
ProDeIUEditPolicy ()
virtual ~ProDeIUEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ProDeIUEditPolicy & operator= (ProDeIUEditPolicy &old)
Assignment not allowed.
ProDeIUEditPolicy (ProDeIUEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how an immediate unit EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports the Request.
Definition at line 49 of file ProDeIUEditPolicy.hh.
Constructor & Destructor Documentation
ProDeIUEditPolicy() [1/2]
ProDeIUEditPolicy::ProDeIUEditPolicy ()
The Constructor.
Definition at line 56 of file ProDeIUEditPolicy.cc.
                                    : EditPolicy() {
}
~ProDeIUEditPolicy()
ProDeIUEditPolicy::~ProDeIUEditPolicy () virtual
The Destructor.
Definition at line 62 of file ProDeIUEditPolicy.cc.
{
}
ProDeIUEditPolicy() [2/2]
ProDeIUEditPolicy::ProDeIUEditPolicy (ProDeIUEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeIUEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 123 of file ProDeIUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
    type == Request::DELETE_REQUEST ||
        type == Request::COPY_REQUEST ||
        type == Request::STATUS_REQUEST) {
    return true;
    } else {
    return false;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, Request::MODIFY_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProDeIUEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 72 of file ProDeIUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifyIUCmd* modifyCmd = new ModifyIUCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteIUCmd* deleteCmd = new DeleteIUCmd(host_);
        return deleteCmd;
    } else if (type == Request::COPY_REQUEST) {
        CopyComponent* copyCmd = new CopyComponent(host_);
        return copyCmd;
    } else if (type == Request::STATUS_REQUEST) {
        ImmediateUnit* iu = dynamic_cast<ImmediateUnit*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(
            ProDeTextGenerator::STATUS_IMMEDIATE_UNIT);
        string extension = "";
        if (iu->extensionMode() == Machine::SIGN) {
            extension = generator->text(
                ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN).str();
        } else if (iu->extensionMode() == Machine::ZERO) {
            extension = generator->text(
                ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO).str();
        } else {
            // unknown extension
            assert(false);
        }
        fmt % iu->name() % Conversion::toString(iu->numberOfRegisters()) %
            Conversion::toString(iu->width()) % extension;
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else {
    return NULL;
    }
}
References assert, Request::COPY_REQUEST, Request::DELETE_REQUEST, TTAMachine::ImmediateUnit::extensionMode(), EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Machine::SIGN, ProDeTextGenerator::STATUS_IMMEDIATE_UNIT, Request::STATUS_REQUEST, Texts::TextGenerator::text(), Conversion::toString(), ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN, ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO, Request::type(), TTAMachine::BaseRegisterFile::width(), and TTAMachine::Machine::ZERO.
operator=()
ProDeIUEditPolicy & ProDeIUEditPolicy::operator= (ProDeIUEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeIUEditPolicy.hh
ProDeIUEditPolicy.cc