OpenASIP: OperationPropertyDialog Class Reference
OperationPropertyDialog Class Reference
#include <OperationPropertyDialog.hh>
Public Member Functions
OperationPropertyDialog (wxWindow *parent, Operation *op, OperationModule &module, const std::string &path)
virtual ~OperationPropertyDialog ()
Operation * operation () const
Private Types
enum {
ID_TEXT_NAME = 1000 , ID_NAME , ID_READS_MEMORY , ID_WRITES_MEMORY ,
ID_CAN_TRAP , ID_HAS_SIDE_EFFECTS , ID_CLOCKED , ID_AFFECTED_BY ,
ID_OPERATION_AFFECTED_BY , ID_AFFECTED_ADD_BUTTON , ID_AFFECTED_DELETE_BUTTON , ID_INPUT_OPERANDS ,
ID_INPUT_UP_BUTTON , ID_INPUT_DOWN_BUTTON , ID_INPUT_ADD_BUTTON , ID_INPUT_MODIFY_BUTTON ,
ID_INPUT_DELETE_BUTTON , ID_AFFECTS , ID_OPERATION_AFFECTS , ID_AFFECTS_ADD_BUTTON ,
ID_AFFECTS_DELETE_BUTTON , ID_OUTPUT_OPERANDS , ID_OUTPUT_UP_BUTTON , ID_OUTPUT_DOWN_BUTTON ,
ID_OUTPUT_ADD_BUTTON , ID_OUTPUT_MODIFY_BUTTON , ID_OUTPUT_DELETE_BUTTON , ID_OPEN_BUTTON ,
ID_DAG_BUTTON , ID_OK_BUTTON , ID_TEXT_CTRL , ID_TEXT_OPEN ,
ID_EDIT_DESCRIPTION
}
Private Member Functions
OperationPropertyDialog (const OperationPropertyDialog &)
Copying not allowed.
OperationPropertyDialog & operator= (const OperationPropertyDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
wxBitmap createBitmaps (size_t index)
virtual bool TransferDataToWindow ()
void updateOperands ()
void updateIndex ()
void updateDAG ()
void updateAffected ()
void updateTypes ()
void onSelection (wxListEvent &event)
void onAddAffectedBy (wxCommandEvent &event)
void onDeleteAffectedBy (wxCommandEvent &event)
void onAddAffects (wxCommandEvent &event)
void onDeleteAffects (wxCommandEvent &event)
void onAddInputOperand (wxCommandEvent &event)
void onModifyInputOperand (wxCommandEvent &event)
void onDeleteInputOperand (wxCommandEvent &event)
void onAddOutputOperand (wxCommandEvent &event)
void onModifyOutputOperand (wxCommandEvent &event)
void onDeleteOutputOperand (wxCommandEvent &event)
void onMoveInputUp (wxCommandEvent &event)
void onMoveInputDown (wxCommandEvent &event)
void onMoveOutputUp (wxCommandEvent &event)
void onMoveOutputDown (wxCommandEvent &event)
void onOpen (wxCommandEvent &event)
void onOpenDAG (wxCommandEvent &event)
void onSaveDAG (wxCommandEvent &event)
void onUndoDAG (wxCommandEvent &event)
void onDeleteDAG (wxCommandEvent &event)
void onNewDAG (wxCommandEvent &event)
void onDAGChange (wxCommandEvent &event)
void onComboBoxChange (wxCommandEvent &event)
void moveUp (std::vector< Operand * > &ops, int id, wxListCtrl *list)
void moveDown (std::vector< Operand * > &ops, int id, wxListCtrl *list)
std::vector< std::string > getSelectedItems (wxListCtrl *listCtrl)
void onOk (wxCommandEvent &event)
ObjectState * saveOperation ()
void setTexts ()
void setBehaviorLabel ()
void launchEditor (const std::string &cmd)
void updateSwapLists (std::vector< std::string > deletedOperands)
void updateOperation (bool newOpDag)
Private Attributes
wxStaticBoxSizer * inputSizer_
Input operand sizer.
wxStaticBoxSizer * outputSizer_
Output operand sizer.
wxStaticBoxSizer * affectsSizer_
Affects sizer.
wxStaticBoxSizer * affectedBySizer_
Affected by sizer.
wxListCtrl * affectedByList_
List of affected by operations.
wxListCtrl * affectsList_
List of affects operations.
wxListCtrl * inputOperandList_
List of input operands.
wxListCtrl * outputOperandList_
List of output operands.
wxComboBox * affectedByChoice_
Choice box for new affected by operations.
wxComboBox * affectsChoice_
Choice box for new affects operations.
wxCheckBox * readMemoryCB_
Read memory check box.
wxCheckBox * writeMemoryCB_
Write memory check box.
wxCheckBox * canTrapCB_
Can trap check box.
wxCheckBox * sideEffectsCB_
Has side effects check box.
wxCheckBox * clockedCB_
Clocked check box.
Operation * operation_
Operation to be created or to be modified.
ObjectState * orig_
Original operation's ObjectState tree.
wxString name_
Name of the operation.
OperationModule & module_
Module in which operation belongs to.
std::string path_
Path in which module belongs to.
bool readMemory_
Does operation read memory?
bool writeMemory_
Does operation write memory?
bool canTrap_
Can operation trap?
bool hasSideEffects_
Does operation has side effects?
bool clocked_
Is operation clocked?
bool controlFlow_
Can operation can change program flow.
bool isCall_
Operation performs function call.
bool isBranch_
Operation is branch.
wxTextCtrl * editDescription_
std::vector< Operand * > inputOperands_
Input operands.
std::vector< Operand * > outputOperands_
Output operands.
std::vector< std::string > affects_
Operations that affects this operation.
std::vector< std::string > affectedBy_
Operations that are affected by this operation.
bool operationWasCreatedHere_
Detailed Description
Dialog which is used to create or modify an operation.
Definition at line 51 of file OperationPropertyDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_TEXT_NAME
ID_NAME
ID_READS_MEMORY
ID_WRITES_MEMORY
ID_CAN_TRAP
ID_HAS_SIDE_EFFECTS
ID_CLOCKED
ID_AFFECTED_BY
ID_OPERATION_AFFECTED_BY
ID_AFFECTED_ADD_BUTTON
ID_AFFECTED_DELETE_BUTTON
ID_INPUT_OPERANDS
ID_INPUT_UP_BUTTON
ID_INPUT_DOWN_BUTTON
ID_INPUT_ADD_BUTTON
ID_INPUT_MODIFY_BUTTON
ID_INPUT_DELETE_BUTTON
ID_AFFECTS
ID_OPERATION_AFFECTS
ID_AFFECTS_ADD_BUTTON
ID_AFFECTS_DELETE_BUTTON
ID_OUTPUT_OPERANDS
ID_OUTPUT_UP_BUTTON
ID_OUTPUT_DOWN_BUTTON
ID_OUTPUT_ADD_BUTTON
ID_OUTPUT_MODIFY_BUTTON
ID_OUTPUT_DELETE_BUTTON
ID_OPEN_BUTTON
ID_DAG_BUTTON
ID_OK_BUTTON
ID_TEXT_CTRL
ID_TEXT_OPEN
ID_EDIT_DESCRIPTION
Definition at line 118 of file OperationPropertyDialog.hh.
         {
        ID_TEXT_NAME = 1000,
        ID_NAME,
        ID_READS_MEMORY,
        ID_WRITES_MEMORY,
        ID_CAN_TRAP,
        ID_HAS_SIDE_EFFECTS,
        ID_CLOCKED,
        ID_AFFECTED_BY,
        ID_OPERATION_AFFECTED_BY,
        ID_AFFECTED_ADD_BUTTON,
        ID_AFFECTED_DELETE_BUTTON,
        ID_INPUT_OPERANDS,
        ID_INPUT_UP_BUTTON,
        ID_INPUT_DOWN_BUTTON,
        ID_INPUT_ADD_BUTTON,
        ID_INPUT_MODIFY_BUTTON,
        ID_INPUT_DELETE_BUTTON,
        ID_AFFECTS,
        ID_OPERATION_AFFECTS,
        ID_AFFECTS_ADD_BUTTON,
        ID_AFFECTS_DELETE_BUTTON,
        ID_OUTPUT_OPERANDS,
        ID_OUTPUT_UP_BUTTON,
        ID_OUTPUT_DOWN_BUTTON,
        ID_OUTPUT_ADD_BUTTON,
        ID_OUTPUT_MODIFY_BUTTON,
        ID_OUTPUT_DELETE_BUTTON,
        ID_OPEN_BUTTON,
        ID_DAG_BUTTON,
        ID_OK_BUTTON,
        ID_TEXT_CTRL,
        ID_TEXT_OPEN,
        ID_EDIT_DESCRIPTION
    };
Constructor & Destructor Documentation
OperationPropertyDialog() [1/2]
OperationPropertyDialog::OperationPropertyDialog (wxWindow * parent, Operation * op, OperationModule & module, const std::string & path)
Constructor.
Parameters
parent The parent window.
op Operation to be created or modified.
module Module in which operation belongs to.
path Path in which module belongs to.
Definition at line 122 of file OperationPropertyDialog.cc.
                            :
     wxDialog(
         parent, -1, _T(""),
         DialogPosition::getPosition(DialogPosition::DIALOG_PROPERTIES),
         wxDefaultSize, wxRESIZE_BORDER),
     operation_(op), name_(_T("")), module_(module), path_(path),
     operationWasCreatedHere_(false) {
    createContents(this, true, true);
    affectedByList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_AFFECTED_BY));
    affectsList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_AFFECTS));
    inputOperandList_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_INPUT_OPERANDS));
    outputOperandList_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OUTPUT_OPERANDS));
    affectedByChoice_ =
        dynamic_cast<wxComboBox*>(FindWindow(ID_OPERATION_AFFECTED_BY));
    affectsChoice_ =
        dynamic_cast<wxComboBox*>(FindWindow(ID_OPERATION_AFFECTS));
    readMemoryCB_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_READS_MEMORY));
    writeMemoryCB_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_WRITES_MEMORY));
    canTrapCB_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_CAN_TRAP));
    sideEffectsCB_ =
        dynamic_cast<wxCheckBox*>(FindWindow(ID_HAS_SIDE_EFFECTS));
    clockedCB_ =
        dynamic_cast<wxCheckBox*>(FindWindow(ID_CLOCKED));
    editDescription_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_EDIT_DESCRIPTION));
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_READS_MEMORY)->SetValidator(
        wxGenericValidator(&readMemory_));
    FindWindow(ID_WRITES_MEMORY)->SetValidator(
        wxGenericValidator(&writeMemory_));
    FindWindow(ID_CAN_TRAP)->SetValidator(wxGenericValidator(&canTrap_));
    FindWindow(ID_HAS_SIDE_EFFECTS)->SetValidator(
        wxGenericValidator(&hasSideEffects_));
    FindWindow(ID_CLOCKED)->SetValidator(
        wxGenericValidator(&clocked_));
    // set OK button as default choice
    FindWindow(ID_OK_BUTTON)->SetFocus();
    if (operation_ != NULL) {
        for (int i = 1; i <= operation_->numberOfInputs(); i++) {
            Operand* op = new Operand(operation_->operand(i));
            inputOperands_.push_back(op);
        }
        for (int i = operation_->numberOfInputs() + 1;
             i <= operation_->numberOfInputs() + operation_->numberOfOutputs(); i++) {
            Operand* op = new Operand(operation_->operand(i));
            outputOperands_.push_back(op);
        }
        for (int i = 0; i < operation_->affectsCount(); i++) {
            affects_.push_back(operation_->affects(i));
        }
        for (int i = 0; i < operation_->affectedByCount(); i++) {
            affectedBy_.push_back(operation_->affectedBy(i));
        }
    } else {
        operation_ = new Operation("", NullOperationBehavior::instance());
        operationWasCreatedHere_ = true;
    }
    orig_ = operation_->saveState(); // save original operation's state
    setTexts();
}
References NullOperationBehavior::instance().
~OperationPropertyDialog()
OperationPropertyDialog::~OperationPropertyDialog () virtual
Destructor.
Definition at line 209 of file OperationPropertyDialog.cc.
{
    for (unsigned int i = 0; i < inputOperands_.size(); i++) {
        delete inputOperands_[i];
    }
    for (unsigned int i = 0; i < outputOperands_.size(); i++) {
        delete outputOperands_[i];
    }
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_PROPERTIES, point);
    if (operationWasCreatedHere_) {
        delete operation_;
        operation_ = NULL;
    }
}
References DialogPosition::DIALOG_PROPERTIES, inputOperands_, operation_, operationWasCreatedHere_, outputOperands_, and DialogPosition::setPosition().
OperationPropertyDialog() [2/2]
OperationPropertyDialog::OperationPropertyDialog (const OperationPropertyDialog &) private
Copying not allowed.
Member Function Documentation
createBitmaps()
wxBitmap OperationPropertyDialog::createBitmaps (size_t index) private
Creates the bitmaps.
NOTE! This function was created by wxDesigner.
Parameters
index Index of the bitmap.
Returns
The bitmap.
Definition at line 1507 of file OperationPropertyDialog.cc.
{
    if (index == 0)
    {
        /* XPM */
        static const char *xpm_data[] = {
            /* columns rows colors chars-per-pixel */
            "16 30 2 1",
            "  c None",
            "a c Black",
            /* pixels */
            "                ",
            "                ",
            "                ",
            "       aa       ",
            "      aaaa      ",
            "     aaaaaa     ",
            "    aa aa aa    ",
            "   aa  aa  aa   ",
            "  aa   aa   aa  ",
            " aa    aa    aa ",
            " a     aa     a ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "                "
        };
        wxBitmap bitmap(xpm_data);
        return bitmap;
    }
    if (index == 1)
    {
        /* XPM */
        static const char *xpm_data[] = {
            /* columns rows colors chars-per-pixel */
            "16 30 2 1",
            "  c None",
            "a c Black",
            /* pixels */
            "                ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "       aa       ",
            "  a    aa    a  ",
            "  aa   aa   aa  ",
            "   aa  aa  aa   ",
            "    aa aa aa    ",
            "     aaaaaa     ",
            "      aaaa      ",
            "       aa       ",
            "                ",
            "                ",
            "                "
        };
        wxBitmap bitmap(xpm_data);
        return bitmap;
    }
    return wxNullBitmap;
}
Referenced by createContents().
createContents()
wxSizer * OperationPropertyDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
NOTE! This function was generated by wxDesigner, that's why it is so ugly.
Parameters
parent Parent window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 1271 of file OperationPropertyDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer *item1 = new wxGridSizer(2, 0, 0);
    wxBoxSizer *opHeaderSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *nameSizer = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText *item2 = new wxStaticText(parent, ID_TEXT_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0);
    nameSizer->Add(item2, 0, wxALL, 5);
    wxTextCtrl *item3 = new wxTextCtrl(parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0);
    nameSizer->Add(item3, 0, wxALL, 5);
    wxStaticBox *opProperties = new wxStaticBox(parent, -1, wxT("Operation properties"));
    wxStaticBoxSizer *opPropertiesContainer = new wxStaticBoxSizer(opProperties, wxVERTICAL);
    opPropertiesContainer->Add(nameSizer, 0, wxGROW, 5);
    opPropertiesContainer->Add(item1, 0, wxGROW, 5);
    wxStaticBox *opDescription = new wxStaticBox(parent, -1, wxT("Operation description"));
    wxTextCtrl* editDescription = new wxTextCtrl(parent, ID_EDIT_DESCRIPTION, wxT(""), wxDefaultPosition, wxSize(250,50), wxTE_MULTILINE);
    wxStaticBoxSizer *opDescriptionContainer = new wxStaticBoxSizer(opDescription, wxHORIZONTAL);
    opDescriptionContainer->Add(editDescription, 0, wxALL|wxEXPAND, 5);
    opHeaderSizer->Add(opPropertiesContainer, 0, wxALL, 5);
    opHeaderSizer->Add(opDescriptionContainer, 0, wxALL|wxGROW, 5);
    wxCheckBox *item4 = new wxCheckBox(parent, ID_READS_MEMORY, wxT("Reads memory"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(item4, 0, wxALL, 5);
    wxCheckBox *item5 = new wxCheckBox(parent, ID_WRITES_MEMORY, wxT("Writes memory"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(item5, 0, wxALL, 5);
    wxCheckBox *item6 = new wxCheckBox(parent, ID_CAN_TRAP, wxT("Can trap"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(item6, 0, wxALL, 5);
    wxCheckBox *item7 = new wxCheckBox(parent, ID_HAS_SIDE_EFFECTS, wxT("Has side effects"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(item7, 0, wxALL, 5);
    wxCheckBox *clocked = new wxCheckBox(parent, ID_CLOCKED, wxT("Clocked"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(clocked, 0, wxALL, 5);
    item0->Add(opHeaderSizer, 0, wxALIGN_CENTER|wxALL, 5);
    wxGridSizer *item8 = new wxGridSizer(2, 0, 0);
    wxStaticBox *item10 = new wxStaticBox(parent, -1, wxT("Affected by"));
    wxStaticBoxSizer *item9 = new wxStaticBoxSizer(item10, wxVERTICAL);
    affectedBySizer_ = item9;
    wxListCtrl *item11 = new wxListCtrl(parent, ID_AFFECTED_BY, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxSUNKEN_BORDER);
    item9->Add(item11, 0, wxGROW|wxALL, 10);
    wxBoxSizer *item12 = new wxBoxSizer(wxHORIZONTAL);
    wxString strs13[] =
    {
        wxT("ComboItem")
    };
    wxComboBox *item13 = new wxComboBox(parent, ID_OPERATION_AFFECTED_BY, wxT(""), wxDefaultPosition, wxSize(100,-1), 1, strs13, wxCB_SORT);
    item12->Add(item13, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item14 = new wxButton(parent, ID_AFFECTED_ADD_BUTTON, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0);
    item12->Add(item14, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item15 = new wxButton(parent, ID_AFFECTED_DELETE_BUTTON, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0);
    item12->Add(item15, 0, wxALIGN_CENTER|wxALL, 5);
    item9->Add(item12, 0, wxGROW|wxALL, 5);
    item8->Add(item9, 0, wxGROW|wxALL, 5);
    // Operation inputs
    wxStaticBox *item17 = new wxStaticBox(parent, -1, wxT("Input operands"));
    wxStaticBoxSizer *item16 = new wxStaticBoxSizer(item17, wxVERTICAL);
    inputSizer_ = item16;
    wxBoxSizer *item18 = new wxBoxSizer(wxHORIZONTAL);
    wxListCtrl *item19 = new wxListCtrl(parent, ID_INPUT_OPERANDS, wxDefaultPosition, wxSize(335,120), wxLC_REPORT|wxSUNKEN_BORDER);
    item18->Add(item19, 0, wxALIGN_CENTER|wxALL, 5);
    // BoxSizer for up and down buttons
    wxBoxSizer *item20 = new wxBoxSizer(wxVERTICAL);
    // Move up and down buttons
    wxBitmapButton *item21 = new wxBitmapButton(parent, ID_INPUT_UP_BUTTON, createBitmaps(0), wxDefaultPosition, wxDefaultSize);
    item20->Add(item21, 0, wxALL, 5);
    wxBitmapButton *item22 = new wxBitmapButton(parent, ID_INPUT_DOWN_BUTTON, createBitmaps(1), wxDefaultPosition, wxDefaultSize);
    item20->Add(item22, 0, wxALIGN_CENTER|wxALL, 5);
    item18->Add(item20, 0, wxALIGN_CENTER|wxALL, 5);
    item16->Add(item18, 0, wxGROW|wxALL, 5);
    wxBoxSizer *item23 = new wxBoxSizer(wxHORIZONTAL);
    wxButton *item24 = new wxButton(parent, ID_INPUT_ADD_BUTTON, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0);
    item23->Add(item24, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item25 = new wxButton(parent, ID_INPUT_MODIFY_BUTTON, wxT("Modify..."), wxDefaultPosition, wxDefaultSize, 0);
    item23->Add(item25, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item26 = new wxButton(parent, ID_INPUT_DELETE_BUTTON, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0);
    item23->Add(item26, 0, wxALIGN_CENTER|wxALL, 5);
    item16->Add(item23, 0, wxALIGN_CENTER|wxALL, 5);
    item8->Add(item16, 0, wxGROW|wxALL, 5);
    wxStaticBox *item28 = new wxStaticBox(parent, -1, wxT("Affects"));
    wxStaticBoxSizer *item27 = new wxStaticBoxSizer(item28, wxVERTICAL);
    affectsSizer_ = item27;
    wxListCtrl *item29 = new wxListCtrl(parent, ID_AFFECTS, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxSUNKEN_BORDER);
    item27->Add(item29, 0, wxGROW|wxALL, 10);
    wxBoxSizer *item30 = new wxBoxSizer(wxHORIZONTAL);
    wxString strs31[] =
    {
        wxT("ComboItem")
    };
    wxComboBox *item31 = new wxComboBox(parent, ID_OPERATION_AFFECTS, wxT(""), wxDefaultPosition, wxSize(100,-1), 1, strs31, wxCB_SORT);
    item30->Add(item31, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item32 = new wxButton(parent, ID_AFFECTS_ADD_BUTTON, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0);
    item30->Add(item32, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item33 = new wxButton(parent, ID_AFFECTS_DELETE_BUTTON, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0);
    item30->Add(item33, 0, wxALIGN_CENTER|wxALL, 5);
    item27->Add(item30, 0, wxGROW|wxALL, 5);
    item8->Add(item27, 0, wxGROW|wxALL, 5);
    wxStaticBox *item35 = new wxStaticBox(parent, -1, wxT("Output operands"));
    wxStaticBoxSizer *item34 = new wxStaticBoxSizer(item35, wxVERTICAL);
    outputSizer_ = item34;
    wxBoxSizer *item36 = new wxBoxSizer(wxHORIZONTAL);
    wxListCtrl *item37 = new wxListCtrl(parent, ID_OUTPUT_OPERANDS, wxDefaultPosition, wxSize(335,120), wxLC_REPORT|wxSUNKEN_BORDER);
    item36->Add(item37, 0, wxALIGN_CENTER|wxALL, 5);
    wxBoxSizer *item38 = new wxBoxSizer(wxVERTICAL);
    wxBitmapButton *item39 = new wxBitmapButton(parent, ID_OUTPUT_UP_BUTTON, createBitmaps(0), wxDefaultPosition, wxDefaultSize);
    item38->Add(item39, 0, wxALIGN_CENTER|wxALL, 5);
    wxBitmapButton *item40 = new wxBitmapButton(parent, ID_OUTPUT_DOWN_BUTTON, createBitmaps(1), wxDefaultPosition, wxDefaultSize);
    item38->Add(item40, 0, wxALIGN_CENTER|wxALL, 5);
    item36->Add(item38, 0, wxALIGN_CENTER|wxALL, 5);
    item34->Add(item36, 0, wxGROW|wxALL, 5);
    wxBoxSizer *item41 = new wxBoxSizer(wxHORIZONTAL);
    wxButton *item42 = new wxButton(parent, ID_OUTPUT_ADD_BUTTON, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0);
    item41->Add(item42, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item43 = new wxButton(parent, ID_OUTPUT_MODIFY_BUTTON, wxT("Modify..."), wxDefaultPosition, wxDefaultSize, 0);
    item41->Add(item43, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item44 = new wxButton(parent, ID_OUTPUT_DELETE_BUTTON, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0);
    item41->Add(item44, 0, wxALIGN_CENTER|wxALL, 5);
    item34->Add(item41, 0, wxALIGN_CENTER|wxALL, 5);
    item8->Add(item34, 0, wxALIGN_CENTER|wxALL, 5);
    wxBoxSizer *pageSizer = new wxBoxSizer(wxHORIZONTAL);
    pageSizer->Add(item8, 0, wxALL, 5);
    item0->Add(pageSizer, 0, wxALIGN_CENTER|wxALL, 5);
    wxGridSizer *item45 = new wxGridSizer(2, 0, 0);
    wxBoxSizer *item46 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText *item47 = NULL;
    if (module_.hasBehaviorSource()) {
        item47 = new wxStaticText(parent, ID_TEXT_OPEN, _T("Operation behavior module defined."), wxDefaultPosition, wxDefaultSize, 0);
    } else {
        item47 = new wxStaticText(parent, ID_TEXT_OPEN, wxT("Operation behavior module not defined."), wxDefaultPosition, wxDefaultSize, 0);
    }
    item46->Add(item47, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item48 = new wxButton(parent, ID_OPEN_BUTTON, wxT("Open"), wxDefaultPosition, wxDefaultSize, 0);
    item46->Add(item48, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *OpenDAG = new wxButton(parent, ID_DAG_BUTTON, wxT("Open DAG"), wxDefaultPosition, wxDefaultSize, 0);
    item46->Add(OpenDAG, 0, wxALIGN_CENTER|wxALL, 5);
    item45->Add(item46, 0, wxALL, 5);
    wxBoxSizer *item49 = new wxBoxSizer(wxHORIZONTAL);
    wxButton *item50 = new wxButton(parent, ID_OK_BUTTON, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0);
    item49->Add(item50, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item51 = new wxButton(parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
    item49->Add(item51, 0, wxALIGN_CENTER|wxALL, 5);
    item45->Add(item49, 0, wxALL, 5);
    item0->Add(item45, 0, wxGROW|wxALL, 5);
    if (set_sizer)
    {
        parent->SetSizer(item0);
        if (call_fit)
            item0->SetSizeHints(parent);
    }
    return item0;
}
References affectedBySizer_, affectsSizer_, createBitmaps(), OperationModule::hasBehaviorSource(), ID_AFFECTED_ADD_BUTTON, ID_AFFECTED_BY, ID_AFFECTED_DELETE_BUTTON, ID_AFFECTS, ID_AFFECTS_ADD_BUTTON, ID_AFFECTS_DELETE_BUTTON, ID_CAN_TRAP, ID_CLOCKED, ID_DAG_BUTTON, ID_EDIT_DESCRIPTION, ID_HAS_SIDE_EFFECTS, ID_INPUT_ADD_BUTTON, ID_INPUT_DELETE_BUTTON, ID_INPUT_DOWN_BUTTON, ID_INPUT_MODIFY_BUTTON, ID_INPUT_OPERANDS, ID_INPUT_UP_BUTTON, ID_NAME, ID_OK_BUTTON, ID_OPEN_BUTTON, ID_OPERATION_AFFECTED_BY, ID_OPERATION_AFFECTS, ID_OUTPUT_ADD_BUTTON, ID_OUTPUT_DELETE_BUTTON, ID_OUTPUT_DOWN_BUTTON, ID_OUTPUT_MODIFY_BUTTON, ID_OUTPUT_OPERANDS, ID_OUTPUT_UP_BUTTON, ID_READS_MEMORY, ID_TEXT_NAME, ID_TEXT_OPEN, ID_WRITES_MEMORY, inputSizer_, module_, and outputSizer_.
getSelectedItems()
vector< string > OperationPropertyDialog::getSelectedItems (wxListCtrl * listCtrl) private
Returns all the selected items of the list control.
Parameters
listCtrl List control which is investigated.
Returns
All selected items as a vector.
Definition at line 998 of file OperationPropertyDialog.cc.
{
    vector<string> selected;
    long item = -1;
    for (;;) {
        item = listCtrl->GetNextItem(
            item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        if (item == -1) {
            break;
        }
        wxListItem info;
        info.SetId(item);
        info.SetColumn(0);
        listCtrl->GetItem(info);
        selected.push_back(WxConversion::toString(info.GetText()));
    }
    return selected;
}
References WxConversion::toString().
Referenced by onDeleteAffectedBy(), onDeleteAffects(), onDeleteInputOperand(), and onDeleteOutputOperand().
launchEditor()
void OperationPropertyDialog::launchEditor (const std::string & cmd) private
Launches editor for editing operation behavior.
Parameters
cmd Command for launching the editor.
Definition at line 1203 of file OperationPropertyDialog.cc.
{
    CommandThread* thread = new CommandThread(cmd);
    thread->Create();
    thread->Run();
}
Referenced by onOpen().
moveDown()
void OperationPropertyDialog::moveDown (std::vector< Operand * > & ops, int id, wxListCtrl * list) private
Moves operand down.
Parameters
list List from which operand is selected.
ops Operands.
id Id of the operand.
Definition at line 974 of file OperationPropertyDialog.cc.
                      {
    if (static_cast<unsigned int>(id) != ops.size()) {
        Operand* temp = ops[id - 1];
        ops[id - 1] = ops[id];
        ops[id] = temp;
        long item = -1;
        item = list->GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        list->SetItemState(
            item + 1, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
        list->SetItemState(item, 0, wxLIST_STATE_SELECTED);
    }
}
Referenced by onMoveInputDown(), and onMoveOutputDown().
moveUp()
void OperationPropertyDialog::moveUp (std::vector< Operand * > & ops, int id, wxListCtrl * list) private
Moves operand up.
Parameters
list List from which operand is selected.
id Id of the operand.
ops Operands.
Definition at line 949 of file OperationPropertyDialog.cc.
                      {
    if (id != 1) {
        Operand* temp = ops[id - 2];
        ops[id - 2] = ops[id - 1];
        ops[id - 1] = temp;
        long item = -1;
        item = list->GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        list->SetItemState(
            item - 1, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
        list->SetItemState(item, 0, wxLIST_STATE_SELECTED);
    }
}
Referenced by onMoveInputUp(), and onMoveOutputUp().
onAddAffectedBy()
void OperationPropertyDialog::onAddAffectedBy (wxCommandEvent & event) private
Handles adding new item to affected by list.
Definition at line 634 of file OperationPropertyDialog.cc.
{
    wxString name = affectedByChoice_->GetValue();
    if (!OperationContainer::operationExists(WxConversion::toString(name))) {
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        format fmt = texts.text(
            OSEdTextGenerator::TXT_ERROR_NON_EXISTING_OPERATION);
        fmt % name;
        ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
    } else {
        affectedBy_.push_back(WxConversion::toString(name));
        updateAffected();
    }
}
References affectedBy_, affectedByChoice_, OSEdTextGenerator::instance(), OperationContainer::operationExists(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NON_EXISTING_OPERATION, and updateAffected().
onAddAffects()
void OperationPropertyDialog::onAddAffects (wxCommandEvent & event) private
Handles event of adding new item to affects list.
Definition at line 676 of file OperationPropertyDialog.cc.
{
    wxString name = affectsChoice_->GetValue();
    if (!OperationContainer::operationExists(WxConversion::toString(name))) {
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        format fmt = texts.text(
            OSEdTextGenerator::TXT_ERROR_NON_EXISTING_OPERATION);
        fmt % name;
        ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
    } else {
        affects_.push_back(WxConversion::toString(name));
        updateAffected();
    }
}
References affects_, affectsChoice_, OSEdTextGenerator::instance(), OperationContainer::operationExists(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NON_EXISTING_OPERATION, and updateAffected().
onAddInputOperand()
void OperationPropertyDialog::onAddInputOperand (wxCommandEvent & event) private
Handles event for adding new operand to input operand list.
Definition at line 718 of file OperationPropertyDialog.cc.
{
    Operand* input =
        new Operand(true, inputOperands_.size() + 1, Operand::SINT_WORD);
    InputOperandDialog dialog(
        this, input, inputOperands_.size(), inputOperands_.size() + 1);
    if (dialog.ShowModal() == wxID_OK) {
        inputOperands_.push_back(input);
        updateOperands();
    } else {
        delete input;
    }
    updateOperands();
}
References inputOperands_, Operand::SINT_WORD, and updateOperands().
onAddOutputOperand()
void OperationPropertyDialog::onAddOutputOperand (wxCommandEvent & event) private
Handles the event of adding new output operand.
Definition at line 779 of file OperationPropertyDialog.cc.
{
    unsigned int id = inputOperands_.size() + outputOperands_.size() + 1;
    Operand* output = new Operand(false, id, Operand::SINT_WORD);
    OutputOperandDialog dialog(this, output, id);
    if (dialog.ShowModal() == wxID_OK) {
        outputOperands_.push_back(output);
        updateOperands();
    } else {
        delete output;
    }
    updateOperands();
}
References inputOperands_, outputOperands_, Operand::SINT_WORD, and updateOperands().
onComboBoxChange()
void OperationPropertyDialog::onComboBoxChange (wxCommandEvent & event) private
onDAGChange()
void OperationPropertyDialog::onDAGChange (wxCommandEvent & event) private
onDeleteAffectedBy()
void OperationPropertyDialog::onDeleteAffectedBy (wxCommandEvent & event) private
Handles deleting an item from affected by list.
Definition at line 655 of file OperationPropertyDialog.cc.
{
    vector<string> toBeDeleted = getSelectedItems(affectedByList_);
    for (size_t i = 0; i < toBeDeleted.size(); i++) {
        vector<string>::iterator it = affectedBy_.begin();
        while (it != affectedBy_.end()) {
            if (*it == toBeDeleted[i]) {
                affectedBy_.erase(it);
                break;
            }
            it++;
        }
    }
    updateAffected();
}
References affectedBy_, affectedByList_, getSelectedItems(), and updateAffected().
onDeleteAffects()
void OperationPropertyDialog::onDeleteAffects (wxCommandEvent & event) private
Handles event of deleting item from affects list.
Definition at line 697 of file OperationPropertyDialog.cc.
{
    vector<string> toBeDeleted = getSelectedItems(affectsList_);
    for (size_t i = 0; i < toBeDeleted.size(); i++) {
        vector<string>::iterator it = affects_.begin();
        while (it != affects_.end()) {
            if (*it == toBeDeleted[i]) {
                affects_.erase(it);
                break;
            }
            it++;
        }
    }
    updateAffected();
}
References affects_, affectsList_, getSelectedItems(), and updateAffected().
onDeleteDAG()
void OperationPropertyDialog::onDeleteDAG (wxCommandEvent & event) private
onDeleteInputOperand()
void OperationPropertyDialog::onDeleteInputOperand (wxCommandEvent & event) private
Handles the event of deleting input operand.
Definition at line 753 of file OperationPropertyDialog.cc.
{
    vector<string> toBeDeleted = getSelectedItems(inputOperandList_);
    size_t i = 0;
    vector<Operand*>::iterator it = inputOperands_.begin();
    int index = 1;
    updateSwapLists(toBeDeleted);
    while (it != inputOperands_.end() && i < toBeDeleted.size()) {
        int id = Conversion::toInt(toBeDeleted[i]);
        while (index < id) {
            it++;
            index++;
        }
        delete *it;
        it = inputOperands_.erase(it);
        index++;
        i++;
    }
    updateOperands();
}
References getSelectedItems(), inputOperandList_, inputOperands_, Conversion::toInt(), updateOperands(), and updateSwapLists().
onDeleteOutputOperand()
void OperationPropertyDialog::onDeleteOutputOperand (wxCommandEvent & event) private
Handles the event of deleting output operand.
Definition at line 812 of file OperationPropertyDialog.cc.
{
    vector<string> toBeDeleted = getSelectedItems(outputOperandList_);
    size_t i = 0;
    vector<Operand*>::iterator it = outputOperands_.begin();
    int index = inputOperands_.size() + 1;
    while (it != outputOperands_.end() && i < toBeDeleted.size()) {
        int id = Conversion::toInt(toBeDeleted[i]);
        while (index < id) {
            it++;
            index++;
        }
        delete *it;
        it = outputOperands_.erase(it);
        index++;
        i++;
    }
    updateOperands();
}
References getSelectedItems(), inputOperands_, outputOperandList_, outputOperands_, Conversion::toInt(), and updateOperands().
onModifyInputOperand()
void OperationPropertyDialog::onModifyInputOperand (wxCommandEvent & event) private
Handles the event for modifying input operand.
Definition at line 738 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(inputOperandList_, 0);
    int id = Conversion::toInt(idString);
    Operand* operand = NULL;
    operand = inputOperands_[id - 1];
    assert(operand != NULL);
    InputOperandDialog dialog(this, operand, inputOperands_.size(), id);
    dialog.ShowModal();
    updateOperands();
}
References assert, inputOperandList_, inputOperands_, WidgetTools::lcStringSelection(), Conversion::toInt(), and updateOperands().
onModifyOutputOperand()
void OperationPropertyDialog::onModifyOutputOperand (wxCommandEvent & event) private
Handles the event for mofifying output operand.
Definition at line 796 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(outputOperandList_, 0);
    int realId = Conversion::toInt(idString);
    int id = realId - static_cast<int>(inputOperands_.size());
    Operand* operand = NULL;
    operand = outputOperands_[id - 1];
    assert(operand != NULL);
    OutputOperandDialog dialog(this, operand, realId);
    dialog.ShowModal();
    updateOperands();
}
References assert, inputOperands_, WidgetTools::lcStringSelection(), outputOperandList_, outputOperands_, Conversion::toInt(), and updateOperands().
onMoveInputDown()
void OperationPropertyDialog::onMoveInputDown (wxCommandEvent & event) private
Handles the event when input operand is moved down.
Definition at line 847 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(inputOperandList_, 0);
    int id = Conversion::toInt(idString);
    moveDown(inputOperands_, id, inputOperandList_);
}
References inputOperandList_, inputOperands_, WidgetTools::lcStringSelection(), moveDown(), and Conversion::toInt().
onMoveInputUp()
void OperationPropertyDialog::onMoveInputUp (wxCommandEvent & event) private
Handles the event when input operand is moved up.
Definition at line 837 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(inputOperandList_, 0);
    int id = Conversion::toInt(idString);
    moveUp(inputOperands_, id, inputOperandList_);
}
References inputOperandList_, inputOperands_, WidgetTools::lcStringSelection(), moveUp(), and Conversion::toInt().
onMoveOutputDown()
void OperationPropertyDialog::onMoveOutputDown (wxCommandEvent & event) private
Handles the event when output operand is moved down.
Definition at line 868 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(outputOperandList_, 0);
    int id = Conversion::toInt(idString) -
        static_cast<int>(inputOperands_.size());
    moveDown(outputOperands_, id, outputOperandList_);
}
References inputOperands_, WidgetTools::lcStringSelection(), moveDown(), outputOperandList_, outputOperands_, and Conversion::toInt().
onMoveOutputUp()
void OperationPropertyDialog::onMoveOutputUp (wxCommandEvent & event) private
Handles the event when output operand is moved up.
Definition at line 857 of file OperationPropertyDialog.cc.
{
    string idString = WidgetTools::lcStringSelection(outputOperandList_, 0);
    int id = Conversion::toInt(idString) -
        static_cast<int>(inputOperands_.size());
    moveUp(outputOperands_, id, outputOperandList_);
}
References inputOperands_, WidgetTools::lcStringSelection(), moveUp(), outputOperandList_, outputOperands_, and Conversion::toInt().
onNewDAG()
void OperationPropertyDialog::onNewDAG (wxCommandEvent & event) private
onOk()
void OperationPropertyDialog::onOk (wxCommandEvent & event) private
Handles the event when OK button is pushed.
Definition at line 1020 of file OperationPropertyDialog.cc.
{
    updateOperation(false);
}
References updateOperation().
onOpen()
void OperationPropertyDialog::onOpen (wxCommandEvent & event) private
Handles the event when Open button is pushed.
Definition at line 879 of file OperationPropertyDialog.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdOptions* options = wxGetApp().options();
    string editor = options->editor();
    if (editor == "") {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_EDITOR);
        ErrorDialog error(this, WxConversion::toWxString(fmt.str()));
        error.ShowModal();
    } else {
        if (FileSystem::fileExists(editor)) {
            if (module_.hasBehaviorSource()) {
                string code = module_.behaviorSourceModule();
                string cmd = editor + " " + code;
                launchEditor(cmd);
            } else {
                // new behavior is added for the module
                string code = module_.propertiesModule();
                size_t pos = code.find_last_of(".");
                code.erase(pos);
                code += ".cc";
                // copy template file as new file
                string dir =
                    Environment::dataDirPath(
                        WxConversion::toString(
                            OSEdConstants::APPLICATION_NAME));
                string templateFile = dir + FileSystem::DIRECTORY_SEPARATOR +
                    OSEdConstants::BEHAVIOR_TEMPLATE_FILE_NAME;
                FileSystem::copy(templateFile, code);
                string cmd = editor + " " + code;
                launchEditor(cmd);
            }
        } else {
            format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_OPEN);
            fmt % editor;
            ErrorDialog error(this, WxConversion::toWxString(fmt.str()));
            error.ShowModal();
        }
    }
    setBehaviorLabel();
}
References OSEdConstants::APPLICATION_NAME, OSEdConstants::BEHAVIOR_TEMPLATE_FILE_NAME, OperationModule::behaviorSourceModule(), FileSystem::copy(), Environment::dataDirPath(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), OperationModule::hasBehaviorSource(), OSEdTextGenerator::instance(), launchEditor(), module_, options, OperationModule::propertiesModule(), setBehaviorLabel(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NO_EDITOR, and OSEdTextGenerator::TXT_ERROR_OPEN.
onOpenDAG()
void OperationPropertyDialog::onOpenDAG (wxCommandEvent & event) private
Handles the event when Open DAG button is pushed.
Definition at line 931 of file OperationPropertyDialog.cc.
{
    if (operationWasCreatedHere_) {
        updateOperation(true);
    }
    // TODO: here set the number of operands of new operation.
    OperationDAGDialog dialog(this, operation_);
    dialog.ShowModal();
}
References operation_, operationWasCreatedHere_, and updateOperation().
onSaveDAG()
void OperationPropertyDialog::onSaveDAG (wxCommandEvent & event) private
onSelection()
void OperationPropertyDialog::onSelection (wxListEvent & event) private
Handles the event when an item is selected from a list.
Item selection affects statuses of several buttons.
Definition at line 556 of file OperationPropertyDialog.cc.
{
    if (affectedByList_->GetSelectedItemCount() < 1) {
        FindWindow(ID_AFFECTED_DELETE_BUTTON)->Disable();
    } else {
        FindWindow(ID_AFFECTED_DELETE_BUTTON)->Enable();
    }
    if (affectsList_->GetSelectedItemCount() < 1) {
        FindWindow(ID_AFFECTS_DELETE_BUTTON)->Disable();
    } else {
        FindWindow(ID_AFFECTS_DELETE_BUTTON)->Enable();
    }
    if (inputOperandList_->GetSelectedItemCount() < 1) {
        FindWindow(ID_INPUT_DELETE_BUTTON)->Disable();
    } else {
        FindWindow(ID_INPUT_DELETE_BUTTON)->Enable();
    }
    if (outputOperandList_->GetSelectedItemCount() < 1) {
        FindWindow(ID_OUTPUT_DELETE_BUTTON)->Disable();
    } else {
        FindWindow(ID_OUTPUT_DELETE_BUTTON)->Enable();
    }
    if (inputOperandList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_INPUT_MODIFY_BUTTON)->Disable();
        FindWindow(ID_INPUT_UP_BUTTON)->Disable();
        FindWindow(ID_INPUT_DOWN_BUTTON)->Disable();
    } else {
        FindWindow(ID_INPUT_MODIFY_BUTTON)->Enable();
        string idString = WidgetTools::lcStringSelection(inputOperandList_, 0);
        int id = Conversion::toInt(idString);
        if (id != 1) {
            FindWindow(ID_INPUT_UP_BUTTON)->Enable();
        } else {
            FindWindow(ID_INPUT_UP_BUTTON)->Disable();
        }
        if (id != static_cast<int>(inputOperands_.size())) {
            FindWindow(ID_INPUT_DOWN_BUTTON)->Enable();
        } else {
            FindWindow(ID_INPUT_DOWN_BUTTON)->Disable();
        }
    }
    if (outputOperandList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_OUTPUT_MODIFY_BUTTON)->Disable();
        FindWindow(ID_OUTPUT_UP_BUTTON)->Disable();
        FindWindow(ID_OUTPUT_DOWN_BUTTON)->Disable();
    } else {
        FindWindow(ID_OUTPUT_MODIFY_BUTTON)->Enable();
        string idString = WidgetTools::lcStringSelection(outputOperandList_, 0);
        int id = Conversion::toInt(idString);
        if (id != static_cast<int>(inputOperands_.size()) + 1) {
            FindWindow(ID_OUTPUT_UP_BUTTON)->Enable();
        } else {
            FindWindow(ID_OUTPUT_UP_BUTTON)->Disable();
        }
        if (id != static_cast<int>(inputOperands_.size()) +
            static_cast<int>(outputOperands_.size())) {
            FindWindow(ID_OUTPUT_DOWN_BUTTON)->Enable();
        } else {
            FindWindow(ID_OUTPUT_DOWN_BUTTON)->Disable();
        }
    }
}
References affectedByList_, affectsList_, ID_AFFECTED_DELETE_BUTTON, ID_AFFECTS_DELETE_BUTTON, ID_INPUT_DELETE_BUTTON, ID_INPUT_DOWN_BUTTON, ID_INPUT_MODIFY_BUTTON, ID_INPUT_UP_BUTTON, ID_OUTPUT_DELETE_BUTTON, ID_OUTPUT_DOWN_BUTTON, ID_OUTPUT_MODIFY_BUTTON, ID_OUTPUT_UP_BUTTON, inputOperandList_, inputOperands_, WidgetTools::lcStringSelection(), outputOperandList_, outputOperands_, and Conversion::toInt().
Referenced by updateAffected(), and updateOperands().
onUndoDAG()
void OperationPropertyDialog::onUndoDAG (wxCommandEvent & event) private
operation()
Operation * OperationPropertyDialog::operation () const
Returns operation object of dialog.
Returns
Operation object of dialog.
Definition at line 236 of file OperationPropertyDialog.cc.
{
    return operation_;
}
References operation_.
Referenced by OSEdAddOperationCmd::Do().
operator=()
OperationPropertyDialog & OperationPropertyDialog::operator= (const OperationPropertyDialog &) private
Assignment not allowed.
saveOperation()
ObjectState * OperationPropertyDialog::saveOperation () private
Returns the operation properties as ObjectState tree.
Returns
Operation properties as ObjectState tree.
Definition at line 1105 of file OperationPropertyDialog.cc.
{
    ObjectState* root = new ObjectState(Operation::OPRN_OPERATION);
    root->setAttribute(Operation::OPRN_NAME, WxConversion::toString(name_));
    std::string description("");
    wxString wxTemp;
    for (int i = 0; i < editDescription_->GetNumberOfLines(); ++i)
    {
        wxTemp = editDescription_->GetLineText(i);
#if wxCHECK_VERSION(2, 6, 0)
        std::string stdTemp(wxTemp.mb_str());
#else
        std::string stdTemp(wxTemp.c_str());
#endif
        if (!StringTools::endsWith(stdTemp, "\n"))
            stdTemp = stdTemp + "\n";
        description += stdTemp;
    }
    description = StringTools::trim(description);
    root->setAttribute(Operation::OPRN_DESCRIPTION, description);
    int inputs = inputOperands_.size();
    int outputs = outputOperands_.size();
    root->setAttribute(Operation::OPRN_INPUTS, inputs);
    root->setAttribute(Operation::OPRN_OUTPUTS, outputs);
    root->setAttribute(Operation::OPRN_TRAP, canTrap_);
    root->setAttribute(Operation::OPRN_SIDE_EFFECTS, hasSideEffects_);
    root->setAttribute(Operation::OPRN_CLOCKED, clocked_);
    root->setAttribute(Operation::OPRN_READS_MEMORY, readMemory_);
    root->setAttribute(Operation::OPRN_WRITES_MEMORY, writeMemory_);
    root->setAttribute(Operation::OPRN_CONTROL_FLOW, controlFlow_);
    root->setAttribute(Operation::OPRN_ISCALL, isCall_);
    root->setAttribute(Operation::OPRN_ISBRANCH, isBranch_);
    if (affectedBy_.size() > 0) {
        ObjectState* affectedBy = new ObjectState(Operation::OPRN_AFFECTED_BY);
        for (unsigned int i = 0; i < affectedBy_.size(); i++) {
            ObjectState* affectedByChild =
                new ObjectState(Operation::OPRN_OPERATION);
            affectedByChild->setAttribute(Operation::OPRN_NAME, affectedBy_[i]);
            affectedBy->addChild(affectedByChild);
        }
        root->addChild(affectedBy);
    }
    if (affects_.size() > 0) {
        ObjectState* affects = new ObjectState(Operation::OPRN_AFFECTS);
        for (unsigned int i = 0; i < affects_.size(); i++) {
            ObjectState* affectsChild =
                new ObjectState(Operation::OPRN_OPERATION);
            affectsChild->setAttribute(Operation::OPRN_NAME, affects_[i]);
            affects->addChild(affectsChild);
        }
        root->addChild(affects);
    }
    for (unsigned int i = 0; i < inputOperands_.size(); i++) {
        ObjectState* operand = inputOperands_[i]->saveState();
        operand->setName(Operation::OPRN_IN);
        int index = i + 1;
        operand->setAttribute(Operand::OPRND_ID, index);
        std::string type = inputOperands_.at(i)->typeString();
        operand->setAttribute(Operand::OPRND_TYPE, type);
        root->addChild(operand);
    }
    for (unsigned int i = 0; i < outputOperands_.size(); i++) {
        ObjectState* operand = outputOperands_[i]->saveState();
        operand->setName(Operation::OPRN_OUT);
        int index = inputOperands_.size() + i + 1;
        operand->setAttribute(Operand::OPRND_ID, index);
        std::string type = outputOperands_.at(i)->typeString();
        operand->setAttribute(Operand::OPRND_TYPE, type);
        root->addChild(operand);
    }
    // copy dags from operation to objectState tree
    for (int i = 0; i < operation_->dagCount(); i++) {
        ObjectState* trigger = new ObjectState(Operation::OPRN_TRIGGER);
        trigger->setValue(operation_->dagCode(i));
        root->addChild(trigger);
    }
    return root;
}
References ObjectState::addChild(), affectedBy_, affects_, canTrap_, clocked_, controlFlow_, Operation::dagCode(), Operation::dagCount(), editDescription_, StringTools::endsWith(), hasSideEffects_, inputOperands_, isBranch_, isCall_, name_, operation_, Operation::OPRN_AFFECTED_BY, Operation::OPRN_AFFECTS, Operation::OPRN_CLOCKED, Operation::OPRN_CONTROL_FLOW, Operation::OPRN_DESCRIPTION, Operation::OPRN_IN, Operation::OPRN_INPUTS, Operation::OPRN_ISBRANCH, Operation::OPRN_ISCALL, Operation::OPRN_NAME, Operation::OPRN_OPERATION, Operation::OPRN_OUT, Operation::OPRN_OUTPUTS, Operation::OPRN_READS_MEMORY, Operation::OPRN_SIDE_EFFECTS, Operation::OPRN_TRAP, Operation::OPRN_TRIGGER, Operation::OPRN_WRITES_MEMORY, Operand::OPRND_ID, Operand::OPRND_TYPE, outputOperands_, readMemory_, ObjectState::setAttribute(), ObjectState::setName(), ObjectState::setValue(), WxConversion::toString(), StringTools::trim(), and writeMemory_.
Referenced by updateOperation().
setBehaviorLabel()
void OperationPropertyDialog::setBehaviorLabel () private
Sets the has behavior label.
Definition at line 393 of file OperationPropertyDialog.cc.
{
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    if (module_.hasBehaviorSource()) {
        WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_OPEN),
                              OSEdTextGenerator::TXT_LABEL_HAS_BEHAVIOR);
    } else {
        WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_OPEN),
                              OSEdTextGenerator::TXT_LABEL_NO_BEHAVIOR);
    }
}
References OperationModule::hasBehaviorSource(), ID_TEXT_OPEN, OSEdTextGenerator::instance(), module_, WidgetTools::setLabel(), OSEdTextGenerator::TXT_LABEL_HAS_BEHAVIOR, and OSEdTextGenerator::TXT_LABEL_NO_BEHAVIOR.
Referenced by onOpen(), and setTexts().
setTexts()
void OperationPropertyDialog::setTexts () private
Set texts to all widgets.
Definition at line 244 of file OperationPropertyDialog.cc.
{
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt = osedText.text(OSEdTextGenerator::TXT_PROPERTY_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_NAME),
                          OSEdTextGenerator::TXT_LABEL_OPERATION_NAME);
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(ID_OK_BUTTON),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(&guiText, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(&guiText, FindWindow(ID_INPUT_ADD_BUTTON),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(&guiText, FindWindow(ID_INPUT_DELETE_BUTTON),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(&guiText, FindWindow(ID_OUTPUT_ADD_BUTTON),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(&guiText, FindWindow(ID_OUTPUT_DELETE_BUTTON),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(&guiText, FindWindow(ID_AFFECTS_ADD_BUTTON),
                          GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(&guiText, FindWindow(ID_AFFECTS_DELETE_BUTTON),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(&guiText, FindWindow(ID_AFFECTED_ADD_BUTTON),
                          GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(&guiText, FindWindow(ID_AFFECTED_DELETE_BUTTON),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(&osedText, FindWindow(ID_INPUT_MODIFY_BUTTON),
                          OSEdTextGenerator::TXT_BUTTON_MODIFY);
    WidgetTools::setLabel(&osedText, FindWindow(ID_OUTPUT_MODIFY_BUTTON),
                          OSEdTextGenerator::TXT_BUTTON_MODIFY);
    WidgetTools::setLabel(&osedText, FindWindow(ID_OPEN_BUTTON),
                              OSEdTextGenerator::TXT_BUTTON_OPEN);
    setBehaviorLabel();
    // column titles
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_OPERATION);
    affectedByList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    affectsList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_ELEMENT_COUNT);
    inputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_ELEMENT_WIDTH);
    inputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_TYPE);
    inputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_OPERAND);
    inputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        70);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_ELEMENT_COUNT);
    outputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_ELEMENT_WIDTH);
    outputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_TYPE);
    outputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        110);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_OPERAND);
    outputOperandList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        70);
    // check boxes
    WidgetTools::setLabel(&osedText, FindWindow(ID_READS_MEMORY),
                          OSEdTextGenerator::TXT_CHECKBOX_READS_MEMORY);
    WidgetTools::setLabel(&osedText, FindWindow(ID_WRITES_MEMORY),
                          OSEdTextGenerator::TXT_CHECKBOX_WRITES_MEMORY);
    WidgetTools::setLabel(&osedText, FindWindow(ID_CAN_TRAP),
                          OSEdTextGenerator::TXT_CHECKBOX_CAN_TRAP);
    WidgetTools::setLabel(&osedText, FindWindow(ID_HAS_SIDE_EFFECTS),
                          OSEdTextGenerator::TXT_CHECKBOX_HAS_SIDE_EFFECTS);
    WidgetTools::setLabel(&osedText, FindWindow(ID_CLOCKED),
                          OSEdTextGenerator::TXT_CHECKBOX_CLOCKED);
    // box sizers
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_AFFECTS);
    WidgetTools::setWidgetLabel(affectsSizer_, fmt.str());
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_AFFECTED_BY);
    WidgetTools::setWidgetLabel(affectedBySizer_, fmt.str());
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_INPUT_OPERANDS);
    WidgetTools::setWidgetLabel(inputSizer_, fmt.str());
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_OUTPUT_OPERANDS);
    WidgetTools::setWidgetLabel(outputSizer_, fmt.str());
}
References affectedByList_, affectedBySizer_, affectsList_, affectsSizer_, OSEdConstants::DEFAULT_COLUMN_WIDTH, ID_AFFECTED_ADD_BUTTON, ID_AFFECTED_DELETE_BUTTON, ID_AFFECTS_ADD_BUTTON, ID_AFFECTS_DELETE_BUTTON, ID_CAN_TRAP, ID_CLOCKED, ID_HAS_SIDE_EFFECTS, ID_INPUT_ADD_BUTTON, ID_INPUT_DELETE_BUTTON, ID_INPUT_MODIFY_BUTTON, ID_OK_BUTTON, ID_OPEN_BUTTON, ID_OUTPUT_ADD_BUTTON, ID_OUTPUT_DELETE_BUTTON, ID_OUTPUT_MODIFY_BUTTON, ID_READS_MEMORY, ID_TEXT_NAME, ID_WRITES_MEMORY, inputOperandList_, inputSizer_, GUITextGenerator::instance(), OSEdTextGenerator::instance(), outputOperandList_, outputSizer_, setBehaviorLabel(), WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BOX_AFFECTED_BY, OSEdTextGenerator::TXT_BOX_AFFECTS, OSEdTextGenerator::TXT_BOX_INPUT_OPERANDS, OSEdTextGenerator::TXT_BOX_OUTPUT_OPERANDS, GUITextGenerator::TXT_BUTTON_ADD, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, OSEdTextGenerator::TXT_BUTTON_MODIFY, GUITextGenerator::TXT_BUTTON_OK, OSEdTextGenerator::TXT_BUTTON_OPEN, OSEdTextGenerator::TXT_CHECKBOX_CAN_TRAP, OSEdTextGenerator::TXT_CHECKBOX_CLOCKED, OSEdTextGenerator::TXT_CHECKBOX_HAS_SIDE_EFFECTS, OSEdTextGenerator::TXT_CHECKBOX_READS_MEMORY, OSEdTextGenerator::TXT_CHECKBOX_WRITES_MEMORY, OSEdTextGenerator::TXT_COLUMN_ELEMENT_COUNT, OSEdTextGenerator::TXT_COLUMN_ELEMENT_WIDTH, OSEdTextGenerator::TXT_COLUMN_OPERAND, OSEdTextGenerator::TXT_COLUMN_OPERATION, OSEdTextGenerator::TXT_COLUMN_TYPE, OSEdTextGenerator::TXT_LABEL_OPERATION_NAME, and OSEdTextGenerator::TXT_PROPERTY_DIALOG_TITLE.
TransferDataToWindow()
bool OperationPropertyDialog::TransferDataToWindow () private virtual
Transfers data to window.
Returns
True if transfer is successful.
Definition at line 410 of file OperationPropertyDialog.cc.
{
    if (operation_ != NULL) {
        name_ = WxConversion::toWxString(operation_->name());
        editDescription_->Clear();
        editDescription_->AppendText(WxConversion::toWxString(operation_->description()));
        readMemory_ = operation_->readsMemory();
        writeMemory_ = operation_->writesMemory();
        canTrap_ = operation_->canTrap();
        hasSideEffects_ = operation_->hasSideEffects();
        clocked_ = operation_->isClocked();
        controlFlow_ = operation_->isControlFlowOperation();
        isCall_ = operation_->isCall();
        isBranch_ = operation_->isBranch();
        updateOperands();
        updateAffected();
    } else {
        readMemory_ = false;
        writeMemory_ = false;
        canTrap_ = false;
        hasSideEffects_ = false;
        clocked_ = false;
        controlFlow_ = false;
        isCall_ = false;
        isBranch_ = false;
    }
    return wxWindow::TransferDataToWindow();
}
References Operation::canTrap(), canTrap_, clocked_, controlFlow_, Operation::description(), editDescription_, Operation::hasSideEffects(), hasSideEffects_, Operation::isBranch(), isBranch_, Operation::isCall(), isCall_, Operation::isClocked(), Operation::isControlFlowOperation(), Operation::name(), name_, operation_, readMemory_, Operation::readsMemory(), WxConversion::toWxString(), updateAffected(), updateOperands(), writeMemory_, and Operation::writesMemory().
updateAffected()
void OperationPropertyDialog::updateAffected () private
Updates the affects and affected by lists.
Definition at line 485 of file OperationPropertyDialog.cc.
{
    affectedByList_->DeleteAllItems();
    affectsList_->DeleteAllItems();
    for (unsigned int i = 0; i < affectedBy_.size(); i++) {
        wxString oper = WxConversion::toWxString(affectedBy_[i]);
        affectedByList_->InsertItem(i, oper);
    }
    for (unsigned int i = 0; i < affects_.size(); i++) {
        wxString oper = WxConversion::toWxString(affects_[i]);
        affectsList_->InsertItem(i, oper);
    }
    OperationIndex& index = OperationContainer::operationIndex();
    affectsChoice_->Clear();
    affectedByChoice_->Clear();
    for (int i = 0; i < index.pathCount(); i++) {
        string path = index.path(i);
        int modules = index.moduleCount(path);
        for (int j = 0; j < modules; j++) {
            OperationModule& module = index.module(j, path);
            int operations = 0;
            try {
                operations = index.operationCount(module);
            } catch (const Exception& e) {
                continue;
            }
            for (int k = 0; k < operations; k++) {
                string name = index.operationName(k, module);
                if (affectsList_->
                    FindItem(-1, WxConversion::toWxString(name)) == -1) {
                    affectsChoice_->Append(WxConversion::toWxString(name));
                }
                if (affectedByList_->
                    FindItem(-1, WxConversion::toWxString(name)) == -1) {
                    affectedByChoice_->Append(WxConversion::toWxString(name));
                }
            }
        }
    }
    affectsChoice_->SetSelection(0);
    affectedByChoice_->SetSelection(0);
    if (affectsChoice_->GetCount() == 0) {
        FindWindow(ID_AFFECTS_ADD_BUTTON)->Disable();
    } else {
        FindWindow(ID_AFFECTS_ADD_BUTTON)->Enable();
    }
    if (affectedByChoice_->GetCount() == 0) {
        FindWindow(ID_AFFECTED_ADD_BUTTON)->Disable();
    } else {
        FindWindow(ID_AFFECTED_ADD_BUTTON)->Enable();
    }
    wxListEvent dummy;
    onSelection(dummy);
}
References affectedBy_, affectedByChoice_, affectedByList_, affects_, affectsChoice_, affectsList_, dummy, ID_AFFECTED_ADD_BUTTON, ID_AFFECTS_ADD_BUTTON, OperationIndex::moduleCount(), onSelection(), OperationIndex::operationCount(), OperationContainer::operationIndex(), OperationIndex::operationName(), OperationIndex::path(), OperationIndex::pathCount(), and WxConversion::toWxString().
Referenced by onAddAffectedBy(), onAddAffects(), onDeleteAffectedBy(), onDeleteAffects(), and TransferDataToWindow().
updateDAG()
void OperationPropertyDialog::updateDAG () private
updateIndex()
void OperationPropertyDialog::updateIndex () private
updateOperands()
void OperationPropertyDialog::updateOperands () private
Updates the operand lists.
Definition at line 443 of file OperationPropertyDialog.cc.
{
    inputOperandList_->DeleteAllItems();
    outputOperandList_->DeleteAllItems();
    for (unsigned int i = 0; i < inputOperands_.size(); i++) {
        wxString id = WxConversion::toWxString(i + 1);
        inputOperandList_->InsertItem(i, id);
        std::string type = inputOperands_.at(i)->typeString();
        inputOperandList_->SetItem(i, 1, WxConversion::toWxString(type));
        std::string elemWidth = Conversion::toString(
            inputOperands_.at(i)->elementWidth());
        inputOperandList_->SetItem(i, 2, WxConversion::toWxString(elemWidth));
        std::string elemCount = Conversion::toString(
            inputOperands_.at(i)->elementCount());
        inputOperandList_->SetItem(i, 3, WxConversion::toWxString(elemCount));
    }
    int k = 0;
    for (unsigned int i = inputOperands_.size() + 1;
         i <= inputOperands_.size() + outputOperands_.size(); i++) {
        wxString id = WxConversion::toWxString(i);
        outputOperandList_->InsertItem(k, id);
        std::string type = outputOperands_.at(k)->typeString();
        outputOperandList_->SetItem(k, 1, WxConversion::toWxString(type));
        std::string elemWidth = Conversion::toString(
            outputOperands_.at(k)->elementWidth());
        outputOperandList_->SetItem(k, 2, WxConversion::toWxString(elemWidth));
        std::string elemCount = Conversion::toString(
            outputOperands_.at(k)->elementCount());
        outputOperandList_->SetItem(k, 3, WxConversion::toWxString(elemCount));
        k++;
    }
    wxListEvent dummy;
    onSelection(dummy);
}
References dummy, inputOperandList_, inputOperands_, onSelection(), outputOperandList_, outputOperands_, Conversion::toString(), and WxConversion::toWxString().
Referenced by onAddInputOperand(), onAddOutputOperand(), onDeleteInputOperand(), onDeleteOutputOperand(), onModifyInputOperand(), onModifyOutputOperand(), and TransferDataToWindow().
updateOperation()
void OperationPropertyDialog::updateOperation (bool newOpDag) private
Definition at line 1025 of file OperationPropertyDialog.cc.
{
    TransferDataFromWindow();
    string opName =
        StringTools::stringToUpper(WxConversion::toString(name_));
    if (newOpDag && opName == "") {
        opName = "__UnnamedNewOperation";
    }
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    if (opName == "" && operation_->name() == "") {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_NAME);
        fmt % "operation";
        WarningDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
    } else {
        // let's check there isn't already an operation by the same name.
        // Do the check only if we are renaming this op.
        if (operation_ != NULL && operation_->name() != opName) {
            Operation* op =
                OperationContainer::operation(path_, module_.name(), opName);
            // there was old operation with same name
            if (op != NULL) {
                format fmt =
                    texts.text(OSEdTextGenerator::TXT_ERROR_OPERATION_EXISTS);
                fmt % WxConversion::toString(name_);
                WarningDialog dialog(this, WxConversion::toWxString(fmt.str()));
                dialog.ShowModal();
                return;
            }
        }
        ObjectState* mod = saveOperation(); // load modified operation's settings from gui
        ObjectState* orig = orig_;
        if (newOpDag) {
            operation_->loadState(mod);
        } else {
            if (*orig != *mod) {
                format fmt = texts.text(
                    OSEdTextGenerator::TXT_QUESTION_SAVE_PROPERTIES);
                ConfirmDialog dialog(this, WxConversion::toWxString(fmt.str()));
                int ans = dialog.ShowModal();
                if (ans == wxID_YES) {
                    try {
                        operation_->loadState(mod);
                    } catch (ObjectStateLoadingException& e) {
                        std::cerr << "Exception caught: " << e.errorMessage()
                                  << std::endl;
                        assert(false);
                    }
                }
                delete mod;
                if (ans == wxID_YES) {
                    delete orig;
                    EndModal(wxID_OK);
                } else if (ans == wxID_NO) {
                    EndModal(wxID_CANCEL);
                }
            } else {
                delete orig;
                delete mod;
                EndModal(wxID_OK);
            }
        }
    }
}
References assert, Exception::errorMessage(), OSEdTextGenerator::instance(), Operation::loadState(), module_, Operation::name(), OperationModule::name(), name_, OperationContainer::operation(), operation_, orig_, path_, saveOperation(), StringTools::stringToUpper(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NO_NAME, OSEdTextGenerator::TXT_ERROR_OPERATION_EXISTS, and OSEdTextGenerator::TXT_QUESTION_SAVE_PROPERTIES.
Referenced by onOk(), and onOpenDAG().
updateSwapLists()
void OperationPropertyDialog::updateSwapLists (std::vector< std::string > deletedOperands) private
Deletes deleted operands from swap lists.
Parameters
deletedOperands Deleted operands.
Definition at line 1215 of file OperationPropertyDialog.cc.
{
    for (size_t i = 0; i < inputOperands_.size(); i++) {
        Operand* operand = inputOperands_[i];
        ObjectState* state = operand->saveState();
        for (int j = 0; j < state->childCount(); j++) {
            if (state->child(j)->name() == Operand::OPRND_CAN_SWAP) {
                ObjectState* canSwap = state->child(j);
                int k = 0;
                while (k < canSwap->childCount()) {
                    ObjectState* child = canSwap->child(k);
                    int id = child->intAttribute(Operand::OPRND_ID);
                    string idString = Conversion::toString(id);
                    bool deleted = false;
                    for (size_t r = 0; r < deletedOperands.size(); r++) {
                        if (deletedOperands[r] == idString) {
                            delete child;
                            child = NULL;
                            k--;
                            deleted = true;
                            break;
                        }
                    }
                    if (!deleted) {
                        int dec = 0;
                        for (size_t r = 0; r < deletedOperands.size(); r++) {
                            int delId = Conversion::toInt(deletedOperands[r]);
                            if (delId < id) {
                                dec++;
                            }
                        }
                        id = id - dec;
                        child->setAttribute(Operand::OPRND_ID, id);
                    }
                    k++;
                }
            }
        }
        operand->loadState(state);
    }
}
References ObjectState::child(), ObjectState::childCount(), inputOperands_, ObjectState::intAttribute(), Operand::loadState(), ObjectState::name(), Operand::OPRND_CAN_SWAP, Operand::OPRND_ID, Operand::saveState(), ObjectState::setAttribute(), Conversion::toInt(), and Conversion::toString().
Referenced by onDeleteInputOperand().
updateTypes()
void OperationPropertyDialog::updateTypes () private
Member Data Documentation
affectedBy_
std::vector<std::string> OperationPropertyDialog::affectedBy_ private
Operations that are affected by this operation.
Definition at line 223 of file OperationPropertyDialog.hh.
Referenced by onAddAffectedBy(), onDeleteAffectedBy(), saveOperation(), and updateAffected().
affectedByChoice_
wxComboBox* OperationPropertyDialog::affectedByChoice_ private
Choice box for new affected by operations.
Definition at line 172 of file OperationPropertyDialog.hh.
Referenced by onAddAffectedBy(), and updateAffected().
affectedByList_
wxListCtrl* OperationPropertyDialog::affectedByList_ private
List of affected by operations.
Definition at line 164 of file OperationPropertyDialog.hh.
Referenced by onDeleteAffectedBy(), onSelection(), setTexts(), and updateAffected().
affectedBySizer_
wxStaticBoxSizer* OperationPropertyDialog::affectedBySizer_ private
Affected by sizer.
Definition at line 161 of file OperationPropertyDialog.hh.
Referenced by createContents(), and setTexts().
affects_
std::vector<std::string> OperationPropertyDialog::affects_ private
Operations that affects this operation.
Definition at line 221 of file OperationPropertyDialog.hh.
Referenced by onAddAffects(), onDeleteAffects(), saveOperation(), and updateAffected().
affectsChoice_
wxComboBox* OperationPropertyDialog::affectsChoice_ private
Choice box for new affects operations.
Definition at line 174 of file OperationPropertyDialog.hh.
Referenced by onAddAffects(), and updateAffected().
affectsList_
wxListCtrl* OperationPropertyDialog::affectsList_ private
List of affects operations.
Definition at line 166 of file OperationPropertyDialog.hh.
Referenced by onDeleteAffects(), onSelection(), setTexts(), and updateAffected().
affectsSizer_
wxStaticBoxSizer* OperationPropertyDialog::affectsSizer_ private
Affects sizer.
Definition at line 159 of file OperationPropertyDialog.hh.
Referenced by createContents(), and setTexts().
canTrap_
bool OperationPropertyDialog::canTrap_ private
Can operation trap?
Definition at line 201 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
canTrapCB_
wxCheckBox* OperationPropertyDialog::canTrapCB_ private
Can trap check box.
Definition at line 180 of file OperationPropertyDialog.hh.
clocked_
bool OperationPropertyDialog::clocked_ private
Is operation clocked?
Definition at line 205 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
clockedCB_
wxCheckBox* OperationPropertyDialog::clockedCB_ private
Clocked check box.
Definition at line 184 of file OperationPropertyDialog.hh.
controlFlow_
bool OperationPropertyDialog::controlFlow_ private
Can operation can change program flow.
Definition at line 207 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
editDescription_
wxTextCtrl* OperationPropertyDialog::editDescription_ private
Definition at line 214 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
hasSideEffects_
bool OperationPropertyDialog::hasSideEffects_ private
Does operation has side effects?
Definition at line 203 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
inputOperandList_
wxListCtrl* OperationPropertyDialog::inputOperandList_ private
List of input operands.
Definition at line 168 of file OperationPropertyDialog.hh.
Referenced by onDeleteInputOperand(), onModifyInputOperand(), onMoveInputDown(), onMoveInputUp(), onSelection(), setTexts(), and updateOperands().
inputOperands_
std::vector<Operand*> OperationPropertyDialog::inputOperands_ private
Input operands.
Definition at line 217 of file OperationPropertyDialog.hh.
Referenced by onAddInputOperand(), onAddOutputOperand(), onDeleteInputOperand(), onDeleteOutputOperand(), onModifyInputOperand(), onModifyOutputOperand(), onMoveInputDown(), onMoveInputUp(), onMoveOutputDown(), onMoveOutputUp(), onSelection(), saveOperation(), updateOperands(), updateSwapLists(), and ~OperationPropertyDialog().
inputSizer_
wxStaticBoxSizer* OperationPropertyDialog::inputSizer_ private
Input operand sizer.
Definition at line 155 of file OperationPropertyDialog.hh.
Referenced by createContents(), and setTexts().
isBranch_
bool OperationPropertyDialog::isBranch_ private
Operation is branch.
Definition at line 211 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
isCall_
bool OperationPropertyDialog::isCall_ private
Operation performs function call.
Definition at line 209 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
module_
OperationModule& OperationPropertyDialog::module_ private
Module in which operation belongs to.
Definition at line 193 of file OperationPropertyDialog.hh.
Referenced by createContents(), onOpen(), setBehaviorLabel(), and updateOperation().
name_
wxString OperationPropertyDialog::name_ private
Name of the operation.
Definition at line 191 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), TransferDataToWindow(), and updateOperation().
operation_
Operation* OperationPropertyDialog::operation_ private
Operation to be created or to be modified.
Definition at line 186 of file OperationPropertyDialog.hh.
Referenced by onOpenDAG(), operation(), saveOperation(), TransferDataToWindow(), updateOperation(), and ~OperationPropertyDialog().
operationWasCreatedHere_
bool OperationPropertyDialog::operationWasCreatedHere_ private
Definition at line 225 of file OperationPropertyDialog.hh.
Referenced by onOpenDAG(), and ~OperationPropertyDialog().
orig_
ObjectState* OperationPropertyDialog::orig_ private
Original operation's ObjectState tree.
Definition at line 188 of file OperationPropertyDialog.hh.
Referenced by updateOperation().
outputOperandList_
wxListCtrl* OperationPropertyDialog::outputOperandList_ private
List of output operands.
Definition at line 170 of file OperationPropertyDialog.hh.
Referenced by onDeleteOutputOperand(), onModifyOutputOperand(), onMoveOutputDown(), onMoveOutputUp(), onSelection(), setTexts(), and updateOperands().
outputOperands_
std::vector<Operand*> OperationPropertyDialog::outputOperands_ private
Output operands.
Definition at line 219 of file OperationPropertyDialog.hh.
Referenced by onAddOutputOperand(), onDeleteOutputOperand(), onModifyOutputOperand(), onMoveOutputDown(), onMoveOutputUp(), onSelection(), saveOperation(), updateOperands(), and ~OperationPropertyDialog().
outputSizer_
wxStaticBoxSizer* OperationPropertyDialog::outputSizer_ private
Output operand sizer.
Definition at line 157 of file OperationPropertyDialog.hh.
Referenced by createContents(), and setTexts().
path_
std::string OperationPropertyDialog::path_ private
Path in which module belongs to.
Definition at line 195 of file OperationPropertyDialog.hh.
Referenced by updateOperation().
readMemory_
bool OperationPropertyDialog::readMemory_ private
Does operation read memory?
Definition at line 197 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
readMemoryCB_
wxCheckBox* OperationPropertyDialog::readMemoryCB_ private
Read memory check box.
Definition at line 176 of file OperationPropertyDialog.hh.
sideEffectsCB_
wxCheckBox* OperationPropertyDialog::sideEffectsCB_ private
Has side effects check box.
Definition at line 182 of file OperationPropertyDialog.hh.
writeMemory_
bool OperationPropertyDialog::writeMemory_ private
Does operation write memory?
Definition at line 199 of file OperationPropertyDialog.hh.
Referenced by saveOperation(), and TransferDataToWindow().
writeMemoryCB_
wxCheckBox* OperationPropertyDialog::writeMemoryCB_ private
Write memory check box.
Definition at line 178 of file OperationPropertyDialog.hh.
The documentation for this class was generated from the following files:
OperationPropertyDialog.hh
OperationPropertyDialog.cc