OpenASIP: TPEF::ReferenceManager::HashFunctions Class Reference
TPEF::ReferenceManager::HashFunctions Class Reference
#include <SafePointer.hh>
Public Member Functions
size_t operator() (const SectionIndexKey &key) const
size_t operator() (const SectionOffsetKey &key) const
size_t operator() (const FileOffsetKey &key) const
size_t operator() (const SectionKey &key) const
size_t operator() (const SafePointable *const &key) const
Detailed Description
Class containing all the hash functions if hash_map is used. However the use of hash_map will make program very slow unless MapTools::containsValue() is not optimised for hash_tables or that function should be circumvented.
Definition at line 111 of file SafePointer.hh.
Member Function Documentation
operator()() [1/5]
size_t TPEF::ReferenceManager::HashFunctions::operator() (const FileOffsetKey & key) const inline
Definition at line 127 of file SafePointer.hh.
{
        return key.fileOffset();
    }
References TPEF::ReferenceManager::FileOffsetKey::fileOffset().
operator()() [2/5]
size_t TPEF::ReferenceManager::HashFunctions::operator() (const SafePointable *const & key) const inline
Definition at line 135 of file SafePointer.hh.
{
        return reinterpret_cast<size_t>(key);
    }
operator()() [3/5]
size_t TPEF::ReferenceManager::HashFunctions::operator() (const SectionIndexKey & key) const inline
Definition at line 113 of file SafePointer.hh.
{
        return key.index()^
            (static_cast<size_t>(key.sectionId()) <<
             ((sizeof(size_t) - sizeof(SectionId)) *
              BYTE_BITWIDTH));
    }
References BYTE_BITWIDTH, TPEF::ReferenceManager::SectionIndexKey::index(), and TPEF::ReferenceManager::SectionIndexKey::sectionId().
operator()() [4/5]
size_t TPEF::ReferenceManager::HashFunctions::operator() (const SectionKey & key) const inline
Definition at line 131 of file SafePointer.hh.
{
        return key.sectionId();
    }
References TPEF::ReferenceManager::SectionKey::sectionId().
operator()() [5/5]
size_t TPEF::ReferenceManager::HashFunctions::operator() (const SectionOffsetKey & key) const inline
Definition at line 120 of file SafePointer.hh.
{
        return key.offset()^
            (static_cast<size_t>(key.sectionId()) <<
             ((sizeof(size_t) - sizeof(SectionId)) *
              BYTE_BITWIDTH));
    }
References BYTE_BITWIDTH, TPEF::ReferenceManager::SectionOffsetKey::offset(), and TPEF::ReferenceManager::SectionOffsetKey::sectionId().
The documentation for this class was generated from the following file:
SafePointer.hh