OpenASIP: AddBusCmd Class Reference
AddBusCmd Class Reference
#include <AddBusCmd.hh>
Public Member Functions
AddBusCmd ()
virtual bool Do ()
virtual int id () const
virtual AddBusCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new buses to the Machine.
Displays a bus dialog and creates a new bus according to the dialog output.
Definition at line 43 of file AddBusCmd.hh.
Constructor & Destructor Documentation
AddBusCmd()
AddBusCmd::AddBusCmd ()
The Constructor.
Definition at line 56 of file AddBusCmd.cc.
                     :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_BUS) {
}
Referenced by create().
Member Function Documentation
create()
AddBusCmd * AddBusCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 130 of file AddBusCmd.cc.
{
    return new AddBusCmd();
}
References AddBusCmd().
Do()
bool AddBusCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 68 of file AddBusCmd.cc.
              {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    // Generate name for the new bus.
    Machine::BusNavigator navigator =
        model->getMachine()->busNavigator();
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_BUS +
        Conversion::toString(i);
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_BUS +
            Conversion::toString(i);
        i++;
    }
    Bus* bus =
        new Bus(newName, ModelConstants::DEFAULT_WIDTH,
                ModelConstants::DEFAULT_WIDTH, Machine::ZERO);
    bus->setMachine(*(model->getMachine()));
    // Create an always-true guard for the bus by default.
    new UnconditionalGuard(false, *bus);
    // Add a default segment to the bus.
    new Segment(ProDeConstants::COMP_DEFAULT_NAME_SEGMENT, *bus);
    BusDialog dialog(parentWindow(), bus);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    // bus creation was cancelled
    model->popFromStack();
    return false;
    }
}
References assert, TTAMachine::Machine::busNavigator(), ProDeConstants::COMP_DEFAULT_NAME_SEGMENT, ProDeConstants::COMP_NEW_NAME_PREFIX_BUS, ModelConstants::DEFAULT_WIDTH, Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), TTAMachine::Bus::setMachine(), Conversion::toString(), EditorCommand::view(), and TTAMachine::Machine::ZERO.
id()
int AddBusCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 119 of file AddBusCmd.cc.
                    {
    return ProDeConstants::COMMAND_ADD_BUS;
}
References ProDeConstants::COMMAND_ADD_BUS.
isEnabled()
bool AddBusCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 154 of file AddBusCmd.cc.
                     {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddBusCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 141 of file AddBusCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_BUS;
}
References ProDeConstants::CMD_SNAME_ADD_BUS.
The documentation for this class was generated from the following files:
AddBusCmd.hh
AddBusCmd.cc