OpenASIP: ExecutableInstruction Class Reference
ExecutableInstruction Class Reference
#include <ExecutableInstruction.hh>
Public Member Functions
ExecutableInstruction ()
virtual ~ExecutableInstruction ()
void addExecutableMove (ExecutableMove *move)
void addLongImmediateUpdateAction (LongImmUpdateAction *action)
void execute ()
ClockCycleCount executionCount () const
ClockCycleCount moveExecutionCount (std::size_t moveIndex) const
void resetExecutionCounts ()
bool moveSquashed (std::size_t moveIndex) const
void setExitPoint (bool b)
bool isExitPoint () const
Private Types
typedef std::vector< ExecutableMove * > MoveContainer
Contains ExecutableMoves.
typedef std::vector< LongImmUpdateAction * > UpdateContainer
Contains long immediate update actions.
Private Member Functions
ExecutableInstruction (const ExecutableInstruction &)
Copying not allowed.
ExecutableInstruction & operator= (const ExecutableInstruction &)
Assignment not allowed.
Private Attributes
MoveContainer moves_
All moves of the instruction.
UpdateContainer updateActions_
All long immediate update actions.
ClockCycleCount executionCount_
The count of times this instruction has been executed.
bool exitPoint_
True in case the instruction is considered a program exit point.
Detailed Description
Represents an interpreted TTA instruction.
This class is used to simulate the data transports performed by a TTA instruction.
Definition at line 49 of file ExecutableInstruction.hh.
Member Typedef Documentation
MoveContainer
typedef std::vector<ExecutableMove*> ExecutableInstruction::MoveContainer private
Contains ExecutableMoves.
Definition at line 74 of file ExecutableInstruction.hh.
UpdateContainer
typedef std::vector<LongImmUpdateAction*> ExecutableInstruction::UpdateContainer private
Contains long immediate update actions.
Definition at line 76 of file ExecutableInstruction.hh.
Constructor & Destructor Documentation
ExecutableInstruction() [1/2]
ExecutableInstruction::ExecutableInstruction ()
Constructor.
Definition at line 42 of file ExecutableInstruction.cc.
                                             :
    exitPoint_(false) {
    resetExecutionCounts();
}
References resetExecutionCounts().
~ExecutableInstruction()
ExecutableInstruction::~ExecutableInstruction () virtual
Destructor.
Definition at line 50 of file ExecutableInstruction.cc.
{
    SequenceTools::deleteAllItems(moves_);
    SequenceTools::deleteAllItems(updateActions_);
}
References SequenceTools::deleteAllItems(), moves_, and updateActions_.
ExecutableInstruction() [2/2]
ExecutableInstruction::ExecutableInstruction (const ExecutableInstruction &) private
Copying not allowed.
Member Function Documentation
addExecutableMove()
void ExecutableInstruction::addExecutableMove (ExecutableMove * move)
Adds move to the instruction.
Moves must be added in the same order they are in source Program model's instruction.
Parameters
move Move to be added.
Definition at line 64 of file ExecutableInstruction.cc.
{
    moves_.push_back(move);
}
References moves_.
Referenced by CompiledSimUtilizationStats::calculate(), and SimProgramBuilder::processInstruction().
addLongImmediateUpdateAction()
void ExecutableInstruction::addLongImmediateUpdateAction (LongImmUpdateAction * action)
Adds long immediate update action.
Parameters
action Action to be added.
Definition at line 74 of file ExecutableInstruction.cc.
{
    updateActions_.push_back(action);
}
References updateActions_.
Referenced by SimProgramBuilder::processInstruction().
execute()
void ExecutableInstruction::execute ()
Referenced by OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
executionCount()
ClockCycleCount ExecutableInstruction::executionCount () const
Returns the count of times this instruction has been executed so far.
Returns
The execution count of this instruction.
Definition at line 85 of file ExecutableInstruction.cc.
{
    return executionCount_;
}
References executionCount_.
Referenced by SimulationStatistics::calculate(), SimulatorFrontend::finishSimulation(), RFAccessTracker::handleEvent(), DisasmTopCountAttrProvider::moveCellAttr(), DesignSpaceExplorer::simulate(), and DisasmTopCountAttrProvider::updateTopCountTable().
isExitPoint()
bool ExecutableInstruction::isExitPoint () const
Referenced by OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
moveExecutionCount()
ClockCycleCount ExecutableInstruction::moveExecutionCount (std::size_t moveIndex) const
Returns the count of full executions so far of move at given index.
Squashed moves are not included in the count. Thus, to get count of times a move has be squashed, one should get the instruction execution count and subsract the move's execution count from it.
Returns
Count of executions of move at given move slot.
Definition at line 110 of file ExecutableInstruction.cc.
{
    return moves_[moveIndex]->executionCount();
}
References moves_.
Referenced by UtilizationStats::calculateForInstruction(), and DisasmExecPercentageAttrProvider::moveCellAttr().
moveSquashed()
bool ExecutableInstruction::moveSquashed (std::size_t moveIndex) const
Referenced by ProximMachineStateWindow::addMoves(), and RFAccessTracker::handleEvent().
operator=()
ExecutableInstruction & ExecutableInstruction::operator= (const ExecutableInstruction &) private
Assignment not allowed.
resetExecutionCounts()
void ExecutableInstruction::resetExecutionCounts ()
Resets the execution counters of this instruction and its moves.
Definition at line 93 of file ExecutableInstruction.cc.
{
    executionCount_ = 0;
    for (std::size_t i = 0; i < moves_.size(); ++i) {
        moves_[i]->resetExecutionCount();
    }
}
References executionCount_, and moves_.
Referenced by ExecutableInstruction(), and InstructionMemory::resetExecutionCounts().
setExitPoint()
void ExecutableInstruction::setExitPoint (bool b)
Member Data Documentation
executionCount_
ClockCycleCount ExecutableInstruction::executionCount_ private
The count of times this instruction has been executed.
Definition at line 82 of file ExecutableInstruction.hh.
Referenced by executionCount(), and resetExecutionCounts().
exitPoint_
bool ExecutableInstruction::exitPoint_ private
True in case the instruction is considered a program exit point.
Definition at line 84 of file ExecutableInstruction.hh.
moves_
MoveContainer ExecutableInstruction::moves_ private
All moves of the instruction.
Definition at line 78 of file ExecutableInstruction.hh.
Referenced by addExecutableMove(), moveExecutionCount(), resetExecutionCounts(), and ~ExecutableInstruction().
updateActions_
UpdateContainer ExecutableInstruction::updateActions_ private
All long immediate update actions.
Definition at line 80 of file ExecutableInstruction.hh.
Referenced by addLongImmediateUpdateAction(), and ~ExecutableInstruction().
The documentation for this class was generated from the following files:
ExecutableInstruction.hh
ExecutableInstruction.cc