OpenASIP: HWBlockArchitecture Class Reference
HWBlockArchitecture Class Reference
#include <HWBlockArchitecture.hh>
Public Member Functions
virtual ~HWBlockArchitecture ()
bool hasID () const
void setID (RowID id)
RowID id () const
Protected Member Functions
HWBlockArchitecture ()
Private Attributes
bool hasID_
RowID id_
Detailed Description
An abstract base class for FUArchitecture and RFArchitecture.
Definition at line 42 of file HWBlockArchitecture.hh.
Constructor & Destructor Documentation
~HWBlockArchitecture()
HWBlockArchitecture::~HWBlockArchitecture () virtual
The destructor.
Definition at line 46 of file HWBlockArchitecture.cc.
{
}
HWBlockArchitecture()
HWBlockArchitecture::HWBlockArchitecture () protected
The constructor.
Definition at line 38 of file HWBlockArchitecture.cc.
                                         :
    hasID_(false), id_(0) {
}
Member Function Documentation
hasID()
bool HWBlockArchitecture::hasID () const
Tells whether the entry has an ID.
Returns
True if the entry has an ID, otherwise false.
Definition at line 56 of file HWBlockArchitecture.cc.
{
    return hasID_;
}
References hasID_.
Referenced by id().
id()
RowID HWBlockArchitecture::id () const
Returns the ID of the entry.
Returns
ID of the entry.
Definition at line 79 of file HWBlockArchitecture.cc.
{
    if (!hasID()) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    } else {
        return id_;
    }
}
References __func__, hasID(), and id_.
Referenced by HDB::HDBManager::fuEntriesByArchitecture(), HDBToHtml::fuEntryToHtml(), HDBToHtml::rfEntryToHtml(), setID(), and HDBBrowserWindow::update().
setID()
void HWBlockArchitecture::setID (RowID id)
Sets the ID for the entry.
Parameters
id The ID to set.
Definition at line 67 of file HWBlockArchitecture.cc.
{
    hasID_ = true;
    id_ = id;
}
References hasID_, id(), and id_.
Referenced by HDB::HDBManager::fuArchitectureByID(), and HDB::HDBManager::rfArchitectureByID().
Member Data Documentation
hasID_
bool HWBlockArchitecture::hasID_ private
Definition at line 54 of file HWBlockArchitecture.hh.
Referenced by hasID(), and setID().
id_
RowID HWBlockArchitecture::id_ private
Definition at line 55 of file HWBlockArchitecture.hh.
Referenced by id(), and setID().
The documentation for this class was generated from the following files:
HWBlockArchitecture.hh
HWBlockArchitecture.cc