OpenASIP: SQLite Class Reference
SQLite Class Reference
#include <SQLite.hh>
Public Member Functions
SQLite ()
virtual ~SQLite ()
virtual RelationalDBConnection & connect (const std::string &database, const std::string &login="", const std::string &password="", bool readOnly=false)
virtual void close (const RelationalDBConnection &connection)
Public Member Functions inherited from RelationalDB
virtual ~RelationalDB ()
Private Attributes
SQLiteConnection * activeConnection_
Only one simultaneous active connection per SQLite instance allowed currently.
Detailed Description
Implementation of RelationalDB interface for SQLite library.
Definition at line 45 of file SQLite.hh.
Constructor & Destructor Documentation
SQLite()
SQLite::SQLite ()
Constructor.
Definition at line 44 of file SQLite.cc.
               : activeConnection_(NULL) {
}
~SQLite()
SQLite::~SQLite () virtual
Destructor.
Definition at line 50 of file SQLite.cc.
                {
    close(*activeConnection_);
}
References activeConnection_, and close().
Member Function Documentation
close()
void SQLite::close (const RelationalDBConnection & connection) virtual
Closes a database connection.
Close should be idempotent, that is, it can be called arbitrary amount of times to a connection without an error.
Parameters
connection The database connection to close.
Exceptions
RelationalDBException Thrown if closing the connection failed.
Implements RelationalDB.
Definition at line 100 of file SQLite.cc.
{
    if (activeConnection_ == NULL) {
        return;
    }
    delete activeConnection_;
    activeConnection_ = NULL;
}
References activeConnection_.
Referenced by connect(), DSDBManager::createNew(), HDB::HDBManager::createNew(), DSDBManager::~DSDBManager(), HDB::HDBManager::~HDBManager(), and ~SQLite().
connect()
RelationalDBConnection & SQLite::connect (const std::string & database, const std::string & login = "", const std::string & password = "", bool readOnly = false) virtual
Connects to a database.
Possible old connection is closed. SQLite implementation doesn't support multiple active connections currently. If database file is not found, creation of new database file with the given name is attempted.
Parameters
database The filename of the SQLite database.
login Login name to use for the database connection.
password Password to use for the database connection.
readOnly Should the database be opened in read-only mode only?
Returns
Connection "handle" which is used to query the DB, etc.
Exceptions
RelationalDBException Thrown if connection failed.
Implements RelationalDB.
Definition at line 69 of file SQLite.cc.
{
    if (activeConnection_ != NULL) {
        close(*activeConnection_);
        activeConnection_ = NULL;
    }
    sqlite3* connection = NULL;
    int value = sqlite3_open(database.c_str(), &connection);
    if (value != SQLITE_OK) {
        string error = sqlite3_errmsg(connection);
        error += " - file:\"" + database +"\"";
        throw RelationalDBException(
            __FILE__, __LINE__, "SQLite::connect()", error);
    }
    activeConnection_ = new SQLiteConnection(connection);
    return *activeConnection_;
}
References activeConnection_, and close().
Referenced by DSDBManager::createNew(), HDB::HDBManager::createNew(), DSDBManager::DSDBManager(), and HDB::HDBManager::HDBManager().
Member Data Documentation
activeConnection_
SQLiteConnection* SQLite::activeConnection_ private
Only one simultaneous active connection per SQLite instance allowed currently.
Definition at line 59 of file SQLite.hh.
Referenced by close(), connect(), and ~SQLite().
The documentation for this class was generated from the following files:
SQLite.hh
SQLite.cc