OpenASIP: IPXactClkInterface Class Reference
IPXactClkInterface Class Reference
#include <IPXactClkInterface.hh>
Public Member Functions
IPXactClkInterface ()
virtual ~IPXactClkInterface ()
virtual bool mapPortsToInterface (const ProGe::NetlistBlock &toplevel)
Public Member Functions inherited from IPXactInterface
IPXactInterface ()
virtual ~IPXactInterface ()
virtual TCEString instanceName () const
virtual IPXact::Vlnv busType () const
virtual IPXact::Vlnv busAbstractionType () const
virtual IPXactModel::BusMode busMode () const
virtual const PlatInt::SignalMappingList & interfaceMapping () const
virtual void addSignalMapping (const TCEString &actualSignal, const TCEString &busSignal)
void setInstanceName (const TCEString &name)
Static Private Attributes
static const TCEString TTA_CLK_PORT = "clk"
static const TCEString SPIRIT_CLK_PORT = "CLK"
static const TCEString DEFAULT_INSTANCE_NAME = "clk_in"
static const TCEString VENDOR = "TUT"
static const TCEString LIBRARY ="ip.hwp.interface"
static const TCEString NAME ="clock.busdef"
static const TCEString BUS_VERSION = "1.0"
static const TCEString ABS_VENDOR
static const TCEString ABS_LIBRARY
static const TCEString ABS_NAME = "clock.absDef"
static const TCEString ABS_VERSION
static const IPXactModel::BusMode DEFAULT_BUS_MODE
Additional Inherited Members
Protected Member Functions inherited from IPXactInterface
void setBusMode (IPXactModel::BusMode mode)
void setBusType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
void setBusAbsType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
Detailed Description
Definition at line 37 of file IPXactClkInterface.hh.
Constructor & Destructor Documentation
IPXactClkInterface()
IPXactClkInterface::IPXactClkInterface ()
Definition at line 54 of file IPXactClkInterface.cc.
                                      : IPXactInterface() {
    setInstanceName(DEFAULT_INSTANCE_NAME);
    setBusType(VENDOR, LIBRARY, NAME, BUS_VERSION);
    setBusAbsType(ABS_VENDOR, ABS_LIBRARY, ABS_NAME, ABS_VERSION);
    setBusMode(DEFAULT_BUS_MODE);
}
References ABS_LIBRARY, ABS_NAME, ABS_VENDOR, ABS_VERSION, BUS_VERSION, DEFAULT_BUS_MODE, DEFAULT_INSTANCE_NAME, LIBRARY, NAME, IPXactInterface::setBusAbsType(), IPXactInterface::setBusMode(), IPXactInterface::setBusType(), IPXactInterface::setInstanceName(), and VENDOR.
~IPXactClkInterface()
IPXactClkInterface::~IPXactClkInterface () virtual
Definition at line 62 of file IPXactClkInterface.cc.
{
}
Member Function Documentation
mapPortsToInterface()
bool IPXactClkInterface::mapPortsToInterface (const ProGe::NetlistBlock & toplevel) virtual
Implements IPXactInterface.
Definition at line 66 of file IPXactClkInterface.cc.
{
    for (size_t i = 0; i < toplevel.portCount(); i++) {
        if (toplevel.port(i).name() == TTA_CLK_PORT) {
            addSignalMapping(TTA_CLK_PORT, SPIRIT_CLK_PORT);
            return true;
        }
    }
    TCEString msg = "Clock port " + TTA_CLK_PORT + " not found!";
    InvalidData exc(__FILE__, __LINE__, "IPXactClkInterface", msg);
    throw exc;
    return false;
}
References IPXactInterface::addSignalMapping(), ProGe::NetlistPort::name(), ProGe::NetlistBlock::port(), ProGe::NetlistBlock::portCount(), SPIRIT_CLK_PORT, and TTA_CLK_PORT.
Member Data Documentation
ABS_LIBRARY
const TCEString IPXactClkInterface::ABS_LIBRARY static private
Initial value:
=
    IPXactClkInterface::LIBRARY
Definition at line 57 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
ABS_NAME
const TCEString IPXactClkInterface::ABS_NAME = "clock.absDef" static private
Definition at line 58 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
ABS_VENDOR
const TCEString IPXactClkInterface::ABS_VENDOR static private
Initial value:
=
    IPXactClkInterface::VENDOR
Definition at line 56 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
ABS_VERSION
const TCEString IPXactClkInterface::ABS_VERSION static private
Initial value:
=
    IPXactClkInterface::BUS_VERSION
Definition at line 59 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
BUS_VERSION
const TCEString IPXactClkInterface::BUS_VERSION = "1.0" static private
Definition at line 55 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
DEFAULT_BUS_MODE
const IPXactModel::BusMode IPXactClkInterface::DEFAULT_BUS_MODE static private
Initial value:
=
    IPXactModel::SLAVE
Definition at line 61 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
DEFAULT_INSTANCE_NAME
const TCEString IPXactClkInterface::DEFAULT_INSTANCE_NAME = "clk_in" static private
Definition at line 51 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
LIBRARY
const TCEString IPXactClkInterface::LIBRARY ="ip.hwp.interface" static private
Definition at line 53 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
NAME
const TCEString IPXactClkInterface::NAME ="clock.busdef" static private
Definition at line 54 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
SPIRIT_CLK_PORT
const TCEString IPXactClkInterface::SPIRIT_CLK_PORT = "CLK" static private
Definition at line 49 of file IPXactClkInterface.hh.
Referenced by mapPortsToInterface().
TTA_CLK_PORT
const TCEString IPXactClkInterface::TTA_CLK_PORT = "clk" static private
Definition at line 48 of file IPXactClkInterface.hh.
Referenced by mapPortsToInterface().
VENDOR
const TCEString IPXactClkInterface::VENDOR = "TUT" static private
Definition at line 52 of file IPXactClkInterface.hh.
Referenced by IPXactClkInterface().
The documentation for this class was generated from the following files:
IPXactClkInterface.hh
IPXactClkInterface.cc