OpenASIP: VhdlImageWriter Class Reference
VhdlImageWriter Class Reference
#include <VhdlImageWriter.hh>
Public Member Functions
VhdlImageWriter (const BitVector &bits, int rowLength, const std::string &entityName)
virtual ~VhdlImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from ArrayImageWriter
ArrayImageWriter (const BitVector &bits, int rowLength)
virtual ~ArrayImageWriter ()
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Private Member Functions
void writeHeader (std::ostream &stream) const
void writeEnding (std::ostream &stream) const
std::string packageName () const
Private Attributes
std::string entityName_
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Writes the (instruction) bit image to a vhdl package.
Definition at line 43 of file VhdlImageWriter.hh.
Constructor & Destructor Documentation
VhdlImageWriter()
VhdlImageWriter::VhdlImageWriter (const BitVector & bits, int rowLength, const std::string & entityName)
The constructor.
Parameters
bits The bits to write.
rowLength Length of the rows to write.
Definition at line 45 of file VhdlImageWriter.cc.
                                 :
    ArrayImageWriter(bits, rowLength), entityName_(entityName) {
}
~VhdlImageWriter()
VhdlImageWriter::~VhdlImageWriter () virtual
The destructor.
Definition at line 55 of file VhdlImageWriter.cc.
{
}
Member Function Documentation
packageName()
std::string VhdlImageWriter::packageName () const private
Definition at line 95 of file VhdlImageWriter.cc.
{
    std::string package = "dmem_image";
    if (!entityName_.empty()) {
        package = entityName_ + "_" + package;
    }
    return package;
}
Referenced by writeEnding(), and writeHeader().
writeEnding()
void VhdlImageWriter::writeEnding (std::ostream & stream) const private
Writes the end declarations to the stream
Definition at line 89 of file VhdlImageWriter.cc.
{
    stream << ");" << endl << endl
           << "end " << packageName() << ";" << endl;
}
References packageName().
Referenced by writeImage().
writeHeader()
void VhdlImageWriter::writeHeader (std::ostream & stream) const private
Writes the vhdl declaration stuff to the beginning of the stream
Definition at line 73 of file VhdlImageWriter.cc.
{
    stream << "library ieee;" << endl
           << "use ieee.std_logic_1164.all;" << endl
           << "use ieee.std_logic_arith.all;" << endl << endl;
    stream << "package " << packageName() << " is" << endl << endl
           << "  type std_logic_dmem_matrix is array (natural range <>) of "
           << "std_logic_vector(" << rowLength() << "-1 downto 0);"
           << endl << endl;
    stream << "  constant dmem_array : std_logic_dmem_matrix := (" << endl;
}
References packageName(), and AsciiImageWriter::rowLength().
Referenced by writeImage().
writeImage()
void VhdlImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given stream.
Parameters
stream The stream to write.
Reimplemented from ArrayImageWriter.
Definition at line 63 of file VhdlImageWriter.cc.
{
    writeHeader(stream);
    ArrayImageWriter::writeImage(stream);
    writeEnding(stream);
}
References writeEnding(), writeHeader(), and ArrayImageWriter::writeImage().
Member Data Documentation
entityName_
std::string VhdlImageWriter::entityName_ private
Definition at line 59 of file VhdlImageWriter.hh.
The documentation for this class was generated from the following files:
VhdlImageWriter.hh
VhdlImageWriter.cc