OpenASIP: CostDBEntryKey Class Reference
CostDBEntryKey Class Reference
#include <CostDBEntryKey.hh>
Public Member Functions
CostDBEntryKey (const EntryKeyProperty *entryType)
virtual ~CostDBEntryKey ()
CostDBEntryKey * copy () const
const EntryKeyProperty * type () const
EntryKeyField keyFieldOfType (const EntryKeyFieldProperty &fieldType) const
EntryKeyField keyFieldOfType (std::string fieldType) const
bool isEqual (const CostDBEntryKey &entryKey) const
void addField (EntryKeyField *field)
void replaceField (EntryKeyField *newField)
int fieldCount () const
const EntryKeyField & field (int index) const
Private Types
typedef std::vector< EntryKeyField * > FieldTable
Table of entry fields.
Private Member Functions
CostDBEntryKey (const CostDBEntryKey &)
Copying not allowed.
CostDBEntryKey & operator= (const CostDBEntryKey &)
Assignment not allowed.
Private Attributes
const EntryKeyProperty * type_
Type of the entry key.
FieldTable fields_
Fields of the entry key.
Detailed Description
Represents the key of the CostDBEntry.
Key properties are the properties of an entry that are used as a search key.
Definition at line 52 of file CostDBEntryKey.hh.
Member Typedef Documentation
FieldTable
typedef std::vector<EntryKeyField*> CostDBEntryKey::FieldTable private
Table of entry fields.
Definition at line 70 of file CostDBEntryKey.hh.
Constructor & Destructor Documentation
CostDBEntryKey() [1/2]
CostDBEntryKey::CostDBEntryKey (const EntryKeyProperty * entryType)
Constructor.
Parameters
entryType Type of the entry key.
Definition at line 43 of file CostDBEntryKey.cc.
                                                                :
    type_(entryType) {
}
~CostDBEntryKey()
CostDBEntryKey::~CostDBEntryKey () virtual
Destructor.
Deallocates memory reserved for the fields of the entry key.
Definition at line 52 of file CostDBEntryKey.cc.
{
    for (FieldTable::iterator i = fields_.begin(); i != fields_.end(); i++) {
        assert(*i != NULL);
        delete *i;
        *i = NULL;
    }
}
References assert, and fields_.
CostDBEntryKey() [2/2]
CostDBEntryKey::CostDBEntryKey (const CostDBEntryKey &) private
Copying not allowed.
Member Function Documentation
addField()
void CostDBEntryKey::addField (EntryKeyField * field)
Adds certain field to the entry key.
Parameters
field A field to be added.
Exceptions
ObjectAlreadyExists Equal field already exists.
Definition at line 88 of file CostDBEntryKey.cc.
{
    for (FieldTable::iterator i = fields_.begin(); i != fields_.end(); i++) {
        if ((*i)->type() == field->type()) {
            throw ObjectAlreadyExists(
                __FILE__, __LINE__, "CostDBEntryKey::addField");
        }
    }
    fields_.push_back(field);
}
References field(), fields_, and EntryKeyField::type().
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), copy(), InterpolatingRFEstimator::createSearch(), and InterpolatingFUEstimator::createSearch().
copy()
CostDBEntryKey * CostDBEntryKey::copy () const
Copies the entry key.
Client is responsible of deallocating the memory reserved for the returned object.
Returns
A copy of the entry key.
Definition at line 69 of file CostDBEntryKey.cc.
{
    CostDBEntryKey* copy = new CostDBEntryKey(type_);
    for (FieldTable::const_iterator i = fields_.begin();
         i != fields_.end(); i++) {
        copy->addField(new EntryKeyField(*(*i)));
    }
    return copy;
}
References addField(), copy(), fields_, and type_.
Referenced by CostDBEntry::copy(), copy(), FilterSearch::Cache::copy(), CostDBEntry::CostDBEntry(), and FilterSearch::search().
field()
const EntryKeyField & CostDBEntryKey::field (int index) const
Returns the field found on the given index.
The index must be between 0 and the number of fields - 1.
Parameters
index Index.
Returns
The field found on the given index.
Exceptions
OutOfRange Index was out of range.
Definition at line 181 of file CostDBEntryKey.cc.
{
    if (index >= fieldCount() || index < 0) {
        throw OutOfRange(__FILE__, __LINE__, "CostDBEntryKey::field");
    }
    return *fields_[index];
}
References fieldCount(), and fields_.
Referenced by addField(), and CostDBEntry::field().
fieldCount()
int CostDBEntryKey::fieldCount () const
Referenced by field(), and CostDBEntry::fieldCount().
isEqual()
bool CostDBEntryKey::isEqual (const CostDBEntryKey & entryKey) const
Compares if two entry keys are equal.
Parameters
entryKey An entry key.
Returns
True if two entry keys are equal, otherwise false.
Definition at line 152 of file CostDBEntryKey.cc.
{
    if (type() == entryKey.type()) {
        bool isMatch = true;
        for (FieldTable::const_iterator f = fields_.begin();
             f != fields_.end(); f++) {
            if (!(*f)->isEqual(entryKey.keyFieldOfType(*(*f)->type()))) {
                isMatch = false;
                break;
            }
        }
        if (isMatch) {
            return true;
        }
    }
    return false;
}
References fields_, keyFieldOfType(), and type().
Referenced by CostDBEntry::isEqualKey().
keyFieldOfType() [1/2]
EntryKeyField CostDBEntryKey::keyFieldOfType (const EntryKeyFieldProperty & fieldType) const
Returns demanded field of the entry key.
Parameters
fieldType Type of the field.
Exceptions
KeyNotFound Requested field type was not found.
Definition at line 123 of file CostDBEntryKey.cc.
{
    for (FieldTable::const_iterator i = fields_.begin();
         i != fields_.end(); i++) {
        if ((*i)->type() == &fieldType) {
            return *(*i);
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, "CostDBEntry::keyFieldOfType");
    return *fields_[0];// stupid return statement to make compiler quiet
}
References fields_.
Referenced by Interpolation::filter(), isEqual(), CostDBEntry::keyFieldOfType(), keyFieldOfType(), CostDBEntry::keyFieldOfType(), and ExactMatch::quickFilter().
keyFieldOfType() [2/2]
EntryKeyField CostDBEntryKey::keyFieldOfType (std::string fieldType) const
Returns demanded field of the entry key.
Returns
type Type of the field.
Definition at line 140 of file CostDBEntryKey.cc.
{
    return keyFieldOfType(*type_->fieldProperty(fieldType));
}
References EntryKeyProperty::fieldProperty(), keyFieldOfType(), and type_.
operator=()
CostDBEntryKey & CostDBEntryKey::operator= (const CostDBEntryKey &) private
Assignment not allowed.
replaceField()
void CostDBEntryKey::replaceField (EntryKeyField * newField)
Replaces certain field of the entry key.
Parameters
newField A field.
Exceptions
KeyNotFound Equal field was not found.
Definition at line 105 of file CostDBEntryKey.cc.
{
    for (FieldTable::iterator i = fields_.begin(); i != fields_.end(); i++) {
        if ((*i)->type() == newField->type()) {
            delete *i;
            *i = newField;
            return;
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, "CostDBEntry::replaceField");
}
References fields_, and EntryKeyField::type().
Referenced by CostDBEntry::CostDBEntry(), and CostDBEntry::replaceField().
type()
const EntryKeyProperty * CostDBEntryKey::type () const
Referenced by isEqual(), CostDatabase::search(), and CostDBEntry::type().
Member Data Documentation
fields_
FieldTable CostDBEntryKey::fields_ private
Fields of the entry key.
Definition at line 75 of file CostDBEntryKey.hh.
Referenced by addField(), copy(), field(), isEqual(), keyFieldOfType(), replaceField(), and ~CostDBEntryKey().
type_
const EntryKeyProperty* CostDBEntryKey::type_ private
Type of the entry key.
Definition at line 73 of file CostDBEntryKey.hh.
Referenced by copy(), and keyFieldOfType().
The documentation for this class was generated from the following files:
CostDBEntryKey.hh
CostDBEntryKey.cc