OpenASIP: KeyboardShortcutDialog Class Reference
KeyboardShortcutDialog Class Reference
#include <KeyboardShortcutDialog.hh>
Public Member Functions
KeyboardShortcutDialog (wxWindow *parent, KeyboardShortcut *shortcut)
virtual ~KeyboardShortcutDialog ()
Private Types
enum { ID_SHORTCUT = 10000 }
enumerated IDs for dialog widgets
Private Member Functions
virtual bool TransferDataToWindow ()
wxSizer * createContents (wxWindow *parent, bool callFit, bool set_sizer)
void onCharEvent (wxKeyEvent &event)
Private Attributes
KeyboardShortcut * shortcut_
modified shortcut
wxStaticText * shortcutField_
shortcut text field widget
Detailed Description
Dialog for defining keyboard shortcuts.
Definition at line 44 of file KeyboardShortcutDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for dialog widgets
Enumerator
ID_SHORTCUT
Definition at line 60 of file KeyboardShortcutDialog.hh.
         {
        ID_SHORTCUT = 10000
    };
Constructor & Destructor Documentation
KeyboardShortcutDialog()
KeyboardShortcutDialog::KeyboardShortcutDialog (wxWindow * parent, KeyboardShortcut * shortcut)
The constructor.
Parameters
parent Parent window of the dialog.
shortcut Shortcut to modify.
Definition at line 56 of file KeyboardShortcutDialog.cc.
                                                 :
    wxDialog(parent, -1, _T("Edit keyboard shortcut"), wxDefaultPosition),
    shortcut_(shortcut) {
    assert(shortcut != NULL);
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    wxPanel* panel = new wxPanel(this, -1);
    createContents(panel, true, true);
    sizer->Add(panel);
    SetSizer(sizer);
    sizer->Fit(this);
    FindWindow(wxID_OK)->Enable(false);
    panel->SetFocus();
}
References assert.
~KeyboardShortcutDialog()
KeyboardShortcutDialog::~KeyboardShortcutDialog () virtual
The Destructor.
Definition at line 77 of file KeyboardShortcutDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * KeyboardShortcutDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
This function was initially generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 178 of file KeyboardShortcutDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxStaticText *item1 = new wxStaticText( parent, -1,
        wxT("Redefine the shortcut by pressing\n"
        "keys for the new key combination."),
        wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 10 );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Shortcut:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxHORIZONTAL );
    shortcutField_ =
     new wxStaticText(parent, ID_SHORTCUT, wxT(""), wxDefaultPosition,
              wxDefaultSize, 0);
    item2->Add(shortcutField_, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item5 =
    new wxStaticLine(parent, -1, wxDefaultPosition, wxSize(20,-1),
             wxLI_HORIZONTAL );
    item0->Add( item5, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item7 =
    new wxButton(parent, wxID_OK, wxT("OK"), wxDefaultPosition,
             wxDefaultSize, 0);
    item6->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item8 =
    new wxButton(parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition,
             wxDefaultSize, 0);
    item6->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer) {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
    {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    return item0;
}
References ID_SHORTCUT, shortcutField_, and TRUE.
onCharEvent()
void KeyboardShortcutDialog::onCharEvent (wxKeyEvent & event) private
Sets a new shortcut for the command.
Parameters
event Keyevent of the new shortcut.
Definition at line 126 of file KeyboardShortcutDialog.cc.
{
    int keycode = event.GetKeyCode();
    PRINT_VAR(keycode);
    // check that key code is valid
    if (!((keycode >= int('0') && keycode <= int('9')) ||
          (keycode >= int('A') && keycode <= int('Z')) ||
          (keycode == 127) ||
          (keycode >= WXK_F1 && keycode <= WXK_F12))) {
        return;
    }
    // Check that character key shortcut has at least control
    // or alt modifier.
    if (keycode < 256 &&
        !(event.AltDown() || event.ControlDown())) {
        return;
    }
    shortcut_->setAlt(event.AltDown());
    shortcut_->setCtrl(event.ControlDown());
    if (keycode < 256) {
        // character key shortcut
        shortcut_->setFKey(0);
        shortcut_->setKey(keycode);
    } else if(keycode >= WXK_F1 && keycode <= WXK_F12) {
        // function key shortcut
        shortcut_->setKey(0);
        shortcut_->setFKey(keycode - WXK_F1 + 1);
    } else {
        // invalid shortcut
        assert(false);
    }
    FindWindow(wxID_OK)->Enable(true);
    TransferDataToWindow();
}
References assert, PRINT_VAR, KeyboardShortcut::setAlt(), KeyboardShortcut::setCtrl(), KeyboardShortcut::setFKey(), KeyboardShortcut::setKey(), shortcut_, and TransferDataToWindow().
TransferDataToWindow()
bool KeyboardShortcutDialog::TransferDataToWindow () private virtual
Transfers data from dialog attributes to dialog widgets.
Returns
True, if the data was succesfully transfered, false othwerwise.
Definition at line 87 of file KeyboardShortcutDialog.cc.
{
    string keyName = "";
    // set the name of the key
    if (shortcut_->key() > 32 && shortcut_->key() < 127) {
        // character key
        keyName = Conversion::toString(shortcut_->key());
    } else if (shortcut_->key() == 127) {
        // delete key
        keyName = "DEL";
    } else if (shortcut_->fKey() != 0) {
        // function key
        keyName = "F"+Conversion::toString(shortcut_->fKey());
    }
    wxString key = WxConversion::toWxString(keyName);
    // prepend key modifiers
    if (shortcut_->alt()) {
        key.Prepend(_T("ALT - "));
    }
    if (shortcut_->ctrl()) {
        key.Prepend(_T("CTRL - "));
    }
    shortcutField_->SetLabel(key);
    return true;
}
References KeyboardShortcut::alt(), KeyboardShortcut::ctrl(), KeyboardShortcut::fKey(), KeyboardShortcut::key(), shortcut_, shortcutField_, Conversion::toString(), and WxConversion::toWxString().
Referenced by onCharEvent().
Member Data Documentation
shortcut_
KeyboardShortcut* KeyboardShortcutDialog::shortcut_ private
modified shortcut
Definition at line 55 of file KeyboardShortcutDialog.hh.
Referenced by onCharEvent(), and TransferDataToWindow().
shortcutField_
wxStaticText* KeyboardShortcutDialog::shortcutField_ private
shortcut text field widget
Definition at line 57 of file KeyboardShortcutDialog.hh.
Referenced by createContents(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
KeyboardShortcutDialog.hh
KeyboardShortcutDialog.cc