OpenASIP: FitWindowCmd Class Reference
FitWindowCmd Class Reference
#include <FitWindowCmd.hh>
Public Member Functions
FitWindowCmd ()
virtual ~FitWindowCmd ()
virtual bool Do ()
virtual int id () const
virtual FitWindowCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for zooming the canvas to fit the window.
Definition at line 40 of file FitWindowCmd.hh.
Constructor & Destructor Documentation
FitWindowCmd()
FitWindowCmd::FitWindowCmd ()
The Constructor.
Definition at line 46 of file FitWindowCmd.cc.
                          :
    EditorCommand(ProDeConstants::CMD_NAME_ZOOM_FIT_WIN) {
}
Referenced by create().
~FitWindowCmd()
FitWindowCmd::~FitWindowCmd () virtual
The Destructor.
Definition at line 55 of file FitWindowCmd.cc.
{
}
Member Function Documentation
create()
FitWindowCmd * FitWindowCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 104 of file FitWindowCmd.cc.
{
    return new FitWindowCmd();
}
References FitWindowCmd().
Do()
bool FitWindowCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file FitWindowCmd.cc.
                 {
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    wxSize figureSize = canvas->getFigureSize();
    wxSize cSize = canvas->GetSize();
    // decrease zoom factor from maximum until the figure fits in the window
    double factor = CanvasConstants::MAX_ZOOM_FACTOR;
    while (cSize.GetWidth() < factor*figureSize.GetWidth() ||
        cSize.GetHeight() < factor*figureSize.GetHeight()) {
        factor = factor - CanvasConstants::AUTOZOOM_STEP;
    }
    canvas->setZoomFactor(factor);
    return true;
}
References CanvasConstants::AUTOZOOM_STEP, MDFView::canvas(), MachineCanvas::getFigureSize(), CanvasConstants::MAX_ZOOM_FACTOR, MachineCanvas::setZoomFactor(), and EditorCommand::view().
icon()
string FitWindowCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 115 of file FitWindowCmd.cc.
{
    return ProDeConstants::CMD_ICON_ZOOM_FIT_WIN;
}
References ProDeConstants::CMD_ICON_ZOOM_FIT_WIN.
id()
int FitWindowCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 93 of file FitWindowCmd.cc.
                       {
    return ProDeConstants::COMMAND_ZOOM_FIT_WIN;
}
References ProDeConstants::COMMAND_ZOOM_FIT_WIN.
isEnabled()
bool FitWindowCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 140 of file FitWindowCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string FitWindowCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 127 of file FitWindowCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ZOOM_FIT_WIN;
}
References ProDeConstants::CMD_SNAME_ZOOM_FIT_WIN.
The documentation for this class was generated from the following files:
FitWindowCmd.hh
FitWindowCmd.cc