OpenASIP: ProximFindCmd Class Reference
ProximFindCmd Class Reference
#include <ProximFindCmd.hh>
Public Member Functions
ProximFindCmd ()
virtual ~ProximFindCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximFindCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for displaying Proxim disassembly search window.
Definition at line 42 of file ProximFindCmd.hh.
Constructor & Destructor Documentation
ProximFindCmd()
ProximFindCmd::ProximFindCmd ()
Definition at line 42 of file ProximFindCmd.cc.
                            :
    GUICommand(ProximConstants::COMMAND_NAME_FIND, NULL) {
}
Referenced by create().
~ProximFindCmd()
ProximFindCmd::~ProximFindCmd () virtual
Definition at line 47 of file ProximFindCmd.cc.
{
}
Member Function Documentation
create()
ProximFindCmd * ProximFindCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 113 of file ProximFindCmd.cc.
{
    return new ProximFindCmd();
}
References ProximFindCmd().
Do()
bool ProximFindCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 55 of file ProximFindCmd.cc.
                  {
    SimulatorFrontend* simulation = ProximToolbox::frontend();
    if (simulation->isSimulationInitialized() ||
        simulation->isSimulationRunning() ||
        simulation->isSimulationStopped()) {
        FindWindow* findWindow = dynamic_cast<FindWindow*>(
            ProximToolbox::mainFrame()->
            FindWindowById(ProximConstants::ID_FIND_WINDOW));
        if (findWindow == NULL) {
            findWindow = new FindWindow(ProximToolbox::mainFrame(),
                ProximConstants::ID_FIND_WINDOW);
            ProximToolbox::addFramedWindow(
                findWindow, _T("Find pattern in disassembly"), false,
                    wxSize(300, 160));
                findWindow->GetParent()->Center();
            findWindow->GetParent()->SetSize(300, 160);
        }
    } else {
        ErrorDialog error(parentWindow(), _T("Simulation not initialized."));
        error.ShowModal();
    }
    return true;
}
References ProximToolbox::addFramedWindow(), ProximToolbox::frontend(), ProximConstants::ID_FIND_WINDOW, SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationRunning(), SimulatorFrontend::isSimulationStopped(), ProximToolbox::mainFrame(), and GUICommand::parentWindow().
icon()
std::string ProximFindCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 93 of file ProximFindCmd.cc.
{
    return "find.png";
}
id()
int ProximFindCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 102 of file ProximFindCmd.cc.
{
    return ProximConstants::COMMAND_FIND;
}
References ProximConstants::COMMAND_FIND.
isEnabled()
bool ProximFindCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 124 of file ProximFindCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximFindCmd.hh
ProximFindCmd.cc