OpenASIP: HDLGenerator::Assign Class Reference
HDLGenerator::Assign Class Reference
#include <HDLGenerator.hh>
Public Member Functions
Assign (std::string var, LHSValue value)
Assign (std::string var, LHSValue value, int idx)
Assign (std::string var, LHSValue value, int ub, int lb)
void build () override
void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
int index_
int upperBound_
int lowerBound_
LHSValue value_
Detailed Description
Assignment.
Definition at line 540 of file HDLGenerator.hh.
Constructor & Destructor Documentation
Assign() [1/3]
HDLGenerator::Assign::Assign (std::string var, LHSValue value) inline
Definition at line 542 of file HDLGenerator.hh.
            : SequentialStatement(var), index_(-1), upperBound_(-1),
              lowerBound_(-1), value_(value) {}
Assign() [2/3]
HDLGenerator::Assign::Assign (std::string var, LHSValue value, int idx) inline
Definition at line 545 of file HDLGenerator.hh.
            : SequentialStatement(var), index_(idx), upperBound_(-1),
              lowerBound_(-1), value_(value) {}
Assign() [3/3]
HDLGenerator::Assign::Assign (std::string var, LHSValue value, int ub, int lb) inline
Definition at line 548 of file HDLGenerator.hh.
            : SequentialStatement(var), index_(-1), upperBound_(ub),
              lowerBound_(lb), value_(value) {}
Member Function Documentation
build()
void HDLGenerator::Assign::build () inline override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 552 of file HDLGenerator.hh.
{
            Generatable::build();
            writes(name());
            reads(value_);
        }
References HDLGenerator::Generatable::build(), HDLGenerator::Generatable::name(), HDLGenerator::Generatable::reads(), value_, and HDLGenerator::Generatable::writes().
hdl()
void HDLGenerator::Assign::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 558 of file HDLGenerator.hh.
{
            if (isRegister(name()) && !parentIs<Synchronous>()) {
                throw std::runtime_error(
                    "assigning to register '" + name() +
                    "' is only allowed in synchronous context");
            } else if (isVariable(name()) && (!parentIs<Synchronous>() ||
                                                 !parentIs<Asynchronous>())) {
                throw std::runtime_error("Not allowed to assign to '" +
                                         name() + "' in this context.");
            }
            if (lang == Language::VHDL) {
                stream << StringTools::indent(level) << name();
                if (upperBound_ >= 0) {
                    stream << "(" << upperBound_ << " downto "
                                  << lowerBound_ << ")";
                } else if (index_ >= 0) {
                    stream << "(" << index_ << ")";
                }
                if (isVariable(name())) {
                    stream << " := ";
                } else {
                    stream << " <= ";
                }
            } else if (lang == Language::Verilog) {
                if (!(parentIs<Synchronous>() || parentIs<Asynchronous>())) {
                    stream << StringTools::indent(level) << "always @*\n"
                           << StringTools::indent(level + 1) << name();
                } else {
                    stream << StringTools::indent(level) << name();
                }
                if (upperBound_ >= 0) {
                    stream << "[" << upperBound_ << ":" << lowerBound_ << "]";
                } else if (index_ >= 0) {
                    stream << "[" << index_ << "]";
                }
                if (isRegister(name())) {
                    stream << " <= ";
                } else {
                    stream << " = ";
                }
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
            value_.hdl(stream, lang);
            stream << ";\n";
        }
References HDLGenerator::LHSValue::hdl(), StringTools::indent(), index_, HDLGenerator::Generatable::isRegister(), HDLGenerator::Generatable::isVariable(), lowerBound_, HDLGenerator::Generatable::name(), upperBound_, value_, HDLGenerator::Verilog, and HDLGenerator::VHDL.
Member Data Documentation
index_
int HDLGenerator::Assign::index_ private
Definition at line 606 of file HDLGenerator.hh.
Referenced by hdl().
lowerBound_
int HDLGenerator::Assign::lowerBound_ private
Definition at line 608 of file HDLGenerator.hh.
Referenced by hdl().
upperBound_
int HDLGenerator::Assign::upperBound_ private
Definition at line 607 of file HDLGenerator.hh.
Referenced by hdl().
value_
LHSValue HDLGenerator::Assign::value_ private
Definition at line 609 of file HDLGenerator.hh.
Referenced by build(), and hdl().
The documentation for this class was generated from the following file:
HDLGenerator.hh