OpenASIP: RegisterFileState Class Reference
RegisterFileState Class Reference
#include <RegisterFileState.hh>
Public Member Functions
RegisterFileState (int size, int width, bool zeroRegister=false)
virtual ~RegisterFileState ()
virtual RegisterState & registerState (int index)
virtual std::size_t registerCount () const
Private Member Functions
RegisterFileState (const RegisterFileState &)
Copying not allowed.
RegisterFileState & operator= (const RegisterFileState)
Assignment not allowed.
Private Attributes
std::vector< RegisterState * > registerStates_
Contains all the registers of the state.
bool zeroRegister_
Detailed Description
Class that manages RegisterState objects.
Definition at line 49 of file RegisterFileState.hh.
Constructor & Destructor Documentation
RegisterFileState() [1/2]
RegisterFileState::RegisterFileState (int size, int width, bool zeroRegister = false) explicit
Constructor.
Parameters
size The size of the RegisterFileState.
width Width of the registers.
zeroRegister Tells whether the first index is hardcoded to zero
Definition at line 54 of file RegisterFileState.cc.
                                                                           :
    zeroRegister_(zeroRegister) {
    if (zeroRegister_) {
        registerStates_.push_back(new RegisterState(width, true));
    } else {
        registerStates_.push_back(new RegisterState(width, false));
    }
    for (int i = 1; i < size; i++) {
        registerStates_.push_back(new RegisterState(width, false));
    }
}
References registerStates_, and zeroRegister_.
~RegisterFileState()
RegisterFileState::~RegisterFileState () virtual
Destructor.
Definition at line 69 of file RegisterFileState.cc.
{
    SequenceTools::deleteAllItems(registerStates_);
}
References SequenceTools::deleteAllItems(), and registerStates_.
RegisterFileState() [2/2]
RegisterFileState::RegisterFileState (const RegisterFileState &) private
Copying not allowed.
Member Function Documentation
operator=()
RegisterFileState & RegisterFileState::operator= (const RegisterFileState) private
Assignment not allowed.
registerCount()
std::size_t RegisterFileState::registerCount () const virtual
Returns the count of registers in the register file.
Returns
Count of registers.
Definition at line 95 of file RegisterFileState.cc.
{
    return registerStates_.size();
}
References registerStates_.
Referenced by ProximRFDetailsCmd::Do(), and ProximRegisterWindow::loadRegisterFile().
registerState()
RegisterState & RegisterFileState::registerState (int index) virtual
Returns RegisterState with a given index.
Parameters
index Index of the wanted RegisterState.
Returns
RegisterState with a given index.
Exceptions
OutOfRange If index is out of range.
Reimplemented in NullRegisterFileState.
Definition at line 81 of file RegisterFileState.cc.
{
    if (index < 0 || index > static_cast<int>(registerStates_.size()) - 1) {
        string msg = "Register index out of range";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    return *registerStates_[index];
}
References __func__, and registerStates_.
Referenced by MachineStateBuilder::buildMachineState(), RFTestbenchGenerator::createStimulus(), ProximRFDetailsCmd::Do(), SimulatorFrontend::findBooleanRegister(), SimulatorFrontend::findRegister(), ProximRegisterWindow::loadRegisterFile(), and SimProgramBuilder::processBidirTerminal().
Member Data Documentation
registerStates_
std::vector<RegisterState*> RegisterFileState::registerStates_ private
Contains all the registers of the state.
Definition at line 66 of file RegisterFileState.hh.
Referenced by registerCount(), RegisterFileState(), registerState(), and ~RegisterFileState().
zeroRegister_
bool RegisterFileState::zeroRegister_ private
Definition at line 68 of file RegisterFileState.hh.
Referenced by RegisterFileState().
The documentation for this class was generated from the following files:
RegisterFileState.hh
RegisterFileState.cc