OpenASIP: QuitCommand Class Reference
QuitCommand Class Reference
#include <QuitCommand.hh>
Public Member Functions
QuitCommand (const std::string &commandString="quit")
virtual ~QuitCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Implementation of the "quit" command of the Simulator Control Language.
Definition at line 46 of file QuitCommand.hh.
Constructor & Destructor Documentation
QuitCommand()
QuitCommand::QuitCommand (const std::string & commandString = "quit")
Constructor.
Sets the name of the command to the base class.
Definition at line 48 of file QuitCommand.cc.
                                                       :
    CustomCommand(commandString) {
}
~QuitCommand()
QuitCommand::~QuitCommand () virtual
Destructor.
Does nothing.
Definition at line 57 of file QuitCommand.cc.
{
}
Member Function Documentation
execute()
bool QuitCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "quit" command.
This method does the uninitialization of the simulator.
Parameters
arguments No arguments needed.
Returns
Always true.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 71 of file QuitCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 0, 0)) {
        return false;
    }
    dynamic_cast<SimulatorInterpreter*>(interpreter())->setQuitCommandGiven();
    return true;
}
References CustomCommand::checkArgumentCount(), and CustomCommand::interpreter().
helpText()
std::string QuitCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 89 of file QuitCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_QUIT).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_QUIT.
The documentation for this class was generated from the following files:
QuitCommand.hh
QuitCommand.cc