OpenASIP: DDGPass Class Reference
DDGPass Class Reference
#include <DDGPass.hh>
Public Member Functions
DDGPass (InterPassData &data)
virtual ~DDGPass ()
virtual int handleDDG (DataDependenceGraph &ddg, SimpleResourceManager &rm, const TTAMachine::Machine &targetMachine, int minCycle=0, bool testOnly=false)
virtual int handleLoopDDG (DataDependenceGraph &, SimpleResourceManager &, const TTAMachine::Machine &, int tripCount, SimpleResourceManager *prologRM=NULL, bool testOnly=false)
Public Member Functions inherited from SchedulerPass
SchedulerPass (InterPassData &data)
virtual ~SchedulerPass ()
InterPassData & interPassData ()
virtual std::string shortDescription () const =0
virtual std::string longDescription () const
Detailed Description
Definition at line 51 of file DDGPass.hh.
Constructor & Destructor Documentation
DDGPass()
DDGPass::DDGPass (InterPassData & data)
Constructor.
Definition at line 42 of file DDGPass.cc.
                                    :
    SchedulerPass(data) {
}
~DDGPass()
DDGPass::~DDGPass () virtual
Destructor.
Definition at line 49 of file DDGPass.cc.
                  {
}
Member Function Documentation
handleDDG()
int DDGPass::handleDDG (DataDependenceGraph & ddg, SimpleResourceManager & rm, const TTAMachine::Machine & targetMachine, int minCycle = 0, bool testOnly = false) virtual
Handles a given DDG.
Parameters
ddg DDG to handle
rm Resource manager that is to be used.
machine The target machine if any. (NullMachine::instance() if target machine is irrelevant).
Exceptions
In case handling is unsuccesful for any reason (basicBlock might still get modified).
Reimplemented in BF2Scheduler, BUBasicBlockScheduler, and BasicBlockScheduler.
Definition at line 63 of file DDGPass.cc.
{
    // just to avoid warnings -- need to keep the argument names for
    // Doxygen comments ;)
    ddg.nodeCount();
    rm.largestCycle();
    targetMachine.machineTester();
    abortWithError("Should never call this.");
    minCycle++;
    return INT_MAX;
}
References abortWithError, SimpleResourceManager::largestCycle(), TTAMachine::Machine::machineTester(), and BoostGraph< GraphNode, GraphEdge >::nodeCount().
handleLoopDDG()
int DDGPass::handleLoopDDG (DataDependenceGraph & , SimpleResourceManager & , const TTAMachine::Machine & , int tripCount, SimpleResourceManager * prologRM = NULL, bool testOnly = false) virtual
For BasicBlockPass to be able to call this method...
Reimplemented in BF2Scheduler, BasicBlockScheduler, and BUBasicBlockScheduler.
Definition at line 77 of file DDGPass.cc.
{
    return -1;
}
The documentation for this class was generated from the following files:
DDGPass.hh
DDGPass.cc