OpenASIP: BlockImplementationDialog Class Reference
BlockImplementationDialog Class Reference
#include <BlockImplementationDialog.hh>
Public Member Functions
BlockImplementationDialog (wxWindow *parent, const TTAMachine::Component &block, IDF::UnitImplementationLocation &impl)
virtual ~BlockImplementationDialog ()
Private Types
enum { ID_HDB_CHOICE , ID_BROWSE , ID_LIST , ID_LINE }
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onBrowse (wxCommandEvent &event)
void onImplSelection (wxListEvent &event)
void onImplActivation (wxListEvent &e)
void doOK ()
void onOK (wxCommandEvent &event)
void onHDBSelection (wxCommandEvent &event)
Private Attributes
const TTAMachine::Component & block_
IDF::UnitImplementationLocation & impl_
wxListCtrl * list_
wxChoice * hdbChoice_
Static Private Attributes
static std::set< std::string > hdbs_
Static set for hdb paths.
static int selection_ = 0
Static variable for the hdb choicer selection.
static const std::string defaultHDB_
Detailed Description
Definition at line 49 of file BlockImplementationDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_HDB_CHOICE
ID_BROWSE
ID_LIST
ID_LINE
Definition at line 80 of file BlockImplementationDialog.hh.
         {
        ID_HDB_CHOICE,
        ID_BROWSE,
        ID_LIST,
        ID_LINE
    };
Constructor & Destructor Documentation
BlockImplementationDialog()
BlockImplementationDialog::BlockImplementationDialog (wxWindow * parent, const TTAMachine::Component & block, IDF::UnitImplementationLocation & impl)
The Constructor.
Parameters
parent Parent window of the dialog.
block Block to select the implementation for.
impl IDF UnitImplementationLocation object for the block.
Definition at line 86 of file BlockImplementationDialog.cc.
                                      :
    wxDialog(parent, -1, _T("Select implementation from a HDB file"),
        wxDefaultPosition, wxDefaultSize,
        wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    block_(block), impl_(impl) {
    createContents(this, true, true);
    SetSize(wxSize(580, 300));
    list_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    hdbChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_HDB_CHOICE));
    list_->InsertColumn(0, _T("module name"), wxLIST_FORMAT_LEFT, 150);
    list_->InsertColumn(1, _T("id"), wxLIST_FORMAT_LEFT, 50);
    list_->InsertColumn(2, _T("param size"), wxLIST_FORMAT_LEFT, 100);
    list_->InsertColumn(3, _T("param width"), wxLIST_FORMAT_LEFT, 100);
    if (dynamic_cast<const RegisterFile*>(&block) != 0) {
        list_->InsertColumn(4, _T("guard latency"), wxLIST_FORMAT_LEFT, 170);
    }
    HDBRegistry& registry = HDBRegistry::instance();
    registry.loadFromSearchPaths();
    for (int i = 0; i < registry.hdbCount(); i++) {
        hdbs_.insert(registry.hdbPath(i));
    }
    if (!hdbs_.empty()) {
        std::set<std::string>::iterator iter = hdbs_.begin();
        bool defaultHDBFound = false;
        for (; iter != hdbs_.end(); iter++) {
            std::string shortPath = Environment::shortHDBPath(*iter);
            hdbChoice_->Append(WxConversion::toWxString(shortPath));
            if (!defaultHDBFound && StringTools::endsWith(*iter, defaultHDB_)) {
                selection_ = hdbChoice_->GetCount() - 1;
                defaultHDBFound = true;
            }
        }
        hdbChoice_->SetSelection(selection_);
        wxCommandEvent dummy;
        onHDBSelection(dummy);
    }
    FindWindow(wxID_OK)->Disable();
}
References dummy, StringTools::endsWith(), HDB::HDBRegistry::hdbCount(), HDB::HDBRegistry::hdbPath(), HDB::HDBRegistry::instance(), HDB::HDBRegistry::loadFromSearchPaths(), Environment::shortHDBPath(), and WxConversion::toWxString().
~BlockImplementationDialog()
BlockImplementationDialog::~BlockImplementationDialog () virtual
The Destructor.
Definition at line 135 of file BlockImplementationDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * BlockImplementationDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 369 of file BlockImplementationDialog.cc.
                    {
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 1 );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxString *strs2 = (wxString*) NULL;
    wxChoice *item2 = new wxChoice( parent, ID_HDB_CHOICE, wxDefaultPosition, wxSize(250,-1), 0, strs2, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item3 = new wxButton( parent, ID_BROWSE, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxListCtrl *item4 = new wxListCtrl( parent, ID_LIST, wxDefaultPosition, wxSize(300,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item0->Add( item4, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item5 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item5, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item7 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item8 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BROWSE, ID_HDB_CHOICE, ID_LINE, and ID_LIST.
doOK()
void BlockImplementationDialog::doOK () private
Do the things that are done to close the dialog on ok
Definition at line 335 of file BlockImplementationDialog.cc.
{
    std::string HDBpath = WxConversion::toString(
                              hdbChoice_->GetStringSelection());
    HDBpath = Environment::longHDBPath(HDBpath);
    impl_.setHDBFile(HDBpath);
    int id = Conversion::toInt(WidgetTools::lcStringSelection(list_, 1));
    impl_.setID(id);
    EndModal(wxID_OK);
}
References hdbChoice_, impl_, WidgetTools::lcStringSelection(), list_, Environment::longHDBPath(), IDF::UnitImplementationLocation::setHDBFile(), IDF::UnitImplementationLocation::setID(), Conversion::toInt(), and WxConversion::toString().
Referenced by onImplActivation(), and onOK().
onBrowse()
void BlockImplementationDialog::onBrowse (wxCommandEvent & event) private
Event handler for the 'Browse...' button.
Opens a file dialog.
Definition at line 144 of file BlockImplementationDialog.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a HDB file containing the implementation"),
        _T(""), _T(""), _T("HDBs|*.hdb|All files|*.*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    if (dialog.ShowModal() == wxID_OK) {
        std::string hdb = std::string(dialog.GetPath().mb_str());
        hdb = Environment::shortHDBPath(hdb);
        auto wxHDB = WxConversion::toWxString(hdb);
        int item = hdbChoice_->FindString(wxHDB);
        if (item == wxNOT_FOUND) {
            item = hdbChoice_->Append(wxHDB);
        }
        hdbChoice_->Select(item);
        wxListEvent dummy;
        onHDBSelection(dummy);
    }
}
References dummy, hdbChoice_, onHDBSelection(), Environment::shortHDBPath(), and WxConversion::toWxString().
onHDBSelection()
void BlockImplementationDialog::onHDBSelection (wxCommandEvent & event) private
Event handler for the HDB choicer widget.
Definition at line 177 of file BlockImplementationDialog.cc.
{
    std::string path = WxConversion::toString(
        hdbChoice_->GetStringSelection());
    path = Environment::longHDBPath(path);
    list_->DeleteAllItems();
    try {
        HDBManager& hdb = HDBRegistry::instance().hdb(path);
        const FunctionUnit* fu = dynamic_cast<const FunctionUnit*>(&block_);
        if (fu != NULL) {
            int i = 0;
            std::set<RowID> fuEntryIDs = hdb.fuEntriesByArchitecture(*fu);
            if (fuEntryIDs.empty()) {
                wxString message = _T("No implementations for '");
                message.Append(WxConversion::toWxString(fu->name()));
                message.Append(_T("' found in '"));
                message.Append(hdbChoice_->GetStringSelection());
                message.Append(_T("'."));
                InformationDialog dialog(this, message);
                dialog.ShowModal();
            }
            std::set<RowID>::iterator iter = fuEntryIDs.begin();
            for (; iter != fuEntryIDs.end(); iter++) {
                if (hdb.fuByEntryID(*iter)->hasImplementation()) {
                    const FUImplementation& impl =
                         hdb.fuByEntryID(*iter)->implementation();
                    const FUArchitecture& arch =
                         hdb.fuByEntryID(*iter)->architecture();
                    list_->InsertItem(
                        i, WxConversion::toWxString(impl.moduleName()));
                    // we want to select the FU *entry ID* which points to the
                    // implementation
                    list_->SetItem(i, 1, WxConversion::toWxString(*iter));
                    if (arch.hasParameterizedWidth("p1")) {
                        list_->SetItem(i, 3, WxConversion::toWxString("*"));
                    }
                }
            }
        }
        // Register files.
        const BaseRegisterFile* rf =
            dynamic_cast<const BaseRegisterFile*>(&block_);
        if (rf != NULL) {
            int width = rf->width();
            int size = rf->size();
            int i = 0;
            int readPorts = 0;
            int writePorts = 0;
            int bidirPorts = 0;
            for (int p = 0; p < rf->portCount(); p++) {
                const RFPort* port = rf->port(p);
                if (port->inputSocket() != NULL &&
                    port->outputSocket() != NULL) {
                    bidirPorts++;
                } else if (port->inputSocket() != NULL) {
                    writePorts++;
                } else if (port->outputSocket() != NULL) {
                    readPorts++;
                }
            }
            int maxReads = 0;
            int maxWrites = 0;
            int guardLatency = 0;
            int latency = 1;
            bool zeroRegister = false;
            const RegisterFile* r = dynamic_cast<const RegisterFile*>(rf);
            if (r != NULL) {
                maxReads = r->maxReads();
                maxWrites = r->maxWrites();
                guardLatency = r->guardLatency();
                zeroRegister = r->zeroRegister();
            }
            const ImmediateUnit* iu = dynamic_cast<const ImmediateUnit*>(rf);
            if (iu != NULL) {
                // TODO: XXX
                latency = iu->latency();
                // Immediate units have always one write port (not seen in adf)
                writePorts = 1;
            }
            std::set<RowID> rfEntryIDs =
                hdb.rfEntriesByArchitecture(
                    readPorts, writePorts, bidirPorts,
                    maxReads,
                    maxWrites,
                    latency,
                    r->isUsedAsGuard(),
                    guardLatency,
                    width,
                    size,
                    zeroRegister);
            if (rfEntryIDs.empty()) {
                wxString message = _T("No implementations for '");
                message.Append(WxConversion::toWxString(rf->name()));
                message.Append(_T("' found in '"));
                message.Append(hdbChoice_->GetStringSelection());
                message.Append(_T("'."));
                InformationDialog dialog(this, message);
                dialog.ShowModal();
            }
            std::set<RowID>::iterator iter = rfEntryIDs.begin();
            for (; iter != rfEntryIDs.end(); iter++) {
                if (hdb.rfByEntryID(*iter)->hasImplementation()) {
                    const RFImplementation& impl =
                         hdb.rfByEntryID(*iter)->implementation();
                    const RFArchitecture& arch =
                         hdb.rfByEntryID(*iter)->architecture();
                    list_->InsertItem(
                        i, WxConversion::toWxString(impl.moduleName()));
                    // we want to select the RF *entry ID* which points to the
                    // implementation
                    list_->SetItem(i, 1, WxConversion::toWxString(*iter));
                    if (arch.hasParameterizedSize()) {
                        list_->SetItem(i, 2, WxConversion::toWxString("*"));
                    }
                    if (arch.hasParameterizedWidth()) {
                        list_->SetItem(i, 3, WxConversion::toWxString("*"));
                    }
                    list_->SetItem(i, 4, r->isUsedAsGuard() ?
                        WxConversion::toWxString(guardLatency) :
                        WxConversion::toWxString("not used as guard"));
                }
            }
        }
    } catch (Exception& e) {
        wxString message = _T("Error opening '");
        message.Append(WxConversion::toWxString(path));
        message.Append(_T("':\n\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        hdbChoice_->Delete(hdbChoice_->GetSelection());
        return;
    }
    hdbs_.insert(path);
    selection_ = hdbChoice_->GetSelection();
}
References HDB::FUEntry::architecture(), HDB::RFEntry::architecture(), block_, Exception::errorMessage(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuEntriesByArchitecture(), TTAMachine::RegisterFile::guardLatency(), HDB::FUEntry::hasImplementation(), HDB::RFEntry::hasImplementation(), HDB::RFArchitecture::hasParameterizedSize(), HDB::RFArchitecture::hasParameterizedWidth(), HDB::FUArchitecture::hasParameterizedWidth(), HDB::HDBRegistry::hdb(), hdbChoice_, hdbs_, HDB::FUEntry::implementation(), HDB::RFEntry::implementation(), TTAMachine::Port::inputSocket(), HDB::HDBRegistry::instance(), TTAMachine::RegisterFile::isUsedAsGuard(), TTAMachine::ImmediateUnit::latency(), list_, Environment::longHDBPath(), TTAMachine::RegisterFile::maxReads(), TTAMachine::RegisterFile::maxWrites(), HDB::HWBlockImplementation::moduleName(), TTAMachine::Component::name(), TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfEntriesByArchitecture(), selection_, TTAMachine::BaseRegisterFile::size(), WxConversion::toString(), WxConversion::toWxString(), TTAMachine::BaseRegisterFile::width(), and TTAMachine::RegisterFile::zeroRegister().
Referenced by onBrowse().
onImplActivation()
void BlockImplementationDialog::onImplActivation (wxListEvent & e) private
Event handler for list activation OK button.
Updates the UnitImplementationLocation object.
Definition at line 361 of file BlockImplementationDialog.cc.
{
    doOK();
}
References doOK().
onImplSelection()
void BlockImplementationDialog::onImplSelection (wxListEvent & event) private
Definition at line 165 of file BlockImplementationDialog.cc.
{
    if (list_->GetSelectedItemCount() == 1) {
        FindWindow(wxID_OK)->Enable();
    } else {
        FindWindow(wxID_OK)->Disable();
    }
}
References list_.
onOK()
void BlockImplementationDialog::onOK (wxCommandEvent & event) private
Event handler for the OK button.
Updates the UnitImplementationLocation object.
Definition at line 351 of file BlockImplementationDialog.cc.
{
    doOK();
}
References doOK().
Member Data Documentation
block_
const TTAMachine::Component& BlockImplementationDialog::block_ private
Definition at line 67 of file BlockImplementationDialog.hh.
Referenced by onHDBSelection().
defaultHDB_
const std::string BlockImplementationDialog::defaultHDB_ static private
Definition at line 78 of file BlockImplementationDialog.hh.
hdbChoice_
wxChoice* BlockImplementationDialog::hdbChoice_ private
Definition at line 70 of file BlockImplementationDialog.hh.
Referenced by doOK(), onBrowse(), and onHDBSelection().
hdbs_
std::set< std::string > BlockImplementationDialog::hdbs_ static private
Static set for hdb paths.
Definition at line 73 of file BlockImplementationDialog.hh.
Referenced by onHDBSelection().
impl_
IDF::UnitImplementationLocation& BlockImplementationDialog::impl_ private
Definition at line 68 of file BlockImplementationDialog.hh.
Referenced by doOK().
list_
wxListCtrl* BlockImplementationDialog::list_ private
Definition at line 69 of file BlockImplementationDialog.hh.
Referenced by doOK(), onHDBSelection(), and onImplSelection().
selection_
int BlockImplementationDialog::selection_ = 0 static private
Static variable for the hdb choicer selection.
Definition at line 75 of file BlockImplementationDialog.hh.
Referenced by onHDBSelection().
The documentation for this class was generated from the following files:
BlockImplementationDialog.hh
BlockImplementationDialog.cc