OpenASIP: StringTools Class Reference
StringTools Class Reference
#include <StringTools.hh>
Static Public Member Functions
static std::string trim (const std::string &source)
static char * stringToCharPtr (const std::string &source)
static bool containsChar (const std::string &source, char ch, bool caseSensitive=true)
static bool endsWith (const std::string &source, const std::string &searchString)
static std::string stringToUpper (const std::string &source)
static std::string stringToLower (const std::string &source)
static bool ciEqual (const std::string &a, const std::string &b)
static std::vector< TCEString > chopString (const std::string &source, const std::string &delimiters)
static void chopString (const std::string &source, const std::string &delimiter, std::vector< std::string > &results)
static std::string splitToRows (const std::string &original, const unsigned int rowLength)
static std::string replaceAllOccurrences (const std::string &source, const std::string &occurrence, const std::string &newString)
static std::string indent (int level)
Detailed Description
Definition at line 44 of file StringTools.hh.
Member Function Documentation
chopString() [1/2]
void StringTools::chopString (const std::string & source, const std::string & delimiter, std::vector< std::string > & results) static
Chops string using a given delimiter.
Result is returned as a vector. Extra blanks are ignored.
Parameters
source String to be chopped.
delimiter Delimiter used.
store String vector reference where result strings are stored.
Definition at line 212 of file StringTools.cc.
{
    string line = trim(source);
    while (line.length() > 0) {
        string::size_type location = line.find(delimiter);
        if (location == string::npos) {
            results.push_back(line);
            line = "";
        } else {
            results.push_back(line.substr(0, location));
            line.replace(0, location + 1, "");
            line = trim(line);
        }
    }
}
References trim().
chopString() [2/2]
vector< TCEString > StringTools::chopString (const std::string & source, const std::string & delimiter) static
Chops string using a given delimiter.
Result is returned as a vector. Extra blanks are ignored.
Parameters
source String to be chopped.
delimiter Delimiter used.
Returns
A vector that contains chopped strings.
Definition at line 181 of file StringTools.cc.
{
    string line = trim(source);
    vector<TCEString> results;
    while (line.length() > 0) {
        string::size_type location = line.find(delimiter);
        if (location == string::npos) {
            results.push_back(line);
            line = "";
        } else {
            results.push_back(line.substr(0, location));
            line.replace(0, location + 1, "");
            line = trim(line);
        }
    }
    return results;
}
References trim().
Referenced by UserManualCmd::Do(), VectorLSGenerator::explore(), llvm::LLVMTCERISCVIntrinsicsLowering::findOperationName(), llvm::LLVMTCERISCVIntrinsicsLowering::findRegs(), GenerateProcessor::generateProcessor(), SimpleScriptInterpreter::interpret(), ConfigurationFile::parse(), Environment::parsePathEnvVariable(), and TCEString::split().
ciEqual()
bool StringTools::ciEqual (const std::string & a, const std::string & b) static
Returns true if two strings are equal if the case is not taken into account.
Parameters
a A string.
b Another string.
Returns
True if strings equal case-insensitively.
Definition at line 240 of file StringTools.cc.
{
    return (stringToLower(a) == stringToLower(b));
}
References stringToLower().
Referenced by InfoRegistersCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), SimulatorFrontend::findPort(), findRegisterFile(), SocketCodeTable::fuPortCode(), DCMFUResourceConflictDetector::operationID(), ReservationTableFUResourceConflictDetector::operationID(), and SimulatorFrontend::state().
containsChar()
bool StringTools::containsChar (const std::string & source, char ch, bool caseSensitive = true) static
Checks whether a string contains a char or not.
Parameters
source The investigated string.
ch Character which is checked whether it is in a string or not.
caseSensitive Flag indicating whether checking is case sensitive or not.
Returns
True, if source string contains ch, false otherwise.
Definition at line 101 of file StringTools.cc.
{
    string::size_type pos = 0;
    if (!caseSensitive) {
        char upC = toupper(ch);
        string upString = StringTools::stringToUpper(source);
        pos = upString.find(upC, 0);
    } else {
        pos = source.find(ch, 0);
    }
    return pos != string::npos;
}
References stringToUpper().
Referenced by BaseLineReader::charQuestion(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCERISCVIntrinsicsLowering::findOperationName(), and llvm::LLVMTCERISCVIntrinsicsLowering::findRegs().
endsWith()
bool StringTools::endsWith (const std::string & source, const std::string & searchString) static
Checks whether a string ends with the given search string.
Parameters
source The investigated string.
searchString The string to search from the end.
Returns
True, if source ends with searchString.
Definition at line 126 of file StringTools.cc.
{
    return source.size() >= searchString.size() &&
        source.substr(
            source.size() - searchString.size(), searchString.size()) ==
        searchString;
}
Referenced by AutoSelectImplementationsDialog::AutoSelectImplementationsDialog(), BlockImplementationDialog::BlockImplementationDialog(), PluginTools::findModule(), OperationPropertyDialog::saveOperation(), GenerateProcessor::validIntegratorParameters(), and QuartusProjectGenerator::writeQSFFile().
indent()
std::string StringTools::indent (int level) static
Returns a (vhdl) indention string
Parameters
level Indention level (one level is 2 spaces)
Returns
Indention string
Definition at line 319 of file StringTools.cc.
{
    string indent;
    for (int i = 0; i < level; i++) {
        indent += "  ";
    }
    return indent;
}
References indent().
Referenced by HDLGenerator::Wire::declare(), HDLGenerator::Register::declare(), HDLGenerator::BinaryConstant::declare(), HDLGenerator::IntegerConstant::declare(), HDLGenerator::Variable::declare(), HDLGenerator::Module::declare(), HDLGenerator::Parameter::declare(), HDLGenerator::Port::declare(), VhdlRomGenerator::generateComponentFile(), HDLGenerator::LHSValue::hdl(), HDLGenerator::RawCodeLine::hdl(), HDLGenerator::HDLOperation::hdl(), HDLGenerator::DefaultAssign::hdl(), HDLGenerator::Assign::hdl(), HDLGenerator::DefaultCase::hdl(), HDLGenerator::Case::hdl(), HDLGenerator::Switch::hdl(), HDLGenerator::If::hdl(), HDLGenerator::Asynchronous::hdl(), HDLGenerator::Synchronous::hdl(), HDLGenerator::Module::implement(), indent(), ProGe::VerilogNetlistWriter::indentation(), ProGe::VHDLNetlistWriter::indentation(), HDLGenerator::Module::instantiate(), HDLGenerator::Register::reset(), and HDLGenerator::Synchronous::vhdlReset().
replaceAllOccurrences()
std::string StringTools::replaceAllOccurrences (const std::string & source, const std::string & occurrence, const std::string & newString) static
Replaces all occurrences of 'occurrence' in 'source' with 'newString'
Parameters
source The source string to be modified
occurrence The string occurrences to be replaced
newString The string that's replaced over the found occurrences
Returns
A string containing the modifications
Definition at line 295 of file StringTools.cc.
{
    std::string modifiedString(source);
    std::string::size_type location = modifiedString.find(occurrence);
    while (location != std::string::npos) {
        modifiedString.replace(modifiedString.begin() + location,
                       modifiedString.begin() + location + occurrence.length(),
                       newString.c_str());
        location = modifiedString.find(occurrence);
    }
    return modifiedString;
}
Referenced by llvm::LLVMTCERISCVIntrinsicsLowering::findOperationName(), and ProGeTestBenchGenerator::generate().
splitToRows()
std::string StringTools::splitToRows (const std::string & original, const unsigned int rowLength) static
Splits a string into rows.
The original string is split in to rows containing a maximum of 'rowLength' characters. After 'rowLength' characters a new-line character is inserted to the string to be returned. If the given string has less than 'rowLength' characters, the string is returned as it was. Also, the "last row" may have less than 'rowLength' characters.
If 'rowLength' is 0, the original string is returned.
Parameters
original The string to be split into rows.
rowLength The length of a row in the returned string.
Returns
A string that has been split into rows containing a maximum of 'rowLength' characters.
Definition at line 262 of file StringTools.cc.
{
    if (rowLength == 0) {
        return original;
    } else {
        unsigned int counter = 0;
        string newString = "";
        while (counter < original.size()) {
            newString += original.substr(counter, 1);
            counter++;
            if (counter % rowLength == 0 && counter != original.size()) {
                newString += "\n";
            }
        }
        return newString;
    }
}
stringToCharPtr()
char * StringTools::stringToCharPtr (const std::string & source) static
Converts string to char*.
Parameters
source The string to be converted.
Returns
The string as a char*.
Definition at line 83 of file StringTools.cc.
{
    char* ch = new char[source.size() + 1];
    copy(source.begin(), source.end(), ch);
    ch[source.size()] = 0;
    return ch;
}
Referenced by TclInterpreter::addCustomCommandToInterpreter(), EditLineReader::charQuestion(), TclInterpreter::dataObjectToTclObj(), EditLineReader::initialize(), TclInterpreter::interpret(), EditLineReader::readLine(), TclInterpreter::removeCustomCommandFromInterpreter(), TclInterpreter::setVariableToInterpreter(), and TclInterpreter::variable().
stringToLower()
string StringTools::stringToLower (const std::string & source) static
Converts a string to lower case letters.
Parameters
source String to be converted.
Returns
String as lower case letters.
Definition at line 160 of file StringTools.cc.
{
    string lowString;
    lowString.reserve(source.length());
    for (unsigned int i = 0; i < source.length(); ++i) {
        lowString.push_back(tolower(source[i]));
    }
    return lowString;
}
Referenced by MachineState::addPortState(), StaticProgramAnalyzer::addProgram(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), InputFUBroker::allAvailableResources(), ConfigurationFile::booleanValue(), DesignSpaceExplorerPlugin::booleanValue(), DataObject::boolValue(), FUGen::buildReplaces(), MachineConnectivityCheck::busConnectedToAnyFU(), ProGeTools::canGenerateFromDAG(), Automagic::canGenerateFromDAG(), TCEString::capitalize(), ciEqual(), FUGen::constantName(), FUGen::createOperationResources(), FUGen::DAGNodeOperandWidth(), ProGe::CUOpcodeGenerator::encodings(), InterpolatingFUEstimator::estimateEnergy(), StrictMatchFUEstimator::estimateEnergy(), EnableBPCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), InfoCommand::execute(), SettingCommand::execute(), ProGeTools::findInOptionList(), Automagic::findInOptionList(), llvm::LLVMTCERISCVIntrinsicsLowering::findOperationName(), SimulatorFrontend::findPort(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), FUGen::FUGen(), ProGeTools::generateableDAGOperations(), Automagic::generateableDAGOperations(), llvm::LLVMTCEBuilder::getHWOperation(), MachineInfo::getOpset(), MachineInfo::getOpset(), TTAMachine::FunctionUnit::hasOperation(), TTAMachine::HWOperation::HWOperation(), llvm::LLVMTCEBuilder::initDataSections(), POMDisassembler::isCallOrJump(), FUTestbenchGenerator::isShiftOrRotOp(), TDGen::llvmOperationName(), TDGen::llvmOperationPattern(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), TCEString::lower(), MachineInfo::maxMemoryAlignment(), ProGeTools::nodeLatency(), Automagic::nodeLatency(), OperationPoolPimpl::operation(), TTAMachine::FunctionUnit::operation(), FUResourceConflictDetector::operationID(), TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand(), SimControlLanguageCommand::parseBreakpoint(), MachineState::portState(), FUGen::prepareSnippet(), SimProgramBuilder::processBidirTerminal(), FUGen::readFile(), FUGen::readImplementation(), FUGen::scheduleOperations(), TTAMachine::HWOperation::setName(), TTAMachine::OperationTriggeredOperand::setName(), FUGen::subOpConnection(), FUGen::subOpName(), TDGen::writeBackendCode(), and FUTestbenchGenerator::writeInputPortStimulus().
stringToUpper()
string StringTools::stringToUpper (const std::string & source) static
Converts a string to upper case letters.
Parameters
source String to be converted.
Returns
String as upper case letters.
Definition at line 143 of file StringTools.cc.
{
    string upString;
    upString.reserve(source.length());
    for (unsigned int i = 0; i < source.length(); ++i) {
        upString.push_back(toupper(source[i]));
    }
    return upString;
}
Referenced by UtilizationStats::calculateForInstruction(), TCEString::capitalize(), ConfigurationFile::checkSemantics(), containsChar(), ProximFUDetailsCmd::Do(), TDGen::emulatingOpNodeLLVMName(), InfoProcCommand::execute(), InfoStatsCommand::execute(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), SimulatorFrontend::finishSimulation(), FUFiniteStateAutomaton::FUFiniteStateAutomaton(), generateHeader(), TDGen::getLLVMPatternWithConstants(), HDB::FUImplementation::hasOpcode(), OperationBehaviorLoader::importBehavior(), OperationPimpl::loadState(), HDB::FUImplementation::opcode(), FUFiniteStateAutomaton::operationCollisionMatrix(), FSAFUResourceConflictDetector::operationID(), ResourceVectorFUResourceConflictDetector::operationID(), TTAMachine::ResourceVectorSet::resourceVector(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), DataDependenceGraph::setMachine(), HDB::FUImplementation::setOpcode(), TDGen::supportedStackAccessOperations(), OperationSerializer::toOperation(), HDB::FUImplementation::unsetOpcode(), OperationPropertyDialog::updateOperation(), TCEString::upper(), TDGen::writeInstrInfo(), TDGen::writeOperationDef(), ProGe::CUOpcodeGenerator::WriteVerilogOpcodePackage(), and ProGe::CUOpcodeGenerator::WriteVhdlOpcodePackage().
trim()
std::string StringTools::trim (const std::string & source) static
Removes leading and trailing whitespace from the string.
Returns
The trimmed string.
Parameters
source The string to trim.
Definition at line 55 of file StringTools.cc.
{
    string result = "";
    int i = 0;
    // remove leading white space
    while (i < static_cast<int>(source.size()) && isspace(source[i])) {
        ++i;
    }
    result = source.substr(i);
    i = result.size() - 1;
    while (i >= 0 && isspace(result[i])) {
        --i;
    }
    result = result.substr(0, i+1);
    return result;
}
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), PlatformIntegrator::chopSignalToTag(), chopString(), chopString(), IPXactHibiInterface::createInstanceName(), ProximSimulationThread::Entry(), DesignSpaceExplorer::evaluate(), CommandsCommand::execute(), EnableBPCommand::execute(), ProjectFileGenerator::extractFUName(), HDLTemplateInstantiator::getPlaceholderDefault(), HDLTemplateInstantiator::getPlaceholderKey(), SimpleScriptInterpreter::interpret(), TclInterpreter::interpret(), main(), ConfigurationFile::parse(), SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimulatorCLI::run(), OperationPropertyDialog::saveOperation(), DesignSpaceExplorer::simulate(), ConfigurationFile::timeStampValue(), and EditLineReader::updateHistory().
The documentation for this class was generated from the following files:
StringTools.hh
StringTools.cc