OpenASIP: ProGe::MemoryBusInterface Class Reference
ProGe::MemoryBusInterface Class Reference
#include <MemoryBusInterface.hh>
Public Member Functions
MemoryBusInterface (const TCEString &addressSpaceName=TCEString())
MemoryBusInterface (SignalGroup groupType, const TCEString &addressSpaceName=TCEString())
virtual ~MemoryBusInterface ()
virtual MemoryBusInterface * clone (bool asMirrored=false) const
TCEString addressSpace () const
Public Member Functions inherited from ProGe::NetlistPortGroup
NetlistPortGroup (SignalGroup signalGroup=SignalGroup())
template<typename... PortType>
NetlistPortGroup (SignalGroup groupType, PortType... ts)
virtual ~NetlistPortGroup ()
size_t portCount () const
const NetlistPort & portAt (size_t index) const
NetlistPort & portAt (size_t index)
void addPort (NetlistPort &port)
bool hasPortBySignal (SignalType type) const
const NetlistPort & portBySignal (SignalType type) const
void clear ()
bool hasParent () const
const BaseNetlistBlock & parent () const
BaseNetlistBlock & parent ()
void assignSignalGroup (SignalGroup signalGroup)
SignalGroup assignedSignalGroup () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
Private Member Functions
MemoryBusInterface ()
MemoryBusInterface (const MemoryBusInterface &, bool asMirrored=false)
Private Attributes
TCEString addressSpaceName_ = TCEString()
Name of the address space the memory bus is bound.
Additional Inherited Members
Public Types inherited from ProGe::NetlistPortGroup
typedef std::vector< NetlistPort * > PortContainerType
typedef PortContainerType::iterator iterator
typedef PortContainerType::const_iterator const_iterator
typedef PortContainerType::reverse_iterator reverse_iterator
typedef PortContainerType::const_reverse_iterator const_reverse_iterator
Protected Member Functions inherited from ProGe::NetlistPortGroup
NetlistPortGroup (const NetlistPortGroup &, bool asMirrored=false)
Detailed Description
Definition at line 46 of file MemoryBusInterface.hh.
Constructor & Destructor Documentation
MemoryBusInterface() [1/4]
ProGe::MemoryBusInterface::MemoryBusInterface (const TCEString & addressSpaceName = TCEString())
Definition at line 38 of file MemoryBusInterface.cc.
    : NetlistPortGroup(SignalGroup()),
      addressSpaceName_(addressSpaceName) {
}
MemoryBusInterface() [2/4]
ProGe::MemoryBusInterface::MemoryBusInterface (SignalGroup groupType, const TCEString & addressSpaceName = TCEString())
Definition at line 43 of file MemoryBusInterface.cc.
    : NetlistPortGroup(groupType),
      addressSpaceName_(addressSpaceName) {
}
~MemoryBusInterface()
ProGe::MemoryBusInterface::~MemoryBusInterface () virtual
Definition at line 57 of file MemoryBusInterface.cc.
{
}
MemoryBusInterface() [3/4]
ProGe::MemoryBusInterface::MemoryBusInterface () private
MemoryBusInterface() [4/4]
ProGe::MemoryBusInterface::MemoryBusInterface (const MemoryBusInterface & otherMemIf, bool asMirrored = false) private
Definition at line 50 of file MemoryBusInterface.cc.
    : NetlistPortGroup(otherMemIf, asMirrored),
      addressSpaceName_(otherMemIf.addressSpaceName_) {
}
Member Function Documentation
addressSpace()
TCEString ProGe::MemoryBusInterface::addressSpace () const
Definition at line 67 of file MemoryBusInterface.cc.
{
    return addressSpaceName_;
}
References addressSpaceName_.
Referenced by ProGe::ProcessorWrapperBlock::addDataMemory(), and ProGe::ProcessorWrapperBlock::addDataMemory2().
clone()
MemoryBusInterface * ProGe::MemoryBusInterface::clone (bool asMirrored = false) const virtual
Clones the NetlistPort and and its ports without parent block reference since it would break unique port name constraint.
Reimplemented from ProGe::NetlistPortGroup.
Definition at line 61 of file MemoryBusInterface.cc.
{
    MemoryBusInterface* newIF =  new MemoryBusInterface(*this, asMirrored);
    return newIF;
}
Member Data Documentation
addressSpaceName_
TCEString ProGe::MemoryBusInterface::addressSpaceName_ = TCEString() private
Name of the address space the memory bus is bound.
Definition at line 65 of file MemoryBusInterface.hh.
Referenced by addressSpace().
The documentation for this class was generated from the following files:
MemoryBusInterface.hh
MemoryBusInterface.cc