OpenASIP: DialogPosition Class Reference
DialogPosition Class Reference
#include <DialogPosition.hh>
Public Types
enum Dialogs {
DIALOG_PROPERTIES , DIALOG_SIMULATE , DIALOG_INPUT_OPERAND , DIALOG_OUTPUT_OPERAND ,
DIALOG_RESULT , DIALOG_OPTIONS , DIALOG_ADD_MODULE , DIALOG_SIMULATION_INFO ,
DIALOG_MEMORY , DIALOG_ABOUT
}
Static Public Member Functions
static wxPoint getPosition (Dialogs dialog)
static void setPosition (Dialogs dialog, wxPoint point)
Private Types
typedef std::map< Dialogs, wxPoint > PositionMap
Container for dialog positions.
Private Member Functions
DialogPosition (const DialogPosition &)
Copying not allowed.
DialogPosition & operator= (const DialogPosition &)
Assignment not allowed.
DialogPosition ()
~DialogPosition ()
Static Private Attributes
static PositionMap positions_
Contains all dialog positions.
Detailed Description
Class that holds the positions of dialogs.
Definition at line 42 of file DialogPosition.hh.
Member Typedef Documentation
PositionMap
typedef std::map<Dialogs, wxPoint> DialogPosition::PositionMap private
Container for dialog positions.
Definition at line 65 of file DialogPosition.hh.
Member Enumeration Documentation
Dialogs
enum DialogPosition::Dialogs
Enumeration of all dialogs in application.
Enumerator
DIALOG_PROPERTIES
Operation properties dialog.
DIALOG_SIMULATE
Simulation dialog.
DIALOG_INPUT_OPERAND
Input operand dialog.
DIALOG_OUTPUT_OPERAND
Output operand dialog.
DIALOG_RESULT
Result dialog.
DIALOG_OPTIONS
Options dialog.
DIALOG_ADD_MODULE
Add module dialog.
DIALOG_SIMULATION_INFO
Simulation info dialog.
DIALOG_MEMORY
Memory dialog.
DIALOG_ABOUT
About dialog.
Definition at line 47 of file DialogPosition.hh.
                 {
        DIALOG_PROPERTIES,        ///< Operation properties dialog.
        DIALOG_SIMULATE,          ///< Simulation dialog.
        DIALOG_INPUT_OPERAND,     ///< Input operand dialog.
        DIALOG_OUTPUT_OPERAND,    ///< Output operand dialog.
        DIALOG_RESULT,            ///< Result dialog.
        DIALOG_OPTIONS,           ///< Options dialog.
        DIALOG_ADD_MODULE,        ///< Add module dialog.
        DIALOG_SIMULATION_INFO,   ///< Simulation info dialog.
        DIALOG_MEMORY,            ///< Memory dialog.
        DIALOG_ABOUT              ///< About dialog.
    };
Constructor & Destructor Documentation
DialogPosition() [1/2]
DialogPosition::DialogPosition (const DialogPosition &) private
Copying not allowed.
DialogPosition() [2/2]
DialogPosition::DialogPosition () private
~DialogPosition()
DialogPosition::~DialogPosition () private
Member Function Documentation
getPosition()
wxPoint DialogPosition::getPosition (Dialogs dialog) static
Gets the position of the dialog.
If position is not stored, returns wxDefaultPosition.
Parameters
dialog Dialog which position is asked.
Returns
The position of the dialog.
Definition at line 49 of file DialogPosition.cc.
{
    PositionMap::iterator it = positions_.find(dialog);
    if (it == positions_.end()) {
        return wxDefaultPosition;
    }
    return (*it).second;
}
References positions_.
operator=()
DialogPosition & DialogPosition::operator= (const DialogPosition &) private
Assignment not allowed.
setPosition()
void DialogPosition::setPosition (Dialogs dialog, wxPoint point) static
Sets the position of the dialog.
Parameters
dialog Dialog which position is set.
Definition at line 63 of file DialogPosition.cc.
{
    PositionMap::iterator it = positions_.find(dialog);
    if (it == positions_.end()) {
        positions_.insert(PositionMap::value_type(dialog, point));
    } else {
        (*it).second = point;
    }
}
References positions_.
Referenced by AddModuleDialog::~AddModuleDialog(), InputOperandDialog::~InputOperandDialog(), MemoryDialog::~MemoryDialog(), OperationDAGDialog::~OperationDAGDialog(), OperationPropertyDialog::~OperationPropertyDialog(), OSEdAboutDialog::~OSEdAboutDialog(), OSEdOptionsDialog::~OSEdOptionsDialog(), OutputOperandDialog::~OutputOperandDialog(), ResultDialog::~ResultDialog(), SimulateDialog::~SimulateDialog(), and SimulationInfoDialog::~SimulationInfoDialog().
Member Data Documentation
positions_
map< DialogPosition::Dialogs, wxPoint > DialogPosition::positions_ static private
Contains all dialog positions.
Definition at line 76 of file DialogPosition.hh.
Referenced by getPosition(), and setPosition().
The documentation for this class was generated from the following files:
DialogPosition.hh
DialogPosition.cc