OpenASIP: TPEF::DebugElement Class Reference
TPEF::DebugElement Class Reference abstract
#include <DebugElement.hh>
Public Types
enum ElementType { DE_STAB = 0x1 }
Public Member Functions
DebugElement ()
virtual ~DebugElement ()
virtual ElementType type () const =0
Chunk * debugString () const
void setDebugString (const ReferenceManager::SafePointer *aString)
void setDebugString (Chunk *aString)
virtual Byte byte (Word index) const =0
Returns one byte of additional data.
virtual Word length () const =0
Returns the length of additional data of debug element.
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Attributes
const ReferenceManager::SafePointer * debugString_
String of debug element.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Base class for all kinds of TPEF elements that belong to debug sections.
Allows representing data of any debug element. All types of TPEF debug elements share a common property: a string that defines (part of) the information stored in the element.
Definition at line 56 of file DebugElement.hh.
Member Enumeration Documentation
ElementType
enum TPEF::DebugElement::ElementType
Enumerator
DE_STAB
Definition at line 58 of file DebugElement.hh.
                     {
        DE_STAB = 0x1
    };
Constructor & Destructor Documentation
DebugElement()
TPEF::DebugElement::DebugElement ()
Constructor.
Definition at line 43 of file DebugElement.cc.
                           : SectionElement() {
}
~DebugElement()
TPEF::DebugElement::~DebugElement () virtual
Destructor.
Definition at line 49 of file DebugElement.cc.
{
}
Member Function Documentation
byte()
virtual Byte TPEF::DebugElement::byte (Word index) const pure virtual
Returns one byte of additional data.
Implemented in TPEF::DebugStabElem.
Referenced by TPEF::TPEFDebugSectionWriter::actualWriteData(), and TPEFDumper::section().
debugString()
Chunk * TPEF::DebugElement::debugString () const
Returns the debug string.
Returns
Debug string.
Definition at line 58 of file DebugElement.cc.
{
    return dynamic_cast<Chunk*>(debugString_->pointer());
}
References debugString_, and TPEF::ReferenceManager::SafePointer::pointer().
Referenced by TPEF::TPEFDebugSectionWriter::actualWriteData(), and TPEFDumper::section().
length()
virtual Word TPEF::DebugElement::length () const pure virtual
Returns the length of additional data of debug element.
Implemented in TPEF::DebugStabElem.
Referenced by TPEF::TPEFDebugSectionWriter::actualWriteData(), and TPEFDumper::section().
setDebugString() [1/2]
void TPEF::DebugElement::setDebugString (Chunk * aString)
Sets the debug string.
Parameters
aString The debug string.
Definition at line 78 of file DebugElement.cc.
{
    using namespace ReferenceManager;
    debugString_ = SafePointer::replaceReference(debugString_, aString);
}
References debugString_, and TPEF::ReferenceManager::SafePointer::replaceReference().
setDebugString() [2/2]
void TPEF::DebugElement::setDebugString (const ReferenceManager::SafePointer * aString)
Sets the debug string.
Parameters
aString Debug string to set.
Definition at line 68 of file DebugElement.cc.
{
    debugString_ = aString;
}
References debugString_.
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol(), and TPEF::TPEFDebugSectionReader::readData().
type()
virtual ElementType TPEF::DebugElement::type () const pure virtual
Implemented in TPEF::DebugStabElem.
Referenced by TPEF::TPEFDebugSectionWriter::actualWriteData(), and TPEFDumper::section().
Member Data Documentation
debugString_
const ReferenceManager::SafePointer* TPEF::DebugElement::debugString_ protected
String of debug element.
Definition at line 78 of file DebugElement.hh.
Referenced by debugString(), setDebugString(), and setDebugString().
The documentation for this class was generated from the following files:
DebugElement.hh
DebugElement.cc