OpenASIP: AssemblyParserDiagnostic Class Reference
AssemblyParserDiagnostic Class Reference
#include <AssemblyParserDiagnostic.hh>
Public Member Functions
void reset (std::shared_ptr< const std::string > assemblyText)
void addWarning (UValue lineNumber, const std::string &message)
void addError (UValue lineNumber, const std::string &message)
void addError (const std::string &message)
void clear ()
const std::set< CompilerMessage > & warnings () const
bool anyErrors () const
const std::set< CompilerMessage > & errors () const
const std::set< CompilerMessage > & otherErrors () const
std::string codeLine (UValue lineNumber) const
Private Attributes
std::set< CompilerMessage > warnings_
Warning messages.
std::set< CompilerMessage > codeErrors_
Error messages with line number.
std::set< CompilerMessage > otherErrors_
For positionless and internal errors.
std::shared_ptr< const std::string > listing_ = nullptr
The current assembly listing.
std::vector< UValue > lineStarts_
New line start positions in assembly listing.
Detailed Description
The class for storing and query assembly parser reports.
Definition at line 68 of file AssemblyParserDiagnostic.hh.
Member Function Documentation
addError() [1/2]
void AssemblyParserDiagnostic::addError (const std::string & message)
Definition at line 79 of file AssemblyParserDiagnostic.cc.
{
    CompilerMessage msg;
    msg.message = message;
    otherErrors_.insert(msg);
}
References CompilerMessage::message, and otherErrors_.
addError() [2/2]
void AssemblyParserDiagnostic::addError (UValue lineNumber, const std::string & message)
Definition at line 68 of file AssemblyParserDiagnostic.cc.
{
    CompilerMessage msg;
    msg.lineNumber = lineNumber;
    msg.message = message;
    msg.assemblerLine = codeLine(lineNumber);
    codeErrors_.insert(msg);
}
References CompilerMessage::assemblerLine, codeErrors_, codeLine(), CompilerMessage::lineNumber, and CompilerMessage::message.
Referenced by InlineAsmParser::reportError(), and InlineAsmParser::reportError().
addWarning()
void AssemblyParserDiagnostic::addWarning (UValue lineNumber, const std::string & message)
Definition at line 56 of file AssemblyParserDiagnostic.cc.
{
    CompilerMessage newWarning;
    newWarning.lineNumber = lineNumber;
    newWarning.message = message;
    newWarning.assemblerLine = codeLine(lineNumber);
    warnings_.insert(newWarning);
}
References CompilerMessage::assemblerLine, codeLine(), CompilerMessage::lineNumber, CompilerMessage::message, and warnings_.
Referenced by CodeSectionCreator::addMove(), Assembler::addWarning(), MachineResourceManager::indexResource(), and MachineResourceManager::rFPortOrFUIndexReference().
anyErrors()
bool AssemblyParserDiagnostic::anyErrors () const inline
Definition at line 82 of file AssemblyParserDiagnostic.hh.
{
        return errors().size() && otherErrors().size();
    }
References errors(), and otherErrors().
clear()
void AssemblyParserDiagnostic::clear ()
Clears all accumulated reports.
Definition at line 89 of file AssemblyParserDiagnostic.cc.
{
    warnings_.clear();
    codeErrors_.clear();
    otherErrors_.clear();
}
References codeErrors_, otherErrors_, and warnings_.
Referenced by reset().
codeLine()
std::string AssemblyParserDiagnostic::codeLine (UValue lineNumber) const
Definition at line 96 of file AssemblyParserDiagnostic.cc.
{
    std::string errorLine;
    assert(listing_ && "reset() must be called before codeLine().");
    unsigned int errorLineNum =
        static_cast<unsigned int>(lineNumber - 1);
    if (errorLineNum < lineStarts_.size()) {
        std::string::size_type startPos =
            lineStarts_[errorLineNum];
        std::string::size_type endPos = listing_->find('\n', startPos);
        // no line feed at end of file
        if (endPos == std::string::npos) {
            endPos = listing_->length();
        }
        errorLine = listing_->substr(startPos, endPos - startPos);
    } else {
        errorLine = "Invalid line number info, probably last line of file.";
    }
    return errorLine;
}
References assert, lineStarts_, and listing_.
Referenced by addError(), addWarning(), and Assembler::codeLine().
errors()
const std::set< CompilerMessage > & AssemblyParserDiagnostic::errors () const inline
Definition at line 86 of file AssemblyParserDiagnostic.hh.
{
        return codeErrors_;
    }
References codeErrors_.
Referenced by anyErrors().
otherErrors()
const std::set< CompilerMessage > & AssemblyParserDiagnostic::otherErrors () const inline
Definition at line 90 of file AssemblyParserDiagnostic.hh.
{
        return otherErrors_;
    }
References otherErrors_.
Referenced by anyErrors().
reset()
void AssemblyParserDiagnostic::reset (std::shared_ptr< const std::string > assemblyText)
Resets assembly text. Also clears all reports.
Definition at line 40 of file AssemblyParserDiagnostic.cc.
{
    clear();
    listing_ = assemblyText;
    lineStarts_.push_back(0);
    for (size_t pos = 0; pos < listing_->size(); pos++) {
        char c = listing_->at(pos);
        if (c == '\n') {
            lineStarts_.push_back(pos+1);
        }
    }
}
References clear(), lineStarts_, and listing_.
Referenced by Assembler::compile(), and InlineAsmParser::parse().
warnings()
const std::set< CompilerMessage > & AssemblyParserDiagnostic::warnings () const inline
Definition at line 78 of file AssemblyParserDiagnostic.hh.
{
        return warnings_;
    }
References warnings_.
Referenced by llvm::LLVMTCEBuilder::emitInlineAsm(), and Assembler::warnings().
Member Data Documentation
codeErrors_
std::set<CompilerMessage> AssemblyParserDiagnostic::codeErrors_ private
Error messages with line number.
Definition at line 102 of file AssemblyParserDiagnostic.hh.
Referenced by addError(), clear(), and errors().
lineStarts_
std::vector<UValue> AssemblyParserDiagnostic::lineStarts_ private
New line start positions in assembly listing.
Definition at line 111 of file AssemblyParserDiagnostic.hh.
Referenced by codeLine(), and reset().
listing_
std::shared_ptr<const std::string> AssemblyParserDiagnostic::listing_ = nullptr private
The current assembly listing.
Definition at line 108 of file AssemblyParserDiagnostic.hh.
Referenced by codeLine(), and reset().
otherErrors_
std::set<CompilerMessage> AssemblyParserDiagnostic::otherErrors_ private
For positionless and internal errors.
Definition at line 105 of file AssemblyParserDiagnostic.hh.
Referenced by addError(), clear(), and otherErrors().
warnings_
std::set<CompilerMessage> AssemblyParserDiagnostic::warnings_ private
Warning messages.
Definition at line 99 of file AssemblyParserDiagnostic.hh.
Referenced by addWarning(), clear(), and warnings().
The documentation for this class was generated from the following files:
AssemblyParserDiagnostic.hh
AssemblyParserDiagnostic.cc