OpenASIP: ConnectionEditPart Class Reference
ConnectionEditPart Class Reference
#include <ConnectionEditPart.hh>
Public Member Functions
ConnectionEditPart ()
virtual ~ConnectionEditPart ()
EditPart * source () const
EditPart * target () const
void setSource (EditPart *source)
void setTarget (EditPart *target)
Public Member Functions inherited from EditPart
EditPart ()
virtual ~EditPart ()
void putGarbage (std::set< EditPart * > &trashbag)
EditPart * parent () const
void setParent (EditPart *parent)
TTAMachine::MachinePart * model () const
void setModel (TTAMachine::MachinePart *model)
Figure * figure () const
void setFigure (Figure *figure)
EditPart * find (wxPoint point)
EditPart * find (const TTAMachine::MachinePart *model)
EditPart * findNearest (wxPoint point, const EditPart *exclude=NULL)
int findInRange (wxPoint point, float radius, std::vector< EditPart * > &found)
bool hasEditPartRecursive (const EditPart *part) const
bool selectable () const
bool selected () const
void setSelectable (bool selectable)
void setSelected (bool select)
void installEditPolicy (EditPolicy *editpolicy)
void addChild (EditPart *child)
int childCount () const
EditPart * child (unsigned int index) const
ComponentCommand * performRequest (Request *request) const
bool canHandle (Request *request) const
Private Member Functions
ConnectionEditPart & operator= (ConnectionEditPart &old)
Assignment not allowed.
ConnectionEditPart (ConnectionEditPart &old)
Copying not allowed.
Private Attributes
EditPart * source_
Source of connection.
EditPart * target_
Target of connection.
Additional Inherited Members
Protected Attributes inherited from EditPart
EditPart * parent_
Parent of this EditPart.
Figure * figure_
Figure of this EditPart.
TTAMachine::MachinePart * model_
Machine component corresponding to this EditPart.
bool selectable_
Tells whether the EditPart is selectable or not.
bool selected_
Tells whether the EditPart is selected or not.
bool garbageCollected_
Helper member to prevent improper deletion.
std::vector< EditPolicy * > editPolicies_
List of supported EditPolicies.
std::vector< EditPart * > children_
List of children EditParts.
Detailed Description
A directed connection between two machine blocks on the canvas.
Definition at line 42 of file ConnectionEditPart.hh.
Constructor & Destructor Documentation
ConnectionEditPart() [1/2]
ConnectionEditPart::ConnectionEditPart ()
The Constructor.
Definition at line 41 of file ConnectionEditPart.cc.
                                      : source_(NULL), target_(NULL) {
}
~ConnectionEditPart()
ConnectionEditPart::~ConnectionEditPart () virtual
The Destructor.
Definition at line 47 of file ConnectionEditPart.cc.
{
}
ConnectionEditPart() [2/2]
ConnectionEditPart::ConnectionEditPart (ConnectionEditPart & old) private
Copying not allowed.
Member Function Documentation
operator=()
ConnectionEditPart & ConnectionEditPart::operator= (ConnectionEditPart & old) private
Assignment not allowed.
setSource()
void ConnectionEditPart::setSource (EditPart * source)
Sets the source of this connection.
Parameters
source New source.
Definition at line 56 of file ConnectionEditPart.cc.
{
    assert(figure_ != NULL);
    ConnectionFigure* fig = dynamic_cast<ConnectionFigure*>(figure_);
    assert(fig != NULL);
    fig->setSource(source->figure());
    figure_ = fig;
    source_ = source;
}
References assert, EditPart::figure(), EditPart::figure_, ConnectionFigure::setSource(), source(), and source_.
Referenced by MachineEditPartFactory::createBiDirBridge(), ConnectionFactory::createConnection(), SocketBusConnFactory::createConnection(), SocketPortConnFactory::createConnection(), and BridgeFactory::createEditPart().
setTarget()
void ConnectionEditPart::setTarget (EditPart * target)
Sets the target of this connection.
Parameters
target New target.
Definition at line 71 of file ConnectionEditPart.cc.
{
    assert(figure_ != NULL);
    ConnectionFigure* fig = dynamic_cast<ConnectionFigure*>(figure_);
    assert(fig != NULL);
    fig->setTarget(target->figure());
    figure_ = fig;
    target_ = target;
}
References assert, EditPart::figure(), EditPart::figure_, ConnectionFigure::setTarget(), target(), and target_.
Referenced by MachineEditPartFactory::createBiDirBridge(), ConnectionFactory::createConnection(), SocketBusConnFactory::createConnection(), SocketPortConnFactory::createConnection(), and BridgeFactory::createEditPart().
source()
EditPart * ConnectionEditPart::source () const
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), and setSource().
target()
EditPart * ConnectionEditPart::target () const
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), and setTarget().
Member Data Documentation
source_
EditPart* ConnectionEditPart::source_ private
Source of connection.
Definition at line 60 of file ConnectionEditPart.hh.
Referenced by setSource().
target_
EditPart* ConnectionEditPart::target_ private
Target of connection.
Definition at line 62 of file ConnectionEditPart.hh.
Referenced by setTarget().
The documentation for this class was generated from the following files:
ConnectionEditPart.hh
ConnectionEditPart.cc