OpenASIP: TPEF::DebugSection Class Reference
TPEF::DebugSection Class Reference
#include <DebugSection.hh>
Public Member Functions
virtual ~DebugSection ()
virtual SectionType type () const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
DebugSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Static Private Attributes
static DebugSection proto_
Prototype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Debug section.
Definition at line 44 of file DebugSection.hh.
Constructor & Destructor Documentation
~DebugSection()
TPEF::DebugSection::~DebugSection () virtual
Destructor.
Definition at line 56 of file DebugSection.cc.
{
}
DebugSection()
TPEF::DebugSection::DebugSection (bool init) protected
Constructor.
Parameters
init True if registeration is wanted.
Definition at line 45 of file DebugSection.cc.
                                    : Section() {
    if (init) {
        Section::registerSection(this);
    }
    setFlagVLen();
    unsetFlagNoBits();
}
References TPEF::Section::registerSection(), TPEF::Section::setFlagVLen(), and TPEF::Section::unsetFlagNoBits().
Member Function Documentation
clone()
Section * TPEF::DebugSection::clone () const protected virtual
Creates an instance of class.
Returns
Newly created section.
Implements TPEF::Section.
Definition at line 75 of file DebugSection.cc.
{
    return new DebugSection(false);
}
type()
Section::SectionType TPEF::DebugSection::type () const virtual
Returns section's type.
Returns
Type of section.
Implements TPEF::Section.
Definition at line 65 of file DebugSection.cc.
{
    return ST_DEBUG;
}
References TPEF::Section::ST_DEBUG.
Member Data Documentation
proto_
DebugSection TPEF::DebugSection::proto_ static private
Prototype instance of section.
Definition at line 56 of file DebugSection.hh.
The documentation for this class was generated from the following files:
DebugSection.hh
DebugSection.cc