OpenASIP: EditParameterDialog Class Reference
EditParameterDialog Class Reference
#include <EditParameterDialog.hh>
Public Member Functions
EditParameterDialog (wxWindow *parent, ExplorerPluginParameter *parameter)
virtual ~EditParameterDialog ()
Private Types
enum {
ID_TEXT , ID_NAME , ID_TYPE , ID_VALUE ,
ID_OK , ID_CANCEL
}
Private Member Functions
virtual bool TransferDataToWindow ()
void onClose (wxCommandEvent &event)
void onOk (wxCommandEvent &event)
void setTexts ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
wxStaticText * paramName_
name
wxStaticText * paramType_
name
wxTextCtrl * paramValue_
name
ExplorerPluginParameter * parameter_
Detailed Description
Explorer plugin call window.
Definition at line 49 of file EditParameterDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_TEXT
ID_NAME
ID_TYPE
ID_VALUE
ID_OK
ID_CANCEL
Definition at line 74 of file EditParameterDialog.hh.
         {
        ID_TEXT,
        ID_NAME,
        ID_TYPE,
        ID_VALUE,
        ID_OK,
        ID_CANCEL
    };
Constructor & Destructor Documentation
EditParameterDialog()
EditParameterDialog::EditParameterDialog (wxWindow * parent, ExplorerPluginParameter * parameter)
The Constructor.
Parameters
parent Parent window of the dialog.
addressSpace The address space to be modified with the dialog.
Definition at line 72 of file EditParameterDialog.cc.
                                       :
    wxDialog(parent, -1, _T(""), wxDefaultPosition), parameter_(parameter)
    {
    createContents(this, true, true);
    paramName_ = dynamic_cast<wxStaticText*>(FindWindow(ID_NAME));
    paramType_ = dynamic_cast<wxStaticText*>(FindWindow(ID_TYPE));
    paramValue_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_VALUE));
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
~EditParameterDialog()
EditParameterDialog::~EditParameterDialog () virtual
The Destructor.
Definition at line 93 of file EditParameterDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * EditParameterDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 162 of file EditParameterDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Parameter Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item3 = new wxStaticText( parent, ID_NAME, wxT("xxxxxxxxxxxxxxx"), wxDefaultPosition, wxSize(150,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALL, 5 );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("Parameter Type:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_TYPE, wxT("xxxxxxxxxxxx"), wxDefaultPosition, wxSize(150,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item4, 0, wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Value:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item9 = new wxTextCtrl( parent, ID_VALUE, wxT(""), wxDefaultPosition, wxSize(110,-1), 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item11 = new wxButton( parent, ID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item12 = new wxButton( parent, ID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxALL, 5 );
    item0->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CANCEL, ID_NAME, ID_OK, ID_TEXT, ID_TYPE, and ID_VALUE.
onClose()
void EditParameterDialog::onClose (wxCommandEvent & event) private
Validates input in the controls, and updates the AddressSpace.
Definition at line 131 of file EditParameterDialog.cc.
{
    EndModal(wxID_OK);
}
onOk()
void EditParameterDialog::onOk (wxCommandEvent & event) private
Stores new value set by the user.
Definition at line 140 of file EditParameterDialog.cc.
{
    std::string value = WxConversion::toString(paramValue_->GetValue());
    parameter_->setValue(value);
    EndModal(wxID_OK);
}
References parameter_, paramValue_, ExplorerPluginParameter::setValue(), and WxConversion::toString().
setTexts()
void EditParameterDialog::setTexts () private
Sets texts for widgets.
Definition at line 101 of file EditParameterDialog.cc.
{
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_EDIT_PARAMETER_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    paramName_->SetLabel(WxConversion::toWxString(parameter_->name()));
    paramType_->SetLabel(WxConversion::toWxString(parameter_->typeAsString()));
    paramValue_->Clear();
    paramValue_->AppendText(WxConversion::toWxString(parameter_->value()));
}
References ProDeTextGenerator::instance(), ExplorerPluginParameter::name(), parameter_, paramName_, paramType_, paramValue_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_EDIT_PARAMETER_TITLE, ExplorerPluginParameter::typeAsString(), and ExplorerPluginParameter::value().
TransferDataToWindow()
bool EditParameterDialog::TransferDataToWindow () private virtual
Transfers data from the AddressSpace object to the dialog widgets.
Returns
false, if an error occured in the transfer, true otherwise.
Definition at line 122 of file EditParameterDialog.cc.
{
    return wxWindow::TransferDataToWindow();
}
Member Data Documentation
parameter_
ExplorerPluginParameter* EditParameterDialog::parameter_ private
Definition at line 72 of file EditParameterDialog.hh.
Referenced by onOk(), and setTexts().
paramName_
wxStaticText* EditParameterDialog::paramName_ private
name
Definition at line 66 of file EditParameterDialog.hh.
Referenced by setTexts().
paramType_
wxStaticText* EditParameterDialog::paramType_ private
name
Definition at line 68 of file EditParameterDialog.hh.
Referenced by setTexts().
paramValue_
wxTextCtrl* EditParameterDialog::paramValue_ private
name
Definition at line 70 of file EditParameterDialog.hh.
Referenced by onOk(), and setTexts().
The documentation for this class was generated from the following files:
EditParameterDialog.hh
EditParameterDialog.cc