OpenASIP: BFPushMoveUp2 Class Reference
BFPushMoveUp2 Class Reference
#include <BFPushMoveUp2.hh>
Public Member Functions
BFPushMoveUp2 (BF2Scheduler &sched, MoveNode &mn, int lc)
bool operator() ()
Public Member Functions inherited from BFUnscheduleMove
BFUnscheduleMove (BF2Scheduler &sched, MoveNode &mn)
void unscheduleOriginal ()
void undoOnlyMe ()
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Member Functions
bool isLoopBypass (MoveNode &mn)
Private Attributes
int lc_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFUnscheduleMove
void returnOriginal ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFUnscheduleMove
MoveNode & mn_
int oldCycle_
const TTAMachine::Bus * oldBus_
const TTAMachine::Bus * prologBus_
int oldImmWriteCycle_
int prologImmWriteCycle_
const TTAMachine::FunctionUnit * dstFU_
const TTAMachine::FunctionUnit * srcFU_
const TTAMachine::ImmediateUnit * immu_
int immRegIndex_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFUnscheduleMove
static int recurseCounter_ = 0
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 51 of file BFPushMoveUp2.hh.
Constructor & Destructor Documentation
BFPushMoveUp2()
BFPushMoveUp2::BFPushMoveUp2 (BF2Scheduler & sched, MoveNode & mn, int lc) inline
Definition at line 54 of file BFPushMoveUp2.hh.
                                                   :
        BFUnscheduleMove(sched, mn), lc_(lc) {}
Member Function Documentation
isLoopBypass()
bool BFPushMoveUp2::isLoopBypass (MoveNode & mn) private
Definition at line 181 of file BFPushMoveUp2.cc.
{
    auto inEdges = ddg().operationInEdges(mn);
    for (auto e: inEdges) {
        if (e->isBackEdge()) {
            return true;
        }
    }
    return false;
}
References BFOptimization::ddg(), and DataDependenceGraph::operationInEdges().
Referenced by operator()().
operator()()
bool BFPushMoveUp2::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 48 of file BFPushMoveUp2.cc.
{
    if (lc_ == -1) {
        std::cerr << "incoming lc -1 on pushmoveup!"  << std::endl;
        assert(false);
    }
    if (mn_.move().isControlFlowMove()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t|TCannot reschedule control flow move!" << std::endl;
#endif
        return false;
    }
    if (&mn_ == sched_.guardWriteNode()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t|TCannot reschedule guard write move!" << std::endl;
#endif
        return false;
    }
    if (!mn_.isSourceOperation()) {
        return false;
    }
    // unschedule this (result) move
    ProgramOperation& po = mn_.sourceOperation();
    MoveNode* trigger = po.triggeringMove();
    unscheduleOriginal();
    int ddgLC = ddg().latestCycle(mn_,ii());
    int ddgEC = ddg().earliestCycle(mn_,ii());
    if (ddgLC == -1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "ddg latest cycle -1 in pushmoveup2 of:"
                  << mn_.toString() << std::endl;
#endif
        returnOriginal();
        return false;
    }
    int lc = std::min(lc_, ddgLC);
    if (ddgEC > lc) {
        DataDependenceGraph::NodeSet unschedOperands;
        DataDependenceGraph::NodeSet unschedResults;
        // undo the inputs
        for (int i = 0; i < po.inputMoveCount(); i++) {
            MoveNode& operand = po.inputMove(i);
            if (operand.isScheduled()) {
                if (!runPostChild(new BFUnscheduleMove(sched_, operand))) {
                    undo();
                    return false;
                } else {
                    unschedOperands.insert(&operand);
                }
            }
        }
        for (int i = 0; i < po.outputMoveCount(); i++) {
            MoveNode& res = po.outputMove(i);
            if (res.isScheduled() &&
                (res.cycle() > lc ||
                 (isLoopBypass(res) && res.cycle()+((signed)ii()) > lc))) {
                if (!runPostChild(new BFUnscheduleMove(sched_, res))) {
                    undo();
                    return false;
                } else {
                    unschedResults.insert(&res);
                }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            } else {
                std::cerr << "res which is not scheduled:" << res.toString()
                          << std::endl;
#endif
            }
        }
        // now whole op is not scheduled?
        // reschedule other results
        for (int i = po.outputMoveCount()-1; i >= 0; i--) {
            MoveNode& res = po.outputMove(i);
            if (AssocTools::containsKey(unschedResults, &res)) {
                int myLC = lc - isLoopBypass(res) * ii();
                if (!runPostChild(
                        new BFScheduleBU(
                            sched_, res, myLC, false, false, false))) {
                    undo();
                    return false;
                }
            }
        }
        // reschedule me.
        if (!runPostChild(
                new BFScheduleBU(sched_, mn_, lc, false, false, false))) {
            undo();
            return false;
        }
        // reschdule trigger
        if (AssocTools::containsKey(unschedOperands, trigger)) {
            if (!runPostChild(
                    new BFScheduleBU(
                        sched_, *trigger, lc, false, false, false))) {
                undo();
                return false;
            }
        }
        // reschedule other operands
        for (int i = 0; i < po.inputMoveCount(); i++) {
            MoveNode& operand = po.inputMove(i);
            if (&operand != trigger) {
                if (AssocTools::containsKey(unschedOperands, &operand)) {
                    if (!runPostChild(
                            new BFScheduleBU(
                                sched_, operand, lc, false, false, false))) {
                        undo();
                        return false;
                    }
                }
            }
        }
    } else {
        undo();
        return false;
    }
    assert(mn_.isScheduled());
    return true;
}
References assert, AssocTools::containsKey(), MoveNode::cycle(), BFOptimization::ddg(), DataDependenceGraph::earliestCycle(), BF2Scheduler::guardWriteNode(), BFOptimization::ii(), ProgramOperation::inputMove(), ProgramOperation::inputMoveCount(), TTAProgram::Move::isControlFlowMove(), isLoopBypass(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), DataDependenceGraph::latestCycle(), lc_, BFUnscheduleMove::mn_, MoveNode::move(), ProgramOperation::outputMove(), ProgramOperation::outputMoveCount(), BFUnscheduleMove::returnOriginal(), Reversible::runPostChild(), BFOptimization::sched_, MoveNode::sourceOperation(), MoveNode::toString(), ProgramOperation::triggeringMove(), Reversible::undo(), and BFUnscheduleMove::unscheduleOriginal().
Member Data Documentation
lc_
int BFPushMoveUp2::lc_ private
Definition at line 62 of file BFPushMoveUp2.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPushMoveUp2.hh
BFPushMoveUp2.cc