OpenASIP: OSEdModifyBehaviorCmd Class Reference
OSEdModifyBehaviorCmd Class Reference
#include <OSEdModifyBehaviorCmd.hh>
Public Member Functions
OSEdModifyBehaviorCmd ()
virtual ~OSEdModifyBehaviorCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdModifyBehaviorCmd (const OSEdModifyBehaviorCmd &)
Copying not allowed.
OSEdModifyBehaviorCmd & operator= (const OSEdModifyBehaviorCmd &)
Assignment not allowed.
Detailed Description
Command for modifying operation behavior.
Definition at line 43 of file OSEdModifyBehaviorCmd.hh.
Constructor & Destructor Documentation
OSEdModifyBehaviorCmd() [1/2]
OSEdModifyBehaviorCmd::OSEdModifyBehaviorCmd ()
Constructor.
Definition at line 54 of file OSEdModifyBehaviorCmd.cc.
                                             :
    GUICommand(OSEdConstants::CMD_NAME_MODIFY_BEHAVIOR, NULL) {
}
Referenced by create().
~OSEdModifyBehaviorCmd()
OSEdModifyBehaviorCmd::~OSEdModifyBehaviorCmd () virtual
Destructor.
Definition at line 61 of file OSEdModifyBehaviorCmd.cc.
{
}
OSEdModifyBehaviorCmd() [2/2]
OSEdModifyBehaviorCmd::OSEdModifyBehaviorCmd (const OSEdModifyBehaviorCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdModifyBehaviorCmd::create () const virtual
Creates a new command.
Returns
A new command.
Implements GUICommand.
Definition at line 80 of file OSEdModifyBehaviorCmd.cc.
{
    return new OSEdModifyBehaviorCmd();
}
References OSEdModifyBehaviorCmd().
Do()
bool OSEdModifyBehaviorCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 90 of file OSEdModifyBehaviorCmd.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdOptions* options = wxGetApp().options();
    string editor = options->editor();
    if (editor == "") {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_EDITOR);
        ErrorDialog error(parentWindow(), WxConversion::toWxString(fmt.str()));
        error.ShowModal();
        return false;
    } else if (!FileSystem::fileExists(editor)) {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_OPEN);
        fmt % editor;
        ErrorDialog error(parentWindow(), WxConversion::toWxString(fmt.str()));
        error.ShowModal();
        return false ;
    } else {
        OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
        wxTreeItemId opId = treeView->selectedOperationId();
        string modName = treeView->moduleOfOperation(opId);
        wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
        string pathName = treeView->pathOfModule(modId);
        OperationModule& module = OperationContainer::module(pathName, modName);
        string cmd = "";
        if (module.hasBehaviorSource()) {
            string code = module.behaviorSourceModule();
            cmd = editor + " " + code;
        } else {
            // new behavior is added for the module
            string code = module.propertiesModule();
            size_t pos = code.find_last_of(".");
            code.erase(pos);
            code += ".cc";
            // copy template file as new file
            string dir = Environment::dataDirPath(
                WxConversion::toString(OSEdConstants::APPLICATION_NAME));
            string templateFile = dir + FileSystem::DIRECTORY_SEPARATOR +
                OSEdConstants::BEHAVIOR_TEMPLATE_FILE_NAME;
            FileSystem::copy(templateFile, code);
            cmd = editor + " " + code;
        }
        // we are using detached thread that will be automatically cleaned
        CommandThread* thread = new CommandThread(cmd);
        thread->Create();
        thread->Run();
        return true;
    }
    assert(false);
    return false;
}
References OSEdConstants::APPLICATION_NAME, assert, OSEdConstants::BEHAVIOR_TEMPLATE_FILE_NAME, FileSystem::copy(), Environment::dataDirPath(), FileSystem::DIRECTORY_SEPARATOR, false, FileSystem::fileExists(), OSEdTextGenerator::instance(), OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::moduleOfOperation(), options, GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OSEdTreeView::selectedOperationId(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NO_EDITOR, and OSEdTextGenerator::TXT_ERROR_OPEN.
icon()
string OSEdModifyBehaviorCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 179 of file OSEdModifyBehaviorCmd.cc.
{
    return "";
}
id()
int OSEdModifyBehaviorCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 70 of file OSEdModifyBehaviorCmd.cc.
{
    return OSEdConstants::CMD_MODIFY_BEHAVIOR;
}
References OSEdConstants::CMD_MODIFY_BEHAVIOR.
isEnabled()
bool OSEdModifyBehaviorCmd::isEnabled () virtual
Returns true if command is enabled.
Command is enable when path of the selected operation is writable.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 155 of file OSEdModifyBehaviorCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    if (treeView->isOperationSelected()) {
        wxTreeItemId opId = treeView->selectedOperationId();
        string mod = treeView->moduleOfOperation(opId);
        wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
        string path = treeView->pathOfModule(modId);
        if (FileSystem::fileIsWritable(path)) {
            return true;
        } else {
            return false;
        }
    } else {
        return false;
    }
}
References FileSystem::fileIsWritable(), OSEdTreeView::isOperationSelected(), OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::moduleOfOperation(), OSEdTreeView::pathOfModule(), and OSEdTreeView::selectedOperationId().
operator=()
OSEdModifyBehaviorCmd & OSEdModifyBehaviorCmd::operator= (const OSEdModifyBehaviorCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdModifyBehaviorCmd.hh
OSEdModifyBehaviorCmd.cc