OpenASIP: PrintCmd Class Reference
PrintCmd Class Reference
#include <PrintCmd.hh>
Public Member Functions
PrintCmd ()
virtual ~PrintCmd ()
virtual bool Do ()
virtual int id () const
virtual PrintCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for printing documents.
Definition at line 41 of file PrintCmd.hh.
Constructor & Destructor Documentation
PrintCmd()
PrintCmd::PrintCmd ()
The Constructor.
Definition at line 47 of file PrintCmd.cc.
                  :
    EditorCommand(ProDeConstants::CMD_NAME_PRINT) {
}
Referenced by create().
~PrintCmd()
PrintCmd::~PrintCmd () virtual
The Destructor.
Definition at line 56 of file PrintCmd.cc.
                    {
}
Member Function Documentation
create()
PrintCmd * PrintCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 131 of file PrintCmd.cc.
                       {
    return new PrintCmd();
}
References PrintCmd().
Do()
bool PrintCmd::Do () virtual
Executes the command.
If the wxWidgets printing framework was not compiled in the wxWidgets library, printing is not possible. An error message will be displayed instead of printing.
Returns
Always false. The command is not undoable.
Implements GUICommand.
Definition at line 70 of file PrintCmd.cc.
             {
#if WX_PRINTING_DISABLED
    // wxWidgets was compiled without printing framework, display an
    // error message.
    wxString message =
        wxString(_T("Printing framework is disabled in the wxWidgets\n"));
    message.Append(_T("library. Print previewing is not possible."));
    ErrorDialog error(parentWindow(), message);
    error.ShowModal();
    return false;
#else
    // wxWidgets was compiled with the printing framework, create printout
    // of the active view and print it.
    // find the active view
    wxView* view = wxGetApp().docManager()->GetCurrentView();
    if (view == NULL) {
        return false;
    }
    // create a printout of the active view
    wxPrintout* printout = view->OnCreatePrintout();
    if (printout != NULL) {
        wxPrinter printer;
        printer.Print(view->GetFrame(), printout, true);
        delete printout;
    }
    return false;
#endif // WX_PRINTING_DISABLED
}
References GUICommand::parentWindow(), and EditorCommand::view().
icon()
string PrintCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 142 of file PrintCmd.cc.
                     {
    return ProDeConstants::CMD_ICON_PRINT;
}
References ProDeConstants::CMD_ICON_PRINT.
id()
int PrintCmd::id () const virtual
Return id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 120 of file PrintCmd.cc.
                   {
    return ProDeConstants::COMMAND_PRINT;
}
References ProDeConstants::COMMAND_PRINT.
isEnabled()
bool PrintCmd::isEnabled () virtual
Returns true when command is executable, false when not.
This command is executable when a document is open.
Returns
True, if the command is executable.
Reimplemented from EditorCommand.
Definition at line 155 of file PrintCmd.cc.
                    {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
The documentation for this class was generated from the following files:
PrintCmd.hh
PrintCmd.cc