OpenASIP: RFPortCheck Class Reference
RFPortCheck Class Reference
#include <RFPortCheck.hh>
Public Member Functions
RFPortCheck ()
virtual ~RFPortCheck ()
virtual bool check (const TTAMachine::Machine &mach, MachineCheckResults &results) const
Public Member Functions inherited from MachineCheck
virtual std::string shortDescription () const
virtual std::string description () const
virtual bool canFix (const TTAMachine::Machine &mach) const
virtual std::string fix (TTAMachine::Machine &mach) const
virtual ~MachineCheck ()
Additional Inherited Members
Protected Member Functions inherited from MachineCheck
MachineCheck (const std::string &shortDesc_)
Detailed Description
Checks that the ports of the register files are sensible.
Currently checks only that there is at least one input port in the register file.
Definition at line 44 of file RFPortCheck.hh.
Constructor & Destructor Documentation
RFPortCheck()
RFPortCheck::RFPortCheck ()
The constructor.
Definition at line 47 of file RFPortCheck.cc.
                         : MachineCheck("Sanity checks for RF ports.") {
}
~RFPortCheck()
RFPortCheck::~RFPortCheck () virtual
The destructor.
Definition at line 53 of file RFPortCheck.cc.
{
}
Member Function Documentation
check()
bool RFPortCheck::check (const TTAMachine::Machine & mach, MachineCheckResults & results) const virtual
Sanity checks the RF ports of the target machine.
Parameters
mach Machine to be checked.
results Check results.
Returns
True if the check passed
Todo:
Check if there is no read ports and the register file has at least one register which is not a predicate reg (read by GCU).
Implements MachineCheck.
Definition at line 64 of file RFPortCheck.cc.
{
    bool checksOk = true;
    Machine::RegisterFileNavigator RFs = mach.registerFileNavigator();
    for (int i = 0; i < RFs.count(); i++) {
        const TTAMachine::RegisterFile& rf = *RFs.item(i);
        int inputPorts = 0;
        const int ports = rf.portCount();
        for (int p = 0; p < ports; ++p) {
            const TTAMachine::RFPort* port = rf.port(p);
            if (port->isInput()) {
                ++inputPorts;
                break;
            }
        }
        if (inputPorts == 0) {
            results.addError(
                *this,
                (boost::format(
                    "Register file '%s' does not have any input ports.").
                 str()));
            checksOk = false;
        }
    }
    /// @todo Check if there is no read ports and the register file has
    /// at least one register which is not a predicate reg (read by GCU).
    return checksOk;
}
References MachineCheckResults::addError(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Port::isInput(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), and TTAMachine::Machine::registerFileNavigator().
The documentation for this class was generated from the following files:
RFPortCheck.hh
RFPortCheck.cc