OpenASIP: HelpCommand Class Reference
HelpCommand Class Reference
#include <HelpCommand.hh>
Public Member Functions
HelpCommand ()
virtual ~HelpCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Private Member Functions
HelpCommand & operator= (const HelpCommand &)
Assignment not allowed.
HelpCommand (const HelpCommand &cmd)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "help" command of the Simulator Control Language.
Definition at line 45 of file HelpCommand.hh.
Constructor & Destructor Documentation
HelpCommand() [1/2]
HelpCommand::HelpCommand ()
Constructor.
Definition at line 47 of file HelpCommand.cc.
                         : SimControlLanguageCommand("help") {
}
~HelpCommand()
HelpCommand::~HelpCommand () virtual
Destructor.
Definition at line 53 of file HelpCommand.cc.
{
}
HelpCommand() [2/2]
HelpCommand::HelpCommand (const HelpCommand & cmd) private
Copying not allowed.
Member Function Documentation
execute()
bool HelpCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the help command.
Prints a help message briefly describing command command. If no command is given, prints general help and a listing of available commands.
Parameters
arguments Arguments for the command.
Returns
True if execution is succesfull, false otherwise
Exceptions
NumberFormatException If conversion of DataObject fails.
Implements CustomCommand.
Definition at line 67 of file HelpCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 0, 1)) {
        return false;
    }
    if (arguments.size() == 1) {
        outputStream() << SimulatorToolbox::textGenerator().text(
                           Texts::TXT_CLI_ONLINE_HELP).str()
                       << std::endl << std::endl;
        outputStream() << SimulatorToolbox::textGenerator().text(
            Texts::TXT_INTERP_HELP_COMMANDS_AVAILABLE).str() << std::endl;
        vector<string> names = interpreter()->customCommandsSortedByName();
        for (size_t i = 0; i < names.size(); i++) {
            outputStream() << names[i] + " ";
        }
        outputStream() << std::endl;
        return true;
    }
    DataObject* obj = new DataObject();
    string cmdName = arguments[1].stringValue();
    CustomCommand* command = interpreter()->customCommand(cmdName);
    if (command == NULL) {
        obj->setString(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_UNKNOWN_COMMAND).str());
        interpreter()->setResult(obj);
        return false;
    } else {
        outputStream() << command->helpText() << std::endl;
        return true;
    }
    return true;
}
References CustomCommand::checkArgumentCount(), ScriptInterpreter::customCommand(), ScriptInterpreter::customCommandsSortedByName(), CustomCommand::helpText(), CustomCommand::interpreter(), SimControlLanguageCommand::outputStream(), ScriptInterpreter::setResult(), DataObject::setString(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_CLI_ONLINE_HELP, Texts::TXT_INTERP_HELP_COMMANDS_AVAILABLE, and Texts::TXT_UNKNOWN_COMMAND.
helpText()
string HelpCommand::helpText () const virtual
Returns help text.
Returns
Help text.
Todo:
TextGenerator.
Implements CustomCommand.
Definition at line 112 of file HelpCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_HELP).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_HELP.
operator=()
HelpCommand & HelpCommand::operator= (const HelpCommand &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
HelpCommand.hh
HelpCommand.cc