OpenASIP: DisassemblyImmediateAssignment Class Reference
DisassemblyImmediateAssignment Class Reference
#include <DisassemblyImmediateAssignment.hh>
Public Member Functions
DisassemblyImmediateAssignment (SimValue value, bool sign, DisassemblyElement *destination)
virtual ~DisassemblyImmediateAssignment ()
virtual std::string toString () const
Public Member Functions inherited from DisassemblyInstructionSlot
virtual ~DisassemblyInstructionSlot ()
DisassemblyAnnotation & annotation (int index) const
void addAnnotation (DisassemblyAnnotation *annotation)
int annotationCount () const
Private Member Functions
DisassemblyImmediateAssignment (const DisassemblyImmediateAssignment &)
Coying not allowed.
DisassemblyImmediateAssignment & operator= (const DisassemblyImmediateAssignment &)
Assignment not allowed.
Private Attributes
SimValue value_
Value of the immediate.
DisassemblyElement * destination_
The destination register.
bool hasValue_
True, if the immediate has value set.
bool signed_
True, if the imm unit is signed.
Additional Inherited Members
Protected Member Functions inherited from DisassemblyInstructionSlot
DisassemblyInstructionSlot ()
Detailed Description
Represents piece of long immediate assignment in the disassembler.
If the long immediate value is given using the constructor with value parameter, disassembly string displays the value.
Definition at line 46 of file DisassemblyImmediateAssignment.hh.
Constructor & Destructor Documentation
DisassemblyImmediateAssignment() [1/2]
DisassemblyImmediateAssignment::DisassemblyImmediateAssignment (SimValue value, bool sign, DisassemblyElement * destination)
The Constructor.
Creates disassembly of an immediate assignment.
Parameters
value Value of the immediate to assign.
destination The destination register.
Definition at line 44 of file DisassemblyImmediateAssignment.cc.
                                    :
    DisassemblyInstructionSlot(),
    value_(value), destination_(destination), hasValue_(true), signed_(sign) {
}
~DisassemblyImmediateAssignment()
DisassemblyImmediateAssignment::~DisassemblyImmediateAssignment () virtual
The destructor.
Definition at line 56 of file DisassemblyImmediateAssignment.cc.
{
    delete destination_;
}
References destination_.
DisassemblyImmediateAssignment() [2/2]
DisassemblyImmediateAssignment::DisassemblyImmediateAssignment (const DisassemblyImmediateAssignment &) private
Coying not allowed.
Member Function Documentation
operator=()
DisassemblyImmediateAssignment & DisassemblyImmediateAssignment::operator= (const DisassemblyImmediateAssignment &) private
Assignment not allowed.
toString()
std::string DisassemblyImmediateAssignment::toString () const virtual
Disassembles the immediate assignment.
Returns
Disassembled immediate assignment as a string.
Implements DisassemblyInstructionSlot.
Definition at line 67 of file DisassemblyImmediateAssignment.cc.
{
    std::string disassembly =  "[" + destination_->toString();
    if (hasValue_) {
        if (signed_) {
            disassembly =
                disassembly + "=" + Conversion::toString(value_.sLongWordValue());
        } else {
            disassembly =
                disassembly + "=" + Conversion::toString(value_.uLongWordValue());
        }
    }
    disassembly = disassembly + "]";
    for (int i = 0; i < annotationCount(); i++) {
        disassembly += annotation(i).toString();
    }
    return disassembly;
}
References DisassemblyInstructionSlot::annotation(), DisassemblyInstructionSlot::annotationCount(), destination_, hasValue_, signed_, SimValue::sLongWordValue(), DisassemblyAnnotation::toString(), DisassemblyElement::toString(), Conversion::toString(), SimValue::uLongWordValue(), and value_.
Referenced by DisassemblyGridTable::GetValue(), and DisassemblyInstruction::toString().
Member Data Documentation
destination_
DisassemblyElement* DisassemblyImmediateAssignment::destination_ private
The destination register.
Definition at line 66 of file DisassemblyImmediateAssignment.hh.
Referenced by toString(), and ~DisassemblyImmediateAssignment().
hasValue_
bool DisassemblyImmediateAssignment::hasValue_ private
True, if the immediate has value set.
Definition at line 68 of file DisassemblyImmediateAssignment.hh.
Referenced by toString().
signed_
bool DisassemblyImmediateAssignment::signed_ private
True, if the imm unit is signed.
Definition at line 70 of file DisassemblyImmediateAssignment.hh.
Referenced by toString().
value_
SimValue DisassemblyImmediateAssignment::value_ private
Value of the immediate.
Definition at line 64 of file DisassemblyImmediateAssignment.hh.
Referenced by toString().
The documentation for this class was generated from the following files:
DisassemblyImmediateAssignment.hh
DisassemblyImmediateAssignment.cc