OpenASIP: LongImmediateUnitState Class Reference
LongImmediateUnitState Class Reference
#include <LongImmediateUnitState.hh>
Classes
struct Item
Public Member Functions
LongImmediateUnitState (int size, int latency, const std::string &name, int width, bool signExtend)
virtual ~LongImmediateUnitState ()
virtual SimValue & registerValue (int index)
virtual void setRegisterValue (int index, const SimValue &value)
virtual LongImmediateRegisterState & immediateRegister (int i)
virtual int immediateRegisterCount () const
virtual void endClock ()
virtual void advanceClock ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
virtual void reset ()
this is called at (re)initialization of the simulation
Private Types
typedef std::queue< Item > ItemQueue
typedef std::vector< LongImmediateRegisterState * > RegisterContainer
typedef std::vector< SimValue > ValueContainer
Private Member Functions
LongImmediateUnitState (const LongImmediateUnitState &)
Copying not allowed.
LongImmediateUnitState & operator= (const LongImmediateUnitState &)
Assignment not allowed.
void clear ()
Private Attributes
int latency_
Latency of LongImmediateUnit.
std::string name_
Name of the unit.
ItemQueue queue_
Queue of register value update requests.
RegisterContainer registers_
Contains all long immediate registers of the unit.
ValueContainer values_
Contains all values of the registers.
unsigned timer_ = 0
Counter to time arrival of immediate values. Note: value is expected to wrap.
Detailed Description
Class that represents the states of long immediate units.
Definition at line 55 of file LongImmediateUnitState.hh.
Member Typedef Documentation
ItemQueue
typedef std::queue<Item> LongImmediateUnitState::ItemQueue private
Definition at line 101 of file LongImmediateUnitState.hh.
RegisterContainer
typedef std::vector<LongImmediateRegisterState*> LongImmediateUnitState::RegisterContainer private
Definition at line 102 of file LongImmediateUnitState.hh.
ValueContainer
typedef std::vector<SimValue> LongImmediateUnitState::ValueContainer private
Definition at line 103 of file LongImmediateUnitState.hh.
Constructor & Destructor Documentation
LongImmediateUnitState() [1/2]
LongImmediateUnitState::LongImmediateUnitState (int size, int latency, const std::string & name, int width, bool signExtend)
Constructor.
Parameters
size Size of the unit.
latency Latency of the unit.
name Name of the unit.
width The bit width of the registers in the unit.
signExtend Whether the values written to the registers should be sign extended.
Definition at line 58 of file LongImmediateUnitState.cc.
                     :
    ClockedState(), latency_(latency), name_(name) {
    for (int i = 0; i < size; i++) {
        registers_.push_back(
            new LongImmediateRegisterState(this, i, width, signExtend));
    }
    SimValue val(width);
    values_.resize(size, val);
}
References registers_, and values_.
~LongImmediateUnitState()
LongImmediateUnitState::~LongImmediateUnitState () virtual
Destructor.
Definition at line 77 of file LongImmediateUnitState.cc.
{
    clear();
}
References clear().
LongImmediateUnitState() [2/2]
LongImmediateUnitState::LongImmediateUnitState (const LongImmediateUnitState &) private
Copying not allowed.
Member Function Documentation
advanceClock()
void LongImmediateUnitState::advanceClock () virtual
Advances clock by one cycle.
Register values are updated. This method is used to simulate the latency of the immediate unit state: register values are not updated immediately in case the latency is greater than zero.
Implements ClockedState.
Reimplemented in NullLongImmediateUnitState.
Definition at line 144 of file LongImmediateUnitState.cc.
{
    timer_++;
    while (!queue_.empty() && queue_.front().arrival_ == timer_) {
        values_[queue_.front().index_] = queue_.front().value_;
        queue_.pop();
    }
}
References queue_, timer_, and values_.
clear()
void LongImmediateUnitState::clear () private
Clears the containers.
Definition at line 85 of file LongImmediateUnitState.cc.
{
    SequenceTools::deleteAllItems(registers_);
    values_.clear();
}
References SequenceTools::deleteAllItems(), registers_, and values_.
Referenced by ~LongImmediateUnitState().
endClock()
void LongImmediateUnitState::endClock () virtual
End of clock cycle.
Nothing is done.
Implements ClockedState.
Reimplemented in NullLongImmediateUnitState.
Definition at line 133 of file LongImmediateUnitState.cc.
{
}
immediateRegister()
LongImmediateRegisterState & LongImmediateUnitState::immediateRegister (int i) virtual
Returns the register of the given index.
Parameters
index Index of the register.
Returns
Register of the given index.
Exceptions
OutOfRange If index is out of range.
Reimplemented in NullLongImmediateUnitState.
Definition at line 160 of file LongImmediateUnitState.cc.
{
    if (i < 0 || i > static_cast<int>(registers_.size()) - 1) {
    string msg = "Index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    return *registers_[i];
}
References __func__, and registers_.
Referenced by ProximRegisterWindow::loadImmediateUnit(), SimProgramBuilder::processInstruction(), and SimProgramBuilder::processSourceTerminal().
immediateRegisterCount()
int LongImmediateUnitState::immediateRegisterCount () const virtual
Returns the count of the registers in the unit.
Returns
The count of the immediate registers.
Reimplemented in NullLongImmediateUnitState.
Definition at line 174 of file LongImmediateUnitState.cc.
{
    return registers_.size();
}
References registers_.
Referenced by ProximIUDetailsCmd::Do(), and ProximRegisterWindow::loadImmediateUnit().
operator=()
LongImmediateUnitState & LongImmediateUnitState::operator= (const LongImmediateUnitState &) private
Assignment not allowed.
registerValue()
SimValue & LongImmediateUnitState::registerValue (int index) virtual
Returns the register value of the given index.
Parameters
index Index of the register.
Returns
Register value of the given index.
Exceptions
OutOfRange If index is out of range.
Reimplemented in NullLongImmediateUnitState.
Definition at line 98 of file LongImmediateUnitState.cc.
{
    if (index < 0 || index > static_cast<int>(values_.size()) - 1) {
        string msg = "Index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    return values_[index];
}
References __func__, and values_.
Referenced by ProximIUDetailsCmd::Do(), and LongImmediateRegisterState::value().
setRegisterValue()
void LongImmediateUnitState::setRegisterValue (int index, const SimValue & value) virtual
Sets the register value.
Parameters
index Index of the register.
value Value to be set.
Exceptions
OutOfRange If index is out of range.
Reimplemented in NullLongImmediateUnitState.
Definition at line 114 of file LongImmediateUnitState.cc.
{
    if (index < 0 || index > static_cast<int>(values_.size()) - 1) {
        string msg = "Index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    if (latency_ == 0) {
        values_[index] = value;
    } else {
        queue_.emplace(value, index, timer_ + latency_);
    }
}
References __func__, latency_, queue_, timer_, and values_.
Referenced by LongImmediateRegisterState::setValue().
Member Data Documentation
latency_
int LongImmediateUnitState::latency_ private
Latency of LongImmediateUnit.
Definition at line 106 of file LongImmediateUnitState.hh.
Referenced by setRegisterValue().
name_
std::string LongImmediateUnitState::name_ private
Name of the unit.
Definition at line 108 of file LongImmediateUnitState.hh.
queue_
ItemQueue LongImmediateUnitState::queue_ private
Queue of register value update requests.
Definition at line 110 of file LongImmediateUnitState.hh.
Referenced by advanceClock(), and setRegisterValue().
registers_
RegisterContainer LongImmediateUnitState::registers_ private
Contains all long immediate registers of the unit.
Definition at line 112 of file LongImmediateUnitState.hh.
Referenced by clear(), immediateRegister(), immediateRegisterCount(), and LongImmediateUnitState().
timer_
unsigned LongImmediateUnitState::timer_ = 0 private
Counter to time arrival of immediate values. Note: value is expected to wrap.
Definition at line 117 of file LongImmediateUnitState.hh.
Referenced by advanceClock(), and setRegisterValue().
values_
ValueContainer LongImmediateUnitState::values_ private
Contains all values of the registers.
Definition at line 114 of file LongImmediateUnitState.hh.
Referenced by advanceClock(), clear(), LongImmediateUnitState(), registerValue(), and setRegisterValue().
The documentation for this class was generated from the following files:
LongImmediateUnitState.hh
LongImmediateUnitState.cc