OpenASIP: CopyComponent Class Reference
CopyComponent Class Reference
#include <CopyComponent.hh>
Public Member Functions
CopyComponent (EditPart *editPart)
~CopyComponent ()
bool Do ()
bool Undo ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * editPart_
Component to copy.
Detailed Description
Command for copying components to the clipboard.
Definition at line 42 of file CopyComponent.hh.
Constructor & Destructor Documentation
CopyComponent()
CopyComponent::CopyComponent (EditPart * editPart)
The Constructor.
Parameters
editPart Function unit to delete.
Definition at line 46 of file CopyComponent.cc.
                                              : editPart_(editPart) {
}
~CopyComponent()
CopyComponent::~CopyComponent ()
The Destructor.
Definition at line 53 of file CopyComponent.cc.
{
}
Member Function Documentation
Do()
bool CopyComponent::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 63 of file CopyComponent.cc.
                  {
    Component* component = dynamic_cast<Component*>(editPart_->model());
    assert (component != NULL);
    ProDeClipboard* clipboard = ProDeClipboard::instance();
    clipboard->setContents(component->saveState(), component->machine());
    return true;
}
References assert, editPart_, ProDeClipboard::instance(), TTAMachine::Component::machine(), EditPart::model(), TTAMachine::Component::saveState(), and ProDeClipboard::setContents().
Undo()
bool CopyComponent::Undo ()
Undoing this command is not possible, returns always false.
Returns
Always false.
Definition at line 78 of file CopyComponent.cc.
                    {
    return false;
}
Member Data Documentation
editPart_
EditPart* CopyComponent::editPart_ private
Component to copy.
Definition at line 52 of file CopyComponent.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
CopyComponent.hh
CopyComponent.cc