OpenASIP: IDF::MachineImplementation Class Reference
IDF::MachineImplementation Class Reference
#include <MachineImplementation.hh>
Classes
struct Parameter
IC/Decoder parameter struct.
Public Member Functions
MachineImplementation ()
MachineImplementation (const ObjectState *state)
virtual ~MachineImplementation ()
std::string sourceIDF () const
std::string icDecoderPluginName () const
bool hasICDecoderPluginName () const
std::string icDecoderPluginFile () const
bool hasICDecoderPluginFile () const
std::string icDecoderHDB () const
bool hasICDecoderHDB () const
std::string decompressorFile () const
bool hasDecompressorFile () const
void setICDecoderPluginName (const std::string &name)
void setICDecoderPluginFile (const std::string &file)
void setICDecoderHDB (const std::string &file)
void setDecompressorFile (const std::string &file)
unsigned icDecoderParameterCount () const
std::string icDecoderParameterName (unsigned param) const
std::string icDecoderParameterValue (const std::string &name) const
std::string icDecoderParameterValue (unsigned param) const
void clearICDecoderParameters ()
void setICDecoderParameter (const std::string &name, const std::string &value)
bool hasFUImplementation (const std::string &unitName) const
bool hasRFImplementation (const std::string &unitName) const
bool hasIUImplementation (const std::string &unitName) const
bool hasBusImplementation (const std::string &busName) const
bool hasSocketImplementation (const std::string &socketName) const
int fuImplementationCount () const
int rfImplementationCount () const
int iuImplementationCount () const
int busImplementationCount () const
int socketImplementationCount () const
FUImplementationLocation & fuImplementation (const std::string &fu) const
RFImplementationLocation & rfImplementation (const std::string &rf) const
RFImplementationLocation & iuImplementation (const std::string &iu) const
BusImplementationLocation & busImplementation (const std::string &bus) const
SocketImplementationLocation & socketImplementation (const std::string &socket) const
FUImplementationLocation & fuImplementation (int index) const
RFImplementationLocation & rfImplementation (int index) const
RFImplementationLocation & iuImplementation (int index) const
BusImplementationLocation & busImplementation (int index) const
SocketImplementationLocation & socketImplementation (int index) const
void addFUImplementation (FUImplementationLocation *implementation)
void addRFImplementation (RFImplementationLocation *implementation)
void addIUImplementation (RFImplementationLocation *implementation)
void addBusImplementation (BusImplementationLocation *implementation)
void addSocketImplementation (SocketImplementationLocation *implementation)
void removeFUImplementation (const std::string &unitName)
void removeRFImplementation (const std::string &unitName)
void removeIUImplementation (const std::string &unitName)
void removeBusImplementation (const std::string &unitName)
void removeSocketImplementation (const std::string &unitName)
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
void makeImplFilesRelative (const std::vector< std::string > &sPaths)
bool checkImplFiles (size_t &missingFiles, size_t &alternativeFiles)
bool isLibraryImplFile (const std::string &path, std::string &resolvedPath)
const std::vector< FUGenerated > & FUGenerations () const
std::vector< FUGenerated > & FUGenerations ()
bool hasFUGeneration (const std::string &name) const
void removeFuGeneration (const std::string &name)
void addFuGeneration (const FUGenerated &fug)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static MachineImplementation * loadFromIDF (const std::string &idfFileName)
Static Public Attributes
static const std::string OSNAME_MACHINE_IMPLEMENTATION
ObjectState name for machine implementation.
static const std::string OSKEY_SOURCE_IDF = "source_idf"
ObjectState attribute name for the source IDF.
static const std::string OSNAME_IC_DECODER_PLUGIN
ObjectState name for the name of the IC/decoder plugin file.
static const std::string OSKEY_IC_DECODER_NAME
ObjectState attribute name for ic&decoder name.
static const std::string OSKEY_IC_DECODER_FILE
ObjectState attribute name for ic&decoder file.
static const std::string OSNAME_IC_DECODER_PARAMETER
ObjectState attribute name for ic&decoder parameter.
static const std::string OSKEY_IC_DECODER_PARAMETER_NAME
ObjectState attribute name for ic&decoder parameter name.
static const std::string OSKEY_IC_DECODER_PARAMETER_VALUE
ObjectState attribute name for ic&decoder parameter value.
static const std::string OSKEY_IC_DECODER_HDB
ObjectState attribute name for ic&decoder HDB.
static const std::string OSKEY_DECOMPRESSOR_FILE
ObjectState attribute key for the name of the decompressor file.
static const std::string OSNAME_FU_GENERATED = "fu_generated"
ObjectState name for FU generations container.
static const std::string OSNAME_FU_IMPLEMENTATIONS
ObjectState name for FU implementation container.
static const std::string OSNAME_RF_IMPLEMENTATIONS
ObjectState name for RF implementation container.
static const std::string OSNAME_IU_IMPLEMENTATIONS
ObjectState name for IU implementation container.
static const std::string OSNAME_BUS_IMPLEMENTATIONS
ObjectState name for bus implementation container.
static const std::string OSNAME_SOCKET_IMPLEMENTATIONS
ObjectState name for socket implementation container.
Private Types
typedef std::vector< UnitImplementationLocation * > ImplementationTable
Vector type for UnitImplementationLocation.
Private Member Functions
bool checkImplFile (const std::vector< std::string > &primarySearchPaths, const std::vector< std::string > &secondarySearchPaths, std::string &file)
bool isLibraryImplFile ()
void makeHDBPathRelative (const std::vector< std::string > &searchPaths, UnitImplementationLocation &implem) const
UnitImplementationLocation * findImplementation (const ImplementationTable &table, const std::string &unitName) const
void ensureIndexValidity (int index, const ImplementationTable &table) const
void clearState ()
Private Attributes
std::vector< FUGenerated > fuGenerated_
Generated FUs.
ImplementationTable fuImplementations_
FU implementations.
ImplementationTable rfImplementations_
RF implementations.
ImplementationTable iuImplementations_
IU implementations.
ImplementationTable busImplementations_
BUS implementations.
ImplementationTable socketImplementations_
SOCKET implementations.
std::string icDecoderPluginName_
Name of the IC/decoder plugin.
std::string icDecoderPluginFile_
Name of the IC/decoder plugin file.
std::string icDecoderHDB_
Name of the HDB of the IC/decoder plugin.
std::string decompressorFile_
Name of the decompressor block file.
std::string sourceIDF_
Absolute path to the source IDF file.
std::vector< Parameter > icDecoderParameters_
IC/decoder plugin parameters.
std::vector< std::string > missingFiles_
Implementation files defined in IDF which cannot be located.
std::vector< std::string > alternativeFiles_
Possible alternative file paths for missing implementation files.
Detailed Description
Represents the implementation of a machine defined in an IDF.
Definition at line 54 of file MachineImplementation.hh.
Member Typedef Documentation
ImplementationTable
typedef std::vector<UnitImplementationLocation*> IDF::MachineImplementation::ImplementationTable private
Vector type for UnitImplementationLocation.
Definition at line 179 of file MachineImplementation.hh.
Constructor & Destructor Documentation
MachineImplementation() [1/2]
IDF::MachineImplementation::MachineImplementation ()
The constructor.
Definition at line 84 of file MachineImplementation.cc.
                                            :
    icDecoderPluginName_(""), icDecoderPluginFile_(""), icDecoderHDB_(""),
    decompressorFile_(""), sourceIDF_("") {
}
MachineImplementation() [2/2]
IDF::MachineImplementation::MachineImplementation (const ObjectState * state)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Definition at line 98 of file MachineImplementation.cc.
    : icDecoderPluginName_(""),
      icDecoderPluginFile_(""),
      icDecoderHDB_(""),
      decompressorFile_(""),
      sourceIDF_("") {
    loadState(state);
}
References loadState().
~MachineImplementation()
IDF::MachineImplementation::~MachineImplementation () virtual
The destructor.
Definition at line 110 of file MachineImplementation.cc.
{
    clearState();
}
References clearState().
Member Function Documentation
addBusImplementation()
void IDF::MachineImplementation::addBusImplementation (BusImplementationLocation * implementation)
Adds the given bus implementation.
Parameters
implementation The implementation to add.
Exceptions
ObjectAlreadyExists If there is an implementation for the same bus already.
InvalidData If the given implementation is registered to another MachineImplementation instance.
Definition at line 596 of file MachineImplementation.cc.
{
    if (hasBusImplementation(implementation->unitName())) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, __func__);
    } else {
        busImplementations_.push_back(implementation);
        implementation->setParent(*this);
    }
}
References __func__, busImplementations_, hasBusImplementation(), and implementation.
Referenced by loadState().
addFuGeneration()
void IDF::MachineImplementation::addFuGeneration (const FUGenerated & fug)
Add fu to generation list.
Parameters
fug FU Generation to add.
Definition at line 1619 of file MachineImplementation.cc.
{
    fuGenerated_.emplace_back(fug);
}
References fuGenerated_.
Referenced by ProGe::ProGeUI::generateIDF().
addFUImplementation()
void IDF::MachineImplementation::addFUImplementation (FUImplementationLocation * implementation)
Adds the given FU implementation.
Parameters
implementation The implementation to add.
Exceptions
ObjectAlreadyExists If there is an implementation for the same FU already.
InvalidData If the given implementation is registered to another MachineImplementation instance.
Definition at line 533 of file MachineImplementation.cc.
{
    if (hasFUImplementation(implementation->unitName())) {
        const string procName = "MachineImplementation::addFUImplementation";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        fuImplementations_.push_back(implementation);
        implementation->setParent(*this);
    }
}
References fuImplementations_, hasFUImplementation(), and implementation.
Referenced by ComponentImplementationSelector::fuImplementations(), ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectFUImplementation(), loadState(), AutoSelectImplementationsDialog::onFind(), and ComponentImplementationSelector::selectFUs().
addIUImplementation()
void IDF::MachineImplementation::addIUImplementation (RFImplementationLocation * implementation)
Adds the given IU implementation.
Parameters
implementation The implementation to add.
Exceptions
ObjectAlreadyExists If there is an implementation for the same IU already.
InvalidData If the given implementation is registered to another MachineImplementation instance.
Definition at line 575 of file MachineImplementation.cc.
{
    if (hasIUImplementation(implementation->unitName())) {
        const string procName = "MachineImplementation::addRFImplementation";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        iuImplementations_.push_back(implementation);
        implementation->setParent(*this);
    }
}
References hasIUImplementation(), implementation, and iuImplementations_.
Referenced by ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectIUImplementation(), ComponentImplementationSelector::iuImplementations(), loadState(), AutoSelectImplementationsDialog::onFind(), and ComponentImplementationSelector::selectIUs().
addRFImplementation()
void IDF::MachineImplementation::addRFImplementation (RFImplementationLocation * implementation)
Adds the given RF implementation.
Parameters
implementation The implementation to add.
Exceptions
ObjectAlreadyExists If there is an implementation for the same RF already.
InvalidData If the given implementation is registered to another MachineImplementation instance.
Definition at line 554 of file MachineImplementation.cc.
{
    if (hasRFImplementation(implementation->unitName())) {
        const string procName = "MachineImplementation::addRFImplementation";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        rfImplementations_.push_back(implementation);
        implementation->setParent(*this);
    }
}
References hasRFImplementation(), implementation, and rfImplementations_.
Referenced by ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectRFImplementation(), loadState(), AutoSelectImplementationsDialog::onFind(), ComponentImplementationSelector::rfImplementations(), and ComponentImplementationSelector::selectRFs().
addSocketImplementation()
void IDF::MachineImplementation::addSocketImplementation (SocketImplementationLocation * implementation)
Adds the given socket implementation.
Parameters
implementation The implementation to add.
Exceptions
ObjectAlreadyExists If there is an implementation for the same socket already.
InvalidData If the given implementation is registered to another MachineImplementation instance.
Definition at line 616 of file MachineImplementation.cc.
{
    if (hasSocketImplementation(implementation->unitName())) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, __func__);
    } else {
        socketImplementations_.push_back(implementation);
        implementation->setParent(*this);
    }
}
References __func__, hasSocketImplementation(), implementation, and socketImplementations_.
Referenced by loadState().
busImplementation() [1/2]
UnitImplementationLocation & IDF::MachineImplementation::busImplementation (const std::string & bus) const
Returns the implementation data of the given bus.
Parameters
bus Name of the bus.
Returns
The implementation data.
Exceptions
InstanceNotFound If there is no implementation defined for the given bus.
Definition at line 420 of file MachineImplementation.cc.
{
    UnitImplementationLocation* impl = findImplementation(
        busImplementations_, bus);
    if (impl == NULL) {
        throw InstanceNotFound(
            __FILE__, __LINE__, __func__,
            "No implementation data found for bus " + bus + ".");
    } else {
        return *impl;
    }
}
References __func__, busImplementations_, and findImplementation().
Referenced by checkImplFiles(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), and saveState().
busImplementation() [2/2]
UnitImplementationLocation & IDF::MachineImplementation::busImplementation (int index) const
Returns the bus implementation at the given position.
Parameters
index The position index.
Returns
The implementation data.
Exceptions
OutOfRange If the index is smaller than 0 or not smaller than the number of bus implementations.
Definition at line 504 of file MachineImplementation.cc.
{
    ensureIndexValidity(index, busImplementations_);
    return *busImplementations_[index];
}
References busImplementations_, and ensureIndexValidity().
busImplementationCount()
int IDF::MachineImplementation::busImplementationCount () const
Returns the number of bus implementations.
Returns
The number of bus implementations.
Definition at line 331 of file MachineImplementation.cc.
{
    return busImplementations_.size();
}
References busImplementations_.
Referenced by checkImplFiles(), makeImplFilesRelative(), and saveState().
checkImplFile()
bool IDF::MachineImplementation::checkImplFile (const std::vector< std::string > & primarySearchPaths, const std::vector< std::string > & secondarySearchPaths, std::string & file) private
Tries to find a file under provided search paths.
If the file cannot be found under primary search paths, it is searched under secondary paths. If an alternative file path is found under secondary paths, it is returned using the string reference parameter.
Parameters
primarySearchPaths Paths where the file is searched first.
secondarySearchPaths Paths where the file is searched after.
file Path to file, might be relative of absolute. The alternative file path is returned in this.
Returns
True if alternative path was placed in the reference parameter.
Definition at line 1224 of file MachineImplementation.cc.
                     {
    if (file == "") {
        return false;
    }
    // Remove tce file specifier.
    if (TCEString(file).startsWith("tce:")) {
        file = TCEString(file).replaceString("tce:", "");
    }
    // return if the file path has already been processed as a missing file
    for (unsigned int i = 0; i < missingFiles_.size(); ++i) {
        if (file.compare(missingFiles_.at(i)) == 0) {
            if (alternativeFiles_.at(i) != "") {
                file = alternativeFiles_.at(i);
                return true;
            } else {
                return false;
            }
        }
    }
    // first search: primary search paths
    try {
        FileSystem::findFileInSearchPaths(primarySearchPaths, file);
        return false;
    } catch (Exception& e) {
        // file was not found
    }
    // second search: secondary search paths (with the plain file name)
    try {
        string alternativePath = FileSystem::findFileInSearchPaths(
            secondarySearchPaths, FileSystem::fileOfPath(file));
        // file was not found, but alternative file path was found
        missingFiles_.push_back(file);
        alternativeFiles_.push_back(alternativePath);
        file = alternativePath;
        return true;
    } catch (Exception& e) {
        // file was not found, and no alternative path was found either
        missingFiles_.push_back(file);
        alternativeFiles_.push_back("");
        return false;
    }
}
References alternativeFiles_, FileSystem::fileOfPath(), FileSystem::findFileInSearchPaths(), missingFiles_, and TCEString::replaceString().
Referenced by checkImplFiles().
checkImplFiles()
bool IDF::MachineImplementation::checkImplFiles (size_t & missingFiles, size_t & alternativeFiles)
Checks that every file defined in IDF exists.
If a file can't be found under current working directory or absolute path, it is searched under default search paths. If the file is found under a default search path, the original file path will be replaced with the found path.
Parameters
missingFiles Amount of missing files is returned using this.
alternativeFiles Amount of alt. files found for missing files.
Returns
True if every file was found locally or from absolute paths.
Definition at line 1066 of file MachineImplementation.cc.
{
    missingFiles_.clear();
    alternativeFiles_.clear();
    // local search paths (current working directory)
    vector<string> localPaths;
    localPaths.push_back(FileSystem::currentWorkingDir());
    // default search paths for different implementation files
    vector<string> defSearchPaths;
    // file that will be searched under search paths
    TCEString filePath;
    // ic&decoder files
    if (hasICDecoderPluginName()) {
        if (hasICDecoderPluginFile()) {
            defSearchPaths = Environment::icDecoderPluginPaths();
            filePath = icDecoderPluginFile_;
            if (isLibraryImplFile(filePath, filePath)) {
                icDecoderPluginFile_ = filePath;
            // try to find file under local or default search paths
            } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
                // found under default search paths, fix the path
                icDecoderPluginFile_ = filePath;
            }
        }
        if (hasICDecoderHDB()) {
            defSearchPaths = Environment::hdbPaths();
            filePath = icDecoderHDB_;
            if (isLibraryImplFile(filePath, filePath)) {
                icDecoderHDB_ = filePath;
                // try to find file under local or default search paths
            } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
                icDecoderHDB_ = filePath;
            }
        }
    }
    // decompressor file
    if (hasDecompressorFile()) {
        defSearchPaths = Environment::decompressorPaths();
        filePath = decompressorFile_;
        if (isLibraryImplFile(filePath, filePath)) {
            decompressorFile_ = filePath;
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            decompressorFile_ = filePath;
        }
    }
    // HDB files
    defSearchPaths = Environment::hdbPaths();
    // FU files
    for (int i = 0; i < fuImplementationCount(); i++) {
        UnitImplementationLocation& impl = fuImplementation(i);
        filePath = impl.hdbFileOriginal();
        if (isLibraryImplFile(filePath, filePath)) {
            impl.setHDBFile(filePath);
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            impl.setHDBFile(filePath);
        }
    }
    // RF files
    for (int i = 0; i < rfImplementationCount(); i++) {
        UnitImplementationLocation& impl = rfImplementation(i);
        filePath = impl.hdbFileOriginal();
        if (isLibraryImplFile(filePath, filePath)) {
            impl.setHDBFile(filePath);
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            impl.setHDBFile(filePath);
        }
    }
    // IU files
    for (int i = 0; i < iuImplementationCount(); i++) {
        UnitImplementationLocation& impl = iuImplementation(i);
        filePath = impl.hdbFileOriginal();
        if (isLibraryImplFile(filePath, filePath)) {
            impl.setHDBFile(filePath);
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            impl.setHDBFile(filePath);
        }
    }
    // bus files
    for (int i = 0; i < busImplementationCount(); i++) {
        UnitImplementationLocation& impl = busImplementation(i);
        filePath = impl.hdbFileOriginal();
        if (isLibraryImplFile(filePath, filePath)) {
            impl.setHDBFile(filePath);
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            impl.setHDBFile(filePath);
        }
    }
    // socket files
    for (int i = 0; i < socketImplementationCount(); i++) {
        UnitImplementationLocation& impl = socketImplementation(i);
        filePath = impl.hdbFileOriginal();
        if (isLibraryImplFile(filePath, filePath)) {
            impl.setHDBFile(filePath);
            // try to find file under local or default search paths
        } else if (checkImplFile(localPaths, defSearchPaths, filePath)) {
            impl.setHDBFile(filePath);
        }
    }
    // check amount of missing files and alternative files that were found
    missingFiles = missingFiles_.size();
    alternativeFiles = 0;
    for (size_t i = 0; i < alternativeFiles_.size(); ++i) {
        if (alternativeFiles_.at(i) != "") {
            ++alternativeFiles;
        }
    }
    // were all the files found under local paths or from absolute paths?
    if (missingFiles_.size() == 0) {
        return true;
    }
    return false;
}
References alternativeFiles_, busImplementation(), busImplementationCount(), checkImplFile(), FileSystem::currentWorkingDir(), decompressorFile_, Environment::decompressorPaths(), fuImplementation(), fuImplementationCount(), hasDecompressorFile(), hasICDecoderHDB(), hasICDecoderPluginFile(), hasICDecoderPluginName(), IDF::UnitImplementationLocation::hdbFileOriginal(), Environment::hdbPaths(), icDecoderHDB_, icDecoderPluginFile_, Environment::icDecoderPluginPaths(), isLibraryImplFile(), iuImplementation(), iuImplementationCount(), missingFiles_, rfImplementation(), rfImplementationCount(), IDF::UnitImplementationLocation::setHDBFile(), socketImplementation(), and socketImplementationCount().
Referenced by ProcessorImplementationWindow::checkImplementationFiles().
clearICDecoderParameters()
void IDF::MachineImplementation::clearICDecoderParameters ()
Clears the ic/decoder parameters.
Definition at line 1512 of file MachineImplementation.cc.
{
    icDecoderParameters_.clear();
}
References icDecoderParameters_.
Referenced by ProcessorImplementationWindow::onBrowseICDecPlugin().
clearState()
void IDF::MachineImplementation::clearState () private
Clears the state of the object.
Definition at line 1352 of file MachineImplementation.cc.
{
    SequenceTools::deleteAllItems(fuImplementations_);
    SequenceTools::deleteAllItems(rfImplementations_);
    SequenceTools::deleteAllItems(iuImplementations_);
    SequenceTools::deleteAllItems(busImplementations_);
    SequenceTools::deleteAllItems(socketImplementations_);
    fuGenerated_.clear();
    icDecoderParameters_.clear();
    icDecoderPluginName_ = "";
    icDecoderPluginFile_ = "";
    icDecoderHDB_ = "";
    decompressorFile_ = "";
    sourceIDF_ = "";
}
References busImplementations_, decompressorFile_, SequenceTools::deleteAllItems(), fuGenerated_, fuImplementations_, icDecoderHDB_, icDecoderParameters_, icDecoderPluginFile_, icDecoderPluginName_, iuImplementations_, rfImplementations_, socketImplementations_, and sourceIDF_.
Referenced by loadState(), and ~MachineImplementation().
decompressorFile()
std::string IDF::MachineImplementation::decompressorFile () const
Returns the absolute path to the the decompressor definition file.
Returns
The absolute path to the decompressor definition file.
Exceptions
FileNotFound If the file is not found in search paths.
Definition at line 205 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::decompressorPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    TCEString expandedPath(decompressorFile_);
    expandedPath.replaceString("tce:", "");
    return FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References decompressorFile_, Environment::decompressorPaths(), FileSystem::directoryOfPath(), FileSystem::findFileInSearchPaths(), TCEString::replaceString(), and sourceIDF_.
Referenced by ProGe::BlockSourceCopier::copyProcessorSpecific(), and ProcessorImplementationWindow::TransferDataToWindow().
ensureIndexValidity()
void IDF::MachineImplementation::ensureIndexValidity (int index, const ImplementationTable & table) const private
Ensures that the given index is valid for getting an instance from the given implementation table.
Parameters
index The index.
table The table.
Exceptions
OutOfRange If the given index is not valid.
Definition at line 1340 of file MachineImplementation.cc.
{
    if (index < 0 || static_cast<size_t>(index) >= table.size()) {
        const string procName = "MachineImplementation::ensureIndexValidity";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
}
Referenced by busImplementation(), fuImplementation(), iuImplementation(), rfImplementation(), and socketImplementation().
findImplementation()
UnitImplementationLocation * IDF::MachineImplementation::findImplementation (const ImplementationTable & table, const std::string & unitName) const private
Finds implementation for the given unit from the given table.
Parameters
table The table to search from.
unitName Name of the unit.
Returns
The correct UnitImplementationLocation instance or NULL if no implementation is found.
Definition at line 1315 of file MachineImplementation.cc.
{
    for (ImplementationTable::const_iterator iter = table.begin();
         iter != table.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            return implementation;
        }
    }
    return NULL;
}
References implementation.
Referenced by busImplementation(), fuImplementation(), hasBusImplementation(), hasFUImplementation(), hasIUImplementation(), hasRFImplementation(), hasSocketImplementation(), iuImplementation(), rfImplementation(), and socketImplementation().
FUGenerations() [1/2]
std::vector< FUGenerated > & IDF::MachineImplementation::FUGenerations ()
Return all FUs to generate.
Definition at line 1580 of file MachineImplementation.cc.
{
    return fuGenerated_;
}
References fuGenerated_.
FUGenerations() [2/2]
const std::vector< FUGenerated > & IDF::MachineImplementation::FUGenerations () const
Return all FUs to generate.
Definition at line 1572 of file MachineImplementation.cc.
{
    return fuGenerated_;
}
References fuGenerated_.
Referenced by ProGe::NetlistGenerator::generate(), ProGe::ProcessorGenerator::generateProcessor(), and makeImplFilesRelative().
fuImplementation() [1/2]
UnitImplementationLocation & IDF::MachineImplementation::fuImplementation (const std::string & fu) const
Returns the implementation data of the given FU.
Parameters
fu Name of the FU.
Returns
The implementation data.
Exceptions
InstanceNotFound If there is no implementation defined for the given FU.
Definition at line 355 of file MachineImplementation.cc.
{
    UnitImplementationLocation* impl = findImplementation(
        fuImplementations_, fu);
    if (impl == NULL) {
        const string procName = "MachineImplementation::fuImplementation";
        throw InstanceNotFound(
            __FILE__, __LINE__, procName,
            "No implementation data found for function unit " + fu + ".");
    } else {
        return *impl;
    }
}
References findImplementation(), and fuImplementations_.
Referenced by IDFValidator::checkFUImplementations(), checkImplFiles(), ProGe::BlockSourceCopier::copyShared(), ProGeTestBenchGenerator::generate(), ProGe::NetlistGenerator::generate(), ProGeScriptGenerator::getBlockOrder(), ProcessorImplementationWindow::handleSelectFUImplementation(), PlatformIntegrator::loadFUExternalPorts(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), saveState(), testUnits(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), ProcessorImplementationWindow::updateFUList(), and ProcessorImplementationWindow::updateImplementationLists().
fuImplementation() [2/2]
UnitImplementationLocation & IDF::MachineImplementation::fuImplementation (int index) const
Returns the FU implementation at the given position.
Parameters
index The position index.
Returns
The implementation data.
Exceptions
OutOfRange If the index is smaller than 0 or not smaller than the number of FU implementations.
Definition at line 462 of file MachineImplementation.cc.
{
    ensureIndexValidity(index, fuImplementations_);
    return *fuImplementations_[index];
}
References ensureIndexValidity(), and fuImplementations_.
fuImplementationCount()
int IDF::MachineImplementation::fuImplementationCount () const
Returns the number of FU implementations.
Returns
The number of FU implementations.
Definition at line 299 of file MachineImplementation.cc.
{
    return fuImplementations_.size();
}
References fuImplementations_.
Referenced by IDFValidator::checkFUImplementations(), checkImplFiles(), ProGe::BlockSourceCopier::copyShared(), ProGeScriptGenerator::getBlockOrder(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), saveState(), and testUnits().
hasBusImplementation()
bool IDF::MachineImplementation::hasBusImplementation (const std::string & busName) const
Tells whether there is an implementation for the given bus defined.
Parameters
busName Name of the bus.
Returns
True if there is an implementation, otherwise false.
Definition at line 272 of file MachineImplementation.cc.
{
    return findImplementation(busImplementations_, busName) != NULL;
}
References busImplementations_, and findImplementation().
Referenced by addBusImplementation(), and CostEstimator::Estimator::longestPath().
hasDecompressorFile()
bool IDF::MachineImplementation::hasDecompressorFile () const
Tells whether the decompressor definition file is given in IDF.
Returns
True if the file is given, otherwise false.
Definition at line 219 of file MachineImplementation.cc.
{
    return decompressorFile_ != "";
}
References decompressorFile_.
Referenced by checkImplFiles(), ProGe::BlockSourceCopier::copyProcessorSpecific(), makeImplFilesRelative(), saveState(), and ProcessorImplementationWindow::TransferDataToWindow().
hasFUGeneration()
bool IDF::MachineImplementation::hasFUGeneration (const std::string & name) const
Return true if fu is to be generated.
Parameters
name Name of the FU Generation to check.
Definition at line 1590 of file MachineImplementation.cc.
{
    for (const auto fug : fuGenerated_) {
        if (fug.name() == name) {
            return true;
        }
    }
    return false;
}
References fuGenerated_.
Referenced by IDFValidator::checkFUImplementations(), and ProGe::ProGeUI::generateIDF().
hasFUImplementation()
bool IDF::MachineImplementation::hasFUImplementation (const std::string & unitName) const
Tells whether there is an implementation for the given FU defined.
Parameters
unitName Name of the FU.
Returns
True if there is an implementation, otherwise false.
Definition at line 231 of file MachineImplementation.cc.
{
    return findImplementation(fuImplementations_, unitName) != NULL;
}
References findImplementation(), and fuImplementations_.
Referenced by addFUImplementation(), IDFValidator::checkFUImplementations(), AutoSelectImplementationsDialog::findFUImplementations(), ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectFUImplementation(), CostEstimator::Estimator::longestPath(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), and ProcessorImplementationWindow::updateImplementationLists().
hasICDecoderHDB()
bool IDF::MachineImplementation::hasICDecoderHDB () const
Returns true in case IC/decoder HDB file is set.
Returns
True in case IC/decoder HDB file is set.
Definition at line 193 of file MachineImplementation.cc.
{
    return icDecoderHDB_ != "";
}
References icDecoderHDB_.
Referenced by checkImplFiles(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), saveState(), and ProcessorImplementationWindow::TransferDataToWindow().
hasICDecoderPluginFile()
bool IDF::MachineImplementation::hasICDecoderPluginFile () const
Returns true in case IC/decoder file is set.
Returns
True in case IC/decoder file is set.
Definition at line 168 of file MachineImplementation.cc.
{
    return icDecoderPluginFile_ != "";
}
References icDecoderPluginFile_.
Referenced by checkImplFiles(), ProGe::ProGeUI::generateIDF(), ProGe::ProGeUI::generateProcessor(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), ProcessorImplementationWindow::onLoadIDF(), saveState(), and ProcessorImplementationWindow::TransferDataToWindow().
hasICDecoderPluginName()
bool IDF::MachineImplementation::hasICDecoderPluginName () const
Returns true in case IC/decoder name is set.
Returns
True in case IC/decoder name is set.
Definition at line 142 of file MachineImplementation.cc.
{
    return icDecoderPluginName_ != "";
}
References icDecoderPluginName_.
Referenced by checkImplFiles(), ProGe::ProGeUI::generateProcessor(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), ProcessorImplementationWindow::onLoadIDF(), saveState(), and ProcessorImplementationWindow::TransferDataToWindow().
hasIUImplementation()
bool IDF::MachineImplementation::hasIUImplementation (const std::string & unitName) const
Tells whether there is an implementation for the given IU defined.
Parameters
unitName Name of the IU.
Returns
True if there is an implementation, otherwise false.
Definition at line 259 of file MachineImplementation.cc.
{
    return findImplementation(iuImplementations_, unitName) != NULL;
}
References findImplementation(), and iuImplementations_.
Referenced by addIUImplementation(), IDFValidator::checkIUImplementations(), AutoSelectImplementationsDialog::findIUImplementations(), ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectIUImplementation(), CostEstimator::Estimator::longestPath(), and ProcessorImplementationWindow::updateImplementationLists().
hasRFImplementation()
bool IDF::MachineImplementation::hasRFImplementation (const std::string & unitName) const
Tells whether there is an implementation for the given RF defined.
Parameters
unitName Name of the RF.
Returns
True if there is an implementation, otherwise false.
Definition at line 245 of file MachineImplementation.cc.
{
    return findImplementation(rfImplementations_, unitName) != NULL;
}
References findImplementation(), and rfImplementations_.
Referenced by addRFImplementation(), IDFValidator::checkRFImplementations(), AutoSelectImplementationsDialog::findRFImplementations(), ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::handleSelectRFImplementation(), CostEstimator::Estimator::longestPath(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), CostEstimator::Estimator::totalEnergyOfRegisterFiles(), and ProcessorImplementationWindow::updateImplementationLists().
hasSocketImplementation()
bool IDF::MachineImplementation::hasSocketImplementation (const std::string & socketName) const
Tells whether there is an implementation for the given socket defined.
Parameters
socketName Name of the IU.
Returns
True if there is an implementation, otherwise false.
Definition at line 286 of file MachineImplementation.cc.
{
    return findImplementation(socketImplementations_, socketName) != NULL;
}
References findImplementation(), and socketImplementations_.
Referenced by addSocketImplementation(), and CostEstimator::Estimator::longestPath().
icDecoderHDB()
std::string IDF::MachineImplementation::icDecoderHDB () const
Returns the absolute path to the IC/decoder HDB file.
Returns
the absolute path to the IC/decoder HDB file.
Exceptions
FileNotFound If the file is not found in search paths.
Definition at line 179 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::hdbPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    TCEString expandedPath(icDecoderHDB_);
    expandedPath.replaceString("tce:", "");
    return FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References FileSystem::directoryOfPath(), FileSystem::findFileInSearchPaths(), Environment::hdbPaths(), icDecoderHDB_, TCEString::replaceString(), and sourceIDF_.
Referenced by DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICDelayOfPath(), DefaultICDecoderEstimator::estimateICEnergy(), and ProcessorImplementationWindow::TransferDataToWindow().
icDecoderParameterCount()
unsigned IDF::MachineImplementation::icDecoderParameterCount () const
Returns number of ic&decoder plugin parameters defined.
Definition at line 1371 of file MachineImplementation.cc.
{
    return icDecoderParameters_.size();
}
References icDecoderParameters_.
Referenced by ProGe::ProGeUI::generateIDF(), and ProGe::ProGeUI::generateProcessor().
icDecoderParameterName()
std::string IDF::MachineImplementation::icDecoderParameterName (unsigned param) const
Returns name of the ic/decoder parameter with the given index.
Parameters
param Index of the parameter.
Returns
Name of the parameter.
Definition at line 1382 of file MachineImplementation.cc.
{
    if (param >= icDecoderParameters_.size()) {
        const string procName =
            "MachineImplementation::icDecoderParameterName";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return icDecoderParameters_[param].name;
}
References icDecoderParameters_.
Referenced by ProGe::ProGeUI::generateProcessor().
icDecoderParameterValue() [1/2]
std::string IDF::MachineImplementation::icDecoderParameterValue (const std::string & name) const
Returns value of the ic/decoder parameter with the given name.
Parameters
name Name of the parameter.
Returns
Value of the parameter.
Definition at line 1415 of file MachineImplementation.cc.
{
    std::vector<Parameter>::const_iterator iter =
        icDecoderParameters_.begin();
    for (; iter != icDecoderParameters_.end(); iter++) {
        if ((*iter).name == name) {
            return (*iter).value;
        }
    }
    // Parameter value not defined.
    return "";
}
References icDecoderParameters_.
Referenced by AlmaIFIntegrator::AlmaIFIntegrator(), ProGeTestBenchGenerator::generate(), ProGe::ProGeUI::generateProcessor(), ProcessorImplementationWindow::TransferDataToWindow(), and ProGe::TestBenchBlock::write().
icDecoderParameterValue() [2/2]
std::string IDF::MachineImplementation::icDecoderParameterValue (unsigned param) const
Returns value of the ic/decoder parameter with the given index.
Parameters
param Index of the parameter.
Returns
Value of the parameter.
Definition at line 1399 of file MachineImplementation.cc.
{
    if (param >= icDecoderParameters_.size()) {
        const string procName = "MachineImplementation::icDecoderParamterName";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return icDecoderParameters_[param].value;
}
References icDecoderParameters_.
icDecoderPluginFile()
std::string IDF::MachineImplementation::icDecoderPluginFile () const
Returns the absolute path to the IC/decoder plugin file given in IDF.
Returns
The absolute path to the IC/decoder plugin file.
Exceptions
FileNotFound If the file is not found in search paths.
Definition at line 153 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::icDecoderPluginPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    TCEString expandedPath(icDecoderPluginFile_);
    expandedPath.replaceString("tce:", "");
    expandedPath = FileSystem::expandTilde(expandedPath);
    return FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References FileSystem::directoryOfPath(), FileSystem::expandTilde(), FileSystem::findFileInSearchPaths(), icDecoderPluginFile_, Environment::icDecoderPluginPaths(), TCEString::replaceString(), and sourceIDF_.
Referenced by ProGe::ProGeUI::generateProcessor(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), CostEstimator::Estimator::longestPath(), ProcessorImplementationWindow::onLoadIDF(), and ProcessorImplementationWindow::TransferDataToWindow().
icDecoderPluginName()
std::string IDF::MachineImplementation::icDecoderPluginName () const
Returns the name of the IC/decoder plugin.
Returns
The name of the IC/decoder plugin.
Definition at line 132 of file MachineImplementation.cc.
{
    return icDecoderPluginName_;
}
References icDecoderPluginName_.
Referenced by ProGe::ProGeUI::generateProcessor(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), CostEstimator::Estimator::longestPath(), ProcessorImplementationWindow::onLoadIDF(), saveState(), and ProcessorImplementationWindow::TransferDataToWindow().
isLibraryImplFile() [1/2]
bool IDF::MachineImplementation::isLibraryImplFile () private
Referenced by checkImplFiles().
isLibraryImplFile() [2/2]
bool IDF::MachineImplementation::isLibraryImplFile (const std::string & path, std::string & resolvedPath)
Returns true if the given file is a library file of TCE.
If the file is a TCE library file, its absolute absolute path returned via reference.
Parameters
path The file path that is relative or absolute.
resolvedPath The resolved absolute path.
Returns
True, if the file is TCE library file. Otherwise, false.
Definition at line 1542 of file MachineImplementation.cc.
{
    TCEString toSearched(path);
    toSearched.replaceString("tce:", "");
    std::vector<std::string> defaultPaths;
    std::vector<std::string> tmp = Environment::hdbPaths(true);
    defaultPaths.insert(defaultPaths.end(), tmp.begin(), tmp.end());
    tmp = Environment::icDecoderPluginPaths(true);
    defaultPaths.insert(defaultPaths.end(), tmp.begin(), tmp.end());
    tmp = Environment::decompressorPaths(true);
    defaultPaths.insert(defaultPaths.end(), tmp.begin(), tmp.end());
    try {
        resolvedPath = FileSystem::findFileInSearchPaths(
            defaultPaths, toSearched);
        return true;
    } catch (Exception& e) {
        // file was not found
    }
    return false;
}
References Environment::decompressorPaths(), FileSystem::findFileInSearchPaths(), Environment::hdbPaths(), Environment::icDecoderPluginPaths(), and TCEString::replaceString().
iuImplementation() [1/2]
UnitImplementationLocation & IDF::MachineImplementation::iuImplementation (const std::string & iu) const
Returns the implementation data of the given IU.
Parameters
iu Name of the IU.
Returns
The implementation data.
Exceptions
InstanceNotFound If there is no implementation defined for the given IU.
Definition at line 399 of file MachineImplementation.cc.
{
    UnitImplementationLocation* impl = findImplementation(
        iuImplementations_, iu);
    if (impl == NULL) {
        throw InstanceNotFound(
            __FILE__, __LINE__, __func__,
            "No implementation data found for immediate unit " + iu + ".");
    } else {
        return *impl;
    }
}
References __func__, findImplementation(), and iuImplementations_.
Referenced by checkImplFiles(), IDFValidator::checkIUImplementations(), ProGe::ProcessorGenerator::checkIULatencies(), ProGe::BlockSourceCopier::copyShared(), ProGe::NetlistGenerator::generate(), ProcessorImplementationWindow::handleSelectIUImplementation(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), saveState(), and ProcessorImplementationWindow::updateImplementationLists().
iuImplementation() [2/2]
UnitImplementationLocation & IDF::MachineImplementation::iuImplementation (int index) const
Returns the IU implementation at the given position.
Parameters
index The position index.
Returns
The implementation data.
Exceptions
OutOfRange If the index is smaller than 0 or not smaller than the number of IU implementations.
Definition at line 490 of file MachineImplementation.cc.
{
    ensureIndexValidity(index, iuImplementations_);
    return *iuImplementations_[index];
}
References ensureIndexValidity(), and iuImplementations_.
iuImplementationCount()
int IDF::MachineImplementation::iuImplementationCount () const
Returns the number of IU implementations.
Returns
The number of IU implementations.
Definition at line 321 of file MachineImplementation.cc.
{
    return iuImplementations_.size();
}
References iuImplementations_.
Referenced by checkImplFiles(), IDFValidator::checkIUImplementations(), ProGe::BlockSourceCopier::copyShared(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), and saveState().
loadFromIDF()
MachineImplementation * IDF::MachineImplementation::loadFromIDF (const std::string & idfFileName) static
Loads a MachineImplementation from the given IDF file.
Parameters
idfFileName The name of the file to load the IDF from.
Returns
A machine implementation instance.
Exceptions
Exception In case some error occured.
Definition at line 1524 of file MachineImplementation.cc.
{
    IDFSerializer serializer;
    serializer.setSourceFile(idfFileName);
    return serializer.readMachineImplementation();
}
References IDF::IDFSerializer::readMachineImplementation(), and XMLSerializer::setSourceFile().
Referenced by Evaluate::createConfig(), MinimalOpSet::createConfig(), and main().
loadState()
void IDF::MachineImplementation::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state The given ObjectState tree.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Implements Serializable.
Definition at line 762 of file MachineImplementation.cc.
{
    const string procName = "MachineImplementation::loadState";
    if (state->name() != OSNAME_MACHINE_IMPLEMENTATION) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    clearState();
    if (state->hasChild(OSNAME_IC_DECODER_PLUGIN)) {
        ObjectState* icdecState = state->childByName(OSNAME_IC_DECODER_PLUGIN);
        icDecoderPluginName_ =
            icdecState->stringAttribute(OSKEY_IC_DECODER_NAME);
        icDecoderPluginFile_ =
            icdecState->stringAttribute(OSKEY_IC_DECODER_FILE);
        if (icdecState->hasAttribute(OSKEY_IC_DECODER_HDB)) {
            icDecoderHDB_ = icdecState->stringAttribute(OSKEY_IC_DECODER_HDB);
        }
        // Load ic/decoder plugin parameters.
        for (int i = 0; i < icdecState->childCount(); i++) {
            ObjectState* parameterState = icdecState->child(i);
            if (parameterState->name() != OSNAME_IC_DECODER_PARAMETER) {
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName);
            }
            std::string name = parameterState->stringAttribute(
                OSKEY_IC_DECODER_PARAMETER_NAME);
            std::string value = parameterState->stringAttribute(
                OSKEY_IC_DECODER_PARAMETER_VALUE);
            Parameter parameter = { name, value };
            icDecoderParameters_.push_back(parameter);
        }
    }
    if (state->hasAttribute(OSKEY_DECOMPRESSOR_FILE)) {
        decompressorFile_ = state->stringAttribute(OSKEY_DECOMPRESSOR_FILE);
    }
    ObjectState* fuGenerate = state->childByName(OSNAME_FU_GENERATED);
    for (int i = 0; i < fuGenerate->childCount(); i++) {
        ObjectState* child = fuGenerate->child(i);
        FUGenerated newfug;
        newfug.loadState(child);
        fuGenerated_.emplace_back(newfug);
    }
    try {
        sourceIDF_ = state->stringAttribute(OSKEY_SOURCE_IDF);
        ObjectState* fuImplementations = state->childByName(
            OSNAME_FU_IMPLEMENTATIONS);
        ObjectState* rfImplementations = state->childByName(
            OSNAME_RF_IMPLEMENTATIONS);
        ObjectState* iuImplementations = state->childByName(
            OSNAME_IU_IMPLEMENTATIONS);
        ObjectState* busImplementations = state->childByName(
            OSNAME_BUS_IMPLEMENTATIONS);
        ObjectState* socketImplementations = state->childByName(
            OSNAME_SOCKET_IMPLEMENTATIONS);
        for (int i = 0; i < fuImplementations->childCount(); i++) {
            ObjectState* child = fuImplementations->child(i);
            addFUImplementation(new UnitImplementationLocation(child));
        }
        for (int i = 0; i < rfImplementations->childCount(); i++) {
            ObjectState* child = rfImplementations->child(i);
            addRFImplementation(new UnitImplementationLocation(child));
        }
        for (int i = 0; i < iuImplementations->childCount(); i++) {
            ObjectState* child = iuImplementations->child(i);
            addIUImplementation(new UnitImplementationLocation(child));
        }
        for (int i = 0; i < busImplementations->childCount(); i++) {
            ObjectState* child = busImplementations->child(i);
            addBusImplementation(new UnitImplementationLocation(child));
        }
        for (int i = 0; i < socketImplementations->childCount(); i++) {
            ObjectState* child = socketImplementations->child(i);
            addSocketImplementation(new UnitImplementationLocation(child));
        }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References addBusImplementation(), addFUImplementation(), addIUImplementation(), addRFImplementation(), addSocketImplementation(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), clearState(), decompressorFile_, Exception::errorMessage(), fuGenerated_, ObjectState::hasAttribute(), ObjectState::hasChild(), icDecoderHDB_, icDecoderParameters_, icDecoderPluginFile_, icDecoderPluginName_, IDF::FUGenerated::loadState(), ObjectState::name(), OSKEY_DECOMPRESSOR_FILE, OSKEY_IC_DECODER_FILE, OSKEY_IC_DECODER_HDB, OSKEY_IC_DECODER_NAME, OSKEY_IC_DECODER_PARAMETER_NAME, OSKEY_IC_DECODER_PARAMETER_VALUE, OSKEY_SOURCE_IDF, OSNAME_BUS_IMPLEMENTATIONS, OSNAME_FU_GENERATED, OSNAME_FU_IMPLEMENTATIONS, OSNAME_IC_DECODER_PARAMETER, OSNAME_IC_DECODER_PLUGIN, OSNAME_IU_IMPLEMENTATIONS, OSNAME_MACHINE_IMPLEMENTATION, OSNAME_RF_IMPLEMENTATIONS, OSNAME_SOCKET_IMPLEMENTATIONS, sourceIDF_, and ObjectState::stringAttribute().
Referenced by DSDBManager::implementation(), MachineImplementation(), and ProcessorImplementationWindow::onLoadIDF().
makeHDBPathRelative()
void IDF::MachineImplementation::makeHDBPathRelative (const std::vector< std::string > & searchPaths, UnitImplementationLocation & implem) const private
Tries to find a relative path for an HDB file.
If a relative path is found under any of the search paths, the first match is saved. In case the HDB file path is invalid, the path field is left empty.
Parameters
searchPaths Search for relative paths is done under these paths.
implem Object containing a file path, which points to an HDB file.
Definition at line 1288 of file MachineImplementation.cc.
{
    try {
        string filePath = implem.hdbFile();
        string relPath;
        if (FileSystem::makeRelativePath(searchPaths, filePath, relPath)) {
            implem.setHDBFile(relPath);
        } else if (FileSystem::makeRelativePath(Environment::hdbPaths(true),
                filePath, relPath)) {
            implem.setHDBFile(std::string("tce:") + relPath);
        }
    } catch (FileNotFound& e) {
        implem.setHDBFile("");
    }
}
References IDF::UnitImplementationLocation::hdbFile(), Environment::hdbPaths(), FileSystem::makeRelativePath(), and IDF::UnitImplementationLocation::setHDBFile().
Referenced by makeImplFilesRelative().
makeImplFilesRelative()
void IDF::MachineImplementation::makeImplFilesRelative (const std::vector< std::string > & sPaths)
Changes file paths in machine implementation to relative file paths.
Tries to find relative file paths under provided search paths.
Parameters
sPaths Search paths, used for finding relative paths.
Definition at line 967 of file MachineImplementation.cc.
{
    // ic&decoder files
    if (hasICDecoderPluginName()) {
        if (hasICDecoderPluginFile()) {
            string filePath = icDecoderPluginFile_;
            string relPath;
            if (FileSystem::makeRelativePath(sPaths, filePath, relPath)) {
                icDecoderPluginFile_ = relPath;
            } else if (FileSystem::makeRelativePath(
                    Environment::icDecoderPluginPaths(true),
                    filePath, relPath)) {
                icDecoderPluginFile_ = std::string("tce:") + relPath;
            }
        }
        if (hasICDecoderHDB()) {
            string filePath = icDecoderHDB_;
            string relPath;
            if (FileSystem::makeRelativePath(sPaths, filePath, relPath)) {
                icDecoderHDB_ = relPath;
            } else if (FileSystem::makeRelativePath(
                    Environment::decompressorPaths(true), filePath, relPath)) {
                icDecoderHDB_ = std::string("tce:") + relPath;
            }
        }
    }
    // decompressor file
    if (hasDecompressorFile()) {
        string filePath = decompressorFile_;
        string relPath;
        if (FileSystem::makeRelativePath(sPaths, filePath, relPath)) {
            decompressorFile_ = relPath;
        } else if (FileSystem::makeRelativePath(
                Environment::decompressorPaths(), filePath, relPath)) {
            decompressorFile_ = std::string("tce:") + relPath;
        }
    }
    // FU files
    for (int i = 0; i < fuImplementationCount(); i++) {
        UnitImplementationLocation& impl = fuImplementation(i);
        makeHDBPathRelative(sPaths, impl);
    }
    // RF files
    for (int i = 0; i < rfImplementationCount(); i++) {
        UnitImplementationLocation& impl = rfImplementation(i);
        makeHDBPathRelative(sPaths, impl);
    }
    // IU files
    for (int i = 0; i < iuImplementationCount(); i++) {
        UnitImplementationLocation& impl = iuImplementation(i);
        makeHDBPathRelative(sPaths, impl);
    }
    // bus files
    for (int i = 0; i < busImplementationCount(); i++) {
        UnitImplementationLocation& impl = busImplementation(i);
        makeHDBPathRelative(sPaths, impl);
    }
    // socket files
    for (int i = 0; i < socketImplementationCount(); i++) {
        UnitImplementationLocation& impl = socketImplementation(i);
        makeHDBPathRelative(sPaths, impl);
    }
    // Generated FUs and their operations.
    for (auto&& fug : FUGenerations()) {
        for (auto&& op : fug.operations()) {
            std::string& hdb = op.hdb;
            std::string rel;
            if (FileSystem::makeRelativePath(sPaths, hdb, rel)) {
                hdb = rel;
            } else if (FileSystem::makeRelativePath(
                           Environment::hdbPaths(true), hdb, rel)) {
                hdb = "tce:" + rel;
            }
        }
    }
}
References busImplementation(), busImplementationCount(), decompressorFile_, Environment::decompressorPaths(), FUGenerations(), fuImplementation(), fuImplementationCount(), hasDecompressorFile(), hasICDecoderHDB(), hasICDecoderPluginFile(), hasICDecoderPluginName(), Environment::hdbPaths(), icDecoderHDB_, icDecoderPluginFile_, Environment::icDecoderPluginPaths(), iuImplementation(), iuImplementationCount(), makeHDBPathRelative(), FileSystem::makeRelativePath(), rfImplementation(), rfImplementationCount(), socketImplementation(), and socketImplementationCount().
Referenced by ProcessorImplementationWindow::doSaveIDF().
removeBusImplementation()
void IDF::MachineImplementation::removeBusImplementation (const std::string & unitName)
Removes the bus implementation with given name.
Parameters
unitName Name of the implementation to remove.
Exceptions
InstanceNotFound If there is no implementation defined for the given bus.
Definition at line 709 of file MachineImplementation.cc.
{
    bool removed = false;
    for (
        ImplementationTable::iterator iter = busImplementations_.begin();
        iter != busImplementations_.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            busImplementations_.erase(iter);
            removed = true;
            break;
        }
    }
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, busImplementations_, and implementation.
Referenced by MinimizeMachine::minimizeBuses().
removeFuGeneration()
void IDF::MachineImplementation::removeFuGeneration (const std::string & name)
Remove fu from generation list.
Parameters
name Name of the FU Generation to remove.
Definition at line 1605 of file MachineImplementation.cc.
{
    fuGenerated_.erase(
        std::remove_if(
            fuGenerated_.begin(), fuGenerated_.end(),
            [name](FUGenerated& fu) { return fu.name() == name; }),
        fuGenerated_.end());
}
References fuGenerated_.
removeFUImplementation()
void IDF::MachineImplementation::removeFUImplementation (const std::string & unitName)
Removes the FU implementation with given name.
Parameters
unitName Name of the implementation to remove.
Exceptions
InstanceNotFound If there is no implementation defined for the given FU.
Definition at line 634 of file MachineImplementation.cc.
{
    bool removed = false;
    for (ImplementationTable::iterator iter = fuImplementations_.begin();
         iter != fuImplementations_.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            fuImplementations_.erase(iter);
            removed = true;
            break;
        }
    }
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, fuImplementations_, and implementation.
Referenced by RemoveUnconnectedComponents::explore(), and IDFValidator::removeUnknownImplementations().
removeIUImplementation()
void IDF::MachineImplementation::removeIUImplementation (const std::string & unitName)
Removes the IU implementation with given name.
Parameters
unitName Name of the implementation to remove.
Exceptions
InstanceNotFound If there is no implementation defined for the given IU.
Definition at line 684 of file MachineImplementation.cc.
{
    bool removed = false;
    for (ImplementationTable::iterator iter = iuImplementations_.begin();
         iter != iuImplementations_.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            iuImplementations_.erase(iter);
            removed = true;
            break;
        }
    }
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, implementation, and iuImplementations_.
Referenced by IDFValidator::removeUnknownImplementations().
removeRFImplementation()
void IDF::MachineImplementation::removeRFImplementation (const std::string & unitName)
Removes the RF implementation with given name.
Parameters
unitName Name of the implementation to remove.
Exceptions
InstanceNotFound If there is no implementation defined for the given RF.
Definition at line 659 of file MachineImplementation.cc.
{
    bool removed = false;
    for (ImplementationTable::iterator iter = rfImplementations_.begin();
         iter != rfImplementations_.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            rfImplementations_.erase(iter);
            removed = true;
            break;
        }
    }
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, implementation, and rfImplementations_.
Referenced by RemoveUnconnectedComponents::explore(), and IDFValidator::removeUnknownImplementations().
removeSocketImplementation()
void IDF::MachineImplementation::removeSocketImplementation (const std::string & unitName)
Removes the socket implementation with given name.
Parameters
unitName Name of the implementation to remove.
Exceptions
InstanceNotFound If there is no implementation defined for the given socket.
Definition at line 735 of file MachineImplementation.cc.
{
    bool removed = false;
    for (
        ImplementationTable::iterator iter =
            socketImplementations_.begin();
        iter != socketImplementations_.end(); iter++) {
        UnitImplementationLocation* implementation = *iter;
        if (implementation->unitName() == unitName) {
            socketImplementations_.erase(iter);
            removed = true;
            break;
        }
    }
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, implementation, and socketImplementations_.
rfImplementation() [1/2]
UnitImplementationLocation & IDF::MachineImplementation::rfImplementation (const std::string & rf) const
Returns the implementation data of the given RF.
Parameters
rf Name of the RF.
Returns
The implementation data.
Exceptions
InstanceNotFound If there is no implementation defined for the given RF.
Definition at line 377 of file MachineImplementation.cc.
{
    UnitImplementationLocation* impl = findImplementation(
        rfImplementations_, rf);
    if (impl == NULL) {
        const string procName = "MachineImplementation::rfImplementation";
        throw InstanceNotFound(
            __FILE__, __LINE__, procName,
            "No implementation data found for register file " + rf + ".");
    } else {
        return *impl;
    }
}
References findImplementation(), and rfImplementations_.
Referenced by checkImplFiles(), IDFValidator::checkRFImplementations(), ProGe::BlockSourceCopier::copyShared(), ProGe::NetlistGenerator::generate(), ProGeScriptGenerator::getBlockOrder(), ProcessorImplementationWindow::handleSelectRFImplementation(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), saveState(), testUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), CostEstimator::Estimator::totalEnergyOfRegisterFiles(), ProcessorImplementationWindow::updateImplementationLists(), and ProcessorImplementationWindow::updateRFList().
rfImplementation() [2/2]
UnitImplementationLocation & IDF::MachineImplementation::rfImplementation (int index) const
Returns the RF implementation at the given position.
Parameters
index The position index.
Returns
The implementation data.
Exceptions
OutOfRange If the index is smaller than 0 or not smaller than the number of RF implementations.
Definition at line 476 of file MachineImplementation.cc.
{
    ensureIndexValidity(index, rfImplementations_);
    return *rfImplementations_[index];
}
References ensureIndexValidity(), and rfImplementations_.
rfImplementationCount()
int IDF::MachineImplementation::rfImplementationCount () const
Returns the number of RF implementations.
Returns
The number of RF implementations.
Definition at line 310 of file MachineImplementation.cc.
{
    return rfImplementations_.size();
}
References rfImplementations_.
Referenced by checkImplFiles(), IDFValidator::checkRFImplementations(), ProGe::BlockSourceCopier::copyShared(), ProGeScriptGenerator::getBlockOrder(), makeImplFilesRelative(), IDFValidator::removeUnknownImplementations(), saveState(), and testUnits().
saveState()
ObjectState * IDF::MachineImplementation::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 862 of file MachineImplementation.cc.
{
    ObjectState* state = new ObjectState(OSNAME_MACHINE_IMPLEMENTATION);
    state->setAttribute(OSKEY_SOURCE_IDF, sourceIDF_);
    // add ic&decoder data
    if (hasICDecoderPluginName()) {
        ObjectState* icdecState = new ObjectState(OSNAME_IC_DECODER_PLUGIN);
        if (hasICDecoderPluginName()) {
            icdecState->setAttribute(
                OSKEY_IC_DECODER_NAME, icDecoderPluginName());
        }
        if (hasICDecoderPluginFile()) {
            icdecState->setAttribute(
                OSKEY_IC_DECODER_FILE, icDecoderPluginFile_);
        }
        if (hasICDecoderHDB()) {
            icdecState->setAttribute(
                OSKEY_IC_DECODER_HDB, icDecoderHDB_);
        }
        std::vector<Parameter>::const_iterator iter =
            icDecoderParameters_.begin();
        // add ic&decoder parameters
        for (; iter != icDecoderParameters_.end(); iter++) {
            ObjectState* parameterState =
                new ObjectState(OSNAME_IC_DECODER_PARAMETER);
            parameterState->setAttribute(
                OSKEY_IC_DECODER_PARAMETER_NAME, (*iter).name);
            parameterState->setAttribute(
                OSKEY_IC_DECODER_PARAMETER_VALUE, (*iter).value);
            icdecState->addChild(parameterState);
        }
        state->addChild(icdecState);
    }
    // add decompressor file data
    if (hasDecompressorFile()) {
        state->setAttribute(OSKEY_DECOMPRESSOR_FILE, decompressorFile_);
    }
    // add Generated FUs.
    ObjectState* fuGenerated = new ObjectState(OSNAME_FU_GENERATED);
    state->addChild(fuGenerated);
    for (const auto fug : fuGenerated_) {
        fuGenerated->addChild(fug.saveState());
    }
    // add FU implementations
    ObjectState* fuImplementations = new ObjectState(
        OSNAME_FU_IMPLEMENTATIONS);
    state->addChild(fuImplementations);
    for (int i = 0; i < fuImplementationCount(); i++) {
        UnitImplementationLocation& impl = fuImplementation(i);
        fuImplementations->addChild(impl.saveState());
    }
    // add RF implementations
    ObjectState* rfImplementations = new ObjectState(
        OSNAME_RF_IMPLEMENTATIONS);
    state->addChild(rfImplementations);
    for (int i = 0; i < rfImplementationCount(); i++) {
        UnitImplementationLocation& impl = rfImplementation(i);
        rfImplementations->addChild(impl.saveState());
    }
    // add IU implementations
    ObjectState* iuImplementations = new ObjectState(
        OSNAME_IU_IMPLEMENTATIONS);
    state->addChild(iuImplementations);
    for (int i = 0; i < iuImplementationCount(); i++) {
        UnitImplementationLocation& impl = iuImplementation(i);
        iuImplementations->addChild(impl.saveState());
    }
    // add bus implementations
    ObjectState* busImplementations = new ObjectState(
        OSNAME_BUS_IMPLEMENTATIONS);
    state->addChild(busImplementations);
    for (int i = 0; i < busImplementationCount(); i++) {
        UnitImplementationLocation& impl = busImplementation(i);
        busImplementations->addChild(impl.saveState());
    }
    // add socket implementations
    ObjectState* socketImplementations = new ObjectState(
        OSNAME_SOCKET_IMPLEMENTATIONS);
    state->addChild(socketImplementations);
    for (int i = 0; i < socketImplementationCount(); i++) {
        UnitImplementationLocation& impl = socketImplementation(i);
        socketImplementations->addChild(impl.saveState());
    }
    return state;
}
References ObjectState::addChild(), busImplementation(), busImplementationCount(), decompressorFile_, fuGenerated_, fuImplementation(), fuImplementationCount(), hasDecompressorFile(), hasICDecoderHDB(), hasICDecoderPluginFile(), hasICDecoderPluginName(), icDecoderHDB_, icDecoderParameters_, icDecoderPluginFile_, icDecoderPluginName(), iuImplementation(), iuImplementationCount(), OSKEY_DECOMPRESSOR_FILE, OSKEY_IC_DECODER_FILE, OSKEY_IC_DECODER_HDB, OSKEY_IC_DECODER_NAME, OSKEY_IC_DECODER_PARAMETER_NAME, OSKEY_IC_DECODER_PARAMETER_VALUE, OSKEY_SOURCE_IDF, OSNAME_BUS_IMPLEMENTATIONS, OSNAME_FU_GENERATED, OSNAME_FU_IMPLEMENTATIONS, OSNAME_IC_DECODER_PARAMETER, OSNAME_IC_DECODER_PLUGIN, OSNAME_IU_IMPLEMENTATIONS, OSNAME_MACHINE_IMPLEMENTATION, OSNAME_RF_IMPLEMENTATIONS, OSNAME_SOCKET_IMPLEMENTATIONS, rfImplementation(), rfImplementationCount(), IDF::UnitImplementationLocation::saveState(), ObjectState::setAttribute(), socketImplementation(), socketImplementationCount(), and sourceIDF_.
Referenced by DSDBManager::addImplementation(), ProGe::ProGeUI::loadMachineImplementation(), ProcessorImplementationWindow::onLoadIDF(), and IDF::IDFSerializer::writeMachineImplementation().
setDecompressorFile()
void IDF::MachineImplementation::setDecompressorFile (const std::string & file)
Sets the decompressor block file.
Parameters
file Full path to the decompressor block file.
Definition at line 1502 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::decompressorPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    decompressorFile_ = FileSystem::findFileInSearchPaths(paths, file);
}
References decompressorFile_, Environment::decompressorPaths(), FileSystem::directoryOfPath(), FileSystem::findFileInSearchPaths(), and sourceIDF_.
Referenced by ProcessorImplementationWindow::onBrowseDecompressor().
setICDecoderHDB()
void IDF::MachineImplementation::setICDecoderHDB (const std::string & file)
Sets the ic/decoder HDB file.
Parameters
file Full path of the ic/decoder HDB file.
Definition at line 1488 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::hdbPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    string expandedPath = FileSystem::expandTilde(file);
    icDecoderHDB_ =
        FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References FileSystem::directoryOfPath(), FileSystem::expandTilde(), FileSystem::findFileInSearchPaths(), Environment::hdbPaths(), icDecoderHDB_, and sourceIDF_.
Referenced by ProcessorImplementationWindow::onBrowseICHDB(), and ComponentImplementationSelector::selectComponents().
setICDecoderParameter()
void IDF::MachineImplementation::setICDecoderParameter (const std::string & name, const std::string & value)
Sets value of an ic/decoder parameter.
Parameters
name Name of the parameter.
value Value of the parameter.
Definition at line 1437 of file MachineImplementation.cc.
{
    std::vector<Parameter>::iterator iter =
        icDecoderParameters_.begin();
    // Check if the parameter already exists.
    for (; iter != icDecoderParameters_.end(); iter++) {
        if ((*iter).name == name) {
            (*iter).value = value;
            return;
        }
    }
    // New parameter.
    Parameter parameter = { name, value };
    icDecoderParameters_.push_back(parameter);
}
References icDecoderParameters_.
Referenced by ProGe::ProGeUI::generateIDF(), and ProcessorImplementationWindow::onSetParameterValue().
setICDecoderPluginFile()
void IDF::MachineImplementation::setICDecoderPluginFile (const std::string & file)
Sets the ic/decoder plugin file.
Parameters
file Full path of the ic/decoder plugin file.
Definition at line 1474 of file MachineImplementation.cc.
{
    vector<string> paths = Environment::icDecoderPluginPaths();
    paths.insert(paths.begin(), FileSystem::directoryOfPath(sourceIDF_));
    string expandedPath = FileSystem::expandTilde(file);
    icDecoderPluginFile_ =
        FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References FileSystem::directoryOfPath(), FileSystem::expandTilde(), FileSystem::findFileInSearchPaths(), icDecoderPluginFile_, Environment::icDecoderPluginPaths(), and sourceIDF_.
Referenced by ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::loadICDecoderPlugin(), and ComponentImplementationSelector::selectComponents().
setICDecoderPluginName()
void IDF::MachineImplementation::setICDecoderPluginName (const std::string & name)
Sets the ic/decoder plugin name.
Parameters
name Name of the ic/decoder plugin.
Definition at line 1462 of file MachineImplementation.cc.
{
    icDecoderPluginName_ = name;
}
References icDecoderPluginName_.
Referenced by ProGe::ProGeUI::generateIDF(), ProcessorImplementationWindow::loadICDecoderPlugin(), and ComponentImplementationSelector::selectComponents().
socketImplementation() [1/2]
UnitImplementationLocation & IDF::MachineImplementation::socketImplementation (const std::string & socket) const
Returns the implementation data of the given socket.
Parameters
socket Name of the socket.
Returns
The implementation data.
Exceptions
InstanceNotFound If there is no implementation defined for the given socket.
Definition at line 441 of file MachineImplementation.cc.
{
    UnitImplementationLocation* impl = findImplementation(
        socketImplementations_, socket);
    if (impl == NULL) {
        throw InstanceNotFound(
            __FILE__, __LINE__, __func__,
            "No implementation data found for socket " + socket + ".");
    } else {
        return *impl;
    }
}
References __func__, findImplementation(), and socketImplementations_.
Referenced by checkImplFiles(), CostEstimator::Estimator::longestPath(), makeImplFilesRelative(), and saveState().
socketImplementation() [2/2]
UnitImplementationLocation & IDF::MachineImplementation::socketImplementation (int index) const
Returns the socket implementation at the given position.
Parameters
index The position index.
Returns
The implementation data.
Exceptions
OutOfRange If the index is smaller than 0 or not smaller than the number of socket implementations.
Definition at line 518 of file MachineImplementation.cc.
{
    ensureIndexValidity(index, socketImplementations_);
    return *socketImplementations_[index];
}
References ensureIndexValidity(), and socketImplementations_.
socketImplementationCount()
int IDF::MachineImplementation::socketImplementationCount () const
Returns the number of socket implementations.
Returns
The number of socket implementations.
Definition at line 341 of file MachineImplementation.cc.
{
    return socketImplementations_.size();
}
References socketImplementations_.
Referenced by checkImplFiles(), makeImplFilesRelative(), and saveState().
sourceIDF()
std::string IDF::MachineImplementation::sourceIDF () const
Returns the path to the source IDF file.
Returns
The source IDF.
Definition at line 121 of file MachineImplementation.cc.
{
    return sourceIDF_;
}
References sourceIDF_.
Referenced by IDF::UnitImplementationLocation::hdbFile().
Member Data Documentation
alternativeFiles_
std::vector<std::string> IDF::MachineImplementation::alternativeFiles_ private
Possible alternative file paths for missing implementation files.
Definition at line 231 of file MachineImplementation.hh.
Referenced by checkImplFile(), and checkImplFiles().
busImplementations_
ImplementationTable IDF::MachineImplementation::busImplementations_ private
BUS implementations.
Definition at line 211 of file MachineImplementation.hh.
Referenced by addBusImplementation(), busImplementation(), busImplementation(), busImplementationCount(), clearState(), hasBusImplementation(), and removeBusImplementation().
decompressorFile_
std::string IDF::MachineImplementation::decompressorFile_ private
Name of the decompressor block file.
Definition at line 222 of file MachineImplementation.hh.
Referenced by checkImplFiles(), clearState(), decompressorFile(), hasDecompressorFile(), loadState(), makeImplFilesRelative(), saveState(), and setDecompressorFile().
fuGenerated_
std::vector<FUGenerated> IDF::MachineImplementation::fuGenerated_ private
Generated FUs.
Definition at line 202 of file MachineImplementation.hh.
Referenced by addFuGeneration(), clearState(), FUGenerations(), FUGenerations(), hasFUGeneration(), loadState(), removeFuGeneration(), and saveState().
fuImplementations_
ImplementationTable IDF::MachineImplementation::fuImplementations_ private
FU implementations.
Definition at line 205 of file MachineImplementation.hh.
Referenced by addFUImplementation(), clearState(), fuImplementation(), fuImplementation(), fuImplementationCount(), hasFUImplementation(), and removeFUImplementation().
icDecoderHDB_
std::string IDF::MachineImplementation::icDecoderHDB_ private
Name of the HDB of the IC/decoder plugin.
Definition at line 220 of file MachineImplementation.hh.
Referenced by checkImplFiles(), clearState(), hasICDecoderHDB(), icDecoderHDB(), loadState(), makeImplFilesRelative(), saveState(), and setICDecoderHDB().
icDecoderParameters_
std::vector<Parameter> IDF::MachineImplementation::icDecoderParameters_ private
IC/decoder plugin parameters.
Definition at line 226 of file MachineImplementation.hh.
Referenced by clearICDecoderParameters(), clearState(), icDecoderParameterCount(), icDecoderParameterName(), icDecoderParameterValue(), icDecoderParameterValue(), loadState(), saveState(), and setICDecoderParameter().
icDecoderPluginFile_
std::string IDF::MachineImplementation::icDecoderPluginFile_ private
Name of the IC/decoder plugin file.
Definition at line 218 of file MachineImplementation.hh.
Referenced by checkImplFiles(), clearState(), hasICDecoderPluginFile(), icDecoderPluginFile(), loadState(), makeImplFilesRelative(), saveState(), and setICDecoderPluginFile().
icDecoderPluginName_
std::string IDF::MachineImplementation::icDecoderPluginName_ private
Name of the IC/decoder plugin.
Definition at line 216 of file MachineImplementation.hh.
Referenced by clearState(), hasICDecoderPluginName(), icDecoderPluginName(), loadState(), and setICDecoderPluginName().
iuImplementations_
ImplementationTable IDF::MachineImplementation::iuImplementations_ private
IU implementations.
Definition at line 209 of file MachineImplementation.hh.
Referenced by addIUImplementation(), clearState(), hasIUImplementation(), iuImplementation(), iuImplementation(), iuImplementationCount(), and removeIUImplementation().
missingFiles_
std::vector<std::string> IDF::MachineImplementation::missingFiles_ private
Implementation files defined in IDF which cannot be located.
Definition at line 229 of file MachineImplementation.hh.
Referenced by checkImplFile(), and checkImplFiles().
OSKEY_DECOMPRESSOR_FILE
const std::string IDF::MachineImplementation::OSKEY_DECOMPRESSOR_FILE static
Initial value:
=
    "decompressor_file"
ObjectState attribute key for the name of the decompressor file.
Definition at line 157 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_IC_DECODER_FILE
const std::string IDF::MachineImplementation::OSKEY_IC_DECODER_FILE static
Initial value:
=
    "ic_dec_file"
ObjectState attribute name for ic&decoder file.
Definition at line 147 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_IC_DECODER_HDB
const std::string IDF::MachineImplementation::OSKEY_IC_DECODER_HDB static
Initial value:
=
    "ic_dec_hdb"
ObjectState attribute name for ic&decoder HDB.
Definition at line 155 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_IC_DECODER_NAME
const std::string IDF::MachineImplementation::OSKEY_IC_DECODER_NAME static
Initial value:
=
    "ic_dec_name"
ObjectState attribute name for ic&decoder name.
Definition at line 145 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_IC_DECODER_PARAMETER_NAME
const std::string IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_NAME static
Initial value:
=
    "ic_dec_parameter_name"
ObjectState attribute name for ic&decoder parameter name.
Definition at line 151 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_IC_DECODER_PARAMETER_VALUE
const std::string IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE static
Initial value:
=
    "ic_dec_parameter_value"
ObjectState attribute name for ic&decoder parameter value.
Definition at line 153 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_SOURCE_IDF
const std::string IDF::MachineImplementation::OSKEY_SOURCE_IDF = "source_idf" static
ObjectState attribute name for the source IDF.
Definition at line 141 of file MachineImplementation.hh.
Referenced by loadState(), IDF::IDFSerializer::readState(), and saveState().
OSNAME_BUS_IMPLEMENTATIONS
const std::string IDF::MachineImplementation::OSNAME_BUS_IMPLEMENTATIONS static
Initial value:
=
    "bus_impls"
ObjectState name for bus implementation container.
Definition at line 167 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_FU_GENERATED
const std::string IDF::MachineImplementation::OSNAME_FU_GENERATED = "fu_generated" static
ObjectState name for FU generations container.
Definition at line 159 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_FU_IMPLEMENTATIONS
const std::string IDF::MachineImplementation::OSNAME_FU_IMPLEMENTATIONS static
Initial value:
=
    "fu_impls"
ObjectState name for FU implementation container.
Definition at line 161 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_IC_DECODER_PARAMETER
const std::string IDF::MachineImplementation::OSNAME_IC_DECODER_PARAMETER static
Initial value:
=
    "ic_dec_parameter"
ObjectState attribute name for ic&decoder parameter.
Definition at line 149 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_IC_DECODER_PLUGIN
const std::string IDF::MachineImplementation::OSNAME_IC_DECODER_PLUGIN static
Initial value:
=
    "ic_dec_plugin"
ObjectState name for the name of the IC/decoder plugin file.
Definition at line 143 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_IU_IMPLEMENTATIONS
const std::string IDF::MachineImplementation::OSNAME_IU_IMPLEMENTATIONS static
Initial value:
=
    "iu_impls"
ObjectState name for IU implementation container.
Definition at line 165 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_MACHINE_IMPLEMENTATION
const std::string IDF::MachineImplementation::OSNAME_MACHINE_IMPLEMENTATION static
Initial value:
=
    "mach_impl"
ObjectState name for machine implementation.
Definition at line 139 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_RF_IMPLEMENTATIONS
const std::string IDF::MachineImplementation::OSNAME_RF_IMPLEMENTATIONS static
Initial value:
=
    "rf_impls"
ObjectState name for RF implementation container.
Definition at line 163 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_SOCKET_IMPLEMENTATIONS
const std::string IDF::MachineImplementation::OSNAME_SOCKET_IMPLEMENTATIONS static
Initial value:
=
    "socket_impls"
ObjectState name for socket implementation container.
Definition at line 169 of file MachineImplementation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
rfImplementations_
ImplementationTable IDF::MachineImplementation::rfImplementations_ private
RF implementations.
Definition at line 207 of file MachineImplementation.hh.
Referenced by addRFImplementation(), clearState(), hasRFImplementation(), removeRFImplementation(), rfImplementation(), rfImplementation(), and rfImplementationCount().
socketImplementations_
ImplementationTable IDF::MachineImplementation::socketImplementations_ private
SOCKET implementations.
Definition at line 213 of file MachineImplementation.hh.
Referenced by addSocketImplementation(), clearState(), hasSocketImplementation(), removeSocketImplementation(), socketImplementation(), socketImplementation(), and socketImplementationCount().
sourceIDF_
std::string IDF::MachineImplementation::sourceIDF_ private
Absolute path to the source IDF file.
Definition at line 224 of file MachineImplementation.hh.
Referenced by clearState(), decompressorFile(), icDecoderHDB(), icDecoderPluginFile(), loadState(), saveState(), setDecompressorFile(), setICDecoderHDB(), setICDecoderPluginFile(), and sourceIDF().
The documentation for this class was generated from the following files:
MachineImplementation.hh
MachineImplementation.cc