OpenASIP: OperationGlobals Class Reference
OperationGlobals Class Reference
#include <OperationGlobals.hh>
Static Public Member Functions
static std::ostream & outputStream ()
static void setOutputStream (std::ostream &newOutputStream)
static void runtimeError (const char *message, const char *file, int line, const Operation &parent)
Private Member Functions
OperationGlobals ()
Instantiation not allowed.
OperationGlobals (const OperationGlobals &)
Copying not allowed.
OperationGlobals & operator= (const OperationGlobals &)
Assignment not allowed.
Static Private Attributes
static std::ostream * outputStream_ = &std::cout
The global output stream, defaults to std::cout.
Detailed Description
Definition at line 40 of file OperationGlobals.hh.
Constructor & Destructor Documentation
OperationGlobals() [1/2]
OperationGlobals::OperationGlobals () private
Instantiation not allowed.
OperationGlobals() [2/2]
OperationGlobals::OperationGlobals (const OperationGlobals &) private
Copying not allowed.
Member Function Documentation
operator=()
OperationGlobals & OperationGlobals::operator= (const OperationGlobals &) private
Assignment not allowed.
outputStream()
std::ostream & OperationGlobals::outputStream () static
Returns the current output stream
Returns
the current output stream
Definition at line 49 of file OperationGlobals.cc.
{
    return *outputStream_;
}
References outputStream_.
Referenced by OperationBehavior::writeOutput().
runtimeError()
void OperationGlobals::runtimeError (const char * message, const char * file, int line, const Operation & parent) static
Throws an exception with a message
Parameters
message Message
file FILE
line LINE
parent parent operation
Exceptions
SimulationExecutionError thrown always.
Definition at line 73 of file OperationGlobals.cc.
{
    throw SimulationExecutionError(std::string(file), line,
        parent.name(), std::string(" ") + parent.name() + ": " + message);
}
References Operation::name().
setOutputStream()
void OperationGlobals::setOutputStream (std::ostream & newOutputStream) static
Sets a new output stream for operation globals
Parameters
newOutputStream new output stream to set
Definition at line 59 of file OperationGlobals.cc.
{
    outputStream_ = &newOutputStream;
}
References outputStream_.
Referenced by DesignSpaceExplorer::DesignSpaceExplorer(), and ProximLineReader::initialize().
Member Data Documentation
outputStream_
std::ostream * OperationGlobals::outputStream_ = &std::cout static private
The global output stream, defaults to std::cout.
Definition at line 59 of file OperationGlobals.hh.
Referenced by outputStream(), and setOutputStream().
The documentation for this class was generated from the following files:
OperationGlobals.hh
OperationGlobals.cc