OpenASIP: CmdLineOptions Class Reference
CmdLineOptions Class Reference abstract
#include <CmdLineOptions.hh>
Public Member Functions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual void printVersion () const =0
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Protected Member Functions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Private Types
typedef std::map< std::string, CmdLineOptionParser * >::value_type valType
For adding new values to maps.
typedef std::map< std::string, CmdLineOptionParser * >::iterator mapIter
For traversing non-const maps.
typedef std::map< std::string, CmdLineOptionParser * >::const_iterator constMapIter
For traversing const maps.
Private Member Functions
CmdLineOptions (const CmdLineOptions &)
Copying not allowed.
CmdLineOptions & operator= (const CmdLineOptions &)
Assignment not allowed.
void parseAll ()
Private Attributes
std::string progName_
The name of the program.
std::string description_
The description of usage of program.
std::string version_
The version of the program.
Static Private Attributes
static const int SHORT_FLAG = 2
Number of characters reserved for printing short version of commandline flag.
static const int LONG_FLAG = 22
Number of characters reserved for printing long version of commandline flag.
static const std::string VERBOSE_SWITCH = "verbose"
Switch for verbose output listing scheduler modules.
static const std::string VERBOSE_SPAM_SWITCH = "verbose_spam"
Switch for verbose output listing spam from scheduler internals.
Additional Inherited Members
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Abstract base class for command line parsers.
Is capable of storing and parsing commmand line options.
Definition at line 54 of file CmdLineOptions.hh.
Member Typedef Documentation
constMapIter
typedef std::map<std::string,CmdLineOptionParser*>::const_iterator CmdLineOptions::constMapIter private
For traversing const maps.
Definition at line 77 of file CmdLineOptions.hh.
mapIter
typedef std::map<std::string,CmdLineOptionParser*>::iterator CmdLineOptions::mapIter private
For traversing non-const maps.
Definition at line 74 of file CmdLineOptions.hh.
valType
typedef std::map<std::string,CmdLineOptionParser*>::value_type CmdLineOptions::valType private
For adding new values to maps.
Definition at line 72 of file CmdLineOptions.hh.
Constructor & Destructor Documentation
CmdLineOptions() [1/2]
CmdLineOptions::CmdLineOptions (std::string description, std::string version = "")
Constructor.
Parameters
description Brief description of the program and how to use it. Only prefix is currently "no-".
Definition at line 73 of file CmdLineOptions.cc.
                       :
    CmdLineParser(description),
    progName_(""),
    description_(description),
    version_(version) {
    BoolCmdLineOptionParser* verboseSwitch =
        new BoolCmdLineOptionParser(
            VERBOSE_SWITCH, "The verbose switch", "v");
    addOption(verboseSwitch);
    BoolCmdLineOptionParser* verboseSpamSwitch =
        new BoolCmdLineOptionParser(
            VERBOSE_SPAM_SWITCH, "The verbose spam - switch", "V");
    addOption(verboseSpamSwitch);
}
References CmdLineParser::addOption(), VERBOSE_SPAM_SWITCH, and VERBOSE_SWITCH.
~CmdLineOptions()
CmdLineOptions::~CmdLineOptions () virtual
Destructor.
Definition at line 95 of file CmdLineOptions.cc.
{
}
CmdLineOptions() [2/2]
CmdLineOptions::CmdLineOptions (const CmdLineOptions &) private
Copying not allowed.
Member Function Documentation
isVerboseSpamSwitchDefined()
bool CmdLineOptions::isVerboseSpamSwitchDefined () const virtual
Return true if the verbose spam switch was defined in the command line.
Returns
True if the verbose spam switch was defined in the command line.
Definition at line 310 of file CmdLineOptions.cc.
{
    return findOption(VERBOSE_SPAM_SWITCH)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and VERBOSE_SPAM_SWITCH.
Referenced by GenerateProcessor::generateProcessor(), main(), and Application::setCmdLineOptions().
isVerboseSwitchDefined()
bool CmdLineOptions::isVerboseSwitchDefined () const virtual
Return true if the verbose switch was defined in the command line.
Returns
True if the verbose switch was defined in the command line.
Reimplemented in LLVMTCECmdLineOptions.
Definition at line 300 of file CmdLineOptions.cc.
{
    return findOption(VERBOSE_SWITCH)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and VERBOSE_SWITCH.
Referenced by GenerateProcessor::generateProcessor(), main(), Application::setCmdLineOptions(), and llvm::LLVMTCEIRBuilder::~LLVMTCEIRBuilder().
operator=()
CmdLineOptions & CmdLineOptions::operator= (const CmdLineOptions &) private
Assignment not allowed.
optionGiven()
bool CmdLineOptions::optionGiven (std::string key) const protected
Returns true if there is a value available for given option.
Returns
True if the option is defined.
Todo:
: This returns always true if trying to find added CmdLineOption...
Definition at line 320 of file CmdLineOptions.cc.
{
    try {
        /// @todo: This returns always true if trying to find added
        /// CmdLineOption...
        return findOption(key)->isDefined();
    } catch (const IllegalCommandLine&) {
        return false;
    }
    return true;
}
References CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
Referenced by SimulatorCmdLineOptions::backendType(), SimulatorCmdLineOptions::debugMode(), SchedulerCmdLineOptions::dumpIfConversionCFGs(), SchedulerCmdLineOptions::enableOffsetAA(), SchedulerCmdLineOptions::enableStackAA(), SchedulerCmdLineOptions::killDeadResults(), SchedulerCmdLineOptions::printResourceConstraints(), SchedulerCmdLineOptions::renameRegisters(), and SimulatorCmdLineOptions::scriptString().
parse() [1/3]
void CmdLineOptions::parse (char * argv[], int argc) virtual
Loads all command line arguments and parses them.
Parameters
options Command line options pre-parsed in char* array.
argc The number of command line options.
Exceptions
IllegalCommandLine If parsing is not succesfull.
ParserStopRequest If help or version option is found.
Reimplemented from CmdLineParser.
Definition at line 107 of file CmdLineOptions.cc.
{
    // command line is emptied
    commandLine_.clear();
    progName_ = string(argv[0]);
    for (int i = 1; i < argc; i++) {
        commandLine_.push_back(string(argv[i]));
    }
    parseAll();
}
References CmdLineParser::commandLine_, parseAll(), and progName_.
Referenced by GenerateProcessor::generateProcessor(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), and main().
parse() [2/3]
void CmdLineOptions::parse (std::string argv[], int argc)
Loads all command line arguments and parses them.
Parameters
options Command line options pre-parsed in string array.
argc The number of command line options.
Exceptions
IllegalCommandLine If parsing is not succesfull.
ParserStopRequest If help or version option is found.
Definition at line 128 of file CmdLineOptions.cc.
{
    // command line is emptied
    commandLine_.clear();
    progName_ = argv[0];
    for (int i = 1; i < argc; i++) {
        commandLine_.push_back(argv[i]);
    }
    parseAll();
}
References CmdLineParser::commandLine_, parseAll(), and progName_.
parse() [3/3]
void CmdLineOptions::parse (std::vector< std::string > argv) virtual
Loads all command line arguments and parses them.
Parameters
options Command line options pre-parsed in string vector.
Exceptions
IllegalCommandLine If parsing is not succesfull.
ParserStopRequest If help or version option is found.
Reimplemented from CmdLineParser.
Definition at line 147 of file CmdLineOptions.cc.
{
    // command line is emptied
    commandLine_.clear();
    progName_ = argv.at(0);
    for (unsigned int i = 1; i < argv.size(); i++) {
        commandLine_.push_back(argv[i]);
    }
    parseAll();
}
References CmdLineParser::commandLine_, parseAll(), and progName_.
parseAll()
void CmdLineOptions::parseAll () private
Parses all command line options.
Exceptions
IllegalCommandLine If parsing fails.
ParserStopRequest The client should not proceed.
Definition at line 165 of file CmdLineOptions.cc.
{
    // finished is set to true when options are parsed and the rest are
    // command line arguments
    bool finished = false;
    // checkArguments is set to false when command line arguments can start
    // with "-" or "--"
    bool checkArguments = true;
    unsigned int i = 0;
    while (i < commandLine_.size()) {
        string optString = commandLine_[i];
        if (!finished) {
            string prefix = "";
            string name = "";
            string arguments = "";
            // hasArgument is true when option has argument
            bool hasArgument = true;
            if (!parseOption(
                    optString, name, arguments, prefix, hasArgument)) {
                finished = true;
                if (optString == "--") {
                    checkArguments = false;
                    i++;
                    continue;
                } else {
                    arguments_.push_back(optString);
                    i++;
                    continue;
                }
            }
        //
            if (name == "help" || name == "h") {
                printHelp();
                string msg = "The client should not proceed";
                string method = "CmdLineParser::parseAll()";
                throw ParserStopRequest(__FILE__, __LINE__, method, msg);
            } else if (name == "version") {
                printVersion();
                string msg = "The client should not proceed";
                string method = "CmdLineParser::parseAll()";
                throw ParserStopRequest(__FILE__, __LINE__, method, msg);
            }
            CmdLineOptionParser* opt = findOption(name);
            if (arguments == "" &&
                dynamic_cast<BoolCmdLineOptionParser*>(opt) == NULL) {
                // argument for an option may be separated with space
                if (i < commandLine_.size() - 1 &&
                    commandLine_[i+1].substr(0, 1) != "-") {
                    hasArgument = true;
                    arguments = commandLine_[i+1];
                    i++;
                }
            }
            bool doneWithParsing = opt->parseValue(arguments, prefix);
            if (!doneWithParsing) {
                if (hasArgument) {
                    // all the rest in command line are "extra" strings
                    arguments_.push_back(arguments);
                    finished = true;
                    i++;
                } else {
                    // this is the situation when we have something like
                    // -abcd (multible flags put together)
                    for (unsigned int i = 0; i < arguments.length(); i++) {
                        opt = findOption(arguments.substr(i, 1));
                        opt->parseValue("", prefix);
                    }
                }
            }
        } else {
            // finished reading options, all rest are command line arguments
            if (checkArguments && optString[0] == '-') {
                string msg = "Illegal command line argument: " + optString;
                string method = "CmdLineOptions::parse()";
                throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
            }
            arguments_.push_back(optString);
        }
        i++;
    }
}
References CmdLineParser::arguments_, CmdLineParser::commandLine_, CmdLineParser::findOption(), CmdLineParser::parseOption(), CmdLineOptionParser::parseValue(), printHelp(), and printVersion().
Referenced by parse(), parse(), and parse().
printHelp()
void CmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Reimplemented in ExplorerCmdLineOptions, SimulatorCmdLineOptions, BEMGeneratorCmdLineOptions, BEMViewerCmdLineOptions, PIGCmdLineOptions, EstimatorCmdLineOptions, OsalCmdLineOptions, CreateHDBCmdLineOptions, TestHDBCmdLineOptions, MachInfoCmdLineOptions, ProGeCmdLineOptions, and TTAUnitTesterCmdLineOptions.
Definition at line 262 of file CmdLineOptions.cc.
{
    cout << description_ << endl;
    cout << "Options:" << endl;
    constMapIter i;
    for (i = optionLongNames_.begin(); i != optionLongNames_.end(); i++) {
        CmdLineOptionParser* opt = findOption((*i).first);
        if (opt->isHidden()) continue;
        if (opt->shortName() != "") {
            cout << left << setw(SHORT_FLAG) << "-" + opt->shortName() + ", "
                 << left << setw(LONG_FLAG) << "--" + opt->longName();
        } else {
            cout << "    "
                 << left << setw(LONG_FLAG) << "--" + opt->longName();
        }
        std::stringstream str(opt->description());
        int charsPrintedInRow = 0;
        while (!str.eof()) {
            std::string nextToken = "";
            str >> nextToken;
            if (nextToken.size() + charsPrintedInRow > 60) {
                cout << std::endl;
                cout << std::left << setw(SHORT_FLAG + LONG_FLAG + 2) << " ";
                charsPrintedInRow = 0;
            }
            cout << nextToken << " ";
            charsPrintedInRow += nextToken.size();
        }
        cout << std::endl;
    }
}
References CmdLineOptionParser::description(), description_, CmdLineParser::findOption(), CmdLineOptionParser::isHidden(), LONG_FLAG, CmdLineOptionParser::longName(), CmdLineParser::optionLongNames_, SHORT_FLAG, and CmdLineOptionParser::shortName().
Referenced by parseAll(), ExplorerCmdLineOptions::printHelp(), SimulatorCmdLineOptions::printHelp(), BEMGeneratorCmdLineOptions::printHelp(), PIGCmdLineOptions::printHelp(), EstimatorCmdLineOptions::printHelp(), CreateHDBCmdLineOptions::printHelp(), TestHDBCmdLineOptions::printHelp(), MachInfoCmdLineOptions::printHelp(), ProGeCmdLineOptions::printHelp(), and TTAUnitTesterCmdLineOptions::printHelp().
printVersion()
virtual void CmdLineOptions::printVersion () const pure virtual
Implemented in ExplorerCmdLineOptions, LLVMTCECmdLineOptions, SchedulerCmdLineOptions, SimulatorCmdLineOptions, AsmCmdLineOptions, BEMGeneratorCmdLineOptions, BEMViewerCmdLineOptions, DisasmCmdLineOptions, DictionaryToolCmdLineOptions, DisasmCmdLineOptions, PIGCmdLineOptions, DumperCmdLineOptions, EstimatorCmdLineOptions, BuildOpsetOptions, OsalCmdLineOptions, CreateHDBCmdLineOptions, TestHDBCmdLineOptions, MachInfoCmdLineOptions, ProGeCmdLineOptions, and TTAUnitTesterCmdLineOptions.
Referenced by parseAll().
Member Data Documentation
description_
std::string CmdLineOptions::description_ private
The description of usage of program.
Definition at line 89 of file CmdLineOptions.hh.
Referenced by printHelp().
LONG_FLAG
const int CmdLineOptions::LONG_FLAG = 22 static private
Number of characters reserved for printing long version of commandline flag.
Definition at line 99 of file CmdLineOptions.hh.
Referenced by printHelp().
progName_
std::string CmdLineOptions::progName_ private
The name of the program.
Definition at line 87 of file CmdLineOptions.hh.
Referenced by parse(), parse(), and parse().
SHORT_FLAG
const int CmdLineOptions::SHORT_FLAG = 2 static private
Number of characters reserved for printing short version of commandline flag.
Definition at line 95 of file CmdLineOptions.hh.
Referenced by printHelp().
VERBOSE_SPAM_SWITCH
const std::string CmdLineOptions::VERBOSE_SPAM_SWITCH = "verbose_spam" static private
Switch for verbose output listing spam from scheduler internals.
Definition at line 105 of file CmdLineOptions.hh.
Referenced by CmdLineOptions(), and isVerboseSpamSwitchDefined().
VERBOSE_SWITCH
const std::string CmdLineOptions::VERBOSE_SWITCH = "verbose" static private
Switch for verbose output listing scheduler modules.
Definition at line 102 of file CmdLineOptions.hh.
Referenced by CmdLineOptions(), and isVerboseSwitchDefined().
version_
std::string CmdLineOptions::version_ private
The version of the program.
Definition at line 91 of file CmdLineOptions.hh.
The documentation for this class was generated from the following files:
CmdLineOptions.hh
CmdLineOptions.cc