OpenASIP: OperationTriggeredEncoding Class Reference
OperationTriggeredEncoding Class Reference
#include <OperationTriggeredEncoding.hh>
Public Member Functions
OperationTriggeredEncoding (const std::string &name, InstructionFormat &parent)
OperationTriggeredEncoding (const ObjectState *state, InstructionFormat &parent)
~OperationTriggeredEncoding ()
std::string name () const
void setName (const std::string &name)
void addField (OperationTriggeredField &field)
virtual int childFieldCount () const
virtual int width () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_OTA_ENCODING
static const std::string OSKEY_OTA_ENCODING_NAME
Private Attributes
std::string name_
std::vector< OperationTriggeredField * > fields_
Detailed Description
Definition at line 44 of file OperationTriggeredEncoding.hh.
Constructor & Destructor Documentation
OperationTriggeredEncoding() [1/2]
OperationTriggeredEncoding::OperationTriggeredEncoding (const std::string & name, InstructionFormat & parent)
The constructor.
Adds the instruction format to the parent binary encoding automatically.
Parameters
name Name of the instruction format.
parent The parent Instruction Format.
Definition at line 54 of file OperationTriggeredEncoding.cc.
    : name_(name) {
    parent.addEncoding(*this);
}
References InstructionFormat::addEncoding().
OperationTriggeredEncoding() [2/2]
OperationTriggeredEncoding::OperationTriggeredEncoding (const ObjectState * state, InstructionFormat & parent)
The constructor.
Loads the state of the instruction format from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent binary encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 71 of file OperationTriggeredEncoding.cc.
{
    parent.addEncoding(*this);
    loadState(state);
}
References InstructionFormat::addEncoding(), and loadState().
~OperationTriggeredEncoding()
OperationTriggeredEncoding::~OperationTriggeredEncoding ()
The destructor
Definition at line 82 of file OperationTriggeredEncoding.cc.
{
    for (unsigned int i = 0; i < fields_.size(); i++) {
        delete fields_.at(i);
    }
}
References fields_.
Member Function Documentation
addField()
void OperationTriggeredEncoding::addField (OperationTriggeredField & field)
Definition at line 138 of file OperationTriggeredEncoding.cc.
{
    // TODO: Inspect that field is valid
    fields_.push_back(&field);
}
References fields_.
Referenced by OperationTriggeredField::OperationTriggeredField(), and OperationTriggeredField::OperationTriggeredField().
childFieldCount()
int OperationTriggeredEncoding::childFieldCount () const virtual
Returns the number of operation triggered fields.
Returns
The number of child fields.
Definition at line 117 of file OperationTriggeredEncoding.cc.
{
    return fields_.size();
}
References fields_.
loadState()
void OperationTriggeredEncoding::loadState (const ObjectState * state) virtual
Loads the state of the instruction format from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Definition at line 152 of file OperationTriggeredEncoding.cc.
{
    ObjectState* newState = new ObjectState(*state);
    try {
        setName(newState->stringAttribute(OSKEY_OTA_ENCODING_NAME));
        for (int i = 0; i < newState->childCount(); i++) {
            ObjectState* child = newState->child(i);
            if (child->name() == OperationTriggeredField::OSNAME_FIELD) {
                new OperationTriggeredField(child, *this);
            }
        }
    } catch (const Exception& exception) {
        const std::string procName = "OperationTriggeredEncoding::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    delete newState;
}
References ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::name(), OSKEY_OTA_ENCODING_NAME, OperationTriggeredField::OSNAME_FIELD, setName(), and ObjectState::stringAttribute().
Referenced by OperationTriggeredEncoding().
name()
std::string OperationTriggeredEncoding::name () const
Returns the name of the instruction format.
Returns
The name of the instruction format
Definition at line 95 of file OperationTriggeredEncoding.cc.
{
    return name_;
}
References name_.
Referenced by setName().
saveState()
ObjectState * OperationTriggeredEncoding::saveState () const virtual
Saves the state of the instruction format to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 177 of file OperationTriggeredEncoding.cc.
{
    ObjectState* state = new ObjectState(OSNAME_OTA_ENCODING);
    state->setAttribute(OSKEY_OTA_ENCODING_NAME, name_);
    for (unsigned int i = 0; i < fields_.size(); i++) {
        OperationTriggeredField* it = fields_.at(i);
        ObjectState* fieldObj = it->saveState();
        state->addChild(fieldObj);
    }
    return state;
}
References ObjectState::addChild(), fields_, name_, OSKEY_OTA_ENCODING_NAME, OSNAME_OTA_ENCODING, OperationTriggeredField::saveState(), and ObjectState::setAttribute().
Referenced by InstructionFormat::saveState().
setName()
void OperationTriggeredEncoding::setName (const std::string & name)
Sets the name of the instruction format.
Parameters
name The name of the instruction format.
Definition at line 106 of file OperationTriggeredEncoding.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by loadState().
width()
int OperationTriggeredEncoding::width () const virtual
Returns the bit width of the instruction format.
Returns
Bit width of the instruction format.
Definition at line 128 of file OperationTriggeredEncoding.cc.
{
    int width = 0;
    for (unsigned int i = 0; i < fields_.size(); i++) {
        OperationTriggeredField* field = fields_.at(i);
        width += field->width();
    }
    return width;
}
References fields_, width(), and OperationTriggeredField::width().
Referenced by InstructionFormat::width(), and width().
Member Data Documentation
fields_
std::vector<OperationTriggeredField*> OperationTriggeredEncoding::fields_ private
Definition at line 76 of file OperationTriggeredEncoding.hh.
Referenced by addField(), childFieldCount(), saveState(), width(), and ~OperationTriggeredEncoding().
name_
std::string OperationTriggeredEncoding::name_ private
Definition at line 74 of file OperationTriggeredEncoding.hh.
Referenced by name(), saveState(), and setName().
OSKEY_OTA_ENCODING_NAME
const std::string OperationTriggeredEncoding::OSKEY_OTA_ENCODING_NAME static
Initial value:
=
    "name"
Definition at line 69 of file OperationTriggeredEncoding.hh.
Referenced by loadState(), and saveState().
OSNAME_OTA_ENCODING
const std::string OperationTriggeredEncoding::OSNAME_OTA_ENCODING static
Initial value:
=
    "ota-encoding"
Definition at line 68 of file OperationTriggeredEncoding.hh.
Referenced by InstructionFormat::loadState(), and saveState().
The documentation for this class was generated from the following files:
OperationTriggeredEncoding.hh
OperationTriggeredEncoding.cc