OpenASIP: MachineCanvasTool Class Reference
MachineCanvasTool Class Reference abstract
#include <MachineCanvasTool.hh>
Public Member Functions
virtual ~MachineCanvasTool ()
virtual void activate ()=0
virtual void deactivate ()=0
virtual void onMouseEvent (wxMouseEvent &event, wxDC &dc)=0
virtual Figure * figure ()
Protected Member Functions
MachineCanvasTool (MachineCanvas *canvas)
Protected Attributes
MachineCanvas * canvas_
Machine canvas where the tool is used.
Detailed Description
Base class for the mouse tools used on the MachineCanvas.
MachineCanvas and MachineCanvasTool follow the 'state' -design pattern. MachineCanvas has always an active tool, which handles the mouse events on the canvas, such as mouse button clicks. The actual tools handling the mouse events are subclasses of this interface class.
Definition at line 49 of file MachineCanvasTool.hh.
Constructor & Destructor Documentation
~MachineCanvasTool()
MachineCanvasTool::~MachineCanvasTool () virtual
The Destructor.
Definition at line 49 of file MachineCanvasTool.cc.
{
}
MachineCanvasTool()
MachineCanvasTool::MachineCanvasTool (MachineCanvas * canvas) protected
The Constructor.
Parameters
canvas MachineCanvas where the tool is used.
Definition at line 41 of file MachineCanvasTool.cc.
                                                          :
    canvas_(canvas) {
}
Member Function Documentation
activate()
virtual void MachineCanvasTool::activate () pure virtual
Activate the tool.
Implemented in ProximMachineCanvasTool, ConnectTool, and SelectTool.
Referenced by BridgeDialog::onCancel(), BridgeDialog::onOK(), and MachineCanvas::setTool().
deactivate()
virtual void MachineCanvasTool::deactivate () pure virtual
Deactivate the tool.
Implemented in ProximMachineCanvasTool, ConnectTool, and SelectTool.
Referenced by BridgeDialog::BridgeDialog(), and MachineCanvas::setTool().
figure()
Figure * MachineCanvasTool::figure () virtual
Returns figure of the tool, or NULL if the tool has no figure.
Returns
Base class implementation returns always NULL (no figure).
Reimplemented in ConnectTool, and SelectTool.
Definition at line 59 of file MachineCanvasTool.cc.
{
    return NULL;
}
Referenced by MachineCanvas::OnDraw(), and MachineCanvas::refreshToolFigure().
onMouseEvent()
virtual void MachineCanvasTool::onMouseEvent (wxMouseEvent & event, wxDC & dc) pure virtual
Handle the mouse events of the canvas in a tool-specific way.
Parameters
event Mouse event to handle.
dc Device context.
Implemented in ProximMachineCanvasTool, ConnectTool, and SelectTool.
Referenced by MachineCanvas::onMouseEvent().
Member Data Documentation
canvas_
MachineCanvas* MachineCanvasTool::canvas_ protected
Machine canvas where the tool is used.
Definition at line 77 of file MachineCanvasTool.hh.
Referenced by ConnectTool::activate(), ConnectTool::deactivate(), ConnectTool::figure(), ConnectTool::leftClick(), SelectTool::leftClick(), ConnectTool::onMouseEvent(), and SelectTool::onMouseEvent().
The documentation for this class was generated from the following files:
MachineCanvasTool.hh
MachineCanvasTool.cc