OpenASIP: CmdLineParser Class Reference
CmdLineParser Class Reference
#include <CmdLineParser.hh>
Public Member Functions
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void parse (char *argv[], int argc)
virtual void parse (std::vector< std::string > options)
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Protected Member Functions
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Private Types
typedef std::map< std::string, CmdLineOptionParser * >::value_type valType
For adding new values to maps.
typedef std::map< std::string, CmdLineOptionParser * >::iterator mapIter
For traversing non-const maps.
typedef std::map< std::string, CmdLineOptionParser * >::const_iterator constMapIter
For traversing const maps.
Private Member Functions
CmdLineParser (const CmdLineParser &)
Copying not allowed.
CmdLineParser & operator= (const CmdLineParser &)
Assignment not allowed.
void parseAll ()
Private Attributes
std::string progName_
The name of the program.
std::string description_
The description of usage of program.
Static Private Attributes
static const int SHORT_FLAG = 2
Number of characters reserved for printing short version of commandline flag.
static const int LONG_FLAG = 22
Number of characters reserved for printing long version of commandline flag.
Detailed Description
Abstract base class for command line parsers.
Is capable of storing and parsing commmand line options.
Definition at line 53 of file CmdLineParser.hh.
Member Typedef Documentation
constMapIter
typedef std::map<std::string,CmdLineOptionParser*>::const_iterator CmdLineParser::constMapIter private
For traversing const maps.
Definition at line 97 of file CmdLineParser.hh.
mapIter
typedef std::map<std::string,CmdLineOptionParser*>::iterator CmdLineParser::mapIter private
For traversing non-const maps.
Definition at line 94 of file CmdLineParser.hh.
valType
typedef std::map<std::string,CmdLineOptionParser*>::value_type CmdLineParser::valType private
For adding new values to maps.
Definition at line 92 of file CmdLineParser.hh.
Constructor & Destructor Documentation
CmdLineParser() [1/2]
CmdLineParser::CmdLineParser (std::string description)
Constructor.
Parameters
description Brief description of the program and how to use it. Only prefix is currently "no-".
Definition at line 59 of file CmdLineParser.cc.
                                                  :
    progName_(""), description_(description) {
    prefixes_.push_back(string("no-"));
}
References prefixes_.
~CmdLineParser()
CmdLineParser::~CmdLineParser () virtual
Destructor.
Definition at line 68 of file CmdLineParser.cc.
{
    mapIter i;
    for (i = optionLongNames_.begin(); i != optionLongNames_.end(); i++) {
        delete (*i).second;
    }
    optionShortNames_.clear();
    commandLine_.clear();
}
References commandLine_, optionLongNames_, and optionShortNames_.
CmdLineParser() [2/2]
CmdLineParser::CmdLineParser (const CmdLineParser &) private
Copying not allowed.
Member Function Documentation
addOption()
void CmdLineParser::addOption (CmdLineOptionParser * opt) protected
Referenced by AsmCmdLineOptions::AsmCmdLineOptions(), BEMGeneratorCmdLineOptions::BEMGeneratorCmdLineOptions(), BuildOpsetOptions::BuildOpsetOptions(), CmdLineOptions::CmdLineOptions(), DictionaryToolCmdLineOptions::DictionaryToolCmdLineOptions(), DisasmCmdLineOptions::DisasmCmdLineOptions(), EstimatorCmdLineOptions::EstimatorCmdLineOptions(), ExplorerCmdLineOptions::ExplorerCmdLineOptions(), LLVMTCECmdLineOptions::LLVMTCECmdLineOptions(), MachInfoCmdLineOptions::MachInfoCmdLineOptions(), PIGCmdLineOptions::PIGCmdLineOptions(), ProGeCmdLineOptions::ProGeCmdLineOptions(), SchedulerCmdLineOptions::SchedulerCmdLineOptions(), SimulatorCmdLineOptions::SimulatorCmdLineOptions(), TestHDBCmdLineOptions::TestHDBCmdLineOptions(), and TTAUnitTesterCmdLineOptions::TTAUnitTesterCmdLineOptions().
argument()
virtual std::string CmdLineParser::argument (int index) const virtual
Referenced by BEMGeneratorCmdLineOptions::adfFile(), BEMViewerCmdLineOptions::bemFile(), TestHDBCmdLineOptions::hdbFile(), TTAUnitTesterCmdLineOptions::idfFileName(), loadInputs(), main(), MachInfoCmdLineOptions::outputFileNameSuffix(), and ProGeCmdLineOptions::processorToGenerate().
findOption()
CmdLineOptionParser * CmdLineParser::findOption (std::string name) const protected
Try to find a particular option.
Parameters
name The name of the option.
Returns
The option if it is found.
Exceptions
IllegalCommandLine If option is not found.
Definition at line 160 of file CmdLineParser.cc.
{
    constMapIter i = optionLongNames_.find(name);
    if (i != optionLongNames_.end()) {
        return (*i).second;
    }
    i = optionShortNames_.find(name);
    if (i != optionShortNames_.end()) {
        return (*i).second;
    }
    string msg = "Unknown option: " + name;
    string method = "CmdLineParser::findOption()";
    throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
}
References optionLongNames_, and optionShortNames_.
Referenced by ExplorerCmdLineOptions::adfFile(), ExplorerCmdLineOptions::adfFileName(), TTAUnitTesterCmdLineOptions::adfFileName(), ExplorerCmdLineOptions::adfOutFile(), ExplorerCmdLineOptions::adfOutFileName(), LLVMTCECmdLineOptions::analyzeInstructionPatterns(), ExplorerCmdLineOptions::applicationIDToRemove(), ExplorerCmdLineOptions::applicationIDToRemoveCount(), LLVMTCECmdLineOptions::assumeADFStackAlignment(), ProGeCmdLineOptions::asyncReset(), LLVMTCECmdLineOptions::backendCacheDir(), SimulatorCmdLineOptions::backendType(), PIGCmdLineOptions::bemFile(), ProGeCmdLineOptions::bemFile(), SchedulerCmdLineOptions::bypassDistance(), ProGeCmdLineOptions::clockFrequency(), ProGeCmdLineOptions::commaSeparatedList(), ExplorerCmdLineOptions::compilerOptions(), ExplorerCmdLineOptions::compilerOptionsString(), PIGCmdLineOptions::compressorParameter(), PIGCmdLineOptions::compressorParameterCount(), PIGCmdLineOptions::compressorPlugin(), ExplorerCmdLineOptions::configurationToWrite(), LLVMTCECmdLineOptions::conservativePreRAScheduler(), PIGCmdLineOptions::dataImageOutputFormat(), PIGCmdLineOptions::dataMemoryWidthInMAUs(), PIGCmdLineOptions::dataStart(), LLVMTCECmdLineOptions::dataStartAddress(), LLVMTCECmdLineOptions::debugFlag(), SimulatorCmdLineOptions::debugMode(), ProGeCmdLineOptions::deviceFamilyName(), ProGeCmdLineOptions::deviceName(), LLVMTCECmdLineOptions::disableAddressSpaceAA(), LLVMTCECmdLineOptions::disableDelaySlotFiller(), LLVMTCECmdLineOptions::disableHWLoops(), LLVMTCECmdLineOptions::disableLLVMAA(), ProGeCmdLineOptions::dmemType(), DictionaryToolCmdLineOptions::doNotPrintErrors(), LLVMTCECmdLineOptions::dumpDDGsDot(), LLVMTCECmdLineOptions::dumpDDGsXML(), SchedulerCmdLineOptions::dumpIfConversionCFGs(), SchedulerCmdLineOptions::enableOffsetAA(), SchedulerCmdLineOptions::enableStackAA(), PIGCmdLineOptions::entityName(), ProGeCmdLineOptions::entityName(), ExplorerCmdLineOptions::explorerPlugin(), ExplorerCmdLineOptions::explorerPluginParameter(), ExplorerCmdLineOptions::explorerPluginParameterCount(), DisasmCmdLineOptions::flatFile(), ProGeCmdLineOptions::forceOutputDirectory(), TestHDBCmdLineOptions::fuEntryID(), PIGCmdLineOptions::generateDataImages(), PIGCmdLineOptions::generateDecompressor(), LLVMTCECmdLineOptions::generatePluginOnly(), ProGeCmdLineOptions::generateTestbench(), LLVMTCECmdLineOptions::getLLVMargv(), ExplorerCmdLineOptions::hdbFileName(), ExplorerCmdLineOptions::hdbFileNameCount(), ExplorerCmdLineOptions::hdbFileNames(), ProGeCmdLineOptions::hdl(), ExplorerCmdLineOptions::idfFile(), ProGeCmdLineOptions::idfFile(), ExplorerCmdLineOptions::idfFileName(), SchedulerCmdLineOptions::ifConversionThreshold(), BuildOpsetOptions::ignore(), ProGeCmdLineOptions::imemType(), LLVMTCECmdLineOptions::initialStackPointerValue(), ProGeCmdLineOptions::integratorName(), LLVMTCECmdLineOptions::isDataStartAddressSet(), TestHDBCmdLineOptions::isFUEntryIDGiven(), LLVMTCECmdLineOptions::isInitialStackPointerValueSet(), SchedulerCmdLineOptions::isLoopOptDefined(), SchedulerCmdLineOptions::isMachineFileDefined(), LLVMTCECmdLineOptions::isOptLevelDefined(), SchedulerCmdLineOptions::isOutputFileDefined(), TestHDBCmdLineOptions::isRFEntryIDGiven(), LLVMTCECmdLineOptions::isStandardEmulationLibDefined(), CmdLineOptions::isVerboseSpamSwitchDefined(), LLVMTCECmdLineOptions::isVerboseSwitchDefined(), CmdLineOptions::isVerboseSwitchDefined(), LLVMTCECmdLineOptions::isWorkItemAAFileDefined(), SchedulerCmdLineOptions::killDeadResults(), TestHDBCmdLineOptions::leaveDirty(), TTAUnitTesterCmdLineOptions::leaveDirty(), DisasmCmdLineOptions::lineNumbers(), ProGeCmdLineOptions::listAvailableIntegrators(), EstimatorCmdLineOptions::longestPath(), SchedulerCmdLineOptions::lowMemModeThreshold(), SimulatorCmdLineOptions::machineFile(), SchedulerCmdLineOptions::machineFile(), SchedulerCmdLineOptions::noaliasFunctions(), SchedulerCmdLineOptions::noDreBypassDistance(), ExplorerCmdLineOptions::numberOfConfigurations(), ExplorerCmdLineOptions::numberOfConfigurationsToWrite(), SchedulerCmdLineOptions::operandShareDistance(), CmdLineOptions::optionGiven(), LLVMTCECmdLineOptions::optLevel(), ProGeCmdLineOptions::outputDirectory(), AsmCmdLineOptions::outputFile(), DisasmCmdLineOptions::outputFile(), SchedulerCmdLineOptions::outputFile(), BEMGeneratorCmdLineOptions::outputFile(), DisasmCmdLineOptions::outputFileDefined(), MachInfoCmdLineOptions::outputFileNameSuffix(), MachInfoCmdLineOptions::outputFormat(), ExplorerCmdLineOptions::paretoSetValues(), CmdLineOptions::parseAll(), parseAll(), ExplorerCmdLineOptions::pluginInfo(), ProGeCmdLineOptions::pluginParametersQuery(), ProGeCmdLineOptions::preferHDLGeneration(), LLVMTCECmdLineOptions::primaryFunctions(), ExplorerCmdLineOptions::printApplications(), DictionaryToolCmdLineOptions::printConnections(), DictionaryToolCmdLineOptions::printGlobalRegister(), CmdLineOptions::printHelp(), LLVMTCECmdLineOptions::printInlineAsmWarnings(), DictionaryToolCmdLineOptions::printMissingConnections(), ExplorerCmdLineOptions::printPlugins(), DictionaryToolCmdLineOptions::printPrimitive(), SchedulerCmdLineOptions::printResourceConstraints(), DictionaryToolCmdLineOptions::printRFConnections(), ExplorerCmdLineOptions::printSummary(), DisasmCmdLineOptions::printToStdout(), AsmCmdLineOptions::printWarnings(), PIGCmdLineOptions::progeOutputDirectory(), SimulatorCmdLineOptions::programFile(), PIGCmdLineOptions::programImageOutputFormat(), SchedulerCmdLineOptions::renameRegisters(), ProGeCmdLineOptions::resetAllRegisters(), TestHDBCmdLineOptions::rfEntryID(), EstimatorCmdLineOptions::runOnlyEstimations(), LLVMTCECmdLineOptions::saveBackendPlugin(), SchedulerCmdLineOptions::schedulingWindowSize(), SimulatorCmdLineOptions::scriptString(), ProGeCmdLineOptions::sharedOutputDirectory(), PIGCmdLineOptions::showCompressors(), ProGeCmdLineOptions::simulationRuntime(), BuildOpsetOptions::sourceDir(), LLVMTCECmdLineOptions::standardEmulationLib(), ExplorerCmdLineOptions::startConfiguration(), ExplorerCmdLineOptions::summaryOrdering(), ProGeCmdLineOptions::syncReset(), LLVMTCECmdLineOptions::tempDir(), ExplorerCmdLineOptions::testApplicationDirectory(), ExplorerCmdLineOptions::testApplicationDirectoryCount(), EstimatorCmdLineOptions::totalArea(), EstimatorCmdLineOptions::totalEnergy(), EstimatorCmdLineOptions::TPEF(), PIGCmdLineOptions::tpefFile(), PIGCmdLineOptions::tpefFileCount(), ProGeCmdLineOptions::tpefName(), EstimatorCmdLineOptions::traceDB(), ProGeCmdLineOptions::useAbsolutePaths(), LLVMTCECmdLineOptions::useBubbleFish2Scheduler(), LLVMTCECmdLineOptions::useBUScheduler(), LLVMTCECmdLineOptions::useOldBackendSources(), SchedulerCmdLineOptions::useRestrictedAliasAnalyzer(), LLVMTCECmdLineOptions::useTDScheduler(), LLVMTCECmdLineOptions::useVectorBackend(), TestHDBCmdLineOptions::verbose(), TTAUnitTesterCmdLineOptions::verbose(), TestHDBCmdLineOptions::vhdlSim(), TTAUnitTesterCmdLineOptions::vhdlSim(), LLVMTCECmdLineOptions::workItemAAFile(), DictionaryToolCmdLineOptions::writeBinary(), ExplorerCmdLineOptions::writeOutBestConfiguration(), and ExplorerCmdLineOptions::writeOutConfiguration().
isPrefix()
bool CmdLineParser::isPrefix (std::string name) const protected
numberOfArguments()
virtual int CmdLineParser::numberOfArguments () const virtual
Referenced by BEMGeneratorCmdLineOptions::adfFile(), BEMViewerCmdLineOptions::bemFile(), GenerateProcessor::generateProcessor(), TestHDBCmdLineOptions::hdbFile(), TTAUnitTesterCmdLineOptions::idfFileName(), loadInputs(), main(), MachInfoCmdLineOptions::outputFileNameSuffix(), and ProGeCmdLineOptions::processorToGenerate().
operator=()
CmdLineParser & CmdLineParser::operator= (const CmdLineParser &) private
Assignment not allowed.
parse() [1/2]
void CmdLineParser::parse (char * argv[], int argc) virtual
Loads all command line arguments and parses them.
Parameters
argv Command line options.
argc The number of command line options.
Exceptions
IllegalCommandLine If parsing is not succesfull.
ParserStopRequest If help or version option is found.
Reimplemented in CmdLineOptions.
Definition at line 109 of file CmdLineParser.cc.
{
    // command line is emptied
    commandLine_.clear();
    progName_ = string(argv[0]);
    for (int i = 1; i < argc; i++) {
        commandLine_.push_back(string(argv[i]));
    }
    parseAll();
}
References commandLine_, parseAll(), and progName_.
parse() [2/2]
void CmdLineParser::parse (std::vector< std::string > options) virtual
Loads all command line arguments and parses them.
Parameters
options Command line options pre-parsed in vector.
argc The number of command line options.
Exceptions
IllegalCommandLine If parsing is not succesfull.
ParserStopRequest If help or version option is found.
Reimplemented in CmdLineOptions.
Definition at line 129 of file CmdLineParser.cc.
{
    // command line is emptied
    commandLine_.clear();
    for (unsigned int i = 0; i < options.size(); i++) {
    bool spaces = true;
        string::size_type curPos = 0;
    while (spaces) {
        string::size_type pos = options[i].find(" ", curPos);
        if (pos != string::npos) {
        commandLine_.push_back(string(options[i].substr(pos, curPos)));
        curPos = pos;
        } else {
        if (options[i].length() - curPos > 0) {
            commandLine_.push_back(string(options[i].substr(curPos)));
        }
        spaces = false;
        }
    }
    }
    parseAll();
}
References commandLine_, options, and parseAll().
parseAll()
void CmdLineParser::parseAll () private
Parses all command line options.
Exceptions
IllegalCommandLine If parsing fails.
Definition at line 182 of file CmdLineParser.cc.
{
    // finished is set to true when options are parsed and the rest are
    // command line arguments
    bool finished = false;
    // checkArguments is set to false when command line arguments can start
    // with "-" or "--"
    bool checkArguments = true;
    unsigned int i = 0;
    while (i < commandLine_.size()) {
        string optString = commandLine_[i];
        if (!finished) {
            string prefix = "";
            string name = "";
            string arguments = "";
            // hasArgument is true when option has argument
            bool hasArgument = true;
            if (!parseOption(optString, name, arguments, prefix, hasArgument)) {
                finished = true;
                if (optString == "--") {
                    checkArguments = false;
                    i++;
                    continue;
                } else {
                    arguments_.push_back(optString);
                    i++;
                    continue;
                }
            }
            CmdLineOptionParser* opt = findOption(name);
            if (arguments == "" &&
                dynamic_cast<BoolCmdLineOptionParser*>(opt) == NULL) {
                // argument for an option may be separated with space
                if (i < commandLine_.size() - 1 &&
                    commandLine_[i+1].substr(0, 1) != "-") {
                    hasArgument = true;
                    arguments = commandLine_[i+1];
                    i++;
                }
            }
            bool doneWithParsing = opt->parseValue(arguments, prefix);
            if (!doneWithParsing) {
                if (hasArgument) {
                    // all the rest in command line are "extra" strings
                    arguments_.push_back(arguments);
                    finished = true;
                    i++;
                } else {
                    // this is the situation when we have something like
                    // -abcd (multible flags put together)
                    for (unsigned int i = 0; i < arguments.length(); i++) {
                        opt = findOption(arguments.substr(i, 1));
                        opt->parseValue("", prefix);
                    }
                }
            }
        } else {
            // finished reading options, all rest are command line arguments
            if (checkArguments && optString[0] == '-') {
                string msg = "Illegal command line argument: " + optString;
                string method = "CmdLineParser::parse()";
                throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
            }
            arguments_.push_back(optString);
        }
        i++;
    }
}
References arguments_, commandLine_, findOption(), parseOption(), and CmdLineOptionParser::parseValue().
Referenced by parse(), and parse().
parseOption()
bool CmdLineParser::parseOption (std::string option, std::string & name, std::string & arguments, std::string & prefix, bool & hasArgument) const protected
Parses one option.
Each option should have name and prefix (-, –, -no, or –no). Arguments are mandatory for all except Boolean options.
Parameters
option The whole option.
name The name of the option.
arguments The arguments for option.
prefix The prefix of option.
hasArgument False if argument is part of option body (eg. -abc).
Returns
True if option is command line option, false if option is command line argument.
Exceptions
IllegalCommandLine If option is illegal.
Definition at line 277 of file CmdLineParser.cc.
{
    // first there is either '-' or '--'
    bool longOption = false;
    if (!readPrefix(option, prefix, longOption)) {
        return false;
    }
    if (longOption) {
        // then there is the name of the option
        unsigned int pos = 0;
        while (pos < option.length() && option[pos] != '=') {
            ++pos;
        }
        name = option.substr(0, pos);
        option.erase(0, pos);
    } else {
        // option name is only one character
        name = option.substr(0, 1);
        option.erase(0, 1);
    }
    // then there might be value
    if (option.length() > 0 && option[0] == '=') {
        if (!longOption) {
            string method = "CmdLineParser::parseOption()";
            string message = "Illegal short option: = not allowed.";
            throw IllegalCommandLine(__FILE__, __LINE__, method, message);
        }
        option.erase(0, 1);
        arguments = option;
    } else {
        arguments = option;
        if (arguments == "" || !longOption) {
            hasArgument = false;
        }
    }
    return true;
}
References readPrefix().
Referenced by CmdLineOptions::parseAll(), and parseAll().
readPrefix()
bool CmdLineParser::readPrefix (std::string & option, std::string & prefix, bool & longOption) const protected
Reads prefix of option.
Parameters
option The whole option as a string.
prefix The prefix of option.
longOption True if option starts with "--".
Returns
True, if prefix is found, false otherwise.
Definition at line 327 of file CmdLineParser.cc.
{
    if (option == "--") {
        return false;
    } else if (option.substr(0, 1) != "-") {
        return false;
    } else {
        option.erase(0, 1);
        if (option.substr(0, 1) == "-") {
            longOption = true;
            option.erase(0, 1);
        }
        // then there might be also something else in the prefix
        // (eg. --no-print, prefix is --no)
        for (unsigned int i = 0; i < prefixes_.size(); i++) {
            if (option.length() > prefixes_[i].length() &&
                option.substr(0, prefixes_[i].length()) == prefixes_[i]) {
                prefix = prefixes_[i];
                option.erase(0, prefix.length());
                break;
            }
        }
    }
    return true;
}
References prefixes_.
Referenced by parseOption().
storeOptions()
void CmdLineParser::storeOptions (Options & options) virtual
Stores options to Options class.
Parameters
options Options-object where the options are stored.
Definition at line 83 of file CmdLineParser.cc.
{
    mapIter i = optionLongNames_.begin();
    for (; i != optionLongNames_.end(); i++) {
        string name = (*i).first;
        CmdLineOptionParser* current = (*i).second;
        options.addOptionValue(name, current->copy());
    }
    i = optionShortNames_.begin();
    for (; i != optionShortNames_.end(); i++) {
        string name = (*i).first;
        CmdLineOptionParser* current = (*i).second;
        options.addOptionValue(name, current->copy());
    }
}
References CmdLineOptionParser::copy(), optionLongNames_, options, and optionShortNames_.
Member Data Documentation
arguments_
std::vector<std::string> CmdLineParser::arguments_ protected
Command line arguments are stored here.
Definition at line 86 of file CmdLineParser.hh.
Referenced by CmdLineOptions::parseAll(), and parseAll().
commandLine_
std::vector<std::string> CmdLineParser::commandLine_ protected
Command line is stored here.
Definition at line 84 of file CmdLineParser.hh.
Referenced by CmdLineOptions::parse(), parse(), CmdLineOptions::parse(), CmdLineOptions::parse(), parse(), CmdLineOptions::parseAll(), parseAll(), and ~CmdLineParser().
description_
std::string CmdLineParser::description_ private
The description of usage of program.
Definition at line 109 of file CmdLineParser.hh.
LONG_FLAG
const int CmdLineParser::LONG_FLAG = 22 static private
Number of characters reserved for printing long version of commandline flag.
Definition at line 117 of file CmdLineParser.hh.
optionLongNames_
std::map<std::string, CmdLineOptionParser*> CmdLineParser::optionLongNames_ protected
Database for holding options with their long names as a key.
Definition at line 79 of file CmdLineParser.hh.
Referenced by findOption(), CmdLineOptions::printHelp(), storeOptions(), and ~CmdLineParser().
optionShortNames_
std::map<std::string, CmdLineOptionParser*> CmdLineParser::optionShortNames_ protected
Database for holding options with their short names as a key.
Definition at line 81 of file CmdLineParser.hh.
Referenced by findOption(), storeOptions(), and ~CmdLineParser().
prefixes_
std::vector<std::string> CmdLineParser::prefixes_ protected
Legal prefixes are stored here.
Definition at line 88 of file CmdLineParser.hh.
Referenced by CmdLineParser(), and readPrefix().
progName_
std::string CmdLineParser::progName_ private
The name of the program.
Definition at line 107 of file CmdLineParser.hh.
Referenced by parse().
SHORT_FLAG
const int CmdLineParser::SHORT_FLAG = 2 static private
Number of characters reserved for printing short version of commandline flag.
Definition at line 113 of file CmdLineParser.hh.
The documentation for this class was generated from the following files:
CmdLineParser.hh
CmdLineParser.cc