OpenASIP: TTAProgram::TerminalBasicBlockReference Class Reference
TTAProgram::TerminalBasicBlockReference Class Reference
#include <TerminalBasicBlockReference.hh>
Public Member Functions
TerminalBasicBlockReference (const BasicBlock &bb)
virtual ~TerminalBasicBlockReference ()
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
virtual SimValue value () const
virtual const BasicBlock & basicBlock () const
virtual bool isBasicBlockReference () const
Public Member Functions inherited from TTAProgram::TerminalImmediate
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Private Attributes
const BasicBlock * bb_
Additional Inherited Members
Protected Attributes inherited from TTAProgram::TerminalImmediate
SimValue value_
Value of the inline immediate.
Detailed Description
Definition at line 42 of file TerminalBasicBlockReference.hh.
Constructor & Destructor Documentation
TerminalBasicBlockReference()
TTAProgram::TerminalBasicBlockReference::TerminalBasicBlockReference (const BasicBlock & bb)
Definition at line 38 of file TerminalBasicBlockReference.cc.
                          :
    TerminalImmediate(
        SimValue(bb.startAddress().location(), WORD_BITWIDTH)),
    bb_(&bb) {}
~TerminalBasicBlockReference()
virtual TTAProgram::TerminalBasicBlockReference::~TerminalBasicBlockReference () inline virtual
Definition at line 45 of file TerminalBasicBlockReference.hh.
{}
Member Function Documentation
basicBlock()
virtual const BasicBlock & TTAProgram::TerminalBasicBlockReference::basicBlock () const inline virtual
Returns a reference to the basic block to which the immediate points.
Returns
A reference to the basic block to which the immediate points.
Reimplemented from TTAProgram::Terminal.
Definition at line 51 of file TerminalBasicBlockReference.hh.
                       {
        return *bb_;
    }
References bb_.
Referenced by TTAProgram::TerminalInstructionReference::equals().
copy()
Terminal * TTAProgram::TerminalBasicBlockReference::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 45 of file TerminalBasicBlockReference.cc.
{
    return new TerminalBasicBlockReference(*bb_); }
References bb_.
equals()
bool TTAProgram::TerminalBasicBlockReference::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 49 of file TerminalBasicBlockReference.cc.
{
    const TerminalBasicBlockReference* otherBBRef =
        dynamic_cast<const TerminalBasicBlockReference*>(&other);
    if (otherBBRef) {
        return otherBBRef->bb_ == bb_;
    }
    const TerminalInstructionReference* otherInsRef =
        dynamic_cast<const TerminalInstructionReference*>(&other);
    if (otherInsRef) {
        return &otherInsRef->instructionReference().instruction() ==
            &(bb_->firstInstruction());
    }
    return false;
}
References bb_, TTAProgram::CodeSnippet::firstInstruction(), TTAProgram::InstructionReference::instruction(), and TTAProgram::TerminalInstructionReference::instructionReference().
isBasicBlockReference()
virtual bool TTAProgram::TerminalBasicBlockReference::isBasicBlockReference () const inline virtual
Tells whether the terminal is reference to a basic block.
Returns
True if the terminal is a ref to a basic block
Reimplemented from TTAProgram::Terminal.
Definition at line 54 of file TerminalBasicBlockReference.hh.
{ return true; }
value()
SimValue TTAProgram::TerminalBasicBlockReference::value () const virtual
Returns the value of the inline immediate.
Returns
The value of the inline immediate.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 66 of file TerminalBasicBlockReference.cc.
{
    return SimValue(bb_->startAddress().location(), WORD_BITWIDTH);
}
References bb_, TTAProgram::Address::location(), TTAProgram::CodeSnippet::startAddress(), and WORD_BITWIDTH.
Member Data Documentation
bb_
const BasicBlock* TTAProgram::TerminalBasicBlockReference::bb_ private
Definition at line 56 of file TerminalBasicBlockReference.hh.
Referenced by basicBlock(), copy(), equals(), and value().
The documentation for this class was generated from the following files:
TerminalBasicBlockReference.hh
TerminalBasicBlockReference.cc