OpenASIP: FUCollisionMatrixIndex Class Reference
FUCollisionMatrixIndex Class Reference
#include <FUCollisionMatrixIndex.hh>
Public Member Functions
FUCollisionMatrixIndex (const TTAMachine::FunctionUnit &functionUnit)
virtual ~FUCollisionMatrixIndex ()
CollisionMatrix & at (int index)
int size () const
Private Attributes
std::vector< CollisionMatrix * > matrices_
Stores all collision matrices, including one for the pseudo NOP.
Detailed Description
Represents an index of collision matrices required for modeling collision behavior of operations in an FU.
Definition at line 47 of file FUCollisionMatrixIndex.hh.
Constructor & Destructor Documentation
FUCollisionMatrixIndex()
FUCollisionMatrixIndex::FUCollisionMatrixIndex (const TTAMachine::FunctionUnit & functionUnit)
Builds collision matrices for all operations in the FU and an empty collision matrix for the pseudo no-operation.
Matrices are stored in the order returned by FunctionUnit::operation(), the NOP matrix is at index FunctionUnit::operationCount().
Parameters
functionUnit The FU to build the matrices for.
Definition at line 48 of file FUCollisionMatrixIndex.cc.
{
    FUReservationTableIndex tables(functionUnit);
    int width = 0;
    int height = 0;
    for (int i = 0; i < functionUnit.operationCount(); ++i) {
        CollisionMatrix* matrix = new CollisionMatrix(tables, i);
#ifndef NDEBUG
        if (width == 0 && height == 0) {
            width = matrix->columnCount();
            height = matrix->rowCount();
        } else {
            // all matrices should be of the same dimension, otherwise there's
            // a bug somewhere
            assert(matrix->columnCount() == width);
            assert(matrix->rowCount() == height);
        }
#endif
        matrices_.push_back(matrix);
    }
    // The NOP.
    matrices_.push_back(new CollisionMatrix(width, height, false));
}
References assert, BitMatrix::columnCount(), matrices_, TTAMachine::FunctionUnit::operationCount(), and BitMatrix::rowCount().
~FUCollisionMatrixIndex()
FUCollisionMatrixIndex::~FUCollisionMatrixIndex () virtual
Destructor.
Definition at line 79 of file FUCollisionMatrixIndex.cc.
{
    SequenceTools::deleteAllItems(matrices_);
}
References SequenceTools::deleteAllItems(), and matrices_.
Member Function Documentation
at()
CollisionMatrix & FUCollisionMatrixIndex::at (int index)
Returns the collision matrix at the given index.
Parameters
operation The index of the operat
Definition at line 89 of file FUCollisionMatrixIndex.cc.
{
    return *matrices_.at(index);
}
References matrices_.
Referenced by FUFiniteStateAutomaton::FUFiniteStateAutomaton(), FUFiniteStateAutomaton::operationCollisionMatrix(), and FUFiniteStateAutomaton::resolveState().
size()
int FUCollisionMatrixIndex::size () const
Returns the count of collision matrices in the index.
Returns
Count of collision matrices.
Definition at line 99 of file FUCollisionMatrixIndex.cc.
{
    return matrices_.size();
}
References matrices_.
Referenced by FUFiniteStateAutomaton::buildStateMachine().
Member Data Documentation
matrices_
std::vector<CollisionMatrix*> FUCollisionMatrixIndex::matrices_ private
Stores all collision matrices, including one for the pseudo NOP.
Definition at line 56 of file FUCollisionMatrixIndex.hh.
Referenced by at(), FUCollisionMatrixIndex(), size(), and ~FUCollisionMatrixIndex().
The documentation for this class was generated from the following files:
FUCollisionMatrixIndex.hh
FUCollisionMatrixIndex.cc