OpenASIP: HDB::HDBRegistry Class Reference
HDB::HDBRegistry Class Reference
#include <HDBRegistry.hh>
Public Member Functions
virtual ~HDBRegistry ()
CachedHDBManager & hdb (const std::string fileName)
void loadFromSearchPaths ()
void addHDB (CachedHDBManager *hdbManager)
bool hasHDB (const std::string &hdbFile)
int hdbCount ()
CachedHDBManager & hdb (unsigned int index)
std::string hdbPath (unsigned int index)
int hdbErrorCount ()
std::string hdbErrorMessage (unsigned int index)
Static Public Member Functions
static HDBRegistry & instance ()
Private Member Functions
HDBRegistry ()
HDB registry must be created with instance() method.
void removeDeadHDBPaths ()
Deletes nonexistent HDB paths from registry.
Private Attributes
std::map< const std::string, CachedHDBManager * > registry_
all opened HDBs are stored in this map
std::vector< std::string > errorMessages_
errors found during loading HDBs are strored in this vector
Static Private Attributes
static HDBRegistry * instance_ = NULL
Unique instance of the class.
Detailed Description
Registry for multiple HDBs.
Definition at line 46 of file HDBRegistry.hh.
Constructor & Destructor Documentation
~HDBRegistry()
HDB::HDBRegistry::~HDBRegistry () virtual
Destructor.
Definition at line 52 of file HDBRegistry.cc.
{
    AssocTools::deleteAllValues(registry_);
}
References AssocTools::deleteAllValues(), and registry_.
HDBRegistry()
HDB::HDBRegistry::HDBRegistry () private
HDB registry must be created with instance() method.
Constructor.
Definition at line 46 of file HDBRegistry.cc.
{
}
Referenced by instance().
Member Function Documentation
addHDB()
void HDB::HDBRegistry::addHDB (CachedHDBManager * hdbManager)
Adds HDBManager in to the registry.
Takes responsibility of deleting the given HDBManager.
Parameters
hdb The HDBManager to be added in to the registry.
Definition at line 100 of file HDBRegistry.cc.
{
    if (AssocTools::containsKey(
            registry_, FileSystem::absolutePathOf(hdbManager->fileName()))) {
        delete hdbManager;
        hdbManager = NULL;
        return;
    }
    registry_[FileSystem::absolutePathOf(hdbManager->fileName())] = hdbManager;
}
References FileSystem::absolutePathOf(), AssocTools::containsKey(), HDB::HDBManager::fileName(), and registry_.
Referenced by HDB::CachedHDBManager::instance().
hasHDB()
bool HDB::HDBRegistry::hasHDB (const std::string & hdbFile)
Returns true if the registry contains a HDBManager of the given HDB file.
Parameters
hdbFile The HDB file managed by the HDBManager.
Returns
True if the registry contains a HDBManager of the given HDB file.
Definition at line 119 of file HDBRegistry.cc.
{
    if (AssocTools::containsKey(
            registry_, FileSystem::absolutePathOf(hdbFile))) {
        return true;
    } else {
        return false;
    }
}
References FileSystem::absolutePathOf(), AssocTools::containsKey(), and registry_.
Referenced by HDB::CachedHDBManager::instance().
hdb() [1/2]
CachedHDBManager & HDB::HDBRegistry::hdb (const std::string fileName)
Returns the HDB at given path.
In case the HDB is not found in registry, tries to open it.
Parameters
fileName File name of the HDB.
Returns
The HDB associated with the file name.
Exceptions
Exception In case there was a problem while opening the HDB.
Definition at line 80 of file HDBRegistry.cc.
{
    if (AssocTools::containsKey(
            registry_, FileSystem::absolutePathOf(fileName))) {
        return *registry_[FileSystem::absolutePathOf(fileName)];
    }
    CachedHDBManager* manager = &CachedHDBManager::instance(
        FileSystem::absolutePathOf(fileName));
    registry_[FileSystem::absolutePathOf(fileName)] = manager;
    return *manager;
}
References FileSystem::absolutePathOf(), AssocTools::containsKey(), HDB::CachedHDBManager::instance(), and registry_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::ProcessorGenerator::checkIULatencies(), ProGe::BlockSourceCopier::copyBaseRFFiles(), ProGe::BlockSourceCopier::copyShared(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICDelayOfPath(), DefaultICDecoderEstimator::estimateICEnergy(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), ComponentImplementationSelector::fuImplementations(), CostEstimator::Estimator::functionUnitArea(), CostEstimator::Estimator::functionUnitEnergy(), CostEstimator::Estimator::functionUnitMaximumComputationDelay(), CostEstimator::Estimator::functionUnitPortReadDelay(), CostEstimator::Estimator::functionUnitPortWriteDelay(), ProGeTestBenchGenerator::generate(), ProGeScriptGenerator::getBlockOrder(), HDB::CachedHDBManager::instance(), ComponentImplementationSelector::iuImplementations(), PlatformIntegrator::loadFUExternalPorts(), AddIUFromHDBDialog::loadHDB(), main(), AutoSelectImplementationsDialog::onFind(), BlockImplementationDialog::onHDBSelection(), CostEstimator::Estimator::registerFileArea(), CostEstimator::Estimator::registerFileEnergy(), CostEstimator::Estimator::registerFileMaximumComputationDelay(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), ComponentImplementationSelector::rfImplementations(), ComponentImplementationSelector::selectComponents(), HDBEditorMainFrame::setHDB(), ImplementationSelector::setupSelector(), AddFUFromHDBDialog::TransferDataToWindow(), and AddRFFromHDBDialog::TransferDataToWindow().
hdb() [2/2]
CachedHDBManager & HDB::HDBRegistry::hdb (unsigned int index)
Returns the HDB from given index.
Returns
The HDB from the given index.
Exceptions
OutOfRange Is thrown if index is bigger than the HDB count.
Definition at line 192 of file HDBRegistry.cc.
{
    if (index > (registry_.size() - 1)) {
        throw OutOfRange(__FILE__, __LINE__,
                         "HDBRegistry::hdb(unsigned int)");
    }
    std::map<const std::string, CachedHDBManager*>::const_iterator
        mapIterator = registry_.begin();
    for (unsigned int counter = 0; mapIterator != registry_.end();
         mapIterator++) {
        if (counter == index) {
            break;
        } else {
            counter++;
        }
    }
    return *(*mapIterator).second;
}
References registry_.
hdbCount()
int HDB::HDBRegistry::hdbCount ()
Returns the total number of stored HDBs.
Returns
Count of stored HDBs.
Definition at line 135 of file HDBRegistry.cc.
                      {
    return registry_.size();
}
References registry_.
Referenced by AutoSelectImplementationsDialog::AutoSelectImplementationsDialog(), BlockImplementationDialog::BlockImplementationDialog(), FrequencySweepExplorer::openHDBs(), ComponentImplementationSelector::selectComponents(), ImplementationSelector::setupSelector(), AddFUFromHDBDialog::TransferDataToWindow(), and AddRFFromHDBDialog::TransferDataToWindow().
hdbErrorCount()
int HDB::HDBRegistry::hdbErrorCount ()
Returns the number of error messages created during HDB loading.
Returns
The number of error messages created during HDB loading.
Definition at line 238 of file HDBRegistry.cc.
{
    return errorMessages_.size();
}
References errorMessages_.
Referenced by AddFUFromHDBDialog::TransferDataToWindow(), and AddRFFromHDBDialog::TransferDataToWindow().
hdbErrorMessage()
std::string HDB::HDBRegistry::hdbErrorMessage (unsigned int index)
Returns the error message from given index.
Returns
The error message in given index.
Exceptions
OutOfRange Is thrown if index is bigger than the HDB error count.
Definition at line 251 of file HDBRegistry.cc.
{
    if (index > (errorMessages_.size() - 1)) {
        throw OutOfRange(__FILE__, __LINE__,
                         "HDBRegistry::hdbErrorMessage(unsigned int)");
    }
    return errorMessages_[index];
}
References errorMessages_.
Referenced by AddFUFromHDBDialog::TransferDataToWindow(), and AddRFFromHDBDialog::TransferDataToWindow().
hdbPath()
std::string HDB::HDBRegistry::hdbPath (unsigned int index)
Returns the full path of the HDB with given index.
Returns
The HDB file path.
Exceptions
OutOfRange Is thrown if index is out of range.
Definition at line 217 of file HDBRegistry.cc.
{
    if (index > (registry_.size() - 1)) {
        throw OutOfRange(__FILE__, __LINE__,
                         "HDBRegistry::hdb(unsigned int)");
    }
    std::map<const std::string, CachedHDBManager*>::const_iterator iter =
        registry_.begin();
    for (unsigned c = 0; iter != registry_.end(); iter++) {
        if (c == index) return (*iter).first;
        c++;
    }
    assert(false);
}
References assert, and registry_.
Referenced by AutoSelectImplementationsDialog::AutoSelectImplementationsDialog(), and BlockImplementationDialog::BlockImplementationDialog().
instance()
HDBRegistry & HDB::HDBRegistry::instance () static
Creates and returns an instance of HDB registry.
Returns
An instance of HDB registry.
Definition at line 62 of file HDBRegistry.cc.
                      {
    if (instance_ == NULL) {
        instance_ = new HDBRegistry();
    }
    return *instance_;
}
References HDBRegistry(), and instance_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUToNetlist(), AutoSelectImplementationsDialog::AutoSelectImplementationsDialog(), BlockImplementationDialog::BlockImplementationDialog(), ProGe::ProcessorGenerator::checkIULatencies(), ProGe::BlockSourceCopier::copyBaseRFFiles(), ProGe::BlockSourceCopier::copyShared(), CostEstimator::Estimator::estimateSocketToSocketDelayOfPath(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), ComponentImplementationSelector::fuImplementations(), CostEstimator::Estimator::functionUnitArea(), CostEstimator::Estimator::functionUnitEnergy(), CostEstimator::Estimator::functionUnitMaximumComputationDelay(), CostEstimator::Estimator::functionUnitPortReadDelay(), CostEstimator::Estimator::functionUnitPortWriteDelay(), ProGeTestBenchGenerator::generate(), ProGeScriptGenerator::getBlockOrder(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), HDB::CachedHDBManager::instance(), ComponentImplementationSelector::iuImplementations(), PlatformIntegrator::loadFUExternalPorts(), AddIUFromHDBDialog::loadHDB(), main(), AutoSelectImplementationsDialog::onFind(), BlockImplementationDialog::onHDBSelection(), FrequencySweepExplorer::openHDBs(), CostEstimator::Estimator::registerFileArea(), CostEstimator::Estimator::registerFileEnergy(), CostEstimator::Estimator::registerFileMaximumComputationDelay(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), ComponentImplementationSelector::rfImplementations(), ComponentImplementationSelector::selectComponents(), HDBEditorMainFrame::setHDB(), ImplementationSelector::setupSelector(), AddFUFromHDBDialog::TransferDataToWindow(), AddRFFromHDBDialog::TransferDataToWindow(), and HDBTester::~HDBTester().
loadFromSearchPaths()
void HDB::HDBRegistry::loadFromSearchPaths ()
Definition at line 146 of file HDBRegistry.cc.
{
    // check every HDB path exists, and if doesn't, remove from registry
    removeDeadHDBPaths();
    const std::vector<std::string> hdbPaths = Environment::hdbPaths();
    std::vector<std::string>::const_iterator hdbIter = hdbPaths.begin();
    for(; hdbIter != hdbPaths.end(); hdbIter++) {
        if (!FileSystem::fileExists(*hdbIter) ||
            !FileSystem::fileIsDirectory(*hdbIter) ||
            !FileSystem::fileIsReadable(*hdbIter)) {
            // Directory doesn't exist or can't be read.
            continue;
        }
        std::vector<std::string> dir =
            FileSystem::directoryContents(*hdbIter);
        std::vector<std::string>::const_iterator dirIter = dir.begin();
        for (; dirIter != dir.end(); dirIter++) {
            std::string file = (*dirIter);
            if (file.rfind(".hdb", file.size()) != std::string::npos &&
                file.rfind(".hdb", file.size()) == (file.size() - 4)) {
                if (!AssocTools::containsKey(registry_, file)) {
                    try {
                        CachedHDBManager* manager =
                            &CachedHDBManager::instance(
                                FileSystem::absolutePathOf(file));
                        registry_[FileSystem::absolutePathOf(file)] = manager;
                    } catch (IOException& e) {
                        std::string errorMessage = "Error in '" + file +
                            "': " + e.errorMessage() + ".";
                        errorMessages_.push_back(errorMessage);
                    }
                }
            }
        }
    }
}
References FileSystem::absolutePathOf(), AssocTools::containsKey(), FileSystem::directoryContents(), Exception::errorMessage(), errorMessages_, FileSystem::fileExists(), FileSystem::fileIsDirectory(), FileSystem::fileIsReadable(), Environment::hdbPaths(), HDB::CachedHDBManager::instance(), registry_, and removeDeadHDBPaths().
Referenced by AutoSelectImplementationsDialog::AutoSelectImplementationsDialog(), BlockImplementationDialog::BlockImplementationDialog(), FrequencySweepExplorer::openHDBs(), ImplementationSelector::setupSelector(), AddFUFromHDBDialog::TransferDataToWindow(), and AddRFFromHDBDialog::TransferDataToWindow().
removeDeadHDBPaths()
void HDB::HDBRegistry::removeDeadHDBPaths () private
Deletes nonexistent HDB paths from registry.
Removes nonexistent HDB files from registry.
Definition at line 263 of file HDBRegistry.cc.
{
    std::map<const std::string, CachedHDBManager*>::iterator it;
    for (it = registry_.begin(); it != registry_.end(); ) {
        if (!FileSystem::fileExists(it->first)) {
            registry_.erase(it->first);
            ++it;
        } else {
            ++it;
        }
    }
}
References FileSystem::fileExists(), and registry_.
Referenced by loadFromSearchPaths().
Member Data Documentation
errorMessages_
std::vector<std::string> HDB::HDBRegistry::errorMessages_ private
errors found during loading HDBs are strored in this vector
Definition at line 69 of file HDBRegistry.hh.
Referenced by hdbErrorCount(), hdbErrorMessage(), and loadFromSearchPaths().
instance_
HDBRegistry * HDB::HDBRegistry::instance_ = NULL static private
Unique instance of the class.
Definition at line 71 of file HDBRegistry.hh.
Referenced by instance().
registry_
std::map<const std::string, CachedHDBManager*> HDB::HDBRegistry::registry_ private
all opened HDBs are stored in this map
Definition at line 67 of file HDBRegistry.hh.
Referenced by addHDB(), hasHDB(), hdb(), hdb(), hdbCount(), hdbPath(), loadFromSearchPaths(), removeDeadHDBPaths(), and ~HDBRegistry().
The documentation for this class was generated from the following files:
HDBRegistry.hh
HDBRegistry.cc