OpenASIP: TTAProgram::NullInstruction Class Reference
TTAProgram::NullInstruction Class Reference
#include <NullInstruction.hh>
Public Member Functions
virtual ~NullInstruction ()
Procedure & parent () const
void setParent (const Procedure &proc)
bool isInProcedure () const
void addMove (Move &move)
int moveCount ()
const Move & move (int i) const
void addImmediate (Immediate &imm)
int immediateCount ()
Immediate & immediate (int i)
Address & address () const
int size () const
Public Member Functions inherited from TTAProgram::Instruction
Instruction (const TTAMachine::InstructionTemplate &instructionTemplate=TTAMachine::NullInstructionTemplate::instance())
Instruction (int size, const TTAMachine::InstructionTemplate &instructionTemplate=TTAMachine::NullInstructionTemplate::instance())
~Instruction ()
CodeSnippet & parent () const
void setParent (CodeSnippet &proc)
bool isInProcedure () const
void addMove (std::shared_ptr< Move > move)
int moveCount () const
Move & move (int i) const
std::shared_ptr< Move > movePtr (int i) const
void removeMove (Move &move)
bool isNOP () const
void addImmediate (std::shared_ptr< Immediate > imm)
int immediateCount () const
Immediate & immediate (int i) const
std::shared_ptr< Immediate > immediatePtr (int i) const
void removeImmediate (Immediate &imm)
Address address () const
bool hasFinalAddress () const
short size () const
void setSize (short size)
bool hasRegisterAccesses () const
bool hasConditionalRegisterAccesses () const
bool hasJump () const
bool hasCall () const
bool hasReturn () const
bool hasControlFlowMove () const
Instruction * copy () const
void setInstructionTemplate (const TTAMachine::InstructionTemplate &insTemp)
const TTAMachine::InstructionTemplate & instructionTemplate () const
std::string toString () const
void setFinalAddress (InstructionAddress addr)
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Static Public Member Functions
static NullInstruction & instance ()
Protected Member Functions
NullInstruction ()
Private Member Functions
NullInstruction (const NullInstruction &)
Copying not allowed.
NullInstruction & operator= (const NullInstruction &)
Assignment not allowed.
Static Private Attributes
static NullInstruction instance_
Unique instance of NullInstruction.
Detailed Description
A singleton class that represents a null instruction.
Calling any method causes the program to abort.
Definition at line 45 of file NullInstruction.hh.
Constructor & Destructor Documentation
~NullInstruction()
TTAProgram::NullInstruction::~NullInstruction () virtual
The destructor.
Definition at line 56 of file NullInstruction.cc.
{
}
NullInstruction() [1/2]
TTAProgram::NullInstruction::NullInstruction () protected
The constructor.
Definition at line 49 of file NullInstruction.cc.
                                 :
    Instruction(TTAMachine::NullInstructionTemplate::instance()) {
}
NullInstruction() [2/2]
TTAProgram::NullInstruction::NullInstruction (const NullInstruction &) private
Copying not allowed.
Member Function Documentation
addImmediate()
void TTAProgram::NullInstruction::addImmediate (Immediate & imm)
Aborts program with error log message.
Definition at line 134 of file NullInstruction.cc.
{
    abortWithError("addMove()");
}
References abortWithError.
addMove()
void TTAProgram::NullInstruction::addMove (Move & move)
Aborts program with error log message.
Definition at line 105 of file NullInstruction.cc.
{
    abortWithError("addMove()");
}
References abortWithError.
address()
Address & TTAProgram::NullInstruction::address () const
Aborts program with error log message.
Returns
A null address.
Definition at line 166 of file NullInstruction.cc.
{
    abortWithError("address()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
immediate()
Immediate & TTAProgram::NullInstruction::immediate (int i)
Aborts program with error log message.
Returns
A null immediate.
Definition at line 154 of file NullInstruction.cc.
{
    abortWithError("addMove()");
    // to avoid warning:
    throw new OutOfRange(__FILE__,__LINE__,__func__,"");
}
References __func__, and abortWithError.
immediateCount()
int TTAProgram::NullInstruction::immediateCount ()
Aborts program with error log message.
Returns
-1.
Definition at line 143 of file NullInstruction.cc.
{
    abortWithError("addMove()");
    return -1;
}
References abortWithError.
instance()
NullInstruction & TTAProgram::NullInstruction::instance () static
Returns an instance of NullInstruction class (singleton).
Returns
Singleton instance of NullInstruction class.
Definition at line 66 of file NullInstruction.cc.
{
    return instance_;
}
References instance_.
Referenced by InstructionDictionary::addInstructions(), TTAProgram::CodeLabel::address(), SimulationStatistics::calculate(), CompiledSimUtilizationStats::calculate(), TTAProgram::CodeSnippet::clear(), TTAProgram::CodeSnippet::copy(), TTAProgram::Move::copy(), CodeCompressorPlugin::encodeImmediateTerminal(), TTAProgram::NullProcedure::firstInstruction(), TTAProgram::NullProgram::firstInstruction(), RFAccessTracker::handleEvent(), TTAProgram::CodeSnippet::hasNextInstruction(), TTAProgram::InstructionReference::instruction(), TTAProgram::CodeSnippet::instructionAt(), TTAProgram::NullProcedure::instructionAt(), TTAProgram::NullProgram::instructionAt(), TTAProgram::CodeLabel::instructionReference(), TTAProgram::Move::isInInstruction(), TTAProgram::NullProcedure::lastInstruction(), TTAProgram::NullProgram::lastInstruction(), TTAProgram::NullProgram::nextInstruction(), TTAProgram::Program::nextInstruction(), TTAProgram::CodeSnippet::nextInstruction(), TTAProgram::NullProcedure::nextInstruction(), TTAProgram::Move::parent(), TTAProgram::CodeSnippet::previousInstruction(), TTAProgram::NullProcedure::previousInstruction(), TTAProgram::Instruction::removeMove(), TTAProgram::Move::setParent(), SimpleIfConverter::successors(), InstructionDictionary::updateDictionary(), DisasmTopCountAttrProvider::updateTopCountTable(), TTAProgram::CodeSnippet::~CodeSnippet(), and TTAProgram::Instruction::~Instruction().
isInProcedure()
bool TTAProgram::NullInstruction::isInProcedure () const
Aborts program with error log message.
Returns
False.
Definition at line 96 of file NullInstruction.cc.
{
    abortWithError("isInProcedure()");
    return false;
}
References abortWithError.
move()
const Move & TTAProgram::NullInstruction::move (int i) const
Aborts program with error log message.
Returns
A null move.
Definition at line 125 of file NullInstruction.cc.
{
    abortWithError("addMove()");
    throw OutOfRange(__FILE__,__LINE__,__func__, "Null intruction is empty.");
}
References __func__, and abortWithError.
moveCount()
int TTAProgram::NullInstruction::moveCount ()
Aborts program with error log message.
Returns
-1.
Definition at line 114 of file NullInstruction.cc.
{
    abortWithError("addMove()");
    return -1;
}
References abortWithError.
operator=()
NullInstruction & TTAProgram::NullInstruction::operator= (const NullInstruction &) private
Assignment not allowed.
parent()
Procedure & TTAProgram::NullInstruction::parent () const
Aborts program with error log message.
Returns
A null procedure.
Exceptions
IllegalRegistration never.
Definition at line 77 of file NullInstruction.cc.
{
    abortWithError("parent()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
setParent()
void TTAProgram::NullInstruction::setParent (const Procedure & proc)
Aborts program with error log message.
Definition at line 86 of file NullInstruction.cc.
{
    abortWithError("setParent()");
}
References abortWithError.
size()
int TTAProgram::NullInstruction::size () const
Aborts program with error log message.
Returns
-1.
Definition at line 177 of file NullInstruction.cc.
{
    abortWithError("size()");
    return -1;
}
References abortWithError.
Member Data Documentation
instance_
NullInstruction TTAProgram::NullInstruction::instance_ static private
Unique instance of NullInstruction.
Definition at line 76 of file NullInstruction.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullInstruction.hh
NullInstruction.cc