OpenASIP: XMLSerializer Class Reference
XMLSerializer Class Reference
#include <XMLSerializer.hh>
Public Member Functions
XMLSerializer ()
virtual ~XMLSerializer ()
void setSourceFile (const std::string &fileName)
void setSourceString (const std::string &source)
void setDestinationFile (const std::string &fileName)
void setDestinationString (std::string &destination)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
void setXMLNamespace (std::string nsUri)
virtual ObjectState * readState ()
virtual void writeState (const ObjectState *rootState)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Protected Member Functions
std::string sourceFile () const
Private Member Functions
XMLSerializer (const XMLSerializer &)
Copying forbidden.
XMLSerializer & operator= (const XMLSerializer &)
Assignment forbidden.
void initializeParser ()
virtual ObjectState * readFile (const std::string &fileName)
virtual ObjectState * readString (const std::string &source)
virtual void writeFile (const std::string &fileName, const ObjectState *rootState)
virtual void writeString (std::string &target, const ObjectState *rootState)
DOMDocument * createDOMDocument (const ObjectState *state) const
void ensureValidStream (const std::string &fileName) const
DOMElement * createDOM (ObjectState *state, DOMDocument *doc) const
ObjectState * createState (const DOMNode *node) const
bool hasChildElementNodes (const DOMNode *node) const
Private Attributes
std::string sourceFile_
Source file path.
std::string destinationFile_
Destination file path.
std::string schemaFile_
Schema file path.
bool useSchema_
Indicates if xml file is validated using schema.
DOMBuilder * parser_
The parser that checks the XML file for errors with the Schema.
DOMImplementation * domImplementation_
Implementation of the DOM.
const std::string * sourceString_
Source string to read.
std::string * destinationString_
Destination string to write.
std::string nsUri_
XML namespace URI.
Detailed Description
This class is used to read and write XML. This is a base class for different kind of XML serializers.
Definition at line 62 of file XMLSerializer.hh.
Constructor & Destructor Documentation
XMLSerializer() [1/2]
XMLSerializer::XMLSerializer ()
Constructor.
Definition at line 78 of file XMLSerializer.cc.
                             :
    Serializer(), sourceFile_(""), destinationFile_(""), schemaFile_(""),
    useSchema_(false), parser_(NULL), domImplementation_(NULL),
    sourceString_(NULL), destinationString_(NULL), nsUri_("") {
    XMLPlatformUtils::Initialize();
    const XMLCh gLS[] = {chLatin_L, chLatin_S, chNull};
    domImplementation_ =
        DOMImplementationRegistry::getDOMImplementation(gLS);
#if XERCES_VERSION_MAJOR >= 3
    parser_ = domImplementation_->createLSParser(
            DOMImplementationLS::MODE_SYNCHRONOUS, 0);
#else
    parser_ = domImplementation_->createDOMBuilder(
        DOMImplementationLS::MODE_SYNCHRONOUS, 0);
#endif
}
References domImplementation_, and parser_.
~XMLSerializer()
XMLSerializer::~XMLSerializer () virtual
Destructor.
Definition at line 101 of file XMLSerializer.cc.
{
    delete parser_;
    XMLPlatformUtils::Terminate();
}
References parser_.
XMLSerializer() [2/2]
XMLSerializer::XMLSerializer (const XMLSerializer &) private
Copying forbidden.
Member Function Documentation
createDOM()
DOMElement * XMLSerializer::createDOM (ObjectState * state, DOMDocument * doc) const private
Creates DOM tree from the given ObjectState tree.
Parameters
state Root node of the ObjectState tree.
doc The DOMDocument to which the created DOM tree belongs.
Definition at line 609 of file XMLSerializer.cc.
{
    XMLCh* elemName = Conversion::toXMLCh(state->name());
    DOMElement* rootElem =
        doc->createElement(elemName);
    XMLString::release(&elemName);
    for (int i = 0; i < state->attributeCount(); i++) {
        ObjectState::Attribute* attribute = state->attribute(i);
        XMLCh* attribName = Conversion::toXMLCh(attribute->name);
        XMLCh* attribValue = Conversion::toXMLCh(attribute->value);
        rootElem->setAttribute(attribName, attribValue);
        XMLString::release(&attribName);
        XMLString::release(&attribValue);
    }
    if (state->childCount() == 0) {
        if (state->stringValue() != "") {
            XMLCh* text = Conversion::toXMLCh(state->stringValue());
            DOMText* value = doc->createTextNode(text);
            rootElem->appendChild(value);
            XMLString::release(&text);
        }
    }
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* childState = state->child(i);
        rootElem->appendChild(createDOM(childState, doc));
    }
    return rootElem;
}
References ObjectState::attribute(), ObjectState::attributeCount(), ObjectState::child(), ObjectState::childCount(), createDOM(), ObjectState::Attribute::name, ObjectState::name(), ObjectState::stringValue(), Conversion::toXMLCh(), and ObjectState::Attribute::value.
Referenced by createDOM(), and createDOMDocument().
createDOMDocument()
DOMDocument * XMLSerializer::createDOMDocument (const ObjectState * state) const private
Creates a DOM tree according to the given ObjectState tree.
Parameters
state Root node of the ObjectState tree.
Returns
The created DOM tree.
Definition at line 537 of file XMLSerializer.cc.
{
    XMLCh* nsUri = NULL;
    if (!nsUri_.empty()) {
        nsUri = Conversion::toXMLCh(nsUri_);
    }
    XMLCh* docName = Conversion::toXMLCh(state->name());
    DOMDocument* doc = domImplementation_->createDocument(nsUri, docName, 0);
    XMLString::release(&docName);
    if (nsUri != NULL) {
        XMLString::release(&nsUri);
        nsUri = NULL;
    }
    DOMElement* rootElem = doc->getDocumentElement();
    for (int i = 0; i < state->attributeCount(); i++) {
        ObjectState::Attribute* attribute = state->attribute(i);
        XMLCh* attribName = Conversion::toXMLCh(attribute->name);
        XMLCh* attribValue = Conversion::toXMLCh(attribute->value);
        rootElem->setAttribute(attribName, attribValue);
        XMLString::release(&attribName);
        XMLString::release(&attribValue);
    }
    string value = state->stringValue();
    if (value != "") {
        XMLCh* nodeValue = Conversion::toXMLCh(value);
        DOMText* valueNode = doc->createTextNode(nodeValue);
        rootElem->appendChild(valueNode);
        XMLString::release(&nodeValue);
    }
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* childState = state->child(i);
        DOMElement* childElement = createDOM(childState, doc);
        rootElem->appendChild(childElement);
    }
    return doc;
}
References ObjectState::attribute(), ObjectState::attributeCount(), ObjectState::child(), ObjectState::childCount(), createDOM(), domImplementation_, ObjectState::Attribute::name, ObjectState::name(), nsUri_, ObjectState::stringValue(), Conversion::toXMLCh(), and ObjectState::Attribute::value.
Referenced by writeFile(), and writeString().
createState()
ObjectState * XMLSerializer::createState (const DOMNode * node) const private
Creates a one-to-one ObjectState object (tree) according to the given DOMNode.
Parameters
node DOMNode from which the ObjectState is created.
Returns
The created ObjectState instance (tree).
Definition at line 653 of file XMLSerializer.cc.
{
    ObjectState* state =
        new ObjectState(Conversion::XMLChToString(node->getNodeName()));
    DOMNamedNodeMap* attributes = node->getAttributes();
    // set the attributes
    if (attributes != NULL) {
        for (unsigned int i = 0; i < attributes->getLength(); i++) {
            DOMNode* attribute = attributes->item(i);
            state->setAttribute(
                Conversion::XMLChToString(attribute->getNodeName()),
                Conversion::XMLChToString(attribute->getNodeValue()));
        }
    }
    DOMNode* child = node->getFirstChild();
    while (child != NULL) {
        if (child->getNodeType() == DOMNode::ELEMENT_NODE) {
            state->addChild(createState(child));
        }
        child = child->getNextSibling();
    }
    // if node has no child elements, read its value
    if (!hasChildElementNodes(node)) {
        if (node->getFirstChild() != NULL) {
            state->setValue(Conversion::XMLChToString(node->getFirstChild()->
                                              getNodeValue()));
        }
    }
    return state;
}
References ObjectState::addChild(), createState(), hasChildElementNodes(), ObjectState::setAttribute(), ObjectState::setValue(), and Conversion::XMLChToString().
Referenced by createState(), readFile(), and readString().
ensureValidStream()
void XMLSerializer::ensureValidStream (const std::string & fileName) const private
Checks that the file is OK for reading.
Parameters
fileName Name of the XML file.
Exceptions
UnreachableStream If the given file cannot be read.
Definition at line 587 of file XMLSerializer.cc.
{
    ifstream filestream;
    filestream.open(fileName.c_str());
    if(!filestream.is_open() || !filestream.good()) {
        filestream.close();
        string procName = "XMLSerializer::ensureValidStream";
        string errorMessage = "Cannot open file \'";
        errorMessage += fileName;
        errorMessage += "\'.";
        throw UnreachableStream(__FILE__, __LINE__, procName, errorMessage);
    }
    filestream.close();
}
Referenced by initializeParser(), and readFile().
hasChildElementNodes()
bool XMLSerializer::hasChildElementNodes (const DOMNode * node) const private
Returns true if the given node has child elements.
Parameters
node Node.
Returns
True if the node has child elements, otherwise false.
Definition at line 695 of file XMLSerializer.cc.
{
    DOMNode* child = node->getFirstChild();
    while (child != NULL) {
        if (child->getNodeType() == DOMNode::ELEMENT_NODE) {
            return true;
        }
        child = child->getNextSibling();
    }
    return false;
}
Referenced by createState().
initializeParser()
void XMLSerializer::initializeParser () private
Initializes the XML parser.
Definition at line 234 of file XMLSerializer.cc.
{
    if (useSchema_ && schemaFile_ == "") {
        string errorMsg = "No schema file set.";
        throw SerializerException(__FILE__, __LINE__, __func__, errorMsg);
    }
    if (useSchema_) {
        try {
            ensureValidStream(schemaFile_);
        } catch (UnreachableStream& exception) {
            SerializerException error(__FILE__, __LINE__, __func__,
                exception.errorMessage());
            error.setCause(exception);
            throw error;
        }
        string absoluteSchemaFile = schemaFile_;
        // convert the given schemaFile path to absolute path if it isn't
        if (FileSystem::isRelativePath(schemaFile_)) {
            absoluteSchemaFile = FileSystem::currentWorkingDir() +
                FileSystem::DIRECTORY_SEPARATOR + schemaFile_;
        }
        XMLCh* filePath = Conversion::toXMLCh(absoluteSchemaFile);
#if XERCES_VERSION_MAJOR >= 3
        parser_->getDomConfig()->setParameter(XMLUni::fgXercesSchema, true);
        parser_->getDomConfig()->setParameter(XMLUni::fgDOMValidate, true);
        parser_->getDomConfig()->setParameter(XMLUni::fgDOMNamespaces, true);
        parser_->getDomConfig()->setParameter(
            XMLUni::fgXercesSchemaFullChecking, true);
        parser_->getDomConfig()->setParameter(
            XMLUni::fgXercesSchemaExternalNoNameSpaceSchemaLocation,
            filePath);
#else
        parser_->setFeature(XMLUni::fgXercesSchema, true);
        parser_->setFeature(XMLUni::fgDOMValidation, true);
        parser_->setFeature(XMLUni::fgDOMNamespaces, true);
        parser_->setFeature(XMLUni::fgXercesSchemaFullChecking, true);
        parser_->setProperty(
            XMLUni::fgXercesSchemaExternalNoNameSpaceSchemaLocation,
            filePath);
#endif
        XMLString::release(&filePath);
    }
#if XERCES_VERSION_MAJOR >= 3
    parser_->getDomConfig()->setParameter(
        XMLUni::fgDOMElementContentWhitespace, false);
    parser_->getDomConfig()->setParameter(XMLUni::fgDOMComments, false);
#else
    parser_->setFeature(XMLUni::fgDOMWhitespaceInElementContent, false);
    parser_->setFeature(XMLUni::fgDOMComments, false);
#endif
}
References __func__, FileSystem::currentWorkingDir(), FileSystem::DIRECTORY_SEPARATOR, ensureValidStream(), Exception::errorMessage(), FileSystem::isRelativePath(), parser_, schemaFile_, Exception::setCause(), Conversion::toXMLCh(), and useSchema_.
Referenced by readFile(), and readString().
operator=()
XMLSerializer & XMLSerializer::operator= (const XMLSerializer &) private
Assignment forbidden.
readFile()
ObjectState * XMLSerializer::readFile (const std::string & sourceFile) private virtual
Reads current XML file set and creates an ObjectState tree according to it.
The XML file is validated with the current schema file if the setting is on.
Returns
Root node of the created ObjectState tree.
Exceptions
SerializerException If an error occurs while reading.
Definition at line 368 of file XMLSerializer.cc.
{
    initializeParser();
    DOMDocument* dom = NULL;
    if (sourceFile == "") {
        string errorMsg = "No source file set.";
        throw SerializerException(__FILE__, __LINE__, __func__, errorMsg);
    }
    // check validity of file stream
    try {
        ensureValidStream(sourceFile);
    } catch (UnreachableStream& exception) {
        throw SerializerException(__FILE__, __LINE__, __func__,
            exception.errorMessage());
    }
    DOMBuilderErrorHandler* errHandler = new DOMBuilderErrorHandler();
#if XERCES_VERSION_MAJOR >= 3
    parser_->getDomConfig()->setParameter(
        XMLUni::fgDOMErrorHandler, errHandler);
#else
    parser_->setErrorHandler(errHandler);
#endif
    try {
        parser_->resetDocumentPool();
        dom = parser_->parseURI(sourceFile.c_str());
    } catch (const ErrorInExternalFile& exception) {
        string errorLog = errHandler->errorLog();
        delete errHandler;
        throw SerializerException(__FILE__, __LINE__, __func__, errorLog);
    }
    if (dom == NULL || dom->getDocumentElement() == NULL) {
        delete errHandler;
        throw SerializerException(
            __FILE__, __LINE__, __func__, "Illegal file: " + sourceFile);
    }
    int errors(errHandler->errorCount());
    if (errors > 0) {
        // if there were such errors in xml file or schema file that
        // exception was not thrown when parseURI was called
        string errorLog = errHandler->errorLog();
        delete errHandler;
        throw SerializerException(__FILE__, __LINE__, __func__, errorLog);
    }
    ObjectState* rootState = createState(dom->getDocumentElement());
    delete errHandler;
    return rootState;
}
References __func__, createState(), ensureValidStream(), DOMBuilderErrorHandler::errorCount(), DOMBuilderErrorHandler::errorLog(), Exception::errorMessage(), initializeParser(), parser_, and sourceFile().
Referenced by readState().
readState()
ObjectState * XMLSerializer::readState () virtual
Reads object state from a file or string.
File is read if a source file is set with setSourceFile(). String is read if a source string is set with setSourceString(). Only the last file/string set will be read.
Implements TCETools::Serializer.
Reimplemented in IPXactSerializer, GUIOptionsSerializer, BEMSerializer, IDF::IDFSerializer, and ADFSerializer.
Definition at line 200 of file XMLSerializer.cc.
{
    if (sourceFile_ != "") {
        return readFile(sourceFile_);
    } else if (sourceString_ != NULL) {
        return readString(*sourceString_);
    } else {
        string errorMsg = "No Source file or string set.";
        throw SerializerException(__FILE__, __LINE__, __func__, errorMsg);
    }
}
References __func__, readFile(), readString(), sourceFile_, and sourceString_.
Referenced by BlocksModel::BlocksModel(), GUIOptionsSerializer::readState(), BEMSerializer::readState(), IDF::IDFSerializer::readState(), ADFSerializer::readState(), OperationSerializer::readState(), and OSEdOptionsSerializer::readState().
readString()
ObjectState * XMLSerializer::readString (const std::string & source) private virtual
Reads object state from an xml string.
Parameters
XML to read as an string containing the entire xml document.
Returns
Root node of the created ObjectState tree.
Exceptions
SerializerException If an error occurs while reading.
Definition at line 301 of file XMLSerializer.cc.
{
    initializeParser();
    DOMDocument* dom = NULL;
    DOMBuilderErrorHandler* errHandler = new DOMBuilderErrorHandler();
#if XERCES_VERSION_MAJOR >= 3
    parser_->getDomConfig()->setParameter(
        XMLUni::fgDOMErrorHandler, errHandler);
#else
    parser_->setErrorHandler(errHandler);
#endif
    // build the DOM object
    try {
        parser_->resetDocumentPool();
        MemBufInputSource* buf = new MemBufInputSource(
            (const XMLByte*)source.c_str(),
            source.length(),
            "sourceXML",
            false);
        Wrapper4InputSource* domBuf = new Wrapper4InputSource(buf);
#if XERCES_VERSION_MAJOR >= 3
        dom = parser_->parse(domBuf);
#else
        dom = parser_->parse(*domBuf);
#endif
        delete domBuf;
    } catch(...) {
        string errorLog = errHandler->errorLog();
        delete errHandler;
        throw SerializerException(__FILE__, __LINE__, __func__, errorLog);
    }
    int errors(errHandler->errorCount());
    if (errors > 0) {
        // if there were such errors in xml file or schema file that
        // exception was not thrown when parseURI was called
        string errorLog = errHandler->errorLog();
        delete errHandler;
        throw SerializerException(__FILE__, __LINE__, __func__, errorLog);
    }
    if (dom == NULL || dom->getDocumentElement() == NULL) {
        delete errHandler;
        throw SerializerException(
            __FILE__, __LINE__, __func__, "Illegal file: " + source);
    }
    ObjectState* rootState = createState(dom->getDocumentElement());
    delete errHandler;
    errHandler = NULL;
    return rootState;
}
References __func__, createState(), DOMBuilderErrorHandler::errorCount(), DOMBuilderErrorHandler::errorLog(), initializeParser(), and parser_.
Referenced by readState().
setDestinationFile()
void XMLSerializer::setDestinationFile (const std::string & fileName)
Sets the destination file used when writeState is called.
Previously set destination file or string is unset.
Parameters
fileName Relative or absolute path of the destination file, e.g. /home/openasip/file.xml or ./file.xml.
Definition at line 142 of file XMLSerializer.cc.
{
    destinationFile_ = fileName;
    destinationString_ = NULL;
}
References destinationFile_, and destinationString_.
Referenced by CompileTools::compileAsC(), CompileTools::compileAsLLVM(), ProximQuitCmd::Do(), SaveOptionsCmd::Do(), ProcessorImplementationWindow::doSaveIDF(), main(), GenerateProcessorDialog::onOK(), MDFDocument::OnSaveDocument(), DesignSpaceExplorer::schedule(), OperationSerializer::setDestinationFile(), OSEdOptionsSerializer::setDestinationFile(), DSDBManager::writeArchitectureToFile(), DSDBManager::writeImplementationToFile(), IPXactFileGenerator::writeProjectFiles(), TTAMachine::Machine::writeToADF(), and DataDependenceGraph::writeToXMLFile().
setDestinationString()
void XMLSerializer::setDestinationString (std::string & target)
Sets the destination string used when writeState is called.
Previously set destination file or string is unset.
Parameters
target Target string to write.
Definition at line 156 of file XMLSerializer.cc.
{
    destinationString_ = &target;
    destinationFile_ = "";
}
References destinationFile_, and destinationString_.
Referenced by DSDBManager::addArchitecture(), DSDBManager::addImplementation(), and TTAMachine::Machine::hash().
setSchemaFile()
void XMLSerializer::setSchemaFile (const std::string & fileName)
Sets the schema file used to validate xml files.
Parameters
fileName Relative or absolute path of the schema file, e.g. /home/openasip/schema.xsd or ./schema.xsd.
Definition at line 168 of file XMLSerializer.cc.
{
    schemaFile_ = fileName;
}
References schemaFile_.
Referenced by ADFSerializer::ADFSerializer(), BEMSerializer::BEMSerializer(), IDF::IDFSerializer::IDFSerializer(), Proxim::loadOptions(), ProDe::OnInit(), OperationSerializer::setSchemaFile(), and OSEdOptionsSerializer::setSchemaFile().
setSourceFile()
void XMLSerializer::setSourceFile (const std::string & fileName)
Sets the source file used when readState is called.
Previously set source file or string is unset.
Parameters
fileName Relative or absolute path of the source file, e.g. /home/openasip/file.xml or ./file.xml.
Definition at line 115 of file XMLSerializer.cc.
{
    sourceFile_ = fileName;
    sourceString_ = NULL;
}
References sourceFile_, and sourceString_.
Referenced by BlocksModel::BlocksModel(), llvm::TCETargetMachine::createMachine(), AddFUArchFromADFCmd::Do(), loadBEM(), ProGe::ProGeUI::loadBinaryEncoding(), TTAMachine::Machine::loadFromADF(), IDF::MachineImplementation::loadFromIDF(), loadInputs(), ProGe::ProGeUI::loadMachine(), loadMachine(), loadMachine(), SimulatorFrontend::loadMachine(), ProGe::ProGeUI::loadMachineImplementation(), Proxim::loadOptions(), ProGe::ProGeUI::loadProcessorConfiguration(), main(), Model::Model(), GenerateProcessorDialog::onBrowseBEMLoad(), ProDe::OnInit(), ProcessorImplementationWindow::onLoadIDF(), readAdf(), readIdf(), OperationSerializer::setSourceFile(), OSEdOptionsSerializer::setSourceFile(), and llvm::TCEStubTargetMachine::TCEStubTargetMachine().
setSourceString()
void XMLSerializer::setSourceString (const std::string & source)
Sets the source string used when readState is called.
Previously set source file or string is unset.
Parameters
source Source string to read.
Definition at line 128 of file XMLSerializer.cc.
{
    sourceString_ = &source;
    sourceFile_ = "";
}
References sourceFile_, and sourceString_.
Referenced by DSDBManager::architecture(), DSDBManager::implementation(), DSDBManager::writeArchitectureToFile(), and DSDBManager::writeImplementationToFile().
setUseSchema()
void XMLSerializer::setUseSchema (bool useSchema)
Sets/unsets validation of xml files using xml schema.
Parameters
useSchema True sets and false unsets validation. Default value is false.
Definition at line 179 of file XMLSerializer.cc.
{
    useSchema_ = useSchema;
}
References useSchema_.
Referenced by ADFSerializer::ADFSerializer(), BEMSerializer::BEMSerializer(), IDF::IDFSerializer::IDFSerializer(), IPXactSerializer::IPXactSerializer(), Proxim::loadOptions(), ProDe::OnInit(), OperationSerializer::setUseSchema(), and OSEdOptionsSerializer::setUseSchema().
setXMLNamespace()
void XMLSerializer::setXMLNamespace (std::string nsUri)
Sets the XML namespace URI to be used when creating a DOM document
Definition at line 188 of file XMLSerializer.cc.
{
    nsUri_ = nsUri;
}
References nsUri_.
Referenced by IPXactSerializer::writeState().
sourceFile()
std::string XMLSerializer::sourceFile () const protected
Returns the source file that is set.
Returns
The source file.
Definition at line 526 of file XMLSerializer.cc.
{
    return sourceFile_;
}
References sourceFile_.
Referenced by readFile(), and IDF::IDFSerializer::readState().
writeFile()
void XMLSerializer::writeFile (const std::string & destinationFile, const ObjectState * rootState) private virtual
Writes the given ObjectState tree into the current XML file set.
Parameters
rootState The root object of the ObjectState tree.
Exceptions
SerializerException If the destination file cannot be written.
Definition at line 435 of file XMLSerializer.cc.
{
#if XERCES_VERSION_MAJOR >= 3
    DOMLSSerializer* domWriter = domImplementation_->createLSSerializer();
    domWriter->getDomConfig()->setParameter(
        XMLUni::fgDOMWRTFormatPrettyPrint, true);
    DOMLSOutput* lsOutput = domImplementation_->createLSOutput();
#else
    DOMWriter* domWriter = domImplementation_->createDOMWriter();
    domWriter->setFeature(XMLUni::fgDOMWRTFormatPrettyPrint, true);
#endif
    DOMDocument* document = createDOMDocument(rootState);
    try {
        if (!FileSystem::fileIsCreatable(destinationFile) &&
            !FileSystem::fileIsWritable(destinationFile)) {
            throw "";
        }
#if XERCES_VERSION_MAJOR >= 3
        LocalFileFormatTarget targetFile(destinationFile.c_str());
        lsOutput->setByteStream(&targetFile);
        domWriter->write(document, lsOutput);
        domWriter->release();
        delete lsOutput;
#else
        LocalFileFormatTarget targetFile(destinationFile.c_str());
        domWriter->writeNode(&targetFile, *document);
        domWriter->release();
        delete document;
#endif
    } catch (...) {
#if XERCES_VERSION_MAJOR >= 3
        domWriter->release();
        delete lsOutput;
#else
        delete document;
#endif
        string errorMessage = "Cannot write to " + destinationFile;
        throw SerializerException(__FILE__, __LINE__, __func__,
            errorMessage);
    }
}
References __func__, createDOMDocument(), domImplementation_, FileSystem::fileIsCreatable(), and FileSystem::fileIsWritable().
Referenced by writeState().
writeState()
void XMLSerializer::writeState (const ObjectState * state) virtual
Writes the given object state to a file or string.
File is written if a destiantion file is set with setDestinationFile(). String is written if a destination string is set with setDestinationString(). Only the last file/string set will be written.
Implements TCETools::Serializer.
Reimplemented in IPXactSerializer, ADFSerializer, GUIOptionsSerializer, BEMSerializer, and IDF::IDFSerializer.
Definition at line 219 of file XMLSerializer.cc.
{
    if (destinationFile_ != "") {
        writeFile(destinationFile_, state);
    } else if (destinationString_ != NULL) {
        writeString(*destinationString_, state);
    } else {
        string errorMsg = "No destination file or string set.";
        throw SerializerException(__FILE__, __LINE__, __func__, errorMsg);
    }
}
References __func__, destinationFile_, destinationString_, writeFile(), and writeString().
Referenced by IPXactSerializer::writeState(), ADFSerializer::writeState(), GUIOptionsSerializer::writeState(), BEMSerializer::writeState(), IDF::IDFSerializer::writeState(), OperationSerializer::writeState(), OSEdOptionsSerializer::writeState(), and DataDependenceGraph::writeToXMLFile().
writeString()
void XMLSerializer::writeString (std::string & target, const ObjectState * rootState) private virtual
Writes the given ObjectState tree to a target string.
Parameters
rootState The root object of the ObjectState tree.
Exceptions
SerializerException If the destination file cannot be written.
Definition at line 485 of file XMLSerializer.cc.
{
#if XERCES_VERSION_MAJOR >= 3
    DOMLSSerializer* domWriter = domImplementation_->createLSSerializer();
    domWriter->getDomConfig()->setParameter(
        XMLUni::fgDOMWRTFormatPrettyPrint, true);
    DOMLSOutput* lsOutput = domImplementation_->createLSOutput();
#else
    DOMWriter* domWriter = domImplementation_->createDOMWriter();
    domWriter->setFeature(XMLUni::fgDOMWRTFormatPrettyPrint, true);
#endif
    DOMDocument* document = createDOMDocument(rootState);
    try {
        target.clear();
#if XERCES_VERSION_MAJOR >= 3
        MemBufFormatTarget* buf = new MemBufFormatTarget();
        lsOutput->setByteStream(buf);
        domWriter->write(document, lsOutput);
#else
        MemBufFormatTarget* buf = new MemBufFormatTarget();
        domWriter->writeNode(buf, *document);
#endif
        target.append((char*)(buf->getRawBuffer()));
        domWriter->release();
        delete buf;
        delete document;
    } catch (...) {
        domWriter->release();
        delete document;
        string errorMessage = "Error writing xml to a string.";
        throw SerializerException(__FILE__, __LINE__, __func__,
            errorMessage);
    }
}
References __func__, createDOMDocument(), and domImplementation_.
Referenced by writeState().
Member Data Documentation
destinationFile_
std::string XMLSerializer::destinationFile_ private
Destination file path.
Definition at line 114 of file XMLSerializer.hh.
Referenced by setDestinationFile(), setDestinationString(), and writeState().
destinationString_
std::string* XMLSerializer::destinationString_ private
Destination string to write.
Definition at line 131 of file XMLSerializer.hh.
Referenced by setDestinationFile(), setDestinationString(), and writeState().
domImplementation_
DOMImplementation* XMLSerializer::domImplementation_ private
Implementation of the DOM.
Definition at line 126 of file XMLSerializer.hh.
Referenced by createDOMDocument(), writeFile(), writeString(), and XMLSerializer().
nsUri_
std::string XMLSerializer::nsUri_ private
XML namespace URI.
Definition at line 134 of file XMLSerializer.hh.
Referenced by createDOMDocument(), and setXMLNamespace().
parser_
DOMBuilder* XMLSerializer::parser_ private
The parser that checks the XML file for errors with the Schema.
Definition at line 123 of file XMLSerializer.hh.
Referenced by initializeParser(), readFile(), readString(), XMLSerializer(), and ~XMLSerializer().
schemaFile_
std::string XMLSerializer::schemaFile_ private
Schema file path.
Definition at line 116 of file XMLSerializer.hh.
Referenced by initializeParser(), and setSchemaFile().
sourceFile_
std::string XMLSerializer::sourceFile_ private
Source file path.
Definition at line 112 of file XMLSerializer.hh.
Referenced by readState(), setSourceFile(), setSourceString(), and sourceFile().
sourceString_
const std::string* XMLSerializer::sourceString_ private
Source string to read.
Definition at line 129 of file XMLSerializer.hh.
Referenced by readState(), setSourceFile(), and setSourceString().
useSchema_
bool XMLSerializer::useSchema_ private
Indicates if xml file is validated using schema.
Definition at line 118 of file XMLSerializer.hh.
Referenced by initializeParser(), and setUseSchema().
The documentation for this class was generated from the following files:
XMLSerializer.hh
XMLSerializer.cc