OpenASIP: SymbolAddressCommand Class Reference
SymbolAddressCommand Class Reference
#include <SymbolAddressCommand.hh>
Public Member Functions
SymbolAddressCommand ()
virtual ~SymbolAddressCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "symbol_address" command of the Simulator Control Language.
Definition at line 48 of file SymbolAddressCommand.hh.
Constructor & Destructor Documentation
SymbolAddressCommand()
SymbolAddressCommand::SymbolAddressCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 53 of file SymbolAddressCommand.cc.
                                           :
    SimControlLanguageCommand("symbol_address") {
}
~SymbolAddressCommand()
SymbolAddressCommand::~SymbolAddressCommand () virtual
Destructor.
Does nothing.
Definition at line 62 of file SymbolAddressCommand.cc.
{
}
Member Function Documentation
execute()
bool SymbolAddressCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "symbol_address" command.
Prints the address of a data symbol.
Parameters
arguments The symbol to print.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 75 of file SymbolAddressCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 1, 1)) {
        return false;
    }
    if (!checkProgramLoaded()) {
        return false;
    }
    const TTAProgram::GlobalScope& globalScope =
        simulatorFrontend().program().globalScopeConst();
    try {
        TTAProgram::Address address =
            globalScope.dataLabel(arguments.at(1).stringValue()).address();
        interpreter()->setResult(static_cast<int>(address.location()));
        interpreter()->setError(false);
        return true;
    } catch (const KeyNotFound&) {
        // couldn't evaluate the label
        interpreter()->setResult(
            "Symbol not found. Try adding '_' prefix to the symbol, "
            "e.g. '_foo'.");
        interpreter()->setError(true);
        return false;
    }
}
References TTAProgram::Label::address(), CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkProgramLoaded(), TTAProgram::Scope::dataLabel(), TTAProgram::Program::globalScopeConst(), CustomCommand::interpreter(), TTAProgram::Address::location(), SimulatorFrontend::program(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), and SimControlLanguageCommand::simulatorFrontend().
helpText()
std::string SymbolAddressCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 111 of file SymbolAddressCommand.cc.
{
    return "Returns the address of the given data symbol (global variable).";
}
The documentation for this class was generated from the following files:
SymbolAddressCommand.hh
SymbolAddressCommand.cc