OpenASIP: OSEdBuildCmd Class Reference
OSEdBuildCmd Class Reference
#include <OSEdBuildCmd.hh>
Public Member Functions
OSEdBuildCmd ()
virtual ~OSEdBuildCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdBuildCmd (const OSEdBuildCmd &)
Copying not allowed.
OSEdBuildCmd & operator= (const OSEdBuildCmd &)
Assignment not allowed.
Detailed Description
Command that builds a module.
Definition at line 43 of file OSEdBuildCmd.hh.
Constructor & Destructor Documentation
OSEdBuildCmd() [1/2]
OSEdBuildCmd::OSEdBuildCmd ()
Constructor.
Definition at line 56 of file OSEdBuildCmd.cc.
                           :
    GUICommand(OSEdConstants::CMD_NAME_BUILD, NULL) {
}
Referenced by create().
~OSEdBuildCmd()
OSEdBuildCmd::~OSEdBuildCmd () virtual
Destructor.
Definition at line 63 of file OSEdBuildCmd.cc.
{
}
OSEdBuildCmd() [2/2]
OSEdBuildCmd::OSEdBuildCmd (const OSEdBuildCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdBuildCmd::create () const virtual
Creates a new command.
Returns
A new command.
Implements GUICommand.
Definition at line 82 of file OSEdBuildCmd.cc.
{
    return new OSEdBuildCmd();
}
References OSEdBuildCmd().
Do()
bool OSEdBuildCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 92 of file OSEdBuildCmd.cc.
                 {
    wxWindow* simulateDialog =
        wxGetApp().mainFrame()->FindWindowByName(SimulateDialog::DIALOG_NAME);
    if (simulateDialog != NULL) {
        simulateDialog->Close();
    }
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    wxStatusBar* statusBar = wxGetApp().mainFrame()->statusBar();
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    string modName = treeView->selectedModule();
    wxTreeItemId modId = treeView->selectedModuleId();
    string pathName = treeView->pathOfModule(modId);
    OperationModule& module = OperationContainer::module(pathName, modName);
    format fmt = texts.text(OSEdTextGenerator::TXT_STATUS_COMPILING);
    fmt % module.name();
    statusBar->SetStatusText(WxConversion::toWxString(fmt.str()));
    vector<string> output;
    output.push_back(module.name() + ":\n");
    OperationBuilder& builder = OperationBuilder::instance();
    size_t oldSize = output.size();
    wxStopWatch sw;
    wxBusyCursor* busy = new wxBusyCursor();
    builder.buildObject(
        module.name(), module.behaviorSourceModule(), pathName, output);
    delete busy;
    sw.Pause();
    if (oldSize == output.size()) {
        fmt = texts.text(OSEdTextGenerator::TXT_STATUS_COMPILE_SUCCESS);
        fmt % sw.Time();
        statusBar->SetStatusText(WxConversion::toWxString(fmt.str()));
    } else {
        fmt = texts.text(OSEdTextGenerator::TXT_STATUS_COMPILE_FAILED);
        statusBar->SetStatusText(WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_BUILD_RESULT_DIALOG_TITLE);
        ResultDialog dialog(parentWindow(), output, fmt.str(),
                            module.behaviorSourceModule());
        dialog.ShowModal();
    }
    return true;
}
References OperationBuilder::buildObject(), SimulateDialog::DIALOG_NAME, OperationBuilder::instance(), OSEdTextGenerator::instance(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OSEdTreeView::selectedModule(), OSEdTreeView::selectedModuleId(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUILD_RESULT_DIALOG_TITLE, OSEdTextGenerator::TXT_STATUS_COMPILE_FAILED, OSEdTextGenerator::TXT_STATUS_COMPILE_SUCCESS, and OSEdTextGenerator::TXT_STATUS_COMPILING.
icon()
string OSEdBuildCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 169 of file OSEdBuildCmd.cc.
{
    return "";
}
id()
int OSEdBuildCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 72 of file OSEdBuildCmd.cc.
                       {
    return OSEdConstants::CMD_BUILD;
}
References OSEdConstants::CMD_BUILD.
isEnabled()
bool OSEdBuildCmd::isEnabled () virtual
Returns true if command is enabled.
Command is enabled when module with behavior source file has been selected.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 150 of file OSEdBuildCmd.cc.
{
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTreeView* treeView = mainFrame->treeView();
    string modName = treeView->selectedModule();
    if (modName == "") {
        return false;
    }
    wxTreeItemId modId = treeView->selectedModuleId();
    string pathName = treeView->pathOfModule(modId);
    OperationModule& module = OperationContainer::module(pathName, modName);
    return module.hasBehaviorSource();
}
References OSEdTreeView::pathOfModule(), OSEdTreeView::selectedModule(), OSEdTreeView::selectedModuleId(), and OSEdMainFrame::treeView().
operator=()
OSEdBuildCmd & OSEdBuildCmd::operator= (const OSEdBuildCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdBuildCmd.hh
OSEdBuildCmd.cc