OpenASIP: TTAMachine::RFPort Class Reference
TTAMachine::RFPort Class Reference
#include <RFPort.hh>
Public Member Functions
RFPort (const std::string &name, BaseRegisterFile &parent)
RFPort (const ObjectState *state, Unit &parent)
virtual ~RFPort ()
virtual int width () const
BaseRegisterFile * parentUnit () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Port
Port (const std::string &name, Unit &parentUnit)
Port (const ObjectState *state, Unit &parentUnit)
virtual ~Port ()
virtual std::string name () const
virtual void setName (const std::string &name)
virtual void attachSocket (Socket &socket)
virtual void detachSocket (Socket &socket)
virtual void detachAllSockets ()
Unit * parentUnit () const
virtual Socket * inputSocket () const
virtual Socket * outputSocket () const
virtual Socket * unconnectedSocket (int index) const
virtual int socketCount () const
virtual bool isConnectedTo (const Socket &socket) const
virtual bool isOutput () const
virtual bool isInput () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_RFPORT = "rf_port"
ObjectState name for register file port.
Static Public Attributes inherited from TTAMachine::Port
static const std::string OSNAME_PORT = "port"
ObjectState name for Port.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_FIRST_SOCKET = "1_socket"
ObjectState attribute key for the name of the connected socket.
static const std::string OSKEY_SECOND_SOCKET = "2_socket"
ObjectState attribute key for the name of the other connected socket.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Port
Port (const std::string &name, FunctionUnit &parentUnit)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
RFPort instances are used as ports of register files.
Definition at line 45 of file RFPort.hh.
Constructor & Destructor Documentation
RFPort() [1/2]
TTAMachine::RFPort::RFPort (const std::string & name, BaseRegisterFile & parent)
The constructor.
Parameters
name Name of the port.
parent The parent register file of the port.
Exceptions
InvalidName If the given name is not a valid component name.
ComponentAlreadyExists If there is another port with the same name in the parent unit.
Definition at line 54 of file RFPort.cc.
    : Port(name, parent) {}
RFPort() [2/2]
TTAMachine::RFPort::RFPort (const ObjectState * state, Unit & parent)
The constuctor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent unit of the port.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 67 of file RFPort.cc.
: Port(state, parent) {}
~RFPort()
TTAMachine::RFPort::~RFPort () virtual
The destructor.
Definition at line 72 of file RFPort.cc.
                {
}
Member Function Documentation
loadState()
void TTAMachine::RFPort::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state An ObjectState instance representing state of an RFPort.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Reimplemented from TTAMachine::Port.
Definition at line 119 of file RFPort.cc.
{
    if (state->name() != OSNAME_RFPORT) {
        const string procName = "RFPort::loadState";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Port::loadState(state);
}
References TTAMachine::Port::loadState(), ObjectState::name(), and OSNAME_RFPORT.
parentUnit()
BaseRegisterFile * TTAMachine::RFPort::parentUnit () const
Returns the parent register file.
Returns
The parent register file.
Definition at line 93 of file RFPort.cc.
{
    return static_cast<BaseRegisterFile*>(Port::parentUnit());
}
References TTAMachine::Port::parentUnit().
Referenced by FullyConnectedCheck::connectIUPort(), FullyConnectedCheck::connectRFPort(), InterpolatingRFEstimator::estimatePortReadDelay(), InterpolatingRFEstimator::estimatePortWriteDelay(), CostEstimator::Estimator::longestPath(), BEMGenerator::needsSocketCodeTable(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), width(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
saveState()
ObjectState * TTAMachine::RFPort::saveState () const virtual
Saves the state of the object to an ObjectState tree and returns it.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::Port.
Definition at line 104 of file RFPort.cc.
{
    ObjectState* state = Port::saveState();
    state->setName(OSNAME_RFPORT);
    return state;
}
References OSNAME_RFPORT, TTAMachine::Port::saveState(), and ObjectState::setName().
width()
int TTAMachine::RFPort::width () const virtual
Returns the bit width of the port.
Returns
The bit width of the port.
Implements TTAMachine::Port.
Definition at line 82 of file RFPort.cc.
                    {
    return parentUnit()->width();
}
References parentUnit(), and TTAMachine::BaseRegisterFile::width().
Member Data Documentation
OSNAME_RFPORT
const string TTAMachine::RFPort::OSNAME_RFPORT = "rf_port" static
ObjectState name for register file port.
Definition at line 58 of file RFPort.hh.
Referenced by ADFSerializer::immediateUnitToMDF(), loadState(), TTAMachine::Unit::loadState(), TTAMachine::Unit::loadStateWithoutReferences(), ADFSerializer::machineRFPort(), and saveState().
The documentation for this class was generated from the following files:
RFPort.hh
RFPort.cc