OpenASIP: GraphNode Class Reference
GraphNode Class Reference
#include <GraphNode.hh>
Classes
class Comparator
Public Member Functions
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
virtual GraphNode * clone () const
int nodeID () const
virtual std::string toString () const
virtual std::string dotString () const
Private Attributes
int nodeID_
Static Private Attributes
static int idCounter_ = 0
Detailed Description
Node of the graph-based program representation.
Definition at line 42 of file GraphNode.hh.
Constructor & Destructor Documentation
GraphNode() [1/2]
GraphNode::GraphNode (int nodeID) inline
Definition at line 45 of file GraphNode.hh.
: nodeID_(nodeID) {}
GraphNode() [2/2]
GraphNode::GraphNode ()
Definition at line 37 of file GraphNode.cc.
: nodeID_(idCounter_++) {}
Referenced by clone().
~GraphNode()
GraphNode::~GraphNode () virtual
Definition at line 39 of file GraphNode.cc.
{ }
Member Function Documentation
clone()
GraphNode * GraphNode::clone () const virtual
Clones node. Needed for dynamic binding, when copying instances through the base class.
Returns
Dynamically allocated copy of the node.
Reimplemented in ConstantNode, OperationNode, and TerminalNode.
Definition at line 48 of file GraphNode.cc.
                       {
    return new GraphNode(*this);
}
References GraphNode().
dotString()
std::string GraphNode::dotString () const virtual
Returns the string that should be placed in the node's properties section in the GraphViz Dot string.
This can be overridden in the derived class to add different properties (e.g., colors, etc.) to different type of nodes. The default implementation only sets the label property.
Returns
String describing the Dot properties of the Node.
Reimplemented in MIDDGNode, ProgramDependenceNode, and MoveNode.
Definition at line 76 of file GraphNode.cc.
{
    return std::string("label=\"") + toString() + "\"";
}
References toString().
Referenced by MoveNode::dotString().
nodeID()
int GraphNode::nodeID () const inline
Referenced by SimpleIfConverter::canConvert(), FUGen::constantName(), SimpleIfConverter::detectDiamond(), SimpleIfConverter::detectTriangleViaFt(), SimpleIfConverter::detectTriangleViaJump(), MachineInstrDDG::dotString(), DataDependenceGraph::dotString(), ResourceConstraintAnalyzer::dumpGraphWithStats(), BBSchedulerController::executeDDGPass(), BFPushMoveUp::operator()(), RLPriorityNodeId::operator()(), RLPriorityCriticalPath::operator()(), RLBUPriorityCriticalPath::operator()(), DataDependenceEdge::saveState(), FUGen::subOpName(), ControlDependenceNode::toString(), ProgramDependenceNode::toString(), toString(), MoveNode::toString(), PreOptimizer::tryToOptimizeAddressReg(), and DataDependenceGraph::writeToXMLFile().
toString()
std::string GraphNode::toString () const virtual
Returns a node description as a string.
Used for printing graph into .dot file. This is used for a label in the default dotString() implementation.
Returns
The node ID as a string.
Reimplemented in ControlDependenceNode, BasicBlockNode, ProgramDependenceNode, ConstantNode, OperationNode, TerminalNode, and MoveNode.
Definition at line 61 of file GraphNode.cc.
{
    return Conversion::toString(nodeID());
}
References nodeID(), and Conversion::toString().
Referenced by ControlDependenceGraph::computeEECInfo(), ProgramDependenceGraph::computeEECInfo(), dotString(), ControlDependenceGraph::entryNode(), ProgramDependenceGraph::processPredicate(), ControlDependenceGraph::regionHelper(), and OperationDAGConverter::writeNode().
Member Data Documentation
idCounter_
int GraphNode::idCounter_ = 0 static private
Definition at line 64 of file GraphNode.hh.
nodeID_
int GraphNode::nodeID_ private
Definition at line 63 of file GraphNode.hh.
The documentation for this class was generated from the following files:
GraphNode.hh
GraphNode.cc