OpenASIP: EditOptionsCmd Class Reference
EditOptionsCmd Class Reference
#include <EditOptionsCmd.hh>
Public Member Functions
EditOptionsCmd ()
virtual ~EditOptionsCmd ()
virtual bool Do ()
virtual int id () const
virtual EditOptionsCmd * create () const
virtual std::string shortName () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing editor options.
Creates and shows an OptionsDialog.
Definition at line 42 of file EditOptionsCmd.hh.
Constructor & Destructor Documentation
EditOptionsCmd()
EditOptionsCmd::EditOptionsCmd ()
The Constructor.
Definition at line 45 of file EditOptionsCmd.cc.
                              :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_OPTIONS) {
}
Referenced by create().
~EditOptionsCmd()
EditOptionsCmd::~EditOptionsCmd () virtual
The Destructor.
Definition at line 54 of file EditOptionsCmd.cc.
{
}
Member Function Documentation
create()
EditOptionsCmd * EditOptionsCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 95 of file EditOptionsCmd.cc.
{
    return new EditOptionsCmd();
}
References EditOptionsCmd().
Do()
bool EditOptionsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file EditOptionsCmd.cc.
                   {
    ProDeOptionsDialog dialog(
        parentWindow(), *wxGetApp().options(), *wxGetApp().commandRegistry());
    if (dialog.ShowModal() == wxID_OK) {
        if (wxGetApp().options()->toolbarVisibility()) {
            wxGetApp().mainFrame()->createToolbar();
            wxGetApp().mainFrame()->createMenubar();
        }
    }
    return true;
}
References options, and GUICommand::parentWindow().
icon()
string EditOptionsCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 117 of file EditOptionsCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_OPTIONS;
}
References ProDeConstants::CMD_ICON_EDIT_OPTIONS.
id()
int EditOptionsCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 84 of file EditOptionsCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_OPTIONS;
}
References ProDeConstants::COMMAND_EDIT_OPTIONS.
isEnabled()
bool EditOptionsCmd::isEnabled () virtual
This command is always executable.
Returns
Always true.
Reimplemented from EditorCommand.
Definition at line 128 of file EditOptionsCmd.cc.
{
    return true;
}
shortName()
string EditOptionsCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 106 of file EditOptionsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_OPTIONS;
}
References ProDeConstants::CMD_SNAME_EDIT_OPTIONS.
The documentation for this class was generated from the following files:
EditOptionsCmd.hh
EditOptionsCmd.cc