OpenASIP: GlobalVsStackAA Class Reference
GlobalVsStackAA Class Reference
#include <GlobalVsStackAA.hh>
Public Member Functions
virtual bool isAddressTraceable (DataDependenceGraph &ddg, const ProgramOperation &pop)
virtual AliasingResult analyze (DataDependenceGraph &ddg, const ProgramOperation &pop1, const ProgramOperation &pop2, MoveNodeUse::BBRelation bbInfo)
GlobalVsStackAA (const TCEString &sp)
virtual ~GlobalVsStackAA ()
Public Member Functions inherited from MemoryAliasAnalyzer
virtual void initProcedure (TTAProgram::Procedure &)
virtual ~MemoryAliasAnalyzer ()
Private Attributes
TCEString sp_
Additional Inherited Members
Public Types inherited from MemoryAliasAnalyzer
enum AliasingResult { ALIAS_FALSE = 0 , ALIAS_TRUE = 1 , ALIAS_UNKNOWN = 2 , ALIAS_PARTIAL = 3 }
Protected Member Functions inherited from MemoryAliasAnalyzer
AliasingResult compareIndeces (int index1, int index2, const ProgramOperation &pop1, const ProgramOperation &pop2)
Static Protected Member Functions inherited from MemoryAliasAnalyzer
static const MoveNode * addressOperandMove (const ProgramOperation &po)
static TwoPartAddressOperandDetection findTwoPartAddressOperands (const ProgramOperation &po)
static const MoveNode * searchLoopIndexBasedIncrement (DataDependenceGraph &ddg, const MoveNode &mn, long &loopIncrement)
static const MoveNode * findIncrement (const MoveNode &mn, long &increment)
static const MoveNode * detectConstantScale (const MoveNode &mn, int &shiftAmount)
Detailed Description
Definition at line 39 of file GlobalVsStackAA.hh.
Constructor & Destructor Documentation
GlobalVsStackAA()
GlobalVsStackAA::GlobalVsStackAA (const TCEString & sp)
Definition at line 39 of file GlobalVsStackAA.cc.
                                                    : sp_(sp) {
}
~GlobalVsStackAA()
GlobalVsStackAA::~GlobalVsStackAA () virtual
Definition at line 37 of file GlobalVsStackAA.cc.
{}
Member Function Documentation
analyze()
MemoryAliasAnalyzer::AliasingResult GlobalVsStackAA::analyze (DataDependenceGraph & ddg, const ProgramOperation & pop1, const ProgramOperation & pop2, MoveNodeUse::BBRelation bbInfo) virtual
Implements MemoryAliasAnalyzer.
Definition at line 17 of file GlobalVsStackAA.cc.
{
    long tmp;
    long tmp2;
    long tmp3;
    long tmp4;
    if ((StackAliasAnalyzer::getStackOffset(ddg, pop2, tmp2, tmp4, sp_) &&
         ConstantAliasAnalyzer::getConstantAddress(ddg, pop1, tmp, tmp3)) ||
        (StackAliasAnalyzer::getStackOffset(ddg, pop1, tmp2, tmp4, sp_) &&
         ConstantAliasAnalyzer::getConstantAddress(ddg, pop2, tmp, tmp3))) {
        return ALIAS_FALSE;
    }
    return ALIAS_UNKNOWN;
}
References MemoryAliasAnalyzer::ALIAS_FALSE, MemoryAliasAnalyzer::ALIAS_UNKNOWN, ConstantAliasAnalyzer::getConstantAddress(), StackAliasAnalyzer::getStackOffset(), and sp_.
isAddressTraceable()
bool GlobalVsStackAA::isAddressTraceable (DataDependenceGraph & ddg, const ProgramOperation & pop) virtual
Checks whether the analyzer knows anything about the address.
ie. if it can return true or false to some query concerning this address.
Returns
true if analyzer can know something about the address.
Implements MemoryAliasAnalyzer.
Definition at line 7 of file GlobalVsStackAA.cc.
{
    long tmp;
    long tmp2;
    return ConstantAliasAnalyzer::getConstantAddress(ddg, po, tmp, tmp2) ||
        StackAliasAnalyzer::getStackOffset(ddg, po, tmp, tmp2, sp_);
}
References ConstantAliasAnalyzer::getConstantAddress(), StackAliasAnalyzer::getStackOffset(), and sp_.
Member Data Documentation
sp_
TCEString GlobalVsStackAA::sp_ private
Definition at line 50 of file GlobalVsStackAA.hh.
Referenced by analyze(), and isAddressTraceable().
The documentation for this class was generated from the following files:
GlobalVsStackAA.hh
GlobalVsStackAA.cc