OpenASIP: MachInfoCmdLineOptions Class Reference
MachInfoCmdLineOptions Class Reference
#include <MachInfoCmdLineOptions.hh>
Public Member Functions
MachInfoCmdLineOptions ()
virtual ~MachInfoCmdLineOptions ()
TCEString outputFileNameSuffix () const
TCEString outputFormat () const
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Definition at line 36 of file MachInfoCmdLineOptions.hh.
Constructor & Destructor Documentation
MachInfoCmdLineOptions()
MachInfoCmdLineOptions::MachInfoCmdLineOptions ()
Definition at line 42 of file MachInfoCmdLineOptions.cc.
                                               :
    CmdLineOptions("") {
    addOption(
        new StringCmdLineOptionParser(
            OUTPUTFN_PARAM_NAME,
            "The suffix of the filenames of the produced documentation files.",
            "s"));
    addOption(
        new StringCmdLineOptionParser(
            OUTPUT_FORMAT_PARAM_NAME,
            "The format of the produced documentation (only 'latex' supported "
            "for now).", "f"));
}
References CmdLineParser::addOption(), OUTPUT_FORMAT_PARAM_NAME, and OUTPUTFN_PARAM_NAME.
~MachInfoCmdLineOptions()
MachInfoCmdLineOptions::~MachInfoCmdLineOptions () virtual
Definition at line 59 of file MachInfoCmdLineOptions.cc.
{
}
Member Function Documentation
outputFileNameSuffix()
TCEString MachInfoCmdLineOptions::outputFileNameSuffix () const
Definition at line 63 of file MachInfoCmdLineOptions.cc.
{
    if (!findOption(OUTPUTFN_PARAM_NAME)->isDefined()) {
        if (numberOfArguments() == 1) return argument(1);
    }
    return findOption(OUTPUTFN_PARAM_NAME)->String();
}
References CmdLineParser::argument(), CmdLineParser::findOption(), CmdLineParser::numberOfArguments(), OUTPUTFN_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by main().
outputFormat()
TCEString MachInfoCmdLineOptions::outputFormat () const
Definition at line 71 of file MachInfoCmdLineOptions.cc.
{
    if (!findOption(OUTPUT_FORMAT_PARAM_NAME)->isDefined())
        return "latex";
    return findOption(OUTPUT_FORMAT_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), OUTPUT_FORMAT_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by main().
printHelp()
void MachInfoCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Reimplemented from CmdLineOptions.
Definition at line 89 of file MachInfoCmdLineOptions.cc.
{
    printVersion();
    cout << "Usage: machinfo [options] ADF" << endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
Referenced by GenerateProcessor::generateProcessor(), and main().
printVersion()
void MachInfoCmdLineOptions::printVersion () const virtual
Prints the version of the application.
Implements CmdLineOptions.
Definition at line 82 of file MachInfoCmdLineOptions.cc.
{
    std::cout << "machinfo - processor design documentation generator "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
The documentation for this class was generated from the following files:
MachInfoCmdLineOptions.hh
MachInfoCmdLineOptions.cc