OpenASIP: IUPortDialog Class Reference
IUPortDialog Class Reference
#include <IUPortDialog.hh>
Public Member Functions
IUPortDialog (wxWindow *parent, TTAMachine::Port *port)
virtual ~IUPortDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_OUTPUT_SOCKET , ID_HELP , ID_LABEL_NAME ,
ID_LABEL_OUTPUT_SOCKET , ID_LINE
}
Enumerated IDs for dialog controls.
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void updateSocket ()
void setTexts ()
Private Attributes
TTAMachine::Port * port_
Immediate unit port to edit with the dialog.
wxString name_
Name of the port.
wxChoice * outputSocketChoice_
Output socket choice control.
Detailed Description
Dialog for editing immediate unit ports.
Definition at line 45 of file IUPortDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerated IDs for dialog controls.
Enumerator
ID_NAME
ID_OUTPUT_SOCKET
ID_HELP
ID_LABEL_NAME
ID_LABEL_OUTPUT_SOCKET
ID_LINE
Definition at line 67 of file IUPortDialog.hh.
         {
    ID_NAME= 10000,
    ID_OUTPUT_SOCKET,
    ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_OUTPUT_SOCKET,
        ID_LINE
    };
Constructor & Destructor Documentation
IUPortDialog()
IUPortDialog::IUPortDialog (wxWindow * parent, TTAMachine::Port * port)
The Constructor.
Parameters
parent Parent window of the dialog.
port Immediate unit port to be modified with the dialog.
Definition at line 64 of file IUPortDialog.cc.
               :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    port_(port),
    name_(_T("")),
    outputSocketChoice_(NULL) {
    createContents(this, true, true);
    FindWindow(wxID_OK)->Disable();
    outputSocketChoice_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_OUTPUT_SOCKET));
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    // set texts for widgets
    setTexts();
    TransferDataToWindow();
}
~IUPortDialog()
IUPortDialog::~IUPortDialog () virtual
The Destructor.
Definition at line 90 of file IUPortDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * IUPortDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was initially generated with wxDesigner, code will be cleaned up later.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 284 of file IUPortDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(140,-1), 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_OUTPUT_SOCKET, wxT("Output Socket"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_OUTPUT_SOCKET, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item6 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item6, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item8 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_HELP, ID_LABEL_NAME, ID_LABEL_OUTPUT_SOCKET, ID_LINE, ID_NAME, and ID_OUTPUT_SOCKET.
onHelp()
void IUPortDialog::onHelp (wxCommandEvent & event) private
onName()
void IUPortDialog::onName (wxCommandEvent & event) private
Validates input in the controls, and updates the port.
Definition at line 259 of file IUPortDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void IUPortDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the port.
Definition at line 191 of file IUPortDialog.cc.
{
    if (!Validate()) {
    return;
    }
    if (!TransferDataFromWindow()) {
    return;
    }
    string trimmedName =
    WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (port_->name() != trimmedName) {
    Unit* iu = port_->parentUnit();
        for (int i = 0; i < iu->portCount(); i++) {
            string name = iu->port(i)->name();
            if (name == WxConversion::toString(name_)) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_port =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_PORT);
                format iu =
                    prodeTexts->text(ProDeTextGenerator::COMP_IMMEDIATE_UNIT);
                format port =
                    prodeTexts->text(ProDeTextGenerator::COMP_PORT);
                message % trimmedName % a_port.str() % iu.str() % port.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    port_->setName(trimmedName);
    port_->detachAllSockets();
    Machine::SocketNavigator navigator =
    port_->parentUnit()->machine()->socketNavigator();
    // set output socket
    string outputSocketName =
    WxConversion::toString(outputSocketChoice_->GetStringSelection());
    if (outputSocketName != WxConversion::toString(ProDeConstants::NONE)) {
    port_->attachSocket(*(navigator.item(outputSocketName)));
    }
    EndModal(wxID_OK);
}
References TTAMachine::Port::attachSocket(), ProDeTextGenerator::COMP_A_PORT, ProDeTextGenerator::COMP_IMMEDIATE_UNIT, ProDeTextGenerator::COMP_PORT, TTAMachine::Port::detachAllSockets(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Port::name(), name_, ProDeConstants::NONE, outputSocketChoice_, TTAMachine::Port::parentUnit(), TTAMachine::Unit::port(), port_, TTAMachine::Unit::portCount(), TTAMachine::Port::setName(), TTAMachine::Machine::socketNavigator(), Texts::TextGenerator::text(), WxConversion::toString(), and WxConversion::toWxString().
setTexts()
void IUPortDialog::setTexts () private
Sets texts for widgets.
Definition at line 98 of file IUPortDialog.cc.
                       {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_IU_PORT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_OUTPUT_SOCKET),
                          ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET);
}
References ID_HELP, ID_LABEL_NAME, ID_LABEL_OUTPUT_SOCKET, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_IU_PORT_DIALOG_TITLE, ProDeTextGenerator::TXT_LABEL_NAME, and ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET.
TransferDataToWindow()
bool IUPortDialog::TransferDataToWindow () private virtual
Transfers data from the Port object to the dialog widgets.
Returns
false, if an error occured in the transfer.
Definition at line 132 of file IUPortDialog.cc.
{
    name_ = WxConversion::toWxString(port_->name());
    updateSocket();
    return wxWindow::TransferDataToWindow();
}
References TTAMachine::Port::name(), name_, port_, WxConversion::toWxString(), and updateSocket().
updateSocket()
void IUPortDialog::updateSocket () private
Updates output socket choicer.
Definition at line 145 of file IUPortDialog.cc.
{
    outputSocketChoice_->Clear();
    outputSocketChoice_->Append(ProDeConstants::NONE);
    MachineTester tester(*(port_->parentUnit()->machine()));
    // Add ports to the choicer
    Machine::SocketNavigator navigator =
    port_->parentUnit()->machine()->socketNavigator();
    for (int i = 0; i < navigator.count(); i++) {
    Socket* socket = navigator.item(i);
    wxString socketName = WxConversion::toWxString(socket->name());
    // Add available output sockets.
    Socket* output = port_->outputSocket();
    if (output != NULL) {
        port_->detachSocket(*output);
    }
        bool legal = tester.canConnect(*socket, *port_);
    if (legal && socket->direction() == Socket::OUTPUT) {
        outputSocketChoice_->Append(socketName);
    }
    if (output != NULL) {
        port_->attachSocket(*output);
    }
    // ignore sockets with unknown direction
    }
    // set output socket choice
    if (port_->outputSocket() == NULL) {
    outputSocketChoice_->SetStringSelection(ProDeConstants::NONE);
    } else {
    wxString socketName =
        WxConversion::toWxString(port_->outputSocket()->name());
    outputSocketChoice_->SetStringSelection(socketName);
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Port::detachSocket(), TTAMachine::Socket::direction(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ProDeConstants::NONE, TTAMachine::Socket::OUTPUT, TTAMachine::Port::outputSocket(), outputSocketChoice_, TTAMachine::Port::parentUnit(), port_, TTAMachine::Machine::socketNavigator(), and WxConversion::toWxString().
Referenced by TransferDataToWindow().
Member Data Documentation
name_
wxString IUPortDialog::name_ private
Name of the port.
Definition at line 62 of file IUPortDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
outputSocketChoice_
wxChoice* IUPortDialog::outputSocketChoice_ private
Output socket choice control.
Definition at line 64 of file IUPortDialog.hh.
Referenced by onOK(), and updateSocket().
port_
TTAMachine::Port* IUPortDialog::port_ private
Immediate unit port to edit with the dialog.
Definition at line 60 of file IUPortDialog.hh.
Referenced by onOK(), TransferDataToWindow(), and updateSocket().
The documentation for this class was generated from the following files:
IUPortDialog.hh
IUPortDialog.cc