OpenASIP: TTAMachine::RegisterGuard Class Reference
TTAMachine::RegisterGuard Class Reference
#include <Guard.hh>
Public Member Functions
RegisterGuard (bool inverted, const RegisterFile &regFile, unsigned int registerIndex, Bus *parentBus)
RegisterGuard (const ObjectState *state, Bus &parentBus)
virtual ~RegisterGuard ()
bool isOpposite (const Guard &guard) const
bool isEqual (const Guard &guard) const
const RegisterFile * registerFile () const
int registerIndex () const
virtual void copyTo (Bus &parentBus) const
ObjectState * saveState () const
void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Guard
virtual ~Guard ()
virtual Bus * parentBus () const
virtual void setParentBus (Bus *parentBus)
virtual bool isInverted () const
virtual bool isMoreRestrictive (const Guard &guard) const
virtual bool isLessRestrictive (const Guard &guard) const
virtual bool isDisjoint (const Guard &guard) const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_REGISTER_GUARD = "registerguard"
ObjectState name for RegisterGuard.
static const std::string OSKEY_REGFILE = "regfile"
ObjectState attribute key for register file name.
static const std::string OSKEY_INDEX = "index"
ObjectState attribute key for register index.
Static Public Attributes inherited from TTAMachine::Guard
static const std::string OSNAME_GUARD = "guard"
ObjectState name for guard.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for inverted feature.
Private Attributes
const RegisterFile * regFile_
RegisterFile from which the condition term is taken.
int registerIndex_
Index of the register from which the condition term is taken.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Guard
Guard (bool inverted, Bus *parentBus)
Guard (const ObjectState *state, Bus &parentBus)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Guard where the condition term is taken from the value of a register (from a RegisterFile).
Definition at line 137 of file Guard.hh.
Constructor & Destructor Documentation
RegisterGuard() [1/2]
TTAMachine::RegisterGuard::RegisterGuard (bool inverted, const RegisterFile & regFile, unsigned int registerIndex, Bus * parentBus)
Constructor.
Parameters
inverted Indicates whether the condition term is inverted.
regFile RegisterFile from which the condition term is taken.
registerIndex Index of the register from which the condition term is taken.
parentBus Parent bus component of the guard.
Exceptions
IllegalRegistration If the given register file is not registered to the same machine as the parent bus of the guard.
ComponentAlreadyExists If the parent bus already has an equal guard.
OutOfRange If the given register file does not have a register by the given register index.
InvalidData If local + global guard latency would be zero.
Definition at line 393 of file Guard.cc.
    : Guard(inverted, parentBus),
      regFile_(&regFile),
      registerIndex_(registerIndex) {
    if (parentBus) {
        parentBus->ensureRegistration(regFile);
    }
    if ((unsigned)regFile.numberOfRegisters() <= registerIndex) {
        string procName = "RegisterGuard::RegisterGuard";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    if (parentBus) {
        // make sure global + local guard latency > 0
        Machine* mach = parentBus->machine();
        ControlUnit* gcu = mach->controlUnit();
        if (gcu != NULL && gcu->globalGuardLatency() == 0 &&
            regFile.guardLatency() == 0) {
            MOMTextGenerator textGen;
            boost::format text = textGen.text(
                MOMTextGenerator::TXT_INVALID_GUARD_LATENCY);
            throw InvalidData(__FILE__, __LINE__, __func__, text.str());
        }
        parentBus->addGuard(*this);
    }
}
References __func__, TTAMachine::Bus::addGuard(), TTAMachine::Machine::controlUnit(), TTAMachine::Component::ensureRegistration(), TTAMachine::ControlUnit::globalGuardLatency(), TTAMachine::RegisterFile::guardLatency(), TTAMachine::Component::machine(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Guard::parentBus(), registerIndex(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_INVALID_GUARD_LATENCY.
RegisterGuard() [2/2]
TTAMachine::RegisterGuard::RegisterGuard (const ObjectState * state, Bus & parentBus)
Constructor.
Creates a skeleton object without references to other machine parts. Loads its state from the given ObjectState instance. This constructor should be used by Bus::loadStateWithoutReferences only. Do not use this constructor.
Parameters
state The ObjectState instance.
parentBus Parent bus of the guard.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if the reference to the register cannot be resolved.
Definition at line 436 of file Guard.cc.
    : Guard(state, parentBus) {
    loadState(state);
    try {
        parentBus.addGuard(*this);
    } catch (const ComponentAlreadyExists&) {
        const string procName = "RegisterGuard::RegisterGuard";
        MOMTextGenerator textGen;
        format errorMsg = textGen.text(
            MOMTextGenerator::TXT_EQUAL_REGISTER_GUARDS);
        errorMsg % registerIndex() % registerFile()->name() %
            parentBus.name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    }
}
References TTAMachine::Bus::addGuard(), loadState(), TTAMachine::Component::name(), TTAMachine::Guard::parentBus(), registerFile(), registerIndex(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_EQUAL_REGISTER_GUARDS.
~RegisterGuard()
TTAMachine::RegisterGuard::~RegisterGuard () virtual
Destructor.
Definition at line 456 of file Guard.cc.
{
}
Member Function Documentation
copyTo()
virtual void TTAMachine::RegisterGuard::copyTo (Bus & parentBus) const inline virtual
Implements TTAMachine::Guard.
Definition at line 149 of file Guard.hh.
{
        new RegisterGuard(
            isInverted(), *regFile_, registerIndex_,
            &parentBus);
    }
References TTAMachine::Guard::isInverted(), TTAMachine::Guard::parentBus(), regFile_, and registerIndex_.
isEqual()
bool TTAMachine::RegisterGuard::isEqual (const Guard & guard) const virtual
Returns true if the guard is equal with the given guard.
Parameters
guard The other guard.
Returns
True if the guard is equal with the given guard.
Implements TTAMachine::Guard.
Definition at line 467 of file Guard.cc.
{
    const RegisterGuard* regGuard =
        dynamic_cast<const RegisterGuard*>(&guard);
    if (regGuard == NULL) {
        return false;
    } else {
        if (registerFile() == regGuard->registerFile() &&
            registerIndex() == regGuard->registerIndex() &&
            isInverted() == regGuard->isInverted()) {
            return true;
        } else {
            return false;
        }
    }
}
References TTAMachine::Guard::isInverted(), registerFile(), and registerIndex().
isOpposite()
bool TTAMachine::RegisterGuard::isOpposite (const Guard & guard) const virtual
Returns true if the guard is opposite with the given guard, ie. always if one is executed, another is not executed.
Parameters
guard The other guard.
Returns
True if the guard is opposite with the given guard.
Implements TTAMachine::Guard.
Definition at line 491 of file Guard.cc.
{
    const RegisterGuard* regGuard =
        dynamic_cast<const RegisterGuard*>(&guard);
    if (regGuard == NULL) {
        return false;
    } else {
        if (registerFile() == regGuard->registerFile() &&
            registerIndex() == regGuard->registerIndex() &&
            isInverted() != regGuard->isInverted()) {
            return true;
        } else {
            return false;
        }
    }
}
References TTAMachine::Guard::isInverted(), registerFile(), and registerIndex().
loadState()
void TTAMachine::RegisterGuard::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if the reference to the register file cannot be resolved.
Reimplemented from TTAMachine::Guard.
Definition at line 535 of file Guard.cc.
{
    string procName = "RegisterGuard::loadState";
    MOMTextGenerator textGenerator;
    if (state->name() != OSNAME_REGISTER_GUARD) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    if (!parentBus()->isRegistered()) {
        format text = textGenerator.text(MOMTextGenerator::
                                         TXT_GUARD_REF_LOAD_ERR);
        text % parentBus()->name();
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          text.str());
    }
    Guard::loadState(state);
    try {
        string regFileName = state->stringAttribute(OSKEY_REGFILE);
        int regIndex = state->intAttribute(OSKEY_INDEX);
        Machine* mach = parentBus()->machine();
        Machine::RegisterFileNavigator regNav =
            mach->registerFileNavigator();
        if (regNav.hasItem(regFileName)) {
            RegisterFile* regFile = regNav.item(regFileName);
            // check local + global guard latency > 0
            ControlUnit* gcu = mach->controlUnit();
            if (regFile->guardLatency() == 0 && gcu != NULL &&
                gcu->globalGuardLatency() == 0) {
                format text = textGenerator.text(
                    MOMTextGenerator::TXT_INVALID_GUARD_LATENCY);
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, __func__, text.str());
            }
            if (regFile->numberOfRegisters() > regIndex) {
                regFile_ = regFile;
                registerIndex_ = regIndex;
            } else {
                format text = textGenerator.text(
                    MOMTextGenerator::TXT_GUARD_REF_LOAD_ERR_REGISTER);
                text % parentBus()->name() % Conversion::toString(regIndex)
                    % regFileName %
                    Conversion::toString(regFile->numberOfRegisters());
                throw ObjectStateLoadingException(__FILE__, __LINE__,
                                                  procName, text.str());
            }
        } else {
            format text = textGenerator.text(MOMTextGenerator::
                                             TXT_GUARD_REF_LOAD_ERR_RF);
            text % parentBus()->name() % regFileName;
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              text.str());
        }
    } catch (Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
}
References __func__, TTAMachine::Machine::controlUnit(), Exception::errorMessage(), TTAMachine::ControlUnit::globalGuardLatency(), TTAMachine::RegisterFile::guardLatency(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), ObjectState::intAttribute(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Guard::loadState(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ObjectState::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), OSKEY_INDEX, OSKEY_REGFILE, OSNAME_REGISTER_GUARD, TTAMachine::Guard::parentBus(), regFile_, TTAMachine::Machine::registerFileNavigator(), registerIndex_, ObjectState::stringAttribute(), Texts::TextGenerator::text(), Conversion::toString(), MOMTextGenerator::TXT_GUARD_REF_LOAD_ERR_REGISTER, and MOMTextGenerator::TXT_INVALID_GUARD_LATENCY.
Referenced by RegisterGuard().
registerFile()
const RegisterFile * TTAMachine::RegisterGuard::registerFile () const
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), TDGen::analyzeRegisters(), MachineStateBuilder::buildMachineState(), UtilizationStats::calculateForInstruction(), SimpleIfConverter::canConvert(), ProgrammabilityValidator::checkBooleanRegister(), BEMValidator::checkGuardField(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), DataDependenceGraphBuilder::constructIndividualFromInlineAsmBB(), DefaultDecoderGenerator::containsSimilarGuard(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createGuard(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), ProgramDependenceGraph::createJump(), TTAMachine::RegisterFile::deleteGuards(), DataDependenceGraph::destRenamed(), CopyingDelaySlotFiller::fillDelaySlots(), findBooleanGuard(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), RegisterRenamer::findGuardRegisters(), RegisterQuantityCheck::findGuardRegisters(), ProgrammabilityValidator::findRegisterGuard(), RegisterCopyAdder::findTempRegisters(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), TTAProgram::Move::guardLatency(), CompiledSimCodeGenerator::guardPipelineTopSymbol(), DefaultDecoderGenerator::guardPortName(), DataDependenceGraph::guardRenamed(), MachineConnectivityCheck::hasBothGuards(), MachineConnectivityCheck::hasConditionalMoves(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), isEqual(), isOpposite(), TTAMachine::RegisterFile::isUsedAsGuard(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), ListCompareFunction(), MachineInfo::longestGuardLatency(), RFGuardDialog::onOK(), DataDependenceGraphBuilder::processGuard(), MachineResourceManager::registerFileIndexReference(), RegisterGuard(), RegisterRenamer::renameLiveRange(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), MachineResourceManager::rFPortOrFUIndexReference(), DataDependenceGraph::sanityCheck(), SequentialScheduler::scheduleMove(), BFRenameLiveRange::setGuard(), MachineInfo::supportsBoolRegisterGuardedJumps(), PostpassOperandSharer::tryRemoveOperandWrite(), and BusDialog::updateGuardLists().
registerIndex()
int TTAMachine::RegisterGuard::registerIndex () const
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), TDGen::analyzeRegisters(), MachineStateBuilder::buildMachineState(), UtilizationStats::calculateForInstruction(), SimpleIfConverter::canConvert(), ProgrammabilityValidator::checkBooleanRegister(), BEMValidator::checkGuardField(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), DataDependenceGraphBuilder::constructIndividualFromInlineAsmBB(), DefaultDecoderGenerator::containsSimilarGuard(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createGuard(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), ProgramDependenceGraph::createJump(), TTAMachine::RegisterFile::deleteGuards(), DataDependenceGraph::destRenamed(), CopyingDelaySlotFiller::fillDelaySlots(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), RegisterRenamer::findGuardRegisters(), RegisterQuantityCheck::findGuardRegisters(), ProgrammabilityValidator::findRegisterGuard(), RegisterCopyAdder::findTempRegisters(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), CompiledSimCodeGenerator::guardPipelineTopSymbol(), DefaultDecoderGenerator::guardPortName(), DataDependenceGraph::guardRenamed(), MachineConnectivityCheck::hasBothGuards(), MachineConnectivityCheck::hasConditionalMoves(), isEqual(), isOpposite(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), ListCompareFunction(), DataDependenceGraphBuilder::processGuard(), MachineResourceManager::registerFileIndexReference(), RegisterGuard(), RegisterGuard(), RegisterRenamer::renameLiveRange(), MachineResourceManager::rFPortOrFUIndexReference(), BFRenameLiveRange::setGuard(), PostpassOperandSharer::tryRemoveOperandWrite(), and BusDialog::updateGuardLists().
saveState()
ObjectState * TTAMachine::RegisterGuard::saveState () const virtual
Saves the contents to an ObjectState object.
Returns
The created ObjectState object..
Reimplemented from TTAMachine::Guard.
Definition at line 514 of file Guard.cc.
{
    ObjectState* guardState = Guard::saveState();
    guardState->setName(OSNAME_REGISTER_GUARD);
    guardState->setAttribute(OSKEY_REGFILE, regFile_->name());
    guardState->setAttribute(OSKEY_INDEX, registerIndex_);
    return guardState;
}
References TTAMachine::Component::name(), OSKEY_INDEX, OSKEY_REGFILE, OSNAME_REGISTER_GUARD, regFile_, registerIndex_, TTAMachine::Guard::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Member Data Documentation
OSKEY_INDEX
const string TTAMachine::RegisterGuard::OSKEY_INDEX = "index" static
ObjectState attribute key for register index.
Definition at line 163 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadState(), and saveState().
OSKEY_REGFILE
const string TTAMachine::RegisterGuard::OSKEY_REGFILE = "regfile" static
ObjectState attribute key for register file name.
Definition at line 161 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadState(), and saveState().
OSNAME_REGISTER_GUARD
const string TTAMachine::RegisterGuard::OSNAME_REGISTER_GUARD = "registerguard" static
ObjectState name for RegisterGuard.
Definition at line 159 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Bus::loadState(), loadState(), and saveState().
regFile_
const RegisterFile* TTAMachine::RegisterGuard::regFile_ private
RegisterFile from which the condition term is taken.
Definition at line 167 of file Guard.hh.
Referenced by copyTo(), loadState(), and saveState().
registerIndex_
int TTAMachine::RegisterGuard::registerIndex_ private
Index of the register from which the condition term is taken.
Definition at line 169 of file Guard.hh.
Referenced by copyTo(), loadState(), and saveState().
The documentation for this class was generated from the following files:
Guard.hh
Guard.cc