OpenASIP: TTAMachine::OperationTriggeredOperand Class Reference
TTAMachine::OperationTriggeredOperand Class Reference
#include <OperationTriggeredOperand.hh>
Public Member Functions
OperationTriggeredOperand (const std::string &name, OperationTriggeredFormat &parent)
OperationTriggeredOperand (const ObjectState *state, OperationTriggeredFormat &parent)
virtual ~OperationTriggeredOperand ()
const std::string & name () const
virtual void setName (const std::string &name)
std::string type () const
void setType (const std::string &type)
std::string direction () const
void setDirection (const std::string &direction)
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_OPERAND = "operand"
static const std::string OSKEY_TYPE = "type"
static const std::string OSKEY_DIRECTION = "direction"
static const std::string OSKEY_NAME = "name"
Private Attributes
std::string name_
std::string type_
std::string direction_
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Definition at line 44 of file OperationTriggeredOperand.hh.
Constructor & Destructor Documentation
OperationTriggeredOperand() [1/2]
TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand (const std::string & name, OperationTriggeredFormat & parent)
The constructor.
Registers the operation code encoding to the parent binary encoding automatically.
Parameters
parent The parent OperationTriggeredFormat.
Definition at line 54 of file OperationTriggeredOperand.cc.
    : SubComponent(), name_(name), type_(""), direction_("") {
    name_ = StringTools::stringToLower(name);
    parent.addOperand(*this);
}
References TTAMachine::OperationTriggeredFormat::addOperand(), name(), name_, and StringTools::stringToLower().
OperationTriggeredOperand() [2/2]
TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand (const ObjectState * state, OperationTriggeredFormat & parent)
The constructor
Loads the state of the operation code encoding from the given ObjectState tree
Parameters
state The ObjectState tree
parent The parent binary encoding map
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 73 of file OperationTriggeredOperand.cc.
    : SubComponent(), name_(""), type_(""), direction_("") {
    const std::string procName =
        "OperationTriggeredOperand::OperationTriggeredOperand";
    // set name
    try {
        setName(state->stringAttribute(OSKEY_NAME));
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    parent.addOperand(*this);
    loadState(state);
}
References TTAMachine::OperationTriggeredFormat::addOperand(), Exception::errorMessage(), loadState(), OSKEY_NAME, setName(), and ObjectState::stringAttribute().
~OperationTriggeredOperand()
TTAMachine::OperationTriggeredOperand::~OperationTriggeredOperand () virtual
Destructor.
Definition at line 92 of file OperationTriggeredOperand.cc.
{
    // TODO
}
Member Function Documentation
direction()
std::string TTAMachine::OperationTriggeredOperand::direction () const
Definition at line 132 of file OperationTriggeredOperand.cc.
{
    return direction_;
}
References direction_.
Referenced by setDirection().
loadState()
void TTAMachine::OperationTriggeredOperand::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState object from which (and the children of which) the state is loaded.
Implements Serializable.
Definition at line 142 of file OperationTriggeredOperand.cc.
{
    ObjectState* newState = new ObjectState(*state);
    try {
        type_ = state->stringAttribute(OSKEY_TYPE);
        direction_ = state->stringAttribute(OSKEY_DIRECTION);
    } catch (const Exception& exception) {
        const std::string procName = "OperationTriggeredOperand::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    delete newState;
}
References direction_, Exception::errorMessage(), OSKEY_DIRECTION, OSKEY_TYPE, ObjectState::stringAttribute(), and type_.
Referenced by OperationTriggeredOperand().
name()
const std::string & TTAMachine::OperationTriggeredOperand::name () const
Returns the name of the operation.
Returns
The name of the operation.
Definition at line 102 of file OperationTriggeredOperand.cc.
{
    return name_;
}
References name_.
Referenced by OperationTriggeredOperand(), and setName().
saveState()
ObjectState * TTAMachine::OperationTriggeredOperand::saveState () const virtual
Saves the state of the operation code encoding to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 164 of file OperationTriggeredOperand.cc.
{
    ObjectState* state = new ObjectState(OSNAME_OPERAND);
    state->setAttribute(OSKEY_NAME, name_);
    state->setAttribute(OSKEY_TYPE, type_);
    state->setAttribute(OSKEY_DIRECTION, direction_);
    return state;
}
References direction_, name_, OSKEY_DIRECTION, OSKEY_NAME, OSKEY_TYPE, OSNAME_OPERAND, ObjectState::setAttribute(), and type_.
setDirection()
void TTAMachine::OperationTriggeredOperand::setDirection (const std::string & direction)
Definition at line 137 of file OperationTriggeredOperand.cc.
{
    type_ = direction;
}
References direction(), and type_.
setName()
void TTAMachine::OperationTriggeredOperand::setName (const std::string & name) virtual
Sets the name of the operand.
Parameters
name The new name.
Definition at line 112 of file OperationTriggeredOperand.cc.
{
    std::string lowerName = StringTools::stringToLower(name);
    if (lowerName == this->name()) {
        return;
    }
    name_ = lowerName;
}
References name(), name_, and StringTools::stringToLower().
Referenced by OperationTriggeredOperand().
setType()
void TTAMachine::OperationTriggeredOperand::setType (const std::string & type)
Definition at line 127 of file OperationTriggeredOperand.cc.
{
    type_ = type;
}
References type(), and type_.
type()
std::string TTAMachine::OperationTriggeredOperand::type () const
Definition at line 122 of file OperationTriggeredOperand.cc.
{
    return type_;
}
References type_.
Referenced by setType().
Member Data Documentation
direction_
std::string TTAMachine::OperationTriggeredOperand::direction_ private
Definition at line 77 of file OperationTriggeredOperand.hh.
Referenced by direction(), loadState(), and saveState().
name_
std::string TTAMachine::OperationTriggeredOperand::name_ private
Definition at line 75 of file OperationTriggeredOperand.hh.
Referenced by name(), OperationTriggeredOperand(), saveState(), and setName().
OSKEY_DIRECTION
const std::string TTAMachine::OperationTriggeredOperand::OSKEY_DIRECTION = "direction" static
Definition at line 70 of file OperationTriggeredOperand.hh.
Referenced by loadState(), and saveState().
OSKEY_NAME
const std::string TTAMachine::OperationTriggeredOperand::OSKEY_NAME = "name" static
Definition at line 71 of file OperationTriggeredOperand.hh.
Referenced by OperationTriggeredOperand(), and saveState().
OSKEY_TYPE
const std::string TTAMachine::OperationTriggeredOperand::OSKEY_TYPE = "type" static
Definition at line 69 of file OperationTriggeredOperand.hh.
Referenced by loadState(), and saveState().
OSNAME_OPERAND
const std::string TTAMachine::OperationTriggeredOperand::OSNAME_OPERAND = "operand" static
Definition at line 68 of file OperationTriggeredOperand.hh.
Referenced by TTAMachine::OperationTriggeredFormat::loadState(), and saveState().
type_
std::string TTAMachine::OperationTriggeredOperand::type_ private
Definition at line 76 of file OperationTriggeredOperand.hh.
Referenced by loadState(), saveState(), setDirection(), setType(), and type().
The documentation for this class was generated from the following files:
OperationTriggeredOperand.hh
OperationTriggeredOperand.cc