OpenASIP: CompileError Class Reference
CompileError Class Reference
#include <Exception.hh>
Public Member Functions
CompileError (std::string filename, int linenum, std::string procname=unknownProcMsg_, std::string errorMessage="")
virtual ~CompileError ()
void setCodeFileLineNumber (int lineNum)
int codeFileLineNumber ()
Public Member Functions inherited from Exception
Exception (std::string filename, int linenum, std::string procname=unknownProcMsg_, std::string errorMessage="")
virtual ~Exception ()
std::string fileName () const
int lineNum () const
std::string procedureName () const
std::string errorMessage () const
std::string errorMessageStack (bool messagesOnly=false) const
void setCause (const Exception &cause)
bool hasCause () const
const Exception & cause () const
Private Attributes
int codeLineNumber_
Additional Inherited Members
Static Public Member Functions inherited from Exception
static std::string lastExceptionInfo ()
Returns information of the last thrown exception.
Static Public Attributes inherited from Exception
static const std::string unknownProcMsg_ = "(unknown)"
Used when no procedure name is given.
Detailed Description
Exception which is thrown when there is error in compilation.
Definition at line 1019 of file Exception.hh.
Constructor & Destructor Documentation
CompileError()
CompileError::CompileError (std::string filename, int linenum, std::string procname = unknownProcMsg_, std::string errorMessage = "")
Constructor.
Parameters
filename Name of the file in which the exception is created.
linenum Number of the line in which the exception is created.
procname Name of the function in which the exception is created.
errorMessage Error message.
Definition at line 1458 of file Exception.cc.
                            :
    Exception(filename, linenum, procname, errorMessage) {
}
~CompileError()
CompileError::~CompileError () virtual
Destructor.
Definition at line 1470 of file Exception.cc.
{
}
Member Function Documentation
codeFileLineNumber()
int CompileError::codeFileLineNumber ()
Returns line number where error happened in source code file that is compiled.
Returns
Line number where error happened in source code file that is compiled.
Definition at line 1489 of file Exception.cc.
{
    return codeLineNumber_;
}
References codeLineNumber_.
Referenced by Assembler::compile().
setCodeFileLineNumber()
void CompileError::setCodeFileLineNumber (int lineNum)
Set's line number where error happened in source code that is compiled.
Parameters
lineNum Line number where error happened in code that is compiled.
Definition at line 1479 of file Exception.cc.
{
    codeLineNumber_ = lineNum;
}
References codeLineNumber_, and Exception::lineNum().
Referenced by CodeSectionCreator::addMove(), DataSectionCreator::finalize(), DataSectionCreator::resolveDataAreaSizesAndLabelAddresses(), LabelManager::resolveExpressionValue(), and DataSectionCreator::writeDataLineToTPEF().
Member Data Documentation
codeLineNumber_
int CompileError::codeLineNumber_ private
Definition at line 1033 of file Exception.hh.
Referenced by codeFileLineNumber(), and setCodeFileLineNumber().
The documentation for this class was generated from the following files:
Exception.hh
Exception.cc