OpenASIP: ImplementMachineCmd Class Reference
ImplementMachineCmd Class Reference
#include <ImplementMachineCmd.hh>
Public Member Functions
ImplementMachineCmd ()
virtual ~ImplementMachineCmd ()
virtual bool Do ()
virtual int id () const
virtual ImplementMachineCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening processor implementation window.
Definition at line 43 of file ImplementMachineCmd.hh.
Constructor & Destructor Documentation
ImplementMachineCmd()
ImplementMachineCmd::ImplementMachineCmd ()
The Constructor.
Definition at line 47 of file ImplementMachineCmd.cc.
                                        :
    EditorCommand(ProDeConstants::CMD_NAME_IMPLEMENTATION) {
}
Referenced by create().
~ImplementMachineCmd()
ImplementMachineCmd::~ImplementMachineCmd () virtual
The Destructor.
Definition at line 56 of file ImplementMachineCmd.cc.
{}
Member Function Documentation
create()
ImplementMachineCmd * ImplementMachineCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 92 of file ImplementMachineCmd.cc.
{
    return new ImplementMachineCmd();
}
References ImplementMachineCmd().
Do()
bool ImplementMachineCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file ImplementMachineCmd.cc.
{
    TTAMachine::Machine* machine = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel()->getMachine();
    IDF::MachineImplementation impl;
    ProcessorImplementationWindow dialog(parentWindow(), *machine, impl);
    dialog.ShowModal();
    return true;
}
References machine, GUICommand::parentWindow(), and EditorCommand::view().
icon()
string ImplementMachineCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 102 of file ImplementMachineCmd.cc.
{
    return ProDeConstants::CMD_ICON_IMPLEMENTATION;
}
References ProDeConstants::CMD_ICON_IMPLEMENTATION.
id()
int ImplementMachineCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 83 of file ImplementMachineCmd.cc.
{
    return ProDeConstants::COMMAND_IMPLEMENTATION;
}
References ProDeConstants::COMMAND_IMPLEMENTATION.
isEnabled()
bool ImplementMachineCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 124 of file ImplementMachineCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string ImplementMachineCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 111 of file ImplementMachineCmd.cc.
{
    return ProDeConstants::CMD_SNAME_IMPLEMENTATION;
}
References ProDeConstants::CMD_SNAME_IMPLEMENTATION.
The documentation for this class was generated from the following files:
ImplementMachineCmd.hh
ImplementMachineCmd.cc