OpenASIP: CostDBEntryStatsFU Class Reference
CostDBEntryStatsFU Class Reference
#include <CostDBEntryStatsFU.hh>
Public Member Functions
CostDBEntryStatsFU (double areaData, double delayData)
virtual ~CostDBEntryStatsFU ()
CostDBEntryStatsFU (const CostDBEntryStatsFU &stats1, const CostDBEntryStatsFU &stats2, double coefficient)
virtual double energyActive () const
virtual double energyOperation (const std::string &name) const
virtual bool hasEnergyOperation (const std::string &name) const
virtual void setEnergyActive (double energy)
virtual void setEnergyOperation (const std::string &name, double energy)
Public Member Functions inherited from CostDBEntryStats
CostDBEntryStats (double areaData, double internalDelayData)
virtual ~CostDBEntryStats ()
CostDBEntryStats (const CostDBEntryStats &stats1, const CostDBEntryStats &stats2, double coefficient)
virtual CostDBEntryStats * copy () const
virtual double area () const
virtual double delay () const
virtual double delayPort (const std::string &port) const
virtual void setDelay (const std::string &port, double delay)
virtual double energyIdle () const
virtual double energyRead () const
virtual double energyWrite () const
virtual double energyReadWrite (int reads, int writes) const
virtual void setEnergyIdle (double energy)
virtual void setEnergyRead (double energy)
virtual void setEnergyWrite (double energy)
virtual void setEnergyReadWrite (int reads, int writes, double energy)
Protected Member Functions
virtual CostDBEntryStats * createStats () const
Protected Member Functions inherited from CostDBEntryStats
virtual bool hasEnergy (const std::string &key) const
virtual double findEnergy (const std::string &key) const
virtual void addEnergy (const std::string &name, double energy)
virtual bool hasDelay (const std::string &key) const
virtual double findDelay (const std::string &key) const
virtual void addDelay (const std::string &name, double delay)
Private Member Functions
CostDBEntryStatsFU (const CostDBEntryStatsFU &)
Copying not allowed.
CostDBEntryStatsFU & operator= (const CostDBEntryStatsFU &)
Assignment not allowed.
Additional Inherited Members
Static Protected Attributes inherited from CostDBEntryStats
static const std::string ENERGY_ACTIVE = "(active)"
String for active energy.
static const std::string ENERGY_IDLE = "(idle)"
String for idle energy.
static const std::string ENERGY_READ = "(read)"
String for read energy.
static const std::string ENERGY_WRITE = "(write)"
String for write energy.
static const std::string ENERGY_READ_WRITE = "(rd,wr)"
String for reads and writes energy.
Detailed Description
Stores area, delay and energy statistics of function units.
Definition at line 44 of file CostDBEntryStatsFU.hh.
Constructor & Destructor Documentation
CostDBEntryStatsFU() [1/3]
CostDBEntryStatsFU::CostDBEntryStatsFU (double areaData, double delayData)
Constructor.
Parameters
areaData area.
delayData delay.
Definition at line 48 of file CostDBEntryStatsFU.cc.
                                                                        :
    CostDBEntryStats(areaData, delayData) {
}
~CostDBEntryStatsFU()
CostDBEntryStatsFU::~CostDBEntryStatsFU () virtual
Destructor.
Definition at line 75 of file CostDBEntryStatsFU.cc.
{
}
CostDBEntryStatsFU() [2/3]
CostDBEntryStatsFU::CostDBEntryStatsFU (const CostDBEntryStatsFU & stats1, const CostDBEntryStatsFU & stats2, double coefficient)
Constructor.
Combines two statistics into one using coefficient as a weighting factor on interpolating the statistics. For example, if weighting factor is 0.4, the first area 100 and the second 200, area of new statistics will be 140. delay and energy will be handled similarly.
Parameters
stats1 First statistics.
stats2 Second statistics.
coefficient Weighting factor.
Definition at line 64 of file CostDBEntryStatsFU.cc.
                       :
    CostDBEntryStats(stats1, stats2, coefficient) {
}
CostDBEntryStatsFU() [3/3]
CostDBEntryStatsFU::CostDBEntryStatsFU (const CostDBEntryStatsFU &) private
Copying not allowed.
Member Function Documentation
createStats()
CostDBEntryStats * CostDBEntryStatsFU::createStats () const protected virtual
Create correct type of statistics.
Returns
Correct type of statistics.
Reimplemented from CostDBEntryStats.
Definition at line 84 of file CostDBEntryStatsFU.cc.
{
    return new CostDBEntryStatsFU(area(), delay());
}
References CostDBEntryStats::area(), and CostDBEntryStats::delay().
energyActive()
double CostDBEntryStatsFU::energyActive () const virtual
Returns the energy of an entry in an active cycle.
The function will fail since function units do not have unambiguous energy for the whole unit but separately for each operation.
Returns
The energy of an entry in an active cycle.
Exceptions
WrongSubclass An illegal function was called for this instance.
KeyNotFound Never thrown by this function.
Reimplemented from CostDBEntryStats.
Definition at line 100 of file CostDBEntryStatsFU.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
            "CostDBEntryStatsFU::energyActive");
    return 0.0; // stupid return statement to make compiler quiet
}
energyOperation()
double CostDBEntryStatsFU::energyOperation (const std::string & name) const virtual
Returns the energy of an entry when given operation is executed.
Parameters
name name of the operation.
Returns
The energy of an entry when given operation is executed.
Exceptions
WrongSubclass Never thrown by this function.
KeyNotFound No energy matching the string found.
Reimplemented from CostDBEntryStats.
Definition at line 115 of file CostDBEntryStatsFU.cc.
{
    return findEnergy(name);
}
References CostDBEntryStats::findEnergy().
hasEnergyOperation()
bool CostDBEntryStatsFU::hasEnergyOperation (const std::string & name) const virtual
Checks whether the energy exists for the given operation.
Parameters
name name of the operation.
Returns
True if the energy exists for the given operation.
Exceptions
WrongSubclass Never thrown by this function.
Reimplemented from CostDBEntryStats.
Definition at line 127 of file CostDBEntryStatsFU.cc.
{
    return hasEnergy(name);
}
References CostDBEntryStats::hasEnergy().
operator=()
CostDBEntryStatsFU & CostDBEntryStatsFU::operator= (const CostDBEntryStatsFU &) private
Assignment not allowed.
setEnergyActive()
void CostDBEntryStatsFU::setEnergyActive (double energy) virtual
Set the energy of an entry in an active cycle.
The function will fail since function units do not have unambiguous energy for the whole unit but separately for each operation.
Parameters
energy The energy of an entry in an active cycle.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented from CostDBEntryStats.
Definition at line 142 of file CostDBEntryStatsFU.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
            "CostDBEntryStatsFU::setEnergyActive");
}
setEnergyOperation()
void CostDBEntryStatsFU::setEnergyOperation (const std::string & name, double energy) virtual
Set the energy of an entry when given operation is executed.
Parameters
name name of the operation.
energy The energy of an entry when given operation is executed.
Exceptions
WrongSubclass Never thrown by this function.
Reimplemented from CostDBEntryStats.
Definition at line 155 of file CostDBEntryStatsFU.cc.
{
    addEnergy(name, energy);
}
References CostDBEntryStats::addEnergy().
Referenced by CostDatabase::buildFunctionUnits().
The documentation for this class was generated from the following files:
CostDBEntryStatsFU.hh
CostDBEntryStatsFU.cc