OpenASIP: TransportPipeline Class Reference
TransportPipeline Class Reference
#include <TransportPipeline.hh>
Public Member Functions
TransportPipeline (GCUState &parent)
virtual ~TransportPipeline ()
virtual int latency () const
virtual void startOperation (Operation &op)
virtual void advanceClock ()
virtual OperationExecutor * copy ()
virtual void setContext (OperationContext &context)
bool hasPendingOperations () const
Public Member Functions inherited from OperationExecutor
OperationExecutor ()
OperationExecutor (FUState &parent)
virtual ~OperationExecutor ()
FUState & parent () const
void setParent (FUState &parent)
void addBinding (int io, PortState &port)
PortState & binding (int io) const
bool hasPendingOperations () const
virtual void reset ()
Private Member Functions
TransportPipeline & operator= (const TransportPipeline &)
Assignment not allowed.
Private Attributes
Operation * operation_
Operation to be triggered next.
OperationContext * context_
Operation context used to fetch the values for PC and RA.
OperationContext tempContext_
Operation context seen by the operation.
InstructionAddress PC_
Storage for PC value in the context.
InstructionAddress IBS_
Storage for IRF block start in the context.
SimValue RA_
Storage for RA value in the context.
int branchDelayCycles_
Branch delay cycles.
GCUState & parent_
The owner GCUState.
Additional Inherited Members
Protected Attributes inherited from OperationExecutor
std::vector< PortState * > bindings_
PortStates that are bound to a certain input or output operand.
bool hasPendingOperations_
This is set to true if the OperationExecutor is not in 'idle' mode.
Detailed Description
Models the transport pipeline of global control unit.
Definition at line 49 of file TransportPipeline.hh.
Constructor & Destructor Documentation
TransportPipeline()
TransportPipeline::TransportPipeline (GCUState & parent) explicit
Constructor.
Parameters
parent Parent of the pipeline.
Definition at line 57 of file TransportPipeline.cc.
                                                     :
    OperationExecutor(parent), operation_(NULL),
    context_(&parent.context()),
    tempContext_(NULL, PC_, RA_, parent.context().branchDelayCycles()),
    parent_(parent) {
    // delete the own state registry to avoid mem leaks
    delete &tempContext_.stateRegistry();
    // share the state registry with the actual context
    tempContext_.setStateRegistry(parent.context().stateRegistry());
}
References FUState::context(), OperationExecutor::parent(), OperationContext::setStateRegistry(), OperationContext::stateRegistry(), and tempContext_.
~TransportPipeline()
TransportPipeline::~TransportPipeline () virtual
Destructor.
Definition at line 71 of file TransportPipeline.cc.
{
    tempContext_.unsetStateRegistry();
}
References tempContext_, and OperationContext::unsetStateRegistry().
Member Function Documentation
advanceClock()
void TransportPipeline::advanceClock () virtual
Nothing is done when clock cycle changes.
Implements OperationExecutor.
Definition at line 130 of file TransportPipeline.cc.
{
}
copy()
OperationExecutor * TransportPipeline::copy () virtual
Copies OperationExecutor.
Returns
The copied OperationExecutor.
Implements OperationExecutor.
Definition at line 139 of file TransportPipeline.cc.
{
    return new TransportPipeline(*this);
}
hasPendingOperations()
bool TransportPipeline::hasPendingOperations () const inline
Definition at line 59 of file TransportPipeline.hh.
{
        return true;
    }
latency()
int TransportPipeline::latency () const virtual
Returns the latency of the pipeline.
Returns
The latency of the pipeline.
Definition at line 81 of file TransportPipeline.cc.
{
    return 0;
}
operator=()
TransportPipeline & TransportPipeline::operator= (const TransportPipeline &) private
Assignment not allowed.
setContext()
void TransportPipeline::setContext (OperationContext & context) virtual
Sets the OperationContext of the pipeline.
Parameters
context The OperationContext.
Implements OperationExecutor.
Definition at line 149 of file TransportPipeline.cc.
{
    context_ = &context;
}
References context_.
startOperation()
void TransportPipeline::startOperation (Operation & op) virtual
Start the execution of the operation.
First inputs and outputs of the operation are collected in a vector. Then a new operation context is created. After triggering the operation the registers which values are changed are updated in parent GCU state.
Parameters
op Operation to be triggered.
Todo:
This can be optimized a lot.
Implements OperationExecutor.
Definition at line 96 of file TransportPipeline.cc.
{
    operation_ = &op;
    int operands = op.numberOfInputs() + op.numberOfOutputs();
    SimValue* io[32];
    assert(operands < 32);
    for (int i = 0; i < operands; ++i)
        io[i] = const_cast<SimValue*>(&(binding(i + 1).value()));
    // use a temporary context here as the original context points to the
    // internal program counter variables of the simulator engine,
    // which we do not want to modify in the middle of simulating
    // a cycle
    tempContext_.programCounter() = context_->programCounter();
    tempContext_.returnAddress() = context_->returnAddress();
    tempContext_.setSaveReturnAddress(false);
    tempContext_.setUpdateProgramCounter(false);
    operation_->simulateTrigger(io, tempContext_);
    // If the operation is a jump or a call operation, update the program
    // counter after delay slot cycles. If a loop buffer setup op is called,
    // do not update the program counter this way.
    if (tempContext_.updateProgramCounter() && (op.isCall() || op.isBranch())) {
        parent_.setProgramCounter(tempContext_.programCounter());
    }
    if (tempContext_.saveReturnAddress()) {
        parent_.setReturnAddress();
    }
}
References assert, OperationExecutor::binding(), context_, Operation::isBranch(), Operation::isCall(), Operation::numberOfInputs(), Operation::numberOfOutputs(), operation_, parent_, OperationContext::programCounter(), OperationContext::returnAddress(), OperationContext::saveReturnAddress(), GCUState::setProgramCounter(), GCUState::setReturnAddress(), OperationContext::setSaveReturnAddress(), OperationContext::setUpdateProgramCounter(), Operation::simulateTrigger(), tempContext_, and OperationContext::updateProgramCounter().
Member Data Documentation
branchDelayCycles_
int TransportPipeline::branchDelayCycles_ private
Branch delay cycles.
Definition at line 80 of file TransportPipeline.hh.
context_
OperationContext* TransportPipeline::context_ private
Operation context used to fetch the values for PC and RA.
Definition at line 70 of file TransportPipeline.hh.
Referenced by setContext(), and startOperation().
IBS_
InstructionAddress TransportPipeline::IBS_ private
Storage for IRF block start in the context.
Definition at line 76 of file TransportPipeline.hh.
operation_
Operation* TransportPipeline::operation_ private
Operation to be triggered next.
Definition at line 68 of file TransportPipeline.hh.
Referenced by startOperation().
parent_
GCUState& TransportPipeline::parent_ private
The owner GCUState.
Definition at line 82 of file TransportPipeline.hh.
Referenced by startOperation().
PC_
InstructionAddress TransportPipeline::PC_ private
Storage for PC value in the context.
Definition at line 74 of file TransportPipeline.hh.
RA_
SimValue TransportPipeline::RA_ private
Storage for RA value in the context.
Definition at line 78 of file TransportPipeline.hh.
tempContext_
OperationContext TransportPipeline::tempContext_ private
Operation context seen by the operation.
Definition at line 72 of file TransportPipeline.hh.
Referenced by startOperation(), TransportPipeline(), and ~TransportPipeline().
The documentation for this class was generated from the following files:
TransportPipeline.hh
TransportPipeline.cc