OpenASIP: ProximToolbox Class Reference
ProximToolbox Class Reference
#include <ProximToolbox.hh>
Static Public Member Functions
static const TTAMachine::Machine & machine ()
static const TTAProgram::Program & program ()
static ProximMainFrame * mainFrame ()
static ProximMachineStateWindow * machineStateWindow ()
static ProximDisassemblyWindow * disassemblyWindow ()
static void addFramedWindow (wxWindow *window, const wxString &title, bool stayOnTop=false, const wxSize &minSize=wxSize(100, 100))
static SimulatorInterpreter * interpreter ()
static TracedSimulatorFrontend * frontend ()
static ProximLineReader & lineReader ()
static bool testExpression (wxWindow *parent, const std::string &expression)
static bool testCondition (wxWindow *parent, const std::string &condition)
Protected Member Functions
ProximToolbox ()
Instantiation not allowed.
Detailed Description
Set of helper functions to access Proxim windows and simulation.
Definition at line 56 of file ProximToolbox.hh.
Constructor & Destructor Documentation
ProximToolbox()
ProximToolbox::ProximToolbox () protected
Instantiation not allowed.
The Constructor.
Definition at line 57 of file ProximToolbox.cc.
{
}
Member Function Documentation
addFramedWindow()
void ProximToolbox::addFramedWindow (wxWindow * window, const wxString & title, bool stayOnTop = false, const wxSize & minSize = wxSize(100, 100)) static
Adds a new simulator window in it's own floating frame.
Parameters
window Window to add.
title Title of the frame.
Definition at line 176 of file ProximToolbox.cc.
{
    // Create a new frame for the window.
    long style = wxDEFAULT_FRAME_STYLE;
    if (stayOnTop) {
    style = (style | wxFRAME_FLOAT_ON_PARENT);
    }
    wxFrame* frame = new wxFrame(
    mainFrame(), -1, title, wxDefaultPosition, wxDefaultSize, style);
    window->Reparent(frame);
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    sizer->Add(window, 1, wxGROW);
    sizer->SetSizeHints(window);
    frame->SetSizer(sizer);
    frame->Fit();
    frame->SetSizeHints(minSize.GetWidth(), minSize.GetHeight());
    frame->Show();
    return;
}
References mainFrame().
Referenced by ProximFindCmd::Do(), ProximNewPortWindowCmd::Do(), ProximNewRegisterWindowCmd::Do(), ProximShowPortsCmd::Do(), ProximShowRegistersCmd::Do(), and ProximMainFrame::onToggleWindow().
disassemblyWindow()
ProximDisassemblyWindow * ProximToolbox::disassemblyWindow () static
Returns pointer to the program disassembly window.
Returns NULL if the disassembly window does not exist.
Returns
Pointer to the disassembly window.
Definition at line 150 of file ProximToolbox.cc.
{
    wxWindow* topWindow = wxGetApp().GetTopWindow();
    if (topWindow == NULL) {
        return NULL;
    }
    wxWindow* disasmWin = topWindow->FindWindowById(
        ProximConstants::ID_DISASSEMBLY_WINDOW);
    if (disasmWin == NULL) {
        return NULL;
    }
    return dynamic_cast<ProximDisassemblyWindow*>(disasmWin);
}
References ProximConstants::ID_DISASSEMBLY_WINDOW.
Referenced by DisasmTopCountAttrProvider::DisasmTopCountAttrProvider(), ClearDisassemblyHighlightCmd::Do(), HighlightExecPercentageCmd::Do(), HighlightTopExecCountsCmd::Do(), ProximBreakpointWindow::onBreakpointLookup(), FindWindow::onFindNext(), FindWindow::onFindPrev(), FindWindow::onInputText(), and DisasmExecCountFrame::onSelection().
frontend()
TracedSimulatorFrontend * ProximToolbox::frontend () static
Returns pointer to the simulator's frontend.
Returns
Simulator frontend.
Definition at line 223 of file ProximToolbox.cc.
{
    if (wxGetApp().simulation() == NULL) {
        return NULL;
    } else {
        return wxGetApp().simulation()->frontend();
    }
}
Referenced by HighlightExecPercentageCmd::Do(), HighlightTopExecCountsCmd::Do(), ProximBusDetailsCmd::Do(), ProximFindCmd::Do(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), ProximIUDetailsCmd::Do(), ProximRFDetailsCmd::Do(), ProximSimulatorSettingsCmd::Do(), ProximSocketDetailsCmd::Do(), ProximDisassemblyGridTable::GetAttr(), ProximDisassemblyGridTable::GetNumberCols(), ProximDisassemblyGridTable::GetNumberRows(), ProximDisassemblyGridTable::GetValue(), ClearDisassemblyHighlightCmd::isEnabled(), HighlightExecPercentageCmd::isEnabled(), HighlightTopExecCountsCmd::isEnabled(), ProximDisassemblyWindow::loadProgram(), machine(), ProximBreakpointWindow::onAddBreakpoint(), ProximBreakpointWindow::onAddWatch(), ProximDisassemblyWindow::onRightClick(), ProximMainFrame::onSimulatorEvent(), ProximMachineStateWindow::onToggleUtilizations(), program(), ProximBreakpointWindow::ProximBreakpointWindow(), ProximExecuteFileCmd::ProximExecuteFileCmd(), ProximQuitCmd::ProximQuitCmd(), ProximBreakpointWindow::refreshStopPoints(), ProximMachineStateWindow::setUtilizationHighlights(), and ProximMainFrame::updateSimulationStatus().
interpreter()
SimulatorInterpreter * ProximToolbox::interpreter () static
Returns pointer to the simulator control language interpreter used by the simulator backend.
Returns
Simulator control language interpreter of the simulator.
Definition at line 207 of file ProximToolbox.cc.
{
    ProximSimulationThread* simulation = wxGetApp().simulation();
    if (simulation == NULL) {
        return NULL;
    }
    return simulation->interpreter();
}
References ProximSimulationThread::interpreter().
Referenced by testCondition(), and testExpression().
lineReader()
ProximLineReader & ProximToolbox::lineReader () static
Returns reference to the line reader used by the simulator engine.
Returns
Simulator linereader.
Definition at line 238 of file ProximToolbox.cc.
{
    return wxGetApp().simulation()->lineReader();
}
Referenced by ProximExecuteFileCmd::Do(), ProximQuitCmd::Do(), ProximSimulatorSettingsCmd::Do(), AddBreakpointDialog::onOK(), AddWatchDialog::onOK(), BreakpointPropertiesDialog::onOK(), WatchPropertiesDialog::onOK(), and ProximMainFrame::onToggleWindow().
machine()
const TTAMachine::Machine & ProximToolbox::machine () static
Returns the simulated machine.
Returns NullMachine, if a machine is not loaded in the simulator.
Returns
Reference to the simulated machine.
Definition at line 69 of file ProximToolbox.cc.
                       {
    TracedSimulatorFrontend* frontend = wxGetApp().simulation()->frontend();
    if (frontend == NULL) {
        return TTAMachine::NullMachine::instance();
    } else {
        return frontend->machine();
    }
}
References frontend(), TTAMachine::NullMachine::instance(), and SimulatorFrontend::machine().
Referenced by AddWatchDialog::initialize(), AddWatchDialog::onASChoice(), AddWatchDialog::onFUChoice(), AddWatchDialog::onRFChoice(), ProximMachineStateWindow::ProximMachineStateWindow(), and ProximMachineStateWindow::setUtilizationHighlights().
machineStateWindow()
ProximMachineStateWindow * ProximToolbox::machineStateWindow () static
Returns pointer to the machine state window.
Returns NULL if the machine state window does not exist.
Returns
Pointer to the machine state window.
Definition at line 123 of file ProximToolbox.cc.
{
    wxWindow* topWindow = wxGetApp().GetTopWindow();
    if (topWindow == NULL) {
        return NULL;
    }
    wxWindow* machineWin = topWindow->FindWindowById(
        ProximConstants::ID_MACHINE_STATE_WINDOW);
    if (machineWin == NULL) {
        return NULL;
    }
    return dynamic_cast<ProximMachineStateWindow*>(machineWin);
}
References ProximConstants::ID_MACHINE_STATE_WINDOW.
Referenced by ProximBusDetailsCmd::Do(), ProximComponentStatusCmd::Do(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), ProximIUDetailsCmd::Do(), ProximRFDetailsCmd::Do(), ProximSetMachineWinStatusCmd::Do(), ProximSocketDetailsCmd::Do(), and ProximMachineCanvasTool::onMouseEvent().
mainFrame()
ProximMainFrame * ProximToolbox::mainFrame () static
Returns pointer to the application main frame.
Returns
Application main frame, or NULL if the main frame does not exist.
Definition at line 105 of file ProximToolbox.cc.
{
    wxWindow* topWindow = wxGetApp().GetTopWindow();
    if (topWindow != NULL) {
        return dynamic_cast<ProximMainFrame*>(topWindow);
    } else {
        return NULL;
    }
}
Referenced by addFramedWindow(), ProximFindCmd::Do(), ProximNewPortWindowCmd::Do(), ProximNewRegisterWindowCmd::Do(), ProximOptionsCmd::Do(), ProximShowPortsCmd::Do(), ProximShowRegistersCmd::Do(), and ProximSimulatorWindow::~ProximSimulatorWindow().
program()
const TTAProgram::Program & ProximToolbox::program () static
Returns the simulated program.
Returns NullProgram, if a program is not loaded in the simulator.
Returns
Reference to the simulated program.
Definition at line 88 of file ProximToolbox.cc.
                       {
    TracedSimulatorFrontend* frontend = wxGetApp().simulation()->frontend();
    if (frontend == NULL) {
        return TTAProgram::NullProgram::instance();
    } else {
        return frontend->program();
    }
}
References frontend(), TTAProgram::NullProgram::instance(), and SimulatorFrontend::program().
Referenced by ProximSetMachineWinStatusCmd::Do(), FindWindow::find(), ProximDebuggerWindow::onProgramLoaded(), ProximDisassemblyWindow::onProgramLoaded(), ProximDebuggerWindow::ProximDebuggerWindow(), and ProximDebuggerWindow::updateAnnotations().
testCondition()
bool ProximToolbox::testCondition (wxWindow * parent, const std::string & condition) static
Tests condition script validity.
An error dialog is displayed if the script is not legal.
Parameters
parent Parent window for the possible error dialog to display.
condition Condition script to test.
Definition at line 280 of file ProximToolbox.cc.
{
    TclConditionScript conditionScript(interpreter(), condition);
    // Check condition script validity using script interpreter.
    try {
        conditionScript.execute();
    } catch (const ScriptExecutionFailure& sef) {
        // Condition erroneous. Display error dialog.
        wxString message = _T("Error in condition:\n");
        message.Append(WxConversion::toWxString(sef.errorMessage()));
        ErrorDialog dialog(parent, message);
        dialog.ShowModal();
        return false;
    }
    return true;
}
References Exception::errorMessage(), Script::execute(), interpreter(), and WxConversion::toWxString().
Referenced by BreakpointPropertiesDialog::onOK(), and WatchPropertiesDialog::onOK().
testExpression()
bool ProximToolbox::testExpression (wxWindow * parent, const std::string & expression) static
Tests expression script validity.
An error dialog is displayed if the script is not legal.
Parameters
parent Parent window for the possible error dialog to display.
expression Expression script to test.
Definition at line 252 of file ProximToolbox.cc.
{
    ExpressionScript expressionScript(interpreter(), expression);
    // Check condition script validity using script interpreter.
    try {
        expressionScript.execute();
    } catch (const ScriptExecutionFailure& sef) {
        // Condition erroneous. Display error dialog.
        wxString message = _T("Error in expression:\n");
        message.Append(WxConversion::toWxString(sef.errorMessage()));
        ErrorDialog dialog(parent, message);
        dialog.ShowModal();
        return false;
    }
    return true;
}
References Exception::errorMessage(), Script::execute(), interpreter(), and WxConversion::toWxString().
Referenced by AddWatchDialog::onOK().
The documentation for this class was generated from the following files:
ProximToolbox.hh
ProximToolbox.cc