OpenASIP: ProGe::Signal Class Reference
ProGe::Signal Class Reference
#include <Signal.hh>
Public Member Functions
Signal ()
Signal (SignalType type, ActiveState activeState=ActiveState::HIGH)
virtual ~Signal ()
SignalType type () const
ActiveState activeState () const
bool operator== (SignalType type) const
bool operator== (const Signal &other) const
Private Attributes
SignalType type_ = SignalType::UNDEFINED
Signal purpose type id.
ActiveState activeState_ = ActiveState::HIGH
The active state of the signal.
Detailed Description
Definition at line 46 of file Signal.hh.
Constructor & Destructor Documentation
Signal() [1/2]
ProGe::Signal::Signal ()
Definition at line 38 of file Signal.cc.
               : Signal(SignalType::UNDEFINED, ActiveState::HIGH) {
}
Signal() [2/2]
ProGe::Signal::Signal (SignalType type, ActiveState activeState = ActiveState::HIGH)
Definition at line 41 of file Signal.cc.
    : type_(type),
      activeState_(activeState) {
}
~Signal()
ProGe::Signal::~Signal () virtual
Definition at line 48 of file Signal.cc.
                {
}
Member Function Documentation
activeState()
ActiveState ProGe::Signal::activeState () const
Returns state in where the signal is considered to be active.
Definition at line 63 of file Signal.cc.
{
    return activeState_;
}
References activeState_.
Referenced by ProGe::Netlist::connect().
operator==() [1/2]
bool ProGe::Signal::operator== (const Signal & other) const inline
Definition at line 59 of file Signal.hh.
{
        return (this->type_ == other.type_
            && this->activeState_ == other.activeState_);
    }
References activeState_, and type_.
operator==() [2/2]
bool ProGe::Signal::operator== (SignalType type) const inline
Definition at line 56 of file Signal.hh.
{
        return (this->type_ == type);
    }
References type_.
type()
SignalType ProGe::Signal::type () const
Returns signal's purpose specified in the comments of SignalType definition.
Definition at line 55 of file Signal.cc.
                   {
    return type_;
}
References type_.
Referenced by ProGe::NetlistPort::clone(), ProGe::NetlistPortGroup::clone(), ProGe::BaseNetlistBlock::hasPortsBy(), ProGe::BaseNetlistBlock::portsBy(), and ProGe::PortFactory::registerPort().
Member Data Documentation
activeState_
ActiveState ProGe::Signal::activeState_ = ActiveState::HIGH private
The active state of the signal.
Definition at line 71 of file Signal.hh.
Referenced by activeState(), and operator==().
type_
SignalType ProGe::Signal::type_ = SignalType::UNDEFINED private
Signal purpose type id.
Definition at line 69 of file Signal.hh.
Referenced by operator==(), operator==(), and type().
The documentation for this class was generated from the following files:
Signal.hh
Signal.cc