OpenASIP: UnitContainerFigure Class Reference
UnitContainerFigure Class Reference
#include <UnitContainerFigure.hh>
Public Member Functions
UnitContainerFigure ()
virtual ~UnitContainerFigure ()
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
Protected Member Functions inherited from Figure
virtual void drawSelf (wxDC *dc)
void drawChildren (wxDC *dc)
Private Member Functions
UnitContainerFigure & operator= (UnitContainerFigure &old)
Assignment not allowed.
UnitContainerFigure (UnitContainerFigure &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a container EditPart for units.
Definition at line 46 of file UnitContainerFigure.hh.
Constructor & Destructor Documentation
UnitContainerFigure() [1/2]
UnitContainerFigure::UnitContainerFigure ()
The Constructor.
Definition at line 44 of file UnitContainerFigure.cc.
                                        : Figure() {
}
~UnitContainerFigure()
UnitContainerFigure::~UnitContainerFigure () virtual
The Destructor.
Definition at line 50 of file UnitContainerFigure.cc.
{
}
UnitContainerFigure() [2/2]
UnitContainerFigure::UnitContainerFigure (UnitContainerFigure & old) private
Copying not allowed.
Member Function Documentation
layoutChildren()
void UnitContainerFigure::layoutChildren (wxDC * dc) protected virtual
Lays out the units in a row, spaced evenly.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 59 of file UnitContainerFigure.cc.
{
    int unitX = location_.x;
    int unitY = location_.y;
    for(unsigned int i = 0; i < children_.size(); i++) {
    if (!children_[i]->xSet()) {
        children_[i]->setLocation(wxPoint(unitX, unitY));
        children_[i]->layout(dc);
        unitX += children_[i]->bounds().GetWidth() +
        MachineCanvasLayoutConstraints::UNIT_SPACE;
    } else {
        children_[i]->layout(dc);
        unitX = children_[i]->location().x +
        children_[i]->bounds().GetWidth() +
        MachineCanvasLayoutConstraints::UNIT_SPACE;
    }
    }
}
References Figure::children_, Figure::location_, Figure::setLocation(), MachineCanvasLayoutConstraints::UNIT_SPACE, and Figure::xSet().
layoutSelf()
void UnitContainerFigure::layoutSelf (wxDC *) protected virtual
Calculates and sets the size of the container.
Depends on the amount and position of the units.
Reimplemented from Figure.
Definition at line 87 of file UnitContainerFigure.cc.
{
    int maxIndex = 0;
    int maxX = 0;
    for (unsigned int i = 0; i < children_.size(); i++) {
    if (children_[i]->location().x > maxX) {
        maxX = children_[i]->location().x;
        maxIndex = i;
    }
    }
    int width = maxX + children_[maxIndex]->bounds().GetWidth() -
    location_.x;
    if (width > size_.GetWidth()) {
        size_.SetWidth(width);
    }
    if (size_.GetHeight() == 0) {
    size_.SetHeight(children_[0]->bounds().GetHeight());
    }
}
References Figure::bounds(), Figure::children_, Figure::location(), Figure::location_, and Figure::size_.
operator=()
UnitContainerFigure & UnitContainerFigure::operator= (UnitContainerFigure & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
UnitContainerFigure.hh
UnitContainerFigure.cc