OpenASIP: OSEdAddModuleCmd Class Reference
OSEdAddModuleCmd Class Reference
#include <OSEdAddModuleCmd.hh>
Public Member Functions
OSEdAddModuleCmd ()
virtual ~OSEdAddModuleCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdAddModuleCmd (const OSEdAddModuleCmd &)
Copying not allowed.
OSEdAddModuleCmd & operator= (const OSEdAddModuleCmd &)
Assignment not allowed.
Detailed Description
Command for adding new module to operation set.
Definition at line 43 of file OSEdAddModuleCmd.hh.
Constructor & Destructor Documentation
OSEdAddModuleCmd() [1/2]
OSEdAddModuleCmd::OSEdAddModuleCmd ()
Constructor.
Definition at line 57 of file OSEdAddModuleCmd.cc.
                                   :
    GUICommand(OSEdConstants::CMD_NAME_ADD_MODULE, NULL) {
}
Referenced by create().
~OSEdAddModuleCmd()
OSEdAddModuleCmd::~OSEdAddModuleCmd () virtual
Destructor.
Definition at line 64 of file OSEdAddModuleCmd.cc.
{
}
OSEdAddModuleCmd() [2/2]
OSEdAddModuleCmd::OSEdAddModuleCmd (const OSEdAddModuleCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdAddModuleCmd::create () const virtual
Creates a new command.
Returns
New command.
Implements GUICommand.
Definition at line 83 of file OSEdAddModuleCmd.cc.
{
    return new OSEdAddModuleCmd();
}
References OSEdAddModuleCmd().
Do()
bool OSEdAddModuleCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 93 of file OSEdAddModuleCmd.cc.
                     {
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTreeView* treeView = mainFrame->treeView();
    string path = treeView->selectedPath();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    wxTreeItemId pathId = treeView->selectedPathId();
    OperationIndex& index = OperationContainer::operationIndex();
    if (!FileSystem::fileExists(path)) {
        if (!FileSystem::createDirectory(path)) {
            format fmt =
                texts.text(OSEdTextGenerator::TXT_ERROR_CAN_NOT_CREATE_MOD);
            ErrorDialog error(
                parentWindow(), WxConversion::toWxString(fmt.str()));
            error.ShowModal();
            return false;
        }
        index.addPath(path);
        treeView->SetItemBold(pathId);
    }
    AddModuleDialog dialog(parentWindow(), path);
    if (dialog.ShowModal() == wxID_OK) {
        OperationModule* module = new OperationModule(dialog.name(), path);
        OperationSerializer& serializer =
            OperationContainer::operationSerializer();
        serializer.setDestinationFile(module->propertiesModule());
        ObjectState* root = new ObjectState("osal");
        try {
            serializer.writeState(root);
        } catch (const Exception& e) {
            format fmt = texts.text(
                OSEdTextGenerator::TXT_ERROR_CAN_NOT_CREATE_MOD);
            ErrorDialog error(parentWindow(),
                              WxConversion::toWxString(fmt.str()));
            error.ShowModal();
            delete root;
            return false;
        }
        delete root;
        index.addModule(module, path);
        treeView->addItem(pathId, module->name());
        treeView->update();
    }
    return true;
}
References OSEdTreeView::addItem(), OperationIndex::addModule(), OperationIndex::addPath(), FileSystem::createDirectory(), FileSystem::fileExists(), OSEdTextGenerator::instance(), OperationContainer::operationIndex(), OperationContainer::operationSerializer(), GUICommand::parentWindow(), OSEdTreeView::selectedPath(), OSEdTreeView::selectedPathId(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdMainFrame::treeView(), OSEdTextGenerator::TXT_ERROR_CAN_NOT_CREATE_MOD, and OSEdTreeView::update().
icon()
string OSEdAddModuleCmd::icon () const virtual
Return icon path.
Returns
Empty string (no icons used).
Implements GUICommand.
Definition at line 181 of file OSEdAddModuleCmd.cc.
{
    return "";
}
id()
int OSEdAddModuleCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 73 of file OSEdAddModuleCmd.cc.
{
    return OSEdConstants::CMD_ADD_MODULE;
}
References OSEdConstants::CMD_ADD_MODULE.
isEnabled()
bool OSEdAddModuleCmd::isEnabled () virtual
Returns true if command is enabled.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 150 of file OSEdAddModuleCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    string path = treeView->selectedPath();
    if (path != "") {
        if (FileSystem::fileExists(path)) {
            string dumbFile = path + FileSystem::DIRECTORY_SEPARATOR +
                "dumb12234";
            if (FileSystem::createFile(dumbFile)) {
                FileSystem::removeFileOrDirectory(dumbFile);
                return true;
            } else {
                return false;
            }
        } else {
            if (FileSystem::createDirectory(path)) {
                FileSystem::removeFileOrDirectory(path);
                return true;
            } else {
                return false;
            }
        }
    }
    return false;
}
References FileSystem::createDirectory(), FileSystem::createFile(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), FileSystem::removeFileOrDirectory(), and OSEdTreeView::selectedPath().
operator=()
OSEdAddModuleCmd & OSEdAddModuleCmd::operator= (const OSEdAddModuleCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdAddModuleCmd.hh
OSEdAddModuleCmd.cc