OpenASIP: ProximUnitWindow Class Reference
ProximUnitWindow Class Reference
#include <ProximUnitWindow.hh>
Public Member Functions
ProximUnitWindow (ProximMainFrame *parent, int id)
virtual ~ProximUnitWindow ()
Public Member Functions inherited from ProximSimulatorWindow
virtual void reset ()
Protected Attributes
SimulatorFrontend * simulator_
Simulator instance .
wxChoice * unitChoice_
Unit choicer widget.
wxChoice * modeChoice_
Value display mode choicer widget.
wxListCtrl * valueList_
List widget for the values.
Static Protected Attributes
static const wxString MODE_INT = _T("Int")
String for the mode choicer integer mode.
static const wxString MODE_UNSIGNED = _T("Unsigned")
String for the mode choicer unsigned integer mode.
static const wxString MODE_HEX = _T("Hex")
String for the mode choicer hexadecimal mode.
static const wxString MODE_BIN = _T("Binary")
String for the mode choicer binary mode.
Private Types
enum {
ID_UNIT_CHOICE = 10000 , ID_MODE_CHOICE , ID_HELP , ID_CLOSE ,
ID_LINE , ID_VALUE_LIST
}
Private Member Functions
void onProgramLoaded (const SimulatorEvent &event)
void onSimulationStop (const SimulatorEvent &event)
void onChoice (wxCommandEvent &event)
void onClose (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual void reinitialize ()
virtual void update ()
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Parent class for windows displaying list information of the Proxim machine state window units.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 51 of file ProximUnitWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_UNIT_CHOICE
ID_MODE_CHOICE
ID_HELP
ID_CLOSE
ID_LINE
ID_VALUE_LIST
Definition at line 87 of file ProximUnitWindow.hh.
         {
    ID_UNIT_CHOICE = 10000,
        ID_MODE_CHOICE,
    ID_HELP,
    ID_CLOSE,
    ID_LINE,
    ID_VALUE_LIST
    };
Constructor & Destructor Documentation
ProximUnitWindow()
ProximUnitWindow::ProximUnitWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 67 of file ProximUnitWindow.cc.
                                    :
    ProximSimulatorWindow(parent, id),
    unitChoice_(NULL),
    valueList_(NULL) {
    createContents(this, true, true);
    simulator_ = wxGetApp().simulation()->frontend();
    unitChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_UNIT_CHOICE));
    modeChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_MODE_CHOICE));
    valueList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_VALUE_LIST));
    modeChoice_->Append(MODE_INT);
    modeChoice_->Append(MODE_UNSIGNED);
    modeChoice_->Append(MODE_HEX);
    modeChoice_->Append(MODE_BIN);
    modeChoice_->SetSelection(0);
}
~ProximUnitWindow()
ProximUnitWindow::~ProximUnitWindow () virtual
Destructor.
Definition at line 93 of file ProximUnitWindow.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ProximUnitWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the window contents.
Code generated by wxWidgets.
Parameters
parent Parent window of the dialog contents.
call_fit If true, created contents are fit inside the parent window.
set_sizer If true, created top level sizer is set as the parent window contents.
Returns
Top level sizer of the created widgets.
Definition at line 169 of file ProximUnitWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 2 );
    wxGridSizer *item1 = new wxGridSizer( 2, 0, 0 );
    wxString *strs2 = (wxString*) NULL;
    wxChoice *item2 = new wxChoice( parent, ID_UNIT_CHOICE, wxDefaultPosition, wxSize(120,-1), 0, strs2, 0 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxChoice *item3 = new wxChoice( parent, ID_MODE_CHOICE, wxDefaultPosition, wxSize(120,-1), 0, strs3, 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item4 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item4, 0, wxGROW|wxALL, 5 );
    wxListCtrl *item5 = new wxListCtrl( parent, ID_VALUE_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxSUNKEN_BORDER );
    item0->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item6 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item6, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item7 = new wxGridSizer( 2, 0, 0 );
    wxButton *item8 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER_VERTICAL, 5 );
    wxButton *item9 = new wxButton( parent, ID_CLOSE, wxT("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CLOSE, ID_HELP, ID_LINE, ID_MODE_CHOICE, ID_UNIT_CHOICE, and ID_VALUE_LIST.
onChoice()
void ProximUnitWindow::onChoice (wxCommandEvent & event) private
Event handler for the dialog mode and unit choicers.
Updates the values list.
Definition at line 139 of file ProximUnitWindow.cc.
{
    update();
}
References update().
onClose()
void ProximUnitWindow::onClose (wxCommandEvent & event) private
Event handler for the Close button.
Closes the window by destroying the parent frame of the window.
Definition at line 149 of file ProximUnitWindow.cc.
{
    wxFrame* parent = dynamic_cast<wxFrame*>(GetParent());
    if (parent != NULL) {
    parent->Destroy();
    }
}
onProgramLoaded()
void ProximUnitWindow::onProgramLoaded (const SimulatorEvent & event) private
Event handler which is called when a new program is loaded in the simulator.
Definition at line 109 of file ProximUnitWindow.cc.
{
    reinitialize();
}
References reinitialize().
onSimulationStop()
void ProximUnitWindow::onSimulationStop (const SimulatorEvent & event) private
Event handler for simulation stop.
Updates the value list.
Definition at line 128 of file ProximUnitWindow.cc.
{
    update();
}
References update().
reinitialize()
void ProximUnitWindow::reinitialize () private virtual
Called when the unit choicer needs to be reinitialized.
Reimplemented in ProximPortWindow, and ProximRegisterWindow.
Definition at line 101 of file ProximUnitWindow.cc.
{
}
Referenced by onProgramLoaded().
update()
void ProximUnitWindow::update () private virtual
Called when the value list needs to be updated.
Reimplemented in ProximPortWindow, and ProximRegisterWindow.
Definition at line 118 of file ProximUnitWindow.cc.
{
}
Referenced by onChoice(), and onSimulationStop().
Member Data Documentation
MODE_BIN
const wxString ProximUnitWindow::MODE_BIN = _T("Binary") static protected
String for the mode choicer binary mode.
Definition at line 73 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), and ProximPortWindow::update().
MODE_HEX
const wxString ProximUnitWindow::MODE_HEX = _T("Hex") static protected
String for the mode choicer hexadecimal mode.
Definition at line 71 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), and ProximPortWindow::update().
MODE_INT
const wxString ProximUnitWindow::MODE_INT = _T("Int") static protected
String for the mode choicer integer mode.
Definition at line 67 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), and ProximPortWindow::update().
MODE_UNSIGNED
const wxString ProximUnitWindow::MODE_UNSIGNED = _T("Unsigned") static protected
String for the mode choicer unsigned integer mode.
Definition at line 69 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), and ProximPortWindow::update().
modeChoice_
wxChoice* ProximUnitWindow::modeChoice_ protected
Value display mode choicer widget.
Definition at line 62 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), ProximRegisterWindow::ProximRegisterWindow(), ProximPortWindow::update(), and ProximRegisterWindow::update().
simulator_
SimulatorFrontend* ProximUnitWindow::simulator_ protected
Simulator instance .
Definition at line 58 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), ProximPortWindow::ProximPortWindow(), ProximRegisterWindow::ProximRegisterWindow(), ProximPortWindow::reinitialize(), ProximRegisterWindow::reinitialize(), ProximPortWindow::update(), and ProximRegisterWindow::update().
unitChoice_
wxChoice* ProximUnitWindow::unitChoice_ protected
Unit choicer widget.
Definition at line 60 of file ProximUnitWindow.hh.
Referenced by ProximPortWindow::reinitialize(), ProximRegisterWindow::reinitialize(), ProximPortWindow::showFunctionUnit(), ProximRegisterWindow::showImmediateUnit(), ProximRegisterWindow::showRegisterFile(), ProximPortWindow::update(), and ProximRegisterWindow::update().
valueList_
wxListCtrl* ProximUnitWindow::valueList_ protected
List widget for the values.
Definition at line 64 of file ProximUnitWindow.hh.
Referenced by ProximRegisterWindow::loadImmediateUnit(), ProximRegisterWindow::loadRegisterFile(), ProximPortWindow::ProximPortWindow(), ProximRegisterWindow::ProximRegisterWindow(), and ProximPortWindow::update().
The documentation for this class was generated from the following files:
ProximUnitWindow.hh
ProximUnitWindow.cc