OpenASIP: TPEF::InstructionElement Class Reference
TPEF::InstructionElement Class Reference
#include <InstructionElement.hh>
Public Member Functions
virtual ~InstructionElement ()
bool isMove () const
bool isImmediate () const
bool begin () const
void setBegin (bool isBegin)
InstructionAnnotation * annotation (Word index) const
void addAnnotation (InstructionAnnotation *anAnnotation)
Word annotationCount () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
InstructionElement (bool isMove)
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Attributes
bool begin_
Is the first element of whole instruction.
bool isMove_
Is move or immediate.
std::vector< InstructionAnnotation * > annotations_
All annotations.
Detailed Description
Abstract base class for all instructions of CodeSection.
Definition at line 77 of file InstructionElement.hh.
Constructor & Destructor Documentation
~InstructionElement()
TPEF::InstructionElement::~InstructionElement () virtual
Destructor
Definition at line 83 of file InstructionElement.cc.
{
    for (Word i = 0; i < annotationCount(); i++) {
        delete annotation(i);
    }
}
References annotation(), and annotationCount().
InstructionElement()
TPEF::InstructionElement::InstructionElement (bool isMove) protected
Constructor
Definition at line 76 of file InstructionElement.cc.
                                                  :
    SectionElement(), begin_(false), isMove_(isMove) {
}
Member Function Documentation
addAnnotation()
void TPEF::InstructionElement::addAnnotation (InstructionAnnotation * anAnnotation)
Referenced by CodeSectionCreator::addAnnotationes(), TTAProgram::ProgramWriter::createCodeSection(), TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFCodeSectionReader::readAnnotations().
annotation()
InstructionAnnotation * TPEF::InstructionElement::annotation (Word index) const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createTerminal(), TPEF::TPEFCodeSectionWriter::writeAnnotations(), and ~InstructionElement().
annotationCount()
Word TPEF::InstructionElement::annotationCount () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createTerminal(), TPEF::TPEFCodeSectionWriter::writeAnnotations(), and ~InstructionElement().
begin()
bool TPEF::InstructionElement::begin () const
Referenced by TPEF::TPEFCodeSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::addProcedures(), TPEFDisassembler::createInstruction(), CodeCompressorPlugin::immediateTerminal(), TPEFDisassembler::initCache(), CodeCompressorPlugin::initializeRelocations(), TPEF::CodeSection::initInstructionCache(), and TPEF::TPEFCodeSectionReader::readData().
isImmediate()
bool TPEF::InstructionElement::isImmediate () const
Referenced by TTAProgram::TPEFProgramFactory::addProcedures(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), CodeCompressorPlugin::initializeRelocations(), and TPEF::TPEFCodeSectionWriter::writeAttributeField().
isMove()
bool TPEF::InstructionElement::isMove () const
Referenced by TTAProgram::TPEFProgramFactory::addProcedures(), and TPEFDisassembler::createInstruction().
setBegin()
void TPEF::InstructionElement::setBegin (bool isBegin)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
Member Data Documentation
annotations_
std::vector<InstructionAnnotation*> TPEF::InstructionElement::annotations_ private
All annotations.
Definition at line 101 of file InstructionElement.hh.
begin_
bool TPEF::InstructionElement::begin_ private
Is the first element of whole instruction.
Definition at line 96 of file InstructionElement.hh.
isMove_
bool TPEF::InstructionElement::isMove_ private
Is move or immediate.
Definition at line 98 of file InstructionElement.hh.
The documentation for this class was generated from the following files:
InstructionElement.hh
InstructionElement.cc