OpenASIP: PrintPreviewCmd Class Reference
PrintPreviewCmd Class Reference
#include <PrintPreviewCmd.hh>
Public Member Functions
PrintPreviewCmd ()
virtual ~PrintPreviewCmd ()
virtual bool Do ()
virtual int id () const
virtual PrintPreviewCmd * create () const
virtual std::string shortName () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for previewing print of documents.
Definition at line 42 of file PrintPreviewCmd.hh.
Constructor & Destructor Documentation
PrintPreviewCmd()
PrintPreviewCmd::PrintPreviewCmd ()
The Constructor.
Definition at line 46 of file PrintPreviewCmd.cc.
                                :
    EditorCommand(ProDeConstants::CMD_NAME_PRINT_PREVIEW) {
}
Referenced by create().
~PrintPreviewCmd()
PrintPreviewCmd::~PrintPreviewCmd () virtual
The Destructor.
Definition at line 55 of file PrintPreviewCmd.cc.
{
}
Member Function Documentation
create()
PrintPreviewCmd * PrintPreviewCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 114 of file PrintPreviewCmd.cc.
{
    return new PrintPreviewCmd();
}
References PrintPreviewCmd().
Do()
bool PrintPreviewCmd::Do () virtual
Executes the command.
If the wxWidgets printing framework was not compiled in the wxWidgets library, print previeving is not possible. An error message will be displayed instead of previewing.
Returns
Always false. The command is not undoable.
Implements GUICommand.
Definition at line 69 of file PrintPreviewCmd.cc.
                    {
#if WX_PRINTING_DISABLED
    // wxWidgets was compiled without printing framework, display an
    // error message.
    wxString message =
        wxString(_T("Printing framework is disabled in the wxWidgets\n"));
    message.Append(_T("library. Print previewing is not possible."));
    ErrorDialog error(parentWindow(), message);
    error.ShowModal();
    return false;
#else
    // wxWidgets was compiled with the printing framework.
    wxCommandEvent dummy;
    wxGetApp().docManager()->OnPreview(dummy);
    return false;
#endif // WX_PRINTING_ENABLED
}
References dummy, and GUICommand::parentWindow().
icon()
string PrintPreviewCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 136 of file PrintPreviewCmd.cc.
{
    return ProDeConstants::CMD_ICON_PRINT_PREVIEW;
}
References ProDeConstants::CMD_ICON_PRINT_PREVIEW.
id()
int PrintPreviewCmd::id () const virtual
Return id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 103 of file PrintPreviewCmd.cc.
{
    return ProDeConstants::COMMAND_PRINT_PREVIEW;
}
References ProDeConstants::COMMAND_PRINT_PREVIEW.
isEnabled()
bool PrintPreviewCmd::isEnabled () virtual
Returns true when command is executable, false when not.
This command is executable when a document is open.
Returns
True, if the command is executable.
Reimplemented from EditorCommand.
Definition at line 149 of file PrintPreviewCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string PrintPreviewCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 125 of file PrintPreviewCmd.cc.
{
    return ProDeConstants::CMD_SNAME_PRINT_PREVIEW;
}
References ProDeConstants::CMD_SNAME_PRINT_PREVIEW.
The documentation for this class was generated from the following files:
PrintPreviewCmd.hh
PrintPreviewCmd.cc