OpenASIP: EntryKeyDataInt Class Reference
EntryKeyDataInt Class Reference
#include <EntryKeyData.hh>
Public Member Functions
EntryKeyDataInt ()
EntryKeyDataInt (int fieldData)
virtual ~EntryKeyDataInt ()
EntryKeyData * copy () const
bool isEqual (const EntryKeyData *fieldData) const
bool isGreater (const EntryKeyData *fieldData) const
bool isSmaller (const EntryKeyData *fieldData) const
double coefficient (const EntryKeyData *data1, const EntryKeyData *data2) const
std::string toString () const
Public Member Functions inherited from EntryKeyData
EntryKeyData ()
virtual ~EntryKeyData ()
Private Member Functions
EntryKeyDataInt (const EntryKeyDataInt &)
Copying not allowed.
EntryKeyDataInt & operator= (const EntryKeyDataInt &)
Assignment not allowed.
Private Attributes
int data_
Integer data.
Detailed Description
Implementation for integer type of data.
Definition at line 83 of file EntryKeyData.hh.
Constructor & Destructor Documentation
EntryKeyDataInt() [1/3]
EntryKeyDataInt::EntryKeyDataInt ()
Default constructor.
Definition at line 73 of file EntryKeyData.cc.
                                 : data_(0) {
}
Referenced by copy().
EntryKeyDataInt() [2/3]
EntryKeyDataInt::EntryKeyDataInt (int fieldData)
Constructor.
Parameters
fieldData An integer.
Definition at line 81 of file EntryKeyData.cc.
                                              : data_(fieldData) {
}
~EntryKeyDataInt()
EntryKeyDataInt::~EntryKeyDataInt () virtual
Destructor.
Definition at line 87 of file EntryKeyData.cc.
{
}
EntryKeyDataInt() [3/3]
EntryKeyDataInt::EntryKeyDataInt (const EntryKeyDataInt &) private
Copying not allowed.
Member Function Documentation
coefficient()
double EntryKeyDataInt::coefficient (const EntryKeyData * data1, const EntryKeyData * data2) const virtual
Returns the relative position between two integers.
Returns the integer's relative position to the first integer compared to the second. For example, if this integer is 14, the first integer is 10 and the second 20, relative position would be 0.4.
Parameters
data1 First integer.
data2 Second integer.
Returns
The relative position between two integers.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 179 of file EntryKeyData.cc.
{
    EntryKeyDataInt* int1 = dynamic_cast<EntryKeyDataInt*>(
                        const_cast<EntryKeyData*>(data1));
    EntryKeyDataInt* int2 = dynamic_cast<EntryKeyDataInt*>(
                        const_cast<EntryKeyData*>(data2));
    if (int1 == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataInt::coefficient param1");
    }
    if (int2 == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataInt::coefficient param2");
    }
    return static_cast<double>(data_ - int1->data_) /
    static_cast<double>(int2->data_ - int1->data_);
}
References data_.
copy()
EntryKeyData * EntryKeyDataInt::copy () const virtual
Copies integer.
Client is responsible of deallocating the memory reserved for the returned object.
Returns
A copy of the integer.
Implements EntryKeyData.
Definition at line 99 of file EntryKeyData.cc.
{
    return new EntryKeyDataInt(data_);
}
References data_, and EntryKeyDataInt().
isEqual()
bool EntryKeyDataInt::isEqual (const EntryKeyData * fieldData) const virtual
Checks if two integers are equal.
Cannot compare integers to other data types.
Parameters
fieldData An integer.
Returns
True if two integers are equal.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 113 of file EntryKeyData.cc.
{
    EntryKeyDataInt* integer = dynamic_cast<EntryKeyDataInt*>(
                           const_cast<EntryKeyData*>(fieldData));
    if (integer == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataInt::isEqual");
    }
    return data_ == integer->data_;
}
References data_.
isGreater()
bool EntryKeyDataInt::isGreater (const EntryKeyData * fieldData) const virtual
Checks if this integer is greater than another integer.
Cannot compare integers to other data types.
Parameters
fieldData An integer.
Returns
True if this integer is greater than another integer, otherwise false.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 134 of file EntryKeyData.cc.
{
    EntryKeyDataInt* integer = dynamic_cast<EntryKeyDataInt*>(
                           const_cast<EntryKeyData*>(fieldData));
    if (integer == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataInt::isGreater");
    }
    return data_ > integer->data_;
}
References data_.
isSmaller()
bool EntryKeyDataInt::isSmaller (const EntryKeyData * fieldData) const virtual
Checks if this integer is smaller than another integer.
Cannot compare integers to other data types.
Parameters
fieldData An integer.
Returns
True if this integer is smaller than another integer, otherwise false.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 155 of file EntryKeyData.cc.
{
    EntryKeyDataInt* integer = dynamic_cast<EntryKeyDataInt*>(
                           const_cast<EntryKeyData*>(fieldData));
    if (integer == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataInt::isSmaller");
    }
    return data_ < integer->data_;
}
References data_.
operator=()
EntryKeyDataInt & EntryKeyDataInt::operator= (const EntryKeyDataInt &) private
Assignment not allowed.
toString()
std::string EntryKeyDataInt::toString () const virtual
Converts the integer into a string.
Returns
integer as a string
Implements EntryKeyData.
Definition at line 204 of file EntryKeyData.cc.
{
    return Conversion::toString(data_);
}
References data_, and Conversion::toString().
Member Data Documentation
data_
int EntryKeyDataInt::data_ private
Integer data.
Definition at line 99 of file EntryKeyData.hh.
Referenced by coefficient(), copy(), isEqual(), isGreater(), isSmaller(), and toString().
The documentation for this class was generated from the following files:
EntryKeyData.hh
EntryKeyData.cc