OpenASIP: SchedulerPass Class Reference
SchedulerPass Class Reference abstract
#include <SchedulerPass.hh>
Public Member Functions
SchedulerPass (InterPassData &data)
virtual ~SchedulerPass ()
InterPassData & interPassData ()
virtual std::string shortDescription () const =0
virtual std::string longDescription () const
Private Attributes
InterPassData * data_
arbitrary data stored by different passes for inter-pass communication
Detailed Description
Interface for scheduler passes with different scopes.
Definition at line 43 of file SchedulerPass.hh.
Constructor & Destructor Documentation
SchedulerPass()
SchedulerPass::SchedulerPass (InterPassData & data)
Constructor.
Parameters
data The container that stores data passed between scheduler passes.
Definition at line 40 of file SchedulerPass.cc.
                                                :
    data_(&data) {
}
~SchedulerPass()
virtual SchedulerPass::~SchedulerPass () inline virtual
Definition at line 46 of file SchedulerPass.hh.
{};
Member Function Documentation
interPassData()
InterPassData & SchedulerPass::interPassData ()
Returns the inter-pass data container that can be used by the pass.
The object is a generic container for data passed between scheduler passes.
Parameters
data The data object.
Definition at line 53 of file SchedulerPass.cc.
{
    return *data_;
}
References data_.
Referenced by ProgramPass::executeProcedurePass(), BBSchedulerController::handleBasicBlock(), BBSchedulerController::handleCFGDDG(), PreOptimizer::handleControlFlowGraph(), BBSchedulerController::handleProcedure(), BF2Scheduler::possibleTempRegRFs(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), SequentialScheduler::scheduleRRMove(), BasicBlockScheduler::scheduleRRMove(), and BUBasicBlockScheduler::scheduleRRMove().
longDescription()
std::string SchedulerPass::longDescription () const virtual
Optional longer description of the pass.
This description can include usage instructions, details of choice of algorithmic details, etc.
Returns
The description as a string.
Reimplemented in BasicBlockScheduler, BUBasicBlockScheduler, SequentialScheduler, and BBSchedulerController.
Definition at line 77 of file SchedulerPass.cc.
{
    return "";
}
shortDescription()
std::string SchedulerPass::shortDescription () const pure virtual
A short description of the pass, usually the optimization name, such as "basic block scheduler".
Returns
The description as a string.
Implemented in BasicBlockScheduler, BUBasicBlockScheduler, CallsToJumps, PostpassOperandSharer, PreOptimizer, ScheduleEstimator, SequentialScheduler, SimpleIfConverter, AbsoluteToRelativeJumps, BBSchedulerController, BF2Scheduler, and Peel2BBLoops.
Definition at line 64 of file SchedulerPass.cc.
{
    return "";
}
Member Data Documentation
data_
InterPassData* SchedulerPass::data_ private
arbitrary data stored by different passes for inter-pass communication
Definition at line 55 of file SchedulerPass.hh.
Referenced by interPassData().
The documentation for this class was generated from the following files:
SchedulerPass.hh
SchedulerPass.cc