OpenASIP: CompiledSimUtilizationStats Class Reference
CompiledSimUtilizationStats Class Reference
#include <CompiledSimUtilizationStats.hh>
Public Member Functions
CompiledSimUtilizationStats ()
virtual ~CompiledSimUtilizationStats ()
virtual void calculate (const TTAProgram::Program &program, const CompiledSimulation &compiledSim)
Public Member Functions inherited from UtilizationStats
UtilizationStats ()
virtual ~UtilizationStats ()
virtual void calculateForInstruction (const TTAProgram::Instruction &instructionData, const ExecutableInstruction &executionCounts)
ClockCycleCount busWrites (const std::string &busName) const
ClockCycleCount socketWrites (const std::string &socketName) const
ClockCycleCount triggerCount (const std::string &fuName) const
ClockCycleCount operationExecutions (const std::string &operationName) const
ClockCycleCount operationExecutions (const std::string &fuName, const std::string &operationName) const
ClockCycleCount registerReads (const std::string &rfName, int registerIndex) const
ClockCycleCount guardRegisterReads (const std::string &rfName, int registerIndex) const
ClockCycleCount registerWrites (const std::string &rfName, int registerIndex) const
ClockCycleCount FUGuardAccesses (const std::string &fuName, const std::string &fuPort) const
FUOperationUtilizationIndex FUGuardAccesses () const
int highestUsedRegisterIndex () const
Public Member Functions inherited from SimulationStatisticsCalculator
SimulationStatisticsCalculator ()
virtual ~SimulationStatisticsCalculator ()
Additional Inherited Members
Public Types inherited from UtilizationStats
typedef std::map< std::string, ClockCycleCount > ComponentUtilizationIndex
Index for connecting component names to utilization counts.
typedef std::map< int, std::pair< ClockCycleCount, ClockCycleCount > > RegisterUtilizationIndex
Index for connecting register indices to utilization counts. The first number in the pair is the count of reads, and the second is the count of writes.
typedef std::map< std::string, ComponentUtilizationIndex > FUOperationUtilizationIndex
Index for connecting function unit and operations implemented in them to utilization counts.
typedef std::map< std::string, RegisterUtilizationIndex > RFRegisterUtilizationIndex
Index for connecting register files and register utilization indices in them.
Detailed Description
Calculates processor utilization data for compiled simulations
Definition at line 47 of file CompiledSimUtilizationStats.hh.
Constructor & Destructor Documentation
CompiledSimUtilizationStats()
CompiledSimUtilizationStats::CompiledSimUtilizationStats ()
Default constructor
Definition at line 47 of file CompiledSimUtilizationStats.cc.
{
}
~CompiledSimUtilizationStats()
CompiledSimUtilizationStats::~CompiledSimUtilizationStats () virtual
Default destructor
Definition at line 53 of file CompiledSimUtilizationStats.cc.
{
}
Member Function Documentation
calculate()
void CompiledSimUtilizationStats::calculate (const TTAProgram::Program & program, const CompiledSimulation & compiledSim) virtual
Definition at line 57 of file CompiledSimUtilizationStats.cc.
{
    // Loop all instructions of a program
    const Instruction* instr = &program.firstInstruction();
    int moveNumber = 0;
    while (instr != &NullInstruction::instance()) {
        ExecutableInstruction executableInstr;
        // Add moves and their execution counts
        for (int i = 0; i < instr->moveCount(); ++i, moveNumber++) {
            ClockCycleCount execCount = compiledSim.moveExecutionCount(
                moveNumber, instr->address().location());
            DummyExecutableMove* move = new DummyExecutableMove(execCount);
            executableInstr.addExecutableMove(move);
        }
        // Calculate execution counts so far
        UtilizationStats::calculateForInstruction(*instr, executableInstr);
        instr = &program.nextInstruction(*instr);
    }
}
References ExecutableInstruction::addExecutableMove(), TTAProgram::Instruction::address(), UtilizationStats::calculateForInstruction(), TTAProgram::NullInstruction::instance(), TTAProgram::Address::location(), TTAProgram::Instruction::moveCount(), CompiledSimulation::moveExecutionCount(), and program.
Referenced by SimulatorFrontend::utilizationStatistics().
The documentation for this class was generated from the following files:
CompiledSimUtilizationStats.hh
CompiledSimUtilizationStats.cc