OpenASIP: BFScheduleTD Class Reference
BFScheduleTD Class Reference
#include <BFScheduleTD.hh>
Public Member Functions
BFScheduleTD (BF2Scheduler &sched, MoveNode &mn, int ec, bool allowLateBypass)
virtual bool operator() ()
virtual void undoOnlyMe ()
Public Member Functions inherited from BFScheduleMove
BFScheduleMove (BF2Scheduler &sched, MoveNode &mn)
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
int ec_
bool allowLateBypass_
bool createdCopy_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFScheduleMove
MoveNode & mn_
bool createdPrologMove_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 43 of file BFScheduleTD.hh.
Constructor & Destructor Documentation
BFScheduleTD()
BFScheduleTD::BFScheduleTD (BF2Scheduler & sched, MoveNode & mn, int ec, bool allowLateBypass) inline
Definition at line 46 of file BFScheduleTD.hh.
                          :
    BFScheduleMove(sched, mn), ec_(ec),
    allowLateBypass_(allowLateBypass),
    createdCopy_(false) {}
Member Function Documentation
operator()()
bool BFScheduleTD::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 56 of file BFScheduleTD.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tPerforming BFSchduleTD for: " << mn_.toString() <<
      " ec limit: " << ec_ << std::endl;
#endif
    assert(!mn_.isScheduled());
    if (&mn_.move().bus() != &UniversalMachine::instance().universalBus()) {
        mn_.move().setBus(UniversalMachine::instance().universalBus());
    }
    if (mn_.isDestinationVariable() && allowLateBypass_) {
        BFLateBypasses* lbp = new BFLateBypasses(sched_, mn_, ec_);
        if (runPreChild(lbp)) {
            if (lbp->removedSource()) {
                return true;
            }
        }
    }
    BFRegCopy* regCopyBefore = NULL;
    BFRegCopy* regCopyAfter = NULL;
    if (!canBeScheduled(mn_)) {
        if (/*isRegCopyAfter_ || */ mn_.isSourceOperation()) {
            regCopyAfter = new BFRegCopyAfter(sched_,mn_, INT_MAX);
        } else {
            regCopyBefore = new BFRegCopyBefore(sched_,mn_, INT_MAX);
            if (!runPreChild(regCopyBefore)) {
                return false;
            }
        }
    }
    int ddglc = std::min(sched_.maximumAllowedCycle(),
                         ddg().latestCycle(mn_, ii(), false, false));
    int ddgec = std::max(ec_,
             ddg().earliestCycle(mn_, ii(), false, false));
    int rmec = rmEC(ddgec, mn_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tDDG lc: " << ddglc << std::endl;
    std::cerr << "\t\tDDG ec: " << ddgec << std::endl;
    std::cerr << "\t\tRM ec: " << rmec << std::endl;
#endif
    if (rmec != -1 && ddglc >= rmec) {
        createdCopy_ = assign(rmec, mn_);
        if (regCopyAfter != NULL) {
            if (!runPostChild(regCopyAfter)) {
                undoAndRemovePreChildren();
                return false;
            }
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\tTD Assigned ok:" << mn_.toString()
                  << " bus: " << mn_.move().bus().name() << std::endl;
#endif
        return true;
    } else {
        undoAndRemovePreChildren();
        return false;
    }
}
References allowLateBypass_, assert, BFOptimization::assign(), TTAProgram::Move::bus(), BFOptimization::canBeScheduled(), createdCopy_, BFOptimization::ddg(), ec_, BFOptimization::ii(), UniversalMachine::instance(), MoveNode::isDestinationVariable(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), BF2Scheduler::maximumAllowedCycle(), BFScheduleMove::mn_, MoveNode::move(), TTAMachine::Component::name(), BFLateBypasses::removedSource(), BFOptimization::rmEC(), Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, TTAProgram::Move::setBus(), MoveNode::toString(), Reversible::undoAndRemovePreChildren(), and UniversalMachine::universalBus().
undoOnlyMe()
void BFScheduleTD::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from BFScheduleMove.
Definition at line 119 of file BFScheduleTD.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "unassign td: " << mn_.toString() << std::endl;
#endif
    if (mn_.isScheduled()) {
        unassign(mn_, createdCopy_);
    }
    if (&mn_.move().bus() != &UniversalMachine::instance().universalBus()) {
        mn_.move().setBus(UniversalMachine::instance().universalBus());
    }
}
References TTAProgram::Move::bus(), createdCopy_, UniversalMachine::instance(), MoveNode::isScheduled(), BFScheduleMove::mn_, MoveNode::move(), TTAProgram::Move::setBus(), MoveNode::toString(), BFOptimization::unassign(), and UniversalMachine::universalBus().
Member Data Documentation
allowLateBypass_
bool BFScheduleTD::allowLateBypass_ private
Definition at line 57 of file BFScheduleTD.hh.
Referenced by operator()().
createdCopy_
bool BFScheduleTD::createdCopy_ private
Definition at line 58 of file BFScheduleTD.hh.
Referenced by operator()(), and undoOnlyMe().
ec_
int BFScheduleTD::ec_ private
Definition at line 56 of file BFScheduleTD.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFScheduleTD.hh
BFScheduleTD.cc