OpenASIP: IUDialog Class Reference
IUDialog Class Reference
#include <IUDialog.hh>
Public Member Functions
IUDialog (wxWindow *parent, TTAMachine::ImmediateUnit *immediateUnit)
virtual ~IUDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_WIDTH , ID_SIZE , ID_EXTENSION ,
ID_PORT_LIST , ID_ADD_PORT , ID_EDIT_PORT , ID_DELETE_PORT ,
ID_TEMPLATE_LIST , ID_HELP , ID_LABEL_NAME , ID_LABEL_WIDTH ,
ID_LABEL_SIZE , ID_LINE
}
enumerated IDs for the dialog controls
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
TTAMachine::Port * selectedPort () const
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void onPortSelection (wxListEvent &event)
void onPortRightClick (wxListEvent &event)
void onAddPort (wxCommandEvent &event)
void onActivatePort (wxListEvent &event)
void onEditPort (wxCommandEvent &event)
void onDeletePort (wxCommandEvent &event)
void updatePortList ()
void updateTemplateList ()
void setTexts ()
Private Attributes
wxStaticBoxSizer * portListSizer_
Sizer containing the port list and associated buttons.
wxStaticBoxSizer * templateListSizer_
Sizer containing the template list.
TTAMachine::ImmediateUnit * immediateUnit_
Immediate unit to modify.
wxString name_
Name of the immediate unit.
int size_
Number of registers.
int width_
Width.
int cycles_
Cycles.
wxListCtrl * portList_
Port list control.
wxListCtrl * templateList_
Template list control.
wxRadioBox * extensionBox_
Radio box for extension.
Detailed Description
Dialog for editing immediate unit parameters.
Definition at line 48 of file IUDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for the dialog controls
Enumerator
ID_NAME
ID_WIDTH
ID_SIZE
ID_EXTENSION
ID_PORT_LIST
ID_ADD_PORT
ID_EDIT_PORT
ID_DELETE_PORT
ID_TEMPLATE_LIST
ID_HELP
ID_LABEL_NAME
ID_LABEL_WIDTH
ID_LABEL_SIZE
ID_LINE
Definition at line 98 of file IUDialog.hh.
         {
        ID_NAME = 10000,
        ID_WIDTH,
        ID_SIZE,
        ID_EXTENSION,
        ID_PORT_LIST,
        ID_ADD_PORT,
        ID_EDIT_PORT,
        ID_DELETE_PORT,
        ID_TEMPLATE_LIST,
        ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_WIDTH,
        ID_LABEL_SIZE,
        ID_LINE
    };
Constructor & Destructor Documentation
IUDialog()
IUDialog::IUDialog (wxWindow * parent, TTAMachine::ImmediateUnit * immediateUnit)
The Constructor.
Parameters
parent Parent window of the dialog.
immediateUnit Immediate unit to be modified with the dialog.
Definition at line 81 of file IUDialog.cc.
                                 :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    immediateUnit_(immediateUnit),
    name_(_T("")),
    size_(ModelConstants::DEFAULT_IU_SIZE),
    width_(ModelConstants::DEFAULT_WIDTH),
    cycles_(ModelConstants::DEFAULT_IU_CYCLES),
    portList_(NULL),
    templateList_(NULL),
    extensionBox_(NULL) {
    createContents(this, true, true);
    portList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    templateList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_TEMPLATE_LIST));
    extensionBox_ = dynamic_cast<wxRadioBox*>(FindWindow(ID_EXTENSION));
    FindWindow(ID_SIZE)->SetValidator(wxGenericValidator(&size_));
    FindWindow(ID_WIDTH)->SetValidator(wxGenericValidator(&width_));
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    // set OK button disabled initially
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_DELETE_PORT)->Disable();
    FindWindow(ID_EDIT_PORT)->Disable();
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
~IUDialog()
IUDialog::~IUDialog () virtual
The Destructor.
Definition at line 119 of file IUDialog.cc.
                    {
}
Member Function Documentation
createContents()
wxSizer * IUDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
Code generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 503 of file IUDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 4, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_SIZE, wxT("Size:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item6 = new wxSpinCtrl( parent, ID_SIZE, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item2->Add( item6, 0, wxGROW|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item8 = new wxSpinCtrl( parent, ID_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item2->Add( item8, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, 0, 5 );
    wxString strs11[] =
    {
        wxT("Zero"),
        wxT("Sign")
    };
    wxRadioBox *item11 = new wxRadioBox( parent, ID_EXTENSION, wxT("Extension"), wxDefaultPosition, wxDefaultSize, 2, strs11, 1, wxRA_SPECIFY_COLS );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item13 = new wxStaticBox( parent, -1, wxT("Templates:") );
    wxStaticBoxSizer *item12 = new wxStaticBoxSizer( item13, wxVERTICAL );
    templateListSizer_ = item12;
    wxListCtrl *item14 = new wxListCtrl( parent, ID_TEMPLATE_LIST, wxDefaultPosition, wxSize(200,200), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item12->Add( item14, 0, wxGROW|wxALL, 5 );
    item1->Add( item12, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item16 = new wxStaticBox( parent, -1, wxT("Ports:") );
    wxStaticBoxSizer *item15 = new wxStaticBoxSizer( item16, wxVERTICAL );
    portListSizer_ = item15;
    wxListCtrl *item17 = new wxListCtrl( parent, ID_PORT_LIST, wxDefaultPosition, wxSize(240,150), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item15->Add( item17, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item19 = new wxButton( parent, ID_ADD_PORT, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item20 = new wxButton( parent, ID_EDIT_PORT, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item21 = new wxButton( parent, ID_DELETE_PORT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );
    item15->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item15, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALL, 5 );
    wxStaticLine *item22 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item22, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item23 = new wxGridSizer( 2, 0, 0 );
    wxButton *item24 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALL, 5 );
    wxBoxSizer *item25 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item26 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item27 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );
    item23->Add( item25, 0, wxALL, 5 );
    item0->Add( item23, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_PORT, ID_DELETE_PORT, ID_EDIT_PORT, ID_EXTENSION, ID_HELP, ID_LABEL_NAME, ID_LABEL_SIZE, ID_LABEL_WIDTH, ID_LINE, ID_NAME, ID_PORT_LIST, ID_SIZE, ID_TEMPLATE_LIST, ID_WIDTH, portListSizer_, and templateListSizer_.
onActivatePort()
void IUDialog::onActivatePort (wxListEvent & event) private
Handles left mouse button double click on the port list.
Definition at line 389 of file IUDialog.cc.
{
    wxCommandEvent dummy;
    onEditPort(dummy);
}
References dummy, and onEditPort().
onAddPort()
void IUDialog::onAddPort (wxCommandEvent & event) private
Creates and shows an empty IUPortDialog for adding ports.
Definition at line 351 of file IUDialog.cc.
{
    // Generate name for the new port.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
        Conversion::toString(i);
    while (immediateUnit_->hasPort(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
            Conversion::toString(i);
        i++;
    }
    RFPort* port = new RFPort(newName, *immediateUnit_);
    IUPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_OK) {
        updatePortList();
    } else {
        delete port;
    }
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_PORT, TTAMachine::Unit::hasPort(), immediateUnit_, Conversion::toString(), and updatePortList().
onDeletePort()
void IUDialog::onDeletePort (wxCommandEvent & event) private
Deletes selected port from the port list.
Definition at line 377 of file IUDialog.cc.
{
    Port* selected = selectedPort();
    assert(selected != NULL);
    delete selected;
    updatePortList();
}
References assert, selectedPort(), and updatePortList().
onEditPort()
void IUDialog::onEditPort (wxCommandEvent & event) private
Handles the 'Edit Port' button event.
Opens a IUPortDialog with the selected port's attributes set.
Definition at line 401 of file IUDialog.cc.
{
    Port* port = selectedPort();
    if (port == NULL) {
        // No port selected.
        return;
    }
    IUPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_OK) {
        updatePortList();
    }
}
References selectedPort(), and updatePortList().
Referenced by onActivatePort().
onHelp()
void IUDialog::onHelp (wxCommandEvent & event) private
onName()
void IUDialog::onName (wxCommandEvent & event) private
Checks whether name field is empty and disables OK button of the dialog if it is.
Definition at line 310 of file IUDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void IUDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the ImmediateUnit.
Definition at line 235 of file IUDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (trimmedName != immediateUnit_->name()) {
        Machine::ImmediateUnitNavigator navigator =
            immediateUnit_->machine()->immediateUnitNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            ImmediateUnit* iu = navigator.item(i);
            if (trimmedName == iu->name()) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format an_iu = prodeTexts->text(
                    ProDeTextGenerator::COMP_AN_IMMEDIATE_UNIT);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format iu =
                    prodeTexts->text(ProDeTextGenerator::COMP_IMMEDIATE_UNIT);
                message % trimmedName % an_iu.str() % machine.str() % iu.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    // set IU attributes
    immediateUnit_->setName(trimmedName);
    immediateUnit_->setNumberOfRegisters(size_);
    immediateUnit_->setWidth(width_);
    wxString extension = extensionBox_->GetStringSelection();
    // set IU extension
    if (extension.IsSameAs(ProDeConstants::EXTENSION_ZERO)) {
        immediateUnit_->setExtensionMode(Machine::ZERO);
    } else if (extension.IsSameAs(ProDeConstants::EXTENSION_SIGN)) {
        immediateUnit_->setExtensionMode(Machine::SIGN);
    } else {
        assert(false);
    }
    EndModal(wxID_OK);
}
References assert, ProDeTextGenerator::COMP_AN_IMMEDIATE_UNIT, ProDeTextGenerator::COMP_IMMEDIATE_UNIT, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::count(), ProDeConstants::EXTENSION_SIGN, ProDeConstants::EXTENSION_ZERO, extensionBox_, immediateUnit_, TTAMachine::Machine::immediateUnitNavigator(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::ImmediateUnit::setExtensionMode(), TTAMachine::ImmediateUnit::setName(), TTAMachine::RegisterFile::setNumberOfRegisters(), TTAMachine::BaseRegisterFile::setWidth(), TTAMachine::Machine::SIGN, size_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), width_, and TTAMachine::Machine::ZERO.
onPortRightClick()
void IUDialog::onPortRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed.
Parameters
event Information about right mouse click event.
Definition at line 441 of file IUDialog.cc.
{
    portList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    contextMenu->Append(ID_EDIT_PORT, _T("&Edit..."));
    contextMenu->Append(ID_DELETE_PORT, _T("&Delete"));
    portList_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_PORT, ID_EDIT_PORT, and portList_.
onPortSelection()
void IUDialog::onPortSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the port list.
If a port is selected, buttons are enabled. If no port is selected the buttons will be disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 424 of file IUDialog.cc.
{
    if (portList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_PORT)->Disable();
        FindWindow(ID_EDIT_PORT)->Disable();
        return;
    }
    FindWindow(ID_DELETE_PORT)->Enable();
    FindWindow(ID_EDIT_PORT)->Enable();
}
References ID_DELETE_PORT, ID_EDIT_PORT, and portList_.
selectedPort()
Port * IUDialog::selectedPort () const private
Returns pointer to the port which is selected on the port list.
Returns
Pointer to the port which is selected on the port list.
Definition at line 329 of file IUDialog.cc.
{
    long item = -1;
    item = portList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    string portName =
        WxConversion::toString(portList_->GetItemText(item));
    return immediateUnit_->port(portName);
}
References immediateUnit_, TTAMachine::BaseRegisterFile::port(), portList_, and WxConversion::toString().
Referenced by onDeletePort(), and onEditPort().
setTexts()
void IUDialog::setTexts () private
Sets texts for widgets.
Definition at line 127 of file IUDialog.cc.
                   {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_IU_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_PORT),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_PORT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_PORT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_SIZE),
                          ProDeTextGenerator::TXT_LABEL_SIZE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_EXTENSION),
                          ProDeTextGenerator::TXT_LABEL_EXTENSION);
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_IU_PORTS_BOX);
    WidgetTools::setWidgetLabel(portListSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_IU_TEMPLATES_BOX);
    WidgetTools::setWidgetLabel(templateListSizer_, fmt.str());
    // Radio button labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO);
    extensionBox_->SetString(0, WxConversion::toWxString(fmt.str()));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN);
    extensionBox_->SetString(1, WxConversion::toWxString(fmt.str()));
    // Create list columns.
    wxListCtrl* portList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    portList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 240);
    wxListCtrl* templateList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_TEMPLATE_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    templateList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 240);
}
References extensionBox_, ID_ADD_PORT, ID_DELETE_PORT, ID_EDIT_PORT, ID_EXTENSION, ID_HELP, ID_LABEL_NAME, ID_LABEL_SIZE, ID_LABEL_WIDTH, ID_PORT_LIST, ID_TEMPLATE_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), portListSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), templateListSizer_, Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_IU_DIALOG_TITLE, ProDeTextGenerator::TXT_IU_PORTS_BOX, ProDeTextGenerator::TXT_IU_TEMPLATES_BOX, ProDeTextGenerator::TXT_LABEL_EXTENSION, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_SIZE, ProDeTextGenerator::TXT_LABEL_WIDTH, ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN, and ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO.
TransferDataToWindow()
bool IUDialog::TransferDataToWindow () private virtual
Transfers data from the ImmediateUnit object to the dialog widgets.
Returns
false, if an error occured in the transfer.
Definition at line 201 of file IUDialog.cc.
{
    name_ = WxConversion::toWxString(immediateUnit_->name());
    width_ = immediateUnit_->width();
    size_ = immediateUnit_->numberOfRegisters();
    cycles_ = immediateUnit_->latency();
    // transfer extension
    if (immediateUnit_->extensionMode() == Machine::ZERO) {
        wxString zero = ProDeConstants::EXTENSION_ZERO;
        extensionBox_->SetStringSelection(zero);
    } else if (immediateUnit_->extensionMode() == Machine::SIGN) {
        wxString sign = ProDeConstants::EXTENSION_SIGN;
        extensionBox_->SetStringSelection(sign);
    } else {
        assert(false);
    }
    updatePortList();
    updateTemplateList();
    // wxWidgets GTK1 version seems to bug with spincontrol validators.
    // The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_WIDTH))->SetValue(width_);
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_SIZE))->SetValue(size_);
    return wxWindow::TransferDataToWindow();
}
References assert, cycles_, ProDeConstants::EXTENSION_SIGN, ProDeConstants::EXTENSION_ZERO, extensionBox_, TTAMachine::ImmediateUnit::extensionMode(), ID_SIZE, ID_WIDTH, immediateUnit_, TTAMachine::ImmediateUnit::latency(), TTAMachine::Component::name(), name_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Machine::SIGN, size_, WxConversion::toWxString(), updatePortList(), updateTemplateList(), TTAMachine::BaseRegisterFile::width(), width_, and TTAMachine::Machine::ZERO.
updatePortList()
void IUDialog::updatePortList () private
Updates 'Ports' list control.
Clears all items from the choicer and adds all ports.
Definition at line 459 of file IUDialog.cc.
{
    portList_->DeleteAllItems();
    for (int i=0; i < immediateUnit_->portCount(); i++) {
        wxString portName =
            WxConversion::toWxString(immediateUnit_->port(i)->name());
        portList_->InsertItem(i, portName);
    }
}
References immediateUnit_, TTAMachine::Port::name(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), portList_, and WxConversion::toWxString().
Referenced by onAddPort(), onDeletePort(), onEditPort(), and TransferDataToWindow().
updateTemplateList()
void IUDialog::updateTemplateList () private
Updates 'Templates' list control.
Definition at line 475 of file IUDialog.cc.
{
    templateList_->DeleteAllItems();
    Machine::InstructionTemplateNavigator navigator =
        immediateUnit_->machine()->instructionTemplateNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        if (navigator.item(i)->isOneOfDestinations(*immediateUnit_)) {
            wxString name =
                WxConversion::toWxString(navigator.item(i)->name());
            templateList_->InsertItem(0, name);
        }
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), immediateUnit_, TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), templateList_, and WxConversion::toWxString().
Referenced by TransferDataToWindow().
Member Data Documentation
cycles_
int IUDialog::cycles_ private
Cycles.
Definition at line 88 of file IUDialog.hh.
Referenced by TransferDataToWindow().
extensionBox_
wxRadioBox* IUDialog::extensionBox_ private
Radio box for extension.
Definition at line 95 of file IUDialog.hh.
Referenced by onOK(), setTexts(), and TransferDataToWindow().
immediateUnit_
TTAMachine::ImmediateUnit* IUDialog::immediateUnit_ private
Immediate unit to modify.
Definition at line 80 of file IUDialog.hh.
Referenced by onAddPort(), onOK(), selectedPort(), TransferDataToWindow(), updatePortList(), and updateTemplateList().
name_
wxString IUDialog::name_ private
Name of the immediate unit.
Definition at line 82 of file IUDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
portList_
wxListCtrl* IUDialog::portList_ private
Port list control.
Definition at line 91 of file IUDialog.hh.
Referenced by onPortRightClick(), onPortSelection(), selectedPort(), and updatePortList().
portListSizer_
wxStaticBoxSizer* IUDialog::portListSizer_ private
Sizer containing the port list and associated buttons.
Definition at line 75 of file IUDialog.hh.
Referenced by createContents(), and setTexts().
size_
int IUDialog::size_ private
Number of registers.
Definition at line 84 of file IUDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
templateList_
wxListCtrl* IUDialog::templateList_ private
Template list control.
Definition at line 93 of file IUDialog.hh.
Referenced by updateTemplateList().
templateListSizer_
wxStaticBoxSizer* IUDialog::templateListSizer_ private
Sizer containing the template list.
Definition at line 77 of file IUDialog.hh.
Referenced by createContents(), and setTexts().
width_
int IUDialog::width_ private
Width.
Definition at line 86 of file IUDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
IUDialog.hh
IUDialog.cc