OpenASIP: GCUFactory Class Reference
GCUFactory Class Reference
#include <GCUFactory.hh>
Public Member Functions
GCUFactory (EditPolicyFactory &editPolicyFactory)
virtual ~GCUFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
GCUFactory & operator= (GCUFactory &old)
Assignment not allowed.
GCUFactory (GCUFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating global control unit EditParts corresponding to a given Machine GlobalControlUnit object.
Definition at line 45 of file GCUFactory.hh.
Constructor & Destructor Documentation
GCUFactory() [1/2]
GCUFactory::GCUFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 54 of file GCUFactory.cc.
                                                          :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new UnitPortFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~GCUFactory()
GCUFactory::~GCUFactory () virtual
The Destructor.
Definition at line 62 of file GCUFactory.cc.
{
}
GCUFactory() [2/2]
GCUFactory::GCUFactory (GCUFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * GCUFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a global control unit.
Parameters
component Global control unit of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the ControlUnit class.
Implements Factory.
Definition at line 73 of file GCUFactory.cc.
{
    ControlUnit* gcu = dynamic_cast<ControlUnit*>(component);
    if (gcu != NULL) {
    EditPart* gcuEditPart = new EditPart();
    gcuEditPart->setModel(gcu);
    UnitFigure* fig = new UnitFigure();
    wxString name = WxConversion::toWxString(gcu->name());
    name.Prepend(_T("GCU: "));
    fig->setName(name);
    gcuEditPart->setFigure(fig);
        // Create editparts of operation ports.
    for (int i = 0; i < gcu->operationPortCount(); i++) {
        vector<Factory*>::const_iterator iter;
        for (iter = factories_.begin(); iter != factories_.end(); iter++) {
        EditPart* portEditPart =
            (*iter)->createEditPart(gcu->operationPort(i));
        if (portEditPart != NULL) {
                    EditPolicy* portEditPolicy =
                        editPolicyFactory_.createFUPortEditPolicy();
                    if (portEditPolicy != NULL) {
                        portEditPart->installEditPolicy(portEditPolicy);
                    }
                    gcuEditPart->addChild(portEditPart);
        }
        }
    }
        // Create editparts of special register ports.
    for (int i = 0; i < gcu->specialRegisterPortCount(); i++) {
        vector<Factory*>::const_iterator iter;
        for (iter = factories_.begin(); iter != factories_.end(); iter++) {
        EditPart* portEditPart =
            (*iter)->createEditPart(gcu->specialRegisterPort(i));
        if (portEditPart != NULL) {
                    EditPolicy* portEditPolicy =
                        editPolicyFactory_.createSRPortEditPolicy();
                    if (portEditPolicy != NULL) {
                        portEditPart->installEditPolicy(portEditPolicy);
                    }
            gcuEditPart->addChild(portEditPart);
        }
        }
    }
        wxString operations = _T("{ ");
    for (int i = 0; i < gcu->operationCount(); i++) {
            if (i > 0) {
                operations.Append(_T(", "));
            }
            operations.Append(
                WxConversion::toWxString(gcu->operation(i)->name()));
        }
        operations.Append(_T(" }"));
        fig->setInfo(operations);
    gcuEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createGCUEditPolicy();
    if (editPolicy != NULL) {
        gcuEditPart->installEditPolicy(editPolicy);
    }
    return gcuEditPart;
    } else {
    return NULL;
    }
}
References EditPart::addChild(), EditPolicyFactory::createFUPortEditPolicy(), EditPolicyFactory::createGCUEditPolicy(), EditPolicyFactory::createSRPortEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), EditPart::setFigure(), UnitFigure::setInfo(), EditPart::setModel(), UnitFigure::setName(), EditPart::setSelectable(), TTAMachine::ControlUnit::specialRegisterPort(), TTAMachine::ControlUnit::specialRegisterPortCount(), and WxConversion::toWxString().
operator=()
GCUFactory & GCUFactory::operator= (GCUFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
GCUFactory.hh
GCUFactory.cc