OpenASIP: FUDialog Class Reference
FUDialog Class Reference
#include <FUDialog.hh>
Public Member Functions
FUDialog (wxWindow *parent, TTAMachine::FunctionUnit *functionUnit)
virtual ~FUDialog ()
Protected Member Functions
virtual bool TransferDataToWindow ()
Private Types
enum {
ID_NAME =10000 , ID_ADDRESS_SPACE , ID_OPERATION_LIST , ID_ADD_OPERATION ,
ID_EDIT_OPERATION , ID_ADD_OPERATION_FROM_OPSET , ID_DELETE_OPERATION , ID_PORT_LIST ,
ID_ADD_PORT , ID_EDIT_PORT , ID_DELETE_PORT , ID_HELP ,
ID_LABEL_NAME , ID_LABEL_AS
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
TTAMachine::FUPort * selectedPort ()
TTAMachine::HWOperation * selectedOperation ()
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void onPortSelection (wxListEvent &event)
void onPortRightClick (wxListEvent &event)
void onAddPort (wxCommandEvent &event)
void onDeletePort (wxCommandEvent &event)
void onEditPort (wxCommandEvent &event)
void onActivatePort (wxListEvent &event)
void onOperationSelection (wxListEvent &event)
void onAddOperation (wxCommandEvent &event)
void onAddOperationFromOpset (wxCommandEvent &event)
void onDeleteOperation (wxCommandEvent &event)
void onEditOperation (wxCommandEvent &event)
void onSetAddressSpace (wxCommandEvent &event)
void onActivateOperation (wxListEvent &event)
void onOperationRightClick (wxListEvent &event)
void updateAddressSpaceChoice ()
void updatePortList ()
void updateOperationList ()
void setTexts ()
Private Attributes
TTAMachine::FunctionUnit * functionUnit_
FunctionUnit to modify.
wxString name_
Name of the function unit.
wxListCtrl * portListCtrl_
Port list control.
wxListCtrl * operationListCtrl_
Operation list control.
wxChoice * addressSpaceChoice_
Address Space choice control.
wxStaticBoxSizer * portsSizer_
Sizer for the port list controls.
wxStaticBoxSizer * operationsSizer_
Sizer for the operation list controls.
Detailed Description
Dialog for querying FunctionUnit parameters from the user.
Definition at line 48 of file FUDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NAME
ID_ADDRESS_SPACE
ID_OPERATION_LIST
ID_ADD_OPERATION
ID_EDIT_OPERATION
ID_ADD_OPERATION_FROM_OPSET
ID_DELETE_OPERATION
ID_PORT_LIST
ID_ADD_PORT
ID_EDIT_PORT
ID_DELETE_PORT
ID_HELP
ID_LABEL_NAME
ID_LABEL_AS
Definition at line 99 of file FUDialog.hh.
         {
    ID_NAME=10000,
    ID_ADDRESS_SPACE,
    ID_OPERATION_LIST,
    ID_ADD_OPERATION,
    ID_EDIT_OPERATION,
        ID_ADD_OPERATION_FROM_OPSET,
    ID_DELETE_OPERATION,
        ID_PORT_LIST,
    ID_ADD_PORT,
    ID_EDIT_PORT,
    ID_DELETE_PORT,
    ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_AS
    };
Constructor & Destructor Documentation
FUDialog()
FUDialog::FUDialog (wxWindow * parent, TTAMachine::FunctionUnit * functionUnit)
The Constructor.
Parameters
parent Parent window of the dialog.
functionUnit A function unit to be shown in the dialog.
Definition at line 109 of file FUDialog.cc.
                               :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    functionUnit_(functionUnit),
    name_(_T("")),
    portListCtrl_(NULL),
    operationListCtrl_(NULL),
    addressSpaceChoice_(NULL) {
    createContents(this, true, true);
    portListCtrl_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    operationListCtrl_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    addressSpaceChoice_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_ADDRESS_SPACE));
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(wxID_OK)->Disable();
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
~FUDialog()
FUDialog::~FUDialog () virtual
The Destructor.
Definition at line 141 of file FUDialog.cc.
                    {
}
Member Function Documentation
createContents()
wxSizer * FUDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was initially generated with wxDesigner, code will be cleaned up later.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 747 of file FUDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 2, 0, 10 );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(150,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_AS, wxT("Address Space:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs6 = (wxString*) NULL;
    wxChoice *item6 = new wxChoice( parent, ID_ADDRESS_SPACE, wxDefaultPosition, wxSize(150,-1), 0, strs6, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxStaticBox *item8 = new wxStaticBox( parent, -1, wxT("Operations:") );
    wxStaticBoxSizer *item7 = new wxStaticBoxSizer( item8, wxVERTICAL );
    operationsSizer_ = item7;
    wxListCtrl *item9 = new wxListCtrl( parent, ID_OPERATION_LIST, wxDefaultPosition, wxSize(160,200), wxLC_REPORT|wxSUNKEN_BORDER );
    item7->Add( item9, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item11 = new wxButton( parent, ID_ADD_OPERATION, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item12 = new wxButton( parent, ID_EDIT_OPERATION, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item13 = new wxButton( parent, ID_DELETE_OPERATION, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    item7->Add( item10, 0, wxALIGN_CENTER, 5 );
    wxButton *item14 = new wxButton( parent, ID_ADD_OPERATION_FROM_OPSET, wxT(" Add from  Opset... "), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item14, 0, wxALL, 5 );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item16 = new wxStaticBox( parent, -1, wxT("Ports:") );
    wxStaticBoxSizer *item15 = new wxStaticBoxSizer( item16, wxVERTICAL );
    portsSizer_ = item15;
    wxListCtrl *item17 = new wxListCtrl( parent, ID_PORT_LIST, wxDefaultPosition, wxSize(160,200), wxLC_REPORT|wxSUNKEN_BORDER );
    item15->Add( item17, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item19 = new wxButton( parent, ID_ADD_PORT, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item20 = new wxButton( parent, ID_EDIT_PORT, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item21 = new wxButton( parent, ID_DELETE_PORT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );
    item15->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item15, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item25 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item26 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item25, 0, wxALL, 5 );
    wxBoxSizer *item27 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item28 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item29 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item27, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_OPERATION, ID_ADD_OPERATION_FROM_OPSET, ID_ADD_PORT, ID_ADDRESS_SPACE, ID_DELETE_OPERATION, ID_DELETE_PORT, ID_EDIT_OPERATION, ID_EDIT_PORT, ID_HELP, ID_LABEL_AS, ID_LABEL_NAME, ID_NAME, ID_OPERATION_LIST, ID_PORT_LIST, operationsSizer_, and portsSizer_.
onActivateOperation()
void FUDialog::onActivateOperation (wxListEvent & event) private
Handles left mouse button double clicks on the operation list.
Definition at line 729 of file FUDialog.cc.
{
    wxCommandEvent dummy;
    onEditOperation(dummy);
}
References dummy, and onEditOperation().
onActivatePort()
void FUDialog::onActivatePort (wxListEvent & event) private
Handles left mouse button double clicks on the port list.
Definition at line 380 of file FUDialog.cc.
{
    wxCommandEvent dummy;
    onEditPort(dummy);
}
References dummy, and onEditPort().
onAddOperation()
void FUDialog::onAddOperation (wxCommandEvent & event) private
Creates and shows an empty Function Unit Operation Dialog for adding operations.
Not Implemented.
Definition at line 430 of file FUDialog.cc.
{
    ObjectState* fu = functionUnit_->saveState();
    // Generate name for the new operation.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION +
        Conversion::toString(i);
    while (functionUnit_->hasOperation(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION +
            Conversion::toString(i);
        i++;
    }
    HWOperation* operation = NULL;
    operation = new HWOperation(newName, *functionUnit_);
    OperationDialog dialog(this, operation);
    if (dialog.ShowModal() == wxID_OK) {
        delete fu;
    } else {
        functionUnit_->loadState(fu);
    }
    updateOperationList();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION, functionUnit_, TTAMachine::FunctionUnit::hasOperation(), TTAMachine::FunctionUnit::loadState(), TTAMachine::FunctionUnit::saveState(), Conversion::toString(), and updateOperationList().
onAddOperationFromOpset()
void FUDialog::onAddOperationFromOpset (wxCommandEvent & event) private
Event handler for the add operation from opset button.
Definition at line 458 of file FUDialog.cc.
{
    try {
        OpsetDialog opsetDialog(this);
        if (opsetDialog.ShowModal() != wxID_OK) {
            return;
        }
        HWOperation* operation = opsetDialog.createOperation(*functionUnit_);
        if (operation == NULL) {
            return;
        }
        OperationDialog operationDialog(this, operation);
        if (operationDialog.ShowModal() != wxID_OK) {
            delete operation;
        }
        updateOperationList();
    } catch (Exception & e) {
        wxString message = WxConversion::toWxString(e.errorMessage());
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
}
References OpsetDialog::createOperation(), Exception::errorMessage(), functionUnit_, WxConversion::toWxString(), and updateOperationList().
onAddPort()
void FUDialog::onAddPort (wxCommandEvent & event) private
Creates and shows an empty Function Unit Port Dialog for adding ports.
Definition at line 321 of file FUDialog.cc.
{
    // Generate name for the new port.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
        Conversion::toString(i);
    while (functionUnit_->hasPort(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
            Conversion::toString(i);
        i++;
    }
    FUPort* port = new FUPort(
        newName, ModelConstants::DEFAULT_WIDTH, *functionUnit_, false, false);
    FUPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_CANCEL) {
        // adding port was cancelled
        delete port;
    }
    updatePortList();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_PORT, ModelConstants::DEFAULT_WIDTH, functionUnit_, TTAMachine::Unit::hasPort(), Conversion::toString(), and updatePortList().
onDeleteOperation()
void FUDialog::onDeleteOperation (wxCommandEvent & event) private
Deletes selected operation from the operation list.
Definition at line 490 of file FUDialog.cc.
{
    string name = WidgetTools::lcStringSelection(operationListCtrl_, 0);
    if (name == "") {
        return;
    }
    delete functionUnit_->operation(name);
    updateOperationList();
}
References functionUnit_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::operation(), operationListCtrl_, and updateOperationList().
onDeletePort()
void FUDialog::onDeletePort (wxCommandEvent & event) private
Deletes selected port from the port list.
Definition at line 349 of file FUDialog.cc.
{
    FUPort* selected = selectedPort();
    if (selected == NULL) {
        return;
    }
    assert(selected != NULL);
    delete selected;
    updatePortList();
}
References assert, selectedPort(), and updatePortList().
onEditOperation()
void FUDialog::onEditOperation (wxCommandEvent & event) private
Handles the 'Edit Operation' button event.
Opens a FUOperationDialog with the selected operation's attributes set.
Definition at line 507 of file FUDialog.cc.
{
    HWOperation* selected = selectedOperation();
    if (selected == NULL) {
        // No operation selected.
        return;
    }
    ObjectState* fu = functionUnit_->saveState();
    OperationDialog dialog(this, selected);
    if (dialog.ShowModal() == wxID_OK) {
        delete fu;
    } else {
        functionUnit_->loadState(fu);
    }
    updateOperationList();
}
References functionUnit_, TTAMachine::FunctionUnit::loadState(), TTAMachine::FunctionUnit::saveState(), selectedOperation(), and updateOperationList().
Referenced by onActivateOperation().
onEditPort()
void FUDialog::onEditPort (wxCommandEvent & event) private
Handles the 'Edit Port' button event.
Opens a FUPortDialog with the selected port set.
Definition at line 392 of file FUDialog.cc.
{
    FUPort* port = selectedPort();
    if (port == NULL) {
        return;
    }
    FUPortDialog portDialog(this, port);
    portDialog.ShowModal();
    updatePortList();
}
References selectedPort(), and updatePortList().
Referenced by onActivatePort().
onHelp()
void FUDialog::onHelp (wxCommandEvent & event) private
onName()
void FUDialog::onName (wxCommandEvent & event) private
Checks whether name field is empty and disables OK button of the dialog if it is.
Definition at line 531 of file FUDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void FUDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the FunctionUnit.
Definition at line 243 of file FUDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (trimmedName != functionUnit_->name()) {
        Machine::FunctionUnitNavigator navigator =
            functionUnit_->machine()->functionUnitNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            FunctionUnit* fu = navigator.item(i);
            if (trimmedName == fu->name()) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_fu =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_FUNCTION_UNIT);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format fu =
                    prodeTexts->text(ProDeTextGenerator::COMP_FUNCTION_UNIT);
                message % trimmedName % a_fu.str() % machine.str() % fu.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    functionUnit_->setName(trimmedName);
    EndModal(wxID_OK);
}
References ProDeTextGenerator::COMP_A_FUNCTION_UNIT, ProDeTextGenerator::COMP_FUNCTION_UNIT, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::count(), functionUnit_, TTAMachine::Machine::functionUnitNavigator(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::FunctionUnit::setName(), Texts::TextGenerator::text(), WxConversion::toString(), and WxConversion::toWxString().
onOperationRightClick()
void FUDialog::onOperationRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed on the operation list.
Parameters
event Information about right mouse click event.
Definition at line 705 of file FUDialog.cc.
{
    operationListCtrl_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_OPERATION, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_OPERATION, WxConversion::toWxString(button.str()));
    operationListCtrl_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_OPERATION, ID_EDIT_OPERATION, ProDeTextGenerator::instance(), operationListCtrl_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onOperationSelection()
void FUDialog::onOperationSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the operation list.
If a operation is selected, buttons are enabled. If no operation is selected the buttons will be disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 568 of file FUDialog.cc.
{
    if (operationListCtrl_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_OPERATION)->Disable();
        FindWindow(ID_EDIT_OPERATION)->Disable();
        return;
    }
    FindWindow(ID_DELETE_OPERATION)->Enable();
    FindWindow(ID_EDIT_OPERATION)->Enable();
}
References ID_DELETE_OPERATION, ID_EDIT_OPERATION, and operationListCtrl_.
Referenced by updateOperationList().
onPortRightClick()
void FUDialog::onPortRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed.
Parameters
event Information about right mouse click event.
Definition at line 678 of file FUDialog.cc.
{
    portListCtrl_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_PORT, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_PORT, WxConversion::toWxString(button.str()));
    portListCtrl_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_PORT, ID_EDIT_PORT, ProDeTextGenerator::instance(), portListCtrl_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onPortSelection()
void FUDialog::onPortSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the port list.
If a port is selected, buttons are enabled. If no port is selected the buttons will be disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 412 of file FUDialog.cc.
{
    if (portListCtrl_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_PORT)->Disable();
        FindWindow(ID_EDIT_PORT)->Disable();
        return;
    }
    FindWindow(ID_DELETE_PORT)->Enable();
    FindWindow(ID_EDIT_PORT)->Enable();
}
References ID_DELETE_PORT, ID_EDIT_PORT, and portListCtrl_.
Referenced by updatePortList().
onSetAddressSpace()
void FUDialog::onSetAddressSpace (wxCommandEvent & event) private
Sets the function unit address space when user changes it.
Definition at line 299 of file FUDialog.cc.
{
    string asName =
        WxConversion::toString(addressSpaceChoice_->GetStringSelection());
    if (asName == WxConversion::toString(ProDeConstants::NONE)) {
        functionUnit_->setAddressSpace(NULL);
    } else {
        Machine::AddressSpaceNavigator navigator =
            functionUnit_->machine()->addressSpaceNavigator();
        AddressSpace* as = navigator.item(asName);
        functionUnit_->setAddressSpace(as);
    }
}
References addressSpaceChoice_, TTAMachine::Machine::addressSpaceNavigator(), functionUnit_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeConstants::NONE, TTAMachine::FunctionUnit::setAddressSpace(), and WxConversion::toString().
selectedOperation()
HWOperation * FUDialog::selectedOperation () private
Returns pointer to the operation, which is selected on the operation list.
Returns
Pointer to the selected operation.
Definition at line 550 of file FUDialog.cc.
{
    string name = WidgetTools::lcStringSelection(operationListCtrl_, 0);
    if (name == "") {
        return NULL;
    }
    return functionUnit_->operation(name);
}
References functionUnit_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::operation(), and operationListCtrl_.
Referenced by onEditOperation().
selectedPort()
FUPort * FUDialog::selectedPort () private
Returns a pointer to the function unit port which is selected.
Returns
Pointer to the port selected in the port list.
Definition at line 366 of file FUDialog.cc.
                       {
    string name = WidgetTools::lcStringSelection(portListCtrl_, 1);
    if (name == "") {
        return NULL;
    }
    FUPort* port = functionUnit_->operationPort(name);
    return port;
}
References functionUnit_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::operationPort(), and portListCtrl_.
Referenced by onDeletePort(), and onEditPort().
setTexts()
void FUDialog::setTexts () private
Sets texts for widgets.
Definition at line 149 of file FUDialog.cc.
                   {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_FU_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_PORT),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_PORT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_PORT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_OPERATION),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_OPERATION),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_OPERATION),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_AS),
                          ProDeTextGenerator::TXT_LABEL_ADDRESS_SPACE);
    // box sizer labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_FU_PORTS_BOX);
    WidgetTools::setWidgetLabel(portsSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_FU_OPERATIONS_BOX);
    WidgetTools::setWidgetLabel(operationsSizer_, fmt.str());
    // Create port list columns.
    wxListCtrl* portList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_TRIGGERS);
    portList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_CENTER, 30);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    portList->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 110);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_WIDTH);
    portList->InsertColumn(2, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 110);
    // Create operation list column.
    wxListCtrl* operationList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    operationList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                                wxLIST_FORMAT_LEFT, 250);
    Layout();
}
References ID_ADD_OPERATION, ID_ADD_PORT, ID_DELETE_OPERATION, ID_DELETE_PORT, ID_EDIT_OPERATION, ID_EDIT_PORT, ID_HELP, ID_LABEL_AS, ID_LABEL_NAME, ID_OPERATION_LIST, ID_PORT_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), operationsSizer_, portsSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_TRIGGERS, ProDeTextGenerator::TXT_COLUMN_WIDTH, ProDeTextGenerator::TXT_FU_DIALOG_TITLE, ProDeTextGenerator::TXT_FU_OPERATIONS_BOX, ProDeTextGenerator::TXT_FU_PORTS_BOX, ProDeTextGenerator::TXT_LABEL_ADDRESS_SPACE, and ProDeTextGenerator::TXT_LABEL_NAME.
TransferDataToWindow()
bool FUDialog::TransferDataToWindow () protected virtual
Transfers data from the MOM to the dialog widgets.
Returns
False, if an error occured in the transfer, true otherwise.
Definition at line 228 of file FUDialog.cc.
{
    name_ = WxConversion::toWxString(functionUnit_->name());
    updatePortList();
    updateOperationList();
    updateAddressSpaceChoice();
    return wxWindow::TransferDataToWindow();
}
References functionUnit_, TTAMachine::Component::name(), name_, WxConversion::toWxString(), updateAddressSpaceChoice(), updateOperationList(), and updatePortList().
updateAddressSpaceChoice()
void FUDialog::updateAddressSpaceChoice () private
Updates 'Address Space' choice control.
Clears all items from the choicer and adds all address spaces plus an item 'NONE' indicating empty selection.
Definition at line 586 of file FUDialog.cc.
{
    addressSpaceChoice_->Clear();
    addressSpaceChoice_->Append(ProDeConstants::NONE);
    Machine::AddressSpaceNavigator navigator =
        functionUnit_->machine()->addressSpaceNavigator();
    // put each address space of the Machine to the control.
    for (int i = 0; i < navigator.count(); i++) {
        AddressSpace* as = navigator.item(i);
        wxString name = WxConversion::toWxString(as->name());
        addressSpaceChoice_->Append(name);
    }
    // set address space selection
    AddressSpace* as = functionUnit_->addressSpace();
    if (as != NULL) {
        wxString name = WxConversion::toWxString(as->name());
        addressSpaceChoice_->SetStringSelection(name);
    } else {
        addressSpaceChoice_->SetStringSelection(ProDeConstants::NONE);
    }
}
References TTAMachine::FunctionUnit::addressSpace(), addressSpaceChoice_, TTAMachine::Machine::addressSpaceNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), functionUnit_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ProDeConstants::NONE, and WxConversion::toWxString().
Referenced by TransferDataToWindow().
updateOperationList()
void FUDialog::updateOperationList () private
Updates operation list.
Definition at line 650 of file FUDialog.cc.
{
    operationListCtrl_->DeleteAllItems();
    // Operation names are put in a set, which will sort the operation
    // names automatically.
    std::set<std::string> operations;
    for (int i=0; i < functionUnit_->operationCount(); i++) {
        operations.insert(functionUnit_->operation(i)->name());
    }
    std::set<std::string>::reverse_iterator iter = operations.rbegin();
    for (; iter != operations.rend(); iter++) {
        wxString name = WxConversion::toWxString(*iter);
        operationListCtrl_->InsertItem(0, name);
    }
    wxListEvent dummy;
    onOperationSelection(dummy);
}
References dummy, functionUnit_, TTAMachine::HWOperation::name(), onOperationSelection(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), operationListCtrl_, and WxConversion::toWxString().
Referenced by onAddOperation(), onAddOperationFromOpset(), onDeleteOperation(), onEditOperation(), and TransferDataToWindow().
updatePortList()
void FUDialog::updatePortList () private
Updates 'Ports' list control.
Clears all items from the choicer and adds all ports.
Definition at line 618 of file FUDialog.cc.
{
    portListCtrl_->DeleteAllItems();
    for (int i = 0; i < functionUnit_->portCount(); i++) {
        FUPort* port = functionUnit_->operationPort(i);
        bool triggers = port->isTriggering();
        string width = Conversion::toString(port->width());
        string name = port->name();
        // set asterisk symbol in the "T" column if port triggers
        if (!triggers) {
            portListCtrl_->InsertItem(i, _T(""), 0);
        } else {
            portListCtrl_->InsertItem(i, _T("*"), 0);
        }
        portListCtrl_->SetItem(i, 1, WxConversion::toWxString(name));
        portListCtrl_->SetItem(i, 2, WxConversion::toWxString(width));
    }
    wxListEvent dummy;
    onPortSelection(dummy);
}
References dummy, functionUnit_, TTAMachine::FUPort::isTriggering(), TTAMachine::Port::name(), onPortSelection(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::Unit::portCount(), portListCtrl_, Conversion::toString(), WxConversion::toWxString(), and TTAMachine::BaseFUPort::width().
Referenced by onAddPort(), onDeletePort(), onEditPort(), and TransferDataToWindow().
Member Data Documentation
addressSpaceChoice_
wxChoice* FUDialog::addressSpaceChoice_ private
Address Space choice control.
Definition at line 92 of file FUDialog.hh.
Referenced by onSetAddressSpace(), and updateAddressSpaceChoice().
functionUnit_
TTAMachine::FunctionUnit* FUDialog::functionUnit_ private
FunctionUnit to modify.
Definition at line 83 of file FUDialog.hh.
Referenced by onAddOperation(), onAddOperationFromOpset(), onAddPort(), onDeleteOperation(), onEditOperation(), onOK(), onSetAddressSpace(), selectedOperation(), selectedPort(), TransferDataToWindow(), updateAddressSpaceChoice(), updateOperationList(), and updatePortList().
name_
wxString FUDialog::name_ private
Name of the function unit.
Definition at line 85 of file FUDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
operationListCtrl_
wxListCtrl* FUDialog::operationListCtrl_ private
Operation list control.
Definition at line 90 of file FUDialog.hh.
Referenced by onDeleteOperation(), onOperationRightClick(), onOperationSelection(), selectedOperation(), and updateOperationList().
operationsSizer_
wxStaticBoxSizer* FUDialog::operationsSizer_ private
Sizer for the operation list controls.
Definition at line 97 of file FUDialog.hh.
Referenced by createContents(), and setTexts().
portListCtrl_
wxListCtrl* FUDialog::portListCtrl_ private
Port list control.
Definition at line 88 of file FUDialog.hh.
Referenced by onPortRightClick(), onPortSelection(), selectedPort(), and updatePortList().
portsSizer_
wxStaticBoxSizer* FUDialog::portsSizer_ private
Sizer for the port list controls.
Definition at line 95 of file FUDialog.hh.
Referenced by createContents(), and setTexts().
The documentation for this class was generated from the following files:
FUDialog.hh
FUDialog.cc