OpenASIP: TTAProgram::Move Class Reference
TTAProgram::Move Class Reference
#include <Move.hh>
Public Member Functions
Move (Terminal *src, Terminal *dst, const TTAMachine::Bus &bus, MoveGuard *guard)
Move (Terminal *src, Terminal *dst, const TTAMachine::Bus &bus)
~Move ()
Instruction & parent () const
void setParent (Instruction &ins)
bool isInInstruction () const
bool isUnconditional () const
bool isConditional () const
bool isJump () const
bool isCall () const
bool isControlFlowMove () const
bool isReturn () const
bool isFunctionCall () const
bool isTriggering () const
Terminal & source () const
void setSource (Terminal *src)
Terminal & destination () const
void setDestination (Terminal *dst)
MoveGuard & guard () const
void setGuard (MoveGuard *guard)
const TTAMachine::Bus & bus () const
void setBus (const TTAMachine::Bus &bus)
TTAMachine::Socket & destinationSocket () const
TTAMachine::Socket & sourceSocket () const
int guardLatency () const
std::shared_ptr< Move > copy () const
std::string toString () const
bool hasSourceLineNumber () const
int sourceLineNumber () const
bool hasSourceFileName () const
std::string sourceFileName () const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Private Member Functions
Move (const Move &)
Copying not allowed.
Move & operator= (const Move &)
Assignment not allowed.
Private Attributes
Instruction * parent_
Parent instruction of the move.
Terminal * src_
The source of the move.
Terminal * dst_
The destination of the move.
const TTAMachine::Bus * bus_
The bus where the transport is carried.
MoveGuard * guard_
The boolean expression that predicates the move.
Detailed Description
Represents a data transport through the TTA programmable interconnection network.
Definition at line 55 of file Move.hh.
Constructor & Destructor Documentation
Move() [1/3]
TTAProgram::Move::Move (Terminal * src, Terminal * dst, const TTAMachine::Bus & bus, MoveGuard * guard)
The constructor.
Creates a guarded move.
The ownership of the source and destination terminal objects and the guard will be passed to the move.
Parameters
src The source of the move.
dst The destination of the move.
bus The bus on which the transport is carried.
guard The Boolean expression the move is predicated with.
Definition at line 73 of file Move.cc.
                                     :
    parent_(NULL), src_(src), dst_(dst), bus_(&bus), guard_(guard) {
}
Move() [2/3]
TTAProgram::Move::Move (Terminal * src, Terminal * dst, const TTAMachine::Bus & bus)
The constructor.
Creates an unguarded move.
Parameters
src The source of the move.
dst The destination of the move.
bus The bus on which the transport is carried.
Definition at line 88 of file Move.cc.
                                                 :
    parent_(NULL), src_(src), dst_(dst), bus_(&bus),
    guard_(NULL) {
}
~Move()
TTAProgram::Move::~Move ()
The destructor.
Definition at line 97 of file Move.cc.
            {
    delete dst_;
    dst_ = NULL;
    delete src_;
    src_ = NULL;
    if (guard_ != NULL) {
        delete guard_;
        guard_ = NULL;
    }
}
References dst_, guard_, and src_.
Move() [3/3]
TTAProgram::Move::Move (const Move &) private
Copying not allowed.
Member Function Documentation
bus()
const Bus & TTAProgram::Move::bus () const
Returns the bus on which the move is carried.
Returns
the bus on which the move is carried.
Definition at line 373 of file Move.cc.
                {
    return *bus_;
}
References bus_.
Referenced by CodeCompressorPlugin::addBitsForDestinationField(), CodeCompressorPlugin::addBitsForSourceField(), SimpleICOptimizer::addConnections(), TTAProgram::Instruction::addMove(), ProximMachineStateWindow::addMoves(), BusBroker::allAvailableResources(), BFOptimization::assign(), SimpleBrokerDirector::assign(), BusBroker::assign(), BFOptimization::assignCopyToPrologEpilog(), ControlFlowGraph::buildMBBFromBB(), CycleLookBackSoftwareBypasser::bypassNode(), UtilizationStats::calculateForInstruction(), SimpleBrokerDirector::canAssign(), POMValidator::checkConnectivity(), CopyingDelaySlotFiller::collectMoves(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createInstruction(), POMDisassembler::createMove(), POMDisassembler::disassemble(), CodeCompressorPlugin::encodeMove(), CopyingDelaySlotFiller::getMoveNode(), CodeCompressorPlugin::immediateTerminal(), DisasmExecPercentageAttrProvider::moveCellAttr(), CompiledSimSymbolGenerator::moveOperandSymbol(), BFLateBypass::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepDown::operator()(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), BFShareOperandLate::operator()(), BFShareOperandWithScheduled::operator()(), SimProgramBuilder::processMove(), ControlFlowGraph::removeJumpToTarget(), RegisterRenamer::renameLiveRange(), AssignmentPlan::resetAssignments(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BFShareOperandLate::revert(), setBus(), PostpassOperandSharer::tryRemoveOperandWrite(), PreOptimizer::tryToRemoveGuardInversingOp(), BusBroker::unassign(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), BFScheduleTD::undoOnlyMe(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), and DataDependenceGraph::writeToXMLFile().
copy()
std::shared_ptr< Move > TTAProgram::Move::copy () const
Makes a copy of the move.
The copy is identical, except that it is not registered to the instruction of the original move (and therefore, any address it refers to is not meaningful).
Returns
A copy of the move.
Definition at line 413 of file Move.cc.
                 {
    std::shared_ptr<Move> newMove = NULL;
    if (isUnconditional()) {
        newMove = std::make_shared<Move>(src_->copy(), dst_->copy(), *bus_);
    } else {
        newMove = std::make_shared<Move>(
            src_->copy(), dst_->copy(), *bus_, guard_->copy());
    }
    for (int i = 0; i < annotationCount(); i++ ) {
        newMove->addAnnotation(annotation(i));
    }
    newMove->setParent(NullInstruction::instance());
    return newMove;
}
References TTAProgram::AnnotatedInstructionElement::annotation(), TTAProgram::AnnotatedInstructionElement::annotationCount(), bus_, TTAProgram::MoveGuard::copy(), TTAProgram::Terminal::copy(), dst_, guard_, TTAProgram::NullInstruction::instance(), isUnconditional(), and src_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), Peel2BBLoops::appendBB(), SimpleIfConverter::appendBB(), TTAProgram::Instruction::copy(), MoveNodeDuplicator::duplicateMove(), CopyingDelaySlotFiller::getMove(), and BFRegCopy::operator()().
destination()
Terminal & TTAProgram::Move::destination () const
Returns the destination of this move.
Returns
the destination of this move.
Definition at line 323 of file Move.cc.
{
    return *dst_;
}
References dst_.
Referenced by CodeCompressorPlugin::addBitsForDestinationField(), llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), ProgramOperation::addInputNode(), TTAProgram::Instruction::addMove(), ProximMachineStateWindow::addMoves(), ProgramOperation::addNode(), StaticProgramAnalyzer::addProgram(), BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), InputPSocketBroker::allAvailableResources(), CopyingDelaySlotFiller::allowedToSpeculate(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), SimpleBrokerDirector::assign(), InputFUBroker::assign(), InputPSocketBroker::assign(), ExecutionPipelineResource::assignDestination(), BFSwapOperands::BFSwapOperands(), MoveNodeGroupBuilder::build(), ControlFlowGraph::buildMBBFromBB(), llvm::LLVMTCEIRBuilder::buildTCECFG(), MachineConnectivityCheck::busConnectedToAnyFU(), MachineConnectivityCheck::busConnectedToDestination(), UtilizationStats::calculateForInstruction(), BusResource::canAssign(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignDestination(), POMValidator::checkCompiledSimulatability(), POMValidator::checkConnectivity(), ExecutionPipelineResource::checkOperandAllowed(), POMValidator::checkSimulatability(), DataDependenceGraphBuilder::constructIndividualBB(), ProcedurePass::copyCfgToProcedure(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::CodeGenerator::createForLoopBufferInit(), ControlFlowGraph::createJumps(), POMDisassembler::createMove(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), BFOptimization::destinationFU(), DataDependenceGraph::destRenamed(), POMDisassembler::disassemble(), MoveNodeDuplicator::duplicateMove(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), MoveNode::earliestResultReadCycle(), ControlFlowEdge::edgePredicateFromMove(), BUBasicBlockScheduler::finalizeSchedule(), BUBasicBlockScheduler::findBypassDestinations(), FUBroker::findDstFUOfMove(), CopyingDelaySlotFiller::findJumpImmediate(), ControlFlowGraph::findNextIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), DataDependenceGraphBuilder::findStaticRegisters(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterKill(), DataDependenceGraph::firstScheduledRegisterWrite(), DataDependenceGraph::firstScheduledRegisterWrites(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateAddFUResult(), CompiledSimCodeGenerator::generateInstruction(), BF2Scheduler::getDstUnit(), CopyingDelaySlotFiller::getMove(), DataDependenceGraph::guardRenamed(), DataDependenceGraph::guardRestored(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), ProcedureTransferTracker::handleEvent(), RFAccessTracker::handleEvent(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BasicBlockScheduler::handleRemovedResultMoves(), llvm::LLVMTCEBuilder::hasAmbiguousASpaceRefs(), BFOptimization::immCountPreventsScheduling(), RegisterRenamer::initializeFreeRegisters(), BUMoveNodeSelector::initializeReadylist(), CriticalPathBBMoveNodeSelector::initializeReadylist(), InputFUBroker::isApplicable(), BusBroker::isAvailable(), BF2Scheduler::isDestinationUniversalReg(), ExecutionPipelineBroker::isMoveTrigger(), BF2Scheduler::isTrigger(), DataDependenceGraphBuilder::isTriggering(), BFOptimization::jumpGuardAvailableCycle(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterKill(), DataDependenceGraph::lastScheduledRegisterWrites(), DataDependenceEdge::latencySt(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), main(), DataDependenceGraph::mergeAndKeepSource(), DataDependenceGraph::mergeAndKeepUser(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), BF2Scheduler::mustBeTrigger(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandTooLate(), BFDropPreShared::operator()(), BFLateBypasses::operator()(), BFLateBypassGuard::operator()(), BFPushMoveUp::operator()(), BFScheduleBU::operator()(), BFShareOperand::operator()(), BFShareOperands::operator()(), BFShareOperandsLate::operator()(), BFShareOperandWithScheduled::operator()(), BFPostpassBypass::operator()(), ExecutionPipelineResource::poConflictsWithInputPort(), DataDependenceGraphBuilder::processDestination(), SimProgramBuilder::processMove(), DataDependenceGraphBuilder::processOperand(), ProgramDependenceGraph::processPredicate(), DataDependenceGraphBuilder::processTriggerPO(), CycleLookBackSoftwareBypasser::removeDeadResults(), ProgramOperation::removeInputNode(), RegisterRenamer::renameDestinationRegister(), RegisterRenamer::renameLiveRange(), ExecutionPipelineResource::resourcesAllowTrigger(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), BF2Scheduler::revertBBLiveRangeBookkeepingForDestination(), BFOptimization::RFReadPortCountPreventsScheduling(), DataDependenceGraph::sanityCheck(), DataDependenceEdge::saveState(), BasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleResultReadTempMoves(), BUBasicBlockScheduler::scheduleRRMove(), BasicBlockScheduler::scheduleRRTempMoves(), BUBasicBlockScheduler::scheduleRRTempMoves(), ProgramOperation::setOperation(), BFOptimization::setPrologDstFUAnno(), DataDependenceGraph::sourceRenamed(), TTAProgram::BasicBlock::statistics(), ProgramOperation::switchInputs(), ProgramOperation::triggeringMove(), ExecutionPipelineResource::triggerTooEarly(), PostpassOperandSharer::tryRemoveOperandWrite(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToRemoveGuardInversingOp(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), InputFUBroker::unassign(), InputPSocketBroker::unassign(), SimpleBrokerDirector::unassign(), ExecutionPipelineResource::unassignDestination(), BFUpdateMoveOnBypass::undoOnlyMe(), BFRegCopyAfter::undoSplit(), DataDependenceGraph::unMergeUser(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), BFMergeAndKeepUser::updateEdges(), SimpleIfConverter::writesRegister(), and CopyingDelaySlotFiller::writesRegister().
destinationSocket()
Socket & TTAProgram::Move::destinationSocket () const
Definition at line 388 of file Move.cc.
{
    return *dst_->port().inputSocket();
}
References dst_, TTAMachine::Port::inputSocket(), and TTAProgram::Terminal::port().
Referenced by SimpleICOptimizer::addConnections(), and UtilizationStats::calculateForInstruction().
guard()
MoveGuard & TTAProgram::Move::guard () const
Returns the Boolean expression that guards this move.
Returns
the Boolean expression that guards this move.
Exceptions
InvalidData if the move is not predicated.
Definition at line 345 of file Move.cc.
                  {
    if (guard_ != NULL) {
        return *guard_;
    } else {
        throw InvalidData(
            __FILE__, __LINE__, "Move::guard()", "Move is not predicated.");
    }
}
References guard_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BusBroker::allAvailableResources(), LoopAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), SimpleBrokerDirector::assign(), BusBroker::assign(), UtilizationStats::calculateForInstruction(), InputPSocketResource::canAssign(), OutputPSocketResource::canAssign(), PSocketResource::canAssign(), SimpleBrokerDirector::canAssign(), MachineConnectivityCheck::canBypass(), MachineConnectivityCheck::canBypassOpToDst(), SimpleIfConverter::canConvert(), MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), BusBroker::canTransportImmediate(), CopyingDelaySlotFiller::collectMoves(), MachineConnectivityCheck::copyOpFUs(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createMove(), DataDependenceGraph::destRenamed(), ControlFlowGraph::directJump(), MoveNodeDuplicator::duplicateMove(), ControlFlowEdge::edgePredicateFromMove(), DataDependenceGraph::exclusingGuards(), ExecutionPipelineResource::exclusiveMoves(), CopyingDelaySlotFiller::fillDelaySlots(), RegisterRenamer::findGuardRegisters(), CopyingDelaySlotFiller::findJump(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), CopyingDelaySlotFiller::getMove(), guardLatency(), DataDependenceGraph::guardRenamed(), DataDependenceGraph::guardsAllowBypass(), CallsToJumps::handleControlFlowGraph(), BusBroker::hasGuard(), ControlFlowGraph::indirectJump(), PreOptimizer::inverseGuardsOfHeads(), OutputFUBroker::isApplicable(), BusBroker::isAvailable(), DataDependenceGraph::isNotAvoidable(), BF2Scheduler::jumpGuard(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), BFLateBypassGuard::operator()(), BFScheduleExact::operator()(), BFEarlyGuardBypass::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardFromSucc::operator()(), ProgramOperation::outputIndexFromGuardOfMove(), BF2Scheduler::possibleTempRegRFs(), DataDependenceGraphBuilder::processGuard(), SimProgramBuilder::processMove(), ProgramDependenceGraph::removeGuardedJump(), ControlFlowGraph::removeJumpToTarget(), RegisterRenamer::renameLiveRange(), ExecutionPipelineResource::resultPort(), DataDependenceGraph::sameGuards(), DataDependenceGraph::sanityCheck(), SequentialScheduler::scheduleMove(), setGuard(), BFRenameLiveRange::setGuard(), SimpleIfConverter::successors(), PostpassOperandSharer::tryRemoveOperandWrite(), BasicBlockScheduler::tryToOptimizeWaw(), and BUBasicBlockScheduler::tryToOptimizeWaw().
guardLatency()
int TTAProgram::Move::guardLatency () const
Returns the total guard latency of the guard of given move, or 0 if the move is unconditional.
Definition at line 503 of file Move.cc.
{
    if (!isUnconditional()) {
        const TTAMachine::Guard& g = guard().guard();
        const TTAMachine::RegisterGuard* rg =
        dynamic_cast<const TTAMachine::RegisterGuard*>(&g);
        if (rg != NULL) {
            const TTAMachine::RegisterFile& rf =
            *rg->registerFile();
            return rf.guardLatency() +
            rf.machine()->controlUnit()->globalGuardLatency();
        } else {
            return g.parentBus()->machine()->controlUnit()->globalGuardLatency();
        }
    } else {
        return 0;
    }
}
References TTAMachine::Machine::controlUnit(), TTAMachine::ControlUnit::globalGuardLatency(), guard(), TTAProgram::MoveGuard::guard(), TTAMachine::RegisterFile::guardLatency(), isUnconditional(), TTAMachine::Component::machine(), TTAMachine::Guard::parentBus(), and TTAMachine::RegisterGuard::registerFile().
Referenced by PostpassOperandSharer::tryRemoveOperandWrite(), and SimpleBrokerDirector::unassign().
hasSourceFileName()
bool TTAProgram::Move::hasSourceFileName () const
Returns true in case at least one source code filename is known for this move.
Definition at line 478 of file Move.cc.
{
    return sourceFileName() != "";
}
References sourceFileName().
Referenced by POMDisassembler::disassemble(), and ProximDebuggerWindow::loadProgram().
hasSourceLineNumber()
bool TTAProgram::Move::hasSourceLineNumber () const
Returns true in case at least one source code line number is known for this move.
Definition at line 445 of file Move.cc.
{
    return sourceLineNumber() != -1;
}
References sourceLineNumber().
Referenced by PRegionAliasAnalyzer::analyze(), POMDisassembler::disassemble(), DataDependenceGraph::dotString(), BasicBlockNode::toString(), and ProximDebuggerWindow::updateAnnotations().
isCall()
bool TTAProgram::Move::isCall () const
Tells whether the move triggers a call operation.
Returns
true if this move triggers a call operation.
Definition at line 190 of file Move.cc.
                   {
    if (dst_->isFUPort()) {
        // there is already check. no need for double-check.
        const TerminalFUPort* tfup = static_cast<const TerminalFUPort*>(dst_);
        if (tfup->isOpcodeSetting()) {
            if (tfup->operation().isCall()) {
                return true;
            }
        } else {
            Operation* tmpOp = &tfup->hintOperation();
            if (tmpOp != &NullOperation::instance() &&
                tfup->hintOperation().isCall()) {
                return true;
            }
        }
    }
    return false;
}
References dst_, TTAProgram::TerminalFUPort::hintOperation(), NullOperation::instance(), Operation::isCall(), TTAProgram::Terminal::isFUPort(), TTAProgram::TerminalFUPort::isOpcodeSetting(), and TTAProgram::TerminalFUPort::operation().
Referenced by ControlFlowGraph::createBBEdges(), POMDisassembler::disassemble(), TTAProgram::Instruction::hasCall(), isFunctionCall(), and ProgramDependenceGraph::processRegion().
isConditional()
bool TTAProgram::Move::isConditional () const inline
Definition at line 69 of file Move.hh.
{ return !isUnconditional(); }
References isUnconditional().
isControlFlowMove()
bool TTAProgram::Move::isControlFlowMove () const
Tells whether the move triggers an operation that controls the program flow.
Returns
true if this move triggers a jump/call operation.
Definition at line 233 of file Move.cc.
{
    if (dst_->isFUPort()) {
        const TerminalFUPort* tfup = dynamic_cast<const TerminalFUPort*>(dst_);
        if (tfup->isOpcodeSetting()) {
            if (tfup->operation().isControlFlowOperation()) {
                return true;
            }
        } else {
            Operation* tmpOp = &tfup->hintOperation();
            if (tmpOp != &NullOperation::instance() &&
                tfup->hintOperation().isControlFlowOperation()) {
                return true;
            }
        }
    }
    return false;
}
References dst_, TTAProgram::TerminalFUPort::hintOperation(), NullOperation::instance(), Operation::isControlFlowOperation(), TTAProgram::Terminal::isFUPort(), TTAProgram::TerminalFUPort::isOpcodeSetting(), and TTAProgram::TerminalFUPort::operation().
Referenced by LoopPrologAndEpilogBuilder::build(), CycleLookBackSoftwareBypasser::bypass(), CopyingDelaySlotFiller::collectMoves(), ControlFlowGraph::computeLeadersFromJumpSuccessors(), DataDependenceGraph::edgeWeight(), BF2ScheduleFront::getPreferredLimits(), BasicBlockScheduler::handleLoopDDG(), TTAProgram::Instruction::hasControlFlowMove(), CriticalPathBBMoveNodeSelector::isReadyToBeScheduled(), BFLateBypass::operator()(), BFPushAntidepDown::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultClose::operator()(), BFScheduleBU::operator()(), BFPostpassBypass::operator()(), RLBUPriorityCriticalPath::operator()(), DataDependenceGraphBuilder::processDestination(), SimProgramBuilder::processMove(), DataDependenceGraph::sanityCheck(), BF2ScheduleFront::scheduleFrontFromMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BFOptimization::usePrologMove(), and MoveNodeGroup::writesJumpGuard().
isFunctionCall()
bool TTAProgram::Move::isFunctionCall () const
Returns true in case the move performs a function call.
Currently two ways of calling functions are supported: the separate CALL operation, and regular JUMP with a separate RA save move. The latter is detected using an annotation in the JUMP move.
Definition at line 219 of file Move.cc.
{
    if (isCall()) return true;
    if (!isJump()) return false;
    return hasAnnotations(ProgramAnnotation::ANN_JUMP_FUNCTION_CALL);
}
References TTAProgram::ProgramAnnotation::ANN_JUMP_FUNCTION_CALL, TTAProgram::AnnotatedInstructionElement::hasAnnotations(), isCall(), and isJump().
Referenced by DataDependenceGraph::firstRegisterCycle(), ConstantAliasAnalyzer::getConstantAddress(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraphBuilder::processTriggerMemoryAndFUStates(), DataDependenceGraphBuilder::processTriggerRegistersAndOperations(), and DataDependenceGraph::sanityCheck().
isInInstruction()
bool TTAProgram::Move::isInInstruction () const
Return true if this move belongs to an instruction.
Returns
True if this move belongs to an instruction.
Definition at line 144 of file Move.cc.
{
    return parent_ != NULL && parent_ != &NullInstruction::instance();
}
References TTAProgram::NullInstruction::instance(), and parent_.
Referenced by ITemplateBroker::assign(), POMDisassembler::createMove(), DataDependenceGraph::createSubgraph(), and ITemplateBroker::isAlreadyAssigned().
isJump()
bool TTAProgram::Move::isJump () const
Tells whether the move triggers a jump operation.
Returns
true if this move triggers a jump operation.
Definition at line 164 of file Move.cc.
                   {
    if (dst_->isFUPort()) {
        // there is already check. no need for double-check.
        const TerminalFUPort* tfup = static_cast<const TerminalFUPort*>(dst_);
        if (tfup->isOpcodeSetting()) {
            if (tfup->operation().isBranch()) {
                return true;
            }
        } else {
            Operation* tmpOp = &tfup->hintOperation();
            if (tmpOp != &NullOperation::instance() &&
                tfup->hintOperation().isBranch()) {
                return true;
            }
        }
    }
    return false;
}
References dst_, TTAProgram::TerminalFUPort::hintOperation(), NullOperation::instance(), Operation::isBranch(), TTAProgram::Terminal::isFUPort(), TTAProgram::TerminalFUPort::isOpcodeSetting(), and TTAProgram::TerminalFUPort::operation().
Referenced by LoopAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), SimpleIfConverter::appendBB(), BusBroker::canTransportImmediate(), CopyingDelaySlotFiller::collectMoves(), SimpleIfConverter::combineBlocks(), ControlFlowGraph::computeLeadersFromJumpSuccessors(), ProcedurePass::copyCfgToProcedure(), ControlFlowGraph::createBBEdges(), POMDisassembler::disassemble(), DataDependenceGraph::edgeWeight(), BF2Scheduler::findJump(), CopyingDelaySlotFiller::findJump(), BasicBlockNode::findJumps(), ProcedureTransferTracker::handleEvent(), ControlFlowGraph::hasInstructionAnotherJump(), TTAProgram::Instruction::hasJump(), PreOptimizer::inverseGuardsOfHeads(), isFunctionCall(), isReturn(), BFRemoveLoopChecksAndJump::operator()(), ProgramDependenceGraph::ProgramDependenceGraph(), ControlFlowGraph::removeJumpToTarget(), SimpleIfConverter::successors(), and BFOptimization::usePrologMove().
isReturn()
bool TTAProgram::Move::isReturn () const
Tells whether the move is used to return from a procedure.
Note: the detection is not always reliable, this method can return false even in case the move actually is a return in some cases.
Definition at line 259 of file Move.cc.
                     {
    if (!isJump()) {
        return false;
    }
    // direct gcu.ra -> gcu.jump.1 is considered a return
    if (source().isRA()) {
        return true;
    }
    if (hasAnnotations(ProgramAnnotation::ANN_STACKFRAME_PROCEDURE_RETURN)) {
        return true;
    }
    return false;
}
References TTAProgram::ProgramAnnotation::ANN_STACKFRAME_PROCEDURE_RETURN, TTAProgram::AnnotatedInstructionElement::hasAnnotations(), isJump(), and source().
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), TTASimulationController::findProgramExitPoints(), TTAProgram::Instruction::hasReturn(), BFRegCopy::operator()(), DataDependenceGraphBuilder::processSource(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), and CopyingDelaySlotFiller::updateJumpsAndCfg().
isTriggering()
bool TTAProgram::Move::isTriggering () const
Tells whether the move triggers an operation.
Returns
true if this move triggers an operation.
Definition at line 284 of file Move.cc.
{
    if (dst_->isFUPort()) {
        const TerminalFUPort* tfup = dynamic_cast<const TerminalFUPort*>(dst_);
        if (tfup->isTriggering()) {
            return true;
        }
    }
    return false;
}
References dst_, TTAProgram::Terminal::isFUPort(), and TTAProgram::TerminalFUPort::isTriggering().
Referenced by CopyingDelaySlotFiller::allowedToSpeculate(), ResourceConstraintAnalyzer::analyzeMoveNode(), ControlFlowGraph::buildMBBFromBB(), CycleLookBackSoftwareBypasser::bypass(), DataDependenceGraph::dotString(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), ControlFlowEdge::edgePredicateFromMove(), CompiledSimCodeGenerator::generateAddFUResult(), CompiledSimCodeGenerator::generateInstruction(), ExecutionPipelineBroker::isMoveTrigger(), DataDependenceEdge::latencySt(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), BFLateBypass::operator()(), DataDependenceEdge::saveState(), BasicBlockScheduler::tryToDelayOperands(), BasicBlockNode::updateHWloopLength(), and DataDependenceGraph::writeToXMLFile().
isUnconditional()
bool TTAProgram::Move::isUnconditional () const
Tells whether the move is predicated or not.
Returns
true if this move is not predicated.
Definition at line 154 of file Move.cc.
{
    return (guard_ == NULL);
}
References guard_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BFOptimization::addJumpGuardIfNeeded(), TTAProgram::Instruction::addMove(), BusBroker::allAvailableResources(), CopyingDelaySlotFiller::allowedToSpeculate(), SimpleBrokerDirector::assign(), BusBroker::assign(), CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), UtilizationStats::calculateForInstruction(), InputPSocketResource::canAssign(), OutputPSocketResource::canAssign(), PSocketResource::canAssign(), BFOptimization::canAssign(), SimpleBrokerDirector::canAssign(), MachineConnectivityCheck::canBypass(), MachineConnectivityCheck::canBypassOpToDst(), SimpleIfConverter::canConvert(), MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), BusBroker::canTransportImmediate(), DataDependenceGraphBuilder::checkAndCreateMemAntideps(), CopyingDelaySlotFiller::collectMoves(), SimpleIfConverter::combineBlocks(), DataDependenceGraphBuilder::constructIndividualBB(), copy(), MachineConnectivityCheck::copyOpFUs(), RegisterCopyAdder::createAntidepsForReg(), BFRegCopy::createAntidepsForReg(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createMove(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), DataDependenceGraphBuilder::createTriggerDependencies(), DataDependenceGraph::destRenamed(), ControlFlowGraph::directJump(), MoveNodeDuplicator::duplicateMove(), ControlFlowEdge::edgePredicateFromMove(), DataDependenceGraph::exclusingGuards(), ExecutionPipelineResource::exclusiveMoves(), CopyingDelaySlotFiller::fillDelaySlots(), RegisterRenamer::findGuardRegisters(), BF2Scheduler::findJump(), CopyingDelaySlotFiller::findJump(), DataDependenceGraph::findLiveRange(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterKill(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateInstruction(), CopyingDelaySlotFiller::getMove(), guardLatency(), DataDependenceGraph::guardRenamed(), DataDependenceGraph::guardsAllowBypass(), CallsToJumps::handleControlFlowGraph(), SimpleIfConverter::hasConditionals(), SimpleBrokerDirector::hasGuard(), ControlFlowGraph::indirectJump(), PreOptimizer::inverseGuardsOfHeads(), OutputFUBroker::isApplicable(), BusBroker::isAvailable(), isConditional(), DataDependenceGraph::isNotAvoidable(), BF2Scheduler::jumpGuard(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterGuardReads(), DataDependenceGraph::lastScheduledRegisterKill(), CompiledSimulation::moveExecutionCount(), ExecutionPipelineResource::operandAllowedAtCycle(), BFLateBypassGuard::operator()(), BFScheduleExact::operator()(), BFSchedulePreLoopShared::operator()(), BFShareOperands::operator()(), BFShareOperandsLate::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardsFromSuccs::operator()(), BFTryRemoveGuard::operator()(), ProgramOperation::outputIndexFromGuardOfMove(), BF2Scheduler::possibleTempRegRFs(), DataDependenceGraphBuilder::processMemWrite(), SimProgramBuilder::processMove(), DataDependenceGraphBuilder::processRegWrite(), ControlFlowGraph::removeJumpToTarget(), ExecutionPipelineResource::resultAllowedAtCycle(), DataDependenceGraph::resultUsed(), BFOptimization::rmEC(), BFOptimization::rmLC(), DataDependenceGraph::rWawRawEdgesOutUncond(), DataDependenceGraph::sameGuards(), DataDependenceGraph::sanityCheck(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BFOptimization::setJumpGuard(), SimpleIfConverter::successors(), PostpassOperandSharer::tryRemoveOperandWrite(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToOptimizeWaw(), and BUBasicBlockScheduler::tryToOptimizeWaw().
operator=()
Move & TTAProgram::Move::operator= (const Move &) private
Assignment not allowed.
parent()
Instruction & TTAProgram::Move::parent () const
Returns
The parent instruction of the move.
Exceptions
IllegalRegistration if the move is independent.
Definition at line 115 of file Move.cc.
                   {
    if (parent_ != NULL && parent_ != &NullInstruction::instance()) {
        return *parent_;
    } else {
        throw IllegalRegistration(__FILE__, __LINE__, __func__,
                                  "Move is not registered.");
    }
}
References __func__, TTAProgram::NullInstruction::instance(), and parent_.
Referenced by ITemplateBroker::assign(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createMove(), DataDependenceGraph::createSubgraph(), DataDependenceGraph::createSubgraph(), CopyingDelaySlotFiller::findJumpImmediate(), ITemplateBroker::isAlreadyAssigned(), TTAProgram::Instruction::removeMove(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveGuardInversingOp(), ITemplateBroker::unassign(), and CopyingDelaySlotFiller::updateJumpsAndCfg().
setBus()
void TTAProgram::Move::setBus (const TTAMachine::Bus & bus)
Sets a new bus for the move.
Parameters
bus The new bus.
Definition at line 383 of file Move.cc.
{
    bus_ = &bus;
}
References bus(), and bus_.
Referenced by BusBroker::assign(), CycleLookBackSoftwareBypasser::bypassNode(), SimpleBrokerDirector::canAssign(), BFLateBypassGuard::operator()(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), CycleLookBackSoftwareBypasser::removeBypass(), BusBroker::unassign(), SimpleBrokerDirector::unassign(), BUBasicBlockScheduler::undoBypass(), BFLateBypassGuard::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), and BFScheduleTD::undoOnlyMe().
setDestination()
void TTAProgram::Move::setDestination (Terminal * dst)
Sets a new destination for the move and deletes the old one.
Parameters
dst The new destination.
Definition at line 333 of file Move.cc.
{
    delete dst_;
    dst_ = dst;
}
References dst_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), InputFUBroker::assign(), InputPSocketBroker::assign(), SimpleBrokerDirector::canAssign(), DataDependenceGraph::mergeAndKeepSource(), RegisterRenamer::renameLiveRange(), BFRenameLiveRange::setTerminals(), BFCopyRegWithOp::splitMove(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), ProgramOperation::switchInputs(), PreOptimizer::tryToOptimizeAddressReg(), SimpleBrokerDirector::unassign(), BFRenameLiveRange::undoSetTerminal(), and BFRegCopyAfter::undoSplit().
setGuard()
void TTAProgram::Move::setGuard (MoveGuard * guard)
Sets a new guard for the move and deletes the old one.
Parameters
guard The new guard.
Definition at line 360 of file Move.cc.
{
    if (guard_ != NULL) {
        delete guard_;
    }
    guard_ = guard;
}
References guard(), and guard_.
Referenced by BusBroker::assign(), LoopPrologAndEpilogBuilder::build(), SimpleBrokerDirector::canAssign(), CopyingDelaySlotFiller::collectMoves(), PreOptimizer::inverseGuardsOfHeads(), BFLateBypassGuard::operator()(), BFSchedulePreLoopShared::operator()(), BFEarlyGuardBypass::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardFromSucc::operator()(), ControlFlowGraph::removeJumpToTarget(), RegisterRenamer::renameLiveRange(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BFRenameLiveRange::setGuard(), BFOptimization::setJumpGuard(), CopyingDelaySlotFiller::tryToAssignNodes(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), SimpleBrokerDirector::unassign(), BFLateBypassGuard::undoOnlyMe(), BFEarlyGuardBypass::undoOnlyMe(), BFRemoveGuard::undoOnlyMe(), BFRemoveGuardFromSucc::undoOnlyMe(), and BFOptimization::unsetJumpGuard().
setParent()
void TTAProgram::Move::setParent (Instruction & ins)
Set a new parent for the move.
Parameters
ins The new parent.
Definition at line 130 of file Move.cc.
{
    if (&ins == &NullInstruction::instance()) {
        parent_ = NULL;
    } else {
        parent_ = &ins;
    }
}
References TTAProgram::NullInstruction::instance(), and parent_.
Referenced by TTAProgram::Instruction::addMove(), and TTAProgram::Instruction::removeMove().
setSource()
void TTAProgram::Move::setSource (Terminal * src)
Sets a new source for the move and deletes the old one.
Parameters
src The new source.
Definition at line 312 of file Move.cc.
{
    delete src_;
    src_ = src;
}
References src_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), IUBroker::assign(), CycleLookBackSoftwareBypasser::bypassNode(), SimpleBrokerDirector::canAssign(), CopyingDelaySlotFiller::collectMoves(), ControlFlowGraph::convertBBRefsToInstRefs(), TTAProgram::Program::convertSymbolRefsToInsRefs(), BUBasicBlockScheduler::handleLoopDDG(), DataDependenceGraph::mergeAndKeepUser(), BFUpdateMoveOnBypass::operator()(), RegisterRenamer::renameLiveRange(), TTAProgram::Program::replaceUniversalAddressSpaces(), BasicBlockScheduler::scheduleMove(), BFRenameLiveRange::setTerminals(), BFCopyRegWithOp::splitMove(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToPrecalcConstantAdd(), IUResource::unassign(), SimpleBrokerDirector::unassign(), BFScheduleExact::undoOnlyMe(), BFUpdateMoveOnBypass::undoOnlyMe(), BFRenameLiveRange::undoSetTerminal(), BFCopyRegWithOp::undoSplit(), BFRegCopyBefore::undoSplit(), DataDependenceGraph::unMergeUser(), BasicBlockNode::updateHWloopLength(), and CopyingDelaySlotFiller::updateJumpsAndCfg().
source()
Terminal & TTAProgram::Move::source () const
Returns the source of this move.
Returns
the source of this move.
Definition at line 302 of file Move.cc.
                   {
    return *src_;
}
References src_.
Referenced by CodeCompressorPlugin::addBitsForSourceField(), llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), SimpleICOptimizer::addConnections(), TTAProgram::Instruction::addMove(), ProximMachineStateWindow::addMoves(), ProgramOperation::addNode(), ProgramOperation::addOutputNode(), StaticProgramAnalyzer::addProgram(), BusBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), IUBroker::allAvailableResources(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), IUResource::assign(), OutputPSocketResource::assign(), IUResource::assign(), SimpleBrokerDirector::assign(), ITemplateBroker::assign(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), IUBroker::assign(), BFOptimization::assignCopyToPrologEpilog(), BFSwapOperands::BFSwapOperands(), MoveNodeGroupBuilder::build(), LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), ControlFlowGraph::buildMBBFromBB(), CycleLookBackSoftwareBypasser::bypassNode(), UtilizationStats::calculateForInstruction(), OutputPSocketResource::canAssign(), BusResource::canAssign(), IUResource::canAssign(), BFOptimization::canAssign(), SimpleBrokerDirector::canAssign(), ExecutionPipelineResource::canAssignSource(), MachineConnectivityCheck::canBypass(), SimpleIfConverter::canConvert(), MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), BusBroker::canTransportImmediate(), POMValidator::checkConnectivity(), CopyingDelaySlotFiller::checkImmediatesAfter(), CopyingDelaySlotFiller::collectMoves(), ControlFlowGraph::computeLeadersFromJumpSuccessors(), DataDependenceGraphBuilder::constructIndividualBB(), ControlFlowGraph::convertBBRefsToInstRefs(), TTAProgram::Program::convertSymbolRefsToInsRefs(), ProcedurePass::copyCfgToProcedure(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), BF2Scheduler::countLoopInvariantValueUsages(), ControlFlowGraph::createBBEdges(), TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::CodeGenerator::createForLoopBufferInit(), ControlFlowGraph::createJumps(), POMDisassembler::createMove(), DataDependenceGraph::createRegisterAntiDependenciesBetweenNodes(), DataDependenceGraph::destRenamed(), MemoryAliasAnalyzer::detectConstantScale(), POMDisassembler::disassemble(), MoveNodeDuplicator::duplicateMove(), ExecutionPipelineBroker::earliestFromSource(), CopyingDelaySlotFiller::fillDelaySlots(), BUBasicBlockScheduler::finalizeSchedule(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), CopyingDelaySlotFiller::findJumpImmediate(), ControlFlowGraph::findLimmWrite(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), DataDependenceGraphBuilder::findStaticRegisters(), DataDependenceGraph::firstRegisterCycle(), DataDependenceGraph::firstScheduledRegisterRead(), DataDependenceGraph::firstScheduledRegisterReads(), TTAProgram::Program::fixInstructionReferences(), DataDependenceGraph::fixInterBBAntiEdges(), CompiledSimCodeGenerator::generateAddFUResult(), CompiledSimCodeGenerator::generateInstruction(), ProgramImageGenerator::generateProgramImage(), ConstantAliasAnalyzer::getConstantAddress(), getInstructionReferenceTerminals(), CopyingDelaySlotFiller::getMove(), StackAliasAnalyzer::getStackOffset(), CallsToJumps::handleControlFlowGraph(), BasicBlockScheduler::handleDDG(), RFAccessTracker::handleEvent(), BUBasicBlockScheduler::handleLoopDDG(), CodeCompressorPlugin::immediateTerminal(), IUResource::immediateValue(), IUResource::immediateWriteCycle(), ControlFlowGraph::indirectJump(), RegisterRenamer::initializeFreeRegisters(), OffsetAliasAnalyzer::isAddressTraceable(), OutputPSocketBroker::isAnyResourceAvailable(), OutputPSocketBroker::isApplicable(), OutputFUBroker::isApplicable(), BusBroker::isAvailable(), isReturn(), MoveNode::isSourceReg(), BF2Scheduler::isSourceUniversalReg(), DataDependenceGraph::lastRegisterCycle(), DataDependenceGraph::lastScheduledRegisterRead(), DataDependenceGraph::lastScheduledRegisterReads(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), MoveNode::latestTriggerWriteCycle(), main(), DataDependenceGraph::mergeAndKeepSource(), DataDependenceGraph::mergeAndKeepUser(), BUMoveNodeSelector::mightBeReady(), CriticalPathBBMoveNodeSelector::mightBeReady(), LoopPrologAndEpilogBuilder::moveJumpDestination(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), BFLateBypassGuard::operator()(), BFRenameSource::operator()(), BFShareOperandLate::operator()(), BFShareOperandsLate::operator()(), BFShareOperandWithScheduled::operator()(), BFEarlyGuardBypass::operator()(), BFPostpassBypass::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), LoopPrologAndEpilogBuilder::optimizeProlog(), ProgramOperation::outputIndexOfMove(), BF2Scheduler::preAllocateFunctionUnits(), BF2ScheduleFront::prefResultCycle(), SimProgramBuilder::processMove(), DataDependenceGraphBuilder::processSource(), CycleLookBackSoftwareBypasser::removeDeadResults(), ControlFlowGraph::removeJumpToTarget(), ProgramOperation::removeOutputNode(), RegisterRenamer::renameLiveRange(), RegisterRenamer::renameSourceRegister(), TTAProgram::Program::replaceUniversalAddressSpaces(), ExecutionPipelineResource::resultPort(), BF2Scheduler::revertBBLiveRangeBookkeepingForSource(), BFOptimization::RFReadPortCountPreventsScheduling(), BFOptimization::rmEC(), BFOptimization::rmLC(), DataDependenceGraph::sanityCheck(), BasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperand(), BUBasicBlockScheduler::scheduleRRMove(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), ProgramOperation::setOperation(), BFOptimization::setPrologSrcFUAnno(), BFOptimization::sourceFU(), DataDependenceGraph::sourceRenamed(), TTAProgram::BasicBlock::statistics(), ExecutionPipelineResource::testTriggerResult(), PostpassOperandSharer::tryRemoveOperandWrite(), CopyingDelaySlotFiller::tryToAssignNodes(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveEq(), PreOptimizer::tryToRemoveGuardInversingOp(), PreOptimizer::tryToRemoveXor(), LoopAnalyzer::tryTrackCommonAncestor(), IUResource::unassign(), OutputFUBroker::unassign(), SimpleBrokerDirector::unassign(), BFCopyRegWithOp::undoSplit(), BFRegCopyBefore::undoSplit(), DataDependenceGraph::unMergeUser(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), BFMergeAndKeepUser::updateEdges(), BasicBlockNode::updateHWloopLength(), and CopyingDelaySlotFiller::updateJumpsAndCfg().
sourceFileName()
std::string TTAProgram::Move::sourceFileName () const
Returns one source code filename for this move.
Returns "" if no source code line info has been set.
Definition at line 488 of file Move.cc.
{
    std::string fileName = "";
    const TTAProgram::ProgramAnnotation::Id id =
        TTAProgram::ProgramAnnotation::ANN_DEBUG_SOURCE_CODE_PATH;
    if (hasAnnotations(id)) {
        fileName=annotation(0,id).stringValue();
    }
    return fileName;
}
References TTAProgram::ProgramAnnotation::ANN_DEBUG_SOURCE_CODE_PATH, TTAProgram::AnnotatedInstructionElement::annotation(), TTAProgram::AnnotatedInstructionElement::hasAnnotations(), and TTAProgram::ProgramAnnotation::stringValue().
Referenced by POMDisassembler::disassemble(), hasSourceFileName(), ProximDebuggerWindow::loadProgram(), and ProximDebuggerWindow::updateAnnotations().
sourceLineNumber()
int TTAProgram::Move::sourceLineNumber () const
Returns one source code line number for this move.
There can be at most two source code line numbers associated to a move in case it's bypassed. This method returns the smaller of them.
Returns -1 if no source code line info has been set.
Definition at line 459 of file Move.cc.
{
    int lineNumber =  -1;
    const TTAProgram::ProgramAnnotation::Id id =
        TTAProgram::ProgramAnnotation::ANN_DEBUG_SOURCE_CODE_LINE;
    if (hasAnnotations(id)) {
        lineNumber = INT_MAX;
        for (int i = 0; i < annotationCount(id); ++i) {
            lineNumber = std::min(lineNumber, annotation(i, id).intValue());
        }
    }
    return lineNumber;
}
References TTAProgram::ProgramAnnotation::ANN_DEBUG_SOURCE_CODE_LINE, TTAProgram::AnnotatedInstructionElement::annotation(), TTAProgram::AnnotatedInstructionElement::annotationCount(), and TTAProgram::AnnotatedInstructionElement::hasAnnotations().
Referenced by PRegionAliasAnalyzer::analyze(), POMDisassembler::disassemble(), DataDependenceGraph::dotString(), hasSourceLineNumber(), BasicBlockNode::toString(), and ProximDebuggerWindow::updateAnnotations().
sourceSocket()
Socket & TTAProgram::Move::sourceSocket () const
Definition at line 393 of file Move.cc.
{
    if (src_->isImmediate()) {
        throw WrongSubclass(
            __FILE__, __LINE__, "Move::sourceSocket()",
            "Move source is an immediate.");
    } else {
        return *src_->port().outputSocket();
    }
}
References TTAProgram::Terminal::isImmediate(), TTAMachine::Port::outputSocket(), TTAProgram::Terminal::port(), and src_.
Referenced by SimpleICOptimizer::addConnections(), and UtilizationStats::calculateForInstruction().
toString()
std::string TTAProgram::Move::toString () const
Returns the disassembly of the move.
Definition at line 436 of file Move.cc.
                     {
    return POMDisassembler::disassemble(*this);
}
References POMDisassembler::disassemble().
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), llvm::LLVMTCEBuilder::addPointerAnnotations(), ResourceConstraintAnalyzer::analyze(), PRegionAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), MoveNodeGroupBuilder::build(), FindWindow::find(), CallsToJumps::handleControlFlowGraph(), BasicBlockScheduler::handleRemovedResultMoves(), SimProgramBuilder::processMove(), DataDependenceGraphBuilder::processResultRead(), BFRescheduleMove::undoOnlyMe(), and BasicBlockNode::updateHWloopLength().
Member Data Documentation
bus_
const TTAMachine::Bus* TTAProgram::Move::bus_ private
The bus where the transport is carried.
Definition at line 112 of file Move.hh.
Referenced by bus(), copy(), and setBus().
dst_
Terminal* TTAProgram::Move::dst_ private
The destination of the move.
Definition at line 110 of file Move.hh.
Referenced by copy(), destination(), destinationSocket(), isCall(), isControlFlowMove(), isJump(), isTriggering(), setDestination(), and ~Move().
guard_
MoveGuard* TTAProgram::Move::guard_ private
The boolean expression that predicates the move.
Definition at line 114 of file Move.hh.
Referenced by copy(), guard(), isUnconditional(), setGuard(), and ~Move().
parent_
Instruction* TTAProgram::Move::parent_ private
Parent instruction of the move.
Definition at line 106 of file Move.hh.
Referenced by isInInstruction(), parent(), and setParent().
src_
Terminal* TTAProgram::Move::src_ private
The source of the move.
Definition at line 108 of file Move.hh.
Referenced by copy(), setSource(), source(), sourceSocket(), and ~Move().
The documentation for this class was generated from the following files:
Move.hh
Move.cc