OpenASIP: ControlDependenceEdge Class Reference
ControlDependenceEdge Class Reference
#include <ControlDependenceEdge.hh>
Public Types
enum CDGEdgeType { CDEP_EDGE_NORMAL , CDEP_EDGE_TRUE , CDEP_EDGE_FALSE , CDEP_EDGE_LOOPCLOSE }
Public Member Functions
ControlDependenceEdge (CDGEdgeType edgeType=CDEP_EDGE_NORMAL)
virtual ~ControlDependenceEdge ()
TCEString toString () const
bool isNormalEdge () const
bool isTrueEdge () const
bool isFalseEdge () const
bool isLoopCloseEdge () const
CDGEdgeType edgeType () const
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual GraphEdge * clone () const
virtual ~GraphEdge ()
virtual int edgeID () const
virtual TCEString dotString () const
virtual bool isBackEdge () const
int weight () const
void setWeight (int w)
Protected Member Functions
void invertEdgePredicate ()
Private Attributes
CDGEdgeType edgeType_
Friends
class ProgramDependenceGraph
Detailed Description
Edge of the control dependence graph (control dependence edge). Each edge implies control dependency.
Definition at line 44 of file ControlDependenceEdge.hh.
Member Enumeration Documentation
CDGEdgeType
enum ControlDependenceEdge::CDGEdgeType
Enumerator
CDEP_EDGE_NORMAL
CDEP_EDGE_TRUE
CDEP_EDGE_FALSE
CDEP_EDGE_LOOPCLOSE
Definition at line 47 of file ControlDependenceEdge.hh.
                     {
        CDEP_EDGE_NORMAL,
        CDEP_EDGE_TRUE,
        CDEP_EDGE_FALSE,
        CDEP_EDGE_LOOPCLOSE};
Constructor & Destructor Documentation
ControlDependenceEdge()
ControlDependenceEdge::ControlDependenceEdge (CDGEdgeType edgeType = CDEP_EDGE_NORMAL) inline
Definition at line 53 of file ControlDependenceEdge.hh.
                                                 :
        edgeType_(edgeType) {}
~ControlDependenceEdge()
ControlDependenceEdge::~ControlDependenceEdge () virtual
Definition at line 37 of file ControlDependenceEdge.cc.
{}
Member Function Documentation
edgeType()
CDGEdgeType ControlDependenceEdge::edgeType () const inline
Definition at line 64 of file ControlDependenceEdge.hh.
{ return edgeType_; }
References edgeType_.
invertEdgePredicate()
void ControlDependenceEdge::invertEdgePredicate () protected
Inverts the predicate of the edge
Todo:
this should be handled better, after the ownership of CDG is moved into the PDG or so
Definition at line 64 of file ControlDependenceEdge.cc.
{
    if (isNormalEdge()) {
        return;
    }
    if (isTrueEdge()) {
        edgeType_ = CDEP_EDGE_FALSE;
    } else {
        edgeType_ = CDEP_EDGE_TRUE;
    }
}
References CDEP_EDGE_FALSE, CDEP_EDGE_TRUE, edgeType_, isNormalEdge(), and isTrueEdge().
Referenced by ProgramDependenceGraph::removeGuardedJump().
isFalseEdge()
bool ControlDependenceEdge::isFalseEdge () const inline
Definition at line 62 of file ControlDependenceEdge.hh.
{ return edgeType_ == CDEP_EDGE_FALSE; }
References CDEP_EDGE_FALSE, and edgeType_.
Referenced by ProgramDependenceEdge::dotString(), ControlDependenceGraph::eliminateMultipleOutputs(), and toString().
isLoopCloseEdge()
bool ControlDependenceEdge::isLoopCloseEdge () const inline
Definition at line 63 of file ControlDependenceEdge.hh.
{ return edgeType_ == CDEP_EDGE_LOOPCLOSE;}
References CDEP_EDGE_LOOPCLOSE, and edgeType_.
Referenced by ProgramDependenceEdge::ProgramDependenceEdge(), and toString().
isNormalEdge()
bool ControlDependenceEdge::isNormalEdge () const inline
Definition at line 60 of file ControlDependenceEdge.hh.
{ return edgeType_ == CDEP_EDGE_NORMAL; }
References CDEP_EDGE_NORMAL, and edgeType_.
Referenced by invertEdgePredicate().
isTrueEdge()
bool ControlDependenceEdge::isTrueEdge () const inline
Definition at line 61 of file ControlDependenceEdge.hh.
{ return edgeType_ == CDEP_EDGE_TRUE; }
References CDEP_EDGE_TRUE, and edgeType_.
Referenced by ProgramDependenceEdge::dotString(), ControlDependenceGraph::eliminateMultipleOutputs(), invertEdgePredicate(), and toString().
toString()
TCEString ControlDependenceEdge::toString () const virtual
Returns a predicate of edge as string.
Returns
The value of edge - true, false, neutral
Reimplemented from GraphEdge.
Definition at line 44 of file ControlDependenceEdge.cc.
{
    TCEString label = "";
    if (isTrueEdge()) {
        label += "True";
    }
    if (isFalseEdge()) {
        label += "False";
    }
    if (isLoopCloseEdge()) {
        label += "Close";
    }
    return label;
}
References isFalseEdge(), isLoopCloseEdge(), and isTrueEdge().
Referenced by ProgramDependenceEdge::toString().
Friends And Related Symbol Documentation
ProgramDependenceGraph
friend class ProgramDependenceGraph friend
Definition at line 46 of file ControlDependenceEdge.hh.
Member Data Documentation
edgeType_
CDGEdgeType ControlDependenceEdge::edgeType_ private
Definition at line 69 of file ControlDependenceEdge.hh.
Referenced by edgeType(), invertEdgePredicate(), isFalseEdge(), isLoopCloseEdge(), isNormalEdge(), and isTrueEdge().
The documentation for this class was generated from the following files:
ControlDependenceEdge.hh
ControlDependenceEdge.cc