OpenASIP: HDLGenerator::Generatable Class Reference
HDLGenerator::Generatable Class Reference
#include <Generatable.hh>
Public Member Functions
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang, int indent)
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::string name_
Generatable * parent_
std::vector< std::shared_ptr< Generatable > > components_
Detailed Description
Base class for all generatable classes.
Definition at line 51 of file Generatable.hh.
Constructor & Destructor Documentation
Generatable()
HDLGenerator::Generatable::Generatable (std::string name) inline
Definition at line 53 of file Generatable.hh.
: name_(name), parent_(nullptr) {}
~Generatable()
virtual HDLGenerator::Generatable::~Generatable () virtual default
Member Function Documentation
addComponent()
template<class Component > void HDLGenerator::Generatable::addComponent (Component c) inline
Definition at line 235 of file Generatable.hh.
{
            components_.push_back(std::make_shared<Component>(c));
        }
References components_.
Referenced by HDLGenerator::Switch::addCase(), HDLGenerator::Switch::addCase(), HDLGenerator::Behaviour::operator<<(), HDLGenerator::Behaviour::operator<<(), HDLGenerator::Behaviour::operator<<(), HDLGenerator::DefaultCase::operator<<(), HDLGenerator::DefaultCase::operator<<(), HDLGenerator::Behaviour::operator<<(), HDLGenerator::Behaviour::operator<<(), HDLGenerator::Behaviour::operator<<(), and HDLGenerator::Behaviour::operator<<().
build()
virtual void HDLGenerator::Generatable::build () inline virtual
Reimplemented in HDLGenerator::Module, HDLGenerator::HDLOperation, HDLGenerator::Assign, HDLGenerator::Switch, HDLGenerator::If, HDLGenerator::Asynchronous, and HDLGenerator::Synchronous.
Definition at line 56 of file Generatable.hh.
{
            forAll([this](std::shared_ptr<Generatable> c) {
                c->setParent(this);
                c->build();
            });
        }
References forAll().
Referenced by HDLGenerator::HDLOperation::build(), HDLGenerator::Assign::build(), HDLGenerator::Switch::build(), HDLGenerator::If::build(), HDLGenerator::Asynchronous::build(), and HDLGenerator::Synchronous::build().
forAll() [1/2]
template<typename Func > void HDLGenerator::Generatable::forAll (Func func) inline
Definition at line 195 of file Generatable.hh.
{
            for (auto&& c : components_) {
                func(c);
            }
        }
References components_.
Referenced by HDLGenerator::Behaviour::behaviour(), build(), implementAll(), and implementAll().
forAll() [2/2]
template<typename Type , typename Func > void HDLGenerator::Generatable::forAll (Func func) inline
Definition at line 201 of file Generatable.hh.
{
            for (auto&& c : components_) {
                Type* ptr = dynamic_cast<Type*>(c.get());
                if (ptr != nullptr)
                    func(ptr);
            }
        }
References components_.
getRegister()
virtual Register & HDLGenerator::Generatable::getRegister (const std::string & var) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 89 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name();
                throw std::runtime_error(err.c_str());
            }
            return parent()->getRegister(var);
        }
References getRegister(), name(), and parent().
Referenced by getRegister(), HDLGenerator::Synchronous::hdl(), and HDLGenerator::Synchronous::vhdlReset().
hasOption()
virtual bool HDLGenerator::Generatable::hasOption (const std::string & var) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 98 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name();
                throw std::runtime_error(err.c_str());
            }
            return parent()->hasOption(var);
        }
References hasOption(), name(), and parent().
Referenced by hasOption(), HDLGenerator::Synchronous::hdl(), and HDLGenerator::Synchronous::vhdlReset().
hdl() [1/2]
virtual void HDLGenerator::Generatable::hdl (std::ostream & stream, Language lang) inline virtual
Definition at line 178 of file Generatable.hh.
{
            (void)lang;
            stream << name();
        }
References name().
hdl() [2/2]
virtual void HDLGenerator::Generatable::hdl (std::ostream & stream, Language lang, int indent) inline virtual
Reimplemented in HDLGenerator::SequentialStatement, HDLGenerator::RawCodeLine, HDLGenerator::NewLine, HDLGenerator::HDLOperation, HDLGenerator::DefaultAssign, HDLGenerator::Assign, HDLGenerator::DefaultCase, HDLGenerator::Case, HDLGenerator::Switch, HDLGenerator::If, HDLGenerator::CodeBlock, HDLGenerator::Asynchronous, and HDLGenerator::Synchronous.
Definition at line 170 of file Generatable.hh.
{
            (void)stream;
            (void)lang;
            (void)indent;
            std::string err = std::string("Attempted to generate ") + name_;
            throw std::runtime_error(err);
        }
References name_.
implementAll() [1/2]
virtual void HDLGenerator::Generatable::implementAll (std::ostream & stream, Language lang) inline virtual
Definition at line 183 of file Generatable.hh.
{
            forAll([&](
                std::shared_ptr<Generatable> c) { c->hdl(stream, lang); });
        }
References forAll().
Referenced by HDLGenerator::DefaultCase::hdl(), HDLGenerator::Case::hdl(), HDLGenerator::Switch::hdl(), HDLGenerator::CodeBlock::hdl(), HDLGenerator::Asynchronous::hdl(), and HDLGenerator::Synchronous::hdl().
implementAll() [2/2]
virtual void HDLGenerator::Generatable::implementAll (std::ostream & stream, Language lang, int indent) inline virtual
Definition at line 189 of file Generatable.hh.
{
            forAll([&](std::shared_ptr<Generatable> c) {
                c->hdl(stream, lang, indent);
            });
        }
References forAll().
integerWidth()
int HDLGenerator::Generatable::integerWidth (const std::string & name) inline
Definition at line 143 of file Generatable.hh.
{
            int intWidth = width(name).intWidth;
            if (intWidth == -1) {
                std::string err = name_
                    + std::string(" does not have an integer width value.");
                throw std::runtime_error(err.c_str());
            }
            return intWidth;
        }
References HDLGenerator::Width::intWidth, name(), name_, and width().
isConstant()
virtual bool HDLGenerator::Generatable::isConstant (const std::string & name) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 125 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name_;
                throw std::runtime_error(err.c_str());
            }
            return parent()->isConstant(name);
        }
References isConstant(), name(), name_, and parent().
Referenced by HDLGenerator::Asynchronous::hdl(), and isConstant().
isRegister()
virtual bool HDLGenerator::Generatable::isRegister (const std::string & name) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 107 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name_;
                throw std::runtime_error(err.c_str());
            }
            return parent()->isRegister(name);
        }
References isRegister(), name(), name_, and parent().
Referenced by HDLGenerator::Synchronous::build(), HDLGenerator::Assign::hdl(), isRegister(), and HDLGenerator::Synchronous::writes().
isVariable()
virtual bool HDLGenerator::Generatable::isVariable (const std::string & name) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 116 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name_;
                throw std::runtime_error(err.c_str());
            }
            return parent()->isVariable(name);
        }
References isVariable(), name(), name_, and parent().
Referenced by HDLGenerator::DefaultAssign::hdl(), HDLGenerator::Assign::hdl(), isVariable(), and HDLGenerator::Synchronous::writes().
name()
const std::string & HDLGenerator::Generatable::name () const inline noexcept
Definition at line 239 of file Generatable.hh.
{ return name_; }
References name_.
Referenced by HDLGenerator::Assign::build(), FUGen::createImplementationFiles(), HDLGenerator::Wire::declare(), HDLGenerator::BinaryConstant::declare(), HDLGenerator::IntegerConstant::declare(), HDLGenerator::Variable::declare(), HDLGenerator::Module::declare(), HDLGenerator::Parameter::declare(), getRegister(), hasOption(), hdl(), HDLGenerator::DefaultAssign::hdl(), HDLGenerator::Assign::hdl(), HDLGenerator::Asynchronous::hdl(), HDLGenerator::Synchronous::hdl(), HDLGenerator::Module::implement(), HDLGenerator::Module::instantiate(), integerWidth(), isConstant(), HDLGenerator::Module::isConstant(), isRegister(), HDLGenerator::Module::isRegister(), isVariable(), HDLGenerator::Module::isVariable(), HDLGenerator::Module::Module(), reads(), HDLGenerator::Parameter::width(), HDLGenerator::BinaryConstant::width(), HDLGenerator::IntegerConstant::width(), width(), HDLGenerator::Module::width(), wireType(), HDLGenerator::Module::wireType(), and writes().
parent()
Generatable * HDLGenerator::Generatable::parent () const inline noexcept
Definition at line 242 of file Generatable.hh.
{ return parent_; }
References parent_.
Referenced by getRegister(), hasOption(), isConstant(), isRegister(), isVariable(), parentIs(), parentType(), reads(), HDLGenerator::Asynchronous::reads(), setParent(), width(), wireType(), and writes().
parentIs()
template<class Type > bool HDLGenerator::Generatable::parentIs () inline
Definition at line 209 of file Generatable.hh.
{
            if (parent() == nullptr) {
                return false;
            } else if (dynamic_cast<Type*>(parent()) != nullptr) {
                return true;
            } else {
                return parent()->parentIs<Type>();
            }
        }
References parent(), and parentIs().
Referenced by parentIs().
parentType()
template<class Type > Type * HDLGenerator::Generatable::parentType () inline
Definition at line 219 of file Generatable.hh.
{
            if (parent() == nullptr) {
                throw std::runtime_error("Couldn't find parent'");
            } else if (dynamic_cast<Type*>(parent()) != nullptr) {
                return dynamic_cast<Type*>(parent());
            } else {
                return parent()->parentType<Type>();
            }
        }
References parent(), and parentType().
Referenced by parentType().
pushComponent()
void HDLGenerator::Generatable::pushComponent (std::shared_ptr< Generatable > c) inline
Definition at line 230 of file Generatable.hh.
{
            components_.push_back(c);
        }
References components_.
Referenced by HDLGenerator::CodeBlock::append(), HDLGenerator::Case::operator<<(), HDLGenerator::Asynchronous::operator<<(), and HDLGenerator::Synchronous::operator<<().
reads() [1/2]
virtual void HDLGenerator::Generatable::reads (const LHSValue & var) inline virtual
Definition at line 72 of file Generatable.hh.
{
            std::unordered_set<std::string> readList;
            var.writeSignals(readList);
            for (auto&& r : readList) {
                reads(r);
            }
        }
References reads(), and HDLGenerator::LHSValue::writeSignals().
reads() [2/2]
virtual void HDLGenerator::Generatable::reads (const std::string & var) inline virtual
Reimplemented in HDLGenerator::Module, and HDLGenerator::Asynchronous.
Definition at line 63 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name();
                throw std::runtime_error(err.c_str());
            }
            parent()->reads(var);
        }
References name(), parent(), and reads().
Referenced by HDLGenerator::HDLOperation::build(), HDLGenerator::Assign::build(), HDLGenerator::Switch::build(), HDLGenerator::If::build(), reads(), reads(), and HDLGenerator::Asynchronous::reads().
setParent()
void HDLGenerator::Generatable::setParent (Generatable * parent) inline noexcept
Definition at line 241 of file Generatable.hh.
{ parent_ = parent; }
References parent(), and parent_.
width() [1/2]
virtual Width HDLGenerator::Generatable::width () inline virtual
Reimplemented in HDLGenerator::Parameter, HDLGenerator::BinaryConstant, HDLGenerator::IntegerConstant, HDLGenerator::Wire, and HDLGenerator::Variable.
Definition at line 162 of file Generatable.hh.
{
            throw std::runtime_error("Shouldn't be here!");
        }
Referenced by HDLGenerator::DefaultAssign::hdl(), and integerWidth().
width() [2/2]
virtual Width HDLGenerator::Generatable::width (const std::string & name) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 134 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name_;
                throw std::runtime_error(err.c_str());
            }
            return parent()->width(name);
        }
References name(), name_, parent(), and width().
Referenced by width().
wireType() [1/2]
virtual WireType HDLGenerator::Generatable::wireType () const inline virtual
Reimplemented in HDLGenerator::Wire.
Definition at line 166 of file Generatable.hh.
{
            throw std::runtime_error("Shouldn't be here!");
        }
Referenced by HDLGenerator::DefaultAssign::hdl().
wireType() [2/2]
virtual WireType HDLGenerator::Generatable::wireType (const std::string & name) inline virtual
Reimplemented in HDLGenerator::Module.
Definition at line 153 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name_;
                throw std::runtime_error(err.c_str());
            }
            return parent()->wireType(name);
        }
References name(), name_, parent(), and wireType().
Referenced by wireType().
writes()
virtual void HDLGenerator::Generatable::writes (const std::string & var) inline virtual
Reimplemented in HDLGenerator::Module, and HDLGenerator::Synchronous.
Definition at line 80 of file Generatable.hh.
{
            if (parent() == nullptr) {
                std::string err =
                    std::string("Couldn't find parent for ") + name();
                throw std::runtime_error(err.c_str());
            }
            parent()->writes(var);
        }
References name(), parent(), and writes().
Referenced by HDLGenerator::Assign::build(), and writes().
Member Data Documentation
components_
std::vector<std::shared_ptr<Generatable> > HDLGenerator::Generatable::components_ private
Definition at line 247 of file Generatable.hh.
Referenced by addComponent(), forAll(), and pushComponent().
name_
std::string HDLGenerator::Generatable::name_ private
Definition at line 245 of file Generatable.hh.
Referenced by hdl(), integerWidth(), isConstant(), isRegister(), isVariable(), name(), width(), and wireType().
parent_
Generatable* HDLGenerator::Generatable::parent_ private
Definition at line 246 of file Generatable.hh.
Referenced by parent(), and setParent().
The documentation for this class was generated from the following file:
Generatable.hh