OpenASIP: TPEF::ReferenceManager::SafePointerList Class Reference
TPEF::ReferenceManager::SafePointerList Class Reference
#include <SafePointer.hh>
Public Types
typedef std::list< SafePointer * > SafePointerListType
Type of the container to hold the SafePointers in.
typedef std::string::size_type LengthType
Type of the list length value.
Public Member Functions
SafePointerList ()
SafePointerList (SafePointerList &aList)
virtual ~SafePointerList ()
void setReference (const SafePointable *obj)
SafePointable * reference () const
void append (SafePointer *newSafePointer)
void append (SafePointerList *anotherSafePointerList)
SafePointer * front () const
void cleanup ()
void cleanupDead ()
LengthType length () const
Private Attributes
SafePointable * reference_
Object that SafePointers in this list are pointing to.
SafePointerListType list_
Container for SafePointers.
Detailed Description
List of SafePointers that are all pointing to the same object.
Definition at line 71 of file SafePointer.hh.
Member Typedef Documentation
LengthType
typedef std::string::size_type TPEF::ReferenceManager::SafePointerList::LengthType
Type of the list length value.
Definition at line 77 of file SafePointer.hh.
SafePointerListType
typedef std::list<SafePointer*> TPEF::ReferenceManager::SafePointerList::SafePointerListType
Type of the container to hold the SafePointers in.
Definition at line 74 of file SafePointer.hh.
Constructor & Destructor Documentation
SafePointerList() [1/2]
TPEF::ReferenceManager::SafePointerList::SafePointerList ()
Constructor.
Definition at line 82 of file SafePointer.cc.
                                 : reference_(NULL) {
}
SafePointerList() [2/2]
TPEF::ReferenceManager::SafePointerList::SafePointerList (SafePointerList & aList)
Copy constructor.
Definition at line 89 of file SafePointer.cc.
                                                       :
    reference_(aList.reference_) {
    for (SafePointerListType::iterator i = aList.list_.begin();
         i != aList.list_.end(); i++) {
        list_.push_back(*i);
    }
}
References list_.
~SafePointerList()
TPEF::ReferenceManager::SafePointerList::~SafePointerList () virtual
Destructor.
Definition at line 103 of file SafePointer.cc.
{
}
Member Function Documentation
append() [1/2]
void TPEF::ReferenceManager::SafePointerList::append (SafePointer * newSafePointer)
Appends a new SafePointer at the end of the list and sets it's reference to the reference of the list.
Parameters
newSafePointer The SafePointer to add.
Definition at line 132 of file SafePointer.cc.
{
    newSafePointer->setPointer(reference());
    list_.push_back(newSafePointer);
}
References list_, reference(), and TPEF::ReferenceManager::SafePointer::setPointer().
append() [2/2]
void TPEF::ReferenceManager::SafePointerList::append (SafePointerList * anotherSafePointerList)
Appends another SafePointerList at the end of the list and sets it's reference to the reference of the list.
Parameters
anotherSafePointerList The SafePointerList to add.
Definition at line 145 of file SafePointer.cc.
{
    if (anotherSafePointerList == NULL) {
        return;
    }
    anotherSafePointerList->setReference(reference());
    insert_iterator<SafePointerListType> ii(list_,
                                            list_.end());
    copy(anotherSafePointerList->list_.begin(),
         anotherSafePointerList->list_.end(), ii);
}
References list_, reference(), and setReference().
cleanup()
void TPEF::ReferenceManager::SafePointerList::cleanup ()
Sets all SafePointers in the list NULL and clears the list.
Definition at line 164 of file SafePointer.cc.
{
    setReference(NULL);
    list_.clear();
}
References list_, and setReference().
Referenced by TPEF::ReferenceManager::SafePointer::notifyDeleted().
cleanupDead()
void TPEF::ReferenceManager::SafePointerList::cleanupDead ()
Removes all dead (deleted) SafePointers from the list.
Definition at line 173 of file SafePointer.cc.
{
    for (SafePointerListType::iterator i = list_.begin();
         i != list_.end();) {
        if (!SafePointer::isAlive((*i))) {
            i = list_.erase(i);
        } else {
            ++i;
        }
    }
}
References TPEF::ReferenceManager::SafePointer::isAlive(), and list_.
Referenced by TPEF::ReferenceManager::SafePointer::isReferenced().
front()
SafePointer * TPEF::ReferenceManager::SafePointerList::front () const
Referenced by TPEF::ReferenceManager::SafePointer::resolve().
length()
LengthType TPEF::ReferenceManager::SafePointerList::length () const
Referenced by TPEF::ReferenceManager::SafePointer::isReferenced().
reference()
SafePointable * TPEF::ReferenceManager::SafePointerList::reference () const
Referenced by append(), append(), and TPEF::ReferenceManager::SafePointer::resolve().
setReference()
void TPEF::ReferenceManager::SafePointerList::setReference (const SafePointable * obj)
Sets the object all SafePointers in the list are pointing to.
Parameters
obj The pointer to the object all SafePointers in the list should be pointing to.
Definition at line 113 of file SafePointer.cc.
{
    reference_ = const_cast<SafePointable*>(obj);
    for (SafePointerListType::iterator i = list_.begin();
         i != list_.end(); i++) {
        if (SafePointer::isAlive((*i))) {
            (*i)->setPointer(reference_);
        }
    }
}
References TPEF::ReferenceManager::SafePointer::isAlive(), list_, and reference_.
Referenced by append(), and cleanup().
Member Data Documentation
list_
SafePointerListType TPEF::ReferenceManager::SafePointerList::list_ private
Container for SafePointers.
Definition at line 102 of file SafePointer.hh.
Referenced by append(), append(), cleanup(), cleanupDead(), SafePointerList(), and setReference().
reference_
SafePointable* TPEF::ReferenceManager::SafePointerList::reference_ private
Object that SafePointers in this list are pointing to.
Definition at line 99 of file SafePointer.hh.
Referenced by setReference().
The documentation for this class was generated from the following files:
SafePointer.hh
SafePointer.cc