OpenASIP: TPEF::DataSymElement Class Reference
TPEF::DataSymElement Class Reference
#include <DataSymElement.hh>
Public Member Functions
DataSymElement ()
virtual ~DataSymElement ()
virtual SymbolType type () const
Chunk * reference () const
void setReference (Chunk *aReference)
void setReference (const ReferenceManager::SafePointer *aReference)
Word size () const
void setSize (Word aSize)
Public Member Functions inherited from TPEF::SymbolElement
SymbolElement ()
virtual ~SymbolElement ()
bool absolute () const
void setAbsolute (bool anAbsoluteness)
SymbolBinding binding () const
void setBinding (SymbolBinding aBinding)
Chunk * name () const
void setName (Chunk *aName)
void setName (const ReferenceManager::SafePointer *aName)
Section * section () const
void setSection (Section *aSect)
void setSection (const ReferenceManager::SafePointer *aSect)
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * reference_
Referred object.
Word size_
Size of referred object in MAUs.
Additional Inherited Members
Public Types inherited from TPEF::SymbolElement
enum SymbolBinding { STB_LOCAL = 0x0 , STB_GLOBAL = 0x1 , STB_WEAK = 0x2 }
Binding types of symbol.
enum SymbolType {
STT_NOTYPE = 0x0 , STT_DATA = 0x1 , STT_CODE = 0x2 , STT_SECTION = 0x3 ,
STT_FILE = 0x4 , STT_PROCEDURE = 0x5
}
Type of symbol element.
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Definition at line 41 of file DataSymElement.hh.
Constructor & Destructor Documentation
DataSymElement()
TPEF::DataSymElement::DataSymElement ()
Constructor.
Definition at line 43 of file DataSymElement.cc.
                               :
    SymbolElement(),
    reference_(&SafePointer::null),
    size_(0) {
}
~DataSymElement()
TPEF::DataSymElement::~DataSymElement () virtual
Destructor.
Definition at line 52 of file DataSymElement.cc.
{
}
Member Function Documentation
reference()
Chunk * TPEF::DataSymElement::reference () const
Returns object which element refers.
Returns
object which element refers.
Definition at line 71 of file DataSymElement.cc.
{
    return dynamic_cast<Chunk*>(reference_->pointer());
}
References TPEF::ReferenceManager::SafePointer::pointer(), and reference_.
Referenced by TTAProgram::TPEFProgramFactory::createLabels(), TPEFDumper::section(), and TPEF::TPEFSymbolSectionWriter::writeValueAndSize().
setReference() [1/2]
void TPEF::DataSymElement::setReference (Chunk * aReference)
Sets object which element refers.
Parameters
aReference Object which element refers.
Definition at line 81 of file DataSymElement.cc.
{
    reference_ = SafePointer::replaceReference(reference_, aReference);
}
References reference_, and TPEF::ReferenceManager::SafePointer::replaceReference().
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::createSymbolWithReference(), and TPEF::AOutSymbolSectionReader::initializeSymbol().
setReference() [2/2]
void TPEF::DataSymElement::setReference (const ReferenceManager::SafePointer * aReference)
Sets object which element refers.
Parameters
aReference Object which element refers.
Definition at line 91 of file DataSymElement.cc.
{
    reference_ = aReference;
}
References reference_.
setSize()
void TPEF::DataSymElement::setSize (Word aSize)
Sets size of referred object in MAUs.
Parameters
aSize of the referred object in MAUs.
Definition at line 112 of file DataSymElement.cc.
{
    size_ = aSize;
}
References size_.
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol().
size()
Word TPEF::DataSymElement::size () const
Returns size of the referred object in MAUs.
Returns
Size of the referred object in MAUs.
Definition at line 102 of file DataSymElement.cc.
{
    return size_;
}
References size_.
Referenced by TPEF::TPEFSymbolSectionWriter::writeValueAndSize().
type()
SymbolElement::SymbolType TPEF::DataSymElement::type () const virtual
Returns type of the element.
Returns
Type of the element.
Implements TPEF::SymbolElement.
Definition at line 61 of file DataSymElement.cc.
{
    return STT_DATA;
}
References TPEF::SymbolElement::STT_DATA.
Member Data Documentation
reference_
const ReferenceManager::SafePointer* TPEF::DataSymElement::reference_ private
Referred object.
Definition at line 57 of file DataSymElement.hh.
Referenced by reference(), setReference(), and setReference().
size_
Word TPEF::DataSymElement::size_ private
Size of referred object in MAUs.
Definition at line 59 of file DataSymElement.hh.
Referenced by setSize(), and size().
The documentation for this class was generated from the following files:
DataSymElement.hh
DataSymElement.cc