OpenASIP: FrequencySweepExplorer Class Reference
FrequencySweepExplorer Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Frequency sweep algorithm.")
FrequencySweepExplorer ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual std::vector< RowID > explore (const RowID &startPointConfigurationID, const unsigned int &)
void readParameters ()
void openHDBs ()
bool fastEnough (const RowID &id, const int &freq, DSDBManager &dsdb)
DSDBManager::MachineConfiguration callPlugin (DesignSpaceExplorerPlugin *plugin, const RowID &arch, DSDBManager &dsdb)
Private Attributes
ComponentImplementationSelector selector_
Selector used by the plugin.
unsigned int startMHz_
unsigned int endMHz_
unsigned int stepMHz_
std::string icDec_
name of the ic decoder plugin for idf
std::string icDecHDB_
name of the hdb used by ic decoder
unsigned int superiority_
Superirity percentage for the GrowMachine plugin.
Static Private Attributes
static const int busCountDefault_ = 4
Default value of busCount_.
static const unsigned int immSlotBusIndexDefault_ = 0
static const int registerFileSizeDefault_ = 4
static const int maxNumberOfRegisterFilesDefault_ = 16
static const int rfReadPortsDefault_ = 1
static const int rfWritePortsDefault_ = 1
static const std::string startMHzPN_
static const std::string endMHzPN_
static const std::string stepMHzPN_
static const std::string icDecPN_
static const std::string icDecHDBPN_
static const std::string superiorityPN_
static const std::string talo
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual bool requiresApplication () const
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin for finding processor configurations that satisfy the runtime requirements with certain clock frequencies.
Sweeps the user-set allowed frequency range with the given steps and collects all configurations that are suitable for running the given applications in the given clock frequencies.
Uses all HDBs found in the HDB registry to create the configurations.
Supported parameters:
start_freq_mhz, lowest frequency in the swept range in MHz
end_freq_mhz, highest frequency in the range in MHz
step_freq_mhz, frequency step in MHz
ic_dec, name of the ic decoder plugin, default is DefaultICDecoder
ic_hdb, name of the HDB that is used in IC estimation
Definition at line 102 of file FrequencySweepExplorer.cc.
Constructor & Destructor Documentation
FrequencySweepExplorer()
FrequencySweepExplorer::FrequencySweepExplorer () inline private
Definition at line 105 of file FrequencySweepExplorer.cc.
                            : DesignSpaceExplorerPlugin(),
        icDec_("DefaultICDecoder"),
        icDecHDB_("asic_130nm_1.5V.hdb"),
        superiority_(10) {
        // compulsory parameters
        addParameter(startMHzPN_, UINT);
        addParameter(endMHzPN_, UINT);
        addParameter(stepMHzPN_, UINT);
        // parameters that have a default value
        addParameter(icDecPN_, STRING, false, icDec_);
        addParameter(icDecHDBPN_, STRING, false, icDecHDB_);
        addParameter(superiorityPN_, UINT, false,
                Conversion::toString(superiority_));
    }
References DesignSpaceExplorerPlugin::addParameter(), endMHzPN_, icDec_, icDecHDB_, icDecHDBPN_, icDecPN_, startMHzPN_, stepMHzPN_, STRING, superiority_, superiorityPN_, Conversion::toString(), and UINT.
Member Function Documentation
callPlugin()
DSDBManager::MachineConfiguration FrequencySweepExplorer::callPlugin (DesignSpaceExplorerPlugin * plugin, const RowID & arch, DSDBManager & dsdb) inline private
Calls an explorer plugin.
Parameters
plugin The plugin to be called.
arch Row id of the architechture to be passed to the plugin.
Returns
dsdb Design space database to be used.
Definition at line 393 of file FrequencySweepExplorer.cc.
{
        vector<RowID> resultConfs = plugin->explore(arch);
        DSDBManager::MachineConfiguration resultConf;
        if (resultConfs.size() == 1) {
            resultConf = dsdb.configuration(resultConfs.at(0));
        } else {
            throw InvalidData(
                __FILE__, __LINE__, __func__,
                (boost::format(
                    "%s failed to optimize "
                    "configuration %d. Possible bug in Optimizer,"
                    " Estimator or missing data from HDB."
                    ) % arch % plugin->name()).str());
        }
        if (Application::verboseLevel() > 2) {
            std::ostringstream msg(std::ostringstream::out);
            msg << plugin->name()
                << " plugin produced config: "
                << resultConfs.at(0) << endl;
            verboseLog(msg.str())
        }
        return resultConf;
    }
References __func__, DSDBManager::configuration(), DesignSpaceExplorerPlugin::explore(), DesignSpaceExplorerPlugin::name(), Application::verboseLevel(), and verboseLog.
Referenced by explore().
explore()
virtual std::vector< RowID > FrequencySweepExplorer::explore (const RowID & startPointConfigurationID, const unsigned int &) inline private virtual
Explores from the given start configuration.
Parameters
startPointConfigurationID Configuration ID to start the exploration from.
Returns
Returns a set of best found configuration IDs.
Todo:
Optimization of the instruction size not required for 1st version!
Todo:
Final optimization/tuning not required for 1st version!
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 136 of file FrequencySweepExplorer.cc.
{
        checkParameters();
        readParameters();
        openHDBs();
        std::vector<RowID> result;
        RowID startPointConfID = startPointConfigurationID;
        // other explorer plugins used
        DesignSpaceExplorerPlugin* icOptimizer =
            DesignSpaceExplorer::loadExplorerPlugin(
                    "SimpleICOptimizer", &db());
        DesignSpaceExplorerPlugin* minimizeMachine =
            DesignSpaceExplorer::loadExplorerPlugin(
                    "MinimizeMachine", &db());
        DesignSpaceExplorerPlugin* growMachine =
            DesignSpaceExplorer::loadExplorerPlugin(
                    "GrowMachine", &db());
        DSDBManager& dsdb = db();
        // Sweep is always done from the lowest frequency towards the highest
        // frequency.
        if (startMHz_ > endMHz_) {
            int tempMHz = startMHz_;
            startMHz_ = endMHz_;
            endMHz_ = tempMHz;
        }
        // helper for returning the stepped frequencies in order
        FrequencySweep sweeper(startMHz_, endMHz_, stepMHz_);
        // parameters for GrowMachine plugin
        growMachine->giveParameter("superiority", Conversion::toString(superiority_));
        // find new configurations by adding components until the cycle
        // count stops going down
        vector<RowID> cycleOptimizedConfs =
            growMachine->explore(startPointConfID);
        if (Application::verboseLevel() > 1) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "GrowMachine plugin produced initial configs: ";
            for (unsigned int i = 0; i < cycleOptimizedConfs.size(); ++i) {
                msg << cycleOptimizedConfs.at(i) << " ";
            }
            msg << endl;
            verboseLog(msg.str())
        }
        delete growMachine;
        growMachine = NULL;
        int currentFrequencyMHz = sweeper.nextFrequency();
        vector<RowID>::const_iterator archIter;
        while (currentFrequencyMHz != 0) {
            verboseLogC("Testing frequency: " + Conversion::toString(
                        currentFrequencyMHz), 3)
            /* Find the configurations that are fast enough for the
               real time requirements of the applications at the
               currently examined frequency. */
            for (archIter = cycleOptimizedConfs.begin();
                 archIter != cycleOptimizedConfs.end();
                 archIter++) {
                verboseLogC("Testing (fast enough) init config: " +
                        Conversion::toString(*archIter), 3)
                // if is fast enough for all apps
                if (fastEnough(*archIter, currentFrequencyMHz, dsdb)) {
                    verboseLogC("Calling minimize machine for init config: " +
                            Conversion::toString(*archIter), 3)
                    // calling MimimizeMachine plugin with confToMinimize
                    // (architer) and currentFrequencyMHz
                    minimizeMachine->giveParameter("frequency",
                            Conversion::toString(currentFrequencyMHz));
                    DSDBManager::MachineConfiguration minConf =
                        callPlugin(minimizeMachine, *archIter, dsdb);
                    // create implementation for configuration
                    RowID selectedConf = createImplementationAndStore(minConf,
                            currentFrequencyMHz, 0, true, icDec_, icDecHDB_);
                    verboseLogC("Implementation selection produced a config: "
                            + Conversion::toString(selectedConf), 3)
                    // check if component selection failed
                    if (selectedConf == 0) {
                        verboseLogC("Component selection failed for minimized"
                            " arch: " + Conversion::toString(
                                minConf.architectureID), 3)
                        continue;
                    }
                    // IC optimization with SimpleICOptimizer plugin
                    vector<RowID> icOptimizedResult =
                        icOptimizer->explore(selectedConf);
                    if (icOptimizedResult.size() == 1) {
                        if (Application::verboseLevel()) {
                            std::ostringstream msg(std::ostringstream::out);
                            msg << "Config " << icOptimizedResult.at(0)
                                << " created for frequency "
                                << currentFrequencyMHz << "." << endl;
                            verboseLogC(msg.str(), 1)
                        }
                        result.push_back(icOptimizedResult.at(0));
                    } else {
                        // simpleICOptimizer can make a machine not fully
                        // connected, and so, register file requirements can
                        // change. Meaning evaluating the machine can fail in
                        // the plugin.
                        verboseLogC("SimpleICOptimzer failed for arch: "
                            + Conversion::toString(selectedConf), 3)
                        continue;
                    }
                    /// @todo Optimization of the instruction size
                    /// not required for 1st version!
                    /// @todo Final optimization/tuning
                    /// not required for 1st version!
                } else {
                    verboseLogC("Init config was too slow.", 3)
                    // the architecture was too slow
                }
            }
            // advance to next frequency
            currentFrequencyMHz = sweeper.nextFrequency();
        }
        delete minimizeMachine;
        minimizeMachine = NULL;
        delete icOptimizer;
        icOptimizer = NULL;
        // Idea:
        // All results will be given to a result explorer that returns
        // the given number of best configuration id:s that can be returned
        // to the user.
        // BestResultExplorer resultExplorer(dsdb, explorer.results());
        // result = resultExplorer.find(5);
        return result;
    }
References DSDBManager::MachineConfiguration::architectureID, callPlugin(), DesignSpaceExplorerPlugin::checkParameters(), DesignSpaceExplorer::createImplementationAndStore(), DesignSpaceExplorer::db(), endMHz_, DesignSpaceExplorerPlugin::explore(), fastEnough(), DesignSpaceExplorerPlugin::giveParameter(), icDec_, icDecHDB_, DesignSpaceExplorer::loadExplorerPlugin(), FrequencySweep::nextFrequency(), openHDBs(), readParameters(), startMHz_, stepMHz_, superiority_, Conversion::toString(), Application::verboseLevel(), verboseLog, and verboseLogC.
fastEnough()
bool FrequencySweepExplorer::fastEnough (const RowID & id, const int & freq, DSDBManager & dsdb) inline private
Check if architecture is fast enough.
Parameters
id Row id of the architecture.
freq Frequency in MHz for testing the run time.
dsdb Desing Space Explorer database.
Definition at line 356 of file FrequencySweepExplorer.cc.
{
        set<RowID>::const_iterator applicationIter;
        set<RowID> applicationIDs = dsdb.applicationIDs();
        DSDBManager::MachineConfiguration configuration =
            dsdb.configuration(id);
        for (applicationIter = applicationIDs.begin();
                applicationIter != applicationIDs.end();
                applicationIter++) {
            ClockCycleCount cycleCount =
                dsdb.cycleCount(
                        *applicationIter, configuration.architectureID);
            TestApplication testApplication(
                    dsdb.applicationPath(*applicationIter));
            // test if application max runtime is set
            if (testApplication.maxRuntime() <= 0) {
                continue;
            }
            if ((static_cast<double>(cycleCount) / (static_cast<double>(freq) * static_cast<double>(1000000))) >
                    testApplication.maxRuntime()) {
                // we can skip this architecture since it won't
                // meet the speed requirements
                return false;
            }
        }
        return true;
    }
References DSDBManager::applicationIDs(), DSDBManager::applicationPath(), DSDBManager::MachineConfiguration::architectureID, DSDBManager::configuration(), DSDBManager::cycleCount(), and TestApplication::maxRuntime().
Referenced by explore().
openHDBs()
void FrequencySweepExplorer::openHDBs () inline private
Loads HDBs that are used into the registry.
Definition at line 339 of file FrequencySweepExplorer.cc.
                    {
        HDBRegistry& hdbRegistry = HDBRegistry::instance();
        // if HDBRegistry contains no HDBManagers load from default paths
        if (hdbRegistry.hdbCount() == 0) {
            hdbRegistry.loadFromSearchPaths();
        }
    }
References HDB::HDBRegistry::hdbCount(), HDB::HDBRegistry::instance(), and HDB::HDBRegistry::loadFromSearchPaths().
Referenced by explore().
PLUGIN_DESCRIPTION()
FrequencySweepExplorer::PLUGIN_DESCRIPTION ("Frequency sweep algorithm.") private
producesArchitecture()
virtual bool FrequencySweepExplorer::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 123 of file FrequencySweepExplorer.cc.
{ return false; }
readParameters()
void FrequencySweepExplorer::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 323 of file FrequencySweepExplorer.cc.
{
        // compulsory parameters
        readCompulsoryParameter(startMHzPN_, startMHz_);
        readCompulsoryParameter(endMHzPN_, endMHz_);
        readCompulsoryParameter(stepMHzPN_, stepMHz_);
        // optional parameters
        readOptionalParameter(icDecPN_, icDec_);
        readOptionalParameter(icDecHDBPN_, icDecHDB_);
        readOptionalParameter(superiorityPN_, superiority_);
    }
References endMHz_, endMHzPN_, icDec_, icDecHDB_, icDecHDBPN_, icDecPN_, DesignSpaceExplorerPlugin::readCompulsoryParameter(), DesignSpaceExplorerPlugin::readOptionalParameter(), startMHz_, startMHzPN_, stepMHz_, stepMHzPN_, superiority_, and superiorityPN_.
Referenced by explore().
requiresHDB()
virtual bool FrequencySweepExplorer::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 124 of file FrequencySweepExplorer.cc.
{ return true; }
requiresSimulationData()
virtual bool FrequencySweepExplorer::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 125 of file FrequencySweepExplorer.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool FrequencySweepExplorer::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 122 of file FrequencySweepExplorer.cc.
{ return true; }
Member Data Documentation
busCountDefault_
const int FrequencySweepExplorer::busCountDefault_ = 4 static private
Default value of busCount_.
Definition at line 288 of file FrequencySweepExplorer.cc.
endMHz_
unsigned int FrequencySweepExplorer::endMHz_ private
Definition at line 308 of file FrequencySweepExplorer.cc.
Referenced by explore(), and readParameters().
endMHzPN_
const std::string FrequencySweepExplorer::endMHzPN_ static private
Definition at line 299 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
icDec_
std::string FrequencySweepExplorer::icDec_ private
name of the ic decoder plugin for idf
Definition at line 312 of file FrequencySweepExplorer.cc.
Referenced by explore(), FrequencySweepExplorer(), and readParameters().
icDecHDB_
std::string FrequencySweepExplorer::icDecHDB_ private
name of the hdb used by ic decoder
Definition at line 314 of file FrequencySweepExplorer.cc.
Referenced by explore(), FrequencySweepExplorer(), and readParameters().
icDecHDBPN_
const std::string FrequencySweepExplorer::icDecHDBPN_ static private
Definition at line 303 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
icDecPN_
const std::string FrequencySweepExplorer::icDecPN_ static private
Definition at line 302 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
immSlotBusIndexDefault_
const unsigned int FrequencySweepExplorer::immSlotBusIndexDefault_ = 0 static private
Definition at line 290 of file FrequencySweepExplorer.cc.
maxNumberOfRegisterFilesDefault_
const int FrequencySweepExplorer::maxNumberOfRegisterFilesDefault_ = 16 static private
Definition at line 293 of file FrequencySweepExplorer.cc.
registerFileSizeDefault_
const int FrequencySweepExplorer::registerFileSizeDefault_ = 4 static private
Definition at line 292 of file FrequencySweepExplorer.cc.
rfReadPortsDefault_
const int FrequencySweepExplorer::rfReadPortsDefault_ = 1 static private
Definition at line 294 of file FrequencySweepExplorer.cc.
rfWritePortsDefault_
const int FrequencySweepExplorer::rfWritePortsDefault_ = 1 static private
Definition at line 295 of file FrequencySweepExplorer.cc.
selector_
ComponentImplementationSelector FrequencySweepExplorer::selector_ private
Selector used by the plugin.
Definition at line 286 of file FrequencySweepExplorer.cc.
startMHz_
unsigned int FrequencySweepExplorer::startMHz_ private
Definition at line 307 of file FrequencySweepExplorer.cc.
Referenced by explore(), and readParameters().
startMHzPN_
const std::string FrequencySweepExplorer::startMHzPN_ static private
Definition at line 298 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
stepMHz_
unsigned int FrequencySweepExplorer::stepMHz_ private
Definition at line 309 of file FrequencySweepExplorer.cc.
Referenced by explore(), and readParameters().
stepMHzPN_
const std::string FrequencySweepExplorer::stepMHzPN_ static private
Definition at line 300 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
superiority_
unsigned int FrequencySweepExplorer::superiority_ private
Superirity percentage for the GrowMachine plugin.
Definition at line 316 of file FrequencySweepExplorer.cc.
Referenced by explore(), FrequencySweepExplorer(), and readParameters().
superiorityPN_
const std::string FrequencySweepExplorer::superiorityPN_ static private
Definition at line 304 of file FrequencySweepExplorer.cc.
Referenced by FrequencySweepExplorer(), and readParameters().
talo
const std::string FrequencySweepExplorer::talo static private
Definition at line 318 of file FrequencySweepExplorer.cc.
The documentation for this class was generated from the following file:
FrequencySweepExplorer.cc