OpenASIP: TPEF::SectionSizeReplacer Class Reference
TPEF::SectionSizeReplacer Class Reference
#include <SectionSizeReplacer.hh>
Public Member Functions
SectionSizeReplacer (const SafePointable *obj)
virtual ~SectionSizeReplacer ()
Public Member Functions inherited from TPEF::ValueReplacer
void resolve ()
Static Public Member Functions
static void setSize (const SafePointable *obj, Word size)
static void clear ()
Static Public Member Functions inherited from TPEF::ValueReplacer
static void finalize ()
static void initialize (BinaryStream &stream)
Protected Member Functions
virtual bool tryToReplace ()
virtual ValueReplacer * clone ()
Protected Member Functions inherited from TPEF::ValueReplacer
ValueReplacer (const SafePointable *obj)
ValueReplacer (const ValueReplacer &replacer)
virtual ~ValueReplacer ()
const SafePointable * reference () const
unsigned int streamPosition () const
Private Member Functions
SectionSizeReplacer (const SectionSizeReplacer &replacer)
SectionSizeReplacer operator= (const SectionSizeReplacer &)
Static Private Attributes
static std::map< const SafePointable *, Word > sizeMap
Contains sections sizes.
Additional Inherited Members
Static Protected Member Functions inherited from TPEF::ValueReplacer
static BinaryStream & stream ()
Detailed Description
Replaces object reference with size of object. Size for object must be stored with static setSize method of this class.
Definition at line 50 of file SectionSizeReplacer.hh.
Constructor & Destructor Documentation
SectionSizeReplacer() [1/2]
TPEF::SectionSizeReplacer::SectionSizeReplacer (const SafePointable * obj)
Constructor.
Definition at line 48 of file SectionSizeReplacer.cc.
                                                                 :
    ValueReplacer(obj) {
}
~SectionSizeReplacer()
TPEF::SectionSizeReplacer::~SectionSizeReplacer () virtual
Destructor.
Definition at line 63 of file SectionSizeReplacer.cc.
{
}
SectionSizeReplacer() [2/2]
TPEF::SectionSizeReplacer::SectionSizeReplacer (const SectionSizeReplacer & replacer) private
Copy constructor.
Definition at line 55 of file SectionSizeReplacer.cc.
                                         :
    ValueReplacer(replacer) {
}
Member Function Documentation
clear()
void TPEF::SectionSizeReplacer::clear () static
Clears all elements from size map.
Definition at line 109 of file SectionSizeReplacer.cc.
{
    sizeMap.clear();
}
References sizeMap.
Referenced by TPEF::BinaryWriter::writeBinary().
clone()
ValueReplacer * TPEF::SectionSizeReplacer::clone () protected virtual
Creates dynamically allocated copy of replacer.
Returns
Dynamically allocated copy of replacer.
Implements TPEF::ValueReplacer.
Definition at line 89 of file SectionSizeReplacer.cc.
{
    return new SectionSizeReplacer(*this);
}
operator=()
SectionSizeReplacer TPEF::SectionSizeReplacer::operator= (const SectionSizeReplacer &) private
setSize()
void TPEF::SectionSizeReplacer::setSize (const SafePointable * obj, Word size) static
Set's size for referred object.
Parameters
obj Objects which for size is stored.
size Size to store.
Definition at line 100 of file SectionSizeReplacer.cc.
{
    assert(obj != NULL);
    sizeMap[obj] = size;
}
References assert, and sizeMap.
Referenced by TPEF::TPEFCodeSectionWriter::actualWriteData(), TPEF::TPEFDataSectionWriter::actualWriteData(), TPEF::TPEFStringSectionWriter::actualWriteData(), TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEF::TPEFDebugSectionWriter::actualWriteData(), TPEF::TPEFLineNumSectionWriter::actualWriteData(), TPEF::TPEFRelocSectionWriter::actualWriteData(), TPEF::TPEFResourceSectionWriter::actualWriteData(), TPEF::TPEFSymbolSectionWriter::actualWriteData(), TPEF::TPEFDebugSectionWriter::createKeys(), and TPEF::TPEFSymbolSectionWriter::createKeys().
tryToReplace()
bool TPEF::SectionSizeReplacer::tryToReplace () protected virtual
Tries to do replacement in to the stream.
Returns
True if replacement were done.
Implements TPEF::ValueReplacer.
Definition at line 72 of file SectionSizeReplacer.cc.
{
    if(MapTools::containsKey(sizeMap, reference())) {
        stream().setWritePosition(streamPosition());
        stream().writeWord(sizeMap[reference()]);
        return true;
    }
    stream().writeWord(0);
    return false;
}
References MapTools::containsKey(), TPEF::ValueReplacer::reference(), TPEF::BinaryStream::setWritePosition(), sizeMap, TPEF::ValueReplacer::stream(), TPEF::ValueReplacer::streamPosition(), and TPEF::BinaryStream::writeWord().
Member Data Documentation
sizeMap
std::map< const SafePointable *, Word > TPEF::SectionSizeReplacer::sizeMap static private
Contains sections sizes.
Definition at line 68 of file SectionSizeReplacer.hh.
Referenced by clear(), setSize(), and tryToReplace().
The documentation for this class was generated from the following files:
SectionSizeReplacer.hh
SectionSizeReplacer.cc