OpenASIP: RISCVTools Class Reference
RISCVTools Class Reference
#include <RISCVTools.hh>
Static Public Member Functions
static std::string getFunc3Str (const int encoding)
static std::string getFunc7Str (const int encoding)
static std::string getFunc2Str (const int encoding)
static std::string getOpcodeStr (const int encoding)
static int getFunc3Int (const int encoding)
static int getFunc7Int (const int encoding)
static int getFunc2Int (const int encoding)
static int getOpcodeInt (const int encoding)
static void findCustomOps (std::map< std::string, int > &customOps_, BinaryEncoding *bem_)
static R4Instruction decodeR4Instruction (const uint32_t opcode)
Detailed Description
Definition at line 42 of file RISCVTools.hh.
Member Function Documentation
decodeR4Instruction()
static R4Instruction RISCVTools::decodeR4Instruction (const uint32_t opcode) static
Referenced by unpackInstruction().
findCustomOps()
static void RISCVTools::findCustomOps (std::map< std::string, int > & customOps_, BinaryEncoding * bem_) inline static
Referenced by initializeMachine().
getFunc2Int()
static int RISCVTools::getFunc2Int (const int encoding) static
Referenced by unpackInstruction().
getFunc2Str()
static std::string RISCVTools::getFunc2Str (const int encoding) static
Referenced by RISCVTDGen::writeInstructionDeclaration().
getFunc3Int()
static int RISCVTools::getFunc3Int (const int encoding) static
Referenced by unpackInstruction().
getFunc3Str()
static std::string RISCVTools::getFunc3Str (const int encoding) static
Referenced by RISCVTDGen::writeInstructionDeclaration().
getFunc7Int()
static int RISCVTools::getFunc7Int (const int encoding) static
Referenced by unpackInstruction().
getFunc7Str()
static std::string RISCVTools::getFunc7Str (const int encoding) static
Referenced by RISCVTDGen::writeInstructionDeclaration().
getOpcodeInt()
static int RISCVTools::getOpcodeInt (const int encoding) static
getOpcodeStr()
static std::string RISCVTools::getOpcodeStr (const int encoding) static
The documentation for this class was generated from the following file:
RISCVTools.hh