OpenASIP: Encoding Class Reference
Encoding Class Reference abstract
#include <Encoding.hh>
Public Member Functions
virtual ~Encoding ()
InstructionField * parent () const
unsigned int encoding () const
unsigned int extraBits () const
virtual int width () const
virtual int bitPosition () const =0
virtual ObjectState * saveState () const
Static Public Attributes
static const std::string OSNAME_ENCODING = "encoding"
ObjectState name for Encoding class.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Protected Member Functions
Encoding (unsigned int encoding, unsigned int extraBits, InstructionField *parent)
Encoding (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
void setEncoding (unsigned int encoding, unsigned int extraBits)
Private Attributes
unsigned int encoding_
The encoding.
unsigned int extraBits_
The number of extra bits.
InstructionField * parent_
The parent instruction field.
Detailed Description
Represents an encoding of a source of destination within a move slot. This is a base class for different encodings.
Definition at line 46 of file Encoding.hh.
Constructor & Destructor Documentation
~Encoding()
Encoding::~Encoding () virtual
The destructor.
Definition at line 87 of file Encoding.cc.
                    {
}
Encoding() [1/2]
Encoding::Encoding (unsigned int encoding, unsigned int extraBits, InstructionField * parent) protected
The constructor.
Parameters
encoding The encoding.
extraBits The number of extra bits.
parent The parent pointer.
Definition at line 53 of file Encoding.cc.
                              :
    encoding_(encoding), extraBits_(extraBits), parent_(parent) {
}
Encoding() [2/2]
Encoding::Encoding (const ObjectState * state, InstructionField * parent) protected
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent pointer.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 71 of file Encoding.cc.
    : encoding_(0), extraBits_(0), parent_(parent) {
    const string procName = "Encoding::Encoding";
    try {
        encoding_ = state->intAttribute(OSKEY_ENCODING);
        extraBits_ = state->intAttribute(OSKEY_EXTRA_BITS);
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References encoding_, Exception::errorMessage(), extraBits_, ObjectState::intAttribute(), OSKEY_ENCODING, and OSKEY_EXTRA_BITS.
Member Function Documentation
bitPosition()
virtual int Encoding::bitPosition () const pure virtual
Returns the position of the encoding within the parent field.
Implemented in BridgeEncoding, ImmediateEncoding, NOPEncoding, and SocketEncoding.
encoding()
unsigned int Encoding::encoding () const
Returns the encoding.
Returns
The encoding.
Definition at line 108 of file Encoding.cc.
{
    return encoding_;
}
References encoding_.
Referenced by SourceField::addBridgeEncoding(), SlotField::addSocketEncoding(), BEMTester::canAddComponentEncoding(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeNOP(), CodeCompressorPlugin::encodeRFTerminal(), printSlotFieldEncodings(), printSourceFieldEncodings(), saveState(), setEncoding(), SocketEncoding::setEncoding(), SourceField::setImmediateEncoding(), SlotField::setNoOperationEncoding(), DefaultDecoderGenerator::socketEncodingCondition(), SocketEncoding::socketIDWidth(), width(), and DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus().
extraBits()
unsigned int Encoding::extraBits () const
Returns the number of extra zero bits in the encoding.
Returns
The number of extra bits.
Definition at line 119 of file Encoding.cc.
{
    return extraBits_;
}
References extraBits_.
Referenced by SourceField::addBridgeEncoding(), SlotField::addSocketEncoding(), BEMTester::canAddComponentEncoding(), saveState(), setEncoding(), SocketEncoding::setEncoding(), SourceField::setImmediateEncoding(), SlotField::setNoOperationEncoding(), SocketEncoding::socketIDWidth(), and width().
parent()
InstructionField * Encoding::parent () const
Returns the parent instruction field.
Returns
The parent instruction field.
Definition at line 97 of file Encoding.cc.
                       {
    return parent_;
}
References parent_.
Referenced by BridgeEncoding::parent(), ImmediateEncoding::parent(), NOPEncoding::parent(), SocketEncoding::parent(), and setParent().
saveState()
ObjectState * Encoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented in BridgeEncoding, ImmediateEncoding, NOPEncoding, and SocketEncoding.
Definition at line 141 of file Encoding.cc.
{
    ObjectState* state = new ObjectState(OSNAME_ENCODING);
    state->setAttribute(OSKEY_ENCODING, encoding());
    state->setAttribute(OSKEY_EXTRA_BITS, extraBits());
    return state;
}
References encoding(), extraBits(), OSKEY_ENCODING, OSKEY_EXTRA_BITS, OSNAME_ENCODING, and ObjectState::setAttribute().
Referenced by BridgeEncoding::saveState(), ImmediateEncoding::saveState(), NOPEncoding::saveState(), and SocketEncoding::saveState().
setEncoding()
void Encoding::setEncoding (unsigned int encoding, unsigned int extraBits) protected
Sets the encoding
Definition at line 163 of file Encoding.cc.
{
    encoding_ = encoding;
    extraBits_ = extraBits;
}
References encoding(), encoding_, extraBits(), and extraBits_.
Referenced by SocketEncoding::setEncoding().
setParent()
void Encoding::setParent (InstructionField * parent) protected
Sets the parent pointer.
Parameters
parent The parent pointer.
Definition at line 155 of file Encoding.cc.
{
    parent_ = parent;
}
References parent(), and parent_.
Referenced by BridgeEncoding::BridgeEncoding(), BridgeEncoding::BridgeEncoding(), SocketEncoding::detachFromParent(), ImmediateEncoding::ImmediateEncoding(), ImmediateEncoding::ImmediateEncoding(), NOPEncoding::NOPEncoding(), NOPEncoding::NOPEncoding(), SocketEncoding::setEncoding(), SocketEncoding::SocketEncoding(), SocketEncoding::SocketEncoding(), BridgeEncoding::~BridgeEncoding(), ImmediateEncoding::~ImmediateEncoding(), and NOPEncoding::~NOPEncoding().
width()
int Encoding::width () const virtual
Returns the bit width required by the encoding.
Returns
The bit width.
Reimplemented in ImmediateEncoding, and SocketEncoding.
Definition at line 130 of file Encoding.cc.
                      {
    return MathTools::bitLength(encoding()) + extraBits();
}
References MathTools::bitLength(), encoding(), and extraBits().
Referenced by BridgeEncoding::bitPosition(), NOPEncoding::bitPosition(), BEMTester::canAddComponentEncoding(), CodeCompressorPlugin::encodeNOP(), ImmediateEncoding::encodingWidth(), printSlotFieldEncodings(), printSourceFieldEncodings(), SlotField::width(), and SourceField::width().
Member Data Documentation
encoding_
unsigned int Encoding::encoding_ private
The encoding.
Definition at line 81 of file Encoding.hh.
Referenced by encoding(), Encoding(), and setEncoding().
extraBits_
unsigned int Encoding::extraBits_ private
The number of extra bits.
Definition at line 83 of file Encoding.hh.
Referenced by Encoding(), extraBits(), and setEncoding().
OSKEY_ENCODING
const std::string Encoding::OSKEY_ENCODING = "encoding" static
ObjectState attribute key for the encoding.
Definition at line 66 of file Encoding.hh.
Referenced by Encoding(), saveState(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
OSKEY_EXTRA_BITS
const std::string Encoding::OSKEY_EXTRA_BITS = "extra_bits" static
ObjectState attribute key for the number of extra bits.
Definition at line 68 of file Encoding.hh.
Referenced by Encoding(), saveState(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
OSNAME_ENCODING
const std::string Encoding::OSNAME_ENCODING = "encoding" static
ObjectState name for Encoding class.
Definition at line 64 of file Encoding.hh.
Referenced by saveState().
parent_
InstructionField* Encoding::parent_ private
The parent instruction field.
Definition at line 85 of file Encoding.hh.
Referenced by parent(), and setParent().
The documentation for this class was generated from the following files:
Encoding.hh
Encoding.cc