OpenASIP: ChildFrame Class Reference
ChildFrame Class Reference
#include <ChildFrame.hh>
Public Member Functions
ChildFrame (wxDocument *doc, wxView *view, wxDocMDIParentFrame *parent)
~ChildFrame ()
void setStatus (const wxString text, int field=0)
Private Member Functions
void onFocus (wxFocusEvent &event)
Private Attributes
wxView * view_
View of the document which is displayed in the frame.
wxDocMDIParentFrame * parent_
MDI parent frame of the ChildFrame.
Detailed Description
MDI child frame for displaying a document.
Definition at line 42 of file ChildFrame.hh.
Constructor & Destructor Documentation
ChildFrame()
ChildFrame::ChildFrame (wxDocument * doc, wxView * view, wxDocMDIParentFrame * parent)
The Constructor.
Parameters
doc Document which is displayed in the ChildFrame.
view View of the document to display.
parent MDI parent frame of the child frame.
Definition at line 52 of file ChildFrame.cc.
                                :
    wxDocMDIChildFrame(doc, view, parent, -1, _T("ChildFrame")),
    view_(view), parent_(parent) {
}
~ChildFrame()
ChildFrame::~ChildFrame ()
The Destructor.
Definition at line 65 of file ChildFrame.cc.
{
}
Member Function Documentation
onFocus()
void ChildFrame::onFocus (wxFocusEvent & event) private
Activates the associated view when a ChildFrame instance gains focus.
Correct views are not always activated by the wxWidgets document/view framework when documents are closed. This function makes sure that the view associated with the focused ChildFrame is activated.
Definition at line 91 of file ChildFrame.cc.
{
    view_->Activate(true);
    event.Skip();
}
References view_.
setStatus()
void ChildFrame::setStatus (const wxString text, int field = 0)
Sets the statusbar text.
Parameters
text New text for the statusbar.
field Field of status bar to set text for.
Definition at line 76 of file ChildFrame.cc.
{
    wxStatusBar* statusbar = parent_->GetStatusBar();
    if (statusbar != NULL && statusbar->GetFieldsCount() > field) {
        statusbar->SetStatusText(text, field);
    }
}
References parent_.
Referenced by SetStatusTextCmd::Do(), SelectTool::onMouseEvent(), MachineCanvas::updateMachine(), and ConnectTool::updateStatusline().
Member Data Documentation
parent_
wxDocMDIParentFrame* ChildFrame::parent_ private
MDI parent frame of the ChildFrame.
Definition at line 55 of file ChildFrame.hh.
Referenced by setStatus().
view_
wxView* ChildFrame::view_ private
View of the document which is displayed in the frame.
Definition at line 53 of file ChildFrame.hh.
Referenced by onFocus().
The documentation for this class was generated from the following files:
ChildFrame.hh
ChildFrame.cc