OpenASIP: TPEF::TPEFStringSectionWriter Class Reference
TPEF::TPEFStringSectionWriter Class Reference
#include <TPEFStringSectionWriter.hh>
Protected Member Functions
TPEFStringSectionWriter ()
virtual ~TPEFStringSectionWriter ()
virtual Section::SectionType type () const
virtual void actualWriteData (BinaryStream &stream, const Section *sect) const
virtual Word elementSize (const Section *section) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void createKeys (const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFStringSectionWriter (const TPEFStringSectionWriter &)
Copying not allowed.
TPEFStringSectionWriter & operator= (const TPEFStringSectionWriter &)
Assignment not allowed.
Static Private Attributes
static const TPEFStringSectionWriter instance_
Unique instance of class.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes the contents of TPEF string section to stream.
Definition at line 47 of file TPEFStringSectionWriter.hh.
Constructor & Destructor Documentation
TPEFStringSectionWriter() [1/2]
TPEF::TPEFStringSectionWriter::TPEFStringSectionWriter () protected
Constructor.
Registers itself to SectionWriter.
Definition at line 57 of file TPEFStringSectionWriter.cc.
                                                 : TPEFSectionWriter() {
    registerSectionWriter(this);
}
References TPEF::SectionWriter::registerSectionWriter().
~TPEFStringSectionWriter()
TPEF::TPEFStringSectionWriter::~TPEFStringSectionWriter () protected virtual
Destructor.
Definition at line 64 of file TPEFStringSectionWriter.cc.
{
}
TPEFStringSectionWriter() [2/2]
TPEF::TPEFStringSectionWriter::TPEFStringSectionWriter (const TPEFStringSectionWriter &) private
Copying not allowed.
Member Function Documentation
actualWriteData()
void TPEF::TPEFStringSectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected virtual
Writes the data of the section to the stream.
Parameters
stream The stream to be written.
sect The section which data is written to stream.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 84 of file TPEFStringSectionWriter.cc.
{
    const StringSection* stringSection =
        dynamic_cast<const StringSection*>(sect);
    assert(stringSection != NULL);
    FileOffset startOffset = stream.writePosition();
    // file offset to data of section
    SafePointer::addObjectReference(FileOffsetKey(startOffset),
                                    sect->chunk(0));
    SectionOffset sectOffset = 0;
    SectionKey sKey = SafePointer::sectionKeyFor(stringSection);
    SectionId id = sKey.sectionId();
    // first byte
    assert(stringSection->byte(stringSection->chunk(0)) == 0);
    // last byte must be also zero
    assert(stringSection->byte(
               stringSection->chunk(
                   stringSection->length() - 1)) == 0);
    for (unsigned int i = 0; i < stringSection->length(); i++) {
        sectOffset = stream.writePosition() - startOffset;
        Chunk* chunk = NULL;
        try {
            chunk = stringSection->chunk(sectOffset);
        } catch (const NotChunkable& n) {
            bool sectionToBeWrittenIsNotChunkable = false;
            assert(sectionToBeWrittenIsNotChunkable);
        }
        if (SafePointer::isReferenced(chunk)) {
            SafePointer::addObjectReference(
                SectionOffsetKey(id, sectOffset), chunk);
        }
        stream.writeByte(stringSection->byte(chunk));
    }
    SectionSizeReplacer::setSize(
        stringSection, stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::DataSection::byte(), TPEF::Section::chunk(), TPEF::RawSection::chunk(), TPEF::ReferenceManager::SafePointer::isReferenced(), TPEF::DataSection::length(), TPEF::ReferenceManager::SectionKey::sectionId(), TPEF::ReferenceManager::SafePointer::sectionKeyFor(), TPEF::SectionSizeReplacer::setSize(), TPEF::BinaryStream::writeByte(), and TPEF::BinaryStream::writePosition().
elementSize()
Word TPEF::TPEFStringSectionWriter::elementSize (const Section * section) const protected virtual
Returns size of char.
Returns
Size of char.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 142 of file TPEFStringSectionWriter.cc.
{
    return sizeof(char);
}
operator=()
TPEFStringSectionWriter & TPEF::TPEFStringSectionWriter::operator= (const TPEFStringSectionWriter &) private
Assignment not allowed.
type()
Section::SectionType TPEF::TPEFStringSectionWriter::type () const protected virtual
Returns the type of the section this writer can write.
Returns
The type of the section writer can write.
Implements TPEF::TPEFSectionWriter.
Definition at line 73 of file TPEFStringSectionWriter.cc.
{
    return Section::ST_STRTAB;
}
References TPEF::Section::ST_STRTAB.
Member Data Documentation
instance_
const TPEFStringSectionWriter TPEF::TPEFStringSectionWriter::instance_ static private
Unique instance of class.
Definition at line 66 of file TPEFStringSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFStringSectionWriter.hh
TPEFStringSectionWriter.cc