OpenASIP: ExplorerPluginParameter Class Reference
ExplorerPluginParameter Class Reference
#include <ExplorerPluginParameter.hh>
Public Member Functions
ExplorerPluginParameter (const std::string &name, ExplorerPluginParameterType type, bool compulsory, const TCEString value, const TCEString description="")
virtual ~ExplorerPluginParameter ()
TCEString name () const
TCEString value () const
TCEString description () const
void setValue (const std::string &value)
ExplorerPluginParameterType type () const
TCEString typeAsString () const
bool isCompulsory () const
bool isSet () const
Private Attributes
TCEString name_
Parameter name.
ExplorerPluginParameterType type_
Parameter type.
bool compulsory_
Is parameter compulsory.
TCEString value_
The value of the parameter as a string, empty if none set.
TCEString description_
The description (help text).
Detailed Description
Explorer plugin parameter class. Represents a parameter that an explorer plugin can have.
Definition at line 46 of file ExplorerPluginParameter.hh.
Constructor & Destructor Documentation
ExplorerPluginParameter()
ExplorerPluginParameter::ExplorerPluginParameter (const std::string & name, ExplorerPluginParameterType type, bool compulsory, const TCEString value, const TCEString description = "")
The constructor.
Definition at line 43 of file ExplorerPluginParameter.cc.
                                     :
        name_(name), type_(type), compulsory_(compulsory), value_(value),
        description_(description) {
}
~ExplorerPluginParameter()
ExplorerPluginParameter::~ExplorerPluginParameter () virtual
The destructor.
Definition at line 58 of file ExplorerPluginParameter.cc.
{
}
Member Function Documentation
description()
TCEString ExplorerPluginParameter::description () const inline
Definition at line 59 of file ExplorerPluginParameter.hh.
{ return description_; }
References description_.
isCompulsory()
bool ExplorerPluginParameter::isCompulsory () const
Returns boolean indicating if the parameter is always needed.
Returns
True if parameter is compulsory, false otherwise.
Definition at line 135 of file ExplorerPluginParameter.cc.
{
    return compulsory_;
}
References compulsory_.
isSet()
bool ExplorerPluginParameter::isSet () const
Returns boolean indicating if the parameter is always needed.
Returns
True if parameter is compulsory, false otherwise.
Definition at line 146 of file ExplorerPluginParameter.cc.
{
    return value_.empty() ? false : true;;
}
References false, and value_.
name()
TCEString ExplorerPluginParameter::name () const
Returns the parameter name.
Returns
Name of the parameter as a string.
Definition at line 86 of file ExplorerPluginParameter.cc.
{
    return name_;
}
References name_.
Referenced by CallExplorerPluginWindow::doEdit(), EditParameterDialog::setTexts(), and CallExplorerPluginWindow::updateParameterList().
setValue()
void ExplorerPluginParameter::setValue (const std::string & value)
Sets the value of the parameter.
Parameters
value The value to be set for the parameter as a string.
Definition at line 74 of file ExplorerPluginParameter.cc.
{
    value_ = value;
}
References value(), and value_.
Referenced by EditParameterDialog::onOk().
type()
ExplorerPluginParameterType ExplorerPluginParameter::type () const
Returns enum for parameter type.
Returns
ExplorerPluginParameterType enumeration for parameter type.
Definition at line 97 of file ExplorerPluginParameter.cc.
{
    return type_;
}
References type_.
typeAsString()
TCEString ExplorerPluginParameter::typeAsString () const
Returns string describing the parameter type.
Returns
ExplorerPluginParameterType as a string.
Definition at line 108 of file ExplorerPluginParameter.cc.
{
    switch (type_) {
        case UINT:
            return "unsigned int";
            break;
        case INT:
            return "int";
            break;
        case STRING:
            return "string";
            break;
        case BOOL:
            return "boolean";
            break;
        default:
            return "";
    }
}
References BOOL, INT, STRING, type_, and UINT.
Referenced by EditParameterDialog::setTexts(), and CallExplorerPluginWindow::updateParameterList().
value()
TCEString ExplorerPluginParameter::value () const
Definition at line 63 of file ExplorerPluginParameter.cc.
{
    return value_;
}
References value_.
Referenced by CallExplorerPluginWindow::doEdit(), EditParameterDialog::setTexts(), setValue(), and CallExplorerPluginWindow::updateParameterList().
Member Data Documentation
compulsory_
bool ExplorerPluginParameter::compulsory_ private
Is parameter compulsory.
Definition at line 74 of file ExplorerPluginParameter.hh.
Referenced by isCompulsory().
description_
TCEString ExplorerPluginParameter::description_ private
The description (help text).
Definition at line 78 of file ExplorerPluginParameter.hh.
Referenced by description().
name_
TCEString ExplorerPluginParameter::name_ private
Parameter name.
Definition at line 70 of file ExplorerPluginParameter.hh.
Referenced by name().
type_
ExplorerPluginParameterType ExplorerPluginParameter::type_ private
Parameter type.
Definition at line 72 of file ExplorerPluginParameter.hh.
Referenced by type(), and typeAsString().
value_
TCEString ExplorerPluginParameter::value_ private
The value of the parameter as a string, empty if none set.
Definition at line 76 of file ExplorerPluginParameter.hh.
Referenced by isSet(), setValue(), and value().
The documentation for this class was generated from the following files:
ExplorerPluginParameter.hh
ExplorerPluginParameter.cc