OpenASIP: AddModuleDialog Class Reference
AddModuleDialog Class Reference
#include <AddModuleDialog.hh>
Public Member Functions
AddModuleDialog (wxWindow *parent, std::string path)
virtual ~AddModuleDialog ()
std::string name () const
Private Types
enum { ID_TEXT , ID_MODULE_NAME }
Private Member Functions
AddModuleDialog (const AddModuleDialog &)
Copying not allowed.
AddModuleDialog & operator= (const AddModuleDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onOk (wxCommandEvent &event)
void setTexts ()
Private Attributes
std::string path_
Path in which module is added.
wxString name_
Name of the module.
Detailed Description
Dialog for adding new modules.
Definition at line 42 of file AddModuleDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_TEXT
ID_MODULE_NAME
Definition at line 62 of file AddModuleDialog.hh.
         {
        ID_TEXT,
        ID_MODULE_NAME
    };
Constructor & Destructor Documentation
AddModuleDialog() [1/2]
AddModuleDialog::AddModuleDialog (wxWindow * parent, std::string path)
Constructor.
@parent Parent window.
Definition at line 62 of file AddModuleDialog.cc.
                                                              :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_ADD_MODULE)),
    path_(path), name_(_T("")){
    createContents(this, true, true);
    FindWindow(ID_MODULE_NAME)->
        SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(wxID_OK)->SetFocus();
    setTexts();
}
~AddModuleDialog()
AddModuleDialog::~AddModuleDialog () virtual
Destructor.
Definition at line 78 of file AddModuleDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_ADD_MODULE, point);
}
References DialogPosition::DIALOG_ADD_MODULE, and DialogPosition::setPosition().
AddModuleDialog() [2/2]
AddModuleDialog::AddModuleDialog (const AddModuleDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * AddModuleDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
Parameters
parent Parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true sets the main sizer as the contents of the dialog.
Returns
The created sizer.
Definition at line 171 of file AddModuleDialog.cc.
                     {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Name of the module:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_MODULE_NAME, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item5 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_MODULE_NAME, and ID_TEXT.
name()
string AddModuleDialog::name () const
Returns the name of the added module.
Returns
The name of the added module.
Definition at line 158 of file AddModuleDialog.cc.
{
    return WxConversion::toString(name_);
}
References name_, and WxConversion::toString().
onOk()
void AddModuleDialog::onOk (wxCommandEvent & event) private
Handles the event when OK button is pushed.
Definition at line 113 of file AddModuleDialog.cc.
{
    TransferDataFromWindow();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    if (name_ == _T("")) {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_NAME);
        fmt % "operation module";
        ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
        return;
    } else {
        string modName = WxConversion::toString(name_);
        // let's check that module name is legal
        const char* regExp = "\\w+";
        boost::regex expression(regExp);
        boost::match_results<string::const_iterator> what;
        if (!boost::regex_match(modName, what, expression)) {
            format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_MOD_NAME);
            fmt % modName;
            ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
            dialog.ShowModal();
            return;
        }
        // let's check there is not already a module by that name
        if (&OperationContainer::module(path_, modName) !=
            &NullOperationModule::instance()) {
            format fmt =
                texts.text(OSEdTextGenerator::TXT_ERROR_MODULE_EXISTS);
            fmt % modName;
            string msg = fmt.str();
            ErrorDialog error(this, WxConversion::toWxString(msg));
            error.ShowModal();
        } else {
            EndModal(wxID_OK);
        }
    }
}
References NullOperationModule::instance(), OSEdTextGenerator::instance(), OperationContainer::module(), name_, path_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_MOD_NAME, OSEdTextGenerator::TXT_ERROR_MODULE_EXISTS, and OSEdTextGenerator::TXT_ERROR_NO_NAME.
operator=()
AddModuleDialog & AddModuleDialog::operator= (const AddModuleDialog &) private
Assignment not allowed.
setTexts()
void AddModuleDialog::setTexts () private
Set texts to widgets.
Definition at line 89 of file AddModuleDialog.cc.
{
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    //title
    format fmt = osedText.text(OSEdTextGenerator::TXT_ADD_MODULE_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT),
                          OSEdTextGenerator::TXT_LABEL_MODULE_NAME);
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(&guiText, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
}
References ID_TEXT, GUITextGenerator::instance(), OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ADD_MODULE_DIALOG_TITLE, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_OK, and OSEdTextGenerator::TXT_LABEL_MODULE_NAME.
Member Data Documentation
name_
wxString AddModuleDialog::name_ private
Name of the module.
Definition at line 70 of file AddModuleDialog.hh.
Referenced by name(), and onOk().
path_
std::string AddModuleDialog::path_ private
Path in which module is added.
Definition at line 68 of file AddModuleDialog.hh.
Referenced by onOk().
The documentation for this class was generated from the following files:
AddModuleDialog.hh
AddModuleDialog.cc