OpenASIP: AddRFArchitectureCmd Class Reference
AddRFArchitectureCmd Class Reference
#include <AddRFArchitectureCmd.hh>
Public Member Functions
AddRFArchitectureCmd ()
virtual ~AddRFArchitectureCmd ()
virtual bool Do ()
virtual int id () const
virtual AddRFArchitectureCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding a new register file archtiecture to a HDB.
Definition at line 41 of file AddRFArchitectureCmd.hh.
Constructor & Destructor Documentation
AddRFArchitectureCmd()
AddRFArchitectureCmd::AddRFArchitectureCmd ()
The Constructor.
Definition at line 47 of file AddRFArchitectureCmd.cc.
                                           :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_RF_ARCHITECTURE, NULL) {
}
Referenced by create().
~AddRFArchitectureCmd()
AddRFArchitectureCmd::~AddRFArchitectureCmd () virtual
The Destructor.
Definition at line 55 of file AddRFArchitectureCmd.cc.
{
}
Member Function Documentation
create()
AddRFArchitectureCmd * AddRFArchitectureCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
A new instance of this command.
Implements GUICommand.
Definition at line 111 of file AddRFArchitectureCmd.cc.
{
    return new AddRFArchitectureCmd();
}
References AddRFArchitectureCmd().
Do()
bool AddRFArchitectureCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 62 of file AddRFArchitectureCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDB::RFArchitecture arch(1, 1, 1, 1, 0, 1, false);
    RFArchitectureDialog dialog(parentWindow(), -1, arch);
    if (dialog.ShowModal() != wxID_OK) {
        return false;
    }
    int id = manager->addRFArchitecture(arch);
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectRFArchitecture(id);
    return true;
}
References HDB::HDBManager::addRFArchitecture(), and GUICommand::parentWindow().
icon()
std::string AddRFArchitectureCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 89 of file AddRFArchitectureCmd.cc.
{
    return "";
}
id()
int AddRFArchitectureCmd::id () const virtual
Returns the command identifier.
Returns
Command identifier for this command.
Implements GUICommand.
Definition at line 100 of file AddRFArchitectureCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_RF_ARCHITECTURE;
}
References HDBEditorConstants::COMMAND_ADD_RF_ARCHITECTURE.
isEnabled()
bool AddRFArchitectureCmd::isEnabled () virtual
Returns true if the command should be enabled in menu/toolbar, false if not.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 122 of file AddRFArchitectureCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddRFArchitectureCmd.hh
AddRFArchitectureCmd.cc