OpenASIP: TerminalNode Class Reference
TerminalNode Class Reference
#include <TerminalNode.hh>
Public Member Functions
TerminalNode (int operandIndex)
TerminalNode (const TerminalNode &other)
virtual ~TerminalNode ()
virtual GraphNode * clone () const
virtual int operandIndex () const
virtual std::string toString () const
Public Member Functions inherited from OperationDAGNode
virtual ~OperationDAGNode ()
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
int nodeID () const
virtual std::string dotString () const
Private Attributes
int operandIndex_
Detailed Description
Input and output node of the operation DAG.
A MoveNode represents one input or output value of an operation.
Definition at line 47 of file TerminalNode.hh.
Constructor & Destructor Documentation
TerminalNode() [1/2]
TerminalNode::TerminalNode (int operandIndex)
Constructor.
Definition at line 39 of file TerminalNode.cc.
                                           :
    OperationDAGNode(), operandIndex_(operandIndex) {}
TerminalNode() [2/2]
TerminalNode::TerminalNode (const TerminalNode & other)
Copoy constructor.
Definition at line 45 of file TerminalNode.cc.
                                                    :
    OperationDAGNode(), operandIndex_(other.operandIndex()) {}
~TerminalNode()
virtual TerminalNode::~TerminalNode () inline virtual
Definition at line 53 of file TerminalNode.hh.
{}
Member Function Documentation
clone()
GraphNode * TerminalNode::clone () const virtual
Clones node. Needed for dynamic binding, when copying instances through the base class.
Returns
Dynamically allocated copy of the node.
Reimplemented from GraphNode.
Definition at line 55 of file TerminalNode.cc.
{
    return new TerminalNode(*this);
}
operandIndex()
int TerminalNode::operandIndex () const virtual
Definition at line 60 of file TerminalNode.cc.
{
    return operandIndex_;
}
References operandIndex_.
Referenced by TDGen::constantNodeString(), TDGen::dagNodeToString(), TDGen::emulatingOpNodeLLVMName(), MemoryAliasAnalyzer::findTwoPartAddressOperands(), OperationDAGBehavior::OperationDAGBehavior(), FUGen::subOpConnection(), and OperationDAGConverter::writeNode().
toString()
std::string TerminalNode::toString () const virtual
Returns a node description as a string.
Used for printing graph into .dot file. This is used for a label in the default dotString() implementation.
Returns
The node ID as a string.
Reimplemented from GraphNode.
Definition at line 65 of file TerminalNode.cc.
{
    return "IO(" + Conversion::toString(operandIndex_) + ")";
}
References operandIndex_, and Conversion::toString().
Member Data Documentation
operandIndex_
int TerminalNode::operandIndex_ private
Definition at line 62 of file TerminalNode.hh.
Referenced by operandIndex(), and toString().
The documentation for this class was generated from the following files:
TerminalNode.hh
TerminalNode.cc