OpenASIP: HDBBrowserInfoPanel Class Reference
HDBBrowserInfoPanel Class Reference
#include <HDBBrowserInfoPanel.hh>
Public Member Functions
HDBBrowserInfoPanel (wxWindow *parent, wxWindowID id)
virtual ~HDBBrowserInfoPanel ()
void setHDB (const HDB::HDBManager &hdb)
void clear ()
void displayFUEntry (RowID id)
void displayRFEntry (RowID id)
void displayBusEntry (RowID id)
void displaySocketEntry (RowID id)
void displayFUArchitecture (RowID id)
void displayRFArchitecture (RowID id)
void displayFUImplementation (RowID id)
void displayRFImplementation (RowID id)
void displayCostFunctionPlugin (RowID id)
void displayOperationImplementation (RowID id)
void displayOperationImplementationResource (RowID id)
Private Member Functions
virtual void OnLinkClicked (const wxHtmlLinkInfo &link)
Private Attributes
HDBToHtml * htmlGen_
HDB to HTML generator.
Detailed Description
Window for displaying HDB element details.
Definition at line 49 of file HDBBrowserInfoPanel.hh.
Constructor & Destructor Documentation
HDBBrowserInfoPanel()
HDBBrowserInfoPanel::HDBBrowserInfoPanel (wxWindow * parent, wxWindowID id)
The Constructor.
Parameters
parent Parent window of the panel.
id Window ientifier for the panel.
Definition at line 51 of file HDBBrowserInfoPanel.cc.
                                                                        :
    wxHtmlWindow(parent, id),
    htmlGen_(NULL) {
}
~HDBBrowserInfoPanel()
HDBBrowserInfoPanel::~HDBBrowserInfoPanel () virtual
The Destructor.
Definition at line 59 of file HDBBrowserInfoPanel.cc.
{
    if (htmlGen_ != NULL) {
        delete htmlGen_;
        htmlGen_ = NULL;
    }
}
References htmlGen_.
Member Function Documentation
clear()
void HDBBrowserInfoPanel::clear ()
Clears the panel contents.
Definition at line 89 of file HDBBrowserInfoPanel.cc.
{
    SetPage(_T("<html><body></body></html>"));
}
Referenced by HDBBrowserWindow::onItemSelected(), and HDBBrowserWindow::update().
displayBusEntry()
void HDBBrowserInfoPanel::displayBusEntry (RowID id)
Displays details of a bus entry in the panel.
Parameters
id ID of the bus entry.
Definition at line 128 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->busEntryToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, HDBToHtml::busEntryToHtml(), htmlGen_, and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayCostFunctionPlugin()
void HDBBrowserInfoPanel::displayCostFunctionPlugin (RowID id)
Displays details of a cost function plugin in the panel.
Parameters
id ID of the cost function plugin.
Definition at line 215 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->costFunctionPluginToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, HDBToHtml::costFunctionPluginToHtml(), htmlGen_, and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayFUArchitecture()
void HDBBrowserInfoPanel::displayFUArchitecture (RowID id)
Displays details of an FU architecture in the panel.
Parameters
id ID of the FU architecture.
Definition at line 157 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->fuArchToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, HDBToHtml::fuArchToHtml(), htmlGen_, and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayFUEntry()
void HDBBrowserInfoPanel::displayFUEntry (RowID id)
Displays details of an FU entry in the panel.
Parameters
id ID of the FU entry.
Definition at line 99 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->fuEntryToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, HDBToHtml::fuEntryToHtml(), htmlGen_, and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayFUImplementation()
void HDBBrowserInfoPanel::displayFUImplementation (RowID id)
Displays details of an FU implementation in the panel.
Parameters
id ID of the FU implementation.
Definition at line 186 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->fuImplToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, HDBToHtml::fuImplToHtml(), htmlGen_, and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayOperationImplementation()
void HDBBrowserInfoPanel::displayOperationImplementation (RowID id)
Displays details of a FUGEN oparation in the panel.
Parameters
id ID of the FUGEN operation plugin.
Definition at line 229 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->OperationImplementationToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::OperationImplementationToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayOperationImplementationResource()
void HDBBrowserInfoPanel::displayOperationImplementationResource (RowID id)
Displays details of a FUGEN resource in the panel.
Parameters
id ID of the FUGEN resource plugin.
Definition at line 243 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->OperationImplementationResourceToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::OperationImplementationResourceToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayRFArchitecture()
void HDBBrowserInfoPanel::displayRFArchitecture (RowID id)
Displays details of a RF architecture in the panel.
Parameters
id ID of the register file architecture.
Definition at line 171 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->rfArchToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::rfArchToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayRFEntry()
void HDBBrowserInfoPanel::displayRFEntry (RowID id)
Displays details of a RF entry in the panel.
Parameters
id ID of the register file entry.
Definition at line 114 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->rfEntryToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::rfEntryToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displayRFImplementation()
void HDBBrowserInfoPanel::displayRFImplementation (RowID id)
Displays details of a RF implementation in the panel.
Parameters
id ID of the RF implementation.
Definition at line 201 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->rfImplToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::rfImplToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
displaySocketEntry()
void HDBBrowserInfoPanel::displaySocketEntry (RowID id)
Displays details of a socket entry in the panel.
Parameters
id ID of the socket entry.
Definition at line 142 of file HDBBrowserInfoPanel.cc.
{
    assert(htmlGen_ != NULL);
    std::stringstream stream;
    htmlGen_->socketEntryToHtml(id, stream);
    std::string page = stream.str();
    SetPage(WxConversion::toWxString(page));
}
References assert, htmlGen_, HDBToHtml::socketEntryToHtml(), and WxConversion::toWxString().
Referenced by HDBBrowserWindow::onItemSelected().
OnLinkClicked()
void HDBBrowserInfoPanel::OnLinkClicked (const wxHtmlLinkInfo & link) private virtual
Definition at line 67 of file HDBBrowserInfoPanel.cc.
{
    wxString href = link.GetHref();
    wxGetApp().browser()->openLink(href);
}
setHDB()
void HDBBrowserInfoPanel::setHDB (const HDB::HDBManager & hdb)
Sets the HDB.
Parameters
hdb HDB to generate html from.
Definition at line 78 of file HDBBrowserInfoPanel.cc.
{
    if (htmlGen_ != NULL) {
        delete htmlGen_;
    }
    htmlGen_ = new HDBToHtml(hdb);
}
References htmlGen_.
Referenced by HDBBrowserWindow::setHDBManager().
Member Data Documentation
htmlGen_
HDBToHtml* HDBBrowserInfoPanel::htmlGen_ private
HDB to HTML generator.
Definition at line 73 of file HDBBrowserInfoPanel.hh.
Referenced by displayBusEntry(), displayCostFunctionPlugin(), displayFUArchitecture(), displayFUEntry(), displayFUImplementation(), displayOperationImplementation(), displayOperationImplementationResource(), displayRFArchitecture(), displayRFEntry(), displayRFImplementation(), displaySocketEntry(), setHDB(), and ~HDBBrowserInfoPanel().
The documentation for this class was generated from the following files:
HDBBrowserInfoPanel.hh
HDBBrowserInfoPanel.cc