OpenASIP: TTAMachine::RegisterFile Class Reference
TTAMachine::RegisterFile Class Reference
#include <RegisterFile.hh>
Public Types
enum Type { NORMAL , RESERVED , VOLATILE }
Type of the register file indicates how the RF is used.
Public Member Functions
RegisterFile (const std::string &name, unsigned int size, unsigned int width, unsigned int maxReads, unsigned int maxwrites, unsigned int guardLatency, Type type, bool zeroRegister=false)
RegisterFile (const ObjectState *state)
virtual ~RegisterFile ()
virtual RegisterFile * copy () const
virtual int maxReads () const
virtual int maxWrites () const
virtual RegisterFile::Type type () const
virtual bool isNormal () const
virtual bool isVolatile () const
virtual bool isReserved () const
virtual void setName (const std::string &name)
virtual void setMaxReads (int maxReads)
virtual void setMaxWrites (int maxWrites)
virtual void setType (RegisterFile::Type type)
virtual void setNumberOfRegisters (int registers)
virtual int guardLatency () const
virtual void setGuardLatency (int latency)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
virtual bool isArchitectureEqual (const RegisterFile &rf) const
virtual bool isUsedAsGuard () const
virtual bool zeroRegister () const
virtual void setZeroRegister (const bool &value)
Port * firstReadPort () const
Port * firstWritePort () const
Public Member Functions inherited from TTAMachine::BaseRegisterFile
virtual ~BaseRegisterFile ()
virtual int numberOfRegisters () const
virtual int width () const
virtual int size () const
virtual void setWidth (int width)
virtual RFPort * port (const std::string &name) const
virtual RFPort * port (int index) const
Public Member Functions inherited from TTAMachine::Unit
virtual ~Unit ()
virtual bool hasPort (const std::string &name) const
virtual int portCount () const
virtual int outputPortCount (bool countBidir=false) const
virtual int inputPortCount (bool countBidir=false) const
virtual int bidirPortCount () const
virtual void setMachine (Machine &mach)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_REGISTER_FILE = "reg_file"
ObjectState name for RegisterFile.
static const std::string OSKEY_TYPE = "type"
ObjectState attribute key for register file type.
static const std::string OSVALUE_NORMAL = "normal"
ObjectState attribute value for normal register file type.
static const std::string OSVALUE_RESERVED = "reserved"
ObjectState attribute value for reserved register file type.
static const std::string OSVALUE_VOLATILE = "volatile"
ObjectState attribute value for volatile register file type.
static const std::string OSKEY_MAX_READS = "max_r"
ObjectState attribute key for maximum simultaneous readers.
static const std::string OSKEY_MAX_WRITES = "max_w"
ObjectState attribute key for maximum simultaneous writers.
static const std::string OSKEY_GUARD_LATENCY = "g_latency"
ObjectState attribute key for the guard latency.
static const std::string OSKEY_ZERO_REGISTER = "zero_register"
ObjectState attribute key for zero register flag.
Static Public Attributes inherited from TTAMachine::BaseRegisterFile
static const std::string OSNAME_BASE_REGISTER_FILE = "baseregfile"
ObjectState name for BaseRegisterFile.
static const std::string OSKEY_SIZE = "size"
ObjectState attribute key for the number of registers.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bit width of the registers.
Static Public Attributes inherited from TTAMachine::Unit
static const std::string OSNAME_UNIT = "unit"
ObjectState name for Unit.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Member Functions
bool updateMaxReadsAndWrites () const
RegisterFile (const RegisterFile &)
Copying forbidden, use the copy() method.
RegisterFile & operator= (const RegisterFile &)
Assingment forbidden.
void loadStateWithoutReferences (const ObjectState *state)
void deleteGuards (int registers) const
Private Attributes
int maxReads_
Max number of ports that can read a register all in the same cycle.
int maxWrites_
Max number of ports that can read a register all in the same cycle.
int guardLatency_
The guard latency of the register file.
Type type_
Type of the register file.
bool zeroRegister_
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::BaseRegisterFile
BaseRegisterFile (const std::string &name, int size, int width)
BaseRegisterFile (const ObjectState *state)
Protected Member Functions inherited from TTAMachine::Unit
Unit (const std::string &name)
Unit (const ObjectState *state)
virtual void removePort (Port &port)
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents a register-file in TTA processor.
Definition at line 47 of file RegisterFile.hh.
Member Enumeration Documentation
Type
enum TTAMachine::RegisterFile::Type
Type of the register file indicates how the RF is used.
Enumerator
NORMAL
Used for general register allocation.
RESERVED
Used for custom, user controlled register allocation.
VOLATILE
Used for user-controlled I/O communication.
Definition at line 50 of file RegisterFile.hh.
              {
        NORMAL,   ///< Used for general register allocation.
        RESERVED, ///< Used for custom, user controlled register allocation.
        VOLATILE  ///< Used for user-controlled I/O communication.
    };
Constructor & Destructor Documentation
RegisterFile() [1/3]
TTAMachine::RegisterFile::RegisterFile (const std::string & name, unsigned int size, unsigned int width, unsigned int maxReads, unsigned int maxWrites, unsigned int guardLatency, Type type, bool zeroRegister = false)
Constructor.
Parameters
name Name of the register file.
size Number of registers in the register file.
width Bit width of the registers in the register file.
maxReads Maximum simultaneous reads of a register.
maxWrites Maximum simultaneous writes of a register.
maxRw Maximum simultaneous reads of a register in the same cycle the register is written.
type Type of the register file, see RegisterFile::Type.
Exceptions
OutOfRange If some of the given parameters has an illegal value.
InvalidName If the given name is not a valid component name.
Definition at line 74 of file RegisterFile.cc.
    : BaseRegisterFile(name, size, width),
      maxReads_(0),
      maxWrites_(0),
      guardLatency_(0),
      type_(type),
      zeroRegister_(zeroRegister) {
    setMaxReads(maxReads);
    setMaxWrites(maxWrites);
    setGuardLatency(guardLatency);
}
References guardLatency(), maxReads(), maxWrites(), setGuardLatency(), setMaxReads(), and setMaxWrites().
RegisterFile() [2/3]
TTAMachine::RegisterFile::RegisterFile (const ObjectState * state) explicit
Constructor.
Loads the state of the register file from the given ObjectState instance. Does not load references to other components.
Parameters
state The ObjectState from which the name is taken.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Definition at line 99 of file RegisterFile.cc.
    : BaseRegisterFile(state),
      maxReads_(0),
      maxWrites_(0),
      guardLatency_(0),
      type_(NORMAL),
      zeroRegister_(false) {
    loadStateWithoutReferences(state);
}
References loadStateWithoutReferences().
~RegisterFile()
TTAMachine::RegisterFile::~RegisterFile () virtual
Destructor.
Definition at line 112 of file RegisterFile.cc.
{
    unsetMachine();
}
References unsetMachine().
RegisterFile() [3/3]
TTAMachine::RegisterFile::RegisterFile (const RegisterFile &) private
Copying forbidden, use the copy() method.
Member Function Documentation
copy()
RegisterFile * TTAMachine::RegisterFile::copy () const virtual
Creates and returns a copy of the register file.
Returns
Copy of register file.
Definition at line 601 of file RegisterFile.cc.
{
    return new RegisterFile(saveState());
}
References saveState().
deleteGuards()
void TTAMachine::RegisterFile::deleteGuards (int registers) const private
Deletes the guards that refer to registers would not exist if there were the given number of registers in this register file.
Parameters
registers The number of registers.
Definition at line 492 of file RegisterFile.cc.
{
    Machine* mach = machine();
    if (mach == NULL) {
        return;
    }
    // for each bus
    Machine::BusNavigator navi = mach->busNavigator();
    for (int busIndex = 0; busIndex < navi.count(); busIndex++) {
        Bus* bus = navi.item(busIndex);
        int guardIndex = 0;
        // delete register guards that refer to non-existing registers
        while (guardIndex < bus->guardCount()) {
            Guard* guard = bus->guard(guardIndex);
            RegisterGuard* regGuard =
                dynamic_cast<RegisterGuard*>(guard);
            if (regGuard != NULL && regGuard->registerFile() == this &&
                regGuard->registerIndex() >= registers) {
                // guard is removed from bus automatically
                delete regGuard;
            } else {
                guardIndex++;
            }
        }
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::RegisterGuard::registerFile(), and TTAMachine::RegisterGuard::registerIndex().
Referenced by setNumberOfRegisters(), and unsetMachine().
firstReadPort()
Port * TTAMachine::RegisterFile::firstReadPort () const
Definition at line 607 of file RegisterFile.cc.
{
    for (int i = 0; i < portCount(); i++) {
        Port* p = port(i);
        if (p->outputSocket() != NULL) {
            return p;
        }
    }
    return NULL;
}
References TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), and TTAMachine::Unit::portCount().
Referenced by RegisterRenamer::renameLiveRange(), BFRenameLiveRange::setTerminals(), BFRegCopyAfter::splitMove(), and BFRegCopyBefore::splitMove().
firstWritePort()
Port * TTAMachine::RegisterFile::firstWritePort () const
Definition at line 618 of file RegisterFile.cc.
{
    for (int i = 0; i < portCount(); i++) {
        Port* p = port(i);
        if (p->inputSocket() != NULL) {
            return p;
        }
    }
    return NULL;
}
References TTAMachine::Port::inputSocket(), TTAMachine::BaseRegisterFile::port(), and TTAMachine::Unit::portCount().
Referenced by RegisterRenamer::renameLiveRange(), BFRenameLiveRange::setTerminals(), BFRegCopyAfter::splitMove(), and BFRegCopyBefore::splitMove().
guardLatency()
int TTAMachine::RegisterFile::guardLatency () const virtual
Returns the guard latency.
Returns
The guard latency.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 333 of file RegisterFile.cc.
{
    return guardLatency_;
}
References guardLatency_.
Referenced by MachineStateBuilder::buildMachineState(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), TTAProgram::Move::guardLatency(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), isArchitectureEqual(), TTAMachine::RegisterGuard::loadState(), MachineInfo::longestGuardLatency(), BlockImplementationDialog::onHDBSelection(), RegisterFile(), TTAMachine::RegisterGuard::RegisterGuard(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), SequentialScheduler::scheduleMove(), setGuardLatency(), and RFDialog::updateWidgets().
isArchitectureEqual()
bool TTAMachine::RegisterFile::isArchitectureEqual (const RegisterFile & rf) const virtual
Checks is this register file architecture equal with the given register file.
Architecture equality means that register files have same values, names and port names may differ.
Parameters
rf Register file to compare with.
Returns
True if the register files are architecture equal.
Definition at line 532 of file RegisterFile.cc.
{
    if (size() != rf.size()) {
        return false;
    }
    if (width() != rf.width()) {
        return false;
    }
    if (maxReads_ != rf.maxReads()) {
        return false;
    }
    if (maxWrites_ != rf.maxWrites()) {
        return false;
    }
    if (type_ != rf.type()) {
        return false;
    }
    if (guardLatency_ != rf.guardLatency()) {
        return false;
    }
    if (portCount() != rf.portCount()) {
        return false;
    }
    // ports have same width that the register file, so port widths are not
    // needed to check
    return true;
}
References guardLatency(), guardLatency_, maxReads(), maxReads_, maxWrites(), maxWrites_, TTAMachine::Unit::portCount(), TTAMachine::BaseRegisterFile::size(), type(), type_, and TTAMachine::BaseRegisterFile::width().
Referenced by MachineResourceModifier::analyzeRegisters().
isNormal()
bool TTAMachine::RegisterFile::isNormal () const virtual
Returns true if the type of the register file is normal, otherwise false.
Returns
True if the type of the register file is normal, otherwise false.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 158 of file RegisterFile.cc.
{
    return (type_ == NORMAL);
}
References NORMAL, and type_.
Referenced by ProDeRFEditPolicy::getCommand().
isReserved()
bool TTAMachine::RegisterFile::isReserved () const virtual
Returns true if the type of the register file is reserved, otherwise false.
Returns
True if the type of the register file is reserved, otherwise false.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 184 of file RegisterFile.cc.
{
    return (type_ == RESERVED);
}
References RESERVED, and type_.
Referenced by TDGen::analyzeRegisters(), and ProDeRFEditPolicy::getCommand().
isUsedAsGuard()
bool TTAMachine::RegisterFile::isUsedAsGuard () const virtual
Returns true if the register file is used as a guard.
Returns
True if the register file is used as a guard.
Definition at line 567 of file RegisterFile.cc.
{
    Machine* mach = machine();
    if (mach == NULL) {
        return false;
    }
    // for each bus
    Machine::BusNavigator navi = mach->busNavigator();
    for (int busIndex = 0; busIndex < navi.count(); busIndex++) {
        Bus* bus = navi.item(busIndex);
        int guardIndex = 0;
        // check if there are register guards that refer to this register file
        while (guardIndex < bus->guardCount()) {
            Guard* guard = bus->guard(guardIndex);
            RegisterGuard* regGuard =
                dynamic_cast<RegisterGuard*>(guard);
            if (regGuard != NULL && regGuard->registerFile() == this) {
                return true;
            } else {
                guardIndex++;
            }
        }
    }
    return false;
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), and TTAMachine::RegisterGuard::registerFile().
Referenced by ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), AutoSelectImplementationsDialog::findRFImplementations(), BlockImplementationDialog::onHDBSelection(), and ComponentImplementationSelector::selectRFs().
isVolatile()
bool TTAMachine::RegisterFile::isVolatile () const virtual
Returns true if the type of the register file is volatile, otherwise false.
Returns
True if the type of the register file is volatile, otherwise false.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 171 of file RegisterFile.cc.
{
    return (type_ == VOLATILE);
}
References type_, and VOLATILE.
Referenced by ProDeRFEditPolicy::getCommand().
loadState()
void TTAMachine::RegisterFile::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Reimplemented from TTAMachine::BaseRegisterFile.
Reimplemented in TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, and UnboundedRegisterFile.
Definition at line 433 of file RegisterFile.cc.
{
    const string procName = "RegisterFile::loadState";
    loadStateWithoutReferences(state);
    BaseRegisterFile::loadState(state);
    MOMTextGenerator textGenerator;
}
References TTAMachine::BaseRegisterFile::loadState(), and loadStateWithoutReferences().
Referenced by TTAMachine::ImmediateUnit::loadState(), and TTAMachine::Machine::loadState().
loadStateWithoutReferences()
void TTAMachine::RegisterFile::loadStateWithoutReferences (const ObjectState * state) private
Loads the state of the register file without references to other components.
Parameters
state The ObjectState instance from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 449 of file RegisterFile.cc.
{
    const string procName = "RegisterFile::loadStateWithoutReferences";
    if (! (state->name() == OSNAME_REGISTER_FILE ||
           state->name() == ImmediateUnit::OSNAME_IMMEDIATE_UNIT)) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        string type = state->stringAttribute(OSKEY_TYPE);
        if (type == OSVALUE_NORMAL) {
            setType(NORMAL);
        } else if (type == OSVALUE_RESERVED) {
            setType(RESERVED);
        } else if (type == OSVALUE_VOLATILE) {
            setType(VOLATILE);
        } else {
            const string errorMsg = "Unknown register file type in "
                "ObjectState instance.";
            throw ObjectStateLoadingException(
                __FILE__, __LINE__, procName, errorMsg);
        }
        setMaxReads(state->intAttribute(OSKEY_MAX_READS));
        setMaxWrites(state->intAttribute(OSKEY_MAX_WRITES));
        setGuardLatency(state->intAttribute(OSKEY_GUARD_LATENCY));
        if (state->hasAttribute(OSKEY_ZERO_REGISTER)) {
            setZeroRegister(state->boolAttribute(OSKEY_ZERO_REGISTER));
        }
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
}
References ObjectState::boolAttribute(), Exception::errorMessage(), ObjectState::hasAttribute(), ObjectState::intAttribute(), ObjectState::name(), NORMAL, OSKEY_GUARD_LATENCY, OSKEY_MAX_READS, OSKEY_MAX_WRITES, OSKEY_TYPE, OSKEY_ZERO_REGISTER, TTAMachine::ImmediateUnit::OSNAME_IMMEDIATE_UNIT, OSNAME_REGISTER_FILE, OSVALUE_NORMAL, OSVALUE_RESERVED, OSVALUE_VOLATILE, RESERVED, setGuardLatency(), setMaxReads(), setMaxWrites(), setType(), setZeroRegister(), ObjectState::stringAttribute(), type(), and VOLATILE.
Referenced by loadState(), and RegisterFile().
maxReads()
int TTAMachine::RegisterFile::maxReads () const virtual
Returns the number of ports that can read a register all in same cycle.
Returns
The number of ports that can read a register all in same cycle.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 123 of file RegisterFile.cc.
{
    updateMaxReadsAndWrites();
    return maxReads_;
}
References maxReads_, and updateMaxReadsAndWrites().
Referenced by ResourceConstraintAnalyzer::analyzeMoveNode(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ADFCombiner::createPortsAndSockets(), FullyConnectedCheck::fix(), isArchitectureEqual(), BlockImplementationDialog::onHDBSelection(), RegisterFile(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), BFOptimization::RFReadPortCountPreventsScheduling(), and RFDialog::updateWidgets().
maxWrites()
int TTAMachine::RegisterFile::maxWrites () const virtual
Returns the number of ports that can write a register all in same cycle.
Returns
The number of ports that can write a register all in same cycle.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 135 of file RegisterFile.cc.
{
    updateMaxReadsAndWrites();
    return maxWrites_;
}
References maxWrites_, and updateMaxReadsAndWrites().
Referenced by ResourceConstraintAnalyzer::analyzeMoveNode(), ADFCombiner::createPortsAndSockets(), FullyConnectedCheck::fix(), isArchitectureEqual(), BlockImplementationDialog::onHDBSelection(), RegisterFile(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), TTAMachine::ImmediateUnit::setMaxWrites(), setMaxWrites(), and RFDialog::updateWidgets().
operator=()
RegisterFile & TTAMachine::RegisterFile::operator= (const RegisterFile &) private
Assingment forbidden.
saveState()
ObjectState * TTAMachine::RegisterFile::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::BaseRegisterFile.
Reimplemented in TTAMachine::ImmediateUnit, and TTAMachine::NullRegisterFile.
Definition at line 392 of file RegisterFile.cc.
{
    ObjectState* regFile = BaseRegisterFile::saveState();
    regFile->setName(OSNAME_REGISTER_FILE);
    // set type
    switch(type_) {
    case NORMAL: regFile->setAttribute(OSKEY_TYPE, OSVALUE_NORMAL); break;
    case RESERVED: regFile->setAttribute(OSKEY_TYPE, OSVALUE_RESERVED);
        break;
    case VOLATILE: regFile->setAttribute(OSKEY_TYPE, OSVALUE_VOLATILE);
        break;
    default: assert(false);
    }
    // set max reads
    regFile->setAttribute(OSKEY_MAX_READS, maxReads_);
    // set max writes
    regFile->setAttribute(OSKEY_MAX_WRITES, maxWrites_);
    // set guard latency
    regFile->setAttribute(OSKEY_GUARD_LATENCY, guardLatency_);
    // set zero register
    if (zeroRegister_) {
        regFile->setAttribute(OSKEY_ZERO_REGISTER, zeroRegister_);
    }
    return regFile;
}
References assert, guardLatency_, maxReads_, maxWrites_, NORMAL, OSKEY_GUARD_LATENCY, OSKEY_MAX_READS, OSKEY_MAX_WRITES, OSKEY_TYPE, OSKEY_ZERO_REGISTER, OSNAME_REGISTER_FILE, OSVALUE_NORMAL, OSVALUE_RESERVED, OSVALUE_VOLATILE, RESERVED, TTAMachine::BaseRegisterFile::saveState(), ObjectState::setAttribute(), ObjectState::setName(), type_, VOLATILE, and zeroRegister_.
Referenced by copy(), and TTAMachine::ImmediateUnit::saveState().
setGuardLatency()
void TTAMachine::RegisterFile::setGuardLatency (int latency) virtual
Sets the guard latency.
Parameters
latency The new guard latency.
Exceptions
OutOfRange If the given value is negative or if local + global guard latency would be zero.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 346 of file RegisterFile.cc.
{
    if (latency < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    // check that local guard latency + global guard latency > 0
    if (latency == 0 && isRegistered()) {
        ControlUnit* gcu = machine()->controlUnit();
        if (gcu != NULL) {
            int oldLatency = guardLatency();
            guardLatency_ = latency;
            try {
                // this throws OutOfRange if the local guard latency cannot
                // be zero
                gcu->setGlobalGuardLatency(gcu->globalGuardLatency());
            } catch (const OutOfRange& exception) {
                guardLatency_ = oldLatency;
                throw exception;
            }
        }
    }
    guardLatency_ = latency;
}
References __func__, TTAMachine::Machine::controlUnit(), TTAMachine::ControlUnit::globalGuardLatency(), guardLatency(), guardLatency_, TTAMachine::Component::isRegistered(), TTAMachine::Component::machine(), and TTAMachine::ControlUnit::setGlobalGuardLatency().
Referenced by loadStateWithoutReferences(), RFDialog::onOK(), and RegisterFile().
setMaxReads()
void TTAMachine::RegisterFile::setMaxReads (int reads) virtual
Sets the maximum number of ports that can read a register all in the same cycle. Note that this function is only needed if all of the ports are unconnected, otherwise this value is computed automatically.
The given value must be at least zero.
Parameters
reads Maximum number of ports.
Exceptions
OutOfRange If the given number of maximum reads is out of range.
Reimplemented in TTAMachine::NullRegisterFile, and UnboundedRegisterFile.
Definition at line 227 of file RegisterFile.cc.
{
    if (reads < 0) {
        std::string procName = "RegisterFile::setMaxReads";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    maxReads_ = reads;
}
References maxReads_.
Referenced by loadStateWithoutReferences(), and RegisterFile().
setMaxWrites()
void TTAMachine::RegisterFile::setMaxWrites (int maxWrites) virtual
Sets the maximum number of ports that can write a register all in the same cycle. Note that this function is only needed if all of the ports are unconnected, otherwise this value is computed automatically.
The given value must be at least zero.
Parameters
writes Maximum number of ports.
Exceptions
OutOfRange If the given number of maximum writes is out of range.
Reimplemented in TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, and UnboundedRegisterFile.
Definition at line 247 of file RegisterFile.cc.
{
    if (maxWrites < 0) {
        std::string procName = "RegisterFile::setMaxWrites";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    maxWrites_ = maxWrites;
}
References maxWrites(), and maxWrites_.
Referenced by loadStateWithoutReferences(), RegisterFile(), and TTAMachine::ImmediateUnit::setMaxWrites().
setName()
void TTAMachine::RegisterFile::setName (const std::string & name) virtual
Sets the name of the register file.
Parameters
name Name of the register file.
Exceptions
ComponentAlreadyExists If a register file with the given name is already in the same machine.
InvalidName If the given name is not a valid component name.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, and UnboundedRegisterFile.
Definition at line 198 of file RegisterFile.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->registerFileNavigator().hasItem(name)) {
            string procName = "RegisterFile::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by ADFCombiner::addRegisterFiles(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), RFDialog::onOK(), and MachineResourceModifier::percentualRegisterIncrease().
setNumberOfRegisters()
void TTAMachine::RegisterFile::setNumberOfRegisters (int registers) virtual
Sets the number of registers in the register file.
If the number of registers decreases, deletes the register guards that were referencing to the registers that are removed.
Parameters
registers The new amount of registers.
Exceptions
OutOfRange If the given number of registers is less or equal to zero.
Reimplemented from TTAMachine::BaseRegisterFile.
Reimplemented in TTAMachine::NullRegisterFile, and UnboundedRegisterFile.
Definition at line 320 of file RegisterFile.cc.
{
    if (registers < numberOfRegisters()) {
        deleteGuards(registers);
    }
    BaseRegisterFile::setNumberOfRegisters(registers);
}
References deleteGuards(), TTAMachine::BaseRegisterFile::numberOfRegisters(), and TTAMachine::BaseRegisterFile::setNumberOfRegisters().
Referenced by RegisterQuantityCheck::fixIntRegs(), TTAMachine::ImmediateUnit::ImmediateUnit(), IUDialog::onOK(), and RFDialog::onOK().
setType()
void TTAMachine::RegisterFile::setType (RegisterFile::Type type) virtual
Sets the type of the register file.
Parameters
type Type of the register file.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 304 of file RegisterFile.cc.
{
    type_ = type;
}
References type(), and type_.
Referenced by loadStateWithoutReferences(), and RFDialog::onOK().
setZeroRegister()
void TTAMachine::RegisterFile::setZeroRegister (const bool & value) virtual
Definition at line 634 of file RegisterFile.cc.
{
    zeroRegister_ = value;
}
References zeroRegister_.
Referenced by loadStateWithoutReferences(), and RFDialog::onOK().
type()
RegisterFile::Type TTAMachine::RegisterFile::type () const virtual
Returns the type of the register file.
Returns
Type of the register file.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 147 of file RegisterFile.cc.
{
    return type_;
}
References type_.
Referenced by isArchitectureEqual(), loadStateWithoutReferences(), setType(), and RFDialog::updateWidgets().
unsetMachine()
void TTAMachine::RegisterFile::unsetMachine () virtual
Removes the register file from machine.
Reimplemented from TTAMachine::Unit.
Reimplemented in TTAMachine::ImmediateUnit, and TTAMachine::NullRegisterFile.
Definition at line 375 of file RegisterFile.cc.
{
    Machine* mach = machine();
    if (mach == NULL) {
        return;
    }
    deleteGuards(0);
    BaseRegisterFile::unsetMachine();
    mach->removeRegisterFile(*this);
}
References deleteGuards(), TTAMachine::Component::machine(), TTAMachine::Machine::removeRegisterFile(), and TTAMachine::Component::unsetMachine().
Referenced by ~RegisterFile().
updateMaxReadsAndWrites()
bool TTAMachine::RegisterFile::updateMaxReadsAndWrites () const private
Updates RFs max reads/writes according in/output ports.
Port that is not assigned to a socket is considered to be a dead port, thus not counted towards the maximum number of reads or writes.
Returns
True if max reads/writes changed
Exceptions
OutOfRange If setMaxReads/setMaxWrites throws outOfRange exception.
Definition at line 266 of file RegisterFile.cc.
{
    int reads = 0;
    int writes = 0;
    bool changed = false;
    for (int p = 0; p < portCount(); ++p) {
        if (!port(p)->isOutput() && !port(p)->isInput()) {
            // do not count unconnected ports
            //++reads;
            //++writes;
        } else {
            if (port(p)->isOutput()) {
                changed = true;
                ++reads;
            }
            if (port(p)->isInput()) {
                changed = true;
                ++writes;
            }
        }
    }
    if (changed)
    {
        maxReads_ = reads;
        maxWrites_ = writes;
    }
    return changed;
}
References TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), maxReads_, maxWrites_, TTAMachine::BaseRegisterFile::port(), and TTAMachine::Unit::portCount().
Referenced by maxReads(), and maxWrites().
zeroRegister()
bool TTAMachine::RegisterFile::zeroRegister () const virtual
Definition at line 629 of file RegisterFile.cc.
{
    return zeroRegister_;
}
References zeroRegister_.
Referenced by TDGen::analyzeRegisters(), MachineStateBuilder::buildMachineState(), ProGeTools::checkForSelectableRF(), ProGe::RV32MicroCodeGenerator::findRF(), BlockImplementationDialog::onHDBSelection(), RegisterRenamer::registersOfRFs(), ComponentImplementationSelector::rfImplementations(), and RFDialog::updateWidgets().
Member Data Documentation
guardLatency_
int TTAMachine::RegisterFile::guardLatency_ private
The guard latency of the register file.
Definition at line 133 of file RegisterFile.hh.
Referenced by guardLatency(), isArchitectureEqual(), saveState(), and setGuardLatency().
maxReads_
int TTAMachine::RegisterFile::maxReads_ mutable private
Max number of ports that can read a register all in the same cycle.
Definition at line 129 of file RegisterFile.hh.
Referenced by isArchitectureEqual(), maxReads(), saveState(), setMaxReads(), and updateMaxReadsAndWrites().
maxWrites_
int TTAMachine::RegisterFile::maxWrites_ mutable private
Max number of ports that can read a register all in the same cycle.
Definition at line 131 of file RegisterFile.hh.
Referenced by isArchitectureEqual(), maxWrites(), saveState(), setMaxWrites(), and updateMaxReadsAndWrites().
OSKEY_GUARD_LATENCY
const string TTAMachine::RegisterFile::OSKEY_GUARD_LATENCY = "g_latency" static
ObjectState attribute key for the guard latency.
Definition at line 108 of file RegisterFile.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSKEY_MAX_READS
const string TTAMachine::RegisterFile::OSKEY_MAX_READS = "max_r" static
ObjectState attribute key for maximum simultaneous readers.
Definition at line 104 of file RegisterFile.hh.
Referenced by ADFSerializer::immediateUnitToMDF(), loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSKEY_MAX_WRITES
const string TTAMachine::RegisterFile::OSKEY_MAX_WRITES = "max_w" static
ObjectState attribute key for maximum simultaneous writers.
Definition at line 106 of file RegisterFile.hh.
Referenced by ADFSerializer::immediateUnitToMDF(), loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSKEY_TYPE
const string TTAMachine::RegisterFile::OSKEY_TYPE = "type" static
ObjectState attribute key for register file type.
Definition at line 96 of file RegisterFile.hh.
Referenced by ADFSerializer::immediateUnitToMDF(), loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSKEY_ZERO_REGISTER
const string TTAMachine::RegisterFile::OSKEY_ZERO_REGISTER = "zero_register" static
ObjectState attribute key for zero register flag.
Definition at line 110 of file RegisterFile.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSNAME_REGISTER_FILE
const string TTAMachine::RegisterFile::OSNAME_REGISTER_FILE = "reg_file" static
ObjectState name for RegisterFile.
Definition at line 94 of file RegisterFile.hh.
Referenced by ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), TTAMachine::Machine::loadState(), loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), and saveState().
OSVALUE_NORMAL
const string TTAMachine::RegisterFile::OSVALUE_NORMAL = "normal" static
ObjectState attribute value for normal register file type.
Definition at line 98 of file RegisterFile.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSVALUE_RESERVED
const string TTAMachine::RegisterFile::OSVALUE_RESERVED = "reserved" static
ObjectState attribute value for reserved register file type.
Definition at line 100 of file RegisterFile.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
OSVALUE_VOLATILE
const string TTAMachine::RegisterFile::OSVALUE_VOLATILE = "volatile" static
ObjectState attribute value for volatile register file type.
Definition at line 102 of file RegisterFile.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), and saveState().
type_
Type TTAMachine::RegisterFile::type_ private
Type of the register file.
Definition at line 136 of file RegisterFile.hh.
Referenced by isArchitectureEqual(), isNormal(), isReserved(), isVolatile(), saveState(), setType(), and type().
zeroRegister_
bool TTAMachine::RegisterFile::zeroRegister_ private
Definition at line 138 of file RegisterFile.hh.
Referenced by saveState(), setZeroRegister(), and zeroRegister().
The documentation for this class was generated from the following files:
RegisterFile.hh
RegisterFile.cc