OpenASIP: CompileTools Class Reference
CompileTools Class Reference
#include <CompileTools.hh>
Static Public Member Functions
static TTAProgram::Program * compileAsC (const TTAMachine::Machine &target, std::stringstream &code, const std::string &cflags="")
static TTAProgram::Program * compileAsC (const TTAMachine::Machine &target, const std::string &code, const std::string &cflags="")
static TTAProgram::Program * compileAsLLVM (const TTAMachine::Machine &target, const std::stringstream &code, const std::string compileOptions)
Private Member Functions
CompileTools ()
virtual ~CompileTools ()
Detailed Description
Definition at line 51 of file CompileTools.hh.
Constructor & Destructor Documentation
CompileTools()
CompileTools::CompileTools () private
Definition at line 46 of file CompileTools.cc.
{
}
~CompileTools()
CompileTools::~CompileTools () private virtual
Definition at line 49 of file CompileTools.cc.
{
}
Member Function Documentation
compileAsC() [1/2]
TTAProgram::Program * CompileTools::compileAsC (const TTAMachine::Machine & target, const std::string & code, const std::string & cflags = "") static
Definition at line 53 of file CompileTools.cc.
{
    std::stringstream codeStream(code);
    return compileAsC(target, codeStream, cflags);
}
References compileAsC().
compileAsC() [2/2]
TTAProgram::Program * CompileTools::compileAsC (const TTAMachine::Machine & target, std::stringstream & code, const std::string & cflags = "") static
Interprets code as C code and tries to convert it to Program.
Returns
Pointer to new program if compilation is successful, otherwise NULL.
Definition at line 68 of file CompileTools.cc.
{
    using namespace TTAProgram;
    Program* resultProgram = NULL;
    std::string tempDir = FileSystem::createTempDirectory(
        FileSystem::currentWorkingDir());
    if (tempDir.empty()) {
        return NULL;
    }
    std::string tempAdfFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.adf";
    std::string sourceCFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.c";
    std::string resultFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.tpef";
    ADFSerializer serializer;
    serializer.setDestinationFile(tempAdfFile);
    try {
        serializer.writeMachine(target);
    } catch (const SerializerException& exception) {
        FileSystem::removeFileOrDirectory(tempDir);
        return NULL;
    }
    std::ofstream cStream(sourceCFile);
    if (cStream.fail()) {
        FileSystem::removeFileOrDirectory(tempDir);
        return NULL;
    }
    cStream << code.rdbuf();
    cStream.close();
    std::string command = Environment::tceCompiler() + " "
        "-a " + tempAdfFile + " " +
        "-o " + resultFile + " " +
        cflags + " " +
        sourceCFile;
    std::vector<std::string> output;
    if (Application::runShellCommandAndGetOutput(command, output) == 0 &&
        FileSystem::fileExists(resultFile)) {
        try {
            resultProgram = Program::loadFromTPEF(resultFile, target);
        } catch (Exception& e) {
            FileSystem::removeFileOrDirectory(tempDir);
            return NULL;
        }
    }
    FileSystem::removeFileOrDirectory(tempDir);
    return resultProgram;
}
References FileSystem::createTempDirectory(), FileSystem::currentWorkingDir(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), FileSystem::removeFileOrDirectory(), Application::runShellCommandAndGetOutput(), XMLSerializer::setDestinationFile(), Environment::tceCompiler(), and ADFSerializer::writeMachine().
Referenced by compileAsC().
compileAsLLVM()
TTAProgram::Program * CompileTools::compileAsLLVM (const TTAMachine::Machine & target, const std::stringstream & code, const std::string compileOptions) static
Interprets string stream as LLVM (.ll) assembly code and tries to convert it to Program.
Returns
Pointer to new program if compilation is successful, otherwise NULL.
Definition at line 133 of file CompileTools.cc.
{
    using namespace TTAProgram;
    Program* resultProgram = NULL;
    std::string tempDir = FileSystem::createTempDirectory(
        FileSystem::currentWorkingDir());
    if (tempDir.empty()) {
        return NULL;
    }
    std::string tempAdfFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.adf";
    std::string sourceLLFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.ll";
    std::string resultFile =
        tempDir + FileSystem::DIRECTORY_SEPARATOR + "temp.tpef";
    ADFSerializer serializer;
    serializer.setDestinationFile(tempAdfFile);
    try {
        serializer.writeMachine(target);
    } catch (const SerializerException& exception) {
        FileSystem::removeFileOrDirectory(tempDir);
        return NULL;
    }
    std::ofstream llStream(sourceLLFile);
    if (llStream.fail()) {
        FileSystem::removeFileOrDirectory(tempDir);
        return NULL;
    }
    llStream << code.rdbuf();
    llStream.close();
    std::string compileLLFilecmd = Environment::tceCompiler() + " "
        +  "-a " + tempAdfFile + " "
        + "-o " + resultFile + " " + " "
        + compileOptions + " "
        +  sourceLLFile;
    if (Application::runShellCommandSilently(compileLLFilecmd) == 0) {
        try {
            resultProgram = Program::loadFromTPEF(resultFile, target);
        } catch (Exception& e) {
            FileSystem::removeFileOrDirectory(tempDir);
            return NULL;
        }
    }
    FileSystem::removeFileOrDirectory(tempDir);
    return resultProgram;
}
References FileSystem::createTempDirectory(), FileSystem::currentWorkingDir(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::removeFileOrDirectory(), Application::runShellCommandSilently(), XMLSerializer::setDestinationFile(), Environment::tceCompiler(), and ADFSerializer::writeMachine().
The documentation for this class was generated from the following files:
CompileTools.hh
CompileTools.cc