OpenASIP: AddFUImplementationCmd Class Reference
AddFUImplementationCmd Class Reference
#include <AddFUImplementationCmd.hh>
Public Member Functions
AddFUImplementationCmd ()
virtual ~AddFUImplementationCmd ()
virtual bool Do ()
virtual int id () const
virtual AddFUImplementationCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding implementation of a FU architecture to HDB.
Definition at line 41 of file AddFUImplementationCmd.hh.
Constructor & Destructor Documentation
AddFUImplementationCmd()
AddFUImplementationCmd::AddFUImplementationCmd ()
The Constructor.
Definition at line 53 of file AddFUImplementationCmd.cc.
                                               :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_FU_IMPLEMENTATION, NULL) {
}
Referenced by create().
~AddFUImplementationCmd()
AddFUImplementationCmd::~AddFUImplementationCmd () virtual
The Destructor.
Definition at line 61 of file AddFUImplementationCmd.cc.
{
}
Member Function Documentation
create()
AddFUImplementationCmd * AddFUImplementationCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 155 of file AddFUImplementationCmd.cc.
{
    return new AddFUImplementationCmd();
}
References AddFUImplementationCmd().
Do()
bool AddFUImplementationCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 68 of file AddFUImplementationCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    HDB::FUImplementation* implementation =
        new HDB::FUImplementation("", "", "","", "", "");
    HDB::FUEntry* entry = NULL;
    if (browser->isFUEntrySelected()) {
        entry = manager->fuByEntryID(browser->selectedFUEntry());
    } else if (browser->isFUArchitectureSelected()) {
        int id = manager->addFUEntry();
        manager->setArchitectureForFU(id, browser->selectedFUArchitecture());
        entry = manager->fuByEntryID(id);
    } else {
        return false;
    }
    const TTAMachine::FunctionUnit& arch =
        entry->architecture().architecture();
    for (int i = 0; i < arch.portCount(); i++) {
        new HDB::FUPortImplementation(
            "", arch.port(i)->name(), "", "", "", *implementation);
    }
    FUImplementationDialog dialog(parentWindow(), -1, *implementation, arch);
    if (dialog.ShowModal() == wxID_OK) {
        try {
            entry->setImplementation(implementation);
            int id = manager->addFUImplementation(*entry);
            wxGetApp().mainFrame().update();
            wxGetApp().mainFrame().browser()->selectFUImplementation(id);
        } catch (Exception& e) {
            wxString message = _T("Error:\n");
            message.Append(WxConversion::toWxString(e.errorMessage()));
            message.Append(_T("\n"));
            message.Append(WxConversion::toWxString(e.lineNum()));
             message.Append(_T(": "));
            message.Append(WxConversion::toWxString(e.fileName()));
            ErrorDialog dialog(parentWindow(), message);
            dialog.ShowModal();
            delete entry;
            delete implementation;
            return false;
        }
    } else {
        delete implementation;
    }
    delete entry;
    return true;
}
References HDB::HDBManager::addFUEntry(), HDB::HDBManager::addFUImplementation(), HDB::FUArchitecture::architecture(), HDB::FUEntry::architecture(), Exception::errorMessage(), Exception::fileName(), HDB::HDBManager::fuByEntryID(), implementation, HDBBrowserWindow::isFUArchitectureSelected(), HDBBrowserWindow::isFUEntrySelected(), Exception::lineNum(), TTAMachine::Port::name(), GUICommand::parentWindow(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), HDBBrowserWindow::selectedFUArchitecture(), HDBBrowserWindow::selectedFUEntry(), HDB::HDBManager::setArchitectureForFU(), HDB::FUEntry::setImplementation(), and WxConversion::toWxString().
icon()
std::string AddFUImplementationCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 134 of file AddFUImplementationCmd.cc.
{
    return "";
}
id()
int AddFUImplementationCmd::id () const virtual
Returns the command id.
Returns
Command identifier.
Implements GUICommand.
Definition at line 144 of file AddFUImplementationCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION;
}
References HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION.
isEnabled()
bool AddFUImplementationCmd::isEnabled () virtual
Returns true if the command should be enabled in the tool/menubar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 166 of file AddFUImplementationCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (browser->isFUArchitectureSelected()) {
        return true;
    } else if (browser->isFUEntrySelected()) {
        HDB::FUEntry* entry = manager->fuByEntryID(browser->selectedFUEntry());
        if (entry->hasArchitecture() && !entry->hasImplementation()) {
            delete entry;
            return true;
        }
        delete entry;
    }
    return false;
}
References HDB::HDBManager::fuByEntryID(), HDB::FUEntry::hasArchitecture(), HDB::FUEntry::hasImplementation(), HDBBrowserWindow::isFUArchitectureSelected(), HDBBrowserWindow::isFUEntrySelected(), and HDBBrowserWindow::selectedFUEntry().
The documentation for this class was generated from the following files:
AddFUImplementationCmd.hh
AddFUImplementationCmd.cc