OpenASIP: OTAFormatListDialog Class Reference
OTAFormatListDialog Class Reference
#include <OTAFormatListDialog.hh>
Public Member Functions
OTAFormatListDialog (wxWindow *parent, TTAMachine::Machine *machine)
virtual ~OTAFormatListDialog ()
Private Types
enum {
ID_OTA_FORMAT_LIST = 10000 , ID_OPERATION_LIST , ID_LINE , ID_HELP ,
ID_ADD_OTA_FORMAT , ID_DELETE_OTA_FORMAT , ID_ADD_OPERATION , ID_EDIT_OPERATION ,
ID_DELETE_OPERATION , ID_NAME , ID_LABEL_NAME
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void updateOperationList ()
void onOTAFormatSelection (wxListEvent &event)
void onOperationSelection (wxListEvent &event)
void onOTAFormatName (wxCommandEvent &event)
void onAddOTAFormat (wxCommandEvent &event)
void onDeleteOTAFormat (wxCommandEvent &event)
void onAddOperation (wxCommandEvent &event)
void onEditOperation (wxCommandEvent &event)
void onDeleteOperation (wxCommandEvent &event)
void setTexts ()
bool validFormatName () const
TTAMachine::OperationTriggeredFormat * selectedOTAFormat ()
std::string selectedOperation ()
Private Attributes
TTAMachine::Machine * machine_
Parent machine of the instruction OTAFormats.
wxStaticBoxSizer * OTAFormatSizer_
Box sizer around the OTAFormat list.
wxStaticBoxSizer * operationSizer_
Box sizer around the operation list.
wxListCtrl * OTAFormatList_
Widget for list of OTAFormats.
wxListCtrl * operationList_
Widget for list of operations in the selected OTAFormat.
wxString OTAFormatName_
Name of the new OTAFormat.
Detailed Description
Dialog for listing and editing instruction OTAFormats in a machine.
Definition at line 44 of file OTAFormatListDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_OTA_FORMAT_LIST
ID_OPERATION_LIST
ID_LINE
ID_HELP
ID_ADD_OTA_FORMAT
ID_DELETE_OTA_FORMAT
ID_ADD_OPERATION
ID_EDIT_OPERATION
ID_DELETE_OPERATION
ID_NAME
ID_LABEL_NAME
Definition at line 80 of file OTAFormatListDialog.hh.
         {
        ID_OTA_FORMAT_LIST = 10000,
        ID_OPERATION_LIST,
        ID_LINE,
        ID_HELP,
        ID_ADD_OTA_FORMAT,
        ID_DELETE_OTA_FORMAT,
        ID_ADD_OPERATION,
        ID_EDIT_OPERATION,
        ID_DELETE_OPERATION,
        ID_NAME,
        ID_LABEL_NAME
    };
Constructor & Destructor Documentation
OTAFormatListDialog()
OTAFormatListDialog::OTAFormatListDialog (wxWindow * parent, TTAMachine::Machine * machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Parent machine of the instruction OTAFormats.
Definition at line 72 of file OTAFormatListDialog.cc.
                      :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    machine_(machine),
    OTAFormatName_(_T("")) {
    createContents(this, true, true);
    OTAFormatList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_OTA_FORMAT_LIST));
    operationList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &OTAFormatName_));
    FindWindow(ID_ADD_OTA_FORMAT)->Disable();
    FindWindow(ID_DELETE_OTA_FORMAT)->Disable();
    // set widget texts
    setTexts();
}
~OTAFormatListDialog()
OTAFormatListDialog::~OTAFormatListDialog () virtual
The Destructor.
Definition at line 96 of file OTAFormatListDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * OTAFormatListDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 417 of file OTAFormatListDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Instruction OTAFormats:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    OTAFormatSizer_ = item2;
    wxListCtrl *item4 = new wxListCtrl( parent, ID_OTA_FORMAT_LIST, wxDefaultPosition, wxSize(160,200), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item5, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, ID_ADD_OTA_FORMAT, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, ID_DELETE_OTA_FORMAT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("OTAFormat Operations:") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );
    operationSizer_ = item11;
    wxListCtrl *item13 = new wxListCtrl( parent, ID_OPERATION_LIST, wxDefaultPosition, wxSize(250,245), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item11->Add( item13, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item15 = new wxButton( parent, ID_ADD_OPERATION, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item17 = new wxButton( parent, ID_DELETE_OPERATION, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    item11->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item18 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item18, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item19 = new wxGridSizer( 2, 0, 0 );
    wxButton *item20 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item22 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item23 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    item19->Add( item21, 0, wxALL, 5 );
    item0->Add( item19, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_OPERATION, ID_ADD_OTA_FORMAT, ID_DELETE_OPERATION, ID_DELETE_OTA_FORMAT, ID_HELP, ID_LABEL_NAME, ID_LINE, ID_NAME, ID_OPERATION_LIST, ID_OTA_FORMAT_LIST, operationSizer_, and OTAFormatSizer_.
onAddOperation()
void OTAFormatListDialog::onAddOperation (wxCommandEvent & event) private
Handles the add Operation button event.
Definition at line 382 of file OTAFormatListDialog.cc.
{
    if (selectedOTAFormat() == NULL) {
        assert(false);
    }
    OTAOperationDialog dialog(this, selectedOTAFormat());
    dialog.ShowModal();
    updateOperationList();
}
References assert, selectedOTAFormat(), and updateOperationList().
onAddOTAFormat()
void OTAFormatListDialog::onAddOTAFormat (wxCommandEvent & event) private
Handles the Add tempalte button event.
Adds a new OTAFormat to the machine.
Definition at line 304 of file OTAFormatListDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    string trimmedName =
        WxConversion::toString(OTAFormatName_.Trim(false).Trim(true));
    // Check the name validity.
    if (!validFormatName()) {
        std::string message = "Format name is illegal. Legal names are:\n" + \
        RISCVFields::RISCV_R_TYPE_NAME   + "\n" + \
        RISCVFields::RISCV_R1_TYPE_NAME  + "\n" + \
        RISCVFields::RISCV_R3R_TYPE_NAME + "\n" + \
        RISCVFields::RISCV_R1R_TYPE_NAME + "\n" + \
        RISCVFields::RISCV_I_TYPE_NAME   + "\n" + \
        RISCVFields::RISCV_S_TYPE_NAME   + "\n" + \
        RISCVFields::RISCV_B_TYPE_NAME   + "\n" + \
        RISCVFields::RISCV_U_TYPE_NAME   + "\n" + \
        RISCVFields::RISCV_J_TYPE_NAME   + "\n";
        InformationDialog warning(
            this, WxConversion::toWxString(message));
        warning.ShowModal();
        return;
    }
    Machine::OperationTriggeredFormatNavigator navigator =
        machine_->operationTriggeredFormatNavigator();
    if (navigator.hasItem(trimmedName)) {
        ProDeTextGenerator* prodeTexts =
            ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        format a_tmplate =
            prodeTexts->text(ProDeTextGenerator::COMP_AN_OTA_FORMAT);
        format machine =
            prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
        format tmplate =
            prodeTexts->text(ProDeTextGenerator::COMP_OTA_FORMAT);
        message % trimmedName % a_tmplate.str() % machine.str() %
            tmplate.str();
        WarningDialog warning(this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    new OperationTriggeredFormat(trimmedName, *machine_);
    OTAFormatName_ = _T("");
    TransferDataToWindow();
}
References assert, ProDeTextGenerator::COMP_AN_OTA_FORMAT, ProDeTextGenerator::COMP_MACHINE, ProDeTextGenerator::COMP_OTA_FORMAT, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), ProDeTextGenerator::instance(), machine, machine_, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Machine::operationTriggeredFormatNavigator(), OTAFormatName_, RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, RISCVFields::RISCV_U_TYPE_NAME, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), TransferDataToWindow(), and validFormatName().
onDeleteOperation()
void OTAFormatListDialog::onDeleteOperation (wxCommandEvent & event) private
Handles the delete Operation button event.
Definition at line 397 of file OTAFormatListDialog.cc.
{
    if (selectedOTAFormat() == NULL) {
        assert(false);
    }
    selectedOTAFormat()->removeOperation(selectedOperation());
    updateOperationList();
}
References assert, TTAMachine::OperationTriggeredFormat::removeOperation(), selectedOperation(), selectedOTAFormat(), and updateOperationList().
onDeleteOTAFormat()
void OTAFormatListDialog::onDeleteOTAFormat (wxCommandEvent & event) private
Deletes the selected OTAFormat.
Definition at line 241 of file OTAFormatListDialog.cc.
{
    delete selectedOTAFormat();
    TransferDataToWindow();
    wxListEvent dummy;
    onOTAFormatSelection(dummy);
}
References dummy, onOTAFormatSelection(), selectedOTAFormat(), and TransferDataToWindow().
onEditOperation()
void OTAFormatListDialog::onEditOperation (wxCommandEvent & event) private
onOperationSelection()
void OTAFormatListDialog::onOperationSelection (wxListEvent & event) private
Updates the edit/delete Operation buttons when the Operation selection changes.
Definition at line 228 of file OTAFormatListDialog.cc.
{
    if (operationList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_DELETE_OPERATION)->Enable();
    } else {
        FindWindow(ID_DELETE_OPERATION)->Disable();
    }
}
References ID_DELETE_OPERATION, and operationList_.
Referenced by updateOperationList().
onOTAFormatName()
void OTAFormatListDialog::onOTAFormatName (wxCommandEvent & event) private
Enables and disables the Add OTAFormat button when text is entered in the OTAFormat name widget.
Definition at line 360 of file OTAFormatListDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = OTAFormatName_.Trim(false).Trim(true);
    Machine::OperationTriggeredFormatNavigator nav =
    machine_->operationTriggeredFormatNavigator();
    if (trimmedName == _T("")) {
        FindWindow(ID_ADD_OTA_FORMAT)->Disable();
    //Only 6 formats in RISC-V + 3 custom formats
    } else if (nav.count() > 8) {
        FindWindow(ID_ADD_OTA_FORMAT)->Disable();
    } else {
        FindWindow(ID_ADD_OTA_FORMAT)->Enable();
    }
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::count(), ID_ADD_OTA_FORMAT, machine_, TTAMachine::Machine::operationTriggeredFormatNavigator(), and OTAFormatName_.
onOTAFormatSelection()
void OTAFormatListDialog::onOTAFormatSelection (wxListEvent & event) private
Updates the Operation list when the OTAFormat selection changes.
Definition at line 214 of file OTAFormatListDialog.cc.
{
    if (OTAFormatList_->GetSelectedItemCount() == 0) {
        FindWindow(ID_DELETE_OTA_FORMAT)->Disable();
    } else {
        FindWindow(ID_DELETE_OTA_FORMAT)->Enable();
    }
    updateOperationList();
}
References ID_DELETE_OTA_FORMAT, OTAFormatList_, and updateOperationList().
Referenced by onDeleteOTAFormat().
selectedOperation()
string OTAFormatListDialog::selectedOperation () private
Returns name of the selected Operation.
Returns
Name of the selected Operation.
Definition at line 276 of file OTAFormatListDialog.cc.
{
    string name = WidgetTools::lcStringSelection(operationList_, 0);
    return name;
}
References WidgetTools::lcStringSelection(), and operationList_.
Referenced by onDeleteOperation().
selectedOTAFormat()
OperationTriggeredFormat * OTAFormatListDialog::selectedOTAFormat () private
Returns pointer to the selected OperationTriggeredFormat.
Returns
Pointer to the selected OperationTriggeredFormat.
Definition at line 255 of file OTAFormatListDialog.cc.
{
    long item = -1;
    item = OTAFormatList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item < 0) {
        return NULL;
    }
    OperationTriggeredFormat* f =
        machine_->operationTriggeredFormatNavigator().item(item);
    return f;
}
References TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Machine::operationTriggeredFormatNavigator(), and OTAFormatList_.
Referenced by onAddOperation(), onDeleteOperation(), onDeleteOTAFormat(), and updateOperationList().
setTexts()
void OTAFormatListDialog::setTexts () private
Sets texts for widgets.
Definition at line 104 of file OTAFormatListDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_OTA_FORMATS_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_OTA_FORMAT),
                          GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_OTA_FORMAT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_OPERATION),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_OPERATION),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_OTA_FORMATS_BOX);
    WidgetTools::setWidgetLabel(OTAFormatSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_OTA_FORMATS_OPERATIONS_BOX);
    WidgetTools::setWidgetLabel(operationSizer_, fmt.str());
    // Create instruction OTAFormat list columns.
    wxListCtrl* OTAFormatList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OTA_FORMAT_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    OTAFormatList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 160);
    // Create OTAFormat Operation list columns.
    wxListCtrl* OperationList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_OTA_OPERATION);
    OperationList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 100);
}
References ID_ADD_OPERATION, ID_ADD_OTA_FORMAT, ID_DELETE_OPERATION, ID_DELETE_OTA_FORMAT, ID_HELP, ID_LABEL_NAME, ID_OPERATION_LIST, ID_OTA_FORMAT_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), operationSizer_, OTAFormatSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_OTA_OPERATION, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_OTA_FORMATS_BOX, ProDeTextGenerator::TXT_OTA_FORMATS_DIALOG_TITLE, and ProDeTextGenerator::TXT_OTA_FORMATS_OPERATIONS_BOX.
TransferDataToWindow()
bool OTAFormatListDialog::TransferDataToWindow () private virtual
Transfers data from the machine to the dialog widgets.
Definition at line 166 of file OTAFormatListDialog.cc.
{
    // update OTAFormat list
    OTAFormatList_->DeleteAllItems();
    Machine::OperationTriggeredFormatNavigator navigator =
        machine_->operationTriggeredFormatNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        OTAFormatList_->InsertItem(
            i, WxConversion::toWxString(navigator.item(i)->name()));
    }
    updateOperationList();
    return wxDialog::TransferDataToWindow();
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Machine::operationTriggeredFormatNavigator(), OTAFormatList_, WxConversion::toWxString(), and updateOperationList().
Referenced by onAddOTAFormat(), and onDeleteOTAFormat().
updateOperationList()
void OTAFormatListDialog::updateOperationList () private
Updates the OTAFormat Operation list.
Definition at line 185 of file OTAFormatListDialog.cc.
{
    operationList_->DeleteAllItems();
    operationList_->Enable();
    OperationTriggeredFormat* f = selectedOTAFormat();
    if (f == NULL) {
        FindWindow(ID_ADD_OPERATION)->Disable();
        return;
    }
    for (int i = 0; i < f->operationCount(); i++) {
        operationList_->InsertItem(
            0, WxConversion::toWxString(f->operationAtIndex(i)));
    }
    FindWindow(ID_ADD_OPERATION)->Enable();
    wxListEvent dummy;
    onOperationSelection(dummy);
}
References dummy, ID_ADD_OPERATION, onOperationSelection(), TTAMachine::OperationTriggeredFormat::operationAtIndex(), TTAMachine::OperationTriggeredFormat::operationCount(), operationList_, selectedOTAFormat(), and WxConversion::toWxString().
Referenced by onAddOperation(), onDeleteOperation(), onOTAFormatSelection(), and TransferDataToWindow().
validFormatName()
bool OTAFormatListDialog::validFormatName () const private
Definition at line 282 of file OTAFormatListDialog.cc.
{
    if (OTAFormatName_ == RISCVFields::RISCV_R_TYPE_NAME   ||
        OTAFormatName_ == RISCVFields::RISCV_R1_TYPE_NAME  ||
        OTAFormatName_ == RISCVFields::RISCV_R3R_TYPE_NAME ||
        OTAFormatName_ == RISCVFields::RISCV_R1R_TYPE_NAME ||
        OTAFormatName_ == RISCVFields::RISCV_I_TYPE_NAME   ||
        OTAFormatName_ == RISCVFields::RISCV_S_TYPE_NAME   ||
        OTAFormatName_ == RISCVFields::RISCV_B_TYPE_NAME   ||
        OTAFormatName_ == RISCVFields::RISCV_U_TYPE_NAME   ||
        OTAFormatName_ == RISCVFields::RISCV_J_TYPE_NAME) {
        return true;
    }
    return false;
}
References OTAFormatName_, RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, and RISCVFields::RISCV_U_TYPE_NAME.
Referenced by onAddOTAFormat().
Member Data Documentation
machine_
TTAMachine::Machine* OTAFormatListDialog::machine_ private
Parent machine of the instruction OTAFormats.
Definition at line 67 of file OTAFormatListDialog.hh.
Referenced by onAddOTAFormat(), onOTAFormatName(), selectedOTAFormat(), and TransferDataToWindow().
operationList_
wxListCtrl* OTAFormatListDialog::operationList_ private
Widget for list of operations in the selected OTAFormat.
Definition at line 75 of file OTAFormatListDialog.hh.
Referenced by onOperationSelection(), selectedOperation(), and updateOperationList().
operationSizer_
wxStaticBoxSizer* OTAFormatListDialog::operationSizer_ private
Box sizer around the operation list.
Definition at line 71 of file OTAFormatListDialog.hh.
Referenced by createContents(), and setTexts().
OTAFormatList_
wxListCtrl* OTAFormatListDialog::OTAFormatList_ private
Widget for list of OTAFormats.
Definition at line 73 of file OTAFormatListDialog.hh.
Referenced by onOTAFormatSelection(), selectedOTAFormat(), and TransferDataToWindow().
OTAFormatName_
wxString OTAFormatListDialog::OTAFormatName_ private
Name of the new OTAFormat.
Definition at line 77 of file OTAFormatListDialog.hh.
Referenced by onAddOTAFormat(), onOTAFormatName(), and validFormatName().
OTAFormatSizer_
wxStaticBoxSizer* OTAFormatListDialog::OTAFormatSizer_ private
Box sizer around the OTAFormat list.
Definition at line 69 of file OTAFormatListDialog.hh.
Referenced by createContents(), and setTexts().
The documentation for this class was generated from the following files:
OTAFormatListDialog.hh
OTAFormatListDialog.cc