OpenASIP: WidgetTools Class Reference
WidgetTools Class Reference
#include <WidgetTools.hh>
Static Public Member Functions
static void setWidgetLabel (wxWindow *widget, std::string text)
static void setWidgetLabel (wxStaticBoxSizer *widget, std::string text)
static void setLabel (Texts::TextGenerator *generator, wxWindow *widget, int textID)
static std::string lcStringSelection (wxListCtrl *list, int column)
Detailed Description
Helper functions for handling wxWidgets controls.
Definition at line 46 of file WidgetTools.hh.
Member Function Documentation
lcStringSelection()
std::string WidgetTools::lcStringSelection (wxListCtrl * list, int column) static
Returns wxListCtrl's first selected item as a string.
Parameters
list List to search for selected item.
column Column of the string to return.
Returns
Selected list item string, or empty string if no item is selected.
Definition at line 108 of file WidgetTools.cc.
{
    long item = -1;
    item = list->GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return "";
    }
    wxListItem info;
    info.SetId(item);
    info.SetColumn(column);
    list->GetItem(info);
    return WxConversion::toString(info.GetText());
}
References WxConversion::toString().
Referenced by BlockImplementationDialog::doOK(), OperationDialog::onBindOperand(), FUImplementationDialog::onClearOpcode(), OperationDialog::onDeleteOperand(), FUDialog::onDeleteOperation(), GCUDialog::onDeleteOperation(), FUImplementationDialog::onDeleteSourceFile(), RFImplementationDialog::onDeleteSourceFile(), OperationPropertyDialog::onModifyInputOperand(), OperationPropertyDialog::onModifyOutputOperand(), OperationPropertyDialog::onMoveInputDown(), OperationPropertyDialog::onMoveInputUp(), OperationPropertyDialog::onMoveOutputDown(), OperationPropertyDialog::onMoveOutputUp(), RFImplementationDialog::onMoveSourceFileDown(), FUImplementationDialog::onMoveSourceFileDown(), RFImplementationDialog::onMoveSourceFileUp(), FUImplementationDialog::onMoveSourceFileUp(), FUImplementationDialog::onOpcodeSelection(), OperationDialog::onOperandSelection(), OperationPropertyDialog::onSelection(), FUImplementationDialog::onSetOpcode(), FUImplementationDialog::onSourceFileSelection(), RFImplementationDialog::onSourceFileSelection(), SimulateDialog::onUpdateValue(), OSEdInfoView::selectedModule(), OSEdInfoView::selectedOperation(), FUDialog::selectedOperation(), GCUDialog::selectedOperation(), OTAFormatListDialog::selectedOperation(), OSEdInfoView::selectedPath(), FUDialog::selectedPort(), GCUDialog::selectedPort(), and TemplateListDialog::selectedSlot().
setLabel()
void WidgetTools::setLabel (Texts::TextGenerator * generator, wxWindow * widget, int textID) static
Sets a widget label text.
Parameters
generator TextGenerator which provides the label text.
widget Widget to set the label to.
textID Text generator string ID for the label text.
Definition at line 92 of file WidgetTools.cc.
{
    format fmt = generator->text(textID);
    setWidgetLabel(widget, fmt.str());
}
References setWidgetLabel(), and Texts::TextGenerator::text().
Referenced by OperationPropertyDialog::setBehaviorLabel(), GCUDialog::setLabels(), AddModuleDialog::setTexts(), InputOperandDialog::setTexts(), MemoryDialog::setTexts(), OperationDAGDialog::setTexts(), OperationPropertyDialog::setTexts(), OSEdAboutDialog::setTexts(), OSEdOptionsDialog::setTexts(), OutputOperandDialog::setTexts(), ResultDialog::setTexts(), SimulateDialog::setTexts(), AboutDialog::setTexts(), AddressSpaceDialog::setTexts(), AddressSpacesDialog::setTexts(), BridgeDialog::setTexts(), BusDialog::setTexts(), FUDialog::setTexts(), FUGuardDialog::setTexts(), FUPortDialog::setTexts(), ImmediateSlotDialog::setTexts(), IUDialog::setTexts(), IUPortDialog::setTexts(), OperationDialog::setTexts(), OTAFormatListDialog::setTexts(), RFDialog::setTexts(), RFGuardDialog::setTexts(), RFPortDialog::setTexts(), SocketDialog::setTexts(), SRPortDialog::setTexts(), TemplateListDialog::setTexts(), and TemplateSlotDialog::setTexts().
setWidgetLabel() [1/2]
void WidgetTools::setWidgetLabel (wxStaticBoxSizer * sizer, std::string text) static
Sets a boxsizer label text.
Parameters
sizer wxStaticBoxSizer to set the label to.
textId Enumerated ID which identifies the text label.
Definition at line 76 of file WidgetTools.cc.
{
    wxControl* box = sizer->GetStaticBox();
    wxString label = WxConversion::toWxString(text);
    box->SetLabel(label);
}
References WxConversion::toWxString().
setWidgetLabel() [2/2]
void WidgetTools::setWidgetLabel (wxWindow * widget, std::string text) static
Sets a wxControl label text.
Parameters
widget Widget to set the label to.
textId Enumerated ID which identifies the text label.
Exceptions
WrongSubclass If the widget was not a wxControl.
Definition at line 52 of file WidgetTools.cc.
{
    // wxControls
    if (widget->IsKindOf(CLASSINFO(wxControl))) {
        wxControl* control = dynamic_cast<wxControl*>(widget);
        assert(widget != NULL);
        wxString label = WxConversion::toWxString(text);
        control->SetLabel(label);
        return;
    }
    string method = "GUITextGenerator::setWidgetLabel()";
    string message = "Widget is not a wxControl, ";
    message += "unable to set the widget label.";
    throw WrongSubclass(__FILE__, __LINE__, method, message);
}
References assert, and WxConversion::toWxString().
Referenced by setLabel(), GCUDialog::setLabels(), InputOperandDialog::setTexts(), OperationPropertyDialog::setTexts(), SimulateDialog::setTexts(), AddressSpaceDialog::setTexts(), BusDialog::setTexts(), FUDialog::setTexts(), IUDialog::setTexts(), OperationDialog::setTexts(), OTAFormatListDialog::setTexts(), RFDialog::setTexts(), SocketDialog::setTexts(), and TemplateListDialog::setTexts().
The documentation for this class was generated from the following files:
WidgetTools.hh
WidgetTools.cc