OpenASIP: TPEF::LineNumElement Class Reference
TPEF::LineNumElement Class Reference
#include <LineNumElement.hh>
Public Member Functions
LineNumElement ()
virtual ~LineNumElement ()
void setLineNumber (HalfWord lineNum)
HalfWord lineNumber () const
void setInstruction (ReferenceManager::SafePointer *aRef)
void setInstruction (InstructionElement *aRef)
InstructionElement * instruction () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
HalfWord lineNumber_
Line number which line in the procedure this element refer.
const ReferenceManager::SafePointer * instruction_
Instruction element of source line.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Line number element.
Definition at line 48 of file LineNumElement.hh.
Constructor & Destructor Documentation
LineNumElement()
TPEF::LineNumElement::LineNumElement ()
Constructor.
Definition at line 43 of file LineNumElement.cc.
                               : SectionElement(),
    lineNumber_(0), instruction_(&SafePointer::null) {
}
~LineNumElement()
TPEF::LineNumElement::~LineNumElement () virtual
Destructor.
Definition at line 50 of file LineNumElement.cc.
{
}
Member Function Documentation
instruction()
InstructionElement * TPEF::LineNumElement::instruction () const
Referenced by TPEF::TPEFLineNumSectionWriter::actualWriteData().
lineNumber()
HalfWord TPEF::LineNumElement::lineNumber () const
Referenced by TPEF::TPEFLineNumSectionWriter::actualWriteData().
setInstruction() [1/2]
void TPEF::LineNumElement::setInstruction (InstructionElement * aRef)
setInstruction() [2/2]
void TPEF::LineNumElement::setInstruction (ReferenceManager::SafePointer * aRef)
Referenced by TPEF::TPEFLineNumSectionReader::readData().
setLineNumber()
void TPEF::LineNumElement::setLineNumber (HalfWord lineNum)
Referenced by TPEF::TPEFLineNumSectionReader::readData().
Member Data Documentation
instruction_
const ReferenceManager::SafePointer* TPEF::LineNumElement::instruction_ private
Instruction element of source line.
Definition at line 64 of file LineNumElement.hh.
lineNumber_
HalfWord TPEF::LineNumElement::lineNumber_ private
Line number which line in the procedure this element refer.
Definition at line 62 of file LineNumElement.hh.
The documentation for this class was generated from the following files:
LineNumElement.hh
LineNumElement.cc