OpenASIP: EditImmediateSlotsCmd Class Reference
EditImmediateSlotsCmd Class Reference
#include <EditImmediateSlotsCmd.hh>
Public Member Functions
EditImmediateSlotsCmd ()
virtual ~EditImmediateSlotsCmd ()
virtual bool Do ()
virtual int id () const
virtual EditImmediateSlotsCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing machine's immediate slots.
Definition at line 41 of file EditImmediateSlotsCmd.hh.
Constructor & Destructor Documentation
EditImmediateSlotsCmd()
EditImmediateSlotsCmd::EditImmediateSlotsCmd ()
The Constructor.
Definition at line 48 of file EditImmediateSlotsCmd.cc.
                                            :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_IMMEDIATE_SLOTS) {
}
Referenced by create().
~EditImmediateSlotsCmd()
EditImmediateSlotsCmd::~EditImmediateSlotsCmd () virtual
The Destructor.
Definition at line 56 of file EditImmediateSlotsCmd.cc.
{}
Member Function Documentation
create()
EditImmediateSlotsCmd * EditImmediateSlotsCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 102 of file EditImmediateSlotsCmd.cc.
{
    return new EditImmediateSlotsCmd();
}
References EditImmediateSlotsCmd().
Do()
bool EditImmediateSlotsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file EditImmediateSlotsCmd.cc.
{
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    ImmediateSlotDialog dialog(parentWindow(), model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, immediate slot modifications are
    // cancelled.
    model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string EditImmediateSlotsCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 112 of file EditImmediateSlotsCmd.cc.
{
    return ProDeConstants::CMD_ICON_DEFAULT;
}
References ProDeConstants::CMD_ICON_DEFAULT.
id()
int EditImmediateSlotsCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 93 of file EditImmediateSlotsCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_IMMEDIATE_SLOTS;
}
References ProDeConstants::COMMAND_EDIT_IMMEDIATE_SLOTS.
isEnabled()
bool EditImmediateSlotsCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 134 of file EditImmediateSlotsCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string EditImmediateSlotsCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 121 of file EditImmediateSlotsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_IMMEDIATE_SLOTS;
}
References ProDeConstants::CMD_SNAME_EDIT_IMMEDIATE_SLOTS.
The documentation for this class was generated from the following files:
EditImmediateSlotsCmd.hh
EditImmediateSlotsCmd.cc