OpenASIP: BusFactory Class Reference
BusFactory Class Reference
#include <BusFactory.hh>
Public Member Functions
BusFactory (EditPolicyFactory &editPolicyFactory)
virtual ~BusFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
BusFactory & operator= (BusFactory &old)
Assignment not allowed.
BusFactory (BusFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating bus EditParts corresponding to a given Machine Bus object.
Definition at line 45 of file BusFactory.hh.
Constructor & Destructor Documentation
BusFactory() [1/2]
BusFactory::BusFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 51 of file BusFactory.cc.
                                                          :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new SegmentFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~BusFactory()
BusFactory::~BusFactory () virtual
The Destructor.
Definition at line 60 of file BusFactory.cc.
{
}
BusFactory() [2/2]
BusFactory::BusFactory (BusFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * BusFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a bus.
Parameters
component Bus of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the Bus class.
Implements Factory.
Definition at line 71 of file BusFactory.cc.
{
    EditPart* busEditPart = EditPartFactory::checkCache(component);
    if (busEditPart != NULL) {
    return busEditPart;
    }
    Bus* bus = dynamic_cast<Bus*>(component);
    if (bus != NULL) {
    busEditPart = new EditPart();
    busEditPart->setModel(bus);
    BusFigure* fig = new BusFigure(bus->position());
    busEditPart->setFigure(fig);
    for (int i = 0; i < bus->segmentCount(); i++) {
        vector<Factory*>::const_iterator iter = factories_.begin();
        while (iter != factories_.end()) {
            EditPart* segEditPart =
                (*iter)->createEditPart((MachinePart*)bus->segment(i));
            if (segEditPart != NULL) {
                busEditPart->addChild(segEditPart);
                segEditPart->setSelectable(true);
                segEditPart->setParent(busEditPart);
            }
            iter++;
        }
    }
    busEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createBusEditPolicy();
    if (editPolicy != NULL) {
        busEditPart->installEditPolicy(editPolicy);
    }
    EditPartFactory::writeToCache(busEditPart);
    return busEditPart;
    } else {
    return NULL;
    }
}
References EditPart::addChild(), EditPartFactory::checkCache(), EditPolicyFactory::createBusEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::Bus::position(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), EditPart::setFigure(), EditPart::setModel(), EditPart::setParent(), EditPart::setSelectable(), and EditPartFactory::writeToCache().
operator=()
BusFactory & BusFactory::operator= (BusFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
BusFactory.hh
BusFactory.cc