OpenASIP: OperationPimpl Class Reference
OperationPimpl Class Reference
#include <OperationPimpl.hh>
Classes
struct OperationDAGInfo
Public Member Functions
~OperationPimpl ()
int numberOfInputs () const
int numberOfOutputs () const
TCEString name () const
void setCall (bool setting)
void setBranch (bool setting)
void setControlFlowOperation (bool setting)
Operand & operand (int id) const
Private Types
typedef std::vector< OperationDAGInfo > DAGContainer
Private Member Functions
OperationPimpl (const TCEString &name, OperationBehavior &behavior)
OperationPimpl ()
OperationPimpl (const OperationPimpl &)
Copying not allowed.
OperationPimpl & operator= (const OperationPimpl &)
Assignment not allowed.
TCEString description () const
void addDag (const TCEString &code)
void removeDag (int index)
int dagCount () const
OperationDAG & dag (int index) const
TCEString dagCode (int index) const
void setDagCode (int index, const TCEString &code)
TCEString dagError (int index) const
bool usesMemory () const
bool readsMemory () const
bool writesMemory () const
bool canTrap () const
bool hasSideEffects () const
bool isClocked () const
bool isControlFlowOperation () const
bool isCall () const
bool isBranch () const
bool dependsOn (const Operation &op) const
void setReadsMemory (bool setting)
void setWritesMemory (bool setting)
int affectsCount () const
int affectedByCount () const
TCEString affects (unsigned int i) const
TCEString affectedBy (unsigned int i) const
bool canSwap (int id1, int id2) const
Operand & input (int index) const
void addInput (Operand *operand)
Operand & output (int index) const
void addOutput (Operand *operand)
void setBehavior (OperationBehavior &behavior)
OperationBehavior & behavior () const
void loadState (const ObjectState *state)
ObjectState * saveState () const
bool simulateTrigger (SimValue **, OperationContext &context) const
void createState (OperationContext &context) const
void deleteState (OperationContext &context) const
bool canBeSimulated () const
bool isNull () const
TCEString emulationFunctionName () const
void clear ()
Operand & fetchOperand (int id, const std::vector< Operand * > &ops) const
Operand & fetchOperand (int id) const
void insertOperand (Operand *operand, std::vector< Operand * > &ops)
Private Attributes
OperationBehavior * behavior_
The behavior of the Operation.
std::string name_
Name of the Operation.
std::string description_
Description of the Operation.
DAGContainer dags_
Table of DAGs and their source codes of an operation.
int inputs_
The number of inputs of the Operation.
int outputs_
The number of outputs of the Operation.
bool readsMemory_
Flag indicating if Operation reads from memory.
bool writesMemory_
Flag indicating if Operation writes to memory.
bool canTrap_
Flag indicating if Operation can trap.
bool hasSideEffects_
Flag indicating if Operation has side effects.
bool isClocked_
Flag indicating if Operation is clocked and needs AdvanceClock.
bool controlFlowOperation_
Flag indicating if the Operation can change program flow.
std::set< std::string > affects_
Operations that affects this Operation.
std::set< std::string > affectedBy_
Operations that are affected by this Operation.
std::vector< Operand * > inputOperands_
Input Operands of the Operation.
std::vector< Operand * > outputOperands_
Output Operands of the Operation.
bool isCall_
Flag indicating if Operation is call.
bool isBranch_
Flag indicating if Operation is branch changing control flow.
Friends
class Operation
Detailed Description
A private implementation class for Operation
Definition at line 54 of file OperationPimpl.hh.
Member Typedef Documentation
DAGContainer
typedef std::vector<OperationDAGInfo> OperationPimpl::DAGContainer private
Definition at line 146 of file OperationPimpl.hh.
Constructor & Destructor Documentation
~OperationPimpl()
OperationPimpl::~OperationPimpl ()
Destructor.
Operands are destroyed.
Definition at line 80 of file OperationPimpl.cc.
{
    clear();
}
References clear().
OperationPimpl() [1/3]
OperationPimpl::OperationPimpl (const TCEString & name, OperationBehavior & behavior) private
Constructor.
Parameters
name The name of the Operation.
behavior The behavior of the Operation.
Definition at line 65 of file OperationPimpl.cc.
                                 :
    behavior_(&behavior), name_(StringTools::stringToUpper(name)),
    description_(""),
    inputs_(0), outputs_(0), readsMemory_(false), writesMemory_(false),
    canTrap_(false), hasSideEffects_(false), isClocked_(false),
    controlFlowOperation_(false), isCall_(false), isBranch_(false) {
}
OperationPimpl() [2/3]
OperationPimpl::OperationPimpl () private
OperationPimpl() [3/3]
OperationPimpl::OperationPimpl (const OperationPimpl &) private
Copying not allowed.
Member Function Documentation
addDag()
void OperationPimpl::addDag (const TCEString & code) private
Creates new DAG and adds it's code for operation.
Parameters
code Source code written in DAG language.
Definition at line 140 of file OperationPimpl.cc.
{
    OperationDAGInfo newDag;
    newDag.code = code;
    newDag.dag = &OperationDAG::null;
    newDag.compilationFailed = false;
    dags_.push_back(newDag);
}
References OperationPimpl::OperationDAGInfo::code, OperationPimpl::OperationDAGInfo::compilationFailed, OperationPimpl::OperationDAGInfo::dag, dags_, and OperationDAG::null.
Referenced by Operation::addDag(), and loadState().
addInput()
void OperationPimpl::addInput (Operand * operand) private
Definition at line 620 of file OperationPimpl.cc.
{
    inputOperands_.push_back(operand);
    inputs_ = inputOperands_.size();
}
References inputOperands_, inputs_, and operand().
Referenced by Operation::addInput().
addOutput()
void OperationPimpl::addOutput (Operand * operand) private
Definition at line 626 of file OperationPimpl.cc.
{
    outputOperands_.push_back(operand);
    outputs_ = outputOperands_.size();
}
References operand(), outputOperands_, and outputs_.
Referenced by Operation::addOutput().
affectedBy()
TCEString OperationPimpl::affectedBy (unsigned int i) const private
Returns the name of the operation that is affected by this operation.
Parameters
i The index of the operation.
Exceptions
OutOfRange If index is illegal.
Returns
The name of the operation.
Definition at line 389 of file OperationPimpl.cc.
{
    if (i >= affectedBy_.size()) {
        string method = "OperationPimpl::affectedBy()";
        string msg = "Index out of range.";
        throw OutOfRange(__FILE__, __LINE__, method, msg);
    }
    set<string>::const_iterator it = affectedBy_.begin();
    unsigned int count = 0;
    while (count < i) {
        it++;
        count++;
    }
    return *it;
}
References affectedBy_.
Referenced by Operation::affectedBy(), loadState(), and saveState().
affectedByCount()
int OperationPimpl::affectedByCount () const private
Returns the number of operations affected by this operation.
Returns
The number of operations affected by this operation.
Definition at line 353 of file OperationPimpl.cc.
{
    return affectedBy_.size();
}
References affectedBy_.
Referenced by Operation::affectedByCount().
affects()
TCEString OperationPimpl::affects (unsigned int i) const private
Returns the name of the operation this operation affects.
Parameters
i The index of the operation.
Returns
The name of the operation.
Definition at line 364 of file OperationPimpl.cc.
{
    if (i >= affects_.size()) {
        string method = "OperationPimpl::affects()";
        string msg = "Index out of range.";
        throw OutOfRange(__FILE__, __LINE__, method, msg);
    }
    set<string>::const_iterator it = affects_.begin();
    unsigned int count = 0;
    while (count < i) {
        it++;
        count++;
    }
    return *it;
}
References affects_.
Referenced by Operation::affects(), loadState(), and saveState().
affectsCount()
int OperationPimpl::affectsCount () const private
Returns the number of operations that affect this operation.
Returns
The number of operations that affect this operation.
Definition at line 343 of file OperationPimpl.cc.
{
    return affects_.size();
}
References affects_.
Referenced by Operation::affectsCount().
behavior()
OperationBehavior & OperationPimpl::behavior () const private
Returns the behavior of Operation.
Returns
The behavior of Operation.
Definition at line 333 of file OperationPimpl.cc.
{
    return *behavior_;
}
References behavior_.
Referenced by Operation::areValid(), Operation::behavior(), and setBehavior().
canBeSimulated()
bool OperationPimpl::canBeSimulated () const private
Returns true if this operation has behavior, or dag which is simulateable (doesn't contain infinite recursion loop).
Returns
True if this operation has behavior, or dag which is
Definition at line 786 of file OperationPimpl.cc.
{
    return behavior_->canBeSimulated();
}
References behavior_, and OperationBehavior::canBeSimulated().
Referenced by Operation::canBeSimulated().
canSwap()
bool OperationPimpl::canSwap (int id1, int id2) const private
Returns true if Operands can be swapped.
Parameters
id1 Id of the first Operand.
id2 Id of the second Operand.
Returns
True, if Operands can be swapped, false otherwise.
Definition at line 435 of file OperationPimpl.cc.
{
    Operand& op1 = fetchOperand(id1);
    Operand& op2 = fetchOperand(id2);
    if (&op1 == &NullOperand::instance() ||
        &op2 == &NullOperand::instance()) {
        return false;
    }
    return op1.canSwap(op2);
}
References Operand::canSwap(), fetchOperand(), and NullOperand::instance().
Referenced by Operation::canSwap().
canTrap()
bool OperationPimpl::canTrap () const private
Returns true if Operation can trap.
Returns
True if Operation can trap, false otherwise.
Definition at line 258 of file OperationPimpl.cc.
{
    return canTrap_;
}
References canTrap_.
Referenced by Operation::canTrap().
clear()
void OperationPimpl::clear () private
Clears the operation.
Definition at line 88 of file OperationPimpl.cc.
                      {
    for (int i = 0; i < dagCount(); i++) {
        if (!dags_[i].dag->isNull()) {
            delete dags_[i].dag;
        }
    }
    dags_.clear();
    SequenceTools::deleteAllItems(inputOperands_);
    SequenceTools::deleteAllItems(outputOperands_);
    inputOperands_.clear();
    outputOperands_.clear();
    affects_.clear();
    affectedBy_.clear();
    name_ = "";
    inputs_ = 0;
    outputs_ = 0;
    readsMemory_ = false;
    writesMemory_ = false;
    canTrap_ = false;
    hasSideEffects_ = false;
    controlFlowOperation_ = false;
    isBranch_ = false;
    isCall_ = false;
}
References affectedBy_, affects_, canTrap_, controlFlowOperation_, dag(), dagCount(), dags_, SequenceTools::deleteAllItems(), hasSideEffects_, inputOperands_, inputs_, isBranch_, isCall_, OperationDAG::isNull(), name_, outputOperands_, outputs_, readsMemory_, and writesMemory_.
Referenced by loadState(), and ~OperationPimpl().
createState()
void OperationPimpl::createState (OperationContext & context) const private
Creates an instance of operation state for this operation and adds it to the operation context.
Parameters
context The operation context to add the state in.
Definition at line 764 of file OperationPimpl.cc.
{
    behavior_->createState(context);
}
References behavior_, and OperationBehavior::createState().
Referenced by Operation::createState().
dag()
OperationDAG & OperationPimpl::dag (int index) const private
Returns an operation DAG for operation.
Compiles DAG from code to object if necessary.
Parameters
index Index of returned DAG.
Returns
Requested operation DAG or OperationDAG::null if DAG is not valid.
Definition at line 186 of file OperationPimpl.cc.
{
    // if dag is not up to date, try to compile it, if compilation failed and
    // dag code has not been changed don't try to compile again
    if (dags_[index].dag->isNull() && !dags_[index].compilationFailed) {
        try {
            dags_[index].dag =
                OperationDAGConverter::createDAG(*this, dags_[index].code);
            dags_[index].compilationFailed = false;
            dags_[index].error = "";
        } catch (const IllegalParameters &e) {
            dags_[index].dag = &OperationDAG::null;
            dags_[index].error = e.errorMessage();
            dags_[index].compilationFailed = true;
        } catch (const Exception &e) {
            dags_[index].dag = &OperationDAG::null;
            dags_[index].error = "UNEXPECTED ERROR: " + e.errorMessage();
            dags_[index].compilationFailed = true;
        }
    }
    return *dags_[index].dag;
}
References OperationDAGConverter::createDAG(), dag(), dags_, Exception::errorMessage(), OperationDAG::isNull(), and OperationDAG::null.
Referenced by clear(), Operation::dag(), dag(), and setDagCode().
dagCode()
TCEString OperationPimpl::dagCode (int index) const private
Returns source code of DAG.
Parameters
index Index of DAG whose source code is requested.
Returns
The source code set for DAG.
Definition at line 220 of file OperationPimpl.cc.
{
    return dags_[index].code;
}
References dags_.
Referenced by Operation::dagCode(), and saveState().
dagCount()
int OperationPimpl::dagCount () const private
Returns number of DAGs stored for operation.
Returns
Number of DAGs stored for operation.
Definition at line 172 of file OperationPimpl.cc.
{
    return dags_.size();
}
References dags_.
Referenced by clear(), Operation::dagCount(), and saveState().
dagError()
TCEString OperationPimpl::dagError (int index) const private
Error message if DAG source code could not be compiled.
Parameters
index Index of DAG whose error is returned.
Returns
Error message, empty string if DAG was compiles successfully.
Definition at line 248 of file OperationPimpl.cc.
{
    return dags_[index].error;
}
References dags_.
Referenced by Operation::dagError().
deleteState()
void OperationPimpl::deleteState (OperationContext & context) const private
Deletes an instance of operation state for this operation from the operation context.
Parameters
context The operation context to delete the state from.
Definition at line 775 of file OperationPimpl.cc.
{
    behavior_->deleteState(context);
}
References behavior_, and OperationBehavior::deleteState().
Referenced by Operation::deleteState().
dependsOn()
bool OperationPimpl::dependsOn (const Operation & op) const private
Returns true if Operation depends on the given operation.
Parameters
op The Operation being investigated.
Returns
True if Operation depends on the given operation, false otherwise.
Definition at line 413 of file OperationPimpl.cc.
{
    set<string>::const_iterator it = affects_.find(op.name());
    if (it != affects_.end()) {
        return true;
    } else {
        it = affectedBy_.find(op.name());
        if (it != affectedBy_.end()) {
            return true;
        }
    }
    return false;
}
References affectedBy_, affects_, and Operation::name().
Referenced by Operation::dependsOn().
description()
TCEString OperationPimpl::description () const private
Returns the description of the Operation.
Returns
The description of the Operation.
Definition at line 131 of file OperationPimpl.cc.
{
    return description_;
}
References description_.
Referenced by Operation::description().
emulationFunctionName()
TCEString OperationPimpl::emulationFunctionName () const private
Name of emulation function which is called if the operation is emulated in program.
Returns
Name of emulation function of the instruction.
Definition at line 819 of file OperationPimpl.cc.
{
    std::string functionName;
    functionName = "__emulate_" + std::string(name()) +
        "_" + Conversion::toString(numberOfInputs()) +
        "_" + Conversion::toString(numberOfOutputs());
    for (int i = 1; i <= numberOfInputs(); i++) {
        Operand& oper = operand(i);
        functionName += "_" + llvmOperandType(oper.type());
    }
    for (int i = 1; i <= numberOfOutputs(); i++) {
        Operand& oper = operand(numberOfInputs() + i);
        functionName += "_" + llvmOperandType(oper.type());
    }
    return functionName;
}
References llvmOperandType(), name(), numberOfInputs(), numberOfOutputs(), operand(), Conversion::toString(), and Operand::type().
Referenced by Operation::emulationFunctionName().
fetchOperand() [1/2]
Operand & OperationPimpl::fetchOperand (int id) const private
Returns an operand with a certain id if it exists.
If operand is not found, NullOperand is returned.
Parameters
id Id of the operand.
Returns
Operand with a certain id.
Definition at line 696 of file OperationPimpl.cc.
{
    assert(id != 0);
    for (unsigned int i = 0; i < inputOperands_.size(); i++) {
        if (inputOperands_[i]->index() == id) {
            return *inputOperands_[i];
        }
    }
    for (unsigned int i = 0; i < outputOperands_.size(); i++) {
        if (outputOperands_[i]->index() == id) {
            return *outputOperands_[i];
        }
    }
    return NullOperand::instance();
}
References assert, inputOperands_, NullOperand::instance(), and outputOperands_.
fetchOperand() [2/2]
Operand & OperationPimpl::fetchOperand (int id, const std::vector< Operand * > & ops) const private
Returns an operand with a certain id if it exists.
If operand is not found, a null operand is returned.
Parameters
id The id of an operand.
ops Vector where operand is searched.
Returns
Operand with a certain id.
Definition at line 674 of file OperationPimpl.cc.
{
    assert(id != 0);
    for (std::vector<Operand*>::const_iterator i = ops.begin(); i != ops.end();
        ++i) {
        if ((*i)->index() == id) {
            return **i;
        }
    }
    return NullOperand::instance();
}
References assert, and NullOperand::instance().
Referenced by canSwap(), and operand().
hasSideEffects()
bool OperationPimpl::hasSideEffects () const private
Return true if operation has side effects.
Returns
True if Operation has side effects, false otherwise.
Definition at line 268 of file OperationPimpl.cc.
{
    return hasSideEffects_;
}
References hasSideEffects_.
Referenced by Operation::hasSideEffects().
input()
Operand & OperationPimpl::input (int index) const inline private
Referenced by Operation::input().
insertOperand()
void OperationPimpl::insertOperand (Operand * operand, std::vector< Operand * > & ops) private
Inserts operand to the right place.
Operands are inserted according to their indexes.
Parameters
operand Operand to be inserted.
ops Vector in which operand is inserted.
Definition at line 723 of file OperationPimpl.cc.
{
    vector<Operand*>::iterator it = ops.begin();
    bool inserted = false;
    while (it != ops.end()) {
        if ((*it)->index() > operand->index()) {
            inserted = true;
            ops.insert(it, operand);
            break;
        }
        it++;
    }
    if (!inserted) {
        ops.push_back(operand);
    }
}
References Operand::index(), and operand().
Referenced by loadState().
isBranch()
bool OperationPimpl::isBranch () const private
Return true if the operation is branch.
Branches of different type have this property set.
Returns
True if Operation is a branch operation.
Definition at line 313 of file OperationPimpl.cc.
{
    return isBranch_;
}
References isBranch_.
Referenced by Operation::isBranch().
isCall()
bool OperationPimpl::isCall () const private
Return true if the operation is call.
Calls of different type have this property set.
Returns
True if Operation is a call operation.
Definition at line 302 of file OperationPimpl.cc.
{
    return isCall_;
}
References isCall_.
Referenced by Operation::isCall().
isClocked()
bool OperationPimpl::isClocked () const private
Returns true if the operation is clocked.
Returns
True if the operation is clocked.
Definition at line 278 of file OperationPimpl.cc.
{
    return isClocked_;
}
References isClocked_.
Referenced by Operation::isClocked().
isControlFlowOperation()
bool OperationPimpl::isControlFlowOperation () const private
Return true if the operation can change control flow.
Branches and calls of different type have this property set.
Returns
True if Operation is a control flow operation.
Definition at line 290 of file OperationPimpl.cc.
{
    return controlFlowOperation_;
}
References controlFlowOperation_.
Referenced by Operation::isControlFlowOperation().
isNull()
bool OperationPimpl::isNull () const private
loadState()
void OperationPimpl::loadState (const ObjectState * state) private
Loads the Operation from ObjectState object.
Parameters
state The state of the Operation.
Definition at line 453 of file OperationPimpl.cc.
{
    clear();
    string method = "OperationPimpl::loadState()";
    try {
        name_ = StringTools::stringToUpper(state->stringAttribute(
            Operation::OPRN_NAME));
        description_ = state->stringAttribute(Operation::OPRN_DESCRIPTION);
        inputs_ = state->intAttribute(Operation::OPRN_INPUTS);
        outputs_ = state->intAttribute(Operation::OPRN_OUTPUTS);
        canTrap_ = state->boolAttribute(Operation::OPRN_TRAP);
        hasSideEffects_ = state->boolAttribute(Operation::OPRN_SIDE_EFFECTS);
        isClocked_ = state->boolAttribute(Operation::OPRN_CLOCKED);
        controlFlowOperation_ = state->boolAttribute(Operation::OPRN_CONTROL_FLOW);
        isCall_ = state->boolAttribute(Operation::OPRN_ISCALL);
        isBranch_ = state->boolAttribute(Operation::OPRN_ISBRANCH);
        readsMemory_ = state->boolAttribute(Operation::OPRN_READS_MEMORY);
        writesMemory_ = state->boolAttribute(Operation::OPRN_WRITES_MEMORY);
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == Operation::OPRN_IN) {
                Operand* operand = new Operand(true);
                operand->loadState(child);
                if (operand->index() < 1 || operand->index() > inputs_) {
                    string msg = "Input operand index illegal";
                    throw Exception(__FILE__, __LINE__, method, msg);
                }
                insertOperand(operand, inputOperands_);
            } else if (child->name() == Operation::OPRN_OUT) {
                Operand* operand = new Operand(false);
                operand->loadState(child);
                if (operand->index() <= inputs_ ||
                    operand->index() > inputs_ + outputs_) {
                    string msg = "Output operand index illegal";
                    throw Exception(__FILE__, __LINE__, method, msg);
                }
                insertOperand(operand, outputOperands_);
            } else if (child->name() == Operation::OPRN_AFFECTS) {
                for (int j = 0; j < child->childCount(); j++) {
                    ObjectState* affects = child->child(j);
                    affects_.insert(
                        StringTools::stringToUpper(
                            affects->stringAttribute(Operation::OPRN_NAME)));
                }
            } else if (child->name() == Operation::OPRN_AFFECTED_BY) {
                for (int j = 0; j < child->childCount(); j++) {
                    ObjectState* affectedBy = child->child(j);
                    affectedBy_.insert(
                        StringTools::stringToUpper(
                            affectedBy->stringAttribute(Operation::OPRN_NAME)));
                }
            } else if (child->name() == Operation::OPRN_TRIGGER) {
                addDag(child->stringValue());
            } else {
                // no other childs should be possible
                string msg = "Unknown child: " + child->name();
                throw Exception(__FILE__, __LINE__, method, msg);
            }
        }
        // TODO: check can-swap operands and verify that they are created
        //       properly
        // add operands that are not defined in XML nor can-swap..
        for (int i = 1; i <= inputs_; ++i) {
            if (&operand(i) == &NullOperand::instance()) {
                Operand* operand = new Operand(true, i, Operand::SINT_WORD);
                insertOperand(operand, inputOperands_);
            }
        }
        for (int i = 1 + inputs_; i <= inputs_ + outputs_; ++i) {
            if (&operand(i) == &NullOperand::instance()) {
                Operand* operand = new Operand(true, i, Operand::SINT_WORD);
                insertOperand(operand, outputOperands_);
            }
        }
    } catch (const Exception& e) {
        string msg = "Problems loading Operation: " + e.errorMessage();
        ObjectStateLoadingException error(__FILE__, __LINE__, method, msg);
        error.setCause(e);
        throw error;
    }
}
References addDag(), affectedBy(), affectedBy_, affects(), affects_, ObjectState::boolAttribute(), canTrap_, ObjectState::child(), ObjectState::childCount(), clear(), controlFlowOperation_, description_, Exception::errorMessage(), hasSideEffects_, Operand::index(), inputOperands_, inputs_, insertOperand(), NullOperand::instance(), ObjectState::intAttribute(), isBranch_, isCall_, isClocked_, Operand::loadState(), ObjectState::name(), name_, operand(), Operation::OPRN_AFFECTED_BY, Operation::OPRN_AFFECTS, Operation::OPRN_CLOCKED, Operation::OPRN_CONTROL_FLOW, Operation::OPRN_DESCRIPTION, Operation::OPRN_IN, Operation::OPRN_INPUTS, Operation::OPRN_ISBRANCH, Operation::OPRN_ISCALL, Operation::OPRN_NAME, Operation::OPRN_OUT, Operation::OPRN_OUTPUTS, Operation::OPRN_READS_MEMORY, Operation::OPRN_SIDE_EFFECTS, Operation::OPRN_TRAP, Operation::OPRN_TRIGGER, Operation::OPRN_WRITES_MEMORY, outputOperands_, outputs_, readsMemory_, Exception::setCause(), Operand::SINT_WORD, ObjectState::stringAttribute(), StringTools::stringToUpper(), ObjectState::stringValue(), and writesMemory_.
Referenced by Operation::loadState().
name()
TCEString OperationPimpl::name () const
Returns the name of the Operation.
Returns
The name of the Operation.
Definition at line 121 of file OperationPimpl.cc.
{
    return name_;
}
References name_.
Referenced by OperationDAGBuilder::connectOperandToNode(), FUGen::constantName(), FUGen::DAGNodeOperandWidth(), emulationFunctionName(), OperationDAGBuilder::finalize(), Operation::name(), and FUGen::subOpConnection().
numberOfInputs()
int OperationPimpl::numberOfInputs () const inline
Referenced by emulationFunctionName(), OperationDAGBuilder::finalize(), and Operation::numberOfInputs().
numberOfOutputs()
int OperationPimpl::numberOfOutputs () const inline
Referenced by emulationFunctionName(), OperationDAGBuilder::finalize(), and Operation::numberOfOutputs().
operand()
Operand & OperationPimpl::operand (int id) const
Returns the Operand with the given id if found, otherwise null Operand.
Note
This method is used to fetch operands with their 'id', the number which identifies it to the programmer. That is, output ids start from the last input id + 1, etc.
Parameters
id The id of Operand.
Returns
Operand if found, null Operand otherwise.
Definition at line 655 of file OperationPimpl.cc.
{
    assert(id != 0);
    Operand& op = fetchOperand(id, inputOperands_);
    if (&op == &NullOperand::instance()) {
        return fetchOperand(id, outputOperands_);
    }
    return op;
}
References assert, fetchOperand(), inputOperands_, NullOperand::instance(), and outputOperands_.
Referenced by addInput(), addOutput(), emulationFunctionName(), insertOperand(), loadState(), Operation::operand(), saveState(), and OperationDAGConverter::writeNode().
operator=()
OperationPimpl & OperationPimpl::operator= (const OperationPimpl &) private
Assignment not allowed.
output()
Operand & OperationPimpl::output (int index) const private
Returns the output Operand with the given index.
This method can be used to traverse the list of output operands (the max index is numberOfOutput() - 1).
Parameters
index The index of Operand.
Definition at line 640 of file OperationPimpl.cc.
{
    return *outputOperands_.at(index);
}
References outputOperands_.
Referenced by Operation::output().
readsMemory()
bool OperationPimpl::readsMemory () const inline private
Referenced by Operation::readsMemory().
removeDag()
void OperationPimpl::removeDag (int index) private
Removes DAG of given index from operation.
Parameters
index Index of dag to delete.
Definition at line 154 of file OperationPimpl.cc.
{
    DAGContainer::iterator i = dags_.begin() + index;
    if (!i->dag->isNull()) {
        delete i->dag;
        i->dag = &OperationDAG::null;
    }
    dags_.erase(i);
}
References dags_, and OperationDAG::null.
Referenced by Operation::removeDag().
saveState()
ObjectState * OperationPimpl::saveState () const private
Saves the state of the Operation in ObjectState object.
Returns
The state of the Operation.
Definition at line 557 of file OperationPimpl.cc.
{
    ObjectState* root = new ObjectState(Operation::OPRN_OPERATION);
    root->setAttribute(Operation::OPRN_NAME, name_);
    root->setAttribute(Operation::OPRN_DESCRIPTION, description_);
    root->setAttribute(Operation::OPRN_INPUTS, inputs_);
    root->setAttribute(Operation::OPRN_OUTPUTS, outputs_);
    root->setAttribute(Operation::OPRN_TRAP, canTrap_);
    root->setAttribute(Operation::OPRN_SIDE_EFFECTS, hasSideEffects_);
    root->setAttribute(Operation::OPRN_CLOCKED, isClocked_);
    root->setAttribute(Operation::OPRN_CONTROL_FLOW, controlFlowOperation_);
    root->setAttribute(Operation::OPRN_ISCALL, isCall_);
    root->setAttribute(Operation::OPRN_ISBRANCH, isBranch_);
    root->setAttribute(Operation::OPRN_READS_MEMORY, readsMemory_);
    root->setAttribute(Operation::OPRN_WRITES_MEMORY, writesMemory_);
    if (affectedBy_.size() > 0) {
            ObjectState* affectedBy = new ObjectState(Operation::OPRN_AFFECTED_BY);
            set<string>::const_iterator it = affectedBy_.begin();
            while (it != affectedBy_.end()) {
                ObjectState* affectedByChild = new ObjectState(Operation::OPRN_OPERATION);
                affectedByChild->setAttribute(Operation::OPRN_NAME, *it);
                affectedBy->addChild(affectedByChild);
                it++;
            }
        root->addChild(affectedBy);
    }
    if (affects_.size() > 0) {
        ObjectState* affects = new ObjectState(Operation::OPRN_AFFECTS);
        set<string>::const_iterator it = affects_.begin();
        while (it != affects_.end()) {
            ObjectState* affectsChild = new ObjectState(Operation::OPRN_OPERATION);
            affectsChild->setAttribute(Operation::OPRN_NAME, *it);
            affects->addChild(affectsChild);
            it++;
        }
        root->addChild(affects);
    }
    for (unsigned int i = 0; i < inputOperands_.size(); i++) {
        ObjectState* operand = inputOperands_[i]->saveState();
        operand->setName(Operation::OPRN_IN);
        root->addChild(operand);
    }
    for (unsigned int i = 0; i < outputOperands_.size(); i++) {
        ObjectState* operand = outputOperands_[i]->saveState();
        operand->setName(Operation::OPRN_OUT);
        root->addChild(operand);
    }
    for (int i = 0; i < dagCount(); i++) {
        ObjectState* trigger = new ObjectState(Operation::OPRN_TRIGGER);
        trigger->setValue(dagCode(i));
        root->addChild(trigger);
    }
    return root;
}
References ObjectState::addChild(), affectedBy(), affectedBy_, affects(), affects_, canTrap_, controlFlowOperation_, dagCode(), dagCount(), description_, hasSideEffects_, inputOperands_, inputs_, isBranch_, isCall_, isClocked_, name_, operand(), Operation::OPRN_AFFECTED_BY, Operation::OPRN_AFFECTS, Operation::OPRN_CLOCKED, Operation::OPRN_CONTROL_FLOW, Operation::OPRN_DESCRIPTION, Operation::OPRN_IN, Operation::OPRN_INPUTS, Operation::OPRN_ISBRANCH, Operation::OPRN_ISCALL, Operation::OPRN_NAME, Operation::OPRN_OPERATION, Operation::OPRN_OUT, Operation::OPRN_OUTPUTS, Operation::OPRN_READS_MEMORY, Operation::OPRN_SIDE_EFFECTS, Operation::OPRN_TRAP, Operation::OPRN_TRIGGER, Operation::OPRN_WRITES_MEMORY, outputOperands_, outputs_, readsMemory_, Operand::saveState(), ObjectState::setAttribute(), ObjectState::setValue(), and writesMemory_.
Referenced by Operation::saveState().
setBehavior()
void OperationPimpl::setBehavior (OperationBehavior & behavior) private
Sets the behavior for operation.
Parameters
behavior Behavior for an operation.
Definition at line 323 of file OperationPimpl.cc.
{
    behavior_ = &behavior;
}
References behavior(), and behavior_.
Referenced by Operation::setBehavior().
setBranch()
void OperationPimpl::setBranch (bool setting)
Sets property of operation indicating that the operation is branch changing control flow.
Definition at line 861 of file OperationPimpl.cc.
{
    isBranch_ = setting;
}
References isBranch_.
Referenced by Operation::setBranch().
setCall()
void OperationPimpl::setCall (bool setting)
Sets property of operation indicating that the operation is function call.
Definition at line 852 of file OperationPimpl.cc.
{
    isCall_ = setting;
}
References isCall_.
Referenced by Operation::setCall().
setControlFlowOperation()
void OperationPimpl::setControlFlowOperation (bool setting)
Sets property of operation indicating that the operation is changing control flow.
Definition at line 844 of file OperationPimpl.cc.
{
    controlFlowOperation_ = setting;
}
References controlFlowOperation_.
Referenced by Operation::setControlFlowOperation().
setDagCode()
void OperationPimpl::setDagCode (int index, const TCEString & code) private
Set new source code for DAG and automatically tries to compile latest version to object.
Parameters
index Index of DAG whose source code is updated.
code New source code in DAG Osal Language.
Definition at line 232 of file OperationPimpl.cc.
{
    dags_[index].code = code;
    if (!dags_[index].dag->isNull()) {
        delete dags_[index].dag;
        dags_[index].dag = &OperationDAG::null;
    }
    dags_[index].compilationFailed = false;
}
References dag(), dags_, OperationDAG::isNull(), and OperationDAG::null.
Referenced by Operation::setDagCode().
setReadsMemory()
void OperationPimpl::setReadsMemory (bool setting) private
Specifies if operation reads memory.
Definition at line 869 of file OperationPimpl.cc.
{
    readsMemory_ = setting;
}
References readsMemory_.
Referenced by Operation::setReadsMemory().
setWritesMemory()
void OperationPimpl::setWritesMemory (bool setting) private
Specifies if operation writes memory.
Definition at line 877 of file OperationPimpl.cc.
{
    writesMemory_ = setting;
}
References writesMemory_.
Referenced by Operation::setWritesMemory().
simulateTrigger()
bool OperationPimpl::simulateTrigger (SimValue ** io, OperationContext & context) const private
Simulates the process of starting execution of an operation.
Parameters
io The input and output operands.
context The operation context.
Returns
True, if all values could be computed, false otherwise.
Exceptions
Exception Depends on the operation behavior.
Definition at line 750 of file OperationPimpl.cc.
{
    return behavior_->simulateTrigger(io, context);
}
References behavior_, and OperationBehavior::simulateTrigger().
Referenced by Operation::simulateTrigger().
usesMemory()
bool OperationPimpl::usesMemory () const inline private
Referenced by Operation::usesMemory().
writesMemory()
bool OperationPimpl::writesMemory () const inline private
Referenced by Operation::writesMemory().
Friends And Related Symbol Documentation
Operation
friend class Operation friend
Definition at line 56 of file OperationPimpl.hh.
Member Data Documentation
affectedBy_
std::set<std::string> OperationPimpl::affectedBy_ private
Operations that are affected by this Operation.
Definition at line 182 of file OperationPimpl.hh.
Referenced by affectedBy(), affectedByCount(), clear(), dependsOn(), loadState(), and saveState().
affects_
std::set<std::string> OperationPimpl::affects_ private
Operations that affects this Operation.
Definition at line 180 of file OperationPimpl.hh.
Referenced by affects(), affectsCount(), clear(), dependsOn(), loadState(), and saveState().
behavior_
OperationBehavior* OperationPimpl::behavior_ private
The behavior of the Operation.
Definition at line 155 of file OperationPimpl.hh.
Referenced by behavior(), canBeSimulated(), createState(), deleteState(), setBehavior(), and simulateTrigger().
canTrap_
bool OperationPimpl::canTrap_ private
Flag indicating if Operation can trap.
Definition at line 172 of file OperationPimpl.hh.
Referenced by canTrap(), clear(), loadState(), and saveState().
controlFlowOperation_
bool OperationPimpl::controlFlowOperation_ private
Flag indicating if the Operation can change program flow.
Definition at line 178 of file OperationPimpl.hh.
Referenced by clear(), isControlFlowOperation(), loadState(), saveState(), and setControlFlowOperation().
dags_
DAGContainer OperationPimpl::dags_ mutable private
Table of DAGs and their source codes of an operation.
Definition at line 161 of file OperationPimpl.hh.
Referenced by addDag(), clear(), dag(), dagCode(), dagCount(), dagError(), removeDag(), and setDagCode().
description_
std::string OperationPimpl::description_ private
Description of the Operation.
Definition at line 159 of file OperationPimpl.hh.
Referenced by description(), loadState(), and saveState().
hasSideEffects_
bool OperationPimpl::hasSideEffects_ private
Flag indicating if Operation has side effects.
Definition at line 174 of file OperationPimpl.hh.
Referenced by clear(), hasSideEffects(), loadState(), and saveState().
inputOperands_
std::vector<Operand*> OperationPimpl::inputOperands_ private
Input Operands of the Operation.
Definition at line 184 of file OperationPimpl.hh.
Referenced by addInput(), clear(), fetchOperand(), loadState(), operand(), and saveState().
inputs_
int OperationPimpl::inputs_ private
The number of inputs of the Operation.
Definition at line 164 of file OperationPimpl.hh.
Referenced by addInput(), clear(), loadState(), and saveState().
isBranch_
bool OperationPimpl::isBranch_ private
Flag indicating if Operation is branch changing control flow.
Definition at line 190 of file OperationPimpl.hh.
Referenced by clear(), isBranch(), loadState(), saveState(), and setBranch().
isCall_
bool OperationPimpl::isCall_ private
Flag indicating if Operation is call.
Definition at line 188 of file OperationPimpl.hh.
Referenced by clear(), isCall(), loadState(), saveState(), and setCall().
isClocked_
bool OperationPimpl::isClocked_ private
Flag indicating if Operation is clocked and needs AdvanceClock.
Definition at line 176 of file OperationPimpl.hh.
Referenced by isClocked(), loadState(), and saveState().
name_
std::string OperationPimpl::name_ private
Name of the Operation.
Definition at line 157 of file OperationPimpl.hh.
Referenced by clear(), loadState(), name(), and saveState().
outputOperands_
std::vector<Operand*> OperationPimpl::outputOperands_ private
Output Operands of the Operation.
Definition at line 186 of file OperationPimpl.hh.
Referenced by addOutput(), clear(), fetchOperand(), loadState(), operand(), output(), and saveState().
outputs_
int OperationPimpl::outputs_ private
The number of outputs of the Operation.
Definition at line 166 of file OperationPimpl.hh.
Referenced by addOutput(), clear(), loadState(), and saveState().
readsMemory_
bool OperationPimpl::readsMemory_ private
Flag indicating if Operation reads from memory.
Definition at line 168 of file OperationPimpl.hh.
Referenced by clear(), loadState(), saveState(), and setReadsMemory().
writesMemory_
bool OperationPimpl::writesMemory_ private
Flag indicating if Operation writes to memory.
Definition at line 170 of file OperationPimpl.hh.
Referenced by clear(), loadState(), saveState(), and setWritesMemory().
The documentation for this class was generated from the following files:
OperationPimpl.hh
OperationPimpl.cc