OpenASIP: AddASCmd Class Reference
AddASCmd Class Reference
#include <AddASCmd.hh>
Public Member Functions
AddASCmd ()
virtual bool Do ()
virtual int id () const
virtual AddASCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new address spaces to the Machine.
Displays a address space dialog and creates a new address space according to the dialog output.
Definition at line 43 of file AddASCmd.hh.
Constructor & Destructor Documentation
AddASCmd()
AddASCmd::AddASCmd ()
The Constructor.
Definition at line 52 of file AddASCmd.cc.
                   :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_AS) {
}
Referenced by create().
Member Function Documentation
create()
AddASCmd * AddASCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 127 of file AddASCmd.cc.
                       {
    return new AddASCmd();
}
References AddASCmd().
Do()
bool AddASCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file AddASCmd.cc.
             {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    // Generate name for the new AS.
    Machine::AddressSpaceNavigator navigator =
        model->getMachine()->addressSpaceNavigator();
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_AS +
        Conversion::toString(i);
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_AS +
            Conversion::toString(i);
        i++;
    }
    AddressSpace* addressSpace =
    new AddressSpace(newName,
             ModelConstants::DEFAULT_WIDTH,
             ModelConstants::DEFAULT_AS_MIN_ADDRESS,
             ModelConstants::DEFAULT_AS_MAX_ADDRESS,
             *model->getMachine());
    AddressSpaceDialog dialog(parentWindow(), model->getMachine(),
                              addressSpace);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    // as creation was cancelled
    model->popFromStack();
    return false;
    }
    return false;
}
References TTAMachine::Machine::addressSpaceNavigator(), assert, ProDeConstants::COMP_NEW_NAME_PREFIX_AS, ModelConstants::DEFAULT_AS_MAX_ADDRESS, ModelConstants::DEFAULT_AS_MIN_ADDRESS, ModelConstants::DEFAULT_WIDTH, Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), Conversion::toString(), and EditorCommand::view().
id()
int AddASCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 116 of file AddASCmd.cc.
                   {
    return ProDeConstants::COMMAND_ADD_AS;
}
References ProDeConstants::COMMAND_ADD_AS.
isEnabled()
bool AddASCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 151 of file AddASCmd.cc.
                    {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddASCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 138 of file AddASCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_AS;
}
References ProDeConstants::CMD_SNAME_ADD_AS.
The documentation for this class was generated from the following files:
AddASCmd.hh
AddASCmd.cc