OpenASIP: BFRemoveEdge Class Reference
BFRemoveEdge Class Reference
#include <BFRemoveEdge.hh>
Public Member Functions
BFRemoveEdge (BF2Scheduler &sched, MoveNode &nTail, MoveNode &nHead, DataDependenceEdge &e)
bool operator() () override
void undoOnlyMe () override
virtual ~BFRemoveEdge ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
DataDependenceEdge & e_
MoveNode & nTail_
MoveNode & nHead_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 40 of file BFRemoveEdge.hh.
Constructor & Destructor Documentation
BFRemoveEdge()
BFRemoveEdge::BFRemoveEdge (BF2Scheduler & sched, MoveNode & nTail, MoveNode & nHead, DataDependenceEdge & e)
Definition at line 36 of file BFRemoveEdge.cc.
                           :
    BFOptimization(sched), e_(e), nTail_(nTail), nHead_(nHead) {}
~BFRemoveEdge()
BFRemoveEdge::~BFRemoveEdge () virtual
Definition at line 65 of file BFRemoveEdge.cc.
{}
Member Function Documentation
operator()()
bool BFRemoveEdge::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 42 of file BFRemoveEdge.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\t\tRemoving edge: " << e_.toString()
              << " from: "<< nTail_.toString()
              << " to: " << nHead_.toString() << std::endl;
#endif
    ddg().rootGraph()->removeEdge(e_);
    return true;
}
References BFOptimization::ddg(), e_, nHead_, nTail_, BoostGraph< GraphNode, GraphEdge >::removeEdge(), BoostGraph< GraphNode, GraphEdge >::rootGraph(), DataDependenceEdge::toString(), and MoveNode::toString().
undoOnlyMe()
void BFRemoveEdge::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 52 of file BFRemoveEdge.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\t\tRestoring edge: "  << e_.toString()
              << " from: " << nTail_.toString()
              << " to: " << nHead_.toString() << std::endl;
#endif
    ddg().rootGraph()->connectNodes(nTail_, nHead_, e_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\t\tRestored edge." << std::endl;
#endif
}
References BoostGraph< GraphNode, GraphEdge >::connectNodes(), BFOptimization::ddg(), e_, nHead_, nTail_, BoostGraph< GraphNode, GraphEdge >::rootGraph(), DataDependenceEdge::toString(), and MoveNode::toString().
Member Data Documentation
e_
DataDependenceEdge& BFRemoveEdge::e_ private
Definition at line 53 of file BFRemoveEdge.hh.
Referenced by operator()(), and undoOnlyMe().
nHead_
MoveNode& BFRemoveEdge::nHead_ private
Definition at line 55 of file BFRemoveEdge.hh.
Referenced by operator()(), and undoOnlyMe().
nTail_
MoveNode& BFRemoveEdge::nTail_ private
Definition at line 54 of file BFRemoveEdge.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFRemoveEdge.hh
BFRemoveEdge.cc