OpenASIP: BFLateBypasses Class Reference
BFLateBypasses Class Reference
#include <BFLateBypasses.hh>
Public Member Functions
BFLateBypasses (BF2Scheduler &sched, MoveNode &src, int lc)
virtual bool operator() ()
bool removedSource ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & src_
int lc_
bool removedSource_
int bypassDistance_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 44 of file BFLateBypasses.hh.
Constructor & Destructor Documentation
BFLateBypasses()
BFLateBypasses::BFLateBypasses (BF2Scheduler & sched, MoveNode & src, int lc)
Definition at line 53 of file BFLateBypasses.cc.
                                                                         :
    BFOptimization(sched), src_(src), lc_(lc), removedSource_(false),
    bypassDistance_(5) {
    SchedulerCmdLineOptions* opts =
        dynamic_cast<SchedulerCmdLineOptions*>(Application::cmdLineOptions());
    if (opts != NULL) {
        if (opts->bypassDistance() > -1) {
            bypassDistance_ = opts->bypassDistance();
        }
    }
}
References SchedulerCmdLineOptions::bypassDistance(), bypassDistance_, and Application::cmdLineOptions().
Member Function Documentation
operator()()
bool BFLateBypasses::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 66 of file BFLateBypasses.cc.
{
    int variableDstCount = 0;
    bool bypassed = false;
    auto rrDestinations =
        ddg().onlyRegisterRawDestinationsWithEdges(src_, false);
    // the boolean specifies whether this is normal or guard bypass.
    std::map<MoveNode*, bool, MoveNode::Comparator> bypassDestinations;
    int earliestDst = INT_MAX;
    // first just search all potentials.
    for (auto i : rrDestinations) {
        MoveNode* n = i.second;
        int guardParam = i.first->guardUse() ? 1 : 2;
        // TODO: the rootgraph here prevents over-loop-edge bypass.
        // TODO: enable over-loop-edge bypass when it works.
        // Needs update to ddg.mergeAndKeep() to put backedge
        // properties and BFOptimization::assign() to keep original
        // register in prolog. (create copy MN of original for prolog
        // when bypassing?
        if ((static_cast<DataDependenceGraph*>(ddg().rootGraph()))->
            onlyRegisterRawSource(*n, guardParam) == NULL) {
            continue;
        }
        // not guard but normal read
        if (guardParam == 2) {
            MachineConnectivityCheck::PortSet destinationPorts;
            destinationPorts.insert(&n->move().destination().port());
            if (MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(
                    src_, destinationPorts)) {
                if (n->isScheduled() == false
                    && (static_cast<SimpleResourceManager&>(
                            rm()).initiationInterval() != 0)) {
                    // Found node connected by loop edge, ignore it.
                    continue;
                }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\tFound ok bypass dest: " << n->toString()
                          << std::endl;
#endif
                if (!ddg().guardsAllowBypass(src_, *n)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    std::cerr << "\t\tGuards do not allow bypass to: "
                              << n->toString() << std::endl;
#endif
                    continue;
                }
                assert(n->isScheduled());
                int originalCycle = n->cycle();
                int earliestLimit = originalCycle - bypassDistance_;
                if (lc_ < earliestLimit) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    std::cerr << "\t\t\tcycle limites prevent late bypass "
                              << std::endl;
#endif
                    continue;
                }
                earliestDst = std::min(earliestDst, originalCycle);
                bypassDestinations.insert(std::make_pair(n, false));
            }
        } else {
            // TODO: test if guard bypass possible.
            // now handled in the guard bypass class itself.
            assert(n->isScheduled());
            int originalCycle = n->cycle();
            int earliestLimit = originalCycle - bypassDistance_;
            if (lc_ < earliestLimit) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\t\tcycle limites prevent late bypass "
                          << std::endl;
#endif
                continue;
            }
            earliestDst = std::min(earliestDst, originalCycle);
            bypassDestinations.insert(std::make_pair(n, true));
        }
    }
    // Do the critical one first. This may force the source FU.
    for (auto n : bypassDestinations) {
        if (n.first->cycle() == earliestDst) {
            if (!n.second) {
                // if always write results,
                // op cannot have more than one register target.
                if (targetMachine().alwaysWriteResults() &&
                    src_.isSourceOperation() &&
                    n.first->isDestinationVariable() &&
                    variableDstCount>0) {
                    continue;
                }
                BFLateBypass* lbp =
                    new BFLateBypass(sched_, src_, *n.first, lc_);
                if (runPreChild(lbp)) {
                    bypassed = true;
                    if (n.first->isDestinationVariable()) {
                        variableDstCount++;
                    }
                }
                bypassDestinations.erase(n.first);
                break;
            } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\nAttempting guard bypass from: " <<
                    src_.toString() << " to: " << n.first->toString()
                          << std::endl;
#endif
                // guard bypass
                BFLateBypassGuard* lbp =
                    new BFLateBypassGuard(sched_, src_, *n.first, lc_);
                if (runPreChild(lbp)) {
                    bypassed = true;
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    std::cerr << "\tguard bypass ok." << std::endl;
                } else {
                    std::cerr << "\tGuard bypass failed." << std::endl;
#endif
                }
                bypassDestinations.erase(n.first);
                break;
            }
        }
    }
    // then actually do the bypass for the other, non-critical moves
    for (auto n : bypassDestinations) {
        if (!n.second) {
            // if always write results,
            // op cannot have more than one register target.
            if (targetMachine().alwaysWriteResults() &&
                src_.isSourceOperation() &&
                n.first->isDestinationVariable() &&
                variableDstCount>0) {
                continue;
            }
            int originalCycle = n.first->cycle();
            if (originalCycle > earliestDst + bypassDistance_) {
                continue;
            }
            BFLateBypass* lbp = new BFLateBypass(sched_, src_, *n.first, lc_);
            if (runPreChild(lbp)) {
                bypassed = true;
                if (n.first->isDestinationVariable()) {
                    variableDstCount++;
                }
            }
        }
    }
    if (!bypassed) {
        return false;
    }
    // if always write results,
    // op must have exactly one register target.
    if (targetMachine().alwaysWriteResults() &&
        src_.isSourceOperation()) {
        // if none of the bypassed are to reg,
        // may not DRE
        if (variableDstCount == 0) {
            return true;
        }
        assert(variableDstCount == 1);
        // if one of the bypasses are to reg,
        // MUST dre.
        BFDRELate* dre = new BFDRELate(sched_, src_);
        if (runPostChild(dre)) {
            removedSource_ = true;
            return true;
        } else {
            undoAndRemovePreChildren();
            return false;
        }
    }
    BFDRELate* dre = new BFDRELate(sched_, src_);
    if (runPostChild(dre)) {
        removedSource_ = true;
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "DRE ok!" << std::endl;
    } else {
        std::cerr << "Could not DRE away: " << src_.toString() << std::endl;
#endif
    }
    return true;
}
References TTAMachine::Machine::alwaysWriteResults(), assert, bypassDistance_, MachineConnectivityCheck::canSourceWriteToAnyDestinationPort(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), DataDependenceGraph::guardsAllowBypass(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), lc_, MoveNode::move(), DataDependenceGraph::onlyRegisterRawDestinationsWithEdges(), TTAProgram::Terminal::port(), removedSource_, BFOptimization::rm(), Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, src_, BFOptimization::targetMachine(), MoveNode::toString(), and Reversible::undoAndRemovePreChildren().
removedSource()
bool BFLateBypasses::removedSource () inline
Definition at line 49 of file BFLateBypasses.hh.
{ return removedSource_;}
References removedSource_.
Referenced by BFScheduleBU::operator()(), and BFScheduleTD::operator()().
Member Data Documentation
bypassDistance_
int BFLateBypasses::bypassDistance_ private
Definition at line 54 of file BFLateBypasses.hh.
Referenced by BFLateBypasses(), and operator()().
lc_
int BFLateBypasses::lc_ private
Definition at line 52 of file BFLateBypasses.hh.
Referenced by operator()().
removedSource_
bool BFLateBypasses::removedSource_ private
Definition at line 53 of file BFLateBypasses.hh.
Referenced by operator()(), and removedSource().
src_
MoveNode& BFLateBypasses::src_ private
Definition at line 51 of file BFLateBypasses.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFLateBypasses.hh
BFLateBypasses.cc