OpenASIP: TTAMachine::OperationTriggeredFormat Class Reference
TTAMachine::OperationTriggeredFormat Class Reference
#include <OperationTriggeredFormat.hh>
Public Member Functions
OperationTriggeredFormat (const std::string &name, Machine &owner)
OperationTriggeredFormat (const ObjectState *state, Machine &owner)
virtual ~OperationTriggeredFormat ()
void addOperation (const std::string &op)
void removeOperation (const std::string &op)
int operationCount () const
std::string operationAtIndex (int index) const
bool hasOperation (const std::string &opName) const
void addOperand (OperationTriggeredOperand &operand)
std::vector< OperationTriggeredOperand * > operands () const
virtual void setMachine (Machine &machine)
virtual void unsetMachine ()
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual void setName (const std::string &name)
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_FORMAT = "ota-format"
static const std::string OSKEY_OPERATION = "ota-operation"
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Attributes
std::vector< std::string > operations_
std::vector< OperationTriggeredOperand * > operands_
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Definition at line 44 of file OperationTriggeredFormat.hh.
Constructor & Destructor Documentation
OperationTriggeredFormat() [1/2]
TTAMachine::OperationTriggeredFormat::OperationTriggeredFormat (const std::string & name, Machine & owner)
The constructor.
Registers the operation code encoding to the parent binary encoding automatically.
Parameters
parent The parent OperationTriggeredFormat.
Definition at line 56 of file OperationTriggeredFormat.cc.
    : Component(name) {
    setMachine(owner);
}
References setMachine().
OperationTriggeredFormat() [2/2]
TTAMachine::OperationTriggeredFormat::OperationTriggeredFormat (const ObjectState * state, Machine & owner)
The constructor
Loads the state of the operation code encoding from the given ObjectState tree
Parameters
state The ObjectState tree
parent The parent binary encoding map
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 74 of file OperationTriggeredFormat.cc.
    : Component(state) {
    const std::string procName =
        "OperationTriggeredFormat::OperationTriggeredFormat";
    try {
        setMachine(owner);
    } catch (const ComponentAlreadyExists&) {
        MOMTextGenerator textGenerator;
        boost::format errorMsg =
            textGenerator.text(MOMTextGenerator::TXT_IT_EXISTS_BY_NAME);
        errorMsg % name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    }
    try {
        loadState(state);
    } catch (const ObjectStateLoadingException&) {
        unsetMachine();
        throw;
    }
}
References loadState(), TTAMachine::Component::name(), setMachine(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_IT_EXISTS_BY_NAME, and unsetMachine().
~OperationTriggeredFormat()
TTAMachine::OperationTriggeredFormat::~OperationTriggeredFormat () virtual
Destructor.
Definition at line 100 of file OperationTriggeredFormat.cc.
{
    for (unsigned int i = 0; i < operands_.size(); i++) {
        delete operands_.at(i);
    }
    unsetMachine();
}
References operands_, and unsetMachine().
Member Function Documentation
addOperand()
void TTAMachine::OperationTriggeredFormat::addOperand (OperationTriggeredOperand & operand)
Definition at line 151 of file OperationTriggeredFormat.cc.
{
    operands_.push_back(&op);
}
References operands_.
Referenced by TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand(), and TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand().
addOperation()
void TTAMachine::OperationTriggeredFormat::addOperation (const std::string & op)
Definition at line 108 of file OperationTriggeredFormat.cc.
{
    operations_.push_back(op);
}
References operations_.
Referenced by OTAOperationDialog::onOK().
hasOperation()
bool TTAMachine::OperationTriggeredFormat::hasOperation (const std::string & opName) const
Definition at line 136 of file OperationTriggeredFormat.cc.
{
    for (const std::string& op : operations_) {
        if (op == opName) {
            return true;
        }
    }
    return false;
}
References operations_.
Referenced by OTAOperationDialog::addRISCVBaseOperations(), OTAOperationDialog::onOK(), and OTAOperationDialog::TransferDataToWindow().
loadState()
void TTAMachine::OperationTriggeredFormat::loadState (const ObjectState * state) virtual
Loads the name of the component from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the machine already contains same type of component with the same name.
Reimplemented from TTAMachine::Component.
Definition at line 185 of file OperationTriggeredFormat.cc.
{
    operations_.clear();
    operands_.clear();
    const std::string procName = "OperationTriggeredOperand::loadState";
    ObjectState* newState = new ObjectState(*state);
    if (newState->name() != OSNAME_FORMAT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Component::loadState(newState);
    try {
        for (int i = 0; i < newState->childCount(); i++) {
            ObjectState* child = newState->child(i);
            if (child->name() == OperationTriggeredOperand::OSNAME_OPERAND) {
                new OperationTriggeredOperand(child, *this);
            } else if (
                child->name() == OperationTriggeredFormat::OSKEY_OPERATION) {
                operations_.push_back(child->stringValue());
            }
        }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    delete newState;
}
References ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), TTAMachine::Component::loadState(), ObjectState::name(), operands_, operations_, OSKEY_OPERATION, OSNAME_FORMAT, TTAMachine::OperationTriggeredOperand::OSNAME_OPERAND, and ObjectState::stringValue().
Referenced by OperationTriggeredFormat().
operands()
std::vector< OperationTriggeredOperand * > TTAMachine::OperationTriggeredFormat::operands () const
Definition at line 146 of file OperationTriggeredFormat.cc.
{
    return operands_;
}
References operands_.
operationAtIndex()
std::string TTAMachine::OperationTriggeredFormat::operationAtIndex (int index) const
Definition at line 127 of file OperationTriggeredFormat.cc.
{
    if (index > operationCount() - 1) {
        const std::string msg = "Operation index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    return operations_.at(index);
}
References __func__, operationCount(), and operations_.
Referenced by BEMGenerator::addRiscvFormat(), and OTAFormatListDialog::updateOperationList().
operationCount()
int TTAMachine::OperationTriggeredFormat::operationCount () const
Definition at line 122 of file OperationTriggeredFormat.cc.
{
    return operations_.size();
}
References operations_.
Referenced by BEMGenerator::addRiscvFormat(), operationAtIndex(), and OTAFormatListDialog::updateOperationList().
removeOperation()
void TTAMachine::OperationTriggeredFormat::removeOperation (const std::string & op)
Definition at line 113 of file OperationTriggeredFormat.cc.
{
    for (unsigned int i = 0; i < operations_.size(); i++) {
        if (operations_.at(i) == op) {
            operations_.erase(operations_.begin() + i);
        }
    }
}
References operations_.
Referenced by OTAFormatListDialog::onDeleteOperation().
saveState()
ObjectState * TTAMachine::OperationTriggeredFormat::saveState () const virtual
Saves the state of the operation code encoding to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::Component.
Definition at line 221 of file OperationTriggeredFormat.cc.
{
    ObjectState* state = Component::saveState();
    state->setName(OSNAME_FORMAT);
    for (unsigned int i = 0; i < operands_.size(); i++) {
        ObjectState* operandObject = operands_.at(i)->saveState();
        state->addChild(operandObject);
    }
    for (unsigned int i = 0; i < operations_.size(); i++) {
        ObjectState* operationObject = new ObjectState(OSKEY_OPERATION);
        operationObject->setValue(operations_.at(i));
        state->addChild(operationObject);
    }
    return state;
}
References ObjectState::addChild(), operands_, operations_, OSKEY_OPERATION, OSNAME_FORMAT, TTAMachine::Component::saveState(), ObjectState::setName(), and ObjectState::setValue().
setMachine()
void TTAMachine::OperationTriggeredFormat::setMachine (Machine & machine) virtual
Adds the OperationTriggeredFormat to the given machine.
Parameters
machine Machine to which the OperationTriggeredFormat Format is added.
Exceptions
ComponentAlreadyExists If there already is another OperationTriggeredFormat Format by the same name or another empty OperationTriggeredFormat Format in the given machine.
Implements TTAMachine::Component.
Definition at line 165 of file OperationTriggeredFormat.cc.
{
    machine.addOperationTriggeredFormat(*this);
    internalSetMachine(machine);
}
References TTAMachine::Machine::addOperationTriggeredFormat(), TTAMachine::Component::internalSetMachine(), and TTAMachine::Component::machine().
Referenced by OperationTriggeredFormat(), and OperationTriggeredFormat().
unsetMachine()
void TTAMachine::OperationTriggeredFormat::unsetMachine () virtual
Removes the OperationTriggeredFormat Format from its machine.
The OperationTriggeredFormat Format is also deleted because it cannot be alone. It must be registered to a machine.
Implements TTAMachine::Component.
Definition at line 177 of file OperationTriggeredFormat.cc.
{
    Machine* mach = machine();
    assert(mach != NULL);
    internalUnsetMachine();
    mach->deleteOperationTriggeredFormat(*this);
}
References assert, TTAMachine::Machine::deleteOperationTriggeredFormat(), TTAMachine::Component::internalUnsetMachine(), and TTAMachine::Component::machine().
Referenced by OperationTriggeredFormat(), and ~OperationTriggeredFormat().
Member Data Documentation
operands_
std::vector<OperationTriggeredOperand*> TTAMachine::OperationTriggeredFormat::operands_ private
Definition at line 77 of file OperationTriggeredFormat.hh.
Referenced by addOperand(), loadState(), operands(), saveState(), and ~OperationTriggeredFormat().
operations_
std::vector<std::string> TTAMachine::OperationTriggeredFormat::operations_ private
Definition at line 76 of file OperationTriggeredFormat.hh.
Referenced by addOperation(), hasOperation(), loadState(), operationAtIndex(), operationCount(), removeOperation(), and saveState().
OSKEY_OPERATION
const std::string TTAMachine::OperationTriggeredFormat::OSKEY_OPERATION = "ota-operation" static
Definition at line 71 of file OperationTriggeredFormat.hh.
Referenced by loadState(), and saveState().
OSNAME_FORMAT
const std::string TTAMachine::OperationTriggeredFormat::OSNAME_FORMAT = "ota-format" static
Definition at line 70 of file OperationTriggeredFormat.hh.
Referenced by ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), TTAMachine::Machine::loadState(), loadState(), and saveState().
The documentation for this class was generated from the following files:
OperationTriggeredFormat.hh
OperationTriggeredFormat.cc