OpenASIP: OSEdOptionsDialog Class Reference
OSEdOptionsDialog Class Reference
#include <OSEdOptionsDialog.hh>
Public Member Functions
OSEdOptionsDialog (wxWindow *parent)
virtual ~OSEdOptionsDialog ()
Private Types
enum { ID_TEXT = 10000 , ID_EDITOR , ID_BUTTON_SAVE , ID_BUTTON_BROWSE }
Private Member Functions
OSEdOptionsDialog (const OSEdOptionsDialog &)
Copying not allowed.
OSEdOptionsDialog & operator= (const OSEdOptionsDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void setTexts ()
bool TransferDataToWindow ()
void onSave (wxCommandEvent &event)
void onBrowse (wxCommandEvent &event)
Private Attributes
wxString editor_
The name of the editor.
Detailed Description
Dialog for modifying OSEd options.
Definition at line 41 of file OSEdOptionsDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_TEXT
ID_EDITOR
ID_BUTTON_SAVE
ID_BUTTON_BROWSE
Definition at line 61 of file OSEdOptionsDialog.hh.
         {
        ID_TEXT = 10000,
        ID_EDITOR,
        ID_BUTTON_SAVE,
        ID_BUTTON_BROWSE
    };
Constructor & Destructor Documentation
OSEdOptionsDialog() [1/2]
OSEdOptionsDialog::OSEdOptionsDialog (wxWindow * parent)
Constructor.
Parameters
parent The parent window.
Definition at line 67 of file OSEdOptionsDialog.cc.
                                                     :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_OPTIONS),
             wxSize(400, 200)) {
    createContents(this, true, true);
    FindWindow(ID_EDITOR)->
        SetValidator(wxTextValidator(wxFILTER_ASCII, &editor_));
    setTexts();
}
~OSEdOptionsDialog()
OSEdOptionsDialog::~OSEdOptionsDialog () virtual
Destructor.
Definition at line 83 of file OSEdOptionsDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_OPTIONS, point);
}
References DialogPosition::DIALOG_OPTIONS, and DialogPosition::setPosition().
OSEdOptionsDialog() [2/2]
OSEdOptionsDialog::OSEdOptionsDialog (const OSEdOptionsDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * OSEdOptionsDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
Parameters
parent Parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 173 of file OSEdOptionsDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Source code editor:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_EDITOR, wxT(""), wxDefaultPosition, wxSize(150,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_BUTTON_BROWSE, wxT("Browse"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item6 = new wxButton( parent, ID_BUTTON_SAVE, wxT("&Save"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item7 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BUTTON_BROWSE, ID_BUTTON_SAVE, ID_EDITOR, and ID_TEXT.
onBrowse()
void OSEdOptionsDialog::onBrowse (wxCommandEvent & event) private
Handles the event when Browse button is pushed.
Definition at line 153 of file OSEdOptionsDialog.cc.
{
    string path = FileSystem::directoryOfPath(WxConversion::toString(editor_));
    wxFileDialog dialog(this, _T("Choose a file"),
                        WxConversion::toWxString(path));
    if (dialog.ShowModal() == wxID_OK) {
        editor_ = dialog.GetPath();
        wxWindow::TransferDataToWindow();
    }
}
References FileSystem::directoryOfPath(), editor_, WxConversion::toString(), and WxConversion::toWxString().
onSave()
void OSEdOptionsDialog::onSave (wxCommandEvent & event) private
Handles the event when Save button is pushed.
Definition at line 132 of file OSEdOptionsDialog.cc.
{
    TransferDataFromWindow();
    wxGetApp().options()->setEditor(WxConversion::toString(editor_));
    OSEdOptionsSerializer serializer;
    string confFile = Environment::userConfPath(OSEdConstants::CONF_FILE_NAME);
    serializer.setDestinationFile(confFile);
    try {
        serializer.writeState(wxGetApp().options()->saveState());
    } catch (const Exception& e) {
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_CAN_NOT_SAVE);
        ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
    }
    EndModal(wxID_OK);
}
References OSEdConstants::CONF_FILE_NAME, editor_, OSEdTextGenerator::instance(), options, OSEdOptionsSerializer::setDestinationFile(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_CAN_NOT_SAVE, Environment::userConfPath(), and OSEdOptionsSerializer::writeState().
operator=()
OSEdOptionsDialog & OSEdOptionsDialog::operator= (const OSEdOptionsDialog &) private
Assignment not allowed.
setTexts()
void OSEdOptionsDialog::setTexts () private
Set texts to all widgets.
Definition at line 94 of file OSEdOptionsDialog.cc.
{
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt = osedText.text(OSEdTextGenerator::TXT_OPTIONS_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT),
                          OSEdTextGenerator::TXT_LABEL_EDITOR);
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_SAVE),
                          OSEdTextGenerator::TXT_BUTTON_SAVE);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_BROWSE),
                          OSEdTextGenerator::TXT_BUTTON_BROWSE);
}
References ID_BUTTON_BROWSE, ID_BUTTON_SAVE, ID_TEXT, GUITextGenerator::instance(), OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUTTON_BROWSE, GUITextGenerator::TXT_BUTTON_CANCEL, OSEdTextGenerator::TXT_BUTTON_SAVE, OSEdTextGenerator::TXT_LABEL_EDITOR, and OSEdTextGenerator::TXT_OPTIONS_DIALOG_TITLE.
TransferDataToWindow()
bool OSEdOptionsDialog::TransferDataToWindow () private
Transfers data to window.
Returns
True if all is successful.
Definition at line 122 of file OSEdOptionsDialog.cc.
{
    OSEdOptions* options = wxGetApp().options();
    editor_ = WxConversion::toWxString(options->editor());
    return wxWindow::TransferDataToWindow();
}
References editor_, options, and WxConversion::toWxString().
Member Data Documentation
editor_
wxString OSEdOptionsDialog::editor_ private
The name of the editor.
Definition at line 69 of file OSEdOptionsDialog.hh.
Referenced by onBrowse(), onSave(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
OSEdOptionsDialog.hh
OSEdOptionsDialog.cc