OpenASIP: CmdHelp Class Reference
CmdHelp Class Reference
#include <CmdHelp.hh>
Public Member Functions
CmdHelp ()
CmdHelp (const CmdHelp &cmd)
virtual ~CmdHelp ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Private Member Functions
CmdHelp & operator= (const CmdHelp &)
Assignment not allowed.
Detailed Description
Help command.
Prints the help text of the CustomCommand that is given as parameter to execute.
Definition at line 50 of file CmdHelp.hh.
Constructor & Destructor Documentation
CmdHelp() [1/2]
CmdHelp::CmdHelp ()
Constructor.
Definition at line 47 of file CmdHelp.cc.
                 : CustomCommand("help") {
}
CmdHelp() [2/2]
CmdHelp::CmdHelp (const CmdHelp & cmd)
~CmdHelp()
CmdHelp::~CmdHelp () virtual
Destructor.
Definition at line 53 of file CmdHelp.cc.
                  {
}
Member Function Documentation
execute()
bool CmdHelp::execute (const std::vector< DataObject > & arguments) virtual
Executes the help command.
Parameters
arguments Arguments for the command.
Returns
True if execution is succesfull, false otherwise
Exceptions
NumberFormatException If conversion of DataObject fails.
Implements CustomCommand.
Definition at line 64 of file CmdHelp.cc.
{
    ScriptInterpreter* interp = interpreter();
    assert(interp != NULL);
    DataObject* obj = new DataObject();
    if (arguments.size() == 1) {
        string result = "Commands available:\n";
        vector<string> names = interp->customCommandsSortedByName();
        for (size_t i = 0; i < names.size(); i++) {
            result += names[i] + " ";
        }
        obj->setString(result);
        interp->setResult(obj);
        return true;
    }
    if (arguments.size() != 2) {
        obj->setString("Wrong number of arguments");
        interp->setResult(obj);
        return false;
    }
    string cmdName = arguments[1].stringValue();
    CustomCommand* command = interp->customCommand(cmdName);
    if (command == NULL) {
        obj->setString("Unknown command: " + cmdName);
        interp->setResult(obj);
        return false;
    } else {
        obj->setString(command->helpText());
        interp->setResult(obj);
        return true;
    }
}
References assert, ScriptInterpreter::customCommand(), ScriptInterpreter::customCommandsSortedByName(), CustomCommand::helpText(), CustomCommand::interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
helpText()
string CmdHelp::helpText () const virtual
Returns help text.
Returns
Help text.
Implements CustomCommand.
Definition at line 105 of file CmdHelp.cc.
{
    return "Use help command to get help";
}
operator=()
CmdHelp & CmdHelp::operator= (const CmdHelp &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
CmdHelp.hh
CmdHelp.cc