OpenASIP: ConstantNode Class Reference
ConstantNode Class Reference
#include <ConstantNode.hh>
Public Member Functions
ConstantNode (long value)
ConstantNode (const ConstantNode &other)
virtual ~ConstantNode ()
virtual GraphNode * clone () const
virtual long value () const
virtual std::string toString () const
Public Member Functions inherited from OperationDAGNode
virtual ~OperationDAGNode ()
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
int nodeID () const
virtual std::string dotString () const
Private Attributes
long value_
Detailed Description
Constant input (not listed in IOs) node of the operation DAG.
Definition at line 43 of file ConstantNode.hh.
Constructor & Destructor Documentation
ConstantNode() [1/2]
ConstantNode::ConstantNode (long value)
Constructor.
Definition at line 39 of file ConstantNode.cc.
                                     :
    OperationDAGNode(), value_(value) {}
ConstantNode() [2/2]
ConstantNode::ConstantNode (const ConstantNode & other)
Cpoy constructor.
Definition at line 45 of file ConstantNode.cc.
                                                    :
    OperationDAGNode(), value_(other.value()) {}
~ConstantNode()
virtual ConstantNode::~ConstantNode () inline virtual
Definition at line 50 of file ConstantNode.hh.
{}
Member Function Documentation
clone()
GraphNode * ConstantNode::clone () const virtual
Clones node. Needed for dynamic binding, when copying instances through the base class.
Returns
Dynamically allocated copy of the node.
Reimplemented from GraphNode.
Definition at line 55 of file ConstantNode.cc.
{
    return new ConstantNode(*this);
}
toString()
std::string ConstantNode::toString () const virtual
Returns a node description as a string.
Used for printing graph into .dot file. This is used for a label in the default dotString() implementation.
Returns
The node ID as a string.
Reimplemented from GraphNode.
Definition at line 65 of file ConstantNode.cc.
{
    return "(" + Conversion::toString(value_) + ")";
}
References Conversion::toString(), and value_.
Referenced by OperationDAGConverter::writeNode().
value()
long ConstantNode::value () const virtual
Definition at line 60 of file ConstantNode.cc.
{
    return value_;
}
References value_.
Referenced by FUGen::constantName(), TDGen::constantNodeString(), and OperationDAGBehavior::OperationDAGBehavior().
Member Data Documentation
value_
long ConstantNode::value_ private
Definition at line 59 of file ConstantNode.hh.
Referenced by toString(), and value().
The documentation for this class was generated from the following files:
ConstantNode.hh
ConstantNode.cc