OpenASIP: RegisterState Class Reference
RegisterState Class Reference
#include <RegisterState.hh>
Public Member Functions
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Protected Attributes
SimValue & value_
Value of the RegisterState.
Private Member Functions
RegisterState (const RegisterState &)
Copying not allowed.
RegisterState & operator= (const RegisterState &)
Assignment not allowed.
Private Attributes
bool shared_
Is the storage of this RegisterState shared with someone else?
bool constantZero_
Is this register constant zero?
Detailed Description
Class that represents the contents of a register.
Definition at line 50 of file RegisterState.hh.
Constructor & Destructor Documentation
RegisterState() [1/3]
RegisterState::RegisterState (int width, bool constantZero = false)
Constructor.
Parameters
width The width of the register.
constantZero Tells whether the register is constant zero
Definition at line 50 of file RegisterState.cc.
                                                         :
    StateData(), value_(*(new SimValue(width))), shared_(false),
    constantZero_(constantZero) {
}
RegisterState() [2/3]
RegisterState::RegisterState (SimValue & sharedRegister)
Constructor for RegisterState which shares the actual register storage.
Parameters
sharedRegister The register which is shared with this.
Definition at line 60 of file RegisterState.cc.
                                                     :
    StateData(), value_(sharedRegister), shared_(true),
    constantZero_(false) {
}
~RegisterState()
RegisterState::~RegisterState () virtual
Destructor.
Definition at line 68 of file RegisterState.cc.
{
    if (!shared_) {
        delete &value_;
    }
}
References shared_, and value_.
RegisterState() [3/3]
RegisterState::RegisterState (const RegisterState &) private
Copying not allowed.
Member Function Documentation
operator=()
RegisterState & RegisterState::operator= (const RegisterState &) private
Assignment not allowed.
setValue()
void RegisterState::setValue (const SimValue & value) virtual
Sets the value for the register.
Parameters
value Value to be set.
Implements WritableState.
Reimplemented in BusState, NullBusState, OpcodeSettingVirtualInputPortState, NullPortState, NullRegisterState, and TriggeringInputPortState.
Definition at line 80 of file RegisterState.cc.
{
    if (!constantZero_) {
        value_ = value;
    }
}
References constantZero_, value(), and value_.
Referenced by SimpleOperationExecutor::advanceClock(), ExecutingOperation::PendingResult::advanceCycle(), RFTestbenchGenerator::createStimulus(), SimProgramBuilder::processMove(), BusState::setValue(), OpcodeSettingVirtualInputPortState::setValue(), TriggeringInputPortState::setValue(), and FUTestbenchGenerator::writeInputPortStimulus().
value()
const SimValue & RegisterState::value () const virtual
Returns the value of the register.
Returns
The value of the register.
Implements ReadableState.
Reimplemented in NullBusState, OpcodeSettingVirtualInputPortState, NullPortState, and NullRegisterState.
Definition at line 92 of file RegisterState.cc.
{
    return value_;
}
References value_.
Referenced by RFTestbenchGenerator::createStimulus(), ProximBusDetailsCmd::Do(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), ProximRFDetailsCmd::Do(), InfoSegmentsCommand::execute(), ExecutableMove::executeWrite(), BusTracker::handleEvent(), ProximRegisterWindow::loadRegisterFile(), FUTestbenchGenerator::readValuesFromOutPorts(), BusState::setValue(), setValue(), TriggeringInputPortState::setValue(), MultiLatencyOperationExecutor::startOperation(), SimpleOperationExecutor::startOperation(), ProximPortWindow::update(), OpcodeSettingVirtualInputPortState::value(), BusState::width(), and FUTestbenchGenerator::writeInputPortStimulus().
Member Data Documentation
constantZero_
bool RegisterState::constantZero_ private
Is this register constant zero?
Definition at line 73 of file RegisterState.hh.
Referenced by setValue().
shared_
bool RegisterState::shared_ private
Is the storage of this RegisterState shared with someone else?
Definition at line 71 of file RegisterState.hh.
Referenced by ~RegisterState().
value_
SimValue& RegisterState::value_ protected
Value of the RegisterState.
Todo:
Fix this mutable mess. It's needed because OutputPortState needs to mask the value_ in its value() implementation.
Definition at line 63 of file RegisterState.hh.
Referenced by setValue(), value(), and ~RegisterState().
The documentation for this class was generated from the following files:
RegisterState.hh
RegisterState.cc