OpenASIP: ProximMachineCanvasTool Class Reference
ProximMachineCanvasTool Class Reference
#include <ProximMachineCanvasTool.hh>
Public Member Functions
ProximMachineCanvasTool (MachineCanvas *canvas)
virtual ~ProximMachineCanvasTool ()
virtual void activate ()
virtual void deactivate ()
virtual void onMouseEvent (wxMouseEvent &event, wxDC &dc)
Public Member Functions inherited from MachineCanvasTool
virtual ~MachineCanvasTool ()
virtual Figure * figure ()
Private Member Functions
void popupMenu (int x, int y)
Private Attributes
MachineCanvas * canvas_
MachineCanvas where the tools is used.
Additional Inherited Members
Protected Member Functions inherited from MachineCanvasTool
MachineCanvasTool (MachineCanvas *canvas)
Protected Attributes inherited from MachineCanvasTool
MachineCanvas * canvas_
Machine canvas where the tool is used.
Detailed Description
MachineCanvasTool for Proxim MachineWindow.
Definition at line 45 of file ProximMachineCanvasTool.hh.
Constructor & Destructor Documentation
ProximMachineCanvasTool()
ProximMachineCanvasTool::ProximMachineCanvasTool (MachineCanvas * canvas)
The Constructor.
Parameters
canvas MachineCanvas where the tool is used.
Definition at line 52 of file ProximMachineCanvasTool.cc.
                                                                      :
    MachineCanvasTool(canvas),
    canvas_(canvas) {
}
~ProximMachineCanvasTool()
ProximMachineCanvasTool::~ProximMachineCanvasTool () virtual
The Destructor.
Definition at line 62 of file ProximMachineCanvasTool.cc.
{
}
Member Function Documentation
activate()
void ProximMachineCanvasTool::activate () virtual
Called when the tool is activated.
Implements MachineCanvasTool.
Definition at line 155 of file ProximMachineCanvasTool.cc.
{
    // do nothing
}
deactivate()
void ProximMachineCanvasTool::deactivate () virtual
Called when the tool is deactivated.
Implements MachineCanvasTool.
Definition at line 164 of file ProximMachineCanvasTool.cc.
{
    // do nothing
}
onMouseEvent()
void ProximMachineCanvasTool::onMouseEvent (wxMouseEvent & event, wxDC & dc) virtual
Handles mouse events on the canvas.
Implements MachineCanvasTool.
Definition at line 70 of file ProximMachineCanvasTool.cc.
{
    // Get event position and translate "raw" coordinates to logical ones.
    wxPoint position = event.GetPosition();
    int x = position.x;
    int y = position.y;
    long logicalX = dc.DeviceToLogicalX(position.x);
    long logicalY = dc.DeviceToLogicalY(position.y);
    // Check if there is an EditPart at the cursor position.
    EditPart* part = canvas_->findEditPart(logicalX, logicalY);
    Request request(Request::STATUS_REQUEST);
    if (part != NULL && part->canHandle(&request)) {
        ComponentCommand* command = part->performRequest(&request);
        command->Do();
        delete command;
    } else {
        ProximToolbox::machineStateWindow()->setStatusText("");
    }
    if (event.LeftDClick()) {
        Request request(Request::MODIFY_REQUEST);
        if (part != NULL && part->canHandle(&request)) {
            ComponentCommand* command = part->performRequest(&request);
            command->setParentWindow(wxGetApp().GetTopWindow());
            command->Do();
            delete command;
        }
    }
    if (event.LeftDown()) {
        canvas_->clearSelection();
        ProximToolbox::machineStateWindow()->clearDetails();
        Request statusRequest(Request::DETAILS_REQUEST);
        if (part != NULL && part->canHandle(&statusRequest)) {
            canvas_->select(part);
            ComponentCommand* command = part->performRequest(&statusRequest);
            command->Do();
            delete command;
        }
    }
    if (event.RightDown()) {
        popupMenu(x, y);
    }
}
References EditPart::canHandle(), canvas_, ProximMachineStateWindow::clearDetails(), MachineCanvas::clearSelection(), Request::DETAILS_REQUEST, ComponentCommand::Do(), MachineCanvas::findEditPart(), ProximToolbox::machineStateWindow(), Request::MODIFY_REQUEST, EditPart::performRequest(), popupMenu(), MachineCanvas::select(), ComponentCommand::setParentWindow(), ProximMachineStateWindow::setStatusText(), and Request::STATUS_REQUEST.
popupMenu()
void ProximMachineCanvasTool::popupMenu (int x, int y) private
Pops a menu at the given position.
Parameters
x X-coordinate of the popup location.
y Y-coordinate of the popup location.
Definition at line 127 of file ProximMachineCanvasTool.cc.
{
    wxMenu* popupMenu = new wxMenu();
    popupMenu->Append(
        ProximMachineStateWindow::COMMAND_ZOOM_IN, _T("Zoom In"));
    popupMenu->Append(
        ProximMachineStateWindow::COMMAND_ZOOM_OUT, _T("Zoom Out"));
    popupMenu->AppendSeparator();
    popupMenu->AppendCheckItem(
        ProximMachineStateWindow::COMMAND_TOGGLE_UNIT_INFO,
        _T("Display Unit Info"));
    popupMenu->AppendSeparator();
    popupMenu->AppendCheckItem(
        ProximMachineStateWindow::COMMAND_TOGGLE_MOVES, _T("Display moves"));
    popupMenu->AppendCheckItem(
        ProximMachineStateWindow::COMMAND_TOGGLE_UTILIZATIONS,
        _T("Display utilizations"));
    popupMenu->AppendSeparator();
    popupMenu->Append(
        ProximMachineStateWindow::COMMAND_EXPORT, _T("Export figure..."));
    canvas_->PopupMenu(popupMenu, wxPoint(x, y));
}
References canvas_, ProximMachineStateWindow::COMMAND_EXPORT, ProximMachineStateWindow::COMMAND_TOGGLE_MOVES, ProximMachineStateWindow::COMMAND_TOGGLE_UNIT_INFO, ProximMachineStateWindow::COMMAND_TOGGLE_UTILIZATIONS, ProximMachineStateWindow::COMMAND_ZOOM_IN, ProximMachineStateWindow::COMMAND_ZOOM_OUT, and popupMenu().
Referenced by onMouseEvent(), and popupMenu().
Member Data Documentation
canvas_
MachineCanvas* ProximMachineCanvasTool::canvas_ private
MachineCanvas where the tools is used.
Definition at line 56 of file ProximMachineCanvasTool.hh.
Referenced by onMouseEvent(), and popupMenu().
The documentation for this class was generated from the following files:
ProximMachineCanvasTool.hh
ProximMachineCanvasTool.cc