OpenASIP: MemoryGridTable Class Reference
MemoryGridTable Class Reference
#include <MemoryGridTable.hh>
Public Types
enum SizeMode { SIZE_MAU , SIZE_TWO_MAUS , SIZE_FOUR_MAUS , SIZE_EIGHT_MAUS }
enum DataMode {
DATA_BIN , DATA_HEX , DATA_SIGNED_INT , DATA_UNSIGNED_INT ,
DATA_DOUBLE , DATA_FLOAT
}
Public Member Functions
MemoryGridTable (Memory &memory)
virtual ~MemoryGridTable ()
virtual int GetNumberRows ()
virtual int GetNumberCols ()
virtual bool IsEmptyCell (int row, int col)
virtual wxString GetValue (int row, int col)
virtual wxString GetRowLabelValue (int row)
virtual wxString GetColLabelValue (int col)
virtual void SetValue (int row, int col, const wxString &value)
void writeValue (int row, int column, UIntWord memoryValue)
void writeValue (int row, int column, DoubleWord memoryValue)
void findAddress (Word addr, int &row, int &col)
void setNumberOfColumns (unsigned columns)
void setSizeMode (SizeMode mode)
void setDataMode (DataMode mode)
unsigned sizeOfCell () const
Private Member Functions
Word cellAddress (int row, int column) const
wxString memoryContents (ULongWord addr)
Private Attributes
Memory & memory_
Memory to access.
Word start_
Start address of the memory range to display.
Word end_
End address of the memory range to display.
DataMode dataMode_
Current data mode of the window (hex/binary/int...).
SizeMode sizeMode_
Current size mode of the window (1/2/4... MAUs per cell).
int mauSize_
Size of MAU in bits.
unsigned numberOfColumns_
Current number of columns in the grid.
Static Private Attributes
static const std::string NOT_AVAILABLE = "N/A"
String that is displayed in a cell that is not in the current AS.
static const int COLUMNS
static const Word MAX_ROWS = 600000000
Maximum number of rows to display in the window.
Detailed Description
Grid table class which allows wxGrid to access TargetMemory contents without copying the memory contents to separate table.
Definition at line 47 of file MemoryGridTable.hh.
Member Enumeration Documentation
DataMode
enum MemoryGridTable::DataMode
Enumerator
DATA_BIN
DATA_HEX
DATA_SIGNED_INT
DATA_UNSIGNED_INT
DATA_DOUBLE
DATA_FLOAT
Definition at line 71 of file MemoryGridTable.hh.
                  {
    DATA_BIN,
    DATA_HEX,
    DATA_SIGNED_INT,
    DATA_UNSIGNED_INT,
    DATA_DOUBLE,
    DATA_FLOAT
    };
SizeMode
enum MemoryGridTable::SizeMode
Enumerator
SIZE_MAU
SIZE_TWO_MAUS
SIZE_FOUR_MAUS
SIZE_EIGHT_MAUS
Definition at line 64 of file MemoryGridTable.hh.
                  {
    SIZE_MAU,
    SIZE_TWO_MAUS,
    SIZE_FOUR_MAUS,
    SIZE_EIGHT_MAUS
    };
Constructor & Destructor Documentation
MemoryGridTable()
MemoryGridTable::MemoryGridTable (Memory & memory)
The Constructor.
Parameters
memory Memory to display in the grid.
Definition at line 49 of file MemoryGridTable.cc.
                                              :
    wxGridTableBase(),
    memory_(memory),
    dataMode_(DATA_HEX),
    sizeMode_(SIZE_MAU),
    numberOfColumns_(8) {
    start_ = memory.start();
    end_ = memory.end();
    mauSize_ = memory.MAUSize();
    // Kludge to avoid overflow with some calculations when the AS size = 2^32.
    // The grid-widget is not capable of displaying enough rows,
    // so the last address wouldn't be displayed anyway.
    if (start_ == 0 && end_ == 0xffffffff) end_ = 0xfffffffe;
}
References Memory::end(), end_, Memory::MAUSize(), mauSize_, Memory::start(), and start_.
~MemoryGridTable()
MemoryGridTable::~MemoryGridTable () virtual
The Destructor.
Definition at line 70 of file MemoryGridTable.cc.
{
}
Member Function Documentation
cellAddress()
Word MemoryGridTable::cellAddress (int row, int column) const private
Calculates the address of given cell.
Parameters
row The selected row.
colummn The selected column.
Returns
Address of the cell.
Definition at line 347 of file MemoryGridTable.cc.
{
    Word address = 0;
    unsigned size = sizeOfCell();
    address += column * size;
    address += row * numberOfColumns_ * size;
    return address;
}
References numberOfColumns_, and sizeOfCell().
Referenced by writeValue(), and writeValue().
findAddress()
void MemoryGridTable::findAddress (Word addr, int & row, int & col)
Returns row and column nubmer of the address in the table.
Parameters
address Memory address to find.
row Variable to set the row to.
col Variable to set the column to.
Definition at line 364 of file MemoryGridTable.cc.
{
    unsigned cellSize = sizeOfCell();
    row = addr / ((unsigned)numberOfColumns_ * cellSize);
    col = (addr % ((unsigned)numberOfColumns_ * cellSize)) / cellSize;
}
References numberOfColumns_, and sizeOfCell().
Referenced by MemoryControl::onGoTo().
GetColLabelValue()
wxString MemoryGridTable::GetColLabelValue (int col) virtual
Returns column label of a grid column.
The label is the offset of the column compared to the first cell in the row.
Parameters
col Column number.
Returns
Label for the grid column.
Definition at line 175 of file MemoryGridTable.cc.
{
    string offset = Conversion::toHexString(col * sizeOfCell());
    return WxConversion::toWxString(offset);
}
References sizeOfCell(), Conversion::toHexString(), and WxConversion::toWxString().
GetNumberCols()
int MemoryGridTable::GetNumberCols () virtual
Returns column count of the grid.
Returns
Number of coulmns in the table.
Definition at line 102 of file MemoryGridTable.cc.
{
    return numberOfColumns_;
}
References numberOfColumns_.
Referenced by MemoryControl::clearHighlights(), and MemoryControl::highlight().
GetNumberRows()
int MemoryGridTable::GetNumberRows () virtual
Returns row count of the grid.
The row count is limited to MAX_ROWS due to limtiations of wxGrid.
Returns
Number of rows in the table.
Definition at line 82 of file MemoryGridTable.cc.
{
    Word size = end_ - start_ + 1;
    Word cells = size / sizeOfCell();
    Word rows = cells / numberOfColumns_;
    if ((cells % numberOfColumns_) != 0) {
        rows++;
    }
    if (rows > MAX_ROWS) {
        rows = MAX_ROWS;
    }
    return rows;
}
References end_, MAX_ROWS, numberOfColumns_, sizeOfCell(), and start_.
GetRowLabelValue()
wxString MemoryGridTable::GetRowLabelValue (int row) virtual
Returns row label of a grid row.
The label is the memory address of the first cell in the row.
Parameters
row Row number.
Returns
Label for the grid row.
Definition at line 156 of file MemoryGridTable.cc.
{
    string address = Conversion::toHexString(
        start_ + row * numberOfColumns_ * sizeOfCell());
    return WxConversion::toWxString(address);
}
References numberOfColumns_, sizeOfCell(), start_, Conversion::toHexString(), and WxConversion::toWxString().
GetValue()
wxString MemoryGridTable::GetValue (int row, int col) virtual
Returns cell value as a wxString.
Returns memory contents corresponding to the cell coordinates. The memory value is formatted to the string depending on the size and type modes set.
Parameters
row Row of the cell.
col Column of the cell.
Returns
Cell contents as a wxString.
Definition at line 132 of file MemoryGridTable.cc.
{
    unsigned addr =
    start_ + (row * numberOfColumns_ * sizeOfCell()) +
    (col * sizeOfCell());
    if ((addr + sizeOfCell()) > (end_ + 1)) {
        return WxConversion::toWxString(NOT_AVAILABLE);
    }
    wxString value = memoryContents(addr);
    return value;
}
References end_, memoryContents(), NOT_AVAILABLE, numberOfColumns_, sizeOfCell(), start_, and WxConversion::toWxString().
IsEmptyCell()
bool MemoryGridTable::IsEmptyCell (int row, int col) virtual
Returns true, if the given cell is empty, false otherwise.
Parameters
row Row of the cell.
col Column of the cell.
Returns
True, if the column is empty.
Definition at line 115 of file MemoryGridTable.cc.
{
    return false;
}
memoryContents()
wxString MemoryGridTable::memoryContents (ULongWord addr) private
Returns contents of the given memory contents as a wxString.
The string formatting depends on the current sizeMode_ and dataMode_ set.
Parameters
addr Memory address to return.
Returns
Memory contents as a wxString.
Definition at line 199 of file MemoryGridTable.cc.
{
    unsigned size = sizeOfCell();
    string dataString = NOT_AVAILABLE;
    unsigned int cellSize = sizeOfCell() * mauSize_;
    if ((size * mauSize_) <= sizeof(SIntWord) * BYTE_BITWIDTH) {
        // read one word
        ULongWord data = 0;
        if (addr < start_ || addr > end_) {
            // memory not available
            return WxConversion::toWxString(NOT_AVAILABLE);
        } else {
            memory_.read(addr, size, data);
        }
        if (dataMode_ == DATA_BIN) {
            dataString =
                Conversion::toBinary(static_cast<int>(data), cellSize);
        } else if (dataMode_ == DATA_HEX) {
            unsigned digits = cellSize / 4;
            if ((cellSize % 4) != 0) {
                cellSize++;
            }
            dataString = Conversion::toHexString(data, digits);
        } else if (dataMode_ == DATA_SIGNED_INT) {
            int extendedValue = data;
            extendedValue =
                extendedValue <<
                ((sizeof(extendedValue)*BYTE_BITWIDTH) - cellSize);
            extendedValue =
                extendedValue >>
                ((sizeof(extendedValue)*BYTE_BITWIDTH) - cellSize);
            dataString = Conversion::toString(extendedValue);
        } else if (dataMode_ == DATA_UNSIGNED_INT) {
            dataString = Conversion::toString(data);
        } else if (dataMode_ == DATA_FLOAT &&
                   cellSize == sizeof(FloatWord) * BYTE_BITWIDTH) {
            FloatWord flt;
            memory_.read(addr, flt);
            dataString = Conversion::toString(flt);
        }
    } else if ((size * mauSize_) <= sizeof(DoubleWord) * BYTE_BITWIDTH) {
        // Only double display is available due to the limitations of
        // stringstream hex/bin conversion.
        if (dataMode_ == DATA_DOUBLE
            && cellSize == sizeof(DoubleWord) * BYTE_BITWIDTH) {
            // read one double word
            DoubleWord data = 0;
            if (addr < start_ || addr > end_) {
                // memory not available
                return WxConversion::toWxString(NOT_AVAILABLE);
            } else {
                memory_.read(addr, data);
            }
            dataString = Conversion::toString(data);
        }
    }
    return WxConversion::toWxString(dataString);
}
References BYTE_BITWIDTH, DATA_BIN, DATA_DOUBLE, DATA_FLOAT, DATA_HEX, DATA_SIGNED_INT, DATA_UNSIGNED_INT, dataMode_, end_, mauSize_, memory_, NOT_AVAILABLE, Memory::read(), sizeOfCell(), Conversion::toBinary(), Conversion::toHexString(), Conversion::toString(), and WxConversion::toWxString().
Referenced by GetValue().
setDataMode()
void MemoryGridTable::setDataMode (DataMode mode)
Sets the data display mode of the table.
Parameters
mode Data display mode to set.
Definition at line 286 of file MemoryGridTable.cc.
{
    dataMode_ = mode;
}
References dataMode_.
Referenced by MemoryControl::onDataModeChanged().
setNumberOfColumns()
void MemoryGridTable::setNumberOfColumns (unsigned columns)
Sets the number of columns to display.
Parameters
columns New table width.
Definition at line 275 of file MemoryGridTable.cc.
{
    numberOfColumns_ = columns;
}
References numberOfColumns_.
Referenced by MemoryControl::onWidthChanged().
setSizeMode()
void MemoryGridTable::setSizeMode (SizeMode mode)
Sets the memory size per cell.
Parameters
mode Size mode to set.
Definition at line 297 of file MemoryGridTable.cc.
{
    sizeMode_ = mode;
}
References sizeMode_.
Referenced by MemoryControl::onSizeModeChanged().
SetValue()
void MemoryGridTable::SetValue (int row, int col, const wxString & value) virtual
Not implemented, use setCellValue() instead.
Definition at line 185 of file MemoryGridTable.cc.
{
    // Do nothing.
}
sizeOfCell()
unsigned MemoryGridTable::sizeOfCell () const
Returns size of memory displayed in a single cell.
Returns
Memory size of a cell.
Definition at line 377 of file MemoryGridTable.cc.
{
    if (sizeMode_ == SIZE_MAU) {
    return 1;
    } else if (sizeMode_ == SIZE_TWO_MAUS) {
    return 2;
    } else if (sizeMode_ == SIZE_FOUR_MAUS) {
    return 4;
    } else if (sizeMode_ == SIZE_EIGHT_MAUS) {
    return 8;
    }
    assert(false);
    return 0;
}
References assert, SIZE_EIGHT_MAUS, SIZE_FOUR_MAUS, SIZE_MAU, SIZE_TWO_MAUS, and sizeMode_.
Referenced by cellAddress(), findAddress(), GetColLabelValue(), GetNumberRows(), GetRowLabelValue(), GetValue(), memoryContents(), MemoryControl::onWriteMemory(), MemoryControl::updateView(), and writeValue().
writeValue() [1/2]
void MemoryGridTable::writeValue (int row, int column, DoubleWord memoryValue)
Sets the memory value correspoding to a cell.
Parameters
row Row of the cell.
column Column of the cell.
memoryValue Value to set.
Definition at line 329 of file MemoryGridTable.cc.
{
    Word address = start_;
    address += cellAddress(row, column);
    if (address < end_) {
        memory_.write(address, memoryValue);
        memory_.advanceClock();
    }
}
References Memory::advanceClock(), cellAddress(), end_, memory_, start_, and Memory::write().
writeValue() [2/2]
void MemoryGridTable::writeValue (int row, int column, UIntWord memoryValue)
Sets the memory value correspoding to a cell.
Parameters
row Row of the cell.
column Column of the cell.
memoryValue Value to set.
Definition at line 310 of file MemoryGridTable.cc.
{
    Word address = start_;
    address += cellAddress(row, column);
    int size = sizeOfCell();
    if (address < end_) {
        memory_.write(address, size, memoryValue);
        memory_.advanceClock();
    }
}
References Memory::advanceClock(), cellAddress(), end_, memory_, sizeOfCell(), start_, and Memory::write().
Referenced by MemoryControl::clearMemory(), and MemoryControl::onWriteMemory().
Member Data Documentation
COLUMNS
const int MemoryGridTable::COLUMNS static private
Definition at line 98 of file MemoryGridTable.hh.
dataMode_
DataMode MemoryGridTable::dataMode_ private
Current data mode of the window (hex/binary/int...).
Definition at line 102 of file MemoryGridTable.hh.
Referenced by memoryContents(), and setDataMode().
end_
Word MemoryGridTable::end_ private
End address of the memory range to display.
Definition at line 94 of file MemoryGridTable.hh.
Referenced by GetNumberRows(), GetValue(), memoryContents(), MemoryGridTable(), writeValue(), and writeValue().
mauSize_
int MemoryGridTable::mauSize_ private
Size of MAU in bits.
Definition at line 106 of file MemoryGridTable.hh.
Referenced by memoryContents(), and MemoryGridTable().
MAX_ROWS
const Word MemoryGridTable::MAX_ROWS = 600000000 static private
Maximum number of rows to display in the window.
Definition at line 100 of file MemoryGridTable.hh.
Referenced by GetNumberRows().
memory_
Memory& MemoryGridTable::memory_ private
Memory to access.
Definition at line 90 of file MemoryGridTable.hh.
Referenced by memoryContents(), writeValue(), and writeValue().
NOT_AVAILABLE
const string MemoryGridTable::NOT_AVAILABLE = "N/A" static private
String that is displayed in a cell that is not in the current AS.
Definition at line 97 of file MemoryGridTable.hh.
Referenced by GetValue(), and memoryContents().
numberOfColumns_
unsigned MemoryGridTable::numberOfColumns_ private
Current number of columns in the grid.
Definition at line 108 of file MemoryGridTable.hh.
Referenced by cellAddress(), findAddress(), GetNumberCols(), GetNumberRows(), GetRowLabelValue(), GetValue(), and setNumberOfColumns().
sizeMode_
SizeMode MemoryGridTable::sizeMode_ private
Current size mode of the window (1/2/4... MAUs per cell).
Definition at line 104 of file MemoryGridTable.hh.
Referenced by setSizeMode(), and sizeOfCell().
start_
Word MemoryGridTable::start_ private
Start address of the memory range to display.
Definition at line 92 of file MemoryGridTable.hh.
Referenced by GetNumberRows(), GetRowLabelValue(), GetValue(), MemoryGridTable(), writeValue(), and writeValue().
The documentation for this class was generated from the following files:
MemoryGridTable.hh
MemoryGridTable.cc