OpenASIP: OperationBehaviorLoader Class Reference
OperationBehaviorLoader Class Reference
#include <OperationBehaviorLoader.hh>
Public Member Functions
OperationBehaviorLoader (OperationIndex &index)
virtual ~OperationBehaviorLoader ()
OperationBehavior & importBehavior (const Operation &parent)
void freeBehavior ()
Private Types
typedef std::map< std::string, OperationBehavior * > BehaviorMap
Contains operation behavior models indexed by operation names.
typedef std::map< OperationBehavior *, void(*)(OperationBehavior *)> DestructionMap
Contains all deletion function of operation behavior models.
Private Member Functions
OperationBehaviorLoader (const OperationBehaviorLoader &)
Copying not allowed.
OperationBehaviorLoader & operator= (const OperationBehaviorLoader &)
Assignment not allowed.
Private Attributes
OperationIndex & index_
Indexed table of all modules and operations accessible for this loader.
PluginTools tools_
PluginTools for loading dynamic modules.
BehaviorMap behaviors_
Container of all loaded operation behavior models.
DestructionMap destructors_
Container of all destruction functions of behavioral models.
Static Private Attributes
static const std::string CREATE_FUNC = "createOpBehavior_"
The name of the creation function in dynamic module.
static const std::string DELETE_FUNC = "deleteOpBehavior_"
The name of the deletion function in dynamic module.
Detailed Description
The purpose of this class is to import operation behavior models from dynamic modules.
PluginTools is used to import the operation behavior modules. OperationIndex is used to obtain modules in which certain operation belongs to.
Definition at line 54 of file OperationBehaviorLoader.hh.
Member Typedef Documentation
BehaviorMap
typedef std::map<std::string, OperationBehavior*> OperationBehaviorLoader::BehaviorMap private
Contains operation behavior models indexed by operation names.
Definition at line 65 of file OperationBehaviorLoader.hh.
DestructionMap
typedef std::map<OperationBehavior*, void (*)(OperationBehavior*)> OperationBehaviorLoader::DestructionMap private
Contains all deletion function of operation behavior models.
Definition at line 68 of file OperationBehaviorLoader.hh.
Constructor & Destructor Documentation
OperationBehaviorLoader() [1/2]
OperationBehaviorLoader::OperationBehaviorLoader (OperationIndex & index) explicit
Constructor.
OperationBehavior uses OperationIndex for getting the right modules.
Parameters
index OperationIndex.
Note
The PluginTools instance should load the behavior modules in the LOCAL mode to enable overriding behavior definitions from later definitions in the search path. E.g., if base.opb defines ADD, a custom.opb can redefine it. If the symbols are made global then the latter symbol is not reloaded but the one from base.opb reused.
Definition at line 61 of file OperationBehaviorLoader.cc.
                                                                      :
    index_(index), tools_(false, true) {
}
~OperationBehaviorLoader()
OperationBehaviorLoader::~OperationBehaviorLoader () virtual
Destructor.
Deletes all the loader operation behavior models.
Definition at line 70 of file OperationBehaviorLoader.cc.
{
    freeBehavior();
}
References freeBehavior().
OperationBehaviorLoader() [2/2]
OperationBehaviorLoader::OperationBehaviorLoader (const OperationBehaviorLoader &) private
Copying not allowed.
Member Function Documentation
freeBehavior()
void OperationBehaviorLoader::freeBehavior ()
Frees all the imported behavior models of the operations.
Definition at line 136 of file OperationBehaviorLoader.cc.
{
    DestructionMap::iterator iter = destructors_.begin();
    while (iter != destructors_.end()) {
        void (*behaviorDestructor)(OperationBehavior*) = (*iter).second;
        behaviorDestructor((*iter).first);
        iter++;
    }
    destructors_.clear();
    behaviors_.clear();
    tools_.unregisterAllModules();
}
References behaviors_, destructors_, tools_, and PluginTools::unregisterAllModules().
Referenced by OperationBehaviorProxy::uninitializeBehavior(), and ~OperationBehaviorLoader().
importBehavior()
OperationBehavior & OperationBehaviorLoader::importBehavior (const Operation & parent)
Imports the behavior model of an operation.
First, the module that contains the given operation is obtained from OperationIndex. A pointer to appropriate create function is obtained and used to create OperationBehavior. Also pointer to appropriate destruction function is obtained and stored.
Parameters
parent The operation that owns the loaded behavior.
Returns
Operation behavior model of the operation.
Exceptions
DynamicLibraryException If an error occurs while accessing the dynamic module.
FileNotFound If the .opb was not found.
SymbolNotFound If the constructor/destructor functions could not be imported from the .opb.
Definition at line 91 of file OperationBehaviorLoader.cc.
{
    string name = parent.name();
    // if behavior was already created, use it
    BehaviorMap::iterator iter = behaviors_.find(name);
    if (iter != behaviors_.end()) {
        return *((*iter).second);
    }
    try {
        OperationModule& module = index_.moduleOf(name);
        if (&module == &NullOperationModule::instance()) {
            string msg = "Module for operation " + name + " not found";
            throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
        }
        string creatorName = CREATE_FUNC + StringTools::stringToUpper(name);
        string destructorName = DELETE_FUNC + StringTools::stringToUpper(name);
        string modName = module.behaviorModule();
        OperationBehavior* (*behaviorCreator)(const Operation&);
        void (*behaviorDestructor)(OperationBehavior*);
        tools_.importSymbol(creatorName, behaviorCreator, modName);
        tools_.importSymbol(destructorName, behaviorDestructor, modName);
        OperationBehavior* behavior = behaviorCreator(parent);
        behaviors_[name] = behavior;
        destructors_[behavior] = behaviorDestructor;
        return *behavior;
    } catch (const FileNotFound& e) {
        throw e;
    } catch (const SymbolNotFound& e) {
        throw e;
    } catch (const Exception& e) {
        string msg =
            std::string("Behavior definition for ") + parent.name() +
            " could not be loaded.";
        DynamicLibraryException error(__FILE__, __LINE__, __func__, msg);
        error.setCause(e);
        throw error;
    }
}
References __func__, behaviors_, CREATE_FUNC, DELETE_FUNC, destructors_, PluginTools::importSymbol(), NullOperationModule::instance(), Operation::name(), Exception::setCause(), StringTools::stringToUpper(), and tools_.
Referenced by OperationBehaviorProxy::initializeBehavior().
operator=()
OperationBehaviorLoader & OperationBehaviorLoader::operator= (const OperationBehaviorLoader &) private
Assignment not allowed.
Member Data Documentation
behaviors_
BehaviorMap OperationBehaviorLoader::behaviors_ private
Container of all loaded operation behavior models.
Definition at line 85 of file OperationBehaviorLoader.hh.
Referenced by freeBehavior(), and importBehavior().
CREATE_FUNC
const string OperationBehaviorLoader::CREATE_FUNC = "createOpBehavior_" static private
The name of the creation function in dynamic module.
Definition at line 76 of file OperationBehaviorLoader.hh.
Referenced by importBehavior().
DELETE_FUNC
const string OperationBehaviorLoader::DELETE_FUNC = "deleteOpBehavior_" static private
The name of the deletion function in dynamic module.
Definition at line 78 of file OperationBehaviorLoader.hh.
Referenced by importBehavior().
destructors_
DestructionMap OperationBehaviorLoader::destructors_ private
Container of all destruction functions of behavioral models.
Definition at line 87 of file OperationBehaviorLoader.hh.
Referenced by freeBehavior(), and importBehavior().
index_
OperationIndex& OperationBehaviorLoader::index_ private
Indexed table of all modules and operations accessible for this loader.
Definition at line 81 of file OperationBehaviorLoader.hh.
tools_
PluginTools OperationBehaviorLoader::tools_ private
PluginTools for loading dynamic modules.
Definition at line 83 of file OperationBehaviorLoader.hh.
Referenced by freeBehavior(), and importBehavior().
The documentation for this class was generated from the following files:
OperationBehaviorLoader.hh
OperationBehaviorLoader.cc