OpenASIP: ProximSocketEditPolicy Class Reference
ProximSocketEditPolicy Class Reference
#include <ProximSocketEditPolicy.hh>
Public Member Functions
ProximSocketEditPolicy ()
virtual ~ProximSocketEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Edit policy for Proxim machine state window sockets.
Definition at line 41 of file ProximSocketEditPolicy.hh.
Constructor & Destructor Documentation
ProximSocketEditPolicy()
ProximSocketEditPolicy::ProximSocketEditPolicy ()
The Constructor.
Definition at line 46 of file ProximSocketEditPolicy.cc.
                                               :
    EditPolicy() {
}
~ProximSocketEditPolicy()
ProximSocketEditPolicy::~ProximSocketEditPolicy () virtual
The Destructor.
Definition at line 54 of file ProximSocketEditPolicy.cc.
{
}
Member Function Documentation
canHandle()
bool ProximSocketEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy can handle request of the given type.
Parameters
Request to be handled.
Returns
True, if the editpolicy can handle give request type.
Implements EditPolicy.
Definition at line 64 of file ProximSocketEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::STATUS_REQUEST ||
        type == Request::DETAILS_REQUEST) {
        return true;
    }
    return false;
}
References Request::DETAILS_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProximSocketEditPolicy::getCommand (Request * request) virtual
Returns command correspoding to the request type.
Parameters
request Request to handle.
Returns
NULL, if the request can't be handled.
Implements EditPolicy.
Definition at line 83 of file ProximSocketEditPolicy.cc.
{
    Request::RequestType type = request->type();
    const Socket* socket = dynamic_cast<Socket*>(host_->model());
    assert(socket != NULL);
    if (type == Request::STATUS_REQUEST) {
        std::string status = ProximConstants::MACH_WIN_SOCKET_LABEL +
            socket->name();
        return new ProximComponentStatusCmd(status);
    } else if (type == Request::DETAILS_REQUEST) {
        return new ProximSocketDetailsCmd(*socket);
    }
    return NULL;
}
References assert, Request::DETAILS_REQUEST, EditPolicy::host_, ProximConstants::MACH_WIN_SOCKET_LABEL, EditPart::model(), TTAMachine::Component::name(), Request::STATUS_REQUEST, and Request::type().
The documentation for this class was generated from the following files:
ProximSocketEditPolicy.hh
ProximSocketEditPolicy.cc