OpenASIP: TPEF::AOutTextSectionReader Class Reference
TPEF::AOutTextSectionReader Class Reference
#include <AOutTextSectionReader.hh>
Public Member Functions
virtual ~AOutTextSectionReader ()
Public Member Functions inherited from TPEF::AOutSectionReader
virtual ~AOutSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Attributes
static const int OFFSET_TO_IMMEDIATE_VALUE = 4
Protected Member Functions
AOutTextSectionReader ()
virtual Section::SectionType type () const
virtual void readData (BinaryStream &stream, Section *section) const
Protected Member Functions inherited from TPEF::AOutSectionReader
AOutSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
void initializeImmediateMove (BinaryStream &stream, MoveElement *move, ImmediateElement *immediate) const
void initializeMove (BinaryStream &stream, MoveElement *move) const
void updateMoveDestination (MoveElement *move, const HalfWord dest) const
void updateMoveSource (MoveElement *move, const Word src) const
Word convertAOutIndexToTPEF (const Word reg) const
void setReference (InstructionElement *elem, SectionOffset sectionOffset, SectionId sectionID) const
AOutTextSectionReader (const AOutTextSectionReader &)
Copying not allowed.
AOutTextSectionReader & operator= (const AOutTextSectionReader &)
Assignment not allowed.
Static Private Attributes
static AOutTextSectionReader proto_
Prototype to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads text sections of a.out format.
Definition at line 49 of file AOutTextSectionReader.hh.
Constructor & Destructor Documentation
~AOutTextSectionReader()
TPEF::AOutTextSectionReader::~AOutTextSectionReader () virtual
Destructor.
Definition at line 71 of file AOutTextSectionReader.cc.
{
}
AOutTextSectionReader() [1/2]
TPEF::AOutTextSectionReader::AOutTextSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 64 of file AOutTextSectionReader.cc.
                                             : AOutSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
AOutTextSectionReader() [2/2]
TPEF::AOutTextSectionReader::AOutTextSectionReader (const AOutTextSectionReader &) private
Copying not allowed.
Member Function Documentation
convertAOutIndexToTPEF()
Word TPEF::AOutTextSectionReader::convertAOutIndexToTPEF (const Word reg) const private
Convert an a.out register index into a TPEF register index.
Service helper method. The callers are responsible for ensuring that the given register index is within the allowed range.
Parameters
reg A.out index of the register.
Returns
The TPEF index of the same register.
Definition at line 209 of file AOutTextSectionReader.cc.
{
    // NOTE: This implementation depends on AOutSymbolSectionReader
    //       implementation  (Where resource section is read).
    // offset to first index of given register class
    int regOffset = 0;
    // int reg
    if (reg < AOutReader::FIRST_FP_REGISTER) {
        regOffset = AOutReader::FIRST_INT_REGISTER;
    // fp reg
    } else if (reg < AOutReader::FIRST_BOOL_REGISTER) {
        regOffset = AOutReader::FIRST_FP_REGISTER;
    // bool register
    } else if (reg < AOutReader::FIRST_FU_REGISTER) {
        regOffset = AOutReader::FIRST_BOOL_REGISTER;
    // fu or special register
    } else {
        regOffset = 0;
    }
    return reg - regOffset;
}
References TPEF::AOutReader::FIRST_BOOL_REGISTER, TPEF::AOutReader::FIRST_FP_REGISTER, TPEF::AOutReader::FIRST_FU_REGISTER, and TPEF::AOutReader::FIRST_INT_REGISTER.
Referenced by updateMoveDestination(), and updateMoveSource().
initializeImmediateMove()
void TPEF::AOutTextSectionReader::initializeImmediateMove (BinaryStream & stream, MoveElement * move, ImmediateElement * immediate) const private
The attributes of move that has immediate in its source field are initialized.
Immediate value of a move is modeled as a separate object.
Parameters
stream Stream to be read from.
move Move to be initialized
immediate Immediate to be initialized.
Exceptions
OutOfRange If destination register index is too large.
UnreachableStream If there occurs problems with stream.
Definition at line 162 of file AOutTextSectionReader.cc.
{
    move->setSourceType(MoveElement::MF_IMM);
    // mark every immediate to be inline encoded
    immediate->setDestinationUnit(ResourceElement::INLINE_IMM);
    immediate->setDestinationIndex(0);
    // mark move source to match immediate
    move->setSourceUnit(ResourceElement::INLINE_IMM);
    move->setSourceIndex(0);
    HalfWord dest = stream.readHalfWord();
    updateMoveDestination(move, dest);
    immediate->setWord(stream.readWord());
}
References TPEF::ResourceElement::INLINE_IMM, TPEF::MoveElement::MF_IMM, TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::ImmediateElement::setDestinationIndex(), TPEF::ImmediateElement::setDestinationUnit(), TPEF::MoveElement::setSourceIndex(), TPEF::MoveElement::setSourceType(), TPEF::MoveElement::setSourceUnit(), TPEF::ImmediateElement::setWord(), and updateMoveDestination().
Referenced by readData().
initializeMove()
void TPEF::AOutTextSectionReader::initializeMove (BinaryStream & stream, MoveElement * move) const private
Initializes an 'ordinary' Move.
Parameters
stream Stream to be read from.
move Move to be initialized.
Exceptions
OutOfRange If destination or source register index is too big.
UnreachableStream If there occurs problems with stream.
Definition at line 190 of file AOutTextSectionReader.cc.
{
    HalfWord dest = stream.readHalfWord();
    updateMoveDestination(move, dest);
    Word src = stream.readWord();
    updateMoveSource(move, src);
}
References TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), updateMoveDestination(), and updateMoveSource().
Referenced by readData().
operator=()
AOutTextSectionReader & TPEF::AOutTextSectionReader::operator= (const AOutTextSectionReader &) private
Assignment not allowed.
readData()
void TPEF::AOutTextSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads all Moves from stream and stores them in to Section.
One move consists of 4 fields: guard (Byte), immediate (Byte), destination index (HalfWord), and source index (Word). If immediate is 1 then the source field of the move contains an immediate value.
Parameters
stream Stream to be read from.
section Pointer to section in which information is stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Implements TPEF::SectionReader.
Definition at line 101 of file AOutTextSectionReader.cc.
{
    AOutReader* aOutReader = dynamic_cast<AOutReader*>(parent());
    FileOffset offset = stream.readPosition();
    Word length = aOutReader->header().sectionSizeText();
    while (stream.readPosition() < offset + length) {
        SectionOffset sectionOffset = stream.readPosition() - offset;
        // we must first discover whether instruction is immediate or not
        Byte guard = stream.readByte();
        Byte imm = stream.readByte();
        MoveElement* move = new MoveElement();
        ImmediateElement* immediate = NULL;
        // guard register is the only boolean register of a.out binaries
        assert((guard == 0) || (guard == '!') || (guard == '?'));
        move->setGuardUnit(ResourceElement::BOOL_RF);
        move->setGuardIndex(0);
        move->setGuardType(MoveElement::MF_RF);
        move->setGuarded(guard != 0);
        move->setGuardInverted(guard == '!');
        // always use universal bus
        move->setBus(ResourceElement::UNIVERSAL_BUS);
        if (imm == 1) {
            immediate = new ImmediateElement();
            initializeImmediateMove(stream, move, immediate);
            immediate->setBegin(true);
            section->addElement(immediate);
            section->addElement(move);
            // set reference pointing immediate, since move is never
            // referenced
            setReference(immediate, sectionOffset, AOutReader::ST_TEXT);
        } else {
            initializeMove(stream, move);
            move->setBegin(true);
            section->addElement(move);
            setReference(move, sectionOffset, AOutReader::ST_TEXT);
        }
    }
}
References TPEF::Section::addElement(), assert, TPEF::ResourceElement::BOOL_RF, TPEF::AOutReader::header(), initializeImmediateMove(), initializeMove(), TPEF::MoveElement::MF_RF, TPEF::AOutSectionReader::parent(), TPEF::BinaryStream::readByte(), TPEF::BinaryStream::readPosition(), TPEF::AOutReader::Header::sectionSizeText(), TPEF::InstructionElement::setBegin(), TPEF::MoveElement::setBus(), TPEF::MoveElement::setGuarded(), TPEF::MoveElement::setGuardIndex(), TPEF::MoveElement::setGuardInverted(), TPEF::MoveElement::setGuardType(), TPEF::MoveElement::setGuardUnit(), setReference(), TPEF::AOutReader::ST_TEXT, and TPEF::ResourceElement::UNIVERSAL_BUS.
setReference()
void TPEF::AOutTextSectionReader::setReference (InstructionElement * elem, SectionOffset sectionOffset, SectionId sectionID) const private
Sets references to ReferenceManager to enable referencing if it's needed later.
Parameters
elem Element to be registered to ReferenceManager.
sectionOffset The offset of the element in the section.
sectionID Identification code of the referenced section.
Exceptions
KeyAlreadyExists If registration fails because of existing key.
Definition at line 319 of file AOutTextSectionReader.cc.
{
    SectionOffsetKey offKey = SectionOffsetKey(sectionID, sectionOffset);
    SafePointer::addObjectReference(offKey, elem);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference().
Referenced by readData().
type()
Section::SectionType TPEF::AOutTextSectionReader::type () const protected virtual
Returns section type which reader can read.
Returns
The type of the section that reader can read.
Implements TPEF::SectionReader.
Definition at line 80 of file AOutTextSectionReader.cc.
{
    return Section::ST_CODE;
}
References TPEF::Section::ST_CODE.
updateMoveDestination()
void TPEF::AOutTextSectionReader::updateMoveDestination (MoveElement * move, const HalfWord dest) const private
Convert an a.out register index to a TPEF register index and update the destination of the given move to reflect the given register index.
Possible values of move destination field are indices of: integer registers, floating point registers, Boolean registers, or function unit registers. The type of the move destination is also set.
Parameters
move The Move to be updated.
dest Index of the destination register.
Exceptions
OutOfRange If destination index is too large.
Definition at line 250 of file AOutTextSectionReader.cc.
{
    if (dest < AOutReader::FIRST_FP_REGISTER) {
        move->setDestinationUnit(ResourceElement::INT_RF);
        move->setDestinationType(MoveElement::MF_RF);
    } else if (dest < AOutReader::FIRST_BOOL_REGISTER) {
        move->setDestinationUnit(ResourceElement::FP_RF);
        move->setDestinationType(MoveElement::MF_RF);
    } else if (dest < AOutReader::FIRST_FU_REGISTER) {
        move->setDestinationUnit(ResourceElement::BOOL_RF);
        move->setDestinationType(MoveElement::MF_RF);
    } else {
        // for special registers move type fields is same that for fu
        move->setDestinationUnit(ResourceElement::UNIVERSAL_FU);
        move->setDestinationType(MoveElement::MF_UNIT);
    }
    move->setDestinationIndex(convertAOutIndexToTPEF(dest));
}
References TPEF::ResourceElement::BOOL_RF, convertAOutIndexToTPEF(), TPEF::AOutReader::FIRST_BOOL_REGISTER, TPEF::AOutReader::FIRST_FP_REGISTER, TPEF::AOutReader::FIRST_FU_REGISTER, TPEF::ResourceElement::FP_RF, TPEF::ResourceElement::INT_RF, TPEF::MoveElement::MF_RF, TPEF::MoveElement::MF_UNIT, TPEF::MoveElement::setDestinationIndex(), TPEF::MoveElement::setDestinationType(), TPEF::MoveElement::setDestinationUnit(), and TPEF::ResourceElement::UNIVERSAL_FU.
Referenced by initializeImmediateMove(), and initializeMove().
updateMoveSource()
void TPEF::AOutTextSectionReader::updateMoveSource (MoveElement * move, const Word src) const private
Convert an a.out register index to a TPEF register index and update the source of the given move to reflect the given register index.
Possible values of move source field are indices of: integer registers, floating point registers, Boolean registers, or function unit registers. The type of the move source is also set.
Parameters
move The Move to be updated.
src Index of the source register.
Exceptions
OutOfRange If source index is too large.
Definition at line 286 of file AOutTextSectionReader.cc.
{
    if (src < AOutReader::FIRST_FP_REGISTER) {
        move->setSourceUnit(ResourceElement::INT_RF);
        move->setSourceType(MoveElement::MF_RF);
    } else if (src < AOutReader::FIRST_BOOL_REGISTER) {
        move->setSourceUnit(ResourceElement::FP_RF);
        move->setSourceType(MoveElement::MF_RF);
    } else if (src < AOutReader::FIRST_FU_REGISTER) {
        move->setSourceUnit(ResourceElement::BOOL_RF);
        move->setSourceType(MoveElement::MF_RF);
    } else {
        // for special registers move type fields is same that for fu
        move->setSourceUnit(ResourceElement::UNIVERSAL_FU);
        move->setSourceType(MoveElement::MF_UNIT);
    }
    move->setSourceIndex(convertAOutIndexToTPEF(src));
}
References TPEF::ResourceElement::BOOL_RF, convertAOutIndexToTPEF(), TPEF::AOutReader::FIRST_BOOL_REGISTER, TPEF::AOutReader::FIRST_FP_REGISTER, TPEF::AOutReader::FIRST_FU_REGISTER, TPEF::ResourceElement::FP_RF, TPEF::ResourceElement::INT_RF, TPEF::MoveElement::MF_RF, TPEF::MoveElement::MF_UNIT, TPEF::MoveElement::setSourceIndex(), TPEF::MoveElement::setSourceType(), TPEF::MoveElement::setSourceUnit(), and TPEF::ResourceElement::UNIVERSAL_FU.
Referenced by initializeMove().
Member Data Documentation
OFFSET_TO_IMMEDIATE_VALUE
const int TPEF::AOutTextSectionReader::OFFSET_TO_IMMEDIATE_VALUE = 4 static
Definition at line 51 of file AOutTextSectionReader.hh.
Referenced by TPEF::AOutRelocationSectionReader::initializeRelocElement().
proto_
AOutTextSectionReader TPEF::AOutTextSectionReader::proto_ static private
Prototype to be registered to SectionReader.
Definition at line 84 of file AOutTextSectionReader.hh.
The documentation for this class was generated from the following files:
AOutTextSectionReader.hh
AOutTextSectionReader.cc