OpenASIP: TCEDAGToDAGISel Class Reference
TCEDAGToDAGISel Class Reference
Public Member Functions
TCEDAGToDAGISel (llvm::TCETargetMachine &tm)
virtual ~TCEDAGToDAGISel ()
bool SelectADDRrr (SDValue N, SDValue &R1, SDValue &R2)
bool SelectADDRri (SDValue N, SDValue &Base, SDValue &Offset)
void Select (llvm::SDNode *op) override
virtual StringRef getPassName () const override
Static Public Attributes
static char ID = 0
Private Member Functions
void SelectOptimizedBuildVector (SDNode *n)
EVT getIntegerVectorVT (EVT vt)
MachineSDNode * createPackNode (SDNode *n, const EVT &vt, int laneCount, SDValue *vals)
Static Private Member Functions
static bool isBroadcast (SDNode *n)
static bool isConstantBuild (SDNode *n)
static bool isConstantFPBuild (SDNode *n)
Private Attributes
llvm::TCETargetLowering & lowering_
const llvm::TCESubtarget & subtarget_
llvm::TCETargetMachine * tm_
Detailed Description
Definition at line 57 of file TCEDAGToDAGISel.cc.
Constructor & Destructor Documentation
TCEDAGToDAGISel()
TCEDAGToDAGISel::TCEDAGToDAGISel (llvm::TCETargetMachine & tm) explicit
Constructor.
Definition at line 101 of file TCEDAGToDAGISel.cc.
                                                    :
    #ifdef LLVM_OLDER_THAN_16
    SelectionDAGISel(tm),
    #else
    SelectionDAGISel(ID, tm),
    #endif
    lowering_(*static_cast<TCETargetLowering*>(tm.getTargetLowering())),
    subtarget_(*tm.getSubtargetImpl()), tm_(&tm) {
}
~TCEDAGToDAGISel()
TCEDAGToDAGISel::~TCEDAGToDAGISel () virtual
Destructor.
Definition at line 114 of file TCEDAGToDAGISel.cc.
{
}
Member Function Documentation
createPackNode()
MachineSDNode * TCEDAGToDAGISel::createPackNode (SDNode * n, const EVT & vt, int laneCount, SDValue * vals) private
getIntegerVectorVT()
EVT TCEDAGToDAGISel::getIntegerVectorVT (EVT vt) private
getPassName()
virtual StringRef TCEDAGToDAGISel::getPassName () const inline override virtual
Definition at line 71 of file TCEDAGToDAGISel.cc.
{
        return "TCE DAG->DAG Pattern Instruction Selection";
    }
isBroadcast()
bool TCEDAGToDAGISel::isBroadcast (SDNode * n) static private
Definition at line 301 of file TCEDAGToDAGISel.cc.
{
    return TCETargetLowering::isBroadcast(n);
}
References llvm::TCETargetLowering::isBroadcast().
isConstantBuild()
bool TCEDAGToDAGISel::isConstantBuild (SDNode * n) static private
Definition at line 306 of file TCEDAGToDAGISel.cc.
{
    int operandCount = n->getNumOperands();
    for (unsigned i = 1; i <operandCount; i++) {
        SDValue val2 = n->getOperand(i);
        SDNode *n2 = val2.getNode();
        if (n2->getOpcode() != ISD::Constant ) {
            return false;
        }
    }
    return true;
}
isConstantFPBuild()
bool TCEDAGToDAGISel::isConstantFPBuild (SDNode * n) static private
Definition at line 319 of file TCEDAGToDAGISel.cc.
{
    int operandCount = n->getNumOperands();
    for (unsigned i = 1; i <operandCount; i++) {
        SDValue val2 = n->getOperand(i);
        SDNode *n2 = val2.getNode();
        if (n2->getOpcode() != ISD::ConstantFP) {
            return false;
        }
    }
    return true;
}
Select()
void TCEDAGToDAGISel::Select (llvm::SDNode * op) override
Handles custom instruction selections.
Parameters
op Operation to select.
Definition at line 132 of file TCEDAGToDAGISel.cc.
{
    // Custom nodes are already selected
    if (n->isMachineOpcode()) {
        n->setNodeId(-1);
        return;
    }
    SDLoc dl(n);
    if (n->getOpcode() >= ISD::BUILTIN_OP_END &&
        n->getOpcode() < TCEISD::FIRST_NUMBER) {
        // Already selected.
        return;
    } else if (n->getOpcode() == ISD::BR) {
        SDValue chain = n->getOperand(0);
        MachineBasicBlock* dest =
            cast<BasicBlockSDNode>(n->getOperand(1))->getBasicBlock();
        SELECT_NODE_AND_RETURN(
        n, TCE::TCEBR, MVT::Other, CurDAG->getBasicBlock(dest), chain);
    } else if (n->getOpcode() == ISD::FrameIndex) {
        int fi = cast<FrameIndexSDNode>(n)->getIndex();
        if (n->hasOneUse()) {
            SELECT_NODE_AND_RETURN(
                n, MOVE_IMM, DEFAULT_TYPE,
                CurDAG->getTargetFrameIndex(fi, DEFAULT_TYPE));
        } else {
            auto fiN = CurDAG->getMachineNode(
                MOVE_IMM, dl, DEFAULT_TYPE,
                CurDAG->getTargetFrameIndex(fi, DEFAULT_TYPE));
            ReplaceNode(n, fiN);
            return;
        }
    } else if (n->getOpcode() == ISD::VSELECT ||
               (n->getOpcode() == ISD::SELECT &&
                !n->getOperand(1).getValueType().isVector())) {
        SDNode* node2 = dyn_cast<SDNode>(n->getOperand(0));
        if (node2->getOpcode() == ISD::SETCC) {
            SDValue val1 = n->getOperand(1);
            SDValue val2 = n->getOperand(2);
            SDValue n2val1 = node2->getOperand(0);
            SDValue n2val2 = node2->getOperand(1);
            if (val1 == n2val1 && val2 == n2val2 && node2->hasOneUse()) {
                int opc;
                ISD::CondCode cc = cast<CondCodeSDNode>(
                    node2->getOperand(2))->get();
                switch (cc) {
                case ISD::SETLT:
                case ISD::SETLE:
                case ISD::SETOLT:
                case ISD::SETOLE:
                    opc = tm_->getMinOpcode(n);
                    if (opc != -1) {
                        SELECT_NODE_AND_RETURN(
                            n,opc, n->getSimpleValueType(0), val1, val2);
                    }
                    break;
                case ISD::SETGT:
                case ISD::SETGE:
                case ISD::SETOGT:
                case ISD::SETOGE: // todo: what is ordered here? nan handling?
                    opc = tm_->getMaxOpcode(n);
                    if (opc != -1) {
                        SELECT_NODE_AND_RETURN(
                            n, opc, n->getSimpleValueType(0), val1, val2);
                    }
                    break;
                case ISD::SETULT:
                case ISD::SETULE:
                    opc = tm_->getMinuOpcode(n);
                    if (opc != -1) {
                        SELECT_NODE_AND_RETURN(
                            n, opc, n->getSimpleValueType(0), val1, val2);
                    }
                    break;
                case ISD::SETUGT:
                case ISD::SETUGE:
                    opc = tm_->getMaxuOpcode(n);
                    if (opc != -1) {
                        SELECT_NODE_AND_RETURN(
                            n, opc, n->getSimpleValueType(0), val1, val2);
                    }
                    break;
                default:
                    break;
                }
            }
        }
    } else if (n->getOpcode() == ISD::SHL ||
               n->getOpcode() == ISD::SRA ||
               n->getOpcode() == ISD::SRL) {
        SDValue shifted = n->getOperand(0);
        SDValue shifter = n->getOperand(1);
        EVT shiftedVt = shifted.getValueType();
        EVT shifterVt = shifter.getValueType();
    } else if (n->getOpcode() == ISD::AND ||
               n->getOpcode() == ISD::OR ||
               n->getOpcode() == ISD::XOR) {
        SDValue lhs = n->getOperand(0);
        SDValue rhs = n->getOperand(1);
        EVT lhsVt = lhs.getValueType();
        EVT rhsVt = rhs.getValueType();
    }
    SelectCode(n);
}
References DEFAULT_TYPE, TCEISD::FIRST_NUMBER, llvm::TCETargetMachine::getMaxOpcode(), llvm::TCETargetMachine::getMaxuOpcode(), llvm::TCETargetMachine::getMinOpcode(), llvm::TCETargetMachine::getMinuOpcode(), MOVE_IMM, SELECT_NODE_AND_RETURN, and tm_.
SelectADDRri()
bool TCEDAGToDAGISel::SelectADDRri (SDValue addr, SDValue & base, SDValue & offset)
Handles ADDRri operands.
Definition at line 249 of file TCEDAGToDAGISel.cc.
{
    if (FrameIndexSDNode* fin = dyn_cast<FrameIndexSDNode>(addr)) {
        base = CurDAG->getTargetFrameIndex(fin->getIndex(), DEFAULT_TYPE);
        offset = CurDAG->getTargetConstant(0, SDLoc(), DEFAULT_TYPE);
        return true;
    } else if (addr.getOpcode() == ISD::TargetExternalSymbol ||
               addr.getOpcode() == ISD::TargetGlobalAddress) {
        return false;  // direct calls.
    }
    base = addr;
    offset = CurDAG->getTargetConstant(0, SDLoc(), DEFAULT_TYPE);
    return true;
}
References DEFAULT_TYPE.
SelectADDRrr()
bool TCEDAGToDAGISel::SelectADDRrr (SDValue addr, SDValue & r1, SDValue & r2)
Handles ADDRrr operands.
Definition at line 270 of file TCEDAGToDAGISel.cc.
{
    if (addr.getOpcode() == ISD::TargetGlobalAddress) {
        //r1 = addr.getOperand(0);
        //r2 = CurDAG->getTargetConstant(cn->getValue(), MVT::i32);
        //return true:
        return false;
    } else if (addr.getOpcode() == ISD::TargetExternalSymbol) {
        return false;
    } else if (addr.getOpcode() == ISD::FrameIndex) {
        return false;
    }
    r1 = addr;
    r2 = CurDAG->getTargetConstant(0, SDLoc(), DEFAULT_TYPE);
    return true;
}
References DEFAULT_TYPE.
SelectOptimizedBuildVector()
void TCEDAGToDAGISel::SelectOptimizedBuildVector (SDNode * n) private
Member Data Documentation
ID
char TCEDAGToDAGISel::ID = 0 static
Definition at line 60 of file TCEDAGToDAGISel.cc.
lowering_
llvm::TCETargetLowering& TCEDAGToDAGISel::lowering_ private
Definition at line 87 of file TCEDAGToDAGISel.cc.
subtarget_
const llvm::TCESubtarget& TCEDAGToDAGISel::subtarget_ private
Definition at line 88 of file TCEDAGToDAGISel.cc.
tm_
llvm::TCETargetMachine* TCEDAGToDAGISel::tm_ private
Definition at line 89 of file TCEDAGToDAGISel.cc.
Referenced by Select().
The documentation for this class was generated from the following file:
TCEDAGToDAGISel.cc