OpenASIP: VectorTools Class Reference
VectorTools Class Reference
#include <VectorTools.hh>
Static Public Member Functions
template<typename ContainerType , typename ValueType >
static bool containsValue (const ContainerType &aVec, const ValueType &aValue)
template<typename ContainerType , typename ValueType >
static bool insertUnique (ContainerType &aVec, const ValueType &aValue)
template<typename ContainerType , typename ValueType >
static void removeDuplicates (ContainerType &aVec, const ValueType &aValue)
Detailed Description
Definition at line 41 of file VectorTools.hh.
Member Function Documentation
containsValue()
template<typename ContainerType , typename ValueType > static bool VectorTools::containsValue (const ContainerType & aVec, const ValueType & aValue) static
Referenced by InstructionFormat::addEncoding(), and ProGe::RV32MicroCodeGenerator::addRPorts().
insertUnique()
template<typename ContainerType , typename ValueType > static bool VectorTools::insertUnique (ContainerType & aVec, const ValueType & aValue) static
Referenced by Environment::osalPaths().
removeDuplicates()
template<typename ContainerType , typename ValueType > static void VectorTools::removeDuplicates (ContainerType & aVec, const ValueType & aValue) static
The documentation for this class was generated from the following file:
VectorTools.hh