OpenASIP: TTAProgram::TerminalProgramOperation Class Reference
TTAProgram::TerminalProgramOperation Class Reference
#include <TerminalProgramOperation.hh>
Public Member Functions
TerminalProgramOperation (TCEString instructionLabel)
TerminalProgramOperation (ProgramOperationPtr po)
virtual ~TerminalProgramOperation ()
ProgramOperationPtr programOperation () const
void setProgramOperation (ProgramOperationPtr po)
bool isProgramOperationKnown () const
bool isProgramOperationReference () const
bool isAddressKnown () const
virtual Address address () const
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
TCEString label () const
Public Member Functions inherited from TTAProgram::TerminalInstructionAddress
TerminalInstructionAddress ()
virtual ~TerminalInstructionAddress ()
bool isInstructionAddress () const
SimValue value () const
Public Member Functions inherited from TTAProgram::TerminalImmediate
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Private Member Functions
TerminalProgramOperation & operator= (const TerminalProgramOperation &)
Assignment not allowed.
Private Attributes
ProgramOperationPtr po_
The referred PO. The pointer can be copied, e.g. to DDG.
TCEString label_
Additional Inherited Members
Protected Attributes inherited from TTAProgram::TerminalImmediate
SimValue value_
Value of the inline immediate.
Detailed Description
Represents an inline immediate that refers to a program operation (a set of moves constituting a single execution of an operation in the program).
The returned instruction address is the one of the trigger move of the tracked ProgramOperation. This class is used to refer to the location of an another ProgramOperation strictly (not wanting to refer to the beginning of a BB).
Definition at line 51 of file TerminalProgramOperation.hh.
Constructor & Destructor Documentation
TerminalProgramOperation() [1/2]
TTAProgram::TerminalProgramOperation::TerminalProgramOperation (TCEString label)
Constructs an incomplete TerminalProgramOperation.
This can be used when a TerminalProgramOperation might point to an non-existing PO during builing of the program.
Parameters
label A textual label of the target PO. Should be used later to find the correct PO.
Definition at line 62 of file TerminalProgramOperation.cc.
                     :
    TerminalInstructionAddress(), label_(label) {
}
TerminalProgramOperation() [2/2]
TTAProgram::TerminalProgramOperation::TerminalProgramOperation (ProgramOperationPtr po)
The constructor.
Parameters
po The ProgramOperation to track.
Definition at line 48 of file TerminalProgramOperation.cc.
                                        :
    TerminalInstructionAddress(), po_(po) {
}
~TerminalProgramOperation()
TTAProgram::TerminalProgramOperation::~TerminalProgramOperation () virtual
The destructor.
Definition at line 71 of file TerminalProgramOperation.cc.
{
}
Member Function Documentation
address()
Address TTAProgram::TerminalProgramOperation::address () const virtual
Returns the instruction address of the trigger move in the tracked ProgramOperation.
Returns 0 in case the target PO is not in a program, thus its address is not known.
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 82 of file TerminalProgramOperation.cc.
{
    assert(isAddressKnown());
    return po_->triggeringMove()->move().parent().address();
}
References assert, isAddressKnown(), and po_.
copy()
Terminal * TTAProgram::TerminalProgramOperation::copy () const virtual
Creates an exact copy of the terminal and returns it.
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 99 of file TerminalProgramOperation.cc.
{
    TerminalProgramOperation* newObj = new TerminalProgramOperation(po_);
    newObj->label_ = this->label_;
    return newObj;
}
References label_, and po_.
equals()
bool TTAProgram::TerminalProgramOperation::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Implements TTAProgram::TerminalInstructionAddress.
Definition at line 109 of file TerminalProgramOperation.cc.
{
    if (!other.isInstructionAddress()) {
        return false;
    }
    return &dynamic_cast<const TerminalProgramOperation&>(other).po_ ==
        &this->po_;
}
References TTAProgram::Terminal::isInstructionAddress(), and po_.
isAddressKnown()
bool TTAProgram::TerminalProgramOperation::isAddressKnown () const
Definition at line 88 of file TerminalProgramOperation.cc.
{
    return isProgramOperationKnown() &&
        po_->triggeringMove() != NULL &&
        po_->triggeringMove()->move().isInInstruction() &&
        po_->triggeringMove()->move().parent().isInProcedure();
}
References isProgramOperationKnown(), and po_.
Referenced by address().
isProgramOperationKnown()
bool TTAProgram::TerminalProgramOperation::isProgramOperationKnown () const inline
Definition at line 65 of file TerminalProgramOperation.hh.
{
        return po_.get() != NULL;
    }
References po_.
Referenced by llvm::LLVMTCEBuilder::fixProgramOperationReferences(), and isAddressKnown().
isProgramOperationReference()
bool TTAProgram::TerminalProgramOperation::isProgramOperationReference () const inline virtual
Reimplemented from TTAProgram::Terminal.
Definition at line 69 of file TerminalProgramOperation.hh.
{ return true; }
label()
TCEString TTAProgram::TerminalProgramOperation::label () const inline
Definition at line 77 of file TerminalProgramOperation.hh.
{ return label_; }
References label_.
Referenced by ControlFlowGraph::buildMBBFromBB(), and llvm::LLVMTCEBuilder::fixProgramOperationReferences().
operator=()
TerminalProgramOperation & TTAProgram::TerminalProgramOperation::operator= (const TerminalProgramOperation &) private
Assignment not allowed.
programOperation()
ProgramOperationPtr TTAProgram::TerminalProgramOperation::programOperation () const inline
Definition at line 57 of file TerminalProgramOperation.hh.
{
        return po_;
    }
References po_.
Referenced by ControlFlowGraph::buildMBBFromBB().
setProgramOperation()
void TTAProgram::TerminalProgramOperation::setProgramOperation (ProgramOperationPtr po) inline
Definition at line 61 of file TerminalProgramOperation.hh.
{
        po_ = po;
    }
References po_.
Referenced by llvm::LLVMTCEBuilder::fixProgramOperationReferences().
Member Data Documentation
label_
TCEString TTAProgram::TerminalProgramOperation::label_ private
Definition at line 84 of file TerminalProgramOperation.hh.
Referenced by copy(), and label().
po_
ProgramOperationPtr TTAProgram::TerminalProgramOperation::po_ private
The referred PO. The pointer can be copied, e.g. to DDG.
Definition at line 83 of file TerminalProgramOperation.hh.
Referenced by address(), copy(), equals(), isAddressKnown(), isProgramOperationKnown(), programOperation(), and setProgramOperation().
The documentation for this class was generated from the following files:
TerminalProgramOperation.hh
TerminalProgramOperation.cc