OpenASIP: ConnectRequest Class Reference
ConnectRequest Class Reference
#include <ConnectRequest.hh>
Public Member Functions
ConnectRequest (EditPart *part)
virtual ~ConnectRequest ()
EditPart * part ()
Public Member Functions inherited from Request
Request (RequestType type)
virtual ~Request ()
void setType (RequestType type)
RequestType type () const
Private Member Functions
ConnectRequest & operator= (Request &old)
Assignment not allowed.
ConnectRequest (Request &old)
Copying not allowed.
Private Attributes
EditPart * part_
EditPart associated with the request.
Additional Inherited Members
Public Types inherited from Request
enum RequestType {
NONE , MODIFY_REQUEST , DELETE_REQUEST , CONNECT_REQUEST ,
COPY_REQUEST , STATUS_REQUEST , DETAILS_REQUEST
}
Data type for determining the type of a Request.
Detailed Description
Request which is used to request EditPart to create connection between itself and another EditPart.
Definition at line 43 of file ConnectRequest.hh.
Constructor & Destructor Documentation
ConnectRequest() [1/2]
ConnectRequest::ConnectRequest (EditPart * part)
The Constructor.
Parameters
part EditPart to connect the part with.
Definition at line 40 of file ConnectRequest.cc.
                   :
    Request(Request::CONNECT_REQUEST),
    part_(part) {
}
~ConnectRequest()
ConnectRequest::~ConnectRequest () virtual
The Destructor.
Definition at line 50 of file ConnectRequest.cc.
{
}
ConnectRequest() [2/2]
ConnectRequest::ConnectRequest (Request & old) private
Copying not allowed.
Member Function Documentation
operator=()
ConnectRequest & ConnectRequest::operator= (Request & old) private
Assignment not allowed.
part()
EditPart * ConnectRequest::part ()
Returns the EditPart associated with the request.
Definition at line 58 of file ConnectRequest.cc.
                     {
    return part_;
}
References part_.
Referenced by ProDePortEditPolicy::canHandle(), ProDeSegmentEditPolicy::canHandle(), ProDeSocketEditPolicy::canHandle(), ProDePortEditPolicy::createConnectCmd(), ProDeSegmentEditPolicy::createConnectCmd(), and ProDeSocketEditPolicy::createConnectCmd().
Member Data Documentation
part_
EditPart* ConnectRequest::part_ private
EditPart associated with the request.
Definition at line 54 of file ConnectRequest.hh.
Referenced by part().
The documentation for this class was generated from the following files:
ConnectRequest.hh
ConnectRequest.cc