OpenASIP: TemplateSlotDialog Class Reference
TemplateSlotDialog Class Reference
#include <TemplateSlotDialog.hh>
Public Member Functions
TemplateSlotDialog (wxWindow *parent, TTAMachine::InstructionTemplate *it, TTAMachine::TemplateSlot *slot=NULL)
virtual ~TemplateSlotDialog ()
Private Types
enum {
ID_LABEL_SLOT = 10000 , ID_SLOT , ID_LABEL_WIDTH , ID_WIDTH ,
ID_LABEL_DESTINATION , ID_DESTINATION , ID_LINE , ID_HELP
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
void setTexts ()
Private Attributes
TTAMachine::TemplateSlot * slot_
Instruction template slot to edit.
TTAMachine::InstructionTemplate * it_
Parent instruction template of the slot.
wxChoice * slotChoice_
Choice control for the slot.
wxChoice * destinationChoice_
Choice control fot the destination IU.
wxSpinCtrl * widthCtrl_
Spin control for the width.
int width_
Bit width of the slot.
TTAMachine::ImmediateUnit * destination_
Destination immediate unit.
Detailed Description
Dialog for editing telplate slot properties.
Definition at line 49 of file TemplateSlotDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LABEL_SLOT
ID_SLOT
ID_LABEL_WIDTH
ID_WIDTH
ID_LABEL_DESTINATION
ID_DESTINATION
ID_LINE
ID_HELP
Definition at line 80 of file TemplateSlotDialog.hh.
         {
        ID_LABEL_SLOT = 10000,
        ID_SLOT,
        ID_LABEL_WIDTH,
        ID_WIDTH,
        ID_LABEL_DESTINATION,
        ID_DESTINATION,
        ID_LINE,
        ID_HELP
    };
Constructor & Destructor Documentation
TemplateSlotDialog()
TemplateSlotDialog::TemplateSlotDialog (wxWindow * parent, TTAMachine::InstructionTemplate * it, TTAMachine::TemplateSlot * slot = NULL)
The Constructor.
Parameters
parent Parent window of the dialog.
temp InstructionTemplate to edit.
slot Slot to edit, NULL if a new slot is being added.
Definition at line 69 of file TemplateSlotDialog.cc.
                        :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    slot_(slot),
    it_(it),
    width_(ModelConstants::DEFAULT_WIDTH),
    destination_(NULL) {
    createContents(this, true, true);
    slotChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_SLOT));
    destinationChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_DESTINATION));
    widthCtrl_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_WIDTH));
    widthCtrl_->SetValidator(wxGenericValidator(&width_));
    // Read slot attributes.
    if (slot_ != NULL) {
        width_ = it_->supportedWidth(slot_->slot());
        Machine::ImmediateUnitNavigator navigator =
            it_->machine()->immediateUnitNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            if (it_->destinationUsesSlot(
                    slot_->slot(), *navigator.item(i))) {
                destination_ = navigator.item(i);
            }
        }
    }
    // set widget texts
    setTexts();
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), and TTAMachine::Machine::Navigator< ComponentType >::item().
~TemplateSlotDialog()
TemplateSlotDialog::~TemplateSlotDialog () virtual
The Destructor.
Definition at line 108 of file TemplateSlotDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * TemplateSlotDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 264 of file TemplateSlotDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_SLOT, wxT("Slot:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxChoice *item3 = new wxChoice( parent, ID_SLOT, wxDefaultPosition, wxSize(150,-1), 0, strs3, 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_DESTINATION, wxT("Destination:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_DESTINATION, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item7 = new wxSpinCtrl( parent, ID_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item1->Add( item7, 0, wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item8 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL );
    item0->Add( item8, 0, wxGROW|wxALL, 5 );
    wxFlexGridSizer *item9 = new wxFlexGridSizer( 2, 0, 0 );
    wxButton *item10 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALL, 5 );
    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item12 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item13 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    item9->Add( item11, 0, 0, 5 );
    item0->Add( item9, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DESTINATION, ID_HELP, ID_LABEL_DESTINATION, ID_LABEL_SLOT, ID_LABEL_WIDTH, ID_LINE, ID_SLOT, and ID_WIDTH.
onOK()
void TemplateSlotDialog::onOK (wxCommandEvent & event) private
Creates a new tempalte slot based on the dialog widget values.
Definition at line 220 of file TemplateSlotDialog.cc.
{
    string slotName = WxConversion::toString(slotChoice_->GetStringSelection());
    // Commit edit as new slot. Delete old slot.
    if (slot_ != NULL) {
        it_->removeSlot(slotName);
    }
    TransferDataFromWindow();
    const Machine::BusNavigator busNavigator = it_->machine()->busNavigator();
    const Machine::ImmediateSlotNavigator immsNavigator =
                    it_->machine()->immediateSlotNavigator();
    destination_ = it_->machine()->immediateUnitNavigator().item(
        WxConversion::toString(destinationChoice_->GetStringSelection()));
    if (busNavigator.hasItem(slotName)) {
        Bus* slot = it_->machine()->busNavigator().item(slotName);
        // create the new slot
        it_->addSlot(slot->name(), width_, *destination_);
    } else if (immsNavigator.hasItem(slotName)) {
        ImmediateSlot* slot = immsNavigator.item(slotName);
        // create the new slot
        it_->addSlot(slot->name(), width_, *destination_);
    } else {
        assert(false);
    }
    EndModal(wxID_OK);
}
References TTAMachine::InstructionTemplate::addSlot(), assert, TTAMachine::Machine::busNavigator(), destination_, destinationChoice_, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::immediateUnitNavigator(), it_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::InstructionTemplate::removeSlot(), slot_, slotChoice_, WxConversion::toString(), and width_.
setTexts()
void TemplateSlotDialog::setTexts () private
Sets texts for widgets.
Definition at line 116 of file TemplateSlotDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_TEMPLATE_SLOT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_SLOT),
                          ProDeTextGenerator::TXT_LABEL_SLOT);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_DESTINATION),
                          ProDeTextGenerator::TXT_LABEL_DESTINATION);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
}
References ID_HELP, ID_LABEL_DESTINATION, ID_LABEL_SLOT, ID_LABEL_WIDTH, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_LABEL_DESTINATION, ProDeTextGenerator::TXT_LABEL_SLOT, ProDeTextGenerator::TXT_LABEL_WIDTH, and ProDeTextGenerator::TXT_TEMPLATE_SLOT_DIALOG_TITLE.
TransferDataToWindow()
bool TemplateSlotDialog::TransferDataToWindow () private virtual
Transfers data from the InstructionTemplate object to the dialog widgets.
Returns
true, if the transfer was succesful, false otherwise.
Definition at line 154 of file TemplateSlotDialog.cc.
{
    // Set slot choicer.
    slotChoice_->Clear();
    if (slot_ == NULL) {
        // A new slot is being added, set all available busses to the
        // slot choice.
        Machine::BusNavigator navigator = it_->machine()->busNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            if (!(it_->usesSlot(navigator.item(i)->name()))) {
                wxString name =
                    WxConversion::toWxString(navigator.item(i)->name());
                slotChoice_->Append(name);
            }
        }
    // Add immediate slots.
        Machine::ImmediateSlotNavigator immSlotNavigator =
        it_->machine()->immediateSlotNavigator();
        for (int i = 0; i < immSlotNavigator.count(); i++) {
            if (!(it_->usesSlot(immSlotNavigator.item(i)->name()))) {
                wxString name =
                    WxConversion::toWxString(immSlotNavigator.item(i)->name());
                slotChoice_->Append(name);
            }
        }
    } else {
        // An old slot is being modified, set the slot and disable the control.
        slotChoice_->Append(WxConversion::toWxString(slot_->slot()));
        slotChoice_->Disable();
    }
    // Set destination choicer.
    destinationChoice_->Clear();
    Machine::ImmediateUnitNavigator navigator =
        it_->machine()->immediateUnitNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        wxString name =
            WxConversion::toWxString(navigator.item(i)->name());
        destinationChoice_->Append(name);
    }
    // Set selections for editing slot
    if(slot_ != NULL) {
      wxString name = WxConversion::toWxString(slot_->destination()->name());
      assert(!name.empty());
      destinationChoice_->SetSelection(destinationChoice_->FindString(name));
      widthCtrl_->SetValue(slot_->width());
    }
    // Set choicer selections.
    slotChoice_->SetSelection(0);
    if (destination_ == NULL) {
        destinationChoice_->SetSelection(0);
    } else {
        wxString name = WxConversion::toWxString(destination_->name());
        destinationChoice_->SetStringSelection(name);
    }
    return wxDialog::TransferDataToWindow();
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::TemplateSlot::destination(), destination_, destinationChoice_, TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::immediateUnitNavigator(), it_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::TemplateSlot::slot(), slot_, slotChoice_, WxConversion::toWxString(), TTAMachine::InstructionTemplate::usesSlot(), TTAMachine::TemplateSlot::width(), and widthCtrl_.
Member Data Documentation
destination_
TTAMachine::ImmediateUnit* TemplateSlotDialog::destination_ private
Destination immediate unit.
Definition at line 77 of file TemplateSlotDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
destinationChoice_
wxChoice* TemplateSlotDialog::destinationChoice_ private
Choice control fot the destination IU.
Definition at line 71 of file TemplateSlotDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
it_
TTAMachine::InstructionTemplate* TemplateSlotDialog::it_ private
Parent instruction template of the slot.
Definition at line 67 of file TemplateSlotDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
slot_
TTAMachine::TemplateSlot* TemplateSlotDialog::slot_ private
Instruction template slot to edit.
Definition at line 65 of file TemplateSlotDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
slotChoice_
wxChoice* TemplateSlotDialog::slotChoice_ private
Choice control for the slot.
Definition at line 69 of file TemplateSlotDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
width_
int TemplateSlotDialog::width_ private
Bit width of the slot.
Definition at line 75 of file TemplateSlotDialog.hh.
Referenced by onOK().
widthCtrl_
wxSpinCtrl* TemplateSlotDialog::widthCtrl_ private
Spin control for the width.
Definition at line 73 of file TemplateSlotDialog.hh.
Referenced by TransferDataToWindow().
The documentation for this class was generated from the following files:
TemplateSlotDialog.hh
TemplateSlotDialog.cc