OpenASIP: MoveFigure Class Reference
MoveFigure Class Reference
#include <MoveFigure.hh>
Public Member Functions
MoveFigure (Figure *bus, Figure *source, Figure *target)
virtual ~MoveFigure ()
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
Private Attributes
Figure * bus_
Figure of the bus where the move is done.
Figure * source_
Figure of the source port.
Figure * target_
Figure of the TargetPort.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(255, 255, 0)
Default colour of the figure.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a move.
Definition at line 41 of file MoveFigure.hh.
Constructor & Destructor Documentation
MoveFigure()
MoveFigure::MoveFigure (Figure * bus, Figure * source, Figure * target)
The Constructor.
Parameters
bus Figure of the bus which transports the move.
source Figure of the source port of the move.
target Figure of the target port of the move.
Definition at line 45 of file MoveFigure.cc.
                                                                 :
    Figure(), bus_(bus), source_(source), target_(target) {
        laidOut_ = true;
}
References Figure::laidOut_.
~MoveFigure()
MoveFigure::~MoveFigure () virtual
The Destructor.
Definition at line 55 of file MoveFigure.cc.
{
}
Member Function Documentation
drawSelf()
void MoveFigure::drawSelf (wxDC * dc) protected virtual
Draws the move figure on a device context.
Parameters
dc Device context where to draw the figure.
Reimplemented from Figure.
Definition at line 65 of file MoveFigure.cc.
{
    assert(bus_ != NULL);
    wxPen pen = wxPen(DEFAULT_COLOUR, 4, wxSOLID);
    wxBrush brush = wxBrush(DEFAULT_COLOUR, wxSOLID);
    dc->SetPen(pen);
    dc->SetBrush(brush);
    int offset = MachineCanvasLayoutConstraints::PORT_WIDTH / 2;
    int busY = bus_->location().y + bus_->bounds().GetHeight()/2;
    int sourceX = 0;
    int targetX = 0;
    // Draw source port -> bus line.
    if (source_ != NULL) {
        sourceX = source_->location().x + source_->bounds().GetWidth()/2;
        int sourceY = source_->location().y + offset * 2;
        dc->DrawLine(sourceX, sourceY, sourceX, busY);
        int size = std::max(
            std::min(source_->bounds().GetWidth(),
                     (MachineCanvasLayoutConstraints::BUS_SPACE-2)),
            (MachineCanvasLayoutConstraints::SOCKET_WIDTH));
        dc->DrawCircle(sourceX, busY, size/2);
    }
    // Draw bus -> target port line.
    if (target_ != NULL) {
        targetX = target_->location().x + target_->bounds().GetWidth()/2;
        int targetY = target_->location().y + offset * 2;
        dc->DrawLine(targetX, targetY, targetX, busY);
        int size = std::max(
            std::min(target_->bounds().GetWidth(),
                     (MachineCanvasLayoutConstraints::BUS_SPACE-2)),
            (MachineCanvasLayoutConstraints::SOCKET_WIDTH));
        dc->DrawCircle(targetX, busY, size/2);
    }
    // Draw line on the bus.
    if (target_ != NULL && source_ != NULL) {
        dc->DrawLine(sourceX, busY, targetX, busY);
    } else {
        // Source or target missing. Draw move over the whole bus.
        sourceX = bus_->location().x;
        targetX = bus_->location().x + bus_->bounds().GetWidth();
        dc->DrawLine(sourceX, busY, targetX, busY);
    }
}
References assert, Figure::bounds(), bus_, MachineCanvasLayoutConstraints::BUS_SPACE, DEFAULT_COLOUR, Figure::location(), MachineCanvasLayoutConstraints::PORT_WIDTH, MachineCanvasLayoutConstraints::SOCKET_WIDTH, source_, and target_.
Member Data Documentation
bus_
Figure* MoveFigure::bus_ private
Figure of the bus where the move is done.
Definition at line 53 of file MoveFigure.hh.
Referenced by drawSelf().
DEFAULT_COLOUR
const wxColour MoveFigure::DEFAULT_COLOUR = wxColour(255, 255, 0) static private
Default colour of the figure.
Definition at line 51 of file MoveFigure.hh.
Referenced by drawSelf().
source_
Figure* MoveFigure::source_ private
Figure of the source port.
Definition at line 55 of file MoveFigure.hh.
Referenced by drawSelf().
target_
Figure* MoveFigure::target_ private
Figure of the TargetPort.
Definition at line 57 of file MoveFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
MoveFigure.hh
MoveFigure.cc