OpenASIP: KillCommand Class Reference
KillCommand Class Reference
#include <KillCommand.hh>
Public Member Functions
KillCommand ()
virtual ~KillCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "kill" command of the Simulator Control Language.
Definition at line 46 of file KillCommand.hh.
Constructor & Destructor Documentation
KillCommand()
KillCommand::KillCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 47 of file KillCommand.cc.
                         :
    SimControlLanguageCommand("kill") {
}
~KillCommand()
KillCommand::~KillCommand () virtual
Destructor.
Does nothing.
Definition at line 56 of file KillCommand.cc.
{
}
Member Function Documentation
execute()
bool KillCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "kill" command.
Terminate the simulation. The program being simulated remains loaded and the simulation can be restarted from the beginning by means of command run. The Simulator will normally prompt the user for comfirmation before terminating the simulation.
Parameters
arguments No arguments needed.
Returns
Always true.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 73 of file KillCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 0, 0)) {
        return false;
    }
    if (!checkSimulationEnded()) {
        if (!checkSimulationStopped()) {
            return false;
        }
    }
    if (!interpreter()->lineReader()->confirmation(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_CONFIRM_KILL_SIMULATION).str())) {
        return false;
    }
    simulatorFrontend().killSimulation();
    return true;
}
References CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkSimulationEnded(), SimControlLanguageCommand::checkSimulationStopped(), CustomCommand::interpreter(), SimulatorFrontend::killSimulation(), SimControlLanguageCommand::simulatorFrontend(), SimulatorToolbox::textGenerator(), and Texts::TXT_CONFIRM_KILL_SIMULATION.
helpText()
std::string KillCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 104 of file KillCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_KILL).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_KILL.
The documentation for this class was generated from the following files:
KillCommand.hh
KillCommand.cc