OpenASIP: KoskiIntegrator Class Reference
KoskiIntegrator Class Reference
#include <KoskiIntegrator.hh>
Public Member Functions
KoskiIntegrator ()
KoskiIntegrator (const TTAMachine::Machine *machine, const IDF::MachineImplementation *idf, ProGe::HDL hdl, TCEString progeOutputDir, TCEString coreEntityName, TCEString outputDir, TCEString programName, int targetClockFreq, std::ostream &warningStream, std::ostream &errorStream, const MemInfo &imem, MemType dmemType)
virtual ~KoskiIntegrator ()
virtual TCEString deviceFamily () const
virtual void setDeviceFamily (TCEString devFamily)
virtual TCEString devicePackage () const
virtual TCEString deviceSpeedClass () const
virtual int targetClockFrequency () const
virtual void printInfo (std::ostream &stream) const
Public Member Functions inherited from AlteraIntegrator
AlteraIntegrator ()
AlteraIntegrator (const TTAMachine::Machine *machine, const IDF::MachineImplementation *idf, ProGe::HDL hdl, TCEString progeOutputDir, TCEString entityName, TCEString outputDir, TCEString programName, int targetClockFreq, std::ostream &warningStream, std::ostream &errorStream, const MemInfo &imem, MemType dmemType)
virtual ~AlteraIntegrator ()
virtual void integrateProcessor (const ProGe::NetlistBlock *progeBlock)
Public Member Functions inherited from PlatformIntegrator
PlatformIntegrator ()
PlatformIntegrator (const TTAMachine::Machine *machine, const IDF::MachineImplementation *idf, ProGe::HDL hdl, TCEString progeOutputDir, TCEString coreEntityName, TCEString outputDir, TCEString programName, int targetClockFreq, std::ostream &warningStream, std::ostream &errorStream, const MemInfo &imem, MemType dmemType)
virtual ~PlatformIntegrator ()
void setDeviceName (TCEString devName)
TCEString deviceName () const
const ProGe::NetlistBlock & progeBlock () const
const ProGe::NetlistBlock & toplevelBlock () const
void setSharedOutputDir (const TCEString &sharedDir)
TCEString outputPath () const
TCEString outputFilePath (TCEString fileName, bool absolute=false) const
TCEString coreEntityName () const
const TTAMachine::Machine * machine () const
const IDF::MachineImplementation * idf () const
const MemInfo & imemInfo () const
const MemInfo & dmemInfo (TTAMachine::AddressSpace *as) const
const MemInfo & dmemInfo (int index) const
int dmemCount () const
ProGe::NetlistPort * clockPort () const
ProGe::NetlistPort * resetPort () const
Protected Member Functions
virtual TCEString pinTag () const
virtual bool chopTaggedSignals () const
virtual ProjectFileGenerator * projectFileGenerator () const
virtual MemoryGenerator & dmemInstance (MemInfo dmem, TTAMachine::FunctionUnit &lsuArch, std::vector< std::string > lsuPorts)
Protected Member Functions inherited from AlteraIntegrator
virtual MemoryGenerator & imemInstance (MemInfo imem, int coreId)
Protected Member Functions inherited from PlatformIntegrator
ProGe::NetlistBlock * integratorBlock ()
virtual void initPlatformNetlist (const ProGe::NetlistBlock *progeBlock)
virtual bool integrateCore (const ProGe::NetlistBlock &cores, int coreId)
virtual void exportUnconnectedPorts (int coreId)
virtual void connectToplevelPort (const ProGe::NetlistPort &corePort, const TCEString signalPrefix="")
virtual bool hasPinTag (const TCEString &signal) const
void copyProgeBlockToNetlist (const ProGe::NetlistBlock *progeBlock)
virtual bool createMemories (int coreId)
virtual bool generateMemory (MemoryGenerator &memGen, std::vector< TCEString > &generatedFiles, int memIndex, int coreId)
virtual void writeNewToplevel ()
void addProGeFiles () const
TCEString programName () const
TCEString progeFilePath (TCEString fileName, bool absolute=false) const
TCEString tbFilePath (TCEString fileName, bool absolute=false) const
TCEString chopSignalToTag (const TCEString &original, const TCEString &tag) const
void progeOutputHdlFiles (std::vector< TCEString > &files) const
std::ostream & warningStream () const
std::ostream & errorStream () const
TCEString platformEntityName () const
void parseDataMemories ()
void clearDataMemories ()
MemInfo readLsuParameters (const TTAMachine::FunctionUnit &lsu)
Private Attributes
ProjectFileGenerator * ipXactGen_
TCEString deviceFamily_
MemoryGenerator * dmemGen_
Static Private Attributes
static const TCEString PIN_TAG_ = "hibi"
static const TCEString DEFAULT_DEVICE_FAMILY_ = "Stratix II"
Additional Inherited Members
Static Protected Attributes inherited from PlatformIntegrator
static const TCEString TTA_CORE_CLK = "clk"
static const TCEString TTA_CORE_RSTX = "rstx"
Detailed Description
Definition at line 40 of file KoskiIntegrator.hh.
Constructor & Destructor Documentation
KoskiIntegrator() [1/2]
KoskiIntegrator::KoskiIntegrator ()
Definition at line 47 of file KoskiIntegrator.cc.
                                :
    AlteraIntegrator(), ipXactGen_(NULL),
    deviceFamily_(DEFAULT_DEVICE_FAMILY_), dmemGen_(NULL) {
}
KoskiIntegrator() [2/2]
KoskiIntegrator::KoskiIntegrator (const TTAMachine::Machine * machine, const IDF::MachineImplementation * idf, ProGe::HDL hdl, TCEString progeOutputDir, TCEString coreEntityName, TCEString outputDir, TCEString programName, int targetClockFreq, std::ostream & warningStream, std::ostream & errorStream, const MemInfo & imem, MemType dmemType)
Definition at line 53 of file KoskiIntegrator.cc.
                     :
    AlteraIntegrator(machine, idf, hdl, progeOutputDir, coreEntityName,
                     outputDir, programName, targetClockFreq, warningStream,
                     errorStream, imem, dmemType),
    ipXactGen_(new IPXactFileGenerator(coreEntityName, this)),
    deviceFamily_(DEFAULT_DEVICE_FAMILY_), dmemGen_(NULL) {
}
~KoskiIntegrator()
KoskiIntegrator::~KoskiIntegrator () virtual
Definition at line 74 of file KoskiIntegrator.cc.
{
    if (ipXactGen_ != NULL) {
        delete ipXactGen_;
    }
    if (dmemGen_ != NULL) {
        delete dmemGen_;
    }
}
References dmemGen_, and ipXactGen_.
Member Function Documentation
chopTaggedSignals()
bool KoskiIntegrator::chopTaggedSignals () const protected virtual
Implements PlatformIntegrator.
Definition at line 92 of file KoskiIntegrator.cc.
{
    return false;
}
deviceFamily()
TCEString KoskiIntegrator::deviceFamily () const virtual
Returns the FPGA device family
Implements PlatformIntegrator.
Definition at line 147 of file KoskiIntegrator.cc.
{
    return deviceFamily_;
}
References deviceFamily_.
devicePackage()
TCEString KoskiIntegrator::devicePackage () const virtual
Returns the device package name
Implements PlatformIntegrator.
Definition at line 159 of file KoskiIntegrator.cc.
{
    return "";
}
deviceSpeedClass()
TCEString KoskiIntegrator::deviceSpeedClass () const virtual
Returns the device speed class
Implements PlatformIntegrator.
Definition at line 164 of file KoskiIntegrator.cc.
{
    return "";
}
dmemInstance()
MemoryGenerator & KoskiIntegrator::dmemInstance (MemInfo dmem, TTAMachine::FunctionUnit & lsuArch, std::vector< std::string > lsuPorts) protected virtual
Reimplemented from AlteraIntegrator.
Definition at line 105 of file KoskiIntegrator.cc.
{
    if (dmem.type == ONCHIP) {
        if (dmemGen_ == NULL) {
            TCEString initFile = programName() + "_" + dmem.asName + ".mif";
            // onchip mem size is scalable, use value from adf's Address Space
            int addrw = dmem.portAddrw;
            dmemGen_ =
                new AlteraHibiDpRamGenerator(
                    dmem.mauWidth, dmem.widthInMaus, addrw, initFile,
                    this, warningStream(), errorStream());
            ipXactGen_->addMemInitFile(initFile);
            dmemGen_->addLsu(lsuArch, lsuPorts);
        }
    } else {
        TCEString msg = "Unsupported data memory type";
        InvalidData exc(__FILE__, __LINE__, "KoskiIntegrator",
                        msg);
        throw exc;
    }
    return *dmemGen_;
}
References MemoryGenerator::addLsu(), ProjectFileGenerator::addMemInitFile(), MemInfo::asName, dmemGen_, PlatformIntegrator::errorStream(), ipXactGen_, MemInfo::mauWidth, ONCHIP, MemInfo::portAddrw, PlatformIntegrator::programName(), MemInfo::type, PlatformIntegrator::warningStream(), and MemInfo::widthInMaus.
pinTag()
TCEString KoskiIntegrator::pinTag () const protected virtual
Implements PlatformIntegrator.
Definition at line 85 of file KoskiIntegrator.cc.
{
    return PIN_TAG_;
}
References PIN_TAG_.
printInfo()
void KoskiIntegrator::printInfo (std::ostream & stream) const virtual
Prints information about the platform
Implements PlatformIntegrator.
Definition at line 131 of file KoskiIntegrator.cc.
{
    stream
        << "Integrator name: KoskiIntegrator" << endl
        << "---------------------------------" << endl
        << "Integrates TTA core to Koski flow compatible IP-block. "
        << "Processor must have a HIBIs-LSU. " << endl
        << "Creates an IP-XACT description of the created IP." << endl
        << "This integrator works with Altera tools and FPGAs." << endl
        << "Supported instruction memory types are 'onchip' and 'vhdl_array."
        << endl << "Supported data memory type is 'onchip'." << endl
        << "FPGA device family can be changed. Default device family is "
        << DEFAULT_DEVICE_FAMILY_ << endl << endl;
}
References DEFAULT_DEVICE_FAMILY_.
projectFileGenerator()
ProjectFileGenerator * KoskiIntegrator::projectFileGenerator () const protected virtual
Implements PlatformIntegrator.
Definition at line 99 of file KoskiIntegrator.cc.
{
    return ipXactGen_;
}
References ipXactGen_.
setDeviceFamily()
void KoskiIntegrator::setDeviceFamily (TCEString devFamily) virtual
Set the FPGA device family.
Intended for TTA IP integration. Integrator can device whether this overrides the default device family.
Implements PlatformIntegrator.
Definition at line 153 of file KoskiIntegrator.cc.
{
    deviceFamily_ = devFamily;
}
References deviceFamily_.
targetClockFrequency()
int KoskiIntegrator::targetClockFrequency () const virtual
Returns the target clock frequency in MHz
Reimplemented from PlatformIntegrator.
Definition at line 169 of file KoskiIntegrator.cc.
{
    return 1;
}
Member Data Documentation
DEFAULT_DEVICE_FAMILY_
const TCEString KoskiIntegrator::DEFAULT_DEVICE_FAMILY_ = "Stratix II" static private
Definition at line 94 of file KoskiIntegrator.hh.
Referenced by printInfo().
deviceFamily_
TCEString KoskiIntegrator::deviceFamily_ private
Definition at line 89 of file KoskiIntegrator.hh.
Referenced by deviceFamily(), and setDeviceFamily().
dmemGen_
MemoryGenerator* KoskiIntegrator::dmemGen_ private
Definition at line 91 of file KoskiIntegrator.hh.
Referenced by dmemInstance(), and ~KoskiIntegrator().
ipXactGen_
ProjectFileGenerator* KoskiIntegrator::ipXactGen_ private
Definition at line 87 of file KoskiIntegrator.hh.
Referenced by dmemInstance(), projectFileGenerator(), and ~KoskiIntegrator().
PIN_TAG_
const TCEString KoskiIntegrator::PIN_TAG_ = "hibi" static private
Definition at line 93 of file KoskiIntegrator.hh.
Referenced by pinTag().
The documentation for this class was generated from the following files:
KoskiIntegrator.hh
KoskiIntegrator.cc