OpenASIP: OperationDAGDialog Class Reference
OperationDAGDialog Class Reference
#include <OperationDAGDialog.hh>
Public Member Functions
OperationDAGDialog (wxWindow *parent, Operation *op)
virtual ~OperationDAGDialog ()
Operation * operation () const
Private Types
enum {
ID_EDIT_DAG = 1000 , ID_SAVE_DAG_BUTTON , ID_UNDO_DAG_BUTTON , ID_DELETE_DAG_BUTTON ,
ID_NEW_DAG_BUTTON , ID_DAG_IMAGE , ID_INDEX_DAG , ID_OK_BUTTON ,
ID_CANCEL_BUTTON
}
Private Member Functions
OperationDAGDialog (const OperationDAGDialog &)
Copying not allowed.
OperationDAGDialog & operator= (const OperationDAGDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void updateIndex ()
bool hasDot ()
void updateDAG ()
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
void doSaveDAG (int index)
void onSaveDAG (wxCommandEvent &event)
void onUndoDAG (wxCommandEvent &event)
void onDeleteDAG (wxCommandEvent &event)
void onNewDAG (wxCommandEvent &event)
void onDAGChange (wxCommandEvent &event)
void onComboBoxChange (wxCommandEvent &event)
ObjectState * saveOperation ()
void setTexts ()
void setBehaviorLabel ()
Private Attributes
Operation * operation_
Operation to be created or to be modified.
ObjectState * orig_
Original operation's ObjectState tree.
wxTextCtrl * dagEdit_
wxTextCtrl * editDescription_
wxChoice * dagIndex_
wxBitmap * dotImage_
wxStaticBitmap * dagStaticBitmap_
wxStaticBoxSizer * dagImageStaticBoxSizer_
wxScrolledWindow * dagWindow_
bool dotInstalled_
Detailed Description
Dialog which is used to create or modify an operation.
Definition at line 51 of file OperationDAGDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_EDIT_DAG
ID_SAVE_DAG_BUTTON
ID_UNDO_DAG_BUTTON
ID_DELETE_DAG_BUTTON
ID_NEW_DAG_BUTTON
ID_DAG_IMAGE
ID_INDEX_DAG
ID_OK_BUTTON
ID_CANCEL_BUTTON
Definition at line 92 of file OperationDAGDialog.hh.
         {
        ID_EDIT_DAG = 1000,
        ID_SAVE_DAG_BUTTON,
        ID_UNDO_DAG_BUTTON,
        ID_DELETE_DAG_BUTTON,
        ID_NEW_DAG_BUTTON,
        ID_DAG_IMAGE,
        ID_INDEX_DAG,
        ID_OK_BUTTON,
        ID_CANCEL_BUTTON
    };
Constructor & Destructor Documentation
OperationDAGDialog() [1/2]
OperationDAGDialog::OperationDAGDialog (wxWindow * parent, Operation * op)
Constructor.
Parameters
parent The parent window.
op Operation to be created or modified.
module Module in which operation belongs to.
path Path in which module belongs to.
Definition at line 91 of file OperationDAGDialog.cc.
                    :
     wxDialog(
         parent, -1, _T(""),
         DialogPosition::getPosition(DialogPosition::DIALOG_PROPERTIES),
         wxDefaultSize, wxRESIZE_BORDER),
     operation_(op),
     dotInstalled_(false) {
    createContents(this, true, true);
    dagEdit_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_EDIT_DAG));
    dagIndex_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_INDEX_DAG));
    //FindWindow(ID_NAME)->SetValidator(
     //   wxTextValidator(wxFILTER_ASCII, &name_));
    // set OK button as default choice
    // FindWindow(ID_OK_BUTTON)->SetFocus();
    orig_ = operation_->saveState(); // save original operation's state
    setTexts();
    FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
    FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
    FindWindow(ID_DELETE_DAG_BUTTON)->Disable();
    FindWindow(ID_NEW_DAG_BUTTON)->Disable();
    updateIndex();
    dotInstalled_ = hasDot();
    updateDAG();
}
~OperationDAGDialog()
OperationDAGDialog::~OperationDAGDialog () virtual
Destructor.
Definition at line 134 of file OperationDAGDialog.cc.
{
    // set dialog position
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_PROPERTIES, point);
}
References DialogPosition::DIALOG_PROPERTIES, and DialogPosition::setPosition().
OperationDAGDialog() [2/2]
OperationDAGDialog::OperationDAGDialog (const OperationDAGDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * OperationDAGDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
Parameters
parent Parent window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 516 of file OperationDAGDialog.cc.
                    {
    // Window for scrolling DAG image
    wxSize size(300, 400);
    dagWindow_ = new wxScrolledWindow(parent, -1, wxDefaultPosition, size);
    // Window sizers
    wxBoxSizer *item0 = new wxBoxSizer(wxVERTICAL);
    // Static box for DAG code
    wxStaticBox *dagStaticBox = new wxStaticBox(parent, -1, wxT("Code"));
    wxStaticBoxSizer *dagStaticBoxSizer =
        new wxStaticBoxSizer(dagStaticBox, wxVERTICAL);
    // DAG editor
    wxTextCtrl* editDAG =
        new wxTextCtrl(
                parent, ID_EDIT_DAG, wxT(""), wxDefaultPosition,
                wxSize(250,-1), wxTE_MULTILINE);
    // Static box for DAG image
    wxStaticBox *dagImageStaticBox = new wxStaticBox(parent, -1, wxT("DAG"));
    dagImageStaticBoxSizer_ =
        new wxStaticBoxSizer(dagImageStaticBox, wxVERTICAL);
    dagImageStaticBoxSizer_->Add(dagWindow_, 1, wxALL|wxGROW, 5);
    dagImageStaticBoxSizer_->SetDimension(-1, -1, 550, 550);
    // DAG image
    dotImage_ = new wxBitmap(300,100);
    dagStaticBitmap_ =
        new wxStaticBitmap(dagWindow_, ID_DAG_IMAGE, *dotImage_);
    dagWindow_->SetSize(-1, -1, 50, 50);
    dagWindow_->SetScrollbars(20, 20, 20, 20);
    dagImageStaticBoxSizer_->Show(true);
    // Add DAG editor to DAG code sizer
    dagStaticBoxSizer->Add(editDAG, 1, wxALL|wxGROW, 5);
    // Add DAG code to page sizer
    wxBoxSizer *pageSizer = new wxBoxSizer(wxHORIZONTAL);
    pageSizer->Add(dagStaticBoxSizer, 1, wxGROW|wxTOP, 10);
    pageSizer->Add(dagImageStaticBoxSizer_, 2, wxGROW|wxTOP, 10);
    // Add page sizer to window sizer
    item0->Add(pageSizer, 1, wxEXPAND|wxALL, 5);
    wxString strs9[] =
        {
            wxT("id: 1")
        };
    // ComboBox for choosing DAG
    wxChoice *indexDAG =
        new wxChoice(
                parent, ID_INDEX_DAG, wxDefaultPosition, wxSize(150,-1), 1,
                strs9);
    wxButton *saveDAG =
        new wxButton(
                parent, ID_SAVE_DAG_BUTTON, wxT("Save"), wxDefaultPosition,
                wxDefaultSize, 0);
    wxButton *undoDAG =
        new wxButton(
                parent, ID_UNDO_DAG_BUTTON, wxT("Undo"), wxDefaultPosition,
                wxDefaultSize, 0);
    wxButton *deleteDAG =
        new wxButton(
                parent, ID_DELETE_DAG_BUTTON, wxT("Delete"), wxDefaultPosition,
                wxDefaultSize, 0);
    wxButton *newDAG =
        new wxButton(
                parent, ID_NEW_DAG_BUTTON, wxT("New"), wxDefaultPosition,
                wxDefaultSize, 0);
    wxBoxSizer *dagToolsSizer = new wxBoxSizer(wxHORIZONTAL);
    dagToolsSizer->Add(indexDAG, 0, wxALIGN_CENTER|wxALL, 5);
    wxGridSizer *dagButtonSizer = new wxGridSizer(2, 0, 0);
    dagButtonSizer->Add(saveDAG, 0, wxALIGN_CENTER|wxALL, 5);
    dagButtonSizer->Add(undoDAG, 0, wxALIGN_CENTER|wxALL, 5);
    dagButtonSizer->Add(deleteDAG, 0, wxALIGN_CENTER|wxALL, 5);
    dagButtonSizer->Add(newDAG, 0, wxALIGN_CENTER|wxALL, 5);
    dagToolsSizer->Add(dagButtonSizer, 0, wxALIGN_CENTER|wxALL, 5);
    dagStaticBoxSizer->Add(dagToolsSizer, 0, wxALL, 5);
    wxBoxSizer *controlButtonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxButton *OK =
        new wxButton(
                parent, ID_OK_BUTTON, wxT("Ok"), wxDefaultPosition,
                wxDefaultSize, 0);
    wxButton *Cancel =
        new wxButton(
                parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition,
                wxDefaultSize, 0);
    controlButtonSizer->Add(OK, 0, wxALL, 5);
    controlButtonSizer->Add(Cancel, 0, wxALL, 5);
    item0->Add(
            controlButtonSizer, 0,
            wxALL, 5);
    if (set_sizer) {
        parent->SetSizer(item0);
        if (call_fit) {
            item0->SetSizeHints(parent);
        }
    }
    return item0;
}
References dagImageStaticBoxSizer_, dagStaticBitmap_, dagWindow_, dotImage_, ID_DAG_IMAGE, ID_DELETE_DAG_BUTTON, ID_EDIT_DAG, ID_INDEX_DAG, ID_NEW_DAG_BUTTON, ID_OK_BUTTON, ID_SAVE_DAG_BUTTON, and ID_UNDO_DAG_BUTTON.
doSaveDAG()
void OperationDAGDialog::doSaveDAG (int index) private
Definition at line 389 of file OperationDAGDialog.cc.
{
    std::string code("");
    wxString wxTemp;
    for (int i = 0; i < dagEdit_->GetNumberOfLines(); ++i) {
        wxTemp = dagEdit_->GetLineText(i);
#if wxCHECK_VERSION(2, 6, 0)
        std::string stdTemp(wxTemp.mb_str());
#else
        std::string stdTemp(wxTemp.c_str());
#endif
        code += stdTemp;
        code += '\n';
    }
    if (operation_->dagCount() == index) {
        operation_->addDag(code);
    } else {
        operation_->setDagCode(index, code.c_str());
    }
    updateIndex();
    dagIndex_->SetSelection(index);
    updateDAG();
}
References Operation::addDag(), Operation::dagCount(), dagEdit_, dagIndex_, operation_, Operation::setDagCode(), updateDAG(), and updateIndex().
Referenced by onOK(), and onSaveDAG().
hasDot()
bool OperationDAGDialog::hasDot () private
Tests whether user has program dot is installed.
Returns
True if dot is installed.
Definition at line 223 of file OperationDAGDialog.cc.
{
    if (system("which dot > /dev/null 2>&1") != 0) {
        wxString caption(wxString::FromAscii("Warning"));
        wxString message(
                wxString::FromAscii(
                    "You must have dot installed to display DAGs."));
        wxMessageBox(message, caption);
        dagImageStaticBoxSizer_->Show(false);
        Layout();
        return false; // cannot display DAG without dot
    } else {
        return true;
    }
}
References dagImageStaticBoxSizer_.
onCancel()
void OperationDAGDialog::onCancel (wxCommandEvent & event) private
Handles the event when Cancel button is pushed.
Definition at line 383 of file OperationDAGDialog.cc.
{
    operation_->loadState(orig_);
    EndModal(wxID_CANCEL);
}
References Operation::loadState(), operation_, and orig_.
onComboBoxChange()
void OperationDAGDialog::onComboBoxChange (wxCommandEvent & event) private
Handles the event when ComboBox is changed
Definition at line 503 of file OperationDAGDialog.cc.
{
    updateDAG();
}
References updateDAG().
onDAGChange()
void OperationDAGDialog::onDAGChange (wxCommandEvent & event) private
Handles the event when DAG is changed
Definition at line 494 of file OperationDAGDialog.cc.
{
    FindWindow(ID_UNDO_DAG_BUTTON)->Enable();
    FindWindow(ID_SAVE_DAG_BUTTON)->Enable();
}
References ID_SAVE_DAG_BUTTON, and ID_UNDO_DAG_BUTTON.
onDeleteDAG()
void OperationDAGDialog::onDeleteDAG (wxCommandEvent & event) private
Handles the event when Delete button is pushed.
Definition at line 458 of file OperationDAGDialog.cc.
{
    int index = dagIndex_->GetSelection();
    if (operation_->dagCount() > index) {
        dagEdit_->Clear();
        operation_->removeDag(index);
    }
    updateIndex();
    if (index > 0) {
        index--;
    }
    dagIndex_->SetSelection(index);
    updateDAG();
}
References Operation::dagCount(), dagEdit_, dagIndex_, operation_, Operation::removeDag(), updateDAG(), and updateIndex().
onNewDAG()
void OperationDAGDialog::onNewDAG (wxCommandEvent & event) private
Handles the event when New button is pushed.
Definition at line 479 of file OperationDAGDialog.cc.
{
    int index = operation_->dagCount();
    dagEdit_->Clear();
    dagIndex_->SetSelection(index);
    FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
    FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
    FindWindow(ID_DELETE_DAG_BUTTON)->Disable();
    FindWindow(ID_NEW_DAG_BUTTON)->Disable();
    dagImageStaticBoxSizer_->Show(false);
}
References Operation::dagCount(), dagEdit_, dagImageStaticBoxSizer_, dagIndex_, ID_DELETE_DAG_BUTTON, ID_NEW_DAG_BUTTON, ID_SAVE_DAG_BUTTON, ID_UNDO_DAG_BUTTON, and operation_.
onOK()
void OperationDAGDialog::onOK (wxCommandEvent & event) private
Handles the event when OK button is pushed.
Definition at line 371 of file OperationDAGDialog.cc.
{
    for (int i = 0; i < operation_->dagCount(); i++) {
        doSaveDAG(i);
    }
    EndModal(wxID_OK);
}
References Operation::dagCount(), doSaveDAG(), and operation_.
onSaveDAG()
void OperationDAGDialog::onSaveDAG (wxCommandEvent & event) private
Handles the event when Save button is pushed.
Definition at line 421 of file OperationDAGDialog.cc.
{
    if(operation_ == NULL) {
        return;
    }
    int index = dagIndex_->GetSelection();
    doSaveDAG(index);
    FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
    FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
    FindWindow(ID_DELETE_DAG_BUTTON)->Enable();
}
References dagIndex_, doSaveDAG(), ID_DELETE_DAG_BUTTON, ID_SAVE_DAG_BUTTON, ID_UNDO_DAG_BUTTON, and operation_.
onUndoDAG()
void OperationDAGDialog::onUndoDAG (wxCommandEvent & event) private
Handles the event when Undo button is pushed.
Definition at line 439 of file OperationDAGDialog.cc.
{
    std::iostream dagCode(dagEdit_);
    int index = dagIndex_->GetSelection();
    if (operation_->dagCount() == index) { // new operation
        dagEdit_->Clear();
        FindWindow(ID_DELETE_DAG_BUTTON)->Disable();
    } else {
        updateDAG();
        FindWindow(ID_DELETE_DAG_BUTTON)->Enable();
    }
    FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
    FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
}
References Operation::dagCount(), dagEdit_, dagIndex_, ID_DELETE_DAG_BUTTON, ID_SAVE_DAG_BUTTON, ID_UNDO_DAG_BUTTON, operation_, and updateDAG().
operation()
Operation * OperationDAGDialog::operation () const
Returns operation object of dialog.
Returns
Operation object of dialog.
Definition at line 149 of file OperationDAGDialog.cc.
{
    return operation_;
}
References operation_.
operator=()
OperationDAGDialog & OperationDAGDialog::operator= (const OperationDAGDialog &) private
Assignment not allowed.
saveOperation()
ObjectState * OperationDAGDialog::saveOperation () private
setBehaviorLabel()
void OperationDAGDialog::setBehaviorLabel () private
setTexts()
void OperationDAGDialog::setTexts () private
Set texts to all widgets.
Definition at line 157 of file OperationDAGDialog.cc.
{
    //GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt = osedText.text(OSEdTextGenerator::TXT_PROPERTY_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    WidgetTools::setLabel(
        &osedText, FindWindow(ID_SAVE_DAG_BUTTON),
        OSEdTextGenerator::TXT_BUTTON_SAVE);
    WidgetTools::setLabel(
        &osedText, FindWindow(ID_UNDO_DAG_BUTTON),
        OSEdTextGenerator::TXT_BUTTON_UNDO);
    WidgetTools::setLabel(
        &osedText, FindWindow(ID_DELETE_DAG_BUTTON),
        OSEdTextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(
        &osedText, FindWindow(ID_NEW_DAG_BUTTON),
        OSEdTextGenerator::TXT_BUTTON_NEW);
}
References ID_DELETE_DAG_BUTTON, ID_NEW_DAG_BUTTON, ID_SAVE_DAG_BUTTON, ID_UNDO_DAG_BUTTON, OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUTTON_DELETE, OSEdTextGenerator::TXT_BUTTON_NEW, OSEdTextGenerator::TXT_BUTTON_SAVE, OSEdTextGenerator::TXT_BUTTON_UNDO, and OSEdTextGenerator::TXT_PROPERTY_DIALOG_TITLE.
TransferDataToWindow()
bool OperationDAGDialog::TransferDataToWindow () private virtual
Transfers data to window.
Returns
True if transfer is successful.
Definition at line 187 of file OperationDAGDialog.cc.
{
    return wxWindow::TransferDataToWindow();
}
updateDAG()
void OperationDAGDialog::updateDAG () private
Updates TextCtrl for DAG
Definition at line 243 of file OperationDAGDialog.cc.
{
    dagEdit_->Clear();
    // get selected item from ComboBox
    int index = dagIndex_->GetSelection();
    // check that index is legal
    if (operation_ != NULL && index < operation_->dagCount()) {
        std::string code = operation_->dagCode(index);
        std::ostream dagCode(dagEdit_);
        dagCode << code;
        dagCode.flush();
        FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
        FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
        FindWindow(ID_DELETE_DAG_BUTTON)->Enable();
        FindWindow(ID_NEW_DAG_BUTTON)->Enable();
        OperationDAG& currentDAG = operation_->dag(index);
        if (operation_->dagError(index) != "") {
            wxString message(
                wxString::FromAscii(
                    operation_->dagError(index).c_str()));
            wxString caption(wxString::FromAscii("Warning"));
            wxMessageBox(message, caption);
            dagImageStaticBoxSizer_->Show(false);
            Layout();
        }
        std::string temp = FileSystem::createTempDirectory();
        std::string pngDag = temp + "/dag.png";
        std::string dotDag = temp + "/dag.dot";
        if( !dotInstalled_ )
        {
            // cannot show DAG without dot
            dagImageStaticBoxSizer_->Show(false);
            Layout();
            return;
        }
        if (currentDAG.isNull() == true) { // compile error
            std::string errText = operation_->dagError(index);
            // strip carriage returns from errText
            while (true) {
                const int pos = errText.find('\n');
                if (pos == -1) {
                    break;
                }
                errText.replace(pos, 1,"\\n");
            }
            // command to generate error message
            std::string dotCmd =
                std::string("echo 'digraph G {n140545368 [label=\"") + errText +
                "\", shape=plaintext, fontsize=12]; }' | dot -Tpng > " + pngDag;
            if (system(dotCmd.c_str()) != 0) {
                debugLog("Error executing dot.");
            }
            delete dotImage_;
            dotImage_ = new wxBitmap(100,100);
            wxString wxTemp(wxString::FromAscii(pngDag.c_str()));
            dotImage_->LoadFile(wxTemp, wxBITMAP_TYPE_PNG);
            dagStaticBitmap_->SetBitmap(*dotImage_);
            unsigned int width = dotImage_->GetWidth();
            unsigned int height = dotImage_->GetHeight();
            // calculate virtual area and rounding the result up
            width = static_cast<unsigned int>(float(width) / 20 + 0.5);
            height = static_cast<unsigned int>(float(height) / 20 + 0.5);
            dagWindow_->SetSize(-1, -1, width, height);
            dagWindow_->SetScrollbars(20, 20, -1, -1);
            dagImageStaticBoxSizer_->Show(true);
        } else {
            // generate dot
            currentDAG.writeToDotFile(dotDag);
            // generate png from dot
            std::string dotCmd = "dot -Tpng " + dotDag + " > " + pngDag;
            if (system(dotCmd.c_str()) != 0) {
                debugLog("Error executing dot.");
            }
            delete dotImage_;
            dotImage_ = new wxBitmap(300,100);
            wxString wxTemp(wxString::FromAscii(pngDag.c_str()));
            dotImage_->LoadFile(wxTemp, wxBITMAP_TYPE_PNG);
            dagStaticBitmap_->SetBitmap(*dotImage_);
            dagImageStaticBoxSizer_->Show(true);
            unsigned int width = dotImage_->GetWidth();
            unsigned int height = dotImage_->GetHeight();
            // calculate virtual area and rounding the result up
            width = static_cast<unsigned int>(float(width) / 20 + 0.5);
            height = static_cast<unsigned int>(float(height) / 20 + 0.5);
            dagWindow_->SetSize(50, 50);
            dagWindow_->SetScrollbars(20, 20, width, height);
        }
        FileSystem::removeFileOrDirectory(temp);
    } else {
        // new dag => do not update, just disable the buttons
        FindWindow(ID_UNDO_DAG_BUTTON)->Disable();
        FindWindow(ID_SAVE_DAG_BUTTON)->Disable();
        FindWindow(ID_DELETE_DAG_BUTTON)->Disable();
        FindWindow(ID_NEW_DAG_BUTTON)->Disable();
        dagImageStaticBoxSizer_->Show(false);
    }
    Layout();
}
References FileSystem::createTempDirectory(), Operation::dag(), Operation::dagCode(), dagEdit_, Operation::dagError(), dagImageStaticBoxSizer_, dagIndex_, dagStaticBitmap_, dagWindow_, debugLog, dotImage_, dotInstalled_, ID_DELETE_DAG_BUTTON, ID_NEW_DAG_BUTTON, ID_SAVE_DAG_BUTTON, ID_UNDO_DAG_BUTTON, OperationDAG::isNull(), operation_, FileSystem::removeFileOrDirectory(), TCEString::replace(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Referenced by doSaveDAG(), onComboBoxChange(), onDeleteDAG(), and onUndoDAG().
updateIndex()
void OperationDAGDialog::updateIndex () private
Updates the DAG list.
Definition at line 195 of file OperationDAGDialog.cc.
{
    dagIndex_->Clear();
    if (operation_ == NULL) {
        return;
    }
    if (operation_->dagCount() > 0) {
        for (int i = 0; i < operation_->dagCount(); i++) {
            wxString oper = WxConversion::toWxString(i+1);
            dagIndex_->Append(oper);
        }
    }
    // last item is "New Dag"-option
    wxString oper = wxT("New DAG");
    dagIndex_->Append(oper);
    dagIndex_->SetSelection(0);
}
References Operation::dagCount(), dagIndex_, operation_, and WxConversion::toWxString().
Referenced by doSaveDAG(), and onDeleteDAG().
Member Data Documentation
dagEdit_
wxTextCtrl* OperationDAGDialog::dagEdit_ private
Definition at line 110 of file OperationDAGDialog.hh.
Referenced by doSaveDAG(), onDeleteDAG(), onNewDAG(), onUndoDAG(), and updateDAG().
dagImageStaticBoxSizer_
wxStaticBoxSizer* OperationDAGDialog::dagImageStaticBoxSizer_ private
Definition at line 123 of file OperationDAGDialog.hh.
Referenced by createContents(), hasDot(), onNewDAG(), and updateDAG().
dagIndex_
wxChoice* OperationDAGDialog::dagIndex_ private
Definition at line 116 of file OperationDAGDialog.hh.
Referenced by doSaveDAG(), onDeleteDAG(), onNewDAG(), onSaveDAG(), onUndoDAG(), updateDAG(), and updateIndex().
dagStaticBitmap_
wxStaticBitmap* OperationDAGDialog::dagStaticBitmap_ private
Definition at line 122 of file OperationDAGDialog.hh.
Referenced by createContents(), and updateDAG().
dagWindow_
wxScrolledWindow* OperationDAGDialog::dagWindow_ private
Definition at line 126 of file OperationDAGDialog.hh.
Referenced by createContents(), and updateDAG().
dotImage_
wxBitmap* OperationDAGDialog::dotImage_ private
Definition at line 119 of file OperationDAGDialog.hh.
Referenced by createContents(), and updateDAG().
dotInstalled_
bool OperationDAGDialog::dotInstalled_ private
Definition at line 128 of file OperationDAGDialog.hh.
Referenced by updateDAG().
editDescription_
wxTextCtrl* OperationDAGDialog::editDescription_ private
Definition at line 113 of file OperationDAGDialog.hh.
operation_
Operation* OperationDAGDialog::operation_ private
Operation to be created or to be modified.
Definition at line 105 of file OperationDAGDialog.hh.
Referenced by doSaveDAG(), onCancel(), onDeleteDAG(), onNewDAG(), onOK(), onSaveDAG(), onUndoDAG(), operation(), updateDAG(), and updateIndex().
orig_
ObjectState* OperationDAGDialog::orig_ private
Original operation's ObjectState tree.
Definition at line 107 of file OperationDAGDialog.hh.
Referenced by onCancel().
The documentation for this class was generated from the following files:
OperationDAGDialog.hh
OperationDAGDialog.cc