OpenASIP: HDLPort Class Reference
HDLPort Class Reference
#include <HDLPort.hh>
Public Member Functions
HDLPort (const TCEString name, const TCEString &widthFormula, ProGe::DataType type, ProGe::Direction direction, bool needsInversion)
HDLPort (const TCEString name, const TCEString &widthFormula, ProGe::DataType type, ProGe::Direction direction, bool needsInversion, int width)
HDLPort (const HDLPort &old)
HDLPort (const ProGe::NetlistPort &port)
TCEString name () const
TCEString widthFormula () const
void updateWidthFormula (const TCEString &widthFormula)
bool hasRealWidth () const
int realWidth () const
ProGe::Direction direction () const
ProGe::DataType type () const
bool needsInversion () const
ProGe::NetlistPort * convertToNetlistPort (ProGe::NetlistBlock &block) const
void setToStatic (ProGe::StaticSignal value)
bool hasStaticValue () const
ProGe::StaticSignal staticValue () const
Private Attributes
TCEString name_
TCEString widthFormula_
ProGe::DataType type_
ProGe::Direction direction_
bool needsInversion_
bool hasWidth_
int width_
bool hasStaticValue_
ProGe::StaticSignal staticValue_
Detailed Description
Represents a HDL port which is on higher abstraction level than NetlistPort
Definition at line 48 of file PlatformIntegrator/HDLPort.hh.
Constructor & Destructor Documentation
HDLPort() [1/4]
HDLPort::HDLPort (const TCEString name, const TCEString & widthFormula, ProGe::DataType type, ProGe::Direction direction, bool needsInversion)
Definition at line 38 of file HDLPort.cc.
    : name_(name),
      widthFormula_(widthFormula),
      type_(type),
      direction_(direction),
      needsInversion_(needsInversion),
      hasWidth_(false),
      width_(0),
      hasStaticValue_(false),
      staticValue_(ProGe::StaticSignal::GND) {}
HDLPort() [2/4]
HDLPort::HDLPort (const TCEString name, const TCEString & widthFormula, ProGe::DataType type, ProGe::Direction direction, bool needsInversion, int width)
Definition at line 51 of file HDLPort.cc.
    : name_(name),
      widthFormula_(widthFormula),
      type_(type),
      direction_(direction),
      needsInversion_(needsInversion),
      hasWidth_(true),
      width_(width),
      hasStaticValue_(false),
      staticValue_(ProGe::StaticSignal::GND) {}
HDLPort() [3/4]
HDLPort::HDLPort (const HDLPort & old)
Definition at line 64 of file HDLPort.cc.
                                  :
    name_(old.name_), widthFormula_(old.widthFormula_), type_(old.type_),
    direction_(old.direction_), needsInversion_(old.needsInversion_),
    hasWidth_(old.hasWidth_), width_(old.width_),
    hasStaticValue_(old.hasStaticValue_), staticValue_(old.staticValue_) {
}
HDLPort() [4/4]
HDLPort::HDLPort (const ProGe::NetlistPort & port)
Definition at line 71 of file HDLPort.cc.
    : name_(port.name()),
      widthFormula_(port.widthFormula()),
      type_(port.dataType()),
      direction_(port.direction()),
      needsInversion_(false),
      hasWidth_(port.realWidthAvailable()),
      width_(0),
      hasStaticValue_(false),
      staticValue_(ProGe::StaticSignal::GND) {
    if (port.realWidthAvailable()) {
        width_ = port.realWidth();
    }
}
References ProGe::NetlistPort::realWidth(), ProGe::NetlistPort::realWidthAvailable(), and width_.
Member Function Documentation
convertToNetlistPort()
ProGe::NetlistPort * HDLPort::convertToNetlistPort (ProGe::NetlistBlock & block) const
Definition at line 127 of file HDLPort.cc.
{
    NetlistPort* port;
    if (hasWidth_) {
        port = new NetlistPort(name_, widthFormula_, width_, type_,
                               direction_, block);
    } else {
        port = new NetlistPort(name_, widthFormula_, type_, direction_,
                               block);
    }
    if (hasStaticValue_) {
        port->setToStatic(staticValue_);
    }
    return port;
}
References direction_, hasStaticValue_, hasWidth_, name_, ProGe::NetlistPort::setToStatic(), staticValue_, type_, width_, and widthFormula_.
Referenced by Stratix2SramGenerator::addMemory(), and MemoryGenerator::createMemoryNetlistBlock().
direction()
ProGe::Direction HDLPort::direction () const
Definition at line 112 of file HDLPort.cc.
{
    return direction_;
}
References direction_.
Referenced by IPXactModel::addSignalObject().
hasRealWidth()
bool HDLPort::hasRealWidth () const
Definition at line 102 of file HDLPort.cc.
{
    return hasWidth_;
}
References hasWidth_.
Referenced by IPXactModel::addSignalObject().
hasStaticValue()
bool HDLPort::hasStaticValue () const
Definition at line 153 of file HDLPort.cc.
{
    return hasStaticValue_;
}
References hasStaticValue_.
Referenced by MemoryGenerator::createMemoryNetlistBlock().
name()
TCEString HDLPort::name () const
Definition at line 87 of file HDLPort.cc.
                    {
    return name_;
}
References name_.
Referenced by MemoryGenerator::addMemory(), XilinxBlockRamGenerator::addMemory(), IPXactModel::addSignalObject(), and MemoryGenerator::portKeyName().
needsInversion()
bool HDLPort::needsInversion () const
Definition at line 122 of file HDLPort.cc.
{
    return needsInversion_;
}
References needsInversion_.
Referenced by MemoryGenerator::addMemory(), Stratix2SramGenerator::addMemory(), and XilinxBlockRamGenerator::addMemory().
realWidth()
int HDLPort::realWidth () const
Definition at line 107 of file HDLPort.cc.
{
    return width_;
}
References width_.
Referenced by IPXactModel::addSignalObject().
setToStatic()
void HDLPort::setToStatic (ProGe::StaticSignal value)
Definition at line 145 of file HDLPort.cc.
{
    hasStaticValue_ = true;
    staticValue_ = value;
}
References hasStaticValue_, and staticValue_.
Referenced by AlteraOnchipRomGenerator::AlteraOnchipRomGenerator(), and VhdlRomGenerator::VhdlRomGenerator().
staticValue()
ProGe::StaticSignal HDLPort::staticValue () const
Definition at line 160 of file HDLPort.cc.
{
    return staticValue_;
}
References staticValue_.
type()
ProGe::DataType HDLPort::type () const
Definition at line 117 of file HDLPort.cc.
                    {
    return type_;
}
References type_.
Referenced by IPXactModel::addSignalObject().
updateWidthFormula()
void HDLPort::updateWidthFormula (const TCEString & widthFormula)
Definition at line 97 of file HDLPort.cc.
{
    widthFormula_ = widthFormula;
}
References widthFormula(), and widthFormula_.
widthFormula()
TCEString HDLPort::widthFormula () const
Definition at line 92 of file HDLPort.cc.
{
    return widthFormula_;
}
References widthFormula_.
Referenced by updateWidthFormula().
Member Data Documentation
direction_
ProGe::Direction HDLPort::direction_ private
Definition at line 99 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), and direction().
hasStaticValue_
bool HDLPort::hasStaticValue_ private
Definition at line 103 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), hasStaticValue(), and setToStatic().
hasWidth_
bool HDLPort::hasWidth_ private
Definition at line 101 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), and hasRealWidth().
name_
TCEString HDLPort::name_ private
Definition at line 96 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), and name().
needsInversion_
bool HDLPort::needsInversion_ private
Definition at line 100 of file PlatformIntegrator/HDLPort.hh.
Referenced by needsInversion().
staticValue_
ProGe::StaticSignal HDLPort::staticValue_ private
Definition at line 104 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), setToStatic(), and staticValue().
type_
ProGe::DataType HDLPort::type_ private
Definition at line 98 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), and type().
width_
int HDLPort::width_ private
Definition at line 102 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), HDLPort(), and realWidth().
widthFormula_
TCEString HDLPort::widthFormula_ private
Definition at line 97 of file PlatformIntegrator/HDLPort.hh.
Referenced by convertToNetlistPort(), updateWidthFormula(), and widthFormula().
The documentation for this class was generated from the following files:
PlatformIntegrator/HDLPort.hh
HDLPort.cc