OpenASIP: BFRescheduleResultsClose Class Reference
BFRescheduleResultsClose Class Reference
#include <BFRescheduleResultsClose.hh>
Public Member Functions
BFRescheduleResultsClose (BF2Scheduler &sched, ProgramOperation &po)
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
ProgramOperation & po_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 48 of file BFRescheduleResultsClose.hh.
Constructor & Destructor Documentation
BFRescheduleResultsClose()
BFRescheduleResultsClose::BFRescheduleResultsClose (BF2Scheduler & sched, ProgramOperation & po) inline
Definition at line 51 of file BFRescheduleResultsClose.hh.
                                                   :
        BFOptimization(sched), po_(po) {}
Member Function Documentation
operator()()
bool BFRescheduleResultsClose::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 43 of file BFRescheduleResultsClose.cc.
{
    int lastNonReg = 0;
    bool rescheduled = false;
    for (int i= 0; i < po_.outputMoveCount(); i++) {
        MoveNode& mn = po_.outputMove(i);
        if (!mn.isScheduled()) {
//            std::cerr << "res not scheduled!" << std::endl;
            continue;
        }
        if (!mn.isDestinationVariable()) {
            lastNonReg = std::min(lastNonReg, mn.cycle());
        }
    }
    for (int i= 0; i < po_.outputMoveCount(); i++) {
        MoveNode& mn = po_.outputMove(i);
        if (!mn.isScheduled()) {
            continue;
        }
        if (mn.isDestinationVariable() && mn.cycle() > lastNonReg) {
            BFRescheduleResultClose* resched =
                new BFRescheduleResultClose(sched_, mn, lastNonReg);
            rescheduled |= runPreChild(resched);
        }
    }
    return rescheduled;
}
References MoveNode::cycle(), MoveNode::isDestinationVariable(), MoveNode::isScheduled(), ProgramOperation::outputMove(), ProgramOperation::outputMoveCount(), po_, Reversible::runPreChild(), and BFOptimization::sched_.
Member Data Documentation
po_
ProgramOperation& BFRescheduleResultsClose::po_ private
Definition at line 57 of file BFRescheduleResultsClose.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFRescheduleResultsClose.hh
BFRescheduleResultsClose.cc