OpenASIP: UndoCmd Class Reference
UndoCmd Class Reference
#include <UndoCmd.hh>
Public Member Functions
UndoCmd ()
virtual ~UndoCmd ()
virtual bool Do ()
virtual int id () const
virtual UndoCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for undoing modifications to the machine.
Definition at line 41 of file UndoCmd.hh.
Constructor & Destructor Documentation
UndoCmd()
UndoCmd::UndoCmd ()
The Constructor.
Definition at line 44 of file UndoCmd.cc.
                :
    EditorCommand(ProDeConstants::CMD_NAME_UNDO) {
}
Referenced by create().
~UndoCmd()
UndoCmd::~UndoCmd () virtual
The Destructor.
Definition at line 53 of file UndoCmd.cc.
{}
Member Function Documentation
create()
UndoCmd * UndoCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 85 of file UndoCmd.cc.
                      {
    return new UndoCmd();
}
References UndoCmd().
Do()
bool UndoCmd::Do () virtual
Executes the command.
Returns
Always false.
Implements GUICommand.
Definition at line 62 of file UndoCmd.cc.
            {
    dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel()->undo();
    return false;
}
References EditorCommand::view().
icon()
string UndoCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 97 of file UndoCmd.cc.
                    {
    return ProDeConstants::CMD_ICON_UNDO;
}
References ProDeConstants::CMD_ICON_UNDO.
id()
int UndoCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 74 of file UndoCmd.cc.
                  {
    return ProDeConstants::COMMAND_UNDO;
}
References ProDeConstants::COMMAND_UNDO.
isEnabled()
bool UndoCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when the model's undo stack is not empty.
Returns
True, if the model's undo stack is not empty.
Reimplemented from EditorCommand.
Definition at line 110 of file UndoCmd.cc.
                   {
    wxDocManager* manager = wxGetApp().docManager();
    wxView* view = manager->GetCurrentView();
    if (view == NULL) {
        return false;
    }
    Model* model =
        dynamic_cast<MDFDocument*>(view->GetDocument())->getModel();
    if (model != NULL && model->canUndo()) {
        return true;
    }
    return false;
}
References Model::canUndo(), and EditorCommand::view().
The documentation for this class was generated from the following files:
UndoCmd.hh
UndoCmd.cc