OpenASIP: UntilCommand Class Reference
UntilCommand Class Reference
#include <UntilCommand.hh>
Public Member Functions
UntilCommand ()
virtual ~UntilCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "until" command of the Simulator Control Language.
Definition at line 47 of file UntilCommand.hh.
Constructor & Destructor Documentation
UntilCommand()
UntilCommand::UntilCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 52 of file UntilCommand.cc.
                           : SimControlLanguageCommand("until") {
}
~UntilCommand()
UntilCommand::~UntilCommand () virtual
Destructor.
Does nothing.
Definition at line 60 of file UntilCommand.cc.
{
}
Member Function Documentation
execute()
bool UntilCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "until" command.
Run until the program location specified by arg is reached and stop before executing the instruction at specified address. Any valid argument that applies to command break is also a valid argument for until.
Parameters
arguments The count of steps (default is one step).
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 75 of file UntilCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 0, 1)) {
        return false;
    }
    if (!checkSimulationInitialized() && !checkSimulationStopped()) {
        return false;
    }
    try {
        const std::string argument =
            ((argumentCount == 1)?(arguments[1].stringValue()):(""));
        const int instructionAddress =
            parseInstructionAddressExpression(argument);
        simulatorFrontend().runUntil(instructionAddress);
        printNextInstruction();
        printSimulationTime();
    } catch (const IllegalParameters&) {
        return false;
    }
    return true;
}
References CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimControlLanguageCommand::printNextInstruction(), SimControlLanguageCommand::printSimulationTime(), SimulatorFrontend::runUntil(), and SimControlLanguageCommand::simulatorFrontend().
helpText()
std::string UntilCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 108 of file UntilCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_UNTIL).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_UNTIL.
The documentation for this class was generated from the following files:
UntilCommand.hh
UntilCommand.cc