OpenASIP: Figure Class Reference
Figure Class Reference
#include <Figure.hh>
Public Member Functions
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
Protected Attributes
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Private Member Functions
Figure & operator= (Figure &old)
Assignment not allowed.
Figure (Figure &old)
Copying not allowed.
Detailed Description
Abstract base class for classes that represent the visuals of a machine block.
Can draw itself on the given device context. May contain other Figures as children, and in that case, knows also how to layout them.
Definition at line 50 of file Figure.hh.
Constructor & Destructor Documentation
Figure() [1/2]
Figure::Figure ()
The Constructor.
Definition at line 44 of file Figure.cc.
              :
    location_(wxPoint(0,0)), size_(wxSize(0,0)), minSize_(wxSize(0,0)),
    xSet_(false), laidOut_(false), drawn_(false), highlight_(*wxRED),
    highlighted_(false), options_(NULL) {
}
~Figure()
Figure::~Figure () virtual
The Destructor.
Definition at line 53 of file Figure.cc.
                {
}
Figure() [2/2]
Figure::Figure (Figure & old) private
Copying not allowed.
Member Function Documentation
addChild()
virtual void Figure::addChild (Figure * child) virtual
Reimplemented in ContentsFigure.
Referenced by EditPart::addChild(), and ContentsFigure::addChild().
bounds()
virtual wxRect Figure::bounds () const virtual
Reimplemented in SelectionFigure.
Referenced by SelectionFigure::bounds(), SocketBusConnFigure::drawConnection(), SocketPortConnFigure::drawConnection(), MoveFigure::drawSelf(), SelectionFigure::drawSelf(), MachineCanvas::getFigureSize(), ContentsFigure::layoutChildren(), UnitFigure::layoutChildren(), BusContainerFigure::layoutSelf(), ContentsFigure::layoutSelf(), SocketContainerFigure::layoutSelf(), UnitContainerFigure::layoutSelf(), SocketBusConnFigure::layoutSelf(), SocketPortConnFigure::layoutSelf(), MachineCanvas::OnDraw(), MachineCanvas::refreshToolFigure(), and setBounds().
child()
Figure * Figure::child (int index) const
Referenced by UnitFigure::layoutChildren().
childCount()
int Figure::childCount () const
Referenced by UnitFigure::layoutChildren(), and BusFigure::virtualBounds().
clearHighlight()
void Figure::clearHighlight ()
Clears highlighting of the figure.
The highlight is cleared next time the figure is drawn. This function has no effect if the figure isn't highlighted.
Definition at line 165 of file Figure.cc.
                       {
    highlighted_ = false;
    // Clear highlighting of child figures.
    vector<Figure*>::iterator i = children_.begin();
    for (; i != children_.end(); i++) {
    (*i)->clearHighlight();
    }
}
References children_, and highlighted_.
Referenced by MachineCanvas::clearHighlights().
clearXSetFlag()
void Figure::clearXSetFlag ()
draw()
void Figure::draw (wxDC * dc) virtual
Draws the Figure and its children on the given device context.
Parameters
dc The device context to draw the Figure on.
Note
The Figure must be laid out before drawing!
Reimplemented in ContentsFigure.
Definition at line 138 of file Figure.cc.
                     {
    assert(laidOut_ == true);
    drawSelf(dc);
    drawChildren(dc);
    drawn_ = true;
}
References assert, drawChildren(), drawn_, drawSelf(), and laidOut_.
Referenced by ContentsFigure::draw(), and MachineCanvas::OnDraw().
drawChildren()
void Figure::drawChildren (wxDC * dc) protected
Draws the Figure's children.
Parameters
dc The device context to draw the children on.
Definition at line 151 of file Figure.cc.
{
    vector<Figure*>::iterator i = children_.begin();
    for (; i != children_.end(); i++) {
    (*i)->draw(dc);
    }
}
References children_.
Referenced by draw().
drawSelf()
virtual void Figure::drawSelf (wxDC * dc) protected virtual
Reimplemented in BusChainFigure, BusFigure, UnitFigure, BidirBridgeFigure, BridgeFigure, InputSocketFigure, MoveFigure, OutputSocketFigure, SegmentFigure, SelectionFigure, SocketBusConnFigure, SocketPortConnFigure, TriggeringPortFigure, UnitPortFigure, UnknownSocketFigure, SocketBusConnToolFigure, and SocketPortConnToolFigure.
Referenced by draw().
highlight()
void Figure::highlight (const wxColour & colour)
Highlights the figure with given colour.
The figure is highlighted next time it's drawn.
Parameters
colour Highlight colour.
Definition at line 182 of file Figure.cc.
{
    highlight_ = colour;
    highlighted_ = true;
    // Highlight child figures.
    vector<Figure*>::iterator i = children_.begin();
    for (; i != children_.end(); i++) {
    (*i)->highlight(colour);
    }
}
References children_, highlight_, and highlighted_.
Referenced by MachineCanvas::highlight().
layout()
void Figure::layout (wxDC * dc) virtual
Lays out the Figure and its children.
Parameters
dc The device context to layout children on.
Reimplemented in UnitFigure.
Definition at line 109 of file Figure.cc.
                       {
    layoutChildren(dc);
    layoutSelf(dc);
    laidOut_ = true;
}
References laidOut_, layoutChildren(), and layoutSelf().
Referenced by ContentsFigure::layoutChildren(), MachineCanvas::OnDraw(), and MachineCanvas::refreshToolFigure().
layoutChildren()
void Figure::layoutChildren (wxDC * dc) protected virtual
Empty default implementation that can be used if no specific laying out needs to be done or the Figure doesn't have children.
Tells all children to layout themselves.
Parameters
dc Device context.
Reimplemented in BidirBridgeFigure, BusChainFigure, BusContainerFigure, BusFigure, ContentsFigure, SocketContainerFigure, UnitContainerFigure, UnitFigure, and UnitPortFigure.
Definition at line 124 of file Figure.cc.
{
    vector<Figure*>::iterator i = children_.begin();
    for (; i != children_.end(); i++) {
    (*i)->layout(dc);
    }
}
References children_.
Referenced by layout().
layoutSelf()
virtual void Figure::layoutSelf (wxDC *) protected virtual
Reimplemented in BusContainerFigure, BusFigure, ContentsFigure, SocketContainerFigure, UnitContainerFigure, UnitFigure, SocketBusConnFigure, and SocketPortConnFigure.
Referenced by layout().
location()
wxPoint Figure::location () const
Referenced by SocketBusConnFigure::drawConnection(), SocketPortConnFigure::drawConnection(), MoveFigure::drawSelf(), UnitPortFigure::layoutChildren(), SocketContainerFigure::layoutSelf(), UnitContainerFigure::layoutSelf(), SocketBusConnFigure::layoutSelf(), and SocketPortConnFigure::layoutSelf().
operator=()
Figure & Figure::operator= (Figure & old) private
Assignment not allowed.
options()
MachineCanvasOptions * Figure::options ()
Returns the options object used by this figure and it's children.
Returns
Current figure options.
Definition at line 199 of file Figure.cc.
                {
    return options_;
}
References options_.
Referenced by UnitFigure::drawSelf(), UnitFigure::layoutSelf(), and setOptions().
setBounds()
void Figure::setBounds (wxSize bounds)
Sets the size of the Figure's bounding rectangle.
Parameters
bounds New size.
Definition at line 62 of file Figure.cc.
{
    if (bounds.GetHeight() < size_.GetHeight()) {
    size_.SetHeight(minSize_.GetHeight());
    } else {
    size_.SetHeight(bounds.GetHeight());
    }
    if (bounds.GetWidth() < size_.GetWidth()) {
    size_.SetWidth(minSize_.GetWidth());
    } else {
    size_.SetWidth(bounds.GetWidth());
    }
}
References bounds(), minSize_, and size_.
setHeight()
void Figure::setHeight (int height)
Sets the height of the Figure.
Parameters
height New height.
Definition at line 95 of file Figure.cc.
{
    if (height < minSize_.GetHeight()) {
    size_.SetHeight(minSize_.GetHeight());
    } else {
    size_.SetHeight(height);
    }
}
References minSize_, and size_.
Referenced by ContentsFigure::layoutChildren(), SocketBusConnFigure::layoutSelf(), and SocketPortConnFigure::layoutSelf().
setLocation()
void Figure::setLocation (wxPoint point)
Referenced by BusContainerFigure::layoutChildren(), ContentsFigure::layoutChildren(), UnitContainerFigure::layoutChildren(), SocketBusConnFigure::layoutSelf(), and SocketPortConnFigure::layoutSelf().
setOptions()
void Figure::setOptions (MachineCanvasOptions * options)
Sets the options object used for setting drawing options.
Options are set recursively for figure children.
Parameters
options Options to set.
Definition at line 212 of file Figure.cc.
{
    vector<Figure*>::iterator i = children_.begin();
    for (; i != children_.end(); i++) {
    (*i)->setOptions(options);
    }
    options_ = options;
}
References children_, options(), and options_.
Referenced by MachineCanvas::updateMachine().
setPreferredX()
void Figure::setPreferredX (int x)
setWidth()
void Figure::setWidth (int width)
Sets the width of the Figure.
Parameters
width New width.
Definition at line 81 of file Figure.cc.
{
    if (width < minSize_.GetWidth()) {
    size_.SetWidth(minSize_.GetWidth());
    } else {
    size_.SetWidth(width);
    }
}
References minSize_, and size_.
Referenced by ContentsFigure::layoutChildren(), SocketBusConnFigure::layoutSelf(), and SocketPortConnFigure::layoutSelf().
setX()
void Figure::setX (int x)
Referenced by BidirBridgeFigure::layoutChildren(), and SocketContainerFigure::layoutChildren().
setY()
void Figure::setY (int y)
virtualBounds()
virtual wxRect Figure::virtualBounds () const virtual
Reimplemented in BusFigure.
Referenced by EditPart::find(), EditPart::findInRange(), and EditPart::findNearest().
xSet()
bool Figure::xSet () const
Referenced by UnitContainerFigure::layoutChildren(), and UnitPortFigure::layoutChildren().
Member Data Documentation
children_
std::vector<Figure*> Figure::children_ protected
Figure's children.
Definition at line 90 of file Figure.hh.
Referenced by clearHighlight(), drawChildren(), BusFigure::drawSelf(), highlight(), BidirBridgeFigure::layoutChildren(), BusChainFigure::layoutChildren(), BusContainerFigure::layoutChildren(), BusFigure::layoutChildren(), layoutChildren(), SocketContainerFigure::layoutChildren(), UnitContainerFigure::layoutChildren(), UnitFigure::layoutChildren(), UnitPortFigure::layoutChildren(), BusContainerFigure::layoutSelf(), BusFigure::layoutSelf(), SocketContainerFigure::layoutSelf(), UnitContainerFigure::layoutSelf(), UnitFigure::layoutSelf(), and setOptions().
drawn_
bool Figure::drawn_ protected
Tells whether the Figure and its children have been drawn or not.
Definition at line 97 of file Figure.hh.
Referenced by draw().
highlight_
wxColour Figure::highlight_ protected
Highlight colour.
Definition at line 99 of file Figure.hh.
Referenced by UnitFigure::drawSelf(), InputSocketFigure::drawSelf(), OutputSocketFigure::drawSelf(), SegmentFigure::drawSelf(), TriggeringPortFigure::drawSelf(), UnitPortFigure::drawSelf(), and highlight().
highlighted_
bool Figure::highlighted_ protected
Tells if the figure is highlighted.
Definition at line 101 of file Figure.hh.
Referenced by clearHighlight(), UnitFigure::drawSelf(), InputSocketFigure::drawSelf(), OutputSocketFigure::drawSelf(), SegmentFigure::drawSelf(), TriggeringPortFigure::drawSelf(), UnitPortFigure::drawSelf(), and highlight().
laidOut_
bool Figure::laidOut_ protected
Tells whether the Figure and its children have been laid out or not.
Definition at line 95 of file Figure.hh.
Referenced by draw(), UnitFigure::layout(), layout(), and MoveFigure::MoveFigure().
location_
wxPoint Figure::location_ protected
Top-left location of the Figure's bounding rectangle.
Definition at line 84 of file Figure.hh.
Referenced by BusChainFigure::drawSelf(), BusFigure::drawSelf(), UnitFigure::drawSelf(), BridgeFigure::drawSelf(), InputSocketFigure::drawSelf(), OutputSocketFigure::drawSelf(), SegmentFigure::drawSelf(), TriggeringPortFigure::drawSelf(), UnitPortFigure::drawSelf(), UnknownSocketFigure::drawSelf(), BidirBridgeFigure::layoutChildren(), BusChainFigure::layoutChildren(), BusContainerFigure::layoutChildren(), BusFigure::layoutChildren(), ContentsFigure::layoutChildren(), SocketContainerFigure::layoutChildren(), UnitContainerFigure::layoutChildren(), UnitFigure::layoutChildren(), UnitPortFigure::layoutChildren(), SocketContainerFigure::layoutSelf(), UnitContainerFigure::layoutSelf(), and BusFigure::virtualBounds().
minSize_
wxSize Figure::minSize_ protected
Figure's minimum size.
Definition at line 88 of file Figure.hh.
Referenced by BidirBridgeFigure::BidirBridgeFigure(), BusChainFigure::BusChainFigure(), BusFigure::BusFigure(), UnitFigure::layoutSelf(), SegmentFigure::SegmentFigure(), setBounds(), setHeight(), setWidth(), and UnitFigure::UnitFigure().
options_
MachineCanvasOptions* Figure::options_ protected
Options which are used for customizing figures.
Definition at line 104 of file Figure.hh.
Referenced by options(), and setOptions().
size_
wxSize Figure::size_ protected
wxSize of the Figure's bounding rectangle.
Definition at line 86 of file Figure.hh.
Referenced by BidirBridgeFigure::BidirBridgeFigure(), BridgeFigure::BridgeFigure(), BusChainFigure::BusChainFigure(), BusFigure::BusFigure(), SocketBusConnFigure::drawConnection(), BusChainFigure::drawSelf(), BusFigure::drawSelf(), UnitFigure::drawSelf(), BridgeFigure::drawSelf(), InputSocketFigure::drawSelf(), OutputSocketFigure::drawSelf(), SegmentFigure::drawSelf(), TriggeringPortFigure::drawSelf(), UnitPortFigure::drawSelf(), UnknownSocketFigure::drawSelf(), InputSocketFigure::InputSocketFigure(), BidirBridgeFigure::layoutChildren(), BusChainFigure::layoutChildren(), BusContainerFigure::layoutChildren(), BusFigure::layoutChildren(), SocketContainerFigure::layoutChildren(), UnitFigure::layoutChildren(), UnitPortFigure::layoutChildren(), BusContainerFigure::layoutSelf(), BusFigure::layoutSelf(), ContentsFigure::layoutSelf(), SocketContainerFigure::layoutSelf(), UnitContainerFigure::layoutSelf(), UnitFigure::layoutSelf(), OutputSocketFigure::OutputSocketFigure(), SegmentFigure::SegmentFigure(), setBounds(), setHeight(), setWidth(), UnitFigure::UnitFigure(), UnitPortFigure::UnitPortFigure(), UnknownSocketFigure::UnknownSocketFigure(), and BusFigure::virtualBounds().
xSet_
bool Figure::xSet_ protected
Tells if x-coordinate has been fixed.
Definition at line 93 of file Figure.hh.
The documentation for this class was generated from the following files:
Figure.hh
Figure.cc