OpenASIP: CreateHDBCmd Class Reference
CreateHDBCmd Class Reference
#include <CreateHDBCmd.hh>
Public Member Functions
CreateHDBCmd ()
virtual ~CreateHDBCmd ()
virtual bool Do ()
virtual int id () const
virtual CreateHDBCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for creating a new HDB in HDBEditor.
Displays a file dialog for choosing filename for the new HDB.
Definition at line 43 of file CreateHDBCmd.hh.
Constructor & Destructor Documentation
CreateHDBCmd()
CreateHDBCmd::CreateHDBCmd ()
The Constructor.
Definition at line 46 of file CreateHDBCmd.cc.
                          :
    GUICommand(HDBEditorConstants::COMMAND_NAME_CREATE_HDB, NULL) {
}
Referenced by create().
~CreateHDBCmd()
CreateHDBCmd::~CreateHDBCmd () virtual
The Destructor.
Definition at line 54 of file CreateHDBCmd.cc.
{
}
Member Function Documentation
create()
CreateHDBCmd * CreateHDBCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 108 of file CreateHDBCmd.cc.
{
    return new CreateHDBCmd();
}
References CreateHDBCmd().
Do()
bool CreateHDBCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 62 of file CreateHDBCmd.cc.
                 {
    assert(parentWindow() != NULL);
    wxString wildcard = _T("Hardware Database files (*.hdb)|*.hdb");
    wildcard.Append(_T("|All files|*"));
    wxFileDialog dialog(
    parentWindow(), _T("Enter path for the new HDB"), _T(""), _T(""),
    wildcard, wxSAVE);
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    std::string command;
    std::string file = WxConversion::toString(dialog.GetPath());
    return wxGetApp().mainFrame().createHDB(file);
}
References assert, GUICommand::parentWindow(), and WxConversion::toString().
icon()
std::string CreateHDBCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 88 of file CreateHDBCmd.cc.
{
    return "filenew.png";
}
id()
int CreateHDBCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 97 of file CreateHDBCmd.cc.
                       {
    return HDBEditorConstants::COMMAND_CREATE_HDB;
}
References HDBEditorConstants::COMMAND_CREATE_HDB.
isEnabled()
bool CreateHDBCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 119 of file CreateHDBCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
CreateHDBCmd.hh
CreateHDBCmd.cc