OpenASIP: NullFUState Class Reference
NullFUState Class Reference
#include <FUState.hh>
Public Member Functions
virtual ~NullFUState ()
virtual void endClock ()
virtual void advanceClock ()
virtual void addInputPortState (PortState &port)
virtual void addOutputPortState (PortState &port)
virtual void addOperationExecutor (OperationExecutor &opExec, Operation &op)
virtual OperationExecutor * executor (Operation &op)
Public Member Functions inherited from FUState
FUState ()
FUState (const TCEString &name)
virtual ~FUState ()
void setTriggered ()
void setOperation (Operation &operation)
void setOperation (Operation &operation, OperationExecutor &executor)
bool isIdle ()
virtual void setOperationSimulator (DetailedOperationSimulator &sim)
virtual void replaceOperationExecutor (Operation &op, OperationExecutor *newExecutor)
virtual OperationContext & context ()
virtual void reset ()
this is called at (re)initialization of the simulation
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Static Public Member Functions
static NullFUState & instance ()
Private Member Functions
NullFUState ()
NullFUState (const NullFUState &)
Copying not allowed.
NullFUState & operator= (const NullFUState &)
Assignment not allowed.
Static Private Attributes
static NullFUState instance_
Unique instance of NullFUState.
Additional Inherited Members
Protected Attributes inherited from FUState
bool idle_
The idle status of the FU. The derived classes should alway set this to true when possible to avoid unnecessary advanceClock() and endClock() calls.
Detailed Description
Models non-existing FUState.
Definition at line 152 of file FUState.hh.
Constructor & Destructor Documentation
~NullFUState()
NullFUState::~NullFUState () virtual
Destructor.
Definition at line 405 of file FUState.cc.
{
}
NullFUState() [1/2]
NullFUState::NullFUState () private
Constructor.
Definition at line 399 of file FUState.cc.
{
}
NullFUState() [2/2]
NullFUState::NullFUState (const NullFUState &) private
Copying not allowed.
Member Function Documentation
addInputPortState()
void NullFUState::addInputPortState (PortState & port) virtual
Aborts the program with error message.
Reimplemented from FUState.
Definition at line 428 of file FUState.cc.
{
    Application::abortWithError("addInputPortState()");
}
addOperationExecutor()
void NullFUState::addOperationExecutor (OperationExecutor & opExec, Operation & op) virtual
Aborts the program with error message.
Reimplemented from FUState.
Definition at line 444 of file FUState.cc.
{
    Application::abortWithError("addOperationExecutor()");
}
addOutputPortState()
void NullFUState::addOutputPortState (PortState & port) virtual
Aborts the program with error message.
Reimplemented from FUState.
Definition at line 436 of file FUState.cc.
{
    Application::abortWithError("addOutputPortState()");
}
advanceClock()
void NullFUState::advanceClock () virtual
Aborts the program with error message.
Reimplemented from FUState.
Definition at line 420 of file FUState.cc.
{
    Application::abortWithError("advanceClock()");
}
endClock()
void NullFUState::endClock () virtual
Aborts the program with error message.
Reimplemented from FUState.
Definition at line 412 of file FUState.cc.
                      {
    Application::abortWithError("endClock()");
}
executor()
OperationExecutor * NullFUState::executor (Operation & op) virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from FUState.
Definition at line 454 of file FUState.cc.
{
    Application::abortWithError("executor()");
    return NULL;
}
instance()
NullFUState & NullFUState::instance () static
Returns the instance of NullFUState.
Returns
Instance of NullFUState.
Definition at line 392 of file FUState.cc.
                      {
    return instance_;
}
References instance_.
Referenced by FUTestbenchGenerator::createStimulus(), MachineState::fuState(), and NullPortState::parent().
operator=()
NullFUState & NullFUState::operator= (const NullFUState &) private
Assignment not allowed.
Member Data Documentation
instance_
NullFUState NullFUState::instance_ static private
Unique instance of NullFUState.
Definition at line 177 of file FUState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
FUState.hh
FUState.cc