OpenASIP: ConsoleWindow Class Reference
ConsoleWindow Class Reference
#include <ConsoleWindow.hh>
Classes
class ConsoleWindowInputCtrl
Public Member Functions
ConsoleWindow (ProximMainFrame *parent, wxWindowID id)
virtual ~ConsoleWindow ()
virtual void reset ()
void write (std::string text)
void clear ()
Private Types
enum { ID_INPUT = 20000 , ID_OUTPUT }
IDs for the window widgets.
Private Member Functions
virtual void onSimulatorBusy (SimulatorEvent &event)
virtual void onSimulatorDone (SimulatorEvent &event)
void createContents ()
void onSimulatorOutput (const SimulatorEvent &event)
void onError (const SimulatorEvent &event)
void textEntered (wxCommandEvent &event)
void onInputKey (wxKeyEvent &event)
Private Attributes
wxTextCtrl * outTextCtrl_
Output text control.
wxTextCtrl * inTextCtrl_
Input text control.
ProximLineReader * lineReader_
Linereader to send the user input to.
int historyIterator_
Stores the command history iterator, used for command history browsing.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Simulator console window class.
ConsoleWindow is a console with a multiline textual output window, and a singleline textual input widget. Commands are requested from the console window using SimulatorEvents.
Definition at line 51 of file ConsoleWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
IDs for the window widgets.
Enumerator
ID_INPUT
ID_OUTPUT
Definition at line 78 of file ConsoleWindow.hh.
         {
    ID_INPUT = 20000,
    ID_OUTPUT
    };
Constructor & Destructor Documentation
ConsoleWindow()
ConsoleWindow::ConsoleWindow (ProximMainFrame * parent, wxWindowID id)
The Constructor.
Parameters
parent Parent window of the console window.
id Window identifier.
Definition at line 101 of file ConsoleWindow.cc.
                   :
    ProximSimulatorWindow(parent, id),
    outTextCtrl_(NULL),
    inTextCtrl_(NULL),
    historyIterator_(-1) {
    createContents();
    lineReader_ = &wxGetApp().simulation()->lineReader();
}
References createContents(), and lineReader_.
~ConsoleWindow()
ConsoleWindow::~ConsoleWindow () virtual
The Destructor.
Definition at line 117 of file ConsoleWindow.cc.
{
}
Member Function Documentation
clear()
void ConsoleWindow::clear ()
Clears text from the output text widget.
Definition at line 269 of file ConsoleWindow.cc.
                     {
    outTextCtrl_->Clear();
}
References outTextCtrl_.
Referenced by ProximClearConsoleCmd::Do().
createContents()
void ConsoleWindow::createContents () private
Creates the window widgets.
Definition at line 164 of file ConsoleWindow.cc.
{
    // output widget
    outTextCtrl_ = new wxTextCtrl(
    this, ID_OUTPUT, _T(""), wxDefaultPosition, wxDefaultSize,
    wxTE_MULTILINE | wxTE_READONLY);
    // input widget
    inTextCtrl_ = new ConsoleWindowInputCtrl(this);
    // Sizer responsible for the window layout.
    wxFlexGridSizer* sizer = new wxFlexGridSizer(1, 0, 0);
    sizer->AddGrowableCol(0);
    sizer->AddGrowableRow(0);
    sizer->Add(outTextCtrl_, 0, wxGROW | wxALL, 5);
    sizer->Add(inTextCtrl_, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);
    SetSizer(sizer);
    sizer->SetSizeHints(this);
}
References ID_OUTPUT, inTextCtrl_, and outTextCtrl_.
Referenced by ConsoleWindow().
onError()
void ConsoleWindow::onError (const SimulatorEvent & event) private
Handles simulator error events.
The error text is printed in the console.
Parameters
event Simulator interpreter command event.
Definition at line 211 of file ConsoleWindow.cc.
{
    std::string error = event.data();
    wxTextAttr oldStyle = outTextCtrl_->GetDefaultStyle();
    outTextCtrl_->SetDefaultStyle(wxTextAttr(*wxRED));
    outTextCtrl_->AppendText(WxConversion::toWxString("\n" + error + "\n"));
    outTextCtrl_->SetDefaultStyle(oldStyle);
}
References outTextCtrl_, and WxConversion::toWxString().
onInputKey()
void ConsoleWindow::onInputKey (wxKeyEvent & event) private
Handles special keypresses in the input widget.
Parameters
event Keypress event to handle.
Definition at line 226 of file ConsoleWindow.cc.
{
    if (event.GetKeyCode() == WXK_UP) {
    // Up key. Browses the command history backward.
    historyIterator_++;
    if (historyIterator_ >= int(lineReader_->inputsInHistory())) {
        historyIterator_ = lineReader_->inputsInHistory() - 1;
        return;
    }
    } else if (event.GetKeyCode() == WXK_DOWN) {
    // Down key. Browses the command history forward.
    if (historyIterator_ < 0) {
        return;
    }
    historyIterator_--;
    } else {
    // Key with no special fucntion. The key event is skipped.
        event.Skip();
    return;
    }
    // If the command history is browsed back to top, the
    // input widget is cleared.
    if (historyIterator_ < 0) {
    inTextCtrl_->Clear();
    return;
    }
    // Command browsed from the command history is set as the input
    // widget value.
    wxString command = WxConversion::toWxString(
    lineReader_->inputHistoryEntry(historyIterator_));
    inTextCtrl_->SetValue(command);
    inTextCtrl_->SetInsertionPointEnd();
}
References historyIterator_, LineReader::inputHistoryEntry(), LineReader::inputsInHistory(), inTextCtrl_, lineReader_, and WxConversion::toWxString().
Referenced by ConsoleWindow::ConsoleWindowInputCtrl::onKeyDown().
onSimulatorBusy()
void ConsoleWindow::onSimulatorBusy (SimulatorEvent & event) private virtual
An event handler for the event of the simulator to start processing a command.
The Console window must stay enabled when the simulator is busy, so this method is overloaded to not to lock the window.
Reimplemented from ProximSimulatorWindow.
Definition at line 281 of file ConsoleWindow.cc.
{
    // Do nothing.
}
onSimulatorDone()
void ConsoleWindow::onSimulatorDone (SimulatorEvent & event) private virtual
An event handler for the event of the simulator to complete command processing.
The Console window is not locked during simulator processing, so there's no need to do anything.
Reimplemented from ProximSimulatorWindow.
Definition at line 293 of file ConsoleWindow.cc.
{
    // Do nothing.
}
onSimulatorOutput()
void ConsoleWindow::onSimulatorOutput (const SimulatorEvent & event) private
Handles simulator text output events.
The event data contains the simulator interpreter output, which is appended to the text output widget.
Parameters
event Simulator interpreter text output event.
Definition at line 195 of file ConsoleWindow.cc.
{
    // Append text to the output widget.
    std::string text = event.data();
    outTextCtrl_->AppendText(WxConversion::toWxString(text));
    outTextCtrl_->ShowPosition(outTextCtrl_->GetLastPosition());
}
References outTextCtrl_, and WxConversion::toWxString().
reset()
void ConsoleWindow::reset () virtual
Called when the simulator program, machine and memory models are deleted.
Reimplemented from ProximSimulatorWindow.
Definition at line 124 of file ConsoleWindow.cc.
                     {
    // Do nothing.
}
textEntered()
void ConsoleWindow::textEntered (wxCommandEvent & event) private
Event handler for the user input to the text input widget.
The text is passed to the linereader as input.
Definition at line 135 of file ConsoleWindow.cc.
{
    std::string command = WxConversion::toString(inTextCtrl_->GetLineText(0));
    lineReader_->input(command);
    historyIterator_ = -1;
    inTextCtrl_->Clear();
}
References historyIterator_, ProximLineReader::input(), inTextCtrl_, lineReader_, and WxConversion::toString().
write()
void ConsoleWindow::write (std::string text)
Appends text to the output window.
Parameters
text Text to append to the output window.
Definition at line 150 of file ConsoleWindow.cc.
{
    if (text == "") {
    return;
    }
    wxString output = WxConversion::toWxString(text);
    outTextCtrl_->AppendText(output);
}
References outTextCtrl_, and WxConversion::toWxString().
Member Data Documentation
historyIterator_
int ConsoleWindow::historyIterator_ private
Stores the command history iterator, used for command history browsing.
Definition at line 75 of file ConsoleWindow.hh.
Referenced by onInputKey(), and textEntered().
inTextCtrl_
wxTextCtrl* ConsoleWindow::inTextCtrl_ private
Input text control.
Definition at line 71 of file ConsoleWindow.hh.
Referenced by createContents(), onInputKey(), and textEntered().
lineReader_
ProximLineReader* ConsoleWindow::lineReader_ private
Linereader to send the user input to.
Definition at line 73 of file ConsoleWindow.hh.
Referenced by ConsoleWindow(), onInputKey(), and textEntered().
outTextCtrl_
wxTextCtrl* ConsoleWindow::outTextCtrl_ private
Output text control.
Definition at line 69 of file ConsoleWindow.hh.
Referenced by clear(), createContents(), onError(), onSimulatorOutput(), and write().
The documentation for this class was generated from the following files:
ConsoleWindow.hh
ConsoleWindow.cc