OpenASIP: HDB::FUPortImplementation Class Reference
HDB::FUPortImplementation Class Reference
#include <FUPortImplementation.hh>
Public Member Functions
FUPortImplementation (const std::string &name, const std::string &architecturePort, const std::string &widthFormula, const std::string &loadPort, const std::string &guardPort, FUImplementation &parent)
virtual ~FUPortImplementation ()
void setArchitecturePort (const std::string &name)
std::string architecturePort () const
void setGuardPort (const std::string &name)
std::string guardPort () const
void setWidthFormula (const std::string &formula)
std::string widthFormula () const
Public Member Functions inherited from HDB::PortImplementation
PortImplementation (const std::string &name, const std::string &loadPort)
virtual ~PortImplementation ()
void setName (const std::string &name)
std::string name () const
void setLoadPort (const std::string &name)
std::string loadPort () const
Private Attributes
std::string architecturePort_
Name of the corresponding port in architecture.
std::string widthFormula_
The formula for the width of the port.
std::string guardPort_
Name of the guard port.
Detailed Description
Represents an architectural port of an FU implementation in HDB.
Definition at line 46 of file FUPortImplementation.hh.
Constructor & Destructor Documentation
FUPortImplementation()
HDB::FUPortImplementation::FUPortImplementation (const std::string & name, const std::string & architecturePort, const std::string & widthFormula, const std::string & loadPort, const std::string & guardPort, FUImplementation & parent)
The constructor.
Adds the port automatically to the given FUImplementation.
Parameters
name Name of the port.
architecturePort Name of the corresponding port in architecture.
widthFormula The formula for the width of the port.
loadPort Name of the load enable port.
guardPort Name of the guard port if the port is guarded.
parent The parent FU implementation.
Definition at line 54 of file FUPortImplementation.cc.
                              :
    PortImplementation(name, loadPort),
    architecturePort_(architecturePort), widthFormula_(widthFormula),
    guardPort_(guardPort) {
    parent.addArchitecturePort(this);
}
References HDB::FUImplementation::addArchitecturePort().
~FUPortImplementation()
HDB::FUPortImplementation::~FUPortImplementation () virtual
The destructor.
Definition at line 72 of file FUPortImplementation.cc.
{
}
Member Function Documentation
architecturePort()
std::string HDB::FUPortImplementation::architecturePort () const
Returns the name of the corresponding port in the FU architecture.
Returns
The name of the port.
Definition at line 93 of file FUPortImplementation.cc.
{
    return architecturePort_;
}
References architecturePort_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), FUTestbenchGenerator::createTbInstantiation(), HDBToHtml::fuImplToHtml(), ProGe::NetlistGenerator::isParameterizable(), FUImplementationDialog::onArchPortActivation(), FUImplementationDialog::onEditArchitecturePort(), FUImplementationDialog::onOK(), and FUImplementationDialog::update().
guardPort()
std::string HDB::FUPortImplementation::guardPort () const
Returns the name of the guard port if the port is guarded.
Returns
The name of the guard port.
Definition at line 115 of file FUPortImplementation.cc.
{
    return guardPort_;
}
References guardPort_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), and HDBToHtml::fuImplToHtml().
setArchitecturePort()
void HDB::FUPortImplementation::setArchitecturePort (const std::string & name)
Sets the corresponding port in the FU architecture.
Parameters
name Name of the port.
Definition at line 82 of file FUPortImplementation.cc.
{
    architecturePort_ = name;
}
References architecturePort_, and HDB::PortImplementation::name().
setGuardPort()
void HDB::FUPortImplementation::setGuardPort (const std::string & name)
Sets the name of the guard port if the port is guarded.
Parameters
name Name of the guard port.
Definition at line 104 of file FUPortImplementation.cc.
{
    guardPort_ = name;
}
References guardPort_, and HDB::PortImplementation::name().
Referenced by FUPortImplementationDialog::onOK().
setWidthFormula()
void HDB::FUPortImplementation::setWidthFormula (const std::string & formula)
Sets the width formula of the port.
Parameters
formula The new formula.
Definition at line 126 of file FUPortImplementation.cc.
{
    widthFormula_ = formula;
}
References widthFormula_.
Referenced by FUPortImplementationDialog::onOK().
widthFormula()
std::string HDB::FUPortImplementation::widthFormula () const
Returns the formula for the width of the port.
Returns
The formula.
Definition at line 137 of file FUPortImplementation.cc.
{
    return widthFormula_;
}
References widthFormula_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), HDBToHtml::fuImplToHtml(), and ProGe::NetlistGenerator::isParameterizable().
Member Data Documentation
architecturePort_
std::string HDB::FUPortImplementation::architecturePort_ private
Name of the corresponding port in architecture.
Definition at line 66 of file FUPortImplementation.hh.
Referenced by architecturePort(), and setArchitecturePort().
guardPort_
std::string HDB::FUPortImplementation::guardPort_ private
Name of the guard port.
Definition at line 70 of file FUPortImplementation.hh.
Referenced by guardPort(), and setGuardPort().
widthFormula_
std::string HDB::FUPortImplementation::widthFormula_ private
The formula for the width of the port.
Definition at line 68 of file FUPortImplementation.hh.
Referenced by setWidthFormula(), and widthFormula().
The documentation for this class was generated from the following files:
FUPortImplementation.hh
FUPortImplementation.cc