OpenASIP: TPEF::AOutSectionReader Class Reference
TPEF::AOutSectionReader Class Reference
#include <AOutSectionReader.hh>
Public Member Functions
virtual ~AOutSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Protected Member Functions
AOutSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const =0
Does actual reading part for constructing section.
virtual Section::SectionType type () const =0
Returns type (TPEF) section which actual section reader reads.
virtual void finalize (Section *section) const
Private Member Functions
AOutSectionReader (const AOutSectionReader &)
Copying is not allowed.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Abstract base class for AOutSectionReaders.
Definition at line 45 of file AOutSectionReader.hh.
Constructor & Destructor Documentation
~AOutSectionReader()
TPEF::AOutSectionReader::~AOutSectionReader () virtual
Destructor
Definition at line 48 of file AOutSectionReader.cc.
{
}
AOutSectionReader() [1/2]
TPEF::AOutSectionReader::AOutSectionReader () protected
Constructor
Definition at line 41 of file AOutSectionReader.cc.
                                     :
    SectionReader() {
}
AOutSectionReader() [2/2]
TPEF::AOutSectionReader::AOutSectionReader (const AOutSectionReader &) private
Copying is not allowed.
Member Function Documentation
parent()
BinaryReader * TPEF::AOutSectionReader::parent () const protected virtual
Returns binary reader instance which uses AOutSectionReader classes.
Returns
Binary reader which uses AOutSectionReader classes.
Implements TPEF::SectionReader.
Definition at line 57 of file AOutSectionReader.cc.
{
    return AOutReader::instance();
}
References TPEF::AOutReader::instance().
Referenced by TPEF::AOutRelocationSectionReader::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutDataSectionReader::readData(), TPEF::AOutRelocationSectionReader::readData(), TPEF::AOutStringSectionReader::readData(), TPEF::AOutSymbolSectionReader::readData(), and TPEF::AOutTextSectionReader::readData().
The documentation for this class was generated from the following files:
AOutSectionReader.hh
AOutSectionReader.cc