OpenASIP: NullRegisterState Class Reference
NullRegisterState Class Reference
#include <RegisterState.hh>
Public Member Functions
virtual ~NullRegisterState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Static Public Member Functions
static NullRegisterState & instance ()
Private Member Functions
NullRegisterState ()
NullRegisterState (const NullRegisterState &)
Copying not allowed.
NullRegisterState & operator= (const NullRegisterState &)
Assignment not allowed.
Static Private Attributes
static NullRegisterState * instance_ = NULL
Unique instance of NullRegisterState.
Additional Inherited Members
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Models non-existing RegisterState.
Definition at line 83 of file RegisterState.hh.
Constructor & Destructor Documentation
~NullRegisterState()
NullRegisterState::~NullRegisterState () virtual
Destructor.
Definition at line 124 of file RegisterState.cc.
{
}
NullRegisterState() [1/2]
NullRegisterState::NullRegisterState () private
Constructor.
Definition at line 118 of file RegisterState.cc.
                                     : RegisterState(0) {
}
Referenced by instance().
NullRegisterState() [2/2]
NullRegisterState::NullRegisterState (const NullRegisterState &) private
Copying not allowed.
Member Function Documentation
instance()
NullRegisterState & NullRegisterState::instance () static
Returns instance of NullRegisterState.
Returns
The instance of NullRegisterState.
Definition at line 108 of file RegisterState.cc.
{
    if (instance_ == NULL) {
        instance_ = new NullRegisterState();
    }
    return *instance_;
}
References instance_, and NullRegisterState().
Referenced by NullRegisterFileState::registerState().
operator=()
NullRegisterState & NullRegisterState::operator= (const NullRegisterState &) private
Assignment not allowed.
setValue()
void NullRegisterState::setValue (const SimValue & value) virtual
Aborts the program with error message.
Reimplemented from RegisterState.
Definition at line 131 of file RegisterState.cc.
{
    Application::abortWithError("setValue()");
}
value()
const SimValue & NullRegisterState::value () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from RegisterState.
Definition at line 141 of file RegisterState.cc.
{
    Application::abortWithError("value()");
    return NullSimValue::instance();
}
References NullSimValue::instance().
Member Data Documentation
instance_
NullRegisterState * NullRegisterState::instance_ = NULL static private
Unique instance of NullRegisterState.
Definition at line 100 of file RegisterState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
RegisterState.hh
RegisterState.cc