OpenASIP: OSEdAboutDialog Class Reference
OSEdAboutDialog Class Reference
#include <OSEdAboutDialog.hh>
Public Member Functions
OSEdAboutDialog (wxWindow *parent)
virtual ~OSEdAboutDialog ()
Private Types
enum { ID_ABOUT_TEXT = 11000 , ID_LINE }
Private Member Functions
OSEdAboutDialog (const OSEdAboutDialog &)
Copying not allowed.
OSEdAboutDialog & operator= (const OSEdAboutDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void setTexts ()
Detailed Description
About dialog of the application.
Definition at line 41 of file OSEdAboutDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_ABOUT_TEXT
ID_LINE
Definition at line 58 of file OSEdAboutDialog.hh.
         {
        ID_ABOUT_TEXT = 11000,
        ID_LINE
    };
Constructor & Destructor Documentation
OSEdAboutDialog() [1/2]
OSEdAboutDialog::OSEdAboutDialog (wxWindow * parent) explicit
Constructor.
Parameters
parent Parent window.
Definition at line 56 of file OSEdAboutDialog.cc.
                                                 :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_ABOUT),
             wxDefaultSize) {
    createContents(this, true, true);
    setTexts();
}
References createContents(), and setTexts().
~OSEdAboutDialog()
OSEdAboutDialog::~OSEdAboutDialog () virtual
Destructor.
Definition at line 68 of file OSEdAboutDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_ABOUT, point);
}
References DialogPosition::DIALOG_ABOUT, and DialogPosition::setPosition().
OSEdAboutDialog() [2/2]
OSEdAboutDialog::OSEdAboutDialog (const OSEdAboutDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * OSEdAboutDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
Parameters
parent Parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true, sets the sizer as dialog contents.
Returns
The created sizer.
Definition at line 106 of file OSEdAboutDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBitmap logo;
    string dir = Environment::bitmapsDirPath(
        WxConversion::toString(OSEdConstants::APPLICATION_NAME));
    string fileName = dir + FileSystem::DIRECTORY_SEPARATOR +
        OSEdConstants::LOGO_NAME;
    logo.LoadFile(WxConversion::toWxString(fileName), wxBITMAP_TYPE_PNG);
    wxStaticBitmap* dialogLogo = new wxStaticBitmap(parent, -1, logo);
    item0->Add(dialogLogo, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item3 = new wxBoxSizer( wxVERTICAL );
    wxStaticText *item4 =
    new wxStaticText(parent, ID_ABOUT_TEXT, wxT("Operation Set Editor"),
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 =
    new wxStaticText(parent, -1, _T("OpenASIP ") + WxConversion::toWxString(VERSION),
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
     wxStaticText *item6 =
    new wxStaticText(parent, -1, OSEdConstants::OSED_COPYRIGHT,
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item7 =
    new wxStaticLine(parent, -1, wxDefaultPosition,
             wxSize(20,-1), wxLI_HORIZONTAL);
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxButton *item8 =
    new wxButton(parent, wxID_OK, wxT("&OK"), wxDefaultPosition,
             wxDefaultSize, 0);
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer) {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    return item0;
}
References OSEdConstants::APPLICATION_NAME, Environment::bitmapsDirPath(), FileSystem::DIRECTORY_SEPARATOR, ID_ABOUT_TEXT, OSEdConstants::LOGO_NAME, OSEdConstants::OSED_COPYRIGHT, WxConversion::toString(), WxConversion::toWxString(), and TRUE.
Referenced by OSEdAboutDialog().
operator=()
OSEdAboutDialog & OSEdAboutDialog::operator= (const OSEdAboutDialog &) private
Assignment not allowed.
setTexts()
void OSEdAboutDialog::setTexts () private
Sets the texts for the dialog.
Definition at line 79 of file OSEdAboutDialog.cc.
{
    OSEdTextGenerator& osedTexts = OSEdTextGenerator::instance();
    GUITextGenerator& guiTexts = *GUITextGenerator::instance();
    // title
    format fmt = osedTexts.text(OSEdTextGenerator::TXT_ABOUT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // static texts
    WidgetTools::setLabel(&osedTexts, FindWindow(ID_ABOUT_TEXT),
                          OSEdTextGenerator::TXT_ABOUT);
    // buttons
    WidgetTools::setLabel(&guiTexts, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
}
References ID_ABOUT_TEXT, GUITextGenerator::instance(), OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ABOUT, OSEdTextGenerator::TXT_ABOUT_DIALOG_TITLE, and GUITextGenerator::TXT_BUTTON_OK.
Referenced by OSEdAboutDialog().
The documentation for this class was generated from the following files:
OSEdAboutDialog.hh
OSEdAboutDialog.cc