OpenASIP: OperationBindingCheck Class Reference
OperationBindingCheck Class Reference
#include <OperationBindingCheck.hh>
Public Member Functions
OperationBindingCheck ()
virtual bool check (const TTAMachine::Machine &mach, MachineCheckResults &results) const
Public Member Functions inherited from MachineCheck
virtual std::string shortDescription () const
virtual std::string description () const
virtual bool canFix (const TTAMachine::Machine &mach) const
virtual std::string fix (TTAMachine::Machine &mach) const
virtual ~MachineCheck ()
Additional Inherited Members
Protected Member Functions inherited from MachineCheck
MachineCheck (const std::string &shortDesc_)
Detailed Description
Check that tests port bindings in machine
Definition at line 42 of file OperationBindingCheck.hh.
Constructor & Destructor Documentation
OperationBindingCheck()
OperationBindingCheck::OperationBindingCheck ()
Definition at line 45 of file OperationBindingCheck.cc.
                                             :
    MachineCheck("Check operation binding, port directions, triggers") {}
Member Function Documentation
check()
bool OperationBindingCheck::check (const TTAMachine::Machine & mach, MachineCheckResults & results) const virtual
Checks that machine's FU's have legal port and trigger bindings
Parameters
mach machine to check
results place where to put detailed error descriptions
Returns
true if everything is ok, false if something is wrong
Implements MachineCheck.
Definition at line 55 of file OperationBindingCheck.cc.
{
    TTAMachine::Machine::FunctionUnitNavigator fuNav =
        mach.functionUnitNavigator();
    bool retval = true;
    bool triggerok = true;
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit& fu = *fuNav.item(i);
        // find trigger port
        FUPort* triggerPort = NULL;
        for (int j = 0; j < fu.operationPortCount(); j++) {
            FUPort* port = fu.operationPort(j);
            if (port->isTriggering()) {
                // check that we do not have multiple trigger ports.
                if ( triggerPort != NULL) {
                    results.addError(
                        *this, (boost::format("Multiple trigger ports are "
                                              "not supported, Used in FU: %s")
                                % fu.name()).str());
                    retval = false;
                    triggerok = false;
                }
                else {
                    // check trigger and fu ports are the same
                    triggerPort = port;
                    if (!port->isOpcodeSetting()) {
                        results.addError(
                            *this, (boost::format("Opcode setting and trigger "
                                                  "port differ in FU: ")
                                    % fu.name()).str());
                        retval = false;
                        triggerok = false;
                    }
                }
            }
        }
        // check that we have a trigger port
        if ( triggerPort == NULL) {
            results.addError(
                *this, (boost::format("Trigger port not found in FU: %s")
                        % fu.name()).str());
            return false;
        }
        // check all operations
        for (int j = 0; j < fu.operationCount(); j++) {
            HWOperation& hwop = *fu.operation(j);
            bool triggerRead = false;
            // check read port bindins
            ExecutionPipeline& pipe = *hwop.pipeline();
            const ExecutionPipeline::OperandSet reads = pipe.readOperands();
            for (ExecutionPipeline::OperandSet::const_iterator iter =
                     reads.begin(); iter != reads.end(); iter++) {
                Port* readPort = hwop.port(*iter);
                if ( readPort->inputSocket() == NULL) {
                    std::string errorMsg =
                        (boost::format(
                            "Operation %s in FU %s reads operand %d which "
                            "is not connected to input socket. "
                            "Check port bindings!")
                         % hwop.name() % fu.name() % *iter).str();
                    results.addError(*this, (errorMsg));
                    retval = false;
                } else {
                    // check if this was read from the trigger
                    if (readPort == triggerPort) {
                        triggerRead = true;
                    }
                }
            }
            // was trigger actually read?
            if ( triggerok && !triggerRead) {
                std::string errorMsg =
                    (boost::format(
                         "Trigger not bound for operation: %s in FU %s") %
                     hwop.name() % fu.name()).str();
                results.addError(*this, errorMsg);
                retval = false;
            }
            // check write port bidings
            const ExecutionPipeline::OperandSet writes =
                pipe.writtenOperands();
            for (ExecutionPipeline::OperandSet::const_iterator iter =
                     writes.begin(); iter != writes.end(); iter++) {
                Port* writePort = hwop.port(*iter);
                if ( writePort->outputSocket() == NULL) {
                    results.addError(
                        *this, (boost::format("Operation %s in FU %s "
                                              "writes operand %d"
                                              "which is not connected to "
                                              "output socket. "
                                              "Check port bindings!")
                                % hwop.name() % fu.name() % *iter).str());
                    retval = false;
                }
            }
        }
    }
    return retval;
}
References MachineCheckResults::addError(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Port::inputSocket(), TTAMachine::FUPort::isOpcodeSetting(), TTAMachine::FUPort::isTriggering(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::Port::outputSocket(), TTAMachine::HWOperation::pipeline(), TTAMachine::HWOperation::port(), TTAMachine::ExecutionPipeline::readOperands(), and TTAMachine::ExecutionPipeline::writtenOperands().
The documentation for this class was generated from the following files:
OperationBindingCheck.hh
OperationBindingCheck.cc