OpenASIP: BFSchedulePreLoopShared Class Reference
BFSchedulePreLoopShared Class Reference
#include <BFSchedulePreLoopShared.hh>
Public Member Functions
BFSchedulePreLoopShared (BF2Scheduler &sched, MoveNode &originalMN)
bool operator() ()
void undoOnlyMe ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & originalMN_
MoveNode * prologMN_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 38 of file BFSchedulePreLoopShared.hh.
Constructor & Destructor Documentation
BFSchedulePreLoopShared()
BFSchedulePreLoopShared::BFSchedulePreLoopShared (BF2Scheduler & sched, MoveNode & originalMN) inline
Definition at line 40 of file BFSchedulePreLoopShared.hh.
                                                                       :
        BFOptimization(sched), originalMN_(originalMN) {}
Member Function Documentation
operator()()
bool BFSchedulePreLoopShared::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 43 of file BFSchedulePreLoopShared.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tScheduling pre-loop-shared operand: "
              << originalMN_.toString()
              << std::endl;
#endif
    auto a = duplicator().duplicateMoveNode(originalMN_, true, true);
    prologMN_ = a.first;
    // These should always be unconditional. Operand moves have
    // no side effects, and nobody else uses the FU,
    // and the value of the guard might change between the iterations
    if (!prologMN_->move().isUnconditional()) {
        prologMN_->move().setGuard(NULL);
    }
    if (prologMN_ == NULL) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\tMissing prolog MN for the move. " << std::endl;
#endif
        return false;
    }
    int ddgLC = prologDDG()->latestCycle(*prologMN_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tddg lc: " << ddgLC << std::endl;
#endif
    if (ddgLC < 0) {
        duplicator().disposeMoveNode(prologMN_);
        return false;
    }
    int lastCycleOfProlog = rm().initiationInterval()-1+
        BF2Scheduler::PROLOG_CYCLE_BIAS;
    int rmlc = prologRM()->latestCycle(
        std::min(ddgLC, lastCycleOfProlog), *prologMN_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\trmlc: " << rmlc << std::endl;
#endif
    if (rmlc < 0) {
        duplicator().disposeMoveNode(prologMN_);
        return false;
    }
    prologRM()->assign(rmlc, *prologMN_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "scheduling of pre-loop opshare ok!"
              << prologMN_->toString() << std::endl;
#endif
    return true;
}
References SimpleResourceManager::assign(), MoveNodeDuplicator::disposeMoveNode(), MoveNodeDuplicator::duplicateMoveNode(), BFOptimization::duplicator(), SimpleResourceManager::initiationInterval(), TTAProgram::Move::isUnconditional(), DataDependenceGraph::latestCycle(), SimpleResourceManager::latestCycle(), MoveNode::move(), originalMN_, BF2Scheduler::PROLOG_CYCLE_BIAS, BFOptimization::prologDDG(), prologMN_, BFOptimization::prologRM(), BFOptimization::rm(), TTAProgram::Move::setGuard(), and MoveNode::toString().
undoOnlyMe()
void BFSchedulePreLoopShared::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 91 of file BFSchedulePreLoopShared.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "undoing scheudle of pre-loop opschare: "
              << prologMN_->toString() << std::endl;
#endif
    prologRM()->unassign(*prologMN_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "unassigned scheudle of pre-loop opschare: "
              << prologMN_->toString() << std::endl;
#endif
    duplicator().disposeMoveNode(prologMN_);
}
References MoveNodeDuplicator::disposeMoveNode(), BFOptimization::duplicator(), prologMN_, BFOptimization::prologRM(), MoveNode::toString(), and SimpleResourceManager::unassign().
Member Data Documentation
originalMN_
MoveNode& BFSchedulePreLoopShared::originalMN_ private
Definition at line 45 of file BFSchedulePreLoopShared.hh.
Referenced by operator()().
prologMN_
MoveNode* BFSchedulePreLoopShared::prologMN_ private
Definition at line 46 of file BFSchedulePreLoopShared.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFSchedulePreLoopShared.hh
BFSchedulePreLoopShared.cc