OpenASIP: FUPortImplementationDialog Class Reference
FUPortImplementationDialog Class Reference
#include <FUPortImplementationDialog.hh>
Public Member Functions
FUPortImplementationDialog (wxWindow *parent, wxWindowID id, HDB::FUPortImplementation &implementation, const TTAMachine::BaseFUPort &architecture)
virtual ~FUPortImplementationDialog ()
virtual bool TransferDataToWindow ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_NAME , ID_LABEL_ARCHITECTURE_PORT , ID_ARCHITECTURE_PORT_NAME ,
ID_LABEL_WIDTH , ID_WIDTH , ID_LOAD_PORT_LABEL , ID_LOAD_PORT ,
ID_GUARD_PORT_LABEL , ID_GUARD_PORT , ID_OPERAND_LIST , ID_LINE
}
Enumerated IDs for dialog widgets.
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Creates the dialog contents.
Private Attributes
HDB::FUPortImplementation & implementation_
FU port implementation to modify.
const TTAMachine::BaseFUPort & architecture_
Architecture of the modified port.
wxString name_
Name of the port.
wxString loadPortName_
Name of the load port.
wxString guardPortName_
Name of the guard port.
wxString widthFormula_
Width formula string.
wxListCtrl * operandList_
List widget for the operand bindings.
Detailed Description
Dialog for editing FU port implementations.
Definition at line 49 of file FUPortImplementationDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerated IDs for dialog widgets.
Enumerator
ID_LABEL_NAME
ID_NAME
ID_LABEL_ARCHITECTURE_PORT
ID_ARCHITECTURE_PORT_NAME
ID_LABEL_WIDTH
ID_WIDTH
ID_LOAD_PORT_LABEL
ID_LOAD_PORT
ID_GUARD_PORT_LABEL
ID_GUARD_PORT
ID_OPERAND_LIST
ID_LINE
Definition at line 63 of file FUPortImplementationDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_NAME,
        ID_LABEL_ARCHITECTURE_PORT,
        ID_ARCHITECTURE_PORT_NAME,
        ID_LABEL_WIDTH,
        ID_WIDTH,
        ID_LOAD_PORT_LABEL,
        ID_LOAD_PORT,
        ID_GUARD_PORT_LABEL,
        ID_GUARD_PORT,
        ID_OPERAND_LIST,
        ID_LINE
    };
Constructor & Destructor Documentation
FUPortImplementationDialog()
FUPortImplementationDialog::FUPortImplementationDialog (wxWindow * parent, wxWindowID id, HDB::FUPortImplementation & implementation, const TTAMachine::BaseFUPort & architecture)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog window.
implementation FU port implementation to modify.
architecthre Architecture of the modified port.
Definition at line 61 of file FUPortImplementationDialog.cc.
                                    :
    wxDialog(parent, id, _T("Function Unit Port Implementation"),
        wxDefaultPosition),
    implementation_(implementation), architecture_(architecture) {
    createContents(this, true, true);
    operandList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERAND_LIST));
    assert(operandList_ != NULL);
    operandList_->InsertColumn(
        0, _T("Operation"), wxLIST_FORMAT_LEFT, 140);
    operandList_->InsertColumn(
        1, _T("R/W"), wxLIST_FORMAT_LEFT, 60);
    operandList_->InsertColumn(
        2, _T("io"), wxLIST_FORMAT_LEFT, 60);
    name_ = WxConversion::toWxString(implementation_.name());
    loadPortName_ = WxConversion::toWxString(
        implementation_.loadPort());
    guardPortName_ = WxConversion::toWxString(
        implementation_.guardPort());
    widthFormula_ = WxConversion::toWxString(
        implementation_.widthFormula());
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_LOAD_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &loadPortName_));
    FindWindow(ID_GUARD_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &guardPortName_));
    FindWindow(ID_WIDTH)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &widthFormula_));
    dynamic_cast<wxStaticText*>(FindWindow(ID_ARCHITECTURE_PORT_NAME))->
        SetLabel(WxConversion::toWxString(implementation_.architecturePort()));
    TransferDataToWindow();
}
References assert, and WxConversion::toWxString().
~FUPortImplementationDialog()
FUPortImplementationDialog::~FUPortImplementationDialog () virtual
The Destructor.
Definition at line 108 of file FUPortImplementationDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FUPortImplementationDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Creates the dialog contents.
Definition at line 199 of file FUPortImplementationDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_ARCHITECTURE_PORT, wxT("Architecture port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_ARCHITECTURE_PORT_NAME, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LOAD_PORT_LABEL, wxT("Load port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_LOAD_PORT, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item8, 0, wxGROW|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_GUARD_PORT_LABEL, wxT("Guard port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item9, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_GUARD_PORT, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width formula:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_WIDTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item12, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticBox *item14 = new wxStaticBox( parent, -1, wxT("Operand bindings:") );
    wxStaticBoxSizer *item13 = new wxStaticBoxSizer( item14, wxVERTICAL );
    wxListCtrl *item15 = new wxListCtrl( parent, ID_OPERAND_LIST, wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item13->Add( item15, 0, wxGROW|wxALL, 5 );
    item1->Add( item13, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item16 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item16, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item18 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER, 5 );
    wxButton *item19 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item17, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ARCHITECTURE_PORT_NAME, ID_GUARD_PORT, ID_GUARD_PORT_LABEL, ID_LABEL_ARCHITECTURE_PORT, ID_LABEL_NAME, ID_LABEL_WIDTH, ID_LINE, ID_LOAD_PORT, ID_LOAD_PORT_LABEL, ID_NAME, ID_OPERAND_LIST, and ID_WIDTH.
onOK()
void FUPortImplementationDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 164 of file FUPortImplementationDialog.cc.
{
    TransferDataFromWindow();
    name_ = name_.Trim(true).Trim(false);
    loadPortName_ = loadPortName_.Trim(true).Trim(false);
    guardPortName_ = guardPortName_.Trim(true).Trim(false);
    widthFormula_ = widthFormula_.Trim(true).Trim(false);
    if (name_.IsEmpty()) {
        wxString message = _T("Name field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    if (widthFormula_.IsEmpty()) {
        wxString message = _T("Width formula field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    implementation_.setName(WxConversion::toString(name_));
    implementation_.setLoadPort(WxConversion::toString(loadPortName_));
    implementation_.setGuardPort(WxConversion::toString(guardPortName_));
    implementation_.setWidthFormula(WxConversion::toString(widthFormula_));
    EndModal(wxID_OK);
}
References guardPortName_, implementation_, loadPortName_, name_, HDB::FUPortImplementation::setGuardPort(), HDB::PortImplementation::setLoadPort(), HDB::PortImplementation::setName(), HDB::FUPortImplementation::setWidthFormula(), WxConversion::toString(), and widthFormula_.
TransferDataToWindow()
bool FUPortImplementationDialog::TransferDataToWindow () virtual
Transfers data from the dialog attributes to the dialog widgets.
Returns
True, if the data was succesfully transferred.
Definition at line 118 of file FUPortImplementationDialog.cc.
{
    operandList_->DeleteAllItems();
    const FunctionUnit* fu = architecture_.parentUnit();
    const FUPort* fuPort = dynamic_cast<const FUPort*>(&architecture_);
    assert(fu != NULL);
    int item = 0;
    for (int i = 0; i < fu->operationCount(); i++) {
        const HWOperation* operation = fu->operation(i);
        if (fuPort != NULL && operation->isBound(*fuPort)) {
            wxString rw;
            bool read = false;
            bool written = false;
            for (int cycle = 0; cycle < operation->latency(); cycle++) {
                if (operation->pipeline()->isPortRead(*fuPort, cycle)) {
                    read = true;
                }
                if (operation->pipeline()->isPortWritten(*fuPort, cycle)) {
                    written = true;
                }
            }
            if (read) {
                rw.Append(_T("R"));
            }
            if (written) {
                rw.Append(_T("W"));
            }
            operandList_->InsertItem(
                item, WxConversion::toWxString(operation->name()));
            operandList_->SetItem(item, 1, rw);
            operandList_->SetItem(
                item, 2, WxConversion::toWxString(operation->io(*fuPort)));
            item++;
        }
    }
    return wxDialog::TransferDataToWindow();
}
References architecture_, assert, TTAMachine::HWOperation::io(), TTAMachine::HWOperation::isBound(), TTAMachine::ExecutionPipeline::isPortRead(), TTAMachine::ExecutionPipeline::isPortWritten(), TTAMachine::HWOperation::latency(), TTAMachine::HWOperation::name(), operandList_, TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::HWOperation::pipeline(), and WxConversion::toWxString().
Member Data Documentation
architecture_
const TTAMachine::BaseFUPort& FUPortImplementationDialog::architecture_ private
Architecture of the modified port.
Definition at line 84 of file FUPortImplementationDialog.hh.
Referenced by TransferDataToWindow().
guardPortName_
wxString FUPortImplementationDialog::guardPortName_ private
Name of the guard port.
Definition at line 91 of file FUPortImplementationDialog.hh.
Referenced by onOK().
implementation_
HDB::FUPortImplementation& FUPortImplementationDialog::implementation_ private
FU port implementation to modify.
Definition at line 82 of file FUPortImplementationDialog.hh.
Referenced by onOK().
loadPortName_
wxString FUPortImplementationDialog::loadPortName_ private
Name of the load port.
Definition at line 89 of file FUPortImplementationDialog.hh.
Referenced by onOK().
name_
wxString FUPortImplementationDialog::name_ private
Name of the port.
Definition at line 87 of file FUPortImplementationDialog.hh.
Referenced by onOK().
operandList_
wxListCtrl* FUPortImplementationDialog::operandList_ private
List widget for the operand bindings.
Definition at line 96 of file FUPortImplementationDialog.hh.
Referenced by TransferDataToWindow().
widthFormula_
wxString FUPortImplementationDialog::widthFormula_ private
Width formula string.
Definition at line 93 of file FUPortImplementationDialog.hh.
Referenced by onOK().
The documentation for this class was generated from the following files:
FUPortImplementationDialog.hh
FUPortImplementationDialog.cc