OpenASIP: ProgCommand Class Reference
ProgCommand Class Reference
#include <ProgCommand.hh>
Public Member Functions
ProgCommand ()
virtual ~ProgCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "prog" command of the Simulator Control Language.
Definition at line 46 of file ProgCommand.hh.
Constructor & Destructor Documentation
ProgCommand()
ProgCommand::ProgCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 48 of file ProgCommand.cc.
                         : SimControlLanguageCommand("prog") {
}
~ProgCommand()
ProgCommand::~ProgCommand () virtual
Destructor.
Does nothing.
Definition at line 56 of file ProgCommand.cc.
{
}
Member Function Documentation
execute()
bool ProgCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "prog" command.
Loads a new program file using the SimulatorFrontend.
Parameters
arguments Filename is given as argument to the command.
Returns
True if loading the program was successful.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 70 of file ProgCommand.cc.
{
    assert(interpreter() != NULL);
    SimulatorTextGenerator& textGen = SimulatorToolbox::textGenerator();
    if (arguments.size() < 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_NO_FILENAME_DEFINED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    if (arguments.size() > 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_ONLY_ONE_FILENAME_EXPECTED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    SimulatorInterpreterContext& interpreterContext =
        dynamic_cast<SimulatorInterpreterContext&>(interpreter()->context());
    SimulatorFrontend& simulatorFrontend =
        interpreterContext.simulatorFrontend();
    try {
        const std::string fileName =
            FileSystem::expandTilde(arguments.at(1).stringValue());
        simulatorFrontend.loadProgram(fileName);
    } catch (const Exception& e) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(e.errorMessage());
        interpreter()->setResult(errorMessage);
        return false;
    }
    if (simulatorFrontend.automaticFinishImpossible())
        outputStream()
            << textGen.text(Texts::TXT_AUTOMATIC_FINISH_IMPOSSIBLE).str()
            << std::endl;
    return true;
}
References assert, SimulatorFrontend::automaticFinishImpossible(), ScriptInterpreter::context(), Exception::errorMessage(), FileSystem::expandTilde(), CustomCommand::interpreter(), SimulatorFrontend::loadProgram(), SimControlLanguageCommand::outputStream(), ScriptInterpreter::setResult(), DataObject::setString(), SimControlLanguageCommand::simulatorFrontend(), SimulatorInterpreterContext::simulatorFrontend(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_AUTOMATIC_FINISH_IMPOSSIBLE, Texts::TXT_NO_FILENAME_DEFINED, and Texts::TXT_ONLY_ONE_FILENAME_EXPECTED.
helpText()
std::string ProgCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 123 of file ProgCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
    Texts::TXT_INTERP_HELP_PROG).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_PROG.
The documentation for this class was generated from the following files:
ProgCommand.hh
ProgCommand.cc