OpenASIP: TTAMachine::FunctionUnit Class Reference
TTAMachine::FunctionUnit Class Reference
#include <FunctionUnit.hh>
Public Member Functions
FunctionUnit (const std::string &name)
FunctionUnit (const ObjectState *state)
virtual ~FunctionUnit ()
virtual FunctionUnit * copy () const
virtual void setName (const std::string &name)
virtual BaseFUPort * port (const std::string &name) const
virtual BaseFUPort * port (int index) const
virtual int operationPortCount () const
virtual bool hasOperationPort (const std::string &name) const
virtual FUPort * operationPort (const std::string &name) const
virtual FUPort * operationPort (int index) const
virtual BaseFUPort * triggerPort () const
virtual void addOperation (HWOperation &operation)
virtual void deleteOperation (HWOperation &operation)
virtual bool hasOperation (const std::string &name) const
virtual bool hasOperationLowercase (const std::string &name) const
virtual HWOperation * operation (const std::string &name) const
virtual HWOperation * operationLowercase (const std::string &name) const
virtual HWOperation * operation (int index) const
virtual int operationCount () const
virtual void operationNames (TCETools::CIStringSet &opNames) const
virtual int maxLatency () const
virtual void addPipelineElement (PipelineElement &element)
virtual void deletePipelineElement (PipelineElement &element)
virtual int pipelineElementCount () const
virtual PipelineElement * pipelineElement (int index) const
virtual bool hasPipelineElement (const std::string &name) const
virtual PipelineElement * pipelineElement (const std::string &name) const
virtual AddressSpace * addressSpace () const
virtual void setAddressSpace (AddressSpace *as)
virtual bool hasAddressSpace () const
virtual void cleanup (const std::string &resource)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
virtual bool isArchitectureEqual (const FunctionUnit *fu, const bool checkPortWidths=true) const
bool needsConflictDetection () const
virtual int orderNumber () const
virtual void setOrderNumber (int)
Public Member Functions inherited from TTAMachine::Unit
virtual ~Unit ()
virtual bool hasPort (const std::string &name) const
virtual int portCount () const
virtual int outputPortCount (bool countBidir=false) const
virtual int inputPortCount (bool countBidir=false) const
virtual int bidirPortCount () const
virtual void setMachine (Machine &mach)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_FU = "fu"
ObjectState name for function unit.
static const std::string OSKEY_AS = "as"
ObjectState attribute key for name of the address space.
static const std::string OSKEY_ORDER_NUMBER = "order_no"
ObjectState attribute key for FU order number name.
Static Public Attributes inherited from TTAMachine::Unit
static const std::string OSNAME_UNIT = "unit"
ObjectState name for Unit.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Protected Member Functions
void unsetMachineDerived ()
Protected Member Functions inherited from TTAMachine::Unit
Unit (const std::string &name)
Unit (const ObjectState *state)
virtual void removePort (Port &port)
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Types
typedef std::vector< HWOperation * > OperationTable
Container for operations.
typedef std::vector< PipelineElement * > PipelineElementTable
Container for pipeline elements.
Private Member Functions
FunctionUnit (const FunctionUnit &)
Copying forbidden.
void cleanupGuards () const
void loadStateWithoutReferences (const ObjectState *fuState)
void deleteAllOperations ()
Private Attributes
OperationTable operations_
Contains all the operations of the function unit.
PipelineElementTable pipelineElements_
Contains all the pipeline elements of the function unit.
AddressSpace * addressSpace_
Address space used by the function unit.
int orderNumber_
Number indicating possition of the FU in the ADF file. Alows putting the FU into the order in the instruction.
Detailed Description
Represents a function unit in machine object model.
Definition at line 55 of file FunctionUnit.hh.
Member Typedef Documentation
OperationTable
typedef std::vector<HWOperation*> TTAMachine::FunctionUnit::OperationTable private
Container for operations.
Definition at line 130 of file FunctionUnit.hh.
PipelineElementTable
typedef std::vector<PipelineElement*> TTAMachine::FunctionUnit::PipelineElementTable private
Container for pipeline elements.
Definition at line 132 of file FunctionUnit.hh.
Constructor & Destructor Documentation
FunctionUnit() [1/3]
TTAMachine::FunctionUnit::FunctionUnit (const std::string & name)
Constructor.
Parameters
name Name of the function unit.
Exceptions
InvalidName If the given name is not a valid component name.
Definition at line 66 of file FunctionUnit.cc.
    : Unit(name), addressSpace_(NULL), orderNumber_(0) {}
FunctionUnit() [2/3]
TTAMachine::FunctionUnit::FunctionUnit (const ObjectState * state)
Constructor.
Loads the state of the function unit from the given ObjectState instance. Does not load references to other components.
Parameters
state The ObjectState instance to load the state from.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 79 of file FunctionUnit.cc.
    : Unit(state), addressSpace_(NULL), orderNumber_(0) {
    loadStateWithoutReferences(state);
}
References loadStateWithoutReferences().
~FunctionUnit()
TTAMachine::FunctionUnit::~FunctionUnit () virtual
Destructor.
Deletes all the operations.
Definition at line 89 of file FunctionUnit.cc.
{
    unsetMachine();
    deleteAllOperations();
}
References deleteAllOperations(), and unsetMachine().
FunctionUnit() [3/3]
TTAMachine::FunctionUnit::FunctionUnit (const FunctionUnit &) private
Copying forbidden.
Member Function Documentation
addOperation()
void TTAMachine::FunctionUnit::addOperation (HWOperation & operation) virtual
Adds an operation into the function unit. This method is called from HWOperation constructor. Do not use this method.
Parameters
operation Operation which is added.
Exceptions
ComponentAlreadyExists If there is already an operation by the same name as the given operation.
Definition at line 286 of file FunctionUnit.cc.
{
    // run time check that this method is called from HWOperation constructor
    // only.
    assert(operation.parentUnit() == NULL);
    if (!FunctionUnit::hasOperation(operation.name())) {
        operations_.push_back(&operation);
    } else {
        string procName = "FunctionUnit::addOperation";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
}
References assert, hasOperation(), TTAMachine::HWOperation::name(), operation(), operations_, and TTAMachine::HWOperation::parentUnit().
Referenced by TTAMachine::HWOperation::HWOperation(), and TTAMachine::HWOperation::HWOperation().
addPipelineElement()
void TTAMachine::FunctionUnit::addPipelineElement (PipelineElement & element) virtual
Adds a pipeline element to the function unit.
Pipeline elements are added automatically if some operation uses it. Clients must not add pipeline elements explicitly. PipelineElement adds itself automatically to the parent function when it is created.
Parameters
name Name of the pipeline element.
Exceptions
ComponentAlreadyExists If there is already a pipeline element by the given name.
Reimplemented in UniversalFunctionUnit.
Definition at line 466 of file FunctionUnit.cc.
{
    // sanity check to verify that this is called from PipelineElement's
    // constructor
    assert(element.parentUnit() == NULL);
    string name = element.name();
    if (hasPipelineElement(name)) {
        string procName = "FunctionUnit::addPipelineElement";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        pipelineElements_.push_back(&element);
    }
}
References assert, hasPipelineElement(), TTAMachine::Component::name(), TTAMachine::PipelineElement::name(), TTAMachine::PipelineElement::parentUnit(), and pipelineElements_.
Referenced by TTAMachine::PipelineElement::PipelineElement().
addressSpace()
AddressSpace * TTAMachine::FunctionUnit::addressSpace () const virtual
Returns the address space used by the function unit.
Returns
The address space used by the function unit.
Definition at line 580 of file FunctionUnit.cc.
{
    return addressSpace_;
}
References addressSpace_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), ADFCombiner::addFunctionUnits(), ProGe::ProcessorWrapperBlock::addInstructionMemory(), MachineStateBuilder::buildMachineState(), ProGe::NetlistGenerator::calculateAddressWidth(), AddressSpaceCheck::check(), MachineValidator::checkGCUHasAddressSpace(), MachineValidator::checkIMemAddrWidth(), BEMValidator::checkImemMauWidth(), MachineResourceManager::codeAddressSpace(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::ProgramWriter::createBinary(), FUFactory::createEditPart(), FUGen::createExternalInterfaces(), PlatformIntegrator::createMemories(), OpsetDialog::createOperation(), TTAProgram::CodeGenerator::createSchedYieldProcedure(), MachineInfo::defaultDataAddressSpace(), PasteComponentCmd::Do(), llvm::LLVMTCEBuilder::emitOperationMacro(), ITemplateBroker::findITemplates(), AlmaIFIntegrator::findMemories(), FUGen::FUGen(), CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateLoadTrigger(), ProgramImageGenerator::generateProgramImage(), ProGe::ProcessorGenerator::iMemAddressWidth(), ProGe::ProcessorGenerator::iMemWidth(), llvm::LLVMTCEBuilder::initDataSections(), SimulatorFrontend::initializeMemorySystem(), ProGe::NetlistGenerator::instructionMemory(), isArchitectureEqual(), isInstructionMemory(), MachineInfo::maxMemoryAlignment(), PlatformIntegrator::parseDataMemories(), printLatexAddressSpaceDescription(), printLatexFunctionUnitDescription(), ProgrammabilityValidator::ProgrammabilityValidator(), ProGe::ProGeUI::readImemParameters(), PlatformIntegrator::readLsuParameters(), TTAProgram::Program::replaceUniversalAddressSpaces(), MachineConnectivityCheck::requiredImmediateWidth(), CodeCompressorPlugin::setImemWidth(), CodeCompressorPlugin::setMachine(), TTAMachine::AddressSpace::unsetMachine(), FUDialog::updateAddressSpaceChoice(), GCUDialog::updateAddressSpaceChoice(), CompiledSimCodeGenerator::updateDeclaredSymbolsList(), and llvm::LLVMTCEIRBuilder::writeMachineFunction().
cleanup()
void TTAMachine::FunctionUnit::cleanup (const std::string & resource) virtual
Deletes a pipeline element by the given name if it is not used by any operation.
Definition at line 622 of file FunctionUnit.cc.
{
    if (!hasPipelineElement(resource)) {
        return;
    }
    for (int i = 0; i < operationCount(); i++) {
        HWOperation* operation = this->operation(i);
        ExecutionPipeline* pLine = operation->pipeline();
        for (int cycle = 0; cycle < pLine->latency(); cycle++) {
            if (pLine->isResourceUsed(resource, cycle)) {
                return;
            }
        }
    }
    PipelineElement* toDelete = pipelineElement(resource);
    delete toDelete;
}
References hasPipelineElement(), TTAMachine::ExecutionPipeline::isResourceUsed(), TTAMachine::ExecutionPipeline::latency(), operation(), operationCount(), TTAMachine::HWOperation::pipeline(), and pipelineElement().
Referenced by TTAMachine::ExecutionPipeline::internalRemoveResourceUse(), and TTAMachine::ExecutionPipeline::removeAllResourceUses().
cleanupGuards()
void TTAMachine::FunctionUnit::cleanupGuards () const private
Cleans up the guards that refer to a port of this function unit.
Definition at line 830 of file FunctionUnit.cc.
{
    Machine* mach = machine();
    if (mach == NULL) {
        return;
    }
    Machine::BusNavigator navi = mach->busNavigator();
    for (int busIndex = 0; busIndex < navi.count(); busIndex++) {
        Bus* bus = navi.item(busIndex);
        int guardIndex = 0;
        while (guardIndex < bus->guardCount()) {
            Guard* guard = bus->guard(guardIndex);
            PortGuard* portGuard =
                dynamic_cast<PortGuard*>(guard);
            if (portGuard != NULL) {
                BaseFUPort* port = portGuard->port();
                FunctionUnit* referenced = port->parentUnit();
                if (referenced == this) {
                    // guard is removed from bus automatically
                    delete portGuard;
                } else {
                    guardIndex++;
                }
            } else {
                guardIndex++;
            }
        }
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), and port().
Referenced by unsetMachine().
copy()
FunctionUnit * TTAMachine::FunctionUnit::copy () const virtual
Copies the instance.
Current FunctionUnit state is copied to a new FunctionUnit object.
Returns
Copy of the instance.
Reimplemented in TTAMachine::ControlUnit.
Definition at line 103 of file FunctionUnit.cc.
{
    return new FunctionUnit(saveState());
}
References saveState().
Referenced by HDB::FUArchitecture::FUArchitecture().
deleteAllOperations()
void TTAMachine::FunctionUnit::deleteAllOperations () private
Deletes all the operations of the function unit.
Definition at line 899 of file FunctionUnit.cc.
{
    while (operations_.size() > 0) {
        delete operations_[0];
    }
}
References operations_.
Referenced by loadStateWithoutReferences(), and ~FunctionUnit().
deleteOperation()
void TTAMachine::FunctionUnit::deleteOperation (HWOperation & operation) virtual
Deletes an operation from the function unit.
Destructor of the operation is called.
Parameters
operation Operation to be deleted.
Exceptions
InstanceNotFound If the given operation doesn't belong to this function unit.
Definition at line 309 of file FunctionUnit.cc.
{
    if (operation.parentUnit() == NULL) {
        bool removed = ContainerTools::removeValueIfExists(operations_,
                                                           &operation);
        assert(removed);
    } else {
        if (!ContainerTools::containsValue(operations_, &operation)) {
            string procName = "FunctionUnit::deleteOperation";
            throw InstanceNotFound(__FILE__, __LINE__, procName);
        }
        delete &operation;
    }
}
References assert, ContainerTools::containsValue(), operation(), operations_, TTAMachine::HWOperation::parentUnit(), and ContainerTools::removeValueIfExists().
Referenced by TTAMachine::HWOperation::~HWOperation().
deletePipelineElement()
void TTAMachine::FunctionUnit::deletePipelineElement (PipelineElement & element) virtual
Deletes the given pipeline element from function unit.
The pipeline element is automatically deleted if it is not used by any of the operations. Clients must not use this method!
Parameters
element The pipeline element to delete.
Definition at line 489 of file FunctionUnit.cc.
{
    // sanity check to verify that this is called from PipelineElement's
    // destructor.
    assert(element.parentUnit() == NULL);
    bool removed = ContainerTools::removeValueIfExists(
        pipelineElements_, &element);
    assert(removed);
}
References assert, TTAMachine::PipelineElement::parentUnit(), pipelineElements_, and ContainerTools::removeValueIfExists().
Referenced by TTAMachine::PipelineElement::~PipelineElement().
hasAddressSpace()
bool TTAMachine::FunctionUnit::hasAddressSpace () const virtual
Returns true if the address space is set.
Returns
True if the address space is set.
Definition at line 608 of file FunctionUnit.cc.
{
    if (addressSpace_ == NULL) {
        return false;
    }
    return true;
}
References addressSpace_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), ADFCombiner::addFunctionUnits(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::calculateAddressWidth(), BEMValidator::checkImemMauWidth(), ADFCombiner::connectVectorLSU(), FUGen::createExternalInterfaces(), OpsetDialog::createOperation(), PasteComponentCmd::Do(), MachineInfo::findLockUnits(), AlmaIFIntegrator::findMemories(), FUGen::FUGen(), ImplementationTester::fuHasMemoryAccess(), SimulatorFrontend::initializeMemorySystem(), ProGe::NetlistGenerator::isLSU(), FUGen::isLSUDataPort(), ProGe::NetlistGenerator::isLSUDataPort(), MachineInfo::maxMemoryAlignment(), PlatformIntegrator::parseDataMemories(), and printLatexFunctionUnitDescription().
hasOperation()
bool TTAMachine::FunctionUnit::hasOperation (const std::string & name) const virtual
Returns true if the requested operation exists in the function unit.
Parameters
operation Name of the operation.
Returns
True if the requested operation exists in the function unit.
Reimplemented in UniversalFunctionUnit.
Definition at line 330 of file FunctionUnit.cc.
{
    return hasOperationLowercase(StringTools::stringToLower(name));
}
References hasOperationLowercase(), TTAMachine::Component::name(), and StringTools::stringToLower().
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), addOperation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), OutputFUBroker::allAvailableResources(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkJumpAndCallOperandBindings(), MachineValidator::checkProgramCounterPort(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), MachineValidator::checkReturnAddressPort(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::CodeGenerator::createForLoopBufferInit(), OpsetDialog::createOperation(), createTerminalFUPort(), VectorLSGenerator::createVectorLSU(), TTAProgram::CodeGenerator::createWhileLoopBufferInit(), ProGe::NetlistGenerator::findCorrespondingPort(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), MachineInfo::findLockUnits(), TTAProgram::TPEFProgramFactory::findPort(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), BasicBlockScheduler::findTrigger(), MinimalOpSetCheck::fix(), MachineResourceManager::functionUnitPortResource(), MachineInfo::getBoundPort(), MachineInfo::getPortBindingsOfOperation(), BasicBlockScheduler::getTriggerOperand(), llvm::LLVMTCEBuilder::hasAmbiguousASpaceRefs(), TTAMachine::Machine::hasOperation(), ProGe::ProcessorGenerator::iMemAddressWidth(), TTAProgram::TPEFResourceUpdater::initCache(), ProgramOperation::isLegalFU(), HDB::HDBManager::isMatchingArchitecture(), ProGe::RV32MicroCodeGenerator::mapFunctionUnit(), MachineInfo::maxLatency(), FUDialog::onAddOperation(), GCUDialog::onAddOperation(), TTAProgram::TPEFResourceUpdater::operand(), UniversalFunctionUnit::operation(), BFLateBypassGuard::operator()(), BFShareOperands::operator()(), BFEarlyGuardBypass::operator()(), BF2Scheduler::preAllocateFunctionUnitsInner(), MachineConnectivityCheck::raConnected(), BF2Scheduler::releasePortForOp(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), HDB::HDBManager::resolveArchitecturePort(), MachineResourceManager::rFPortOrFUIndexReference(), MachineInfo::supportsBoolRegisterGuardedJumps(), MachineInfo::supportsPortGuardedJump(), MachineInfo::supportsPortGuardedJumps(), TTAProgram::ProgramWriter::terminalResource(), MachineInfo::triggerIndex(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), TDGen::writeHWLoopDef(), and llvm::LLVMTCEIRBuilder::writeMachineFunction().
hasOperationLowercase()
bool TTAMachine::FunctionUnit::hasOperationLowercase (const std::string & name) const virtual
Returns true if the requested operation exists in the function unit.
Parameters
operation Name of the operation which MUST be in lowercase.
Returns
True if the requested operation exists in the function unit.
Definition at line 341 of file FunctionUnit.cc.
{
    OperationTable::const_iterator iter = operations_.begin();
    while (iter != operations_.end()) {
        if ((*iter)->name() == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References TTAMachine::Component::name(), and operations_.
Referenced by InputFUBroker::allAvailableResources(), MachineConnectivityCheck::busConnectedToFU(), hasOperation(), and ProGe::NetlistGenerator::isLSU().
hasOperationPort()
bool TTAMachine::FunctionUnit::hasOperationPort (const std::string & name) const virtual
Tells whether the function unit has an operation port with the given name.
Parameters
name Name of the port.
Returns
True if the function unit has the operation port, otherwise false.
Definition at line 204 of file FunctionUnit.cc.
{
    if (!hasPort(name)) {
        return false;
    } else {
        Port* port = this->port(name);
        return dynamic_cast<FUPort*>(port) != NULL;
    }
}
References TTAMachine::Unit::hasPort(), TTAMachine::Component::name(), and port().
Referenced by HDB::HDBManager::addFUImplementation(), TTAProgram::ProgramWriter::createCodeSection(), ProGe::NetlistGenerator::findCorrespondingPort(), TTAMachine::ControlUnit::hasSpecialRegisterPort(), GCUDialog::onEditPort(), and HDB::FUArchitecture::portDirection().
hasPipelineElement()
bool TTAMachine::FunctionUnit::hasPipelineElement (const std::string & name) const virtual
Returns true if the function unit has a pipeline element by the given name.
Returns
True if the function unit has a pipeline element by the given name.
Definition at line 540 of file FunctionUnit.cc.
{
    PipelineElementTable::const_iterator iter = pipelineElements_.begin();
    while (iter != pipelineElements_.end()) {
        if ((*iter)->name() == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References TTAMachine::Component::name(), and pipelineElements_.
Referenced by TTAMachine::ExecutionPipeline::addPipelineElement(), addPipelineElement(), cleanup(), isArchitectureEqual(), OperationDialog::onAddResource(), OperationDialog::onResourceLClick(), and TTAMachine::ExecutionPipeline::removeResourceUse().
isArchitectureEqual()
bool TTAMachine::FunctionUnit::isArchitectureEqual (const FunctionUnit * fu, const bool checkPortWidths = true) const virtual
Compares two FunctionUnit architectures.
Names are not compared. Port width comparison can be omitted.
Parameters
fu Function unit to compare with.
checkPortWidths Boolean for if port widths are matched or not. Defaul is true.
Returns
True if the architectures match otherwise false.
Definition at line 747 of file FunctionUnit.cc.
{
    if (operationCount() != fu->operationCount()) {
        return false;
    }
    int fuPortCount = fu->operationPortCount();
    if (operationPortCount() != fuPortCount) {
        return false;
    }
    int fuPipelineElementCount = fu->pipelineElementCount();
    if (pipelineElementCount() != fuPipelineElementCount) {
        return false;
    }
    if (addressSpace() != NULL && fu->addressSpace() != NULL) {
        if (addressSpace()->name() != fu->addressSpace()->name()) {
            return false;
        }
    } else if ((addressSpace() == NULL && fu->addressSpace() != NULL) ||
               (addressSpace() != NULL && fu->addressSpace() == NULL)) {
        return false;
    }
    for (int i = 0; i < fuPipelineElementCount; i++) {
        string element = pipelineElement(i)->name();
        if (fu->hasPipelineElement(element)) {
            return false;
        }
    }
    for (int i = 0; i < fuPortCount; i++) {
        if (checkPortWidths) {
            if (!operationPort(i)->isArchitectureEqual(fu->operationPort(i))) {
                return false;
            }
        } else {
            if (operationPort(i)->isTriggering() !=
                fu->operationPort(i)->isTriggering()) {
                return false;
            }
           if (operationPort(i)->isOpcodeSetting() !=
                fu->operationPort(i)->isOpcodeSetting()) {
                return false;
            }
       }
    }
    if (!(ResourceVectorSet(*this) == ResourceVectorSet(*fu))) {
        return false;
    }
    return true;
}
References addressSpace(), hasPipelineElement(), isArchitectureEqual(), TTAMachine::FUPort::isOpcodeSetting(), TTAMachine::FUPort::isTriggering(), TTAMachine::Component::name(), TTAMachine::PipelineElement::name(), operationCount(), operationPort(), operationPortCount(), pipelineElement(), and pipelineElementCount().
Referenced by MachineResourceModifier::analyzeFunctionUnits(), isArchitectureEqual(), and EntryKeyDataFunctionUnit::isEqual().
loadState()
void TTAMachine::FunctionUnit::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if connections to other machine parts cannot be made.
Reimplemented from TTAMachine::Unit.
Reimplemented in TTAMachine::ControlUnit, and UniversalFunctionUnit.
Definition at line 706 of file FunctionUnit.cc.
{
    const string procName = "FunctionUnit::loadState";
    Unit::loadState(state);
    loadStateWithoutReferences(state);
    try {
        // set address space
        if (state->hasAttribute(OSKEY_AS)) {
            MOMTextGenerator textGenerator;
            Machine::AddressSpaceNavigator asNav =
                machine()->addressSpaceNavigator();
            string asName = state->stringAttribute(OSKEY_AS);
            if (!isRegistered() || !asNav.hasItem(asName)) {
                format errorMsg = textGenerator.text(MOMTextGenerator::
                                                     TXT_FU_REF_LOAD_ERR_AS);
                errorMsg % asName % name();
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName, errorMsg.str());
            } else {
                setAddressSpace(asNav.item(asName));
            }
        }
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
}
References TTAMachine::Machine::addressSpaceNavigator(), Exception::errorMessage(), ObjectState::hasAttribute(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Unit::loadState(), loadStateWithoutReferences(), TTAMachine::Component::machine(), TTAMachine::Component::name(), OSKEY_AS, setAddressSpace(), ObjectState::stringAttribute(), and Texts::TextGenerator::text().
Referenced by TTAMachine::ControlUnit::loadState(), TTAMachine::Machine::loadState(), FUDialog::onAddOperation(), and FUDialog::onEditOperation().
loadStateWithoutReferences()
void TTAMachine::FunctionUnit::loadStateWithoutReferences (const ObjectState * fuState) private
Loads the state of the function unit without references to other components.
Parameters
fuState The ObjectState instance from which the state is loaded.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 872 of file FunctionUnit.cc.
{
    deleteAllOperations();
    addressSpace_ = NULL;
    if (fuState->hasAttribute(FunctionUnit::OSKEY_ORDER_NUMBER)) {
        setOrderNumber(fuState->intAttribute(FunctionUnit::OSKEY_ORDER_NUMBER));
    }
    try {
        // load operations
        for (int i = 0; i < fuState->childCount(); i++) {
            ObjectState* child = fuState->child(i);
            if (child->name() == HWOperation::OSNAME_OPERATION) {
                new HWOperation(child, *this);
            }
        }
    } catch (const Exception& e) {
        const string procName = "FunctionUnit::loadStateWithoutReferences";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
}
References addressSpace_, ObjectState::child(), ObjectState::childCount(), deleteAllOperations(), Exception::errorMessage(), ObjectState::hasAttribute(), ObjectState::intAttribute(), ObjectState::name(), OSKEY_ORDER_NUMBER, TTAMachine::HWOperation::OSNAME_OPERATION, and setOrderNumber().
Referenced by FunctionUnit(), and loadState().
maxLatency()
int TTAMachine::FunctionUnit::maxLatency () const virtual
Returns the maximum latency among the operations of the function unit.
Returns
The maximum latency.
Definition at line 443 of file FunctionUnit.cc.
{
    int max(0);
    for (int i = 0; i < operationCount(); i++) {
        if (operation(i)->latency() > max) {
            max = operation(i)->latency();
        }
    }
    return max;
}
References TTAMachine::HWOperation::latency(), operation(), and operationCount().
Referenced by CostDatabase::buildFunctionUnits(), ExecutionPipelineBroker::buildResources(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), CompiledSimCodeGenerator::generateAddFUResult(), TTAMachine::Machine::maximumLatency(), and CompiledSimCodeGenerator::updateDeclaredSymbolsList().
needsConflictDetection()
bool TTAMachine::FunctionUnit::needsConflictDetection () const
Checks if all the operations in the FU have the same latency and there are no shared resources.
Returns
True if the FU needs conflict detection
Definition at line 804 of file FunctionUnit.cc.
{
    if (operationCount() == 0) {
        return false;
    }
    // same latency for all operations?
    const int latency = operation(0)->latency();
    for (int i = 1; i < operationCount(); ++i) {
        if (latency != operation(i)->latency()) {
            return true;
        }
    }
    if (pipelineElementCount() == 0) {
        return false;
    }
    return true;
}
References TTAMachine::HWOperation::latency(), operation(), operationCount(), and pipelineElementCount().
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), and ConflictDetectionCodeGenerator::symbolDeclaration().
operation() [1/2]
HWOperation * TTAMachine::FunctionUnit::operation (const std::string & name) const virtual
Returns operation by the given name.
The requested operation must exist, otherwise assertion fails.
Parameters
name Name of the operation.
Returns
Operation by the given name.
Exceptions
InstanceNotFound If an operation is not found by the given name.
Reimplemented in UniversalFunctionUnit.
Definition at line 363 of file FunctionUnit.cc.
{
    return operationLowercase(StringTools::stringToLower(name));
}
References TTAMachine::Component::name(), operationLowercase(), and StringTools::stringToLower().
Referenced by AddFUFromHDBDialog::acceptToList(), ProGe::RV32MicroCodeGenerator::addBPorts(), RegisterCopyAdder::addConnectionRegisterCopies(), ProgrammabilityValidator::addConnectionToProgram(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), ProGe::RV32MicroCodeGenerator::addIPorts(), addOperation(), ProgrammabilityValidator::addOperationConnections(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), BEMGenerator::addPortCodes(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), MachineStateBuilder::addPortToFU(), ProGe::RV32MicroCodeGenerator::addR1Ports(), ProGe::RV32MicroCodeGenerator::addR1RPorts(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addSPorts(), ProGe::RV32MicroCodeGenerator::addUJPorts(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), OutputFUBroker::allAvailableResources(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForFU(), InputFUBroker::assign(), OutputFUBroker::assign(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), AddressSpaceCheck::check(), OperationBindingCheck::check(), ProGeTools::checkForGeneratableFU(), Automagic::checkForGeneratableFU(), ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), FUGen::checkForValidity(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkJumpAndCallOperandBindings(), FUValidator::checkOperandBindings(), FUValidator::checkOperations(), MachineValidator::checkProgramCounterPort(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), BEMValidator::checkSocketCodeTable(), cleanup(), TTAMachine::FUPort::cleanupOperandBindings(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectVectorLSU(), ProGe::RV32MicroCodeGenerator::constructBInstructions(), ProGe::RV32MicroCodeGenerator::constructIInstructions(), ProGe::RV32MicroCodeGenerator::constructR1Instructions(), ProGe::RV32MicroCodeGenerator::constructR1RInstructions(), ProGe::RV32MicroCodeGenerator::constructRInstructions(), ProGe::RV32MicroCodeGenerator::constructSInstructions(), ProGe::RV32MicroCodeGenerator::constructUJInstructions(), TTAProgram::ProgramWriter::createCodeSection(), FUFactory::createEditPart(), GCUFactory::createEditPart(), FUGen::createFUHeaderComment(), POMDisassembler::createFUPort(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), ProgramDependenceGraph::createJump(), FUTestbenchGenerator::createStimulus(), TTAProgram::TPEFProgramFactory::createTerminal(), TTAProgram::CodeGenerator::createTerminalFUPort(), createTerminalFUPort(), deleteOperation(), ConflictDetectionCodeGenerator::detectConflicts(), ProximFUDetailsCmd::Do(), SocketBusConnCmd::Do(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), MoveNode::earliestResultReadCycle(), llvm::LLVMTCEBuilder::emitReturn(), InfoProcCommand::execute(), InfoStatsCommand::execute(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), ProGe::NetlistGenerator::findCorrespondingPort(), TTAProgram::TPEFProgramFactory::findGuard(), AlmaIFIntegrator::findMemories(), TTAProgram::TerminalFUPort::findNewOperationIndex(), SimulatorFrontend::findPort(), TTAProgram::TPEFProgramFactory::findPort(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), BasicBlockScheduler::findTriggerFromUnit(), ProgramOperation::findTriggerFromUnit(), SimulatorFrontend::finishSimulation(), HDBBrowserWindow::fuArchLabel(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), HDBToHtml::fuArchToHtml(), HDB::HDBManager::fuEntriesByArchitecture(), FUFiniteStateAutomaton::FUFiniteStateAutomaton(), MachineResourceManager::functionUnitPortResource(), FUReservationTableIndex::FUReservationTableIndex(), CompiledSimCodeGenerator::generateConstructorCode(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProGe::RV32MicroCodeGenerator::generateOperationLatencyLogic(), MachineInfo::getBoundPort(), llvm::LLVMTCEBuilder::getHWOperation(), MachineInfo::getOpset(), MachineInfo::getOpset(), getOutputPort(), MachineInfo::getPortBindingsOfOperation(), BasicBlockScheduler::getTriggerOperand(), ProgramOperation::hwopFromOutMove(), ProGe::ProcessorGenerator::iMemAddressWidth(), BFOptimization::immCountPreventsScheduling(), TTAProgram::TPEFResourceUpdater::initCache(), llvm::LLVMTCEBuilder::initDataSections(), HDB::HDBManager::isMatchingArchitecture(), BF2Scheduler::isTrigger(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), MoveNode::latestTriggerWriteCycle(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), AddFUFromHDBDialog::loadHDB(), maxLatency(), MachineInfo::maxLatency(), MachineInfo::maxMemoryAlignment(), needsConflictDetection(), ExecutionPipelineResource::nodeOfInputPort(), AddFUFromHDBDialog::onAdd(), FUDialog::onDeleteOperation(), GCUDialog::onDeleteOperation(), FUImplementationDialog::onOK(), FUImplementationDialog::onSetOpcode(), DefaultDecoderGenerator::opcode(), ProGe::NetlistGenerator::opcodePortWidth(), ProGe::NetlistGenerator::opcodePortWidth(), TTAProgram::TPEFResourceUpdater::operand(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), UniversalFunctionUnit::operation(), DCMFUResourceConflictDetector::operationID(), ReservationTableFUResourceConflictDetector::operationID(), BFShareOperands::operator()(), HDB::FUArchitecture::operator==(), ProgramOperation::outputIndexFromGuard(), PlatformIntegrator::parseDataMemories(), FUGen::parseOperations(), ExecutionPipelineResource::poConflictsWithInputPort(), HDB::FUArchitecture::portDirection(), BF2Scheduler::preAllocateFunctionUnitsInner(), ProgrammabilityValidator::printConnection(), printLatexFunctionUnitDescription(), MachineConnectivityCheck::raConnected(), BF2Scheduler::releasePortForOp(), HDB::HDBManager::resolveArchitecturePort(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), ExecutionPipelineResource::resultReadyCycle(), MachineResourceManager::rFPortOrFUIndexReference(), BFOptimization::RFReadPortCountPreventsScheduling(), saveState(), BUBasicBlockScheduler::scheduleMove(), FUGen::scheduleOperations(), FUDialog::selectedOperation(), GCUDialog::selectedOperation(), DataDependenceGraph::setMachine(), ExecutionPipelineResource::setOperandsUsed(), ExecutionPipelineResource::setResultWriten(), TTAProgram::ProgramWriter::terminalResource(), ExecutionPipelineResource::testTriggerResult(), EntryKeyDataFunctionUnit::toString(), FUPortImplementationDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), ExecutionPipelineResource::triggerTooEarly(), ExecutionPipelineResource::unsetOperandsUsed(), ExecutionPipelineResource::unsetResultWriten(), FUImplementationDialog::update(), TTAMachine::FUPort::updateBindingString(), FUDialog::updateOperationList(), GCUDialog::updateOperationList(), TDGen::writeBackendCode(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), TDGen::writeInstrInfo(), and TTAMachine::PipelineElement::~PipelineElement().
operation() [2/2]
HWOperation * TTAMachine::FunctionUnit::operation (int index) const virtual
Returns operation by the given index.
The value of given index must be between 0 and the return value of operationCount() - 1.
Parameters
index Index.
Returns
Operation by the given index.
Exceptions
OutOfRange If the given index is less than zero or greater or equal to the number of operations in the function unit.
Definition at line 405 of file FunctionUnit.cc.
{
    if (index < 0 || index >= operationCount()) {
        string procName = "FunctionUnit::operation";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return operations_[index];
}
References operationCount(), and operations_.
operationCount()
int TTAMachine::FunctionUnit::operationCount () const virtual
Returns the number of operations in the function unit.
Returns
The number of operations in the function unit.
Definition at line 419 of file FunctionUnit.cc.
{
    return operations_.size();
}
References operations_.
Referenced by AddFUFromHDBDialog::acceptToList(), ProgrammabilityValidator::addConnectionToProgram(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), ProgrammabilityValidator::addOperationConnections(), BEMGenerator::addPortCodes(), MachineStateBuilder::addPortToFU(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForFU(), InputFUBroker::buildResources(), OutputFUBroker::buildResources(), AddressSpaceCheck::check(), OperationBindingCheck::check(), ProGeTools::checkForGeneratableFU(), Automagic::checkForGeneratableFU(), ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), FUValidator::checkOperandBindings(), FUValidator::checkOperations(), BEMValidator::checkSocketCodeTable(), cleanup(), TTAMachine::FUPort::cleanupOperandBindings(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectVectorLSU(), TTAProgram::ProgramWriter::createCodeSection(), FUFactory::createEditPart(), GCUFactory::createEditPart(), FUGen::createFUHeaderComment(), FUGen::createMandatoryPorts(), FUTestbenchGenerator::createStimulus(), FUTestbenchGenerator::createStimulusArrays(), FUTestbenchGenerator::createTbCode(), ConflictDetectionCodeGenerator::detectConflicts(), ProximFUDetailsCmd::Do(), SocketBusConnCmd::Do(), InfoProcCommand::execute(), InfoStatsCommand::execute(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), ProGe::NetlistGenerator::findCorrespondingPort(), AlmaIFIntegrator::findMemories(), SimulatorFrontend::finishSimulation(), HDBBrowserWindow::fuArchLabel(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), HDBToHtml::fuArchToHtml(), FUCollisionMatrixIndex::FUCollisionMatrixIndex(), HDB::HDBManager::fuEntriesByArchitecture(), FUFiniteStateAutomaton::FUFiniteStateAutomaton(), FUReservationTableIndex::FUReservationTableIndex(), ProGe::CUOpcodeGenerator::gcuOpcodeWidth(), CompiledSimCodeGenerator::generateConstructorCode(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), MachineInfo::getOpset(), MachineInfo::getOpset(), llvm::LLVMTCEBuilder::initDataSections(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), AddFUFromHDBDialog::loadHDB(), maxLatency(), MachineInfo::maxMemoryAlignment(), needsConflictDetection(), BEMValidator::needsSocketCodeTable(), BEMGenerator::needsSocketCodeTable(), AddFUFromHDBDialog::onAdd(), FUImplementationDialog::onOK(), FUImplementationDialog::onSetOpcode(), DefaultDecoderGenerator::opcode(), ProGe::NetlistGenerator::opcodePortWidth(), ProGe::NetlistGenerator::opcodePortWidth(), DefaultDecoderGenerator::opcodeWidth(), operation(), DCMFUResourceConflictDetector::operationID(), ReservationTableFUResourceConflictDetector::operationID(), HDB::FUArchitecture::operator==(), PlatformIntegrator::parseDataMemories(), HDB::FUArchitecture::portDirection(), ProgrammabilityValidator::printConnection(), printLatexFunctionUnitDescription(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), saveState(), DataDependenceGraph::setMachine(), EntryKeyDataFunctionUnit::toString(), FUPortImplementationDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), FUImplementationDialog::update(), TTAMachine::FUPort::updateBindingString(), FUDialog::updateOperationList(), GCUDialog::updateOperationList(), TDGen::writeBackendCode(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), TDGen::writeInstrInfo(), and TTAMachine::PipelineElement::~PipelineElement().
operationLowercase()
HWOperation * TTAMachine::FunctionUnit::operationLowercase (const std::string & name) const virtual
Returns operation by the given name.
The requested operation must exist, otherwise assertion fails.
Parameters
name Name of the operation.
Returns
Operation by the given name which MUST be in lowercase.
Exceptions
InstanceNotFound If an operation is not found by the given name.
Definition at line 378 of file FunctionUnit.cc.
{
    OperationTable::const_iterator iter = operations_.begin();
    while (iter != operations_.end()) {
        if ((*iter)->name() == name) {
            return *iter;
        }
        iter++;
    }
    string procName = "FunctionUnit::operation";
    throw InstanceNotFound(
        __FILE__, __LINE__, procName,"Operation not found:" + name );
}
References TTAMachine::Component::name(), and operations_.
Referenced by InputFUBroker::allAvailableResources(), MachineConnectivityCheck::busConnectedToFU(), and operation().
operationNames()
void TTAMachine::FunctionUnit::operationNames (TCETools::CIStringSet & opNames) const virtual
Adds FUs operations to the set given as a parameter.
Definition at line 428 of file FunctionUnit.cc.
{
    OperationTable::const_iterator iter = operations_.begin();
    while (iter != operations_.end()) {
        opNames.insert((*iter)->name());
        ++iter;
    }
}
References operations_.
Referenced by MinimalOpSetCheck::buildMinimalOpSet(), MinimalOpSetCheck::check(), MinimalOpSetCheck::check(), MinimalOpSetCheck::checkWithIgnore(), and MinimalOpSetCheck::missingOperations().
operationPort() [1/2]
FUPort * TTAMachine::FunctionUnit::operationPort (const std::string & name) const virtual
Returns an operation port by the given name.
Operation port is a port which can be read or written by an operation.
Parameters
name Name of the port.
Returns
The requested port.
Exceptions
InstanceNotFound If the requested port does not exist.
Definition at line 224 of file FunctionUnit.cc.
{
    Port* port = Unit::port(name);
    FUPort* fuPort = dynamic_cast<FUPort*>(port);
    if (fuPort == NULL) {
        const string procName = "FunctionUnit::operationPort";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    return fuPort;
}
References TTAMachine::Component::name(), port(), and TTAMachine::Unit::port().
Referenced by HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), VectorLSGenerator::addOperation(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), MachineValidator::checkFUConnections(), FullyConnectedCheck::connectControlUnit(), ADFCombiner::connectVectorLSU(), GCUFactory::createEditPart(), POMDisassembler::createFUPort(), OpsetDialog::createOperation(), createTerminalFUPort(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), ProGe::NetlistGenerator::findCorrespondingPort(), FullyConnectedCheck::fix(), MinimalOpSetCheck::fix(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), TTAMachine::PortGuard::loadState(), TTAMachine::HWOperation::loadState(), OperationDialog::onBindOperand(), GCUDialog::onEditPort(), OperationDialog::onOperandSelection(), HDB::FUArchitecture::operator==(), HDB::FUArchitecture::portDirection(), PlatformIntegrator::readLsuParameters(), ReservationTable::ReservationTable(), FUDialog::selectedPort(), FUGuardDialog::selectedPort(), MachineInfo::triggerIndex(), FUImplementationDialog::update(), OperationDialog::updateOperandList(), and FUDialog::updatePortList().
operationPort() [2/2]
FUPort * TTAMachine::FunctionUnit::operationPort (int index) const virtual
Returns an operation port by the given index.
Operation port is a port which can be read or written by an operation.
Parameters
index The index.
Returns
The port found by the given index.
Exceptions
OutOfRange If the given index is less than 0 or greater or equal to the number of operation ports.
Definition at line 245 of file FunctionUnit.cc.
{
    int portCount = this->portCount();
    int current(-1);
    for (int i = 0; i < portCount; i++) {
        Port* port = Unit::port(i);
        if (dynamic_cast<FUPort*>(port) != NULL) {
            current++;
            if (current == index) {
                return dynamic_cast<FUPort*>(port);
            }
        }
    }
    const string procName = "FunctionUnit::operandPort";
    throw OutOfRange(__FILE__, __LINE__, procName);
}
References port(), TTAMachine::Unit::port(), and TTAMachine::Unit::portCount().
operationPortCount()
int TTAMachine::FunctionUnit::operationPortCount () const virtual
Returns the number of port used for inputs and outputs of operations.
Control unit may contain also ports for special registers. Those ports are ignored by this method.
Returns
The number of operation ports.
Definition at line 182 of file FunctionUnit.cc.
{
    int portCount = this->portCount();
    int opCount = 0;
    for (int i = 0; i < portCount; i++) {
        Port* port = Unit::port(i);
        if (dynamic_cast<FUPort*>(port) != NULL) {
            opCount++;
        }
    }
    return opCount;
}
References port(), TTAMachine::Unit::port(), and TTAMachine::Unit::portCount().
Referenced by HDB::HDBManager::addFUArchitecture(), ProGe::NetlistGenerator::addGCUToNetlist(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), MachineValidator::checkFUConnections(), FullyConnectedCheck::connectControlUnit(), ADFCombiner::connectVectorLSU(), GCUFactory::createEditPart(), OpsetDialog::createOperation(), InterpolatingFUEstimator::createSearch(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), FullyConnectedCheck::fix(), MinimalOpSetCheck::fix(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), PlatformIntegrator::readLsuParameters(), ReservationTable::ReservationTable(), TTAMachine::ControlUnit::specialRegisterPortCount(), and MachineInfo::triggerIndex().
orderNumber()
int TTAMachine::FunctionUnit::orderNumber () const virtual
Returns the order number of the FU.
In certain architectures (Cell SPU) the "relative order" of the function units matters when it comes to accessing same register by multiple operations in the same cycle.
This method returns number indicating possition of the FU in the ADF file. Alows putting the FU into the order in the instruction.
Definition at line 915 of file FunctionUnit.cc.
{
    return orderNumber_;
}
References orderNumber_.
Referenced by saveState().
pipelineElement() [1/2]
PipelineElement * TTAMachine::FunctionUnit::pipelineElement (const std::string & name) const virtual
Returns the pipeline element which has the given name.
Parameters
name Name of the pipeline element.
Returns
The pipeline element which has the given name, or NULL If there is no pipeline element by the given name.
Definition at line 561 of file FunctionUnit.cc.
{
    PipelineElementTable::const_iterator iter = pipelineElements_.begin();
    while (iter != pipelineElements_.end()) {
        if ((*iter)->name() == name) {
            return *iter;
        }
        iter++;
    }
    return NULL;
}
References TTAMachine::Component::name(), and pipelineElements_.
pipelineElement() [2/2]
PipelineElement * TTAMachine::FunctionUnit::pipelineElement (int index) const virtual
Returns a pipeline element by the given index.
The index must be greater or equal to 0 and less than the number of pipeline elements in the function unit.
Parameters
index The index.
Returns
A pipeline element by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 523 of file FunctionUnit.cc.
{
    if (index < 0 || index >= pipelineElementCount()) {
        string procName = "FunctionUnit::pipelineElement";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return pipelineElements_[index];
}
References pipelineElementCount(), and pipelineElements_.
Referenced by HDB::HDBManager::addFUArchitecture(), TTAMachine::ExecutionPipeline::addPipelineElement(), cleanup(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), HDBToHtml::fuArchToHtml(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), HDB::FUArchitecture::operator==(), TTAMachine::ExecutionPipeline::pipelineElement(), ReservationTable::ReservationTable(), and OperationDialog::updateResourceGrid().
pipelineElementCount()
int TTAMachine::FunctionUnit::pipelineElementCount () const virtual
Returns the number of pipeline elements in the function unit.
Returns
The number of pipeline elements.
Definition at line 507 of file FunctionUnit.cc.
{
    return pipelineElements_.size();
}
References pipelineElements_.
Referenced by HDB::HDBManager::addFUArchitecture(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), HDBToHtml::fuArchToHtml(), ImplementationTester::fuFullyPipelined(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), needsConflictDetection(), HDB::FUArchitecture::operator==(), pipelineElement(), ReservationTable::ReservationTable(), and OperationDialog::updateResourceGrid().
port() [1/2]
BaseFUPort * TTAMachine::FunctionUnit::port (const std::string & name) const virtual
Returns the requested port.
Parameters
name Name of the port.
Returns
The requested port.
Exceptions
InstanceNotFound If there is no port by the given name.
Reimplemented from TTAMachine::Unit.
Definition at line 145 of file FunctionUnit.cc.
{
    if (!hasPort(name)) {
        string procName = "FunctionUnit::port";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    Port* port = Unit::port(name);
    BaseFUPort* fuPort = dynamic_cast<BaseFUPort*>(port);
    assert(fuPort != NULL);
    return fuPort;
}
References assert, TTAMachine::Unit::hasPort(), TTAMachine::Component::name(), port(), and TTAMachine::Unit::port().
Referenced by ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), CostDatabase::buildFunctionUnits(), MachineStateBuilder::buildMachineState(), cleanupGuards(), SimulatorFrontend::compareState(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::copyGuards(), FUFactory::createEditPart(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), FUGen::createMandatoryPorts(), FUGen::createOutputPipeline(), FUGen::createPortPipeline(), InterpolatingFUEstimator::createSearch(), FUGen::createShadowRegisters(), FUTestbenchGenerator::createStimulusArrays(), FUTestbenchGenerator::createTbInstantiation(), ProximFUDetailsCmd::Do(), AddFUImplementationCmd::Do(), UniversalFunctionUnit::ensureInputPorts(), UniversalFunctionUnit::ensureOutputPorts(), InfoPortsCommand::execute(), ProgrammabilityValidator::findConnections(), findFUPort(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findPort(), BasicBlockScheduler::findTriggerFromUnit(), ProgramOperation::findTriggerFromUnit(), MachineConnectivityCheck::fromRfConnected(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), HDBToHtml::fuArchToHtml(), MachineResourceManager::functionUnitPortResource(), CompiledSimCodeGenerator::fuOutputPorts(), TTAMachine::FUPort::FUPort(), CompiledSimulation::FUPortValue(), hasOperationPort(), TTAProgram::TPEFResourceUpdater::initCache(), ExecutionPipelineResource::isAvailable(), DefaultICGenerator::isGcuPort(), TTAMachine::FUPort::loadStateWithoutReferences(), MachineAnalysis::MachineAnalysis(), AddFUFromHDBDialog::onAdd(), FUImplementationDialog::onArchPortActivation(), FUImplementationDialog::onEditArchitecturePort(), AddWatchDialog::onFUChoice(), FUGuardDialog::onFUChoice(), FUArchitectureDialog::onOK(), FUPortDialog::onOK(), SRPortDialog::onOK(), operationPort(), operationPort(), operationPortCount(), FUTestbenchGenerator::parseFuPorts(), port(), UniversalFunctionUnit::portCountWithWidth(), UniversalFunctionUnit::portWithWidth(), TTAMachine::ControlUnit::removePort(), GCUDialog::selectedPort(), TTAMachine::ControlUnit::setReturnAddressPort(), TTAMachine::FUPort::setTriggering(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), TTAMachine::ControlUnit::specialRegisterPort(), TTAMachine::ControlUnit::specialRegisterPort(), MachineConnectivityCheck::toRfConnected(), FUGuardDialog::TransferDataToWindow(), triggerPort(), ProximPortWindow::update(), FUArchitectureDialog::update(), GCUDialog::updatePortList(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeFUCntrlSignals(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
port() [2/2]
BaseFUPort * TTAMachine::FunctionUnit::port (int index) const virtual
Returns port by the given index.
The index must be between 0 and the return value of numberOfPorts() - 1.
Parameters
index Index.
Returns
The port found by the given index.
Exceptions
OutOfRange If the given index is out of range.
Reimplemented from TTAMachine::Unit.
Definition at line 167 of file FunctionUnit.cc.
{
    // the out of range test is already done in Unit::Port,
    // no need to do it here also.
    return static_cast<BaseFUPort*>(Unit::port(index));
}
References TTAMachine::Unit::port().
saveState()
ObjectState * TTAMachine::FunctionUnit::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::Unit.
Reimplemented in TTAMachine::ControlUnit.
Definition at line 677 of file FunctionUnit.cc.
{
    ObjectState* fuState = Unit::saveState();
    fuState->setName(OSNAME_FU);
    fuState->setAttribute(FunctionUnit::OSKEY_ORDER_NUMBER, orderNumber());
    // set address space
    if (addressSpace_ != NULL) {
        fuState->setAttribute(OSKEY_AS, addressSpace_->name());
    }
    // add operations
    for (int i = 0; i < operationCount(); i++) {
        HWOperation* operation = this->operation(i);
        fuState->addChild(operation->saveState());
    }
    return fuState;
}
References ObjectState::addChild(), addressSpace_, TTAMachine::Component::name(), operation(), operationCount(), orderNumber(), OSKEY_AS, OSKEY_ORDER_NUMBER, OSNAME_FU, TTAMachine::HWOperation::saveState(), TTAMachine::Unit::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by copy(), AddFUFromHDBDialog::onAdd(), FUDialog::onAddOperation(), FUDialog::onEditOperation(), and TTAMachine::ControlUnit::saveState().
setAddressSpace()
void TTAMachine::FunctionUnit::setAddressSpace (AddressSpace * as) virtual
Adds an address space which can be accessed by the function unit.
Parameters
as Address space which can be accessed.
Exceptions
IllegalRegistration If the given address space and the function unit are not registrered to the same machine.
Definition at line 594 of file FunctionUnit.cc.
{
    if (as != NULL) {
        ensureRegistration(*as);
    }
    addressSpace_ = as;
}
References addressSpace_, and TTAMachine::Component::ensureRegistration().
Referenced by ADFCombiner::addFunctionUnits(), BlocksGCU::BlocksGCU(), BlocksLSU::BlocksLSU(), UniversalMachine::construct(), PasteComponentCmd::Do(), VectorLSGenerator::explore(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), loadState(), GCUDialog::onOK(), FUDialog::onSetAddressSpace(), MachineResourceModifier::percentualFUIncrease(), and TTAMachine::AddressSpace::unsetMachine().
setName()
void TTAMachine::FunctionUnit::setName (const std::string & name) virtual
Sets the name of the function unit.
Parameters
name Name of the function unit.
Exceptions
ComponentAlreadyExists If a function unit with the given name is already in the same machine.
InvalidName If the given name is not a valid component name.
Reimplemented from TTAMachine::Component.
Definition at line 118 of file FunctionUnit.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->functionUnitNavigator().hasItem(name) ||
            (machine()->controlUnit() != NULL &&
             machine()->controlUnit()->name() == name)) {
            string procName = "FunctionUnit::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by ADFCombiner::addFunctionUnits(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), AddFUFromHDBDialog::onAdd(), FUDialog::onOK(), GCUDialog::onOK(), and MachineResourceModifier::percentualFUIncrease().
setOrderNumber()
void TTAMachine::FunctionUnit::setOrderNumber (int number) virtual
Sets order number of the FU.
In certain architectures (Cell SPU) the "relative order" of the function units matters when it comes to accessing same register by multiple operations in the same cycle.
This method sets number indicating possition of the FU in the ADF file.
Definition at line 928 of file FunctionUnit.cc.
{
    orderNumber_ = number;
}
References orderNumber_.
Referenced by loadStateWithoutReferences().
triggerPort()
BaseFUPort * TTAMachine::FunctionUnit::triggerPort () const virtual
Returns triggering port if found. Otherwise returns NULL.
Definition at line 267 of file FunctionUnit.cc.
{
    int portc = portCount();
    for (int i = 0; i < portc; i++) {
        if (port(i)->isTriggering()) {
            return port(i);
        }
    }
    return NULL;
}
References port(), and TTAMachine::Unit::portCount().
Referenced by ProGe::NetlistGenerator::addGCUToNetlist(), DefaultICGenerator::addICToNetlist(), ExecutionPipelineBroker::isMoveTrigger(), DefaultDecoderGenerator::writeControlRegisterMappings(), and DefaultICGenerator::writeInterconnectionNetwork().
unsetMachine()
void TTAMachine::FunctionUnit::unsetMachine () virtual
Removes registration of the function unit from its current machine.
Reimplemented from TTAMachine::Unit.
Reimplemented in TTAMachine::ControlUnit.
Definition at line 648 of file FunctionUnit.cc.
{
    if (machine() == NULL) {
        return;
    }
    cleanupGuards();
    Machine* mach = machine();
    unsetMachineDerived();
    mach->removeFunctionUnit(*this);
}
References cleanupGuards(), TTAMachine::Component::machine(), TTAMachine::Machine::removeFunctionUnit(), and unsetMachineDerived().
Referenced by AddFUArchFromADFCmd::Do(), MinimalOpSetCheck::fix(), and ~FunctionUnit().
unsetMachineDerived()
void TTAMachine::FunctionUnit::unsetMachineDerived () protected
Removes function unit part of a derived class from machine.
Definition at line 665 of file FunctionUnit.cc.
{
    addressSpace_ = NULL;
    Unit::unsetMachine();
}
References addressSpace_, and TTAMachine::Unit::unsetMachine().
Referenced by TTAMachine::ControlUnit::unsetMachine(), and unsetMachine().
Member Data Documentation
addressSpace_
AddressSpace* TTAMachine::FunctionUnit::addressSpace_ private
Address space used by the function unit.
Definition at line 145 of file FunctionUnit.hh.
Referenced by addressSpace(), hasAddressSpace(), loadStateWithoutReferences(), saveState(), setAddressSpace(), and unsetMachineDerived().
operations_
OperationTable TTAMachine::FunctionUnit::operations_ private
Contains all the operations of the function unit.
Definition at line 139 of file FunctionUnit.hh.
Referenced by addOperation(), deleteAllOperations(), deleteOperation(), hasOperationLowercase(), operation(), operationCount(), operationLowercase(), and operationNames().
orderNumber_
int TTAMachine::FunctionUnit::orderNumber_ private
Number indicating possition of the FU in the ADF file. Alows putting the FU into the order in the instruction.
Definition at line 149 of file FunctionUnit.hh.
Referenced by orderNumber(), and setOrderNumber().
OSKEY_AS
const string TTAMachine::FunctionUnit::OSKEY_AS = "as" static
ObjectState attribute key for name of the address space.
Definition at line 119 of file FunctionUnit.hh.
Referenced by ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), loadState(), and saveState().
OSKEY_ORDER_NUMBER
const string TTAMachine::FunctionUnit::OSKEY_ORDER_NUMBER = "order_no" static
ObjectState attribute key for FU order number name.
Definition at line 121 of file FunctionUnit.hh.
Referenced by ADFSerializer::functionUnitToMachine(), loadStateWithoutReferences(), and saveState().
OSNAME_FU
const string TTAMachine::FunctionUnit::OSNAME_FU = "fu" static
ObjectState name for function unit.
Definition at line 117 of file FunctionUnit.hh.
Referenced by ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), ADFSerializer::functionUnitToMachine(), TTAMachine::Machine::loadState(), and saveState().
pipelineElements_
PipelineElementTable TTAMachine::FunctionUnit::pipelineElements_ private
Contains all the pipeline elements of the function unit.
Definition at line 142 of file FunctionUnit.hh.
Referenced by addPipelineElement(), deletePipelineElement(), hasPipelineElement(), pipelineElement(), pipelineElement(), and pipelineElementCount().
The documentation for this class was generated from the following files:
FunctionUnit.hh
FunctionUnit.cc