OpenASIP: BitMatrix Class Reference
BitMatrix Class Reference
#include <BitMatrix.hh>
Public Member Functions
BitMatrix (int width, int height, bool initialValue)
BitMatrix (const BitMatrix &another)
virtual ~BitMatrix ()
bool bitAt (int column, int row) const
void setBit (int column, int row, bool value)
void setAllToZero ()
void setAllToOne ()
void shiftLeft ()
void orWith (const BitMatrix &another)
bool conflictsWith (const BitMatrix &another) const
int rowCount () const
int columnCount () const
std::string toString () const
std::string toDotString () const
bool operator== (const BitMatrix &other) const
bool operator< (const BitMatrix &rightHand) const
Private Types
typedef unsigned RowWord
Private Attributes
RowWord * matrix_
const int rows_
const int columns_
const int wordsPerRow_
Detailed Description
Models a bit matrix.
The implementation should be quite efficient. It uses natural words of the machine to store the bits to provide fast logical operations on larger bit chunks at the same time. Especially functions such as fully ORing and ANDing two bit matrices should be quite efficient. Checking a single matrix element is couple of cycles slower than the naive implementation of storing one bit per word. The main methods are inline non-virtual methods for fastest possible access.
Definition at line 49 of file BitMatrix.hh.
Member Typedef Documentation
RowWord
typedef unsigned BitMatrix::RowWord private
Definition at line 73 of file BitMatrix.hh.
Constructor & Destructor Documentation
BitMatrix() [1/2]
BitMatrix::BitMatrix (int width, int height, bool initialValue)
Builds a bit matrix of given size and default content.
Parameters
width The width of the matrix.
height The height of the matrix.
initialValue The initial value for elements.
Definition at line 46 of file BitMatrix.cc.
                                                             :
    rows_(height), columns_(width), wordsPerRow_(
        static_cast<int>(
            std::ceil(columns_ / float(sizeof(RowWord) * BYTE_BITWIDTH)))) {
    matrix_ = new RowWord[rows_ * wordsPerRow_];
    RowWord word = 0;
    if (initialValue) {
        word = ~word;
    }
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < wordsPerRow_; ++col) {
            matrix_[row * wordsPerRow_ + col] = word;
        }
    }
}
References matrix_, rows_, and wordsPerRow_.
BitMatrix() [2/2]
BitMatrix::BitMatrix (const BitMatrix & another)
Copy constructor.
Definition at line 75 of file BitMatrix.cc.
                                             :
    rows_(another.rows_), columns_(another.columns_),
    wordsPerRow_(another.wordsPerRow_) {
    matrix_ = new RowWord[rows_ * wordsPerRow_];
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < wordsPerRow_; ++col) {
            matrix_[row * wordsPerRow_ + col] =
                another.matrix_[row * wordsPerRow_ + col];
        }
    }
}
References matrix_, rows_, and wordsPerRow_.
~BitMatrix()
BitMatrix::~BitMatrix () virtual
Frees the bit matrix content storage.
Definition at line 67 of file BitMatrix.cc.
                      {
    delete[] matrix_;
    matrix_ = NULL;
}
References matrix_.
Member Function Documentation
bitAt()
bool BitMatrix::bitAt (int column, int row) const
Referenced by CollisionMatrix::isCollision(), operator<(), operator==(), toDotString(), and toString().
columnCount()
int BitMatrix::columnCount () const
Referenced by CollisionMatrix::CollisionMatrix(), FUCollisionMatrixIndex::FUCollisionMatrixIndex(), and ReservationTable::ReservationTable().
conflictsWith()
bool BitMatrix::conflictsWith (const BitMatrix & another) const
operator<()
bool BitMatrix::operator< (const BitMatrix & rightHand) const
Returns true in case the given matrix is "smaller" than this one.
The one that has the first non-equal non-zero matrix element is considered larger. That is, the matrix is considered as a bit string. This is an arbitrary ordering constraint to make it possible to store BitMatrices in sets.
Parameters
rightHand The right hand side of the comparison.
Returns
True in case the the right hand is considered larger.
Definition at line 191 of file BitMatrix.cc.
{
    for (int row = 0; row < rows_; ++row) {
        for (int column = 0; column < columns_; ++column) {
            bool left = bitAt(column, row);
            bool right = rightHand.bitAt(column, row);
            if (left != right)
                return static_cast<int>(left) < static_cast<int>(right);
        }
    }
    // they are equal
    return false;
}
References bitAt(), columns_, and rows_.
operator==()
bool BitMatrix::operator== (const BitMatrix & other) const
Compares two bit matrices..
Parameters
other The RT to compare to.
Returns
True in case all values in both reservation tables are equal and the dimensions are the same.
Definition at line 143 of file BitMatrix.cc.
{
    if (other.rows_ != rows_ || other.columns_ != columns_)
        return false;
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < columns_; ++col) {
            if (other.bitAt(col, row) != bitAt(col, row))
                return false;
        }
    }
    return true;
}
References bitAt(), columns_, and rows_.
orWith()
void BitMatrix::orWith (const BitMatrix & another)
Referenced by FUFiniteStateAutomaton::resolveState().
rowCount()
int BitMatrix::rowCount () const
Referenced by CollisionMatrix::CollisionMatrix(), and FUCollisionMatrixIndex::FUCollisionMatrixIndex().
setAllToOne()
void BitMatrix::setAllToOne ()
Sets all bits to one.
Definition at line 106 of file BitMatrix.cc.
                       {
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < wordsPerRow_; ++col) {
            matrix_[row * wordsPerRow_ + col] = ~0;
        }
    }
}
References matrix_, rows_, and wordsPerRow_.
setAllToZero()
void BitMatrix::setAllToZero ()
Sets all bits to zero.
Definition at line 93 of file BitMatrix.cc.
{
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < wordsPerRow_; ++col) {
            matrix_[row * wordsPerRow_ + col] = 0;
        }
    }
}
References matrix_, rows_, and wordsPerRow_.
Referenced by DCMFUResourceConflictDetector::reset(), and ReservationTableFUResourceConflictDetector::reset().
setBit()
void BitMatrix::setBit (int column, int row, bool value)
Referenced by CollisionMatrix::CollisionMatrix(), and ReservationTable::ReservationTable().
shiftLeft()
void BitMatrix::shiftLeft ()
Referenced by FUFiniteStateAutomaton::resolveState().
toDotString()
std::string BitMatrix::toDotString () const
Returns a textual description of the matrix suitable to be used as a dot edge/node label.
Returns
A string describing the matrix.
Definition at line 164 of file BitMatrix.cc.
{
    std::string theString = "";
    for (int row = 0; row < rows_; ++row) {
        for (int column = 0; column < columns_;
             ++column) {
            if (bitAt(column, row))
                theString += "1 ";
            else
                theString += "0 ";
        }
        theString += "\\n";
    }
    return theString;
}
References bitAt(), columns_, and rows_.
toString()
std::string BitMatrix::toString () const
ASCII representation of the bit matrix.
For debugging and testing.
Returns
A string representation of the matrix.
Definition at line 124 of file BitMatrix.cc.
{
    std::ostringstream s;
    for (int row = 0; row < rows_; ++row) {
        for (int col = 0; col < columns_; ++col) {
            s << bitAt(col, row) << " ";
        }
        s << std::endl;
    }
    return s.str();
}
References bitAt(), columns_, and rows_.
Member Data Documentation
columns_
const int BitMatrix::columns_ private
Definition at line 79 of file BitMatrix.hh.
Referenced by operator<(), operator==(), toDotString(), and toString().
matrix_
RowWord* BitMatrix::matrix_ private
Definition at line 75 of file BitMatrix.hh.
Referenced by BitMatrix(), BitMatrix(), setAllToOne(), setAllToZero(), and ~BitMatrix().
rows_
const int BitMatrix::rows_ private
Definition at line 77 of file BitMatrix.hh.
Referenced by BitMatrix(), BitMatrix(), operator<(), operator==(), setAllToOne(), setAllToZero(), toDotString(), and toString().
wordsPerRow_
const int BitMatrix::wordsPerRow_ private
Definition at line 81 of file BitMatrix.hh.
Referenced by BitMatrix(), BitMatrix(), setAllToOne(), and setAllToZero().
The documentation for this class was generated from the following files:
BitMatrix.hh
BitMatrix.cc