OpenASIP: FullyConnectBussesCmd Class Reference
FullyConnectBussesCmd Class Reference
#include <FullyConnectBussesCmd.hh>
Public Member Functions
FullyConnectBussesCmd ()
virtual ~FullyConnectBussesCmd ()
virtual bool Do ()
virtual int id () const
virtual FullyConnectBussesCmd * create () const
virtual bool isEnabled ()
virtual std::string shortName () const
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for connecting all sockets to all busses.
Definition at line 49 of file FullyConnectBussesCmd.hh.
Constructor & Destructor Documentation
FullyConnectBussesCmd()
FullyConnectBussesCmd::FullyConnectBussesCmd ()
The Constructor.
Definition at line 60 of file FullyConnectBussesCmd.cc.
                                            :
    EditorCommand(ProDeConstants::CMD_NAME_FULLY_CONNECT_BUSSES) {
}
Referenced by create().
~FullyConnectBussesCmd()
FullyConnectBussesCmd::~FullyConnectBussesCmd () virtual
The Destructor.
Definition at line 68 of file FullyConnectBussesCmd.cc.
{}
Member Function Documentation
create()
FullyConnectBussesCmd * FullyConnectBussesCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 108 of file FullyConnectBussesCmd.cc.
{
    return new FullyConnectBussesCmd();
}
References FullyConnectBussesCmd().
Do()
bool FullyConnectBussesCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 77 of file FullyConnectBussesCmd.cc.
{
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    Machine& machine = *model->getMachine();
    FullyConnectedCheck checker;
    checker.fix(machine);
    model->notifyObservers();
    return true;
}
References assert, FullyConnectedCheck::fix(), Model::getMachine(), machine, Model::notifyObservers(), Model::pushToStack(), and EditorCommand::view().
id()
int FullyConnectBussesCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 99 of file FullyConnectBussesCmd.cc.
{
    return ProDeConstants::COMMAND_FULLY_CONNECT_BUSSES;
}
References ProDeConstants::COMMAND_FULLY_CONNECT_BUSSES.
isEnabled()
bool FullyConnectBussesCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 130 of file FullyConnectBussesCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    wxView* view = manager->GetCurrentView();
    if (view == NULL) {
    return false;
    }
    Model* model = dynamic_cast<MDFDocument*>(
        view->GetDocument())->getModel();
    if (model == NULL) {
        return false;
    }
    FullyConnectedCheck checker;
    MachineCheckResults results;
    if (!checker.check(*model->getMachine(), results)) {
        return checker.canFix(*model->getMachine());
    } else {
        return false;
    }
}
References FullyConnectedCheck::canFix(), FullyConnectedCheck::check(), Model::getMachine(), and EditorCommand::view().
shortName()
string FullyConnectBussesCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 117 of file FullyConnectBussesCmd.cc.
{
    return ProDeConstants::CMD_SNAME_FULLY_CONNECT_BUSSES;
}
References ProDeConstants::CMD_SNAME_FULLY_CONNECT_BUSSES.
The documentation for this class was generated from the following files:
FullyConnectBussesCmd.hh
FullyConnectBussesCmd.cc