OpenASIP: ProGe::CUOpcodeGenerator Class Reference
ProGe::CUOpcodeGenerator Class Reference
#include <CUOpcodeGenerator.hh>
Public Types
typedef std::string OperationType
typedef size_t EncodingType
typedef std::map< OperationType, EncodingType, TCEString::ICLess > OperationEncodingMapType
Public Member Functions
CUOpcodeGenerator (const TTAMachine::Machine &mach, const std::string &entityName="tta0")
virtual ~CUOpcodeGenerator ()
OperationEncodingMapType encodings () const
size_t encoding (const std::string &operName) const
size_t opcodeWidth () const
void generateOpcodePackage (HDL language, std::ofstream &stream) const
Static Public Member Functions
static size_t gcuOpcodeWidth (const TTAMachine::Machine &mach)
Private Member Functions
CUOpcodeGenerator ()
void WriteVhdlOpcodePackage (const OperationEncodingMapType &encodings, std::ofstream &stream) const
void WriteVerilogOpcodePackage (const OperationEncodingMapType &encodings, std::ofstream &stream) const
Private Attributes
const TTAMachine::Machine * mach_
const std::string entityStr_
Detailed Description
Class that for given ADF generates encodings for Global Control Unit and RTL package that holds encoding information for CU RTL source codes.
Definition at line 57 of file CUOpcodeGenerator.hh.
Member Typedef Documentation
EncodingType
typedef size_t ProGe::CUOpcodeGenerator::EncodingType
Definition at line 61 of file CUOpcodeGenerator.hh.
OperationEncodingMapType
typedef std::map<OperationType, EncodingType, TCEString::ICLess> ProGe::CUOpcodeGenerator::OperationEncodingMapType
Definition at line 63 of file CUOpcodeGenerator.hh.
OperationType
typedef std::string ProGe::CUOpcodeGenerator::OperationType
Definition at line 60 of file CUOpcodeGenerator.hh.
Constructor & Destructor Documentation
CUOpcodeGenerator() [1/2]
ProGe::CUOpcodeGenerator::CUOpcodeGenerator (const TTAMachine::Machine & mach, const std::string & entityName = "tta0")
Definition at line 55 of file CUOpcodeGenerator.cc.
    : mach_(&mach), entityStr_(entityName) {}
~CUOpcodeGenerator()
ProGe::CUOpcodeGenerator::~CUOpcodeGenerator () virtual
Definition at line 61 of file CUOpcodeGenerator.cc.
{}
CUOpcodeGenerator() [2/2]
ProGe::CUOpcodeGenerator::CUOpcodeGenerator () private
Definition at line 59 of file CUOpcodeGenerator.cc.
: mach_(NULL), entityStr_() {}
Member Function Documentation
encoding()
size_t ProGe::CUOpcodeGenerator::encoding (const std::string & operName) const
Definition at line 84 of file CUOpcodeGenerator.cc.
{
    OperationEncodingMapType encMap = encodings();
    if (encMap.count(operName)) {
        return encMap.at(operName);
    } else {
        THROW_EXCEPTION(
            InstanceNotFound, "CU does not have operation" + operName + ".");
    }
}
References encodings(), and THROW_EXCEPTION.
Referenced by encodings(), and DefaultDecoderGenerator::opcode().
encodings()
CUOpcodeGenerator::OperationEncodingMapType ProGe::CUOpcodeGenerator::encodings () const
Definition at line 67 of file CUOpcodeGenerator.cc.
{
    assert(mach_ != NULL);
    MachineInfo::OperationSet gcuOps =
        MachineInfo::getOpset(*(mach_->controlUnit()));
    size_t encoding = 0;
    OperationEncodingMapType encMap;
    MachineInfo::OperationSet::iterator it;
    for (it = gcuOps.begin(); it != gcuOps.end(); it++) {
        encMap.insert(make_pair(StringTools::stringToLower(*it), encoding));
        encoding++;
    }
    return encMap;
}
References assert, TTAMachine::Machine::controlUnit(), encoding(), MachineInfo::getOpset(), mach_, and StringTools::stringToLower().
Referenced by encoding(), generateOpcodePackage(), WriteVerilogOpcodePackage(), and WriteVhdlOpcodePackage().
gcuOpcodeWidth()
size_t ProGe::CUOpcodeGenerator::gcuOpcodeWidth (const TTAMachine::Machine & mach) static
Definition at line 140 of file CUOpcodeGenerator.cc.
{
    const TTAMachine::ControlUnit* gcu = mach.controlUnit();
    size_t opCount = gcu->operationCount();
    if (opCount == 0) {
        return 0;
    } else {
        return std::max(MathTools::requiredBits(opCount - 1), 1);
    }
}
References TTAMachine::Machine::controlUnit(), TTAMachine::FunctionUnit::operationCount(), and MathTools::requiredBits().
Referenced by DefaultICDecoderGenerator::generate(), and opcodeWidth().
generateOpcodePackage()
void ProGe::CUOpcodeGenerator::generateOpcodePackage (HDL language, std::ofstream & stream) const
Definition at line 114 of file CUOpcodeGenerator.cc.
{
    OperationEncodingMapType gcuEncodings = encodings();
    // Add dummy operations for missing CALL and JUMP operations since ifetch
    // templates refers to them.
    gcuEncodings.insert(
        make_pair(OperationType("call"), gcuEncodings.size()));
    gcuEncodings.insert(
        make_pair(OperationType("jump"), gcuEncodings.size()));
    if (language == VHDL) {
        WriteVhdlOpcodePackage(gcuEncodings, stream);
    } else if (language == Verilog) {
        WriteVerilogOpcodePackage(gcuEncodings, stream);
    } else {
        assert(false && "Unsupported HDL.");
    }
}
References assert, encodings(), ProGe::Verilog, ProGe::VHDL, WriteVerilogOpcodePackage(), and WriteVhdlOpcodePackage().
Referenced by ProGe::ProcessorGenerator::generateGCUOpcodesPackage().
opcodeWidth()
size_t ProGe::CUOpcodeGenerator::opcodeWidth () const
Definition at line 98 of file CUOpcodeGenerator.cc.
{
    return CUOpcodeGenerator::gcuOpcodeWidth(*mach_);
}
References gcuOpcodeWidth(), and mach_.
WriteVerilogOpcodePackage()
void ProGe::CUOpcodeGenerator::WriteVerilogOpcodePackage (const OperationEncodingMapType & encodings, std::ofstream & stream) const private
Definition at line 173 of file CUOpcodeGenerator.cc.
{
    if (encodings.empty()) {
        return;
    }
    OperationEncodingMapType::const_iterator it;
    for (it = encodings.begin(); it != encodings.end(); it++) {
        stream << "parameter IFE_" << StringTools::stringToUpper(it->first)
               << "=" << Conversion::toString(it->second);
        if (it != --encodings.end()) {
            stream << "," << endl;
        } else {
            stream << endl;
        }
    }
}
References encodings(), StringTools::stringToUpper(), and Conversion::toString().
Referenced by generateOpcodePackage().
WriteVhdlOpcodePackage()
void ProGe::CUOpcodeGenerator::WriteVhdlOpcodePackage (const OperationEncodingMapType & encodings, std::ofstream & stream) const private
Definition at line 154 of file CUOpcodeGenerator.cc.
{
    stream << "library IEEE;" << endl
           << "use IEEE.std_logic_1164.all;" << endl
           << endl
           << "package " + entityStr_ + "_gcu_opcodes is" << endl;
    OperationEncodingMapType::const_iterator it;
    for (it = encodings.begin(); it != encodings.end(); it++) {
        stream << "  constant IFE_" << StringTools::stringToUpper(it->first)
               << " : natural := " << Conversion::toString(it->second) << ";"
               << endl;
    }
    stream << "end " + entityStr_ + "_gcu_opcodes;" << endl;
}
References encodings(), entityStr_, StringTools::stringToUpper(), and Conversion::toString().
Referenced by generateOpcodePackage().
Member Data Documentation
entityStr_
const std::string ProGe::CUOpcodeGenerator::entityStr_ private
Definition at line 86 of file CUOpcodeGenerator.hh.
Referenced by WriteVhdlOpcodePackage().
mach_
const TTAMachine::Machine* ProGe::CUOpcodeGenerator::mach_ private
Definition at line 85 of file CUOpcodeGenerator.hh.
Referenced by encodings(), and opcodeWidth().
The documentation for this class was generated from the following files:
CUOpcodeGenerator.hh
CUOpcodeGenerator.cc