OpenASIP: SimulatorCmdLineOptions Class Reference
SimulatorCmdLineOptions Class Reference
#include <SimulatorCmdLineOptions.hh>
Public Member Functions
SimulatorCmdLineOptions ()
virtual ~SimulatorCmdLineOptions ()
virtual void printVersion () const
virtual void printHelp () const
bool debugMode ()
std::string scriptString ()
std::string machineFile ()
std::string programFile ()
SimulatorFrontend::SimulationType backendType ()
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Private Member Functions
SimulatorCmdLineOptions (const SimulatorCmdLineOptions &)
Copying not allowed.
SimulatorCmdLineOptions & operator= (const SimulatorCmdLineOptions &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line option class for Simulator.
Definition at line 45 of file SimulatorCmdLineOptions.hh.
Constructor & Destructor Documentation
SimulatorCmdLineOptions() [1/2]
SimulatorCmdLineOptions::SimulatorCmdLineOptions ()
Constructor.
Todo:
Use textgenerator in the help texts.
Definition at line 82 of file SimulatorCmdLineOptions.cc.
                                                 : CmdLineOptions("") {
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DEBUG_MODE, "starts simulator in debugging mode (default), "
            "use --no-debugmode to disable",
            SWS_DEBUG_MODE));
    addOption(
        new StringCmdLineOptionParser(
            SWL_EXECUTE_SCRIPT, "executes the given string as a script in the "
            "simulator control language script interpreter, "
            "e.g. -e \"stepi 10000\" executes simulation for 10000 cycles",
            SWS_EXECUTE_SCRIPT));
    addOption(
        new StringCmdLineOptionParser(
            SWL_MACHINE_TO_LOAD, "sets the machine file (.adf) to be loaded.",
            SWS_MACHINE_TO_LOAD));
    addOption(
        new StringCmdLineOptionParser(
            SWL_PROGRAM_TO_LOAD, "sets the program file to be loaded.",
            SWS_PROGRAM_TO_LOAD));
     addOption(
        new BoolCmdLineOptionParser(
            SWL_FAST_SIM, "uses the fast simulation engine.",
            SWS_FAST_SIM));
     addOption(
        new BoolCmdLineOptionParser(
            SWL_REMOTE_DBG, "connect to a remote debugging interface on an FPGA or ASIC.",
            SWS_REMOTE_DBG));
     addOption(
        new BoolCmdLineOptionParser(
            SWL_CUSTOM_DBG, "connect to a custom remote debugger (if implemented).",
            SWS_CUSTOM_DBG));
}
References CmdLineParser::addOption(), SWL_CUSTOM_DBG, SWL_DEBUG_MODE, SWL_EXECUTE_SCRIPT, SWL_FAST_SIM, SWL_MACHINE_TO_LOAD, SWL_PROGRAM_TO_LOAD, SWL_REMOTE_DBG, SWS_CUSTOM_DBG, SWS_DEBUG_MODE, SWS_EXECUTE_SCRIPT, SWS_FAST_SIM, SWS_MACHINE_TO_LOAD, SWS_PROGRAM_TO_LOAD, and SWS_REMOTE_DBG.
~SimulatorCmdLineOptions()
SimulatorCmdLineOptions::~SimulatorCmdLineOptions () virtual
Destructor.
Definition at line 124 of file SimulatorCmdLineOptions.cc.
{
}
SimulatorCmdLineOptions() [2/2]
SimulatorCmdLineOptions::SimulatorCmdLineOptions (const SimulatorCmdLineOptions &) private
Copying not allowed.
Member Function Documentation
backendType()
SimulatorFrontend::SimulationType SimulatorCmdLineOptions::backendType ()
Check what sort of simulation user asked for on the command line.
If no value is given in the parsed command line the "normal" simulation, i.e. the interpreted, non-compiled, version is returned.
Returns
type of TTA backend user wants
Definition at line 209 of file SimulatorCmdLineOptions.cc.
{
    bool wantCompiled = false;
    bool wantRemote = false;
    bool wantCustom = false;
    wantCompiled |= optionGiven(SWL_FAST_SIM);
    wantCompiled &= findOption(SWL_FAST_SIM)->isFlagOn();
    wantRemote |= optionGiven(SWL_REMOTE_DBG);
    wantRemote &= findOption(SWL_REMOTE_DBG)->isFlagOn();
    wantCustom |= optionGiven(SWL_CUSTOM_DBG);
    wantCustom &= findOption(SWL_CUSTOM_DBG)->isFlagOn();
    // TODO: no check for if user requests simultaneously several
    // versions of TTA backend. Start with the most picky one,
    // user probably notices it erroring out.
    if (wantCustom) return SimulatorFrontend::SIM_CUSTOM;
    if (wantRemote) return SimulatorFrontend::SIM_REMOTE;
    if (wantCompiled) return SimulatorFrontend::SIM_COMPILED;
    return SimulatorFrontend::SIM_NORMAL;
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), SimulatorFrontend::SIM_COMPILED, SimulatorFrontend::SIM_CUSTOM, SimulatorFrontend::SIM_NORMAL, SimulatorFrontend::SIM_REMOTE, SWL_CUSTOM_DBG, SWL_FAST_SIM, and SWL_REMOTE_DBG.
debugMode()
bool SimulatorCmdLineOptions::debugMode ()
Returns true if Simulator should be started in debugging mode.
If no value is given in the parsed command line, default one is returned.
Returns
True if Simulator should be started in debugging mode.
Definition at line 158 of file SimulatorCmdLineOptions.cc.
{
    if (!optionGiven(SWL_DEBUG_MODE)) {
        return true;
    }
    return findOption(SWL_DEBUG_MODE)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_DEBUG_MODE.
machineFile()
std::string SimulatorCmdLineOptions::machineFile ()
Returns the filename of the given machine (.adf)
Returns
the filename of the given machine (.adf)
Definition at line 186 of file SimulatorCmdLineOptions.cc.
{
    return findOption(SWS_MACHINE_TO_LOAD)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWS_MACHINE_TO_LOAD.
operator=()
SimulatorCmdLineOptions & SimulatorCmdLineOptions::operator= (const SimulatorCmdLineOptions &) private
Assignment not allowed.
printHelp()
void SimulatorCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Todo:
Implement using SimulatorTextGenerator.
Reimplemented from CmdLineOptions.
Definition at line 142 of file SimulatorCmdLineOptions.cc.
{
    printVersion();
    std::cout << std::endl << SimulatorToolbox::textGenerator().text(
        Texts::TXT_CMD_LINE_HELP).str() << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), printVersion(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_CMD_LINE_HELP.
printVersion()
void SimulatorCmdLineOptions::printVersion () const virtual
Prints the version of the program.
Implements CmdLineOptions.
Definition at line 131 of file SimulatorCmdLineOptions.cc.
{
    std::cout << SIM_CLI_TITLE << " " << Application::TCEVersionString()
              << std::endl;
}
References SIM_CLI_TITLE, and Application::TCEVersionString().
Referenced by printHelp().
programFile()
std::string SimulatorCmdLineOptions::programFile ()
Returns the filename of the given program
Returns
the filename of the given program
Definition at line 196 of file SimulatorCmdLineOptions.cc.
{
    return findOption(SWS_PROGRAM_TO_LOAD)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWS_PROGRAM_TO_LOAD.
scriptString()
std::string SimulatorCmdLineOptions::scriptString ()
Returns the script to be executed in the interpreter.
Returns an empty string, if none defined.
Returns
Script string.
Definition at line 173 of file SimulatorCmdLineOptions.cc.
{
    if (!optionGiven(SWL_EXECUTE_SCRIPT)) {
        return "";
    }
    return findOption(SWL_EXECUTE_SCRIPT)->String();
}
References CmdLineParser::findOption(), CmdLineOptions::optionGiven(), CmdLineOptionParser::String(), and SWL_EXECUTE_SCRIPT.
The documentation for this class was generated from the following files:
SimulatorCmdLineOptions.hh
SimulatorCmdLineOptions.cc