OpenASIP: ScriptInterpreter Class Reference
ScriptInterpreter Class Reference abstract
#include <ScriptInterpreter.hh>
Public Member Functions
ScriptInterpreter ()
virtual ~ScriptInterpreter ()
virtual void addCustomCommand (CustomCommand *command)
virtual void removeCustomCommand (const std::string &commandName)
virtual CustomCommand * customCommand (const std::string &commandName)
virtual void setResult (DataObject *result)
virtual void setResult (const std::string &result)
virtual void setResult (int result)
virtual void setResult (double result)
virtual std::string result ()
virtual void setError (bool state)
virtual void setError (std::string errorMessage)
virtual bool error () const
virtual void setVariable (const std::string &interpreterVariableName, const std::string &value)
virtual void setVariable (const std::string &interpreterVariableName, int value)
virtual std::string variableStringValue (const std::string &interpreterVariableName)
virtual int variableIntegerValue (const std::string &interpreterVariableName)
virtual bool processScriptFile (const std::string &scriptFileName)
virtual void finalize ()
virtual void setLineReader (LineReader *reader)
virtual LineReader * lineReader () const
std::vector< std::string > customCommandsSortedByName ()
virtual void initialize (int argc, char *argv[], InterpreterContext *context, LineReader *reader)=0
virtual void setVariableToInterpreter (const std::string &name, const DataObject &value)=0
virtual DataObject variable (const std::string &name)=0
virtual bool interpret (const std::string &commandLine)=0
virtual void setResultToInterpreter (const DataObject &value)=0
virtual InterpreterContext & context () const =0
Protected Member Functions
virtual void addCustomCommandToInterpreter (const CustomCommand &command)=0
virtual void removeCustomCommandFromInterpreter (const CustomCommand &command)=0
Private Types
typedef std::map< std::string, CustomCommand * >::iterator MapIter
Iterator for map.
typedef std::map< std::string, CustomCommand * >::value_type ValType
val_type for map.
Private Member Functions
ScriptInterpreter (const ScriptInterpreter &)
Copying not allowed.
ScriptInterpreter & operator= (const ScriptInterpreter &)
Assignment not allowed.
Private Attributes
std::map< std::string, CustomCommand * > commands_
Map containing all custom commands for interpreter.
DataObject * result_
The latest interpreter result.
bool errorState_
Indicates whether we are in error state.
bool finalized_
True if Interpreter is finalized.
LineReader * reader_
LineReader for interpreter.
Detailed Description
Abstract base class for all interpreters.
Interpreter processes its input, takes actions according to it and returns to wait more input.
Definition at line 55 of file ScriptInterpreter.hh.
Member Typedef Documentation
MapIter
typedef std::map<std::string,CustomCommand*>::iterator ScriptInterpreter::MapIter private
Iterator for map.
Definition at line 117 of file ScriptInterpreter.hh.
ValType
typedef std::map<std::string,CustomCommand*>::value_type ScriptInterpreter::ValType private
val_type for map.
Definition at line 119 of file ScriptInterpreter.hh.
Constructor & Destructor Documentation
ScriptInterpreter() [1/2]
ScriptInterpreter::ScriptInterpreter ()
Constructor.
Definition at line 50 of file ScriptInterpreter.cc.
                                     :
    result_(NULL), errorState_(false), finalized_(false) {
}
~ScriptInterpreter()
ScriptInterpreter::~ScriptInterpreter () virtual
Destructor.
Definition at line 57 of file ScriptInterpreter.cc.
{
    if (!finalized_) {
        string method = "ScriptInterpreter::~ScriptInterpreter()";
        string message = "Interpreter not finalized.";
        Application::writeToErrorLog(__FILE__, __LINE__, method, message);
    }
    MapTools::deleteAllValues(commands_);
    if (result_ != NULL) {
        delete result_;
    }
}
References commands_, MapTools::deleteAllValues(), finalized_, result_, and Application::writeToErrorLog().
ScriptInterpreter() [2/2]
ScriptInterpreter::ScriptInterpreter (const ScriptInterpreter &) private
Copying not allowed.
Member Function Documentation
addCustomCommand()
void ScriptInterpreter::addCustomCommand (CustomCommand * command) virtual
Adds a custom command to interpreter.
Parameters
command The command to be added.
Definition at line 78 of file ScriptInterpreter.cc.
{
    command->setInterpreter(this);
    commands_.insert(ValType(command->name(), command));
    addCustomCommandToInterpreter(*command);
}
References addCustomCommandToInterpreter(), commands_, CustomCommand::name(), and CustomCommand::setInterpreter().
Referenced by CompiledSimInterpreter::CompiledSimInterpreter(), main(), and SimulatorInterpreter::SimulatorInterpreter().
addCustomCommandToInterpreter()
virtual void ScriptInterpreter::addCustomCommandToInterpreter (const CustomCommand & command) protected pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by addCustomCommand().
context()
virtual InterpreterContext & ScriptInterpreter::context () const pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by BackTraceCommand::execute(), ConfCommand::execute(), DisassembleCommand::execute(), MachCommand::execute(), ProgCommand::execute(), and SimControlLanguageCommand::simulatorFrontend().
customCommand()
CustomCommand * ScriptInterpreter::customCommand (const std::string & commandName) virtual
Returns a custom command with a given name.
Returns NULL if CustomCommand is not found.
Parameters
commandName The name of the wanted command.
Returns
The pointer to a wanted custom command.
Definition at line 110 of file ScriptInterpreter.cc.
{
    if (!MapTools::containsKey(commands_, commandName)) {
        return NULL;
    }
    MapIter mi = commands_.find(commandName);
    return (*mi).second;
}
References commands_, and MapTools::containsKey().
Referenced by CmdHelp::execute(), HelpCommand::execute(), and SimpleScriptInterpreter::interpret().
customCommandsSortedByName()
vector< string > ScriptInterpreter::customCommandsSortedByName ()
Returns a vector of alphabetically sorted names of CustomCommands.
Returns
CustomCommands sorted by name.
Definition at line 342 of file ScriptInterpreter.cc.
{
    vector<string> names;
    MapIter it = commands_.begin();
    while (it != commands_.end()) {
        names.push_back((*it).second->name());
        it++;
    }
    vector<string>::iterator first = names.begin();
    vector<string>::iterator last = names.end();
    stable_sort(first , last);
    return names;
}
References commands_.
Referenced by CmdHelp::execute(), and HelpCommand::execute().
error()
bool ScriptInterpreter::error () const virtual
Returns true, if interpreter is in error state.
Returns
True, if interpreter is in error state.
Definition at line 229 of file ScriptInterpreter.cc.
{
    return errorState_;
}
References errorState_.
Referenced by ProximSimulationThread::Entry().
finalize()
void ScriptInterpreter::finalize () virtual
Removes all created CustomCommands from interpreter.
This is called before interpreter is deleted.
Definition at line 329 of file ScriptInterpreter.cc.
{
    for (MapIter mi = commands_.begin(); mi != commands_.end(); mi++) {
        removeCustomCommandFromInterpreter(*(*mi).second);
    }
    finalized_ = true;
}
References commands_, finalized_, and removeCustomCommandFromInterpreter().
Referenced by main(), and SimulatorInterpreter::~SimulatorInterpreter().
initialize()
virtual void ScriptInterpreter::initialize (int argc, char * argv[], InterpreterContext * context, LineReader * reader) pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
interpret()
virtual bool ScriptInterpreter::interpret (const std::string & commandLine) pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by Script::execute(), and processScriptFile().
lineReader()
LineReader * ScriptInterpreter::lineReader () const virtual
Returns the LineReader instance.
LineReader is needed by some CustomCommands. ScriptInterpreter may also need it.
Returns
LineReader instance.
Definition at line 367 of file ScriptInterpreter.cc.
{
    return reader_;
}
References reader_.
Referenced by SetHistorySave::execute(), SetHistoryFilename::execute(), SetHistorySize::execute(), TclInterpreter::interpret(), SimControlLanguageCommand::outputStream(), and SimulatorInterpreter::SimulatorInterpreter().
operator=()
ScriptInterpreter & ScriptInterpreter::operator= (const ScriptInterpreter &) private
Assignment not allowed.
processScriptFile()
bool ScriptInterpreter::processScriptFile (const std::string & scriptFileName) virtual
Opens a script file and processes it.
Parameters
scriptFileName The name of the script file.
Returns
True, if process is successful, false otherwise.
Exceptions
UnreachableStream If file cannot be opened.
Reimplemented in TclInterpreter.
Definition at line 303 of file ScriptInterpreter.cc.
{
    ifstream fileStream(scriptFileName.c_str());
    if (fileStream.bad()) {
        string method = "ScriptInterpreter::processScriptFile";
        string message = "Cannot open file " + scriptFileName;
        throw UnreachableStream(__FILE__, __LINE__, method, message);
    }
    string line;
    while (getline(fileStream, line)) {
        if (!interpret(line)) {
            fileStream.close();
            return false;
        }
    }
    fileStream.close();
    return true;
}
References interpret().
removeCustomCommand()
void ScriptInterpreter::removeCustomCommand (const std::string & commandName) virtual
Removes a custom command from interpreter.
Reserved memory for CustomCommand is freed.
Parameters
commandName The name of the command that is removed.
Definition at line 92 of file ScriptInterpreter.cc.
{
    if (MapTools::containsKey(commands_, commandName)) {
        MapIter mi = commands_.find(commandName);
        removeCustomCommandFromInterpreter(*(*mi).second);
        delete (*mi).second;
        commands_.erase(mi);
    }
}
References commands_, MapTools::containsKey(), and removeCustomCommandFromInterpreter().
Referenced by CompiledSimInterpreter::CompiledSimInterpreter().
removeCustomCommandFromInterpreter()
virtual void ScriptInterpreter::removeCustomCommandFromInterpreter (const CustomCommand & command) protected pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by finalize(), and removeCustomCommand().
result()
string ScriptInterpreter::result () virtual
Returns the result of last executed command as a string.
Returns
Last result as string.
Exceptions
NumberFormatException If converting result to string fails.
Definition at line 191 of file ScriptInterpreter.cc.
{
    if (result_ != NULL) {
        return result_->stringValue();
    } else {
        return "";
    }
}
References result_, and DataObject::stringValue().
Referenced by ProximSimulationThread::Entry(), Script::execute(), executeCommand(), SimpleScriptInterpreter::interpret(), SimulatorCLI::interpreteAndPrintResults(), Proxim::OnInit(), SimulatorCLI::run(), setError(), setResult(), setResult(), setResult(), setResult(), and DesignSpaceExplorer::simulate().
setError() [1/2]
void ScriptInterpreter::setError (bool state) virtual
Sets or unsets the error state of interpreter.
Parameters
state The error state flag.
Definition at line 205 of file ScriptInterpreter.cc.
{
    errorState_ = state;
}
References errorState_.
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), SimControlLanguageCommand::checkMachineLoaded(), SimControlLanguageCommand::checkProgramLoaded(), ConditionCommand::execute(), DisassembleCommand::execute(), IgnoreCommand::execute(), InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), InfoCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), SettingCommand::execute(), SymbolAddressCommand::execute(), SimpleScriptInterpreter::interpret(), TclInterpreter::interpret(), SimControlLanguageCommand::parseBreakpoint(), SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimControlLanguageCommand::printBreakpointInfo(), setError(), SimControlLanguageCommand::setMemoryPointer(), and SimControlLanguageCommand::verifyBreakpointHandles().
setError() [2/2]
void ScriptInterpreter::setError (std::string errorMessage) virtual
Sets an error message and sets errors status of interpreter.
Parameters
errorMessage The error message.
Definition at line 215 of file ScriptInterpreter.cc.
{
    DataObject* result = new DataObject();
    result->setString(errorMessage);
    setResult(result);
    setError(true);
}
References result(), setError(), and setResult().
setLineReader()
void ScriptInterpreter::setLineReader (LineReader * reader) virtual
Sets the LineReader for the interpreter.
Parameters
reader The LineReader.
Definition at line 377 of file ScriptInterpreter.cc.
{
    reader_ = reader;
}
References reader_.
Referenced by SimpleScriptInterpreter::initialize(), and TclInterpreter::initialize().
setResult() [1/4]
void ScriptInterpreter::setResult (const std::string & result) virtual
Stores the result of last executed command.
Sets result also to concrete interpreter.
Parameters
result The result.
Definition at line 144 of file ScriptInterpreter.cc.
{
    if (result_ == NULL) {
        result_ = new DataObject();
    }
    result_->setString(result);
    setResultToInterpreter(*result_);
}
References result(), result_, setResultToInterpreter(), and DataObject::setString().
setResult() [2/4]
void ScriptInterpreter::setResult (DataObject * result) virtual
Stores the result of last executed command.
Sets result also to concrete interpreter.
Parameters
result The result.
Definition at line 128 of file ScriptInterpreter.cc.
{
    if (result_ != NULL) {
        delete result_;
    }
    result_ = result;
    setResultToInterpreter(*result);
}
References result(), result_, and setResultToInterpreter().
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), CustomCommand::checkArgumentCount(), CustomCommand::checkDoubleArgument(), CustomCommand::checkIntegerArgument(), CustomCommand::checkPositiveIntegerArgument(), SimControlLanguageCommand::checkSimulationEnded(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationNotAlreadyRunning(), SimControlLanguageCommand::checkSimulationStopped(), CustomCommand::checkUnsignedIntegerArgument(), ConditionScript::conditionOk(), CmdHelp::execute(), ConfCommand::execute(), HelpCommand::execute(), InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoRegFilesCommand::execute(), InfoIunitsCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), MachCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), ProgCommand::execute(), SettingCommand::execute(), SymbolAddressCommand::execute(), CmdTrigger::execute(), CmdReset::execute(), CmdQuit::execute(), CmdOutput::execute(), CmdRegister::execute(), CmdMem::execute(), CmdAdvanceClock::execute(), SimpleScriptInterpreter::interpret(), TclInterpreter::interpret(), ExpressionScript::resultChanged(), setError(), and SimControlLanguageCommand::setErrorMessage().
setResult() [3/4]
void ScriptInterpreter::setResult (double result) virtual
Stores the result of last executed command.
Sets result also to concrete interpreter.
Parameters
result The result.
Definition at line 176 of file ScriptInterpreter.cc.
{
    if (result_ == NULL) {
        result_ = new DataObject();
    }
    result_->setDouble(result);
    setResultToInterpreter(*result_);
}
References result(), result_, DataObject::setDouble(), and setResultToInterpreter().
setResult() [4/4]
void ScriptInterpreter::setResult (int result) virtual
Stores the result of last executed command.
Sets result also to concrete interpreter.
Parameters
result The result.
Definition at line 160 of file ScriptInterpreter.cc.
{
    if (result_ == NULL) {
        result_ = new DataObject();
    }
    result_->setInteger(result);
    setResultToInterpreter(*result_);
}
References result(), result_, DataObject::setInteger(), and setResultToInterpreter().
setResultToInterpreter()
virtual void ScriptInterpreter::setResultToInterpreter (const DataObject & value) pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by setResult(), setResult(), setResult(), and setResult().
setVariable() [1/2]
void ScriptInterpreter::setVariable (const std::string & interpreterVariableName, const std::string & value) virtual
Sets value for a variable.
Parameters
interpreterVariableName The name of the variable.
value The value for a variable.
Definition at line 240 of file ScriptInterpreter.cc.
{
    DataObject object;
    object.setString(value);
    setVariableToInterpreter(interpreterVariableName, object);
}
References DataObject::setString(), and setVariableToInterpreter().
Referenced by TclInterpreter::initialize().
setVariable() [2/2]
void ScriptInterpreter::setVariable (const std::string & interpreterVariableName, int value) virtual
Sets the value for interpreter variable.
Parameters
interpreterVariableName The name of the variable.
value The value for the variable.
Definition at line 256 of file ScriptInterpreter.cc.
               {
    DataObject object;
    object.setInteger(value);
    setVariableToInterpreter(interpreterVariableName, object);
}
References DataObject::setInteger(), and setVariableToInterpreter().
setVariableToInterpreter()
virtual void ScriptInterpreter::setVariableToInterpreter (const std::string & name, const DataObject & value) pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by setVariable(), and setVariable().
variable()
virtual DataObject ScriptInterpreter::variable (const std::string & name) pure virtual
Implemented in SimpleScriptInterpreter, and TclInterpreter.
Referenced by variableIntegerValue(), and variableStringValue().
variableIntegerValue()
int ScriptInterpreter::variableIntegerValue (const std::string & interpreterVariableName) virtual
Returns the value of the integer variable.
Parameters
interpreterVariableName The name of the variable.
Returns
The value of the variable.
Exceptions
NumberFormatException If converting variable to integer fails.
Definition at line 288 of file ScriptInterpreter.cc.
{
    DataObject var = variable(interpreterVariableName);
    int value = var.integerValue();
    return value;
}
References DataObject::integerValue(), and variable().
variableStringValue()
string ScriptInterpreter::variableStringValue (const std::string & interpreterVariableName) virtual
Returns the value of the string variable.
Parameters
interpreterVariableName The name of the variable.
Returns
The value of the variable.
Exceptions
NumberFormatException If converting variable to string fails.
Definition at line 273 of file ScriptInterpreter.cc.
{
    DataObject var = variable(interpreterVariableName);
    string value = var.stringValue();
    return value;
}
References DataObject::stringValue(), and variable().
Member Data Documentation
commands_
std::map<std::string, CustomCommand*> ScriptInterpreter::commands_ private
Map containing all custom commands for interpreter.
Definition at line 127 of file ScriptInterpreter.hh.
Referenced by addCustomCommand(), customCommand(), customCommandsSortedByName(), finalize(), removeCustomCommand(), and ~ScriptInterpreter().
errorState_
bool ScriptInterpreter::errorState_ private
Indicates whether we are in error state.
Definition at line 131 of file ScriptInterpreter.hh.
Referenced by error(), and setError().
finalized_
bool ScriptInterpreter::finalized_ private
True if Interpreter is finalized.
Definition at line 133 of file ScriptInterpreter.hh.
Referenced by finalize(), and ~ScriptInterpreter().
reader_
LineReader* ScriptInterpreter::reader_ private
LineReader for interpreter.
Definition at line 135 of file ScriptInterpreter.hh.
Referenced by lineReader(), and setLineReader().
result_
DataObject* ScriptInterpreter::result_ private
The latest interpreter result.
Definition at line 129 of file ScriptInterpreter.hh.
Referenced by result(), setResult(), setResult(), setResult(), setResult(), and ~ScriptInterpreter().
The documentation for this class was generated from the following files:
ScriptInterpreter.hh
ScriptInterpreter.cc