OpenASIP: BlocksALU Class Reference
BlocksALU Class Reference
#include <BlocksALU.hh>
Public Member Functions
BlocksALU (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksALU ()
Public Attributes
TTAMachine::FunctionUnit * alu
Public Attributes inherited from BlocksFU
std::vector< TTAMachine::HWOperation * > ops
TTAMachine::FunctionUnit * fu
TTAMachine::FUPort * in1
TTAMachine::FUPort * in2
TTAMachine::FUPort * out
std::shared_ptr< TTAMachine::Socket > in1sock
std::shared_ptr< TTAMachine::Socket > in2sock
TTAMachine::Socket * outsock
std::list< std::string > sources
std::string name
Private Member Functions
void ConfigurePipeline (TTAMachine::ExecutionPipeline *pipeline, int numOfOperands)
void BindPorts (TTAMachine::HWOperation *hwOp, int numOfOperands)
TTAMachine::HWOperation * CreateHWOp (const std::string &name, int numOfOperands)
Additional Inherited Members
Protected Member Functions inherited from BlocksFU
BlocksFU (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksFU ()
Detailed Description
Definition at line 39 of file BlocksALU.hh.
Constructor & Destructor Documentation
BlocksALU()
BlocksALU::BlocksALU (TTAMachine::Machine & mach, const std::string & name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
Create BlocksALU with default instructions
Parameters
mach The TTA machine where the ALU needs to be added.
name The name of the ALU.
sources A list of sources that are attached to this unit's input.
in1sock (shared) pointer to the TTA socket for in1 input port.
in2sock (shared) pointer to the TTA socket for in2 input port.
Definition at line 47 of file BlocksALU.cc.
    : BlocksFU::BlocksFU(mach, name, sources, in1sock, in2sock) {
    // Function unit and ports
    alu = this->fu;
    // HW ops
    ops.push_back(CreateHWOp("add", 3));
    ops.push_back(CreateHWOp("and", 3));
    ops.push_back(CreateHWOp("eq", 3));
    ops.push_back(CreateHWOp("ge", 3));
    ops.push_back(CreateHWOp("geu", 3));
    ops.push_back(CreateHWOp("gt", 3));
    ops.push_back(CreateHWOp("gtu", 3));
    ops.push_back(CreateHWOp("ior", 3));
    ops.push_back(CreateHWOp("lt", 3));
    ops.push_back(CreateHWOp("ltu", 3));
    ops.push_back(CreateHWOp("ne", 3));
    ops.push_back(CreateHWOp("not", 2));
    ops.push_back(CreateHWOp("shl1_32", 2));
    ops.push_back(CreateHWOp("shl4_32", 2));
    ops.push_back(CreateHWOp("shr1_32", 2));
    ops.push_back(CreateHWOp("shr4_32", 2));
    ops.push_back(CreateHWOp("shru1_32", 2));
    ops.push_back(CreateHWOp("shru4_32", 2));
    ops.push_back(CreateHWOp("sub", 3));
    ops.push_back(CreateHWOp("xor", 3));
    ops.push_back(CreateHWOp("copy", 2));
}
References alu, CreateHWOp(), BlocksFU::fu, and BlocksFU::ops.
~BlocksALU()
BlocksALU::~BlocksALU () inline
Definition at line 47 of file BlocksALU.hh.
                 {
        while (!ops.empty()) {
            delete ops.back();
            ops.pop_back();
        }
    }
References BlocksFU::ops.
Member Function Documentation
BindPorts()
void BlocksALU::BindPorts (TTAMachine::HWOperation * hwOp, int numOfOperands) private
Bind the operation's operands to FU ports.
Parameters
hwOp A pointer to the hardware operation of which the operands need to be binded to FU ports.
numOfOperands The number of operands of the given hwOp.
Definition at line 130 of file BlocksALU.cc.
{
    if (numOfOperands == 2) {
        hwOp->bindPort(1, *in1);
        hwOp->bindPort(2, *out);
    } else if (numOfOperands == 3) {
        hwOp->bindPort(1, *in1);
        hwOp->bindPort(2, *in2);
        hwOp->bindPort(3, *out);
    } else {
        // Currently no operation known that uses a different numbers of
        // operands.
        assert(
            false &&
            "Trying to add an ALU operation with a different number of "
            "operands than 2 or 3.");
    }
}
References assert, TTAMachine::HWOperation::bindPort(), BlocksFU::in1, BlocksFU::in2, and BlocksFU::out.
Referenced by CreateHWOp().
ConfigurePipeline()
void BlocksALU::ConfigurePipeline (TTAMachine::ExecutionPipeline * pipeline, int numOfOperands) private
Configure the operation pipeline.
Parameters
pipeline A pointer to the execution pipeline of the operation of which the pipeline needs to be configured.
numOfOperands The number of operands of the given hwOp.
Definition at line 156 of file BlocksALU.cc.
{
    if (numOfOperands < 3) {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortWrite(2, 0, 1);
    } else {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortRead(2, 0, 1);
        pipeline->addPortWrite(3, 0, 1);
    }
}
References TTAMachine::ExecutionPipeline::addPortRead(), and TTAMachine::ExecutionPipeline::addPortWrite().
Referenced by CreateHWOp().
CreateHWOp()
HWOperation * BlocksALU::CreateHWOp (const std::string & name, int numOfOperands) private
Creates a hardware operation.
Parameters
name The name of the hardware operation. This needs to exactly match the name in OSEd.
numOfOperands The number of operands that this hardware operation requires.
Definition at line 115 of file BlocksALU.cc.
{
    HWOperation* op = new HWOperation(name, *alu);
    BindPorts(op, numOfOperands);
    ConfigurePipeline(op->pipeline(), numOfOperands);
    return op;
}
References alu, BindPorts(), ConfigurePipeline(), BlocksFU::name, and TTAMachine::HWOperation::pipeline().
Referenced by BlocksALU().
Member Data Documentation
alu
TTAMachine::FunctionUnit* BlocksALU::alu
Definition at line 41 of file BlocksALU.hh.
Referenced by BlocksALU(), and CreateHWOp().
The documentation for this class was generated from the following files:
BlocksALU.hh
BlocksALU.cc