OpenASIP: HDLGenerator::DefaultAssign Class Reference
HDLGenerator::DefaultAssign Class Reference
#include <HDLGenerator.hh>
Public Member Functions
DefaultAssign (std::string name, std::string value)
DefaultAssign (std::string name)
void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::string value_
bool dontCare_
Detailed Description
Assign default value.
Definition at line 367 of file HDLGenerator.hh.
Constructor & Destructor Documentation
DefaultAssign() [1/2]
HDLGenerator::DefaultAssign::DefaultAssign (std::string name, std::string value) inline
Definition at line 369 of file HDLGenerator.hh.
            : SequentialStatement(name), value_(value), dontCare_(false) {}
DefaultAssign() [2/2]
HDLGenerator::DefaultAssign::DefaultAssign (std::string name) inline
Definition at line 371 of file HDLGenerator.hh.
            : SequentialStatement(name), value_(""), dontCare_(true) {}
Member Function Documentation
hdl()
void HDLGenerator::DefaultAssign::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 374 of file HDLGenerator.hh.
{
            Width w = width(name());
            WireType t = wireType(name());
            if (lang == Language::VHDL) {
                std::string def = "-";
                if (!dontCare_)
                    def = value_.substr(0, 1);
                std::string assign = " <= ";
                if (isVariable(name())) {
                    assign = " := ";
                }
                stream << StringTools::indent(level) << name() << assign;
                if (w.strWidth.empty() && w.intWidth == 1) {
                    char delim = t == WireType::Auto ? '\'' : '"';
                    stream << delim << def << delim << ";\n";
                } else {
                    stream << "(others => '" << def << "');\n";
                }
            } else if (lang == Language::Verilog) {
                std::string def = "x";
                if (!dontCare_)
                    def = value_.substr(0, 1);
                stream << StringTools::indent(level)
                       << name() << " = 'b" << def << ";\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References HDLGenerator::Auto, dontCare_, StringTools::indent(), HDLGenerator::Width::intWidth, HDLGenerator::Generatable::isVariable(), HDLGenerator::Generatable::name(), HDLGenerator::Width::strWidth, value_, HDLGenerator::Verilog, HDLGenerator::VHDL, HDLGenerator::Generatable::width(), and HDLGenerator::Generatable::wireType().
Member Data Documentation
dontCare_
bool HDLGenerator::DefaultAssign::dontCare_ private
Definition at line 410 of file HDLGenerator.hh.
Referenced by hdl().
value_
std::string HDLGenerator::DefaultAssign::value_ private
Definition at line 409 of file HDLGenerator.hh.
Referenced by hdl().
The documentation for this class was generated from the following file:
HDLGenerator.hh