OpenASIP: ConflictDetectingOperationExecutor Class Reference
ConflictDetectingOperationExecutor Class Reference
#include <ConflictDetectingOperationExecutor.hh>
Public Member Functions
ConflictDetectingOperationExecutor (FUResourceConflictDetector &detector, FUResourceConflictDetector::OperationID operationID, FUState &parent, TTAMachine::HWOperation &hwOp, bool throwWhenConflict)
virtual ~ConflictDetectingOperationExecutor ()
virtual void startOperation (Operation &op)
virtual void advanceClock ()
virtual OperationExecutor * copy ()
Public Member Functions inherited from MultiLatencyOperationExecutor
MultiLatencyOperationExecutor (FUState &parent, TTAMachine::HWOperation &hwOp)
MultiLatencyOperationExecutor ()
virtual ~MultiLatencyOperationExecutor ()
virtual void setContext (OperationContext &context)
virtual void reset ()
virtual void setOperationSimulator (DetailedOperationSimulator &sim)
Public Member Functions inherited from OperationExecutor
OperationExecutor ()
OperationExecutor (FUState &parent)
virtual ~OperationExecutor ()
FUState & parent () const
void setParent (FUState &parent)
void addBinding (int io, PortState &port)
PortState & binding (int io) const
bool hasPendingOperations () const
Private Member Functions
ConflictDetectingOperationExecutor & operator= (const ConflictDetectingOperationExecutor &)
Assignment not allowed.
Private Attributes
FUResourceConflictDetector & detector_
The conflict detector used to test whether starting operation is legal.
const FUResourceConflictDetector::OperationID operationID_
The conflict detector ID of the operation executed with this executor.
const bool throwWhenConflict_
True in case an exception should be thrown in case of a resource conflict.
ClockCycleCount conflictCounter_
Counter for detected conflicts.
Additional Inherited Members
Protected Attributes inherited from OperationExecutor
std::vector< PortState * > bindings_
PortStates that are bound to a certain input or output operand.
bool hasPendingOperations_
This is set to true if the OperationExecutor is not in 'idle' mode.
Detailed Description
OperationExecutor that checks for FU resource conflicts.
This kind of OperationExecutor is created for each operation in the simulated FU. This is purely for optimization purposes: as we need to check the resource conflicts using a per operation ID, it's faster to use a constant ID for requesting the conflict detection data instead of first fetching the constant from a map for the executed operation.
Definition at line 49 of file ConflictDetectingOperationExecutor.hh.
Constructor & Destructor Documentation
ConflictDetectingOperationExecutor()
ConflictDetectingOperationExecutor::ConflictDetectingOperationExecutor (FUResourceConflictDetector & detector, FUResourceConflictDetector::OperationID operationID, FUState & parent, TTAMachine::HWOperation & hwOp, bool throwWhenConflict)
Constructor.
Parameters
detector The conflict detector.
operationID The conflict detector ID of the operation executed by this operation executor.
parent Parent of the OperationExecutor.
throwWhenConflict In case an exception should be thrown in case of a resource conflict (otherwise the conflicts are only counted).
Definition at line 53 of file ConflictDetectingOperationExecutor.cc.
                            :
    MultiLatencyOperationExecutor(parent, hwOp), detector_(detector),
    operationID_(operationID), throwWhenConflict_(throwWhenConflict),
    conflictCounter_(0) {
}
~ConflictDetectingOperationExecutor()
ConflictDetectingOperationExecutor::~ConflictDetectingOperationExecutor () virtual
Destructor.
Definition at line 67 of file ConflictDetectingOperationExecutor.cc.
{
#if 0
    if (conflictCounter_ > 0)
        std::cout << " (" << conflictCounter_ << " conflicts) ";
#endif
}
References conflictCounter_.
Member Function Documentation
advanceClock()
void ConflictDetectingOperationExecutor::advanceClock () virtual
Advances clock by one cycle.
Updates the resource conflict model.
Reimplemented from MultiLatencyOperationExecutor.
Definition at line 109 of file ConflictDetectingOperationExecutor.cc.
{
    MultiLatencyOperationExecutor::advanceClock();
    // we need to receive the advanceClock() on every clock advance to update
    // the resource conflict model
    hasPendingOperations_ = true;
}
References MultiLatencyOperationExecutor::advanceClock(), and OperationExecutor::hasPendingOperations_.
copy()
OperationExecutor * ConflictDetectingOperationExecutor::copy () virtual
Copies OperationExecutor.
Returns
The copied OperationExecutor.
Reimplemented from MultiLatencyOperationExecutor.
Definition at line 123 of file ConflictDetectingOperationExecutor.cc.
{
    return new ConflictDetectingOperationExecutor(*this);
}
operator=()
ConflictDetectingOperationExecutor & ConflictDetectingOperationExecutor::operator= (const ConflictDetectingOperationExecutor &) private
Assignment not allowed.
startOperation()
void ConflictDetectingOperationExecutor::startOperation (Operation & op) virtual
Starts new operation.
Checks for resource conflicts before actually simulating the operation using the parent class implementation.
Parameters
op Operation to be triggered.
Reimplemented from MultiLatencyOperationExecutor.
Definition at line 83 of file ConflictDetectingOperationExecutor.cc.
{
    if (!detector_.issueOperation(operationID_)) {
        ++conflictCounter_;
        if (throwWhenConflict_)
            throw SimulationExecutionError(
                __FILE__, __LINE__, __func__,
                (boost::format(
                    "Resource conflict detected: operation %s.")
                 % op.name()).str());
        return;
    }
    MultiLatencyOperationExecutor::startOperation(op);
    // we need to receive the advanceClock() on every clock advance to update
    // the resource conflict model
    hasPendingOperations_ = true;
}
References __func__, conflictCounter_, detector_, OperationExecutor::hasPendingOperations_, FUResourceConflictDetector::issueOperation(), Operation::name(), operationID_, MultiLatencyOperationExecutor::startOperation(), and throwWhenConflict_.
Member Data Documentation
conflictCounter_
ClockCycleCount ConflictDetectingOperationExecutor::conflictCounter_ private
Counter for detected conflicts.
Definition at line 79 of file ConflictDetectingOperationExecutor.hh.
Referenced by startOperation(), and ~ConflictDetectingOperationExecutor().
detector_
FUResourceConflictDetector& ConflictDetectingOperationExecutor::detector_ private
The conflict detector used to test whether starting operation is legal.
Definition at line 72 of file ConflictDetectingOperationExecutor.hh.
Referenced by startOperation().
operationID_
const FUResourceConflictDetector::OperationID ConflictDetectingOperationExecutor::operationID_ private
The conflict detector ID of the operation executed with this executor.
Definition at line 74 of file ConflictDetectingOperationExecutor.hh.
Referenced by startOperation().
throwWhenConflict_
const bool ConflictDetectingOperationExecutor::throwWhenConflict_ private
True in case an exception should be thrown in case of a resource conflict.
Definition at line 77 of file ConflictDetectingOperationExecutor.hh.
Referenced by startOperation().
The documentation for this class was generated from the following files:
ConflictDetectingOperationExecutor.hh
ConflictDetectingOperationExecutor.cc