OpenASIP: TPEF::SectionIdReplacer Class Reference
TPEF::SectionIdReplacer Class Reference
#include <SectionIdReplacer.hh>
Public Member Functions
SectionIdReplacer (const SafePointable *obj)
virtual ~SectionIdReplacer ()
Public Member Functions inherited from TPEF::ValueReplacer
void resolve ()
Protected Member Functions
virtual bool tryToReplace ()
virtual ValueReplacer * clone ()
Protected Member Functions inherited from TPEF::ValueReplacer
ValueReplacer (const SafePointable *obj)
ValueReplacer (const ValueReplacer &replacer)
virtual ~ValueReplacer ()
const SafePointable * reference () const
unsigned int streamPosition () const
Private Member Functions
SectionIdReplacer (const SectionIdReplacer &replacer)
SectionIdReplacer operator= (const SectionIdReplacer &)
Additional Inherited Members
Static Public Member Functions inherited from TPEF::ValueReplacer
static void finalize ()
static void initialize (BinaryStream &stream)
Static Protected Member Functions inherited from TPEF::ValueReplacer
static BinaryStream & stream ()
Detailed Description
Replaces object references with the section identification code that identifies the object. The reference manager must contain a SectionId key for the objects whose section identification code is written out.
Definition at line 47 of file SectionIdReplacer.hh.
Constructor & Destructor Documentation
SectionIdReplacer() [1/2]
TPEF::SectionIdReplacer::SectionIdReplacer (const SafePointable * obj)
Constructor.
Definition at line 46 of file SectionIdReplacer.cc.
                                                             :
    ValueReplacer(obj) {
}
~SectionIdReplacer()
TPEF::SectionIdReplacer::~SectionIdReplacer () virtual
Destructor.
Definition at line 60 of file SectionIdReplacer.cc.
{
}
SectionIdReplacer() [2/2]
TPEF::SectionIdReplacer::SectionIdReplacer (const SectionIdReplacer & replacer) private
Copy constructor.
Definition at line 53 of file SectionIdReplacer.cc.
                                                                      :
    ValueReplacer(replacer) {
}
Member Function Documentation
clone()
ValueReplacer * TPEF::SectionIdReplacer::clone () protected virtual
Creates dynamically allocated copy of replacer.
Returns
Dynamically allocated copy of replacer.
Implements TPEF::ValueReplacer.
Definition at line 90 of file SectionIdReplacer.cc.
{
    return new SectionIdReplacer(*this);
}
operator=()
SectionIdReplacer TPEF::SectionIdReplacer::operator= (const SectionIdReplacer &) private
tryToReplace()
bool TPEF::SectionIdReplacer::tryToReplace () protected virtual
Tries to do replacement in to the stream.
Returns
True if replacement were done.
Implements TPEF::ValueReplacer.
Definition at line 69 of file SectionIdReplacer.cc.
{
    try {
        SectionKey key =
            SafePointer::sectionKeyFor(reference());
        stream().setWritePosition(streamPosition());
        stream().writeHalfWord(key.sectionId());
        return true;
    } catch (KeyNotFound& e) {
        stream().writeHalfWord(0);
        return false;
    }
}
References TPEF::ValueReplacer::reference(), TPEF::ReferenceManager::SectionKey::sectionId(), TPEF::ReferenceManager::SafePointer::sectionKeyFor(), TPEF::BinaryStream::setWritePosition(), TPEF::ValueReplacer::stream(), TPEF::ValueReplacer::streamPosition(), and TPEF::BinaryStream::writeHalfWord().
The documentation for this class was generated from the following files:
SectionIdReplacer.hh
SectionIdReplacer.cc