OpenASIP: MachCommand Class Reference
MachCommand Class Reference
#include <MachCommand.hh>
Public Member Functions
MachCommand ()
virtual ~MachCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Implementation of the "mach" command of the Simulator Control Language.
Definition at line 46 of file MachCommand.hh.
Constructor & Destructor Documentation
MachCommand()
MachCommand::MachCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 47 of file MachCommand.cc.
                         : CustomCommand("mach") {
}
~MachCommand()
MachCommand::~MachCommand () virtual
Destructor.
Does nothing.
Definition at line 55 of file MachCommand.cc.
{
}
Member Function Documentation
execute()
bool MachCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "mach" command.
Loads a new machine file using the SimulatorFrontend.
Parameters
arguments Filename is given as argument to the command.
Returns
True if loading the program was successful.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 69 of file MachCommand.cc.
{
    assert(interpreter() != NULL);
    SimulatorTextGenerator& textGen = SimulatorToolbox::textGenerator();
    if (arguments.size() < 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_NO_FILENAME_DEFINED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    if (arguments.size() > 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_ONLY_ONE_FILENAME_EXPECTED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    SimulatorInterpreterContext& interpreterContext =
        dynamic_cast<SimulatorInterpreterContext&>(interpreter()->context());
    SimulatorFrontend& simulatorFrontend =
        interpreterContext.simulatorFrontend();
    try {
        const std::string fileName =
            FileSystem::expandTilde(arguments.at(1).stringValue());
        simulatorFrontend.loadMachine(fileName);
    } catch (const Exception& e) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_UNABLE_TO_LOAD_MACHINE).str() + e.errorMessageStack(true));
        interpreter()->setResult(errorMessage);
        return false;
    } catch (...) {
        assert(false);
        return false;
    }
    return true;
}
References assert, ScriptInterpreter::context(), Exception::errorMessageStack(), FileSystem::expandTilde(), CustomCommand::interpreter(), SimulatorFrontend::loadMachine(), ScriptInterpreter::setResult(), DataObject::setString(), SimulatorInterpreterContext::simulatorFrontend(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_NO_FILENAME_DEFINED, Texts::TXT_ONLY_ONE_FILENAME_EXPECTED, and Texts::TXT_UNABLE_TO_LOAD_MACHINE.
helpText()
std::string MachCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 122 of file MachCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_MACH).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_MACH.
The documentation for this class was generated from the following files:
MachCommand.hh
MachCommand.cc