OpenASIP: BFSwapOperands Class Reference
BFSwapOperands Class Reference
#include <BFSwapOperands.hh>
Public Member Functions
BFSwapOperands (BF2Scheduler &sched, MoveNode &mn)
BFSwapOperands (BF2Scheduler &sched, ProgramOperationPtr po, MoveNode &mn1, MoveNode &mn2)
virtual bool operator() ()
virtual ~BFSwapOperands ()
std::pair< MoveNode *, MoveNode * > switchedMNs ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
virtual void undoOnlyMe ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes
std::pair< MoveNode *, MoveNode * > switched_
ProgramOperationPtr poPtr_
int idx1_
int idx2_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 41 of file BFSwapOperands.hh.
Constructor & Destructor Documentation
BFSwapOperands() [1/2]
BFSwapOperands::BFSwapOperands (BF2Scheduler & sched, MoveNode & trigger)
Tries to switch operand and trigger so that it makees immediates triggers, but minimizes the critical path if both operands come from variables.
Definition at line 56 of file BFSwapOperands.cc.
                                                                     :
    BFOptimization(sched), switched_(NULL,NULL), poPtr_(),
    idx1_(0), idx2_(0) {
    if (trigger.destinationOperationCount() != 1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "not exactly one destop:" << trigger.toString()
                  << std::endl;
#endif
        return;
    }
    // keep immediates as triggers
    if (trigger.move().source().isImmediate()) {
        return;
    }
    int index = trigger.move().destination().operationIndex();
    ProgramOperationPtr poPtr = trigger.destinationOperationPtr(0);
    const Operation &op = poPtr->operation();
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "trying to swap operand of po: "
              << poPtr->toString() << std::endl;
#endif
    for (int i = 1; i <= op.numberOfInputs(); i++) {
        if (i == index) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\tNot swapping with itself" << std::endl;
#endif
            continue;
        }
        if (!op.canSwap(i, index)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\tnot commutative" << std::endl;
#endif
            continue;
        }
        MoveNodeSet& otherInputs = poPtr->inputNode(i);
        if (otherInputs.count() != 1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\tother input count not 1" << std::endl;
#endif
            continue;
        }
        MoveNode& other = otherInputs.at(0);
        if (other.isScheduled()) {
            continue;
        }
        if (sched_.isPreLoopSharedOperand(other)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\tCannot swap operand with pre-loop-shared" << std::endl;
#endif
            continue;
        }
        // make longer path OR immediate into trigger
        // currently only immediate.
        if (other.move().source().isImmediate()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\tshould swap indeces: " << i << " and  " << index
                      << std::endl;
#endif
            idx1_ = index;
            idx2_ = i;
            poPtr_ = poPtr;
            switched_.first = &trigger;
            switched_.second = &other;
            return;
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\tother input is: " << other.toString() << std::endl;
#endif
    }
    return;
}
References MoveNodeSet::at(), Operation::canSwap(), MoveNodeSet::count(), TTAProgram::Move::destination(), MoveNode::destinationOperationCount(), MoveNode::destinationOperationPtr(), idx1_, idx2_, TTAProgram::Terminal::isImmediate(), BF2Scheduler::isPreLoopSharedOperand(), MoveNode::isScheduled(), MoveNode::move(), Operation::numberOfInputs(), TTAProgram::Terminal::operationIndex(), poPtr_, BFOptimization::sched_, TTAProgram::Move::source(), switched_, and MoveNode::toString().
BFSwapOperands() [2/2]
BFSwapOperands::BFSwapOperands (BF2Scheduler & sched, ProgramOperationPtr po, MoveNode & mn1, MoveNode & mn2)
Definition at line 45 of file BFSwapOperands.cc.
                                                                :
    BFOptimization(sched), switched_(&mn1, &mn2), poPtr_(po),
    idx1_(mn1.move().destination().operationIndex()),
    idx2_(mn2.move().destination().operationIndex()) {}
~BFSwapOperands()
virtual BFSwapOperands::~BFSwapOperands () inline virtual
Definition at line 48 of file BFSwapOperands.hh.
{}
Member Function Documentation
operator()()
bool BFSwapOperands::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 137 of file BFSwapOperands.cc.
{
    if (poPtr_ == NULL) {
        return false;
    }
    const Operation &op = poPtr_->operation();
    if (!op.canSwap(idx1_, idx2_)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "Cannot swap: " << idx1_ << " and " << idx2_ << std::endl;
#endif
        return false;
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "Swapping inputs: " << poPtr_->toString() << std::endl;
#endif
    poPtr_->switchInputs(idx1_, idx2_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "Swapped inputs: " << poPtr_->toString() << std::endl;
#endif
    return true;
}
References Operation::canSwap(), idx1_, idx2_, and poPtr_.
switchedMNs()
std::pair< MoveNode *, MoveNode * > BFSwapOperands::switchedMNs () inline
Definition at line 49 of file BFSwapOperands.hh.
{ return switched_; }
References switched_.
Referenced by BF2ScheduleFront::getMoveNodeFromFrontBU().
undoOnlyMe()
void BFSwapOperands::undoOnlyMe () protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 158 of file BFSwapOperands.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "undoing swap: " << poPtr_->toString() << std::endl;
#endif
    poPtr_->switchInputs(idx1_, idx2_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "undid swap: " << poPtr_->toString() << std::endl;
#endif
}
References idx1_, idx2_, and poPtr_.
Member Data Documentation
idx1_
int BFSwapOperands::idx1_ protected
Definition at line 54 of file BFSwapOperands.hh.
Referenced by BFSwapOperands(), operator()(), and undoOnlyMe().
idx2_
int BFSwapOperands::idx2_ protected
Definition at line 55 of file BFSwapOperands.hh.
Referenced by BFSwapOperands(), operator()(), and undoOnlyMe().
poPtr_
ProgramOperationPtr BFSwapOperands::poPtr_ protected
Definition at line 53 of file BFSwapOperands.hh.
Referenced by BFSwapOperands(), operator()(), and undoOnlyMe().
switched_
std::pair<MoveNode*, MoveNode*> BFSwapOperands::switched_ protected
Definition at line 52 of file BFSwapOperands.hh.
Referenced by BFSwapOperands(), and switchedMNs().
The documentation for this class was generated from the following files:
BFSwapOperands.hh
BFSwapOperands.cc