OpenASIP: ITemplateResource Class Reference
ITemplateResource Class Reference
#include <ITemplateResource.hh>
Public Member Functions
virtual ~ITemplateResource ()
ITemplateResource (TTAMachine::InstructionTemplate &templ, unsigned int initiationInterval=0)
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual bool canAssign (const int cycle) const
virtual void assign (const int cycle, MoveNode &node) override
virtual void assign (const int cycle)
virtual void unassign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle)
virtual bool isITemplateResource () const override
void clear () override
virtual bool operator< (const SchedulingResource &other) const override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Types
typedef std::map< int, int > ResourceRecordType
Private Member Functions
ITemplateResource (const ITemplateResource &)
ITemplateResource & operator= (const ITemplateResource &)
Private Attributes
ResourceRecordType resourceRecord_
TTAMachine::InstructionTemplate * template_
Additional Inherited Members
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model The derived class ITemplateResource
Definition at line 51 of file ITemplateResource.hh.
Member Typedef Documentation
ResourceRecordType
typedef std::map<int, int> ITemplateResource::ResourceRecordType private
Definition at line 76 of file ITemplateResource.hh.
Constructor & Destructor Documentation
~ITemplateResource()
ITemplateResource::~ITemplateResource () virtual
Destructor.
Definition at line 53 of file ITemplateResource.cc.
{
}
ITemplateResource() [1/2]
ITemplateResource::ITemplateResource (TTAMachine::InstructionTemplate & templ, unsigned int initiationInterval = 0)
Constructor.
Parameters
name Name of template.
Definition at line 43 of file ITemplateResource.cc.
                                    :
    SchedulingResource(templ.name(), initiationInterval),
    template_(&templ){
}
ITemplateResource() [2/2]
ITemplateResource::ITemplateResource (const ITemplateResource &) private
Member Function Documentation
assign() [1/2]
void ITemplateResource::assign (const int cycle) virtual
Assign instruction template resource to given cycle.
Parameters
cycle Cycle to assign.
Definition at line 97 of file ITemplateResource.cc.
{
    if (canAssign(cycle)) {
        if (MapTools::containsKey(resourceRecord_, cycle)){
            resourceRecord_[instructionIndex(cycle)]++;
        } else {
            resourceRecord_[instructionIndex(cycle)] = 1;
        }
    }
}
References canAssign(), MapTools::containsKey(), SchedulingResource::instructionIndex(), and resourceRecord_.
assign() [2/2]
void ITemplateResource::assign (const int cycle, MoveNode & node) override virtual
The overridden method should be used instead.
Implements SchedulingResource.
Definition at line 87 of file ITemplateResource.cc.
{
    abortWithError("Not implemented!");
}
References abortWithError.
Referenced by ITemplateBroker::assign(), ITemplateBroker::assignImmediate(), ITemplateBroker::instruction(), and ITemplateBroker::reselectTemplate().
canAssign() [1/2]
bool ITemplateResource::canAssign (const int cycle) const virtual
Return true if instruction template resource can be assigned on given cycle.
Parameters
cycle Cycle to test.
Returns
True if template can be assigned to given cycle.
Definition at line 146 of file ITemplateResource.cc.
{
    return !isInUse(cycle);
}
References isInUse().
canAssign() [2/2]
bool ITemplateResource::canAssign (const int cycle, const MoveNode & node) const override virtual
The overridden method should be used instead.
Implements SchedulingResource.
Definition at line 134 of file ITemplateResource.cc.
{
    abortWithError("Not implemented!");
    return false;
}
References abortWithError.
Referenced by assign().
clear()
void ITemplateResource::clear () override virtual
Clears bookkeeping of the scheduling resource.
After this call the state of the resource should be identical to a newly-created and initialized resource.
Reimplemented from SchedulingResource.
Definition at line 204 of file ITemplateResource.cc.
{
    SchedulingResource::clear();
    resourceRecord_.clear();
}
References SchedulingResource::clear(), and resourceRecord_.
isAvailable()
bool ITemplateResource::isAvailable (const int cycle) const override virtual
Test if instruction tempalte resource is available in given cycle.
Parameters
cycle Cycle to test.
Returns
True if resource available in given cycle.
Implements SchedulingResource.
Definition at line 79 of file ITemplateResource.cc.
{
    return !isInUse(cycle);
}
References isInUse().
isInUse()
bool ITemplateResource::isInUse (const int cycle) const override virtual
Test if instruction template resource is used in given cycle.
Parameters
cycle Cycle to test.
Returns
True if resource is used in given cycle.
Implements SchedulingResource.
Definition at line 63 of file ITemplateResource.cc.
{
    if (MapTools::containsKey(resourceRecord_, instructionIndex(cycle))) {
        if (MapTools::valueForKey<int>(resourceRecord_, instructionIndex(cycle)) != 0) {
            return true;
        }
    }
    return false;
}
References MapTools::containsKey(), SchedulingResource::instructionIndex(), MapTools::keyForValue(), and resourceRecord_.
Referenced by canAssign(), isAvailable(), and unassign().
isITemplateResource()
bool ITemplateResource::isITemplateResource () const override virtual
Return true always.
Returns
True always.
Reimplemented from SchedulingResource.
Definition at line 156 of file ITemplateResource.cc.
{
    return true;
}
operator<()
bool ITemplateResource::operator< (const SchedulingResource & other) const override virtual
Comparison operator.
Favours itemplates with more nop slots.
Reimplemented from SchedulingResource.
Definition at line 214 of file ITemplateResource.cc.
{
    const ITemplateResource *itr = static_cast<const ITemplateResource*>(&other);
    if (itr == NULL) {
        return false;
    }
    return SchedulingResource::operator<(other);
}
References SchedulingResource::operator<().
operator=()
ITemplateResource & ITemplateResource::operator= (const ITemplateResource &) private
unassign() [1/2]
void ITemplateResource::unassign (const int cycle) virtual
Unassign instruction template from given cycle.
Parameters
cycle Cycle to remove assignment from.
Definition at line 123 of file ITemplateResource.cc.
{
    if (isInUse(cycle)) {
        resourceRecord_[instructionIndex(cycle)]--;
    }
}
References SchedulingResource::instructionIndex(), isInUse(), and resourceRecord_.
unassign() [2/2]
void ITemplateResource::unassign (const int cycle, MoveNode & node) override virtual
The overridden method should be used instead.
Implements SchedulingResource.
Definition at line 112 of file ITemplateResource.cc.
{
    abortWithError("Not implemented!");
}
References abortWithError.
Referenced by ITemplateBroker::assign(), ITemplateBroker::assignImmediate(), and ITemplateBroker::unassignImmediate().
validateDependentGroups()
bool ITemplateResource::validateDependentGroups () override protected virtual
Tests if all referred resources in dependent groups are of proper types.
Returns
True If all resources in dependent groups are immediate units or buses (move slots).
Reimplemented from SchedulingResource.
Definition at line 168 of file ITemplateResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (!(dependentResource(i, j).isIUResource() ||
                dependentResource(i, j).isBusResource())) {
                return false;
            }
        }
    }
    return true;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isBusResource(), and SchedulingResource::isIUResource().
validateRelatedGroups()
bool ITemplateResource::validateRelatedGroups () override protected virtual
Tests if related resource groups are empty.
Returns
True if related resource groups are empty.
Note
This resource type has no related resources.
Reimplemented from SchedulingResource.
Definition at line 187 of file ITemplateResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        if (relatedResourceCount(i) > 0) {
            return false;
        }
    }
    return true;
}
References SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
Member Data Documentation
resourceRecord_
ResourceRecordType ITemplateResource::resourceRecord_ private
Definition at line 82 of file ITemplateResource.hh.
Referenced by assign(), clear(), isInUse(), and unassign().
template_
TTAMachine::InstructionTemplate* ITemplateResource::template_ private
Definition at line 83 of file ITemplateResource.hh.
The documentation for this class was generated from the following files:
ITemplateResource.hh
ITemplateResource.cc