OpenASIP: TTAMachine::Bus Class Reference
TTAMachine::Bus Class Reference
#include <Bus.hh>
Public Member Functions
Bus (const std::string &name, int width, int immWidth, Machine::Extension extensionMode)
Bus (const ObjectState *state)
virtual ~Bus ()
virtual Bus * copy () const
virtual void copyGuardsTo (Bus &other) const
operator Segment & ()
virtual int position () const
int width () const
int immediateWidth () const
bool signExtends () const
bool zeroExtends () const
virtual void setName (const std::string &name)
virtual void setWidth (int width)
virtual void setImmediateWidth (int width)
virtual void setZeroExtends ()
virtual void setSignExtends ()
virtual void setExtensionMode (const Machine::Extension extension)
virtual void addSegment (Segment &segment)
virtual void removeSegment (Segment &segment)
virtual bool hasSegment (const std::string &name) const
virtual Segment * segment (int index) const
virtual Segment * segment (const std::string &name) const
virtual int segmentCount () const
virtual bool isConnectedTo (const Socket &socket) const
bool hasGuard (const Guard &guard) const
void addGuard (Guard &guard)
virtual void removeGuard (Guard &guard)
int guardCount () const
Guard * guard (int index) const
virtual bool hasNextBus () const
virtual bool hasPreviousBus () const
virtual Bus * nextBus () const
virtual Bus * previousBus () const
virtual bool canRead (const Bus &bus) const
virtual bool canWrite (const Bus &bus) const
virtual bool canReadWrite (const Bus &bus) const
virtual void setSourceBridge (Bridge &bridge)
virtual void setDestinationBridge (Bridge &bridge)
virtual void clearSourceBridge (Bridge &bridge)
virtual void clearDestinationBridge (Bridge &bridge)
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
virtual bool isArchitectureEqual (const Bus &bus) const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_BUS = "bus"
ObjectState name for Bus ObjectState.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bus width.
static const std::string OSKEY_IMMWIDTH = "immwidth"
ObjectState attribute key for immediate width.
static const std::string OSKEY_EXTENSION = "extension"
ObjectState attribute key for extension mode.
static const std::string OSVALUE_SIGN = "sign"
ObjectState attribute value for sign extension.
static const std::string OSVALUE_ZERO = "zero"
ObjectState attribute key for zero extension.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Types
typedef std::vector< Guard * > GuardTable
Vector of Guard pointers.
typedef std::vector< Segment * > SegmentTable
Vector of Segment pointers.
typedef std::vector< Bridge * > BridgeTable
Private Member Functions
Bus & operator= (const Bus &)
Assingment forbidden.
void loadStateWithoutReferences (const ObjectState *state)
void deleteAllSegments ()
void deleteAllGuards ()
Bridge * previousBridge () const
Bridge * nextBridge () const
Bridge * previousBridge (const BridgeTable &bridges) const
Bridge * nextBridge (const BridgeTable &bridges) const
void adjustSegmentChain (const ObjectState *busState)
Private Attributes
int width_
Bit width of the bus.
int immWidth_
Bit width of the inline immediate word.
Machine::Extension extensionMode_
Extension mode applied to the inline immediate word.
GuardTable guards_
Contains all guards of the bus.
SegmentTable segments_
Contains all the segments of the bus.
BridgeTable sourceBridges_
Contains the source bridges (max 2).
BridgeTable destinationBridges_
Contains the destination bridges (max 2).
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents a bus in TTA-processor.
Definition at line 53 of file Bus.hh.
Member Typedef Documentation
BridgeTable
typedef std::vector<Bridge*> TTAMachine::Bus::BridgeTable private
Definition at line 134 of file Bus.hh.
GuardTable
typedef std::vector<Guard*> TTAMachine::Bus::GuardTable private
Vector of Guard pointers.
Definition at line 130 of file Bus.hh.
SegmentTable
typedef std::vector<Segment*> TTAMachine::Bus::SegmentTable private
Vector of Segment pointers.
Definition at line 132 of file Bus.hh.
Constructor & Destructor Documentation
Bus() [1/2]
TTAMachine::Bus::Bus (const std::string & name, int width, int immWidth, Machine::Extension extensionMode)
Constructor.
Parameters
name Name of the bus.
width Bit width of the bus.
immWidth Bit width of the inline immediate word.
extensionMode Extension mode applied to the inline immediate word when it is narrower than the bus on which it is transported.
Exceptions
OutOfRange If the given width or immediate width is invalid.
InvalidName If the given name is not a valid component name.
Definition at line 74 of file Bus.cc.
    : Component(name),
      width_(width),
      immWidth_(immWidth),
      extensionMode_(extensionMode) {
    if (width <= 0 || immWidth < 0 || immWidth > width) {
        string procName = "Bus::Bus";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
}
References width().
Bus() [2/2]
TTAMachine::Bus::Bus (const ObjectState * state)
Constructor.
Loads the state of the bus from the given ObjectState instance. Does not load connections to sockets.
Parameters
state Root node of the ObjectState tree from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 98 of file Bus.cc.
                                 : Component(state) {
    try {
        loadStateWithoutReferences(state);
    } catch (Exception&) {
        deleteAllSegments();
        deleteAllGuards();
        throw;
    }
}
References deleteAllGuards(), deleteAllSegments(), and loadStateWithoutReferences().
~Bus()
TTAMachine::Bus::~Bus () virtual
Destructor.
Before destruction detaches all sockets from the bus.
Definition at line 113 of file Bus.cc.
          {
    unsetMachine();
    deleteAllSegments();
    deleteAllGuards();
}
References deleteAllGuards(), deleteAllSegments(), and unsetMachine().
Member Function Documentation
addGuard()
void TTAMachine::Bus::addGuard (Guard & guard)
Adds guard to the bus.
Parameters
guard Pointer to the Guard object to be added.
Exceptions
ComponentAlreadyExists If there is an equal guard already.
Definition at line 410 of file Bus.cc.
{
    if (hasGuard(guard)) {
        string procName = "Bus::addGuard";
        throw ComponentAlreadyExists(__FILE__, __LINE__, __func__,
                                     "Bus already has the given guard!");
    }
    guards_.push_back(&guard);
}
References __func__, guard(), guards_, and hasGuard().
Referenced by TTAMachine::PortGuard::PortGuard(), TTAMachine::PortGuard::PortGuard(), TTAMachine::RegisterGuard::RegisterGuard(), TTAMachine::RegisterGuard::RegisterGuard(), TTAMachine::UnconditionalGuard::UnconditionalGuard(), and TTAMachine::UnconditionalGuard::UnconditionalGuard().
addSegment()
void TTAMachine::Bus::addSegment (Segment & segment) virtual
Adds the given segment to this bus.
This method should be called by Segment constructor only.
Parameters
segment Segment to be added.
Exceptions
ComponentAlreadyExists If a segment with the same name as the given segment is already existing in this bus.
Definition at line 737 of file Bus.cc.
{
    // run time check: can be called from Segment constructor only
    assert(segment.parentBus() == NULL);
    if (hasSegment(segment.name())) {
        string procname = "Bus::addSegment";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procname);
    } else {
        segments_.push_back(&segment);
    }
}
References assert, hasSegment(), TTAMachine::Segment::name(), TTAMachine::Segment::parentBus(), segment(), and segments_.
Referenced by TTAMachine::Segment::Segment(), and TTAMachine::Segment::Segment().
adjustSegmentChain()
void TTAMachine::Bus::adjustSegmentChain (const ObjectState * busState) private
Adjusts the order of segments according to the order represented by the given ObjectState tree.
Parameters
busState ObjectState tree representing the state of this bus.
Exceptions
ObjectStateLoadingException If the segment chain is erroneus in the given ObjectState tree.
Definition at line 1027 of file Bus.cc.
{
    const string procName = "Bus::adjustSegmentChain";
    if (segmentCount() == 0) {
        assert(!busState->hasChild(Segment::OSNAME_SEGMENT));
        return;
    }
    MOMTextGenerator textGenerator;
    try {
        // find the last segment, the segment that has no destination
        Segment* lastSegment = NULL;
        for (int i = 0; i < busState->childCount(); i++) {
            ObjectState* childState = busState->child(i);
            if (childState->name() == Segment::OSNAME_SEGMENT &&
                !childState->hasAttribute(Segment::OSKEY_DESTINATION)) {
                string lastSegmentName =
                    childState->stringAttribute(Segment::OSKEY_NAME);
                lastSegment = segment(lastSegmentName);
                break;
            }
        }
        // if last segment was not found, throw
        if (lastSegment == NULL) {
            format errorMsg = textGenerator.text(
                MOMTextGenerator::TXT_NO_LAST_SEGMENT);
            errorMsg % name();
            throw ObjectStateLoadingException(
                __FILE__, __LINE__, procName, errorMsg.str());
        }
        Segment* destSegment = lastSegment;
        int modifications = 0;
        // in the following loop, find a segment whose destination should be
        // lastSegment and set it in front of that segment
        while (modifications < segmentCount() - 1) {
            bool chainModified = false;
            for (int i = 0; i < busState->childCount(); i++) {
                ObjectState* childState = busState->child(i);
                if (childState->name() == Segment::OSNAME_SEGMENT &&
                    childState->hasAttribute(Segment::OSKEY_DESTINATION)) {
                    string destName = childState->stringAttribute(
                        Segment::OSKEY_DESTINATION);
                    if (destName == destSegment->name()) {
                        string thisName = childState->
                            stringAttribute(Segment::OSKEY_NAME);
                        Segment* thisSegment = segment(thisName);
                        thisSegment->moveBefore(*destSegment);
                        destSegment = thisSegment;
                        modifications++;
                        chainModified = true;
                    }
                }
            }
            // if the source segment was not found and the segment chain is not
            // set completely yet, throw
            if (!chainModified && modifications < segmentCount() - 1) {
                format errorMsg = textGenerator.text(
                    MOMTextGenerator::TXT_NO_SOURCE_SEGMENT);
                errorMsg % name() % destSegment->name();
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName, errorMsg.str());
            }
        }
    } catch (Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References assert, ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::hasAttribute(), ObjectState::hasChild(), TTAMachine::Segment::moveBefore(), TTAMachine::Component::name(), TTAMachine::Segment::name(), ObjectState::name(), TTAMachine::Segment::OSKEY_DESTINATION, TTAMachine::Segment::OSKEY_NAME, TTAMachine::Segment::OSNAME_SEGMENT, segment(), segmentCount(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_NO_LAST_SEGMENT, and MOMTextGenerator::TXT_NO_SOURCE_SEGMENT.
Referenced by loadStateWithoutReferences().
canRead()
bool TTAMachine::Bus::canRead (const Bus & bus) const virtual
Checks if the bus can read from the given bus.
That is, checks if the given bus is source bus of this bus.
Parameters
bus The bus.
Returns
True if this bus can read from the given bus.
Definition at line 537 of file Bus.cc.
{
    BridgeTable::const_iterator iter = sourceBridges_.begin();
    while (iter != sourceBridges_.end()) {
        if ((*iter)->sourceBus() == &bus) {
            return true;
        }
        iter++;
    }
    return false;
}
References sourceBridges_.
Referenced by canReadWrite(), BEMValidator::needsSourceField(), and TTAMachine::Bridge::setSourceAndDestination().
canReadWrite()
bool TTAMachine::Bus::canReadWrite (const Bus & bus) const virtual
Check if the bus can both read from and write to the given bus.
That is, checks if the given bus is joined by a bidirectional bridge to this bus.
Parameters
bus The bus.
Returns
True if this bus can both read from and write to the given bus.
Definition at line 580 of file Bus.cc.
{
    return canWrite(bus) && canRead(bus);
}
References canRead(), and canWrite().
canWrite()
bool TTAMachine::Bus::canWrite (const Bus & bus) const virtual
Checks if the bus can write to the given bus.
That is, checks if the given bus is destination bus of this bus.
Parameters
bus The bus.
Returns
True if this bus can write to the given bus.
Definition at line 558 of file Bus.cc.
{
    BridgeTable::const_iterator iter = destinationBridges_.begin();
    while (iter != destinationBridges_.end()) {
        if ((*iter)->destinationBus() == &bus) {
            return true;
        }
        iter++;
    }
    return false;
}
References destinationBridges_.
Referenced by MachineTester::canBridge(), canReadWrite(), and TTAMachine::Bridge::setSourceAndDestination().
clearDestinationBridge()
void TTAMachine::Bus::clearDestinationBridge (Bridge & bridge) virtual
Removes a destination bridge from the bus.
This method can be called from Bridge destructor only. Do not call this method.
Parameters
bridge The destination bridge to remove.
Definition at line 652 of file Bus.cc.
{
    // run time check: can be called from Bridge destructor only
    assert(bridge.sourceBus() == NULL);
    bool removed = ContainerTools::removeValueIfExists(
        destinationBridges_, &bridge);
    assert(removed);
}
References assert, destinationBridges_, ContainerTools::removeValueIfExists(), and TTAMachine::Bridge::sourceBus().
Referenced by TTAMachine::Bridge::unsetMachine().
clearSourceBridge()
void TTAMachine::Bus::clearSourceBridge (Bridge & bridge) virtual
Removes a source bridge from the bus.
This method can be called from Bridge destructor only. Do not call this method.
Parameters
bridge The source bridge to remove.
Definition at line 632 of file Bus.cc.
{
    // run time check: can be called from Bridge destructor only
    assert(bridge.destinationBus() == NULL);
    bool removed = ContainerTools::removeValueIfExists(
        sourceBridges_, &bridge);
    assert(removed);
}
References assert, TTAMachine::Bridge::destinationBus(), ContainerTools::removeValueIfExists(), and sourceBridges_.
Referenced by TTAMachine::Bridge::unsetMachine().
copy()
Bus * TTAMachine::Bus::copy () const virtual
Copies the bus.
Returns
Copy of the Bus.
Definition at line 1145 of file Bus.cc.
                {
    ObjectState* newBusState = saveState();
    Bus* newBus = new Bus(newBusState);
    delete newBusState;
    newBusState = NULL;
    return newBus;
}
References saveState().
Referenced by MachineResourceModifier::addBusesByAmount().
copyGuardsTo()
void TTAMachine::Bus::copyGuardsTo (Bus & other) const virtual
Definition at line 1155 of file Bus.cc.
{
    for (int i = 0; i < guardCount(); ++i) {
        if (!other.hasGuard(*guard(i)))
            guard(i)->copyTo(other);
    }
}
References TTAMachine::Guard::copyTo(), guard(), guardCount(), and hasGuard().
Referenced by ADFCombiner::addAllGuardsToConnectionBuses(), and MachineResourceModifier::addBusesByAmount().
deleteAllGuards()
void TTAMachine::Bus::deleteAllGuards () private
Deletes all the guards.
Definition at line 930 of file Bus.cc.
                     {
    // guard destructor removes the pointer from the table
    while (guards_.size() > 0) {
        delete guards_[0];
    }
}
References guards_.
Referenced by Bus(), loadState(), and ~Bus().
deleteAllSegments()
void TTAMachine::Bus::deleteAllSegments () private
Deletes all the segments.
Definition at line 918 of file Bus.cc.
                       {
    // segment destructor removes the pointer from the table
    while (segments_.size() > 0) {
        delete segments_[0];
    }
}
References segments_.
Referenced by Bus(), loadState(), and ~Bus().
guard()
Guard * TTAMachine::Bus::guard (int index) const
Returns the guard by the given index.
The index must be between 0 and the return value of numberOfGuards() - 1.
Parameters
index Index.
Returns
The guard by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 456 of file Bus.cc.
{
    if (index < 0 || static_cast<size_t>(index) >= guards_.size()) {
        string procName = "Bus::guard";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return guards_[index];
}
References guards_.
Referenced by BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), addGuard(), BusBroker::allAvailableResources(), TDGen::analyzeRegisters(), BusBroker::assign(), MachineStateBuilder::buildMachineState(), BusBroker::canTransportImmediate(), ProgrammabilityValidator::checkBooleanRegister(), BEMValidator::checkGuardField(), TTAMachine::FunctionUnit::cleanupGuards(), TTAMachine::FUPort::cleanupGuards(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::copyGuards(), copyGuardsTo(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), ProgramDependenceGraph::createJump(), TTAMachine::RegisterFile::deleteGuards(), PasteComponentCmd::Do(), findBooleanGuard(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), RegisterRenamer::findGuardRegisters(), RegisterQuantityCheck::findGuardRegisters(), ProgrammabilityValidator::findRegisterGuard(), RegisterCopyAdder::findTempRegisters(), MachineConnectivityCheck::hasBothGuards(), MachineConnectivityCheck::hasConditionalMoves(), hasGuard(), BusBroker::hasGuard(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), BEMGenerator::hasUnconditionalGuard(), isArchitectureEqual(), BusBroker::isAvailable(), TTAMachine::RegisterFile::isUsedAsGuard(), MachineInfo::longestGuardLatency(), RFGuardDialog::onOK(), BusDialog::onUnconditionalGuard(), BFLateBypassGuard::operator()(), MachineResourceManager::registerFileIndexReference(), removeGuard(), RegisterRenamer::renameLiveRange(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), MachineResourceManager::rFPortOrFUIndexReference(), saveState(), BFRenameLiveRange::setGuard(), BusDialog::updateGuardLists(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
guardCount()
int TTAMachine::Bus::guardCount () const
Returns the number of guards in the bus.
Returns
The number of guards in the bus.
Definition at line 441 of file Bus.cc.
                      {
    return guards_.size();
}
References guards_.
Referenced by BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addSubfields(), BusBroker::allAvailableResources(), TDGen::analyzeRegisters(), BusBroker::assign(), MachineStateBuilder::buildMachineState(), BusBroker::buildResources(), BusBroker::canTransportImmediate(), ProgrammabilityValidator::checkBooleanRegister(), BEMValidator::checkGuardField(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::copyGuards(), copyGuardsTo(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), ProgramDependenceGraph::createJump(), PasteComponentCmd::Do(), findBooleanGuard(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), RegisterRenamer::findGuardRegisters(), RegisterQuantityCheck::findGuardRegisters(), ProgrammabilityValidator::findRegisterGuard(), RegisterCopyAdder::findTempRegisters(), MachineConnectivityCheck::hasBothGuards(), MachineConnectivityCheck::hasConditionalMoves(), BusBroker::hasGuard(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), BEMGenerator::hasUnconditionalGuard(), isArchitectureEqual(), BusBroker::isAvailable(), MachineInfo::longestGuardLatency(), MachineAnalysis::MachineAnalysis(), RFGuardDialog::onOK(), BusDialog::onUnconditionalGuard(), BFLateBypassGuard::operator()(), MachineResourceManager::registerFileIndexReference(), RegisterRenamer::renameLiveRange(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), MachineResourceManager::rFPortOrFUIndexReference(), saveState(), BFRenameLiveRange::setGuard(), BusDialog::updateGuardLists(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
hasGuard()
bool TTAMachine::Bus::hasGuard (const Guard & guard) const
Checks whether the bus has the given guard.
Definition at line 393 of file Bus.cc.
{
    for (GuardTable::const_iterator iter = guards_.begin();
         iter != guards_.end(); iter++) {
        if ((*iter)->isEqual(guard)) {
            return true;
        }
    }
    return false;
}
References guard(), and guards_.
Referenced by addGuard(), MachineConnectivityCheck::canTransportImmediate(), ADFCombiner::connectRegisterFiles(), and copyGuardsTo().
hasNextBus()
bool TTAMachine::Bus::hasNextBus () const virtual
Checks if the bus has next bus.
Next does not mean destination bus in that case but the next bus from location point of view.
Returns
True if the bus has next bus, otherwise false.
Definition at line 488 of file Bus.cc.
                      {
    Bridge* nextBridge = this->nextBridge();
    return nextBridge != NULL;
}
References nextBridge().
Referenced by TTAMachine::Bridge::adjustChainDirection(), MachineTester::areInSameChain(), MachineTester::canBridge(), MachineEditPartFactory::getBusChains(), BEMValidator::needsSourceField(), and TTAMachine::Bridge::setFirstOfChain().
hasPreviousBus()
bool TTAMachine::Bus::hasPreviousBus () const virtual
Checks if the bus has previous bus.
Previous does not mean source in that case but the previous bus from location point of view.
Returns
True if the bus has previous bus, otherwise false.
Definition at line 473 of file Bus.cc.
{
    Bridge* prevBridge = previousBridge();
    return prevBridge != NULL;
}
References previousBridge().
Referenced by MachineTester::areInSameChain(), MachineTester::canBridge(), MachineEditPartFactory::getBusChains(), BEMValidator::needsSourceField(), and TTAMachine::Bridge::setFirstOfChain().
hasSegment()
bool TTAMachine::Bus::hasSegment (const std::string & name) const virtual
Returns true if the bus has a segment with the given name.
Parameters
name Name of the segment.
Returns
True if the bus has a segment with the given name, otherwise false.
Definition at line 284 of file Bus.cc.
{
    SegmentTable::const_iterator iter = segments_.begin();
    while (iter != segments_.end()) {
        if ((*iter)->name() == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References TTAMachine::Component::name(), and segments_.
Referenced by addSegment(), ADFCombiner::createBus(), TTAMachine::Segment::loadStateWithoutReferences(), and BusDialog::onAddSegment().
immediateWidth()
int TTAMachine::Bus::immediateWidth () const
Returns the bit width of the inline immediate word.
Returns
Bit width of the inline immediate word.
Definition at line 160 of file Bus.cc.
{
    return immWidth_;
}
References immWidth_.
Referenced by BEMGenerator::addEncodings(), DefaultICGenerator::addICToNetlist(), BusBroker::buildResources(), MachineInfo::canEncodeImmediateInteger(), MachineConnectivityCheck::canTransportImmediate(), MachineConnectivityCheck::canWriteAllImmediates(), BEMValidator::checkSourceField(), DefaultDecoderGenerator::completeDecoderBlock(), TTAProgram::ProgramWriter::createCodeSection(), DefaultICGenerator::createSignalsForIC(), TTAProgram::TPEFProgramFactory::createTerminal(), ProGe::RV32MicroCodeGenerator::findConnectedBusses(), DefaultICGenerator::generateSocketsAndMuxes(), ProDeBusEditPolicy::getCommand(), isArchitectureEqual(), CompiledSimSymbolGenerator::moveOperandSymbol(), BEMValidator::needsSourceField(), SimProgramBuilder::processMove(), BusBroker::setupResourceLinks(), DefaultDecoderGenerator::simmPortWidth(), DefaultICGenerator::simmPortWidth(), BusDialog::TransferDataToWindow(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), and DefaultDecoderGenerator::writeSocketCntrlSignals().
isArchitectureEqual()
bool TTAMachine::Bus::isArchitectureEqual (const Bus & bus) const virtual
Checks is this bus architecture equal with the given bus.
Architecture equality means that buses have same widths, immediate widths, extension modes, number of segments and same guards. Bridges are not checked.
Parameters
bus Bus to compare with.
Returns
True if the buses are architecture equal.
Definition at line 1111 of file Bus.cc.
{
    if (width() != bus.width() ||
        immediateWidth() != bus.immediateWidth() ||
        signExtends() != bus.signExtends() ||
        segmentCount() != bus.segmentCount()) {
        return false;
    }
    for (int i = 0; i < guardCount(); i++) {
        bool match = false;
        // check if there is matching guard in another bus
        for (int j = 0; j < bus.guardCount(); j++) {
            if (guard(i)->isEqual(*bus.guard(j))) {
                match = true;
                break;
            }
        }
        // if no matching guard was not found buses are not equal
        if (match == false) {
            return false;
        }
        // otherwise continue to next guard
    }
    return true;
}
References guard(), guardCount(), immediateWidth(), TTAMachine::Guard::isEqual(), segmentCount(), signExtends(), and width().
Referenced by MachineResourceModifier::analyzeBuses().
isConnectedTo()
bool TTAMachine::Bus::isConnectedTo (const Socket & socket) const virtual
Returns true if the bus is connected to the given socket, otherwise false.
Parameters
socket Socket.
Returns
True if the bus is connected to the given socket, otherwise false.
Definition at line 303 of file Bus.cc.
{
    SegmentTable::const_iterator iter = segments_.begin();
    while (iter != segments_.end()) {
        if ((*iter)->isConnectedTo(socket)) {
            return true;
        }
        iter++;
    }
    return false;
}
References segments_.
Referenced by DefaultICDecoderEstimator::busParameters().
loadState()
void TTAMachine::Bus::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the name of this bus becomes the same as an existing bus in the same machine or if generating references to other components did not succeed.
Reimplemented from TTAMachine::Component.
Definition at line 816 of file Bus.cc.
{
    deleteAllSegments();
    deleteAllGuards();
    // load state without references to other machine parts
    try {
        loadStateWithoutReferences(state);
        // create guards and load states of segments
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* childState = state->child(i);
            if (childState->name() == PortGuard::OSNAME_PORT_GUARD) {
                // guard is registered automatically
                new PortGuard(childState, *this);
            } else if (childState->name() ==
                       RegisterGuard::OSNAME_REGISTER_GUARD) {
                // guard is registered automatically
                new RegisterGuard(childState, *this);
            } else if (childState->name() ==
                       UnconditionalGuard::OSNAME_UNCONDITIONAL_GUARD) {
                // guard is registered automatically.
                new UnconditionalGuard(childState, *this);
            } else if (childState->name() == Segment::OSNAME_SEGMENT) {
                string segmentName =
                    childState->stringAttribute(Segment::OSKEY_NAME);
                Segment* segment = this->segment(segmentName);
                segment->loadState(childState);
            }
        }
    } catch (Exception& exception) {
        const string procName = "Bus::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References ObjectState::child(), ObjectState::childCount(), deleteAllGuards(), deleteAllSegments(), Exception::errorMessage(), TTAMachine::Segment::loadState(), loadStateWithoutReferences(), ObjectState::name(), TTAMachine::Segment::OSKEY_NAME, TTAMachine::PortGuard::OSNAME_PORT_GUARD, TTAMachine::RegisterGuard::OSNAME_REGISTER_GUARD, TTAMachine::Segment::OSNAME_SEGMENT, TTAMachine::UnconditionalGuard::OSNAME_UNCONDITIONAL_GUARD, segment(), and ObjectState::stringAttribute().
Referenced by TTAMachine::Machine::loadState().
loadStateWithoutReferences()
void TTAMachine::Bus::loadStateWithoutReferences (const ObjectState * state) private
Loads the state of the object from the given ObjectState tree without references to other components/subcomponents.
Parameters
state Root node of the ObjectState tree.
Exceptions
ObjectStateLoadingException If a bus by the same name is already registered to the same machine or if the given ObjectState tree is invalid.
Definition at line 863 of file Bus.cc.
{
    const string procName = "Bus::loadStateWithoutReferences";
    if (state->name() != OSNAME_BUS) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName,
            "Invalid XML object state for a bus, name: " + state->name());
    }
    Component::loadState(state);
    // read attributes
    try {
        setWidth(state->intAttribute(OSKEY_WIDTH));
        setImmediateWidth(state->intAttribute(OSKEY_IMMWIDTH));
        string extensionMode = state->stringAttribute(OSKEY_EXTENSION);
        if (extensionMode == OSVALUE_SIGN) {
            setSignExtends();
        } else if (extensionMode == OSVALUE_ZERO) {
            setZeroExtends();
        } else {
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
        }
    } catch (Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
    // create all segments, guards are not created because they are
    // completely useless without references
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == Segment::OSNAME_SEGMENT) {
            try {
                // segment is attached automatically
                new Segment(child, *this);
            } catch (const ComponentAlreadyExists&) {
                MOMTextGenerator textGen;
                format errorMsg = textGen.text(
                    MOMTextGenerator::TXT_SEGMENT_WITH_SAME_NAME);
                errorMsg % child->stringAttribute(Segment::OSKEY_NAME) %
                    name();
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName, errorMsg.str());
            }
        }
    }
    adjustSegmentChain(state);
}
References adjustSegmentChain(), ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::intAttribute(), TTAMachine::Component::loadState(), TTAMachine::Component::name(), ObjectState::name(), OSKEY_EXTENSION, OSKEY_IMMWIDTH, TTAMachine::Segment::OSKEY_NAME, OSKEY_WIDTH, OSNAME_BUS, TTAMachine::Segment::OSNAME_SEGMENT, OSVALUE_SIGN, OSVALUE_ZERO, setImmediateWidth(), setSignExtends(), setWidth(), setZeroExtends(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_SEGMENT_WITH_SAME_NAME.
Referenced by Bus(), and loadState().
nextBridge() [1/2]
Bridge * TTAMachine::Bus::nextBridge () const private
Returns a bridge that joins this bus and the next bus of this bus.
If there is two such bridges, returns one of them. If there is no such a bridge, returns NULL.
Returns
Next bridge or NULL.
Definition at line 965 of file Bus.cc.
                      {
    Bridge* nextBridge = this->nextBridge(sourceBridges_);
    if (nextBridge == NULL) {
        nextBridge = this->nextBridge(destinationBridges_);
    }
    return nextBridge;
}
References destinationBridges_, nextBridge(), and sourceBridges_.
Referenced by hasNextBus(), nextBridge(), and nextBus().
nextBridge() [2/2]
Bridge * TTAMachine::Bus::nextBridge (const BridgeTable & bridges) const private
Returns a bridge that joins this bus and the next bus of this bus.
Returns NULL if such a bridge does not exist.
Parameters
bridge The bridge table to look for the bridge.
Returns
The next bridge.
Definition at line 1005 of file Bus.cc.
{
    BridgeTable::const_iterator iter = bridges.begin();
    while (iter != bridges.end()) {
        Bridge* bridge = *iter;
        if (bridge->previousBus() == this) {
            return bridge;
        }
        iter++;
    }
    return NULL;
}
References TTAMachine::Bridge::previousBus().
nextBus()
Bus * TTAMachine::Bus::nextBus () const virtual
Returns the next bus from the location point of view.
Returns
The next bus.
Exceptions
InstanceNotFound If the bus is the last in the chain.
Definition at line 501 of file Bus.cc.
                   {
    Bridge* nextBridge = this->nextBridge();
    if (nextBridge != NULL) {
        return nextBridge->nextBus();
    } else {
        string procName = "Bus::nextBus";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
}
References nextBridge(), and TTAMachine::Bridge::nextBus().
Referenced by TTAMachine::Bridge::adjustChainDirection(), MachineTester::areInSameChain(), MachineTester::canBridge(), MachineEditPartFactory::findConnectedBridges(), MachineEditPartFactory::getBusChains(), and BEMValidator::needsSourceField().
operator Segment &()
TTAMachine::Bus::operator Segment & () inline
Definition at line 62 of file Bus.hh.
{ return *this->segment(0); }
References segment().
operator=()
Bus & TTAMachine::Bus::operator= (const Bus &) private
Assingment forbidden.
position()
int TTAMachine::Bus::position () const virtual
Returns the position of the bus in move slot order.
Returns
The position (0 is the first position).
Exceptions
NotAvailable If the bus is not registered to a machine.
Definition at line 127 of file Bus.cc.
                    {
    if (!isRegistered()) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    }
    Machine::BusNavigator busNav = machine()->busNavigator();
    for (int i = 0; i < busNav.count(); i++) {
        if (busNav.item(i) == this) {
            return i;
        }
    }
    assert(false);
    return 0;
}
References __func__, assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), and TTAMachine::Component::machine().
Referenced by BusFactory::createEditPart().
previousBridge() [1/2]
Bridge * TTAMachine::Bus::previousBridge () const private
Returns a bridge that joins this bus and the previous bus of this bus.
If there is two such bridges, returns one of them. If there is no such a bridge, returns NULL.
Returns
Previous bridge or NULL.
Definition at line 947 of file Bus.cc.
{
    Bridge* prevBridge = previousBridge(sourceBridges_);
    if (prevBridge == NULL) {
        prevBridge = previousBridge(destinationBridges_);
    }
    return prevBridge;
}
References destinationBridges_, previousBridge(), and sourceBridges_.
Referenced by hasPreviousBus(), previousBridge(), and previousBus().
previousBridge() [2/2]
Bridge * TTAMachine::Bus::previousBridge (const BridgeTable & bridges) const private
Returns a bridge that joins this bus and the previous bus of this bus.
Returns NULL if such a bridge does not exist.
Parameters
bridge The bridge table to look for the bridge.
Returns
The previous bridge.
Definition at line 983 of file Bus.cc.
{
    BridgeTable::const_iterator iter = bridges.begin();
    while (iter != bridges.end()) {
        Bridge* bridge = *iter;
        if (bridge->nextBus() == this) {
            return bridge;
        }
        iter++;
    }
    return NULL;
}
References TTAMachine::Bridge::nextBus().
previousBus()
Bus * TTAMachine::Bus::previousBus () const virtual
Returns the previous bus from the location point of view.
Returns
The previous bus.
Exceptions
InstanceNotFound If the bus is the first in the chain.
Definition at line 518 of file Bus.cc.
                       {
    Bridge* prevBridge = previousBridge();
    if (prevBridge != NULL) {
        return prevBridge->previousBus();
    } else {
        string procName = "Bus::previousBus";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
}
References previousBridge(), and TTAMachine::Bridge::previousBus().
Referenced by MachineTester::areInSameChain(), MachineTester::canBridge(), MachineEditPartFactory::getBusChains(), BEMValidator::needsSourceField(), and TTAMachine::Bridge::setFirstOfChain().
removeGuard()
void TTAMachine::Bus::removeGuard (Guard & guard) virtual
Removes the given guard from the bus.
This method should be called by Guard destructor only.
Parameters
guard Guard to be removed.
Definition at line 428 of file Bus.cc.
{
    // run time check: can be called from Guard destructor only
    assert(guard.parentBus() == NULL);
    ContainerTools::removeValueIfExists(guards_, &guard);
}
References assert, guard(), guards_, TTAMachine::Guard::parentBus(), and ContainerTools::removeValueIfExists().
Referenced by TTAMachine::Guard::~Guard().
removeSegment()
void TTAMachine::Bus::removeSegment (Segment & segment) virtual
Removes the given segment from the bus.
This method should be called by Segment destructor only.
Parameters
segment Segment to be removed.
Definition at line 757 of file Bus.cc.
{
    // run time check: can be called from Segment destructor only
    assert(segment.parentBus() == NULL);
    bool removed = ContainerTools::removeValueIfExists(segments_, &segment);
    assert(removed);
}
References assert, TTAMachine::Segment::parentBus(), ContainerTools::removeValueIfExists(), segment(), and segments_.
Referenced by TTAMachine::Segment::~Segment().
saveState()
ObjectState * TTAMachine::Bus::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
Root of the created tree.
Reimplemented from TTAMachine::Component.
Definition at line 773 of file Bus.cc.
                     {
    ObjectState* busState = Component::saveState();
    // change the name of the ObjectState
    busState->setName(OSNAME_BUS);
    // set attributes
    busState->setAttribute(OSKEY_WIDTH, width_);
    busState->setAttribute(OSKEY_IMMWIDTH, immWidth_);
    if (extensionMode_ == Machine::SIGN) {
        busState->setAttribute(OSKEY_EXTENSION, OSVALUE_SIGN);
    } else if (extensionMode_ == Machine::ZERO) {
        busState->setAttribute(OSKEY_EXTENSION, OSVALUE_ZERO);
    }
    // add segments
    for (int i = 0; i < segmentCount(); i++) {
        Segment* seg = segment(i);
        busState->addChild(seg->saveState());
    }
    // save guards
    for (int i = 0; i < guardCount(); i++) {
        Guard* currentGuard = guard(i);
        busState->addChild(currentGuard->saveState());
    }
    return busState;
}
References ObjectState::addChild(), extensionMode_, guard(), guardCount(), immWidth_, OSKEY_EXTENSION, OSKEY_IMMWIDTH, OSKEY_WIDTH, OSNAME_BUS, OSVALUE_SIGN, OSVALUE_ZERO, TTAMachine::Guard::saveState(), TTAMachine::Component::saveState(), TTAMachine::Segment::saveState(), segment(), segmentCount(), ObjectState::setAttribute(), ObjectState::setName(), TTAMachine::Machine::SIGN, width_, and TTAMachine::Machine::ZERO.
Referenced by copy().
segment() [1/2]
Segment * TTAMachine::Bus::segment (const std::string & name) const virtual
Returns the segment which has the given name.
Parameters
name Name of the segment.
Returns
Segment which has the given name.
Exceptions
InstanceNotFound If the bus does not contain a segment by the given name.
Definition at line 365 of file Bus.cc.
{
    SegmentTable::const_iterator iter = segments_.begin();
    while (iter != segments_.end()) {
        if ((*iter)->name() == name) {
            return *iter;
        }
        iter++;
    }
    // requested segment not found
    string procName = "Bus::segment";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
}
References TTAMachine::Component::name(), and segments_.
segment() [2/2]
Segment * TTAMachine::Bus::segment (int index) const virtual
Returns the bus segment at a given index.
The index must be greater or equal to 0 and less than the number of segments. The segments are returned in the correct order. Thus, index 0 returns the first segment in the segment chain, index 1 returns its destination segment and so on.
Parameters
index Index.
Returns
The segment found on the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 329 of file Bus.cc.
{
    if (index < 0 || index >= segmentCount()) {
        string procName = "Bus::segment";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    // find the first segment of the chain
    Segment* firstSegment = NULL;
    SegmentTable::const_iterator iter = segments_.begin();
    while (iter != segments_.end()) {
        Segment* segment = *iter;
        if (!segment->hasSourceSegment()) {
            firstSegment = segment;
            break;
        }
        iter++;
    }
    // follow the segment chain until the requested segment is reached
    Segment* nextSegment = firstSegment;
    for (int i = 0; i < index; i++) {
        nextSegment = nextSegment->destinationSegment();
    }
    return nextSegment;
}
References TTAMachine::Segment::destinationSegment(), TTAMachine::Segment::hasSourceSegment(), segment(), segmentCount(), and segments_.
Referenced by ADFCombiner::addBuses(), SimpleICOptimizer::addConnections(), addSegment(), adjustSegmentChain(), FullyConnectedCheck::attachSocketToAllBusses(), BusBroker::buildResources(), DefaultDecoderGenerator::busCntrlSignalPinOfSocket(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), BusFactory::createEditPart(), ADFCombiner::createPortsAndSockets(), BlocksTranslator::Deinitialize(), TTAMachine::Socket::detachBus(), InfoBussesCommand::execute(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::inputSockets(), DefaultICGenerator::isBusConnected(), TTAMachine::Socket::isConnectedTo(), ProgrammabilityValidator::listConnections(), loadState(), TTAMachine::Socket::loadState(), CostEstimator::Estimator::longestPath(), BEMValidator::needsSourceField(), operator Segment &(), DefaultICGenerator::outputSockets(), removeSegment(), saveState(), TTAMachine::Segment::Segment(), segment(), BusDialog::selectedSegment(), TTAMachine::Segment::setName(), BusBroker::setupResourceLinks(), BEMGenerator::socket(), FullyConnectedCheck::socketAttachedToAllBusses(), BEMGenerator::socketCount(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), SocketDialog::updateConnected(), BusDialog::updateSegmentList(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
segmentCount()
int TTAMachine::Bus::segmentCount () const virtual
Returns the number of segments in this bus.
Returns
Number of segments in this bus.
Definition at line 385 of file Bus.cc.
{
    return segments_.size();
}
References segments_.
Referenced by ADFCombiner::addBuses(), SimpleICOptimizer::addConnections(), adjustSegmentChain(), FullyConnectedCheck::attachSocketToAllBusses(), BusBroker::buildResources(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), BusFactory::createEditPart(), TTAMachine::Socket::detachBus(), InfoBussesCommand::execute(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::inputSockets(), isArchitectureEqual(), DefaultICGenerator::isBusConnected(), TTAMachine::Socket::isConnectedTo(), ProgrammabilityValidator::listConnections(), BEMValidator::needsSourceField(), DefaultICGenerator::outputSockets(), saveState(), TTAMachine::Segment::Segment(), segment(), TTAMachine::Segment::setName(), BusBroker::setupResourceLinks(), BEMGenerator::socket(), FullyConnectedCheck::socketAttachedToAllBusses(), BEMGenerator::socketCount(), SocketDialog::updateConnected(), BusDialog::updateSegmentList(), and DefaultICGenerator::verifyCompatibility().
setDestinationBridge()
void TTAMachine::Bus::setDestinationBridge (Bridge & bridge) virtual
Adds a destination bridge for the bus.
This method can be called from methods of Bridge only. Do not call this method.
Parameters
bridge The destination bridge to add.
Definition at line 613 of file Bus.cc.
{
    // run time check: can be called from Bridge methods only
    assert(bridge.sourceBus() == NULL);
    assert(destinationBridges_.size() < 2);
    destinationBridges_.push_back(&bridge);
}
References assert, destinationBridges_, and TTAMachine::Bridge::sourceBus().
Referenced by TTAMachine::Bridge::setSourceAndDestination().
setExtensionMode()
void TTAMachine::Bus::setExtensionMode (const Machine::Extension extension) virtual
Sets the extension mode.
Definition at line 271 of file Bus.cc.
{
    extensionMode_ = extension;
}
References extensionMode_.
setImmediateWidth()
void TTAMachine::Bus::setImmediateWidth (int width) virtual
Sets the number of bits of inline immediates.
Parameters
width The bit width of inline immediates.
Exceptions
OutOfRange If the given width is negative or greater than the bit width of the bus.
Definition at line 241 of file Bus.cc.
{
    if (width < 0 || width > this->width()) {
        string procName = "Bus::setImmediateWidth";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    immWidth_ = width;
}
References immWidth_, and width().
Referenced by VLIWConnectIC::explore(), loadStateWithoutReferences(), and BusDialog::onOK().
setMachine()
void TTAMachine::Bus::setMachine (Machine & mach) virtual
Registers the bus to a machine.
Parameters
mach Machine to which the bus is going to be registered.
Exceptions
ComponentAlreadyExists If the given machine already has another bus by the same name.
Implements TTAMachine::Component.
Definition at line 671 of file Bus.cc.
{
    internalSetMachine(mach);
    mach.addBus(*this);
}
References TTAMachine::Machine::addBus(), and TTAMachine::Component::internalSetMachine().
Referenced by AddBusCmd::Do().
setName()
void TTAMachine::Bus::setName (const std::string & name) virtual
Sets the name of the bus.
Parameters
name Name of the bus.
Exceptions
ComponentAlreadyExists If a bus with the given name is already in the same machine.
InvalidName If the given name is not a valid component name.
Reimplemented from TTAMachine::Component.
Definition at line 196 of file Bus.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->busNavigator().hasItem(name) ||
            machine()->immediateSlotNavigator().hasItem(name)) {
            string procName = "Bus::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by ADFCombiner::addBuses(), MachineResourceModifier::addBusesByAmount(), and BusDialog::onOK().
setSignExtends()
void TTAMachine::Bus::setSignExtends () virtual
Sets the sign extension mode.
Definition at line 262 of file Bus.cc.
                    {
    extensionMode_ = Machine::SIGN;
}
References extensionMode_, and TTAMachine::Machine::SIGN.
Referenced by loadStateWithoutReferences(), and BusDialog::onOK().
setSourceBridge()
void TTAMachine::Bus::setSourceBridge (Bridge & bridge) virtual
Adds a source bridge for the bus.
This method can be called from methods of Bridge only. Do not call this method.
Parameters
bridge The source bridge to add.
Definition at line 594 of file Bus.cc.
{
    // run time check: can be called from Bridge methods only
    assert(bridge.destinationBus() == NULL);
    assert(sourceBridges_.size() < 2);
    sourceBridges_.push_back(&bridge);
}
References assert, TTAMachine::Bridge::destinationBus(), and sourceBridges_.
Referenced by TTAMachine::Bridge::setSourceAndDestination().
setWidth()
void TTAMachine::Bus::setWidth (int width) virtual
Sets the bit width of the bus.
Parameters
width The new bit width of the bus.
Exceptions
OutOfRange If the given width is less or equal to zero or if there is an instruction template that has greater bit width for this slot.
Definition at line 223 of file Bus.cc.
                       {
    const string procName = "Bus::setWidth";
    if (width <= 0) {
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    width_ = width;
}
References width(), and width_.
Referenced by loadStateWithoutReferences(), and BusDialog::onOK().
setZeroExtends()
void TTAMachine::Bus::setZeroExtends () virtual
Sets the zero extension mode.
Definition at line 253 of file Bus.cc.
                    {
    extensionMode_ = Machine::ZERO;
}
References extensionMode_, and TTAMachine::Machine::ZERO.
Referenced by loadStateWithoutReferences(), and BusDialog::onOK().
signExtends()
bool TTAMachine::Bus::signExtends () const
Returns true if the bus uses sign extension.
Returns
True if the bus uses sign extension.
Definition at line 171 of file Bus.cc.
                       {
    return extensionMode_ == Machine::SIGN;
}
References extensionMode_, and TTAMachine::Machine::SIGN.
Referenced by MachineInfo::canEncodeImmediateInteger(), MachineConnectivityCheck::canTransportImmediate(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createMove(), ProDeBusEditPolicy::getCommand(), isArchitectureEqual(), CompiledSimSymbolGenerator::moveOperandSymbol(), SimProgramBuilder::processMove(), BusBroker::setupResourceLinks(), DefaultDecoderGenerator::simmPortWidth(), DefaultICGenerator::simmPortWidth(), BusDialog::TransferDataToWindow(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), DefaultICGenerator::writeInterconnectionNetwork(), and DefaultDecoderGenerator::writeSimmDataSignal().
unsetMachine()
void TTAMachine::Bus::unsetMachine () virtual
Removes registration of the bus from its current machine.
Detaches all the sockets attached to the bus and deletes all the guards and modifies instruction templates to not use this bus.
Implements TTAMachine::Component.
Definition at line 683 of file Bus.cc.
                  {
    Machine* mach = machine();
    if (mach == NULL) {
        return;
    }
    internalUnsetMachine();
    // detach all sockets
    SegmentTable::iterator iter = segments_.begin();
    while (iter != segments_.end()) {
        (*iter)->detachAllSockets();
        iter++;
    }
    // delete bridges
    Machine::BridgeNavigator bNavigator = mach->bridgeNavigator();
    for (int i = 0; i < bNavigator.count();) {
        if (bNavigator.item(i)->sourceBus() == this ||
            bNavigator.item(i)->destinationBus() == this) {
            // deleting bridge removes it automatically from the container,
            // no iterator increment needed
            delete bNavigator.item(i);
        } else {
            i++;
        }
    }
    // delete the template slot that uses the bus
    Machine::InstructionTemplateNavigator itNav =
        mach->instructionTemplateNavigator();
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* it = itNav.item(i);
        it->removeSlot(name());
    }
    mach->removeBus(*this);
}
References TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Component::internalUnsetMachine(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::Machine::removeBus(), TTAMachine::InstructionTemplate::removeSlot(), and segments_.
Referenced by ~Bus().
width()
int TTAMachine::Bus::width () const
Returns the bit width of the bus.
Returns
Bit width of the bus.
Definition at line 149 of file Bus.cc.
                 {
    return width_;
}
References width_.
Referenced by ImmediateGenerator::addSplitInsTemplate(), MachineStateBuilder::buildMachineState(), BusBroker::buildResources(), Bus(), MachineInfo::canEncodeImmediateInteger(), ProGe::RV32MicroCodeGenerator::constructBInstructions(), ProGe::RV32MicroCodeGenerator::constructIInstructions(), ProGe::RV32MicroCodeGenerator::constructSInstructions(), ProGe::RV32MicroCodeGenerator::constructUJInstructions(), SegmentFactory::createEditPart(), DefaultICGenerator::createSignalsForIC(), MachineResourceManager::findBusWidth(), ProgrammabilityValidator::findGlobalConnectionRegister(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProDeBusEditPolicy::getCommand(), isArchitectureEqual(), SimProgramBuilder::processMove(), setImmediateWidth(), setWidth(), DefaultDecoderGenerator::simmPortWidth(), DefaultICGenerator::simmPortWidth(), DefaultICDecoderEstimator::socketParameters(), BusDialog::TransferDataToWindow(), PostpassOperandSharer::tryRemoveOperandWrite(), DefaultICGenerator::writeBusDumpCode(), and DefaultICGenerator::writeInterconnectionNetwork().
zeroExtends()
bool TTAMachine::Bus::zeroExtends () const
Returns true if the bus uses zero extension.
Returns
True if the bus uses zero extension.
Definition at line 182 of file Bus.cc.
                       {
    return extensionMode_ == Machine::ZERO;
}
References extensionMode_, and TTAMachine::Machine::ZERO.
Referenced by CompiledSimSymbolGenerator::moveOperandSymbol(), DefaultDecoderGenerator::simmPortWidth(), DefaultICGenerator::simmPortWidth(), and DefaultICGenerator::writeInterconnectionNetwork().
Member Data Documentation
destinationBridges_
BridgeTable TTAMachine::Bus::destinationBridges_ private
Contains the destination bridges (max 2).
Definition at line 162 of file Bus.hh.
Referenced by canWrite(), clearDestinationBridge(), nextBridge(), previousBridge(), and setDestinationBridge().
extensionMode_
Machine::Extension TTAMachine::Bus::extensionMode_ private
Extension mode applied to the inline immediate word.
Definition at line 152 of file Bus.hh.
Referenced by saveState(), setExtensionMode(), setSignExtends(), setZeroExtends(), signExtends(), and zeroExtends().
guards_
GuardTable TTAMachine::Bus::guards_ private
Contains all guards of the bus.
Definition at line 155 of file Bus.hh.
Referenced by addGuard(), deleteAllGuards(), guard(), guardCount(), hasGuard(), and removeGuard().
immWidth_
int TTAMachine::Bus::immWidth_ private
Bit width of the inline immediate word.
Definition at line 150 of file Bus.hh.
Referenced by immediateWidth(), saveState(), and setImmediateWidth().
OSKEY_EXTENSION
const string TTAMachine::Bus::OSKEY_EXTENSION = "extension" static
ObjectState attribute key for extension mode.
Definition at line 122 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadStateWithoutReferences(), and saveState().
OSKEY_IMMWIDTH
const string TTAMachine::Bus::OSKEY_IMMWIDTH = "immwidth" static
ObjectState attribute key for immediate width.
Definition at line 120 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadStateWithoutReferences(), and saveState().
OSKEY_WIDTH
const string TTAMachine::Bus::OSKEY_WIDTH = "width" static
ObjectState attribute key for bus width.
Definition at line 118 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadStateWithoutReferences(), and saveState().
OSNAME_BUS
const string TTAMachine::Bus::OSNAME_BUS = "bus" static
ObjectState name for Bus ObjectState.
Definition at line 116 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), TTAMachine::Machine::loadState(), loadStateWithoutReferences(), and saveState().
OSVALUE_SIGN
const string TTAMachine::Bus::OSVALUE_SIGN = "sign" static
ObjectState attribute value for sign extension.
Definition at line 124 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadStateWithoutReferences(), and saveState().
OSVALUE_ZERO
const string TTAMachine::Bus::OSVALUE_ZERO = "zero" static
ObjectState attribute key for zero extension.
Definition at line 126 of file Bus.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadStateWithoutReferences(), and saveState().
segments_
SegmentTable TTAMachine::Bus::segments_ private
Contains all the segments of the bus.
Definition at line 157 of file Bus.hh.
Referenced by addSegment(), deleteAllSegments(), hasSegment(), isConnectedTo(), removeSegment(), segment(), segment(), segmentCount(), and unsetMachine().
sourceBridges_
BridgeTable TTAMachine::Bus::sourceBridges_ private
Contains the source bridges (max 2).
Definition at line 160 of file Bus.hh.
Referenced by canRead(), clearSourceBridge(), nextBridge(), previousBridge(), and setSourceBridge().
width_
int TTAMachine::Bus::width_ private
Bit width of the bus.
Definition at line 148 of file Bus.hh.
Referenced by saveState(), setWidth(), and width().
The documentation for this class was generated from the following files:
Bus.hh
Bus.cc