OpenASIP: TPEF::Swapper Class Reference
TPEF::Swapper Class Reference
#include <Swapper.hh>
Static Public Member Functions
static void swap (const Byte *src, Byte *dst, int size)
Detailed Description
Definition at line 43 of file Swapper.hh.
Member Function Documentation
swap()
static void TPEF::Swapper::swap (const Byte * src, Byte * dst, int size) static
Referenced by TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::BinaryStream::writeHalfWord(), and TPEF::BinaryStream::writeWord().
The documentation for this class was generated from the following file:
Swapper.hh