OpenASIP: RFArchitectureDialog Class Reference
RFArchitectureDialog Class Reference
#include <RFArchitectureDialog.hh>
Public Member Functions
RFArchitectureDialog (wxWindow *parent, wxWindowID id, HDB::RFArchitecture &arch)
virtual ~RFArchitectureDialog ()
Private Types
enum {
ID_LABEL_SIZE = 10000 , ID_SIZE , ID_LABEL_WIDTH , ID_WIDTH ,
ID_LABEL_READ_PORTS , ID_READ_PORTS , ID_LABEL_WRITE_PORTS , ID_WRITE_PORTS ,
ID_LABEL_BIDIR_PORTS , ID_BIDIR_PORTS , ID_LABEL_MAX_READS , ID_MAX_READS ,
ID_LABEL_MAX_WRITES , ID_MAX_WRITES , ID_PARAM_WIDTH , ID_PARAM_SIZE ,
ID_GUARD_SUPPORT , ID_LINE , ID_ZERO_REGISTER
}
Widget IDs.
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void update ()
Private Attributes
HDB::RFArchitecture & arch_
int size_
int width_
int readPorts_
int writePorts_
int bidirPorts_
int maxReads_
int maxWrites_
int latency_
bool guardSupport_
bool paramWidth_
bool paramSize_
bool zeroRegister_
Detailed Description
Dialog for defining RF architecture paramters to HDB.
Definition at line 46 of file RFArchitectureDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_LABEL_SIZE
ID_SIZE
ID_LABEL_WIDTH
ID_WIDTH
ID_LABEL_READ_PORTS
ID_READ_PORTS
ID_LABEL_WRITE_PORTS
ID_WRITE_PORTS
ID_LABEL_BIDIR_PORTS
ID_BIDIR_PORTS
ID_LABEL_MAX_READS
ID_MAX_READS
ID_LABEL_MAX_WRITES
ID_MAX_WRITES
ID_PARAM_WIDTH
ID_PARAM_SIZE
ID_GUARD_SUPPORT
ID_LINE
ID_ZERO_REGISTER
Definition at line 58 of file RFArchitectureDialog.hh.
         {
        ID_LABEL_SIZE = 10000,
        ID_SIZE,
        ID_LABEL_WIDTH,
        ID_WIDTH,
        ID_LABEL_READ_PORTS,
        ID_READ_PORTS,
        ID_LABEL_WRITE_PORTS,
        ID_WRITE_PORTS,
        ID_LABEL_BIDIR_PORTS,
        ID_BIDIR_PORTS,
        ID_LABEL_MAX_READS,
        ID_MAX_READS,
        ID_LABEL_MAX_WRITES,
        ID_MAX_WRITES,
        ID_PARAM_WIDTH,
        ID_PARAM_SIZE,
        ID_GUARD_SUPPORT,
        ID_LINE,
        ID_ZERO_REGISTER
    };
Constructor & Destructor Documentation
RFArchitectureDialog()
RFArchitectureDialog::RFArchitectureDialog (wxWindow * parent, wxWindowID id, HDB::RFArchitecture & arch)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog.
arch Register file architecture to modify.
Definition at line 51 of file RFArchitectureDialog.cc.
                                                              :
    wxDialog(parent, id, _T("Register file architecture.")),
    arch_(arch), size_(0), width_(0) {
   if (!arch_.hasParameterizedSize()) {
       size_ = arch_.size();
   }
   if (!arch_.hasParameterizedWidth()) {
       width_ = arch_.width();
   }
   readPorts_ = arch_.readPortCount();
   writePorts_ = arch_.writePortCount();
   bidirPorts_ = arch_.bidirPortCount();
   maxReads_ = arch_.maxReads();
   maxWrites_ = arch_.maxWrites();
   latency_ = arch_.latency();
   zeroRegister_ = arch.zeroRegister();
   paramWidth_ = arch_.hasParameterizedWidth();
   paramSize_ = arch_.hasParameterizedSize();
   guardSupport_ = arch_.hasGuardSupport();
   createContents(this, true, true);
   FindWindow(ID_SIZE)->SetValidator(wxGenericValidator(&size_));
   FindWindow(ID_WIDTH)->SetValidator(wxGenericValidator(&width_));
   FindWindow(ID_MAX_READS)->SetValidator(wxGenericValidator(&maxReads_));
   FindWindow(ID_MAX_WRITES)->SetValidator(wxGenericValidator(&maxWrites_));
   FindWindow(ID_READ_PORTS)->SetValidator(wxGenericValidator(&readPorts_));
   FindWindow(ID_WRITE_PORTS)->SetValidator(wxGenericValidator(&writePorts_));
   FindWindow(ID_BIDIR_PORTS)->SetValidator(wxGenericValidator(&bidirPorts_));
   FindWindow(ID_ZERO_REGISTER)->SetValidator(
       wxGenericValidator(&zeroRegister_));
   FindWindow(ID_PARAM_SIZE)->SetValidator(wxGenericValidator(&paramSize_));
   FindWindow(ID_PARAM_WIDTH)->SetValidator(wxGenericValidator(&paramWidth_));
   FindWindow(ID_GUARD_SUPPORT)->SetValidator(
       wxGenericValidator(&guardSupport_));
}
~RFArchitectureDialog()
RFArchitectureDialog::~RFArchitectureDialog () virtual
The Destructor.
Definition at line 99 of file RFArchitectureDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * RFArchitectureDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Definition at line 134 of file RFArchitectureDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_SIZE, wxT("Size:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALL, 5 );
    wxSpinCtrl *item4 = new wxSpinCtrl( parent, ID_SIZE, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALL, 5 );
    wxSpinCtrl *item6 = new wxSpinCtrl( parent, ID_WIDTH, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 0 );
    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    // Modifying latency disabled for now!
    //wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_LATENCY, wxT("Latency:"), wxDefaultPosition, wxDefaultSize, 0 );
    //item2->Add( item7, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    //wxSpinCtrl *item8 = new wxSpinCtrl( parent, ID_LATENCY, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    //item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_LABEL_MAX_READS, wxT("Max reads:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item9, 0, wxALL, 5 );
    wxSpinCtrl *item10 = new wxSpinCtrl( parent, ID_MAX_READS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 0 );
    item2->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_LABEL_MAX_WRITES, wxT("Max writes:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item11, 0, wxALL, 5 );
    wxSpinCtrl *item12 = new wxSpinCtrl( parent, ID_MAX_WRITES, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item2->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item13 = new wxStaticText( parent, ID_LABEL_READ_PORTS, wxT("Read ports:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item13, 0, wxALL, 5 );
    wxSpinCtrl *item14 = new wxSpinCtrl( parent, ID_READ_PORTS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item2->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item15 = new wxStaticText( parent, ID_LABEL_WRITE_PORTS, wxT("Write ports:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item15, 0, wxALL, 5 );
    wxSpinCtrl *item16 = new wxSpinCtrl( parent, ID_WRITE_PORTS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item2->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item17 = new wxStaticText( parent, ID_LABEL_BIDIR_PORTS, wxT("Bidirectional ports:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item17, 0, wxALL, 5 );
    wxSpinCtrl *item18 = new wxSpinCtrl( parent, ID_BIDIR_PORTS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item2->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item19 = new wxBoxSizer( wxVERTICAL );
    wxCheckBox *item20 = new wxCheckBox( parent, ID_PARAM_WIDTH, wxT("Parametrized width"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALL, 5 );
    wxCheckBox *item21 = new wxCheckBox( parent, ID_PARAM_SIZE, wxT("Parametrized size"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item21, 0, wxALL, 5 );
    wxCheckBox *item22 = new wxCheckBox( parent, ID_GUARD_SUPPORT, wxT("Guard support"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item22, 0, wxALL, 5 );
    item1->Add( item19, 0, wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item23 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item23, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item24 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item25 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item26 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item24, 0, wxALL, 5 );
    wxCheckBox *item27 = new wxCheckBox( parent, ID_ZERO_REGISTER, wxT("Zero register"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item27, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BIDIR_PORTS, ID_GUARD_SUPPORT, ID_LABEL_BIDIR_PORTS, ID_LABEL_MAX_READS, ID_LABEL_MAX_WRITES, ID_LABEL_READ_PORTS, ID_LABEL_SIZE, ID_LABEL_WIDTH, ID_LABEL_WRITE_PORTS, ID_LINE, ID_MAX_READS, ID_MAX_WRITES, ID_PARAM_SIZE, ID_PARAM_WIDTH, ID_READ_PORTS, ID_SIZE, ID_WIDTH, ID_WRITE_PORTS, and ID_ZERO_REGISTER.
onOK()
void RFArchitectureDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 107 of file RFArchitectureDialog.cc.
{
    TransferDataFromWindow();
    if (!paramSize_) {
        arch_.setSize(size_);
    }
    if (!paramWidth_) {
        arch_.setWidth(width_);
    }
    arch_.setReadPortCount(readPorts_);
    arch_.setWritePortCount(writePorts_);
    arch_.setBidirPortCount(bidirPorts_);
    arch_.setMaxReads(maxReads_);
    arch_.setMaxWrites(maxWrites_);
    arch_.setLatency(latency_);
    arch_.setGuardSupport(guardSupport_);
    arch_.setZeroRegister(zeroRegister_);
    EndModal(wxID_OK);
}
References arch_, bidirPorts_, guardSupport_, latency_, maxReads_, maxWrites_, paramSize_, paramWidth_, readPorts_, HDB::RFArchitecture::setBidirPortCount(), HDB::RFArchitecture::setGuardSupport(), HDB::RFArchitecture::setLatency(), HDB::RFArchitecture::setMaxReads(), HDB::RFArchitecture::setMaxWrites(), HDB::RFArchitecture::setReadPortCount(), HDB::RFArchitecture::setSize(), HDB::RFArchitecture::setWidth(), HDB::RFArchitecture::setWritePortCount(), HDB::RFArchitecture::setZeroRegister(), size_, width_, writePorts_, and zeroRegister_.
update()
void RFArchitectureDialog::update () private
Member Data Documentation
arch_
HDB::RFArchitecture& RFArchitectureDialog::arch_ private
Definition at line 80 of file RFArchitectureDialog.hh.
Referenced by onOK().
bidirPorts_
int RFArchitectureDialog::bidirPorts_ private
Definition at line 86 of file RFArchitectureDialog.hh.
Referenced by onOK().
guardSupport_
bool RFArchitectureDialog::guardSupport_ private
Definition at line 90 of file RFArchitectureDialog.hh.
Referenced by onOK().
latency_
int RFArchitectureDialog::latency_ private
Definition at line 89 of file RFArchitectureDialog.hh.
Referenced by onOK().
maxReads_
int RFArchitectureDialog::maxReads_ private
Definition at line 87 of file RFArchitectureDialog.hh.
Referenced by onOK().
maxWrites_
int RFArchitectureDialog::maxWrites_ private
Definition at line 88 of file RFArchitectureDialog.hh.
Referenced by onOK().
paramSize_
bool RFArchitectureDialog::paramSize_ private
Definition at line 92 of file RFArchitectureDialog.hh.
Referenced by onOK().
paramWidth_
bool RFArchitectureDialog::paramWidth_ private
Definition at line 91 of file RFArchitectureDialog.hh.
Referenced by onOK().
readPorts_
int RFArchitectureDialog::readPorts_ private
Definition at line 84 of file RFArchitectureDialog.hh.
Referenced by onOK().
size_
int RFArchitectureDialog::size_ private
Definition at line 82 of file RFArchitectureDialog.hh.
Referenced by onOK().
width_
int RFArchitectureDialog::width_ private
Definition at line 83 of file RFArchitectureDialog.hh.
Referenced by onOK().
writePorts_
int RFArchitectureDialog::writePorts_ private
Definition at line 85 of file RFArchitectureDialog.hh.
Referenced by onOK().
zeroRegister_
bool RFArchitectureDialog::zeroRegister_ private
Definition at line 93 of file RFArchitectureDialog.hh.
Referenced by onOK().
The documentation for this class was generated from the following files:
RFArchitectureDialog.hh
RFArchitectureDialog.cc