OpenASIP: QuitCmd Class Reference
QuitCmd Class Reference
#include <QuitCmd.hh>
Public Member Functions
QuitCmd ()
virtual ~QuitCmd ()
virtual bool Do ()
virtual int id () const
virtual QuitCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for quiting the editor.
Definition at line 41 of file QuitCmd.hh.
Constructor & Destructor Documentation
QuitCmd()
QuitCmd::QuitCmd ()
The Constructor.
Definition at line 48 of file QuitCmd.cc.
                :
    EditorCommand(ProDeConstants::CMD_NAME_QUIT) {
}
Referenced by create().
~QuitCmd()
QuitCmd::~QuitCmd () virtual
The Destructor.
Definition at line 57 of file QuitCmd.cc.
{}
Member Function Documentation
create()
QuitCmd * QuitCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 117 of file QuitCmd.cc.
                      {
    return new QuitCmd();
}
References QuitCmd().
Do()
bool QuitCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file QuitCmd.cc.
            {
    MainFrame* parent = wxGetApp().mainFrame();
    ProDeOptions* options = wxGetApp().options();
    if (options->isModified()) {
        wxString question = _T("Options are modified. ");
        if (options->hasFileName()) {
            question.Append(_T("Do you want to save changes to '"));
            question.Append(WxConversion::toWxString(
                                options->fileName()));
            question.Append(_T("'?"));
        } else {
            question.Append(_T("Do you want to save changes?"));
        }
        ConfirmDialog confirm(parentWindow(), question);
        int buttonPressed = confirm.ShowModal();
        if (buttonPressed == wxID_YES) {
            GUICommand* command = wxGetApp().commandRegistry()
                ->createCommand(ProDeConstants::COMMAND_SAVE_OPTIONS);
            if (!command->Do()) {
                return false;
            }
        } else if (buttonPressed == wxID_CANCEL) {
            return false;
        }
        // if 'No' button was pressed just exit the program
    }
    wxCommandEvent dummy(wxID_EXIT, 0);
    parent->OnExit(dummy);
    return false;
}
References ProDeConstants::COMMAND_SAVE_OPTIONS, GUICommand::Do(), dummy, MainFrame::OnExit(), options, GUICommand::parentWindow(), and WxConversion::toWxString().
icon()
string QuitCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 128 of file QuitCmd.cc.
                    {
    return ProDeConstants::CMD_ICON_QUIT;
}
References ProDeConstants::CMD_ICON_QUIT.
id()
int QuitCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 106 of file QuitCmd.cc.
                  {
    return ProDeConstants::COMMAND_QUIT;
}
References ProDeConstants::COMMAND_QUIT.
isEnabled()
bool QuitCmd::isEnabled () virtual
This command is always executable.
Returns
Always true.
Reimplemented from EditorCommand.
Definition at line 139 of file QuitCmd.cc.
                   {
    return true;
}
The documentation for this class was generated from the following files:
QuitCmd.hh
QuitCmd.cc