OpenASIP: HDB::HDBEntry Class Reference
HDB::HDBEntry Class Reference abstract
#include <HDBEntry.hh>
Public Member Functions
virtual ~HDBEntry ()
bool hasID () const
void setID (RowID id)
RowID id () const
virtual bool hasArchitecture () const =0
virtual bool hasImplementation () const =0
bool hasCostFunction () const
CostFunctionPlugin & costFunction () const
void setCostFunction (CostFunctionPlugin *costFunction)
std::string hdbFile () const
void setHDBFile (const std::string &file)
Protected Member Functions
HDBEntry ()
Private Attributes
bool hasID_
Tells whether the entry has an ID set.
RowID id_
ID of the entry in HDB.
CostFunctionPlugin * costFunction_
Cost function of the entry.
std::string hdbFile_
The HDB file that contains the entry.
Detailed Description
An abstract base class for FUEntry and RFEntry.
Definition at line 46 of file HDBEntry.hh.
Constructor & Destructor Documentation
~HDBEntry()
HDB::HDBEntry::~HDBEntry () virtual
The destructor.
Definition at line 49 of file HDBEntry.cc.
                    {
    if (hasCostFunction()) {
        delete costFunction_;
    }
}
References costFunction_, and hasCostFunction().
HDBEntry()
HDB::HDBEntry::HDBEntry () protected
The constructor.
Definition at line 41 of file HDBEntry.cc.
                   :
    hasID_(false), id_(0), costFunction_(NULL), hdbFile_("") {
}
Member Function Documentation
costFunction()
CostFunctionPlugin & HDB::HDBEntry::costFunction () const
Returns the cost function of the entry.
Returns
Cost function of the entry.
Exceptions
NotAvailable If the entry doesn't have a cost function.
Definition at line 111 of file HDBEntry.cc.
{
    if (!hasCostFunction()) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    }
    return *costFunction_;
}
References __func__, costFunction_, and hasCostFunction().
Referenced by CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), HDBToHtml::fuEntryToHtml(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), HDBToHtml::rfEntryToHtml(), and setCostFunction().
hasArchitecture()
virtual bool HDB::HDBEntry::hasArchitecture () const pure virtual
Implemented in HDB::FUEntry, and HDB::RFEntry.
hasCostFunction()
bool HDB::HDBEntry::hasCostFunction () const
Tells whether the entry contains a cost function.
Returns
True if the entry contains a cost function.
Definition at line 99 of file HDBEntry.cc.
{
    return costFunction_ != NULL;
}
References costFunction_.
Referenced by CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), costFunction(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), HDBToHtml::fuEntryToHtml(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), HDBToHtml::rfEntryToHtml(), setCostFunction(), and ~HDBEntry().
hasID()
bool HDB::HDBEntry::hasID () const
Tells whether the entry has an ID.
Returns
True if the entry has an ID, otherwise false.
Definition at line 62 of file HDBEntry.cc.
                      {
    return hasID_;
}
References hasID_.
Referenced by HDB::HDBManager::addFUImplementation(), and id().
hasImplementation()
virtual bool HDB::HDBEntry::hasImplementation () const pure virtual
Implemented in HDB::FUEntry, and HDB::RFEntry.
hdbFile()
std::string HDB::HDBEntry::hdbFile () const
Returns the HDB file that contains the entry.
Returns
The HDB file.
Definition at line 141 of file HDBEntry.cc.
{
    return hdbFile_;
}
References hdbFile_.
id()
RowID HDB::HDBEntry::id () const
Returns the ID of the entry.
Returns
ID of the entry.
Definition at line 85 of file HDBEntry.cc.
                   {
    if (!hasID()) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    } else {
        return id_;
    }
}
References __func__, hasID(), and id_.
Referenced by HDB::HDBManager::addFUImplementation(), AddRFImplementationCmd::Do(), SetFUArchitectureCmd::Do(), SetRFArchitectureCmd::Do(), HDBToHtml::fuEntryToHtml(), HDBToHtml::rfEntryToHtml(), and setID().
setCostFunction()
void HDB::HDBEntry::setCostFunction (CostFunctionPlugin * costFunction)
Sets cost function for the entry.
Deletes the old cost function if one exists.
Parameters
costFunction The new cost function.
Definition at line 127 of file HDBEntry.cc.
{
    if (hasCostFunction()) {
        delete costFunction_;
    }
    costFunction_ = costFunction;
}
References costFunction(), costFunction_, and hasCostFunction().
Referenced by HDB::HDBManager::fuByEntryID(), and HDB::HDBManager::rfByEntryID().
setHDBFile()
void HDB::HDBEntry::setHDBFile (const std::string & file)
Sets the HDB file that contains the entry.
Parameters
file The HDB file.
Definition at line 152 of file HDBEntry.cc.
{
    hdbFile_ = file;
}
References hdbFile_.
Referenced by HDB::HDBManager::fuByEntryID(), and HDB::HDBManager::rfByEntryID().
setID()
void HDB::HDBEntry::setID (RowID id)
Sets the ID for the entry.
Parameters
id The ID to set.
Definition at line 73 of file HDBEntry.cc.
{
    hasID_ = true;
    id_ = id;
}
References hasID_, id(), and id_.
Referenced by HDB::HDBManager::fuByEntryID(), and HDB::HDBManager::rfByEntryID().
Member Data Documentation
costFunction_
CostFunctionPlugin* HDB::HDBEntry::costFunction_ private
Cost function of the entry.
Definition at line 73 of file HDBEntry.hh.
Referenced by costFunction(), hasCostFunction(), setCostFunction(), and ~HDBEntry().
hasID_
bool HDB::HDBEntry::hasID_ private
Tells whether the entry has an ID set.
Definition at line 69 of file HDBEntry.hh.
Referenced by hasID(), and setID().
hdbFile_
std::string HDB::HDBEntry::hdbFile_ private
The HDB file that contains the entry.
Definition at line 75 of file HDBEntry.hh.
Referenced by hdbFile(), and setHDBFile().
id_
RowID HDB::HDBEntry::id_ private
ID of the entry in HDB.
Definition at line 71 of file HDBEntry.hh.
Referenced by id(), and setID().
The documentation for this class was generated from the following files:
HDBEntry.hh
HDBEntry.cc