OpenASIP: TTAProgram::TerminalFUPort Class Reference
TTAProgram::TerminalFUPort Class Reference
#include <TerminalFUPort.hh>
Public Member Functions
TerminalFUPort (const TTAMachine::FUPort &opcodeSettingPort, const TTAMachine::HWOperation &opcode)
TerminalFUPort (const TTAMachine::BaseFUPort &port)
TerminalFUPort (const TTAMachine::HWOperation &operation, int opIndex)
virtual ~TerminalFUPort ()
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual void setOperation (const TTAMachine::HWOperation &hwOp)
void setHintOperation (const char *name)
virtual int operationIndex () const
virtual void setOperationIndex (int index)
virtual const TTAMachine::Port & port () const
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
virtual const TTAMachine::HWOperation * hwOperation () const
bool hasProgramOperation () const
these methods are used to group terminals belonging to a single program operation invocation
void setProgramOperation (ProgramOperationPtr po)
ProgramOperationPtr programOperation () const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isImmediate () const
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual SimValue value () const
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Private Member Functions
TerminalFUPort (const TerminalFUPort &tfup)
TerminalFUPort & operator= (const TerminalFUPort &)
Assignment not allowed.
int findNewOperationIndex () const
Private Attributes
const TTAMachine::BaseFUPort & port_
Port of the unit.
const TTAMachine::HWOperation * operation_
Operation code transported to the port.
Operation * opcode_
The OSAL operation.
int opIndex_
Operation index.
ProgramOperationPtr po_
The ProgramOperation this terminal belongs to, if applicable. The instance is shared by all the TerminalFUs belonging to the operation.
Detailed Description
Represents an input or output port of a function unit and (when applicable) the operation code written into it.
Notice that, in principle, operation codes can be written into FU output ports.
Definition at line 56 of file TerminalFUPort.hh.
Constructor & Destructor Documentation
TerminalFUPort() [1/4]
TTAProgram::TerminalFUPort::TerminalFUPort (const TTAMachine::FUPort & opcodeSettingPort, const TTAMachine::HWOperation & opcode)
Creates a destination that writes to an opcode setting FU port.
Parameters
opcodeSettingPort The port of the terminal.
opcode The operation to trigger.
Definition at line 72 of file TerminalFUPort.cc.
                                         :
    port_(opcodeSettingPort), operation_(&opcode), opcode_(NULL) {
    assert(opcodeSettingPort.isOpcodeSetting());
    opIndex_ = opcode.io(opcodeSettingPort);
    static OperationPool pool;
    // opcode is NullOperation instance if operation for that name was not
    // found
    try {
        opcode_ = &pool.operation(operation_->name().c_str());
    } catch (const Exception& e) {
        IllegalParameters ip(
            __FILE__, __LINE__, __func__,
            (boost::format(
                "Error loading the operation '%s' definition: '%s'.")
             % operation_->name() % e.errorMessage()).str());
        ip.setCause(e);
        throw ip;
    }
}
References __func__, assert, Exception::errorMessage(), TTAMachine::HWOperation::io(), TTAMachine::FUPort::isOpcodeSetting(), TTAMachine::HWOperation::name(), opcode_, operation_, opIndex_, and Exception::setCause().
TerminalFUPort() [2/4]
TTAProgram::TerminalFUPort::TerminalFUPort (const TTAMachine::BaseFUPort & port)
Constructor.
Parameters
port The port of the terminal.
Definition at line 57 of file TerminalFUPort.cc.
    : port_(port), operation_(NULL), opcode_(NULL) {
    if (port_.isOpcodeSetting()) {
        std::string msg =
            "Opcode setting port terminals must have opcode set!";
        throw IllegalParameters(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, TTAMachine::BaseFUPort::isOpcodeSetting(), and port_.
TerminalFUPort() [3/4]
TTAProgram::TerminalFUPort::TerminalFUPort (const TTAMachine::HWOperation & operation, int opIndex)
Constructor.
Parameters
operation Operation of terminal.
opIndex Operation index.
Definition at line 104 of file TerminalFUPort.cc.
    : port_(*operation.port(opIndex)),
      operation_(&operation),
      opIndex_(opIndex) {
    /* In case the operand cannot be resolved to a legal port, it's an
       error in the loaded input program. Thus, we cannot abort the program but
       we'll throw an exception instead. */
    if (dynamic_cast<const FUPort*>(&port_) == NULL) {
        throw IllegalParameters(
            __FILE__, __LINE__, __func__,
            (boost::format(
                "Port binding of operand %d of operation '%s' "
                "cannot be resolved.") % opIndex % operation.name()).
            str());
    }
    static OperationPool pool;
    // opcode is NullOperation instance if operation for that name was not
    // found
    try {
        opcode_ = &pool.operation(operation_->name().c_str());
    } catch (const Exception& e) {
        IllegalParameters ip(
            __FILE__, __LINE__, __func__,
            (boost::format(
                "Error loading the operation '%s' definition: '%s'.")
             % operation_->name() % e.errorMessage()).str());
        ip.setCause(e);
        throw ip;
    }
}
References __func__, Exception::errorMessage(), TTAMachine::HWOperation::name(), Operation::name(), opcode_, operation(), operation_, port_, and Exception::setCause().
~TerminalFUPort()
TTAProgram::TerminalFUPort::~TerminalFUPort () virtual
The destructor.
Definition at line 148 of file TerminalFUPort.cc.
{
}
TerminalFUPort() [4/4]
TTAProgram::TerminalFUPort::TerminalFUPort (const TerminalFUPort & tfup) private
Copy Constructor. private, only called internally by copy().
Parameters
tfup object to copy from.
Definition at line 140 of file TerminalFUPort.cc.
                                                         :
    Terminal(), port_(tfup.port_), operation_(tfup.operation_),
    opcode_(tfup.opcode_), opIndex_(tfup.opIndex_), po_(tfup.po_) {
}
Member Function Documentation
copy()
Terminal * TTAProgram::TerminalFUPort::copy () const virtual
Creates an exact copy of the terminal and returns it.
Note
The returned copy is a deep cope but the copied ProgramOperation, if contained, will not be updated to refer to the new moves. This should be done in the caller.
Returns
A copy of the terminal.
Implements TTAProgram::Terminal.
Definition at line 305 of file TerminalFUPort.cc.
{
    return new TerminalFUPort(*this);
}
equals()
bool TTAProgram::TerminalFUPort::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Implements TTAProgram::Terminal.
Definition at line 316 of file TerminalFUPort.cc.
{
    if (!other.isFUPort()) {
        return false;
    }
    const TerminalFUPort& subclass =
        dynamic_cast<const TerminalFUPort&>(other);
    // if ports are same
    if (&port_ == &subclass.port_) {
        // we care about opcodes only if they are necessary data
        if (port_.isOpcodeSetting()) {
            // if opcodes are the same
            if (operation_ == subclass.operation_) {
                // same port same operation
                return true;
            } else {
                // if opcodes are not defined -> error
                if (operation_ == NULL ||
                    subclass.operation_ == NULL) {
                    abortWithError(
                        "Opcode _must_ be set for terminals that "
                        "refers opcode setting port!");
                }
                // same port different operations
                return false;
            }
        } else {
            // same ports not opcode setting
            return true;
        }
    }
    // different ports
    return false;
}
References abortWithError, TTAProgram::Terminal::isFUPort(), TTAMachine::BaseFUPort::isOpcodeSetting(), operation_, and port_.
findNewOperationIndex()
int TTAProgram::TerminalFUPort::findNewOperationIndex () const private
Return operation index bound to the terminal port for a given operation.
Used if operation in terminal is changed.
Returns
Operation index bound to the terminal port for a given operation.
Definition at line 366 of file TerminalFUPort.cc.
{
    const FunctionUnit* fu = port_.parentUnit();
    const HWOperation* hwop = fu->operation(operation_->name());
    return hwop->io(dynamic_cast<const FUPort&>(port_));
}
References TTAMachine::HWOperation::io(), TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), operation_, TTAMachine::BaseFUPort::parentUnit(), and port_.
functionUnit()
const FunctionUnit & TTAProgram::TerminalFUPort::functionUnit () const virtual
Returns the function unit of the port.
Returns
The function unit of the port.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 202 of file TerminalFUPort.cc.
{
    return *port_.parentUnit();
}
References TTAMachine::BaseFUPort::parentUnit(), and port_.
Referenced by ProcedurePass::copyCfgToProcedure(), InputFUBroker::unassign(), and OutputFUBroker::unassign().
hasProgramOperation()
bool TTAProgram::TerminalFUPort::hasProgramOperation () const inline
these methods are used to group terminals belonging to a single program operation invocation
Definition at line 91 of file TerminalFUPort.hh.
{
        return po_ != NULL && po_.get() != NULL;
    }
References po_.
Referenced by DataDependenceGraphBuilder::processOperand(), and DataDependenceGraphBuilder::processTriggerPO().
hintOperation()
Operation & TTAProgram::TerminalFUPort::hintOperation () const virtual
Return the operation to which this terminal was originally bound.
NOTE! : Method must not be used for checkin if terminal contains opcode. See. operation().
Method is mainly used for preserving information to which operation port reference is bound, during TPEF -> POM -> TPEF write cycles.
Returns
The operation code to which terminal was originally bound. Null operation if terminal does not contain operation code.
Reimplemented from TTAProgram::Terminal.
Definition at line 262 of file TerminalFUPort.cc.
{
    if (opcode_ != NULL) {
        return *opcode_;
    } else {
        return NullOperation::instance();
    }
}
References NullOperation::instance(), and opcode_.
Referenced by InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), InputFUBroker::assign(), OutputFUBroker::assign(), POMDisassembler::createFUPort(), SimpleIfConverter::fixTerminalPO(), TTAProgram::Move::isCall(), TTAProgram::Move::isControlFlowMove(), TTAProgram::Move::isJump(), DataDependenceGraphBuilder::processDestination(), TTAProgram::ProgramWriter::terminalResource(), and DataDependenceGraphBuilder::updateBB().
hwOperation()
const HWOperation * TTAProgram::TerminalFUPort::hwOperation () const virtual
Returns a pointer to the HW operation
Returns
a pointer to the HW operation
Definition at line 379 of file TerminalFUPort.cc.
{
     return operation_;
}
References operation_.
Referenced by ControlFlowGraph::buildMBBFromBB(), POMDisassembler::createFUPort(), CodeCompressorPlugin::encodeFUTerminal(), CompiledSimCodeGenerator::generateInstruction(), DataDependenceEdge::latencySt(), and DataDependenceEdge::saveState().
isFUPort()
bool TTAProgram::TerminalFUPort::isFUPort () const virtual
Tells whether the terminal is a function unit port (possibly, including an operation code).
Returns
True always.
Reimplemented from TTAProgram::Terminal.
Definition at line 158 of file TerminalFUPort.cc.
{
    return true;
}
isOpcodeSetting()
bool TTAProgram::TerminalFUPort::isOpcodeSetting () const virtual
Tells whether terminal transports an opcode to a function unit port.
Returns
True if the terminal transports an opcode to a function unit port.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 180 of file TerminalFUPort.cc.
{
    return port_.isOpcodeSetting();
}
References TTAMachine::BaseFUPort::isOpcodeSetting(), and port_.
Referenced by POMDisassembler::createFUPort(), TTAProgram::Move::isCall(), TTAProgram::Move::isControlFlowMove(), TTAProgram::Move::isJump(), DataDependenceGraphBuilder::processDestination(), and TTAProgram::ProgramWriter::terminalResource().
isRA()
bool TTAProgram::TerminalFUPort::isRA () const virtual
Tells whether the terminal is the return address port of gcu.
Returns
returns true if this is the RA.
Reimplemented from TTAProgram::Terminal.
Definition at line 168 of file TerminalFUPort.cc.
{
    return dynamic_cast<const TTAMachine::SpecialRegisterPort*>
        (&port()) != NULL;
}
References port().
isTriggering()
bool TTAProgram::TerminalFUPort::isTriggering () const virtual
Tells whether terminal is a triggering port.
Returns
True if the terminal transports an opcode to a function unit port.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 191 of file TerminalFUPort.cc.
{
    return port_.isTriggering();
}
References TTAMachine::BaseFUPort::isTriggering(), and port_.
Referenced by TTAProgram::Move::isTriggering().
operation()
Operation & TTAProgram::TerminalFUPort::operation () const virtual
Return the operation code transported into the function unit port.
Returns
The operation code transported into the function unit port.
Exceptions
InvalidData If terminal does not set opcode for FU.
Reimplemented from TTAProgram::Terminal.
Definition at line 213 of file TerminalFUPort.cc.
{
    if (port_.isOpcodeSetting() && opcode_ != NULL) {
        return *opcode_;
    } else {
        std::cerr
            << "operation == NULL || !port_.isopcodesetting()" << std::endl;
    }
    throw InvalidData(__FILE__, __LINE__, __func__,
                        "Terminal does not set opcode for FU.");
}
References __func__, TTAMachine::BaseFUPort::isOpcodeSetting(), opcode_, and port_.
Referenced by POMDisassembler::createFUPort(), TTAProgram::Move::isCall(), TTAProgram::Move::isControlFlowMove(), TTAProgram::Move::isJump(), TerminalFUPort(), and TTAProgram::ProgramWriter::terminalResource().
operationIndex()
int TTAProgram::TerminalFUPort::operationIndex () const virtual
Return the index that identifies the operation input or output that is represented by this terminal.
Returns
The index that identifies the operation input or output that is represented by this terminal.
Exceptions
WrongSubclass Never.
InvalidData If the terminal is of the the right class type, but the FU port of the terminal is not opcode-setting and bears no auxiliary "hint operation" information.
Todo:
Rename to operandIndex()?
Reimplemented from TTAProgram::Terminal.
Definition at line 238 of file TerminalFUPort.cc.
{
    if (operation_ != NULL || opcode_ != nullptr) {
        return opIndex_;
    } else {
        const string msg =
            "FU port of the terminal is not opcode-setting "
            "and bears no auxiliary 'hint operation' information.";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, opcode_, operation_, and opIndex_.
Referenced by InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), InputFUBroker::assign(), OutputFUBroker::assign(), and MachineConnectivityCheck::busConnectedToAnyFU().
operator=()
TerminalFUPort & TTAProgram::TerminalFUPort::operator= (const TerminalFUPort &) private
Assignment not allowed.
port()
const Port & TTAProgram::TerminalFUPort::port () const virtual
Return the port.
Returns
The port.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 291 of file TerminalFUPort.cc.
{
    return port_;
}
References port_.
Referenced by InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), InputFUBroker::assign(), OutputFUBroker::assign(), POMDisassembler::createFUPort(), isRA(), and toString().
programOperation()
ProgramOperationPtr TTAProgram::TerminalFUPort::programOperation () const inline
Definition at line 97 of file TerminalFUPort.hh.
{
        return po_;
    }
References po_.
Referenced by InputFUBroker::assign(), ControlFlowGraph::buildMBBFromBB(), llvm::LLVMTCEIRBuilder::buildTCECFG(), SimpleIfConverter::fixTerminalPO(), DataDependenceGraphBuilder::processOperand(), and DataDependenceGraphBuilder::processTriggerPO().
setHintOperation()
void TTAProgram::TerminalFUPort::setHintOperation (const char * name)
Definition at line 270 of file TerminalFUPort.cc.
{
    OperationPool opPool;
    assert(&opPool.operation(name) != &NullOperation::instance());
    opcode_ = &opPool.operation(name);
    operation_ = nullptr;
}
References assert, NullOperation::instance(), opcode_, OperationPool::operation(), and operation_.
Referenced by ProgramOperation::setOperation().
setOperation()
void TTAProgram::TerminalFUPort::setOperation (const TTAMachine::HWOperation & hwOp) virtual
Definition at line 278 of file TerminalFUPort.cc.
{
    OperationPool opPool;
    opcode_ = &opPool.operation(hwOp.name().c_str());
    operation_ = &hwOp;
}
References TTAMachine::HWOperation::name(), opcode_, OperationPool::operation(), and operation_.
setOperationIndex()
virtual void TTAProgram::TerminalFUPort::setOperationIndex (int index) inline virtual
Definition at line 82 of file TerminalFUPort.hh.
{ opIndex_ = index; }
References TTAProgram::Terminal::index(), and opIndex_.
setProgramOperation()
void TTAProgram::TerminalFUPort::setProgramOperation (ProgramOperationPtr po) inline
Definition at line 94 of file TerminalFUPort.hh.
{
        po_ = po;
    }
References po_.
Referenced by InputFUBroker::assign(), llvm::LLVMTCEIRBuilder::createMoveNode(), and SimpleIfConverter::fixTerminalPO().
toString()
TCEString TTAProgram::TerminalFUPort::toString () const virtual
Implements TTAProgram::Terminal.
Definition at line 384 of file TerminalFUPort.cc.
{
    if (operation_ != NULL) {
        DisassemblyFUOpcodePort disasm(
            port().parentUnit()->name(), port().name(), operation_->name());
        return disasm.toString();
    } else {
        DisassemblyFUPort disasm(port().parentUnit()->name(), port().name());
        return disasm.toString();
    }
}
References TTAMachine::HWOperation::name(), operation_, port(), DisassemblyFUOpcodePort::toString(), and DisassemblyFUPort::toString().
Member Data Documentation
opcode_
Operation* TTAProgram::TerminalFUPort::opcode_ private
The OSAL operation.
Definition at line 117 of file TerminalFUPort.hh.
Referenced by hintOperation(), operation(), operationIndex(), setHintOperation(), setOperation(), TerminalFUPort(), and TerminalFUPort().
operation_
const TTAMachine::HWOperation* TTAProgram::TerminalFUPort::operation_ private
Operation code transported to the port.
Definition at line 115 of file TerminalFUPort.hh.
Referenced by equals(), findNewOperationIndex(), hwOperation(), operationIndex(), setHintOperation(), setOperation(), TerminalFUPort(), TerminalFUPort(), and toString().
opIndex_
int TTAProgram::TerminalFUPort::opIndex_ private
Operation index.
Definition at line 119 of file TerminalFUPort.hh.
Referenced by operationIndex(), setOperationIndex(), and TerminalFUPort().
po_
ProgramOperationPtr TTAProgram::TerminalFUPort::po_ private
The ProgramOperation this terminal belongs to, if applicable. The instance is shared by all the TerminalFUs belonging to the operation.
Definition at line 123 of file TerminalFUPort.hh.
Referenced by hasProgramOperation(), programOperation(), and setProgramOperation().
port_
const TTAMachine::BaseFUPort& TTAProgram::TerminalFUPort::port_ private
Port of the unit.
Definition at line 113 of file TerminalFUPort.hh.
Referenced by equals(), findNewOperationIndex(), functionUnit(), isOpcodeSetting(), isTriggering(), operation(), port(), TerminalFUPort(), and TerminalFUPort().
The documentation for this class was generated from the following files:
TerminalFUPort.hh
TerminalFUPort.cc