OpenASIP: OperationTriggeredField Class Reference
OperationTriggeredField Class Reference
#include <OperationTriggeredField.hh>
Public Member Functions
OperationTriggeredField (const ObjectState *state, OperationTriggeredEncoding &parent)
OperationTriggeredField (OperationTriggeredEncoding &parent, int piece, int start, int width)
int piece () const
void setPiece (int piece)
int start () const
void setStart (int start)
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
virtual int childFieldCount () const
virtual int width () const
void setWidth (int width)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_FIELD = "ota-field"
static const std::string OSKEY_PIECE_NAME = "piece"
static const std::string OSKEY_START_NAME = "start"
static const std::string OSKEY_WIDTH_NAME = "width"
Private Attributes
int piece_
int start_
int width_
Detailed Description
Definition at line 43 of file OperationTriggeredField.hh.
Constructor & Destructor Documentation
OperationTriggeredField() [1/2]
OperationTriggeredField::OperationTriggeredField (const ObjectState * state, OperationTriggeredEncoding & parent)
The constructor
Loads the state of the field encoding from the given ObjectState tree
Parameters
state The ObjectState tree
parent The parent operation triggered encoding
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 69 of file OperationTriggeredField.cc.
{
    parent.addField(*this);
    loadState(state);
}
References OperationTriggeredEncoding::addField(), and loadState().
OperationTriggeredField() [2/2]
OperationTriggeredField::OperationTriggeredField (OperationTriggeredEncoding & parent, int piece, int start, int width)
The constructor.
Registers the field encoding to the parent binary encoding automatically.
Parameters
parent The parent binaryEncoding.
Definition at line 51 of file OperationTriggeredField.cc.
    : piece_(piece), start_(start), width_(width) {
    parent.addField(*this);
}
References OperationTriggeredEncoding::addField().
Member Function Documentation
childFieldCount()
int OperationTriggeredField::childFieldCount () const virtual
Always returns 0 because field encoding does not have any child fields.
Returns
0
Definition at line 115 of file OperationTriggeredField.cc.
{
    return 0;
}
loadState()
void OperationTriggeredField::loadState (const ObjectState * state) virtual
Loads the state of the field encoding from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Definition at line 145 of file OperationTriggeredField.cc.
{
    ObjectState* newState = new ObjectState(*state);
    try {
        piece_ = newState->intAttribute(OSKEY_PIECE_NAME);
        start_ = newState->intAttribute(OSKEY_START_NAME);
        width_ = newState->intAttribute(OSKEY_WIDTH_NAME);
    } catch (const Exception& exception) {
        const std::string procName = "OperationTriggeredField::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    delete newState;
}
References Exception::errorMessage(), ObjectState::intAttribute(), OSKEY_PIECE_NAME, OSKEY_START_NAME, OSKEY_WIDTH_NAME, piece_, start_, and width_.
Referenced by OperationTriggeredField().
piece()
int OperationTriggeredField::piece () const
Returns the piece index that indicates the index of the encoding piece.
Returns
The encoding piece index.
Definition at line 82 of file OperationTriggeredField.cc.
{
    return piece_;
}
References piece_.
Referenced by setPiece().
saveState()
ObjectState * OperationTriggeredField::saveState () const virtual
Saves the state of the field encoding to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 170 of file OperationTriggeredField.cc.
{
    ObjectState* state = new ObjectState(OSNAME_FIELD);
    state->setAttribute(OSKEY_PIECE_NAME, piece_);
    state->setAttribute(OSKEY_START_NAME, start_);
    state->setAttribute(OSKEY_WIDTH_NAME, width_);
    return state;
}
References OSKEY_PIECE_NAME, OSKEY_START_NAME, OSKEY_WIDTH_NAME, OSNAME_FIELD, piece_, ObjectState::setAttribute(), start_, and width_.
Referenced by OperationTriggeredEncoding::saveState().
setPiece()
void OperationTriggeredField::setPiece (int piece)
Definition at line 87 of file OperationTriggeredField.cc.
{
    piece_ = piece;
}
References piece(), and piece_.
setStart()
void OperationTriggeredField::setStart (int start)
Definition at line 103 of file OperationTriggeredField.cc.
{
    start_ = start;
}
References start(), and start_.
setWidth()
void OperationTriggeredField::setWidth (int width)
Definition at line 131 of file OperationTriggeredField.cc.
{
    width_ = width;
}
References width(), and width_.
start()
int OperationTriggeredField::start () const
Returns the piece index that indicates the index of the encoding piece.
Returns
The encoding piece index.
Definition at line 98 of file OperationTriggeredField.cc.
{
    return start_;
}
References start_.
Referenced by setStart().
width()
int OperationTriggeredField::width () const virtual
Returns the bit width of the field encoding
Returns
The bit width of the field encoding.
Definition at line 126 of file OperationTriggeredField.cc.
{
    return width_;
}
References width_.
Referenced by setWidth(), and OperationTriggeredEncoding::width().
Member Data Documentation
OSKEY_PIECE_NAME
const std::string OperationTriggeredField::OSKEY_PIECE_NAME = "piece" static
Definition at line 66 of file OperationTriggeredField.hh.
Referenced by loadState(), and saveState().
OSKEY_START_NAME
const std::string OperationTriggeredField::OSKEY_START_NAME = "start" static
Definition at line 67 of file OperationTriggeredField.hh.
Referenced by loadState(), and saveState().
OSKEY_WIDTH_NAME
const std::string OperationTriggeredField::OSKEY_WIDTH_NAME = "width" static
Definition at line 68 of file OperationTriggeredField.hh.
Referenced by loadState(), and saveState().
OSNAME_FIELD
const std::string OperationTriggeredField::OSNAME_FIELD = "ota-field" static
Definition at line 65 of file OperationTriggeredField.hh.
Referenced by OperationTriggeredEncoding::loadState(), and saveState().
piece_
int OperationTriggeredField::piece_ private
Definition at line 71 of file OperationTriggeredField.hh.
Referenced by loadState(), piece(), saveState(), and setPiece().
start_
int OperationTriggeredField::start_ private
Definition at line 72 of file OperationTriggeredField.hh.
Referenced by loadState(), saveState(), setStart(), and start().
width_
int OperationTriggeredField::width_ private
Definition at line 73 of file OperationTriggeredField.hh.
Referenced by loadState(), saveState(), setWidth(), and width().
The documentation for this class was generated from the following files:
OperationTriggeredField.hh
OperationTriggeredField.cc