OpenASIP: HDBBrowserWindow Class Reference
HDBBrowserWindow Class Reference
#include <HDBBrowserWindow.hh>
Public Member Functions
HDBBrowserWindow (wxWindow *parent, wxWindowID id)
virtual ~HDBBrowserWindow ()
void setHDBManager (HDB::CachedHDBManager &manager)
void update ()
bool isFUArchitectureSelected ()
bool isFUImplementationSelected ()
bool isRFArchitectureSelected ()
bool isRFImplementationSelected ()
bool isFUEntrySelected ()
bool isRFEntrySelected ()
bool isBusEntrySelected ()
bool isSocketEntrySelected ()
bool isCostFunctionPluginSelected ()
bool isOperationImplementationSelected ()
bool isOperationImplementationResourceSelected ()
RowID selectedFUArchitecture ()
RowID selectedFUImplementation ()
RowID selectedRFArchitecture ()
RowID selectedRFImplementation ()
RowID selectedFUEntry ()
RowID selectedRFEntry ()
RowID selectedBusEntry ()
RowID selectedSocketEntry ()
RowID selectedCostFunctionPlugin ()
RowID selectedOperationImplementation ()
RowID selectedOperationImplementationResource ()
void selectRFArchitecture (int id)
void selectFUArchitecture (int id)
void selectRFImplementation (int id)
void selectFUImplementation (int id)
void selectFUEntry (int id)
void selectRFEntry (int id)
void selectBusEntry (int id)
void selectSocketEntry (int id)
void selectCostFunctionPlugin (int id)
void openLink (const wxString &link)
Private Types
enum { ID_TREE_VIEW = 20000 }
Widget window IDs.
Private Member Functions
void onItemSelected (wxTreeEvent &event)
void onRMBClick (wxTreeEvent &event)
wxString fuArchLabel (const TTAMachine::FunctionUnit &fu) const
Private Attributes
HDB::CachedHDBManager * manager_
HDB to display in the browser.
wxTreeCtrl * tree_
Tree widget displayign the HDB hierarchy.
std::map< RowID, wxTreeItemId > rfArchitectures_
Map of rf architecture RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > rfImplementations_
Map of rf implementation RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > fuArchitectures_
Map of fu architecture RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > fuImplementations_
Map of fu implementation RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > fuEntries_
Map of fu entry RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > rfEntries_
Map of rf entry RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > busEntries_
Map of bus entry RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > socketEntries_
Map of socket entry RowIDs to tree item IDs.
std::map< RowID, wxTreeItemId > costPlugins_
Map of cost function plugin RowIDs to tree item IDs.
HDBBrowserInfoPanel * infoPanel_
Info panel widget for displaying the selected element information.
Detailed Description
Window for browsing an HDB.
Displays a tree-view of the HDB, and an info panel which shows details of the element selected in the tree-view.
Definition at line 59 of file HDBBrowserWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget window IDs.
Enumerator
ID_TREE_VIEW
Definition at line 112 of file HDBBrowserWindow.hh.
         {
        ID_TREE_VIEW = 20000
    };
Constructor & Destructor Documentation
HDBBrowserWindow()
HDBBrowserWindow::HDBBrowserWindow (wxWindow * parent, wxWindowID id)
The Constructor.
Parameters
parent Parent window of the browser panel.
id Window identifier.
Definition at line 70 of file HDBBrowserWindow.cc.
                                                                  :
    wxPanel(parent, id), manager_(NULL) {
    wxSplitterWindow* splitter = new wxSplitterWindow(this, wxVERTICAL);
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    tree_ = new wxTreeCtrl(splitter, ID_TREE_VIEW);
    infoPanel_ = new HDBBrowserInfoPanel(splitter, -1);
    splitter->SetMinimumPaneSize(150);
    splitter->SplitVertically(tree_, infoPanel_);
    sizer->Add(splitter, 1, wxGROW);
    Fit();
    SetSizer(sizer);
}
~HDBBrowserWindow()
HDBBrowserWindow::~HDBBrowserWindow () virtual
The destructor.
Definition at line 89 of file HDBBrowserWindow.cc.
{
}
Member Function Documentation
fuArchLabel()
wxString HDBBrowserWindow::fuArchLabel (const TTAMachine::FunctionUnit & fu) const private
Returns label string for an function unit architecture.
Parameters
fu Function unit object to create the label from.
Returns
Label for the fu architecture.
Definition at line 864 of file HDBBrowserWindow.cc.
{
    // Operation names are put in a set which sorts them alphbetically.
    std::set<std::string> opNames;
    for (int i = 0; i < fu.operationCount(); i++) {
        const HWOperation* op = fu.operation(i);
        std::string opName =
            op->name() + "(" + Conversion::toString(op->latency()) + ")";
        opNames.insert(opName);
    }
    wxString archName;
    std::set<std::string>::const_iterator oIter = opNames.begin();
    for (; oIter != opNames.end(); oIter++) {
        archName.Append(WxConversion::toWxString(*oIter));
        archName.Append(_T(" "));
    }
    return archName;
}
References TTAMachine::HWOperation::latency(), TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), Conversion::toString(), and WxConversion::toWxString().
Referenced by update().
isBusEntrySelected()
bool HDBBrowserWindow::isBusEntrySelected ()
Function for checking if a Bus entry is selected in the tree view.
Returns
True, if a bus entry is selected.
Definition at line 407 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(busEntries_, tree_->GetSelection());
}
References busEntries_, MapTools::containsValue(), and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorDeleteCmd::isEnabled(), onItemSelected(), and selectedBusEntry().
isCostFunctionPluginSelected()
bool HDBBrowserWindow::isCostFunctionPluginSelected ()
Function for checking if a cost function plugin is selected in the tree view.
Returns
True, if a cost function plugin is selected.
Definition at line 428 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(costPlugins_, tree_->GetSelection());
}
References MapTools::containsValue(), costPlugins_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), HDBEditorDeleteCmd::isEnabled(), HDBEditorModifyCmd::isEnabled(), onItemSelected(), and selectedCostFunctionPlugin().
isFUArchitectureSelected()
bool HDBBrowserWindow::isFUArchitectureSelected ()
Function for checking if a FU architecture is selected in the tree view.
Returns
True, if a FU architecture is selected.
Definition at line 343 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(fuArchitectures_, tree_->GetSelection());
}
References MapTools::containsValue(), fuArchitectures_, and tree_.
Referenced by AddFUImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), AddFUImplementationCmd::isEnabled(), HDBEditorDeleteCmd::isEnabled(), onItemSelected(), onRMBClick(), and selectedFUArchitecture().
isFUEntrySelected()
bool HDBBrowserWindow::isFUEntrySelected ()
Function for checking if a FU entry is selected in the tree view.
Returns
True, if a FU entry is selected.
Definition at line 387 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(fuEntries_, tree_->GetSelection());
}
References MapTools::containsValue(), fuEntries_, and tree_.
Referenced by AddFUImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), SetCostFunctionPluginCmd::Do(), AddFUImplementationCmd::isEnabled(), HDBEditorDeleteCmd::isEnabled(), SetCostFunctionPluginCmd::isEnabled(), SetFUArchitectureCmd::isEnabled(), onItemSelected(), onRMBClick(), and selectedFUEntry().
isFUImplementationSelected()
bool HDBBrowserWindow::isFUImplementationSelected ()
Function for checking if a FU implementation is selected in the tree view.
Returns
True, if a FU implementation is selected.
Definition at line 364 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(
        fuImplementations_, tree_->GetSelection());
}
References MapTools::containsValue(), fuImplementations_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), HDBEditorDeleteCmd::isEnabled(), HDBEditorModifyCmd::isEnabled(), onItemSelected(), and selectedFUImplementation().
isOperationImplementationResourceSelected()
bool HDBBrowserWindow::isOperationImplementationResourceSelected ()
Function for checking if a operation implementation resource is selected in the tree view.
Returns
True, if selected.
Definition at line 439 of file HDBBrowserWindow.cc.
{
    std::string parent = tree_->GetItemParent(tree_->GetSelection()).IsOk() ?
        tree_->GetItemText(tree_->GetItemParent(tree_->GetSelection()))
        .ToStdString() : "none";
    return parent == "Operation Implementation Resources";
}
References tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorDeleteCmd::isEnabled(), and selectedOperationImplementationResource().
isOperationImplementationSelected()
bool HDBBrowserWindow::isOperationImplementationSelected ()
Function for checking if a operation implementation is selected in the tree view.
Returns
True, if selected.
Definition at line 453 of file HDBBrowserWindow.cc.
{
    std::string parent = tree_->GetItemParent(tree_->GetSelection()).IsOk() ?
        tree_->GetItemText(tree_->GetItemParent(tree_->GetSelection()))
        .ToStdString() : "none";
    return parent == "Operation Implementations";
}
References tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorDeleteCmd::isEnabled(), and selectedOperationImplementation().
isRFArchitectureSelected()
bool HDBBrowserWindow::isRFArchitectureSelected ()
Function for checking if a RF architecture is selected in the tree view.
Returns
True, if a RF architecture is selected.
Definition at line 353 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(rfArchitectures_, tree_->GetSelection());
}
References MapTools::containsValue(), rfArchitectures_, and tree_.
Referenced by AddRFImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), AddRFImplementationCmd::isEnabled(), HDBEditorDeleteCmd::isEnabled(), onItemSelected(), onRMBClick(), and selectedRFArchitecture().
isRFEntrySelected()
bool HDBBrowserWindow::isRFEntrySelected ()
Function for checking if a RF entry is selected in the tree view.
Returns
True, if a RF entry is selected.
Definition at line 397 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(rfEntries_, tree_->GetSelection());
}
References MapTools::containsValue(), rfEntries_, and tree_.
Referenced by AddRFImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), SetCostFunctionPluginCmd::Do(), AddRFImplementationCmd::isEnabled(), HDBEditorDeleteCmd::isEnabled(), SetCostFunctionPluginCmd::isEnabled(), onItemSelected(), onRMBClick(), and selectedRFEntry().
isRFImplementationSelected()
bool HDBBrowserWindow::isRFImplementationSelected ()
Function for checking if a RF implementation is selected in the tree view.
Returns
True, if a RF implementation is selected.
Definition at line 376 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(
        rfImplementations_, tree_->GetSelection());
}
References MapTools::containsValue(), rfImplementations_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), HDBEditorDeleteCmd::isEnabled(), HDBEditorModifyCmd::isEnabled(), onItemSelected(), and selectedRFImplementation().
isSocketEntrySelected()
bool HDBBrowserWindow::isSocketEntrySelected ()
Function for checking if a socket entry is selected in the tree view.
Returns
True, if a socket entry is selected.
Definition at line 417 of file HDBBrowserWindow.cc.
{
    return MapTools::containsValue(socketEntries_, tree_->GetSelection());
}
References MapTools::containsValue(), socketEntries_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorDeleteCmd::isEnabled(), onItemSelected(), and selectedSocketEntry().
onItemSelected()
void HDBBrowserWindow::onItemSelected (wxTreeEvent & e) private
Event handler for the tree-view selection changes.
Definition at line 782 of file HDBBrowserWindow.cc.
{
    wxTreeCtrl* ctrl = new wxTreeCtrl();
    std::string current = ctrl->GetItemText(e.GetItem().GetID()).ToStdString();
    std::string parent = ctrl->GetItemParent(e.GetItem().GetID()).IsOk() ?
        ctrl->GetItemText(ctrl->GetItemParent(e.GetItem().GetID())).ToStdString() :
        "none";
    infoPanel_->clear();
    if (isFUArchitectureSelected()) {
        infoPanel_->displayFUArchitecture(selectedFUArchitecture());
    } else  if (isRFArchitectureSelected()) {
        infoPanel_->displayRFArchitecture(selectedRFArchitecture());
    } else if (isFUImplementationSelected()) {
        infoPanel_->displayFUImplementation(selectedFUImplementation());
    } else if (isRFImplementationSelected()) {
        infoPanel_->displayRFImplementation(selectedRFImplementation());
    } else if (isFUEntrySelected()) {
        infoPanel_->displayFUEntry(selectedFUEntry());
    } else if (isRFEntrySelected()) {
        infoPanel_->displayRFEntry(selectedRFEntry());
    } else if (isBusEntrySelected()) {
        infoPanel_->displayBusEntry(selectedBusEntry());
    } else if (isSocketEntrySelected()) {
        infoPanel_->displaySocketEntry(selectedSocketEntry());
    } else if (isCostFunctionPluginSelected()) {
        infoPanel_->displayCostFunctionPlugin(selectedCostFunctionPlugin());
    } else if (parent == HDBToHtml::OPERATION_IMPLEMENTATIONS) {
        std::istringstream iss(current);
        int id;
        iss >> id;
        infoPanel_->displayOperationImplementation(id);
    } else if (parent == HDBToHtml::OPERATION_IMPLEMENTATION_RESOURCES) {
        std::istringstream iss(current);
        int id;
        iss >> id;
        infoPanel_->displayOperationImplementationResource(id);
    }
    delete ctrl;
}
References HDBBrowserInfoPanel::clear(), HDBBrowserInfoPanel::displayBusEntry(), HDBBrowserInfoPanel::displayCostFunctionPlugin(), HDBBrowserInfoPanel::displayFUArchitecture(), HDBBrowserInfoPanel::displayFUEntry(), HDBBrowserInfoPanel::displayFUImplementation(), HDBBrowserInfoPanel::displayOperationImplementation(), HDBBrowserInfoPanel::displayOperationImplementationResource(), HDBBrowserInfoPanel::displayRFArchitecture(), HDBBrowserInfoPanel::displayRFEntry(), HDBBrowserInfoPanel::displayRFImplementation(), HDBBrowserInfoPanel::displaySocketEntry(), infoPanel_, isBusEntrySelected(), isCostFunctionPluginSelected(), isFUArchitectureSelected(), isFUEntrySelected(), isFUImplementationSelected(), isRFArchitectureSelected(), isRFEntrySelected(), isRFImplementationSelected(), isSocketEntrySelected(), HDBToHtml::OPERATION_IMPLEMENTATION_RESOURCES, HDBToHtml::OPERATION_IMPLEMENTATIONS, selectedBusEntry(), selectedCostFunctionPlugin(), selectedFUArchitecture(), selectedFUEntry(), selectedFUImplementation(), selectedRFArchitecture(), selectedRFEntry(), selectedRFImplementation(), and selectedSocketEntry().
onRMBClick()
void HDBBrowserWindow::onRMBClick (wxTreeEvent & event) private
Event handler for right mouse button clicks in the treeview.
Pops up a context menu.
Definition at line 832 of file HDBBrowserWindow.cc.
{
    tree_->SelectItem(event.GetItem());
    wxMenu* popupMenu = new wxMenu();
    if (isFUArchitectureSelected()) {
        popupMenu->Append(
            HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION,
            _T("Add &Implementation..."));
    }
    if (isRFArchitectureSelected()) {
        popupMenu->Append(
            HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION,
            _T("Add &Implementation..."));
    }
    if (isFUEntrySelected() || isRFEntrySelected()) {
        popupMenu->Append(
            HDBEditorConstants::COMMAND_SET_COST_PLUGIN,
            _T("Set Cost Function Plugin"));
    }
    popupMenu->AppendSeparator();
    popupMenu->Append(HDBEditorConstants::COMMAND_MODIFY, _T("&Modify..."));
    popupMenu->Append(HDBEditorConstants::COMMAND_DELETE, _T("&Delete"));
    PopupMenu(popupMenu, event.GetPoint());
}
References HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION, HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION, HDBEditorConstants::COMMAND_DELETE, HDBEditorConstants::COMMAND_MODIFY, HDBEditorConstants::COMMAND_SET_COST_PLUGIN, isFUArchitectureSelected(), isFUEntrySelected(), isRFArchitectureSelected(), isRFEntrySelected(), and tree_.
openLink()
void HDBBrowserWindow::openLink (const wxString & link)
Opens a link generated by HDBToHtml in the browser window.
Parameters
link Link to open.
Definition at line 892 of file HDBBrowserWindow.cc.
{
    const wxString fuArchPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::FU_ARCHITECTURES) +
        _T("/");
    const wxString rfArchPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::RF_ARCHITECTURES) +
        _T("/");
    const wxString fuEntryPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::FU_ENTRIES) + _T("/");
    const wxString rfEntryPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::RF_ENTRIES) + _T("/");
    const wxString busEntryPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::BUS_ENTRIES) + _T("/");
    const wxString socketEntryPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::SOCKET_ENTRIES) +
        _T("/");
    const wxString fuImplPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::FU_IMPLEMENTATIONS) +
        _T("/");
    const wxString rfImplPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::RF_IMPLEMENTATIONS) +
        _T("/");
    const wxString costPluginPrefix =
        _T("/") + WxConversion::toWxString(HDBToHtml::COST_PLUGINS) + _T("/");
    wxString rest;
    if (link.StartsWith(fuArchPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectFUArchitecture(id);
    } else if (link.StartsWith(rfArchPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectRFArchitecture(id);
    } else if (link.StartsWith(fuEntryPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectFUEntry(id);
    } else if (link.StartsWith(rfEntryPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectRFEntry(id);
    } else if (link.StartsWith(busEntryPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectBusEntry(id);
    } else if (link.StartsWith(socketEntryPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectSocketEntry(id);
    } else if (link.StartsWith(fuImplPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectFUImplementation(id);
    } else if (link.StartsWith(rfImplPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectRFImplementation(id);
    } else if (link.StartsWith(costPluginPrefix, &rest)) {
        int id = Conversion::toInt(WxConversion::toString(rest));
        selectCostFunctionPlugin(id);
    }
}
References HDBToHtml::BUS_ENTRIES, HDBToHtml::COST_PLUGINS, HDBToHtml::FU_ARCHITECTURES, HDBToHtml::FU_ENTRIES, HDBToHtml::FU_IMPLEMENTATIONS, HDBToHtml::RF_ARCHITECTURES, HDBToHtml::RF_ENTRIES, HDBToHtml::RF_IMPLEMENTATIONS, selectBusEntry(), selectCostFunctionPlugin(), selectFUArchitecture(), selectFUEntry(), selectFUImplementation(), selectRFArchitecture(), selectRFEntry(), selectRFImplementation(), selectSocketEntry(), HDBToHtml::SOCKET_ENTRIES, Conversion::toInt(), WxConversion::toString(), and WxConversion::toWxString().
selectBusEntry()
void HDBBrowserWindow::selectBusEntry (int id)
Selects the given Bus Entry.
Parameters
id RowID of the bus entry to select.
Definition at line 679 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(busEntries_, id)) {
        return;
    }
    tree_->SelectItem(busEntries_[id]);
}
References busEntries_, MapTools::containsKey(), and tree_.
Referenced by openLink().
selectCostFunctionPlugin()
void HDBBrowserWindow::selectCostFunctionPlugin (int id)
Selects the given cost function plugin.
Parameters
id RowID of the cost function plugin.
Definition at line 769 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(costPlugins_, id)) {
        return;
    }
    tree_->SelectItem(costPlugins_[id]);
}
References MapTools::containsKey(), costPlugins_, and tree_.
Referenced by openLink().
selectedBusEntry()
RowID HDBBrowserWindow::selectedBusEntry ()
Returns rowID of the bus entry selected in the tree view.
Returns
ID of the selected bus entry, or -1 if none is selected.
Definition at line 565 of file HDBBrowserWindow.cc.
{
    if (!isBusEntrySelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        busEntries_, tree_->GetSelection());
    return id;
}
References busEntries_, isBusEntrySelected(), MapTools::keyForValue(), and tree_.
Referenced by HDBEditorDeleteCmd::Do(), and onItemSelected().
selectedCostFunctionPlugin()
RowID HDBBrowserWindow::selectedCostFunctionPlugin ()
Returns rowID of the cost function plugin selected in the treeview.
Returns
ID of the selected cost function plugin, or -1 if none is selected.
Definition at line 598 of file HDBBrowserWindow.cc.
{
    if (!isCostFunctionPluginSelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        costPlugins_, tree_->GetSelection());
    return id;
}
References costPlugins_, isCostFunctionPluginSelected(), MapTools::keyForValue(), and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), and onItemSelected().
selectedFUArchitecture()
RowID HDBBrowserWindow::selectedFUArchitecture ()
Returns rowID of the FU architecture selected in the treeview.
Returns
ID of the selected FU architecture, or -1 if none is selected.
Definition at line 466 of file HDBBrowserWindow.cc.
{
    if (!isFUArchitectureSelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        fuArchitectures_, tree_->GetSelection());
    return id;
}
References fuArchitectures_, isFUArchitectureSelected(), MapTools::keyForValue(), and tree_.
Referenced by AddFUImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), and onItemSelected().
selectedFUEntry()
RowID HDBBrowserWindow::selectedFUEntry ()
Returns rowID of the FU entry selected in the tree view.
Returns
ID of the selected FU entry, or -1 if none is selected.
Definition at line 533 of file HDBBrowserWindow.cc.
{
    if (!isFUEntrySelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        fuEntries_, tree_->GetSelection());
    return id;
}
References fuEntries_, isFUEntrySelected(), MapTools::keyForValue(), and tree_.
Referenced by AddFUImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), SetCostFunctionPluginCmd::Do(), AddFUImplementationCmd::isEnabled(), SetFUArchitectureCmd::isEnabled(), and onItemSelected().
selectedFUImplementation()
RowID HDBBrowserWindow::selectedFUImplementation ()
Returns rowID of the FU implementation selected in the treeview.
Returns
ID of the selected FU implementation, or -1 if none is selected.
Definition at line 500 of file HDBBrowserWindow.cc.
{
    if (!isFUImplementationSelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        fuImplementations_, tree_->GetSelection());
    return id;
}
References fuImplementations_, isFUImplementationSelected(), MapTools::keyForValue(), and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), and onItemSelected().
selectedOperationImplementation()
RowID HDBBrowserWindow::selectedOperationImplementation ()
Returns rowID of the operation implementation selected in the treeview.
Returns
ID of the selection, or -1 if none is selected.
Definition at line 614 of file HDBBrowserWindow.cc.
{
    if (!isOperationImplementationSelected()) {
        return -1;
    }
    std::istringstream iss(tree_->GetItemText(tree_->GetSelection())
        .ToStdString());
    RowID id;
    iss >> id;
    return id;
}
References isOperationImplementationSelected(), and tree_.
Referenced by HDBEditorDeleteCmd::Do().
selectedOperationImplementationResource()
RowID HDBBrowserWindow::selectedOperationImplementationResource ()
Returns rowID of the operation implementation resource selected in the treeview.
Returns
ID of the selection, or -1 if none is selected.
Definition at line 632 of file HDBBrowserWindow.cc.
{
    if (!isOperationImplementationResourceSelected()) {
        return -1;
    }
    std::istringstream iss(tree_->GetItemText(tree_->GetSelection())
        .ToStdString());
    RowID id;
    iss >> id;
    return id;
}
References isOperationImplementationResourceSelected(), and tree_.
Referenced by HDBEditorDeleteCmd::Do().
selectedRFArchitecture()
RowID HDBBrowserWindow::selectedRFArchitecture ()
Returns rowID of the RF architecture selected in the treeview.
Returns
ID of the selected RF architecture, or -1 if none is selected.
Definition at line 483 of file HDBBrowserWindow.cc.
{
    if (!isRFArchitectureSelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        rfArchitectures_, tree_->GetSelection());
    return id;
}
References isRFArchitectureSelected(), MapTools::keyForValue(), rfArchitectures_, and tree_.
Referenced by AddRFImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), and onItemSelected().
selectedRFEntry()
RowID HDBBrowserWindow::selectedRFEntry ()
Returns rowID of the RF entry selected in the tree view.
Returns
ID of the selected RF entry, or -1 if none is selected.
Definition at line 549 of file HDBBrowserWindow.cc.
{
    if (!isRFEntrySelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        rfEntries_, tree_->GetSelection());
    return id;
}
References isRFEntrySelected(), MapTools::keyForValue(), rfEntries_, and tree_.
Referenced by AddRFImplementationCmd::Do(), HDBEditorDeleteCmd::Do(), SetCostFunctionPluginCmd::Do(), AddRFImplementationCmd::isEnabled(), and onItemSelected().
selectedRFImplementation()
RowID HDBBrowserWindow::selectedRFImplementation ()
Returns rowID of the RF implementation selected in the treeview.
Returns
ID of the selected RF implementation, or -1 if none is selected.
Definition at line 517 of file HDBBrowserWindow.cc.
{
    if (!isRFImplementationSelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        rfImplementations_, tree_->GetSelection());
    return id;
}
References isRFImplementationSelected(), MapTools::keyForValue(), rfImplementations_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), and onItemSelected().
selectedSocketEntry()
RowID HDBBrowserWindow::selectedSocketEntry ()
Returns rowID of the socket entry selected in the tree view.
Returns
ID of the selected socket entry, or -1 if none is selected.
Definition at line 581 of file HDBBrowserWindow.cc.
{
    if (!isSocketEntrySelected()) {
        return -1;
    }
    RowID id = MapTools::keyForValue<RowID>(
        socketEntries_, tree_->GetSelection());
    return id;
}
References isSocketEntrySelected(), MapTools::keyForValue(), socketEntries_, and tree_.
Referenced by HDBEditorDeleteCmd::Do(), and onItemSelected().
selectFUArchitecture()
void HDBBrowserWindow::selectFUArchitecture (int id)
Selects the given FU architecture.
Parameters
id RowID of the
Definition at line 709 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(fuArchitectures_, id)) {
        return;
    }
    tree_->SelectItem(fuArchitectures_[id]);
}
References MapTools::containsKey(), fuArchitectures_, and tree_.
Referenced by openLink().
selectFUEntry()
void HDBBrowserWindow::selectFUEntry (int id)
Selects the given FU Entry.
Parameters
id RowID of the
Definition at line 649 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(fuEntries_, id)) {
        return;
    }
    tree_->SelectItem(fuEntries_[id]);
}
References MapTools::containsKey(), fuEntries_, and tree_.
Referenced by SetCostFunctionPluginCmd::Do(), and openLink().
selectFUImplementation()
void HDBBrowserWindow::selectFUImplementation (int id)
Selects the given FU implementation.
Parameters
id RowID of the FU implementation.
Definition at line 739 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(fuImplementations_, id)) {
        return;
    }
    tree_->SelectItem(fuImplementations_[id]);
}
References MapTools::containsKey(), fuImplementations_, and tree_.
Referenced by openLink().
selectRFArchitecture()
void HDBBrowserWindow::selectRFArchitecture (int id)
Selects the given RF architecture.
Parameters
id RowID of the
Definition at line 724 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(rfArchitectures_, id)) {
        return;
    }
    tree_->SelectItem(rfArchitectures_[id]);
}
References MapTools::containsKey(), rfArchitectures_, and tree_.
Referenced by openLink().
selectRFEntry()
void HDBBrowserWindow::selectRFEntry (int id)
Selects the given RF Entry.
Parameters
id RowID of the RF entry to select.
Definition at line 664 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(rfEntries_, id)) {
        return;
    }
    tree_->SelectItem(rfEntries_[id]);
}
References MapTools::containsKey(), rfEntries_, and tree_.
Referenced by SetCostFunctionPluginCmd::Do(), and openLink().
selectRFImplementation()
void HDBBrowserWindow::selectRFImplementation (int id)
Selects the given RF implementation.
Parameters
id RowID of the RF implementation.
Definition at line 754 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(rfImplementations_, id)) {
        return;
    }
    tree_->SelectItem(rfImplementations_[id]);
}
References MapTools::containsKey(), rfImplementations_, and tree_.
Referenced by openLink().
selectSocketEntry()
void HDBBrowserWindow::selectSocketEntry (int id)
Selects the given Socket Entry.
Parameters
id RowID of the socket entry to select.
Definition at line 694 of file HDBBrowserWindow.cc.
{
    if (!MapTools::containsKey(socketEntries_, id)) {
        return;
    }
    tree_->SelectItem(socketEntries_[id]);
}
References MapTools::containsKey(), socketEntries_, and tree_.
Referenced by openLink().
setHDBManager()
void HDBBrowserWindow::setHDBManager (HDB::CachedHDBManager & manager)
Sets the HDB which is displayed in the browser.
Parameters
manager HDBManager managing the HDB to display.
Definition at line 99 of file HDBBrowserWindow.cc.
{
    manager_ = &manager;
    infoPanel_->setHDB(manager);
    update();
}
References infoPanel_, manager_, HDBBrowserInfoPanel::setHDB(), and update().
Referenced by HDBEditorMainFrame::createHDB(), and HDBEditorMainFrame::setHDB().
update()
void HDBBrowserWindow::update ()
Updates the treeview of the HDB.
Definition at line 109 of file HDBBrowserWindow.cc.
{
    fuArchitectures_.clear();
    rfArchitectures_.clear();
    fuImplementations_.clear();
    rfImplementations_.clear();
    fuEntries_.clear();
    rfEntries_.clear();
    busEntries_.clear();
    socketEntries_.clear();
    costPlugins_.clear();
    tree_->DeleteAllItems();
    wxTreeItemId root = tree_->AddRoot(_T("HDB"));
    wxTreeItemId fus = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::FU_ARCHITECTURES));
    wxTreeItemId rfs = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::RF_ARCHITECTURES));
    wxTreeItemId fuEntries = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::FU_ENTRIES));
    wxTreeItemId rfEntries = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::RF_IU_ENTRIES));
    wxTreeItemId busEntries = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::BUS_ENTRIES));
    wxTreeItemId socketEntries = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::SOCKET_ENTRIES));
    wxTreeItemId costPlugins = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::COST_PLUGINS));
    wxTreeItemId operationImplementations = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::OPERATION_IMPLEMENTATIONS));
    wxTreeItemId operationImplementationResources = tree_->AppendItem(
        root, WxConversion::toWxString(HDBToHtml::OPERATION_IMPLEMENTATION_RESOURCES));
    std::set<RowID>::iterator iter;
    std::set<RowID> fuArchIds = manager_->fuArchitectureIDs();
    std::set<RowID> rfArchIds = manager_->rfArchitectureIDs();
    std::set<RowID> fuIDs = manager_->fuEntryIDs();
    std::set<RowID> rfIDs = manager_->rfEntryIDs();
    std::set<RowID> busIDs = manager_->busEntryIDs();
    std::set<RowID> socketIDs = manager_->socketEntryIDs();
    std::set<RowID> pluginIDs = manager_->costFunctionPluginIDs();
    std::set<RowID> operationImplementationIDs = manager_->OperationImplementationIDs();
    std::set<RowID> operationImplementationResourceIDs = manager_->OperationImplementationResourceIDs();
    int entries = fuArchIds.size() + rfArchIds.size() + fuIDs.size() +
        rfIDs.size() + busIDs.size() + socketIDs.size() + pluginIDs.size();
    int c = 0;
    wxProgressDialog dialog(
        _T("Loading HDB"), _T("Loading HDB"), entries, this,
        wxPD_APP_MODAL|wxPD_AUTO_HIDE);
    dialog.SetSize(300,100);
    int ids = fuArchIds.size();
    int cur = 0;
    wxString message;
    // FU architectures
    for (iter = fuArchIds.begin(); iter != fuArchIds.end(); iter++) {
        const FUArchitecture& arch = manager_->fuArchitectureByIDConst(*iter);
        const FunctionUnit& fu = arch.architecture();
        wxTreeItemId id = tree_->AppendItem(fus, fuArchLabel(fu));
        fuArchitectures_[*iter] = id;
        c++;
        cur++;
        message.Printf(wxT("Loading FU Architectures... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    tree_->SortChildren(fus);
    cur = 0;
    ids = rfArchIds.size();
    // RF architectures
    for (iter = rfArchIds.begin(); iter != rfArchIds.end(); iter++) {
        wxString archLabel = WxConversion::toWxString(*iter);
        wxTreeItemId id = tree_->AppendItem(rfs, archLabel);
        rfArchitectures_[*iter] = id;
        c++;
        cur++;
        message.Printf(wxT("Loading RF Architectures... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // FU Entries
    cur = 0;
    ids = fuIDs.size();
    for (iter = fuIDs.begin(); iter != fuIDs.end(); iter++) {
        const FUEntry* fuEntry = manager_->fuByEntryID(*iter);
        wxString fuEntryLabel = WxConversion::toWxString(*iter);
        wxTreeItemId entryTreeID = tree_->AppendItem(fuEntries, fuEntryLabel);
        fuEntries_[*iter] = entryTreeID;
        if (fuEntry->hasArchitecture()) {
            const FUArchitecture& arch = fuEntry->architecture();
            int archID = arch.id();
            wxTreeItemId archTreeID = fuArchitectures_[archID];
            if (fuEntry->hasImplementation()) {
                const FUImplementation& imp = fuEntry->implementation();
                wxString impName = WxConversion::toWxString(imp.moduleName());
                wxTreeItemId id = tree_->AppendItem(archTreeID, impName);
                fuImplementations_[imp.id()] = id;
            }
        }
        delete fuEntry;
        c++;
        cur++;
        message.Printf(wxT("Loading FU entries... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // RF Entries
    cur = 0;
    ids = rfIDs.size();
    for (iter = rfIDs.begin(); iter != rfIDs.end(); iter++) {
        const RFEntry* rfEntry = manager_->rfByEntryID(*iter);
        wxString rfEntryLabel = WxConversion::toWxString(*iter);
        wxTreeItemId entryTreeID = tree_->AppendItem(rfEntries, rfEntryLabel);
        rfEntries_[*iter] = entryTreeID;
        if (rfEntry->hasArchitecture()) {
            const RFArchitecture& arch = rfEntry->architecture();
            int archID = arch.id();
            wxTreeItemId archTreeID = rfArchitectures_[archID];
            if (rfEntry->hasImplementation()) {
                const RFImplementation& imp = rfEntry->implementation();
                wxString impName = WxConversion::toWxString(imp.moduleName());
                wxTreeItemId id = tree_->AppendItem(archTreeID, impName);
                rfImplementations_[imp.id()] = id;
            }
        }
        delete rfEntry;
        c++;
        cur++;
        message.Printf(wxT("Loading RF entries... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // Bus Entries
    cur = 0;
    ids = busIDs.size();
    for (iter = busIDs.begin(); iter != busIDs.end(); iter++) {
        wxString busEntryLabel = WxConversion::toWxString(*iter);
        wxTreeItemId entryTreeID =
            tree_->AppendItem(busEntries, busEntryLabel);
        busEntries_[*iter] = entryTreeID;
        c++;
        cur++;
        message.Printf(wxT("Loading bus entries... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // Socket Entries
    cur = 0;
    ids = socketIDs.size();
    for (iter = socketIDs.begin(); iter != socketIDs.end(); iter++) {
        wxString socketEntryLabel = WxConversion::toWxString(*iter);
        wxTreeItemId entryTreeID =
            tree_->AppendItem(socketEntries, socketEntryLabel);
        socketEntries_[*iter] = entryTreeID;
        cur++;
        message.Printf(wxT("Loading socket entries... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // Cost estimation plugin data
    cur = 0;
    ids = pluginIDs.size();
    for (iter = pluginIDs.begin(); iter != pluginIDs.end(); iter++) {
        const CostFunctionPlugin* plugin =
            manager_->costFunctionPluginByID(*iter);
        wxString pluginName = WxConversion::toWxString(plugin->name());
        wxTreeItemId id = tree_->AppendItem(costPlugins, pluginName);
        costPlugins_[*iter] = id;
        delete plugin;
        c++;
        cur++;
        message.Printf(wxT("Loading cost estimation plugins... (%04d / %04d)"),cur,ids);
        dialog.Update(c, message);
        dialog.SetSize(300,100);
    }
    // fugenOperations
    for (auto &id : operationImplementationIDs) {
        auto op = manager_->OperationImplementationByID(id);
        std::string label = std::to_string(id) + " : " + op.name;
        tree_->AppendItem(operationImplementations, label);
    }
    // fugenResources
    for (auto &id : operationImplementationResourceIDs) {
        auto res = manager_->OperationImplementationResourceByID(id);
        std::string label = std::to_string(id) + " : " + res.name;
        tree_->AppendItem(operationImplementationResources, label);
    }
    tree_->Expand(root);
    infoPanel_->clear();
}
References HDB::FUArchitecture::architecture(), HDB::FUEntry::architecture(), HDB::RFEntry::architecture(), HDBToHtml::BUS_ENTRIES, busEntries_, HDB::HDBManager::busEntryIDs(), HDBBrowserInfoPanel::clear(), HDBToHtml::COST_PLUGINS, HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginIDs(), costPlugins_, HDBToHtml::FU_ARCHITECTURES, HDBToHtml::FU_ENTRIES, HDB::CachedHDBManager::fuArchitectureByIDConst(), HDB::HDBManager::fuArchitectureIDs(), fuArchitectures_, fuArchLabel(), HDB::HDBManager::fuByEntryID(), fuEntries_, HDB::HDBManager::fuEntryIDs(), fuImplementations_, HDB::FUEntry::hasArchitecture(), HDB::RFEntry::hasArchitecture(), HDB::FUEntry::hasImplementation(), HDB::RFEntry::hasImplementation(), HWBlockArchitecture::id(), HDB::HWBlockImplementation::id(), HDB::FUEntry::implementation(), HDB::RFEntry::implementation(), infoPanel_, manager_, HDB::HWBlockImplementation::moduleName(), HDB::CostFunctionPlugin::name(), HDB::OperationImplementation::name, HDB::OperationImplementationResource::name, HDBToHtml::OPERATION_IMPLEMENTATION_RESOURCES, HDBToHtml::OPERATION_IMPLEMENTATIONS, HDB::HDBManager::OperationImplementationByID(), HDB::HDBManager::OperationImplementationIDs(), HDB::HDBManager::OperationImplementationResourceByID(), HDB::HDBManager::OperationImplementationResourceIDs(), HDBToHtml::RF_ARCHITECTURES, HDBToHtml::RF_IU_ENTRIES, HDB::HDBManager::rfArchitectureIDs(), rfArchitectures_, HDB::HDBManager::rfByEntryID(), rfEntries_, HDB::HDBManager::rfEntryIDs(), rfImplementations_, HDBToHtml::SOCKET_ENTRIES, socketEntries_, HDB::HDBManager::socketEntryIDs(), WxConversion::toWxString(), and tree_.
Referenced by setHDBManager(), and HDBEditorMainFrame::update().
Member Data Documentation
busEntries_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::busEntries_ private
Map of bus entry RowIDs to tree item IDs.
Definition at line 129 of file HDBBrowserWindow.hh.
Referenced by isBusEntrySelected(), selectBusEntry(), selectedBusEntry(), and update().
costPlugins_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::costPlugins_ private
Map of cost function plugin RowIDs to tree item IDs.
Definition at line 133 of file HDBBrowserWindow.hh.
Referenced by isCostFunctionPluginSelected(), selectCostFunctionPlugin(), selectedCostFunctionPlugin(), and update().
fuArchitectures_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::fuArchitectures_ private
Map of fu architecture RowIDs to tree item IDs.
Definition at line 121 of file HDBBrowserWindow.hh.
Referenced by isFUArchitectureSelected(), selectedFUArchitecture(), selectFUArchitecture(), and update().
fuEntries_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::fuEntries_ private
Map of fu entry RowIDs to tree item IDs.
Definition at line 125 of file HDBBrowserWindow.hh.
Referenced by isFUEntrySelected(), selectedFUEntry(), selectFUEntry(), and update().
fuImplementations_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::fuImplementations_ private
Map of fu implementation RowIDs to tree item IDs.
Definition at line 123 of file HDBBrowserWindow.hh.
Referenced by isFUImplementationSelected(), selectedFUImplementation(), selectFUImplementation(), and update().
infoPanel_
HDBBrowserInfoPanel* HDBBrowserWindow::infoPanel_ private
Info panel widget for displaying the selected element information.
Definition at line 136 of file HDBBrowserWindow.hh.
Referenced by onItemSelected(), setHDBManager(), and update().
manager_
HDB::CachedHDBManager* HDBBrowserWindow::manager_ private
HDB to display in the browser.
Definition at line 103 of file HDBBrowserWindow.hh.
Referenced by setHDBManager(), and update().
rfArchitectures_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::rfArchitectures_ private
Map of rf architecture RowIDs to tree item IDs.
Definition at line 117 of file HDBBrowserWindow.hh.
Referenced by isRFArchitectureSelected(), selectedRFArchitecture(), selectRFArchitecture(), and update().
rfEntries_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::rfEntries_ private
Map of rf entry RowIDs to tree item IDs.
Definition at line 127 of file HDBBrowserWindow.hh.
Referenced by isRFEntrySelected(), selectedRFEntry(), selectRFEntry(), and update().
rfImplementations_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::rfImplementations_ private
Map of rf implementation RowIDs to tree item IDs.
Definition at line 119 of file HDBBrowserWindow.hh.
Referenced by isRFImplementationSelected(), selectedRFImplementation(), selectRFImplementation(), and update().
socketEntries_
std::map<RowID, wxTreeItemId> HDBBrowserWindow::socketEntries_ private
Map of socket entry RowIDs to tree item IDs.
Definition at line 131 of file HDBBrowserWindow.hh.
Referenced by isSocketEntrySelected(), selectedSocketEntry(), selectSocketEntry(), and update().
tree_
wxTreeCtrl* HDBBrowserWindow::tree_ private
Tree widget displayign the HDB hierarchy.
Definition at line 105 of file HDBBrowserWindow.hh.
Referenced by isBusEntrySelected(), isCostFunctionPluginSelected(), isFUArchitectureSelected(), isFUEntrySelected(), isFUImplementationSelected(), isOperationImplementationResourceSelected(), isOperationImplementationSelected(), isRFArchitectureSelected(), isRFEntrySelected(), isRFImplementationSelected(), isSocketEntrySelected(), onRMBClick(), selectBusEntry(), selectCostFunctionPlugin(), selectedBusEntry(), selectedCostFunctionPlugin(), selectedFUArchitecture(), selectedFUEntry(), selectedFUImplementation(), selectedOperationImplementation(), selectedOperationImplementationResource(), selectedRFArchitecture(), selectedRFEntry(), selectedRFImplementation(), selectedSocketEntry(), selectFUArchitecture(), selectFUEntry(), selectFUImplementation(), selectRFArchitecture(), selectRFEntry(), selectRFImplementation(), selectSocketEntry(), and update().
The documentation for this class was generated from the following files:
HDBBrowserWindow.hh
HDBBrowserWindow.cc