OpenASIP: OSEdTextGenerator Class Reference
OSEdTextGenerator Class Reference
#include <OSEdTextGenerator.hh>
Public Types
enum {
TXT_LABEL_OPERATION_NAME = Texts::LAST__ , TXT_LABEL_MODULE_NAME , TXT_LABEL_HAS_BEHAVIOR , TXT_LABEL_NO_BEHAVIOR ,
TXT_LABEL_READY , TXT_LABEL_UPDATE , TXT_LABEL_EDITOR , TXT_LABEL_FORMAT ,
TXT_LABEL_CLOCK , TXT_LABEL_PC , TXT_LABEL_RA , TXT_LABEL_SYS_CALL_HANDLER ,
TXT_LABEL_SYS_CALL_NUMBER , TXT_LABEL_MODE , TXT_LABEL_END , TXT_LABEL_START ,
TXT_BUTTON_MODIFY , TXT_BUTTON_OPEN , TXT_BUTTON_TRIGGER , TXT_BUTTON_LATE_RESULT ,
TXT_BUTTON_ADVANCE_LOCK , TXT_BUTTON_SAVE , TXT_BUTTON_UNDO , TXT_BUTTON_DELETE ,
TXT_BUTTON_NEW , TXT_BUTTON_BROWSE , TXT_BUTTON_RESET , TXT_BUTTON_CLOSE ,
TXT_BUTTON_SHOW_REGISTERS , TXT_BUTTON_HIDE_REGISTERS , TXT_BUTTON_UPDATE , TXT_CHECKBOX_READS_MEMORY ,
TXT_CHECKBOX_WRITES_MEMORY , TXT_CHECKBOX_CAN_TRAP , TXT_CHECKBOX_HAS_SIDE_EFFECTS , TXT_CHECKBOX_CLOCKED ,
TXT_CHECKBOX_MEM_DATA , TXT_CHECKBOX_MEM_ADDRESS , TXT_COLUMN_OPERATION , TXT_COLUMN_OPERAND ,
TXT_COLUMN_TYPE , TXT_COLUMN_VALUE , TXT_COLUMN_SEARCH_PATHS , TXT_COLUMN_MODULES ,
TXT_COLUMN_OPERATIONS , TXT_COLUMN_PROPERTY , TXT_COLUMN_OPERAND_VALUE , TXT_COLUMN_ELEMENT_WIDTH ,
TXT_COLUMN_ELEMENT_COUNT , TXT_PROPERTY_DIALOG_TITLE , TXT_INPUT_OPERAND_DIALOG_TITLE , TXT_OUTPUT_OPERAND_DIALOG_TITLE ,
TXT_ADD_MODULE_DIALOG_TITLE , TXT_SIMULATE_DIALOG_TITLE , TXT_OPTIONS_DIALOG_TITLE , TXT_BUILD_RESULT_DIALOG_TITLE ,
TXT_USER_MANUAL_TITLE , TXT_XML_RESULT_DIALOG_TITLE , TXT_ABOUT_DIALOG_TITLE , TXT_SIMULATION_INFO_DIALOG_TITLE ,
TXT_MEMORY_DIALOG_TITLE , TXT_BOX_AFFECTS , TXT_BOX_AFFECTED_BY , TXT_BOX_INPUT_OPERANDS ,
TXT_BOX_OUTPUT_OPERANDS , TXT_BOX_CAN_SWAP , TXT_BOX_INPUT_VALUES , TXT_BOX_OUTPUT_VALUES ,
TXT_ERROR_NO_NAME , TXT_ERROR_CAN_NOT_MODIFY , TXT_ERROR_CAN_NOT_CREATE_MOD , TXT_ERROR_CAN_NOT_CREATE_OP ,
TXT_ERROR_NO_EDITOR , TXT_ERROR_OPEN , TXT_ERROR_CAN_NOT_SAVE , TXT_ERROR_NON_EXISTING_OPERATION ,
TXT_ERROR_TRIGGER_FAILED , TXT_ERROR_CAN_NOT_REMOVE_OPERATION , TXT_ERROR_MODULE_EXISTS , TXT_ERROR_OPERATION_EXISTS ,
TXT_ERROR_NO_HANDLER , TXT_ERROR_MOD_NAME , TXT_MSG_BUILD_OK , TXT_ABOUT ,
TXT_MENU_OPTIONS , TXT_MENU_QUIT , TXT_MENU_FILE , TXT_MENU_ADD_OPERATION ,
TXT_MENU_REMOVE_OPERATION , TXT_MENU_ADD_MODULE , TXT_MENU_MODIFY_PROPERTIES , TXT_MENU_BUILD ,
TXT_MENU_BUILD_ALL , TXT_MENU_SIMULATE , TXT_MENU_TOOLS , TXT_MENU_ABOUT ,
TXT_MENU_USER_MANUAL , TXT_MENU_HELP , TXT_MENU_REMOVE_MODULE , TXT_MENU_MODIFY_BEHAVIOR ,
TXT_MENU_MEMORY , TXT_ROW_NAME , TXT_ROW_DESCRIPTION , TXT_ROW_INPUTS ,
TXT_ROW_OUTPUTS , TXT_ROW_READS_MEMORY , TXT_ROW_TRUE , TXT_ROW_FALSE ,
TXT_ROW_WRITES_MEMORY , TXT_ROW_CAN_TRAP , TXT_ROW_HAS_SIDE_EFFECTS , TXT_ROW_CLOCKED ,
TXT_ROW_AFFECTED_BY , TXT_ROW_AFFECTS , TXT_ROW_INPUT_OPERANDS , TXT_ROW_OUTPUT_OPERANDS ,
TXT_ROW_ID , TXT_ROW_YES , TXT_ROW_NO , TXT_ROW_TYPE ,
TXT_ROW_MEMORY_ADDRESS , TXT_ROW_CAN_SWAP , TXT_ROW_MEMORY_DATA , TXT_ROW_HAS_BEHAVIOR ,
TXT_QUESTION_REMOVE_MODULE , TXT_QUESTION_REMOVE_BEHAVIOR_FILE , TXT_QUESTION_SAVE_PROPERTIES , TXT_QUESTION_REMOVE_OPERATION ,
TXT_STATUS_PATH_SELECTED , TXT_STATUS_MODULE_SELECTED , TXT_STATUS_OPERATION_SELECTED , TXT_STATUS_COMPILING ,
TXT_STATUS_COMPILE_SUCCESS , TXT_STATUS_COMPILE_FAILED
}
Static Public Member Functions
static OSEdTextGenerator & instance ()
static void destroy ()
Private Member Functions
OSEdTextGenerator ()
virtual ~OSEdTextGenerator ()
Static Private Attributes
static OSEdTextGenerator * instance_ = NULL
Static instance of text generator.
Additional Inherited Members
Public Member Functions inherited from Texts::TextGenerator
TextGenerator ()
virtual ~TextGenerator ()
virtual boost::format text (int textId)
virtual void addText (int textId, const std::string &templateString)
virtual void replaceText (int textId, const std::string &newString)
Detailed Description
Provides static texts visible in the OSEd user interface.
Definition at line 42 of file OSEdTextGenerator.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Text ids.
Enumerator
TXT_LABEL_OPERATION_NAME
Operation name label.
TXT_LABEL_MODULE_NAME
Module name label.
TXT_LABEL_HAS_BEHAVIOR
Has behavior label.
TXT_LABEL_NO_BEHAVIOR
No behavior label.
TXT_LABEL_READY
Ready label.
TXT_LABEL_UPDATE
Update label.
TXT_LABEL_EDITOR
Editor label.
TXT_LABEL_FORMAT
Format label.
TXT_LABEL_CLOCK
Clock label.
TXT_LABEL_PC
Program counter label.
TXT_LABEL_RA
Return address label.
TXT_LABEL_SYS_CALL_HANDLER
Sys call handler label.
TXT_LABEL_SYS_CALL_NUMBER
Sys call number label.
TXT_LABEL_MODE
Mode label.
TXT_LABEL_END
Memory end label.
TXT_LABEL_START
Memory start label.
TXT_BUTTON_MODIFY
Modify button label.
TXT_BUTTON_OPEN
Open button label.
TXT_BUTTON_TRIGGER
Trigger button label.
TXT_BUTTON_LATE_RESULT
Late result button label.
TXT_BUTTON_ADVANCE_LOCK
Advance Lock button label.
TXT_BUTTON_SAVE
Save button label.
TXT_BUTTON_UNDO
Undo button label.
TXT_BUTTON_DELETE
Delete button label.
TXT_BUTTON_NEW
New button label.
TXT_BUTTON_BROWSE
Browse button label.
TXT_BUTTON_RESET
Reset button label.
TXT_BUTTON_CLOSE
Close button label.
TXT_BUTTON_SHOW_REGISTERS
Show registers button label.
TXT_BUTTON_HIDE_REGISTERS
Hide registers button label.
TXT_BUTTON_UPDATE
Update button label.
TXT_CHECKBOX_READS_MEMORY
Reads memory label.
TXT_CHECKBOX_WRITES_MEMORY
Writes memory label.
TXT_CHECKBOX_CAN_TRAP
Can trap label.
TXT_CHECKBOX_HAS_SIDE_EFFECTS
Has side effects label.
TXT_CHECKBOX_CLOCKED
Clocked label.
TXT_CHECKBOX_MEM_DATA
Memory data label.
TXT_CHECKBOX_MEM_ADDRESS
Memory address label.
TXT_COLUMN_OPERATION
Operation column header.
TXT_COLUMN_OPERAND
Operand column header.
TXT_COLUMN_TYPE
Type column header.
TXT_COLUMN_VALUE
Value column header.
TXT_COLUMN_SEARCH_PATHS
Search path column header.
TXT_COLUMN_MODULES
Module column header.
TXT_COLUMN_OPERATIONS
Operations column header.
TXT_COLUMN_PROPERTY
Property column header.
TXT_COLUMN_OPERAND_VALUE
Operand value column header.
TXT_COLUMN_ELEMENT_WIDTH
Operand element width header.
TXT_COLUMN_ELEMENT_COUNT
Operand element count header.
TXT_PROPERTY_DIALOG_TITLE
Property dialog title.
TXT_INPUT_OPERAND_DIALOG_TITLE
Input operand dialog title.
TXT_OUTPUT_OPERAND_DIALOG_TITLE
Output operand dialog title.
TXT_ADD_MODULE_DIALOG_TITLE
Add module dialog title.
TXT_SIMULATE_DIALOG_TITLE
Simulate dialog title.
TXT_OPTIONS_DIALOG_TITLE
Options dialog title.
TXT_BUILD_RESULT_DIALOG_TITLE
Build result dialog title.
TXT_USER_MANUAL_TITLE
User manual dialog title.
TXT_XML_RESULT_DIALOG_TITLE
XML result dialog title.
TXT_ABOUT_DIALOG_TITLE
About dialog title.
TXT_SIMULATION_INFO_DIALOG_TITLE
Simulation info dialog title.
TXT_MEMORY_DIALOG_TITLE
Memory dialog title.
TXT_BOX_AFFECTS
Affects sizer label.
TXT_BOX_AFFECTED_BY
Affected by sizer label.
TXT_BOX_INPUT_OPERANDS
Input operand sizer label.
TXT_BOX_OUTPUT_OPERANDS
Output operand sizer label.
TXT_BOX_CAN_SWAP
Can swap sizer label.
TXT_BOX_INPUT_VALUES
Input values sizer label.
TXT_BOX_OUTPUT_VALUES
Output values sizer label.
TXT_ERROR_NO_NAME
Error when no name is given.
TXT_ERROR_CAN_NOT_MODIFY
Error when can not modify.
TXT_ERROR_CAN_NOT_CREATE_MOD
Error when can not create module.
TXT_ERROR_CAN_NOT_CREATE_OP
Error when can not create operation.
TXT_ERROR_NO_EDITOR
Error when no editor is given.
TXT_ERROR_OPEN
Error when opening fails.
TXT_ERROR_CAN_NOT_SAVE
Error when options can not be saved.
TXT_ERROR_NON_EXISTING_OPERATION
Error when operation does not exist.
TXT_ERROR_TRIGGER_FAILED
Error when trigger fails.
TXT_ERROR_CAN_NOT_REMOVE_OPERATION
Error when operation can not be removed.
TXT_ERROR_MODULE_EXISTS
Module exists error.
TXT_ERROR_OPERATION_EXISTS
Operation exists error.
TXT_ERROR_NO_HANDLER
Error when custom command handler is not found.
TXT_ERROR_MOD_NAME
Module name is erronous.
TXT_MSG_BUILD_OK
Build ok message.
TXT_ABOUT
About text.
TXT_MENU_OPTIONS
Option menu label.
TXT_MENU_QUIT
Quit menu label.
TXT_MENU_FILE
File menu label.
TXT_MENU_ADD_OPERATION
Add operation menu label.
TXT_MENU_REMOVE_OPERATION
Remove operation menu label.
TXT_MENU_ADD_MODULE
Add module menu label.
TXT_MENU_MODIFY_PROPERTIES
Modify properties menu label.
TXT_MENU_BUILD
Build menu label.
TXT_MENU_BUILD_ALL
Build all menu label.
TXT_MENU_SIMULATE
Simulate menu label.
TXT_MENU_TOOLS
Tools menu label.
TXT_MENU_ABOUT
About menu label.
TXT_MENU_USER_MANUAL
User manual menu label.
TXT_MENU_HELP
Help menu label.
TXT_MENU_REMOVE_MODULE
Remove module menu label.
TXT_MENU_MODIFY_BEHAVIOR
Modify behavior menu label.
TXT_MENU_MEMORY
Memory menu label.
TXT_ROW_NAME
Name row label.
TXT_ROW_DESCRIPTION
Description row label.
TXT_ROW_INPUTS
Inputs row label.
TXT_ROW_OUTPUTS
Outputs row label.
TXT_ROW_READS_MEMORY
Reads memory row label.
TXT_ROW_TRUE
True text.
TXT_ROW_FALSE
False text.
TXT_ROW_WRITES_MEMORY
Writes memory row label.
TXT_ROW_CAN_TRAP
Can trap row label.
TXT_ROW_HAS_SIDE_EFFECTS
Has side effects row label.
TXT_ROW_CLOCKED
Clocked row label.
TXT_ROW_AFFECTED_BY
Affected by row label.
TXT_ROW_AFFECTS
Affects row label.
TXT_ROW_INPUT_OPERANDS
Input operands row label.
TXT_ROW_OUTPUT_OPERANDS
Output operands row label.
TXT_ROW_ID
Id row label.
TXT_ROW_YES
Yes text.
TXT_ROW_NO
No text.
TXT_ROW_TYPE
Type row label.
TXT_ROW_MEMORY_ADDRESS
Memory address row label.
TXT_ROW_CAN_SWAP
Can swap row label.
TXT_ROW_MEMORY_DATA
Memory data row label.
TXT_ROW_HAS_BEHAVIOR
Has behavior row label.
TXT_QUESTION_REMOVE_MODULE
Remove module question.
TXT_QUESTION_REMOVE_BEHAVIOR_FILE
Remove behavior question.
TXT_QUESTION_SAVE_PROPERTIES
Save properties question.
TXT_QUESTION_REMOVE_OPERATION
Remove operation question.
TXT_STATUS_PATH_SELECTED
Status bar text when path is selected.
TXT_STATUS_MODULE_SELECTED
Status bar text when module is selected.
TXT_STATUS_OPERATION_SELECTED
Status bar text when operation is selected.
TXT_STATUS_COMPILING
Status bar text when compiling.
TXT_STATUS_COMPILE_SUCCESS
Status bar text when compiling was successful.
TXT_STATUS_COMPILE_FAILED
Status bar text when compilation failed.
Definition at line 50 of file OSEdTextGenerator.hh.
         {
        // text labels
        TXT_LABEL_OPERATION_NAME = Texts::LAST__, ///< Operation name label.
        TXT_LABEL_MODULE_NAME,            ///< Module name label.
        TXT_LABEL_HAS_BEHAVIOR,           ///< Has behavior label.
        TXT_LABEL_NO_BEHAVIOR,            ///< No behavior label.
        TXT_LABEL_READY,                  ///< Ready label.
        TXT_LABEL_UPDATE,                 ///< Update label.
        TXT_LABEL_EDITOR,                 ///< Editor label.
        TXT_LABEL_FORMAT,                 ///< Format label.
        TXT_LABEL_CLOCK,                  ///< Clock label.
        TXT_LABEL_PC,                     ///< Program counter label.
        TXT_LABEL_RA,                     ///< Return address label.
        TXT_LABEL_SYS_CALL_HANDLER,       ///< Sys call handler label.
        TXT_LABEL_SYS_CALL_NUMBER,        ///< Sys call number label.
        TXT_LABEL_MODE,                   ///< Mode label.
        TXT_LABEL_END,                    ///< Memory end label.
        TXT_LABEL_START,                  ///< Memory start label.
        // button labels
        TXT_BUTTON_MODIFY,                ///< Modify button label.
        TXT_BUTTON_OPEN,                  ///< Open button label.
        TXT_BUTTON_TRIGGER,               ///< Trigger button label.
        TXT_BUTTON_LATE_RESULT,           ///< Late result button label.
        TXT_BUTTON_ADVANCE_LOCK,          ///< Advance Lock button label.
        TXT_BUTTON_SAVE,                  ///< Save button label.
        TXT_BUTTON_UNDO,                  ///< Undo button label.
        TXT_BUTTON_DELETE,                ///< Delete button label.
        TXT_BUTTON_NEW,                   ///< New button label.
        TXT_BUTTON_BROWSE,                ///< Browse button label.
        TXT_BUTTON_RESET,                 ///< Reset button label.
        TXT_BUTTON_CLOSE,                 ///< Close button label.
        TXT_BUTTON_SHOW_REGISTERS,        ///< Show registers button label.
        TXT_BUTTON_HIDE_REGISTERS,        ///< Hide registers button label.
        TXT_BUTTON_UPDATE,                ///< Update button label.
        // checkbox texts
        TXT_CHECKBOX_READS_MEMORY,        ///< Reads memory label.
        TXT_CHECKBOX_WRITES_MEMORY,       ///< Writes memory label.
        TXT_CHECKBOX_CAN_TRAP,            ///< Can trap label.
        TXT_CHECKBOX_HAS_SIDE_EFFECTS,    ///< Has side effects label.
        TXT_CHECKBOX_CLOCKED,             ///< Clocked label.
        TXT_CHECKBOX_MEM_DATA,            ///< Memory data label.
        TXT_CHECKBOX_MEM_ADDRESS,         ///< Memory address label.
        // column headers
        TXT_COLUMN_OPERATION,             ///< Operation column header.
        TXT_COLUMN_OPERAND,               ///< Operand column header.
        TXT_COLUMN_TYPE,                  ///< Type column header.
        TXT_COLUMN_VALUE,                 ///< Value column header.
        TXT_COLUMN_SEARCH_PATHS,          ///< Search path column header.
        TXT_COLUMN_MODULES,               ///< Module column header.
        TXT_COLUMN_OPERATIONS,            ///< Operations column header.
        TXT_COLUMN_PROPERTY,              ///< Property column header.
        TXT_COLUMN_OPERAND_VALUE,         ///< Operand value column header.
        TXT_COLUMN_ELEMENT_WIDTH,         ///< Operand element width header.
        TXT_COLUMN_ELEMENT_COUNT,         ///< Operand element count header.
        // dialog titles
        TXT_PROPERTY_DIALOG_TITLE,        ///< Property dialog title.
        TXT_INPUT_OPERAND_DIALOG_TITLE,   ///< Input operand dialog title.
        TXT_OUTPUT_OPERAND_DIALOG_TITLE,  ///< Output operand dialog title.
        TXT_ADD_MODULE_DIALOG_TITLE,      ///< Add module dialog title.
        TXT_SIMULATE_DIALOG_TITLE,        ///< Simulate dialog title.
        TXT_OPTIONS_DIALOG_TITLE,         ///< Options dialog title.
        TXT_BUILD_RESULT_DIALOG_TITLE,    ///< Build result dialog title.
        TXT_USER_MANUAL_TITLE,            ///< User manual dialog title.
        TXT_XML_RESULT_DIALOG_TITLE,      ///< XML result dialog title.
        TXT_ABOUT_DIALOG_TITLE,           ///< About dialog title.
        TXT_SIMULATION_INFO_DIALOG_TITLE, ///< Simulation info dialog title.
        TXT_MEMORY_DIALOG_TITLE,          ///< Memory dialog title.
        // box sizer labels
        TXT_BOX_AFFECTS,                  ///< Affects sizer label.
        TXT_BOX_AFFECTED_BY,              ///< Affected by sizer label.
        TXT_BOX_INPUT_OPERANDS,           ///< Input operand sizer label.
        TXT_BOX_OUTPUT_OPERANDS,          ///< Output operand sizer label.
        TXT_BOX_CAN_SWAP,                 ///< Can swap sizer label.
        TXT_BOX_INPUT_VALUES,             ///< Input values sizer label.
        TXT_BOX_OUTPUT_VALUES,            ///< Output values sizer label.
        // error texts
        TXT_ERROR_NO_NAME,                ///< Error when no name is given.
        TXT_ERROR_CAN_NOT_MODIFY,         ///< Error when can not modify.
        TXT_ERROR_CAN_NOT_CREATE_MOD,     ///< Error when can not create
                                          ///< module.
        TXT_ERROR_CAN_NOT_CREATE_OP,      ///< Error when can not create
                                          ///< operation.
        TXT_ERROR_NO_EDITOR,              ///< Error when no editor is given.
        TXT_ERROR_OPEN,                   ///< Error when opening fails.
        TXT_ERROR_CAN_NOT_SAVE,           ///< Error when options can not be
                                          ///< saved.
        TXT_ERROR_NON_EXISTING_OPERATION, ///< Error when operation does not
                                          ///< exist.
        TXT_ERROR_TRIGGER_FAILED,         ///< Error when trigger fails.
        TXT_ERROR_CAN_NOT_REMOVE_OPERATION, ///< Error when operation can not
                                            ///< be removed.
        TXT_ERROR_MODULE_EXISTS,          ///< Module exists error.
        TXT_ERROR_OPERATION_EXISTS,       ///< Operation exists error.
        TXT_ERROR_NO_HANDLER,             ///< Error when custom command handler
                                          ///< is not found.
        TXT_ERROR_MOD_NAME,               ///< Module name is erronous.
        // message
        TXT_MSG_BUILD_OK,                 ///< Build ok message.
        // about text
        TXT_ABOUT,                        ///< About text.
        // menu item labels
        TXT_MENU_OPTIONS,                 ///< Option menu label.
        TXT_MENU_QUIT,                    ///< Quit menu label.
        TXT_MENU_FILE,                    ///< File menu label.
        TXT_MENU_ADD_OPERATION,           ///< Add operation menu label.
        TXT_MENU_REMOVE_OPERATION,        ///< Remove operation menu label.
        TXT_MENU_ADD_MODULE,              ///< Add module menu label.
        TXT_MENU_MODIFY_PROPERTIES,       ///< Modify properties menu label.
        TXT_MENU_BUILD,                   ///< Build menu label.
        TXT_MENU_BUILD_ALL,               ///< Build all menu label.
        TXT_MENU_SIMULATE,                ///< Simulate menu label.
        TXT_MENU_TOOLS,                   ///< Tools menu label.
        TXT_MENU_ABOUT,                   ///< About menu label.
        TXT_MENU_USER_MANUAL,             ///< User manual menu label.
        TXT_MENU_HELP,                    ///< Help menu label.
        TXT_MENU_REMOVE_MODULE,           ///< Remove module menu label.
        TXT_MENU_MODIFY_BEHAVIOR,         ///< Modify behavior menu label.
        TXT_MENU_MEMORY,                  ///< Memory menu label.
        // row texts
        TXT_ROW_NAME,                     ///< Name row label.
        TXT_ROW_DESCRIPTION,              ///< Description row label.
        TXT_ROW_INPUTS,                   ///< Inputs row label.
        TXT_ROW_OUTPUTS,                  ///< Outputs row label.
        TXT_ROW_READS_MEMORY,             ///< Reads memory row label.
        TXT_ROW_TRUE,                     ///< True text.
        TXT_ROW_FALSE,                    ///< False text.
        TXT_ROW_WRITES_MEMORY,            ///< Writes memory row label.
        TXT_ROW_CAN_TRAP,                 ///< Can trap row label.
        TXT_ROW_HAS_SIDE_EFFECTS,         ///< Has side effects row label.
        TXT_ROW_CLOCKED,                  ///< Clocked row label.
        TXT_ROW_AFFECTED_BY,              ///< Affected by row label.
        TXT_ROW_AFFECTS,                  ///< Affects row label.
        TXT_ROW_INPUT_OPERANDS,           ///< Input operands row label.
        TXT_ROW_OUTPUT_OPERANDS,          ///< Output operands row label.
        TXT_ROW_ID,                       ///< Id row label.
        TXT_ROW_YES,                      ///< Yes text.
        TXT_ROW_NO,                       ///< No text.
        TXT_ROW_TYPE,                     ///< Type row label.
        TXT_ROW_MEMORY_ADDRESS,           ///< Memory address row label.
        TXT_ROW_CAN_SWAP,                 ///< Can swap row label.
        TXT_ROW_MEMORY_DATA,              ///< Memory data row label.
        TXT_ROW_HAS_BEHAVIOR,             ///< Has behavior row label.
        // questions
        TXT_QUESTION_REMOVE_MODULE,       ///< Remove module question.
        TXT_QUESTION_REMOVE_BEHAVIOR_FILE,///< Remove behavior question.
        TXT_QUESTION_SAVE_PROPERTIES,     ///< Save properties question.
        TXT_QUESTION_REMOVE_OPERATION,    ///< Remove operation question.
        TXT_STATUS_PATH_SELECTED,         ///< Status bar text when path
                                          ///< is selected.
        TXT_STATUS_MODULE_SELECTED,       ///< Status bar text when module
                                          ///< is selected.
        TXT_STATUS_OPERATION_SELECTED,    ///< Status bar text when operation
                                          ///< is selected.
        TXT_STATUS_COMPILING,             ///< Status bar text when compiling.
        TXT_STATUS_COMPILE_SUCCESS,       ///< Status bar text when compiling
                                          ///< was successful.
        TXT_STATUS_COMPILE_FAILED         ///< Status bar text when compilation
                                          ///< failed.
    };
Constructor & Destructor Documentation
OSEdTextGenerator()
OSEdTextGenerator::OSEdTextGenerator () private
Constructor.
Definition at line 40 of file OSEdTextGenerator.cc.
{
    addText(TXT_LABEL_OPERATION_NAME, "Name:");
    addText(TXT_LABEL_MODULE_NAME, "Name of the module:");
    addText(TXT_LABEL_HAS_BEHAVIOR, "Operation behavior module defined.");
    addText(TXT_LABEL_NO_BEHAVIOR, "Operation behavior module not defined.");
    addText(TXT_LABEL_READY, "Ready");
    addText(TXT_LABEL_UPDATE, "Update");
    addText(TXT_LABEL_EDITOR, "Source code editor:");
    addText(TXT_LABEL_FORMAT, "Format:");
    addText(TXT_LABEL_CLOCK, "Clock count:");
    addText(TXT_LABEL_PC, "Program counter:");
    addText(TXT_LABEL_RA, "Return address:");
    addText(TXT_LABEL_SYS_CALL_HANDLER, "System call handler:");
    addText(TXT_LABEL_SYS_CALL_NUMBER, "System call number:");
    addText(TXT_LABEL_MODE, "Mode:");
    addText(TXT_LABEL_END, "End point:");
    addText(TXT_LABEL_START, "Start point:");
    addText(TXT_BUTTON_MODIFY, "Modify...");
    addText(TXT_BUTTON_OPEN, "Open");
    addText(TXT_BUTTON_TRIGGER, "Trigger");
    addText(TXT_BUTTON_ADVANCE_LOCK, "Advance Clock");
    addText(TXT_BUTTON_SAVE, "Save");
    addText(TXT_BUTTON_UNDO, "Undo");
    addText(TXT_BUTTON_DELETE, "Delete");
    addText(TXT_BUTTON_NEW, "New");
    addText(TXT_BUTTON_BROWSE, "Browse");
    addText(TXT_BUTTON_RESET, "Reset");
    addText(TXT_BUTTON_CLOSE, "Close");
    addText(TXT_BUTTON_SHOW_REGISTERS, "Show registers");
    addText(TXT_BUTTON_HIDE_REGISTERS, "Hide registers");
    addText(TXT_BUTTON_UPDATE, "Update");
    addText(TXT_CHECKBOX_READS_MEMORY, "Reads memory");
    addText(TXT_CHECKBOX_WRITES_MEMORY, "Writes memory");
    addText(TXT_CHECKBOX_CAN_TRAP, "Can trap");
    addText(TXT_CHECKBOX_HAS_SIDE_EFFECTS, "Has side effects");
    addText(TXT_CHECKBOX_CLOCKED, "Clocked");
    addText(TXT_CHECKBOX_MEM_DATA, "Memory data");
    addText(TXT_CHECKBOX_MEM_ADDRESS, "Memory address");
    addText(TXT_COLUMN_OPERATION, "operation");
    addText(TXT_COLUMN_OPERAND, "operand");
    addText(TXT_COLUMN_TYPE, "type");
    addText(TXT_COLUMN_VALUE, "value");
    addText(TXT_COLUMN_SEARCH_PATHS, "search paths");
    addText(TXT_COLUMN_MODULES, "modules");
    addText(TXT_COLUMN_OPERATIONS, "operations");
    addText(TXT_COLUMN_PROPERTY, "property");
    addText(TXT_COLUMN_OPERAND_VALUE, "operand value");
    addText(TXT_COLUMN_ELEMENT_WIDTH, "element width");
    addText(TXT_COLUMN_ELEMENT_COUNT, "element count");
    addText(TXT_PROPERTY_DIALOG_TITLE, "Operation properties");
    addText(TXT_INPUT_OPERAND_DIALOG_TITLE, "Input operand properties: id %i");
    addText(TXT_OUTPUT_OPERAND_DIALOG_TITLE, "Output operand properties: id %i");
    addText(TXT_ADD_MODULE_DIALOG_TITLE, "Add module");
    addText(TXT_SIMULATE_DIALOG_TITLE, "Simulate Operation Behavior: %s");
    addText(TXT_OPTIONS_DIALOG_TITLE, "Options");
    addText(TXT_BUILD_RESULT_DIALOG_TITLE, "Build results");
    addText(TXT_USER_MANUAL_TITLE, "User manual");
    addText(TXT_XML_RESULT_DIALOG_TITLE, "Bad modules");
    addText(TXT_ABOUT_DIALOG_TITLE, "About Operation Set Editor");
    addText(TXT_SIMULATION_INFO_DIALOG_TITLE, "Simulation information");
    addText(TXT_MEMORY_DIALOG_TITLE, "Memory");
    addText(TXT_BOX_AFFECTS, "Affects");
    addText(TXT_BOX_AFFECTED_BY, "Affected by");
    addText(TXT_BOX_INPUT_OPERANDS, "Operation inputs");
    addText(TXT_BOX_OUTPUT_OPERANDS, "Operation outputs");
    addText(TXT_BOX_CAN_SWAP, "Can swap");
    addText(TXT_BOX_INPUT_VALUES, "Input values");
    addText(TXT_BOX_OUTPUT_VALUES, "Output values");
    addText(TXT_ERROR_NO_NAME, "No name given to %s.");
    addText(TXT_ERROR_CAN_NOT_MODIFY, "Operation cannot be modified.");
    addText(TXT_ERROR_CAN_NOT_CREATE_MOD, "Module cannot be created.");
    addText(TXT_ERROR_CAN_NOT_CREATE_OP, "Operation cannot be created.");
    addText(TXT_ERROR_NO_EDITOR, "Editor not set");
    addText(TXT_ERROR_OPEN, "Can not open editor %s");
    addText(TXT_ERROR_CAN_NOT_SAVE, "Can not save options");
    addText(TXT_ERROR_NON_EXISTING_OPERATION, "Operation %s does not exist");
    addText(TXT_ERROR_TRIGGER_FAILED, "Result could not be compiled");
    addText(TXT_ERROR_CAN_NOT_REMOVE_OPERATION,
            "Operation %s can not be removed");
    addText(TXT_ERROR_MODULE_EXISTS, "Module %s already exists.");
    addText(TXT_ERROR_OPERATION_EXISTS, "Operation %s already exists.");
    addText(TXT_ERROR_NO_HANDLER, "No handler found for the command event");
    addText(TXT_ERROR_MOD_NAME, "Module name %s is erronous");
    addText(TXT_MSG_BUILD_OK, "Build successful");
    addText(TXT_ABOUT, "Operation Set Editor");
    addText(TXT_MENU_OPTIONS, "&Options");
    addText(TXT_MENU_QUIT, "&Quit");
    addText(TXT_MENU_FILE, "&File");
    addText(TXT_MENU_ADD_OPERATION, "Add &operation");
    addText(TXT_MENU_REMOVE_OPERATION, "R&emove operation");
    addText(TXT_MENU_ADD_MODULE, "Add &module");
    addText(TXT_MENU_MODIFY_PROPERTIES, "Modify &properties");
    addText(TXT_MENU_BUILD, "&Build");
    addText(TXT_MENU_BUILD_ALL, "Build &all");
    addText(TXT_MENU_SIMULATE, "&Simulate");
    addText(TXT_MENU_TOOLS, "&Tools");
    addText(TXT_MENU_ABOUT, "&About...");
    addText(TXT_MENU_USER_MANUAL, "&User manual...");
    addText(TXT_MENU_HELP, "&Help");
    addText(TXT_MENU_REMOVE_MODULE, "&Remove module");
    addText(TXT_MENU_MODIFY_BEHAVIOR, "Modify &behavior");
    addText(TXT_MENU_MEMORY, "Memo&ry");
    addText(TXT_ROW_NAME, "name");
    addText(TXT_ROW_DESCRIPTION, "description");
    addText(TXT_ROW_INPUTS, "inputs");
    addText(TXT_ROW_OUTPUTS, "outputs");
    addText(TXT_ROW_READS_MEMORY, "reads memory");
    addText(TXT_ROW_WRITES_MEMORY, "writes memory");
    addText(TXT_ROW_TRUE, "true");
    addText(TXT_ROW_FALSE, "false");
    addText(TXT_ROW_CAN_TRAP, "can trap");
    addText(TXT_ROW_HAS_SIDE_EFFECTS, "has side effects");
    addText(TXT_ROW_CLOCKED, "clocked");
    addText(TXT_ROW_AFFECTED_BY, "affected by");
    addText(TXT_ROW_AFFECTS, "affects");
    addText(TXT_ROW_INPUT_OPERANDS, "input operands");
    addText(TXT_ROW_OUTPUT_OPERANDS, "output operands");
    addText(TXT_ROW_ID, "id: ");
    addText(TXT_ROW_YES, "yes");
    addText(TXT_ROW_NO, "no");
    addText(TXT_ROW_TYPE, "type");
    addText(TXT_ROW_MEMORY_ADDRESS, "memory address");
    addText(TXT_ROW_CAN_SWAP, "can swap");
    addText(TXT_ROW_MEMORY_DATA, "memory data");
    addText(TXT_ROW_HAS_BEHAVIOR, "has behavior");
    addText(
        TXT_QUESTION_REMOVE_MODULE,
        "Are you sure you want to remove module %s?");
    addText(
        TXT_QUESTION_REMOVE_BEHAVIOR_FILE,
        "Are you sure you want to remove behavior file %s?");
    addText(
        TXT_QUESTION_SAVE_PROPERTIES,
        "Operation properties modified. Save properties?");
    addText(
        TXT_QUESTION_REMOVE_OPERATION,
        "Are you sure you want to remove operation %s?");
    addText(TXT_STATUS_PATH_SELECTED, "Path selected");
    addText(TXT_STATUS_MODULE_SELECTED, "Module selected");
    addText(TXT_STATUS_OPERATION_SELECTED, "Operation selected");
    addText(TXT_STATUS_COMPILING, "Compiling %s...");
    addText(TXT_STATUS_COMPILE_SUCCESS, "Compilation successful. It took %i ms");
    addText(TXT_STATUS_COMPILE_FAILED, "Compilation failed.");
}
References Texts::TextGenerator::addText(), TXT_ABOUT, TXT_ABOUT_DIALOG_TITLE, TXT_ADD_MODULE_DIALOG_TITLE, TXT_BOX_AFFECTED_BY, TXT_BOX_AFFECTS, TXT_BOX_CAN_SWAP, TXT_BOX_INPUT_OPERANDS, TXT_BOX_INPUT_VALUES, TXT_BOX_OUTPUT_OPERANDS, TXT_BOX_OUTPUT_VALUES, TXT_BUILD_RESULT_DIALOG_TITLE, TXT_BUTTON_ADVANCE_LOCK, TXT_BUTTON_BROWSE, TXT_BUTTON_CLOSE, TXT_BUTTON_DELETE, TXT_BUTTON_HIDE_REGISTERS, TXT_BUTTON_MODIFY, TXT_BUTTON_NEW, TXT_BUTTON_OPEN, TXT_BUTTON_RESET, TXT_BUTTON_SAVE, TXT_BUTTON_SHOW_REGISTERS, TXT_BUTTON_TRIGGER, TXT_BUTTON_UNDO, TXT_BUTTON_UPDATE, TXT_CHECKBOX_CAN_TRAP, TXT_CHECKBOX_CLOCKED, TXT_CHECKBOX_HAS_SIDE_EFFECTS, TXT_CHECKBOX_MEM_ADDRESS, TXT_CHECKBOX_MEM_DATA, TXT_CHECKBOX_READS_MEMORY, TXT_CHECKBOX_WRITES_MEMORY, TXT_COLUMN_ELEMENT_COUNT, TXT_COLUMN_ELEMENT_WIDTH, TXT_COLUMN_MODULES, TXT_COLUMN_OPERAND, TXT_COLUMN_OPERAND_VALUE, TXT_COLUMN_OPERATION, TXT_COLUMN_OPERATIONS, TXT_COLUMN_PROPERTY, TXT_COLUMN_SEARCH_PATHS, TXT_COLUMN_TYPE, TXT_COLUMN_VALUE, TXT_ERROR_CAN_NOT_CREATE_MOD, TXT_ERROR_CAN_NOT_CREATE_OP, TXT_ERROR_CAN_NOT_MODIFY, TXT_ERROR_CAN_NOT_REMOVE_OPERATION, TXT_ERROR_CAN_NOT_SAVE, TXT_ERROR_MOD_NAME, TXT_ERROR_MODULE_EXISTS, TXT_ERROR_NO_EDITOR, TXT_ERROR_NO_HANDLER, TXT_ERROR_NO_NAME, TXT_ERROR_NON_EXISTING_OPERATION, TXT_ERROR_OPEN, TXT_ERROR_OPERATION_EXISTS, TXT_ERROR_TRIGGER_FAILED, TXT_INPUT_OPERAND_DIALOG_TITLE, TXT_LABEL_CLOCK, TXT_LABEL_EDITOR, TXT_LABEL_END, TXT_LABEL_FORMAT, TXT_LABEL_HAS_BEHAVIOR, TXT_LABEL_MODE, TXT_LABEL_MODULE_NAME, TXT_LABEL_NO_BEHAVIOR, TXT_LABEL_OPERATION_NAME, TXT_LABEL_PC, TXT_LABEL_RA, TXT_LABEL_READY, TXT_LABEL_START, TXT_LABEL_SYS_CALL_HANDLER, TXT_LABEL_SYS_CALL_NUMBER, TXT_LABEL_UPDATE, TXT_MEMORY_DIALOG_TITLE, TXT_MENU_ABOUT, TXT_MENU_ADD_MODULE, TXT_MENU_ADD_OPERATION, TXT_MENU_BUILD, TXT_MENU_BUILD_ALL, TXT_MENU_FILE, TXT_MENU_HELP, TXT_MENU_MEMORY, TXT_MENU_MODIFY_BEHAVIOR, TXT_MENU_MODIFY_PROPERTIES, TXT_MENU_OPTIONS, TXT_MENU_QUIT, TXT_MENU_REMOVE_MODULE, TXT_MENU_REMOVE_OPERATION, TXT_MENU_SIMULATE, TXT_MENU_TOOLS, TXT_MENU_USER_MANUAL, TXT_MSG_BUILD_OK, TXT_OPTIONS_DIALOG_TITLE, TXT_OUTPUT_OPERAND_DIALOG_TITLE, TXT_PROPERTY_DIALOG_TITLE, TXT_QUESTION_REMOVE_BEHAVIOR_FILE, TXT_QUESTION_REMOVE_MODULE, TXT_QUESTION_REMOVE_OPERATION, TXT_QUESTION_SAVE_PROPERTIES, TXT_ROW_AFFECTED_BY, TXT_ROW_AFFECTS, TXT_ROW_CAN_SWAP, TXT_ROW_CAN_TRAP, TXT_ROW_CLOCKED, TXT_ROW_DESCRIPTION, TXT_ROW_FALSE, TXT_ROW_HAS_BEHAVIOR, TXT_ROW_HAS_SIDE_EFFECTS, TXT_ROW_ID, TXT_ROW_INPUT_OPERANDS, TXT_ROW_INPUTS, TXT_ROW_MEMORY_ADDRESS, TXT_ROW_MEMORY_DATA, TXT_ROW_NAME, TXT_ROW_NO, TXT_ROW_OUTPUT_OPERANDS, TXT_ROW_OUTPUTS, TXT_ROW_READS_MEMORY, TXT_ROW_TRUE, TXT_ROW_TYPE, TXT_ROW_WRITES_MEMORY, TXT_ROW_YES, TXT_SIMULATE_DIALOG_TITLE, TXT_SIMULATION_INFO_DIALOG_TITLE, TXT_STATUS_COMPILE_FAILED, TXT_STATUS_COMPILE_SUCCESS, TXT_STATUS_COMPILING, TXT_STATUS_MODULE_SELECTED, TXT_STATUS_OPERATION_SELECTED, TXT_STATUS_PATH_SELECTED, TXT_USER_MANUAL_TITLE, and TXT_XML_RESULT_DIALOG_TITLE.
Referenced by instance().
~OSEdTextGenerator()
OSEdTextGenerator::~OSEdTextGenerator () private virtual
Destructor.
Definition at line 205 of file OSEdTextGenerator.cc.
{
}
Member Function Documentation
destroy()
void OSEdTextGenerator::destroy () static
Destroys the only instance of text generator.
Definition at line 225 of file OSEdTextGenerator.cc.
{
    if (instance_ != NULL) {
        delete instance_;
        instance_ = NULL;
    }
}
References instance_.
Referenced by OSEd::OnExit().
instance()
OSEdTextGenerator & OSEdTextGenerator::instance () static
Returns an instance of text generator.
Returns
Instance of text generator.
Definition at line 214 of file OSEdTextGenerator.cc.
{
    if (instance_ == NULL) {
        instance_ = new OSEdTextGenerator();
    }
    return *instance_;
}
References instance_, and OSEdTextGenerator().
Referenced by OSEdAddModuleCmd::Do(), OSEdBuildAllCmd::Do(), OSEdBuildCmd::Do(), OSEdModifyBehaviorCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveModuleCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdUserManualCmd::Do(), DropDownMenu::DropDownMenu(), OSEdInfoView::insertOperationPropertyColumns(), OSEdInfoView::moduleView(), OperationPropertyDialog::onAddAffectedBy(), OperationPropertyDialog::onAddAffects(), OSEdMainFrame::onCommandEvent(), OSEdInfoView::onDropDownMenu(), OSEdTreeView::onDropDownMenu(), OSEd::OnInit(), OSEdTreeView::onItemSelected(), AddModuleDialog::onOk(), OperationPropertyDialog::onOpen(), ResultDialog::onOpen(), OSEdOptionsDialog::onSave(), OSEdInfoView::onSelection(), OSEdInfoView::operationPropertyView(), OSEdInfoView::operationView(), OSEdMainFrame::OSEdMainFrame(), OSEdInfoView::pathView(), OperationPropertyDialog::setBehaviorLabel(), AddModuleDialog::setTexts(), InputOperandDialog::setTexts(), MemoryDialog::setTexts(), OperationDAGDialog::setTexts(), OperationPropertyDialog::setTexts(), OSEdAboutDialog::setTexts(), OSEdOptionsDialog::setTexts(), OutputOperandDialog::setTexts(), ResultDialog::setTexts(), SimulateDialog::setTexts(), SimulationInfoDialog::setTexts(), SimulateDialog::showOrHideRegisters(), SimulationInfoDialog::SimulationInfoDialog(), OperationPropertyDialog::updateOperation(), and OSEdInfoView::writeStaticPropertiesOfOperation().
Member Data Documentation
instance_
OSEdTextGenerator * OSEdTextGenerator::instance_ = NULL static private
Static instance of text generator.
Definition at line 231 of file OSEdTextGenerator.hh.
Referenced by destroy(), and instance().
The documentation for this class was generated from the following files:
OSEdTextGenerator.hh
OSEdTextGenerator.cc