OpenASIP: OSEd Class Reference
OSEd Class Reference
#include <OSEd.hh>
Public Member Functions
OSEd ()
virtual ~OSEd ()
virtual bool OnInit ()
virtual int OnExit ()
OSEdMainFrame * mainFrame () const
OSEdOptions * options () const
Private Member Functions
OSEd (const OSEd &)
Copying not allowed.
OSEd & operator= (const OSEd &)
Assignment not allowed.
void createDefaultOptions ()
Private Attributes
OSEdMainFrame * mainFrame_
Main window of the application.
OSEdOptions * options_
Options of the application.
Detailed Description
Main class for OSEd (Operation Set Editor).
Initializes the application.
Definition at line 47 of file OSEd.hh.
Constructor & Destructor Documentation
OSEd() [1/2]
OSEd::OSEd ()
Constructor.
Definition at line 62 of file OSEd.cc.
           : mainFrame_(NULL), options_(NULL) {
}
~OSEd()
OSEd::~OSEd () virtual
Destructor.
Definition at line 68 of file OSEd.cc.
            {
}
OSEd() [2/2]
OSEd::OSEd (const OSEd &) private
Copying not allowed.
Member Function Documentation
createDefaultOptions()
void OSEd::createDefaultOptions () private
Creates the default options and writes them to the file.
Definition at line 163 of file OSEd.cc.
{
    options_->setEditor(OSEdConstants::DEFAULT_EDITOR);
    OSEdOptionsSerializer serializer;
    string confFile =
        Environment::userConfPath(OSEdConstants::CONF_FILE_NAME);
    serializer.setDestinationFile(confFile);
    try {
        serializer.writeState(options_->saveState());
    } catch (const Exception& e) {
        cerr << "Writing options failed: " << e.errorMessage() << endl;
    }
}
References OSEdConstants::CONF_FILE_NAME, OSEdConstants::DEFAULT_EDITOR, Exception::errorMessage(), options_, OSEdOptions::saveState(), OSEdOptionsSerializer::setDestinationFile(), OSEdOptions::setEditor(), Environment::userConfPath(), and OSEdOptionsSerializer::writeState().
Referenced by OnInit().
mainFrame()
OSEdMainFrame * OSEd::mainFrame () const
Returns the main frame of the application.
Returns
The main frame of the application.
Definition at line 145 of file OSEd.cc.
                      {
    return mainFrame_;
}
References mainFrame_.
OnExit()
int OSEd::OnExit () virtual
Deletes the application level dynamic objects not handled by wxWindows.
This function is called when application is about to exit.
Returns
0.
Definition at line 131 of file OSEd.cc.
             {
    OSEdTextGenerator::destroy();
    OperationContainer::destroy();
    delete options_;
    options_ = NULL;
    return 0;
}
References OperationContainer::destroy(), OSEdTextGenerator::destroy(), and options_.
OnInit()
bool OSEd::OnInit () virtual
Initializes the application.
Creates mainframe as well as reads the configure file.
Returns
True.
Definition at line 79 of file OSEd.cc.
             {
    Application::initialize(argc, WxConversion::toCStringArray(argc, argv));
    mainFrame_ = new OSEdMainFrame(_T("Operation Set Editor"),
                                   wxPoint(50, 50), wxSize(900, 500));
    mainFrame_->updateMenuBar();
    options_ = new OSEdOptions();
    OSEdOptionsSerializer serializer;
    string confFile = Environment::confPath(OSEdConstants::CONF_FILE_NAME);
    serializer.setSourceFile(confFile);
    try {
        options_->loadState(serializer.readState());
    } catch (const Exception& e) {
        cerr << "Config file not found, default options will be used." << endl
             << "OseD may use the editor in your $VISUAL"
             << " environmental variable." << endl
             << "If this points to some non-graphical editor, "
             << "please change the editor from settings." << endl;
        createDefaultOptions();
    }
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdTreeView* treeView = mainFrame_->treeView();
    vector<string> results = treeView->constructTree();
    // if some errors occurred while buildin the tree view, error message is
    // shown
    if (results.size() > 0) {
        format fmt = texts.text(OSEdTextGenerator::TXT_XML_RESULT_DIALOG_TITLE);
        ResultDialog result(mainFrame_, results, fmt.str());
        result.ShowModal();
    }
    mainFrame_->Show(true);
    SetTopWindow(mainFrame_);
    return true;
}
References OSEdConstants::CONF_FILE_NAME, Environment::confPath(), OSEdTreeView::constructTree(), createDefaultOptions(), Application::initialize(), OSEdTextGenerator::instance(), OSEdOptions::loadState(), mainFrame_, options_, OSEdOptionsSerializer::readState(), OSEdOptionsSerializer::setSourceFile(), Texts::TextGenerator::text(), WxConversion::toCStringArray(), OSEdMainFrame::treeView(), OSEdTextGenerator::TXT_XML_RESULT_DIALOG_TITLE, and OSEdMainFrame::updateMenuBar().
operator=()
OSEd & OSEd::operator= (const OSEd &) private
Assignment not allowed.
options()
OSEdOptions * OSEd::options () const
Returns the options of the application.
Returns
The options of the application.
Definition at line 155 of file OSEd.cc.
                    {
    return options_;
}
References options_.
Member Data Documentation
mainFrame_
OSEdMainFrame* OSEd::mainFrame_ private
Main window of the application.
Definition at line 67 of file OSEd.hh.
Referenced by mainFrame(), and OnInit().
options_
OSEdOptions* OSEd::options_ private
Options of the application.
Definition at line 69 of file OSEd.hh.
Referenced by createDefaultOptions(), OnExit(), OnInit(), and options().
The documentation for this class was generated from the following files:
OSEd.hh
OSEd.cc