OpenASIP: OSEdOptionsCmd Class Reference
OSEdOptionsCmd Class Reference
#include <OSEdOptionsCmd.hh>
Public Member Functions
OSEdOptionsCmd ()
virtual ~OSEdOptionsCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdOptionsCmd (const OSEdOptionsCmd &)
Copying not allowed.
OSEdOptionsCmd & operator= (const OSEdOptionsCmd &)
Assignment not allowed.
Detailed Description
Command for modifying options.
Definition at line 43 of file OSEdOptionsCmd.hh.
Constructor & Destructor Documentation
OSEdOptionsCmd() [1/2]
OSEdOptionsCmd::OSEdOptionsCmd ()
Constructor.
Definition at line 42 of file OSEdOptionsCmd.cc.
                               :
    GUICommand(OSEdConstants::CMD_NAME_OPTIONS, NULL) {
}
Referenced by create().
~OSEdOptionsCmd()
OSEdOptionsCmd::~OSEdOptionsCmd () virtual
Destructor.
Definition at line 49 of file OSEdOptionsCmd.cc.
{
}
OSEdOptionsCmd() [2/2]
OSEdOptionsCmd::OSEdOptionsCmd (const OSEdOptionsCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdOptionsCmd::create () const virtual
Creates a new command.
Returns
New command.
Implements GUICommand.
Definition at line 68 of file OSEdOptionsCmd.cc.
{
    return new OSEdOptionsCmd();
}
References OSEdOptionsCmd().
Do()
bool OSEdOptionsCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 78 of file OSEdOptionsCmd.cc.
                   {
    OSEdOptionsDialog dialog(parentWindow());
    dialog.ShowModal();
    return true;
}
References GUICommand::parentWindow().
icon()
string OSEdOptionsCmd::icon () const virtual
Return icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 100 of file OSEdOptionsCmd.cc.
{
    return "";
}
id()
int OSEdOptionsCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 58 of file OSEdOptionsCmd.cc.
{
    return OSEdConstants::CMD_OPTIONS;
}
References OSEdConstants::CMD_OPTIONS.
isEnabled()
bool OSEdOptionsCmd::isEnabled () virtual
Return true if command is enabled.
Returns
Always true.
Implements GUICommand.
Definition at line 90 of file OSEdOptionsCmd.cc.
{
    return true;
}
operator=()
OSEdOptionsCmd & OSEdOptionsCmd::operator= (const OSEdOptionsCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdOptionsCmd.hh
OSEdOptionsCmd.cc