OpenASIP: Exception Class Reference
Exception Class Reference
#include <Exception.hh>
Public Member Functions
Exception (std::string filename, int linenum, std::string procname=unknownProcMsg_, std::string errorMessage="")
virtual ~Exception ()
std::string fileName () const
int lineNum () const
std::string procedureName () const
std::string errorMessage () const
std::string errorMessageStack (bool messagesOnly=false) const
void setCause (const Exception &cause)
bool hasCause () const
const Exception & cause () const
Static Public Member Functions
static std::string lastExceptionInfo ()
Returns information of the last thrown exception.
Static Public Attributes
static const std::string unknownProcMsg_ = "(unknown)"
Used when no procedure name is given.
Private Attributes
std::string file_
Name of the file where exception occurred.
int line_
Line number in the file.
std::string proc_
Procedure name.
std::string errorMessage_
Error message.
const Exception * cause_
Exception that caused current exception.
Static Private Attributes
static std::string lastExceptionInfo_ = ""
Information of the last thrown exception for easing the debugging.
Detailed Description
Base class for all exceptions of the system.
It contains information common to all exceptions that identifies the spot in the source code in which the execption was thrown: name of the source file, line number and name of the procedure. Also, it may contain an error message.
Definition at line 54 of file Exception.hh.
Constructor & Destructor Documentation
Exception()
Exception::Exception (std::string filename, int linenum, std::string procname = unknownProcMsg_, std::string errorMessage = "")
The constructor.
Parameters
filename Name of the file in which the exception occurred.
linenum Line number in the file.
procname Name of the procedure.
errorMessage Error message.
Definition at line 57 of file Exception.cc.
                            :
    file_(filename), line_(linenum), proc_(procname),
    errorMessage_(errorMessage), cause_(NULL) {
    lastExceptionInfo_ =
        filename + ", line " + Conversion::toString(linenum) + ". Message: " +
        errorMessage;
}
References errorMessage(), lastExceptionInfo_, and Conversion::toString().
~Exception()
Exception::~Exception () virtual
The destructor. Nothing specific to do in the destructor.
Definition at line 116 of file Exception.cc.
                      {
}
Member Function Documentation
cause()
const Exception & Exception::cause () const
Returns Exception that caused throwing current exception.
Returns
Exception that caused throwing current exception.
Definition at line 95 of file Exception.cc.
                       {
    return *cause_;
}
References cause_.
Referenced by errorMessageStack().
errorMessage()
string Exception::errorMessage () const
Returns the exception's error message.
Definition at line 123 of file Exception.cc.
{
    return errorMessage_;
}
References errorMessage_.
Referenced by DSDBManager::addApplication(), DSDBManager::addArchitecture(), ProGe::NetlistGenerator::addBaseRFToNetlist(), CodeCompressorPlugin::addBitsForDstRegisterField(), CodeCompressorPlugin::addBitsForICField(), HDB::HDBManager::addBooleanColumn(), ExecutionTrace::addBusActivity(), HDB::HDBManager::addBusCostEstimationData(), HDB::HDBManager::addBusEntry(), ExecutionTrace::addBusWriteCount(), ExecutionTrace::addConcurrentRegisterFileAccessCount(), DSDBManager::addConfiguration(), DesignSpaceExplorer::addConfToDSDB(), HDB::HDBManager::addCostEstimationData(), HDB::HDBManager::addCostFunctionPlugin(), HDB::HDBManager::addDataPortsToImplementation(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUCostEstimationData(), HDB::HDBManager::addFUEntry(), HDB::HDBManager::addFUExternalPortsToImplementation(), HDB::HDBManager::addFUImplementation(), ExecutionTrace::addFunctionUnitOperationTriggerCount(), ProGe::NetlistGenerator::addFUToNetlist(), DSDBManager::addImplementation(), ImmediateGenerator::addInsTemplate(), ExecutionTrace::addInstructionExecution(), ExecutionTrace::addInstructionExecutionCount(), CodeSectionCreator::addMove(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), ExecutionTrace::addProcedureAddressRange(), TTAProgram::TPEFProgramFactory::addProcedures(), ProcedureTransferTracker::addProcedureTransfer(), ExecutionTrace::addRegisterAccessCount(), TTAMachine::ExecutionPipeline::addResourceUsage(), HDB::HDBManager::addRFArchitecture(), HDB::HDBManager::addRFCostEstimationData(), HDB::HDBManager::addRFEntry(), HDB::HDBManager::addRFExternalPortsToImplementation(), HDB::HDBManager::addRFImplementation(), HDB::HDBManager::addSocketCostEstimationData(), HDB::HDBManager::addSocketEntry(), ExecutionTrace::addSocketWriteCount(), ImmediateGenerator::addSplitInsTemplate(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), TTAMachine::Bus::adjustSegmentChain(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), DSDBManager::applicationCostEstimatesByConf(), DSDBManager::applicationCount(), DSDBManager::applicationIDs(), DSDBManager::applicationPath(), DSDBManager::archConfigurationIDs(), DSDBManager::architectureId(), DSDBManager::architectureIDs(), DSDBManager::architectureString(), DSDBManager::areaEstimate(), MachineStateBuilder::bindPortsToOperands(), HDB::HDBManager::blockSourceFile(), BridgeEncoding::BridgeEncoding(), SimProgramBuilder::build(), MachineStateBuilder::buildMachineState(), HDB::HDBManager::busCostEstimationData(), HDB::HDBManager::busCostEstimationDataIDs(), HDB::HDBManager::busCostEstimationDataList(), HDB::HDBManager::busEntryIDs(), ExecutionPipelineResource::canAssignDestination(), HDB::HDBManager::canRemoveFUArchitecture(), HDB::HDBManager::canRemoveRFArchitecture(), SimpleBrokerDirector::canTransportImmediate(), ProGe::ProcessorGenerator::checkIULatencies(), TPEF::RawSection::chunk(), Assembler::compile(), TTAMachine::Component::Component(), InstructionDictionary::compress(), DEFAULT_Compressor::compress(), DSDBManager::configuration(), DSDBManager::configurationId(), DSDBManager::configurationIDs(), UniversalMachine::construct(), OSEdTreeView::constructTree(), HDB::HDBManager::containsFUArchitecture(), HDB::HDBManager::containsImplementationFile(), HDB::HDBManager::containsOperation(), HDB::HDBManager::containsRFArchitecture(), ProGe::BlockSourceCopier::copyFiles(), copyImageToTb(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::costEstimationDataIDs(), HDB::HDBManager::costEstimationDataValue(), HDB::HDBManager::costEstimationDataValue(), HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginDataIDs(), HDB::HDBManager::costFunctionPluginIDs(), HDB::HDBManager::createCostFunctionOfFU(), HDB::HDBManager::createCostFunctionOfRF(), OSEd::createDefaultOptions(), HDBEditorMainFrame::createHDB(), HDB::HDBManager::createImplementationOfFU(), DSDBManager::createNew(), HDB::HDBManager::createNew(), LLVMBackend::createPlugin(), DSDBManager::cycleCount(), OperationPimpl::dag(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::delayOfSocket(), OSEdAddOperationCmd::Do(), ProximQuitCmd::Do(), AddFUArchFromADFCmd::Do(), AddFUImplementationCmd::Do(), AddRFImplementationCmd::Do(), HDBEditorModifyCmd::Do(), PasteComponentCmd::Do(), SaveOptionsCmd::Do(), ProcessorImplementationWindow::doSaveIDF(), DSDBManager::DSDBManager(), Encoding::Encoding(), DSDBManager::energyEstimate(), errorMessageStack(), StrictMatchRFEstimator::estimateArea(), StrictMatchFUEstimator::estimateArea(), InterpolatingRFEstimator::estimateEnergy(), StrictMatchRFEstimator::estimateEnergy(), InterpolatingFUEstimator::estimateEnergy(), StrictMatchFUEstimator::estimateEnergy(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICDelayOfPath(), DefaultICDecoderEstimator::estimateICEnergy(), StrictMatchRFEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimatePortReadDelay(), StrictMatchRFEstimator::estimatePortReadDelay(), StrictMatchFUEstimator::estimatePortWriteDelay(), StrictMatchRFEstimator::estimatePortWriteDelay(), CostEstimator::Estimator::estimateSocketToSocketDelayOfPath(), Exception(), ProgCommand::execute(), SettingCommand::execute(), CmdTrigger::execute(), executeInstruction32(), executeInstruction64(), ComponentAdder::explore(), Evaluate::explore(), GrowMachine::explore(), ImplementationSelector::explore(), MinimalOpSet::explore(), RemoveUnconnectedComponents::explore(), ImmediateGenerator::explore(), SimpleICOptimizer::explore(), DataSectionCreator::finalize(), HDB::HDBManager::fuArchitectureID(), HDB::HDBManager::fuArchitectureIDs(), HDB::HDBManager::fuArchitectureIDsByOperationSet(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuCostEstimationData(), HDB::HDBManager::fuCostEstimationDataIDs(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), HDB::HDBManager::fuEntriesByArchitecture(), HDB::HDBManager::fuEntryHasArchitecture(), HDB::HDBManager::fuEntryIDOfImplementation(), HDB::HDBManager::fuEntryIDs(), FUGuardEncoding::FUGuardEncoding(), CostEstimator::Estimator::functionUnitArea(), CostEstimator::Estimator::functionUnitEnergy(), CostEstimator::Estimator::functionUnitMaximumComputationDelay(), ExecutionTrace::functionUnitOperationTriggerCounts(), CostEstimator::Estimator::functionUnitPortReadDelay(), CostEstimator::Estimator::functionUnitPortWriteDelay(), ProGeTestBenchGenerator::generate(), DefaultICDecoderGenerator::generate(), ProgramImageGenerator::generateDataImage(), ProGe::ProGeUI::generateProcessor(), GenerateProcessor::generateProcessor(), GPRGuardEncoding::GPRGuardEncoding(), GuardEncoding::GuardEncoding(), ExecutionTracker::handleEvent(), HDB::HDBManager::hasColumn(), HDB::HDBManager::HDBManager(), TTAMachine::HWOperation::HWOperation(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), ImmediateEncoding::ImmediateEncoding(), DSDBManager::implementationString(), ExecutionTrace::initialize(), SimulatorFrontend::initializeDataMemories(), initializeMachine(), XMLSerializer::initializeParser(), HDBTester::initializeTester(), HDB::HDBManager::insertFileFormats(), ExecutionTrace::instructionExecutions(), SimpleScriptInterpreter::interpret(), StopPoint::isConditionOK(), DSDBManager::isUnschedulable(), GenerateProcessor::listICDecPluginParameters(), llvm::LLVMTCERISCVIntrinsicsLowering::LLVMTCERISCVIntrinsicsLowering(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), loadExplorerPlugin(), HDB::HDBRegistry::loadFromSearchPaths(), AddIUFromHDBDialog::loadHDB(), GenerateProcessorDialog::loadICDecoderGeneratorPlugin(), ProcessorImplementationWindow::loadICDecoderPlugin(), loadInputs(), OperationPropertyLoader::loadModule(), OperationPropertyLoader::loadOperationProperties(), Proxim::loadOptions(), loadPluginParameters(), SimulatorFrontend::loadProgram(), GuardField::loadState(), ImmediateControlField::loadState(), InstructionField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), OperationTriggeredEncoding::loadState(), OperationTriggeredField::loadState(), SlotField::loadState(), SourceField::loadState(), IDF::MachineImplementation::loadState(), IDF::UnitImplementationLocation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::Bridge::loadState(), TTAMachine::Bus::loadState(), TTAMachine::ExecutionPipeline::loadState(), TTAMachine::FunctionUnit::loadState(), TTAMachine::Guard::loadState(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::OperationTriggeredFormat::loadState(), TTAMachine::OperationTriggeredOperand::loadState(), TTAMachine::Port::loadState(), TTAMachine::Socket::loadState(), Operand::loadState(), OperationPimpl::loadState(), OSEdOptions::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::BaseFUPort::loadStateWithoutReferences(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::ControlUnit::loadStateWithoutReferences(), TTAMachine::FUPort::loadStateWithoutReferences(), TTAMachine::ImmediateUnit::loadStateWithoutReferences(), TTAMachine::Port::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), TTAMachine::Segment::loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), DSDBManager::longestPathDelayEstimate(), main(), HDB::HDBManager::modifyCostEstimationData(), HDB::HDBManager::modifyCostFunctionPlugin(), numbersToAscending(), AddFUFromHDBDialog::onAdd(), FUDialog::onAddOperationFromOpset(), GenerateProcessorDialog::onBrowseBEMLoad(), AutoSelectImplementationsDialog::onFind(), BlockImplementationDialog::onHDBSelection(), ProDe::OnInit(), ProcessorImplementationWindow::onLoadIDF(), GCUDialog::onOK(), GenerateProcessorDialog::onOK(), RFDialog::onOK(), CallExplorerPluginWindow::onRun(), MDFDocument::OnSaveDocument(), BusDialog::onUnconditionalGuard(), ValidateMachineDialog::onValidate(), ExecutionTrace::open(), MDFDocument::openADF(), MDFDocument::openCFG(), ImplementationTester::openHdb(), OperationIndex::operationCount(), HDB::HDBManager::OperationImplementationByID(), HDB::HDBManager::OperationImplementationIDs(), HDB::HDBManager::OperationImplementationResourceByID(), HDB::HDBManager::OperationImplementationResourceIDs(), OperationIndex::operationName(), TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand(), ProGe::ICDecoderGeneratorPlugin::parameterDescription(), DSDBManager::paretoSetConnectivityAndCycles(), InlineAsmParser::parse(), SimProgramBuilder::processBidirTerminal(), SimProgramBuilder::processInstruction(), PlatformIntegrator::progeOutputHdlFiles(), readAdf(), TPEF::BinaryReader::readBinary(), XMLSerializer::readFile(), readIdf(), OperationSerializer::readState(), OSEdOptionsSerializer::readState(), ExecutionTrace::registerFileAccessCounts(), CostEstimator::Estimator::registerFileArea(), CostEstimator::Estimator::registerFileEnergy(), CostEstimator::Estimator::registerFileMaximumComputationDelay(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), DSDBManager::removeApplication(), HDB::HDBManager::removeBusEntry(), DSDBManager::removeConfiguration(), HDB::HDBManager::removeCostEstimationData(), HDB::HDBManager::removeCostFunctionPlugin(), HDB::HDBManager::removeFUArchitecture(), HDB::HDBManager::removeFUEntry(), HDB::HDBManager::removeFUImplementation(), HDB::HDBManager::removeRFArchitecture(), HDB::HDBManager::removeRFEntry(), HDB::HDBManager::removeRFImplementation(), HDB::HDBManager::removeSocketEntry(), DataSectionCreator::resolveDataAreaSizesAndLabelAddresses(), LabelManager::resolveExpressionValue(), HDB::HDBManager::rfArchitectureByID(), HDB::HDBManager::rfArchitectureID(), HDB::HDBManager::rfArchitectureIDs(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfCostEstimationData(), HDB::HDBManager::rfCostEstimationDataIDs(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), HDB::HDBManager::rfEntriesByArchitecture(), HDB::HDBManager::rfEntryHasArchitecture(), HDB::HDBManager::rfEntryIDOfImplementation(), HDB::HDBManager::rfEntryIDs(), MachineResourceManager::rFPortOrFUIndexReference(), SQLiteConnection::rowCountInTable(), DesignSpaceExplorer::schedule(), DesignSpaceExplorer::selectComponents(), ComponentImplementationSelector::selectComponentsToConf(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), HDB::HDBManager::setArchitectureForFU(), HDB::HDBManager::setArchitectureForRF(), HDB::HDBManager::setCostFunctionPluginForFU(), HDB::HDBManager::setCostFunctionPluginForRF(), HDBEditorMainFrame::setHDB(), SimpleSimulatorFrontend::setOperationSimulator(), ExecutionTrace::setSimulatedCycleCount(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), OTASimulationController::simulateCycle(), SimulationController::simulateCycle(), ExecutionTrace::simulatedCycleCount(), OperationSimulator::simulateTrigger(), HDB::HDBManager::socketCostEstimationData(), HDB::HDBManager::socketCostEstimationDataIDs(), HDB::HDBManager::socketCostEstimationDataList(), SocketEncoding::SocketEncoding(), HDB::HDBManager::socketEntryIDs(), CodeCompressorPlugin::startNewProgram(), SQLiteConnection::tableExistsInDB(), tandemSimulate(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::ProgramWriter::terminalResource(), TestApplication::TestApplication(), ProGe::TestBenchBlock::TestBenchBlock(), ProximToolbox::testCondition(), ProximToolbox::testExpression(), HDBTester::testFU(), HDBTester::testRF(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), HDB::HDBManager::unsetArchitectureForFU(), HDB::HDBManager::unsetArchitectureForRF(), HDB::HDBManager::unsetCostFunctionPluginForFU(), HDB::HDBManager::unsetCostFunctionPluginForRF(), ProcessorImplementationWindow::updateFUList(), ProcessorImplementationWindow::updateImplementationLists(), OperationPropertyDialog::updateOperation(), ProcessorImplementationWindow::updateRFList(), OperationBuilder::verifyXML(), SQLiteConnection::version(), DSDBManager::writeArchitectureToFile(), TPEF::BinaryWriter::writeBinary(), writeCustomOpMacros(), DSDBManager::writeImplementationToFile(), OperationSerializer::writeState(), OSEdOptionsSerializer::writeState(), ExecutionTrace::~ExecutionTrace(), and SQLiteQueryResult::~SQLiteQueryResult().
errorMessageStack()
string Exception::errorMessageStack (bool messagesOnly = false) const
Returns error message of exception and all error messages of exceptions that caused current exception.
Parameters
messagesOnly if true, only returns error messages, not the exception names and line numbers
Returns
error message of exception and all error messages of exceptions that caused current exception.
Definition at line 138 of file Exception.cc.
{
    string result = messagesOnly ?
        errorMessage() :
        (boost::format("%s:%d '%s'\n") %
         fileName() % lineNum() % errorMessage()).str();
    const Exception* exception = this;
    while (exception->hasCause()) {
        exception = &exception->cause();
        assert(exception != NULL);
        result += messagesOnly ?
            exception->errorMessage() :
            (boost::format("%s:%d '%s'\n") %
             exception->fileName() % exception->lineNum() %
             exception->errorMessage()).str();
    }
    return result;
}
References assert, cause(), errorMessage(), fileName(), hasCause(), and lineNum().
Referenced by BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), DataDependenceGraphBuilder::build(), CycleLookBackSoftwareBypasser::bypass(), LLVMBackend::compile(), ControlDependenceGraph::createControlDependenceEdge(), MoveNode::earliestResultReadCycle(), DesignSpaceExplorer::evaluate(), ConfCommand::execute(), MachCommand::execute(), BBSchedulerController::executeDDGPass(), ADFCombiner::explore(), Evaluate::explore(), GrowMachine::explore(), MinimalOpSet::explore(), VectorLSGenerator::explore(), SimpleICOptimizer::explore(), ControlDependenceGraphPass::handleControlDependenceGraph(), BusBroker::isAvailable(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), Operand::loadState(), main(), ProgramDependenceGraph::ProgramDependenceGraph(), ProgramDependenceGraph::removeGuardedJump(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperation(), ExecutionPipelineBroker::setupResourceLinks(), InputPSocketBroker::setupResourceLinks(), ITemplateBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), and OutputPSocketBroker::setupResourceLinks().
fileName()
std::string Exception::fileName () const
Referenced by DataDependenceGraphBuilder::build(), AddFUImplementationCmd::Do(), AddRFImplementationCmd::Do(), HDBEditorModifyCmd::Do(), errorMessageStack(), InterpolatingRFEstimator::estimateArea(), ComponentAdder::explore(), ImplementationSelector::explore(), GenerateProcessor::generateProcessor(), main(), SimProgramBuilder::processInstruction(), SimpleSimulatorFrontend::setOperationSimulator(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), and SimpleSimulatorFrontend::SimpleSimulatorFrontend().
hasCause()
bool Exception::hasCause () const
Returns true if cause is set for current exception.
Returns
True if cause is set for current exception.
Definition at line 85 of file Exception.cc.
{
    return (cause_ != NULL);
}
References cause_.
Referenced by errorMessageStack().
lastExceptionInfo()
std::string Exception::lastExceptionInfo () static
Returns information of the last thrown exception.
Returns information of the last exception thrown.
This is useful in debugging. It's used in Application.hh's unexpected exception handler.
Returns
A string describing the last thrown exception.
Definition at line 108 of file Exception.cc.
{
    return lastExceptionInfo_;
}
References lastExceptionInfo_.
Referenced by Application::unexpectedExceptionHandler().
lineNum()
int Exception::lineNum () const
Referenced by DataDependenceGraphBuilder::build(), AddFUImplementationCmd::Do(), AddRFImplementationCmd::Do(), HDBEditorModifyCmd::Do(), errorMessageStack(), InterpolatingRFEstimator::estimateArea(), ComponentAdder::explore(), ImplementationSelector::explore(), GenerateProcessor::generateProcessor(), main(), SimProgramBuilder::processInstruction(), CompileError::setCodeFileLineNumber(), SimpleSimulatorFrontend::setOperationSimulator(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), and SimpleSimulatorFrontend::SimpleSimulatorFrontend().
procedureName()
std::string Exception::procedureName () const
Referenced by GenerateProcessor::generateProcessor(), main(), SimProgramBuilder::processInstruction(), SimpleSimulatorFrontend::setOperationSimulator(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), SimpleSimulatorFrontend::SimpleSimulatorFrontend(), and TPEF::BinaryWriter::writeBinary().
setCause()
void Exception::setCause (const Exception & aCause)
Sets cause of exception.
Parameters
aCause Exception that resulted current exception.
Definition at line 75 of file Exception.cc.
{
    cause_ = new Exception(aCause);
}
References cause_.
Referenced by CodeSectionCreator::addMove(), TTAProgram::TPEFProgramFactory::addProcedures(), BUMoveNodeSelector::BUMoveNodeSelector(), TTAProgram::TPEFProgramFactory::createLabels(), LLVMBackend::createPlugin(), TTAProgram::TPEFProgramFactory::createTerminal(), CriticalPathBBMoveNodeSelector::CriticalPathBBMoveNodeSelector(), TPEF::BinaryStream::endOfFile(), CodeSectionCreator::finalize(), DataSectionCreator::finalize(), OperationBehaviorLoader::importBehavior(), XMLSerializer::initializeParser(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadProgram(), Operand::loadState(), OperationPimpl::loadState(), main(), TPEF::BinaryReader::readBinary(), TPEF::BinaryStream::readByte(), TPEF::BinaryStream::readByteBlock(), TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readHalfWordBlock(), TPEF::BinaryStream::readPosition(), OperationSerializer::readState(), TPEF::BinaryStream::readWord(), TPEF::BinaryStream::readWordBlock(), DataSectionCreator::resolveDataAreaSizesAndLabelAddresses(), LabelManager::resolveExpressionValue(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), MachineResourceManager::rFPortOrFUIndexReference(), DesignSpaceExplorer::schedule(), ComponentImplementationSelector::selectComponentsToConf(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), TPEF::BinaryStream::setReadPosition(), TPEF::BinaryStream::setWritePosition(), TPEF::BinaryStream::sizeOfFile(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::ProgramWriter::terminalResource(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), TPEF::BinaryStream::writeByte(), TPEF::BinaryStream::writeByteBlock(), TPEF::BinaryStream::writeHalfWord(), TPEF::BinaryStream::writeHalfWordBlock(), TPEF::BinaryStream::writePosition(), OperationSerializer::writeState(), TPEF::BinaryStream::writeWord(), and TPEF::BinaryStream::writeWordBlock().
Member Data Documentation
cause_
const Exception* Exception::cause_ private
Exception that caused current exception.
Definition at line 91 of file Exception.hh.
Referenced by cause(), hasCause(), and setCause().
errorMessage_
std::string Exception::errorMessage_ private
Error message.
Definition at line 89 of file Exception.hh.
Referenced by errorMessage().
file_
std::string Exception::file_ private
Name of the file where exception occurred.
Definition at line 83 of file Exception.hh.
lastExceptionInfo_
std::string Exception::lastExceptionInfo_ = "" static private
Information of the last thrown exception for easing the debugging.
Definition at line 81 of file Exception.hh.
Referenced by Exception(), and lastExceptionInfo().
line_
int Exception::line_ private
Line number in the file.
Definition at line 85 of file Exception.hh.
proc_
std::string Exception::proc_ private
Procedure name.
Definition at line 87 of file Exception.hh.
unknownProcMsg_
const string Exception::unknownProcMsg_ = "(unknown)" static
Used when no procedure name is given.
Definition at line 70 of file Exception.hh.
The documentation for this class was generated from the following files:
Exception.hh
Exception.cc