OpenASIP: EntryKeyDataFunctionUnit Class Reference
EntryKeyDataFunctionUnit Class Reference
#include <EntryKeyData.hh>
Public Member Functions
EntryKeyDataFunctionUnit ()
EntryKeyDataFunctionUnit (const TTAMachine::FunctionUnit *fieldData)
virtual ~EntryKeyDataFunctionUnit ()
EntryKeyData * copy () const
bool isEqual (const EntryKeyData *fieldData) const
bool isGreater (const EntryKeyData *fieldData) const
bool isSmaller (const EntryKeyData *fieldData) const
double coefficient (const EntryKeyData *data1, const EntryKeyData *data2) const
std::string toString () const
Public Member Functions inherited from EntryKeyData
EntryKeyData ()
virtual ~EntryKeyData ()
Private Member Functions
EntryKeyDataFunctionUnit (const EntryKeyDataFunctionUnit &)
Copying not allowed.
EntryKeyDataFunctionUnit & operator= (const EntryKeyDataFunctionUnit &)
Assignment not allowed.
Private Attributes
const TTAMachine::FunctionUnit * data_
FunctionUnit* data.
Detailed Description
Implementation for FunctionUnit type of data.
Definition at line 193 of file EntryKeyData.hh.
Constructor & Destructor Documentation
EntryKeyDataFunctionUnit() [1/3]
EntryKeyDataFunctionUnit::EntryKeyDataFunctionUnit ()
Default constructor.
Definition at line 602 of file EntryKeyData.cc.
                                                   : data_() {
}
Referenced by copy().
EntryKeyDataFunctionUnit() [2/3]
EntryKeyDataFunctionUnit::EntryKeyDataFunctionUnit (const TTAMachine::FunctionUnit * fieldData)
Constructor.
Parameters
fieldData A set of parameters.
Definition at line 610 of file EntryKeyData.cc.
                                   : data_(fieldData) {
}
~EntryKeyDataFunctionUnit()
EntryKeyDataFunctionUnit::~EntryKeyDataFunctionUnit () virtual
Destructor.
Definition at line 617 of file EntryKeyData.cc.
{
}
EntryKeyDataFunctionUnit() [3/3]
EntryKeyDataFunctionUnit::EntryKeyDataFunctionUnit (const EntryKeyDataFunctionUnit &) private
Copying not allowed.
Member Function Documentation
coefficient()
double EntryKeyDataFunctionUnit::coefficient (const EntryKeyData * data1, const EntryKeyData * data2) const virtual
Cannot be called for EntryKeyDataFunctionUnit.
FunctionUnits cannot be compared with greater of smaller and no coefficient can be counted.
Parameters
data1 Nothing.
data2 Nothing.
Returns
Nothing
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 696 of file EntryKeyData.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "EntryKeyDataFunctionUnit::coefficient");
    return 0.0; // stupid return statement to keep compiler quiet
}
copy()
EntryKeyData * EntryKeyDataFunctionUnit::copy () const virtual
Copies the set of parameters.
Client is responsible of deallocating the memory reserved for the returned object.
Returns
A copy of the parameter set.
Implements EntryKeyData.
Definition at line 629 of file EntryKeyData.cc.
{
    return new EntryKeyDataFunctionUnit(data_);
}
References data_, and EntryKeyDataFunctionUnit().
isEqual()
bool EntryKeyDataFunctionUnit::isEqual (const EntryKeyData * fieldData) const virtual
Checks if two FunctionUnits are equal
Cannot compare to other data types.
Parameters
fieldData FunctionUnit pointer.
Returns
True if two FunctionUnits are equal.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 643 of file EntryKeyData.cc.
{
    EntryKeyDataFunctionUnit* data = dynamic_cast<EntryKeyDataFunctionUnit*>(
        const_cast<EntryKeyData*>(fieldData));
    if (data == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataFunctionUnit::isEqual");
    }
    return data_->isArchitectureEqual(data->data_, false);
}
References data_, and TTAMachine::FunctionUnit::isArchitectureEqual().
isGreater()
bool EntryKeyDataFunctionUnit::isGreater (const EntryKeyData * fieldData) const virtual
Checks if another EntryKeyDataFunctionUnit is greater.
Cannot compare to other data types. Cannot say which is greater in case of FunctionUnits and false is returned always.
Parameters
fieldData FunctionUnit*.
Returns
Always false.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 665 of file EntryKeyData.cc.
{
    return false;
}
isSmaller()
bool EntryKeyDataFunctionUnit::isSmaller (const EntryKeyData * fieldData) const virtual
Checks if another EntryKeyDataFunctionUnit is smaller.
Cannot compare to other data types. Cannot say which is smaller in case of FunctionUnits and true is returned always.
Parameters
fieldData FunctionUnit*.
Returns
Always true.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 680 of file EntryKeyData.cc.
{
    return true;
}
operator=()
EntryKeyDataFunctionUnit & EntryKeyDataFunctionUnit::operator= (const EntryKeyDataFunctionUnit &) private
Assignment not allowed.
toString()
std::string EntryKeyDataFunctionUnit::toString () const virtual
Converts the FunctionUnit name and operations into a string.
Returns
FunctionUnit name and operations as a string.
Implements EntryKeyData.
Definition at line 709 of file EntryKeyData.cc.
{
    string result = "";
    result += data_->name();
    result += ":";
    for (int i = 0; i < data_->operationCount(); i++) {
        result += data_->operation(i)->name();
        if ((i + 1) < data_->operationCount()) {
            result += "_";
        }
    }
    return result;
}
References data_, TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), and TTAMachine::FunctionUnit::operationCount().
Member Data Documentation
data_
const TTAMachine::FunctionUnit* EntryKeyDataFunctionUnit::data_ private
FunctionUnit* data.
Definition at line 209 of file EntryKeyData.hh.
Referenced by copy(), isEqual(), and toString().
The documentation for this class was generated from the following files:
EntryKeyData.hh
EntryKeyData.cc