OpenASIP: HDLGenerator::Register Class Reference
HDLGenerator::Register Class Reference
#include <HDLRegister.hh>
Public Member Functions
Register (std::string name, int width, WireType wt, ResetOption rst=ResetOption::Mandatory)
Register (std::string name, int width=1, ResetOption rst=ResetOption::Mandatory)
Register (std::string name, std::string width, ResetOption rst=ResetOption::Mandatory)
Width width () noexcept
std::string name ()
Register & setResetValue (BinaryLiteral &&rhs)
void reset (std::ostream &stream, Language lang, int ident)
void declare (std::ostream &stream, Language lang, int ident)
ResetOption resetOption () const noexcept
Private Attributes
std::string name_
std::string strWidth_
int width_
WireType wt_
ResetOption rst_
BinaryLiteral literal_
Detailed Description
Sync signal/sync reg.
Definition at line 51 of file HDLRegister.hh.
Constructor & Destructor Documentation
Register() [1/3]
HDLGenerator::Register::Register (std::string name, int width, WireType wt, ResetOption rst = ResetOption::Mandatory) inline
Definition at line 53 of file HDLRegister.hh.
            : name_(name), strWidth_(), width_(width), wt_(wt),
              rst_(rst), literal_("") {}
Register() [2/3]
HDLGenerator::Register::Register (std::string name, int width = 1, ResetOption rst = ResetOption::Mandatory) inline
Definition at line 57 of file HDLRegister.hh.
            : name_(name), strWidth_(), width_(width),
              wt_(WireType::Auto), rst_(rst), literal_("") {}
Register() [3/3]
HDLGenerator::Register::Register (std::string name, std::string width, ResetOption rst = ResetOption::Mandatory) inline
Definition at line 61 of file HDLRegister.hh.
            : name_(name), strWidth_(width), width_(-1),
              wt_(WireType::Auto), rst_(rst), literal_("") {}
Member Function Documentation
declare()
void HDLGenerator::Register::declare (std::ostream & stream, Language lang, int ident) inline
Definition at line 100 of file HDLRegister.hh.
{
            if (lang == Language::VHDL) {
                stream << StringTools::indent(ident) << "signal "
                       << name() << " : ";
                if (width_ < 0 || width_ > 1 || wt_ == WireType::Vector) {
                    if (strWidth_.empty()) {
                        stream << "std_logic_vector("
                               << std::to_string(width_ - 1)
                               << " downto 0);\n";
                    } else {
                        stream << "std_logic_vector(" << strWidth_
                               << "-1 downto 0);\n";
                    }
                } else {
                    stream << "std_logic;\n";
                }
            } else if (lang == Language::Verilog) {
                stream << StringTools::indent(ident) << "reg ";
                if (width_ < 0 || width_ > 1) {
                    if (strWidth_.empty()) {
                        stream << "[" << std::to_string(width_ - 1) << ":0] ";
                    } else {
                        stream << "[" << strWidth_ << "-1:0] ";
                    }
                }
                stream << name() << ";\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References StringTools::indent(), name(), strWidth_, HDLGenerator::Vector, HDLGenerator::Verilog, HDLGenerator::VHDL, width_, and wt_.
name()
std::string HDLGenerator::Register::name () inline
Definition at line 68 of file HDLRegister.hh.
{ return name_; }
References name_.
Referenced by declare(), and reset().
reset()
void HDLGenerator::Register::reset (std::ostream & stream, Language lang, int ident) inline
Definition at line 75 of file HDLRegister.hh.
{
            stream << StringTools::indent(ident) << name() << " <= ";
            if (lang == Language::VHDL) {
                if (literal_.name().empty()) {
                    if (width_ == 1 && wt_ != WireType::Vector) {
                        stream << "'0';\n";
                    } else {
                        stream << "(others => '0');\n";
                    }
                } else {
                    literal_.hdl(stream, lang);
                    stream << ";\n";
                }
            } else if (lang == Language::Verilog) {
                if (literal_.name().empty()) {
                    stream << "0;\n";
                } else {
                    literal_.hdl(stream, lang);
                    stream << ";\n";
                }
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References HDLGenerator::LHSValue::hdl(), StringTools::indent(), literal_, name(), HDLGenerator::BinaryLiteral::name(), HDLGenerator::Vector, HDLGenerator::Verilog, HDLGenerator::VHDL, width_, and wt_.
Referenced by HDLGenerator::Synchronous::hdl(), and HDLGenerator::Synchronous::vhdlReset().
resetOption()
ResetOption HDLGenerator::Register::resetOption () const inline noexcept
Definition at line 131 of file HDLRegister.hh.
{ return rst_; }
References rst_.
Referenced by HDLGenerator::Synchronous::hdl(), and HDLGenerator::Synchronous::vhdlReset().
setResetValue()
Register & HDLGenerator::Register::setResetValue (BinaryLiteral && rhs) inline
Definition at line 70 of file HDLRegister.hh.
{
            literal_ = rhs;
            return *this;
        }
References literal_.
width()
Width HDLGenerator::Register::width () inline noexcept
Definition at line 66 of file HDLRegister.hh.
{ return {strWidth_, width_}; }
References strWidth_, and width_.
Member Data Documentation
literal_
BinaryLiteral HDLGenerator::Register::literal_ private
Definition at line 139 of file HDLRegister.hh.
Referenced by reset(), and setResetValue().
name_
std::string HDLGenerator::Register::name_ private
Definition at line 134 of file HDLRegister.hh.
Referenced by name().
rst_
ResetOption HDLGenerator::Register::rst_ private
Definition at line 138 of file HDLRegister.hh.
Referenced by resetOption().
strWidth_
std::string HDLGenerator::Register::strWidth_ private
Definition at line 135 of file HDLRegister.hh.
Referenced by declare(), and width().
width_
int HDLGenerator::Register::width_ private
Definition at line 136 of file HDLRegister.hh.
Referenced by declare(), reset(), and width().
wt_
WireType HDLGenerator::Register::wt_ private
Definition at line 137 of file HDLRegister.hh.
Referenced by declare(), and reset().
The documentation for this class was generated from the following file:
HDLRegister.hh