OpenASIP: SQLiteQueryResult Class Reference
SQLiteQueryResult Class Reference
#include <SQLiteQueryResult.hh>
Public Member Functions
SQLiteQueryResult (sqlite3_stmt *statement, SQLiteConnection *connection, bool init=true)
virtual ~SQLiteQueryResult ()
virtual int columns () const
virtual std::string columnName (std::size_t columnIndex) const
virtual const DataObject & data (std::size_t columnIndex) const
virtual const DataObject & data (const std::string &name) const
virtual bool hasNext ()
virtual bool next ()
virtual void bindInt (unsigned int position, int value)
virtual void bindString (unsigned int position, const std::string &value)
virtual void reset ()
Public Member Functions inherited from RelationalDBQueryResult
virtual ~RelationalDBQueryResult ()
virtual int column (const std::string &name) const
Private Attributes
sqlite3_stmt * statement_
the compiled SQLite statement handle
SQLiteConnection * connection_
sqlite connection handle
std::vector< std::string > columnNames_
column names
std::vector< DataObject > currentData_
data of the current row
std::vector< DataObject > nextData_
data of the next row
bool dataInitialized_
has next() been called for this query
Additional Inherited Members
Static Public Attributes inherited from RelationalDBQueryResult
static const int UNKNOWN_INDEX = -1
Detailed Description
Implementation of RelationalDBQueryResult interface for SQLite.
Definition at line 50 of file SQLiteQueryResult.hh.
Constructor & Destructor Documentation
SQLiteQueryResult()
SQLiteQueryResult::SQLiteQueryResult (sqlite3_stmt * statement, SQLiteConnection * connection, bool init = true)
Constructor.
Parameters
virtualMachine Compiled SQLite virtual machine for the query.
Definition at line 49 of file SQLiteQueryResult.cc.
               :
    statement_(statement),
    connection_(connection),
    dataInitialized_(init) {
    // initialize columnNames_ and nextData_
    if (init) {
        next();
    }
}
References next().
~SQLiteQueryResult()
SQLiteQueryResult::~SQLiteQueryResult () virtual
Destructor.
SQLite virtual machine is freed.
Definition at line 69 of file SQLiteQueryResult.cc.
{
    try {
        connection_->finalizeQuery(statement_);
    } catch (const RelationalDBException& e) {
        Application::writeToErrorLog(
            __FILE__, __LINE__, "~SQLiteQueryResult()", e.errorMessage());
    }
}
References connection_, Exception::errorMessage(), SQLiteConnection::finalizeQuery(), statement_, and Application::writeToErrorLog().
Member Function Documentation
bindInt()
void SQLiteQueryResult::bindInt (unsigned int position, int value) virtual
Binds int to sqlite statement at given position (1->)
Reimplemented from RelationalDBQueryResult.
Definition at line 215 of file SQLiteQueryResult.cc.
{
    connection_->throwIfSQLiteError(sqlite3_bind_int(statement_, position, value));
}
References connection_, statement_, and SQLiteConnection::throwIfSQLiteError().
bindString()
void SQLiteQueryResult::bindString (unsigned int position, const std::string & value) virtual
Binds string to sqlite statement at given position (1->)
Reimplemented from RelationalDBQueryResult.
Definition at line 223 of file SQLiteQueryResult.cc.
{
    connection_->throwIfSQLiteError(sqlite3_bind_text(statement_, position, value.c_str(),
                -1, NULL));
}
References connection_, statement_, and SQLiteConnection::throwIfSQLiteError().
columnName()
std::string SQLiteQueryResult::columnName (std::size_t columnIndex) const virtual
Returns the name (title) of a column in the result set.
Parameters
columnIndex Index of the column of which title interested.
Returns
Title. Empty string if unknown (if not supported by the driver or index out of bounds).
Reimplemented from RelationalDBQueryResult.
Definition at line 98 of file SQLiteQueryResult.cc.
{
    if (columnIndex >= columnNames_.size()) {
        return "";
    }
    return columnNames_[columnIndex];
}
References columnNames_.
columns()
int SQLiteQueryResult::columns () const virtual
Returns the number of columns in the result set.
Returns
Number of columns, UNKNOWN_INDEX if unknown (if not supported by the driver).
Reimplemented from RelationalDBQueryResult.
Definition at line 86 of file SQLiteQueryResult.cc.
{
    return columnNames_.size();
}
References columnNames_.
data() [1/2]
const DataObject & SQLiteQueryResult::data (const std::string & name) const virtual
Returns the data of a column in the current row in the result set.
This implementation is just to silence Intel compiler's warnings about "partial implementation" of data() (because it's overriden function).
Parameters
name Name of the column of which data to return.
Returns
The data. Returns NullDataObject if the column cannot be found. Also returns NullDataObject in case the feature is not supported by the database implementation.
Reimplemented from RelationalDBQueryResult.
Definition at line 135 of file SQLiteQueryResult.cc.
{
    return RelationalDBQueryResult::data(name);
}
References RelationalDBQueryResult::data().
data() [2/2]
const DataObject & SQLiteQueryResult::data (std::size_t columnIndex) const virtual
Returns the data of a column in the current row in the result set.
Parameters
columnIndex Index of the column of which data to return.
Returns
The data. Returns NullDataObject if the index is out of bounds.
Implements RelationalDBQueryResult.
Definition at line 114 of file SQLiteQueryResult.cc.
{
    if (currentData_.size() == 0 || columnIndex >= currentData_.size()) {
        return NullDataObject::instance();
    }
    return currentData_.at(columnIndex);
}
References currentData_, and NullDataObject::instance().
Referenced by next().
hasNext()
bool SQLiteQueryResult::hasNext () virtual
Queries if the result set contains more rows.
Returns
True if there are more rows that can be accessed with next().
Implements RelationalDBQueryResult.
Definition at line 146 of file SQLiteQueryResult.cc.
{
    if (!dataInitialized_) {
        next();
    }
    return nextData_.size() > 0;
}
References dataInitialized_, next(), and nextData_.
Referenced by next().
next()
bool SQLiteQueryResult::next () virtual
Advances the row cursor to next row in the result set.
In case the current row is the last row this method does nothing but returns false.
Returns
True if there are still more rows to fetch.
Implements RelationalDBQueryResult.
Definition at line 162 of file SQLiteQueryResult.cc.
{
    dataInitialized_ = true;
    if (currentData_.size() > 0 && !hasNext()) {
        return false;
    }
    std::vector<std::string> columnNames;
    assert(statement_ != NULL);
    int columnCount = 0;
    int dataCount = 0;
    int result = sqlite3_step(statement_);
    columnCount = sqlite3_column_count(statement_);
    for (int i = 0; i < columnCount; i++) {
        columnNames.push_back(sqlite3_column_name(statement_, i));
    }
    currentData_ = nextData_;
    if (result == SQLITE_ROW) {
        nextData_.clear();
        dataCount = sqlite3_data_count(statement_);
        for (int i = 0; i < dataCount; i++) {
            char* columnText = (char*)sqlite3_column_text(statement_, i);
            DataObject data;
            if (columnText == NULL) {
                data.setNull();
            } else {
                data.setString(columnText);
            }
            nextData_.push_back(data);
        }
    } else if (result == SQLITE_DONE) {
        nextData_.clear();
    } else {
        // error occured
        nextData_.clear();
        return false;
    }
    // check if it's the initialization call when one should save column
    // names and column count
    if (columnNames_.size() == 0 && columnNames.size() != 0) {
        columnNames_ = columnNames;
    }
    return nextData_.size() > 0;
}
References assert, columnNames_, currentData_, data(), dataInitialized_, hasNext(), nextData_, DataObject::setNull(), DataObject::setString(), and statement_.
Referenced by hasNext(), and SQLiteQueryResult().
reset()
void SQLiteQueryResult::reset () virtual
Resets compiled sqlite statement for new bindings and execution.
Reimplemented from RelationalDBQueryResult.
Definition at line 232 of file SQLiteQueryResult.cc.
{
    connection_->throwIfSQLiteError(sqlite3_reset(statement_));
    // reset doesn't clear bindings
    //connection_->throwIfSQLiteError(sqlite3_clear_bindings(statement_));
    columnNames_.clear();
    currentData_.clear();
    nextData_.clear();
    dataInitialized_ = false;
}
References columnNames_, connection_, currentData_, dataInitialized_, nextData_, statement_, and SQLiteConnection::throwIfSQLiteError().
Member Data Documentation
columnNames_
std::vector<std::string> SQLiteQueryResult::columnNames_ private
column names
Definition at line 74 of file SQLiteQueryResult.hh.
Referenced by columnName(), columns(), next(), and reset().
connection_
SQLiteConnection* SQLiteQueryResult::connection_ private
sqlite connection handle
Definition at line 72 of file SQLiteQueryResult.hh.
Referenced by bindInt(), bindString(), reset(), and ~SQLiteQueryResult().
currentData_
std::vector<DataObject> SQLiteQueryResult::currentData_ private
data of the current row
Definition at line 76 of file SQLiteQueryResult.hh.
Referenced by data(), next(), and reset().
dataInitialized_
bool SQLiteQueryResult::dataInitialized_ private
has next() been called for this query
Definition at line 80 of file SQLiteQueryResult.hh.
Referenced by hasNext(), next(), and reset().
nextData_
std::vector<DataObject> SQLiteQueryResult::nextData_ private
data of the next row
Definition at line 78 of file SQLiteQueryResult.hh.
Referenced by hasNext(), next(), and reset().
statement_
sqlite3_stmt* SQLiteQueryResult::statement_ private
the compiled SQLite statement handle
Definition at line 70 of file SQLiteQueryResult.hh.
Referenced by bindInt(), bindString(), next(), reset(), and ~SQLiteQueryResult().
The documentation for this class was generated from the following files:
SQLiteQueryResult.hh
SQLiteQueryResult.cc