OpenASIP: GhdlSimulator Class Reference
GhdlSimulator Class Reference
#include <GhdlSimulator.hh>
Public Member Functions
GhdlSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
virtual ~GhdlSimulator ()
virtual bool compile (std::vector< std::string > &errors)
virtual bool simulate (std::vector< std::string > &errors)
Public Member Functions inherited from ImplementationSimulator
ImplementationSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
virtual ~ImplementationSimulator ()
Private Member Functions
bool importFile (std::string file, std::vector< std::string > &errors)
bool compileDesign (std::vector< std::string > &errors)
Additional Inherited Members
Protected Member Functions inherited from ImplementationSimulator
virtual std::string createWorkDir ()
void setWorkDir (std::string dir)
std::string workDir () const
std::string tbDirectory () const
std::string tbFile () const
int hdlFileCount () const
std::string file (int index) const
bool verbose ()
void parseErrorMessages (std::vector< std::string > &inputMsg, std::vector< std::string > &errors)
Detailed Description
Definition at line 40 of file GhdlSimulator.hh.
Constructor & Destructor Documentation
GhdlSimulator()
GhdlSimulator::GhdlSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
Definition at line 44 of file GhdlSimulator.cc.
                    :
    ImplementationSimulator(tbFile, hdlFiles, verbose, leaveDirty) {
}
~GhdlSimulator()
GhdlSimulator::~GhdlSimulator () virtual
Definition at line 52 of file GhdlSimulator.cc.
{
}
Member Function Documentation
compile()
bool GhdlSimulator::compile (std::vector< std::string > & errors) virtual
Implements ImplementationSimulator.
Definition at line 55 of file GhdlSimulator.cc.
{
    string workDir = createWorkDir();
    if (workDir.empty()) {
        errors.push_back("Couldn't create work dir");
        return false;
    }
    string baseDir = tbDirectory();
    if (!FileSystem::changeWorkingDir(baseDir)) {
        errors.push_back("Couldn't change directory to " + baseDir);
        return false;
    }
    for (int i = 0; i < hdlFileCount(); i++) {
        if (!importFile(file(i), errors)) {
            return false;
        } else {
            errors.clear();
        }
    }
    if (!importFile(tbFile(), errors)) {
        return false;
    }
    errors.clear();
    return compileDesign(errors);
}
References FileSystem::changeWorkingDir(), compileDesign(), ImplementationSimulator::createWorkDir(), ImplementationSimulator::file(), ImplementationSimulator::hdlFileCount(), importFile(), ImplementationSimulator::tbDirectory(), ImplementationSimulator::tbFile(), and ImplementationSimulator::workDir().
compileDesign()
bool GhdlSimulator::compileDesign (std::vector< std::string > & errors) private
Definition at line 120 of file GhdlSimulator.cc.
{
    string command = "ghdl  -m -Wno-hide --std=08 --ieee=synopsys --workdir="
        + workDir() + " testbench 2>&1";
    if (verbose()) {
        // TODO: get output stream
        std::cout << command << std::endl;
    }
    int rv = Application::runShellCommandAndGetOutput(command, errors);
    return rv == 0;
}
References Application::runShellCommandAndGetOutput(), ImplementationSimulator::verbose(), and ImplementationSimulator::workDir().
Referenced by compile().
importFile()
bool GhdlSimulator::importFile (std::string file, std::vector< std::string > & errors) private
Definition at line 108 of file GhdlSimulator.cc.
{
    string command = "ghdl  -i --std=08 --ieee=synopsys --workdir="
        + workDir() + " " + file + " 2>&1";
    if (verbose()) {
        // TODO: get output stream
        std::cout << command << std::endl;
    }
    int rv = Application::runShellCommandAndGetOutput(command, errors);
    return rv == 0;
}
References ImplementationSimulator::file(), Application::runShellCommandAndGetOutput(), ImplementationSimulator::verbose(), and ImplementationSimulator::workDir().
Referenced by compile().
simulate()
bool GhdlSimulator::simulate (std::vector< std::string > & errors) virtual
Implements ImplementationSimulator.
Definition at line 80 of file GhdlSimulator.cc.
{
    errors.clear();
    string baseDir = tbDirectory();
    if (!FileSystem::changeWorkingDir(baseDir)) {
        errors.push_back("Couldn't change directory to " + baseDir);
        return false;
    }
    string command;
    if (FileSystem::fileExists("testbench")) {
        command = "./testbench 2>&1";
    } else {
        // In the latest GHDL no executable is produces, thus the simulation
        // command is different.
        command = string("ghdl -r --std=08 --ieee=synopsys --workdir=") + workDir()
            + " testbench  2>&1";
    }
    if (verbose()) {
        std::cout << command << std::endl;
    }
    vector<string> messages;
    int rv = Application::runShellCommandAndGetOutput(command, messages);
    // call parse
    parseErrorMessages(messages, errors);
    return rv == 0 && errors.size() == 0;
}
References FileSystem::changeWorkingDir(), FileSystem::fileExists(), ImplementationSimulator::parseErrorMessages(), Application::runShellCommandAndGetOutput(), ImplementationSimulator::tbDirectory(), ImplementationSimulator::verbose(), and ImplementationSimulator::workDir().
The documentation for this class was generated from the following files:
GhdlSimulator.hh
GhdlSimulator.cc