OpenASIP: CmdReset Class Reference
CmdReset Class Reference
#include <TestOsal.hh>
Public Member Functions
CmdReset ()
CmdReset (const CmdReset &cmd)
virtual ~CmdReset ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Custom command that executes the reset command.
Reset command resets the state of the operation.
Definition at line 77 of file TestOsal.hh.
Constructor & Destructor Documentation
CmdReset() [1/2]
CmdReset::CmdReset ()
Constructor.
Definition at line 186 of file TestOsal.cc.
                   : CustomCommand("reset") {
}
CmdReset() [2/2]
CmdReset::CmdReset (const CmdReset & cmd) explicit
Copy constructor.
Parameters
cmd Command to be copied.
Definition at line 194 of file TestOsal.cc.
                                      : CustomCommand(cmd) {
}
~CmdReset()
CmdReset::~CmdReset () virtual
Destructor
Definition at line 200 of file TestOsal.cc.
                    {
}
Member Function Documentation
execute()
bool CmdReset::execute (const std::vector< DataObject > & arguments) virtual
Executes the command.
Parameters
arguments Arguments for the command.
Returns
True if the command is executed succesfully, otherwise false.
Implements CustomCommand.
Definition at line 210 of file TestOsal.cc.
{
    ScriptInterpreter* scriptInterp = interpreter();
    OsalInterpreter* interp = dynamic_cast<OsalInterpreter*>(scriptInterp);
    assert(interp != NULL);
    DataObject* result = new DataObject();
    if (arguments.size() != 2) {
        result->setString("wrong number of arguments");
        interp->setResult(result);
    return false;
    }
    string opName = arguments[1].stringValue();
    Operation& op = interp->operation(opName);
    if (&op == &NullOperation::instance()) {
        result->setString("unknown operation \"" + opName + "\"");
        interp->setResult(result);
    return false;
    }
    TesterContext& context = *dynamic_cast<TesterContext*>(&interp->context());
    OperationContext& opContext = context.operationContext();
    OperationBehavior& behavior = op.behavior();
    behavior.deleteState(opContext);
    result->setString("");
    interp->setResult(result);
    return true;
}
References assert, Operation::behavior(), CustomCommand::context(), SimpleScriptInterpreter::context(), OperationBehavior::deleteState(), NullOperation::instance(), CustomCommand::interpreter(), OsalInterpreter::operation(), ScriptInterpreter::setResult(), and DataObject::setString().
helpText()
string CmdReset::helpText () const virtual
Returns the help text of the command.
Returns
The help text.
Implements CustomCommand.
Definition at line 248 of file TestOsal.cc.
{
    return "Resets the state of the operation.\n\n"
        "!reset <command name>";
}
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc