OpenASIP: TPEF::ReferenceManager::FileOffsetKey Class Reference
TPEF::ReferenceManager::FileOffsetKey Class Reference
#include <ReferenceKey.hh>
Public Member Functions
FileOffsetKey (FileOffset fileOffset)
virtual ~FileOffsetKey ()
bool operator== (const FileOffsetKey &other) const
bool operator!= (const FileOffsetKey &other) const
bool operator< (const FileOffsetKey &other) const
FileOffset fileOffset () const
Public Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
virtual ~ReferenceKey ()
Private Attributes
FileOffset fileOffset_
File offset of the element this key points to.
Additional Inherited Members
Protected Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
ReferenceKey ()
Detailed Description
With this type of key one can identify objects with its file offset.
Definition at line 121 of file ReferenceKey.hh.
Constructor & Destructor Documentation
FileOffsetKey()
TPEF::ReferenceManager::FileOffsetKey::FileOffsetKey (FileOffset fileOffset)
The constructor.
Parameters
fileOffset File offset.
Definition at line 106 of file ReferenceKey.cc.
                                                  :
    ReferenceKey(), fileOffset_(fileOffset) {
}
~FileOffsetKey()
TPEF::ReferenceManager::FileOffsetKey::~FileOffsetKey () virtual
The destructor.
Definition at line 113 of file ReferenceKey.cc.
{
}
Member Function Documentation
fileOffset()
FileOffset TPEF::ReferenceManager::FileOffsetKey::fileOffset () const
Referenced by TPEF::ReferenceManager::HashFunctions::operator()(), TPEF::ReferenceManager::SafePointer::resolve(), and TPEF::FileOffsetReplacer::tryToReplace().
operator!=()
bool TPEF::ReferenceManager::FileOffsetKey::operator!= (const FileOffsetKey & other) const
operator<()
bool TPEF::ReferenceManager::FileOffsetKey::operator< (const FileOffsetKey & other) const
operator==()
bool TPEF::ReferenceManager::FileOffsetKey::operator== (const FileOffsetKey & other) const
Member Data Documentation
fileOffset_
FileOffset TPEF::ReferenceManager::FileOffsetKey::fileOffset_ private
File offset of the element this key points to.
Definition at line 134 of file ReferenceKey.hh.
The documentation for this class was generated from the following files:
ReferenceKey.hh
ReferenceKey.cc