OpenASIP: HDLGenerator::IntegerConstant Class Reference
HDLGenerator::IntegerConstant Class Reference
#include <HDLGenerator.hh>
Public Member Functions
IntegerConstant (std::string name, int value)
int value () const noexcept
Width width () final
void declare (std::ostream &stream, Language lang, int level)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang, int indent)
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
int value_
Detailed Description
Integer constant.
Definition at line 288 of file HDLGenerator.hh.
Constructor & Destructor Documentation
IntegerConstant()
HDLGenerator::IntegerConstant::IntegerConstant (std::string name, int value) inline
Definition at line 290 of file HDLGenerator.hh.
            : Generatable(name), value_(value) {}
Member Function Documentation
declare()
void HDLGenerator::IntegerConstant::declare (std::ostream & stream, Language lang, int level) inline
Definition at line 297 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                stream << StringTools::indent(level) << "constant " << name()
                       << " : integer := " << value() << ";\n";
            } else if (lang == Language::Verilog) {
                stream << StringTools::indent(level) << "localparam integer "
                       << name() << " = " << value() << ";\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References StringTools::indent(), HDLGenerator::Generatable::name(), value(), HDLGenerator::Verilog, and HDLGenerator::VHDL.
value()
int HDLGenerator::IntegerConstant::value () const inline noexcept
Definition at line 293 of file HDLGenerator.hh.
{ return value_; }
References value_.
Referenced by declare().
width()
Width HDLGenerator::IntegerConstant::width () inline final virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 295 of file HDLGenerator.hh.
{ return {name(), value_}; }
References HDLGenerator::Generatable::name(), and value_.
Member Data Documentation
value_
int HDLGenerator::IntegerConstant::value_ private
Definition at line 310 of file HDLGenerator.hh.
Referenced by value(), and width().
The documentation for this class was generated from the following file:
HDLGenerator.hh