OpenASIP: BFEarlyBypass Class Reference
BFEarlyBypass Class Reference
#include <BFEarlyBypass.hh>
Public Member Functions
BFEarlyBypass (BF2Scheduler &sched, MoveNode &src, MoveNode &mn)
bool operator() () override
void undoOnlyMe () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & src_
MoveNode & dst_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 39 of file BFEarlyBypass.hh.
Constructor & Destructor Documentation
BFEarlyBypass()
BFEarlyBypass::BFEarlyBypass (BF2Scheduler & sched, MoveNode & src, MoveNode & mn) inline
Definition at line 41 of file BFEarlyBypass.hh.
                                                                    :
        BFOptimization(sched), src_(src), dst_(mn) {}
Member Function Documentation
operator()()
bool BFEarlyBypass::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 52 of file BFEarlyBypass.cc.
{
#ifdef DEBUG_LOOP_SCHEDULER
    if (ii() != 0) {
        std::cerr << "\t\t\tEarly bypass for: " << src_.toString()
                  << " to " << dst_.toString() << std::endl;
    }
#endif
    // Take the predecssors so that they can be notified because their
    // antideps may change
    DataDependenceGraph::NodeSet pred = ddg().predecessors(dst_);
    assert(!dst_.isScheduled());
    if (!runPreChild(new BFMergeAndKeepUser(sched_, src_, dst_))) {
        return false;
    }
    // if alwayswriteresults, then must have exactly one result write.
    if (targetMachine().alwaysWriteResults()) {
        // if destination is variable, we have two variable writes. MUST DRE.
        if (dst_.isDestinationVariable()) {
            BFDREEarly* dre = new BFDREEarly(sched_,src_);
            if (!runPostChild(dre)) {
                undo();
                return false;
            }
        }
        // if destination is not variable, must NOT DRE.
    } else {
        BFDREEarly* dre = new BFDREEarly(sched_,src_);
        runPostChild(dre);
    }
    sched_.currentFront()->bypassed(src_, dst_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tEarly bypass ok for: " << dst_.toString() << std::endl;
#endif
    // now notify antideps sources
    for (auto i : pred) {
        mightBeReady(*i);
    }
    return true;
}
References assert, BF2ScheduleFront::bypassed(), BF2Scheduler::currentFront(), BFOptimization::ddg(), dst_, BFOptimization::ii(), MoveNode::isDestinationVariable(), MoveNode::isScheduled(), BFOptimization::mightBeReady(), BoostGraph< GraphNode, GraphEdge >::predecessors(), Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, src_, BFOptimization::targetMachine(), MoveNode::toString(), and Reversible::undo().
undoOnlyMe()
void BFEarlyBypass::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 98 of file BFEarlyBypass.cc.
{
    sched_.currentFront()->undidBypass(src_, dst_);
}
References BF2Scheduler::currentFront(), dst_, BFOptimization::sched_, src_, and BF2ScheduleFront::undidBypass().
Member Data Documentation
dst_
MoveNode& BFEarlyBypass::dst_ private
Definition at line 47 of file BFEarlyBypass.hh.
Referenced by operator()(), and undoOnlyMe().
src_
MoveNode& BFEarlyBypass::src_ private
Definition at line 46 of file BFEarlyBypass.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFEarlyBypass.hh
BFEarlyBypass.cc