OpenASIP: ProximDisassemblyGridTable Class Reference
ProximDisassemblyGridTable Class Reference
#include <ProximDisassemblyGridTable.hh>
Public Member Functions
ProximDisassemblyGridTable ()
~ProximDisassemblyGridTable ()
virtual wxString GetValue (int row, int col)
virtual int GetNumberCols ()
virtual int GetNumberRows ()
virtual wxString GetColLabelValue (int col)
virtual wxGridCellAttr * GetAttr (int row, int col, wxGridCellAttr::wxAttrKind kind)
void setStopPointManager (StopPointManager &manager)
void setCurrentInstruction (Word address)
void setMoveCellAttrProvider (ProximDisasmAttrProvider *attrProvider)
ProximDisasmAttrProvider * moveCellAttrProvider () const
void showPCArrow ()
void hidePCArrow ()
Public Member Functions inherited from DisassemblyGridTable
DisassemblyGridTable ()
virtual ~DisassemblyGridTable ()
virtual bool IsEmptyCell (int row, int col)
virtual wxString GetRowLabelValue (int row)
virtual void SetValue (int row, int col, const wxString &value)
virtual bool CanHaveAttributes ()
int rowOfAddress (Word address)
Word addressOfRow (int row)
void loadProgram (const TTAProgram::Program &program)
Private Attributes
Word currentInstruction_
Program counter value.
StopPointManager * bpManager_
Stoppoint manager managing program breakpoints.
bool showPCArrow_
True, if the current istrcution arrow should be displayed.
ProximDisasmAttrProvider * attrProvider_
Additional Inherited Members
Protected Attributes inherited from DisassemblyGridTable
const TTAProgram::Program * program_
Program loaded in the table.
Detailed Description
A specialized DisassemblyGridTable class, which adds a column with breakpoint labels and arrow displaying the current instruction to the disassembly grid.
Definition at line 47 of file ProximDisassemblyGridTable.hh.
Constructor & Destructor Documentation
ProximDisassemblyGridTable()
ProximDisassemblyGridTable::ProximDisassemblyGridTable ()
The Constructor.
Definition at line 49 of file ProximDisassemblyGridTable.cc.
                                                      :
    DisassemblyGridTable(), bpManager_(NULL),
    attrProvider_(NULL) {
}
~ProximDisassemblyGridTable()
ProximDisassemblyGridTable::~ProximDisassemblyGridTable ()
The Destructor.
Definition at line 59 of file ProximDisassemblyGridTable.cc.
{
    if (attrProvider_ != NULL) {
        delete attrProvider_;
    }
}
References attrProvider_.
Member Function Documentation
GetAttr()
wxGridCellAttr * ProximDisassemblyGridTable::GetAttr (int row, int col, wxGridCellAttr::wxAttrKind kind) virtual
Returns cell style attributes for a cell with given row and column.
@paran row Row of the grid cell.
Parameters
col Column of the grid cell.
Returns
Cell's style attribute.
Definition at line 232 of file ProximDisassemblyGridTable.cc.
{
    wxGridCellAttr* attr = new wxGridCellAttr();
    if (ProximToolbox::frontend()->isProgramLoaded() &&  row >= 0 && col > 1) {
        if (attrProvider_ != NULL) {
            return attrProvider_->moveCellAttr(addressOfRow(row), col - 2);
        }
    } else {
        attr->SetBackgroundColour(wxColour(180, 180, 180));
    }
    return attr;
}
References DisassemblyGridTable::addressOfRow(), attrProvider_, ProximToolbox::frontend(), and ProximDisasmAttrProvider::moveCellAttr().
GetColLabelValue()
wxString ProximDisassemblyGridTable::GetColLabelValue (int col) virtual
Returns label for a column.
Parameters
col Column index.
Returns
Column label.
Reimplemented from DisassemblyGridTable.
Definition at line 160 of file ProximDisassemblyGridTable.cc.
{
    if (col > 1) {
        return DisassemblyGridTable::GetColLabelValue(col - 1);
    } else {
        return _T("");
    }
}
References DisassemblyGridTable::GetColLabelValue().
GetNumberCols()
int ProximDisassemblyGridTable::GetNumberCols () virtual
Returns number of columns in the grid.
Returns
Number of columns.
Reimplemented from DisassemblyGridTable.
Definition at line 128 of file ProximDisassemblyGridTable.cc.
{
    if (!ProximToolbox::frontend()->isProgramLoaded()) {
        return 0;
    }
    return DisassemblyGridTable::GetNumberCols() + 1;
}
References ProximToolbox::frontend(), and DisassemblyGridTable::GetNumberCols().
GetNumberRows()
int ProximDisassemblyGridTable::GetNumberRows () virtual
Returns number of rows in the grid.
Returns
Number of rows.
Reimplemented from DisassemblyGridTable.
Definition at line 144 of file ProximDisassemblyGridTable.cc.
{
    if (!ProximToolbox::frontend()->isProgramLoaded()) {
        return 0;
    }
    return DisassemblyGridTable::GetNumberRows();
}
References ProximToolbox::frontend(), and DisassemblyGridTable::GetNumberRows().
GetValue()
wxString ProximDisassemblyGridTable::GetValue (int row, int col) virtual
Returns text value of a cell.
Parameters
row Row of the cell.
col Column of the cell.
Returns
Value of the cell as wxString.
Reimplemented from DisassemblyGridTable.
Definition at line 86 of file ProximDisassemblyGridTable.cc.
{
    if (!ProximToolbox::frontend()->isProgramLoaded()) {
        return _T("");
    }
    wxString value;
    if (col == 0 && bpManager_ != NULL) {
        for (unsigned i = 0; i < bpManager_->stopPointCount(); i++) {
            unsigned handle = bpManager_->stopPointHandle(i);
            const Breakpoint* bp =
                dynamic_cast<const Breakpoint*>(
                      &bpManager_->stopPointWithHandleConst(handle));
            if (bp != NULL) {
                Word address = bp->address();
                if (address == (Word)row) {
                    value.Append(WxConversion::toWxString(handle));
                    value.Append(_T(" "));
                }
            }
        }
    }
    if (col == 0 && showPCArrow_ && (Word)row == currentInstruction_) {
        value.Append(_T("next>"));
    }
    if (col > 0) {
        value = DisassemblyGridTable::GetValue(row, col - 1);
    }
    return value;
}
References Breakpoint::address(), bpManager_, currentInstruction_, ProximToolbox::frontend(), DisassemblyGridTable::GetValue(), showPCArrow_, StopPointManager::stopPointCount(), StopPointManager::stopPointHandle(), StopPointManager::stopPointWithHandleConst(), and WxConversion::toWxString().
hidePCArrow()
void ProximDisassemblyGridTable::hidePCArrow ()
Turns off showing of the arrow displaying the current instruction.
Definition at line 180 of file ProximDisassemblyGridTable.cc.
{
    showPCArrow_ = false;
}
References showPCArrow_.
moveCellAttrProvider()
ProximDisasmAttrProvider * ProximDisassemblyGridTable::moveCellAttrProvider () const
Returns the move cell attribute provider.
Returns
Move cell attribute provider, or NULL is it's not set.
Definition at line 219 of file ProximDisassemblyGridTable.cc.
{
    return attrProvider_;
}
References attrProvider_.
Referenced by ProximDisassemblyWindow::onSimulatorStop().
setCurrentInstruction()
void ProximDisassemblyGridTable::setCurrentInstruction (Word address)
Sets address of the current instruction.
Parameters
address Address of the current instruction.
Definition at line 191 of file ProximDisassemblyGridTable.cc.
{
    currentInstruction_ = address;
}
References currentInstruction_.
Referenced by ProximDisassemblyWindow::loadProgram(), and ProximDisassemblyWindow::onSimulatorStop().
setMoveCellAttrProvider()
void ProximDisassemblyGridTable::setMoveCellAttrProvider (ProximDisasmAttrProvider * attrProvider)
Sets the cell attribute provider for cell's containing move disassembly.
ProximDisassemblyGridTable take ownership of the pointer and deletes the object when it's no longer needed.
Parameters
attrProvider New move cell attribute provider.
Definition at line 204 of file ProximDisassemblyGridTable.cc.
{
    if (attrProvider_ != NULL) {
        delete attrProvider_;
    }
    attrProvider_ = attrProvider;
}
References attrProvider_.
Referenced by ProximDisassemblyWindow::setMoveAttrProvider().
setStopPointManager()
void ProximDisassemblyGridTable::setStopPointManager (StopPointManager & bpManager)
Sets the breakpoint manager containing program breakpoints to display.
Parameters
bpManager Breakpoint manager of the program.
Definition at line 71 of file ProximDisassemblyGridTable.cc.
{
    bpManager_ = &bpManager;
}
References bpManager_.
Referenced by ProximDisassemblyWindow::loadProgram().
showPCArrow()
void ProximDisassemblyGridTable::showPCArrow ()
Turns on showing of the arrow displaying the current instruction.
Definition at line 172 of file ProximDisassemblyGridTable.cc.
{
    showPCArrow_ = true;
}
References showPCArrow_.
Referenced by ProximDisassemblyWindow::loadProgram().
Member Data Documentation
attrProvider_
ProximDisasmAttrProvider* ProximDisassemblyGridTable::attrProvider_ private
Definition at line 74 of file ProximDisassemblyGridTable.hh.
Referenced by GetAttr(), moveCellAttrProvider(), setMoveCellAttrProvider(), and ~ProximDisassemblyGridTable().
bpManager_
StopPointManager* ProximDisassemblyGridTable::bpManager_ private
Stoppoint manager managing program breakpoints.
Definition at line 70 of file ProximDisassemblyGridTable.hh.
Referenced by GetValue(), and setStopPointManager().
currentInstruction_
Word ProximDisassemblyGridTable::currentInstruction_ private
Program counter value.
Definition at line 68 of file ProximDisassemblyGridTable.hh.
Referenced by GetValue(), and setCurrentInstruction().
showPCArrow_
bool ProximDisassemblyGridTable::showPCArrow_ private
True, if the current istrcution arrow should be displayed.
Definition at line 72 of file ProximDisassemblyGridTable.hh.
Referenced by GetValue(), hidePCArrow(), and showPCArrow().
The documentation for this class was generated from the following files:
ProximDisassemblyGridTable.hh
ProximDisassemblyGridTable.cc