OpenASIP: ProximSocketDetailsCmd Class Reference
ProximSocketDetailsCmd Class Reference
#include <ProximSocketDetailsCmd.hh>
Public Member Functions
ProximSocketDetailsCmd (const TTAMachine::Socket &socket)
virtual ~ProximSocketDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::Socket & socket_
Socket to display.
Detailed Description
Command for displaying socket details in the machine window component details pane.
Definition at line 46 of file ProximSocketDetailsCmd.hh.
Constructor & Destructor Documentation
ProximSocketDetailsCmd()
ProximSocketDetailsCmd::ProximSocketDetailsCmd (const TTAMachine::Socket & socket)
The Constructor.
Parameters
bus Socket to display.
Definition at line 51 of file ProximSocketDetailsCmd.cc.
                                    :
    ComponentCommand(), socket_(socket) {
}
~ProximSocketDetailsCmd()
ProximSocketDetailsCmd::~ProximSocketDetailsCmd () virtual
The Destructor.
Definition at line 60 of file ProximSocketDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximSocketDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 67 of file ProximSocketDetailsCmd.cc.
{
    string socketName = socket_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_SOCKET_LABEL);
    machineWin->appendDetails(socketName + "\n\n");
    // Append utlization statistics.
    ClockCycleCount writes = stats.socketWrites(socketName);
    machineWin->appendUtilizationData(
        ProximConstants::MACH_WIN_SOCKET_WRITES_LABEL);
    machineWin->appendUtilizationData(Conversion::toString(writes));
    ClockCycleCount cycles = ProximToolbox::frontend()->cycleCount();
    double percent = 0;
    if (cycles > 0) {
        percent = (100.0 * writes) / cycles;
    }
    machineWin->appendUtilizationData(
        " (" + Conversion::toString(percent) + "%)");
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximMachineStateWindow::appendUtilizationData(), SimulatorFrontend::cycleCount(), ProximToolbox::frontend(), ProximConstants::MACH_WIN_SOCKET_LABEL, ProximConstants::MACH_WIN_SOCKET_WRITES_LABEL, ProximToolbox::machineStateWindow(), TTAMachine::Component::name(), socket_, UtilizationStats::socketWrites(), Conversion::toString(), and SimulatorFrontend::utilizationStatistics().
Member Data Documentation
socket_
const TTAMachine::Socket& ProximSocketDetailsCmd::socket_ private
Socket to display.
Definition at line 53 of file ProximSocketDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximSocketDetailsCmd.hh
ProximSocketDetailsCmd.cc