OpenASIP: LImmDstRegisterField Class Reference
LImmDstRegisterField Class Reference
#include <LImmDstRegisterField.hh>
Public Member Functions
LImmDstRegisterField (int width, BinaryEncoding &parent)
LImmDstRegisterField (const ObjectState *state, BinaryEncoding &parent)
virtual ~LImmDstRegisterField ()
BinaryEncoding * parent () const
void addDestination (const std::string &instructionTemplate, const std::string &immediateUnit)
int instructionTemplateCount () const
std::string instructionTemplate (int index) const
bool usedByInstructionTemplate (const std::string &instructionTemplate) const
std::string immediateUnit (const std::string &instructionTemplate) const
virtual int width () const
virtual int childFieldCount () const
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
virtual InstructionField & childField (int position) const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_LIMM_DST_REGISTER_FIELD
ObjectState name for long immediate destination register field.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for the width of the field.
static const std::string OSNAME_IU_DESTINATION = "iu_dst"
ObjectState name for a immediate unit destination.
static const std::string OSKEY_ITEMP = "itemp"
ObjectState attribute key for the name of the instruction template.
static const std::string OSKEY_DST_IU = "iu"
ObjectState attribute key for the name of the immediate unit.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Types
typedef std::map< std::string, std::string > StringMap
Map type for strings.
Private Member Functions
void loadState (const ObjectState *state)
Private Attributes
int width_
Width of the field.
StringMap destinationMap_
Maps instruction templates to immediate units.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
Represets the instruction field that contains the register index where a long immediate is going to be written.
Definition at line 47 of file LImmDstRegisterField.hh.
Member Typedef Documentation
StringMap
typedef std::map<std::string, std::string> LImmDstRegisterField::StringMap private
Map type for strings.
Definition at line 82 of file LImmDstRegisterField.hh.
Constructor & Destructor Documentation
LImmDstRegisterField() [1/2]
LImmDstRegisterField::LImmDstRegisterField (int width, BinaryEncoding & parent)
The constructor.
Registers the field automatically to the given parent.
Parameters
width Width of the field.
parent The parent BinaryEncoding instance.
Exceptions
OutOfRange If the given width is 0 or smaller.
Definition at line 59 of file LImmDstRegisterField.cc.
    : InstructionField(&parent), width_(width) {
    if (width < 1) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    setParent(NULL);
    parent.addLongImmDstRegisterField(*this);
    setParent(&parent);
}
References __func__, BinaryEncoding::addLongImmDstRegisterField(), parent(), InstructionField::setParent(), and width().
LImmDstRegisterField() [2/2]
LImmDstRegisterField::LImmDstRegisterField (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the object from the given ObjectState instance. Registers the field automatically to the given parent.
Parameters
state The ObjectState instance.
parent The parent BinaryEncoding instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is erroneous.
Definition at line 81 of file LImmDstRegisterField.cc.
    : InstructionField(state, &parent), width_(0) {
    loadState(state);
    setParent(NULL);
    parent.addLongImmDstRegisterField(*this);
    setParent(&parent);
}
References BinaryEncoding::addLongImmDstRegisterField(), loadState(), parent(), and InstructionField::setParent().
~LImmDstRegisterField()
LImmDstRegisterField::~LImmDstRegisterField () virtual
The destructor.
Definition at line 93 of file LImmDstRegisterField.cc.
{
    BinaryEncoding* parent = this->parent();
    setParent(NULL);
    parent->removeLongImmDstRegisterField(*this);
}
References parent(), BinaryEncoding::removeLongImmDstRegisterField(), and InstructionField::setParent().
Member Function Documentation
addDestination()
void LImmDstRegisterField::addDestination (const std::string & instructionTemplate, const std::string & immediateUnit)
Sets that the register index of the given immediate unit in the given instruction template is given in this field.
Parameters
instructionTemplate The instruction template.
immediateUnit The immediate unit.
Exceptions
NotAvailable If index of some other immediate unit is assigned to this field in the same instruction template.
Definition at line 129 of file LImmDstRegisterField.cc.
{
    if (MapTools::containsKey(destinationMap_, instructionTemplate) &&
        MapTools::valueForKey<string>(destinationMap_, instructionTemplate)
        != immediateUnit) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    } else {
        destinationMap_.insert(
            std::pair<string, string>(instructionTemplate, immediateUnit));
    }
}
References __func__, MapTools::containsKey(), destinationMap_, immediateUnit(), instructionTemplate(), and MapTools::keyForValue().
Referenced by BEMGenerator::addLongImmDstRegisterFields(), and loadState().
childFieldCount()
int LImmDstRegisterField::childFieldCount () const virtual
Returns the number of child fields, that is always 0.
Returns
0.
Implements InstructionField.
Definition at line 224 of file LImmDstRegisterField.cc.
{
    return 0;
}
immediateUnit()
std::string LImmDstRegisterField::immediateUnit (const std::string & instructionTemplate) const
Returns the name of the immediate unit for which the field is assigned in the given instruction template.
Parameters
instructionTemplate Name of the instruction template.
Exceptions
NotAvailable If the field is not used in the given instruction template.
Definition at line 197 of file LImmDstRegisterField.cc.
{
    try {
        return MapTools::valueForKey<string>(
            destinationMap_, instructionTemplate);
    } catch (const Exception&) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    }
}
References __func__, destinationMap_, instructionTemplate(), and MapTools::keyForValue().
Referenced by CodeCompressorPlugin::addBitsForDstRegisterField(), addDestination(), BEMValidator::checkLImmDstRegisterFields(), BinaryEncoding::longImmDstRegisterField(), and printLImmDstRegisterField().
instructionTemplate()
std::string LImmDstRegisterField::instructionTemplate (int index) const
By the given index, returns an instruction template that uses this destination register field.
Parameters
index The index.
Exceptions
OutOfRange If the index is negative or not smaller than the number of instruction templates.
Definition at line 162 of file LImmDstRegisterField.cc.
{
    if (index < 0 || index >= instructionTemplateCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    StringMap::const_iterator iter = destinationMap_.begin();
    for (int i = 0; i < index; i++) {
        iter++;
    }
    return iter->first;
}
References __func__, destinationMap_, and instructionTemplateCount().
Referenced by addDestination(), immediateUnit(), printLImmDstRegisterField(), and usedByInstructionTemplate().
instructionTemplateCount()
int LImmDstRegisterField::instructionTemplateCount () const
Returns the number of instruction templates that use this destination register field.
Returns
The number of instruction templates.
Definition at line 148 of file LImmDstRegisterField.cc.
{
    return destinationMap_.size();
}
References destinationMap_.
Referenced by instructionTemplate(), and printLImmDstRegisterField().
loadState()
void LImmDstRegisterField::loadState (const ObjectState * state) private virtual
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Reimplemented from InstructionField.
Definition at line 260 of file LImmDstRegisterField.cc.
{
    if (state->name() != OSNAME_LIMM_DST_REGISTER_FIELD) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, __func__);
    }
    InstructionField::loadState(state);
    try {
        width_ = state->intAttribute(OSKEY_WIDTH);
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() != OSNAME_IU_DESTINATION) {
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, __func__);
            }
            string iTemp = child->stringAttribute(OSKEY_ITEMP);
            string iu = child->stringAttribute(OSKEY_DST_IU);
            addDestination(iTemp, iu);
        }
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, __func__, e.errorMessage());
    }
}
References __func__, addDestination(), ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::intAttribute(), InstructionField::loadState(), ObjectState::name(), OSKEY_DST_IU, OSKEY_ITEMP, OSKEY_WIDTH, OSNAME_IU_DESTINATION, OSNAME_LIMM_DST_REGISTER_FIELD, ObjectState::stringAttribute(), and width_.
Referenced by LImmDstRegisterField().
parent()
BinaryEncoding * LImmDstRegisterField::parent () const
Returns the parent BinaryEncoding instance.
Returns
The parent BinaryEncoding instance.
Definition at line 106 of file LImmDstRegisterField.cc.
{
    InstructionField* parent = InstructionField::parent();
    if (parent != NULL) {
        BinaryEncoding* bem = dynamic_cast<BinaryEncoding*>(parent);
        assert(bem != NULL);
        return bem;
    } else {
        return NULL;
    }
}
References assert, InstructionField::parent(), and parent().
Referenced by BinaryEncoding::addLongImmDstRegisterField(), LImmDstRegisterField(), LImmDstRegisterField(), parent(), BinaryEncoding::removeLongImmDstRegisterField(), and ~LImmDstRegisterField().
saveState()
ObjectState * LImmDstRegisterField::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from InstructionField.
Definition at line 235 of file LImmDstRegisterField.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_LIMM_DST_REGISTER_FIELD);
    state->setAttribute(OSKEY_WIDTH, width());
    // add destinations
    for (StringMap::const_iterator iter = destinationMap_.begin();
         iter != destinationMap_.end(); iter++) {
        ObjectState* dstState = new ObjectState(OSNAME_IU_DESTINATION);
        state->addChild(dstState);
        dstState->setAttribute(OSKEY_ITEMP, iter->first);
        dstState->setAttribute(OSKEY_DST_IU, iter->second);
    }
    return state;
}
References ObjectState::addChild(), destinationMap_, OSKEY_DST_IU, OSKEY_ITEMP, OSKEY_WIDTH, OSNAME_IU_DESTINATION, OSNAME_LIMM_DST_REGISTER_FIELD, InstructionField::saveState(), ObjectState::setAttribute(), ObjectState::setName(), and width().
Referenced by BinaryEncoding::saveState().
usedByInstructionTemplate()
bool LImmDstRegisterField::usedByInstructionTemplate (const std::string & instructionTemplate) const
Tells whether the field is used by the given instruction template.
Parameters
instructionTemplate The instruction template.
Definition at line 181 of file LImmDstRegisterField.cc.
{
    return MapTools::containsKey(destinationMap_, instructionTemplate);
}
References MapTools::containsKey(), destinationMap_, and instructionTemplate().
Referenced by BEMValidator::checkLImmDstRegisterFields(), and BinaryEncoding::longImmDstRegisterField().
width()
int LImmDstRegisterField::width () const virtual
Returns the width of the field.
Returns
The bit width of the field.
Implements InstructionField.
Definition at line 213 of file LImmDstRegisterField.cc.
{
    return width_;
}
References width_.
Referenced by CodeCompressorPlugin::addBitsForDstRegisterField(), CodeCompressorPlugin::bemInstructionBits(), BEMValidator::checkLImmDstRegisterFields(), CodeCompressorPlugin::firstMoveSlotIndex(), LImmDstRegisterField(), printInstructionLayout(), printLImmDstRegisterField(), saveState(), and BinaryEncoding::width().
Member Data Documentation
destinationMap_
StringMap LImmDstRegisterField::destinationMap_ private
Maps instruction templates to immediate units.
Definition at line 89 of file LImmDstRegisterField.hh.
Referenced by addDestination(), immediateUnit(), instructionTemplate(), instructionTemplateCount(), saveState(), and usedByInstructionTemplate().
OSKEY_DST_IU
const std::string LImmDstRegisterField::OSKEY_DST_IU = "iu" static
ObjectState attribute key for the name of the immediate unit.
Definition at line 78 of file LImmDstRegisterField.hh.
Referenced by loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), and saveState().
OSKEY_ITEMP
const std::string LImmDstRegisterField::OSKEY_ITEMP = "itemp" static
ObjectState attribute key for the name of the instruction template.
Definition at line 76 of file LImmDstRegisterField.hh.
Referenced by loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), and saveState().
OSKEY_WIDTH
const std::string LImmDstRegisterField::OSKEY_WIDTH = "width" static
ObjectState attribute key for the width of the field.
Definition at line 72 of file LImmDstRegisterField.hh.
Referenced by loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), and saveState().
OSNAME_IU_DESTINATION
const std::string LImmDstRegisterField::OSNAME_IU_DESTINATION = "iu_dst" static
ObjectState name for a immediate unit destination.
Definition at line 74 of file LImmDstRegisterField.hh.
Referenced by loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), and saveState().
OSNAME_LIMM_DST_REGISTER_FIELD
const std::string LImmDstRegisterField::OSNAME_LIMM_DST_REGISTER_FIELD static
Initial value:
=
    "dst_reg_field"
ObjectState name for long immediate destination register field.
Definition at line 70 of file LImmDstRegisterField.hh.
Referenced by BEMSerializer::convertToFileFormat(), BinaryEncoding::loadState(), loadState(), BEMSerializer::longImmDstRegFieldToOM(), and saveState().
width_
int LImmDstRegisterField::width_ private
Width of the field.
Definition at line 87 of file LImmDstRegisterField.hh.
Referenced by loadState(), and width().
The documentation for this class was generated from the following files:
LImmDstRegisterField.hh
LImmDstRegisterField.cc