OpenASIP: OSEdSimulateCmd Class Reference
OSEdSimulateCmd Class Reference
#include <OSEdSimulateCmd.hh>
Public Member Functions
OSEdSimulateCmd ()
virtual ~OSEdSimulateCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdSimulateCmd (const OSEdSimulateCmd &)
Copying not allowed.
OSEdSimulateCmd & operator= (const OSEdSimulateCmd &)
Assignment not allowed.
Detailed Description
Executes the command when operation is simulated.
Definition at line 43 of file OSEdSimulateCmd.hh.
Constructor & Destructor Documentation
OSEdSimulateCmd() [1/2]
OSEdSimulateCmd::OSEdSimulateCmd ()
Constructor.
Definition at line 50 of file OSEdSimulateCmd.cc.
                                 :
    GUICommand(OSEdConstants::CMD_NAME_SIMULATE, NULL) {
}
Referenced by create().
~OSEdSimulateCmd()
OSEdSimulateCmd::~OSEdSimulateCmd () virtual
Destructor.
Definition at line 57 of file OSEdSimulateCmd.cc.
{
}
OSEdSimulateCmd() [2/2]
OSEdSimulateCmd::OSEdSimulateCmd (const OSEdSimulateCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdSimulateCmd::create () const virtual
Creates a new command.
Returns
The created command.
Implements GUICommand.
Definition at line 76 of file OSEdSimulateCmd.cc.
{
    return new OSEdSimulateCmd();
}
References OSEdSimulateCmd().
Do()
bool OSEdSimulateCmd::Do () virtual
Executes the command.
Returns
Always true.
Implements GUICommand.
Definition at line 86 of file OSEdSimulateCmd.cc.
                    {
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTreeView* treeView = mainFrame->treeView();
    Operation* op = treeView->selectedOperation();
    wxTreeItemId opId = treeView->selectedOperationId();
    string modName = treeView->moduleOfOperation(opId);
    wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
    string pathName = treeView->pathOfModule(modId);
    //OperationModule& module = OperationContainer::module(pathName, modName);
    SimulateDialog* dialog =
        new SimulateDialog(parentWindow(), op, pathName, modName);
    dialog->ShowModal();
    return true;
}
References OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::moduleOfOperation(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OSEdTreeView::selectedOperation(), OSEdTreeView::selectedOperationId(), and OSEdMainFrame::treeView().
icon()
string OSEdSimulateCmd::icon () const virtual
Return icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 128 of file OSEdSimulateCmd.cc.
{
    return "";
}
id()
int OSEdSimulateCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 66 of file OSEdSimulateCmd.cc.
{
    return OSEdConstants::CMD_SIMULATE;
}
References OSEdConstants::CMD_SIMULATE.
isEnabled()
bool OSEdSimulateCmd::isEnabled () virtual
Returns true if command is enabled.
Command is enabled, if selected operation has behavior module.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 112 of file OSEdSimulateCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    Operation* op = treeView->selectedOperation();
    if (treeView->isOperationSelected() &&  op != NULL) {
        return op->canBeSimulated();
    }
    return false;
}
References Operation::canBeSimulated(), OSEdTreeView::isOperationSelected(), and OSEdTreeView::selectedOperation().
operator=()
OSEdSimulateCmd & OSEdSimulateCmd::operator= (const OSEdSimulateCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdSimulateCmd.hh
OSEdSimulateCmd.cc