OpenASIP: CompiledSimMove Class Reference
CompiledSimMove Class Reference
#include <CompiledSimMove.hh>
Public Member Functions
CompiledSimMove (const TTAProgram::Move &move, const std::string &guardSymbol, const CompiledSimSymbolGenerator &symbolGenerator)
CompiledSimMove (const CompiledSimMove &)
CompiledSimMove & operator= (const CompiledSimMove &)
std::string copyToBusCode () const
std::string copyFromBusCode () const
const TTAProgram::Terminal & destination () const
Private Attributes
const TTAProgram::Move * move_
The move.
const TTAProgram::Terminal * source_
Source of move.
const TTAProgram::Terminal * destination_
Destination of move.
const TTAMachine::Bus * bus_
Bus.
std::string guardSymbol_
guard symbol used for move
const CompiledSimSymbolGenerator & symbolGenerator_
the symbol generator
Detailed Description
A class that handles copying values to/from a bus in the compiled simulation
Definition at line 53 of file CompiledSimMove.hh.
Constructor & Destructor Documentation
CompiledSimMove() [1/2]
CompiledSimMove::CompiledSimMove (const TTAProgram::Move & move, const std::string & guardSymbol, const CompiledSimSymbolGenerator & symbolGenerator)
The Constructor
Parameters
move The original move
guardSymbol Symbolname of the guard or "" if no guard is used
Definition at line 49 of file CompiledSimMove.cc.
                                                       :
    move_(&move),
    source_(&move.source()),
    destination_(&move.destination()),
    bus_(&move.bus()),
    guardSymbol_(guardSymbol),
    symbolGenerator_(symbolGenerator) {
}
CompiledSimMove() [2/2]
CompiledSimMove::CompiledSimMove (const CompiledSimMove & move)
Copy constructor
Parameters
move the move
Definition at line 66 of file CompiledSimMove.cc.
                                                            :
    source_(move.source_),
    destination_ (move.destination_),
    bus_(move.bus_),
    guardSymbol_(move.guardSymbol_),
    symbolGenerator_(move.symbolGenerator_) {
}
Member Function Documentation
copyFromBusCode()
std::string CompiledSimMove::copyFromBusCode () const
Generates C/C++ code that copies data from bus variable to a move destination
Returns
The generated code
Definition at line 107 of file CompiledSimMove.cc.
{
    string destination = symbolGenerator_.moveOperandSymbol(*destination_,
        *move_);
    string bus = symbolGenerator_.busSymbol(*bus_);
    string code = destination + " = " + bus + ";";
    if (guardSymbol_ != "") {
        code = "if (" + guardSymbol_ + ") {" + code + " } ";
    }
    return code;
}
References bus_, CompiledSimSymbolGenerator::busSymbol(), destination(), destination_, guardSymbol_, move_, CompiledSimSymbolGenerator::moveOperandSymbol(), and symbolGenerator_.
copyToBusCode()
std::string CompiledSimMove::copyToBusCode () const
Generates C/C++ code that copies data from move source to a bus variable
Returns
The generated code
Definition at line 95 of file CompiledSimMove.cc.
{
    string source = symbolGenerator_.moveOperandSymbol(*source_, *move_);
    string bus = symbolGenerator_.busSymbol(*bus_);
    return bus + " = " + source + ";";
}
References bus_, CompiledSimSymbolGenerator::busSymbol(), move_, CompiledSimSymbolGenerator::moveOperandSymbol(), source_, and symbolGenerator_.
Referenced by CompiledSimCodeGenerator::generateInstruction().
destination()
const TTAProgram::Terminal & CompiledSimMove::destination () const inline
Definition at line 64 of file CompiledSimMove.hh.
{ return *destination_; }
References destination_.
Referenced by copyFromBusCode().
operator=()
CompiledSimMove & CompiledSimMove::operator= (const CompiledSimMove & move)
Assignmnent operator
Parameters
move the move
Definition at line 80 of file CompiledSimMove.cc.
{
    this->source_ = move.source_;
    this->destination_ = move.destination_;
    this->bus_ = move.bus_;
    this->guardSymbol_ = move.guardSymbol_;
    return *this;
}
References bus_, destination_, guardSymbol_, and source_.
Member Data Documentation
bus_
const TTAMachine::Bus* CompiledSimMove::bus_ private
Bus.
Definition at line 76 of file CompiledSimMove.hh.
Referenced by copyFromBusCode(), copyToBusCode(), and operator=().
destination_
const TTAProgram::Terminal* CompiledSimMove::destination_ private
Destination of move.
Definition at line 73 of file CompiledSimMove.hh.
Referenced by copyFromBusCode(), destination(), and operator=().
guardSymbol_
std::string CompiledSimMove::guardSymbol_ private
guard symbol used for move
Definition at line 79 of file CompiledSimMove.hh.
Referenced by copyFromBusCode(), and operator=().
move_
const TTAProgram::Move* CompiledSimMove::move_ private
The move.
Definition at line 67 of file CompiledSimMove.hh.
Referenced by copyFromBusCode(), and copyToBusCode().
source_
const TTAProgram::Terminal* CompiledSimMove::source_ private
Source of move.
Definition at line 70 of file CompiledSimMove.hh.
Referenced by copyToBusCode(), and operator=().
symbolGenerator_
const CompiledSimSymbolGenerator& CompiledSimMove::symbolGenerator_ private
the symbol generator
Definition at line 82 of file CompiledSimMove.hh.
Referenced by copyFromBusCode(), and copyToBusCode().
The documentation for this class was generated from the following files:
CompiledSimMove.hh
CompiledSimMove.cc