OpenASIP: FSAFUResourceConflictDetector Class Reference
FSAFUResourceConflictDetector Class Reference
#include <FSAFUResourceConflictDetector.hh>
Public Member Functions
FSAFUResourceConflictDetector (const TTAMachine::FunctionUnit &fu)
virtual ~FSAFUResourceConflictDetector ()
virtual bool issueOperation (OperationID id)
virtual bool advanceCycle ()
virtual bool isIdle ()
bool issueOperationInline (OperationID id)
bool issueOperationLazyInline (OperationID id)
bool advanceCycleInline ()
bool advanceCycleLazyInline ()
virtual void reset ()
void initializeAllStates ()
const char * operationName (OperationID id) const
virtual OperationID operationID (const TCEString &operationName) const
virtual void writeToDotFile (const TCEString &fileName) const
Public Member Functions inherited from FUResourceConflictDetector
FUResourceConflictDetector ()
virtual ~FUResourceConflictDetector ()
virtual void endClock ()
virtual void advanceClock ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Private Attributes
FSAFUResourceConflictDetectorPimpl * pimpl_
Private implementation in a separate source file.
Additional Inherited Members
Public Types inherited from FUResourceConflictDetector
typedef int OperationID
Type for identifying operations in the conflict detector interface.
Protected Attributes inherited from FUResourceConflictDetector
OperationIDIndex * operationIndices_
Map for finding indices for operations quickly.
Detailed Description
An FSA implementation of a FU resource conflict detector.
Definition at line 49 of file FSAFUResourceConflictDetector.hh.
Constructor & Destructor Documentation
FSAFUResourceConflictDetector()
FSAFUResourceConflictDetector::FSAFUResourceConflictDetector (const TTAMachine::FunctionUnit & fu)
Constructor.
Initializes the FSA to a lazy mode in which the states are built when they are needed the first time. In order to initialize all states, call initializeAllStates().
Parameters
fu The function unit to detect conflicts for.
Exceptions
InvalidData If the model could not be built from the given FU.
Definition at line 52 of file FSAFUResourceConflictDetector.cc.
                                      :
    FUResourceConflictDetector(),
    pimpl_(new FSAFUResourceConflictDetectorPimpl(fu)) {
    issueOperation(pimpl_->NOP);
}
References issueOperation(), FSAFUResourceConflictDetectorPimpl::NOP, and pimpl_.
~FSAFUResourceConflictDetector()
FSAFUResourceConflictDetector::~FSAFUResourceConflictDetector () virtual
Destructor.
Definition at line 62 of file FSAFUResourceConflictDetector.cc.
{
    delete pimpl_;
    pimpl_ = NULL;
}
References pimpl_.
Member Function Documentation
advanceCycle()
bool FSAFUResourceConflictDetector::advanceCycle () virtual
Simulates a cycle advance and reports a conflict if detected.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 120 of file FSAFUResourceConflictDetector.cc.
{
    return advanceCycleLazyInline();
}
References advanceCycleLazyInline().
advanceCycleInline()
bool FSAFUResourceConflictDetector::advanceCycleInline () inline
Simulates a cycle advance and reports a conflict if detected.
Inlineable optimized version for compiled simulation and benchmarking.
Note
Do not call this in case the last operation issue transfered the FSA to the illegal state! That is, returned false. No checking is done to get fastest possible simulation.
Returns
False in case a conflict is detected, otherwise true.
Definition at line 230 of file FSAFUResourceConflictDetector.cc.
{
    // assert(nextState_ != FiniteStateAutomaton::ILLEGAL_STATE);
    pimpl_->currentState_ = pimpl_->nextState_;
    // issue NOP transition at the next cycle in case there are no other
    // operation issues
    pimpl_->nextState_ = pimpl_->
        fsa_.transitions_[pimpl_->currentState_][pimpl_->NOP];
    return true;
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::nextState_, FSAFUResourceConflictDetectorPimpl::NOP, and pimpl_.
advanceCycleLazyInline()
bool FSAFUResourceConflictDetector::advanceCycleLazyInline () inline
Simulates a cycle advance and reports a conflict if detected.
Inlineable optimized version for compiled simulation and benchmarking.
Note
Do not call this in case the last operation issue transfered the FSA to the illegal state! That is, returned false. No checking is done to get fastest possible simulation.
Returns
False in case a conflict is detected, otherwise true.
Definition at line 253 of file FSAFUResourceConflictDetector.cc.
{
    // assert(nextState_ != FiniteStateAutomaton::ILLEGAL_STATE);
    pimpl_->currentState_ = pimpl_->nextState_;
    // issue NOP transition at the next cycle in case there are no other
    // operation issues
    pimpl_->nextState_ = pimpl_->fsa_.transitions_[pimpl_->currentState_][pimpl_->NOP];
    if (pimpl_->nextState_ == FiniteStateAutomaton::UNKNOWN_STATE) {
        pimpl_->nextState_ = pimpl_->fsa_.resolveState(
            pimpl_->currentState_, pimpl_->NOP);
    }
    return true;
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::fsa_, FSAFUResourceConflictDetectorPimpl::nextState_, FSAFUResourceConflictDetectorPimpl::NOP, pimpl_, FUFiniteStateAutomaton::resolveState(), FiniteStateAutomaton::transitions_, and FiniteStateAutomaton::UNKNOWN_STATE.
Referenced by advanceCycle().
initializeAllStates()
void FSAFUResourceConflictDetector::initializeAllStates ()
Initializes all states in the state machine.
By default, only the initial state is constructed and rest when visited the first time.
Definition at line 74 of file FSAFUResourceConflictDetector.cc.
{
    pimpl_->fsa_.buildStateMachine();
}
References FUFiniteStateAutomaton::buildStateMachine(), FSAFUResourceConflictDetectorPimpl::fsa_, and pimpl_.
isIdle()
bool FSAFUResourceConflictDetector::isIdle () virtual
The FSA FU model is considered to be idle when the FSA is at start state and there are no new operations issued at that state.
Reimplemented from FUResourceConflictDetector.
Definition at line 157 of file FSAFUResourceConflictDetector.cc.
{
    return pimpl_->currentState_ == pimpl_->fsa_.startState()
        && pimpl_->currentState_ == pimpl_->nextState_;
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::fsa_, FSAFUResourceConflictDetectorPimpl::nextState_, pimpl_, and FiniteStateAutomaton::startState().
issueOperation()
bool FSAFUResourceConflictDetector::issueOperation (OperationID id) virtual
Issues an operation and reports a conflict if detected.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 99 of file FSAFUResourceConflictDetector.cc.
{
    return issueOperationLazyInline(id);
}
References issueOperationLazyInline().
Referenced by FSAFUResourceConflictDetector(), and reset().
issueOperationInline()
bool FSAFUResourceConflictDetector::issueOperationInline (OperationID id)
Issues an operation and reports a conflict if detected.
Inlineable optimized version for compiled simulation and benchmarking. All states are assumed initialized. For lazily initialized FSA, use issueOperationLazyInline(). This version has about balanced runtime for conflict and no-conflict cases for sensible benchmarking with random operation sequences.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Definition at line 184 of file FSAFUResourceConflictDetector.cc.
{
    pimpl_->nextState_ = pimpl_->fsa_.transitions_[pimpl_->currentState_][id];
    if (pimpl_->nextState_ == FiniteStateAutomaton::ILLEGAL_STATE) {
        pimpl_->nextState_ = 0;
        return false;
    }
    return true;
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::fsa_, FiniteStateAutomaton::ILLEGAL_STATE, FSAFUResourceConflictDetectorPimpl::nextState_, pimpl_, and FiniteStateAutomaton::transitions_.
issueOperationLazyInline()
bool FSAFUResourceConflictDetector::issueOperationLazyInline (OperationID id)
Issues an operation and reports a conflict if detected.
Inlineable optimized version for compiled simulation and benchmarking. For lazily initialized FSA. Checks if a state is missing and constructs it if needed.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Definition at line 205 of file FSAFUResourceConflictDetector.cc.
{
    pimpl_->nextState_ = pimpl_->fsa_.transitions_[pimpl_->currentState_][id];
    if (pimpl_->nextState_ == FiniteStateAutomaton::UNKNOWN_STATE) {
        pimpl_->nextState_ = pimpl_->fsa_.resolveState(pimpl_->currentState_, id);
    }
    if (pimpl_->nextState_ == FiniteStateAutomaton::ILLEGAL_STATE) {
        pimpl_->nextState_ = 0;
        return false;
    }
    return true;
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::fsa_, FiniteStateAutomaton::ILLEGAL_STATE, FSAFUResourceConflictDetectorPimpl::nextState_, pimpl_, FUFiniteStateAutomaton::resolveState(), FiniteStateAutomaton::transitions_, and FiniteStateAutomaton::UNKNOWN_STATE.
Referenced by issueOperation().
operationID()
FSAFUResourceConflictDetector::OperationID FSAFUResourceConflictDetector::operationID (const TCEString & operationName) const virtual
Returns an operation id for the given operation.
Operation IDs are used in the interface for optimizing the access. This method converts OSAL Operations to operation IDs.
Parameters
operation The OSAL Operation to find ID for.
Returns
The operation ID.
Reimplemented from FUResourceConflictDetector.
Definition at line 134 of file FSAFUResourceConflictDetector.cc.
{
    return pimpl_->fsa_.transitionIndex(
        StringTools::stringToUpper(operationName));
}
References FSAFUResourceConflictDetectorPimpl::fsa_, operationName(), pimpl_, StringTools::stringToUpper(), and FiniteStateAutomaton::transitionIndex().
operationName()
const char * FSAFUResourceConflictDetector::operationName (OperationID id) const
Returns the name of the operation associated to the given transition id.
Parameters
id The transition id.
Returns
The name of the operation.
Definition at line 110 of file FSAFUResourceConflictDetector.cc.
{
    return pimpl_->fsa_.transitionName(id).c_str();
}
References FSAFUResourceConflictDetectorPimpl::fsa_, pimpl_, and FiniteStateAutomaton::transitionName().
Referenced by operationID().
reset()
void FSAFUResourceConflictDetector::reset () virtual
Sets the state of the detector to its initial state.
This means that the FU state is assumed to be what it is in powerup.
Reimplemented from FUResourceConflictDetector.
Definition at line 147 of file FSAFUResourceConflictDetector.cc.
{
    pimpl_->currentState_ = pimpl_->fsa_.startState();
    issueOperation(pimpl_->NOP);
}
References FSAFUResourceConflictDetectorPimpl::currentState_, FSAFUResourceConflictDetectorPimpl::fsa_, issueOperation(), FSAFUResourceConflictDetectorPimpl::NOP, pimpl_, and FiniteStateAutomaton::startState().
writeToDotFile()
void FSAFUResourceConflictDetector::writeToDotFile (const TCEString & fileName) const virtual
Writes the state machine to a Graphviz dot file.
Parameters
fileName The file name.
Definition at line 84 of file FSAFUResourceConflictDetector.cc.
{
    std::ofstream dot(fileName.c_str());
    dot << pimpl_->fsa_.toDotString() << std::endl;
    dot.close();
}
References FSAFUResourceConflictDetectorPimpl::fsa_, pimpl_, and FiniteStateAutomaton::toDotString().
Member Data Documentation
pimpl_
FSAFUResourceConflictDetectorPimpl* FSAFUResourceConflictDetector::pimpl_ private
Private implementation in a separate source file.
Definition at line 77 of file FSAFUResourceConflictDetector.hh.
Referenced by advanceCycleInline(), advanceCycleLazyInline(), FSAFUResourceConflictDetector(), initializeAllStates(), isIdle(), issueOperationInline(), issueOperationLazyInline(), operationID(), operationName(), reset(), writeToDotFile(), and ~FSAFUResourceConflictDetector().
The documentation for this class was generated from the following files:
FSAFUResourceConflictDetector.hh
FSAFUResourceConflictDetector.cc