OpenASIP: DisasmCmdLineOptions Class Reference
DisasmCmdLineOptions Class Reference
Public Member Functions
DisasmCmdLineOptions ()
std::string outputFile ()
bool outputFileDefined ()
bool printToStdout ()
void printVersion () const
virtual ~DisasmCmdLineOptions ()
DisasmCmdLineOptions ()
std::string outputFile ()
bool outputFileDefined ()
bool lineNumbers ()
bool flatFile ()
bool printToStdout ()
void printVersion () const
virtual ~DisasmCmdLineOptions ()
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Commandline options.
Definition at line 79 of file tpef2pasm.cc.
Constructor & Destructor Documentation
DisasmCmdLineOptions() [1/2]
DisasmCmdLineOptions::DisasmCmdLineOptions () inline
Definition at line 81 of file tpef2pasm.cc.
        : CmdLineOptions("Usage: tpef2pasm [options] adffile tpeffile") {
        StringCmdLineOptionParser* outputFile = new StringCmdLineOptionParser(
            "outputfile", "Name of the output file.", "o");
        BoolCmdLineOptionParser* toStdout = new BoolCmdLineOptionParser(
            "stdout", "Print to standard output", "s");
        addOption(outputFile);
        addOption(toStdout);
    }
References CmdLineParser::addOption(), and outputFile().
~DisasmCmdLineOptions() [1/2]
virtual DisasmCmdLineOptions::~DisasmCmdLineOptions () inline virtual
Definition at line 114 of file tpef2pasm.cc.
{}
DisasmCmdLineOptions() [2/2]
DisasmCmdLineOptions::DisasmCmdLineOptions () inline
Definition at line 62 of file tcedisasm.cc.
                           :
        CmdLineOptions("Usage: tcedisasm [options] adffile tpeffile") {
        StringCmdLineOptionParser* outputFile =
            new StringCmdLineOptionParser(
                "outputfile", "Name of the output file.", "o");
        BoolCmdLineOptionParser* lineNumbers =
            new BoolCmdLineOptionParser(
                "linenumbers", "Print line numbers","n");
        BoolCmdLineOptionParser* flatFile =
            new BoolCmdLineOptionParser(
                "flat", "The instructions only with file line numbers "
                "matching instruction indices","F");
        BoolCmdLineOptionParser* toStdout =
            new BoolCmdLineOptionParser(
                "stdout", "Print to standard output","s");
        addOption(lineNumbers);
        addOption(outputFile);
        addOption(flatFile);
        addOption(toStdout);
    }
References CmdLineParser::addOption(), flatFile(), lineNumbers(), and outputFile().
~DisasmCmdLineOptions() [2/2]
virtual DisasmCmdLineOptions::~DisasmCmdLineOptions () inline virtual
Definition at line 113 of file tcedisasm.cc.
{
    }
Member Function Documentation
flatFile()
bool DisasmCmdLineOptions::flatFile () inline
Definition at line 100 of file tcedisasm.cc.
                    {
        return findOption("flat")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DisasmCmdLineOptions().
lineNumbers()
bool DisasmCmdLineOptions::lineNumbers () inline
Definition at line 96 of file tcedisasm.cc.
                       {
        return findOption("linenumbers")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DisasmCmdLineOptions().
outputFile() [1/2]
std::string DisasmCmdLineOptions::outputFile () inline
Definition at line 94 of file tpef2pasm.cc.
                 {
        return findOption("outputfile")->String();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by DisasmCmdLineOptions().
outputFile() [2/2]
std::string DisasmCmdLineOptions::outputFile () inline
Definition at line 88 of file tcedisasm.cc.
{
        return findOption("outputfile")->String();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::String().
outputFileDefined() [1/2]
bool DisasmCmdLineOptions::outputFileDefined () inline
Definition at line 99 of file tpef2pasm.cc.
{
        return findOption("outputfile")->isDefined();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
outputFileDefined() [2/2]
bool DisasmCmdLineOptions::outputFileDefined () inline
Definition at line 92 of file tcedisasm.cc.
{
        return findOption("outputfile")->isDefined();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isDefined().
printToStdout() [1/2]
bool DisasmCmdLineOptions::printToStdout () inline
Definition at line 104 of file tpef2pasm.cc.
                    {
        return findOption("stdout")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
printToStdout() [2/2]
bool DisasmCmdLineOptions::printToStdout () inline
Definition at line 104 of file tcedisasm.cc.
{
        return findOption("stdout")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
printVersion() [1/2]
void DisasmCmdLineOptions::printVersion () const inline virtual
Implements CmdLineOptions.
Definition at line 109 of file tpef2pasm.cc.
{
        std::cout << "tcedisasm - OpenASIP TTA parallel disassembler "
                  << Application::TCEVersionString() << std::endl;
    }
References Application::TCEVersionString().
printVersion() [2/2]
void DisasmCmdLineOptions::printVersion () const inline virtual
Implements CmdLineOptions.
Definition at line 108 of file tcedisasm.cc.
{
        std::cout << "tcedisasm - OpenASIP TTA parallel disassembler "
                  << Application::TCEVersionString() << std::endl;
    }
References Application::TCEVersionString().
The documentation for this class was generated from the following files:
tpef2pasm.cc
tcedisasm.cc