OpenASIP: InfoPortsCommand Class Reference
InfoPortsCommand Class Reference
Public Member Functions
InfoPortsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoPortsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info ports".
Definition at line 501 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoPortsCommand()
InfoPortsCommand::InfoPortsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 506 of file InfoCommand.cc.
                                                               :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoPortsCommand()
virtual InfoPortsCommand::~InfoPortsCommand () inline virtual
Destructor.
Definition at line 513 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoPortsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info ports" command.
"info ports" prints info of FU ports.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 524 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkMachineLoaded()) {
            return false;
        }
        if (!parent().checkArgumentCount(argumentCount, 1, 2)) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        const std::string functionUnit = arguments.at(2).stringValue();
        const TTAMachine::Machine::FunctionUnitNavigator nav =
            mach.functionUnitNavigator();
        TTAMachine::FunctionUnit* fu = NULL;
        if (nav.hasItem(functionUnit)) {
            fu = nav.item(functionUnit);
        } else if (functionUnit == mach.controlUnit()->name()) {
            fu = mach.controlUnit();
        }
        if (fu == NULL) {
            parent().interpreter()->setError(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_FU_NOT_FOUND).str());
            return false;
        }
        if (argumentCount == 1) {
            std::string result = "";
            bool isFirst = true;
            for (int i = 0; i < fu->portCount(); ++i) {
                if (!isFirst)
                    result += "\n";
                std::string portName = fu->port(i)->name();
                DisassemblyFUPort portString(functionUnit, portName);
                SimValue portValue = parent().simulatorFrontend().FUPortValue(
                    functionUnit, portName);
                result += InfoRegistersCommand::registerDescription(
                    portString.toString(), portValue);
                isFirst = false;
            }
            parent().interpreter()->setResult(result);
            return true;
        } else if (argumentCount == 2) {
            const std::string portName = arguments.at(3).stringValue();
            try {
                // @todo printing of double values (size > 32)
                SimValue portValue = parent().simulatorFrontend().FUPortValue(
                    functionUnit, portName);
                parent().interpreter()->setResult(portValue.intValue());
                return true;
            } catch (const Exception& e) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_FUPORT_NOT_FOUND).str());
                return false;
            }
        }
        return false;
    }
References TTAMachine::Machine::controlUnit(), TTAMachine::Machine::functionUnitNavigator(), SimulatorFrontend::FUPortValue(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), CustomCommand::interpreter(), SimValue::intValue(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::Component::name(), TTAMachine::Port::name(), SimControlLanguageSubCommand::parent(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), InfoRegistersCommand::registerDescription(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), SimulatorToolbox::textGenerator(), DisassemblyFUPort::toString(), Texts::TXT_FU_NOT_FOUND, and Texts::TXT_FUPORT_NOT_FOUND.
The documentation for this class was generated from the following file:
InfoCommand.cc