OpenASIP: OSEdBuildAllCmd Class Reference
OSEdBuildAllCmd Class Reference
#include <OSEdBuildAllCmd.hh>
Public Member Functions
OSEdBuildAllCmd ()
virtual ~OSEdBuildAllCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdBuildAllCmd (const OSEdBuildAllCmd &)
Copying not allowed.
OSEdBuildAllCmd & operator= (const OSEdBuildAllCmd &)
Assignment not allowed.
Detailed Description
Command that build all modules.
Definition at line 43 of file OSEdBuildAllCmd.hh.
Constructor & Destructor Documentation
OSEdBuildAllCmd() [1/2]
OSEdBuildAllCmd::OSEdBuildAllCmd ()
Constructor.
Definition at line 57 of file OSEdBuildAllCmd.cc.
                                 :
    GUICommand(OSEdConstants::CMD_NAME_BUILD_ALL, NULL) {
}
Referenced by create().
~OSEdBuildAllCmd()
OSEdBuildAllCmd::~OSEdBuildAllCmd () virtual
Destructor.
Definition at line 64 of file OSEdBuildAllCmd.cc.
{
}
OSEdBuildAllCmd() [2/2]
OSEdBuildAllCmd::OSEdBuildAllCmd (const OSEdBuildAllCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdBuildAllCmd::create () const virtual
Returns a new command.
Returns
A new command.
Implements GUICommand.
Definition at line 83 of file OSEdBuildAllCmd.cc.
{
    return new OSEdBuildAllCmd();
}
References OSEdBuildAllCmd().
Do()
bool OSEdBuildAllCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 93 of file OSEdBuildAllCmd.cc.
                    {
    wxWindow* simulateDialog =
        wxGetApp().mainFrame()->FindWindowByName(SimulateDialog::DIALOG_NAME);
    if (simulateDialog != NULL) {
        simulateDialog->Close();
    }
    OperationIndex& index = OperationContainer::operationIndex();
    OperationBuilder& builder = OperationBuilder::instance();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    wxStatusBar* statusBar = wxGetApp().mainFrame()->statusBar();
    vector<OperationModule> buildModules;
    vector<string> paths;
    for (int i = 0; i < index.pathCount(); i++) {
        string path = index.path(i);
        for (int k = 0; k < index.moduleCount(path); k++) {
            OperationModule& module = index.module(k, path);
            if (module.hasBehaviorSource()) {
                buildModules.push_back(module);
                paths.push_back(path);
            }
        }
    }
    vector<string> output;
    wxStopWatch sw;
    sw.Pause();
    wxBusyCursor* busy = new wxBusyCursor();
    bool compileOk = true;
    for (size_t i = 0; i < buildModules.size(); i++) {
        OperationModule module = buildModules[i];
        string path = paths[i];
        output.push_back(module.name() + ":\n");
        size_t oldSize = output.size();
        sw.Resume();
        builder.buildObject(module.name(),
                            module.behaviorSourceModule(),
                            path, output);
        sw.Pause();
        if (oldSize != output.size()) {
            compileOk = false;
        }
        output.push_back("\n");
    }
    delete busy;
    if (!compileOk) {
        format fmt = texts.text(OSEdTextGenerator::TXT_STATUS_COMPILE_FAILED);
        statusBar->SetStatusText(WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_BUILD_RESULT_DIALOG_TITLE);
        ResultDialog dialog(parentWindow(), output, fmt.str());
        dialog.ShowModal();
    } else {
        format fmt = texts.text(OSEdTextGenerator::TXT_STATUS_COMPILE_SUCCESS);
        fmt % sw.Time();
        statusBar->SetStatusText(WxConversion::toWxString(fmt.str()));
    }
    return true;
}
References OperationBuilder::buildObject(), SimulateDialog::DIALOG_NAME, OperationBuilder::instance(), OSEdTextGenerator::instance(), OperationIndex::moduleCount(), OperationContainer::operationIndex(), GUICommand::parentWindow(), OperationIndex::path(), OperationIndex::pathCount(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUILD_RESULT_DIALOG_TITLE, OSEdTextGenerator::TXT_STATUS_COMPILE_FAILED, and OSEdTextGenerator::TXT_STATUS_COMPILE_SUCCESS.
icon()
string OSEdBuildAllCmd::icon () const virtual
Returns icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 186 of file OSEdBuildAllCmd.cc.
{
    return "";
}
id()
int OSEdBuildAllCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 73 of file OSEdBuildAllCmd.cc.
{
    return OSEdConstants::CMD_BUILD_ALL;
}
References OSEdConstants::CMD_BUILD_ALL.
isEnabled()
bool OSEdBuildAllCmd::isEnabled () virtual
Returns true if command is enabled.
Command is enabled, if at least one module has behavior source file.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 169 of file OSEdBuildAllCmd.cc.
{
    OperationIndex& index = OperationContainer::operationIndex();
    for (int i = 0; i < index.moduleCount(); i++) {
        OperationModule& module = index.module(i);
        if (module.hasBehaviorSource()) {
            return true;
        }
    }
    return false;
}
References OperationIndex::moduleCount(), and OperationContainer::operationIndex().
operator=()
OSEdBuildAllCmd & OSEdBuildAllCmd::operator= (const OSEdBuildAllCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdBuildAllCmd.hh
OSEdBuildAllCmd.cc