OpenASIP: RLPriorityNodeId Class Reference
RLPriorityNodeId Class Reference
#include <NodeIdCompList.hh>
Public Member Functions
bool operator() (MoveNodeGroup &a, MoveNodeGroup &b)
Detailed Description
A function object for prioritizing the ready list according to the move's node id. stupid but working order.
Definition at line 49 of file NodeIdCompList.hh.
Member Function Documentation
operator()()
bool RLPriorityNodeId::operator() (MoveNodeGroup & a, MoveNodeGroup & b) inline
Compares two nodes according to their priority in the ready list.
Parameters
a Node a.
b Node b.
Returns
True if b should be scheduled before a (b greater than a).
Definition at line 59 of file NodeIdCompList.hh.
{
        if (b.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return true;
        }
        if (a.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return false;
        }
        return b.node(0).nodeID() < a.node(0).nodeID();
    }
References MoveNodeGroup::isScheduled(), MoveNodeGroup::node(), and GraphNode::nodeID().
The documentation for this class was generated from the following file:
NodeIdCompList.hh