OpenASIP: ReadableState Class Reference
ReadableState Class Reference abstract
#include <ReadableState.hh>
Public Member Functions
ReadableState ()
virtual ~ReadableState ()
virtual const SimValue & value () const =0
Private Member Functions
ReadableState (const ReadableState &)
Copying not allowed.
ReadableState & operator= (const ReadableState &)
Assignment not allowed.
Detailed Description
Models a piece of machine state model that can be read.
Definition at line 41 of file ReadableState.hh.
Constructor & Destructor Documentation
ReadableState() [1/2]
ReadableState::ReadableState ()
Constructor.
Definition at line 38 of file ReadableState.cc.
{
}
~ReadableState()
ReadableState::~ReadableState () virtual
Destructor.
Definition at line 44 of file ReadableState.cc.
{
}
ReadableState() [2/2]
ReadableState::ReadableState (const ReadableState &) private
Copying not allowed.
Member Function Documentation
operator=()
ReadableState & ReadableState::operator= (const ReadableState &) private
Assignment not allowed.
value()
virtual const SimValue & ReadableState::value () const pure virtual
Implemented in NullBusState, GuardState, DirectGuardState, LongImmediateRegisterState, OpcodeSettingVirtualInputPortState, NullPortState, RegisterState, and NullRegisterState.
Referenced by GuardState::advanceClock(), ExecutableMove::evaluateGuard(), InfoRegistersCommand::execute(), ExecutableMove::executeRead(), BuslessExecutableMove::executeWrite(), GuardState::GuardState(), SimulationController::registerFileValue(), SimulatorFrontend::stateValue(), and DirectGuardState::value().
The documentation for this class was generated from the following files:
ReadableState.hh
ReadableState.cc