OpenASIP: MapTools Class Reference
MapTools Class Reference
#include <MapTools.hh>
Static Public Member Functions
template<typename MapType , typename ValueType >
static bool containsValue (const MapType &aMap, const ValueType &aValue)
template<typename MapType , typename KeyType >
static bool containsKey (const MapType &aMap, const KeyType &aKey)
template<typename KeyType , typename MapType , typename ValueType >
static KeyType keyForValue (const MapType &aMap, const ValueType &aValue)
template<typename ValueType , typename MapType , typename KeyType >
static ValueType valueForKey (const MapType &aMap, const KeyType &aKey)
template<typename ValueType , typename MapType , typename KeyType >
static const ValueType valueForKeyNoThrow (const MapType &aMap, const KeyType &aKey)
template<typename MapType >
static void deleteAllValues (MapType &aMap)
template<typename MapType >
static void deleteAllKeys (MapType &aMap)
template<typename MapType , typename KeyType >
static void deleteByKey (MapType &aMap, const KeyType &aKey)
template<typename MapType , typename ValueType >
static bool removeItemsByValue (MapType &aMap, const ValueType &aValue)
template<typename KeyType , typename MapType >
static std::set< KeyType > keys (const MapType &aMap)
Detailed Description
Definition at line 42 of file MapTools.hh.
Member Function Documentation
containsKey()
template<typename MapType , typename KeyType > static bool MapTools::containsKey (const MapType & aMap, const KeyType & aKey) static
Referenced by LImmDstRegisterField::addDestination(), ControlFlowGraph::addExit(), ProgramOperation::addInputNode(), LabelManager::addLabel(), InstructionFormat::addOperation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), ProgramOperation::addOutputNode(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), LabelManager::addProcedure(), BEMGenerator::addRiscvFormat(), InstructionDictionary::addToDictionary(), MoveSlotDictionary::addToDictionary(), LabelManager::aSpaceElement(), ITemplateResource::assign(), ITemplateBroker::assign(), ITemplateBroker::assignImmediate(), BEMGenerator::assignSocketCodeTable(), TPEF::RawSection::belongsToSection(), CodeCompressorPlugin::bemInstructionBits(), llvm::LLVMTCEIRBuilder::buildTCECFG(), TTAProgram::TPEFResourceUpdater::bus(), DefaultICGenerator::busAltSignal(), UtilizationStats::busWrites(), TTAProgram::TPEFProgramFactory::canDestinationBeAssigned(), TTAProgram::TPEFProgramFactory::canSourceBeAssigned(), TPEF::RawSection::chunk(), BUBasicBlockScheduler::clearRemovedNodes(), ControlDependenceGraph::computeDependence(), ProgramDependenceGraph::copyRegionEECComponent(), TTAProgram::ProgramWriter::createASpaceElement(), ControlFlowGraph::createBBEdges(), ControlFlowGraph::createBlock(), ControlFlowGraph::createControlFlowEdge(), TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::Section::createSection(), TTAProgram::TPEFProgramFactory::createTerminal(), ScriptInterpreter::customCommand(), llvm::LLVMTCEBuilder::dataEnd(), llvm::LLVMTCEBuilder::dataMemoryForAddressSpace(), InterPassData::datum(), ProGe::Netlist::descriptor(), ControlDependenceGraph::detectControlDependencies(), ControlFlowGraph::directJump(), CodeCompressorPlugin::encodeLongImmediate(), InstructionFormat::encoding(), TPEF::AOutSymbolSectionReader::finalize(), BUBasicBlockScheduler::finalizeSchedule(), RISCVTDGen::findCustomOps(), MachineResourceManager::findDataAddressSpace(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), ITemplateBroker::findITemplates(), TPEF::SectionReader::findSectionReader(), TPEF::SectionWriter::findSectionWriter(), InstructionBitVector::fixInstructionAddress(), TTAProgram::TPEFProgramFactory::functionName(), TTAProgram::TPEFResourceUpdater::functionUnit(), MachineResourceManager::functionUnitID(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFProgramFactory::getFromCache(), ControlFlowGraph::getMBB(), SOPCBuilderFileGenerator::handleAvalonSignal(), InterPassData::hasDatum(), ProGe::NetlistGenerator::hasGlockPort(), ProGe::NetlistGenerator::hasGlockReqPort(), ProgramOperation::hasInputNode(), HDB::FUImplementation::hasOpcode(), ProGe::NetlistGenerator::hasOpcodePort(), InstructionFormat::hasOperation(), ProgramOperation::hasOutputNode(), ProGe::ICDecoderGeneratorPlugin::hasParameterSet(), TPEF::TPEFTools::hasRelocation(), ResourceBroker::hasResourceOf(), ImmediateControlField::hasTemplateEncoding(), TTAProgram::TPEFResourceUpdater::immediateUnit(), IUBroker::immediateValue(), IUBroker::immediateWriteCycle(), InstructionBitVector::indexBounds(), ControlFlowGraph::indirectJump(), ProGe::RV32MicroCodeGenerator::initializeOperations(), TPEF::AOutSymbolSectionReader::initializeSymbol(), ITemplateBroker::instruction(), InputPSocketBroker::isAlreadyAssigned(), BusBroker::isAlreadyAssigned(), InputFUBroker::isAlreadyAssigned(), ITemplateBroker::isAlreadyAssigned(), IUBroker::isAlreadyAssigned(), OutputFUBroker::isAlreadyAssigned(), OutputPSocketBroker::isAlreadyAssigned(), TTAMachine::HWOperation::isBound(), ProgramOperation::isComplete(), TTAProgram::TPEFProgramFactory::isFunctionStart(), ITemplateBroker::isImmediateInTemplate(), TPEF::CodeSection::isInSection(), ITemplateResource::isInUse(), ProgramOperation::isReady(), TPEF::ReferenceManager::SafePointer::isReferenced(), ProGe::Netlist::isRegistered(), PluginTools::loadSym(), CentralizedControlICGenerator::mapBusCntrlPortOfSocket(), ProGe::NetlistGenerator::mapClockPort(), CentralizedControlICGenerator::mapDataCntrlPortOfSocket(), ProGe::NetlistGenerator::mapFUGuardPort(), ProGe::NetlistGenerator::mapFUOpcodePort(), ProGe::NetlistGenerator::mapGlobalLockPort(), ProGe::NetlistGenerator::mapGlobalLockRequestPort(), ProGe::NetlistGenerator::mapLoadPort(), ProGe::NetlistGenerator::mapNetlistBlock(), ProGe::NetlistGenerator::mapResetPort(), ProGe::NetlistGenerator::mapRFGuardPort(), ProGe::NetlistGenerator::mapRFOpcodePort(), CentralizedControlICGenerator::mapSImmCntrlPort(), CentralizedControlICGenerator::mapSImmDataPort(), CodeCompressorPlugin::memoryAddress(), TPEF::ReferenceManager::SafePointer::notifyDeleted(), TTAProgram::TPEFResourceUpdater::operand(), UtilizationStats::operationExecutions(), MachineResourceManager::opOrPortID(), ProgramOperation::outputNode(), ProgramDependenceGraph::ProgramDependenceGraph(), InstructionBitVector::pushBack(), TTAProgram::TPEFResourceUpdater::registerFile(), MachineResourceManager::registerFileID(), PluginTools::registerModule(), ProGe::Netlist::registerPort(), TPEF::Section::registerSection(), TPEF::SectionReader::registerSectionReader(), TPEF::SectionWriter::registerSectionWriter(), CycleLookBackSoftwareBypasser::removeBypass(), ScriptInterpreter::removeCustomCommand(), InterPassData::removeDatum(), CycleLookBackSoftwareBypasser::removeDeadResults(), ProgramOperation::removeInputNode(), LabelManager::removeLabel(), ProgramOperation::removeOutputNode(), Texts::TextGenerator::replaceText(), TPEF::ReferenceManager::SafePointer::resolve(), DataSectionCreator::resolveDataAreaSizesAndLabelAddresses(), MachineResourceManager::resourceID(), SequentialScheduler::scheduleInputOperandTempMoves(), SequentialScheduler::scheduleResultTempMoves(), SequentialScheduler::scheduleRRTempMoves(), HDBBrowserWindow::selectBusEntry(), HDBBrowserWindow::selectCostFunctionPlugin(), HDBBrowserWindow::selectFUArchitecture(), HDBBrowserWindow::selectFUEntry(), HDBBrowserWindow::selectFUImplementation(), HDBBrowserWindow::selectRFArchitecture(), HDBBrowserWindow::selectRFEntry(), HDBBrowserWindow::selectRFImplementation(), HDBBrowserWindow::selectSocketEntry(), InterPassData::setDatum(), ExecutionPipelineResourceTable::setLatency(), ProGe::ICDecoderGeneratorPlugin::setParameter(), ExecutionPipelineResourceTable::setResourceUse(), BEMGenerator::socketCodeTable(), UtilizationStats::socketWrites(), Texts::TextGenerator::text(), UtilizationStats::triggerCount(), TPEF::SectionSizeReplacer::tryToReplace(), BusBroker::unassign(), InputFUBroker::unassign(), InputPSocketBroker::unassign(), ITemplateBroker::unassign(), IUBroker::unassign(), OutputFUBroker::unassign(), OutputPSocketBroker::unassign(), SimpleBrokerDirector::unassign(), ITemplateBroker::unassignImmediate(), ExecutionPipelineResource::unassignSource(), BUBasicBlockScheduler::undoBypass(), ProGe::Netlist::unregisterPort(), BasicBlockScheduler::unscheduleInputOperandTempMoves(), SequentialScheduler::unscheduleInputOperandTempMoves(), BasicBlockScheduler::unscheduleResultReadTempMoves(), LImmDstRegisterField::usedByInstructionTemplate(), LabelManager::value(), DefaultDecoderGenerator::writeGlockMapping(), and llvm::LLVMTCEBuilder::writeMachineFunction().
containsValue()
template<typename MapType , typename ValueType > static bool MapTools::containsValue (const MapType & aMap, const ValueType & aValue) static
Referenced by ProGe::RV32MicroCodeGenerator::addRPorts(), ImmediateControlField::addTemplateEncoding(), TTAMachine::HWOperation::bindPort(), llvm::GeneratedTCEPlugin::hasOperation(), ResourceBroker::hasResource(), TTAMachine::HWOperation::isBound(), HDBBrowserWindow::isBusEntrySelected(), HDBBrowserWindow::isCostFunctionPluginSelected(), HDBBrowserWindow::isFUArchitectureSelected(), HDBBrowserWindow::isFUEntrySelected(), HDBBrowserWindow::isFUImplementationSelected(), OSEdTreeView::isModule(), OSEdTreeView::isModuleSelected(), OSEdTreeView::isOperation(), OSEdTreeView::isOperationSelected(), OSEdTreeView::isPath(), OSEdTreeView::isPathSelected(), HDBBrowserWindow::isRFArchitectureSelected(), HDBBrowserWindow::isRFEntrySelected(), HDBBrowserWindow::isRFImplementationSelected(), HDBBrowserWindow::isSocketEntrySelected(), TPEF::ReferenceManager::SafePointer::notifyDeleted(), OSEdTreeView::selectedModuleId(), OTAOperationDialog::TransferDataToWindow(), ExecutionPipelineResource::unassignDestination(), and ExecutionPipelineResource::unassignSource().
deleteAllKeys()
template<typename MapType > static void MapTools::deleteAllKeys (MapType & aMap) static
Referenced by ControlDependenceGraph::computeDependence(), and ConfigurationFile::~ConfigurationFile().
deleteAllValues()
template<typename MapType > static void MapTools::deleteAllValues (MapType & aMap) static
Referenced by LabelManager::cleanup(), TPEF::ReferenceManager::SafePointer::cleanup(), MachineState::clear(), ControlDependenceGraph::computeDependence(), ExecutionPipelineResourceTable::finalize(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), AddFUFromHDBDialog::TransferDataToWindow(), AddIUFromHDBDialog::TransferDataToWindow(), AddRFFromHDBDialog::TransferDataToWindow(), HDB::CachedHDBManager::validateCache(), AddFUFromHDBDialog::~AddFUFromHDBDialog(), AddIUFromHDBDialog::~AddIUFromHDBDialog(), HDB::CachedHDBManager::~CachedHDBManager(), TTAProgram::DataMemory::~DataMemory(), InfoCommand::~InfoCommand(), InterPassData::~InterPassData(), LabelManager::~LabelManager(), ProGe::NetlistGenerator::~NetlistGenerator(), TPEF::RawSection::~RawSection(), ResourceBroker::~ResourceBroker(), ScriptInterpreter::~ScriptInterpreter(), SettingCommand::~SettingCommand(), SimpleBrokerDirector::~SimpleBrokerDirector(), SOPCBuilderFileGenerator::~SOPCBuilderFileGenerator(), StopPointManager::~StopPointManager(), and TTAProgram::TPEFProgramFactory::~TPEFProgramFactory().
deleteByKey()
template<typename MapType , typename KeyType > static void MapTools::deleteByKey (MapType & aMap, const KeyType & aKey) static
Referenced by CompiledSimSettingCommand::CompiledSimSettingCommand().
keyForValue()
template<typename KeyType , typename MapType , typename ValueType > static KeyType MapTools::keyForValue (const MapType & aMap, const ValueType & aValue) static
Referenced by LImmDstRegisterField::addDestination(), HDB::HDBManager::addFUArchitecture(), ProgramOperation::addInputNode(), InstructionDictionary::addInstructions(), MoveSlotDictionary::addInstructions(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), Options::addOptionValue(), ProgramOperation::addOutputNode(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), ProGe::RV32MicroCodeGenerator::addRPorts(), ImmediateControlField::addTemplateEncoding(), ITemplateBroker::assign(), ITemplateBroker::assignImmediate(), CentralizedControlICGenerator::busCntrlPortOfSocket(), UtilizationStats::busWrites(), OSEdTreeView::changeText(), ProGe::NetlistGenerator::clkPort(), ControlDependenceGraph::computeEECInfo(), ProgramDependenceGraph::computeEECInfo(), ControlDependenceGraph::computeRegionInfo(), ProgramDependenceGraph::computeRegionInfo(), ControlDependenceGraph::computeRelations(), ProgramDependenceGraph::computeRelations(), RFAccessTracker::concurrentRegisterFileAccessCount(), ProgramDependenceGraph::copyRegionEECComponent(), ControlFlowGraph::createAllBlocks(), TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createTerminal(), CentralizedControlICGenerator::dataCntrlPortOfSocket(), ProGe::Netlist::descriptor(), ControlDependenceGraph::detectControlDependencies(), ControlDependenceGraph::detectStrongComponents(), ProgramDependenceGraph::detectStrongComponents(), CodeCompressorPlugin::encodeLongImmediate(), ITemplateBroker::findITemplates(), ProGe::NetlistGenerator::fuEntry(), UtilizationStats::FUGuardAccesses(), ProGe::NetlistGenerator::fuGuardPort(), TTAProgram::TPEFProgramFactory::functionName(), ProGe::NetlistGenerator::fuOpcodePort(), InstructionDictionary::generateDecompressor(), MoveSlotDictionary::generateDictionaryVhdl(), TTAProgram::TPEFProgramFactory::getFromCache(), ProGe::NetlistGenerator::glockPort(), ProGe::NetlistGenerator::glockReqPort(), UtilizationStats::guardRegisterReads(), ExecutionPipelineResource::hasConflictingResultsOnCycle(), ExecutionPipelineResource::highestKnownCycle(), LImmDstRegisterField::immediateUnit(), ProGe::NetlistGenerator::immediateUnitWritePort(), IUBroker::immediateValue(), IUBroker::immediateWriteCycle(), InstructionBitVector::indexBounds(), TPEF::CodeSection::indexOfElement(), TPEF::CodeSection::indexOfInstruction(), ITemplateBroker::instruction(), TTAMachine::HWOperation::io(), IUBroker::isAlreadyAssigned(), ITemplateBroker::isImmediateInTemplate(), ExecutionPipelineResource::isInUse(), ITemplateResource::isInUse(), HDB::HDBManager::isMatchingArchitecture(), ProGe::NetlistGenerator::loadPort(), ResourceBroker::machinePartOf(), CodeCompressorPlugin::memoryAddress(), OSEdTreeView::moduleOfOperation(), ProGe::NetlistGenerator::netlistBlock(), ProGe::NetlistGenerator::netlistPort(), ExecutionPipelineResource::nextResultCycle(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), OSEdTreeView::onItemSelected(), HDB::FUImplementation::opcode(), llvm::GeneratedTCEPlugin::opcode(), UtilizationStats::operationExecutions(), UtilizationStats::operationExecutions(), HDB::FUArchitecture::operator==(), Options::optionValue(), ProgramOperation::outputNode(), ProGe::ICDecoderGeneratorPlugin::parameterDescription(), ProGe::ICDecoderGeneratorPlugin::parameterValue(), OSEdTreeView::pathOfModule(), ProgramDependenceGraph::ProgramDependenceGraph(), InstructionBitVector::pushBack(), UtilizationStats::registerReads(), UtilizationStats::registerWrites(), TPEF::TPEFTools::relocation(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), ProgramDependenceGraph::removeGuardedJump(), ProgramOperation::removeInputNode(), OSEdTreeView::removeItem(), ProgramOperation::removeOutputNode(), ExecutionPipelineResource::resultAllowedAtCycle(), ProGe::NetlistGenerator::rfEntry(), ProGe::NetlistGenerator::rfGuardPort(), ProGe::NetlistGenerator::rfOpcodePort(), ProGe::NetlistGenerator::rstPort(), HDBBrowserWindow::selectedBusEntry(), HDBBrowserWindow::selectedCostFunctionPlugin(), HDBBrowserWindow::selectedFUArchitecture(), HDBBrowserWindow::selectedFUEntry(), HDBBrowserWindow::selectedFUImplementation(), HDBBrowserWindow::selectedRFArchitecture(), HDBBrowserWindow::selectedRFEntry(), HDBBrowserWindow::selectedRFImplementation(), HDBBrowserWindow::selectedSocketEntry(), ExecutionPipelineResourceTable::setLatency(), ExecutionPipelineResourceTable::setResourceUse(), ExecutionPipelineBroker::setupResourceLinks(), CentralizedControlICGenerator::simmCntrlPort(), CentralizedControlICGenerator::simmDataPort(), BEMGenerator::socketCodeTable(), UtilizationStats::socketWrites(), UtilizationStats::triggerCount(), InputPSocketBroker::unassign(), ITemplateBroker::unassign(), IUBroker::unassign(), OutputPSocketBroker::unassign(), SimpleBrokerDirector::unassign(), ITemplateBroker::unassignImmediate(), ExecutionPipelineResource::unassignSource(), and Options::valueCount().
keys()
template<typename KeyType , typename MapType > static std::set< KeyType > MapTools::keys (const MapType & aMap) static
removeItemsByValue()
template<typename MapType , typename ValueType > static bool MapTools::removeItemsByValue (MapType & aMap, const ValueType & aValue) static
Referenced by ExecutionPipelineResource::unassignDestination(), ExecutionPipelineResource::unassignSource(), and TTAMachine::HWOperation::unbindPort().
valueForKey()
template<typename ValueType , typename MapType , typename KeyType > static ValueType MapTools::valueForKey (const MapType & aMap, const KeyType & aKey) static
Referenced by CodeCompressorPlugin::bemInstructionBits(), UtilizationStats::guardRegisterReads(), UtilizationStats::registerReads(), and UtilizationStats::registerWrites().
valueForKeyNoThrow()
template<typename ValueType , typename MapType , typename KeyType > static const ValueType MapTools::valueForKeyNoThrow (const MapType & aMap, const KeyType & aKey) static
The documentation for this class was generated from the following file:
MapTools.hh