OpenASIP: EntryKeyDataDouble Class Reference
EntryKeyDataDouble Class Reference
#include <EntryKeyData.hh>
Public Member Functions
EntryKeyDataDouble ()
EntryKeyDataDouble (double fieldData)
virtual ~EntryKeyDataDouble ()
EntryKeyData * copy () const
bool isEqual (const EntryKeyData *fieldData) const
bool isGreater (const EntryKeyData *fieldData) const
bool isSmaller (const EntryKeyData *fieldData) const
double coefficient (const EntryKeyData *data1, const EntryKeyData *data2) const
std::string toString () const
Public Member Functions inherited from EntryKeyData
EntryKeyData ()
virtual ~EntryKeyData ()
Private Member Functions
EntryKeyDataDouble (const EntryKeyDataDouble &)
Copying not allowed.
EntryKeyDataDouble & operator= (const EntryKeyDataDouble &)
Assignment not allowed.
Private Attributes
double data_
Double data.
Detailed Description
Implementation for double type of data.
Definition at line 111 of file EntryKeyData.hh.
Constructor & Destructor Documentation
EntryKeyDataDouble() [1/3]
EntryKeyDataDouble::EntryKeyDataDouble ()
Default constructor.
Definition at line 216 of file EntryKeyData.cc.
                                       : data_(0) {
}
Referenced by copy().
EntryKeyDataDouble() [2/3]
EntryKeyDataDouble::EntryKeyDataDouble (double fieldData)
Constructor.
Parameters
fieldData A double.
Definition at line 224 of file EntryKeyData.cc.
                                                       : data_(fieldData) {
}
~EntryKeyDataDouble()
EntryKeyDataDouble::~EntryKeyDataDouble () virtual
Destructor.
Definition at line 230 of file EntryKeyData.cc.
{
}
EntryKeyDataDouble() [3/3]
EntryKeyDataDouble::EntryKeyDataDouble (const EntryKeyDataDouble &) private
Copying not allowed.
Member Function Documentation
coefficient()
double EntryKeyDataDouble::coefficient (const EntryKeyData * data1, const EntryKeyData * data2) const virtual
Returns the relative position between two doubles.
Returns the double's relative position to the first double compared to the second. For example, if this double is 14, the first double is 10 and the second 20, relative position would be 0.4.
Parameters
data1 First double.
data2 Second double.
Returns
The relative position between two doubles.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 322 of file EntryKeyData.cc.
{
    EntryKeyDataDouble* double1 = dynamic_cast<EntryKeyDataDouble*>(
        const_cast<EntryKeyData*>(data1));
    EntryKeyDataDouble* double2 = dynamic_cast<EntryKeyDataDouble*>(
        const_cast<EntryKeyData*>(data2));
    if (double1 == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataDouble::coefficient param1");
    }
    if(double2 == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataDouble::coefficient param2");
    }
    return (data_ - double1->data_) / (double2->data_ - double1->data_);
}
References data_.
copy()
EntryKeyData * EntryKeyDataDouble::copy () const virtual
Copies the double.
Client is responsible of deallocating the memory reserved for the returned object.
Returns
A copy of the double.
Implements EntryKeyData.
Definition at line 242 of file EntryKeyData.cc.
{
    return new EntryKeyDataDouble(data_);
}
References data_, and EntryKeyDataDouble().
isEqual()
bool EntryKeyDataDouble::isEqual (const EntryKeyData * fieldData) const virtual
Checks if two doubles are equal.
Cannot compare double to other data types.
Parameters
fieldData A double.
Returns
True if two doubles are equal.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 256 of file EntryKeyData.cc.
{
    EntryKeyDataDouble* data = dynamic_cast<EntryKeyDataDouble*>(
        const_cast<EntryKeyData*>(fieldData));
    if (data == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataDouble::isEqual");
    }
    return data_ == data->data_;
}
References data_.
isGreater()
bool EntryKeyDataDouble::isGreater (const EntryKeyData * fieldData) const virtual
Checks if another double is greater.
Cannot compare double to other data types.
Parameters
fieldData A double.
Returns
True if this double is greater than another double, otherwise false.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 277 of file EntryKeyData.cc.
{
    EntryKeyDataDouble* data = dynamic_cast<EntryKeyDataDouble*>(
        const_cast<EntryKeyData*>(fieldData));
    if (data == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataDouble::isGreater");
    }
    return data_ > data->data_;
}
References data_.
isSmaller()
bool EntryKeyDataDouble::isSmaller (const EntryKeyData * fieldData) const virtual
Checks if this double is smaller than another double.
Cannot compare double to other data types.
Parameters
fieldData A double.
Returns
True if this double is smaller than another double, otherwise false.
Exceptions
WrongSubclass Given data type was illegal.
Implements EntryKeyData.
Definition at line 298 of file EntryKeyData.cc.
{
    EntryKeyDataDouble* data = dynamic_cast<EntryKeyDataDouble*>(
        const_cast<EntryKeyData*>(fieldData));
    if (data == NULL) {
        throw WrongSubclass(__FILE__, __LINE__,
                            "EntryKeyDataDouble::isSmaller");
    }
    return data_ < data->data_;
}
References data_.
operator=()
EntryKeyDataDouble & EntryKeyDataDouble::operator= (const EntryKeyDataDouble &) private
Assignment not allowed.
toString()
std::string EntryKeyDataDouble::toString () const virtual
Converts the double into a string.
Returns
Double as a string.
Implements EntryKeyData.
Definition at line 346 of file EntryKeyData.cc.
{
    return Conversion::toString(data_);
}
References data_, and Conversion::toString().
Member Data Documentation
data_
double EntryKeyDataDouble::data_ private
Double data.
Definition at line 127 of file EntryKeyData.hh.
Referenced by coefficient(), copy(), isEqual(), isGreater(), isSmaller(), and toString().
The documentation for this class was generated from the following files:
EntryKeyData.hh
EntryKeyData.cc