OpenASIP: OSEdRemoveOperationCmd Class Reference
OSEdRemoveOperationCmd Class Reference
#include <OSEdRemoveOperationCmd.hh>
Public Member Functions
OSEdRemoveOperationCmd ()
virtual ~OSEdRemoveOperationCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdRemoveOperationCmd (const OSEdRemoveOperationCmd &)
Copying not allowed.
OSEdRemoveOperationCmd & operator= (const OSEdRemoveOperationCmd &)
Assignment not allowed.
Detailed Description
Command for removing an operation.
Definition at line 43 of file OSEdRemoveOperationCmd.hh.
Constructor & Destructor Documentation
OSEdRemoveOperationCmd() [1/2]
OSEdRemoveOperationCmd::OSEdRemoveOperationCmd ()
Constructor.
Definition at line 58 of file OSEdRemoveOperationCmd.cc.
                                               :
    GUICommand(OSEdConstants::CMD_NAME_REMOVE_OPERATION, NULL) {
}
Referenced by create().
~OSEdRemoveOperationCmd()
OSEdRemoveOperationCmd::~OSEdRemoveOperationCmd () virtual
Destructor.
Definition at line 65 of file OSEdRemoveOperationCmd.cc.
{
}
OSEdRemoveOperationCmd() [2/2]
OSEdRemoveOperationCmd::OSEdRemoveOperationCmd (const OSEdRemoveOperationCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdRemoveOperationCmd::create () const virtual
Creates a new command.
Returns
New command.
Implements GUICommand.
Definition at line 84 of file OSEdRemoveOperationCmd.cc.
{
    return new OSEdRemoveOperationCmd();
}
References OSEdRemoveOperationCmd().
Do()
bool OSEdRemoveOperationCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 94 of file OSEdRemoveOperationCmd.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    Operation* op = treeView->selectedOperation();
    wxTreeItemId opId = treeView->selectedOperationId();
    string modName = treeView->moduleOfOperation(opId);
    wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
    string pathName = treeView->pathOfModule(modId);
    OperationModule& module = OperationContainer::module(pathName, modName);
    format fmt = texts.text(OSEdTextGenerator::TXT_QUESTION_REMOVE_OPERATION);
    fmt % op->name();
    ConfirmDialog dialog(parentWindow(), WxConversion::toWxString(fmt.str()));
    if (dialog.ShowModal() == wxID_YES) {
        OperationSerializer& serializer =
            OperationContainer::operationSerializer();
        serializer.setSourceFile(module.propertiesModule());
        ObjectState* root = NULL;
        try {
            root = serializer.readState();
            for (int i = 0; i < root->childCount(); i++) {
                ObjectState* child = root->child(i);
                if (child->stringAttribute("name") == op->name()) {
                    delete child;
                    break;
                }
            }
            serializer.setDestinationFile(module.propertiesModule());
            serializer.writeState(root);
            delete root;
        } catch (const Exception& e) {
            fmt = texts.text(
                OSEdTextGenerator::TXT_ERROR_CAN_NOT_REMOVE_OPERATION);
            fmt % op->name();
            ErrorDialog error(
                parentWindow(), WxConversion::toWxString(fmt.str()));
            error.ShowModal();
            delete root;
            delete op;
            return false;
        }
        OperationIndex& index = OperationContainer::operationIndex();
        index.refreshModule(pathName, modName);
        treeView->removeItem(opId);
        treeView->infoView()->operationView(pathName, modName);
    }
    delete op;
    return true;
}
References ObjectState::child(), ObjectState::childCount(), OSEdTreeView::infoView(), OSEdTextGenerator::instance(), OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::moduleOfOperation(), Operation::name(), OperationContainer::operationIndex(), OperationContainer::operationSerializer(), OSEdInfoView::operationView(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OperationSerializer::readState(), OperationIndex::refreshModule(), OSEdTreeView::removeItem(), OSEdTreeView::selectedOperation(), OSEdTreeView::selectedOperationId(), OperationSerializer::setDestinationFile(), OperationSerializer::setSourceFile(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_CAN_NOT_REMOVE_OPERATION, OSEdTextGenerator::TXT_QUESTION_REMOVE_OPERATION, and OperationSerializer::writeState().
icon()
string OSEdRemoveOperationCmd::icon () const virtual
Returns the icon of the command.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 180 of file OSEdRemoveOperationCmd.cc.
{
    return "";
}
id()
int OSEdRemoveOperationCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 74 of file OSEdRemoveOperationCmd.cc.
{
    return OSEdConstants::CMD_REMOVE_OPERATION;
}
References OSEdConstants::CMD_REMOVE_OPERATION.
isEnabled()
bool OSEdRemoveOperationCmd::isEnabled () virtual
Returns true if command is enabled, otherwise false.
Command is enabled when the path of the operation is writable.
Returns
True if command is enabled, otherwise false.
Implements GUICommand.
Definition at line 158 of file OSEdRemoveOperationCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    if (treeView->isOperationSelected()) {
        wxTreeItemId opId = treeView->selectedOperationId();
        wxTreeItemId modId = treeView->moduleIdOfOperation(opId);
        string path = treeView->pathOfModule(modId);
        if (FileSystem::fileIsWritable(path)) {
            return true;
        } else {
            return false;
        }
    } else {
        return false;
    }
}
References FileSystem::fileIsWritable(), OSEdTreeView::isOperationSelected(), OSEdTreeView::moduleIdOfOperation(), OSEdTreeView::pathOfModule(), and OSEdTreeView::selectedOperationId().
operator=()
OSEdRemoveOperationCmd & OSEdRemoveOperationCmd::operator= (const OSEdRemoveOperationCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdRemoveOperationCmd.hh
OSEdRemoveOperationCmd.cc