OpenASIP: CostEstimator::TransportPath Class Reference
CostEstimator::TransportPath Class Reference
#include <TransportPath.hh>
Public Member Functions
TransportPath (const TTAMachine::Port &sourcePort, const TTAMachine::Socket &sourceSocket, const TTAMachine::Bus &bus, const TTAMachine::Socket &destinationSocket, const TTAMachine::Port &destinationPort)
virtual ~TransportPath ()
const TTAMachine::Port & sourcePort () const
const TTAMachine::Socket & sourceSocket () const
const TTAMachine::Bus & bus () const
const TTAMachine::Socket & destinationSocket () const
const TTAMachine::Port & destinationPort () const
Private Attributes
const TTAMachine::Port & sourcePort_
const TTAMachine::Socket & sourceSocket_
const TTAMachine::Bus & bus_
const TTAMachine::Socket & destinationSocket_
const TTAMachine::Port & destinationPort_
Detailed Description
Represents a single transport path in a machine.
The class is simply a storage for source port, source socket, bus, destination socket, destination port components that make a path for data transports in a machine.
Definition at line 52 of file TransportPath.hh.
Constructor & Destructor Documentation
TransportPath()
CostEstimator::TransportPath::TransportPath (const TTAMachine::Port & sourcePort, const TTAMachine::Socket & sourceSocket, const TTAMachine::Bus & bus, const TTAMachine::Socket & destinationSocket, const TTAMachine::Port & destinationPort)
Constructor.
Definition at line 40 of file TransportPath.cc.
                                           :
    sourcePort_(sourcePort), sourceSocket_(sourceSocket), bus_(bus),
    destinationSocket_(destinationSocket), destinationPort_(destinationPort) {
}
~TransportPath()
CostEstimator::TransportPath::~TransportPath () virtual
Destructor.
Definition at line 53 of file TransportPath.cc.
{
}
Member Function Documentation
bus()
const TTAMachine::Bus & CostEstimator::TransportPath::bus () const
Returns the bus.
Returns
The bus.
Definition at line 82 of file TransportPath.cc.
{
    return bus_;
}
References bus_.
Referenced by DefaultICDecoderEstimator::estimateICDelayOfPath(), and CostEstimator::Estimator::longestPath().
destinationPort()
const TTAMachine::Port & CostEstimator::TransportPath::destinationPort () const
Returns the destination port.
Parameters
Destination port.
Definition at line 102 of file TransportPath.cc.
{
    return destinationPort_;
}
References destinationPort_.
Referenced by CostEstimator::Estimator::longestPath().
destinationSocket()
const TTAMachine::Socket & CostEstimator::TransportPath::destinationSocket () const
Returns the destination socket.
Parameters
Destination socket.
Definition at line 92 of file TransportPath.cc.
{
    return destinationSocket_;
}
References destinationSocket_.
Referenced by DefaultICDecoderEstimator::estimateICDelayOfPath(), and CostEstimator::Estimator::longestPath().
sourcePort()
const TTAMachine::Port & CostEstimator::TransportPath::sourcePort () const
Returns the source port.
Returns
Source port.
Definition at line 62 of file TransportPath.cc.
{
    return sourcePort_;
}
References sourcePort_.
Referenced by CostEstimator::Estimator::longestPath().
sourceSocket()
const TTAMachine::Socket & CostEstimator::TransportPath::sourceSocket () const
Returns the source socket.
Returns
Source socket.
Definition at line 72 of file TransportPath.cc.
{
    return sourceSocket_;
}
References sourceSocket_.
Referenced by DefaultICDecoderEstimator::estimateICDelayOfPath(), and CostEstimator::Estimator::longestPath().
Member Data Documentation
bus_
const TTAMachine::Bus& CostEstimator::TransportPath::bus_ private
Definition at line 71 of file TransportPath.hh.
Referenced by bus().
destinationPort_
const TTAMachine::Port& CostEstimator::TransportPath::destinationPort_ private
Definition at line 73 of file TransportPath.hh.
Referenced by destinationPort().
destinationSocket_
const TTAMachine::Socket& CostEstimator::TransportPath::destinationSocket_ private
Definition at line 72 of file TransportPath.hh.
Referenced by destinationSocket().
sourcePort_
const TTAMachine::Port& CostEstimator::TransportPath::sourcePort_ private
Definition at line 69 of file TransportPath.hh.
Referenced by sourcePort().
sourceSocket_
const TTAMachine::Socket& CostEstimator::TransportPath::sourceSocket_ private
Definition at line 70 of file TransportPath.hh.
Referenced by sourceSocket().
The documentation for this class was generated from the following files:
TransportPath.hh
TransportPath.cc