OpenASIP: BFShareOperandWithScheduled Class Reference
BFShareOperandWithScheduled Class Reference
#include <BFShareOperandWithScheduled.hh>
Public Member Functions
BFShareOperandWithScheduled (BF2Scheduler &sched, MoveNode &removed, MoveNode &scheduled)
virtual bool operator() ()
virtual ~BFShareOperandWithScheduled ()
Public Member Functions inherited from BFShareOperand
BFShareOperand (BF2Scheduler &sched, MoveNode &removed, MoveNode &shared)
virtual ~BFShareOperand ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
virtual void undoOnlyMe ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes
int originalCycle_
const TTAMachine::Bus * originalRemovedBus_
const TTAMachine::Bus * prologBus_
int oldImmWriteCycle_
int prologImmWriteCycle_
const TTAMachine::ImmediateUnit * immu_
int immRegIndex_
Protected Attributes inherited from BFShareOperand
MoveNode & removed_
MoveNode & shared_
std::vector< ProgramOperationPtr > ops_
std::set< ProgramOperationPtr > createdPrologPOs_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 44 of file BFShareOperandWithScheduled.hh.
Constructor & Destructor Documentation
BFShareOperandWithScheduled()
BFShareOperandWithScheduled::BFShareOperandWithScheduled (BF2Scheduler & sched, MoveNode & removed, MoveNode & scheduled) inline
Definition at line 46 of file BFShareOperandWithScheduled.hh.
                                    :
        BFShareOperand(sched, removed, scheduled), originalCycle_(-1),
        originalRemovedBus_(NULL), prologBus_(NULL), oldImmWriteCycle_(-1),
        prologImmWriteCycle_(-1), immu_(NULL), immRegIndex_(-1)
    {}
~BFShareOperandWithScheduled()
virtual BFShareOperandWithScheduled::~BFShareOperandWithScheduled () inline virtual
Definition at line 53 of file BFShareOperandWithScheduled.hh.
{}
Member Function Documentation
operator()()
bool BFShareOperandWithScheduled::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Reimplemented from BFShareOperand.
Definition at line 48 of file BFShareOperandWithScheduled.cc.
{
    if (removed_.move().destination().operationIndex() !=
        shared_.move().destination().operationIndex()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\t\tDestination operand index mismatch"
                  << std::endl;
#endif
        return false;
    }
    originalRemovedBus_ = &removed_.move().bus();
    originalCycle_ = removed_.cycle();
    if (removed_.move().source().isImmediateRegister()) {
        oldImmWriteCycle_ = rm().immediateWriteCycle(removed_);
        immRegIndex_ = removed_.move().source().index();
        immu_ = &removed_.move().source().immediateUnit();
    }
    MoveNode* removedPrologMN = ii() ?
        duplicator().getMoveNode(removed_) :
        NULL;
    if (removedPrologMN != NULL) {
        prologBus_ = &removedPrologMN->move().bus();
    if (removedPrologMN->move().source().isImmediateRegister()) {
        prologImmWriteCycle_ =
            prologRM()->immediateWriteCycle(*removedPrologMN);
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tShareOpWithSched Saving prolog bus: "
                  << prologBus_->name() << std::endl;
        std::cerr << "\t\t\t\t\tProlog move: " << removedPrologMN->toString()
                  << std::endl;
#endif
    }
    unassign(removed_, false);
    if (BFShareOperand::operator()()) {
        ddg().dropNode(removed_);
        sched_.nodeAndCopyKilled(removed_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\t\tShared operand ok!" << std::endl;
#endif
        return true;
    } else {
        sched_.nodeResurrected(removed_);
        ddg().restoreNodeFromParent(removed_);
        assign(originalCycle_, removed_, originalRemovedBus_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\t\tShare operand failed!" << std::endl;
#endif
        return false;
    }
}
References BFOptimization::assign(), TTAProgram::Move::bus(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), BoostGraph< GraphNode, GraphEdge >::dropNode(), BFOptimization::duplicator(), MoveNodeDuplicator::getMoveNode(), BFOptimization::ii(), TTAProgram::Terminal::immediateUnit(), SimpleResourceManager::immediateWriteCycle(), immRegIndex_, immu_, TTAProgram::Terminal::index(), TTAProgram::Terminal::isImmediateRegister(), MoveNode::move(), TTAMachine::Component::name(), BF2Scheduler::nodeAndCopyKilled(), BF2Scheduler::nodeResurrected(), oldImmWriteCycle_, TTAProgram::Terminal::operationIndex(), originalCycle_, originalRemovedBus_, prologBus_, prologImmWriteCycle_, BFOptimization::prologRM(), BFShareOperand::removed_, BoostGraph< GraphNode, GraphEdge >::restoreNodeFromParent(), BFOptimization::rm(), BFOptimization::sched_, BFShareOperand::shared_, TTAProgram::Move::source(), MoveNode::toString(), and BFOptimization::unassign().
undoOnlyMe()
void BFShareOperandWithScheduled::undoOnlyMe () protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from BFShareOperand.
Definition at line 105 of file BFShareOperandWithScheduled.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\t\t\tUndoing operandshare: " << shared_.toString()
              << std::endl;
#endif
    BFShareOperand::undoOnlyMe();
    sched_.nodeResurrected(removed_);
    ddg().restoreNodeFromParent(removed_);
    assign(originalCycle_, removed_, originalRemovedBus_, NULL, NULL,
           prologBus_, oldImmWriteCycle_, prologImmWriteCycle_, immu_,
           immRegIndex_);
}
References BFOptimization::assign(), BFOptimization::ddg(), immRegIndex_, immu_, BF2Scheduler::nodeResurrected(), oldImmWriteCycle_, originalCycle_, originalRemovedBus_, prologBus_, prologImmWriteCycle_, BFShareOperand::removed_, BoostGraph< GraphNode, GraphEdge >::restoreNodeFromParent(), BFOptimization::sched_, BFShareOperand::shared_, MoveNode::toString(), and BFShareOperand::undoOnlyMe().
Member Data Documentation
immRegIndex_
int BFShareOperandWithScheduled::immRegIndex_ protected
Definition at line 63 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
immu_
const TTAMachine::ImmediateUnit* BFShareOperandWithScheduled::immu_ protected
Definition at line 62 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
oldImmWriteCycle_
int BFShareOperandWithScheduled::oldImmWriteCycle_ protected
Definition at line 60 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
originalCycle_
int BFShareOperandWithScheduled::originalCycle_ protected
Definition at line 56 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
originalRemovedBus_
const TTAMachine::Bus* BFShareOperandWithScheduled::originalRemovedBus_ protected
Definition at line 57 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
prologBus_
const TTAMachine::Bus* BFShareOperandWithScheduled::prologBus_ protected
Definition at line 58 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
prologImmWriteCycle_
int BFShareOperandWithScheduled::prologImmWriteCycle_ protected
Definition at line 61 of file BFShareOperandWithScheduled.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFShareOperandWithScheduled.hh
BFShareOperandWithScheduled.cc