OpenASIP: ModifyBridgeCmd Class Reference
ModifyBridgeCmd Class Reference
#include <ModifyBridgeCmd.hh>
Public Member Functions
ModifyBridgeCmd (EditPart *editPart)
virtual ~ModifyBridgeCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * editPart_
Bridge to modify.
Detailed Description
Command which displays a bridge dialog with precompleted values for modifying a bridge.
Definition at line 45 of file ModifyBridgeCmd.hh.
Constructor & Destructor Documentation
ModifyBridgeCmd()
ModifyBridgeCmd::ModifyBridgeCmd (EditPart * editPart)
The Constructor.
Parameters
editPart EditPart of the component to modify.
Definition at line 52 of file ModifyBridgeCmd.cc.
                                                  :
    ComponentCommand(),
    editPart_(editPart) {
}
~ModifyBridgeCmd()
ModifyBridgeCmd::~ModifyBridgeCmd () virtual
The Destructor.
Definition at line 62 of file ModifyBridgeCmd.cc.
{
}
Member Function Documentation
Do()
bool ModifyBridgeCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 72 of file ModifyBridgeCmd.cc.
                    {
    Bridge* bridge = NULL;
    Bridge* opposite = NULL;
    if (editPart_->childCount() == 0) {
        bridge = dynamic_cast<Bridge*>(editPart_->model());
    editPart_->setModel(NULL);
        assert (bridge != NULL);
    } else {
        // bidirectional bridge
        assert(editPart_->childCount() == 2);
        // find bridges of both direction
        bridge = dynamic_cast<Bridge*>(editPart_->child(0)->model());
        opposite = dynamic_cast<Bridge*>(editPart_->child(1)->model());
    editPart_->setModel(NULL);
    }
    assert(opposite != bridge);
    BridgeDialog dialog(parentWindow(), bridge, opposite);
    if (dialog.ShowModal() == wxID_OK) {
    return true;
    } else {
    // modification was cancelled
    return false;
    }
    return false;
}
References assert, EditPart::child(), EditPart::childCount(), editPart_, EditPart::model(), ComponentCommand::parentWindow(), and EditPart::setModel().
Member Data Documentation
editPart_
EditPart* ModifyBridgeCmd::editPart_ private
Bridge to modify.
Definition at line 53 of file ModifyBridgeCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ModifyBridgeCmd.hh
ModifyBridgeCmd.cc