OpenASIP: ProximBusEditPolicy Class Reference
ProximBusEditPolicy Class Reference
#include <ProximBusEditPolicy.hh>
Public Member Functions
ProximBusEditPolicy ()
virtual ~ProximBusEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Edit policy for Proxim machine state window buses.
Definition at line 41 of file ProximBusEditPolicy.hh.
Constructor & Destructor Documentation
ProximBusEditPolicy()
ProximBusEditPolicy::ProximBusEditPolicy ()
The Constructor.
Definition at line 47 of file ProximBusEditPolicy.cc.
                                         :
    EditPolicy() {
}
~ProximBusEditPolicy()
ProximBusEditPolicy::~ProximBusEditPolicy () virtual
The Destructor.
Definition at line 55 of file ProximBusEditPolicy.cc.
{
}
Member Function Documentation
canHandle()
bool ProximBusEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy can handle request of the given type.
Parameters
Request to be handled.
Returns
True, if the editpolicy can handle give request type.
Implements EditPolicy.
Definition at line 65 of file ProximBusEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::STATUS_REQUEST ||
        type == Request::DETAILS_REQUEST) {
        return true;
    }
    return false;
}
References Request::DETAILS_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProximBusEditPolicy::getCommand (Request * request) virtual
Returns command correspoding to the request type.
Parameters
request Request to handle.
Returns
NULL, if the request can't be handled.
Implements EditPolicy.
Definition at line 84 of file ProximBusEditPolicy.cc.
{
    Request::RequestType type = request->type();
    const Bus* bus = dynamic_cast<const Bus*>(host_->model());
    if (bus == NULL) {
        const Segment* segment = dynamic_cast<const Segment*>(host_->model());
        assert(segment != NULL);
        bus = segment->parentBus();
    }
    assert(bus != NULL);
    if (type == Request::STATUS_REQUEST) {
        std::string status = ProximConstants::MACH_WIN_BUS_LABEL + bus->name();
        return new ProximComponentStatusCmd(status);
    } else if (type == Request::DETAILS_REQUEST) {
        return new ProximBusDetailsCmd(*bus);
    }
    return NULL;
}
References assert, Request::DETAILS_REQUEST, EditPolicy::host_, ProximConstants::MACH_WIN_BUS_LABEL, EditPart::model(), TTAMachine::Component::name(), TTAMachine::Segment::parentBus(), Request::STATUS_REQUEST, and Request::type().
The documentation for this class was generated from the following files:
ProximBusEditPolicy.hh
ProximBusEditPolicy.cc