OpenASIP: EditPolicyFactory Class Reference
EditPolicyFactory Class Reference
#include <EditPolicyFactory.hh>
Public Member Functions
EditPolicyFactory ()
virtual ~EditPolicyFactory ()
virtual EditPolicy * createFUEditPolicy ()
virtual EditPolicy * createRFEditPolicy ()
virtual EditPolicy * createIUEditPolicy ()
virtual EditPolicy * createGCUEditPolicy ()
virtual EditPolicy * createFUPortEditPolicy ()
virtual EditPolicy * createRFPortEditPolicy ()
virtual EditPolicy * createIUPortEditPolicy ()
virtual EditPolicy * createSRPortEditPolicy ()
virtual EditPolicy * createPortEditPolicy ()
virtual EditPolicy * createBusEditPolicy ()
virtual EditPolicy * createSocketEditPolicy ()
virtual EditPolicy * createSegmentEditPolicy ()
virtual EditPolicy * createBridgeEditPolicy ()
Detailed Description
Base class for EditPolicyFactories, which are utilized by the EditPartFactory class to create EditPolicies.
EditPolicies of MachineCanvas components can be defined by deriving a factory from this class, and passing it to the EditPartFactory as the EditPolicyFactory.
Definition at line 46 of file EditPolicyFactory.hh.
Constructor & Destructor Documentation
EditPolicyFactory()
EditPolicyFactory::EditPolicyFactory ()
The Constructor.
Definition at line 38 of file EditPolicyFactory.cc.
{
}
~EditPolicyFactory()
EditPolicyFactory::~EditPolicyFactory () virtual
The Destructor.
Definition at line 44 of file EditPolicyFactory.cc.
{
}
Member Function Documentation
createBridgeEditPolicy()
virtual EditPolicy * EditPolicyFactory::createBridgeEditPolicy () virtual
Reimplemented in ProDeEditPolicyFactory.
Referenced by MachineEditPartFactory::createBiDirBridge(), and BridgeFactory::createEditPart().
createBusEditPolicy()
virtual EditPolicy * EditPolicyFactory::createBusEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by BusFactory::createEditPart().
createFUEditPolicy()
virtual EditPolicy * EditPolicyFactory::createFUEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by FUFactory::createEditPart().
createFUPortEditPolicy()
virtual EditPolicy * EditPolicyFactory::createFUPortEditPolicy () virtual
Reimplemented in ProDeEditPolicyFactory.
Referenced by FUFactory::createEditPart(), and GCUFactory::createEditPart().
createGCUEditPolicy()
virtual EditPolicy * EditPolicyFactory::createGCUEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by GCUFactory::createEditPart().
createIUEditPolicy()
virtual EditPolicy * EditPolicyFactory::createIUEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by IUFactory::createEditPart().
createIUPortEditPolicy()
virtual EditPolicy * EditPolicyFactory::createIUPortEditPolicy () virtual
Reimplemented in ProDeEditPolicyFactory.
Referenced by IUFactory::createEditPart().
createPortEditPolicy()
virtual EditPolicy * EditPolicyFactory::createPortEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by UnitPortFactory::createEditPart().
createRFEditPolicy()
virtual EditPolicy * EditPolicyFactory::createRFEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by RFFactory::createEditPart().
createRFPortEditPolicy()
virtual EditPolicy * EditPolicyFactory::createRFPortEditPolicy () virtual
Reimplemented in ProDeEditPolicyFactory.
Referenced by RFFactory::createEditPart().
createSegmentEditPolicy()
virtual EditPolicy * EditPolicyFactory::createSegmentEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by SegmentFactory::createEditPart().
createSocketEditPolicy()
virtual EditPolicy * EditPolicyFactory::createSocketEditPolicy () virtual
Reimplemented in ProximEditPolicyFactory, and ProDeEditPolicyFactory.
Referenced by SocketFactory::createEditPart().
createSRPortEditPolicy()
virtual EditPolicy * EditPolicyFactory::createSRPortEditPolicy () virtual
Reimplemented in ProDeEditPolicyFactory.
Referenced by GCUFactory::createEditPart().
The documentation for this class was generated from the following files:
EditPolicyFactory.hh
EditPolicyFactory.cc