OpenASIP: BusResource Class Reference
BusResource Class Reference
#include <BusResource.hh>
Public Member Functions
BusResource (const std::string &name, int width, int limmSlotCount, int nopSlotCount, int guardCount, int immSize, int socketCount, unsigned int initiationInterval=0)
virtual ~BusResource ()
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual bool isAvailable (const int cycle, const SchedulingResource &inputPSocket, const SchedulingResource &outputPSocket) const
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
virtual bool canAssign (const int cycle, const MoveNode &node, const SchedulingResource &inputPSocket, const SchedulingResource &outputPSocket) const
virtual bool isBusResource () const override
virtual bool operator< (const SchedulingResource &other) const override
int nopSlotCount ()
void clear () override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Types
typedef std::map< int, int > ResourceRecordType
Private Member Functions
BusResource (const BusResource &)
BusResource & operator= (const BusResource &)
Private Attributes
int busWidth_
int limmSlotCount_
int nopSlotCount_
int guardCount_
int immSize_
int socketCount_
ResourceRecordType resourceRecord_
Additional Inherited Members
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model The derived class BusResource
Definition at line 46 of file BusResource.hh.
Member Typedef Documentation
ResourceRecordType
typedef std::map<int, int> BusResource::ResourceRecordType private
Definition at line 97 of file BusResource.hh.
Constructor & Destructor Documentation
BusResource() [1/2]
BusResource::BusResource (const std::string & name, int width, int limmSlotCount, int nopSlotCount, int guardCount, int immSize, int socketCount, unsigned int initiationInterval = 0)
Constructor Creates new resource with defined name
Parameters
name Name of resource
width short immediate width of the bus
limmSlotCount how many itemplates use this bus in limm field
Definition at line 54 of file BusResource.cc.
                                                                   :
    SchedulingResource(name, initiationInterval), busWidth_(width),
    limmSlotCount_(limmSlotCount), nopSlotCount_(nopSlotCount),
    guardCount_(guardCount),
    immSize_(immSize), socketCount_(socketCount) {
}
~BusResource()
BusResource::~BusResource () virtual
Empty destructor
Definition at line 67 of file BusResource.cc.
{}
BusResource() [2/2]
BusResource::BusResource (const BusResource &) private
Member Function Documentation
assign()
void BusResource::assign (const int cycle, MoveNode & node) override virtual
Assign resource to given node for given cycle without testing Input or Output PSocket, assign ALL segments of bus.
Parameters
cycle Cycle to assign
node MoveNode assigned
Exceptions
In case assignment can not be done
Implements SchedulingResource.
Definition at line 124 of file BusResource.cc.
{
   if (canAssign(cycle, node)) {
        resourceRecord_[instructionIndex(cycle)] = 1;
        increaseUseCount();
        return;
    }
}
References canAssign(), SchedulingResource::increaseUseCount(), SchedulingResource::instructionIndex(), and resourceRecord_.
Referenced by BusBroker::assign().
canAssign() [1/2]
bool BusResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Return true if resource can be assigned for given node in given cycle
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Implements SchedulingResource.
Definition at line 164 of file BusResource.cc.
{
    return isAvailable(cycle);
}
References isAvailable().
Referenced by BusBroker::allAvailableResources(), assign(), and BusBroker::isAvailable().
canAssign() [2/2]
bool BusResource::canAssign (const int cycle, const MoveNode & node, const SchedulingResource & inputPSocket, const SchedulingResource & outputPSocket) const virtual
Return true if resource can be assigned for given node in given cycle
Parameters
cycle Cycle to test
node MoveNode to test
inputPSocket PSocket connected to source of move
outputPSocket PSocket connected to destination of move
Returns
true if node can be assigned to cycle
Definition at line 177 of file BusResource.cc.
{
    if (!isAvailable(cycle, inputPSocket, outputPSocket)) {
        return false;
    }
    int defBits = node.isSourceConstant()?
        busWidth_ : node.move().source().port().width();
    // TODO: Check if source is from an operation result that defines less bits.
    int useBits = node.move().destination().port().width();
    if (useBits > busWidth_ && node.destinationOperationCount()) {
        // Writing undefined bits *1 to upper bits of the destination port.
        // Check if none of the destinations use those bits.
        //     *1: DefaultICDecoderPlugin zero extends when writing to port from
        //         narrower bus, but this is not documented semantic?
        int maxOpdWidth = 0;
        for (size_t i = 0; i < node.destinationOperationCount(); i++) {
            const auto& op = node.destinationOperation(i).operation();
            int opdIdx = node.move().destination().operationIndex();
            int opdWidth = op.operand(opdIdx).width();
            maxOpdWidth = std::max(maxOpdWidth, opdWidth);
        }
        assert(maxOpdWidth > 0);
        useBits = std::min(useBits, maxOpdWidth);
    }
    // Define bit width of the value transportation as in below statement to
    // allow cases such as:
    // - Move from ALU compare to boolean reg.
    // - Move from boolean reg to LSU store.
    int transportWidth = std::min(defBits, useBits);
    if (transportWidth > busWidth_) {
        return false;
    }
    if (!inputPSocket.isOutputPSocketResource() ||
        !hasRelatedResource(inputPSocket)) {
        return false;
    }
    if (!outputPSocket.isInputPSocketResource() ||
        !hasRelatedResource(outputPSocket)) {
        return false;
    }
    return true;
}
References assert, busWidth_, TTAProgram::Move::destination(), MoveNode::destinationOperation(), MoveNode::destinationOperationCount(), SchedulingResource::hasRelatedResource(), isAvailable(), SchedulingResource::isInputPSocketResource(), SchedulingResource::isOutputPSocketResource(), MoveNode::isSourceConstant(), MoveNode::move(), ProgramOperation::operation(), TTAProgram::Terminal::operationIndex(), TTAProgram::Terminal::port(), TTAProgram::Move::source(), and TTAMachine::Port::width().
clear()
void BusResource::clear () override virtual
Clears bookkeeping of the scheduling resource.
After this call the state of the resource should be identical to a newly-created and initialized resource.
Reimplemented from SchedulingResource.
Definition at line 334 of file BusResource.cc.
                   {
    SchedulingResource::clear();
    resourceRecord_.clear();
}
References SchedulingResource::clear(), and resourceRecord_.
isAvailable() [1/2]
bool BusResource::isAvailable (const int cycle) const override virtual
Test if resource BusResource is available
Parameters
cycle Cycle which to test
Returns
False if all the segments of bus are InUse
Implements SchedulingResource.
Definition at line 90 of file BusResource.cc.
{
    return !isInUse(cycle);
}
References isInUse().
Referenced by canAssign(), canAssign(), and isAvailable().
isAvailable() [2/2]
bool BusResource::isAvailable (const int cycle, const SchedulingResource & inputPSocket, const SchedulingResource & outputPSocket) const virtual
Test if resource BusResource is available.
Parameters
cycle Cycle which to test
Returns
False if all the segments of bus are InUse
Definition at line 101 of file BusResource.cc.
{
    if (!(hasRelatedResource(inputPSocket) &&
        hasRelatedResource(outputPSocket))) {
        // BusBroker does not need to test if sockets
        // are connected to the bus...
       return false;
    }
    return isAvailable(cycle);
}
References SchedulingResource::hasRelatedResource(), and isAvailable().
isBusResource()
bool BusResource::isBusResource () const override virtual
Return allways true
Returns
true
Reimplemented from SchedulingResource.
Definition at line 232 of file BusResource.cc.
{
    return true;
}
isInUse()
bool BusResource::isInUse (const int cycle) const override virtual
Test if resource BusResource is used in given cycle
Parameters
cycle Cycle which to test
Returns
True if any of segments of bus isInUse in given cycle
Implements SchedulingResource.
Definition at line 75 of file BusResource.cc.
{
    ResourceRecordType::const_iterator i =
        resourceRecord_.find(instructionIndex(cycle));
    if (i != resourceRecord_.end() && i->second != 0) {
        return true;
    }
    return false;
}
References SchedulingResource::instructionIndex(), and resourceRecord_.
Referenced by isAvailable(), BusBroker::isInUse(), and unassign().
nopSlotCount()
int BusResource::nopSlotCount () inline
Definition at line 72 of file BusResource.hh.
{ return nopSlotCount_; }
References nopSlotCount_.
operator<()
bool BusResource::operator< (const SchedulingResource & other) const override virtual
Comparison operator.
Favours busses which have less limm slots associated to then in instruction templates, ie. busses which do not get into way of limm writes.
Reimplemented from SchedulingResource.
Definition at line 274 of file BusResource.cc.
{
    const BusResource *busr = static_cast<const BusResource*>(&other);
    // favour buses with less nop slots
    if (nopSlotCount_ < busr->nopSlotCount_) {
        return true;
    }
    if (nopSlotCount_ > busr->nopSlotCount_) {
        return false;
    }
    if (busr == NULL) {
        return false;
    }
    // then try to use busses without guards, if possible.
    if (guardCount_ < busr->guardCount_) {
        return true;
    }
    if (guardCount_ > busr->guardCount_) {
        return false;
    }
    // then favour busses with less sockets.
    if (socketCount_ < busr->socketCount_) {
        return true;
    }
    if (socketCount_ > busr->socketCount_) {
        return false;
    }
    // first priority are limm slots.
    if (limmSlotCount_ < busr->limmSlotCount_) {
        return true;
    }
    if (limmSlotCount_ > busr->limmSlotCount_) {
        return false;
    }
    // then favour busses with smallest immediate.
    if (immSize_ < busr->immSize_) {
        return true;
    }
    if (immSize_ > busr->immSize_) {
        return false;
    }
    // then use the default use count, name comparison,
    // but in opposite direction, facouring already used
    return other.SchedulingResource::operator<(*this);
}
References guardCount_, immSize_, limmSlotCount_, nopSlotCount_, and socketCount_.
operator=()
BusResource & BusResource::operator= (const BusResource &) private
unassign()
void BusResource::unassign (const int cycle, MoveNode & node) override virtual
Unassign resource from given node for given cycle without testing Input or Output PSocket, unassign all segments of bus
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
Exceptions
In case bus was not assigned
Implements SchedulingResource.
Definition at line 142 of file BusResource.cc.
{
    if (isInUse(cycle)) {
        resourceRecord_[instructionIndex(cycle)] = 0;
        return;
    } else{
        std::string msg = "Bus ";
        msg += name();
        msg += " can not be unassigned in cycle ";
        msg += Conversion::toString(cycle);
        msg += ", it was not in use!";
        throw ModuleRunTimeError(__FILE__, __LINE__,__func__, msg);
    }
}
References __func__, SchedulingResource::instructionIndex(), isInUse(), SchedulingResource::name(), resourceRecord_, and Conversion::toString().
Referenced by BusBroker::unassign().
validateDependentGroups()
bool BusResource::validateDependentGroups () override protected virtual
Tests if all referred resources in dependent groups are of proper types
Returns
true If all resources in dependent groups are Segment resources
Reimplemented from SchedulingResource.
Definition at line 243 of file BusResource.cc.
{
    return true;
}
validateRelatedGroups()
bool BusResource::validateRelatedGroups () override protected virtual
Tests if all resources in related resource groups are of proper types
Returns
true If all resources in related resource groups are PSockets
Reimplemented from SchedulingResource.
Definition at line 254 of file BusResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        for (int j = 0, count = relatedResourceCount(i);
            j < count;
            j++) {
            if (!(relatedResource(i, j).isInputPSocketResource() ||
                relatedResource(i, j).isOutputPSocketResource()))
                return false;
        }
    }
    return true;
}
References SchedulingResource::isInputPSocketResource(), SchedulingResource::isOutputPSocketResource(), SchedulingResource::relatedResource(), SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
Member Data Documentation
busWidth_
int BusResource::busWidth_ private
Definition at line 84 of file BusResource.hh.
Referenced by canAssign().
guardCount_
int BusResource::guardCount_ private
Definition at line 90 of file BusResource.hh.
Referenced by operator<().
immSize_
int BusResource::immSize_ private
Definition at line 92 of file BusResource.hh.
Referenced by operator<().
limmSlotCount_
int BusResource::limmSlotCount_ private
Definition at line 86 of file BusResource.hh.
Referenced by operator<().
nopSlotCount_
int BusResource::nopSlotCount_ private
Definition at line 88 of file BusResource.hh.
Referenced by nopSlotCount(), and operator<().
resourceRecord_
ResourceRecordType BusResource::resourceRecord_ private
Definition at line 98 of file BusResource.hh.
Referenced by assign(), clear(), isInUse(), and unassign().
socketCount_
int BusResource::socketCount_ private
Definition at line 94 of file BusResource.hh.
Referenced by operator<().
The documentation for this class was generated from the following files:
BusResource.hh
BusResource.cc