OpenASIP: SparseVector< ValueType > Class Template Reference
SparseVector< ValueType > Class Template Reference
#include <SparseVectorMap.hh>
Public Member Functions
size_t size () const
size_t number_of_elements () const
Detailed Description
template<class ValueType>
class SparseVector< ValueType >
Definition at line 43 of file SparseVectorMap.hh.
Member Function Documentation
number_of_elements()
template<class ValueType > size_t SparseVector< ValueType >::number_of_elements () const inline
Definition at line 54 of file SparseVectorMap.hh.
{
        return std::map<unsigned int, ValueType>::size();
    }
size()
template<class ValueType > size_t SparseVector< ValueType >::size () const inline
Definition at line 45 of file SparseVectorMap.hh.
{
        typename std::map<unsigned int, ValueType>::const_reverse_iterator i =
            std::map<unsigned int, ValueType>::rbegin();
        if (i != std::map<unsigned int, ValueType>::rend()) {
            return (i->first)+1;
        } else {
            return 0;
        }
    }
Referenced by ExecutionPipelineResource::assignSource(), ExecutionPipelineResource::highestKnownCycle(), ExecutionPipelineResource::nextResultCycle(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::resourcesAllowTrigger(), ExecutionPipelineResource::resultAllowedAtCycle(), ExecutionPipelineResource::size(), ExecutionPipelineResource::unassignDestination(), and ExecutionPipelineResource::unassignSource().
The documentation for this class was generated from the following file:
SparseVectorMap.hh