OpenASIP: EditConnectionsCmd Class Reference
EditConnectionsCmd Class Reference
#include <EditConnectionsCmd.hh>
Public Member Functions
EditConnectionsCmd ()
virtual ~EditConnectionsCmd ()
virtual bool Do ()
virtual int id () const
virtual EditConnectionsCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing connections.
Definition at line 42 of file EditConnectionsCmd.hh.
Constructor & Destructor Documentation
EditConnectionsCmd()
EditConnectionsCmd::EditConnectionsCmd ()
The Constructor.
Definition at line 47 of file EditConnectionsCmd.cc.
                                      :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_CONNECTIONS) {
}
Referenced by create().
~EditConnectionsCmd()
EditConnectionsCmd::~EditConnectionsCmd () virtual
The Destructor.
Definition at line 56 of file EditConnectionsCmd.cc.
{}
Member Function Documentation
create()
EditConnectionsCmd * EditConnectionsCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 89 of file EditConnectionsCmd.cc.
{
    return new EditConnectionsCmd();
}
References EditConnectionsCmd().
Do()
bool EditConnectionsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file EditConnectionsCmd.cc.
                       {
    MDFView* mdfView = dynamic_cast<MDFView*>(view());
    ChildFrame* frame = dynamic_cast<ChildFrame*>(mdfView->GetFrame());
    assert(frame != NULL);
    mdfView->clearSelection();
    ConnectTool* tool = new ConnectTool(frame, mdfView);
    mdfView->canvas()->setTool(tool);
    return true;
}
References assert, MDFView::canvas(), MDFView::clearSelection(), MachineCanvas::setTool(), and EditorCommand::view().
icon()
string EditConnectionsCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 98 of file EditConnectionsCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_CONNECTIONS;
}
References ProDeConstants::CMD_ICON_EDIT_CONNECTIONS.
id()
int EditConnectionsCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 80 of file EditConnectionsCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_CONNECTIONS;
}
References ProDeConstants::COMMAND_EDIT_CONNECTIONS.
isEnabled()
bool EditConnectionsCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 120 of file EditConnectionsCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string EditConnectionsCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 107 of file EditConnectionsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_CONNECTIONS;
}
References ProDeConstants::CMD_SNAME_EDIT_CONNECTIONS.
The documentation for this class was generated from the following files:
EditConnectionsCmd.hh
EditConnectionsCmd.cc