OpenASIP: AddSocketCmd Class Reference
AddSocketCmd Class Reference
#include <AddSocketCmd.hh>
Public Member Functions
AddSocketCmd ()
virtual bool Do ()
virtual int id () const
virtual AddSocketCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new sockets to the Machine.
Displays a socket dialog and creates a new socket according to the dialog output.
Definition at line 43 of file AddSocketCmd.hh.
Constructor & Destructor Documentation
AddSocketCmd()
AddSocketCmd::AddSocketCmd ()
The Constructor.
Definition at line 53 of file AddSocketCmd.cc.
                           :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_SOCKET) {
}
Referenced by create().
Member Function Documentation
create()
AddSocketCmd * AddSocketCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 120 of file AddSocketCmd.cc.
{
    return new AddSocketCmd();
}
References AddSocketCmd().
Do()
bool AddSocketCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file AddSocketCmd.cc.
                 {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    // Generate name for the new socket.
    Machine::SocketNavigator navigator =
        model->getMachine()->socketNavigator();
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_SOCKET +
        Conversion::toString(i);
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_SOCKET +
            Conversion::toString(i);
        i++;
    }
    Socket* socket = new Socket(newName);
    socket->setMachine(*(model->getMachine()));
    SocketDialog dialog(parentWindow(), socket);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    model->popFromStack();
    return false;
    }
    return false;
}
References assert, ProDeConstants::COMP_NEW_NAME_PREFIX_SOCKET, Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), TTAMachine::Socket::setMachine(), TTAMachine::Machine::socketNavigator(), Conversion::toString(), and EditorCommand::view().
id()
int AddSocketCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 109 of file AddSocketCmd.cc.
                       {
    return ProDeConstants::COMMAND_ADD_SOCKET;
}
References ProDeConstants::COMMAND_ADD_SOCKET.
isEnabled()
bool AddSocketCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 144 of file AddSocketCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddSocketCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 131 of file AddSocketCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_SOCKET;
}
References ProDeConstants::CMD_SNAME_ADD_SOCKET.
The documentation for this class was generated from the following files:
AddSocketCmd.hh
AddSocketCmd.cc