OpenASIP: HDLGenerator::Ext Class Reference
HDLGenerator::Ext Class Reference
#include <WidthTransformations.hh>
Public Member Functions
Ext (std::string name, int extWidth, int signalWidth)
Ext (std::string name, std::string extWidth, int signalWidth)
void write_rtl (std::string name, std::string extWidth, std::string signalWidth)
Public Member Functions inherited from HDLGenerator::LHSValue
LHSValue ()
void hdl (std::ostream &stream, Language lang, int level)
void hdl (std::ostream &stream, Language lang)
void writeSignals (std::unordered_set< std::string > &readList) const
std::string vhdl () const
std::string verilog () const
LHSValue operator|| (LHSValue rhs)
LHSValue operator| (LHSValue rhs)
LHSValue operator&& (LHSValue rhs)
LHSValue operator& (LHSValue rhs)
LHSValue operator^ (LHSValue rhs)
LHSValue operator! ()
LHSValue operator~ ()
Additional Inherited Members
Protected Attributes inherited from HDLGenerator::LHSValue
std::unordered_set< std::string > readList_
std::string vhdl_
std::string verilog_
Detailed Description
Unsigned extend.
Definition at line 39 of file WidthTransformations.hh.
Constructor & Destructor Documentation
Ext() [1/2]
HDLGenerator::Ext::Ext (std::string name, int extWidth, int signalWidth) inline
Definition at line 41 of file WidthTransformations.hh.
{
            readList_.insert(name);
            if (extWidth > signalWidth) {
                write_rtl(name, std::to_string(extWidth),
                          std::to_string(signalWidth));
            } else {
                vhdl_ = name;
                verilog_ = name;
            }
        }
References HDLGenerator::LHSValue::readList_, HDLGenerator::LHSValue::verilog_, HDLGenerator::LHSValue::vhdl_, and write_rtl().
Ext() [2/2]
HDLGenerator::Ext::Ext (std::string name, std::string extWidth, int signalWidth) inline
Definition at line 51 of file WidthTransformations.hh.
{
            readList_.insert(name);
            write_rtl(name,  extWidth, std::to_string(signalWidth));
        }
References HDLGenerator::LHSValue::readList_, and write_rtl().
Member Function Documentation
write_rtl()
void HDLGenerator::Ext::write_rtl (std::string name, std::string extWidth, std::string signalWidth) inline
Definition at line 56 of file WidthTransformations.hh.
{
            vhdl_ = "((" + extWidth + "-1 downto " + signalWidth
                    + " => '0') & " + name + ")";
            verilog_ = "{{" + extWidth + "-" + signalWidth + "{"
                       + "1'b0}}, " + name + "}";
        }
References HDLGenerator::LHSValue::verilog_, and HDLGenerator::LHSValue::vhdl_.
Referenced by Ext(), and Ext().
The documentation for this class was generated from the following file:
WidthTransformations.hh