OpenASIP: CompiledSimulation Class Reference
CompiledSimulation Class Reference abstract
#include <CompiledSimulation.hh>
Public Member Functions
CompiledSimulation (const TTAMachine::Machine &machine, InstructionAddress entryAddress, InstructionAddress lastInstruction, SimulatorFrontend &frontend, CompiledSimController &controller, MemorySystem &memorySystem, bool dynamicCompilation, ProcedureBBRelations &procedureBBRelations)
virtual ~CompiledSimulation ()
virtual void simulateCycle ()=0
virtual void cycleEnd ()
virtual void step (double count)
virtual void next (int count)
virtual void run ()
virtual void runUntil (UIntWord address)
virtual InstructionAddress programCounter () const
virtual InstructionAddress lastExecutedInstruction () const
virtual ClockCycleCount cycleCount () const
virtual SimValue registerFileValue (const char *rfName, int registerIndex)
virtual SimValue immediateUnitRegisterValue (const char *iuName, int index)
virtual SimValue FUPortValue (const char *fuName, const char *portName)
virtual void requestToStop ()
virtual bool stopRequested () const
virtual bool isFinished () const
virtual ClockCycleCount moveExecutionCount (int moveNumber, InstructionAddress address) const
virtual InstructionAddress basicBlockStart (InstructionAddress address) const
Static Public Member Functions
static void clearFUResults (FUResultType &results)
static void addFUResult (FUResultType &results, ClockCycleCount cycleCount, const SimValue &value, int latency)
static void addFUResult (FUResultType &results, ClockCycleCount cycleCount, const UIntWord &value, int latency)
static void FUResult (SimValue &target, FUResultType &results, ClockCycleCount cycles)
Public Attributes
ClockCycleCount cycleCount_
Number of cycles simulated so far.
int basicBlockCount_
Number of basic blocks gone through.
InstructionAddress jumpTarget_
The jump target. Allows jumping to different addresses in the code.
InstructionAddress programCounter_
The program counter. i.e. which address the simulation is currently at.
InstructionAddress lastExecutedInstruction_
Last executed instruction.
ClockCycleCount cyclesToSimulate_
Number of cycles left to simulate until the execution returns.
bool stopRequested_
Should the simulation stop or not?
bool isFinished_
Is the simulation finished?
OperationPool operationPool_
The operation pool.
SimulateFunction jumpTargetFunc_
Next jump target as a function pointer" << endl.
bool conflictDetected_
A flag for FU conflict detection.
ClockCycleCount * moveExecCounts_
Move execution counts in a C style table.
ClockCycleCount * bbExecCounts_
Basic block execution counts in a C style table.
Protected Member Functions
TTAMachine::FunctionUnit & functionUnit (const char *name) const
DirectAccessMemory & FUMemory (const char *FUName) const
MemorySystem * memorySystem () const
SimulatorFrontend & frontend () const
void msg (const char *message) const
void haltSimulation (const char *file, int line, const char *procedure, const char *message) const
void resizeJumpTable (int newSize)
SimulateFunction getSimulateFunction (InstructionAddress address)
void setJumpTargetFunction (InstructionAddress address, SimulateFunction fp)
void compileAndLoadFunction (InstructionAddress address)
SimValue * getSymbolValue (const char *symbolName)
void addSymbol (const char *symbolName, SimValue &value)
Protected Attributes
bool dynamicCompilation_
Is this a dynamic compiled simulation?
ProcedureBBRelations & procedureBBRelations_
A struct for finding out procedure begins from procedure's basic blocks.
const TTAMachine::Machine & machine_
The simulated machine.
const InstructionAddress entryAddress_
Entry address of the program.
const InstructionAddress lastInstruction_
Last instruction of the program.
Private Member Functions
CompiledSimulation (const CompiledSimulation &)
Copying not allowed.
CompiledSimulation & operator= (const CompiledSimulation &)
Assignment not allowed.
Private Attributes
CompiledSimulationPimpl * pimpl_
Private implementation in a separate source file.
Detailed Description
An abstract class that is used as a base for all the compiled simulations
The derived classes are generated by CompiledSimCodeGenerator and then get loaded as plugins by the CompiledSimController.
Definition at line 112 of file CompiledSimulation.hh.
Constructor & Destructor Documentation
CompiledSimulation() [1/2]
CompiledSimulation::CompiledSimulation (const TTAMachine::Machine & machine, InstructionAddress entryAddress, InstructionAddress lastInstruction, SimulatorFrontend & frontend, CompiledSimController & controller, MemorySystem & memorySystem, bool dynamicCompilation, ProcedureBBRelations & procedureBBRelations)
The constructor
Grabs all shared data from machine and program and saves them for easy access for later usage.
Parameters
machine The simulated machine
program The simulated program
frontend The simulation frontend
memorySystem The memory system
Definition at line 72 of file CompiledSimulation.cc.
                                                :
    cycleCount_(0),
    basicBlockCount_(0),
    jumpTarget_(entryAddress),
    programCounter_(entryAddress),
    lastExecutedInstruction_(0),
    cyclesToSimulate_(MAX_CYCLES),
    stopRequested_(false),
    isFinished_(false),
    conflictDetected_(false),
    dynamicCompilation_(dynamicCompilation),
    procedureBBRelations_(procedureBBRelations),
    machine_(machine),
    entryAddress_(entryAddress),
    lastInstruction_(lastInstruction), pimpl_(new CompiledSimulationPimpl()) {
    pimpl_->memorySystem_ = &memorySystem;
    pimpl_->frontend_ = &frontend;
    pimpl_->controller_ = &controller;
    // Allocate memory for calculating move and basic block execution counts
    int moveCount = pimpl_->controller_->program().moveCount();
    moveExecCounts_ = new ClockCycleCount[moveCount];
    for (int i = 0; i < moveCount; ++i) {
        moveExecCounts_[i] = 0;
    }
    int bbCount = lastInstruction - entryAddress + 1;
    bbExecCounts_ = new ClockCycleCount[bbCount];
    for (int i = 0; i < bbCount; ++i) {
        bbExecCounts_[i] = 0;
    }
    // Find program exit points
    pimpl_->exitPoints_ = pimpl_->controller_->findProgramExitPoints(
        pimpl_->controller_->program(), machine_);
}
References bbExecCounts_, CompiledSimulationPimpl::controller_, CompiledSimulationPimpl::exitPoints_, TTASimulationController::findProgramExitPoints(), frontend(), CompiledSimulationPimpl::frontend_, machine_, memorySystem(), CompiledSimulationPimpl::memorySystem_, TTAProgram::Program::moveCount(), moveExecCounts_, pimpl_, and CompiledSimController::program().
~CompiledSimulation()
CompiledSimulation::~CompiledSimulation () virtual
The destructor. Frees private implementation
Definition at line 120 of file CompiledSimulation.cc.
{
    delete[] bbExecCounts_;
    bbExecCounts_ = NULL;
    delete[] moveExecCounts_;
    moveExecCounts_ = NULL;
    delete pimpl_;
    pimpl_ = NULL;
}
References bbExecCounts_, moveExecCounts_, and pimpl_.
CompiledSimulation() [2/2]
CompiledSimulation::CompiledSimulation (const CompiledSimulation &) private
Copying not allowed.
Member Function Documentation
addFUResult() [1/2]
static void CompiledSimulation::addFUResult (FUResultType & results, ClockCycleCount cycleCount, const SimValue & value, int latency) inline static
addFUResult() [2/2]
static void CompiledSimulation::addFUResult (FUResultType & results, ClockCycleCount cycleCount, const UIntWord & value, int latency) inline static
addSymbol()
void CompiledSimulation::addSymbol (const char * symbolName, SimValue & value) protected
Adds a new symbol name -> SimValue pair to the symbols map
Parameters
symbolName the symbol name
value the SimValue
Definition at line 597 of file CompiledSimulation.cc.
{
    pimpl_->symbols_[std::string(symbolName)] = &value;
}
References pimpl_, and CompiledSimulationPimpl::symbols_.
basicBlockStart()
InstructionAddress CompiledSimulation::basicBlockStart (InstructionAddress address) const virtual
Returns start of the basic block for given address of a basic block
Parameters
address address of a basic block
Returns
start address of the basic block
Definition at line 389 of file CompiledSimulation.cc.
{
    return pimpl_->controller_->basicBlockStart(address);
}
References CompiledSimController::basicBlockStart(), CompiledSimulationPimpl::controller_, and pimpl_.
Referenced by moveExecutionCount().
clearFUResults()
static void CompiledSimulation::clearFUResults (FUResultType & results) inline static
compileAndLoadFunction()
void CompiledSimulation::compileAndLoadFunction (InstructionAddress address) protected
Compiles and loads all simulate functions belonging to a procedure containing the given address.
Parameters
address (any) address of a procedure to compile
Definition at line 535 of file CompiledSimulation.cc.
{
    InstructionAddress procedureStart =
        procedureBBRelations_.procedureStart[address];
    // Files compiled so far
    std::set<std::string> compiledFiles;
    CompiledSimSymbolGenerator symbolGen(Conversion::toString(pimpl_->controller_));
    // Get basic blocks of a procedure
    typedef ProcedureBBRelations::BasicBlockStarts::iterator BBIterator;
    std::pair<BBIterator, BBIterator> equalRange =
        procedureBBRelations_.basicBlockStarts.equal_range(procedureStart);
    // Loop all basic blocks of a procedure, then compile all its files
    for (BBIterator it = equalRange.first; it != equalRange.second; ++it) {
        std::string file = procedureBBRelations_.basicBlockFiles[it->second];
        // Compile the file if it hasn't been already
        if (compiledFiles.find(file) == compiledFiles.end()) {
            pimpl_->compiler_.compileToSO(file);
            std::string soPath = FileSystem::directoryOfPath(file)
                + FileSystem::DIRECTORY_SEPARATOR
                + FileSystem::fileNameBody(file) + ".so";
            pimpl_->pluginTools_.registerModule(soPath);
            compiledFiles.insert(file);
        }
        // Load the generated simulate function
        SimulateFunction fn;
        pimpl_->pluginTools_.importSymbol(
            symbolGen.basicBlockSymbol(it->second), fn);
        setJumpTargetFunction(it->second, fn);
    }
}
References ProcedureBBRelations::basicBlockFiles, ProcedureBBRelations::basicBlockStarts, CompiledSimSymbolGenerator::basicBlockSymbol(), CompiledSimulationPimpl::compiler_, CompiledSimCompiler::compileToSO(), CompiledSimulationPimpl::controller_, FileSystem::DIRECTORY_SEPARATOR, FileSystem::directoryOfPath(), FileSystem::fileNameBody(), PluginTools::importSymbol(), pimpl_, CompiledSimulationPimpl::pluginTools_, procedureBBRelations_, ProcedureBBRelations::procedureStart, PluginTools::registerModule(), setJumpTargetFunction(), and Conversion::toString().
Referenced by getSimulateFunction().
cycleCount()
ClockCycleCount CompiledSimulation::cycleCount () const virtual
Returns the current cycle count
Returns
the current cycle count
Definition at line 242 of file CompiledSimulation.cc.
{
    return cycleCount_;
}
References cycleCount_.
cycleEnd()
void CompiledSimulation::cycleEnd () virtual
Lets the simulator frontend handle a single cycle end.
Used for example when generating traces.
Definition at line 138 of file CompiledSimulation.cc.
{
    lastExecutedInstruction_ = programCounter_;
    programCounter_++;
    pimpl_->frontend_->eventHandler().handleEvent(
        SimulationEventHandler::SE_CYCLE_END);
}
References SimulatorFrontend::eventHandler(), CompiledSimulationPimpl::frontend_, Informer::handleEvent(), lastExecutedInstruction_, pimpl_, programCounter_, and SimulationEventHandler::SE_CYCLE_END.
frontend()
SimulatorFrontend & CompiledSimulation::frontend () const protected
Returns a reference to the simulator frontend
Returns
a reference to the simulator frontend
Definition at line 440 of file CompiledSimulation.cc.
{
    return *(pimpl_->frontend_);
}
References CompiledSimulationPimpl::frontend_, and pimpl_.
Referenced by CompiledSimulation().
FUMemory()
DirectAccessMemory & CompiledSimulation::FUMemory (const char * FUName) const protected
Returns a memory object of the given function unit
Parameters
FUName name of the function unit
Returns
memory object of the given function unit
Exceptions
InstanceNotFound If an item is not found
Definition at line 413 of file CompiledSimulation.cc.
{
    assert(
        machine_.functionUnitNavigator().item(FUName)->addressSpace() != NULL);
    return
        dynamic_cast<DirectAccessMemory&>(
            *memorySystem()->memory(
                *machine_.functionUnitNavigator().item(
                    FUName)->addressSpace()).get());
}
References assert, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MemorySystem::memory(), and memorySystem().
functionUnit()
TTAMachine::FunctionUnit & CompiledSimulation::functionUnit (const char * name) const protected
Returns a function unit of the given name
Parameters
name name of the function unit to return
Returns
function unit of given name
Exceptions
InstanceNotFound If a function unit is not found
Definition at line 401 of file CompiledSimulation.cc.
{
    return *machine_.functionUnitNavigator().item(name);
}
References TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), and machine_.
Referenced by FUPortValue().
FUPortValue()
SimValue CompiledSimulation::FUPortValue (const char * fuName, const char * portName) virtual
Returns the value of the given FU port
Parameters
fuName Name of the FU
portIndex index of the port in the FU
Returns
A SimValue containing the port's present value
Exceptions
InstanceNotFound If the FU port cannot be found
Definition at line 306 of file CompiledSimulation.cc.
{
    CompiledSimSymbolGenerator symbolGen(Conversion::toString(pimpl_->controller_));
    FunctionUnit* fu = NULL;
    try {
        fu = &functionUnit(fuName);
    } catch(InstanceNotFound& e) {
        fu = machine_.controlUnit();
    }
    std::string fuPort = symbolGen.portSymbol(*fu->port(portName));
    CompiledSimulationPimpl::Symbols::const_iterator fuPortIterator =
        pimpl_->symbols_.find(fuPort);
    if (fuPortIterator != pimpl_->symbols_.end()) {
        return *(fuPortIterator->second);
    } else {
        throw InstanceNotFound(__FILE__, __LINE__, __func__,
            "FU port " + std::string(fuPort) + " not found.");
    }
}
References __func__, CompiledSimulationPimpl::controller_, TTAMachine::Machine::controlUnit(), functionUnit(), machine_, pimpl_, TTAMachine::FunctionUnit::port(), CompiledSimSymbolGenerator::portSymbol(), CompiledSimulationPimpl::symbols_, and Conversion::toString().
FUResult()
static void CompiledSimulation::FUResult (SimValue & target, FUResultType & results, ClockCycleCount cycles) inline static
getSimulateFunction()
SimulateFunction CompiledSimulation::getSimulateFunction (InstructionAddress address) protected
Gets the simulate function of given address from the jump table.
If this is a dynamic compiled simulation, it'll first check if the simulate- function is available. If not, it will compile the required files first and then loads the simulate function symbols.
Parameters
address address to get the simulate function for
Returns
Simulate Function of given address from the jump table
Exceptions
SimulationExecutionError If the jump function couldn't be gotten
Definition at line 494 of file CompiledSimulation.cc.
{
    // Is there an already existing simulate function in the given address?
    SimulateFunction targetFunction = pimpl_->jumpTable_[address];
    if (targetFunction != 0) {
            return targetFunction;
    }
    if (dynamicCompilation_) {
        compileAndLoadFunction(address);
        targetFunction = pimpl_->jumpTable_[address];
        if (targetFunction != 0) {
            return targetFunction;
        }
    }
    throw SimulationExecutionError(__FILE__, __LINE__, __FUNCTION__,
        "Cannot simulate jump to address " + Conversion::toString(address) +
        ". Please try with the interpretive simulation engine." );
}
References compileAndLoadFunction(), dynamicCompilation_, CompiledSimulationPimpl::jumpTable_, pimpl_, and Conversion::toString().
getSymbolValue()
SimValue * CompiledSimulation::getSymbolValue (const char * symbolName) protected
Returns value of the given symbol (be it RF, FU, or IU)
Parameters
symbolName Symbol name in the generated code
Returns
a pointer to the symbol's SimValue or 0 if the symbol wasn't found
Definition at line 579 of file CompiledSimulation.cc.
{
    CompiledSimulationPimpl::Symbols::iterator it = pimpl_->symbols_.find(
        std::string(symbolName));
    if (it != pimpl_->symbols_.end()) {
        return it->second;
    } else {
        return 0;
    }
}
References pimpl_, and CompiledSimulationPimpl::symbols_.
haltSimulation()
void CompiledSimulation::haltSimulation (const char * file, int line, const char * procedure, const char * message) const protected
Halts simulation by throwing an exception with a message attached to it
Parameters
file file where the exception happened, i.e. FILE
line line where the exception happened, i.e. LINE
procedure function where the exception happened, i.e. FUNCTION
message message to attach
Exceptions
SimulationExecutionError thrown always
Definition at line 464 of file CompiledSimulation.cc.
{
    throw SimulationExecutionError(file, line, procedure, message);
}
immediateUnitRegisterValue()
SimValue CompiledSimulation::immediateUnitRegisterValue (const char * iuName, int index) virtual
Returns the value of the selected immediate unit register
Parameters
iuName The name of the immediate unit
index Index of the immediate register
Returns
A SimValue containing the present immediate register value
Exceptions
InstanceNotFound If the immediate unit cannot be found
Definition at line 280 of file CompiledSimulation.cc.
{
    CompiledSimSymbolGenerator symbolGen(Conversion::toString(pimpl_->controller_));
    ImmediateUnit& iu = *machine_.immediateUnitNavigator().item(iuName);
    std::string immediateUnit = symbolGen.immediateRegisterSymbol(
        iu, index);
    CompiledSimulationPimpl::Symbols::const_iterator iuIterator =
        pimpl_->symbols_.find(immediateUnit);
    if (iuIterator != pimpl_->symbols_.end()) {
        return *(iuIterator->second);
    } else {
        throw InstanceNotFound(__FILE__, __LINE__, __func__,
            "Immediate unit " + std::string(iuName) + " not found.");
    }
}
References __func__, CompiledSimulationPimpl::controller_, CompiledSimSymbolGenerator::immediateRegisterSymbol(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, pimpl_, CompiledSimulationPimpl::symbols_, and Conversion::toString().
isFinished()
bool CompiledSimulation::isFinished () const virtual
Returns true if the simulation is finished
Returns
true if the simulation is finished
Definition at line 354 of file CompiledSimulation.cc.
{
    return isFinished_;
}
References isFinished_.
lastExecutedInstruction()
InstructionAddress CompiledSimulation::lastExecutedInstruction () const virtual
Returns address of the last executed instruction
Returns
Address of the last executed instruction
Definition at line 233 of file CompiledSimulation.cc.
{
    return lastExecutedInstruction_;
}
References lastExecutedInstruction_.
memorySystem()
MemorySystem * CompiledSimulation::memorySystem () const protected
Returns a pointer to the memory system
Returns
a pointer to the memory system
Definition at line 429 of file CompiledSimulation.cc.
{
    assert (pimpl_->memorySystem_ != NULL);
    return pimpl_->memorySystem_;
}
References assert, CompiledSimulationPimpl::memorySystem_, and pimpl_.
Referenced by CompiledSimulation(), and FUMemory().
moveExecutionCount()
ClockCycleCount CompiledSimulation::moveExecutionCount (int moveNumber, InstructionAddress address) const virtual
Returns move execution count for move #moveNumber.
Parameters
moveNumber move number as in POM
Returns
move execution count
Definition at line 365 of file CompiledSimulation.cc.
{
    const Program& program = pimpl_->controller_->program();
    InstructionAddress programStartAddress = program.startAddress().location();
    const Move& move = program.moveAt(moveNumber);
    if (move.isUnconditional() && pimpl_->exitPoints_.find(address) ==
        pimpl_->exitPoints_.end()) {
        // Grab the whole basic block execution count
        InstructionAddress bbStart = basicBlockStart(address -
            programStartAddress);
        return bbExecCounts_[bbStart];
    } else { // guarded move or an exit point, grab single move execution count
        return moveExecCounts_[moveNumber];
    }
}
References basicBlockStart(), bbExecCounts_, CompiledSimulationPimpl::controller_, CompiledSimulationPimpl::exitPoints_, TTAProgram::Move::isUnconditional(), TTAProgram::Address::location(), moveExecCounts_, pimpl_, program, CompiledSimController::program(), and TTAProgram::Program::startAddress().
Referenced by CompiledSimUtilizationStats::calculate().
msg()
void CompiledSimulation::msg (const char * message) const protected
A short cut for printing debugging info from the compiled code.
Parameters
message The message string to be shown on the log stream
Definition at line 450 of file CompiledSimulation.cc.
{
    Application::logStream() << message << std::endl;
}
References Application::logStream().
Referenced by next().
next()
void CompiledSimulation::next (int count) virtual
Throws an exception since this feature is not supported yet!
Exceptions
SimulationExecutionError always thrown
Definition at line 170 of file CompiledSimulation.cc.
{
    std::string msg(
        "Command nexti not yet supported in the compiled simulation!");
    throw SimulationExecutionError(__FILE__, __LINE__, __FUNCTION__, msg);
    if (count) {}
}
References msg().
operator=()
CompiledSimulation & CompiledSimulation::operator= (const CompiledSimulation &) private
Assignment not allowed.
programCounter()
InstructionAddress CompiledSimulation::programCounter () const virtual
Returns the value of the current PC
Returns
the value of the current PC
Definition at line 223 of file CompiledSimulation.cc.
{
    return programCounter_;
}
References programCounter_.
registerFileValue()
SimValue CompiledSimulation::registerFileValue (const char * rfName, int registerIndex) virtual
Returns the value of the selected register
Parameters
rfName The name of the register file
registerIndex index of the register in the RF
Returns
A SimValue containing the present register value
Exceptions
InstanceNotFound If the RF cannot be found
Definition at line 255 of file CompiledSimulation.cc.
{
    CompiledSimSymbolGenerator symbolGen(Conversion::toString(pimpl_->controller_));
    RegisterFile& rf = *machine_.registerFileNavigator().item(rfName);
    std::string registerFile = symbolGen.registerSymbol(rf, registerIndex);
    CompiledSimulationPimpl::Symbols::const_iterator rfIterator =
        pimpl_->symbols_.find(registerFile);
    if (rfIterator != pimpl_->symbols_.end()) {
        return *(rfIterator->second);
    } else {
        throw InstanceNotFound(__FILE__, __LINE__, __func__,
            "Register file " + std::string(rfName) + " not found.");
    }
}
References __func__, CompiledSimulationPimpl::controller_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, pimpl_, TTAMachine::Machine::registerFileNavigator(), CompiledSimSymbolGenerator::registerSymbol(), CompiledSimulationPimpl::symbols_, and Conversion::toString().
requestToStop()
void CompiledSimulation::requestToStop () virtual
Sets the simulation to be requested to stop
Definition at line 332 of file CompiledSimulation.cc.
{
    stopRequested_ = true;
}
References stopRequested_.
resizeJumpTable()
void CompiledSimulation::resizeJumpTable (int newSize) protected
Resizes the jump table
Parameters
newSize New size
Definition at line 478 of file CompiledSimulation.cc.
{
    pimpl_->jumpTable_.resize(newSize, 0);
}
References CompiledSimulationPimpl::jumpTable_, and pimpl_.
run()
void CompiledSimulation::run () virtual
Runs the simulation until it is finished or an exception occurs
Note
Advances only at an accuracy of a one basic block!
Parameters
address An address the simulation is allowed to stop after
Exceptions
SimulationExecutionError If a runtime error occurs in the simulated program.
Definition at line 189 of file CompiledSimulation.cc.
{
    cyclesToSimulate_ = MAX_CYCLES;
    stopRequested_ = false;
    while (!isFinished_ && !stopRequested_) {
        simulateCycle();
    }
}
References cyclesToSimulate_, isFinished_, MAX_CYCLES, simulateCycle(), and stopRequested_.
runUntil()
void CompiledSimulation::runUntil (UIntWord address) virtual
Advance the simulation until a given address is reached
Note
Advances only at an accuracy of a one basic block!
Parameters
address An address the simulation is allowed to stop after
Exceptions
SimulationExecutionError If a runtime error occurs in the simulated program.
Definition at line 207 of file CompiledSimulation.cc.
{
    cyclesToSimulate_ = MAX_CYCLES;
    stopRequested_ = false;
    while ((!stopRequested_ && !isFinished_ &&
        (jumpTarget_ != address || cycleCount_ == 0))) {
        simulateCycle();
    }
}
References cycleCount_, cyclesToSimulate_, isFinished_, jumpTarget_, MAX_CYCLES, simulateCycle(), and stopRequested_.
setJumpTargetFunction()
void CompiledSimulation::setJumpTargetFunction (InstructionAddress address, SimulateFunction fp) protected
Sets a jump target function for given address at the jump table
Parameters
address address to set a jump function for
fp function pointer to set at the address
Definition at line 522 of file CompiledSimulation.cc.
{
    pimpl_->jumpTable_[address] = fp;
}
References CompiledSimulationPimpl::jumpTable_, and pimpl_.
Referenced by compileAndLoadFunction().
simulateCycle()
virtual void CompiledSimulation::simulateCycle () pure virtual
Referenced by run(), runUntil(), and step().
step()
void CompiledSimulation::step (double count) virtual
Advance the simulation by a given amout of cycles.
Note
Advances only at an accuracy of a one basic block!
Parameters
count The number of cycles the simulation should be advanced at least
Exceptions
SimulationExecutionError If a runtime error occurs in the simulated program.
Definition at line 155 of file CompiledSimulation.cc.
{
    cyclesToSimulate_ = cycleCount_ + static_cast<ClockCycleCount>(count);
    stopRequested_ = false;
    while (!stopRequested_ && !isFinished_) {
        simulateCycle();
    }
}
References cycleCount_, cyclesToSimulate_, isFinished_, simulateCycle(), and stopRequested_.
stopRequested()
bool CompiledSimulation::stopRequested () const virtual
Returns true if the simulation is requested to stop
This can be either because the simulation has finished or the requested amount of cycles has been simulated.
Returns
true if the simulation should stop
Definition at line 345 of file CompiledSimulation.cc.
{
    return stopRequested_;
}
References stopRequested_.
Member Data Documentation
basicBlockCount_
int CompiledSimulation::basicBlockCount_
Number of basic blocks gone through.
Definition at line 164 of file CompiledSimulation.hh.
bbExecCounts_
ClockCycleCount* CompiledSimulation::bbExecCounts_
Basic block execution counts in a C style table.
Definition at line 192 of file CompiledSimulation.hh.
Referenced by CompiledSimulation(), moveExecutionCount(), and ~CompiledSimulation().
conflictDetected_
bool CompiledSimulation::conflictDetected_
A flag for FU conflict detection.
Definition at line 184 of file CompiledSimulation.hh.
cycleCount_
ClockCycleCount CompiledSimulation::cycleCount_
Number of cycles simulated so far.
Definition at line 162 of file CompiledSimulation.hh.
Referenced by cycleCount(), runUntil(), and step().
cyclesToSimulate_
ClockCycleCount CompiledSimulation::cyclesToSimulate_
Number of cycles left to simulate until the execution returns.
Definition at line 172 of file CompiledSimulation.hh.
Referenced by run(), runUntil(), and step().
dynamicCompilation_
bool CompiledSimulation::dynamicCompilation_ protected
Is this a dynamic compiled simulation?
Definition at line 236 of file CompiledSimulation.hh.
Referenced by getSimulateFunction().
entryAddress_
const InstructionAddress CompiledSimulation::entryAddress_ protected
Entry address of the program.
Definition at line 245 of file CompiledSimulation.hh.
isFinished_
bool CompiledSimulation::isFinished_
Is the simulation finished?
Definition at line 176 of file CompiledSimulation.hh.
Referenced by isFinished(), run(), runUntil(), and step().
jumpTarget_
InstructionAddress CompiledSimulation::jumpTarget_
The jump target. Allows jumping to different addresses in the code.
Definition at line 166 of file CompiledSimulation.hh.
Referenced by runUntil().
jumpTargetFunc_
SimulateFunction CompiledSimulation::jumpTargetFunc_
Next jump target as a function pointer" << endl.
Definition at line 181 of file CompiledSimulation.hh.
lastExecutedInstruction_
InstructionAddress CompiledSimulation::lastExecutedInstruction_
Last executed instruction.
Definition at line 170 of file CompiledSimulation.hh.
Referenced by cycleEnd(), and lastExecutedInstruction().
lastInstruction_
const InstructionAddress CompiledSimulation::lastInstruction_ protected
Last instruction of the program.
Definition at line 247 of file CompiledSimulation.hh.
machine_
const TTAMachine::Machine& CompiledSimulation::machine_ protected
The simulated machine.
Definition at line 242 of file CompiledSimulation.hh.
Referenced by CompiledSimulation(), FUMemory(), functionUnit(), FUPortValue(), immediateUnitRegisterValue(), and registerFileValue().
moveExecCounts_
ClockCycleCount* CompiledSimulation::moveExecCounts_
Move execution counts in a C style table.
Definition at line 189 of file CompiledSimulation.hh.
Referenced by CompiledSimulation(), moveExecutionCount(), and ~CompiledSimulation().
operationPool_
OperationPool CompiledSimulation::operationPool_
The operation pool.
Definition at line 179 of file CompiledSimulation.hh.
pimpl_
CompiledSimulationPimpl* CompiledSimulation::pimpl_ private
Private implementation in a separate source file.
Definition at line 256 of file CompiledSimulation.hh.
Referenced by addSymbol(), basicBlockStart(), compileAndLoadFunction(), CompiledSimulation(), cycleEnd(), frontend(), FUPortValue(), getSimulateFunction(), getSymbolValue(), immediateUnitRegisterValue(), memorySystem(), moveExecutionCount(), registerFileValue(), resizeJumpTable(), setJumpTargetFunction(), and ~CompiledSimulation().
procedureBBRelations_
ProcedureBBRelations& CompiledSimulation::procedureBBRelations_ protected
A struct for finding out procedure begins from procedure's basic blocks.
Definition at line 239 of file CompiledSimulation.hh.
Referenced by compileAndLoadFunction().
programCounter_
InstructionAddress CompiledSimulation::programCounter_
The program counter. i.e. which address the simulation is currently at.
Definition at line 168 of file CompiledSimulation.hh.
Referenced by cycleEnd(), and programCounter().
stopRequested_
bool CompiledSimulation::stopRequested_
Should the simulation stop or not?
Definition at line 174 of file CompiledSimulation.hh.
Referenced by requestToStop(), run(), runUntil(), step(), and stopRequested().
The documentation for this class was generated from the following files:
CompiledSimulation.hh
CompiledSimulation.cc