OpenASIP: DropDownMenu Class Reference
DropDownMenu Class Reference
#include <DropDownMenu.hh>
Public Types
enum MenuType { MENU_PATH , MENU_MODULE , MENU_OPERATION }
Public Member Functions
DropDownMenu (MenuType type)
virtual ~DropDownMenu ()
Private Member Functions
DropDownMenu (const DropDownMenu &)
Copying not allowed.
DropDownMenu & operator= (const DropDownMenu &)
Assignment not allowed.
void onMenuEvent (wxCommandEvent &event)
void updateMenu ()
Detailed Description
Class that models drop down menu.
Drop down menu is shown, when user clicks right mouse button over tree item or list item in main window.
Definition at line 44 of file DropDownMenu.hh.
Member Enumeration Documentation
MenuType
enum DropDownMenu::MenuType
Type of the drop down menu.
Enumerator
MENU_PATH
Path menu.
MENU_MODULE
Module menu.
MENU_OPERATION
Operation menu.
Definition at line 50 of file DropDownMenu.hh.
                  {
        MENU_PATH,      ///< Path menu.
        MENU_MODULE,    ///< Module menu.
        MENU_OPERATION  ///< Operation menu.
    };
Constructor & Destructor Documentation
DropDownMenu() [1/2]
DropDownMenu::DropDownMenu (MenuType type) explicit
Constructor.
param type The type of the drop down menu.
Definition at line 54 of file DropDownMenu.cc.
                                        : wxMenu() {
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    switch (type) {
    case MENU_PATH: {
        format fmt = texts.text(OSEdTextGenerator::TXT_MENU_ADD_MODULE);
        Append(
            OSEdConstants::CMD_ADD_MODULE,
            WxConversion::toWxString(fmt.str()));
    }
        break;
    case MENU_MODULE: {
        format fmt = texts.text(OSEdTextGenerator::TXT_MENU_ADD_OPERATION);
        Append(
            OSEdConstants::CMD_ADD_OPERATION,
            WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_MENU_REMOVE_MODULE);
        Append(
            OSEdConstants::CMD_REMOVE_MODULE,
            WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_MENU_BUILD);
        Append(
            OSEdConstants::CMD_BUILD, WxConversion::toWxString(fmt.str()));
    }
        break;
    case MENU_OPERATION: {
        format fmt = texts.text(OSEdTextGenerator::TXT_MENU_MODIFY_PROPERTIES);
        Append(
            OSEdConstants::CMD_PROPERTIES,
            WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_MENU_MODIFY_BEHAVIOR);
        Append(
            OSEdConstants::CMD_MODIFY_BEHAVIOR,
            WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_MENU_REMOVE_OPERATION);
        Append(
            OSEdConstants::CMD_REMOVE_OPERATION,
            WxConversion::toWxString(fmt.str()));
        fmt = texts.text(OSEdTextGenerator::TXT_MENU_SIMULATE);
        Append(
            OSEdConstants::CMD_SIMULATE,
            WxConversion::toWxString(fmt.str()));
    }
        break;
    default:
        break;
    }
    updateMenu();
}
References OSEdConstants::CMD_ADD_MODULE, OSEdConstants::CMD_ADD_OPERATION, OSEdConstants::CMD_BUILD, OSEdConstants::CMD_MODIFY_BEHAVIOR, OSEdConstants::CMD_PROPERTIES, OSEdConstants::CMD_REMOVE_MODULE, OSEdConstants::CMD_REMOVE_OPERATION, OSEdConstants::CMD_SIMULATE, OSEdTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_MENU_ADD_MODULE, OSEdTextGenerator::TXT_MENU_ADD_OPERATION, OSEdTextGenerator::TXT_MENU_BUILD, OSEdTextGenerator::TXT_MENU_MODIFY_BEHAVIOR, OSEdTextGenerator::TXT_MENU_MODIFY_PROPERTIES, OSEdTextGenerator::TXT_MENU_REMOVE_MODULE, OSEdTextGenerator::TXT_MENU_REMOVE_OPERATION, and OSEdTextGenerator::TXT_MENU_SIMULATE.
~DropDownMenu()
DropDownMenu::~DropDownMenu () virtual
Destructor.
Definition at line 114 of file DropDownMenu.cc.
{
}
DropDownMenu() [2/2]
DropDownMenu::DropDownMenu (const DropDownMenu &) private
Copying not allowed.
Member Function Documentation
onMenuEvent()
void DropDownMenu::onMenuEvent (wxCommandEvent & event) private
Handles the menu commands.
Parameters
event The event to be handled.
Definition at line 123 of file DropDownMenu.cc.
{
    wxGetApp().mainFrame()->onCommandEvent(event);
}
operator=()
DropDownMenu & DropDownMenu::operator= (const DropDownMenu &) private
Assignment not allowed.
updateMenu()
void DropDownMenu::updateMenu () private
Updates the menus enabled/disabled status.
Definition at line 131 of file DropDownMenu.cc.
{
    CommandRegistry* registry = wxGetApp().mainFrame()->registry();
    GUICommand* command = registry->firstCommand();
    while (command != NULL) {
        if (FindItem(command->id()) != NULL) {
            if (command->isEnabled()) {
                Enable(command->id(), true);
            } else {
                Enable(command->id(), false);
            }
        }
        command = registry->nextCommand();
    }
}
References CommandRegistry::firstCommand(), GUICommand::id(), GUICommand::isEnabled(), and CommandRegistry::nextCommand().
The documentation for this class was generated from the following files:
DropDownMenu.hh
DropDownMenu.cc