OpenASIP: VertexList Class Reference
VertexList Class Reference
#include <VertexList.hh>
Public Member Functions
VertexList ()
~VertexList ()
void addVertex (int x, int y)
size_t size () const
int vertexX (size_t index) const
int vertexY (size_t index) const
void clear ()
Private Member Functions
VertexList (const VertexList &)
Copying forbidden.
VertexList & operator= (const VertexList &)
Assignment forbidden.
Private Attributes
std::vector< std::pair< int, int > > vertices_
Vector containing vertices in the list.
Detailed Description
VertexList is a class for storing x,y coordinate pairs in a list.
Definition at line 42 of file VertexList.hh.
Constructor & Destructor Documentation
VertexList() [1/2]
VertexList::VertexList ()
The Constructor
Definition at line 39 of file VertexList.cc.
                       {
}
~VertexList()
VertexList::~VertexList ()
The Destructor.
Definition at line 46 of file VertexList.cc.
{
}
VertexList() [2/2]
VertexList::VertexList (const VertexList &) private
Copying forbidden.
Member Function Documentation
addVertex()
void VertexList::addVertex (int x, int y)
Adds a vertex to the list.
Parameters
x X-coordinate of the vertex.
y Y-coordinate of the vertex.
Definition at line 57 of file VertexList.cc.
{
    std::pair<int, int> vertex(x, y);
    vertices_.push_back(vertex);
}
References vertices_.
Referenced by EPSDC::DoDrawPolygon().
clear()
void VertexList::clear ()
Removes all vertices from the list.
Definition at line 118 of file VertexList.cc.
                  {
    vertices_.clear();
}
References vertices_.
operator=()
VertexList & VertexList::operator= (const VertexList &) private
Assignment forbidden.
size()
size_t VertexList::size () const
Returns vertex count.
Returns
Number of vertices in the list.
Definition at line 68 of file VertexList.cc.
                       {
    return vertices_.size();
}
References vertices_.
Referenced by EPSGenerator::drawFilledPolygon(), EPSGenerator::drawPolygon(), EPSGenerator::drawPolygonPath(), vertexX(), and vertexY().
vertexX()
int VertexList::vertexX (size_t index) const
Returns x-coordinate of a vertex with given index.
Parameters
index Index of the vertex.
Returns
X-coordinate of the vertex.
Exceptions
OutOfRange If the index is out of range.
Definition at line 80 of file VertexList.cc.
{
    if (index > size()) {
        std::string error = "Vertex index out of range";
        std::string proc = "VertexList::vertexX";
        OutOfRange e(__FILE__, __LINE__, proc, error);
        throw e;
    }
    int x = vertices_[index].first;
    return x;
}
References size(), and vertices_.
Referenced by EPSGenerator::drawPolygonPath().
vertexY()
int VertexList::vertexY (size_t index) const
Returns y-coordinate of a vertex with given index.
Parameters
index Index of the vertex.
Returns
Y-coordinate of the vertex.
Exceptions
OutOfRange If the index is out of range.
Definition at line 101 of file VertexList.cc.
{
    if (index > size()) {
        std::string error = "Vertex index out of range";
        std::string proc = "VertexList::vertexY";
        OutOfRange e(__FILE__, __LINE__, proc, error);
        throw e;
    }
    int y = vertices_[index].second;
    return y;
}
References size(), and vertices_.
Referenced by EPSGenerator::drawPolygonPath().
Member Data Documentation
vertices_
std::vector<std::pair<int, int> > VertexList::vertices_ private
Vector containing vertices in the list.
Definition at line 59 of file VertexList.hh.
Referenced by addVertex(), clear(), size(), vertexX(), and vertexY().
The documentation for this class was generated from the following files:
VertexList.hh
VertexList.cc