OpenASIP: OSEdOptions Class Reference
OSEdOptions Class Reference
#include <OSEdOptions.hh>
Public Member Functions
OSEdOptions ()
virtual ~OSEdOptions ()
std::string editor () const
void setEditor (const std::string &editor)
virtual void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Member Functions
OSEdOptions (const OSEdOptions &)
Copying not allowed.
OSEdOptions & operator= (const OSEdOptions &)
Assignment not allowed.
Private Attributes
std::string editor_
Editor used to edit operation behavior files.
Detailed Description
Class that represents the OSEd options.
Options are stored in XML file.
Definition at line 46 of file OSEdOptions.hh.
Constructor & Destructor Documentation
OSEdOptions() [1/2]
OSEdOptions::OSEdOptions ()
Constructor.
Definition at line 44 of file OSEdOptions.cc.
                         : editor_("") {
}
~OSEdOptions()
OSEdOptions::~OSEdOptions () virtual
Destructor.
Definition at line 50 of file OSEdOptions.cc.
{
}
OSEdOptions() [2/2]
OSEdOptions::OSEdOptions (const OSEdOptions &) private
Copying not allowed.
Member Function Documentation
editor()
string OSEdOptions::editor () const
Returns the editor.
Returns
The editor.
Definition at line 59 of file OSEdOptions.cc.
{
    return editor_;
}
References editor_.
Referenced by saveState(), and setEditor().
loadState()
void OSEdOptions::loadState (const ObjectState * state) virtual
Loads the state from the object tree.
Parameters
state The to be loaded.
Implements Serializable.
Definition at line 79 of file OSEdOptions.cc.
{
    try {
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == OSED_EDITOR) {
                editor_ = child->stringValue();
            }
        }
    } catch (const Exception& e) {
        string method = "OSEdOptions::loadState()";
        string msg = "Problems loading state: " + e.errorMessage();
        throw ObjectStateLoadingException(__FILE__, __LINE__, method, msg);
    }
}
References ObjectState::child(), ObjectState::childCount(), editor_, Exception::errorMessage(), ObjectState::name(), OSED_EDITOR, and ObjectState::stringValue().
Referenced by OSEd::OnInit().
operator=()
OSEdOptions & OSEdOptions::operator= (const OSEdOptions &) private
Assignment not allowed.
saveState()
ObjectState * OSEdOptions::saveState () const virtual
Saves the state of the options in ObjectState tree.
Returns
The created ObjectState tree.
Implements Serializable.
Definition at line 100 of file OSEdOptions.cc.
{
    ObjectState* root = new ObjectState(OSED_CONF);
    ObjectState* editor = new ObjectState(OSED_EDITOR);
    editor->setValue(editor_);
    root->addChild(editor);
    return root;
}
References ObjectState::addChild(), editor(), editor_, OSED_CONF, and OSED_EDITOR.
Referenced by OSEd::createDefaultOptions().
setEditor()
void OSEdOptions::setEditor (const std::string & editor)
Sets the editor.
Parameters
editor. Editor to be set.
Definition at line 69 of file OSEdOptions.cc.
{
    editor_ = editor;
}
References editor(), and editor_.
Referenced by OSEd::createDefaultOptions().
Member Data Documentation
editor_
std::string OSEdOptions::editor_ private
Editor used to edit operation behavior files.
Definition at line 63 of file OSEdOptions.hh.
Referenced by editor(), loadState(), saveState(), and setEditor().
The documentation for this class was generated from the following files:
OSEdOptions.hh
OSEdOptions.cc