OpenASIP: EPSDC Class Reference
EPSDC Class Reference
#include <EPSDC.hh>
Public Member Functions
EPSDC ()
virtual ~EPSDC ()
virtual bool Ok () const
virtual void BeginDrawing ()
virtual void EndDrawing ()
virtual void DoDrawText (const wxString &text, wxCoord x, wxCoord y)
virtual void DoDrawLine (wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2)
virtual void DoCrossHair (wxCoord x, wxCoord y)
virtual void DoDrawPoint (wxCoord x, wxCoord y)
virtual void DoDrawIcon (const wxIcon &icon, wxCoord x, wxCoord y)
virtual void DoDrawLines (int n, wxPoint points[], wxCoord xoffset, wxCoord yoffset)
virtual void DoDrawArc (wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2, wxCoord xc, wxCoord yc)
virtual void DoDrawEllipticArc (wxCoord x, wxCoord y, wxCoord width, wxCoord height, double start, double end)
virtual bool DoFloodFill (wxCoord x, wxCoord y, const wxColour &colour, int style)
virtual void DoDrawBitmap (const wxBitmap &bitmap, wxCoord x, wxCoord y, bool transparent)
virtual void DoDrawPolygon (int n, wxPoint points[], wxCoord xoffset=0, wxCoord yoffset=0, int fillStyle=wxODDEVEN_RULE)
virtual void DoDrawRectangle (wxCoord x, wxCoord y, wxCoord width, wxCoord height)
virtual void DoDrawRoundedRectangle (wxCoord x, wxCoord y, wxCoord width, wxCoord height, double radius=20)
virtual void DoDrawEllipse (wxCoord x, wxCoord y, wxCoord width, wxCoord height)
virtual void DoDrawRotatedText (const wxString &text, wxCoord x, wxCoord y, double angle)
virtual bool DoBlit (wxCoord xdest, wxCoord ydest, wxCoord width, wxCoord height, wxDC *source, wxCoord xsrc, wxCoord ysrc, int logicalFunc=wxCOPY, bool useMask=false, wxCoord xsrcMask=-1, wxCoord ysrcMask=-1)
virtual void DoGetSize (wxCoord *width, wxCoord *height) const
virtual void DoGetTextExtent (const wxString &text, wxCoord *w, wxCoord *h, wxCoord *descent=NULL, wxCoord *externalLeading=NULL, wxFont *font=NULL) const
virtual bool DoGetPixel (wxCoord x, wxCoord y, wxColour *colour) const
virtual void DoSetClippingRegionAsRegion (const wxRegion &region)
virtual bool CanDrawBitmap () const
virtual bool CanGetTextExtent () const
virtual void Clear ()
virtual void SetFont (const wxFont &font)
virtual void SetPen (const wxPen &pen)
virtual void SetBrush (const wxBrush &brush)
virtual void SetBackground (const wxBrush &brush)
virtual void SetBackgroundMode (int mode)
virtual void SetPalette (const wxPalette &palette)
virtual void SetLogicalFunction (int function)
virtual wxCoord GetCharHeight () const
virtual wxCoord GetCharWidth () const
virtual int GetDepth () const
virtual bool StartDoc (const wxString &message)
virtual void EndDoc ()
virtual void StartPage ()
virtual void EndPage ()
void setTitle (const std::string &title)
void setCreator (const std::string &creator)
void writeToStream (std::ostream &stream)
Private Member Functions
void setLineColour (const wxColour &colour)
void setFillColour (const wxColour &colour)
void drawCircle (int x, int y, unsigned radius)
Private Attributes
EPSGenerator eps_
EPSGenerator generating the postscript code.
bool fill_
True, if background brush is set to fill the shapes.
unsigned fontSize_
Current font size.
Detailed Description
Encapsulated postscript device context.
EPSDC is a wxWidgets device context for drawing graphics and text to an eps file.
Definition at line 48 of file EPSDC.hh.
Constructor & Destructor Documentation
EPSDC()
EPSDC::EPSDC ()
The Constructor.
Definition at line 42 of file EPSDC.cc.
             : wxDC(), fill_(false), fontSize_(0) {
}
~EPSDC()
EPSDC::~EPSDC () virtual
The Destructor.
Definition at line 48 of file EPSDC.cc.
              {
}
Member Function Documentation
BeginDrawing()
void EPSDC::BeginDrawing () virtual
Called before the drawing ends.
Definition at line 300 of file EPSDC.cc.
                    {
    // Do nothing.
}
CanDrawBitmap()
bool EPSDC::CanDrawBitmap () const virtual
Bitmap drawing not implemented.
Returns
Always false.
Definition at line 220 of file EPSDC.cc.
{
    return false;
}
CanGetTextExtent()
bool EPSDC::CanGetTextExtent () const virtual
NOT IMPLEMENTED
Returns
Always false.
Definition at line 490 of file EPSDC.cc.
{
    return false;
}
Clear()
void EPSDC::Clear () virtual
Clears all drawings on the canvas.
Definition at line 136 of file EPSDC.cc.
             {
    eps_.clearBuffer();
}
References EPSGenerator::clearBuffer(), and eps_.
DoBlit()
bool EPSDC::DoBlit (wxCoord xdest, wxCoord ydest, wxCoord width, wxCoord height, wxDC * source, wxCoord xsrc, wxCoord ysrc, int logicalFunc = wxCOPY, bool useMask = false, wxCoord xsrcMask = -1, wxCoord ysrcMask = -1) virtual
NOT IMPLEMENTED
Definition at line 386 of file EPSDC.cc.
             {
    return false;
}
DoCrossHair()
void EPSDC::DoCrossHair (wxCoord x, wxCoord y) virtual
NOT IMPLEMENTED
Definition at line 285 of file EPSDC.cc.
{
}
DoDrawArc()
void EPSDC::DoDrawArc (wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2, wxCoord xc, wxCoord yc) virtual
NOT IMPLEMENTED
Definition at line 271 of file EPSDC.cc.
{
}
DoDrawBitmap()
void EPSDC::DoDrawBitmap (const wxBitmap & bitmap, wxCoord x, wxCoord y, bool transparent) virtual
NOT IMPLEMENTED
Definition at line 293 of file EPSDC.cc.
{
}
DoDrawEllipse()
void EPSDC::DoDrawEllipse (wxCoord x, wxCoord y, wxCoord width, wxCoord height) virtual
Draws an ellipse on the dc.
Parameters
x Ellipse bounding box lower left corner x-coordinate.
y Ellipse bounding box lower left corner y-coordinate.
width Ellipse width.
height Ellipse height.
Definition at line 361 of file EPSDC.cc.
{
    y = -1 * y -height;
    // Check if the ellipse is actually circle, which will generated more
    // simple postscript-code.
    if (width == height) {
        x += width / 2;
        y += width / 2;
        drawCircle(x, y, width / 2);
        return;
    }
    if (fill_) {
        eps_.drawFilledEllipse(x, y, width, height);
    } else {
        eps_.drawEllipse(x, y, width, height);
    }
}
References drawCircle(), EPSGenerator::drawEllipse(), EPSGenerator::drawFilledEllipse(), eps_, and fill_.
DoDrawEllipticArc()
void EPSDC::DoDrawEllipticArc (wxCoord x, wxCoord y, wxCoord width, wxCoord height, double start, double end) virtual
NOT IMPLEMENTED
Definition at line 330 of file EPSDC.cc.
                {
}
DoDrawIcon()
void EPSDC::DoDrawIcon (const wxIcon & icon, wxCoord x, wxCoord y) virtual
NOT IMPLEMENTED
Definition at line 278 of file EPSDC.cc.
{
}
DoDrawLine()
void EPSDC::DoDrawLine (wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2) virtual
Draws a line on the dc.
Parameters
x1 x-coordinate of the first end of the line.
y1 y-coordinate of the first end of the line.
x2 x-coordinate of the second end of the line.
y2 y-coordinate of the second end of the line.
Definition at line 70 of file EPSDC.cc.
{
    eps_.drawLine(x1, -1 * y1, x2, -1 * y2);
}
References EPSGenerator::drawLine(), and eps_.
DoDrawLines()
void EPSDC::DoDrawLines (int n, wxPoint points[], wxCoord xoffset, wxCoord yoffset) virtual
NOT IMPLEMENTED
Definition at line 318 of file EPSDC.cc.
                 {
}
DoDrawPoint()
void EPSDC::DoDrawPoint (wxCoord x, wxCoord y) virtual
NOT IMPLEMENTED.
Definition at line 248 of file EPSDC.cc.
{
}
DoDrawPolygon()
void EPSDC::DoDrawPolygon (int n, wxPoint vertices[], wxCoord xOffset = 0, wxCoord yOffset = 0, int fillStyle = wxODDEVEN_RULE) virtual
Draws a polygon on the dc.
Parameters
n Number of vertices.
vertices Vertices.
xOffset Offset for x-coordinates.
yOffset Offset for y-coordinates.
Definition at line 83 of file EPSDC.cc.
           {
    // Create VertexList of the vertices.
    VertexList list;
    for (int i = 0; i < n; i++) {
        list.addVertex(vertices[i].x + xOffset, -1 * (vertices[i].y + yOffset));
    }
    if (fill_) {
        eps_.drawFilledPolygon(list);
    } else {
        eps_.drawPolygon(list);
    }
}
References VertexList::addVertex(), EPSGenerator::drawFilledPolygon(), EPSGenerator::drawPolygon(), eps_, and fill_.
DoDrawRectangle()
void EPSDC::DoDrawRectangle (wxCoord x, wxCoord y, wxCoord width, wxCoord height) virtual
Draws a rectangle on the dc.
Parameters
x Lower left corner x-coordinate of the canvas.
y Lower left corner y-coordinate of the canvas.
Definition at line 111 of file EPSDC.cc.
{
    if (fill_) {
        eps_.drawFilledRectangle(x, (-1 * y - height), width, height);
    } else {
        eps_.drawRectangle(x, (-1 * y - height), width, height);
    }
}
References EPSGenerator::drawFilledRectangle(), EPSGenerator::drawRectangle(), eps_, and fill_.
Referenced by DoDrawRoundedRectangle().
DoDrawRotatedText()
void EPSDC::DoDrawRotatedText (const wxString & text, wxCoord x, wxCoord y, double angle) virtual
NOT IMPLEMENTED.
Definition at line 240 of file EPSDC.cc.
{
}
DoDrawRoundedRectangle()
void EPSDC::DoDrawRoundedRectangle (wxCoord x, wxCoord y, wxCoord width, wxCoord height, double radius = 20) virtual
Not implemented, falls back to a rectangle.
Definition at line 343 of file EPSDC.cc.
                {
    DoDrawRectangle(x, y, width, height);
}
References DoDrawRectangle().
DoDrawText()
void EPSDC::DoDrawText (const wxString & text, wxCoord x, wxCoord y) virtual
Draws text on the dc.
Parameters
text Text to draw.
x x-coordinate of the lower left corner of the text.
y y-coordinate of the lower left corner of the text.
Definition at line 127 of file EPSDC.cc.
{
    std::string textStr = WxConversion::toString(text);
    eps_.drawText(x, -1 * y - 12, textStr);
}
References EPSGenerator::drawText(), eps_, and WxConversion::toString().
DoFloodFill()
bool EPSDC::DoFloodFill (wxCoord x, wxCoord y, const wxColour & colour, int style) virtual
NOT IMPLEMENTED
Definition at line 255 of file EPSDC.cc.
{
    return false;
}
DoGetPixel()
bool EPSDC::DoGetPixel (wxCoord x, wxCoord y, wxColour * colour) const virtual
NOT IMPLEMENTED
Returns
Always false.
Definition at line 472 of file EPSDC.cc.
{
    return false;
}
DoGetSize()
void EPSDC::DoGetSize (wxCoord * width, wxCoord * height) const virtual
NOT IMPLEMENTED
Definition at line 264 of file EPSDC.cc.
{
}
DoGetTextExtent()
void EPSDC::DoGetTextExtent (const wxString & text, wxCoord * w, wxCoord * h, wxCoord * descent = NULL, wxCoord * externalLeading = NULL, wxFont * font = NULL) const virtual
Returns crude approximation of the width and height of a text on the dc.
Parameters
w Approximation of width is set as the value of w.
h Approximation of height is set as the value of h.
Definition at line 453 of file EPSDC.cc.
                       {
    // TODO: find a better way to approximate text extent.
    *h = fontSize_;
    *w = Conversion::toInt((fontSize_ * 72.0 / 120) * text.Length());
}
References fontSize_, and Conversion::toInt().
DoSetClippingRegionAsRegion()
void EPSDC::DoSetClippingRegionAsRegion (const wxRegion & region) virtual
NOT IMPLEMENTED
Definition at line 480 of file EPSDC.cc.
{
}
drawCircle()
void EPSDC::drawCircle (int x, int y, unsigned radius) private
Draws a circle.
Parameters
x X-coordinate of the circle centre.
y Y-coordinate of the circle centre.
radius Radius of the circle.
Definition at line 437 of file EPSDC.cc.
{
    if (fill_) {
        eps_.drawFilledCircle(x, y, radius);
    } else {
        eps_.drawCircle(x, y, radius);
    }
}
References EPSGenerator::drawCircle(), EPSGenerator::drawFilledCircle(), eps_, and fill_.
Referenced by DoDrawEllipse().
EndDoc()
void EPSDC::EndDoc () virtual
Ends the document that is being drawn on.
Definition at line 576 of file EPSDC.cc.
              {
    // Do nothing.
}
EndDrawing()
void EPSDC::EndDrawing () virtual
Called when the drawing ends.
Definition at line 308 of file EPSDC.cc.
                  {
    // Do nothing.
}
EndPage()
void EPSDC::EndPage () virtual
Ends current page.
Definition at line 568 of file EPSDC.cc.
               {
    // Do nothing.
}
Referenced by MachineCanvas::saveEPS().
GetCharHeight()
wxCoord EPSDC::GetCharHeight () const virtual
NOT IMPLEMENTED
Returns
Always zero.
Definition at line 532 of file EPSDC.cc.
{
    return 0;
}
GetCharWidth()
wxCoord EPSDC::GetCharWidth () const virtual
NOT IMPLEMENTED
Returns
Always zero.
Definition at line 542 of file EPSDC.cc.
{
    return 0;
}
GetDepth()
int EPSDC::GetDepth () const virtual
NOT IMPLEMENTED
Returns
Always zero.
Definition at line 552 of file EPSDC.cc.
                      {
    return 0;
}
Ok()
bool EPSDC::Ok () const virtual
Returns true, if the DC is ok to use.
Returns
always true
Definition at line 57 of file EPSDC.cc.
                {
   return true;
}
SetBackground()
void EPSDC::SetBackground (const wxBrush & brush) virtual
NOT IMPLEMENTED
Definition at line 499 of file EPSDC.cc.
{
}
SetBackgroundMode()
void EPSDC::SetBackgroundMode (int mode) virtual
NOT IMPLEMENTED
Definition at line 507 of file EPSDC.cc.
{
}
SetBrush()
void EPSDC::SetBrush (const wxBrush & brush) virtual
Sets the brush used for filling shapes with colour.
Only solid and transparent brushes are supported. Everything else is interpreted as transparent brush.
Definition at line 171 of file EPSDC.cc.
{
    if (brush.GetStyle() == wxSOLID) {
        fill_ = true;
        wxColour fillColour = brush.GetColour();
        setFillColour(fillColour);
    } else {
        fill_ = false;
    }
}
References fill_, and setFillColour().
setCreator()
void EPSDC::setCreator (const std::string & creator)
Sets the eps-file creator string.
Parameters
creator String describin the eps file creator.
Definition at line 199 of file EPSDC.cc.
{
    eps_.setCreator(creator);
}
References eps_, and EPSGenerator::setCreator().
Referenced by MachineCanvas::saveEPS().
setFillColour()
void EPSDC::setFillColour (const wxColour & colour) private
Sets the filling colour of the eps generator.
Parameters
colour New filing colour.
Definition at line 421 of file EPSDC.cc.
{
    double redC = (double)colour.Red() / 255;
    double greenC = (double)colour.Green() / 255;
    double blueC = (double)colour.Blue() / 255;
    eps_.setFillColour(redC, greenC, blueC);
}
References eps_, and EPSGenerator::setFillColour().
Referenced by SetBrush().
SetFont()
void EPSDC::SetFont (const wxFont & font) virtual
Sets the dc font.
Only font size is currently set.
Parameters
font Font to set.
Definition at line 148 of file EPSDC.cc.
{
    fontSize_ = font.GetPointSize();
    eps_.setFont(fontSize_);
}
References eps_, fontSize_, and EPSGenerator::setFont().
setLineColour()
void EPSDC::setLineColour (const wxColour & colour) private
Sets the line drawing colour of the eps generator.
Parameters
colour New line drawing colour.
Definition at line 408 of file EPSDC.cc.
{
    double redC = (double)colour.Red() / 255;
    double greenC = (double)colour.Green() / 255;
    double blueC = (double)colour.Blue() / 255;
    eps_.setLineColour(redC, greenC, blueC);
}
References eps_, and EPSGenerator::setLineColour().
Referenced by SetPen().
SetLogicalFunction()
void EPSDC::SetLogicalFunction (int function) virtual
NOT IMPLEMENTED
Definition at line 522 of file EPSDC.cc.
{
}
SetPalette()
void EPSDC::SetPalette (const wxPalette & palette) virtual
NOT IMPLEMENTED
Definition at line 515 of file EPSDC.cc.
{
}
SetPen()
void EPSDC::SetPen (const wxPen & pen) virtual
NOT IMPLEMENTED
Definition at line 158 of file EPSDC.cc.
{
    wxColour lineColour = pen.GetColour();
    eps_.setLineWidth(pen.GetWidth());
    setLineColour(lineColour);
}
References eps_, setLineColour(), and EPSGenerator::setLineWidth().
setTitle()
void EPSDC::setTitle (const std::string & title)
Sets the eps-file title.
Parameters
title String which will be set as the eps file title.
Definition at line 189 of file EPSDC.cc.
{
    eps_.setTitle(title);
}
References eps_, and EPSGenerator::setTitle().
Referenced by MachineCanvas::saveEPS().
StartDoc()
bool EPSDC::StartDoc (const wxString & message) virtual
Called by the device context client before the drawing is started.
Returns
Always true.
Definition at line 231 of file EPSDC.cc.
{
    return true;
}
StartPage()
void EPSDC::StartPage () virtual
Starts a new page in the document.
Definition at line 560 of file EPSDC.cc.
                 {
    // Do nothing.
}
Referenced by MachineCanvas::saveEPS().
writeToStream()
void EPSDC::writeToStream (std::ostream & stream)
Writes the generated eps file to an output stream.
Parameters
stream Output stream where the eps file contents will be written.
Definition at line 209 of file EPSDC.cc.
{
    eps_.writeEPS(stream);
}
References eps_, and EPSGenerator::writeEPS().
Referenced by MachineCanvas::saveEPS().
Member Data Documentation
eps_
EPSGenerator EPSDC::eps_ private
EPSGenerator generating the postscript code.
Definition at line 189 of file EPSDC.hh.
Referenced by Clear(), DoDrawEllipse(), DoDrawLine(), DoDrawPolygon(), DoDrawRectangle(), DoDrawText(), drawCircle(), setCreator(), setFillColour(), SetFont(), setLineColour(), SetPen(), setTitle(), and writeToStream().
fill_
bool EPSDC::fill_ private
True, if background brush is set to fill the shapes.
Definition at line 191 of file EPSDC.hh.
Referenced by DoDrawEllipse(), DoDrawPolygon(), DoDrawRectangle(), drawCircle(), and SetBrush().
fontSize_
unsigned EPSDC::fontSize_ private
Current font size.
Definition at line 193 of file EPSDC.hh.
Referenced by DoGetTextExtent(), and SetFont().
The documentation for this class was generated from the following files:
EPSDC.hh
EPSDC.cc