OpenASIP: MachineDialog Class Reference
MachineDialog Class Reference
#include <MachineDialog.hh>
Public Member Functions
MachineDialog (wxWindow *parent, TTAMachine::Machine &machine)
virtual ~MachineDialog ()
Private Types
enum { ID_ENDIANESS_CHOICE = 10000 }
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
Private Attributes
TTAMachine::Machine & machine_
The machine to modify.
wxChoice * endianessChoise_
Detailed Description
Dialog for editing processor wide properties.
Definition at line 48 of file MachineDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_ENDIANESS_CHOICE
Definition at line 63 of file MachineDialog.hh.
         {
        ID_ENDIANESS_CHOICE = 10000
    };
Constructor & Destructor Documentation
MachineDialog()
MachineDialog::MachineDialog (wxWindow * parent, TTAMachine::Machine & machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine The machine to modify.
Definition at line 54 of file MachineDialog.cc.
                                                                         :
        wxDialog(parent, -1, _T(""), wxDefaultPosition),
        machine_(machine) {
    createContents(this, true, true);
    SetTitle(wxT("Architecture Features"));
    endianessChoise_->Append(wxT("Big-endian"));
    endianessChoise_->Append(wxT("Little-endian"));
    TransferDataToWindow();
}
References createContents(), endianessChoise_, and TransferDataToWindow().
~MachineDialog()
MachineDialog::~MachineDialog () virtual
The Destructor.
Definition at line 69 of file MachineDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * MachineDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 120 of file MachineDialog.cc.
{
    wxBoxSizer *root = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer *machSettings = new wxFlexGridSizer(2, 0, 0);
    // Global Endianess Setting //
    // Label
    wxStaticText *endianessLabel = new wxStaticText(parent, -1,
        wxT("Endianess:"), wxDefaultPosition, wxDefaultSize, 0 );
    machSettings->Add(endianessLabel,
        0, wxALIGN_RIGHT|wxALL, 5);
    // Choice
    endianessChoise_ = new wxChoice(parent, ID_ENDIANESS_CHOICE,
        wxDefaultPosition, wxDefaultSize);
    machSettings->Add(endianessChoise_,
        0, wxALL, 5);
    root->Add(machSettings, 0, wxALIGN_CENTER|wxALL, 5);
    // Buttons //
    wxStaticLine *horizLine = new wxStaticLine(parent, wxID_ANY,
        wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL);
    root->Add(horizLine, 0, wxGROW|wxALL, 5);
    wxBoxSizer *buttonBox = new wxBoxSizer(wxHORIZONTAL);
    // Ok button
    wxButton *okButton =
        new wxButton(parent, wxID_OK, wxT("&OK"), wxDefaultPosition,
            wxDefaultSize, 0);
    buttonBox->Add(okButton, 0, wxALIGN_CENTER|wxALL, 5);
    // Cancel Button
    wxButton *cancelButton =
        new wxButton(parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition,
            wxDefaultSize, 0);
    buttonBox->Add(cancelButton, 0, wxALIGN_CENTER|wxALL, 5);
    root->Add(buttonBox, 0, wxALIGN_CENTER|wxALL, 5);
    if (set_sizer) {
        parent->SetAutoLayout(TRUE);
        parent->SetSizer(root);
        if (call_fit)
        {
            root->Fit(parent);
            root->SetSizeHints(parent);
        }
    }
    return root;
}
References endianessChoise_, ID_ENDIANESS_CHOICE, and TRUE.
Referenced by MachineDialog().
onCancel()
void MachineDialog::onCancel (wxCommandEvent & event) private
Event handler for Cancel button press.
Definition at line 106 of file MachineDialog.cc.
{
    EndModal(wxID_CANCEL);
}
onOK()
void MachineDialog::onOK (wxCommandEvent & event) private
Event handler for Ok button press.
Definition at line 96 of file MachineDialog.cc.
{
    machine_.setLittleEndian(endianessChoise_->GetSelection() == LITTLEENDIAN);
    EndModal(wxID_OK);
}
References endianessChoise_, LITTLEENDIAN, machine_, and TTAMachine::Machine::setLittleEndian().
TransferDataToWindow()
bool MachineDialog::TransferDataToWindow () private virtual
Transfers data from the port object to the dialog widgets.
Returns
False, if an error occured in the transfer.
Definition at line 80 of file MachineDialog.cc.
{
    assert(endianessChoise_->GetCount() > 1); // Assume
    if (machine_.isLittleEndian()) {
        endianessChoise_->SetSelection(LITTLEENDIAN);
    } else {
        endianessChoise_->SetSelection(BIGENDIAN);
    }
    return wxWindow::TransferDataToWindow();
}
References assert, BIGENDIAN, endianessChoise_, TTAMachine::Machine::isLittleEndian(), LITTLEENDIAN, and machine_.
Referenced by MachineDialog().
Member Data Documentation
endianessChoise_
wxChoice* MachineDialog::endianessChoise_ private
Definition at line 61 of file MachineDialog.hh.
Referenced by createContents(), MachineDialog(), onOK(), and TransferDataToWindow().
machine_
TTAMachine::Machine& MachineDialog::machine_ private
The machine to modify.
Definition at line 60 of file MachineDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
MachineDialog.hh
MachineDialog.cc