OpenASIP: ContainerTools Class Reference
ContainerTools Class Reference
#include <ContainerTools.hh>
Static Public Member Functions
template<typename ContainerType , typename ElementType >
static bool containsValue (const ContainerType &aContainer, const ElementType &aKey)
template<typename ContainerType , typename ElementType >
static bool removeValueIfExists (ContainerType &aContainer, const ElementType &aKey)
template<typename ContainerType , typename ElementType >
static bool deleteValueIfExists (ContainerType &aContainer, const ElementType &aKey)
template<typename ContainerType >
static void removeValues (ContainerType &aContainer, const ContainerType &toRemove)
template<typename E , typename I >
static void swapRemoveValue (std::vector< E > &aContainer, I index)
Detailed Description
Definition at line 39 of file ContainerTools.hh.
Member Function Documentation
containsValue()
template<typename ContainerType , typename ElementType > static bool ContainerTools::containsValue (const ContainerType & aContainer, const ElementType & aKey) static
Referenced by ResourceBuildDirector::addBroker(), TTAProgram::Scope::addChild(), EditPart::addChild(), TTAProgram::Instruction::addImmediate(), TTAProgram::Instruction::addMove(), ProGe::BaseNetlistBlock::addPackage(), FUGen::addRegisterIfMissing(), ResourceMapper::addResourceMap(), ProximMainFrame::addSubWindow(), Operand::canSwap(), POMValidator::checkSimulatability(), FUTestbenchGenerator::createTbInstantiation(), TTAMachine::FunctionUnit::deleteOperation(), LabelManager::finalize(), ProgrammabilityValidator::findConnections(), ITemplateBroker::findITemplates(), HDBToHtml::fuArchToHtml(), MachineEditPartFactory::getBusChains(), SchedulingResourceSet::insert(), ProGe::BaseNetlistBlock::isSubBlock(), OperationDialog::onAddResource(), OperationDialog::onDeleteOperand(), OperationDialog::onOperandLClick(), HDB::ExternalPort::setParameterDependency(), BEMGenerator::socket(), ProGe::VerilogNetlistWriter::writeSignalAssignments(), and ProGe::VHDLNetlistWriter::writeSignalAssignments().
deleteValueIfExists()
template<typename ContainerType , typename ElementType > static bool ContainerTools::deleteValueIfExists (ContainerType & aContainer, const ElementType & aKey) static
Referenced by HDB::FUImplementation::deleteArchitecturePort(), HDB::FUImplementation::deleteExternalPort(), HDB::RFImplementation::deleteExternalPort(), HDB::RFImplementation::deletePort(), and TTAMachine::InstructionTemplate::removeSlot().
removeValueIfExists()
template<typename ContainerType , typename ElementType > static bool ContainerTools::removeValueIfExists (ContainerType & aContainer, const ElementType & aKey) static
Referenced by DataDependenceGraphBuilder::changeState(), TTAMachine::Bus::clearDestinationBridge(), TTAMachine::Bus::clearSourceBridge(), TTAMachine::FunctionUnit::deleteOperation(), TTAMachine::FunctionUnit::deletePipelineElement(), TTAMachine::Socket::detachPort(), TTAMachine::ExecutionPipeline::internalRemoveOperandUse(), TTAMachine::ExecutionPipeline::internalRemoveResourceUse(), OperationDialog::onDeleteOperand(), OperationDialog::onDeleteResource(), OperationDialog::onResourceLClick(), SourceField::removeBridgeEncoding(), ObjectState::removeChild(), TTAMachine::Segment::removeConnection(), TTAMachine::Socket::removeConnection(), SocketCodeTable::removeFUPortCode(), TTAMachine::Bus::removeGuard(), GuardField::removeGuardEncoding(), GuardField::removeGuardEncoding(), BinaryEncoding::removeImmediateSlot(), HDB::HWBlockImplementation::removeImplementationFile(), BinaryEncoding::removeInstructionFormat(), SocketCodeTable::removeIUPortCode(), BinaryEncoding::removeLongImmDstRegisterField(), BinaryEncoding::removeMoveSlot(), ProGe::BaseNetlistBlock::removePort(), TTAMachine::Unit::removePort(), SocketCodeTable::removeRFPortCode(), PluginTools::removeSearchPath(), TTAMachine::Bus::removeSegment(), BinaryEncoding::removeSocketCodeTable(), SlotField::removeSocketEncoding(), ProximMainFrame::removeSubWindow(), HDB::ExternalPort::unsetParameterDependency(), and ObjectState::~ObjectState().
removeValues()
template<typename ContainerType > static void ContainerTools::removeValues (ContainerType & aContainer, const ContainerType & toRemove) static
swapRemoveValue()
template<typename E , typename I > static void ContainerTools::swapRemoveValue (std::vector< E > & aContainer, I index) static
Referenced by ProGe::BaseNetlistBlock::deleteSubBlock(), ProGe::BaseNetlistBlock::removePortGroup(), and ProGe::BaseNetlistBlock::removeSubBlock().
The documentation for this class was generated from the following file:
ContainerTools.hh