OpenASIP: OptionalStringCmdLineOptionParser Class Reference
OptionalStringCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
OptionalStringCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~OptionalStringCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual std::string String (int index=0) const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual unsigned unsignedInteger (int index=0) const
virtual double real () const
virtual int listSize () const
Private Member Functions
OptionalStringCmdLineOptionParser (const OptionalStringCmdLineOptionParser &)
Copying not allowed.
OptionalStringCmdLineOptionParser & operator= (const OptionalStringCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
std::string value_
The value of the option.
bool flag_
The flag status.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that acts as flag with optional string value.
Definition at line 210 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
OptionalStringCmdLineOptionParser() [1/2]
OptionalStringCmdLineOptionParser::OptionalStringCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 419 of file CmdLineOptionParser.cc.
    :  CmdLineOptionParser(name, desc, alias), value_(""), flag_(false) {
}
~OptionalStringCmdLineOptionParser()
OptionalStringCmdLineOptionParser::~OptionalStringCmdLineOptionParser () virtual
Destructor.
Definition at line 427 of file CmdLineOptionParser.cc.
{
}
OptionalStringCmdLineOptionParser() [2/2]
OptionalStringCmdLineOptionParser::OptionalStringCmdLineOptionParser (const OptionalStringCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * OptionalStringCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 439 of file CmdLineOptionParser.cc.
{
    StringOptionValue* copy = new StringOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
isFlagOff()
bool OptionalStringCmdLineOptionParser::isFlagOff () const virtual
Returns true if the flag is not set.
Returns
Inverse of the boolean flag.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 492 of file CmdLineOptionParser.cc.
{
    return !flag_;
}
References flag_.
isFlagOn()
bool OptionalStringCmdLineOptionParser::isFlagOn () const virtual
Returns true if the flag is set.
Returns
The boolean flag value.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 481 of file CmdLineOptionParser.cc.
{
    return flag_;
}
References flag_.
operator=()
OptionalStringCmdLineOptionParser & OptionalStringCmdLineOptionParser::operator= (const OptionalStringCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool OptionalStringCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of option.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine Not thrown.
Implements CmdLineOptionParser.
Definition at line 453 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for string option";
        string method = "StringCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    value_ = arguments;
    flag_ = true;
    setDefined();
    return true;
}
References flag_, CmdLineOptionParser::setDefined(), and value_.
String()
string OptionalStringCmdLineOptionParser::String (int index = 0) const virtual
This implementation should be never called.
Returns
Nothing.
Exceptions
WrongSubclass Called for a wrong subclass.
Reimplemented from CmdLineOptionParser.
Definition at line 469 of file CmdLineOptionParser.cc.
{
    assert(index == 0);
    return value_;
}
References assert, and value_.
Member Data Documentation
flag_
bool OptionalStringCmdLineOptionParser::flag_ private
The flag status.
Definition at line 236 of file CmdLineOptionParser.hh.
Referenced by isFlagOff(), isFlagOn(), and parseValue().
value_
std::string OptionalStringCmdLineOptionParser::value_ private
The value of the option.
Definition at line 234 of file CmdLineOptionParser.hh.
Referenced by copy(), parseValue(), and String().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc