OpenASIP: EstimatorCmdLineOptions Class Reference
EstimatorCmdLineOptions Class Reference
#include <EstimatorCmdLineOptions.hh>
Public Member Functions
EstimatorCmdLineOptions ()
virtual ~EstimatorCmdLineOptions ()
virtual void printVersion () const
virtual void printHelp () const
bool runOnlyEstimations () const
bool totalArea () const
bool longestPath () const
bool totalEnergy () const
std::string TPEF ()
std::string traceDB ()
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Private Member Functions
EstimatorCmdLineOptions (const EstimatorCmdLineOptions &)
Copying not allowed.
EstimatorCmdLineOptions & operator= (const EstimatorCmdLineOptions &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line option class for Simulator.
Definition at line 43 of file EstimatorCmdLineOptions.hh.
Constructor & Destructor Documentation
EstimatorCmdLineOptions() [1/2]
EstimatorCmdLineOptions::EstimatorCmdLineOptions ()
Constructor.
Definition at line 65 of file EstimatorCmdLineOptions.cc.
                                                 : CmdLineOptions("") {
    addOption(
        new StringCmdLineOptionParser(
            SWL_TPEF,
            "sets the TTA program exchange format file (TPEF) from which to "
            "load the estimated program (required for energy estimation only)",
            SWS_TPEF));
    addOption(
        new StringCmdLineOptionParser(
            SWL_TRACE,
            "sets the simulation trace database (TraceDB) from which to "
            "load the simulation data of the estimated program (required for "
            "energy estimation only)",
            SWS_TRACE));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_TOTALAREA,
            "run total area estimation",
            SWS_TOTALAREA));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_LONGESTPATH,
            "run longest path estimation",
            SWS_LONGESTPATH));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_TOTALENERGY,
            "run total energy consumption estimation",
            SWS_TOTALENERGY));
}
References CmdLineParser::addOption(), SWL_LONGESTPATH, SWL_TOTALAREA, SWL_TOTALENERGY, SWL_TPEF, SWL_TRACE, SWS_LONGESTPATH, SWS_TOTALAREA, SWS_TOTALENERGY, SWS_TPEF, and SWS_TRACE.
~EstimatorCmdLineOptions()
EstimatorCmdLineOptions::~EstimatorCmdLineOptions () virtual
Destructor.
Definition at line 99 of file EstimatorCmdLineOptions.cc.
{
}
EstimatorCmdLineOptions() [2/2]
EstimatorCmdLineOptions::EstimatorCmdLineOptions (const EstimatorCmdLineOptions &) private
Copying not allowed.
Member Function Documentation
longestPath()
bool EstimatorCmdLineOptions::longestPath () const
Checks if run longest path estimation option was given.
Returns
True if option was given and was not "no" prefixed
Definition at line 187 of file EstimatorCmdLineOptions.cc.
{
    if (findOption(SWL_LONGESTPATH)->isDefined()) {
        return findOption(SWL_LONGESTPATH)->isFlagOn();
    }
    return false;
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_LONGESTPATH.
operator=()
EstimatorCmdLineOptions & EstimatorCmdLineOptions::operator= (const EstimatorCmdLineOptions &) private
Assignment not allowed.
printHelp()
void EstimatorCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Reimplemented from CmdLineOptions.
Definition at line 115 of file EstimatorCmdLineOptions.cc.
{
    printVersion();
    std::cout << std::endl
              << "usage: estimate [options] ADF IDF "
              << std::endl
              << std::endl
              << "ADF and IDF are required always, TPEF and TraceDB only for "
              << "energy estimation, which is not performed in case they are "
              << "not given."
              << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void EstimatorCmdLineOptions::printVersion () const virtual
Prints the version of the program.
Implements CmdLineOptions.
Definition at line 106 of file EstimatorCmdLineOptions.cc.
{
    std::cout << "estimate - TTA Processor Cost Estimator "
              <<  Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
runOnlyEstimations()
bool EstimatorCmdLineOptions::runOnlyEstimations () const
Test if estimation selection flags are given, returns true is so.
Returns
True if estimation selection flags are given.
Definition at line 158 of file EstimatorCmdLineOptions.cc.
{
   if (findOption(SWL_TOTALAREA)->isDefined() ||
       findOption(SWL_LONGESTPATH)->isDefined() ||
       findOption(SWL_LONGESTPATH)->isDefined()) {
       return true;
   }
   return false;
}
References CmdLineParser::findOption(), SWL_LONGESTPATH, and SWL_TOTALAREA.
totalArea()
bool EstimatorCmdLineOptions::totalArea () const
Checks if run total area estimation option was given.
Returns
True if option was given and was not "no" prefixed
Definition at line 174 of file EstimatorCmdLineOptions.cc.
{
    if (findOption(SWL_TOTALAREA)->isDefined()) {
        return findOption(SWL_TOTALAREA)->isFlagOn();
    }
    return false;
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_TOTALAREA.
totalEnergy()
bool EstimatorCmdLineOptions::totalEnergy () const
Checks if run total energy consumption estimation option was given.
Returns
True if option was given and was not "no" prefixed
Definition at line 200 of file EstimatorCmdLineOptions.cc.
{
    if (findOption(SWL_TOTALENERGY)->isDefined()) {
        return findOption(SWL_TOTALENERGY)->isFlagOn();
    }
    return false;
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_TOTALENERGY.
TPEF()
std::string EstimatorCmdLineOptions::TPEF ()
Returns the TPEF file name given by the user.
If no value is given in the parsed command line, returns an empty string.
Returns
The TPEF file name.
Definition at line 136 of file EstimatorCmdLineOptions.cc.
{
    return findOption(SWL_TPEF)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_TPEF.
traceDB()
std::string EstimatorCmdLineOptions::traceDB ()
Returns the TraceDB file name given by the user.
If no value is given in the parsed command line, returns an empty string.
Returns
The TraceDB file name.
Definition at line 148 of file EstimatorCmdLineOptions.cc.
{
    return findOption(SWL_TRACE)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_TRACE.
The documentation for this class was generated from the following files:
EstimatorCmdLineOptions.hh
EstimatorCmdLineOptions.cc