OpenASIP: EditAddressSpacesCmd Class Reference
EditAddressSpacesCmd Class Reference
#include <EditAddressSpacesCmd.hh>
Public Member Functions
EditAddressSpacesCmd ()
virtual ~EditAddressSpacesCmd ()
virtual bool Do ()
virtual int id () const
virtual EditAddressSpacesCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing address spaces.
Definition at line 40 of file EditAddressSpacesCmd.hh.
Constructor & Destructor Documentation
EditAddressSpacesCmd()
EditAddressSpacesCmd::EditAddressSpacesCmd ()
The Constructor.
Definition at line 52 of file EditAddressSpacesCmd.cc.
                                          :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_ADDRESS_SPACES) {
}
Referenced by create().
~EditAddressSpacesCmd()
EditAddressSpacesCmd::~EditAddressSpacesCmd () virtual
The Destructor.
Definition at line 60 of file EditAddressSpacesCmd.cc.
{}
Member Function Documentation
create()
EditAddressSpacesCmd * EditAddressSpacesCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 105 of file EditAddressSpacesCmd.cc.
{
    return new EditAddressSpacesCmd();
}
References EditAddressSpacesCmd().
Do()
bool EditAddressSpacesCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 69 of file EditAddressSpacesCmd.cc.
{
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    AddressSpacesDialog dialog(parentWindow(), model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, address spaces are not modified.
    model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string EditAddressSpacesCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 115 of file EditAddressSpacesCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_ADDRESS_SPACES;
}
References ProDeConstants::CMD_ICON_EDIT_ADDRESS_SPACES.
id()
int EditAddressSpacesCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 96 of file EditAddressSpacesCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_ADDRESS_SPACES;
}
References ProDeConstants::COMMAND_EDIT_ADDRESS_SPACES.
isEnabled()
bool EditAddressSpacesCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 137 of file EditAddressSpacesCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string EditAddressSpacesCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 124 of file EditAddressSpacesCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_ADDRESS_SPACES;
}
References ProDeConstants::CMD_SNAME_EDIT_ADDRESS_SPACES.
The documentation for this class was generated from the following files:
EditAddressSpacesCmd.hh
EditAddressSpacesCmd.cc