OpenASIP: CutComponentCmd Class Reference
CutComponentCmd Class Reference
#include <CutComponentCmd.hh>
Public Member Functions
CutComponentCmd ()
virtual bool Do ()
virtual int id () const
virtual CutComponentCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for cutting machine components to the clipboard.
Definition at line 43 of file CutComponentCmd.hh.
Constructor & Destructor Documentation
CutComponentCmd()
CutComponentCmd::CutComponentCmd ()
The Constructor.
Definition at line 49 of file CutComponentCmd.cc.
                                :
    EditorCommand(ProDeConstants::CMD_NAME_CUT) {
}
Referenced by create().
Member Function Documentation
create()
CutComponentCmd * CutComponentCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 121 of file CutComponentCmd.cc.
{
    return new CutComponentCmd();
}
References CutComponentCmd().
Do()
bool CutComponentCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 61 of file CutComponentCmd.cc.
                    {
    assert(view() != NULL);
    Request* copyRequest = new Request(Request::COPY_REQUEST);
    Request* deleteRequest = new Request(Request::DELETE_REQUEST);
    EditPart* selected = dynamic_cast<MDFView*>(view())->selection();
    if (selected == NULL) {
        return false;
    }
    // Request copy and delete commands.
    ComponentCommand* copyCommand = selected->performRequest(copyRequest);
    ComponentCommand* deleteCommand = selected->performRequest(deleteRequest);
    // Execute the returned commands.
    if (copyCommand == NULL || deleteCommand == NULL) {
        return false;
    } else {
        dynamic_cast<MDFView*>(view())->clearSelection();
    Model* model = dynamic_cast<MDFDocument*>(
        wxGetApp().docManager()->GetCurrentDocument())->getModel();
    model->pushToStack();
        // copy
        copyCommand->setParentWindow(parentWindow());
        copyCommand->Do();
        // delete
        deleteCommand->setParentWindow(parentWindow());
        deleteCommand->Do();
    model->notifyObservers();
        return false;
    }
}
References assert, Request::COPY_REQUEST, Request::DELETE_REQUEST, ComponentCommand::Do(), Model::notifyObservers(), GUICommand::parentWindow(), EditPart::performRequest(), Model::pushToStack(), ComponentCommand::setParentWindow(), and EditorCommand::view().
icon()
string CutComponentCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 133 of file CutComponentCmd.cc.
{
    return ProDeConstants::CMD_ICON_CUT;
}
References ProDeConstants::CMD_ICON_CUT.
id()
int CutComponentCmd::id () const virtual
Returns command identifier of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 110 of file CutComponentCmd.cc.
{
    return ProDeConstants::COMMAND_CUT;
}
References ProDeConstants::COMMAND_CUT.
isEnabled()
bool CutComponentCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a component is selected, and the selected component can be copied and deleted.
Returns
True, if a component is selected.
Reimplemented from EditorCommand.
Definition at line 148 of file CutComponentCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    MDFView* mdfView = dynamic_cast<MDFView*>(manager->GetCurrentView());
    if (mdfView == NULL) {
    return false;
    }
    EditPart* selected = mdfView->selection();
    Request* copyRequest = new Request(Request::COPY_REQUEST);
    Request* deleteRequest = new Request(Request::DELETE_REQUEST);
    if (selected == NULL ||
        !(selected->canHandle(copyRequest)) ||
        !(selected->canHandle(deleteRequest))) {
    delete copyRequest;
    return false;
    }
    delete copyRequest;
    delete deleteRequest;
    return true;
}
References EditPart::canHandle(), Request::COPY_REQUEST, Request::DELETE_REQUEST, and MDFView::selection().
The documentation for this class was generated from the following files:
CutComponentCmd.hh
CutComponentCmd.cc