OpenASIP: OutputPSocketResource Class Reference
OutputPSocketResource Class Reference
#include <OutputPSocketResource.hh>
Public Member Functions
virtual ~OutputPSocketResource ()
OutputPSocketResource (const std::string &name, unsigned int initiationInterval=0)
virtual bool isAvailable (const int cycle) const override
virtual bool isOutputPSocketResource () const override
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual bool operator< (const SchedulingResource &other) const override
void clear () override
Public Member Functions inherited from PSocketResource
virtual ~PSocketResource ()
PSocketResource (const std::string &name, unsigned int initiationInterval=0)
virtual bool isInUse (const int cycle) const override
void clear () override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Member Functions
OutputPSocketResource (const OutputPSocketResource &)
OutputPSocketResource & operator= (const OutputPSocketResource &)
Private Attributes
int activeCycle_
std::map< int, std::pair< const TTAMachine::Port *, int > > storedPorts_
Additional Inherited Members
Protected Types inherited from PSocketResource
typedef std::map< int, std::set< MoveNode * > > ResourceRecordType
Protected Attributes inherited from PSocketResource
ResourceRecordType resourceRecord_
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model The derived class OutputPSocketResource
Definition at line 52 of file OutputPSocketResource.hh.
Constructor & Destructor Documentation
~OutputPSocketResource()
OutputPSocketResource::~OutputPSocketResource () virtual
Destructor.
Definition at line 54 of file OutputPSocketResource.cc.
{}
OutputPSocketResource() [1/2]
OutputPSocketResource::OutputPSocketResource (const std::string & name, unsigned int initiationInterval = 0)
Constructor.
Parameters
name Name of resource.
Definition at line 48 of file OutputPSocketResource.cc.
                                                                                                   :
    PSocketResource(name, initiationInterval), activeCycle_(-1) {}
OutputPSocketResource() [2/2]
OutputPSocketResource::OutputPSocketResource (const OutputPSocketResource &) private
Member Function Documentation
assign()
void OutputPSocketResource::assign (const int cycle, MoveNode & node) override virtual
Assign resource to given node for given cycle.
Parameters
cycle Cycle to assign
node MoveNode to assign
Reimplemented from PSocketResource.
Definition at line 83 of file OutputPSocketResource.cc.
{
    PSocketResource::assign(cycle, node);
    auto i = storedPorts_.find(instructionIndex(cycle));
    if (i == storedPorts_.end()) {
        const TTAMachine::Port* newPort = &node.move().source().port();
        storedPorts_[instructionIndex(cycle)] =
            std::make_pair(newPort,1);
    } else {
        i->second.second++;
    }
}
References PSocketResource::assign(), SchedulingResource::instructionIndex(), MoveNode::move(), TTAProgram::Terminal::port(), TTAProgram::Move::source(), and storedPorts_.
canAssign()
bool OutputPSocketResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Return true if resource can be assigned for given resource in given cycle.
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Reimplemented from PSocketResource.
Definition at line 124 of file OutputPSocketResource.cc.
          {
    MoveNode& mNode = const_cast<MoveNode&>(node);
    auto i = storedPorts_.find(instructionIndex(cycle));
    if (mNode.move().source().isFUPort()) {
        if (i != storedPorts_.end()) {
            const TTAMachine::Port* storedP = i->second.first;
            if (&mNode.move().source().port() != storedP) {
                return false;
            }
        }
    }
    if (mNode.move().source().isImmediateRegister()) {
        if (i != storedPorts_.end()) {
            return false;
        }
    }
    if (node.move().source().isGPR()) {
        if (i != storedPorts_.end()) {
            const TTAMachine::Port* storedP =
                i->second.first;
            if (mNode.move().source().port().parentUnit() !=
                storedP->parentUnit()) {
                return false;
            }
        }
        ResourceRecordType::const_iterator iter = resourceRecord_.find(cycle);
        if (iter != resourceRecord_.end()) {
            std::set<MoveNode*> movesInCycle = iter->second;
            for (std::set<MoveNode*>::iterator it = movesInCycle.begin();
                 it != movesInCycle.end(); it++) {
#ifdef NO_OVERCOMMIT
                return false;
#else
                MoveNode* mn = *it;
                if (node.move().isUnconditional() ||
                    mn->move().isUnconditional()) {
                    if (node.move().source().port().parentUnit() !=
                        mn->move().source().port().parentUnit() ||
                            node.move().source().index() !=
                            mn->move().source().index()) {
                        return false;
                    } else {
                        continue;
                    }
                }
                if (!node.move().guard().guard().isOpposite(
                        mn->move().guard().guard())) {
                    if (!node.move().source().equals(
                            mn->move().source())) {
                        return false;
                    }
                }
#endif
            }
        }
    }
    activeCycle_ = cycle;
    return true;
}
References activeCycle_, TTAProgram::Terminal::equals(), TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), TTAProgram::Terminal::index(), SchedulingResource::instructionIndex(), TTAProgram::Terminal::isFUPort(), TTAProgram::Terminal::isGPR(), TTAProgram::Terminal::isImmediateRegister(), TTAMachine::Guard::isOpposite(), TTAProgram::Move::isUnconditional(), MoveNode::move(), TTAMachine::Port::parentUnit(), TTAProgram::Terminal::port(), PSocketResource::resourceRecord_, TTAProgram::Move::source(), and storedPorts_.
clear()
void OutputPSocketResource::clear () override virtual
Clears bookkeeping of the scheduling resource.
After this call the state of the resource should be identical to a newly-created and initialized resource.
Reimplemented from SchedulingResource.
Definition at line 305 of file OutputPSocketResource.cc.
{
    PSocketResource::clear();
    storedPorts_.clear();
}
References PSocketResource::clear(), and storedPorts_.
isAvailable()
bool OutputPSocketResource::isAvailable (const int cycle) const override virtual
Test if resource OutputPSocketResource is available.
Parameters
cycle Cycle which to test.
Returns
Always true, multiple reads are possible.
Reimplemented from PSocketResource.
Definition at line 63 of file OutputPSocketResource.cc.
{
    return true;
}
isOutputPSocketResource()
bool OutputPSocketResource::isOutputPSocketResource () const override virtual
Return true always.
Returns
True always.
Reimplemented from SchedulingResource.
Definition at line 73 of file OutputPSocketResource.cc.
{
    return true;
}
operator<()
bool OutputPSocketResource::operator< (const SchedulingResource & other) const override virtual
Comparison operator.
Favours sockets which have less connections.
TODO: precalc/cache these to optimize scheduling time?
Reimplemented from SchedulingResource.
Definition at line 231 of file OutputPSocketResource.cc.
{
    const OutputPSocketResource *opsr =
        dynamic_cast<const OutputPSocketResource*>(&other);
    if (opsr == NULL) {
        return false;
    }
    // first priority is to put reads from same source to same psocket.
    // so favour the one with most moves in current cycle.
    int myCount = 0;
    int otherCount = 0;
    ResourceRecordType::const_iterator myIter = resourceRecord_.find(activeCycle_);
    if (myIter != resourceRecord_.end()) {
        myCount = myIter->second.size();
    }
    ResourceRecordType::const_iterator otherIter = opsr->resourceRecord_.find(opsr->activeCycle_);
    if (otherIter != opsr->resourceRecord_.end()) {
        otherCount = otherIter->second.size();
    }
    if (myCount  < otherCount) {
        return false;
    } else if (myCount > otherCount) {
        return true;
    }
    // favour sockets which have connections to busses with fewest connections
    // calculate the connections..
    int connCount = 0;
    int connCount2 = 0;
    int rrCount2 = relatedResourceCount(2);
    for (int i = 0; i < rrCount2; i++) {
        SchedulingResource& r = relatedResource(2,i);
        connCount += r.relatedResourceCount(0);
    }
    int oRRCount2 = other.relatedResourceCount(2);
    for (int i = 0; i < oRRCount2; i++) {
        SchedulingResource& r = other.relatedResource(2,i);
        connCount2 += r.relatedResourceCount(0);
    }
    // then the comparison.
    if (connCount < connCount2) {
        return true;
    }
    if (connCount > connCount2) {
        return false;
    }
    // favour sockets with less buses.
    if (rrCount2 < oRRCount2) {
        return true;
    }
    if (rrCount2 > oRRCount2) {
        return false;
    }
    // then use the default use count, name comparison,
    // but in opposite direction, facouring already used
    return other.SchedulingResource::operator<(*this);
}
References activeCycle_, SchedulingResource::relatedResource(), SchedulingResource::relatedResourceCount(), and PSocketResource::resourceRecord_.
operator=()
OutputPSocketResource & OutputPSocketResource::operator= (const OutputPSocketResource &) private
unassign()
void OutputPSocketResource::unassign (const int cycle, MoveNode & node) override virtual
Unassign resource from given node for given cycle.
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
Reimplemented from PSocketResource.
Definition at line 103 of file OutputPSocketResource.cc.
{
    PSocketResource::unassign(cycle, node);
    auto i = storedPorts_.find(instructionIndex(cycle));
    if (i != storedPorts_.end()) {
        if (i->second.second == 1) {
            storedPorts_.erase(i);
        } else {
            i->second.second--;
        }
    }
}
References SchedulingResource::instructionIndex(), storedPorts_, and PSocketResource::unassign().
validateDependentGroups()
bool OutputPSocketResource::validateDependentGroups () override protected virtual
Tests if all referred resources in dependent groups are of proper types.
Returns
True if all dependent groups are empty.
Reimplemented from SchedulingResource.
Definition at line 194 of file OutputPSocketResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        if (dependentResourceCount(i) > 0) {
            return false;
        }
    }
    return true;
}
References SchedulingResource::dependentResourceCount(), and SchedulingResource::dependentResourceGroupCount().
validateRelatedGroups()
bool OutputPSocketResource::validateRelatedGroups () override protected virtual
Tests if all referred resources in related groups are of proper types.
Returns
True if all resources in related groups are Segment or OutputFU or IU resources.
Reimplemented from SchedulingResource.
Reimplemented in ShortImmPSocketResource.
Definition at line 211 of file OutputPSocketResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        for (int j = 0, count = relatedResourceCount(i); j < count; j++) {
            if (!(relatedResource(i, j).isOutputFUResource() ||
                relatedResource(i, j).isBusResource() ||
                relatedResource(i, j).isIUResource())) {
                return false;
            }
        }
    }
    return true;
}
References SchedulingResource::isBusResource(), SchedulingResource::isIUResource(), SchedulingResource::isOutputFUResource(), SchedulingResource::relatedResource(), SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
Member Data Documentation
activeCycle_
int OutputPSocketResource::activeCycle_ mutable private
Definition at line 69 of file OutputPSocketResource.hh.
Referenced by canAssign(), and operator<().
storedPorts_
std::map<int, std::pair<const TTAMachine::Port*, int> > OutputPSocketResource::storedPorts_ private
Definition at line 75 of file OutputPSocketResource.hh.
Referenced by assign(), canAssign(), clear(), and unassign().
The documentation for this class was generated from the following files:
OutputPSocketResource.hh
OutputPSocketResource.cc