OpenASIP: InfoSegmentsCommand Class Reference
InfoSegmentsCommand Class Reference
Public Member Functions
InfoSegmentsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoSegmentsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info segments".
Definition at line 595 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoSegmentsCommand()
InfoSegmentsCommand::InfoSegmentsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 600 of file InfoCommand.cc.
                                                                  :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoSegmentsCommand()
virtual InfoSegmentsCommand::~InfoSegmentsCommand () inline virtual
Destructor.
Definition at line 607 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoSegmentsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info segments" command.
Prints the values of segments in the given bus.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 618 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 1, 2)) {
            return false;
        }
        if (!parent().checkMachineLoaded()) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        const std::string busName = arguments.at(2).stringValue();
        const TTAMachine::Machine::BusNavigator nav =
            mach.busNavigator();
        if (!nav.hasItem(busName)) {
            parent().interpreter()->setError(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_BUS_NOT_FOUND).str());
            return false;
        }
        TTAMachine::Bus* bus = nav.item(busName);
        assert(bus != NULL);
        MachineState& state = parent().simulatorFrontend().machineState();
        if (argumentCount == 1) {
            std::string result = "";
            BusState& busState = state.busState(busName);
            parent().interpreter()->setResult(busState.value().intValue());
            return true;
        } else if (argumentCount == 2) {
            parent().interpreter()->setResult(
                "Segmented busses not yet supported.");
            return false;
        }
        return false;
    }
References assert, TTAMachine::Machine::busNavigator(), MachineState::busState(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), CustomCommand::interpreter(), SimValue::intValue(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), SimulatorFrontend::machineState(), SimControlLanguageSubCommand::parent(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), SimulatorToolbox::textGenerator(), Texts::TXT_BUS_NOT_FOUND, and RegisterState::value().
The documentation for this class was generated from the following file:
InfoCommand.cc