OpenASIP: ResourceBuildDirector Class Reference
ResourceBuildDirector Class Reference
#include <ResourceBuildDirector.hh>
Public Member Functions
ResourceBuildDirector ()
virtual ~ResourceBuildDirector ()
void addBroker (ResourceBroker &broker)
void build (const TTAMachine::Machine &machine)
void print (std::ostream &target_, unsigned int cycles) const
void clear ()
Private Attributes
std::vector< ResourceBroker * > brokers_
Resource brokers.
ResourceMapper mapper_
Resource mapper.
Detailed Description
Handles resource model construction.
Definition at line 51 of file ResourceBuildDirector.hh.
Constructor & Destructor Documentation
ResourceBuildDirector()
ResourceBuildDirector::ResourceBuildDirector ()
Constructor.
Definition at line 42 of file ResourceBuildDirector.cc.
{
}
~ResourceBuildDirector()
ResourceBuildDirector::~ResourceBuildDirector () virtual
Destructor.
Definition at line 48 of file ResourceBuildDirector.cc.
{
    SequenceTools::deleteAllItems(brokers_);
}
References brokers_, and SequenceTools::deleteAllItems().
Member Function Documentation
addBroker()
void ResourceBuildDirector::addBroker (ResourceBroker & broker)
Add given broker to the list of brokers responsible for resource construction.
The order in which brokers are added is irrelevant.
Parameters
broker Broker to add.
Definition at line 61 of file ResourceBuildDirector.cc.
{
    if (ContainerTools::containsValue(brokers_, &broker)) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, __func__);
    } else {
        brokers_.push_back(&broker);
    }
}
References __func__, brokers_, and ContainerTools::containsValue().
Referenced by SimpleResourceManager::buildResourceModel().
build()
void ResourceBuildDirector::build (const TTAMachine::Machine & machine)
Build a complete resource object model for given target processor.
@machine Machine to build from.
Definition at line 75 of file ResourceBuildDirector.cc.
{
    // build primary resources
    for (unsigned int i = 0; i < brokers_.size(); i++) {
        brokers_[i]->buildResources(machine);
        mapper_.addResourceMap(*brokers_[i]);
    }
    // setup dependent and related resource links
    for (unsigned int i = 0; i < brokers_.size(); i++) {
        brokers_[i]->setupResourceLinks(mapper_);
    }
    for (unsigned int i = 0; i < brokers_.size(); i++) {
        // broker throws in case problem is found
        brokers_[i]->validateResources();
    }
}
References ResourceMapper::addResourceMap(), brokers_, machine, and mapper_.
Referenced by SimpleResourceManager::buildResourceModel().
clear()
void ResourceBuildDirector::clear ()
Clears all resources of the resouce manager so that the RM can be reused.
Definition at line 178 of file ResourceBuildDirector.cc.
{
    for (size_t i = 0; i < brokers_.size(); i++) {
        brokers_[i]->clear();
    }
}
References brokers_.
Referenced by SimpleResourceManager::clear().
print()
void ResourceBuildDirector::print (std::ostream & target_, unsigned int cycles) const
Print resource manager's contents.
Parameters
target_ Output stream to pring (eg. std::cout).
cycles How many cycles to print.
@machine Machine to build from.
Definition at line 102 of file ResourceBuildDirector.cc.
{
    std::vector<ResourceBroker::ResourceSet> contents;
    std::vector<ResourceBroker::ResourceSet::iterator> contentIterators;
    bool finished = false;
    unsigned int k = 0;
    unsigned int minWidth = cycles;
    // determine minimum width for field, it is constrained by cycle count or broker's name
    for (std::vector<ResourceBroker*>::const_iterator i = brokers_.begin(); i != brokers_.end(); ++i) {
        std::string name =  (*i)->brokerName();
        if(name.length() > minWidth) {
            minWidth = name.length();
        }
    }
    minWidth += 1;
    // print broker names
    for (std::vector<ResourceBroker*>::const_iterator i = brokers_.begin(); i != brokers_.end(); ++i) {
        target_ << std::left << std::setw(minWidth);
        target_ << (*i)->brokerName();
    }
    target_ << std::endl;
    // print broker reservation tables
    while (!finished) {
        finished = true;
        for (std::vector<ResourceBroker*>::const_iterator i = brokers_.begin(); i != brokers_.end(); ++i) {
            ResourceBroker::ResourceSet c;
            (*i)->resources(c);
            ResourceBroker::ResourceSet::iterator j = c.begin();
            if(k >= c.size()) {
                target_ << std::left << std::setw(minWidth) << ' ';
                //<<
//                    std::string(cycles, ' ');
                continue;
            }
            std::advance(j, k);
            if(j == c.end()) {
//                target_ << std::left << std::setw(minWidth) <<
//                    std::string(cycles, ' ');
                continue;
            }
            finished = false;
            std::string table = "";
            for (unsigned int cycle = 0; cycle < cycles; ++cycle)
            {
                if((*j)->isAvailable(cycle)) {
                    table += '-';
                }
                else {
                    table += '#';
                    std::cerr << (*j) << " " << (*j)->name() << std::endl;
                }
            }
            target_ << std::left << std::setw(minWidth) << table;
        }
        target_ << std::endl;
        k += 1;
    }
}
References brokers_.
Referenced by SimpleResourceManager::print(), and SimpleResourceManager::toString().
Member Data Documentation
brokers_
std::vector<ResourceBroker*> ResourceBuildDirector::brokers_ private
Resource brokers.
Definition at line 63 of file ResourceBuildDirector.hh.
Referenced by addBroker(), build(), clear(), print(), and ~ResourceBuildDirector().
mapper_
ResourceMapper ResourceBuildDirector::mapper_ private
Resource mapper.
Definition at line 65 of file ResourceBuildDirector.hh.
Referenced by build().
The documentation for this class was generated from the following files:
ResourceBuildDirector.hh
ResourceBuildDirector.cc