OpenASIP: SlotField Class Reference
SlotField Class Reference
#include <SlotField.hh>
Public Member Functions
virtual ~SlotField ()
MoveSlot * parent () const
void addSocketEncoding (SocketEncoding &encoding)
void removeSocketEncoding (SocketEncoding &encoding)
int socketEncodingCount () const
SocketEncoding & socketEncoding (int index) const
bool hasSocketEncoding (const std::string &socket) const
SocketEncoding & socketEncoding (const std::string &socket) const
void setNoOperationEncoding (NOPEncoding &encoding)
void unsetNoOperationEncoding ()
bool hasNoOperationEncoding () const
NOPEncoding & noOperationEncoding () const
BinaryEncoding::Position componentIDPosition () const
virtual int width () const
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_SLOT_FIELD = "slot_field"
ObjectState name for slot field.
static const std::string OSKEY_COMPONENT_ID_POSITION = "comp_id_pos"
ObjectState attribute key for component ID position.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Protected Member Functions
SlotField (BinaryEncoding::Position componentIDPos, MoveSlot &parent)
SlotField (const ObjectState *state, MoveSlot &parent)
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Private Types
typedef std::vector< SocketEncoding * > SocketEncodingTable
A container type for socket encodings.
Private Member Functions
void clearSocketEncodings ()
void clearNoOperationEncoding ()
Private Attributes
NOPEncoding * nopEncoding_
The NOP encoding.
SocketEncodingTable encodings_
The container for socket encodings.
BinaryEncoding::Position componentIDPos_
Position of the socket and bridge IDs within the field.
Additional Inherited Members
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
SlotField is an abstract base class that models the properties common to SourceField and DestinationField classes.
SlotField contains and manages the encodings for sockets. Encodings for different sources and destinations consists of two parts: socket ID and optional socket code. Socket ID determines the socket. Socket code determines the port (and opcode) the socket is connected to. Socket ID may be on either left or right side of the socket code in the source or destination field. If socket ID is on the left side of socket code, socket ID is aligned to the left end of the whole source/destination field. In the other case, socket ID is aligned to the right end of the source/destination field.
Definition at line 58 of file SlotField.hh.
Member Typedef Documentation
SocketEncodingTable
typedef std::vector<SocketEncoding*> SlotField::SocketEncodingTable private
A container type for socket encodings.
Definition at line 99 of file SlotField.hh.
Constructor & Destructor Documentation
~SlotField()
SlotField::~SlotField () virtual
The destructor.
Definition at line 88 of file SlotField.cc.
                      {
    clearSocketEncodings();
    clearNoOperationEncoding();
}
References clearNoOperationEncoding(), and clearSocketEncodings().
SlotField() [1/2]
SlotField::SlotField (BinaryEncoding::Position componentIDPos, MoveSlot & parent) protected
The constructor.
Parameters
componentIDPos Position of the socket (or bridge) ID within the source or destination field.
parent The parent move slot.
Definition at line 60 of file SlotField.cc.
                      :
    InstructionField(&parent), nopEncoding_(NULL),
    componentIDPos_(componentIDPos) {
}
SlotField() [2/2]
SlotField::SlotField (const ObjectState * state, MoveSlot & parent) protected
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent move slot.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 78 of file SlotField.cc.
    : InstructionField(state, &parent),
      nopEncoding_(NULL),
      componentIDPos_(BinaryEncoding::LEFT) {
    loadState(state);
}
References loadState().
Member Function Documentation
addSocketEncoding()
void SlotField::addSocketEncoding (SocketEncoding & encoding)
Adds the given socket encoding.
This method is to be called from the constructor of SocketEncoding.
Parameters
encoding The socket encoding to be added.
Exceptions
ObjectAlreadyExists If the field already has an encoding for the same socket or if the encoding is already assigned to another socket.
Definition at line 121 of file SlotField.cc.
{
    // verify that this is called from SocketEncoding constructor
    assert(encoding.parent() == NULL);
    if (hasSocketEncoding(encoding.socketName()) ||
    !BEMTester::canAddComponentEncoding(
        *this, encoding.encoding(), encoding.extraBits())) {
    const string procName = "SlotField::addSocketEncoding";
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    encodings_.push_back(&encoding);
}
References assert, BEMTester::canAddComponentEncoding(), Encoding::encoding(), encodings_, Encoding::extraBits(), hasSocketEncoding(), SocketEncoding::parent(), and SocketEncoding::socketName().
Referenced by SocketEncoding::setEncoding(), SocketEncoding::SocketEncoding(), and SocketEncoding::SocketEncoding().
childField()
InstructionField & SlotField::childField (int position) const virtual
Always throws OutOfRange because slot fields do not have any child fields.
Returns
Never returns.
Exceptions
OutOfRange Always throws.
Reimplemented from InstructionField.
Definition at line 345 of file SlotField.cc.
{
    const string procName = "SlotField::childField";
    throw OutOfRange(__FILE__, __LINE__, procName);
}
childFieldCount()
int SlotField::childFieldCount () const virtual
Always returns 0 because slot fields do not have any child fields.
Returns
0.
Implements InstructionField.
Definition at line 333 of file SlotField.cc.
{
    return 0;
}
clearNoOperationEncoding()
void SlotField::clearNoOperationEncoding () private
Deletes the NOP encoding if one exists.
Definition at line 422 of file SlotField.cc.
{
    if (hasNoOperationEncoding()) {
        delete nopEncoding_;
    }
}
References hasNoOperationEncoding(), and nopEncoding_.
Referenced by loadState(), and ~SlotField().
clearSocketEncodings()
void SlotField::clearSocketEncodings () private
Clears all the socket encodings from the slot field.
Definition at line 413 of file SlotField.cc.
{
    SequenceTools::deleteAllItems(encodings_);
}
References SequenceTools::deleteAllItems(), and encodings_.
Referenced by loadState(), and ~SlotField().
componentIDPosition()
BinaryEncoding::Position SlotField::componentIDPosition () const
Returns the position of the component ID within the slot field.
Returns
Position of the component ID.
Definition at line 296 of file SlotField.cc.
{
    return componentIDPos_;
}
References componentIDPos_.
Referenced by BEMTester::calculateAlignment(), DestinationField::DestinationField(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeNOP(), CodeCompressorPlugin::encodeSlotField(), DefaultDecoderGenerator::portCodeCondition(), printSlotFieldEncodings(), printSourceFieldEncodings(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), saveState(), SourceField::SourceField(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
hasNoOperationEncoding()
bool SlotField::hasNoOperationEncoding () const
Tells whether the slot field has a NOP encoding.
Returns
True if the slot field has a NOP encoding, otherwise false.
Definition at line 267 of file SlotField.cc.
{
    return nopEncoding_ != NULL;
}
References nopEncoding_.
Referenced by BEMTester::canAddComponentEncoding(), clearNoOperationEncoding(), CodeCompressorPlugin::encodeNOP(), noOperationEncoding(), printSlotFieldEncodings(), saveState(), setNoOperationEncoding(), unsetNoOperationEncoding(), and width().
hasSocketEncoding()
bool SlotField::hasSocketEncoding (const std::string & socket) const
Tells whether the slot field has an encoding for the socket with the given name.
Parameters
socket Name of the socket.
Returns
True if the slot field has an encoding for the given socket, otherwise false.
Definition at line 188 of file SlotField.cc.
{
    for (SocketEncodingTable::const_iterator iter = encodings_.begin();
     iter != encodings_.end(); iter++) {
    SocketEncoding* encoding = *iter;
    if (encoding->socketName() == socket) {
        return true;
    }
    }
    return false;
}
References encodings_, and SocketEncoding::socketName().
Referenced by addSocketEncoding(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), and CodeCompressorPlugin::encodeRFTerminal().
loadState()
void SlotField::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Reimplemented in SourceField.
Definition at line 358 of file SlotField.cc.
{
    clearSocketEncodings();
    clearNoOperationEncoding();
    InstructionField::loadState(state);
    const string procName = "SlotField::loadState";
    try {
    componentIDPos_ = static_cast<BinaryEncoding::Position>(
        state->intAttribute(OSKEY_COMPONENT_ID_POSITION));
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == SocketEncoding::OSNAME_SOCKET_ENCODING) {
        new SocketEncoding(child, *this);
            } else if (child->name() == NOPEncoding::OSNAME_NOP_ENCODING) {
                new NOPEncoding(child, *this);
        }
    }
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References ObjectState::child(), ObjectState::childCount(), clearNoOperationEncoding(), clearSocketEncodings(), componentIDPos_, Exception::errorMessage(), ObjectState::intAttribute(), InstructionField::loadState(), ObjectState::name(), OSKEY_COMPONENT_ID_POSITION, NOPEncoding::OSNAME_NOP_ENCODING, and SocketEncoding::OSNAME_SOCKET_ENCODING.
Referenced by SourceField::loadState(), and SlotField().
noOperationEncoding()
NOPEncoding & SlotField::noOperationEncoding () const
Returns the NOP encoding.
Returns NullNOPEncoding instance if the slot field does not have a NOP encoding.
Returns
The NOP encoding.
Definition at line 281 of file SlotField.cc.
{
    if (hasNoOperationEncoding()) {
        return *nopEncoding_;
    } else {
        return NullNOPEncoding::instance();
    }
}
References hasNoOperationEncoding(), NullNOPEncoding::instance(), and nopEncoding_.
Referenced by BEMTester::canAddComponentEncoding(), CodeCompressorPlugin::encodeNOP(), printSlotFieldEncodings(), saveState(), unsetNoOperationEncoding(), and width().
parent()
MoveSlot * SlotField::parent () const
Returns the parent move slot.
Definition at line 98 of file SlotField.cc.
{
    InstructionField* parent = InstructionField::parent();
    if (parent == NULL) {
    return NULL;
    } else {
    MoveSlot* slot = dynamic_cast<MoveSlot*>(parent);
    assert(slot != NULL);
    return slot;
    }
}
References assert, InstructionField::parent(), and parent().
Referenced by CodeCompressorPlugin::addBitsForDestinationField(), CodeCompressorPlugin::addBitsForSourceField(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMValidator::checkSocketCodeTable(), DestinationField::DestinationField(), DestinationField::DestinationField(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), parent(), DefaultDecoderGenerator::portCodeCondition(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), MoveSlot::setDestinationField(), SourceField::setImmediateEncoding(), MoveSlot::setSourceField(), SocketEncoding::SocketEncoding(), DefaultDecoderGenerator::socketEncodingCondition(), SourceField::SourceField(), SourceField::SourceField(), SourceField::unsetImmediateEncoding(), unsetNoOperationEncoding(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DestinationField::~DestinationField(), and SourceField::~SourceField().
removeSocketEncoding()
void SlotField::removeSocketEncoding (SocketEncoding & encoding)
Removes the given socket encoding.
This method is to be called from SocketEncoding destructor.
Parameters
encoding The socket encoding to be removed.
Definition at line 143 of file SlotField.cc.
{
    // verify that this is called from SocketEncoding destructor
    assert(encoding.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(encodings_, &encoding));
}
References assert, encodings_, SocketEncoding::parent(), and ContainerTools::removeValueIfExists().
Referenced by SocketEncoding::detachFromParent().
saveState()
ObjectState * SlotField::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from InstructionField.
Reimplemented in DestinationField, and SourceField.
Definition at line 388 of file SlotField.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_SLOT_FIELD);
    state->setAttribute(OSKEY_COMPONENT_ID_POSITION, componentIDPosition());
    // add socket encodings
    for (int i = 0; i < socketEncodingCount(); i++) {
    SocketEncoding& enc = socketEncoding(i);
    state->addChild(enc.saveState());
    }
    // add NOP encoding
    if (hasNoOperationEncoding()) {
        state->addChild(noOperationEncoding().saveState());
    }
    return state;
}
References ObjectState::addChild(), componentIDPosition(), hasNoOperationEncoding(), noOperationEncoding(), OSKEY_COMPONENT_ID_POSITION, OSNAME_SLOT_FIELD, InstructionField::saveState(), saveState(), SocketEncoding::saveState(), ObjectState::setAttribute(), ObjectState::setName(), socketEncoding(), and socketEncodingCount().
Referenced by DestinationField::saveState(), saveState(), and SourceField::saveState().
setNoOperationEncoding()
void SlotField::setNoOperationEncoding (NOPEncoding & encoding)
Sets the given encoding for no operation.
This method is to be called from the constructor of NOPEncoding.
Parameters
encoding The encoding to be set.
Exceptions
ObjectAlreadyExists If the slot field has a NOP encoding already or if the given encoding is ambiguous with some other encoding.
Definition at line 234 of file SlotField.cc.
{
    assert(encoding.parent() == NULL);
    if (hasNoOperationEncoding() ||
        !BEMTester::canAddComponentEncoding(
            *this, encoding.encoding(), encoding.extraBits())) {
        const string procName = "SlotField::setNoOperationEncoding";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    nopEncoding_ = &encoding;
}
References assert, BEMTester::canAddComponentEncoding(), Encoding::encoding(), Encoding::extraBits(), hasNoOperationEncoding(), nopEncoding_, and NOPEncoding::parent().
Referenced by NOPEncoding::NOPEncoding(), and NOPEncoding::NOPEncoding().
socketEncoding() [1/2]
SocketEncoding & SlotField::socketEncoding (const std::string & socket) const
Returns the socket encoding of the socket with the given name.
Returns a NullSocketEncoding instance if this field does not encode the socket.
Parameters
socket Name of the socket.
Returns
The socket encoding of the given socket.
Definition at line 210 of file SlotField.cc.
{
    for (SocketEncodingTable::const_iterator iter = encodings_.begin();
     iter != encodings_.end(); iter++) {
    SocketEncoding* encoding = *iter;
    if (encoding->socketName() == socket) {
        return **iter;
    }
    }
    return NullSocketEncoding::instance();
}
References encodings_, NullSocketEncoding::instance(), and SocketEncoding::socketName().
socketEncoding() [2/2]
SocketEncoding & SlotField::socketEncoding (int index) const
Returns the socket encoding stored at the given position.
Parameters
index The position.
Returns
The socket encoding.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of sockets encoded in the field.
Definition at line 170 of file SlotField.cc.
{
    if (index < 0 || index >= socketEncodingCount()) {
    const string procName = "SlotField::socketEncoding";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *encodings_[index];
}
References encodings_, and socketEncodingCount().
Referenced by BEMTester::canAddComponentEncoding(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), printSlotFieldEncodings(), SocketCodeTable::removeReferences(), saveState(), DefaultDecoderGenerator::socketEncodingCondition(), width(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
socketEncodingCount()
int SlotField::socketEncodingCount () const
Returns the number of sockets that are encoded in this field.
Returns
The number of sockets.
Definition at line 156 of file SlotField.cc.
{
    return encodings_.size();
}
References encodings_.
Referenced by BEMTester::canAddComponentEncoding(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), printSlotFieldEncodings(), SocketCodeTable::removeReferences(), saveState(), socketEncoding(), and width().
unsetNoOperationEncoding()
void SlotField::unsetNoOperationEncoding ()
Unsets the NOP encoding.
This method is to be called from the destructor of NOPEncoding.
Definition at line 253 of file SlotField.cc.
{
    assert(hasNoOperationEncoding());
    assert(noOperationEncoding().parent() == NULL);
    nopEncoding_ = NULL;
}
References assert, hasNoOperationEncoding(), noOperationEncoding(), nopEncoding_, and parent().
Referenced by NOPEncoding::~NOPEncoding().
width()
int SlotField::width () const virtual
Returns the bit width required by the socket encodings.
Returns
The bit width.
Implements InstructionField.
Reimplemented in SourceField.
Definition at line 307 of file SlotField.cc.
                       {
    int width(0);
    int encodings = socketEncodingCount();
    for (int i = 0; i < encodings; i++) {
    SocketEncoding& encoding = socketEncoding(i);
    int encodingWidth = encoding.width();
    if (encodingWidth > width) {
        width = encodingWidth;
    }
    }
    if (hasNoOperationEncoding() && noOperationEncoding().width() > width) {
        width = noOperationEncoding().width();
    }
    return width + extraBits();
}
References InstructionField::extraBits(), hasNoOperationEncoding(), noOperationEncoding(), socketEncoding(), socketEncodingCount(), Encoding::width(), width(), and SocketEncoding::width().
Referenced by NOPEncoding::bitPosition(), BEMTester::canAddComponentPriorityEncoding(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), CodeCompressorPlugin::encodeSlotField(), ProGe::RV32MicroCodeGenerator::findBusWidths(), printMoveSlotLayout(), printSlotFieldEncodings(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), SocketEncoding::socketCodePosition(), SocketEncoding::socketIDPosition(), MoveSlot::width(), width(), SourceField::width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
Member Data Documentation
componentIDPos_
BinaryEncoding::Position SlotField::componentIDPos_ private
Position of the socket and bridge IDs within the field.
Definition at line 109 of file SlotField.hh.
Referenced by componentIDPosition(), and loadState().
encodings_
SocketEncodingTable SlotField::encodings_ private
The container for socket encodings.
Definition at line 107 of file SlotField.hh.
Referenced by addSocketEncoding(), clearSocketEncodings(), hasSocketEncoding(), removeSocketEncoding(), socketEncoding(), socketEncoding(), and socketEncodingCount().
nopEncoding_
NOPEncoding* SlotField::nopEncoding_ private
The NOP encoding.
Definition at line 105 of file SlotField.hh.
Referenced by clearNoOperationEncoding(), hasNoOperationEncoding(), noOperationEncoding(), setNoOperationEncoding(), and unsetNoOperationEncoding().
OSKEY_COMPONENT_ID_POSITION
const std::string SlotField::OSKEY_COMPONENT_ID_POSITION = "comp_id_pos" static
ObjectState attribute key for component ID position.
Definition at line 91 of file SlotField.hh.
Referenced by loadState(), saveState(), BEMSerializer::slotFieldToFile(), and BEMSerializer::slotFieldToOM().
OSNAME_SLOT_FIELD
const std::string SlotField::OSNAME_SLOT_FIELD = "slot_field" static
ObjectState name for slot field.
Definition at line 89 of file SlotField.hh.
Referenced by saveState(), and BEMSerializer::slotFieldToOM().
The documentation for this class was generated from the following files:
SlotField.hh
SlotField.cc