OpenASIP: ProximShowRegistersCmd Class Reference
ProximShowRegistersCmd Class Reference
#include <ProximShowRegistersCmd.hh>
Public Member Functions
ProximShowRegistersCmd (EditPart *part)
virtual ~ProximShowRegistersCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * part_
Detailed Description
Command for opening a register window displaying register state of a registerfile.
Definition at line 45 of file ProximShowRegistersCmd.hh.
Constructor & Destructor Documentation
ProximShowRegistersCmd()
ProximShowRegistersCmd::ProximShowRegistersCmd (EditPart * part)
The Constructor.
Definition at line 42 of file ProximShowRegistersCmd.cc.
                    :
    ComponentCommand(),
    part_(part) {
}
~ProximShowRegistersCmd()
ProximShowRegistersCmd::~ProximShowRegistersCmd () virtual
The Destructor.
Definition at line 53 of file ProximShowRegistersCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximShowRegistersCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 64 of file ProximShowRegistersCmd.cc.
{
    std::string rfName =
        dynamic_cast<TTAMachine::Component*>(part_->model())->name();
    ProximRegisterWindow* regWindow = new ProximRegisterWindow(
        ProximToolbox::mainFrame(), -1);
    ProximToolbox::addFramedWindow(
        regWindow, _T("Registers"), false, wxSize(270, 200));
    regWindow->GetParent()->SetSize(270, 300);
    regWindow->showRegisterFile(rfName);
    return true;
}
References ProximToolbox::addFramedWindow(), ProximToolbox::mainFrame(), EditPart::model(), part_, and ProximRegisterWindow::showRegisterFile().
Member Data Documentation
part_
EditPart* ProximShowRegistersCmd::part_ private
Definition at line 52 of file ProximShowRegistersCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximShowRegistersCmd.hh
ProximShowRegistersCmd.cc