OpenASIP: TPEF::Section Class Reference
TPEF::Section Class Reference abstract
#include <Section.hh>
Public Types
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Public Member Functions
virtual SectionType type () const =0
Returns SectioType of actual section instance.
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Static Public Member Functions
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Protected Member Functions
virtual Section * clone () const =0
Creates clone of instance.
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Static Protected Member Functions
static void registerSection (const Section *section)
Private Types
typedef std::map< SectionType, const Section * > SectionPrototypeMap
Type of map that contains section prototypes.
Private Member Functions
Section (const Section &)
bool flag (SectionFlag aFlag) const
void setFlag (SectionFlag aFlag)
void unsetFlag (SectionFlag aFlag)
Private Attributes
std::vector< SectionElement * > elements_
Contain elements.
const ReferenceManager::SafePointer * link_
TPEF link field.
const ReferenceManager::SafePointer * aSpace_
TPEF address space field.
const ReferenceManager::SafePointer * name_
TPEF name field.
Byte flags_
TPEF flag byte.
Word startingAddress_
TPEF startin memory address field.
Static Private Attributes
static SectionPrototypeMap * prototypes_ = NULL
Container for registere section prototypes.
static const Byte PROGRAM_SECTION_MASK = 0x80
Mask for checking if section is auxiliary or program section.
Detailed Description
Abstract base class for concrete sections.
Stores section header data and handles registration requests and book keeping for concrete sections. See prototype design pattern.
Definition at line 64 of file Section.hh.
Member Typedef Documentation
SectionPrototypeMap
typedef std::map<SectionType, const Section*> TPEF::Section::SectionPrototypeMap private
Type of map that contains section prototypes.
Definition at line 165 of file Section.hh.
Member Enumeration Documentation
SectionFlag
enum TPEF::Section::SectionFlag
TPEF section flags.
Enumerator
SF_VLEN
Contains elements with variable length.
SF_NOBITS
Not initialized or not stored in this file.
Definition at line 89 of file Section.hh.
                     {
        SF_VLEN   = 0x40, ///< Contains elements with variable length.
        SF_NOBITS = 0x80  ///< Not initialized or not stored in this file.
    };
SectionType
enum TPEF::Section::SectionType
TPEF section type ids.
Enumerator
ST_NULL
NULL Section.
ST_STRTAB
String table.
ST_SYMTAB
Symbol table.
ST_DEBUG
Debug section.
ST_RELOC
Relocation section.
ST_LINENO
Line number section.
ST_NOTE
Note section.
ST_ADDRSP
Address space section.
ST_MR
Machine resources section.
ST_CODE
Text section.
ST_DATA
Initialized data section.
ST_UDATA
Uninitialized data section.
ST_LEDATA
Initialized little endian data section.
ST_DUMMY
Dummy section type for testing purposes.
Definition at line 69 of file Section.hh.
                     {
        ST_NULL   = 0x00, ///< NULL Section
        ST_STRTAB = 0x01, ///< String table.
        ST_SYMTAB = 0x02, ///< Symbol table.
        ST_DEBUG  = 0x03, ///< Debug section.
        ST_RELOC  = 0x04, ///< Relocation section.
        ST_LINENO = 0x05, ///< Line number section.
        ST_NOTE   = 0x06, ///< Note section.
        ST_ADDRSP = 0x07, ///< Address space section.
        ST_MR     = 0x0A, ///< Machine resources section.
        ST_CODE   = 0x81, ///< Text section.
        ST_DATA   = 0x82, ///< Initialized data section.
        ST_UDATA  = 0x83, ///< Uninitialized data section.
        ST_LEDATA = 0x84, ///< Initialized little endian data section.
        ST_DUMMY  = 0xff  ///< Dummy section type for testing purposes.
    };
Constructor & Destructor Documentation
~Section()
TPEF::Section::~Section () virtual
Destructor.
Definition at line 76 of file Section.cc.
                  {
    while (elements_.size() != 0) {
        delete elements_[elements_.size() - 1];
        elements_.pop_back();
    }
}
References elements_.
Section() [1/2]
TPEF::Section::Section () protected
Constructor.
Definition at line 64 of file Section.cc.
                 :
    SafePointable(),
    link_(&SafePointer::null),
    aSpace_(&SafePointer::null),
    name_(&SafePointer::null),
    flags_(0),
    startingAddress_(0) {
}
Section() [2/2]
TPEF::Section::Section (const Section &) private
Member Function Documentation
addElement()
void TPEF::Section::addElement (SectionElement * element) virtual
Adds an element to section.
Parameters
element Element that is added to section.
Reimplemented in TPEF::CodeSection.
Definition at line 133 of file Section.cc.
{
    assert(element != NULL);
    elements_.push_back(element);
}
References assert, element(), and elements_.
Referenced by TPEF::CodeSection::addElement(), MachineResourceManager::addResourceElement(), TTAProgram::TPEFResourceUpdater::bus(), MachineResourceManager::codeAddressSpace(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::finalize(), MachineResourceManager::findDataAddressSpace(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), TPEF::AOutSymbolSectionReader::initializeSymbol(), MachineResourceManager::initResourceSection(), TTAProgram::TPEFResourceUpdater::operand(), TPEF::AOutReader::readData(), TPEF::AOutRelocationSectionReader::readData(), TPEF::AOutSymbolSectionReader::readData(), TPEF::AOutTextSectionReader::readData(), TPEF::TPEFASpaceSectionReader::readData(), TPEF::TPEFDebugSectionReader::readData(), TPEF::TPEFLineNumSectionReader::readData(), TPEF::TPEFRelocSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), TTAProgram::TPEFResourceUpdater::registerFile(), MachineResourceManager::undefinedAddressSpace(), and LabelManager::writeProcedureSymbols().
aSpace()
ASpaceElement * TPEF::Section::aSpace () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), TPEF::DataSection::addMAU(), TTAProgram::TPEFProgramFactory::build(), TPEF::RawSection::bytesToMAUs(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::TPEFDataSectionWriter::elementSize(), TPEF::TPEFUDataSectionWriter::elementSize(), TPEF::TPEFRelocSectionReader::finalize(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), TPEF::ASpaceSection::isUndefined(), TPEF::RawSection::MAUsToBytes(), TPEFDumper::memoryInfo(), TPEFDumper::sectionHeader(), TPEF::TPEFReader::sectionOfAddress(), TPEF::ASpaceSection::setUndefinedASpace(), DataSectionCreator::writeDataLineToTPEF(), ProgramImageGenerator::writeDataSection(), TPEF::DataSection::writeValue(), TPEF::LEDataSection::writeValue(), TPEF::DataSection::writeValue(), and TPEF::LEDataSection::writeValue().
chunk()
Chunk * TPEF::Section::chunk (SectionOffset offset) const virtual
Returns a chunk that has offset to a data of section.
Parameters
offset Offset to a data that is wanted to be referenced.
Returns
Chunk for raw data section.
Exceptions
NotChunkable If Section is not derived from RawSection.
Reimplemented in TPEF::RawSection.
Definition at line 169 of file Section.cc.
{
    throw NotChunkable(__FILE__, __LINE__, "Section::chunk");
}
Referenced by TPEF::TPEFStringSectionWriter::actualWriteData(), TPEF::ReferenceManager::SafePointer::resolve(), and TPEF::TPEFSectionWriter::writeBodyStartOffset().
clone()
virtual Section * TPEF::Section::clone () const protected pure virtual
Creates clone of instance.
Implemented in TPEF::ASpaceSection, TPEF::CodeSection, TPEF::DataSection, TPEF::DebugSection, TPEF::LEDataSection, TPEF::LineNumSection, TPEF::NullSection, TPEF::RelocSection, TPEF::ResourceSection, TPEF::StringSection, TPEF::SymbolSection, and TPEF::UDataSection.
Referenced by createSection().
createSection()
Section * TPEF::Section::createSection (SectionType type) static
Creates instance of concrete section type.
Parameters
type Type of section instance that is to be created.
Returns
Pointer to newly created section.
Exceptions
InstanceNotFound If there is no registered instance for type.
Definition at line 91 of file Section.cc.
{
    if (prototypes_ == NULL ||
        !MapTools::containsKey(*prototypes_,type)) {
        throw InstanceNotFound(
            __FILE__, __LINE__, __func__,
            TCEString("No prototype for section type: ") +
            Conversion::toString(static_cast<int>(type)));
    }
    Section* section = (*prototypes_)[type]->clone();
    return section;
}
References __func__, clone(), MapTools::containsKey(), prototypes_, Conversion::toString(), and type().
Referenced by CodeSectionCreator::finalize(), DataSectionCreator::finalize(), MachineResourceManager::initResourceSection(), MachineResourceManager::nullSection(), TPEF::AOutReader::readData(), TPEF::TPEFReader::readData(), MachineResourceManager::stringToChunk(), and MachineResourceManager::undefinedAddressSpace().
element()
SectionElement * TPEF::Section::element (Word index) const
Referenced by TPEF::TPEFCodeSectionWriter::actualWriteData(), TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEF::TPEFDebugSectionWriter::actualWriteData(), TPEF::TPEFLineNumSectionWriter::actualWriteData(), TPEF::TPEFRelocSectionWriter::actualWriteData(), TPEF::TPEFResourceSectionWriter::actualWriteData(), TPEF::TPEFSymbolSectionWriter::actualWriteData(), addElement(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createLabels(), TTAProgram::ProgramWriter::createRelocSections(), TPEF::CodeSection::element(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), TPEFDumper::findElementIndex(), TPEF::ResourceSection::findResource(), TPEF::TPEFTools::hasRelocation(), TPEF::ResourceSection::hasResource(), TTAProgram::TPEFResourceUpdater::initCache(), CodeCompressorPlugin::initializeRelocations(), TPEF::TPEFTools::initRelocationCache(), TPEFDumper::memoryInfo(), TPEF::TPEFTools::relocation(), ProgramImageGenerator::relocTarget(), TTAProgram::ProgramWriter::resolveFileType(), TPEFDumper::section(), TPEF::TPEFTools::sectionOfElement(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), setElement(), and TPEF::TPEFSectionWriter::writeBodyStartOffset().
elementCount()
Word TPEF::Section::elementCount () const
Referenced by TPEF::TPEFCodeSectionWriter::actualWriteData(), TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEF::TPEFDebugSectionWriter::actualWriteData(), TPEF::TPEFLineNumSectionWriter::actualWriteData(), TPEF::TPEFRelocSectionWriter::actualWriteData(), TPEF::TPEFResourceSectionWriter::actualWriteData(), TPEF::TPEFSymbolSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::addProcedures(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), TPEFDumper::findElementIndex(), TPEF::ResourceSection::findResource(), TPEF::TPEFTools::hasRelocation(), TPEF::ResourceSection::hasResource(), CodeCompressorPlugin::immediateTerminal(), TTAProgram::TPEFResourceUpdater::initCache(), TPEFDisassembler::initCache(), CodeCompressorPlugin::initializeRelocations(), TPEF::CodeSection::initInstructionCache(), TPEF::TPEFTools::initRelocationCache(), TPEFDumper::memoryInfo(), TPEF::TPEFTools::relocation(), ProgramImageGenerator::relocTarget(), TTAProgram::ProgramWriter::resolveFileType(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TPEF::TPEFTools::sectionOfElement(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), and setElement().
flag()
bool TPEF::Section::flag (SectionFlag aFlag) const private
flags()
Byte TPEF::Section::flags () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), and TPEFDumper::sectionHeader().
isAuxSection()
bool TPEF::Section::isAuxSection () const
isChunkable()
bool TPEF::Section::isChunkable () const virtual
Returns true if section is chunkable.
Returns
True if section is chunkable.
Reimplemented in TPEF::RawSection.
Definition at line 157 of file Section.cc.
{
    return false;
}
Referenced by TPEFDumper::sectionHeader(), TPEF::TPEFTools::sectionOfElement(), and TPEF::TPEFSectionWriter::writeBodyStartOffset().
isCodeSection()
virtual bool TPEF::Section::isCodeSection () const inline virtual
Reimplemented in TPEF::CodeSection.
Definition at line 143 of file Section.hh.
{ return false; }
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::createSymbolWithReference(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), TPEF::AOutRelocationSectionReader::readData(), TPEF::TPEFReader::sectionOfAddress(), and TPEF::TPEFTools::sectionOfElement().
isDataSection()
virtual bool TPEF::Section::isDataSection () const inline virtual
Reimplemented in TPEF::DataSection.
Definition at line 142 of file Section.hh.
{ return false; }
Referenced by TTAProgram::ProgramWriter::createDataSections().
isProgramSection() [1/2]
bool TPEF::Section::isProgramSection () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), TTAProgram::ProgramWriter::findSection(), TPEFDumper::memoryInfo(), and TPEF::TPEFReader::readData().
isProgramSection() [2/2]
static bool TPEF::Section::isProgramSection (SectionType type) static
link()
Section * TPEF::Section::link () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), TTAProgram::TPEFProgramFactory::addProcedures(), TPEF::TPEFTools::addressSpaceName(), TPEFDumper::addressSpaceString(), TTAProgram::TPEFProgramFactory::build(), TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::ProgramWriter::createDataSections(), TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createLabels(), TTAProgram::TPEFProgramFactory::createTerminal(), TPEF::AOutSymbolSectionReader::finalize(), TTAProgram::TPEFProgramFactory::findBus(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), TTAProgram::TPEFProgramFactory::findRegisterFile(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), TTAProgram::TPEFResourceUpdater::initCache(), TTAProgram::TPEFResourceUpdater::operand(), TTAProgram::TPEFResourceUpdater::registerFile(), TPEF::TPEFTools::resourceName(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), and TPEFDumper::symbolString().
name()
Chunk * TPEF::Section::name () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), and TPEFDumper::sectionHeader().
noBits()
bool TPEF::Section::noBits () const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), TPEF::TPEFSectionWriter::actualWriteHeader(), TPEF::TPEFASpaceSectionReader::readData(), TPEF::TPEFCodeSectionReader::readData(), TPEF::TPEFDataSectionReader::readData(), TPEF::TPEFDebugSectionReader::readData(), TPEF::TPEFLineNumSectionReader::readData(), TPEF::TPEFRelocSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), and TPEF::TPEFSectionWriter::writeBodyStartOffset().
registerSection()
void TPEF::Section::registerSection (const Section * section) static protected
Registers section instance that implements some section type.
Every registered prototype implements one of used sections. These registered sections are used to clone section instances by SectionType.
Parameters
section Section instance that will be registered.
Definition at line 114 of file Section.cc.
{
    // We can't create prototypes_ map statically, because we don't know
    //if it is initialized before this method is called.
    if (prototypes_ == NULL) {
        prototypes_ = new SectionPrototypeMap();
    }
    assert(!MapTools::containsKey(*prototypes_, section->type()));
    (*prototypes_)[section->type()] = section;
}
References assert, MapTools::containsKey(), prototypes_, and type().
Referenced by TPEF::ASpaceSection::ASpaceSection(), TPEF::CodeSection::CodeSection(), TPEF::DataSection::DataSection(), TPEF::DebugSection::DebugSection(), TPEF::LEDataSection::LEDataSection(), TPEF::LineNumSection::LineNumSection(), TPEF::NullSection::NullSection(), TPEF::RelocSection::RelocSection(), TPEF::ResourceSection::ResourceSection(), TPEF::StringSection::StringSection(), TPEF::SymbolSection::SymbolSection(), and TPEF::UDataSection::UDataSection().
setASpace() [1/2]
void TPEF::Section::setASpace (ASpaceElement * addrSpace)
setASpace() [2/2]
void TPEF::Section::setASpace (const ReferenceManager::SafePointer * addrSpace)
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), CodeSectionCreator::finalize(), DataSectionCreator::finalize(), LabelManager::findOrCreateRelocationSection(), MachineResourceManager::initResourceSection(), MachineResourceManager::nullSection(), TPEF::AOutReader::readData(), TPEF::TPEFSectionReader::readData(), MachineResourceManager::stringToChunk(), and MachineResourceManager::undefinedAddressSpace().
setElement()
void TPEF::Section::setElement (Word index, SectionElement * element) virtual
Sets replaces an element in given index with another.
Parameters
index Index of element that is replaced.
element Element that is set to given index.
Reimplemented in TPEF::CodeSection.
Definition at line 145 of file Section.cc.
{
    assert(element != NULL);
    assert(index < elementCount());
    elements_[index] = element;
}
References assert, element(), elementCount(), and elements_.
Referenced by TPEF::AOutSymbolSectionReader::finalize(), and TPEF::CodeSection::setElement().
setFlag()
void TPEF::Section::setFlag (SectionFlag aFlag) private
setFlagNoBits()
void TPEF::Section::setFlagNoBits ()
Referenced by TPEF::NullSection::NullSection(), and TPEF::UDataSection::UDataSection().
setFlags()
void TPEF::Section::setFlags (Byte flagByte)
Referenced by TPEF::TPEFSectionReader::readData().
setFlagVLen()
void TPEF::Section::setFlagVLen () protected
Referenced by TPEF::CodeSection::CodeSection(), and TPEF::DebugSection::DebugSection().
setLink() [1/2]
void TPEF::Section::setLink (const ReferenceManager::SafePointer * aLink)
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), CodeSectionCreator::finalize(), LabelManager::findOrCreateRelocationSection(), MachineResourceManager::initResourceSection(), MachineResourceManager::nullSection(), TPEF::AOutReader::readData(), TPEF::TPEFSectionReader::readData(), MachineResourceManager::stringToChunk(), and MachineResourceManager::undefinedAddressSpace().
setLink() [2/2]
void TPEF::Section::setLink (Section * aLink)
setName() [1/2]
void TPEF::Section::setName (Chunk * sectionName)
setName() [2/2]
void TPEF::Section::setName (const ReferenceManager::SafePointer * sectionName)
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::ProgramWriter::createRelocSections(), CodeSectionCreator::finalize(), DataSectionCreator::finalize(), MachineResourceManager::initResourceSection(), MachineResourceManager::nullSection(), TPEF::AOutReader::readData(), TPEF::TPEFSectionReader::readData(), and MachineResourceManager::undefinedAddressSpace().
setStartingAddress()
void TPEF::Section::setStartingAddress (AddressImage address)
Referenced by TPEF::ASpaceSection::ASpaceSection(), TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::ProgramWriter::createDataSections(), DataSectionCreator::finalize(), TPEF::LineNumSection::LineNumSection(), TPEF::NullSection::NullSection(), TPEF::AOutReader::readData(), TPEF::TPEFSectionReader::readData(), TPEF::RelocSection::RelocSection(), TPEF::ResourceSection::ResourceSection(), and TPEF::UDataSection::UDataSection().
startingAddress()
AddressImage TPEF::Section::startingAddress () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), TTAProgram::TPEFProgramFactory::addProcedures(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::TPEFProgramFactory::createLabels(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::createSymbolWithReference(), LabelManager::finalize(), TPEF::TPEFRelocSectionReader::finalize(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), TPEFDumper::memoryInfo(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TPEF::TPEFReader::sectionOfAddress(), TPEFDisassembler::startAddress(), ProgramImageGenerator::writeDataSection(), and LabelManager::writeProcedureSymbols().
type()
virtual SectionType TPEF::Section::type () const pure virtual
Returns SectioType of actual section instance.
Implemented in TPEF::ASpaceSection, TPEF::CodeSection, TPEF::DataSection, TPEF::DebugSection, TPEF::LEDataSection, TPEF::LineNumSection, TPEF::NullSection, TPEF::RelocSection, TPEF::ResourceSection, TPEF::StringSection, TPEF::SymbolSection, and TPEF::UDataSection.
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), TPEF::TPEFReader::aSpaceSection(), TTAProgram::TPEFProgramFactory::createDataMemories(), createSection(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), TPEF::SectionReader::finalizeBinary(), TPEF::SectionWriter::finalizeBinary(), LabelManager::findRelocationDstSection(), LabelManager::findSectionByAddress(), TPEFDumper::memoryInfo(), TPEF::AOutRelocationSectionReader::readData(), TPEF::SectionReader::readSection(), registerSection(), TPEFDumper::relocationTables(), TPEFDumper::section(), TPEFDumper::sectionHeader(), TPEFDumper::sectionString(), TPEFDumper::symbolTables(), TPEF::SectionWriter::writeData(), and TPEF::SectionWriter::writeHeader().
unsetFlag()
void TPEF::Section::unsetFlag (SectionFlag aFlag) private
unsetFlagNoBits()
void TPEF::Section::unsetFlagNoBits ()
Referenced by TPEF::ASpaceSection::ASpaceSection(), TPEF::CodeSection::CodeSection(), TPEF::DataSection::DataSection(), TPEF::DebugSection::DebugSection(), TPEF::LEDataSection::LEDataSection(), TPEF::LineNumSection::LineNumSection(), TPEF::RelocSection::RelocSection(), TPEF::ResourceSection::ResourceSection(), TPEF::StringSection::StringSection(), and TPEF::SymbolSection::SymbolSection().
unsetFlagVLen()
void TPEF::Section::unsetFlagVLen () protected
Referenced by TPEF::ASpaceSection::ASpaceSection(), TPEF::DataSection::DataSection(), TPEF::LEDataSection::LEDataSection(), TPEF::LineNumSection::LineNumSection(), TPEF::NullSection::NullSection(), TPEF::RelocSection::RelocSection(), TPEF::ResourceSection::ResourceSection(), TPEF::StringSection::StringSection(), TPEF::SymbolSection::SymbolSection(), and TPEF::UDataSection::UDataSection().
vLen()
bool TPEF::Section::vLen () const
Referenced by TPEF::TPEFSectionWriter::actualWriteHeader(), and TPEF::TPEFSectionReader::readData().
Member Data Documentation
aSpace_
const ReferenceManager::SafePointer* TPEF::Section::aSpace_ private
TPEF address space field.
Definition at line 175 of file Section.hh.
elements_
std::vector<SectionElement*> TPEF::Section::elements_ private
Contain elements.
Definition at line 170 of file Section.hh.
Referenced by addElement(), setElement(), and ~Section().
flags_
Byte TPEF::Section::flags_ private
TPEF flag byte.
Definition at line 179 of file Section.hh.
link_
const ReferenceManager::SafePointer* TPEF::Section::link_ private
TPEF link field.
Definition at line 173 of file Section.hh.
name_
const ReferenceManager::SafePointer* TPEF::Section::name_ private
TPEF name field.
Definition at line 177 of file Section.hh.
PROGRAM_SECTION_MASK
const Byte TPEF::Section::PROGRAM_SECTION_MASK = 0x80 static private
Mask for checking if section is auxiliary or program section.
Definition at line 183 of file Section.hh.
prototypes_
Section::SectionPrototypeMap * TPEF::Section::prototypes_ = NULL static private
Container for registere section prototypes.
Definition at line 168 of file Section.hh.
Referenced by createSection(), and registerSection().
startingAddress_
Word TPEF::Section::startingAddress_ private
TPEF startin memory address field.
Definition at line 181 of file Section.hh.
The documentation for this class was generated from the following files:
Section.hh
Section.cc