OpenASIP: ProximDebuggerWindow Class Reference
ProximDebuggerWindow Class Reference
#include <ProximDebuggerWindow.hh>
Public Member Functions
ProximDebuggerWindow (ProximMainFrame *parent, int id)
virtual ~ProximDebuggerWindow ()
virtual void reset ()
void loadProgram (const TTAProgram::Program &program)
void updateAnnotations ()
void loadSourceCode (wxString sourceFile)
void setLineAttributes (int lineNum, wxTextAttr style)
void highlightLine (int lineNum)
void showLine (int lineNum)
Private Types
enum { ID_SOURCEFILE_CHOICE = 19000 , ID_SOURCECODE }
Private Member Functions
void onProgramLoaded (const SimulatorEvent &event)
void onSimulationStop (const SimulatorEvent &event)
void onSourceFileChoice (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
wxString currentFile_
std::vector< int > currentLineNums_
wxChoice * sourceFileList_
wxTextCtrl * sourceCodeText_
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Proxim subwindow which displays program source code annotations.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 54 of file ProximDebuggerWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_SOURCEFILE_CHOICE
ID_SOURCECODE
Definition at line 82 of file ProximDebuggerWindow.hh.
         {
        ID_SOURCEFILE_CHOICE = 19000,
        ID_SOURCECODE
    };
Constructor & Destructor Documentation
ProximDebuggerWindow()
ProximDebuggerWindow::ProximDebuggerWindow (ProximMainFrame * parent, int id)
Definition at line 58 of file ProximDebuggerWindow.cc.
                                    :
    ProximSimulatorWindow(parent, id, wxDefaultPosition, wxSize(800,600)),
    currentFile_() {
    createContents(this, true, true);
    loadProgram(ProximToolbox::program());
}
References ProximToolbox::program().
~ProximDebuggerWindow()
ProximDebuggerWindow::~ProximDebuggerWindow () virtual
Definition at line 68 of file ProximDebuggerWindow.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ProximDebuggerWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the window contents.
Code generated by wxDesigner.
Definition at line 250 of file ProximDebuggerWindow.cc.
{
    wxBoxSizer *mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *upperSizer = new wxBoxSizer(wxHORIZONTAL);
    sourceFileList_ = new wxChoice(
        parent, ID_SOURCEFILE_CHOICE, wxDefaultPosition, wxDefaultSize);
    upperSizer->Add(sourceFileList_, 1, wxGROW|wxALL, 5);
    mainSizer->Add(upperSizer, 0, wxGROW|wxALL, 5);
    sourceCodeText_ = new wxTextCtrl(
        parent, ID_SOURCECODE, wxEmptyString, wxDefaultPosition,
        wxSize(640, 600), wxTE_MULTILINE | wxTE_READONLY | wxTE_DONTWRAP);
    mainSizer->Add(sourceCodeText_, 1, wxGROW|wxALL, 5);
    if (set_sizer)
    {
        parent->SetSizer( mainSizer );
        if (call_fit)
            mainSizer->SetSizeHints( parent );
    }
    return mainSizer;
}
References ID_SOURCECODE, ID_SOURCEFILE_CHOICE, sourceCodeText_, and sourceFileList_.
highlightLine()
void ProximDebuggerWindow::highlightLine (int lineNum)
Highlights line of code in the sourceCodeText_ widget
Parameters
lineNum Source code line number.
Definition at line 185 of file ProximDebuggerWindow.cc.
{
    if (std::find(currentLineNums_.begin(), currentLineNums_.end(), lineNum) ==
        currentLineNums_.end()) {
        currentLineNums_.push_back(lineNum);
        setLineAttributes(lineNum, wxTextAttr(*wxWHITE, *wxBLUE));
    }
}
References currentLineNums_, and setLineAttributes().
Referenced by updateAnnotations().
loadProgram()
void ProximDebuggerWindow::loadProgram (const TTAProgram::Program & program)
Loads a program model to the window.
Parameters
program Program to load.
Definition at line 91 of file ProximDebuggerWindow.cc.
{
    // get list of used source code files for drop-down list
    for (int i = 0; i < program.moveCount(); i++) {
        const TTAProgram::Move& m = program.moveAt(i);
        if (m.hasSourceFileName()) {
            wxString sourceFile = WxConversion::toWxString(m.sourceFileName());
            if (sourceFileList_->FindString(sourceFile) == -1) {
                sourceFileList_->Append(sourceFile);
            }
        }
    }
    // load first file from drop-down list and set hilights
    if (sourceFileList_->GetCount() > 0) {
        loadSourceCode(sourceFileList_->GetString(0));
        updateAnnotations();
    } else {
        ErrorDialog dialog(
            this, _T("No debugging information available."));
        dialog.ShowModal();
    }
}
References TTAProgram::Move::hasSourceFileName(), loadSourceCode(), program, sourceFileList_, TTAProgram::Move::sourceFileName(), WxConversion::toWxString(), and updateAnnotations().
Referenced by onProgramLoaded().
loadSourceCode()
void ProximDebuggerWindow::loadSourceCode (wxString sourceFile)
Loads source code into the sourceCodeText_ widget
Parameters
sourceFile Absolute file location as wxString.
Definition at line 155 of file ProximDebuggerWindow.cc.
{
    sourceCodeText_->LoadFile(sourceFile);
    currentFile_ = sourceFile;
    sourceFileList_->SetSelection(sourceFileList_->FindString(sourceFile));
}
References currentFile_, sourceCodeText_, and sourceFileList_.
Referenced by loadProgram(), and onSourceFileChoice().
onProgramLoaded()
void ProximDebuggerWindow::onProgramLoaded (const SimulatorEvent & event) private
Event handler which is called when a new program is loaded in the simulator.
Definition at line 211 of file ProximDebuggerWindow.cc.
{
    loadProgram(ProximToolbox::program());
}
References loadProgram(), and ProximToolbox::program().
onSimulationStop()
void ProximDebuggerWindow::onSimulationStop (const SimulatorEvent & event) private
Event handler which is called when simulation step ends.
Definition at line 220 of file ProximDebuggerWindow.cc.
{
    // unhilight old lines
    for (int lineNum : currentLineNums_) {
        setLineAttributes(lineNum, wxTextAttr(*wxBLACK, *wxWHITE));
    }
    currentLineNums_.clear();
    updateAnnotations();
}
References currentLineNums_, setLineAttributes(), and updateAnnotations().
onSourceFileChoice()
void ProximDebuggerWindow::onSourceFileChoice (wxCommandEvent & event) private
Event handler for drop-down list selection.
Loads selected source code from the drop-down list.
Definition at line 237 of file ProximDebuggerWindow.cc.
{
    loadSourceCode(sourceFileList_->GetString(sourceFileList_->GetSelection()));
    currentLineNums_.clear();
    updateAnnotations();
}
References currentLineNums_, loadSourceCode(), sourceFileList_, and updateAnnotations().
reset()
void ProximDebuggerWindow::reset () virtual
Resets the window when a new program or machine is being loaded in the simulator.
Reimplemented from ProximSimulatorWindow.
Definition at line 77 of file ProximDebuggerWindow.cc.
{
    sourceFileList_->Clear();
    sourceCodeText_->Clear();
    currentFile_.clear();
    currentLineNums_.clear();
}
References currentFile_, currentLineNums_, sourceCodeText_, and sourceFileList_.
setLineAttributes()
void ProximDebuggerWindow::setLineAttributes (int lineNum, wxTextAttr style)
Sets certain style attributes to the line in sourceCodeText_ widget
Parameters
lineNum Line number
style Style attributes (text color, background color, font, alignment)
Definition at line 170 of file ProximDebuggerWindow.cc.
{
    long lineStart = sourceCodeText_->XYToPosition(0, lineNum - 1);
    long lineEnd = lineStart + sourceCodeText_->GetLineLength(lineNum - 1);
    sourceCodeText_->SetStyle(lineStart, lineEnd, style);
}
References sourceCodeText_.
Referenced by highlightLine(), and onSimulationStop().
showLine()
void ProximDebuggerWindow::showLine (int lineNum)
Makes line visible in the sourceCodeText_ widget
Parameters
lineNum Source code line number.
Definition at line 202 of file ProximDebuggerWindow.cc.
{
    sourceCodeText_->ShowPosition(sourceCodeText_->XYToPosition(0,lineNum - 1));
}
References sourceCodeText_.
Referenced by updateAnnotations().
updateAnnotations()
void ProximDebuggerWindow::updateAnnotations ()
Parses possible annotations in the current instruction and hilights source code lines.
Definition at line 123 of file ProximDebuggerWindow.cc.
{
    Word pc = wxGetApp().simulation()->frontend()->programCounter();
    const TTAProgram::Instruction& instruction =
        ProximToolbox::program().instructionAt(pc);
    // check annotations and hilight possible lines
    for (int i = 0; i < instruction.moveCount(); i++) {
        const TTAProgram::Move& m = instruction.move(i);
        if (m.hasSourceLineNumber()) {
            wxString sourceFile = WxConversion::toWxString(m.sourceFileName());
            if (sourceFile == currentFile_) {
                highlightLine(m.sourceLineNumber());
            }
        }
    }
    // make last higlighted line visible
    if (currentLineNums_.size() > 0) {
        showLine(currentLineNums_.back());
    }
}
References currentFile_, currentLineNums_, TTAProgram::Move::hasSourceLineNumber(), highlightLine(), TTAProgram::Program::instructionAt(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), ProximToolbox::program(), showLine(), TTAProgram::Move::sourceFileName(), TTAProgram::Move::sourceLineNumber(), and WxConversion::toWxString().
Referenced by loadProgram(), onSimulationStop(), and onSourceFileChoice().
Member Data Documentation
currentFile_
wxString ProximDebuggerWindow::currentFile_ private
Definition at line 73 of file ProximDebuggerWindow.hh.
Referenced by loadSourceCode(), reset(), and updateAnnotations().
currentLineNums_
std::vector<int> ProximDebuggerWindow::currentLineNums_ private
Definition at line 75 of file ProximDebuggerWindow.hh.
Referenced by highlightLine(), onSimulationStop(), onSourceFileChoice(), reset(), and updateAnnotations().
sourceCodeText_
wxTextCtrl* ProximDebuggerWindow::sourceCodeText_ private
Definition at line 79 of file ProximDebuggerWindow.hh.
Referenced by createContents(), loadSourceCode(), reset(), setLineAttributes(), and showLine().
sourceFileList_
wxChoice* ProximDebuggerWindow::sourceFileList_ private
Definition at line 77 of file ProximDebuggerWindow.hh.
Referenced by createContents(), loadProgram(), loadSourceCode(), onSourceFileChoice(), and reset().
The documentation for this class was generated from the following files:
ProximDebuggerWindow.hh
ProximDebuggerWindow.cc