OpenASIP: TPEF::SymbolElement Class Reference
TPEF::SymbolElement Class Reference abstract
#include <SymbolElement.hh>
Public Types
enum SymbolBinding { STB_LOCAL = 0x0 , STB_GLOBAL = 0x1 , STB_WEAK = 0x2 }
Binding types of symbol.
enum SymbolType {
STT_NOTYPE = 0x0 , STT_DATA = 0x1 , STT_CODE = 0x2 , STT_SECTION = 0x3 ,
STT_FILE = 0x4 , STT_PROCEDURE = 0x5
}
Type of symbol element.
Public Member Functions
SymbolElement ()
virtual ~SymbolElement ()
virtual SymbolType type () const =0
Returns type of symbol.
bool absolute () const
void setAbsolute (bool anAbsoluteness)
SymbolBinding binding () const
void setBinding (SymbolBinding aBinding)
Chunk * name () const
void setName (Chunk *aName)
void setName (const ReferenceManager::SafePointer *aName)
Section * section () const
void setSection (Section *aSect)
void setSection (const ReferenceManager::SafePointer *aSect)
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
bool absolute_
Is symbol absolutely or relocating.
SymbolBinding bind_
Binding of the symbol.
const ReferenceManager::SafePointer * name_
The name of the symbol.
const ReferenceManager::SafePointer * section_
Section to which the symbol belongs.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Symbol table entry.
Definition at line 52 of file SymbolElement.hh.
Member Enumeration Documentation
SymbolBinding
enum TPEF::SymbolElement::SymbolBinding
Binding types of symbol.
Enumerator
STB_LOCAL
Not visible outside the object file that contains it's definition.
STB_GLOBAL
Visible to all files that are combined in TPEF file.
STB_WEAK
Visible to all object files that are combined in the TPEF file, but with linkage priority lower than STB_GLOBAL symbols.
Definition at line 55 of file SymbolElement.hh.
                       {
        STB_LOCAL = 0x0,  ///< Not visible outside the object file that
                          ///< contains it's definition.
        STB_GLOBAL = 0x1, ///< Visible to all files that are combined
                          ///< in TPEF file.
        STB_WEAK = 0x2    ///< Visible to all object files that are combined
                          ///< in the TPEF file, but with linkage priority
                          ///< lower than STB_GLOBAL symbols.
    };
SymbolType
enum TPEF::SymbolElement::SymbolType
Type of symbol element.
Enumerator
STT_NOTYPE
Type is not defined.
STT_DATA
Associated with data object.
STT_CODE
Associated with executable code.
STT_SECTION
Associated with section.
STT_FILE
Name of symbol gives the name of source file associated with this object file.
STT_PROCEDURE
Symbol gives indicates procedure start position in section.
Definition at line 66 of file SymbolElement.hh.
                    {
        STT_NOTYPE = 0x0, ///< Type is not defined.
        STT_DATA = 0x1,   ///< Associated with data object.
        STT_CODE = 0x2,   ///< Associated with executable code.
        STT_SECTION = 0x3,///< Associated with section.
        STT_FILE = 0x4,   ///< Name of symbol gives the name of source file
                          ///< associated with this object file.
        STT_PROCEDURE = 0x5 ///< Symbol gives indicates procedure start
                            ///< position in section
    };
Constructor & Destructor Documentation
SymbolElement()
TPEF::SymbolElement::SymbolElement ()
Constructor.
Definition at line 46 of file SymbolElement.cc.
                             :
    SectionElement(),
    absolute_(false),
    bind_(STB_LOCAL),
    name_(&SafePointer::null),
    section_(&SafePointer::null) {
}
~SymbolElement()
TPEF::SymbolElement::~SymbolElement () virtual
Destructor.
Definition at line 57 of file SymbolElement.cc.
{
}
Member Function Documentation
absolute()
bool TPEF::SymbolElement::absolute () const
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::TPEFSymbolSectionReader::readData(), and TPEFDumper::section().
binding()
SymbolBinding TPEF::SymbolElement::binding () const
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::TPEFSymbolSectionReader::readData(), and TPEFDumper::section().
name()
Chunk * TPEF::SymbolElement::name () const
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutSymbolSectionReader::finalize(), TPEFDumper::section(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), and TPEFDumper::symbolString().
section()
Section * TPEF::SymbolElement::section () const
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutSymbolSectionReader::finalize(), and TPEFDumper::section().
setAbsolute()
void TPEF::SymbolElement::setAbsolute (bool anAbsoluteness)
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::NoTypeSymElement::NoTypeSymElement(), TPEF::TPEFSymbolSectionReader::readData(), and LabelManager::writeProcedureSymbols().
setBinding()
void TPEF::SymbolElement::setBinding (SymbolBinding aBinding)
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::TPEFSymbolSectionReader::readData(), and LabelManager::writeProcedureSymbols().
setName() [1/2]
void TPEF::SymbolElement::setName (Chunk * aName)
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutSymbolSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), and LabelManager::writeProcedureSymbols().
setName() [2/2]
void TPEF::SymbolElement::setName (const ReferenceManager::SafePointer * aName)
setSection() [1/2]
void TPEF::SymbolElement::setSection (const ReferenceManager::SafePointer * aSect)
setSection() [2/2]
void TPEF::SymbolElement::setSection (Section * aSect)
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::finalize(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutSymbolSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), and LabelManager::writeProcedureSymbols().
type()
virtual SymbolType TPEF::SymbolElement::type () const pure virtual
Returns type of symbol.
Implemented in TPEF::CodeSymElement, TPEF::DataSymElement, TPEF::FileSymElement, TPEF::NoTypeSymElement, TPEF::ProcedSymElement, and TPEF::SectionSymElement.
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::TPEFSymbolSectionReader::readData(), TPEFDumper::section(), and TPEF::TPEFSymbolSectionWriter::writeValueAndSize().
Member Data Documentation
absolute_
bool TPEF::SymbolElement::absolute_ private
Is symbol absolutely or relocating.
Definition at line 99 of file SymbolElement.hh.
bind_
SymbolBinding TPEF::SymbolElement::bind_ private
Binding of the symbol.
Definition at line 101 of file SymbolElement.hh.
name_
const ReferenceManager::SafePointer* TPEF::SymbolElement::name_ private
The name of the symbol.
Definition at line 103 of file SymbolElement.hh.
section_
const ReferenceManager::SafePointer* TPEF::SymbolElement::section_ private
Section to which the symbol belongs.
Definition at line 105 of file SymbolElement.hh.
The documentation for this class was generated from the following files:
SymbolElement.hh
SymbolElement.cc