OpenASIP: RLPriorityCriticalPath Class Reference
RLPriorityCriticalPath Class Reference
#include <ReadyMoveNodeGroupList.hh>
Public Member Functions
bool operator() (MoveNodeGroup &a, MoveNodeGroup &b)
Detailed Description
A function object for prioritizing the ready list according to the move's distance from farthest sink node.
Definition at line 48 of file ReadyMoveNodeGroupList.hh.
Member Function Documentation
operator()()
bool RLPriorityCriticalPath::operator() (MoveNodeGroup & a, MoveNodeGroup & b) inline
Compares two nodes according to their priority in the ready list.
Parameters
a Node a.
b Node b.
Returns
True if b should be scheduled before a (b greater than a).
Definition at line 58 of file ReadyMoveNodeGroupList.hh.
{
        if (b.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return true;
        }
        if (a.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return false;
        }
        // Compute distances only once, it is expensive operation on graph
        int aSinkDistance = a.maxSinkDistance();
        int bSinkDistance = b.maxSinkDistance();
        if (bSinkDistance == aSinkDistance) {
            return b.node(0).nodeID() < a.node(0).nodeID();
        }
        // the higher the sink distance, the higher the priority
        return bSinkDistance > aSinkDistance;
    }
References MoveNodeGroup::isScheduled(), MoveNodeGroup::maxSinkDistance(), MoveNodeGroup::node(), and GraphNode::nodeID().
The documentation for this class was generated from the following file:
ReadyMoveNodeGroupList.hh