OpenASIP: llvm::LLVMTCEPOMBuilder Class Reference
llvm::LLVMTCEPOMBuilder Class Reference
#include <LLVMTCEPOMBuilder.hh>
Public Member Functions
LLVMTCEPOMBuilder ()
virtual ~LLVMTCEPOMBuilder ()
virtual unsigned spDRegNum () const
virtual unsigned raPortDRegNum () const
virtual TCEString registerFileName (unsigned llvmRegNum) const
virtual int registerIndex (unsigned llvmRegNum) const
virtual TCEString operationName (const MachineInstr &mi) const
virtual TTAProgram::Terminal * createFUTerminal (const MachineOperand &) const
bool doFinalization (Module &m)
bool doInitialization (Module &M)
TTAProgram::Instruction * emitMove (const MachineInstr *mi, TTAProgram::CodeSnippet *proc, bool conditional=false, bool trueGuard=true)
Public Member Functions inherited from llvm::LLVMTCEBuilder
LLVMTCEBuilder (char &ID)
LLVMTCEBuilder (const TargetMachine &tm, TTAMachine::Machine *mach, char &ID, bool functionAtATime=false)
virtual ~LLVMTCEBuilder ()
TTAProgram::Program * result ()
TTAProgram::Instruction * firstInstructionOfBasicBlock (const llvm::BasicBlock *bb)
bool isProgramUsingRestrictedPointers () const
virtual void getAnalysisUsage (AnalysisUsage &AU) const
virtual bool isTTATarget () const
void deleteDeadProcedures ()
void setInitialStackPointerValue (unsigned value)
Static Public Attributes
static char ID = 0
Static Public Attributes inherited from llvm::LLVMTCEBuilder
static char ID = 0
Additional Inherited Members
Protected Member Functions inherited from llvm::LLVMTCEBuilder
bool doInitialization (Module &M)
bool runOnMachineFunction (MachineFunction &MF)
bool doFinalization (Module &M)
bool hasAmbiguousASpaceRefs (const TTAProgram::Instruction &instr) const
virtual bool writeMachineFunction (MachineFunction &MF)
void initDataSections ()
std::shared_ptr< TTAProgram::Move > createMove (const MachineOperand &src, const MachineOperand &dst, TTAProgram::MoveGuard *guard)
const TargetMachine & targetMachine () const
TCEString registerName (unsigned llvmRegNum) const
std::string mbbName (const MachineBasicBlock &mbb)
const TTAMachine::HWOperation & getHWOperation (std::string opName)
TTAProgram::TerminalRegister * createTerminalRegister (const std::string &rfName, int index)
TTAProgram::Terminal * createTerminal (const MachineOperand &mo, int bitLimit=0)
std::shared_ptr< TTAProgram::Move > createMove (TTAProgram::Terminal *src, TTAProgram::Terminal *dst, const TTAMachine::Bus &bus, TTAProgram::MoveGuard *guard=NULL)
void emitConstantPool (const llvm::MachineConstantPool &cp)
virtual TTAProgram::Terminal * createMBBReference (const MachineOperand &mo)
virtual TTAProgram::Terminal * createSymbolReference (const MachineOperand &mo)
virtual TTAProgram::Terminal * createProgramOperationReference (const MachineOperand &mo)
virtual TTAProgram::Terminal * createSymbolReference (const TCEString &symbolName)
TTAProgram::Instruction * emitInstruction (const MachineInstr *mi, TTAProgram::CodeSnippet *proc)
TTAProgram::Instruction * emitInlineAsm (const MachineFunction &mf, const MachineInstr *mi, TTAProgram::BasicBlock *bb, TTAProgram::InstructionReferenceManager &irm)
void fixProgramOperationReferences ()
void addLabelForProgramOperation (TCEString label, ProgramOperationPtr po)
virtual void emitSPInitialization ()
void emitSPInitialization (TTAProgram::CodeSnippet &target)
void clearFunctionBookkeeping ()
Static Protected Member Functions inherited from llvm::LLVMTCEBuilder
static bool isInlineAsm (const MachineInstr &instr)
Protected Attributes inherited from llvm::LLVMTCEBuilder
std::map< std::string, TTAProgram::Instruction * > codeLabels_
Code labels.
TTAMachine::Machine * mach_
Machine for building the program.
const llvm::TargetMachine * tm_
Target machine description.
llvm::Mangler * mang_
Mangler for mangling label strings.
TTAProgram::Program * prog_
Current program being built.
std::set< std::string > opset_
The operations supported by the current target machine.
bool functionAtATime_
PRegionMarkerAnalyzer * pregions_
int spillMoveCount_
unsigned initialStackPointerValue_
MachineFrameInfo * curFrameInfo_
LLVMTCECmdLineOptions * options_ = nullptr
The compiler options.
Detailed Description
Implements building TCE POM from TTA-style (MOVE) sequential input from LLVM codegen.
Note
Experimental and still lots to do before can be considered for real use.
Definition at line 81 of file LLVMTCEPOMBuilder.hh.
Constructor & Destructor Documentation
LLVMTCEPOMBuilder()
llvm::LLVMTCEPOMBuilder::LLVMTCEPOMBuilder ()
Definition at line 67 of file LLVMTCEPOMBuilder.cc.
                                     :
    LLVMTCEBuilder(ID) {
}
~LLVMTCEPOMBuilder()
virtual llvm::LLVMTCEPOMBuilder::~LLVMTCEPOMBuilder () inline virtual
Definition at line 85 of file LLVMTCEPOMBuilder.hh.
{}
Member Function Documentation
createFUTerminal()
TTAProgram::Terminal * llvm::LLVMTCEPOMBuilder::createFUTerminal (const MachineOperand & mo) const virtual
Reimplemented from llvm::LLVMTCEBuilder.
Definition at line 131 of file LLVMTCEPOMBuilder.cc.
{
    TCEString regName(
        targetMachine().getSubtargetImpl(
            mo.getParent()->getParent()->getParent()->getFunction())->
        getRegisterInfo()->getName(mo.getReg()));
    // test for _number which indicates a RF access
    std::vector<TCEString> pieces = regName.split("_");
    if (pieces.size() == 2) {
        TCEString indexStr = pieces.at(1);
        try {
            Conversion::toInt(indexStr);
            return NULL;
        } catch (Exception&) {
        }
    }
    assert(pieces.size() > 0);
    TCEString fuName = pieces.at(0);
    TCEString portName = pieces.at(1);
    TCEString operationName = "";
    if (pieces.size() == 3) {
        // FU_triggerport_OP
        operationName = pieces.at(2);
    }
    // always assume it's the ALU of minimal.adf for now
    // should be parsed from the regName
    TTAMachine::FunctionUnit* fu =
        mach_->functionUnitNavigator().item(fuName);
    assert(fu != NULL);
    TTAMachine::FUPort* fuPort =
        dynamic_cast<TTAMachine::FUPort*>(fu->port(portName));
    assert(fuPort != NULL);
    if (operationName != "") {
        assert(fuPort->isTriggering());
        TTAMachine::HWOperation& hwOp = *fu->operation(operationName);
        return new TTAProgram::TerminalFUPort(hwOp, hwOp.io(*fuPort));
    } else {
        TTAProgram::TerminalFUPort* term =
            new TTAProgram::TerminalFUPort(*fuPort);
        return term;
    }
}
References assert, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::HWOperation::io(), TTAMachine::FUPort::isTriggering(), TTAMachine::Machine::Navigator< ComponentType >::item(), llvm::LLVMTCEBuilder::mach_, TTAMachine::FunctionUnit::operation(), operationName(), TTAMachine::FunctionUnit::port(), TCEString::split(), llvm::LLVMTCEBuilder::targetMachine(), and Conversion::toInt().
doFinalization()
bool llvm::LLVMTCEPOMBuilder::doFinalization (Module & m)
Definition at line 190 of file LLVMTCEPOMBuilder.cc.
{
    LLVMTCEBuilder::doFinalization(m);
    prog_->convertSymbolRefsToInsRefs();
    return true;
}
References TTAProgram::Program::convertSymbolRefsToInsRefs(), llvm::LLVMTCEBuilder::doFinalization(), and llvm::LLVMTCEBuilder::prog_.
doInitialization()
bool llvm::LLVMTCEPOMBuilder::doInitialization (Module & M)
Definition at line 184 of file LLVMTCEPOMBuilder.cc.
{
    mach_ = TTAMachine::Machine::loadFromADF("tta/4bus_minimal.adf");
    return LLVMTCEBuilder::doInitialization(M);
}
References llvm::LLVMTCEBuilder::doInitialization(), TTAMachine::Machine::loadFromADF(), and llvm::LLVMTCEBuilder::mach_.
emitMove()
TTAProgram::Instruction * llvm::LLVMTCEPOMBuilder::emitMove (const MachineInstr * mi, TTAProgram::CodeSnippet * proc, bool conditional = false, bool trueGuard = true) virtual
Creates POM instruction for a move.
Parameters
mi Move machine instruction.
proc POM procedure to add the move to.
Returns
Emitted POM instruction.
Reimplemented from llvm::LLVMTCEBuilder.
Definition at line 98 of file LLVMTCEPOMBuilder.cc.
                {
    TCEString opName(targetMachine().getSubtargetImpl(
                         mi->getParent()->getParent()->getFunction())->
                     getInstrInfo()->getName(mi->getOpcode()).str());
    /* Non-trigger move. */
    if (opName == "MOVE")
        return LLVMTCEBuilder::emitMove(mi, proc);
    /* A trigger move. The source is the 2nd last argument. */
    TTAProgram::Terminal* src =
        createTerminal(mi->getOperand(mi->getNumOperands() - 2));
    TTAProgram::Terminal* dst = /* defined as implicit def */
        createTerminal(mi->getOperand(mi->getNumOperands() - 1));
    TTAMachine::Bus& bus = result()->universalMachine().universalBus();
    auto move = createMove(src, dst, bus);
    TTAProgram::Instruction* instr = new TTAProgram::Instruction();
    instr->addMove(move);
    proc->add(instr);
    return instr;
}
References TTAProgram::CodeSnippet::add(), TTAProgram::Instruction::addMove(), llvm::LLVMTCEBuilder::createMove(), llvm::LLVMTCEBuilder::createTerminal(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEBuilder::result(), llvm::LLVMTCEBuilder::targetMachine(), UniversalMachine::universalBus(), and TTAProgram::Program::universalMachine().
operationName()
TCEString llvm::LLVMTCEPOMBuilder::operationName (const MachineInstr & mi) const virtual
Implements llvm::LLVMTCEBuilder.
Definition at line 126 of file LLVMTCEPOMBuilder.cc.
{
    return "MOVE";
}
Referenced by createFUTerminal().
raPortDRegNum()
unsigned llvm::LLVMTCEPOMBuilder::raPortDRegNum () const virtual
Implements llvm::LLVMTCEBuilder.
Definition at line 77 of file LLVMTCEPOMBuilder.cc.
{
    return 1000001; // ;D
}
registerFileName()
TCEString llvm::LLVMTCEPOMBuilder::registerFileName (unsigned llvmRegNum) const virtual
Implements llvm::LLVMTCEBuilder.
Definition at line 82 of file LLVMTCEPOMBuilder.cc.
{
    if (llvmRegNum == 1000000)
        return "RF"; /* temp hack, always assume SP is the RF.4 */
    abortWithError("Unimplemented.");
}
References abortWithError.
registerIndex()
int llvm::LLVMTCEPOMBuilder::registerIndex (unsigned llvmRegNum) const virtual
Implements llvm::LLVMTCEBuilder.
Definition at line 90 of file LLVMTCEPOMBuilder.cc.
{
    if (llvmRegNum == 1000000)
        return 4; /* temp hack, always assume SP is the RF.4 */
    abortWithError("Unimplemented.");
}
References abortWithError.
spDRegNum()
unsigned llvm::LLVMTCEPOMBuilder::spDRegNum () const virtual
Implements llvm::LLVMTCEBuilder.
Definition at line 72 of file LLVMTCEPOMBuilder.cc.
{
    return 1000000; // ;)
}
Member Data Documentation
ID
char llvm::LLVMTCEPOMBuilder::ID = 0 static
Definition at line 83 of file LLVMTCEPOMBuilder.hh.
The documentation for this class was generated from the following files:
LLVMTCEPOMBuilder.hh
LLVMTCEPOMBuilder.cc