OpenASIP: CompiledSimSettingCommand Class Reference
CompiledSimSettingCommand Class Reference
#include <CompiledSimSettingCommand.hh>
Public Member Functions
CompiledSimSettingCommand ()
virtual ~CompiledSimSettingCommand ()
Public Member Functions inherited from SettingCommand
SettingCommand ()
virtual ~SettingCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Types inherited from SettingCommand
typedef std::map< std::string, SimulatorSetting * > SettingMap
container for simulator settings indexed by name
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Protected Attributes inherited from SettingCommand
SettingMap settings_
storage for simulator settings
Detailed Description
Implementation of the "setting" command for the compiled simulator
Definition at line 41 of file CompiledSimSettingCommand.hh.
Constructor & Destructor Documentation
CompiledSimSettingCommand()
CompiledSimSettingCommand::CompiledSimSettingCommand ()
Default constructor
Definition at line 79 of file CompiledSimSettingCommand.cc.
                                                     :
    SettingCommand() {
    // Remove unsupported settings
    MapTools::deleteByKey(settings_, "rf_tracking");
    MapTools::deleteByKey(settings_, "bus_trace");
    MapTools::deleteByKey(settings_, "profile_data_saving");
    MapTools::deleteByKey(settings_, "utilization_data_saving");
    // Replace FU conflict detection setting
    MapTools::deleteByKey(settings_, "fu_conflict_detection");
    settings_["fu_conflict_detection"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, CompiledSimSetFUConflictDetection>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_FU_CONFLICT_DETECTION).str());
}
References MapTools::deleteByKey(), SettingCommand::settings_, Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_SETTING_FU_CONFLICT_DETECTION.
~CompiledSimSettingCommand()
CompiledSimSettingCommand::~CompiledSimSettingCommand () virtual
Default destructor
Definition at line 100 of file CompiledSimSettingCommand.cc.
{
}
The documentation for this class was generated from the following files:
CompiledSimSettingCommand.hh
CompiledSimSettingCommand.cc