OpenASIP: RootEditPart Class Reference
RootEditPart Class Reference
#include <RootEditPart.hh>
Public Member Functions
RootEditPart ()
virtual ~RootEditPart ()
EditPart * contents () const
void setContents (EditPart *contents)
Public Member Functions inherited from EditPart
EditPart ()
virtual ~EditPart ()
void putGarbage (std::set< EditPart * > &trashbag)
EditPart * parent () const
void setParent (EditPart *parent)
TTAMachine::MachinePart * model () const
void setModel (TTAMachine::MachinePart *model)
Figure * figure () const
void setFigure (Figure *figure)
EditPart * find (wxPoint point)
EditPart * find (const TTAMachine::MachinePart *model)
EditPart * findNearest (wxPoint point, const EditPart *exclude=NULL)
int findInRange (wxPoint point, float radius, std::vector< EditPart * > &found)
bool hasEditPartRecursive (const EditPart *part) const
bool selectable () const
bool selected () const
void setSelectable (bool selectable)
void setSelected (bool select)
void installEditPolicy (EditPolicy *editpolicy)
void addChild (EditPart *child)
int childCount () const
EditPart * child (unsigned int index) const
ComponentCommand * performRequest (Request *request) const
bool canHandle (Request *request) const
Private Member Functions
RootEditPart & operator= (RootEditPart &old)
Assignment not allowed.
RootEditPart (RootEditPart &old)
Copying not allowed.
void collectTrash ()
Private Attributes
EditPart * contents_
Contents EditPart which parents all EditParts in the View.
Additional Inherited Members
Protected Attributes inherited from EditPart
EditPart * parent_
Parent of this EditPart.
Figure * figure_
Figure of this EditPart.
TTAMachine::MachinePart * model_
Machine component corresponding to this EditPart.
bool selectable_
Tells whether the EditPart is selectable or not.
bool selected_
Tells whether the EditPart is selected or not.
bool garbageCollected_
Helper member to prevent improper deletion.
std::vector< EditPolicy * > editPolicies_
List of supported EditPolicies.
std::vector< EditPart * > children_
List of children EditParts.
Detailed Description
The root EditPart of the whole processor view.
Contains contents EditPart.
Definition at line 44 of file RootEditPart.hh.
Constructor & Destructor Documentation
RootEditPart() [1/2]
RootEditPart::RootEditPart ()
The Constructor.
Definition at line 45 of file RootEditPart.cc.
                          : EditPart(), contents_(NULL) {
}
~RootEditPart()
RootEditPart::~RootEditPart () virtual
The Destructor.
Collects garbage from the contents EditPart and deletes it all.
Definition at line 53 of file RootEditPart.cc.
{
    collectTrash();
}
References collectTrash().
RootEditPart() [2/2]
RootEditPart::RootEditPart (RootEditPart & old) private
Copying not allowed.
Member Function Documentation
collectTrash()
void RootEditPart::collectTrash () private
Collects trash from the contents EditPart and deletes it.
Definition at line 73 of file RootEditPart.cc.
{
    if (contents_ != NULL) {
    set<EditPart*> trashbag;
    contents_->putGarbage(trashbag);
    for (set<EditPart*>::iterator i = trashbag.begin();
         i != trashbag.end(); i++) {
        delete *i;
    }
    }
    garbageCollected_ = true;
}
References contents_, EditPart::garbageCollected_, and EditPart::putGarbage().
Referenced by setContents(), and ~RootEditPart().
contents()
EditPart * RootEditPart::contents () const
Referenced by MachineCanvas::clearHighlights(), MachineCanvas::findEditPart(), MachineCanvas::findEditPart(), MachineCanvas::findEditPartsInRange(), MachineCanvas::getFigureSize(), MachineCanvas::hasEditPart(), MachineCanvas::highlight(), MachineCanvas::OnDraw(), and setContents().
operator=()
RootEditPart & RootEditPart::operator= (RootEditPart & old) private
Assignment not allowed.
setContents()
void RootEditPart::setContents (EditPart * contents)
Sets the contents EditPart of the whole view.
Parameters
contents The new contents EditPart.
Definition at line 63 of file RootEditPart.cc.
{
    collectTrash();
    contents_ = contents;
    garbageCollected_ = false;
}
References collectTrash(), contents(), contents_, and EditPart::garbageCollected_.
Referenced by MachineCanvas::updateMachine().
Member Data Documentation
contents_
EditPart* RootEditPart::contents_ private
Contents EditPart which parents all EditParts in the View.
Definition at line 60 of file RootEditPart.hh.
Referenced by collectTrash(), and setContents().
The documentation for this class was generated from the following files:
RootEditPart.hh
RootEditPart.cc