OpenASIP: Assembler Class Reference
Assembler Class Reference
#include <Assembler.hh>
Public Member Functions
Assembler (TPEF::BinaryStream &assemblerFile, TTAMachine::Machine &assemblerMachine)
TPEF::Binary * compile ()
const std::set< CompilerMessage > & warnings () const
const CompilerMessage & error () const
void addWarning (UValue lineNumber, std::string errorMessage)
const TTAMachine::Machine & targetMachine () const
Private Member Functions
void readAssemblerCode ()
std::string codeLine (UValue lineNumber) const
Private Attributes
TPEF::BinaryStream & stream_
File containing file to assemble.
TTAMachine::Machine * mach_
Machine for assembled TPEF.
CompilerMessage error_
Last thrown error message.
AssemblyParserDiagnostic parserDiagnostic_
Parser messages.
std::shared_ptr< std::string > asmCode_
String containing code to compile.
Detailed Description
TCE Assembler user interface.
Definition at line 55 of file Assembler.hh.
Constructor & Destructor Documentation
Assembler()
Assembler::Assembler (TPEF::BinaryStream & assemblerFile, TTAMachine::Machine & assemblerMachine)
Constructor.
Parameters
assemblerFile Stream containing file to assemble.
assemblerMachine Machine to use for running compiled binary.
Definition at line 55 of file Assembler.cc.
                               :
    stream_(assemblerFile), mach_(&assemblerMachine) {
}
Member Function Documentation
addWarning()
void Assembler::addWarning (UValue lineNumber, std::string errorMessage)
Adds warning message for client to see.
Parameters
lineNumber Line number of assembly code, where error accured.
errorMessage Warning message.
Definition at line 140 of file Assembler.cc.
{
    parserDiagnostic_.addWarning(lineNumber, errorMessage);
}
References AssemblyParserDiagnostic::addWarning(), and parserDiagnostic_.
codeLine()
std::string Assembler::codeLine (UValue lineNumber) const private
Definition at line 196 of file Assembler.cc.
{
    return parserDiagnostic_.codeLine(lineNumber);
}
References AssemblyParserDiagnostic::codeLine(), and parserDiagnostic_.
Referenced by compile().
compile()
Binary * Assembler::compile ()
Compiles assembler and returns TPEF hierarchy.
Returns
Compiled TPEF.
Exceptions
CompileError If there was any problems during the compilation.
Definition at line 68 of file Assembler.cc.
                   {
    // read binary stream to string
    readAssemblerCode();
    // clear old warnings from previous compilation
    parserDiagnostic_.reset(asmCode_);
    Binary* newBinary = new Binary();
    // this one does the actual parsing work
    AssemblerParser parser(*newBinary, *mach_, &parserDiagnostic_);
    try {
        try {
            if (!parser.compile(*asmCode_)) {
                CompileError error(
                    __FILE__, __LINE__, __func__, "Syntax error.");
                error.setCodeFileLineNumber(parser.errorLine());
                throw error;
            }
        // ObjectAllreadyExists and IllegalMachine exceptions.
        } catch (Exception& e) {
            CompileError error(
                __FILE__, __LINE__, __func__, e.errorMessage());
            error.setCause(e);
            error.setCodeFileLineNumber(parser.errorLine());
            throw error;
        }
        parser.finalize(mach_->isLittleEndian());
    } catch (CompileError& e) {
        error_.lineNumber = e.codeFileLineNumber();
        error_.assemblerLine = codeLine(e.codeFileLineNumber());
        error_.message = e.errorMessage();
        // clean up internals of creators and managers and delete
        // partial binary
        parser.cleanup();
        delete newBinary;
        newBinary = NULL;
        CompileError error(
            __FILE__, __LINE__, __func__,
            "Error in line " + Conversion::toString(error_.lineNumber) +
            ": " + error_.assemblerLine + "\nMessage: " + error_.message);
        error.setCause(e);
        error.setCodeFileLineNumber(error_.lineNumber);
        throw error;
    }
    return newBinary;
}
References __func__, asmCode_, CompilerMessage::assemblerLine, AssemblerParser::cleanup(), CompileError::codeFileLineNumber(), codeLine(), AssemblerParser::compile(), error(), error_, AssemblerParser::errorLine(), Exception::errorMessage(), AssemblerParser::finalize(), TTAMachine::Machine::isLittleEndian(), CompilerMessage::lineNumber, mach_, CompilerMessage::message, parserDiagnostic_, readAssemblerCode(), AssemblyParserDiagnostic::reset(), and Conversion::toString().
Referenced by main().
error()
const CompilerMessage & Assembler::error () const
Returns last thrown error message..
Returns
Error that halted compilation.
Definition at line 165 of file Assembler.cc.
                       {
    return error_;
}
References error_.
Referenced by compile().
readAssemblerCode()
void Assembler::readAssemblerCode () private
Reads assembly code from binary stream to a string.
Definition at line 173 of file Assembler.cc.
{
    unsigned int streamPosition = stream_.readPosition();
    asmCode_ = std::make_shared<std::string>();
    // read file to string and mark line start indexes.
    for (unsigned int i = streamPosition; i < stream_.sizeOfFile(); i++) {
        Byte readByte = stream_.readByte();
        *asmCode_ += readByte;
    }
    // restore stream position...
    stream_.setReadPosition(streamPosition);
}
References asmCode_, TPEF::BinaryStream::readByte(), TPEF::BinaryStream::readPosition(), TPEF::BinaryStream::setReadPosition(), TPEF::BinaryStream::sizeOfFile(), and stream_.
Referenced by compile().
targetMachine()
const TTAMachine::Machine & Assembler::targetMachine () const
Returns the target machine of the assembler.
Returns
The target machine.
Definition at line 150 of file Assembler.cc.
{
    return *mach_;
}
References mach_.
warnings()
const std::set< CompilerMessage > & Assembler::warnings () const
Definition at line 155 of file Assembler.cc.
{
    return parserDiagnostic_.warnings();
}
References parserDiagnostic_, and AssemblyParserDiagnostic::warnings().
Referenced by main().
Member Data Documentation
asmCode_
std::shared_ptr<std::string> Assembler::asmCode_ private
String containing code to compile.
Definition at line 89 of file Assembler.hh.
Referenced by compile(), and readAssemblerCode().
error_
CompilerMessage Assembler::error_ private
Last thrown error message.
Definition at line 83 of file Assembler.hh.
Referenced by compile(), and error().
mach_
TTAMachine::Machine* Assembler::mach_ private
Machine for assembled TPEF.
Definition at line 80 of file Assembler.hh.
Referenced by compile(), and targetMachine().
parserDiagnostic_
AssemblyParserDiagnostic Assembler::parserDiagnostic_ private
Parser messages.
Definition at line 86 of file Assembler.hh.
Referenced by addWarning(), codeLine(), compile(), and warnings().
stream_
TPEF::BinaryStream& Assembler::stream_ private
File containing file to assemble.
Definition at line 77 of file Assembler.hh.
Referenced by readAssemblerCode().
The documentation for this class was generated from the following files:
Assembler.hh
Assembler.cc