OpenASIP: CostFunctionPluginDialog Class Reference
CostFunctionPluginDialog Class Reference
#include <CostFunctionPluginDialog.hh>
Public Member Functions
CostFunctionPluginDialog (wxWindow *parent, wxWindowID id, HDB::HDBManager &hdb, int pluginID)
virtual ~CostFunctionPluginDialog ()
Private Types
enum {
ID_LIST = 10000 , ID_NAME , ID_PATH , ID_TYPE ,
ID_BROWSE , ID_DESCRIPTION , ID_ADD , ID_MODIFY ,
ID_DELETE , ID_TEXT , ID_LINE
}
Widget ids.
Private Member Functions
virtual bool TransferDataToWindow ()
void onBrowse (wxCommandEvent &event)
void onAdd (wxCommandEvent &event)
void onModify (wxCommandEvent &event)
void onDelete (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onDataSelection (wxListEvent &event)
int selectedData ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
wxListCtrl * list_
Pointer to the data list widget.
HDB::HDBManager & hdb_
HDB containing the plugin.
int id_
Plugin id in the HDB.
wxString name_
Plugin name.
wxString path_
Plugin file path.
wxString description_
Plugin description string.
wxChoice * typeChoice_
Pointer to the type choice widget.
Static Private Attributes
static const wxString TYPE_COST_FU
FU Cost estimator string for the type choicer widget.
static const wxString TYPE_COST_RF
RF Cost estimator string for the type choicer widget.
static const wxString TYPE_COST_DECOMP
Decompressor cost estimator string for the type choicer widget.
static const wxString TYPE_COST_ICDEC
IC&decoder Cost estimator string for the type choicer widget.
Detailed Description
Dialog for modifying CostFunctionPlugins.
Definition at line 46 of file CostFunctionPluginDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_LIST
ID_NAME
ID_PATH
ID_TYPE
ID_BROWSE
ID_DESCRIPTION
ID_ADD
ID_MODIFY
ID_DELETE
ID_TEXT
ID_LINE
Definition at line 92 of file CostFunctionPluginDialog.hh.
         {
        ID_LIST = 10000,
        ID_NAME,
        ID_PATH,
        ID_TYPE,
        ID_BROWSE,
        ID_DESCRIPTION,
        ID_ADD,
        ID_MODIFY,
        ID_DELETE,
        ID_TEXT,
        ID_LINE
    };
Constructor & Destructor Documentation
CostFunctionPluginDialog()
CostFunctionPluginDialog::CostFunctionPluginDialog (wxWindow * parent, wxWindowID id, HDB::HDBManager & hdb, int pluginID)
The Constructor.
Parameters
parent Parent window of the dialog.
id Dialog window ID.
hdb HDB containing the cost function plugin.
pluginID Row ID of the plugin in the HDB.
Definition at line 79 of file CostFunctionPluginDialog.cc.
                                                                       :
    wxDialog(parent, id, _T("Cost Function Plugin")),
    hdb_(hdb), id_(pluginID) {
    createContents(this, true, true);
    list_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    typeChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_TYPE));
    list_->InsertColumn(0, _T("Type"), wxLIST_FORMAT_LEFT, 50);
    list_->InsertColumn(1, _T("ID"), wxLIST_FORMAT_LEFT, 50);
    list_->InsertColumn(2, _T("Name"), wxLIST_FORMAT_LEFT, 200);
    list_->InsertColumn(3, _T("Data"), wxLIST_FORMAT_RIGHT, 200);
    typeChoice_->Append(TYPE_COST_RF);
    typeChoice_->Append(TYPE_COST_FU);
    typeChoice_->Append(TYPE_COST_DECOMP);
    typeChoice_->Append(TYPE_COST_ICDEC);
    FindWindow(ID_NAME)->SetValidator(wxGenericValidator(&name_));
    FindWindow(ID_PATH)->SetValidator(wxGenericValidator(&path_));
    FindWindow(
        ID_DESCRIPTION)->SetValidator(wxGenericValidator(&description_));
    const CostFunctionPlugin* plugin = hdb_.costFunctionPluginByID(id_);
    name_ = WxConversion::toWxString(plugin->name());
    path_ = WxConversion::toWxString(plugin->pluginFilePath());
    description_ = WxConversion::toWxString(plugin->description());
    if (plugin->type() == CostFunctionPlugin::COST_FU) {
        typeChoice_->SetStringSelection(TYPE_COST_FU);
    } else if (plugin->type() == CostFunctionPlugin::COST_RF) {
        typeChoice_->SetStringSelection(TYPE_COST_RF);
    } else if (plugin->type() == CostFunctionPlugin::COST_DECOMP) {
        typeChoice_->SetStringSelection(TYPE_COST_DECOMP);
    } else if (plugin->type() == CostFunctionPlugin::COST_ICDEC) {
        typeChoice_->SetStringSelection(TYPE_COST_ICDEC);
    }
    delete plugin;
    FindWindow(ID_DELETE)->Disable();
    FindWindow(ID_MODIFY)->Disable();
}
References HDB::CostFunctionPlugin::COST_DECOMP, HDB::CostFunctionPlugin::COST_FU, HDB::CostFunctionPlugin::COST_ICDEC, HDB::CostFunctionPlugin::COST_RF, HDB::CostFunctionPlugin::description(), HDB::CostFunctionPlugin::name(), HDB::CostFunctionPlugin::pluginFilePath(), WxConversion::toWxString(), and HDB::CostFunctionPlugin::type().
~CostFunctionPluginDialog()
CostFunctionPluginDialog::~CostFunctionPluginDialog () virtual
y * The Destructor.
Definition at line 128 of file CostFunctionPluginDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * CostFunctionPluginDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Parameters
parent Parent window of the dialog widgets.
Definition at line 302 of file CostFunctionPluginDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 3, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(300,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_TEXT, wxT("Plugin file path:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_PATH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, ID_BROWSE, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_TEXT, wxT("Plugin type:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item7, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs8 = (wxString*) NULL;
    wxChoice *item8 = new wxChoice( parent, ID_TYPE, wxDefaultPosition, wxSize(100,-1), 0, strs8, 0 );
    item1->Add( item8, 0, wxGROW|wxALL, 5 );
    item1->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("Description:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item9, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_DESCRIPTION, wxT(""), wxDefaultPosition, wxSize(200,60), wxTE_MULTILINE );
    item1->Add( item10, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("Plugin data:") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );
    wxListCtrl *item13 = new wxListCtrl( parent, ID_LIST, wxDefaultPosition, wxSize(500,300), wxLC_REPORT|wxSUNKEN_BORDER );
    item11->Add( item13, 0, wxGROW|wxALL, 5 );
    item0->Add( item11, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item15 = new wxButton( parent, ID_ADD, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item16 = new wxButton( parent, ID_MODIFY, wxT("Modify..."), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item17 = new wxButton( parent, ID_DELETE, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item14, 0, wxALIGN_CENTER, 5 );
    wxStaticLine *item18 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item18, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item20 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item21 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item21, 0, wxALL, 5 );
    item0->Add( item19, 0, 0, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD, ID_BROWSE, ID_DELETE, ID_DESCRIPTION, ID_LINE, ID_LIST, ID_MODIFY, ID_NAME, ID_PATH, ID_TEXT, and ID_TYPE.
onAdd()
void CostFunctionPluginDialog::onAdd (wxCommandEvent & event) private
Event handler for the add button.
Definition at line 224 of file CostFunctionPluginDialog.cc.
{
    TransferDataFromWindow();
    CostEstimationDataDialog dialog(this, -1, hdb_, id_, -1);
    dialog.ShowModal();
    TransferDataFromWindow();
    TransferDataToWindow();
}
References hdb_, id_, and TransferDataToWindow().
onBrowse()
void CostFunctionPluginDialog::onBrowse (wxCommandEvent & event) private
Event handler for the browse plugin file path button.
Definition at line 210 of file CostFunctionPluginDialog.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a plugin file."), _T(""), _T(""),
        _T("Plugin files (*.so)|*.so|All Files|*.*"),
        wxOPEN | wxFILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK) {
        dynamic_cast<wxTextCtrl*>(
            FindWindow(ID_PATH))->SetValue(dialog.GetPath());
    }
}
References ID_PATH.
onDataSelection()
void CostFunctionPluginDialog::onDataSelection (wxListEvent & event) private
Event handler for the plugin data list selection changes.
Updates the delete and modify button enabled/disabled states.
Definition at line 196 of file CostFunctionPluginDialog.cc.
{
    if (selectedData() == -1) {
        FindWindow(ID_DELETE)->Disable();
        FindWindow(ID_MODIFY)->Disable();
    } else {
        FindWindow(ID_DELETE)->Enable();
        FindWindow(ID_MODIFY)->Enable();
    }
}
References ID_DELETE, ID_MODIFY, and selectedData().
onDelete()
void CostFunctionPluginDialog::onDelete (wxCommandEvent & event) private
Event handler for the Delete button.
Definition at line 251 of file CostFunctionPluginDialog.cc.
{
    TransferDataFromWindow();
    int selected = selectedData();
    if (selected >= 0) {
        hdb_.removeCostEstimationData(selected);
        TransferDataToWindow();
    }
}
References hdb_, HDB::HDBManager::removeCostEstimationData(), selectedData(), and TransferDataToWindow().
onModify()
void CostFunctionPluginDialog::onModify (wxCommandEvent & event) private
Event handler for the modify button.
Definition at line 237 of file CostFunctionPluginDialog.cc.
{
    TransferDataFromWindow();
    int selected = selectedData();
    if (selected >= 0) {
        CostEstimationDataDialog dialog(this, -1, hdb_, id_, selected);
        dialog.ShowModal();
        TransferDataToWindow();
    }
}
References hdb_, id_, selectedData(), and TransferDataToWindow().
onOK()
void CostFunctionPluginDialog::onOK (wxCommandEvent & event) private
Event handler for the Close button.
Definition at line 264 of file CostFunctionPluginDialog.cc.
{
    TransferDataFromWindow();
     if (name_.IsEmpty()) {
             wxString message(_T("Plugin name not set."));
             ErrorDialog dialog(this, message);
             dialog.ShowModal();
             return;
     }
    CostFunctionPlugin::CostFunctionPluginType type =
        CostFunctionPlugin::COST_FU;
    if (typeChoice_->GetStringSelection() == TYPE_COST_RF) {
        type = CostFunctionPlugin::COST_RF;
    } else if (typeChoice_->GetStringSelection() == TYPE_COST_DECOMP) {
        type = CostFunctionPlugin::COST_DECOMP;
    } else if (typeChoice_->GetStringSelection() == TYPE_COST_ICDEC) {
        type = CostFunctionPlugin::COST_ICDEC;
    } else {
        assert(typeChoice_->GetStringSelection() == TYPE_COST_FU);
    }
    std::string description = WxConversion::toString(description_);
    std::string name = WxConversion::toString(name_);
    std::string path = WxConversion::toString(path_);
    CostFunctionPlugin modified(-1, description, name, path, type);
    hdb_.modifyCostFunctionPlugin(id_, modified);
    EndModal(wxID_OK);
}
References assert, HDB::CostFunctionPlugin::COST_DECOMP, HDB::CostFunctionPlugin::COST_FU, HDB::CostFunctionPlugin::COST_ICDEC, HDB::CostFunctionPlugin::COST_RF, description_, hdb_, id_, HDB::HDBManager::modifyCostFunctionPlugin(), name_, path_, WxConversion::toString(), TYPE_COST_DECOMP, TYPE_COST_FU, TYPE_COST_ICDEC, TYPE_COST_RF, and typeChoice_.
selectedData()
int CostFunctionPluginDialog::selectedData () private
Returns RowID of the cost estimation data selected in the list.
Returns -1 if no data is selected.
Returns
RowID of the selected cost estiamtion data.
Definition at line 180 of file CostFunctionPluginDialog.cc.
{
    int item = list_->GetNextItem(-1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item < 0) {
        return -1;
    }
    return list_->GetItemData(item);
}
References list_.
Referenced by onDataSelection(), onDelete(), and onModify().
TransferDataToWindow()
bool CostFunctionPluginDialog::TransferDataToWindow () private virtual
Transfers data to the dilaog widgets.
Definition at line 135 of file CostFunctionPluginDialog.cc.
{
    list_->DeleteAllItems();
    // Plugin cost estimation data.
    const std::set<RowID> pluginDataIDs = hdb_.costFunctionPluginDataIDs(id_);
    std::set<RowID>::const_iterator iter = pluginDataIDs.begin();
    for (; iter != pluginDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        if (data.hasFUReference()) {
            list_->InsertItem(0, _T("FU"));
            list_->SetItem(0, 1, WxConversion::toWxString(data.fuReference()));
        } else if (data.hasRFReference()) {
            list_->InsertItem(0, _T("RF"));
            list_->SetItem(0, 1, WxConversion::toWxString(data.rfReference()));
        } else if (data.hasBusReference()) {
            list_->InsertItem(0, _T("Bus"));
            list_->SetItem(
                0, 1, WxConversion::toWxString(data.busReference()));
        } else if (data.hasSocketReference()) {
            list_->InsertItem(0, _T("Socket"));
            list_->SetItem(
                0, 1, WxConversion::toWxString(data.socketReference()));
        } else {
            list_->InsertItem(0, _T("-"));
            list_->SetItem(0, 1, _T("-"));
        }
        list_->SetItem(0, 2, WxConversion::toWxString(data.name()));
        list_->SetItem(
            0, 3, WxConversion::toWxString(data.value().stringValue()));
        list_->SetItemData(0, *iter);
    }
    return wxDialog::TransferDataToWindow();
}
References CostEstimationData::busReference(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::costFunctionPluginDataIDs(), CostEstimationData::fuReference(), CostEstimationData::hasBusReference(), CostEstimationData::hasFUReference(), CostEstimationData::hasRFReference(), CostEstimationData::hasSocketReference(), hdb_, id_, list_, CostEstimationData::name(), CostEstimationData::rfReference(), CostEstimationData::socketReference(), DataObject::stringValue(), WxConversion::toWxString(), and CostEstimationData::value().
Referenced by onAdd(), onDelete(), and onModify().
Member Data Documentation
description_
wxString CostFunctionPluginDialog::description_ private
Plugin description string.
Definition at line 77 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
hdb_
HDB::HDBManager& CostFunctionPluginDialog::hdb_ private
HDB containing the plugin.
Definition at line 69 of file CostFunctionPluginDialog.hh.
Referenced by onAdd(), onDelete(), onModify(), onOK(), and TransferDataToWindow().
id_
int CostFunctionPluginDialog::id_ private
Plugin id in the HDB.
Definition at line 71 of file CostFunctionPluginDialog.hh.
Referenced by onAdd(), onModify(), onOK(), and TransferDataToWindow().
list_
wxListCtrl* CostFunctionPluginDialog::list_ private
Pointer to the data list widget.
Definition at line 66 of file CostFunctionPluginDialog.hh.
Referenced by selectedData(), and TransferDataToWindow().
name_
wxString CostFunctionPluginDialog::name_ private
Plugin name.
Definition at line 73 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
path_
wxString CostFunctionPluginDialog::path_ private
Plugin file path.
Definition at line 75 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
TYPE_COST_DECOMP
const wxString CostFunctionPluginDialog::TYPE_COST_DECOMP static private
Initial value:
=
    _T("Decompressor Cost Estimator")
Decompressor cost estimator string for the type choicer widget.
Definition at line 87 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
TYPE_COST_FU
const wxString CostFunctionPluginDialog::TYPE_COST_FU static private
Initial value:
=
    _T("FU Cost Estimator")
FU Cost estimator string for the type choicer widget.
Definition at line 83 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
TYPE_COST_ICDEC
const wxString CostFunctionPluginDialog::TYPE_COST_ICDEC static private
Initial value:
=
    _T("IC & Decoder Cost Estimator")
IC&decoder Cost estimator string for the type choicer widget.
Definition at line 89 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
TYPE_COST_RF
const wxString CostFunctionPluginDialog::TYPE_COST_RF static private
Initial value:
=
    _T("RF Cost Estimator")
RF Cost estimator string for the type choicer widget.
Definition at line 85 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
typeChoice_
wxChoice* CostFunctionPluginDialog::typeChoice_ private
Pointer to the type choice widget.
Definition at line 80 of file CostFunctionPluginDialog.hh.
Referenced by onOK().
The documentation for this class was generated from the following files:
CostFunctionPluginDialog.hh
CostFunctionPluginDialog.cc