OpenASIP: TTAProgram::TerminalRegister Class Reference
TTAProgram::TerminalRegister Class Reference
#include <TerminalRegister.hh>
Public Member Functions
TerminalRegister (const TTAMachine::Port &port, int index)
virtual ~TerminalRegister ()
Copying is allowed.
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isUniversalMachineRegister () const
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual int index () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isImmediate () const
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual SimValue value () const
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Private Member Functions
TerminalRegister & operator= (const TerminalRegister &)
Assignment not allowed.
Private Attributes
const TTAMachine::Unit & unit_
Unit of the terminal.
const TTAMachine::Port & port_
Port of the unit.
short index_
Index of the register of the register file or immediate unit.
bool isImmUnit_
Unit type flag: true if immediate unit, false if register file.
Detailed Description
Represents a reference to registers from general-purpose register files and immediate units.
These types of terminals are characterised by the fact that multiple, functionally identical registers are accessed through the same port. Registers are identified by an index.
Definition at line 53 of file TerminalRegister.hh.
Constructor & Destructor Documentation
TerminalRegister()
TTAProgram::TerminalRegister::TerminalRegister (const TTAMachine::Port & port, int index)
The constructor.
Parameters
unit The register file.
port The port of the register file.
index Register identifier.
Definition at line 50 of file TerminalRegister.cc.
    : unit_(*port.parentUnit()), port_(port), index_(index), isImmUnit_(false) {
    if (dynamic_cast<const ImmediateUnit*>(&unit_) != NULL) {
        isImmUnit_ = true;
    } else if (dynamic_cast<const RegisterFile*>(&unit_) == NULL) {
        throw InvalidData(
            __FILE__, __LINE__, "TerminalRegister::TerminalRegister()",
            "Unit of the terminal has invalid type");
    }
}
References isImmUnit_, and unit_.
~TerminalRegister()
TTAProgram::TerminalRegister::~TerminalRegister () virtual
Copying is allowed.
The destructor.
Definition at line 64 of file TerminalRegister.cc.
{
}
Member Function Documentation
copy()
Terminal * TTAProgram::TerminalRegister::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Implements TTAProgram::Terminal.
Definition at line 147 of file TerminalRegister.cc.
{
    return new TerminalRegister(port_, index_);
}
References index_, and port_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), and RegisterCopyAdder::addConnectionRegisterCopiesImmediate().
equals()
bool TTAProgram::TerminalRegister::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Implements TTAProgram::Terminal.
Definition at line 158 of file TerminalRegister.cc.
{
    try {
        if (isImmediateRegister()) {
            return (other.isImmediateRegister() &&
                index() == other.index() &&
                immediateUnit().name() == other.immediateUnit().name());
        }
        if (isGPR()) {
            return (other.isGPR() &&
                index() == other.index() &&
                registerFile().name() == other.registerFile().name());
        }
    return false;
    } catch (const WrongSubclass&) {
        // the method should throw this when called for wrong type,
        // thus the objects cannot be equal
        return false;
    }
}
References TTAProgram::Terminal::immediateUnit(), immediateUnit(), TTAProgram::Terminal::index(), index(), TTAProgram::Terminal::isGPR(), isGPR(), TTAProgram::Terminal::isImmediateRegister(), isImmediateRegister(), TTAMachine::Component::name(), TTAProgram::Terminal::registerFile(), and registerFile().
Referenced by ControlFlowGraph::createJumps().
immediateUnit()
const ImmediateUnit & TTAProgram::TerminalRegister::immediateUnit () const virtual
Returns the immediate unit of the long immediate register.
Applicable only if the unit of the terminal is an instance of ImmediateUnit.
Returns
The immediate unit of the long immediate register.
Exceptions
WrongSubclass if the unit of the terminal is not an instance of ImmediateUnit.
Reimplemented from TTAProgram::Terminal.
Definition at line 99 of file TerminalRegister.cc.
{
    if (isImmUnit_ == true) {
        return static_cast<const ImmediateUnit&>(unit_);
    } else {
        throw WrongSubclass(
            __FILE__, __LINE__, "TerminalRegister::immediateUnit()",
            "Unit of the terminal is not of type ImmediateUnit");
    }
}
References isImmUnit_, and unit_.
Referenced by equals().
index()
virtual int TTAProgram::TerminalRegister::index () const virtual
Return the index of the register (either a long immediate or a general-purpose register).
Returns
The index of the register.
Exceptions
WrongSubclass if the terminal is not an instance of TerminalRegister.
Reimplemented from TTAProgram::Terminal.
Referenced by llvm::LLVMTCEBuilder::createGuard(), equals(), setIndex(), toString(), SimpleIfConverter::writesRegister(), and CopyingDelaySlotFiller::writesRegister().
isGPR()
virtual bool TTAProgram::TerminalRegister::isGPR () const virtual
Tells whether the terminal is a general-purpose register.
Returns
True if the terminal is a general-purpose register.
Reimplemented from TTAProgram::Terminal.
Referenced by ControlFlowGraph::createJumps(), and equals().
isImmediateRegister()
virtual bool TTAProgram::TerminalRegister::isImmediateRegister () const virtual
Tells whether the terminal is a long immediate register.
Returns
True if the terminal is a long immediate register.
Reimplemented from TTAProgram::Terminal.
Referenced by ControlFlowGraph::createJumps(), and equals().
isUniversalMachineRegister()
bool TTAProgram::TerminalRegister::isUniversalMachineRegister () const virtual
Tells whether the terminal is a reg in UniversalMachine
Returns
True if the terminal is a register in universalmachine, ie. not in any real machine. This practically means the register is unallocated and meant to be bypassed.
Reimplemented from TTAProgram::Terminal.
Definition at line 198 of file TerminalRegister.cc.
{
    return (dynamic_cast<const UnboundedRegisterFile*>(&unit_) != NULL);
}
References unit_.
operator=()
TerminalRegister & TTAProgram::TerminalRegister::operator= (const TerminalRegister &) private
Assignment not allowed.
port()
const Port & TTAProgram::TerminalRegister::port () const virtual
Return the port.
Returns
The port of the unit of the terminal.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::Terminal.
Definition at line 116 of file TerminalRegister.cc.
{
    return port_;
}
References port_.
registerFile()
const RegisterFile & TTAProgram::TerminalRegister::registerFile () const virtual
Returns the register file of the general-purpose register.
Applicable only if the unit of the terminal is an instance of RegisterFile.
Returns
The register file of the general-purpose register.
Exceptions
WrongSubclass if the unit of the terminal is not an instance of RegisterFile.
Reimplemented from TTAProgram::Terminal.
Definition at line 78 of file TerminalRegister.cc.
{
    if (isImmUnit_ == false) {
        return static_cast<const RegisterFile&>(unit_);
    } else {
        throw WrongSubclass(
            __FILE__, __LINE__, "TerminalRegister::registerFile()",
            "Unit of the terminal is not of type RegisterFile");
    }
}
References isImmUnit_, and unit_.
Referenced by llvm::LLVMTCEBuilder::createGuard(), equals(), toString(), SimpleIfConverter::writesRegister(), and CopyingDelaySlotFiller::writesRegister().
setIndex()
void TTAProgram::TerminalRegister::setIndex (int index) virtual
Change the register of the register file to the given index.
Parameters
index The new register index.
Exceptions
OutOfRange if index is not smaller than the size of the register file or immediate unit it belongs to.
Reimplemented from TTAProgram::Terminal.
Definition at line 128 of file TerminalRegister.cc.
{
    const BaseRegisterFile& reg =
        dynamic_cast<const BaseRegisterFile&>(unit_);
    if (index < reg.numberOfRegisters()) {
        index_ = index;
    } else {
        throw OutOfRange(
            __FILE__, __LINE__, "TerminalRegister::setIndex()",
            "Index out of range.");
    }
}
References index(), index_, TTAMachine::BaseRegisterFile::numberOfRegisters(), and unit_.
toString()
TCEString TTAProgram::TerminalRegister::toString () const virtual
Implements TTAProgram::Terminal.
Definition at line 179 of file TerminalRegister.cc.
{
    if (isImmUnit_ == false) {
        DisassemblyRegister disasm(registerFile().name(), index());
        return disasm.toString();
    } else {
        TCEString res = unit_.name();
        res << "." << index_;
        return res;
    }
}
References index(), index_, isImmUnit_, TTAMachine::Component::name(), registerFile(), DisassemblyRegister::toString(), and unit_.
Member Data Documentation
index_
short TTAProgram::TerminalRegister::index_ private
Index of the register of the register file or immediate unit.
Definition at line 86 of file TerminalRegister.hh.
Referenced by copy(), setIndex(), and toString().
isImmUnit_
bool TTAProgram::TerminalRegister::isImmUnit_ private
Unit type flag: true if immediate unit, false if register file.
Definition at line 88 of file TerminalRegister.hh.
Referenced by immediateUnit(), registerFile(), TerminalRegister(), and toString().
port_
const TTAMachine::Port& TTAProgram::TerminalRegister::port_ private
Port of the unit.
Definition at line 84 of file TerminalRegister.hh.
Referenced by copy(), and port().
unit_
const TTAMachine::Unit& TTAProgram::TerminalRegister::unit_ private
Unit of the terminal.
Definition at line 82 of file TerminalRegister.hh.
Referenced by immediateUnit(), isUniversalMachineRegister(), registerFile(), setIndex(), TerminalRegister(), and toString().
The documentation for this class was generated from the following files:
TerminalRegister.hh
TerminalRegister.cc