OpenASIP: MachineValidatorResults Class Reference
MachineValidatorResults Class Reference
#include <MachineValidatorResults.hh>
Public Types
typedef std::pair< MachineValidator::ErrorCode, std::string > Error
Typedef for an error (error code + error message).
Public Member Functions
MachineValidatorResults ()
virtual ~MachineValidatorResults ()
int errorCount () const
Error error (int index) const
void addError (MachineValidator::ErrorCode code, const std::string &errorMsg)
Private Types
typedef std::vector< Error > ErrorTable
Typedef for vector of errors.
Private Attributes
ErrorTable errors_
Contains the errors.
Detailed Description
This class bundles up the results of MachineValidator.
Definition at line 45 of file MachineValidatorResults.hh.
Member Typedef Documentation
Error
typedef std::pair<MachineValidator::ErrorCode, std::string> MachineValidatorResults::Error
Typedef for an error (error code + error message).
Definition at line 48 of file MachineValidatorResults.hh.
ErrorTable
typedef std::vector<Error> MachineValidatorResults::ErrorTable private
Typedef for vector of errors.
Definition at line 62 of file MachineValidatorResults.hh.
Constructor & Destructor Documentation
MachineValidatorResults()
MachineValidatorResults::MachineValidatorResults ()
The constructor.
Definition at line 39 of file MachineValidatorResults.cc.
{
}
~MachineValidatorResults()
MachineValidatorResults::~MachineValidatorResults () virtual
The destructor.
Definition at line 46 of file MachineValidatorResults.cc.
{
}
Member Function Documentation
addError()
void MachineValidatorResults::addError (MachineValidator::ErrorCode code, const std::string & errorMsg)
Adds an error to the results.
Parameters
code The error code.
errorMsg The error message.
Definition at line 85 of file MachineValidatorResults.cc.
{
    Error error(code, errorMsg);
    errors_.push_back(error);
}
References error(), and errors_.
Referenced by MachineValidator::checkFUConnections(), MachineValidator::checkGCUExists(), MachineValidator::checkGCUHasAddressSpace(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkJumpAndCallOperandBindings(), FUValidator::checkOperandBindings(), FUValidator::checkOperations(), MachineValidator::checkProgramCounterPort(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), and MachineValidator::checkReturnAddressPort().
error()
MachineValidatorResults::Error MachineValidatorResults::error (int index) const
Returns an error by the given index.
Parameters
index The index.
Returns
The error.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 70 of file MachineValidatorResults.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return errors_[index];
}
References __func__, errorCount(), and errors_.
Referenced by addError(), HDB::HDBManager::addFUArchitecture(), LLVMBackend::compile(), ProgrammabilityValidator::ProgrammabilityValidator(), and ProGe::ProcessorGenerator::validateMachine().
errorCount()
int MachineValidatorResults::errorCount () const
Returns the number of errors.
Returns
The number of errors.
Definition at line 56 of file MachineValidatorResults.cc.
{
    return errors_.size();
}
References errors_.
Referenced by HDB::HDBManager::addFUArchitecture(), LLVMBackend::compile(), error(), ProgrammabilityValidator::ProgrammabilityValidator(), and ProGe::ProcessorGenerator::validateMachine().
Member Data Documentation
errors_
ErrorTable MachineValidatorResults::errors_ private
Contains the errors.
Definition at line 65 of file MachineValidatorResults.hh.
Referenced by addError(), error(), and errorCount().
The documentation for this class was generated from the following files:
MachineValidatorResults.hh
MachineValidatorResults.cc