OpenASIP: ProximFUDetailsCmd Class Reference
ProximFUDetailsCmd Class Reference
#include <ProximFUDetailsCmd.hh>
Public Member Functions
ProximFUDetailsCmd (const TTAMachine::FunctionUnit &fu)
virtual ~ProximFUDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::FunctionUnit & fu_
Function unit to display.
Detailed Description
Command for displaying function unit details in the machine state window component details pane.
Definition at line 46 of file ProximFUDetailsCmd.hh.
Constructor & Destructor Documentation
ProximFUDetailsCmd()
ProximFUDetailsCmd::ProximFUDetailsCmd (const TTAMachine::FunctionUnit & fu)
The Constructor.
Parameters
fu Function unit to display.
Definition at line 55 of file ProximFUDetailsCmd.cc.
                                                                       :
    ComponentCommand(), fu_(fu) {
}
~ProximFUDetailsCmd()
ProximFUDetailsCmd::~ProximFUDetailsCmd () virtual
The Destructor.
Definition at line 63 of file ProximFUDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximFUDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 70 of file ProximFUDetailsCmd.cc.
                       {
    string fuName = fu_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    MachineState& machineState = ProximToolbox::frontend()->machineState();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_FU_LABEL);
    machineWin->appendDetails(fuName + "\n\n");
    // Append ports to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_PORTS_TITLE + "\n");
    for (int i = 0; i < fu_.portCount(); i++) {
        string portName = fu_.port(i)->name();
        const PortState& portState = machineState.portState(portName, fuName);
        machineWin->appendDetails("  " + portName + ":\t");
        machineWin->appendDetails(
            Conversion::toString(portState.value().uIntWordValue()) + "\n");
    }
    // Append trigger count to the utlization widget.
    machineWin->appendUtilizationData(
        ProximConstants::MACH_WIN_TRIGGER_COUNT_LABEL);
    double triggerCount = stats.triggerCount(fuName);
    machineWin->appendUtilizationData(Conversion::toString(triggerCount));
    machineWin->appendUtilizationData("\n\n");
    // Append operation usage to the utilization widget.
    machineWin->appendUtilizationData(
        ProximConstants::MACH_WIN_EXECUTION_COUNT_LABEL);
    machineWin->appendUtilizationData("\n");
    for (int i = 0; i < fu_.operationCount(); i++) {
        string opName = StringTools::stringToUpper(fu_.operation(i)->name());
        ClockCycleCount execCount = stats.operationExecutions(fuName, opName);
        double percent = 0;
        if (triggerCount > 0) {
            percent = 100 * (execCount / triggerCount);
        }
        machineWin->appendUtilizationData(
            "  " + opName + ": " +
            Conversion::toString(execCount) + "  (" +
            Conversion::toString(percent) + "%)\n");
    }
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximMachineStateWindow::appendUtilizationData(), ProximToolbox::frontend(), fu_, ProximConstants::MACH_WIN_EXECUTION_COUNT_LABEL, ProximConstants::MACH_WIN_FU_LABEL, ProximConstants::MACH_WIN_PORTS_TITLE, ProximConstants::MACH_WIN_TRIGGER_COUNT_LABEL, SimulatorFrontend::machineState(), ProximToolbox::machineStateWindow(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), UtilizationStats::operationExecutions(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), MachineState::portState(), StringTools::stringToUpper(), Conversion::toString(), UtilizationStats::triggerCount(), SimValue::uIntWordValue(), SimulatorFrontend::utilizationStatistics(), and RegisterState::value().
Member Data Documentation
fu_
const TTAMachine::FunctionUnit& ProximFUDetailsCmd::fu_ private
Function unit to display.
Definition at line 53 of file ProximFUDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximFUDetailsCmd.hh
ProximFUDetailsCmd.cc