OpenASIP: ExplorerCmdLineOptions Class Reference
ExplorerCmdLineOptions Class Reference
#include <ExplorerCmdLineOptions.hh>
Public Member Functions
ExplorerCmdLineOptions ()
virtual ~ExplorerCmdLineOptions ()
virtual void printVersion () const
virtual void printHelp () const
std::string explorerPlugin () const
std::string pluginInfo () const
int testApplicationDirectoryCount () const
std::string testApplicationDirectory (int index) const
int explorerPluginParameterCount () const
std::string explorerPluginParameter (int index) const
bool numberOfConfigurations () const
bool printSummary () const
std::string summaryOrdering () const
bool writeOutConfiguration () const
bool writeOutBestConfiguration () const
int numberOfConfigurationsToWrite () const
RowID configurationToWrite (int index) const
bool printApplications () const
bool printPlugins () const
int applicationIDToRemoveCount () const
RowID applicationIDToRemove (int index) const
bool hdbFileNames () const
int hdbFileNameCount () const
std::string hdbFileName (int index) const
RowID startConfiguration () const
bool adfFile () const
bool adfOutFile () const
bool idfFile () const
std::string adfFileName () const
std::string adfOutFileName () const
std::string idfFileName () const
std::string paretoSetValues () const
bool compilerOptions () const
std::string compilerOptionsString () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Private Member Functions
ExplorerCmdLineOptions (const ExplorerCmdLineOptions &)
Copying not allowed.
ExplorerCmdLineOptions & operator= (const ExplorerCmdLineOptions &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line option class for Explorer.
Definition at line 45 of file ExplorerCmdLineOptions.hh.
Constructor & Destructor Documentation
ExplorerCmdLineOptions() [1/2]
ExplorerCmdLineOptions::ExplorerCmdLineOptions ()
Constructor.
Todo:
Use textgenerator in the help texts.
Definition at line 117 of file ExplorerCmdLineOptions.cc.
                                               : CmdLineOptions("") {
    addOption(
        new StringCmdLineOptionParser(
            SWL_PLUGIN_NAME,
            "Design Space Explorer plugin to be used.",
            SWS_PLUGIN_NAME));
    addOption(
        new StringCmdLineOptionParser(
            SWL_PLUGIN_INFO,
            "Design Space Explorer plugin to print info about.",
            SWS_PLUGIN_INFO));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_PLUGIN_PARAM,
            "Parameter to the explorer plugin in form 'name=value'.",
            SWS_PLUGIN_PARAM));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_TEST_DIR_ADD,
            "Path(s) of the test application(s) to be added into the DSDB.",
            SWS_TEST_DIR_ADD));
    addOption(
        new IntegerListCmdLineOptionParser(
            SWL_TEST_DIR_RM,
            "ID(s) of the test program path(s) to be removed from the DSDB.",
            SWS_TEST_DIR_RM));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_START_ID,
            "Starting point configuration ID in the DSDB.",
            SWS_START_ID));
    addOption(
        new StringCmdLineOptionParser(
            SWL_CONFIGURATION_SUMMARY,
            "Print the summary of machine configurations in the DSDB"
            "ordered by:\n"
            "  Ordering may be one of the following:\n"
            "    I  ordering by configuration Id,\n"
            "    P  ordering by application path,\n"
            "    C  ordering by cycle count,\n"
            "    E  ordering by energy estimate.",
            SWS_CONFIGURATION_SUMMARY));
    addOption(
        new StringCmdLineOptionParser(
            SWL_PARETO_SET,
            "Print the pareto sets of machine configurations in the DSDB "
            "with certain value sets:\n"
            "  Value set may be one of the following:\n"
            "    C  cycle counts and number of connections.",
            SWS_PARETO_SET));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_CONFIGURATION_COUNT,
            "Print the number of machine configurations in the DSDB.",
            SWS_CONFIGURATION_COUNT));
    addOption(
        new IntegerListCmdLineOptionParser(
            SWL_CONFIGURATION_WRITE,
            "Write out the ADF and IDF files from the DSDB with given "
            "configuration id.",
            SWS_CONFIGURATION_WRITE));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_LIST_APPS,
            "List the applications in the DSDB.",
            SWS_LIST_APPS));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_LIST_PLUGINS,
            "List loadable plugins.",
            SWS_LIST_PLUGINS));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_HDB_FILE,
            "HDB to use with exploration. If not given 'asic_130nm_1.5V.hdb' "
            "will be used.",
            SWS_HDB_FILE));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_ADF_FILE,
            "ADF to add into the DSDB.",
            SWS_ADF_FILE));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_IDF_FILE,
            "IDF to add into the DSDB, needs also ADF.",
            SWS_IDF_FILE));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_COMPILER_OPTIONS,
            "Options to pass to the compiler.",
            SWS_COMPILER_OPTIONS));
    addOption(
        new StringCmdLineOptionParser(
            SWL_ADF_OUT_FILE,
            "Set the ADF output filename (use in combination with -w "
            "or --dump_best).", ""));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DUMP_BEST,
            "Dump the best configuration produced by the executed exploration "
            "algorithm.", ""));
}
References CmdLineParser::addOption(), SWL_ADF_FILE, SWL_ADF_OUT_FILE, SWL_COMPILER_OPTIONS, SWL_CONFIGURATION_COUNT, SWL_CONFIGURATION_SUMMARY, SWL_CONFIGURATION_WRITE, SWL_DUMP_BEST, SWL_HDB_FILE, SWL_IDF_FILE, SWL_LIST_APPS, SWL_LIST_PLUGINS, SWL_PARETO_SET, SWL_PLUGIN_INFO, SWL_PLUGIN_NAME, SWL_PLUGIN_PARAM, SWL_START_ID, SWL_TEST_DIR_ADD, SWL_TEST_DIR_RM, SWS_ADF_FILE, SWS_COMPILER_OPTIONS, SWS_CONFIGURATION_COUNT, SWS_CONFIGURATION_SUMMARY, SWS_CONFIGURATION_WRITE, SWS_HDB_FILE, SWS_IDF_FILE, SWS_LIST_APPS, SWS_LIST_PLUGINS, SWS_PARETO_SET, SWS_PLUGIN_INFO, SWS_PLUGIN_NAME, SWS_PLUGIN_PARAM, SWS_START_ID, SWS_TEST_DIR_ADD, and SWS_TEST_DIR_RM.
~ExplorerCmdLineOptions()
ExplorerCmdLineOptions::~ExplorerCmdLineOptions () virtual
Destructor.
Definition at line 224 of file ExplorerCmdLineOptions.cc.
{
}
ExplorerCmdLineOptions() [2/2]
ExplorerCmdLineOptions::ExplorerCmdLineOptions (const ExplorerCmdLineOptions &) private
Copying not allowed.
Member Function Documentation
adfFile()
bool ExplorerCmdLineOptions::adfFile () const
Returns true if an adf file is given as an option.
Returns
True if an adf file is given as an option.
Definition at line 538 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_ADF_FILE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_ADF_FILE.
Referenced by adfFileName().
adfFileName()
std::string ExplorerCmdLineOptions::adfFileName () const
Returns the name of the adf file given as an option.
Returns an empty string if no adf file was given.
Returns
ADF file name.
Definition at line 565 of file ExplorerCmdLineOptions.cc.
{
    if (adfFile()) {
        return findOption(SWL_ADF_FILE)->String(1);
    } else {
        return "";
    }
}
References adfFile(), CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_ADF_FILE.
adfOutFile()
bool ExplorerCmdLineOptions::adfOutFile () const
Definition at line 543 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_ADF_OUT_FILE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_ADF_OUT_FILE.
Referenced by adfOutFileName().
adfOutFileName()
std::string ExplorerCmdLineOptions::adfOutFileName () const
Definition at line 574 of file ExplorerCmdLineOptions.cc.
{
    if (adfOutFile()) {
        return findOption(SWL_ADF_OUT_FILE)->String();
    } else {
        return "";
    }
}
References adfOutFile(), CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_ADF_OUT_FILE.
applicationIDToRemove()
RowID ExplorerCmdLineOptions::applicationIDToRemove (int index) const
By the given index, returns the application id given as an option to remove from DSDB.
Parameters
index The index.
Returns
Application id in the given index.
Exceptions
OutOfRange If the given index is negative or greater than the number of expendable applications.
Definition at line 469 of file ExplorerCmdLineOptions.cc.
{
    if (index < 0 || index >= applicationIDToRemoveCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return findOption(SWL_TEST_DIR_RM)->integer(index + 1);
}
References __func__, applicationIDToRemoveCount(), CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_TEST_DIR_RM.
applicationIDToRemoveCount()
int ExplorerCmdLineOptions::applicationIDToRemoveCount () const
Returns the number of test applications to be removed from the DSDB.
Returns
The number of expendable applications.
Definition at line 455 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_TEST_DIR_RM)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_TEST_DIR_RM.
Referenced by applicationIDToRemove().
compilerOptions()
bool ExplorerCmdLineOptions::compilerOptions () const
Returns true if a compiler options are given as an option.
Returns
True if a compiler options are given as an option.
Definition at line 604 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_COMPILER_OPTIONS)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_COMPILER_OPTIONS.
Referenced by compilerOptionsString().
compilerOptionsString()
std::string ExplorerCmdLineOptions::compilerOptionsString () const
Returns the string of compiler options given as an option.
Returns an empty string if no compiler options were given.
Returns
compiler options as a string.
Definition at line 616 of file ExplorerCmdLineOptions.cc.
{
    if (!compilerOptions()) return "";
    TCEString optsString;
    for (int i = 0; i < findOption(SWL_COMPILER_OPTIONS)->listSize(); ++i) {
        optsString << findOption(SWL_COMPILER_OPTIONS)->String(i + 1) << " ";
    }
    return optsString;
}
References compilerOptions(), CmdLineParser::findOption(), CmdLineOptionParser::listSize(), CmdLineOptionParser::String(), and SWL_COMPILER_OPTIONS.
configurationToWrite()
RowID ExplorerCmdLineOptions::configurationToWrite (int index) const
By the given index, returns the configuration id given as an option.
Parameters
index The index.
Returns
Configuration id in the given index.
Exceptions
OutOfRange If the given index is negative or greater than the number configurations.
Definition at line 421 of file ExplorerCmdLineOptions.cc.
{
    if (index < 0 || index >= numberOfConfigurationsToWrite()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return findOption(SWL_CONFIGURATION_WRITE)->integer(index + 1);
}
References __func__, CmdLineParser::findOption(), CmdLineOptionParser::integer(), numberOfConfigurationsToWrite(), and SWL_CONFIGURATION_WRITE.
explorerPlugin()
std::string ExplorerCmdLineOptions::explorerPlugin () const
Returns the explorer plugin name.
Returns
The explorer plugin name.
Definition at line 274 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_PLUGIN_NAME)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_PLUGIN_NAME.
explorerPluginParameter()
std::string ExplorerCmdLineOptions::explorerPluginParameter (int index) const
By the given index, returns a parameter given to the explorer plugin.
Parameters
index The index.
Returns
Parameter in the given index.
Exceptions
OutOfRange If the given index is negative or greater than the number of parameters given to the explorer plugin.
Definition at line 335 of file ExplorerCmdLineOptions.cc.
{
    if (index < 0 || index >= explorerPluginParameterCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return findOption(SWL_PLUGIN_PARAM)->String(index + 1);
}
References __func__, explorerPluginParameterCount(), CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_PLUGIN_PARAM.
explorerPluginParameterCount()
int ExplorerCmdLineOptions::explorerPluginParameterCount () const
Returns the number of parameters given to the explorer plugin.
Returns
The number of parameters.
Definition at line 322 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_PLUGIN_PARAM)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_PLUGIN_PARAM.
Referenced by explorerPluginParameter().
hdbFileName()
std::string ExplorerCmdLineOptions::hdbFileName (int index) const
By the given index, returns the HDB file given as an option.
Parameters
index The index.
Returns
HDB file string from the given index.
Exceptions
OutOfRange If the given index is negative or greater than the number given HDB files.
Definition at line 506 of file ExplorerCmdLineOptions.cc.
{
    if (index < 0 || index >= hdbFileNameCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return findOption(SWL_HDB_FILE)->String(index + 1);
}
References __func__, CmdLineParser::findOption(), hdbFileNameCount(), CmdLineOptionParser::String(), and SWL_HDB_FILE.
hdbFileNameCount()
int ExplorerCmdLineOptions::hdbFileNameCount () const
Returns the number of the HDB file options given.
Returns
Number of given HDB file options.
Definition at line 493 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_HDB_FILE)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_HDB_FILE.
Referenced by hdbFileName().
hdbFileNames()
bool ExplorerCmdLineOptions::hdbFileNames () const
Returns true if at least one HDB file is given as an option.
Returns
True if the option is defined.
Definition at line 483 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_HDB_FILE)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_HDB_FILE.
idfFile()
bool ExplorerCmdLineOptions::idfFile () const
Returns true if an idf file is given as an option.
Returns
True if an idf file is given as an option.
Definition at line 553 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_IDF_FILE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_IDF_FILE.
Referenced by idfFileName().
idfFileName()
std::string ExplorerCmdLineOptions::idfFileName () const
Returns the name of the idf file given as an option.
Returns an empty string if no adf file was given.
Returns
IDF file name.
Definition at line 590 of file ExplorerCmdLineOptions.cc.
{
    if (idfFile()) {
        return findOption(SWL_IDF_FILE)->String(1);
    } else {
        return "";
    }
}
References CmdLineParser::findOption(), idfFile(), CmdLineOptionParser::String(), and SWL_IDF_FILE.
numberOfConfigurations()
bool ExplorerCmdLineOptions::numberOfConfigurations () const
Returns true if the number of configurations options is set.
Returns
True if the option is set.
Definition at line 349 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_CONFIGURATION_COUNT)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_CONFIGURATION_COUNT.
numberOfConfigurationsToWrite()
int ExplorerCmdLineOptions::numberOfConfigurationsToWrite () const
Returns the number of the write out configuration options given.
Returns
Number of given write out options.
Definition at line 408 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_CONFIGURATION_WRITE)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_CONFIGURATION_WRITE.
Referenced by configurationToWrite().
operator=()
ExplorerCmdLineOptions & ExplorerCmdLineOptions::operator= (const ExplorerCmdLineOptions &) private
Assignment not allowed.
paretoSetValues()
std::string ExplorerCmdLineOptions::paretoSetValues () const
Returns the valuing type of the pareto set printing.
Returns
Empty if pareto set not wanted.
Definition at line 379 of file ExplorerCmdLineOptions.cc.
{
    if (!findOption(SWL_PARETO_SET)->isDefined()) {
        return "";
    }
    return findOption(SWL_PARETO_SET)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_PARETO_SET.
pluginInfo()
std::string ExplorerCmdLineOptions::pluginInfo () const
Returns the the plugin name which info is to be printed.
Returns
The explorer plugin name which info is to be printed.
Definition at line 284 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_PLUGIN_INFO)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_PLUGIN_INFO.
printApplications()
bool ExplorerCmdLineOptions::printApplications () const
Returns true if print applications option is used.
Returns
True if the option is defined.
Definition at line 435 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_LIST_APPS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_LIST_APPS.
printHelp()
void ExplorerCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Todo:
Implement using ExplorerTextGenerator.
Reimplemented from CmdLineOptions.
Definition at line 242 of file ExplorerCmdLineOptions.cc.
{
    printVersion();
    std::cout << std::endl
              << "Usage: explore [options] [dsdb_file]"
              << std::endl
              << "Example: -e InitialMachineExplorer "
              << "-d data/newApplication "
              << "-u bus_count=5 -u build_idf=true test.dsdb"
              << std::endl
              << std::endl
              << "DSDB file is required always and new is created if not found."
              << std::endl
              << "Plugin name, DSDB and at least one application directory "
              << std::endl
              << "in the DSDB are required to run exploration, start "
              << std::endl
              << "configuration ID is optional."
              << std::endl
              << "Any number of parameters that are passed to the used plugin "
              << "can be given."
              << std::endl
              << "Queries can be carried out to the DSDB."
              << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printPlugins()
bool ExplorerCmdLineOptions::printPlugins () const
Returns true if print applications option is used.
Returns
True if the option is defined.
Definition at line 445 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_LIST_PLUGINS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SWL_LIST_PLUGINS.
printSummary()
bool ExplorerCmdLineOptions::printSummary () const
Returns true if the number of configurations options is set.
Returns
True if the option is set.
Definition at line 359 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_CONFIGURATION_SUMMARY)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_CONFIGURATION_SUMMARY.
printVersion()
void ExplorerCmdLineOptions::printVersion () const virtual
Prints the version of the program.
Implements CmdLineOptions.
Definition at line 231 of file ExplorerCmdLineOptions.cc.
{
    std::cout << DSCLI_TITLE << " version "
              << Application::TCEVersionString() << std::endl;
}
References DSCLI_TITLE, and Application::TCEVersionString().
Referenced by printHelp().
startConfiguration()
RowID ExplorerCmdLineOptions::startConfiguration () const
Returns the ID of the start configuration given as option.
If start configuration option was not given returns zero.
Returns
The ID of given start configuration or zero if the option was not used.
Definition at line 523 of file ExplorerCmdLineOptions.cc.
{
    if (findOption(SWL_START_ID)->isDefined()) {
        return findOption(SWL_START_ID)->integer();
    } else {
        return 0;
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_START_ID.
summaryOrdering()
std::string ExplorerCmdLineOptions::summaryOrdering () const
Returns true if the number of configurations options is set.
Returns
True if the option is set.
Definition at line 369 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_CONFIGURATION_SUMMARY)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWL_CONFIGURATION_SUMMARY.
testApplicationDirectory()
std::string ExplorerCmdLineOptions::testApplicationDirectory (int index) const
By the given index, returns a test application directory name given as command line parameter.
Parameters
index The index.
Returns
Test application directory path in the given index.
Exceptions
OutOfRange If the given index is negative or greater than the number of test directories given as parameter.
Definition at line 308 of file ExplorerCmdLineOptions.cc.
{
    if (index < 0 || index >= testApplicationDirectoryCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return findOption(SWL_TEST_DIR_ADD)->String(index + 1);
}
References __func__, CmdLineParser::findOption(), CmdLineOptionParser::String(), SWL_TEST_DIR_ADD, and testApplicationDirectoryCount().
testApplicationDirectoryCount()
int ExplorerCmdLineOptions::testApplicationDirectoryCount () const
Returns the number of directories where test applications are located.
Returns
The number of test directories.
Definition at line 294 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_TEST_DIR_ADD)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_TEST_DIR_ADD.
Referenced by testApplicationDirectory().
writeOutBestConfiguration()
bool ExplorerCmdLineOptions::writeOutBestConfiguration () const
Definition at line 398 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_DUMP_BEST)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_DUMP_BEST.
writeOutConfiguration()
bool ExplorerCmdLineOptions::writeOutConfiguration () const
Returns true if writing out configuration(s) option is used.
Returns
True if the option is defined.
Definition at line 393 of file ExplorerCmdLineOptions.cc.
{
    return findOption(SWL_CONFIGURATION_WRITE)->listSize();
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), and SWL_CONFIGURATION_WRITE.
The documentation for this class was generated from the following files:
ExplorerCmdLineOptions.hh
ExplorerCmdLineOptions.cc