OpenASIP: AlteraOnchipRomGenerator Class Reference
AlteraOnchipRomGenerator Class Reference
#include <AlteraOnchipRomGenerator.hh>
Public Member Functions
AlteraOnchipRomGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator *integrator, std::ostream &warningStream, std::ostream &errorStream)
virtual ~AlteraOnchipRomGenerator ()
virtual bool generatesComponentHdlFile () const
virtual std::vector< TCEString > generateComponentFile (TCEString outputPath)
virtual void addMemory (const ProGe::NetlistBlock &ttaCore, ProGe::NetlistBlock &integratorBlock, int memIndex, int coreId)
Public Member Functions inherited from AlteraMemGenerator
AlteraMemGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator *integrator, std::ostream &warningStream, std::ostream &errorStream)
virtual ~AlteraMemGenerator ()
Public Member Functions inherited from MemoryGenerator
MemoryGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator *integrator, std::ostream &warningStream, std::ostream &errorStream)
virtual ~MemoryGenerator ()
virtual bool isCompatible (const ProGe::NetlistBlock &ttaCore, int coreId, std::vector< TCEString > &reasons) const
int memoryTotalWidth () const
int memoryMauSize () const
int memoryWidthInMaus () const
int memoryAddrWidth () const
TCEString initializationFile () const
void addLsu (TTAMachine::FunctionUnit &lsuArch, std::vector< std::string > lsuPorts)
Protected Member Functions
virtual TCEString moduleName () const
virtual TCEString instanceName (int coreId, int memIndex) const
Protected Member Functions inherited from AlteraMemGenerator
std::vector< TCEString > instantiateAlteraTemplate (const TCEString &templateFile, const TCEString &outputPath) const
virtual void addGenerics (ProGe::NetlistBlock &topBlock, const TCEString &addrWidth, const TCEString &dataWidth, int memIndex)
Protected Member Functions inherited from MemoryGenerator
virtual bool checkFuPort (const std::string fuPort, std::vector< TCEString > &reasons) const
virtual void connectPorts (ProGe::NetlistBlock &netlistBlock, const ProGe::NetlistPort &memPort, const ProGe::NetlistPort &corePort, bool inverted, int coreId)
virtual MemoryGenerator::BlockPair createMemoryNetlistBlock (ProGe::NetlistBlock &integratorBlock, int memIndex, int coreId)
const PlatformIntegrator * platformIntegrator () const
std::ostream & warningStream ()
std::ostream & errorStream ()
int portCount () const
const HDLPort * port (int index) const
const HDLPort * portByKeyName (TCEString name) const
TCEString portKeyName (const HDLPort *port) const
void addPort (const TCEString &name, HDLPort *port)
int parameterCount () const
const ProGe::Parameter & parameter (int index) const
void addParameter (const ProGe::Parameter &add)
TCEString ttaCoreName () const
TCEString memoryIndexString (int coreId, int memIndex) const
TCEString templatePath () const
void instantiateTemplate (const TCEString &inFile, const TCEString &outFile, const TCEString &entity) const
bool hasLSUArchitecture () const
const TTAMachine::FunctionUnit & lsuArchitecture () const
TCEString corePortName (const TCEString &portBaseName, int coreId) const
Static Private Attributes
static const TCEString COMPONENT_FILE
Additional Inherited Members
Protected Types inherited from MemoryGenerator
typedef std::multimap< TCEString, HDLPort * > PortMap
typedef std::pair< ProGe::NetlistBlock *, ProGe::VirtualNetlistBlock * > BlockPair
Static Protected Attributes inherited from AlteraMemGenerator
static const TCEString INIT_FILE_G = "init_file_g"
static const TCEString DEV_FAMILY_G = "dev_family_g"
static const TCEString ADDRW_G = "addrw_g"
static const TCEString DATAW_G = "dataw_g"
Detailed Description
Definition at line 43 of file AlteraOnchipRomGenerator.hh.
Constructor & Destructor Documentation
AlteraOnchipRomGenerator()
AlteraOnchipRomGenerator::AlteraOnchipRomGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator * integrator, std::ostream & warningStream, std::ostream & errorStream)
Definition at line 44 of file AlteraOnchipRomGenerator.cc.
                            :
    AlteraMemGenerator(memMauWidth, widthInMaus, addrWidth, initFile,
                       integrator, warningStream, errorStream) {
    bool noInvert = false;
    bool inverted = true;
    addPort("clk",
        new HDLPort("clock", "1", ProGe::BIT, ProGe::IN, noInvert, 1));
    addPort("imem_addr",
        new HDLPort("address", "IMEMADDRWIDTH", ProGe::BIT_VECTOR,
            ProGe::IN, noInvert));
    addPort("imem_en_x",
        new HDLPort("clken", "1", ProGe::BIT, ProGe::IN, inverted, 1));
    addPort("imem_data",
        new HDLPort("q", "IMEMWIDTHINMAUS*IMEMMAUWIDTH",
            ProGe::BIT_VECTOR, ProGe::OUT, noInvert));
    // these signals are not driven by the imem component, connect to zero
    HDLPort* busyToGnd =
        new HDLPort("wait", "1", ProGe::BIT, ProGe::OUT, noInvert, 1);
    busyToGnd->setToStatic(ProGe::StaticSignal::GND);
    addPort("busy", busyToGnd);
}
References MemoryGenerator::addPort(), ProGe::BIT, ProGe::BIT_VECTOR, ProGe::StaticSignal::GND, ProGe::IN, ProGe::OUT, and HDLPort::setToStatic().
~AlteraOnchipRomGenerator()
AlteraOnchipRomGenerator::~AlteraOnchipRomGenerator () virtual
Definition at line 77 of file AlteraOnchipRomGenerator.cc.
{
}
Member Function Documentation
addMemory()
void AlteraOnchipRomGenerator::addMemory (const ProGe::NetlistBlock & ttaCore, ProGe::NetlistBlock & integratorBlock, int memIndex, int coreId) virtual
Reimplemented from AlteraMemGenerator.
Definition at line 93 of file AlteraOnchipRomGenerator.cc.
                {
    // Add generics as string constants!
    TCEString addrwGeneric = "IMEMADDRWIDTH";
    TCEString datawGeneric = "IMEMWIDTHINMAUS*IMEMMAUWIDTH";
    addGenerics(integratorBlock, addrwGeneric, datawGeneric, memIndex);
    MemoryGenerator::addMemory(ttaCore, integratorBlock, memIndex, coreId);
}
References AlteraMemGenerator::addGenerics(), and MemoryGenerator::addMemory().
generateComponentFile()
std::vector< TCEString > AlteraOnchipRomGenerator::generateComponentFile (TCEString outputPath) virtual
Implements MemoryGenerator.
Definition at line 87 of file AlteraOnchipRomGenerator.cc.
{
    return instantiateAlteraTemplate(COMPONENT_FILE, outputPath);
}
References COMPONENT_FILE, and AlteraMemGenerator::instantiateAlteraTemplate().
generatesComponentHdlFile()
bool AlteraOnchipRomGenerator::generatesComponentHdlFile () const virtual
Implements MemoryGenerator.
Definition at line 81 of file AlteraOnchipRomGenerator.cc.
{
    return true;
}
instanceName()
TCEString AlteraOnchipRomGenerator::instanceName (int coreId, int memIndex) const protected virtual
Implements MemoryGenerator.
Definition at line 115 of file AlteraOnchipRomGenerator.cc.
{
    TCEString iname("onchip_imem_");
    return iname << memoryIndexString(coreId, memIndex);
}
References MemoryGenerator::memoryIndexString().
moduleName()
TCEString AlteraOnchipRomGenerator::moduleName () const protected virtual
Implements MemoryGenerator.
Definition at line 108 of file AlteraOnchipRomGenerator.cc.
{
    return ttaCoreName() + "_altera_onchip_rom_comp";
}
References MemoryGenerator::ttaCoreName().
Member Data Documentation
COMPONENT_FILE
const TCEString AlteraOnchipRomGenerator::COMPONENT_FILE static private
Initial value:
=
    "altera_onchip_rom_comp.vhd"
Definition at line 76 of file AlteraOnchipRomGenerator.hh.
Referenced by generateComponentFile().
The documentation for this class was generated from the following files:
AlteraOnchipRomGenerator.hh
AlteraOnchipRomGenerator.cc