OpenASIP: ResourceBroker Class Reference
ResourceBroker Class Reference abstract
#include <ResourceBroker.hh>
Public Types
typedef std::set< SchedulingResource * > ResourceSet
Public Member Functions
ResourceBroker (std::string, unsigned int initiationInterval=0)
virtual ~ResourceBroker ()
virtual bool isAnyResourceAvailable (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual SchedulingResource & availableResource (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual SchedulingResourceSet allAvailableResources (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual bool isAvailable (SchedulingResource &des, const MoveNode &node, int cycle, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual int earliestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const =0
virtual int latestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const =0
virtual bool isAlreadyAssigned (int cycle, const MoveNode &node, const TTAMachine::Bus *preassignedBus) const =0
virtual bool isApplicable (const MoveNode &node, const TTAMachine::Bus *preassignedBus) const =0
virtual void assign (int cycle, MoveNode &node, SchedulingResource &res, int immWriteCycle, int immRegIndex)=0
virtual void unassign (MoveNode &node)=0
virtual void buildResources (const TTAMachine::Machine &target)=0
virtual void setupResourceLinks (const ResourceMapper &mapper)=0
SchedulingResource * resourceOf (const TTAMachine::MachinePart &mp) const
virtual const TTAMachine::MachinePart & machinePartOf (const SchedulingResource &r) const
bool hasResourceOf (const TTAMachine::MachinePart &mp) const
bool hasResource (const SchedulingResource &r) const
int resourceCount () const
virtual bool isBusBroker () const
virtual bool isITemplateBroker () const
virtual bool isIUBroker () const
virtual bool isExecutionPipelineBroker () const
void validateResources () const
virtual std::string brokerName () const
void resources (ResourceSet &contents)
virtual void setInitiationInterval (unsigned int cycles)
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Protected Types
typedef std::map< const TTAMachine::MachinePart *, SchedulingResource *, TTAMachine::MachinePart::Comparator > ResourceMap
typedef std::map< const MoveNode *, SchedulingResource *, MoveNode::Comparator > MoveResMap
Protected Member Functions
void setResourceMapper (const ResourceMapper &mapper)
const ResourceMapper & resourceMapper () const
unsigned int instructionIndex (unsigned int) const
void addResource (const TTAMachine::MachinePart &mp, SchedulingResource *res)
Protected Attributes
unsigned int initiationInterval_
ResourceMap resMap_
const ResourceMapper * resourceMapper_
MoveResMap assignedResources_
std::string brokerName_
Detailed Description
Base interface for resource brokers.
Definition at line 61 of file ResourceBroker.hh.
Member Typedef Documentation
MoveResMap
typedef std::map<const MoveNode*, SchedulingResource*, MoveNode::Comparator> ResourceBroker::MoveResMap protected
Definition at line 154 of file ResourceBroker.hh.
ResourceMap
typedef std::map< const TTAMachine::MachinePart*, SchedulingResource*, TTAMachine::MachinePart::Comparator> ResourceBroker::ResourceMap protected
Definition at line 151 of file ResourceBroker.hh.
ResourceSet
typedef std::set<SchedulingResource*> ResourceBroker::ResourceSet
Definition at line 66 of file ResourceBroker.hh.
Constructor & Destructor Documentation
ResourceBroker()
ResourceBroker::ResourceBroker (std::string name, unsigned int initiationInterval = 0)
Constructor.
Definition at line 49 of file ResourceBroker.cc.
                                        :
    initiationInterval_(initiationInterval),
    resourceMapper_(NULL),
    brokerName_(name){
}
~ResourceBroker()
ResourceBroker::~ResourceBroker () virtual
Destructor.
Definition at line 59 of file ResourceBroker.cc.
{
    MapTools::deleteAllValues(resMap_);
}
References MapTools::deleteAllValues(), and resMap_.
Member Function Documentation
addResource()
void ResourceBroker::addResource (const TTAMachine::MachinePart & mp, SchedulingResource * res) protected
Add resource - machine part pair to the broker.
Parameters
mp Machine part.
res Corresponding resource.
Definition at line 265 of file ResourceBroker.cc.
{
    resMap_.insert(
        pair<const TTAMachine::MachinePart*, SchedulingResource*>(&mp, res));
}
References resMap_.
Referenced by BusBroker::buildResources(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), InputPSocketBroker::buildResources(), ITemplateBroker::buildResources(), IUBroker::buildResources(), OutputFUBroker::buildResources(), and OutputPSocketBroker::buildResources().
allAvailableResources()
SchedulingResourceSet ResourceBroker::allAvailableResources (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const virtual
Return all resources managed by this broker that can be assigned to the given node in the given cycle.
Returns
All resources managed by this broker that can be assigned to the given node in the given cycle.
Parameters
cycle Cycle.
node Node.
Note
This default implementation always returns an empty set.
Reimplemented in BusBroker, InputFUBroker, InputPSocketBroker, OutputFUBroker, OutputPSocketBroker, IUBroker, and ITemplateBroker.
Definition at line 143 of file ResourceBroker.cc.
{
    SchedulingResourceSet resourceSet;
    return resourceSet;
}
Referenced by PendingAssignment::isAssignmentPossible(), and isAvailable().
assign()
virtual void ResourceBroker::assign (int cycle, MoveNode & node, SchedulingResource & res, int immWriteCycle, int immRegIndex) pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, ITemplateBroker, OutputFUBroker, OutputPSocketBroker, and IUBroker.
Referenced by PendingAssignment::tryNext().
availableResource()
SchedulingResource & ResourceBroker::availableResource (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const virtual
Return one (any) resource managed by this broker that can be assigned to the given node in the given cycle.
If no change occurs to the state of the resources, the broker should always return the same object. If a resource of the type managed by this broker is already assigned to the node, it is returned.
Parameters
cycle Cycle.
node Node.
Returns
One (any) resource managed by this broker that can be assigned to the given node in the given cycle.
Exceptions
InstanceNotFound If no available resource is found.
Reimplemented in BusBroker, and IUBroker.
Definition at line 111 of file ResourceBroker.cc.
          {
    for (ResourceMap::const_iterator resIter = resMap_.begin();
         resIter != resMap_.end(); resIter++) {
        SchedulingResource* res = (*resIter).second;
        if (res->isAvailable(cycle)
        && res->canAssign(cycle, node)) {
            return *res;
        }
    }
    string msg = "No available resource found.";
    throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
}
References __func__, SchedulingResource::canAssign(), SchedulingResource::isAvailable(), and resMap_.
brokerName()
std::string ResourceBroker::brokerName () const virtual
Returns the name of particular broker. Used for debugging mainly.
Returns
Name of a broker.
Definition at line 356 of file ResourceBroker.cc.
{
    return brokerName_;
}
References brokerName_.
Referenced by validateResources().
buildResources()
virtual void ResourceBroker::buildResources (const TTAMachine::Machine & target) pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, ITemplateBroker, IUBroker, OutputFUBroker, and OutputPSocketBroker.
clear()
void ResourceBroker::clear () virtual
Clears all resources managed by the broker so that the broker can be reused.
Reimplemented in BusBroker, and ITemplateBroker.
Definition at line 365 of file ResourceBroker.cc.
                      {
    // Call clear for all resources.
    for (ResourceMap::iterator i = resMap_.begin(); i != resMap_.end(); i++) {
        i->second->clear();
    }
    assignedResources_.clear();
}
References assignedResources_, and resMap_.
Referenced by BusBroker::clear(), and ITemplateBroker::clear().
earliestCycle()
virtual int ResourceBroker::earliestCycle (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, IUBroker, OutputFUBroker, OutputPSocketBroker, and ITemplateBroker.
hasResource()
bool ResourceBroker::hasResource (const SchedulingResource & r) const
Return true if this broker holds given resource instance.
Parameters
r Scheduling resource.
Returns
True if this broker holds given resource instance.
Definition at line 214 of file ResourceBroker.cc.
{
    return MapTools::containsValue(resMap_, &r);
}
References MapTools::containsValue(), and resMap_.
Referenced by BusBroker::assign(), InputFUBroker::assign(), InputPSocketBroker::assign(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), and IUBroker::assign().
hasResourceOf()
bool ResourceBroker::hasResourceOf (const TTAMachine::MachinePart & mp) const
Return true if this broker holds a resource instance that models given machine part.
Parameters
mp Machine part.
Returns
True if this broker holds a resource instance that models given machine part.
Definition at line 203 of file ResourceBroker.cc.
{
    return MapTools::containsKey(resMap_, &mp);
}
References MapTools::containsKey(), and resMap_.
Referenced by FUBroker::findDstFUOfMove(), FUBroker::findFUOfPO(), InputFUBroker::isAlreadyAssigned(), OutputFUBroker::isAlreadyAssigned(), and BusBroker::isInUse().
instructionIndex()
unsigned int ResourceBroker::instructionIndex (unsigned int cycle) const protected
Return the instruction index corresponding to cycle.
If modulo scheduling is not used (ie. initiation interval is 0), then index is equal to cycle.
Parameters
cycle Cycle to get instruction index.
Returns
Return the instruction index for cycle.
Definition at line 249 of file ResourceBroker.cc.
{
    if (initiationInterval_ != 0) {
        return cycle % initiationInterval_;
    } else {
        return cycle;
    }
}
References initiationInterval_.
Referenced by BusBroker::allAvailableResources(), InputPSocketBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), ITemplateBroker::allAvailableResources(), BusBroker::assign(), InputPSocketBroker::assign(), ITemplateBroker::assign(), OutputPSocketBroker::assign(), ITemplateBroker::assignImmediate(), BusBroker::availableResource(), ITemplateBroker::findITemplates(), ITemplateBroker::instruction(), InputPSocketBroker::isAlreadyAssigned(), BusBroker::isAlreadyAssigned(), InputFUBroker::isAlreadyAssigned(), ITemplateBroker::isAlreadyAssigned(), OutputFUBroker::isAlreadyAssigned(), OutputPSocketBroker::isAlreadyAssigned(), BusBroker::isAnyResourceAvailable(), OutputPSocketBroker::isAnyResourceAvailable(), ITemplateBroker::isAnyResourceAvailable(), BusBroker::isAvailable(), BusBroker::isInUse(), and ITemplateBroker::unassignImmediate().
isAlreadyAssigned()
virtual bool ResourceBroker::isAlreadyAssigned (int cycle, const MoveNode & node, const TTAMachine::Bus * preassignedBus) const pure virtual
Implemented in InputPSocketBroker, BusBroker, ExecutionPipelineBroker, InputFUBroker, ITemplateBroker, IUBroker, OutputFUBroker, and OutputPSocketBroker.
Referenced by AssignmentPlan::backtrack(), PendingAssignment::forget(), AssignmentPlan::tryNextAssignment(), and PendingAssignment::undoAssignment().
isAnyResourceAvailable()
bool ResourceBroker::isAnyResourceAvailable (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const virtual
Return true if one of the resources managed by this broker is suitable for the request contained in the node and can be assigned to it in given cycle.
Parameters
cycle Cycle.
node Node.
Returns
True if one of the resources managed by this broker is suitable for the request contained in the node and can be assigned to it in given cycle.
Reimplemented in BusBroker, OutputPSocketBroker, IUBroker, and ITemplateBroker.
Definition at line 75 of file ResourceBroker.cc.
{
    for (ResourceMap::const_iterator resIter = resMap_.begin();
         resIter != resMap_.end(); resIter++) {
        // IUBroker overrides this so no need for immu check
        const SchedulingResource* res = (*resIter).second;
        if (res->isAvailable(cycle) && res->canAssign(cycle, node)) {
            return true;
        }
    }
    return false;
}
References SchedulingResource::canAssign(), SchedulingResource::isAvailable(), and resMap_.
isApplicable()
virtual bool ResourceBroker::isApplicable (const MoveNode & node, const TTAMachine::Bus * preassignedBus) const pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, ITemplateBroker, OutputPSocketBroker, OutputFUBroker, InputFUBroker, IUBroker, and InputPSocketBroker.
Referenced by AssignmentPlan::tryCachedAssignment().
isAvailable()
bool ResourceBroker::isAvailable (SchedulingResource & res, const MoveNode & node, int cycle, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const virtual
Tells whether the given resource is available for given node at given cycle.
Reimplemented in BusBroker.
Definition at line 158 of file ResourceBroker.cc.
{
    SchedulingResourceSet resources =
      allAvailableResources(cycle, node, bus, srcFU, dstFU,
                immWriteCycle, immu, immRegIndex);
    return resources.hasResource(res);
}
References allAvailableResources(), and resources().
isBusBroker()
bool ResourceBroker::isBusBroker () const virtual
Reimplemented in BusBroker.
Definition at line 303 of file ResourceBroker.cc.
{
    return false;
}
Referenced by SimpleBrokerDirector::busBroker().
isExecutionPipelineBroker()
bool ResourceBroker::isExecutionPipelineBroker () const virtual
Reimplemented in ExecutionPipelineBroker.
Definition at line 318 of file ResourceBroker.cc.
{
    return false;
}
Referenced by SimpleBrokerDirector::executionPipelineBroker().
isITemplateBroker()
bool ResourceBroker::isITemplateBroker () const virtual
Reimplemented in ITemplateBroker.
Definition at line 308 of file ResourceBroker.cc.
{
    return false;
}
Referenced by SimpleBrokerDirector::instructionTemplateBroker().
isIUBroker()
bool ResourceBroker::isIUBroker () const virtual
Reimplemented in IUBroker.
Definition at line 313 of file ResourceBroker.cc.
{
    return false;
}
Referenced by SimpleBrokerDirector::immediateUnitBroker().
latestCycle()
virtual int ResourceBroker::latestCycle (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, IUBroker, OutputFUBroker, OutputPSocketBroker, and ITemplateBroker.
machinePartOf()
const TTAMachine::MachinePart & ResourceBroker::machinePartOf (const SchedulingResource & r) const virtual
Return the machine part that models the given resource.
Parameters
r Scheduling resource.
Returns
The machine part that models the given resource.
Exceptions
KeyNotFound If no corresponding machine part is found or r is not one of the primary resources of this broker.
Definition at line 181 of file ResourceBroker.cc.
{
    const TTAMachine::MachinePart* machinePart = NULL;
    try {
        machinePart = MapTools::keyForValue<const MachinePart*>(resMap_, &r);
    } catch (const Exception& e) {
        string msg = "Machine part of for resource ";
        msg += r.name();
        msg += " not found!";
        throw KeyNotFound(__FILE__, __LINE__, __func__, msg);
    }
    return *machinePart;
}
References __func__, MapTools::keyForValue(), SchedulingResource::name(), and resMap_.
Referenced by BusBroker::allAvailableResources(), IUBroker::allAvailableResources(), BusBroker::assign(), InputFUBroker::assign(), InputPSocketBroker::assign(), ITemplateBroker::assign(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), IUBroker::assign(), ITemplateBroker::assignImmediate(), BusBroker::hasGuard(), ITemplateBroker::instruction(), BusBroker::isAvailable(), ITemplateBroker::reselectTemplate(), and OutputFUBroker::unassign().
resourceCount()
int ResourceBroker::resourceCount () const
Definition at line 298 of file ResourceBroker.cc.
{
    return resMap_.size();
}
References resMap_.
resourceMapper()
const ResourceMapper & ResourceBroker::resourceMapper () const protected
Return the resource mapper set for this broker.
Returns
The resource mapper set for this broker.
Definition at line 234 of file ResourceBroker.cc.
{
    return *resourceMapper_;
}
References resourceMapper_.
Referenced by InputFUBroker::allAvailableResources().
resourceOf()
SchedulingResource * ResourceBroker::resourceOf (const TTAMachine::MachinePart & mp) const inline
Referenced by BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), InputPSocketBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), IUBroker::allAvailableResources(), ITemplateBroker::assign(), IUBroker::assign(), ITemplateBroker::assignImmediate(), ExecutionPipelineBroker::earliestFromSource(), ITemplateBroker::findITemplates(), InputPSocketBroker::isAlreadyAssigned(), ITemplateBroker::isAlreadyAssigned(), OutputPSocketBroker::isAlreadyAssigned(), OutputPSocketBroker::isAnyResourceAvailable(), BusBroker::isAvailable(), BusBroker::isInUse(), ExecutionPipelineBroker::latestFromSource(), BusBroker::setupResourceLinks(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), BusBroker::unassign(), InputFUBroker::unassign(), InputPSocketBroker::unassign(), OutputFUBroker::unassign(), and ITemplateBroker::unassignImmediate().
resources()
void ResourceBroker::resources (ResourceSet & contents)
Get resources
Parameters
contents Set to which resources are copied to.
Definition at line 279 of file ResourceBroker.cc.
{
    for (ResourceMap::iterator i = resMap_.begin(); i != resMap_.end(); ++i ) {
        contents.insert(i->second);
    }
}
References resMap_.
Referenced by ITemplateBroker::assignImmediate(), isAvailable(), and ITemplateBroker::reselectTemplate().
setInitiationInterval()
void ResourceBroker::setInitiationInterval (unsigned int ii) virtual
Set initiation interval, if ii = 0 then initiation interval is not used.
Parameters
ii initiation interval
Reimplemented in ExecutionPipelineBroker.
Definition at line 292 of file ResourceBroker.cc.
{
    initiationInterval_ = ii;
}
References initiationInterval_.
Referenced by ExecutionPipelineBroker::ExecutionPipelineBroker().
setMaxCycle()
virtual void ResourceBroker::setMaxCycle (unsigned int) inline virtual
Reimplemented in ExecutionPipelineBroker.
Definition at line 147 of file ResourceBroker.hh.
{};
setResourceMapper()
void ResourceBroker::setResourceMapper (const ResourceMapper & mapper) protected
Set the resource mapper for this broker.
Parameters
mapper Resource mapper.
Definition at line 224 of file ResourceBroker.cc.
{
    resourceMapper_ = &mapper;
}
References resourceMapper_.
Referenced by BusBroker::setupResourceLinks(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), InputPSocketBroker::setupResourceLinks(), ITemplateBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), and OutputPSocketBroker::setupResourceLinks().
setupResourceLinks()
virtual void ResourceBroker::setupResourceLinks (const ResourceMapper & mapper) pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, ITemplateBroker, IUBroker, OutputFUBroker, and OutputPSocketBroker.
unassign()
virtual void ResourceBroker::unassign (MoveNode & node) pure virtual
Implemented in BusBroker, ExecutionPipelineBroker, InputFUBroker, InputPSocketBroker, ITemplateBroker, IUBroker, OutputFUBroker, and OutputPSocketBroker.
Referenced by PendingAssignment::forget(), and PendingAssignment::undoAssignment().
validateResources()
void ResourceBroker::validateResources () const
Tests if is each resource has correct related and dependent groups.
Exceptions
ModuleRunTimeError in case resource does not have correct related or dependent resources.
Definition at line 329 of file ResourceBroker.cc.
{
    ResourceMap::const_iterator itr = resMap_.begin();
    while (itr != resMap_.end()) {
        if (!(*itr).second->validateDependentGroups()) {
            std::string msg = (boost::format(
                "Broker '%s' failed to validate DependentGroup for '%s'!") %
                brokerName() % (*itr).second->name()).str();
            throw ModuleRunTimeError(__FILE__, __LINE__, __func__, msg);
        }
        if (!(*itr).second->validateRelatedGroups()){
            std::string msg = (boost::format(
                "Broker '%s' failed to validate RelatedGroup for '%s'!") %
                brokerName() % (*itr).second->name()).str();
            throw ModuleRunTimeError(__FILE__, __LINE__, __func__, msg);
        }
        ++itr;
    }
    return;
}
References __func__, brokerName(), and resMap_.
Member Data Documentation
assignedResources_
MoveResMap ResourceBroker::assignedResources_ protected
Definition at line 167 of file ResourceBroker.hh.
Referenced by BusBroker::assign(), InputFUBroker::assign(), InputPSocketBroker::assign(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), IUBroker::assign(), clear(), IUBroker::immediateValue(), IUBroker::immediateWriteCycle(), InputPSocketBroker::isAlreadyAssigned(), BusBroker::isAlreadyAssigned(), InputFUBroker::isAlreadyAssigned(), IUBroker::isAlreadyAssigned(), OutputFUBroker::isAlreadyAssigned(), OutputPSocketBroker::isAlreadyAssigned(), BusBroker::unassign(), InputFUBroker::unassign(), InputPSocketBroker::unassign(), IUBroker::unassign(), OutputFUBroker::unassign(), and OutputPSocketBroker::unassign().
brokerName_
std::string ResourceBroker::brokerName_ protected
Definition at line 168 of file ResourceBroker.hh.
Referenced by brokerName().
initiationInterval_
unsigned int ResourceBroker::initiationInterval_ protected
Definition at line 158 of file ResourceBroker.hh.
Referenced by IUBroker::allAvailableResources(), BusBroker::buildResources(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), InputPSocketBroker::buildResources(), ITemplateBroker::buildResources(), IUBroker::buildResources(), OutputPSocketBroker::buildResources(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), instructionIndex(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), setInitiationInterval(), ExecutionPipelineBroker::setInitiationInterval(), and BusBroker::setupResourceLinks().
resMap_
ResourceMap ResourceBroker::resMap_ protected
Definition at line 165 of file ResourceBroker.hh.
Referenced by addResource(), BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), IUBroker::allAvailableResources(), availableResource(), BusBroker::canTransportImmediate(), clear(), IUBroker::clearOldResources(), ITemplateBroker::findITemplates(), BusBroker::hasGuard(), hasResource(), hasResourceOf(), ExecutionPipelineBroker::highestKnownCycle(), isAnyResourceAvailable(), machinePartOf(), resourceCount(), resources(), ExecutionPipelineBroker::setDDG(), BusBroker::setupResourceLinks(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), InputPSocketBroker::setupResourceLinks(), ITemplateBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), validateResources(), and ~ResourceBroker().
resourceMapper_
const ResourceMapper* ResourceBroker::resourceMapper_ protected
Definition at line 166 of file ResourceBroker.hh.
Referenced by resourceMapper(), and setResourceMapper().
The documentation for this class was generated from the following files:
ResourceBroker.hh
ResourceBroker.cc