OpenASIP: HDB::CostFunctionPlugin Class Reference
HDB::CostFunctionPlugin Class Reference
#include <CostFunctionPlugin.hh>
Public Types
enum CostFunctionPluginType { COST_FU , COST_RF , COST_DECOMP , COST_ICDEC }
all supported cost function plugin types
Public Member Functions
CostFunctionPlugin (int id, const std::string &description, const std::string &name, const std::string &pluginFilePath, CostFunctionPluginType type)
virtual ~CostFunctionPlugin ()
int id () const
std::string description () const
std::string name () const
std::string pluginFilePath () const
CostFunctionPluginType type () const
Private Attributes
int id_
id of the plugin in HDB
std::string description_
description of the plugin HDB
std::string name_
(the class) name of the plugin
std::string pluginFilePath_
the path in the file system of the plugin
CostFunctionPluginType type_
the type of the plugin
Detailed Description
Class that contains data stored in HDB of a cost function plugin.
Definition at line 43 of file CostFunctionPlugin.hh.
Member Enumeration Documentation
CostFunctionPluginType
enum HDB::CostFunctionPlugin::CostFunctionPluginType
all supported cost function plugin types
Enumerator
COST_FU
function unit cost estimator
COST_RF
register file cost estimator
COST_DECOMP
decompressor cost estimator
COST_ICDEC
interconnection network & decoder cost estimator
Definition at line 46 of file CostFunctionPlugin.hh.
{
        COST_FU,     ///< function unit cost estimator
        COST_RF,     ///< register file cost estimator
        COST_DECOMP, ///< decompressor cost estimator
        COST_ICDEC   ///< interconnection network & decoder cost estimator
    };
Constructor & Destructor Documentation
CostFunctionPlugin()
HDB::CostFunctionPlugin::CostFunctionPlugin (int id, const std::string & description, const std::string & name, const std::string & pluginFilePath, CostFunctionPluginType type)
Constructor.
Parameters
pluginFilePath Path of the plugin.
Definition at line 42 of file CostFunctionPlugin.cc.
                                 :
    id_(id), description_(description), name_(name),
    pluginFilePath_(pluginFilePath), type_(type) {
}
~CostFunctionPlugin()
HDB::CostFunctionPlugin::~CostFunctionPlugin () virtual
Destructor.
Definition at line 55 of file CostFunctionPlugin.cc.
{
}
Member Function Documentation
description()
std::string HDB::CostFunctionPlugin::description () const
Returns the description of the plugin.
Returns
Description of the plugin.
Definition at line 74 of file CostFunctionPlugin.cc.
{
    return description_;
}
References description_.
Referenced by HDB::HDBManager::addCostFunctionPlugin(), CostFunctionPluginDialog::CostFunctionPluginDialog(), HDBToHtml::costFunctionPluginToHtml(), and HDB::HDBManager::modifyCostFunctionPlugin().
id()
int HDB::CostFunctionPlugin::id () const
Returns the id of the plugin.
Returns
Id of the plugin.
Definition at line 64 of file CostFunctionPlugin.cc.
{
    return id_;
}
References id_.
Referenced by CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), HDBToHtml::fuEntryToHtml(), and HDBToHtml::rfEntryToHtml().
name()
std::string HDB::CostFunctionPlugin::name () const
Returns the (class) name of the plugin.
Returns
Name of the plugin.
Definition at line 84 of file CostFunctionPlugin.cc.
{
    return name_;
}
References name_.
Referenced by HDB::HDBManager::addCostFunctionPlugin(), CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), CostFunctionPluginDialog::CostFunctionPluginDialog(), HDBToHtml::costFunctionPluginToHtml(), SetCostFunctionPluginCmd::Do(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), HDBToHtml::fuEntryToHtml(), HDB::HDBManager::modifyCostFunctionPlugin(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), HDBToHtml::rfEntryToHtml(), and HDBBrowserWindow::update().
pluginFilePath()
std::string HDB::CostFunctionPlugin::pluginFilePath () const
Returns the path of the plugin file.
Returns
Path of the plugin.
Definition at line 94 of file CostFunctionPlugin.cc.
{
    return pluginFilePath_;
}
References pluginFilePath_.
Referenced by HDB::HDBManager::addCostFunctionPlugin(), CostFunctionPluginDialog::CostFunctionPluginDialog(), HDBToHtml::costFunctionPluginToHtml(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), HDB::HDBManager::modifyCostFunctionPlugin(), and CostEstimator::Estimator::rfCostFunctionPluginOfImplementation().
type()
CostFunctionPlugin::CostFunctionPluginType HDB::CostFunctionPlugin::type () const
Returns the type of the plugin.
Returns
Description of the plugin.
Definition at line 104 of file CostFunctionPlugin.cc.
{
    return type_;
}
References type_.
Referenced by HDB::HDBManager::addCostFunctionPlugin(), CostFunctionPluginDialog::CostFunctionPluginDialog(), HDBToHtml::costFunctionPluginToHtml(), and HDB::HDBManager::modifyCostFunctionPlugin().
Member Data Documentation
description_
std::string HDB::CostFunctionPlugin::description_ private
description of the plugin HDB
Definition at line 71 of file CostFunctionPlugin.hh.
Referenced by description().
id_
int HDB::CostFunctionPlugin::id_ private
id of the plugin in HDB
Definition at line 69 of file CostFunctionPlugin.hh.
Referenced by id().
name_
std::string HDB::CostFunctionPlugin::name_ private
(the class) name of the plugin
Definition at line 73 of file CostFunctionPlugin.hh.
Referenced by name().
pluginFilePath_
std::string HDB::CostFunctionPlugin::pluginFilePath_ private
the path in the file system of the plugin
Definition at line 75 of file CostFunctionPlugin.hh.
Referenced by pluginFilePath().
type_
CostFunctionPluginType HDB::CostFunctionPlugin::type_ private
the type of the plugin
Definition at line 77 of file CostFunctionPlugin.hh.
Referenced by type().
The documentation for this class was generated from the following files:
CostFunctionPlugin.hh
CostFunctionPlugin.cc