OpenASIP: FUReservationTableIndex Class Reference
FUReservationTableIndex Class Reference
#include <FUReservationTableIndex.hh>
Public Member Functions
FUReservationTableIndex (const TTAMachine::FunctionUnit &functionUnit)
virtual ~FUReservationTableIndex ()
ReservationTable & at (std::size_t operation)
std::size_t size () const
Private Attributes
std::vector< ReservationTable * > tables_
Stores all reservation tables.
Detailed Description
Represents an index of reservation tables for modeling resource usage of operations in an FU.
Definition at line 47 of file FUReservationTableIndex.hh.
Constructor & Destructor Documentation
FUReservationTableIndex()
FUReservationTableIndex::FUReservationTableIndex (const TTAMachine::FunctionUnit & functionUnit)
Builds reservation tables for all operations in the FU.
Tables are stored in the order returned by FunctionUnit::operation(), the NOP matrix is at index FunctionUnit::operationCount().
Parameters
functionUnit The FU to build the matrices for.
Definition at line 47 of file FUReservationTableIndex.cc.
{
    for (int i = 0; i < functionUnit.operationCount(); ++i) {
        const TTAMachine::HWOperation& operation =
            *functionUnit.operation(i);
        tables_.push_back(new ReservationTable(operation));
    }
}
References TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), and tables_.
~FUReservationTableIndex()
FUReservationTableIndex::~FUReservationTableIndex () virtual
Destructor.
Definition at line 60 of file FUReservationTableIndex.cc.
{
    SequenceTools::deleteAllItems(tables_);
}
References SequenceTools::deleteAllItems(), and tables_.
Member Function Documentation
at()
ReservationTable & FUReservationTableIndex::at (std::size_t index)
Returns the reservation table at the given index.
Parameters
operation The index of the reservation table.
Definition at line 70 of file FUReservationTableIndex.cc.
{
    return *tables_.at(index);
}
References tables_.
Referenced by CollisionMatrix::CollisionMatrix().
size()
std::size_t FUReservationTableIndex::size () const
Returns the count of reservation tables in the index.
Returns
The count of reservation tables in the index.
Definition at line 80 of file FUReservationTableIndex.cc.
{
    return tables_.size();
}
References tables_.
Member Data Documentation
tables_
std::vector<ReservationTable*> FUReservationTableIndex::tables_ private
Stores all reservation tables.
Definition at line 56 of file FUReservationTableIndex.hh.
Referenced by at(), FUReservationTableIndex(), size(), and ~FUReservationTableIndex().
The documentation for this class was generated from the following files:
FUReservationTableIndex.hh
FUReservationTableIndex.cc