OpenASIP: OperationImplementationResourceDialog Class Reference
OperationImplementationResourceDialog Class Reference
#include <OperationImplementationResourceDialog.hh>
Public Member Functions
OperationImplementationResourceDialog ()
virtual ~OperationImplementationResourceDialog ()=default
void onOK (wxCommandEvent &)
void onAddVhdlSynFile (wxFileDirPickerEvent &)
void onAddVhdlSimFile (wxFileDirPickerEvent &)
void onAddVerilogSynFile (wxFileDirPickerEvent &)
void onAddVerilogSimFile (wxFileDirPickerEvent &)
void onDeleteListItem (wxCommandEvent &)
Private Member Functions
std::string sanitize (const wxString &path)
Private Attributes
wxListCtrl * fileList1_
wxTextCtrl * nameCtrl_
wxFilePickerCtrl * ipxactPick_
Detailed Description
Definition at line 44 of file OperationImplementationResourceDialog.hh.
Constructor & Destructor Documentation
OperationImplementationResourceDialog()
OperationImplementationResourceDialog::OperationImplementationResourceDialog ()
~OperationImplementationResourceDialog()
virtual OperationImplementationResourceDialog::~OperationImplementationResourceDialog () virtual default
Member Function Documentation
onAddVerilogSimFile()
void OperationImplementationResourceDialog::onAddVerilogSimFile (wxFileDirPickerEvent & e)
Definition at line 251 of file OperationImplementationResourceDialog.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    int idx = fileList1_->GetItemCount();
    fileList1_->InsertItem(idx, sanitize(e.GetPath()));
    fileList1_->SetItem(idx, 1, manager->formatString(
                HDB::BlockImplementationFile::Verilogsim));
}
References fileList1_, HDB::HDBManager::formatString(), sanitize(), and HDB::BlockImplementationFile::Verilogsim.
onAddVerilogSynFile()
void OperationImplementationResourceDialog::onAddVerilogSynFile (wxFileDirPickerEvent & e)
Definition at line 241 of file OperationImplementationResourceDialog.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    int idx = fileList1_->GetItemCount();
    fileList1_->InsertItem(idx, sanitize(e.GetPath()));
    fileList1_->SetItem(idx, 1, manager->formatString(
                HDB::BlockImplementationFile::Verilog));
}
References fileList1_, HDB::HDBManager::formatString(), sanitize(), and HDB::BlockImplementationFile::Verilog.
onAddVhdlSimFile()
void OperationImplementationResourceDialog::onAddVhdlSimFile (wxFileDirPickerEvent & e)
Definition at line 231 of file OperationImplementationResourceDialog.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    int idx = fileList1_->GetItemCount();
    fileList1_->InsertItem(idx, sanitize(e.GetPath()));
    fileList1_->SetItem(idx, 1, manager->formatString(
                HDB::BlockImplementationFile::VHDLsim));
}
References fileList1_, HDB::HDBManager::formatString(), sanitize(), and HDB::BlockImplementationFile::VHDLsim.
onAddVhdlSynFile()
void OperationImplementationResourceDialog::onAddVhdlSynFile (wxFileDirPickerEvent & e)
Definition at line 221 of file OperationImplementationResourceDialog.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    int idx = fileList1_->GetItemCount();
    fileList1_->InsertItem(idx, sanitize(e.GetPath()));
    fileList1_->SetItem(idx, 1, manager->formatString(
                HDB::BlockImplementationFile::VHDL));
}
References fileList1_, HDB::HDBManager::formatString(), sanitize(), and HDB::BlockImplementationFile::VHDL.
onDeleteListItem()
void OperationImplementationResourceDialog::onDeleteListItem (wxCommandEvent &)
Definition at line 261 of file OperationImplementationResourceDialog.cc.
{
    long item = -1;
    for (;;)
    {
        item = fileList1_->GetNextItem(
            item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        if (item == -1)
            break;
        fileList1_->DeleteItem(item);
        if (fileList1_->GetItemCount() == 0 ||
            item == fileList1_->GetItemCount())
            break;
    }
}
References fileList1_.
onOK()
void OperationImplementationResourceDialog::onOK (wxCommandEvent &)
Definition at line 152 of file OperationImplementationResourceDialog.cc.
{
    HDB::OperationImplementationResource resource;
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    resource.name = nameCtrl_->GetLineText(0);
    if (resource.name.length() < 1) {
        wxMessageBox( wxT("Give the resource a name."),
            wxT("Error"), wxICON_ERROR);
            return;
    }
    long items = fileList1_->GetItemCount();
    for (int i = 0; i < items; ++i) {
        std::string file = fileList1_->GetItemText(i, 0).ToStdString();
        std::string type = fileList1_->GetItemText(i, 1).ToStdString();
        if (type == manager->formatString(
                HDB::BlockImplementationFile::VHDL)) {
            resource.synFiles.emplace_back(file);
            resource.synFormats.emplace_back(type);
        } else if (type == manager->formatString(
                HDB::BlockImplementationFile::VHDLsim)) {
            resource.simFiles.emplace_back(file);
            resource.simFormats.emplace_back(type);
        }
        else if (type == manager->formatString(
                HDB::BlockImplementationFile::Verilog)) {
            resource.synFiles.emplace_back(file);
            resource.synFormats.emplace_back(type);
        }
        else if (type == manager->formatString(
                HDB::BlockImplementationFile::Verilogsim)) {
            resource.simFiles.emplace_back(file);
            resource.simFormats.emplace_back(type);
        } else {
            wxMessageBox( wxT("Unknown file type."),
            wxT("Error"), wxICON_ERROR);
            return;
        }
    }
    resource.ipxact = sanitize(ipxactPick_->GetPath());
    if (resource.ipxact.length() < 1) {
        wxMessageBox(wxT("Give the IP-XACT component file."),
            wxT("Error"), wxICON_ERROR);
        return;
    }
    manager->addOperationImplementationResource(resource);
    wxGetApp().mainFrame().browser()->update();
    EndModal(wxID_OK);
}
References HDB::HDBManager::addOperationImplementationResource(), fileList1_, HDB::HDBManager::formatString(), HDB::OperationImplementationResource::ipxact, ipxactPick_, HDB::OperationImplementationResource::name, nameCtrl_, sanitize(), HDB::OperationImplementationResource::simFiles, HDB::OperationImplementationResource::simFormats, HDB::OperationImplementationResource::synFiles, HDB::OperationImplementationResource::synFormats, HDB::BlockImplementationFile::Verilog, HDB::BlockImplementationFile::Verilogsim, HDB::BlockImplementationFile::VHDL, and HDB::BlockImplementationFile::VHDLsim.
sanitize()
std::string OperationImplementationResourceDialog::sanitize (const wxString & path) private
Definition at line 205 of file OperationImplementationResourceDialog.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    std::string es(path);
    std::string s(manager->fileName());
    size_t i = s.rfind('/', s.length());
    if (i != std::string::npos) {
        s = s.substr(0, i+1);
        if (es.find(s) == 0) {
            return es.substr(s.length());
        }
    }
    return es;
}
References HDB::HDBManager::fileName().
Referenced by onAddVerilogSimFile(), onAddVerilogSynFile(), onAddVhdlSimFile(), onAddVhdlSynFile(), and onOK().
Member Data Documentation
fileList1_
wxListCtrl* OperationImplementationResourceDialog::fileList1_ private
Definition at line 58 of file OperationImplementationResourceDialog.hh.
Referenced by onAddVerilogSimFile(), onAddVerilogSynFile(), onAddVhdlSimFile(), onAddVhdlSynFile(), onDeleteListItem(), and onOK().
ipxactPick_
wxFilePickerCtrl* OperationImplementationResourceDialog::ipxactPick_ private
Definition at line 60 of file OperationImplementationResourceDialog.hh.
Referenced by onOK().
nameCtrl_
wxTextCtrl* OperationImplementationResourceDialog::nameCtrl_ private
Definition at line 59 of file OperationImplementationResourceDialog.hh.
Referenced by onOK().
The documentation for this class was generated from the following files:
OperationImplementationResourceDialog.hh
OperationImplementationResourceDialog.cc