OpenASIP: OSEdInfoView Class Reference
OSEdInfoView Class Reference
#include <OSEdInfoView.hh>
Public Member Functions
OSEdInfoView (wxWindow *parent)
virtual ~OSEdInfoView ()
void clear ()
void pathView ()
void moduleView (const std::string &name)
void operationView (const std::string &path, const std::string &mod)
void operationPropertyView (const std::string &opName, const std::string &modName, const std::string &pathName)
std::string selectedPath ()
std::string selectedModule ()
std::string selectedOperation ()
Private Types
enum InfoMode {
MODE_NOMODE , MODE_PATH , MODE_MODULE , MODE_OPERATION ,
MODE_PROPERTY
}
Private Member Functions
void onSelection (wxListEvent &event)
void onDropDownMenu (wxMouseEvent &event)
void insertOperationPropertyColumns ()
int writeStaticPropertiesOfOperation (Operation *op)
Private Attributes
InfoMode mode_
Mode of the info view.
Detailed Description
Models an info screen.
Info screen shows info about search paths, modules, and operations.
Definition at line 47 of file OSEdInfoView.hh.
Member Enumeration Documentation
InfoMode
enum OSEdInfoView::InfoMode private
Possible modes of info view.
Enumerator
MODE_NOMODE
Initial state.
MODE_PATH
Path view.
MODE_MODULE
Module view.
MODE_OPERATION
Operation View.
MODE_PROPERTY
Operation property view.
Definition at line 75 of file OSEdInfoView.hh.
                  {
        MODE_NOMODE,    ///< Initial state.
        MODE_PATH,      ///< Path view.
        MODE_MODULE,    ///< Module view.
        MODE_OPERATION, ///< Operation View.
        MODE_PROPERTY   ///< Operation property view.
    };
Constructor & Destructor Documentation
OSEdInfoView()
OSEdInfoView::OSEdInfoView (wxWindow * parent)
Constructor.
Parameters
parent Parent window.
Definition at line 68 of file OSEdInfoView.cc.
                                           :
    wxListCtrl(
        parent, OSEdConstants::CMD_INFO_VIEW, wxDefaultPosition,
        wxSize(400,400),
        wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER), mode_(MODE_NOMODE) {
}
~OSEdInfoView()
OSEdInfoView::~OSEdInfoView () virtual
Destructor.
Definition at line 79 of file OSEdInfoView.cc.
{
}
Member Function Documentation
clear()
void OSEdInfoView::clear ()
Clears the info screen.
Definition at line 86 of file OSEdInfoView.cc.
                    {
    int columns = GetColumnCount();
    for (int i = 0; i < columns; i++) {
        DeleteColumn(0);
    }
    DeleteAllItems();
}
Referenced by moduleView(), operationPropertyView(), operationView(), and pathView().
insertOperationPropertyColumns()
void OSEdInfoView::insertOperationPropertyColumns () private
Inserts columns in operation property view.
Definition at line 372 of file OSEdInfoView.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_PROPERTY);
    InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_VALUE);
    InsertColumn(
        1, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_OPERAND_VALUE);
    InsertColumn(
        2, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
}
References OSEdConstants::DEFAULT_COLUMN_WIDTH, OSEdTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_COLUMN_OPERAND_VALUE, OSEdTextGenerator::TXT_COLUMN_PROPERTY, and OSEdTextGenerator::TXT_COLUMN_VALUE.
Referenced by operationPropertyView().
moduleView()
void OSEdInfoView::moduleView (const std::string & name)
Shows the module view.
Parameters
The name of the path.
Definition at line 129 of file OSEdInfoView.cc.
{
    OperationIndex& index = OperationContainer::operationIndex();
    clear();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_MODULES);
    InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    int modules = 0;
    try {
        modules = index.moduleCount(name);
    } catch (const PathNotFound& p) {
        // path not found
    }
    for (int i = 0; i < modules; i++) {
        OperationModule& module = index.module(i, name);
        InsertItem(i, WxConversion::toWxString(module.name()));
    }
    mode_ = MODE_MODULE;
}
References clear(), OSEdConstants::DEFAULT_COLUMN_WIDTH, OSEdTextGenerator::instance(), mode_, MODE_MODULE, OperationIndex::moduleCount(), OperationContainer::operationIndex(), Texts::TextGenerator::text(), WxConversion::toWxString(), and OSEdTextGenerator::TXT_COLUMN_MODULES.
Referenced by OSEdRemoveModuleCmd::Do(), OSEdTreeView::onItemSelected(), and OSEdTreeView::update().
onDropDownMenu()
void OSEdInfoView::onDropDownMenu (wxMouseEvent & event) private
Handles the event when list item is clicked with right mouse button.
Then the drop down menu is shown.
Parameters
event Event to be handled.
Definition at line 579 of file OSEdInfoView.cc.
{
    if (GetSelectedItemCount() <= 1 && mode_ != MODE_PROPERTY) {
        // deselect the selected item
        long item = -1;
        item = GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        if (item != -1) {
            SetItemState(item, 0, wxLIST_STATE_SELECTED);
        }
        wxPoint pos = event.GetPosition();
        int flags = wxLIST_HITTEST_ONITEMLABEL;
        item = -1;
        item = HitTest(pos, flags);
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
        DropDownMenu* menu = NULL;
        if (item != -1) {
            // select the item that was clicked
            SetItemState(item, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
            switch(mode_) {
            case MODE_PATH: {
                format fmt =
                    texts.text(OSEdTextGenerator::TXT_STATUS_PATH_SELECTED);
                mainFrame->statusBar()->
                    SetStatusText(WxConversion::toWxString(fmt.str()));
                menu = new DropDownMenu(DropDownMenu::MENU_PATH);
                PopupMenu(menu, pos);
            }
                break;
            case MODE_MODULE: {
                format fmt =
                    texts.text(OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED);
                mainFrame->statusBar()->
                    SetStatusText(WxConversion::toWxString(fmt.str()));
                menu = new DropDownMenu(DropDownMenu::MENU_MODULE);
                PopupMenu(menu, pos);
            }
                break;
            case MODE_OPERATION: {
                format fmt =
                    texts.text(OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED);
                mainFrame->statusBar()->
                    SetStatusText(WxConversion::toWxString(fmt.str()));
                menu = new DropDownMenu(DropDownMenu::MENU_OPERATION);
                PopupMenu(menu, pos);
            }
                break;
            default:
                break;
            }
        }
        delete menu;
    }
}
References OSEdTextGenerator::instance(), DropDownMenu::MENU_MODULE, DropDownMenu::MENU_OPERATION, DropDownMenu::MENU_PATH, mode_, MODE_MODULE, MODE_OPERATION, MODE_PATH, MODE_PROPERTY, OSEdMainFrame::statusBar(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED, OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED, and OSEdTextGenerator::TXT_STATUS_PATH_SELECTED.
onSelection()
void OSEdInfoView::onSelection (wxListEvent & event) private
Handles the event when list item is selected.
Definition at line 538 of file OSEdInfoView.cc.
{
    if (GetSelectedItemCount() == 1) {
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
        mainFrame->updateMenuBar();
        switch (mode_) {
        case MODE_PATH: {
            format fmt =
                texts.text(OSEdTextGenerator::TXT_STATUS_PATH_SELECTED);
            mainFrame->statusBar()->
                SetStatusText(WxConversion::toWxString(fmt.str()));
        }
            break;
        case MODE_MODULE: {
            format fmt =
                texts.text(OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED);
            mainFrame->statusBar()->
                SetStatusText(WxConversion::toWxString(fmt.str()));
        }
            break;
        case MODE_OPERATION: {
            format fmt =
                texts.text(OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED);
            mainFrame->statusBar()->
                SetStatusText(WxConversion::toWxString(fmt.str()));
        }
            break;
        default:
            break;
        }
    }
}
References OSEdTextGenerator::instance(), mode_, MODE_MODULE, MODE_OPERATION, MODE_PATH, OSEdMainFrame::statusBar(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED, OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED, OSEdTextGenerator::TXT_STATUS_PATH_SELECTED, and OSEdMainFrame::updateMenuBar().
operationPropertyView()
void OSEdInfoView::operationPropertyView (const std::string & opName, const std::string & modName, const std::string & pathName)
Shows the operation properties of an operation.
Parameters
opName The name of the operation.
modName The name of the module.
pathName The name of the path.
Definition at line 202 of file OSEdInfoView.cc.
{
    clear();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format yesFmt = texts.text(OSEdTextGenerator::TXT_ROW_YES);
    format noFmt = texts.text(OSEdTextGenerator::TXT_ROW_NO);
    format trueFmt = texts.text(OSEdTextGenerator::TXT_ROW_TRUE);
    format falseFmt = texts.text(OSEdTextGenerator::TXT_ROW_FALSE);
    Operation* op = OperationContainer::operation(pathName, modName, opName);
    // insert columns
    insertOperationPropertyColumns();
    if (op == NULL) {
        // operation properties can not be loaded
        return;
    }
    // write "static" properties
    int i = writeStaticPropertiesOfOperation(op);
    format fmt;
    // affected by
    for (int k = 0; k < op->affectedByCount(); k++) {
        if (k == 0) {
            fmt = texts.text(OSEdTextGenerator::TXT_ROW_AFFECTED_BY);
            InsertItem(i, WxConversion::toWxString(fmt.str()));
        } else {
            InsertItem(i, _T(""));
        }
        SetItem(i, 1, WxConversion::toWxString(op->affectedBy(k)));
        i++;
    }
    // affects
    for (int k = 0; k < op->affectsCount(); k++) {
        if (k == 0) {
            fmt = texts.text(OSEdTextGenerator::TXT_ROW_AFFECTS);
            InsertItem(i, WxConversion::toWxString(fmt.str()));
        } else {
            InsertItem(i, _T(""));
        }
        SetItem(i, 1, WxConversion::toWxString(op->affects(k)));
        i++;
    }
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_INPUT_OPERANDS);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    i++;
    // input operands
    for (int j = 1; j <= op->numberOfInputs(); j++) {
        Operand& operand = op->operand(j);
        InsertItem(i, _T(""));
        wxString index = WxConversion::toWxString(j);
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_ID);
        index.Prepend(WxConversion::toWxString(fmt.str()));
        SetItem(i, 1, index);
        i++;
        InsertItem(i, _T(""));
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_TYPE);
        SetItem(i, 1, WxConversion::toWxString(fmt.str()));
        SetItem(i, 2, WxConversion::toWxString(operand.typeString()));
        i++;
        InsertItem(i, _T(""));
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_MEMORY_ADDRESS);
        SetItem(i, 1, WxConversion::toWxString(fmt.str()));
        // is operand address?
        if (operand.isAddress()) {
            SetItem(i, 2, WxConversion::toWxString(yesFmt.str()));
        } else {
            SetItem(i, 2, WxConversion::toWxString(noFmt.str()));
        }
        i++;
        InsertItem(i, _T(""));
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_MEMORY_DATA);
        SetItem(i, 1, WxConversion::toWxString(fmt.str()));
        // is operand memory data?
        if (operand.isMemoryData()) {
            SetItem(i, 2, WxConversion::toWxString(yesFmt.str()));
        } else {
            SetItem(i, 2, WxConversion::toWxString(noFmt.str()));
        }
        i++;
        set<int> canSwap = operand.swap();
        set<int>::iterator it = canSwap.begin();
        // can swap list
        while (it != canSwap.end()) {
            wxString opId = WxConversion::toWxString(*it);
            opId.Prepend(_T("id: "));
            if (it == canSwap.begin()) {
                InsertItem(i, _T(""));
                fmt = texts.text(OSEdTextGenerator::TXT_ROW_CAN_SWAP);
                SetItem(i, 1, WxConversion::toWxString(fmt.str()));
                SetItem(i, 2, opId);
            } else {
                InsertItem(i, _T(""));
                SetItem(i, 2, opId);
            }
            i++;
            it++;
        }
    }
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_OUTPUT_OPERANDS);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    i++;
    // outputs
    for (int j = op->numberOfInputs() + 1;
         j <= op->numberOfOutputs() + op->numberOfInputs(); j++) {
        Operand& operand = op->operand(j);
        InsertItem(i, _T(""));
        wxString opId = WxConversion::toWxString(j);
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_ID);
        opId.Prepend(WxConversion::toWxString(fmt.str()));
        SetItem(i, 1, opId);
        i++;
        InsertItem(i, _T(""));
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_TYPE);
        SetItem(i, 1, WxConversion::toWxString(fmt.str()));
        SetItem(i, 2, WxConversion::toWxString(operand.typeString()));
        i++;
        InsertItem(i, _T(""));
        fmt = texts.text(OSEdTextGenerator::TXT_ROW_MEMORY_DATA);
        SetItem(i, 1, WxConversion::toWxString(fmt.str()));
        // is operand memory data?
        if (operand.isMemoryData()) {
            SetItem(i, 2, WxConversion::toWxString(yesFmt.str()));
        } else {
            SetItem(i, 2, WxConversion::toWxString(noFmt.str()));
        }
        i++;
    }
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_HAS_BEHAVIOR);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->canBeSimulated()) {
        SetItem(i, 1, WxConversion::toWxString(yesFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(noFmt.str()));
    }
    delete op;
    mode_ = MODE_PROPERTY;
}
References Operation::affectedBy(), Operation::affectedByCount(), Operation::affects(), Operation::affectsCount(), Operation::canBeSimulated(), clear(), insertOperationPropertyColumns(), OSEdTextGenerator::instance(), Operand::isAddress(), Operand::isMemoryData(), mode_, MODE_PROPERTY, Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::operand(), OperationContainer::operation(), Operand::swap(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ROW_AFFECTED_BY, OSEdTextGenerator::TXT_ROW_AFFECTS, OSEdTextGenerator::TXT_ROW_CAN_SWAP, OSEdTextGenerator::TXT_ROW_FALSE, OSEdTextGenerator::TXT_ROW_HAS_BEHAVIOR, OSEdTextGenerator::TXT_ROW_ID, OSEdTextGenerator::TXT_ROW_INPUT_OPERANDS, OSEdTextGenerator::TXT_ROW_MEMORY_ADDRESS, OSEdTextGenerator::TXT_ROW_MEMORY_DATA, OSEdTextGenerator::TXT_ROW_NO, OSEdTextGenerator::TXT_ROW_OUTPUT_OPERANDS, OSEdTextGenerator::TXT_ROW_TRUE, OSEdTextGenerator::TXT_ROW_TYPE, OSEdTextGenerator::TXT_ROW_YES, Operand::typeString(), and writeStaticPropertiesOfOperation().
Referenced by OSEdTreeView::onItemSelected(), and OSEdTreeView::update().
operationView()
void OSEdInfoView::operationView (const std::string & path, const std::string & mod)
Shows the operation view.
Parameters
path The path of the module.
mod The name of the module.
Definition at line 161 of file OSEdInfoView.cc.
{
    OperationIndex& index = OperationContainer::operationIndex();
    OperationModule& module = OperationContainer::module(path, mod);
    clear();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_OPERATIONS);
    InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    int operations = 0;
    try {
        operations = index.operationCount(module);
    } catch (const Exception& e) {
        return;
    }
    for (int j = 0; j < operations; j++) {
        string name = index.operationName(j, module);
        wxListItem item;
        if (OperationContainer::isEffective(module, name)) {
            // operation is effective, let's put it with bold font
            wxFont boldFont = wxFont(10, wxROMAN, wxNORMAL, wxBOLD);
            item.SetFont(boldFont);
        }
        item.SetId(j);
        int index = InsertItem(item);
        SetItemText(index, WxConversion::toWxString(name));
    }
    mode_ = MODE_OPERATION;
}
References clear(), OSEdConstants::DEFAULT_COLUMN_WIDTH, OSEdTextGenerator::instance(), OperationContainer::isEffective(), mode_, MODE_OPERATION, OperationIndex::operationCount(), OperationContainer::operationIndex(), OperationIndex::operationName(), Texts::TextGenerator::text(), WxConversion::toWxString(), and OSEdTextGenerator::TXT_COLUMN_OPERATIONS.
Referenced by OSEdRemoveOperationCmd::Do(), OSEdTreeView::onItemSelected(), and OSEdTreeView::update().
pathView()
void OSEdInfoView::pathView ()
Shows the search path view.
Definition at line 98 of file OSEdInfoView.cc.
                       {
    clear();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_COLUMN_SEARCH_PATHS);
    InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH * 2);
    vector<string> paths = Environment::osalPaths();
    for (size_t i = 0; i < paths.size(); i++) {
        wxListItem item;
        if (FileSystem::fileExists(paths[i])) {
            // path exists, let's write it bold
            wxFont boldFont = wxFont(10, wxROMAN, wxNORMAL, wxBOLD);
            item.SetFont(boldFont);
        }
        item.SetId(i);
        int index = InsertItem(item);
        SetItemText(index, WxConversion::toWxString(paths[i]));
    }
    mode_ = MODE_PATH;
}
References clear(), OSEdConstants::DEFAULT_COLUMN_WIDTH, FileSystem::fileExists(), OSEdTextGenerator::instance(), mode_, MODE_PATH, Environment::osalPaths(), Texts::TextGenerator::text(), WxConversion::toWxString(), and OSEdTextGenerator::TXT_COLUMN_SEARCH_PATHS.
Referenced by OSEdTreeView::constructTree(), OSEdTreeView::onItemSelected(), and OSEdTreeView::update().
selectedModule()
string OSEdInfoView::selectedModule ()
Returns the selected module.
If no module is selected, returns an empty string.
Returns
The selected module.
Definition at line 510 of file OSEdInfoView.cc.
{
    if (mode_ != MODE_MODULE || GetSelectedItemCount() != 1) {
        return "";
    }
    return WidgetTools::lcStringSelection(this, 0);
}
References WidgetTools::lcStringSelection(), mode_, and MODE_MODULE.
Referenced by OSEdTreeView::isModuleSelected().
selectedOperation()
string OSEdInfoView::selectedOperation ()
Returns the selected operation.
If no operation is selected, return empty string.
Returns
The selected operation.
Definition at line 526 of file OSEdInfoView.cc.
{
    if(mode_ != MODE_OPERATION || GetSelectedItemCount() != 1) {
        return "";
    }
    return WidgetTools::lcStringSelection(this, 0);
}
References WidgetTools::lcStringSelection(), mode_, and MODE_OPERATION.
Referenced by OSEdTreeView::isOperationSelected(), OSEdTreeView::selectedOperation(), and OSEdTreeView::selectedOperationId().
selectedPath()
string OSEdInfoView::selectedPath ()
Returns the selected path.
If path is not selected returns an empty string.
Returns
The selected path.
Definition at line 493 of file OSEdInfoView.cc.
{
    if (mode_ != MODE_PATH || GetSelectedItemCount() != 1) {
        return "";
    }
    return WidgetTools::lcStringSelection(this, 0);
}
References WidgetTools::lcStringSelection(), mode_, and MODE_PATH.
Referenced by OSEdTreeView::isPathSelected(), OSEdTreeView::selectedPath(), and OSEdTreeView::selectedPathId().
writeStaticPropertiesOfOperation()
int OSEdInfoView::writeStaticPropertiesOfOperation (Operation * op) private
Writes the "static" operation properties in operation property view
Parameters
op Operation which static properties are written.
Returns
Number of written properties.
Definition at line 398 of file OSEdInfoView.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format trueFmt = texts.text(OSEdTextGenerator::TXT_ROW_TRUE);
    format falseFmt = texts.text(OSEdTextGenerator::TXT_ROW_FALSE);
    // row counter
    int i = 0;
    // name of the operation
    format fmt = texts.text(OSEdTextGenerator::TXT_ROW_NAME);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    SetItem(i, 1, WxConversion::toWxString(op->name()));
    i++;
    // description of the operation
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_DESCRIPTION);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    SetItem(i, 1, WxConversion::toWxString(op->description()));
    i++;
    // number of inputs
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_INPUTS);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    SetItem(i, 1, WxConversion::toWxString(op->numberOfInputs()));
    i++;
    // number of outputs
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_OUTPUTS);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    SetItem(i, 1, WxConversion::toWxString(op->numberOfOutputs()));
    i++;
    // reads memory
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_READS_MEMORY);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->readsMemory()) {
        SetItem(i, 1, WxConversion::toWxString(trueFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(falseFmt.str()));
    }
    i++;
    // writes memory
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_WRITES_MEMORY);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->writesMemory()) {
        SetItem(i, 1, WxConversion::toWxString(trueFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(falseFmt.str()));
    }
    i++;
    // can trap
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_CAN_TRAP);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->canTrap()) {
        SetItem(i, 1, WxConversion::toWxString(trueFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(falseFmt.str()));
    }
    i++;
    // has side effects
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_HAS_SIDE_EFFECTS);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->hasSideEffects()) {
        SetItem(i, 1, WxConversion::toWxString(trueFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(falseFmt.str()));
    }
    i++;
    // is clocked
    fmt = texts.text(OSEdTextGenerator::TXT_ROW_CLOCKED);
    InsertItem(i, WxConversion::toWxString(fmt.str()));
    if (op->isClocked()) {
        SetItem(i, 1, WxConversion::toWxString(trueFmt.str()));
    } else {
        SetItem(i, 1, WxConversion::toWxString(falseFmt.str()));
    }
    i++;
    return i;
}
References Operation::canTrap(), Operation::description(), Operation::hasSideEffects(), OSEdTextGenerator::instance(), Operation::isClocked(), Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::readsMemory(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ROW_CAN_TRAP, OSEdTextGenerator::TXT_ROW_CLOCKED, OSEdTextGenerator::TXT_ROW_DESCRIPTION, OSEdTextGenerator::TXT_ROW_FALSE, OSEdTextGenerator::TXT_ROW_HAS_SIDE_EFFECTS, OSEdTextGenerator::TXT_ROW_INPUTS, OSEdTextGenerator::TXT_ROW_NAME, OSEdTextGenerator::TXT_ROW_OUTPUTS, OSEdTextGenerator::TXT_ROW_READS_MEMORY, OSEdTextGenerator::TXT_ROW_TRUE, OSEdTextGenerator::TXT_ROW_WRITES_MEMORY, and Operation::writesMemory().
Referenced by operationPropertyView().
Member Data Documentation
mode_
InfoMode OSEdInfoView::mode_ private
Mode of the info view.
Definition at line 84 of file OSEdInfoView.hh.
Referenced by moduleView(), onDropDownMenu(), onSelection(), operationPropertyView(), operationView(), pathView(), selectedModule(), selectedOperation(), and selectedPath().
The documentation for this class was generated from the following files:
OSEdInfoView.hh
OSEdInfoView.cc