OpenASIP: CostEstimates Class Reference
CostEstimates Class Reference
#include <CostEstimates.hh>
Public Member Functions
CostEstimates ()
virtual ~CostEstimates ()
void setArea (double area)
void setLongestPathDelay (double delay)
void setEnergy (const TTAProgram::Program &program, double energy)
void setCycleCount (const TTAProgram::Program &program, ClockCycleCount cycles)
double area () const
double longestPathDelay () const
int energies () const
double energy (int index) const
double energy (const TTAProgram::Program &program) const
Private Attributes
std::map< const TTAProgram::Program *, double > energyMap_
Map containing programs and energies consumed in running the programs.
double area_
Area estimation value (in gates).
double longestPathDelay_
Longest path delay estimation value (in nano seconds).
Detailed Description
This class represents cost estimates for a machine configuration.
Class stores estimates of area (in gates), longest path delay (in nano seconds) and energy consumptions (in milli joules) when the configuration is used to run different programs. Area and longest path delay are constants to one configuration while there can be multiple programs executed so multiple energy consumption estimations and cycle counts as well. Each energy consumption is bound to one program.
Definition at line 57 of file CostEstimates.hh.
Constructor & Destructor Documentation
CostEstimates()
CostEstimates::CostEstimates ()
The contstructor.
Definition at line 42 of file CostEstimates.cc.
                             :
    area_(0), longestPathDelay_(0) {
}
~CostEstimates()
CostEstimates::~CostEstimates () virtual
The destructor.
Definition at line 49 of file CostEstimates.cc.
{
}
Member Function Documentation
area()
double CostEstimates::area () const
Returns the area estimate (in gates).
Returns
Returns the area estimate (in gates).
Definition at line 101 of file CostEstimates.cc.
{
    return area_;
}
References area_.
Referenced by MinimizeMachine::minimizeBuses(), Evaluate::printEstimates(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), ComponentImplementationSelector::selectRFs(), and setArea().
energies()
int CostEstimates::energies () const
Returns the number of different energy estimates (one for each program) in the cost estimation data.
Returns
Returns the number of stored energy estimates.
Definition at line 124 of file CostEstimates.cc.
{
    return energyMap_.size();
}
References energyMap_.
Referenced by energy(), and Evaluate::printEstimates().
energy() [1/2]
double CostEstimates::energy (const TTAProgram::Program & program) const
Returns the energy value corresponding to the Program.
Parameters
program Program of which energy is returned.
Returns
The energy of the Program.
Exceptions
KeyNotFound Is thrown if program has no energy set.
Definition at line 159 of file CostEstimates.cc.
{
    map<const TTAProgram::Program*, double>::const_iterator iter =
        energyMap_.find(&program);
    if (iter == energyMap_.end()) {
        throw KeyNotFound(__FILE__, __LINE__, __func__);
    }
    return (*iter).second;
}
References __func__, energyMap_, and program.
energy() [2/2]
double CostEstimates::energy (int index) const
Returns the energy value from the given index.
Parameters
index The index.
Returns
The energy value in the given index.
Exceptions
OutOfRange If the given index is less than 0 or greater or equal to the number of energies.
Definition at line 138 of file CostEstimates.cc.
{
    if (index < 0 || index >= energies()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    map<const TTAProgram::Program*, double>::const_iterator iter =
        energyMap_.begin();
    while (index > 0) {
        iter++;
        index--;
    }
    return (*iter).second;
}
References __func__, energies(), and energyMap_.
Referenced by Evaluate::printEstimates(), and setEnergy().
longestPathDelay()
double CostEstimates::longestPathDelay () const
Returns the longest path delay estimate (in nano seconds).
Returns
Returns the longest path delay estimate (in nano seconds).
Definition at line 112 of file CostEstimates.cc.
{
    return longestPathDelay_;
}
References longestPathDelay_.
Referenced by MinimizeMachine::minimizeBuses(), Evaluate::printEstimates(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), and ComponentImplementationSelector::selectRFs().
setArea()
void CostEstimates::setArea (double area)
Sets the area estimate (in gates).
Parameters
area Area estimate value (in gates).
Definition at line 58 of file CostEstimates.cc.
{
    area_ = area;
}
References area(), and area_.
Referenced by DesignSpaceExplorer::evaluate(), ComponentImplementationSelector::fuImplementations(), ComponentImplementationSelector::iuImplementations(), and ComponentImplementationSelector::rfImplementations().
setCycleCount()
void CostEstimates::setCycleCount (const TTAProgram::Program & program, ClockCycleCount cycles)
setEnergy()
void CostEstimates::setEnergy (const TTAProgram::Program & program, double energy)
Sets new energy estimate for the given program.
If there was an old energy value for the given key it is removed first.
Parameters
program Program that is used as a key.
energy Energy consumed while running the program (in milli joules).
Definition at line 83 of file CostEstimates.cc.
{
    map<const TTAProgram::Program*, double>::iterator iter =
        energyMap_.find(&program);
    if (iter != energyMap_.end()) {
        energyMap_.erase(iter);
    }
    energyMap_.insert(
        std::pair<const TTAProgram::Program*, double>(&program, energy));
}
References energy(), energyMap_, and program.
Referenced by DesignSpaceExplorer::evaluate().
setLongestPathDelay()
void CostEstimates::setLongestPathDelay (double delay)
Sets the longest path delay estimate (in nano seconds).
Parameters
delay Longest path delay estimte value (in nano seconds).
Definition at line 69 of file CostEstimates.cc.
{
    longestPathDelay_ = delay;
}
References longestPathDelay_.
Referenced by DesignSpaceExplorer::evaluate(), ComponentImplementationSelector::fuImplementations(), ComponentImplementationSelector::iuImplementations(), and ComponentImplementationSelector::rfImplementations().
Member Data Documentation
area_
double CostEstimates::area_ private
Area estimation value (in gates).
Definition at line 76 of file CostEstimates.hh.
Referenced by area(), and setArea().
energyMap_
std::map<const TTAProgram::Program*, double> CostEstimates::energyMap_ private
Map containing programs and energies consumed in running the programs.
Definition at line 74 of file CostEstimates.hh.
Referenced by energies(), energy(), energy(), and setEnergy().
longestPathDelay_
double CostEstimates::longestPathDelay_ private
Longest path delay estimation value (in nano seconds).
Definition at line 78 of file CostEstimates.hh.
Referenced by longestPathDelay(), and setLongestPathDelay().
The documentation for this class was generated from the following files:
CostEstimates.hh
CostEstimates.cc