OpenASIP: BlocksMUL Class Reference
BlocksMUL Class Reference
#include <BlocksMUL.hh>
Public Member Functions
BlocksMUL (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksMUL ()
Public Attributes
TTAMachine::FunctionUnit * mul
Public Attributes inherited from BlocksFU
std::vector< TTAMachine::HWOperation * > ops
TTAMachine::FunctionUnit * fu
TTAMachine::FUPort * in1
TTAMachine::FUPort * in2
TTAMachine::FUPort * out
std::shared_ptr< TTAMachine::Socket > in1sock
std::shared_ptr< TTAMachine::Socket > in2sock
TTAMachine::Socket * outsock
std::list< std::string > sources
std::string name
Private Member Functions
void ConfigurePipeline (TTAMachine::ExecutionPipeline *pipeline, int numOfOperands)
void BindPorts (TTAMachine::HWOperation *hwOp, int numOfOperands)
TTAMachine::HWOperation * CreateHWOp (const std::string &name, int numOfOperands)
Additional Inherited Members
Protected Member Functions inherited from BlocksFU
BlocksFU (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksFU ()
Detailed Description
Definition at line 39 of file BlocksMUL.hh.
Constructor & Destructor Documentation
BlocksMUL()
BlocksMUL::BlocksMUL (TTAMachine::Machine & mach, const std::string & name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
Constructor BlocksMUL
Parameters
mach The TTA machine where the MUL needs to be added.
name The name of the MUL.
sources A list of sources that are attached to this unit's input.
in1sock (shared) pointer to the TTA socket for in1 input port.
in2sock (shared) pointer to the TTA socket for in2 input port.
Definition at line 47 of file BlocksMUL.cc.
    : BlocksFU::BlocksFU(mach, name, sources, in1sock, in2sock) {
    // Function unit and ports
    mul = this->fu;
    // HW ops
    HWOperation* mulOp = CreateHWOp("mul", 3);
    ops.push_back(mulOp);
    HWOperation* copyOp = CreateHWOp("copy", 2);
    ops.push_back(copyOp);
}
References CreateHWOp(), BlocksFU::fu, mul, and BlocksFU::ops.
~BlocksMUL()
BlocksMUL::~BlocksMUL () inline
Definition at line 47 of file BlocksMUL.hh.
                 {
        while (!ops.empty()) {
            delete ops.back();
            ops.pop_back();
        }
    }
References BlocksFU::ops.
Member Function Documentation
BindPorts()
void BlocksMUL::BindPorts (TTAMachine::HWOperation * hwOp, int numOfOperands) private
Bind the operation's operands to FU ports.
Parameters
hwOp A pointer to the hardware operation of which the operands need to be binded to FU ports.
numOfOperands The number of operands of the given hwOp.
Definition at line 113 of file BlocksMUL.cc.
{
    if (numOfOperands == 2) {
        hwOp->bindPort(1, *in1);
        hwOp->bindPort(2, *out);
    } else if (numOfOperands == 3) {
        hwOp->bindPort(1, *in1);
        hwOp->bindPort(2, *in2);
        hwOp->bindPort(3, *out);
    } else {
        // Currently no operation known that uses a different numbers of
        // operands.
        assert(
            false &&
            "Trying to add an MUL operation with a different number of "
            "operands than 2 or 3.");
    }
}
References assert, TTAMachine::HWOperation::bindPort(), BlocksFU::in1, BlocksFU::in2, and BlocksFU::out.
Referenced by CreateHWOp().
ConfigurePipeline()
void BlocksMUL::ConfigurePipeline (TTAMachine::ExecutionPipeline * pipeline, int numOfOperands) private
Configure the operation pipeline.
Parameters
pipeline A pointer to the execution pipeline of the operation of which the pipeline needs to be configured.
numOfOperands The number of operands of the given hwOp.
Definition at line 139 of file BlocksMUL.cc.
{
    if (numOfOperands < 3) {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortWrite(2, 0, 1);
    } else {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortRead(2, 0, 1);
        pipeline->addPortWrite(3, 0, 1);
    }
}
References TTAMachine::ExecutionPipeline::addPortRead(), and TTAMachine::ExecutionPipeline::addPortWrite().
Referenced by CreateHWOp().
CreateHWOp()
HWOperation * BlocksMUL::CreateHWOp (const std::string & name, int numOfOperands) private
Creates a hardware operation.
Parameters
name The name of the hardware operation. This needs to exactly match the name in OSEd.
numOfOperands The number of operands that this hardware operation requires.
Definition at line 98 of file BlocksMUL.cc.
{
    HWOperation* op = new HWOperation(name, *mul);
    BindPorts(op, numOfOperands);
    ConfigurePipeline(op->pipeline(), numOfOperands);
    return op;
}
References BindPorts(), ConfigurePipeline(), mul, BlocksFU::name, and TTAMachine::HWOperation::pipeline().
Referenced by BlocksMUL().
Member Data Documentation
mul
TTAMachine::FunctionUnit* BlocksMUL::mul
Definition at line 41 of file BlocksMUL.hh.
Referenced by BlocksMUL(), and CreateHWOp().
The documentation for this class was generated from the following files:
BlocksMUL.hh
BlocksMUL.cc