OpenASIP: AddRFEntryCmd Class Reference
AddRFEntryCmd Class Reference
#include <AddRFEntryCmd.hh>
Public Member Functions
AddRFEntryCmd ()
virtual ~AddRFEntryCmd ()
virtual bool Do ()
virtual int id () const
virtual AddRFEntryCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new RF entries to a HDB.
Definition at line 41 of file AddRFEntryCmd.hh.
Constructor & Destructor Documentation
AddRFEntryCmd()
AddRFEntryCmd::AddRFEntryCmd ()
The Constructor.
Definition at line 45 of file AddRFEntryCmd.cc.
                             :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_RF_ENTRY, NULL) {
}
Referenced by create().
~AddRFEntryCmd()
AddRFEntryCmd::~AddRFEntryCmd () virtual
The Destructor.
Definition at line 53 of file AddRFEntryCmd.cc.
{
}
Member Function Documentation
create()
AddRFEntryCmd * AddRFEntryCmd::create () const virtual
Creates and returns new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 103 of file AddRFEntryCmd.cc.
{
    return new AddRFEntryCmd();
}
References AddRFEntryCmd().
Do()
bool AddRFEntryCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file AddRFEntryCmd.cc.
                  {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    RowID id = manager->addRFEntry();
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectRFEntry(id);
    return true;
}
References HDB::HDBManager::addRFEntry().
icon()
std::string AddRFEntryCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 81 of file AddRFEntryCmd.cc.
{
    return "";
}
id()
int AddRFEntryCmd::id () const virtual
Returns command identifier for this command.
Returns
Command identifier of this command.
Implements GUICommand.
Definition at line 92 of file AddRFEntryCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_RF_ENTRY;
}
References HDBEditorConstants::COMMAND_ADD_RF_ENTRY.
isEnabled()
bool AddRFEntryCmd::isEnabled () virtual
Returns true, if the command should be enabled in the menu/toolbar.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 114 of file AddRFEntryCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddRFEntryCmd.hh
AddRFEntryCmd.cc