OpenASIP: FUPortCode Class Reference
FUPortCode Class Reference
#include <FUPortCode.hh>
Public Member Functions
FUPortCode (const std::string &fu, const std::string &port, unsigned int encoding, unsigned int extraBits, SocketCodeTable &parent)
FUPortCode (const std::string &fu, const std::string &port, const std::string &operation, unsigned int encoding, unsigned int extraBits, SocketCodeTable &parent)
FUPortCode (const ObjectState *state, SocketCodeTable &parent)
virtual ~FUPortCode ()
std::string portName () const
std::string operationName () const
bool hasOperation () const
virtual ObjectState * saveState () const
Public Member Functions inherited from PortCode
virtual ~PortCode ()
std::string unitName () const
bool hasEncoding () const
unsigned int encoding () const
unsigned int extraBits () const
int width () const
int encodingWidth () const
int indexWidth () const
void setMaxIndex (unsigned regIndex)
bool isMaxIndexSet () const
unsigned maxIndex () const
SocketCodeTable * parent () const
Static Public Attributes
static const std::string OSNAME_FU_PORT_CODE = "fu_port_code"
ObjectState name for FU port code.
static const std::string OSKEY_PORT_NAME = "port"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_OPERATION_NAME = "operation"
ObjectState attribute key for the name of the operation.
Static Public Attributes inherited from PortCode
static const std::string OSNAME_PORT_CODE = "port_code"
ObjectState name for PortCode.
static const std::string OSKEY_UNIT_NAME = "unit_name"
ObjectState attribute key for the name of the unit.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_INDEX_WIDTH = "index_width"
ObjectState attribute key for the widht of register index.
static const std::string OSKEY_MAX_INDEX = "max-index"
ObjectState attribute key for the max-index attribute.
Private Attributes
std::string port_
Name of the port.
std::string opName_
Name of the operation.
Additional Inherited Members
Protected Member Functions inherited from PortCode
PortCode (const std::string &unitName, unsigned int encoding, unsigned int extraBits, int indexWidth)
PortCode (const std::string &unitName, int indexWidth)
PortCode (const ObjectState *state)
void setParent (SocketCodeTable *parent)
Detailed Description
Class FUPortCode represents the control code that identifies an FU port or, if the port carries an opcode, the combination of port and operation.
Definition at line 47 of file FUPortCode.hh.
Constructor & Destructor Documentation
FUPortCode() [1/3]
FUPortCode::FUPortCode (const std::string & fu, const std::string & port, unsigned int encoding, unsigned int extraBits, SocketCodeTable & parent)
The constructor.
Creates an encoding for a FU port and registers it into a socket code table. The port is identified by a name string and by the name of its function unit.
Parameters
fu Name of the function unit.
port Name of the port.
encoding The encoding.
extraBits The number of extra (zero) bits in the encoding.
parent The parent socket code table.
Exceptions
ObjectAlreadyExists If the given socket code table already has a code for the same port or if the encoding is ambiguous with another encoding in the same socket code table.
OutOfRange If some of the given values is out of range.
Definition at line 62 of file FUPortCode.cc.
    : PortCode(fu, encoding, extraBits, 0), port_(port), opName_("") {
    parent.addFUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addFUPortCode(), PortCode::parent(), and PortCode::setParent().
FUPortCode() [2/3]
FUPortCode::FUPortCode (const std::string & fu, const std::string & port, const std::string & operation, unsigned int encoding, unsigned int extraBits, SocketCodeTable & parent)
The constructor.
Creates an encoding for a FU port and registers it into a socket code table. The port is identified by a name string, the operation carried by it and the name of the parent function unit.
Parameters
fu Name of the function unit.
port Name of the port.
operation Name of the operation carried by the port.
encoding The encoding for the port + operation.
extraBits The number of extra zero bits in the encoding.
parent The parent socket code table.
Exceptions
ObjectAlreadyExists If the given socket code table already has a code for this port and the operation carried or if the encoding is ambiguous with another encoding in the same socket code table.
OutOfRange If some of the given values is out of range.
Definition at line 90 of file FUPortCode.cc.
    : PortCode(fu, encoding, extraBits, 0), port_(port), opName_(operation) {
    parent.addFUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addFUPortCode(), PortCode::parent(), and PortCode::setParent().
FUPortCode() [3/3]
FUPortCode::FUPortCode (const ObjectState * state, SocketCodeTable & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent socket code table.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the given socket code table already has a code for this port and the operation carried or if the encoding is ambiguous with another encoding in the same socket code table.
Definition at line 114 of file FUPortCode.cc.
    : PortCode(state), port_(""), opName_("") {
    const string procName = "FUPortCode::FUPortCode";
    if (state->name() != OSNAME_FU_PORT_CODE) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    if (state->hasAttribute(OSKEY_OPERATION_NAME)) {
        opName_ = state->stringAttribute(OSKEY_OPERATION_NAME);
    }
    port_ = state->stringAttribute(OSKEY_PORT_NAME);
    parent.addFUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addFUPortCode(), ObjectState::hasAttribute(), ObjectState::name(), opName_, OSKEY_OPERATION_NAME, OSKEY_PORT_NAME, OSNAME_FU_PORT_CODE, PortCode::parent(), port_, PortCode::setParent(), and ObjectState::stringAttribute().
~FUPortCode()
FUPortCode::~FUPortCode () virtual
The destructor.
Definition at line 134 of file FUPortCode.cc.
{
    SocketCodeTable* parent = this->parent();
    setParent(NULL);
    parent->removeFUPortCode(*this);
}
References PortCode::parent(), SocketCodeTable::removeFUPortCode(), and PortCode::setParent().
Member Function Documentation
hasOperation()
bool FUPortCode::hasOperation () const
Tells whether this control code identifies also one of the operations carried by the FU port.
Returns
True if the control code identifies an operation, otherwise false.
Definition at line 176 of file FUPortCode.cc.
{
    return opName_ != "";
}
References opName_.
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::fuPortCode(), SocketCodeTable::fuPortCode(), portCodeDescription(), and saveState().
operationName()
std::string FUPortCode::operationName () const
Returns the name of the operation.
Returns
The name of the operation.
Exceptions
InstanceNotFound If this control code identifies a plain FU port without operation.
Definition at line 160 of file FUPortCode.cc.
{
    if (opName_ == "") {
    const string procName = "FUPortCode::operationName";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    return opName_;
}
References opName_.
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::fuPortCode(), portCodeDescription(), and saveState().
portName()
std::string FUPortCode::portName () const
Returns the name of the port.
Returns
The name of the port.
Definition at line 147 of file FUPortCode.cc.
{
    return port_;
}
References port_.
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::fuPortCode(), SocketCodeTable::fuPortCode(), portCodeDescription(), and saveState().
saveState()
ObjectState * FUPortCode::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from PortCode.
Definition at line 187 of file FUPortCode.cc.
{
    ObjectState* state = PortCode::saveState();
    state->setName(OSNAME_FU_PORT_CODE);
    state->setAttribute(OSKEY_PORT_NAME, portName());
    if (hasOperation()) {
    state->setAttribute(OSKEY_OPERATION_NAME, operationName());
    }
    return state;
}
References hasOperation(), operationName(), OSKEY_OPERATION_NAME, OSKEY_PORT_NAME, OSNAME_FU_PORT_CODE, portName(), PortCode::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by SocketCodeTable::saveState().
Member Data Documentation
opName_
std::string FUPortCode::opName_ private
Name of the operation.
Definition at line 76 of file FUPortCode.hh.
Referenced by FUPortCode(), hasOperation(), and operationName().
OSKEY_OPERATION_NAME
const std::string FUPortCode::OSKEY_OPERATION_NAME = "operation" static
ObjectState attribute key for the name of the operation.
Definition at line 70 of file FUPortCode.hh.
Referenced by FUPortCode(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSKEY_PORT_NAME
const std::string FUPortCode::OSKEY_PORT_NAME = "port" static
ObjectState attribute key for the name of the port.
Definition at line 68 of file FUPortCode.hh.
Referenced by FUPortCode(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSNAME_FU_PORT_CODE
const std::string FUPortCode::OSNAME_FU_PORT_CODE = "fu_port_code" static
ObjectState name for FU port code.
Definition at line 66 of file FUPortCode.hh.
Referenced by FUPortCode(), SocketCodeTable::loadState(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
port_
std::string FUPortCode::port_ private
Name of the port.
Definition at line 74 of file FUPortCode.hh.
Referenced by FUPortCode(), and portName().
The documentation for this class was generated from the following files:
FUPortCode.hh
FUPortCode.cc