OpenASIP: MachineTestReporter Class Reference
MachineTestReporter Class Reference
#include <MachineTestReporter.hh>
Static Public Member Functions
static std::string socketSegmentConnectionError (const TTAMachine::Socket &socket, const TTAMachine::Segment &segment, const MachineTester &tester)
static std::string socketPortConnectionError (const TTAMachine::Socket &socket, const TTAMachine::Port &port, const MachineTester &tester)
static std::string bridgingError (const TTAMachine::Bus &sourceBus, const TTAMachine::Bus &destinationBus, const MachineTester &tester)
static std::string socketDirectionSettingError (const TTAMachine::Socket &socket, TTAMachine::Socket::Direction, const MachineTester &tester)
Detailed Description
Creates string error messages according to the error stated by MachineTester.
Definition at line 45 of file MachineTestReporter.hh.
Member Function Documentation
bridgingError()
string MachineTestReporter::bridgingError (const TTAMachine::Bus & sourceBus, const TTAMachine::Bus & destinationBus, const MachineTester & tester) static
Generates a general error message of the error that occurred when tried to bridge the given buses.
Parameters
sourceBus The source bus.
destinationBus The destination bus.
tester MachineTester that was used to check if the buses can be joined by a bridge.
Returns
An error message.
Definition at line 219 of file MachineTestReporter.cc.
{
    MachineTestReportTextGenerator textGenerator;
    if (tester.illegalRegistration()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_BRIDGE_ILLEGAL_REG);
        text % sourceBus.name() % destinationBus.name();
        return text.str();
    }
    if (tester.loop()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_BRIDGE_LOOP);
        text % sourceBus.name() % destinationBus.name();
        return text.str();
    }
    if (tester.connectionExists()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_BRIDGE_EXISTS);
        text % sourceBus.name() % destinationBus.name();
        return text.str();
    }
//     Bus* straddlingBus = tester.straddlingBus();
//     if (straddlingBus != NULL) {
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//                                          TXT_BRIDGE_STRADDLING_BUS);
//         text % sourceBus.name() % destinationBus.name() %
//             straddlingBus->name();
//         return text.str();
//     }
//     Socket* crossing = tester.crossingSocket(0);
//     if (crossing != NULL) {
//         Socket* crossing2 = tester.crossingSocket(1);
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//                                          TXT_BRIDGE_CROSSING_SOCKET);
//         text % sourceBus.name() % destinationBus.name() % crossing->name() %
//             crossing2->name();
//         return text.str();
//     }
    Bus* branchedBus = tester.branchedBus();
    if (branchedBus != NULL) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_BRIDGE_BRANCHED_BUS);
        text % sourceBus.name() % destinationBus.name() %
            branchedBus->name();
        return text.str();
    }
//     Socket* bindingSocket = tester.bindingSocket();
//     if (bindingSocket != NULL) {
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//                                          TXT_BRIDGE_BINDING_SOCKET);
//         text % sourceBus.name() % destinationBus.name() %
//             bindingSocket->name();
//         return text.str();
//     }
//     Unit* straddlingUnit = tester.straddlingUnit();
//     if (straddlingUnit != NULL) {
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//                                          TXT_BRIDGE_STRADDLING_UNIT);
//         text % sourceBus.name() % destinationBus.name() %
//             straddlingUnit->name();
//         return text.str();
//     }
    return "";
}
References MachineTester::branchedBus(), MachineTester::connectionExists(), MachineTester::illegalRegistration(), MachineTester::loop(), TTAMachine::Component::name(), and Texts::TextGenerator::text().
Referenced by TTAMachine::Bridge::Bridge(), and TTAMachine::Bridge::loadState().
socketDirectionSettingError()
string MachineTestReporter::socketDirectionSettingError (const TTAMachine::Socket & socket, TTAMachine::Socket::Direction direction, const MachineTester & tester) static
Generates a general error message of the reason why the direction of the given socket can not be set.
Parameters
socket The socket.
direction The direction that was tried to set.
tester The MachineTester used to check if the direction can be set.
Returns
An error message.
Definition at line 299 of file MachineTestReporter.cc.
{
    MachineTestReportTextGenerator textGenerator;
    if (tester.unknownSocketDirection()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_DIR_UNKNOWN);
        text % socket.name();
        return text.str();
    }
    if (tester.noConnections()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_NO_CONN);
        text % socket.name();
        return text.str();
    }
    Port* sameDirConnection = tester.sameDirSocketConnection(direction);
    if (sameDirConnection != NULL) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_SAME_DIR_CONN);
        if (direction == Socket::OUTPUT) {
            text % socket.name() % "output" % sameDirConnection->name() %
                sameDirConnection->parentUnit()->name();
        } else if (direction == Socket::INPUT) {
            text % socket.name() % "input" % sameDirConnection->name() %
                sameDirConnection->parentUnit()->name();
        } else {
            assert(false);
        }
        return text.str();
    }
    Port* forbiddenSocketDir = tester.forbiddenSocketDirection(direction);
    if (forbiddenSocketDir != NULL) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_FORBIDDEN_DIR);
        if (direction == Socket::OUTPUT) {
            text % socket.name() % "output" % forbiddenSocketDir->name() %
                forbiddenSocketDir->parentUnit()->name();
        } else if (direction == Socket::INPUT) {
            text % socket.name() % "input" % forbiddenSocketDir->name() %
                forbiddenSocketDir->parentUnit()->name();
        } else {
            assert(false);
        }
        return text.str();
    }
    return "";
}
References assert, MachineTester::forbiddenSocketDirection(), TTAMachine::Socket::INPUT, TTAMachine::Component::name(), TTAMachine::Port::name(), MachineTester::noConnections(), TTAMachine::Socket::OUTPUT, TTAMachine::Port::parentUnit(), MachineTester::sameDirSocketConnection(), Texts::TextGenerator::text(), and MachineTester::unknownSocketDirection().
Referenced by SocketDialog::onDirection(), and TTAMachine::Socket::setDirection().
socketPortConnectionError()
string MachineTestReporter::socketPortConnectionError (const TTAMachine::Socket & socket, const TTAMachine::Port & port, const MachineTester & tester) static
Generates a general error message of the error that occurred when tried to attach a socket to a port.
Parameters
socket The socket that was tried to be connected.
port The port to which the socket was tried to be connected.
tester MachineTester that was used to check if the connection can be made.
Returns
An error message.
Definition at line 150 of file MachineTestReporter.cc.
{
    MachineTestReportTextGenerator textGenerator;
    if (tester.illegalRegistration()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_PORT_CONN_ILLEGAL_REG);
        text % socket.name() % port.parentUnit()->name();
        return text.str();
    }
    if (tester.connectionExists()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_PORT_CONN_EXISTS);
        text % socket.name() % port.name() % port.parentUnit()->name();
        return text.str();
    }
    if (tester.wrongSocketDirection()) {
        format text = textGenerator.text(
            MachineTestReportTextGenerator::
            TXT_SOCKET_PORT_CONN_WRONG_SOCKET_DIR);
        text % socket.name() % port.name() % port.parentUnit()->name();
        return text.str();
    }
    if (tester.maxConnections()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_PORT_CONN_MAX_CONN);
        text % socket.name() % port.name() % port.parentUnit()->name();
        return text.str();
    }
//     Socket* straddlingUnitConn = tester.straddlingUnitConnection();
//     if (straddlingUnitConn != NULL) {
//         format text = textGenerator.text(
//             MachineTestReportTextGenerator::
//             TXT_SOCKET_PORT_CONN_STRADDLING_UNIT);
//         text % socket.name() % port.name() % port.parentUnit()->name() %
//             straddlingUnitConn->name();
//         return text.str();
//     }
    if (tester.registerFilePortAlreadyConnected()) {
        format text = textGenerator.text(
            MachineTestReportTextGenerator::
            TXT_SOCKET_PORT_CONN_RF_PORT_CONN_EXISTS);
        text % socket.name() % port.name() % port.parentUnit()->name();
        return text.str();
    }
    return "";
}
References MachineTester::connectionExists(), MachineTester::illegalRegistration(), MachineTester::maxConnections(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::Port::parentUnit(), MachineTester::registerFilePortAlreadyConnected(), Texts::TextGenerator::text(), and MachineTester::wrongSocketDirection().
Referenced by TTAMachine::Port::attachSocket().
socketSegmentConnectionError()
string MachineTestReporter::socketSegmentConnectionError (const TTAMachine::Socket & socket, const TTAMachine::Segment & segment, const MachineTester & tester) static
Generates a general error message of the error that occurred when tried to attach a socket to a segment.
Parameters
socket The socket that was tried to be connected.
segment The segment to which the socket was tried to be connected.
tester MachineTester that was used to check if the connection can be made.
Returns
An error message.
Definition at line 55 of file MachineTestReporter.cc.
{
    MachineTestReportTextGenerator textGenerator;
//     Bus* sameChainConnection = tester.sameChainConnection();
//     if (sameChainConnection != NULL) {
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//             TXT_SOCKET_SEGMENT_CONN_SAME_CHAIN);
//         text % socket.name() % segment.name() % segment.parentBus()->name() %
//             sameChainConnection->name();
//         return text.str();
//     }
    if (tester.connectionExists()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
                                         TXT_SOCKET_SEGMENT_CONN_EXISTS);
        text % socket.name() % segment.name() % segment.parentBus()->name();
        return text.str();
    }
    if (tester.illegalRegistration()) {
        format text = textGenerator.text(MachineTestReportTextGenerator::
            TXT_SOCKET_SEGMENT_CONN_ILLEGAL_REG);
        text % socket.name() % segment.parentBus()->name();
        return text.str();
    }
//     Bus* straddlingBus = tester.straddlingBus();
//     if (straddlingBus != NULL) {
//         format text = textGenerator.text(
//             MachineTestReportTextGenerator::
//             TXT_SOCKET_SEGMENT_CONN_STRADDLING_BUS);
//         text % socket.name() % segment.name() % segment.parentBus()->name() %
//             straddlingBus->name();
//         return text.str();
//     }
//     Socket* crossingSocket = tester.crossingSocket(socket);
//     if (crossingSocket != NULL) {
//         format text = textGenerator.text(MachineTestReportTextGenerator::
//                                          TXT_SOCKET_SEGMENT_CONN_CROSSING);
//         text % socket.name() % segment.name() % segment.parentBus()->name() %
//             crossingSocket->name();
//         return text.str();
//     }
//     Unit* straddlingUnit = tester.straddlingUnit();
//     if (straddlingUnit != NULL) {
//         format text = textGenerator.text(
//             MachineTestReportTextGenerator::
//             TXT_SOCKET_SEGMENT_CONN_STRADDLING_UNIT);
//         text % socket.name() % segment.name() % segment.parentBus()->name() %
//             straddlingUnit->name();
//         return text.str();
//     }
    Port* doubleInputConn = tester.sameDirSocketConnection(Socket::INPUT);
    Port* doubleOutputConn = tester.sameDirSocketConnection(Socket::OUTPUT);
    Port* forbiddenInputConn =
        tester.forbiddenSocketDirection(Socket::INPUT);
    Port* forbiddenOutputConn =
        tester.forbiddenSocketDirection(Socket::OUTPUT);
    if (doubleInputConn != NULL || forbiddenInputConn != NULL) {
        assert(doubleOutputConn != NULL || forbiddenOutputConn != NULL);
        format text = textGenerator.text(
            MachineTestReportTextGenerator::
            TXT_SOCKET_SEGMENT_CONN_BOTH_DIRS_ARE_ILLEGAL);
        Port* errInputPort = doubleInputConn != NULL ? doubleInputConn :
            forbiddenInputConn;
        Port* errOutputPort = doubleOutputConn != NULL ? doubleOutputConn :
            forbiddenOutputConn;
        text % socket.name() % errInputPort->name() %
            errInputPort->parentUnit()->name() % errOutputPort->name() %
            errOutputPort->parentUnit()->name();
        return text.str();
    }
    return "";
}
References assert, MachineTester::connectionExists(), MachineTester::forbiddenSocketDirection(), MachineTester::illegalRegistration(), TTAMachine::Socket::INPUT, TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::Segment::name(), TTAMachine::Socket::OUTPUT, TTAMachine::Segment::parentBus(), TTAMachine::Port::parentUnit(), MachineTester::sameDirSocketConnection(), and Texts::TextGenerator::text().
Referenced by TTAMachine::Socket::attachBus(), TTAMachine::Segment::attachSocket(), and SocketDialog::onAttach().
The documentation for this class was generated from the following files:
MachineTestReporter.hh
MachineTestReporter.cc