OpenASIP: BlocksLSU Class Reference
BlocksLSU Class Reference
#include <BlocksLSU.hh>
Public Member Functions
BlocksLSU (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, TTAMachine::AddressSpace &asData, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksLSU ()
Public Attributes
TTAMachine::FunctionUnit * lsu
Public Attributes inherited from BlocksFU
std::vector< TTAMachine::HWOperation * > ops
TTAMachine::FunctionUnit * fu
TTAMachine::FUPort * in1
TTAMachine::FUPort * in2
TTAMachine::FUPort * out
std::shared_ptr< TTAMachine::Socket > in1sock
std::shared_ptr< TTAMachine::Socket > in2sock
TTAMachine::Socket * outsock
std::list< std::string > sources
std::string name
Private Member Functions
void ConfigurePipeline (TTAMachine::ExecutionPipeline *pipeline, bool isLoadOp)
void BindPorts (TTAMachine::HWOperation *hwOp, bool isLoadOp)
TTAMachine::HWOperation * CreateHWLoadOp (const std::string &name)
TTAMachine::HWOperation * CreateHWStoreOp (const std::string &name)
Additional Inherited Members
Protected Member Functions inherited from BlocksFU
BlocksFU (TTAMachine::Machine &mach, const std::string &name, std::list< std::string > sources, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
~BlocksFU ()
Detailed Description
Definition at line 41 of file BlocksLSU.hh.
Constructor & Destructor Documentation
BlocksLSU()
BlocksLSU::BlocksLSU (TTAMachine::Machine & mach, const std::string & name, std::list< std::string > sources, TTAMachine::AddressSpace & asData, std::shared_ptr< TTAMachine::Socket > in1sock, std::shared_ptr< TTAMachine::Socket > in2sock)
BlocksLSU with default instructions
Parameters
mach The TTA machine where the LSU needs to be added.
name The name of the LSU.
sources A list of sources that are attached to this unit's input.
asData The address space containing the program data.
in1sock (shared) pointer to the TTA socket for in1 input port.
in2sock (shared) pointer to the TTA socket for in2 input port.
Definition at line 47 of file BlocksLSU.cc.
    : BlocksFU::BlocksFU(mach, name, sources, in1sock, in2sock) {
    // Function unit and ports
    lsu = this->fu;
    // Set adress space to data
    lsu->setAddressSpace(&asData);
    // HWOps
    ops.push_back(CreateHWLoadOp("ld32"));
    ops.push_back(CreateHWLoadOp("ldu16"));
    ops.push_back(CreateHWLoadOp("ldu8"));
    ops.push_back(CreateHWStoreOp("st16"));
    ops.push_back(CreateHWStoreOp("st8"));
    ops.push_back(CreateHWStoreOp("st32"));
    ops.push_back(CreateHWLoadOp("copy"));
}
References CreateHWLoadOp(), CreateHWStoreOp(), BlocksFU::fu, lsu, BlocksFU::ops, and TTAMachine::FunctionUnit::setAddressSpace().
~BlocksLSU()
BlocksLSU::~BlocksLSU () inline
Definition at line 49 of file BlocksLSU.hh.
                 {
        while (!ops.empty()) {
            delete ops.back();
            ops.pop_back();
        }
    }
References BlocksFU::ops.
Member Function Documentation
BindPorts()
void BlocksLSU::BindPorts (TTAMachine::HWOperation * hwOp, bool isLoadOp) private
Bind the operation's operands to FU ports.
Parameters
hwOp A pointer to the hardware operation of which the operands need to be binded to FU ports.
isLoadOp A boolean that indicates whether the operation given is a load operation(true) or store operation(false).
Definition at line 132 of file BlocksLSU.cc.
{
    if (isLoadOp) {               // Load operation
        hwOp->bindPort(1, *in1);  // Memory address to read
        hwOp->bindPort(2, *out);  // Data
    } else {                      // Store operation
        hwOp->bindPort(1, *in1);  // Memory address to write
        hwOp->bindPort(2, *in2);  // Data to write
    }
}
References TTAMachine::HWOperation::bindPort(), BlocksFU::in1, BlocksFU::in2, and BlocksFU::out.
Referenced by CreateHWLoadOp(), and CreateHWStoreOp().
ConfigurePipeline()
void BlocksLSU::ConfigurePipeline (TTAMachine::ExecutionPipeline * pipeline, bool isLoadOp) private
Configure the operation pipeline.
Parameters
pipeline A pointer to the execution pipeline of the operation of which the pipeline needs to be configured.
isLoadOp A boolean that indicates whether the operation given is a load operation(true) or store operation(false).
Definition at line 151 of file BlocksLSU.cc.
{
    if (isLoadOp) {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortWrite(2, 0, 1);
    } else {
        pipeline->addPortRead(1, 0, 1);
        pipeline->addPortRead(2, 0, 1);
    }
}
References TTAMachine::ExecutionPipeline::addPortRead(), and TTAMachine::ExecutionPipeline::addPortWrite().
Referenced by CreateHWLoadOp(), and CreateHWStoreOp().
CreateHWLoadOp()
HWOperation * BlocksLSU::CreateHWLoadOp (const std::string & name) private
Creates a hardware load operation.
Parameters
name The name of the hardware operation. This needs to exactly match the name in OSEd.
Definition at line 103 of file BlocksLSU.cc.
{
    HWOperation* op = new HWOperation(name, *lsu);
    BindPorts(op, true);
    ConfigurePipeline(op->pipeline(), true);
    return op;
}
References BindPorts(), ConfigurePipeline(), lsu, BlocksFU::name, and TTAMachine::HWOperation::pipeline().
Referenced by BlocksLSU().
CreateHWStoreOp()
HWOperation * BlocksLSU::CreateHWStoreOp (const std::string & name) private
Creates a hardware store operation.
Parameters
name The name of the hardware operation. This needs to exactly match the name in OSEd.
Definition at line 116 of file BlocksLSU.cc.
{
    HWOperation* op = new HWOperation(name, *lsu);
    BindPorts(op, false);
    ConfigurePipeline(op->pipeline(), false);
    return op;
}
References BindPorts(), ConfigurePipeline(), lsu, BlocksFU::name, and TTAMachine::HWOperation::pipeline().
Referenced by BlocksLSU().
Member Data Documentation
lsu
TTAMachine::FunctionUnit* BlocksLSU::lsu
Definition at line 43 of file BlocksLSU.hh.
Referenced by BlocksLSU(), CreateHWLoadOp(), and CreateHWStoreOp().
The documentation for this class was generated from the following files:
BlocksLSU.hh
BlocksLSU.cc