OpenASIP: TPEF::SectionIndexReplacer Class Reference
TPEF::SectionIndexReplacer Class Reference
#include <SectionIndexReplacer.hh>
Public Member Functions
SectionIndexReplacer (const SafePointable *obj, Byte fieldSize)
virtual ~SectionIndexReplacer ()
Public Member Functions inherited from TPEF::ValueReplacer
void resolve ()
Protected Member Functions
virtual bool tryToReplace ()
virtual ValueReplacer * clone ()
Protected Member Functions inherited from TPEF::ValueReplacer
ValueReplacer (const SafePointable *obj)
ValueReplacer (const ValueReplacer &replacer)
virtual ~ValueReplacer ()
const SafePointable * reference () const
unsigned int streamPosition () const
Private Member Functions
SectionIndexReplacer (const SectionIndexReplacer &replacer)
SectionIndexReplacer operator= (const SectionIndexReplacer &)
void writeReplacement (Word value)
Private Attributes
const Byte fieldSize_
Field how many bytes of stream are replaced with section index.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::ValueReplacer
static void finalize ()
static void initialize (BinaryStream &stream)
Static Protected Member Functions inherited from TPEF::ValueReplacer
static BinaryStream & stream ()
Detailed Description
Replaces object reference with section index. Section index key must be stored in reference manager for that object whose section index is written.
Definition at line 48 of file SectionIndexReplacer.hh.
Constructor & Destructor Documentation
SectionIndexReplacer() [1/2]
TPEF::SectionIndexReplacer::SectionIndexReplacer (const SafePointable * obj, Byte size)
Constructor.
Definition at line 46 of file SectionIndexReplacer.cc.
                                         :
    ValueReplacer(obj), fieldSize_(size) {
}
~SectionIndexReplacer()
TPEF::SectionIndexReplacer::~SectionIndexReplacer () virtual
Destructor.
Definition at line 62 of file SectionIndexReplacer.cc.
{
}
SectionIndexReplacer() [2/2]
TPEF::SectionIndexReplacer::SectionIndexReplacer (const SectionIndexReplacer & replacer) private
Copy constructor.
Definition at line 54 of file SectionIndexReplacer.cc.
                                          :
    ValueReplacer(replacer), fieldSize_(replacer.fieldSize_) {
}
Member Function Documentation
clone()
ValueReplacer * TPEF::SectionIndexReplacer::clone () protected virtual
Creates dynamically allocated copy of replacer.
Returns
Dynamically allocated copy of replacer.
Implements TPEF::ValueReplacer.
Definition at line 92 of file SectionIndexReplacer.cc.
{
    return new SectionIndexReplacer(*this);
}
operator=()
SectionIndexReplacer TPEF::SectionIndexReplacer::operator= (const SectionIndexReplacer &) private
tryToReplace()
bool TPEF::SectionIndexReplacer::tryToReplace () protected virtual
Tries to do replacement in to the stream.
Returns
True if replacement were done.
Implements TPEF::ValueReplacer.
Definition at line 71 of file SectionIndexReplacer.cc.
{
    try {
        SectionIndexKey key =
            SafePointer::sectionIndexKeyFor(reference());
        stream().setWritePosition(streamPosition());
        writeReplacement(key.index());
        return true;
    } catch (KeyNotFound& e) {
        writeReplacement(0);
        return false;
    }
}
References TPEF::ReferenceManager::SectionIndexKey::index(), TPEF::ValueReplacer::reference(), TPEF::ReferenceManager::SafePointer::sectionIndexKeyFor(), TPEF::BinaryStream::setWritePosition(), TPEF::ValueReplacer::stream(), TPEF::ValueReplacer::streamPosition(), and writeReplacement().
writeReplacement()
void TPEF::SectionIndexReplacer::writeReplacement (Word value) private
Writes value with one, two or four bytes wide.
Parameters
value Value to be written.
Definition at line 102 of file SectionIndexReplacer.cc.
{
    switch (fieldSize_) {
    case 1: {
        stream().writeByte(value);
        break;
    }
    case 2: {
        stream().writeHalfWord(value);
        break;
    }
    case 3: {
        Byte firstByte = (value >> HALFWORD_BITWIDTH);
        HalfWord lastBytes = (value << HALFWORD_BITWIDTH)
                                    >> HALFWORD_BITWIDTH;
        // writing three bytes in big endian format
        stream().writeHalfWord(lastBytes);
        stream().writeByte(firstByte);
        break;
    }
    case 4: {
        stream().writeWord(value);
        break;
    }
    default:
        bool unsupportedFieldSizeOfReplacement = false;
        assert(unsupportedFieldSizeOfReplacement);
        }
}
References assert, fieldSize_, HALFWORD_BITWIDTH, TPEF::ValueReplacer::stream(), TPEF::BinaryStream::writeByte(), TPEF::BinaryStream::writeHalfWord(), and TPEF::BinaryStream::writeWord().
Referenced by tryToReplace().
Member Data Documentation
fieldSize_
const Byte TPEF::SectionIndexReplacer::fieldSize_ private
Field how many bytes of stream are replaced with section index.
Definition at line 65 of file SectionIndexReplacer.hh.
Referenced by writeReplacement().
The documentation for this class was generated from the following files:
SectionIndexReplacer.hh
SectionIndexReplacer.cc