OpenASIP: PasteComponentCmd Class Reference
PasteComponentCmd Class Reference
#include <PasteComponentCmd.hh>
Public Member Functions
PasteComponentCmd ()
virtual bool Do ()
virtual int id () const
virtual PasteComponentCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
template<class ComponentNavigator >
void paste (TTAMachine::Machine &machine, TTAMachine::Component *component, ComponentNavigator &navigator)
bool setMachine (TTAMachine::Component *component, TTAMachine::Machine *machine)
Detailed Description
Command for pasting components from the clipboard to the machine.
Definition at line 49 of file PasteComponentCmd.hh.
Constructor & Destructor Documentation
PasteComponentCmd()
PasteComponentCmd::PasteComponentCmd ()
The Constructor.
Definition at line 64 of file PasteComponentCmd.cc.
                                    :
    EditorCommand(ProDeConstants::CMD_NAME_PASTE) {
}
Referenced by create().
Member Function Documentation
create()
PasteComponentCmd * PasteComponentCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 221 of file PasteComponentCmd.cc.
{
    return new PasteComponentCmd();
}
References PasteComponentCmd().
Do()
bool PasteComponentCmd::Do () virtual
Executes the command.
Copies descriptor of a component from the clipboard and adds corresponding component to the machine
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 79 of file PasteComponentCmd.cc.
                      {
    ProDeClipboard* clipboard = ProDeClipboard::instance();
    ObjectState* contents = clipboard->copyContents();
    MDFDocument* document =
    dynamic_cast<MDFDocument*>(view()->GetDocument());
    assert(document != NULL);
    Machine* machine = document->getModel()->getMachine();
    assert(machine != NULL);
    document->getModel()->pushToStack();
    if (contents->name() == Socket::OSNAME_SOCKET) {
        // socket
        Machine::SocketNavigator navigator = machine->socketNavigator();
        Socket* socket = new Socket(contents);
        paste(*machine, socket, navigator);
        contents->setAttribute(Socket::OSKEY_NAME, socket->name());
        // Socket can be pasted only if the target machine has busses with
        // the same names as the busses where the copied socket was connected
        // to.
        try {
            socket->loadState(contents);
        } catch (ObjectStateLoadingException& e) {
            wxString message =
                _T("The socket cannot be pasted to this machine.\n\n");
            message.Append(WxConversion::toWxString(e.errorMessage()));
            InformationDialog dialog(parentWindow(), message);
            dialog.ShowModal();
            delete socket;
            return false;
        }
    } else if (contents->name() == FunctionUnit::OSNAME_FU) {
        // function unit
        Machine::FunctionUnitNavigator navigator =
            machine->functionUnitNavigator();
        TTAMachine::FunctionUnit* copiedFU = new FunctionUnit(contents);
        std::string fuName = copiedFU->name();
        paste(*machine, copiedFU, navigator);
        // cannot copy address space from one machien to another.
        if (clipboard->sourceMachine() == machine) {
            TTAMachine::FunctionUnit& original =
                *navigator.item(fuName);
            // need to do this after paste() as the FU must be registered to
            // the machine before the address space can be set
            if (original.hasAddressSpace()) {
                copiedFU->setAddressSpace(original.addressSpace());
            }
        }
    } else if (contents->name() == ImmediateUnit::OSNAME_IMMEDIATE_UNIT) {
        // immediate unit
        Machine::ImmediateUnitNavigator navigator =
            machine->immediateUnitNavigator();
        paste(*machine, new ImmediateUnit(contents), navigator);
    } else if (contents->name() == RegisterFile::OSNAME_REGISTER_FILE) {
        // register file
        Machine::RegisterFileNavigator navigator =
            machine->registerFileNavigator();
        paste(*machine, new RegisterFile(contents), navigator);
    } else if (contents->name() == Bus::OSNAME_BUS) {
        // register file
        Machine::BusNavigator navigator =
            machine->busNavigator();
        TTAMachine::Bus* copiedBus = new Bus(contents);
        // cannot copy guards from one machine into another
        // plus additional check if oroginal bus has been deleted
        if (clipboard->sourceMachine() == machine &&
            navigator.hasItem(copiedBus->name())) {
            TTAMachine::Bus& original =
                *navigator.item(copiedBus->name());
            // register the bus to the machine, possibly rename it to
            // avoid name clashes
            paste(*machine, copiedBus, navigator);
            // also copy the guards from the original Bus
            assert(copiedBus->guardCount() == 0);
            for (int i = 0; i < original.guardCount(); ++i) {
                original.guard(i)->copyTo(*copiedBus);
            }
        } else {
            // register the bus as above
            paste(*machine, copiedBus, navigator);
            assert(copiedBus->guardCount() == 0);
        }
    } else if (contents->name() == ControlUnit::OSNAME_CONTROL_UNIT) {
        // control unit
        if (machine->controlUnit() != NULL) {
            // Target machine already contained a control unit.
            // Display error message and pop the machine from undo stack.
            ProDeTextGenerator* generator = ProDeTextGenerator::instance();
            format fmt =
                generator->text(ProDeTextGenerator::MSG_ERROR_ONE_GCU);
            string title = fmt.str();
            wxString message = WxConversion::toWxString(title);
            InformationDialog info(parentWindow(), message);
            info.ShowModal();
            document->getModel()->popFromStack();
            delete contents;
            return false;
        } else {
            // Paste control unit.
            ControlUnit* gcu = new ControlUnit(contents);
            gcu->setMachine(*machine);
        }
    } else {
        // Unknown component type.
        assert(false);
    }
    delete contents;
    document->getModel()->notifyObservers();
    return false;
}
References TTAMachine::FunctionUnit::addressSpace(), assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::controlUnit(), ProDeClipboard::copyContents(), TTAMachine::Guard::copyTo(), Exception::errorMessage(), TTAMachine::Machine::functionUnitNavigator(), Model::getMachine(), MDFDocument::getModel(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::FunctionUnit::hasAddressSpace(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateUnitNavigator(), ProDeClipboard::instance(), ProDeTextGenerator::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Socket::loadState(), machine, ProDeTextGenerator::MSG_ERROR_ONE_GCU, TTAMachine::Component::name(), ObjectState::name(), Model::notifyObservers(), TTAMachine::Bus::OSNAME_BUS, TTAMachine::ControlUnit::OSNAME_CONTROL_UNIT, TTAMachine::FunctionUnit::OSNAME_FU, TTAMachine::ImmediateUnit::OSNAME_IMMEDIATE_UNIT, TTAMachine::RegisterFile::OSNAME_REGISTER_FILE, TTAMachine::Socket::OSNAME_SOCKET, GUICommand::parentWindow(), paste(), Model::popFromStack(), Model::pushToStack(), TTAMachine::Machine::registerFileNavigator(), TTAMachine::FunctionUnit::setAddressSpace(), ObjectState::setAttribute(), TTAMachine::ControlUnit::setMachine(), TTAMachine::Machine::socketNavigator(), ProDeClipboard::sourceMachine(), Texts::TextGenerator::text(), WxConversion::toWxString(), and EditorCommand::view().
icon()
string PasteComponentCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 233 of file PasteComponentCmd.cc.
{
    return ProDeConstants::CMD_ICON_PASTE;
}
References ProDeConstants::CMD_ICON_PASTE.
id()
int PasteComponentCmd::id () const virtual
Returns command identifier of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 210 of file PasteComponentCmd.cc.
{
    return ProDeConstants::COMMAND_PASTE;
}
References ProDeConstants::COMMAND_PASTE.
isEnabled()
bool PasteComponentCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open and the clipboard is not empty.
Returns
True, if the command is executable.
Reimplemented from EditorCommand.
Definition at line 248 of file PasteComponentCmd.cc.
{
    // check that a document is open
    wxDocManager* manager = wxGetApp().docManager();
    MDFView* mdfView = dynamic_cast<MDFView*>(manager->GetCurrentView());
    if (mdfView == NULL) {
        return false;
    }
    // check that the clipboard is not empty
    ProDeClipboard* clipboard = ProDeClipboard::instance();
    if (clipboard->isEmpty()) {
        return false;
    }
    return true;
}
References ProDeClipboard::instance(), and ProDeClipboard::isEmpty().
paste()
template<class ComponentNavigator > void PasteComponentCmd::paste (TTAMachine::Machine & machine, TTAMachine::Component * component, ComponentNavigator & navigator) private
Referenced by Do().
setMachine()
bool PasteComponentCmd::setMachine (TTAMachine::Component * component, TTAMachine::Machine * machine) private
The documentation for this class was generated from the following files:
PasteComponentCmd.hh
PasteComponentCmd.cc