OpenASIP: ProDeExportCmd Class Reference
ProDeExportCmd Class Reference
#include <ProDeExportCmd.hh>
Public Member Functions
ProDeExportCmd ()
virtual ~ProDeExportCmd ()
virtual bool Do ()
virtual int id () const
virtual ProDeExportCmd * create () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for exporting machine visualization to an encapsulated postscript file or a bitmap.
Definition at line 43 of file ProDeExportCmd.hh.
Constructor & Destructor Documentation
ProDeExportCmd()
ProDeExportCmd::ProDeExportCmd ()
The Constructor.
Definition at line 55 of file ProDeExportCmd.cc.
                              :
    EditorCommand(ProDeConstants::CMD_NAME_EXPORT) {
}
Referenced by create().
~ProDeExportCmd()
ProDeExportCmd::~ProDeExportCmd () virtual
The Destructor.
Definition at line 64 of file ProDeExportCmd.cc.
{}
Member Function Documentation
create()
ProDeExportCmd * ProDeExportCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 156 of file ProDeExportCmd.cc.
{
    return new ProDeExportCmd();
}
References ProDeExportCmd().
Do()
bool ProDeExportCmd::Do () virtual
Executes the command.
Returns
Always false. Returning true here would cause problems with the wxCommandProcessor, and the command is never undoable so it's safe to return false even if the command was succesfully executed.
Implements GUICommand.
Definition at line 75 of file ProDeExportCmd.cc.
                   {
    wxView* view = wxGetApp().docManager()->GetCurrentView();
    MachineCanvas* canvas = dynamic_cast<MDFView*>(view)->canvas();
    assert(view != NULL && canvas != NULL);
    wxString message = _T("Export processor figure.");
    wxString defaultDir = _T(".");
    wxString defaultFile= _T("");
#if wxCHECK_VERSION(3, 0, 0)
    wxString fileTypes = _T("Scalable Vector Graphics (.svg)|*.svg|");
#else
    wxString fileTypes = _T("Encapsulated Postscript (.eps)|*.eps;*.epsi|");
#endif
    fileTypes.Append(_T("Portable Network Graphics (.png)|*.png"));
    wxFileDialog dialog(
        parentWindow(), message, defaultDir, defaultFile, fileTypes,
        wxSAVE | wxOVERWRITE_PROMPT);
    if (dialog.ShowModal() == wxID_CANCEL) {
        return false;
    }
    std::string filename = WxConversion::toString(dialog.GetPath());
    std::string extension = FileSystem::fileExtension(filename);
    std::string creator = "TTA Processor Designer";
    std::string title =
        WxConversion::toString(view->GetDocument()->GetTitle());
#if wxCHECK_VERSION(3, 0, 0)
    if (extension == ".svg") {
        if (!canvas->saveSVG(filename)) {
#else
    if (extension == ".eps" || extension == ".epsi") {
        if (!canvas->saveEPS(filename, title, creator)) {
#endif
            wxString message = _T("Error saving file '");
            message.Append(dialog.GetPath());
            message.Append(_T("'."));
            ErrorDialog errorDialog(parentWindow(), message);
            errorDialog.ShowModal();
        }
    } else if (extension == ".png") {
        if (!canvas->savePNG(filename)) {
            wxString message = _T("Error saving file '");
            message.Append(dialog.GetPath());
            message.Append(_T("'."));
            ErrorDialog errorDialog(parentWindow(), message);
            errorDialog.ShowModal();
        }
    } else {
        wxString message = _T("File type with extension '");
        message.Append(WxConversion::toWxString(extension));
        message.Append(_T("' is not supported."));
        ErrorDialog dialog(parentWindow(), message);
        dialog.ShowModal();
        return false;
    }
    return false;
}
References assert, FileSystem::fileExtension(), GUICommand::parentWindow(), MachineCanvas::saveEPS(), MachineCanvas::savePNG(), WxConversion::toString(), WxConversion::toWxString(), and EditorCommand::view().
id()
int ProDeExportCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 145 of file ProDeExportCmd.cc.
{
    return ProDeConstants::COMMAND_EXPORT;
}
References ProDeConstants::COMMAND_EXPORT.
isEnabled()
bool ProDeExportCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 169 of file ProDeExportCmd.cc.
{
    wxView* view = wxGetApp().docManager()->GetCurrentView();
    if (view != NULL) {
    return true;
    }
    return false;
}
References EditorCommand::view().
The documentation for this class was generated from the following files:
ProDeExportCmd.hh
ProDeExportCmd.cc