OpenASIP: CommandRegistry Class Reference
CommandRegistry Class Reference
#include <CommandRegistry.hh>
Public Member Functions
CommandRegistry ()
~CommandRegistry ()
void addCommand (GUICommand *command)
GUICommand * createCommand (const int id)
GUICommand * createCommand (const std::string name)
GUICommand * firstCommand ()
GUICommand * nextCommand ()
std::string commandName (int id) const
std::string commandShortName (const std::string name) const
int commandId (const std::string name) const
std::string commandIcon (const std::string name) const
bool isEnabled (const std::string command)
Private Attributes
std::vector< GUICommand * > commands_
Commands in the registry.
std::vector< GUICommand * >::iterator iterator_
The position of the iteration. Used by the firstCommand() and nextCommand().
Detailed Description
List of editor commands which can be added to the toolbar or executed using a keyboard shortcut.
Definition at line 47 of file CommandRegistry.hh.
Constructor & Destructor Documentation
CommandRegistry()
CommandRegistry::CommandRegistry ()
The Constructor.
Definition at line 44 of file CommandRegistry.cc.
{
}
~CommandRegistry()
CommandRegistry::~CommandRegistry ()
The Destructor.
Definition at line 51 of file CommandRegistry.cc.
{
    // delete commands in registry
    vector<GUICommand*>::iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    delete *i;
    }
    commands_.clear();
}
References commands_.
Member Function Documentation
addCommand()
void CommandRegistry::addCommand (GUICommand * command)
Referenced by EVT_MENU_RANGE().
commandIcon()
std::string CommandRegistry::commandIcon (const std::string name) const
Returns icon for the GUICommand.
Parameters
name Name of the GUICommand.
Returns
Icon for the GUICommand.
Definition at line 155 of file CommandRegistry.cc.
{
    vector<GUICommand*>::const_iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->name() == name) {
        return (*i)->icon();
    }
    }
    throw InstanceNotFound(__FILE__, __LINE__, __func__, "");
    return "";
}
References __func__, and commands_.
Referenced by GUIOptions::createToolbar().
commandId()
int CommandRegistry::commandId (const std::string name) const
Returns enumerated ID of the command.
Parameters
name Name of the GUICommand.
Returns
Enumerated ID of the GUICommand, or -1 if no command was found.
Definition at line 137 of file CommandRegistry.cc.
{
    vector<GUICommand*>::const_iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->name() == name) {
        return (*i)->id();
    }
    }
    return -1;
}
References commands_, and GUICommand::id().
Referenced by GUIOptions::createToolbar(), and MainFrame::updateUI().
commandName()
std::string CommandRegistry::commandName (int id) const
Returns name of the GUICommand.
Parameters
id ID of the GUICommand.
Returns
Command name.
Definition at line 173 of file CommandRegistry.cc.
{
    vector<GUICommand*>::const_iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->id() == id) {
        return (*i)->name();
    }
    }
    throw InstanceNotFound(__FILE__, __LINE__, __func__, "");
    return "";
}
References __func__, and commands_.
Referenced by ProximMainFrame::menuAccelerator(), and MainFrame::menuAccelerator().
commandShortName()
std::string CommandRegistry::commandShortName (const std::string name) const
Returns short name of the GUICommand.
Parameters
name Name of the GUICommand.
Returns
Short version of the command name.
Definition at line 191 of file CommandRegistry.cc.
{
    vector<GUICommand*>::const_iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->name() == name) {
        return (*i)->shortName();
    }
    }
    throw InstanceNotFound(__FILE__, __LINE__, __func__, "");
    return "";
}
References __func__, and commands_.
Referenced by GUIOptions::createToolbar().
createCommand() [1/2]
GUICommand * CommandRegistry::createCommand (const int id)
Creates a new command corresponding to the id.
Parameters
id Enumerated ID of the GUICommand.
Returns
Created GUICommand, or NULL, if no GUICommand was found with the ID.
Definition at line 69 of file CommandRegistry.cc.
{
    vector<GUICommand*>::iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->id() == id) {
        return (*i)->create();
    }
    }
    return NULL;
}
References commands_, and GUICommand::create().
Referenced by OSEdMainFrame::onCommandEvent(), HDBEditorMainFrame::onCommandEvent(), OSEdTreeView::onItemClicked(), HDBEditorMainFrame::onUpdateUI(), and MainFrame::onUpdateUI().
createCommand() [2/2]
GUICommand * CommandRegistry::createCommand (const std::string name)
Creates a new command corresponding to the command name.
Parameters
name Name of the GUICommand.
Returns
Created GUICommand, or NULL, if no GUICommand was found with the name.
Definition at line 87 of file CommandRegistry.cc.
{
    vector<GUICommand*>::iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->name() == name) {
        return (*i)->create();
    }
    }
    return NULL;
}
References commands_, and GUICommand::create().
firstCommand()
GUICommand * CommandRegistry::firstCommand ()
Returns first command in the registry.
Returns
Pointer to the first command in the registry.
Definition at line 104 of file CommandRegistry.cc.
{
    iterator_ = commands_.begin();
    if (iterator_ == commands_.end()) {
    return NULL;
    }
    return (*iterator_);
}
References commands_, and iterator_.
Referenced by OptionsDialog::readCommands(), DropDownMenu::updateMenu(), and OSEdMainFrame::updateMenuBar().
isEnabled()
bool CommandRegistry::isEnabled (const std::string command)
Returns true, if command is executable and should be enabled, false if not.
Parameters
command The command which is checked for enabled/disabled state.
Returns
true, if the command is executable.
Definition at line 210 of file CommandRegistry.cc.
{
    vector<GUICommand*>::iterator i = commands_.begin();
    for (; i != commands_.end(); i++) {
    if ((*i)->name() == command) {
        return (*i)->isEnabled();
    }
    }
    throw InstanceNotFound(__FILE__, __LINE__, __func__, "");
    return false;
}
References __func__, and commands_.
Referenced by SelectTool::createDefaultMenu(), GUIOptions::createToolbar(), SelectTool::popContextMenu(), ConnectTool::rightClick(), and MainFrame::updateUI().
nextCommand()
GUICommand * CommandRegistry::nextCommand ()
Returns next command in the registry.
Returns
Pointer to the next command in the registry.
Definition at line 120 of file CommandRegistry.cc.
{
    iterator_++;
    if (iterator_ == commands_.end()) {
    return NULL;
    }
    return (*iterator_);
}
References commands_, and iterator_.
Referenced by OptionsDialog::readCommands(), DropDownMenu::updateMenu(), and OSEdMainFrame::updateMenuBar().
Member Data Documentation
commands_
std::vector<GUICommand*> CommandRegistry::commands_ private
Commands in the registry.
Definition at line 65 of file CommandRegistry.hh.
Referenced by commandIcon(), commandId(), commandName(), commandShortName(), createCommand(), createCommand(), firstCommand(), isEnabled(), nextCommand(), and ~CommandRegistry().
iterator_
std::vector<GUICommand*>::iterator CommandRegistry::iterator_ private
The position of the iteration. Used by the firstCommand() and nextCommand().
Definition at line 68 of file CommandRegistry.hh.
Referenced by firstCommand(), and nextCommand().
The documentation for this class was generated from the following files:
CommandRegistry.hh
CommandRegistry.cc