OpenASIP: CostEstimationData Class Reference
CostEstimationData Class Reference
#include <CostEstimationData.hh>
Public Member Functions
CostEstimationData ()
virtual ~CostEstimationData ()
void setName (const std::string &name)
bool hasName () const
std::string name () const
void setValue (const DataObject &value)
bool hasValue () const
DataObject value () const
void setFUReference (RowID fuEntryID)
bool hasFUReference () const
RowID fuReference () const
void setRFReference (RowID rfEntryID)
bool hasRFReference () const
RowID rfReference () const
void setBusReference (RowID busEntryID)
bool hasBusReference () const
RowID busReference () const
void setSocketReference (RowID socketEntryID)
bool hasSocketReference () const
RowID socketReference () const
void setPluginID (RowID pluginID)
bool hasPluginID () const
RowID pluginID () const
Private Attributes
bool hasName_
Is the data name set?
std::string name_
Name of the data.
bool hasValue_
Is the value set?
DataObject value_
Value data.
bool hasFUReference_
Is the fu reference set?
RowID fuReference_
FU reference.
bool hasRFReference_
Is the RF reference set?
RowID rfReference_
RF reference.
bool hasBusReference_
Is the bus reference set?
RowID busReference_
Bus reference.
bool hasSocketReference_
Is the socket reference set?
RowID socketReference_
Socket reference.
bool hasPluginID_
Is the plugin ID set?
RowID pluginID_
Plugin ID.
Detailed Description
Class that represents one row in the cost estimation data table.
Definition at line 42 of file CostEstimationData.hh.
Constructor & Destructor Documentation
CostEstimationData()
CostEstimationData::CostEstimationData ()
The Constructor.
Definition at line 38 of file CostEstimationData.cc.
                                      :
    hasName_(false), hasValue_(false),
    hasFUReference_(false), hasRFReference_(false),
    hasBusReference_(false), hasSocketReference_(false),
    hasPluginID_(false) {
}
~CostEstimationData()
CostEstimationData::~CostEstimationData () virtual
Destructor.
Definition at line 49 of file CostEstimationData.cc.
{
}
Member Function Documentation
busReference()
RowID CostEstimationData::busReference () const
Returns the bus entry reference.
Returns
Register file entry reference.
Definition at line 133 of file CostEstimationData.cc.
{
    if (!hasBusReference_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return busReference_;
}
References __func__, busReference_, and hasBusReference_.
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
fuReference()
RowID CostEstimationData::fuReference () const
Returns the FU entry reference.
Returns
Function unit entry reference.
Definition at line 103 of file CostEstimationData.cc.
{
    if (!hasFUReference_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return fuReference_;
}
References __func__, fuReference_, and hasFUReference_.
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
hasBusReference()
bool CostEstimationData::hasBusReference () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
hasFUReference()
bool CostEstimationData::hasFUReference () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
hasName()
bool CostEstimationData::hasName () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), and HDB::HDBManager::modifyCostEstimationData().
hasPluginID()
bool CostEstimationData::hasPluginID () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), and HDB::HDBManager::modifyCostEstimationData().
hasRFReference()
bool CostEstimationData::hasRFReference () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
hasSocketReference()
bool CostEstimationData::hasSocketReference () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
hasValue()
bool CostEstimationData::hasValue () const
Referenced by HDB::HDBManager::addCostEstimationData(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), and HDB::HDBManager::modifyCostEstimationData().
name()
std::string CostEstimationData::name () const
Returns name of the cost estimation data value.
Returns
Cost data name.
Definition at line 58 of file CostEstimationData.cc.
{
    if (!hasName_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return name_;
}
References __func__, hasName_, and name_.
Referenced by HDB::HDBManager::addCostEstimationData(), CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), HDBToHtml::busEntryToHtml(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDBToHtml::fuEntryToHtml(), HDBToHtml::fuImplToHtml(), HDB::HDBManager::modifyCostEstimationData(), HDBToHtml::rfEntryToHtml(), HDBToHtml::rfImplToHtml(), HDBToHtml::socketEntryToHtml(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
pluginID()
RowID CostEstimationData::pluginID () const
Returns the cost function plugin ID.
Returns
Cost function plugin ID.
Definition at line 88 of file CostEstimationData.cc.
{
    if (!hasPluginID_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return pluginID_;
}
References __func__, hasPluginID_, and pluginID_.
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::busEntryToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDBToHtml::fuEntryToHtml(), HDBToHtml::fuImplToHtml(), HDB::HDBManager::modifyCostEstimationData(), HDBToHtml::rfEntryToHtml(), HDBToHtml::rfImplToHtml(), and HDBToHtml::socketEntryToHtml().
rfReference()
RowID CostEstimationData::rfReference () const
Returns the RF entry reference.
Returns
Register file entry reference.
Definition at line 118 of file CostEstimationData.cc.
{
    if (!hasRFReference_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return rfReference_;
}
References __func__, hasRFReference_, and rfReference_.
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
setBusReference()
void CostEstimationData::setBusReference (RowID busEntryID)
Referenced by CostDatabase::buildBuses(), HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setFUReference()
void CostEstimationData::setFUReference (RowID fuEntryID)
Referenced by CostDatabase::buildFunctionUnits(), HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setName()
void CostEstimationData::setName (const std::string & name)
Referenced by HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setPluginID()
void CostEstimationData::setPluginID (RowID pluginID)
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setRFReference()
void CostEstimationData::setRFReference (RowID rfEntryID)
Referenced by CostDatabase::buildRegisterFiles(), HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setSocketReference()
void CostEstimationData::setSocketReference (RowID socketEntryID)
Referenced by CostDatabase::buildSockets(), HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
setValue()
void CostEstimationData::setValue (const DataObject & value)
Referenced by HDB::HDBManager::costEstimationData(), and CostEstimationDataDialog::onOK().
socketReference()
RowID CostEstimationData::socketReference () const
Returns the socket entry reference.
Returns
Register file entry reference.
Definition at line 148 of file CostEstimationData.cc.
{
    if (!hasSocketReference_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return socketReference_;
}
References __func__, hasSocketReference_, and socketReference_.
Referenced by HDB::HDBManager::addCostEstimationData(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostEstimatioDataIdsQuery(), HDB::HDBManager::modifyCostEstimationData(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
value()
DataObject CostEstimationData::value () const
Returns value of the cost estimation data.
Returns
Cost data value.
Definition at line 73 of file CostEstimationData.cc.
{
    if (!hasValue_) {
        throw NotAvailable(
            __FILE__, __LINE__, __func__, "Attribute value not set.");
    }
    return value_;
}
References __func__, hasValue_, and value_.
Referenced by HDB::HDBManager::addCostEstimationData(), CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), HDBToHtml::busEntryToHtml(), HDBToHtml::costFunctionPluginToHtml(), HDBToHtml::fuEntryToHtml(), HDBToHtml::fuImplToHtml(), HDB::HDBManager::modifyCostEstimationData(), HDBToHtml::rfEntryToHtml(), HDBToHtml::rfImplToHtml(), HDBToHtml::socketEntryToHtml(), CostEstimationDataDialog::TransferDataToWindow(), and CostFunctionPluginDialog::TransferDataToWindow().
Member Data Documentation
busReference_
RowID CostEstimationData::busReference_ private
Bus reference.
Definition at line 99 of file CostEstimationData.hh.
Referenced by busReference().
fuReference_
RowID CostEstimationData::fuReference_ private
FU reference.
Definition at line 89 of file CostEstimationData.hh.
Referenced by fuReference().
hasBusReference_
bool CostEstimationData::hasBusReference_ private
Is the bus reference set?
Definition at line 97 of file CostEstimationData.hh.
Referenced by busReference().
hasFUReference_
bool CostEstimationData::hasFUReference_ private
Is the fu reference set?
Definition at line 87 of file CostEstimationData.hh.
Referenced by fuReference().
hasName_
bool CostEstimationData::hasName_ private
Is the data name set?
Definition at line 77 of file CostEstimationData.hh.
Referenced by name().
hasPluginID_
bool CostEstimationData::hasPluginID_ private
Is the plugin ID set?
Definition at line 107 of file CostEstimationData.hh.
Referenced by pluginID().
hasRFReference_
bool CostEstimationData::hasRFReference_ private
Is the RF reference set?
Definition at line 92 of file CostEstimationData.hh.
Referenced by rfReference().
hasSocketReference_
bool CostEstimationData::hasSocketReference_ private
Is the socket reference set?
Definition at line 102 of file CostEstimationData.hh.
Referenced by socketReference().
hasValue_
bool CostEstimationData::hasValue_ private
Is the value set?
Definition at line 82 of file CostEstimationData.hh.
Referenced by value().
name_
std::string CostEstimationData::name_ private
Name of the data.
Definition at line 79 of file CostEstimationData.hh.
Referenced by name().
pluginID_
RowID CostEstimationData::pluginID_ private
Plugin ID.
Definition at line 109 of file CostEstimationData.hh.
Referenced by pluginID().
rfReference_
RowID CostEstimationData::rfReference_ private
RF reference.
Definition at line 94 of file CostEstimationData.hh.
Referenced by rfReference().
socketReference_
RowID CostEstimationData::socketReference_ private
Socket reference.
Definition at line 104 of file CostEstimationData.hh.
Referenced by socketReference().
value_
DataObject CostEstimationData::value_ private
Value data.
Definition at line 84 of file CostEstimationData.hh.
Referenced by value().
The documentation for this class was generated from the following files:
CostEstimationData.hh
CostEstimationData.cc