OpenASIP: InfoRegFilesCommand Class Reference
InfoRegFilesCommand Class Reference
Public Member Functions
InfoRegFilesCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoRegFilesCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info regfiles".
Definition at line 305 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoRegFilesCommand()
InfoRegFilesCommand::InfoRegFilesCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 310 of file InfoCommand.cc.
                                                                  :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoRegFilesCommand()
virtual InfoRegFilesCommand::~InfoRegFilesCommand () inline virtual
Destructor.
Definition at line 317 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoRegFilesCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info regfiles" command.
"info regfiles" prints the names of all the register files in the machine.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 329 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 0, 0)) {
            return false;
        }
        if (!parent().checkMachineLoaded()) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        const TTAMachine::Machine::RegisterFileNavigator& nav =
            mach.registerFileNavigator();
        std::string result = "";
        bool isFirst = true;
        for (int i = 0; i < nav.count(); ++i) {
            if (!isFirst)
                result += "\n";
            result += nav.item(i)->name();
            isFirst = false;
        }
        parent().interpreter()->setResult(result);
        return true;
    }
References TTAMachine::Machine::Navigator< ComponentType >::count(), CustomCommand::interpreter(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), SimControlLanguageSubCommand::parent(), TTAMachine::Machine::registerFileNavigator(), ScriptInterpreter::setResult(), and SimControlLanguageCommand::simulatorFrontend().
The documentation for this class was generated from the following file:
InfoCommand.cc