OpenASIP: IPXactHibiInterface Class Reference
IPXactHibiInterface Class Reference
#include <IPXactHibiInterface.hh>
Public Member Functions
IPXactHibiInterface ()
virtual ~IPXactHibiInterface ()
virtual bool mapPortsToInterface (const ProGe::NetlistBlock &toplevel)
Public Member Functions inherited from IPXactInterface
IPXactInterface ()
virtual ~IPXactInterface ()
virtual TCEString instanceName () const
virtual IPXact::Vlnv busType () const
virtual IPXact::Vlnv busAbstractionType () const
virtual IPXactModel::BusMode busMode () const
virtual const PlatInt::SignalMappingList & interfaceMapping () const
virtual void addSignalMapping (const TCEString &actualSignal, const TCEString &busSignal)
void setInstanceName (const TCEString &name)
Private Member Functions
void createInstanceName (const TCEString &fullName, const TCEString &portName)
Private Attributes
PlatInt::SignalMappingList interfaceSearch_
Mapping of known port names and interface port names.
Static Private Attributes
static const TCEString DEFAULT_INSTANCE_NAME = "hibi_p"
static const TCEString VENDOR = "TUT"
static const TCEString LIBRARY ="ip.hwp.communication"
static const TCEString NAME ="hibi_ip_r4.busdef"
static const TCEString BUS_VERSION = "2.0"
static const TCEString ABS_VENDOR
static const TCEString ABS_LIBRARY
static const TCEString ABS_NAME = "hibi_ip_r4.absdef"
static const TCEString ABS_VERSION
static const IPXactModel::BusMode DEFAULT_BUS_MODE
Additional Inherited Members
Protected Member Functions inherited from IPXactInterface
void setBusMode (IPXactModel::BusMode mode)
void setBusType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
void setBusAbsType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
Detailed Description
Definition at line 38 of file IPXactHibiInterface.hh.
Constructor & Destructor Documentation
IPXactHibiInterface()
IPXactHibiInterface::IPXactHibiInterface ()
Definition at line 55 of file IPXactHibiInterface.cc.
                                        :
    IPXactInterface(), interfaceSearch_() {
    setInstanceName(DEFAULT_INSTANCE_NAME);
    setBusType(VENDOR, LIBRARY, NAME, BUS_VERSION);
    setBusAbsType(ABS_VENDOR, ABS_LIBRARY, ABS_NAME, ABS_VERSION);
    setBusMode(DEFAULT_BUS_MODE);
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_comm_out", "COMM_FROM_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_data_out", "DATA_FROM_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_av_out", "AV_FROM_IP"));
    interfaceSearch_. push_back(
        new pair<TCEString,TCEString>("hibi_we_out", "WE_FROM_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_re_out", "RE_FROM_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_comm_in", "COMM_TO_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_data_in", "DATA_TO_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_av_in", "AV_TO_IP"));
    interfaceSearch_. push_back(
        new pair<TCEString,TCEString>("hibi_full_in", "FULL_TO_IP"));
    interfaceSearch_.push_back(
        new pair<TCEString,TCEString>("hibi_empty_in", "EMPTY_TO_IP"));
}
References ABS_LIBRARY, ABS_NAME, ABS_VENDOR, ABS_VERSION, BUS_VERSION, DEFAULT_BUS_MODE, DEFAULT_INSTANCE_NAME, interfaceSearch_, LIBRARY, NAME, IPXactInterface::setBusAbsType(), IPXactInterface::setBusMode(), IPXactInterface::setBusType(), IPXactInterface::setInstanceName(), and VENDOR.
~IPXactHibiInterface()
IPXactHibiInterface::~IPXactHibiInterface () virtual
Definition at line 86 of file IPXactHibiInterface.cc.
{
    for (unsigned int i = 0; i < interfaceSearch_.size(); i++) {
        delete interfaceSearch_.at(i);
    }
}
References interfaceSearch_.
Member Function Documentation
createInstanceName()
void IPXactHibiInterface::createInstanceName (const TCEString & fullName, const TCEString & portName) private
Definition at line 125 of file IPXactHibiInterface.cc.
{
    TCEString fu = "";
    TCEString::size_type pos = fullName.find(portName);
    if (pos == TCEString::npos || pos == 0) {
        fu = fullName;
    } else {
        fu = StringTools::trim(fullName.substr(0, pos));
    }
    TCEString instance = fu + DEFAULT_INSTANCE_NAME;
    setInstanceName(instance);
}
References DEFAULT_INSTANCE_NAME, IPXactInterface::setInstanceName(), and StringTools::trim().
Referenced by mapPortsToInterface().
mapPortsToInterface()
bool IPXactHibiInterface::mapPortsToInterface (const ProGe::NetlistBlock & toplevel) virtual
Implements IPXactInterface.
Definition at line 94 of file IPXactHibiInterface.cc.
{
    bool instanceNameSet = false;
    for (unsigned int i = 0; i < interfaceSearch_.size(); i++) {
        for (size_t j = 0; j < toplevel.portCount(); j++) {
            TCEString interfacePort = interfaceSearch_.at(i)->first;
            const NetlistPort& port = toplevel.port(j);
            if (port.name().find(interfacePort) != TCEString::npos) {
                TCEString abstractPort = interfaceSearch_.at(i)->second;
                addSignalMapping(port.name(), abstractPort);
                if (!instanceNameSet) {
                    createInstanceName(port.name(), interfacePort);
                    instanceNameSet = true;
                }
                break;
            }
        }
        if (interfaceMapping().size() == 0) {
            // does not contain this interface
            return false;
        }
    }
    bool foundAllPorts = false;
    if (interfaceSearch_.size() == interfaceMapping().size()) {
        foundAllPorts = true;
    }
    return foundAllPorts;
}
References IPXactInterface::addSignalMapping(), createInstanceName(), IPXactInterface::interfaceMapping(), interfaceSearch_, ProGe::NetlistPort::name(), ProGe::NetlistBlock::port(), and ProGe::NetlistBlock::portCount().
Member Data Documentation
ABS_LIBRARY
const TCEString IPXactHibiInterface::ABS_LIBRARY static private
Initial value:
=
    IPXactHibiInterface::LIBRARY
Definition at line 61 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
ABS_NAME
const TCEString IPXactHibiInterface::ABS_NAME = "hibi_ip_r4.absdef" static private
Definition at line 62 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
ABS_VENDOR
const TCEString IPXactHibiInterface::ABS_VENDOR static private
Initial value:
=
    IPXactHibiInterface::VENDOR
Definition at line 60 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
ABS_VERSION
const TCEString IPXactHibiInterface::ABS_VERSION static private
Initial value:
=
    IPXactHibiInterface::BUS_VERSION
Definition at line 63 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
BUS_VERSION
const TCEString IPXactHibiInterface::BUS_VERSION = "2.0" static private
Definition at line 59 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
DEFAULT_BUS_MODE
const IPXactModel::BusMode IPXactHibiInterface::DEFAULT_BUS_MODE static private
Initial value:
=
    IPXactModel::MASTER
Definition at line 65 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
DEFAULT_INSTANCE_NAME
const TCEString IPXactHibiInterface::DEFAULT_INSTANCE_NAME = "hibi_p" static private
Definition at line 55 of file IPXactHibiInterface.hh.
Referenced by createInstanceName(), and IPXactHibiInterface().
interfaceSearch_
PlatInt::SignalMappingList IPXactHibiInterface::interfaceSearch_ private
Mapping of known port names and interface port names.
Definition at line 53 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface(), mapPortsToInterface(), and ~IPXactHibiInterface().
LIBRARY
const TCEString IPXactHibiInterface::LIBRARY ="ip.hwp.communication" static private
Definition at line 57 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
NAME
const TCEString IPXactHibiInterface::NAME ="hibi_ip_r4.busdef" static private
Definition at line 58 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
VENDOR
const TCEString IPXactHibiInterface::VENDOR = "TUT" static private
Definition at line 56 of file IPXactHibiInterface.hh.
Referenced by IPXactHibiInterface().
The documentation for this class was generated from the following files:
IPXactHibiInterface.hh
IPXactHibiInterface.cc