OpenASIP: FUExternalPortDialog Class Reference
FUExternalPortDialog Class Reference
#include <FUExternalPortDialog.hh>
Public Member Functions
FUExternalPortDialog (wxWindow *parent, wxWindowID id, HDB::FUExternalPort &implementation, const HDB::FUImplementation &fu)
virtual ~FUExternalPortDialog ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_NAME , ID_LABEL_WIDTH , ID_WIDTH ,
ID_LABEL_DESCRIPTION , ID_DESCRIPTION , ID_DIRECTION , ID_PARAMETER_DEPS ,
ID_LINE
}
Enumerated IDs for dialog widgets.
Private Member Functions
void initialize ()
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Creates the dialog contents.
Private Attributes
HDB::FUExternalPort & port_
FU port implementation to modify.
const HDB::FUImplementation & fu_
Parent FU implementation of the port.
wxString name_
wxString widthFormula_
wxString description_
int direction_
wxCheckListBox * depList_
Detailed Description
Dialog for editing FU external ports.
Definition at line 48 of file FUExternalPortDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerated IDs for dialog widgets.
Enumerator
ID_LABEL_NAME
ID_NAME
ID_LABEL_WIDTH
ID_WIDTH
ID_LABEL_DESCRIPTION
ID_DESCRIPTION
ID_DIRECTION
ID_PARAMETER_DEPS
ID_LINE
Definition at line 62 of file FUExternalPortDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_NAME,
        ID_LABEL_WIDTH,
        ID_WIDTH,
        ID_LABEL_DESCRIPTION,
        ID_DESCRIPTION,
        ID_DIRECTION,
        ID_PARAMETER_DEPS,
        ID_LINE
    };
Constructor & Destructor Documentation
FUExternalPortDialog()
FUExternalPortDialog::FUExternalPortDialog (wxWindow * parent, wxWindowID id, HDB::FUExternalPort & implementation, const HDB::FUImplementation & fu)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog window.
port FU external port to modify.
Definition at line 58 of file FUExternalPortDialog.cc.
                                :
    wxDialog(parent, id, _T("Function Unit Port Port")),
    port_(port), fu_(fu), depList_(NULL) {
    initialize();
}
~FUExternalPortDialog()
FUExternalPortDialog::~FUExternalPortDialog () virtual
The Destructor.
Definition at line 70 of file FUExternalPortDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FUExternalPortDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Creates the dialog contents.
Definition at line 168 of file FUExternalPortDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(300,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width formula:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_WIDTH, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item6, 0, wxGROW|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_DESCRIPTION, wxT("Description:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_DESCRIPTION, wxT(""), wxDefaultPosition, wxSize(300,-1), 0 );
    item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item9 = new wxGridSizer( 2, 0, 0 );
    wxString strs10[] =
    {
        wxT("In"),
        wxT("Out"),
        wxT("Bidirectional")
    };
    wxRadioBox *item10 = new wxRadioBox( parent, ID_DIRECTION, wxT("Direction:"), wxDefaultPosition, wxDefaultSize, 3, strs10, 1, wxRA_SPECIFY_COLS );
    item9->Add( item10, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("Parameter dependency:") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );
    wxWindow *item13 = new wxCheckListBox(parent, ID_PARAMETER_DEPS, wxDefaultPosition, wxSize(200, 150));
    wxASSERT( item13 );
    item11->Add( item13, 0, wxGROW|wxALL, 5 );
    item9->Add( item11, 0, wxGROW|wxALL, 5 );
    item1->Add( item9, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item14 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item14, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item16 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item17 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item15, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DESCRIPTION, ID_DIRECTION, ID_LABEL_DESCRIPTION, ID_LABEL_NAME, ID_LABEL_WIDTH, ID_LINE, ID_NAME, ID_PARAMETER_DEPS, and ID_WIDTH.
Referenced by initialize().
initialize()
void FUExternalPortDialog::initialize () private
Creates and initializes the dialog widgets.
Definition at line 77 of file FUExternalPortDialog.cc.
{
    createContents(this, true, true);
    depList_ = dynamic_cast<wxCheckListBox*>(
        FindWindow(ID_PARAMETER_DEPS));
    name_ = WxConversion::toWxString(port_.name());
    widthFormula_ = WxConversion::toWxString(port_.widthFormula());
    description_ = WxConversion::toWxString(port_.description());
    direction_ = port_.direction();
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_WIDTH)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &widthFormula_));
    FindWindow(ID_DIRECTION)->SetValidator(wxGenericValidator(&direction_));
    FindWindow(ID_DESCRIPTION)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &description_));
    depList_->Clear();
    for (int i = 0; i < fu_.parameterCount(); i++) {
        string parameter = fu_.parameter(i).name;
        depList_->Append( WxConversion::toWxString(parameter));
        for (int dep = 0; dep < port_.parameterDependencyCount(); dep++) {
            if (port_.parameterDependency(dep) == parameter) {
                depList_->Check(i);
            }
        }
    }
}
References createContents(), depList_, HDB::ExternalPort::description(), description_, HDB::ExternalPort::direction(), direction_, fu_, ID_DESCRIPTION, ID_DIRECTION, ID_NAME, ID_PARAMETER_DEPS, ID_WIDTH, HDB::ExternalPort::name(), HDB::Parameter::name, name_, HDB::FUImplementation::parameter(), HDB::FUImplementation::parameterCount(), HDB::ExternalPort::parameterDependency(), HDB::ExternalPort::parameterDependencyCount(), port_, WxConversion::toWxString(), HDB::ExternalPort::widthFormula(), and widthFormula_.
onOK()
void FUExternalPortDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 114 of file FUExternalPortDialog.cc.
{
    TransferDataFromWindow();
    name_ = name_.Trim(true).Trim(false);
    widthFormula_ = widthFormula_.Trim(true).Trim(false);
    description_ = description_.Trim(true).Trim(false);
    if (name_.IsEmpty()) {
        wxString message = _T("Name field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    if (widthFormula_.IsEmpty()) {
        wxString message =
            _T("Width formula field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    port_.setName(WxConversion::toString(name_));
    port_.setWidthFormula(WxConversion::toString(widthFormula_));
    port_.setDescription(WxConversion::toString(description_));
    if (direction_ == 0) {
        port_.setDirection(IN);
    } else if (direction_ == 1) {
        port_.setDirection(OUT);
    } else if (direction_ == 2) {
        port_.setDirection(BIDIR);
    } else {
        assert(false);
    }
    for (int i = 0; i < fu_.parameterCount(); i++) {
        string parameter = WxConversion::toString(depList_->GetString(i));
        if (depList_->IsChecked(i)) {
            port_.setParameterDependency(parameter);
        } else {
            port_.unsetParameterDependency(parameter);
        }
    }
    EndModal(wxID_OK);
}
References assert, HDB::BIDIR, depList_, description_, direction_, fu_, HDB::IN, name_, HDB::OUT, HDB::FUImplementation::parameterCount(), port_, HDB::ExternalPort::setDescription(), HDB::ExternalPort::setDirection(), HDB::ExternalPort::setName(), HDB::ExternalPort::setParameterDependency(), HDB::ExternalPort::setWidthFormula(), WxConversion::toString(), HDB::ExternalPort::unsetParameterDependency(), and widthFormula_.
Member Data Documentation
depList_
wxCheckListBox* FUExternalPortDialog::depList_ private
Definition at line 87 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
description_
wxString FUExternalPortDialog::description_ private
Definition at line 84 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
direction_
int FUExternalPortDialog::direction_ private
Definition at line 85 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
fu_
const HDB::FUImplementation& FUExternalPortDialog::fu_ private
Parent FU implementation of the port.
Definition at line 80 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
name_
wxString FUExternalPortDialog::name_ private
Definition at line 82 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
port_
HDB::FUExternalPort& FUExternalPortDialog::port_ private
FU port implementation to modify.
Definition at line 78 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
widthFormula_
wxString FUExternalPortDialog::widthFormula_ private
Definition at line 83 of file FUExternalPortDialog.hh.
Referenced by initialize(), and onOK().
The documentation for this class was generated from the following files:
FUExternalPortDialog.hh
FUExternalPortDialog.cc