OpenASIP: TTAProgram::NullAddress Class Reference
TTAProgram::NullAddress Class Reference
#include <NullAddress.hh>
Public Member Functions
virtual ~NullAddress ()
UIntWord location () const
const TTAMachine::AddressSpace & space () const
Public Member Functions inherited from TTAProgram::Address
Address (InstructionAddress location, const TTAMachine::AddressSpace &space)
~Address ()
InstructionAddress location () const
const TTAMachine::AddressSpace & space () const
bool operator== (const Address &other) const
bool operator!= (const Address &other) const
bool operator< (const Address &addr) const
Static Public Member Functions
static NullAddress & instance ()
Protected Member Functions
NullAddress ()
Private Member Functions
NullAddress (const NullAddress &)
Copying not allowed.
NullAddress & operator= (const NullAddress &)
Assignment not allowed.
Static Private Attributes
static NullAddress instance_
Detailed Description
A singleton class that represents a null address.
Calling any method causes the program to abort.
Definition at line 45 of file NullAddress.hh.
Constructor & Destructor Documentation
~NullAddress()
TTAProgram::NullAddress::~NullAddress () virtual
The destructor.
Definition at line 56 of file NullAddress.cc.
{
}
NullAddress() [1/2]
TTAProgram::NullAddress::NullAddress () protected
The constructor.
Definition at line 49 of file NullAddress.cc.
                         :
    Address(0, NullAddressSpace::instance()) {
}
NullAddress() [2/2]
TTAProgram::NullAddress::NullAddress (const NullAddress &) private
Copying not allowed.
Member Function Documentation
instance()
NullAddress & TTAProgram::NullAddress::instance () static
Returns an instance of NullAddress class (singleton).
Returns
Singleton instance of NullAddress class.
Definition at line 65 of file NullAddress.cc.
                      {
    return instance_;
}
References instance_.
Referenced by TTAProgram::NullInstruction::address(), TTAProgram::NullProcedure::address(), TTAProgram::NullProcedure::endAddress(), TTAProgram::NullProgram::entryAddress(), TTAProgram::NullProcedure::startAddress(), and TTAProgram::NullProgram::startAddress().
location()
UIntWord TTAProgram::NullAddress::location () const
Aborts program with error log message.
Returns
0.
Definition at line 75 of file NullAddress.cc.
{
    abortWithError("location()");
    return 0;
}
References abortWithError.
operator=()
NullAddress & TTAProgram::NullAddress::operator= (const NullAddress &) private
Assignment not allowed.
space()
const AddressSpace & TTAProgram::NullAddress::space () const
Aborts program with error log message.
Returns
A null address space.
Definition at line 86 of file NullAddress.cc.
{
    abortWithError("space()");
    return NullAddressSpace::instance();
}
References abortWithError, and TTAMachine::NullAddressSpace::instance().
Member Data Documentation
instance_
NullAddress TTAProgram::NullAddress::instance_ static private
Definition at line 62 of file NullAddress.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullAddress.hh
NullAddress.cc