OpenASIP: ProximPortWindow Class Reference
ProximPortWindow Class Reference
#include <ProximPortWindow.hh>
Public Member Functions
ProximPortWindow (ProximMainFrame *parent, int id)
virtual ~ProximPortWindow ()
void showFunctionUnit (const std::string &name)
Public Member Functions inherited from ProximUnitWindow
ProximUnitWindow (ProximMainFrame *parent, int id)
virtual ~ProximUnitWindow ()
Public Member Functions inherited from ProximSimulatorWindow
virtual void reset ()
Private Member Functions
virtual void reinitialize ()
virtual void update ()
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Protected Attributes inherited from ProximUnitWindow
SimulatorFrontend * simulator_
Simulator instance .
wxChoice * unitChoice_
Unit choicer widget.
wxChoice * modeChoice_
Value display mode choicer widget.
wxListCtrl * valueList_
List widget for the values.
Static Protected Attributes inherited from ProximUnitWindow
static const wxString MODE_INT = _T("Int")
String for the mode choicer integer mode.
static const wxString MODE_UNSIGNED = _T("Unsigned")
String for the mode choicer unsigned integer mode.
static const wxString MODE_HEX = _T("Hex")
String for the mode choicer hexadecimal mode.
static const wxString MODE_BIN = _T("Binary")
String for the mode choicer binary mode.
Detailed Description
Proxim subwindow which displays function unit port values.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 47 of file ProximPortWindow.hh.
Constructor & Destructor Documentation
ProximPortWindow()
ProximPortWindow::ProximPortWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 64 of file ProximPortWindow.cc.
                                    :
    ProximUnitWindow(parent, id) {
    valueList_->InsertColumn(0, _T("Port"), wxLIST_FORMAT_LEFT, 100);
    valueList_->InsertColumn(1, _T("Value"), wxLIST_FORMAT_RIGHT, 120);
    if (simulator_->isSimulationInitialized() ||
    simulator_->isSimulationStopped() ||
    simulator_->hasSimulationEnded()) {
    reinitialize();
    }
}
References SimulatorFrontend::hasSimulationEnded(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationStopped(), reinitialize(), ProximUnitWindow::simulator_, and ProximUnitWindow::valueList_.
~ProximPortWindow()
ProximPortWindow::~ProximPortWindow () virtual
Destructor.
Definition at line 83 of file ProximPortWindow.cc.
{
}
Member Function Documentation
reinitialize()
void ProximPortWindow::reinitialize () private virtual
Sets the available function unit selections in the function unit choice.
Reimplemented from ProximUnitWindow.
Definition at line 91 of file ProximPortWindow.cc.
{
    unitChoice_->Clear();
    string gcuName = simulator_->machine().controlUnit()->name();
    unitChoice_->Append(WxConversion::toWxString(gcuName));
    const TTAMachine::Machine::FunctionUnitNavigator& navigator =
    simulator_->machine().functionUnitNavigator();
    for (int i = 0; i < navigator.count(); i++) {
    string fuName = navigator.item(i)->name();
    unitChoice_->Append(WxConversion::toWxString(fuName));
    }
    unitChoice_->SetSelection(0);
    update();
}
References TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::Component::name(), ProximUnitWindow::simulator_, WxConversion::toWxString(), ProximUnitWindow::unitChoice_, and update().
Referenced by ProximPortWindow().
showFunctionUnit()
void ProximPortWindow::showFunctionUnit (const std::string & name)
Changes unit selection to function unit with given name.
Parameters
name Name of the function unit to select.
Definition at line 117 of file ProximPortWindow.cc.
{
    unitChoice_->SetStringSelection(WxConversion::toWxString(name));
    update();
}
References WxConversion::toWxString(), ProximUnitWindow::unitChoice_, and update().
Referenced by ProximShowPortsCmd::Do().
update()
void ProximPortWindow::update () private virtual
Updates the value list with port values of the selected function unit.
Reimplemented from ProximUnitWindow.
Definition at line 126 of file ProximPortWindow.cc.
{
    valueList_->DeleteAllItems();
    MachineState& machState = simulator_->machineState();
    const TTAMachine::Machine::FunctionUnitNavigator& navigator =
    simulator_->machine().functionUnitNavigator();
    int fuIndex = unitChoice_->GetSelection();
    FunctionUnit* fu = NULL;
    // FU Choice item with index 0 is the control unit.
    if (fuIndex == 0) {
    fu = simulator_->machine().controlUnit();
    } else {
    fu = navigator.item(fuIndex - 1);
    }
    // Append all ports of the function unit to the port list.
    for (int i = 0; i < fu->portCount(); i++) {
    string portName = fu->port(i)->name();
    const PortState& state = machState.portState(portName, fu->name());
    wxString value;
        wxString mode = modeChoice_->GetStringSelection();
        if (mode == MODE_UNSIGNED) {
        value = WxConversion::toWxString(state.value().unsignedValue());
        } else if (mode == MODE_INT) {
            int intValue = state.value().intValue();
        value = WxConversion::toWxString(intValue);
        } else if (mode == MODE_HEX) {
        value = WxConversion::toWxString(
                Conversion::toHexString(state.value().unsignedValue()));
        } else if (mode == MODE_BIN) {
            int intValue = state.value().unsignedValue();
        value = WxConversion::toWxString(
                Conversion::toBinString(intValue));
        }
    valueList_->InsertItem(i, WxConversion::toWxString(portName));
    valueList_->SetItem(i, 1, value);
    }
}
References TTAMachine::Machine::controlUnit(), TTAMachine::Machine::functionUnitNavigator(), SimValue::intValue(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), SimulatorFrontend::machineState(), ProximUnitWindow::MODE_BIN, ProximUnitWindow::MODE_HEX, ProximUnitWindow::MODE_INT, ProximUnitWindow::MODE_UNSIGNED, ProximUnitWindow::modeChoice_, TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), MachineState::portState(), ProximUnitWindow::simulator_, Conversion::toBinString(), Conversion::toHexString(), WxConversion::toWxString(), ProximUnitWindow::unitChoice_, SimValue::unsignedValue(), RegisterState::value(), and ProximUnitWindow::valueList_.
Referenced by reinitialize(), and showFunctionUnit().
The documentation for this class was generated from the following files:
ProximPortWindow.hh
ProximPortWindow.cc