OpenASIP: MifImageWriter Class Reference
MifImageWriter Class Reference
#include <MifImageWriter.hh>
Public Member Functions
MifImageWriter (const BitVector &bits, int rowLength)
virtual ~MifImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Private Member Functions
void writeHeader (std::ostream &stream) const
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Definition at line 17 of file MifImageWriter.hh.
Constructor & Destructor Documentation
MifImageWriter()
MifImageWriter::MifImageWriter (const BitVector & bits, int rowLength)
The constructor.
Parameters
bits The bits to be written.
rowLength The length of the row in the output stream.
Definition at line 38 of file MifImageWriter.cc.
                                                                  :
    AsciiImageWriter(bits,rowLength) {
}
~MifImageWriter()
MifImageWriter::~MifImageWriter () virtual
The destructor.
Definition at line 45 of file MifImageWriter.cc.
{
}
Member Function Documentation
writeHeader()
void MifImageWriter::writeHeader (std::ostream & stream) const private
Writes the MIF header to the given stream.
Parameters
stream The output stream.
Definition at line 88 of file MifImageWriter.cc.
{
    int wordCount = static_cast<int>(ceil((float)bits().size() / rowLength()));
    stream << COMMENT << endl
           << WIDTH << rowLength() << ";" << endl;
    // empty MIF is invalid
    if (wordCount == 0) {
        stream << DEPTH << "1" << ";" << endl;
    } else {
        stream << DEPTH << wordCount << ";" << endl;
    }
    stream << A_RADIX << endl
           << D_RADIX << endl << endl
           << BEGIN << endl;
}
References A_RADIX, BEGIN, AsciiImageWriter::bits(), COMMENT, D_RADIX, DEPTH, AsciiImageWriter::rowLength(), and WIDTH.
Referenced by writeImage().
writeImage()
void MifImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bits to the given stream.
Parameters
stream The output stream.
Reimplemented from AsciiImageWriter.
Definition at line 53 of file MifImageWriter.cc.
{
    int wordCount =
        static_cast<int>(ceil((float)bits().size() / rowLength()));
    writeHeader(stream);
    int address = 0;
    if (wordCount == 0) {
        // empty MIF is invalid, fill one row with zeroes
        stream << address << INDENT << ":" << INDENT;
        for (int i = 0; i < rowLength(); i++) {
            stream << "0";
        }
        stream << ";" << endl;
    } else {
        bool padEndings = false;
        for (int i = 0; i < wordCount-1; i++) {
            stream << address << INDENT << ":" << INDENT;
            writeSequence(stream, rowLength(), padEndings);
            stream << ";" << endl;
            address++;
        }
        // last line might need to be padded
        padEndings = true;
        stream << address << INDENT << ":" << INDENT;
        writeSequence(stream, rowLength(), padEndings);
        stream << ";" << endl;
    }
    stream << END << endl;
}
References AsciiImageWriter::bits(), END, INDENT, AsciiImageWriter::rowLength(), writeHeader(), and AsciiImageWriter::writeSequence().
The documentation for this class was generated from the following files:
MifImageWriter.hh
MifImageWriter.cc