OpenASIP: StateLocator Class Reference
StateLocator Class Reference
#include <StateLocator.hh>
Public Member Functions
StateLocator ()
virtual ~StateLocator ()
void addState (const TTAMachine::MachinePart &momComponent, StateData &state)
StateData & state (const TTAMachine::MachinePart &momComponent) const
Private Types
typedef std::map< const TTAMachine::MachinePart *, StateData * > StateContainer
State objects indexed by MOM components.
Private Member Functions
StateLocator (const StateLocator &)
Copying not allowed.
StateLocator & operator= (const StateLocator &)
Assignment not allowed.
Private Attributes
StateContainer states_
Contains all the states indexed by MOM components.
Detailed Description
Class that makes it possible to lookup state objects corresponding to MOM component instances.
Definition at line 51 of file StateLocator.hh.
Member Typedef Documentation
StateContainer
typedef std::map<const TTAMachine::MachinePart*, StateData*> StateLocator::StateContainer private
State objects indexed by MOM components.
Definition at line 69 of file StateLocator.hh.
Constructor & Destructor Documentation
StateLocator() [1/2]
StateLocator::StateLocator ()
Constructor.
Definition at line 45 of file StateLocator.cc.
{
}
~StateLocator()
StateLocator::~StateLocator () virtual
Destructor.
Definition at line 51 of file StateLocator.cc.
{
}
StateLocator() [2/2]
StateLocator::StateLocator (const StateLocator &) private
Copying not allowed.
Member Function Documentation
addState()
void StateLocator::addState (const TTAMachine::MachinePart & momComponent, StateData & state)
Adds state to to StateLocator.
Parameters
momComponent Machine object model component.
state Machine state model state.
Definition at line 61 of file StateLocator.cc.
{
    StateContainer::iterator iter = states_.find(&momComponent);
    if (iter != states_.end()) {
        (*iter).second = &state;
    } else {
        states_[&momComponent] = &state;
    }
}
References state(), and states_.
Referenced by MachineStateBuilder::addPortToFU(), and MachineStateBuilder::buildMachineState().
operator=()
StateLocator & StateLocator::operator= (const StateLocator &) private
Assignment not allowed.
state()
StateData & StateLocator::state (const TTAMachine::MachinePart & momComponent) const
Returns state corresponding to the given component.
Parameters
momComponent Component.
Returns
State corresponding to given component.
Exceptions
IllegalParameters If state is not found.
Definition at line 78 of file StateLocator.cc.
{
    StateContainer::const_iterator iter = states_.find(&momComponent);
    if (iter == states_.end()) {
        string msg = "State corresponding to component not found";
        throw IllegalParameters(__FILE__, __LINE__, __func__, msg);
    }
    return *((*iter).second);
}
References __func__, and states_.
Referenced by addState().
Member Data Documentation
states_
StateContainer StateLocator::states_ private
Contains all the states indexed by MOM components.
Definition at line 72 of file StateLocator.hh.
Referenced by addState(), and state().
The documentation for this class was generated from the following files:
StateLocator.hh
StateLocator.cc