OpenASIP: OperationDAGEdge Class Reference
OperationDAGEdge Class Reference
#include <OperationDAGEdge.hh>
Public Member Functions
OperationDAGEdge (int srcOperand, int dstOperand)
OperationDAGEdge (const OperationDAGEdge &other)
virtual ~OperationDAGEdge ()
virtual GraphEdge * clone () const
int srcOperand () const
int dstOperand () const
TCEString toString () const
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual ~GraphEdge ()
virtual int edgeID () const
virtual TCEString dotString () const
virtual bool isBackEdge () const
int weight () const
void setWeight (int w)
Private Attributes
int srcOperand_
int dstOperand_
Detailed Description
Definition at line 38 of file OperationDAGEdge.hh.
Constructor & Destructor Documentation
OperationDAGEdge() [1/2]
OperationDAGEdge::OperationDAGEdge (int srcOperand, int dstOperand)
Definition at line 36 of file OperationDAGEdge.cc.
                                                                 :
    GraphEdge(), srcOperand_(srcOperand), dstOperand_(dstOperand) {}
OperationDAGEdge() [2/2]
OperationDAGEdge::OperationDAGEdge (const OperationDAGEdge & other)
Definition at line 39 of file OperationDAGEdge.cc.
                                                                :
    GraphEdge(other), srcOperand_(other.srcOperand()),
    dstOperand_(other.dstOperand()) {}
~OperationDAGEdge()
virtual OperationDAGEdge::~OperationDAGEdge () inline virtual
Definition at line 42 of file OperationDAGEdge.hh.
{}
Member Function Documentation
clone()
GraphEdge * OperationDAGEdge::clone () const virtual
Clones edge. Needed for dynamic binding, when copying instances through the base class.
Returns
Dynamically allocated copy of the edge.
Reimplemented from GraphEdge.
Definition at line 44 of file OperationDAGEdge.cc.
{
    return new OperationDAGEdge(*this);
}
dstOperand()
int OperationDAGEdge::dstOperand () const
Definition at line 54 of file OperationDAGEdge.cc.
{
    return dstOperand_;
}
References dstOperand_.
Referenced by TDGen::emulatingOpNodeLLVMName(), MemoryAliasAnalyzer::findTwoPartAddressOperands(), OperationDAGBehavior::OperationDAGBehavior(), TDGen::operationNodeToString(), FUGen::subOpConnection(), and OperationDAGConverter::writeNode().
srcOperand()
int OperationDAGEdge::srcOperand () const
Definition at line 49 of file OperationDAGEdge.cc.
{
    return srcOperand_;
}
References srcOperand_.
Referenced by TDGen::emulatingOpNodeLLVMName(), OperationDAGBehavior::OperationDAGBehavior(), FUGen::subOpConnection(), and OperationDAGConverter::writeNode().
toString()
TCEString OperationDAGEdge::toString () const virtual
Return the label of the edge as a string.
Used for printing graph in GraphViz .dot file.
Returns
The edge ID as a string
Reimplemented from GraphEdge.
Definition at line 59 of file OperationDAGEdge.cc.
{
    return Conversion::toString(srcOperand_) + "," +
        Conversion::toString(dstOperand_);
}
References dstOperand_, srcOperand_, and Conversion::toString().
Member Data Documentation
dstOperand_
int OperationDAGEdge::dstOperand_ private
Definition at line 53 of file OperationDAGEdge.hh.
Referenced by dstOperand(), and toString().
srcOperand_
int OperationDAGEdge::srcOperand_ private
Definition at line 52 of file OperationDAGEdge.hh.
Referenced by srcOperand(), and toString().
The documentation for this class was generated from the following files:
OperationDAGEdge.hh
OperationDAGEdge.cc