OpenASIP: OperationContextPimpl Class Reference
OperationContextPimpl Class Reference
#include <OperationContextPimpl.hh>
Public Types
typedef std::map< std::string, OperationState * > StateRegistry
Type of state registry.
Public Member Functions
~OperationContextPimpl ()
void setStateRegistry (StateRegistry &stateRegistry)
void unsetStateRegistry ()
StateRegistry & stateRegistry ()
Private Member Functions
OperationContextPimpl (const TCEString &name)
OperationContextPimpl (const TCEString &name, Memory *memory, InstructionAddress &programCounter, SimValue &returnAddress, int delayCycles)
Memory & memory ()
void setMemory (Memory *memory)
int contextId () const
CycleCount cycleCount () const
void setCycleCountVariable (CycleCount &cycleCount)
InstructionAddress & programCounter ()
InstructionAddress & irfBlockStart ()
void setUpdateProgramCounter (bool value)
bool updateProgramCounter () const
void setSaveReturnAddress (bool value)
bool saveReturnAddress ()
SimValue & returnAddress ()
void advanceClock (OperationContext &)
bool isEmpty () const
bool hasMemoryModel () const
const TCEString & functionUnitName ()
int branchDelayCycles ()
void registerState (OperationState *state)
void unregisterState (const char *name)
OperationState & state (const char *name) const
bool hasState (const char *name) const
void initializeContextId ()
Private Attributes
Memory * memory_
The Memory model instance.
int contextId_
Unique number that identifies a context instance.
InstructionAddress & programCounter_
Simulates the program counter value.
SimValue & returnAddress_
Simulates the procedure return address.
StateRegistry * stateRegistry_
The state registry.
bool saveReturnAddress_
Should the return address be saved?
bool updateProgramCounter_
Should program counter be updated?
CycleCount cycleCount_
Number of times advanceClock() has been called since the creation.
CycleCount * cycleCountVar_
The external variable that contains the current simulation cycle count.
const TCEString FUName_
Name of the FU instance – passed down from MachineStateBuilder.
int branchDelayCycles_
Amount of delay cycles caused by pipeline.
Static Private Attributes
static int nextContextId_ = 0
Context id for the next created context instance.
Friends
class OperationContext
Detailed Description
Definition at line 47 of file OperationContextPimpl.hh.
Member Typedef Documentation
StateRegistry
typedef std::map<std::string, OperationState*> OperationContextPimpl::StateRegistry
Type of state registry.
Definition at line 54 of file OperationContextPimpl.hh.
Constructor & Destructor Documentation
~OperationContextPimpl()
OperationContextPimpl::~OperationContextPimpl ()
Default destructor
Definition at line 101 of file OperationContextPimpl.cc.
{
    delete stateRegistry_;
    stateRegistry_ = NULL;
}
References stateRegistry_.
OperationContextPimpl() [1/2]
OperationContextPimpl::OperationContextPimpl (const TCEString & name) private
Constructor for contexts suitable for basic operations.
Definition at line 54 of file OperationContextPimpl.cc.
                                                                  :
    memory_(NULL),
    programCounter_(dummyInstructionAddress),
    returnAddress_(NullSimValue::instance()),
    saveReturnAddress_(false),
    updateProgramCounter_(false),
    cycleCount_(0),
    cycleCountVar_(NULL),
    FUName_(name),
    branchDelayCycles_(dummyInt) {
    initializeContextId();
    stateRegistry_ = new StateRegistry();
}
References initializeContextId(), and stateRegistry_.
OperationContextPimpl() [2/2]
OperationContextPimpl::OperationContextPimpl (const TCEString & name, Memory * memory, InstructionAddress & programCounter, SimValue & returnAddress, int delayCycles) private
Constructor for contexts suitable for any kinds of operations.
Parameters
memory The memory model instance.
nww The natural word width of the memory model.
programCounter The program counter register.
returnAddress The return address register.
syscallHandler The syscall handler register.
syscallNumber The syscall code register.
Definition at line 79 of file OperationContextPimpl.cc.
                     :
    memory_(memory),
    programCounter_(programCounter),
    returnAddress_(returnAddress),
    saveReturnAddress_(false),
    updateProgramCounter_(false),
    cycleCount_(0),
    cycleCountVar_(NULL),
    FUName_(name),
    branchDelayCycles_(delayCycles) {
    initializeContextId();
    stateRegistry_ = new StateRegistry();
}
References initializeContextId(), and stateRegistry_.
Member Function Documentation
advanceClock()
void OperationContextPimpl::advanceClock (OperationContext & context) private
Advances the internal clock of each registered operation state object.
Definition at line 155 of file OperationContextPimpl.cc.
{
    StateRegistry::iterator i = stateRegistry_->begin();
    while (i != stateRegistry_->end()) {
        (*i).second->advanceClock(context);
        ++i;
    }
    ++cycleCount_;
}
References cycleCount_, and stateRegistry_.
Referenced by OperationContext::advanceClock().
branchDelayCycles()
int OperationContextPimpl::branchDelayCycles () private
Returns the amount of pipeline delay cycles.
Definition at line 360 of file OperationContextPimpl.cc.
{
    return branchDelayCycles_;
}
References branchDelayCycles_.
Referenced by OperationContext::branchDelayCycles().
contextId()
int OperationContextPimpl::contextId () const private
Returns the unique id of the OperationContext instance.
Returns
The unique id for the OperationContext instance.
Definition at line 237 of file OperationContextPimpl.cc.
{
    return contextId_;
}
References contextId_.
Referenced by OperationContext::contextId().
cycleCount()
CycleCount OperationContextPimpl::cycleCount () const private
Returns the count of cycles simulated.
Can be used to implement real time timer operations, etc. Uses the simulator's cycle count, if available, otherwise uses internal cycle counter that is incremented with the advanceClock();
Definition at line 348 of file OperationContextPimpl.cc.
{
    if (cycleCountVar_ != NULL) {
        return *cycleCountVar_;
    } else {
        return cycleCount_;
    }
}
References cycleCount_, and cycleCountVar_.
Referenced by OperationContext::cycleCount(), and setCycleCountVariable().
functionUnitName()
const TCEString & OperationContextPimpl::functionUnitName () private
Returns the FU name of the OperationContext instance.
Returns
The FU name for the OperationContext instance.
Definition at line 247 of file OperationContextPimpl.cc.
{
    return FUName_;
}
References FUName_.
Referenced by OperationContext::functionUnitName().
hasMemoryModel()
bool OperationContextPimpl::hasMemoryModel () const private
Returns true if the context has memory model associated with it.
Returns
True if the context has memory model associated with it.
Definition at line 336 of file OperationContextPimpl.cc.
{
    return (memory_ != NULL);
}
References memory_.
hasState()
bool OperationContextPimpl::hasState (const char * name) const private
Checks if state with given name can be found in the context.
Parameters
name Name of the state.
Returns
True if the state is found.
Definition at line 113 of file OperationContextPimpl.cc.
{
    try {
        state(name);
    } catch (const KeyNotFound&) {
        return false;
    }
    return true;
}
References state().
Referenced by registerState(), and unregisterState().
initializeContextId()
void OperationContextPimpl::initializeContextId () private
Generates an unique context id for the current OperationContext instance.
Definition at line 126 of file OperationContextPimpl.cc.
{
    contextId_ = nextContextId_;
    nextContextId_++;
}
References contextId_, and nextContextId_.
Referenced by OperationContextPimpl(), and OperationContextPimpl().
irfBlockStart()
InstructionAddress & OperationContextPimpl::irfBlockStart () private
isEmpty()
bool OperationContextPimpl::isEmpty () const private
Returns true if there are no operation state objects stored in the context.
Returns
True if there are no operation state objects stored in the context.
Definition at line 326 of file OperationContextPimpl.cc.
{
    return stateRegistry_->size() == 0;
}
References stateRegistry_.
Referenced by OperationContext::isEmpty().
memory()
Memory & OperationContextPimpl::memory () private
Returns a reference to a Memory Module wrapper instance.
This instance can be accessed by the function unit and behavior simulation methods to simulate memory access.
Returns
The Memory instance.
Definition at line 214 of file OperationContextPimpl.cc.
{
    return *memory_;
}
References memory_.
Referenced by OperationContext::memory(), OperationContext::memory(), and setMemory().
programCounter()
InstructionAddress & OperationContextPimpl::programCounter () private
Returns a reference to the current value of the program counter register.
The value of the program counter can be changed through this reference. This is used to implement control transfer operations like jumps and calls to subroutines.
Returns
The program counter value as a reference.
Definition at line 261 of file OperationContextPimpl.cc.
{
    return programCounter_;
}
References programCounter_.
Referenced by OperationContext::programCounter(), and OperationContext::programCounter().
registerState()
void OperationContextPimpl::registerState (OperationState * stateToRegister) private
Registers the operation state for given name.
Called in the createState() of the custom OperationBehavior classes. If state with given identifier is already found in the context, program is aborted. This method is only for internal use. Used by the macro definitions of OSAL.hh.
Parameters
name The identifier for the registered state instance.
stateToRegister The state instance.
Definition at line 178 of file OperationContextPimpl.cc.
{
    string stateName = stateToRegister->name();
    // RegisterState() and unregisterState() are supposed to be used
    // only internally, they are not part of the "client IF", therefore
    // it's reasonable to assert.
    assert(!hasState(stateName.c_str()));
    (*stateRegistry_)[stateName] = stateToRegister;
}
References assert, hasState(), and OperationState::name().
Referenced by OperationContext::registerState().
returnAddress()
SimValue & OperationContextPimpl::returnAddress () private
Returns a reference to the current value of the return address register.
The value of the return address can be changed through this reference. This is used in implementing calls to subroutines.
Returns
The return address value as a reference.
Definition at line 290 of file OperationContextPimpl.cc.
{
    return returnAddress_;
}
References returnAddress_.
Referenced by OperationContext::returnAddress(), and OperationContext::returnAddress().
saveReturnAddress()
bool OperationContextPimpl::saveReturnAddress () private
Returns true if RA should saved before executing next control flow operation.
Returns
The return address value as a reference.
Definition at line 314 of file OperationContextPimpl.cc.
{
    return saveReturnAddress_;
}
References saveReturnAddress_.
Referenced by OperationContext::saveReturnAddress().
setCycleCountVariable()
void OperationContextPimpl::setCycleCountVariable (CycleCount & cycleCount) inline private
Definition at line 74 of file OperationContextPimpl.hh.
{
        cycleCountVar_ = &cycleCount;
    }
References cycleCount(), and cycleCountVar_.
Referenced by OperationContext::setCycleCountVariable().
setMemory()
void OperationContextPimpl::setMemory (Memory * memory) private
Sets the reference to a Memory Module instance.
This instance can be accessed by the function unit and behavior simulation methods to simulate memory access.
Parameters
memory The Memory instance.
Definition at line 227 of file OperationContextPimpl.cc.
{
    memory_ = memory;
}
References memory(), and memory_.
Referenced by OperationContext::setMemory().
setSaveReturnAddress()
void OperationContextPimpl::setSaveReturnAddress (bool value) private
Makes the return address to be saved in the RA register.
This is used by CALL instruction to save the RA before jumping.
Parameters
value Value to set to.
Returns
The return address value as a reference.
Definition at line 303 of file OperationContextPimpl.cc.
{
    saveReturnAddress_ = value;
}
References saveReturnAddress_.
Referenced by OperationContext::setSaveReturnAddress().
setStateRegistry()
void OperationContextPimpl::setStateRegistry (StateRegistry & stateRegistry) inline
Definition at line 56 of file OperationContextPimpl.hh.
        { stateRegistry_ = &stateRegistry; }
References stateRegistry(), and stateRegistry_.
Referenced by OperationContext::setStateRegistry().
setUpdateProgramCounter()
void OperationContextPimpl::setUpdateProgramCounter (bool value) private
TODO
Definition at line 269 of file OperationContextPimpl.cc.
{
    updateProgramCounter_ = value;
}
References updateProgramCounter_.
Referenced by OperationContext::setUpdateProgramCounter().
state()
OperationState & OperationContextPimpl::state (const char * name) const private
Looks up the (concrete) operation state identified by the string name.
Parameters
name The state identifier.
Returns
The found operation state instance.
Exceptions
KeyNotFound If state by name couldn't be found.
Definition at line 139 of file OperationContextPimpl.cc.
{
    StateRegistry::const_iterator i = stateRegistry_->find(name);
    if (i == stateRegistry_->end()) {
        throw KeyNotFound(__FILE__, __LINE__, __func__,
                          "OperationContextPimpl: State not found.");
    }
    return *(*i).second;
}
References __func__, and stateRegistry_.
Referenced by hasState(), and OperationContext::state().
stateRegistry()
StateRegistry & OperationContextPimpl::stateRegistry () inline
Definition at line 59 of file OperationContextPimpl.hh.
{ return *stateRegistry_; }
References stateRegistry_.
Referenced by setStateRegistry(), and OperationContext::stateRegistry().
unregisterState()
void OperationContextPimpl::unregisterState (const char * name) private
Unregisters the operation state of given name.
This method is only for internal use. Used by the macro definitions of OSAL.hh.
Called in deleteState() of the custom OperationBehavior classes. Aborts if there's no state with given identifier in the context.
Definition at line 197 of file OperationContextPimpl.cc.
{
    // RegisterState() and unregisterState() are supposed to be used
    // only internally, they are not part of the "client IF", therefore
    // it's reasonable to assert.
    assert(hasState(name));
    stateRegistry_->erase(name);
}
References assert, hasState(), and stateRegistry_.
Referenced by OperationContext::unregisterState().
unsetStateRegistry()
void OperationContextPimpl::unsetStateRegistry () inline
Definition at line 58 of file OperationContextPimpl.hh.
{ stateRegistry_ = NULL; }
References stateRegistry_.
Referenced by OperationContext::unsetStateRegistry().
updateProgramCounter()
bool OperationContextPimpl::updateProgramCounter () const private
TODO
Definition at line 277 of file OperationContextPimpl.cc.
{
    return updateProgramCounter_;
}
References updateProgramCounter_.
Referenced by OperationContext::updateProgramCounter().
Friends And Related Symbol Documentation
OperationContext
friend class OperationContext friend
Definition at line 49 of file OperationContextPimpl.hh.
Member Data Documentation
branchDelayCycles_
int OperationContextPimpl::branchDelayCycles_ private
Amount of delay cycles caused by pipeline.
Definition at line 127 of file OperationContextPimpl.hh.
Referenced by branchDelayCycles().
contextId_
int OperationContextPimpl::contextId_ private
Unique number that identifies a context instance.
Definition at line 105 of file OperationContextPimpl.hh.
Referenced by contextId(), and initializeContextId().
cycleCount_
CycleCount OperationContextPimpl::cycleCount_ private
Number of times advanceClock() has been called since the creation.
Definition at line 120 of file OperationContextPimpl.hh.
Referenced by advanceClock(), and cycleCount().
cycleCountVar_
CycleCount* OperationContextPimpl::cycleCountVar_ private
The external variable that contains the current simulation cycle count.
Definition at line 123 of file OperationContextPimpl.hh.
Referenced by cycleCount(), and setCycleCountVariable().
FUName_
const TCEString OperationContextPimpl::FUName_ private
Name of the FU instance – passed down from MachineStateBuilder.
Definition at line 125 of file OperationContextPimpl.hh.
Referenced by functionUnitName().
memory_
Memory* OperationContextPimpl::memory_ private
The Memory model instance.
Definition at line 103 of file OperationContextPimpl.hh.
Referenced by hasMemoryModel(), memory(), and setMemory().
nextContextId_
int OperationContextPimpl::nextContextId_ = 0 static private
Context id for the next created context instance.
Id given for the next created OperationContext instance.
Definition at line 107 of file OperationContextPimpl.hh.
Referenced by initializeContextId().
programCounter_
InstructionAddress& OperationContextPimpl::programCounter_ private
Simulates the program counter value.
Definition at line 109 of file OperationContextPimpl.hh.
Referenced by programCounter().
returnAddress_
SimValue& OperationContextPimpl::returnAddress_ private
Simulates the procedure return address.
Definition at line 111 of file OperationContextPimpl.hh.
Referenced by returnAddress().
saveReturnAddress_
bool OperationContextPimpl::saveReturnAddress_ private
Should the return address be saved?
Definition at line 115 of file OperationContextPimpl.hh.
Referenced by saveReturnAddress(), and setSaveReturnAddress().
stateRegistry_
StateRegistry* OperationContextPimpl::stateRegistry_ private
The state registry.
Definition at line 113 of file OperationContextPimpl.hh.
Referenced by advanceClock(), isEmpty(), OperationContextPimpl(), OperationContextPimpl(), setStateRegistry(), state(), stateRegistry(), unregisterState(), unsetStateRegistry(), and ~OperationContextPimpl().
updateProgramCounter_
bool OperationContextPimpl::updateProgramCounter_ private
Should program counter be updated?
Definition at line 117 of file OperationContextPimpl.hh.
Referenced by setUpdateProgramCounter(), and updateProgramCounter().
The documentation for this class was generated from the following files:
OperationContextPimpl.hh
OperationContextPimpl.cc