OpenASIP: BFRescheduleResultClose Class Reference
BFRescheduleResultClose Class Reference
#include <BFRescheduleResultClose.hh>
Public Member Functions
BFRescheduleResultClose (BF2Scheduler &sched, MoveNode &result, int ec)
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & result_
int ec_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 44 of file BFRescheduleResultClose.hh.
Constructor & Destructor Documentation
BFRescheduleResultClose()
BFRescheduleResultClose::BFRescheduleResultClose (BF2Scheduler & sched, MoveNode & result, int ec) inline
Definition at line 47 of file BFRescheduleResultClose.hh.
                                                       :
        BFOptimization(sched), result_(result), ec_(ec) {}
Member Function Documentation
operator()()
bool BFRescheduleResultClose::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 42 of file BFRescheduleResultClose.cc.
{
    if (result_.move().isControlFlowMove()) {
        return false;
    }
    int originalCycle = result_.cycle();
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tPushing result close: " <<  result_.toString() << std::endl;
#endif
    BFUnscheduleMove* unsched = new BFUnscheduleMove(sched_, result_);
    if (!(runPreChild(unsched))) {
        return false;
    }
    BFScheduleTD* td = new BFScheduleTD(sched_, result_, ec_, false);
    if ((!runPreChild(td)) || result_.cycle() == originalCycle) {
        undo();
        return false;
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tPushed result close: " <<  result_.toString() << std::endl;
#endif
    auto succs = new BFRescheduleSuccessorsClose(sched_, result_);
    runPostChild(succs);
    return true;
}
References MoveNode::cycle(), ec_, TTAProgram::Move::isControlFlowMove(), MoveNode::move(), result_, Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, MoveNode::toString(), and Reversible::undo().
Member Data Documentation
ec_
int BFRescheduleResultClose::ec_ private
Definition at line 54 of file BFRescheduleResultClose.hh.
Referenced by operator()().
result_
MoveNode& BFRescheduleResultClose::result_ private
Definition at line 53 of file BFRescheduleResultClose.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFRescheduleResultClose.hh
BFRescheduleResultClose.cc