OpenASIP: MemoryControl Class Reference
MemoryControl Class Reference
#include <MemoryControl.hh>
Public Member Functions
MemoryControl (wxWindow *parent, Memory *memory, wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, const wxString &name=_T("MemoryControl"))
virtual ~MemoryControl ()
void updateView ()
void setMemory (Memory *memory)
void clearHighlights ()
void highlight (Word address, unsigned count, const wxColour &colour)
Private Types
enum {
ID_GRID , ID_CHOICE_MODE , ID_CHOICE_DATA , ID_CHOICE_WIDTH ,
ID_ADDRESS_GO_TO , ID_BUTTON_GO_TO , ID_SPIN_SIZE
}
Private Member Functions
MemoryControl (const MemoryControl &)
Copying not allowed.
MemoryControl & operator= (const MemoryControl &)
Assignment not allowed.
void createContents ()
void onGoTo (wxCommandEvent &event)
void onSizeModeChanged (wxCommandEvent &)
void onDataModeChanged (wxCommandEvent &)
void onWidthChanged (wxCommandEvent &)
void onSize (wxSizeEvent &)
void onWriteMemory (wxGridEvent &event)
void onChar (wxKeyEvent &event)
void clearMemory ()
void copySelection ()
Private Attributes
Memory * memory_
Used for access to memory contents.
int MAUSize_
Size of the minimum addressable unit.
Word start_
Start point of memory.
Word end_
End point of memory.
wxGrid * grid_
Grid in which the contents of the memory is written.
wxChoice * dataMode_
Mode of the data in the cells.
wxChoice * sizeMode_
Mode of the data size.
wxChoice * widthMode_
Grid width choicer.
wxString goToAddress_
Go to address.
MemoryGridTable * table_
Grid contents.
wxBoxSizer * sizer_
Top level sizer of the window.
unsigned mausPerCell_
Number of maus displayed in a cell.
std::vector< unsigned > highlights_
Static Private Attributes
static const std::string SIZE_MAU = "MAU"
Size label for byte size.
static const std::string SIZE_TWO_MAUS = "2 MAUs"
Size label for half word size.
static const std::string SIZE_FOUR_MAUS = "4 MAUs"
Size label for word size.
static const std::string SIZE_EIGHT_MAUS = "8 MAUs"
Size label for word size.
static const std::string DATA_BIN = "Binary"
Data label for binary format.
static const std::string DATA_HEX = "Hex"
Data label for hexa format.
static const std::string DATA_SIGNED_INT = "Signed int"
Data label for signed int format.
static const std::string DATA_UNSIGNED_INT = "Unsigned int"
Data label for unsigned int format.
static const std::string DATA_FLOAT = "Float"
Data label for float format.
static const std::string DATA_DOUBLE = "Double"
Data label for double format.
static const wxString WIDTH_8 = _T("8")
Table width label for 8 column mode.
static const wxString WIDTH_16 = _T("16")
Table width label for 16 column mode.
static const wxString WIDTH_32 = _T("32")
Table width label for 32 column mode.
Detailed Description
Widget for showing the contents of the memory.
The contents of the memory is shown in bytes, half words, words, or double words, and either in binary, hexa, float, decimal, or double format.
Definition at line 53 of file MemoryControl.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_GRID
ID_CHOICE_MODE
ID_CHOICE_DATA
ID_CHOICE_WIDTH
ID_ADDRESS_GO_TO
ID_BUTTON_GO_TO
ID_SPIN_SIZE
Definition at line 145 of file MemoryControl.hh.
         {
        ID_GRID,
        ID_CHOICE_MODE,
        ID_CHOICE_DATA,
    ID_CHOICE_WIDTH,
        ID_ADDRESS_GO_TO,
        ID_BUTTON_GO_TO,
        ID_SPIN_SIZE
    };
Constructor & Destructor Documentation
MemoryControl() [1/2]
MemoryControl::MemoryControl (wxWindow * parent, Memory * memory, wxWindowID id = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, const wxString & name = _T("MemoryControl"))
Constructor.
Parameters
parent Parent window.
memory The memory.
start The start point of memory.
end The end point of memory.
id Id of the widget.
pos Position of the widget.
size Size of the widget.
name Name of the widget.
Definition at line 92 of file MemoryControl.cc.
                          :
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL, name),
    memory_(memory), MAUSize_(memory->MAUSize()),
    start_(memory->start()), end_(memory->end()),
    grid_(NULL),
    goToAddress_(_T("0")),
    table_(NULL),
    sizer_(NULL),
    mausPerCell_(1) {
    createContents();
    dataMode_->Append(WxConversion::toWxString(DATA_BIN));
    dataMode_->Append(WxConversion::toWxString(DATA_HEX));
    dataMode_->Append(WxConversion::toWxString(DATA_SIGNED_INT));
    dataMode_->Append(WxConversion::toWxString(DATA_UNSIGNED_INT));
    dataMode_->Append(WxConversion::toWxString(DATA_FLOAT));
    dataMode_->Append(WxConversion::toWxString(DATA_DOUBLE));
    dataMode_->SetSelection(1);
    sizeMode_->Append(WxConversion::toWxString(SIZE_MAU));
    if (MAUSize_ <= 32) {
        sizeMode_->Append(WxConversion::toWxString(SIZE_TWO_MAUS));
    }
    if (MAUSize_ <= 16) {
        sizeMode_->Append(WxConversion::toWxString(SIZE_FOUR_MAUS));
    }
    if (MAUSize_ <= 8) {
        sizeMode_->Append(WxConversion::toWxString(SIZE_EIGHT_MAUS));
    }
    sizeMode_->SetSelection(0);
    widthMode_->Append(WIDTH_8);
    widthMode_->Append(WIDTH_16);
    widthMode_->Append(WIDTH_32);
    widthMode_->SetSelection(0);
    wxTextValidator hexValidator(wxFILTER_INCLUDE_CHAR_LIST, &goToAddress_);
#if wxCHECK_VERSION(2, 5, 4)
    wxArrayString includes;
    includes.Add(_T("0"));
    includes.Add(_T("1"));
    includes.Add(_T("2"));
    includes.Add(_T("3"));
    includes.Add(_T("4"));
    includes.Add(_T("5"));
    includes.Add(_T("6"));
    includes.Add(_T("7"));
    includes.Add(_T("8"));
    includes.Add(_T("9"));
    includes.Add(_T("a"));
    includes.Add(_T("b"));
    includes.Add(_T("c"));
    includes.Add(_T("d"));
    includes.Add(_T("e"));
    includes.Add(_T("f"));
    includes.Add(_T("A"));
    includes.Add(_T("B"));
    includes.Add(_T("C"));
    includes.Add(_T("D"));
    includes.Add(_T("E"));
    includes.Add(_T("F"));
    hexValidator.SetIncludes(includes);
#else
    hexValidator.SetIncludeList(
    wxStringList(
        _T("0"), _T("1"), _T("2"), _T("3"), _T("4"), _T("5"), _T("6"),
        _T("7"), _T("8"), _T("9"), _T("a"), _T("b"), _T("c"), _T("d"),
        _T("e"), _T("f"), _T("A"), _T("B"), _T("C"), _T("D"), _T("E"),
        _T("F"), NULL));
#endif
    FindWindow(ID_ADDRESS_GO_TO)->SetValidator(hexValidator);
    updateView();
}
References WxConversion::toWxString().
~MemoryControl()
MemoryControl::~MemoryControl () virtual
Destructor.
Definition at line 182 of file MemoryControl.cc.
{
}
MemoryControl() [2/2]
MemoryControl::MemoryControl (const MemoryControl &) private
Copying not allowed.
Member Function Documentation
clearHighlights()
void MemoryControl::clearHighlights ()
Definition at line 553 of file MemoryControl.cc.
{
    int cols = table_->GetNumberCols();
    while (!highlights_.empty()) {
        int row = *highlights_.begin() / cols;
        int col = *highlights_.begin() % cols;
        grid_->SetCellBackgroundColour(row, col, *wxWHITE);
        highlights_.erase(highlights_.begin());
    }
}
References MemoryGridTable::GetNumberCols(), grid_, highlights_, and table_.
Referenced by ProximMemoryWindow::onSimulationStop(), onSizeModeChanged(), onWidthChanged(), and setMemory().
clearMemory()
void MemoryControl::clearMemory () private
Clears the contents of the selected cells, that is, the contents is set to zero.
Definition at line 445 of file MemoryControl.cc.
{
    wxGridCellCoordsArray topLeft = grid_->GetSelectionBlockTopLeft();
    wxGridCellCoordsArray botRight = grid_->GetSelectionBlockBottomRight();
    int currentRow = topLeft[0].GetRow();
    int currentCol = topLeft[0].GetCol();
    int endRow = botRight[0].GetRow();
    int endCol = botRight[0].GetCol();
    while (currentRow <= endRow) {
        currentCol = topLeft[0].GetCol();
        while (currentCol <= endCol) {
            UIntWord data = 0;
            table_->writeValue(currentRow, currentCol, data);
            currentCol++;
        }
        currentRow++;
    }
    updateView();
}
References grid_, table_, updateView(), and MemoryGridTable::writeValue().
Referenced by onChar().
copySelection()
void MemoryControl::copySelection () private
Copies contents of the selected cells to the clipboard.
Definition at line 515 of file MemoryControl.cc.
{
    if (grid_ == NULL || !(grid_->IsSelection())) {
        return;
    }
    if (wxTheClipboard->Open()) {
        wxTextDataObject* data = new wxTextDataObject();
        wxString contents;
        wxGridCellCoordsArray topLs = grid_->GetSelectionBlockTopLeft();
        wxGridCellCoordsArray bottomRs = grid_->GetSelectionBlockBottomRight();
        for (unsigned i = 0; i < topLs.Count(); i++) {
            if (i > 0) {
                contents.Append(_T("\n"));
            }
            int row = topLs.Item(i).GetRow();
            for (; row <= bottomRs.Item(i).GetRow(); row++) {
                int col = topLs.Item(i).GetCol();
                for (; col <= bottomRs.Item(i).GetCol(); col++) {
                    contents.Append(grid_->GetCellValue(row, col));
                    contents.Append(_T(" "));
                }
                contents.Append(_T("\n"));
            }
        }
        data->SetText(contents);
        wxTheClipboard->SetData(data);
        wxTheClipboard->Close();
    }
}
References grid_.
Referenced by onChar().
createContents()
void MemoryControl::createContents () private
Creates the components of the widget.
Definition at line 190 of file MemoryControl.cc.
{
    sizer_ = new wxBoxSizer(wxVERTICAL);
    table_ = new MemoryGridTable(*memory_);
    grid_ = new wxGrid(this, ID_GRID, wxDefaultPosition, wxDefaultSize);
    grid_->SetTable(table_);
    grid_->SetDefaultCellAlignment(wxALIGN_RIGHT, wxALIGN_BOTTOM);
    grid_->SetRowLabelSize(100);
    grid_->SetDefaultCellFont(
        wxFont(12, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL,
               wxFONTWEIGHT_NORMAL));
    grid_->EnableEditing(false);
    grid_->DisableDragGridSize();
    grid_->DisableDragRowSize();
    sizer_->Add(grid_, 1, wxGROW|wxALL, 5);
    dataMode_ = new wxChoice(
        this, ID_CHOICE_DATA, wxDefaultPosition, wxDefaultSize, 0, NULL, 0);
    sizeMode_ = new wxChoice(
        this, ID_CHOICE_MODE, wxDefaultPosition, wxDefaultSize, 0, NULL, 0);
    widthMode_ = new wxChoice(
    this, ID_CHOICE_WIDTH, wxDefaultPosition, wxDefaultSize, 0, NULL, 0);
    wxTextCtrl* addressCtrl = new wxTextCtrl(
        this, ID_ADDRESS_GO_TO, wxT(""), wxDefaultPosition, wxDefaultSize,
        wxTE_PROCESS_ENTER);
    wxButton* goTo = new wxButton(this, ID_BUTTON_GO_TO, wxT("Go to"));
    wxSizer* sizer1 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText* columnsLabel = new wxStaticText(this, -1, _T("Columns:"));
    wxStaticText* asLabel = new wxStaticText(this, -1, _T("as"));
    sizer1->Add(sizeMode_, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(asLabel, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(dataMode_, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(addressCtrl, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(goTo, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(columnsLabel, 0, wxALIGN_CENTER|wxALL, 5);
    sizer1->Add(widthMode_, 0, wxALIGN_CENTER|wxALL, 5);
    sizer_->Add(sizer1, 0, wxALIGN_CENTER|wxALL, 5);
    SetSizer(sizer_);
    Fit();
}
References dataMode_, grid_, ID_ADDRESS_GO_TO, ID_BUTTON_GO_TO, ID_CHOICE_DATA, ID_CHOICE_MODE, ID_CHOICE_WIDTH, ID_GRID, memory_, sizeMode_, sizer_, table_, and widthMode_.
highlight()
void MemoryControl::highlight (Word address, unsigned count, const wxColour & colour)
Definition at line 564 of file MemoryControl.cc.
{
    if (count < 1 || address < start_ || address + count > end_) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    int cols = table_->GetNumberCols();
    for (unsigned i = 0; i < count; i++) {
        unsigned cell = (address - start_ + i) / mausPerCell_;
        int row = cell / cols;
        int col = cell % cols;
        highlights_.push_back(cell);
        grid_->SetCellBackgroundColour(row, col, colour);
    }
}
References __func__, end_, MemoryGridTable::GetNumberCols(), grid_, highlights_, mausPerCell_, start_, and table_.
Referenced by ProximMemoryWindow::onSimulationStop().
onChar()
void MemoryControl::onChar (wxKeyEvent & event) private
Handles the event when key is pressed.
Two hardcoded keyboard commands currently exist: delete and copy.
Parameters
event Key event ot be handled.
Definition at line 421 of file MemoryControl.cc.
{
    if (event.GetKeyCode() == WXK_DELETE) {
        if (grid_->IsSelection()) {
            clearMemory();
        }
    } else if (event.m_controlDown &&
               (event.GetKeyCode() == 'c' ||
                event.GetKeyCode() == 'C' ||
                event.GetKeyCode() == WXK_INSERT)) {
        // Copy contents of the selected cells to the clipboard.
        if (grid_->IsSelection()) {
            copySelection();
        }
    }
}
References clearMemory(), copySelection(), and grid_.
onDataModeChanged()
void MemoryControl::onDataModeChanged (wxCommandEvent &) private
Handles the event when the data mode is changed.
Definition at line 344 of file MemoryControl.cc.
{
    string dataMode = WxConversion::toString(dataMode_->GetStringSelection());
    if (dataMode == DATA_BIN) {
    table_->setDataMode(MemoryGridTable::DATA_BIN);
    } else if (dataMode == DATA_HEX) {
    table_->setDataMode(MemoryGridTable::DATA_HEX);
    } else if (dataMode == DATA_SIGNED_INT) {
    table_->setDataMode(MemoryGridTable::DATA_SIGNED_INT);
    } else if (dataMode == DATA_UNSIGNED_INT) {
    table_->setDataMode(MemoryGridTable::DATA_UNSIGNED_INT);
    } else if (dataMode == DATA_FLOAT) {
    table_->setDataMode(MemoryGridTable::DATA_FLOAT);
    } else if (dataMode == DATA_DOUBLE) {
    table_->setDataMode(MemoryGridTable::DATA_DOUBLE);
    }
    updateView();
}
References DATA_BIN, MemoryGridTable::DATA_BIN, DATA_DOUBLE, MemoryGridTable::DATA_DOUBLE, DATA_FLOAT, MemoryGridTable::DATA_FLOAT, DATA_HEX, MemoryGridTable::DATA_HEX, DATA_SIGNED_INT, MemoryGridTable::DATA_SIGNED_INT, DATA_UNSIGNED_INT, MemoryGridTable::DATA_UNSIGNED_INT, dataMode_, MemoryGridTable::setDataMode(), table_, WxConversion::toString(), and updateView().
onGoTo()
void MemoryControl::onGoTo (wxCommandEvent & event) private
Handles the event when Go to button is pushed.
The row which represents the asked address is selected.
Definition at line 248 of file MemoryControl.cc.
{
    TransferDataFromWindow();
    if (goToAddress_ != _T("")) {
        Word addr = 0;
        try {
            // add 0x to the beginning of the address string
            goToAddress_ = _T("0x") + goToAddress_;
            addr = Conversion::toInt(WxConversion::toString(goToAddress_));
        } catch (const NumberFormatException& n) {
            string msg = "Invalid number: " +
                WxConversion::toString(goToAddress_);
            ErrorDialog dialog(this, WxConversion::toWxString(msg));
            dialog.ShowModal();
            return;
        }
        if (addr >= end_) {
            string msg = "Address " + WxConversion::toString(goToAddress_) +
                " out of memory bounds.";
            ErrorDialog dialog(this, WxConversion::toWxString(msg));
            dialog.ShowModal();
            return;
        }
        int row = 0;
    int col = 0;
    table_->findAddress(addr, row, col);
        //grid_->SetCellBackgroundColour(row, col, *wxGREEN);
        grid_->MakeCellVisible(row, col);
        grid_->SetGridCursor(row, col);
        updateView();
    }
}
References end_, MemoryGridTable::findAddress(), goToAddress_, grid_, table_, Conversion::toInt(), WxConversion::toString(), WxConversion::toWxString(), and updateView().
onSize()
void MemoryControl::onSize (wxSizeEvent & event) private
Handles the event when the size of the window is changed.
Definition at line 368 of file MemoryControl.cc.
{
    updateView();
    event.Skip();
}
References updateView().
onSizeModeChanged()
void MemoryControl::onSizeModeChanged (wxCommandEvent &) private
Handles the event size in which data is shown is changed.
Definition at line 317 of file MemoryControl.cc.
{
    clearHighlights();
    string sizeMode = WxConversion::toString(sizeMode_->GetStringSelection());
    if (sizeMode == SIZE_MAU) {
        mausPerCell_ = 1;
    table_->setSizeMode(MemoryGridTable::SIZE_MAU);
    } else if (sizeMode == SIZE_TWO_MAUS) {
        mausPerCell_ = 2;
    table_->setSizeMode(MemoryGridTable::SIZE_TWO_MAUS);
    } else if (sizeMode == SIZE_FOUR_MAUS) {
        mausPerCell_ = 4;
    table_->setSizeMode(MemoryGridTable::SIZE_FOUR_MAUS);
    } else if (sizeMode == SIZE_EIGHT_MAUS) {
        mausPerCell_ = 8;
    table_->setSizeMode(MemoryGridTable::SIZE_EIGHT_MAUS);
    }
    updateView();
}
References clearHighlights(), mausPerCell_, MemoryGridTable::setSizeMode(), SIZE_EIGHT_MAUS, MemoryGridTable::SIZE_EIGHT_MAUS, SIZE_FOUR_MAUS, MemoryGridTable::SIZE_FOUR_MAUS, SIZE_MAU, MemoryGridTable::SIZE_MAU, SIZE_TWO_MAUS, MemoryGridTable::SIZE_TWO_MAUS, sizeMode_, table_, WxConversion::toString(), and updateView().
onWidthChanged()
void MemoryControl::onWidthChanged (wxCommandEvent &) private
Event handler for the grid width choicer.
Definition at line 496 of file MemoryControl.cc.
{
    clearHighlights();
    wxString width = widthMode_->GetStringSelection();
    if (width == WIDTH_8) {
    table_->setNumberOfColumns(8);
    } else if (width == WIDTH_16) {
    table_->setNumberOfColumns(16);
    } else  if (width == WIDTH_32) {
    table_->setNumberOfColumns(32);
    }
    grid_->SetTable(table_);
    updateView();
}
References clearHighlights(), grid_, MemoryGridTable::setNumberOfColumns(), table_, updateView(), WIDTH_16, WIDTH_32, WIDTH_8, and widthMode_.
onWriteMemory()
void MemoryControl::onWriteMemory (wxGridEvent & event) private
Handles the event when user double clicks a memory cell.
A new dialog is opened in which user can type a new value for the cell.
Definition at line 379 of file MemoryControl.cc.
{
    int column = event.GetCol();
    int row = event.GetRow();
    string stringValue =
        WxConversion::toString(grid_->GetCellValue(row, column));
    int value = 0;
    MemoryValueDialog dialog(this, table_->sizeOfCell() * MAUSize_);
    dialog.CenterOnParent();
    try {
        value = Conversion::toInt(stringValue);
        dialog.setValue(value);
    } catch (const NumberFormatException& n) {
        // can not convert for some reason (do something?)
        dialog.setValue(0);
    }
    if(dialog.ShowModal() == wxID_OK) {
    if (dialog.mode() != NumberControl::MODE_DOUBLE) {
        UIntWord memoryValue = dialog.intValue();
        table_->writeValue(row, column, memoryValue);
    } else {
        DoubleWord memoryValue = dialog.doubleValue();
        table_->writeValue(row, column, memoryValue);
    }
        updateView();
    }
}
References MemoryValueDialog::doubleValue(), grid_, MemoryValueDialog::intValue(), MAUSize_, MemoryValueDialog::mode(), NumberControl::MODE_DOUBLE, MemoryValueDialog::setValue(), MemoryGridTable::sizeOfCell(), table_, Conversion::toInt(), WxConversion::toString(), updateView(), and MemoryGridTable::writeValue().
operator=()
MemoryControl & MemoryControl::operator= (const MemoryControl &) private
Assignment not allowed.
setMemory()
void MemoryControl::setMemory (Memory * memory)
Sets the memory to display in the window.
Parameters
memory Memory to display.
Definition at line 477 of file MemoryControl.cc.
{
    clearHighlights();
    MAUSize_ = memory->MAUSize();
    memory_ = memory;
    start_ = memory->start();
    end_ = memory->end();
    table_ = new MemoryGridTable(*memory_);
    grid_->SetTable(table_);
    updateView();
}
References clearHighlights(), Memory::end(), end_, grid_, Memory::MAUSize(), MAUSize_, memory_, Memory::start(), start_, table_, and updateView().
Referenced by ProximMemoryWindow::loadMemory().
updateView()
void MemoryControl::updateView ()
Updates the contents of the memory.
Data is retrieved only for those area that is visible to user.
Definition at line 290 of file MemoryControl.cc.
{
    unsigned digits = table_->sizeOfCell() * MAUSize_;
    string dataMode = WxConversion::toString(dataMode_->GetStringSelection());
    if (dataMode == DATA_HEX) {
        digits = (digits / 4) + 3;
    } else if (dataMode == DATA_SIGNED_INT ||
               dataMode == DATA_UNSIGNED_INT) {
        digits = (digits / 3) + 1;
    } else if (dataMode == DATA_FLOAT ||
               dataMode == DATA_DOUBLE) {
        digits = 16;
    }
    grid_->SetDefaultColSize(digits * 12, true);
    grid_->ForceRefresh();
}
References DATA_DOUBLE, DATA_FLOAT, DATA_HEX, DATA_SIGNED_INT, DATA_UNSIGNED_INT, dataMode_, grid_, MAUSize_, MemoryGridTable::sizeOfCell(), table_, and WxConversion::toString().
Referenced by clearMemory(), MemoryDialog::handleEvent(), onDataModeChanged(), onGoTo(), ProximMemoryWindow::onSimulationStop(), onSize(), onSizeModeChanged(), onWidthChanged(), onWriteMemory(), and setMemory().
Member Data Documentation
DATA_BIN
const string MemoryControl::DATA_BIN = "Binary" static private
Data label for binary format.
Definition at line 86 of file MemoryControl.hh.
Referenced by onDataModeChanged().
DATA_DOUBLE
const string MemoryControl::DATA_DOUBLE = "Double" static private
Data label for double format.
Definition at line 96 of file MemoryControl.hh.
Referenced by onDataModeChanged(), and updateView().
DATA_FLOAT
const string MemoryControl::DATA_FLOAT = "Float" static private
Data label for float format.
Definition at line 94 of file MemoryControl.hh.
Referenced by onDataModeChanged(), and updateView().
DATA_HEX
const string MemoryControl::DATA_HEX = "Hex" static private
Data label for hexa format.
Definition at line 88 of file MemoryControl.hh.
Referenced by onDataModeChanged(), and updateView().
DATA_SIGNED_INT
const string MemoryControl::DATA_SIGNED_INT = "Signed int" static private
Data label for signed int format.
Definition at line 90 of file MemoryControl.hh.
Referenced by onDataModeChanged(), and updateView().
DATA_UNSIGNED_INT
const string MemoryControl::DATA_UNSIGNED_INT = "Unsigned int" static private
Data label for unsigned int format.
Definition at line 92 of file MemoryControl.hh.
Referenced by onDataModeChanged(), and updateView().
dataMode_
wxChoice* MemoryControl::dataMode_ private
Mode of the data in the cells.
Definition at line 127 of file MemoryControl.hh.
Referenced by createContents(), onDataModeChanged(), and updateView().
end_
Word MemoryControl::end_ private
End point of memory.
Definition at line 123 of file MemoryControl.hh.
Referenced by highlight(), onGoTo(), and setMemory().
goToAddress_
wxString MemoryControl::goToAddress_ private
Go to address.
Definition at line 133 of file MemoryControl.hh.
Referenced by onGoTo().
grid_
wxGrid* MemoryControl::grid_ private
Grid in which the contents of the memory is written.
Definition at line 125 of file MemoryControl.hh.
Referenced by clearHighlights(), clearMemory(), copySelection(), createContents(), highlight(), onChar(), onGoTo(), onWidthChanged(), onWriteMemory(), setMemory(), and updateView().
highlights_
std::vector<unsigned> MemoryControl::highlights_ private
Definition at line 141 of file MemoryControl.hh.
Referenced by clearHighlights(), and highlight().
MAUSize_
int MemoryControl::MAUSize_ private
Size of the minimum addressable unit.
Definition at line 119 of file MemoryControl.hh.
Referenced by onWriteMemory(), setMemory(), and updateView().
mausPerCell_
unsigned MemoryControl::mausPerCell_ private
Number of maus displayed in a cell.
Definition at line 139 of file MemoryControl.hh.
Referenced by highlight(), and onSizeModeChanged().
memory_
Memory* MemoryControl::memory_ private
Used for access to memory contents.
Definition at line 117 of file MemoryControl.hh.
Referenced by createContents(), and setMemory().
SIZE_EIGHT_MAUS
const string MemoryControl::SIZE_EIGHT_MAUS = "8 MAUs" static private
Size label for word size.
Definition at line 83 of file MemoryControl.hh.
Referenced by onSizeModeChanged().
SIZE_FOUR_MAUS
const string MemoryControl::SIZE_FOUR_MAUS = "4 MAUs" static private
Size label for word size.
Definition at line 81 of file MemoryControl.hh.
Referenced by onSizeModeChanged().
SIZE_MAU
const string MemoryControl::SIZE_MAU = "MAU" static private
Size label for byte size.
Definition at line 77 of file MemoryControl.hh.
Referenced by onSizeModeChanged().
SIZE_TWO_MAUS
const string MemoryControl::SIZE_TWO_MAUS = "2 MAUs" static private
Size label for half word size.
Definition at line 79 of file MemoryControl.hh.
Referenced by onSizeModeChanged().
sizeMode_
wxChoice* MemoryControl::sizeMode_ private
Mode of the data size.
Definition at line 129 of file MemoryControl.hh.
Referenced by createContents(), and onSizeModeChanged().
sizer_
wxBoxSizer* MemoryControl::sizer_ private
Top level sizer of the window.
Definition at line 137 of file MemoryControl.hh.
Referenced by createContents().
start_
Word MemoryControl::start_ private
Start point of memory.
Definition at line 121 of file MemoryControl.hh.
Referenced by highlight(), and setMemory().
table_
MemoryGridTable* MemoryControl::table_ private
Grid contents.
Definition at line 135 of file MemoryControl.hh.
Referenced by clearHighlights(), clearMemory(), createContents(), highlight(), onDataModeChanged(), onGoTo(), onSizeModeChanged(), onWidthChanged(), onWriteMemory(), setMemory(), and updateView().
WIDTH_16
const wxString MemoryControl::WIDTH_16 = _T("16") static private
Table width label for 16 column mode.
Definition at line 101 of file MemoryControl.hh.
Referenced by onWidthChanged().
WIDTH_32
const wxString MemoryControl::WIDTH_32 = _T("32") static private
Table width label for 32 column mode.
Definition at line 103 of file MemoryControl.hh.
Referenced by onWidthChanged().
WIDTH_8
const wxString MemoryControl::WIDTH_8 = _T("8") static private
Table width label for 8 column mode.
Definition at line 99 of file MemoryControl.hh.
Referenced by onWidthChanged().
widthMode_
wxChoice* MemoryControl::widthMode_ private
Grid width choicer.
Definition at line 131 of file MemoryControl.hh.
Referenced by createContents(), and onWidthChanged().
The documentation for this class was generated from the following files:
MemoryControl.hh
MemoryControl.cc