OpenASIP: SocketFactory Class Reference
SocketFactory Class Reference
#include <SocketFactory.hh>
Public Member Functions
SocketFactory (EditPolicyFactory &editPolicyFactory)
virtual ~SocketFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
SocketFactory & operator= (SocketFactory &old)
Assignment not allowed.
SocketFactory (SocketFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating socket EditParts corresponding to a given Machine Socket object.
Definition at line 47 of file SocketFactory.hh.
Constructor & Destructor Documentation
SocketFactory() [1/2]
SocketFactory::SocketFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 49 of file SocketFactory.cc.
                                                                :
    EditPartFactory(editPolicyFactory) {
}
~SocketFactory()
SocketFactory::~SocketFactory () virtual
The Destructor.
Definition at line 56 of file SocketFactory.cc.
{
}
SocketFactory() [2/2]
SocketFactory::SocketFactory (SocketFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * SocketFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a socket.
Parameters
component Socket of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the Socket class.
Implements Factory.
Definition at line 66 of file SocketFactory.cc.
{
    EditPart* socketEditPart = EditPartFactory::checkCache(component);
    if (socketEditPart != NULL) {
    return socketEditPart;
    }
    Socket* socket = dynamic_cast<Socket*>(component);
    if (socket != NULL) {
    socketEditPart = new EditPart();
    socketEditPart->setModel(socket);
    Figure* fig = NULL;
    if (socket->direction() == Socket::INPUT) {
        fig = new InputSocketFigure();
    } else if (socket->direction() == Socket::OUTPUT) {
        fig = new OutputSocketFigure();
    } else {
        fig = new UnknownSocketFigure();
    }
    socketEditPart->setFigure(fig);
    socketEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createSocketEditPolicy();
    if (editPolicy != NULL) {
        socketEditPart->installEditPolicy(editPolicy);
    }
    EditPartFactory::writeToCache(socketEditPart);
    return socketEditPart;
    } else {
    return NULL;
    }
}
References EditPartFactory::checkCache(), EditPolicyFactory::createSocketEditPolicy(), TTAMachine::Socket::direction(), EditPartFactory::editPolicyFactory_, TTAMachine::Socket::INPUT, EditPart::installEditPolicy(), TTAMachine::Socket::OUTPUT, EditPart::setFigure(), EditPart::setModel(), EditPart::setSelectable(), and EditPartFactory::writeToCache().
operator=()
SocketFactory & SocketFactory::operator= (SocketFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
SocketFactory.hh
SocketFactory.cc