OpenASIP: NextiCommand Class Reference
NextiCommand Class Reference
#include <NextiCommand.hh>
Public Member Functions
NextiCommand ()
virtual ~NextiCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "nexti" command of the Simulator Control Language.
Definition at line 47 of file NextiCommand.hh.
Constructor & Destructor Documentation
NextiCommand()
NextiCommand::NextiCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 55 of file NextiCommand.cc.
                           :
    SimControlLanguageCommand("nexti") {
}
~NextiCommand()
NextiCommand::~NextiCommand () virtual
Destructor.
Does nothing.
Definition at line 64 of file NextiCommand.cc.
{
}
Member Function Documentation
execute()
bool NextiCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "nexti" command.
Advances simulation to the next machine instructions in current procedure. If the instruction contains a function call, simulation proceeds until control returns from it, to the instruction past the function call. The count argument gives the number of machine instruction to simulate.
Parameters
arguments The count of steps (default is one step).
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 81 of file NextiCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 0, 1)) {
        return false;
    }
    if (!checkSimulationInitialized() && !checkSimulationStopped()) {
        return false;
    }
    unsigned int stepCount = 1;
    if (argumentCount == 1) {
        if (!checkPositiveIntegerArgument(arguments[1])) {
            return false;
        }
        stepCount = arguments[1].integerValue();
    }
    simulatorFrontend().next(stepCount);
    printNextInstruction();
    return true;
}
References CustomCommand::checkArgumentCount(), CustomCommand::checkPositiveIntegerArgument(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), SimulatorFrontend::next(), SimControlLanguageCommand::printNextInstruction(), and SimControlLanguageCommand::simulatorFrontend().
helpText()
std::string NextiCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 113 of file NextiCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_NEXTI).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_NEXTI.
The documentation for this class was generated from the following files:
NextiCommand.hh
NextiCommand.cc