OpenASIP: OSEdAboutCmd Class Reference
OSEdAboutCmd Class Reference
#include <OSEdAboutCmd.hh>
Public Member Functions
OSEdAboutCmd ()
virtual ~OSEdAboutCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdAboutCmd (const OSEdAboutCmd &)
Copying not allowed.
OSEdAboutCmd & operator= (const OSEdAboutCmd &)
Assignment not allowed.
Detailed Description
Command that shows the about dialog of OSEd.
Definition at line 43 of file OSEdAboutCmd.hh.
Constructor & Destructor Documentation
OSEdAboutCmd() [1/2]
OSEdAboutCmd::OSEdAboutCmd ()
Constructor.
Definition at line 48 of file OSEdAboutCmd.cc.
                           :
    GUICommand(OSEdConstants::CMD_NAME_ABOUT, NULL) {
}
Referenced by create().
~OSEdAboutCmd()
OSEdAboutCmd::~OSEdAboutCmd () virtual
Destructor.
Definition at line 55 of file OSEdAboutCmd.cc.
{
}
OSEdAboutCmd() [2/2]
OSEdAboutCmd::OSEdAboutCmd (const OSEdAboutCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdAboutCmd::create () const virtual
Creates a new command.
Returns
The created command.
Implements GUICommand.
Definition at line 74 of file OSEdAboutCmd.cc.
{
    return new OSEdAboutCmd();
}
References OSEdAboutCmd().
Do()
bool OSEdAboutCmd::Do () virtual
Executes the command.
Returns
True.
Implements GUICommand.
Definition at line 84 of file OSEdAboutCmd.cc.
                 {
    OSEdAboutDialog about(parentWindow());
    about.ShowModal();
    return true;
}
References GUICommand::parentWindow().
icon()
string OSEdAboutCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (no icons used).
Implements GUICommand.
Definition at line 106 of file OSEdAboutCmd.cc.
{
    return "";
}
id()
int OSEdAboutCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 64 of file OSEdAboutCmd.cc.
                       {
    return OSEdConstants::CMD_ABOUT;
}
References OSEdConstants::CMD_ABOUT.
isEnabled()
bool OSEdAboutCmd::isEnabled () virtual
Returns true, if command is enabled.
Returns
Always true.
Implements GUICommand.
Definition at line 96 of file OSEdAboutCmd.cc.
{
    return true;
}
operator=()
OSEdAboutCmd & OSEdAboutCmd::operator= (const OSEdAboutCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdAboutCmd.hh
OSEdAboutCmd.cc