OpenASIP: SocketPortConnCmd Class Reference
SocketPortConnCmd Class Reference
#include <SocketPortConnCmd.hh>
Public Member Functions
SocketPortConnCmd (TTAMachine::Socket *socket, TTAMachine::Port *port)
virtual ~SocketPortConnCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
TTAMachine::Socket * socket_
Socket to connect.
TTAMachine::Port * port_
Port to connect.
Detailed Description
Command for connecting/disconencting ports to sockets.
Definition at line 46 of file SocketPortConnCmd.hh.
Constructor & Destructor Documentation
SocketPortConnCmd()
SocketPortConnCmd::SocketPortConnCmd (TTAMachine::Socket * socket, TTAMachine::Port * port)
The Constructor.
Parameters
port Port to connect/disconnect.
socket Socket to connect/disconnect.
Definition at line 45 of file SocketPortConnCmd.cc.
                                                              :
    ComponentCommand(),
    socket_(socket), port_(port) {
}
~SocketPortConnCmd()
SocketPortConnCmd::~SocketPortConnCmd () virtual
The Destructor.
Definition at line 54 of file SocketPortConnCmd.cc.
{
}
Member Function Documentation
Do()
bool SocketPortConnCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 64 of file SocketPortConnCmd.cc.
                      {
    if (port_->isConnectedTo(*socket_)) {
        try {
            port_->detachSocket(*socket_);
        } catch (Exception& e) {
            return false;
        }
    } else {
        try {
            port_->attachSocket(*socket_);
        } catch (Exception& e) {
            return false;
        }
    }
    return true;
}
References TTAMachine::Port::attachSocket(), TTAMachine::Port::detachSocket(), TTAMachine::Port::isConnectedTo(), port_, and socket_.
Member Data Documentation
port_
TTAMachine::Port* SocketPortConnCmd::port_ private
Port to connect.
Definition at line 56 of file SocketPortConnCmd.hh.
Referenced by Do().
socket_
TTAMachine::Socket* SocketPortConnCmd::socket_ private
Socket to connect.
Definition at line 54 of file SocketPortConnCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
SocketPortConnCmd.hh
SocketPortConnCmd.cc