OpenASIP: CustomCommand Class Reference
CustomCommand Class Reference abstract
#include <CustomCommand.hh>
Public Member Functions
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
virtual bool execute (const std::vector< DataObject > &arguments)=0
virtual std::string helpText () const =0
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Private Member Functions
CustomCommand & operator= (const CustomCommand &)
Assignment not allowed.
Private Attributes
std::string name_
The name of the command.
InterpreterContext * context_
Context of the command.
ScriptInterpreter * interpreter_
Interpreter for the command.
Detailed Description
Abstract base class for all CustomCommands for Interpreter.
CustomCommand is a user defined command designed for a particular task.
Definition at line 54 of file CustomCommand.hh.
Constructor & Destructor Documentation
CustomCommand() [1/2]
CustomCommand::CustomCommand (std::string name) explicit
Constructor.
Parameters
name The name of the command.
Definition at line 48 of file CustomCommand.cc.
                                           :
    name_(name), context_(NULL), interpreter_(NULL) {
}
CustomCommand() [2/2]
CustomCommand::CustomCommand (const CustomCommand & cmd)
Copy Constructor.
Parameters
cmd CustomCommand to be copied.
Definition at line 57 of file CustomCommand.cc.
                                                     :
    name_(cmd.name()), context_(cmd.context()),
    interpreter_(cmd.interpreter()) {
}
~CustomCommand()
CustomCommand::~CustomCommand () virtual
Destructor.
Definition at line 66 of file CustomCommand.cc.
{
}
Member Function Documentation
checkArgumentCount()
bool CustomCommand::checkArgumentCount (int argumentCount, int minimum, int maximum)
Checks if the count of arguments fits between the given minimum and maximum arguments.
If the count of arguments is wrong, sets the error message and returns false.
Parameters
argumentCount The count of the arguments.
minimum Minimum amount of arguments.
maximum Maximum amount of arguments.
Returns
True if the count of arguments is valid.
Definition at line 82 of file CustomCommand.cc.
                 {
    if (argumentCount < minimum) {
        DataObject* result = new DataObject();
        result->setString("Not enough arguments.");
        interpreter()->setResult(result);
        return false;
    } else if (argumentCount > maximum) {
        DataObject* result = new DataObject();
        result->setString("Too many arguments.");
        interpreter()->setResult(result);
        return false;
    }
    return true;
}
References interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
Referenced by BackTraceCommand::execute(), CommandsCommand::execute(), ConditionCommand::execute(), DisableBPCommand::execute(), DisassembleCommand::execute(), EnableBPCommand::execute(), HelpCommand::execute(), IgnoreCommand::execute(), InfoCommand::execute(), KillCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), NextiCommand::execute(), QuitCommand::execute(), ResumeCommand::execute(), SettingCommand::execute(), StepiCommand::execute(), SymbolAddressCommand::execute(), UntilCommand::execute(), and WatchCommand::execute().
checkDoubleArgument()
bool CustomCommand::checkDoubleArgument (const DataObject & argument)
Checks if the given argument is a valid double
If the argument is not double, sets the error message and returns false.
Parameters
argument The argument to check.
Returns
True if argument is double.
Definition at line 195 of file CustomCommand.cc.
{
    try {
        argument.doubleValue();
    } catch (const NumberFormatException&) {
        DataObject* result = new DataObject();
        result->setString("Argument not double as expected.");
        interpreter()->setResult(result);
        return false;
    }
    return true;
}
References DataObject::doubleValue(), interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
Referenced by StepiCommand::execute().
checkIntegerArgument()
bool CustomCommand::checkIntegerArgument (const DataObject & argument)
Checks if the given argument is an integer.
If argument is not integer, sets the error message and returns false.
Parameters
argument The argument to check.
Returns
True if argument is integer.
Definition at line 110 of file CustomCommand.cc.
{
    try {
        argument.integerValue();
    } catch (const NumberFormatException&) {
        DataObject* result = new DataObject();
        result->setString("Argument not integer as expected.");
        interpreter()->setResult(result);
        return false;
    }
    return true;
}
References DataObject::integerValue(), interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
Referenced by ConditionCommand::execute().
checkPositiveIntegerArgument()
bool CustomCommand::checkPositiveIntegerArgument (const DataObject & argument)
Checks if the given argument is a positive integer (zero is included).
If argument is not positive integer, sets the error message and returns false. Note that this function assumes that the value range is that of an 'int', i.e., the maximum positive value is less than that of an 'unsigned int'.
Parameters
argument The argument to check.
Returns
True if argument is integer.
Definition at line 134 of file CustomCommand.cc.
{
    bool argumentOk = false;
    try {
        argumentOk = (argument.integerValue() >= 0);
    } catch (const NumberFormatException&) {
        argumentOk = false;
    }
    if (!argumentOk) {
        DataObject* result = new DataObject();
        result->setString("Argument not positive integer as expected.");
        interpreter()->setResult(result);
        return false;
    }
    return true;
}
References DataObject::integerValue(), interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
Referenced by CommandsCommand::execute(), IgnoreCommand::execute(), NextiCommand::execute(), ResumeCommand::execute(), and SimControlLanguageCommand::verifyBreakpointHandles().
checkUnsignedIntegerArgument()
bool CustomCommand::checkUnsignedIntegerArgument (const DataObject & argument)
Checks if the given argument is an unsigned integer.
If argument is not unsigned integer, sets the error message and returns false. This function assumes that the value range of the argument is that of an 'unsigned int'.
Parameters
argument The argument to check.
Returns
True if argument is integer.
Definition at line 164 of file CustomCommand.cc.
{
    try {
        if (argument.stringValue().size() > 0) {
            // ensure the first char is a digit, not a '-'
            if (isdigit(argument.stringValue().at(0))) {
                // this should throw NumberFormatException if the argument
                // cannot be converted to an int
                argument.integerValue();
                return true;
            }
        }
    } catch (const NumberFormatException&) {
    }
    // some of the checks failed, it's not an unsigned int
    DataObject* result = new DataObject();
    result->setString("Argument not positive integer as expected.");
    interpreter()->setResult(result);
    return false;
}
References DataObject::integerValue(), interpreter(), ScriptInterpreter::setResult(), DataObject::setString(), and DataObject::stringValue().
Referenced by MemDumpCommand::execute().
context()
InterpreterContext * CustomCommand::context () const
Referenced by CmdTrigger::execute(), CmdReset::execute(), CmdOutput::execute(), CmdRegister::execute(), CmdMem::execute(), CmdAdvanceClock::execute(), and CmdOutput::helpText().
execute()
virtual bool CustomCommand::execute (const std::vector< DataObject > & arguments) pure virtual
Implemented in CmdHelp, BackTraceCommand, BPCommand, CommandsCommand, ConditionCommand, ConfCommand, DeleteBPCommand, DisableBPCommand, DisassembleCommand, EnableBPCommand, HelpCommand, IgnoreCommand, InfoCommand, KillCommand, MachCommand, MemDumpCommand, MemWriteCommand, NextiCommand, ProgCommand, QuitCommand, ResumeCommand, RunCommand, SettingCommand, StepiCommand, SymbolAddressCommand, TBPCommand, UntilCommand, WatchCommand, CmdTrigger, CmdReset, CmdQuit, CmdOutput, CmdRegister, CmdMem, and CmdAdvanceClock.
Referenced by TclInterpreter::customCommandRedirector(), and SimpleScriptInterpreter::interpret().
helpText()
virtual std::string CustomCommand::helpText () const pure virtual
Implemented in CmdHelp, BackTraceCommand, BPCommand, CommandsCommand, ConditionCommand, ConfCommand, DeleteBPCommand, DisableBPCommand, DisassembleCommand, EnableBPCommand, HelpCommand, IgnoreCommand, InfoCommand, KillCommand, MachCommand, MemDumpCommand, MemWriteCommand, NextiCommand, ProgCommand, QuitCommand, ResumeCommand, RunCommand, SettingCommand, StepiCommand, SymbolAddressCommand, TBPCommand, UntilCommand, WatchCommand, CmdTrigger, CmdReset, CmdQuit, CmdOutput, CmdRegister, CmdMem, and CmdAdvanceClock.
Referenced by CmdHelp::execute(), and HelpCommand::execute().
interpreter()
ScriptInterpreter * CustomCommand::interpreter () const
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), checkArgumentCount(), checkDoubleArgument(), checkIntegerArgument(), SimControlLanguageCommand::checkMachineLoaded(), checkPositiveIntegerArgument(), SimControlLanguageCommand::checkProgramLoaded(), SimControlLanguageCommand::checkSimulationEnded(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationNotAlreadyRunning(), SimControlLanguageCommand::checkSimulationStopped(), checkUnsignedIntegerArgument(), CmdHelp::execute(), BackTraceCommand::execute(), CommandsCommand::execute(), ConditionCommand::execute(), ConfCommand::execute(), DeleteBPCommand::execute(), DisassembleCommand::execute(), HelpCommand::execute(), IgnoreCommand::execute(), InfoRegistersCommand::execute(), InfoImmediatesCommand::execute(), InfoRegFilesCommand::execute(), InfoIunitsCommand::execute(), InfoBussesCommand::execute(), InfoPortsCommand::execute(), InfoSegmentsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), InfoProgramCommand::execute(), InfoCommand::execute(), KillCommand::execute(), MachCommand::execute(), MemDumpCommand::execute(), MemWriteCommand::execute(), ProgCommand::execute(), QuitCommand::execute(), SettingCommand::execute(), SymbolAddressCommand::execute(), CmdTrigger::execute(), CmdReset::execute(), CmdQuit::execute(), CmdOutput::execute(), CmdRegister::execute(), CmdMem::execute(), CmdAdvanceClock::execute(), CmdOutput::helpText(), SimControlLanguageCommand::outputStream(), SimControlLanguageCommand::parseBreakpoint(), SimControlLanguageCommand::parseDataAddressExpression(), SimControlLanguageCommand::parseInstructionAddressExpression(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::setErrorMessage(), SimControlLanguageCommand::setMemoryPointer(), SimControlLanguageCommand::simulatorFrontend(), and SimControlLanguageCommand::verifyBreakpointHandles().
name()
std::string CustomCommand::name () const
Referenced by ScriptInterpreter::addCustomCommand(), TclInterpreter::addCustomCommandToInterpreter(), BackTraceCommand::execute(), and TclInterpreter::removeCustomCommandFromInterpreter().
operator=()
CustomCommand & CustomCommand::operator= (const CustomCommand &) private
Assignment not allowed.
setContext()
void CustomCommand::setContext (InterpreterContext * context)
setInterpreter()
void CustomCommand::setInterpreter (ScriptInterpreter * si)
Referenced by ScriptInterpreter::addCustomCommand().
Member Data Documentation
context_
InterpreterContext* CustomCommand::context_ private
Context of the command.
Definition at line 85 of file CustomCommand.hh.
interpreter_
ScriptInterpreter* CustomCommand::interpreter_ private
Interpreter for the command.
Definition at line 87 of file CustomCommand.hh.
name_
std::string CustomCommand::name_ private
The name of the command.
Definition at line 83 of file CustomCommand.hh.
The documentation for this class was generated from the following files:
CustomCommand.hh
CustomCommand.cc