OpenASIP: WatchCommand Class Reference
WatchCommand Class Reference
#include <WatchCommand.hh>
Public Member Functions
WatchCommand ()
virtual ~WatchCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "watch" command of the Simulator Control Language.
Definition at line 47 of file WatchCommand.hh.
Constructor & Destructor Documentation
WatchCommand()
WatchCommand::WatchCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 50 of file WatchCommand.cc.
                           : SimControlLanguageCommand("watch") {
}
~WatchCommand()
WatchCommand::~WatchCommand () virtual
Destructor.
Does nothing.
Definition at line 58 of file WatchCommand.cc.
{
}
Member Function Documentation
execute()
bool WatchCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "watch" command.
A watch stops the simulation whenever the given expression changes its value. It is possible to add a condition to a watch, to control when the Simulator must stop with increased precision.
Parameters
arguments None. The expression is queried from the user.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 73 of file WatchCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 0, 0)) {
        return false;
    }
    ExpressionScript expression(NULL, "");
    if (!askExpressionFromUser(expression)) {
        return false;
    }
    Watch watch(simulatorFrontend(), expression);
    StopPointManager& stopPointManager =
        simulatorFrontend().stopPointManager();
    return printBreakpointInfo(stopPointManager.add(watch));
}
References StopPointManager::add(), SimControlLanguageCommand::askExpressionFromUser(), CustomCommand::checkArgumentCount(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::simulatorFrontend(), and SimulatorFrontend::stopPointManager().
helpText()
std::string WatchCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 98 of file WatchCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_WATCH).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_WATCH.
The documentation for this class was generated from the following files:
WatchCommand.hh
WatchCommand.cc