OpenASIP: OperationPool Class Reference
OperationPool Class Reference
#include <OperationPool.hh>
Public Member Functions
OperationPool ()
virtual ~OperationPool ()
Operation & operation (const char *name)
OperationIndex & index ()
bool sharesState (const Operation &op)
Static Public Member Functions
static void cleanupCache ()
static void setLLVMTargetInstrInfo (const llvm::MCInstrInfo *tid)
Private Member Functions
OperationPool (const OperationPool &)
Copying not allowed.
OperationPool & operator= (const OperationPool &)
Assignment not allowed.
Private Attributes
OperationPoolPimpl * pimpl_
Private implementation in a separate source file.
Detailed Description
OperationPool provides interface for obtaining operations of the target architecture template.
Definition at line 52 of file OperationPool.hh.
Constructor & Destructor Documentation
OperationPool() [1/2]
OperationPool::OperationPool ()
Constructor.
Records the search paths of the operation modules.
Definition at line 64 of file OperationPool.cc.
                             : pimpl_(new OperationPoolPimpl()) {
}
~OperationPool()
OperationPool::~OperationPool () virtual
Destructor.
Cleans proxies and operations.
Definition at line 72 of file OperationPool.cc.
{
    delete pimpl_;
    pimpl_ = NULL;
}
References pimpl_.
OperationPool() [2/2]
OperationPool::OperationPool (const OperationPool &) private
Copying not allowed.
Member Function Documentation
cleanupCache()
void OperationPool::cleanupCache () static
Cleans up the static Operation cache.
Deletes also the Operation instances, so be sure you are not using them after calling this!
Definition at line 84 of file OperationPool.cc.
{
    OperationPoolPimpl::cleanupCache();
}
References OperationPoolPimpl::cleanupCache().
Referenced by OpsetDialog::TransferDataToWindow().
index()
OperationIndex & OperationPool::index ()
Returns the operation index of operation pool.
Returns
The operation index.
Definition at line 109 of file OperationPool.cc.
                     {
    return pimpl_->index();
}
References OperationPoolPimpl::index(), and pimpl_.
Referenced by ProGeTools::generateableDAGOperations(), Automagic::generateableDAGOperations(), and FUGen::parseOperations().
operation()
Operation & OperationPool::operation (const char * name)
Looks up an operation identified by its name and returns a reference to it.
The first found operation is returned. If operation is not found, a null operation is returned.
Parameters
name The name of the operation.
Returns
The wanted operation.
Definition at line 99 of file OperationPool.cc.
{
    return pimpl_->operation(name);
}
References OperationPoolPimpl::operation(), and pimpl_.
Referenced by TDGen::analyzeMachineVectorRegisterClasses(), ControlFlowGraph::buildMBBFromBB(), AddressSpaceCheck::check(), OperationDAGBuilder::createOperationNode(), TDGen::createSelectPatterns(), FUGen::DAGNodeOperandWidth(), SocketBusConnCmd::Do(), llvm::LLVMTCEBuilder::emitGlobalXXtructorCalls(), OperationDAGSelector::findDags(), TDGen::gatherAllMachineOperations(), ProGeTools::generateableDAGOperations(), Automagic::generateableDAGOperations(), CompiledSimCodeGenerator::generateTriggerCode(), RISCVTDGen::getFormatType(), CompiledSimCodeGenerator::handleOperation(), UniversalFunctionUnit::hasOperation(), MachineConnectivityCheck::isPortApplicableToWidths(), MultiLatencyOperationExecutor::MultiLatencyOperationExecutor(), operandBindingsString(), MachineInfo::operandFromPort(), MachineConnectivityCheck::operandWidth(), OsalInterpreter::operation(), UniversalFunctionUnit::operation(), MachineInfo::osalOperation(), MIDDGNode::osalOperationName(), FUGen::parseOperations(), printLatexFunctionUnitDescription(), ConstantTransformer::runOnMachineFunction(), FUGen::scheduleOperations(), TTAProgram::TerminalFUPort::setHintOperation(), TTAProgram::TerminalFUPort::setOperation(), BFCopyRegWithOp::splitMove(), TDGen::writeInstrInfo(), TDGen::writeIntegerImmediateDefs(), RISCVTDGen::writePatternDefinitions(), TDGen::writeScalarOperationExploitations(), and TDGen::writeVectorLoadStoreOperationExploitations().
operator=()
OperationPool & OperationPool::operator= (const OperationPool &) private
Assignment not allowed.
setLLVMTargetInstrInfo()
void OperationPool::setLLVMTargetInstrInfo (const llvm::MCInstrInfo * tid) static
Used to force loading of OSAL data straight from LLVM backend data instead of the .opp XML files.
Definition at line 132 of file OperationPool.cc.
{
    OperationPoolPimpl::setLLVMTargetInstrInfo(tid);
}
References OperationPoolPimpl::setLLVMTargetInstrInfo().
Referenced by llvm::LLVMTCEScheduler::runOnMachineFunction().
sharesState()
bool OperationPool::sharesState (const Operation & op)
Checks globally from all the loaded operations whether the given operation shares state with any of them.
In case another operation affects this operation or vice-versa, they are assumed to share state. The shares-property has to be in only one of the operation's description.
Definition at line 123 of file OperationPool.cc.
{
    return pimpl_->sharesState(op);
}
References pimpl_, and OperationPoolPimpl::sharesState().
Member Data Documentation
pimpl_
OperationPoolPimpl* OperationPool::pimpl_ private
Private implementation in a separate source file.
Definition at line 71 of file OperationPool.hh.
Referenced by index(), operation(), sharesState(), and ~OperationPool().
The documentation for this class was generated from the following files:
OperationPool.hh
OperationPool.cc