OpenASIP: TTAProgram::BasicBlockStatistics Class Reference
TTAProgram::BasicBlockStatistics Class Reference
#include <BasicBlock.hh>
Public Member Functions
BasicBlockStatistics ()
virtual ~BasicBlockStatistics ()
virtual int moveCount () const
virtual int immediateCount () const
virtual int instructionCount () const
virtual int bypassedCount () const
virtual void setMoveCount (int)
virtual void setImmediateCount (int)
virtual void setInstructionCount (int)
virtual void setBypassedCount (int)
Private Attributes
int moveCount_
int immediateCount_
int instructionCount_
int bypassedCount_
Detailed Description
Represents statistics about single basic block.
Definition at line 55 of file BasicBlock.hh.
Constructor & Destructor Documentation
BasicBlockStatistics()
BasicBlockStatistics::BasicBlockStatistics ()
Constructor, creates statistics structure with zero content.
Definition at line 159 of file BasicBlock.cc.
                                           :
    moveCount_(0),
    immediateCount_(0),
    instructionCount_(0),
    bypassedCount_(0) {
}
~BasicBlockStatistics()
BasicBlockStatistics::~BasicBlockStatistics () virtual
To prevent compiler warning of virtual destructor.
Definition at line 169 of file BasicBlock.cc.
{
}
Member Function Documentation
bypassedCount()
int BasicBlockStatistics::bypassedCount () const virtual
Returns bypassed move count from statistics object.
Returns
count of bypassed moves stored in object
Definition at line 201 of file BasicBlock.cc.
{
    return bypassedCount_;
}
References bypassedCount_.
Referenced by ControlFlowGraph::printStatistics(), ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
immediateCount()
int BasicBlockStatistics::immediateCount () const virtual
Returns immediate count from statistics object.
Returns
count of immediates stored in object
Definition at line 185 of file BasicBlock.cc.
{
    return immediateCount_;
}
References immediateCount_.
Referenced by ControlFlowGraph::printStatistics(), ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
instructionCount()
int BasicBlockStatistics::instructionCount () const virtual
Returns instruction count from statistics object.
Returns
count of instructions stored in object
Definition at line 193 of file BasicBlock.cc.
{
    return instructionCount_;
}
References instructionCount_.
Referenced by ControlFlowGraph::printStatistics(), and ControlFlowGraph::statistics().
moveCount()
int BasicBlockStatistics::moveCount () const virtual
Returns move count from statistics object.
Returns
count of moves stored in object
Definition at line 177 of file BasicBlock.cc.
{
    return moveCount_;
}
References moveCount_.
Referenced by ControlFlowGraph::printStatistics(), ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
setBypassedCount()
void BasicBlockStatistics::setBypassedCount (int count) virtual
Sets the bypassed move count in statistic object.
Parameters
count number of bypassed moves to store in object
Definition at line 239 of file BasicBlock.cc.
{
    bypassedCount_ = count;
}
References bypassedCount_.
Referenced by ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
setImmediateCount()
void BasicBlockStatistics::setImmediateCount (int count) virtual
Sets the immediate count in statistic object.
Parameters
count number of immediates to store in object
Definition at line 220 of file BasicBlock.cc.
{
    immediateCount_ = count;
}
References immediateCount_.
Referenced by ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
setInstructionCount()
void BasicBlockStatistics::setInstructionCount (int count) virtual
Sets the instruction count in statistic object.
Parameters
count number of instructions to store in object
Definition at line 230 of file BasicBlock.cc.
{
    instructionCount_ = count;
}
References instructionCount_.
Referenced by ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
setMoveCount()
void BasicBlockStatistics::setMoveCount (int count) virtual
Sets the move count in statistic object.
Parameters
count number of moves to store in object
Definition at line 210 of file BasicBlock.cc.
{
    moveCount_ = count;
}
References moveCount_.
Referenced by ControlFlowGraph::statistics(), and TTAProgram::BasicBlock::statistics().
Member Data Documentation
bypassedCount_
int TTAProgram::BasicBlockStatistics::bypassedCount_ private
Definition at line 71 of file BasicBlock.hh.
Referenced by bypassedCount(), and setBypassedCount().
immediateCount_
int TTAProgram::BasicBlockStatistics::immediateCount_ private
Definition at line 69 of file BasicBlock.hh.
Referenced by immediateCount(), and setImmediateCount().
instructionCount_
int TTAProgram::BasicBlockStatistics::instructionCount_ private
Definition at line 70 of file BasicBlock.hh.
Referenced by instructionCount(), and setInstructionCount().
moveCount_
int TTAProgram::BasicBlockStatistics::moveCount_ private
Definition at line 68 of file BasicBlock.hh.
Referenced by moveCount(), and setMoveCount().
The documentation for this class was generated from the following files:
BasicBlock.hh
BasicBlock.cc