OpenASIP: TTAMachine::FUPort Class Reference
TTAMachine::FUPort Class Reference
#include <FUPort.hh>
Public Member Functions
FUPort (const std::string &name, int width, FunctionUnit &parent, bool triggers, bool setsOpcode, bool noRegister=false)
FUPort (const ObjectState *state, Unit &parent)
virtual ~FUPort ()
virtual bool isTriggering () const
virtual bool isOpcodeSetting () const
void setTriggering (bool triggers)
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
std::string bindingString () const
void updateBindingString () const
bool isArchitectureEqual (FUPort *port)
bool noRegister () const
void setNoRegister (bool noRegister)
Public Member Functions inherited from TTAMachine::BaseFUPort
virtual ~BaseFUPort ()
FunctionUnit * parentUnit () const
virtual int width () const
void setWidth (int width)
Public Member Functions inherited from TTAMachine::Port
Port (const std::string &name, Unit &parentUnit)
Port (const ObjectState *state, Unit &parentUnit)
virtual ~Port ()
virtual std::string name () const
virtual void setName (const std::string &name)
virtual void attachSocket (Socket &socket)
virtual void detachSocket (Socket &socket)
virtual void detachAllSockets ()
Unit * parentUnit () const
virtual Socket * inputSocket () const
virtual Socket * outputSocket () const
virtual Socket * unconnectedSocket (int index) const
virtual int socketCount () const
virtual bool isConnectedTo (const Socket &socket) const
virtual bool isOutput () const
virtual bool isInput () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_FUPORT = "fu_port"
ObjectState name for FUPort.
static const std::string OSKEY_TRIGGERING = "triggering"
ObjectState attribute key for triggering feature.
static const std::string OSKEY_OPCODE_SETTING = "oc_setting"
ObjectState attribute key for operand code setting feature.
static const std::string OSKEY_NO_REGISTER = "no_register"
ObjectState attribute key for noRegister setting feature.
Static Public Attributes inherited from TTAMachine::BaseFUPort
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bit width of the port.
Static Public Attributes inherited from TTAMachine::Port
static const std::string OSNAME_PORT = "port"
ObjectState name for Port.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_FIRST_SOCKET = "1_socket"
ObjectState attribute key for the name of the connected socket.
static const std::string OSKEY_SECOND_SOCKET = "2_socket"
ObjectState attribute key for the name of the other connected socket.
Protected Member Functions
FUPort (const std::string &name, int width, FunctionUnit &parent, bool triggers, bool setsOpcode, bool noRegister, bool dummy)
Protected Member Functions inherited from TTAMachine::BaseFUPort
BaseFUPort (const std::string &name, int width, FunctionUnit &parent)
BaseFUPort (const ObjectState *state, Unit &parent)
Protected Member Functions inherited from TTAMachine::Port
Port (const std::string &name, FunctionUnit &parentUnit)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Member Functions
void cleanupGuards () const
void cleanupOperandBindings () const
void loadStateWithoutReferences (const ObjectState *state)
Private Attributes
bool triggers_
Specifies whether this is a triggering port.
bool setsOpcode_
Specifies whether this is an operation selecting port.
std::string bindingString_
Binding string describes the operation bindings of of the port to allow fast binding comparison.
bool noRegister_
Detailed Description
Represens an operand, trigger or result port of a function unit.
Definition at line 46 of file FUPort.hh.
Constructor & Destructor Documentation
FUPort() [1/3]
TTAMachine::FUPort::FUPort (const std::string & name, int width, FunctionUnit & parent, bool triggers, bool setsOpcode, bool noRegister = false)
Constructor.
Parameters
name Name of the port.
width Bit width of the port.
parent The function unit to which the port belongs.
triggers If true, writing (or reading) this port starts the execution of a new operation.
setsOpcode If true, writing (or reading) this port selects the operation to be executed. Opcode-setting ports must be triggering.
noRegister If true, the port do not have internal register.
Exceptions
ComponentAlreadyExists If the function unit already has another port by the same name or another port that sets operation code.
OutOfRange If the given bit width is less or equal to zero.
IllegalParameters If setsOpcode argument is true and isTriggering false.
InvalidName If the given name is not a valid component name.
Definition at line 76 of file FUPort.cc.
    : BaseFUPort(name, width, parent),
      triggers_(triggers),
      setsOpcode_(setsOpcode),
      noRegister_(noRegister) {
    const std::string procName = "FUPort::FUPort";
    if (setsOpcode && !triggers) {
        throw IllegalParameters(__FILE__, __LINE__, procName);
    }
    // check that parent unit will not have two operation code setting
    // ports
    if (setsOpcode) {
        for (int i = 0; i < parent.portCount(); i++) {
            BaseFUPort* port = parent.port(i);
            if (port->isOpcodeSetting() && port != this) {
                throw ComponentAlreadyExists(
                    __FILE__, __LINE__, procName);
            }
        }
    }
}
References TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::FunctionUnit::port(), and TTAMachine::Unit::portCount().
FUPort() [2/3]
TTAMachine::FUPort::FUPort (const ObjectState * state, Unit & parent)
Constructor.
Loads its state from the given ObjectState instance but does not create connections to sockets. This constructor is used when the state of a function unit is loaded. Do not use this constructor.
Parameters
state The ObjectState instance.
parent The parent function unit which contains the port.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 153 of file FUPort.cc.
    : BaseFUPort(state, parent), triggers_(false), setsOpcode_(false) {
    loadStateWithoutReferences(state);
    if (setsOpcode_ != triggers_) {
        const std::string procName = "FUPort::FUPort";
        const std::string error = "Port must trigger iff sets opcode.";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                error);
    }
}
References loadStateWithoutReferences(), setsOpcode_, and triggers_.
~FUPort()
TTAMachine::FUPort::~FUPort () virtual
Destructor.
Definition at line 168 of file FUPort.cc.
                {
    cleanupGuards();
    cleanupOperandBindings();
}
References cleanupGuards(), and cleanupOperandBindings().
FUPort() [3/3]
TTAMachine::FUPort::FUPort (const std::string & name, int width, FunctionUnit & parent, bool triggers, bool setsOpcode, bool noRegister, bool dummy) protected
Constructor.
This constructor does not check that the parent unit will not have two operation code setting ports. This constructor is used by UniversalFUPort class.
Parameters
name Name of the port.
width Bit width of the port.
parent The function unit to which the port belongs.
triggers If true, writing (or reading) this port starts the execution of a new operation.
setsOpcode If true, writing (or reading) this port selects the operation to be executed. Opcode-setting ports must be triggering.
noRegister If true, the port do not have internal register.
dummy This parameter is not used and exists only to make some difference to the other constructor.
Exceptions
ComponentAlreadyExists If the function unit already has another port by the same name.
OutOfRange If the given bit width is less or equal to zero.
IllegalParameters If setsOpcode argument is true and isTriggering false.
InvalidName If the given name is not a valid component name.
Definition at line 127 of file FUPort.cc.
    : BaseFUPort(name, width, parent),
      triggers_(triggers),
      setsOpcode_(setsOpcode),
      noRegister_(noRegister) {
    if (setsOpcode != triggers) {
        const std::string procName = "FUPort::FUPort";
        const std::string error = "Port must trigger iff sets opcode.";
        throw IllegalParameters(__FILE__, __LINE__, procName, error);
    }
}
Member Function Documentation
bindingString()
std::string TTAMachine::FUPort::bindingString () const
Returns a description of operand bindings of the port.
This returned string can be used to compare the bindings of to FUPorts using a string comparison because Operations are listed in alphapetical order.
Todo:
this should be moved to BaseFUPort.
Returns
String describing the operand bindings of the port.
Definition at line 280 of file FUPort.cc.
{
    return bindingString_;
}
References bindingString_.
Referenced by isArchitectureEqual(), and TTAMachine::ResourceVector::ResourceVector().
cleanupGuards()
void TTAMachine::FUPort::cleanupGuards () const private
Cleans up the guards that refer to this port.
Definition at line 354 of file FUPort.cc.
{
    // delete guards referencing to this port
    Unit* parent = Port::parentUnit();
    Machine* machine = parent->machine();
    if (machine != NULL) {
        Machine::BusNavigator navi = machine->busNavigator();
        for (int busIndex = 0; busIndex < navi.count(); busIndex++) {
            Bus* bus = navi.item(busIndex);
            int guardIndex = 0;
            while (guardIndex < bus->guardCount()) {
                Guard* guard = bus->guard(guardIndex);
                PortGuard* portGuard = dynamic_cast<PortGuard*>(guard);
                if (portGuard != NULL && portGuard->port() == this) {
                    // guard is removed automatically from bus
                    delete portGuard;
                } else {
                    guardIndex++;
                }
            }
        }
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, TTAMachine::Port::parentUnit(), and TTAMachine::PortGuard::port().
Referenced by ~FUPort().
cleanupOperandBindings()
void TTAMachine::FUPort::cleanupOperandBindings () const private
Removes all the operand bindings of the parent unit that use this port.
Definition at line 388 of file FUPort.cc.
{
    // NOTE! Cannot call directly FUPort::parentUnit because this method is
    // called from FUPort's destructor and it is possible that FunctionUnit
    // instance does not exist any more. This is the case if FunctionUnit is
    // deleted because its destructor is called before Unit's destructor.
    Unit* parentUnit = Port::parentUnit();
    FunctionUnit* parentFU = dynamic_cast<FunctionUnit*>(parentUnit);
    if (parentFU != NULL) {
        for (int i = 0; i < parentFU->operationCount(); i++) {
            HWOperation* operation = parentFU->operation(i);
            operation->unbindPort(*this);
        }
    }
    bindingString_ = "";
}
References bindingString_, TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::Port::parentUnit(), and TTAMachine::HWOperation::unbindPort().
Referenced by ~FUPort().
isArchitectureEqual()
bool TTAMachine::FUPort::isArchitectureEqual (FUPort * port)
Checks if the two ports have same architecture.
Compares also operation bindings. Names are allowed to differ.
Returns
True if the two ports have equal architecture.
Definition at line 332 of file FUPort.cc.
{
    if (triggers_ != port->isTriggering()) {
        return false;
    }
    if (setsOpcode_ != port->isOpcodeSetting()) {
        return false;
    }
    if (width() != port->width()) {
        return false;
    }
    if (bindingString() != port->bindingString()) {
        return false;
    }
    return true;
}
References bindingString(), isOpcodeSetting(), isTriggering(), setsOpcode_, triggers_, and TTAMachine::BaseFUPort::width().
isOpcodeSetting()
bool TTAMachine::FUPort::isOpcodeSetting () const virtual
Returns true if reading (or writing) this port selects the operation to be executed, otherwise false.
Returns
True if reading (or writing) this port selects the operation to be executed, otherwise false.
Implements TTAMachine::BaseFUPort.
Definition at line 195 of file FUPort.cc.
{
    return setsOpcode_;
}
References setsOpcode_.
Referenced by HDB::HDBManager::addFUArchitecture(), OperationBindingCheck::check(), VectorLSGenerator::createVectorLSU(), TTAMachine::FunctionUnit::isArchitectureEqual(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), BEMGenerator::needsSocketCodeTable(), HDB::FUArchitecture::operator==(), SmartHWOperation::port(), and TTAProgram::TerminalFUPort::TerminalFUPort().
isTriggering()
bool TTAMachine::FUPort::isTriggering () const virtual
Returns true if reading (or writing) this port starts the execution of a new operation, otherwise false.
Returns
True if reading (or writing) this port starts the execution of a new operation, otherwise false.
Implements TTAMachine::BaseFUPort.
Definition at line 182 of file FUPort.cc.
{
    return triggers_;
}
References triggers_.
Referenced by ProGe::RV32MicroCodeGenerator::addBPorts(), HDB::HDBManager::addFUArchitecture(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::RV32MicroCodeGenerator::addR1Ports(), ProGe::RV32MicroCodeGenerator::addR1RPorts(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addSPorts(), ProGe::RV32MicroCodeGenerator::addUJPorts(), InputFUBroker::allAvailableResources(), OpsetDialog::bindPorts(), OperationBindingCheck::check(), FUValidator::checkOperations(), ADFCombiner::connectVectorLSU(), UnitPortFactory::createEditPart(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), OpsetDialog::createOperation(), FUGen::createShadowRegisters(), VectorLSGenerator::createVectorLSU(), BasicBlockScheduler::findTriggerFromUnit(), ProgramOperation::findTriggerFromUnit(), OpsetDialog::findTriggerPort(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), BasicBlockScheduler::getTriggerOperand(), TTAMachine::FunctionUnit::isArchitectureEqual(), isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), BF2Scheduler::isTrigger(), AddFUFromHDBDialog::onAdd(), HDB::FUArchitecture::operator==(), BF2Scheduler::preAllocateFunctionUnits(), PlatformIntegrator::readLsuParameters(), BF2Scheduler::releasePortForOp(), FUPortDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), and FUDialog::updatePortList().
loadState()
void TTAMachine::FUPort::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from TTAMachine::BaseFUPort.
Reimplemented in UniversalFUPort.
Definition at line 257 of file FUPort.cc.
{
    const string procName = "FUPort::loadState";
    if (state->name() != OSNAME_FUPORT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    loadStateWithoutReferences(state);
    BaseFUPort::loadState(state);
    updateBindingString();
}
References TTAMachine::BaseFUPort::loadState(), loadStateWithoutReferences(), ObjectState::name(), OSNAME_FUPORT, and updateBindingString().
loadStateWithoutReferences()
void TTAMachine::FUPort::loadStateWithoutReferences (const ObjectState * state) private
Loads its state from the given ObjectState instance but does not create connections to sockets.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 416 of file FUPort.cc.
{
    const string procName = "FUPort::loadStateWithoutReferences";
    try {
        setTriggering(state->intAttribute(OSKEY_TRIGGERING));
        setNoRegister(state->intAttribute(OSKEY_NO_REGISTER));
        if (state->boolAttribute(OSKEY_OPCODE_SETTING)) {
            // Check that parent unit does not contain another operation
            // code setting port. Cannot call directly setOpcodeSetting
            // method because FunctionUnit part of parent unit may not have
            // been instantiated when this method is called (for example if
            // FunctionUnit is created by FunctionUnit(ObjectState*).
            Unit* parentUnit = Port::parentUnit();
            MOMTextGenerator textGenerator;
            for (int i = 0; i < parentUnit->portCount(); i++) {
                Port* port = parentUnit->port(i);
                BaseFUPort* fuPort = dynamic_cast<BaseFUPort*>(port);
                assert(fuPort != NULL);
                if (fuPort->isOpcodeSetting() && fuPort != this) {
                    format text = textGenerator.text(
                        MOMTextGenerator::TXT_OPCODE_SETTING_PORT_EXISTS);
                    text % parentUnit->name();
                    throw ObjectStateLoadingException(
                        __FILE__, __LINE__, procName, text.str());
                }
            }
            setsOpcode_ = true;
            if (!triggers_) {
                format text = textGenerator.text(
                    MOMTextGenerator::TXT_OPCODE_SETTING_MUST_BE_TRIGGERING);
                text % name() % parentUnit->name();
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName, text.str());
            }
        }
    } catch (Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
    updateBindingString();
}
References assert, ObjectState::boolAttribute(), Exception::errorMessage(), ObjectState::intAttribute(), TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::Component::name(), TTAMachine::Port::name(), OSKEY_NO_REGISTER, OSKEY_OPCODE_SETTING, OSKEY_TRIGGERING, TTAMachine::BaseFUPort::parentUnit(), TTAMachine::Port::parentUnit(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), setNoRegister(), setsOpcode_, setTriggering(), Texts::TextGenerator::text(), triggers_, MOMTextGenerator::TXT_OPCODE_SETTING_MUST_BE_TRIGGERING, MOMTextGenerator::TXT_OPCODE_SETTING_PORT_EXISTS, and updateBindingString().
Referenced by FUPort(), and loadState().
noRegister()
bool TTAMachine::FUPort::noRegister () const
Definition at line 469 of file FUPort.cc.
{
    return noRegister_;
}
References noRegister_.
Referenced by ExecutionPipelineResource::canAssignSource(), FUGen::createShadowRegisters(), ExecutionPipelineResource::operandTooLate(), setNoRegister(), and ExecutionPipelineResource::triggerTooEarly().
saveState()
ObjectState * TTAMachine::FUPort::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from TTAMachine::BaseFUPort.
Definition at line 239 of file FUPort.cc.
{
    ObjectState* state = BaseFUPort::saveState();
    state->setName(OSNAME_FUPORT);
    state->setAttribute(OSKEY_TRIGGERING, triggers_);
    state->setAttribute(OSKEY_OPCODE_SETTING, setsOpcode_);
    state->setAttribute(OSKEY_NO_REGISTER, noRegister_);
    return state;
}
References noRegister_, OSKEY_NO_REGISTER, OSKEY_OPCODE_SETTING, OSKEY_TRIGGERING, OSNAME_FUPORT, TTAMachine::BaseFUPort::saveState(), ObjectState::setAttribute(), ObjectState::setName(), setsOpcode_, and triggers_.
setNoRegister()
void TTAMachine::FUPort::setNoRegister (bool noRegister)
Definition at line 479 of file FUPort.cc.
{
    noRegister_ = noRegister;
}
References noRegister(), and noRegister_.
Referenced by loadStateWithoutReferences().
setTriggering()
void TTAMachine::FUPort::setTriggering (bool triggers)
Sets/unsets the port to a triggering and opcode setting.
Triggering port is always the opcode setting port in TCE v1.0 and only one port can trigger in TCE v1.0. If ports parent unit already has a triggering port this ports triggering status is removed.
Parameters
triggers When true, the port is set to a triggering and opcode setting port.
Definition at line 212 of file FUPort.cc.
{
    if (triggers) {
        setsOpcode_ = true;
        FunctionUnit* parent = this->parentUnit();
        if (parent != NULL) {
            for (int i = 0; i < parent->portCount(); i++) {
                BaseFUPort* port = parent->port(i);
                if (port->isTriggering() && port != this) {
                    dynamic_cast<FUPort*>(port)->setTriggering(false);
                    break; // only one other port can be triggering
                }
            }
        }
    } else {
        setsOpcode_ = false;
    }
    triggers_ = triggers;
}
References TTAMachine::BaseFUPort::isTriggering(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), setsOpcode_, setTriggering(), and triggers_.
Referenced by loadStateWithoutReferences(), FUPortDialog::onOK(), and setTriggering().
updateBindingString()
void TTAMachine::FUPort::updateBindingString () const
Updates the string of bindings of the port.
Separated to another method so it's not recomputed every time it's asked.
Todo:
this should be moved to BaseFUPort.
Returns
String of bindings. Operations are listed in alphapetical order.
Definition at line 294 of file FUPort.cc.
{
    if (parentUnit() == NULL) {
        bindingString_ = "";
        return;
    }
    set<string> bindings;
    for (int i = 0; i < parentUnit()->operationCount(); i++) {
        if (parentUnit()->operation(i)->isBound(*this)) {
            string binding = parentUnit()->operation(i)->name();
            binding += ".";
            binding += Conversion::toString(
                parentUnit()->operation(i)->io(*this));
            bindings.insert(binding);
        }
    }
    set<string>::const_iterator iter = bindings.begin();
    string result;
    while (iter != bindings.end()) {
        result += (*iter);
        iter++;
        if (iter != bindings.end()) {
            result += ",";
        }
    }
    bindingString_ = result;
}
References bindingString_, TTAMachine::HWOperation::isBound(), TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::BaseFUPort::parentUnit(), and Conversion::toString().
Referenced by TTAMachine::HWOperation::bindPort(), loadState(), loadStateWithoutReferences(), and TTAMachine::HWOperation::unbindPort().
Member Data Documentation
bindingString_
std::string TTAMachine::FUPort::bindingString_ mutable private
Binding string describes the operation bindings of of the port to allow fast binding comparison.
Definition at line 96 of file FUPort.hh.
Referenced by bindingString(), cleanupOperandBindings(), and updateBindingString().
noRegister_
bool TTAMachine::FUPort::noRegister_ private
Definition at line 98 of file FUPort.hh.
Referenced by noRegister(), saveState(), and setNoRegister().
OSKEY_NO_REGISTER
const string TTAMachine::FUPort::OSKEY_NO_REGISTER = "no_register" static
ObjectState attribute key for noRegister setting feature.
Definition at line 77 of file FUPort.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::machineFUPort(), ADFSerializer::mdfFUPort(), and saveState().
OSKEY_OPCODE_SETTING
const string TTAMachine::FUPort::OSKEY_OPCODE_SETTING = "oc_setting" static
ObjectState attribute key for operand code setting feature.
Definition at line 75 of file FUPort.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::machineFUPort(), ADFSerializer::mdfFUPort(), and saveState().
OSKEY_TRIGGERING
const string TTAMachine::FUPort::OSKEY_TRIGGERING = "triggering" static
ObjectState attribute key for triggering feature.
Definition at line 73 of file FUPort.hh.
Referenced by loadStateWithoutReferences(), ADFSerializer::machineFUPort(), ADFSerializer::mdfFUPort(), and saveState().
OSNAME_FUPORT
const string TTAMachine::FUPort::OSNAME_FUPORT = "fu_port" static
ObjectState name for FUPort.
Definition at line 71 of file FUPort.hh.
Referenced by ADFSerializer::controlUnitToMDF(), ADFSerializer::functionUnitToMDF(), loadState(), TTAMachine::Unit::loadState(), TTAMachine::Unit::loadStateWithoutReferences(), ADFSerializer::machineFUPort(), and saveState().
setsOpcode_
bool TTAMachine::FUPort::setsOpcode_ private
Specifies whether this is an operation selecting port.
Definition at line 93 of file FUPort.hh.
Referenced by FUPort(), isArchitectureEqual(), isOpcodeSetting(), loadStateWithoutReferences(), saveState(), and setTriggering().
triggers_
bool TTAMachine::FUPort::triggers_ private
Specifies whether this is a triggering port.
Definition at line 91 of file FUPort.hh.
Referenced by FUPort(), isArchitectureEqual(), isTriggering(), loadStateWithoutReferences(), saveState(), and setTriggering().
The documentation for this class was generated from the following files:
FUPort.hh
FUPort.cc