OpenASIP: Script Class Reference
Script Class Reference
#include <Script.hh>
Public Member Functions
Script (ScriptInterpreter *interpreter, std::string scriptLine)
Script (ScriptInterpreter *interpreter, std::vector< std::string > &script)
virtual ~Script ()
virtual DataObject execute ()
DataObject lastResult ()
virtual std::vector< std::string > script () const
Protected Attributes
ScriptInterpreter * interpreter_
Interpreter executing the commands.
Private Attributes
DataObject result_
Result of execution.
bool executeCalled_
Flag indicating whether script has been executed or not.
std::vector< std::string > scriptLines_
Contains script.
Detailed Description
Helper class that contains line(s) of script that can be executed on demand.
Definition at line 47 of file Script.hh.
Constructor & Destructor Documentation
Script() [1/2]
Script::Script (ScriptInterpreter * interpreter, std::string scriptLine)
Constructor.
Parameters
interpreter Interpreter for script.
scriptLine A line of script.
Definition at line 47 of file Script.cc.
                                                                   :
    interpreter_(interpreter), executeCalled_(false) {
    scriptLines_.push_back(scriptLine);
}
References scriptLines_.
Script() [2/2]
Script::Script (ScriptInterpreter * interpreter, std::vector< std::string > & script)
Constructor.
Parameters
interpreter Interpreter for script.
script Script lines.
Definition at line 58 of file Script.cc.
{
    interpreter_ = interpreter;
    for (unsigned int i = 0; i < script.size(); i++) {
        scriptLines_.push_back(script[i]);
    }
}
References interpreter_, script(), and scriptLines_.
~Script()
Script::~Script () virtual
Destructor.
Definition at line 71 of file Script.cc.
                {
}
Member Function Documentation
execute()
DataObject Script::execute () virtual
Executes the script.
Returns
The result of execution as a DataObject.
Exceptions
ScriptExecutionFailure If execution of script fails.
NumberFormatException If DataObject operation fails.
Definition at line 82 of file Script.cc.
                {
    Application::initialize();
    for (unsigned int i = 0; i < scriptLines_.size(); i++) {
        if (!interpreter_->interpret(scriptLines_[i])) {
            string method = "Script::execute()";
            string message = "Interpreter error: " +
                interpreter_->result();
            throw ScriptExecutionFailure(__FILE__, __LINE__, method, message);
        }
    }
    DataObject obj;
    obj.setString(interpreter_->result());
    result_ = obj;
    executeCalled_ = true;
    return obj;
}
References executeCalled_, Application::initialize(), ScriptInterpreter::interpret(), interpreter_, ScriptInterpreter::result(), result_, scriptLines_, and DataObject::setString().
Referenced by SimControlLanguageCommand::askConditionFromUser(), SimControlLanguageCommand::askExpressionFromUser(), ConditionScript::conditionOk(), ExpressionScript::resultChanged(), ProximToolbox::testCondition(), and ProximToolbox::testExpression().
lastResult()
DataObject Script::lastResult ()
Referenced by ExpressionScript::resultChanged().
script()
std::vector< std::string > Script::script () const virtual
Returns the script.
Returns
The script.
Reimplemented in TclConditionScript.
Definition at line 106 of file Script.cc.
                     {
    return scriptLines_;
}
References scriptLines_.
Referenced by ConditionScript::conditionOk(), Watch::description(), StopPoint::description(), ProximBreakpointWindow::refreshStopPoints(), Script(), BreakpointPropertiesDialog::TransferDataToWindow(), and WatchPropertiesDialog::TransferDataToWindow().
Member Data Documentation
executeCalled_
bool Script::executeCalled_ private
Flag indicating whether script has been executed or not.
Definition at line 63 of file Script.hh.
Referenced by execute().
interpreter_
ScriptInterpreter* Script::interpreter_ protected
Interpreter executing the commands.
Definition at line 58 of file Script.hh.
Referenced by ConditionScript::conditionOk(), execute(), ExpressionScript::resultChanged(), and Script().
result_
DataObject Script::result_ private
Result of execution.
Definition at line 61 of file Script.hh.
Referenced by execute().
scriptLines_
std::vector<std::string> Script::scriptLines_ private
Contains script.
Definition at line 65 of file Script.hh.
Referenced by execute(), script(), Script(), and Script().
The documentation for this class was generated from the following files:
Script.hh
Script.cc