OpenASIP: IDF::IDFSerializer Class Reference
IDF::IDFSerializer Class Reference
#include <IDFSerializer.hh>
Public Member Functions
IDFSerializer ()
virtual ~IDFSerializer ()
virtual ObjectState * readState ()
virtual void writeState (const ObjectState *state)
MachineImplementation * readMachineImplementation ()
void writeMachineImplementation (const MachineImplementation &implementation)
Public Member Functions inherited from XMLSerializer
XMLSerializer ()
virtual ~XMLSerializer ()
void setSourceFile (const std::string &fileName)
void setSourceString (const std::string &source)
void setDestinationFile (const std::string &fileName)
void setDestinationString (std::string &destination)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
void setXMLNamespace (std::string nsUri)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Static Private Member Functions
static ObjectState * convertToOMFormat (const ObjectState *fileState)
static ObjectState * convertToFileFormat (const ObjectState *omState)
Additional Inherited Members
Protected Member Functions inherited from XMLSerializer
std::string sourceFile () const
Detailed Description
Writer and reader for IDF files.
Definition at line 45 of file IDFSerializer.hh.
Constructor & Destructor Documentation
IDFSerializer()
IDF::IDFSerializer::IDFSerializer ()
The constructor.
Definition at line 90 of file IDFSerializer.cc.
                             : XMLSerializer() {
    setSchemaFile(Environment::schemaDirPath(IDF_SCHEMA_FILE));
    setUseSchema(true);
}
References IDF_SCHEMA_FILE, Environment::schemaDirPath(), XMLSerializer::setSchemaFile(), and XMLSerializer::setUseSchema().
~IDFSerializer()
IDF::IDFSerializer::~IDFSerializer () virtual
The destructor.
Definition at line 99 of file IDFSerializer.cc.
{
}
Member Function Documentation
convertToFileFormat()
ObjectState * IDF::IDFSerializer::convertToFileFormat (const ObjectState * omState) static private
Converts the given ObjectState tree that represents state of a MachineImplementation instance to IDF file format.
Parameters
omState ObjectState tree that represents state of a MachineImplementation instance.
Returns
The newly created ObjectState tree.
Definition at line 352 of file IDFSerializer.cc.
{
    ObjectState* fileState = new ObjectState(ADF_IMPLEMENTATION);
    // the IC&decoder plugin data
    if (omState->hasChild(MachineImplementation::OSNAME_IC_DECODER_PLUGIN)) {
        ObjectState* child = omState->childByName(
            MachineImplementation::OSNAME_IC_DECODER_PLUGIN);
        ObjectState* icdecState = new ObjectState(IC_DECODER_PLUGIN);
        if (child->hasAttribute(
                MachineImplementation::OSKEY_IC_DECODER_NAME)) {
            ObjectState* newChild = new ObjectState(IC_DECODER_PLUGIN_NAME);
            newChild->setValue(
                child->stringAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_NAME));
            icdecState->addChild(newChild);
        }
        if (child->hasAttribute(
                MachineImplementation::OSKEY_IC_DECODER_FILE)) {
            ObjectState* newChild = new ObjectState(
                IC_DECODER_PLUGIN_FILE);
            newChild->setValue(
                child->stringAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_FILE));
            icdecState->addChild(newChild);
        }
        if (child->hasAttribute(
                MachineImplementation::OSKEY_IC_DECODER_HDB)) {
            ObjectState* newChild = new ObjectState(HDB_FILE);
            newChild->setValue(
                child->stringAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_HDB));
            icdecState->addChild(newChild);
        }
        // Parameters
        for (int i = 0; i < child->childCount(); i++) {
            ObjectState* parameter = child->child(i);
            assert(parameter->name() ==
                   MachineImplementation::OSNAME_IC_DECODER_PARAMETER);
            ObjectState* fileParam = new ObjectState(IC_DECODER_PARAMETER);
            icdecState->addChild(fileParam);
            fileParam->setAttribute(
                IC_DECODER_PARAMETER_NAME,
                parameter->stringAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_PARAMETER_NAME));
            if (parameter->hasAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE)) {
                ObjectState* value =
                    new ObjectState(IC_DECODER_PARAMETER_VALUE);
                value->setValue(parameter->stringAttribute(
                   MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE));
                fileParam->addChild(value);
            }
        }
        fileState->addChild(icdecState);
    }
    // decompressor file
    if (omState->hasAttribute(
            MachineImplementation::OSKEY_DECOMPRESSOR_FILE)) {
        ObjectState* newChild = new ObjectState(DECOMPRESSOR_FILE);
        fileState->addChild(newChild);
        newChild->setValue(
            omState->stringAttribute(
                MachineImplementation::OSKEY_DECOMPRESSOR_FILE));
    }
    // add generated FUs.
    ObjectState* fuGens =
        omState->childByName(MachineImplementation::OSNAME_FU_GENERATED);
    for (int i = fuGens->childCount() - 1; i >= 0; --i) {
        ObjectState* child = fuGens->child(i);
        fileState->addChild(new ObjectState(*child));
    }
    // add FU implementations
    ObjectState* fuImpls = omState->childByName(
        MachineImplementation::OSNAME_FU_IMPLEMENTATIONS);
    for (int i = 0; i < fuImpls->childCount(); i++) {
        ObjectState* child = fuImpls->child(i);
        ObjectState* fu = new ObjectState(FU);
        fileState->addChild(fu);
        fu->setAttribute(
            FU_NAME,
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME));
        ObjectState* hdbFile = new ObjectState(HDB_FILE);
        fu->addChild(hdbFile);
        hdbFile->setValue(
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_HDB_FILE));
        ObjectState* id = new ObjectState(FU_ID);
        fu->addChild(id);
        id->setValue(
            child->stringAttribute(UnitImplementationLocation::OSKEY_ID));
    }
    // add RF implementations
    ObjectState* rfImpls = omState->childByName(
        MachineImplementation::OSNAME_RF_IMPLEMENTATIONS);
    for (int i = 0; i < rfImpls->childCount(); i++) {
        ObjectState* child = rfImpls->child(i);
        ObjectState* rf = new ObjectState(RF);
        fileState->addChild(rf);
        rf->setAttribute(
            RF_NAME,
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME));
        ObjectState* hdbFile = new ObjectState(HDB_FILE);
        rf->addChild(hdbFile);
        hdbFile->setValue(
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_HDB_FILE));
        ObjectState* id = new ObjectState(RF_ID);
        rf->addChild(id);
        id->setValue(
            child->stringAttribute(UnitImplementationLocation::OSKEY_ID));
    }
    // add IU implementations
    ObjectState* iuImpls = omState->childByName(
        MachineImplementation::OSNAME_IU_IMPLEMENTATIONS);
    for (int i = 0; i < iuImpls->childCount(); i++) {
        ObjectState* child = iuImpls->child(i);
        ObjectState* iu = new ObjectState(IU);
        fileState->addChild(iu);
        iu->setAttribute(
            IU_NAME,
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME));
        ObjectState* hdbFile = new ObjectState(HDB_FILE);
        iu->addChild(hdbFile);
        hdbFile->setValue(
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_HDB_FILE));
        ObjectState* id = new ObjectState(RF_ID);
        iu->addChild(id);
        id->setValue(
            child->stringAttribute(UnitImplementationLocation::OSKEY_ID));
    }
    // add bus implementations
    ObjectState* busImpls = omState->childByName(
        MachineImplementation::OSNAME_BUS_IMPLEMENTATIONS);
    for (int i = 0; i < busImpls->childCount(); i++) {
        ObjectState* child = busImpls->child(i);
        ObjectState* bus = new ObjectState(BUS);
        fileState->addChild(bus);
        bus->setAttribute(
            BUS_NAME,
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME));
        ObjectState* hdbFile = new ObjectState(HDB_FILE);
        bus->addChild(hdbFile);
        hdbFile->setValue(
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_HDB_FILE));
        ObjectState* id = new ObjectState(BUS_ID);
        bus->addChild(id);
        id->setValue(
            child->stringAttribute(UnitImplementationLocation::OSKEY_ID));
    }
    // add socket implementations
    ObjectState* socketImpls = omState->childByName(
        MachineImplementation::OSNAME_SOCKET_IMPLEMENTATIONS);
    for (int i = 0; i < socketImpls->childCount(); i++) {
        ObjectState* child = socketImpls->child(i);
        ObjectState* socket = new ObjectState(SOCKET);
        fileState->addChild(socket);
        socket->setAttribute(
            IU_NAME,
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME));
        ObjectState* hdbFile = new ObjectState(HDB_FILE);
        socket->addChild(hdbFile);
        hdbFile->setValue(
            child->stringAttribute(
                UnitImplementationLocation::OSKEY_HDB_FILE));
        ObjectState* id = new ObjectState(SOCKET_ID);
        socket->addChild(id);
        id->setValue(
            child->stringAttribute(UnitImplementationLocation::OSKEY_ID));
    }
    return fileState;
}
References ObjectState::addChild(), ADF_IMPLEMENTATION, assert, BUS, BUS_ID, BUS_NAME, ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), DECOMPRESSOR_FILE, FU, FU_ID, FU_NAME, ObjectState::hasAttribute(), ObjectState::hasChild(), HDB_FILE, IC_DECODER_PARAMETER, IC_DECODER_PARAMETER_NAME, IC_DECODER_PARAMETER_VALUE, IC_DECODER_PLUGIN, IC_DECODER_PLUGIN_FILE, IC_DECODER_PLUGIN_NAME, IU, IU_NAME, ObjectState::name(), IDF::MachineImplementation::OSKEY_DECOMPRESSOR_FILE, IDF::UnitImplementationLocation::OSKEY_HDB_FILE, IDF::MachineImplementation::OSKEY_IC_DECODER_FILE, IDF::MachineImplementation::OSKEY_IC_DECODER_HDB, IDF::MachineImplementation::OSKEY_IC_DECODER_NAME, IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_NAME, IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE, IDF::UnitImplementationLocation::OSKEY_ID, IDF::UnitImplementationLocation::OSKEY_UNIT_NAME, IDF::MachineImplementation::OSNAME_BUS_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_FU_GENERATED, IDF::MachineImplementation::OSNAME_FU_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_IC_DECODER_PARAMETER, IDF::MachineImplementation::OSNAME_IC_DECODER_PLUGIN, IDF::MachineImplementation::OSNAME_IU_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_RF_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_SOCKET_IMPLEMENTATIONS, RF, RF_ID, RF_NAME, ObjectState::setAttribute(), ObjectState::setValue(), SOCKET, SOCKET_ID, and ObjectState::stringAttribute().
Referenced by writeState().
convertToOMFormat()
ObjectState * IDF::IDFSerializer::convertToOMFormat (const ObjectState * fileState) static private
Converts the given ObjectState tree that represents an IDF file to format that can be loaded by MachineImplementation instance.
Parameters
fileState ObjectState tree that represents an IDF file.
Returns
The newly created ObjectState tree.
Definition at line 178 of file IDFSerializer.cc.
{
    ObjectState* omState = new ObjectState(
        MachineImplementation::OSNAME_MACHINE_IMPLEMENTATION);
    // add unit implementations
    ObjectState* fuGenerated =
        new ObjectState(MachineImplementation::OSNAME_FU_GENERATED);
    ObjectState* fuImpls = new ObjectState(
        MachineImplementation::OSNAME_FU_IMPLEMENTATIONS);
    ObjectState* rfImpls = new ObjectState(
        MachineImplementation::OSNAME_RF_IMPLEMENTATIONS);
    ObjectState* iuImpls = new ObjectState(
        MachineImplementation::OSNAME_IU_IMPLEMENTATIONS);
    ObjectState* busImpls = new ObjectState(
        MachineImplementation::OSNAME_BUS_IMPLEMENTATIONS);
    ObjectState* socketImpls = new ObjectState(
        MachineImplementation::OSNAME_SOCKET_IMPLEMENTATIONS);
    omState->addChild(fuImpls);
    omState->addChild(rfImpls);
    omState->addChild(iuImpls);
    omState->addChild(busImpls);
    omState->addChild(socketImpls);
    omState->addChild(fuGenerated);
    // the IC&decoder plugin data
    if (fileState->hasChild(IC_DECODER_PLUGIN)) {
        ObjectState* child = fileState->childByName(IC_DECODER_PLUGIN);
        ObjectState* icdecState = new ObjectState(
            MachineImplementation::OSNAME_IC_DECODER_PLUGIN);
        std::string name = "";
        std::string fileName = "";
        std::string hdbFile = "";
        for (int i = 0; i < child->childCount(); i++) {
            ObjectState* attr = child->child(i);
            if (attr->name() == IC_DECODER_PLUGIN_NAME) {
                name = attr->stringValue();
            } else if (attr->name() == IC_DECODER_PLUGIN_FILE) {
                fileName = attr->stringValue();
            } else if (attr->name() == HDB_FILE) {
                hdbFile = attr->stringValue();
            } else if (attr->name() == IC_DECODER_PARAMETER) {
                // IC&decoder parameter.
                ObjectState* parameterState = new ObjectState(
                    MachineImplementation::OSNAME_IC_DECODER_PARAMETER);
                std::string parameterName = attr->stringAttribute(
                    IC_DECODER_PARAMETER_NAME);
                parameterState->setAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_PARAMETER_NAME,
                    parameterName);
                std::string parameterValue = "";
                if (attr->hasChild(IC_DECODER_PARAMETER_VALUE)) {
                    parameterValue = attr->childByName(
                        IC_DECODER_PARAMETER_VALUE)->stringValue();
                }
                parameterState->setAttribute(
                    MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE,
                    parameterValue);
                icdecState->addChild(parameterState);
            }
        }
        icdecState->setAttribute(
            MachineImplementation::OSKEY_IC_DECODER_NAME, name);
        icdecState->setAttribute(
            MachineImplementation::OSKEY_IC_DECODER_FILE, fileName);
        icdecState->setAttribute(
            MachineImplementation::OSKEY_IC_DECODER_HDB, hdbFile);
        omState->addChild(icdecState);
    }
    // decompressor file
    if (fileState->hasChild(DECOMPRESSOR_FILE)) {
        ObjectState* child = fileState->childByName(DECOMPRESSOR_FILE);
        omState->setAttribute(
            MachineImplementation::OSKEY_DECOMPRESSOR_FILE,
            child->stringValue());
    }
    // Generated FUs.
    for (int i = 0; i < fileState->childCount(); i++) {
        ObjectState* child = fileState->child(i);
        if (child->name() != FU_GENERATE) {
            continue;
        }
        ObjectState* impl = new ObjectState(*child);
        fuGenerated->addChild(impl);
    }
    const std::set<std::string> handledElements{FU, RF, IU, SOCKET, BUS};
    for (int i = 0; i < fileState->childCount(); i++) {
        ObjectState* child = fileState->child(i);
        if (!handledElements.count(child->name())) {
            continue;
        }
        ObjectState* impl = new ObjectState(
            UnitImplementationLocation::OSNAME_UNIT_IMPLEMENTATION);
        impl->setAttribute(
            UnitImplementationLocation::OSKEY_HDB_FILE,
            child->childByName(HDB_FILE)->stringValue());
        if (child->name() == FU) {
            fuImpls->addChild(impl);
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME,
                child->stringAttribute(FU_NAME));
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_ID,
                child->childByName(FU_ID)->stringValue());
        } else if (child->name() == RF) {
            rfImpls->addChild(impl);
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME,
                child->stringAttribute(RF_NAME));
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_ID,
                child->childByName(RF_ID)->stringValue());
        } else if (child->name() == IU) {
            iuImpls->addChild(impl);
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME,
                child->stringAttribute(IU_NAME));
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_ID,
                child->childByName(RF_ID)->stringValue());
        } else if (child->name() == BUS) {
            busImpls->addChild(impl);
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME,
                child->stringAttribute(BUS_NAME));
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_ID,
                child->childByName(BUS_ID)->stringValue());
        } else if (child->name() == SOCKET) {
            socketImpls->addChild(impl);
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_UNIT_NAME,
                child->stringAttribute(SOCKET_NAME));
            impl->setAttribute(
                UnitImplementationLocation::OSKEY_ID,
                child->childByName(SOCKET_ID)->stringValue());
        } else {
            assert(false);
        }
    }
    return omState;
}
References ObjectState::addChild(), assert, BUS, BUS_ID, BUS_NAME, ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), DECOMPRESSOR_FILE, FU, FU_GENERATE, FU_ID, FU_NAME, ObjectState::hasChild(), HDB_FILE, IC_DECODER_PARAMETER, IC_DECODER_PARAMETER_NAME, IC_DECODER_PARAMETER_VALUE, IC_DECODER_PLUGIN, IC_DECODER_PLUGIN_FILE, IC_DECODER_PLUGIN_NAME, IU, IU_NAME, ObjectState::name(), IDF::MachineImplementation::OSKEY_DECOMPRESSOR_FILE, IDF::UnitImplementationLocation::OSKEY_HDB_FILE, IDF::MachineImplementation::OSKEY_IC_DECODER_FILE, IDF::MachineImplementation::OSKEY_IC_DECODER_HDB, IDF::MachineImplementation::OSKEY_IC_DECODER_NAME, IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_NAME, IDF::MachineImplementation::OSKEY_IC_DECODER_PARAMETER_VALUE, IDF::UnitImplementationLocation::OSKEY_ID, IDF::UnitImplementationLocation::OSKEY_UNIT_NAME, IDF::MachineImplementation::OSNAME_BUS_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_FU_GENERATED, IDF::MachineImplementation::OSNAME_FU_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_IC_DECODER_PARAMETER, IDF::MachineImplementation::OSNAME_IC_DECODER_PLUGIN, IDF::MachineImplementation::OSNAME_IU_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_MACHINE_IMPLEMENTATION, IDF::MachineImplementation::OSNAME_RF_IMPLEMENTATIONS, IDF::MachineImplementation::OSNAME_SOCKET_IMPLEMENTATIONS, IDF::UnitImplementationLocation::OSNAME_UNIT_IMPLEMENTATION, RF, RF_ID, RF_NAME, ObjectState::setAttribute(), SOCKET, SOCKET_ID, SOCKET_NAME, ObjectState::stringAttribute(), and ObjectState::stringValue().
Referenced by readState().
readMachineImplementation()
MachineImplementation * IDF::IDFSerializer::readMachineImplementation ()
Reads the source IDF file that is set and creates a MachineImplementation instance from it.
Returns
The newly created MachineImplementation instance.
Exceptions
SerializerException If an error occurs while reading the file.
ObjectStateLoadingException If an error occurs while loading the state of MachineImplementation instance.
Definition at line 148 of file IDFSerializer.cc.
{
    ObjectState* omState = readState();
    MachineImplementation* implementation = new MachineImplementation(
        omState);
    delete omState;
    return implementation;
}
References implementation, and readState().
Referenced by IDF::MachineImplementation::loadFromIDF(), loadInputs(), ProGe::ProGeUI::loadMachineImplementation(), ProGe::ProGeUI::loadProcessorConfiguration(), and readIdf().
readState()
ObjectState * IDF::IDFSerializer::readState () virtual
Reads the source file that is set and creates an ObjectState tree that can be loaded by MachineImplementation instance.
Returns
The newly created ObjectState tree.
Exceptions
SerializerException If an error occurs while reading the file.
Reimplemented from XMLSerializer.
Definition at line 111 of file IDFSerializer.cc.
{
    ObjectState* fileState = XMLSerializer::readState();
    ObjectState* omState = convertToOMFormat(fileState);
    // set the source IDF
    omState->setAttribute(
        MachineImplementation::OSKEY_SOURCE_IDF, sourceFile());
    delete fileState;
    return omState;
}
References convertToOMFormat(), IDF::MachineImplementation::OSKEY_SOURCE_IDF, XMLSerializer::readState(), ObjectState::setAttribute(), and XMLSerializer::sourceFile().
Referenced by DSDBManager::implementation(), ProcessorImplementationWindow::onLoadIDF(), readMachineImplementation(), and DSDBManager::writeImplementationToFile().
writeMachineImplementation()
void IDF::IDFSerializer::writeMachineImplementation (const MachineImplementation & implementation)
Writes the given machine implementation to the destination IDF file.
Parameters
implementation The implementation to be written.
Exceptions
SerializerException If an error occurs while writing file.
Definition at line 163 of file IDFSerializer.cc.
{
    ObjectState* omState = implementation.saveState();
    writeState(omState);
    delete omState;
}
References implementation, IDF::MachineImplementation::saveState(), and writeState().
Referenced by ProcessorImplementationWindow::doSaveIDF().
writeState()
void IDF::IDFSerializer::writeState (const ObjectState * state) virtual
Writes the given ObjectState tree created by MachineImplementation::saveState to an IDF file.
Parameters
state ObjectState tree that represents the MachineImplementation instance.
Exceptions
SerializerException If an error occurs while writing the file.
Reimplemented from XMLSerializer.
Definition at line 131 of file IDFSerializer.cc.
{
    ObjectState* fileState = convertToFileFormat(state);
    XMLSerializer::writeState(fileState);
    delete fileState;
}
References convertToFileFormat(), and XMLSerializer::writeState().
Referenced by DSDBManager::addImplementation(), DSDBManager::writeImplementationToFile(), and writeMachineImplementation().
The documentation for this class was generated from the following files:
IDFSerializer.hh
IDFSerializer.cc