OpenASIP: AsciiProgramImageWriter Class Reference
AsciiProgramImageWriter Class Reference
#include <AsciiProgramImageWriter.hh>
Public Member Functions
AsciiProgramImageWriter (const InstructionBitVector &bits)
virtual ~AsciiProgramImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
This class writes ASCII program images.
Definition at line 43 of file AsciiProgramImageWriter.hh.
Constructor & Destructor Documentation
AsciiProgramImageWriter()
AsciiProgramImageWriter::AsciiProgramImageWriter (const InstructionBitVector & bits)
The constructor.
Parameters
bits The program bits to be written.
Definition at line 42 of file AsciiProgramImageWriter.cc.
                                      : AsciiImageWriter(bits, 0) {
}
~AsciiProgramImageWriter()
AsciiProgramImageWriter::~AsciiProgramImageWriter () virtual
The destructor.
Definition at line 50 of file AsciiProgramImageWriter.cc.
{
}
Member Function Documentation
writeImage()
void AsciiProgramImageWriter::writeImage (std::ostream & stream) const virtual
Writes the program image to the given output stream.
Parameters
stream The output stream.
Reimplemented from AsciiImageWriter.
Definition at line 60 of file AsciiProgramImageWriter.cc.
{
    const BitVector& bits = this->bits();
    const InstructionBitVector* programBits =
        dynamic_cast<const InstructionBitVector*>(&bits);
    assert(programBits != NULL);
    unsigned int previousBoundary(0);
    for (unsigned int i = 1; i < programBits->instructionCount(); i++) {
        unsigned int instructionBoundary =
            programBits->instructionStartingPoint(i);
        writeSequence(stream, instructionBoundary - previousBoundary);
        stream << std::endl;
        previousBoundary = instructionBoundary;
    }
    writeSequence(stream, bits.size() - previousBoundary);
    stream << std::endl;
}
References assert, AsciiImageWriter::bits(), InstructionBitVector::instructionCount(), InstructionBitVector::instructionStartingPoint(), and AsciiImageWriter::writeSequence().
The documentation for this class was generated from the following files:
AsciiProgramImageWriter.hh
AsciiProgramImageWriter.cc