OpenASIP: BFRemoveGuardsFromSuccs Class Reference
BFRemoveGuardsFromSuccs Class Reference
#include <BFRemoveGuardsFromSuccs.hh>
Public Member Functions
BFRemoveGuardsFromSuccs (BF2Scheduler &sched, MoveNode &guardWrite, int oldLC, int maxLC)
bool operator() () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & guardWrite_
int oldLC_
int maxLC_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 45 of file BFRemoveGuardsFromSuccs.hh.
Constructor & Destructor Documentation
BFRemoveGuardsFromSuccs()
BFRemoveGuardsFromSuccs::BFRemoveGuardsFromSuccs (BF2Scheduler & sched, MoveNode & guardWrite, int oldLC, int maxLC) inline
Definition at line 47 of file BFRemoveGuardsFromSuccs.hh.
                                                                         :
        BFOptimization(sched),
        guardWrite_(guardWrite), oldLC_(oldLC), maxLC_(maxLC) {}
Member Function Documentation
operator()()
bool BFRemoveGuardsFromSuccs::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 45 of file BFRemoveGuardsFromSuccs.cc.
{
    DataDependenceGraph::EdgeSet outEdges = ddg().outEdges(guardWrite_);
//    std::list<BFRemoveGuardFromSucc*> guardRemoves;
    std::list<MoveNode*> guardRemoveNodes;
    for (auto e: outEdges) {
        if (e->guardUse() &&
            e->dependenceType() == DataDependenceEdge::DEP_RAW) {
            MoveNode& head = ddg().headNode(*e);
            if (head.move().isUnconditional()) {
                std::cerr << "guard edge to uncond move?" << head.toString()
                          << std::endl;
                continue;
            }
            if (head.isScheduled()) {
                // this is not in critical path.
                int cycle = head.cycle();
                if (cycle > maxLC_ + head.guardLatency()) {
                    continue;
                } else {
                    if (canBeSpeculated(head)) {
                        guardRemoveNodes.push_back(&head);
                    } else {
                        maxLC_ = std::min(
                            maxLC_, head.cycle() - head.guardLatency());
                        continue;
                    }
                }
            }
        }
    }
    for (auto i: guardRemoveNodes) {
        MoveNode& mn = *i;
        if (mn.cycle() - mn.guardLatency() <  maxLC_) {
            runPostChild(new BFRemoveGuardFromSucc(sched_, mn));
        }
    }
    if (postChildren_.empty()) {
        return false;
    }
    // if could not improve schedule, return everything back the way it was
    int ddglc = ddg().latestCycle(guardWrite_, ii(), false, false);
    int rmlc = rm().latestCycle(ddglc, guardWrite_);
    if (rmlc <= oldLC_) {
        undo();
        return false;
    }
    return true;
}
References BFOptimization::canBeSpeculated(), MoveNode::cycle(), BFOptimization::ddg(), DataDependenceEdge::DEP_RAW, MoveNode::guardLatency(), guardWrite_, BoostGraph< GraphNode, GraphEdge >::headNode(), BFOptimization::ii(), MoveNode::isScheduled(), TTAProgram::Move::isUnconditional(), DataDependenceGraph::latestCycle(), SimpleResourceManager::latestCycle(), maxLC_, MoveNode::move(), oldLC_, BoostGraph< GraphNode, GraphEdge >::outEdges(), Reversible::postChildren_, BFOptimization::rm(), Reversible::runPostChild(), BFOptimization::sched_, MoveNode::toString(), and Reversible::undo().
Member Data Documentation
guardWrite_
MoveNode& BFRemoveGuardsFromSuccs::guardWrite_ private
Definition at line 53 of file BFRemoveGuardsFromSuccs.hh.
Referenced by operator()().
maxLC_
int BFRemoveGuardsFromSuccs::maxLC_ private
Definition at line 55 of file BFRemoveGuardsFromSuccs.hh.
Referenced by operator()().
oldLC_
int BFRemoveGuardsFromSuccs::oldLC_ private
Definition at line 54 of file BFRemoveGuardsFromSuccs.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFRemoveGuardsFromSuccs.hh
BFRemoveGuardsFromSuccs.cc