OpenASIP: llvm::TCEStubTTIImpl Class Reference
llvm::TCEStubTTIImpl Class Reference
#include <TCEStubTargetTransformInfo.hh>
Public Member Functions
TCEStubTTIImpl (const TCEStubTargetMachine *TM, const Function &F)
unsigned getNumberOfRegisters (bool vector)
unsigned getRegisterBitWidth (bool vector) const
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *=nullptr)
Private Types
typedef BasicTTIImplBase< TCEStubTTIImpl > BaseT
typedef TargetTransformInfo TTI
Private Member Functions
const TCEStubSubTarget * getST () const
const TargetLowering * getTLI () const
Private Attributes
friend BaseT
const TCEStubTargetMachine * TM
const TCEStubSubTarget * ST
const TargetLowering * TLI
Detailed Description
Definition at line 43 of file TCEStubTargetTransformInfo.hh.
Member Typedef Documentation
BaseT
typedef BasicTTIImplBase<TCEStubTTIImpl> llvm::TCEStubTTIImpl::BaseT private
Definition at line 44 of file TCEStubTargetTransformInfo.hh.
TTI
typedef TargetTransformInfo llvm::TCEStubTTIImpl::TTI private
Definition at line 45 of file TCEStubTargetTransformInfo.hh.
Constructor & Destructor Documentation
TCEStubTTIImpl()
llvm::TCEStubTTIImpl::TCEStubTTIImpl (const TCEStubTargetMachine * TM, const Function & F) inline explicit
Definition at line 57 of file TCEStubTargetTransformInfo.hh.
            : BaseT(TM, F.getParent()->getDataLayout()),
              TM(TM), ST(TM->getSubtargetImpl()) {}
Member Function Documentation
getCastInstrCost()
unsigned TCEStubTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * = nullptr)
Definition at line 92 of file TCEStubTargetTransformInfo.cc.
  {
    // TODO: Maybe use ADF/osal information to figure out real cost
    // 1 selected at the moment because LLVM cost model assumed way too high
    // cost for trunc/zext instructions. Too low value here might lead to
    // vectorization of loop that would be better left in scalar form
    return 1;
}
getMaxInterleaveFactor()
unsigned TCEStubTTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 84 of file TCEStubTargetTransformInfo.cc.
{
    // This means maximum loop unroll factor
    // 2 because loopvectorizer requires >1
    // TODO: find some way adjust this.
    return 2;
}
getNumberOfRegisters()
unsigned TCEStubTTIImpl::getNumberOfRegisters (bool vector)
Definition at line 59 of file TCEStubTargetTransformInfo.cc.
{
    // without adf information we have no clue about registers
    if (TM->ttaMach_ == NULL)
        return 0;
    // Widest operand tells directly the widest register
    unsigned widestOperand =
        MachineInfo::findWidestOperand(*(TM->ttaMach_), vector);
    return MachineInfo::numberOfRegisters(*(TM->ttaMach_), widestOperand);
}
References MachineInfo::findWidestOperand(), MachineInfo::numberOfRegisters(), TM, and llvm::TCEBaseTargetMachine::ttaMach_.
getRegisterBitWidth()
unsigned TCEStubTTIImpl::getRegisterBitWidth (bool vector) const
Definition at line 72 of file TCEStubTargetTransformInfo.cc.
{
    // without adf information we have no clue about registers
    if (TM->ttaMach_ == NULL)
        return 0;
    // Widest operand tells directly the widest register
    return MachineInfo::findWidestOperand(*(TM->ttaMach_), vector);
}
References MachineInfo::findWidestOperand(), TM, and llvm::TCEBaseTargetMachine::ttaMach_.
getST()
const TCEStubSubTarget * llvm::TCEStubTTIImpl::getST () const inline private
Definition at line 51 of file TCEStubTargetTransformInfo.hh.
{ return ST; }
References ST.
getTLI()
const TargetLowering * llvm::TCEStubTTIImpl::getTLI () const inline private
Definition at line 52 of file TCEStubTargetTransformInfo.hh.
{
            return ST->getTargetLowering();
        }
References llvm::TCEStubSubTarget::getTargetLowering(), and ST.
Member Data Documentation
BaseT
friend llvm::TCEStubTTIImpl::BaseT private
Definition at line 46 of file TCEStubTargetTransformInfo.hh.
ST
const TCEStubSubTarget* llvm::TCEStubTTIImpl::ST private
Definition at line 49 of file TCEStubTargetTransformInfo.hh.
Referenced by getST(), and getTLI().
TLI
const TargetLowering* llvm::TCEStubTTIImpl::TLI private
Definition at line 50 of file TCEStubTargetTransformInfo.hh.
TM
const TCEStubTargetMachine* llvm::TCEStubTTIImpl::TM private
Definition at line 48 of file TCEStubTargetTransformInfo.hh.
Referenced by getNumberOfRegisters(), and getRegisterBitWidth().
The documentation for this class was generated from the following files:
TCEStubTargetTransformInfo.hh
TCEStubTargetTransformInfo.cc