OpenASIP: BFDropPreShared Class Reference
BFDropPreShared Class Reference
#include <BFDropPreShared.hh>
Public Member Functions
BFDropPreShared (BF2Scheduler &sched, MoveNode &mn)
bool operator() ()
void undoOnlyMe ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & mn_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 41 of file BFDropPreShared.hh.
Constructor & Destructor Documentation
BFDropPreShared()
BFDropPreShared::BFDropPreShared (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 43 of file BFDropPreShared.hh.
                                                       :
        BFOptimization(sched), mn_(mn) {}
Member Function Documentation
operator()()
bool BFDropPreShared::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 47 of file BFDropPreShared.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tDropping pre-shared: " << mn_.toString() << std::endl;
#endif
    MoveNode* trigger = getSisterTrigger(mn_, targetMachine());
    if (trigger == &mn_) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "Cannot pre-share trigger operand, must swap operands"
                  << std::endl;
#endif
        ProgramOperationPtr destPO = mn_.destinationOperationPtr();
        const Operation& op = destPO->operation();
        int operandCount  = op.numberOfInputs();
        bool swapped = false;
        for (int i = 1 ; i <= operandCount && !swapped; i++) {
            int idx = mn_.move().destination().operationIndex();
            MoveNode& mn = destPO->inputNode(i).at(0);
            if (i != idx && op.canSwap(i, idx) &&
                !sched_.isPreLoopSharedOperand(mn)) {
                // TODO: force the indeces here
                BFSwapOperands* bfswo =
                    new BFSwapOperands(sched_, destPO, mn_, mn);
                if (runPreChild(bfswo)) {
                    swapped = true;
                }
            }
        }
        if (!swapped) {
            return false;
        }
    }
    ddg().dropNode(mn_);
    sched_.nodeKilled(mn_);
    return true;
}
References Operation::canSwap(), BFOptimization::ddg(), TTAProgram::Move::destination(), MoveNode::destinationOperationPtr(), BoostGraph< GraphNode, GraphEdge >::dropNode(), BFOptimization::getSisterTrigger(), BF2Scheduler::isPreLoopSharedOperand(), mn_, MoveNode::move(), BF2Scheduler::nodeKilled(), Operation::numberOfInputs(), TTAProgram::Terminal::operationIndex(), Reversible::runPreChild(), BFOptimization::sched_, BFOptimization::targetMachine(), and MoveNode::toString().
undoOnlyMe()
void BFDropPreShared::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 84 of file BFDropPreShared.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\tUndoing dropping of pre-shared: " << mn_.toString()
              << std::endl;
#endif
    ddg().restoreNodeFromParent(mn_);
    sched_.nodeResurrected(mn_);
}
References BFOptimization::ddg(), mn_, BF2Scheduler::nodeResurrected(), BoostGraph< GraphNode, GraphEdge >::restoreNodeFromParent(), BFOptimization::sched_, and MoveNode::toString().
Member Data Documentation
mn_
MoveNode& BFDropPreShared::mn_ private
Definition at line 48 of file BFDropPreShared.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFDropPreShared.hh
BFDropPreShared.cc