OpenASIP: HDBEditorMainFrame Class Reference
HDBEditorMainFrame Class Reference
#include <HDBEditorMainFrame.hh>
Public Member Functions
HDBEditorMainFrame (const wxString &title, const wxPoint &position, const wxSize &size)
virtual ~HDBEditorMainFrame ()
bool setHDB (const std::string &hdbFile)
bool createHDB (const std::string &filePath)
HDB::HDBManager * hdbManager ()
HDBBrowserWindow * browser () const
void update ()
Private Member Functions
void onCommandEvent (wxCommandEvent &event)
void onUpdateUI (wxUpdateUIEvent &event)
Private Attributes
CommandRegistry * commandRegistry_
Command registry.
HDB::CachedHDBManager * hdb_
HDBBrowserWindow * browser_
Detailed Description
Main window of the editor.
Definition at line 50 of file HDBEditorMainFrame.hh.
Constructor & Destructor Documentation
HDBEditorMainFrame()
HDBEditorMainFrame::HDBEditorMainFrame (const wxString & title, const wxPoint & position, const wxSize & size)
The Constructor.
Parameters
title Title of the MainFrame.
position Position of the MainFrame on the screen.
size Size of the MainFrame on the screen.
Definition at line 83 of file HDBEditorMainFrame.cc.
                       :
    wxFrame(NULL, -1, title, position, size),
    hdb_(NULL) {
    commandRegistry_ = new CommandRegistry();
    wxBoxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
    browser_ = new HDBBrowserWindow(this, -1);
    sizer->Add(browser_, 1, wxGROW);
    Fit();
    // Create the default menubar.
    wxMenu* fileMenu = new wxMenu;
    fileMenu->Append(HDBEditorConstants::COMMAND_OPEN_HDB, _T("&Open HDB..."));
    fileMenu->Append(
        HDBEditorConstants::COMMAND_CREATE_HDB, _T("&Create HDB..."));
    fileMenu->AppendSeparator();
    fileMenu->Append(HDBEditorConstants::COMMAND_QUIT, _T("&Quit"));
    wxMenu* editMenu = new wxMenu;
    wxMenu* addSubMenu = new wxMenu;
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_FU_FROM_ADF,
        _T("FU Architecture From ADF..."));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_RF_ARCHITECTURE,
        _T("RF Architecture..."));
    addSubMenu->AppendSeparator();
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_OPERATION_IMPLEMENTATION_RESOURCE,
        _T("Operation Implementation Resource..."));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_OPERATION_IMPLEMENTATION,
        _T("Operation Implementation..."));
    addSubMenu->AppendSeparator();
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION,
        _T("FU Entry Implementation..."));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION,
        _T("RF Entry Implementation..."));
    addSubMenu->AppendSeparator();
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_FU_ENTRY, _T("FU Entry"));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_RF_ENTRY, _T("RF Entry"));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_BUS_ENTRY, _T("Bus Entry"));
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_SOCKET_ENTRY, _T("Socket Entry"));
    addSubMenu->AppendSeparator();
    addSubMenu->Append(
        HDBEditorConstants::COMMAND_ADD_COST_PLUGIN,
        _T("Cost Function Plugin..."));
    editMenu->Append(-1, _T("Add"), addSubMenu);
    editMenu->AppendSeparator();
    editMenu->Append(
        HDBEditorConstants::COMMAND_SET_COST_PLUGIN,
        _T("Set Cost Function Plugin"));
    editMenu->AppendSeparator();
    editMenu->Append(HDBEditorConstants::COMMAND_DELETE, _T("Delete"));
    editMenu->Append(HDBEditorConstants::COMMAND_MODIFY, _T("Modify..."));
    wxMenu* helpMenu = new wxMenu;
    helpMenu->Append(UserManualCmd::COMMAND_ID, _T("User Manual..."));
    helpMenu->Append(HDBEditorConstants::COMMAND_ABOUT, _T("About..."));
    wxMenuBar* menuBar = new wxMenuBar;
    menuBar->Append(fileMenu, _T("&File"));
    menuBar->Append(editMenu, _T("&Edit"));
    menuBar->Append(helpMenu, _T("&Help"));
    SetMenuBar(menuBar);
    CreateStatusBar();
    SetSizer(sizer);
    commandRegistry_->addCommand(new OpenHDBCmd());
    commandRegistry_->addCommand(new CreateHDBCmd());
    commandRegistry_->addCommand(new HDBEditorDeleteCmd());
    commandRegistry_->addCommand(new HDBEditorModifyCmd());
    commandRegistry_->addCommand(new AddFUArchFromADFCmd());
    commandRegistry_->addCommand(new HDBEditorQuitCmd());
    commandRegistry_->addCommand(new AddFUImplementationCmd());
    commandRegistry_->addCommand(new AddRFArchitectureCmd());
    commandRegistry_->addCommand(new AddRFImplementationCmd());
    commandRegistry_->addCommand(new AddFUEntryCmd());
    commandRegistry_->addCommand(new AddRFEntryCmd());
    commandRegistry_->addCommand(new AddBusEntryCmd());
    commandRegistry_->addCommand(new AddSocketEntryCmd());
    commandRegistry_->addCommand(new AddCostFunctionPluginCmd());
    commandRegistry_->addCommand(new SetCostFunctionPluginCmd());
    commandRegistry_->addCommand(new HDBEditorAboutCmd());
    commandRegistry_->addCommand(new UserManualCmd());
    commandRegistry_->addCommand(new AddOperationImplementationCmd());
    commandRegistry_->addCommand(new AddOperationImplementationResourceCmd());
    SetSizeHints(400,300);
    SetSize(600, 400);
}
References HDBEditorConstants::COMMAND_ABOUT, HDBEditorConstants::COMMAND_ADD_BUS_ENTRY, HDBEditorConstants::COMMAND_ADD_COST_PLUGIN, HDBEditorConstants::COMMAND_ADD_FU_ENTRY, HDBEditorConstants::COMMAND_ADD_FU_FROM_ADF, HDBEditorConstants::COMMAND_ADD_FU_IMPLEMENTATION, HDBEditorConstants::COMMAND_ADD_OPERATION_IMPLEMENTATION, HDBEditorConstants::COMMAND_ADD_OPERATION_IMPLEMENTATION_RESOURCE, HDBEditorConstants::COMMAND_ADD_RF_ARCHITECTURE, HDBEditorConstants::COMMAND_ADD_RF_ENTRY, HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION, HDBEditorConstants::COMMAND_ADD_SOCKET_ENTRY, HDBEditorConstants::COMMAND_CREATE_HDB, HDBEditorConstants::COMMAND_DELETE, UserManualCmd::COMMAND_ID, HDBEditorConstants::COMMAND_MODIFY, HDBEditorConstants::COMMAND_OPEN_HDB, HDBEditorConstants::COMMAND_QUIT, and HDBEditorConstants::COMMAND_SET_COST_PLUGIN.
~HDBEditorMainFrame()
HDBEditorMainFrame::~HDBEditorMainFrame () virtual
The Destructor.
Definition at line 199 of file HDBEditorMainFrame.cc.
{
}
Member Function Documentation
browser()
HDBBrowserWindow * HDBEditorMainFrame::browser () const
Returns pointer to the HDB browser window.
Returns
HDB Browser window of the application.
Definition at line 335 of file HDBEditorMainFrame.cc.
{
    return browser_;
}
References browser_.
Referenced by HDBEditor::browser().
createHDB()
bool HDBEditorMainFrame::createHDB (const std::string & filePath)
Creates a new HDB and opens it in the main frame.
Parameters
filePath Full path of the HDB to be created.
Returns
True, if the HDB was succesfully created and opened, false if not.
Definition at line 283 of file HDBEditorMainFrame.cc.
{
    if (hdb_ != NULL) {
        hdb_ = NULL;
    }
    try {
        hdb_ = &HDB::CachedHDBManager::createNew(filePath);
    } catch (Exception& e) {
        wxString message = _T("Error creating HDB ");
        message.Append(WxConversion::toWxString(filePath));
        message.Append(_T(":\n\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return false;
    }
    browser_->setHDBManager(*hdb_);
    std::string title = "HDB Editor - " + FileSystem::fileOfPath(filePath);
    SetTitle(WxConversion::toWxString(title));
    return true;
}
References browser_, HDB::CachedHDBManager::createNew(), Exception::errorMessage(), FileSystem::fileOfPath(), hdb_, HDBBrowserWindow::setHDBManager(), and WxConversion::toWxString().
hdbManager()
HDB::HDBManager * HDBEditorMainFrame::hdbManager ()
Returns pointer to the HDBManager managing the current HDB.
Returns
Pointer to the HDBManager of the main frame.
Definition at line 315 of file HDBEditorMainFrame.cc.
{
    return hdb_;
}
References hdb_.
onCommandEvent()
void HDBEditorMainFrame::onCommandEvent (wxCommandEvent & event) private
Handles menu and toolbar events.
Parameters
event Event to handle.
Definition at line 210 of file HDBEditorMainFrame.cc.
{
    GUICommand* command = commandRegistry_->createCommand(event.GetId());
    if (command == NULL) {
    ErrorDialog dialog(
            this, _T("No handler found for the command event!"));
    dialog.ShowModal();
    return;
    }
    command->setParentWindow(this);
    command->Do();
}
References commandRegistry_, CommandRegistry::createCommand(), GUICommand::Do(), and GUICommand::setParentWindow().
onUpdateUI()
void HDBEditorMainFrame::onUpdateUI (wxUpdateUIEvent & event) private
Updates toolbar and menubar item enabled/disabled states.
Parameters
event Update event for the menu or toolbar item to be updated.
Definition at line 231 of file HDBEditorMainFrame.cc.
{
    GUICommand* command = commandRegistry_->createCommand(event.GetId());
    if (command == NULL || command->isEnabled()) {
    event.Enable(true);
    } else {
    event.Enable(false);
    }
    delete command;
}
References commandRegistry_, CommandRegistry::createCommand(), and GUICommand::isEnabled().
setHDB()
bool HDBEditorMainFrame::setHDB (const std::string & hdbFile)
Sets the HDB to be displayed and modified with the main frame.
Parameters
HDB to be opened in the main frame.
Returns
True, if the HDB was succesfully opened, false if not.
Definition at line 252 of file HDBEditorMainFrame.cc.
{
    if (hdb_ != NULL) {
        hdb_ = NULL;
    }
    try {
        hdb_ = &HDB::HDBRegistry::instance().hdb(hdbFile);
    } catch (Exception& e) {
        wxString message = _T("Error opening HDB ");
        message.Append(WxConversion::toWxString(hdbFile));
        message.Append(_T(":\n\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return false;
    }
    browser_->setHDBManager(*hdb_);
    std::string title = "HDB Editor - " + FileSystem::fileOfPath(hdbFile);
    SetTitle(WxConversion::toWxString(title));
    return true;
}
References browser_, Exception::errorMessage(), FileSystem::fileOfPath(), HDB::HDBRegistry::hdb(), hdb_, HDB::HDBRegistry::instance(), HDBBrowserWindow::setHDBManager(), and WxConversion::toWxString().
Referenced by HDBEditor::OnInit().
update()
void HDBEditorMainFrame::update ()
Updates the HDB window.
Definition at line 324 of file HDBEditorMainFrame.cc.
{
    browser_->update();
}
References browser_, and HDBBrowserWindow::update().
Member Data Documentation
browser_
HDBBrowserWindow* HDBEditorMainFrame::browser_ private
Definition at line 72 of file HDBEditorMainFrame.hh.
Referenced by browser(), createHDB(), setHDB(), and update().
commandRegistry_
CommandRegistry* HDBEditorMainFrame::commandRegistry_ private
Command registry.
Definition at line 69 of file HDBEditorMainFrame.hh.
Referenced by onCommandEvent(), and onUpdateUI().
hdb_
HDB::CachedHDBManager* HDBEditorMainFrame::hdb_ private
Definition at line 71 of file HDBEditorMainFrame.hh.
Referenced by createHDB(), hdbManager(), and setHDB().
The documentation for this class was generated from the following files:
HDBEditorMainFrame.hh
HDBEditorMainFrame.cc