OpenASIP: NullLongImmediateUnitState Class Reference
NullLongImmediateUnitState Class Reference
#include <LongImmediateUnitState.hh>
Public Member Functions
virtual ~NullLongImmediateUnitState ()
virtual SimValue & registerValue (int index)
virtual void setRegisterValue (int index, const SimValue &value)
virtual LongImmediateRegisterState & immediateRegister (int i)
virtual int immediateRegisterCount () const
virtual void endClock ()
virtual void advanceClock ()
Public Member Functions inherited from LongImmediateUnitState
LongImmediateUnitState (int size, int latency, const std::string &name, int width, bool signExtend)
virtual ~LongImmediateUnitState ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
virtual void reset ()
this is called at (re)initialization of the simulation
Static Public Member Functions
static NullLongImmediateUnitState & instance ()
Private Member Functions
NullLongImmediateUnitState ()
NullLongImmediateUnitState (const NullLongImmediateUnitState &)
Copying not allowed.
NullLongImmediateUnitState & operator= (const NullLongImmediateUnitState &)
Assignment not allowed.
Static Private Attributes
static NullLongImmediateUnitState * instance_ = NULL
Unique instance of NullLongImmediateUnitState.
Detailed Description
Models non-existing LongImmediateUnitState.
Definition at line 128 of file LongImmediateUnitState.hh.
Constructor & Destructor Documentation
~NullLongImmediateUnitState()
NullLongImmediateUnitState::~NullLongImmediateUnitState () virtual
Destructor.
Definition at line 208 of file LongImmediateUnitState.cc.
{
}
NullLongImmediateUnitState() [1/2]
NullLongImmediateUnitState::NullLongImmediateUnitState () private
Constructor.
Definition at line 201 of file LongImmediateUnitState.cc.
                                                       :
    LongImmediateUnitState(0, 0, "<NULL>", 0, false) {
}
Referenced by instance().
NullLongImmediateUnitState() [2/2]
NullLongImmediateUnitState::NullLongImmediateUnitState (const NullLongImmediateUnitState &) private
Copying not allowed.
Member Function Documentation
advanceClock()
void NullLongImmediateUnitState::advanceClock () virtual
Aborts the program with error message.
Reimplemented from LongImmediateUnitState.
Definition at line 245 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("advanceClock()");
}
endClock()
void NullLongImmediateUnitState::endClock () virtual
Aborts the program with error message.
Reimplemented from LongImmediateUnitState.
Definition at line 237 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("endClock()");
}
immediateRegister()
LongImmediateRegisterState & NullLongImmediateUnitState::immediateRegister (int i) virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from LongImmediateUnitState.
Definition at line 255 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("immediateRegister()");
    return *(new LongImmediateRegisterState(NULL, 0, 0, false));
}
immediateRegisterCount()
int NullLongImmediateUnitState::immediateRegisterCount () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from LongImmediateUnitState.
Definition at line 266 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("immediateRegisterCount()");
    return 0;
}
instance()
NullLongImmediateUnitState & NullLongImmediateUnitState::instance () static
Returns NullLongImmediateUnitState instance.
Returns
NullLongImmediateUnitState instance.
Definition at line 191 of file LongImmediateUnitState.cc.
{
    if (instance_ == NULL) {
        instance_ = new NullLongImmediateUnitState();
    }
    return *instance_;
}
References instance_, and NullLongImmediateUnitState().
Referenced by MachineState::longImmediateUnitState(), SimProgramBuilder::processInstruction(), and SimProgramBuilder::processSourceTerminal().
operator=()
NullLongImmediateUnitState & NullLongImmediateUnitState::operator= (const NullLongImmediateUnitState &) private
Assignment not allowed.
registerValue()
SimValue & NullLongImmediateUnitState::registerValue (int index) virtual
Aborts the program with error message.
Returns
Never returns.
Exceptions
OutOfRange Never throws.
Reimplemented from LongImmediateUnitState.
Definition at line 218 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("registerValue()");
    return NullSimValue::instance();
}
References NullSimValue::instance().
setRegisterValue()
void NullLongImmediateUnitState::setRegisterValue (int index, const SimValue & value) virtual
Aborts the program with error message.
Exceptions
OutOfRange Never throws.
Reimplemented from LongImmediateUnitState.
Definition at line 229 of file LongImmediateUnitState.cc.
{
    Application::abortWithError("setRegisterValue()");
}
Member Data Documentation
instance_
NullLongImmediateUnitState * NullLongImmediateUnitState::instance_ = NULL static private
Unique instance of NullLongImmediateUnitState.
Definition at line 151 of file LongImmediateUnitState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
LongImmediateUnitState.hh
LongImmediateUnitState.cc