OpenASIP: DisableBPCommand Class Reference
DisableBPCommand Class Reference
#include <DisableBPCommand.hh>
Public Member Functions
DisableBPCommand ()
virtual ~DisableBPCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "disablebp" command of the Simulator Control Language.
Definition at line 47 of file DisableBPCommand.hh.
Constructor & Destructor Documentation
DisableBPCommand()
DisableBPCommand::DisableBPCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 52 of file DisableBPCommand.cc.
                                   :
    SimControlLanguageCommand("disablebp") {
}
~DisableBPCommand()
DisableBPCommand::~DisableBPCommand () virtual
Destructor.
Does nothing.
Definition at line 61 of file DisableBPCommand.cc.
{
}
Member Function Documentation
execute()
bool DisableBPCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "disablebp" command.
Disables the given breakpoints.
Parameters
arguments The handle(s) of the breakpoint(s) to enable.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 75 of file DisableBPCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 1, INT_MAX)) {
        return false;
    }
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    StopPointManager& breakpointManager =
        simulatorFrontend().stopPointManager();
    if (!verifyBreakpointHandles(arguments)) {
        return false;
    }
    // disable the given breakpoints
    for (size_t i = 1; i < arguments.size(); ++i) {
        const unsigned int breakpointHandle = arguments[i].integerValue();
        breakpointManager.disable(breakpointHandle);
        printBreakpointInfo(breakpointHandle);
    }
    return true;
}
References CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), StopPointManager::disable(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::stopPointManager(), and SimControlLanguageCommand::verifyBreakpointHandles().
helpText()
std::string DisableBPCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 111 of file DisableBPCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_DISABLEBP).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_DISABLEBP.
The documentation for this class was generated from the following files:
DisableBPCommand.hh
DisableBPCommand.cc