OpenASIP: ImmediateGenerator Class Reference
ImmediateGenerator Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Creates immediates for configuration.")
ImmediateGenerator ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual bool requiresApplication () const
virtual std::vector< RowID > explore (const RowID &startPointConfigurationID, const unsigned int &)
void readParameters ()
void printImmediateTemplates (TTAMachine::Machine &mach)
void removeInsTemplate (TTAMachine::Machine &mach, std::string name)
void addInsTemplate (TTAMachine::Machine &mach, std::string name)
void addSplitInsTemplate (TTAMachine::Machine &mach, std::string name)
Private Attributes
bool createNewConfig_
Boolean value used to decide if new config is created.
bool print_
print values
std::string removeInsTemplateName_
instruction template name to be removed.
std::string addInsTemplateName_
instruction template name to be added.
std::string modInsTemplateName_
instruction template name to be modified.
unsigned int width_
width of the target template
unsigned int widthPart_
minimum width on long instruction slot when splitting the template.
bool split_
make evenly bus/slot wise splitted template.
std::string dstImmUnitName_
destination immediate unit name
Static Private Attributes
static const std::string printPN_
static const std::string removeInsTemplateNamePN_
static const std::string addInsTemplateNamePN_
static const std::string modInsTemplateNamePN_
static const std::string widthPN_
static const std::string widthPartPN_
static const std::string splitPN_
static const std::string dstImmUnitNamePN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that creates or modifies machine instruction template by adding/removing immediates.
Definition at line 69 of file ImmediateGenerator.cc.
Constructor & Destructor Documentation
ImmediateGenerator()
ImmediateGenerator::ImmediateGenerator () inline private
Definition at line 72 of file ImmediateGenerator.cc.
                        : DesignSpaceExplorerPlugin(),
        createNewConfig_(false),
        print_(false),
        removeInsTemplateName_(""),
        addInsTemplateName_(""),
        modInsTemplateName_(""),
        width_(32),
        widthPart_(8),
        split_(false),
        dstImmUnitName_("") {
        // compulsory parameters
        // no compulsory parameters
        // parameters that have a default value
        addParameter(printPN_, BOOL, false, Conversion::toString(print_));
        addParameter(removeInsTemplateNamePN_, STRING, false, removeInsTemplateName_);
        addParameter(addInsTemplateNamePN_, STRING, false, addInsTemplateName_);
        addParameter(modInsTemplateNamePN_, STRING, false, modInsTemplateName_);
        addParameter(widthPN_, UINT, false, Conversion::toString(width_));
        addParameter(widthPartPN_, UINT, false, Conversion::toString(widthPart_));
        addParameter(splitPN_, BOOL, false, Conversion::toString(split_));
        addParameter(dstImmUnitNamePN_, STRING, false, dstImmUnitName_);
    }
References addInsTemplateName_, addInsTemplateNamePN_, DesignSpaceExplorerPlugin::addParameter(), BOOL, dstImmUnitName_, dstImmUnitNamePN_, modInsTemplateName_, modInsTemplateNamePN_, print_, printPN_, removeInsTemplateName_, removeInsTemplateNamePN_, split_, splitPN_, STRING, Conversion::toString(), UINT, width_, widthPart_, widthPartPN_, and widthPN_.
Member Function Documentation
addInsTemplate()
void ImmediateGenerator::addInsTemplate (TTAMachine::Machine & mach, std::string name) inline private
Adds instruction template with a name given as parameter.
Parameters
mach Target machine.
name Instruction template name to be added.
Definition at line 320 of file ImmediateGenerator.cc.
{
        TTAMachine::InstructionTemplate* insTemplate = NULL;
        try {
            insTemplate = new InstructionTemplate(name, mach);
        } catch (ComponentAlreadyExists& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            delete insTemplate;
            return;
        } catch (InvalidName& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            delete insTemplate;
            return;
        }
        createNewConfig_ = true;
    }
References createNewConfig_, Exception::errorMessage(), DesignSpaceExplorerPlugin::name(), and verboseLog.
Referenced by explore().
addSplitInsTemplate()
void ImmediateGenerator::addSplitInsTemplate (TTAMachine::Machine & mach, std::string name) inline private
Adds instruction template with a name given as parameter and add bus wise splitted slots to the template.
Parameters
mach Target machine.
name Instruction template name to be added.
Definition at line 350 of file ImmediateGenerator.cc.
{
        TTAMachine::InstructionTemplate* insTemplate = NULL;
        // find target immediate unit for the instruction template slots
        Machine::ImmediateUnitNavigator IUNav =
            mach.immediateUnitNavigator();
        TTAMachine::ImmediateUnit* immUnit = NULL;
        TTAMachine::ImmediateUnit* dstImmUnit = NULL;
        if (dstImmUnitName_.empty()) {
            // if no destination immediate unit specified take one if exists
            if (IUNav.count() > 0) {
                dstImmUnit = IUNav.item(0);
            } else {
                std::ostringstream msg(std::ostringstream::out);
                msg << "Error while using ImmediateGenerator:" << endl
                    << "No immediate units." << endl;
                verboseLog(msg.str());
                return;
            }
        } else {
            for (int iu = 0; iu < IUNav.count(); iu++) {
                immUnit = IUNav.item(iu);
                if (immUnit->name() == dstImmUnitName_) {
                    dstImmUnit = immUnit;
                }
            }
            if (dstImmUnit == NULL) {
                std::ostringstream msg(std::ostringstream::out);
                msg << "Error while using ImmediateGenerator:" << endl
                    << "Given destination immediate unit \""
                    << dstImmUnitName_ << "\" was not found." << endl;
                verboseLog(msg.str());
                return;
            }
        }
        // add instruction template
        try {
            insTemplate = new InstructionTemplate(name, mach);
        } catch (ComponentAlreadyExists& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            delete insTemplate;
            insTemplate = NULL;
            return;
        } catch (InvalidName& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            delete insTemplate;
            insTemplate = NULL;
            return;
        }
        // TODO: split among immediate slots also?
        Machine::BusNavigator busNav = mach.busNavigator();
        int slotCount = (width_/widthPart_);
        // if too few busses to make even one widthPart_ length template slot
        if (busNav.count() < slotCount) {
            slotCount = busNav.count();
        }
        int overSpill = width_ - (slotCount * widthPart_);
        int widthAdd = 0;
        TTAMachine::Bus* busP = NULL;
        for (int bus = 0; bus < slotCount; bus++) {
            busP = busNav.item(bus);
            if (overSpill > 0) {
                if (overSpill < static_cast<int>(
                            busP->width() - widthPart_)) {
                    widthAdd = overSpill;
                    overSpill = -1; // all spilled
                } else {
                    widthAdd = busP->width() - widthPart_;
                    overSpill = overSpill - widthAdd;
                }
            } else {
                widthAdd = 0;
            }
            try {
                insTemplate->addSlot(busP->name(), widthPart_ + widthAdd,
                        *dstImmUnit);
            } catch (const Exception& e) {
                std::ostringstream msg(std::ostringstream::out);
                msg << "Error while using ImmediateGenerator:" << endl
                    << e.errorMessage() << endl;
                verboseLog(msg.str());
                delete insTemplate;
                insTemplate = NULL;
                return;
            }
        }
        // check if all spilled
        if (overSpill > 0) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << "Immediate template generation failed, width=\"" << width_
                << "\" too great by: \"" << overSpill << "\"" << endl;
            verboseLog(msg.str());
            delete insTemplate;
            insTemplate = NULL;
            return;
        }
        createNewConfig_ = true;
    }
References TTAMachine::InstructionTemplate::addSlot(), TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), createNewConfig_, dstImmUnitName_, Exception::errorMessage(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), DesignSpaceExplorerPlugin::name(), TTAMachine::Component::name(), verboseLog, TTAMachine::Bus::width(), width_, and widthPart_.
Referenced by explore().
explore()
virtual std::vector< RowID > ImmediateGenerator::explore (const RowID & startPointConfigurationID, const unsigned int &) inline private virtual
Explorer plugin that creates or modifies machine instruction templates. TODO: add some modifying functionality.
Supported parameters:
print, boolean, print information about machines instruction templates.
remove_it_name, string, remove instruction template with a given name.
add_it_name, string, add empty instruction template with a given name.
modify_it_name, string, modify instruction template with a given name.
width, int, instruction template supported width.
width_part, int, minimum size of width per slot. Default 8.
split, boolean, split immediate among slots.
dst_imm_unit, string, destination immediate unit.
Parameters
startPointConfigurationID Configuration to optimize.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 120 of file ImmediateGenerator.cc.
{
        // XXX: does this plugin have to touch short immediates.
        std::vector<RowID> result;
        readParameters();
        try {
            DSDBManager& dsdb = db();
            // loads starting configuration
            DSDBManager::MachineConfiguration conf =
                dsdb.configuration(startPointConfigurationID);
            // load machine from configuration
            //Machine* origMach = NULL;
            Machine* mach = NULL;
            try {
                //origMach = dsdb.architecture(conf.architectureID);
                mach = dsdb.architecture(conf.architectureID);
            } catch (const Exception& e) {
                std::ostringstream msg(std::ostringstream::out);
                msg << e.errorMessage() << endl;
                verboseLog(msg.str());
                return result;
            }
            if (!removeInsTemplateName_.empty()) {
                removeInsTemplate(*mach, removeInsTemplateName_);
            }
            if (!addInsTemplateName_.empty()) {
                if (split_) {
                    addSplitInsTemplate(*mach, addInsTemplateName_);
                } else {
                    addInsTemplate(*mach, addInsTemplateName_);
                }
            }
            // print immediate info if print parameter given
            if (print_) {
                printImmediateTemplates(*mach);
            }
            if (createNewConfig_) {
                // create the new configuration to be saved to dsdb
                // do long immediates affect these
                DSDBManager::MachineConfiguration newConf;
                if (conf.hasImplementation) {
                    newConf.hasImplementation = true;
                    IDF::MachineImplementation* idf =
                        dsdb.implementation(conf.implementationID);
                    CostEstimator::Estimator estimator;
                    CostEstimator::AreaInGates area =
                        estimator.totalArea(*mach, *idf);
                    CostEstimator::DelayInNanoSeconds longestPathDelay =
                        estimator.longestPath(*mach, *idf);
                    newConf.implementationID =
                        dsdb.addImplementation(*idf, longestPathDelay, area);
                } else {
                    newConf.hasImplementation = false;
                }
                newConf.architectureID = dsdb.addArchitecture(*mach);
                CostEstimates estimates;
                RowID confID = dsdb.addConfiguration(newConf);
                result.push_back(confID);
            }
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            return result;
        }
        return result;
    }
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::addImplementation(), addInsTemplate(), addInsTemplateName_, addSplitInsTemplate(), DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, DSDBManager::configuration(), createNewConfig_, DesignSpaceExplorer::db(), Exception::errorMessage(), DSDBManager::MachineConfiguration::hasImplementation, DSDBManager::implementation(), DSDBManager::MachineConfiguration::implementationID, CostEstimator::Estimator::longestPath(), print_, printImmediateTemplates(), readParameters(), removeInsTemplate(), removeInsTemplateName_, split_, CostEstimator::Estimator::totalArea(), and verboseLog.
PLUGIN_DESCRIPTION()
ImmediateGenerator::PLUGIN_DESCRIPTION ("Creates immediates for configuration.") private
printImmediateTemplates()
void ImmediateGenerator::printImmediateTemplates (TTAMachine::Machine & mach) inline private
Print info about instruction templates of a given machine.
Parameters
mach Machine which instruction templates are to be printed.
Definition at line 252 of file ImmediateGenerator.cc.
{
        Machine::InstructionTemplateNavigator ITNav =
            mach.instructionTemplateNavigator();
        std::ostringstream msg(std::ostringstream::out);
        msg << "====== Instruction templates: =======" << endl;
        TTAMachine::InstructionTemplate* insTemplate = NULL;
        TTAMachine::TemplateSlot* tempSlot = NULL;
        for (int it = 0; it < ITNav.count(); it++) {
            insTemplate = ITNav.item(it);
            msg << "Instruction template: " << insTemplate->name() << endl;
            if (insTemplate->isEmpty()) {
                msg << "\tEmpty instruction template." << endl;
                continue;
            }
            msg << "\tSlot count: " << insTemplate->slotCount() << endl;
            for (int sc = 0; sc < insTemplate->slotCount(); sc++) {
                tempSlot = insTemplate->slot(sc);
                msg << "\t\tSlot name: " << tempSlot->slot() << endl;
                msg << "\t\tSlot width: " << tempSlot->width() << endl;
                msg << "\t\tSlot destination: "
                    << tempSlot->destination()->name() << endl;
            }
            msg << "\tSupported Width: " << insTemplate->supportedWidth() << endl;
            msg << "\tNumber of Destinations: "
                << insTemplate->numberOfDestinations() << endl;
        }
        verboseLog(msg.str());
    }
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::TemplateSlot::destination(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::InstructionTemplate::isEmpty(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::InstructionTemplate::numberOfDestinations(), TTAMachine::TemplateSlot::slot(), TTAMachine::InstructionTemplate::slot(), TTAMachine::InstructionTemplate::slotCount(), TTAMachine::InstructionTemplate::supportedWidth(), verboseLog, and TTAMachine::TemplateSlot::width().
Referenced by explore().
producesArchitecture()
virtual bool ImmediateGenerator::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 98 of file ImmediateGenerator.cc.
{ return true; }
readParameters()
void ImmediateGenerator::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 235 of file ImmediateGenerator.cc.
{
        readCompulsoryParameter(printPN_, print_);
        readCompulsoryParameter(removeInsTemplateNamePN_, removeInsTemplateName_);
        readCompulsoryParameter(addInsTemplateNamePN_, addInsTemplateName_);
        readCompulsoryParameter(modInsTemplateNamePN_, modInsTemplateName_);
        readCompulsoryParameter(widthPN_, width_);
        readCompulsoryParameter(widthPartPN_, widthPart_);
        readCompulsoryParameter(splitPN_, split_);
        readCompulsoryParameter(dstImmUnitNamePN_, dstImmUnitName_);
    }
References addInsTemplateName_, addInsTemplateNamePN_, dstImmUnitName_, dstImmUnitNamePN_, modInsTemplateName_, modInsTemplateNamePN_, print_, printPN_, DesignSpaceExplorerPlugin::readCompulsoryParameter(), removeInsTemplateName_, removeInsTemplateNamePN_, split_, splitPN_, width_, widthPart_, widthPartPN_, and widthPN_.
Referenced by explore().
removeInsTemplate()
void ImmediateGenerator::removeInsTemplate (TTAMachine::Machine & mach, std::string name) inline private
Removes instruction template with a name given as parameter.
Parameters
mach Target machine.
name Instruction template name to be removed.
Definition at line 292 of file ImmediateGenerator.cc.
{
        Machine::InstructionTemplateNavigator ITNav =
            mach.instructionTemplateNavigator();
        TTAMachine::InstructionTemplate* insTemplate = NULL;
        for (int it = 0; it < ITNav.count(); it++) {
            insTemplate = ITNav.item(it);
            if (insTemplate->name() == name) {
                mach.deleteInstructionTemplate(*insTemplate);
                createNewConfig_ = true;
            }
        }
        if (!createNewConfig_) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using ImmediateGenerator:" << endl
                << "Instruction template with name \"" << name
                << "\" was not found."  << endl;
            verboseLog(msg.str());
        }
    }
References TTAMachine::Machine::Navigator< ComponentType >::count(), createNewConfig_, TTAMachine::Machine::deleteInstructionTemplate(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), DesignSpaceExplorerPlugin::name(), TTAMachine::Component::name(), and verboseLog.
Referenced by explore().
requiresApplication()
virtual bool ImmediateGenerator::requiresApplication () const inline private virtual
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 101 of file ImmediateGenerator.cc.
{ return false; }
requiresHDB()
virtual bool ImmediateGenerator::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 99 of file ImmediateGenerator.cc.
{ return false; }
requiresSimulationData()
virtual bool ImmediateGenerator::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 100 of file ImmediateGenerator.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool ImmediateGenerator::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 97 of file ImmediateGenerator.cc.
{ return true; }
Member Data Documentation
addInsTemplateName_
std::string ImmediateGenerator::addInsTemplateName_ private
instruction template name to be added.
Definition at line 219 of file ImmediateGenerator.cc.
Referenced by explore(), ImmediateGenerator(), and readParameters().
addInsTemplateNamePN_
const std::string ImmediateGenerator::addInsTemplateNamePN_ static private
Definition at line 206 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
createNewConfig_
bool ImmediateGenerator::createNewConfig_ private
Boolean value used to decide if new config is created.
Definition at line 201 of file ImmediateGenerator.cc.
Referenced by addInsTemplate(), addSplitInsTemplate(), explore(), and removeInsTemplate().
dstImmUnitName_
std::string ImmediateGenerator::dstImmUnitName_ private
destination immediate unit name
Definition at line 229 of file ImmediateGenerator.cc.
Referenced by addSplitInsTemplate(), ImmediateGenerator(), and readParameters().
dstImmUnitNamePN_
const std::string ImmediateGenerator::dstImmUnitNamePN_ static private
Definition at line 211 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
modInsTemplateName_
std::string ImmediateGenerator::modInsTemplateName_ private
instruction template name to be modified.
Definition at line 221 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
modInsTemplateNamePN_
const std::string ImmediateGenerator::modInsTemplateNamePN_ static private
Definition at line 207 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
print_
bool ImmediateGenerator::print_ private
print values
Definition at line 215 of file ImmediateGenerator.cc.
Referenced by explore(), ImmediateGenerator(), and readParameters().
printPN_
const std::string ImmediateGenerator::printPN_ static private
Definition at line 204 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
removeInsTemplateName_
std::string ImmediateGenerator::removeInsTemplateName_ private
instruction template name to be removed.
Definition at line 217 of file ImmediateGenerator.cc.
Referenced by explore(), ImmediateGenerator(), and readParameters().
removeInsTemplateNamePN_
const std::string ImmediateGenerator::removeInsTemplateNamePN_ static private
Definition at line 205 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
split_
bool ImmediateGenerator::split_ private
make evenly bus/slot wise splitted template.
Definition at line 227 of file ImmediateGenerator.cc.
Referenced by explore(), ImmediateGenerator(), and readParameters().
splitPN_
const std::string ImmediateGenerator::splitPN_ static private
Definition at line 210 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
width_
unsigned int ImmediateGenerator::width_ private
width of the target template
Definition at line 223 of file ImmediateGenerator.cc.
Referenced by addSplitInsTemplate(), ImmediateGenerator(), and readParameters().
widthPart_
unsigned int ImmediateGenerator::widthPart_ private
minimum width on long instruction slot when splitting the template.
Definition at line 225 of file ImmediateGenerator.cc.
Referenced by addSplitInsTemplate(), ImmediateGenerator(), and readParameters().
widthPartPN_
const std::string ImmediateGenerator::widthPartPN_ static private
Definition at line 209 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
widthPN_
const std::string ImmediateGenerator::widthPN_ static private
Definition at line 208 of file ImmediateGenerator.cc.
Referenced by ImmediateGenerator(), and readParameters().
The documentation for this class was generated from the following file:
ImmediateGenerator.cc