OpenASIP: TTAMachine::NullMachine Class Reference
TTAMachine::NullMachine Class Reference
#include <NullMachine.hh>
Public Member Functions
virtual void addBus (Bus &bus)
virtual void addSocket (Socket &socket)
void addUnit (Unit &unit)
virtual void addFunctionUnit (FunctionUnit &unit)
virtual void addImmediateUnit (ImmediateUnit &unit)
virtual void addRegisterFile (RegisterFile &unit)
virtual void addAddressSpace (AddressSpace &as)
virtual void addBridge (Bridge &bridge)
virtual void addInstructionTemplate (InstructionTemplate &instrTempl)
virtual void setGlobalControl (ControlUnit &unit)
virtual void unsetGlobalControl ()
virtual ControlUnit * controlUnit () const
virtual void removeBus (Bus &bus)
virtual void removeSocket (Socket &socket)
virtual void removeUnit (Unit &unit)
virtual void removeFunctionUnit (FunctionUnit &unit)
virtual void removeImmediateUnit (ImmediateUnit &unit)
virtual void removeRegisterFile (RegisterFile &unit)
virtual void deleteBridge (Bridge &bridge)
virtual void deleteInstructionTemplate (InstructionTemplate &instrTempl)
virtual void deleteAddressSpace (AddressSpace &as)
virtual BusNavigator busNavigator () const
virtual SocketNavigator socketNavigator () const
virtual FunctionUnitNavigator functionUnitNavigator () const
virtual AddressSpaceNavigator addressSpaceNavigator () const
virtual BridgeNavigator bridgeNavigator () const
virtual ImmediateUnitNavigator immediateUnitNavigator () const
virtual InstructionTemplateNavigator instructionTemplateNavigator () const
virtual RegisterFileNavigator registerFileNavigator () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from TTAMachine::Machine
Machine ()
Machine (const Machine &old)
virtual ~Machine ()
virtual bool isUniversalMachine () const
void addUnit (Unit &unit)
virtual void addOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void addImmediateSlot (ImmediateSlot &slot)
virtual void deleteOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void deleteImmediateSlot (ImmediateSlot &slot)
void setBusPosition (const Bus &bus, int newPosition)
MachineTester & machineTester () const
bool alwaysWriteResults () const
bool triggerInvalidatesResults () const
bool isFUOrdered () const
void setAlwaysWriteResults (bool)
void setTriggerInvalidatesResults (bool)
void setFUOrdered (bool)
int maximumLatency () const
virtual void copyFromMachine (Machine &machine)
void writeToADF (const std::string &adfFileName) const
TCEString hash () const
bool hasOperation (const TCEString &opName) const
bool isRISCVMachine () const
virtual ImmediateSlotNavigator immediateSlotNavigator () const
virtual OperationTriggeredFormatNavigator operationTriggeredFormatNavigator () const
bool isLittleEndian () const
void setLittleEndian (bool flag)
bool is64bit () const
void set64bits (bool flag)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static NullMachine & instance ()
Static Public Member Functions inherited from TTAMachine::Machine
static Machine * loadFromADF (const std::string &adfFileName)
Private Member Functions
NullMachine ()
virtual ~NullMachine ()
Static Private Attributes
static NullMachine machine_
The only instance of NullMachine.
Additional Inherited Members
Public Types inherited from TTAMachine::Machine
enum Extension { ZERO , SIGN }
typedef Navigator< Bus > BusNavigator
Navigator type for BusNavigator.
typedef Navigator< Socket > SocketNavigator
Navigator type for SocketNavigator.
typedef Navigator< FunctionUnit > FunctionUnitNavigator
Navigator type for FunctionUnitNavigator.
typedef Navigator< AddressSpace > AddressSpaceNavigator
Navigator type for AddressSpaceNavigator.
typedef Navigator< Bridge > BridgeNavigator
Navigator type for BridgeNavigator.
typedef Navigator< ImmediateUnit > ImmediateUnitNavigator
Navigator type for ImmediateUnitNavigator.
typedef Navigator< InstructionTemplate > InstructionTemplateNavigator
Navigator type for InstructionTemplateNavigator.
typedef Navigator< RegisterFile > RegisterFileNavigator
Navigator type for RegisterFileNavigator.
typedef Navigator< ImmediateSlot > ImmediateSlotNavigator
Navigator type for ImmediateSlotNavigator.
typedef Navigator< OperationTriggeredFormat > OperationTriggeredFormatNavigator
Navigator type for OperationTriggeredFormatNavigator.
Static Public Attributes inherited from TTAMachine::Machine
static const std::string OSNAME_MACHINE = "machine"
ObjectState name for Machine.
static const std::string OSKEY_ALWAYS_WRITE_BACK_RESULTS = "always-write-back"
ObjectState attribute key for always-write-back-results.
static const std::string OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS = "trigger-invalidates"
ObjectState attribute key for trigger-invalidates-old-results.
static const std::string OSKEY_FUNCTION_UNITS_ORDERED = "fu-ordered"
ObjectState attribute key for function units ordered in order of their sequential presence in ADF.
Detailed Description
A singleton class which represents a null machine.
Definition at line 43 of file NullMachine.hh.
Constructor & Destructor Documentation
NullMachine()
TTAMachine::NullMachine::NullMachine () private
The constructor.
Definition at line 43 of file NullMachine.cc.
                         : Machine() {
}
~NullMachine()
TTAMachine::NullMachine::~NullMachine () private virtual
The destructor.
Definition at line 50 of file NullMachine.cc.
{
}
Member Function Documentation
addAddressSpace()
void TTAMachine::NullMachine::addAddressSpace (AddressSpace & as) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 133 of file NullMachine.cc.
{
    abortWithError("NullMachine::addAddressSpace");
}
References abortWithError.
addBridge()
void TTAMachine::NullMachine::addBridge (Bridge & bridge) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 143 of file NullMachine.cc.
{
    abortWithError("NullMachine::addBridge");
}
References abortWithError.
addBus()
void TTAMachine::NullMachine::addBus (Bus & bus) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 71 of file NullMachine.cc.
{
    abortWithError("NullMachine::addBus");
}
References abortWithError.
addFunctionUnit()
void TTAMachine::NullMachine::addFunctionUnit (FunctionUnit & unit) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
IllegalParameters Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 103 of file NullMachine.cc.
{
    abortWithError("NullMachine::addFunctionUnit");
}
References abortWithError.
addImmediateUnit()
void TTAMachine::NullMachine::addImmediateUnit (ImmediateUnit & unit) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 113 of file NullMachine.cc.
{
    abortWithError("NullMachine::addImmediateUnit");
}
References abortWithError.
addInstructionTemplate()
void TTAMachine::NullMachine::addInstructionTemplate (InstructionTemplate & instrTempl) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 153 of file NullMachine.cc.
{
    abortWithError("NullMachine::addInstructionTemplate");
}
References abortWithError.
addRegisterFile()
void TTAMachine::NullMachine::addRegisterFile (RegisterFile & unit) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 123 of file NullMachine.cc.
{
    abortWithError("NullMachine::addRegisterFile");
}
References abortWithError.
addressSpaceNavigator()
Machine::AddressSpaceNavigator TTAMachine::NullMachine::addressSpaceNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 321 of file NullMachine.cc.
{
    abortWithError("NullMachine::addressSpaceNavigator");
    return Machine::addressSpaceNavigator();
}
References abortWithError, and TTAMachine::Machine::addressSpaceNavigator().
addSocket()
void TTAMachine::NullMachine::addSocket (Socket & socket) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 81 of file NullMachine.cc.
{
    abortWithError("NullMachine::addSocket");
}
References abortWithError.
addUnit()
void TTAMachine::NullMachine::addUnit (Unit & unit)
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
IllegalParameters Never thrown.
Definition at line 92 of file NullMachine.cc.
{
    abortWithError("NullMachine::addUnit");
}
References abortWithError.
bridgeNavigator()
Machine::BridgeNavigator TTAMachine::NullMachine::bridgeNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 333 of file NullMachine.cc.
{
    abortWithError("NullMachine::bridgeNavigator");
    return Machine::bridgeNavigator();
}
References abortWithError, and TTAMachine::Machine::bridgeNavigator().
busNavigator()
Machine::BusNavigator TTAMachine::NullMachine::busNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 285 of file NullMachine.cc.
{
    abortWithError("NullMachine::busNavigator");
    return Machine::busNavigator();
}
References abortWithError, and TTAMachine::Machine::busNavigator().
controlUnit()
ControlUnit * TTAMachine::NullMachine::controlUnit () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 182 of file NullMachine.cc.
{
    abortWithError("NullMachine::controlUnit");
    return NULL;
}
References abortWithError.
deleteAddressSpace()
void TTAMachine::NullMachine::deleteAddressSpace (AddressSpace & as) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 275 of file NullMachine.cc.
{
    abortWithError("NullMachine::deleteAddressSpace");
}
References abortWithError.
deleteBridge()
void TTAMachine::NullMachine::deleteBridge (Bridge & bridge) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 255 of file NullMachine.cc.
{
    abortWithError("NullMachine::deleteBridge");
}
References abortWithError.
deleteInstructionTemplate()
void TTAMachine::NullMachine::deleteInstructionTemplate (InstructionTemplate & instrTempl) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 265 of file NullMachine.cc.
{
    abortWithError("NullMachine::deleteInstructionTemplate");
}
References abortWithError.
functionUnitNavigator()
Machine::FunctionUnitNavigator TTAMachine::NullMachine::functionUnitNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 309 of file NullMachine.cc.
{
    abortWithError("NullMachine::functionUnitNavigator");
    return Machine::functionUnitNavigator();
}
References abortWithError, and TTAMachine::Machine::functionUnitNavigator().
immediateUnitNavigator()
Machine::ImmediateUnitNavigator TTAMachine::NullMachine::immediateUnitNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 345 of file NullMachine.cc.
{
    abortWithError("NullMachine::immediateUnitNavigator");
    return Machine::immediateUnitNavigator();
}
References abortWithError, and TTAMachine::Machine::immediateUnitNavigator().
instance()
NullMachine & TTAMachine::NullMachine::instance () static
Returns the only instance of NullMachine class.
Returns
The only instance of NullMachine class.
Definition at line 60 of file NullMachine.cc.
                      {
    return machine_;
}
References machine_.
Referenced by ProximToolbox::machine(), SimulatorFrontend::machine(), and TTAProgram::NullProgram::targetProcessor().
instructionTemplateNavigator()
Machine::InstructionTemplateNavigator TTAMachine::NullMachine::instructionTemplateNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 357 of file NullMachine.cc.
{
    abortWithError("NullMachine::instructionTemplateNavigator");
    return Machine::instructionTemplateNavigator();
}
References abortWithError, and TTAMachine::Machine::instructionTemplateNavigator().
loadState()
void TTAMachine::NullMachine::loadState (const ObjectState * state) virtual
Aborts the program with an error message.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 381 of file NullMachine.cc.
{
    abortWithError("NullMachine::loadState");
}
References abortWithError.
registerFileNavigator()
Machine::RegisterFileNavigator TTAMachine::NullMachine::registerFileNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 369 of file NullMachine.cc.
{
    abortWithError("NullMachine::registerFileNavigator");
    return Machine::registerFileNavigator();
}
References abortWithError, and TTAMachine::Machine::registerFileNavigator().
removeBus()
void TTAMachine::NullMachine::removeBus (Bus & bus) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 194 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeBus");
}
References abortWithError.
removeFunctionUnit()
void TTAMachine::NullMachine::removeFunctionUnit (FunctionUnit & unit) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 225 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeFunctionUnit");
}
References abortWithError.
removeImmediateUnit()
void TTAMachine::NullMachine::removeImmediateUnit (ImmediateUnit & unit) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 235 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeImmediateUnit");
}
References abortWithError.
removeRegisterFile()
void TTAMachine::NullMachine::removeRegisterFile (RegisterFile & unit) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 245 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeRegisterFile");
}
References abortWithError.
removeSocket()
void TTAMachine::NullMachine::removeSocket (Socket & socket) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 204 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeSocket");
}
References abortWithError.
removeUnit()
void TTAMachine::NullMachine::removeUnit (Unit & unit) virtual
Aborts the program with an error message.
Exceptions
InstanceNotFound Never thrown.
IllegalParameters Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 215 of file NullMachine.cc.
{
    abortWithError("NullMachine::removeUnit");
}
References abortWithError.
saveState()
ObjectState * TTAMachine::NullMachine::saveState () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 391 of file NullMachine.cc.
{
    abortWithError("NullMachine::saveState");
    return NULL;
}
References abortWithError.
setGlobalControl()
void TTAMachine::NullMachine::setGlobalControl (ControlUnit & unit) virtual
Aborts the program with an error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 163 of file NullMachine.cc.
{
    abortWithError("NullMachine::setGlobalControl");
}
References abortWithError.
socketNavigator()
Machine::SocketNavigator TTAMachine::NullMachine::socketNavigator () const virtual
Aborts the program with an error message.
Returns
Never returns.
Reimplemented from TTAMachine::Machine.
Definition at line 297 of file NullMachine.cc.
{
    abortWithError("NullMachine::socketNavigator");
    return Machine::socketNavigator();
}
References abortWithError, and TTAMachine::Machine::socketNavigator().
unsetGlobalControl()
void TTAMachine::NullMachine::unsetGlobalControl () virtual
Aborts the program with an error message.
Reimplemented from TTAMachine::Machine.
Definition at line 171 of file NullMachine.cc.
{
    abortWithError("NullMachine::unsetGlobalControl");
}
References abortWithError.
Member Data Documentation
machine_
NullMachine TTAMachine::NullMachine::machine_ static private
The only instance of NullMachine.
Definition at line 90 of file NullMachine.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullMachine.hh
NullMachine.cc