OpenASIP: HDLGenerator::Asynchronous Class Reference
HDLGenerator::Asynchronous Class Reference
#include <HDLGenerator.hh>
Public Member Functions
Asynchronous (const std::string &name)
template<typename SS >
Asynchronous & operator<< (SS op)
template<typename Var >
void addVariable (Var op)
virtual void reads (const std::string &var) override
virtual void build () override
virtual void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::vector< std::shared_ptr< Variable > > variables_
std::unordered_set< std::string > readList_
Detailed Description
Async process/always.
Definition at line 901 of file HDLGenerator.hh.
Constructor & Destructor Documentation
Asynchronous()
HDLGenerator::Asynchronous::Asynchronous (const std::string & name) inline
Definition at line 904 of file HDLGenerator.hh.
: Generatable(name) {}
Member Function Documentation
addVariable()
template<typename Var > void HDLGenerator::Asynchronous::addVariable (Var op) inline
Definition at line 914 of file HDLGenerator.hh.
{
            std::shared_ptr<Variable> ptr = std::make_shared<Var>(op);
            variables_.push_back(ptr);
        }
References variables_.
Referenced by FUGen::buildOperations().
build()
void HDLGenerator::Asynchronous::build () override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 47 of file HDLGenerator.cc.
                    {
    Generatable::build();
    for (auto&& v : variables_) {
        parentType<Module>()->registerVariable(v);
    }
}
References HDLGenerator::Generatable::build(), and variables_.
hdl()
virtual void HDLGenerator::Asynchronous::hdl (std::ostream & stream, Language lang, int level) inline override virtual
@lassetodo Sensitivity list implementation here for verilog if needed.
If sensitivity list is needed for verilog replace
@* with @(, uncomment following code, and add) before
begin
std::string separator = "";
for (auto&& r : readList_) {
  stream << separator << r;
  separator = " or ";
}
Reimplemented from HDLGenerator::Generatable.
Definition at line 929 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                stream << "\n";
                stream << StringTools::indent(level) << name() << " : process(";
                std::string separator = "";
                for (auto&& r : readList_) {
                    if (!isConstant(r)) {
                        stream << separator << r;
                        separator = ", ";
                    }
                }
                stream << ")\n";
                for (auto&& v : variables_) {
                    v->declare(stream, lang, level + 1);
                }
                stream << StringTools::indent(level) << "begin\n";
                implementAll(stream, lang, level + 1);
                stream << StringTools::indent(level) << "end process "
                       << name() << ";\n";
            } else if (lang == Language::Verilog) {
                stream << "\n";
                stream << StringTools::indent(level) << "// " << name() << "\n";
                stream << StringTools::indent(level) << "always @*";
                /**
                 * @lassetodo Sensitivity list implementation here
                 * for verilog if needed.
                 * <pre>
                 * If sensitivity list is needed for verilog replace
                 * @* with @(, uncomment following code, and add ) before
                 * begin
                 *
                 * std::string separator = "";
                 * for (auto&& r : readList_) {
                 *   stream << separator << r;
                 *   separator = " or ";
                 * }
                 * </pre>
                 */
                stream << " begin\n";
                implementAll(stream, lang, level + 1);
                stream << StringTools::indent(level) << "end\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References HDLGenerator::Generatable::implementAll(), StringTools::indent(), HDLGenerator::Generatable::isConstant(), HDLGenerator::Generatable::name(), readList_, variables_, HDLGenerator::Verilog, and HDLGenerator::VHDL.
operator<<()
template<typename SS > Asynchronous & HDLGenerator::Asynchronous::operator<< (SS op) inline
Definition at line 907 of file HDLGenerator.hh.
{
            std::shared_ptr<SequentialStatement> ptr = std::make_shared<SS>(op);
            pushComponent(ptr);
            return *this;
        }
References HDLGenerator::Generatable::pushComponent().
reads()
virtual void HDLGenerator::Asynchronous::reads (const std::string & var) inline override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 919 of file HDLGenerator.hh.
{
            readList_.emplace(var);
            if (parent() != nullptr) {
                parent()->reads(var);
            }
        }
References HDLGenerator::Generatable::parent(), readList_, and HDLGenerator::Generatable::reads().
Referenced by FUGen::buildOperations().
Member Data Documentation
readList_
std::unordered_set<std::string> HDLGenerator::Asynchronous::readList_ private
Definition at line 977 of file HDLGenerator.hh.
Referenced by hdl(), and reads().
variables_
std::vector< std::shared_ptr<Variable> > HDLGenerator::Asynchronous::variables_ private
Definition at line 976 of file HDLGenerator.hh.
Referenced by addVariable(), build(), and hdl().
The documentation for this class was generated from the following files:
HDLGenerator.hh
HDLGenerator.cc