OpenASIP: TemplateListDialog Class Reference
TemplateListDialog Class Reference
#include <TemplateListDialog.hh>
Public Member Functions
TemplateListDialog (wxWindow *parent, TTAMachine::Machine *machine)
virtual ~TemplateListDialog ()
Private Types
enum {
ID_TEMPLATE_LIST = 10000 , ID_SLOT_LIST , ID_LINE , ID_HELP ,
ID_ADD_TEMPLATE , ID_DELETE_TEMPLATE , ID_ADD_SLOT , ID_EDIT_SLOT ,
ID_DELETE_SLOT , ID_NAME , ID_LABEL_NAME
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void updateSlotList ()
void onTemplateSelection (wxListEvent &event)
void onSlotSelection (wxListEvent &event)
void onTemplateName (wxCommandEvent &event)
void onAddTemplate (wxCommandEvent &event)
void onDeleteTemplate (wxCommandEvent &event)
void onAddSlot (wxCommandEvent &event)
void onEditSlot (wxCommandEvent &event)
void onDeleteSlot (wxCommandEvent &event)
void setTexts ()
TTAMachine::InstructionTemplate * selectedTemplate ()
std::string selectedSlot ()
Private Attributes
TTAMachine::Machine * machine_
Parent machine of the instruction templates.
wxStaticBoxSizer * templateSizer_
Box sizer around the template list.
wxStaticBoxSizer * slotSizer_
Box sizer around the slot list.
wxListCtrl * templateList_
Widget for list of templates.
wxListCtrl * slotList_
Widget for list of slots in the selected template.
wxString templateName_
Name of the new template.
Detailed Description
Dialog for listing and editing instruction templates in a machine.
Definition at line 50 of file TemplateListDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_TEMPLATE_LIST
ID_SLOT_LIST
ID_LINE
ID_HELP
ID_ADD_TEMPLATE
ID_DELETE_TEMPLATE
ID_ADD_SLOT
ID_EDIT_SLOT
ID_DELETE_SLOT
ID_NAME
ID_LABEL_NAME
Definition at line 85 of file TemplateListDialog.hh.
         {
        ID_TEMPLATE_LIST = 10000,
        ID_SLOT_LIST,
        ID_LINE,
        ID_HELP,
        ID_ADD_TEMPLATE,
        ID_DELETE_TEMPLATE,
        ID_ADD_SLOT,
        ID_EDIT_SLOT,
        ID_DELETE_SLOT,
        ID_NAME,
        ID_LABEL_NAME
    };
Constructor & Destructor Documentation
TemplateListDialog()
TemplateListDialog::TemplateListDialog (wxWindow * parent, TTAMachine::Machine * machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Parent machine of the instruction templates.
Definition at line 77 of file TemplateListDialog.cc.
                      :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    machine_(machine),
    templateName_(_T("")) {
    createContents(this, true, true);
    templateList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_TEMPLATE_LIST));
    slotList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_SLOT_LIST));
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &templateName_));
    FindWindow(ID_ADD_TEMPLATE)->Disable();
    FindWindow(ID_DELETE_TEMPLATE)->Disable();
    FindWindow(ID_EDIT_SLOT)->Disable();
    // set widget texts
    setTexts();
}
~TemplateListDialog()
TemplateListDialog::~TemplateListDialog () virtual
The Destructor.
Definition at line 103 of file TemplateListDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * TemplateListDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 505 of file TemplateListDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Instruction Templates:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    templateSizer_ = item2;
    wxListCtrl *item4 = new wxListCtrl( parent, ID_TEMPLATE_LIST, wxDefaultPosition, wxSize(160,200), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item5, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, ID_ADD_TEMPLATE, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, ID_DELETE_TEMPLATE, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("Template Slots:") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );
    slotSizer_ = item11;
    wxListCtrl *item13 = new wxListCtrl( parent, ID_SLOT_LIST, wxDefaultPosition, wxSize(250,245), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item11->Add( item13, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item15 = new wxButton( parent, ID_ADD_SLOT, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item16 = new wxButton( parent, ID_EDIT_SLOT, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item17 = new wxButton( parent, ID_DELETE_SLOT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    item11->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item18 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item18, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item19 = new wxGridSizer( 2, 0, 0 );
    wxButton *item20 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item22 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item23 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    item19->Add( item21, 0, wxALL, 5 );
    item0->Add( item19, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_SLOT, ID_ADD_TEMPLATE, ID_DELETE_SLOT, ID_DELETE_TEMPLATE, ID_EDIT_SLOT, ID_HELP, ID_LABEL_NAME, ID_LINE, ID_NAME, ID_SLOT_LIST, ID_TEMPLATE_LIST, slotSizer_, and templateSizer_.
onAddSlot()
void TemplateListDialog::onAddSlot (wxCommandEvent & event) private
Handles the add slot button event.
Definition at line 415 of file TemplateListDialog.cc.
{
    if (selectedTemplate() == NULL) {
        assert(false);
    }
    // Check that there is at least one immediate unit in the machine.
    const Machine::ImmediateUnitNavigator iuNavigator =
        machine_->immediateUnitNavigator();
    if (iuNavigator.count() == 0) {
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        wxString message = WxConversion::toWxString(generator->text(
            ProDeTextGenerator::MSG_ERROR_NO_IMMEDIATE_UNITS).str());
        InformationDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    // check that the template doesn't have all possible slots already
    bool available = false;
    // check buses
    const Machine::BusNavigator busNavigator = machine_->busNavigator();
    for (int i = 0; i < busNavigator.count(); i++) {
        if (!selectedTemplate()->usesSlot(busNavigator.item(i)->name())) {
            available = true;
            break;
        }
    }
    // check immediate slots
    const Machine::ImmediateSlotNavigator immsNavigator =
        machine_->immediateSlotNavigator();
    for (int i = 0; i < immsNavigator.count(); i++) {
        if (!selectedTemplate()->usesSlot(immsNavigator.item(i)->name())) {
            available = true;
            break;
        }
    }
    if (available == false) {
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        wxString message = WxConversion::toWxString(generator->text(
            ProDeTextGenerator::MSG_ERROR_NO_SLOTS_AVAILABLE).str());
        InformationDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    TemplateSlotDialog dialog(this, selectedTemplate());
    dialog.ShowModal();
    updateSlotList();
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::immediateUnitNavigator(), ProDeTextGenerator::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, ProDeTextGenerator::MSG_ERROR_NO_IMMEDIATE_UNITS, ProDeTextGenerator::MSG_ERROR_NO_SLOTS_AVAILABLE, selectedTemplate(), Texts::TextGenerator::text(), WxConversion::toWxString(), and updateSlotList().
onAddTemplate()
void TemplateListDialog::onAddTemplate (wxCommandEvent & event) private
Handles the Add tempalte button event.
Adds a new template to the machine.
Definition at line 349 of file TemplateListDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    string trimmedName =
        WxConversion::toString(templateName_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    Machine::InstructionTemplateNavigator navigator =
        machine_->instructionTemplateNavigator();
    if (navigator.hasItem(trimmedName)) {
        ProDeTextGenerator* prodeTexts =
            ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        format a_tmplate =
            prodeTexts->text(ProDeTextGenerator::COMP_A_TEMPLATE);
        format machine =
            prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
        format tmplate =
            prodeTexts->text(ProDeTextGenerator::COMP_TEMPLATE);
        message % trimmedName % a_tmplate.str() % machine.str() %
            tmplate.str();
        WarningDialog warning(this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    new InstructionTemplate(trimmedName, *machine_);
    templateName_ = _T("");
    TransferDataToWindow();
}
References assert, ProDeTextGenerator::COMP_A_TEMPLATE, ProDeTextGenerator::COMP_MACHINE, ProDeTextGenerator::COMP_TEMPLATE, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), ProDeTextGenerator::instance(), TTAMachine::Machine::instructionTemplateNavigator(), MachineTester::isValidComponentName(), machine, machine_, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, templateName_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), and TransferDataToWindow().
onDeleteSlot()
void TemplateListDialog::onDeleteSlot (wxCommandEvent & event) private
Handles the delete slot button event.
Definition at line 476 of file TemplateListDialog.cc.
{
    selectedTemplate()->removeSlot(selectedSlot());
    updateSlotList();
}
References TTAMachine::InstructionTemplate::removeSlot(), selectedSlot(), selectedTemplate(), and updateSlotList().
onDeleteTemplate()
void TemplateListDialog::onDeleteTemplate (wxCommandEvent & event) private
Deletes the selected template.
Definition at line 302 of file TemplateListDialog.cc.
{
    delete selectedTemplate();
    TransferDataToWindow();
    wxListEvent dummy;
    onTemplateSelection(dummy);
}
References dummy, onTemplateSelection(), selectedTemplate(), and TransferDataToWindow().
onEditSlot()
void TemplateListDialog::onEditSlot (wxCommandEvent & event) private
Handles the edit slot button event.
Definition at line 486 of file TemplateListDialog.cc.
{
    TemplateSlotDialog dialog(this, selectedTemplate(),
        selectedTemplate()->templateSlot(selectedSlot()) );
    dialog.ShowModal();
    updateSlotList();
}
References selectedSlot(), selectedTemplate(), and updateSlotList().
onSlotSelection()
void TemplateListDialog::onSlotSelection (wxListEvent & event) private
Updates the edit/delete slot buttons when the slot selection changes.
Definition at line 287 of file TemplateListDialog.cc.
{
    if (slotList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_DELETE_SLOT)->Enable();
        FindWindow(ID_EDIT_SLOT)->Enable();
    } else {
        FindWindow(ID_DELETE_SLOT)->Disable();
        FindWindow(ID_EDIT_SLOT)->Disable();
    }
}
References ID_DELETE_SLOT, ID_EDIT_SLOT, and slotList_.
Referenced by updateSlotList().
onTemplateName()
void TemplateListDialog::onTemplateName (wxCommandEvent & event) private
Enables and disables the Add template button when text is entered in the template name widget.
Definition at line 398 of file TemplateListDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = templateName_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(ID_ADD_TEMPLATE)->Disable();
    } else {
        FindWindow(ID_ADD_TEMPLATE)->Enable();
    }
}
References assert, ID_ADD_TEMPLATE, and templateName_.
onTemplateSelection()
void TemplateListDialog::onTemplateSelection (wxListEvent & event) private
Updates the slot list when the template selection changes.
Definition at line 273 of file TemplateListDialog.cc.
{
    if (templateList_->GetSelectedItemCount() == 0) {
        FindWindow(ID_DELETE_TEMPLATE)->Disable();
    } else {
        FindWindow(ID_DELETE_TEMPLATE)->Enable();
    }
    updateSlotList();
}
References ID_DELETE_TEMPLATE, templateList_, and updateSlotList().
Referenced by onDeleteTemplate().
selectedSlot()
string TemplateListDialog::selectedSlot () private
Returns name of the selected slot.
Returns
Name of the selected slot.
Definition at line 337 of file TemplateListDialog.cc.
{
    string name = WidgetTools::lcStringSelection(slotList_, 0);
    return name;
}
References WidgetTools::lcStringSelection(), and slotList_.
Referenced by onDeleteSlot(), and onEditSlot().
selectedTemplate()
InstructionTemplate * TemplateListDialog::selectedTemplate () private
Returns pointer to the selected InstructionTemplate.
Returns
Pointer to the selected InstructionTemplate.
Definition at line 316 of file TemplateListDialog.cc.
{
    long item = -1;
    item = templateList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item < 0) {
        return NULL;
    }
    InstructionTemplate* temp =
        machine_->instructionTemplateNavigator().item(item);
    return temp;
}
References TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, and templateList_.
Referenced by onAddSlot(), onDeleteSlot(), onDeleteTemplate(), onEditSlot(), and updateSlotList().
setTexts()
void TemplateListDialog::setTexts () private
Sets texts for widgets.
Definition at line 111 of file TemplateListDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_TEMPLATES_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_TEMPLATE),
                          GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_TEMPLATE),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_SLOT),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_SLOT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_SLOT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_TEMPLATES_TEMPLATES_BOX);
    WidgetTools::setWidgetLabel(templateSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_TEMPLATES_SLOTS_BOX);
    WidgetTools::setWidgetLabel(slotSizer_, fmt.str());
    // Create instruction template list columns.
    wxListCtrl* templateList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_TEMPLATE_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    templateList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                               wxLIST_FORMAT_LEFT, 160);
    // Create template slot list columns.
    wxListCtrl* slotList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_SLOT_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_SLOT);
    slotList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_DESTINATION);
    slotList->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_WIDTH);
    slotList->InsertColumn(2, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 50);
}
References ID_ADD_SLOT, ID_ADD_TEMPLATE, ID_DELETE_SLOT, ID_DELETE_TEMPLATE, ID_EDIT_SLOT, ID_HELP, ID_LABEL_NAME, ID_SLOT_LIST, ID_TEMPLATE_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), slotSizer_, templateSizer_, Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_DESTINATION, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_SLOT, ProDeTextGenerator::TXT_COLUMN_WIDTH, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_TEMPLATES_DIALOG_TITLE, ProDeTextGenerator::TXT_TEMPLATES_SLOTS_BOX, and ProDeTextGenerator::TXT_TEMPLATES_TEMPLATES_BOX.
TransferDataToWindow()
bool TemplateListDialog::TransferDataToWindow () private virtual
Transfers data from the machine to the dialog widgets.
Definition at line 183 of file TemplateListDialog.cc.
{
    // update template list
    templateList_->DeleteAllItems();
    Machine::InstructionTemplateNavigator navigator =
        machine_->instructionTemplateNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        templateList_->InsertItem(
            i, WxConversion::toWxString(navigator.item(i)->name()));
    }
    updateSlotList();
    return wxDialog::TransferDataToWindow();
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, templateList_, WxConversion::toWxString(), and updateSlotList().
Referenced by onAddTemplate(), and onDeleteTemplate().
updateSlotList()
void TemplateListDialog::updateSlotList () private
Updates the template slot list.
Definition at line 202 of file TemplateListDialog.cc.
{
    slotList_->DeleteAllItems();
    slotList_->Enable();
    InstructionTemplate* templ = selectedTemplate();
    if (templ == NULL) {
        FindWindow(ID_ADD_SLOT)->Disable();
        return;
    }
    FindWindow(ID_ADD_SLOT)->Enable();
    // Add bus slots.
    Machine::BusNavigator busNavigator = machine_->busNavigator();
    for (int i = 0; i < busNavigator.count(); i++) {
        if (templ->usesSlot(busNavigator.item(i)->name())) {
            Bus* slot = busNavigator.item(i);
            // Add slot name.
            slotList_->InsertItem(
                0, WxConversion::toWxString(slot->name()));
            // Add slot Destination.
            // Set slot destination.
            wxString name = WxConversion::toWxString(
                templ->destinationOfSlot(slot->name())->name());
            slotList_->SetItem(0, 1, name);
            // Set slot width.
            wxString width = WxConversion::toWxString(
                templ->supportedWidth(slot->name()));
            slotList_->SetItem(0, 2, width);
        }
    }
    // Add immediate slots.
    Machine::ImmediateSlotNavigator immsNavigator =
        machine_->immediateSlotNavigator();
    for (int i = 0; i < immsNavigator.count(); i++) {
        if (templ->usesSlot(immsNavigator.item(i)->name())) {
            ImmediateSlot* slot = immsNavigator.item(i);
            // Add slot name.
            slotList_->InsertItem(
                0, WxConversion::toWxString(slot->name()));
            // Set slot destination.
            wxString name = WxConversion::toWxString(
                templ->destinationOfSlot(slot->name())->name());
            slotList_->SetItem(0, 1, name);
            // Set slot width.
            wxString width = WxConversion::toWxString(
                templ->supportedWidth(slot->name()));
            slotList_->SetItem(0, 2, width);
        }
    }
    wxListEvent dummy;
    onSlotSelection(dummy);
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::InstructionTemplate::destinationOfSlot(), dummy, ID_ADD_SLOT, TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), onSlotSelection(), selectedTemplate(), slotList_, TTAMachine::InstructionTemplate::supportedWidth(), WxConversion::toWxString(), and TTAMachine::InstructionTemplate::usesSlot().
Referenced by onAddSlot(), onDeleteSlot(), onEditSlot(), onTemplateSelection(), and TransferDataToWindow().
Member Data Documentation
machine_
TTAMachine::Machine* TemplateListDialog::machine_ private
Parent machine of the instruction templates.
Definition at line 72 of file TemplateListDialog.hh.
Referenced by onAddSlot(), onAddTemplate(), selectedTemplate(), TransferDataToWindow(), and updateSlotList().
slotList_
wxListCtrl* TemplateListDialog::slotList_ private
Widget for list of slots in the selected template.
Definition at line 80 of file TemplateListDialog.hh.
Referenced by onSlotSelection(), selectedSlot(), and updateSlotList().
slotSizer_
wxStaticBoxSizer* TemplateListDialog::slotSizer_ private
Box sizer around the slot list.
Definition at line 76 of file TemplateListDialog.hh.
Referenced by createContents(), and setTexts().
templateList_
wxListCtrl* TemplateListDialog::templateList_ private
Widget for list of templates.
Definition at line 78 of file TemplateListDialog.hh.
Referenced by onTemplateSelection(), selectedTemplate(), and TransferDataToWindow().
templateName_
wxString TemplateListDialog::templateName_ private
Name of the new template.
Definition at line 82 of file TemplateListDialog.hh.
Referenced by onAddTemplate(), and onTemplateName().
templateSizer_
wxStaticBoxSizer* TemplateListDialog::templateSizer_ private
Box sizer around the template list.
Definition at line 74 of file TemplateListDialog.hh.
Referenced by createContents(), and setTexts().
The documentation for this class was generated from the following files:
TemplateListDialog.hh
TemplateListDialog.cc