OpenASIP: BFPostpassBypasser Class Reference
BFPostpassBypasser Class Reference
#include <BFPostpassBypasser.hh>
Public Member Functions
BFPostpassBypasser (BF2Scheduler &sched)
bool operator() () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Member Functions
bool tryBypassNode (MoveNode &n)
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 42 of file BFPostpassBypasser.hh.
Constructor & Destructor Documentation
BFPostpassBypasser()
BFPostpassBypasser::BFPostpassBypasser (BF2Scheduler & sched) inline
Definition at line 44 of file BFPostpassBypasser.hh.
                                            :
        BFOptimization(sched) {}
Member Function Documentation
operator()()
bool BFPostpassBypasser::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 42 of file BFPostpassBypasser.cc.
{
    for (int i = 0; i < ddg().nodeCount(); i++) {
        MoveNode& n = ddg().node(i);
        bool dred = tryBypassNode(n);
        // make sure do not skip over one if dre removes something
        if (dred) {
            i--;
        }
    }
    return !postChildren_.empty();
}
References BFOptimization::ddg(), BoostGraph< GraphNode, GraphEdge >::node(), BoostGraph< GraphNode, GraphEdge >::nodeCount(), Reversible::postChildren_, and tryBypassNode().
tryBypassNode()
bool BFPostpassBypasser::tryBypassNode (MoveNode & n) private
Definition at line 55 of file BFPostpassBypasser.cc.
{
    DataDependenceEdge* bypassEdge = sched_.findBypassEdge(n);
    if (bypassEdge == NULL) {
        return false;
    }
    MoveNode& src = ddg().tailNode(*bypassEdge);
    if (!ddg().guardsAllowBypass(src, n)) {
        return false;
    }
    auto bypass = new BFPostpassBypass(sched_, src, n, bypassEdge->isBackEdge());
    if (!(runPostChild(bypass))) {
        return false;
    }
    return bypass->dred();
}
References BFOptimization::ddg(), BF2Scheduler::findBypassEdge(), DataDependenceEdge::isBackEdge(), Reversible::runPostChild(), BFOptimization::sched_, and BoostGraph< GraphNode, GraphEdge >::tailNode().
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPostpassBypasser.hh
BFPostpassBypasser.cc