OpenASIP: RLBUPriorityCriticalPath Class Reference
RLBUPriorityCriticalPath Class Reference
#include <ReadyMoveNodeGroupList.hh>
Public Member Functions
bool operator() (MoveNodeGroup &a, MoveNodeGroup &b)
Detailed Description
A function object for prioritizing the ready list according to the move's distance from farthest source node. Futher away from source the better.
Definition at line 87 of file ReadyMoveNodeGroupList.hh.
Member Function Documentation
operator()()
bool RLBUPriorityCriticalPath::operator() (MoveNodeGroup & a, MoveNodeGroup & b) inline
Compares two nodes according to their priority in the ready list.
Parameters
a Node a.
b Node b.
Returns
True if b should be scheduled before a (b greater than a).
Definition at line 97 of file ReadyMoveNodeGroupList.hh.
{
        if (b.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return true;
        }
        if (a.isScheduled()) {
            // keep scheduled MoveNodeSets on a top of a queue
            // so they will be poped out
            return false;
        }
        if (a.node(0).move().isControlFlowMove()) {
            // Push control flow move to beginning of the ready list
            return false;
        }
        if (b.node(0).move().isControlFlowMove()) {
            // Push control flow move to beginning of the ready list
            return true;
        }
#if 0
        // also prioritize moves which write the jump guard.
        if (a.writesJumpGuard()) {
            return false;
        }
        // also prioritize moves which write the jump guard.
        if (b.writesJumpGuard()) {
            return true;
        }
#endif
        // Compute distances only once, it is expensive operation on graph
        int aSourceDistance = a.maxSourceDistance();
        int bSourceDistance = b.maxSourceDistance();
        if (bSourceDistance == aSourceDistance) {
            int aSinkDistance = a.maxSinkDistance();
            int bSinkDistance = b.maxSinkDistance();
            if (bSinkDistance == aSinkDistance) {
                return b.node(0).nodeID() < a.node(0).nodeID();
            }
            // the lower the sink distance, the higher the priority
            // this priority is better for loop scheduling, to make
            // true tails get scheudled first.
            return bSinkDistance < aSinkDistance;
        }
        // the higher the source distance, the higher the priority
        return bSourceDistance > aSourceDistance;
    }
References TTAProgram::Move::isControlFlowMove(), MoveNodeGroup::isScheduled(), MoveNodeGroup::maxSinkDistance(), MoveNodeGroup::maxSourceDistance(), MoveNode::move(), MoveNodeGroup::node(), GraphNode::nodeID(), and MoveNodeGroup::writesJumpGuard().
The documentation for this class was generated from the following file:
ReadyMoveNodeGroupList.hh