OpenASIP: StringListCmdLineOptionParser Class Reference
StringListCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
StringListCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~StringListCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual std::string String (int index=0) const
virtual int listSize () const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual unsigned unsignedInteger (int index=0) const
virtual double real () const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
Private Member Functions
StringListCmdLineOptionParser (const StringListCmdLineOptionParser &)
Copying not allowed.
StringListCmdLineOptionParser & operator= (const StringListCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
std::vector< std::string > values_
The values in string list.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that has a list of strings as value.
Definition at line 344 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
StringListCmdLineOptionParser() [1/2]
StringListCmdLineOptionParser::StringListCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 799 of file CmdLineOptionParser.cc.
                     : CmdLineOptionParser(name, desc, alias) {
}
~StringListCmdLineOptionParser()
StringListCmdLineOptionParser::~StringListCmdLineOptionParser () virtual
Destructor.
Definition at line 808 of file CmdLineOptionParser.cc.
{
    values_.clear();
}
References values_.
StringListCmdLineOptionParser() [2/2]
StringListCmdLineOptionParser::StringListCmdLineOptionParser (const StringListCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * StringListCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 821 of file CmdLineOptionParser.cc.
{
    StringListOptionValue* copy = new StringListOptionValue(values_);
    return copy;
}
References copy(), and values_.
Referenced by copy().
listSize()
int StringListCmdLineOptionParser::listSize () const virtual
Returns the number of list elements.
Returns
The number of list elements.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 889 of file CmdLineOptionParser.cc.
{
    return values_.size();
}
References values_.
operator=()
StringListCmdLineOptionParser & StringListCmdLineOptionParser::operator= (const StringListCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool StringListCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of string set.
Value should be strings separated by commas.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine If argument is invalid.
Implements CmdLineOptionParser.
Definition at line 837 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for string list option";
        throw IllegalCommandLine(__FILE__, __LINE__, __func__, msg);
    }
    if (arguments == "") {
        string msg = "Missing value for option " + longName();
        throw IllegalCommandLine(__FILE__, __LINE__, __func__, msg);
    }
    string comma = ",";
    string::size_type commaPosition = 0;
    string::size_type lastPosition = 0;
    while (commaPosition < arguments.size()) {
        commaPosition = arguments.find(comma, lastPosition);
        if (commaPosition == string::npos) {
            values_.push_back(
                arguments.substr(lastPosition, arguments.size()));
            break;
        } else {
            values_.push_back(
                arguments.substr(lastPosition, commaPosition-lastPosition));
            lastPosition = commaPosition + 1;
        }
    }
    setDefined();
    return true;
}
References __func__, CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and values_.
String()
std::string StringListCmdLineOptionParser::String (int index = 0) const virtual
Returns a particular value of string list option.
Parameters
index The index of list element that is wanted.
Returns
The value of a particular element in list.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 877 of file CmdLineOptionParser.cc.
{
    assert(index > 0 && static_cast<unsigned>(index) <= values_.size());
    return values_[index - 1];
}
References assert, and values_.
Member Data Documentation
values_
std::vector<std::string> StringListCmdLineOptionParser::values_ private
The values in string list.
Definition at line 367 of file CmdLineOptionParser.hh.
Referenced by copy(), listSize(), parseValue(), String(), and ~StringListCmdLineOptionParser().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc