OpenASIP: ProgramOperation Class Reference
ProgramOperation Class Reference
#include <ProgramOperation.hh>
Classes
class Comparator
Public Member Functions
ProgramOperation (const Operation &operation, const llvm::MachineInstr *instr=NULL)
ProgramOperation ()
TODO: this better go, just for testing with empty operation...
~ProgramOperation ()
void addNode (MoveNode &node)
void addInputNode (MoveNode &node)
void addOutputNode (MoveNode &node, int outputIndex)
void addOutputNode (MoveNode &node)
void addGuardOutputNode (MoveNode &node)
int outputIndexFromGuardOfMove (const MoveNode &node) const
int outputIndexFromGuard (const TTAMachine::PortGuard &pg) const
int outputIndexOfMove (const MoveNode &mn) const
const TTAMachine::FunctionUnit * scheduledFU () const
const TTAMachine::FunctionUnit * fuFromOutMove (const MoveNode &outputNode) const
const TTAMachine::HWOperation * hwopFromOutMove (const MoveNode &outputNode) const
void removeOutputNode (MoveNode &node, int outputIndex)
void removeOutputNode (MoveNode &node)
void removeGuardOutputNode (MoveNode &node)
void removeInputNode (MoveNode &node)
bool isComplete ()
bool isReady ()
bool isMultinode ()
bool isAssigned ()
bool isAnyNodeAssigned ()
bool isAnyInputAssigned ()
bool isAnyOutputAssigned ()
bool areInputsAssigned ()
bool areOutputsAssigned ()
MoveNode & opcodeSettingNode ()
MoveNodeSet & inputNode (int in) const
MoveNodeSet & outputNode (int out) const
bool hasOutputNode (int out) const
bool hasInputNode (int in) const
const Operation & operation () const
void setOperation (const Operation &op)
int inputMoveCount () const
int outputMoveCount () const
bool hasMoveNodeForMove (const TTAProgram::Move &move) const
MoveNode & moveNode (const TTAProgram::Move &move) const
MoveNode & inputMove (int index) const
MoveNode & outputMove (int index) const
MoveNode * triggeringMove () const
MoveNode * findTriggerFromUnit (const TTAMachine::Unit &unit) const
bool isLegalFU (const TTAMachine::FunctionUnit &fu) const
const llvm::MachineInstr * machineInstr () const
void switchInputs (int idx1=1, int idx2=2)
std::string toString () const
unsigned int poId () const
bool hasConstantOperand () const
bool operator== (const ProgramOperation &po)
Static Public Member Functions
static int outputIndexFromGuard (const TTAMachine::PortGuard &pg, const Operation &op)
Private Types
typedef std::vector< MoveNode * > MoveVector
Private Member Functions
ProgramOperation (const ProgramOperation &)
ProgramOperation & operator= (const ProgramOperation &)
Private Attributes
const Operation * operation_
std::map< int, MoveNodeSet * > inputMoves_
std::map< int, MoveNodeSet * > outputMoves_
MoveVector allInputMoves_
MoveVector allOutputMoves_
unsigned int poId_
const llvm::MachineInstr * mInstr_
Static Private Attributes
static unsigned int idCounter = 0
Detailed Description
Represents a single execution of an operation in a program.
Definition at line 70 of file ProgramOperation.hh.
Member Typedef Documentation
MoveVector
typedef std::vector<MoveNode*> ProgramOperation::MoveVector private
Definition at line 158 of file ProgramOperation.hh.
Constructor & Destructor Documentation
ProgramOperation() [1/3]
ProgramOperation::ProgramOperation (const Operation & operation, const llvm::MachineInstr * instr = NULL)
Constructor.
Creates a ProgramOperation from operation
Parameters
operation Operation
Definition at line 67 of file ProgramOperation.cc.
                                   :
    operation_(&operation), poId_(idCounter++), mInstr_(instr) {
}
ProgramOperation() [2/3]
ProgramOperation::ProgramOperation ()
TODO: this better go, just for testing with empty operation...
Constructor.
Creates a ProgramOperation from NullOperation
Definition at line 79 of file ProgramOperation.cc.
                                   :
    operation_(&NullOperation::instance()), poId_(idCounter++) {
    inputMoves_.clear();
    outputMoves_.clear();
}
References inputMoves_, and outputMoves_.
~ProgramOperation()
ProgramOperation::~ProgramOperation ()
Destructor.
Deletes MoveNodeSets. Does not unregister these program operations from movenodes.
Definition at line 90 of file ProgramOperation.cc.
{
    // If MoveNodes of PO are not destroyed before PO they need to unset
    // their source or destination operation respectively
    for (int i = 0; i < inputMoveCount(); i++) {
        inputMove(i).removeDestinationOperation(this);
    }
    for (int i = 0; i < outputMoveCount(); i++) {
        if (&outputMove(i).sourceOperation() == this) {
            outputMove(i).unsetSourceOperation();
        } else {
            if (&outputMove(i).guardOperation() == this) {
                outputMove(i).unsetGuardOperation();
            }
        }
    }
    AssocTools::deleteAllValues(inputMoves_);
    AssocTools::deleteAllValues(outputMoves_);
}
References AssocTools::deleteAllValues(), inputMove(), inputMoveCount(), inputMoves_, outputMove(), outputMoveCount(), outputMoves_, MoveNode::removeDestinationOperation(), MoveNode::sourceOperation(), MoveNode::unsetGuardOperation(), and MoveNode::unsetSourceOperation().
ProgramOperation() [3/3]
ProgramOperation::ProgramOperation (const ProgramOperation &) private
Member Function Documentation
addGuardOutputNode()
void ProgramOperation::addGuardOutputNode (MoveNode & node)
Add given node to the set of nodes that belong to this program operation.
Add node to nodes of program operation
Parameters
node MoveNode to add to operation
Definition at line 201 of file ProgramOperation.cc.
{
    addOutputNode(node, outputIndexFromGuardOfMove(node));
}
References addOutputNode(), and outputIndexFromGuardOfMove().
Referenced by MoveNodeDuplicator::duplicateMoveNode().
addInputNode()
void ProgramOperation::addInputNode (MoveNode & node)
Add given node to the set of input nodes that belong to this program operation.
Input node is a move that writes an operand of the operation.
Parameters
node MoveNode to add to operation
Definition at line 144 of file ProgramOperation.cc.
{
    int inputIndex = node.move().destination().operationIndex();
    if (MapTools::containsKey(inputMoves_, inputIndex)) {
        MoveNodeSet* nodeSet =
            MapTools::valueForKey<MoveNodeSet*>(inputMoves_, inputIndex);
        nodeSet->addMoveNode(node);
        allInputMoves_.push_back(&node);
    } else {
        MoveNodeSet* nodeSet = new MoveNodeSet;
        nodeSet->addMoveNode(node);
        inputMoves_[inputIndex] = nodeSet;
        allInputMoves_.push_back(&node);
    }
}
References MoveNodeSet::addMoveNode(), allInputMoves_, MapTools::containsKey(), TTAProgram::Move::destination(), inputMoves_, MapTools::keyForValue(), MoveNode::move(), and TTAProgram::Terminal::operationIndex().
Referenced by addNode(), MoveNode::copy(), and MoveNodeDuplicator::duplicateMoveNode().
addNode()
void ProgramOperation::addNode (MoveNode & node)
Add given node to the set of nodes that belong to this program operation.
Warning: this should not be used with bypassed moves!
Add node to nodes of program operation
Parameters
node MoveNode to add to operation
Definition at line 119 of file ProgramOperation.cc.
{
    if (node.move().source().isFUPort()) {
        if (node.move().source().hintOperation().name() ==
            operation().name()) {
            addOutputNode(node);
        }
    } else {
        if (node.move().destination().isFUPort()) {
            if (node.move().destination().hintOperation().name() ==
                operation().name()) {
                addInputNode(node);
            }
        }
    }
}
References addInputNode(), addOutputNode(), TTAProgram::Move::destination(), TTAProgram::Terminal::hintOperation(), TTAProgram::Terminal::isFUPort(), MoveNode::move(), Operation::name(), operation(), and TTAProgram::Move::source().
addOutputNode() [1/2]
void ProgramOperation::addOutputNode (MoveNode & node)
Add given node to the set of nodes that belong to this program operation.
Add node to nodes of program operation
Parameters
node MoveNode to add to operation
Definition at line 188 of file ProgramOperation.cc.
{
    int outputIndex = node.move().source().operationIndex();
    addOutputNode(node, outputIndex);
}
References addOutputNode(), MoveNode::move(), TTAProgram::Terminal::operationIndex(), and TTAProgram::Move::source().
addOutputNode() [2/2]
void ProgramOperation::addOutputNode (MoveNode & node, int outputIndex)
Add given node to the set of nodes that belong to this program operation.
Add node to nodes of program operation
Parameters
node MoveNode to add to operation
outputIndex output index of the operation.
Definition at line 167 of file ProgramOperation.cc.
{
    if (MapTools::containsKey(outputMoves_, outputIndex)) {
        MoveNodeSet* nodeSet =
            MapTools::valueForKey<MoveNodeSet*>(outputMoves_,outputIndex);
        nodeSet->addMoveNode(node);
        allOutputMoves_.push_back(&node);
    } else {
        MoveNodeSet* nodeSet = new MoveNodeSet;
        nodeSet->addMoveNode(node);
        allOutputMoves_.push_back(&node);
        outputMoves_[outputIndex] = nodeSet;
    }
}
References MoveNodeSet::addMoveNode(), allOutputMoves_, MapTools::containsKey(), MapTools::keyForValue(), and outputMoves_.
Referenced by addGuardOutputNode(), addNode(), addOutputNode(), MoveNode::copy(), and MoveNodeDuplicator::duplicateMoveNode().
areInputsAssigned()
bool ProgramOperation::areInputsAssigned ()
Return true if nodes of this operation have function unit assigned to their source or destination respectively
Returns
True if nodes have source or destination function unit assigned
Definition at line 435 of file ProgramOperation.cc.
{
    for (int i = 0; i < inputMoveCount(); i++ ) {
        if (!inputMove(i).isAssigned()) {
            return false;
        }
    }
    return true;
}
References inputMove(), inputMoveCount(), and MoveNode::isAssigned().
Referenced by CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp().
areOutputsAssigned()
bool ProgramOperation::areOutputsAssigned ()
Return true if nodes of this operation have function unit assigned to their source or destination respectively
Returns
True if nodes have source or destination function unit assigned
Definition at line 467 of file ProgramOperation.cc.
{
    for (int i = 0; i < outputMoveCount(); i++ ) {
        if (!outputMove(i).isAssigned()) {
            return false;
        }
    }
    return true;
}
References MoveNode::isAssigned(), outputMove(), and outputMoveCount().
findTriggerFromUnit()
MoveNode * ProgramOperation::findTriggerFromUnit (const TTAMachine::Unit & unit) const
Definition at line 677 of file ProgramOperation.cc.
{
    const TTAMachine::FunctionUnit* fu =
    dynamic_cast<const TTAMachine::FunctionUnit*>(&unit);
    int ioIndex = -1;
    assert(fu);
    int portC = fu->portCount();
    for (int i = 0; i < portC; i++) {
        auto p = fu->port(i);
        const TTAMachine::FUPort* port = dynamic_cast<const TTAMachine::FUPort*>(p);
        if (port != nullptr && port->isTriggering()) {
            const TTAMachine::HWOperation* hwop =
            fu->operation(operation().name());
            ioIndex = hwop->io(*port);
            auto ngi = inputMoves_.find(ioIndex);
            if (ngi == inputMoves_.end()) {
                return NULL;
            }
            auto mng = *ngi->second;
            if (mng.count() < 1)
                return NULL;
            return &mng.at(0);
        }
    }
    return NULL;
}
References assert, inputMoves_, TTAMachine::HWOperation::io(), TTAMachine::FUPort::isTriggering(), Operation::name(), operation(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::port(), and TTAMachine::Unit::portCount().
Referenced by ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), and triggeringMove().
fuFromOutMove()
const TTAMachine::FunctionUnit * ProgramOperation::fuFromOutMove (const MoveNode & outputNode) const
Definition at line 844 of file ProgramOperation.cc.
{
    if (outputNode.isAssigned() &&
        outputNode.isSourceOperation() &&
        &outputNode.sourceOperation() == this) {
        return static_cast<const TTAMachine::FunctionUnit*>(
            outputNode.move().source().port().parentUnit());
    }
    if (!outputNode.move().isUnconditional() &&
        outputNode.isGuardOperation() &&
        outputNode.guardOperationPtr().get() == this) {
        const TTAMachine::Guard& guard =
            outputNode.move().guard().guard();
        const TTAMachine::PortGuard* pg =
            dynamic_cast<const TTAMachine::PortGuard*>(&guard);
        assert(pg); // todo: throw?
        return static_cast<const TTAMachine::FunctionUnit*>(
            pg->port()->parentUnit());
    }
    return nullptr;
}
References assert, outputNode(), TTAMachine::BaseFUPort::parentUnit(), and TTAMachine::PortGuard::port().
Referenced by ExecutionPipelineBroker::earliestFromDestination(), OutputFUBroker::isAlreadyAssigned(), ExecutionPipelineBroker::latestFromSource(), ExecutionPipelineResource::latestTriggerWriteCycle(), scheduledFU(), triggeringMove(), and OutputFUBroker::unassign().
hasConstantOperand()
bool ProgramOperation::hasConstantOperand () const
Returns true in case the operation has at least one operand that is a contant/immediate.
Definition at line 831 of file ProgramOperation.cc.
{
    for (MoveVector::const_iterator i = allInputMoves_.begin();
         i != allInputMoves_.end(); ++i) {
        MoveNode* mn = *i;
        if (mn->isSourceConstant())
            return true;
    }
    return false;
}
References allInputMoves_, and MoveNode::isSourceConstant().
hasInputNode()
bool ProgramOperation::hasInputNode (int index) const
Return true if program operation has node registered for input identified by index.
Parameters
Index Operation input to test
Returns
True if the operation input Index has node registered
Definition at line 560 of file ProgramOperation.cc.
{
    if (MapTools::containsKey(inputMoves_,index)) {
        return true;
    } else {
        return false;
    }
}
References MapTools::containsKey(), and inputMoves_.
hasMoveNodeForMove()
bool ProgramOperation::hasMoveNodeForMove (const TTAProgram::Move & move) const
Definition at line 723 of file ProgramOperation.cc.
          {
    for (std::size_t i = 0; i < allInputMoves_.size(); ++i) {
        MoveNode& moveNode = *allInputMoves_.at(i);
        if (&moveNode.move() == &move)
            return true;
    }
    for (std::size_t i = 0; i < allOutputMoves_.size(); ++i) {
        MoveNode& moveNode = *allOutputMoves_.at(i);
        if (&moveNode.move() == &move)
            return true;
    }
    return false;
}
References allInputMoves_, allOutputMoves_, MoveNode::move(), and moveNode().
hasOutputNode()
bool ProgramOperation::hasOutputNode (int index) const
Return true if program operation has node registered for output identified by index.
Parameters
Index Operation output to test
Returns
True if the operation output Index has node registered
Definition at line 576 of file ProgramOperation.cc.
{
    if (MapTools::containsKey(outputMoves_,index)) {
        return true;
    } else {
        return false;
    }
}
References MapTools::containsKey(), and outputMoves_.
hwopFromOutMove()
const TTAMachine::HWOperation * ProgramOperation::hwopFromOutMove (const MoveNode & outputNode) const
Definition at line 895 of file ProgramOperation.cc.
{
    if (outputNode.isSourceOperation() &&
        &outputNode.sourceOperation() == this) {
        return outputNode.move().source().functionUnit().operation(
            operation().name());
    } else {
        const TTAMachine::Guard& guard =
            outputNode.move().guard().guard();
        const TTAMachine::PortGuard* pg =
            dynamic_cast<const TTAMachine::PortGuard*>(&guard);
        assert(pg); // todo: throw?
        const TTAMachine::Port* p = pg->port();
        const TTAMachine::Unit* u = p->parentUnit();
        const TTAMachine::FunctionUnit* fu =
            static_cast<const TTAMachine::FunctionUnit*>(u);
        return fu->operation(operation().name());
    }
}
References assert, Operation::name(), operation(), TTAMachine::FunctionUnit::operation(), outputNode(), TTAMachine::Port::parentUnit(), and TTAMachine::PortGuard::port().
Referenced by BF2ScheduleFront::prefResultCycle().
inputMove()
MoveNode & ProgramOperation::inputMove (int index) const
Returns the given input move.
Parameters
index Index of the move.
Returns
The input move.
Definition at line 621 of file ProgramOperation.cc.
{
    return *allInputMoves_.at(index);
}
References allInputMoves_.
Referenced by RegisterCopyAdder::addCandidateSetAnnotations(), RegisterCopyAdder::addRegisterCopies(), InputFUBroker::allAvailableResources(), ResourceConstraintAnalyzer::analyzeMoveNode(), annotateAllInputs(), areInputsAssigned(), BFEarlyBypasser::bypassSourceLatestCycle(), DataDependenceGraphBuilder::checkAndCreateMemDep(), ExecutionPipelineResource::checkOperandAllowed(), DataDependenceGraph::dotString(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), BF2ScheduleFront::findInducingBypassSourceFromOperation(), MachineConnectivityCheck::findPossibleDestinationPorts(), BF2Scheduler::getDstUnit(), BFOptimization::immCountPreventsScheduling(), RegisterCopyAdder::isAllowedUnit(), isAnyInputAssigned(), isAnyNodeAssigned(), isAssigned(), MoveNode::isLastUnscheduledMoveOfDstOp(), isLegalFU(), ExecutionPipelineBroker::isMoveTrigger(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), DataDependenceGraphBuilder::memoryCategory(), CriticalPathBBMoveNodeSelector::mightBeReady(), DataDependenceGraph::moveFUDependenciesToTrigger(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandsOverwritten(), BFLateBypassGuard::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), ExecutionPipelineResource::poConflictsWithInputPort(), BUMoveNodeSelector::queueOperation(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), BFOptimization::RFReadPortCountPreventsScheduling(), scheduledFU(), BUBasicBlockScheduler::scheduleOperation(), setOperation(), switchInputs(), ExecutionPipelineResource::triggerTooEarly(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveEq(), PreOptimizer::tryToRemoveGuardInversingOp(), PreOptimizer::tryToRemoveXor(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), DataDependenceGraph::writeToXMLFile(), and ~ProgramOperation().
inputMoveCount()
int ProgramOperation::inputMoveCount () const
Count of input moves to this operation.
Returns
The count of input moves.
Definition at line 600 of file ProgramOperation.cc.
{
    return allInputMoves_.size();
}
References allInputMoves_.
Referenced by RegisterCopyAdder::addCandidateSetAnnotations(), RegisterCopyAdder::addRegisterCopies(), InputFUBroker::allAvailableResources(), ResourceConstraintAnalyzer::analyzeMoveNode(), annotateAllInputs(), areInputsAssigned(), BFEarlyBypasser::bypassSourceLatestCycle(), DataDependenceGraphBuilder::checkAndCreateMemDep(), ExecutionPipelineResource::checkOperandAllowed(), DataDependenceGraph::dotString(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), BF2ScheduleFront::findInducingBypassSourceFromOperation(), MachineConnectivityCheck::findPossibleDestinationPorts(), BF2Scheduler::getDstUnit(), BFOptimization::immCountPreventsScheduling(), RegisterCopyAdder::isAllowedUnit(), isAnyInputAssigned(), isAnyNodeAssigned(), isAssigned(), MoveNode::isLastUnscheduledMoveOfDstOp(), isLegalFU(), ExecutionPipelineBroker::isMoveTrigger(), DataDependenceGraph::latestCycle(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), DataDependenceGraphBuilder::memoryCategory(), CriticalPathBBMoveNodeSelector::mightBeReady(), DataDependenceGraph::moveFUDependenciesToTrigger(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandsOverwritten(), BFLateBypassGuard::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), ExecutionPipelineResource::poConflictsWithInputPort(), BUMoveNodeSelector::queueOperation(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), BFOptimization::RFReadPortCountPreventsScheduling(), scheduledFU(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperation(), setOperation(), switchInputs(), ExecutionPipelineResource::triggerTooEarly(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveEq(), PreOptimizer::tryToRemoveXor(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), DataDependenceGraph::writeToXMLFile(), and ~ProgramOperation().
inputNode()
MoveNodeSet & ProgramOperation::inputNode (int index) const
Return the nodes that writes input Index of operation
Parameters
index Index of a operation to test
Returns
Set of nodes that writes particular input of operation
Exceptions
OutOfRange In case the index is higher then number of operation inputs
Definition at line 513 of file ProgramOperation.cc.
{
    if (index < 1 || index > operation_->numberOfInputs()) {
        std::string msg = "InputNode index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    std::map<int, MoveNodeSet*>::const_iterator i = inputMoves_.find(index);
    if (i != inputMoves_.end()) {
        return *(i->second);
    } else {
        std::string msg = "InputNode index not found.";
        throw KeyNotFound(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, inputMoves_, Operation::numberOfInputs(), and operation_.
Referenced by MemoryAliasAnalyzer::addressOperandMove(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), BasicBlockScheduler::findTriggerFromUnit(), StackAliasAnalyzer::getStackOffset(), OffsetAliasAnalyzer::isAddressTraceable(), ExecutionPipelineResource::nodeOfInputPort(), BF2Scheduler::reservePreallocatedFUs(), scheduledFU(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), and LoopAnalyzer::tryTrackCommonAncestor().
isAnyInputAssigned()
bool ProgramOperation::isAnyInputAssigned ()
Return true if any node of this operation have function unit assigned to their source or destination respectively
Returns
True if any node has source or destination function unit assigned
Definition at line 419 of file ProgramOperation.cc.
{
    for (int i = 0; i < inputMoveCount(); i++ ) {
        if (inputMove(i).isAssigned()) {
            return true;
        }
    }
    return false;
}
References inputMove(), inputMoveCount(), and MoveNode::isAssigned().
isAnyNodeAssigned()
bool ProgramOperation::isAnyNodeAssigned ()
Return true if any node of this operation have function unit assigned to their source or destination respectively
Returns
True if any node has source or destination function unit assigned
Definition at line 398 of file ProgramOperation.cc.
{
    for (int i = 0; i < inputMoveCount(); i++ ) {
        if (inputMove(i).isAssigned()) {
            return true;
        }
    }
    for (int i = 0; i < outputMoveCount(); i++ ) {
        if (outputMove(i).isAssigned()) {
            return true;
        }
    }
    return false;
}
References inputMove(), inputMoveCount(), MoveNode::isAssigned(), outputMove(), and outputMoveCount().
Referenced by MachineConnectivityCheck::findPossibleDestinationPorts().
isAnyOutputAssigned()
bool ProgramOperation::isAnyOutputAssigned ()
Return true if any output node of this operation have function unit assigned to their source or destination respectively
Returns
True if any node has source or destination function unit assigned
Definition at line 451 of file ProgramOperation.cc.
{
    for (int i = 0; i < outputMoveCount(); i++ ) {
        if (outputMove(i).isAssigned()) {
            return true;
        }
    }
    return false;
}
References MoveNode::isAssigned(), outputMove(), and outputMoveCount().
Referenced by BUBasicBlockScheduler::scheduleMove().
isAssigned()
bool ProgramOperation::isAssigned ()
Return true if nodes of this operation have function unit assigned to their source or destination respectively
Returns
True if nodes have source or destination function unit assigned
Definition at line 377 of file ProgramOperation.cc.
{
    for (int i = 0; i < inputMoveCount(); i++ ) {
        if (!inputMove(i).isAssigned()) {
            return false;
        }
    }
    for (int i = 0; i < outputMoveCount(); i++ ) {
        if (!outputMove(i).isAssigned()) {
            return false;
        }
    }
    return true;
}
References inputMove(), inputMoveCount(), MoveNode::isAssigned(), outputMove(), and outputMoveCount().
isComplete()
bool ProgramOperation::isComplete ()
Return true if each input and each output of the operation has a corresponding node reference in this program operation
Returns
True if each input and output of operation has node reference
Definition at line 315 of file ProgramOperation.cc.
{
    if (!isReady()) {
        return false;
    }
    // numbering of output does not start from 1 but input count +1
    int begin = operation_->numberOfInputs() + 1;
    int end =  operation_->numberOfInputs() + operation_->numberOfOutputs();
    for (int i = begin; i <= end; i++) {
        if (!MapTools::containsKey(outputMoves_,i)) {
            return false;
        }
    }
    return true;
}
References MapTools::containsKey(), isReady(), Operation::numberOfInputs(), Operation::numberOfOutputs(), operation_, and outputMoves_.
isLegalFU()
bool ProgramOperation::isLegalFU (const TTAMachine::FunctionUnit & fu) const
Definition at line 915 of file ProgramOperation.cc.
{
    if (!fu.hasOperation(operation_->name())) {
        return false;
    }
    for (int i = 0; i < inputMoveCount(); i++) {
        MoveNode& mn = inputMove(i);
        TTAProgram::Move& move = mn.move();
        if (move.hasAnnotation(
                TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_DST,
                fu.name())) {
            return false;
        }
    }
    for (int i = 0; i < outputMoveCount(); i++) {
        MoveNode& mn = outputMove(i);
        TTAProgram::Move& move = mn.move();
        if (move.hasAnnotation(
                TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_SRC,
                fu.name())) {
            return false;
        }
    }
    return true;
}
References TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_DST, TTAProgram::ProgramAnnotation::ANN_REJECTED_UNIT_SRC, TTAProgram::AnnotatedInstructionElement::hasAnnotation(), TTAMachine::FunctionUnit::hasOperation(), inputMove(), inputMoveCount(), MoveNode::move(), TTAMachine::Component::name(), Operation::name(), operation_, outputMove(), and outputMoveCount().
Referenced by FUBroker::findFUOfPO(), and BFLateBypassGuard::operator()().
isMultinode()
bool ProgramOperation::isMultinode ()
Return true if this program operation has more then one reference for some input or output of the operation.
Returns
True if some of inputs or outputs has more then one reference
Definition at line 352 of file ProgramOperation.cc.
{
    std::map<int,MoveNodeSet*>::iterator moveIt = inputMoves_.begin();
    while (moveIt != inputMoves_.end()) {
        if ((*moveIt).second->count() > 1) {
            return true;
        }
        moveIt++;
    }
    moveIt = outputMoves_.begin();
    while (moveIt != outputMoves_.end()) {
        if ((*moveIt).second->count() > 1) {
            return true;
        }
        moveIt++;
    }
    return false;
}
References inputMoves_, and outputMoves_.
isReady()
bool ProgramOperation::isReady ()
Return true if each input node has corresponding node reference
Returns
True if each input of operation has corresponding node reference
Definition at line 336 of file ProgramOperation.cc.
{
    for (int i = 1; i <= operation_->numberOfInputs(); i++) {
        if (!MapTools::containsKey(inputMoves_,i)) {
            return false;
        }
    }
    return true;
}
References MapTools::containsKey(), inputMoves_, Operation::numberOfInputs(), and operation_.
Referenced by isComplete().
machineInstr()
const llvm::MachineInstr * ProgramOperation::machineInstr () const inline
Definition at line 136 of file ProgramOperation.hh.
{ return mInstr_; }
References mInstr_.
Referenced by LLVMAliasAnalyzer::analyze(), DataDependenceGraphBuilder::checkAndCreateMemDep(), and LLVMAliasAnalyzer::isAddressTraceable().
moveNode()
MoveNode & ProgramOperation::moveNode (const TTAProgram::Move & move) const
Definition at line 706 of file ProgramOperation.cc.
{
    for (std::size_t i = 0; i < allInputMoves_.size(); ++i) {
        MoveNode& moveNode = *allInputMoves_.at(i);
        if (&moveNode.move() == &move)
            return moveNode;
    }
    for (std::size_t i = 0; i < allOutputMoves_.size(); ++i) {
        MoveNode& moveNode = *allOutputMoves_.at(i);
        if (&moveNode.move() == &move)
            return moveNode;
    }
    throw KeyNotFound(__FILE__, __LINE__, __func__,
                      "No MoveNode for the Move found in the ProgramOperation.");
}
References __func__, allInputMoves_, allOutputMoves_, MoveNode::move(), and moveNode().
Referenced by hasMoveNodeForMove(), moveNode(), and triggeringMove().
opcodeSettingNode()
MoveNode & ProgramOperation::opcodeSettingNode ()
Return the MoveNode of program operation that sets the opcode and triggers operation execution.
Such a MoveNode is usually one of input nodes and can not have multiple copies.
Returns
MoveNode that sets opcode and triggers execution
Exceptions
InvalidData In case there is no opcode setting node register in operation
Definition at line 487 of file ProgramOperation.cc.
{
    std::map<int,MoveNodeSet*>::iterator moveIt = inputMoves_.begin();
    while (moveIt != inputMoves_.end()) {
        if ((*moveIt).second->at(0).move().destination().isOpcodeSetting()) {
            if ((*moveIt).second->count() > 1) {
                std::string msg = "ProgramOperation has more then one opcode\
                    setting node.";
                throw InvalidData(__FILE__, __LINE__, __func__, msg);
            }
            return (*moveIt).second->at(0);
        }
        moveIt++;
    }
    std::string msg = "ProgramOperation is missing opcode setting node.";
    throw InvalidData(__FILE__, __LINE__, __func__, msg);
}
References __func__, and inputMoves_.
Referenced by ResourceConstraintAnalyzer::analyzeMoveNode().
operation()
const Operation & ProgramOperation::operation () const
Return the operation from OSAL
Returns
Return the operation object handle from OSAL
Definition at line 590 of file ProgramOperation.cc.
{
    return *operation_;
}
References operation_.
Referenced by addNode(), MemoryAliasAnalyzer::addressOperandMove(), OutputFUBroker::allAvailableResources(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), OutputFUBroker::assign(), BusResource::canAssign(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), BFOptimization::canBeSpeculated(), PreOptimizer::checkGuardReversalAllowed(), CopyingDelaySlotFiller::collectMoves(), MemoryAliasAnalyzer::compareIndeces(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeDuplicator::duplicateMove(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), MoveNode::earliestResultReadCycle(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), BasicBlockScheduler::findTrigger(), BasicBlockScheduler::findTriggerFromUnit(), findTriggerFromUnit(), MemoryAliasAnalyzer::findTwoPartAddressOperands(), CopyingDelaySlotFiller::getMove(), PreOptimizer::handleCFGDDG(), hwopFromOutMove(), BFOptimization::immCountPreventsScheduling(), OffsetAliasAnalyzer::isAddressTraceable(), ExecutionPipelineBroker::isMoveTrigger(), BF2Scheduler::isTrigger(), DataDependenceGraphBuilder::isTriggering(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), MoveNode::latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), BF2Scheduler::mustBeTrigger(), ExecutionPipelineResource::nodeOfInputPort(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), BFLateBypassGuard::operator()(), BFRemoveLoopChecksAndJump::operator()(), BFShareOperands::operator()(), outputIndexFromGuard(), ExecutionPipelineResource::poConflictsWithInputPort(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), BF2Scheduler::reservePreallocatedFUs(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), ExecutionPipelineResource::resultReadyCycle(), BFOptimization::RFReadPortCountPreventsScheduling(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), ExecutionPipelineResource::setOperandsUsed(), ExecutionPipelineResource::setResultWriten(), switchInputs(), ExecutionPipelineResource::testTriggerResult(), ExecutionPipelineResource::triggerTooEarly(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveEq(), BasicBlockScheduler::tryToSwitchInputs(), BUBasicBlockScheduler::tryToSwitchInputs(), LoopAnalyzer::tryTrackCommonAncestor(), ExecutionPipelineResource::unsetOperandsUsed(), and ExecutionPipelineResource::unsetResultWriten().
operator=()
ProgramOperation & ProgramOperation::operator= (const ProgramOperation &) private
operator==()
bool ProgramOperation::operator== (const ProgramOperation & po) inline
Definition at line 147 of file ProgramOperation.hh.
{ return poId() == po.poId(); }
References poId().
outputIndexFromGuard() [1/2]
int ProgramOperation::outputIndexFromGuard (const TTAMachine::PortGuard & pg) const
Definition at line 266 of file ProgramOperation.cc.
{
    return outputIndexFromGuard(pg, operation());
}
References operation(), and outputIndexFromGuard().
Referenced by BFLateBypassGuard::operator()(), outputIndexFromGuard(), and outputIndexFromGuardOfMove().
outputIndexFromGuard() [2/2]
int ProgramOperation::outputIndexFromGuard (const TTAMachine::PortGuard & pg, const Operation & op) static
Definition at line 271 of file ProgramOperation.cc.
{
    const TTAMachine::Port* p = pg.port();
    const TTAMachine::FUPort* fup = static_cast<const TTAMachine::FUPort*>(p);
    const TTAMachine::Unit* u = p->parentUnit();
    const TTAMachine::FunctionUnit* fu =
        static_cast<const TTAMachine::FunctionUnit*>(u);
    const TTAMachine::HWOperation* hwop = fu->operation(op.name());
    return hwop->io(*fup);
}
References TTAMachine::HWOperation::io(), Operation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::Port::parentUnit(), and TTAMachine::PortGuard::port().
outputIndexFromGuardOfMove()
int ProgramOperation::outputIndexFromGuardOfMove (const MoveNode & node) const
Definition at line 256 of file ProgramOperation.cc.
{
    assert(!node.move().isUnconditional()); // todo: throw?
    const TTAMachine::Guard& guard = node.move().guard().guard();
    const TTAMachine::PortGuard* pg =
        dynamic_cast<const TTAMachine::PortGuard*>(&guard);
    assert(pg); // todo: throw?
    return outputIndexFromGuard(*pg);
}
References assert, TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), TTAProgram::Move::isUnconditional(), MoveNode::move(), and outputIndexFromGuard().
Referenced by addGuardOutputNode(), OutputFUBroker::allAvailableResources(), ExecutionPipelineResource::canAssignSource(), ExecutionPipelineBroker::latestFromDestination(), outputIndexOfMove(), removeGuardOutputNode(), and ExecutionPipelineResource::testTriggerResult().
outputIndexOfMove()
int ProgramOperation::outputIndexOfMove (const MoveNode & mn) const
Definition at line 886 of file ProgramOperation.cc.
{
    if (mn.isSourceOperation() &&
        &mn.sourceOperation() == this) {
        return mn.move().source().operationIndex();
    } else {
        return outputIndexFromGuardOfMove(mn);
    }
}
References MoveNode::isSourceOperation(), MoveNode::move(), TTAProgram::Terminal::operationIndex(), outputIndexFromGuardOfMove(), TTAProgram::Move::source(), and MoveNode::sourceOperation().
Referenced by OutputFUBroker::assign(), ExecutionPipelineBroker::earliestFromDestination(), MoveNode::earliestResultReadCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), BF2ScheduleFront::prefResultCycle(), and ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing().
outputMove()
MoveNode & ProgramOperation::outputMove (int index) const
Returns the given output move.
Parameters
index Index of the move.
Returns
The output move.
Definition at line 632 of file ProgramOperation.cc.
{
    return *allOutputMoves_.at(index);
}
References allOutputMoves_.
Referenced by RegisterCopyAdder::addCandidateSetAnnotations(), RegisterCopyAdder::addRegisterCopies(), annotateAllOutputs(), areOutputsAssigned(), BFEarlyBypasser::bypassSourceLatestCycle(), DataDependenceGraph::dotString(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromDestination(), BF2ScheduleFront::findInducingBypassSourceFromOperation(), MachineConnectivityCheck::findPossibleDestinationPorts(), RegisterCopyAdder::isAllowedUnit(), isAnyNodeAssigned(), isAnyOutputAssigned(), isAssigned(), isLegalFU(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), MoveNode::latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), CriticalPathBBMoveNodeSelector::mightBeReady(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), BFLateBypassGuard::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultsClose::operator()(), BF2ScheduleFront::prefResultCycle(), BUMoveNodeSelector::queueOperation(), scheduledFU(), BUBasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperation(), setOperation(), ExecutionPipelineResource::testTriggerResult(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToPrecalcConstantAdd(), PreOptimizer::tryToRemoveGuardInversingOp(), and ~ProgramOperation().
outputMoveCount()
int ProgramOperation::outputMoveCount () const
Count of output moves to this operation.
Returns
The count of output moves.
Definition at line 610 of file ProgramOperation.cc.
{
    return allOutputMoves_.size();
}
References allOutputMoves_.
Referenced by RegisterCopyAdder::addCandidateSetAnnotations(), RegisterCopyAdder::addRegisterCopies(), annotateAllOutputs(), areOutputsAssigned(), BFEarlyBypasser::bypassSourceLatestCycle(), DataDependenceGraph::dotString(), DataDependenceGraph::earliestCycle(), ExecutionPipelineBroker::earliestFromDestination(), BF2ScheduleFront::findInducingBypassSourceFromOperation(), MachineConnectivityCheck::findPossibleDestinationPorts(), RegisterCopyAdder::isAllowedUnit(), isAnyNodeAssigned(), isAnyOutputAssigned(), isAssigned(), isLegalFU(), ExecutionPipelineBroker::latestFromDestination(), ExecutionPipelineBroker::latestFromSource(), MoveNode::latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), CriticalPathBBMoveNodeSelector::mightBeReady(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), BFLateBypassGuard::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultsClose::operator()(), BF2ScheduleFront::prefResultCycle(), BUMoveNodeSelector::queueOperation(), scheduledFU(), BUBasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperation(), setOperation(), ExecutionPipelineResource::testTriggerResult(), CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp(), PreOptimizer::tryToOptimizeAddressReg(), PreOptimizer::tryToRemoveEq(), PreOptimizer::tryToRemoveXor(), and ~ProgramOperation().
outputNode()
MoveNodeSet & ProgramOperation::outputNode (int index) const
Return the nodes that writes output Index of operation
Parameters
index Index of a operation to test
Returns
Set of nodes that writes particular output of operation
Exceptions
OutOfRange If index is not found
Definition at line 535 of file ProgramOperation.cc.
{
    if (index <= operation_->numberOfInputs() ||
        index > operation_->numberOfInputs()+
        operation_->numberOfOutputs()) {
        std::string msg = "OutputNode index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    if (MapTools::containsKey(outputMoves_, index)) {
        MoveNodeSet* nodeSet =
                MapTools::valueForKey<MoveNodeSet*>(outputMoves_, index);
        return *nodeSet;
    } else {
        std::string msg = "OutputNode index not found.";
        throw KeyNotFound(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, MapTools::containsKey(), MapTools::keyForValue(), Operation::numberOfInputs(), Operation::numberOfOutputs(), operation_, and outputMoves_.
Referenced by ExecutionPipelineResource::canAssignSource(), fuFromOutMove(), hwopFromOutMove(), and scheduledFU().
poId()
unsigned int ProgramOperation::poId () const
Returns an unique id of this program operation.
These can be used instead of pointers for comparison, and are more deterministic as they are given in order.
Definition at line 765 of file ProgramOperation.cc.
{
    return poId_;
}
References poId_.
Referenced by StackAliasAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), DataDependenceGraph::dotString(), MoveNode::dotString(), OffsetAliasAnalyzer::isAddressTraceable(), StackAliasAnalyzer::isAddressTraceable(), ProgramOperation::Comparator::operator()(), operator==(), and toString().
removeGuardOutputNode()
void ProgramOperation::removeGuardOutputNode (MoveNode & node)
Removes output node from set of nodes that belong to this program operation.
Parameters
node MoveNode being removed from this program operation
Definition at line 249 of file ProgramOperation.cc.
{
    removeOutputNode(node, outputIndexFromGuardOfMove(node));
}
References outputIndexFromGuardOfMove(), and removeOutputNode().
Referenced by DataDependenceGraph::guardRestored(), and MoveNode::~MoveNode().
removeInputNode()
void ProgramOperation::removeInputNode (MoveNode & node)
Removes output node from set of nodes that belong to this program operation.
Parameters
node MoveNode being removed from this program operation
Definition at line 289 of file ProgramOperation.cc.
{
    int inputIndex = node.move().destination().operationIndex();
    if (MapTools::containsKey(inputMoves_,inputIndex)) {
        MoveNodeSet* nodeSet =
            MapTools::valueForKey<MoveNodeSet*>(inputMoves_,inputIndex);
        nodeSet->removeMoveNode(node);
        for (std::vector<MoveNode*>::iterator i = allInputMoves_.begin();
             i != allInputMoves_.end(); i++) {
            if (*i == &node) {
                allInputMoves_.erase(i);
                break;
            }
        }
    } else {
        throw IllegalRegistration(
            __FILE__,__LINE__,__func__,"MoveNode not part of PO");
    }
}
References __func__, allInputMoves_, MapTools::containsKey(), TTAProgram::Move::destination(), inputMoves_, MapTools::keyForValue(), MoveNode::move(), TTAProgram::Terminal::operationIndex(), and MoveNodeSet::removeMoveNode().
Referenced by DataDependenceGraph::removeNode(), and MoveNode::~MoveNode().
removeOutputNode() [1/2]
void ProgramOperation::removeOutputNode (MoveNode & node)
Removes output node from set of nodes that belong to this program operation.
Parameters
node MoveNode being removed from this program operation
Definition at line 238 of file ProgramOperation.cc.
{
    int outputIndex = node.move().source().operationIndex();
    removeOutputNode(node, outputIndex);
}
References MoveNode::move(), TTAProgram::Terminal::operationIndex(), removeOutputNode(), and TTAProgram::Move::source().
removeOutputNode() [2/2]
void ProgramOperation::removeOutputNode (MoveNode & node, int outputIndex)
Removes output node from set of nodes that belong to this program operation.
Parameters
node MoveNode being removed from this program operation
outputIndex the output index.
Definition at line 214 of file ProgramOperation.cc.
{
    if (MapTools::containsKey(outputMoves_,outputIndex)) {
        MoveNodeSet* nodeSet =
            MapTools::valueForKey<MoveNodeSet*>(outputMoves_,outputIndex);
        nodeSet->removeMoveNode(node);
        for (std::vector<MoveNode*>::iterator i = allOutputMoves_.begin();
             i != allOutputMoves_.end(); i++) {
            if (*i == &node) {
                allOutputMoves_.erase(i);
                break;
            }
        }
    } else {
        throw IllegalRegistration(
            __FILE__,__LINE__,__func__,"MoveNode not part of PO");
    }
}
References __func__, allOutputMoves_, MapTools::containsKey(), MapTools::keyForValue(), outputMoves_, and MoveNodeSet::removeMoveNode().
Referenced by removeGuardOutputNode(), DataDependenceGraph::removeNode(), removeOutputNode(), PreOptimizer::tryToPrecalcConstantAdd(), BFUpdateMoveOnBypass::undoOnlyMe(), DataDependenceGraph::unMergeUser(), and MoveNode::~MoveNode().
scheduledFU()
const TTAMachine::FunctionUnit * ProgramOperation::scheduledFU () const
Definition at line 866 of file ProgramOperation.cc.
{
    for (int i = 0; i < inputMoveCount(); i++ ) {
        MoveNode& inputNode = inputMove(i);
        if (inputNode.isAssigned()) {
            return static_cast<const TTAMachine::FunctionUnit*>(
                inputNode.move().destination().port().parentUnit());
        }
    }
    for (int i = 0; i < outputMoveCount(); i++ ) {
        MoveNode& outputNode = outputMove(i);
        const TTAMachine::FunctionUnit* fu = fuFromOutMove(outputNode);
        if (fu != nullptr) {
            return fu;
        }
    }
    return nullptr;
}
References fuFromOutMove(), inputMove(), inputMoveCount(), inputNode(), outputMove(), outputMoveCount(), and outputNode().
Referenced by MachineConnectivityCheck::busConnectedToAnyFU(), FUBroker::findFUOfPO(), and BFShareOperands::operator()().
setOperation()
void ProgramOperation::setOperation (const Operation & op)
Definition at line 941 of file ProgramOperation.cc.
{
    operation_ = &op;
    for (int i = 0; i < inputMoveCount(); i++) {
        MoveNode& mn = inputMove(i);
        TTAProgram::TerminalFUPort* tfp = dynamic_cast<TTAProgram::TerminalFUPort*>(
            &mn.move().destination());
        assert(tfp);
        tfp->setHintOperation(op.name().c_str());
    }
    for (int i = 0; i < outputMoveCount(); i++) {
        MoveNode& mn = outputMove(i);
        TTAProgram::TerminalFUPort* tfp = dynamic_cast<TTAProgram::TerminalFUPort*>(
            &mn.move().source());
        assert(tfp);
        tfp->setHintOperation(op.name().c_str());
    }
}
References assert, TTAProgram::Move::destination(), inputMove(), inputMoveCount(), MoveNode::move(), Operation::name(), operation_, outputMove(), outputMoveCount(), TTAProgram::TerminalFUPort::setHintOperation(), and TTAProgram::Move::source().
Referenced by Peel2BBLoops::appendBB().
switchInputs()
void ProgramOperation::switchInputs (int idx1 = 1, int idx2 = 2)
Switches inputs of 2-operand commutative operations
Definition at line 795 of file ProgramOperation.cc.
{
    const Operation& op = operation();
    assert (op.numberOfInputs() >= 2);
    // switch input nodes.
    MoveNodeSet tmpSet = *inputMoves_[idx1];
    *inputMoves_[idx1] = *inputMoves_[idx2];
    *inputMoves_[idx2] = tmpSet;
    for (int i = 0; i < inputMoveCount(); i++) {
        MoveNode& node = inputMove(i);
        TTAProgram::Move& move = node.move();
        TTAProgram::Terminal& oldDest = move.destination();
        // then update the moves.
        if (move.destination().operationIndex() == idx1) {
            move.setDestination(
                new TTAProgram::TerminalFUPort(
                    *static_cast<TTAProgram::TerminalFUPort&>(oldDest).
                    hwOperation(), idx2));
        } else if (move.destination().operationIndex() == idx2) {
            move.setDestination(
                new TTAProgram::TerminalFUPort(
                    *static_cast<TTAProgram::TerminalFUPort&>(oldDest).
                    hwOperation(), idx1));
        }
    }
}
References assert, TTAProgram::Move::destination(), inputMove(), inputMoveCount(), inputMoves_, MoveNode::move(), Operation::numberOfInputs(), operation(), TTAProgram::Terminal::operationIndex(), and TTAProgram::Move::setDestination().
Referenced by PreOptimizer::inverseGuardsOfHeads(), BasicBlockScheduler::tryToSwitchInputs(), and BUBasicBlockScheduler::tryToSwitchInputs().
toString()
std::string ProgramOperation::toString () const
The moves of the program operation in human readable format.
Returns
The program operation as a string.
Definition at line 746 of file ProgramOperation.cc.
{
    TCEString output = Conversion::toString(poId());
    output << " Inputs: ";
    for (std::size_t i = 0; i < allInputMoves_.size(); ++i) {
        output += allInputMoves_.at(i)->toString() + " ";
    }
    output << " Outputs: ";
    for (std::size_t i = 0; i < allOutputMoves_.size(); ++i) {
        output += allOutputMoves_.at(i)->toString() + " ";
    }
    return output;
}
References allInputMoves_, allOutputMoves_, poId(), and Conversion::toString().
Referenced by RegisterCopyAdder::addMinimumRegisterCopies(), BF2Scheduler::allocateFunctionUnits(), LoopAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeMoveNode(), BFOptimization::assign(), BFOptimization::assignCopyToPrologEpilog(), ExecutionPipelineResource::assignDestination(), MoveNodeGroupBuilder::build(), BFOptimization::canAssign(), ExecutionPipelineResource::canAssignDestination(), DataDependenceGraphBuilder::checkAndCreateMemDep(), ExecutionPipelineResource::checkOperandAllowed(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandsOverwritten(), BFLateBypassGuard::operator()(), BF2Scheduler::preAllocateFunctionUnits(), ExecutionPipelineResource::resultAllowedAtCycle(), ExecutionPipelineResource::resultReadyCycle(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), BFShareOperandLate::revert(), ExecutionPipelineResource::triggerTooEarly(), BFLateBypass::undoOnlyMe(), BFUnscheduleFromBody::unscheduleOriginal(), and BFUnscheduleMove::unscheduleOriginal().
triggeringMove()
MoveNode * ProgramOperation::triggeringMove () const
Returns the triggering move of the operation.
Returns
The triggering move. NULL in case the operation is not yet assigned to an FU, or the triggering move has not been assigned yet.
Definition at line 643 of file ProgramOperation.cc.
{
    for (std::size_t i = 0; i < allInputMoves_.size(); ++i) {
        MoveNode& moveNode = *allInputMoves_.at(i);
        const TTAProgram::Move& move = moveNode.move();
        TTAProgram::Terminal& dest = move.destination();
        if (!dest.isFUPort()) {
            continue;
        }
        const TTAMachine::BaseFUPort* fup =
            static_cast<const TTAMachine::BaseFUPort*>(&dest.port());
        if (dynamic_cast<const UniversalFUPort*>(fup)) {
            continue;
        }
        if (fup->isTriggering()) {
            return &moveNode;
        } else {
            return findTriggerFromUnit(
                *fup->parentUnit());
        }
    }
    for (std::size_t i = 0; i< allOutputMoves_.size(); ++i) {
        MoveNode& moveNode = *allOutputMoves_.at(i);
        const TTAMachine::FunctionUnit* fu = fuFromOutMove(moveNode);
        if (fu != nullptr) {
            return findTriggerFromUnit(*fu);
        }
    }
    return NULL;
}
References allInputMoves_, allOutputMoves_, TTAProgram::Move::destination(), findTriggerFromUnit(), fuFromOutMove(), TTAProgram::Terminal::isFUPort(), TTAMachine::BaseFUPort::isTriggering(), MoveNode::move(), moveNode(), TTAMachine::BaseFUPort::parentUnit(), and TTAProgram::Terminal::port().
Referenced by CopyingDelaySlotFiller::allowedToSpeculate(), ResourceConstraintAnalyzer::analyzeMoveNode(), ExecutionPipelineResource::canAssignSource(), DataDependenceGraph::earliestCycle(), MoveNode::earliestResultReadCycle(), BasicBlockScheduler::findTrigger(), ExecutionPipelineResource::hasConflictingResultsOnCycle(), ExecutionPipelineResource::nextResultCycle(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), BFPushMoveUp2::operator()(), BFShareOperandLate::operator()(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), and ExecutionPipelineResource::resultReadyCycle().
Member Data Documentation
allInputMoves_
MoveVector ProgramOperation::allInputMoves_ private
Definition at line 170 of file ProgramOperation.hh.
Referenced by addInputNode(), hasConstantOperand(), hasMoveNodeForMove(), inputMove(), inputMoveCount(), moveNode(), removeInputNode(), toString(), and triggeringMove().
allOutputMoves_
MoveVector ProgramOperation::allOutputMoves_ private
Definition at line 172 of file ProgramOperation.hh.
Referenced by addOutputNode(), hasMoveNodeForMove(), moveNode(), outputMove(), outputMoveCount(), removeOutputNode(), toString(), and triggeringMove().
idCounter
unsigned int ProgramOperation::idCounter = 0 static private
Definition at line 174 of file ProgramOperation.hh.
inputMoves_
std::map<int,MoveNodeSet*> ProgramOperation::inputMoves_ private
Definition at line 166 of file ProgramOperation.hh.
Referenced by addInputNode(), findTriggerFromUnit(), hasInputNode(), inputNode(), isMultinode(), isReady(), opcodeSettingNode(), ProgramOperation(), removeInputNode(), switchInputs(), and ~ProgramOperation().
mInstr_
const llvm::MachineInstr* ProgramOperation::mInstr_ private
Definition at line 176 of file ProgramOperation.hh.
Referenced by machineInstr().
operation_
const Operation* ProgramOperation::operation_ private
Definition at line 164 of file ProgramOperation.hh.
Referenced by inputNode(), isComplete(), isLegalFU(), isReady(), operation(), outputNode(), and setOperation().
outputMoves_
std::map<int,MoveNodeSet*> ProgramOperation::outputMoves_ private
Definition at line 168 of file ProgramOperation.hh.
Referenced by addOutputNode(), hasOutputNode(), isComplete(), isMultinode(), outputNode(), ProgramOperation(), removeOutputNode(), and ~ProgramOperation().
poId_
unsigned int ProgramOperation::poId_ private
Definition at line 173 of file ProgramOperation.hh.
Referenced by poId().
The documentation for this class was generated from the following files:
ProgramOperation.hh
ProgramOperation.cc