OpenASIP: AddBridgeCmd Class Reference
AddBridgeCmd Class Reference
#include <AddBridgeCmd.hh>
Public Member Functions
AddBridgeCmd ()
virtual ~AddBridgeCmd ()
virtual bool Do ()
virtual int id () const
virtual AddBridgeCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new bridges to the Machine.
Displays a bridge dialog and creates a new bridge according to the dialog output.
Definition at line 43 of file AddBridgeCmd.hh.
Constructor & Destructor Documentation
AddBridgeCmd()
AddBridgeCmd::AddBridgeCmd ()
The Constructor.
Definition at line 61 of file AddBridgeCmd.cc.
                           :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_BRIDGE) {
}
Referenced by create().
~AddBridgeCmd()
AddBridgeCmd::~AddBridgeCmd () virtual
The Destructor.
Definition at line 69 of file AddBridgeCmd.cc.
{
}
Member Function Documentation
create()
AddBridgeCmd * AddBridgeCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 166 of file AddBridgeCmd.cc.
{
    return new AddBridgeCmd();
}
References AddBridgeCmd().
Do()
bool AddBridgeCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 79 of file AddBridgeCmd.cc.
                 {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model =
        dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel();
    Machine* machine = model->getMachine();
    Machine::BusNavigator navigator = machine->busNavigator();
    Bus* source = NULL;
    Bus* destination = NULL;
    MachineTester tester(*machine);
    // Check that two buses in the machine can be bridged.
    int i = 0;
    while (i < navigator.count() && source == NULL) {
    for (int j = 0; j < navigator.count(); j++) {
        if (tester.canBridge(*navigator.item(i), *navigator.item(j))) {
                source = navigator.item(i);
                destination = navigator.item(j);
                break;
            }
        }
        i++;
    }
    if (source == NULL) {
        // It's not possible to create a legal bridge to the machine,
        // display an error message.
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        boost::format message =
            generator->text(ProDeTextGenerator::MSG_ERROR_CANNOT_BRIDGE);
        InformationDialog info(parentWindow(),
                               WxConversion::toWxString(message.str()));
        info.ShowModal();
        return false;
    }
    // Generate name for the new FU.
    Machine::BridgeNavigator bridgeNavigator =
        model->getMachine()->bridgeNavigator();
    int suffix = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_BRIDGE +
        Conversion::toString(suffix);
    while (bridgeNavigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_BRIDGE +
            Conversion::toString(suffix);
        suffix++;
    }
    // Create and show bridge dialog.
    model->pushToStack();
    Bridge* bridge = new Bridge(newName, *source, *destination);
    BridgeDialog dialog(parentWindow(), bridge, NULL);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    } else {
    // bridge creation was cancelled
    model->popFromStack();
    }
    return false;
}
References assert, TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::busNavigator(), MachineTester::canBridge(), ProDeConstants::COMP_NEW_NAME_PREFIX_BRIDGE, TTAMachine::Machine::Navigator< ComponentType >::count(), Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), ProDeTextGenerator::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, ProDeTextGenerator::MSG_ERROR_CANNOT_BRIDGE, Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), Texts::TextGenerator::text(), Conversion::toString(), WxConversion::toWxString(), and EditorCommand::view().
id()
int AddBridgeCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 155 of file AddBridgeCmd.cc.
                       {
    return ProDeConstants::COMMAND_ADD_BRIDGE;
}
References ProDeConstants::COMMAND_ADD_BRIDGE.
isEnabled()
bool AddBridgeCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 191 of file AddBridgeCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddBridgeCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 178 of file AddBridgeCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_BRIDGE;
}
References ProDeConstants::CMD_SNAME_ADD_BRIDGE.
The documentation for this class was generated from the following files:
AddBridgeCmd.hh
AddBridgeCmd.cc