OpenASIP: ResourceVectorFUResourceConflictDetector Class Reference
ResourceVectorFUResourceConflictDetector Class Reference
#include <ResourceVectorFUResourceConflictDetector.hh>
Public Member Functions
ResourceVectorFUResourceConflictDetector (const TTAMachine::FunctionUnit &fu)
virtual ~ResourceVectorFUResourceConflictDetector ()
virtual bool issueOperation (OperationID id)
virtual bool advanceCycle ()
virtual void reset ()
virtual OperationID operationID (const TCEString &operationName) const
Public Member Functions inherited from FUResourceConflictDetector
FUResourceConflictDetector ()
virtual ~FUResourceConflictDetector ()
virtual void endClock ()
virtual void advanceClock ()
virtual bool isIdle ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Private Attributes
TTAMachine::ResourceVectorSet vectors_
The resource vectors of operations.
TTAMachine::ResourceVector compositeVector_
The composite resource vector.
Additional Inherited Members
Public Types inherited from FUResourceConflictDetector
typedef int OperationID
Type for identifying operations in the conflict detector interface.
Protected Attributes inherited from FUResourceConflictDetector
OperationIDIndex * operationIndices_
Map for finding indices for operations quickly.
Detailed Description
An FSA implementation of a FU resource conflict detector.
Definition at line 54 of file ResourceVectorFUResourceConflictDetector.hh.
Constructor & Destructor Documentation
ResourceVectorFUResourceConflictDetector()
ResourceVectorFUResourceConflictDetector::ResourceVectorFUResourceConflictDetector (const TTAMachine::FunctionUnit & fu)
Constructor.
Parameters
fu The function unit to detect conflicts for.
Exceptions
InvalidData If the model could not be built from the given FU.
Definition at line 46 of file ResourceVectorFUResourceConflictDetector.cc.
    : vectors_(fu) {}
~ResourceVectorFUResourceConflictDetector()
ResourceVectorFUResourceConflictDetector::~ResourceVectorFUResourceConflictDetector () virtual
Destructor.
Definition at line 53 of file ResourceVectorFUResourceConflictDetector.cc.
{
}
Member Function Documentation
advanceCycle()
bool ResourceVectorFUResourceConflictDetector::advanceCycle () virtual
Simulates a cycle advance and reports a conflict if detected.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 80 of file ResourceVectorFUResourceConflictDetector.cc.
{
    compositeVector_.shiftLeft();
    return true;
}
References compositeVector_, and TTAMachine::ResourceVector::shiftLeft().
issueOperation()
bool ResourceVectorFUResourceConflictDetector::issueOperation (OperationID id) virtual
Issues an operation and reports a conflict if detected.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 64 of file ResourceVectorFUResourceConflictDetector.cc.
{
    const TTAMachine::ResourceVector& operationVector =
        vectors_.resourceVector(id);
    if (compositeVector_.conflictsWith(operationVector, 1))
        return false;
    compositeVector_.mergeWith(operationVector, 1);
    return true;
}
References compositeVector_, TTAMachine::ResourceVector::conflictsWith(), TTAMachine::ResourceVector::mergeWith(), TTAMachine::ResourceVectorSet::resourceVector(), and vectors_.
operationID()
ResourceVectorFUResourceConflictDetector::OperationID ResourceVectorFUResourceConflictDetector::operationID (const TCEString & operationName) const virtual
Returns an operation id for the given operation.
Operation IDs are used in the interface for optimizing the access. This method converts OSAL Operations to operation IDs.
Parameters
operation The OSAL Operation to find ID for.
Returns
The operation ID.
Reimplemented from FUResourceConflictDetector.
Definition at line 96 of file ResourceVectorFUResourceConflictDetector.cc.
{
    return vectors_.operationIndex(StringTools::stringToUpper(operationName));
}
References TTAMachine::ResourceVectorSet::operationIndex(), StringTools::stringToUpper(), and vectors_.
reset()
void ResourceVectorFUResourceConflictDetector::reset () virtual
Sets the state of the detector to its initial state.
This means that the FU state is assumed to be what it is in powerup.
Reimplemented from FUResourceConflictDetector.
Definition at line 108 of file ResourceVectorFUResourceConflictDetector.cc.
{
    compositeVector_.clear();
}
References TTAMachine::ResourceVector::clear(), and compositeVector_.
Member Data Documentation
compositeVector_
TTAMachine::ResourceVector ResourceVectorFUResourceConflictDetector::compositeVector_ private
The composite resource vector.
Definition at line 73 of file ResourceVectorFUResourceConflictDetector.hh.
Referenced by advanceCycle(), issueOperation(), and reset().
vectors_
TTAMachine::ResourceVectorSet ResourceVectorFUResourceConflictDetector::vectors_ private
The resource vectors of operations.
Definition at line 71 of file ResourceVectorFUResourceConflictDetector.hh.
Referenced by issueOperation(), and operationID().
The documentation for this class was generated from the following files:
ResourceVectorFUResourceConflictDetector.hh
ResourceVectorFUResourceConflictDetector.cc