OpenASIP: DestinationField Class Reference
DestinationField Class Reference
#include <DestinationField.hh>
Public Member Functions
DestinationField (BinaryEncoding::Position socketIDPos, MoveSlot &parent)
DestinationField (const ObjectState *state, MoveSlot &parent)
virtual ~DestinationField ()
virtual ObjectState * saveState () const
Public Member Functions inherited from SlotField
virtual ~SlotField ()
MoveSlot * parent () const
void addSocketEncoding (SocketEncoding &encoding)
void removeSocketEncoding (SocketEncoding &encoding)
int socketEncodingCount () const
SocketEncoding & socketEncoding (int index) const
bool hasSocketEncoding (const std::string &socket) const
SocketEncoding & socketEncoding (const std::string &socket) const
void setNoOperationEncoding (NOPEncoding &encoding)
void unsetNoOperationEncoding ()
bool hasNoOperationEncoding () const
NOPEncoding & noOperationEncoding () const
BinaryEncoding::Position componentIDPosition () const
virtual int width () const
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_DESTINATION_FIELD = "dest_field"
ObjectState name for destination field.
Static Public Attributes inherited from SlotField
static const std::string OSNAME_SLOT_FIELD = "slot_field"
ObjectState name for slot field.
static const std::string OSKEY_COMPONENT_ID_POSITION = "comp_id_pos"
ObjectState attribute key for component ID position.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Additional Inherited Members
Protected Member Functions inherited from SlotField
SlotField (BinaryEncoding::Position componentIDPos, MoveSlot &parent)
SlotField (const ObjectState *state, MoveSlot &parent)
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
The DestinationField class represents the destination field of a move slot.
The destination field contains only socket encodings and so it is just a realization of SlotField class. It does not provide any additional methods.
Definition at line 44 of file DestinationField.hh.
Constructor & Destructor Documentation
DestinationField() [1/2]
DestinationField::DestinationField (BinaryEncoding::Position socketIDPos, MoveSlot & parent)
The constructor.
Registers the destination field to the given move slot automatically.
Parameters
socketIDPos Position of the socket ID within the destination field.
parent The parent move slot.
Exceptions
ObjectAlreadyExists If the parent move slot already has a destination field.
IllegalParameters If the given socket ID position is not the same with other destination fields.
Definition at line 56 of file DestinationField.cc.
    : SlotField(socketIDPos, parent) {
    BinaryEncoding* bem = parent.parent();
    for (int i = 0; i < bem->moveSlotCount(); i++) {
    MoveSlot& slot = bem->moveSlot(i);
    if (slot.hasDestinationField() &&
        slot.destinationField().componentIDPosition() != socketIDPos) {
        const string procName = "SourceField::SourceField";
        throw IllegalParameters(__FILE__, __LINE__, procName);
    } else {
        break;
    }
    }
    setParent(NULL);
    parent.setDestinationField(*this);
    setParent(&parent);
}
References SlotField::componentIDPosition(), MoveSlot::destinationField(), MoveSlot::hasDestinationField(), BinaryEncoding::moveSlot(), BinaryEncoding::moveSlotCount(), MoveSlot::parent(), SlotField::parent(), MoveSlot::setDestinationField(), and InstructionField::setParent().
DestinationField() [2/2]
DestinationField::DestinationField (const ObjectState * state, MoveSlot & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent move slot.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the parent move slot already has a destination field.
Definition at line 88 of file DestinationField.cc.
    : SlotField(state, parent) {
    if (state->name() != OSNAME_DESTINATION_FIELD) {
    const string procName = "DestinationField::DestinationField";
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    setParent(NULL);
    parent.setDestinationField(*this);
    setParent(&parent);
}
References ObjectState::name(), OSNAME_DESTINATION_FIELD, SlotField::parent(), MoveSlot::setDestinationField(), and InstructionField::setParent().
~DestinationField()
DestinationField::~DestinationField () virtual
The destructor.
Definition at line 103 of file DestinationField.cc.
{
    MoveSlot* parent = this->parent();
    assert(parent != NULL);
    setParent(NULL);
    parent->unsetDestinationField();
}
References assert, SlotField::parent(), InstructionField::setParent(), and MoveSlot::unsetDestinationField().
Member Function Documentation
saveState()
ObjectState * DestinationField::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from SlotField.
Definition at line 117 of file DestinationField.cc.
{
    ObjectState* state = SlotField::saveState();
    state->setName(OSNAME_DESTINATION_FIELD);
    return state;
}
References OSNAME_DESTINATION_FIELD, SlotField::saveState(), and ObjectState::setName().
Member Data Documentation
OSNAME_DESTINATION_FIELD
const std::string DestinationField::OSNAME_DESTINATION_FIELD = "dest_field" static
ObjectState name for destination field.
Definition at line 54 of file DestinationField.hh.
Referenced by DestinationField(), BEMSerializer::destinationFieldToOM(), MoveSlot::loadState(), BEMSerializer::moveSlotToFile(), and saveState().
The documentation for this class was generated from the following files:
DestinationField.hh
DestinationField.cc