OpenASIP: IUFactory Class Reference
IUFactory Class Reference
#include <IUFactory.hh>
Public Member Functions
IUFactory (EditPolicyFactory &editPolicyFactory)
virtual ~IUFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
IUFactory & operator= (IUFactory &old)
Assignment not allowed.
IUFactory (IUFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating immediate unit EditParts corresponding to a given Machine ImmediateUnit object.
Definition at line 45 of file IUFactory.hh.
Constructor & Destructor Documentation
IUFactory() [1/2]
IUFactory::IUFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 52 of file IUFactory.cc.
                                                        :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new UnitPortFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~IUFactory()
IUFactory::~IUFactory () virtual
The Destructor.
Definition at line 61 of file IUFactory.cc.
                      {
}
IUFactory() [2/2]
IUFactory::IUFactory (IUFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * IUFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a immediate unit.
Parameters
component Immediate unit of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the ImmediateUnit class.
Implements Factory.
Definition at line 72 of file IUFactory.cc.
{
    ImmediateUnit* imm = dynamic_cast<ImmediateUnit*>(component);
    if (imm != NULL) {
    EditPart* immEditPart = new EditPart();
    immEditPart->setModel(imm);
    UnitFigure* fig = new UnitFigure();
    wxString name = WxConversion::toWxString(imm->name());
    name.Prepend(_T("IMM: "));
    fig->setName(name);
    immEditPart->setFigure(fig);
    for (int i = 0; i < imm->portCount(); i++) {
        vector<Factory*>::const_iterator iter;
        for (iter = factories_.begin(); iter != factories_.end(); iter++) {
        EditPart* portEditPart =
            (*iter)->createEditPart(imm->port(i));
        if (portEditPart != NULL) {
            EditPolicy* editPolicy =
            editPolicyFactory_.createIUPortEditPolicy();
            if (editPolicy != NULL) {
            portEditPart->installEditPolicy(editPolicy);
            }
            immEditPart->addChild(portEditPart);
        }
        }
    }
        wxString info = WxConversion::toWxString(imm->numberOfRegisters());
        info.Append(_T("x"));
        info.Append(WxConversion::toWxString(imm->width()));
        fig->setInfo(info);
    immEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createIUEditPolicy();
    if (editPolicy != NULL) {
        immEditPart->installEditPolicy(editPolicy);
    }
    return immEditPart;
    } else {
    return NULL;
    }
}
References EditPart::addChild(), EditPolicyFactory::createIUEditPolicy(), EditPolicyFactory::createIUPortEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), EditPart::setFigure(), UnitFigure::setInfo(), EditPart::setModel(), UnitFigure::setName(), EditPart::setSelectable(), WxConversion::toWxString(), and TTAMachine::BaseRegisterFile::width().
operator=()
IUFactory & IUFactory::operator= (IUFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
IUFactory.hh
IUFactory.cc