OpenASIP: RedoCmd Class Reference
RedoCmd Class Reference
#include <RedoCmd.hh>
Public Member Functions
RedoCmd ()
virtual ~RedoCmd ()
virtual bool Do ()
virtual int id () const
virtual RedoCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for redoing undone modifications to the machine.
Definition at line 41 of file RedoCmd.hh.
Constructor & Destructor Documentation
RedoCmd()
RedoCmd::RedoCmd ()
The Constructor.
Definition at line 44 of file RedoCmd.cc.
                :
    EditorCommand(ProDeConstants::CMD_NAME_REDO) {
}
Referenced by create().
~RedoCmd()
RedoCmd::~RedoCmd () virtual
The Destructor.
Definition at line 53 of file RedoCmd.cc.
{}
Member Function Documentation
create()
RedoCmd * RedoCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 85 of file RedoCmd.cc.
                      {
    return new RedoCmd();
}
References RedoCmd().
Do()
bool RedoCmd::Do () virtual
Executes the command.
Returns
Always false.
Implements GUICommand.
Definition at line 62 of file RedoCmd.cc.
            {
    dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel()->redo();
    return false;
}
References EditorCommand::view().
icon()
string RedoCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 97 of file RedoCmd.cc.
                    {
    return ProDeConstants::CMD_ICON_REDO;
}
References ProDeConstants::CMD_ICON_REDO.
id()
int RedoCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 74 of file RedoCmd.cc.
                  {
    return ProDeConstants::COMMAND_REDO;
}
References ProDeConstants::COMMAND_REDO.
isEnabled()
bool RedoCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when the model has an undone modification cached.
Returns
True, if the model's redo cache is not empty.
Reimplemented from EditorCommand.
Definition at line 111 of file RedoCmd.cc.
                   {
    wxDocManager* manager = wxGetApp().docManager();
    wxView* view = manager->GetCurrentView();
    if (view == NULL) {
        return false;
    }
    Model* model =
        dynamic_cast<MDFDocument*>(view->GetDocument())->getModel();
    if (model != NULL && model->canRedo()) {
    return true;
    }
    return false;
}
References Model::canRedo(), and EditorCommand::view().
The documentation for this class was generated from the following files:
RedoCmd.hh
RedoCmd.cc