OpenASIP: ConfCommand Class Reference
ConfCommand Class Reference
#include <ConfCommand.hh>
Public Member Functions
ConfCommand ()
virtual ~ConfCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Implementation of the "conf" command of the Simulator Control Language.
Definition at line 46 of file ConfCommand.hh.
Constructor & Destructor Documentation
ConfCommand()
ConfCommand::ConfCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 47 of file ConfCommand.cc.
: CustomCommand("conf") {}
~ConfCommand()
ConfCommand::~ConfCommand () virtual
Destructor.
Does nothing.
Definition at line 54 of file ConfCommand.cc.
{}
Member Function Documentation
execute()
bool ConfCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "conf" command.
Loads a new machine file using the ProcessorConfigurationFile and SimulatorFrontend.
Parameters
arguments Processor configuration file name is given as argument to the command.
Returns
True if loading the program was successful.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 69 of file ConfCommand.cc.
{
    assert(interpreter() != NULL);
    SimulatorTextGenerator& textGen = SimulatorToolbox::textGenerator();
    if (arguments.size() < 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_NO_FILENAME_DEFINED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    if (arguments.size() > 2) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(
            textGen.text(Texts::TXT_ONLY_ONE_FILENAME_EXPECTED).str());
        interpreter()->setResult(errorMessage);
        return false;
    }
    SimulatorInterpreterContext& interpreterContext =
        dynamic_cast<SimulatorInterpreterContext&>(interpreter()->context());
    SimulatorFrontend& simulatorFrontend =
        interpreterContext.simulatorFrontend();
    try {
        const std::string fileName =
            FileSystem::expandTilde(arguments.at(1).stringValue());
        simulatorFrontend.loadProcessorConfiguration(fileName);
    } catch (const Exception& e) {
        DataObject* errorMessage = new DataObject();
        errorMessage->setString(e.errorMessageStack(true));
        interpreter()->setResult(errorMessage);
        return false;
    }
    catch (...) {
        assert(false);
        return false;
    }
    return true;
}
References assert, ScriptInterpreter::context(), Exception::errorMessageStack(), FileSystem::expandTilde(), CustomCommand::interpreter(), SimulatorFrontend::loadProcessorConfiguration(), ScriptInterpreter::setResult(), DataObject::setString(), SimulatorInterpreterContext::simulatorFrontend(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_NO_FILENAME_DEFINED, and Texts::TXT_ONLY_ONE_FILENAME_EXPECTED.
helpText()
std::string ConfCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 121 of file ConfCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_CONF).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_CONF.
The documentation for this class was generated from the following files:
ConfCommand.hh
ConfCommand.cc