OpenASIP: ModelsimSimulator Class Reference
ModelsimSimulator Class Reference
#include <ModelsimSimulator.hh>
Public Member Functions
ModelsimSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
virtual ~ModelsimSimulator ()
virtual bool compile (std::vector< std::string > &errors)
virtual bool simulate (std::vector< std::string > &errors)
Public Member Functions inherited from ImplementationSimulator
ImplementationSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
virtual ~ImplementationSimulator ()
Protected Member Functions
virtual std::string createWorkDir ()
Protected Member Functions inherited from ImplementationSimulator
void setWorkDir (std::string dir)
std::string workDir () const
std::string tbDirectory () const
std::string tbFile () const
int hdlFileCount () const
std::string file (int index) const
bool verbose ()
void parseErrorMessages (std::vector< std::string > &inputMsg, std::vector< std::string > &errors)
Private Member Functions
bool mapWorkDir (std::string file, std::vector< std::string > &errors)
bool compileOneFile (std::string file, std::vector< std::string > &errors)
Detailed Description
Definition at line 40 of file ModelsimSimulator.hh.
Constructor & Destructor Documentation
ModelsimSimulator()
ModelsimSimulator::ModelsimSimulator (std::string tbFile, std::vector< std::string > hdlFiles, bool verbose, bool leaveDirty)
Definition at line 45 of file ModelsimSimulator.cc.
                    :
    ImplementationSimulator(tbFile, hdlFiles, verbose, leaveDirty) {
}
~ModelsimSimulator()
ModelsimSimulator::~ModelsimSimulator () virtual
Definition at line 53 of file ModelsimSimulator.cc.
{
}
Member Function Documentation
compile()
bool ModelsimSimulator::compile (std::vector< std::string > & errors) virtual
Implements ImplementationSimulator.
Definition at line 56 of file ModelsimSimulator.cc.
{
    string workDir = createWorkDir();
    if (workDir.empty()) {
        errors.push_back("Couldn't create work dir. Are the modelsim "
                         "executables in PATH?");
        return false;
    }
    string baseDir = tbDirectory();
    if (!FileSystem::changeWorkingDir(baseDir)) {
        errors.push_back("Couldn't change directory to " + baseDir);
        return false;
    }
    for (int i = 0; i < hdlFileCount(); i++) {
        if (!compileOneFile(file(i), errors)) {
            return false;
        } else {
            errors.clear();
        }
    }
    if (!compileOneFile(tbFile(), errors)) {
        return false;
    }
    errors.clear();
    return true;
}
References FileSystem::changeWorkingDir(), compileOneFile(), createWorkDir(), ImplementationSimulator::file(), ImplementationSimulator::hdlFileCount(), ImplementationSimulator::tbDirectory(), ImplementationSimulator::tbFile(), and ImplementationSimulator::workDir().
compileOneFile()
bool ModelsimSimulator::compileOneFile (std::string file, std::vector< std::string > & errors) private
Definition at line 132 of file ModelsimSimulator.cc.
{
    string command = "vcom " + file + " 2>&1";
    if (verbose()) {
        std::cout << command << std::endl;
    }
    int rv = Application::runShellCommandAndGetOutput(command, errors);
    return rv == 0;
}
References ImplementationSimulator::file(), Application::runShellCommandAndGetOutput(), and ImplementationSimulator::verbose().
Referenced by compile().
createWorkDir()
std::string ModelsimSimulator::createWorkDir () protected virtual
Reimplemented from ImplementationSimulator.
Definition at line 98 of file ModelsimSimulator.cc.
{
    string work = tbDirectory() + FileSystem::DIRECTORY_SEPARATOR + "work";
    string createLib = "vlib " + work + " 2>&1";
    if (verbose()) {
        std::cout << createLib << std::endl;
    }
    vector<string> messages;
    int rv = Application::runShellCommandAndGetOutput(createLib, messages);
    if (rv != 0) {
        if (verbose()) {
            for (unsigned int i = 0; i < messages.size(); i++) {
                std::cout << messages.at(i) << std::endl;
            }
        }
        string failed = "";
        return failed;
    }
    string mapWorkDir = "vmap work " + work + " 2>&1";
    messages.clear();
    int rv2 = Application::runShellCommandAndGetOutput(mapWorkDir, messages);
    if (rv2 != 0) {
        if (verbose()) {
            for (unsigned int i = 0; i < messages.size(); i++) {
                std::cout << messages.at(i) << std::endl;
            }
        }
        string failed = "";
        return failed;
    }
    setWorkDir(work);
    return work;
}
References FileSystem::DIRECTORY_SEPARATOR, mapWorkDir(), Application::runShellCommandAndGetOutput(), ImplementationSimulator::setWorkDir(), ImplementationSimulator::tbDirectory(), and ImplementationSimulator::verbose().
Referenced by compile().
mapWorkDir()
bool ModelsimSimulator::mapWorkDir (std::string file, std::vector< std::string > & errors) private
Referenced by createWorkDir().
simulate()
bool ModelsimSimulator::simulate (std::vector< std::string > & errors) virtual
Implements ImplementationSimulator.
Definition at line 83 of file ModelsimSimulator.cc.
{
    // get correct simulation time from somewhere?
    // There's practically no difference between 30 ns and 300 ns simulation
    // time
    string simulate = "vsim -c -do \"run 300ns;quit\" work.testbench 2>&1";
    if (verbose()) {
        std::cout << simulate << std::endl;
    }
    vector<string> messages;
    int rv = Application::runShellCommandAndGetOutput(simulate, messages);
    parseErrorMessages(messages, errors);
    return rv == 0 && errors.size() == 0;
}
References ImplementationSimulator::parseErrorMessages(), Application::runShellCommandAndGetOutput(), simulate(), and ImplementationSimulator::verbose().
Referenced by simulate().
The documentation for this class was generated from the following files:
ModelsimSimulator.hh
ModelsimSimulator.cc