OpenASIP: IntegerCmdLineOptionParser Class Reference
IntegerCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
IntegerCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~IntegerCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual int integer (int index=0) const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual unsigned unsignedInteger (int index=0) const
virtual std::string String (int index=0) const
virtual double real () const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
virtual int listSize () const
Private Member Functions
IntegerCmdLineOptionParser (const IntegerCmdLineOptionParser &)
Copying not allowed.
IntegerCmdLineOptionParser & operator= (const IntegerCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
int value_
The value of option.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
Models an option that has an integer value.
Definition at line 117 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
IntegerCmdLineOptionParser() [1/2]
IntegerCmdLineOptionParser::IntegerCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 184 of file CmdLineOptionParser.cc.
                     : CmdLineOptionParser(name, desc, alias), value_(0) {
}
~IntegerCmdLineOptionParser()
IntegerCmdLineOptionParser::~IntegerCmdLineOptionParser () virtual
Destructor.
Definition at line 193 of file CmdLineOptionParser.cc.
{
}
IntegerCmdLineOptionParser() [2/2]
IntegerCmdLineOptionParser::IntegerCmdLineOptionParser (const IntegerCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * IntegerCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 205 of file CmdLineOptionParser.cc.
{
    IntegerOptionValue* copy = new IntegerOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
integer()
int IntegerCmdLineOptionParser::integer (int index = 0) const virtual
Returns the value of integer option.
Parameters
index This must be zero for integer option.
Returns
The value of integer option.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 253 of file CmdLineOptionParser.cc.
{
    assert(index == 0);
    return value_;
}
References assert, and value_.
operator=()
IntegerCmdLineOptionParser & IntegerCmdLineOptionParser::operator= (const IntegerCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool IntegerCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the integer option value.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine If the arguments of option are erronous.
Implements CmdLineOptionParser.
Definition at line 219 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for integer option";
        string method = "IntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    if (arguments == "") {
        string msg = "Missing value for integer option.";
        string method = "IntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    istringstream istream(arguments);
    if((!(istream >> value_)) || istream.peek() != EOF) {
        string msg = "Format of " + longName() + " option value was wrong: "
            + arguments;
        string method = "IntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    setDefined();
    return true;
}
References CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and value_.
Member Data Documentation
value_
int IntegerCmdLineOptionParser::value_ private
The value of option.
Definition at line 137 of file CmdLineOptionParser.hh.
Referenced by copy(), integer(), and parseValue().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc