OpenASIP: TestbenchGenerator Class Reference
TestbenchGenerator Class Reference abstract
#include <TestbenchGenerator.hh>
Public Member Functions
TestbenchGenerator ()
virtual ~TestbenchGenerator ()
virtual void generateTestbench (std::ofstream &file)=0
Protected Types
typedef std::map< std::string, std::vector< uint32_t > > PortDataArray
Protected Member Functions
virtual void writeStimulusArray (std::ostringstream &stream, std::vector< uint32_t > &dataArray, std::string portName, int portWidth)
void writeTbConstants (int totalCycles, int outputIgnoreCycles)
void writeTestbench (std::ofstream &file, HDB::HWBlockImplementation *impl)
std::ostringstream & declarationStream ()
std::ostringstream & bindingStream ()
std::ostringstream & signalStream ()
std::ostringstream & instantiationStream ()
std::ostringstream & inputArrayStream ()
std::ostringstream & opcodeArrayStream ()
std::ostringstream & loadArrayStream ()
std::ostringstream & outputArrayStream ()
std::ostringstream & tbCodeStream ()
Private Member Functions
std::string findVhdlTemplate () const
void loadVhdlTemplate (const std::string &fileName, std::string &vhdlTemplate) const
Private Attributes
std::ostringstream componentDeclaration_
std::ostringstream componentBinding_
std::ostringstream signalDeclaration_
std::ostringstream componentInstantiation_
std::ostringstream inputArrays_
std::ostringstream opcodeArrays_
std::ostringstream loadSignalArrays_
std::ostringstream outputArrays_
std::ostringstream testbenchCode_
Static Private Attributes
static const std::string TB_TEMPLATE_
Detailed Description
Definition at line 47 of file TestbenchGenerator.hh.
Member Typedef Documentation
PortDataArray
typedef std::map<std::string, std::vector<uint32_t> > TestbenchGenerator::PortDataArray protected
Definition at line 56 of file TestbenchGenerator.hh.
Constructor & Destructor Documentation
TestbenchGenerator()
TestbenchGenerator::TestbenchGenerator ()
Definition at line 57 of file TestbenchGenerator.cc.
                                      :
    componentDeclaration_(), componentBinding_(), signalDeclaration_(),
    componentInstantiation_(), inputArrays_(), opcodeArrays_(),
    loadSignalArrays_(), outputArrays_(), testbenchCode_() {
}
~TestbenchGenerator()
TestbenchGenerator::~TestbenchGenerator () virtual
Definition at line 63 of file TestbenchGenerator.cc.
{
}
Member Function Documentation
bindingStream()
std::ostringstream & TestbenchGenerator::bindingStream () protected
Definition at line 188 of file TestbenchGenerator.cc.
{
    return componentBinding_;
}
References componentBinding_.
Referenced by FUTestbenchGenerator::createTbInstantiation(), and RFTestbenchGenerator::createTbInstantiation().
declarationStream()
std::ostringstream & TestbenchGenerator::declarationStream () protected
Definition at line 183 of file TestbenchGenerator.cc.
{
    return componentDeclaration_;
}
References componentDeclaration_.
Referenced by FUTestbenchGenerator::createTbInstantiation(), and RFTestbenchGenerator::createTbInstantiation().
findVhdlTemplate()
std::string TestbenchGenerator::findVhdlTemplate () const private
Definition at line 142 of file TestbenchGenerator.cc.
{
    vector<string> paths = Environment::implementationTesterTemplatePaths();
    for (unsigned int i = 0; i < paths.size(); i++) {
        string file = paths.at(i) + FileSystem::DIRECTORY_SEPARATOR
            + TB_TEMPLATE_;
        if (FileSystem::fileExists(file)) {
            return file;
        }
    }
    InvalidData exception(__FILE__, __LINE__, "",
                          "The VHDL template file " + TB_TEMPLATE_ +
                          "not found");
    throw exception;
    string notFound = "";
    return notFound;
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), Environment::implementationTesterTemplatePaths(), and TB_TEMPLATE_.
Referenced by writeTestbench().
generateTestbench()
virtual void TestbenchGenerator::generateTestbench (std::ofstream & file) pure virtual
Implemented in FUTestbenchGenerator, and RFTestbenchGenerator.
Referenced by ImplementationTester::createTestbench().
inputArrayStream()
std::ostringstream & TestbenchGenerator::inputArrayStream () protected
Definition at line 203 of file TestbenchGenerator.cc.
{
    return inputArrays_;
}
References inputArrays_.
Referenced by RFTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createStimulusArrays().
instantiationStream()
std::ostringstream & TestbenchGenerator::instantiationStream () protected
Definition at line 198 of file TestbenchGenerator.cc.
{
    return componentInstantiation_;
}
References componentInstantiation_.
Referenced by FUTestbenchGenerator::createTbInstantiation(), and RFTestbenchGenerator::createTbInstantiation().
loadArrayStream()
std::ostringstream & TestbenchGenerator::loadArrayStream () protected
Definition at line 213 of file TestbenchGenerator.cc.
{
    return loadSignalArrays_;
}
References loadSignalArrays_.
Referenced by RFTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createStimulusArrays().
loadVhdlTemplate()
void TestbenchGenerator::loadVhdlTemplate (const std::string & fileName, std::string & vhdlTemplate) const private
Definition at line 163 of file TestbenchGenerator.cc.
{
    ifstream input(fileName.c_str());
    if (!input.is_open()) {
        InvalidData exception(__FILE__, __LINE__, "",
                              "The VHDL template file " + fileName +
                              "unreadable.");
        throw exception;
    }
    string line = "";
    while (getline(input, line)) {
        vhdlTemplate += line;
        vhdlTemplate += "\n";
    }
    input.close();
}
Referenced by writeTestbench().
opcodeArrayStream()
std::ostringstream & TestbenchGenerator::opcodeArrayStream () protected
Definition at line 208 of file TestbenchGenerator.cc.
{
    return opcodeArrays_;
}
References opcodeArrays_.
Referenced by RFTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createStimulusArrays().
outputArrayStream()
std::ostringstream & TestbenchGenerator::outputArrayStream () protected
Definition at line 218 of file TestbenchGenerator.cc.
{
    return outputArrays_;
}
References outputArrays_.
Referenced by RFTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createStimulusArrays().
signalStream()
std::ostringstream & TestbenchGenerator::signalStream () protected
Definition at line 193 of file TestbenchGenerator.cc.
{
    return signalDeclaration_;
}
References signalDeclaration_.
Referenced by FUTestbenchGenerator::createTbInstantiation(), and RFTestbenchGenerator::createTbInstantiation().
tbCodeStream()
std::ostringstream & TestbenchGenerator::tbCodeStream () protected
Definition at line 223 of file TestbenchGenerator.cc.
{
    return testbenchCode_;
}
References testbenchCode_.
Referenced by FUTestbenchGenerator::createTbCode(), and RFTestbenchGenerator::createTbCode().
writeStimulusArray()
void TestbenchGenerator::writeStimulusArray (std::ostringstream & stream, std::vector< uint32_t > & dataArray, std::string portName, int portWidth) protected virtual
Definition at line 68 of file TestbenchGenerator.cc.
{
    stream
        << INDENT INDENT  << "type " << portName
        << "_data_array is array (natural range <>) of" << std::endl
        << INDENT INDENT INDENT
        << "std_logic_vector(" << portWidth - 1 << " downto 0);"
        << std::endl << std::endl << INDENT INDENT
        << "constant " << portName << "_data : "
        << portName << "_data_array :=" << std::endl;
    for (std::size_t i = 0; i < dataArray.size(); ++i) {
        uint32_t input = dataArray.at(i);
        std::string inputAsBinaryLiteral =
            Conversion::toBinary(input, portWidth);
        stream << INDENT INDENT;
        if (i == 0) {
            stream << "(";
        } else {
            stream << " ";
        }
        stream << "\"" << inputAsBinaryLiteral << "\"";
        if (i == dataArray.size() - 1) {
            stream << ");";
        } else {
            stream << ",";
        }
        stream << "\t -- @" << i << " = " << input << std::endl;
    }
    stream << std::endl;
}
References INDENT, and Conversion::toBinary().
Referenced by FUTestbenchGenerator::createStimulusArrays(), and RFTestbenchGenerator::writeDataArrays().
writeTbConstants()
void TestbenchGenerator::writeTbConstants (int totalCycles, int outputIgnoreCycles) protected
Definition at line 104 of file TestbenchGenerator.cc.
{
    outputArrays_
        << INDENT INDENT << "constant IGNORE_OUTPUT_COUNT : integer := "
        << outputIgnoreCycles << ";" << std::endl;
    outputArrays_
        << INDENT INDENT << "constant TOTAL_CYCLE_COUNT : integer := "
        << totalCycles << ";" << std::endl;
}
References INDENT, and outputArrays_.
Referenced by FUTestbenchGenerator::createStimulus(), and RFTestbenchGenerator::createStimulus().
writeTestbench()
void TestbenchGenerator::writeTestbench (std::ofstream & file, HDB::HWBlockImplementation * impl) protected
Definition at line 116 of file TestbenchGenerator.cc.
{
    string templateFile = findVhdlTemplate();
    string vhdlTemplate = "";
    loadVhdlTemplate(templateFile, vhdlTemplate);
    string testBench =
        (boost::format(vhdlTemplate)
         % componentDeclaration_.str()
         % componentBinding_.str()
         % signalDeclaration_.str()
         % componentInstantiation_.str()
         % inputArrays_.str()
         % opcodeArrays_.str()
         % loadSignalArrays_.str()
         % outputArrays_.str()
         % impl->clkPort()
         % impl->rstPort()
         % impl->glockPort()
         % testbenchCode_.str()).str();
    file << testBench;
}
References HDB::HWBlockImplementation::clkPort(), componentBinding_, componentDeclaration_, componentInstantiation_, findVhdlTemplate(), HDB::HWBlockImplementation::glockPort(), inputArrays_, loadSignalArrays_, loadVhdlTemplate(), opcodeArrays_, outputArrays_, HDB::HWBlockImplementation::rstPort(), signalDeclaration_, and testbenchCode_.
Referenced by FUTestbenchGenerator::generateTestbench(), and RFTestbenchGenerator::generateTestbench().
Member Data Documentation
componentBinding_
std::ostringstream TestbenchGenerator::componentBinding_ private
Definition at line 86 of file TestbenchGenerator.hh.
Referenced by bindingStream(), and writeTestbench().
componentDeclaration_
std::ostringstream TestbenchGenerator::componentDeclaration_ private
Definition at line 85 of file TestbenchGenerator.hh.
Referenced by declarationStream(), and writeTestbench().
componentInstantiation_
std::ostringstream TestbenchGenerator::componentInstantiation_ private
Definition at line 88 of file TestbenchGenerator.hh.
Referenced by instantiationStream(), and writeTestbench().
inputArrays_
std::ostringstream TestbenchGenerator::inputArrays_ private
Definition at line 89 of file TestbenchGenerator.hh.
Referenced by inputArrayStream(), and writeTestbench().
loadSignalArrays_
std::ostringstream TestbenchGenerator::loadSignalArrays_ private
Definition at line 91 of file TestbenchGenerator.hh.
Referenced by loadArrayStream(), and writeTestbench().
opcodeArrays_
std::ostringstream TestbenchGenerator::opcodeArrays_ private
Definition at line 90 of file TestbenchGenerator.hh.
Referenced by opcodeArrayStream(), and writeTestbench().
outputArrays_
std::ostringstream TestbenchGenerator::outputArrays_ private
Definition at line 92 of file TestbenchGenerator.hh.
Referenced by outputArrayStream(), writeTbConstants(), and writeTestbench().
signalDeclaration_
std::ostringstream TestbenchGenerator::signalDeclaration_ private
Definition at line 87 of file TestbenchGenerator.hh.
Referenced by signalStream(), and writeTestbench().
TB_TEMPLATE_
const std::string TestbenchGenerator::TB_TEMPLATE_ static private
Initial value:
=
    "testbench.vhdl.template"
Definition at line 95 of file TestbenchGenerator.hh.
Referenced by findVhdlTemplate().
testbenchCode_
std::ostringstream TestbenchGenerator::testbenchCode_ private
Definition at line 93 of file TestbenchGenerator.hh.
Referenced by tbCodeStream(), and writeTestbench().
The documentation for this class was generated from the following files:
TestbenchGenerator.hh
TestbenchGenerator.cc