OpenASIP: FitHeightCmd Class Reference
FitHeightCmd Class Reference
#include <FitHeightCmd.hh>
Public Member Functions
FitHeightCmd ()
virtual ~FitHeightCmd ()
virtual bool Do ()
virtual int id () const
virtual FitHeightCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for zooming the canvas to fit the window height.
Definition at line 40 of file FitHeightCmd.hh.
Constructor & Destructor Documentation
FitHeightCmd()
FitHeightCmd::FitHeightCmd ()
The Constructor.
Definition at line 47 of file FitHeightCmd.cc.
                          :
    EditorCommand(ProDeConstants::CMD_NAME_ZOOM_FIT_HEI) {
}
Referenced by create().
~FitHeightCmd()
FitHeightCmd::~FitHeightCmd () virtual
The Destructor.
Definition at line 56 of file FitHeightCmd.cc.
{
}
Member Function Documentation
create()
FitHeightCmd * FitHeightCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 104 of file FitHeightCmd.cc.
{
    return new FitHeightCmd();
}
References FitHeightCmd().
Do()
bool FitHeightCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 67 of file FitHeightCmd.cc.
                 {
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    wxSize figureSize = canvas->getFigureSize();
    wxSize cSize = canvas->GetSize();
    // Decrease zoom factor from maximum until the figure height is smaller
    // than the window height.
    double factor = CanvasConstants::MAX_ZOOM_FACTOR;
    while (cSize.GetHeight() < factor*figureSize.GetHeight()) {
        factor = factor - CanvasConstants::AUTOZOOM_STEP;
    }
    canvas->setZoomFactor(factor);
    return true;
}
References CanvasConstants::AUTOZOOM_STEP, MDFView::canvas(), MachineCanvas::getFigureSize(), CanvasConstants::MAX_ZOOM_FACTOR, MachineCanvas::setZoomFactor(), and EditorCommand::view().
icon()
string FitHeightCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 115 of file FitHeightCmd.cc.
{
    return ProDeConstants::CMD_ICON_ZOOM_FIT_HEI;
}
References ProDeConstants::CMD_ICON_ZOOM_FIT_HEI.
id()
int FitHeightCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 93 of file FitHeightCmd.cc.
                       {
    return ProDeConstants::COMMAND_ZOOM_FIT_HEI;
}
References ProDeConstants::COMMAND_ZOOM_FIT_HEI.
isEnabled()
bool FitHeightCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 138 of file FitHeightCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string FitHeightCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 125 of file FitHeightCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ZOOM_FIT_HEI;
}
References ProDeConstants::CMD_SNAME_ZOOM_FIT_HEI.
The documentation for this class was generated from the following files:
FitHeightCmd.hh
FitHeightCmd.cc