OpenASIP: AddIUCmd Class Reference
AddIUCmd Class Reference
#include <AddIUCmd.hh>
Public Member Functions
AddIUCmd ()
virtual bool Do ()
virtual int id () const
virtual AddIUCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new immediate units to the Machine.
Displays a immediate unit dialog and creates a new immediate unit according to the dialog output.
Definition at line 43 of file AddIUCmd.hh.
Constructor & Destructor Documentation
AddIUCmd()
AddIUCmd::AddIUCmd ()
The Constructor.
Definition at line 52 of file AddIUCmd.cc.
                   :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_IU) {
}
Referenced by create().
Member Function Documentation
create()
AddIUCmd * AddIUCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 126 of file AddIUCmd.cc.
                       {
    return new AddIUCmd();
}
References AddIUCmd().
Do()
bool AddIUCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file AddIUCmd.cc.
             {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model =
    dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel();
    model->pushToStack();
    // Generate name for the new IU.
    Machine::ImmediateUnitNavigator navigator =
        model->getMachine()->immediateUnitNavigator();
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_IU;
    int i = 1;
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_IU +
            Conversion::toString(i);
        i++;
    }
    ImmediateUnit* iu =
        new ImmediateUnit(newName, ModelConstants::DEFAULT_IU_SIZE,
                          ModelConstants::DEFAULT_WIDTH,
                          ModelConstants::DEFAULT_IU_MAX_READS,
                          ModelConstants::DEFAULT_IU_GUARD_LATENCY,
                          Machine::ZERO);
    iu->setMachine(*(model->getMachine()));
    IUDialog dialog(parentWindow(), iu);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    // immediate unit creation was cancelled
    model->popFromStack();
    return false;
    }
    return false;
}
References assert, ProDeConstants::COMP_NEW_NAME_PREFIX_IU, ModelConstants::DEFAULT_IU_GUARD_LATENCY, ModelConstants::DEFAULT_IU_MAX_READS, ModelConstants::DEFAULT_IU_SIZE, ModelConstants::DEFAULT_WIDTH, Model::getMachine(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateUnitNavigator(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), TTAMachine::Unit::setMachine(), Conversion::toString(), EditorCommand::view(), and TTAMachine::Machine::ZERO.
id()
int AddIUCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 115 of file AddIUCmd.cc.
                   {
    return ProDeConstants::COMMAND_ADD_IU;
}
References ProDeConstants::COMMAND_ADD_IU.
isEnabled()
bool AddIUCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 150 of file AddIUCmd.cc.
                    {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddIUCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 137 of file AddIUCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_IU;
}
References ProDeConstants::CMD_SNAME_ADD_IU.
The documentation for this class was generated from the following files:
AddIUCmd.hh
AddIUCmd.cc