OpenASIP: Watch Class Reference
Watch Class Reference
#include <Watch.hh>
Public Member Functions
Watch (const SimulatorFrontend &frontend, const ExpressionScript &expression)
virtual ~Watch ()
virtual bool isTriggered () const
virtual std::string description () const
virtual StopPoint * copy () const
virtual const ExpressionScript & expression () const
virtual void setExpression (const ExpressionScript &expression)
Public Member Functions inherited from StopPoint
StopPoint ()
virtual ~StopPoint ()
virtual void setEnabled (bool flag)
virtual bool isEnabled () const
virtual void setDisabledAfterTriggered (bool flag)
virtual bool isDisabledAfterTriggered () const
virtual void setDeletedAfterTriggered (bool flag)
virtual bool isDeletedAfterTriggered () const
virtual void setCondition (const ConditionScript &condition)
virtual void removeCondition ()
virtual const ConditionScript & condition () const
virtual bool isConditional () const
virtual void setIgnoreCount (unsigned int count)
virtual unsigned int ignoreCount () const
virtual bool isConditionOK ()
virtual void decreaseIgnoreCount ()
Private Member Functions
Watch (const Watch &source)
Static copying not allowed (should use copy()).
Private Attributes
ExpressionScript expression_
The expression that is watched.
const SimulatorFrontend & frontend_
The simulator frontend which is used to fetch the current PC.
bool isTriggered_
Flag which tells whether the watch was triggered in current simulation cycle.
ClockCycleCount lastCheckedCycle_
The simulation clock cycle in which the expression was checked the last time.
Additional Inherited Members
Protected Attributes inherited from StopPoint
bool enabled_
Tells whether the breakpoint is enabled or disabled.
bool disabledAfterTriggered_
Tells if the breakpoint is disabled after it is triggered the next time.
bool deletedAfterTriggered_
Tells if the breakpoint is deleted after it is triggered the next time.
bool conditional_
Tells whether the breakpoint is conditional or not.
ConditionScript * condition_
The condition which is used to determine whether the breakpoint should be fired or not.
unsigned int ignoreCount_
The number of times the condition is to be ignored before enabling the breakpoint.
Detailed Description
Represents a simulation watch point.
Watch stops simulation when user-given expression changes its value.
Definition at line 48 of file Watch.hh.
Constructor & Destructor Documentation
Watch() [1/2]
Watch::Watch (const SimulatorFrontend & frontend, const ExpressionScript & expression)
Constructor.
Parameters
frontend Used to fetch the simulation clock.
expression The expression watched.
Definition at line 48 of file Watch.cc.
                                        :
    StopPoint(), expression_(expression), frontend_(frontend),
    isTriggered_(false), lastCheckedCycle_(0) {
}
~Watch()
Watch::~Watch () virtual
Destructor.
Definition at line 58 of file Watch.cc.
              {
}
Watch() [2/2]
Watch::Watch (const Watch & source) private
Static copying not allowed (should use copy()).
Member Function Documentation
copy()
StopPoint * Watch::copy () const virtual
Copy method for dynamically bound copies.
Implements StopPoint.
Definition at line 65 of file Watch.cc.
                  {
    StopPoint* aCopy = new Watch(frontend_, expression_);
    if (conditional_) {
        assert(condition_ != NULL);
        ConditionScript* conditionCopy = condition_->copy();
        assert(conditionCopy != NULL);
        aCopy->setCondition(*conditionCopy);
    } else {
        aCopy->removeCondition();
    }
    aCopy->setEnabled(enabled_);
    aCopy->setDisabledAfterTriggered(disabledAfterTriggered_);
    aCopy->setDeletedAfterTriggered(deletedAfterTriggered_);
    aCopy->setIgnoreCount(ignoreCount_);
    return aCopy;
}
References assert, StopPoint::condition_, StopPoint::conditional_, ConditionScript::copy(), StopPoint::deletedAfterTriggered_, StopPoint::disabledAfterTriggered_, StopPoint::enabled_, expression_, frontend_, StopPoint::ignoreCount_, StopPoint::removeCondition(), StopPoint::setCondition(), StopPoint::setDeletedAfterTriggered(), StopPoint::setDisabledAfterTriggered(), StopPoint::setEnabled(), and StopPoint::setIgnoreCount().
description()
std::string Watch::description () const virtual
Prints the description string of the stop point.
Each subclass overrides this method to construct a descripting string of itself.
Implements StopPoint.
Definition at line 134 of file Watch.cc.
{
    return std::string("watch for expression '") + expression_.script().at(0) +
        "' " + StopPoint::description();
}
References StopPoint::description(), expression_, and Script::script().
expression()
const ExpressionScript & Watch::expression () const virtual
Returns the expression.
Returns
The expression.
Definition at line 88 of file Watch.cc.
{
    return expression_;
}
References expression_.
Referenced by ProximBreakpointWindow::refreshStopPoints(), setExpression(), and WatchPropertiesDialog::TransferDataToWindow().
isTriggered()
bool Watch::isTriggered () const virtual
Returns true in case this watch is triggered.
Returns true in case the expression has changed in current simulation cycle.
Returns
The status of the watch.
Implements StopPoint.
Definition at line 110 of file Watch.cc.
{
    if (lastCheckedCycle_ != frontend_.cycleCount()) {
        // simulation clock has changed since the last expression check,
        // let's see if the watch expression value has changed
        try {
            isTriggered_ = expression_.resultChanged();
        } catch (const Exception&) {
            // for example simulation might not be initialized in every
            // check so the script throws, we'll assume that no triggering
            // should happen at that case
            isTriggered_ = false;
        }
        lastCheckedCycle_ = frontend_.cycleCount();
    }
    return isTriggered_;
}
References SimulatorFrontend::cycleCount(), expression_, frontend_, isTriggered_, lastCheckedCycle_, and ExpressionScript::resultChanged().
setExpression()
void Watch::setExpression (const ExpressionScript & expression) virtual
Sets the expression the watch is watching.
Parameters
expression The new expression.
Definition at line 98 of file Watch.cc.
{
    expression_ = expression;
}
References expression(), and expression_.
Member Data Documentation
expression_
ExpressionScript Watch::expression_ mutable private
The expression that is watched.
Definition at line 66 of file Watch.hh.
Referenced by copy(), description(), expression(), isTriggered(), and setExpression().
frontend_
const SimulatorFrontend& Watch::frontend_ private
The simulator frontend which is used to fetch the current PC.
Definition at line 68 of file Watch.hh.
Referenced by copy(), and isTriggered().
isTriggered_
bool Watch::isTriggered_ mutable private
Flag which tells whether the watch was triggered in current simulation cycle.
Definition at line 71 of file Watch.hh.
Referenced by isTriggered().
lastCheckedCycle_
ClockCycleCount Watch::lastCheckedCycle_ mutable private
The simulation clock cycle in which the expression was checked the last time.
Definition at line 74 of file Watch.hh.
Referenced by isTriggered().
The documentation for this class was generated from the following files:
Watch.hh
Watch.cc