OpenASIP: HDLGenerator::Variable Class Reference
HDLGenerator::Variable Class Reference
#include <HDLGenerator.hh>
Public Member Functions
Variable (std::string name, int width=1)
Variable (std::string name, std::string width)
Width width () final
void declare (std::ostream &stream, Language lang, int level)
std::string vhdlRange ()
std::string verilogRange ()
virtual std::string vhdlTypeDeclaration ()
std::string verilogTypeDeclaration ()
bool isVector ()
WireType wireType ()
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang, int indent)
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::string strWidth_
int width_
WireType wireType_
Detailed Description
Definition at line 414 of file HDLGenerator.hh.
Constructor & Destructor Documentation
Variable() [1/2]
HDLGenerator::Variable::Variable (std::string name, int width = 1) inline
Definition at line 416 of file HDLGenerator.hh.
            : Generatable(name), strWidth_(std::to_string(width)),
              width_(width), wireType_(WireType::Auto) {}
Variable() [2/2]
HDLGenerator::Variable::Variable (std::string name, std::string width) inline
Definition at line 419 of file HDLGenerator.hh.
            : Generatable(name), strWidth_(width), width_(-1),
              wireType_(WireType::Vector) {}
Member Function Documentation
declare()
void HDLGenerator::Variable::declare (std::ostream & stream, Language lang, int level) inline
Definition at line 425 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                stream << StringTools::indent(level) << "variable " << name()
                       << " : " << vhdlTypeDeclaration() << ";\n";
            } else if (lang == Language::Verilog) {
                stream << StringTools::indent(level)
                       << verilogTypeDeclaration()
                       << " " << name() << ";\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References StringTools::indent(), HDLGenerator::Generatable::name(), HDLGenerator::Verilog, verilogTypeDeclaration(), HDLGenerator::VHDL, and vhdlTypeDeclaration().
isVector()
bool HDLGenerator::Variable::isVector () inline
Definition at line 466 of file HDLGenerator.hh.
{
            return wireType_ == WireType::Vector || width_ > 1;
        }
References HDLGenerator::Vector, width_, and wireType_.
Referenced by verilogTypeDeclaration(), HDLGenerator::SignedVariable::verilogTypeDeclaration(), and HDLGenerator::LogicVariable::vhdlTypeDeclaration().
verilogRange()
std::string HDLGenerator::Variable::verilogRange () inline
Definition at line 446 of file HDLGenerator.hh.
{
            std::string width = strWidth_;
            if (width.empty()) {
                width = std::to_string(width_);
            }
            return "[" + width + "-1:0] ";
        }
References strWidth_, width(), and width_.
Referenced by verilogTypeDeclaration(), and HDLGenerator::SignedVariable::verilogTypeDeclaration().
verilogTypeDeclaration()
std::string HDLGenerator::Variable::verilogTypeDeclaration () inline
Definition at line 458 of file HDLGenerator.hh.
{
            std::string decl = "reg";
            if (isVector()) {
                decl += " " + verilogRange();
            }
            return decl;
        }
References isVector(), and verilogRange().
Referenced by declare().
vhdlRange()
std::string HDLGenerator::Variable::vhdlRange () inline
Definition at line 438 of file HDLGenerator.hh.
{
            std::string width = strWidth_;
            if (width.empty()) {
                width = std::to_string(width_);
            }
            return "(" + width + "-1 downto 0)";
        }
References strWidth_, width(), and width_.
Referenced by HDLGenerator::LogicVariable::vhdlTypeDeclaration(), HDLGenerator::UnsignedVariable::vhdlTypeDeclaration(), and HDLGenerator::SignedVariable::vhdlTypeDeclaration().
vhdlTypeDeclaration()
virtual std::string HDLGenerator::Variable::vhdlTypeDeclaration () inline virtual
Reimplemented in HDLGenerator::LogicVariable, HDLGenerator::UnsignedVariable, and HDLGenerator::SignedVariable.
Definition at line 454 of file HDLGenerator.hh.
{
            throw std::runtime_error(__PRETTY_FUNCTION__);
        }
Referenced by declare().
width()
Width HDLGenerator::Variable::width () inline final virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 423 of file HDLGenerator.hh.
{ return {strWidth_, width_}; }
References strWidth_, and width_.
Referenced by verilogRange(), and vhdlRange().
wireType()
WireType HDLGenerator::Variable::wireType () inline
Definition at line 470 of file HDLGenerator.hh.
{
            return wireType_;
        }
References wireType_.
Member Data Documentation
strWidth_
std::string HDLGenerator::Variable::strWidth_ private
Definition at line 475 of file HDLGenerator.hh.
Referenced by verilogRange(), vhdlRange(), and width().
width_
int HDLGenerator::Variable::width_ private
Definition at line 476 of file HDLGenerator.hh.
Referenced by isVector(), verilogRange(), vhdlRange(), and width().
wireType_
WireType HDLGenerator::Variable::wireType_ private
Definition at line 477 of file HDLGenerator.hh.
Referenced by isVector(), and wireType().
The documentation for this class was generated from the following file:
HDLGenerator.hh