OpenASIP: InfoImmediatesCommand Class Reference
InfoImmediatesCommand Class Reference
Public Member Functions
InfoImmediatesCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoImmediatesCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info immediates".
Definition at line 206 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoImmediatesCommand()
InfoImmediatesCommand::InfoImmediatesCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 212 of file InfoCommand.cc.
                                                                    :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoImmediatesCommand()
virtual InfoImmediatesCommand::~InfoImmediatesCommand () inline virtual
Destructor.
Definition at line 219 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoImmediatesCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info immediates" command.
"info immediates iunit regname" prints the value of register regname in immediate unit iunit, where regfile is the name of a register file of the target processor, and regname is the name of a register that belongs to the specified register file. If regname is omitted, values of all registers of the specified immediate unit are displayed.
Parameters
arguments Arguments to the command, including "info immediates".
Returns
true in case execution was successful.
Implements SimControlLanguageSubCommand.
Definition at line 234 of file InfoCommand.cc.
{
        if (!parent().checkProgramLoaded()) {
            return false;
        }
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 1, 2)) {
            return false;
        }
        const std::string unitName = arguments[2].stringValue();
        const TTAMachine::Machine::ImmediateUnitNavigator navigator =
                parent().simulatorFrontend().machine().immediateUnitNavigator();
        if (!navigator.hasItem(unitName)) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_IMMEDIATE_UNIT_NOT_FOUND).str());
                return false;
            }
        if (argumentCount == 1) {
            std::string output = "";
            bool firstReg = true;
            for (int i = 0; i < navigator.count(); ++i) {
                if (!firstReg)
                    output += "\n";
                SimValue value = parent().simulatorFrontend().
                    immediateUnitRegisterValue(unitName, i);
                const std::string registerName =
                    unitName + "." + Conversion::toString(i);
                output += InfoRegistersCommand::registerDescription(
                    registerName, value);
                firstReg = false;
            }
            parent().interpreter()->setResult(output);
            return true;
        } else if (argumentCount == 2) {
            // prints out the register in the given register file
            if (!parent().checkPositiveIntegerArgument(arguments[3])) {
                return false;
            }
            int registerIndex = arguments[3].integerValue();
            try {
                SimValue value = parent().simulatorFrontend().
                    immediateUnitRegisterValue(unitName, registerIndex);
                parent().interpreter()->setResult(value.intValue());
                return true;
            } catch (const Exception& e) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_REGISTER_NOT_FOUND).str());
                return false;
            }
        }
        abortWithError("Shouldn't get here.");
        return false;
    }
References abortWithError, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateUnitNavigator(), CustomCommand::interpreter(), SimValue::intValue(), SimulatorFrontend::machine(), SimControlLanguageSubCommand::parent(), InfoRegistersCommand::registerDescription(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), SimulatorToolbox::textGenerator(), Conversion::toString(), Texts::TXT_IMMEDIATE_UNIT_NOT_FOUND, and Texts::TXT_REGISTER_NOT_FOUND.
The documentation for this class was generated from the following file:
InfoCommand.cc