OpenASIP: CentralizedControlICGenerator Class Reference
CentralizedControlICGenerator Class Reference abstract
#include <CentralizedControlICGenerator.hh>
Public Member Functions
CentralizedControlICGenerator ()
virtual ~CentralizedControlICGenerator ()
ProGe::NetlistPort & simmDataPort (const std::string &busName) const
ProGe::NetlistPort & simmCntrlPort (const std::string &busName) const
ProGe::NetlistPort & busCntrlPortOfSocket (const std::string &socketName) const
ProGe::NetlistPort & dataCntrlPortOfSocket (const std::string &socketName) const
bool hasGlockPort () const
ProGe::NetlistPort & glockPort () const
virtual int outputSocketCntrlPinForSegment (const TTAMachine::Socket &socket, const TTAMachine::Segment &segment) const =0
virtual int outputSocketDataControlValue (const TTAMachine::Socket &socket, const TTAMachine::Port &port) const =0
virtual int inputSocketControlValue (const TTAMachine::Socket &socket, const TTAMachine::Segment &segment) const =0
Protected Member Functions
void mapSImmDataPort (const std::string &busName, ProGe::NetlistPort &port)
void mapSImmCntrlPort (const std::string &busName, ProGe::NetlistPort &port)
void mapBusCntrlPortOfSocket (const std::string &socketName, ProGe::NetlistPort &port)
void mapDataCntrlPortOfSocket (const std::string &socketName, ProGe::NetlistPort &port)
void setGlockPort (ProGe::NetlistPort &glockPort)
Private Types
typedef std::map< std::string, ProGe::NetlistPort * > NetlistPortMap
Private Attributes
NetlistPortMap simmDataPortMap_
Maps the short immediate data ports for buses.
NetlistPortMap simmCntrlPortMap_
Maps the short immediate control ports for buses.
NetlistPortMap socketDataPortMap_
Maps the data ports of sockets.
NetlistPortMap busCntrlPortMap_
Maps the bus control ports of sockets.
NetlistPortMap dataCntrlPortMap_
Maps the data control ports of sockets.
ProGe::NetlistPort * glockPort_
(optional) Glock port
Detailed Description
Definition at line 52 of file CentralizedControlICGenerator.hh.
Member Typedef Documentation
NetlistPortMap
typedef std::map<std::string, ProGe::NetlistPort*> CentralizedControlICGenerator::NetlistPortMap private
Definition at line 90 of file CentralizedControlICGenerator.hh.
Constructor & Destructor Documentation
CentralizedControlICGenerator()
CentralizedControlICGenerator::CentralizedControlICGenerator ()
The constructor.
Definition at line 44 of file CentralizedControlICGenerator.cc.
                                                             :
    glockPort_(0) {
}
~CentralizedControlICGenerator()
CentralizedControlICGenerator::~CentralizedControlICGenerator () virtual
The destructor.
Definition at line 52 of file CentralizedControlICGenerator.cc.
{
}
Member Function Documentation
busCntrlPortOfSocket()
ProGe::NetlistPort & CentralizedControlICGenerator::busCntrlPortOfSocket (const std::string & socketName) const
Returns the bus control port of the given socket in the IC block.
Parameters
socketName Name of the socket.
Returns
The netlist port that was added by the IC generator.
Exceptions
InstanceNotFound If the port was not created.
Definition at line 98 of file CentralizedControlICGenerator.cc.
{
    try {
        return *MapTools::valueForKey<NetlistPort*>(busCntrlPortMap_, socketName);
    } catch (const Exception&) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, busCntrlPortMap_, and MapTools::keyForValue().
Referenced by DefaultDecoderGenerator::completeDecoderBlock().
dataCntrlPortOfSocket()
ProGe::NetlistPort & CentralizedControlICGenerator::dataCntrlPortOfSocket (const std::string & socketName) const
Returns the data control port of the given socket in the IC block.
Parameters
socketName Name of the socket.
Returns
The netlist port that was added by the IC generator.
Exceptions
InstanceNotFound If the port was not created.
Definition at line 115 of file CentralizedControlICGenerator.cc.
{
    try {
        return *MapTools::valueForKey<NetlistPort*>(dataCntrlPortMap_, socketName);
    } catch (const Exception&) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, dataCntrlPortMap_, and MapTools::keyForValue().
Referenced by DefaultDecoderGenerator::completeDecoderBlock().
glockPort()
ProGe::NetlistPort & CentralizedControlICGenerator::glockPort () const
Returns reference to NetlistPort of glock.
Exceptions
InstanceNotFound If IC does not have glock port.
Definition at line 139 of file CentralizedControlICGenerator.cc.
{
    if (!hasGlockPort()) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__,
            "IC does not have glock port.");
    } else {
        return *glockPort_;
    }
}
References __func__, glockPort_, and hasGlockPort().
Referenced by DefaultDecoderGenerator::addGlockPortToDecoder(), and setGlockPort().
hasGlockPort()
bool CentralizedControlICGenerator::hasGlockPort () const
Returns true if IC has glock port.
Definition at line 128 of file CentralizedControlICGenerator.cc.
{
    return (glockPort_ != 0);
}
References glockPort_.
Referenced by DefaultDecoderGenerator::addGlockPortToDecoder(), glockPort(), and DefaultDecoderGenerator::glockPortWidth().
inputSocketControlValue()
virtual int CentralizedControlICGenerator::inputSocketControlValue (const TTAMachine::Socket & socket, const TTAMachine::Segment & segment) const pure virtual
Implemented in DefaultICGenerator.
Referenced by DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
mapBusCntrlPortOfSocket()
void CentralizedControlICGenerator::mapBusCntrlPortOfSocket (const std::string & socketName, ProGe::NetlistPort & port) protected
Maps the given bus control port for the given socket.
Parameters
socketName Name of the socket.
port The netlist port.
Definition at line 191 of file CentralizedControlICGenerator.cc.
{
    assert(!MapTools::containsKey(busCntrlPortMap_, socketName));
    busCntrlPortMap_.insert(
        std::pair<std::string, NetlistPort*>(socketName, &port));
}
References assert, busCntrlPortMap_, and MapTools::containsKey().
Referenced by DefaultICGenerator::addICToNetlist().
mapDataCntrlPortOfSocket()
void CentralizedControlICGenerator::mapDataCntrlPortOfSocket (const std::string & socketName, ProGe::NetlistPort & port) protected
Maps the given data control port for the given socket.
Parameters
socketName Name of the socket.
port The netlist port.
Definition at line 208 of file CentralizedControlICGenerator.cc.
{
    assert(!MapTools::containsKey(dataCntrlPortMap_, socketName));
    dataCntrlPortMap_.insert(
        std::pair<std::string, NetlistPort*>(socketName, &port));
}
References assert, MapTools::containsKey(), and dataCntrlPortMap_.
Referenced by DefaultICGenerator::addICToNetlist().
mapSImmCntrlPort()
void CentralizedControlICGenerator::mapSImmCntrlPort (const std::string & busName, ProGe::NetlistPort & port) protected
Maps the given netlist port as the short immediate control port of the given bus.
Parameters
busName The bus.
port The netlist port.
Definition at line 174 of file CentralizedControlICGenerator.cc.
{
    assert(!MapTools::containsKey(simmCntrlPortMap_, busName));
    simmCntrlPortMap_.insert(
        std::pair<std::string, NetlistPort*>(busName, &port));
}
References assert, MapTools::containsKey(), and simmCntrlPortMap_.
Referenced by DefaultICGenerator::addICToNetlist().
mapSImmDataPort()
void CentralizedControlICGenerator::mapSImmDataPort (const std::string & busName, ProGe::NetlistPort & port) protected
Maps the given netlist port as the short immediate data port of the given bus.
Parameters
busName The bus.
port The netlist port.
Definition at line 156 of file CentralizedControlICGenerator.cc.
{
    assert(!MapTools::containsKey(simmDataPortMap_, busName));
    simmDataPortMap_.insert(
        std::pair<std::string, NetlistPort*>(busName, &port));
}
References assert, MapTools::containsKey(), and simmDataPortMap_.
Referenced by DefaultICGenerator::addICToNetlist().
outputSocketCntrlPinForSegment()
virtual int CentralizedControlICGenerator::outputSocketCntrlPinForSegment (const TTAMachine::Socket & socket, const TTAMachine::Segment & segment) const pure virtual
Implemented in DefaultICGenerator.
Referenced by DefaultDecoderGenerator::busCntrlSignalPinOfSocket().
outputSocketDataControlValue()
virtual int CentralizedControlICGenerator::outputSocketDataControlValue (const TTAMachine::Socket & socket, const TTAMachine::Port & port) const pure virtual
Implemented in DefaultICGenerator.
Referenced by DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), and DefaultDecoderGenerator::writeControlRulesOfRFReadPort().
setGlockPort()
void CentralizedControlICGenerator::setGlockPort (ProGe::NetlistPort & glockPort) protected
Sets optional glock port of IC.
Parameters
glockPort The glock port.
Definition at line 224 of file CentralizedControlICGenerator.cc.
{
    assert(glockPort_ == 0);
    glockPort_ = &glockPort;
}
References assert, glockPort(), and glockPort_.
Referenced by DefaultICGenerator::addICToNetlist().
simmCntrlPort()
ProGe::NetlistPort & CentralizedControlICGenerator::simmCntrlPort (const std::string & busName) const
Returns the short immediate control port for the given bus.
Parameters
busName Name of the bus.
Returns
The netlist port that was added by the IC generator.
Exceptions
InstanceNotFound If the port was not created.
Definition at line 81 of file CentralizedControlICGenerator.cc.
{
    try {
        return *MapTools::valueForKey<NetlistPort*>(
            simmCntrlPortMap_, busName);
    } catch (const Exception&) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, MapTools::keyForValue(), and simmCntrlPortMap_.
simmDataPort()
ProGe::NetlistPort & CentralizedControlICGenerator::simmDataPort (const std::string & busName) const
Returns the short immediate data port for the given bus.
Parameters
busName Name of the bus.
Returns
The netlist port that was added by the IC generator.
Exceptions
InstanceNotFound If the port was not created.
Definition at line 64 of file CentralizedControlICGenerator.cc.
{
    try {
        return *MapTools::valueForKey<NetlistPort*>(
            simmDataPortMap_, busName);
    } catch (const Exception&) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, MapTools::keyForValue(), and simmDataPortMap_.
Referenced by DefaultDecoderGenerator::completeDecoderBlock().
Member Data Documentation
busCntrlPortMap_
NetlistPortMap CentralizedControlICGenerator::busCntrlPortMap_ private
Maps the bus control ports of sockets.
Definition at line 99 of file CentralizedControlICGenerator.hh.
Referenced by busCntrlPortOfSocket(), and mapBusCntrlPortOfSocket().
dataCntrlPortMap_
NetlistPortMap CentralizedControlICGenerator::dataCntrlPortMap_ private
Maps the data control ports of sockets.
Definition at line 101 of file CentralizedControlICGenerator.hh.
Referenced by dataCntrlPortOfSocket(), and mapDataCntrlPortOfSocket().
glockPort_
ProGe::NetlistPort* CentralizedControlICGenerator::glockPort_ private
(optional) Glock port
Definition at line 103 of file CentralizedControlICGenerator.hh.
Referenced by glockPort(), hasGlockPort(), and setGlockPort().
simmCntrlPortMap_
NetlistPortMap CentralizedControlICGenerator::simmCntrlPortMap_ private
Maps the short immediate control ports for buses.
Definition at line 95 of file CentralizedControlICGenerator.hh.
Referenced by mapSImmCntrlPort(), and simmCntrlPort().
simmDataPortMap_
NetlistPortMap CentralizedControlICGenerator::simmDataPortMap_ private
Maps the short immediate data ports for buses.
Definition at line 93 of file CentralizedControlICGenerator.hh.
Referenced by mapSImmDataPort(), and simmDataPort().
socketDataPortMap_
NetlistPortMap CentralizedControlICGenerator::socketDataPortMap_ private
Maps the data ports of sockets.
Definition at line 97 of file CentralizedControlICGenerator.hh.
The documentation for this class was generated from the following files:
CentralizedControlICGenerator.hh
CentralizedControlICGenerator.cc