OpenASIP: ReservationTableFUResourceConflictDetector Class Reference
ReservationTableFUResourceConflictDetector Class Reference
#include <ReservationTableFUResourceConflictDetector.hh>
Public Member Functions
ReservationTableFUResourceConflictDetector (const TTAMachine::FunctionUnit &fu)
virtual ~ReservationTableFUResourceConflictDetector ()
virtual bool issueOperation (OperationID id)
virtual bool advanceCycle ()
virtual void reset ()
bool issueOperationInline (OperationID id)
bool advanceCycleInline ()
virtual OperationID operationID (const TCEString &operationName) const
Public Member Functions inherited from FUResourceConflictDetector
FUResourceConflictDetector ()
virtual ~FUResourceConflictDetector ()
virtual void endClock ()
virtual void advanceClock ()
virtual bool isIdle ()
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Private Attributes
FUReservationTableIndex reservationTables_
The reservation tables of operations.
ReservationTable globalReservationTable_
The global reservation table.
const TTAMachine::FunctionUnit & fu_
The modeled FU.
Additional Inherited Members
Public Types inherited from FUResourceConflictDetector
typedef int OperationID
Type for identifying operations in the conflict detector interface.
Protected Attributes inherited from FUResourceConflictDetector
OperationIDIndex * operationIndices_
Map for finding indices for operations quickly.
Detailed Description
A Conventional Reservation Table implementation of a FU resource conflict detector.
Definition at line 55 of file ReservationTableFUResourceConflictDetector.hh.
Constructor & Destructor Documentation
ReservationTableFUResourceConflictDetector()
ReservationTableFUResourceConflictDetector::ReservationTableFUResourceConflictDetector (const TTAMachine::FunctionUnit & fu)
Constructor.
Parameters
fu The function unit to detect conflicts for.
Exceptions
InvalidData If the model could not be built from the given FU.
Definition at line 45 of file ReservationTableFUResourceConflictDetector.cc.
    : reservationTables_(fu), globalReservationTable_(fu), fu_(fu) {}
~ReservationTableFUResourceConflictDetector()
ReservationTableFUResourceConflictDetector::~ReservationTableFUResourceConflictDetector () virtual
Destructor.
Definition at line 53 of file ReservationTableFUResourceConflictDetector.cc.
{
}
Member Function Documentation
advanceCycle()
bool ReservationTableFUResourceConflictDetector::advanceCycle () virtual
Simulates a cycle advance and reports a conflict if detected.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 74 of file ReservationTableFUResourceConflictDetector.cc.
{
    return advanceCycleInline();
}
References advanceCycleInline().
advanceCycleInline()
bool ReservationTableFUResourceConflictDetector::advanceCycleInline ()
Referenced by advanceCycle().
issueOperation()
bool ReservationTableFUResourceConflictDetector::issueOperation (OperationID id) virtual
Issues an operation and reports a conflict if detected.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented from FUResourceConflictDetector.
Definition at line 64 of file ReservationTableFUResourceConflictDetector.cc.
{
    return issueOperationInline(id);
}
References issueOperationInline().
issueOperationInline()
bool ReservationTableFUResourceConflictDetector::issueOperationInline (OperationID id)
Referenced by issueOperation().
operationID()
ReservationTableFUResourceConflictDetector::OperationID ReservationTableFUResourceConflictDetector::operationID (const TCEString & operationName) const virtual
Returns an operation id for the given operation.
Operation IDs are used in the interface for optimizing the access. This method converts OSAL Operations to operation IDs.
Parameters
operation The OSAL Operation to find ID for.
Returns
The operation ID.
Exceptions
KeyNotFound if the operation of given name couldn't be found
Reimplemented from FUResourceConflictDetector.
Definition at line 89 of file ReservationTableFUResourceConflictDetector.cc.
{
    // find the index of the operation in the FU, it corresponds to the
    // operation ID
    for (int i = 0; i < fu_.operationCount(); ++i) {
        if (StringTools::ciEqual(fu_.operation(i)->name(), operationName)) {
            return i;
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, __func__, "Operation not found.");
}
References __func__, StringTools::ciEqual(), fu_, TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), and TTAMachine::FunctionUnit::operationCount().
reset()
void ReservationTableFUResourceConflictDetector::reset () virtual
Sets the state of the detector to its initial state.
This means that the FU state is assumed to be what it is in powerup.
Reimplemented from FUResourceConflictDetector.
Definition at line 108 of file ReservationTableFUResourceConflictDetector.cc.
{
    globalReservationTable_.setAllToZero();
}
References globalReservationTable_, and BitMatrix::setAllToZero().
Member Data Documentation
fu_
const TTAMachine::FunctionUnit& ReservationTableFUResourceConflictDetector::fu_ private
The modeled FU.
Definition at line 77 of file ReservationTableFUResourceConflictDetector.hh.
Referenced by operationID().
globalReservationTable_
ReservationTable ReservationTableFUResourceConflictDetector::globalReservationTable_ private
The global reservation table.
Definition at line 75 of file ReservationTableFUResourceConflictDetector.hh.
Referenced by reset().
reservationTables_
FUReservationTableIndex ReservationTableFUResourceConflictDetector::reservationTables_ private
The reservation tables of operations.
Definition at line 73 of file ReservationTableFUResourceConflictDetector.hh.
The documentation for this class was generated from the following files:
ReservationTableFUResourceConflictDetector.hh
ReservationTableFUResourceConflictDetector.cc