OpenASIP: TPEF::TPEFLineNumSectionWriter Class Reference
TPEF::TPEFLineNumSectionWriter Class Reference
#include <TPEFLineNumSectionWriter.hh>
Protected Member Functions
TPEFLineNumSectionWriter ()
virtual ~TPEFLineNumSectionWriter ()
virtual Section::SectionType type () const
virtual void actualWriteData (BinaryStream &stream, const Section *section) const
virtual Word elementSize (const Section *section) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void createKeys (const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFLineNumSectionWriter (const TPEFLineNumSectionWriter &)
Copying not allowed.
TPEFLineNumSectionWriter operator= (const TPEFLineNumSectionWriter &)
Assignment not allowed.
Static Private Attributes
static const TPEFLineNumSectionWriter instance_
An unique instance of class.
static const Word elementSize_ = 6
The fixed size address space element.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes TPEF line number section to stream.
Definition at line 46 of file TPEFLineNumSectionWriter.hh.
Constructor & Destructor Documentation
TPEFLineNumSectionWriter() [1/2]
TPEF::TPEFLineNumSectionWriter::TPEFLineNumSectionWriter () protected
Constructor.
Registers itself to SectionWriter.
Definition at line 66 of file TPEFLineNumSectionWriter.cc.
                                                   : TPEFSectionWriter() {
    registerSectionWriter(this);
}
References TPEF::SectionWriter::registerSectionWriter().
~TPEFLineNumSectionWriter()
TPEF::TPEFLineNumSectionWriter::~TPEFLineNumSectionWriter () protected virtual
Destructor.
Definition at line 73 of file TPEFLineNumSectionWriter.cc.
{
}
TPEFLineNumSectionWriter() [2/2]
TPEF::TPEFLineNumSectionWriter::TPEFLineNumSectionWriter (const TPEFLineNumSectionWriter &) private
Copying not allowed.
Member Function Documentation
actualWriteData()
void TPEF::TPEFLineNumSectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected virtual
Writes the data of the section in to stream.
Parameters
stream The stream to be written to.
sect The section to be written.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 93 of file TPEFLineNumSectionWriter.cc.
{
    FileOffset startOffset = stream.writePosition();
    // file offset to data of section
    SafePointer::addObjectReference(
        FileOffsetKey(startOffset), sect->element(0));
    for (Word i = 0; i < sect->elementCount(); i++) {
        LineNumProcedure* elem =
            dynamic_cast<LineNumProcedure*>(sect->element(i));
        assert(elem != NULL);
        if (elem->procedureSymbol() != NULL) {
            SectionIndexReplacer
                replacer(elem->procedureSymbol(), sizeof(Word));
            replacer.resolve();
        } else {
            bool procedureSymbolMustBeSet = false;
            assert(procedureSymbolMustBeSet);
        }
        // line number zero represents procedure
        stream.writeHalfWord(0);
        // write line nums...
        for(Word lineIndex = 0; lineIndex < elem->lineCount(); lineIndex++) {
            const LineNumElement* lineElem = elem->line(lineIndex);
            // write each line
            SectionOffsetReplacer replacer(lineElem->instruction());
            replacer.resolve();
            stream.writeHalfWord(lineElem->lineNumber());
        }
    }
    SectionSizeReplacer::setSize(sect, stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::LineNumElement::instruction(), TPEF::LineNumProcedure::line(), TPEF::LineNumProcedure::lineCount(), TPEF::LineNumElement::lineNumber(), TPEF::LineNumProcedure::procedureSymbol(), TPEF::ValueReplacer::resolve(), TPEF::SectionSizeReplacer::setSize(), TPEF::BinaryStream::writeHalfWord(), and TPEF::BinaryStream::writePosition().
elementSize()
Word TPEF::TPEFLineNumSectionWriter::elementSize (const Section * section) const protected virtual
Returns the fixed size length of section elements.
Returns
The fixed size length of section elements.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 139 of file TPEFLineNumSectionWriter.cc.
{
    return elementSize_;
}
References elementSize_.
operator=()
TPEFLineNumSectionWriter TPEF::TPEFLineNumSectionWriter::operator= (const TPEFLineNumSectionWriter &) private
Assignment not allowed.
type()
Section::SectionType TPEF::TPEFLineNumSectionWriter::type () const protected virtual
Returns the section type this writer can write.
Returns
The section type writer can write.
Implements TPEF::TPEFSectionWriter.
Definition at line 82 of file TPEFLineNumSectionWriter.cc.
{
    return Section::ST_LINENO;
}
References TPEF::Section::ST_LINENO.
writeInfo()
void TPEF::TPEFLineNumSectionWriter::writeInfo (BinaryStream & stream, const Section * sect) const protected virtual
Writes Info field of section header.
Parameters
stream The stream where to write.
sect Section to write.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 150 of file TPEFLineNumSectionWriter.cc.
{
    const Section* codeSection =
        dynamic_cast<const LineNumSection*>(sect)->codeSection();
    SectionIdReplacer idReplacer(codeSection);
    idReplacer.resolve();
    stream.writeHalfWord(0);
}
References TPEF::ValueReplacer::resolve(), and TPEF::BinaryStream::writeHalfWord().
Member Data Documentation
elementSize_
const Word TPEF::TPEFLineNumSectionWriter::elementSize_ = 6 static private
The fixed size address space element.
Definition at line 70 of file TPEFLineNumSectionWriter.hh.
Referenced by elementSize().
instance_
const TPEFLineNumSectionWriter TPEF::TPEFLineNumSectionWriter::instance_ static private
An unique instance of class.
Definition at line 68 of file TPEFLineNumSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFLineNumSectionWriter.hh
TPEFLineNumSectionWriter.cc