OpenASIP: llvm::TCEPassConfig Class Reference
llvm::TCEPassConfig Class Reference
#include <TCETargetMachine.hh>
Public Member Functions
TCEPassConfig (LLVMTargetMachine *tm, PassManagerBase &pm, TCETargetMachinePlugin *plugin)
virtual bool addPreISel ()
virtual bool addInstSelector ()
virtual void addPreRegAlloc ()
virtual void addPreSched2 ()
Public Attributes
TCETargetMachinePlugin * plugin_
Detailed Description
Definition at line 81 of file TCETargetMachine.hh.
Constructor & Destructor Documentation
TCEPassConfig()
llvm::TCEPassConfig::TCEPassConfig (LLVMTargetMachine * tm, PassManagerBase & pm, TCETargetMachinePlugin * plugin) inline
Definition at line 83 of file TCETargetMachine.hh.
                                        :
        TargetPassConfig(*tm, pm),
plugin_(plugin) {
        assert(plugin_ != NULL);
    }
References assert, and plugin_.
Member Function Documentation
addInstSelector()
bool TCEPassConfig::addInstSelector () virtual
Creates an instruction selector instance.
Definition at line 256 of file TCETargetMachine.cc.
{
    addPass(plugin_->createISelPass(static_cast<TCETargetMachine*>(TM)));
    return false;
}
References addPass, llvm::TCETargetMachinePlugin::createISelPass(), and plugin_.
addPreISel()
bool TCEPassConfig::addPreISel () virtual
Definition at line 274 of file TCETargetMachine.cc.
{
    LLVMTCECmdLineOptions* options =
        dynamic_cast<LLVMTCECmdLineOptions*>(Application::cmdLineOptions());
    if (options != NULL && !options->disableHWLoops() &&
        ((static_cast<TCETargetMachine*>(TM))->ttaMach_)
            ->hasOperation("hwloop"))
        #ifdef LLVM_OLDER_THAN_17
            addPass(createHardwareLoopsPass());
        #else
            addPass(createHardwareLoopsLegacyPass());
        #endif
    // lower floating point stuff.. maybe could use plugin as param instead machine...
    addPass(createLowerMissingInstructionsPass(
                *((static_cast<TCETargetMachine*>(TM))->ttaMach_)));
    if ((static_cast<TCETargetMachine*>(TM))->emulationModule_ != NULL) {
        addPass(createLinkBitcodePass(
                  *((static_cast<TCETargetMachine*>(TM))->emulationModule_)));
    }
    CodeGenOpt::Level OptLevel = getOptLevel();
    // NOTE: This must be added before Machine function analysis pass..
    // needed by POMBuilder to prevent writing debug data to data section
    // might be good to disable when printing out machine function code...
    // However, it need to comment out to support debug info
//    PM.add(createStripSymbolsPass(/*bool OnlyDebugInfo=*/true));
    return false;
}
References addPass, Application::cmdLineOptions(), createLinkBitcodePass(), createLowerMissingInstructionsPass(), and options.
addPreRegAlloc()
void TCEPassConfig::addPreRegAlloc () virtual
Some extra passes needed by TCE
Parameters
pm Function pass manager to add isel pass.
fast Not used.
Definition at line 269 of file TCETargetMachine.cc.
{
}
addPreSched2()
void TCEPassConfig::addPreSched2 () virtual
Definition at line 463 of file TCETargetMachine.cc.
{
    addPass(&IfConverterID);
}
References addPass.
Member Data Documentation
plugin_
TCETargetMachinePlugin* llvm::TCEPassConfig::plugin_
Definition at line 98 of file TCETargetMachine.hh.
Referenced by addInstSelector(), and TCEPassConfig().
The documentation for this class was generated from the following files:
TCETargetMachine.hh
TCETargetMachine.cc