OpenASIP: CostEstimator::CostEstimationPluginRegistry< T > Class Template Reference
CostEstimator::CostEstimationPluginRegistry< T > Class Template Reference
#include <CostEstimationPluginRegistry.hh>
Public Member Functions
CostEstimationPluginRegistry ()
virtual ~CostEstimationPluginRegistry ()
T & plugin (const std::string &pluginFileName, const std::string &pluginName)
Private Types
typedef std::map< std::string, T * > PluginRegistry
type of the index of accessible plugins, maps the plugin file path to the plugin
Private Attributes
PluginRegistry registry_
index of accessible plugins, maps the plugin file path to the plugin
PluginTools pluginTools_
the plugin tools instance used to access the plugin files
Detailed Description
template<typename T>
class CostEstimator::CostEstimationPluginRegistry< T >
Templated helper class for storing, accessing and caching of different types of cost estimation plugins.
The template parameter T is the type of the plugin to store.
Definition at line 51 of file CostEstimationPluginRegistry.hh.
Member Typedef Documentation
PluginRegistry
template<typename T > typedef std::map<std::string, T*> CostEstimator::CostEstimationPluginRegistry< T >::PluginRegistry private
type of the index of accessible plugins, maps the plugin file path to the plugin
Definition at line 61 of file CostEstimationPluginRegistry.hh.
Constructor & Destructor Documentation
CostEstimationPluginRegistry()
template<typename T > CostEstimator::CostEstimationPluginRegistry< T >::CostEstimationPluginRegistry ()
~CostEstimationPluginRegistry()
template<typename T > virtual CostEstimator::CostEstimationPluginRegistry< T >::~CostEstimationPluginRegistry () virtual
Member Function Documentation
plugin()
template<typename T > T & CostEstimator::CostEstimationPluginRegistry< T >::plugin (const std::string & pluginFileName, const std::string & pluginName)
Referenced by CostEstimator::Estimator::estimateSocketToSocketDelayOfPath(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), CostEstimator::Estimator::icArea(), CostEstimator::Estimator::icEnergy(), and CostEstimator::Estimator::rfCostFunctionPluginOfImplementation().
Member Data Documentation
pluginTools_
template<typename T > PluginTools CostEstimator::CostEstimationPluginRegistry< T >::pluginTools_ private
the plugin tools instance used to access the plugin files
Definition at line 66 of file CostEstimationPluginRegistry.hh.
registry_
template<typename T > PluginRegistry CostEstimator::CostEstimationPluginRegistry< T >::registry_ private
index of accessible plugins, maps the plugin file path to the plugin
Definition at line 64 of file CostEstimationPluginRegistry.hh.
The documentation for this class was generated from the following file:
CostEstimationPluginRegistry.hh