OpenASIP: ConditionScript Class Reference
ConditionScript Class Reference
#include <ConditionScript.hh>
Public Member Functions
ConditionScript (ScriptInterpreter *interpreter, std::string scriptLine)
ConditionScript (ScriptInterpreter *interpreter, std::vector< std::string > &script)
virtual ~ConditionScript ()
virtual bool conditionOk ()
virtual ConditionScript * copy () const
Public Member Functions inherited from Script
Script (ScriptInterpreter *interpreter, std::string scriptLine)
Script (ScriptInterpreter *interpreter, std::vector< std::string > &script)
virtual ~Script ()
virtual DataObject execute ()
DataObject lastResult ()
virtual std::vector< std::string > script () const
Additional Inherited Members
Protected Attributes inherited from Script
ScriptInterpreter * interpreter_
Interpreter executing the commands.
Detailed Description
Class that contains a script that defines a condition for some action.
Definition at line 45 of file ConditionScript.hh.
Constructor & Destructor Documentation
ConditionScript() [1/2]
ConditionScript::ConditionScript (ScriptInterpreter * interpreter, std::string scriptLine)
Constructor.
Parameters
interpreter Interpreter for the script.
scriptLine A line of script.
Definition at line 46 of file ConditionScript.cc.
                          : Script(interpreter, scriptLine) {
}
ConditionScript() [2/2]
ConditionScript::ConditionScript (ScriptInterpreter * interpreter, std::vector< std::string > & script)
Constructor.
Parameters
interpreter Interpreter for the script.
script The script.
Definition at line 57 of file ConditionScript.cc.
                                  : Script(interpreter, script) {
}
~ConditionScript()
ConditionScript::~ConditionScript () virtual
Destructor.
Definition at line 65 of file ConditionScript.cc.
{
}
Member Function Documentation
conditionOk()
bool ConditionScript::conditionOk () virtual
Tests if condition is true of false.
Returns
True, if condition is true, false otherwise.
Exceptions
NumberFormatException If DataObject operation fails.
ScriptExecutionFailure If script execution fails.
Definition at line 76 of file ConditionScript.cc.
{
    vector<string> scripts = script();
    if (scripts.size() == 1 && scripts[0] == "") {
        return true;
    }
    DataObject obj = execute();
    if (obj.stringValue() == "0") {
        interpreter_->setResult("");
        return false;
    }
    interpreter_->setResult("");
    return true;
}
References Script::execute(), Script::interpreter_, Script::script(), ScriptInterpreter::setResult(), and DataObject::stringValue().
Referenced by StopPoint::isConditionOK().
copy()
ConditionScript * ConditionScript::copy () const virtual
Copies the condition script.
Allows dynamically bound copy.
Returns
a new instance which is identical to this.
Reimplemented in TclConditionScript.
Definition at line 99 of file ConditionScript.cc.
{
    return new ConditionScript(*this);
}
Referenced by Breakpoint::copy(), Watch::copy(), and StopPoint::setCondition().
The documentation for this class was generated from the following files:
ConditionScript.hh
ConditionScript.cc