OpenASIP: KeyboardShortcut Class Reference
KeyboardShortcut Class Reference
#include <KeyboardShortcut.hh>
Public Member Functions
KeyboardShortcut (const std::string &action, int fKey, bool ctrl, bool alt, char key)
KeyboardShortcut (const ObjectState *state)
KeyboardShortcut (const KeyboardShortcut &old)
virtual ~KeyboardShortcut ()
std::string action () const
int fKey () const
bool ctrl () const
bool alt () const
char key () const
void setFKey (int fKey)
void setCtrl (bool ctrl)
void setAlt (bool alt)
void setKey (char key)
bool equals (const KeyboardShortcut &sc) const
void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_KEYBOARD_SHORTCUT = "keybsc"
ObjectState name for keyboard shortcut.
static const std::string OSKEY_ACTION = "action"
ObjectState attribute key for action name.
static const std::string OSKEY_FKEY = "fkey"
ObjectState attribute key for function key number.
static const std::string OSKEY_CTRL = "ctrl"
ObjectState attribute key for ctrl key.
static const std::string OSKEY_ALT = "alt"
ObjectState attribute key for alt key.
static const std::string OSKEY_KEY = "key"
ObjectState attribute key for normal letter or number key.
Private Member Functions
KeyboardShortcut & operator= (const KeyboardShortcut)
Assigment forbidden.
Private Attributes
std::string action_
Name of the action which is performed by the key combination.
int fKey_
Number of the function key if it is used, 0 otherwise.
bool ctrl_
True if Ctrl button is used in the key combination.
bool alt_
True if Alt button is used in the key combination.
char key_
Detailed Description
This class stores the keyboard buttons used in a keyboard shortcut.
It contains also the name of the action performed by the key combination. This class implements the Serializable interface because keyboard shortcuts are serialized into the configuration file.
Definition at line 50 of file KeyboardShortcut.hh.
Constructor & Destructor Documentation
KeyboardShortcut() [1/3]
KeyboardShortcut::KeyboardShortcut (const std::string & action, int fKey, bool ctrl, bool alt, char key)
Constructor.
Parameters
action Name of the action performed by the key combination.
fKey Number of the function key used in the shortcut, if the value is not between 1 and 12 it is ignored and any function key won't be used.
ctrl True if the Ctrl button is used.
alt True if the Alt button is used.
key Character used in the key combination, NUL character if no character is used. If delete is used, apply ascii 127.
Definition at line 60 of file KeyboardShortcut.cc.
             :
    action_(action), fKey_(fKey), ctrl_(ctrl), alt_(alt), key_(key) {
    // validity checks
    if (key < '0' && key != 0) {
        assert(false);
    }
    if (key > '9' && key < 'A') {
        assert(false);
    }
    if (key > 'Z' && key < 'a') {
        assert(false);
    }
    if (key > 'z' && key != 127) {
        assert(false);
    }
    // if key is lower case letter, convert it to lower case
    if (key_ >= 'a' && key_ <= 'z') {
        key_ -= 32;
    }
    // validity checks
    if (this->fKey() != 0) {
        assert(this->key() == 0);
    }
    if (this->key() != 0) {
        assert(this->fKey() == 0);
        assert(ctrl_ == true || alt_ == true);
    }
}
References alt_, assert, ctrl_, fKey(), key(), and key_.
KeyboardShortcut() [2/3]
KeyboardShortcut::KeyboardShortcut (const ObjectState * state)
Constructor.
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState from which the state is loaded.
Definition at line 105 of file KeyboardShortcut.cc.
{
    loadState(state);
}
References loadState().
KeyboardShortcut() [3/3]
KeyboardShortcut::KeyboardShortcut (const KeyboardShortcut & old)
Copy constructor.
Definition at line 113 of file KeyboardShortcut.cc.
                                : Serializable() {
    action_ = old.action_;
    fKey_ = old.fKey_;
    ctrl_ = old.ctrl_;
    alt_ = old.alt_;
    key_ = old.key_;
}
References action_, alt_, ctrl_, fKey_, and key_.
~KeyboardShortcut()
KeyboardShortcut::~KeyboardShortcut () virtual
Destructor.
Definition at line 127 of file KeyboardShortcut.cc.
{
}
Member Function Documentation
action()
std::string KeyboardShortcut::action () const
Returns the name of the action performed by this key combination.
Returns
Name of the action performed by this key combination.
Definition at line 137 of file KeyboardShortcut.cc.
{
    return action_;
}
References action_.
Referenced by OptionsDialog::readOptions(), and GUIOptions::validate().
alt()
bool KeyboardShortcut::alt () const
Returns true if Alt button is used in the key combination.
Returns
True if Alt button is used in the key combination, otherwise false.
Definition at line 177 of file KeyboardShortcut.cc.
{
    return alt_;
}
References alt_.
Referenced by ProximMainFrame::menuAccelerator(), MainFrame::menuAccelerator(), setAlt(), and KeyboardShortcutDialog::TransferDataToWindow().
ctrl()
bool KeyboardShortcut::ctrl () const
Returns true if Ctrl button is used in the key combination.
Returns
True if Ctrl button is used in the key combination, otherwise false.
Definition at line 165 of file KeyboardShortcut.cc.
{
    return ctrl_;
}
References ctrl_.
Referenced by ProximMainFrame::menuAccelerator(), MainFrame::menuAccelerator(), setCtrl(), and KeyboardShortcutDialog::TransferDataToWindow().
equals()
bool KeyboardShortcut::equals (const KeyboardShortcut & sc) const
Returns true if the given keyboard shortcut has the same key combination as this.
Parameters
sc Keyboard shortcut.
Returns
True if the given keyboard shortcut has the same key combination as this.
Definition at line 250 of file KeyboardShortcut.cc.
{
    if (ctrl_ == sc.ctrl_ && alt_ == sc.alt_ && key_ == sc.key_ &&
        fKey() == sc.fKey()) {
        return true;
    } else {
        return false;
    }
}
References alt_, ctrl_, fKey(), and key_.
Referenced by GUIOptions::validate().
fKey()
int KeyboardShortcut::fKey () const
Returns the number of the function key used in the key combination.
Returns
Number of the function key used in the key combination, 0 if no function key is used.
Definition at line 149 of file KeyboardShortcut.cc.
{
    if (fKey_ < 1 || fKey_ > 12) {
        return 0;
    } else {
        return fKey_;
    }
}
References fKey_.
Referenced by equals(), KeyboardShortcut(), ProximMainFrame::menuAccelerator(), MainFrame::menuAccelerator(), saveState(), setFKey(), and KeyboardShortcutDialog::TransferDataToWindow().
key()
char KeyboardShortcut::key () const
Returns the character used in the key combination or NUL character if no character is used.
Returns
The character used in the key combination or NUL character if no character is used.
Definition at line 190 of file KeyboardShortcut.cc.
{
    return key_;
}
References key_.
Referenced by KeyboardShortcut(), ProximMainFrame::menuAccelerator(), MainFrame::menuAccelerator(), setKey(), and KeyboardShortcutDialog::TransferDataToWindow().
loadState()
void KeyboardShortcut::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Implements Serializable.
Definition at line 268 of file KeyboardShortcut.cc.
{
    const string procName = "KeyboardShortcut::loadState";
    if (state->name() != OSNAME_KEYBOARD_SHORTCUT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        action_ = state->stringAttribute(OSKEY_ACTION);
        if (state->hasAttribute(OSKEY_FKEY)) {
            fKey_ = state->intAttribute(OSKEY_FKEY);
        } else {
            fKey_ = 0;
        }
        ctrl_ = state->intAttribute(OSKEY_CTRL);
        alt_ = state->intAttribute(OSKEY_ALT);
        if (state->hasAttribute(OSKEY_KEY)) {
            key_ = state->intAttribute(OSKEY_KEY);
            // convert to upper case if lower case
            if (key_ >= 'a' && key_ <= 'z') {
                key_ -= 32;
            }
        } else {
            key_ = 0;
        }
    } catch (...) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References action_, alt_, ctrl_, fKey_, ObjectState::hasAttribute(), ObjectState::intAttribute(), key_, ObjectState::name(), OSKEY_ACTION, OSKEY_ALT, OSKEY_CTRL, OSKEY_FKEY, OSKEY_KEY, OSNAME_KEYBOARD_SHORTCUT, and ObjectState::stringAttribute().
Referenced by KeyboardShortcut().
operator=()
KeyboardShortcut & KeyboardShortcut::operator= (const KeyboardShortcut) private
Assigment forbidden.
saveState()
ObjectState * KeyboardShortcut::saveState () const virtual
Creates an ObjectState object and saves the state of the object into it.
Returns
The created ObjectState object.
Implements Serializable.
Definition at line 310 of file KeyboardShortcut.cc.
{
    ObjectState* state = new ObjectState(OSNAME_KEYBOARD_SHORTCUT);
    state->setAttribute(OSKEY_ACTION, action_);
    // if function key is used
    if (fKey() != 0) {
        state->setAttribute(OSKEY_FKEY, fKey());
    }
    state->setAttribute(OSKEY_CTRL, ctrl_);
    state->setAttribute(OSKEY_ALT, alt_);
    // if key is not nul character
    if (key_ != 0) {
        state->setAttribute(OSKEY_KEY, key_);
    }
    return state;
}
References action_, alt_, ctrl_, fKey(), key_, OSKEY_ACTION, OSKEY_ALT, OSKEY_CTRL, OSKEY_FKEY, OSKEY_KEY, OSNAME_KEYBOARD_SHORTCUT, and ObjectState::setAttribute().
Referenced by GUIOptions::saveState().
setAlt()
void KeyboardShortcut::setAlt (bool alt)
Sets alt-button state of the shortcut.
Parameters
alt Alt-button state of the shortcut.
Definition at line 212 of file KeyboardShortcut.cc.
{
    alt_ = alt;
}
References alt(), and alt_.
Referenced by KeyboardShortcutDialog::onCharEvent().
setCtrl()
void KeyboardShortcut::setCtrl (bool ctrl)
Sets control button state of the shortcut.
Parameters
ctrl Ctrl-button state of the shortcut.
Definition at line 201 of file KeyboardShortcut.cc.
{
    ctrl_ = ctrl;
}
References ctrl(), and ctrl_.
Referenced by KeyboardShortcutDialog::onCharEvent().
setFKey()
void KeyboardShortcut::setFKey (int fKey)
Sets the function key of the keyboard shortcut. Set as 0 if the shortcut doesn't use function key.
Parameters
key Function key of the shortcut.
Definition at line 233 of file KeyboardShortcut.cc.
{
    if (fKey < 0 || fKey > 12) {
        fKey = 0;
    } else {
        fKey_ = fKey;
    }
}
References fKey(), and fKey_.
Referenced by KeyboardShortcutDialog::onCharEvent().
setKey()
void KeyboardShortcut::setKey (char key)
Sets the character key of the keyboard shortcut.
Parameters
key Character key of the shortcut.
Definition at line 222 of file KeyboardShortcut.cc.
{
    key_ = key;
}
References key(), and key_.
Referenced by KeyboardShortcutDialog::onCharEvent().
Member Data Documentation
action_
std::string KeyboardShortcut::action_ private
Name of the action which is performed by the key combination.
Definition at line 93 of file KeyboardShortcut.hh.
Referenced by action(), KeyboardShortcut(), loadState(), and saveState().
alt_
bool KeyboardShortcut::alt_ private
True if Alt button is used in the key combination.
Definition at line 99 of file KeyboardShortcut.hh.
Referenced by alt(), equals(), KeyboardShortcut(), KeyboardShortcut(), loadState(), saveState(), and setAlt().
ctrl_
bool KeyboardShortcut::ctrl_ private
True if Ctrl button is used in the key combination.
Definition at line 97 of file KeyboardShortcut.hh.
Referenced by ctrl(), equals(), KeyboardShortcut(), KeyboardShortcut(), loadState(), saveState(), and setCtrl().
fKey_
int KeyboardShortcut::fKey_ private
Number of the function key if it is used, 0 otherwise.
Definition at line 95 of file KeyboardShortcut.hh.
Referenced by fKey(), KeyboardShortcut(), loadState(), and setFKey().
key_
char KeyboardShortcut::key_ private
ASCII character of the button used in the key combination, if the key is not used the value is a NUL character (ASCII 0).
Definition at line 104 of file KeyboardShortcut.hh.
Referenced by equals(), key(), KeyboardShortcut(), KeyboardShortcut(), loadState(), saveState(), and setKey().
OSKEY_ACTION
const string KeyboardShortcut::OSKEY_ACTION = "action" static
ObjectState attribute key for action name.
Definition at line 55 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), and saveState().
OSKEY_ALT
const string KeyboardShortcut::OSKEY_ALT = "alt" static
ObjectState attribute key for alt key.
Definition at line 61 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), and saveState().
OSKEY_CTRL
const string KeyboardShortcut::OSKEY_CTRL = "ctrl" static
ObjectState attribute key for ctrl key.
Definition at line 59 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), and saveState().
OSKEY_FKEY
const string KeyboardShortcut::OSKEY_FKEY = "fkey" static
ObjectState attribute key for function key number.
Definition at line 57 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), and saveState().
OSKEY_KEY
const string KeyboardShortcut::OSKEY_KEY = "key" static
ObjectState attribute key for normal letter or number key.
Definition at line 63 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), and saveState().
OSNAME_KEYBOARD_SHORTCUT
const string KeyboardShortcut::OSNAME_KEYBOARD_SHORTCUT = "keybsc" static
ObjectState name for keyboard shortcut.
Definition at line 53 of file KeyboardShortcut.hh.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptions::loadState(), loadState(), and saveState().
The documentation for this class was generated from the following files:
KeyboardShortcut.hh
KeyboardShortcut.cc