OpenASIP: CompiledSimSymbolGenerator Class Reference
CompiledSimSymbolGenerator Class Reference
#include <CompiledSimSymbolGenerator.hh>
Public Member Functions
CompiledSimSymbolGenerator (const TCEString &globalSymbolSuffix)
virtual ~CompiledSimSymbolGenerator ()
void enablePrefix (const std::string &prefix)
void disablePrefix ()
std::string timeStamp () const
std::string portSymbol (const TTAMachine::Port &port) const
std::string registerSymbol (const TTAProgram::Terminal &terminal) const
std::string registerSymbol (const TTAMachine::RegisterFile &rf, int index) const
std::string immediateRegisterSymbol (const TTAProgram::Terminal &terminal) const
std::string immediateRegisterSymbol (const TTAMachine::ImmediateUnit &iu, int index) const
std::string busSymbol (const TTAMachine::Bus &bus) const
std::string returnAddressSymbol (const TTAMachine::ControlUnit &gcu) const
std::string moveOperandSymbol (const TTAProgram::Terminal &terminal, const TTAProgram::Move &move) const
std::string operationContextSymbol (const TTAMachine::FunctionUnit &fu) const
std::string conflictDetectorSymbol (const TTAMachine::FunctionUnit &fu) const
std::string targetMemorySymbol (const TTAMachine::FunctionUnit &fu) const
std::string DAMemorySymbol (const TTAMachine::FunctionUnit &fu) const
std::string guardBoolSymbol () const
std::string basicBlockSymbol (InstructionAddress startAddress) const
std::string operationSymbol (const std::string &operationName, const TTAMachine::FunctionUnit &fu) const
std::string FUResultSymbol (const TTAMachine::Port &port) const
std::string generateTempVariable () const
std::string jumpTargetSetterSymbol (InstructionAddress address) const
Private Member Functions
CompiledSimSymbolGenerator (const CompiledSimSymbolGenerator &)
Copying not allowed.
CompiledSimSymbolGenerator & operator= (const CompiledSimSymbolGenerator &)
Assignment not allowed.
Private Attributes
TCEString prefix_
Prefix used for generated variable symbols.
TCEString globalSymbolSuffix_
Suffix used for the generated global function symbols.
Detailed Description
A class that generates C/C++ symbol names for given objects in the simulation
Used for the compiled simulation
Definition at line 66 of file CompiledSimSymbolGenerator.hh.
Constructor & Destructor Documentation
CompiledSimSymbolGenerator() [1/2]
CompiledSimSymbolGenerator::CompiledSimSymbolGenerator (const TCEString & globalSymbolSuffix)
Default constructor.
Parameters
globalSymbolSuffix Can be used to produce unique symbol names for the global BB simulation functions. This has to be used in case using multiple simulation engines in the same process.
Definition at line 62 of file CompiledSimSymbolGenerator.cc.
                                         :
    globalSymbolSuffix_(globalSymbolSuffix) {
}
~CompiledSimSymbolGenerator()
CompiledSimSymbolGenerator::~CompiledSimSymbolGenerator () virtual
Default destructor
Definition at line 70 of file CompiledSimSymbolGenerator.cc.
{
}
CompiledSimSymbolGenerator() [2/2]
CompiledSimSymbolGenerator::CompiledSimSymbolGenerator (const CompiledSimSymbolGenerator &) private
Copying not allowed.
Member Function Documentation
basicBlockSymbol()
std::string CompiledSimSymbolGenerator::basicBlockSymbol (InstructionAddress startAddress) const
Generates an unique symbol name for a basic block function
A new C/C++ function is created for each basic block in the program, so the generated symbol will also be used as the generated function name.
Parameters
startAddress The start address of the basic block
Returns
A string containing the generated symbol name
Definition at line 320 of file CompiledSimSymbolGenerator.cc.
          {
    return "simulate_" + globalSymbolSuffix_ + "_" + Conversion::toString(startAddress);
}
References globalSymbolSuffix_, and Conversion::toString().
Referenced by CompiledSimulation::compileAndLoadFunction(), CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateInstruction(), and CompiledSimCodeGenerator::generateJumpTableCode().
busSymbol()
std::string CompiledSimSymbolGenerator::busSymbol (const TTAMachine::Bus & bus) const
Generates an unique symbol name for a TTA machine bus
Parameters
bus The given bus
Returns
A string containing the generated symbol name
Definition at line 205 of file CompiledSimSymbolGenerator.cc.
{
    return prefix_ + "bus_" + bus.name();
}
References TTAMachine::Component::name(), and prefix_.
Referenced by CompiledSimMove::copyFromBusCode(), CompiledSimMove::copyToBusCode(), and CompiledSimCodeGenerator::generateHeaderAndMainCode().
conflictDetectorSymbol()
std::string CompiledSimSymbolGenerator::conflictDetectorSymbol (const TTAMachine::FunctionUnit & fu) const
Generates an unique symbol name for a given FU conflict detector.
Parameters
fu The given function unit
Returns
std::string containing the generated symbol name
Definition at line 270 of file CompiledSimSymbolGenerator.cc.
{
    return prefix_ + "FU_" + fu.name() + "_conflict_detector";
}
References TTAMachine::Component::name(), and prefix_.
Referenced by ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), and ConflictDetectionCodeGenerator::symbolDeclaration().
DAMemorySymbol()
std::string CompiledSimSymbolGenerator::DAMemorySymbol (const TTAMachine::FunctionUnit & fu) const
Generates an unique symbol name for the given FU's DirectAccessMemory&
Parameters
fuName Given function unit
Returns
A string containing the generated symbol name
Definition at line 294 of file CompiledSimSymbolGenerator.cc.
          {
    return prefix_ + fu.name() + "_direct_access_memory";
}
References TTAMachine::Component::name(), and prefix_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateStoreTrigger(), and CompiledSimCodeGenerator::updateDeclaredSymbolsList().
disablePrefix()
void CompiledSimSymbolGenerator::disablePrefix ()
Disables the usage of prefix.
Definition at line 87 of file CompiledSimSymbolGenerator.cc.
{
    prefix_ = "";
}
References prefix_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateSymbolDeclarations(), and CompiledSimCodeGenerator::updateDeclaredSymbolsList().
enablePrefix()
void CompiledSimSymbolGenerator::enablePrefix (const std::string & prefix)
Sets a new prefix to be used for generated variable symbols
Parameters
prefix new prefix to be set
Definition at line 79 of file CompiledSimSymbolGenerator.cc.
{
    prefix_ = prefix;
}
References prefix_.
Referenced by CompiledSimCodeGenerator::generateFUOutputUpdater(), and CompiledSimCodeGenerator::generateInstruction().
FUResultSymbol()
std::string CompiledSimSymbolGenerator::FUResultSymbol (const TTAMachine::Port & port) const
Generates an unique symbol name for FU's results.
Parameters
port The FU port
Returns
A string containing the generated FU results symbol
Definition at line 346 of file CompiledSimSymbolGenerator.cc.
{
    return portSymbol(port) + "_results";
}
References portSymbol().
Referenced by CompiledSimCodeGenerator::generateAddFUResult(), CompiledSimCodeGenerator::generateFUOutputUpdater(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateInstruction(), and CompiledSimCodeGenerator::updateDeclaredSymbolsList().
generateTempVariable()
std::string CompiledSimSymbolGenerator::generateTempVariable () const
Generates name for temporary variables using incremental numbers
Returns
The generated temporary variable name
Definition at line 356 of file CompiledSimSymbolGenerator.cc.
{
    static int counter = 0;
    return "_tmp_variable_" + Conversion::toString(counter++);
}
References Conversion::toString().
Referenced by CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateTriggerCode(), and CompiledSimCodeGenerator::handleOperationWithoutDag().
guardBoolSymbol()
std::string CompiledSimSymbolGenerator::guardBoolSymbol () const
Generates an unique symbol name for a temporary guard variable
Returns
A string containing the generated symbol name
Definition at line 305 of file CompiledSimSymbolGenerator.cc.
{
    static int guardNumber = 0;
    return "guard_" + Conversion::toString(guardNumber++);
}
References Conversion::toString().
Referenced by CompiledSimCodeGenerator::generateGuardCondition(), and CompiledSimCodeGenerator::generateGuardRead().
immediateRegisterSymbol() [1/2]
std::string CompiledSimSymbolGenerator::immediateRegisterSymbol (const TTAMachine::ImmediateUnit & iu, int index) const
Generates an unique symbol name for a IU register
Parameters
iu The given IU
index Index of the immediate register
Returns
A string containing the generated symbol name
Definition at line 191 of file CompiledSimSymbolGenerator.cc.
                     {
    return prefix_ + "IU_" + DisassemblyRegister::registerName(iu, index, '_');
    //.name() + "_" + Conversion::toString(index);
}
References prefix_, and DisassemblyRegister::registerName().
immediateRegisterSymbol() [2/2]
std::string CompiledSimSymbolGenerator::immediateRegisterSymbol (const TTAProgram::Terminal & terminal) const
Generates an unique symbol name for a IU register of the terminal
Parameters
terminal Given terminal
Returns
A string containing the generated symbol name
Definition at line 178 of file CompiledSimSymbolGenerator.cc.
{
    return immediateRegisterSymbol(terminal.immediateUnit(), terminal.index());
}
References immediateRegisterSymbol(), TTAProgram::Terminal::immediateUnit(), and TTAProgram::Terminal::index().
Referenced by CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateInstruction(), immediateRegisterSymbol(), CompiledSimulation::immediateUnitRegisterValue(), and moveOperandSymbol().
jumpTargetSetterSymbol()
std::string CompiledSimSymbolGenerator::jumpTargetSetterSymbol (InstructionAddress address) const
Generates name for jump target setting function
Parameters
address address of the simulate function to be set
Definition at line 367 of file CompiledSimSymbolGenerator.cc.
{
    return "setJumpTargetFor_" + Conversion::toString(address);
}
References Conversion::toString().
moveOperandSymbol()
std::string CompiledSimSymbolGenerator::moveOperandSymbol (const TTAProgram::Terminal & terminal, const TTAProgram::Move & move) const
Generates an unique symbol name for a given move operand (terminal)
Parameters
terminal The operand terminal
move The move
Returns
a string containing the generated symbol name
Definition at line 228 of file CompiledSimSymbolGenerator.cc.
{
    if (terminal.isGPR()) {
        return registerSymbol(terminal);
    } else if (terminal.isImmediateRegister()) {
        return immediateRegisterSymbol(terminal);
    } else if (terminal.isImmediate()) {
        int value = terminal.value().unsignedValue();
        const Bus& bus = move.bus();
        if (bus.signExtends()) {
            value = MathTools::signExtendTo(value, bus.immediateWidth());
        }
        else if (bus.zeroExtends()) {
            value = MathTools::zeroExtendTo(value, bus.immediateWidth());
        }
        return "(int)" + Conversion::toString(value) + "u";
    } else {
        return portSymbol(terminal.port());
    }
}
References TTAProgram::Move::bus(), immediateRegisterSymbol(), TTAMachine::Bus::immediateWidth(), TTAProgram::Terminal::isGPR(), TTAProgram::Terminal::isImmediate(), TTAProgram::Terminal::isImmediateRegister(), TTAProgram::Terminal::port(), portSymbol(), registerSymbol(), TTAMachine::Bus::signExtends(), MathTools::signExtendTo(), Conversion::toString(), SimValue::unsignedValue(), TTAProgram::Terminal::value(), TTAMachine::Bus::zeroExtends(), and MathTools::zeroExtendTo().
Referenced by CompiledSimMove::copyFromBusCode(), CompiledSimMove::copyToBusCode(), and CompiledSimCodeGenerator::generateInstruction().
operationContextSymbol()
std::string CompiledSimSymbolGenerator::operationContextSymbol (const TTAMachine::FunctionUnit & fu) const
Generates an unique symbol name for a given operation context
Parameters
fu The given function unit
Returns
a string containing the generated symbol name
Definition at line 258 of file CompiledSimSymbolGenerator.cc.
{
    return prefix_ + "FU_" + fu.name() + "_context";
}
References TTAMachine::Component::name(), and prefix_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::handleOperation(), and CompiledSimCodeGenerator::handleOperationWithoutDag().
operationSymbol()
std::string CompiledSimSymbolGenerator::operationSymbol (const std::string & operationName, const TTAMachine::FunctionUnit & fu) const
Generates an unique symbol name for a FU's operation
Parameters
operationName Name of the operation
fu The function unit containing the operation
Returns
The generated operation symbol string
Definition at line 333 of file CompiledSimSymbolGenerator.cc.
{
    return prefix_ + "op_" + fu.name() + "_" + operationName;
}
References TTAMachine::Component::name(), and prefix_.
Referenced by CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), and CompiledSimCodeGenerator::handleOperationWithoutDag().
operator=()
CompiledSimSymbolGenerator & CompiledSimSymbolGenerator::operator= (const CompiledSimSymbolGenerator &) private
Assignment not allowed.
portSymbol()
std::string CompiledSimSymbolGenerator::portSymbol (const TTAMachine::Port & port) const
Generates an unique symbol name for the given port
Converts a TTA unit's port to a unique symbol name that can be later referred as a SimValue variable in the generated C/C++ code.
Parameters
port A port of the TTA unit
Returns
A string containing the generated symbol name
Definition at line 117 of file CompiledSimSymbolGenerator.cc.
{
    string symbolName;
    // just speed opt. no need to reserve more at every append.
    symbolName = prefix_;
    symbolName.reserve(40);
    Unit* unit = port.parentUnit();
    if (dynamic_cast<const FunctionUnit*>(unit) != NULL) {
        symbolName += "FU_";
        if (dynamic_cast<const ControlUnit*>(unit) != NULL) {
            symbolName += "GCU_";
        }
    } else if (dynamic_cast<const RegisterFile*>(unit) != NULL) {
        symbolName += "RF_";
        if (dynamic_cast<const ImmediateUnit*>(unit) != NULL) {
            symbolName += "IU_";
        }
    } else {
        symbolName += "unknown_";
    }
    symbolName += unit->name();
    symbolName += "_";
    symbolName += port.name();
    return symbolName;
}
References TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::Port::parentUnit(), and prefix_.
Referenced by CompiledSimulation::FUPortValue(), FUResultSymbol(), CompiledSimCodeGenerator::generateAddFUResult(), CompiledSimCodeGenerator::generateFUOutputUpdater(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateStoreTrigger(), CompiledSimCodeGenerator::generateTriggerCode(), CompiledSimCodeGenerator::handleJump(), CompiledSimCodeGenerator::handleOperationWithoutDag(), moveOperandSymbol(), and returnAddressSymbol().
registerSymbol() [1/2]
std::string CompiledSimSymbolGenerator::registerSymbol (const TTAMachine::RegisterFile & rf, int index) const
Generates an unique symbol name for a RF register
Parameters
rf The given register file
index The index of the register
Returns
A string containing the generated symbol name
Definition at line 163 of file CompiledSimSymbolGenerator.cc.
                     {
    return prefix_ + "RF_" +
        DisassemblyRegister::registerName(rf, index, '_');
}
References prefix_, and DisassemblyRegister::registerName().
registerSymbol() [2/2]
std::string CompiledSimSymbolGenerator::registerSymbol (const TTAProgram::Terminal & terminal) const
Generates an unique symbol name for a RF register of the terminal
Parameters
terminal Given terminal
Returns
A string containing the generated symbol name
Definition at line 150 of file CompiledSimSymbolGenerator.cc.
{
    return registerSymbol(terminal.registerFile(), terminal.index());
}
References TTAProgram::Terminal::index(), TTAProgram::Terminal::registerFile(), and registerSymbol().
Referenced by CompiledSimCodeGenerator::CompiledSimCodeGenerator(), CompiledSimCodeGenerator::generateGuardCondition(), CompiledSimCodeGenerator::generateGuardRead(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateInstruction(), moveOperandSymbol(), CompiledSimulation::registerFileValue(), and registerSymbol().
returnAddressSymbol()
std::string CompiledSimSymbolGenerator::returnAddressSymbol (const TTAMachine::ControlUnit & gcu) const
Generates a symbol name for the GCU's return address
Returns
A symbol name for the GCU's return address
Definition at line 215 of file CompiledSimSymbolGenerator.cc.
{
    return portSymbol(*gcu.returnAddressPort());
}
References portSymbol(), and TTAMachine::ControlUnit::returnAddressPort().
Referenced by CompiledSimCodeGenerator::handleJump().
targetMemorySymbol()
std::string CompiledSimSymbolGenerator::targetMemorySymbol (const TTAMachine::FunctionUnit & fu) const
Generates an unique symbol name for the given FU's memory space
Parameters
fuName given function unit
Returns
A string containing the generated symbol name
Definition at line 282 of file CompiledSimSymbolGenerator.cc.
{
    return prefix_ + fu.name() + "_target_memory";
}
References TTAMachine::Component::name(), and prefix_.
timeStamp()
std::string CompiledSimSymbolGenerator::timeStamp () const
Generates a timestamp
Note
Should not be printed to the simulation sources as this makes ccache useless. There's always a cache miss due to the changing timestamp.
Returns
a string containing the timestamp
Definition at line 101 of file CompiledSimSymbolGenerator.cc.
{
    time_t rawTime;
    time(&rawTime);
    return string(ctime(&rawTime));
}
Member Data Documentation
globalSymbolSuffix_
TCEString CompiledSimSymbolGenerator::globalSymbolSuffix_ private
Suffix used for the generated global function symbols.
Definition at line 133 of file CompiledSimSymbolGenerator.hh.
Referenced by basicBlockSymbol().
prefix_
TCEString CompiledSimSymbolGenerator::prefix_ private
Prefix used for generated variable symbols.
Definition at line 130 of file CompiledSimSymbolGenerator.hh.
Referenced by busSymbol(), conflictDetectorSymbol(), DAMemorySymbol(), disablePrefix(), enablePrefix(), immediateRegisterSymbol(), operationContextSymbol(), operationSymbol(), portSymbol(), registerSymbol(), and targetMemorySymbol().
The documentation for this class was generated from the following files:
CompiledSimSymbolGenerator.hh
CompiledSimSymbolGenerator.cc