OpenASIP: BitVector Class Reference
BitVector Class Reference
#include <BitVector.hh>
Public Member Functions
BitVector ()
BitVector (const BitVector &vector, unsigned int firstIndex, unsigned int lastIndex)
virtual ~BitVector ()
void pushBack (long long unsigned int integer, int size)
void pushBack (const BitVector &bits)
void pushBack (bool bit)
std::string toString () const
Detailed Description
BitVector is a specialization of STL's bit vector. It provides some handy helper methods.
Definition at line 44 of file BitVector.hh.
Constructor & Destructor Documentation
BitVector() [1/2]
BitVector::BitVector ()
The constructor.
Definition at line 44 of file BitVector.cc.
                     {
}
BitVector() [2/2]
BitVector::BitVector (const BitVector & vector, unsigned int firstIndex, unsigned int lastIndex)
The constructor.
Creates a bit vector that is a sub vector of the given vector.
Parameters
vector The bit vector.
firstIndex The index of the given vector that is to be the first element in the created vector.
lastIndex The index of the given vector that is to be that last element in the created vector.
Exceptions
OutOfRange If the given indexes are too big or too small.
Definition at line 60 of file BitVector.cc.
{
    if (lastIndex < firstIndex || lastIndex >= vector.size()) {
        const string procName = "BitVector::BitVector";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    BitVector::const_iterator firstIter = vector.begin();
    firstIter += firstIndex;
    BitVector::const_iterator lastIter = vector.begin();
    lastIter += lastIndex + 1;
    insert(begin(), firstIter, lastIter);
    assert(size() == lastIndex - firstIndex + 1);
}
References assert.
~BitVector()
BitVector::~BitVector () virtual
The destructor.
Definition at line 78 of file BitVector.cc.
                      {
}
Member Function Documentation
pushBack() [1/3]
void BitVector::pushBack (bool bit)
Pushes back the given bit.
Parameters
bit The bit to be added.
Definition at line 120 of file BitVector.cc.
{
    push_back(bit);
}
pushBack() [2/3]
void BitVector::pushBack (const BitVector & bits)
Pushes back the given bit vector.
Parameters
bits The bit vector.
Definition at line 107 of file BitVector.cc.
{
    reserve(size() + bits.size());
    for (std::vector<bool>::const_iterator iter = bits.begin();
         iter != bits.end(); iter++) {
        push_back(*iter);
    }
}
pushBack() [3/3]
void BitVector::pushBack (long long unsigned int integer, int size)
Pushes back the given number and increases the size of the vector by the given amount.
For example, if number 6 (110) is added with size 5, bits 00110 are concatenated to the vector. If size 2 is given, then bits 10 are concatenated to the vector.
Parameters
integer The number to be added.
size The number of bits to be added.
Definition at line 94 of file BitVector.cc.
{
    for (int i = size - 1; i >= 0; i--) {
        push_back(MathTools::bit(integer, i));
    }
}
References MathTools::bit().
Referenced by CodeCompressorPlugin::addBitsForDstRegisterField(), CodeCompressorPlugin::addBitsForGuardField(), CodeCompressorPlugin::addBitsForICField(), CodeCompressorPlugin::addBitsForImmediateSlot(), MoveSlotDictionary::addInstructions(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeNOP(), CodeCompressorPlugin::encodeRFTerminal(), CodeCompressorPlugin::encodeSlotField(), ProGe::RV32MicroCodeGenerator::initializeOperations(), InstructionBitVector::pushBack(), CodeCompressorPlugin::socketCodeBits(), and ProgramImageGenerator::writeDataSection().
toString()
std::string BitVector::toString () const
Converts BitVector to std::string format
Definition at line 130 of file BitVector.cc.
{
    std::string bits;
    for (unsigned int i = 0; i < this->size(); i++) {
        bits.append(std::to_string(this->at(i)));
    }
    return bits;
}
Referenced by ProGe::RV32MicroCodeGenerator::generateNOP(), and ProGe::RV32MicroCodeGenerator::initializeOperations().
The documentation for this class was generated from the following files:
BitVector.hh
BitVector.cc