OpenASIP: MachineCheckResults Class Reference
MachineCheckResults Class Reference
#include <MachineCheckResults.hh>
Public Types
typedef std::pair< const MachineCheck *, std::string > Error
Typedef for an error (error code + error message).
Public Member Functions
MachineCheckResults ()
virtual ~MachineCheckResults ()
int errorCount () const
Error error (int index) const
void addError (const MachineCheck &check, const std::string &errorMsg)
Private Types
typedef std::vector< Error > ErrorTable
Typedef for vector of errors.
Private Attributes
ErrorTable errors_
Contains the errors.
Detailed Description
Container for MachineCheck error messages.
Definition at line 46 of file MachineCheckResults.hh.
Member Typedef Documentation
Error
typedef std::pair<const MachineCheck*, std::string> MachineCheckResults::Error
Typedef for an error (error code + error message).
Definition at line 49 of file MachineCheckResults.hh.
ErrorTable
typedef std::vector<Error> MachineCheckResults::ErrorTable private
Typedef for vector of errors.
Definition at line 63 of file MachineCheckResults.hh.
Constructor & Destructor Documentation
MachineCheckResults()
MachineCheckResults::MachineCheckResults ()
The constructor.
Definition at line 39 of file MachineCheckResults.cc.
{
}
~MachineCheckResults()
MachineCheckResults::~MachineCheckResults () virtual
The destructor.
Definition at line 46 of file MachineCheckResults.cc.
{
}
Member Function Documentation
addError()
void MachineCheckResults::addError (const MachineCheck & check, const std::string & errorMsg)
Adds an error to the results.
Parameters
code The error code.
errorMsg The error message.
Definition at line 85 of file MachineCheckResults.cc.
{
    Error error(&check, errorMsg);
    errors_.push_back(error);
}
References error(), and errors_.
Referenced by AddressSpaceCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), RFPortCheck::check(), MinimalOpSetCheck::check(), RegisterQuantityCheck::checkPredRegs(), and RegisterQuantityCheck::missingIntRegs().
error()
MachineCheckResults::Error MachineCheckResults::error (int index) const
Returns an error by the given index.
Parameters
index The index.
Returns
The error.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 70 of file MachineCheckResults.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return errors_[index];
}
References __func__, errorCount(), and errors_.
Referenced by addError(), and MachineStateBuilder::buildMachineState().
errorCount()
int MachineCheckResults::errorCount () const
Returns the number of errors.
Returns
The number of errors.
Definition at line 56 of file MachineCheckResults.cc.
{
    return errors_.size();
}
References errors_.
Referenced by RegisterQuantityCheck::checkWithIgnore(), and error().
Member Data Documentation
errors_
ErrorTable MachineCheckResults::errors_ private
Contains the errors.
Definition at line 66 of file MachineCheckResults.hh.
Referenced by addError(), error(), and errorCount().
The documentation for this class was generated from the following files:
MachineCheckResults.hh
MachineCheckResults.cc