OpenASIP: BEMGeneratorCmdLineOptions Class Reference
BEMGeneratorCmdLineOptions Class Reference
#include <BEMGeneratorCmdLineOptions.hh>
Public Member Functions
BEMGeneratorCmdLineOptions ()
virtual ~BEMGeneratorCmdLineOptions ()
std::string adfFile () const
std::string outputFile () const
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Static Private Attributes
static const std::string ADF_PARAM_NAME = "adf"
Long name of the ADF file parameter.
static const std::string OUTPUT_FILE_PARAM_NAME
Long name of the output file parameter.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line options for the command line interface of bem generator (createbem).
Definition at line 42 of file BEMGeneratorCmdLineOptions.hh.
Constructor & Destructor Documentation
BEMGeneratorCmdLineOptions()
BEMGeneratorCmdLineOptions::BEMGeneratorCmdLineOptions ()
The constructor.
Definition at line 43 of file BEMGeneratorCmdLineOptions.cc.
                                                       :
    CmdLineOptions("") {
    StringCmdLineOptionParser* outputFile = new StringCmdLineOptionParser(
        OUTPUT_FILE_PARAM_NAME, "The name of the output file", "o");
    addOption(outputFile);
}
References CmdLineParser::addOption(), OUTPUT_FILE_PARAM_NAME, and outputFile().
~BEMGeneratorCmdLineOptions()
BEMGeneratorCmdLineOptions::~BEMGeneratorCmdLineOptions () virtual
The destructor.
Definition at line 55 of file BEMGeneratorCmdLineOptions.cc.
{
}
Member Function Documentation
adfFile()
std::string BEMGeneratorCmdLineOptions::adfFile () const
Returns the name of the ADF file given as command line parameter.
Returns
The name of the ADF file.
Definition at line 65 of file BEMGeneratorCmdLineOptions.cc.
{
    if (numberOfArguments() < 1) {
        return "";
    } else {
        return argument(numberOfArguments());
    }
}
References CmdLineParser::argument(), and CmdLineParser::numberOfArguments().
outputFile()
std::string BEMGeneratorCmdLineOptions::outputFile () const
Returns the name of the output file given as command line parameter.
Returns
The name of the output file.
Definition at line 80 of file BEMGeneratorCmdLineOptions.cc.
{
    return findOption(OUTPUT_FILE_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), OUTPUT_FILE_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by BEMGeneratorCmdLineOptions().
printHelp()
void BEMGeneratorCmdLineOptions::printHelp () const virtual
Prints the help.
Reimplemented from CmdLineOptions.
Definition at line 105 of file BEMGeneratorCmdLineOptions.cc.
{
    printVersion();
    std::cout << "Usage: createbem [OPTION] <ADF File>";
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void BEMGeneratorCmdLineOptions::printVersion () const virtual
Prints the version of the user interface.
Implements CmdLineOptions.
Definition at line 89 of file BEMGeneratorCmdLineOptions.cc.
{
    BEMGeneratorCLITextGenerator textGenerator;
    std::cout
        << textGenerator.text(BEMGeneratorCLITextGenerator::TXT_CLI_TITLE).
        str()
        << " "
        << textGenerator.text(
            BEMGeneratorCLITextGenerator::TXT_CLI_VERSION).str()
        << std::endl;
}
References Texts::TextGenerator::text(), BEMGeneratorCLITextGenerator::TXT_CLI_TITLE, and BEMGeneratorCLITextGenerator::TXT_CLI_VERSION.
Referenced by printHelp().
Member Data Documentation
ADF_PARAM_NAME
const std::string BEMGeneratorCmdLineOptions::ADF_PARAM_NAME = "adf" static private
Long name of the ADF file parameter.
Definition at line 54 of file BEMGeneratorCmdLineOptions.hh.
OUTPUT_FILE_PARAM_NAME
const std::string BEMGeneratorCmdLineOptions::OUTPUT_FILE_PARAM_NAME static private
Initial value:
=
    "output"
Long name of the output file parameter.
Definition at line 56 of file BEMGeneratorCmdLineOptions.hh.
Referenced by BEMGeneratorCmdLineOptions(), and outputFile().
The documentation for this class was generated from the following files:
BEMGeneratorCmdLineOptions.hh
BEMGeneratorCmdLineOptions.cc