OpenASIP: HDB::BlockImplementationFile Class Reference
HDB::BlockImplementationFile Class Reference
#include <BlockImplementationFile.hh>
Public Types
enum Format { VHDL , Verilog , VHDLsim , Verilogsim }
Format of the file.
Public Member Functions
BlockImplementationFile (const std::string &pathToFile, Format format)
virtual ~BlockImplementationFile ()
std::string pathToFile () const
Format format () const
void setPathToFile (const std::string &pathToFile)
void setFormat (Format format)
Private Attributes
std::string file_
The file.
Format format_
Format of the file.
Detailed Description
Represents a file that contains implementation for a block in HDB.
Definition at line 44 of file BlockImplementationFile.hh.
Member Enumeration Documentation
Format
enum HDB::BlockImplementationFile::Format
Format of the file.
Enumerator
VHDL
VHDL file.
Verilog
Verilog file.
VHDLsim
VHDL simulation file.
Verilogsim
Verilog simulation file.
Definition at line 47 of file BlockImplementationFile.hh.
                {
        VHDL, ///< VHDL file.
        Verilog, ///< Verilog file.
        VHDLsim, ///< VHDL simulation file.
        Verilogsim ///< Verilog simulation file.
    };
Constructor & Destructor Documentation
BlockImplementationFile()
HDB::BlockImplementationFile::BlockImplementationFile (const std::string & pathToFile, Format format)
The constructor.
Parameters
pathToFile Path to the file.
format Format of the file.
Definition at line 43 of file BlockImplementationFile.cc.
                   :
    file_(pathToFile), format_(format) {
}
~BlockImplementationFile()
HDB::BlockImplementationFile::~BlockImplementationFile () virtual
The destructor.
Definition at line 53 of file BlockImplementationFile.cc.
{
}
Member Function Documentation
format()
BlockImplementationFile::Format HDB::BlockImplementationFile::format () const
Returns the format of the file.
Definition at line 70 of file BlockImplementationFile.cc.
{
    return format_;
}
References format_.
Referenced by HDB::HDBManager::addBlockImplementationFileToHDB(), ProGe::BlockSourceCopier::copyFiles(), HDBToHtml::fuImplToHtml(), HDBToHtml::rfImplToHtml(), and setFormat().
pathToFile()
std::string HDB::BlockImplementationFile::pathToFile () const
Returns path to the file.
Definition at line 61 of file BlockImplementationFile.cc.
{
    return file_;
}
References file_.
Referenced by HDB::HDBManager::addBlockImplementationFileToHDB(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), ProGe::BlockSourceCopier::copyFiles(), ImplementationTester::createListOfSimulationFiles(), HDBToHtml::fuImplToHtml(), ProGeScriptGenerator::getBlockOrder(), FUImplementationDialog::onDeleteSourceFile(), RFImplementationDialog::onDeleteSourceFile(), RFImplementationDialog::onMoveSourceFileDown(), FUImplementationDialog::onMoveSourceFileDown(), RFImplementationDialog::onMoveSourceFileUp(), FUImplementationDialog::onMoveSourceFileUp(), HDBToHtml::rfImplToHtml(), setPathToFile(), RFImplementationDialog::update(), and FUImplementationDialog::update().
setFormat()
void HDB::BlockImplementationFile::setFormat (Format format)
Sets the format of the file.
Parameters
format The new format.
Definition at line 92 of file BlockImplementationFile.cc.
{
    format_ = format;
}
References format(), and format_.
Referenced by BlockImplementationFileDialog::onOK().
setPathToFile()
void HDB::BlockImplementationFile::setPathToFile (const std::string & pathToFile)
Sets the file path.
Parameters
pathToFile The new path.
Definition at line 81 of file BlockImplementationFile.cc.
{
    file_ = pathToFile;
}
References file_, and pathToFile().
Referenced by BlockImplementationFileDialog::onOK().
Member Data Documentation
file_
std::string HDB::BlockImplementationFile::file_ private
The file.
Definition at line 65 of file BlockImplementationFile.hh.
Referenced by pathToFile(), and setPathToFile().
format_
Format HDB::BlockImplementationFile::format_ private
Format of the file.
Definition at line 67 of file BlockImplementationFile.hh.
Referenced by format(), and setFormat().
The documentation for this class was generated from the following files:
BlockImplementationFile.hh
BlockImplementationFile.cc