OpenASIP: TPEF::SectionOffsetReplacer Class Reference
TPEF::SectionOffsetReplacer Class Reference
#include <SectionOffsetReplacer.hh>
Public Member Functions
SectionOffsetReplacer (const SafePointable *obj)
virtual ~SectionOffsetReplacer ()
Public Member Functions inherited from TPEF::ValueReplacer
void resolve ()
Protected Member Functions
virtual bool tryToReplace ()
virtual ValueReplacer * clone ()
Protected Member Functions inherited from TPEF::ValueReplacer
ValueReplacer (const SafePointable *obj)
ValueReplacer (const ValueReplacer &replacer)
virtual ~ValueReplacer ()
const SafePointable * reference () const
unsigned int streamPosition () const
Private Member Functions
SectionOffsetReplacer (const SectionOffsetReplacer &replacer)
SectionOffsetReplacer operator= (const SectionOffsetReplacer &)
Additional Inherited Members
Static Public Member Functions inherited from TPEF::ValueReplacer
static void finalize ()
static void initialize (BinaryStream &stream)
Static Protected Member Functions inherited from TPEF::ValueReplacer
static BinaryStream & stream ()
Detailed Description
Replaces object reference with section offset. Section offset key must be stored in reference manager for that object whose section offset is written.
Definition at line 47 of file SectionOffsetReplacer.hh.
Constructor & Destructor Documentation
SectionOffsetReplacer() [1/2]
TPEF::SectionOffsetReplacer::SectionOffsetReplacer (const SafePointable * obj)
Constructor.
Definition at line 46 of file SectionOffsetReplacer.cc.
                                                                     :
    ValueReplacer(obj) {
}
~SectionOffsetReplacer()
TPEF::SectionOffsetReplacer::~SectionOffsetReplacer () virtual
Destructor.
Definition at line 60 of file SectionOffsetReplacer.cc.
{
}
SectionOffsetReplacer() [2/2]
TPEF::SectionOffsetReplacer::SectionOffsetReplacer (const SectionOffsetReplacer & replacer) private
Copy constructor.
Definition at line 53 of file SectionOffsetReplacer.cc.
                                           : ValueReplacer(replacer) {
}
Member Function Documentation
clone()
ValueReplacer * TPEF::SectionOffsetReplacer::clone () protected virtual
Creates dynamically allocated copy of replacer.
Returns
Dynamically allocated copy of replacer.
Implements TPEF::ValueReplacer.
Definition at line 90 of file SectionOffsetReplacer.cc.
{
    return new SectionOffsetReplacer(*this);
}
operator=()
SectionOffsetReplacer TPEF::SectionOffsetReplacer::operator= (const SectionOffsetReplacer &) private
tryToReplace()
bool TPEF::SectionOffsetReplacer::tryToReplace () protected virtual
Tries to do replacement in to the stream.
Returns
True if replacement were done.
Implements TPEF::ValueReplacer.
Definition at line 69 of file SectionOffsetReplacer.cc.
{
    try {
        SectionOffsetKey key =
            SafePointer::sectionOffsetKeyFor(reference());
        stream().setWritePosition(streamPosition());
        stream().writeWord(key.offset());
        return true;
    } catch (KeyNotFound& e) {
        stream().writeWord(0);
        return false;
    }
}
References TPEF::ReferenceManager::SectionOffsetKey::offset(), TPEF::ValueReplacer::reference(), TPEF::ReferenceManager::SafePointer::sectionOffsetKeyFor(), TPEF::BinaryStream::setWritePosition(), TPEF::ValueReplacer::stream(), TPEF::ValueReplacer::streamPosition(), and TPEF::BinaryStream::writeWord().
The documentation for this class was generated from the following files:
SectionOffsetReplacer.hh
SectionOffsetReplacer.cc