OpenASIP: NullPortState Class Reference
NullPortState Class Reference
#include <PortState.hh>
Public Member Functions
virtual ~NullPortState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
virtual FUState & parent () const
Public Member Functions inherited from PortState
PortState (FUState &parent, int width)
PortState (FUState &parent, SimValue &sharedRegister)
virtual ~PortState ()
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Static Public Member Functions
static NullPortState & instance ()
Private Member Functions
NullPortState ()
NullPortState (const NullPortState &)
Copying not allowed.
NullPortState & operator= (const NullPortState &)
Assignment not allowed.
Static Private Attributes
static NullPortState * instance_ = NULL
Unique instance of NullPortState class.
Additional Inherited Members
Protected Attributes inherited from PortState
FUState * parent_
Parent of the port.
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Models non-existing PortState.
Definition at line 76 of file PortState.hh.
Constructor & Destructor Documentation
~NullPortState()
NullPortState::~NullPortState () virtual
Destructor.
Definition at line 112 of file PortState.cc.
{
}
NullPortState() [1/2]
NullPortState::NullPortState () private
Constructor.
Definition at line 106 of file PortState.cc.
                             : PortState(NullFUState::instance(), 0) {
}
Referenced by instance().
NullPortState() [2/2]
NullPortState::NullPortState (const NullPortState &) private
Copying not allowed.
Member Function Documentation
instance()
NullPortState & NullPortState::instance () static
Returns the instance of NullPortState.
Returns
The instance of NullPortState.
Definition at line 96 of file PortState.cc.
{
    if (instance_ == NULL) {
        instance_ = new NullPortState();
    }
    return *instance_;
}
References instance_, and NullPortState().
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), MachineStateBuilder::buildMachineState(), SimulatorFrontend::findPort(), FUTestbenchGenerator::parseFuPorts(), MachineState::portState(), and SimProgramBuilder::processBidirTerminal().
operator=()
NullPortState & NullPortState::operator= (const NullPortState &) private
Assignment not allowed.
parent()
FUState & NullPortState::parent () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from PortState.
Definition at line 140 of file PortState.cc.
{
    Application::abortWithError("parent()");
    return NullFUState::instance();
}
References NullFUState::instance().
setValue()
void NullPortState::setValue (const SimValue & value) virtual
Aborts the program with error message.
Reimplemented from RegisterState.
Definition at line 119 of file PortState.cc.
{
    Application::abortWithError("setValue()");
}
value()
const SimValue & NullPortState::value () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from RegisterState.
Definition at line 129 of file PortState.cc.
{
    Application::abortWithError("value()");
    return NullSimValue::instance();
}
References NullSimValue::instance().
Member Data Documentation
instance_
NullPortState * NullPortState::instance_ = NULL static private
Unique instance of NullPortState class.
Definition at line 94 of file PortState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
PortState.hh
PortState.cc