OpenASIP: Request Class Reference
Request Class Reference
#include <Request.hh>
Public Types
enum RequestType {
NONE , MODIFY_REQUEST , DELETE_REQUEST , CONNECT_REQUEST ,
COPY_REQUEST , STATUS_REQUEST , DETAILS_REQUEST
}
Data type for determining the type of a Request.
Public Member Functions
Request (RequestType type)
virtual ~Request ()
void setType (RequestType type)
RequestType type () const
Private Member Functions
Request & operator= (Request &old)
Assignment not allowed.
Request (Request &old)
Copying not allowed.
Private Attributes
RequestType type_
Determines type of this Request.
Detailed Description
Used to communicate with EditPart objects.
Type of the Request determines the function an EditPart should perform.
Definition at line 43 of file Request.hh.
Member Enumeration Documentation
RequestType
enum Request::RequestType
Data type for determining the type of a Request.
Enumerator
NONE
No type.
MODIFY_REQUEST
Modfify request.
DELETE_REQUEST
Delete request.
CONNECT_REQUEST
Connect request.
COPY_REQUEST
Copy request.
STATUS_REQUEST
Status request.
DETAILS_REQUEST
Detailed info request.
Definition at line 46 of file Request.hh.
                     {
    NONE,            ///< No type.
        MODIFY_REQUEST,  ///< Modfify request.
    DELETE_REQUEST,  ///< Delete request.
    CONNECT_REQUEST, ///< Connect request.
    COPY_REQUEST,    ///< Copy request.
        STATUS_REQUEST,  ///< Status request.
        DETAILS_REQUEST  ///< Detailed info request.
    };
Constructor & Destructor Documentation
Request() [1/2]
Request::Request (RequestType type) explicit
The Constructor.
Parameters
type Type of the Request.
Definition at line 41 of file Request.cc.
: type_(type) {}
~Request()
Request::~Request () virtual
The Destructor.
Definition at line 46 of file Request.cc.
{}
Request() [2/2]
Request::Request (Request & old) private
Copying not allowed.
Member Function Documentation
operator=()
Request & Request::operator= (Request & old) private
Assignment not allowed.
setType()
void Request::setType (RequestType type)
type()
RequestType Request::type () const
Referenced by ProximBusEditPolicy::canHandle(), ProximFUEditPolicy::canHandle(), ProximIUEditPolicy::canHandle(), ProximPortEditPolicy::canHandle(), ProximRFEditPolicy::canHandle(), ProximSocketEditPolicy::canHandle(), ProDeBridgeEditPolicy::canHandle(), ProDeBusEditPolicy::canHandle(), ProDeFUEditPolicy::canHandle(), ProDeFUPortEditPolicy::canHandle(), ProDeGCUEditPolicy::canHandle(), ProDeIUEditPolicy::canHandle(), ProDeIUPortEditPolicy::canHandle(), ProDePortEditPolicy::canHandle(), ProDeRFEditPolicy::canHandle(), ProDeRFPortEditPolicy::canHandle(), ProDeSegmentEditPolicy::canHandle(), ProDeSocketEditPolicy::canHandle(), ProDeSRPortEditPolicy::canHandle(), ProximBusEditPolicy::getCommand(), ProximFUEditPolicy::getCommand(), ProximIUEditPolicy::getCommand(), ProximPortEditPolicy::getCommand(), ProximRFEditPolicy::getCommand(), ProximSocketEditPolicy::getCommand(), ProDeBridgeEditPolicy::getCommand(), ProDeBusEditPolicy::getCommand(), ProDeFUEditPolicy::getCommand(), ProDeFUPortEditPolicy::getCommand(), ProDeGCUEditPolicy::getCommand(), ProDeIUEditPolicy::getCommand(), ProDeIUPortEditPolicy::getCommand(), ProDePortEditPolicy::getCommand(), ProDeRFEditPolicy::getCommand(), ProDeRFPortEditPolicy::getCommand(), ProDeSegmentEditPolicy::getCommand(), ProDeSocketEditPolicy::getCommand(), and ProDeSRPortEditPolicy::getCommand().
Member Data Documentation
type_
RequestType Request::type_ private
Determines type of this Request.
Definition at line 69 of file Request.hh.
The documentation for this class was generated from the following files:
Request.hh
Request.cc