OpenASIP: MemWriteCommand Class Reference
MemWriteCommand Class Reference
#include <MemWriteCommand.hh>
Public Member Functions
MemWriteCommand ()
virtual ~MemWriteCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "load_data" command of the Simulator Control Language.
Definition at line 48 of file MemWriteCommand.hh.
Constructor & Destructor Documentation
MemWriteCommand()
MemWriteCommand::MemWriteCommand ()
Definition at line 49 of file MemWriteCommand.cc.
                                 :
    SimControlLanguageCommand("load_data") {
}
~MemWriteCommand()
MemWriteCommand::~MemWriteCommand () virtual
Definition at line 54 of file MemWriteCommand.cc.
{
}
Member Function Documentation
execute()
bool MemWriteCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "load_data" command.
This low-level command reads binary data from file and loads it to memory starting at specified address.
Parameters
arguments Memory address to be written, file to read from, read size.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 68 of file MemWriteCommand.cc.
{
    const int argumentCount = arguments.size() - 1;
    if (!checkArgumentCount(argumentCount, 2, 5)) {
        return false;
    }
    if (!checkProgramLoaded()) {
        return false;
    }
    size_t nextArg = 1;
    size_t writeAddress;
    std::string addressSpaceName = "";
    if (StringTools::ciEqual(arguments.at(nextArg).stringValue(), "/a")) {
        addressSpaceName = arguments.at(2).stringValue();
        nextArg = 3;
    }
    const std::string addressString = arguments.at(nextArg).stringValue();
    if (!setMemoryAddress(addressString, addressSpaceName, writeAddress)) {
        return false;
    }
    std::string fileName = arguments.at(nextArg + 1).stringValue();
    if (!FileSystem::fileExists(fileName) ||
        !FileSystem::fileIsReadable(fileName)) {
        interpreter()->setResult("Error reading input file.");
        interpreter()->setError(true);
        return false;
    }
    size_t readSize = FileSystem::sizeInBytes(fileName);
    if (argumentCount == 3 || argumentCount == 5) {
        readSize = arguments.at(nextArg + 2).integerValue();
    }
    MemorySystem::MemoryPtr memory;
    if (!setMemoryPointer(memory, addressSpaceName)) {
        return false;
    }
    std::ifstream inputFile(fileName.c_str(), std::ios::binary);
    char dataByte;
    while (inputFile.get(dataByte) && readSize > 0) {
        try {
            memory->write(writeAddress, 1, (UIntWord)dataByte);
        } catch (const OutOfRange&) {
            interpreter()->setResult(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_ADDRESS_OUT_OF_RANGE).str());
            interpreter()->setError(true);
            return false;
        }
        writeAddress++;
        readSize--;
    }
    memory->advanceClock();
    inputFile.close();
    return true;
}
References CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkProgramLoaded(), StringTools::ciEqual(), FileSystem::fileExists(), FileSystem::fileIsReadable(), CustomCommand::interpreter(), ScriptInterpreter::setError(), SimControlLanguageCommand::setMemoryAddress(), SimControlLanguageCommand::setMemoryPointer(), ScriptInterpreter::setResult(), FileSystem::sizeInBytes(), SimulatorToolbox::textGenerator(), and Texts::TXT_ADDRESS_OUT_OF_RANGE.
helpText()
std::string MemWriteCommand::helpText () const virtual
Implements CustomCommand.
Definition at line 133 of file MemWriteCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_LOADDATA).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_LOADDATA.
The documentation for this class was generated from the following files:
MemWriteCommand.hh
MemWriteCommand.cc