OpenASIP: MoveNodeDuplicator Class Reference
MoveNodeDuplicator Class Reference
#include <MoveNodeDuplicator.hh>
Public Member Functions
MoveNodeDuplicator (DataDependenceGraph &oldDDG, DataDependenceGraph &newDDG)
std::pair< MoveNode *, bool > duplicateMoveNode (MoveNode &mn, bool addToDDG, bool ignoreSameBBBackEdges)
std::shared_ptr< TTAProgram::Move > duplicateMove (TTAProgram::Move &old)
ProgramOperationPtr duplicateProgramOperationPtr (ProgramOperationPtr old)
void disposeMoveNode (MoveNode *newMN)
void setBBN (BasicBlockNode &bbn)
MoveNode * getMoveNode (MoveNode &mn)
ProgramOperationPtr getProgramOperation (ProgramOperationPtr old)
void dumpDDG ()
Private Attributes
std::map< ProgramOperation *, ProgramOperationPtr, ProgramOperation::Comparator > programOperations_
std::map< ProgramOperation *, ProgramOperationPtr, ProgramOperation::Comparator > oldProgramOperations_
std::map< MoveNode *, MoveNode *, MoveNode::Comparator > moveNodes_
std::map< MoveNode *, MoveNode *, MoveNode::Comparator > oldMoveNodes_
std::map< TTAProgram::Move *, std::shared_ptr< TTAProgram::Move > > moves_
BasicBlockNode * bbn_
DataDependenceGraph * oldDDG_
DataDependenceGraph * newDDG_
DataDependenceGraph * bigDDG_
Detailed Description
Definition at line 38 of file MoveNodeDuplicator.hh.
Constructor & Destructor Documentation
MoveNodeDuplicator()
MoveNodeDuplicator::MoveNodeDuplicator (DataDependenceGraph & oldDDG, DataDependenceGraph & newDDG)
This class is used for copying moves from a basic block to another corresponding basic block, copying also the programoperation structure.
Definition at line 48 of file MoveNodeDuplicator.cc.
                                                              :
    oldDDG_(&oldDDG), newDDG_(&newDDG),
    bigDDG_(static_cast<DataDependenceGraph*>(oldDDG.rootGraph())) { }
Member Function Documentation
disposeMoveNode()
void MoveNodeDuplicator::disposeMoveNode (MoveNode * newMN)
Definition at line 53 of file MoveNodeDuplicator.cc.
{
    if (newMN == NULL) {
        return;
    }
    if (newMN->isScheduled()) {
        std::cerr << "\t\t\t\t\tCannot dispose scheduled mn: "
                  << newMN->toString() << std::endl;
        assert(false);
    }
    assert(!newMN->isScheduled());
    std::map<MoveNode*,MoveNode*,MoveNode::Comparator>::iterator i =
        oldMoveNodes_.find(newMN);
    // already disposed?
    if (i == oldMoveNodes_.end()) {
        return;
    }
    MoveNode* old = i->second;
    moveNodes_.erase(old);
    oldMoveNodes_.erase(newMN);
    TTAProgram::Move* oldMove = &old->move();
    moves_.erase(oldMove);
    if (newDDG_->hasNode(*newMN)) {
        newDDG_->removeNode(*newMN);
    }
    delete newMN;
}
References assert, BoostGraph< GraphNode, GraphEdge >::hasNode(), MoveNode::isScheduled(), MoveNode::move(), moveNodes_, moves_, newDDG_, oldMoveNodes_, DataDependenceGraph::removeNode(), and MoveNode::toString().
Referenced by BFOptimization::canAssign(), BFDRELoop::operator()(), BFSchedulePreLoopShared::operator()(), BFOptimization::rmEC(), BFOptimization::rmLC(), BFOptimization::unassignCopyFromPrologEpilog(), BFDRELoop::undoOnlyMe(), BFSchedulePreLoopShared::undoOnlyMe(), and BFMergeAndKeepUser::undoOnlyMe().
dumpDDG()
void MoveNodeDuplicator::dumpDDG ()
Definition at line 273 of file MoveNodeDuplicator.cc.
{
    newDDG_->writeToDotFile("prolog_ddg.dot");
}
References newDDG_, and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
duplicateMove()
std::shared_ptr< TTAProgram::Move > MoveNodeDuplicator::duplicateMove (TTAProgram::Move & old)
Definition at line 199 of file MoveNodeDuplicator.cc.
{
    if (AssocTools::containsKey(moves_,&old)) {
        return moves_[&old];
    } else {
        MoveNode& oldMN = oldDDG_->nodeOfMove(old);
        std::shared_ptr<TTAProgram::Move> newMove(old.copy());
        newMove->setBus(UniversalMachine::instance().universalBus());
        TTAProgram::Terminal& source = newMove->source();
        if (oldMN.isSourceOperation()) {
            if (oldMN.isScheduled()) {
                assert(source.isFUPort());
                std::string fuName = source.functionUnit().name();
                //TODO: which is the correct annotation here?
                TTAProgram::ProgramAnnotation srcUnit(
                    TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC,
                    fuName);
                newMove->setAnnotation(srcUnit);
                const Operation &srcOp = oldMN.sourceOperation().operation();
                const TTAMachine::HWOperation& hwop =
                    *UniversalMachine::instance().universalFunctionUnit().
                    operation(srcOp.name());
                newMove->setSource(new TTAProgram::TerminalFUPort(
                                       hwop, old.source().operationIndex()));
            }
        } else {
            if (source.isRA()) {
                newMove->setSource(
                    new TTAProgram::TerminalFUPort(
                        *UniversalMachine::instance().controlUnit()->
                        returnAddressPort()));
            }
        }
        TTAProgram::Terminal& dest = newMove->destination();
        if (oldMN.isDestinationOperation()) {
            assert(dest.isFUPort());
            if (oldMN.isScheduled()) {
                std::string fuName = dest.functionUnit().name();
                //TODO: which is the correct annotation here?
                TTAProgram::ProgramAnnotation dstUnit(
                    TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_DST,
                    fuName);
                newMove->setAnnotation(dstUnit);
                const Operation &dstOp =
                    oldMN.destinationOperation().operation();
                TTAMachine::HWOperation& hwop =
                    *UniversalMachine::instance().universalFunctionUnit().
                    operation(dstOp.name());
                newMove->setDestination(new TTAProgram::TerminalFUPort(
                                            hwop, old.destination().
                                            operationIndex()));
            } else {
                if (dest.isRA()) {
                    newMove->setDestination(
                        new TTAProgram::TerminalFUPort(
                            *UniversalMachine::instance().controlUnit()->
                            returnAddressPort()));
                }
            }
        }
        moves_[&old] = newMove;
        // set guard of new move to be same as old move.
        if (!old.isUnconditional()) {
            TTAProgram::MoveGuard* g = old.guard().copy();
            newMove->setGuard(g);
        }
        return newMove;
    }
}
References TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_DST, TTAProgram::ProgramAnnotation::ANN_CONN_CANDIDATE_UNIT_SRC, assert, AssocTools::containsKey(), TTAProgram::Move::copy(), TTAProgram::MoveGuard::copy(), TTAProgram::Move::destination(), MoveNode::destinationOperation(), TTAProgram::Terminal::functionUnit(), TTAProgram::Move::guard(), UniversalMachine::instance(), MoveNode::isDestinationOperation(), TTAProgram::Terminal::isFUPort(), TTAProgram::Terminal::isRA(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), TTAProgram::Move::isUnconditional(), moves_, TTAMachine::Component::name(), Operation::name(), DataDependenceGraph::nodeOfMove(), oldDDG_, ProgramOperation::operation(), TTAProgram::Terminal::operationIndex(), TTAProgram::Move::source(), MoveNode::sourceOperation(), and UniversalMachine::universalFunctionUnit().
Referenced by duplicateMoveNode().
duplicateMoveNode()
std::pair< MoveNode *, bool > MoveNodeDuplicator::duplicateMoveNode (MoveNode & old, bool addToDDG, bool ignoreSameBBBackEdges)
Duplicates a corresponding MoveNode a given move in the next BB.
If no corresponding MoveNode created, creates one
Parameters
old ProgramOperation in jump target BB.
Returns
new MoveNode for this BB.
Definition at line 106 of file MoveNodeDuplicator.cc.
{
    std::map<MoveNode*,MoveNode*,MoveNode::Comparator>::iterator iter =
        moveNodes_.find(&old);
    if (iter != moveNodes_.end()) {
        MoveNode* node = iter->second;
        if (addToDDG) {
            if (!newDDG_->hasNode(*node)) {
                newDDG_->addNode(*node, *bbn_);
                bigDDG_->copyDependencies(old,*node, ignoreSameBBBackEdges, false);
            }
        }
    }
    if (AssocTools::containsKey(moveNodes_,&old)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\t\told mn found: "
                  << moveNodes_[&old]->toString() << std::endl;
#endif
        return std::make_pair(moveNodes_[&old], false);
    } else {
        auto movePtr = duplicateMove(old.move());
        MoveNode *newMN = new MoveNode(movePtr);
        // TODO: only add to ddg if really scheduling, not for testing?
        if (addToDDG) {
            newDDG_->addNode(*newMN, *bbn_);
            bigDDG_->copyDependencies(old,*newMN, ignoreSameBBBackEdges, false);
        }
        moveNodes_[&old] = newMN;
        oldMoveNodes_[newMN] = &old;
        if (old.isSourceOperation()) {
            newMN->setSourceOperationPtr(
                duplicateProgramOperationPtr(old.sourceOperationPtr()));
            newMN->sourceOperation().addOutputNode(*newMN);
            assert(newMN->isSourceOperation());
        }
        if (old.isDestinationOperation()) {
            for (unsigned int i = 0;
                 i < old.destinationOperationCount(); i++) {
                newMN->addDestinationOperationPtr(
                    duplicateProgramOperationPtr(
                        old.destinationOperationPtr(i)));
                newMN->destinationOperation(i).addInputNode(*newMN);
            }
            assert(newMN->isDestinationOperation());
        }
        if (old.isGuardOperation()) {
            newMN->setGuardOperationPtr(
                duplicateProgramOperationPtr(old.guardOperationPtr()));
            newMN->guardOperation().addGuardOutputNode(*newMN);
            assert(newMN->isGuardOperation());
        }
        return std::make_pair(newMN, true);
    }
}
References MoveNode::addDestinationOperationPtr(), ProgramOperation::addGuardOutputNode(), ProgramOperation::addInputNode(), DataDependenceGraph::addNode(), ProgramOperation::addOutputNode(), assert, bbn_, bigDDG_, AssocTools::containsKey(), DataDependenceGraph::copyDependencies(), MoveNode::destinationOperation(), MoveNode::destinationOperationCount(), MoveNode::destinationOperationPtr(), duplicateMove(), duplicateProgramOperationPtr(), MoveNode::guardOperation(), MoveNode::guardOperationPtr(), BoostGraph< GraphNode, GraphEdge >::hasNode(), MoveNode::isDestinationOperation(), MoveNode::isGuardOperation(), MoveNode::isSourceOperation(), MoveNode::move(), moveNodes_, newDDG_, oldMoveNodes_, MoveNode::setGuardOperationPtr(), MoveNode::setSourceOperationPtr(), MoveNode::sourceOperation(), and MoveNode::sourceOperationPtr().
Referenced by BFOptimization::canAssign(), BFOptimization::createCopyForPrologEpilog(), BFDRELoop::operator()(), BFSchedulePreLoopShared::operator()(), BFMergeAndKeepUser::operator()(), BFOptimization::rmEC(), and BFOptimization::rmLC().
duplicateProgramOperationPtr()
ProgramOperationPtr MoveNodeDuplicator::duplicateProgramOperationPtr (ProgramOperationPtr old)
Gets a corresponding ProgramOperation to a given move in the next BB.
If no corresponding ProgramOperation created, creates one
Parameters
old ProgramOperation in jump target BB.
Returns
new ProgramOperation for this BB.
Definition at line 173 of file MoveNodeDuplicator.cc.
                             { // , BasicBlockNode& bbn) {
    if (AssocTools::containsKey(programOperations_, old.get())) {
        return programOperations_[old.get()];
    } else {
        ProgramOperationPtr po =
            ProgramOperationPtr(
                new ProgramOperation(old->operation()));
        programOperations_[old.get()] = po;
        oldProgramOperations_[po.get()] = old;
        return po;
    }
}
References AssocTools::containsKey(), oldProgramOperations_, and programOperations_.
Referenced by duplicateMoveNode(), and BFShareOperand::operator()().
getMoveNode()
MoveNode * MoveNodeDuplicator::getMoveNode (MoveNode & mn)
Definition at line 85 of file MoveNodeDuplicator.cc.
{
    std::map<MoveNode*,MoveNode*,MoveNode::Comparator>::iterator iter =
        moveNodes_.find(&old);
if (iter != moveNodes_.end()) {
        return iter->second;
    }
    return NULL;
}
References moveNodes_.
Referenced by BF2Scheduler::finalizeSchedule(), BFLateBypass::operator()(), BFShareOperand::operator()(), BFShareOperandLate::operator()(), BFShareOperandWithScheduled::operator()(), BFMergeAndKeepUser::operator()(), BFPostpassLoopDRE::operator()(), BFRemoveGuardFromSucc::operator()(), BFShareOperand::undoOnlyMe(), BFRemoveGuardFromSucc::undoOnlyMe(), and BFUnscheduleMove::unscheduleOriginal().
getProgramOperation()
ProgramOperationPtr MoveNodeDuplicator::getProgramOperation (ProgramOperationPtr old)
Definition at line 188 of file MoveNodeDuplicator.cc.
{
    auto i = programOperations_.find(old.get());
    if (i != programOperations_.end()) {
        return i->second;
    } else {
        return ProgramOperationPtr(nullptr);
    }
}
References programOperations_.
Referenced by BFShareOperand::operator()(), and BFShareOperand::undoOnlyMe().
setBBN()
void MoveNodeDuplicator::setBBN (BasicBlockNode & bbn) inline
Definition at line 52 of file MoveNodeDuplicator.hh.
{
        bbn_ = &bbn;
    }
References bbn_.
Referenced by BF2Scheduler::handleLoopDDG().
Member Data Documentation
bbn_
BasicBlockNode* MoveNodeDuplicator::bbn_ private
Definition at line 77 of file MoveNodeDuplicator.hh.
Referenced by duplicateMoveNode(), and setBBN().
bigDDG_
DataDependenceGraph* MoveNodeDuplicator::bigDDG_ private
Definition at line 80 of file MoveNodeDuplicator.hh.
Referenced by duplicateMoveNode().
moveNodes_
std::map<MoveNode*,MoveNode*,MoveNode::Comparator> MoveNodeDuplicator::moveNodes_ private
Definition at line 72 of file MoveNodeDuplicator.hh.
Referenced by disposeMoveNode(), duplicateMoveNode(), and getMoveNode().
moves_
std::map<TTAProgram::Move*,std::shared_ptr<TTAProgram::Move> > MoveNodeDuplicator::moves_ private
Definition at line 75 of file MoveNodeDuplicator.hh.
Referenced by disposeMoveNode(), and duplicateMove().
newDDG_
DataDependenceGraph* MoveNodeDuplicator::newDDG_ private
Definition at line 79 of file MoveNodeDuplicator.hh.
Referenced by disposeMoveNode(), dumpDDG(), and duplicateMoveNode().
oldDDG_
DataDependenceGraph* MoveNodeDuplicator::oldDDG_ private
Definition at line 78 of file MoveNodeDuplicator.hh.
Referenced by duplicateMove().
oldMoveNodes_
std::map<MoveNode*,MoveNode*,MoveNode::Comparator> MoveNodeDuplicator::oldMoveNodes_ private
Definition at line 74 of file MoveNodeDuplicator.hh.
Referenced by disposeMoveNode(), and duplicateMoveNode().
oldProgramOperations_
std::map<ProgramOperation*, ProgramOperationPtr, ProgramOperation::Comparator> MoveNodeDuplicator::oldProgramOperations_ private
Definition at line 70 of file MoveNodeDuplicator.hh.
Referenced by duplicateProgramOperationPtr().
programOperations_
std::map<ProgramOperation*, ProgramOperationPtr, ProgramOperation::Comparator> MoveNodeDuplicator::programOperations_ private
Definition at line 65 of file MoveNodeDuplicator.hh.
Referenced by duplicateProgramOperationPtr(), and getProgramOperation().
The documentation for this class was generated from the following files:
MoveNodeDuplicator.hh
MoveNodeDuplicator.cc