OpenASIP: SelectCmd Class Reference
SelectCmd Class Reference
#include <SelectCmd.hh>
Public Member Functions
SelectCmd ()
virtual ~SelectCmd ()
virtual bool Do ()
virtual int id () const
virtual SelectCmd * create () const
virtual std::string icon () const
bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for changing the canvas tool to the SelectTool.
Definition at line 41 of file SelectCmd.hh.
Constructor & Destructor Documentation
SelectCmd()
SelectCmd::SelectCmd ()
The Constructor.
Definition at line 45 of file SelectCmd.cc.
                    :
    EditorCommand(ProDeConstants::CMD_NAME_SELECT) {
}
Referenced by create().
~SelectCmd()
SelectCmd::~SelectCmd () virtual
The Destructor.
Definition at line 54 of file SelectCmd.cc.
                      {
}
Member Function Documentation
create()
SelectCmd * SelectCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 92 of file SelectCmd.cc.
{
    return new SelectCmd();
}
References SelectCmd().
Do()
bool SelectCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file SelectCmd.cc.
              {
    MDFView* mdfView = dynamic_cast<MDFView*>(view());
    ChildFrame* frame = dynamic_cast<ChildFrame*>(mdfView->GetFrame());
    assert(frame != NULL);
    mdfView->clearSelection();
    SelectTool* tool = new SelectTool(frame, mdfView);
    mdfView->canvas()->setTool(tool);
    return true;
}
References assert, MDFView::canvas(), MDFView::clearSelection(), MachineCanvas::setTool(), and EditorCommand::view().
icon()
string SelectCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 103 of file SelectCmd.cc.
                      {
    return ProDeConstants::CMD_ICON_SELECT;
}
References ProDeConstants::CMD_ICON_SELECT.
id()
int SelectCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 81 of file SelectCmd.cc.
                    {
    return ProDeConstants::COMMAND_SELECT;
}
References ProDeConstants::COMMAND_SELECT.
isEnabled()
bool SelectCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 116 of file SelectCmd.cc.
                     {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
The documentation for this class was generated from the following files:
SelectCmd.hh
SelectCmd.cc