OpenASIP: VhdlProgramImageWriter Class Reference
VhdlProgramImageWriter Class Reference
#include <VhdlProgramImageWriter.hh>
Public Member Functions
VhdlProgramImageWriter (const InstructionBitVector &bits, const std::string &entityName)
virtual ~VhdlProgramImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from ArrayProgramImageWriter
ArrayProgramImageWriter (const InstructionBitVector &bits)
virtual ~ArrayProgramImageWriter ()
Public Member Functions inherited from ArrayImageWriter
ArrayImageWriter (const BitVector &bits, int rowLength)
virtual ~ArrayImageWriter ()
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Private Member Functions
void writeHeader (std::ostream &stream) const
void writeEnding (std::ostream &stream) const
std::string packageName () const
Private Attributes
std::string entityName_
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Writes the (instruction) bit image to a vhdl package.
Definition at line 43 of file VhdlProgramImageWriter.hh.
Constructor & Destructor Documentation
VhdlProgramImageWriter()
VhdlProgramImageWriter::VhdlProgramImageWriter (const InstructionBitVector & bits, const std::string & entityName)
The constructor.
Parameters
bits The bits to write.
rowLength Length of the rows to write.
Definition at line 45 of file VhdlProgramImageWriter.cc.
                                                                  :
    ArrayProgramImageWriter(bits), entityName_(entityName) {
}
~VhdlProgramImageWriter()
VhdlProgramImageWriter::~VhdlProgramImageWriter () virtual
The destructor.
Definition at line 53 of file VhdlProgramImageWriter.cc.
{
}
Member Function Documentation
packageName()
std::string VhdlProgramImageWriter::packageName () const private
Definition at line 97 of file VhdlProgramImageWriter.cc.
{
    std::string package = "imem_image";
    if (!entityName_.empty()) {
        package = entityName_ + "_" + package;
    }
    return package;
}
Referenced by writeEnding(), and writeHeader().
writeEnding()
void VhdlProgramImageWriter::writeEnding (std::ostream & stream) const private
Writes the end declarations to the stream
Definition at line 91 of file VhdlProgramImageWriter.cc.
{
    stream << ");" << endl << endl
           << "end " << packageName() << ";" << endl;
}
References packageName().
Referenced by writeImage().
writeHeader()
void VhdlProgramImageWriter::writeHeader (std::ostream & stream) const private
Writes the vhdl declaration stuff to the beginning of the stream
Definition at line 71 of file VhdlProgramImageWriter.cc.
{
    stream << "library ieee;" << endl
           << "use ieee.std_logic_1164.all;" << endl
           << "use ieee.std_logic_arith.all;" << endl
           << "use work.";
    if (!entityName_.empty()) {
        stream << entityName_ << "_";
    }
    stream << "imem_mau.all;" << endl << endl;
    stream << "package " << packageName() << " is" << endl << endl
           << "  type std_logic_imem_matrix is array (natural range <>) of "
           << "std_logic_vector(IMEMMAUWIDTH-1 downto 0);" << endl << endl;
    stream << "  constant imem_array : std_logic_imem_matrix := (" << endl;
}
References entityName_, and packageName().
Referenced by writeImage().
writeImage()
void VhdlProgramImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given stream.
Parameters
stream The stream to write.
Reimplemented from ArrayProgramImageWriter.
Definition at line 62 of file VhdlProgramImageWriter.cc.
{
    writeHeader(stream);
    ArrayProgramImageWriter::writeImage(stream);
    writeEnding(stream);
}
References writeEnding(), writeHeader(), and ArrayProgramImageWriter::writeImage().
Member Data Documentation
entityName_
std::string VhdlProgramImageWriter::entityName_ private
Definition at line 58 of file VhdlProgramImageWriter.hh.
Referenced by writeHeader().
The documentation for this class was generated from the following files:
VhdlProgramImageWriter.hh
VhdlProgramImageWriter.cc