OpenASIP: TPEF::TPEFResourceSectionWriter Class Reference
TPEF::TPEFResourceSectionWriter Class Reference
#include <TPEFResourceSectionWriter.hh>
Protected Member Functions
TPEFResourceSectionWriter ()
virtual ~TPEFResourceSectionWriter ()
virtual Section::SectionType type () const
virtual void actualWriteData (BinaryStream &stream, const Section *section) const
virtual Word elementSize (const Section *section) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void createKeys (const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFResourceSectionWriter (const TPEFResourceSectionWriter &)
Copying not allowed.
TPEFResourceSectionWriter operator= (const TPEFResourceSectionWriter &)
Assignment not allowed.
Static Private Attributes
static const TPEFResourceSectionWriter instance_
An unique instance of class.
static const Word elementSize_ = 11
The fixed size element.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes TPEF Processor Resource Table section to stream.
Definition at line 46 of file TPEFResourceSectionWriter.hh.
Constructor & Destructor Documentation
TPEFResourceSectionWriter() [1/2]
TPEF::TPEFResourceSectionWriter::TPEFResourceSectionWriter () protected
Constructor.
Registers itself to SectionWriter.
Definition at line 62 of file TPEFResourceSectionWriter.cc.
                                                     :
    TPEFSectionWriter() {
    registerSectionWriter(this);
}
References TPEF::SectionWriter::registerSectionWriter().
~TPEFResourceSectionWriter()
TPEF::TPEFResourceSectionWriter::~TPEFResourceSectionWriter () protected virtual
Destructor.
Definition at line 70 of file TPEFResourceSectionWriter.cc.
{
}
TPEFResourceSectionWriter() [2/2]
TPEF::TPEFResourceSectionWriter::TPEFResourceSectionWriter (const TPEFResourceSectionWriter &) private
Copying not allowed.
Member Function Documentation
actualWriteData()
void TPEF::TPEFResourceSectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected virtual
Writes the data of the section in to stream.
Parameters
stream The stream to be written to.
sect The section to be written.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 90 of file TPEFResourceSectionWriter.cc.
{
    FileOffset startOffset = stream.writePosition();
    // file offset to body of section
    SafePointer::addObjectReference(
        FileOffsetKey(startOffset), sect->element(0));
    // set for checking multiple items
    std::multiset<
        std::pair<HalfWord, ResourceElement::ResourceType> > checkMultiple;
    for (Word i = 0; i < sect->elementCount(); i++) {
        ResourceElement* elem =
            dynamic_cast<ResourceElement*>(sect->element(i));
        assert(elem != NULL);
        // identification codes of resources must be unique among all
        // resources of the same type
        std::pair<HalfWord, ResourceElement::ResourceType>
            pairToFind(elem->id(), elem->type());
        // TODO: check that OP, SR and PORT share the same id space and don't
        // collide
        if (checkMultiple.find(pairToFind) != checkMultiple.end()) {
            bool multipleResourcesWithSameIdAndType = false;
            assert(multipleResourcesWithSameIdAndType);
        } else {
            checkMultiple.insert(pairToFind);
        }
        stream.writeHalfWord(elem->id());
        stream.writeByte(static_cast<Byte>(elem->type()));
        assert(elem->name() != NULL);
        SectionOffsetReplacer replacer(elem->name());
        replacer.resolve();
        stream.writeWord(elem->info());
    }
    SectionSizeReplacer::setSize(sect, stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::ResourceElement::id(), TPEF::ResourceElement::info(), TPEF::ResourceElement::name(), TPEF::ValueReplacer::resolve(), TPEF::SectionSizeReplacer::setSize(), TPEF::ResourceElement::type(), TPEF::BinaryStream::writeByte(), TPEF::BinaryStream::writeHalfWord(), TPEF::BinaryStream::writePosition(), and TPEF::BinaryStream::writeWord().
elementSize()
Word TPEF::TPEFResourceSectionWriter::elementSize (const Section * section) const protected virtual
Returns the fixed size length of section elements.
Returns
The fixed size length of section elements.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 144 of file TPEFResourceSectionWriter.cc.
{
    return elementSize_;
}
References elementSize_.
operator=()
TPEFResourceSectionWriter TPEF::TPEFResourceSectionWriter::operator= (const TPEFResourceSectionWriter &) private
Assignment not allowed.
type()
Section::SectionType TPEF::TPEFResourceSectionWriter::type () const protected virtual
Returns the section type this writer can write.
Returns
The section type writer can write.
Implements TPEF::TPEFSectionWriter.
Definition at line 79 of file TPEFResourceSectionWriter.cc.
{
    return Section::ST_MR;
}
References TPEF::Section::ST_MR.
Member Data Documentation
elementSize_
const Word TPEF::TPEFResourceSectionWriter::elementSize_ = 11 static private
The fixed size element.
Definition at line 69 of file TPEFResourceSectionWriter.hh.
Referenced by elementSize().
instance_
const TPEFResourceSectionWriter TPEF::TPEFResourceSectionWriter::instance_ static private
An unique instance of class.
Definition at line 67 of file TPEFResourceSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFResourceSectionWriter.hh
TPEFResourceSectionWriter.cc