OpenASIP: TTAMachine::ResourceVectorSet Class Reference
TTAMachine::ResourceVectorSet Class Reference
#include <ResourceVectorSet.hh>
Public Member Functions
ResourceVectorSet (const TTAMachine::FunctionUnit &functionUnit)
virtual ~ResourceVectorSet ()
const ResourceVector & resourceVector (const std::string &operationName) const
std::size_t operationIndex (const std::string &operationName) const
std::size_t resourceVectorCount () const
const ResourceVector & resourceVector (std::size_t index) const
std::string operationName (std::size_t index) const
std::size_t width () const
bool operator== (const ResourceVectorSet &rightHand) const
Private Types
typedef std::map< std::string, ResourceVector * > ResourceVectorIndex
Container for indexing the resource vectors by the operation name.
Private Attributes
ResourceVectorIndex vectors_
Storage for the resource vectors.
std::size_t width_
Width of the longest resource vector.
Detailed Description
Represents a set of resource vectors used in building the states in case of an function unit FSA.
Definition at line 47 of file ResourceVectorSet.hh.
Member Typedef Documentation
ResourceVectorIndex
typedef std::map<std::string, ResourceVector*> TTAMachine::ResourceVectorSet::ResourceVectorIndex private
Container for indexing the resource vectors by the operation name.
Definition at line 70 of file ResourceVectorSet.hh.
Constructor & Destructor Documentation
ResourceVectorSet()
TTAMachine::ResourceVectorSet::ResourceVectorSet (const TTAMachine::FunctionUnit & functionUnit)
Builds the resource vectors for the given FU.
Resource vectors are built for all operations in the FU.
Parameters
functionUnit The function unit to build the resource vectors for.
Exceptions
InvalidData In case the function unit is incomplete to build resource vectors for (e.g., missing operand-port bindings).
Definition at line 55 of file ResourceVectorSet.cc.
    : width_(0) {
    try {
        // add the port usages of each operation and resource usages
        for (int i = 0; i < functionUnit.operationCount(); ++i) {
            const TTAMachine::HWOperation* op = functionUnit.operation(i);
            ResourceVector* rv =
                new ResourceVector(*op->pipeline());
            vectors_[StringTools::stringToUpper(op->name())] = rv;
            width_ = std::max(width_, rv->width());
        }
    } catch (const Exception& e) {
        InvalidData io(
            __FILE__, __LINE__, __func__,
            "Error building the resource vectors");
        io.setCause(e);
        throw io;
    }
}
References __func__, TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::HWOperation::pipeline(), Exception::setCause(), StringTools::stringToUpper(), vectors_, TTAMachine::ResourceVector::width(), and width_.
~ResourceVectorSet()
TTAMachine::ResourceVectorSet::~ResourceVectorSet () virtual
Destructor.
Definition at line 79 of file ResourceVectorSet.cc.
{
    AssocTools::deleteAllValues(vectors_);
}
References AssocTools::deleteAllValues(), and vectors_.
Member Function Documentation
operationIndex()
std::size_t TTAMachine::ResourceVectorSet::operationIndex (const std::string & operationName) const
Returns the index of the operation with the given name.
Parameters
operationName The name of the operation.
Returns
Index of the operation.
Exceptions
KeyNotFound If the operation is not found.
Definition at line 160 of file ResourceVectorSet.cc.
{
    int counter = 0;
    for (ResourceVectorIndex::const_iterator i = vectors_.begin();
         i != vectors_.end(); ++i) {
        if ((*i).first == operationName)
            return counter;
        ++counter;
    }
    throw KeyNotFound(__FILE__, __LINE__, __func__, "Operation not found.");
}
References __func__, operationName(), and vectors_.
Referenced by ResourceVectorFUResourceConflictDetector::operationID().
operationName()
std::string TTAMachine::ResourceVectorSet::operationName (std::size_t index) const
Returns the name of the operation of the resource vector at the given index.
Parameters
index The index.
Returns
The operation name.
Definition at line 139 of file ResourceVectorSet.cc.
{
    int counter = index;
    for (ResourceVectorIndex::const_iterator i = vectors_.begin();
         i != vectors_.end(); ++i) {
        if (counter == 0)
            return (*i).first;
        --counter;
    }
    // should never get here
    return (*vectors_.end()).first;
}
References vectors_.
Referenced by operationIndex(), and resourceVector().
operator==()
bool TTAMachine::ResourceVectorSet::operator== (const ResourceVectorSet & rightHand) const
Compares two ResourceVectorSets.
Parameters
rightHand Right hand operand.
Returns
True is the two sets match false otherwise.
Definition at line 189 of file ResourceVectorSet.cc.
{
    if (resourceVectorCount() != rightHand.resourceVectorCount()) {
        return false;
    }
    ResourceVectorIndex::const_iterator iter = vectors_.begin();
    for (; iter != vectors_.end(); iter++) {
        try {
            if (!((*(*iter).second) ==
                  rightHand.resourceVector((*iter).first))) {
                return false;
            }
        } catch (KeyNotFound& e) {
            return false;
        }
    }
    return true;
}
References resourceVector(), resourceVectorCount(), and vectors_.
resourceVector() [1/2]
const ResourceVector & TTAMachine::ResourceVectorSet::resourceVector (const std::string & operationName) const
Returns the resource vector associated with the given operation.
Parameters
operationName The operation name.
Returns
The resource vector.
Exceptions
KeyNotFound If the operation is not found.
Definition at line 91 of file ResourceVectorSet.cc.
{
    const std::string opName = StringTools::stringToUpper(operationName);
    if (!AssocTools::containsKey(vectors_, opName)) {
        std::string message = "No resource vector found for operation " +
            operationName + ".";
        throw KeyNotFound(
            __FILE__, __LINE__, __func__, message);
    }
    return *(*vectors_.find(opName)).second;
}
References __func__, AssocTools::containsKey(), operationName(), StringTools::stringToUpper(), and vectors_.
Referenced by ResourceVectorFUResourceConflictDetector::issueOperation(), and operator==().
resourceVector() [2/2]
const ResourceVector & TTAMachine::ResourceVectorSet::resourceVector (std::size_t index) const
Returns the resource vector at the given index.
Parameters
index The index.
Returns
The resource vector.
Definition at line 119 of file ResourceVectorSet.cc.
{
    int counter = index;
    for (ResourceVectorIndex::const_iterator i = vectors_.begin();
         i != vectors_.end(); ++i) {
        if (counter == 0)
            return *((*i).second);
        --counter;
    }
    // should never get here
    return *((*vectors_.end()).second);
}
References vectors_.
resourceVectorCount()
std::size_t TTAMachine::ResourceVectorSet::resourceVectorCount () const
Returns the count of resource vectors in the set.
Returns
The count.
Definition at line 108 of file ResourceVectorSet.cc.
{
    return vectors_.size();
}
References vectors_.
Referenced by operator==().
width()
std::size_t TTAMachine::ResourceVectorSet::width () const
Returns the width of the longest resource vector in the resource vector set.
Returns
The width.
Definition at line 177 of file ResourceVectorSet.cc.
{
    return width_;
}
References width_.
Member Data Documentation
vectors_
ResourceVectorIndex TTAMachine::ResourceVectorSet::vectors_ private
Storage for the resource vectors.
Definition at line 72 of file ResourceVectorSet.hh.
Referenced by operationIndex(), operationName(), operator==(), resourceVector(), resourceVector(), resourceVectorCount(), ResourceVectorSet(), and ~ResourceVectorSet().
width_
std::size_t TTAMachine::ResourceVectorSet::width_ private
Width of the longest resource vector.
Definition at line 74 of file ResourceVectorSet.hh.
Referenced by ResourceVectorSet(), and width().
The documentation for this class was generated from the following files:
ResourceVectorSet.hh
ResourceVectorSet.cc