OpenASIP: TPEF::AOutStringSectionReader Class Reference
TPEF::AOutStringSectionReader Class Reference
#include <AOutStringSectionReader.hh>
Public Member Functions
virtual ~AOutStringSectionReader ()
Public Member Functions inherited from TPEF::AOutSectionReader
virtual ~AOutSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Protected Member Functions
AOutStringSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::AOutSectionReader
AOutSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
AOutStringSectionReader (const AOutStringSectionReader &)
Copying not allowed.
AOutStringSectionReader & operator= (const AOutStringSectionReader &)
Assignment not allowed.
Static Private Attributes
static AOutStringSectionReader proto_
Static attribute enables registering to SectionReader before main function is executed.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads string section from a.out binary file.
Definition at line 47 of file AOutStringSectionReader.hh.
Constructor & Destructor Documentation
~AOutStringSectionReader()
TPEF::AOutStringSectionReader::~AOutStringSectionReader () virtual
Destructor.
Definition at line 63 of file AOutStringSectionReader.cc.
{
}
AOutStringSectionReader() [1/2]
TPEF::AOutStringSectionReader::AOutStringSectionReader () protected
Constructor.
Registers to SectionReader.
Definition at line 56 of file AOutStringSectionReader.cc.
                                                 : AOutSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
AOutStringSectionReader() [2/2]
TPEF::AOutStringSectionReader::AOutStringSectionReader (const AOutStringSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
AOutStringSectionReader & TPEF::AOutStringSectionReader::operator= (const AOutStringSectionReader &) private
Assignment not allowed.
readData()
void TPEF::AOutStringSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads string section from a.out binary file.
Reads section from stream and makes sure that section starts withs zero.
Parameters
stream Stream to be read from.
section Section where to the information is stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Implements TPEF::SectionReader.
Definition at line 92 of file AOutStringSectionReader.cc.
{
    AOutReader* aOutReader = dynamic_cast<AOutReader*>(parent());
    StringSection* strSect = dynamic_cast<StringSection*>(section);
    assert(strSect != NULL);
    for (unsigned int i = 0;
         i < aOutReader->header().sectionSizeString(); i++) {
        strSect->addByte(stream.readByte());
    }
    // add zero byte if no data
    if (strSect->length() == 0) {
        strSect->addByte(0);
    }
    // section must start with zero.
    assert(strSect->byte(strSect->chunk(0)) == 0);
}
References TPEF::DataSection::addByte(), assert, TPEF::DataSection::byte(), TPEF::RawSection::chunk(), TPEF::AOutReader::header(), TPEF::DataSection::length(), TPEF::AOutSectionReader::parent(), and TPEF::BinaryStream::readByte().
type()
Section::SectionType TPEF::AOutStringSectionReader::type () const protected virtual
Returns the type of section that this class can read.
Returns
Type of section to read.
Implements TPEF::SectionReader.
Definition at line 72 of file AOutStringSectionReader.cc.
{
    return Section::ST_STRTAB;
}
References TPEF::Section::ST_STRTAB.
Member Data Documentation
proto_
AOutStringSectionReader TPEF::AOutStringSectionReader::proto_ static private
Static attribute enables registering to SectionReader before main function is executed.
Definition at line 66 of file AOutStringSectionReader.hh.
The documentation for this class was generated from the following files:
AOutStringSectionReader.hh
AOutStringSectionReader.cc