OpenASIP: TTAProgram::DataMemory Class Reference
TTAProgram::DataMemory Class Reference
#include <DataMemory.hh>
Public Member Functions
DataMemory (const TTAMachine::AddressSpace &aSpace)
virtual ~DataMemory ()
void addDataDefinition (DataDefinition *dataDef)
DataDefinition & dataDefinition (Address address) const
DataDefinition & dataDefinition (int index) const
int dataDefinitionCount () const
int dataDefinitionsEnd () const
void deleteDataDefinition (int index)
const TTAMachine::AddressSpace & addressSpace () const
void setAddressSpace (const TTAMachine::AddressSpace &space)
DataMemory * copy () const
Private Types
typedef std::map< AddressImage, DataDefinition * > DataDefMap
Map for data definitions.
Private Attributes
const TTAMachine::AddressSpace * ramSpace_
Address space of the memory.
DataDefMap dataDefs_
Data definitions for the address space.
std::vector< DataDefinition * > indexCache_
Cache for indexing dataDefinitions.
Detailed Description
Represents an address space containing data.
Data definitions are ordered in the DataMemory class so that largest index contains the last data definition.
Definition at line 56 of file DataMemory.hh.
Member Typedef Documentation
DataDefMap
typedef std::map<AddressImage, DataDefinition*> TTAProgram::DataMemory::DataDefMap private
Map for data definitions.
Definition at line 76 of file DataMemory.hh.
Constructor & Destructor Documentation
DataMemory()
TTAProgram::DataMemory::DataMemory (const TTAMachine::AddressSpace & aSpace)
Sets address space of the memory.
Parameters
aSpace Address space of the memory.
Definition at line 46 of file DataMemory.cc.
                                                           :
    ramSpace_(&aSpace) {
}
~DataMemory()
TTAProgram::DataMemory::~DataMemory () virtual
Deletes all the added definitions.
Definition at line 53 of file DataMemory.cc.
{
    MapTools::deleteAllValues(dataDefs_);
}
References dataDefs_, and MapTools::deleteAllValues().
Member Function Documentation
addDataDefinition()
void TTAProgram::DataMemory::addDataDefinition (DataDefinition * dataDef)
Adds data to memory.
Data definitions are sorted by starting address of defined area.
Parameters
dataDef Definition to add.
Definition at line 66 of file DataMemory.cc.
{
    dataDefs_[dataDef->startAddress().location()] = dataDef;
    // clear index cache since indices may change
    indexCache_.clear();
}
References dataDefs_, indexCache_, TTAProgram::Address::location(), and TTAProgram::DataDefinition::startAddress().
Referenced by copy(), TTAProgram::Program::copyDataMemoriesFrom(), llvm::LLVMTCEBuilder::createDataDefinition(), TTAProgram::TPEFProgramFactory::createDataMemories(), llvm::LLVMTCEBuilder::createFPDataDefinition(), llvm::LLVMTCEBuilder::createGlobalValueDataDefinition(), llvm::LLVMTCEBuilder::createIntDataDefinition(), llvm::LLVMTCEBuilder::emitDataDef(), llvm::LLVMTCEBuilder::emitSPInitialization(), llvm::LLVMTCEBuilder::initDataSections(), and llvm::LLVMTCEBuilder::padToAlignment().
addressSpace()
const TTAMachine::AddressSpace & TTAProgram::DataMemory::addressSpace () const
Returns the address space of the data memory.
Returns
The address space of the data memory.
Definition at line 182 of file DataMemory.cc.
{
    return *ramSpace_;
}
References ramSpace_.
Referenced by TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::Program::dataMemory(), POMDisassembler::disassembleProgram(), SimulatorFrontend::initializeDataMemories(), and main().
copy()
DataMemory * TTAProgram::DataMemory::copy () const
POM style copy constructor, which supports dynamic binding.
Returns
Copy of the object.
Definition at line 206 of file DataMemory.cc.
                       {
    DataMemory* memCopy = new DataMemory(*ramSpace_);
    for (int i = 0; i < dataDefinitionCount(); i++) {
        memCopy->addDataDefinition(dataDefinition(i).copy());
    }
    return memCopy;
}
References addDataDefinition(), TTAProgram::DataDefinition::copy(), dataDefinition(), dataDefinitionCount(), and ramSpace_.
dataDefinition() [1/2]
DataDefinition & TTAProgram::DataMemory::dataDefinition (Address address) const
Finds the data definition, which contains the requested address.
Parameters
address Address whose data definition is requested.
Returns
Data definition, which contains requested address.
Definition at line 79 of file DataMemory.cc.
{
    std::map<AddressImage, DataDefinition*>::const_iterator iter =
        dataDefs_.upper_bound(address.location());
    if (iter != dataDefs_.begin()) {
        iter--;
        DataDefinition* dataDef = (*iter).second;
        // this data definition should contain the requested address
        if (address.location() < dataDef->startAddress().location() +
            dataDef->size()) {
            return *dataDef;
        }
    }
    throw NotAvailable(
        __FILE__, __LINE__, __func__,
        "Address space: " + ramSpace_->name() +
        " does not contain data definition for requested address:" +
        Conversion::toString(address.location()));
}
References __func__, dataDefs_, TTAProgram::Address::location(), TTAMachine::Component::name(), ramSpace_, TTAProgram::DataDefinition::size(), TTAProgram::DataDefinition::startAddress(), and Conversion::toString().
Referenced by StaticProgramAnalyzer::addProgram(), ControlFlowGraph::computeLeadersFromRelocations(), copy(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), llvm::LLVMTCEBuilder::deleteDeadProcedures(), POMDisassembler::disassembleProgram(), SimulatorFrontend::initializeDataMemories(), main(), TTAProgram::Program::replaceUniversalAddressSpaces(), and setAddressSpace().
dataDefinition() [2/2]
DataDefinition & TTAProgram::DataMemory::dataDefinition (int index) const
Finds the data definition by index.
Indices may change if new definitions are added to memory.
Parameters
index Index of the requested data definition.
Returns
Data definition, which contains requested address.
Definition at line 110 of file DataMemory.cc.
{
    if (indexCache_.empty()) {
        // create cache
        for (std::map<AddressImage, DataDefinition*>::const_iterator iter =
                 dataDefs_.begin(); iter != dataDefs_.end(); iter++) {
            indexCache_.push_back((*iter).second);
        }
    }
    return *indexCache_[index];
}
References dataDefs_, and indexCache_.
dataDefinitionCount()
int TTAProgram::DataMemory::dataDefinitionCount () const
Returns the number of data definitions stored in memory.
Returns
Number of data definitions.
Definition at line 129 of file DataMemory.cc.
{
    return dataDefs_.size();
}
References dataDefs_, and TTAProgram::DataDefinition::size().
Referenced by StaticProgramAnalyzer::addProgram(), ControlFlowGraph::computeLeadersFromRelocations(), copy(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), deleteDataDefinition(), POMDisassembler::disassembleProgram(), SimulatorFrontend::initializeDataMemories(), main(), TTAProgram::Program::replaceUniversalAddressSpaces(), and setAddressSpace().
dataDefinitionsEnd()
int TTAProgram::DataMemory::dataDefinitionsEnd () const
Returns the place where the data definitions end. Calculates it based only on the last data definition (since dataDefs_ is sorted).
Returns
int end of data definitions
Definition at line 141 of file DataMemory.cc.
{
    std::map<AddressImage, DataDefinition*>::const_reverse_iterator iter =
        dataDefs_.rbegin();
    if (iter != dataDefs_.rend()) {
        DataDefinition* dataDef = (*iter).second;
        // this data definition should be the last one
        return dataDef->startAddress().location() + dataDef->size();
    }
    // no data definitions added
    return 0;
}
References dataDefs_, TTAProgram::Address::location(), TTAProgram::DataDefinition::size(), and TTAProgram::DataDefinition::startAddress().
deleteDataDefinition()
void TTAProgram::DataMemory::deleteDataDefinition (int index)
Deletes the data definition at the given index.
Parameters
index Which data definition to delete.
Definition at line 160 of file DataMemory.cc.
{
    if (index < 0 || index >= dataDefinitionCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    DataDefMap::iterator iter = dataDefs_.begin();
    for (int i = 0; i < index; i++) {
        iter++;
    }
    dataDefs_.erase(iter);
    indexCache_.clear();
}
References __func__, dataDefinitionCount(), dataDefs_, and indexCache_.
setAddressSpace()
void TTAProgram::DataMemory::setAddressSpace (const TTAMachine::AddressSpace & space)
Set new address space for the data memory.
Parameters
space New address space.
Definition at line 192 of file DataMemory.cc.
{
    ramSpace_ = &space;
    for (int i = 0; i < dataDefinitionCount(); i++) {
        DataDefinition& def = dataDefinition(i);
        def.setStartAddress(Address(def.startAddress().location(), space));
    }
}
References dataDefinition(), dataDefinitionCount(), TTAProgram::Address::location(), ramSpace_, TTAProgram::DataDefinition::setStartAddress(), and TTAProgram::DataDefinition::startAddress().
Referenced by TTAProgram::Program::replaceUniversalAddressSpaces().
Member Data Documentation
dataDefs_
DataDefMap TTAProgram::DataMemory::dataDefs_ private
Data definitions for the address space.
Definition at line 82 of file DataMemory.hh.
Referenced by addDataDefinition(), dataDefinition(), dataDefinition(), dataDefinitionCount(), dataDefinitionsEnd(), deleteDataDefinition(), and ~DataMemory().
indexCache_
std::vector<DataDefinition*> TTAProgram::DataMemory::indexCache_ mutable private
Cache for indexing dataDefinitions.
Definition at line 85 of file DataMemory.hh.
Referenced by addDataDefinition(), dataDefinition(), and deleteDataDefinition().
ramSpace_
const TTAMachine::AddressSpace* TTAProgram::DataMemory::ramSpace_ private
Address space of the memory.
Definition at line 79 of file DataMemory.hh.
Referenced by addressSpace(), copy(), dataDefinition(), and setAddressSpace().
The documentation for this class was generated from the following files:
DataMemory.hh
DataMemory.cc