OpenASIP: SequentialMoveNodeSelector Class Reference
SequentialMoveNodeSelector Class Reference
#include <SequentialMoveNodeSelector.hh>
Public Member Functions
SequentialMoveNodeSelector (TTAProgram::BasicBlock &bb)
virtual ~SequentialMoveNodeSelector ()
virtual MoveNodeGroup candidates ()
virtual void notifyScheduled (MoveNode &node)
void mightBeReady (MoveNode &node)
Public Member Functions inherited from MoveNodeSelector
MoveNodeSelector ()
virtual ~MoveNodeSelector ()
Private Types
typedef std::list< ProgramOperation * > ProgramOperationList
typedef std::list< MoveNodeGroup * > MNGList
Private Member Functions
void createMoveNodes (TTAProgram::BasicBlock &bb)
Private Attributes
MNGList * mngs_
MNGList::iterator mngIter_
Detailed Description
Selects move nodes from a basic block in their sequential input order.
Definition at line 47 of file SequentialMoveNodeSelector.hh.
Member Typedef Documentation
MNGList
typedef std::list<MoveNodeGroup*> SequentialMoveNodeSelector::MNGList private
Definition at line 61 of file SequentialMoveNodeSelector.hh.
ProgramOperationList
typedef std::list<ProgramOperation*> SequentialMoveNodeSelector::ProgramOperationList private
Definition at line 60 of file SequentialMoveNodeSelector.hh.
Constructor & Destructor Documentation
SequentialMoveNodeSelector()
SequentialMoveNodeSelector::SequentialMoveNodeSelector (TTAProgram::BasicBlock & bb)
Constructor.
Parameters
bb Basic block containing moves to be selected.
Definition at line 58 of file SequentialMoveNodeSelector.cc.
{
    MoveNodeGroupBuilder builder;
    mngs_ = builder.build(bb);
    mngIter_ = mngs_->begin();
}
References MoveNodeGroupBuilder::build(), mngIter_, and mngs_.
~SequentialMoveNodeSelector()
SequentialMoveNodeSelector::~SequentialMoveNodeSelector () virtual
Definition at line 65 of file SequentialMoveNodeSelector.cc.
{
    while(!mngs_->empty()) {
        std::list<MoveNodeGroup*>::iterator iter = mngs_->begin();
        MoveNodeGroup* mng = *iter;
        for (int i = 0; i < mng->nodeCount(); i++) {
            delete &mng->node(i);
        }
        delete mng;
        mngs_->erase(iter);
    }
    delete mngs_;
}
References mngs_, MoveNodeGroup::node(), and MoveNodeGroup::nodeCount().
Member Function Documentation
candidates()
MoveNodeGroup SequentialMoveNodeSelector::candidates () virtual
Gives a group of unselected movenodes to schedules.
This always returns them in order; and every one just once. Returns an empty MNG when there's no more MNGS to return.
Implements MoveNodeSelector.
Definition at line 85 of file SequentialMoveNodeSelector.cc.
{
    // are there any unselected movenodegroups left?
    if (mngIter_ != mngs_->end()) {
        return **mngIter_++;
    } else {
        // return empty mng
        return MoveNodeGroup();
    }
}
References mngIter_, and mngs_.
Referenced by SequentialScheduler::handleBasicBlock().
createMoveNodes()
void SequentialMoveNodeSelector::createMoveNodes (TTAProgram::BasicBlock & bb) private
mightBeReady()
void SequentialMoveNodeSelector::mightBeReady (MoveNode & node) virtual
This should be called by the client when some incoming dependence to a moveNode is removed.
Parameters
node Node which has lost some incoming dependence
Implements MoveNodeSelector.
Definition at line 96 of file SequentialMoveNodeSelector.cc.
{
}
notifyScheduled()
void SequentialMoveNodeSelector::notifyScheduled (MoveNode & node) virtual
This should be called by the client as soon as a MoveNode is scheduled in order to update the internal state of the selector.
Parameters
node The scheduled MoveNode.
Implements MoveNodeSelector.
Definition at line 100 of file SequentialMoveNodeSelector.cc.
{
}
Referenced by SequentialScheduler::handleBasicBlock().
Member Data Documentation
mngIter_
MNGList::iterator SequentialMoveNodeSelector::mngIter_ private
Definition at line 66 of file SequentialMoveNodeSelector.hh.
Referenced by candidates(), and SequentialMoveNodeSelector().
mngs_
MNGList* SequentialMoveNodeSelector::mngs_ private
Definition at line 63 of file SequentialMoveNodeSelector.hh.
Referenced by candidates(), SequentialMoveNodeSelector(), and ~SequentialMoveNodeSelector().
The documentation for this class was generated from the following files:
SequentialMoveNodeSelector.hh
SequentialMoveNodeSelector.cc