OpenASIP: CopyComponentCmd Class Reference
CopyComponentCmd Class Reference
#include <CopyComponentCmd.hh>
Public Member Functions
CopyComponentCmd ()
virtual bool Do ()
virtual int id () const
virtual CopyComponentCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for copying machine components to the clipboard.
Definition at line 43 of file CopyComponentCmd.hh.
Constructor & Destructor Documentation
CopyComponentCmd()
CopyComponentCmd::CopyComponentCmd ()
The Constructor.
Definition at line 50 of file CopyComponentCmd.cc.
                                  :
    EditorCommand(ProDeConstants::CMD_NAME_COPY) {
}
Referenced by create().
Member Function Documentation
create()
CopyComponentCmd * CopyComponentCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 108 of file CopyComponentCmd.cc.
{
    return new CopyComponentCmd();
}
References CopyComponentCmd().
Do()
bool CopyComponentCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 62 of file CopyComponentCmd.cc.
                     {
    assert(view() != NULL);
    // send copy request to the selected EditPart
    Request* copyRequest = new Request(Request::COPY_REQUEST);
    EditPart* selected = dynamic_cast<MDFView*>(view())->selection();
    if (selected == NULL) {
        return false;
    }
    ComponentCommand* command = selected->performRequest(copyRequest);
    // execute the returned command
    if (command == NULL) {
        return false;
    } else {
        dynamic_cast<MDFView*>(view())->clearSelection();
        command->setParentWindow(parentWindow());
    // Copying component to clipboard doesn't modify model.
    // The model is not pushed into the undo stack.
        bool result = command->Do();
        return result;
    }
}
References assert, Request::COPY_REQUEST, ComponentCommand::Do(), GUICommand::parentWindow(), EditPart::performRequest(), ComponentCommand::setParentWindow(), and EditorCommand::view().
icon()
string CopyComponentCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 120 of file CopyComponentCmd.cc.
{
    return ProDeConstants::CMD_ICON_COPY;
}
References ProDeConstants::CMD_ICON_COPY.
id()
int CopyComponentCmd::id () const virtual
Returns command identifier of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 97 of file CopyComponentCmd.cc.
{
    return ProDeConstants::COMMAND_COPY;
}
References ProDeConstants::COMMAND_COPY.
isEnabled()
bool CopyComponentCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a component is selected, and the selected component can be copied.
Returns
True, if a component is selected.
Reimplemented from EditorCommand.
Definition at line 135 of file CopyComponentCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    MDFView* mdfView = dynamic_cast<MDFView*>(manager->GetCurrentView());
    if (mdfView == NULL) {
    return false;
    }
    EditPart* selected = mdfView->selection();
    Request* copyRequest = new Request(Request::COPY_REQUEST);
    if (selected == NULL || !(selected->canHandle(copyRequest))) {
    delete copyRequest;
    return false;
    }
    delete copyRequest;
    return true;
}
References EditPart::canHandle(), Request::COPY_REQUEST, and MDFView::selection().
The documentation for this class was generated from the following files:
CopyComponentCmd.hh
CopyComponentCmd.cc