OpenASIP: HDB::RFPortImplementation Class Reference
HDB::RFPortImplementation Class Reference
#include <RFPortImplementation.hh>
Public Member Functions
RFPortImplementation (const std::string &name, Direction direction, const std::string &loadPort, const std::string &opcodePort, const std::string &opcodePortWidthFormula, RFImplementation &parent)
virtual ~RFPortImplementation ()
void setDirection (Direction direction)
Direction direction () const
void setOpcodePort (const std::string &name)
std::string opcodePort () const
void setOpcodePortWidthFormula (const std::string &formula)
std::string opcodePortWidthFormula () const
Public Member Functions inherited from HDB::PortImplementation
PortImplementation (const std::string &name, const std::string &loadPort)
virtual ~PortImplementation ()
void setName (const std::string &name)
std::string name () const
void setLoadPort (const std::string &name)
std::string loadPort () const
Private Attributes
Direction direction_
Direction of the port.
std::string opcodePort_
Name of the opcode port.
std::string opcodePortWidthFormula_
Width calculation formula for the opcode port.
Detailed Description
Definition at line 43 of file RFPortImplementation.hh.
Constructor & Destructor Documentation
RFPortImplementation()
HDB::RFPortImplementation::RFPortImplementation (const std::string & name, Direction direction, const std::string & loadPort, const std::string & opcodePort, const std::string & opcodePortWidthFormula, RFImplementation & parent)
The constructor.
Adds the port automatically to the given parent RF implementation.
Parameters
name Name of the port.
direction Direction of the port.
loadPort Name of the load enable port.
opcodePort Name of the opcode port.
parent The parent RF implementation.
Definition at line 49 of file RFPortImplementation.cc.
                              :
    PortImplementation(name, loadPort), direction_(direction),
    opcodePort_(opcodePort),
    opcodePortWidthFormula_(opcodePortWidthFormula) {
    parent.addPort(this);
}
References HDB::RFImplementation::addPort().
~RFPortImplementation()
HDB::RFPortImplementation::~RFPortImplementation () virtual
The destructor.
Definition at line 67 of file RFPortImplementation.cc.
{
}
Member Function Documentation
direction()
Direction HDB::RFPortImplementation::direction () const
Returns the direction of the port.
Returns
The direction of the port.
Definition at line 88 of file RFPortImplementation.cc.
{
    return direction_;
}
References direction_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFImplementation(), RFTestbenchGenerator::parseRfPorts(), HDBToHtml::rfImplToHtml(), and setDirection().
opcodePort()
std::string HDB::RFPortImplementation::opcodePort () const
Returns the name of the opcode port.
Returns
The name of the opcode port.
Definition at line 110 of file RFPortImplementation.cc.
{
    return opcodePort_;
}
References opcodePort_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFImplementation(), RFTestbenchGenerator::parseRfPorts(), and HDBToHtml::rfImplToHtml().
opcodePortWidthFormula()
std::string HDB::RFPortImplementation::opcodePortWidthFormula () const
Returns the formula of the width of the opcode port.
Returns
The formula.
Definition at line 132 of file RFPortImplementation.cc.
{
    return opcodePortWidthFormula_;
}
References opcodePortWidthFormula_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFImplementation(), and HDBToHtml::rfImplToHtml().
setDirection()
void HDB::RFPortImplementation::setDirection (Direction direction)
Sets the direction of the port.
Parameters
direction The new direction.
Definition at line 77 of file RFPortImplementation.cc.
{
    direction_ = direction;
}
References direction(), and direction_.
Referenced by RFPortImplementationDialog::onOK().
setOpcodePort()
void HDB::RFPortImplementation::setOpcodePort (const std::string & name)
Sets the name of the opcode port.
Parameters
name The new name.
Definition at line 99 of file RFPortImplementation.cc.
{
    opcodePort_ = name;
}
References HDB::PortImplementation::name(), and opcodePort_.
Referenced by RFPortImplementationDialog::onOK().
setOpcodePortWidthFormula()
void HDB::RFPortImplementation::setOpcodePortWidthFormula (const std::string & formula)
Sets the width formula of the opcode port.
Parameters
formula The new width formula.
Definition at line 121 of file RFPortImplementation.cc.
{
    opcodePortWidthFormula_ = formula;
}
References opcodePortWidthFormula_.
Referenced by RFPortImplementationDialog::onOK().
Member Data Documentation
direction_
Direction HDB::RFPortImplementation::direction_ private
Direction of the port.
Definition at line 63 of file RFPortImplementation.hh.
Referenced by direction(), and setDirection().
opcodePort_
std::string HDB::RFPortImplementation::opcodePort_ private
Name of the opcode port.
Definition at line 65 of file RFPortImplementation.hh.
Referenced by opcodePort(), and setOpcodePort().
opcodePortWidthFormula_
std::string HDB::RFPortImplementation::opcodePortWidthFormula_ private
Width calculation formula for the opcode port.
Definition at line 67 of file RFPortImplementation.hh.
Referenced by opcodePortWidthFormula(), and setOpcodePortWidthFormula().
The documentation for this class was generated from the following files:
RFPortImplementation.hh
RFPortImplementation.cc