OpenASIP: CallExplorerPluginCmd Class Reference
CallExplorerPluginCmd Class Reference
#include <CallExplorerPluginCmd.hh>
Public Member Functions
CallExplorerPluginCmd ()
virtual ~CallExplorerPluginCmd ()
virtual bool Do ()
virtual int id () const
virtual CallExplorerPluginCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening explorer plugin call window.
Definition at line 43 of file CallExplorerPluginCmd.hh.
Constructor & Destructor Documentation
CallExplorerPluginCmd()
CallExplorerPluginCmd::CallExplorerPluginCmd ()
The Constructor.
Definition at line 46 of file CallExplorerPluginCmd.cc.
                                            :
    EditorCommand(ProDeConstants::CMD_CALL_EXPLORER_PLUGIN) {
}
Referenced by create().
~CallExplorerPluginCmd()
CallExplorerPluginCmd::~CallExplorerPluginCmd () virtual
The Destructor.
Definition at line 55 of file CallExplorerPluginCmd.cc.
{}
Member Function Documentation
create()
CallExplorerPluginCmd * CallExplorerPluginCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 101 of file CallExplorerPluginCmd.cc.
{
    return new CallExplorerPluginCmd();
}
References CallExplorerPluginCmd().
Do()
bool CallExplorerPluginCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file CallExplorerPluginCmd.cc.
{
    TTAMachine::Machine* machine = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel()->getMachine();
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    CallExplorerPluginWindow dialog(parentWindow(), *machine, *model);
    if (dialog.ShowModal() == wxID_OK) {
        model->notifyObservers();
        return true;
    } else {
        model->popFromStack();
        return false;
    }
    return true;
}
References machine, Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string CallExplorerPluginCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 111 of file CallExplorerPluginCmd.cc.
{
    return ProDeConstants::CMD_ICON_EXPLORER_PLUGIN;
}
References ProDeConstants::CMD_ICON_EXPLORER_PLUGIN.
id()
int CallExplorerPluginCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 92 of file CallExplorerPluginCmd.cc.
{
    return ProDeConstants::COMMAND_CALL_EXPLORER_PLUGIN;
}
References ProDeConstants::COMMAND_CALL_EXPLORER_PLUGIN.
isEnabled()
bool CallExplorerPluginCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 133 of file CallExplorerPluginCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string CallExplorerPluginCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 120 of file CallExplorerPluginCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EXPLORER_PLUGIN;
}
References ProDeConstants::CMD_SNAME_EXPLORER_PLUGIN.
The documentation for this class was generated from the following files:
CallExplorerPluginCmd.hh
CallExplorerPluginCmd.cc