OpenASIP: DisasmTopCountAttrProvider Class Reference
DisasmTopCountAttrProvider Class Reference
#include <DisasmTopCountAttrProvider.hh>
Public Types
typedef std::set< InstructionAddress > AddressSet
typedef std::map< ClockCycleCount, AddressSet > ExecutionCountTable
Public Member Functions
DisasmTopCountAttrProvider (TracedSimulatorFrontend &simulator, size_t topCounts)
virtual ~DisasmTopCountAttrProvider ()
virtual void update ()
virtual wxGridCellAttr * moveCellAttr (InstructionAddress address, int move)
Public Member Functions inherited from ProximDisasmAttrProvider
ProximDisasmAttrProvider ()
virtual ~ProximDisasmAttrProvider ()
Private Member Functions
void updateTopCountTable ()
void addToTopCountTable (InstructionAddress address, ClockCycleCount execCount)
void createExecCountWindow ()
wxColour bgColour (ClockCycleCount execCount)
Private Attributes
ExecutionCountTable topCountTable_
Top execution counts and set of instruction addresses with each count.
TracedSimulatorFrontend & simulator_
Simulator frontend used for accessing the instructions and exec counts.
size_t topCounts_
Number of top execution counts in the top execution count list.
DisasmExecCountFrame * listWin_
Detailed Description
Attribute provider for disassembly window grid.
Highlights instructions with top execution counts with background colour.
Definition at line 53 of file DisasmTopCountAttrProvider.hh.
Member Typedef Documentation
AddressSet
typedef std::set<InstructionAddress> DisasmTopCountAttrProvider::AddressSet
Definition at line 62 of file DisasmTopCountAttrProvider.hh.
ExecutionCountTable
typedef std::map<ClockCycleCount, AddressSet> DisasmTopCountAttrProvider::ExecutionCountTable
Definition at line 63 of file DisasmTopCountAttrProvider.hh.
Constructor & Destructor Documentation
DisasmTopCountAttrProvider()
DisasmTopCountAttrProvider::DisasmTopCountAttrProvider (TracedSimulatorFrontend & simulator, size_t topCounts)
The Constructor.
Parameters
simulator Simulator frontend for accessing instructions and execution counts.
topCounts Number of top execution counts to list and highlight.
Definition at line 170 of file DisasmTopCountAttrProvider.cc.
                                                         :
    ProximDisasmAttrProvider(),
    simulator_(simulator), topCounts_(topCounts) {
    listWin_ = new DisasmExecCountFrame(
        ProximToolbox::disassemblyWindow(), -1, topCountTable_);
    listWin_->Show();
}
References ProximToolbox::disassemblyWindow(), listWin_, and topCountTable_.
~DisasmTopCountAttrProvider()
DisasmTopCountAttrProvider::~DisasmTopCountAttrProvider () virtual
The Destructor.
Definition at line 185 of file DisasmTopCountAttrProvider.cc.
{
    if (listWin_ != NULL) {
        listWin_->Destroy();
    }
}
References listWin_.
Member Function Documentation
addToTopCountTable()
void DisasmTopCountAttrProvider::addToTopCountTable (InstructionAddress address, ClockCycleCount execCount) private
Adds an instruction to the execution top count list if the count is high enough for the list.
Parameters
address Address of the instruction.
execCount Execution count of the instruction.
Definition at line 256 of file DisasmTopCountAttrProvider.cc.
{
    ExecutionCountTable::iterator iter = topCountTable_.find(execCount);
    if (iter != topCountTable_.end()) {
        (*iter).second.insert(address);
    } else if (topCountTable_.empty() ||
               execCount > ((*topCountTable_.begin())).first) {
        AddressSet addressSet;
        addressSet.insert(address);
        topCountTable_.insert(
            std::pair<ClockCycleCount, AddressSet>(execCount, addressSet));
    }
    if (topCountTable_.size() > topCounts_) {
        topCountTable_.erase(topCountTable_.begin());
    }
}
References topCounts_, and topCountTable_.
Referenced by updateTopCountTable().
bgColour()
wxColour DisasmTopCountAttrProvider::bgColour (ClockCycleCount execCount) private
Returns background highlight colour for an instruction with the given exec count.
Parameters
execCount Execution count of the instruciton.
Returns
Background highlight colour for the instruction.
Definition at line 285 of file DisasmTopCountAttrProvider.cc.
{
    ExecutionCountTable::reverse_iterator iter = topCountTable_.rbegin();
    size_t pos = 0;
    while (iter != topCountTable_.rend()) {
        if ((*iter).first == execCount) {
            break;
        }
        pos++;
        iter++;
    }
    if (pos < topCounts_) {
        int value = pos * (255 / topCounts_);
        if (pos < (topCounts_ / 2)) {
            return wxColour(255 , 2 * value, 0);
        } else {
            return wxColour(255 - (2 * (value-128)), 255, 0);
        }
    } else {
        return wxColour(255, 255, 255);
    }
}
References topCounts_, and topCountTable_.
Referenced by moveCellAttr().
createExecCountWindow()
void DisasmTopCountAttrProvider::createExecCountWindow () private
moveCellAttr()
wxGridCellAttr * DisasmTopCountAttrProvider::moveCellAttr (InstructionAddress address, int move) virtual
Returns grid cell attributes for cell with given move.
Parameters
address Address of the cell's instruction.
Implements ProximDisasmAttrProvider.
Definition at line 207 of file DisasmTopCountAttrProvider.cc.
{
    wxGridCellAttr* attr = new wxGridCellAttr();
    ClockCycleCount execCount =
        simulator_.executableInstructionAt(address).executionCount();
    if (execCount == 0) {
        attr->SetBackgroundColour(wxColour(220, 220, 220));
    } else {
        attr->SetBackgroundColour(bgColour(execCount));
    }
    return attr;
}
References bgColour(), SimulatorFrontend::executableInstructionAt(), ExecutableInstruction::executionCount(), and simulator_.
update()
void DisasmTopCountAttrProvider::update () virtual
Updates the list of top execution counts when simulation stops.
Reimplemented from ProximDisasmAttrProvider.
Definition at line 195 of file DisasmTopCountAttrProvider.cc.
{
    updateTopCountTable();
    listWin_->update();
}
References listWin_, DisasmExecCountFrame::update(), and updateTopCountTable().
Referenced by HighlightTopExecCountsCmd::Do().
updateTopCountTable()
void DisasmTopCountAttrProvider::updateTopCountTable () private
Updates the list of top execution counts.
Definition at line 228 of file DisasmTopCountAttrProvider.cc.
{
    topCountTable_.clear();
    const TTAProgram::Program& program = simulator_.program();
    const TTAProgram::Instruction* instruction = &program.firstInstruction();
    while (instruction != &TTAProgram::NullInstruction::instance()) {
        InstructionAddress address = instruction->address().location();
        ClockCycleCount execCount =
            simulator_.executableInstructionAt(address).executionCount();
        if (execCount > 0) {
            addToTopCountTable(address, execCount);
        }
        instruction = &program.nextInstruction(*instruction);
    }
}
References TTAProgram::Instruction::address(), addToTopCountTable(), SimulatorFrontend::executableInstructionAt(), ExecutableInstruction::executionCount(), TTAProgram::NullInstruction::instance(), TTAProgram::Address::location(), program, SimulatorFrontend::program(), simulator_, and topCountTable_.
Referenced by update().
Member Data Documentation
listWin_
DisasmExecCountFrame* DisasmTopCountAttrProvider::listWin_ private
Definition at line 78 of file DisasmTopCountAttrProvider.hh.
Referenced by DisasmTopCountAttrProvider(), update(), and ~DisasmTopCountAttrProvider().
simulator_
TracedSimulatorFrontend& DisasmTopCountAttrProvider::simulator_ private
Simulator frontend used for accessing the instructions and exec counts.
Definition at line 75 of file DisasmTopCountAttrProvider.hh.
Referenced by moveCellAttr(), and updateTopCountTable().
topCounts_
size_t DisasmTopCountAttrProvider::topCounts_ private
Number of top execution counts in the top execution count list.
Definition at line 77 of file DisasmTopCountAttrProvider.hh.
Referenced by addToTopCountTable(), and bgColour().
topCountTable_
ExecutionCountTable DisasmTopCountAttrProvider::topCountTable_ private
Top execution counts and set of instruction addresses with each count.
Definition at line 73 of file DisasmTopCountAttrProvider.hh.
Referenced by addToTopCountTable(), bgColour(), DisasmTopCountAttrProvider(), and updateTopCountTable().
The documentation for this class was generated from the following files:
DisasmTopCountAttrProvider.hh
DisasmTopCountAttrProvider.cc