OpenASIP: BridgeFactory Class Reference
BridgeFactory Class Reference
#include <BridgeFactory.hh>
Public Member Functions
BridgeFactory (EditPolicyFactory &editPolicyFactory)
virtual ~BridgeFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
BridgeFactory & operator= (BridgeFactory &old)
Assignment not allowed.
BridgeFactory (BridgeFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating bridge EditParts corresponding to a given Machine Bridge object.
Definition at line 45 of file BridgeFactory.hh.
Constructor & Destructor Documentation
BridgeFactory() [1/2]
BridgeFactory::BridgeFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 50 of file BridgeFactory.cc.
                                                                :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new BusFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~BridgeFactory()
BridgeFactory::~BridgeFactory () virtual
The Destructor.
Definition at line 59 of file BridgeFactory.cc.
{
}
BridgeFactory() [2/2]
BridgeFactory::BridgeFactory (BridgeFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * BridgeFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a bridge.
Parameters
component Bridge of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the Bridge class.
Implements Factory.
Definition at line 70 of file BridgeFactory.cc.
{
    Bridge* bridge = dynamic_cast<Bridge*>(component);
    if (bridge != NULL) {
    ConnectionEditPart* bridgeEditPart = new ConnectionEditPart();
    bridgeEditPart->setModel(bridge);
    BridgeFigure* fig = new BridgeFigure();
    bridgeEditPart->setFigure(fig);
    vector<Factory*>::const_iterator iter;
    for (iter = factories_.begin(); iter != factories_.end(); iter++) {
        EditPart* busEditPart = (*iter)->createEditPart(
        (MachinePart*)bridge->sourceBus());
        if (busEditPart != NULL) {
        bridgeEditPart->setSource(busEditPart);
        bridgeEditPart->setTarget(
            (*iter)->createEditPart(
            (MachinePart*)bridge->destinationBus()));
        break;
        }
    }
    assert(bridgeEditPart->target() != NULL &&
           bridgeEditPart->source() != NULL);
    bridgeEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createBridgeEditPolicy();
    if (editPolicy != NULL) {
        bridgeEditPart->installEditPolicy(editPolicy);
    }
    return bridgeEditPart;
    } else {
    return NULL;
    }
}
References assert, EditPolicyFactory::createBridgeEditPolicy(), TTAMachine::Bridge::destinationBus(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), EditPart::setFigure(), EditPart::setModel(), EditPart::setSelectable(), ConnectionEditPart::setSource(), ConnectionEditPart::setTarget(), ConnectionEditPart::source(), TTAMachine::Bridge::sourceBus(), and ConnectionEditPart::target().
operator=()
BridgeFactory & BridgeFactory::operator= (BridgeFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
BridgeFactory.hh
BridgeFactory.cc