OpenASIP: ImmInfoValue Class Reference
ImmInfoValue Class Reference
#include <ImmInfo.hh>
Public Member Functions
ImmInfoValue ()
ImmInfoValue (int immediateWidth, bool signExtending)
int64_t lowerBound () const
int64_t upperBound () const
int width () const
bool signExtending () const
Detailed Description
The stored immediate result in ImmInfo.
Definition at line 58 of file ImmInfo.hh.
Constructor & Destructor Documentation
ImmInfoValue() [1/2]
ImmInfoValue::ImmInfoValue ()
Default constructor. Set as zero width and as zero extending.
Definition at line 164 of file ImmInfo.cc.
    : pair(0, false) {
}
ImmInfoValue() [2/2]
ImmInfoValue::ImmInfoValue (int immediateWidth, bool signExtending)
Constructor with the specified immediate width and sign-extension.
Definition at line 172 of file ImmInfo.cc.
    : pair(immediateWidth, signExtending) {
}
Member Function Documentation
lowerBound()
int64_t ImmInfoValue::lowerBound () const
Return largest inclusive value that can be expressed as immediate.
Definition at line 181 of file ImmInfo.cc.
{
    if (second) { // is sign extending?
        return -(1ll << (first-1));
    } else { // is then zero extending.
        return 0;
    }
}
signExtending()
bool ImmInfoValue::signExtending () const inline
Return true if the immediate is sign extending.
Definition at line 75 of file ImmInfo.hh.
{ return second; }
Referenced by ImmInfo::canTakeImmediate().
upperBound()
int64_t ImmInfoValue::upperBound () const
Return smallest inclusive value that can be expressed as immediate.
Definition at line 193 of file ImmInfo.cc.
{
    if (second) { // is sign extending?
        return (1ll << (first-1))-1;
    } else { // is then zero extending.
        return (1ll << (first));
    }
}
width()
int ImmInfoValue::width () const inline
Returns bit width of the immediate.
Definition at line 71 of file ImmInfo.hh.
{ return first; }
Referenced by ImmInfo::canTakeImmediate(), and ImmInfo::canTakeImmediateByWidth().
The documentation for this class was generated from the following files:
ImmInfo.hh
ImmInfo.cc