OpenASIP: TTAProgram::NullProcedure Class Reference
TTAProgram::NullProcedure Class Reference
#include <NullProcedure.hh>
Public Member Functions
virtual ~NullProcedure ()
Program & parent () const
void setParent (Program &prog)
bool isInProgram () const
std::string name () const
int alignment () const
Address address (const Instruction &ins) const
Address startAddress () const
void setStartAddress (Address start)
Address endAddress () const
int instructionCount () const
Instruction & firstInstruction () const
Instruction & instructionAt (UIntWord address) const
bool hasNextInstruction (const Instruction &ins) const
Instruction & nextInstruction (const Instruction &ins) const
Instruction & previousInstruction (const Instruction &ins) const
Instruction & lastInstruction () const
void addInstruction (Instruction &ins)
void insertInstructionAfter (const Instruction &pos, Instruction *ins)
Public Member Functions inherited from TTAProgram::Procedure
Procedure (const TCEString &name, const TTAMachine::AddressSpace &space)
Procedure (const TCEString &name, const TTAMachine::AddressSpace &space, UIntWord startLocation)
virtual ~Procedure ()
TCEString name () const
int alignment () const
Address address (const Instruction &ins) const
void addFront (Instruction *)
void add (Instruction *ins)
void insertAfter (const Instruction &pos, Instruction *ins)
void insertBefore (const Instruction &pos, Instruction *ins)
void clear ()
void remove (Instruction &ins)
CodeSnippet * copy () const
virtual void insertAfter (const Instruction &pos, Instruction *ins)
virtual void insertAfter (const Instruction &pos, const CodeSnippet &cs)
virtual void insertAfter (const Instruction &pos, CodeSnippet *cs)
virtual void insertBefore (const Instruction &pos, Instruction *ins)
virtual void insertBefore (const Instruction &pos, const CodeSnippet &cs)
virtual void insertBefore (const Instruction &pos, CodeSnippet *cs)
Public Member Functions inherited from TTAProgram::CodeSnippet
CodeSnippet ()
CodeSnippet (const TTAProgram::Address &start)
virtual ~CodeSnippet ()
virtual void removeLastInstruction ()
virtual void setEndAddress (Address end)
virtual Instruction & instructionAtIndex (int index) const
virtual Instruction & operator[] (size_t index) const
virtual void deleteInstructionAt (InstructionAddress address)
virtual void prepend (const CodeSnippet &cs)
virtual void prepend (CodeSnippet *cs)
virtual void append (const CodeSnippet &cs)
virtual void append (CodeSnippet *cs)
bool hasReturn () const
virtual std::string disassembly () const
virtual std::string toString () const
Static Public Member Functions
static NullProcedure & instance ()
Protected Member Functions
NullProcedure ()
Private Member Functions
NullProcedure (const NullProcedure &)
Copying not allowed.
NullProcedure & operator= (const NullProcedure &)
Assignment not allowed.
Static Private Attributes
static NullProcedure instance_
Unique instance of NullProcedure.
Additional Inherited Members
Protected Types inherited from TTAProgram::CodeSnippet
typedef std::vector< Instruction * > InsList
List of instructions.
typedef InsList::iterator InsIter
Iterator for the instruction list.
Protected Attributes inherited from TTAProgram::CodeSnippet
InsList instructions_
The instructions in this procedure.
Program * parent_
The parent program of the procedure.
Address startAddr_
The start (lowest) address of the procedure.
Address endAddr_
The highest address of the procedure.
Detailed Description
A singleton class that represents a null procedure.
Calling any method causes the program to abort.
Definition at line 50 of file NullProcedure.hh.
Constructor & Destructor Documentation
~NullProcedure()
TTAProgram::NullProcedure::~NullProcedure () virtual
The destructor.
Definition at line 59 of file NullProcedure.cc.
{
}
NullProcedure() [1/2]
TTAProgram::NullProcedure::NullProcedure () protected
The constructor.
Definition at line 52 of file NullProcedure.cc.
                             :
    Procedure("NULL", NullAddressSpace::instance()) {
}
NullProcedure() [2/2]
TTAProgram::NullProcedure::NullProcedure (const NullProcedure &) private
Copying not allowed.
Member Function Documentation
addInstruction()
void TTAProgram::NullProcedure::addInstruction (Instruction & ins)
Aborts program with error log message.
Exceptions
IllegalRegistration never.
Definition at line 240 of file NullProcedure.cc.
{
    abortWithError("addInstruction()");
}
References abortWithError.
address()
Address TTAProgram::NullProcedure::address (const Instruction & ins) const virtual
Aborts program with error log message.
Returns
A null address.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 122 of file NullProcedure.cc.
{
    abortWithError("address()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
alignment()
int TTAProgram::NullProcedure::alignment () const
Definition at line 110 of file NullProcedure.cc.
{
    abortWithError("alignment()");
    return -1;
}
References abortWithError.
endAddress()
Address TTAProgram::NullProcedure::endAddress () const virtual
Aborts program with error log message.
Returns
A null address.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 152 of file NullProcedure.cc.
{
    abortWithError("endAddress()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
firstInstruction()
Instruction & TTAProgram::NullProcedure::firstInstruction () const virtual
Returns the first instruction in the code snippet.
Returns
The first instruction in the code snippet.
Exceptions
InstanceNotFound if there are no instructions in the code snippet.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 169 of file NullProcedure.cc.
{
    abortWithError("firstInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
hasNextInstruction()
bool TTAProgram::NullProcedure::hasNextInstruction (const Instruction & ins) const virtual
Aborts program with error log message.
Returns
False.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 193 of file NullProcedure.cc.
{
    abortWithError("hasNextInstruction()");
    return false;
}
References abortWithError.
insertInstructionAfter()
void TTAProgram::NullProcedure::insertInstructionAfter (const Instruction & pos, Instruction * ins)
Aborts program with error log message.
Exceptions
IllegalRegistration never.
Definition at line 250 of file NullProcedure.cc.
{
    abortWithError("insertInstructionAfter()");
}
References abortWithError.
instance()
NullProcedure & TTAProgram::NullProcedure::instance () static
Returns an instance of NullProcedure class (singleton).
Returns
Singleton instance of NullProcedure class.
Definition at line 68 of file NullProcedure.cc.
{
    return instance_;
}
References instance_.
Referenced by TTAProgram::NullProgram::firstProcedure(), TTAProgram::Instruction::isInProcedure(), TTAProgram::NullProgram::lastProcedure(), TTAProgram::NullProgram::nextProcedure(), TTAProgram::Program::nextProcedure(), TTAProgram::NullInstruction::parent(), TTAProgram::NullProgram::procedure(), TTAProgram::NullProgram::procedure(), TTAProgram::CodeSnippet::remove(), and TTAProgram::Procedure::remove().
instructionAt()
Instruction & TTAProgram::NullProcedure::instructionAt (UIntWord address) const virtual
Aborts program with error log message.
Returns
A null instruction.
Exceptions
KeyNotFound never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 181 of file NullProcedure.cc.
{
    abortWithError("instructionAt()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
instructionCount()
int TTAProgram::NullProcedure::instructionCount () const virtual
Aborts program with error log message.
Returns
-1.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 163 of file NullProcedure.cc.
{
    abortWithError("instructionCount()");
    return -1;
}
References abortWithError.
isInProgram()
bool TTAProgram::NullProcedure::isInProgram () const virtual
Aborts program with error log message.
Returns
False.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 98 of file NullProcedure.cc.
{
    abortWithError("isInProgram()");
    return false;
}
References abortWithError.
lastInstruction()
Instruction & TTAProgram::NullProcedure::lastInstruction () const virtual
Aborts program with error log message.
Returns
A null instruction.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 229 of file NullProcedure.cc.
{
    abortWithError("lastInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
name()
std::string TTAProgram::NullProcedure::name () const
Definition at line 104 of file NullProcedure.cc.
{
    abortWithError("name()");
    return "";
}
References abortWithError.
nextInstruction()
Instruction & TTAProgram::NullProcedure::nextInstruction (const Instruction & ins) const virtual
Aborts program with error log message.
Returns
A null instruction.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 205 of file NullProcedure.cc.
{
    abortWithError("nextInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
operator=()
NullProcedure & TTAProgram::NullProcedure::operator= (const NullProcedure &) private
Assignment not allowed.
parent()
Program & TTAProgram::NullProcedure::parent () const virtual
Aborts program with error log message.
Returns
A null program.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 79 of file NullProcedure.cc.
{
    abortWithError("parent()");
    return NullProgram::instance();
}
References abortWithError, and TTAProgram::NullProgram::instance().
previousInstruction()
Instruction & TTAProgram::NullProcedure::previousInstruction (const Instruction & ins) const virtual
Aborts program with error log message.
Returns
A null instruction.
Exceptions
IllegalRegistration never.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 217 of file NullProcedure.cc.
{
    abortWithError("previousInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
setParent()
void TTAProgram::NullProcedure::setParent (Program & prog) virtual
Aborts program with error log message.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 88 of file NullProcedure.cc.
{
    abortWithError("setParent()");
}
References abortWithError.
setStartAddress()
void TTAProgram::NullProcedure::setStartAddress (Address start) virtual
Aborts program with error log message.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 142 of file NullProcedure.cc.
{
    abortWithError("setStartAddress()");
}
References abortWithError.
startAddress()
Address TTAProgram::NullProcedure::startAddress () const virtual
Aborts program with error log message.
Returns
A null address.
Reimplemented from TTAProgram::CodeSnippet.
Definition at line 133 of file NullProcedure.cc.
{
    abortWithError("startAddress()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
Member Data Documentation
instance_
NullProcedure TTAProgram::NullProcedure::instance_ static private
Unique instance of NullProcedure.
Definition at line 88 of file NullProcedure.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullProcedure.hh
NullProcedure.cc