OpenASIP: InfoProgramCommand Class Reference
InfoProgramCommand Class Reference
Public Member Functions
InfoProgramCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoProgramCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info program".
Definition at line 1236 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoProgramCommand()
InfoProgramCommand::InfoProgramCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 1241 of file InfoCommand.cc.
                                                                 :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoProgramCommand()
virtual InfoProgramCommand::~InfoProgramCommand () inline virtual
Destructor.
Definition at line 1248 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoProgramCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info program" command.
Displays information about the status of the program: whether it is loaded or running, why it stopped.
Parameters
arguments Arguments to the command, including the command.
Returns
true in case execution was successful.
Implements SimControlLanguageSubCommand.
Definition at line 1260 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (argumentCount == 0) {
            if (parent().simulatorFrontend().isSimulationStopped()) {
                parent().outputStream()
                    << (SimulatorToolbox::textGenerator().text(
                            Texts::TXT_STATUS_STOPPED) %
                        parent().simulatorFrontend().programCounter()).str()
                    << std::endl;
                parent().printStopReasons();
            } else if (parent().simulatorFrontend().hasSimulationEnded()) {
                parent().outputStream()
                    << SimulatorToolbox::textGenerator().text(
                        Texts::TXT_STATUS_FINISHED).str() << std::endl;
            } else if (parent().simulatorFrontend().isSimulationRunning()) {
                abortWithError(
                    "It should not be possible to do this while "
                    "simulation is running!");
            } else if (parent().simulatorFrontend().isSimulationInitialized()) {
                parent().outputStream() << SimulatorToolbox::textGenerator().text(
                    Texts::TXT_STATUS_INITIALIZED).str() << std::endl;
            } else {
                parent().outputStream() << SimulatorToolbox::textGenerator().text(
                    Texts::TXT_STATUS_NOT_INITIALIZED).str() << std::endl;
            }
            return true;
        } else if (argumentCount == 3) {
            if (!parent().simulatorFrontend().isProgramLoaded()) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_STATUS_NOT_INITIALIZED).str());
                return false;
            }
            const std::string command =
                StringTools::stringToLower(arguments[2].stringValue());
            if (command == "is_instruction_reference") {
                try {
                    const int addr = arguments[3].integerValue();
                    const int move = arguments[4].integerValue();
                    if (parent().simulatorFrontend().program().instructionAt(addr).
                        move(move).source().isInstructionAddress()) {
                        parent().interpreter()->setResult("1");
                        return true;
                    } else {
                        parent().interpreter()->setResult("0");
                        return true;
                    }
                } catch (const NumberFormatException& e) {
                    string msg = "Instruction address and move index parameters "
                        "must be integers.";
                    parent().interpreter()->setError(msg);
                    return false;
                } catch (const KeyNotFound & e) {
                    string msg = "Instruction address not found.";
                    parent().interpreter()->setError(msg);
                    return false;
                } catch (const OutOfRange& e) {
                    string msg = "Move slot not found.";
                    parent().interpreter()->setError(msg);
                    return false;
                } catch (const Exception& e) {
                    abortWithError(
                        "Unexpected exception in 'info program "
                        "is_instruction_reference' command!");
                }
            } else {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_UNKNOWN_SUBCOMMAND).str());
                return false;
            }
        } else {
            if (!(parent().checkArgumentCount(argumentCount, 0, 0) ||
                  parent().checkArgumentCount(argumentCount, 3, 3))) {
                return false;
            }
        }
        // should not end up here
        return false;
    }
References abortWithError, CustomCommand::interpreter(), SimControlLanguageCommand::outputStream(), SimControlLanguageSubCommand::parent(), SimControlLanguageCommand::printStopReasons(), program, SimulatorFrontend::programCounter(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), StringTools::stringToLower(), Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_STATUS_FINISHED, Texts::TXT_STATUS_INITIALIZED, Texts::TXT_STATUS_NOT_INITIALIZED, Texts::TXT_STATUS_STOPPED, and Texts::TXT_UNKNOWN_SUBCOMMAND.
The documentation for this class was generated from the following file:
InfoCommand.cc