OpenASIP: TPEF::TPEFASpaceSectionReader Class Reference
TPEF::TPEFASpaceSectionReader Class Reference
#include <TPEFASpaceSectionReader.hh>
Protected Member Functions
TPEFASpaceSectionReader ()
virtual ~TPEFASpaceSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFASpaceSectionReader (const TPEFASpaceSectionReader &)
Copying not allowed.
TPEFASpaceSectionReader & operator= (TPEFASpaceSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFASpaceSectionReader proto_
Prototype instance of TPEFASpaceSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads address space section from TPEF binary file.
Definition at line 46 of file TPEFASpaceSectionReader.hh.
Constructor & Destructor Documentation
TPEFASpaceSectionReader() [1/2]
TPEF::TPEFASpaceSectionReader::TPEFASpaceSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 57 of file TPEFASpaceSectionReader.cc.
                                                 : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFASpaceSectionReader()
TPEF::TPEFASpaceSectionReader::~TPEFASpaceSectionReader () protected virtual
Destructor.
Definition at line 64 of file TPEFASpaceSectionReader.cc.
{
}
TPEFASpaceSectionReader() [2/2]
TPEF::TPEFASpaceSectionReader::TPEFASpaceSectionReader (const TPEFASpaceSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFASpaceSectionReader & TPEF::TPEFASpaceSectionReader::operator= (TPEFASpaceSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFASpaceSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read value were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 90 of file TPEFASpaceSectionReader.cc.
{
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    // just being paranoid...
    ASpaceSection* aSpaceSection =
        dynamic_cast<ASpaceSection*>(section);
    assert(aSpaceSection != NULL);
    std::set<Byte> alreadyUsedIds;
    bool undefFound = false;
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // start of first element
        SectionOffset elementStart = header().bodyOffset;
        while (elementStart + header().elementSize <=
               header().bodyOffset + header().bodyLength) {
            ASpaceElement *elem = new ASpaceElement();
            // first byte of address space element is a unique identifier
            Byte id = stream.readByte();
            // check that the identifier is really unique
            if (alreadyUsedIds.find(id) != alreadyUsedIds.end()) {
                bool twoASpaceElementsWithSameId = false;
                assert(twoASpaceElementsWithSameId);
            } else {
                alreadyUsedIds.insert(id);
            }
            SectionIndexKey sectionIndexKey(
                dynamic_cast<TPEFReader*>(parent())->aSpaceId(), id);
            SafePointer::addObjectReference(sectionIndexKey, elem);
            elem->setMAU(stream.readByte());
            elem->setAlign(stream.readByte());
            elem->setWordSize(stream.readByte());
            SectionOffsetKey nameSectionOffset(
                header().linkId, stream.readWord());
            elem->setName(CREATE_SAFEPOINTER(nameSectionOffset));
            // check undef aspace
            if (id == 0) {
                assert(elem->MAU() == 0);
                assert(elem->align() == 0);
                assert(elem->wordSize() == 0);
                assert(nameSectionOffset.offset() == 0);
                aSpaceSection->setUndefinedASpace(elem);
                undefFound = true;
            }
            section->addElement(elem);
            elementStart += header().elementSize;
            stream.setReadPosition(elementStart);
        }
    }
    // if there was no undef aspace create it (if nobits flag is set)
    if (!undefFound) {
        ASpaceElement *elem = new ASpaceElement();
        elem->setMAU(0);
        elem->setAlign(0);
        elem->setWordSize(0);
        section->addElement(elem);
        aSpaceSection->setUndefinedASpace(elem);
    }
}
References TPEF::Section::addElement(), TPEF::ReferenceManager::SafePointer::addObjectReference(), TPEF::ASpaceElement::align(), assert, TPEF::TPEFSectionReader::Header::bodyOffset, TPEF::TPEFSectionReader::Header::elementSize, TPEF::TPEFSectionReader::header(), TPEF::ASpaceElement::MAU(), TPEF::Section::noBits(), TPEF::ReferenceManager::SectionOffsetKey::offset(), TPEF::TPEFSectionReader::parent(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readWord(), TPEF::ASpaceElement::setAlign(), TPEF::ASpaceElement::setMAU(), TPEF::ASpaceElement::setName(), TPEF::BinaryStream::setReadPosition(), TPEF::ASpaceSection::setUndefinedASpace(), TPEF::ASpaceElement::setWordSize(), and TPEF::ASpaceElement::wordSize().
type()
Section::SectionType TPEF::TPEFASpaceSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 73 of file TPEFASpaceSectionReader.cc.
{
    return Section::ST_ADDRSP;
}
References TPEF::Section::ST_ADDRSP.
Member Data Documentation
proto_
TPEFASpaceSectionReader TPEF::TPEFASpaceSectionReader::proto_ static private
Prototype instance of TPEFASpaceSectionReader to be registered to SectionReader.
Definition at line 63 of file TPEFASpaceSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFASpaceSectionReader.hh
TPEFASpaceSectionReader.cc