OpenASIP: TPEF::AOutReader Class Reference
TPEF::AOutReader Class Reference
#include <AOutReader.hh>
Classes
class Header
Public Types
enum SymbolType {
N_UNDF = 0x0 , N_ABS = 0x2 , N_TEXT = 0x4 , N_DATA = 0x6 ,
N_BSS = 0x8 , N_COMM = 0x12 , N_FN = 0x1e , N_EXT = 0x1 ,
N_TYPE = 0x1e , N_TJ = 0x76 , N_JTE = 0x96 , N_MEM = 0xb6 ,
N_FC = 0xd6 , N_STAB = 0xe0 , N_GSYM = 0x20 , N_FNAME = 0x22 ,
N_FUN = 0x24 , N_STSYM = 0x26 , N_LCSYM = 0x28 , N_MAIN = 0x2a ,
N_RSYM = 0x40 , N_SLINE = 0x44 , N_SSYM = 0x60 , N_SO = 0x64 ,
N_LSYM = 0x80 , N_BINCL = 0x82 , N_SOL = 0x84 , N_PSYM = 0xa0 ,
N_EINCL = 0xa2 , N_LBRAC = 0xc0 , N_EXCL = 0xc2 , N_RBRAC = 0xe0 ,
N_BCOMM = 0xe2 , N_ECOMM = 0xe4 , N_ECOML = 0xe8 , N_LENG = 0xfe ,
N_PC = 0x30 , N_M2C = 0x42 , N_SCOPE = 0xc4 , N_BROWS = 0x48 ,
N_PRTAB = 0xd2 , N_ANN = 0xa4
}
enum AOutSectionID {
ST_UNDEF = 0x00 , ST_TEXT = N_TEXT , ST_DATA = N_DATA , ST_UDATA = N_BSS ,
ST_SYMBOL = 0x10 , ST_STRING = 0x12
}
Public Types inherited from TPEF::BinaryReader
typedef unsigned long Length
Public Member Functions
SectionOffset sectionOffsetOfAddress (AddressImage address) const
AddressImage addressOfElement (SectionElement *elem) const
ASpaceElement * aSpaceOfElement (SectionElement *elem) const
ResourceSection * resourceTable () const
NullSection * nullSection () const
DebugSection * debugSection () const
StringSection * stringSection () const
CodeSection * textSection () const
Public Member Functions inherited from TPEF::BinaryReader
virtual ~BinaryReader ()
Static Public Member Functions
static BinaryReader * instance ()
static const Header & header ()
Static Public Member Functions inherited from TPEF::BinaryReader
static Binary * readBinary (BinaryStream &stream)
Static Public Attributes
static const Word INT_REGISTERS = 1024
Number of integer registers.
static const Word FP_REGISTERS = 1024
Number of floating-point registers.
static const Word BOOL_REGISTERS = 1
Number of Boolean registers.
static const Word FIRST_INT_REGISTER = 0
Index of the first integer register in a.out.
static const Word FIRST_FP_REGISTER = FIRST_INT_REGISTER + INT_REGISTERS
Index of the first floating-point register.
static const Word FIRST_BOOL_REGISTER = FIRST_FP_REGISTER + FP_REGISTERS
Index of the first Boolean register.
static const Word FIRST_FU_REGISTER = FIRST_BOOL_REGISTER + BOOL_REGISTERS
Index of the first function unit register.
static const Byte AOUT_INSTRUCTION_SIZE = 8
Size of one instruction in a.out file.
static const Byte AOUT_BITS_PER_MAU = 8
Minimum addressable word of address space.
static const Byte AOUT_WORD_ALIGN = 4
Aligment of address space.
static const Byte AOUT_WORD_SIZE = 4
Word size of address space.
static const char * AOUT_CODE_ASPACE_NAME = "universal_instructions"
Name of universal machines code address space.
static const char * AOUT_DATA_ASPACE_NAME = "universal_data"
Name of universal machines data address space.
Protected Member Functions
AOutReader ()
virtual ~AOutReader ()
virtual Binary * readData (BinaryStream &stream) const
virtual bool isMyStreamType (BinaryStream &stream) const
Protected Member Functions inherited from TPEF::BinaryReader
BinaryReader ()
Private Member Functions
void readHeader (BinaryStream &stream) const
void readSection (BinaryStream &stream, FileOffset startPosition, Section *section, Length length) const
void addOrDeleteSection (Section *section, Binary *binary) const
AOutReader (const AOutReader &)
Copying not allowed.
AOutReader & operator= (const AOutReader &)
Assignment not allowed.
Private Attributes
ASpaceElement * undefASpace_
Undefined address space.
ASpaceElement * codeASpace_
Address space of text section.
ASpaceElement * dataASpace_
Address space of data sections.
Static Private Attributes
static ResourceSection * resourceTable_ = NULL
static NullSection * nullSection_ = NULL
static DebugSection * debugSection_ = NULL
static StringSection * stringSection_ = NULL
static CodeSection * textSection_ = NULL
static const HalfWord OMAGIC = 0x0107
Move a.out format identifier.
static const Byte FILE_HEADER_SIZE = 8 * sizeof(Word)
Size of file header.
static Header header_
Header of a.out file.
static AOutReader * proto_ = NULL
Prototype instance of AOutReader registered into BinaryReader.
Additional Inherited Members
Static Protected Member Functions inherited from TPEF::BinaryReader
static void registerBinaryReader (BinaryReader *reader)
Detailed Description
Reads binary file that is in TTA a.out format.
Definition at line 54 of file AOutReader.hh.
Member Enumeration Documentation
AOutSectionID
enum TPEF::AOutReader::AOutSectionID
Names for a.out sections.
Sections are expected in this order in a.out file. Since there is only one section of each type, these names can be used as section identifiers.
Enumerator
ST_UNDEF
Undefined section.
ST_TEXT
Text section.
ST_DATA
Data section.
ST_UDATA
Uninitialized data section.
ST_SYMBOL
Symbol table.
ST_STRING
String table.
Definition at line 114 of file AOutReader.hh.
                       {
        ST_UNDEF =  0x00,     ///< Undefined section.
        ST_TEXT =   N_TEXT,   ///< Text section.
        ST_DATA =   N_DATA,   ///< Data section.
        ST_UDATA =  N_BSS,    ///< Uninitialized data section.
        ST_SYMBOL = 0x10,     ///< Symbol table.
        ST_STRING = 0x12      ///< String table.
    };
SymbolType
enum TPEF::AOutReader::SymbolType
TODO: get these from tce-frontend a.out symbols. (from MOVE/sched/exec.h)
Enumerator
N_UNDF
Undefined.
N_ABS
Absolute.
N_TEXT
Text.
N_DATA
Data.
N_BSS
BSS.
N_COMM
Common (internal to ld).
N_FN
File name.
N_EXT
Mask bit for external.
N_TYPE
Mask bits for resolving symbol type.
N_TJ
Table jump.
N_JTE
Jump table entry.
N_MEM
Memory reference.
N_FC
Function call.
N_STAB
Mask forstabs.
N_GSYM
Global.
N_FNAME
Procedure name (f77).
N_FUN
Procedure.
N_STSYM
Static.
N_LCSYM
.lcomm.
N_MAIN
Name of main rutine.
N_RSYM
Register.
N_SLINE
Source line.
N_SSYM
Structure.
N_SO
Source file name.
N_LSYM
Local.
N_BINCL
Header file.
N_SOL
#included file name.
N_PSYM
Parameter.
N_EINCL
End of include file.
N_LBRAC
Left bracket.
N_EXCL
Excluded include file.
N_RBRAC
Right bracket.
N_BCOMM
Begin common.
N_ECOMM
End common.
N_ECOML
End common (local name).
N_LENG
Second symbol table entry with length.
N_PC
Global pascal symbol.
N_M2C
Compilation unit symbol table entry.
N_SCOPE
Scope information.
N_BROWS
Sun source code browser.
N_PRTAB
TCE processors resource entry.
N_ANN
TCE annotation entry.
Definition at line 61 of file AOutReader.hh.
                    {
        N_UNDF  = 0x0,  ///< Undefined.
        N_ABS   = 0x2,  ///< Absolute.
        N_TEXT  = 0x4,  ///< Text.
        N_DATA  = 0x6,  ///< Data.
        N_BSS   = 0x8,  ///< BSS.
        N_COMM  = 0x12, ///< Common (internal to ld).
        N_FN    = 0x1e, ///< File name.
        N_EXT   = 0x1,  ///< Mask bit for external.
        N_TYPE  = 0x1e, ///< Mask bits for resolving symbol type.
        N_TJ    = 0x76, ///< Table jump.
        N_JTE   = 0x96, ///< Jump table entry.
        N_MEM   = 0xb6, ///< Memory reference.
        N_FC    = 0xd6, ///< Function call.
        N_STAB  = 0xe0, ///< Mask forstabs.
        N_GSYM  = 0x20, ///< Global.
        N_FNAME = 0x22, ///< Procedure name (f77).
        N_FUN   = 0x24, ///< Procedure.
        N_STSYM = 0x26, ///< Static.
        N_LCSYM = 0x28, ///< .lcomm.
        N_MAIN  = 0x2a, ///< Name of main rutine.
        N_RSYM  = 0x40, ///< Register.
        N_SLINE = 0x44, ///< Source line.
        N_SSYM  = 0x60, ///< Structure.
        N_SO    = 0x64, ///< Source file name.
        N_LSYM  = 0x80, ///< Local.
        N_BINCL = 0x82, ///< Header file.
        N_SOL   = 0x84, ///< #included file name.
        N_PSYM  = 0xa0, ///< Parameter.
        N_EINCL = 0xa2, ///< End of include file.
        N_LBRAC = 0xc0, ///< Left bracket.
        N_EXCL  = 0xc2, ///< Excluded include file.
        N_RBRAC = 0xe0, ///< Right bracket.
        N_BCOMM = 0xe2, ///< Begin common.
        N_ECOMM = 0xe4, ///< End common.
        N_ECOML = 0xe8, ///< End common (local name).
        N_LENG  = 0xfe, ///< Second symbol table entry with length.
        N_PC    = 0x30, ///< Global pascal symbol.
        N_M2C   = 0x42, ///< Compilation unit symbol table entry.
        N_SCOPE = 0xc4, ///< Scope information.
        N_BROWS = 0x48, ///< Sun source code browser.
        N_PRTAB = 0xd2, ///< TCE processors resource entry.
        N_ANN   = 0xa4  ///< TCE annotation entry.
    };
Constructor & Destructor Documentation
AOutReader() [1/2]
TPEF::AOutReader::AOutReader () protected
Constructor.
Creates Header and registers itself to BinaryReader.
Definition at line 101 of file AOutReader.cc.
                       : BinaryReader(),
    codeASpace_(NULL), dataASpace_(NULL) {
    BinaryReader::registerBinaryReader(this);
}
References TPEF::BinaryReader::registerBinaryReader().
~AOutReader()
TPEF::AOutReader::~AOutReader () protected virtual
Destructor.
Definition at line 110 of file AOutReader.cc.
{
    if (proto_ != NULL) {
        auto proto = proto_;
        proto_ = NULL;
        delete proto;
    }
}
References proto_.
AOutReader() [2/2]
TPEF::AOutReader::AOutReader (const AOutReader &) private
Copying not allowed.
Member Function Documentation
addOrDeleteSection()
void TPEF::AOutReader::addOrDeleteSection (Section * section, Binary * binary) const private
Referenced by readData().
addressOfElement()
AddressImage TPEF::AOutReader::addressOfElement (SectionElement * elem) const
Referenced by TPEF::AOutRelocationSectionReader::finalize().
aSpaceOfElement()
ASpaceElement * TPEF::AOutReader::aSpaceOfElement (SectionElement * elem) const
Referenced by TPEF::AOutRelocationSectionReader::finalize().
debugSection()
DebugSection * TPEF::AOutReader::debugSection () const
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol().
header()
static const Header & TPEF::AOutReader::header () static
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutDataSectionReader::readData(), TPEF::AOutRelocationSectionReader::readData(), TPEF::AOutStringSectionReader::readData(), TPEF::AOutSymbolSectionReader::readData(), and TPEF::AOutTextSectionReader::readData().
instance()
static BinaryReader * TPEF::AOutReader::instance () static
Referenced by TPEF::AOutSectionReader::parent().
isMyStreamType()
bool TPEF::AOutReader::isMyStreamType (BinaryStream & stream) const protected virtual
Checks whether AOutReader can read from the given stream.
The test simply consists of checking that file size is at least the size of a.out header. Then it checks whether the third and fourth Byte of stream match the magic number of a.out files. Only 'old impure format' files (not read-only text and not page-aligned for on demand load) are accepted.
This method does not modify the stream position.
Parameters
stream The stream to test.
Returns
True if stream contains data in a.out format, false otherwise.
Exceptions
UnreachableStream If there occurs an exception with stream.
Implements TPEF::BinaryReader.
Definition at line 341 of file AOutReader.cc.
{
    unsigned long startPos = stream.readPosition();
    try {
        if (stream.sizeOfFile() < FILE_HEADER_SIZE) {
            return false;
        } else {
            stream.readHalfWord();
            Word magic = stream.readHalfWord();
            stream.setReadPosition(startPos);
            if(magic == OMAGIC) {
                return true;
            } else {
                return false;
            }
        }
    } catch (EndOfFile& e) {
        stream.setReadPosition(startPos);
        return false;
    }
}
References FILE_HEADER_SIZE, OMAGIC, TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readPosition(), TPEF::BinaryStream::setReadPosition(), and TPEF::BinaryStream::sizeOfFile().
nullSection()
NullSection * TPEF::AOutReader::nullSection () const
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol(), and TPEF::AOutSymbolSectionReader::readData().
operator=()
AOutReader & TPEF::AOutReader::operator= (const AOutReader &) private
Assignment not allowed.
readData()
Binary * TPEF::AOutReader::readData (BinaryStream & stream) const protected virtual
Does the actual work of reading binary file from stream.
Reads a.out binary file and creates valid TPEF object hierarchy out of it.
Parameters
stream Stream to be read from.
Returns
Pointer to the Binary object created.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Implements TPEF::BinaryReader.
Definition at line 134 of file AOutReader.cc.
{
    Binary* newBin = NULL;
    newBin = new Binary();
    // read section sizes and other file header data
    readHeader(stream);
    // create all a.out sections and
    nullSection_ =
        dynamic_cast<NullSection*>(
            Section::createSection(Section::ST_NULL));
    nullSection_->setLink(nullSection_);
    textSection_ = dynamic_cast<CodeSection*>(
        Section::createSection(Section::ST_CODE));
    DataSection* dataSection = dynamic_cast<DataSection*>(
        Section::createSection(Section::ST_DATA));
    UDataSection* uDataSection = dynamic_cast<UDataSection*>(
        Section::createSection(Section::ST_UDATA));
    stringSection_ = dynamic_cast<StringSection*>(
        Section::createSection(Section::ST_STRTAB));
    stringSection_->setLink(nullSection_);
    Section* symbolTable = Section::createSection(Section::ST_SYMTAB);
    RelocSection* textRelocSection = dynamic_cast<RelocSection*>(
        Section::createSection(Section::ST_RELOC));
    RelocSection* dataRelocSection = dynamic_cast<RelocSection*>(
        Section::createSection(Section::ST_RELOC));
    debugSection_ = dynamic_cast<DebugSection*>(
        Section::createSection(Section::ST_DEBUG));
    debugSection_->setLink(stringSection_);
    // create TPEF needed sections (NullSection and ASpaceSection)
    // and processors resource table
    resourceTable_ = dynamic_cast<ResourceSection*>
        (Section::createSection(Section::ST_MR));
    ASpaceSection* aSpaceSection = dynamic_cast<ASpaceSection*>(
        Section::createSection(Section::ST_ADDRSP));
    newBin->setStrings(stringSection_);
    SectionOffsetKey nullString(ST_STRING, 0);
    undefASpace_ = new ASpaceElement();
    codeASpace_ = new ASpaceElement();
    codeASpace_->setMAU(AOUT_BITS_PER_MAU);
    codeASpace_->setAlign(AOUT_WORD_ALIGN);
    codeASpace_->setWordSize(AOUT_WORD_SIZE);
    dataASpace_ = new ASpaceElement();
    dataASpace_->setMAU(AOUT_BITS_PER_MAU);
    dataASpace_->setAlign(AOUT_WORD_ALIGN);
    dataASpace_->setWordSize(AOUT_WORD_SIZE);
    aSpaceSection->setUndefinedASpace(undefASpace_);
    aSpaceSection->addElement(undefASpace_);
    aSpaceSection->addElement(codeASpace_);
    aSpaceSection->addElement(dataASpace_);
    aSpaceSection->setLink(stringSection_);
    // set addresses and address spaces
    // code section starts from address zero
    textSection_->setASpace(codeASpace_);
    textSection_->setStartingAddress(0);
    textSection_->setLink(resourceTable_);
    // after that comes data section
    dataSection->setASpace(dataASpace_);
    dataSection->setStartingAddress(header_.sectionSizeText());
    dataSection->setLink(nullSection_);
    // and at last uninitilized data section after that
    uDataSection->setASpace(dataASpace_);
    uDataSection->setStartingAddress(
        (header_.sectionSizeData() + header_.sectionSizeText()));
    uDataSection->setLink(nullSection_);
    //  undefined address spaces for all aux sections
    nullSection_->setASpace(undefASpace_);
    debugSection_->setASpace(undefASpace_);
    aSpaceSection->setASpace(undefASpace_);
    stringSection_->setASpace(undefASpace_);
    symbolTable->setASpace(undefASpace_);
    textRelocSection->setASpace(undefASpace_);
    dataRelocSection->setASpace(undefASpace_);
    resourceTable_->setASpace(undefASpace_);
    resourceTable_->setLink(stringSection_);
    FileOffset textSection_Start = stream.readPosition();
    FileOffset dataSectionStart =
        textSection_Start + header_.sectionSizeText();
    FileOffset textRelocationTableStart =
        dataSectionStart + header_.sectionSizeData();
    FileOffset dataRelocationTableStart =
        textRelocationTableStart + header_.sectionSizeTextReloc();
    FileOffset symbolTableStart =
        dataRelocationTableStart + header_.sectionSizeDataReloc();
    FileOffset stringTableStart =
        symbolTableStart + header_.sectionSizeSymbol();
    // reading sections and creating reference keys
    SafePointer::addObjectReference(SectionKey(ST_UDATA), uDataSection);
    uDataSection->setDataLength(header_.sectionSizeUData());
    SafePointer::addObjectReference(SectionKey(ST_STRING), stringSection_);
    readSection(stream, stringTableStart, stringSection_,
                header_.sectionSizeString());
    SafePointer::addObjectReference(SectionKey(ST_TEXT), textSection_);
    readSection(stream, textSection_Start,
                textSection_, header_.sectionSizeText());
    SafePointer::addObjectReference(SectionKey(ST_DATA), dataSection);
    readSection(stream, dataSectionStart,
                dataSection, header_.sectionSizeData());
    SafePointer::addObjectReference(SectionKey(ST_SYMBOL), symbolTable);
    symbolTable->setLink(stringSection_);
    readSection(stream, symbolTableStart,
                symbolTable, header_.sectionSizeSymbol());
    // relocation sections are not referenced anywhere by SectionId
    textRelocSection->setLink(symbolTable);
    textRelocSection->setReferencedSection(textSection_);
    readSection(stream, textRelocationTableStart,
                textRelocSection, header_.sectionSizeTextReloc());
    dataRelocSection->setLink(symbolTable);
    dataRelocSection->setReferencedSection(dataSection);
    readSection(stream, dataRelocationTableStart,
                dataRelocSection, header_.sectionSizeDataReloc());
    // add sections necessary sections and sections that contained elements
    newBin->addSection(nullSection_);
    newBin->addSection(aSpaceSection);
    // set names for sections and address spaces
    symbolTable->setName(stringSection_->string2Chunk("Symbols"));
    resourceTable_->setName(
        stringSection_->string2Chunk("Universal resources"));
    dataSection->setName(stringSection_->string2Chunk("Initialized data"));
    textSection_->setName(stringSection_->string2Chunk("Code"));
    aSpaceSection->setName(stringSection_->string2Chunk("Address spaces"));
    nullSection_->setName(stringSection_->string2Chunk("Null section"));
    uDataSection->setName(stringSection_->string2Chunk("Uninitilized data"));
    textRelocSection->setName(
        stringSection_->string2Chunk("Relocated immediates"));
    dataRelocSection->setName(stringSection_->string2Chunk("Relocated data"));
    stringSection_->setName(stringSection_->string2Chunk("Strings of TPEF"));
    debugSection_->setName(stringSection_->string2Chunk("A.out stabs"));
    undefASpace_->setName(stringSection_->string2Chunk(""));
    codeASpace_->setName(stringSection_->string2Chunk(AOUT_CODE_ASPACE_NAME));
    dataASpace_->setName(stringSection_->string2Chunk(AOUT_DATA_ASPACE_NAME));
    addOrDeleteSection(textSection_, newBin);
    addOrDeleteSection(textRelocSection, newBin);
    addOrDeleteSection(symbolTable, newBin);
    addOrDeleteSection(dataSection, newBin);
    addOrDeleteSection(dataRelocSection, newBin);
    addOrDeleteSection(uDataSection, newBin);
    addOrDeleteSection(resourceTable_, newBin);
    addOrDeleteSection(debugSection_, newBin);
    // there should be always at least one starting zero
    assert(stringSection_->length() > 0);
    newBin->addSection(stringSection_);
    // can't be sure about these, but external clients will fix
    // values if needed
    newBin->setType(Binary::FT_OBJSEQ);
    newBin->setArch(Binary::FA_TTA_TUT);
    return newBin;
}
References TPEF::Section::addElement(), TPEF::ReferenceManager::SafePointer::addObjectReference(), addOrDeleteSection(), TPEF::Binary::addSection(), AOUT_BITS_PER_MAU, AOUT_CODE_ASPACE_NAME, AOUT_DATA_ASPACE_NAME, AOUT_WORD_ALIGN, AOUT_WORD_SIZE, assert, codeASpace_, TPEF::Section::createSection(), dataASpace_, debugSection_, TPEF::Binary::FA_TTA_TUT, TPEF::Binary::FT_OBJSEQ, header_, TPEF::DataSection::length(), nullSection_, readHeader(), TPEF::BinaryStream::readPosition(), readSection(), resourceTable_, TPEF::AOutReader::Header::sectionSizeData(), TPEF::AOutReader::Header::sectionSizeDataReloc(), TPEF::AOutReader::Header::sectionSizeString(), TPEF::AOutReader::Header::sectionSizeSymbol(), TPEF::AOutReader::Header::sectionSizeText(), TPEF::AOutReader::Header::sectionSizeTextReloc(), TPEF::AOutReader::Header::sectionSizeUData(), TPEF::ASpaceElement::setAlign(), TPEF::Binary::setArch(), TPEF::Section::setASpace(), TPEF::RawSection::setDataLength(), TPEF::Section::setLink(), TPEF::ASpaceElement::setMAU(), TPEF::ASpaceElement::setName(), TPEF::Section::setName(), TPEF::RelocSection::setReferencedSection(), TPEF::Section::setStartingAddress(), TPEF::Binary::setStrings(), TPEF::Binary::setType(), TPEF::ASpaceSection::setUndefinedASpace(), TPEF::ASpaceElement::setWordSize(), TPEF::Section::ST_ADDRSP, TPEF::Section::ST_CODE, ST_DATA, TPEF::Section::ST_DATA, TPEF::Section::ST_DEBUG, TPEF::Section::ST_MR, TPEF::Section::ST_NULL, TPEF::Section::ST_RELOC, ST_STRING, TPEF::Section::ST_STRTAB, ST_SYMBOL, TPEF::Section::ST_SYMTAB, ST_TEXT, ST_UDATA, TPEF::Section::ST_UDATA, TPEF::StringSection::string2Chunk(), stringSection_, textSection_, and undefASpace_.
readHeader()
void TPEF::AOutReader::readHeader (BinaryStream & stream) const private
Reads file header from the stream and stores it to a specific object.
Parameters
stream Stream to be read from.
Exceptions
UnreachableStream If there occurs a problem with stream.
EndOfFile If end of file were reached where it shouldn't.
Definition at line 374 of file AOutReader.cc.
{
    // test magic number again just in case...
    stream.readHalfWord();
    assert(stream.readHalfWord() == OMAGIC);
    header_.setSectionSizeText(stream.readWord());
    header_.setSectionSizeData(stream.readWord());
    header_.setSectionSizeUData(stream.readWord());
    header_.setSectionSizeSymbol(stream.readWord());
    // virtual address of the entry point of the program is ignored
    assert(stream.readWord() == 0);
    header_.setSectionSizeTextReloc(stream.readWord());
    header_.setSectionSizeDataReloc(stream.readWord());
    SectionOffset currentPosition = stream.readPosition();
    // calculate the size of string table
    SectionOffset beginOfStrTable = currentPosition +
        header_.sectionSizeText() + header_.sectionSizeData() +
        header_.sectionSizeSymbol() + header_.sectionSizeTextReloc() +
        header_.sectionSizeDataReloc();
    header_.setSectionSizeString(stream.sizeOfFile() -
                                 beginOfStrTable);
}
References assert, header_, OMAGIC, TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readPosition(), TPEF::BinaryStream::readWord(), TPEF::AOutReader::Header::sectionSizeData(), TPEF::AOutReader::Header::sectionSizeDataReloc(), TPEF::AOutReader::Header::sectionSizeSymbol(), TPEF::AOutReader::Header::sectionSizeText(), TPEF::AOutReader::Header::sectionSizeTextReloc(), TPEF::AOutReader::Header::setSectionSizeData(), TPEF::AOutReader::Header::setSectionSizeDataReloc(), TPEF::AOutReader::Header::setSectionSizeString(), TPEF::AOutReader::Header::setSectionSizeSymbol(), TPEF::AOutReader::Header::setSectionSizeText(), TPEF::AOutReader::Header::setSectionSizeTextReloc(), TPEF::AOutReader::Header::setSectionSizeUData(), and TPEF::BinaryStream::sizeOfFile().
Referenced by readData().
readSection()
void TPEF::AOutReader::readSection (BinaryStream & stream, FileOffset startPosition, Section * section, Length length) const private
Referenced by readData().
resourceTable()
ResourceSection * TPEF::AOutReader::resourceTable () const
sectionOffsetOfAddress()
SectionOffset TPEF::AOutReader::sectionOffsetOfAddress (AddressImage address) const
Referenced by TPEF::AOutRelocationSectionReader::initializeRelocElement(), and TPEF::AOutSymbolSectionReader::initializeSymbol().
stringSection()
StringSection * TPEF::AOutReader::stringSection () const
textSection()
CodeSection * TPEF::AOutReader::textSection () const
Member Data Documentation
AOUT_BITS_PER_MAU
const Byte TPEF::AOutReader::AOUT_BITS_PER_MAU = 8 static
Minimum addressable word of address space.
Definition at line 143 of file AOutReader.hh.
Referenced by readData().
AOUT_CODE_ASPACE_NAME
const char * TPEF::AOutReader::AOUT_CODE_ASPACE_NAME = "universal_instructions" static
Name of universal machines code address space.
Definition at line 150 of file AOutReader.hh.
Referenced by readData().
AOUT_DATA_ASPACE_NAME
const char * TPEF::AOutReader::AOUT_DATA_ASPACE_NAME = "universal_data" static
Name of universal machines data address space.
Definition at line 152 of file AOutReader.hh.
Referenced by readData().
AOUT_INSTRUCTION_SIZE
const Byte TPEF::AOutReader::AOUT_INSTRUCTION_SIZE = 8 static
Size of one instruction in a.out file.
Definition at line 140 of file AOutReader.hh.
AOUT_WORD_ALIGN
const Byte TPEF::AOutReader::AOUT_WORD_ALIGN = 4 static
Aligment of address space.
Definition at line 145 of file AOutReader.hh.
Referenced by readData().
AOUT_WORD_SIZE
const Byte TPEF::AOutReader::AOUT_WORD_SIZE = 4 static
Word size of address space.
Definition at line 147 of file AOutReader.hh.
Referenced by readData().
BOOL_REGISTERS
const Word TPEF::AOutReader::BOOL_REGISTERS = 1 static
Number of Boolean registers.
Definition at line 128 of file AOutReader.hh.
codeASpace_
ASpaceElement* TPEF::AOutReader::codeASpace_ mutable private
Address space of text section.
Definition at line 237 of file AOutReader.hh.
Referenced by readData().
dataASpace_
ASpaceElement* TPEF::AOutReader::dataASpace_ mutable private
Address space of data sections.
Definition at line 239 of file AOutReader.hh.
Referenced by readData().
debugSection_
DebugSection * TPEF::AOutReader::debugSection_ = NULL static private
Definition at line 248 of file AOutReader.hh.
Referenced by readData().
FILE_HEADER_SIZE
const Byte TPEF::AOutReader::FILE_HEADER_SIZE = 8 * sizeof(Word) static private
Size of file header.
Definition at line 259 of file AOutReader.hh.
Referenced by isMyStreamType().
FIRST_BOOL_REGISTER
const Word TPEF::AOutReader::FIRST_BOOL_REGISTER = FIRST_FP_REGISTER + FP_REGISTERS static
Index of the first Boolean register.
Definition at line 135 of file AOutReader.hh.
Referenced by TPEF::AOutTextSectionReader::convertAOutIndexToTPEF(), TPEF::AOutTextSectionReader::updateMoveDestination(), and TPEF::AOutTextSectionReader::updateMoveSource().
FIRST_FP_REGISTER
const Word TPEF::AOutReader::FIRST_FP_REGISTER = FIRST_INT_REGISTER + INT_REGISTERS static
Index of the first floating-point register.
Definition at line 133 of file AOutReader.hh.
Referenced by TPEF::AOutTextSectionReader::convertAOutIndexToTPEF(), TPEF::AOutTextSectionReader::updateMoveDestination(), and TPEF::AOutTextSectionReader::updateMoveSource().
FIRST_FU_REGISTER
const Word TPEF::AOutReader::FIRST_FU_REGISTER = FIRST_BOOL_REGISTER + BOOL_REGISTERS static
Index of the first function unit register.
Definition at line 137 of file AOutReader.hh.
Referenced by TPEF::AOutTextSectionReader::convertAOutIndexToTPEF(), TPEF::AOutSymbolSectionReader::readData(), TPEF::AOutTextSectionReader::updateMoveDestination(), and TPEF::AOutTextSectionReader::updateMoveSource().
FIRST_INT_REGISTER
const Word TPEF::AOutReader::FIRST_INT_REGISTER = 0 static
Index of the first integer register in a.out.
Definition at line 131 of file AOutReader.hh.
Referenced by TPEF::AOutTextSectionReader::convertAOutIndexToTPEF().
FP_REGISTERS
const Word TPEF::AOutReader::FP_REGISTERS = 1024 static
Number of floating-point registers.
Definition at line 126 of file AOutReader.hh.
header_
AOutReader::Header TPEF::AOutReader::header_ static private
Header of a.out file.
Definition at line 262 of file AOutReader.hh.
Referenced by readData(), and readHeader().
INT_REGISTERS
const Word TPEF::AOutReader::INT_REGISTERS = 1024 static
Number of integer registers.
Definition at line 124 of file AOutReader.hh.
nullSection_
NullSection * TPEF::AOutReader::nullSection_ = NULL static private
Definition at line 245 of file AOutReader.hh.
Referenced by readData().
OMAGIC
const HalfWord TPEF::AOutReader::OMAGIC = 0x0107 static private
Move a.out format identifier.
Definition at line 257 of file AOutReader.hh.
Referenced by isMyStreamType(), and readHeader().
proto_
AOutReader * TPEF::AOutReader::proto_ = NULL static private
Prototype instance of AOutReader registered into BinaryReader.
AOutReader class.
Definition at line 264 of file AOutReader.hh.
Referenced by ~AOutReader().
resourceTable_
ResourceSection * TPEF::AOutReader::resourceTable_ = NULL static private
Definition at line 242 of file AOutReader.hh.
Referenced by readData().
stringSection_
StringSection * TPEF::AOutReader::stringSection_ = NULL static private
Definition at line 251 of file AOutReader.hh.
Referenced by readData().
textSection_
CodeSection * TPEF::AOutReader::textSection_ = NULL static private
Definition at line 254 of file AOutReader.hh.
Referenced by readData().
undefASpace_
ASpaceElement* TPEF::AOutReader::undefASpace_ mutable private
Undefined address space.
Definition at line 235 of file AOutReader.hh.
Referenced by readData().
The documentation for this class was generated from the following files:
AOutReader.hh
AOutReader.cc