OpenASIP: TPEF::ResourceElement Class Reference
TPEF::ResourceElement Class Reference
#include <ResourceElement.hh>
Public Types
enum ResourceType {
MRT_NULL = 0x00 , MRT_BUS = 0x01 , MRT_UNIT = 0x02 , MRT_RF = 0x03 ,
MRT_OP = 0x04 , MRT_IMM = 0x05 , MRT_SR = 0x06 , MRT_PORT = 0x07
}
Resource types.
enum ReservedResourceIDs {
UNIVERSAL_BUS = 0x00 , UNIVERSAL_FU = 0x00 , ILLEGAL_RF = 0x00 , INT_RF = 0x80 ,
BOOL_RF = 0x81 , FP_RF = 0x82 , UNIVERSAL_RF_MASK = 0x80 , INLINE_IMM = 0x00
}
Resource Id numbers that are reserved for some particular use.
Public Member Functions
ResourceElement ()
virtual ~ResourceElement ()
HalfWord id () const
void setId (HalfWord aId)
ResourceType type () const
void setType (ResourceType aType)
Word info () const
void setInfo (Word aInfo)
Chunk * name () const
void setName (ReferenceManager::SafePointer *aName)
void setName (Chunk *aName)
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Static Public Attributes
static const std::string RETURN_ADDRESS_NAME = "return-address"
Reserved string of return address special register.
Private Attributes
HalfWord id_
Unique id number that is used to refer resource.
ResourceType type_
Type.
const ReferenceManager::SafePointer * name_
Name.
Word info_
Additional info.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Resource table element.
Definition at line 47 of file ResourceElement.hh.
Member Enumeration Documentation
ReservedResourceIDs
enum TPEF::ResourceElement::ReservedResourceIDs
Resource Id numbers that are reserved for some particular use.
Enumerator
UNIVERSAL_BUS
Universal bus.
UNIVERSAL_FU
Universal function unit.
ILLEGAL_RF
Illegal register file.
INT_RF
Universal integer register file.
BOOL_RF
Universal boolean register file.
FP_RF
Universal floating point register file.
UNIVERSAL_RF_MASK
Bit to check if registerfile is real or universal.
INLINE_IMM
Inline immediate unit id.
Definition at line 63 of file ResourceElement.hh.
{
        UNIVERSAL_BUS     = 0x00, ///< Universal bus.
        UNIVERSAL_FU      = 0x00, ///< Universal function unit.
        ILLEGAL_RF        = 0x00, ///< Illegal register file.
        INT_RF            = 0x80, ///< Universal integer register file.
        BOOL_RF           = 0x81, ///< Universal boolean register file.
        FP_RF             = 0x82, ///< Universal floating point register file.
        UNIVERSAL_RF_MASK = 0x80, ///< Bit to check if registerfile is real or
                                  ///< universal.
        INLINE_IMM        = 0x00  ///< Inline immediate unit id.
    };
ResourceType
enum TPEF::ResourceElement::ResourceType
Resource types.
Enumerator
MRT_NULL
Illegal undefined machine resource.
MRT_BUS
Transport bus.
MRT_UNIT
Function unit.
MRT_RF
Register file.
MRT_OP
Operation operand or function unit register.
MRT_IMM
Immediate unit.
MRT_SR
Special register.
MRT_PORT
Function unit port.
Definition at line 51 of file ResourceElement.hh.
                      {
        MRT_NULL = 0x00, ///< Illegal undefined machine resource.
        MRT_BUS  = 0x01, ///< Transport bus.
        MRT_UNIT = 0x02, ///< Function unit.
        MRT_RF   = 0x03, ///< Register file.
        MRT_OP   = 0x04, ///< Operation operand or function unit register.
        MRT_IMM  = 0x05, ///< Immediate unit.
        MRT_SR   = 0x06, ///< Special register.
        MRT_PORT = 0x07  ///< Function unit port.
    };
Constructor & Destructor Documentation
ResourceElement()
TPEF::ResourceElement::ResourceElement ()
Constructs empty element.
Definition at line 46 of file ResourceElement.cc.
                                 : SectionElement(),
    id_(0), type_(MRT_NULL), name_(&SafePointer::null), info_(0) {
}
~ResourceElement()
TPEF::ResourceElement::~ResourceElement () virtual
Handles destruction element.
Definition at line 54 of file ResourceElement.cc.
{
}
Member Function Documentation
id()
HalfWord TPEF::ResourceElement::id () const
Referenced by TPEF::TPEFResourceSectionWriter::actualWriteData(), MachineResourceManager::addResourceElement(), TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::ProgramWriter::createCodeSection(), TPEFDisassembler::createInstruction(), TPEF::ResourceSection::findResource(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TPEF::ResourceSection::hasResource(), TTAProgram::TPEFResourceUpdater::immediateUnit(), TTAProgram::TPEFResourceUpdater::initCache(), TTAProgram::TPEFResourceUpdater::operand(), TTAProgram::TPEFResourceUpdater::registerFile(), TTAProgram::ProgramWriter::resolveFileType(), TPEFDumper::section(), and TTAProgram::ProgramWriter::terminalResource().
info()
Word TPEF::ResourceElement::info () const
Referenced by TPEF::TPEFResourceSectionWriter::actualWriteData(), and TPEFDumper::section().
name()
Chunk * TPEF::ResourceElement::name () const
Referenced by TPEF::TPEFResourceSectionWriter::actualWriteData(), MachineResourceManager::addResourceElement(), TTAProgram::TPEFResourceUpdater::bus(), TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createTerminal(), TTAProgram::TPEFProgramFactory::findBus(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), TTAProgram::TPEFProgramFactory::findRegisterFile(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), TTAProgram::TPEFResourceUpdater::initCache(), TTAProgram::TPEFResourceUpdater::operand(), TTAProgram::TPEFResourceUpdater::registerFile(), TPEF::TPEFTools::resourceName(), and TPEFDumper::section().
setId()
void TPEF::ResourceElement::setId (HalfWord aId)
Referenced by TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::TPEFResourceUpdater::functionUnit(), MachineResourceManager::functionUnitID(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), MachineResourceManager::initResourceSection(), TTAProgram::TPEFResourceUpdater::operand(), MachineResourceManager::opOrPortID(), TPEF::AOutSymbolSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TTAProgram::TPEFResourceUpdater::registerFile(), and MachineResourceManager::registerFileID().
setInfo()
void TPEF::ResourceElement::setInfo (Word aInfo)
Referenced by TPEF::TPEFResourceSectionReader::readData().
setName() [1/2]
void TPEF::ResourceElement::setName (Chunk * aName)
setName() [2/2]
void TPEF::ResourceElement::setName (ReferenceManager::SafePointer * aName)
Referenced by TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::TPEFResourceUpdater::functionUnit(), MachineResourceManager::functionUnitID(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), MachineResourceManager::initResourceSection(), TTAProgram::TPEFResourceUpdater::operand(), MachineResourceManager::opOrPortID(), TPEF::AOutSymbolSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TTAProgram::TPEFResourceUpdater::registerFile(), and MachineResourceManager::registerFileID().
setType()
void TPEF::ResourceElement::setType (ResourceType aType)
Referenced by TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::TPEFResourceUpdater::functionUnit(), MachineResourceManager::functionUnitID(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TTAProgram::TPEFResourceUpdater::immediateUnit(), MachineResourceManager::initResourceSection(), TTAProgram::TPEFResourceUpdater::operand(), MachineResourceManager::opOrPortID(), TPEF::AOutSymbolSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TTAProgram::TPEFResourceUpdater::registerFile(), and MachineResourceManager::registerFileID().
type()
ResourceType TPEF::ResourceElement::type () const
Referenced by TPEF::TPEFResourceSectionWriter::actualWriteData(), MachineResourceManager::addResourceElement(), TTAProgram::TPEFResourceUpdater::bus(), TPEFDisassembler::createInstruction(), TPEF::ResourceSection::findResource(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), TPEF::ResourceSection::hasResource(), TTAProgram::TPEFResourceUpdater::immediateUnit(), TTAProgram::TPEFResourceUpdater::initCache(), TTAProgram::TPEFResourceUpdater::operand(), TTAProgram::TPEFResourceUpdater::registerFile(), TTAProgram::ProgramWriter::resolveFileType(), and TPEFDumper::section().
Member Data Documentation
id_
HalfWord TPEF::ResourceElement::id_ private
Unique id number that is used to refer resource.
Definition at line 96 of file ResourceElement.hh.
info_
Word TPEF::ResourceElement::info_ private
Additional info.
Definition at line 102 of file ResourceElement.hh.
name_
const ReferenceManager::SafePointer* TPEF::ResourceElement::name_ private
Name.
Definition at line 100 of file ResourceElement.hh.
RETURN_ADDRESS_NAME
const std::string TPEF::ResourceElement::RETURN_ADDRESS_NAME = "return-address" static
Reserved string of return address special register.
Definition at line 76 of file ResourceElement.hh.
Referenced by TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), and TTAProgram::TPEFProgramFactory::findPort().
type_
ResourceType TPEF::ResourceElement::type_ private
Type.
Definition at line 98 of file ResourceElement.hh.
The documentation for this class was generated from the following files:
ResourceElement.hh
ResourceElement.cc