OpenASIP: ProximMachineStateWindow Class Reference
ProximMachineStateWindow Class Reference
#include <ProximMachineStateWindow.hh>
Public Types
enum {
COMMAND_ZOOM_IN = 20000 , COMMAND_ZOOM_OUT , COMMAND_TOGGLE_UNIT_INFO , COMMAND_TOGGLE_MOVES ,
COMMAND_TOGGLE_UTILIZATIONS , COMMAND_EXPORT
}
Public Member Functions
ProximMachineStateWindow (ProximMainFrame *parent, int id)
virtual ~ProximMachineStateWindow ()
virtual void reset ()
void setMachine (TTAMachine::Machine *machine)
void setStatusText (std::string status)
void appendUtilizationData (std::string text)
void appendDetails (std::string text)
void clearDetails ()
Private Types
enum {
ID_MACHINE_CANVAS = 10000 , ID_UTILIZATION_WINDOW , ID_TITLE , ID_DETAILS ,
ID_LINE , ID_LABEL_UTILIZATION , ID_UTILIZATION , ID_SPLITTER
}
Private Member Functions
void onMachineLoaded (const SimulatorEvent &event)
void onProgramLoaded (const SimulatorEvent &event)
void onSimulationStop (const SimulatorEvent &event)
void createContents ()
void onZoom (wxCommandEvent &event)
void setUtilizationHighlights ()
void addMoves ()
void onToggleMoves (wxCommandEvent &event)
void onToggleUtilizations (wxCommandEvent &event)
void onToggleUnitInfo (wxCommandEvent &event)
void onUpdateUIEvent (wxUpdateUIEvent &event)
void onExport (wxCommandEvent &event)
Private Attributes
MachineCanvas * canvas_
Machine visualization canvas.
SimulatorFrontend * simulator_
Simulator instance which contains the registers to display.
wxBoxSizer * sizer_
Toplevel sizer for the window widgets.
wxStatusBar * statusbar_
Statusbar of the window.
bool showMoves_
Tells if the moves are displayed or not.
bool showUtilizations_
Tells if the machine part utilizations are displayed or not.
wxTextCtrl * detailsCtrl_
Utilziation window where to display utilization data of the components.
wxTextCtrl * utilizationCtrl_
Static Private Attributes
static const int MINIMUM_PANE_WIDTH = 150
Minimum width for the splitter window panes.
static const int INITIAL_DETAILS_PANE_WIDTH = 200
Initial width for the component detail pane.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Proxim subwindow which displays the simulated machine state.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 56 of file ProximMachineStateWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
COMMAND_ZOOM_IN
COMMAND_ZOOM_OUT
COMMAND_TOGGLE_UNIT_INFO
COMMAND_TOGGLE_MOVES
COMMAND_TOGGLE_UTILIZATIONS
COMMAND_EXPORT
Definition at line 68 of file ProximMachineStateWindow.hh.
         {
    COMMAND_ZOOM_IN = 20000,
    COMMAND_ZOOM_OUT,
        COMMAND_TOGGLE_UNIT_INFO,
        COMMAND_TOGGLE_MOVES,
        COMMAND_TOGGLE_UTILIZATIONS,
        COMMAND_EXPORT
    };
anonymous enum
anonymous enum private
Enumerator
ID_MACHINE_CANVAS
ID_UTILIZATION_WINDOW
ID_TITLE
ID_DETAILS
ID_LINE
ID_LABEL_UTILIZATION
ID_UTILIZATION
ID_SPLITTER
Definition at line 101 of file ProximMachineStateWindow.hh.
         {
    ID_MACHINE_CANVAS = 10000,
        ID_UTILIZATION_WINDOW,
        ID_TITLE,
        ID_DETAILS,
        ID_LINE,
        ID_LABEL_UTILIZATION,
        ID_UTILIZATION,
        ID_SPLITTER
    };
Constructor & Destructor Documentation
ProximMachineStateWindow()
ProximMachineStateWindow::ProximMachineStateWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 94 of file ProximMachineStateWindow.cc.
                                    :
    ProximSimulatorWindow(parent, id, wxDefaultPosition, wxSize(800,600)),
    showMoves_(true), showUtilizations_(true),
    detailsCtrl_(NULL), utilizationCtrl_(NULL) {
    createContents();
    SetSizeHints(400, 300);
    simulator_ = wxGetApp().simulation()->frontend();
    if (simulator_->isSimulationInitialized() ||
        simulator_->isSimulationStopped() ||
        simulator_->isSimulationRunning() ||
        simulator_->hasSimulationEnded()) {
    TTAMachine::Machine* machine =
            const_cast<Machine*>(&ProximToolbox::machine());
    canvas_->setMachine(machine);
    if (showUtilizations_) {
        setUtilizationHighlights();
    }
    }
}
References machine, and ProximToolbox::machine().
~ProximMachineStateWindow()
ProximMachineStateWindow::~ProximMachineStateWindow () virtual
Destructor.
Definition at line 127 of file ProximMachineStateWindow.cc.
{
}
Member Function Documentation
addMoves()
void ProximMachineStateWindow::addMoves () private
Adds active moves to be drawn on the canvas.
Definition at line 358 of file ProximMachineStateWindow.cc.
{
    InstructionAddress address = simulator_->lastExecutedInstruction();
    const TTAProgram::Instruction& instruction =
        simulator_->program().instructionAt(address);
    canvas_->clearMoves();
    for (int i = 0; i < instruction.moveCount(); i++) {
        // Check that the move wasn't squashed by a guard.
        const ExecutableInstruction& lastInstruction =
            simulator_->lastExecInstruction();
        if (lastInstruction.moveSquashed(i)) {
            continue;
        }
        // Move not squashed, add move to be drawn on the canvas.
        TTAProgram::Move& move = instruction.move(i);
        const Bus* bus = &move.bus();
        const Port* source = NULL;
        const Port* target = NULL;
        if (move.source().isFUPort() || move.source().isGPR()) {
            source = &move.source().port();
        }
        if (move.destination().isFUPort() || move.destination().isGPR()) {
            target = &move.destination().port();
        }
        canvas_->addMove(bus, source, target);
    }
}
References MachineCanvas::addMove(), TTAProgram::Move::bus(), canvas_, MachineCanvas::clearMoves(), TTAProgram::Move::destination(), TTAProgram::Program::instructionAt(), TTAProgram::Terminal::isFUPort(), TTAProgram::Terminal::isGPR(), SimulatorFrontend::lastExecInstruction(), SimulatorFrontend::lastExecutedInstruction(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), ExecutableInstruction::moveSquashed(), TTAProgram::Terminal::port(), SimulatorFrontend::program(), simulator_, and TTAProgram::Move::source().
Referenced by onSimulationStop(), and onToggleMoves().
appendDetails()
void ProximMachineStateWindow::appendDetails (std::string text)
Appends text to the component details widget.
Parameters
text Text to append.
Definition at line 479 of file ProximMachineStateWindow.cc.
{
    wxString data = WxConversion::toWxString(text);
    detailsCtrl_->AppendText(data);
}
References detailsCtrl_, and WxConversion::toWxString().
Referenced by ProximBusDetailsCmd::Do(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), ProximIUDetailsCmd::Do(), ProximRFDetailsCmd::Do(), and ProximSocketDetailsCmd::Do().
appendUtilizationData()
void ProximMachineStateWindow::appendUtilizationData (std::string text)
Appends text to the component utilization widget.
Parameters
text Text to append.
Definition at line 467 of file ProximMachineStateWindow.cc.
{
    wxString data = WxConversion::toWxString(text);
    utilizationCtrl_->AppendText(data);
}
References WxConversion::toWxString(), and utilizationCtrl_.
Referenced by ProximBusDetailsCmd::Do(), ProximFUDetailsCmd::Do(), ProximIUDetailsCmd::Do(), ProximRFDetailsCmd::Do(), and ProximSocketDetailsCmd::Do().
clearDetails()
void ProximMachineStateWindow::clearDetails ()
Clears data in the component details pane.
Definition at line 488 of file ProximMachineStateWindow.cc.
{
    detailsCtrl_->Clear();
    utilizationCtrl_->Clear();
}
References detailsCtrl_, and utilizationCtrl_.
Referenced by ProximMachineCanvasTool::onMouseEvent(), and onSimulationStop().
createContents()
void ProximMachineStateWindow::createContents () private
Creates the window contents.
Code generated by wxWidgets.
Definition at line 199 of file ProximMachineStateWindow.cc.
{
    sizer_ = new wxBoxSizer(wxVERTICAL);
    wxSplitterWindow* splitter = new wxSplitterWindow(
        this, ID_SPLITTER, wxDefaultPosition, wxSize(800,600),
        wxSP_BORDER|wxSP_3D|wxCLIP_CHILDREN);
    wxPanel* left = new wxPanel(splitter, -1);
    wxPanel* right = new wxPanel(splitter, -1);
    // Splitter window left hand pane sizer.
    wxFlexGridSizer* leftSizer = new wxFlexGridSizer(1, 0, 0);
    leftSizer->AddGrowableCol(0);
    leftSizer->AddGrowableRow(1);
    leftSizer->AddGrowableRow(4);
    wxStaticText* title = new wxStaticText(
        left, ID_TITLE, ProximConstants::MACH_WIN_DETAILS_TITLE,
        wxDefaultPosition, wxDefaultSize, 0);
    detailsCtrl_ = new wxTextCtrl(
        left, ID_DETAILS, wxT(""), wxDefaultPosition, wxSize(80,40),
        wxTE_MULTILINE|wxTE_READONLY|wxVSCROLL|wxHSCROLL);
    wxStaticLine* line = new wxStaticLine(
        left, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL);
    wxStaticText* utilizationTitle = new wxStaticText(
        left, ID_LABEL_UTILIZATION,
        ProximConstants::MACH_WIN_UTILIZATION_TITLE, wxDefaultPosition,
        wxDefaultSize, 0);
    utilizationCtrl_ = new wxTextCtrl(
        left, ID_UTILIZATION, wxT(""), wxDefaultPosition, wxSize(80,40),
        wxTE_MULTILINE|wxTE_READONLY|wxVSCROLL|wxHSCROLL);
    leftSizer->Add(title, 0, wxGROW|wxALL, 5);
    leftSizer->Add(detailsCtrl_, 0, wxGROW|wxALL, 5);
    leftSizer->Add(line, 0, wxGROW|wxALL, 5);
    leftSizer->Add(utilizationTitle, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);
    leftSizer->Add(utilizationCtrl_, 0, wxGROW|wxALL, 5);
    left->SetSizer(leftSizer);
    // Splitter window right hand pane sizer.
    wxFlexGridSizer* rightSizer = new wxFlexGridSizer(1, 0, 0);
    rightSizer->AddGrowableCol(0);
    rightSizer->AddGrowableRow(0);
    canvas_ = new MachineCanvas(right, new ProximEditPolicyFactory());
    statusbar_ = new wxStatusBar(right, -1);
    rightSizer->Add(canvas_, 0, wxGROW|wxALL, 5);
    rightSizer->Add(statusbar_, 0, wxGROW|wxALL, 5);
    right->SetSizer(rightSizer);
    // Set sizers and split the window.
    splitter->SetMinimumPaneSize(MINIMUM_PANE_WIDTH);
    splitter->SplitVertically(left, right);
    splitter->SetSashPosition(INITIAL_DETAILS_PANE_WIDTH);
    sizer_->Add(splitter, 1, wxGROW);
    SetSizer(sizer_);
    // Create tool for the canvas.
    MachineCanvasTool* canvasTool = new ProximMachineCanvasTool(canvas_);
    canvas_->setTool(canvasTool);
}
References canvas_, detailsCtrl_, ID_DETAILS, ID_LABEL_UTILIZATION, ID_LINE, ID_SPLITTER, ID_TITLE, ID_UTILIZATION, INITIAL_DETAILS_PANE_WIDTH, ProximConstants::MACH_WIN_DETAILS_TITLE, ProximConstants::MACH_WIN_UTILIZATION_TITLE, MINIMUM_PANE_WIDTH, MachineCanvas::setTool(), sizer_, statusbar_, and utilizationCtrl_.
onExport()
void ProximMachineStateWindow::onExport (wxCommandEvent & event) private
Displays a dialog for saving machine figure in a file.
Definition at line 498 of file ProximMachineStateWindow.cc.
{
    wxString message = _T("Export processor figure.");
    wxString defaultDir = _T(".");
    wxString defaultFile= _T("");
#if wxCHECK_VERSION(3, 0, 0)
    wxString fileTypes = _T("Scalable Vector Graphics (.svg)|*.svg|");
#else
    wxString fileTypes = _T("Encapsulated Postscript (.eps)|*.eps;*.epsi|");
#endif
    fileTypes.Append(_T("Portable Network Graphics (.png)|*.png"));
    wxFileDialog dialog(
        this, message, defaultDir, defaultFile, fileTypes,
        wxSAVE | wxOVERWRITE_PROMPT);
    if (dialog.ShowModal() == wxID_CANCEL) {
        return;
    }
    std::string filename = WxConversion::toString(dialog.GetPath());
    std::string extension = FileSystem::fileExtension(filename);
    std::string creator = "TTA Processor Simulator (Proxim)";
    std::string title = "Processor Simulation";
#if wxCHECK_VERSION(3, 0, 0)
    if (extension == ".svg") {
        if (!canvas_->saveSVG(filename)) {
#else
    if (extension == ".eps" || extension == ".epsi") {
        if (!canvas_->saveEPS(filename, title, creator)) {
#endif
            wxString message = _T("Error saving file '");
            message.Append(dialog.GetPath());
            message.Append(_T("'."));
            ErrorDialog errorDialog(this, message);
            errorDialog.ShowModal();
        }
    } else if (extension == ".png") {
        if (!canvas_->savePNG(filename)) {
            wxString message = _T("Error saving file '");
            message.Append(dialog.GetPath());
            message.Append(_T("'."));
            ErrorDialog errorDialog(this, message);
            errorDialog.ShowModal();
        }
    } else {
        wxString message = _T("File type with extension '");
        message.Append(WxConversion::toWxString(extension));
        message.Append(_T("' is not supported."));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
    }
}
References canvas_, FileSystem::fileExtension(), MachineCanvas::saveEPS(), MachineCanvas::savePNG(), WxConversion::toString(), and WxConversion::toWxString().
onMachineLoaded()
void ProximMachineStateWindow::onMachineLoaded (const SimulatorEvent & event) private
onProgramLoaded()
void ProximMachineStateWindow::onProgramLoaded (const SimulatorEvent & event) private
Event handler which is called when a new program is loaded in the simulator.
Definition at line 135 of file ProximMachineStateWindow.cc.
{
    TTAMachine::Machine* machine =
        const_cast<Machine*>(&simulator_->machine());
    canvas_->setMachine(machine);
}
References canvas_, SimulatorFrontend::machine(), machine, MachineCanvas::setMachine(), and simulator_.
onSimulationStop()
void ProximMachineStateWindow::onSimulationStop (const SimulatorEvent & event) private
Event handler for simulation stop.
Refreshes the register values.
Definition at line 159 of file ProximMachineStateWindow.cc.
{
    // Store pointer to the selected machine part.
    const MachinePart* selection = NULL;
    if (canvas_->selection() != NULL) {
        selection = canvas_->selection()->model();
    }
    canvas_->clearSelection();
    clearDetails();
    if (showMoves_) {
        addMoves();
    }
    if (showUtilizations_) {
        setUtilizationHighlights();
    }
    canvas_->Refresh();
    // Reselect & display details of the previously selected machine part.
    Request statusRequest(Request::DETAILS_REQUEST);
    if (selection != NULL) {
        EditPart * part = canvas_->findEditPart(selection);
        if (part != NULL && part->canHandle(&statusRequest)) {
            canvas_->select(part);
            ComponentCommand* command = part->performRequest(&statusRequest);
            command->Do();
            delete command;
        }
    }
}
References addMoves(), EditPart::canHandle(), canvas_, clearDetails(), MachineCanvas::clearSelection(), Request::DETAILS_REQUEST, ComponentCommand::Do(), MachineCanvas::findEditPart(), EditPart::model(), EditPart::performRequest(), MachineCanvas::select(), MachineCanvas::selection(), setUtilizationHighlights(), showMoves_, and showUtilizations_.
onToggleMoves()
void ProximMachineStateWindow::onToggleMoves (wxCommandEvent & event) private
Toggles the move display on and off.
Definition at line 411 of file ProximMachineStateWindow.cc.
{
    showMoves_ = !showMoves_;
    if (showMoves_) {
        addMoves();
    } else {
        canvas_->clearMoves();
    }
    canvas_->Refresh();
}
References addMoves(), canvas_, MachineCanvas::clearMoves(), and showMoves_.
onToggleUnitInfo()
void ProximMachineStateWindow::onToggleUnitInfo (wxCommandEvent & event) private
Toggles the unit info string display on and off.
Definition at line 396 of file ProximMachineStateWindow.cc.
{
    OptionValue& showInfo = canvas_->options().optionValue(
        MachineCanvasOptions::SHOW_UNIT_INFO_STRING);
    showInfo.setBoolValue(!showInfo.isFlagOn());
    canvas_->updateMachine();
}
References canvas_, OptionValue::isFlagOn(), MachineCanvas::options(), Options::optionValue(), OptionValue::setBoolValue(), MachineCanvasOptions::SHOW_UNIT_INFO_STRING, and MachineCanvas::updateMachine().
onToggleUtilizations()
void ProximMachineStateWindow::onToggleUtilizations (wxCommandEvent & event) private
Toggles the utilization display on and off.
Definition at line 425 of file ProximMachineStateWindow.cc.
{
    showUtilizations_ = !showUtilizations_;
    SimulatorFrontend* frontend = ProximToolbox::frontend();
    if (showUtilizations_ && frontend != NULL) {
        setUtilizationHighlights();
    } else {
        canvas_->clearHighlights();
    }
    canvas_->Refresh();
}
References canvas_, MachineCanvas::clearHighlights(), ProximToolbox::frontend(), setUtilizationHighlights(), and showUtilizations_.
onUpdateUIEvent()
void ProximMachineStateWindow::onUpdateUIEvent (wxUpdateUIEvent & event) private
Event handler for meni item UI update events.
Parameters
event Update event to handle.
Definition at line 445 of file ProximMachineStateWindow.cc.
{
    if (event.GetId() == COMMAND_TOGGLE_MOVES) {
        event.Check(showMoves_);
    } else if (event.GetId() == COMMAND_TOGGLE_UTILIZATIONS) {
        event.Check(showUtilizations_);
    } else if (event.GetId() == COMMAND_TOGGLE_UNIT_INFO) {
        OptionValue& showInfo = canvas_->options().optionValue(
            MachineCanvasOptions::SHOW_UNIT_INFO_STRING);
        event.Check(showInfo.isFlagOn());
    } else {
        event.Skip();
    }
}
References canvas_, COMMAND_TOGGLE_MOVES, COMMAND_TOGGLE_UNIT_INFO, COMMAND_TOGGLE_UTILIZATIONS, OptionValue::isFlagOn(), MachineCanvas::options(), Options::optionValue(), MachineCanvasOptions::SHOW_UNIT_INFO_STRING, showMoves_, and showUtilizations_.
onZoom()
void ProximMachineStateWindow::onZoom (wxCommandEvent & event) private
Handles zoom menu item events.
Parameters
event Menu event to handle.
Definition at line 286 of file ProximMachineStateWindow.cc.
{
    // Zoom in.
    if (event.GetId() == COMMAND_ZOOM_IN) {
        canvas_->zoomIn();
    }
    // Zoom out.
    if (event.GetId() == COMMAND_ZOOM_OUT) {
        canvas_->zoomOut();
    }
}
References canvas_, COMMAND_ZOOM_IN, COMMAND_ZOOM_OUT, MachineCanvas::zoomIn(), and MachineCanvas::zoomOut().
reset()
void ProximMachineStateWindow::reset () virtual
Resets the machine displayed on the canvas when the machine is unloaded in the simulator.
Reimplemented from ProximSimulatorWindow.
Definition at line 147 of file ProximMachineStateWindow.cc.
{
    canvas_->setMachine(NULL);
}
References canvas_, and MachineCanvas::setMachine().
setMachine()
void ProximMachineStateWindow::setMachine (TTAMachine::Machine * machine)
setStatusText()
void ProximMachineStateWindow::setStatusText (std::string status)
Sets the status line text.
Parameters
status Status text to set.
Definition at line 274 of file ProximMachineStateWindow.cc.
{
    wxString text = WxConversion::toWxString(status);
    statusbar_->SetStatusText(text);
}
References statusbar_, and WxConversion::toWxString().
Referenced by ProximComponentStatusCmd::Do(), and ProximMachineCanvasTool::onMouseEvent().
setUtilizationHighlights()
void ProximMachineStateWindow::setUtilizationHighlights () private
Sets machine part highlights based on part utilizations.
Definition at line 304 of file ProximMachineStateWindow.cc.
{
    canvas_->clearHighlights();
    Machine* machine = const_cast<Machine*>(&ProximToolbox::machine());
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    ClockCycleCount cycles = ProximToolbox::frontend()->cycleCount();
    // Highlight buses.
    const Machine::BusNavigator& busNavigator = machine->busNavigator();
    for (int i = 0; i < busNavigator.count(); i++) {
        ClockCycleCount writes =
            stats.busWrites(busNavigator.item(i)->name());
        double utilization = static_cast<double>(writes) / cycles;
        unsigned value = unsigned(utilization * 255);
        canvas_->highlight(busNavigator.item(i), wxColour(value, 0, 0));
    }
    // Highlight sockets.
    const Machine::SocketNavigator& socketNavigator =
        machine->socketNavigator();
    for (int i = 0; i < socketNavigator.count(); i++) {
        ClockCycleCount writes =
            stats.socketWrites(socketNavigator.item(i)->name());
        double utilization = static_cast<double>(writes) / cycles;
        unsigned value = 255 - unsigned(utilization * 255);
        wxColour colour = wxColour(255, value, value);
        canvas_->highlight(socketNavigator.item(i), colour);
    }
    // Highlight function units.
    const Machine::FunctionUnitNavigator& fuNavigator =
        machine->functionUnitNavigator();
    for (int i = 0; i < fuNavigator.count(); i++) {
        ClockCycleCount writes =
            stats.triggerCount(fuNavigator.item(i)->name());
        double utilization = static_cast<double>(writes) / cycles;
        unsigned value = 255 - unsigned(utilization * 255);
        wxColour colour = wxColour(255, value, value);
        canvas_->highlight(fuNavigator.item(i), colour);
    }
}
References TTAMachine::Machine::busNavigator(), UtilizationStats::busWrites(), canvas_, MachineCanvas::clearHighlights(), TTAMachine::Machine::Navigator< ComponentType >::count(), SimulatorFrontend::cycleCount(), ProximToolbox::frontend(), TTAMachine::Machine::functionUnitNavigator(), MachineCanvas::highlight(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, ProximToolbox::machine(), TTAMachine::Machine::socketNavigator(), UtilizationStats::socketWrites(), UtilizationStats::triggerCount(), and SimulatorFrontend::utilizationStatistics().
Referenced by onSimulationStop(), and onToggleUtilizations().
Member Data Documentation
canvas_
MachineCanvas* ProximMachineStateWindow::canvas_ private
Machine visualization canvas.
Definition at line 92 of file ProximMachineStateWindow.hh.
Referenced by addMoves(), createContents(), onExport(), onProgramLoaded(), onSimulationStop(), onToggleMoves(), onToggleUnitInfo(), onToggleUtilizations(), onUpdateUIEvent(), onZoom(), reset(), and setUtilizationHighlights().
detailsCtrl_
wxTextCtrl* ProximMachineStateWindow::detailsCtrl_ private
Utilziation window where to display utilization data of the components.
Definition at line 119 of file ProximMachineStateWindow.hh.
Referenced by appendDetails(), clearDetails(), and createContents().
INITIAL_DETAILS_PANE_WIDTH
const int ProximMachineStateWindow::INITIAL_DETAILS_PANE_WIDTH = 200 static private
Initial width for the component detail pane.
Definition at line 125 of file ProximMachineStateWindow.hh.
Referenced by createContents().
MINIMUM_PANE_WIDTH
const int ProximMachineStateWindow::MINIMUM_PANE_WIDTH = 150 static private
Minimum width for the splitter window panes.
Definition at line 123 of file ProximMachineStateWindow.hh.
Referenced by createContents().
showMoves_
bool ProximMachineStateWindow::showMoves_ private
Tells if the moves are displayed or not.
Definition at line 113 of file ProximMachineStateWindow.hh.
Referenced by onSimulationStop(), onToggleMoves(), and onUpdateUIEvent().
showUtilizations_
bool ProximMachineStateWindow::showUtilizations_ private
Tells if the machine part utilizations are displayed or not.
Definition at line 115 of file ProximMachineStateWindow.hh.
Referenced by onSimulationStop(), onToggleUtilizations(), and onUpdateUIEvent().
simulator_
SimulatorFrontend* ProximMachineStateWindow::simulator_ private
Simulator instance which contains the registers to display.
Definition at line 94 of file ProximMachineStateWindow.hh.
Referenced by addMoves(), and onProgramLoaded().
sizer_
wxBoxSizer* ProximMachineStateWindow::sizer_ private
Toplevel sizer for the window widgets.
Definition at line 96 of file ProximMachineStateWindow.hh.
Referenced by createContents().
statusbar_
wxStatusBar* ProximMachineStateWindow::statusbar_ private
Statusbar of the window.
Definition at line 98 of file ProximMachineStateWindow.hh.
Referenced by createContents(), and setStatusText().
utilizationCtrl_
wxTextCtrl* ProximMachineStateWindow::utilizationCtrl_ private
Definition at line 120 of file ProximMachineStateWindow.hh.
Referenced by appendUtilizationData(), clearDetails(), and createContents().
The documentation for this class was generated from the following files:
ProximMachineStateWindow.hh
ProximMachineStateWindow.cc