OpenASIP: AddressSpaceDialog Class Reference
AddressSpaceDialog Class Reference
#include <AddressSpaceDialog.hh>
Public Member Functions
AddressSpaceDialog (wxWindow *parent, TTAMachine::Machine *machine, TTAMachine::AddressSpace *addressSpace)
~AddressSpaceDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_WIDTH , ID_MIN_ADDRESS , ID_MAX_ADDRESS ,
ID_BIT_WIDTH , ID_ID_LIST , ID_SPIN_ID , ID_ADD_ID ,
ID_DELETE_ID , ID_RADIO_MIN_DEC , ID_RADIO_MIN_HEX , ID_RADIO_MAX_DEC ,
ID_RADIO_MAX_HEX , ID_TEXT , ID_LINE , ID_HELP
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onName (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onMinAddress (wxCommandEvent &event)
void onMinHex (wxCommandEvent &event)
void onMaxAddress (wxCommandEvent &event)
void onMaxHex (wxCommandEvent &event)
void onMinToDec (wxCommandEvent &event)
void onMinToHex (wxCommandEvent &event)
void onMaxToDec (wxCommandEvent &event)
void onMaxToHex (wxCommandEvent &event)
void onBitWidth (wxSpinEvent &event)
void onBitWidthText (wxCommandEvent &event)
void onAddId (wxCommandEvent &event)
void onDeleteId (wxCommandEvent &event)
void onSpinId (wxSpinEvent &event)
void onIdListSelection (wxListEvent &event)
void updateIdLists ()
bool isFreeId (unsigned id) const
void setTexts ()
Private Attributes
TTAMachine::Machine * machine_
Machine containing all the address spaces.
TTAMachine::AddressSpace * as_
Address space to modify with the dialog.
wxString name_
Name of the address space.
int width_
The bit width of the minimum addressable word.
wxString minAddress_
The lowest address in the address space.
wxString maxAddress_
The highest address in the address space.
NumberControl * minControl_
Widget for the lowest address hex value.
NumberControl * maxControl_
Widget for the highest address hex value.
wxStaticBoxSizer * nameSizer_
Boxsizer containing the name widget.
wxStaticBoxSizer * minAddressSizer_
Boxsizer containing the min-address widget.
wxStaticBoxSizer * maxAddressSizer_
Boxsizer containing the max-address widget.
wxStaticBoxSizer * widthSizer_
Boxsizer containing the width widget.
wxSpinCtrl * bitWidthSpinCtrl_
SpinCtrl containing the bit width of the max-address.
wxStaticBoxSizer * idSizer_
Boxsizer containing the address space id widget.
wxListCtrl * idListCtrl_
List control containing the address space ids.
wxSpinCtrl * idSpinCtrl_
SpinCtrl containing an address space id.
std::set< unsigned > idNumbers_
Container for unique id numbers.
Detailed Description
Dialog for editing address space properties.
Definition at line 50 of file AddressSpaceDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NAME
ID_WIDTH
ID_MIN_ADDRESS
ID_MAX_ADDRESS
ID_BIT_WIDTH
ID_ID_LIST
ID_SPIN_ID
ID_ADD_ID
ID_DELETE_ID
ID_RADIO_MIN_DEC
ID_RADIO_MIN_HEX
ID_RADIO_MAX_DEC
ID_RADIO_MAX_HEX
ID_TEXT
ID_LINE
ID_HELP
Definition at line 123 of file AddressSpaceDialog.hh.
         {
        ID_NAME = 10000,
        ID_WIDTH,
        ID_MIN_ADDRESS,
        ID_MAX_ADDRESS,
        ID_BIT_WIDTH,
        ID_ID_LIST,
        ID_SPIN_ID,
        ID_ADD_ID,
        ID_DELETE_ID,
        ID_RADIO_MIN_DEC,
        ID_RADIO_MIN_HEX,
        ID_RADIO_MAX_DEC,
        ID_RADIO_MAX_HEX,
        ID_TEXT,
        ID_LINE,
        ID_HELP
    };
Constructor & Destructor Documentation
AddressSpaceDialog()
AddressSpaceDialog::AddressSpaceDialog (wxWindow * parent, TTAMachine::Machine * machine, TTAMachine::AddressSpace * addressSpace)
The Constructor.
Parameters
parent Parent window of the dialog.
addressSpace The address space to be modified with the dialog.
Definition at line 82 of file AddressSpaceDialog.cc.
                               :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    machine_(machine),
    as_(addressSpace),
    name_(_T("")),
    width_(ModelConstants::DEFAULT_WIDTH),
    nameSizer_(NULL),
    minAddressSizer_(NULL),
    maxAddressSizer_(NULL),
    widthSizer_(NULL) {
    createContents(this, true, true);
    // disable conditional buttons initially
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_DELETE_ID)->Disable();
    // set validators for dialog controls
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_WIDTH)->SetValidator(
        wxGenericValidator(&width_));
    // set min and max adress spin button ranges
    minControl_ = dynamic_cast<NumberControl*>(FindWindow(ID_MIN_ADDRESS));
    maxControl_ = dynamic_cast<NumberControl*>(FindWindow(ID_MAX_ADDRESS));
    bitWidthSpinCtrl_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_BIT_WIDTH));
    // set widget texts
    setTexts();
    TransferDataToWindow();
    FindWindow(ID_NAME)->SetFocus();
}
~AddressSpaceDialog()
AddressSpaceDialog::~AddressSpaceDialog ()
The Destructor.
Definition at line 126 of file AddressSpaceDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * AddressSpaceDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 494 of file AddressSpaceDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Name:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    nameSizer_ = item2;
    wxTextCtrl *item4 = new wxTextCtrl(parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(160,-1), 0);
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item6 = new wxStaticBox( parent, -1, wxT("Min-Address") );
    wxStaticBoxSizer *item5 = new wxStaticBoxSizer( item6, wxVERTICAL );
    minAddressSizer_ = item5;
    NumberControl* item7 = new NumberControl(parent, ID_MIN_ADDRESS, wxDefaultPosition, wxSize(180, -1), (NumberControl::MODE_UNSIGNED | NumberControl::MODE_HEXADECIMAL));
    wxASSERT( item7 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item9 = new wxStaticBox( parent, -1, wxT("Width:") );
    wxStaticBoxSizer *item8 = new wxStaticBoxSizer( item9, wxVERTICAL );
    widthSizer_ = item8;
    wxSpinCtrl *item10 = new wxSpinCtrl(parent, ID_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1, wxT("Spin"));
    item8->Add( item10, 0, wxGROW|wxALL, 5 );
    item1->Add( item8, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("Max-Address") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );
    maxAddressSizer_ = item11;
    NumberControl* item13 = new NumberControl(parent, ID_MAX_ADDRESS, wxDefaultPosition, wxSize(180, -1), (NumberControl::MODE_UNSIGNED | NumberControl::MODE_HEXADECIMAL));
    wxASSERT( item13 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *bitSizer = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText *bitText = new wxStaticText(parent, -1, wxT("Bits:"));
    bitSizer->Add( bitText, 0, wxGROW|wxALL, 5 );
    wxSpinCtrl *bitWidth = new wxSpinCtrl( parent, ID_BIT_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1);
    bitSizer->Add( bitWidth, 0, wxGROW|wxALL, 5 );
    item11->Add( bitSizer, 0, wxGROW|wxALL, 5 );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    // address space id box
    wxStaticBox *itemIdBox = new wxStaticBox(parent, -1, wxT("ID number:"));
    wxStaticBoxSizer *itemIdSizer = new wxStaticBoxSizer(itemIdBox,
                                                          wxHORIZONTAL);
    idSizer_ = itemIdSizer;
    wxListCtrl *itemIdListCtrl = new wxListCtrl( parent, ID_ID_LIST,
                                                 wxDefaultPosition,
                                                 wxSize(100,120),
                                                 wxLC_REPORT|wxSUNKEN_BORDER );
    idSizer_->Add( itemIdListCtrl, 0, wxALIGN_CENTER|wxALL, 5 );
    idListCtrl_ = itemIdListCtrl;
    idListCtrl_->InsertColumn(0, _("ID"));
    wxBoxSizer *sizerOnRight = new wxBoxSizer(wxVERTICAL);
    wxSpinCtrl *itemIdSpinCtrl = new wxSpinCtrl( parent, ID_SPIN_ID, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 2147483647, 1, wxT("Spin") );
    sizerOnRight->Add( itemIdSpinCtrl, 0, wxGROW|wxALL, 5 );
    idSpinCtrl_ = itemIdSpinCtrl;
    wxButton *addButton = new wxButton( parent, ID_ADD_ID, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    sizerOnRight->Add( addButton, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *deleteButton = new wxButton( parent, ID_DELETE_ID, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    sizerOnRight->Add( deleteButton, 0, wxALIGN_CENTER|wxALL, 5 );
    idSizer_->Add( sizerOnRight, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( idSizer_, 0, wxGROW|wxALL, 5 );
    assert (idSizer_ != NULL);
    assert (idListCtrl_ != NULL);
    assert (idSpinCtrl_ != NULL);
    // end of address space id box
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item14 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item14, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item15 = new wxGridSizer( 2, 0, 0 );
    wxButton *item16 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALL, 5 );
    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item18 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER, 5 );
    wxButton *item19 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    item15->Add( item17, 0, wxALL, 5 );
    item0->Add( item15, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References assert, ID_ADD_ID, ID_BIT_WIDTH, ID_DELETE_ID, ID_HELP, ID_ID_LIST, ID_LINE, ID_MAX_ADDRESS, ID_MIN_ADDRESS, ID_NAME, ID_SPIN_ID, ID_WIDTH, idListCtrl_, idSizer_, idSpinCtrl_, maxAddressSizer_, minAddressSizer_, NumberControl::MODE_HEXADECIMAL, NumberControl::MODE_UNSIGNED, nameSizer_, and widthSizer_.
isFreeId()
bool AddressSpaceDialog::isFreeId (unsigned id) const private
Checks if given id is already reserved by some address space
Parameters
id Number that should be checked against reserved ids
Definition at line 450 of file AddressSpaceDialog.cc.
{
    assert (machine_ != NULL);
    std::set<unsigned>::iterator it;
    // check id numbers reserved by this address space
    it = idNumbers_.find(id);
    if (it != idNumbers_.end()) {
        return false;
    }
    Machine::AddressSpaceNavigator asNavigator =
    machine_->addressSpaceNavigator();
    // check other address spaces
    for (int i = 0; i < asNavigator.count(); i++) {
        AddressSpace* as = asNavigator.item(i);
        // ignore address space owned by this because data might be old
        if (as != as_) {
            std::set<unsigned> ids = as->numericalIds();
            it = ids.find(id);
            if (it != ids.end()) {
                return false;
            }
        }
    }
    // the id is free
    return true;
}
References TTAMachine::Machine::addressSpaceNavigator(), as_, assert, TTAMachine::Machine::Navigator< ComponentType >::count(), idNumbers_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, and TTAMachine::AddressSpace::numericalIds().
Referenced by onAddId(), and onSpinId().
onAddId()
void AddressSpaceDialog::onAddId (wxCommandEvent & event) private
Adds a new id number for the address space.
Definition at line 366 of file AddressSpaceDialog.cc.
{
    // current number in spin field
    unsigned spinId = static_cast<unsigned>(idSpinCtrl_->GetValue());
    // existing entry found from some address space
    if (!isFreeId(spinId)) {
        return;
    }
    // no conflict, make a new entry for the current value in the spin field
    idNumbers_.insert(spinId);
    updateIdLists();
    // disable add button for added id number
    FindWindow(ID_ADD_ID)->Disable();
}
References ID_ADD_ID, idNumbers_, idSpinCtrl_, isFreeId(), and updateIdLists().
onBitWidth()
void AddressSpaceDialog::onBitWidth (wxSpinEvent & event) private
Reads the range from bitWidth spin-button and updates min- and max ranges.
Definition at line 351 of file AddressSpaceDialog.cc.
{
    unsigned maxAddress = static_cast<unsigned>(
        pow(2, bitWidthSpinCtrl_->GetValue()) - 1u);
    maxControl_->setValue(maxAddress);
    wxCommandEvent dummy;
    onMaxAddress(dummy);
    onMinAddress(dummy);
}
References bitWidthSpinCtrl_, dummy, maxControl_, onMaxAddress(), onMinAddress(), and NumberControl::setValue().
onBitWidthText()
void AddressSpaceDialog::onBitWidthText (wxCommandEvent & event) private
Reads the range from bitWidth spin-button and updates min- and max ranges.
Definition at line 342 of file AddressSpaceDialog.cc.
{
    //wxSpinEvent dummy;
    //onBitWidth(dummy);
}
onDeleteId()
void AddressSpaceDialog::onDeleteId (wxCommandEvent & event) private
Deletes selected id number(s) from the address space.
Definition at line 387 of file AddressSpaceDialog.cc.
{
    long itemIndex = -1;
    // loop through all selected ids
    for (int i = 0; i < idListCtrl_->GetSelectedItemCount(); ++i) {
        itemIndex = idListCtrl_->GetNextItem(
            itemIndex, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        // get numerical value of the id and erase it from the address space
        if (itemIndex >= 0) {
            wxString idText = idListCtrl_->GetItemText(itemIndex);
            long id;
            if (idText.ToLong(&id)) {
                idNumbers_.erase(id);
            }
        }
    }
    updateIdLists();
    wxSpinEvent dummy1;
    onSpinId(dummy1);
    wxListEvent dummy2;
    onIdListSelection(dummy2);
}
References idListCtrl_, idNumbers_, onIdListSelection(), onSpinId(), and updateIdLists().
onHelp()
void AddressSpaceDialog::onHelp (wxCommandEvent & event) private
onIdListSelection()
void AddressSpaceDialog::onIdListSelection (wxListEvent & event) private
Sets state of delete button depending on whether items are selected
Definition at line 436 of file AddressSpaceDialog.cc.
{
    if (idListCtrl_->GetSelectedItemCount() < 1) {
        FindWindow(ID_DELETE_ID)->Disable();
    } else {
        FindWindow(ID_DELETE_ID)->Enable();
    }
}
References ID_DELETE_ID, and idListCtrl_.
Referenced by onDeleteId().
onMaxAddress()
void AddressSpaceDialog::onMaxAddress (wxCommandEvent & event) private
Sets the range of the MaxAddress spin-button.
Definition at line 330 of file AddressSpaceDialog.cc.
{
    if (maxControl_->unsignedValue() <= minControl_->unsignedValue()) {
        maxControl_->setValue(minControl_->unsignedValue() + 1);
    }
    int bitWidth = MathTools::requiredBits(maxControl_->unsignedValue());
    bitWidthSpinCtrl_->SetValue(bitWidth);
}
References bitWidthSpinCtrl_, maxControl_, minControl_, MathTools::requiredBits(), NumberControl::setValue(), and NumberControl::unsignedValue().
Referenced by onBitWidth(), and TransferDataToWindow().
onMaxHex()
void AddressSpaceDialog::onMaxHex (wxCommandEvent & event) private
onMaxToDec()
void AddressSpaceDialog::onMaxToDec (wxCommandEvent & event) private
onMaxToHex()
void AddressSpaceDialog::onMaxToHex (wxCommandEvent & event) private
onMinAddress()
void AddressSpaceDialog::onMinAddress (wxCommandEvent & event) private
Sets the range of the MaxAddress spin-button.
Definition at line 319 of file AddressSpaceDialog.cc.
{
    if (minControl_->unsignedValue() >= maxControl_->unsignedValue()) {
        minControl_->setValue(maxControl_->unsignedValue() - 1);
    }
}
References maxControl_, minControl_, NumberControl::setValue(), and NumberControl::unsignedValue().
Referenced by onBitWidth(), and TransferDataToWindow().
onMinHex()
void AddressSpaceDialog::onMinHex (wxCommandEvent & event) private
onMinToDec()
void AddressSpaceDialog::onMinToDec (wxCommandEvent & event) private
onMinToHex()
void AddressSpaceDialog::onMinToHex (wxCommandEvent & event) private
onName()
void AddressSpaceDialog::onName (wxCommandEvent & event) private
Checks whether the name field is empty, and disables OK button of the dialog if it is.
Definition at line 302 of file AddressSpaceDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void AddressSpaceDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the AddressSpace.
Definition at line 226 of file AddressSpaceDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
    WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (trimmedName != as_->name()) {
        // Check that the new address space name is unique among
        // all address spaces in the machine.
    Machine::AddressSpaceNavigator navigator =
        as_->machine()->addressSpaceNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            string asName = navigator.item(i)->name();
            if (trimmedName == asName) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format an_as = prodeTexts->text(
                    ProDeTextGenerator::COMP_AN_ADDRESS_SPACE);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format as =
                    prodeTexts->text(ProDeTextGenerator::COMP_ADDRESS_SPACE);
                message % trimmedName % an_as.str() % machine.str() % as.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    as_->setName(trimmedName);
    as_->setWidth(width_);
    unsigned int minAddr = minControl_->unsignedValue();
    unsigned int maxAddr = maxControl_->unsignedValue();
    as_->setAddressBounds(minAddr, maxAddr);
    if (!as_->setNumericalIds(idNumbers_)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ID_EXISTS);
        InformationDialog dialog(
            this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
    }
    EndModal(wxID_OK);
}
References TTAMachine::Machine::addressSpaceNavigator(), as_, ProDeTextGenerator::COMP_ADDRESS_SPACE, ProDeTextGenerator::COMP_AN_ADDRESS_SPACE, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::count(), idNumbers_, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, maxControl_, minControl_, ProDeTextGenerator::MSG_ERROR_ID_EXISTS, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::AddressSpace::setAddressBounds(), TTAMachine::AddressSpace::setName(), TTAMachine::AddressSpace::setNumericalIds(), TTAMachine::AddressSpace::setWidth(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), NumberControl::unsignedValue(), and width_.
onSpinId()
void AddressSpaceDialog::onSpinId (wxSpinEvent & event) private
Sets state of add button depending on whether the number in spin input already exists in some address space
Definition at line 418 of file AddressSpaceDialog.cc.
{
    // current number in spin field
    unsigned spinId = static_cast<unsigned>(idSpinCtrl_->GetValue());
    // no conflict found, enable add button
    if (isFreeId(spinId)) {
        FindWindow(ID_ADD_ID)->Enable();
        return;
    }
    // the number is already reserved, disable add button
    FindWindow(ID_ADD_ID)->Disable();
}
References ID_ADD_ID, idSpinCtrl_, and isFreeId().
Referenced by onDeleteId(), and TransferDataToWindow().
setTexts()
void AddressSpaceDialog::setTexts () private
Sets texts for widgets.
Definition at line 134 of file AddressSpaceDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_ADDRESS_SPACE_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_ID),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_ID),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // box sizer label
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setWidgetLabel(nameSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_LABEL_MAU);
    WidgetTools::setWidgetLabel(widthSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_ADDRESS_SPACE_MIN_ADDRESS);
    WidgetTools::setWidgetLabel(minAddressSizer_, fmt.str());
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_ADDRESS_SPACE_MAX_ADDRESS);
    WidgetTools::setWidgetLabel(maxAddressSizer_, fmt.str());
}
References ID_ADD_ID, ID_DELETE_ID, ID_HELP, GUITextGenerator::instance(), ProDeTextGenerator::instance(), maxAddressSizer_, minAddressSizer_, nameSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_ADDRESS_SPACE_DIALOG_TITLE, ProDeTextGenerator::TXT_ADDRESS_SPACE_MAX_ADDRESS, ProDeTextGenerator::TXT_ADDRESS_SPACE_MIN_ADDRESS, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_LABEL_MAU, ProDeTextGenerator::TXT_LABEL_NAME, and widthSizer_.
TransferDataToWindow()
bool AddressSpaceDialog::TransferDataToWindow () private virtual
Transfers data from the AddressSpace object to the dialog widgets.
Returns
false, if an error occured in the transfer, true otherwise.
Definition at line 180 of file AddressSpaceDialog.cc.
{
    name_ = WxConversion::toWxString(as_->name());
    width_ = as_->width();
    minControl_->setValue(as_->start());
    maxControl_->setValue(as_->end());
    //minControl_->setRange(0, as_->end() - 1);
    //maxControl_->setRange(as_->start() + 1, 0xFFFFFFFF);
    idNumbers_ = as_->numericalIds();
    updateIdLists();
    // wxWidgets GTK1 version seems to bug with spincontrol validators.
    // The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_WIDTH))->SetValue(width_);
    wxCommandEvent dummy;
    onMaxAddress(dummy);
    onMinAddress(dummy);
    wxSpinEvent dummySpin;
    onSpinId(dummySpin);
    return wxWindow::TransferDataToWindow();
}
References as_, dummy, TTAMachine::AddressSpace::end(), ID_WIDTH, idNumbers_, maxControl_, minControl_, TTAMachine::Component::name(), name_, TTAMachine::AddressSpace::numericalIds(), onMaxAddress(), onMinAddress(), onSpinId(), NumberControl::setValue(), TTAMachine::AddressSpace::start(), WxConversion::toWxString(), updateIdLists(), TTAMachine::AddressSpace::width(), and width_.
updateIdLists()
void AddressSpaceDialog::updateIdLists () private
Updates the id lists.
Definition at line 211 of file AddressSpaceDialog.cc.
{
    assert (idListCtrl_ != NULL);
    idListCtrl_->DeleteAllItems();
    for (std::set<unsigned>::iterator it = idNumbers_.begin();
         it != idNumbers_.end(); ++it) {
        idListCtrl_->InsertItem(
            static_cast<long>(*it), WxConversion::toWxString(*it));
    }
}
References assert, idListCtrl_, idNumbers_, and WxConversion::toWxString().
Referenced by onAddId(), onDeleteId(), and TransferDataToWindow().
Member Data Documentation
as_
TTAMachine::AddressSpace* AddressSpaceDialog::as_ private
Address space to modify with the dialog.
Definition at line 87 of file AddressSpaceDialog.hh.
Referenced by isFreeId(), onOK(), and TransferDataToWindow().
bitWidthSpinCtrl_
wxSpinCtrl* AddressSpaceDialog::bitWidthSpinCtrl_ private
SpinCtrl containing the bit width of the max-address.
Definition at line 110 of file AddressSpaceDialog.hh.
Referenced by onBitWidth(), and onMaxAddress().
idListCtrl_
wxListCtrl* AddressSpaceDialog::idListCtrl_ private
List control containing the address space ids.
Definition at line 115 of file AddressSpaceDialog.hh.
Referenced by createContents(), onDeleteId(), onIdListSelection(), and updateIdLists().
idNumbers_
std::set<unsigned> AddressSpaceDialog::idNumbers_ private
Container for unique id numbers.
Definition at line 120 of file AddressSpaceDialog.hh.
Referenced by isFreeId(), onAddId(), onDeleteId(), onOK(), TransferDataToWindow(), and updateIdLists().
idSizer_
wxStaticBoxSizer* AddressSpaceDialog::idSizer_ private
Boxsizer containing the address space id widget.
Definition at line 113 of file AddressSpaceDialog.hh.
Referenced by createContents().
idSpinCtrl_
wxSpinCtrl* AddressSpaceDialog::idSpinCtrl_ private
SpinCtrl containing an address space id.
Definition at line 117 of file AddressSpaceDialog.hh.
Referenced by createContents(), onAddId(), and onSpinId().
machine_
TTAMachine::Machine* AddressSpaceDialog::machine_ private
Machine containing all the address spaces.
Definition at line 85 of file AddressSpaceDialog.hh.
Referenced by isFreeId().
maxAddress_
wxString AddressSpaceDialog::maxAddress_ private
The highest address in the address space.
Definition at line 95 of file AddressSpaceDialog.hh.
maxAddressSizer_
wxStaticBoxSizer* AddressSpaceDialog::maxAddressSizer_ private
Boxsizer containing the max-address widget.
Definition at line 106 of file AddressSpaceDialog.hh.
Referenced by createContents(), and setTexts().
maxControl_
NumberControl* AddressSpaceDialog::maxControl_ private
Widget for the highest address hex value.
Definition at line 99 of file AddressSpaceDialog.hh.
Referenced by onBitWidth(), onMaxAddress(), onMinAddress(), onOK(), and TransferDataToWindow().
minAddress_
wxString AddressSpaceDialog::minAddress_ private
The lowest address in the address space.
Definition at line 93 of file AddressSpaceDialog.hh.
minAddressSizer_
wxStaticBoxSizer* AddressSpaceDialog::minAddressSizer_ private
Boxsizer containing the min-address widget.
Definition at line 104 of file AddressSpaceDialog.hh.
Referenced by createContents(), and setTexts().
minControl_
NumberControl* AddressSpaceDialog::minControl_ private
Widget for the lowest address hex value.
Definition at line 97 of file AddressSpaceDialog.hh.
Referenced by onMaxAddress(), onMinAddress(), onOK(), and TransferDataToWindow().
name_
wxString AddressSpaceDialog::name_ private
Name of the address space.
Definition at line 89 of file AddressSpaceDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
nameSizer_
wxStaticBoxSizer* AddressSpaceDialog::nameSizer_ private
Boxsizer containing the name widget.
Definition at line 102 of file AddressSpaceDialog.hh.
Referenced by createContents(), and setTexts().
width_
int AddressSpaceDialog::width_ private
The bit width of the minimum addressable word.
Definition at line 91 of file AddressSpaceDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
widthSizer_
wxStaticBoxSizer* AddressSpaceDialog::widthSizer_ private
Boxsizer containing the width widget.
Definition at line 108 of file AddressSpaceDialog.hh.
Referenced by createContents(), and setTexts().
The documentation for this class was generated from the following files:
AddressSpaceDialog.hh
AddressSpaceDialog.cc