OpenASIP: OSEdAddOperationCmd Class Reference
OSEdAddOperationCmd Class Reference
#include <OSEdAddOperationCmd.hh>
Public Member Functions
OSEdAddOperationCmd ()
virtual ~OSEdAddOperationCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdAddOperationCmd (const OSEdAddOperationCmd &)
Copying not allowed.
OSEdAddOperationCmd operator= (OSEdAddOperationCmd &)
Assignment not allowed.
Detailed Description
Command for adding new operation to operation set.
Definition at line 43 of file OSEdAddOperationCmd.hh.
Constructor & Destructor Documentation
OSEdAddOperationCmd() [1/2]
OSEdAddOperationCmd::OSEdAddOperationCmd ()
Constructor.
Definition at line 57 of file OSEdAddOperationCmd.cc.
                                         :
    GUICommand(OSEdConstants::CMD_NAME_ADD_OPERATION, NULL) {
}
Referenced by create().
~OSEdAddOperationCmd()
OSEdAddOperationCmd::~OSEdAddOperationCmd () virtual
Destructor.
Definition at line 64 of file OSEdAddOperationCmd.cc.
{
}
OSEdAddOperationCmd() [2/2]
OSEdAddOperationCmd::OSEdAddOperationCmd (const OSEdAddOperationCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdAddOperationCmd::create () const virtual
Creates a new command.
Returns
New command.
Implements GUICommand.
Definition at line 83 of file OSEdAddOperationCmd.cc.
{
    return new OSEdAddOperationCmd();
}
References OSEdAddOperationCmd().
Do()
bool OSEdAddOperationCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 91 of file OSEdAddOperationCmd.cc.
{
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTreeView* treeView = mainFrame->treeView();
    string modName = treeView->selectedModule();
    wxTreeItemId modId = treeView->selectedModuleId();
    string pathName = treeView->pathOfModule(modId);
    OperationIndex& index = OperationContainer::operationIndex();
    OperationModule& module = OperationContainer::module(pathName, modName);
    assert(&module != &NullOperationModule::instance());
    OperationPropertyDialog dialog(parentWindow(), NULL, module, pathName);
    if (dialog.ShowModal() == wxID_OK) {
        Operation* op = dialog.operation();
        OperationSerializer& serializer =
            OperationContainer::operationSerializer();
        serializer.setDestinationFile(module.propertiesModule());
        ObjectState* root = new ObjectState("");
        for (int k = 0; k < index.operationCount(module); k++) {
            string opName = index.operationName(k, module);
            Operation* oper = OperationContainer::operation(
                pathName, modName, opName);
            root->addChild(oper->saveState());
            delete oper;
        }
        root->addChild(op->saveState());
        try {
            serializer.writeState(root);
            delete root;
        } catch (const SerializerException& s) {
            wxString msg = WxConversion::toWxString(s.errorMessage());
            ErrorDialog eDialog(parentWindow(), msg);
            eDialog.ShowModal();
            delete root;
            delete op;
            return false;
        }
        index.refreshModule(pathName, modName);
        treeView->addItem(modId, op->name());
        treeView->update();
    }
    return true;
}
References ObjectState::addChild(), OSEdTreeView::addItem(), assert, Exception::errorMessage(), NullOperationModule::instance(), Operation::name(), OperationPropertyDialog::operation(), OperationContainer::operation(), OperationIndex::operationCount(), OperationContainer::operationIndex(), OperationIndex::operationName(), OperationContainer::operationSerializer(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), OperationIndex::refreshModule(), Operation::saveState(), OSEdTreeView::selectedModule(), OSEdTreeView::selectedModuleId(), OperationSerializer::setDestinationFile(), WxConversion::toWxString(), OSEdMainFrame::treeView(), OSEdTreeView::update(), and OperationSerializer::writeState().
icon()
string OSEdAddOperationCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (no icons used).
Implements GUICommand.
Definition at line 178 of file OSEdAddOperationCmd.cc.
{
    return "";
}
id()
int OSEdAddOperationCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 73 of file OSEdAddOperationCmd.cc.
{
    return OSEdConstants::CMD_ADD_OPERATION;
}
References OSEdConstants::CMD_ADD_OPERATION.
isEnabled()
bool OSEdAddOperationCmd::isEnabled () virtual
Returns true, if command is enabled.
Operation can be added, if path is writable.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 154 of file OSEdAddOperationCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    string modName = treeView->selectedModule();
    if (modName != "") {
        wxTreeItemId modId = treeView->selectedModuleId();
        string pathName = treeView->pathOfModule(modId);
        string tempFile = pathName + FileSystem::DIRECTORY_SEPARATOR +
            "temp12341";
        if (FileSystem::createFile(tempFile)) {
            FileSystem::removeFileOrDirectory(tempFile);
            return true;
        } else {
            return false;
        }
    }
    return false;
}
References FileSystem::createFile(), FileSystem::DIRECTORY_SEPARATOR, OSEdTreeView::pathOfModule(), FileSystem::removeFileOrDirectory(), OSEdTreeView::selectedModule(), and OSEdTreeView::selectedModuleId().
operator=()
OSEdAddOperationCmd OSEdAddOperationCmd::operator= (OSEdAddOperationCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdAddOperationCmd.hh
OSEdAddOperationCmd.cc