OpenASIP: TTAMachine::AddressSpace Class Reference
TTAMachine::AddressSpace Class Reference
#include <AddressSpace.hh>
Public Member Functions
AddressSpace (const std::string &name, int width, ULongWord minAddress, ULongWord maxAddress, Machine &owner)
AddressSpace (const ObjectState *state, Machine &owner)
virtual ~AddressSpace ()
virtual int width () const
virtual ULongWord start () const
virtual ULongWord end () const
virtual void setName (const std::string &name)
virtual void setWidth (int width)
virtual void setAddressBounds (ULongWord start, ULongWord end)
virtual void addNumericalId (unsigned id)
virtual bool hasNumericalId (unsigned id) const
std::set< unsigned > numericalIds () const
bool setNumericalIds (const std::set< unsigned > &ids)
virtual void setShared (bool shared)
virtual bool isShared () const
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
bool operator== (const AddressSpace &other) const
bool operator!= (const AddressSpace &other) const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_ADDRESS_SPACE = "adress_space"
ObjectState name for AddressSpace.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for the bit width.
static const std::string OSKEY_MIN_ADDRESS = "min_a"
ObjectState attribute key for minimum address.
static const std::string OSKEY_MAX_ADDRESS = "max_a"
ObjectState attribute key for maximum address.
static const std::string OSKEY_SHARED_MEMORY = "shared-memory"
static const std::string OSKEY_NUMERICAL_ID = "numerical-id"
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Types
typedef std::set< unsigned > IDSet
Private Attributes
int width_
Bit width of the minimum addressable word.
ULongWord minAddress_
Lowest address in the address space.
ULongWord maxAddress_
Highest address in the address space.
IDSet numericalIds_
The numerical ids mapped to this address space.
bool shared_
True in case this address space maps to a memory that is shared across all the cores in the multicore.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents an address space in the machine.
Definition at line 51 of file AddressSpace.hh.
Member Typedef Documentation
IDSet
typedef std::set<unsigned> TTAMachine::AddressSpace::IDSet private
Definition at line 95 of file AddressSpace.hh.
Constructor & Destructor Documentation
AddressSpace() [1/2]
TTAMachine::AddressSpace::AddressSpace (const std::string & name, int width, ULongWord minAddress, ULongWord maxAddress, Machine & owner)
Constructor.
Parameters
name Name of the address space.
width Bit width of the minimum addressable word.
minAddress Lowest address in the address space.
maxAddress Highest address in the address space.
owner The machine which owns the address space.
Exceptions
ComponentAlreadyExists If another address space by the same name is already registered to the machine.
OutOfRange If the some of the given parameters is out of range.
InvalidName If the given name is not valid for a component.
Definition at line 74 of file AddressSpace.cc.
    : Component(name) {
    if (width <= 0 || minAddress >= maxAddress) {
        string procName = "AddressSpace::AddressSpace";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    width_ = width;
    minAddress_ = minAddress;
    maxAddress_ = maxAddress;
    setMachine(owner);
}
References maxAddress_, minAddress_, setMachine(), width(), and width_.
AddressSpace() [2/2]
TTAMachine::AddressSpace::AddressSpace (const ObjectState * state, Machine & owner)
Constructor.
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState from which the name is taken.
owner The machine which owns the address space.
Exceptions
ObjectStateLoadingException If the machine already has an address space by the same name as the coming name of this or if the ObjectState instance is invalid.
Definition at line 103 of file AddressSpace.cc.
    : Component(state),
      width_(0),
      minAddress_(0),
      maxAddress_(0),
      shared_(true) {
    loadState(state);
    for (IDSet::const_iterator i = numericalIds_.begin();
         i != numericalIds_.end(); ++i) {
        unsigned id = (*i);
        TTAMachine::Machine::AddressSpaceNavigator nav = owner.addressSpaceNavigator();
        for (int asi = 0; asi < nav.count(); ++asi) {
            AddressSpace& otherAS = *nav.item(asi);
            if (otherAS.hasNumericalId(id)) {
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, __func__,
                    (boost::format(
                        "Address space '%s' has the same numerical "
                        "id %d as '%s'.") %
                     otherAS.name() % id % name()).str());
            }
        }
    }
    try {
        setMachine(owner);
    } catch (ComponentAlreadyExists&) {
        MOMTextGenerator textGenerator;
        format errorMsg = textGenerator.text(MOMTextGenerator::
                                         TXT_AS_EXISTS_BY_NAME);
        errorMsg % name();
        string procName = "AddressSpace::AddressSpace";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          errorMsg.str());
    }
}
References __func__, TTAMachine::Machine::addressSpaceNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), hasNumericalId(), TTAMachine::Machine::Navigator< ComponentType >::item(), loadState(), TTAMachine::Component::name(), numericalIds_, setMachine(), and Texts::TextGenerator::text().
~AddressSpace()
TTAMachine::AddressSpace::~AddressSpace () virtual
Destructor.
Definition at line 144 of file AddressSpace.cc.
{
    unsetMachine();
}
References unsetMachine().
Member Function Documentation
addNumericalId()
void TTAMachine::AddressSpace::addNumericalId (unsigned id) virtual
Adds a numerical address space id that should be mapped to this address space.
Numerical IDs are referred to from programs, i.e., by means of the attribute((address_space(N)). Single ADF address space can map multiple program address spaces.
Definition at line 378 of file AddressSpace.cc.
{
    numericalIds_.insert(id);
}
References numericalIds_.
Referenced by loadState().
end()
ULongWord TTAMachine::AddressSpace::end () const virtual
Returns the highest memory address of the address space.
Returns
The highest memory address of the address space.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 177 of file AddressSpace.cc.
{
    return maxAddress_;
}
References maxAddress_.
Referenced by ProGe::ProcessorWrapperBlock::addInstructionMemory(), ProGe::NetlistGenerator::calculateAddressWidth(), MachineValidator::checkIMemAddrWidth(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), OpsetDialog::createOperation(), VectorLSGenerator::createVectorLSU(), PlatformIntegrator::dmemInfo(), llvm::LLVMTCEBuilder::emitSPInitialization(), InfoProcCommand::execute(), CodeSectionCreator::finalize(), ITemplateBroker::findITemplates(), ProGeTestBenchGenerator::generate(), ProGe::ProcessorGenerator::iMemAddressWidth(), SimulatorFrontend::initializeDataMemories(), SimulatorFrontend::initializeMemorySystem(), ProGe::NetlistGenerator::instructionMemoryAddressWidth(), ProximMemoryWindow::loadMemory(), AddWatchDialog::onASChoice(), printLatexAddressSpaceDescription(), ProGe::ProGeUI::readImemParameters(), PlatformIntegrator::readLsuParameters(), MachineConnectivityCheck::requiredImmediateWidth(), setAddressBounds(), AddressSpaceDialog::TransferDataToWindow(), and AddressSpacesDialog::updateASList().
hasNumericalId()
bool TTAMachine::AddressSpace::hasNumericalId (unsigned id) const virtual
Definition at line 383 of file AddressSpace.cc.
{
    return AssocTools::containsKey(numericalIds_, id);
}
References AssocTools::containsKey(), and numericalIds_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), AddressSpace(), llvm::LLVMTCEBuilder::addressSpaceById(), llvm::LLVMTCEBuilder::emitOperationMacro(), AlmaIFIntegrator::findMemories(), and MachineInfo::maxMemoryAlignment().
isShared()
virtual bool TTAMachine::AddressSpace::isShared () const inline virtual
Definition at line 72 of file AddressSpace.hh.
{ return shared_; }
References shared_.
Referenced by SimulatorFrontend::initializeDataMemories(), SimulatorFrontend::initializeMemorySystem(), ProGe::ProGeUI::readImemParameters(), and MemorySystem::shareMemoriesWith().
loadState()
void TTAMachine::AddressSpace::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if the machine already has an address space by the same name as the coming name of this address space.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 334 of file AddressSpace.cc.
{
    const string procName = "AddressSpace::loadState";
    if (state->name() != OSNAME_ADDRESS_SPACE) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Component::loadState(state);
    try {
        setWidth(state->intAttribute(OSKEY_WIDTH));
        ULongWord minAddress = state->uLongAttribute(
            OSKEY_MIN_ADDRESS);
        ULongWord maxAddress = state->uLongAttribute(
            OSKEY_MAX_ADDRESS);
        setAddressBounds(minAddress, maxAddress);
        if (state->hasAttribute(OSKEY_SHARED_MEMORY)) {
            setShared(
                state->boolAttribute(OSKEY_SHARED_MEMORY));
        }
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == OSKEY_NUMERICAL_ID) {
                addNumericalId(child->intValue());
            }
        }
    } catch (Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
}
References addNumericalId(), ObjectState::boolAttribute(), ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::hasAttribute(), ObjectState::intAttribute(), ObjectState::intValue(), TTAMachine::Component::loadState(), ObjectState::name(), OSKEY_MAX_ADDRESS, OSKEY_MIN_ADDRESS, OSKEY_NUMERICAL_ID, OSKEY_SHARED_MEMORY, OSKEY_WIDTH, OSNAME_ADDRESS_SPACE, setAddressBounds(), setShared(), setWidth(), and ObjectState::uLongAttribute().
Referenced by AddressSpace().
numericalIds()
std::set< unsigned > TTAMachine::AddressSpace::numericalIds () const
Returns ids that are assigned to this address space.
Returns
Address space ids.
Definition at line 393 of file AddressSpace.cc.
{
    return numericalIds_;
}
References numericalIds_.
Referenced by AddressSpaceDialog::isFreeId(), printLatexAddressSpaceDescription(), setNumericalIds(), and AddressSpaceDialog::TransferDataToWindow().
operator!=()
bool TTAMachine::AddressSpace::operator!= (const AddressSpace & other) const
Definition at line 441 of file AddressSpace.cc.
{
    return !this->operator==(other);
}
References operator==().
operator==()
bool TTAMachine::AddressSpace::operator== (const AddressSpace & other) const
Definition at line 432 of file AddressSpace.cc.
{
    return (this->width_ == other.width_
        && this->minAddress_ == other.minAddress_
        && this->maxAddress_ == other.maxAddress_
        && this->numericalIds_ == other.numericalIds_
        && this->shared_ == other.shared_);
}
References maxAddress_, minAddress_, numericalIds_, shared_, and width_.
Referenced by operator!=().
saveState()
ObjectState * TTAMachine::AddressSpace::saveState () const virtual
Saves the contents to an ObjectState object.
Returns
The newly created ObjectState object.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 295 of file AddressSpace.cc.
{
    ObjectState* as = new ObjectState(OSNAME_ADDRESS_SPACE);
    as->setAttribute(OSKEY_NAME, name());
    // set width
    as->setAttribute(OSKEY_WIDTH, width_);
    // set min address
    as->setAttribute(OSKEY_MIN_ADDRESS, minAddress_);
    // set max address
    as->setAttribute(OSKEY_MAX_ADDRESS, maxAddress_);
    if (!shared_) {
        as->setAttribute(OSKEY_SHARED_MEMORY, shared_);
    }
    for (IDSet::const_iterator i = numericalIds_.begin();
         i != numericalIds_.end(); ++i) {
        ObjectState* child = new ObjectState(OSKEY_NUMERICAL_ID, as);
        child->setValue((int)(*i));
    }
    return as;
}
References maxAddress_, minAddress_, TTAMachine::Component::name(), numericalIds_, OSKEY_MAX_ADDRESS, OSKEY_MIN_ADDRESS, TTAMachine::Component::OSKEY_NAME, OSKEY_NUMERICAL_ID, OSKEY_SHARED_MEMORY, OSKEY_WIDTH, OSNAME_ADDRESS_SPACE, ObjectState::setAttribute(), ObjectState::setValue(), shared_, and width_.
Referenced by ADFCombiner::addAddressSpaces().
setAddressBounds()
void TTAMachine::AddressSpace::setAddressBounds (ULongWord start, ULongWord end) virtual
Sets the memory address bounds of the address space.
Parameters
start The lowest memory address.
end The highest memory address.
Exceptions
OutOfRange If the given start and end addresses are illegal.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 232 of file AddressSpace.cc.
{
    if (start >= end) {
        string procName = "AddressSpace::setAddressBounds";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    minAddress_ = start;
    maxAddress_ = end;
}
References end(), maxAddress_, minAddress_, and start().
Referenced by loadState(), and AddressSpaceDialog::onOK().
setMachine()
void TTAMachine::AddressSpace::setMachine (TTAMachine::Machine & mach) virtual
Registers the address space to a machine. Do not use this method.
Parameters
mach Machine to which the address space is going to be registered.
Exceptions
ComponentAlreadyExists If there is another address space by the same name in the given machine.
Implements TTAMachine::Component.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 250 of file AddressSpace.cc.
{
    assert(!isRegistered());
    mach.addAddressSpace(*this);
    internalSetMachine(mach);
}
References TTAMachine::Machine::addAddressSpace(), assert, TTAMachine::Component::internalSetMachine(), and TTAMachine::Component::isRegistered().
Referenced by AddressSpace(), and AddressSpace().
setName()
void TTAMachine::AddressSpace::setName (const std::string & name) virtual
Sets the name of the address space.
Parameters
name Name of the address space.
Exceptions
ComponentAlreadyExists If an address space with the given name is already in the same machine.
InvalidName If the given name is not valid for a component.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 191 of file AddressSpace.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->addressSpaceNavigator().hasItem(name)) {
            string procName = "AddressSpace::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by AddressSpaceDialog::onOK().
setNumericalIds()
bool TTAMachine::AddressSpace::setNumericalIds (const std::set< unsigned > & ids)
Sets the ids for the address space.
Parameters
ids Contains new ids for the address space.
Returns
True if setting the new address space ids was successful.
Definition at line 404 of file AddressSpace.cc.
{
    assert (machine() != NULL);
    Machine::AddressSpaceNavigator asNavigator =
        machine()->addressSpaceNavigator();
    // loop through all other address spaces and check if input parameter
    // violates any existing ids
    for (int i = 0; i < asNavigator.count(); i++) {
        AddressSpace* as = asNavigator.item(i);
        if (as != this) {
            IDSet otherIds = as->numericalIds();
            for (IDSet::iterator id = ids.begin(); id != ids.end(); ++id) {
                if (AssocTools::containsKey(otherIds, *id)) {
                    return false;
                }
            }
        }
    }
    // no violating ids found, overwrite ids for this address space
    numericalIds_ = ids;
    return true;
}
References TTAMachine::Machine::addressSpaceNavigator(), assert, AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), numericalIds(), and numericalIds_.
Referenced by AddressSpaceDialog::onOK().
setShared()
virtual void TTAMachine::AddressSpace::setShared (bool shared) inline virtual
Definition at line 71 of file AddressSpace.hh.
{ shared_ = shared; }
References shared_.
Referenced by loadState().
setWidth()
void TTAMachine::AddressSpace::setWidth (int width) virtual
Sets the bit width of the minimum addressable word.
Parameters
width The bit width of the minimum addressable word.
Exceptions
OutOfRange If the given width is illegal (<=0).
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 215 of file AddressSpace.cc.
{
    if (width <= 0) {
        string procName = "AddressSpace::setWidth";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    width_ = width;
}
References width(), and width_.
Referenced by loadState(), AddressSpaceDialog::onOK(), and CodeCompressorPlugin::setImemWidth().
start()
ULongWord TTAMachine::AddressSpace::start () const virtual
Returns the lowest memory address of the address space.
Returns
The lowest memory address of the address space.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 166 of file AddressSpace.cc.
{
    return minAddress_;
}
References minAddress_.
Referenced by ProGe::NetlistGenerator::calculateAddressWidth(), TTAProgram::ProgramWriter::createBinary(), llvm::LLVMTCEBuilder::dataEnd(), InfoProcCommand::execute(), SimulatorFrontend::initializeDataMemories(), SimulatorFrontend::initializeMemorySystem(), ProximMemoryWindow::loadMemory(), AddWatchDialog::onASChoice(), printLatexAddressSpaceDescription(), setAddressBounds(), CodeCompressorPlugin::setMachine(), AddressSpaceDialog::TransferDataToWindow(), and AddressSpacesDialog::updateASList().
unsetMachine()
void TTAMachine::AddressSpace::unsetMachine () virtual
Removes registration of the address space from its current machine. The address space is deleted too because it cannot be unregistered.
Implements TTAMachine::Component.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 261 of file AddressSpace.cc.
{
    assert(isRegistered());
    Machine* mach = machine();
    // remove dangling pointers in function units
    Machine::FunctionUnitNavigator fuNav = mach->functionUnitNavigator();
    int units = fuNav.count();
    for (int i = 0; i < units; i++) {
        FunctionUnit* fu = fuNav.item(i);
        if (fu->addressSpace() == this) {
            fu->setAddressSpace(NULL);
        }
    }
    // remove dangling pointer in GCU
    ControlUnit* cu = mach->controlUnit();
    if (cu != NULL) {
        if (cu->addressSpace() == this) {
            cu->setAddressSpace(NULL);
        }
    }
    internalUnsetMachine();
    mach->deleteAddressSpace(*this);
}
References TTAMachine::FunctionUnit::addressSpace(), assert, TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::deleteAddressSpace(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Component::internalUnsetMachine(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), and TTAMachine::FunctionUnit::setAddressSpace().
Referenced by ~AddressSpace().
width()
int TTAMachine::AddressSpace::width () const virtual
Returns the bit width of the minimum addressable word.
Returns
The bit width of the minimum addressable word.
Reimplemented in TTAMachine::NullAddressSpace.
Definition at line 155 of file AddressSpace.cc.
{
    return width_;
}
References width_.
Referenced by AddressSpace(), BEMValidator::checkImemMauWidth(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::DataDefinition::DataDefinition(), TTAProgram::DataDefinition::DataDefinition(), InfoProcCommand::execute(), MemDumpCommand::execute(), MachineResourceManager::findDataAddressSpace(), ProgramImageGenerator::generateDataImage(), CompiledSimCodeGenerator::generateLoadTrigger(), ProgramImageGenerator::generateProgramImage(), ProGe::ProcessorGenerator::iMemWidth(), SimulatorFrontend::initializeMemorySystem(), ProGe::NetlistGenerator::instructionMemoryWidth(), ProximMemoryWindow::loadMemory(), TTAProgram::DataDefinition::MAU(), printLatexAddressSpaceDescription(), PlatformIntegrator::readLsuParameters(), CodeCompressorPlugin::setMachine(), setWidth(), AddressSpaceDialog::TransferDataToWindow(), and AddressSpacesDialog::updateASList().
Member Data Documentation
maxAddress_
ULongWord TTAMachine::AddressSpace::maxAddress_ private
Highest address in the address space.
Definition at line 101 of file AddressSpace.hh.
Referenced by AddressSpace(), end(), operator==(), saveState(), and setAddressBounds().
minAddress_
ULongWord TTAMachine::AddressSpace::minAddress_ private
Lowest address in the address space.
Definition at line 99 of file AddressSpace.hh.
Referenced by AddressSpace(), operator==(), saveState(), setAddressBounds(), and start().
numericalIds_
IDSet TTAMachine::AddressSpace::numericalIds_ private
The numerical ids mapped to this address space.
Definition at line 103 of file AddressSpace.hh.
Referenced by addNumericalId(), AddressSpace(), hasNumericalId(), numericalIds(), operator==(), saveState(), and setNumericalIds().
OSKEY_MAX_ADDRESS
const string TTAMachine::AddressSpace::OSKEY_MAX_ADDRESS = "max_a" static
ObjectState attribute key for maximum address.
Definition at line 90 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), loadState(), and saveState().
OSKEY_MIN_ADDRESS
const string TTAMachine::AddressSpace::OSKEY_MIN_ADDRESS = "min_a" static
ObjectState attribute key for minimum address.
Definition at line 88 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), loadState(), and saveState().
OSKEY_NUMERICAL_ID
const string TTAMachine::AddressSpace::OSKEY_NUMERICAL_ID = "numerical-id" static
Definition at line 92 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), loadState(), and saveState().
OSKEY_SHARED_MEMORY
const string TTAMachine::AddressSpace::OSKEY_SHARED_MEMORY = "shared-memory" static
Definition at line 91 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), loadState(), and saveState().
OSKEY_WIDTH
const string TTAMachine::AddressSpace::OSKEY_WIDTH = "width" static
ObjectState attribute key for the bit width.
Definition at line 86 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), loadState(), and saveState().
OSNAME_ADDRESS_SPACE
const string TTAMachine::AddressSpace::OSNAME_ADDRESS_SPACE = "adress_space" static
ObjectState name for AddressSpace.
Definition at line 84 of file AddressSpace.hh.
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::convertToMDFFormat(), loadState(), TTAMachine::Machine::loadState(), and saveState().
shared_
bool TTAMachine::AddressSpace::shared_ private
True in case this address space maps to a memory that is shared across all the cores in the multicore.
Definition at line 106 of file AddressSpace.hh.
Referenced by isShared(), operator==(), saveState(), and setShared().
width_
int TTAMachine::AddressSpace::width_ private
Bit width of the minimum addressable word.
Definition at line 97 of file AddressSpace.hh.
Referenced by AddressSpace(), operator==(), saveState(), setWidth(), and width().
The documentation for this class was generated from the following files:
AddressSpace.hh
AddressSpace.cc