OpenASIP: TTAMachine::Connection Class Reference
TTAMachine::Connection Class Reference
#include <Connection.hh>
Public Member Functions
Connection (Socket &socket, Segment &bus)
~Connection ()
Segment * bus () const
Socket * socket () const
ObjectState * saveState () const
Static Public Attributes
static const std::string OSNAME_CONNECTION = "connection"
ObjectState name for Connection.
static const std::string OSKEY_SOCKET = "socket"
ObjectState attribute key for socket name.
static const std::string OSKEY_BUS = "bus"
ObjectState attribute key for bus name.
static const std::string OSKEY_SEGMENT = "segment"
ObjectState attribute key for segment name.
Private Attributes
Socket * socket_
Socket which is connected to the bus.
Segment * bus_
Bus which is connected to the socket.
Detailed Description
Joins Bus and Socket objects if they are connected in the machine.
Definition at line 48 of file Connection.hh.
Constructor & Destructor Documentation
Connection()
TTAMachine::Connection::Connection (Socket & socket, Segment & bus)
Constructor.
Parameters
socket Socket which is connected to the given segment.
bus Segment of a bus which is connected to the socket.
Definition at line 58 of file Connection.cc.
                                                   :
    socket_(&socket), bus_(&bus) {
}
~Connection()
TTAMachine::Connection::~Connection ()
Destructor.
If Connection object still joins a socket and a segment, they are detached before destructing the Connection object.
Definition at line 68 of file Connection.cc.
{
    if (socket_->isConnectedTo(*bus_)) {
        assert(bus_->isConnectedTo(*socket_)); // sanity check
        socket_->detachBus(*bus_); // or bus_->detachSocket(socket_)
    } else {
        // this is for when destructor is called by a detach methods
        assert(!bus_->isConnectedTo(*socket_));
    }
}
References assert, bus_, TTAMachine::Socket::detachBus(), TTAMachine::Socket::isConnectedTo(), TTAMachine::Segment::isConnectedTo(), and socket_.
Member Function Documentation
bus()
Segment * TTAMachine::Connection::bus () const
Referenced by ConnectionSweeper::removeConnection(), and saveState().
saveState()
ObjectState * TTAMachine::Connection::saveState () const
Saves its state to an ObjectState instance.
Returns
The newly created ObjectState instance.
Definition at line 85 of file Connection.cc.
{
    ObjectState* state = new ObjectState(OSNAME_CONNECTION);
    state->setAttribute(OSKEY_SOCKET, socket()->name());
    state->setAttribute(OSKEY_BUS, bus()->parentBus()->name());
    state->setAttribute(OSKEY_SEGMENT, bus()->name());
    return state;
}
References bus(), OSKEY_BUS, OSKEY_SEGMENT, OSKEY_SOCKET, OSNAME_CONNECTION, ObjectState::setAttribute(), and socket().
Referenced by TTAMachine::Socket::saveState().
socket()
Socket * TTAMachine::Connection::socket () const
Referenced by ConnectionSweeper::removeConnection(), saveState(), ConnectionSweeper::sweepBypasses(), and ConnectionSweeper::sweepRFs().
Member Data Documentation
bus_
Segment* TTAMachine::Connection::bus_ private
Bus which is connected to the socket.
Definition at line 70 of file Connection.hh.
Referenced by ~Connection().
OSKEY_BUS
const string TTAMachine::Connection::OSKEY_BUS = "bus" static
ObjectState attribute key for bus name.
Definition at line 62 of file Connection.hh.
Referenced by TTAMachine::Socket::loadState(), saveState(), ADFSerializer::socketToMachine(), and ADFSerializer::socketToMDF().
OSKEY_SEGMENT
const string TTAMachine::Connection::OSKEY_SEGMENT = "segment" static
ObjectState attribute key for segment name.
Definition at line 64 of file Connection.hh.
Referenced by TTAMachine::Socket::loadState(), saveState(), ADFSerializer::socketToMachine(), and ADFSerializer::socketToMDF().
OSKEY_SOCKET
const string TTAMachine::Connection::OSKEY_SOCKET = "socket" static
ObjectState attribute key for socket name.
Definition at line 60 of file Connection.hh.
Referenced by saveState(), and ADFSerializer::socketToMachine().
OSNAME_CONNECTION
const string TTAMachine::Connection::OSNAME_CONNECTION = "connection" static
ObjectState name for Connection.
Definition at line 58 of file Connection.hh.
Referenced by TTAMachine::Socket::loadState(), saveState(), and ADFSerializer::socketToMachine().
socket_
Socket* TTAMachine::Connection::socket_ private
Socket which is connected to the bus.
Definition at line 68 of file Connection.hh.
Referenced by ~Connection().
The documentation for this class was generated from the following files:
Connection.hh
Connection.cc