OpenASIP: TPEF::TPEFRelocSectionReader Class Reference
TPEF::TPEFRelocSectionReader Class Reference
#include <TPEFRelocSectionReader.hh>
Protected Member Functions
TPEFRelocSectionReader ()
virtual ~TPEFRelocSectionReader ()
virtual void finalize (Section *section) const
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
Private Member Functions
TPEFRelocSectionReader (const TPEFRelocSectionReader &)
Copying not allowed.
TPEFRelocSectionReader & operator= (TPEFRelocSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFRelocSectionReader proto_
Prototype instance of TPEFRelocSectionReader to be registered to SectionReader.
static SectionId refSectionId_ = 0
Section id of last referenced section.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads relocation section from TPEF binary file.
Definition at line 47 of file TPEFRelocSectionReader.hh.
Constructor & Destructor Documentation
TPEFRelocSectionReader() [1/2]
TPEF::TPEFRelocSectionReader::TPEFRelocSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 77 of file TPEFRelocSectionReader.cc.
                                               : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFRelocSectionReader()
TPEF::TPEFRelocSectionReader::~TPEFRelocSectionReader () protected virtual
Destructor.
Definition at line 84 of file TPEFRelocSectionReader.cc.
{
}
TPEFRelocSectionReader() [2/2]
TPEF::TPEFRelocSectionReader::TPEFRelocSectionReader (const TPEFRelocSectionReader &) private
Copying not allowed.
Member Function Documentation
finalize()
void TPEF::TPEFRelocSectionReader::finalize (Section * section) const protected virtual
Finalizer method for TPEF relocation sections.
Resolves destination fields of relocation elements.
Parameters
section Section to finalize.
Reimplemented from TPEF::SectionReader.
Definition at line 182 of file TPEFRelocSectionReader.cc.
{
    Section *refSection =
        dynamic_cast<RelocSection*>(section)->referencedSection();
    TPEFReader* tpefReader = dynamic_cast<TPEFReader*>(parent());
    for (Word i = 0; i < section->elementCount(); i++) {
        RelocElement *elem =
            dynamic_cast<RelocElement*>(section->element(i));
        assert(elem->location() != NULL);
        // file offset of destination element to find
        AddressImage address = 0;
        // should we dig up code or data section
        if (refSection->isCodeSection()) {
            // value of immediate element, is an address to that element,
            // which to immediate refers
            ImmediateElement *imm =
                dynamic_cast<ImmediateElement*>(elem->location());
            // relocation must have Immediate or Chunk element as location
            assert(imm != NULL);
            assert(imm->length() <= sizeof(address));
            // read destination address of relocation
            unsigned int neededBits = MathTools::requiredBits(imm->word());
            if (neededBits > elem->size()) {
                throw OutOfRange(
                    __FILE__, __LINE__, __func__,
                    (boost::format(
                        "Destination address width %d of relocation is "
                        "bigger than the field size %d.")
                     % neededBits % elem->size()).str());
            }
            address = imm->word();
        } else if (refSection->type() == Section::ST_DATA) {
            try {
                DataSection *dataSect =
                    dynamic_cast<DataSection*>(refSection);
                int startIndex =
                    dataSect->chunkToMAUIndex(
                        dynamic_cast<Chunk*>(elem->location()));
                int mauSize = dataSect->aSpace()->MAU();
                // BE
                for (int i = 0; i < elem->size() / mauSize; i++) {
                    address = address << mauSize;
                    address = address |  dataSect->MAU(startIndex+i);
                }
            } catch (const OutOfRange &e) {
                bool requestedChunkWasOutOfRange = false;
                assert(requestedChunkWasOutOfRange);
            }
        } else if (refSection->type() == Section::ST_LEDATA) {
            try {
                LEDataSection *dataSect =
                    dynamic_cast<LEDataSection*>(refSection);
                int startIndex =
                    dataSect->chunkToMAUIndex(
                        dynamic_cast<Chunk*>(elem->location()));
                int mauSize = dataSect->aSpace()->MAU();
                // LE
                for (int i = 0; i < elem->size() / mauSize; i++) {
                    address |= (dataSect->MAU(startIndex+i) << (mauSize*i));
                }
            } catch (const OutOfRange &e) {
                bool requestedChunkWasOutOfRange = false;
                assert(requestedChunkWasOutOfRange);
            }
        } else {
            bool referencedSectionMustBeEitherCodeOrData = false;
            assert(referencedSectionMustBeEitherCodeOrData);
        }
        // if unresolved relocation leave destination to undefined
        if (tpefReader->aSpaceSection()->isUndefined(elem->aSpace())) {
            continue;
        }
        // absolute address depending on relocation type and value
        AddressImage absoluteAddress =
            Locator::absoluteAddress(address, elem->type());
        // here we need to resolve section of section referenced
        // by value of location
        Section *destSection =
            tpefReader->sectionOfAddress(elem->aSpace(), absoluteAddress);
        assert(destSection != NULL);
        // do the magic!
        // find section identification code
        SectionId destSectionId =
            SafePointer::sectionKeyFor(destSection).sectionId();
        SectionOffset sectOffsetOfElement;
         // if code section check instructionsize and encoding from
        // refSection...
        if (destSection->isCodeSection()) {
            CodeSection *codeSection =
                dynamic_cast<CodeSection*>(destSection);
            // find instruction number of absolute address
            Word instructionNumber =
                absoluteAddress - codeSection->startingAddress();
            // every index is stored for every instruction element that is
            // start of instruction
            SectionIndexKey sectIndexKey(destSectionId, instructionNumber);
            elem->setDestination(CREATE_SAFEPOINTER(sectIndexKey));
        } else {
            Word mauInBytes =
                static_cast<Word>(
                    ceil(static_cast<double>(elem->aSpace()->MAU()) /
                         static_cast<double>(BYTE_BITWIDTH)));
            // else find just section offset
            sectOffsetOfElement =
                (absoluteAddress - destSection->startingAddress()) *
                mauInBytes;
            SectionOffsetKey sectOffKey(destSectionId, sectOffsetOfElement);
            elem->setDestination(CREATE_SAFEPOINTER(sectOffKey));
        }
    }
}
References __func__, TPEF::Locator::absoluteAddress(), TPEF::RelocElement::aSpace(), TPEF::Section::aSpace(), TPEF::TPEFReader::aSpaceSection(), assert, BYTE_BITWIDTH, TPEF::RawSection::chunkToMAUIndex(), TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::Section::isCodeSection(), TPEF::ASpaceSection::isUndefined(), TPEF::ImmediateElement::length(), TPEF::RelocElement::location(), TPEF::ASpaceElement::MAU(), TPEF::DataSection::MAU(), TPEF::TPEFSectionReader::parent(), MathTools::requiredBits(), TPEF::ReferenceManager::SectionKey::sectionId(), TPEF::ReferenceManager::SafePointer::sectionKeyFor(), TPEF::TPEFReader::sectionOfAddress(), TPEF::RelocElement::setDestination(), TPEF::RelocElement::size(), TPEF::Section::ST_DATA, TPEF::Section::ST_LEDATA, TPEF::Section::startingAddress(), TPEF::RelocElement::type(), TPEF::Section::type(), and TPEF::ImmediateElement::word().
operator=()
TPEFRelocSectionReader & TPEF::TPEFRelocSectionReader::operator= (TPEFRelocSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFRelocSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue Ift here was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 110 of file TPEFRelocSectionReader.cc.
{
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    RelocSection* relocSection = dynamic_cast<RelocSection*>(section);
    assert(relocSection != NULL);
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // store start of first element
        SectionOffset elementStart = header().bodyOffset;
        SectionIndex id = 0;
        while (elementStart + header().elementSize <=
               header().bodyOffset + header().bodyLength) {
            RelocElement *elem = new RelocElement();
            SectionIndexKey sectionIndexKey(header().sectionId, id);
            SafePointer::addObjectReference(sectionIndexKey, elem);
            // r_offset is source element section offset
            Word rOffset =  stream.readWord();
            SectionOffsetKey sKey(refSectionId_, rOffset);
            elem->setLocation(CREATE_SAFEPOINTER(sKey));
            // r_symbol
            Word rSymbol = stream.readWord();
            SectionIndexKey indexKey(header().linkId, rSymbol);
            elem->setSymbol(CREATE_SAFEPOINTER(indexKey));
            // r_type
            Byte rType = stream.readByte();
            elem->setType(
                static_cast<RelocElement::RelocType>(
                    rType&TPEFHeaders::STF_RELOCATION_TYPE_MASK));
            elem->setChunked(rType & TPEFHeaders::STF_CHUNK);
            // r_asp
            Byte rASP = stream.readByte();
            SectionIndexKey aSpaceIndexKey(
                dynamic_cast<TPEFReader*>(parent())->aSpaceId(), rASP);
            elem->setASpace(CREATE_SAFEPOINTER(aSpaceIndexKey));
            // r_size
            elem->setSize(stream.readByte());
            // r_bitpos skipped for now
            elem->setBitOffset(stream.readByte());
            section->addElement(elem);
            elementStart += header().elementSize;
            stream.setReadPosition(elementStart);
            id++;
        }
    }
}
References TPEF::Section::addElement(), TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::TPEFSectionReader::Header::bodyOffset, TPEF::TPEFSectionReader::Header::elementSize, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::TPEFSectionReader::parent(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readWord(), refSectionId_, TPEF::RelocElement::setASpace(), TPEF::RelocElement::setBitOffset(), TPEF::RelocElement::setChunked(), TPEF::RelocElement::setLocation(), TPEF::BinaryStream::setReadPosition(), TPEF::RelocElement::setSize(), TPEF::RelocElement::setSymbol(), TPEF::RelocElement::setType(), TPEF::TPEFHeaders::STF_CHUNK, and TPEF::TPEFHeaders::STF_RELOCATION_TYPE_MASK.
readInfo()
void TPEF::TPEFRelocSectionReader::readInfo (BinaryStream & stream, Section * sect) const protected virtual
Reads info field of section header.
Read position of stream will be moved 4 bytes forward.
Parameters
stream Stream where from info word is read.
section Reloc section whose info field is read.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 343 of file TPEFRelocSectionReader.cc.
{
    // referenced section identifier is in first 2 bytes of info field
    refSectionId_ = stream.readHalfWord();
    if (refSectionId_ != 0) {
        SectionKey sKey(refSectionId_);
        dynamic_cast<RelocSection*>(sect)->setReferencedSection(
            CREATE_SAFEPOINTER(sKey));
    } else {
        bool referencedSectionOfRelocationMustNotBeNullSection = false;
        assert(referencedSectionOfRelocationMustNotBeNullSection);
    }
    // skip rest 2 of 4 bytes
    stream.readHalfWord();
}
References assert, TPEF::BinaryStream::readHalfWord(), and refSectionId_.
type()
Section::SectionType TPEF::TPEFRelocSectionReader::type () const protected virtual
Returns the type of section which the reader can read.
Returns
The type of section which reader can read.
Implements TPEF::SectionReader.
Definition at line 93 of file TPEFRelocSectionReader.cc.
{
    return Section::ST_RELOC;
}
References TPEF::Section::ST_RELOC.
Member Data Documentation
proto_
TPEFRelocSectionReader TPEF::TPEFRelocSectionReader::proto_ static private
Prototype instance of TPEFRelocSectionReader to be registered to SectionReader.
Definition at line 68 of file TPEFRelocSectionReader.hh.
refSectionId_
SectionId TPEF::TPEFRelocSectionReader::refSectionId_ = 0 static private
Section id of last referenced section.
Definition at line 71 of file TPEFRelocSectionReader.hh.
Referenced by readData(), and readInfo().
The documentation for this class was generated from the following files:
TPEFRelocSectionReader.hh
TPEFRelocSectionReader.cc