OpenASIP: NullDataObject Class Reference
NullDataObject Class Reference
#include <DataObject.hh>
Public Member Functions
virtual int integerValue () const override
virtual SLongWord longValue () const override
virtual void setInteger (int value) override
virtual void setLong (SLongWord value) override
virtual std::string stringValue () const
virtual void setString (std::string value) override
virtual double doubleValue () const
virtual void setDouble (double value) override
virtual float floatValue () const
virtual void setFloat (float value) override
virtual bool isNull () const
virtual void setNull () override
Public Member Functions inherited from DataObject
DataObject ()
DataObject (int value)
DataObject (SLongWord value)
DataObject (double value)
DataObject (const std::string value)
virtual ~DataObject ()
virtual bool boolValue () const
virtual void setBool (bool value)
virtual bool operator!= (const DataObject &object) const
Static Public Member Functions
static NullDataObject & instance ()
Private Member Functions
NullDataObject ()
virtual ~NullDataObject ()
NullDataObject (const DataObject &obj)
Static Private Attributes
static NullDataObject * instance_ = NULL
Additional Inherited Members
Public Types inherited from DataObject
enum OrigType {
TYPE_INT , TYPE_STRING , TYPE_DOUBLE , TYPE_FLOAT ,
TYPE_NULL , TYPE_NOTYPE
}
Protected Member Functions inherited from DataObject
OrigType type () const
bool intFresh () const
bool stringFresh () const
bool doubleFresh () const
bool floatFresh () const
Detailed Description
Singleton class that represents a null DataObject.
All methods write to error log and abort the program.
Definition at line 128 of file DataObject.hh.
Constructor & Destructor Documentation
NullDataObject() [1/2]
NullDataObject::NullDataObject () private
Constructor.
Definition at line 526 of file DataObject.cc.
{
}
Referenced by instance().
~NullDataObject()
NullDataObject::~NullDataObject () private virtual
Destructor.
Definition at line 532 of file DataObject.cc.
{
}
NullDataObject() [2/2]
NullDataObject::NullDataObject (const DataObject & obj) private
Member Function Documentation
doubleValue()
double NullDataObject::doubleValue () const virtual
Returns the double value of DataObject.
If double value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to 0.0.
Returns
The double value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented from DataObject.
Definition at line 603 of file DataObject.cc.
{
    abortWithError("doubleValue()");
    return 0.0;
}
References abortWithError.
floatValue()
float NullDataObject::floatValue () const virtual
Returns the float value of DataObject.
If float value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to 0.0.
Returns
The float value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented from DataObject.
Definition at line 609 of file DataObject.cc.
{
    abortWithError("floatValue()");
    return 0.0;
}
References abortWithError.
instance()
NullDataObject & NullDataObject::instance () static
Returns an instance of NullDataObject (singleton)
Returns
NullDataObject singleton instance.
Definition at line 542 of file DataObject.cc.
{
    if (instance_ == NULL) {
        instance_ = new NullDataObject();
    }
    return *instance_;
}
References instance_, and NullDataObject().
Referenced by InstructionExecution::address(), InstructionExecution::cycle(), RelationalDBQueryResult::data(), RelationalDBQueryResult::data(), and SQLiteQueryResult::data().
integerValue()
int NullDataObject::integerValue () const override virtual
Returns the integer value of DataObject.
If integer value is not available, the conversion is done from the original value type. Note that a NULL DataObject is converted to 0.
Returns
The integer value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented from DataObject.
Definition at line 585 of file DataObject.cc.
{
    abortWithError("integerValue()");
    return 0;
}
References abortWithError.
isNull()
bool NullDataObject::isNull () const virtual
Returns true in case the object represents a NULL value.
Returns
True in case the object's value is NULL.
Reimplemented from DataObject.
Definition at line 615 of file DataObject.cc.
{
    abortWithError("isNull()");
    return false;
}
References abortWithError.
longValue()
SLongWord NullDataObject::longValue () const override virtual
Returns the (long) integer value of DataObject.
If integer value is not available, the conversion is done from the original value type. Note that a NULL DataObject is converted to 0.
Returns
The integer value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented from DataObject.
Definition at line 591 of file DataObject.cc.
{
    abortWithError("longValue()");
    return 0;
}
References abortWithError.
setDouble()
void NullDataObject::setDouble (double value) override virtual
Sets the double value of DataObject.
Parameters
value The double value of DataObject.
Reimplemented from DataObject.
Definition at line 570 of file DataObject.cc.
{
    abortWithError("setDouble()");
}
References abortWithError.
setFloat()
void NullDataObject::setFloat (float value) override virtual
Sets the float value of DataObject.
Parameters
value The float value of DataObject.
Reimplemented from DataObject.
Definition at line 575 of file DataObject.cc.
{
    abortWithError("setFloat()");
}
References abortWithError.
setInteger()
void NullDataObject::setInteger (int value) override virtual
All method implementations of NullDataObject write a message to error log and abort the program.
Reimplemented from DataObject.
Definition at line 555 of file DataObject.cc.
{
    abortWithError("setInteger()");
}
References abortWithError.
setLong()
void NullDataObject::setLong (SLongWord value) override virtual
Sets the integer value of DataObject.
Parameters
value The integer value.
Reimplemented from DataObject.
Definition at line 560 of file DataObject.cc.
{
    abortWithError("setLong()");
}
References abortWithError.
setNull()
void NullDataObject::setNull () override virtual
Sets the DataObject to null.
Reimplemented from DataObject.
Definition at line 580 of file DataObject.cc.
{
    abortWithError("setNull()");
}
References abortWithError.
setString()
void NullDataObject::setString (std::string value) override virtual
Sets the string value of DataObject.
Parameters
value The string value.
Reimplemented from DataObject.
Definition at line 565 of file DataObject.cc.
{
    abortWithError("setString()");
}
References abortWithError.
stringValue()
string NullDataObject::stringValue () const virtual
Returns the string value of DataObject.
If string value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to an empty string.
Returns
The string value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented from DataObject.
Definition at line 597 of file DataObject.cc.
{
    abortWithError("stringValue()");
    return "";
}
References abortWithError.
Member Data Documentation
instance_
NullDataObject * NullDataObject::instance_ = NULL static private
Definition at line 156 of file DataObject.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
DataObject.hh
DataObject.cc