OpenASIP: TTAProgram::TerminalLaneIDImmediate Class Reference
TTAProgram::TerminalLaneIDImmediate Class Reference
#include <TerminalLaneIDImmediate.hh>
Public Member Functions
TerminalLaneIDImmediate (SimValue value)
virtual ~TerminalLaneIDImmediate ()
virtual SimValue value () const
virtual Terminal * copy () const
virtual bool equals (const Terminal &other) const
virtual TCEString toString () const
Public Member Functions inherited from TTAProgram::TerminalImmediate
TerminalImmediate (SimValue value)
virtual ~TerminalImmediate ()
virtual bool isImmediate () const
Public Member Functions inherited from TTAProgram::Terminal
Terminal ()
virtual ~Terminal ()
virtual bool isAddress () const
virtual bool isInstructionAddress () const
virtual bool isImmediateRegister () const
virtual bool isGPR () const
virtual bool isFUPort () const
virtual bool isRA () const
virtual bool isBasicBlockReference () const
virtual bool isProgramOperationReference () const
virtual bool isCodeSymbolReference () const
virtual bool isUniversalMachineRegister () const
virtual Address address () const
virtual const InstructionReference & instructionReference () const
virtual InstructionReference & instructionReference ()
virtual const TTAMachine::RegisterFile & registerFile () const
virtual const TTAMachine::ImmediateUnit & immediateUnit () const
virtual const TTAMachine::FunctionUnit & functionUnit () const
virtual const BasicBlock & basicBlock () const
virtual int index () const
virtual bool isOpcodeSetting () const
virtual bool isTriggering () const
virtual Operation & operation () const
virtual Operation & hintOperation () const
virtual int operationIndex () const
virtual const TTAMachine::Port & port () const
virtual void setIndex (int index)
virtual void setInstructionReference (InstructionReference ref)
bool operator== (const Terminal &other) const
Public Member Functions inherited from TTAProgram::AnnotatedInstructionElement
AnnotatedInstructionElement ()
~AnnotatedInstructionElement ()
void addAnnotation (const ProgramAnnotation &annotation)
void setAnnotation (const ProgramAnnotation &annotation)
ProgramAnnotation annotation (int index, ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
int annotationCount (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
void removeAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID)
bool hasAnnotations (ProgramAnnotation::Id id=ProgramAnnotation::ANN_UNDEF_ID) const
bool hasAnnotation (ProgramAnnotation::Id id, const TCEString &data) const
void copyAnnotationsFrom (const AnnotatedInstructionElement &other)
Protected Attributes
SimValue value_
Value of the inline immediate.
Protected Attributes inherited from TTAProgram::TerminalImmediate
SimValue value_
Value of the inline immediate.
Private Member Functions
TerminalLaneIDImmediate & operator= (const TerminalLaneIDImmediate &)
Assignment not allowed.
Detailed Description
Represents a special inline immediate that is fixed to the lane id of the scheduled move in a clustered/SMMT machine.
Definition at line 45 of file TerminalLaneIDImmediate.hh.
Constructor & Destructor Documentation
TerminalLaneIDImmediate()
TTAProgram::TerminalLaneIDImmediate::TerminalLaneIDImmediate (SimValue lane)
The constructor.
Parameters
value The value of the inline immediate.
Definition at line 46 of file TerminalLaneIDImmediate.cc.
                                                              :
    TerminalImmediate(lane) {
}
~TerminalLaneIDImmediate()
TTAProgram::TerminalLaneIDImmediate::~TerminalLaneIDImmediate () virtual
The destructor.
Definition at line 53 of file TerminalLaneIDImmediate.cc.
{
}
Member Function Documentation
copy()
Terminal * TTAProgram::TerminalLaneIDImmediate::copy () const virtual
Creates an exact copy of the terminal and returns it.
Returns
A copy of the terminal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 73 of file TerminalLaneIDImmediate.cc.
{
    return new TerminalLaneIDImmediate(value_);
}
References value_.
equals()
bool TTAProgram::TerminalLaneIDImmediate::equals (const Terminal & other) const virtual
Checks if terminals are equal.
Parameters
other Terminal to compare.
Returns
true if terminals are equal.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 84 of file TerminalLaneIDImmediate.cc.
{
    if (dynamic_cast<const TerminalLaneIDImmediate*>(&other) ==
        NULL) {
        return false;
    }
    return value() == other.value();
}
References TTAProgram::Terminal::value(), and value().
operator=()
TerminalLaneIDImmediate & TTAProgram::TerminalLaneIDImmediate::operator= (const TerminalLaneIDImmediate &) private
Assignment not allowed.
toString()
TCEString TTAProgram::TerminalLaneIDImmediate::toString () const virtual
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 94 of file TerminalLaneIDImmediate.cc.
{
    DisassemblyImmediate* disasm =
        POMDisassembler::createInlineImmediate(*this, false);
    TCEString dis = disasm->toString();
    delete disasm;
    return dis;
}
References POMDisassembler::createInlineImmediate(), and DisassemblyImmediate::toString().
value()
SimValue TTAProgram::TerminalLaneIDImmediate::value () const virtual
Returns the value of the inline immediate.
Returns
The value of the inline immediate.
Exceptions
WrongSubclass never.
Reimplemented from TTAProgram::TerminalImmediate.
Definition at line 63 of file TerminalLaneIDImmediate.cc.
{
    return value_;
}
References value_.
Referenced by equals().
Member Data Documentation
value_
SimValue TTAProgram::TerminalLaneIDImmediate::value_ protected
Value of the inline immediate.
Definition at line 63 of file TerminalLaneIDImmediate.hh.
Referenced by copy(), and value().
The documentation for this class was generated from the following files:
TerminalLaneIDImmediate.hh
TerminalLaneIDImmediate.cc