OpenASIP: CostDatabaseRegistry Class Reference
CostDatabaseRegistry Class Reference
#include <CostDatabaseRegistry.hh>
Public Member Functions
virtual ~CostDatabaseRegistry ()
CostDatabase & costDatabase (const HDB::HDBManager &hdb)
void addCostDatabase (CostDatabase *costDatabase, const HDB::HDBManager &hdb)
bool hasCostDatabase (const HDB::HDBManager &hdb)
int costDatabaseCount ()
CostDatabase & costDatabase (unsigned int index)
std::string hdbPath (unsigned int index)
Static Public Member Functions
static CostDatabaseRegistry & instance ()
Private Member Functions
CostDatabaseRegistry ()
CostDatabase registry must be created with instance() method.
Private Attributes
std::map< const HDB::HDBManager *, CostDatabase * > registry_
All created CostDatabasess are stored in this map.
Static Private Attributes
static CostDatabaseRegistry * instance_ = NULL
Unique instance of the class.
Detailed Description
Registry for multiple CostDatabases.
Definition at line 46 of file CostDatabaseRegistry.hh.
Constructor & Destructor Documentation
~CostDatabaseRegistry()
CostDatabaseRegistry::~CostDatabaseRegistry () virtual
Destructor.
Definition at line 49 of file CostDatabaseRegistry.cc.
{
    AssocTools::deleteAllValues(registry_);
    instance_ = NULL;
}
References AssocTools::deleteAllValues(), instance_, and registry_.
CostDatabaseRegistry()
CostDatabaseRegistry::CostDatabaseRegistry () private
CostDatabase registry must be created with instance() method.
Constructor.
Definition at line 43 of file CostDatabaseRegistry.cc.
{
}
Referenced by instance().
Member Function Documentation
addCostDatabase()
void CostDatabaseRegistry::addCostDatabase (CostDatabase * costDatabase, const HDB::HDBManager & hdb)
Adds CostDatabase and HDB used in the CostDatabase in to the registry.
Parameters
costDatabase The cost database to be added in to the registry.
hdb The HDB that is used to create the CostDatabase.
Definition at line 95 of file CostDatabaseRegistry.cc.
{
    if (AssocTools::containsKey(registry_, &hdb)) {
        delete costDatabase;
        costDatabase = NULL;
        return;
    }
    registry_[&hdb] = costDatabase;
}
References AssocTools::containsKey(), costDatabase(), and registry_.
Referenced by CostDatabase::instance().
costDatabase() [1/2]
CostDatabase & CostDatabaseRegistry::costDatabase (const HDB::HDBManager & hdb)
Returns CostDatabase that is build against the HDB at given path.
In case the CostDatabase is not found in registry, tries to generate it.
Parameters
hdbFileName File name of the HDB to build the CostDatabase against.
Returns
The CostDatabase build against the HDB file.
Exceptions
Exception In case there was a problem while creating the CostDatabase.
Definition at line 79 of file CostDatabaseRegistry.cc.
{
    if (AssocTools::containsKey(registry_, &hdb)) {
        return *registry_[&hdb];
    }
    CostDatabase* costDatabase = &CostDatabase::instance(hdb);
    registry_[&hdb] = costDatabase;
    return *costDatabase;
}
References AssocTools::containsKey(), costDatabase(), CostDatabase::instance(), and registry_.
Referenced by addCostDatabase(), costDatabase(), InterpolatingFUEstimator::initializeEstimator(), InterpolatingRFEstimator::initializeEstimator(), and CostDatabase::instance().
costDatabase() [2/2]
CostDatabase & CostDatabaseRegistry::costDatabase (unsigned int index)
Returns the CostDatabase from given index.
Returns
The CostDatabase from the given index.
Exceptions
OutOfRange Is thrown if index is bigger than the CostDatabase count.
Definition at line 143 of file CostDatabaseRegistry.cc.
{
    if (index > (registry_.size() - 1)) {
        throw OutOfRange(__FILE__, __LINE__,
                         "CostDatabaseRegistry::costDatavase(unsigned int)");
    }
    std::map<const HDB::HDBManager*, CostDatabase*>::const_iterator iter =
        registry_.begin();
    for (unsigned int counter = 0; iter != registry_.end(); iter++) {
        if (counter == index) {
            break;
        } else {
            counter++;
        }
    }
    return *(*iter).second;
}
References registry_.
costDatabaseCount()
int CostDatabaseRegistry::costDatabaseCount ()
Returns the total number of stored CostDatabases.
Returns
Count of stored CostDatabases.
Definition at line 130 of file CostDatabaseRegistry.cc.
{
    return registry_.size();
}
References registry_.
hasCostDatabase()
bool CostDatabaseRegistry::hasCostDatabase (const HDB::HDBManager & hdb)
Returns true if the registry contains a CostDatabase build against the given HDB.
Parameters
hdb The HDB that is used in creating the CostDatabase.
Returns
True if the registry contains a CostDatabase build against the given HDB.
Definition at line 115 of file CostDatabaseRegistry.cc.
{
    if (AssocTools::containsKey(registry_, &hdb)) {
        return true;
    } else {
        return false;
    }
}
References AssocTools::containsKey(), and registry_.
Referenced by CostDatabase::instance().
hdbPath()
std::string CostDatabaseRegistry::hdbPath (unsigned int index)
Returns the full path of the HDB with given index.
Returns
The HDB file path.
Exceptions
OutOfRange Is thrown if index is out of range.
Definition at line 167 of file CostDatabaseRegistry.cc.
{
    if (index > (registry_.size() - 1)) {
        throw OutOfRange(__FILE__, __LINE__,
                         "CostDatabaseRegistry::hdbPath(unsigned int)");
    }
    std::map<const HDB::HDBManager*, CostDatabase*>::const_iterator iter =
        registry_.begin();
    for (unsigned c = 0; iter != registry_.end(); iter++) {
        if (c == index) return (*iter).first->fileName();
        c++;
    }
    assert(false);
}
References assert, and registry_.
instance()
CostDatabaseRegistry & CostDatabaseRegistry::instance () static
Creates and returns an instance of cost database registry.
Returns
An instance of cost database registry.
Definition at line 60 of file CostDatabaseRegistry.cc.
{
    if (instance_ == NULL) {
        instance_ = new CostDatabaseRegistry();
    }
    return *instance_;
}
References CostDatabaseRegistry(), and instance_.
Referenced by CostDatabase::instance(), InterpolatingFUEstimator::InterpolatingFUEstimator(), and InterpolatingRFEstimator::InterpolatingRFEstimator().
Member Data Documentation
instance_
CostDatabaseRegistry * CostDatabaseRegistry::instance_ = NULL static private
Unique instance of the class.
Definition at line 65 of file CostDatabaseRegistry.hh.
Referenced by instance(), and ~CostDatabaseRegistry().
registry_
std::map<const HDB::HDBManager*, CostDatabase*> CostDatabaseRegistry::registry_ private
All created CostDatabasess are stored in this map.
Definition at line 63 of file CostDatabaseRegistry.hh.
Referenced by addCostDatabase(), costDatabase(), costDatabase(), costDatabaseCount(), hasCostDatabase(), hdbPath(), and ~CostDatabaseRegistry().
The documentation for this class was generated from the following files:
CostDatabaseRegistry.hh
CostDatabaseRegistry.cc