OpenASIP: BFPushDepsUp Class Reference
BFPushDepsUp Class Reference
#include <BFPushDepsUp.hh>
Public Member Functions
BFPushDepsUp (BF2Scheduler &sched, MoveNode &mn, int prefCycle)
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Static Public Attributes
static int recurseCounter_ = 0
Private Attributes
MoveNode & mn_
int prefCycle_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 43 of file BFPushDepsUp.hh.
Constructor & Destructor Documentation
BFPushDepsUp()
BFPushDepsUp::BFPushDepsUp (BF2Scheduler & sched, MoveNode & mn, int prefCycle) inline
Definition at line 46 of file BFPushDepsUp.hh.
                                                      :
    BFOptimization(sched),
    mn_(mn), prefCycle_(prefCycle) {}
Member Function Documentation
operator()()
bool BFPushDepsUp::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 41 of file BFPushDepsUp.cc.
{
    if (prefCycle_ < 0) {
        std::cerr << "push deps up prefcycle negative! "
                  << prefCycle_ << " move: " << mn_.toString() << std::endl;
        assert(false);
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    recurseCounter_++;
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\tPushing loop deps up: " << mn_.toString() << std::endl;
#endif
    bool pushed = false;
    DataDependenceGraph::EdgeSet inEdges = ddg().inEdges(mn_);
    for (auto e : inEdges) {
        MoveNode& loopDepTail = ddg().tailNode(*e);
        if (loopDepTail.isScheduled()) {
            int eLat = ddg().edgeLatency(*e, ii(), &loopDepTail, &mn_);
            int prefTailCycle = prefCycle_ - eLat;
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\t\tmy prefcycle is: " << prefCycle_
                      << " latency is: " << eLat
                      << " so preftailcycle is: " << prefTailCycle
                      << std::endl;
            std::cerr << "\t\t\t\tedge: " <<e->toString() << std::endl;
#endif
            if (loopDepTail.cycle() > prefTailCycle) {
                if (prefTailCycle < 0) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    recurseCounter_--;
#endif
                    undoAndRemovePreChildren();
                    return false;
                }
                BFOptimization* pushMoveUp;
                if (loopDepTail.isSourceOperation()) {
                    pushMoveUp =
                        new BFPushMoveUp2(sched_, loopDepTail, prefTailCycle);
                } else {
                    pushMoveUp =
                        new BFPushMoveUp(sched_, loopDepTail, prefTailCycle);
                }
                if (runPreChild(pushMoveUp)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    for (int i = 0; i < recurseCounter_*2; i++)
                        std::cerr << "\t";
                    std::cerr << "\tpushed up succesfully: "
                              << loopDepTail.toString()
                              << " preChildren size: "
                              << preChildren_.size() << std::endl;
#endif
                    pushed = true;
                } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    for (int i = 0; i < recurseCounter_*2; i++)
                        std::cerr << "\t";
                    std::cerr << "\t\tpushing up fail: "
                              << loopDepTail.toString()
                              << " preChildren size: "
                              << preChildren_.size() << std::endl;
#endif
                    undoAndRemovePreChildren();
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                    recurseCounter_--;
#endif
                    return false;
                }
            }
        }
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    recurseCounter_--;
#endif
    return pushed;
}
References assert, MoveNode::cycle(), BFOptimization::ddg(), DataDependenceGraph::edgeLatency(), BFOptimization::ii(), BoostGraph< GraphNode, GraphEdge >::inEdges(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), mn_, Reversible::preChildren_, prefCycle_, recurseCounter_, Reversible::runPreChild(), BFOptimization::sched_, BoostGraph< GraphNode, GraphEdge >::tailNode(), MoveNode::toString(), and Reversible::undoAndRemovePreChildren().
Member Data Documentation
mn_
MoveNode& BFPushDepsUp::mn_ private
Definition at line 52 of file BFPushDepsUp.hh.
Referenced by operator()().
prefCycle_
int BFPushDepsUp::prefCycle_ private
Definition at line 53 of file BFPushDepsUp.hh.
Referenced by operator()().
recurseCounter_
int BFPushDepsUp::recurseCounter_ = 0 static
Definition at line 45 of file BFPushDepsUp.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPushDepsUp.hh
BFPushDepsUp.cc