OpenASIP: HDBTester Class Reference
HDBTester Class Reference
#include <HDBTester.hh>
Public Member Functions
HDBTester ()
HDBTester (std::ostream &infoStream, std::ostream &errorStream, VhdlSim simulator, bool verbose, bool leaveDirty)
virtual ~HDBTester ()
bool testAllEntries (std::string hdbFile)
bool testOneRF (std::string hdbFile, int entryId)
bool testOneFU (std::string hdbFile, int entryId)
Private Member Functions
ImplementationTester * initializeTester (std::string hdbFile)
bool testFU (int id, ImplementationTester *tester)
bool testRF (int id, ImplementationTester *tester)
Private Attributes
std::ostream * infoStream_
std::ostream * errorStream_
VhdlSim sim_
bool verbose_
bool leaveDirty_
Detailed Description
Definition at line 39 of file HDBTester.hh.
Constructor & Destructor Documentation
HDBTester() [1/2]
HDBTester::HDBTester ()
Definition at line 43 of file HDBTester.cc.
                    : infoStream_(NULL), errorStream_(NULL), sim_(SIM_GHDL),
                        verbose_(false), leaveDirty_(false) {
}
HDBTester() [2/2]
HDBTester::HDBTester (std::ostream & infoStream, std::ostream & errorStream, VhdlSim simulator, bool verbose, bool leaveDirty)
Definition at line 47 of file HDBTester.cc.
                                                     :
    infoStream_(&infoStream), errorStream_(&errorStream), sim_(simulator),
    verbose_(verbose), leaveDirty_(leaveDirty) {
}
~HDBTester()
HDBTester::~HDBTester () virtual
Definition at line 55 of file HDBTester.cc.
                      {
    // clear hdb cache
    HDB::HDBRegistry* registry = &HDB::HDBRegistry::instance();
    delete registry;
}
References HDB::HDBRegistry::instance().
Member Function Documentation
initializeTester()
ImplementationTester * HDBTester::initializeTester (std::string hdbFile) private
Definition at line 128 of file HDBTester.cc.
{
    ImplementationTester* tester = NULL;
    try {
        tester =
            new ImplementationTester(hdbFile, sim_, verbose_, leaveDirty_);
    } catch (Exception& e) {
        if (errorStream_ != NULL) {
            *errorStream_ << "Failed to create implementation tester: "
                          << e.errorMessage() << std::endl;
        }
        return NULL;
    }
    return tester;
}
References Exception::errorMessage(), errorStream_, leaveDirty_, sim_, and verbose_.
Referenced by testAllEntries(), testOneFU(), and testOneRF().
testAllEntries()
bool HDBTester::testAllEntries (std::string hdbFile)
Definition at line 62 of file HDBTester.cc.
{
    ImplementationTester* implTester = initializeTester(hdbFile);
    if (implTester == NULL) {
        return false;
    }
    bool noFailures = true;
    set<int> fus = implTester->fuEntryIDs();
    for (set<int>::iterator iter = fus.begin(); iter != fus.end(); iter++) {
        if (!testFU(*iter, implTester)) {
            noFailures = false;
            std::cerr << "FU Entry " << *iter << " from " << hdbFile
                      << " failed." << std::endl;
        }
    }
    set<int> rfs = implTester->rfEntryIDs();
    for (set<int>::iterator iter = rfs.begin(); iter != rfs.end(); iter++) {
        if (!testRF(*iter, implTester)) {
            noFailures = false;
            std::cerr << "RF Entry " << *iter << " from " << hdbFile
                      << " failed." << std::endl;
        }
    }
    delete implTester;
    return noFailures;
}
References ImplementationTester::fuEntryIDs(), initializeTester(), ImplementationTester::rfEntryIDs(), testFU(), and testRF().
Referenced by main().
testFU()
bool HDBTester::testFU (int id, ImplementationTester * tester) private
Definition at line 145 of file HDBTester.cc.
{
    string reason = "";
    if (!tester->canTestFU(id, reason)) {
        if (infoStream_ != NULL) {
            *infoStream_ << "Cannot test FU id " << id << " because: "
                         << reason << std::endl;
        }
        // this is not failure
        return true;
    }
    vector<string> errors;
    bool success = false;
    try {
        success = tester->validateFU(id, errors);
    } catch (Exception& e) {
        if (errorStream_ != NULL) {
            *errorStream_
                << "Runtime error: " << e.errorMessage() << std::endl;
        }
        return false;
    }
    if (!errors.empty()) {
        if (errorStream_ != NULL) {
            for (unsigned int i = 0; i < errors.size(); i++) {
                 *errorStream_ << errors.at(i);
            }
        }
        success = false;
    }
    return success;
}
References ImplementationTester::canTestFU(), Exception::errorMessage(), errorStream_, infoStream_, and ImplementationTester::validateFU().
Referenced by testAllEntries(), and testOneFU().
testOneFU()
bool HDBTester::testOneFU (std::string hdbFile, int entryId)
Definition at line 110 of file HDBTester.cc.
{
    ImplementationTester* implTester = initializeTester(hdbFile);
    if (implTester == NULL) {
        return false;
    }
    bool success = testFU(entryId, implTester);
    delete implTester;
    if (!success) {
        std::cerr << "FU Entry " << entryId << " from " << hdbFile
                  << " failed." << std::endl;
    }
    return success;
}
References initializeTester(), and testFU().
Referenced by main(), and testUnits().
testOneRF()
bool HDBTester::testOneRF (std::string hdbFile, int entryId)
Definition at line 92 of file HDBTester.cc.
{
    ImplementationTester* implTester = initializeTester(hdbFile);
    if (implTester == NULL) {
        return false;
    }
    bool success = testRF(entryId, implTester);
    delete implTester;
    if (!success) {
        std::cerr << "RF Entry " << entryId << " from " << hdbFile
                  << " failed." << std::endl;
    }
    return success;
}
References initializeTester(), and testRF().
Referenced by main(), and testUnits().
testRF()
bool HDBTester::testRF (int id, ImplementationTester * tester) private
Definition at line 179 of file HDBTester.cc.
{
    string reason = "";
    if (!tester->canTestRF(id, reason)) {
        if (infoStream_ != NULL) {
            *infoStream_ << "Cannot test RF id " << id << " because: "
                         << reason << std::endl;
        }
        // this is not failure
        return true;
    }
    vector<string> errors;
    bool success = false;
    try {
        success = tester->validateRF(id, errors);
    } catch (Exception& e) {
        if (errorStream_ != NULL) {
            *errorStream_
                << "Runtime error: " << e.errorMessage() << std::endl;
        }
        return false;
    }
    if (!errors.empty()) {
        if (errorStream_ != NULL) {
            for (unsigned int i = 0; i < errors.size(); i++) {
                 *errorStream_ << errors.at(i);
            }
        }
        success = false;
    }
    return success;
}
References ImplementationTester::canTestRF(), Exception::errorMessage(), errorStream_, infoStream_, and ImplementationTester::validateRF().
Referenced by testAllEntries(), and testOneRF().
Member Data Documentation
errorStream_
std::ostream* HDBTester::errorStream_ private
Definition at line 65 of file HDBTester.hh.
Referenced by initializeTester(), testFU(), and testRF().
infoStream_
std::ostream* HDBTester::infoStream_ private
Definition at line 64 of file HDBTester.hh.
Referenced by testFU(), and testRF().
leaveDirty_
bool HDBTester::leaveDirty_ private
Definition at line 68 of file HDBTester.hh.
Referenced by initializeTester().
sim_
VhdlSim HDBTester::sim_ private
Definition at line 66 of file HDBTester.hh.
Referenced by initializeTester().
verbose_
bool HDBTester::verbose_ private
Definition at line 67 of file HDBTester.hh.
Referenced by initializeTester().
The documentation for this class was generated from the following files:
HDBTester.hh
HDBTester.cc