OpenASIP: MachineCanvas Class Reference
MachineCanvas Class Reference
#include <MachineCanvas.hh>
Public Member Functions
MachineCanvas (wxWindow *parent, EditPolicyFactory *policyFactory, ChildFrame *parentFrame=nullptr)
virtual ~MachineCanvas ()
virtual void OnDraw (wxDC &dc)
double zoomFactor ()
void setZoomFactor (double factor)
void zoomIn ()
void zoomOut ()
wxSize getFigureSize () const
void setTool (MachineCanvasTool *tool)
MachineCanvasTool * tool ()
void setMachine (TTAMachine::Machine *machine)
void updateMachine ()
EditPart * selection ()
EditPart * findEditPart (int x, int y)
EditPart * findEditPart (const TTAMachine::MachinePart *model)
bool hasEditPart (const EditPart *part) const
int findEditPartsInRange (int x, int y, int range, std::vector< EditPart * > &found)
void highlight (TTAMachine::MachinePart *model, const wxColour &colour)
void clearHighlights ()
void clearSelection ()
void select (EditPart *part)
void refreshToolFigure ()
void addMove (const TTAMachine::Bus *bus, const TTAMachine::Port *source, const TTAMachine::Port *target)
void clearMoves ()
bool saveEPS (const std::string &filename, const std::string &title, const std::string &creator="")
bool savePNG (const std::string &filename)
MachineCanvasOptions & options ()
Protected Member Functions
void onMouseEvent (wxMouseEvent &event)
void refreshLogicalRect (const wxRect &rectangle)
Private Attributes
MachineCanvasTool * tool_
Tool which handles mouse events on the MachineCanvas.
TTAMachine::Machine * machine_
Machine to draw on the canvas.
EditPolicyFactory * editPolicyFactory_
EditPolicyFactory which creates edit policies for machine components.
ChildFrame * parent_
Parent frame which holds the MachineCanvas.
double zoomFactor_
Zoom factor of the canvas.
bool dirty_
Tells if the figures need to be laid out before next draw.
RootEditPart * root_
Root of the machine EditPart hierarchy.
EditPart * selection_
Pointer to the the selected component.
wxRect toolBounds_
Bounding box of the last tool figure drawn.
std::vector< Figure * > moveFigures_
Move figures to be drawn on the canvas.
MachineCanvasOptions options_
Detailed Description
Machine Object Model visualization canvas.
MachineCanvas is a window which can be utilized to display visualization of a machine object model. The visualization is interactive, and behaviour of machine components can be defined using custom EditPolicies and custom MachineCanvasTools.
Definition at line 64 of file MachineCanvas.hh.
Constructor & Destructor Documentation
MachineCanvas()
MachineCanvas::MachineCanvas (wxWindow * parent, EditPolicyFactory * policyFactory, ChildFrame * parentFrame = nullptr)
The Constructor, with a parameter for parent frame.
Parameters
parent Parent frame of the canvas.
policyFactory EditPolicyFactory for creating edit policies.
Definition at line 70 of file MachineCanvas.cc.
                                                               :
                wxScrolledWindow(parent), tool_(NULL), machine_(NULL),
                    editPolicyFactory_(policyFactory),  parent_(parentFrame),
                    zoomFactor_(1.0), dirty_(true), root_(NULL),
                    selection_(NULL), toolBounds_(0, 0, 0, 0) {
    root_ = new RootEditPart();
    SetScrollRate(20, 20);
    SetVirtualSize(1000, 800);
}
~MachineCanvas()
MachineCanvas::~MachineCanvas () virtual
The Destructor.
Definition at line 88 of file MachineCanvas.cc.
{
    if (root_ != NULL) {
        delete root_;
    }
    clearMoves();
}
References clearMoves(), and root_.
Member Function Documentation
addMove()
void MachineCanvas::addMove (const TTAMachine::Bus * bus, const TTAMachine::Port * source, const TTAMachine::Port * target)
Adds a move to be drawn on the canvas.
Parameters
bus Transport bus of the move.
source Source port of the move.
target Target port of the move.
Definition at line 541 of file MachineCanvas.cc.
{
    std::string procName = "MachineCanvas::addMove";
    EditPart* busEditPart = findEditPart(bus);
    if (busEditPart == NULL) {
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    Figure* busFigure = busEditPart->figure();
    Figure* sourceFigure = NULL;
    Figure* targetFigure = NULL;
    if (source != NULL) {
        EditPart* sourceEditPart = findEditPart(source);
        if (sourceEditPart == NULL) {
            throw InstanceNotFound(__FILE__, __LINE__, procName);
        }
        sourceFigure = sourceEditPart->figure();
    }
    if (target != NULL) {
        EditPart* targetEditPart = findEditPart(target);
        if (targetEditPart == NULL) {
            throw InstanceNotFound(__FILE__, __LINE__, procName);
        }
        targetFigure = targetEditPart->figure();
    }
    moveFigures_.push_back(
        new MoveFigure(busFigure, sourceFigure, targetFigure));
}
References EditPart::figure(), findEditPart(), and moveFigures_.
Referenced by ProximMachineStateWindow::addMoves().
clearHighlights()
void MachineCanvas::clearHighlights ()
Clears highlighting of all machine components.
Definition at line 527 of file MachineCanvas.cc.
{
    if (root_ != NULL && root_->contents() != NULL) {
        root_->contents()->figure()->clearHighlight();
    }
}
References Figure::clearHighlight(), RootEditPart::contents(), EditPart::figure(), and root_.
Referenced by ProximMachineStateWindow::onToggleUtilizations(), and ProximMachineStateWindow::setUtilizationHighlights().
clearMoves()
void MachineCanvas::clearMoves ()
Clears list of moves to be drawn on the canvas.
Definition at line 577 of file MachineCanvas.cc.
{
    SequenceTools::deleteAllItems(moveFigures_);
}
References SequenceTools::deleteAllItems(), and moveFigures_.
Referenced by ProximMachineStateWindow::addMoves(), ProximMachineStateWindow::onToggleMoves(), updateMachine(), and ~MachineCanvas().
clearSelection()
void MachineCanvas::clearSelection ()
Clears component selection.
Definition at line 395 of file MachineCanvas.cc.
{
    if (selection_ != NULL) {
        selection_->setSelected(false);
    }
    selection_ = NULL;
    Refresh();
}
References selection_, and EditPart::setSelected().
Referenced by MDFView::clearSelection(), SelectTool::leftClick(), ProximMachineCanvasTool::onMouseEvent(), ProximMachineStateWindow::onSimulationStop(), and updateMachine().
findEditPart() [1/2]
EditPart * MachineCanvas::findEditPart (const TTAMachine::MachinePart * model)
Finds an edit part corresponding the given machine part.
Parameters
model MachinePart to find
Returns
Pointer to the found edit part, or NULL if no edit part was found.
Definition at line 436 of file MachineCanvas.cc.
{
    EditPart* part = NULL;
    if (root_ != NULL && root_->contents() != NULL) {
        part = root_->contents()->find(model);
    }
    return part;
}
References RootEditPart::contents(), EditPart::find(), and root_.
findEditPart() [2/2]
EditPart * MachineCanvas::findEditPart (int x, int y)
Finds an edit part at the given coordinates on the canvas.
Parameters
x X-coordinate of the position to search.
y Y-coordinate of the position to search.
Returns
Pointer to the found edit part, or NULL if no edit part was found.
Definition at line 421 of file MachineCanvas.cc.
{
    EditPart* part = NULL;
    if (root_ != NULL && root_->contents() != NULL) {
        part = root_->contents()->find(wxPoint(x, y));
    }
    return part;
}
References RootEditPart::contents(), EditPart::find(), and root_.
Referenced by addMove(), ProximMachineCanvasTool::onMouseEvent(), ConnectTool::onMouseEvent(), SelectTool::onMouseEvent(), and ProximMachineStateWindow::onSimulationStop().
findEditPartsInRange()
int MachineCanvas::findEditPartsInRange (int x, int y, int range, std::vector< EditPart * > & found)
Finds EditParts around coordinates that are in given range.
Parameters
x X-coordinate of the position to search.
y Y-coordinate of the position to search.
range Search range from position (x, y).
found Found EditParts after call.
Returns
Number of found EditParts. Zero if found nothing.
Definition at line 454 of file MachineCanvas.cc.
{
    if (root_ != NULL && root_->contents() != NULL) {
        return root_->contents()->findInRange(wxPoint(x, y),
            static_cast<float>(range), found);
    }
    return 0;
}
References RootEditPart::contents(), EditPart::findInRange(), and root_.
Referenced by ConnectTool::onMouseEvent().
getFigureSize()
wxSize MachineCanvas::getFigureSize () const
Return the original size of the currently loaded Machine Figure
Definition at line 294 of file MachineCanvas.cc.
{
    return root_->contents()->figure()->bounds().GetSize();
}
References Figure::bounds(), RootEditPart::contents(), EditPart::figure(), and root_.
Referenced by FitHeightCmd::Do(), FitWidthCmd::Do(), and FitWindowCmd::Do().
hasEditPart()
bool MachineCanvas::hasEditPart (const EditPart * part) const
Looks for given EditPart recursively.
Parameters
part Part to look up.
Returns
True if canvas has given EditPart.
Definition at line 470 of file MachineCanvas.cc.
{
    if (root_ != NULL && root_->contents() != NULL) {
        return root_->contents()->hasEditPartRecursive(part);
    }
    return false;
}
References RootEditPart::contents(), EditPart::hasEditPartRecursive(), and root_.
Referenced by ConnectTool::figure().
highlight()
void MachineCanvas::highlight (TTAMachine::MachinePart * component, const wxColour & colour)
Highlights figure of a machine component.
Definition at line 510 of file MachineCanvas.cc.
{
    if (root_->contents() == NULL) {
        return;
    }
    EditPart* editPart = root_->contents()->find(component);
    if (editPart != NULL && editPart->figure() != NULL) {
        editPart->figure()->highlight(colour);
    }
}
References RootEditPart::contents(), EditPart::figure(), EditPart::find(), Figure::highlight(), and root_.
Referenced by ProximMachineStateWindow::setUtilizationHighlights().
OnDraw()
void MachineCanvas::OnDraw (wxDC & dc) virtual
Called when the window needs to be drawn again.
Parameters
dc The device context where to do the actual drawing.
Definition at line 101 of file MachineCanvas.cc.
{
    wxBrush backgroundBrush(*wxLIGHT_GREY, wxSOLID);
    dc.SetBackground(backgroundBrush);
#if wxCHECK_VERSION(3, 0, 0)
    // Do not call Clear() for wxSVGFileDC object cause its not implemented
    try {
        (void)dynamic_cast<wxSVGFileDC&> (dc);
    } catch (const std::bad_cast& e) {
        dc.Clear();
    }
#else
    dc.Clear();
#endif
    // Set the canvas font.
    dc.SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxNORMAL));
    // Set scaling factor.
    dc.SetUserScale(zoomFactor_, zoomFactor_);
    // draw machine
    if (root_->contents() != NULL) {
        if (dirty_) {
            root_->contents()->figure()->layout(&dc);
            // Set Canvas virtual size according to the size needed by the
            // figures.
            wxRect bounds = root_->contents()->figure()->bounds();
            SetVirtualSize(int(bounds.GetWidth() * zoomFactor()),
                int(bounds.GetHeight() * zoomFactor()));
            dirty_ = false;
        }
        root_->contents()->figure()->draw(&dc);
    }
    // draw tool figure
    if (tool() != NULL) {
        Figure* toolFigure = tool()->figure();
        if (toolFigure != NULL) {
            toolFigure->layout(&dc);
            toolFigure->draw(&dc);
        }
    }
    // Draw moves.
    for (unsigned i = 0; i < moveFigures_.size(); i++) {
        moveFigures_[i]->draw(&dc);
    }
    // Draw selection rectangle.
    if (selection() != NULL) {
        SelectionFigure figure(selection()->figure());
        figure.layout(&dc);
        figure.draw(&dc);
    }
}
References Figure::bounds(), RootEditPart::contents(), dirty_, Figure::draw(), MachineCanvasTool::figure(), EditPart::figure(), Figure::layout(), moveFigures_, root_, selection(), tool(), zoomFactor(), and zoomFactor_.
Referenced by MDFView::OnDraw(), ADFPrintout::OnPrintPage(), saveEPS(), and savePNG().
onMouseEvent()
void MachineCanvas::onMouseEvent (wxMouseEvent & event) protected
Handles mouse events on the canvas.
Passes the mouse event to the active tool.
Parameters
event Mouse event to pass to the active tool.
Definition at line 265 of file MachineCanvas.cc.
{
    wxClientDC dc(this);
    PrepareDC(dc);
    dc.SetUserScale(zoomFactor_, zoomFactor_);
    // Zoomin/out with mousewheel
    if (event.GetEventType() == wxEVT_MOUSEWHEEL) {
        double factor;
        if (event.GetWheelRotation() > 0) {
            factor = zoomFactor() + CanvasConstants::ZOOM_STEP;
        } else {
            factor = zoomFactor() - CanvasConstants::ZOOM_STEP;
        }
        setZoomFactor(factor);
    }
    if (tool_ != NULL) {
        tool_->onMouseEvent(event, dc);
    }
}
References MachineCanvasTool::onMouseEvent(), setZoomFactor(), tool_, CanvasConstants::ZOOM_STEP, zoomFactor(), and zoomFactor_.
options()
MachineCanvasOptions & MachineCanvas::options ()
Returns the current options used by machine canvas figures.
Returns
Current machine canvas options.
Definition at line 681 of file MachineCanvas.cc.
                       {
    return options_;
}
References options_.
Referenced by ToggleUnitDetailsCmd::Do(), ToggleUnitDetailsCmd::isChecked(), ProximMachineStateWindow::onToggleUnitInfo(), and ProximMachineStateWindow::onUpdateUIEvent().
refreshLogicalRect()
void MachineCanvas::refreshLogicalRect (const wxRect & rectangle) protected
Refreshes area of the MachineCanvas bound by a logical coordinate rectangle.
Parameters
rectangle Area to refresh.
Definition at line 329 of file MachineCanvas.cc.
{
    int x = 0;
    int y = 0;
    CalcScrolledPosition(int(rectangle.x * zoomFactor_),
        int(rectangle.y * zoomFactor_), &x, &y);
    wxRect zoomed(x, y, int(rectangle.width * zoomFactor_),
        int(rectangle.height * zoomFactor_));
    RefreshRect(zoomed);
}
References zoomFactor_.
Referenced by refreshToolFigure().
refreshToolFigure()
void MachineCanvas::refreshToolFigure ()
Refreshes the tool figures on the canvas.
Definition at line 164 of file MachineCanvas.cc.
{
    if (toolBounds_.GetWidth() > 0 && toolBounds_.GetHeight() > 0) {
        // Clear previous tool figure.
        refreshLogicalRect(toolBounds_);
    }
    Figure* toolFigure = tool()->figure();
    if (toolFigure != NULL) {
        // Draw new tool figure.
        toolFigure->layout(NULL);
        toolBounds_ = toolFigure->bounds();
        refreshLogicalRect(toolBounds_);
    } else {
        toolBounds_ = wxRect(0, 0, 0, 0);
    }
}
References Figure::bounds(), MachineCanvasTool::figure(), Figure::layout(), refreshLogicalRect(), tool(), and toolBounds_.
Referenced by ConnectTool::onMouseEvent().
saveEPS()
bool MachineCanvas::saveEPS (const std::string & filename, const std::string & title, const std::string & creator = "")
Saves the machine figure to an eps file.
Parameters
filename Name of the eps file.
title Title of the eps document.
creator Creator of the eps document.
Returns
True, if the eps was succesfully saved.
Definition at line 617 of file MachineCanvas.cc.
{
    EPSDC dc;
    dc.setCreator(creator);
    dc.setTitle(title);
    dc.StartPage();
    OnDraw(dc);
    dc.EndPage();
    std::ofstream file(filename.c_str());
    if (file.bad()) {
        return false;
    }
    dc.writeToStream(file);
    file.close();
    return true;
}
References EPSDC::EndPage(), OnDraw(), EPSDC::setCreator(), EPSDC::setTitle(), EPSDC::StartPage(), and EPSDC::writeToStream().
Referenced by ProDeExportCmd::Do(), and ProximMachineStateWindow::onExport().
savePNG()
bool MachineCanvas::savePNG (const std::string & filename)
Saves the machine figure to a .png file.
Parameters
filename Name of the .png file.
Returns
True, if the png was succesfully saved.
Definition at line 648 of file MachineCanvas.cc.
{
    // Refresh machine figure to get the canvas size.
    wxClientDC clientDC(this);
    OnDraw(clientDC);
    // Add minimum coordinates to maximum coordinates to create margins
    // of equal width.
    int width = clientDC.MaxX() + clientDC.MinX();
    int height = clientDC.MaxY() + clientDC.MinY();
    // Create bitmap and a MemoryDC which writes the bitmap.
    wxMemoryDC bitmapDC;
    wxBitmap bitmap(width, height);
    bitmapDC.SelectObject(bitmap);
    OnDraw(bitmapDC);
    wxString file = WxConversion::toWxString(filename);
    // Save bitmap.
    if (bitmap.SaveFile(file, wxBITMAP_TYPE_PNG)) {
        return true;
    }
    return false;
}
References OnDraw(), and WxConversion::toWxString().
Referenced by ProDeExportCmd::Do(), and ProximMachineStateWindow::onExport().
select()
void MachineCanvas::select (EditPart * part)
Marks an edit part selected.
Previous selection is cleared.
Parameters
part Edit part to select.
Definition at line 485 of file MachineCanvas.cc.
{
    if (selection_ != NULL) {
        selection_->setSelected(false);
    }
    // segments are not supported so we should select the parent
    // bus instead the segment (a very long standing irritating bug)
    TTAMachine::Segment* segment =
                    dynamic_cast<TTAMachine::Segment*>(part->model());
    if (segment != NULL) {
        // clicked segment, selecting parent bus instead
        part = part->parent();
    }
    selection_ = part;
    if (selection_ != NULL) {
        selection_->setSelected(true);
    }
    Refresh();
}
References EditPart::model(), EditPart::parent(), selection_, and EditPart::setSelected().
Referenced by ConnectTool::leftClick(), SelectTool::leftClick(), ProximMachineCanvasTool::onMouseEvent(), and ProximMachineStateWindow::onSimulationStop().
selection()
EditPart * MachineCanvas::selection ()
Returns pointer to the EditPart of the selected component.
Returns
Pointer to the selected EditPart, or null if selection is empty.
Definition at line 409 of file MachineCanvas.cc.
{
    return selection_;
}
References selection_.
Referenced by OnDraw(), ConnectTool::onMouseEvent(), ProximMachineStateWindow::onSimulationStop(), and MDFView::selection().
setMachine()
void MachineCanvas::setMachine (TTAMachine::Machine * machine)
Sets the machine which is dispalyed on the canvas.
Parameters
machine Machine to display on the canvas.
Definition at line 386 of file MachineCanvas.cc.
{
    machine_ = machine;
    updateMachine();
}
References machine, machine_, and updateMachine().
Referenced by ProximMachineStateWindow::onProgramLoaded(), MDFView::OnUpdate(), and ProximMachineStateWindow::reset().
setTool()
void MachineCanvas::setTool (MachineCanvasTool * tool)
Sets the active tool.
Parameters
tool MachineCanvasTool to activate.
Definition at line 305 of file MachineCanvas.cc.
{
    if (tool_ != NULL) {
        tool_->deactivate();
        delete (tool_);
    }
    tool_ = tool;
    tool_->activate();
}
References MachineCanvasTool::activate(), MachineCanvasTool::deactivate(), tool(), and tool_.
Referenced by ProximMachineStateWindow::createContents(), EditConnectionsCmd::Do(), SelectCmd::Do(), and MDFView::OnCreate().
setZoomFactor()
void MachineCanvas::setZoomFactor (double factor)
Sets the zoom factor of the canvas.
Parameters
factor New zoom factor of the canvas.
Definition at line 188 of file MachineCanvas.cc.
{
    // Limit the min/max size of the zoom factor
    if (factor > CanvasConstants::MAX_ZOOM_FACTOR) {
        factor = CanvasConstants::MAX_ZOOM_FACTOR;
    } else if (factor < CanvasConstants::MIN_ZOOM_FACTOR) {
        factor = CanvasConstants::MIN_ZOOM_FACTOR;
    }
    // when scrolling, try to:
    // * On X direction, keep the middle pointing to same position in machine
    // * On Y direction, keep the upper edge of the windows pointer to
    //   same position in the machine.
    // This code calculates this and does the scrolling.
    int x, y;
    int xSize, ySize;
    int scrollUnitX, scrollUnitY;
    GetScrollPixelsPerUnit(&scrollUnitX, &scrollUnitY);
    GetViewStart(&x, &y);
    x *= scrollUnitX;
    y *= scrollUnitY;
    GetSize(&xSize, &ySize);
    double xPos = (x + (xSize >> 1)) / zoomFactor_;
    double yPos = y / zoomFactor_;
    x = std::max(static_cast<int>(xPos * factor) - (xSize >> 1), 0);
    y = static_cast<int>(yPos * factor);
    Scroll((x + (scrollUnitX >> 1)) / scrollUnitX,
        (y + (scrollUnitY >> 1)) / scrollUnitY);
    // then do the zooming
    zoomFactor_ = factor;
    dirty_ = true;
    Refresh();
}
References dirty_, CanvasConstants::MAX_ZOOM_FACTOR, CanvasConstants::MIN_ZOOM_FACTOR, and zoomFactor_.
Referenced by FitHeightCmd::Do(), FitWidthCmd::Do(), FitWindowCmd::Do(), onMouseEvent(), zoomIn(), and zoomOut().
tool()
MachineCanvasTool * MachineCanvas::tool ()
Returns pointer to the current tool of the canvas.
Definition at line 318 of file MachineCanvas.cc.
                    {
    return tool_;
}
References tool_.
Referenced by BridgeDialog::BridgeDialog(), BridgeDialog::onCancel(), OnDraw(), BridgeDialog::onOK(), refreshToolFigure(), and setTool().
updateMachine()
void MachineCanvas::updateMachine ()
Updates the machine from the machine object model.
Definition at line 345 of file MachineCanvas.cc.
{
    clearSelection();
    clearMoves();
    dirty_ = true;
    if (machine_ == NULL) {
        root_->setContents(NULL);
        return;
    }
    MachineEditPartFactory factory(*editPolicyFactory_);
    EditPart* contents = factory.createEditPart(machine_);
    assert(root_ != NULL);
    root_->setContents(contents);
    contents->figure()->setOptions(&options_);
    if (parent_ != nullptr) {
        wxString text(_T(""));
        BinaryEncoding* bem(nullptr);
        try {
            bem = BEMGenerator(*machine_).generate();
            int width = bem->width();
            text = wxString::Format(_T("Instruction width: %u"), width);
        } catch (...) {
            text = _T("BEM could not be generated");
        }
        delete bem;
        parent_->setStatus(text, 1);
    }
    Refresh();
}
References assert, clearMoves(), clearSelection(), MachineEditPartFactory::createEditPart(), dirty_, editPolicyFactory_, EditPart::figure(), BEMGenerator::generate(), machine_, options_, parent_, root_, RootEditPart::setContents(), Figure::setOptions(), ChildFrame::setStatus(), and BinaryEncoding::width().
Referenced by ToggleUnitDetailsCmd::Do(), ProximMachineStateWindow::onToggleUnitInfo(), and setMachine().
zoomFactor()
double MachineCanvas::zoomFactor ()
Returns the zoom factor of the canvas.
Returns
Zoom factor of the canvas.
Definition at line 230 of file MachineCanvas.cc.
{
    return zoomFactor_;
}
References zoomFactor_.
Referenced by OnDraw(), onMouseEvent(), zoomIn(), and zoomOut().
zoomIn()
void MachineCanvas::zoomIn ()
Zooms in the canvas by a predefined factor
Definition at line 240 of file MachineCanvas.cc.
                      {
    double factor = zoomFactor() + CanvasConstants::ZOOM_STEP;
    setZoomFactor(factor);
}
References setZoomFactor(), CanvasConstants::ZOOM_STEP, and zoomFactor().
Referenced by ZoomInCmd::Do(), and ProximMachineStateWindow::onZoom().
zoomOut()
void MachineCanvas::zoomOut ()
Zooms out the canvas by a predefined factor
Definition at line 251 of file MachineCanvas.cc.
                       {
    double factor = zoomFactor() - CanvasConstants::ZOOM_STEP;
    setZoomFactor(factor);
}
References setZoomFactor(), CanvasConstants::ZOOM_STEP, and zoomFactor().
Referenced by ZoomOutCmd::Do(), and ProximMachineStateWindow::onZoom().
Member Data Documentation
dirty_
bool MachineCanvas::dirty_ private
Tells if the figures need to be laid out before next draw.
Definition at line 130 of file MachineCanvas.hh.
Referenced by OnDraw(), setZoomFactor(), and updateMachine().
editPolicyFactory_
EditPolicyFactory* MachineCanvas::editPolicyFactory_ private
EditPolicyFactory which creates edit policies for machine components.
Definition at line 123 of file MachineCanvas.hh.
Referenced by updateMachine().
machine_
TTAMachine::Machine* MachineCanvas::machine_ private
Machine to draw on the canvas.
Definition at line 121 of file MachineCanvas.hh.
Referenced by setMachine(), and updateMachine().
moveFigures_
std::vector<Figure*> MachineCanvas::moveFigures_ private
Move figures to be drawn on the canvas.
Definition at line 140 of file MachineCanvas.hh.
Referenced by addMove(), clearMoves(), and OnDraw().
options_
MachineCanvasOptions MachineCanvas::options_ private
Definition at line 142 of file MachineCanvas.hh.
Referenced by options(), and updateMachine().
parent_
ChildFrame* MachineCanvas::parent_ private
Parent frame which holds the MachineCanvas.
Definition at line 125 of file MachineCanvas.hh.
Referenced by updateMachine().
root_
RootEditPart* MachineCanvas::root_ private
Root of the machine EditPart hierarchy.
Definition at line 132 of file MachineCanvas.hh.
Referenced by clearHighlights(), findEditPart(), findEditPart(), findEditPartsInRange(), getFigureSize(), hasEditPart(), highlight(), OnDraw(), updateMachine(), and ~MachineCanvas().
selection_
EditPart* MachineCanvas::selection_ private
Pointer to the the selected component.
Definition at line 135 of file MachineCanvas.hh.
Referenced by clearSelection(), select(), and selection().
tool_
MachineCanvasTool* MachineCanvas::tool_ private
Tool which handles mouse events on the MachineCanvas.
Definition at line 119 of file MachineCanvas.hh.
Referenced by onMouseEvent(), setTool(), and tool().
toolBounds_
wxRect MachineCanvas::toolBounds_ private
Bounding box of the last tool figure drawn.
Definition at line 137 of file MachineCanvas.hh.
Referenced by refreshToolFigure().
zoomFactor_
double MachineCanvas::zoomFactor_ private
Zoom factor of the canvas.
Definition at line 128 of file MachineCanvas.hh.
Referenced by OnDraw(), onMouseEvent(), refreshLogicalRect(), setZoomFactor(), and zoomFactor().
The documentation for this class was generated from the following files:
MachineCanvas.hh
MachineCanvas.cc