OpenASIP: ProximNewRegisterWindowCmd Class Reference
ProximNewRegisterWindowCmd Class Reference
#include <ProximNewRegisterWindowCmd.hh>
Public Member Functions
ProximNewRegisterWindowCmd ()
virtual ~ProximNewRegisterWindowCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximNewRegisterWindowCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening a new register window in Proxim.
Definition at line 41 of file ProximNewRegisterWindowCmd.hh.
Constructor & Destructor Documentation
ProximNewRegisterWindowCmd()
ProximNewRegisterWindowCmd::ProximNewRegisterWindowCmd ()
The Constructor.
Definition at line 41 of file ProximNewRegisterWindowCmd.cc.
                                                      :
    GUICommand(ProximConstants::COMMAND_NAME_NEW_REGISTER_WINDOW, NULL) {
    }
Referenced by create().
~ProximNewRegisterWindowCmd()
ProximNewRegisterWindowCmd::~ProximNewRegisterWindowCmd () virtual
The Destructor.
Definition at line 49 of file ProximNewRegisterWindowCmd.cc.
{
}
Member Function Documentation
create()
ProximNewRegisterWindowCmd * ProximNewRegisterWindowCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 97 of file ProximNewRegisterWindowCmd.cc.
{
    return new ProximNewRegisterWindowCmd();
}
References ProximNewRegisterWindowCmd().
Do()
bool ProximNewRegisterWindowCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 57 of file ProximNewRegisterWindowCmd.cc.
{
    ProximRegisterWindow* regWindow = new ProximRegisterWindow(
        ProximToolbox::mainFrame(), -1);
    ProximToolbox::addFramedWindow(
        regWindow, _T("Registers"), false, wxSize(270, 200));
    regWindow->GetParent()->SetSize(270, 300);
    return true;
}
References ProximToolbox::addFramedWindow(), and ProximToolbox::mainFrame().
icon()
std::string ProximNewRegisterWindowCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 77 of file ProximNewRegisterWindowCmd.cc.
{
    return "window_new.png";
}
id()
int ProximNewRegisterWindowCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 86 of file ProximNewRegisterWindowCmd.cc.
{
    return ProximConstants::COMMAND_NEW_REGISTER_WINDOW;
}
References ProximConstants::COMMAND_NEW_REGISTER_WINDOW.
isEnabled()
bool ProximNewRegisterWindowCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 108 of file ProximNewRegisterWindowCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximNewRegisterWindowCmd.hh
ProximNewRegisterWindowCmd.cc