OpenASIP: MDFDocument Class Reference
MDFDocument Class Reference
#include <MDFDocument.hh>
Public Member Functions
MDFDocument ()
virtual ~MDFDocument ()
virtual bool OnOpenDocument (const wxString &filename)
virtual bool OnSaveDocument (const wxString &filename)
virtual bool OnNewDocument ()
Model * getModel ()
virtual void update ()
Private Member Functions
bool openCFG (const std::string &filename)
bool openADF (const std::string &filename)
Private Member Functions inherited from ModelObserver
virtual ~ModelObserver ()
Private Attributes
Model * model_
Machine Object Model which the document represents.
Detailed Description
An instance of MDFDocument represents one machine object model for the editor.
Part of the wxWindows document/view framework. Opening and saving of documents is passed through this class to the xml reader/writer components. When a new document is created or opened, this class initializes a new model. Document's model can be accessed with the getModel() method.
Definition at line 51 of file MDFDocument.hh.
Constructor & Destructor Documentation
MDFDocument()
MDFDocument::MDFDocument ()
The constructor.
Definition at line 54 of file MDFDocument.cc.
                        : model_(NULL) {
}
~MDFDocument()
MDFDocument::~MDFDocument () virtual
The destructor.
Definition at line 61 of file MDFDocument.cc.
{
    if (model_ != NULL) {
        delete model_;
        model_ = NULL;
    }
}
References model_.
Member Function Documentation
getModel()
Model * MDFDocument::getModel ()
Returns document's model.
Returns
Document's model.
Definition at line 229 of file MDFDocument.cc.
                      {
    return model_;
}
References model_.
Referenced by PasteComponentCmd::Do(), and MDFView::OnUpdate().
OnNewDocument()
bool MDFDocument::OnNewDocument () virtual
Creates a new document.
Returns
True, if a new document was succesfully created, false otherwise.
Definition at line 75 of file MDFDocument.cc.
{
    model_ = new Model();
    model_->addObserver(this);
    return wxDocument::OnNewDocument();
}
References Model::addObserver(), and model_.
OnOpenDocument()
bool MDFDocument::OnOpenDocument (const wxString & fileName) virtual
Opens an .adf or .cfg file. If the opened file extension is .cfg, the architecture file name is read from the configuration.
Parameters
fileName Name of the file to read.
Returns
True if the file was succesfully loaded, false otherwise.
Definition at line 90 of file MDFDocument.cc.
{
    string configExtension = ProDeConstants::PROCESSOR_CONFIG_FILE_EXTENSION;
    string fileExtension =
    FileSystem::fileExtension(WxConversion::toString(fileName));
    if (fileExtension == configExtension) {
    // read .adf filename from the configuration
    return openCFG(WxConversion::toString(fileName));
    } else {
    return openADF(WxConversion::toString(fileName));
    }
    assert(false);
    return false;
}
References assert, FileSystem::fileExtension(), openADF(), openCFG(), ProDeConstants::PROCESSOR_CONFIG_FILE_EXTENSION, and WxConversion::toString().
OnSaveDocument()
bool MDFDocument::OnSaveDocument (const wxString & filename) virtual
Writes the machine object model to an mdf file using the mdf writer component and sets the model unmodified.
Parameters
filename Name of the file into which the Model will be saved.
Definition at line 205 of file MDFDocument.cc.
{
    ADFSerializer writer;
    writer.setDestinationFile(WxConversion::toString(filename));
    try {
        writer.writeMachine(*model_->getMachine());
    } catch (Exception& e) {
        ErrorDialog errorDialog(GetDocumentWindow(),
        WxConversion::toWxString(e.errorMessage()));
        errorDialog.ShowModal();
        return false;
    }
    Modify(false);
    return true;
}
References Exception::errorMessage(), Model::getMachine(), model_, XMLSerializer::setDestinationFile(), WxConversion::toString(), WxConversion::toWxString(), and ADFSerializer::writeMachine().
openADF()
bool MDFDocument::openADF (const std::string & filename) private
Opens an architecture definition file, and creates model of the architecture.
Parameters
filename Architecture file to open.
Returns
True, if the file was succesfully opened, false otherwise.
Definition at line 169 of file MDFDocument.cc.
{
    try {
        model_ = new Model(filename);
        model_->addObserver(this);
    } catch (Exception const& e) {
        // Display an error dialog and return false.
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        boost::format fmt =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_LOADING_FILE);
        fmt % filename;
        wxString message = WxConversion::toWxString(fmt.str());
    message.Append(_T("\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog errorDialog(GetDocumentWindow(), message);
        errorDialog.ShowModal();
        return false;
    }
    // Update document title.
    string title = FileSystem::fileOfPath(filename);
    SetTitle(WxConversion::toWxString(title));
    // File opened succesfully.
    Modify(false);
    UpdateAllViews();
    return true;
}
References Model::addObserver(), Exception::errorMessage(), FileSystem::fileOfPath(), ProDeTextGenerator::instance(), model_, ProDeTextGenerator::MSG_ERROR_LOADING_FILE, Texts::TextGenerator::text(), and WxConversion::toWxString().
Referenced by OnOpenDocument(), and openCFG().
openCFG()
bool MDFDocument::openCFG (const std::string & filename) private
Reads architectrue definition file name from a processor configuration file, and opens the .adf file.
Parameters
filename Configuration file to read.
Returns
True, if the adf defined in the .cfg was succesfully opened, false otherwise.
Definition at line 117 of file MDFDocument.cc.
{
    std::fstream cfgFile(filename.c_str());
    if (cfgFile.fail()) {
    return false;
    }
    ProcessorConfigurationFile cfg(cfgFile);
    cfg.setPCFDirectory(FileSystem::directoryOfPath(filename));
    if (cfg.errors()) {
    // Errors in the .cfg file.
    // Display error strings in an error dialog.
    wxString message;
    for (int i = 0;i < cfg.errorCount();i++) {
        message.Append(WxConversion::toWxString(cfg.errorString(i)));
        message.Append(_T("\n\n"));
    }
    ErrorDialog dialog(GetDocumentWindow(), message);
    dialog.ShowModal();
    return false;
    }
    string adfName;
    try {
    adfName = cfg.architectureName();
    } catch (KeyNotFound& e) {
    wxString message = WxConversion::toWxString(e.errorMessage());
    ErrorDialog dialog(GetDocumentWindow(), message);
    dialog.ShowModal();
    return false;
    }
    if(openADF(adfName)) {
        SetFilename(WxConversion::toWxString(adfName), true);
        return true;
    } else {
        return false;
    }
}
References ProcessorConfigurationFile::architectureName(), FileSystem::directoryOfPath(), ProcessorConfigurationFile::errorCount(), Exception::errorMessage(), ProcessorConfigurationFile::errors(), ProcessorConfigurationFile::errorString(), openADF(), ProcessorConfigurationFile::setPCFDirectory(), and WxConversion::toWxString().
Referenced by OnOpenDocument().
update()
void MDFDocument::update () virtual
Updates the document when the Model changes.
Implements ModelObserver.
Definition at line 238 of file MDFDocument.cc.
                    {
    if (model_->isModified()) {
        Modify(true);
        model_->setNotModified();
    }
    UpdateAllViews();
}
References Model::isModified(), model_, and Model::setNotModified().
Member Data Documentation
model_
Model* MDFDocument::model_ private
Machine Object Model which the document represents.
Definition at line 67 of file MDFDocument.hh.
Referenced by getModel(), OnNewDocument(), OnSaveDocument(), openADF(), update(), and ~MDFDocument().
The documentation for this class was generated from the following files:
MDFDocument.hh
MDFDocument.cc