OpenASIP: NullBusState Class Reference
NullBusState Class Reference
#include <BusState.hh>
Public Member Functions
virtual ~NullBusState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
Public Member Functions inherited from BusState
BusState (int width)
virtual ~BusState ()
void setValueInlined (const SimValue &value)
void clear ()
void setSquashed (bool isSquashed)
bool isSquashed () const
int width () const
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Static Public Member Functions
static NullBusState & instance ()
Private Member Functions
NullBusState ()
NullBusState (const NullBusState &)
Copying not allowed.
NullBusState & operator= (const NullBusState &)
Assignment not allowed.
Static Private Attributes
static NullBusState * instance_ = NULL
Unique instance of NullBusState.
Additional Inherited Members
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Models null BusState object.
Definition at line 85 of file BusState.hh.
Constructor & Destructor Documentation
~NullBusState()
NullBusState::~NullBusState () virtual
Destructor.
Definition at line 128 of file BusState.cc.
{
}
NullBusState() [1/2]
NullBusState::NullBusState () private
Constructor.
Definition at line 122 of file BusState.cc.
                           : BusState(0) {
}
Referenced by instance().
NullBusState() [2/2]
NullBusState::NullBusState (const NullBusState &) private
Copying not allowed.
Member Function Documentation
instance()
NullBusState & NullBusState::instance () static
Returns the instance of NullBusState.
Returns
The instance of NullBusState.
Definition at line 112 of file BusState.cc.
                       {
    if (instance_ == NULL) {
        instance_ = new NullBusState();
    }
    return *instance_;
}
References instance_, and NullBusState().
Referenced by MachineState::busState(), and SimProgramBuilder::processMove().
operator=()
NullBusState & NullBusState::operator= (const NullBusState &) private
Assignment not allowed.
setValue()
void NullBusState::setValue (const SimValue & value) virtual
Aborts the program with error message.
Reimplemented from BusState.
Definition at line 135 of file BusState.cc.
{
    Application::abortWithError("setValue()");
}
value()
const SimValue & NullBusState::value () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from RegisterState.
Definition at line 145 of file BusState.cc.
{
    Application::abortWithError("value()");
    return NullSimValue::instance();
}
References NullSimValue::instance().
Member Data Documentation
instance_
NullBusState * NullBusState::instance_ = NULL static private
Unique instance of NullBusState.
Definition at line 102 of file BusState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
BusState.hh
BusState.cc