OpenASIP: TTAMachine::UnconditionalGuard Class Reference
TTAMachine::UnconditionalGuard Class Reference
#include <Guard.hh>
Public Member Functions
UnconditionalGuard (bool inverted, Bus &parentBus)
UnconditionalGuard (const ObjectState *state, Bus &parentBus)
virtual ~UnconditionalGuard ()
bool isOpposite (const Guard &) const
bool isEqual (const Guard &guard) const
ObjectState * saveState () const
void loadState (const ObjectState *state)
virtual void copyTo (Bus &parentBus) const
Public Member Functions inherited from TTAMachine::Guard
virtual ~Guard ()
virtual Bus * parentBus () const
virtual void setParentBus (Bus *parentBus)
virtual bool isInverted () const
virtual bool isMoreRestrictive (const Guard &guard) const
virtual bool isLessRestrictive (const Guard &guard) const
virtual bool isDisjoint (const Guard &guard) const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_UNCONDITIONAL_GUARD = "unconditional"
ObjectState name for UnconditionalGuard.
Static Public Attributes inherited from TTAMachine::Guard
static const std::string OSNAME_GUARD = "guard"
ObjectState name for guard.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for inverted feature.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Guard
Guard (bool inverted, Bus *parentBus)
Guard (const ObjectState *state, Bus &parentBus)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Always true guard term. Always false if inverted.
Definition at line 180 of file Guard.hh.
Constructor & Destructor Documentation
UnconditionalGuard() [1/2]
TTAMachine::UnconditionalGuard::UnconditionalGuard (bool inverted, Bus & parentBus)
Constructor.
Parameters
inverted If true, the guard condition is always false and vice versa.
parentBus Parent bus component of the guard.
Exceptions
ComponentAlreadyExists If the parent bus already has an equal guard.
Definition at line 615 of file Guard.cc.
    : Guard(inverted, &parentBus) {
    parentBus.addGuard(*this);
}
References TTAMachine::Bus::addGuard(), and TTAMachine::Guard::parentBus().
UnconditionalGuard() [2/2]
TTAMachine::UnconditionalGuard::UnconditionalGuard (const ObjectState * state, Bus & parentBus)
Constructor.
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
parentBus The parent bus of the guard.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 630 of file Guard.cc.
    : Guard(state, parentBus) {
    loadState(state);
    try {
        parentBus.addGuard(*this);
    } catch (const ComponentAlreadyExists&) {
        const string procName = "UnconditionalGuard::UnconditionalGuard";
        MOMTextGenerator textGen;
        format errorMsg = textGen.text(
            MOMTextGenerator::TXT_EQUAL_UNCONDITIONAL_GUARDS);
        errorMsg % parentBus.name();
        throw ObjectStateLoadingException(
            __FILE__,  __LINE__, procName, errorMsg.str());
    }
}
References TTAMachine::Bus::addGuard(), loadState(), TTAMachine::Component::name(), TTAMachine::Guard::parentBus(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_EQUAL_UNCONDITIONAL_GUARDS.
~UnconditionalGuard()
TTAMachine::UnconditionalGuard::~UnconditionalGuard () virtual
Destructor.
Definition at line 649 of file Guard.cc.
{
}
Member Function Documentation
copyTo()
virtual void TTAMachine::UnconditionalGuard::copyTo (Bus & parentBus) const inline virtual
Implements TTAMachine::Guard.
Definition at line 190 of file Guard.hh.
{
        new UnconditionalGuard(isInverted(), parentBus);
    }
References TTAMachine::Guard::isInverted(), and TTAMachine::Guard::parentBus().
isEqual()
bool TTAMachine::UnconditionalGuard::isEqual (const Guard & guard) const virtual
Returns true if the guard is equal with the given guard.
Parameters
guard The other guard.
Returns
True if the guard is equal with the given guard.
Implements TTAMachine::Guard.
Definition at line 660 of file Guard.cc.
{
    const UnconditionalGuard* ucGuard =
        dynamic_cast<const UnconditionalGuard*>(&guard);
    if (ucGuard == NULL) {
        return false;
    } else {
        if (isInverted() == ucGuard->isInverted()) {
            return true;
        } else {
            return false;
        }
    }
}
References TTAMachine::Guard::isInverted().
isOpposite()
bool TTAMachine::UnconditionalGuard::isOpposite (const Guard &) const inline virtual
Implements TTAMachine::Guard.
Definition at line 186 of file Guard.hh.
{ return false; }
loadState()
void TTAMachine::UnconditionalGuard::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Reimplemented from TTAMachine::Guard.
Definition at line 696 of file Guard.cc.
{
    string procName = "UnconditionalGuard::loadState";
    if (state->name() != OSNAME_UNCONDITIONAL_GUARD) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Guard::loadState(state);
}
References TTAMachine::Guard::loadState(), ObjectState::name(), and OSNAME_UNCONDITIONAL_GUARD.
Referenced by UnconditionalGuard().
saveState()
ObjectState * TTAMachine::UnconditionalGuard::saveState () const virtual
Saves the contents to an ObjectState object.
Returns
The created ObjectState object.
Reimplemented from TTAMachine::Guard.
Definition at line 681 of file Guard.cc.
{
    ObjectState* guardState = Guard::saveState();
    guardState->setName(OSNAME_UNCONDITIONAL_GUARD);
    return guardState;
}
References OSNAME_UNCONDITIONAL_GUARD, TTAMachine::Guard::saveState(), and ObjectState::setName().
Member Data Documentation
OSNAME_UNCONDITIONAL_GUARD
const string TTAMachine::UnconditionalGuard::OSNAME_UNCONDITIONAL_GUARD = "unconditional" static
ObjectState name for UnconditionalGuard.
Definition at line 195 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Bus::loadState(), loadState(), and saveState().
The documentation for this class was generated from the following files:
Guard.hh
Guard.cc