OpenASIP: HDBToHtml Class Reference
HDBToHtml Class Reference
#include <HDBToHtml.hh>
Public Member Functions
HDBToHtml (const HDB::HDBManager &hdb)
virtual ~HDBToHtml ()
void fuEntryToHtml (RowID id, std::ostream &stream)
void rfEntryToHtml (RowID id, std::ostream &stream)
void busEntryToHtml (RowID id, std::ostream &stream)
void socketEntryToHtml (RowID id, std::ostream &stream)
void fuArchToHtml (RowID id, std::ostream &stream)
void rfArchToHtml (RowID id, std::ostream &stream)
void fuImplToHtml (RowID id, std::ostream &stream)
void rfImplToHtml (RowID id, std::ostream &stream)
void costFunctionPluginToHtml (RowID id, std::ostream &stream)
void OperationImplementationToHtml (RowID id, std::ostream &stream)
void OperationImplementationResourceToHtml (RowID id, std::ostream &stream)
Static Public Attributes
static const std::string HDB_ROOT
static const std::string FU_ENTRIES = "FU Entries"
static const std::string RF_ENTRIES = "RF Entries"
static const std::string RF_IU_ENTRIES = "RF/IU Entries"
static const std::string BUS_ENTRIES = "Bus Entries"
static const std::string SOCKET_ENTRIES = "Socket Entries"
static const std::string FU_ARCHITECTURES = "Function Units"
static const std::string RF_ARCHITECTURES = "Register Files"
static const std::string FU_IMPLEMENTATIONS = "FU Implementations"
static const std::string RF_IMPLEMENTATIONS = "RF Implementations"
static const std::string COST_PLUGINS = "Cost Function Plugins"
static const std::string OPERATION_IMPLEMENTATIONS
static const std::string OPERATION_IMPLEMENTATION_RESOURCES
Private Attributes
const HDB::HDBManager & hdb_
HDB to create html from.
Detailed Description
Collection of functions for generating html pages displaying information of HDB elements.
Definition at line 47 of file HDBToHtml.hh.
Constructor & Destructor Documentation
HDBToHtml()
HDBToHtml::HDBToHtml (const HDB::HDBManager & hdb)
The Cosntructor.
Parameters
hdb HDB
Definition at line 86 of file HDBToHtml.cc.
                                            :
    hdb_(hdb) {
}
~HDBToHtml()
HDBToHtml::~HDBToHtml () virtual
The Destructor.
Definition at line 93 of file HDBToHtml.cc.
                      {
}
Member Function Documentation
busEntryToHtml()
void HDBToHtml::busEntryToHtml (RowID id, std::ostream & stream)
Generates a html page of a bus entry.
Parameters
id ID of the bus entry.
stream Stream where the html is written to.
Definition at line 250 of file HDBToHtml.cc.
{
    stream << "<html><body><small>" << endl;
    stream << "<b>Bus entry " << id << "</b><br>" << endl;
    stream << "<tr><td align=right><b>Cost estimation data:</b></td><td>";
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.busCostEstimationDataIDs(id);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" <<  COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream << "</small></body></html>" << endl;
}
References HDB::HDBManager::busCostEstimationDataIDs(), COST_PLUGINS, HDB::HDBManager::costEstimationData(), hdb_, CostEstimationData::name(), CostEstimationData::pluginID(), DataObject::stringValue(), and CostEstimationData::value().
Referenced by HDBBrowserInfoPanel::displayBusEntry().
costFunctionPluginToHtml()
void HDBToHtml::costFunctionPluginToHtml (RowID id, std::ostream & stream)
Generates html page of a cost function plugin information.
Parameters
id Row id of the cost estimation plugin.
strem Stream where the html is written to.
Definition at line 900 of file HDBToHtml.cc.
{
    CostFunctionPlugin* plugin = hdb_.costFunctionPluginByID(id);
    stream << "<html><body><small>" << endl;
    stream << "<table bgcolor=#bbbbbb>"<< endl;
    // Plugin name.
    stream << "<tr><td align=right>Name:</td><td>" << plugin->name()
           << "</td></tr>" << endl;
    // Plugin type.
    stream << "<tr><td align=right>Type:</td><td>";
    if (plugin->type() == CostFunctionPlugin::COST_FU) {
        stream << "Function unit cost estimator.";
    } else if (plugin->type() == CostFunctionPlugin::COST_RF) {
        stream << "Register file cost estimator.";
    } else if (plugin->type() == CostFunctionPlugin::COST_DECOMP) {
        stream << "Decompressor cost estimator.";
    } else if (plugin->type() == CostFunctionPlugin::COST_ICDEC) {
        stream << "Interconnection network & decoder cost estimator.";
    } else {
        stream << "unknown";
    }
    stream << "</td></tr>" << endl;
    // Plugin file path.
    stream << "<tr><td align=right>File path:</td><td>"
           << plugin->pluginFilePath() << "</td></tr>" << endl;
    // Plugin description.
    stream << "<tr><td align=right>Description:</td><td>"
           << plugin->description() << "</td></tr>" << endl;
    stream << "</table><br><br>"<< endl;
    // Cost estiamtion data
    stream << "<b>Cost estimation data:</b>" << endl;
    stream << "<table bgcolor=#bbbbbb>"<< endl;
    stream << "<tr><th>Entry type</th><th>Entry ID</th>"
           << "<th>Key</th><th>Value</th></tr>" << endl;
    const std::set<RowID> dataIDs = hdb_.costFunctionPluginDataIDs(id);
    std::set<RowID>::const_iterator iter = dataIDs.begin();
    for (; iter != dataIDs.end(); iter++) {
        CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr>";
        if (data.hasFUReference()) {
            // Function unit reference.
            stream << "<td>FU</td><td><a href=\"/" << FU_ENTRIES << "/"
                   << data.fuReference() << "\">"
                   << data.fuReference() << "</a>";
            stream << "</td>";
        } else if (data.hasRFReference()) {
            // Register file entry reference.
            stream << "<td>RF</td><td><a href=\"/" << RF_ENTRIES << "/"
                   << data.rfReference() << "\">"
                   << data.rfReference() << "</a>";
            stream << "</td>";
        } else if (data.hasBusReference()) {
            // Bus entry reference.
            stream << "<td>Bus</td><td>"
                   << data.busReference() << "</a>";
            stream << "</td>";
        } else if (data.hasSocketReference()) {
            // Socket entry reference.
            stream << "<td>Socket</td><td>"
                   << data.socketReference() << "</a>";
            stream << "</td>";
        } else {
            stream << "<td>-</td><td>-</td>";
        }
        stream << "<td>" << data.name() << "</td><td>"
               << data.value().stringValue() << "</td></tr>" <<  endl;
    }
    stream << "</table>"<< endl;
    stream << "</small></body></html>" << endl;
    delete plugin;
}
References CostEstimationData::busReference(), HDB::CostFunctionPlugin::COST_DECOMP, HDB::CostFunctionPlugin::COST_FU, HDB::CostFunctionPlugin::COST_ICDEC, HDB::CostFunctionPlugin::COST_RF, HDB::HDBManager::costEstimationData(), HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginDataIDs(), HDB::CostFunctionPlugin::description(), FU_ENTRIES, CostEstimationData::fuReference(), CostEstimationData::hasBusReference(), CostEstimationData::hasFUReference(), CostEstimationData::hasRFReference(), CostEstimationData::hasSocketReference(), hdb_, CostEstimationData::name(), HDB::CostFunctionPlugin::name(), HDB::CostFunctionPlugin::pluginFilePath(), RF_ENTRIES, CostEstimationData::rfReference(), CostEstimationData::socketReference(), DataObject::stringValue(), HDB::CostFunctionPlugin::type(), and CostEstimationData::value().
Referenced by HDBBrowserInfoPanel::displayCostFunctionPlugin().
fuArchToHtml()
void HDBToHtml::fuArchToHtml (RowID id, std::ostream & stream)
Generates a html page of a function unit architecture.
Parameters
id ID of the FU architecture.
stream Stream where the html is written to.
Definition at line 328 of file HDBToHtml.cc.
{
    const FUArchitecture* arch = hdb_.fuArchitectureByID(id);
    const FunctionUnit& fu = arch->architecture();
    stream <<  "<html><body><small>" << endl;
    //
    //  PORTS
    //
    stream << "<b>Ports:</b><br>" << endl;
    stream << "<table bgcolor=#bbbbbb>" << endl;
    stream << "<tr><th>Name</th><th>Width</th>"
           << "<th>Triggering</th>"
           << "<th>Opcode</th>"
           << "<th>Guard</th></tr>"
           << endl;
    for (int i = 0; i < fu.portCount(); i++) {
        const BaseFUPort& port = *fu.port(i);
        stream << "<tr><td align=left>" << port.name() << "</td>";
        if (arch->hasParameterizedWidth(port.name())) {
            stream << "<td align=right>param</td>";
        } else {
            stream << "<td align=right>" << port.width() << "</td>";
        }
        if (port.isTriggering()) {
            stream << "<td align=center><font color=#009900>yes</font></td>";
        } else {
            stream << "<td align=center><font color=#ff0000>no</font></td>";
        }
        if (port.isOpcodeSetting()) {
            stream << "<td align=center><font color=#009900>yes</font></td>";
        } else {
            stream << "<td align=center><font color=#ff0000>no</font></td>";
        }
        if (arch->hasGuardSupport(port.name())) {
            stream << "<td align=center><font color=#009900>yes</font></td>";
        } else {
            stream << "<td align=center><font color=#ff0000>no</font></td>";
        }
        stream << "</tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    //
    // OPERATIONS
    //
    stream << "<b>Operations:</b><br><br>" << endl;
    for (int i = 0; i < fu.operationCount(); i++) {
        const HWOperation& operation = *fu.operation(i);
        const ExecutionPipeline& pipeline = *operation.pipeline();
        stream << "<b>" << operation.name() << "</b><br>" << endl;
        stream << "Latency: " << operation.latency() << endl;
        stream << "<br>" << endl;
        stream << "<table><tr><td valing=top>" << endl;
        stream << "<table bgcolor=#bbbbbb><tr><th>operand</th><th>port</th>";
        for (int cycle = 0; cycle < operation.latency(); cycle++) {
            stream << "<th width=20>" << cycle << "</th>";
        }
        stream << "</tr>" << endl;
        // Reads operands.
        ExecutionPipeline::OperandSet read = pipeline.readOperands();
        ExecutionPipeline::OperandSet::iterator iter = read.begin();
        for (; iter != read.end(); iter++) {
            stream << "<tr><td>" << *iter << "</td><td>"
                   << operation.port(*iter)->name() << "</td>";
            for (int cycle = 0; cycle < operation.latency(); cycle++) {
                if (ContainerTools::containsValue(
                        pipeline.readOperands(cycle), *iter)) {
                    stream << "<td align=center><b>R</b></td>";
                } else {
                    stream << "<td></td>";
                }
            }
            stream << "</tr>" << endl;
        }
        // Written operands.
        ExecutionPipeline::OperandSet written = pipeline.writtenOperands();
        iter = written.begin();
        for (; iter != written.end(); iter++) {
            stream << "<tr><td>" << *iter << "</td><td>"
                   << operation.port(*iter)->name() << "</td>";
            for (int cycle = 0; cycle < operation.latency(); cycle++) {
                if (ContainerTools::containsValue(
                        pipeline.writtenOperands(cycle), *iter)) {
                    stream << "<td align=center><b>W</b></td>";
                } else {
                    stream << "<td></td>";
                }
            }
            stream << "</tr>" << endl;
        }
        stream << "</table></td>" << endl;
        stream << "<td valign=top><table bgcolor=#bbbbbb>"
               << "<tr><th>resource</th>";
        for (int cycle = 0; cycle < operation.latency(); cycle++) {
            stream << "<th width=20>" << cycle << "</th>";
        }
        stream << "</tr>" << endl;
        // Resources used.
        for (int r = 0; r < fu.pipelineElementCount(); r++) {
            const PipelineElement& res = *fu.pipelineElement(r);
            stream << "<tr><td>" << res.name() << "</td>";
            for (int cycle = 0; cycle < operation.latency(); cycle++) {
                if (pipeline.isResourceUsed(res.name(), cycle)) {
                    stream << "<td align=center><b>X</b></td>";
                } else {
                    stream << "<td></td>";
                }
            }
            stream << "</tr>" << endl;
        }
        stream << "</table></td></tr></table><br><br>" << endl;
    }
    stream << "</small></body></html>" << endl;
    delete arch;
}
References HDB::FUArchitecture::architecture(), ContainerTools::containsValue(), HDB::HDBManager::fuArchitectureByID(), HDB::FUArchitecture::hasGuardSupport(), HDB::FUArchitecture::hasParameterizedWidth(), hdb_, TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::ExecutionPipeline::isResourceUsed(), TTAMachine::BaseFUPort::isTriggering(), TTAMachine::HWOperation::latency(), TTAMachine::HWOperation::name(), TTAMachine::PipelineElement::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::HWOperation::pipeline(), TTAMachine::FunctionUnit::pipelineElement(), TTAMachine::FunctionUnit::pipelineElementCount(), TTAMachine::FunctionUnit::port(), TTAMachine::HWOperation::port(), TTAMachine::Unit::portCount(), TTAMachine::ExecutionPipeline::readOperands(), TTAMachine::BaseFUPort::width(), and TTAMachine::ExecutionPipeline::writtenOperands().
Referenced by HDBBrowserInfoPanel::displayFUArchitecture().
fuEntryToHtml()
void HDBToHtml::fuEntryToHtml (RowID id, std::ostream & stream)
Generates a html page of a function unit entry->
Parameters
id ID of the FU entry in the HDB.
stream Stream where the html is written to.
Definition at line 103 of file HDBToHtml.cc.
{
    const HDB::FUEntry* entry = hdb_.fuByEntryID(id);
    stream << "<html><body><small>" << endl;
    stream << "<b>Function unit entry " << entry->id() << "</b><br>" << endl;
    stream << "<table>" << endl;
    stream << "<tr><td align=right><b>Architecture:</b></td><td>";
    if (entry->hasArchitecture()) {
        stream << "<a href=\"/" << FU_ARCHITECTURES << "/"
               << entry->architecture().id() << "\">"
               << entry->architecture().id() << "</a>"
               << "</td></tr>" << endl;
    } else {
        stream << "-</td></tr>";
    }
    stream << "<tr><td align=right><b>Implementation:</b></td><td>";
    if (entry->hasImplementation()) {
        stream << "<a href=\"/" << FU_IMPLEMENTATIONS << "/"
               << entry->implementation().id() << "\">"
               << entry->implementation().moduleName()
               << "</a></td></tr>" << endl;
    } else {
        stream << "-</td></tr>" << endl;
    }
    stream << "<tr><td align=right><b>Cost function plugin:</b></td><td>";
    if (entry->hasCostFunction()) {
        const CostFunctionPlugin& plugin = entry->costFunction();
        stream << "<a href=\"/" << COST_PLUGINS << "/"
               << plugin.id() << "\">"
               << plugin.name()
               << "</a></td></tr>" << endl;
    } else {
        stream << "-</td></tr>" << endl;
    }
    stream << "</table>";
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.fuCostEstimationDataIDs(id);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" <<  COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream << "</small></body></html>" << endl;
    delete entry;
}
References HDB::FUEntry::architecture(), COST_PLUGINS, HDB::HDBManager::costEstimationData(), HDB::HDBEntry::costFunction(), FU_ARCHITECTURES, FU_IMPLEMENTATIONS, HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuCostEstimationDataIDs(), HDB::FUEntry::hasArchitecture(), HDB::HDBEntry::hasCostFunction(), HDB::FUEntry::hasImplementation(), hdb_, HDB::CostFunctionPlugin::id(), HDB::HDBEntry::id(), HWBlockArchitecture::id(), HDB::HWBlockImplementation::id(), HDB::FUEntry::implementation(), HDB::HWBlockImplementation::moduleName(), CostEstimationData::name(), HDB::CostFunctionPlugin::name(), CostEstimationData::pluginID(), DataObject::stringValue(), and CostEstimationData::value().
Referenced by HDBBrowserInfoPanel::displayFUEntry().
fuImplToHtml()
void HDBToHtml::fuImplToHtml (RowID id, std::ostream & stream)
Generates a html page of a function unit implementation.
Parameters
id ID of the fu implementation.
stream Stream where the html is written to.
Definition at line 539 of file HDBToHtml.cc.
{
    RowID entryID = hdb_.fuEntryIDOfImplementation(id);
    const HDB::FUEntry* entry = hdb_.fuByEntryID(entryID);
    const HDB::FUImplementation& impl = entry->implementation();
    stream << "<html><body>" << endl;
    stream << "<small><table>" << endl;
    stream << "<tr><td align=right><b>Module name:</b></td><td align=left>"
           << impl.moduleName() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Opcode port:</b></td><td align=left>"
           << impl.opcodePort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Clock port:</b></td><td align=left>"
           << impl.clkPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Reset port:</b></td><td align=left>"
           << impl.rstPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Global lock port:</b></td>"
           << "<td align=left>"
           << impl.glockPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Global lock req. port:</b></td>"
           << "<td align=left>"
           << impl.glockReqPort() << "</td></tr>" << endl;
    stream << "</table><br><br>" << endl;
    // Architecture ports.
    if (impl.architecturePortCount() > 0) {
        stream << "<b>Architecture ports:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th>"
               << "<th>Architecture port</th>"
               << "<th>Load port</th>"
               << "<th>Guard port</th>"
               << "<th>Width formula</th></tr>" << endl;
    } else {
        stream << "No architecture ports.<br>" << endl;
    }
    for (int i = 0; i < impl.architecturePortCount(); i++) {
        const HDB::FUPortImplementation& port = impl.architecturePort(i);
        stream << "<tr><td>" << port.name() << "</td>"
               << "<td>" << port.architecturePort() << "</td>"
               << "<td>" << port.loadPort() << "</td>"
               << "<td>" << port.guardPort() << "</td>"
               << "</td><td>" << port.widthFormula() << "</td></td>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Opcodes
    if (impl.opcodeCount() > 0) {
        stream << "<b>Opcodes:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Operation</th><th>Opcode</th></tr>" << endl;
    } else {
        stream << "No opcodes.<br>" << endl;
    }
    for (int i = 0; i < impl.opcodeCount(); i++) {
        stream << "<tr><td>" << impl.opcodeOperation(i) << "</td>"
               << "<td align=center>" << impl.opcode(impl.opcodeOperation(i))
               << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // External ports
    if (impl.externalPortCount() > 0) {
        stream << "<b>External ports:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Direction</th><th>Width formula</th>"
               << "<th>Parameter dependencies</th>"
               << "<th>Description</th></tr>" << endl;
    } else {
        stream << "No external ports.<br>" << endl;
    }
    for (int i = 0; i < impl.externalPortCount(); i++) {
        const HDB::FUExternalPort& port = impl.externalPort(i);
        stream << "<tr><td>" << port.name() << "</td><td align=center>";
        if (port.direction() == HDB::IN) {
            stream << "in";
        } else if (port.direction() == HDB::OUT) {
            stream << "out";
        } else if (port.direction() == HDB::BIDIR) {
            stream << "bidir";
        }
        stream << "</td><td>" << port.widthFormula() << "</td>";
        stream << "<td>";
        for (int dep = 0; dep < port.parameterDependencyCount(); dep++) {
            if (dep > 0) {
                stream << ", ";
            }
            stream << port.parameterDependency(dep);
        }
        stream << "</td><td>" << port.description() << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Parameters
    if (impl.parameterCount() > 0) {
        stream << "<b>Parameters:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Type</th><th>Value</th></tr>" << endl;
    } else {
        stream << "No parameters.<br>" << endl;
    }
    for (int i = 0; i < impl.parameterCount(); i++) {
        const HDB::FUImplementation::Parameter& parameter = impl.parameter(i);
        stream << "<tr><td>" << parameter.name << "</td>"
               << "<td align=center>" << parameter.type << "</td>"
               << "<td>" << parameter.value << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Implementation files
    if (impl.implementationFileCount() > 0) {
        stream << "<b>Implementation files:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Path</th><th>Format</th></tr>" << endl;
    } else {
        stream << "No implementation files.<br>" << endl;
    }
    for (int i = 0; i < impl.implementationFileCount(); i++) {
        const HDB::BlockImplementationFile& file = impl.file(i);
        stream << "<tr><td>" << file.pathToFile() << "</td>"
               << "<td align=center>";
        if (file.format() == HDB::BlockImplementationFile::VHDL) {
            stream << "VHDL";
        }else
        if (file.format() == HDB::BlockImplementationFile::Verilog) {
            stream << "Verilog";
        }
        stream << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.fuCostEstimationDataIDs(entryID);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" <<  COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream << "</small></body></html>" << endl;
    delete entry;
}
References HDB::FUPortImplementation::architecturePort(), HDB::FUImplementation::architecturePort(), HDB::FUImplementation::architecturePortCount(), HDB::BIDIR, HDB::HWBlockImplementation::clkPort(), COST_PLUGINS, HDB::HDBManager::costEstimationData(), HDB::ExternalPort::description(), HDB::ExternalPort::direction(), HDB::FUImplementation::externalPort(), HDB::FUImplementation::externalPortCount(), HDB::HWBlockImplementation::file(), HDB::BlockImplementationFile::format(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuCostEstimationDataIDs(), HDB::HDBManager::fuEntryIDOfImplementation(), HDB::HWBlockImplementation::glockPort(), HDB::FUImplementation::glockReqPort(), HDB::FUPortImplementation::guardPort(), hdb_, HDB::FUEntry::implementation(), HDB::HWBlockImplementation::implementationFileCount(), HDB::IN, HDB::PortImplementation::loadPort(), HDB::HWBlockImplementation::moduleName(), CostEstimationData::name(), HDB::ExternalPort::name(), HDB::Parameter::name, HDB::PortImplementation::name(), HDB::FUImplementation::opcode(), HDB::FUImplementation::opcodeCount(), HDB::FUImplementation::opcodeOperation(), HDB::FUImplementation::opcodePort(), HDB::OUT, HDB::FUImplementation::parameter(), HDB::FUImplementation::parameterCount(), HDB::ExternalPort::parameterDependency(), HDB::ExternalPort::parameterDependencyCount(), HDB::BlockImplementationFile::pathToFile(), CostEstimationData::pluginID(), HDB::HWBlockImplementation::rstPort(), DataObject::stringValue(), HDB::Parameter::type, CostEstimationData::value(), HDB::Parameter::value, HDB::BlockImplementationFile::Verilog, HDB::BlockImplementationFile::VHDL, HDB::ExternalPort::widthFormula(), and HDB::FUPortImplementation::widthFormula().
Referenced by HDBBrowserInfoPanel::displayFUImplementation().
OperationImplementationResourceToHtml()
void HDBToHtml::OperationImplementationResourceToHtml (RowID id, std::ostream & stream)
Definition at line 1003 of file HDBToHtml.cc.
{
    OperationImplementationResource res
        = hdb_.OperationImplementationResourceByID(id);
    stream << "<html><body>";
    stream << "<b>Operation Implementation Resource</b><br/>";
    stream << "name : " << res.name << "<br/>";
    for (const auto& sim : res.simFiles) {
        stream << "simulation file : " << sim << "<br/>";
    }
    for (const auto& syn : res.synFiles) {
        stream << "synthesis file : " << syn << "<br/>";
    }
    stream << "</body></html>";
}
References hdb_, HDB::OperationImplementationResource::name, HDB::HDBManager::OperationImplementationResourceByID(), HDB::OperationImplementationResource::simFiles, and HDB::OperationImplementationResource::synFiles.
Referenced by HDBBrowserInfoPanel::displayOperationImplementationResource().
OperationImplementationToHtml()
void HDBToHtml::OperationImplementationToHtml (RowID id, std::ostream & stream)
Definition at line 986 of file HDBToHtml.cc.
{
    OperationImplementation op = hdb_.OperationImplementationByID(id);
    stream << "<html><body>";
    stream << "<b>Operation Implementation</b><br/>";
    stream << "operation : " << op.name << "<br/>";
    stream << "implementation (VHDL) : " << op.implFileVhdl << "<br/>";
    stream << "implementation (Verilog) : " << op.implFileVerilog << "<br/>";
    for(const auto& r : op.resources) {
        stream << "resource : " << r.name
               << " * " << r.count
               << "<br/>";
    }
    stream << "</body></html>\n";
}
References hdb_, HDB::OperationImplementation::implFileVerilog, HDB::OperationImplementation::implFileVhdl, HDB::OperationImplementation::name, HDB::HDBManager::OperationImplementationByID(), and HDB::OperationImplementation::resources.
Referenced by HDBBrowserInfoPanel::displayOperationImplementation().
rfArchToHtml()
void HDBToHtml::rfArchToHtml (RowID id, std::ostream & stream)
Generates a html page of a register file architecture.
Parameters
id ID of the register file architecture.
stream Stream where the html is written to.
Definition at line 469 of file HDBToHtml.cc.
{
    const HDB::RFArchitecture* arch = hdb_.rfArchitectureByID(id);
    stream <<  "<html><body><small>" << endl;
    stream << "<table>" << endl;
    // Width
    stream << "<tr><td align=right><b>Width:</b></td>";
    if (arch->hasParameterizedWidth()) {
        stream << "<td>param</td>";
    } else {
        stream << "<td align=center>" << arch->width() << "</td>";
    }
    stream << "</tr>" << endl;
    // Size
    stream << "<tr><td align=right><b>Size:</b></td>";
    if (arch->hasParameterizedSize()) {
        stream << "<td align=center>param</td>";
    } else {
        stream << "<td align=center>" << arch->size() << "</td>";
    }
    stream << "</tr>" << endl;
    stream << "<tr><td align=right><b>Read ports:</b></td><td align=center>"
           << arch->readPortCount() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Write ports:</b></td><td align=center>"
           << arch->writePortCount() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Bidirectional ports:</b></td>"
           << "<td align=center>" << arch->bidirPortCount() << "</td></tr>"
           << endl;
    stream << "<tr><td align=right><b>Max reads:</b></td><td align=center>"
           << arch->maxReads() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Max Writes:</b></td><td align=center>"
           << arch->maxWrites() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Latency:</b></td><td align=center>"
           << arch->latency() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Guard support:</b></td>";
    if (arch->hasGuardSupport()) {
        stream << "<td align=center>yes</td></tr>";
        stream << "<tr><td align=right><b>Guard Latency:</b></td>"
           << "<td align=center>" << arch->guardLatency()
           << "</td></tr>" << endl;
    } else {
        stream << "<td align=center>no</td></tr>";
    }
    stream << "<tr><td align=right><b>Zero Register:</b></td><td" <<
    " align=center>" << arch->zeroRegister() << "</td></tr>" << endl;
    stream << "</table></small><br>" << endl;
    stream << "</body></html>" << endl;
    delete arch;
}
References HDB::RFArchitecture::bidirPortCount(), HDB::RFArchitecture::guardLatency(), HDB::RFArchitecture::hasGuardSupport(), HDB::RFArchitecture::hasParameterizedSize(), HDB::RFArchitecture::hasParameterizedWidth(), hdb_, HDB::RFArchitecture::latency(), HDB::RFArchitecture::maxReads(), HDB::RFArchitecture::maxWrites(), HDB::RFArchitecture::readPortCount(), HDB::HDBManager::rfArchitectureByID(), HDB::RFArchitecture::size(), HDB::RFArchitecture::width(), HDB::RFArchitecture::writePortCount(), and HDB::RFArchitecture::zeroRegister().
Referenced by HDBBrowserInfoPanel::displayRFArchitecture().
rfEntryToHtml()
void HDBToHtml::rfEntryToHtml (RowID id, std::ostream & stream)
Generates a html page of a register file entry.
Parameters
id ID of the register file entry.
stream Stream where the html is written to.
Definition at line 177 of file HDBToHtml.cc.
{
    const HDB::RFEntry* entry = hdb_.rfByEntryID(id);
    stream << "<html><body><small>" << endl;
    stream << "<b>Register file entry " << entry->id() << "</b><br>" << endl;
    stream << "<table>" << endl;
    stream << "<tr><td>Architecture:</td><td>";
    if (entry->hasArchitecture()) {
        stream << "<a href=\"/" << RF_ARCHITECTURES << "/"
               << entry->architecture().id() << "\">"
               << entry->architecture().id() << "</a>"
               << "</td></tr>" << endl;
    } else {
        stream << "-</td></tr>";
    }
    stream << "<tr><td><b>Implementation:</b></td><td>";
    if (entry->hasImplementation()) {
        stream << "<td><a href=\"/" << RF_IMPLEMENTATIONS << "/"
               << entry->implementation().id() << "\">"
               << entry->implementation().moduleName() << "</a>"
               << "</td></tr>" << endl;
    } else {
        stream << "-</td></tr>" << endl;
    }
    stream << "<tr><td align=right><b>Cost function plugin:</b></td><td>";
    if (entry->hasCostFunction()) {
        const CostFunctionPlugin& plugin = entry->costFunction();
        stream << "<a href=\"/" << COST_PLUGINS << "/"
               << plugin.id() << "\">"
               << plugin.name()
               << "</a></td></tr>" << endl;
    } else {
        stream << "-</td></tr>" << endl;
    }
    stream << "</table>";
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.rfCostEstimationDataIDs(id);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" <<  COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream << "</small></body></html>" << endl;
    delete entry;
}
References HDB::RFEntry::architecture(), COST_PLUGINS, HDB::HDBManager::costEstimationData(), HDB::HDBEntry::costFunction(), HDB::RFEntry::hasArchitecture(), HDB::HDBEntry::hasCostFunction(), HDB::RFEntry::hasImplementation(), hdb_, HDB::CostFunctionPlugin::id(), HDB::HDBEntry::id(), HWBlockArchitecture::id(), HDB::HWBlockImplementation::id(), HDB::RFEntry::implementation(), HDB::HWBlockImplementation::moduleName(), CostEstimationData::name(), HDB::CostFunctionPlugin::name(), CostEstimationData::pluginID(), RF_ARCHITECTURES, RF_IMPLEMENTATIONS, HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfCostEstimationDataIDs(), DataObject::stringValue(), and CostEstimationData::value().
Referenced by HDBBrowserInfoPanel::displayRFEntry().
rfImplToHtml()
void HDBToHtml::rfImplToHtml (RowID id, std::ostream & stream)
Generates a html page of a register file implementation.
Parameters
id ID of the RF implementation.
stream Stream where the html is written to.
Definition at line 720 of file HDBToHtml.cc.
{
    RowID entryID = hdb_.rfEntryIDOfImplementation(id);
    const RFEntry* entry = hdb_.rfByEntryID(entryID);
    const RFImplementation& impl = entry->implementation();
    stream << "<html><body>" << endl;
    stream << "<small><table>" << endl;
    stream << "<tr><td align=right><b>Module name:</b></td><td align=center>"
           << impl.moduleName() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Clock port:</b></td><td align=center>"
           << impl.clkPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Reset port:</b></td><td align=center>"
           << impl.rstPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Global lock port:</b></td>"
           << "<td align=center>"
           << impl.glockPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Guard port:</b></td>"
           << "<td align=center>"
           << impl.guardPort() << "</td></tr>" << endl;
    stream << "<tr><td align=right><b>Size parameter:</b></td>"
           << "<td align=center>" << impl.sizeParameter() << "</td></tr>"
           << endl;
    stream << "<tr><td align=right><b>Width parameter:</b></td>"
           << "<td align=center>" << impl.widthParameter() << "</td></tr>"
           << endl;
    std::string sac_flag(impl.separateAddressCycleParameter() ?
        "true" : "false");
    stream << "<tr><td align=right><b>Separate address cycle:</b></td>"
           << "<td align=center>"
           << sac_flag << "</td></tr>" << endl;
    stream << "</table><br><br>" << endl;
    // Ports
    if (impl.portCount() > 0) {
        stream << "<b>Ports:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th>"
               << "<th>Direction</th>"
               << "<th>Load port</th>"
               << "<th>Opcode port</th>"
               << "<th>Opcode port width formula</th></tr>" << endl;
    } else {
        stream << "No ports.<br>" << endl;
    }
    for (int i = 0; i < impl.portCount(); i++) {
        const HDB::RFPortImplementation& port = impl.port(i);
        stream << "<tr><td>" << port.name() << "</td><td align=center>";
        if (port.direction() == HDB::IN) {
            stream << "in";
        } else if (port.direction() == HDB::OUT) {
            stream << "out";
        } else if (port.direction() == HDB::BIDIR) {
            stream << "bidir";
        }
        stream << "</td><td>" << port.loadPort() << "</td>"
               << "<td>" << port.opcodePort() << "</td>"
               << "</td><td>" << port.opcodePortWidthFormula()
               << "</td></td>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // External ports
    if (impl.externalPortCount() > 0) {
        stream << "<b>External ports:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Direction</th><th>Width formula</th>"
            << "<th>Parameter dependencies</th>"
            << "<th>Description</th></tr>" << endl;
    } else {
        stream << "No external ports.<br>" << endl;
    }
    for (int i = 0; i < impl.externalPortCount(); i++) {
        const HDB::RFExternalPort& port = impl.externalPort(i);
        stream << "<tr><td>" << port.name() << "</td><td align=center>";
        if (port.direction() == HDB::IN) {
            stream << "in";
        } else if (port.direction() == HDB::OUT) {
            stream << "out";
        } else if (port.direction() == HDB::BIDIR) {
            stream << "bidir";
        }
        stream << "</td><td>" << port.widthFormula() << "</td>";
        stream << "<td>";
        for (int dep = 0; dep < port.parameterDependencyCount(); dep++) {
            if (dep > 0) {
                stream << ", ";
            }
            stream << port.parameterDependency(dep);
        }
        stream << "</td><td>" << port.description() << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Parameters
    if (impl.parameterCount() > 0) {
        stream << "<b>Parameters:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Type</th><th>Value</th></tr>" << endl;
    } else {
        stream << "No parameters.<br>" << endl;
    }
    for (int i = 0; i < impl.parameterCount(); i++) {
        const HDB::RFImplementation::Parameter& parameter = impl.parameter(i);
        stream << "<tr><td>" << parameter.name << "</td>"
            << "<td align=center>" << parameter.type << "</td>"
            << "<td>" << parameter.value << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Implementation files
    if (impl.implementationFileCount() > 0) {
        stream << "<b>Implementation files:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Path</th><th>Format</th></tr>" << endl;
    } else {
        stream << "No implementation files.<br>" << endl;
    }
    for (int i = 0; i < impl.implementationFileCount(); i++) {
        const HDB::BlockImplementationFile& file = impl.file(i);
        stream << "<tr><td>" << file.pathToFile() << "</td>"
               << "<td align=center>";
        if (file.format() == HDB::BlockImplementationFile::VHDL) {
            stream << "VHDL";
        }else
        if (file.format() == HDB::BlockImplementationFile::Verilog) {
            stream << "Verilog";
        }
        stream << "</td></tr>" << endl;
    }
    stream << "</table><br><br>" << endl;
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.rfCostEstimationDataIDs(entryID);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" << COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream <<  "</small></body></html>" << endl;
    delete entry;
}
References HDB::BIDIR, HDB::HWBlockImplementation::clkPort(), COST_PLUGINS, HDB::HDBManager::costEstimationData(), HDB::ExternalPort::description(), HDB::ExternalPort::direction(), HDB::RFPortImplementation::direction(), HDB::RFImplementation::externalPort(), HDB::RFImplementation::externalPortCount(), HDB::HWBlockImplementation::file(), HDB::BlockImplementationFile::format(), HDB::HWBlockImplementation::glockPort(), HDB::RFImplementation::guardPort(), hdb_, HDB::RFEntry::implementation(), HDB::HWBlockImplementation::implementationFileCount(), HDB::IN, HDB::PortImplementation::loadPort(), HDB::HWBlockImplementation::moduleName(), CostEstimationData::name(), HDB::ExternalPort::name(), HDB::Parameter::name, HDB::PortImplementation::name(), HDB::RFPortImplementation::opcodePort(), HDB::RFPortImplementation::opcodePortWidthFormula(), HDB::OUT, HDB::RFImplementation::parameter(), HDB::RFImplementation::parameterCount(), HDB::ExternalPort::parameterDependency(), HDB::ExternalPort::parameterDependencyCount(), HDB::BlockImplementationFile::pathToFile(), CostEstimationData::pluginID(), HDB::RFImplementation::port(), HDB::RFImplementation::portCount(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfCostEstimationDataIDs(), HDB::HDBManager::rfEntryIDOfImplementation(), HDB::HWBlockImplementation::rstPort(), HDB::RFImplementation::separateAddressCycleParameter(), HDB::RFImplementation::sizeParameter(), DataObject::stringValue(), HDB::Parameter::type, CostEstimationData::value(), HDB::Parameter::value, HDB::BlockImplementationFile::Verilog, HDB::BlockImplementationFile::VHDL, HDB::ExternalPort::widthFormula(), and HDB::RFImplementation::widthParameter().
Referenced by HDBBrowserInfoPanel::displayRFImplementation().
socketEntryToHtml()
void HDBToHtml::socketEntryToHtml (RowID id, std::ostream & stream)
Generates a html page of a socket entry.
Parameters
id ID of the sovket entry.
stream Stream where the html is written to.
Definition at line 289 of file HDBToHtml.cc.
{
    stream << "<html><body><small>" << endl;
    stream << "<b>Socket entry " << id << "</b><br>" << endl;
    stream << "<tr><td align=right><b>Cost estimation data:</b></td><td>";
    // Cost estimation data
    const std::set<RowID> costDataIDs = hdb_.socketCostEstimationDataIDs(id);
    if (!costDataIDs.empty()) {
        stream << "<b>Cost estimation data:</b>" << endl;
        stream << "<table bgcolor=#bbbbbb>" << endl;
        stream << "<tr><th>Name</th><th>Value</th>"
               << "<th>Plugin</th></tr>" << endl;
    } else {
        stream << "No cost estimation data.<br>" << endl;
    }
    std::set<RowID>::const_iterator iter = costDataIDs.begin();
    for (; iter != costDataIDs.end(); iter++) {
        const CostEstimationData data = hdb_.costEstimationData(*iter);
        stream << "<tr><td>" << data.name() << "</td>"
               << "<td align=right>";
        stream << data.value().stringValue();
        stream << "</td><td align=center><a href=\"/" <<  COST_PLUGINS
               << "/" << data.pluginID() << "\">"
               << data.pluginID() << "</a></td></tr>" << endl;
    }
    stream << "</table>" << endl;
    stream << "</small></body></html>" << endl;
}
References COST_PLUGINS, HDB::HDBManager::costEstimationData(), hdb_, CostEstimationData::name(), CostEstimationData::pluginID(), HDB::HDBManager::socketCostEstimationDataIDs(), DataObject::stringValue(), and CostEstimationData::value().
Referenced by HDBBrowserInfoPanel::displaySocketEntry().
Member Data Documentation
BUS_ENTRIES
const std::string HDBToHtml::BUS_ENTRIES = "Bus Entries" static
Definition at line 68 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::openLink(), and HDBBrowserWindow::update().
COST_PLUGINS
const std::string HDBToHtml::COST_PLUGINS = "Cost Function Plugins" static
Definition at line 74 of file HDBToHtml.hh.
Referenced by busEntryToHtml(), fuEntryToHtml(), fuImplToHtml(), HDBBrowserWindow::openLink(), rfEntryToHtml(), rfImplToHtml(), socketEntryToHtml(), and HDBBrowserWindow::update().
FU_ARCHITECTURES
const std::string HDBToHtml::FU_ARCHITECTURES = "Function Units" static
Definition at line 70 of file HDBToHtml.hh.
Referenced by fuEntryToHtml(), HDBBrowserWindow::openLink(), and HDBBrowserWindow::update().
FU_ENTRIES
const std::string HDBToHtml::FU_ENTRIES = "FU Entries" static
Definition at line 65 of file HDBToHtml.hh.
Referenced by costFunctionPluginToHtml(), HDBBrowserWindow::openLink(), and HDBBrowserWindow::update().
FU_IMPLEMENTATIONS
const std::string HDBToHtml::FU_IMPLEMENTATIONS = "FU Implementations" static
Definition at line 72 of file HDBToHtml.hh.
Referenced by fuEntryToHtml(), and HDBBrowserWindow::openLink().
hdb_
const HDB::HDBManager& HDBToHtml::hdb_ private
HDB to create html from.
Definition at line 80 of file HDBToHtml.hh.
Referenced by busEntryToHtml(), costFunctionPluginToHtml(), fuArchToHtml(), fuEntryToHtml(), fuImplToHtml(), OperationImplementationResourceToHtml(), OperationImplementationToHtml(), rfArchToHtml(), rfEntryToHtml(), rfImplToHtml(), and socketEntryToHtml().
HDB_ROOT
const std::string HDBToHtml::HDB_ROOT static
Definition at line 64 of file HDBToHtml.hh.
OPERATION_IMPLEMENTATION_RESOURCES
const std::string HDBToHtml::OPERATION_IMPLEMENTATION_RESOURCES static
Initial value:
=
    "Operation Implementation Resources"
Definition at line 76 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::onItemSelected(), and HDBBrowserWindow::update().
OPERATION_IMPLEMENTATIONS
const std::string HDBToHtml::OPERATION_IMPLEMENTATIONS static
Initial value:
=
    "Operation Implementations"
Definition at line 75 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::onItemSelected(), and HDBBrowserWindow::update().
RF_ARCHITECTURES
const std::string HDBToHtml::RF_ARCHITECTURES = "Register Files" static
Definition at line 71 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::openLink(), rfEntryToHtml(), and HDBBrowserWindow::update().
RF_ENTRIES
const std::string HDBToHtml::RF_ENTRIES = "RF Entries" static
Definition at line 66 of file HDBToHtml.hh.
Referenced by costFunctionPluginToHtml(), and HDBBrowserWindow::openLink().
RF_IMPLEMENTATIONS
const std::string HDBToHtml::RF_IMPLEMENTATIONS = "RF Implementations" static
Definition at line 73 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::openLink(), and rfEntryToHtml().
RF_IU_ENTRIES
const std::string HDBToHtml::RF_IU_ENTRIES = "RF/IU Entries" static
Definition at line 67 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::update().
SOCKET_ENTRIES
const std::string HDBToHtml::SOCKET_ENTRIES = "Socket Entries" static
Definition at line 69 of file HDBToHtml.hh.
Referenced by HDBBrowserWindow::openLink(), and HDBBrowserWindow::update().
The documentation for this class was generated from the following files:
HDBToHtml.hh
HDBToHtml.cc