OpenASIP: TTAProgram::GlobalScope Class Reference
TTAProgram::GlobalScope Class Reference
#include <GlobalScope.hh>
Classes
class LabelOwner
Public Member Functions
GlobalScope ()
virtual ~GlobalScope ()
virtual bool isGlobal () const
int globalCodeLabelCount (Address address) const
const CodeLabel & globalCodeLabel (Address address, int index) const
int globalCodeLabelCount () const
const CodeLabel & globalCodeLabel (int index) const
int globalDataLabelCount (Address address) const
const DataLabel & globalDataLabel (Address address, int index) const
int globalDataLabelCount () const
const DataLabel & globalDataLabel (int index) const
virtual void removeCodeLabels (InstructionAddress address)
virtual Scope * copy () const
virtual Scope * copyAndRelocate (const TTAProgram::Program &program) const
virtual void setDataLabelAddressSpace (const TTAMachine::AddressSpace &space)
Public Member Functions inherited from TTAProgram::Scope
Scope ()
virtual ~Scope ()
virtual bool isUnit () const
virtual bool isProcedure () const
virtual bool isLocal () const
bool containsCodeLabel (const std::string &name) const
bool containsDataLabel (const std::string &name) const
const CodeLabel & codeLabel (const std::string &name) const
const DataLabel & dataLabel (const std::string &name) const
int codeLabelCount (Address address) const
const CodeLabel & codeLabel (Address address, int index) const
int dataLabelCount (Address address) const
const DataLabel & dataLabel (Address address, int index) const
virtual void addCodeLabel (const CodeLabel *codeLabel)
virtual void addDataLabel (const DataLabel *dataLabel)
Protected Member Functions
virtual void addGlobalCodeLabel (const CodeLabel &codeLabel, const Scope &owner)
virtual void addGlobalDataLabel (const DataLabel &codeLabel, const Scope &owner)
Protected Member Functions inherited from TTAProgram::Scope
Scope & parent () const
void setParent (Scope &scope)
int childCount () const
void addChild (const Scope &scope)
const Scope & child (int index) const
Private Types
typedef std::vector< LabelOwner * > LabelOwnerList
List for LabelOwners.
Private Member Functions
GlobalScope (const GlobalScope &)
Copying not allowed.
GlobalScope & operator= (const GlobalScope &)
Assignment not allowed.
Private Attributes
LabelOwnerList allCodeLabels_
Container for all code labels contained in the global scope and its child scopes.
LabelOwnerList allDataLabels_
Container for all data labels.
Additional Inherited Members
Protected Types inherited from TTAProgram::Scope
typedef std::vector< const Scope * > ScopeList
List for child scopes.
typedef std::vector< const DataLabel * > DataLabelList
List of data labels.
typedef std::vector< const CodeLabel * > CodeLabelList
List of code labels.
Protected Attributes inherited from TTAProgram::Scope
ScopeList children_
Child scopes.
DataLabelList dataLabels_
Data labels contained by this scope.
CodeLabelList codeLabels_
Code labels contained by this scope.
Detailed Description
Definition at line 47 of file GlobalScope.hh.
Member Typedef Documentation
LabelOwnerList
typedef std::vector<LabelOwner*> TTAProgram::GlobalScope::LabelOwnerList private
List for LabelOwners.
Definition at line 109 of file GlobalScope.hh.
Constructor & Destructor Documentation
GlobalScope() [1/2]
TTAProgram::GlobalScope::GlobalScope ()
Constructor.
Definition at line 50 of file GlobalScope.cc.
{
}
Referenced by copy(), and copyAndRelocate().
~GlobalScope()
TTAProgram::GlobalScope::~GlobalScope () virtual
Destructor.
Definition at line 56 of file GlobalScope.cc.
{
    SequenceTools::deleteAllItems(allCodeLabels_);
    SequenceTools::deleteAllItems(allDataLabels_);
}
References allCodeLabels_, allDataLabels_, and SequenceTools::deleteAllItems().
GlobalScope() [2/2]
TTAProgram::GlobalScope::GlobalScope (const GlobalScope &) private
Copying not allowed.
Member Function Documentation
addGlobalCodeLabel()
void TTAProgram::GlobalScope::addGlobalCodeLabel (const CodeLabel & codeLabel, const Scope & owner) protected virtual
Adds a code label to the global bookkeeping.
Parameters
codeLabel The label to be added.
owner The owner scope of the label.
Implements TTAProgram::Scope.
Definition at line 78 of file GlobalScope.cc.
{
    allCodeLabels_.push_back(new LabelOwner(codeLabel, owner));
}
References allCodeLabels_, and TTAProgram::Scope::codeLabel().
addGlobalDataLabel()
void TTAProgram::GlobalScope::addGlobalDataLabel (const DataLabel & dataLabel, const Scope & owner) protected virtual
Adds a data label to the global bookkeeping.
Applies to all child scopes of this global scope.
Parameters
dataLabel The label to be added.
owner The owner scope of the label.
Implements TTAProgram::Scope.
Definition at line 180 of file GlobalScope.cc.
{
    allDataLabels_.push_back(new LabelOwner(dataLabel, owner));
}
References allDataLabels_, and TTAProgram::Scope::dataLabel().
copy()
Scope * TTAProgram::GlobalScope::copy () const virtual
Creates a copy of the scope and its labels.
The targets of the labels are not converted to point to the instructions of the given program and data of the data sections.
Returns
A copy of the scope.
Implements TTAProgram::Scope.
Definition at line 282 of file GlobalScope.cc.
{
    GlobalScope* newScope = new GlobalScope();
    for (unsigned int i = 0; i < allDataLabels_.size(); ++i) {
        const DataLabel& source = dynamic_cast<const DataLabel&>(
            allDataLabels_.at(i)->label());
        newScope->addDataLabel(new DataLabel(source));
    }
    for (unsigned int i = 0; i < allCodeLabels_.size(); ++i) {
        const CodeLabel& source = dynamic_cast<const CodeLabel&>(
            allCodeLabels_.at(i)->label());
        newScope->addCodeLabel(new CodeLabel(source));
    }
    return newScope;
}
References TTAProgram::Scope::addCodeLabel(), TTAProgram::Scope::addDataLabel(), allCodeLabels_, allDataLabels_, and GlobalScope().
copyAndRelocate()
Scope * TTAProgram::GlobalScope::copyAndRelocate (const TTAProgram::Program & program) const virtual
Creates a copy of the scope and its labels.
The targets of the labels are converted to point to the instructions of the given program. The data labels still point to the old address spaces, assuming the target machine is still the same.
Parameters
program The Program containing the instructions code labels should be converted to point to.
Returns
A copy of the scope.
Definition at line 334 of file GlobalScope.cc.
          {
    GlobalScope* newScope = new GlobalScope();
    for (unsigned int i = 0; i < allDataLabels_.size(); ++i) {
        const Label& source = allDataLabels_.at(i)->label();
        newScope->addDataLabel(new DataLabel(
                                   source.name(), source.address(),
                                   *newScope));
    }
    for (unsigned int i = 0; i < allCodeLabels_.size(); ++i) {
        const CodeLabel& source = dynamic_cast<const CodeLabel&>(
            allCodeLabels_.at(i)->label());
        newScope->addCodeLabel(
            new CodeLabel(
                program.instructionReferenceManager().createReference(
                    program.instructionAt(source.address().location())),
                source.name()));
    }
    return newScope;
}
References TTAProgram::Scope::addCodeLabel(), TTAProgram::Scope::addDataLabel(), TTAProgram::CodeLabel::address(), TTAProgram::Label::address(), allCodeLabels_, allDataLabels_, GlobalScope(), TTAProgram::Address::location(), TTAProgram::Label::name(), and program.
Referenced by TTAProgram::Program::copyFrom().
globalCodeLabel() [1/2]
const CodeLabel & TTAProgram::GlobalScope::globalCodeLabel (Address address, int index) const
Returns the code label in the given address.
Applies to all child scopes of this global scope.
Parameters
address The address of the label.
index The index of the label if there are many labels at the address.
Exceptions
KeyNotFound If no code labels in the given address were found.
Returns
The code label in the given address.
Definition at line 118 of file GlobalScope.cc.
{
    int found = 0;
    for (unsigned int i = 0; i < allCodeLabels_.size(); i++) {
        if (allCodeLabels_.at(i)->label().address().location() ==
            address.location() &&
            &allCodeLabels_.at(i)->label().address().space() ==
            &address.space()) {
            if (index == found) {
                return dynamic_cast<const CodeLabel&>(
                    allCodeLabels_.at(i)->label());
            } else {
                found++;
            }
        }
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References allCodeLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by TTAProgram::ProgramWriter::createBinary(), and DisassemblyGridTable::loadProgram().
globalCodeLabel() [2/2]
const CodeLabel & TTAProgram::GlobalScope::globalCodeLabel (int index) const
Returns the code label of requested index.
Applies to all child scopes of this global scope.
Parameters
index The index of the label.
Exceptions
KeyNotFound If no code labels in the given index.
Returns
The code label in the given index.
Definition at line 162 of file GlobalScope.cc.
{
    if (index < globalCodeLabelCount()) {
        return dynamic_cast<const CodeLabel&>(
            allCodeLabels_.at(index)->label());
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References allCodeLabels_, and globalCodeLabelCount().
globalCodeLabelCount() [1/2]
int TTAProgram::GlobalScope::globalCodeLabelCount () const
Returns the number of code labels in program.
Applies to all child scopes of this global scope.
Returns
The number of code labels in program.
Definition at line 148 of file GlobalScope.cc.
{
    return allCodeLabels_.size();
}
References allCodeLabels_.
Referenced by globalCodeLabel().
globalCodeLabelCount() [2/2]
int TTAProgram::GlobalScope::globalCodeLabelCount (Address address) const
Returns the number of code labels at the given address.
Applies to all child scopes of this global scope.
Parameters
address The address of the label(s).
Returns
The number of code labels at the given address.
Definition at line 93 of file GlobalScope.cc.
{
    int count = 0;
    for (unsigned int i = 0; i < allCodeLabels_.size(); i++) {
        if (allCodeLabels_.at(i)->label().address().location() ==
            address.location() &&
            &allCodeLabels_.at(i)->label().address().space() ==
            &address.space()) {
            count++;
        }
    }
    return count;
}
References allCodeLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by TTAProgram::ProgramWriter::createBinary(), POMDisassembler::labelCount(), and DisassemblyGridTable::loadProgram().
globalDataLabel() [1/2]
const DataLabel & TTAProgram::GlobalScope::globalDataLabel (Address address, int index) const
Returns the data label in the given address.
Applies to all child scopes of this global scope.
Parameters
address The address of the label.
index The index of the label if there are many labels at the address.
Exceptions
KeyNotFound If no data labels in the given address were found.
Returns
The data label in the given address.
Definition at line 220 of file GlobalScope.cc.
{
    int found = 0;
    for (unsigned int i = 0; i < allDataLabels_.size(); i++) {
        if (allDataLabels_.at(i)->label().address().location() ==
            address.location() &&
            &allDataLabels_.at(i)->label().address().space() ==
            &address.space()) {
            if (index == found) {
                return dynamic_cast<const DataLabel&>(
                    allDataLabels_.at(i)->label());
            } else {
                found++;
            }
        }
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References allDataLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by TTAProgram::Program::convertSymbolRef(), TTAProgram::ProgramWriter::createBinary(), and setDataLabelAddressSpace().
globalDataLabel() [2/2]
const DataLabel & TTAProgram::GlobalScope::globalDataLabel (int index) const
Returns the data label of given index.
Applies to all child scopes of this global scope.
Parameters
index The index of the label.
Exceptions
KeyNotFound If no data labels with given index.
Returns
The data label of given index.
Definition at line 264 of file GlobalScope.cc.
{
    if (index < globalDataLabelCount()) {
        return dynamic_cast<const DataLabel&>(
            allDataLabels_.at(index)->label());
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References allDataLabels_, and globalDataLabelCount().
globalDataLabelCount() [1/2]
int TTAProgram::GlobalScope::globalDataLabelCount () const
Returns the number of data labels in the program.
Applies to all child scopes of this global scope.
Returns
The number of data labels in the program.
Definition at line 250 of file GlobalScope.cc.
{
    return allDataLabels_.size();
}
References allDataLabels_.
Referenced by globalDataLabel(), and setDataLabelAddressSpace().
globalDataLabelCount() [2/2]
int TTAProgram::GlobalScope::globalDataLabelCount (Address address) const
Returns the number of data labels at the given address.
Applies to all child scopes of this global scope.
Parameters
address The address of the label(s).
Returns
The number of data labels at the given address.
Definition at line 195 of file GlobalScope.cc.
{
    int count = 0;
    for (unsigned int i = 0; i < allDataLabels_.size(); i++) {
        if (allDataLabels_.at(i)->label().address().location() ==
            address.location() &&
            &allDataLabels_.at(i)->label().address().space() ==
            &address.space()) {
            count++;
        }
    }
    return count;
}
References allDataLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by TTAProgram::Program::convertSymbolRef(), and TTAProgram::ProgramWriter::createBinary().
isGlobal()
bool TTAProgram::GlobalScope::isGlobal () const virtual
Tells whether this is a global scope.
Returns
True always.
Reimplemented from TTAProgram::Scope.
Definition at line 67 of file GlobalScope.cc.
{
    return true;
}
operator=()
GlobalScope & TTAProgram::GlobalScope::operator= (const GlobalScope &) private
Assignment not allowed.
removeCodeLabels()
void TTAProgram::GlobalScope::removeCodeLabels (InstructionAddress address) virtual
Removes all code labels attached to the given instruction address.
Parameters
address The instruction address.
Reimplemented from TTAProgram::Scope.
Definition at line 363 of file GlobalScope.cc.
{
    for (LabelOwnerList::iterator i = allCodeLabels_.begin();
         i != allCodeLabels_.end(); ) {
        if ((*i)->label().address().location() == address) {
            delete (*i);
            i = allCodeLabels_.erase(i); //returns the following element or end
        } else {
            i++; // advance to next
        }
    }
}
References allCodeLabels_.
Referenced by TTAProgram::Procedure::remove(), and TTAProgram::Program::removeProcedure().
setDataLabelAddressSpace()
void TTAProgram::GlobalScope::setDataLabelAddressSpace (const TTAMachine::AddressSpace & space) virtual
Sets the address space of all data labels.
Parameters
space The address space.
Definition at line 305 of file GlobalScope.cc.
{
    LabelOwnerList newDataLabels_;
    for (int i = 0; i < globalDataLabelCount(); ++i) {
        const DataLabel& source = globalDataLabel(i);
        LabelOwner* labelOwner = new LabelOwner(
            *(new DataLabel(
                source.name(), Address(source.address().location(), space),
                *this)), *this);
        newDataLabels_.push_back(labelOwner);
    }
    SequenceTools::deleteAllItems(allDataLabels_);
    allDataLabels_ = newDataLabels_;
}
References TTAProgram::Label::address(), allDataLabels_, SequenceTools::deleteAllItems(), globalDataLabel(), globalDataLabelCount(), TTAProgram::Address::location(), and TTAProgram::Label::name().
Referenced by TTAProgram::Program::replaceUniversalAddressSpaces().
Member Data Documentation
allCodeLabels_
LabelOwnerList TTAProgram::GlobalScope::allCodeLabels_ private
Container for all code labels contained in the global scope and its child scopes.
Definition at line 113 of file GlobalScope.hh.
Referenced by addGlobalCodeLabel(), copy(), copyAndRelocate(), globalCodeLabel(), globalCodeLabel(), globalCodeLabelCount(), globalCodeLabelCount(), removeCodeLabels(), and ~GlobalScope().
allDataLabels_
LabelOwnerList TTAProgram::GlobalScope::allDataLabels_ private
Container for all data labels.
Definition at line 115 of file GlobalScope.hh.
Referenced by addGlobalDataLabel(), copy(), copyAndRelocate(), globalDataLabel(), globalDataLabel(), globalDataLabelCount(), globalDataLabelCount(), setDataLabelAddressSpace(), and ~GlobalScope().
The documentation for this class was generated from the following files:
GlobalScope.hh
GlobalScope.cc