OpenASIP: ProGe::ProGeContext Class Reference
ProGe::ProGeContext Class Reference
#include <ProGeContext.hh>
Public Member Functions
ProGeContext ()=delete
ProGeContext (const TTAMachine::Machine &adf, const IDF::MachineImplementation &idf, const std::string &progeOutputDirectory, const std::string &sharedOutputDirectory, const std::string &coreEntityName, HDL targetHDL, int imemWidthInMAUs)
virtual ~ProGeContext ()
const TTAMachine::Machine & adf () const
const IDF::MachineImplementation & idf () const
const std::string & outputDirectory () const
const std::string & sharedDeirectory () const
const std::string & coreEntityName () const
HDL targetHDL () const
const GlobalPackage & globalPackage () const
Private Attributes
const TTAMachine::Machine & adf_
The ADF.
const IDF::MachineImplementation & idf_
The IDF.
const std::string & progeOutputDirectory_
The target base directory under where generated files are placed.
const std::string & sharedOutputDirectory_
The target base directory for files that are shared across multiple TTAs.
const std::string entityName_
The entity name of the cores.
HDL hdl_
The target language of generated files.
std::unique_ptr< GlobalPackage > globalPackage_
The package that defines (multi)core wide constants.
Detailed Description
Definition at line 60 of file ProGeContext.hh.
Constructor & Destructor Documentation
ProGeContext() [1/2]
ProGe::ProGeContext::ProGeContext () delete
ProGeContext() [2/2]
ProGe::ProGeContext::ProGeContext (const TTAMachine::Machine & adf, const IDF::MachineImplementation & idf, const std::string & progeOutputDirectory, const std::string & sharedOutputDirectory, const std::string & coreEntityName, HDL targetHDL, int imemWidthInMAUs)
Definition at line 40 of file ProGeContext.cc.
    : adf_(adf),
      idf_(idf),
      progeOutputDirectory_(progeOutputDirectory),
      sharedOutputDirectory_(sharedOutputDirectory),
      entityName_(coreEntityName),
      hdl_(targetHDL),
      globalPackage_(new GlobalPackage(coreEntityName)) {}
~ProGeContext()
ProGe::ProGeContext::~ProGeContext () virtual
Definition at line 54 of file ProGeContext.cc.
{}
Member Function Documentation
adf()
const TTAMachine::Machine & ProGe::ProGeContext::adf () const
Definition at line 57 of file ProGeContext.cc.
{
    return adf_;
}
References adf_.
Referenced by ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), ProGe::ProcessorWrapperBlock::addInstructionMemory(), ProGe::NetlistGenerator::addIUToNetlist(), ProGe::NetlistGenerator::addRFToNetlist(), DefaultICDecoderGenerator::generate(), ProGe::ProcessorGenerator::generateProcessor(), ProGe::LoopBufferBlock::LoopBufferBlock(), and ProGe::TestBenchBlock::TestBenchBlock().
coreEntityName()
const std::string & ProGe::ProGeContext::coreEntityName () const
Definition at line 77 of file ProGeContext.cc.
{
    return entityName_;
}
References entityName_.
Referenced by ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::NetlistGenerator::generate(), ProGe::LoopBufferBlock::LoopBufferBlock(), ProGe::ProcessorWrapperBlock::ProcessorWrapperBlock(), and ProGe::TestBenchBlock::write().
globalPackage()
const GlobalPackage & ProGe::ProGeContext::globalPackage () const
Definition at line 87 of file ProGeContext.cc.
{
    return *globalPackage_;
}
References globalPackage_.
Referenced by ProGe::ProcessorWrapperBlock::addInstructionMemory(), and ProGe::ProcessorWrapperBlock::ProcessorWrapperBlock().
idf()
const IDF::MachineImplementation & ProGe::ProGeContext::idf () const
Definition at line 62 of file ProGeContext.cc.
{
    return idf_;
}
References idf_.
Referenced by ProGe::NetlistGenerator::generate(), ProGe::ProcessorGenerator::generateProcessor(), and ProGe::TestBenchBlock::write().
outputDirectory()
const std::string & ProGe::ProGeContext::outputDirectory () const
Definition at line 67 of file ProGeContext.cc.
{
    return progeOutputDirectory_;
}
References progeOutputDirectory_.
sharedDeirectory()
const std::string & ProGe::ProGeContext::sharedDeirectory () const
Definition at line 72 of file ProGeContext.cc.
{
    return sharedOutputDirectory_;
}
References sharedOutputDirectory_.
targetHDL()
HDL ProGe::ProGeContext::targetHDL () const
Definition at line 82 of file ProGeContext.cc.
{
    return hdl_;
}
References hdl_.
Member Data Documentation
adf_
const TTAMachine::Machine& ProGe::ProGeContext::adf_ private
The ADF.
Definition at line 87 of file ProGeContext.hh.
Referenced by adf().
entityName_
const std::string ProGe::ProGeContext::entityName_ private
The entity name of the cores.
Definition at line 96 of file ProGeContext.hh.
Referenced by coreEntityName().
globalPackage_
std::unique_ptr<GlobalPackage> ProGe::ProGeContext::globalPackage_ private
The package that defines (multi)core wide constants.
Definition at line 102 of file ProGeContext.hh.
Referenced by globalPackage().
hdl_
HDL ProGe::ProGeContext::hdl_ private
The target language of generated files.
Definition at line 98 of file ProGeContext.hh.
Referenced by targetHDL().
idf_
const IDF::MachineImplementation& ProGe::ProGeContext::idf_ private
The IDF.
Definition at line 89 of file ProGeContext.hh.
Referenced by idf().
progeOutputDirectory_
const std::string& ProGe::ProGeContext::progeOutputDirectory_ private
The target base directory under where generated files are placed.
Definition at line 91 of file ProGeContext.hh.
Referenced by outputDirectory().
sharedOutputDirectory_
const std::string& ProGe::ProGeContext::sharedOutputDirectory_ private
The target base directory for files that are shared across multiple TTAs.
Definition at line 94 of file ProGeContext.hh.
Referenced by sharedDeirectory().
The documentation for this class was generated from the following files:
ProGeContext.hh
ProGeContext.cc