OpenASIP: SocketPortConnToolFigure Class Reference
SocketPortConnToolFigure Class Reference
#include <SocketPortConnToolFigure.hh>
Public Member Functions
SocketPortConnToolFigure (bool creating)
virtual ~SocketPortConnToolFigure ()
Public Member Functions inherited from SocketPortConnFigure
SocketPortConnFigure ()
virtual ~SocketPortConnFigure ()
Public Member Functions inherited from ConnectionFigure
virtual ~ConnectionFigure ()
void setSource (Figure *figure)
void setTarget (Figure *figure)
Figure * source () const
Figure * target () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from SocketPortConnFigure
virtual void layoutSelf (wxDC *dc)
virtual void drawConnection (wxDC *dc)
Protected Member Functions inherited from ConnectionFigure
ConnectionFigure ()
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutChildren (wxDC *)
Private Member Functions
SocketPortConnToolFigure & operator= (SocketPortConnToolFigure &old)
Assignment not allowed.
SocketPortConnToolFigure (SocketPortConnToolFigure &old)
Copying not allowed.
Private Attributes
wxColor color_
Current color of the figure.
Static Private Attributes
static const wxColor LINE_COLOR_GREEN = wxColor(0, 200, 0)
Figure color for connections being created.
static const wxColor LINE_COLOR_RED = wxColor(255, 0, 0)
Figure color for connections being removed.
Additional Inherited Members
Protected Attributes inherited from ConnectionFigure
Figure * source_
Source of connection.
Figure * target_
Target of connection.
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a socket-to-port connection for the connection tool.
Definition at line 45 of file SocketPortConnToolFigure.hh.
Constructor & Destructor Documentation
SocketPortConnToolFigure() [1/2]
SocketPortConnToolFigure::SocketPortConnToolFigure (bool creating)
The Constructor.
Parameters
creating True, if the tool is creating a new connection. False, if an old connection is being removed.
Definition at line 46 of file SocketPortConnToolFigure.cc.
                                                               :
    SocketPortConnFigure() {
    if (creating) {
        color_ = LINE_COLOR_GREEN;
    } else {
        color_ = LINE_COLOR_RED;
    }
}
References color_, LINE_COLOR_GREEN, and LINE_COLOR_RED.
~SocketPortConnToolFigure()
SocketPortConnToolFigure::~SocketPortConnToolFigure () virtual
The Destructor.
Definition at line 60 of file SocketPortConnToolFigure.cc.
{
}
SocketPortConnToolFigure() [2/2]
SocketPortConnToolFigure::SocketPortConnToolFigure (SocketPortConnToolFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void SocketPortConnToolFigure::drawSelf (wxDC * dc) protected virtual
Draws the connection's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from SocketPortConnFigure.
Definition at line 69 of file SocketPortConnToolFigure.cc.
{
    assert(source_ != NULL && target_ != NULL);
    wxPen pen = wxPen(color_, 3, wxSHORT_DASH);
    dc->SetPen(pen);
    drawConnection(dc);
}
References assert, color_, SocketPortConnFigure::drawConnection(), ConnectionFigure::source_, and ConnectionFigure::target_.
operator=()
SocketPortConnToolFigure & SocketPortConnToolFigure::operator= (SocketPortConnToolFigure & old) private
Assignment not allowed.
Member Data Documentation
color_
wxColor SocketPortConnToolFigure::color_ private
Current color of the figure.
Definition at line 63 of file SocketPortConnToolFigure.hh.
Referenced by drawSelf(), and SocketPortConnToolFigure().
LINE_COLOR_GREEN
const wxColor SocketPortConnToolFigure::LINE_COLOR_GREEN = wxColor(0, 200, 0) static private
Figure color for connections being created.
Definition at line 59 of file SocketPortConnToolFigure.hh.
Referenced by SocketPortConnToolFigure().
LINE_COLOR_RED
const wxColor SocketPortConnToolFigure::LINE_COLOR_RED = wxColor(255, 0, 0) static private
Figure color for connections being removed.
Definition at line 61 of file SocketPortConnToolFigure.hh.
Referenced by SocketPortConnToolFigure().
The documentation for this class was generated from the following files:
SocketPortConnToolFigure.hh
SocketPortConnToolFigure.cc