OpenASIP: SimulateDialog Class Reference
SimulateDialog Class Reference
#include <SimulateDialog.hh>
Public Member Functions
SimulateDialog (wxWindow *parent, Operation *operation, const std::string &pathName, const std::string &modName)
virtual ~SimulateDialog ()
std::string formattedValue (SimValue *value)
Static Public Attributes
static const wxString DIALOG_NAME = _T("SimulateDialog")
Name of the dialog so it can be found with wxWindow::FindWindowByName.
Private Types
enum {
ID_INPUT_LIST = 12000 , ID_VALUE , ID_BUTTON_UPDATE , ID_OUTPUT_LIST ,
ID_TEXT_READY , ID_BITMAP_READY , ID_TEXT_UPDATE , ID_BITMAP_UPDATE ,
ID_TEXT_CLOCK , ID_TEXT_CLOCK_VALUE , ID_BUTTON_RESET , ID_BUTTON_TRIGGER ,
ID_BUTTON_LATE_RESULT , ID_BUTTON_ADVANCE_LOCK , ID_BUTTON_SHOW_HIDE_REGISTERS , ID_FORMAT_TEXT ,
ID_FORMAT
}
Private Member Functions
SimulateDialog (const SimulateDialog &)
Copying not allowed.
SimulateDialog & operator= (const SimulateDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
wxBitmap createBitmap (unsigned int index)
virtual bool TransferDataToWindow ()
void updateLists ()
void setTexts ()
void onSelection (wxListEvent &event)
void onUpdateValue (wxCommandEvent &event)
void onReset (wxCommandEvent &event)
void onTrigger (wxCommandEvent &event)
void onLateResult (wxCommandEvent &event)
void onAdvanceClock (wxCommandEvent &event)
void onFormatChanged (wxCommandEvent &event)
void showOrHideRegisters (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onClose (wxCloseEvent &)
void setInputValues (std::vector< SimValue * > inputs)
void setOutputValues (std::vector< SimValue * > outputs)
void createState ()
Private Attributes
wxStaticBoxSizer * inputSizer_
Input operand sizer.
wxStaticBoxSizer * outputSizer_
Output operand sizer.
wxListCtrl * inputList_
Input list.
wxListCtrl * outputList_
Output list.
NumberControl * updateValue_
Text control for updating input values.
wxChoice * format_
Choice list of possible output formats.
Operation * operation_
Bitmap for Trigger result.
std::string pathName_
Path in which operation module belongs to.
std::string modName_
Module in which operation belongs to.
std::vector< DataObject * > inputs_
List of input values.
std::vector< DataObject * > outputs_
List of output values.
unsigned int clock_
Variable where the value of clock is kept.
SimulationInfoDialog * infoDialog_
Dialog for showing additional information.
OperationBehaviorProxy * behaviorProxy_
The behavior proxy that loads the behavior. Used to "freeze" the behavior loading for the duration of the simulation.
Static Private Attributes
static const std::string FORMAT_SIGNED_INT = "signed int"
Signed int format.
static const std::string FORMAT_UNSIGNED_INT = "unsigned int"
Unsigned int format.
static const std::string FORMAT_DOUBLE = "double"
Double format.
static const std::string FORMAT_FLOAT = "float"
Float format.
static const std::string FORMAT_BINARY = "binary"
Binary format.
static const std::string FORMAT_HEXA_DECIMAL = "hexadecimal"
Hexadecimal format.
Detailed Description
Class for simulating operation behavior.
Definition at line 53 of file SimulateDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_INPUT_LIST
ID_VALUE
ID_BUTTON_UPDATE
ID_OUTPUT_LIST
ID_TEXT_READY
ID_BITMAP_READY
ID_TEXT_UPDATE
ID_BITMAP_UPDATE
ID_TEXT_CLOCK
ID_TEXT_CLOCK_VALUE
ID_BUTTON_RESET
ID_BUTTON_TRIGGER
ID_BUTTON_LATE_RESULT
ID_BUTTON_ADVANCE_LOCK
ID_BUTTON_SHOW_HIDE_REGISTERS
ID_FORMAT_TEXT
ID_FORMAT
Definition at line 109 of file SimulateDialog.hh.
         {
        ID_INPUT_LIST = 12000,
        ID_VALUE,
        ID_BUTTON_UPDATE,
        ID_OUTPUT_LIST,
        ID_TEXT_READY,
        ID_BITMAP_READY,
        ID_TEXT_UPDATE,
        ID_BITMAP_UPDATE,
        ID_TEXT_CLOCK,
        ID_TEXT_CLOCK_VALUE,
        ID_BUTTON_RESET,
        ID_BUTTON_TRIGGER,
        ID_BUTTON_LATE_RESULT,
        ID_BUTTON_ADVANCE_LOCK,
        ID_BUTTON_SHOW_HIDE_REGISTERS,
        ID_FORMAT_TEXT,
        ID_FORMAT
    };
Constructor & Destructor Documentation
SimulateDialog() [1/2]
SimulateDialog::SimulateDialog (wxWindow * parent, Operation * operation, const std::string & pathName, const std::string & modName)
Constructor.
Parameters
parent Parent window.
operation Operation to be simulated.
Definition at line 98 of file SimulateDialog.cc.
                              :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_SIMULATE),
             wxDefaultSize, wxRESIZE_BORDER, DIALOG_NAME),
    operation_(operation), pathName_(pathName), modName_(modName), clock_(0) {
    createContents(this, true, true);
    for (int i = 0; i < operation_->numberOfInputs(); i++) {
        inputs_.push_back(new DataObject());
        inputs_[i]->setString("0");
    }
    for (int i = 0; i < operation_->numberOfOutputs(); i++) {
        outputs_.push_back(new DataObject());
        outputs_[i]->setString("0");
    }
    inputList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_INPUT_LIST));
    outputList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_OUTPUT_LIST));
    updateValue_ = dynamic_cast<NumberControl*>(FindWindow(ID_VALUE));
    format_ = dynamic_cast<wxChoice*>(FindWindow(ID_FORMAT));
    //triggerBM_ = dynamic_cast<wxStaticBitmap*>(FindWindow(ID_BITMAP_READY));
    //lateResultBM_ =
    //    dynamic_cast<wxStaticBitmap*>(FindWindow(ID_BITMAP_UPDATE));
    FindWindow(wxID_OK)->SetFocus();
    format_->Append(WxConversion::toWxString(FORMAT_SIGNED_INT));
    format_->Append(WxConversion::toWxString(FORMAT_UNSIGNED_INT));
    format_->Append(WxConversion::toWxString(FORMAT_DOUBLE));
    format_->Append(WxConversion::toWxString(FORMAT_FLOAT));
    format_->Append(WxConversion::toWxString(FORMAT_BINARY));
    format_->Append(WxConversion::toWxString(FORMAT_HEXA_DECIMAL));
    format_->SetSelection(0);
    setTexts();
    infoDialog_ = new SimulationInfoDialog(
        this, &OperationContainer::operationContext());
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->registerListener(OSEdInformer::EVENT_REGISTER, infoDialog_);
    informer->registerListener(OSEdInformer::EVENT_RESET, infoDialog_);
    /* Ensure we won't refresh the behavior from the plugin file again
       during the simulation. This leads to crashes due to using a state
       instance created by a behavior definition created by a previously
       loaded behavior instance. This effectively "freezes" the behavior
       to the one loaded in the next behavior function call. */
    behaviorProxy_ =
        dynamic_cast<OperationBehaviorProxy*>(&operation->behavior());
    assert(behaviorProxy_ != NULL);
    behaviorProxy_->setAlwaysReloadBehavior(false);
}
References assert, OSEdInformer::EVENT_REGISTER, OSEdInformer::EVENT_RESET, OperationContainer::operationContext(), OSEdInformer::registerListener(), and WxConversion::toWxString().
~SimulateDialog()
SimulateDialog::~SimulateDialog () virtual
Destructor.
Definition at line 162 of file SimulateDialog.cc.
{
    SequenceTools::deleteAllItems(inputs_);
    SequenceTools::deleteAllItems(outputs_);
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_SIMULATE, point);
    /* Ensure we won't use the old state object the next time because
       the behavior will be reloaded from the dynlib. It would crash. */
    OperationBehavior& behavior = operation_->behavior();
    behavior.deleteState(OperationContainer::operationContext());
    /* "Unfreeze" the OperationBehavior. Now it will be reloaded always
       when accessing the methods to enable the dynamic menu items in
       the operation list. */
    behaviorProxy_->setAlwaysReloadBehavior(true);
    behaviorProxy_->uninitializeBehavior();
}
References Operation::behavior(), behaviorProxy_, SequenceTools::deleteAllItems(), OperationBehavior::deleteState(), DialogPosition::DIALOG_SIMULATE, inputs_, operation_, OperationContainer::operationContext(), outputs_, OperationBehaviorProxy::setAlwaysReloadBehavior(), DialogPosition::setPosition(), and OperationBehaviorProxy::uninitializeBehavior().
SimulateDialog() [2/2]
SimulateDialog::SimulateDialog (const SimulateDialog &) private
Copying not allowed.
Member Function Documentation
createBitmap()
wxBitmap SimulateDialog::createBitmap (unsigned int index) private
Definition at line 693 of file SimulateDialog.cc.
{
    if (index == 0)
    {
        /* XPM */
        static const char *xpm_data[] = {
            /* columns rows colors chars-per-pixel */
            "16 15 2 1",
            "  c None",
            "a c #FF0000",
            /* pixels */
            "                ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            "                "
        };
        wxBitmap bitmap( xpm_data );
        return bitmap;
    }
    if (index == 1)
    {
        /* XPM */
        static const char *xpm_data[] = {
            /* columns rows colors chars-per-pixel */
            "16 15 2 1",
            "  c None",
            "b c #00FF00",
            /* pixels */
            "                ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            " bbbbbbbbbbbbbb ",
            "                "
        };
        wxBitmap bitmap( xpm_data );
        return bitmap;
    }
    if (index == 2)
    {
        /* XPM */
        static const char *xpm_data[] = {
            /* columns rows colors chars-per-pixel */
            "16 15 2 1",
            "  c None",
            "a c Black",
            /* pixels */
            "                ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            " aaaaaaaaaaaaaa ",
            "                "
        };
        wxBitmap bitmap( xpm_data );
        return bitmap;
    }
    return wxNullBitmap;
}
createContents()
wxSizer * SimulateDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
NOTE! This function was generated by wxDesigner.
Parameters
parent Parent window.
call_fit If true fits the contenst inside the dialog.
set_sizer If true sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 582 of file SimulateDialog.cc.
                     {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Input values") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    inputSizer_ = item2;
    wxListCtrl *item4 = new wxListCtrl( parent, ID_INPUT_LIST, wxDefaultPosition, wxSize(160,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item2->Add( item4, 1, wxGROW|wxALL, 5 );
    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );
    NumberControl *item6 = new NumberControl(
        parent, ID_VALUE, wxDefaultPosition, wxSize(200, -1),
        NumberControl::MODE_BINARY | NumberControl::MODE_INT |
        NumberControl::MODE_UNSIGNED | NumberControl::MODE_HEXADECIMAL |
        NumberControl::MODE_FLOAT | NumberControl::MODE_DOUBLE);
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item7 = new wxButton( parent, ID_BUTTON_UPDATE, wxT("Update"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 1, wxGROW|wxALL, 5 );
    wxStaticBox *item9 = new wxStaticBox( parent, -1, wxT("Output values") );
    wxStaticBoxSizer *item8 = new wxStaticBoxSizer( item9, wxVERTICAL );
    outputSizer_ = item8;
    wxListCtrl *item10 = new wxListCtrl( parent, ID_OUTPUT_LIST, wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item8->Add( item10, 1, wxGROW|wxALL, 5 );
    item1->Add( item8, 1, wxGROW|wxALL, 5 );
    wxGridSizer *item11 = new wxGridSizer( 2, 0, 0 );
    //wxStaticText *item12 = new wxStaticText( parent, ID_TEXT_READY, wxT("Ready"), wxDefaultPosition, wxDefaultSize, 0 );
    //item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    //wxStaticBitmap *item13 = new wxStaticBitmap( parent, ID_BITMAP_READY, createBitmap( 2 ), wxDefaultPosition, wxDefaultSize );
    //item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    //wxStaticText *item14 = new wxStaticText( parent, ID_TEXT_UPDATE, wxT("Update"), wxDefaultPosition, wxDefaultSize, 0 );
    //item11->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    //wxStaticBitmap *item15 = new wxStaticBitmap( parent, ID_BITMAP_UPDATE, createBitmap( 2 ), wxDefaultPosition, wxDefaultSize );
    //item11->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT_CLOCK, wxT("Clock count:"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT_CLOCK_VALUE, wxT("0"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item11, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 1, wxGROW|wxALL, 5 );
    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item19 = new wxStaticText( parent, ID_FORMAT_TEXT, wxT("Format:"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs20 = (wxString*) NULL;
    wxChoice *item20 = new wxChoice( parent, ID_FORMAT, wxDefaultPosition, wxSize(130,-1), 0, strs20, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item22 = new wxButton( parent, ID_BUTTON_RESET, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item23 = new wxButton( parent, ID_BUTTON_TRIGGER, wxT("Trigger"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item25 = new wxButton( parent, ID_BUTTON_ADVANCE_LOCK, wxT("Advance Clock"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item26 = new wxButton( parent, ID_BUTTON_SHOW_HIDE_REGISTERS, wxT("Show registers"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item27 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BUTTON_ADVANCE_LOCK, ID_BUTTON_RESET, ID_BUTTON_SHOW_HIDE_REGISTERS, ID_BUTTON_TRIGGER, ID_BUTTON_UPDATE, ID_FORMAT, ID_FORMAT_TEXT, ID_INPUT_LIST, ID_OUTPUT_LIST, ID_TEXT_CLOCK, ID_TEXT_CLOCK_VALUE, ID_VALUE, inputSizer_, NumberControl::MODE_BINARY, NumberControl::MODE_DOUBLE, NumberControl::MODE_FLOAT, NumberControl::MODE_HEXADECIMAL, NumberControl::MODE_INT, NumberControl::MODE_UNSIGNED, and outputSizer_.
createState()
void SimulateDialog::createState () private
Creates the state for the operation.
Definition at line 566 of file SimulateDialog.cc.
{
    OperationBehavior& beh = operation_->behavior();
    beh.createState(OperationContainer::operationContext());
}
References Operation::behavior(), OperationBehavior::createState(), operation_, and OperationContainer::operationContext().
Referenced by onAdvanceClock(), and onTrigger().
formattedValue()
string SimulateDialog::formattedValue (SimValue * value)
Formats the value of the SimValue.
Parameters
value Value to be formatted.
Definition at line 532 of file SimulateDialog.cc.
{
    string format = WxConversion::toString(format_->GetStringSelection());
    if (format == FORMAT_SIGNED_INT) {
        SIntWord intSigned = value->sIntWordValue();
        return Conversion::toString(static_cast<int>(intSigned));
    } else if (format == FORMAT_UNSIGNED_INT) {
        UIntWord intUnsigned = value->uIntWordValue();
        return Conversion::toString(intUnsigned);
    } else if (format == FORMAT_DOUBLE) {
        DoubleWord doubleWord = value->doubleWordValue();
        return Conversion::toString(doubleWord);
    } else if (format == FORMAT_FLOAT) {
        FloatWord floatWord = value->floatWordValue();
        string floatString = Conversion::toString(floatWord);
        if (floatString.find(".") == string::npos) {
            floatString += ".0";
        }
        floatString += "f";
        return floatString;
    } else if (format == FORMAT_BINARY) {
        UIntWord binary = value->uIntWordValue();
        return Conversion::toBinString(static_cast<int>(binary));
    } else if (format == FORMAT_HEXA_DECIMAL) {
        UIntWord hex = value->uIntWordValue();
        return Conversion::toHexString(hex);
    }
    return "";
}
References SimValue::doubleWordValue(), SimValue::floatWordValue(), format_, FORMAT_BINARY, FORMAT_DOUBLE, FORMAT_FLOAT, FORMAT_HEXA_DECIMAL, FORMAT_SIGNED_INT, FORMAT_UNSIGNED_INT, SimValue::sIntWordValue(), Conversion::toBinString(), Conversion::toHexString(), Conversion::toString(), WxConversion::toString(), and SimValue::uIntWordValue().
Referenced by onUpdateValue(), setInputValues(), setOutputValues(), and SimulationInfoDialog::updateList().
onAdvanceClock()
void SimulateDialog::onAdvanceClock (wxCommandEvent & event) private
Handles the event when advance clock button is pushed.
Definition at line 399 of file SimulateDialog.cc.
{
    createState();
    OperationContainer::operationContext().advanceClock();
    OperationContainer::memory().advanceClock();
    clock_++;
    FindWindow(ID_TEXT_CLOCK_VALUE)->SetLabel(WxConversion::toWxString(clock_));
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->handleEvent(OSEdInformer::EVENT_MEMORY);
}
References Memory::advanceClock(), OperationContext::advanceClock(), clock_, createState(), OSEdInformer::EVENT_MEMORY, OSEdInformer::handleEvent(), ID_TEXT_CLOCK_VALUE, OperationContainer::memory(), OperationContainer::operationContext(), and WxConversion::toWxString().
onClose()
void SimulateDialog::onClose (wxCloseEvent & event) private
Handles the event when window is closed.
Parameters
event Event to be handled.
Definition at line 485 of file SimulateDialog.cc.
{
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->unregisterListener(OSEdInformer::EVENT_REGISTER, infoDialog_);
    informer->unregisterListener(OSEdInformer::EVENT_RESET, infoDialog_);
    infoDialog_->Destroy();
    event.Skip();
}
References OSEdInformer::EVENT_REGISTER, OSEdInformer::EVENT_RESET, infoDialog_, and OSEdInformer::unregisterListener().
onFormatChanged()
void SimulateDialog::onFormatChanged (wxCommandEvent & event) private
Handles the event when intput and output format is changed.
Definition at line 413 of file SimulateDialog.cc.
{
    vector<SimValue*> outputs;
    OperationSimulator& simulator = OperationSimulator::instance();
    string result = "";
    for (size_t i = 0; i < inputs_.size(); i++) {
        SimValue* sim = new SimValue(32);
        string value = inputs_[i]->stringValue();
        simulator.initializeSimValue(value, sim, result);
        outputs.push_back(sim);
    }
    for (size_t i = 0; i < outputs_.size(); i++) {
        SimValue* sim = new SimValue(32);
        string value = outputs_[i]->stringValue();
        simulator.initializeSimValue(value, sim, result);
        outputs.push_back(sim);
    }
    setInputValues(outputs);
    setOutputValues(outputs);
    updateLists();
    SequenceTools::deleteAllItems(outputs);
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->handleEvent(OSEdInformer::EVENT_REGISTER);
}
References SequenceTools::deleteAllItems(), OSEdInformer::EVENT_REGISTER, OSEdInformer::handleEvent(), OperationSimulator::initializeSimValue(), inputs_, OperationSimulator::instance(), outputs_, setInputValues(), setOutputValues(), and updateLists().
onLateResult()
void SimulateDialog::onLateResult (wxCommandEvent & event) private
onOK()
void SimulateDialog::onOK (wxCommandEvent & event) private
Handles the event when OK button is pushed.
Definition at line 471 of file SimulateDialog.cc.
{
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->unregisterListener(OSEdInformer::EVENT_REGISTER, infoDialog_);
    informer->unregisterListener(OSEdInformer::EVENT_RESET, infoDialog_);
    infoDialog_->Destroy();
    Destroy();
}
References OSEdInformer::EVENT_REGISTER, OSEdInformer::EVENT_RESET, infoDialog_, and OSEdInformer::unregisterListener().
onReset()
void SimulateDialog::onReset (wxCommandEvent & event) private
Handles the event when Reset button is pushed.
Reset sets all values to their defaults.
Definition at line 336 of file SimulateDialog.cc.
{
    OperationBehavior& behavior = operation_->behavior();
    behavior.deleteState(OperationContainer::operationContext());
    for (size_t i = 0; i < inputs_.size(); i++) {
        inputs_[i]->setString("0");
    }
    for (size_t i = 0; i < outputs_.size(); i++) {
        outputs_[i]->setString("0");
    }
    //triggerBM_->SetBitmap(createBitmap(2));
    //lateResultBM_->SetBitmap(createBitmap(2));
    clock_ = 0;
    FindWindow(ID_TEXT_CLOCK_VALUE)->
        SetLabel(WxConversion::toWxString(clock_));
    updateLists();
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->handleEvent(OSEdInformer::EVENT_RESET);
}
References Operation::behavior(), clock_, OperationBehavior::deleteState(), OSEdInformer::EVENT_RESET, OSEdInformer::handleEvent(), ID_TEXT_CLOCK_VALUE, inputs_, operation_, OperationContainer::operationContext(), outputs_, WxConversion::toWxString(), and updateLists().
onSelection()
void SimulateDialog::onSelection (wxListEvent & event) private
Handles the event when a value is selected or deselected on input list.
Definition at line 299 of file SimulateDialog.cc.
{
    if (inputList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_BUTTON_UPDATE)->Disable();
    } else {
        FindWindow(ID_BUTTON_UPDATE)->Enable();
    }
}
References ID_BUTTON_UPDATE, and inputList_.
Referenced by updateLists().
onTrigger()
void SimulateDialog::onTrigger (wxCommandEvent & event) private
Handles the event when Trigger button is pushed.
Definition at line 363 of file SimulateDialog.cc.
{
    OperationSimulator& simulator = OperationSimulator::instance();
    vector<SimValue*> outputs;
    vector<DataObject> inputs;
    for (size_t i = 0; i < inputs_.size(); i++) {
        inputs.push_back(*inputs_[i]);
    }
    string result = "";
    createState();
    OperationContext& context = OperationContainer::operationContext();
    if (simulator.simulateTrigger(
            *operation_, inputs, outputs, context, result)) {
        //triggerBM_->SetBitmap(createBitmap(1));
        setOutputValues(outputs);
        updateLists();
    } else {
        //triggerBM_->SetBitmap(createBitmap(0));
        if (result != "") {
            ErrorDialog dialog(this, WxConversion::toWxString(result));
            dialog.ShowModal();
        }
    }
    SequenceTools::deleteAllItems(outputs);
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->handleEvent(OSEdInformer::EVENT_REGISTER);
    informer->handleEvent(OSEdInformer::EVENT_MEMORY);
}
References createState(), SequenceTools::deleteAllItems(), OSEdInformer::EVENT_MEMORY, OSEdInformer::EVENT_REGISTER, OSEdInformer::handleEvent(), inputs_, OperationSimulator::instance(), operation_, OperationContainer::operationContext(), setOutputValues(), OperationSimulator::simulateTrigger(), WxConversion::toWxString(), and updateLists().
onUpdateValue()
void SimulateDialog::onUpdateValue (wxCommandEvent & event) private
Handles the event when input value is updated.
Definition at line 311 of file SimulateDialog.cc.
{
    TransferDataFromWindow();
    string inputString = WidgetTools::lcStringSelection(inputList_, 0);
    if (inputString != "") {
        int input = Conversion::toInt(inputString);
        SimValue* temp = new SimValue(32);
        if (updateValue_->mode() == NumberControl::MODE_DOUBLE) {
            double value = updateValue_->doubleValue();
            *temp = value;
        } else {
            int value = updateValue_->intValue();
            *temp = value;
        }
        inputs_[input - 1]->setString(formattedValue(temp));
        delete temp;
        updateLists();
    }
}
References NumberControl::doubleValue(), formattedValue(), inputList_, inputs_, NumberControl::intValue(), WidgetTools::lcStringSelection(), NumberControl::mode(), NumberControl::MODE_DOUBLE, Conversion::toInt(), updateLists(), and updateValue_.
operator=()
SimulateDialog & SimulateDialog::operator= (const SimulateDialog &) private
Assignment not allowed.
setInputValues()
void SimulateDialog::setInputValues (std::vector< SimValue * > inputs) private
Sets the input values after the format has changed.
Parameters
inputs Input values of operation.
Definition at line 499 of file SimulateDialog.cc.
{
    string inputFormat = WxConversion::toString(format_->GetStringSelection());
    for (size_t i = 0; i < inputs_.size(); i++) {
        SimValue* current = inputs[i];
        inputs_[i]->setString(formattedValue(current));
    }
}
References format_, formattedValue(), inputs_, and WxConversion::toString().
Referenced by onFormatChanged().
setOutputValues()
void SimulateDialog::setOutputValues (std::vector< SimValue * > outputs) private
Sets the output values of the operation after executing a command.
Parameters
outputs Output values of operation.
Definition at line 515 of file SimulateDialog.cc.
{
    int k = 0;
    size_t upperBound = inputs_.size() + outputs_.size();
    for (size_t i = inputs_.size(); i < upperBound; i++) {
        SimValue* current = outputs[i];
        outputs_[k]->setString(formattedValue(current));
        k++;
    }
}
References formattedValue(), inputs_, and outputs_.
Referenced by onFormatChanged(), and onTrigger().
setTexts()
void SimulateDialog::setTexts () private
Set texts to widgets.
Definition at line 198 of file SimulateDialog.cc.
{
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt = osedText.text(OSEdTextGenerator::TXT_SIMULATE_DIALOG_TITLE);
    fmt % operation_->name();
    SetTitle(WxConversion::toWxString(fmt.str()));
    // static texts
    //WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_READY),
    //                      OSEdTextGenerator::TXT_LABEL_READY);
    //WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_UPDATE),
    //                      OSEdTextGenerator::TXT_LABEL_UPDATE);
    WidgetTools::setLabel(&osedText, FindWindow(ID_TEXT_CLOCK),
                          OSEdTextGenerator::TXT_LABEL_CLOCK);
    WidgetTools::setLabel(&osedText, FindWindow(ID_FORMAT_TEXT),
                          OSEdTextGenerator::TXT_LABEL_FORMAT);
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_RESET),
                          OSEdTextGenerator::TXT_BUTTON_RESET);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_TRIGGER),
                          OSEdTextGenerator::TXT_BUTTON_TRIGGER);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_ADVANCE_LOCK),
                          OSEdTextGenerator::TXT_BUTTON_ADVANCE_LOCK);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_SHOW_HIDE_REGISTERS),
                          OSEdTextGenerator::TXT_BUTTON_SHOW_REGISTERS);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_UPDATE),
                          OSEdTextGenerator::TXT_BUTTON_UPDATE);
    // column titles
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_OPERAND);
    inputList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH/2);
    outputList_->InsertColumn(
        0, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH/2);
    fmt = osedText.text(OSEdTextGenerator::TXT_COLUMN_VALUE);
    inputList_->InsertColumn(
        1, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    outputList_->InsertColumn(
        1, WxConversion::toWxString(fmt.str()), wxLIST_FORMAT_LEFT,
        OSEdConstants::DEFAULT_COLUMN_WIDTH);
    // box sizers
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_INPUT_VALUES);
    WidgetTools::setWidgetLabel(inputSizer_, fmt.str());
    fmt = osedText.text(OSEdTextGenerator::TXT_BOX_OUTPUT_VALUES);
    WidgetTools::setWidgetLabel(outputSizer_, fmt.str());
}
References OSEdConstants::DEFAULT_COLUMN_WIDTH, ID_BUTTON_ADVANCE_LOCK, ID_BUTTON_RESET, ID_BUTTON_SHOW_HIDE_REGISTERS, ID_BUTTON_TRIGGER, ID_BUTTON_UPDATE, ID_FORMAT_TEXT, ID_TEXT_CLOCK, inputList_, inputSizer_, GUITextGenerator::instance(), OSEdTextGenerator::instance(), Operation::name(), operation_, outputList_, outputSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BOX_INPUT_VALUES, OSEdTextGenerator::TXT_BOX_OUTPUT_VALUES, OSEdTextGenerator::TXT_BUTTON_ADVANCE_LOCK, GUITextGenerator::TXT_BUTTON_OK, OSEdTextGenerator::TXT_BUTTON_RESET, OSEdTextGenerator::TXT_BUTTON_SHOW_REGISTERS, OSEdTextGenerator::TXT_BUTTON_TRIGGER, OSEdTextGenerator::TXT_BUTTON_UPDATE, OSEdTextGenerator::TXT_COLUMN_OPERAND, OSEdTextGenerator::TXT_COLUMN_VALUE, OSEdTextGenerator::TXT_LABEL_CLOCK, OSEdTextGenerator::TXT_LABEL_FORMAT, and OSEdTextGenerator::TXT_SIMULATE_DIALOG_TITLE.
showOrHideRegisters()
void SimulateDialog::showOrHideRegisters (wxCommandEvent & event) private
Handles the event when registers are shown or hidden.
Definition at line 446 of file SimulateDialog.cc.
{
    wxButton* button =
        dynamic_cast<wxButton*>(FindWindow(ID_BUTTON_SHOW_HIDE_REGISTERS));
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_BUTTON_SHOW_REGISTERS);
    if (button->GetLabel() == WxConversion::toWxString(fmt.str())) {
        int x, y;
        GetPosition(&x, &y);
        int width, height;
        GetSize(&width, &height);
        y += height + 25;
        infoDialog_->Move(x, y);
        infoDialog_->Show(true);
        fmt = texts.text(OSEdTextGenerator::TXT_BUTTON_HIDE_REGISTERS);
        button->SetLabel(WxConversion::toWxString(fmt.str()));
    } else {
        infoDialog_->Show(false);
        button->SetLabel(WxConversion::toWxString(fmt.str()));
    }
}
References ID_BUTTON_SHOW_HIDE_REGISTERS, infoDialog_, OSEdTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUTTON_HIDE_REGISTERS, and OSEdTextGenerator::TXT_BUTTON_SHOW_REGISTERS.
TransferDataToWindow()
bool SimulateDialog::TransferDataToWindow () private virtual
Transfers data to window.
Definition at line 189 of file SimulateDialog.cc.
{
    updateLists();
    return wxWindow::TransferDataToWindow();
}
References updateLists().
updateLists()
void SimulateDialog::updateLists () private
Updates input and output value lists.
Definition at line 271 of file SimulateDialog.cc.
{
    inputList_->DeleteAllItems();
    outputList_->DeleteAllItems();
    for (unsigned int i = 0; i < inputs_.size(); i++) {
        wxString id = WxConversion::toWxString(i + 1);
        inputList_->InsertItem(i, id);
        inputList_->SetItem(
            i, 1, WxConversion::toWxString(inputs_[i]->stringValue()));
    }
    int k = inputs_.size() + 1;
    for (unsigned int i = 0; i < outputs_.size(); i++) {
        wxString id = WxConversion::toWxString(k);
        outputList_->InsertItem(i, id);
        outputList_->SetItem(
            i, 1, WxConversion::toWxString(outputs_[i]->stringValue()));
        k++;
    }
    wxListEvent dummy;
    onSelection(dummy);
}
References dummy, inputList_, inputs_, onSelection(), outputList_, outputs_, and WxConversion::toWxString().
Referenced by onFormatChanged(), onReset(), onTrigger(), onUpdateValue(), and TransferDataToWindow().
Member Data Documentation
behaviorProxy_
OperationBehaviorProxy* SimulateDialog::behaviorProxy_ private
The behavior proxy that loads the behavior. Used to "freeze" the behavior loading for the duration of the simulation.
Definition at line 161 of file SimulateDialog.hh.
Referenced by ~SimulateDialog().
clock_
unsigned int SimulateDialog::clock_ private
Variable where the value of clock is kept.
Definition at line 156 of file SimulateDialog.hh.
Referenced by onAdvanceClock(), and onReset().
DIALOG_NAME
const wxString SimulateDialog::DIALOG_NAME = _T("SimulateDialog") static
Name of the dialog so it can be found with wxWindow::FindWindowByName.
Definition at line 66 of file SimulateDialog.hh.
Referenced by OSEdBuildAllCmd::Do(), and OSEdBuildCmd::Do().
format_
wxChoice* SimulateDialog::format_ private
Choice list of possible output formats.
Definition at line 140 of file SimulateDialog.hh.
Referenced by formattedValue(), and setInputValues().
FORMAT_BINARY
const string SimulateDialog::FORMAT_BINARY = "binary" static private
Binary format.
Definition at line 102 of file SimulateDialog.hh.
Referenced by formattedValue().
FORMAT_DOUBLE
const string SimulateDialog::FORMAT_DOUBLE = "double" static private
Double format.
Definition at line 98 of file SimulateDialog.hh.
Referenced by formattedValue().
FORMAT_FLOAT
const string SimulateDialog::FORMAT_FLOAT = "float" static private
Float format.
Definition at line 100 of file SimulateDialog.hh.
Referenced by formattedValue().
FORMAT_HEXA_DECIMAL
const string SimulateDialog::FORMAT_HEXA_DECIMAL = "hexadecimal" static private
Hexadecimal format.
Definition at line 104 of file SimulateDialog.hh.
Referenced by formattedValue().
FORMAT_SIGNED_INT
const string SimulateDialog::FORMAT_SIGNED_INT = "signed int" static private
Signed int format.
Definition at line 94 of file SimulateDialog.hh.
Referenced by formattedValue().
FORMAT_UNSIGNED_INT
const string SimulateDialog::FORMAT_UNSIGNED_INT = "unsigned int" static private
Unsigned int format.
Definition at line 96 of file SimulateDialog.hh.
Referenced by formattedValue().
infoDialog_
SimulationInfoDialog* SimulateDialog::infoDialog_ private
Dialog for showing additional information.
Definition at line 158 of file SimulateDialog.hh.
Referenced by onClose(), onOK(), and showOrHideRegisters().
inputList_
wxListCtrl* SimulateDialog::inputList_ private
Input list.
Definition at line 134 of file SimulateDialog.hh.
Referenced by onSelection(), onUpdateValue(), setTexts(), and updateLists().
inputs_
std::vector<DataObject*> SimulateDialog::inputs_ private
List of input values.
Definition at line 152 of file SimulateDialog.hh.
Referenced by onFormatChanged(), onReset(), onTrigger(), onUpdateValue(), setInputValues(), setOutputValues(), updateLists(), and ~SimulateDialog().
inputSizer_
wxStaticBoxSizer* SimulateDialog::inputSizer_ private
Input operand sizer.
Definition at line 130 of file SimulateDialog.hh.
Referenced by createContents(), and setTexts().
modName_
std::string SimulateDialog::modName_ private
Module in which operation belongs to.
Definition at line 150 of file SimulateDialog.hh.
operation_
Operation* SimulateDialog::operation_ private
Bitmap for Trigger result.
Bitmap for Late Result result. Operation to be simulated.
Definition at line 146 of file SimulateDialog.hh.
Referenced by createState(), onReset(), onTrigger(), setTexts(), and ~SimulateDialog().
outputList_
wxListCtrl* SimulateDialog::outputList_ private
Output list.
Definition at line 136 of file SimulateDialog.hh.
Referenced by setTexts(), and updateLists().
outputs_
std::vector<DataObject*> SimulateDialog::outputs_ private
List of output values.
Definition at line 154 of file SimulateDialog.hh.
Referenced by onFormatChanged(), onReset(), setOutputValues(), updateLists(), and ~SimulateDialog().
outputSizer_
wxStaticBoxSizer* SimulateDialog::outputSizer_ private
Output operand sizer.
Definition at line 132 of file SimulateDialog.hh.
Referenced by createContents(), and setTexts().
pathName_
std::string SimulateDialog::pathName_ private
Path in which operation module belongs to.
Definition at line 148 of file SimulateDialog.hh.
updateValue_
NumberControl* SimulateDialog::updateValue_ private
Text control for updating input values.
Definition at line 138 of file SimulateDialog.hh.
Referenced by onUpdateValue().
The documentation for this class was generated from the following files:
SimulateDialog.hh
SimulateDialog.cc