OpenASIP: BlockImplementationFileDialog Class Reference
BlockImplementationFileDialog Class Reference
#include <BlockImplementationFileDialog.hh>
Public Member Functions
BlockImplementationFileDialog (wxWindow *parent, wxWindowID id, HDB::BlockImplementationFile &file)
virtual ~BlockImplementationFileDialog ()
Private Types
enum {
ID_LABEL_PATH = 10000 , ID_PATH , ID_LABEL_FORMAT , ID_FORMAT ,
ID_BROWSE , ID_LINE
}
Enumerated IDs for dialog widgets.
Private Member Functions
void onBrowse (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Creates the dialog contents.
Private Attributes
HDB::BlockImplementationFile & file_
BlockImplementationFile object to modify.
wxString path_
Block implementation file path.
int format_
Selected implementation file type.
Detailed Description
Dialog for editing BlockImplementationFile objects.
Definition at line 44 of file BlockImplementationFileDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerated IDs for dialog widgets.
Enumerator
ID_LABEL_PATH
ID_PATH
ID_LABEL_FORMAT
ID_FORMAT
ID_BROWSE
ID_LINE
Definition at line 56 of file BlockImplementationFileDialog.hh.
         {
        ID_LABEL_PATH = 10000,
        ID_PATH,
        ID_LABEL_FORMAT,
        ID_FORMAT,
        ID_BROWSE,
        ID_LINE
    };
Constructor & Destructor Documentation
BlockImplementationFileDialog()
BlockImplementationFileDialog::BlockImplementationFileDialog (wxWindow * parent, wxWindowID id, HDB::BlockImplementationFile & file)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog window.
file BlockImplementationFile object to modify.
Definition at line 64 of file BlockImplementationFileDialog.cc.
                                                                       :
    wxDialog(parent, id, _T("Parameter")),
    file_(file) {
    createContents(this, true, true);
    path_ = WxConversion::toWxString(file_.pathToFile());
    format_ = file_.format();
    FindWindow(ID_PATH)->SetValidator(wxTextValidator(wxFILTER_ASCII, &path_));
    FindWindow(ID_FORMAT)->SetValidator(wxGenericValidator(&format_));
    TransferDataToWindow();
}
References WxConversion::toWxString().
~BlockImplementationFileDialog()
BlockImplementationFileDialog::~BlockImplementationFileDialog () virtual
The Destructor.
Definition at line 84 of file BlockImplementationFileDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * BlockImplementationFileDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Creates the dialog contents.
Definition at line 185 of file BlockImplementationFileDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 3, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_PATH, wxT("Path:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_PATH, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_BROWSE, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_FORMAT, wxT("Format:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item5, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString strs6[] =
    {
        wxT("VHDL"),
        wxT("Verilog")
    };
    wxChoice *item6 = new wxChoice( parent, ID_FORMAT, wxDefaultPosition, wxSize(100,-1), 2, strs6, 0 );
    item1->Add( item6, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item7 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALL, 5 );
    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BROWSE, ID_FORMAT, ID_LABEL_FORMAT, ID_LABEL_PATH, ID_LINE, and ID_PATH.
onBrowse()
void BlockImplementationFileDialog::onBrowse (wxCommandEvent & event) private
Event handler for the Browse-button.
Displays a wxFileDialog for selecting the implementation file.
Definition at line 93 of file BlockImplementationFileDialog.cc.
{
    const HDBManager& manager = *wxGetApp().mainFrame().hdbManager();
    std::string hdbPath = manager.fileName();
    wxString defaultDir = WxConversion::toWxString(
    FileSystem::directoryOfPath(manager.fileName()).c_str());
    wxFileDialog dialog(
        this, _T("Choose a file"), defaultDir, _T(""),
        _T("VHDL files (*.vhd;*.vhdl)|*.vhd;*.vhdl|Verilog files (*.v)|*.v| All files (*.*)|*.*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    wxChoice *hdl_type = (wxChoice *)FindWindow(ID_FORMAT);
    dialog.SetFilterIndex(hdl_type->GetCurrentSelection());
    if (dialog.ShowModal() == wxID_OK) {
        std::string filename = WxConversion::toString(dialog.GetPath());
        std::string vhdlPath = FileSystem::directoryOfPath(filename);
        std::vector<std::string> vhdlPaths = Environment::vhdlPaths(hdbPath);
        for (std::vector<std::string>::iterator it = vhdlPaths.begin();
             it != vhdlPaths.end(); ++it) {
                 // check if VHDL path is relative to one of the search paths.
                 if (vhdlPath.substr(0, (*it).length()) == *it) {
                     filename = filename.substr((*it).length() + 1);
                     break;
                 }
             }
        path_ = WxConversion::toWxString(filename);
        TransferDataToWindow();
   }
}
References FileSystem::directoryOfPath(), HDB::HDBManager::fileName(), ID_FORMAT, path_, WxConversion::toString(), WxConversion::toWxString(), and Environment::vhdlPaths().
onOK()
void BlockImplementationFileDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 134 of file BlockImplementationFileDialog.cc.
{
    TransferDataFromWindow();
    path_ = path_.Trim(true).Trim(false);
    if (path_.IsEmpty()) {
        wxString message = _T("Path field must not be empty.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    // Attempt to find the file in search paths
    const HDBManager& manager = *wxGetApp().mainFrame().hdbManager();
    std::string hdbPath = manager.fileName();
    std::vector<std::string> vhdlPaths =
        Environment::vhdlPaths(hdbPath);
    try {
        std::string filename =
            FileSystem::findFileInSearchPaths(
                vhdlPaths, WxConversion::toString(path_));
        for (std::vector<std::string>::iterator it = vhdlPaths.begin();
             it != vhdlPaths.end(); ++it) {
                 if (filename.substr(0, (*it).length()) == *it) {
                     Application::logStream()
                         << filename << " in search path " << *it << std::endl;
                     filename = filename.substr((*it).length() + 1);
                     path_ = WxConversion::toWxString(filename);
                     break;
                 }
             }
    } catch (FileNotFound const& f) {
        wxString message = _T("File not found from the VHDL search paths.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    file_.setPathToFile(WxConversion::toString(path_));
    file_.setFormat((HDB::BlockImplementationFile::Format)format_);
    EndModal(wxID_OK);
}
References file_, HDB::HDBManager::fileName(), FileSystem::findFileInSearchPaths(), format_, Application::logStream(), path_, HDB::BlockImplementationFile::setFormat(), HDB::BlockImplementationFile::setPathToFile(), WxConversion::toString(), WxConversion::toWxString(), and Environment::vhdlPaths().
Member Data Documentation
file_
HDB::BlockImplementationFile& BlockImplementationFileDialog::file_ private
BlockImplementationFile object to modify.
Definition at line 69 of file BlockImplementationFileDialog.hh.
Referenced by onOK().
format_
int BlockImplementationFileDialog::format_ private
Selected implementation file type.
Definition at line 74 of file BlockImplementationFileDialog.hh.
Referenced by onOK().
path_
wxString BlockImplementationFileDialog::path_ private
Block implementation file path.
Definition at line 72 of file BlockImplementationFileDialog.hh.
Referenced by onBrowse(), and onOK().
The documentation for this class was generated from the following files:
BlockImplementationFileDialog.hh
BlockImplementationFileDialog.cc