OpenASIP: SchedulerCmdLineOptions Class Reference
SchedulerCmdLineOptions Class Reference
#include <SchedulerCmdLineOptions.hh>
Public Member Functions
SchedulerCmdLineOptions ()
virtual ~SchedulerCmdLineOptions ()
virtual void printVersion () const
virtual bool isMachineFileDefined () const
virtual std::string machineFile () const
virtual bool isOutputFileDefined () const
virtual std::string outputFile () const
virtual int schedulingWindowSize () const
virtual bool useRestrictedAliasAnalyzer () const
virtual bool renameRegisters () const
bool enableStackAA () const
bool enableOffsetAA () const
bool printResourceConstraints () const
virtual int ifConversionThreshold () const
virtual bool dumpIfConversionCFGs () const
virtual int lowMemModeThreshold () const
virtual bool isLoopOptDefined () const
virtual int bypassDistance () const
virtual int noDreBypassDistance () const
virtual int operandShareDistance () const
virtual bool killDeadResults () const
virtual FunctionNameList * noaliasFunctions () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Private Member Functions
SchedulerCmdLineOptions (const SchedulerCmdLineOptions &)
Copying forbidden.
SchedulerCmdLineOptions & operator= (const SchedulerCmdLineOptions &)
Assignment forbidden.
Static Private Attributes
static const std::string USAGE
Description of the command line usage of the Scheduler.
static const std::string SWL_TARGET_MACHINE = "adf"
static const std::string SWS_TARGET_MACHINE = "a"
static const std::string SWL_OUTPUT_FILE = "output"
static const std::string SWS_OUTPUT_FILE = "o"
static const std::string SWL_LOOP_FLAG = "loop"
static const std::string SWL_SCHEDULING_WINDOW
static const std::string SWL_STACK_AA = "stack-aa"
static const std::string SWL_OFFSET_AA = "offset-aa"
static const std::string SWL_RENAME_REGISTERS = "rename-registers"
static const std::string SWL_RESTRICTED_AA = "restricted-aa"
static const std::string SWL_IF_CONVERSION_THRESHOLD
static const std::string SWL_LOWMEM_MODE_THRESHOLD
static const std::string SWL_RESOURCE_CONSTRAINT_PRINTING
static const std::string SWL_KILL_DEAD_RESULTS = "kill-dead-results"
static const std::string SWL_NO_DRE_BYPASS_DISTANCE = "bypass-distance-nodre"
static const std::string SWL_BYPASS_DISTANCE = "bypass-distance"
static const std::string SWL_DUMP_IFCONVERSION_CFGS
static const std::string SWL_OPERAND_SHARE_DISTANCE = "operand-share-distance"
static const std::string SWL_NOALIAS_FUNCTIONS = "noalias-functions"
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line options for the command line interface of the Scheduler (schedule).
Definition at line 45 of file SchedulerCmdLineOptions.hh.
Constructor & Destructor Documentation
SchedulerCmdLineOptions() [1/2]
SchedulerCmdLineOptions::SchedulerCmdLineOptions ()
Constructor.
Definition at line 76 of file SchedulerCmdLineOptions.cc.
                                                : CmdLineOptions(USAGE) {
    addOption(
        new StringCmdLineOptionParser(
            SWL_TARGET_MACHINE, "Target machine (.adf file)",
            SWS_TARGET_MACHINE));
    addOption(
        new StringCmdLineOptionParser(
            SWL_OUTPUT_FILE, "Output file name.",
            SWS_OUTPUT_FILE));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_LOOP_FLAG, "Use loop optimizations."));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_SCHEDULING_WINDOW,
            "The scheduling window size in TTA instructions."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_RESTRICTED_AA,
            "Use restricted C language keyword in alias analyzis."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_STACK_AA, "Enable stack alias analyzer. On by default."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_RENAME_REGISTERS,
            "Rename already allocated registers during scheduler"));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_IF_CONVERSION_THRESHOLD,
            "The maximum number of moves in an if-structure to predicate "
            "when if-converting."));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_LOWMEM_MODE_THRESHOLD,
            "Move count of procedure which activates low-mem mode"
            "which saves memory from scheduler but "
            "disables some optimizations."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_OFFSET_AA, "Enable constant offset alias analyzer. On by default."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_RENAME_REGISTERS,
            "Rename already allocated registers during scheduler. "
            "On by default."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_RESOURCE_CONSTRAINT_PRINTING,
            "Print out the resource constraints that potentially limit the "
            "basic block's schedule."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_DUMP_IFCONVERSION_CFGS,
            "Dumps the control flow graphs before and after if-conversion."));
    addOption(
        new BoolCmdLineOptionParser(
            SWL_KILL_DEAD_RESULTS,
            "Kill dead results after bypass. On by default."));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_BYPASS_DISTANCE,
            "Bypass distance when dead result elimination can be used"));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_NO_DRE_BYPASS_DISTANCE,
            "Bypass distance when dead result elimination cannot be used"));
    addOption(
        new IntegerCmdLineOptionParser(
            SWL_OPERAND_SHARE_DISTANCE,
            "Operand sharing max distance"));
    addOption(
        new StringListCmdLineOptionParser(
            SWL_NOALIAS_FUNCTIONS,
            "List of functions which are scheduled with assumptions "
            "that there are no aliased memory accesses in these function "
            "This allows much more aggressive instruction scheduling, "
            "but will cause broken code if the code contains memory "
            "aliasing. Use with extreme caution!"));
}
References CmdLineParser::addOption(), SWL_BYPASS_DISTANCE, SWL_DUMP_IFCONVERSION_CFGS, SWL_IF_CONVERSION_THRESHOLD, SWL_KILL_DEAD_RESULTS, SWL_LOOP_FLAG, SWL_LOWMEM_MODE_THRESHOLD, SWL_NO_DRE_BYPASS_DISTANCE, SWL_NOALIAS_FUNCTIONS, SWL_OFFSET_AA, SWL_OPERAND_SHARE_DISTANCE, SWL_OUTPUT_FILE, SWL_RENAME_REGISTERS, SWL_RESOURCE_CONSTRAINT_PRINTING, SWL_RESTRICTED_AA, SWL_SCHEDULING_WINDOW, SWL_STACK_AA, SWL_TARGET_MACHINE, SWS_OUTPUT_FILE, and SWS_TARGET_MACHINE.
~SchedulerCmdLineOptions()
SchedulerCmdLineOptions::~SchedulerCmdLineOptions () virtual
Destructor.
Definition at line 179 of file SchedulerCmdLineOptions.cc.
{
}
SchedulerCmdLineOptions() [2/2]
SchedulerCmdLineOptions::SchedulerCmdLineOptions (const SchedulerCmdLineOptions &) private
Copying forbidden.
Member Function Documentation
bypassDistance()
int SchedulerCmdLineOptions::bypassDistance () const virtual
Returns the bypass limit when dead result elimination can be used.
By default returns -1 which results in using heuristics to define the maximum values.
Definition at line 327 of file SchedulerCmdLineOptions.cc.
{
    if (!findOption(SWL_BYPASS_DISTANCE)->isDefined()) {
        return -1;
    } else {
        return findOption(SWL_BYPASS_DISTANCE)->integer();
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_BYPASS_DISTANCE.
Referenced by BFEarlyBypasser::BFEarlyBypasser(), BFLateBypasses::BFLateBypasses(), CycleLookBackSoftwareBypasser::CycleLookBackSoftwareBypasser(), BUBasicBlockScheduler::handleDDG(), and BUBasicBlockScheduler::handleLoopDDG().
dumpIfConversionCFGs()
bool SchedulerCmdLineOptions::dumpIfConversionCFGs () const virtual
Definition at line 279 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_DUMP_IFCONVERSION_CFGS)) {
        return false;
    }
    return findOption(SWL_DUMP_IFCONVERSION_CFGS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_DUMP_IFCONVERSION_CFGS.
Referenced by SimpleIfConverter::handleControlFlowGraph().
enableOffsetAA()
bool SchedulerCmdLineOptions::enableOffsetAA () const
Definition at line 255 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_OFFSET_AA)) {
        return true;
    }
    return findOption(SWL_OFFSET_AA)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_OFFSET_AA.
enableStackAA()
bool SchedulerCmdLineOptions::enableStackAA () const
Definition at line 247 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_STACK_AA)) {
        return true;
    }
    return findOption(SWL_STACK_AA)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_STACK_AA.
ifConversionThreshold()
int SchedulerCmdLineOptions::ifConversionThreshold () const virtual
Returns the maximum number of moves in an if-structure which is still if-converted.
By default returns -1 which results in using heuristics to define the maximum values.
Definition at line 294 of file SchedulerCmdLineOptions.cc.
{
    if (!findOption(SWL_IF_CONVERSION_THRESHOLD)->isDefined()) {
        return -1;
    } else {
        return findOption(SWL_IF_CONVERSION_THRESHOLD)->integer();
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_IF_CONVERSION_THRESHOLD.
Referenced by SimpleIfConverter::SimpleIfConverter().
isLoopOptDefined()
bool SchedulerCmdLineOptions::isLoopOptDefined () const virtual
Return true if the loop opt switch was defined in the command line.
Returns
True if the loop opt switch was defined in the command line.
Definition at line 237 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWL_LOOP_FLAG)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_LOOP_FLAG.
Referenced by BBSchedulerController::handleBasicBlock().
isMachineFileDefined()
bool SchedulerCmdLineOptions::isMachineFileDefined () const virtual
Returns true if the target machine file is defined, false otherwise.
Returns
True if the target machine file is defined.
Definition at line 207 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWS_TARGET_MACHINE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWS_TARGET_MACHINE.
isOutputFileDefined()
bool SchedulerCmdLineOptions::isOutputFileDefined () const virtual
Returns true if the output file name is defined, false otherwise.
Returns
True if the output file name is defined.
Definition at line 227 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWS_OUTPUT_FILE)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWS_OUTPUT_FILE.
killDeadResults()
bool SchedulerCmdLineOptions::killDeadResults () const virtual
Definition at line 361 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_KILL_DEAD_RESULTS)) {
        return true;
    }
    return findOption(SWL_KILL_DEAD_RESULTS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_KILL_DEAD_RESULTS.
Referenced by BF2Scheduler::BF2Scheduler(), CycleLookBackSoftwareBypasser::CycleLookBackSoftwareBypasser(), BUBasicBlockScheduler::handleDDG(), and BUBasicBlockScheduler::handleLoopDDG().
lowMemModeThreshold()
int SchedulerCmdLineOptions::lowMemModeThreshold () const virtual
Returns the maximum number of moves in an if-structure which is still if-converted.
By default returns -1 which results in using heuristics to define the maximum values.
Definition at line 310 of file SchedulerCmdLineOptions.cc.
{
    if (!findOption(SWL_LOWMEM_MODE_THRESHOLD)->isDefined()) {
        return -1;
    } else {
        return findOption(SWL_LOWMEM_MODE_THRESHOLD)->integer();
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_LOWMEM_MODE_THRESHOLD.
Referenced by PreOptimizer::handleProcedure(), and BBSchedulerController::handleProcedure().
machineFile()
std::string SchedulerCmdLineOptions::machineFile () const virtual
Returns path to the target .adf file defined with the -a switch.
Returns
Target adf file defined in the command line.
Definition at line 197 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWS_TARGET_MACHINE)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWS_TARGET_MACHINE.
noaliasFunctions()
FunctionNameList * SchedulerCmdLineOptions::noaliasFunctions () const virtual
Returns the list of "noalias functions" that are scheduled with assumption of no aliasing memory accesses.
Definition at line 373 of file SchedulerCmdLineOptions.cc.
{
    FunctionNameList* funcs = new FunctionNameList();
    CmdLineOptionParser* opt = findOption(SWL_NOALIAS_FUNCTIONS);
    if (opt == NULL)
        return funcs;
    for (int i = 1; i <= opt->listSize(); ++i) {
        funcs->insert(opt->String(i));
    }
    return funcs;
}
References CmdLineParser::findOption(), CmdLineOptionParser::listSize(), CmdLineOptionParser::String(), and SWL_NOALIAS_FUNCTIONS.
noDreBypassDistance()
int SchedulerCmdLineOptions::noDreBypassDistance () const virtual
Returns the bypass limit when dead result elimination cannot be used.
By default returns -1 which results in using heuristics to define the maximum values.
Definition at line 352 of file SchedulerCmdLineOptions.cc.
{
    if (!findOption(SWL_NO_DRE_BYPASS_DISTANCE)->isDefined()) {
        return -1;
    } else {
        return findOption(SWL_NO_DRE_BYPASS_DISTANCE)->integer();
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_NO_DRE_BYPASS_DISTANCE.
Referenced by CycleLookBackSoftwareBypasser::CycleLookBackSoftwareBypasser().
operandShareDistance()
int SchedulerCmdLineOptions::operandShareDistance () const virtual
Definition at line 336 of file SchedulerCmdLineOptions.cc.
{
    if (!findOption(SWL_OPERAND_SHARE_DISTANCE)->isDefined()) {
        return -1;
    } else {
        return findOption(SWL_OPERAND_SHARE_DISTANCE)->integer();
    }
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SWL_OPERAND_SHARE_DISTANCE.
Referenced by BFShareOperands::BFShareOperands(), and BFShareOperandsLate::BFShareOperandsLate().
operator=()
SchedulerCmdLineOptions & SchedulerCmdLineOptions::operator= (const SchedulerCmdLineOptions &) private
Assignment forbidden.
outputFile()
std::string SchedulerCmdLineOptions::outputFile () const virtual
Returns path to the output file defined with the -o switch.
Returns
Output file name defined in the command line.
Definition at line 217 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWS_OUTPUT_FILE)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and SWS_OUTPUT_FILE.
printResourceConstraints()
bool SchedulerCmdLineOptions::printResourceConstraints () const
Definition at line 271 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_RESOURCE_CONSTRAINT_PRINTING)) {
        return false;
    }
    return findOption(SWL_RESOURCE_CONSTRAINT_PRINTING)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_RESOURCE_CONSTRAINT_PRINTING.
Referenced by BBSchedulerController::executeDDGPass().
printVersion()
void SchedulerCmdLineOptions::printVersion () const virtual
Print the version of the user interface.
Implements CmdLineOptions.
Reimplemented in LLVMTCECmdLineOptions.
Definition at line 186 of file SchedulerCmdLineOptions.cc.
{
    cout << "schedule - OpenASIP TTA Scheduler command line interface "
         <<  Application::TCEVersionString() << endl;
}
References Application::TCEVersionString().
renameRegisters()
bool SchedulerCmdLineOptions::renameRegisters () const virtual
Definition at line 263 of file SchedulerCmdLineOptions.cc.
{
    if (!optionGiven(SWL_RENAME_REGISTERS)) {
        return true;
    }
    return findOption(SWL_RENAME_REGISTERS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), CmdLineOptions::optionGiven(), and SWL_RENAME_REGISTERS.
schedulingWindowSize()
virtual int SchedulerCmdLineOptions::schedulingWindowSize () const inline virtual
Definition at line 58 of file SchedulerCmdLineOptions.hh.
{
        return findOption(SWL_SCHEDULING_WINDOW)->isDefined() ?
            findOption(SWL_SCHEDULING_WINDOW)->integer() :
            140;
    }
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), CmdLineOptionParser::isDefined(), and SWL_SCHEDULING_WINDOW.
useRestrictedAliasAnalyzer()
bool SchedulerCmdLineOptions::useRestrictedAliasAnalyzer () const virtual
Definition at line 242 of file SchedulerCmdLineOptions.cc.
{
    return findOption(SWL_RESTRICTED_AA)->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and SWL_RESTRICTED_AA.
Member Data Documentation
SWL_BYPASS_DISTANCE
const std::string SchedulerCmdLineOptions::SWL_BYPASS_DISTANCE = "bypass-distance" static private
Definition at line 109 of file SchedulerCmdLineOptions.hh.
Referenced by bypassDistance(), and SchedulerCmdLineOptions().
SWL_DUMP_IFCONVERSION_CFGS
const std::string SchedulerCmdLineOptions::SWL_DUMP_IFCONVERSION_CFGS static private
Initial value:
=
    "dump-ifconversion-cfgs"
Definition at line 110 of file SchedulerCmdLineOptions.hh.
Referenced by dumpIfConversionCFGs(), and SchedulerCmdLineOptions().
SWL_IF_CONVERSION_THRESHOLD
const std::string SchedulerCmdLineOptions::SWL_IF_CONVERSION_THRESHOLD static private
Initial value:
=
    "if-conversion-threshold"
Definition at line 104 of file SchedulerCmdLineOptions.hh.
Referenced by ifConversionThreshold(), and SchedulerCmdLineOptions().
SWL_KILL_DEAD_RESULTS
const std::string SchedulerCmdLineOptions::SWL_KILL_DEAD_RESULTS = "kill-dead-results" static private
Definition at line 107 of file SchedulerCmdLineOptions.hh.
Referenced by killDeadResults(), and SchedulerCmdLineOptions().
SWL_LOOP_FLAG
const std::string SchedulerCmdLineOptions::SWL_LOOP_FLAG = "loop" static private
Definition at line 98 of file SchedulerCmdLineOptions.hh.
Referenced by isLoopOptDefined(), and SchedulerCmdLineOptions().
SWL_LOWMEM_MODE_THRESHOLD
const std::string SchedulerCmdLineOptions::SWL_LOWMEM_MODE_THRESHOLD static private
Initial value:
=
    "lowmem-mode-threshold"
Definition at line 105 of file SchedulerCmdLineOptions.hh.
Referenced by lowMemModeThreshold(), and SchedulerCmdLineOptions().
SWL_NO_DRE_BYPASS_DISTANCE
const std::string SchedulerCmdLineOptions::SWL_NO_DRE_BYPASS_DISTANCE = "bypass-distance-nodre" static private
Definition at line 108 of file SchedulerCmdLineOptions.hh.
Referenced by noDreBypassDistance(), and SchedulerCmdLineOptions().
SWL_NOALIAS_FUNCTIONS
const std::string SchedulerCmdLineOptions::SWL_NOALIAS_FUNCTIONS = "noalias-functions" static private
Definition at line 112 of file SchedulerCmdLineOptions.hh.
Referenced by noaliasFunctions(), and SchedulerCmdLineOptions().
SWL_OFFSET_AA
const std::string SchedulerCmdLineOptions::SWL_OFFSET_AA = "offset-aa" static private
Definition at line 101 of file SchedulerCmdLineOptions.hh.
Referenced by enableOffsetAA(), and SchedulerCmdLineOptions().
SWL_OPERAND_SHARE_DISTANCE
const std::string SchedulerCmdLineOptions::SWL_OPERAND_SHARE_DISTANCE = "operand-share-distance" static private
Definition at line 111 of file SchedulerCmdLineOptions.hh.
Referenced by operandShareDistance(), and SchedulerCmdLineOptions().
SWL_OUTPUT_FILE
const std::string SchedulerCmdLineOptions::SWL_OUTPUT_FILE = "output" static private
Definition at line 96 of file SchedulerCmdLineOptions.hh.
Referenced by SchedulerCmdLineOptions().
SWL_RENAME_REGISTERS
const std::string SchedulerCmdLineOptions::SWL_RENAME_REGISTERS = "rename-registers" static private
Definition at line 102 of file SchedulerCmdLineOptions.hh.
Referenced by renameRegisters(), and SchedulerCmdLineOptions().
SWL_RESOURCE_CONSTRAINT_PRINTING
const std::string SchedulerCmdLineOptions::SWL_RESOURCE_CONSTRAINT_PRINTING static private
Initial value:
=
    "print-resource-constraints"
Definition at line 106 of file SchedulerCmdLineOptions.hh.
Referenced by printResourceConstraints(), and SchedulerCmdLineOptions().
SWL_RESTRICTED_AA
const std::string SchedulerCmdLineOptions::SWL_RESTRICTED_AA = "restricted-aa" static private
Definition at line 103 of file SchedulerCmdLineOptions.hh.
Referenced by SchedulerCmdLineOptions(), and useRestrictedAliasAnalyzer().
SWL_SCHEDULING_WINDOW
const std::string SchedulerCmdLineOptions::SWL_SCHEDULING_WINDOW static private
Initial value:
=
    "scheduling-window-size"
Definition at line 99 of file SchedulerCmdLineOptions.hh.
Referenced by SchedulerCmdLineOptions(), and schedulingWindowSize().
SWL_STACK_AA
const std::string SchedulerCmdLineOptions::SWL_STACK_AA = "stack-aa" static private
Definition at line 100 of file SchedulerCmdLineOptions.hh.
Referenced by enableStackAA(), and SchedulerCmdLineOptions().
SWL_TARGET_MACHINE
const std::string SchedulerCmdLineOptions::SWL_TARGET_MACHINE = "adf" static private
Definition at line 94 of file SchedulerCmdLineOptions.hh.
Referenced by SchedulerCmdLineOptions().
SWS_OUTPUT_FILE
const std::string SchedulerCmdLineOptions::SWS_OUTPUT_FILE = "o" static private
Definition at line 97 of file SchedulerCmdLineOptions.hh.
Referenced by isOutputFileDefined(), outputFile(), and SchedulerCmdLineOptions().
SWS_TARGET_MACHINE
const std::string SchedulerCmdLineOptions::SWS_TARGET_MACHINE = "a" static private
Definition at line 95 of file SchedulerCmdLineOptions.hh.
Referenced by isMachineFileDefined(), machineFile(), and SchedulerCmdLineOptions().
USAGE
const std::string SchedulerCmdLineOptions::USAGE static private
Initial value:
=
    "Usage: schedule [OPTION]... SOURCE\n"
    "Schedule SOURCE binary with the given options\n"
    "Example: schedule -a mach.adf hello.tpef"
Description of the command line usage of the Scheduler.
Definition at line 93 of file SchedulerCmdLineOptions.hh.
The documentation for this class was generated from the following files:
SchedulerCmdLineOptions.hh
SchedulerCmdLineOptions.cc