OpenASIP: OperationExecutor Class Reference
OperationExecutor Class Reference abstract
#include <OperationExecutor.hh>
Public Member Functions
OperationExecutor ()
OperationExecutor (FUState &parent)
virtual ~OperationExecutor ()
FUState & parent () const
void setParent (FUState &parent)
void addBinding (int io, PortState &port)
PortState & binding (int io) const
virtual void startOperation (Operation &op)=0
bool hasPendingOperations () const
virtual void advanceClock ()=0
virtual OperationExecutor * copy ()=0
virtual void setContext (OperationContext &context)=0
virtual void reset ()
Protected Attributes
std::vector< PortState * > bindings_
PortStates that are bound to a certain input or output operand.
bool hasPendingOperations_
This is set to true if the OperationExecutor is not in 'idle' mode.
Private Member Functions
OperationExecutor & operator= (const OperationExecutor &)
Assignment not allowed.
Private Attributes
FUState * parent_
Parent of the executor.
Detailed Description
Executes operations in function units.
Definition at line 49 of file OperationExecutor.hh.
Constructor & Destructor Documentation
OperationExecutor() [1/2]
OperationExecutor::OperationExecutor () inline
Definition at line 51 of file OperationExecutor.hh.
: hasPendingOperations_(false), parent_(NULL) {}
OperationExecutor() [2/2]
OperationExecutor::OperationExecutor (FUState & parent) explicit
Constructor.
Parameters
parent Parent FUState.
Definition at line 48 of file OperationExecutor.cc.
                                                    :
     hasPendingOperations_(false), parent_(&parent) {
}
~OperationExecutor()
OperationExecutor::~OperationExecutor () virtual
Destructor.
Definition at line 55 of file OperationExecutor.cc.
{
}
Member Function Documentation
addBinding()
void OperationExecutor::addBinding (int io, PortState & port)
Adds binding of operand to a port.
Parameters
io Operand index.
port Port to be bind.
Exceptions
IllegalRegistration If parent of the port is not the same as the parent of the executor.
Definition at line 67 of file OperationExecutor.cc.
{
    if (io > static_cast<int>(bindings_.size()) - 1) {
        bindings_.resize(io, NULL);
    }
    if (&port.parent() != parent_) {
        string msg = "Parent of the port and executors differs";
        throw IllegalRegistration(__FILE__, __LINE__, __func__, msg);
    }
    if (bindings_[io - 1] != NULL) {
        string msg = "Operand with given index has been already bound"
            " to a port";
        throw IllegalRegistration(__FILE__, __LINE__, __func__, msg);
    }
    bindings_[io - 1] = &port;
}
References __func__, bindings_, PortState::parent(), and parent_.
Referenced by MachineStateBuilder::bindPortsToOperands(), and FUState::replaceOperationExecutor().
advanceClock()
virtual void OperationExecutor::advanceClock () pure virtual
Implemented in ConflictDetectingOperationExecutor, MultiLatencyOperationExecutor, OneCycleOperationExecutor, SimpleOperationExecutor, and TransportPipeline.
Referenced by FUState::advanceClock().
binding()
PortState & OperationExecutor::binding (int io) const
Referenced by SimpleOperationExecutor::advanceClock(), FUState::replaceOperationExecutor(), FUState::sameBindings(), MultiLatencyOperationExecutor::startOperation(), SimpleOperationExecutor::startOperation(), and TransportPipeline::startOperation().
copy()
virtual OperationExecutor * OperationExecutor::copy () pure virtual
Implemented in ConflictDetectingOperationExecutor, MultiLatencyOperationExecutor, OneCycleOperationExecutor, SimpleOperationExecutor, and TransportPipeline.
Referenced by FUState::addOperationExecutor().
hasPendingOperations()
bool OperationExecutor::hasPendingOperations () const
Referenced by FUState::advanceClock(), and FUState::endClock().
operator=()
OperationExecutor & OperationExecutor::operator= (const OperationExecutor &) private
Assignment not allowed.
parent()
FUState & OperationExecutor::parent () const
Referenced by FUState::replaceOperationExecutor(), setParent(), and TransportPipeline::TransportPipeline().
reset()
void OperationExecutor::reset () virtual
Reimplemented in MultiLatencyOperationExecutor.
Definition at line 87 of file OperationExecutor.cc.
{
    return;
}
setContext()
virtual void OperationExecutor::setContext (OperationContext & context) pure virtual
Implemented in MultiLatencyOperationExecutor, OneCycleOperationExecutor, SimpleOperationExecutor, and TransportPipeline.
Referenced by FUState::addOperationExecutor(), and FUState::replaceOperationExecutor().
setParent()
void OperationExecutor::setParent (FUState & parent) inline
Definition at line 56 of file OperationExecutor.hh.
{ parent_ = &parent; }
References parent(), and parent_.
Referenced by FUState::replaceOperationExecutor().
startOperation()
virtual void OperationExecutor::startOperation (Operation & op) pure virtual
Implemented in ConflictDetectingOperationExecutor, MultiLatencyOperationExecutor, OneCycleOperationExecutor, SimpleOperationExecutor, and TransportPipeline.
Referenced by FUState::endClock().
Member Data Documentation
bindings_
std::vector<PortState*> OperationExecutor::bindings_ protected
PortStates that are bound to a certain input or output operand.
Definition at line 70 of file OperationExecutor.hh.
Referenced by addBinding(), and OneCycleOperationExecutor::initializeIOVector().
hasPendingOperations_
bool OperationExecutor::hasPendingOperations_ protected
This is set to true if the OperationExecutor is not in 'idle' mode.
Definition at line 73 of file OperationExecutor.hh.
Referenced by ConflictDetectingOperationExecutor::advanceClock(), MultiLatencyOperationExecutor::advanceClock(), OneCycleOperationExecutor::advanceClock(), SimpleOperationExecutor::advanceClock(), MultiLatencyOperationExecutor::MultiLatencyOperationExecutor(), MultiLatencyOperationExecutor::reset(), SimpleOperationExecutor::SimpleOperationExecutor(), ConflictDetectingOperationExecutor::startOperation(), MultiLatencyOperationExecutor::startOperation(), OneCycleOperationExecutor::startOperation(), and SimpleOperationExecutor::startOperation().
parent_
FUState* OperationExecutor::parent_ private
Parent of the executor.
Definition at line 79 of file OperationExecutor.hh.
Referenced by addBinding(), and setParent().
The documentation for this class was generated from the following files:
OperationExecutor.hh
OperationExecutor.cc