OpenASIP: HDLTemplateInstantiator Class Reference
HDLTemplateInstantiator Class Reference
#include <HDLTemplateInstantiator.hh>
Public Member Functions
HDLTemplateInstantiator ()
HDLTemplateInstantiator (const TCEString &entityStr)
void setEntityString (const TCEString &entityStr)
void replacePlaceholder (const std::string &key, const std::string &replacer, bool append=false)
void replacePlaceholderFromFile (const std::string &key, const Path &filePath, bool append=false)
void instantiateTemplateFile (const std::string &templateFile, const std::string &dstFile)
Private Types
typedef TCEString PlaceholderKey
typedef TCEString Replacer
typedef std::map< PlaceholderKey, Replacer > ReplacerMap
Private Member Functions
void fillPlaceholders (TCEString &str)
TCEString findPlaceholder (const TCEString &str)
TCEString getPlaceholderKey (const TCEString &str)
TCEString getPlaceholderDefault (const TCEString &str)
Private Attributes
TCEString entityStr_
ReplacerMap replacers_
Static Private Attributes
static const std::string PLACEHOLDERSEPARATOR = ","
static const std::string PLACEHOLDERBEGIN
static const std::string PLACEHOLDEREND = ">>"
Friends
class HDLTemplateInstantiatorTest
Detailed Description
Helper class for instantiating HDL template files.
Definition at line 45 of file HDLTemplateInstantiator.hh.
Member Typedef Documentation
PlaceholderKey
typedef TCEString HDLTemplateInstantiator::PlaceholderKey private
Definition at line 65 of file HDLTemplateInstantiator.hh.
Replacer
typedef TCEString HDLTemplateInstantiator::Replacer private
Definition at line 66 of file HDLTemplateInstantiator.hh.
ReplacerMap
typedef std::map<PlaceholderKey, Replacer> HDLTemplateInstantiator::ReplacerMap private
Definition at line 67 of file HDLTemplateInstantiator.hh.
Constructor & Destructor Documentation
HDLTemplateInstantiator() [1/2]
HDLTemplateInstantiator::HDLTemplateInstantiator ()
Definition at line 42 of file HDLTemplateInstantiator.cc.
    : HDLTemplateInstantiator(TCEString()) {}
HDLTemplateInstantiator() [2/2]
HDLTemplateInstantiator::HDLTemplateInstantiator (const TCEString & entityStr)
Definition at line 45 of file HDLTemplateInstantiator.cc.
    : entityStr_(entityStr), replacers_() {}
Member Function Documentation
fillPlaceholders()
void HDLTemplateInstantiator::fillPlaceholders (TCEString & str) private
Fills all placeholder templates with added replace strings by key.
The placeholder markers are in form "<<placeholder,key>>" or "<<placeholder,key,default-value>>". If no replacer is not found for the key the placeholder template is replaced with empty string or default-value if defined.
Parameters
str The string to search and fill placeholders.
Definition at line 153 of file HDLTemplateInstantiator.cc.
{
    TCEString target(str);
    TCEString placeholder;
    while (!(placeholder = findPlaceholder(target)).empty()) {
        TCEString replacer("");
        TCEString key = getPlaceholderKey(placeholder);
        if (replacers_.count(key)) {
            replacer = replacers_[key];
        } else {
            replacer = getPlaceholderDefault(placeholder);
        }
        target.replaceString(placeholder, replacer);
    }
    // Correct indentation
    if (!target.empty()) {
        TCEString identation("");
        unsigned int i = 0;
        while (i < target.size() && target.at(i) == ' ') {
            identation.append(" ");
            i++;
        }
        // Note: only LF newline convention is considered.
        target.replaceString("\n", "\n" + identation);
    }
    str = target;
}
References findPlaceholder(), getPlaceholderDefault(), getPlaceholderKey(), replacers_, and TCEString::replaceString().
Referenced by instantiateTemplateFile().
findPlaceholder()
TCEString HDLTemplateInstantiator::findPlaceholder (const TCEString & str) private
Searches placeholder template over given string.
Parameters
str The string to search over for placeholder template.
Returns
The placeholder string or empty string if not found.
Definition at line 189 of file HDLTemplateInstantiator.cc.
{
    size_t beginpos = str.find(PLACEHOLDERBEGIN);
    if (beginpos == std::string::npos) {
        return "";
    }
    size_t endpos =
        str.find(PLACEHOLDEREND, beginpos + PLACEHOLDERBEGIN.size());
    if (endpos == std::string::npos) {
        return "";
    }
    TCEString placeholder;
    placeholder =
        str.substr(beginpos, endpos - beginpos + PLACEHOLDEREND.size());
    return placeholder;
}
References PLACEHOLDERBEGIN, and PLACEHOLDEREND.
Referenced by fillPlaceholders(), getPlaceholderDefault(), and getPlaceholderKey().
getPlaceholderDefault()
TCEString HDLTemplateInstantiator::getPlaceholderDefault (const TCEString & str) private
Searches placeholder template over given string and returns its default part.
The placeholder template is in form of <placeholder,keystring,default> and this function return default part.
Definition at line 247 of file HDLTemplateInstantiator.cc.
{
    TCEString placeholder = findPlaceholder(str);
    if (placeholder.empty()) {
        return "";
    }
    int count = 0;
    for (size_t offset = placeholder.find(PLACEHOLDERSEPARATOR);
         offset != std::string::npos;
         offset = placeholder.find(
             PLACEHOLDERSEPARATOR, offset + PLACEHOLDERSEPARATOR.size())) {
        count++;
    }
    if (count == 2) {
        size_t beginpos = placeholder.rfind(PLACEHOLDERSEPARATOR);
        size_t endpos = placeholder.rfind(PLACEHOLDEREND);
        if (beginpos == std::string::npos || endpos == std::string::npos) {
            return "";
        }
        assert(endpos >= beginpos);
        TCEString defaultStr;
        defaultStr = placeholder.substr(
            beginpos + PLACEHOLDERSEPARATOR.size(),
            endpos - beginpos - PLACEHOLDERSEPARATOR.size());
        return StringTools::trim(defaultStr);
    } else {
        return "";
    }
}
References assert, findPlaceholder(), PLACEHOLDEREND, PLACEHOLDERSEPARATOR, and StringTools::trim().
Referenced by fillPlaceholders().
getPlaceholderKey()
TCEString HDLTemplateInstantiator::getPlaceholderKey (const TCEString & str) private
Searches placeholder template over given string and returns its key.
The placeholder template is in form of <placeholder, keystring, default> and this function return keystring part.
Parameters
str The string to search over for placeholder template
Returns
Key for the placeholder or empty string if not found.
Definition at line 215 of file HDLTemplateInstantiator.cc.
{
    TCEString placeholder = findPlaceholder(str);
    if (placeholder.empty()) {
        return "";
    }
    // todo Better field separation
    size_t beginpos = placeholder.find(PLACEHOLDERBEGIN);
    size_t midpos = placeholder.rfind(PLACEHOLDERSEPARATOR);
    size_t endpos = placeholder.find(PLACEHOLDEREND);
    if (beginpos == std::string::npos || endpos == std::string::npos) {
        return "";
    }
    // Check for optional default value field
    if ((beginpos + PLACEHOLDERBEGIN.size()) < midpos && midpos < endpos) {
        endpos = midpos;
    }
    assert(endpos >= beginpos);
    TCEString key = placeholder.substr(
        beginpos + PLACEHOLDERBEGIN.size(),
        endpos - beginpos - PLACEHOLDERBEGIN.size());
    return StringTools::trim(key);
}
References assert, findPlaceholder(), PLACEHOLDERBEGIN, PLACEHOLDEREND, PLACEHOLDERSEPARATOR, and StringTools::trim().
Referenced by fillPlaceholders().
instantiateTemplateFile()
void HDLTemplateInstantiator::instantiateTemplateFile (const std::string & templateFile, const std::string & dstFile)
Creates a target HDL file from a HDL template, replacing certain magic strings with certain variable contents.
Currently supported magic strings: ENTITY_STR The entity name string used to make entities unique. Same as the toplevel entity name.
Definition at line 113 of file HDLTemplateInstantiator.cc.
{
    std::ifstream input(templateFile.c_str());
    if (!input.is_open())
        throw UnreachableStream(
            __FILE__, __LINE__, __func__,
            TCEString("Could not open ") + templateFile + " for reading.");
    std::ofstream output(dstFile.c_str(), std::ios::trunc);
    if (!output.is_open())
        throw UnreachableStream(
            __FILE__, __LINE__, __func__,
            TCEString("Could not open ") + dstFile + " for writing.");
    while (!input.eof()) {
        char line_buf[1024];
        input.getline(line_buf, 1024);
        TCEString line(line_buf);
        line.replaceString("ENTITY_STR", entityStr_);
        fillPlaceholders(line);
        output << line << std::endl;
    }
    input.close();
    output.close();
}
References __func__, entityStr_, fillPlaceholders(), and TCEString::replaceString().
Referenced by AlmaIFIntegrator::addAlmaifFiles(), ProGe::BlockSourceCopier::copyProcessorSpecific(), ProGeTestBenchGenerator::copyTestBenchFiles(), AlmaIFIntegrator::generateIntegratedTestbench(), ProGe::RV32MicroCodeGenerator::generateWrapper(), ProGe::BlockSourceCopier::instantiateHDLTemplate(), MemoryGenerator::instantiateTemplate(), ProGe::LoopBufferBlock::write(), ProGe::SinglePortByteMaskSSRAMBlock::write(), ProGe::SinglePortSSRAMBlock::write(), and ProGe::TestBenchBlock::write().
replacePlaceholder()
void HDLTemplateInstantiator::replacePlaceholder (const std::string & key, const std::string & replacer, bool append = false)
Adds replace string for the template placeholder by key.
During HDL template instantiation all placeholders by the key will be replaced with given replace string.
Parameters
key The key to identify placeholder.
replacer The string to replace the placeholder.
append Appends the given string to the existing placeholder filler at the key.
Exceptions
KeyAlreadyExists If a placeholder is already filled by the key and append flag is false.
Definition at line 62 of file HDLTemplateInstantiator.cc.
{
    // todo: add rule for key (all uppercase)?
    if (append) {
        replacers_[key] += replacer;
    } else {
        if (replacers_.count(key)) {
            THROW_EXCEPTION(
                KeyAlreadyExists,
                "The placeholder \"" + key + "\" is already filled. ");
        }
        replacers_.insert(std::pair<PlaceholderKey, Replacer>(key, replacer));
    }
}
References replacers_, and THROW_EXCEPTION.
Referenced by AlmaIFIntegrator::addAlmaifFiles(), DefaultICDecoderGenerator::generate(), ProGe::RV32MicroCodeGenerator::generateOperationLatencyLogic(), ProGe::ProcessorGenerator::generateProcessor(), ProGe::RV32MicroCodeGenerator::generateWrapper(), AlmaIFIntegrator::initAlmaifBlock(), replacePlaceholderFromFile(), ProGe::LoopBufferBlock::write(), and ProGe::TestBenchBlock::write().
replacePlaceholderFromFile()
void HDLTemplateInstantiator::replacePlaceholderFromFile (const std::string & key, const Path & filePath, bool append = false)
Adds replace string from file for the template placeholder by key.
During HDL template instantiation all placeholders by the key will be replaced with given replace string.
Parameters
key The key to identify placeholder.
replacer The string to replace the placeholder.
append Appends the given string to the existing placeholder filler at the key.
Definition at line 89 of file HDLTemplateInstantiator.cc.
{
    std::string snippetFileName = filePath;
    std::ifstream snippetfile(snippetFileName.c_str());
    if (!snippetfile.is_open()) {
        THROW_EXCEPTION(
            UnreachableStream, "Could not open snippet file: \"" +
                                   snippetFileName + "\" for reading.");
    }
    std::string str(
        (std::istreambuf_iterator<char>(snippetfile)),
        std::istreambuf_iterator<char>());
    replacePlaceholder(key, str, append);
}
References replacePlaceholder(), and THROW_EXCEPTION.
Referenced by AlmaIFIntegrator::addAlmaifFiles(), AlmaIFIntegrator::connectCoreMemories(), DefaultICDecoderGenerator::generate(), AlmaIFIntegrator::generateIntegratedTestbench(), AlmaIFIntegrator::initAlmaifBlock(), and ProGe::LoopBufferBlock::write().
setEntityString()
void HDLTemplateInstantiator::setEntityString (const TCEString & entityStr) inline
Definition at line 51 of file HDLTemplateInstantiator.hh.
{
        entityStr_ = entityStr; }
References entityStr_.
Referenced by ProGe::BlockSourceCopier::BlockSourceCopier(), ProGeTestBenchGenerator::copyTestBenchFiles(), ProGeTestBenchGenerator::createProcArchVhdl(), and MemoryGenerator::instantiateTemplate().
Friends And Related Symbol Documentation
HDLTemplateInstantiatorTest
friend class HDLTemplateInstantiatorTest friend
Definition at line 47 of file HDLTemplateInstantiator.hh.
Member Data Documentation
entityStr_
TCEString HDLTemplateInstantiator::entityStr_ private
Definition at line 78 of file HDLTemplateInstantiator.hh.
Referenced by instantiateTemplateFile(), and setEntityString().
PLACEHOLDERBEGIN
const std::string HDLTemplateInstantiator::PLACEHOLDERBEGIN static private
Initial value:
=
    "<<placeholder" + PLACEHOLDERSEPARATOR
Definition at line 75 of file HDLTemplateInstantiator.hh.
Referenced by findPlaceholder(), and getPlaceholderKey().
PLACEHOLDEREND
const std::string HDLTemplateInstantiator::PLACEHOLDEREND = ">>" static private
Definition at line 76 of file HDLTemplateInstantiator.hh.
Referenced by findPlaceholder(), getPlaceholderDefault(), and getPlaceholderKey().
PLACEHOLDERSEPARATOR
const std::string HDLTemplateInstantiator::PLACEHOLDERSEPARATOR = "," static private
Definition at line 74 of file HDLTemplateInstantiator.hh.
Referenced by getPlaceholderDefault(), and getPlaceholderKey().
replacers_
ReplacerMap HDLTemplateInstantiator::replacers_ private
Definition at line 79 of file HDLTemplateInstantiator.hh.
Referenced by fillPlaceholders(), and replacePlaceholder().
The documentation for this class was generated from the following files:
HDLTemplateInstantiator.hh
HDLTemplateInstantiator.cc