OpenASIP: AddSocketEntryCmd Class Reference
AddSocketEntryCmd Class Reference
#include <AddSocketEntryCmd.hh>
Public Member Functions
AddSocketEntryCmd ()
virtual ~AddSocketEntryCmd ()
virtual bool Do ()
virtual int id () const
virtual AddSocketEntryCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new socket entries to a HDB.
Definition at line 41 of file AddSocketEntryCmd.hh.
Constructor & Destructor Documentation
AddSocketEntryCmd()
AddSocketEntryCmd::AddSocketEntryCmd ()
The Constructor.
Definition at line 45 of file AddSocketEntryCmd.cc.
                                     :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_SOCKET_ENTRY, NULL) {
}
Referenced by create().
~AddSocketEntryCmd()
AddSocketEntryCmd::~AddSocketEntryCmd () virtual
The Destructor.
Definition at line 53 of file AddSocketEntryCmd.cc.
{
}
Member Function Documentation
create()
AddSocketEntryCmd * AddSocketEntryCmd::create () const virtual
Creates and returns new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 103 of file AddSocketEntryCmd.cc.
{
    return new AddSocketEntryCmd();
}
References AddSocketEntryCmd().
Do()
bool AddSocketEntryCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file AddSocketEntryCmd.cc.
                      {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    RowID id = manager->addSocketEntry();
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectSocketEntry(id);
    return true;
}
References HDB::HDBManager::addSocketEntry().
icon()
std::string AddSocketEntryCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 81 of file AddSocketEntryCmd.cc.
{
    return "";
}
id()
int AddSocketEntryCmd::id () const virtual
Returns command identifier for this command.
Returns
Command identifier of this command.
Implements GUICommand.
Definition at line 92 of file AddSocketEntryCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_SOCKET_ENTRY;
}
References HDBEditorConstants::COMMAND_ADD_SOCKET_ENTRY.
isEnabled()
bool AddSocketEntryCmd::isEnabled () virtual
Returns true, if the command should be enabled in the menu/toolbar.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 114 of file AddSocketEntryCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddSocketEntryCmd.hh
AddSocketEntryCmd.cc