OpenASIP: BFShareOperandLate Class Reference
BFShareOperandLate Class Reference
#include <BFShareOperandLate.hh>
Public Member Functions
BFShareOperandLate (BF2Scheduler &sched, MoveNode &removed, MoveNode &scheduled)
virtual bool operator() ()
virtual ~BFShareOperandLate ()
Public Member Functions inherited from BFShareOperand
BFShareOperand (BF2Scheduler &sched, MoveNode &removed, MoveNode &shared)
virtual ~BFShareOperand ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
virtual void undoOnlyMe ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Private Member Functions
void revert (int cycle)
Private Attributes
int originalCycle_
const TTAMachine::Bus * originalRemovedBus_
const TTAMachine::Bus * originalSharedBus_
const TTAMachine::Bus * originalRemovedPrologBus_
const TTAMachine::Bus * originalSharedPrologBus_
int removedImmWriteCycle_
int removedPrologImmWriteCycle_
const TTAMachine::ImmediateUnit * removedImmu_
int removedImmRegIndex_
int sharedImmWriteCycle_
int sharedPrologImmWriteCycle_
const TTAMachine::ImmediateUnit * sharedImmu_
int sharedImmRegIndex_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Attributes inherited from BFShareOperand
MoveNode & removed_
MoveNode & shared_
std::vector< ProgramOperationPtr > ops_
std::set< ProgramOperationPtr > createdPrologPOs_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 46 of file BFShareOperandLate.hh.
Constructor & Destructor Documentation
BFShareOperandLate()
BFShareOperandLate::BFShareOperandLate (BF2Scheduler & sched, MoveNode & removed, MoveNode & scheduled) inline
Definition at line 48 of file BFShareOperandLate.hh.
                             :
        BFShareOperand(sched, removed, scheduled), originalCycle_(-1),
        originalRemovedPrologBus_(NULL),
        originalSharedPrologBus_(NULL),
        removedImmWriteCycle_(-1),
        removedPrologImmWriteCycle_(-1),
        removedImmu_(NULL),
        removedImmRegIndex_(-1),
        sharedImmWriteCycle_(-1),
        sharedPrologImmWriteCycle_(-1),
        sharedImmu_(NULL),
        sharedImmRegIndex_(-1) {}
~BFShareOperandLate()
virtual BFShareOperandLate::~BFShareOperandLate () inline virtual
Definition at line 64 of file BFShareOperandLate.hh.
{}
Member Function Documentation
operator()()
bool BFShareOperandLate::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Reimplemented from BFShareOperand.
Definition at line 52 of file BFShareOperandLate.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "Sharing oeprand late: removing: " << removed_.toString()
              << " shared: " << shared_.toString() << std::endl;
#endif
    originalCycle_ = removed_.cycle();
    originalRemovedBus_ = &removed_.move().bus();
    originalSharedBus_ = &shared_.move().bus();
    if (removed_.move().source().isImmediateRegister()) {
        removedImmWriteCycle_ = rm().immediateWriteCycle(removed_);
        removedImmRegIndex_ = removed_.move().source().index();
        removedImmu_ = &removed_.move().source().immediateUnit();
    }
    if (shared_.move().source().isImmediateRegister()) {
        sharedImmWriteCycle_ = rm().immediateWriteCycle(shared_);
        sharedImmRegIndex_ = shared_.move().source().index();
        sharedImmu_ = &shared_.move().source().immediateUnit();
    }
    MoveNode* removedPrologMN = ii() ?  duplicator().getMoveNode(removed_) : NULL;
    if (removedPrologMN != NULL) {
        originalRemovedPrologBus_ = &removedPrologMN->move().bus();
        if (removedPrologMN->move().source().isImmediateRegister()) {
            removedPrologImmWriteCycle_ =
                prologRM()->immediateWriteCycle(*removedPrologMN);
        }
    }
    MoveNode* sharedPrologMN = ii() ?  duplicator().getMoveNode(shared_) : NULL;
    if (sharedPrologMN != NULL) {
        originalSharedPrologBus_ = &sharedPrologMN->move().bus();
        if (sharedPrologMN->move().source().isImmediateRegister()) {
            sharedPrologImmWriteCycle_ =
                prologRM()->immediateWriteCycle(*sharedPrologMN);
        }
    }
    int cycle = shared_.cycle();
    MoveNode* removedOpTrigger = removed_.destinationOperation().triggeringMove();
    unassign(shared_, false);
    unassign(removed_, false);
    ddg().dropNode(removed_);
    sched_.nodeAndCopyKilled(removed_);
    if (BFShareOperand::operator()()) {
        if (canAssign(cycle, shared_)) {
            assign(cycle, shared_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\t\t\tShare operand late OK for: "
                      << shared_.toString() << std::endl;
            std::cerr << "\t\t\t\tRescheduling trigger closer:"
                      << removedOpTrigger->toString() << std::endl;
#endif
            auto resched =
                new BFRescheduleResultClose(sched_, *removedOpTrigger, 0);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            if (runPostChild(resched)) {
                std::cerr << "\t\t\tRescheduled trigger closer." << std::endl;
            }
#else
            runPostChild(resched);
#endif
            return true;
        } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\t\t\tShare operand late FAIL on assign for: "
                      << shared_.toString() << std::endl;
#endif
            BFShareOperand::undoOnlyMe();
            revert(cycle);
            return false;
        }
    } else {
        revert(cycle);
        return false;
    }
}
References BFOptimization::assign(), TTAProgram::Move::bus(), BFOptimization::canAssign(), MoveNode::cycle(), BFOptimization::ddg(), MoveNode::destinationOperation(), BoostGraph< GraphNode, GraphEdge >::dropNode(), BFOptimization::duplicator(), MoveNodeDuplicator::getMoveNode(), BFOptimization::ii(), TTAProgram::Terminal::immediateUnit(), SimpleResourceManager::immediateWriteCycle(), TTAProgram::Terminal::index(), TTAProgram::Terminal::isImmediateRegister(), MoveNode::move(), BF2Scheduler::nodeAndCopyKilled(), originalCycle_, originalRemovedBus_, originalRemovedPrologBus_, originalSharedBus_, originalSharedPrologBus_, BFOptimization::prologRM(), BFShareOperand::removed_, removedImmRegIndex_, removedImmu_, removedImmWriteCycle_, removedPrologImmWriteCycle_, revert(), BFOptimization::rm(), Reversible::runPostChild(), BFOptimization::sched_, BFShareOperand::shared_, sharedImmRegIndex_, sharedImmu_, sharedImmWriteCycle_, sharedPrologImmWriteCycle_, TTAProgram::Move::source(), MoveNode::toString(), ProgramOperation::triggeringMove(), BFOptimization::unassign(), and BFShareOperand::undoOnlyMe().
revert()
void BFShareOperandLate::revert (int cycle) private
Definition at line 139 of file BFShareOperandLate.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    assert(
        canAssign(
            cycle, shared_, originalSharedBus_, NULL, NULL,
            originalSharedPrologBus_,
            sharedImmWriteCycle_, sharedPrologImmWriteCycle_,
            sharedImmu_, sharedImmRegIndex_));
#endif
    assign(cycle, shared_, originalSharedBus_, NULL, NULL,
           originalSharedPrologBus_,
           sharedImmWriteCycle_, sharedPrologImmWriteCycle_,
           sharedImmu_, sharedImmRegIndex_);
    ddg().restoreNodeFromParent(removed_);
    sched_.nodeResurrected(removed_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    if (!canAssign(originalCycle_, removed_, originalRemovedBus_,
                   NULL, NULL, originalRemovedPrologBus_,
                   removedImmWriteCycle_, removedPrologImmWriteCycle_,
                   removedImmu_, removedImmRegIndex_)) {
        std::cerr << "Cannot return to original: " << removed_.toString()
                  << std::endl
                  << "dest PO: " << removed_.destinationOperation().toString()
                  << std::endl
                  << "original cycle: " << originalCycle_ << std::endl;
        TTAProgram::Instruction* ins = rm().instruction(originalCycle_);
        for (int i = 0; i < ins->moveCount(); i++) {
            TTAProgram::Move& m = ins->move(i);
            std::cerr << "\t" << POMDisassembler::disassemble(m)
                      << " bus: " << m.bus().name() << std::endl;
        }
        assert(false);
    }
#endif
    assign(originalCycle_,removed_, originalRemovedBus_,
           NULL, NULL, originalRemovedPrologBus_,
           removedImmWriteCycle_, removedPrologImmWriteCycle_,
           removedImmu_, removedImmRegIndex_);
}
References assert, BFOptimization::assign(), TTAProgram::Move::bus(), BFOptimization::canAssign(), BFOptimization::ddg(), MoveNode::destinationOperation(), POMDisassembler::disassemble(), SimpleResourceManager::instruction(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), TTAMachine::Component::name(), BF2Scheduler::nodeResurrected(), originalCycle_, originalRemovedBus_, originalRemovedPrologBus_, originalSharedBus_, originalSharedPrologBus_, BFShareOperand::removed_, removedImmRegIndex_, removedImmu_, removedImmWriteCycle_, removedPrologImmWriteCycle_, BoostGraph< GraphNode, GraphEdge >::restoreNodeFromParent(), BFOptimization::rm(), BFOptimization::sched_, BFShareOperand::shared_, sharedImmRegIndex_, sharedImmu_, sharedImmWriteCycle_, sharedPrologImmWriteCycle_, MoveNode::toString(), and ProgramOperation::toString().
Referenced by operator()(), and undoOnlyMe().
undoOnlyMe()
void BFShareOperandLate::undoOnlyMe () protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from BFShareOperand.
Definition at line 132 of file BFShareOperandLate.cc.
{
    int cycle = shared_.cycle();
    unassign(shared_, false);
    BFShareOperand::undoOnlyMe();
    revert(cycle);
}
References MoveNode::cycle(), revert(), BFShareOperand::shared_, BFOptimization::unassign(), and BFShareOperand::undoOnlyMe().
Member Data Documentation
originalCycle_
int BFShareOperandLate::originalCycle_ private
Definition at line 69 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
originalRemovedBus_
const TTAMachine::Bus* BFShareOperandLate::originalRemovedBus_ private
Definition at line 70 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
originalRemovedPrologBus_
const TTAMachine::Bus* BFShareOperandLate::originalRemovedPrologBus_ private
Definition at line 72 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
originalSharedBus_
const TTAMachine::Bus* BFShareOperandLate::originalSharedBus_ private
Definition at line 71 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
originalSharedPrologBus_
const TTAMachine::Bus* BFShareOperandLate::originalSharedPrologBus_ private
Definition at line 73 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
removedImmRegIndex_
int BFShareOperandLate::removedImmRegIndex_ private
Definition at line 78 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
removedImmu_
const TTAMachine::ImmediateUnit* BFShareOperandLate::removedImmu_ private
Definition at line 77 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
removedImmWriteCycle_
int BFShareOperandLate::removedImmWriteCycle_ private
Definition at line 75 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
removedPrologImmWriteCycle_
int BFShareOperandLate::removedPrologImmWriteCycle_ private
Definition at line 76 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
sharedImmRegIndex_
int BFShareOperandLate::sharedImmRegIndex_ private
Definition at line 83 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
sharedImmu_
const TTAMachine::ImmediateUnit* BFShareOperandLate::sharedImmu_ private
Definition at line 82 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
sharedImmWriteCycle_
int BFShareOperandLate::sharedImmWriteCycle_ private
Definition at line 80 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
sharedPrologImmWriteCycle_
int BFShareOperandLate::sharedPrologImmWriteCycle_ private
Definition at line 81 of file BFShareOperandLate.hh.
Referenced by operator()(), and revert().
The documentation for this class was generated from the following files:
BFShareOperandLate.hh
BFShareOperandLate.cc