OpenASIP: SimulatorInterpreterContext Class Reference
SimulatorInterpreterContext Class Reference
#include <SimulatorInterpreterContext.hh>
Public Member Functions
SimulatorInterpreterContext (SimulatorFrontend &simFrontend)
virtual ~SimulatorInterpreterContext ()
SimulatorFrontend & simulatorFrontend ()
Public Member Functions inherited from InterpreterContext
InterpreterContext ()
virtual ~InterpreterContext ()
Private Attributes
SimulatorFrontend & simulatorFrontend_
Detailed Description
Interpreter context for Simulator.
Holds the SimulatorFrontend instance the interpreter commands use to access simulator functionality.
Definition at line 45 of file SimulatorInterpreterContext.hh.
Constructor & Destructor Documentation
SimulatorInterpreterContext()
SimulatorInterpreterContext::SimulatorInterpreterContext (SimulatorFrontend & simFrontend)
Constructor.
Initializes the SimulatorFrontend instance.
Definition at line 42 of file SimulatorInterpreterContext.cc.
                                    :
    InterpreterContext(), simulatorFrontend_(simFrontend) {
}
~SimulatorInterpreterContext()
SimulatorInterpreterContext::~SimulatorInterpreterContext () virtual
Destructor.
Does nothing.
Definition at line 52 of file SimulatorInterpreterContext.cc.
{
}
Member Function Documentation
simulatorFrontend()
SimulatorFrontend & SimulatorInterpreterContext::simulatorFrontend ()
Returns the SimulatorFrontend instance contained in the context.
Returns
SimulatorFrontend instance.
Definition at line 61 of file SimulatorInterpreterContext.cc.
{
    return simulatorFrontend_;
}
References simulatorFrontend_.
Referenced by BackTraceCommand::execute(), ConfCommand::execute(), DisassembleCommand::execute(), MachCommand::execute(), ProgCommand::execute(), and SimControlLanguageCommand::simulatorFrontend().
Member Data Documentation
simulatorFrontend_
SimulatorFrontend& SimulatorInterpreterContext::simulatorFrontend_ private
Definition at line 53 of file SimulatorInterpreterContext.hh.
Referenced by simulatorFrontend().
The documentation for this class was generated from the following files:
SimulatorInterpreterContext.hh
SimulatorInterpreterContext.cc