OpenASIP: EnableBPCommand Class Reference
EnableBPCommand Class Reference
#include <EnableBPCommand.hh>
Public Member Functions
EnableBPCommand ()
virtual ~EnableBPCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "enablebp" command of the Simulator Control Language.
Definition at line 47 of file EnableBPCommand.hh.
Constructor & Destructor Documentation
EnableBPCommand()
EnableBPCommand::EnableBPCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 52 of file EnableBPCommand.cc.
                                 :
    SimControlLanguageCommand("enablebp") {
}
~EnableBPCommand()
EnableBPCommand::~EnableBPCommand () virtual
Destructor.
Does nothing.
Definition at line 61 of file EnableBPCommand.cc.
{
}
Member Function Documentation
execute()
bool EnableBPCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "enablebp" command.
Enables the given breakpoints.
Parameters
arguments The handle(s) of the breakpoint(s) to enable.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 75 of file EnableBPCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 1, INT_MAX)) {
        return false;
    }
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    const std::string firstArgument =
        StringTools::trim(StringTools::stringToLower(
                              arguments[1].stringValue()));
    bool enableOnce = false;
    bool temporary = false;
    int firstHandleIndex = 1;
    if (firstArgument == "once") {
        enableOnce = true;
        firstHandleIndex = 2;
    } else if (firstArgument == "delete") {
        temporary = true;
        firstHandleIndex = 2;
    }
    StopPointManager& breakpointManager =
        simulatorFrontend().stopPointManager();
    if (!verifyBreakpointHandles(arguments, firstHandleIndex)) {
        return false;
    }
    // enable (and modify the properties of) the given breakpoints
    for (size_t i = firstHandleIndex; i < arguments.size(); ++i) {
        const unsigned int breakpointHandle = arguments[i].integerValue();
        breakpointManager.enable(breakpointHandle);
        if (enableOnce) {
            breakpointManager.enableOnceAndDisable(breakpointHandle);
        }
        if (temporary) {
            breakpointManager.enableOnceAndDelete(breakpointHandle);
        }
        printBreakpointInfo(breakpointHandle);
    }
    return true;
}
References CustomCommand::checkArgumentCount(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), StopPointManager::enable(), StopPointManager::enableOnceAndDelete(), StopPointManager::enableOnceAndDisable(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::stopPointManager(), StringTools::stringToLower(), temporary, StringTools::trim(), and SimControlLanguageCommand::verifyBreakpointHandles().
helpText()
std::string EnableBPCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 132 of file EnableBPCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_ENABLEBP).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_ENABLEBP.
The documentation for this class was generated from the following files:
EnableBPCommand.hh
EnableBPCommand.cc