OpenASIP: TTAProgram::Scope Class Reference
TTAProgram::Scope Class Reference abstract
#include <Scope.hh>
Public Member Functions
Scope ()
virtual ~Scope ()
virtual bool isGlobal () const
virtual bool isUnit () const
virtual bool isProcedure () const
virtual bool isLocal () const
bool containsCodeLabel (const std::string &name) const
bool containsDataLabel (const std::string &name) const
const CodeLabel & codeLabel (const std::string &name) const
const DataLabel & dataLabel (const std::string &name) const
int codeLabelCount (Address address) const
const CodeLabel & codeLabel (Address address, int index) const
int dataLabelCount (Address address) const
const DataLabel & dataLabel (Address address, int index) const
virtual void addCodeLabel (const CodeLabel *codeLabel)
virtual void addDataLabel (const DataLabel *dataLabel)
virtual void removeCodeLabels (InstructionAddress address)
virtual Scope * copy () const =0
Protected Types
typedef std::vector< const Scope * > ScopeList
List for child scopes.
typedef std::vector< const DataLabel * > DataLabelList
List of data labels.
typedef std::vector< const CodeLabel * > CodeLabelList
List of code labels.
Protected Member Functions
virtual void addGlobalCodeLabel (const CodeLabel &codeLabel, const Scope &owner)=0
Adds a code label and its owner to the global label bookkeeping.
virtual void addGlobalDataLabel (const DataLabel &dataLabel, const Scope &owner)=0
Adds a data label and its owner to the global label bookkeeping.
Scope & parent () const
void setParent (Scope &scope)
int childCount () const
void addChild (const Scope &scope)
const Scope & child (int index) const
Protected Attributes
ScopeList children_
Child scopes.
DataLabelList dataLabels_
Data labels contained by this scope.
CodeLabelList codeLabels_
Code labels contained by this scope.
Private Member Functions
Scope (const Scope &)
Copying not allowed.
Scope & operator= (const Scope &)
Assignment not allowed.
Private Attributes
Scope * parent_
The smallest outer scope that contains this scope.
Detailed Description
Scopes provide containers for different visibility level labels.
Todo:
Implement rest of the Scopes (only GlobalScope is supported currently).
Definition at line 53 of file Scope.hh.
Member Typedef Documentation
CodeLabelList
typedef std::vector<const CodeLabel*> TTAProgram::Scope::CodeLabelList protected
List of code labels.
Definition at line 90 of file Scope.hh.
DataLabelList
typedef std::vector<const DataLabel*> TTAProgram::Scope::DataLabelList protected
List of data labels.
Definition at line 88 of file Scope.hh.
ScopeList
typedef std::vector<const Scope*> TTAProgram::Scope::ScopeList protected
List for child scopes.
Definition at line 83 of file Scope.hh.
Constructor & Destructor Documentation
Scope() [1/2]
Scope::Scope ()
Constructor.
Definition at line 48 of file Scope.cc.
            : parent_(NULL) {
}
~Scope()
Scope::~Scope () virtual
Destructor.
Definition at line 54 of file Scope.cc.
              {
    for (unsigned int i = 0; i < dataLabels_.size(); i++) {
        delete dataLabels_.at(i);
    }
    dataLabels_.clear();
    for (unsigned int i = 0; i < codeLabels_.size(); i++) {
        delete codeLabels_.at(i);
    }
    codeLabels_.clear();
}
References codeLabels_, and dataLabels_.
Scope() [2/2]
TTAProgram::Scope::Scope (const Scope &) private
Copying not allowed.
Member Function Documentation
addChild()
void Scope::addChild (const Scope & scope) protected
Adds a child scope to this scope.
Parameters
scope The child scope to be added.
Exceptions
ObjectAlreadyExists if the given scope has already been added. or a scope with the same name already exists.
Definition at line 114 of file Scope.cc.
{
    if (!ContainerTools::containsValue(children_, &scope)) {
        children_.push_back(&scope);
    } else {
        throw ObjectAlreadyExists(__FILE__, __LINE__);
    }
}
References children_, and ContainerTools::containsValue().
addCodeLabel()
void Scope::addCodeLabel (const CodeLabel * codeLabel) virtual
Adds a code label to this scope.
Parameters
codeLabel The code label to be added.
Exceptions
KeyAlreadyExists of a code label of the same name already exists.
Definition at line 376 of file Scope.cc.
{
    if (containsCodeLabel(codeLabel->name())) {
        throw KeyAlreadyExists(
            __FILE__, __LINE__, "Scope::addCodeLabel()",
            "A code label already exists by this name.");
    } else {
        codeLabels_.push_back(codeLabel);
        // add label to the global bookkeeping
        Scope* scope = NULL;
        if (!isGlobal()) {
            scope = &parent();
            while (!scope->isGlobal()) {
                try {
                    scope = &scope->parent();
                } catch (WrongSubclass const&) {
                    assert(false);
                } catch (IllegalRegistration const&) {
                    assert(false);
                }
            }
        } else {
            scope = this;
        }
        scope->addGlobalCodeLabel(*codeLabel, *this);
    }
}
References addGlobalCodeLabel(), assert, codeLabel(), codeLabels_, containsCodeLabel(), isGlobal(), TTAProgram::Label::name(), and parent().
Referenced by TTAProgram::GlobalScope::copy(), TTAProgram::GlobalScope::copyAndRelocate(), TTAProgram::TPEFProgramFactory::createLabels(), and llvm::LLVMTCEBuilder::writeMachineFunction().
addDataLabel()
void Scope::addDataLabel (const DataLabel * dataLabel) virtual
Adds a data label to this scope.
Parameters
dataLabel The data label to be added.
Exceptions
KeyAlreadyExists of a data label of the same name already exists.
Definition at line 415 of file Scope.cc.
{
    if (containsDataLabel(dataLabel->name())) {
        throw KeyAlreadyExists(
            __FILE__, __LINE__, "Scope::addDataLabel()",
            "A data label already exists by this name.");
    } else {
        dataLabels_.push_back(dataLabel);
        // add label to the global bookkeeping
        Scope* scope = NULL;
        if (!isGlobal()) {
            scope = &parent();
            while (!scope->isGlobal()) {
                try {
                    scope = &scope->parent();
                } catch (WrongSubclass const&) {
                    assert(false);
                } catch (IllegalRegistration const&) {
                    assert(false);
                }
            }
        } else {
            scope = this;
        }
        scope->addGlobalDataLabel(*dataLabel, *this);
    }
}
References addGlobalDataLabel(), assert, containsDataLabel(), dataLabel(), dataLabels_, isGlobal(), TTAProgram::Label::name(), and parent().
Referenced by TTAProgram::GlobalScope::copy(), TTAProgram::GlobalScope::copyAndRelocate(), TTAProgram::TPEFProgramFactory::createLabels(), llvm::LLVMTCEBuilder::doFinalization(), and llvm::LLVMTCEBuilder::initDataSections().
addGlobalCodeLabel()
virtual void TTAProgram::Scope::addGlobalCodeLabel (const CodeLabel & codeLabel, const Scope & owner) protected pure virtual
Adds a code label and its owner to the global label bookkeeping.
Parameters
dataLabel The code label to be added.
owner The owner scope of the label.
Implemented in TTAProgram::GlobalScope.
Referenced by addCodeLabel().
addGlobalDataLabel()
virtual void TTAProgram::Scope::addGlobalDataLabel (const DataLabel & dataLabel, const Scope & owner) protected pure virtual
Adds a data label and its owner to the global label bookkeeping.
Parameters
dataLabel The data label to be added.
owner The owner scope of the label.
Implemented in TTAProgram::GlobalScope.
Referenced by addDataLabel().
child()
const Scope & Scope::child (int index) const protected
Returns the child scope at given index.
Parameters
index The index of the child scope.
Returns
The child scope at given index.
Exceptions
OutOfRange if the exceeds the number of scopes contained in this scope.
Definition at line 184 of file Scope.cc.
{
    if (index >= 0 && static_cast<unsigned int>(index) < children_.size()) {
        return *children_.at(index);
    } else {
        throw OutOfRange(__FILE__, __LINE__);
    }
}
References children_.
childCount()
int Scope::childCount () const protected
Returns the number of contained scopes.
Only scopes directly contained in this scope are counted, not inner scopes inside one of the child scopes.
Returns
The number of contained scopes.
Definition at line 171 of file Scope.cc.
{
    return children_.size();
}
References children_.
codeLabel() [1/2]
const CodeLabel & Scope::codeLabel (Address address, int index) const
Returns a code label visible in this scope in the given address and index.
Parameters
address The address of the code label.
index The index of the label if there area many labels at this address.
Returns
A code label visible in this scope in the given address and index.
Definition at line 289 of file Scope.cc.
{
    if (index < codeLabelCount(address)) {
        int found = -1;
        for (unsigned int i = 0; i < codeLabels_.size(); i++) {
            if (&codeLabels_.at(i)->address().space() ==
                &address.space() &&
                codeLabels_.at(i)->address().location() ==
                address.location()) {
                found++;
                if (found == index) {
                    return *codeLabels_.at(i);
                }
            }
        }
        throw KeyNotFound(__FILE__, __LINE__);
    } else {
        throw OutOfRange(__FILE__, __LINE__);
    }
}
References codeLabelCount(), codeLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
codeLabel() [2/2]
const CodeLabel & Scope::codeLabel (const std::string & name) const
Returns the code label with the given name.
Parameters
name The name of the label.
Exceptions
KeyNotFound if no code label with the given name exists in this scope.
Returns
The code label with the given name.
Definition at line 233 of file Scope.cc.
{
    for (unsigned int i = 0; i < codeLabels_.size(); i++) {
        if (name == codeLabels_.at(i)->name()) {
            return *codeLabels_.at(i);
        }
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References codeLabels_.
Referenced by addCodeLabel(), TTAProgram::GlobalScope::addGlobalCodeLabel(), and SimControlLanguageCommand::parseInstructionAddressExpression().
codeLabelCount()
int Scope::codeLabelCount (Address address) const
Returns the number of code labels in the given address visible in this scope.
Parameters
address The address of the label.
Returns
The number of code labels in the given address visible in this scope.
Definition at line 269 of file Scope.cc.
{
    int count = 0;
    for (unsigned int i = 0; i < codeLabels_.size(); i++) {
        if (&codeLabels_.at(i)->address().space() == &address.space() &&
            codeLabels_.at(i)->address().location() == address.location()) {
            count++;
        }
    }
    return count;
}
References codeLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by codeLabel().
containsCodeLabel()
bool Scope::containsCodeLabel (const std::string & name) const
Tells whether this scope contains a code label with the given name.
Parameters
The name of the label.
Returns
True if this scope contains a code label with the given name.
Definition at line 199 of file Scope.cc.
{
    for (unsigned int i = 0; i < codeLabels_.size(); i++) {
        if (name == codeLabels_.at(i)->name()) {
            return true;
        }
    }
    return false;
}
References codeLabels_.
Referenced by addCodeLabel().
containsDataLabel()
bool Scope::containsDataLabel (const std::string & name) const
Tells whether this scope contains a data label with the given name.
Parameters
The name of the label.
Returns
True if this scope contains a data label with the given name.
Definition at line 215 of file Scope.cc.
{
    for (unsigned int i = 0; i < dataLabels_.size(); i++) {
        if (name == dataLabels_.at(i)->name()) {
            return true;
        }
    }
    return false;
}
References dataLabels_.
Referenced by addDataLabel().
copy()
virtual Scope * TTAProgram::Scope::copy () const pure virtual
Implemented in TTAProgram::GlobalScope.
dataLabel() [1/2]
const DataLabel & Scope::dataLabel (Address address, int index) const
Returns a data label visible in this scope in the given address and index.
Parameters
address The address of the data label.
index The index of the label if there area many labels at this address.
Returns
A data label visible in this scope in the given address and index.
Definition at line 343 of file Scope.cc.
{
    if (index < dataLabelCount(address)) {
        int found = -1;
        for (unsigned int i = 0; i < dataLabels_.size(); i++) {
            if (&dataLabels_.at(i)->address().space() ==
                &address.space() &&
                dataLabels_.at(i)->address().location() ==
                address.location()) {
                found++;
                if (found == index) {
                    return *dataLabels_.at(i);
                }
            }
        }
        throw KeyNotFound(__FILE__, __LINE__);
    } else {
        throw OutOfRange(__FILE__, __LINE__);
    }
}
References dataLabelCount(), dataLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
dataLabel() [2/2]
const DataLabel & Scope::dataLabel (const std::string & name) const
Returns the data label with the given name.
Parameters
name The name of the label.
Exceptions
KeyNotFound if no data label with the given name exists in this scope.
Returns
The data label with the given name.
Definition at line 251 of file Scope.cc.
{
    for (unsigned int i = 0; i < dataLabels_.size(); i++) {
        if (name == dataLabels_.at(i)->name()) {
            return *dataLabels_.at(i);
        }
    }
    throw KeyNotFound(__FILE__, __LINE__);
}
References dataLabels_.
Referenced by addDataLabel(), TTAProgram::GlobalScope::addGlobalDataLabel(), SymbolAddressCommand::execute(), and SimControlLanguageCommand::parseDataAddressExpression().
dataLabelCount()
int Scope::dataLabelCount (Address address) const
Returns the number of data labels in the given address visible in this scope.
Parameters
address The address of the label.
Returns
The number of data labels in the given address visible in this scope.
Definition at line 323 of file Scope.cc.
{
    int count = 0;
    for (unsigned int i = 0; i < dataLabels_.size(); i++) {
        if (&dataLabels_.at(i)->address().space() == &address.space() &&
            dataLabels_.at(i)->address().location() == address.location()) {
            count++;
        }
    }
    return count;
}
References dataLabels_, TTAProgram::Address::location(), and TTAProgram::Address::space().
Referenced by dataLabel().
isGlobal()
bool Scope::isGlobal () const virtual
Tells whether this is a global scope.
Returns
True if this is a global scope.
Reimplemented in TTAProgram::GlobalScope.
Definition at line 72 of file Scope.cc.
                      {
    return false;
}
Referenced by addCodeLabel(), addDataLabel(), parent(), and setParent().
isLocal()
bool Scope::isLocal () const virtual
Tells whether this is a local scope.
Returns
True if this is a local scope.
Definition at line 102 of file Scope.cc.
                     {
    return false;
}
isProcedure()
bool Scope::isProcedure () const virtual
Tells whether this is a procedure scope.
Returns
True if this is a procedure scope.
Definition at line 92 of file Scope.cc.
{
    return false;
}
isUnit()
bool Scope::isUnit () const virtual
Tells whether this is a unit scope.
Returns
True if this is a unit scope.
Definition at line 82 of file Scope.cc.
                    {
    return false;
}
operator=()
Scope & TTAProgram::Scope::operator= (const Scope &) private
Assignment not allowed.
parent()
Scope & Scope::parent () const protected
Return the parent scope., that is, the scope that contains this scope.
Returns
The parent scope, that is, the scope that contains this scope.
Exceptions
WrongSubclass if this scope has no parent scope (it is the global scope).
IllegalRegistration if no parent has been set (and the scope is not the global scope.
Definition at line 132 of file Scope.cc.
                    {
    if (isGlobal()) {
        throw WrongSubclass(
            __FILE__, __LINE__, "Scope::parent()",
            "Global scope cannot have parent scope.");
    } else if (parent_ == NULL) {
        throw IllegalRegistration(
            __FILE__, __LINE__, "Scope::parent()", "No parent set.");
    } else {
        return *parent_;
    }
}
References isGlobal(), and parent_.
Referenced by addCodeLabel(), and addDataLabel().
removeCodeLabels()
void Scope::removeCodeLabels (InstructionAddress address) virtual
Removes all code labels attached to the given instruction address.
Parameters
address The instruction address.
Reimplemented in TTAProgram::GlobalScope.
Definition at line 451 of file Scope.cc.
{
    for (CodeLabelList::iterator i = codeLabels_.begin();
         i != codeLabels_.end(); ) {
        CodeLabelList::iterator next = i;
        next++;
        if ((*i)->address().location() == address) {
            delete (*i);
            codeLabels_.erase(i);
        }
        i = next;
    }
}
References codeLabels_.
setParent()
void Scope::setParent (Scope & scope) protected
Sets the parent scope.
Parameters
scope The new parent scope.
Exceptions
WrongSubclass if the scope is the global scope.
Definition at line 152 of file Scope.cc.
{
    if (!isGlobal()) {
        parent_ = &scope;
    } else {
        throw WrongSubclass(
            __FILE__, __LINE__, "Scope::parent()",
            "Global scope cannot have parent scope.");
    }
}
References isGlobal(), and parent_.
Member Data Documentation
children_
ScopeList TTAProgram::Scope::children_ protected
Child scopes.
Definition at line 85 of file Scope.hh.
Referenced by addChild(), child(), and childCount().
codeLabels_
CodeLabelList TTAProgram::Scope::codeLabels_ protected
Code labels contained by this scope.
Definition at line 95 of file Scope.hh.
Referenced by addCodeLabel(), codeLabel(), codeLabel(), codeLabelCount(), containsCodeLabel(), removeCodeLabels(), and ~Scope().
dataLabels_
DataLabelList TTAProgram::Scope::dataLabels_ protected
Data labels contained by this scope.
Definition at line 93 of file Scope.hh.
Referenced by addDataLabel(), containsDataLabel(), dataLabel(), dataLabel(), dataLabelCount(), and ~Scope().
parent_
Scope* TTAProgram::Scope::parent_ private
The smallest outer scope that contains this scope.
Definition at line 125 of file Scope.hh.
Referenced by parent(), and setParent().
The documentation for this class was generated from the following files:
Scope.hh
Scope.cc