OpenASIP: AddCostFunctionPluginCmd Class Reference
AddCostFunctionPluginCmd Class Reference
#include <AddCostFunctionPluginCmd.hh>
Public Member Functions
AddCostFunctionPluginCmd ()
virtual ~AddCostFunctionPluginCmd ()
virtual bool Do ()
virtual int id () const
virtual AddCostFunctionPluginCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding a new cost function plugin to a HDB.
Definition at line 41 of file AddCostFunctionPluginCmd.hh.
Constructor & Destructor Documentation
AddCostFunctionPluginCmd()
AddCostFunctionPluginCmd::AddCostFunctionPluginCmd ()
The Constructor.
Definition at line 49 of file AddCostFunctionPluginCmd.cc.
                                                   :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_COST_PLUGIN, NULL) {
}
Referenced by create().
~AddCostFunctionPluginCmd()
AddCostFunctionPluginCmd::~AddCostFunctionPluginCmd () virtual
The Destructor.
Definition at line 57 of file AddCostFunctionPluginCmd.cc.
{
}
Member Function Documentation
create()
AddCostFunctionPluginCmd * AddCostFunctionPluginCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
A new instance of this command.
Implements GUICommand.
Definition at line 113 of file AddCostFunctionPluginCmd.cc.
{
    return new AddCostFunctionPluginCmd();
}
References AddCostFunctionPluginCmd().
Do()
bool AddCostFunctionPluginCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 64 of file AddCostFunctionPluginCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    CostFunctionPlugin plugin(0, "", "", "", CostFunctionPlugin::COST_FU);
    RowID id = manager->addCostFunctionPlugin(plugin);
    CostFunctionPluginDialog dialog(parentWindow(), -1, *manager, id);
    if (dialog.ShowModal() == wxID_OK) {
        wxGetApp().mainFrame().update();
        wxGetApp().mainFrame().browser()->selectCostFunctionPlugin(id);
        return true;
    } else {
        manager->removeCostFunctionPlugin(id);
        return false;
    }
}
References HDB::HDBManager::addCostFunctionPlugin(), HDB::CostFunctionPlugin::COST_FU, GUICommand::parentWindow(), and HDB::HDBManager::removeCostFunctionPlugin().
icon()
std::string AddCostFunctionPluginCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 91 of file AddCostFunctionPluginCmd.cc.
{
    return "";
}
id()
int AddCostFunctionPluginCmd::id () const virtual
Returns the command identifier.
Returns
Command identifier for this command.
Implements GUICommand.
Definition at line 102 of file AddCostFunctionPluginCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_COST_PLUGIN;
}
References HDBEditorConstants::COMMAND_ADD_COST_PLUGIN.
isEnabled()
bool AddCostFunctionPluginCmd::isEnabled () virtual
Returns true if the command should be enabled in menu/toolbar, false if not.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 124 of file AddCostFunctionPluginCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddCostFunctionPluginCmd.hh
AddCostFunctionPluginCmd.cc