OpenASIP: ModifyComponentCmd Class Reference
ModifyComponentCmd Class Reference
#include <ModifyComponentCmd.hh>
Public Member Functions
ModifyComponentCmd ()
virtual bool Do ()
virtual int id () const
virtual ModifyComponentCmd * create () const
virtual std::string shortName () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for modifying components in the Machine.
Definition at line 43 of file ModifyComponentCmd.hh.
Constructor & Destructor Documentation
ModifyComponentCmd()
ModifyComponentCmd::ModifyComponentCmd ()
The Constructor.
Definition at line 49 of file ModifyComponentCmd.cc.
                                      :
    EditorCommand(ProDeConstants::CMD_NAME_MODIFY_COMP) {
}
Referenced by create().
Member Function Documentation
create()
ModifyComponentCmd * ModifyComponentCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 117 of file ModifyComponentCmd.cc.
{
    return new ModifyComponentCmd();
}
References ModifyComponentCmd().
Do()
bool ModifyComponentCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 61 of file ModifyComponentCmd.cc.
                       {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    // send modify request to the selected EditPart
    Request* modifyRequest = new Request(Request::MODIFY_REQUEST);
    EditPart* selected = dynamic_cast<MDFView*>(view())->selection();
    if (selected == NULL) {
    return false;
    }
    ComponentCommand* command = selected->performRequest(modifyRequest);
    // execute the returned command
    if (command == NULL) {
    return false;
    } else {
    Model* model = dynamic_cast<MDFDocument*>(
        wxGetApp().docManager()->GetCurrentDocument())->getModel();
    model->pushToStack();
    dynamic_cast<MDFView*>(view())->clearSelection();
    command->setParentWindow(parentWindow());
    bool result = command->Do();
    if (result) {
        // Model was modified.
        model->notifyObservers();
    } else {
        // Modification was cancelled.
        model->popFromStack();
    }
    return result;
    }
}
References assert, ComponentCommand::Do(), Request::MODIFY_REQUEST, Model::notifyObservers(), GUICommand::parentWindow(), EditPart::performRequest(), Model::popFromStack(), Model::pushToStack(), ComponentCommand::setParentWindow(), and EditorCommand::view().
Referenced by SelectTool::onMouseEvent().
icon()
string ModifyComponentCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 138 of file ModifyComponentCmd.cc.
{
    return ProDeConstants::CMD_ICON_MODIFY_COMP;
}
References ProDeConstants::CMD_ICON_MODIFY_COMP.
id()
int ModifyComponentCmd::id () const virtual
Returns command identifier of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 106 of file ModifyComponentCmd.cc.
{
    return ProDeConstants::COMMAND_MODIFY_COMP;
}
References ProDeConstants::COMMAND_MODIFY_COMP.
isEnabled()
bool ModifyComponentCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a block is selected, and the selected block can handle modify requests.
Returns
True, if a modifyable block is selected.
Reimplemented from EditorCommand.
Definition at line 153 of file ModifyComponentCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    MDFView* mdfView = dynamic_cast<MDFView*>(manager->GetCurrentView());
    if (mdfView == NULL) {
    return false;
    }
    Request* modifyRequest = new Request(Request::MODIFY_REQUEST);
    if (mdfView->selection() == NULL ||
        !mdfView->selection()->canHandle(modifyRequest)) {
    return false;
    }
    return true;
}
References EditPart::canHandle(), Request::MODIFY_REQUEST, and MDFView::selection().
shortName()
string ModifyComponentCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 128 of file ModifyComponentCmd.cc.
{
    return ProDeConstants::CMD_SNAME_MODIFY_COMP;
}
References ProDeConstants::CMD_SNAME_MODIFY_COMP.
The documentation for this class was generated from the following files:
ModifyComponentCmd.hh
ModifyComponentCmd.cc