OpenASIP: MoveSlot Class Reference
MoveSlot Class Reference
#include <MoveSlot.hh>
Public Member Functions
MoveSlot (const std::string &busName, BinaryEncoding &parent)
MoveSlot (const ObjectState *state, BinaryEncoding &parent)
virtual ~MoveSlot ()
BinaryEncoding * parent () const
std::string name () const
void setName (const std::string &name)
void setGuardField (GuardField &field)
void unsetGuardField ()
bool hasGuardField () const
GuardField & guardField () const
void setSourceField (SourceField &field)
void unsetSourceField ()
bool hasSourceField () const
SourceField & sourceField () const
void setDestinationField (DestinationField &field)
void unsetDestinationField ()
bool hasDestinationField () const
DestinationField & destinationField () const
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
virtual int width () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_MOVE_SLOT = "move_slot"
ObjectState name for move slot.
static const std::string OSKEY_BUS_NAME = "bus_name"
ObjectState attribute key for the name of the bus.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Member Functions
void deleteGuardField ()
void deleteSourceField ()
void deleteDestinationField ()
Private Attributes
std::string name_
The bus name.
GuardField * guardField_
The guard field.
SourceField * sourceField_
The source field.
DestinationField * destinationField_
The destination field.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
The MoveSlot class represents move slots, fields of the TTA instruction dedicated to program data transports.
Move slots are subdivided into 2 or 3 fields: the guard (optional), source and destination fields. Each type of move slot field is modelled by a different class. MoveSlot has handles to the instances of these classes. A move slot is identified by the name of the transport bus it controls. MoveSlot instances cannot exist alone. They belong to a binary encoding and are always registered to a BinaryEncoding object.
Definition at line 60 of file MoveSlot.hh.
Constructor & Destructor Documentation
MoveSlot() [1/2]
MoveSlot::MoveSlot (const std::string & busName, BinaryEncoding & parent)
The constructor.
Registers the move slot to the parent binary encoding automatically. The slot is added as the leftmost field of the instruction word.
Parameters
busName Name of the bus programmed by this move slot.
parent The parent BinaryEncoding.
Exceptions
ObjectAlreadyExists If the parent binary encoding has a move slot with the same bus name already.
Definition at line 64 of file MoveSlot.cc.
    : InstructionField(&parent),
      name_(busName),
      guardField_(NULL),
      sourceField_(NULL),
      destinationField_(NULL) {
    setParent(NULL);
    parent.addMoveSlot(*this);
    setParent(&parent);
}
References BinaryEncoding::addMoveSlot(), parent(), and InstructionField::setParent().
MoveSlot() [2/2]
MoveSlot::MoveSlot (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the move slot from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent binary encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 85 of file MoveSlot.cc.
    : InstructionField(state, &parent),
      name_(""),
      guardField_(NULL),
      sourceField_(NULL),
      destinationField_(NULL) {
    loadState(state);
    setParent(NULL);
    parent.addMoveSlot(*this);
    setParent(&parent);
}
References BinaryEncoding::addMoveSlot(), loadState(), parent(), and InstructionField::setParent().
~MoveSlot()
MoveSlot::~MoveSlot () virtual
The destructor.
Definition at line 100 of file MoveSlot.cc.
                    {
    deleteGuardField();
    deleteSourceField();
    deleteDestinationField();
    BinaryEncoding* parent = this->parent();
    setParent(NULL);
    parent->removeMoveSlot(*this);
}
References deleteDestinationField(), deleteGuardField(), deleteSourceField(), parent(), BinaryEncoding::removeMoveSlot(), and InstructionField::setParent().
Member Function Documentation
childField()
InstructionField & MoveSlot::childField (int position) const virtual
Returns the child field at the given relative position.
Parameters
position The position (0 is the rightmost position).
Exceptions
OutOfRange If the position is negative or not smaller than the number of child fields.
Reimplemented from InstructionField.
Definition at line 380 of file MoveSlot.cc.
{
    InstructionField::childField(position);
    if (hasGuardField() && guardField().relativePosition() == position) {
        return guardField();
    }
    if (hasSourceField() && sourceField().relativePosition() == position) {
        return sourceField();
    }
    if (hasDestinationField() &&
        destinationField().relativePosition() == position) {
        return destinationField();
    }
    assert(false);
    return NullInstructionField::instance();
}
References assert, InstructionField::childField(), destinationField(), guardField(), hasDestinationField(), hasGuardField(), hasSourceField(), NullInstructionField::instance(), InstructionField::relativePosition(), and sourceField().
Referenced by CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), and printMoveSlotLayout().
childFieldCount()
int MoveSlot::childFieldCount () const virtual
Returns the number of child fields (guard, source, destination) within the move slot.
Returns
The number of child fields.
Implements InstructionField.
Definition at line 357 of file MoveSlot.cc.
{
    int count(0);
    if (hasGuardField()) {
        count++;
    }
    if (hasSourceField()) {
        count++;
    }
    if (hasDestinationField()) {
        count++;
    }
    return count;
}
References hasDestinationField(), hasGuardField(), and hasSourceField().
Referenced by CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), and printMoveSlotLayout().
deleteDestinationField()
void MoveSlot::deleteDestinationField () private
Deletes the destination field of the move slot.
Definition at line 516 of file MoveSlot.cc.
{
    if (destinationField_ != NULL) {
        delete destinationField_;
        destinationField_ = NULL;
    }
}
References destinationField_.
Referenced by loadState(), and ~MoveSlot().
deleteGuardField()
void MoveSlot::deleteGuardField () private
Deletes the guard field of the move slot.
Definition at line 493 of file MoveSlot.cc.
{
    if (guardField_ != NULL) {
        delete guardField_;
        guardField_ = NULL;
    }
}
References guardField_.
Referenced by loadState(), and ~MoveSlot().
deleteSourceField()
void MoveSlot::deleteSourceField () private
Deletes the source field of the move slot.
Definition at line 505 of file MoveSlot.cc.
{
    if (sourceField_ != NULL) {
        delete sourceField_;
        sourceField_ = NULL;
    }
}
References sourceField_.
Referenced by loadState(), and ~MoveSlot().
destinationField()
DestinationField & MoveSlot::destinationField () const
Returns the destination field of the move slot.
Returns NullDestinationField if the move slot does not have a destination field.
Returns
The destination field of the move slot.
Definition at line 341 of file MoveSlot.cc.
{
    if (hasDestinationField()) {
        return *destinationField_;
    } else {
        return NullDestinationField::instance();
    }
}
References destinationField_, hasDestinationField(), and NullDestinationField::instance().
Referenced by BEMTester::canAddComponentPriorityEncoding(), BEMValidator::checkDestinationField(), childField(), DestinationField::DestinationField(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), ProGe::RV32MicroCodeGenerator::findBusWidths(), printDestinationFieldEncodings(), saveState(), unsetDestinationField(), width(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfRFWritePort(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), and SocketCodeTable::~SocketCodeTable().
guardField()
GuardField & MoveSlot::guardField () const
Returns the guard field of the move slot.
Returns NullGuardField instance if the guard field is missing.
Returns
The guard field of the move slot.
Definition at line 215 of file MoveSlot.cc.
{
    if (hasGuardField()) {
        return *guardField_;
    } else {
        return NullGuardField::instance();
    }
}
References guardField_, hasGuardField(), and NullGuardField::instance().
Referenced by BEMTester::canAddComponentPriorityEncoding(), BEMValidator::checkGuardField(), childField(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), printGuardFieldEncodings(), saveState(), unsetGuardField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
hasDestinationField()
bool MoveSlot::hasDestinationField () const
Tells whether the move slot has a destination field.
Returns
True if the move slot has a destination field, otherwise false.
Definition at line 327 of file MoveSlot.cc.
{
    return destinationField_ != NULL;
}
References destinationField_.
Referenced by BEMValidator::checkDestinationField(), childField(), childFieldCount(), destinationField(), DestinationField::DestinationField(), ProGe::RV32MicroCodeGenerator::findBusWidths(), GuardField::GuardField(), printDestinationFieldEncodings(), saveState(), setDestinationField(), unsetDestinationField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
hasGuardField()
bool MoveSlot::hasGuardField () const
Tells whether the move slot has a guard field.
Returns
True if the move has a guard field, otherwise false.
Definition at line 202 of file MoveSlot.cc.
{
    return guardField_ != NULL;
}
References guardField_.
Referenced by BEMValidator::checkGuardField(), childField(), childFieldCount(), guardField(), printGuardFieldEncodings(), saveState(), setGuardField(), unsetGuardField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), DefaultDecoderGenerator::writeSquashSignalGenerationProcess(), and DefaultDecoderGenerator::writeSquashSignals().
hasSourceField()
bool MoveSlot::hasSourceField () const
Tells whether the move slot has a source field.
Returns
True if the move slot has a source field, otherwise false.
Definition at line 264 of file MoveSlot.cc.
{
    return sourceField_ != NULL;
}
References sourceField_.
Referenced by BEMValidator::checkSourceField(), childField(), childFieldCount(), GuardField::GuardField(), printSourceFieldEncodings(), saveState(), setSourceField(), sourceField(), SourceField::SourceField(), unsetSourceField(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
loadState()
void MoveSlot::loadState (const ObjectState * state) virtual
Loads the state of the move slot from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Definition at line 432 of file MoveSlot.cc.
{
    deleteGuardField();
    deleteSourceField();
    deleteDestinationField();
    ObjectState* newState = new ObjectState(*state);
    reorderSubfields(newState);
    InstructionField::loadState(newState);
    try {
        setName(newState->stringAttribute(OSKEY_BUS_NAME));
        for (int i = 0; i < newState->childCount(); i++) {
            ObjectState* child = newState->child(i);
            if (child->name() == GuardField::OSNAME_GUARD_FIELD) {
                new GuardField(child, *this);
            } else if (child->name() == SourceField::OSNAME_SOURCE_FIELD) {
                new SourceField(child, *this);
            } else if (
                child->name() == DestinationField::OSNAME_DESTINATION_FIELD) {
                new DestinationField(child, *this);
            }
        }
    } catch (const Exception& exception) {
        const string procName = "MoveSlot::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    delete newState;
}
References ObjectState::child(), ObjectState::childCount(), deleteDestinationField(), deleteGuardField(), deleteSourceField(), Exception::errorMessage(), InstructionField::loadState(), ObjectState::name(), OSKEY_BUS_NAME, DestinationField::OSNAME_DESTINATION_FIELD, GuardField::OSNAME_GUARD_FIELD, SourceField::OSNAME_SOURCE_FIELD, InstructionField::reorderSubfields(), setName(), and ObjectState::stringAttribute().
Referenced by MoveSlot().
name()
std::string MoveSlot::name () const
Returns the bus name programmed by this move slot in the instruction word.
Returns
Name of the bus.
Definition at line 136 of file MoveSlot.cc.
                     {
    return name_;
}
References name_.
Referenced by CodeCompressorPlugin::addBitsForDestinationField(), CodeCompressorPlugin::addBitsForGuardField(), CodeCompressorPlugin::addBitsForMoveSlot(), CodeCompressorPlugin::addBitsForSourceField(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BinaryEncoding::addMoveSlot(), BEMGenerator::addSubfields(), BEMValidator::checkSocketCodeTable(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), CodeCompressorPlugin::encodeRFTerminal(), ProGe::RV32MicroCodeGenerator::findBusWidths(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), BinaryEncoding::hasMoveSlot(), BEMGenerator::maxLongImmSlotWidth(), BinaryEncoding::moveSlot(), BEMValidator::needsSourceField(), DefaultDecoderGenerator::portCodeCondition(), printInstructionLayout(), printMoveSlot(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), saveState(), SourceField::setImmediateEncoding(), setName(), DefaultDecoderGenerator::socketEncodingCondition(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
parent()
BinaryEncoding * MoveSlot::parent () const
Returns the parent binary encoding.
Returns
The parent binary encoding.
Definition at line 118 of file MoveSlot.cc.
                       {
    InstructionField* parent = InstructionField::parent();
    if (parent == NULL) {
        return NULL;
    } else {
        BinaryEncoding* bem = dynamic_cast<BinaryEncoding*>(parent);
        assert(bem != NULL);
        return bem;
    }
}
References assert, InstructionField::parent(), and parent().
Referenced by BinaryEncoding::addMoveSlot(), DestinationField::DestinationField(), MoveSlot(), MoveSlot(), parent(), BinaryEncoding::removeMoveSlot(), setName(), SocketEncoding::SocketEncoding(), SourceField::SourceField(), unsetDestinationField(), unsetGuardField(), unsetSourceField(), and ~MoveSlot().
saveState()
ObjectState * MoveSlot::saveState () const virtual
Saves the state of the move slot to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from InstructionField.
Definition at line 469 of file MoveSlot.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_MOVE_SLOT);
    state->setAttribute(OSKEY_BUS_NAME, name());
    if (hasGuardField()) {
        state->addChild(guardField().saveState());
    }
    if (hasSourceField()) {
        state->addChild(sourceField().saveState());
    }
    if (hasDestinationField()) {
        state->addChild(destinationField().saveState());
    }
    return state;
}
References ObjectState::addChild(), destinationField(), guardField(), hasDestinationField(), hasGuardField(), hasSourceField(), name(), OSKEY_BUS_NAME, OSNAME_MOVE_SLOT, InstructionField::saveState(), saveState(), ObjectState::setAttribute(), ObjectState::setName(), and sourceField().
Referenced by BinaryEncoding::saveState(), and saveState().
setDestinationField()
void MoveSlot::setDestinationField (DestinationField & field)
Adds the given destination field to the move slot.
This method is to be called from the constructor of DestinationField.
Parameters
field The destination field to be added.
Exceptions
ObjectAlreadyExists If the move slot has a destination field already.
Definition at line 296 of file MoveSlot.cc.
{
    // verify that this is called from DestinationField constructor
    assert(field.parent() == NULL);
    if (hasDestinationField()) {
        const string procName = "MoveSlot::setDestinationField";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    destinationField_ = &field;
}
References assert, destinationField_, hasDestinationField(), and SlotField::parent().
Referenced by DestinationField::DestinationField(), and DestinationField::DestinationField().
setGuardField()
void MoveSlot::setGuardField (GuardField & field)
Adds the given guard field to the move slot.
This method is to be called from the constructor of GuardField.
Parameters
field The guard field to be added.
Exceptions
ObjectAlreadyExists If the move slot has a guard field already.
Definition at line 171 of file MoveSlot.cc.
{
    // verify that this is called from GuardField constructor
    assert(field.parent() == NULL);
    if (hasGuardField()) {
        const string procName = "MoveSlot::setGuardField";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    guardField_ = &field;
}
References assert, guardField_, hasGuardField(), and GuardField::parent().
Referenced by GuardField::GuardField(), and GuardField::GuardField().
setName()
void MoveSlot::setName (const std::string & name)
Sets the name of the bus programmed by this move slot.
Parameters
name Name of the bus.
Exceptions
ObjectAlreadyExists If there is a move slot that programs the given bus already.
Definition at line 149 of file MoveSlot.cc.
{
    if (name == this->name()) {
        return;
    }
    if (parent()->hasMoveSlot(name)) {
        const string procName = "MoveSlot::setName";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    name_ = name;
}
References name(), name_, and parent().
Referenced by loadState().
setSourceField()
void MoveSlot::setSourceField (SourceField & field)
Adds the given source field to the move slot.
This method is to be called from the constructor of SourceField.
Parameters
field The source field to be added.
Exceptions
ObjectAlreadyExists If the move slot has a source field already.
Definition at line 233 of file MoveSlot.cc.
{
    // verify that this is called from SourceField constructor
    assert(field.parent() == NULL);
    if (hasSourceField()) {
        const string procName = "MoveSlot::setSourceField";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    sourceField_ = &field;
}
References assert, hasSourceField(), SlotField::parent(), and sourceField_.
Referenced by SourceField::SourceField(), and SourceField::SourceField().
sourceField()
SourceField & MoveSlot::sourceField () const
Returns the source field of the move slot.
Returns NullSourceField if the move slot does not have a source field.
Returns
The source field of the move slot.
Definition at line 277 of file MoveSlot.cc.
{
    if (hasSourceField()) {
        return *sourceField_;
    } else {
        return NullSourceField::instance();
    }
}
References hasSourceField(), NullSourceField::instance(), and sourceField_.
Referenced by BEMTester::canAddComponentPriorityEncoding(), BEMValidator::checkSourceField(), childField(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), printSourceFieldEncodings(), saveState(), SourceField::SourceField(), unsetSourceField(), width(), DefaultDecoderGenerator::writeBusControlRulesOfOutputSocket(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), DefaultDecoderGenerator::writeInstructionDismembering(), DefaultDecoderGenerator::writeMoveFieldSignals(), DefaultDecoderGenerator::writeSimmDataSignal(), and SocketCodeTable::~SocketCodeTable().
unsetDestinationField()
void MoveSlot::unsetDestinationField ()
Removes the destination field from the move slot.
This method is to be called from the destructor of DestinationField.
Definition at line 314 of file MoveSlot.cc.
{
    assert(hasDestinationField());
    assert(destinationField().parent() == NULL);
    destinationField_ = NULL;
}
References assert, destinationField(), destinationField_, hasDestinationField(), and parent().
Referenced by DestinationField::~DestinationField().
unsetGuardField()
void MoveSlot::unsetGuardField ()
Removes the guard field from the move slot.
This method is to be called from the destructor of GuardField.
Definition at line 189 of file MoveSlot.cc.
{
    assert(hasGuardField());
    assert(guardField().parent() == NULL);
    guardField_ = NULL;
}
References assert, guardField(), guardField_, hasGuardField(), and parent().
Referenced by GuardField::~GuardField().
unsetSourceField()
void MoveSlot::unsetSourceField ()
Removes the source field from the move slot.
This method is to be called from the destructor of SourceField.
Definition at line 251 of file MoveSlot.cc.
{
    assert(hasSourceField());
    assert(sourceField().parent() == NULL);
    sourceField_ = NULL;
}
References assert, hasSourceField(), parent(), sourceField(), and sourceField_.
Referenced by SourceField::~SourceField().
width()
int MoveSlot::width () const virtual
Returns the bit width of the move slot.
Returns
The bit width of the move slot.
Implements InstructionField.
Definition at line 406 of file MoveSlot.cc.
                      {
    int width(0);
    if (hasGuardField()) {
        width += guardField().width();
    }
    if (hasSourceField()) {
        width += sourceField().width();
    }
    if (hasDestinationField()) {
        width += destinationField().width();
    }
    return width;
}
References destinationField(), guardField(), hasDestinationField(), hasGuardField(), hasSourceField(), sourceField(), GuardField::width(), width(), SlotField::width(), and SourceField::width().
Referenced by CodeCompressorPlugin::addBitsForMoveSlot(), BEMGenerator::addSubfields(), CodeCompressorPlugin::bemInstructionBits(), BEMTester::canAddComponentPriorityEncoding(), CodeCompressorPlugin::encodeMove(), ProGe::RV32MicroCodeGenerator::findBusWidths(), CodeCompressorPlugin::moveSlotWidth(), printInstructionLayout(), printMoveSlot(), width(), BinaryEncoding::width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
Member Data Documentation
destinationField_
DestinationField* MoveSlot::destinationField_ private
The destination field.
Definition at line 112 of file MoveSlot.hh.
Referenced by deleteDestinationField(), destinationField(), hasDestinationField(), setDestinationField(), and unsetDestinationField().
guardField_
GuardField* MoveSlot::guardField_ private
The guard field.
Definition at line 108 of file MoveSlot.hh.
Referenced by deleteGuardField(), guardField(), hasGuardField(), setGuardField(), and unsetGuardField().
name_
std::string MoveSlot::name_ private
The bus name.
Definition at line 106 of file MoveSlot.hh.
Referenced by name(), and setName().
OSKEY_BUS_NAME
const std::string MoveSlot::OSKEY_BUS_NAME = "bus_name" static
ObjectState attribute key for the name of the bus.
Definition at line 98 of file MoveSlot.hh.
Referenced by loadState(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), and saveState().
OSNAME_MOVE_SLOT
const std::string MoveSlot::OSNAME_MOVE_SLOT = "move_slot" static
ObjectState name for move slot.
Definition at line 96 of file MoveSlot.hh.
Referenced by BEMSerializer::convertToFileFormat(), BinaryEncoding::loadState(), BEMSerializer::moveSlotToOM(), and saveState().
sourceField_
SourceField* MoveSlot::sourceField_ private
The source field.
Definition at line 110 of file MoveSlot.hh.
Referenced by deleteSourceField(), hasSourceField(), setSourceField(), sourceField(), and unsetSourceField().
The documentation for this class was generated from the following files:
MoveSlot.hh
MoveSlot.cc