OpenASIP: TPEF::AOutDataSectionReader Class Reference
TPEF::AOutDataSectionReader Class Reference
#include <AOutDataSectionReader.hh>
Public Member Functions
virtual ~AOutDataSectionReader ()
Public Member Functions inherited from TPEF::AOutSectionReader
virtual ~AOutSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Protected Member Functions
AOutDataSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::AOutSectionReader
AOutSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
AOutDataSectionReader (const AOutDataSectionReader &)
Copying not allowed.
Static Private Attributes
static AOutDataSectionReader proto_
Prototype instance of AOutDataSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads data section from a.out binary file.
Definition at line 49 of file AOutDataSectionReader.hh.
Constructor & Destructor Documentation
~AOutDataSectionReader()
TPEF::AOutDataSectionReader::~AOutDataSectionReader () virtual
Destructor.
Definition at line 64 of file AOutDataSectionReader.cc.
{
}
AOutDataSectionReader() [1/2]
TPEF::AOutDataSectionReader::AOutDataSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 57 of file AOutDataSectionReader.cc.
                                             : AOutSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
AOutDataSectionReader() [2/2]
TPEF::AOutDataSectionReader::AOutDataSectionReader (const AOutDataSectionReader &) private
Copying not allowed.
Member Function Documentation
readData()
void TPEF::AOutDataSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads data section of a.out binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Implements TPEF::SectionReader.
Definition at line 90 of file AOutDataSectionReader.cc.
{
    AOutReader* bReader = dynamic_cast<AOutReader*>(parent());
    assert(bReader != NULL);
    DataSection* theDataSection = dynamic_cast<DataSection*>(section);
    assert(theDataSection != NULL);
    for (SectionOffset i = 0;
         i < bReader->header().sectionSizeData(); i++) {
        theDataSection->addByte(stream.readByte());
    }
}
References TPEF::DataSection::addByte(), assert, TPEF::AOutReader::header(), TPEF::AOutSectionReader::parent(), and TPEF::BinaryStream::readByte().
type()
Section::SectionType TPEF::AOutDataSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 73 of file AOutDataSectionReader.cc.
{
    return Section::ST_DATA;
}
References TPEF::Section::ST_DATA.
Member Data Documentation
proto_
AOutDataSectionReader TPEF::AOutDataSectionReader::proto_ static private
Prototype instance of AOutDataSectionReader to be registered to SectionReader.
Definition at line 66 of file AOutDataSectionReader.hh.
The documentation for this class was generated from the following files:
AOutDataSectionReader.hh
AOutDataSectionReader.cc