OpenASIP: MachineCheckSuite Class Reference
MachineCheckSuite Class Reference
#include <MachineCheckSuite.hh>
Public Member Functions
virtual ~MachineCheckSuite ()
int checkCount () const
const MachineCheck & check (int index)
bool run (const TTAMachine::Machine &machine, MachineCheckResults &results)
Protected Member Functions
MachineCheckSuite ()
void addCheck (MachineCheck *check)
Private Attributes
std::vector< MachineCheck * > checks_
Checks contained in the suite.
Detailed Description
Container for a group machine checks that are meant to be run as a test suite.
Definition at line 51 of file MachineCheckSuite.hh.
Constructor & Destructor Documentation
~MachineCheckSuite()
MachineCheckSuite::~MachineCheckSuite () virtual
The Destructor.
Definition at line 47 of file MachineCheckSuite.cc.
{
    SequenceTools::deleteAllItems(checks_);
}
References checks_, and SequenceTools::deleteAllItems().
MachineCheckSuite()
MachineCheckSuite::MachineCheckSuite () protected
The Cosntructor.
Definition at line 41 of file MachineCheckSuite.cc.
{
}
Member Function Documentation
addCheck()
void MachineCheckSuite::addCheck (MachineCheck * check) protected
Adds a check to the suite.
Parameters
check Check to add (suite takes ownership of the check object).
Definition at line 97 of file MachineCheckSuite.cc.
{
    checks_.push_back(check);
}
References check(), and checks_.
Referenced by BasicMachineCheckSuite::BasicMachineCheckSuite().
check()
const MachineCheck & MachineCheckSuite::check (int index)
Definition at line 62 of file MachineCheckSuite.cc.
{
    if (index < 0 || index > checkCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return *checks_[index];
}
References __func__, checkCount(), and checks_.
Referenced by addCheck(), and run().
checkCount()
int MachineCheckSuite::checkCount () const
Returns number of checks in the suite.
Returns
Suite check count.
Definition at line 57 of file MachineCheckSuite.cc.
{
    return checks_.size();
}
References checks_.
Referenced by check(), and run().
run()
bool MachineCheckSuite::run (const TTAMachine::Machine & machine, MachineCheckResults & results)
Runs all checks in the check suite.
Parameters
machine Machine to check.
results Result container where error messages are added.
Returns
True, if all checks passed, false otherwise.
Definition at line 78 of file MachineCheckSuite.cc.
{
    bool pass = true;
    for (int i = 0; i < checkCount(); i++) {
        if (!checks_[i]->check(machine, results)) {
            pass = false;
        }
    }
    return pass;
}
References check(), checkCount(), checks_, and machine.
Member Data Documentation
checks_
std::vector<MachineCheck*> MachineCheckSuite::checks_ private
Checks contained in the suite.
Definition at line 68 of file MachineCheckSuite.hh.
Referenced by addCheck(), check(), checkCount(), run(), and ~MachineCheckSuite().
The documentation for this class was generated from the following files:
MachineCheckSuite.hh
MachineCheckSuite.cc