OpenASIP: CoeImageWriter Class Reference
CoeImageWriter Class Reference
#include <CoeImageWriter.hh>
Public Member Functions
CoeImageWriter (const BitVector &bits, int rowLength)
virtual ~CoeImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Private Member Functions
void writeHeader (std::ostream &stream) const
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Writes the bit image in COE format. It's used at least by Xilinx tools
Definition at line 41 of file CoeImageWriter.hh.
Constructor & Destructor Documentation
CoeImageWriter()
CoeImageWriter::CoeImageWriter (const BitVector & bits, int rowLength)
The constructor.
Parameters
bits The bits to write.
rowLength Length of the rows to write.
Definition at line 46 of file CoeImageWriter.cc.
                                                                   :
    AsciiImageWriter(bits, rowLength) {
}
~CoeImageWriter()
CoeImageWriter::~CoeImageWriter () virtual
The destructor.
Definition at line 53 of file CoeImageWriter.cc.
{
}
Member Function Documentation
writeHeader()
void CoeImageWriter::writeHeader (std::ostream & stream) const private
Writes header to the given stream.
Parameters
stream The stream to write.
Definition at line 88 of file CoeImageWriter.cc.
{
    stream << "; Created by generatebits" << endl;
    stream << "memory_initialization_radix=2;" << endl
           << "memory_initialization_vector=" << endl;
}
Referenced by writeImage().
writeImage()
void CoeImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given stream.
Parameters
stream The stream to write.
Reimplemented from AsciiImageWriter.
Definition at line 61 of file CoeImageWriter.cc.
{
    int lineCount =  static_cast<int>(
        ceil(static_cast<double>(bits().size()) / rowLength()));
    writeHeader(stream);
    if (lineCount == 0) {
        for (int i = 0; i < rowLength(); i++) {
            stream << "0";
        }
    } else {
        bool padEndings = false;
        for (int i = 0; i < lineCount-1; i++) {
            writeSequence(stream, rowLength(), padEndings);
            stream << "," << endl;
        }
        // last line might need padding
        padEndings = true;
        writeSequence(stream, rowLength(), padEndings);
    }
    // format requires semicolon at the end
    stream << ";" << endl;
}
References AsciiImageWriter::bits(), AsciiImageWriter::rowLength(), writeHeader(), and AsciiImageWriter::writeSequence().
The documentation for this class was generated from the following files:
CoeImageWriter.hh
CoeImageWriter.cc