OpenASIP: DisassemblyElement Class Reference
DisassemblyElement Class Reference abstract
#include <DisassemblyElement.hh>
Public Member Functions
virtual ~DisassemblyElement ()
virtual std::string toString () const =0
Protected Member Functions
DisassemblyElement ()
Detailed Description
Represents a source or destination of a move in the disassembler.
Definition at line 41 of file DisassemblyElement.hh.
Constructor & Destructor Documentation
~DisassemblyElement()
DisassemblyElement::~DisassemblyElement () virtual
Destructor.
Definition at line 45 of file DisassemblyElement.cc.
{
}
DisassemblyElement()
DisassemblyElement::DisassemblyElement () protected
Constructor.
Definition at line 38 of file DisassemblyElement.cc.
{
}
Member Function Documentation
toString()
virtual std::string DisassemblyElement::toString () const pure virtual
Implemented in DisassemblyAnnotation, DisassemblyBoolRegister, DisassemblyControlUnitPort, DisassemblyFPRegister, DisassemblyFUOpcodePort, DisassemblyFUOperand, DisassemblyFUPort, DisassemblyImmediate, DisassemblyImmediateRegister, DisassemblyIntRegister, DisassemblyLabel, DisassemblyOperand, DisassemblyRegister, and DisassemblyReturnAddressRegister.
Referenced by DisassemblyGuard::toString(), DisassemblyImmediateAssignment::toString(), and DisassemblyMove::toString().
The documentation for this class was generated from the following files:
DisassemblyElement.hh
DisassemblyElement.cc