OpenASIP: TPEF::LineNumProcedure Class Reference
TPEF::LineNumProcedure Class Reference
#include <LineNumProcedure.hh>
Public Member Functions
LineNumProcedure ()
virtual ~LineNumProcedure ()
void addLine (const LineNumElement *elem)
const LineNumElement * line (HalfWord index) const
HalfWord lineCount () const
void setProcedureSymbol (const ReferenceManager::SafePointer *aRef)
void setProcedureSymbol (SymbolElement *aRef)
SymbolElement * procedureSymbol () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * symbol_
Symbol element of procedure.
std::vector< const LineNumElement * > lines_
Contains LineNumElements of procedure.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Procedure entry for line number section.
Class represents one procedure and contains all line number elements for procedure.
Definition at line 53 of file LineNumProcedure.hh.
Constructor & Destructor Documentation
LineNumProcedure()
TPEF::LineNumProcedure::LineNumProcedure ()
Constructor.
Definition at line 43 of file LineNumProcedure.cc.
                                   : SectionElement(),
    symbol_(&SafePointer::null) {
}
~LineNumProcedure()
TPEF::LineNumProcedure::~LineNumProcedure () virtual
Destructor.
Deletes all line numbers inside procedure.
Definition at line 52 of file LineNumProcedure.cc.
{
    for (HalfWord i = 0; i < lines_.size(); i++) {
        delete lines_[i];
        lines_[i] = NULL;
    }
    lines_.clear();
}
References lines_.
Member Function Documentation
addLine()
void TPEF::LineNumProcedure::addLine (const LineNumElement * elem)
Referenced by TPEF::TPEFLineNumSectionReader::readData().
line()
const LineNumElement * TPEF::LineNumProcedure::line (HalfWord index) const
Referenced by TPEF::TPEFLineNumSectionWriter::actualWriteData().
lineCount()
HalfWord TPEF::LineNumProcedure::lineCount () const
Referenced by TPEF::TPEFLineNumSectionWriter::actualWriteData().
procedureSymbol()
SymbolElement * TPEF::LineNumProcedure::procedureSymbol () const
Referenced by TPEF::TPEFLineNumSectionWriter::actualWriteData().
setProcedureSymbol() [1/2]
void TPEF::LineNumProcedure::setProcedureSymbol (const ReferenceManager::SafePointer * aRef)
Referenced by TPEF::TPEFLineNumSectionReader::readData().
setProcedureSymbol() [2/2]
void TPEF::LineNumProcedure::setProcedureSymbol (SymbolElement * aRef)
Member Data Documentation
lines_
std::vector<const LineNumElement*> TPEF::LineNumProcedure::lines_ private
Contains LineNumElements of procedure.
Definition at line 72 of file LineNumProcedure.hh.
Referenced by ~LineNumProcedure().
symbol_
const ReferenceManager::SafePointer* TPEF::LineNumProcedure::symbol_ private
Symbol element of procedure.
Definition at line 69 of file LineNumProcedure.hh.
The documentation for this class was generated from the following files:
LineNumProcedure.hh
LineNumProcedure.cc