OpenASIP: RFFactory Class Reference
RFFactory Class Reference
#include <RFFactory.hh>
Public Member Functions
RFFactory (EditPolicyFactory &editPolicyFactory)
virtual ~RFFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
RFFactory & operator= (RFFactory &old)
Assignment not allowed.
RFFactory (RFFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating register file EditParts corresponding to a given Machine RegisterFile object.
Definition at line 45 of file RFFactory.hh.
Constructor & Destructor Documentation
RFFactory() [1/2]
RFFactory::RFFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 53 of file RFFactory.cc.
                                                        :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new UnitPortFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~RFFactory()
RFFactory::~RFFactory () virtual
The Destructor.
Definition at line 62 of file RFFactory.cc.
                      {
}
RFFactory() [2/2]
RFFactory::RFFactory (RFFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * RFFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a register file.
Parameters
component Register file of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the RegisterFile class.
Implements Factory.
Definition at line 73 of file RFFactory.cc.
{
    RegisterFile* rf = dynamic_cast<RegisterFile*>(component);
    if (rf != NULL) {
    EditPart* rfEditPart = new EditPart();
    rfEditPart->setModel(rf);
    UnitFigure* fig = new UnitFigure();
    wxString name = WxConversion::toWxString(rf->name().c_str());
    name.Prepend(_T("RF: "));
    fig->setName(name);
    rfEditPart->setFigure(fig);
    for (int i = 0; i < rf->portCount(); i++) {
        vector<Factory*>::const_iterator iter;
        for (iter = factories_.begin(); iter != factories_.end(); iter++) {
        EditPart* portEditPart =
            (*iter)->createEditPart(rf->port(i));
        if (portEditPart != NULL) {
            EditPolicy* editPolicy =
            editPolicyFactory_.createRFPortEditPolicy();
            if (editPolicy != NULL) {
            portEditPart->installEditPolicy(editPolicy);
            }
            rfEditPart->addChild(portEditPart);
        }
        }
    }
        wxString info;
        if (dynamic_cast<UnboundedRegisterFile*>(rf) != NULL) {
            info.Append(_T("?"));
        } else {
            info.Append(WxConversion::toWxString(rf->numberOfRegisters()));
        }
        info.Append(_T("x"));
        info.Append(WxConversion::toWxString(rf->width()));
        fig->setInfo(info);
    rfEditPart->setSelectable(true);
    EditPolicy* editPolicy = editPolicyFactory_.createRFEditPolicy();
    if (editPolicy != NULL) {
        rfEditPart->installEditPolicy(editPolicy);
    }
    return rfEditPart;
    } else {
    return NULL;
    }
}
References EditPart::addChild(), EditPolicyFactory::createRFEditPolicy(), EditPolicyFactory::createRFPortEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), EditPart::setFigure(), UnitFigure::setInfo(), EditPart::setModel(), UnitFigure::setName(), EditPart::setSelectable(), WxConversion::toWxString(), and TTAMachine::BaseRegisterFile::width().
operator=()
RFFactory & RFFactory::operator= (RFFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
RFFactory.hh
RFFactory.cc