OpenASIP: HDLGenerator::BinaryConstant Class Reference
HDLGenerator::BinaryConstant Class Reference
#include <HDLGenerator.hh>
Public Member Functions
BinaryConstant (std::string name, int width, int value)
int value () const noexcept
Width width () final
void declare (std::ostream &stream, Language lang, int level)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang, int indent)
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
int width_
int value_
Detailed Description
Binary constant.
Definition at line 245 of file HDLGenerator.hh.
Constructor & Destructor Documentation
BinaryConstant()
HDLGenerator::BinaryConstant::BinaryConstant (std::string name, int width, int value) inline
Definition at line 247 of file HDLGenerator.hh.
            : Generatable(name), width_(width), value_(value) {}
Member Function Documentation
declare()
void HDLGenerator::BinaryConstant::declare (std::ostream & stream, Language lang, int level) inline
Definition at line 254 of file HDLGenerator.hh.
{
            std::string binVal = "";
            int tempVal = value_;
            for (int i = width_ - 1; i >= 0; --i) {
                long power = static_cast<long>(std::pow(2, i));
                if (power <= tempVal) {
                    tempVal -= power;
                    binVal += "1";
                } else {
                    binVal += "0";
                }
            }
            if (lang == Language::VHDL) {
                stream << StringTools::indent(level) << "constant " << name()
                       << " : std_logic_vector(" << width_ - 1
                       << " downto 0) := \"" << binVal << "\";\n";
            } else if (lang == Language::Verilog) {
                stream << StringTools::indent(level)
                       << "localparam [" << width_-1 << ":0] "
                       << name() << " = " << width_ << "'b" << binVal << ";\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References StringTools::indent(), HDLGenerator::Generatable::name(), value_, HDLGenerator::Verilog, HDLGenerator::VHDL, and width_.
value()
int HDLGenerator::BinaryConstant::value () const inline noexcept
Definition at line 250 of file HDLGenerator.hh.
{ return value_; }
References value_.
width()
Width HDLGenerator::BinaryConstant::width () inline final virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 252 of file HDLGenerator.hh.
{ return {name(), width_}; }
References HDLGenerator::Generatable::name(), and width_.
Member Data Documentation
value_
int HDLGenerator::BinaryConstant::value_ private
Definition at line 282 of file HDLGenerator.hh.
Referenced by declare(), and value().
width_
int HDLGenerator::BinaryConstant::width_ private
Definition at line 281 of file HDLGenerator.hh.
Referenced by declare(), and width().
The documentation for this class was generated from the following file:
HDLGenerator.hh