OpenASIP: SimpleScriptInterpreter Class Reference
SimpleScriptInterpreter Class Reference
#include <SimpleScriptInterpreter.hh>
Public Member Functions
SimpleScriptInterpreter ()
virtual ~SimpleScriptInterpreter ()
virtual void initialize (int argc, char *argv[], InterpreterContext *context, LineReader *reader)
virtual void setVariableToInterpreter (const std::string &name, const DataObject &value)
virtual DataObject variable (const std::string &name)
virtual bool interpret (const std::string &commandLine)
virtual void setResultToInterpreter (const DataObject &value)
virtual InterpreterContext & context () const
Public Member Functions inherited from ScriptInterpreter
ScriptInterpreter ()
virtual ~ScriptInterpreter ()
virtual void addCustomCommand (CustomCommand *command)
virtual void removeCustomCommand (const std::string &commandName)
virtual CustomCommand * customCommand (const std::string &commandName)
virtual void setResult (DataObject *result)
virtual void setResult (const std::string &result)
virtual void setResult (int result)
virtual void setResult (double result)
virtual std::string result ()
virtual void setError (bool state)
virtual void setError (std::string errorMessage)
virtual bool error () const
virtual void setVariable (const std::string &interpreterVariableName, const std::string &value)
virtual void setVariable (const std::string &interpreterVariableName, int value)
virtual std::string variableStringValue (const std::string &interpreterVariableName)
virtual int variableIntegerValue (const std::string &interpreterVariableName)
virtual bool processScriptFile (const std::string &scriptFileName)
virtual void finalize ()
virtual void setLineReader (LineReader *reader)
virtual LineReader * lineReader () const
std::vector< std::string > customCommandsSortedByName ()
Protected Member Functions
virtual void addCustomCommandToInterpreter (const CustomCommand &command)
virtual void removeCustomCommandFromInterpreter (const CustomCommand &command)
Private Types
typedef std::map< std::string, std::string > VariableMap
Map for variables.
Private Member Functions
SimpleScriptInterpreter (const SimpleScriptInterpreter &)
Copying not allowed.
SimpleScriptInterpreter & operator= (const ScriptInterpreter &)
Assignment not allowed.
Private Attributes
VariableMap variables_
Holds all the variables given to interpreter.
InterpreterContext * context_
Context for interpreter.
Detailed Description
Interpreter which uses only custom commands.
Custom commands are user defined commands.
Definition at line 49 of file SimpleScriptInterpreter.hh.
Member Typedef Documentation
VariableMap
typedef std::map<std::string, std::string> SimpleScriptInterpreter::VariableMap private
Map for variables.
Definition at line 75 of file SimpleScriptInterpreter.hh.
Constructor & Destructor Documentation
SimpleScriptInterpreter() [1/2]
SimpleScriptInterpreter::SimpleScriptInterpreter ()
Constructor.
Definition at line 48 of file SimpleScriptInterpreter.cc.
                                                 : ScriptInterpreter() {
}
~SimpleScriptInterpreter()
SimpleScriptInterpreter::~SimpleScriptInterpreter () virtual
Destructor.
Definition at line 54 of file SimpleScriptInterpreter.cc.
{
}
SimpleScriptInterpreter() [2/2]
SimpleScriptInterpreter::SimpleScriptInterpreter (const SimpleScriptInterpreter &) private
Copying not allowed.
Member Function Documentation
addCustomCommandToInterpreter()
void SimpleScriptInterpreter::addCustomCommandToInterpreter (const CustomCommand & command) protected virtual
Does nothing.
Implements ScriptInterpreter.
Definition at line 193 of file SimpleScriptInterpreter.cc.
{
}
context()
InterpreterContext & SimpleScriptInterpreter::context () const virtual
Returns an instance of InterpreteContext.
Returns
InterpreterContext.
Implements ScriptInterpreter.
Definition at line 185 of file SimpleScriptInterpreter.cc.
{
    return *context_;
}
References context_.
Referenced by CmdTrigger::execute(), CmdReset::execute(), CmdQuit::execute(), CmdOutput::execute(), CmdRegister::execute(), CmdMem::execute(), CmdAdvanceClock::execute(), CmdOutput::helpText(), initialize(), main(), and OsalInterpreter::operation().
initialize()
void SimpleScriptInterpreter::initialize (int argc, char * argv[], InterpreterContext * context, LineReader * reader) virtual
Initializes the interpreter.
Parameters
context Context for interpreter.
reader LineReader for interpreter.
Implements ScriptInterpreter.
Definition at line 64 of file SimpleScriptInterpreter.cc.
{
    context_ = context;
    setLineReader(reader);
}
References context(), context_, and ScriptInterpreter::setLineReader().
Referenced by main().
interpret()
bool SimpleScriptInterpreter::interpret (const std::string & commandLine) virtual
Interprets a given command line.
Parameters
commandLine The command line to interpreted.
Returns
True if interpreting was successful, false otherwise.
Implements ScriptInterpreter.
Definition at line 118 of file SimpleScriptInterpreter.cc.
{
    string line = StringTools::trim(commandLine);
    if (commandLine != "") {
        vector<TCEString> commands = StringTools::chopString(commandLine, " ");
        CustomCommand* custCommand = customCommand(commands[0]);
        if (custCommand == NULL) {
            DataObject* result = new DataObject();
            string msg = "Unknown command: " + commands[0];
            result->setString(msg);
            setResult(result);
            return false;
        }
        vector<DataObject> args;
        for (unsigned int i = 0; i < commands.size(); i++) {
            DataObject obj;
            obj.setString(commands[i]);
            args.push_back(obj);
        }
        bool res;
        try {
            res = custCommand->execute(args);
        } catch (const NumberFormatException& n) {
            DataObject* result = new DataObject();
            result->setString(n.errorMessage());
            setResult(result);
            res = false;
        }
        if (res) {
            setError(false);
            return true;
        } else {
            setError(true);
            return false;
        }
    } else {
        // command line was empty
        DataObject* result = new DataObject();
        result->setString("");
        setResult(result);
        setError(false);
        return true;
    }
    assert(false);
    return false;
}
References assert, StringTools::chopString(), ScriptInterpreter::customCommand(), Exception::errorMessage(), CustomCommand::execute(), ScriptInterpreter::result(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), DataObject::setString(), and StringTools::trim().
Referenced by executeCommand(), and main().
operator=()
SimpleScriptInterpreter & SimpleScriptInterpreter::operator= (const ScriptInterpreter &) private
Assignment not allowed.
removeCustomCommandFromInterpreter()
void SimpleScriptInterpreter::removeCustomCommandFromInterpreter (const CustomCommand & command) protected virtual
Does nothing.
Implements ScriptInterpreter.
Definition at line 200 of file SimpleScriptInterpreter.cc.
{
}
setResultToInterpreter()
void SimpleScriptInterpreter::setResultToInterpreter (const DataObject & value) virtual
This function does nothing, because result is already stored in ScriptInterpreter.
Exceptions
Cannot throw.
Implements ScriptInterpreter.
Definition at line 177 of file SimpleScriptInterpreter.cc.
{}
setVariableToInterpreter()
void SimpleScriptInterpreter::setVariableToInterpreter (const std::string & name, const DataObject & value) virtual
Sets variable to interpreter.
Parameters
name The name of the variable.
value The value of the variable.
Exceptions
NumberFormatException Cannot throw.
Implements ScriptInterpreter.
Definition at line 82 of file SimpleScriptInterpreter.cc.
{
    VariableMap::iterator iter = variables_.find(name);
    if (iter == variables_.end()) {
        variables_[name] = value.stringValue();
    } else {
        (*iter).second = value.stringValue();
    }
}
References DataObject::stringValue(), and variables_.
variable()
DataObject SimpleScriptInterpreter::variable (const std::string & name) virtual
Returns the variable with the given name.
If variable is not found, returns uninitialized data object.
Parameters
name The name of the variable.
Returns
The data object that holds the value of the varible.
Implements ScriptInterpreter.
Definition at line 102 of file SimpleScriptInterpreter.cc.
{
    DataObject object;
    VariableMap::iterator iter = variables_.find(name);
    if (iter != variables_.end()) {
        object.setString((*iter).second);
    }
    return object;
}
References DataObject::setString(), and variables_.
Member Data Documentation
context_
InterpreterContext* SimpleScriptInterpreter::context_ private
Context for interpreter.
Definition at line 85 of file SimpleScriptInterpreter.hh.
Referenced by context(), and initialize().
variables_
VariableMap SimpleScriptInterpreter::variables_ private
Holds all the variables given to interpreter.
Definition at line 83 of file SimpleScriptInterpreter.hh.
Referenced by setVariableToInterpreter(), and variable().
The documentation for this class was generated from the following files:
SimpleScriptInterpreter.hh
SimpleScriptInterpreter.cc