OpenASIP: UniversalMachine Class Reference
UniversalMachine Class Reference
#include <UniversalMachine.hh>
Public Member Functions
virtual ~UniversalMachine ()
virtual bool isUniversalMachine () const
UniversalFunctionUnit & universalFunctionUnit () const
TTAMachine::RegisterFile & booleanRegisterFile () const
UnboundedRegisterFile & integerRegisterFile () const
UnboundedRegisterFile & doubleRegisterFile () const
TTAMachine::RegisterFile & specialRegisterFile () const
TTAMachine::AddressSpace & instructionAddressSpace () const
TTAMachine::AddressSpace & dataAddressSpace () const
TTAMachine::Bus & universalBus () const
virtual void addBus (TTAMachine::Bus &bus)
virtual void addSocket (TTAMachine::Socket &socket)
virtual void addFunctionUnit (TTAMachine::FunctionUnit &unit)
virtual void addImmediateUnit (TTAMachine::ImmediateUnit &unit)
virtual void addRegisterFile (TTAMachine::RegisterFile &unit)
virtual void addAddressSpace (TTAMachine::AddressSpace &as)
virtual void addBridge (TTAMachine::Bridge &bridge)
virtual void addInstructionTemplate (TTAMachine::InstructionTemplate &iTemp)
virtual void setGlobalControl (TTAMachine::ControlUnit &unit)
virtual void removeBus (TTAMachine::Bus &bus)
virtual void removeSocket (TTAMachine::Socket &socket)
virtual void removeFunctionUnit (TTAMachine::FunctionUnit &unit)
virtual void removeRegisterFile (TTAMachine::RegisterFile &unit)
virtual void deleteAddressSpace (TTAMachine::AddressSpace &as)
virtual void unsetGlobalControl ()
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Machine
Machine ()
Machine (const Machine &old)
virtual ~Machine ()
void addUnit (Unit &unit)
virtual void addOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void addImmediateSlot (ImmediateSlot &slot)
virtual ControlUnit * controlUnit () const
virtual void removeUnit (Unit &unit)
virtual void removeImmediateUnit (ImmediateUnit &unit)
virtual void deleteBridge (Bridge &bridge)
virtual void deleteInstructionTemplate (InstructionTemplate &instrTempl)
virtual void deleteOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void deleteImmediateSlot (ImmediateSlot &slot)
void setBusPosition (const Bus &bus, int newPosition)
MachineTester & machineTester () const
bool alwaysWriteResults () const
bool triggerInvalidatesResults () const
bool isFUOrdered () const
void setAlwaysWriteResults (bool)
void setTriggerInvalidatesResults (bool)
void setFUOrdered (bool)
int maximumLatency () const
virtual ObjectState * saveState () const
virtual void copyFromMachine (Machine &machine)
void writeToADF (const std::string &adfFileName) const
TCEString hash () const
bool hasOperation (const TCEString &opName) const
bool isRISCVMachine () const
virtual BusNavigator busNavigator () const
virtual SocketNavigator socketNavigator () const
virtual FunctionUnitNavigator functionUnitNavigator () const
virtual AddressSpaceNavigator addressSpaceNavigator () const
virtual BridgeNavigator bridgeNavigator () const
virtual ImmediateUnitNavigator immediateUnitNavigator () const
virtual InstructionTemplateNavigator instructionTemplateNavigator () const
virtual RegisterFileNavigator registerFileNavigator () const
virtual ImmediateSlotNavigator immediateSlotNavigator () const
virtual OperationTriggeredFormatNavigator operationTriggeredFormatNavigator () const
bool isLittleEndian () const
void setLittleEndian (bool flag)
bool is64bit () const
void set64bits (bool flag)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static UniversalMachine & instance ()
Static Public Member Functions inherited from TTAMachine::Machine
static Machine * loadFromADF (const std::string &adfFileName)
Private Member Functions
UniversalMachine ()
void construct ()
Private Attributes
bool isBuilt_
Indicates whether the UniversalMachine is built completely.
OperationPool opPool
The operation pool instance to use for finding operations.
Static Private Attributes
static UniversalMachine * instance_ = NULL
The singleton instance. Use this instance everywhere. Creating multiple instances of UM is deprecated.
Additional Inherited Members
Public Types inherited from TTAMachine::Machine
enum Extension { ZERO , SIGN }
typedef Navigator< Bus > BusNavigator
Navigator type for BusNavigator.
typedef Navigator< Socket > SocketNavigator
Navigator type for SocketNavigator.
typedef Navigator< FunctionUnit > FunctionUnitNavigator
Navigator type for FunctionUnitNavigator.
typedef Navigator< AddressSpace > AddressSpaceNavigator
Navigator type for AddressSpaceNavigator.
typedef Navigator< Bridge > BridgeNavigator
Navigator type for BridgeNavigator.
typedef Navigator< ImmediateUnit > ImmediateUnitNavigator
Navigator type for ImmediateUnitNavigator.
typedef Navigator< InstructionTemplate > InstructionTemplateNavigator
Navigator type for InstructionTemplateNavigator.
typedef Navigator< RegisterFile > RegisterFileNavigator
Navigator type for RegisterFileNavigator.
typedef Navigator< ImmediateSlot > ImmediateSlotNavigator
Navigator type for ImmediateSlotNavigator.
typedef Navigator< OperationTriggeredFormat > OperationTriggeredFormatNavigator
Navigator type for OperationTriggeredFormatNavigator.
Static Public Attributes inherited from TTAMachine::Machine
static const std::string OSNAME_MACHINE = "machine"
ObjectState name for Machine.
static const std::string OSKEY_ALWAYS_WRITE_BACK_RESULTS = "always-write-back"
ObjectState attribute key for always-write-back-results.
static const std::string OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS = "trigger-invalidates"
ObjectState attribute key for trigger-invalidates-old-results.
static const std::string OSKEY_FUNCTION_UNITS_ORDERED = "fu-ordered"
ObjectState attribute key for function units ordered in order of their sequential presence in ADF.
Detailed Description
UniversalMachine is used to mark unassigned/unscheduled resources.
In the old versions of TCE, UniversalMachine represented a TTA processor which used to model an imaginary target for the old "sequential code", an intermediate format from the old gcc frontend. Previously, one UM instance per Program was created but from now one, the singleton object should be used everywhere because UM resources are just used to mark unscheduled parts of the program.
Definition at line 56 of file UniversalMachine.hh.
Constructor & Destructor Documentation
~UniversalMachine()
UniversalMachine::~UniversalMachine () virtual
Destructor.
Definition at line 191 of file UniversalMachine.cc.
{
}
UniversalMachine()
UniversalMachine::UniversalMachine () private
Constructor.
Creates a complete universal machine with all the required components. Only called by instance().
Definition at line 61 of file UniversalMachine.cc.
                                   :
    Machine(), isBuilt_(false) {
    construct();
}
References construct().
Referenced by instance().
Member Function Documentation
addAddressSpace()
void UniversalMachine::addAddressSpace (TTAMachine::AddressSpace & as) virtual
Adds an address space to the machine. Aborts the program if tried to add an address space after the UniversalMachine is constructed. DO NOT CALL THIS METHOD.
Parameters
as The address space being added.
Exceptions
ComponentAlreadyExists If an address space by the same name already exists in the machine.
Reimplemented from TTAMachine::Machine.
Definition at line 427 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::addAddressSpace(as);
    } else {
        const string procName = "UniversalMachine::addAddressSpace";
        const string errorMsg =
            "Tried to add an address space to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), TTAMachine::Machine::addAddressSpace(), isBuilt_, and Application::writeToErrorLog().
addBridge()
void UniversalMachine::addBridge (TTAMachine::Bridge & bridge) virtual
Aborts the program. UniversalMachine can not contain bridges. DO NOT CALL THIS METHOD.
Parameters
bridge Never used.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 447 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::addBridge";
    const string errorMsg = "Tried to add a bridge to UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
addBus()
void UniversalMachine::addBus (TTAMachine::Bus & bus) virtual
Adds a bus to the machine.
Aborts the program if tried to add a bus after the UniversalMachine is constructed. DO NOT CALL THIS METHOD.
Parameters
bus Bus being added.
Exceptions
ComponentAlreadyExists If a bus by the same name already exists in the machine.
Reimplemented from TTAMachine::Machine.
Definition at line 324 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::addBus(bus);
    } else {
        const string procName = "UniversalMachine::addBus";
        const string errorMsg = "Tried to add a bus to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), TTAMachine::Machine::addBus(), isBuilt_, and Application::writeToErrorLog().
Referenced by construct().
addFunctionUnit()
void UniversalMachine::addFunctionUnit (TTAMachine::FunctionUnit & unit) virtual
Adds a function unit to the machine. Aborts the program if tried to add a function unit after the UniversalMachine is constructed. DO NOT CALL THIS METHOD.
Parameters
unit The function unit being added.
Exceptions
ComponentAlreadyExists If a function unit by the same name already exists in the machine.
Reimplemented from TTAMachine::Machine.
Definition at line 367 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::addFunctionUnit(unit);
    } else {
        const string procName = "UniversalMachine::addFunctionUnit";
        const string errorMsg =
            "Tried to add a function unit to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), TTAMachine::Machine::addFunctionUnit(), isBuilt_, and Application::writeToErrorLog().
Referenced by construct().
addImmediateUnit()
void UniversalMachine::addImmediateUnit (TTAMachine::ImmediateUnit & unit) virtual
Aborts the program. It is not allowed to add immediate units to UniversalMachine. DO NOT CALL THIS METHOD.
Parameters
unit Never used.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 387 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::addImmediateUnit";
    const string errorMsg =
        "Tried to add an immediate unit to UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
addInstructionTemplate()
void UniversalMachine::addInstructionTemplate (TTAMachine::InstructionTemplate & iTemp) virtual
Aborts the program. UniversalMachine can not contain instruction templates. DO NOT CALL THIS METHOD!
Parameters
iTemp Never used.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 462 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::addInstructionTemplate";
    const string errorMsg =
        "Tried to add an instruction template to UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
addRegisterFile()
void UniversalMachine::addRegisterFile (TTAMachine::RegisterFile & unit) virtual
Adds a register file to the machine. Aborts the program if tried to add a register file after the UniversalMachine is constructed. DO NOT CALL THIS METHOD.
Parameters
unit The register file being added.
Exceptions
ComponentAlreadyExists If a register file by the same name already exists in the machine.
Reimplemented from TTAMachine::Machine.
Definition at line 405 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::addRegisterFile(unit);
    } else {
        const string procName = "UniversalMachine::addRegisterFile";
        const string errorMsg =
            "Tried to add a register file to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), TTAMachine::Machine::addRegisterFile(), isBuilt_, and Application::writeToErrorLog().
Referenced by construct().
addSocket()
void UniversalMachine::addSocket (TTAMachine::Socket & socket) virtual
Adds a socket to the machine.
Aborts the program if tried to add a socket after the UniversalMachine is constructed. DO NOT CALL THIS METHOD.
Parameters
socket The socket being added.
Exceptions
ComponentAlreadyExists If a socket by the same name already exists in the machine.
Reimplemented from TTAMachine::Machine.
Definition at line 346 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::addSocket(socket);
    } else {
        const string procName = "UniversalMachine::addSocket";
        const string errorMsg = "Tried to add a socket to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), TTAMachine::Machine::addSocket(), isBuilt_, and Application::writeToErrorLog().
Referenced by construct().
booleanRegisterFile()
RegisterFile & UniversalMachine::booleanRegisterFile () const
Returns the boolean register file of the universal machine.
Returns
The boolean register file.
Definition at line 221 of file UniversalMachine.cc.
{
    RegisterFileNavigator rfNav = registerFileNavigator();
    assert(rfNav.hasItem(UM_BOOLEAN_RF_NAME));
    return *rfNav.item(UM_BOOLEAN_RF_NAME);
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Machine::registerFileNavigator(), and UM_BOOLEAN_RF_NAME.
Referenced by TTAProgram::TPEFProgramFactory::findRegisterFile(), and TTAProgram::TPEFResourceUpdater::registerFile().
construct()
void UniversalMachine::construct () private
Actually constructs the resources in the universal machine.
Definition at line 83 of file UniversalMachine.cc.
{
    try {
        // add bus
        Bus* bus = new Bus(UM_BUS_NAME, 64, 32, Machine::ZERO);
        addBus(*bus);
        // add a segment to the bus
        Segment* segment = new Segment(UM_SEGMENT_NAME, *bus);
        // add sockets
        Socket* inputSocket = new Socket(UM_INPUT_SOCKET_NAME);
        Socket* outputSocket =  new Socket(UM_OUTPUT_SOCKET_NAME);
        addSocket(*inputSocket);
        addSocket(*outputSocket);
        inputSocket->attachBus(*segment);
        inputSocket->setDirection(Socket::INPUT);
        outputSocket->attachBus(*segment);
        outputSocket->setDirection(Socket::OUTPUT);
        // add a boolean register file
        RegisterFile* boolean = new RegisterFile(
            UM_BOOLEAN_RF_NAME, 1, 1, 1, 1, 0, RegisterFile::NORMAL);
        addRegisterFile(*boolean);
        (new RFPort(UM_BOOLEAN_RF_WRITE_PORT, *boolean))->
            attachSocket(*inputSocket);
        (new RFPort(UM_BOOLEAN_RF_READ_PORT, *boolean))->
            attachSocket(*outputSocket);
        // add boolean register guards
        new RegisterGuard(false, *boolean, 0, bus);
        new RegisterGuard(true, *boolean, 0, bus);
        // add universal register file for integers
        UnboundedRegisterFile* integerURF = new UnboundedRegisterFile(
            UM_INTEGER_URF_NAME, 32, RegisterFile::NORMAL);
        addRegisterFile(*integerURF);
        (new RFPort(UM_INTEGER_URF_WRITE_PORT, *integerURF))->
            attachSocket(*inputSocket);
        (new RFPort(UM_INTEGER_URF_READ_PORT, *integerURF))->
            attachSocket(*outputSocket);
        // add universal register file for doubles
        UnboundedRegisterFile* doubleURF = new UnboundedRegisterFile(
            UM_DOUBLE_URF_NAME, 64, RegisterFile::NORMAL);
        addRegisterFile(*doubleURF);
        (new RFPort(UM_DOUBLE_URF_WRITE_PORT, *doubleURF))->
            attachSocket(*inputSocket);
        (new RFPort(UM_DOUBLE_URF_READ_PORT, *doubleURF))->
            attachSocket(*outputSocket);
        // add a special register file for function return value
        RegisterFile* specialRF = new RegisterFile(
            UM_SPECIAL_RF_NAME, 1, 32, 1, 1, 0, RegisterFile::NORMAL);
        addRegisterFile(*specialRF);
        (new RFPort(UM_SPECIAL_RF_WRITE_PORT, *specialRF))->
            attachSocket(*inputSocket);
        (new RFPort(UM_SPECIAL_RF_READ_PORT, *specialRF))->
            attachSocket(*outputSocket);
        // add address space for instruction memory
        AddressSpace* iMem = new AddressSpace(
            UM_IMEM_NAME, 8, 0, 0xFFFFFF, *this);
        // add address space for data memory
        AddressSpace* dMem = new AddressSpace(
            UM_DMEM_NAME, 8, 0, DATA_MEM_SIZE_UINT - 1, *this);
        // add universal function unit
        UniversalFunctionUnit* uFU = new UniversalFunctionUnit(
            UM_UNIVERSAL_FU_NAME, opPool);
        addFunctionUnit(*uFU);
        uFU->setAddressSpace(dMem);
        // add control unit
        ControlUnit* cu = new ControlUnit(UM_GCU_NAME, 0, 1);
        setGlobalControl(*cu);
        cu->setAddressSpace(iMem);
        HWOperation* callOp = new HWOperation("CALL", *cu);
        HWOperation* jumpOp = new HWOperation("JUMP", *cu);
        FUPort* port1 = new FUPort("port1", 32, *cu, true, true);
        port1->attachSocket(*inputSocket);
        FUPort* port2 = new FUPort("port2", 32, *cu, false, false);
        port2->attachSocket(*inputSocket);
        SpecialRegisterPort* raPort = new SpecialRegisterPort("ra", 32, *cu);
        raPort->attachSocket(*inputSocket);
        raPort->attachSocket(*outputSocket);
        cu->setReturnAddressPort(*raPort);
        // create pipelines and operand bindings of GCU operations
        callOp->bindPort(1, *port1);
        callOp->pipeline()->addPortRead(1, 0, 1);
        jumpOp->bindPort(1, *port1);
        jumpOp->pipeline()->addPortRead(1, 0, 1);
    } catch (const Exception& exception) {
        const string procName = "UniversalMachine::UniversalMachine";
        Application::writeToErrorLog(
            __FILE__, __LINE__, procName, exception.errorMessage());
        Application::abortProgram();
    }
    isBuilt_ = true;
}
References Application::abortProgram(), addBus(), addFunctionUnit(), TTAMachine::ExecutionPipeline::addPortRead(), addRegisterFile(), addSocket(), TTAMachine::Socket::attachBus(), TTAMachine::Port::attachSocket(), TTAMachine::HWOperation::bindPort(), DATA_MEM_SIZE_UINT, Exception::errorMessage(), TTAMachine::Socket::INPUT, isBuilt_, TTAMachine::RegisterFile::NORMAL, opPool, TTAMachine::Socket::OUTPUT, TTAMachine::HWOperation::pipeline(), TTAMachine::FunctionUnit::setAddressSpace(), TTAMachine::Socket::setDirection(), setGlobalControl(), TTAMachine::ControlUnit::setReturnAddressPort(), UM_BOOLEAN_RF_NAME, UM_BOOLEAN_RF_READ_PORT, UM_BOOLEAN_RF_WRITE_PORT, UM_BUS_NAME, UM_DMEM_NAME, UM_DOUBLE_URF_NAME, UM_DOUBLE_URF_READ_PORT, UM_DOUBLE_URF_WRITE_PORT, UM_GCU_NAME, UM_IMEM_NAME, UM_INPUT_SOCKET_NAME, UM_INTEGER_URF_NAME, UM_INTEGER_URF_READ_PORT, UM_INTEGER_URF_WRITE_PORT, UM_OUTPUT_SOCKET_NAME, UM_SEGMENT_NAME, UM_SPECIAL_RF_NAME, UM_SPECIAL_RF_READ_PORT, UM_SPECIAL_RF_WRITE_PORT, UM_UNIVERSAL_FU_NAME, Application::writeToErrorLog(), and TTAMachine::Machine::ZERO.
Referenced by UniversalMachine().
dataAddressSpace()
AddressSpace & UniversalMachine::dataAddressSpace () const
Returns the address space of data memory.
Returns
The address space of data memory.
Definition at line 293 of file UniversalMachine.cc.
{
    AddressSpaceNavigator asNav = addressSpaceNavigator();
    assert(asNav.hasItem(UM_DMEM_NAME));
    return *asNav.item(UM_DMEM_NAME);
}
References TTAMachine::Machine::addressSpaceNavigator(), assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), and UM_DMEM_NAME.
Referenced by TTAProgram::TPEFProgramFactory::findAddressSpace().
deleteAddressSpace()
void UniversalMachine::deleteAddressSpace (TTAMachine::AddressSpace & as) virtual
Aborts the program. It is not allowed to delete address spaces from UniversalMachine. DO NOT CALL THIS METHOD!
Parameters
as Never used.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 561 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::deleteAddressSpace";
    const string errorMsg =
        "Tried to delete address space from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
doubleRegisterFile()
UnboundedRegisterFile & UniversalMachine::doubleRegisterFile () const
Returns the unbounded register file for double precision floating point numbers.
Returns
The unbounded register file for doubles.
Definition at line 251 of file UniversalMachine.cc.
{
    RegisterFileNavigator rfNav = registerFileNavigator();
    assert(rfNav.hasItem(UM_DOUBLE_URF_NAME));
    RegisterFile* rf = rfNav.item(UM_DOUBLE_URF_NAME);
    UnboundedRegisterFile* urf = dynamic_cast<UnboundedRegisterFile*>(rf);
    assert(urf != NULL);
    return *urf;
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Machine::registerFileNavigator(), and UM_DOUBLE_URF_NAME.
Referenced by TTAProgram::TPEFProgramFactory::findRegisterFile(), and TTAProgram::TPEFResourceUpdater::registerFile().
instance()
UniversalMachine & UniversalMachine::instance () static
Use this to get access to an UM.
Do not explicitly create new instances of UM anymore. It's deprecated and won't work in the future. *
Definition at line 73 of file UniversalMachine.cc.
{
    if (instance_ == NULL)
        instance_ = new UniversalMachine();
    return *instance_;
}
References instance_, and UniversalMachine().
Referenced by BusBroker::allAvailableResources(), BusBroker::assign(), llvm::LLVMTCEBuilder::createMove(), llvm::LLVMTCEBuilder::createTerminal(), llvm::LLVMTCEBuilder::createTerminalRegister(), MoveNodeDuplicator::duplicateMove(), llvm::LLVMTCEBuilder::emitComparisonForBranch(), llvm::LLVMTCEBuilder::emitGlobalXXtructorCalls(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCEBuilder::emitRemaingingBrach(), llvm::LLVMTCEBuilder::emitReturn(), llvm::LLVMTCEBuilder::emitSelect(), llvm::LLVMTCEBuilder::emitSPInitialization(), CopyingDelaySlotFiller::fillDelaySlots(), llvm::LLVMTCEBuilder::getHWOperation(), CallsToJumps::handleControlFlowGraph(), CopyingDelaySlotFiller::initialize(), TTAProgram::Program::loadFromUnscheduledTPEF(), main(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), DataDependenceGraph::setMachine(), MachineInfo::triggerIndex(), BusBroker::unassign(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), BFScheduleTD::undoOnlyMe(), and TTAProgram::Program::universalMachine().
instructionAddressSpace()
AddressSpace & UniversalMachine::instructionAddressSpace () const
Returns the address space of instruction memory.
Returns
The address space of instruction memory.
Definition at line 280 of file UniversalMachine.cc.
{
    AddressSpaceNavigator asNav = addressSpaceNavigator();
    assert(asNav.hasItem(UM_IMEM_NAME));
    return *asNav.item(UM_IMEM_NAME);
}
References TTAMachine::Machine::addressSpaceNavigator(), assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), and UM_IMEM_NAME.
Referenced by TTAProgram::TPEFProgramFactory::build(), ProgramDependenceGraph::disassemble(), and TTAProgram::TPEFProgramFactory::findAddressSpace().
integerRegisterFile()
UnboundedRegisterFile & UniversalMachine::integerRegisterFile () const
Returns the unbounded register file for integers.
Returns
The unbounded register file for integers.
Definition at line 234 of file UniversalMachine.cc.
{
    RegisterFileNavigator rfNav = registerFileNavigator();
    assert(rfNav.hasItem(UM_INTEGER_URF_NAME));
    RegisterFile* rf = rfNav.item(UM_INTEGER_URF_NAME);
    UnboundedRegisterFile* urf = dynamic_cast<UnboundedRegisterFile*>(rf);
    assert(urf != NULL);
    return *urf;
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Machine::registerFileNavigator(), and UM_INTEGER_URF_NAME.
Referenced by llvm::LLVMTCEBuilder::createTerminalRegister(), TTAProgram::CodeGenerator::createTerminalRegister(), TTAProgram::TPEFProgramFactory::findRegisterFile(), DataDependenceGraphBuilder::findStaticRegisters(), and TTAProgram::TPEFResourceUpdater::registerFile().
isUniversalMachine()
bool UniversalMachine::isUniversalMachine () const virtual
Reimplemented from TTAMachine::Machine.
Definition at line 195 of file UniversalMachine.cc.
{
    return true;
}
loadState()
void UniversalMachine::loadState (const ObjectState * state) virtual
Redefinement of this method prevents loading the state of UniversalMachine from an ObjectState tree. Aborts the program if this method is called. DO NOT CALL THIS METHOD.
Parameters
state ObjectState instance.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 593 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::loadState";
    const string errorMsg =
        "Tried to load UniversalMachine from an ObjectState tree!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
removeBus()
void UniversalMachine::removeBus (TTAMachine::Bus & bus) virtual
Aborts the program. It is not allowed to remove buses from UniversalMachine. DO NOT CALL THIS METHOD!
Parameters
bus Never used.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 499 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::removeBus";
    const string errorMsg = "Tried to remove bus from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
removeFunctionUnit()
void UniversalMachine::removeFunctionUnit (TTAMachine::FunctionUnit & unit) virtual
Aborts the program. It is not allowed to remove function units from UniversalMachine. DO NOT CALL THIS METHOD!
Parameters
unit Never used.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 529 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::removeFunctionUnit";
    const string errorMsg =
        "Tried to remove function unit from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
removeRegisterFile()
void UniversalMachine::removeRegisterFile (TTAMachine::RegisterFile & unit) virtual
Aborts the program. It is not allowed to remove register files from UniversalMachine. DO NOT CALL THIS METHOD!
Parameters
unit Never used.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 545 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::removeRegisterFile";
    const string errorMsg =
        "Tried to remove register file from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
removeSocket()
void UniversalMachine::removeSocket (TTAMachine::Socket & socket) virtual
Aborts the program. It is not allowed to remove sockets from UniversalMachine. DO NOT CALL THIS METHOD!
Parameters
socket Never used.
Exceptions
InstanceNotFound Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 514 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::removeSocket";
    const string errorMsg = "Tried to remove socket from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
setGlobalControl()
void UniversalMachine::setGlobalControl (TTAMachine::ControlUnit & unit) virtual
Sets the control unit of the machine. Aborts the program if tried to set the control unit after the UniversalMachine is constructed. DO NOT CALL THIS METHOD!
Parameters
unit The control unit to be set.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::Machine.
Definition at line 479 of file UniversalMachine.cc.
{
    if (!isBuilt_) {
        Machine::setGlobalControl(unit);
    } else {
        const string procName = "UniversalMachine::setGlobalControl";
        const string errorMsg =
            "Tried to set control unit to UniversalMachine!";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
    }
}
References Application::abortProgram(), isBuilt_, TTAMachine::Machine::setGlobalControl(), and Application::writeToErrorLog().
Referenced by construct().
specialRegisterFile()
RegisterFile & UniversalMachine::specialRegisterFile () const
Returns the special register file.
Returns
The special register file.
Definition at line 267 of file UniversalMachine.cc.
{
    RegisterFileNavigator rfNav = registerFileNavigator();
    assert(rfNav.hasItem(UM_SPECIAL_RF_NAME));
    return *rfNav.item(UM_SPECIAL_RF_NAME);
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Machine::registerFileNavigator(), and UM_SPECIAL_RF_NAME.
universalBus()
Bus & UniversalMachine::universalBus () const
Returns the only transport bus of universal machine.
Returns
The bus.
Definition at line 306 of file UniversalMachine.cc.
{
    BusNavigator busNav = busNavigator();
    assert(busNav.hasItem(UM_BUS_NAME));
    return *busNav.item(UM_BUS_NAME);
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), and UM_BUS_NAME.
Referenced by TTAProgram::CodeGenerator::addAnnotatedMoveToProcedure(), TTAProgram::CodeGenerator::addMoveToProcedure(), BusBroker::allAvailableResources(), BusBroker::assign(), TTAProgram::TPEFResourceUpdater::bus(), TTAProgram::CodeGenerator::createCall(), ProgramDependenceGraph::createJump(), TTAProgram::CodeGenerator::createJump(), llvm::LLVMTCEBuilder::createMove(), TTAProgram::CodeGenerator::createMove(), llvm::LLVMTCEBuilder::emitComparisonForBranch(), llvm::LLVMTCEBuilder::emitGlobalXXtructorCalls(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEPOMBuilder::emitMove(), llvm::LLVMTCEBuilder::emitOperationMacro(), llvm::LLVMTCEBuilder::emitRemaingingBrach(), llvm::LLVMTCEBuilder::emitReturn(), llvm::LLVMTCEBuilder::emitSelect(), llvm::LLVMTCEBuilder::emitSPInitialization(), TTAProgram::TPEFProgramFactory::findBus(), TTAProgram::TPEFProgramFactory::findPort(), CopyingDelaySlotFiller::getMove(), CallsToJumps::handleControlFlowGraph(), BFScheduleBU::operator()(), BFScheduleTD::operator()(), BusBroker::unassign(), BFRescheduleMove::undoOnlyMe(), BFScheduleBU::undoOnlyMe(), and BFScheduleTD::undoOnlyMe().
universalFunctionUnit()
UniversalFunctionUnit & UniversalMachine::universalFunctionUnit () const
Returns the universal function unit of the machine.
Returns
The universal function unit.
Definition at line 205 of file UniversalMachine.cc.
{
    FunctionUnitNavigator fuNav = functionUnitNavigator();
    assert(fuNav.hasItem(UM_UNIVERSAL_FU_NAME));
    FunctionUnit* fu = fuNav.item(UM_UNIVERSAL_FU_NAME);
    UniversalFunctionUnit* ufu = dynamic_cast<UniversalFunctionUnit*>(fu);
    assert(ufu != NULL);
    return *ufu;
}
References assert, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), and UM_UNIVERSAL_FU_NAME.
Referenced by TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::CodeGenerator::createForLoopBufferInit(), TTAProgram::CodeGenerator::createTerminalFUPort(), TTAProgram::CodeGenerator::createWhileLoopBufferInit(), MoveNodeDuplicator::duplicateMove(), llvm::LLVMTCEBuilder::emitOperationMacro(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), TTAProgram::TPEFResourceUpdater::functionUnit(), llvm::LLVMTCEBuilder::getHWOperation(), and CopyingDelaySlotFiller::getMove().
unsetGlobalControl()
void UniversalMachine::unsetGlobalControl () virtual
Aborts the program. It is not allowed to unset global control unit from UniversalMachine. DO NOT CALL THIS METHOD!
Reimplemented from TTAMachine::Machine.
Definition at line 574 of file UniversalMachine.cc.
{
    const string procName = "UniversalMachine::unsetglobalControl";
    const string errorMsg =
        "Tried to unset global control unit from UniversalMachine!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
Member Data Documentation
instance_
UniversalMachine * UniversalMachine::instance_ = NULL static private
The singleton instance. Use this instance everywhere. Creating multiple instances of UM is deprecated.
Definition at line 102 of file UniversalMachine.hh.
Referenced by instance().
isBuilt_
bool UniversalMachine::isBuilt_ private
Indicates whether the UniversalMachine is built completely.
Definition at line 97 of file UniversalMachine.hh.
Referenced by addAddressSpace(), addBus(), addFunctionUnit(), addRegisterFile(), addSocket(), construct(), and setGlobalControl().
opPool
OperationPool UniversalMachine::opPool private
The operation pool instance to use for finding operations.
Definition at line 99 of file UniversalMachine.hh.
Referenced by construct().
The documentation for this class was generated from the following files:
UniversalMachine.hh
UniversalMachine.cc