OpenASIP: TTAProgram::InstructionReferenceImpl Class Reference
TTAProgram::InstructionReferenceImpl Class Reference
#include <InstructionReferenceImpl.hh>
Public Member Functions
InstructionReferenceImpl (TTAProgram::Instruction &ins, TTAProgram::InstructionReferenceManager &irm)
~InstructionReferenceImpl ()
void nullify ()
void addRef (InstructionReference &ref)
bool removeRef (InstructionReference &ref)
InstructionReferenceManager & referencemanager ()
void setInstruction (Instruction &ins)
void merge (InstructionReferenceImpl &other)
Instruction & instruction ()
unsigned int count ()
const InstructionReference & ref ()
Private Member Functions
InstructionReferenceImpl ()
InstructionReferenceImpl (const InstructionReferenceImpl &)
Private Attributes
Instruction * ins_
std::set< InstructionReference * > refs_
InstructionReferenceManager * refMan_
Detailed Description
Definition at line 48 of file InstructionReferenceImpl.hh.
Constructor & Destructor Documentation
InstructionReferenceImpl() [1/3]
TTAProgram::InstructionReferenceImpl::InstructionReferenceImpl (TTAProgram::Instruction & ins, TTAProgram::InstructionReferenceManager & irm)
Constructor.
Stores the instruction and reference manager.
Parameters
ins Instruction whose references this will handle
irm the InstructionReferenceManager owning this object.
Definition at line 60 of file InstructionReferenceImpl.cc.
                                                                  :
    ins_(&ins), refMan_(&irm) {}
~InstructionReferenceImpl()
TTAProgram::InstructionReferenceImpl::~InstructionReferenceImpl ()
Destructor.
Just asserts no refs point into this.
Definition at line 70 of file InstructionReferenceImpl.cc.
{
    assert(refs_.empty());
}
References assert, and refs_.
InstructionReferenceImpl() [2/3]
TTAProgram::InstructionReferenceImpl::InstructionReferenceImpl () private
InstructionReferenceImpl() [3/3]
TTAProgram::InstructionReferenceImpl::InstructionReferenceImpl (const InstructionReferenceImpl &) private
Member Function Documentation
addRef()
void TTAProgram::InstructionReferenceImpl::addRef (InstructionReference & ref)
A new reference has been created for the instruction handled by this object. Adds it to the list.
Parameters
InstructionReference new reference.
Definition at line 100 of file InstructionReferenceImpl.cc.
{
    refs_.insert(&ref);
}
References ref(), and refs_.
Referenced by TTAProgram::InstructionReference::InstructionReference(), TTAProgram::InstructionReference::InstructionReference(), TTAProgram::InstructionReference::operator=(), and TTAProgram::InstructionReference::setImpl().
count()
unsigned int TTAProgram::InstructionReferenceImpl::count () inline
instruction()
Instruction & TTAProgram::InstructionReferenceImpl::instruction () inline
Referenced by TTAProgram::InstructionReference::instruction().
merge()
void TTAProgram::InstructionReferenceImpl::merge (InstructionReferenceImpl & other)
Merges another irimpl to this object.
Makes all of it's references to point into this instead. This will also indirectly lead to the deletion of the other. This is used for irm.update() when the new target ins already has a ref.
Parameters
other InstructionRefererenceImpl which to merge into this.
Definition at line 134 of file InstructionReferenceImpl.cc.
{
    // copy this in order to prevent it being deleted on last iteration
    std::set<InstructionReference*> otherRefs = other.refs_;
    for (std::set<InstructionReference*>::iterator iter =
             otherRefs.begin(); iter != otherRefs.end(); iter++) {
        (*iter)->setImpl(this);
    }
}
References refs_.
Referenced by TTAProgram::InstructionReferenceManager::replace().
nullify()
void TTAProgram::InstructionReferenceImpl::nullify ()
Nullifies all references pointing to this.
This should only be called by instructionreferenec manager when removing zombie refs.
Definition at line 81 of file InstructionReferenceImpl.cc.
{
    // the set is modified inside so cannot iterate normally.
    // get the first as long as there are some.
    while (!refs_.empty()) {
        // if setimpl return false, I am dead and cannot do
        // anything.
        if (!(*refs_.begin())->setImpl(NULL)) {
            return;
        }
    }
}
References refs_.
ref()
const InstructionReference & TTAProgram::InstructionReferenceImpl::ref ()
Returns a reference pointing into instruction handled by this object.
Returns
some InstructionReference pointing to this.
Definition at line 161 of file InstructionReferenceImpl.cc.
{
    return **refs_.begin();
}
References refs_.
Referenced by addRef(), and removeRef().
referencemanager()
InstructionReferenceManager & TTAProgram::InstructionReferenceImpl::referencemanager ()
removeRef()
bool TTAProgram::InstructionReferenceImpl::removeRef (InstructionReference & ref)
A reference no longer points to instruction handled by this object.
Removes it from the list. If it was last, ask InstructionReferenceManager to delete this object.
Parameters
ref reference which no longer points here
Returns
true if impl stays alive, false if dies.(removed last ref)
Definition at line 114 of file InstructionReferenceImpl.cc.
{
    assert(refs_.find(&ref) != refs_.end());
    refs_.erase(&ref);
    if (refs_.empty()) {
        refMan_->referenceDied(ins_);
        return false;
    }
    return true;
}
References assert, ins_, ref(), TTAProgram::InstructionReferenceManager::referenceDied(), refMan_, and refs_.
Referenced by TTAProgram::InstructionReference::operator=(), TTAProgram::InstructionReference::setImpl(), and TTAProgram::InstructionReference::~InstructionReference().
setInstruction()
void TTAProgram::InstructionReferenceImpl::setInstruction (Instruction & ins)
Sets this object to point into another instruction.
This method should be only called by InstructionReferenceManager.
Parameters
ins new insruction where to point.
Definition at line 151 of file InstructionReferenceImpl.cc.
{
    ins_ = &ins;
}
References ins_.
Referenced by TTAProgram::InstructionReferenceManager::replace().
Member Data Documentation
ins_
Instruction* TTAProgram::InstructionReferenceImpl::ins_ private
Definition at line 65 of file InstructionReferenceImpl.hh.
Referenced by removeRef(), and setInstruction().
refMan_
InstructionReferenceManager* TTAProgram::InstructionReferenceImpl::refMan_ private
Definition at line 67 of file InstructionReferenceImpl.hh.
Referenced by removeRef().
refs_
std::set<InstructionReference*> TTAProgram::InstructionReferenceImpl::refs_ private
Definition at line 66 of file InstructionReferenceImpl.hh.
Referenced by addRef(), merge(), nullify(), ref(), removeRef(), and ~InstructionReferenceImpl().
The documentation for this class was generated from the following files:
InstructionReferenceImpl.hh
InstructionReferenceImpl.cc