OpenASIP: IPXactResetInterface Class Reference
IPXactResetInterface Class Reference
#include <IPXactResetInterface.hh>
Public Member Functions
IPXactResetInterface ()
virtual ~IPXactResetInterface ()
virtual bool mapPortsToInterface (const ProGe::NetlistBlock &toplevel)
Public Member Functions inherited from IPXactInterface
IPXactInterface ()
virtual ~IPXactInterface ()
virtual TCEString instanceName () const
virtual IPXact::Vlnv busType () const
virtual IPXact::Vlnv busAbstractionType () const
virtual IPXactModel::BusMode busMode () const
virtual const PlatInt::SignalMappingList & interfaceMapping () const
virtual void addSignalMapping (const TCEString &actualSignal, const TCEString &busSignal)
void setInstanceName (const TCEString &name)
Static Private Attributes
static const TCEString TTA_RESET_PORT = "rstx"
static const TCEString SPIRIT_RESET_PORT = "RESETn"
static const TCEString DEFAULT_INSTANCE_NAME = "rst_n"
static const TCEString VENDOR = "TUT"
static const TCEString LIBRARY ="ip.hwp.interface"
static const TCEString NAME ="reset.busdef"
static const TCEString BUS_VERSION = "1.0"
static const TCEString ABS_VENDOR
static const TCEString ABS_LIBRARY
static const TCEString ABS_NAME = "reset.absDef"
static const TCEString ABS_VERSION
static const IPXactModel::BusMode DEFAULT_BUS_MODE
Additional Inherited Members
Protected Member Functions inherited from IPXactInterface
void setBusMode (IPXactModel::BusMode mode)
void setBusType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
void setBusAbsType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
Detailed Description
Definition at line 37 of file IPXactResetInterface.hh.
Constructor & Destructor Documentation
IPXactResetInterface()
IPXactResetInterface::IPXactResetInterface ()
Definition at line 54 of file IPXactResetInterface.cc.
                                          : IPXactInterface() {
    setInstanceName(DEFAULT_INSTANCE_NAME);
    setBusType(VENDOR, LIBRARY, NAME, BUS_VERSION);
    setBusAbsType(ABS_VENDOR, ABS_LIBRARY, ABS_NAME, ABS_VERSION);
    setBusMode(DEFAULT_BUS_MODE);
}
References ABS_LIBRARY, ABS_NAME, ABS_VENDOR, ABS_VERSION, BUS_VERSION, DEFAULT_BUS_MODE, DEFAULT_INSTANCE_NAME, LIBRARY, NAME, IPXactInterface::setBusAbsType(), IPXactInterface::setBusMode(), IPXactInterface::setBusType(), IPXactInterface::setInstanceName(), and VENDOR.
~IPXactResetInterface()
IPXactResetInterface::~IPXactResetInterface () virtual
Definition at line 62 of file IPXactResetInterface.cc.
{
}
Member Function Documentation
mapPortsToInterface()
bool IPXactResetInterface::mapPortsToInterface (const ProGe::NetlistBlock & toplevel) virtual
Implements IPXactInterface.
Definition at line 66 of file IPXactResetInterface.cc.
{
    for (size_t i = 0; i < toplevel.portCount(); i++) {
        if (toplevel.port(i).name() == TTA_RESET_PORT) {
            addSignalMapping(TTA_RESET_PORT, SPIRIT_RESET_PORT);
            return true;
        }
    }
    TCEString msg = "Reset port " + TTA_RESET_PORT + " not found!";
    InvalidData exc(__FILE__, __LINE__, "IPXactResetInterface", msg);
    throw exc;
    return false;
}
References IPXactInterface::addSignalMapping(), ProGe::NetlistPort::name(), ProGe::NetlistBlock::port(), ProGe::NetlistBlock::portCount(), SPIRIT_RESET_PORT, and TTA_RESET_PORT.
Member Data Documentation
ABS_LIBRARY
const TCEString IPXactResetInterface::ABS_LIBRARY static private
Initial value:
=
    IPXactResetInterface::LIBRARY
Definition at line 57 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
ABS_NAME
const TCEString IPXactResetInterface::ABS_NAME = "reset.absDef" static private
Definition at line 58 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
ABS_VENDOR
const TCEString IPXactResetInterface::ABS_VENDOR static private
Initial value:
=
    IPXactResetInterface::VENDOR
Definition at line 56 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
ABS_VERSION
const TCEString IPXactResetInterface::ABS_VERSION static private
Initial value:
=
    IPXactResetInterface::BUS_VERSION
Definition at line 59 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
BUS_VERSION
const TCEString IPXactResetInterface::BUS_VERSION = "1.0" static private
Definition at line 55 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
DEFAULT_BUS_MODE
const IPXactModel::BusMode IPXactResetInterface::DEFAULT_BUS_MODE static private
Initial value:
=
    IPXactModel::SLAVE
Definition at line 61 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
DEFAULT_INSTANCE_NAME
const TCEString IPXactResetInterface::DEFAULT_INSTANCE_NAME = "rst_n" static private
Definition at line 51 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
LIBRARY
const TCEString IPXactResetInterface::LIBRARY ="ip.hwp.interface" static private
Definition at line 53 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
NAME
const TCEString IPXactResetInterface::NAME ="reset.busdef" static private
Definition at line 54 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
SPIRIT_RESET_PORT
const TCEString IPXactResetInterface::SPIRIT_RESET_PORT = "RESETn" static private
Definition at line 49 of file IPXactResetInterface.hh.
Referenced by mapPortsToInterface().
TTA_RESET_PORT
const TCEString IPXactResetInterface::TTA_RESET_PORT = "rstx" static private
Definition at line 48 of file IPXactResetInterface.hh.
Referenced by mapPortsToInterface().
VENDOR
const TCEString IPXactResetInterface::VENDOR = "TUT" static private
Definition at line 52 of file IPXactResetInterface.hh.
Referenced by IPXactResetInterface().
The documentation for this class was generated from the following files:
IPXactResetInterface.hh
IPXactResetInterface.cc