OpenASIP: ProgramDependenceEdge Class Reference
ProgramDependenceEdge Class Reference
#include <ProgramDependenceEdge.hh>
Public Types
enum EdgeType { PDG_EDGE_CONTROL , PDG_EDGE_DATA , PDG_EDGE_LOOP_CLOSE , PDG_EDGE_CONTROL_ARTIFICIAL }
Public Member Functions
ProgramDependenceEdge (ControlDependenceEdge &cEdge)
ProgramDependenceEdge (DataDependenceEdge &cEdge)
ProgramDependenceEdge (EdgeType type=PDG_EDGE_CONTROL_ARTIFICIAL)
virtual ~ProgramDependenceEdge ()
bool isControlDependence () const
bool isDataDependence () const
bool isArtificialControlDependence () const
bool isLoopCloseEdge () const
ControlDependenceEdge & controlDependenceEdge ()
DataDependenceEdge & dataDependenceEdge ()
TCEString toString () const
TCEString dotString () const
void setFixed ()
bool fixed ()
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual GraphEdge * clone () const
virtual ~GraphEdge ()
virtual int edgeID () const
virtual bool isBackEdge () const
int weight () const
void setWeight (int w)
Private Attributes
ControlDependenceEdge * cEdge_
DataDependenceEdge * dEdge_
EdgeType type_
bool fixed_
Set to fixed if edge is not to be moved any more while serializing.
Detailed Description
Definition at line 41 of file ProgramDependenceEdge.hh.
Member Enumeration Documentation
EdgeType
enum ProgramDependenceEdge::EdgeType
Enumerator
PDG_EDGE_CONTROL
PDG_EDGE_DATA
Indicates Control Dependence Edge from CDG.
PDG_EDGE_LOOP_CLOSE
Indicates Data Dependence Edge from DDG.
PDG_EDGE_CONTROL_ARTIFICIAL
Loop close edge from close node to loop entry.
Indicates artificial control edge for serialization
Definition at line 43 of file ProgramDependenceEdge.hh.
                  {
        PDG_EDGE_CONTROL, /// Indicates Control Dependence Edge from CDG
        PDG_EDGE_DATA, /// Indicates Data Dependence Edge from DDG
        PDG_EDGE_LOOP_CLOSE, /// Loop close edge from close node to loop entry
        PDG_EDGE_CONTROL_ARTIFICIAL /// Indicates artificial control edge for
                                    /// serialization
    };
Constructor & Destructor Documentation
ProgramDependenceEdge() [1/3]
ProgramDependenceEdge::ProgramDependenceEdge (ControlDependenceEdge & cEdge)
Constructor, makes new Program Dependence Edge with reference to original Control Dependence Edge in CDG.
Parameters
cEdge Control Dependence Edge
Definition at line 50 of file ProgramDependenceEdge.cc.
    : cEdge_(&cEdge), dEdge_(NULL), type_(PDG_EDGE_CONTROL), fixed_(false) {
    if (cEdge.isLoopCloseEdge()) {
        type_ = PDG_EDGE_LOOP_CLOSE;
    } else {
        type_ = PDG_EDGE_CONTROL;
    }
}
References ControlDependenceEdge::isLoopCloseEdge(), PDG_EDGE_CONTROL, PDG_EDGE_LOOP_CLOSE, and type_.
ProgramDependenceEdge() [2/3]
ProgramDependenceEdge::ProgramDependenceEdge (DataDependenceEdge & dEdge)
Constructor, makes new Program Dependence Edge with reference to original Data Dependence Edge in DDG.
Parameters
dEdge Data Dependence Edge
Definition at line 65 of file ProgramDependenceEdge.cc.
    : cEdge_(NULL), dEdge_(&dEdge), type_(PDG_EDGE_DATA), fixed_(false) {
}
ProgramDependenceEdge() [3/3]
ProgramDependenceEdge::ProgramDependenceEdge (EdgeType type = PDG_EDGE_CONTROL_ARTIFICIAL)
Constructor, makes new Program Dependence Edge without reference to original Control Dependence Edge in CDG. It is artificial edge.
Definition at line 41 of file ProgramDependenceEdge.cc.
    : cEdge_(NULL), dEdge_(NULL), type_(type), fixed_(false) {
}
~ProgramDependenceEdge()
ProgramDependenceEdge::~ProgramDependenceEdge () virtual
Empty destructor.
Definition at line 73 of file ProgramDependenceEdge.cc.
{
}
Member Function Documentation
controlDependenceEdge()
ControlDependenceEdge & ProgramDependenceEdge::controlDependenceEdge ()
Returns reference to control dependence edge of CDG.
Returns
control dependence edge of underlying CDG
Definition at line 166 of file ProgramDependenceEdge.cc.
{
    if (cEdge_ != NULL) {
        return *cEdge_;
    } else {
        throw InvalidData(__FILE__, __LINE__, __func__,
            "Not a control dependence edge!");
    }
}
References __func__, and cEdge_.
dataDependenceEdge()
DataDependenceEdge & ProgramDependenceEdge::dataDependenceEdge ()
Returns reference to data dependence edge of CDG.
Returns
data dependence edge of underlying DDG
Definition at line 179 of file ProgramDependenceEdge.cc.
{
    return *dEdge_;
}
References dEdge_.
Referenced by ProgramDependenceGraph::moveDDGedges().
dotString()
TCEString ProgramDependenceEdge::dotString () const virtual
Returns the edge description as a string in .dot format.
Returns
string describing the edge payload in .dot format
Reimplemented from GraphEdge.
Definition at line 101 of file ProgramDependenceEdge.cc.
{
    if (isArtificialControlDependence()) {
       return TCEString("label=\"") + toString() + "\",color=green";
    }
    if (isLoopCloseEdge()) {
       return TCEString("label=\"") + toString() + "\",color=cyan";
    }
    if (isControlDependence()) {
        if (cEdge_->isTrueEdge()) {
            return TCEString("label=\"") + toString() + "\",color=blue";
        }
        if (cEdge_->isFalseEdge()) {
            return TCEString("label=\"") + toString() + "\",color=red";
        }
        return TCEString("label=\"") + toString() + "\"";
    }
    return TCEString("label=\"") + toString() + "\",style=dashed";
}
References cEdge_, isArtificialControlDependence(), isControlDependence(), ControlDependenceEdge::isFalseEdge(), isLoopCloseEdge(), ControlDependenceEdge::isTrueEdge(), and toString().
fixed()
bool ProgramDependenceEdge::fixed () inline
Definition at line 66 of file ProgramDependenceEdge.hh.
{ return fixed_; }
References fixed_.
isArtificialControlDependence()
bool ProgramDependenceEdge::isArtificialControlDependence () const
Tests if edge is artificial control dependence type. Artificial edges are added during PDG synchronization.
Returns
true if edge is artificial control dependence
Definition at line 147 of file ProgramDependenceEdge.cc.
{
    return type_ == PDG_EDGE_CONTROL_ARTIFICIAL;
}
References PDG_EDGE_CONTROL_ARTIFICIAL, and type_.
Referenced by dotString(), isControlDependence(), and toString().
isControlDependence()
bool ProgramDependenceEdge::isControlDependence () const
Tests if edge is control dependence type.
Returns
true if edge is control dependence
Definition at line 126 of file ProgramDependenceEdge.cc.
{
    if (isArtificialControlDependence()) {
        return true;
    }
    return type_ == PDG_EDGE_CONTROL && cEdge_ != NULL ;
}
References cEdge_, isArtificialControlDependence(), PDG_EDGE_CONTROL, and type_.
Referenced by dotString(), and toString().
isDataDependence()
bool ProgramDependenceEdge::isDataDependence () const
Tests if edge is data dependence type.
Returns
true if edge is data dependence
Definition at line 137 of file ProgramDependenceEdge.cc.
{
    return type_ == PDG_EDGE_DATA && dEdge_ != NULL;
}
References dEdge_, PDG_EDGE_DATA, and type_.
Referenced by toString().
isLoopCloseEdge()
bool ProgramDependenceEdge::isLoopCloseEdge () const
Tests if edge is loop close edge from artificial close node to loop entry node
Returns
true if edge is loop close edge
Definition at line 157 of file ProgramDependenceEdge.cc.
{
    return type_ == PDG_EDGE_LOOP_CLOSE;
}
References PDG_EDGE_LOOP_CLOSE, and type_.
Referenced by dotString(), and toString().
setFixed()
void ProgramDependenceEdge::setFixed () inline
Definition at line 65 of file ProgramDependenceEdge.hh.
{ fixed_ = true; }
References fixed_.
toString()
TCEString ProgramDependenceEdge::toString () const virtual
Returns the edge description as a string.
Returns
string describing the edge payload
Reimplemented from GraphEdge.
Definition at line 81 of file ProgramDependenceEdge.cc.
{
    if (isArtificialControlDependence()) {
        return "PDG_ARTIFICIAL";
    }
    if (isLoopCloseEdge()) {
        return "LoopClose";
    }
    if (isDataDependence()) {
        return dEdge_->toString();
    }
    if (isControlDependence()) {
        return cEdge_->toString();
    }
    return "Error!";
}
References cEdge_, dEdge_, isArtificialControlDependence(), isControlDependence(), isDataDependence(), isLoopCloseEdge(), ControlDependenceEdge::toString(), and DataDependenceEdge::toString().
Referenced by dotString().
Member Data Documentation
cEdge_
ControlDependenceEdge* ProgramDependenceEdge::cEdge_ private
Definition at line 68 of file ProgramDependenceEdge.hh.
Referenced by controlDependenceEdge(), dotString(), isControlDependence(), and toString().
dEdge_
DataDependenceEdge* ProgramDependenceEdge::dEdge_ private
Definition at line 69 of file ProgramDependenceEdge.hh.
Referenced by dataDependenceEdge(), isDataDependence(), and toString().
fixed_
bool ProgramDependenceEdge::fixed_ private
Set to fixed if edge is not to be moved any more while serializing.
Definition at line 72 of file ProgramDependenceEdge.hh.
Referenced by fixed(), and setFixed().
type_
EdgeType ProgramDependenceEdge::type_ private
Definition at line 70 of file ProgramDependenceEdge.hh.
Referenced by isArtificialControlDependence(), isControlDependence(), isDataDependence(), isLoopCloseEdge(), and ProgramDependenceEdge().
The documentation for this class was generated from the following files:
ProgramDependenceEdge.hh
ProgramDependenceEdge.cc