OpenASIP: TPEF::SectionWriter Class Reference
TPEF::SectionWriter Class Reference abstract
#include <SectionWriter.hh>
Static Public Member Functions
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Protected Member Functions
SectionWriter ()
virtual ~SectionWriter ()
virtual const BinaryWriter & parent () const =0
Gets parent of instance which for SectionWriter is created.
virtual Section::SectionType type () const =0
Returns SectionType that actual reader or writer instance can handle.
virtual void finalize (BinaryStream &stream, Section *section) const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const =0
Does actual writing of sections header.
virtual void actualWriteData (BinaryStream &stream, const Section *sect) const =0
Does actual writing of sections data.
Static Protected Member Functions
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Private Types
typedef std::pair< const Section::SectionType, const BinaryWriter * > MapKey
Key type for finding values in map of section writers.
typedef std::map< MapKey, const SectionWriter * > MapType
Map type that contains instances of registered section writers.
Private Member Functions
SectionWriter (const SectionWriter &)
Static Private Member Functions
static const SectionWriter * findSectionWriter (const Section::SectionType type, const BinaryWriter *bWriter)
Static Private Attributes
static MapType * prototypes_ = NULL
Contains section writers for all kinds of sections and all kinds of binrary fromats that are supported.
Detailed Description
Abstract base class for actual section writer classes.
SectionWriter base class stores instances of all registed section writer classes and serve registeration methods for actual SectionWriter instances. Actual section writer classes needs also static instance() method to work correctly.
Definition at line 58 of file SectionWriter.hh.
Member Typedef Documentation
MapKey
typedef std::pair<const Section::SectionType, const BinaryWriter*> TPEF::SectionWriter::MapKey private
Key type for finding values in map of section writers.
Definition at line 104 of file SectionWriter.hh.
MapType
typedef std::map<MapKey, const SectionWriter*> TPEF::SectionWriter::MapType private
Map type that contains instances of registered section writers.
Definition at line 107 of file SectionWriter.hh.
Constructor & Destructor Documentation
SectionWriter() [1/2]
TPEF::SectionWriter::SectionWriter () protected
Constructor
Definition at line 44 of file SectionWriter.cc.
{
}
~SectionWriter()
TPEF::SectionWriter::~SectionWriter () protected virtual
Destructor
Definition at line 50 of file SectionWriter.cc.
{
}
SectionWriter() [2/2]
TPEF::SectionWriter::SectionWriter (const SectionWriter &) private
Member Function Documentation
actualWriteData()
virtual void TPEF::SectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected pure virtual
Does actual writing of sections data.
Implemented in TPEF::TPEFCodeSectionWriter, TPEF::TPEFDataSectionWriter, TPEF::TPEFSectionWriter, TPEF::TPEFStringSectionWriter, TPEF::TPEFASpaceSectionWriter, TPEF::TPEFDebugSectionWriter, TPEF::TPEFLineNumSectionWriter, TPEF::TPEFRelocSectionWriter, TPEF::TPEFResourceSectionWriter, and TPEF::TPEFSymbolSectionWriter.
Referenced by writeData().
actualWriteHeader()
virtual void TPEF::SectionWriter::actualWriteHeader (BinaryStream & stream, const Section * sect) const protected pure virtual
Does actual writing of sections header.
Implemented in TPEF::TPEFSectionWriter.
Referenced by writeHeader().
finalize()
void TPEF::SectionWriter::finalize (BinaryStream & stream, Section * section) const protected virtual
Default finalizer method.
This is used, if section does not have its own method defined.
Parameters
stream Stream that contains binary to finalize.
section Section to finalize.
Definition at line 192 of file SectionWriter.cc.
{
}
Referenced by finalizeBinary().
finalizeBinary()
void TPEF::SectionWriter::finalizeBinary (BinaryStream & stream, const Binary * bin, const BinaryWriter * writer) static
Writes those values to stream, which can't be written before all objects are written down.
This is used for example when some section writer has to update data of other section or sections.
Parameters
stream Stream that contains binary to finalize.
Binary Binary file which needs finalization.
writer Writer, which was used for writing binary.
Definition at line 99 of file SectionWriter.cc.
{
    for (Word i = 0; i < bin->sectionCount(); i++) {
        // get section and finalize it
        Section* sect =bin->section(i);
        try {
            const SectionWriter* sectionWriter =
                findSectionWriter(sect->type(), writer);
            sectionWriter->finalize(stream, sect);
        } catch (const InstanceNotFound &e) {
            // there is not always reader for every created section
            // and it's ok.
        }
    }
}
References finalize(), findSectionWriter(), TPEF::Binary::section(), TPEF::Binary::sectionCount(), and TPEF::Section::type().
Referenced by TPEF::BinaryWriter::writeBinary().
findSectionWriter()
const SectionWriter * TPEF::SectionWriter::findSectionWriter (const Section::SectionType type, const BinaryWriter * bWriter) static private
Finds SectionWriter instance by SectionType and BinaryWriter*.
Parameters
type Type of section to find.
bWriter BinaryWriter which requested finding section.
Returns
Instance which can write section.
Exceptions
InstanceNotFound Writer instance was not found.
Definition at line 129 of file SectionWriter.cc.
{
    MapKey key(type, bWriter);
    if (prototypes_ == NULL ||
        !MapTools::containsKey(*prototypes_, key)) {
        throw InstanceNotFound(__FILE__, __LINE__,
                               "SectionWriter::findSectionWriter");
    }
    return (*prototypes_)[key];
}
References MapTools::containsKey(), prototypes_, and type().
Referenced by finalizeBinary(), writeData(), and writeHeader().
getUniqueSectionId()
SectionId TPEF::SectionWriter::getUniqueSectionId () static protected
Generates a unique section identification code.
If several files are written out, the section identification codes of each file will be starting from a different numeric code. Never returns the reserved identification code for null/invalid section.
Definition at line 172 of file SectionWriter.cc.
{
    // counter used to generate unique identification codes
    static SectionId counter = 0;
    counter++;
    // skip zero (reserved identification code) if the counter wraps around
    if (counter == 0) counter++;
    return counter;
}
Referenced by TPEF::TPEFSectionWriter::getSectionId().
parent()
virtual const BinaryWriter & TPEF::SectionWriter::parent () const protected pure virtual
Gets parent of instance which for SectionWriter is created.
Implemented in TPEF::TPEFSectionWriter.
Referenced by registerSectionWriter().
registerSectionWriter()
void TPEF::SectionWriter::registerSectionWriter (const SectionWriter * sWriter) static protected
Registers SectionWriter instance for writing specific section type.
Parameters
sWriter Instance to register for writing.
Definition at line 148 of file SectionWriter.cc.
{
    MapKey key(sWriter->type(), &sWriter->parent());
    // We can't create prototypes_ map statically, because we don't know
    // if it is initialized before this method is called.
    if (prototypes_ == NULL) {
        prototypes_ = new MapType();
    }
    assert(!MapTools::containsKey(*prototypes_, key));
    (*prototypes_)[key] = sWriter;
}
References assert, MapTools::containsKey(), parent(), prototypes_, and type().
Referenced by TPEF::TPEFASpaceSectionWriter::TPEFASpaceSectionWriter(), TPEF::TPEFCodeSectionWriter::TPEFCodeSectionWriter(), TPEF::TPEFDataSectionWriter::TPEFDataSectionWriter(), TPEF::TPEFDebugSectionWriter::TPEFDebugSectionWriter(), TPEF::TPEFLEDataSectionWriter::TPEFLEDataSectionWriter(), TPEF::TPEFLineNumSectionWriter::TPEFLineNumSectionWriter(), TPEF::TPEFNullSectionWriter::TPEFNullSectionWriter(), TPEF::TPEFRelocSectionWriter::TPEFRelocSectionWriter(), TPEF::TPEFResourceSectionWriter::TPEFResourceSectionWriter(), TPEF::TPEFStringSectionWriter::TPEFStringSectionWriter(), TPEF::TPEFSymbolSectionWriter::TPEFSymbolSectionWriter(), and TPEF::TPEFUDataSectionWriter::TPEFUDataSectionWriter().
type()
virtual Section::SectionType TPEF::SectionWriter::type () const protected pure virtual
Returns SectionType that actual reader or writer instance can handle.
Implemented in TPEF::TPEFASpaceSectionWriter, TPEF::TPEFCodeSectionWriter, TPEF::TPEFDataSectionWriter, TPEF::TPEFDebugSectionWriter, TPEF::TPEFLEDataSectionWriter, TPEF::TPEFLineNumSectionWriter, TPEF::TPEFNullSectionWriter, TPEF::TPEFRelocSectionWriter, TPEF::TPEFResourceSectionWriter, TPEF::TPEFStringSectionWriter, TPEF::TPEFSymbolSectionWriter, TPEF::TPEFUDataSectionWriter, and TPEF::TPEFSectionWriter.
Referenced by findSectionWriter(), and registerSectionWriter().
writeData()
void TPEF::SectionWriter::writeData (BinaryStream & stream, const Section * sect, const BinaryWriter * writer) static
Finds correct SectionWriter instance and command it to write section data.
Parameters
stream Stream where to write.
sect Section which data will be written.
writer BinaryWriter which filetype we want to write.
Exceptions
InstanceNotFound If there wasn't found any writer for section.
Definition at line 79 of file SectionWriter.cc.
{
    findSectionWriter(sect->type(), writer)->actualWriteData(stream, sect);
}
References actualWriteData(), findSectionWriter(), and TPEF::Section::type().
Referenced by TPEF::TPEFWriter::actualWriteBinary().
writeHeader()
void TPEF::SectionWriter::writeHeader (BinaryStream & stream, const Section * sect, const BinaryWriter * writer) static
Finds correct SectionWriter instance and use it to write section header.
Parameters
stream Stream where to write.
sect Section which header will be written.
writer BinaryWriter which filetype we want to write.
Exceptions
InstanceNotFound If there wasn't found any writer for section.
Definition at line 62 of file SectionWriter.cc.
{
    findSectionWriter(sect->type(), writer)->actualWriteHeader(stream, sect);
}
References actualWriteHeader(), findSectionWriter(), and TPEF::Section::type().
Referenced by TPEF::TPEFWriter::actualWriteBinary().
Member Data Documentation
prototypes_
SectionWriter::MapType * TPEF::SectionWriter::prototypes_ = NULL static private
Contains section writers for all kinds of sections and all kinds of binrary fromats that are supported.
Definition at line 116 of file SectionWriter.hh.
Referenced by findSectionWriter(), and registerSectionWriter().
The documentation for this class was generated from the following files:
SectionWriter.hh
SectionWriter.cc