OpenASIP: RuntimeErrorReporter Class Reference
RuntimeErrorReporter Class Reference
Public Member Functions
RuntimeErrorReporter (SimulatorFrontend &target)
virtual ~RuntimeErrorReporter ()
virtual void handleEvent ()
Public Member Functions inherited from Listener
Listener ()
virtual ~Listener ()
virtual void handleEvent (int event)
Private Attributes
SimulatorFrontend & target_
Simulator frontend to use.
Detailed Description
Class that catches simulated program runtime error events and prints the error reports to stderr.
Definition at line 53 of file SimulatorCLI.cc.
Constructor & Destructor Documentation
RuntimeErrorReporter()
RuntimeErrorReporter::RuntimeErrorReporter (SimulatorFrontend & target) inline
Constructor.
Registers itself to the SimulationEventHandler to listen to runtime error events.
Parameters
target The target SimulatorFrontend instance.
Definition at line 63 of file SimulatorCLI.cc.
                                                    :
        Listener(), target_(target) {
        target.eventHandler().registerListener(
            SimulationEventHandler::SE_RUNTIME_ERROR, this);
    }
References SimulatorFrontend::eventHandler(), Informer::registerListener(), and SimulationEventHandler::SE_RUNTIME_ERROR.
~RuntimeErrorReporter()
virtual RuntimeErrorReporter::~RuntimeErrorReporter () inline virtual
Definition at line 69 of file SimulatorCLI.cc.
{
        target_.eventHandler().unregisterListener(
            SimulationEventHandler::SE_RUNTIME_ERROR, this);
    }
References SimulatorFrontend::eventHandler(), SimulationEventHandler::SE_RUNTIME_ERROR, target_, and Informer::unregisterListener().
Member Function Documentation
handleEvent()
virtual void RuntimeErrorReporter::handleEvent () inline virtual
Handles the runtime error event by printing and error report to stderr and stopping simulation in case it's a fatal error.
Reimplemented from Listener.
Definition at line 78 of file SimulatorCLI.cc.
{
        size_t minorErrors = target_.programErrorReportCount(
            SimulatorFrontend::RES_MINOR);
        size_t fatalErrors = target_.programErrorReportCount(
            SimulatorFrontend::RES_FATAL);
        InstructionAddress currentPC = target_.programCounter();
        InstructionAddress lastPC = target_.lastExecutedInstruction();
        ClockCycleCount cycleCount = target_.cycleCount();
        if (minorErrors > 0) {
            for (size_t i = 0; i < minorErrors; ++i) {
                std::cerr << "warning: runtime error: "
                          << target_.programErrorReport(
                              SimulatorFrontend::RES_MINOR, i)
                          << std::endl;
            }
        }
        if (fatalErrors > 0) {
            for (size_t i = 0; i < fatalErrors; ++i) {
                std::cerr << "error: runtime error: "
                          << target_.programErrorReport(
                              SimulatorFrontend::RES_FATAL, i)
                          << std::endl;
            }
            target_.prepareToStop(SRE_RUNTIME_ERROR);
        }
        std::cerr
            << "Current PC: " << currentPC << " last PC: " << lastPC
            << " cycle count: " << cycleCount << std::endl;
        target_.clearProgramErrorReports();
    }
References SimulatorFrontend::clearProgramErrorReports(), SimulatorFrontend::cycleCount(), SimulatorFrontend::lastExecutedInstruction(), SimulatorFrontend::prepareToStop(), SimulatorFrontend::programCounter(), SimulatorFrontend::programErrorReport(), SimulatorFrontend::programErrorReportCount(), SimulatorFrontend::RES_FATAL, SimulatorFrontend::RES_MINOR, SRE_RUNTIME_ERROR, and target_.
Member Data Documentation
target_
SimulatorFrontend& RuntimeErrorReporter::target_ private
Simulator frontend to use.
Definition at line 113 of file SimulatorCLI.cc.
Referenced by handleEvent(), and ~RuntimeErrorReporter().
The documentation for this class was generated from the following file:
SimulatorCLI.cc