OpenASIP: DeleteBPCommand Class Reference
DeleteBPCommand Class Reference
#include <DeleteBPCommand.hh>
Public Member Functions
DeleteBPCommand ()
virtual ~DeleteBPCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "deletebp" command of the Simulator Control Language.
Definition at line 47 of file DeleteBPCommand.hh.
Constructor & Destructor Documentation
DeleteBPCommand()
DeleteBPCommand::DeleteBPCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 51 of file DeleteBPCommand.cc.
                                 :
    SimControlLanguageCommand("deletebp") {
}
~DeleteBPCommand()
DeleteBPCommand::~DeleteBPCommand () virtual
Destructor.
Does nothing.
Definition at line 60 of file DeleteBPCommand.cc.
{
}
Member Function Documentation
execute()
bool DeleteBPCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "deletebp" command.
Deletes the given breakpoints.
Parameters
arguments The handle(s) of the breakpoint(s) to delete.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 74 of file DeleteBPCommand.cc.
{
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    StopPointManager& breakpointManager =
        simulatorFrontend().stopPointManager();
    if (arguments.size() > 1) {
        if (!verifyBreakpointHandles(arguments)) {
            return false;
        }
        // delete the given breakpoints
        for (size_t i = 1; i < arguments.size(); ++i) {
            const unsigned int breakpointHandle = arguments[i].integerValue();
            try {
                breakpointManager.deleteStopPoint(breakpointHandle);
            } catch (const InstanceNotFound&) {
                // user defined the same breakpoint handle twice, let's
                // ignore this
            }
        }
    } else {
        // delete all breakpoints
        if (!interpreter()->lineReader()->confirmation(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_CONFIRM_DELETE_ALL_BREAKPOINTS).str())) {
            // user answered "no", command is still considered succesful
            return true;
        }
        breakpointManager.deleteAll();
    }
    return true;
}
References SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), StopPointManager::deleteAll(), StopPointManager::deleteStopPoint(), CustomCommand::interpreter(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::stopPointManager(), SimulatorToolbox::textGenerator(), Texts::TXT_CONFIRM_DELETE_ALL_BREAKPOINTS, and SimControlLanguageCommand::verifyBreakpointHandles().
helpText()
std::string DeleteBPCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 120 of file DeleteBPCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_DELETEBP).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_DELETEBP.
The documentation for this class was generated from the following files:
DeleteBPCommand.hh
DeleteBPCommand.cc