OpenASIP: InputPSocketBroker Class Reference
InputPSocketBroker Class Reference
#include <InputPSocketBroker.hh>
Public Member Functions
InputPSocketBroker (std::string name, ResourceBroker &fub, unsigned int initiationInterval=0)
virtual ~InputPSocketBroker ()
virtual SchedulingResourceSet allAvailableResources (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const override
virtual void assign (int cycle, MoveNode &node, SchedulingResource &res, int immWriteCycle, int immRegIndex) override
virtual void unassign (MoveNode &node) override
virtual int earliestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const override
virtual int latestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const override
virtual bool isAlreadyAssigned (int cycle, const MoveNode &node, const TTAMachine::Bus *) const override
virtual bool isApplicable (const MoveNode &node, const TTAMachine::Bus *preassignedBus=NULL) const override
virtual void buildResources (const TTAMachine::Machine &target) override
virtual void setupResourceLinks (const ResourceMapper &mapper) override
void setBusBroker (ResourceBroker &sb)
Public Member Functions inherited from ResourceBroker
ResourceBroker (std::string, unsigned int initiationInterval=0)
virtual ~ResourceBroker ()
virtual bool isAnyResourceAvailable (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual SchedulingResource & availableResource (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual bool isAvailable (SchedulingResource &des, const MoveNode &node, int cycle, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
SchedulingResource * resourceOf (const TTAMachine::MachinePart &mp) const
virtual const TTAMachine::MachinePart & machinePartOf (const SchedulingResource &r) const
bool hasResourceOf (const TTAMachine::MachinePart &mp) const
bool hasResource (const SchedulingResource &r) const
int resourceCount () const
virtual bool isBusBroker () const
virtual bool isITemplateBroker () const
virtual bool isIUBroker () const
virtual bool isExecutionPipelineBroker () const
void validateResources () const
virtual std::string brokerName () const
void resources (ResourceSet &contents)
virtual void setInitiationInterval (unsigned int cycles)
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Private Attributes
ResourceBroker & inputFUBroker_
ResourceBroker * busBroker_
Additional Inherited Members
Public Types inherited from ResourceBroker
typedef std::set< SchedulingResource * > ResourceSet
Protected Types inherited from ResourceBroker
typedef std::map< const TTAMachine::MachinePart *, SchedulingResource *, TTAMachine::MachinePart::Comparator > ResourceMap
typedef std::map< const MoveNode *, SchedulingResource *, MoveNode::Comparator > MoveResMap
Protected Member Functions inherited from ResourceBroker
void setResourceMapper (const ResourceMapper &mapper)
const ResourceMapper & resourceMapper () const
unsigned int instructionIndex (unsigned int) const
void addResource (const TTAMachine::MachinePart &mp, SchedulingResource *res)
Protected Attributes inherited from ResourceBroker
unsigned int initiationInterval_
ResourceMap resMap_
const ResourceMapper * resourceMapper_
MoveResMap assignedResources_
std::string brokerName_
Detailed Description
Input p-socket broker takes care of assigning input socket and input port (of FU or RF) at once.
Definition at line 51 of file InputPSocketBroker.hh.
Constructor & Destructor Documentation
InputPSocketBroker()
InputPSocketBroker::InputPSocketBroker (std::string name, ResourceBroker & fub, unsigned int initiationInterval = 0)
Constructor.
Definition at line 57 of file InputPSocketBroker.cc.
                                                                         :
    ResourceBroker(name, initiationInterval),
    inputFUBroker_(fub), busBroker_(NULL) {
}
~InputPSocketBroker()
InputPSocketBroker::~InputPSocketBroker () virtual
Destructor.
Definition at line 66 of file InputPSocketBroker.cc.
{
}
Member Function Documentation
allAvailableResources()
SchedulingResourceSet InputPSocketBroker::allAvailableResources (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const override virtual
Return all resources managed by this broker that can be assigned to the given node in the given cycle.
Parameters
cycle Cycle.
node Node.
Returns
All resources managed by this broker that can be assigned to the given node in the given cycle.
Reimplemented from ResourceBroker.
Definition at line 79 of file InputPSocketBroker.cc.
{
    cycle = instructionIndex(cycle);
    if (!isApplicable(node)) {
        string msg = "Broker not capable of assigning resources to node!";
        throw ModuleRunTimeError(__FILE__, __LINE__, __func__, msg);
    }
    Move& move = const_cast<MoveNode&>(node).move();
    SchedulingResourceSet resourceSet;
    if (move.destination().isFUPort()) {
        // psocket already implicitly assigned by fubroker
        Socket& inputSocket = *move.destination().port().inputSocket();
        SchedulingResource* res = resourceOf(inputSocket);
        if (res->canAssign(cycle, node)) {
            resourceSet.insert(*res);
        }
        return resourceSet;
    } else {
        // assign psocket for writing rf
        // ImmediateUnits can not be writen to this way
        const RegisterFile& rf = move.destination().registerFile();
        for (int i = 0; i < rf.portCount(); i++) {
            Port& port = *rf.port(i);
            Socket* inputSocket = port.inputSocket();
            if (inputSocket != NULL) {
                SchedulingResource* res = resourceOf(*inputSocket);
                if (res->canAssign(cycle, node)) {
                    resourceSet.insert(*res);
                }
            }
        }
        return resourceSet;
    }
}
References __func__, SchedulingResource::canAssign(), TTAProgram::Move::destination(), TTAMachine::Port::inputSocket(), SchedulingResourceSet::insert(), ResourceBroker::instructionIndex(), isApplicable(), TTAProgram::Terminal::isFUPort(), TTAProgram::Terminal::port(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), TTAProgram::Terminal::registerFile(), and ResourceBroker::resourceOf().
assign()
void InputPSocketBroker::assign (int cycle, MoveNode & node, SchedulingResource & res, int immWriteCycle, int immRegIndex) override virtual
Mark given resource as in use for the given node, and assign the corresponding machine part (if applicable) to the node's move.
If the node is already assigned to given resource, this method does nothing.
Parameters
cycle Cycle.
node Node to assign.
res Resource representing input PSocket
Exceptions
WrongSubclass If this broker does not recognise the given type of resource.
InvalidParameters If he given resource cannot be assigned to given node or no corresponding machine part is found.
Todo:
Add caching of assigned resource objects (a MoveNode-Resource mapping).
Implements ResourceBroker.
Definition at line 233 of file InputPSocketBroker.cc.
{
    if (!isApplicable(node)) {
        string msg = "Broker not capable of assigning resources to node!";
        throw ModuleRunTimeError(__FILE__, __LINE__, __func__, msg);
    }
    if (!hasResource(res)) {
        string msg = "Broker does not contain given resource.";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    Move& move = node.move();
    if (move.destination().isGPR()) {
        Port* port = NULL;
        const Socket& socket = static_cast<const Socket&>(machinePartOf(res));
        for (int i = 0; i < socket.portCount(); i++) {
            if (socket.port(i)->inputSocket() == &socket) {
                if (socket.port(i)->parentUnit() !=
                    &move.destination().registerFile())
                    continue;
                port = socket.port(i);
                break;
            }
        }
        if (port == NULL){
            throw InvalidData(
                __FILE__, __LINE__, __func__,
                "Broker does not have necessary Port registered!");
        }
        TerminalRegister* newDst =
            new TerminalRegister(*port, move.destination().index());
        move.setDestination(newDst);
    }
    res.assign(instructionIndex(cycle), node);
    assignedResources_.insert(
        std::pair<const MoveNode*, SchedulingResource*>(&node,&res));
}
References __func__, SchedulingResource::assign(), ResourceBroker::assignedResources_, TTAProgram::Move::destination(), ResourceBroker::hasResource(), TTAProgram::Terminal::index(), TTAMachine::Port::inputSocket(), ResourceBroker::instructionIndex(), isApplicable(), TTAProgram::Terminal::isGPR(), ResourceBroker::machinePartOf(), MoveNode::move(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), TTAProgram::Terminal::registerFile(), and TTAProgram::Move::setDestination().
buildResources()
void InputPSocketBroker::buildResources (const TTAMachine::Machine & target) override virtual
Build all resource objects of the controlled type required to model scheduling resources of the given target processor.
This method cannot set up the resource links (dependent and related resources) of the constructed resource objects.
Parameters
target Target machine.
Implements ResourceBroker.
Definition at line 318 of file InputPSocketBroker.cc.
{
    Machine::SocketNavigator navi = target.socketNavigator();
    for (int i = 0; i < navi.count(); i++) {
        Socket* socket = navi.item(i);
        if (socket->direction() == Socket::INPUT) {
            InputPSocketResource* ipsResource =
                new InputPSocketResource(socket->name(), initiationInterval_);
            ResourceBroker::addResource(*socket, ipsResource);
        }
    }
}
References ResourceBroker::addResource(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Socket::direction(), ResourceBroker::initiationInterval_, TTAMachine::Socket::INPUT, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), and TTAMachine::Machine::socketNavigator().
earliestCycle()
int InputPSocketBroker::earliestCycle (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const override virtual
Return the earliest cycle, starting from given cycle, where a resource of the type managed by this broker can be assigned to the given node.
Parameters
cycle Cycle.
node Node.
Returns
The earliest cycle, starting from given cycle, where a resource of the type managed by this broker can be assigned to the given node.
Implements ResourceBroker.
Definition at line 138 of file InputPSocketBroker.cc.
{
    abortWithError("Not implemented.");
    return -1;
}
References abortWithError.
isAlreadyAssigned()
bool InputPSocketBroker::isAlreadyAssigned (int cycle, const MoveNode & node, const TTAMachine::Bus *) const override virtual
Return true if the given node is already assigned a resource of the type managed by this broker, and the assignment appears valid (that is, the broker has marked that resource as in use in the given cycle).
Parameters
cycle Cycle.
node Node.
Returns
True if the given node is already assigned a resource of the type managed by this broker, and the assignment appears valid (that is, the broker has marked that resource as in use in the given cycle).
Implements ResourceBroker.
Definition at line 183 of file InputPSocketBroker.cc.
{
    cycle = instructionIndex(cycle);
    Terminal& dst = const_cast<MoveNode&>(node).move().destination();
    const Port& port = dst.port();
    if (port.inputSocket() == NULL)
        return false;
    SchedulingResource* res = resourceOf(*port.inputSocket());
    if (res != NULL && res->isInUse(cycle) &&
        MapTools::containsKey(assignedResources_, &node)) {
        return true;
    } else {
        return false;
    }
}
References ResourceBroker::assignedResources_, MapTools::containsKey(), TTAMachine::Port::inputSocket(), ResourceBroker::instructionIndex(), SchedulingResource::isInUse(), TTAProgram::Terminal::port(), and ResourceBroker::resourceOf().
isApplicable()
bool InputPSocketBroker::isApplicable (const MoveNode & node, const TTAMachine::Bus * preassignedBus = NULL) const override virtual
Return true if the given node needs a resource of the type managed by this broker, false otherwise.
This broker is applicable for all moves, but not long immediates.
Parameters
node Node.
Returns
True if the given node needs a resource of the type managed by this broker, false otherwise.
Implements ResourceBroker.
Definition at line 210 of file InputPSocketBroker.cc.
{
    return node.isMove();
}
References MoveNode::isMove().
Referenced by allAvailableResources(), assign(), and unassign().
latestCycle()
int InputPSocketBroker::latestCycle (int cycle, const MoveNode & node, const TTAMachine::Bus * bus, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit * immu, int immRegIndex) const override virtual
Return the latest cycle, starting from given cycle, where a resource of the type managed by this broker can be assigned to the given node.
Parameters
cycle Cycle.
node Node.
Returns
The latest cycle, starting from given cycle, where a resource of the type managed by this broker can be assigned to the given node.
Implements ResourceBroker.
Definition at line 160 of file InputPSocketBroker.cc.
{
    abortWithError("Not implemented.");
    return -1;
}
References abortWithError.
setBusBroker()
void InputPSocketBroker::setBusBroker (ResourceBroker & sb)
Gives reference to segmentbroker to this broker.
Cannot be given in constructor because SegmentBroker is created later.
Definition at line 391 of file InputPSocketBroker.cc.
{
    busBroker_ = &sb;
}
References busBroker_.
Referenced by SimpleResourceManager::buildResourceModel().
setupResourceLinks()
void InputPSocketBroker::setupResourceLinks (const ResourceMapper & mapper) override virtual
Complete resource initialisation by creating the references to other resources due to a dependency or a relation.
Use the given resource mapper to lookup dependent and related resources using machine parts as keys.
Parameters
mapper Resource mapper.
Implements ResourceBroker.
Definition at line 340 of file InputPSocketBroker.cc.
{
    setResourceMapper(mapper);
    for (ResourceMap::iterator resIter = resMap_.begin();
         resIter != resMap_.end(); resIter++) {
        const Socket* socket =
            dynamic_cast<const Socket*>((*resIter).first);
        if (socket == NULL){
            throw InvalidData(
                __FILE__, __LINE__, __func__,
                "Broker does not have necessary Socket registered!");
        }
        SchedulingResource* socketResource = (*resIter).second;
        for (int i = 0; i < socket->portCount(); i++) {
            Port* port = socket->port(i);
            FunctionUnit* fu = dynamic_cast<FunctionUnit*>(port->parentUnit());
            if (fu != NULL) {
                SchedulingResource& relRes =
                    *inputFUBroker_.resourceOf(*fu);
                socketResource->addToRelatedGroup(0, relRes);
            }
        }
        for (int i = 0; i < socket->segmentCount(); i++) {
            Segment* segment = socket->segment(i);
            Bus* bus = segment->parentBus();
            try {
                SchedulingResource& relRes =
                    *busBroker_->resourceOf(*bus);
                socketResource->addToRelatedGroup(1, relRes);
            } catch (const KeyNotFound& e) {
                std::string msg = "InputPSocketBroker: finding ";
                msg += " resource for Segment ";
                msg += " failed with error: ";
                msg += e.errorMessageStack();
                throw KeyNotFound(
                    __FILE__, __LINE__, __func__, msg);
            }
        }
    }
}
References __func__, SchedulingResource::addToRelatedGroup(), busBroker_, Exception::errorMessageStack(), inputFUBroker_, TTAMachine::Segment::parentBus(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), ResourceBroker::resMap_, ResourceBroker::resourceOf(), TTAMachine::Socket::segment(), TTAMachine::Socket::segmentCount(), and ResourceBroker::setResourceMapper().
unassign()
void InputPSocketBroker::unassign (MoveNode & node) override virtual
Free the resource type managed by this broker and unassign it from given node.
If this broker is not applicable to the given node, or the node is not assigned a resource of the managed type, this method does nothing.
Parameters
node Node.
Todo:
Remove from cache of assigned resource objects.
Implements ResourceBroker.
Definition at line 288 of file InputPSocketBroker.cc.
{
    if (!isApplicable(node)) {
        return;
    }
    if (MapTools::containsKey(assignedResources_, &node)) {
        Move& move = const_cast<MoveNode&>(node).move();
        Terminal& dst = move.destination();
        SchedulingResource& res = *resourceOf(*dst.port().inputSocket());
        if ((MapTools::valueForKey<SchedulingResource*>(
            assignedResources_, &node)) != &res) {
            std::string msg =
                "InputPSocketBroker: assigned resource changed!";
            throw ModuleRunTimeError(__FILE__,__LINE__, __func__, msg);
        }
        res.unassign(node.cycle(), node);
        assignedResources_.erase(&node);
    }
}
References __func__, ResourceBroker::assignedResources_, MapTools::containsKey(), MoveNode::cycle(), TTAProgram::Move::destination(), TTAMachine::Port::inputSocket(), isApplicable(), MapTools::keyForValue(), TTAProgram::Terminal::port(), ResourceBroker::resourceOf(), and SchedulingResource::unassign().
Member Data Documentation
busBroker_
ResourceBroker* InputPSocketBroker::busBroker_ private
Definition at line 98 of file InputPSocketBroker.hh.
Referenced by setBusBroker(), and setupResourceLinks().
inputFUBroker_
ResourceBroker& InputPSocketBroker::inputFUBroker_ private
Definition at line 97 of file InputPSocketBroker.hh.
Referenced by setupResourceLinks().
The documentation for this class was generated from the following files:
InputPSocketBroker.hh
InputPSocketBroker.cc