OpenASIP: MemoryValueDialog Class Reference
MemoryValueDialog Class Reference
#include <MemoryValueDialog.hh>
Public Member Functions
MemoryValueDialog (wxWindow *parent, unsigned maxBits=64)
virtual ~MemoryValueDialog ()
void setValue (int value)
long mode ()
int intValue ()
double doubleValue ()
Private Types
enum { ID_VALUE = 10000 }
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
NumberControl * value_
NumberControl for giving new values to memory.
unsigned maxBits_
Maximum number of bits used by the returned value.
Detailed Description
Class for giving new values to memory addresses.
Definition at line 44 of file MemoryValueDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_VALUE
Definition at line 62 of file MemoryValueDialog.hh.
         {
        ID_VALUE = 10000
    };
Constructor & Destructor Documentation
MemoryValueDialog()
MemoryValueDialog::MemoryValueDialog (wxWindow * parent, unsigned maxBits = 64)
Constructor.
Parameters
parent Parent window.
pos Position of the dialog.
Definition at line 51 of file MemoryValueDialog.cc.
                                                                       :
    wxDialog(parent, -1, _T("Memory value"), wxDefaultPosition,
             wxDefaultSize),
    maxBits_(maxBits) {
    createContents(this, true, true);
    value_ = dynamic_cast<NumberControl*>(FindWindow(ID_VALUE));
}
~MemoryValueDialog()
MemoryValueDialog::~MemoryValueDialog () virtual
Destructor.
Definition at line 63 of file MemoryValueDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * MemoryValueDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
Parameters
parent The parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 137 of file MemoryValueDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxWindow *item1 = new NumberControl(
        parent, ID_VALUE, wxDefaultPosition,
        wxSize(240, -1), NumberControl::MODE_BINARY |
        NumberControl::MODE_UNSIGNED | NumberControl::MODE_HEXADECIMAL |
        NumberControl::MODE_FLOAT);
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item3 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_VALUE, NumberControl::MODE_BINARY, NumberControl::MODE_FLOAT, NumberControl::MODE_HEXADECIMAL, and NumberControl::MODE_UNSIGNED.
doubleValue()
double MemoryValueDialog::doubleValue ()
Returns the value user typed.
Returns
User given value as double.
Definition at line 102 of file MemoryValueDialog.cc.
{
    return value_->doubleValue();
}
References NumberControl::doubleValue(), and value_.
Referenced by MemoryControl::onWriteMemory().
intValue()
int MemoryValueDialog::intValue ()
Returns the value user typed.
Returns
User given value.
Definition at line 92 of file MemoryValueDialog.cc.
{
    return value_->intValue();
}
References NumberControl::intValue(), and value_.
Referenced by onOK(), and MemoryControl::onWriteMemory().
mode()
long MemoryValueDialog::mode ()
Returns the mode of the number control.
Returns
The mode.
Definition at line 72 of file MemoryValueDialog.cc.
{
    return value_->mode();
}
References NumberControl::mode(), and value_.
Referenced by MemoryControl::onWriteMemory().
onOK()
void MemoryValueDialog::onOK (wxCommandEvent & event) private
Event handler for the OK button.
Checks that the value doesn't use more than maximum number of bits allowed.
Definition at line 112 of file MemoryValueDialog.cc.
{
    std::string binary = Conversion::toBinary(intValue());
    if (binary.length() > maxBits_) {
        wxString message = _T("Bit width of the value exceeds the maximum");
        message.Append(_T(" bit width of "));
        message.Append(WxConversion::toWxString(maxBits_));
        message.Append(_T("."));
        InformationDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    EndModal(wxID_OK);
}
References intValue(), maxBits_, Conversion::toBinary(), and WxConversion::toWxString().
setValue()
void MemoryValueDialog::setValue (int value)
Sets the value.
Parameters
value Value to be set.
Definition at line 82 of file MemoryValueDialog.cc.
{
    value_->setValue(value);
}
References NumberControl::setValue(), and value_.
Referenced by MemoryControl::onWriteMemory().
Member Data Documentation
maxBits_
unsigned MemoryValueDialog::maxBits_ private
Maximum number of bits used by the returned value.
Definition at line 69 of file MemoryValueDialog.hh.
Referenced by onOK().
value_
NumberControl* MemoryValueDialog::value_ private
NumberControl for giving new values to memory.
Definition at line 67 of file MemoryValueDialog.hh.
Referenced by doubleValue(), intValue(), mode(), and setValue().
The documentation for this class was generated from the following files:
MemoryValueDialog.hh
MemoryValueDialog.cc