OpenASIP: ProximPortEditPolicy Class Reference
ProximPortEditPolicy Class Reference
#include <ProximPortEditPolicy.hh>
Public Member Functions
ProximPortEditPolicy ()
virtual ~ProximPortEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Edit policy for Proxim machine state window ports.
Definition at line 41 of file ProximPortEditPolicy.hh.
Constructor & Destructor Documentation
ProximPortEditPolicy()
ProximPortEditPolicy::ProximPortEditPolicy ()
The Constructor.
Definition at line 46 of file ProximPortEditPolicy.cc.
                                           :
    EditPolicy() {
}
~ProximPortEditPolicy()
ProximPortEditPolicy::~ProximPortEditPolicy () virtual
The Destructor.
Definition at line 54 of file ProximPortEditPolicy.cc.
{
}
Member Function Documentation
canHandle()
bool ProximPortEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy can handle request of the given type.
Parameters
Request to be handled.
Returns
True, if the editpolicy can handle give request type.
Implements EditPolicy.
Definition at line 64 of file ProximPortEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::STATUS_REQUEST) {
        return true;
    } else if (type == Request::DETAILS_REQUEST) {
        // Details only available for function unit ports.
        const FUPort* fuPort =
            dynamic_cast<const FUPort*>(host_->model());
        if (fuPort != NULL) {
            return true;
        }
    }
    return false;
}
References Request::DETAILS_REQUEST, EditPolicy::host_, EditPart::model(), Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProximPortEditPolicy::getCommand (Request * request) virtual
Returns command correspoding to the request type.
Parameters
request Request to handle.
Returns
NULL, if the request can't be handled.
Implements EditPolicy.
Definition at line 90 of file ProximPortEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::STATUS_REQUEST) {
        const Port* port = dynamic_cast<Port*>(host_->model());
        assert(port != NULL);
        std::string name = port->name();
        return new ProximComponentStatusCmd("Port: " + name);
    } else if (type == Request::DETAILS_REQUEST) {
        const FUPort* fuPort =
            dynamic_cast<const FUPort*>(host_->model());
        if (fuPort == NULL) {
            return NULL;
        } else {
            return new ProximFUPortDetailsCmd(*fuPort);
        }
    }
    return NULL;
}
References assert, Request::DETAILS_REQUEST, EditPolicy::host_, EditPart::model(), TTAMachine::Port::name(), Request::STATUS_REQUEST, and Request::type().
The documentation for this class was generated from the following files:
ProximPortEditPolicy.hh
ProximPortEditPolicy.cc