OpenASIP: ProjectFileGenerator Class Reference
ProjectFileGenerator Class Reference abstract
#include <ProjectFileGenerator.hh>
Public Member Functions
ProjectFileGenerator (TCEString coreEntity, const PlatformIntegrator *integrator)
virtual ~ProjectFileGenerator ()
virtual void writeProjectFiles ()=0
void addHdlFile (const TCEString &file)
void addHdlFiles (const std::vector< TCEString > &files)
void addMemInitFile (const TCEString &memInit)
void addSignalMapping (const PlatInt::SignalMapping &mapping)
Protected Member Functions
const std::vector< TCEString > & hdlFileList () const
const std::vector< TCEString > & memInitFileList () const
const PlatformIntegrator * integrator () const
TCEString coreEntity () const
TCEString toplevelEntity () const
int signalMappingCount () const
const PlatInt::SignalMapping * signalMapping (int index) const
TCEString extractFUName (const TCEString &port, const TCEString &delimiter) const
Private Attributes
TCEString coreEntity_
the HDL entity of the non-integrated TTA core
const PlatformIntegrator * integrator_
std::vector< TCEString > hdlFiles_
std::vector< TCEString > memInitFiles_
PlatInt::SignalMappingList signalMap_
Detailed Description
Definition at line 41 of file ProjectFileGenerator.hh.
Constructor & Destructor Documentation
ProjectFileGenerator()
ProjectFileGenerator::ProjectFileGenerator (TCEString coreEntity, const PlatformIntegrator * integrator)
Definition at line 40 of file ProjectFileGenerator.cc.
                                         :
    coreEntity_(coreEntity), integrator_(integrator) {
}
~ProjectFileGenerator()
ProjectFileGenerator::~ProjectFileGenerator () virtual
Definition at line 47 of file ProjectFileGenerator.cc.
{
    for (unsigned int i = 0; i < signalMap_.size(); i++) {
        delete signalMap_.at(i);
    }
}
References signalMap_.
Member Function Documentation
addHdlFile()
void ProjectFileGenerator::addHdlFile (const TCEString & file)
Definition at line 56 of file ProjectFileGenerator.cc.
{
    hdlFiles_.push_back(file);
}
References hdlFiles_.
Referenced by AlmaIFIntegrator::addAlmaifFiles(), PlatformIntegrator::addProGeFiles(), and PlatformIntegrator::writeNewToplevel().
addHdlFiles()
void ProjectFileGenerator::addHdlFiles (const std::vector< TCEString > & files)
Definition at line 63 of file ProjectFileGenerator.cc.
{
    for (unsigned int i = 0; i < files.size(); i++) {
        hdlFiles_.push_back(files.at(i));
    }
}
References hdlFiles_.
Referenced by PlatformIntegrator::createMemories().
addMemInitFile()
void ProjectFileGenerator::addMemInitFile (const TCEString & memInit)
Definition at line 72 of file ProjectFileGenerator.cc.
{
    memInitFiles_.push_back(memInit);
}
References memInitFiles_.
Referenced by AlteraIntegrator::dmemInstance(), KoskiIntegrator::dmemInstance(), and AlteraIntegrator::imemInstance().
addSignalMapping()
void ProjectFileGenerator::addSignalMapping (const PlatInt::SignalMapping & mapping)
Definition at line 79 of file ProjectFileGenerator.cc.
{
    SignalMapping* signalMap = new SignalMapping(mapping);
    signalMap_.push_back(signalMap);
}
References signalMap_.
Referenced by Stratix2DSPBoardIntegrator::addSignalMapping(), and Stratix3DevKitIntegrator::addSignalMapping().
coreEntity()
TCEString ProjectFileGenerator::coreEntity () const inline protected
Definition at line 65 of file ProjectFileGenerator.hh.
{ return coreEntity_; }
References coreEntity_.
extractFUName()
TCEString ProjectFileGenerator::extractFUName (const TCEString & port, const TCEString & delimiter) const protected
Definition at line 120 of file ProjectFileGenerator.cc.
{
    TCEString::size_type pos = port.find(delimiter);
    if (pos == TCEString::npos || pos == 0) {
        return port;
    }
    TCEString fuName = port.substr(0, pos);
    return StringTools::trim(fuName);
}
References StringTools::trim().
Referenced by SOPCBuilderFileGenerator::handleAvalonSignal().
hdlFileList()
const std::vector< TCEString > & ProjectFileGenerator::hdlFileList () const protected
Definition at line 87 of file ProjectFileGenerator.cc.
{
    return hdlFiles_;
}
References hdlFiles_.
Referenced by SOPCBuilderFileGenerator::writeFileList(), IPXactFileGenerator::writeProjectFiles(), and QuartusProjectGenerator::writeQSFFile().
integrator()
const PlatformIntegrator * ProjectFileGenerator::integrator () const protected
Definition at line 101 of file ProjectFileGenerator.cc.
{
    return integrator_;
}
References integrator_.
Referenced by IPXactFileGenerator::addAddressSpaces(), IPXactFileGenerator::addBusInterfaces(), SOPCBuilderFileGenerator::countAvalonMMMasters(), SOPCBuilderFileGenerator::createInterfaces(), SOPCBuilderFileGenerator::writeGenerics(), SOPCBuilderFileGenerator::writeModuleProperties(), IPXactFileGenerator::writeProjectFiles(), and QuartusProjectGenerator::writeQSFFile().
memInitFileList()
const std::vector< TCEString > & ProjectFileGenerator::memInitFileList () const protected
Definition at line 94 of file ProjectFileGenerator.cc.
{
    return memInitFiles_;
}
References memInitFiles_.
Referenced by SOPCBuilderFileGenerator::writeFileList(), IPXactFileGenerator::writeProjectFiles(), and QuartusProjectGenerator::writeQSFFile().
signalMapping()
const SignalMapping * ProjectFileGenerator::signalMapping (int index) const protected
Definition at line 113 of file ProjectFileGenerator.cc.
{
    return signalMap_.at(index);
}
References signalMap_.
Referenced by QuartusProjectGenerator::writeQSFFile().
signalMappingCount()
int ProjectFileGenerator::signalMappingCount () const protected
Definition at line 106 of file ProjectFileGenerator.cc.
{
    return signalMap_.size();
}
References signalMap_.
Referenced by QuartusProjectGenerator::writeQSFFile().
toplevelEntity()
TCEString ProjectFileGenerator::toplevelEntity () const inline protected
Definition at line 66 of file ProjectFileGenerator.hh.
{
        return coreEntity_ + "_toplevel";
    }
References coreEntity_.
Referenced by IPXactFileGenerator::outputFileName(), SOPCBuilderFileGenerator::writeModuleProperties(), IPXactFileGenerator::writeProjectFiles(), SOPCBuilderFileGenerator::writeProjectFiles(), QuartusProjectGenerator::writeQPFFile(), QuartusProjectGenerator::writeQSFFile(), and QuartusProjectGenerator::writeScripts().
writeProjectFiles()
virtual void ProjectFileGenerator::writeProjectFiles () pure virtual
Implemented in DefaultProjectFileGenerator, IPXactFileGenerator, QuartusProjectGenerator, and SOPCBuilderFileGenerator.
Referenced by AlmaIFIntegrator::integrateProcessor(), AlteraIntegrator::integrateProcessor(), Stratix2DSPBoardIntegrator::integrateProcessor(), and Stratix3DevKitIntegrator::integrateProcessor().
Member Data Documentation
coreEntity_
TCEString ProjectFileGenerator::coreEntity_ private
the HDL entity of the non-integrated TTA core
Definition at line 80 of file ProjectFileGenerator.hh.
Referenced by coreEntity(), and toplevelEntity().
hdlFiles_
std::vector<TCEString> ProjectFileGenerator::hdlFiles_ private
Definition at line 83 of file ProjectFileGenerator.hh.
Referenced by addHdlFile(), addHdlFiles(), and hdlFileList().
integrator_
const PlatformIntegrator* ProjectFileGenerator::integrator_ private
Definition at line 81 of file ProjectFileGenerator.hh.
Referenced by integrator().
memInitFiles_
std::vector<TCEString> ProjectFileGenerator::memInitFiles_ private
Definition at line 84 of file ProjectFileGenerator.hh.
Referenced by addMemInitFile(), and memInitFileList().
signalMap_
PlatInt::SignalMappingList ProjectFileGenerator::signalMap_ private
Definition at line 85 of file ProjectFileGenerator.hh.
Referenced by addSignalMapping(), signalMapping(), signalMappingCount(), and ~ProjectFileGenerator().
The documentation for this class was generated from the following files:
ProjectFileGenerator.hh
ProjectFileGenerator.cc