OpenASIP: TTAMachine::Unit Class Reference
TTAMachine::Unit Class Reference
#include <Unit.hh>
Public Member Functions
virtual ~Unit ()
virtual bool hasPort (const std::string &name) const
virtual Port * port (const std::string &name) const
virtual Port * port (int index) const
virtual int portCount () const
virtual int outputPortCount (bool countBidir=false) const
virtual int inputPortCount (bool countBidir=false) const
virtual int bidirPortCount () const
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual void setName (const std::string &name)
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_UNIT = "unit"
ObjectState name for Unit.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Protected Member Functions
Unit (const std::string &name)
Unit (const ObjectState *state)
virtual void removePort (Port &port)
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Types
typedef std::vector< Port * > PortTable
Container for ports.
typedef std::set< std::string > NameSet
Set type for strings.
Private Member Functions
Unit (const Unit &)
Copying forbidden.
Unit & operator= (const Unit &)
Assingment forbidden.
void addPort (Port &port)
void deleteAllPorts ()
void deleteOtherPorts (const NameSet &portsToLeave)
void loadStateWithoutReferences (const ObjectState *state)
Static Private Member Functions
static NameSet portNames (const ObjectState *state)
Private Attributes
PortTable ports_
Contains all the ports of the unit.
Friends
class Port
Detailed Description
An Abstract base class for the different units in the machine.
Definition at line 51 of file Unit.hh.
Member Typedef Documentation
NameSet
typedef std::set<std::string> TTAMachine::Unit::NameSet private
Set type for strings.
Definition at line 82 of file Unit.hh.
PortTable
typedef std::vector<Port*> TTAMachine::Unit::PortTable private
Container for ports.
Definition at line 80 of file Unit.hh.
Constructor & Destructor Documentation
~Unit()
TTAMachine::Unit::~Unit () virtual
Destructor.
Definition at line 84 of file Unit.cc.
            {
    deleteAllPorts();
}
References deleteAllPorts().
Unit() [1/3]
TTAMachine::Unit::Unit (const std::string & name) protected
Constructor.
Parameters
name The name of the unit.
Exceptions
InvalidName If the given name is not a valid component name.
Definition at line 59 of file Unit.cc.
: Component(name) {}
Unit() [2/3]
TTAMachine::Unit::Unit (const ObjectState * state) protected
Constructor.
Loads the state of the unit from the given ObjectState instance. Does not load connections to other components.
Parameters
state The ObjectState instance from which the name is taken.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 71 of file Unit.cc.
                                   : Component(state) {
    try {
        loadStateWithoutReferences(state);
    } catch (const Exception&) {
        // delete the ports that were loaded
        deleteAllPorts();
        throw;
    }
}
References deleteAllPorts(), and loadStateWithoutReferences().
Unit() [3/3]
TTAMachine::Unit::Unit (const Unit &) private
Copying forbidden.
Member Function Documentation
addPort()
void TTAMachine::Unit::addPort (Port & port) private
Adds a port to the unit.
This method can be called from Port constructor only.
Parameters
port Port to be added.
Exceptions
ComponentAlreadyExists If another port with the same name exists.
Definition at line 213 of file Unit.cc.
{
    // check that this method is called from Port constructor only
    assert(port.parentUnit() == NULL);
    // check that a port with same name does not exist
    if (!hasPort(port.name())) {
        ports_.push_back(&port);
        return;
    }
    string procName = "Unit::addPort";
    throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
}
References assert, hasPort(), TTAMachine::Port::name(), TTAMachine::Port::parentUnit(), port(), and ports_.
Referenced by TTAMachine::Port::Port(), and TTAMachine::Port::Port().
bidirPortCount()
int TTAMachine::Unit::bidirPortCount () const virtual
Returns
The number of bidirectional ports in the unit.
Definition at line 174 of file Unit.cc.
{
    unsigned count = 0;
    for (auto &port : ports_) {
        if (port->isInput() && port->isOutput())
            count++;
    }
    return count;
}
References TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), port(), and ports_.
Referenced by ProGeTools::checkForSelectableRF(), and Automagic::checkForSelectableRF().
deleteAllPorts()
void TTAMachine::Unit::deleteAllPorts () private
Deletes all the ports from the unit.
Definition at line 373 of file Unit.cc.
                     {
    while (ports_.size() > 0) {
        // the size of the vector is decreased when the code of Port
        // destructor is executed
        delete ports_[0];
    }
}
References ports_.
Referenced by Unit(), and ~Unit().
deleteOtherPorts()
void TTAMachine::Unit::deleteOtherPorts (const NameSet & portsToLeave) private
Deletes all the ports which has a name that does not appear in the given name set.
Parameters
portsToLeave A set of names of ports to leave.
Definition at line 389 of file Unit.cc.
{
    for (int i = 0; i < portCount();) {
        Port* port = this->port(i);
        if (!AssocTools::containsKey(portsToLeave, port->name())) {
            delete port;
        } else {
            i++;
        }
    }
}
References AssocTools::containsKey(), TTAMachine::Port::name(), port(), and portCount().
Referenced by loadStateWithoutReferences().
hasPort()
bool TTAMachine::Unit::hasPort (const std::string & name) const virtual
Returns true if the requested port is found, otherwise false.
Parameters
name Name of the port.
Returns
Tru if the port is found, otherwise false.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 96 of file Unit.cc.
{
    PortTable::const_iterator iter = ports_.begin();
    while (iter != ports_.end()) {
        if ((*iter)->name() == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References TTAMachine::Component::name(), and ports_.
Referenced by addPort(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findPort(), MachineResourceManager::functionUnitPortResource(), TTAMachine::FunctionUnit::hasOperationPort(), TTAMachine::ControlUnit::hasSpecialRegisterPort(), TTAProgram::TPEFResourceUpdater::initCache(), loadStateWithoutReferences(), GCUDialog::onAddFUPort(), FUDialog::onAddPort(), IUDialog::onAddPort(), RFDialog::onAddPort(), GCUDialog::onAddSRPort(), TTAMachine::FunctionUnit::port(), and TTAMachine::ControlUnit::specialRegisterPort().
inputPortCount()
int TTAMachine::Unit::inputPortCount (bool countBidir = false) const virtual
Parameters
countBidir True if we should count bidirectional ports
Returns
The number of input ports in the unit.
Definition at line 160 of file Unit.cc.
{
    unsigned count = 0;
    for (auto &port : ports_) {
        if (port->isInput() && (!port->isOutput() || countBidir))
            count++;
    }
    return count;
}
References TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), port(), and ports_.
Referenced by ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), and ProGe::RV32MicroCodeGenerator::findRF().
loadState()
void TTAMachine::Unit::loadState (const ObjectState * state) virtual
Loads the state of the unit from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid or if references to sockets cannot be made.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::BaseRegisterFile, TTAMachine::ControlUnit, TTAMachine::FunctionUnit, TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, TTAMachine::RegisterFile, UnboundedRegisterFile, and UniversalFunctionUnit.
Definition at line 309 of file Unit.cc.
{
    loadStateWithoutReferences(state);
    // create port-socket connections
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == FUPort::OSNAME_FUPORT ||
            child->name() == RFPort::OSNAME_RFPORT ||
            child->name() == SpecialRegisterPort::OSNAME_SPECIAL_REG_PORT) {
            string portName = child->stringAttribute(Port::OSKEY_NAME);
            Port* port = this->port(portName);
            port->loadState(child);
        }
    }
}
References ObjectState::child(), ObjectState::childCount(), TTAMachine::Port::loadState(), loadStateWithoutReferences(), ObjectState::name(), TTAMachine::Port::OSKEY_NAME, TTAMachine::FUPort::OSNAME_FUPORT, TTAMachine::RFPort::OSNAME_RFPORT, TTAMachine::SpecialRegisterPort::OSNAME_SPECIAL_REG_PORT, port(), and ObjectState::stringAttribute().
Referenced by TTAMachine::BaseRegisterFile::loadState(), and TTAMachine::FunctionUnit::loadState().
loadStateWithoutReferences()
void TTAMachine::Unit::loadStateWithoutReferences (const ObjectState * state) private
Loads its state from the given ObjectState instance without references to other components.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 334 of file Unit.cc.
{
    const string procName = "Unit::loadStateWithoutReferences";
    // load ports
    try {
        // cannot delete all the ports because there might be guards
        // referencing to them
        NameSet newPortNames = portNames(state);
        deleteOtherPorts(newPortNames);
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            string portName = child->stringAttribute(Port::OSKEY_NAME);
            if (!hasPort(portName)) {
                if (child->name() == RFPort::OSNAME_RFPORT) {
                    // port is attached automatically
                    new RFPort(child, *this);
                } else if (child->name() == FUPort::OSNAME_FUPORT) {
                    // port is attached automatically
                    new FUPort(child, *this);
                } else if (child->name() ==
                           SpecialRegisterPort::OSNAME_SPECIAL_REG_PORT) {
                    // port is attached automatically
                    new SpecialRegisterPort(child, *this);
                }
            }
        }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References ObjectState::child(), ObjectState::childCount(), deleteOtherPorts(), Exception::errorMessage(), hasPort(), ObjectState::name(), TTAMachine::Port::OSKEY_NAME, TTAMachine::FUPort::OSNAME_FUPORT, TTAMachine::RFPort::OSNAME_RFPORT, TTAMachine::SpecialRegisterPort::OSNAME_SPECIAL_REG_PORT, portNames(), and ObjectState::stringAttribute().
Referenced by loadState(), and Unit().
operator=()
Unit & TTAMachine::Unit::operator= (const Unit &) private
Assingment forbidden.
outputPortCount()
int TTAMachine::Unit::outputPortCount (bool countBidir = false) const virtual
Parameters
countBidir True if we should count bidirectional ports
Returns
The number of output ports in the unit.
Definition at line 145 of file Unit.cc.
{
    unsigned count = 0;
    for (auto &port : ports_) {
        if (port->isOutput() && (!port->isInput() || countBidir))
            count++;
    }
    return count;
}
References TTAMachine::Port::isInput(), TTAMachine::Port::isOutput(), port(), and ports_.
Referenced by ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), ProGe::RV32MicroCodeGenerator::findRF(), and DefaultDecoderGenerator::verifyCompatibility().
port() [1/2]
Port * TTAMachine::Unit::port (const std::string & name) const virtual
Returns the requested port.
Parameters
name Name of the port.
Returns
The requested port.
Exceptions
InstanceNotFound If a port is not found by the given name.
Reimplemented in TTAMachine::BaseRegisterFile, and TTAMachine::FunctionUnit.
Definition at line 116 of file Unit.cc.
{
    PortTable::const_iterator iter = ports_.begin();
    while (iter != ports_.end()) {
        if ((*iter)->name() == name) {
            return *iter;
        }
        iter++;
    }
    string procName = "Unit::port";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
}
References TTAMachine::Component::name(), and ports_.
Referenced by addPort(), MachineConnectivityCheck::appendConnectedDestinationBuses(), MachineConnectivityCheck::appendConnectedSourceBuses(), bidirPortCount(), MachineConnectivityCheck::busConnectedToRF(), ADFCombiner::connectPorts(), deleteOtherPorts(), MachineConnectivityCheck::findReadPorts(), MachineConnectivityCheck::findWritePorts(), inputPortCount(), loadState(), IUPortDialog::onOK(), RFPortDialog::onOK(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), outputPortCount(), TTAMachine::BaseRegisterFile::port(), TTAMachine::FunctionUnit::port(), TTAMachine::BaseRegisterFile::port(), TTAMachine::FunctionUnit::port(), removePort(), saveState(), TTAMachine::Port::setName(), and unsetMachine().
port() [2/2]
Port * TTAMachine::Unit::port (int index) const virtual
Returns a port by the given index.
The index must be greater or equal to 0 and smaller than the number of ports in the unit.
Parameters
index Index.
Returns
The port by the given index.
Exceptions
OutOfRange If the given index is out of range.
Reimplemented in TTAMachine::BaseRegisterFile, and TTAMachine::FunctionUnit.
Definition at line 195 of file Unit.cc.
{
    if (index < 0 || index >= portCount()) {
        string procName = "Unit::port";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return ports_[index];
}
References portCount(), and ports_.
portCount()
int TTAMachine::Unit::portCount () const virtual
Returns the number of ports in the unit.
Returns
The number of ports in the unit.
Reimplemented in TTAMachine::NullRegisterFile.
Definition at line 135 of file Unit.cc.
                      {
    return ports_.size();
}
References ports_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), DefaultDecoderGenerator::addGlockPortToDecoder(), DefaultDecoderGenerator::addLockReqPortToDecoder(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), InputPSocketBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), MachineConnectivityCheck::appendConnectedDestinationBuses(), MachineConnectivityCheck::appendConnectedSourceBuses(), CostDatabase::buildFunctionUnits(), MachineStateBuilder::buildMachineState(), MachineConnectivityCheck::busConnectedToRF(), MachineTester::canConnect(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), RFPortCheck::check(), SimulatorFrontend::compareState(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::connectPorts(), ProGe::RV32MicroCodeGenerator::connectRF(), ADFCombiner::copyGuards(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), FUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), FUGen::createMandatoryPorts(), FUGen::createOutputPipeline(), FUGen::createPortPipeline(), ADFCombiner::createPortsAndSockets(), FUGen::createShadowRegisters(), llvm::LLVMTCEBuilder::createTerminalRegister(), TTAProgram::CodeGenerator::createTerminalRegister(), deleteOtherPorts(), ProximFUDetailsCmd::Do(), AddFUImplementationCmd::Do(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEBuilder::emitSPInitialization(), UniversalFunctionUnit::ensureInputPorts(), InfoPortsCommand::execute(), ProgrammabilityValidator::findConnections(), MachineConnectivityCheck::findPossibleSourcePorts(), MachineConnectivityCheck::findReadPorts(), BasicBlockScheduler::findTriggerFromUnit(), ProgramOperation::findTriggerFromUnit(), MachineConnectivityCheck::findWritePorts(), TTAMachine::RegisterFile::firstReadPort(), TTAMachine::RegisterFile::firstWritePort(), FullyConnectedCheck::fix(), MachineConnectivityCheck::fromRfConnected(), HDBToHtml::fuArchToHtml(), CompiledSimCodeGenerator::fuOutputPorts(), TTAMachine::FUPort::FUPort(), DefaultDecoderGenerator::glockPortWidth(), DefaultDecoderGenerator::glockRequestWidth(), MachineConnectivityCheck::immBits(), OutputPSocketBroker::isAnyResourceAvailable(), TTAMachine::RegisterFile::isArchitectureEqual(), ExecutionPipelineResource::isAvailable(), MachineConnectivityCheck::isConnected(), MachineConnectivityCheck::isConnected(), DefaultICGenerator::isGcuPort(), ComponentImplementationSelector::iuImplementations(), TTAMachine::FUPort::loadStateWithoutReferences(), MachineAnalysis::MachineAnalysis(), AddFUFromHDBDialog::onAdd(), AddWatchDialog::onFUChoice(), FUGuardDialog::onFUChoice(), BlockImplementationDialog::onHDBSelection(), FUArchitectureDialog::onOK(), FUPortDialog::onOK(), IUPortDialog::onOK(), RFPortDialog::onOK(), SRPortDialog::onOK(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), port(), UniversalFunctionUnit::portWithWidth(), MachineResourceManager::registerFileIndexReference(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), MachineResourceManager::rFPortOrFUIndexReference(), saveState(), TTAMachine::Port::setName(), TTAMachine::FUPort::setTriggering(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), TTAMachine::ControlUnit::specialRegisterPort(), TTAMachine::ControlUnit::specialRegisterPortCount(), MachineConnectivityCheck::toRfConnected(), TTAMachine::FunctionUnit::triggerPort(), unsetMachine(), ProximPortWindow::update(), FUArchitectureDialog::update(), TTAMachine::RegisterFile::updateMaxReadsAndWrites(), FUDialog::updatePortList(), GCUDialog::updatePortList(), IUDialog::updatePortList(), RFDialog::updatePortList(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeFUCntrlSignals(), DefaultDecoderGenerator::writeRFCntrlSignals(), DefaultDecoderGenerator::writeRFSRAMDecodingProcess(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
portNames()
Unit::NameSet TTAMachine::Unit::portNames (const ObjectState * state) static private
Creates a set of port names that exists in the given ObjectState tree.
Parameters
state An ObjectState instance representing an unit.
Returns
Set of port names.
Exceptions
KeyNotFound If the given ObjectState instance is invalid.
Definition at line 409 of file Unit.cc.
{
    NameSet names;
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        names.insert(child->stringAttribute(Port::OSKEY_NAME));
    }
    return names;
}
References ObjectState::child(), ObjectState::childCount(), TTAMachine::Port::OSKEY_NAME, and ObjectState::stringAttribute().
Referenced by loadStateWithoutReferences().
removePort()
void TTAMachine::Unit::removePort (Port & port) protected virtual
Removes the given port.
This method should only be called by Port destructor.
Parameters
port Port to be removed.
Reimplemented in TTAMachine::ControlUnit.
Definition at line 235 of file Unit.cc.
{
    // sanity check to verify that this is called from Port's destructor
    // only
    assert(port.parentUnit() == NULL);
    bool removed = ContainerTools::removeValueIfExists(ports_, &port);
    assert(removed);
}
References assert, TTAMachine::Port::parentUnit(), port(), ports_, and ContainerTools::removeValueIfExists().
Referenced by TTAMachine::ControlUnit::removePort(), and TTAMachine::Port::~Port().
saveState()
ObjectState * TTAMachine::Unit::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::Component.
Reimplemented in TTAMachine::BaseRegisterFile, TTAMachine::ControlUnit, TTAMachine::FunctionUnit, TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, and TTAMachine::RegisterFile.
Definition at line 285 of file Unit.cc.
                      {
    ObjectState* state = Component::saveState();
    state->setName(OSNAME_UNIT);
    // add ports
    for (int i = 0; i < portCount(); i++) {
        Port* port = this->port(i);
        state->addChild(port->saveState());
    }
    return state;
}
References ObjectState::addChild(), OSNAME_UNIT, port(), portCount(), TTAMachine::Component::saveState(), TTAMachine::Port::saveState(), and ObjectState::setName().
Referenced by TTAMachine::BaseRegisterFile::saveState(), and TTAMachine::FunctionUnit::saveState().
setMachine()
void TTAMachine::Unit::setMachine (Machine & mach) virtual
Registers the unit to a machine.
Parameters
mach Machine to which the unit is to be registered.
Exceptions
ComponentAlreadyExists If there is another unit by the same name and type in the machine.
Implements TTAMachine::Component.
Reimplemented in TTAMachine::ControlUnit, and TTAMachine::NullRegisterFile.
Definition at line 253 of file Unit.cc.
{
    internalSetMachine(mach);
    mach.addUnit(*this);
}
References TTAMachine::Machine::addUnit(), and TTAMachine::Component::internalSetMachine().
Referenced by AddFUCmd::Do(), AddIUCmd::Do(), and AddRFCmd::Do().
unsetMachine()
void TTAMachine::Unit::unsetMachine () virtual
Removes registration of the unit from its current machine.
Implements TTAMachine::Component.
Reimplemented in TTAMachine::ControlUnit, TTAMachine::FunctionUnit, TTAMachine::ImmediateUnit, TTAMachine::NullRegisterFile, and TTAMachine::RegisterFile.
Definition at line 262 of file Unit.cc.
                   {
    if (machine() == NULL) {
        return;
    }
    internalUnsetMachine();
    // detach all ports from sockets
    int ports = portCount();
    for (int i = 0; i < ports; i++) {
        Port* unitPort = port(i);
        unitPort->detachAllSockets();
    }
}
References TTAMachine::Port::detachAllSockets(), TTAMachine::Component::internalUnsetMachine(), TTAMachine::Component::machine(), port(), and portCount().
Referenced by TTAMachine::FunctionUnit::unsetMachineDerived().
Friends And Related Symbol Documentation
Port
friend class Port friend
Definition at line 99 of file Unit.hh.
Member Data Documentation
OSNAME_UNIT
const string TTAMachine::Unit::OSNAME_UNIT = "unit" static
ObjectState name for Unit.
Definition at line 70 of file Unit.hh.
Referenced by saveState().
ports_
PortTable TTAMachine::Unit::ports_ private
Contains all the ports of the unit.
Definition at line 96 of file Unit.hh.
Referenced by addPort(), bidirPortCount(), deleteAllPorts(), hasPort(), inputPortCount(), outputPortCount(), port(), port(), portCount(), and removePort().
The documentation for this class was generated from the following files:
Unit.hh
Unit.cc