OpenASIP: QuartusProjectGenerator Class Reference
QuartusProjectGenerator Class Reference
#include <QuartusProjectGenerator.hh>
Public Member Functions
QuartusProjectGenerator (TCEString toplevelEntity, const PlatformIntegrator *integrator)
virtual ~QuartusProjectGenerator ()
virtual void writeProjectFiles ()
Public Member Functions inherited from ProjectFileGenerator
ProjectFileGenerator (TCEString coreEntity, const PlatformIntegrator *integrator)
virtual ~ProjectFileGenerator ()
void addHdlFile (const TCEString &file)
void addHdlFiles (const std::vector< TCEString > &files)
void addMemInitFile (const TCEString &memInit)
void addSignalMapping (const PlatInt::SignalMapping &mapping)
Private Member Functions
void writeQPFFile ()
void writeQSFFile ()
void writeScripts ()
Additional Inherited Members
Protected Member Functions inherited from ProjectFileGenerator
const std::vector< TCEString > & hdlFileList () const
const std::vector< TCEString > & memInitFileList () const
const PlatformIntegrator * integrator () const
TCEString coreEntity () const
TCEString toplevelEntity () const
int signalMappingCount () const
const PlatInt::SignalMapping * signalMapping (int index) const
TCEString extractFUName (const TCEString &port, const TCEString &delimiter) const
Detailed Description
Definition at line 41 of file QuartusProjectGenerator.hh.
Constructor & Destructor Documentation
QuartusProjectGenerator()
QuartusProjectGenerator::QuartusProjectGenerator (TCEString toplevelEntity, const PlatformIntegrator * integrator)
Definition at line 46 of file QuartusProjectGenerator.cc.
                                         :
    ProjectFileGenerator(coreEntity, integrator) {
}
~QuartusProjectGenerator()
QuartusProjectGenerator::~QuartusProjectGenerator () virtual
Definition at line 52 of file QuartusProjectGenerator.cc.
{
}
Member Function Documentation
writeProjectFiles()
void QuartusProjectGenerator::writeProjectFiles () virtual
Implements ProjectFileGenerator.
Definition at line 56 of file QuartusProjectGenerator.cc.
{
    writeQPFFile();
    writeQSFFile();
    writeScripts();
}
References writeQPFFile(), writeQSFFile(), and writeScripts().
writeQPFFile()
void QuartusProjectGenerator::writeQPFFile () private
Definition at line 67 of file QuartusProjectGenerator.cc.
{
    TCEString qpfFileName = toplevelEntity() + ".qpf";
    ofstream qpfFile;
    qpfFile.open(qpfFileName.c_str());
    if (!qpfFile) {
        TCEString msg = "Couldn't open file " + qpfFileName + " for writing";
        IOException exc(__FILE__, __LINE__, "QuartusProjectGenerator", msg);
        throw exc;
    }
    qpfFile
        << "# Generated by QuartusProject Generator" << endl << endl
        << "QUARTUS_VERSION = \"8.0\"" << endl << endl
        << "PROJECT_REVISION = \"" << toplevelEntity() << "\"" << endl;
    qpfFile.close();
}
References ProjectFileGenerator::toplevelEntity().
Referenced by writeProjectFiles().
writeQSFFile()
void QuartusProjectGenerator::writeQSFFile () private
Definition at line 86 of file QuartusProjectGenerator.cc.
{
    TCEString qsfFileName = toplevelEntity() + ".qsf";
    ofstream qsfFile;
    qsfFile.open(qsfFileName.c_str());
    if (!qsfFile) {
        TCEString msg = "Couldn't open file " + qsfFileName + " for writing";
        IOException exc(__FILE__, __LINE__, "QuartusProjectGenerator", msg);
        throw exc;
    }
    TCEString deviceFamily = integrator()->deviceFamily();
    TCEString deviceName = integrator()->deviceName();
    int fmax = integrator()->targetClockFrequency();
    qsfFile
        << "# Generated by QuartusProjectGenerator" << endl << endl
        << "set_global_assignment -name FAMILY \"" << deviceFamily << "\""
        << endl
        << "set_global_assignment -name DEVICE " << deviceName << endl
        << "set_global_assignment -name TOP_LEVEL_ENTITY " << toplevelEntity()
        << endl
        << "set_global_assignment -name ORIGINAL_QUARTUS_VERSION 8.0" << endl
        << "set_global_assignment -name LAST_QUARTUS_VERSION 8.0" << endl
        << "set_global_assignment -name USE_GENERATED_PHYSICAL_CONSTRAINTS "
        << "OFF -section_id eda_palace" << endl
        << "set_global_assignment -name USE_CONFIGURATION_DEVICE ON" << endl
        << "set_global_assignment -name RESERVE_ALL_UNUSED_PINS \"AS "
        << "INPUT TRI-STATED\"" << endl
        << "set_global_assignment -name FMAX_REQUIREMENT \"" << fmax
        << " MHz\"" << endl;
    for (unsigned int i = 0; i < hdlFileList().size(); i++) {
        qsfFile << "set_global_assignment -name VHDL_FILE \""
                << hdlFileList().at(i) << "\"" << endl;
    }
    for (unsigned int i = 0; i < memInitFileList().size(); i++) {
        if (StringTools::endsWith(memInitFileList().at(i), ".mif")) {
            qsfFile << "set_global_assignment -name MIF_FILE \""
                    << memInitFileList().at(i) << "\"" << endl;
        } else if (StringTools::endsWith(memInitFileList().at(i), ".hex")) {
            qsfFile << "set_global_assignment -name HEX_FILE \""
                    << memInitFileList().at(i) << "\"" << endl;
        }
    }
    for (int i = 0; i < signalMappingCount(); i++) {
        const SignalMapping* mapping = signalMapping(i);
        qsfFile << "set_location_assignment " << mapping->first
                << " -to " << mapping->second << endl;
    }
    qsfFile.close();
}
References PlatformIntegrator::deviceFamily(), PlatformIntegrator::deviceName(), StringTools::endsWith(), ProjectFileGenerator::hdlFileList(), ProjectFileGenerator::integrator(), ProjectFileGenerator::memInitFileList(), ProjectFileGenerator::signalMapping(), ProjectFileGenerator::signalMappingCount(), PlatformIntegrator::targetClockFrequency(), and ProjectFileGenerator::toplevelEntity().
Referenced by writeProjectFiles().
writeScripts()
void QuartusProjectGenerator::writeScripts () private
Definition at line 142 of file QuartusProjectGenerator.cc.
{
    TCEString exportCommand = "";
    TCEString alteraLibPath =
        Environment::environmentVariable(
            "ALTERA_LIBRARY_PATH");
    if (alteraLibPath != "") {
        exportCommand << "export LD_LIBRARY_PATH=" << alteraLibPath << "\n";
    }
    TCEString synthesisScript = "quartus_synthesize.sh";
    ofstream synthesis;
    synthesis.open(synthesisScript.c_str());
    if (!synthesis) {
        TCEString msg =
            "Couldn't open file " + synthesisScript + " for writing";
        IOException exc(__FILE__, __LINE__, "QuartusProjectGenerator", msg);
        throw exc;
    }
    synthesis
        << "#!/bin/bash" << endl
        << "# Generated by QuartusProjectGenerator of TCE" << endl << endl
        << exportCommand
        << "quartus_sh --flow compile " << toplevelEntity() << endl;
    synthesis.close();
    FileSystem::setFileExecutable(synthesisScript);
    TCEString programmingScript = "quartus_program_fpga.sh";
    ofstream programming;
    programming.open(programmingScript.c_str());
    if (!programming) {
        TCEString msg = "Couldn't open file " + programmingScript
            + " for writing";
        IOException exc(__FILE__, __LINE__, "QuartusProjectGenerator", msg);
        throw exc;
    }
    programming
        << "#!/bin/bash" << endl
        << "# Generated by QuartusProjectGenerator of TCE" << endl << endl
        << exportCommand
        << "quartus_pgm -c USB-Blaster -m JTAG -o p\\;"
        << toplevelEntity() << ".sof" << endl << endl;
    programming.close();
    FileSystem::setFileExecutable(programmingScript);
}
References Environment::environmentVariable(), FileSystem::setFileExecutable(), and ProjectFileGenerator::toplevelEntity().
Referenced by writeProjectFiles().
The documentation for this class was generated from the following files:
QuartusProjectGenerator.hh
QuartusProjectGenerator.cc