OpenASIP: OpenHDBCmd Class Reference
OpenHDBCmd Class Reference
#include <OpenHDBCmd.hh>
Public Member Functions
OpenHDBCmd ()
virtual ~OpenHDBCmd ()
virtual bool Do ()
virtual int id () const
virtual OpenHDBCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening HDB in HDBEditor.
Displays a file dialog for choosing the HDB file to open.
Definition at line 43 of file OpenHDBCmd.hh.
Constructor & Destructor Documentation
OpenHDBCmd()
OpenHDBCmd::OpenHDBCmd ()
The Constructor.
Definition at line 46 of file OpenHDBCmd.cc.
                      :
    GUICommand(HDBEditorConstants::COMMAND_NAME_OPEN_HDB, NULL) {
}
Referenced by create().
~OpenHDBCmd()
OpenHDBCmd::~OpenHDBCmd () virtual
The Destructor.
Definition at line 54 of file OpenHDBCmd.cc.
{
}
Member Function Documentation
create()
OpenHDBCmd * OpenHDBCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 110 of file OpenHDBCmd.cc.
{
    return new OpenHDBCmd();
}
References OpenHDBCmd().
Do()
bool OpenHDBCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 62 of file OpenHDBCmd.cc.
               {
    assert(parentWindow() != NULL);
    wxString wildcard = _T("Hardware Database files (*.hdb)|*.hdb");
    wildcard.Append(_T("|All files|*"));
    wxFileDialog dialog(
    parentWindow(), _T("Choose a file."), _T(""), _T(""),
    wildcard, wxOPEN);
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    std::string command;
    std::string file = WxConversion::toString(dialog.GetPath());
    wxGetApp().mainFrame().setHDB(file);
    return true;
}
References assert, GUICommand::parentWindow(), and WxConversion::toString().
icon()
std::string OpenHDBCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 90 of file OpenHDBCmd.cc.
                       {
    return "fileopen.png";
}
id()
int OpenHDBCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 99 of file OpenHDBCmd.cc.
                     {
    return HDBEditorConstants::COMMAND_OPEN_HDB;
}
References HDBEditorConstants::COMMAND_OPEN_HDB.
isEnabled()
bool OpenHDBCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 121 of file OpenHDBCmd.cc.
                      {
    return true;
}
The documentation for this class was generated from the following files:
OpenHDBCmd.hh
OpenHDBCmd.cc