OpenASIP: OperationBehaviorProxy Class Reference
OperationBehaviorProxy Class Reference
#include <OperationBehaviorProxy.hh>
Public Member Functions
OperationBehaviorProxy (Operation &targetOperation, OperationBehaviorLoader &loader, bool alwaysReloadBehavior=false)
virtual ~OperationBehaviorProxy ()
virtual bool simulateTrigger (SimValue **io, OperationContext &context) const
virtual bool canBeSimulated () const
virtual void createState (OperationContext &context) const
virtual void deleteState (OperationContext &context) const
virtual void setAlwaysReloadBehavior (bool f)
void uninitializeBehavior () const
Public Member Functions inherited from OperationBehavior
virtual bool areValid (const InputOperandVector &inputs, const OperationContext &context) const
virtual const char * stateName () const
virtual void writeOutput (const char *text) const
OperationBehavior ()
OperationBehavior (const Operation &parent)
virtual ~OperationBehavior ()
Private Member Functions
OperationBehaviorProxy (const OperationBehaviorProxy &)
Copying not allowed.
OperationBehaviorProxy & operator= (const OperationBehaviorProxy &)
Assignment not allowed.
void initializeBehavior () const
Private Attributes
Operation * target_
Operation that owns this proxy;.
OperationBehaviorLoader * loader_
Used to load behavior model for operation.
bool initialized_
Flag indicating whether proxy is initialized or not.
std::set< OperationDAGBehavior * > cleanUs_
Clean up list for created OperationDAGBehaviors.
bool alwaysReloadBehavior_
If this is true, the behavior is always (re)loaded from the dynamic library or the DAG instead of loading it once and reusing in the future calls.
bool alreadyCreatingState_
Helpers variable to catch infinite recursive function call due to missing or undefined operation behavior.
Additional Inherited Members
Public Types inherited from OperationBehavior
typedef std::vector< SimValue > InputOperandVector
Input operand type for areValid()
Protected Attributes inherited from OperationBehavior
const Operation & parent_
Detailed Description
This class is used to create a behavior model of an operation.
A first time operation calls simulateTrigger() proxy creates the appropriate operation behavior model for the operation. Proxy replaces itself in the operation with the newly created behavior model. That new model then executes all simulation functions.
Definition at line 58 of file OperationBehaviorProxy.hh.
Constructor & Destructor Documentation
OperationBehaviorProxy() [1/2]
OperationBehaviorProxy::OperationBehaviorProxy (Operation & targetOperation, OperationBehaviorLoader & loader, bool alwaysReloadBehavior = false)
Constructor.
Registers the operation for which this proxy represents the behavior model. Registers the operation behavior loader that is used to find the appropriate behavior model of the operation.
Parameters
targetOperation Target operation for proxy.
loader Operation behavior loader for the proxy.
Definition at line 56 of file OperationBehaviorProxy.cc.
                               :
    OperationBehavior(), target_(&targetOperation), loader_(&loader),
    initialized_(false),  alwaysReloadBehavior_(alwaysReloadBehavior),
    alreadyCreatingState_(false) {
}
~OperationBehaviorProxy()
OperationBehaviorProxy::~OperationBehaviorProxy () virtual
Destructor.
Operation behavior loader frees all loaded operation behavior models.
Definition at line 70 of file OperationBehaviorProxy.cc.
{
    while (!cleanUs_.empty()) {
        delete *(cleanUs_.begin());
        cleanUs_.erase(cleanUs_.begin());
    }
}
References cleanUs_.
OperationBehaviorProxy() [2/2]
OperationBehaviorProxy::OperationBehaviorProxy (const OperationBehaviorProxy &) private
Copying not allowed.
Member Function Documentation
canBeSimulated()
bool OperationBehaviorProxy::canBeSimulated () const virtual
Imports operation behavior model for the operation that owns this proxy and then delegates the work to that imported model.
After initializing the operation with imported operation behavior model proxy has done its job.
Returns
True if this operation has behavior, or dag which is
Reimplemented from OperationBehavior.
Definition at line 162 of file OperationBehaviorProxy.cc.
{
    try {
        initializeBehavior();
    } catch (Exception&) {
        if (alwaysReloadBehavior_) uninitializeBehavior();
        return false;
    }
    // if initialization was not success
    if (&target_->behavior() == this) {
        if (alwaysReloadBehavior_) uninitializeBehavior();
        return false;
    } else {
        bool retVal = target_->canBeSimulated();
        if (alwaysReloadBehavior_) uninitializeBehavior();
        return retVal;
    }
}
References alwaysReloadBehavior_, Operation::behavior(), Operation::canBeSimulated(), initializeBehavior(), target_, and uninitializeBehavior().
createState()
void OperationBehaviorProxy::createState (OperationContext & context) const virtual
Imports operation behavior model for the operation that owns this proxy and then delegates the work to that imported model.
After initializing the operation with imported operation behavior model proxy has done its job.
Parameters
context The operation context to add the state in.
Reimplemented from OperationBehavior.
Definition at line 111 of file OperationBehaviorProxy.cc.
{
    initializeBehavior();
    // If operation does not have operation behavior defined or behavior file
    // is missing it causes infinite recursive call between
    // Operation::createState() and this function. Catch such event and break
    // out of it.
    if (alreadyCreatingState_) {
        throw IllegalOperationBehavior(__FILE__, __LINE__, __func__,
            std::string("Error while loading operation behavior for "
                "operation \"")
            + target_->name()
            + "\". Operation behavior is undefined or missing.");
    }
    alreadyCreatingState_ = true;
    target_->createState(context);
    if (alwaysReloadBehavior_) {
        uninitializeBehavior();
    }
    alreadyCreatingState_ = true;
}
References __func__, alreadyCreatingState_, alwaysReloadBehavior_, Operation::createState(), initializeBehavior(), Operation::name(), target_, and uninitializeBehavior().
deleteState()
void OperationBehaviorProxy::deleteState (OperationContext & context) const virtual
Imports operation behavior model for the operation that owns this proxy and then delegates the work to that imported model.
After initializing the operation with imported operation behavior model proxy has done its job.
Parameters
context The operation context to delete the state from.
Reimplemented from OperationBehavior.
Definition at line 145 of file OperationBehaviorProxy.cc.
{
    initializeBehavior();
    target_->deleteState(context);
    if (alwaysReloadBehavior_) uninitializeBehavior();
}
References alwaysReloadBehavior_, Operation::deleteState(), initializeBehavior(), target_, and uninitializeBehavior().
initializeBehavior()
void OperationBehaviorProxy::initializeBehavior () const private
Initializes the operation that owns this proxy with an operation behavior model.
Proxy replaces itself with the imported operation behavior model. After that proxy methods are never called.
This method is executed only once. After that, this function does nothing. This function may abort the program, if error condition occurs while operation behavior model is imported.
Exceptions
DynamicLibraryException Leaked from importBehavior in case behavior file was invalid.
Definition at line 195 of file OperationBehaviorProxy.cc.
{
    if (initialized_) {
        return;
    }
    try {
        OperationBehavior& ob = loader_->importBehavior(*target_);
        target_->setBehavior(ob);
        return;
    } catch (FileNotFound&) {
    } catch (SymbolNotFound& e) {
        // try loading behavior from DAG
        if (target_->dagCount() == 0) {
            throw e;
        }
    } catch (Exception& e) {
        throw e;
    }
    // no compiled behavior in .opb found
    // if there is DAG to create behavior model...
    if (target_->dagCount() == 0) {
        initialized_ = true;
        return;
    }
    // there was not behavior plugin so let's use dag for simulation
    OperationDAGBehavior* behavior =
        new OperationDAGBehavior(
            target_->dag(0),
            target_->numberOfInputs() +
            target_->numberOfOutputs(),
            *target_);
    target_->setBehavior(*behavior);
    // add for cleanup
    cleanUs_.insert(behavior);
    initialized_ = true;
}
References cleanUs_, Operation::dag(), Operation::dagCount(), OperationBehaviorLoader::importBehavior(), initialized_, loader_, Operation::numberOfInputs(), Operation::numberOfOutputs(), Operation::setBehavior(), and target_.
Referenced by canBeSimulated(), createState(), deleteState(), and simulateTrigger().
operator=()
OperationBehaviorProxy & OperationBehaviorProxy::operator= (const OperationBehaviorProxy &) private
Assignment not allowed.
setAlwaysReloadBehavior()
virtual void OperationBehaviorProxy::setAlwaysReloadBehavior (bool f) inline virtual
Definition at line 76 of file OperationBehaviorProxy.hh.
{ alwaysReloadBehavior_ = f; }
References alwaysReloadBehavior_.
Referenced by SimulateDialog::~SimulateDialog().
simulateTrigger()
bool OperationBehaviorProxy::simulateTrigger (SimValue ** io, OperationContext & context) const virtual
Imports operation behavior model for the operation that owns this proxy and then delegates the work to that imported model.
After initializing the operation with imported operation behavior model proxy has done its job.
Parameters
io The input and output operands.
context The operation context.
Returns
True if all values could be computed, false otherwise.
Exceptions
IllegalOperationBehavior If trigger command lacks return statement.
Implements OperationBehavior.
Definition at line 91 of file OperationBehaviorProxy.cc.
{
    initializeBehavior();
    bool retVal = target_->simulateTrigger(io, context);
    if (alwaysReloadBehavior_) uninitializeBehavior();
    return retVal;
}
References alwaysReloadBehavior_, initializeBehavior(), Operation::simulateTrigger(), target_, and uninitializeBehavior().
uninitializeBehavior()
void OperationBehaviorProxy::uninitializeBehavior () const
Uninitializes the behavior description from the operation so it will be reloaded again when a behavior method is called the next time.
Definition at line 244 of file OperationBehaviorProxy.cc.
{
    while (!cleanUs_.empty()) {
        OperationBehavior* behavior = *cleanUs_.begin();
        delete behavior;
        cleanUs_.erase(cleanUs_.begin());
    }
    target_->setBehavior(const_cast<OperationBehaviorProxy&>(*this));
    loader_->freeBehavior();
    initialized_ = false;
}
References cleanUs_, OperationBehaviorLoader::freeBehavior(), initialized_, loader_, Operation::setBehavior(), and target_.
Referenced by canBeSimulated(), createState(), deleteState(), simulateTrigger(), and SimulateDialog::~SimulateDialog().
Member Data Documentation
alreadyCreatingState_
bool OperationBehaviorProxy::alreadyCreatingState_ mutable private
Helpers variable to catch infinite recursive function call due to missing or undefined operation behavior.
Definition at line 101 of file OperationBehaviorProxy.hh.
Referenced by createState().
alwaysReloadBehavior_
bool OperationBehaviorProxy::alwaysReloadBehavior_ private
If this is true, the behavior is always (re)loaded from the dynamic library or the DAG instead of loading it once and reusing in the future calls.
Definition at line 98 of file OperationBehaviorProxy.hh.
Referenced by canBeSimulated(), createState(), deleteState(), setAlwaysReloadBehavior(), and simulateTrigger().
cleanUs_
std::set<OperationDAGBehavior*> OperationBehaviorProxy::cleanUs_ mutable private
Clean up list for created OperationDAGBehaviors.
Definition at line 94 of file OperationBehaviorProxy.hh.
Referenced by initializeBehavior(), uninitializeBehavior(), and ~OperationBehaviorProxy().
initialized_
bool OperationBehaviorProxy::initialized_ mutable private
Flag indicating whether proxy is initialized or not.
Definition at line 92 of file OperationBehaviorProxy.hh.
Referenced by initializeBehavior(), and uninitializeBehavior().
loader_
OperationBehaviorLoader* OperationBehaviorProxy::loader_ private
Used to load behavior model for operation.
Definition at line 90 of file OperationBehaviorProxy.hh.
Referenced by initializeBehavior(), and uninitializeBehavior().
target_
Operation* OperationBehaviorProxy::target_ private
Operation that owns this proxy;.
Definition at line 88 of file OperationBehaviorProxy.hh.
Referenced by canBeSimulated(), createState(), deleteState(), initializeBehavior(), simulateTrigger(), and uninitializeBehavior().
The documentation for this class was generated from the following files:
OperationBehaviorProxy.hh
OperationBehaviorProxy.cc