OpenASIP: ImmediateEncoding Class Reference
ImmediateEncoding Class Reference
#include <ImmediateEncoding.hh>
Public Member Functions
ImmediateEncoding (unsigned int encoding, unsigned int extraBits, int immediateWidth, SourceField &parent)
ImmediateEncoding (const ObjectState *state, SourceField &parent)
virtual ~ImmediateEncoding ()
SourceField * parent () const
int immediateWidth () const
int encodingWidth () const
int encodingPosition () const
int immediatePosition () const
virtual int bitPosition () const
virtual int width () const
virtual ObjectState * saveState () const
Public Member Functions inherited from Encoding
virtual ~Encoding ()
InstructionField * parent () const
unsigned int encoding () const
unsigned int extraBits () const
Static Public Attributes
static const std::string OSNAME_IMM_ENCODING = "imm_encoding"
ObjectState name for immediate encoding.
static const std::string OSKEY_IMM_WIDTH = "imm_width"
ObjectState attribute key for the immediate width.
Static Public Attributes inherited from Encoding
static const std::string OSNAME_ENCODING = "encoding"
ObjectState name for Encoding class.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Private Attributes
int immediateWidth_
Additional Inherited Members
Protected Member Functions inherited from Encoding
Encoding (unsigned int encoding, unsigned int extraBits, InstructionField *parent)
Encoding (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
void setEncoding (unsigned int encoding, unsigned int extraBits)
Detailed Description
Represents the encoding for inline immediate within the source field.
Definition at line 44 of file ImmediateEncoding.hh.
Constructor & Destructor Documentation
ImmediateEncoding() [1/2]
ImmediateEncoding::ImmediateEncoding (unsigned int encoding, unsigned int extraBits, int immediateWidth, SourceField & parent)
The constructor.
Registers the encoding automatically to the parent source field.
Parameters
encoding The encoding for inline immediates.
extraBits The number of extra bits in the encoding.
immediateWidth Width of the inline immediate.
parent The parent source field.
Exceptions
ObjectAlreadyExists If the given source field has an immediate encoding already or if the encoding is ambiguous with some socket or bridge encoding in the source field.
OutOfRange If the given immediate width is negative.
Definition at line 60 of file ImmediateEncoding.cc.
    : Encoding(encoding, extraBits, NULL), immediateWidth_(immediateWidth) {
    if (immediateWidth < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    parent.setImmediateEncoding(*this);
    setParent(&parent);
}
References __func__, immediateWidth(), parent(), SourceField::setImmediateEncoding(), and Encoding::setParent().
ImmediateEncoding() [2/2]
ImmediateEncoding::ImmediateEncoding (const ObjectState * state, SourceField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent source field.
Exceptions
ObjectAlreadyExists If the given source field has an immediate encoding already or if the encoding is ambiguous with some socket or bridge encoding in the source field.
ObjectStateLoadingException If the given ObjectState instance is erroneous.
Definition at line 86 of file ImmediateEncoding.cc.
    : Encoding(state, NULL) {
    const string procName = "ImmediateEncoding::ImmediateEncoding";
    if (state->name() != OSNAME_IMM_ENCODING) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        immediateWidth_ = state->intAttribute(OSKEY_IMM_WIDTH);
        if (immediateWidth_ < 0) {
            throw OutOfRange(__FILE__, __LINE__, __func__);
        }
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, __func__, e.errorMessage());
    }
    parent.setImmediateEncoding(*this);
    setParent(&parent);
}
References __func__, Exception::errorMessage(), immediateWidth_, ObjectState::intAttribute(), ObjectState::name(), OSKEY_IMM_WIDTH, OSNAME_IMM_ENCODING, parent(), SourceField::setImmediateEncoding(), and Encoding::setParent().
~ImmediateEncoding()
ImmediateEncoding::~ImmediateEncoding () virtual
The destructor.
Definition at line 112 of file ImmediateEncoding.cc.
{
    SourceField* oldParent = parent();
    assert(oldParent != NULL);
    setParent(NULL);
    oldParent->unsetImmediateEncoding();
}
References assert, parent(), Encoding::setParent(), and SourceField::unsetImmediateEncoding().
Member Function Documentation
bitPosition()
int ImmediateEncoding::bitPosition () const virtual
Returns always 0.
Returns
The position of the encoding.
Implements Encoding.
Definition at line 196 of file ImmediateEncoding.cc.
{
    return 0;
}
encodingPosition()
int ImmediateEncoding::encodingPosition () const
Returns the position of the immediate encoding.
Returns
The position of the immediate encoding.
Definition at line 166 of file ImmediateEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::LEFT) {
        return parent()->width() - parent()->extraBits() - encodingWidth();
    } else {
        return 0;
    }
}
References encodingWidth(), InstructionField::extraBits(), BinaryEncoding::LEFT, parent(), and SourceField::width().
Referenced by BEMTester::conflictsWithSourceEncodings(), and DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus().
encodingWidth()
int ImmediateEncoding::encodingWidth () const
Returns the encoding width.
Returns
The encoding width.
Definition at line 155 of file ImmediateEncoding.cc.
{
    return Encoding::width();
}
References Encoding::width().
Referenced by BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeImmediateTerminal(), encodingPosition(), printSourceFieldEncodings(), width(), and DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus().
immediatePosition()
int ImmediateEncoding::immediatePosition () const
Returns the position of the short immediate within the source field.
Returns
The position of the short immediate.
Definition at line 181 of file ImmediateEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::LEFT) {
        return 0;
    } else {
        return parent()->width() - parent()->extraBits() - immediateWidth();
    }
}
References InstructionField::extraBits(), immediateWidth(), BinaryEncoding::LEFT, parent(), and SourceField::width().
Referenced by DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), and DefaultDecoderGenerator::writeSimmDataSignal().
immediateWidth()
int ImmediateEncoding::immediateWidth () const
Returns the immediate width.
Returns
The immediate width.
Definition at line 144 of file ImmediateEncoding.cc.
{
    return immediateWidth_;
}
References immediateWidth_.
Referenced by ImmediateEncoding(), immediatePosition(), printSourceFieldEncodings(), saveState(), width(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), and DefaultDecoderGenerator::writeSimmDataSignal().
parent()
SourceField * ImmediateEncoding::parent () const
Returns the parent source field.
Returns
The parent.
Definition at line 126 of file ImmediateEncoding.cc.
{
    InstructionField* parent = Encoding::parent();
    if (parent != NULL) {
        SourceField* sField = dynamic_cast<SourceField*>(parent);
        assert(sField != NULL);
        return sField;
    } else {
        return NULL;
    }
}
References assert, Encoding::parent(), and parent().
Referenced by encodingPosition(), ImmediateEncoding(), ImmediateEncoding(), immediatePosition(), parent(), SourceField::setImmediateEncoding(), and ~ImmediateEncoding().
saveState()
ObjectState * ImmediateEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from Encoding.
Definition at line 218 of file ImmediateEncoding.cc.
{
    ObjectState* state = Encoding::saveState();
    state->setName(OSNAME_IMM_ENCODING);
    state->setAttribute(OSKEY_IMM_WIDTH, immediateWidth());
    return state;
}
References immediateWidth(), OSKEY_IMM_WIDTH, OSNAME_IMM_ENCODING, Encoding::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
width()
int ImmediateEncoding::width () const virtual
Returns the width of the encoding + immediate width.
Returns
The width.
Reimplemented from Encoding.
Definition at line 207 of file ImmediateEncoding.cc.
{
    return immediateWidth() + encodingWidth();
}
References encodingWidth(), and immediateWidth().
Referenced by BEMTester::canAddComponentEncoding(), printSourceFieldEncodings(), and SourceField::width().
Member Data Documentation
immediateWidth_
int ImmediateEncoding::immediateWidth_ private
Definition at line 68 of file ImmediateEncoding.hh.
Referenced by ImmediateEncoding(), and immediateWidth().
OSKEY_IMM_WIDTH
const std::string ImmediateEncoding::OSKEY_IMM_WIDTH = "imm_width" static
ObjectState attribute key for the immediate width.
Definition at line 65 of file ImmediateEncoding.hh.
Referenced by ImmediateEncoding(), saveState(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
OSNAME_IMM_ENCODING
const std::string ImmediateEncoding::OSNAME_IMM_ENCODING = "imm_encoding" static
ObjectState name for immediate encoding.
Definition at line 63 of file ImmediateEncoding.hh.
Referenced by ImmediateEncoding(), SourceField::loadState(), saveState(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
The documentation for this class was generated from the following files:
ImmediateEncoding.hh
ImmediateEncoding.cc