OpenASIP: HDLGenerator::Sext Class Reference
HDLGenerator::Sext Class Reference
#include <WidthTransformations.hh>
Public Member Functions
Sext (std::string name, int extWidth, int signalWidth)
Sext (std::string name, std::string extWidth, int signalWidth)
void write_rtl (std::string name, std::string extWidth, int signalWidth)
Public Member Functions inherited from HDLGenerator::LHSValue
LHSValue ()
void hdl (std::ostream &stream, Language lang, int level)
void hdl (std::ostream &stream, Language lang)
void writeSignals (std::unordered_set< std::string > &readList) const
std::string vhdl () const
std::string verilog () const
LHSValue operator|| (LHSValue rhs)
LHSValue operator| (LHSValue rhs)
LHSValue operator&& (LHSValue rhs)
LHSValue operator& (LHSValue rhs)
LHSValue operator^ (LHSValue rhs)
LHSValue operator! ()
LHSValue operator~ ()
Additional Inherited Members
Protected Attributes inherited from HDLGenerator::LHSValue
std::unordered_set< std::string > readList_
std::string vhdl_
std::string verilog_
Detailed Description
Signed extend.
Definition at line 82 of file WidthTransformations.hh.
Constructor & Destructor Documentation
Sext() [1/2]
HDLGenerator::Sext::Sext (std::string name, int extWidth, int signalWidth) inline
Definition at line 84 of file WidthTransformations.hh.
{
            readList_.insert(name);
            if (extWidth > signalWidth) {
                write_rtl(name, std::to_string(extWidth), signalWidth);
            } else {
                vhdl_ = name;
                verilog_ = name;
            }
        }
References HDLGenerator::LHSValue::readList_, HDLGenerator::LHSValue::verilog_, HDLGenerator::LHSValue::vhdl_, and write_rtl().
Sext() [2/2]
HDLGenerator::Sext::Sext (std::string name, std::string extWidth, int signalWidth) inline
Definition at line 94 of file WidthTransformations.hh.
{
             readList_.insert(name);
             write_rtl(name,  extWidth, signalWidth);
        }
References HDLGenerator::LHSValue::readList_, and write_rtl().
Member Function Documentation
write_rtl()
void HDLGenerator::Sext::write_rtl (std::string name, std::string extWidth, int signalWidth) inline
Definition at line 99 of file WidthTransformations.hh.
{
            std::string sigWidth = std::to_string(signalWidth);
            vhdl_ = "((" + extWidth + "-1 downto " + sigWidth + " => " + name;
            verilog_ = "{{" + extWidth + "-" + sigWidth + "{" + name + "}";
            if (signalWidth > 1) {
                vhdl_ += "(" + sigWidth + "-1)";
                verilog_ += "[" + sigWidth + "-1]";
            }
            vhdl_ += ") & " + name + ")";
            verilog_ += "}}" + name + "}";
        }
References HDLGenerator::LHSValue::verilog_, and HDLGenerator::LHSValue::vhdl_.
Referenced by Sext(), and Sext().
The documentation for this class was generated from the following file:
WidthTransformations.hh