OpenASIP: IntegerListCmdLineOptionParser Class Reference
IntegerListCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
IntegerListCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~IntegerListCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual int integer (int index=0) const
virtual int listSize () const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual unsigned unsignedInteger (int index=0) const
virtual std::string String (int index=0) const
virtual double real () const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
Private Member Functions
IntegerListCmdLineOptionParser (const IntegerListCmdLineOptionParser &)
Copying not allowed.
IntegerListCmdLineOptionParser & operator= (const IntegerListCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
std::vector< int > values_
The values in integer list.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that has a list of integers as value.
Definition at line 310 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
IntegerListCmdLineOptionParser() [1/2]
IntegerListCmdLineOptionParser::IntegerListCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 681 of file CmdLineOptionParser.cc.
                     : CmdLineOptionParser(name, desc, alias) {
}
~IntegerListCmdLineOptionParser()
IntegerListCmdLineOptionParser::~IntegerListCmdLineOptionParser () virtual
Destructor.
Definition at line 690 of file CmdLineOptionParser.cc.
{
    values_.clear();
}
References values_.
IntegerListCmdLineOptionParser() [2/2]
IntegerListCmdLineOptionParser::IntegerListCmdLineOptionParser (const IntegerListCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * IntegerListCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 703 of file CmdLineOptionParser.cc.
{
    IntegerListOptionValue* copy = new IntegerListOptionValue(values_);
    return copy;
}
References copy(), and values_.
Referenced by copy().
integer()
int IntegerListCmdLineOptionParser::integer (int index = 0) const virtual
Returns a particular value of integer list option.
Parameters
index The index of list element that is wanted.
Returns
The value of a particular element in list.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 772 of file CmdLineOptionParser.cc.
{
    assert(index > 0 && static_cast<unsigned>(index) <= values_.size());
    return values_[index - 1];
}
References assert, and values_.
listSize()
int IntegerListCmdLineOptionParser::listSize () const virtual
Returns the number of list elements.
Returns
The number of list elements.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 784 of file CmdLineOptionParser.cc.
{
    return values_.size();
}
References values_.
operator=()
IntegerListCmdLineOptionParser & IntegerListCmdLineOptionParser::operator= (const IntegerListCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool IntegerListCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of integer set.
Value should be integers separated by commas.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine If argument is invalid.
Implements CmdLineOptionParser.
Definition at line 719 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for integer list option";
        string method = "IntegerListCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    if (arguments == "") {
        string msg = "Missing value for option " + longName();
        string method = "IntegerSetCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    int number;
    char comma;
    istringstream istream(arguments);
    // there must be at least one number
    if (!(istream >> number)) {
        string msg = "Format of " + longName() + "option value was wrong";
        string method = "IntegerSetCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    values_.push_back(number);
    while (istream.peek() != EOF) {
        // now there must be comma
        if (!(istream >> comma) || comma != ',') {
            string msg = "Format of " + longName() + "option value was wrong";
            string method = "IntegerSetCmdLineOptionParser::parseValue()";
            throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
        }
        if (!(istream >> number)) {
            string msg = "Format of " + longName() + "option value was wrong";
            string method = "IntegerSetCmdLineOptionParser::parseValue()";
            throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
        }
        values_.push_back(number);
    }
    setDefined();
    return true;
}
References CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and values_.
Member Data Documentation
values_
std::vector<int> IntegerListCmdLineOptionParser::values_ private
The values in integer list.
Definition at line 333 of file CmdLineOptionParser.hh.
Referenced by copy(), integer(), listSize(), parseValue(), and ~IntegerListCmdLineOptionParser().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc