OpenASIP: SocketContainerFigure Class Reference
SocketContainerFigure Class Reference
#include <SocketContainerFigure.hh>
Public Member Functions
SocketContainerFigure ()
virtual ~SocketContainerFigure ()
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutChildren (wxDC *)
virtual void layoutSelf (wxDC *)
Protected Member Functions inherited from Figure
virtual void drawSelf (wxDC *dc)
void drawChildren (wxDC *dc)
Private Member Functions
SocketContainerFigure & operator= (SocketContainerFigure &old)
Assignment not allowed.
SocketContainerFigure (SocketContainerFigure &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a container EditPart for sockets.
Definition at line 46 of file SocketContainerFigure.hh.
Constructor & Destructor Documentation
SocketContainerFigure() [1/2]
SocketContainerFigure::SocketContainerFigure ()
The Constructor.
Definition at line 44 of file SocketContainerFigure.cc.
                                            : Figure() {
}
~SocketContainerFigure()
SocketContainerFigure::~SocketContainerFigure () virtual
The Destructor.
Definition at line 50 of file SocketContainerFigure.cc.
{
}
SocketContainerFigure() [2/2]
SocketContainerFigure::SocketContainerFigure (SocketContainerFigure & old) private
Copying not allowed.
Member Function Documentation
layoutChildren()
void SocketContainerFigure::layoutChildren (wxDC * dc) protected virtual
Lays out child sockets.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 59 of file SocketContainerFigure.cc.
{
    int unknownSocketX = location_.x + size_.GetWidth();
    // set locations for sockets not connected to any port
    vector<Figure*>::iterator i = children_.begin();
    for(; i != children_.end(); i++) {
    if ((*i)->location().x == 0) {
        (*i)->setX(unknownSocketX);
        unknownSocketX += MachineCanvasLayoutConstraints::SOCKET_WIDTH +
        MachineCanvasLayoutConstraints::SOCKET_SPACE;
    }
    (*i)->setY(location_.y);
    if (size_.GetHeight() > (*i)->bounds().GetHeight()) {
        (*i)->setHeight(size_.GetHeight());
    }
    (*i)->layout(dc);
    (*i)->clearXSetFlag();
    }
}
References Figure::children_, Figure::location_, Figure::setX(), Figure::size_, MachineCanvasLayoutConstraints::SOCKET_SPACE, and MachineCanvasLayoutConstraints::SOCKET_WIDTH.
layoutSelf()
void SocketContainerFigure::layoutSelf (wxDC *) protected virtual
Calculates and sets the width of the container.
Depends on the amount and position of sockets.
Reimplemented from Figure.
Definition at line 89 of file SocketContainerFigure.cc.
{
    int maxIndex = 0;
    int maxX = 0;
    for (unsigned int i = 0; i < children_.size(); i++) {
    if (children_[i]->location().x > maxX) {
        maxX = children_[i]->location().x;
        maxIndex = i;
    }
    }
    int rightBound = maxX + children_[maxIndex]->bounds().GetWidth() +
    MachineCanvasLayoutConstraints::SOCKET_WIDTH;
    if (rightBound > location_.x + size_.GetWidth()) {
        size_.SetWidth(rightBound - location_.x);
    }
    if (children_[0]->bounds().GetHeight() > size_.GetHeight()) {
    size_.SetHeight(children_[0]->bounds().GetHeight());
    }
}
References Figure::bounds(), Figure::children_, Figure::location(), Figure::location_, Figure::size_, and MachineCanvasLayoutConstraints::SOCKET_WIDTH.
operator=()
SocketContainerFigure & SocketContainerFigure::operator= (SocketContainerFigure & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
SocketContainerFigure.hh
SocketContainerFigure.cc