OpenASIP: SaveOptionsCmd Class Reference
SaveOptionsCmd Class Reference
#include <SaveOptionsCmd.hh>
Public Member Functions
SaveOptionsCmd ()
virtual ~SaveOptionsCmd ()
virtual bool Do ()
virtual int id () const
virtual SaveOptionsCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for saving editor options.
Creates and shows an OptionsDialog.
Definition at line 42 of file SaveOptionsCmd.hh.
Constructor & Destructor Documentation
SaveOptionsCmd()
SaveOptionsCmd::SaveOptionsCmd ()
The Constructor.
Definition at line 49 of file SaveOptionsCmd.cc.
                              :
    EditorCommand(ProDeConstants::CMD_NAME_SAVE_OPTIONS) {
}
Referenced by create().
~SaveOptionsCmd()
SaveOptionsCmd::~SaveOptionsCmd () virtual
The Destructor.
Definition at line 57 of file SaveOptionsCmd.cc.
{}
Member Function Documentation
create()
SaveOptionsCmd * SaveOptionsCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 98 of file SaveOptionsCmd.cc.
{
    return new SaveOptionsCmd();
}
References SaveOptionsCmd().
Do()
bool SaveOptionsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file SaveOptionsCmd.cc.
                   {
    ProDeOptions* options = wxGetApp().options();
    ProDeOptionsSerializer writer;
    writer.setDestinationFile(Environment::userConfPath("ProDe.conf"));
    try {
        writer.writeOptions(*options);
        options->clearModified();
    } catch (Exception const& e) {
        ErrorDialog errorDialog(parentWindow(),
            WxConversion::toWxString(e.errorMessage()));
        errorDialog.ShowModal();
        return false;
    }
    return true;
}
References Exception::errorMessage(), options, GUICommand::parentWindow(), XMLSerializer::setDestinationFile(), WxConversion::toWxString(), Environment::userConfPath(), and GUIOptionsSerializer::writeOptions().
icon()
string SaveOptionsCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 117 of file SaveOptionsCmd.cc.
{
    return ProDeConstants::CMD_ICON_SAVE_OPTIONS;
}
References ProDeConstants::CMD_ICON_SAVE_OPTIONS.
id()
int SaveOptionsCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 89 of file SaveOptionsCmd.cc.
{
    return ProDeConstants::COMMAND_SAVE_OPTIONS;
}
References ProDeConstants::COMMAND_SAVE_OPTIONS.
isEnabled()
bool SaveOptionsCmd::isEnabled () virtual
This command is enabled when the options have been modified.
Returns
True if the options have been modified, otherwise false.
Reimplemented from EditorCommand.
Definition at line 128 of file SaveOptionsCmd.cc.
{
    return wxGetApp().options()->isModified();
}
shortName()
string SaveOptionsCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 108 of file SaveOptionsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_SAVE_OPTIONS;
}
References ProDeConstants::CMD_SNAME_SAVE_OPTIONS.
The documentation for this class was generated from the following files:
SaveOptionsCmd.hh
SaveOptionsCmd.cc