OpenASIP: ExecutionPipelineResourceTable Class Reference
ExecutionPipelineResourceTable Class Reference
#include <ExecutionPipelineResourceTable.hh>
Public Member Functions
unsigned int numberOfResources () const
unsigned int pipelineSize () const
unsigned int maximalLatency () const
bool operationPipeline (int op, int cycle, int res) const
int operationIndex (const std::string &opName) const
bool hasOperation (const std::string &opName) const
const std::map< int, int > & operationLatency (unsigned int operationIndex) const
const std::string & name () const
Static Public Member Functions
static const ExecutionPipelineResourceTable & resourceTable (const TTAMachine::FunctionUnit &fu)
static void finalize ()
Private Types
typedef std::vector< bool > ResourceVector
Type for resource vector, represents one cycle of use.
typedef std::vector< ResourceVector > ResourceTable
Type for resource reservation table, resource vector x latency.
typedef std::map< const TTAMachine::FunctionUnit *, ExecutionPipelineResourceTable * > ResourceTableMap
Private Member Functions
ExecutionPipelineResourceTable (const TTAMachine::FunctionUnit &fu)
void setLatency (const std::string &opName, const int output, const int latency)
void setResourceUse (const std::string &opName, const int cycle, const int resIndex)
Private Attributes
std::string name_
int numberOfResources_
Resource and ports vector width, depends on particular FU.
unsigned int maximalLatency_
Maximal latency of operation in FU.
std::map< std::string, int > operationSupported_
Operations supported, name - index to operation pipeline vector.
std::vector< std::map< int, int > > operationLatencies_
std::vector< ResourceTable > operationPipelines_
Pipelines for operations.
Static Private Attributes
static ResourceTableMap allResourceTables_
Contains these tables for all FU's.
Detailed Description
Definition at line 44 of file ExecutionPipelineResourceTable.hh.
Member Typedef Documentation
ResourceTable
typedef std::vector<ResourceVector> ExecutionPipelineResourceTable::ResourceTable private
Type for resource reservation table, resource vector x latency.
Definition at line 83 of file ExecutionPipelineResourceTable.hh.
ResourceTableMap
typedef std::map<const TTAMachine::FunctionUnit*, ExecutionPipelineResourceTable*> ExecutionPipelineResourceTable::ResourceTableMap private
Definition at line 86 of file ExecutionPipelineResourceTable.hh.
ResourceVector
typedef std::vector<bool> ExecutionPipelineResourceTable::ResourceVector private
Type for resource vector, represents one cycle of use.
Definition at line 80 of file ExecutionPipelineResourceTable.hh.
Constructor & Destructor Documentation
ExecutionPipelineResourceTable()
ExecutionPipelineResourceTable::ExecutionPipelineResourceTable (const TTAMachine::FunctionUnit & fu) private
Definition at line 50 of file ExecutionPipelineResourceTable.cc.
                                      :
    name_(fu.name()),
    numberOfResources_(fu.pipelineElementCount() + fu.operationPortCount()),
    maximalLatency_(fu.maxLatency()) {
    for (int j = 0; j < fu.operationCount(); j++) {
        HWOperation& hwop = *fu.operation(j);
        ExecutionPipeline* ep = hwop.pipeline();
        std::string opName = StringTools::stringToUpper(
            fu.operation(j)->name());
        for (int l = 0; l < ep->latency(); l++ ) {
            for (int k = 0; k < fu.pipelineElementCount(); k++) {
                PipelineElement *pe = fu.pipelineElement(k);
                if (ep->isResourceUsed(pe->name(),l)){
                    setResourceUse(opName, l, k);
                }
            }
            for (int k = 0; k < fu.operationPortCount(); k++) {
                TTAMachine::FUPort* fuPort = fu.operationPort(k);
                if (ep->isPortWritten(*fuPort,l)) {
                    setResourceUse(
                        opName, l,fu.pipelineElementCount()+k);
                }
                if (ep->isPortRead(*fuPort,l)) {
                    setResourceUse(
                        opName, -1, fu.pipelineElementCount()+k);
                }
            }
        }
        // set operation latencies
        ExecutionPipeline::OperandSet writes = ep->writtenOperands();
        for (ExecutionPipeline::OperandSet::iterator iter =
                 writes.begin(); iter != writes.end(); iter++) {
            int index = *iter;
            int latency = hwop.latency(index);
            setLatency(opName, index, latency);
        }
    }
}
References TTAMachine::ExecutionPipeline::isPortRead(), TTAMachine::ExecutionPipeline::isPortWritten(), TTAMachine::ExecutionPipeline::isResourceUsed(), TTAMachine::ExecutionPipeline::latency(), TTAMachine::HWOperation::latency(), TTAMachine::HWOperation::name(), TTAMachine::PipelineElement::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::HWOperation::pipeline(), TTAMachine::FunctionUnit::pipelineElement(), TTAMachine::FunctionUnit::pipelineElementCount(), setLatency(), setResourceUse(), StringTools::stringToUpper(), and TTAMachine::ExecutionPipeline::writtenOperands().
Member Function Documentation
finalize()
void ExecutionPipelineResourceTable::finalize () static
Delete all the resource tables. This can be called after scheduling is done, when resource managers are longer used.
Definition at line 185 of file ExecutionPipelineResourceTable.cc.
{
    MapTools::deleteAllValues(allResourceTables_);
}
References allResourceTables_, and MapTools::deleteAllValues().
Referenced by SimpleResourceManager::disposeRM().
hasOperation()
bool ExecutionPipelineResourceTable::hasOperation (const std::string & opName) const inline
Referenced by ExecutionPipelineResource::resourcesAllowTrigger(), and ExecutionPipelineResource::unassignDestination().
maximalLatency()
unsigned int ExecutionPipelineResourceTable::maximalLatency () const inline
Referenced by ExecutionPipelineResource::assignDestination(), ExecutionPipelineResource::resourcesAllowTrigger(), and ExecutionPipelineResource::unassignDestination().
name()
const std::string & ExecutionPipelineResourceTable::name () const inline
numberOfResources()
unsigned int ExecutionPipelineResourceTable::numberOfResources () const inline
Referenced by ExecutionPipelineResource::assignDestination(), ExecutionPipelineResource::isInUse(), ExecutionPipelineResource::resourcesAllowTrigger(), ExecutionPipelineResource::size(), and ExecutionPipelineResource::unassignDestination().
operationIndex()
int ExecutionPipelineResourceTable::operationIndex (const std::string & opName) const inline
Referenced by ExecutionPipelineResource::assignDestination(), ExecutionPipelineResource::resourcesAllowTrigger(), and ExecutionPipelineResource::unassignDestination().
operationLatency()
const std::map< int, int > & ExecutionPipelineResourceTable::operationLatency (unsigned int operationIndex) const inline
operationPipeline()
bool ExecutionPipelineResourceTable::operationPipeline (int op, int cycle, int res) const inline
Referenced by ExecutionPipelineResource::assignDestination(), ExecutionPipelineResource::resourcesAllowTrigger(), and ExecutionPipelineResource::unassignDestination().
pipelineSize()
unsigned int ExecutionPipelineResourceTable::pipelineSize () const inline
resourceTable()
const ExecutionPipelineResourceTable & ExecutionPipelineResourceTable::resourceTable (const TTAMachine::FunctionUnit & fu) static
Gives an resource table for given FU. If no existing found, creates a new one.
Parameters
fu function unit whose resource table we are asking for.
Definition at line 164 of file ExecutionPipelineResourceTable.cc.
{
    ResourceTableMap::iterator i = allResourceTables_.find(&fu);
    if (i != allResourceTables_.end()) {
        return *i->second;
    }
    ExecutionPipelineResourceTable* newTable =
        new ExecutionPipelineResourceTable(fu);
    allResourceTables_[&fu] = newTable;
    return *newTable;
}
References allResourceTables_.
setLatency()
void ExecutionPipelineResourceTable::setLatency (const std::string & opName, const int output, const int latency) private
Sets latency of an output of an operation. The resource usage of the operation has to be set before calling this.
Parameters
opName operation to set the latency
output index of the output operand(stating from numberofinputoperand, not 0/1)
latency latency of the output of the operation
Definition at line 139 of file ExecutionPipelineResourceTable.cc.
                       {
    if (!MapTools::containsKey(operationSupported_, opName)) {
        ResourceTable newOp(maximalLatency_, std::vector<bool>(0, false));
        operationPipelines_.push_back(newOp);
        operationSupported_[opName] = operationPipelines_.size() - 1;
    }
    int pIndex = MapTools::valueForKey<int>(operationSupported_, opName);
    while (static_cast<int>(operationLatencies_.size()) <= pIndex) {
        operationLatencies_.push_back(std::map<int,int>());
    }
    operationLatencies_[pIndex][output] = latency;
}
References MapTools::containsKey(), MapTools::keyForValue(), maximalLatency_, operationLatencies_, operationPipelines_, and operationSupported_.
Referenced by ExecutionPipelineResourceTable().
setResourceUse()
void ExecutionPipelineResourceTable::setResourceUse (const std::string & opName, const int cycle, const int resIndex) private
Sets usage of resource/port to true for given cycle and resource number and particular pipeline.
Parameters
opName Name of operation to set resource for
cycle Cycle in which to set usage
index Index of resource/port in resource vector
Definition at line 102 of file ExecutionPipelineResourceTable.cc.
{
    if (cycle > (signed)maximalLatency_) {
        throw InvalidData(__FILE__, __LINE__, __func__,
            "Trying to set resource use to cycle out of scope of "
            "FU pipeline!");
    }
    if (resIndex >= numberOfResources_ || resIndex < 0){
        throw InvalidData(__FILE__, __LINE__, __func__,
            "Trying to set resource use for resource out of scope of "
            "FU pipeline!");
    }
    if (!MapTools::containsKey(operationSupported_, opName)) {
        ResourceTable newOp(
            maximalLatency_, std::vector<bool>(numberOfResources_, false));
        operationPipelines_.push_back(newOp);
        operationSupported_[opName] = operationPipelines_.size() - 1;
    }
    int pIndex = MapTools::valueForKey<int>(operationSupported_, opName);
    if(cycle > -1) {
        operationPipelines_[pIndex][cycle][resIndex] = true;
    }
}
References __func__, MapTools::containsKey(), MapTools::keyForValue(), maximalLatency_, numberOfResources_, operationPipelines_, and operationSupported_.
Referenced by ExecutionPipelineResourceTable().
Member Data Documentation
allResourceTables_
ExecutionPipelineResourceTable::ResourceTableMap ExecutionPipelineResourceTable::allResourceTables_ static private
Contains these tables for all FU's.
Definition at line 100 of file ExecutionPipelineResourceTable.hh.
Referenced by finalize(), and resourceTable().
maximalLatency_
unsigned int ExecutionPipelineResourceTable::maximalLatency_ private
Maximal latency of operation in FU.
Definition at line 91 of file ExecutionPipelineResourceTable.hh.
Referenced by setLatency(), and setResourceUse().
name_
std::string ExecutionPipelineResourceTable::name_ private
Definition at line 77 of file ExecutionPipelineResourceTable.hh.
numberOfResources_
int ExecutionPipelineResourceTable::numberOfResources_ private
Resource and ports vector width, depends on particular FU.
Definition at line 89 of file ExecutionPipelineResourceTable.hh.
Referenced by setResourceUse().
operationLatencies_
std::vector<std::map<int,int> > ExecutionPipelineResourceTable::operationLatencies_ private
Definition at line 95 of file ExecutionPipelineResourceTable.hh.
Referenced by setLatency().
operationPipelines_
std::vector<ResourceTable> ExecutionPipelineResourceTable::operationPipelines_ private
Pipelines for operations.
Definition at line 97 of file ExecutionPipelineResourceTable.hh.
Referenced by setLatency(), and setResourceUse().
operationSupported_
std::map<std::string, int> ExecutionPipelineResourceTable::operationSupported_ private
Operations supported, name - index to operation pipeline vector.
Definition at line 93 of file ExecutionPipelineResourceTable.hh.
Referenced by setLatency(), and setResourceUse().
The documentation for this class was generated from the following files:
ExecutionPipelineResourceTable.hh
ExecutionPipelineResourceTable.cc