OpenASIP: BreakpointPropertiesDialog Class Reference
BreakpointPropertiesDialog Class Reference
#include <BreakpointPropertiesDialog.hh>
Public Member Functions
BreakpointPropertiesDialog (wxWindow *parent, StopPointManager &manager, unsigned int handle)
virtual ~BreakpointPropertiesDialog ()
Private Types
enum {
ID_TEXT_BREAKPOINT = 10000 , ID_TEXT_BP_ID , ID_LABEL_CONDITION , ID_CONDITION ,
ID_LABEL_IGNORE_COUNT , ID_IGNORE_CTRL , ID_LINE , ID_HELP ,
ID_CLOSE
}
Widget IDs.
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
Private Attributes
StopPointManager & manager_
Stoppoint manager containing the breakpoint,.
unsigned int handle_
Handle of the breakpoint to modify.
Detailed Description
Dialog for editing breakpoint properties in Proxim.
Definition at line 45 of file BreakpointPropertiesDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_TEXT_BREAKPOINT
ID_TEXT_BP_ID
ID_LABEL_CONDITION
ID_CONDITION
ID_LABEL_IGNORE_COUNT
ID_IGNORE_CTRL
ID_LINE
ID_HELP
ID_CLOSE
Definition at line 56 of file BreakpointPropertiesDialog.hh.
         {
        ID_TEXT_BREAKPOINT = 10000,
        ID_TEXT_BP_ID,
        ID_LABEL_CONDITION,
        ID_CONDITION,
        ID_LABEL_IGNORE_COUNT,
        ID_IGNORE_CTRL,
        ID_LINE,
        ID_HELP,
        ID_CLOSE
    };
Constructor & Destructor Documentation
BreakpointPropertiesDialog()
BreakpointPropertiesDialog::BreakpointPropertiesDialog (wxWindow * parent, StopPointManager & manager, unsigned int handle)
The Constructor.
Parameters
parent Parent window of the dialog.
breakpoint Breakpoint to edit.
Definition at line 57 of file BreakpointPropertiesDialog.cc.
                                                                      :
  wxDialog(parent, -1, _T("Breakpoint properties"), wxDefaultPosition),
    manager_(manager), handle_(handle) {
    createContents(this, true, true);
}
~BreakpointPropertiesDialog()
BreakpointPropertiesDialog::~BreakpointPropertiesDialog () virtual
The Destructor.
Definition at line 70 of file BreakpointPropertiesDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * BreakpointPropertiesDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Definition at line 151 of file BreakpointPropertiesDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT_BREAKPOINT, wxT("Breakpoint"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT_BP_ID, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_IGNORE_COUNT, wxT("Ignore count:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item5 = new wxSpinCtrl( parent, ID_IGNORE_CTRL, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item1->Add( item5, 0, wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_CONDITION, wxT("Condition:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_CONDITION, wxT(""), wxDefaultPosition, wxSize(250,-1));
    item1->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxGROW, 5 );
    wxStaticLine *item8 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item8, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item9 = new wxGridSizer( 2, 0, 0 );
    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item9, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CONDITION, ID_IGNORE_CTRL, ID_LABEL_CONDITION, ID_LABEL_IGNORE_COUNT, ID_LINE, ID_TEXT_BP_ID, and ID_TEXT_BREAKPOINT.
onOK()
void BreakpointPropertiesDialog::onOK (wxCommandEvent & event) private
Handles the dialog OK-button event.
Breakpoint properties are checked for validity, and the breakpoint is modified if the properties are valid. An error dialog is displayed if the breakpoint properties are invalid.
Definition at line 110 of file BreakpointPropertiesDialog.cc.
{
    wxTextCtrl* conditionCtrl =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_CONDITION));
    unsigned ignoreCount =
        dynamic_cast<wxSpinCtrl*>(FindWindow(ID_IGNORE_CTRL))->GetValue();
    string condition = WxConversion::toString(
        conditionCtrl->GetValue().Trim(true).Trim(false));
    // Check condition script.
    if (condition != "" && !ProximToolbox::testCondition(this, condition)) {
        // Invalid condition.
        return;
    }
    ProximLineReader& lineReader = ProximToolbox::lineReader();
    // Set ignore count.
    std::string ignoreCommand = ProximConstants::SCL_SET_IGNORE_COUNT +
        " " + Conversion::toString(handle_) +
        " " + Conversion::toString(ignoreCount);
    lineReader.input(ignoreCommand);
    // Set Condition script.
    std::string conditionCommand = ProximConstants::SCL_SET_CONDITION + " " +
        Conversion::toString(handle_);
    lineReader.input(conditionCommand);
    lineReader.input(condition);
    EndModal(wxID_OK);
}
References handle_, ID_CONDITION, ID_IGNORE_CTRL, ProximLineReader::input(), ProximToolbox::lineReader(), ProximConstants::SCL_SET_CONDITION, ProximConstants::SCL_SET_IGNORE_COUNT, ProximToolbox::testCondition(), Conversion::toString(), and WxConversion::toString().
TransferDataToWindow()
bool BreakpointPropertiesDialog::TransferDataToWindow () private virtual
Sets the widget values when the dialog is opened.
Definition at line 78 of file BreakpointPropertiesDialog.cc.
{
    const Breakpoint& breakpoint = dynamic_cast<const Breakpoint&>(
        manager_.stopPointWithHandleConst(handle_));
    if (breakpoint.isConditional()) {
        wxTextCtrl* conditionCtrl =
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_CONDITION));
        for (unsigned i = 0; i < breakpoint.condition().script().size(); i++) {
            string line = breakpoint.condition().script()[i];
            conditionCtrl->AppendText(WxConversion::toWxString(line));
        }
    }
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_IGNORE_CTRL))->SetValue(
        breakpoint.ignoreCount());
    dynamic_cast<wxStaticText*>(FindWindow(ID_TEXT_BP_ID))->SetLabel(
        WxConversion::toWxString(handle_));
    return wxDialog::TransferDataToWindow();
}
References StopPoint::condition(), handle_, ID_CONDITION, ID_IGNORE_CTRL, ID_TEXT_BP_ID, StopPoint::ignoreCount(), StopPoint::isConditional(), manager_, Script::script(), StopPointManager::stopPointWithHandleConst(), and WxConversion::toWxString().
Member Data Documentation
handle_
unsigned int BreakpointPropertiesDialog::handle_ private
Handle of the breakpoint to modify.
Definition at line 70 of file BreakpointPropertiesDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
manager_
StopPointManager& BreakpointPropertiesDialog::manager_ private
Stoppoint manager containing the breakpoint,.
Definition at line 68 of file BreakpointPropertiesDialog.hh.
Referenced by TransferDataToWindow().
The documentation for this class was generated from the following files:
BreakpointPropertiesDialog.hh
BreakpointPropertiesDialog.cc