OpenASIP: llvm::TCETargetMachinePlugin Class Reference
llvm::TCETargetMachinePlugin Class Reference abstract
#include <TCETargetMachinePlugin.hh>
Public Member Functions
TCETargetMachinePlugin ()
virtual ~TCETargetMachinePlugin ()
virtual const TargetInstrInfo * getInstrInfo () const =0
virtual const TargetRegisterInfo * getRegisterInfo () const =0
virtual const TargetFrameLowering * getFrameLowering () const =0
virtual TargetLowering * getTargetLowering () const =0
virtual const TargetSubtargetInfo * getSubtarget () const =0
virtual TargetTransformInfo getTargetTransformInfo (const Function &F) const =0
virtual FunctionPass * createISelPass (TCETargetMachine *tm)=0
virtual std::string rfName (unsigned dwarfRegNum)=0
Returns name of the physical register file corresponding to a generated register ID.
virtual unsigned registerIndex (unsigned dwarfRegNum)=0
Returns name of the physical register index corresponding to a generated register ID.
virtual unsigned llvmRegisterId (const TCEString &ttaRegister)=0
virtual std::string operationName (unsigned opc) const =0
Returns operation name corresponding to llvm target opcode.
virtual bool validStackAccessOperation (const std::string &opName) const =0
Returns true if OSAL operation is valid for stack accesses.
virtual bool hasOperation (TCEString operationName) const =0
Returns true in case the target supports the given osal operation.
virtual unsigned opcode (TCEString operationName) const =0
Returns the opcode for the given osal operation, undefined if not found.
virtual unsigned int extractElementLane (const MachineInstr &mi) const =0
virtual int getTruePredicateOpcode (unsigned opc) const =0
virtual int getFalsePredicateOpcode (unsigned opc) const =0
virtual std::string dataASName ()=0
Returns name of the data address space.
virtual unsigned raPortDRegNum ()=0
Returns ID number of the return address register.
virtual unsigned spDRegNum ()=0
Returns ID number of the stack pointer register.
virtual unsigned fpDRegNum ()=0
Returns ID number of the frame pointer register.
virtual unsigned rvDRegNum ()=0
virtual unsigned rvHighDRegNum ()=0
virtual std::vector< unsigned > getParamDRegNums () const =0
virtual std::vector< unsigned > getVectorRVDRegNums () const =0
virtual bool hasUDIV () const =0
virtual bool hasSDIV () const =0
virtual bool hasUREM () const =0
virtual bool hasSREM () const =0
virtual bool hasMUL () const =0
virtual bool hasROTL () const =0
virtual bool hasROTR () const =0
virtual bool hasSXHW () const =0
virtual bool hasSXQW () const =0
virtual bool hasSQRTF () const =0
virtual bool hasSHR () const =0
virtual bool hasSHL () const =0
virtual bool hasSHRU () const =0
virtual bool has8bitLoads () const =0
virtual bool has16bitLoads () const =0
virtual int maxVectorSize () const =0
virtual void registerTargetMachine (TCETargetMachine &tm)=0
Plugin needs target machine for TragetLowering generation.
virtual int getMinOpcode (llvm::SDNode *n) const =0
virtual int getMaxOpcode (llvm::SDNode *n) const =0
virtual int getMinuOpcode (llvm::SDNode *n) const =0
virtual int getMaxuOpcode (llvm::SDNode *n) const =0
virtual int getLoad (const TargetRegisterClass *rc) const =0
virtual int getStore (const TargetRegisterClass *rc) const =0
virtual int getLoadOpcode (const llvm::EVT &vt) const =0
virtual int getAddOpcode (const llvm::EVT &vt) const =0
virtual int getShlOpcode (const llvm::EVT &vt) const =0
virtual int getIorOpcode (const llvm::EVT &vt) const =0
virtual const llvm::TargetRegisterClass * extrasRegClass (const llvm::TargetRegisterClass *current) const =0
Clustered-TTA-subtemplate related methods.
virtual const llvm::TargetRegisterClass * nodeRegClass (unsigned nodeId, const llvm::TargetRegisterClass *current) const =0
virtual bool isLittleEndian () const =0
virtual bool is64bit () const =0
virtual const DataLayout * getDataLayout () const
virtual DataLayout * getDataLayout ()
virtual TCETargetMachine * getCurrentTargetMachine ()
virtual const TCETargetMachine * getCurrentTargetMachine () const
virtual bool analyzeCCBranch (llvm::MachineInstr &i, llvm::SmallVectorImpl< llvm::MachineOperand > &cond) const
virtual const SelectionDAGTargetInfo * getSelectionDAGInfo () const
virtual bool canMaterializeConstant (const ConstantInt &ci) const =0
virtual std::tuple< int, int > getPointerAdjustment (int offset) const =0
virtual MVT::SimpleValueType getDefaultType () const =0
Protected Attributes
TCEInstrInfo * instrInfo_
Target machine instruction info for the llvm framework.
TargetLowering * lowering_
TargetFrameLowering * frameInfo_
TCETargetMachine * tm_
TCESubtarget * subTarget_
DataLayout dl_
SelectionDAGTargetInfo tsInfo_
Detailed Description
Definition at line 109 of file TCETargetMachinePlugin.hh.
Constructor & Destructor Documentation
TCETargetMachinePlugin()
llvm::TCETargetMachinePlugin::TCETargetMachinePlugin () inline
Definition at line 112 of file TCETargetMachinePlugin.hh.
                                : lowering_(NULL), tm_(NULL),
                                  dl_(TCELE64DLString) {};
~TCETargetMachinePlugin()
virtual llvm::TCETargetMachinePlugin::~TCETargetMachinePlugin () inline virtual
Definition at line 116 of file TCETargetMachinePlugin.hh.
{};
Member Function Documentation
analyzeCCBranch()
virtual bool llvm::TCETargetMachinePlugin::analyzeCCBranch (llvm::MachineInstr & i, llvm::SmallVectorImpl< llvm::MachineOperand > & cond) const inline virtual
Reimplemented in llvm::GeneratedTCEPlugin.
Definition at line 236 of file TCETargetMachinePlugin.hh.
{
           return true;
       }
Referenced by llvm::TCEInstrInfo::analyzeBranch().
canMaterializeConstant()
virtual bool llvm::TCETargetMachinePlugin::canMaterializeConstant (const ConstantInt & ci) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::canMaterializeConstant().
createISelPass()
virtual FunctionPass * llvm::TCETargetMachinePlugin::createISelPass (TCETargetMachine * tm) pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEPassConfig::addInstSelector().
dataASName()
virtual std::string llvm::TCETargetMachinePlugin::dataASName () pure virtual
Returns name of the data address space.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::dataASName().
extractElementLane()
virtual unsigned int llvm::TCETargetMachinePlugin::extractElementLane (const MachineInstr & mi) const pure virtual
extrasRegClass()
virtual const llvm::TargetRegisterClass * llvm::TCETargetMachinePlugin::extrasRegClass (const llvm::TargetRegisterClass * current) const pure virtual
Clustered-TTA-subtemplate related methods.
Implemented in llvm::GeneratedTCEPlugin.
fpDRegNum()
virtual unsigned llvm::TCETargetMachinePlugin::fpDRegNum () pure virtual
Returns ID number of the frame pointer register.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile().
getAddOpcode()
virtual int llvm::TCETargetMachinePlugin::getAddOpcode (const llvm::EVT & vt) const pure virtual
Referenced by llvm::TCETargetMachine::getAddOpcode().
getCurrentTargetMachine() [1/2]
virtual TCETargetMachine * llvm::TCETargetMachinePlugin::getCurrentTargetMachine () inline virtual
Definition at line 229 of file TCETargetMachinePlugin.hh.
{
            return tm_;
        }
References tm_.
getCurrentTargetMachine() [2/2]
virtual const TCETargetMachine * llvm::TCETargetMachinePlugin::getCurrentTargetMachine () const inline virtual
Definition at line 232 of file TCETargetMachinePlugin.hh.
{
            return tm_;
        }
References tm_.
getDataLayout() [1/2]
virtual DataLayout * llvm::TCETargetMachinePlugin::getDataLayout () inline virtual
Definition at line 225 of file TCETargetMachinePlugin.hh.
{
           return &dl_;
       }
References dl_.
getDataLayout() [2/2]
virtual const DataLayout * llvm::TCETargetMachinePlugin::getDataLayout () const inline virtual
Definition at line 221 of file TCETargetMachinePlugin.hh.
{
           return &dl_;
       }
References dl_.
Referenced by llvm::TCETargetMachine::getDataLayout(), and llvm::TCETargetMachine::setTargetMachinePlugin().
getDefaultType()
virtual MVT::SimpleValueType llvm::TCETargetMachinePlugin::getDefaultType () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
getFalsePredicateOpcode()
virtual int llvm::TCETargetMachinePlugin::getFalsePredicateOpcode (unsigned opc) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::getMatchingCondBranchOpcode().
getFrameLowering()
virtual const TargetFrameLowering * llvm::TCETargetMachinePlugin::getFrameLowering () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getFrameLowering(), and llvm::TCESubtarget::getFrameLowering().
getInstrInfo()
virtual const TargetInstrInfo * llvm::TCETargetMachinePlugin::getInstrInfo () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getInstrInfo(), and llvm::TCESubtarget::getInstrInfo().
getIorOpcode()
virtual int llvm::TCETargetMachinePlugin::getIorOpcode (const llvm::EVT & vt) const pure virtual
Referenced by llvm::TCETargetMachine::getIorOpcode().
getLoad()
virtual int llvm::TCETargetMachinePlugin::getLoad (const TargetRegisterClass * rc) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::loadRegFromStackSlot().
getLoadOpcode()
virtual int llvm::TCETargetMachinePlugin::getLoadOpcode (const llvm::EVT & vt) const pure virtual
Referenced by llvm::TCETargetMachine::getLoadOpcode().
getMaxOpcode()
virtual int llvm::TCETargetMachinePlugin::getMaxOpcode (llvm::SDNode * n) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getMaxOpcode().
getMaxuOpcode()
virtual int llvm::TCETargetMachinePlugin::getMaxuOpcode (llvm::SDNode * n) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getMaxuOpcode().
getMinOpcode()
virtual int llvm::TCETargetMachinePlugin::getMinOpcode (llvm::SDNode * n) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getMinOpcode().
getMinuOpcode()
virtual int llvm::TCETargetMachinePlugin::getMinuOpcode (llvm::SDNode * n) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getMinuOpcode().
getParamDRegNums()
virtual std::vector< unsigned > llvm::TCETargetMachinePlugin::getParamDRegNums () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile().
getPointerAdjustment()
virtual std::tuple< int, int > llvm::TCETargetMachinePlugin::getPointerAdjustment (int offset) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::getPointerAdjustment().
getRegisterInfo()
virtual const TargetRegisterInfo * llvm::TCETargetMachinePlugin::getRegisterInfo () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getRegisterInfo(), and llvm::TCESubtarget::getRegisterInfo().
getSelectionDAGInfo()
virtual const SelectionDAGTargetInfo * llvm::TCETargetMachinePlugin::getSelectionDAGInfo () const inline virtual
Definition at line 242 of file TCETargetMachinePlugin.hh.
{
           return &tsInfo_;
       }
References tsInfo_.
Referenced by llvm::TCESubtarget::getSelectionDAGInfo().
getShlOpcode()
virtual int llvm::TCETargetMachinePlugin::getShlOpcode (const llvm::EVT & vt) const pure virtual
Referenced by llvm::TCETargetMachine::getShlOpcode().
getStore()
virtual int llvm::TCETargetMachinePlugin::getStore (const TargetRegisterClass * rc) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::storeRegToStackSlot().
getSubtarget()
virtual const TargetSubtargetInfo * llvm::TCETargetMachinePlugin::getSubtarget () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getSubtargetImpl(), and llvm::TCETargetMachine::getSubtargetImpl().
getTargetLowering()
virtual TargetLowering * llvm::TCETargetMachinePlugin::getTargetLowering () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getTargetLowering(), and llvm::TCESubtarget::getTargetLowering().
getTargetTransformInfo()
virtual TargetTransformInfo llvm::TCETargetMachinePlugin::getTargetTransformInfo (const Function & F) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::getTargetTransformInfo().
getTruePredicateOpcode()
virtual int llvm::TCETargetMachinePlugin::getTruePredicateOpcode (unsigned opc) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::getMatchingCondBranchOpcode().
getVectorRVDRegNums()
virtual std::vector< unsigned > llvm::TCETargetMachinePlugin::getVectorRVDRegNums () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile().
has16bitLoads()
virtual bool llvm::TCETargetMachinePlugin::has16bitLoads () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::has16bitLoads().
has8bitLoads()
virtual bool llvm::TCETargetMachinePlugin::has8bitLoads () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::has8bitLoads().
hasMUL()
virtual bool llvm::TCETargetMachinePlugin::hasMUL () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasOperation()
virtual bool llvm::TCETargetMachinePlugin::hasOperation (TCEString operationName) const pure virtual
Returns true in case the target supports the given osal operation.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::hasOperation().
hasROTL()
virtual bool llvm::TCETargetMachinePlugin::hasROTL () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasROTR()
virtual bool llvm::TCETargetMachinePlugin::hasROTR () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSDIV()
virtual bool llvm::TCETargetMachinePlugin::hasSDIV () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSHL()
virtual bool llvm::TCETargetMachinePlugin::hasSHL () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSHR()
virtual bool llvm::TCETargetMachinePlugin::hasSHR () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSHRU()
virtual bool llvm::TCETargetMachinePlugin::hasSHRU () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSQRTF()
virtual bool llvm::TCETargetMachinePlugin::hasSQRTF () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSREM()
virtual bool llvm::TCETargetMachinePlugin::hasSREM () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSXHW()
virtual bool llvm::TCETargetMachinePlugin::hasSXHW () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasSXQW()
virtual bool llvm::TCETargetMachinePlugin::hasSXQW () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasUDIV()
virtual bool llvm::TCETargetMachinePlugin::hasUDIV () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
hasUREM()
virtual bool llvm::TCETargetMachinePlugin::hasUREM () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
is64bit()
virtual bool llvm::TCETargetMachinePlugin::is64bit () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::bitness().
isLittleEndian()
virtual bool llvm::TCETargetMachinePlugin::isLittleEndian () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
llvmRegisterId()
virtual unsigned llvm::TCETargetMachinePlugin::llvmRegisterId (const TCEString & ttaRegister) pure virtual
Returns LLVM register ID corresponding to TTA register name.
Parameters
ttaRegister The name of the TTA register. For example "RF.5".
Returns
The register number if it exists in the target. Otherwise, returns TCE::NoRegister.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::llvmRegisterId().
maxVectorSize()
virtual int llvm::TCETargetMachinePlugin::maxVectorSize () const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
nodeRegClass()
virtual const llvm::TargetRegisterClass * llvm::TCETargetMachinePlugin::nodeRegClass (unsigned nodeId, const llvm::TargetRegisterClass * current) const pure virtual
Implemented in llvm::GeneratedTCEPlugin.
opcode()
virtual unsigned llvm::TCETargetMachinePlugin::opcode (TCEString operationName) const pure virtual
Returns the opcode for the given osal operation, undefined if not found.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::opcode(), and ConstantTransformer::runOnMachineFunction().
operationName()
virtual std::string llvm::TCETargetMachinePlugin::operationName (unsigned opc) const pure virtual
Returns operation name corresponding to llvm target opcode.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCEInstrInfo::isPredicated(), and llvm::TCETargetMachine::operationName().
raPortDRegNum()
virtual unsigned llvm::TCETargetMachinePlugin::raPortDRegNum () pure virtual
Returns ID number of the return address register.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::raPortDRegNum().
registerIndex()
virtual unsigned llvm::TCETargetMachinePlugin::registerIndex (unsigned dwarfRegNum) pure virtual
Returns name of the physical register index corresponding to a generated register ID.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile(), and llvm::TCETargetMachine::registerIndex().
registerTargetMachine()
virtual void llvm::TCETargetMachinePlugin::registerTargetMachine (TCETargetMachine & tm) pure virtual
Plugin needs target machine for TragetLowering generation.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::setTargetMachinePlugin().
rfName()
virtual std::string llvm::TCETargetMachinePlugin::rfName (unsigned dwarfRegNum) pure virtual
Returns name of the physical register file corresponding to a generated register ID.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile(), and llvm::TCETargetMachine::rfName().
rvDRegNum()
virtual unsigned llvm::TCETargetMachinePlugin::rvDRegNum () pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile().
rvHighDRegNum()
virtual unsigned llvm::TCETargetMachinePlugin::rvHighDRegNum () pure virtual
Implemented in llvm::GeneratedTCEPlugin.
Referenced by ConstantTransformer::runOnMachineFunction().
spDRegNum()
virtual unsigned llvm::TCETargetMachinePlugin::spDRegNum () pure virtual
Returns ID number of the stack pointer register.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by LLVMBackend::compile(), and llvm::TCETargetMachine::spDRegNum().
validStackAccessOperation()
virtual bool llvm::TCETargetMachinePlugin::validStackAccessOperation (const std::string & opName) const pure virtual
Returns true if OSAL operation is valid for stack accesses.
Implemented in llvm::GeneratedTCEPlugin.
Referenced by llvm::TCETargetMachine::validStackAccessOperation().
Member Data Documentation
dl_
DataLayout llvm::TCETargetMachinePlugin::dl_ protected
Definition at line 260 of file TCETargetMachinePlugin.hh.
Referenced by getDataLayout(), and getDataLayout().
frameInfo_
TargetFrameLowering* llvm::TCETargetMachinePlugin::frameInfo_ protected
Definition at line 257 of file TCETargetMachinePlugin.hh.
Referenced by llvm::GeneratedTCEPlugin::getFrameLowering(), and llvm::GeneratedTCEPlugin::registerTargetMachine().
instrInfo_
TCEInstrInfo* llvm::TCETargetMachinePlugin::instrInfo_ protected
Target machine instruction info for the llvm framework.
Definition at line 255 of file TCETargetMachinePlugin.hh.
Referenced by llvm::GeneratedTCEPlugin::getInstrInfo(), llvm::GeneratedTCEPlugin::getRegisterInfo(), llvm::GeneratedTCEPlugin::registerTargetMachine(), and llvm::GeneratedTCEPlugin::~GeneratedTCEPlugin().
lowering_
TargetLowering* llvm::TCETargetMachinePlugin::lowering_ protected
Definition at line 256 of file TCETargetMachinePlugin.hh.
Referenced by llvm::GeneratedTCEPlugin::GeneratedTCEPlugin(), llvm::GeneratedTCEPlugin::getTargetLowering(), llvm::GeneratedTCEPlugin::registerTargetMachine(), and llvm::GeneratedTCEPlugin::~GeneratedTCEPlugin().
subTarget_
TCESubtarget* llvm::TCETargetMachinePlugin::subTarget_ protected
Definition at line 259 of file TCETargetMachinePlugin.hh.
Referenced by llvm::GeneratedTCEPlugin::getSubtarget(), and llvm::GeneratedTCEPlugin::registerTargetMachine().
tm_
TCETargetMachine* llvm::TCETargetMachinePlugin::tm_ protected
Definition at line 258 of file TCETargetMachinePlugin.hh.
Referenced by getCurrentTargetMachine(), getCurrentTargetMachine(), llvm::GeneratedTCEPlugin::getTargetTransformInfo(), and llvm::GeneratedTCEPlugin::registerTargetMachine().
tsInfo_
SelectionDAGTargetInfo llvm::TCETargetMachinePlugin::tsInfo_ protected
Definition at line 261 of file TCETargetMachinePlugin.hh.
Referenced by getSelectionDAGInfo().
The documentation for this class was generated from the following file:
TCETargetMachinePlugin.hh