OpenASIP: GUITextGenerator Class Reference
GUITextGenerator Class Reference
#include <GUITextGenerator.hh>
Public Types
enum {
TXT_BUTTON_ADD = Texts::LAST__ , TXT_BUTTON_ADD_DIALOG , TXT_BUTTON_CANCEL , TXT_BUTTON_DELETE ,
TXT_BUTTON_EDIT , TXT_BUTTON_EDIT_DIALOG , TXT_BUTTON_OK , TXT_BUTTON_HELP
}
Ids for the generated texts.
Static Public Member Functions
static GUITextGenerator * instance ()
static void destroy ()
Private Member Functions
GUITextGenerator ()
~GUITextGenerator ()
Static Private Attributes
static GUITextGenerator * instance_ = NULL
Additional Inherited Members
Public Member Functions inherited from Texts::TextGenerator
TextGenerator ()
virtual ~TextGenerator ()
virtual boost::format text (int textId)
virtual void addText (int textId, const std::string &templateString)
virtual void replaceText (int textId, const std::string &newString)
Detailed Description
Provides common texts for tce graphical user interfaces.
The class is implemented using the 'singleton' design pattern. Only one instance of this class is created, and the instance can be accessed using the instance() method.
Definition at line 46 of file GUITextGenerator.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Ids for the generated texts.
Enumerator
TXT_BUTTON_ADD
Label for an add button.
TXT_BUTTON_ADD_DIALOG
Label for add button (with trailing ...).
TXT_BUTTON_CANCEL
Label for cancel button.
TXT_BUTTON_DELETE
Label for delete button.
TXT_BUTTON_EDIT
Label for edit button.
TXT_BUTTON_EDIT_DIALOG
Label for edit button (with trailing ...).
TXT_BUTTON_OK
Label for OK button.
TXT_BUTTON_HELP
Label for help button.
Definition at line 52 of file GUITextGenerator.hh.
         {
        TXT_BUTTON_ADD = Texts::LAST__, ///< Label for an add button.
        TXT_BUTTON_ADD_DIALOG,  ///< Label for add button (with trailing ...).
        TXT_BUTTON_CANCEL,      ///< Label for cancel button.
        TXT_BUTTON_DELETE,      ///< Label for delete button.
        TXT_BUTTON_EDIT,        ///< Label for edit button.
        TXT_BUTTON_EDIT_DIALOG, ///< Label for edit button (with trailing ...).
        TXT_BUTTON_OK,          ///< Label for OK button.
        TXT_BUTTON_HELP         ///< Label for help button.
    };
Constructor & Destructor Documentation
GUITextGenerator()
GUITextGenerator::GUITextGenerator () private
The Constructor.
Initializes string templates to the text generator.
Definition at line 42 of file GUITextGenerator.cc.
{
    addText(TXT_BUTTON_ADD, "Add");
    addText(TXT_BUTTON_ADD_DIALOG, "Add...");
    addText(TXT_BUTTON_CANCEL, "&Cancel");
    addText(TXT_BUTTON_DELETE, "Delete");
    addText(TXT_BUTTON_EDIT, "Edit");
    addText(TXT_BUTTON_EDIT_DIALOG, "Edit...");
    addText(TXT_BUTTON_HELP, "&Help");
    addText(TXT_BUTTON_OK, "&OK");
}
References Texts::TextGenerator::addText(), TXT_BUTTON_ADD, TXT_BUTTON_ADD_DIALOG, TXT_BUTTON_CANCEL, TXT_BUTTON_DELETE, TXT_BUTTON_EDIT, TXT_BUTTON_EDIT_DIALOG, TXT_BUTTON_HELP, and TXT_BUTTON_OK.
Referenced by instance().
~GUITextGenerator()
GUITextGenerator::~GUITextGenerator () private
The Destructor.
Definition at line 57 of file GUITextGenerator.cc.
{
}
Member Function Documentation
destroy()
void GUITextGenerator::destroy () static
Deletes the instance of this command if one exists.
Definition at line 79 of file GUITextGenerator.cc.
{
    if (instance_ != NULL) {
        delete instance_;
        instance_ = NULL;
    }
}
References instance_.
instance()
GUITextGenerator * GUITextGenerator::instance () static
Returns the only instance of this class.
Returns
The singleton instance of GUITextGenerator class.
Definition at line 67 of file GUITextGenerator.cc.
{
    if (instance_ == NULL) {
        instance_ = new GUITextGenerator();
    }
    return instance_;
}
References GUITextGenerator(), and instance_.
Referenced by GCUDialog::setLabels(), AddModuleDialog::setTexts(), InputOperandDialog::setTexts(), OperationPropertyDialog::setTexts(), OSEdAboutDialog::setTexts(), OSEdOptionsDialog::setTexts(), OutputOperandDialog::setTexts(), ResultDialog::setTexts(), SimulateDialog::setTexts(), AboutDialog::setTexts(), AddressSpaceDialog::setTexts(), AddressSpacesDialog::setTexts(), BridgeDialog::setTexts(), BusDialog::setTexts(), FUDialog::setTexts(), FUGuardDialog::setTexts(), FUPortDialog::setTexts(), ImmediateSlotDialog::setTexts(), IUDialog::setTexts(), IUPortDialog::setTexts(), OperationDialog::setTexts(), OTAFormatListDialog::setTexts(), RFDialog::setTexts(), RFGuardDialog::setTexts(), RFPortDialog::setTexts(), SocketDialog::setTexts(), SRPortDialog::setTexts(), TemplateListDialog::setTexts(), and TemplateSlotDialog::setTexts().
Member Data Documentation
instance_
GUITextGenerator * GUITextGenerator::instance_ = NULL static private
Definition at line 66 of file GUITextGenerator.hh.
Referenced by destroy(), and instance().
The documentation for this class was generated from the following files:
GUITextGenerator.hh
GUITextGenerator.cc