OpenASIP: TTAUnitTesterCmdLineOptions Class Reference
TTAUnitTesterCmdLineOptions Class Reference
#include <TTAUnitTesterCmdLineOptions.hh>
Public Member Functions
TTAUnitTesterCmdLineOptions ()
~TTAUnitTesterCmdLineOptions ()
bool verbose () const
bool leaveDirty () const
std::string vhdlSim () const
std::string adfFileName () const
std::string idfFileName () const
void printVersion () const
void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Static Private Attributes
static const std::string VERBOSE_PARAM_NAME = "verbose"
Long name of verbose output parameter.
static const std::string DIRTY_PARAM_NAME
Long name of leave dirty parameter.
static const std::string SIM_PARAM_NAME = "simulator"
Long name of VHDL simulator parameter.
static const std::string ADF_PARAM_NAME = "adf"
Long name of ADF file parameter.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Definition at line 39 of file TTAUnitTesterCmdLineOptions.hh.
Constructor & Destructor Documentation
TTAUnitTesterCmdLineOptions()
TTAUnitTesterCmdLineOptions::TTAUnitTesterCmdLineOptions ()
Definition at line 44 of file TTAUnitTesterCmdLineOptions.cc.
                                                        :
    CmdLineOptions("") {
    BoolCmdLineOptionParser* verbose =
        new BoolCmdLineOptionParser(
            VERBOSE_PARAM_NAME, "Enable verbose output", "v");
    addOption(verbose);
    BoolCmdLineOptionParser* dirty =
        new BoolCmdLineOptionParser(
            DIRTY_PARAM_NAME, "Don't delete created files", "d");
    addOption(dirty);
    StringCmdLineOptionParser* simulator =
        new StringCmdLineOptionParser(
            SIM_PARAM_NAME, "HDL simulator used to simulate testbench. "
            "Accepted values are 'ghdl' and 'modelsim'. Default is ghdl",
            "s");
    addOption(simulator);
    StringCmdLineOptionParser* adfFile =
        new StringCmdLineOptionParser(
            ADF_PARAM_NAME, "If ADF file is given IDF will be validated",
            "a");
    addOption(adfFile);
}
References CmdLineParser::addOption(), ADF_PARAM_NAME, DIRTY_PARAM_NAME, SIM_PARAM_NAME, verbose(), and VERBOSE_PARAM_NAME.
~TTAUnitTesterCmdLineOptions()
TTAUnitTesterCmdLineOptions::~TTAUnitTesterCmdLineOptions ()
Definition at line 69 of file TTAUnitTesterCmdLineOptions.cc.
{
}
Member Function Documentation
adfFileName()
std::string TTAUnitTesterCmdLineOptions::adfFileName () const
Definition at line 95 of file TTAUnitTesterCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(ADF_PARAM_NAME);
    return option->String();
}
References ADF_PARAM_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::String().
idfFileName()
std::string TTAUnitTesterCmdLineOptions::idfFileName () const
Definition at line 102 of file TTAUnitTesterCmdLineOptions.cc.
{
     return argument(numberOfArguments());
}
References CmdLineParser::argument(), and CmdLineParser::numberOfArguments().
leaveDirty()
bool TTAUnitTesterCmdLineOptions::leaveDirty () const
Definition at line 81 of file TTAUnitTesterCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(DIRTY_PARAM_NAME);
    return option->isFlagOn();
}
References DIRTY_PARAM_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
printHelp()
void TTAUnitTesterCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Reimplemented from CmdLineOptions.
Definition at line 114 of file TTAUnitTesterCmdLineOptions.cc.
{
    printVersion();
    std::cout << "Usage: ttaunittester <options> IDF-file" << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void TTAUnitTesterCmdLineOptions::printVersion () const virtual
Implements CmdLineOptions.
Definition at line 107 of file TTAUnitTesterCmdLineOptions.cc.
{
    std::cout << "ttaunittester "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
verbose()
bool TTAUnitTesterCmdLineOptions::verbose () const
Definition at line 74 of file TTAUnitTesterCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(VERBOSE_PARAM_NAME);
    return option->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and VERBOSE_PARAM_NAME.
Referenced by TTAUnitTesterCmdLineOptions().
vhdlSim()
std::string TTAUnitTesterCmdLineOptions::vhdlSim () const
Definition at line 88 of file TTAUnitTesterCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(SIM_PARAM_NAME);
    return option->String();
}
References CmdLineParser::findOption(), SIM_PARAM_NAME, and CmdLineOptionParser::String().
Member Data Documentation
ADF_PARAM_NAME
const std::string TTAUnitTesterCmdLineOptions::ADF_PARAM_NAME = "adf" static private
Long name of ADF file parameter.
Definition at line 66 of file TTAUnitTesterCmdLineOptions.hh.
Referenced by adfFileName(), and TTAUnitTesterCmdLineOptions().
DIRTY_PARAM_NAME
const std::string TTAUnitTesterCmdLineOptions::DIRTY_PARAM_NAME static private
Initial value:
=
    "leave-dirty"
Long name of leave dirty parameter.
Definition at line 62 of file TTAUnitTesterCmdLineOptions.hh.
Referenced by leaveDirty(), and TTAUnitTesterCmdLineOptions().
SIM_PARAM_NAME
const std::string TTAUnitTesterCmdLineOptions::SIM_PARAM_NAME = "simulator" static private
Long name of VHDL simulator parameter.
Definition at line 64 of file TTAUnitTesterCmdLineOptions.hh.
Referenced by TTAUnitTesterCmdLineOptions(), and vhdlSim().
VERBOSE_PARAM_NAME
const std::string TTAUnitTesterCmdLineOptions::VERBOSE_PARAM_NAME = "verbose" static private
Long name of verbose output parameter.
Definition at line 60 of file TTAUnitTesterCmdLineOptions.hh.
Referenced by TTAUnitTesterCmdLineOptions(), and verbose().
The documentation for this class was generated from the following files:
TTAUnitTesterCmdLineOptions.hh
TTAUnitTesterCmdLineOptions.cc