OpenASIP: TTAMachine::TemplateSlot Class Reference
TTAMachine::TemplateSlot Class Reference
#include <TemplateSlot.hh>
Public Member Functions
TemplateSlot (const Bus &slot, int width, ImmediateUnit &destination)
TemplateSlot (const ImmediateSlot &slot, int width, ImmediateUnit &destination)
TemplateSlot (const Bus &slot)
virtual ~TemplateSlot ()
int width () const
std::string slot () const
ImmediateUnit * destination () const
ObjectState * saveState () const
const Bus * bus () const
Static Public Attributes
static const std::string OSNAME_TEMPLATE_SLOT = "template_slot"
ObjectState name for template slot.
static const std::string OSKEY_SLOT = "slot"
ObjectState attribute key for slot name.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bit width.
static const std::string OSKEY_DESTINATION = "destination"
ObjectState attribute key for destination.
static const std::string OSKEY_RF_READ = "rf_read"
static const std::string OSKEY_RF_WRITE = "rf_write"
static const std::string OSKEY_FU_READ = "fu_read"
static const std::string OSKEY_FU_WRITE = "fu_write"
Private Attributes
const Bus * bus_
The bus which is programmed by the instruction bit field of this template slot.
const ImmediateSlot * immSlot_
The immediate slot which is programmed by the instruction bit field of this template slot.
int width_
The number of bits that can be encoded in this instruction field.
ImmediateUnit * destination_
Destination unit.
Detailed Description
Repsesents a bit field of the TTA instruction that is used to encode a piece of a long immediate for a given instruction template or a NOP move.
Definition at line 55 of file TemplateSlot.hh.
Constructor & Destructor Documentation
TemplateSlot() [1/3]
TTAMachine::TemplateSlot::TemplateSlot (const Bus & slot, int width, ImmediateUnit & destination)
Constructor.
Parameters
slot The bus or which is programmed by the instruction bit field of this template slot.
width The number of significant bits that can be encoded in this instruction field.
destination The destination ImmediateUnit, that is, the ImmediateUnit that contains the registers that can be written with the bits in this template slot.
Definition at line 64 of file TemplateSlot.cc.
                                :
    bus_(&slot), immSlot_(NULL), width_(width), destination_(&destination) {
}
TemplateSlot() [2/3]
TTAMachine::TemplateSlot::TemplateSlot (const ImmediateSlot & slot, int width, ImmediateUnit & destination)
Constructor.
Parameters
slot The immediate slot which is programmed by the instruction bit field of this template slot.
width The number of significant bits that can be encoded in this instruction field.
destination The destination ImmediateUnit, that is, the ImmediateUnit that contains the registers that can be written with the bits in this template slot.
Definition at line 82 of file TemplateSlot.cc.
                                :
    bus_(NULL), immSlot_(&slot), width_(width), destination_(&destination) {
}
TemplateSlot() [3/3]
TTAMachine::TemplateSlot::TemplateSlot (const Bus & slot)
Creates an implicit slot in a template that does not target an ImmediateUnit.
Parameters
slot The bus or which is programmed by the instruction bit field of this template slot.
Definition at line 97 of file TemplateSlot.cc.
    : bus_(&slot), width_(0), destination_(NULL) {}
~TemplateSlot()
TTAMachine::TemplateSlot::~TemplateSlot () virtual
Destructor.
Definition at line 103 of file TemplateSlot.cc.
{
}
Member Function Documentation
bus()
const Bus * TTAMachine::TemplateSlot::bus () const
Referenced by BusBroker::buildResources().
destination()
ImmediateUnit * TTAMachine::TemplateSlot::destination () const
Referenced by BusBroker::buildResources(), TTAMachine::InstructionTemplate::destinationOfSlot(), TTAMachine::InstructionTemplate::destinationUsesSlot(), TTAMachine::InstructionTemplate::isOneOfDestinations(), TTAMachine::InstructionTemplate::numberOfDestinations(), TTAMachine::InstructionTemplate::numberOfSlots(), ImmediateGenerator::printImmediateTemplates(), TTAMachine::InstructionTemplate::removeSlots(), saveState(), TTAMachine::InstructionTemplate::slotOfDestination(), TTAMachine::InstructionTemplate::supportedWidth(), and TemplateSlotDialog::TransferDataToWindow().
saveState()
ObjectState * TTAMachine::TemplateSlot::saveState () const
Saves the state of the object into an ObjectState instance.
Returns
The newly created ObjectState instance.
Definition at line 113 of file TemplateSlot.cc.
{
    ObjectState* slotState = new ObjectState(OSNAME_TEMPLATE_SLOT);
    slotState->setAttribute(OSKEY_SLOT, slot());
    slotState->setAttribute(OSKEY_WIDTH, width());
    slotState->setAttribute(OSKEY_DESTINATION, destination()->name());
    return slotState;
}
References destination(), OSKEY_DESTINATION, OSKEY_SLOT, OSKEY_WIDTH, OSNAME_TEMPLATE_SLOT, ObjectState::setAttribute(), slot(), and width().
Referenced by TTAMachine::InstructionTemplate::saveState().
slot()
std::string TTAMachine::TemplateSlot::slot () const
Referenced by TTAMachine::InstructionTemplate::destinationOfSlot(), BEMGenerator::maxLongImmSlotWidth(), ImmediateGenerator::printImmediateTemplates(), saveState(), TTAMachine::InstructionTemplate::slotOfDestination(), TTAMachine::InstructionTemplate::templateSlot(), and TemplateSlotDialog::TransferDataToWindow().
width()
int TTAMachine::TemplateSlot::width () const
Referenced by BEMGenerator::maxLongImmSlotWidth(), ImmediateGenerator::printImmediateTemplates(), saveState(), TTAMachine::InstructionTemplate::supportedWidth(), TTAMachine::InstructionTemplate::supportedWidth(), and TemplateSlotDialog::TransferDataToWindow().
Member Data Documentation
bus_
const Bus* TTAMachine::TemplateSlot::bus_ private
The bus which is programmed by the instruction bit field of this template slot.
Definition at line 100 of file TemplateSlot.hh.
destination_
ImmediateUnit* TTAMachine::TemplateSlot::destination_ private
Destination unit.
Definition at line 110 of file TemplateSlot.hh.
immSlot_
const ImmediateSlot* TTAMachine::TemplateSlot::immSlot_ private
The immediate slot which is programmed by the instruction bit field of this template slot.
Definition at line 104 of file TemplateSlot.hh.
OSKEY_DESTINATION
const string TTAMachine::TemplateSlot::OSKEY_DESTINATION = "destination" static
ObjectState attribute key for destination.
Definition at line 85 of file TemplateSlot.hh.
Referenced by ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), TTAMachine::InstructionTemplate::loadState(), and saveState().
OSKEY_FU_READ
const string TTAMachine::TemplateSlot::OSKEY_FU_READ = "fu_read" static
Definition at line 91 of file TemplateSlot.hh.
OSKEY_FU_WRITE
const string TTAMachine::TemplateSlot::OSKEY_FU_WRITE = "fu_write" static
Definition at line 93 of file TemplateSlot.hh.
OSKEY_RF_READ
const string TTAMachine::TemplateSlot::OSKEY_RF_READ = "rf_read" static
Definition at line 87 of file TemplateSlot.hh.
OSKEY_RF_WRITE
const string TTAMachine::TemplateSlot::OSKEY_RF_WRITE = "rf_write" static
Definition at line 89 of file TemplateSlot.hh.
OSKEY_SLOT
const string TTAMachine::TemplateSlot::OSKEY_SLOT = "slot" static
ObjectState attribute key for slot name.
Definition at line 81 of file TemplateSlot.hh.
Referenced by ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), TTAMachine::InstructionTemplate::loadState(), ADFSerializer::momTemplateSlot(), and saveState().
OSKEY_WIDTH
const string TTAMachine::TemplateSlot::OSKEY_WIDTH = "width" static
ObjectState attribute key for bit width.
Definition at line 83 of file TemplateSlot.hh.
Referenced by ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), TTAMachine::InstructionTemplate::loadState(), and saveState().
OSNAME_TEMPLATE_SLOT
const string TTAMachine::TemplateSlot::OSNAME_TEMPLATE_SLOT = "template_slot" static
ObjectState name for template slot.
Definition at line 79 of file TemplateSlot.hh.
Referenced by ADFSerializer::instructionTemplateToMachine(), TTAMachine::InstructionTemplate::loadState(), and saveState().
width_
int TTAMachine::TemplateSlot::width_ private
The number of bits that can be encoded in this instruction field.
Definition at line 107 of file TemplateSlot.hh.
The documentation for this class was generated from the following files:
TemplateSlot.hh
TemplateSlot.cc