OpenASIP: TPEF::BinaryWriter Class Reference
TPEF::BinaryWriter Class Reference abstract
#include <BinaryWriter.hh>
Public Member Functions
virtual ~BinaryWriter ()
void writeBinary (BinaryStream &stream, const Binary *bin) const
Protected Member Functions
BinaryWriter ()
virtual void actualWriteBinary (BinaryStream &stream, const Binary *bin) const =0
Does real writing of binary.
void setWriter (const BinaryWriter *writer)
Private Attributes
const BinaryWriter * writerToUse_
Contains concrete writer instance that is used for writing binary.
Detailed Description
Interface for actual binary writer classes and for clients to write binary object representation.
Provides a way for calling the concrete writers with better error checking.
Definition at line 50 of file BinaryWriter.hh.
Constructor & Destructor Documentation
~BinaryWriter()
TPEF::BinaryWriter::~BinaryWriter () virtual
Destructor.
Definition at line 54 of file BinaryWriter.cc.
{
}
BinaryWriter()
TPEF::BinaryWriter::BinaryWriter () protected
Constructor.
Definition at line 48 of file BinaryWriter.cc.
{
}
Member Function Documentation
actualWriteBinary()
virtual void TPEF::BinaryWriter::actualWriteBinary (BinaryStream & stream, const Binary * bin) const protected pure virtual
Does real writing of binary.
Implemented in TPEF::TPEFWriter.
Referenced by writeBinary().
setWriter()
void TPEF::BinaryWriter::setWriter (const BinaryWriter * writer) protected
Sets the concrete binary writer to be used for writing binary program representations to a binary stream.
Parameters
writer Writer instance that we use for writing binary.
Definition at line 131 of file BinaryWriter.cc.
{
    writerToUse_ = writer;
}
References writerToUse_.
Referenced by TPEF::TPEFWriter::TPEFWriter().
writeBinary()
void TPEF::BinaryWriter::writeBinary (BinaryStream & stream, const Binary * bin) const
Stores a binary program representation to given binary stream.
Parameters
stream Stream where to write the program representation.
bin Binary class hierarchy to write.
Definition at line 64 of file BinaryWriter.cc.
{
    assert(writerToUse_ != NULL);
    // init referencemanager and replacers
    SafePointer::cleanupKeyTables();
    ValueReplacer::initialize(stream);
    SectionSizeReplacer::clear();
    try {
        writerToUse_->actualWriteBinary(stream, bin);
    } catch (Exception& e) {
        std::cerr << "Failed to write binary. Maybe the disk is full?" << std::endl << std::endl;;
        exit(-1);
    }
    // try catch blocks are just for debug use right now
    try {
        ValueReplacer::finalize();
    } catch(const MissingKeys &e) {
        std::cerr << "Missing keys during writing binary file! : \n"
                  << e.procedureName() << std::endl
                  << e.errorMessage() << std::endl
                  << std::endl;
        assert(false);
    } catch( ... ) {
        std::cerr << "Problems with stream during writing binary file"
                  << std::endl;
        assert(false);
    }
    // finalize was called successfully so init must be run again
    ValueReplacer::initialize(stream);
    try {
        SectionWriter::finalizeBinary(stream, bin, writerToUse_);
    } catch (Exception& e) {
        std::cerr << "Failed to finalize binary." << std::endl;
        exit(-1);
    }
    // try catch blocks are just for debug use right now
    try {
        ValueReplacer::finalize();
    } catch(const MissingKeys &e) {
        std::cerr << "Missing keys during finalization of writing! \n"
                  << e.procedureName() << std::endl
                  << e.errorMessage() << std::endl
                  << std::endl;
        assert(false);
    } catch( ... ) {
        std::cerr << "Problems with stream during finalization of writing"
                  << std::endl;
        assert(false);
    }
    ReferenceManager::SafePointer::cleanupKeyTables();
}
References actualWriteBinary(), assert, TPEF::ReferenceManager::SafePointer::cleanupKeyTables(), TPEF::SectionSizeReplacer::clear(), Exception::errorMessage(), TPEF::ValueReplacer::finalize(), TPEF::SectionWriter::finalizeBinary(), TPEF::ValueReplacer::initialize(), Exception::procedureName(), and writerToUse_.
Referenced by main(), and TTAProgram::Program::writeToTPEF().
Member Data Documentation
writerToUse_
const BinaryWriter* TPEF::BinaryWriter::writerToUse_ private
Contains concrete writer instance that is used for writing binary.
Definition at line 68 of file BinaryWriter.hh.
Referenced by setWriter(), and writeBinary().
The documentation for this class was generated from the following files:
BinaryWriter.hh
BinaryWriter.cc