OpenASIP: TCEPluginInitializer Class Reference
TCEPluginInitializer Class Reference
Public Member Functions
TCEPluginInitializer ()
Detailed Description
Definition at line 207 of file TCETargetMachinePlugin.cc.
Constructor & Destructor Documentation
TCEPluginInitializer()
TCEPluginInitializer::TCEPluginInitializer () inline
Definition at line 209 of file TCETargetMachinePlugin.cc.
{
        GeneratedTCEPlugin* plugin = new GeneratedTCEPlugin();
        plugin->manualInitialize();
        // Register LLVM Target and TCE Stub TargetMachine
        LLVMInitializeTCETargetInfo();
        LLVMInitializeTCEStubTarget();
    }
References LLVMInitializeTCEStubTarget(), LLVMInitializeTCETargetInfo(), and llvm::GeneratedTCEPlugin::manualInitialize().
The documentation for this class was generated from the following file:
TCETargetMachinePlugin.cc