OpenASIP: IgnoreCommand Class Reference
IgnoreCommand Class Reference
#include <IgnoreCommand.hh>
Public Member Functions
IgnoreCommand ()
virtual ~IgnoreCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "ignore" command of the Simulator Control Language.
Definition at line 47 of file IgnoreCommand.hh.
Constructor & Destructor Documentation
IgnoreCommand()
IgnoreCommand::IgnoreCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 51 of file IgnoreCommand.cc.
                             :
    SimControlLanguageCommand("ignore") {
}
~IgnoreCommand()
IgnoreCommand::~IgnoreCommand () virtual
Destructor.
Does nothing.
Definition at line 60 of file IgnoreCommand.cc.
{
}
Member Function Documentation
execute()
bool IgnoreCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "ignore" command.
Modifies the ignore counts of breakpoints.
Parameters
arguments The count of steps (default is one step).
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 74 of file IgnoreCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 2, 2)) {
        return false;
    }
    if  (!checkPositiveIntegerArgument(arguments[1]) ||
         !checkPositiveIntegerArgument(arguments[2])) {
        return false;
    }
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    const int breakpointHandle = arguments[1].integerValue();
    const int ignoreCount = arguments[2].integerValue();
    try {
        StopPointManager& stopPointManager =
            simulatorFrontend().stopPointManager();
        // just check that breakpoint is found with the handle
        stopPointManager.stopPointWithHandleConst(breakpointHandle);
        stopPointManager.setIgnore(breakpointHandle, ignoreCount);
        printBreakpointInfo(breakpointHandle);
    } catch (const InstanceNotFound&) {
        interpreter()->setError(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_BREAKPOINT_NOT_FOUND).str());
        return false;
    }
    return true;
}
References CustomCommand::checkArgumentCount(), CustomCommand::checkPositiveIntegerArgument(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), CustomCommand::interpreter(), SimControlLanguageCommand::printBreakpointInfo(), ScriptInterpreter::setError(), StopPointManager::setIgnore(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::stopPointManager(), StopPointManager::stopPointWithHandleConst(), SimulatorToolbox::textGenerator(), and Texts::TXT_BREAKPOINT_NOT_FOUND.
helpText()
std::string IgnoreCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 119 of file IgnoreCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_IGNORE).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_IGNORE.
The documentation for this class was generated from the following files:
IgnoreCommand.hh
IgnoreCommand.cc