OpenASIP: SOPCInterface Class Reference
SOPCInterface Class Reference
#include <SOPCInterface.hh>
Classes
struct SOPCPort
Public Member Functions
SOPCInterface (TCEString name, TCEString declaration)
virtual ~SOPCInterface ()
void setProperty (const TCEString &propertyName, const TCEString &propertyValue)
void setProperty (const TCEString &propertyName, int propertyValue)
void setPort (const TCEString &hdlName, const TCEString &interfaceName, ProGe::Direction direction, int width)
TCEString name () const
bool hasPorts () const
virtual void writeInterface (std::ostream &stream) const
Static Public Attributes
static const TCEString SOPC_ADD_INTERFACE
static const TCEString SOPC_SET_INT_PROPERTY
static const TCEString SOPC_ADD_INT_PORT
static const TCEString SOPC_ASSOCIATED_CLOCK
static const TCEString SOPC_MASTER_INT_NAME = "avalon_master"
static const TCEString SOPC_MASTER_INT_DECLR = "avalon start"
static const TCEString SOPC_CLOCK_INT_NAME = "clock_reset"
static const TCEString SOPC_CLOCK_INT_DECLR = "clock end"
static const TCEString SOPC_EXPORT_INT_NAME = "conduit_interface"
static const TCEString SOPC_EXPORT_INT_DECLR = "conduit end"
static const TCEString SOPC_EXPORT_NAME = "export"
static const TCEString SOPC_IRQ_RECV_INT_NAME = "interrupt_recv"
static const TCEString SOPC_IRQ_RECV_INT_DECLR = "interrupt start"
static const TCEString SOPC_INPUT = "Input"
static const TCEString SOPC_OUTPUT = "Output"
static const TCEString SOPC_BIDIR = "Bidir"
Protected Types
typedef std::map< TCEString, TCEString > PropertyMap
typedef std::vector< SOPCPort > PortList
Protected Member Functions
const PropertyMap * properties () const
const PortList * ports () const
void writeProperties (std::ostream &stream) const
void writePorts (std::ostream &stream) const
Private Member Functions
SOPCInterface ()
SOPCInterface (const SOPCInterface &old)
SOPCInterface & operator= (SOPCInterface old)
Private Attributes
TCEString name_
TCEString declaration_
PropertyMap properties_
PortList ports_
Detailed Description
Definition at line 41 of file SOPCInterface.hh.
Member Typedef Documentation
PortList
typedef std::vector<SOPCPort> SOPCInterface::PortList protected
Definition at line 99 of file SOPCInterface.hh.
PropertyMap
typedef std::map<TCEString, TCEString> SOPCInterface::PropertyMap protected
Definition at line 98 of file SOPCInterface.hh.
Constructor & Destructor Documentation
SOPCInterface() [1/3]
SOPCInterface::SOPCInterface (TCEString name, TCEString declaration)
Definition at line 66 of file SOPCInterface.cc.
                                                                 :
    name_(name), declaration_(declaration) {
}
~SOPCInterface()
SOPCInterface::~SOPCInterface () virtual
Definition at line 70 of file SOPCInterface.cc.
{
}
SOPCInterface() [2/3]
SOPCInterface::SOPCInterface () private
Referenced by AvalonMMMasterInterface::addIrqInterface().
SOPCInterface() [3/3]
SOPCInterface::SOPCInterface (const SOPCInterface & old) private
Member Function Documentation
hasPorts()
bool SOPCInterface::hasPorts () const
Definition at line 104 of file SOPCInterface.cc.
{
    return !ports_.empty();
}
References ports_.
Referenced by SOPCBuilderFileGenerator::writeInterfaces().
name()
TCEString SOPCInterface::name () const
Definition at line 98 of file SOPCInterface.cc.
{
    return name_;
}
References name_.
Referenced by AvalonMMMasterInterface::addIrqInterface(), AvalonMMMasterInterface::AvalonMMMasterInterface(), and SOPCBuilderFileGenerator::SOPCBuilderFileGenerator().
operator=()
SOPCInterface & SOPCInterface::operator= (SOPCInterface old) private
ports()
const SOPCInterface::PortList * SOPCInterface::ports () const protected
Definition at line 127 of file SOPCInterface.cc.
{
    return &ports_;
}
References ports_.
properties()
const SOPCInterface::PropertyMap * SOPCInterface::properties () const protected
Definition at line 121 of file SOPCInterface.cc.
{
    return &properties_;
}
References properties_.
setPort()
void SOPCInterface::setPort (const TCEString & hdlName, const TCEString & interfaceName, ProGe::Direction direction, int width)
Definition at line 90 of file SOPCInterface.cc.
{
    SOPCPort port = {hdlName, interfaceName, direction, width};
    ports_.push_back(port);
}
References ports_.
Referenced by AvalonMMMasterInterface::addIrqInterface(), AvalonMMMasterInterface::addPort(), SOPCBuilderFileGenerator::exportSignal(), and SOPCBuilderFileGenerator::SOPCBuilderFileGenerator().
setProperty() [1/2]
void SOPCInterface::setProperty (const TCEString & propertyName, const TCEString & propertyValue)
Definition at line 73 of file SOPCInterface.cc.
{
    properties_[propertyName] = propertyValue;
}
References properties_.
Referenced by AvalonMMMasterInterface::addIrqInterface(), AvalonMMMasterInterface::AvalonMMMasterInterface(), setProperty(), and SOPCBuilderFileGenerator::SOPCBuilderFileGenerator().
setProperty() [2/2]
void SOPCInterface::setProperty (const TCEString & propertyName, int propertyValue)
Definition at line 81 of file SOPCInterface.cc.
                       {
    TCEString convertedValue = Conversion::toString(propertyValue);
    setProperty(propertyName, convertedValue);
}
References setProperty(), and Conversion::toString().
writeInterface()
void SOPCInterface::writeInterface (std::ostream & stream) const virtual
Reimplemented in AvalonMMMasterInterface.
Definition at line 110 of file SOPCInterface.cc.
{
    stream
        << "# " << name_ << endl
        << SOPC_ADD_INTERFACE << " " << name_ << " " << declaration_ << endl;
    writeProperties(stream);
    writePorts(stream);
    stream << endl;
}
References declaration_, name_, SOPC_ADD_INTERFACE, writePorts(), and writeProperties().
Referenced by AvalonMMMasterInterface::writeInterface(), and SOPCBuilderFileGenerator::writeInterfaces().
writePorts()
void SOPCInterface::writePorts (std::ostream & stream) const protected
Definition at line 147 of file SOPCInterface.cc.
{
    for (unsigned int i = 0; i < ports_.size(); i++) {
        stream
            << SOPC_ADD_INT_PORT << " " << name_ << " "
            << ports_.at(i).hdlName << " " << ports_.at(i).interfaceName
            << " ";
        if (ports_.at(i).direction == ProGe::IN) {
            stream << SOPC_INPUT << " ";
        } else if (ports_.at(i).direction == ProGe::OUT) {
            stream << SOPC_OUTPUT << " ";
        } else if (ports_.at(i).direction == ProGe::BIDIR) {
            stream << SOPC_BIDIR << " ";
        } else {
            assert(false && "Invalid port direction");
        }
        stream << ports_.at(i).width << endl;
    }
}
References assert, ProGe::BIDIR, ProGe::IN, name_, ProGe::OUT, ports_, SOPC_ADD_INT_PORT, SOPC_BIDIR, SOPC_INPUT, and SOPC_OUTPUT.
Referenced by writeInterface().
writeProperties()
void SOPCInterface::writeProperties (std::ostream & stream) const protected
Definition at line 134 of file SOPCInterface.cc.
{
    PropertyMap::const_iterator iter = properties_.begin();
    while (iter != properties_.end()) {
        stream
            << SOPC_SET_INT_PROPERTY << " " << name_ << " " << iter->first
            << " " << iter->second << endl;
        iter++;
    }
}
References name_, properties_, and SOPC_SET_INT_PROPERTY.
Referenced by writeInterface().
Member Data Documentation
declaration_
TCEString SOPCInterface::declaration_ private
Definition at line 115 of file SOPCInterface.hh.
Referenced by writeInterface().
name_
TCEString SOPCInterface::name_ private
Definition at line 114 of file SOPCInterface.hh.
Referenced by name(), writeInterface(), writePorts(), and writeProperties().
ports_
PortList SOPCInterface::ports_ private
Definition at line 117 of file SOPCInterface.hh.
Referenced by hasPorts(), ports(), setPort(), and writePorts().
properties_
PropertyMap SOPCInterface::properties_ private
Definition at line 116 of file SOPCInterface.hh.
Referenced by properties(), setProperty(), and writeProperties().
SOPC_ADD_INT_PORT
const TCEString SOPCInterface::SOPC_ADD_INT_PORT static
Initial value:
=
    "add_interface_port"
Definition at line 69 of file SOPCInterface.hh.
Referenced by writePorts().
SOPC_ADD_INTERFACE
const TCEString SOPCInterface::SOPC_ADD_INTERFACE static
Initial value:
=
    "add_interface"
Definition at line 67 of file SOPCInterface.hh.
Referenced by writeInterface().
SOPC_ASSOCIATED_CLOCK
const TCEString SOPCInterface::SOPC_ASSOCIATED_CLOCK static
Initial value:
=
    "ASSOCIATED_CLOCK"
Definition at line 70 of file SOPCInterface.hh.
Referenced by AvalonMMMasterInterface::addIrqInterface(), AvalonMMMasterInterface::AvalonMMMasterInterface(), and SOPCBuilderFileGenerator::SOPCBuilderFileGenerator().
SOPC_BIDIR
const TCEString SOPCInterface::SOPC_BIDIR = "Bidir" static
Definition at line 87 of file SOPCInterface.hh.
Referenced by writePorts().
SOPC_CLOCK_INT_DECLR
const TCEString SOPCInterface::SOPC_CLOCK_INT_DECLR = "clock end" static
Definition at line 76 of file SOPCInterface.hh.
SOPC_CLOCK_INT_NAME
const TCEString SOPCInterface::SOPC_CLOCK_INT_NAME = "clock_reset" static
Definition at line 75 of file SOPCInterface.hh.
SOPC_EXPORT_INT_DECLR
const TCEString SOPCInterface::SOPC_EXPORT_INT_DECLR = "conduit end" static
Definition at line 79 of file SOPCInterface.hh.
SOPC_EXPORT_INT_NAME
const TCEString SOPCInterface::SOPC_EXPORT_INT_NAME = "conduit_interface" static
Definition at line 78 of file SOPCInterface.hh.
SOPC_EXPORT_NAME
const TCEString SOPCInterface::SOPC_EXPORT_NAME = "export" static
Definition at line 80 of file SOPCInterface.hh.
Referenced by SOPCBuilderFileGenerator::exportSignal().
SOPC_INPUT
const TCEString SOPCInterface::SOPC_INPUT = "Input" static
Definition at line 85 of file SOPCInterface.hh.
Referenced by writePorts().
SOPC_IRQ_RECV_INT_DECLR
const TCEString SOPCInterface::SOPC_IRQ_RECV_INT_DECLR = "interrupt start" static
Definition at line 83 of file SOPCInterface.hh.
Referenced by AvalonMMMasterInterface::addIrqInterface().
SOPC_IRQ_RECV_INT_NAME
const TCEString SOPCInterface::SOPC_IRQ_RECV_INT_NAME = "interrupt_recv" static
Definition at line 82 of file SOPCInterface.hh.
Referenced by AvalonMMMasterInterface::addIrqInterface().
SOPC_MASTER_INT_DECLR
const TCEString SOPCInterface::SOPC_MASTER_INT_DECLR = "avalon start" static
Definition at line 73 of file SOPCInterface.hh.
Referenced by SOPCBuilderFileGenerator::handleAvalonSignal().
SOPC_MASTER_INT_NAME
const TCEString SOPCInterface::SOPC_MASTER_INT_NAME = "avalon_master" static
Definition at line 72 of file SOPCInterface.hh.
Referenced by SOPCBuilderFileGenerator::handleAvalonSignal().
SOPC_OUTPUT
const TCEString SOPCInterface::SOPC_OUTPUT = "Output" static
Definition at line 86 of file SOPCInterface.hh.
Referenced by writePorts().
SOPC_SET_INT_PROPERTY
const TCEString SOPCInterface::SOPC_SET_INT_PROPERTY static
Initial value:
=
    "set_interface_property"
Definition at line 68 of file SOPCInterface.hh.
Referenced by writeProperties().
The documentation for this class was generated from the following files:
SOPCInterface.hh
SOPCInterface.cc