OpenASIP: BusFigure Class Reference
BusFigure Class Reference
#include <BusFigure.hh>
Public Member Functions
BusFigure (unsigned int slot)
virtual ~BusFigure ()
virtual wxRect virtualBounds () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
virtual void drawSelf (wxDC *)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
Private Member Functions
BusFigure & operator= (BusFigure &old)
Assignment not allowed.
BusFigure (BusFigure &old)
Copying not allowed.
Private Attributes
unsigned int slot_
Slot of the bus.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(150, 150, 150)
Default colour for the figure.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a bus.
Definition at line 48 of file BusFigure.hh.
Constructor & Destructor Documentation
BusFigure() [1/2]
BusFigure::BusFigure (unsigned int slot)
The Constructor.
Definition at line 48 of file BusFigure.cc.
                                     : Figure(), slot_(slot) {
    minSize_ = wxSize(
    MachineCanvasLayoutConstraints::BUS_MIN_WIDTH,
    MachineCanvasLayoutConstraints::BUS_MIN_HEIGHT);
    size_ = minSize_;
}
References MachineCanvasLayoutConstraints::BUS_MIN_HEIGHT, MachineCanvasLayoutConstraints::BUS_MIN_WIDTH, Figure::minSize_, and Figure::size_.
~BusFigure()
BusFigure::~BusFigure () virtual
The Destructor.
Definition at line 58 of file BusFigure.cc.
{}
BusFigure() [2/2]
BusFigure::BusFigure (BusFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void BusFigure::drawSelf (wxDC * dc) protected virtual
Draws the Figure of the bus on the given device context if it has no segments, otherwise only the segments are drawn.
Parameters
dc The device context.
Reimplemented from Figure.
Definition at line 128 of file BusFigure.cc.
{
    if (children_.empty()) {
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    wxBrush brush = wxBrush(DEFAULT_COLOUR, wxSOLID);
    dc->SetPen(pen);
    dc->SetBrush(brush);
    dc->DrawRectangle(location_.x, location_.y,
              size_.GetWidth(), size_.GetHeight());
    }
    // Draw slot label.
    int slotLabelWidth;
    int slotLabelHeight;
    wxString slotLabel = WxConversion::toWxString(slot_);
    dc->GetTextExtent(slotLabel, &slotLabelWidth, &slotLabelHeight);
    int slotLabelX = location_.x - slotLabelWidth - 10;
    int slotLabelY =
        ((size_.GetHeight() / 2) + location_.y) - (slotLabelHeight / 2);
    dc->SetBackgroundMode(wxTRANSPARENT);
    dc->SetTextForeground(*wxBLACK);
    dc->DrawText(slotLabel, slotLabelX, slotLabelY);
}
References Figure::children_, DEFAULT_COLOUR, Figure::location_, Figure::size_, slot_, and WxConversion::toWxString().
layoutChildren()
void BusFigure::layoutChildren (wxDC * dc) protected virtual
Lays ouf the segments in a column, spaced evenly.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 84 of file BusFigure.cc.
{
    int segY = location_.y;
    int segX = location_.x;
    for(unsigned int i = 0; i < children_.size(); i++) {
        children_[i]->setLocation(wxPoint(segX, segY));
    children_[i]->setWidth(size_.GetWidth());
        children_[i]->layout(dc);
        segY += children_[i]->bounds().GetHeight() +
        MachineCanvasLayoutConstraints::SEGMENT_SPACE;
    }
}
References Figure::children_, Figure::location_, MachineCanvasLayoutConstraints::SEGMENT_SPACE, and Figure::size_.
layoutSelf()
void BusFigure::layoutSelf (wxDC *) protected virtual
Calculates and sets bus size according to the size of segments.
Reimplemented from Figure.
Definition at line 102 of file BusFigure.cc.
{
    if (children_.size() > 0) {
    int segsHeight = 0;
    vector<Figure*>::const_iterator i = children_.begin();
    for (; i != children_.end(); i++) {
        segsHeight += (*i)->bounds().GetHeight();
    }
    dynamic_cast<SegmentFigure*>(children_.back())->setLast(true);
    segsHeight += (children_.size() - 1)
        * MachineCanvasLayoutConstraints::SEGMENT_SPACE;
    size_.SetHeight(segsHeight);
    }
}
References Figure::children_, MachineCanvasLayoutConstraints::SEGMENT_SPACE, and Figure::size_.
operator=()
BusFigure & BusFigure::operator= (BusFigure & old) private
Assignment not allowed.
virtualBounds()
wxRect BusFigure::virtualBounds () const virtual
Returns the virtual bounds of a bus, which are a bit higher than the visible bounds to make selection easier.
Returns
The virtual bounds of a bus.
Reimplemented from Figure.
Definition at line 67 of file BusFigure.cc.
{
    if (childCount() <= 1) {
    wxRect virtualLocation = wxRect(
        wxPoint(location_.x, location_.y - size_.GetHeight()),
        wxSize(size_.GetWidth(), size_.GetHeight() * 3));
    return virtualLocation;
    } else {
    return wxRect(location_, size_);
    }
}
References Figure::childCount(), Figure::location_, and Figure::size_.
Member Data Documentation
DEFAULT_COLOUR
const wxColour BusFigure::DEFAULT_COLOUR = wxColour(150, 150, 150) static private
Default colour for the figure.
Definition at line 69 of file BusFigure.hh.
Referenced by drawSelf().
slot_
unsigned int BusFigure::slot_ private
Slot of the bus.
Definition at line 67 of file BusFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
BusFigure.hh
BusFigure.cc