OpenASIP: OperationPropertyLoader Class Reference
OperationPropertyLoader Class Reference
#include <OperationPropertyLoader.hh>
Public Member Functions
OperationPropertyLoader ()
virtual ~OperationPropertyLoader ()
void loadOperationProperties (Operation &operation, const OperationModule &module)
Private Types
typedef std::map< std::string, std::vector< ObjectState * > > ObjectStateCache
Container containing already read ObjectState trees.
typedef ObjectStateCache::iterator MapIter
Iterator for map containing already read ObjectState trees.
typedef ObjectStateCache::value_type ValueType
value_type for map containing already read ObjectState trees.
Private Member Functions
OperationPropertyLoader (const OperationPropertyLoader &)
Copying not allowed.
OperationPropertyLoader & operator= (const OperationPropertyLoader &)
Assignment not allowed.
void loadModule (const OperationModule &module)
Private Attributes
OperationSerializer serializer_
Serializer instance.
ObjectStateCache operations_
Cache for already read ObjectState trees.
Detailed Description
Imports the static information contents of an operation from a data file.
Definition at line 51 of file OperationPropertyLoader.hh.
Member Typedef Documentation
MapIter
typedef ObjectStateCache::iterator OperationPropertyLoader::MapIter private
Iterator for map containing already read ObjectState trees.
Definition at line 64 of file OperationPropertyLoader.hh.
ObjectStateCache
typedef std::map<std::string, std::vector<ObjectState*> > OperationPropertyLoader::ObjectStateCache private
Container containing already read ObjectState trees.
Definition at line 61 of file OperationPropertyLoader.hh.
ValueType
typedef ObjectStateCache::value_type OperationPropertyLoader::ValueType private
value_type for map containing already read ObjectState trees.
Definition at line 66 of file OperationPropertyLoader.hh.
Constructor & Destructor Documentation
OperationPropertyLoader() [1/2]
OperationPropertyLoader::OperationPropertyLoader ()
Constructor.
Definition at line 50 of file OperationPropertyLoader.cc.
{
}
~OperationPropertyLoader()
OperationPropertyLoader::~OperationPropertyLoader () virtual
Destructor.
Definition at line 56 of file OperationPropertyLoader.cc.
{
    MapIter it = operations_.begin();
    while (it != operations_.end()) {
        SequenceTools::deleteAllItems((*it).second);
        it++;
    }
}
References SequenceTools::deleteAllItems(), and operations_.
OperationPropertyLoader() [2/2]
OperationPropertyLoader::OperationPropertyLoader (const OperationPropertyLoader &) private
Copying not allowed.
Member Function Documentation
loadModule()
void OperationPropertyLoader::loadModule (const OperationModule & module) private
Loads the module.
Saves its operations as an ObjectState objects.
Parameters
module The OperationModule.
Exceptions
InstanceNotFound If loading the module fails.
Definition at line 120 of file OperationPropertyLoader.cc.
{
    serializer_.setSourceFile(module.propertiesModule());
    ObjectState* root = NULL;
    try {
        root = serializer_.readState();
    } catch (const SerializerException& s) {
        string msg = "Problems when reading the XML file: " + s.errorMessage();
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    }
    vector<ObjectState*> ops;
    for (int i = 0; i < root->childCount(); i++) {
        ObjectState* child = new ObjectState(*root->child(i));
        ops.push_back(child);
    }
    delete root;
    operations_.insert(ValueType(module.propertiesModule(), ops));
}
References __func__, ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), operations_, OperationModule::propertiesModule(), OperationSerializer::readState(), serializer_, and OperationSerializer::setSourceFile().
Referenced by loadOperationProperties().
loadOperationProperties()
void OperationPropertyLoader::loadOperationProperties (Operation & operation, const OperationModule & module)
Loads the properties of an operation.
If operation properties has not yet been loaded, it is done first.
Parameters
operation Operation which properties are loaded and updated.
module Module where properties are loaded from.
Exceptions
InstanceNotFound If reading of XML fails, if Operation fails to load its state, or if properties are not found at all.
Definition at line 76 of file OperationPropertyLoader.cc.
{
    MapIter it = operations_.find(module.propertiesModule());
    if (it == operations_.end()) {
        // properties are not yet read, let's do it first
        loadModule(module);
        it = operations_.find(module.propertiesModule());
    }
    const vector<ObjectState*> ops = (*it).second;
    bool operationFound = false;
    for (unsigned int i = 0; i < ops.size(); i++) {
        if (ops[i]->stringAttribute(Operation::OPRN_NAME) ==
            operation.name()) {
            operationFound = true;
            try {
                operation.loadState(ops[i]);
            } catch (const ObjectStateLoadingException& o) {
                string msg = "Problems when loading the state of the Object: "
                    + o.errorMessage();
                throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
            }
            break;
        }
    }
    if (!operationFound) {
        string msg = string("Properties for operation ") + operation.name() +
            " not found";
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, Exception::errorMessage(), loadModule(), Operation::loadState(), Operation::name(), operations_, Operation::OPRN_NAME, and OperationModule::propertiesModule().
operator=()
OperationPropertyLoader & OperationPropertyLoader::operator= (const OperationPropertyLoader &) private
Assignment not allowed.
Member Data Documentation
operations_
ObjectStateCache OperationPropertyLoader::operations_ private
Cache for already read ObjectState trees.
Definition at line 78 of file OperationPropertyLoader.hh.
Referenced by loadModule(), loadOperationProperties(), and ~OperationPropertyLoader().
serializer_
OperationSerializer OperationPropertyLoader::serializer_ private
Serializer instance.
Definition at line 76 of file OperationPropertyLoader.hh.
Referenced by loadModule().
The documentation for this class was generated from the following files:
OperationPropertyLoader.hh
OperationPropertyLoader.cc