OpenASIP: HDBEditorModifyCmd Class Reference
HDBEditorModifyCmd Class Reference
#include <HDBEditorModifyCmd.hh>
Public Member Functions
HDBEditorModifyCmd ()
virtual ~HDBEditorModifyCmd ()
virtual bool Do ()
virtual int id () const
virtual HDBEditorModifyCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for modifying HDB items.
Definition at line 41 of file HDBEditorModifyCmd.hh.
Constructor & Destructor Documentation
HDBEditorModifyCmd()
HDBEditorModifyCmd::HDBEditorModifyCmd ()
The Constructor.
Definition at line 60 of file HDBEditorModifyCmd.cc.
                                       :
    GUICommand(HDBEditorConstants::COMMAND_NAME_MODIFY, NULL) {
}
Referenced by create().
~HDBEditorModifyCmd()
HDBEditorModifyCmd::~HDBEditorModifyCmd () virtual
The Destructor.
Definition at line 68 of file HDBEditorModifyCmd.cc.
{
}
Member Function Documentation
create()
HDBEditorModifyCmd * HDBEditorModifyCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 207 of file HDBEditorModifyCmd.cc.
{
    return new HDBEditorModifyCmd();
}
References HDBEditorModifyCmd().
Do()
bool HDBEditorModifyCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 75 of file HDBEditorModifyCmd.cc.
                       {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (browser->isFUImplementationSelected()) {
        // FU implementation modification.
        int entryID = manager->fuEntryIDOfImplementation(
            browser->selectedFUImplementation());
        HDB::FUEntry* entry = manager->fuByEntryID(entryID);
        FUImplementationDialog dialog(
            parentWindow(), -1, entry->implementation(),
            entry->architecture().architecture());
        if (dialog.ShowModal() == wxID_OK) {
            try {
                assert(entry->hasImplementation() &&
                       entry->implementation().hasID());
                int implID = entry->implementation().id();
                manager->removeFUImplementation(implID);
                int id = manager->addFUImplementation(*entry);
                wxGetApp().mainFrame().update();
                wxGetApp().mainFrame().browser()->selectFUImplementation(id);
            } catch (Exception& e) {
                wxString message = _T("Error:\n");
                message.Append(WxConversion::toWxString(e.errorMessage()));
                message.Append(_T("\n"));
                message.Append(WxConversion::toWxString(e.lineNum()));
                message.Append(_T(": "));
                message.Append(WxConversion::toWxString(e.fileName()));
                ErrorDialog dialog(parentWindow(), message);
                dialog.ShowModal();
                delete entry;
                return false;
            }
        } else {
            delete entry;
        }
        return true;
    } else if (browser->isRFImplementationSelected()) {
        // RF implementation modification.
        int entryID = manager->rfEntryIDOfImplementation(
            browser->selectedRFImplementation());
        HDB::RFEntry* entry = manager->rfByEntryID(entryID);
        RFImplementationDialog dialog(
            parentWindow(), -1, entry->implementation());
        if (dialog.ShowModal() == wxID_OK) {
            try {
                assert(entry->hasImplementation() &&
                       entry->implementation().hasID());
                int implID = entry->implementation().id();
                manager->removeRFImplementation(implID);
                int id = manager->addRFImplementation(
                    entry->implementation(), entryID);
                //can be commented for not update DB-> fast editing
                wxGetApp().mainFrame().update();
                wxGetApp().mainFrame().browser()->selectRFImplementation(id);
            } catch (Exception& e) {
                wxString message = _T("Error:\n");
                message.Append(WxConversion::toWxString(e.errorMessage()));
                message.Append(_T("\n"));
                message.Append(WxConversion::toWxString(e.lineNum()));
                message.Append(_T(": "));
                message.Append(WxConversion::toWxString(e.fileName()));
                ErrorDialog dialog(parentWindow(), message);
                dialog.ShowModal();
                delete entry;
                return false;
            }
        } else {
            delete entry;
        }
        return true;
    } else if (browser->isCostFunctionPluginSelected()) {
        CostFunctionPluginDialog dialog(
            parentWindow(), -1,
            *manager, browser->selectedCostFunctionPlugin());
        dialog.ShowModal();
        wxGetApp().mainFrame().update();
        return true;
    }
    return false;
}
References HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDB::FUArchitecture::architecture(), HDB::FUEntry::architecture(), assert, Exception::errorMessage(), Exception::fileName(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuEntryIDOfImplementation(), HDB::HWBlockImplementation::hasID(), HDB::FUEntry::hasImplementation(), HDB::RFEntry::hasImplementation(), HDB::HWBlockImplementation::id(), HDB::FUEntry::implementation(), HDB::RFEntry::implementation(), HDBBrowserWindow::isCostFunctionPluginSelected(), HDBBrowserWindow::isFUImplementationSelected(), HDBBrowserWindow::isRFImplementationSelected(), Exception::lineNum(), GUICommand::parentWindow(), HDB::HDBManager::removeFUImplementation(), HDB::HDBManager::removeRFImplementation(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfEntryIDOfImplementation(), HDBBrowserWindow::selectedCostFunctionPlugin(), HDBBrowserWindow::selectedFUImplementation(), HDBBrowserWindow::selectedRFImplementation(), and WxConversion::toWxString().
icon()
std::string HDBEditorModifyCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 186 of file HDBEditorModifyCmd.cc.
{
    return "";
}
id()
int HDBEditorModifyCmd::id () const virtual
Returns the command id.
Returns
Command identifier.
Implements GUICommand.
Definition at line 196 of file HDBEditorModifyCmd.cc.
{
    return HDBEditorConstants::COMMAND_MODIFY;
}
References HDBEditorConstants::COMMAND_MODIFY.
isEnabled()
bool HDBEditorModifyCmd::isEnabled () virtual
Returns true if the command should be enabled in the tool/menubar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 218 of file HDBEditorModifyCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (browser->isFUImplementationSelected() ||
        browser->isRFImplementationSelected() ||
        browser->isCostFunctionPluginSelected()) {
        return true;
    }
    return false;
}
References HDBBrowserWindow::isCostFunctionPluginSelected(), HDBBrowserWindow::isFUImplementationSelected(), and HDBBrowserWindow::isRFImplementationSelected().
The documentation for this class was generated from the following files:
HDBEditorModifyCmd.hh
HDBEditorModifyCmd.cc