OpenASIP: EditorCommand Class Reference
EditorCommand Class Reference
#include <EditorCommand.hh>
Inherits GUICommand.
Inherited by AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOTAFormatsCmd, EditOptionsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VLIWConnectICCmd, VerifyMachineCmd, ZoomInCmd, and ZoomOutCmd.
Public Member Functions
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual int id () const =0
virtual GUICommand * create () const =0
virtual bool Do ()=0
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Attributes
wxView * view_
The view assigned for the command.
Detailed Description
Base class for editor commands, which can be added to menus or toolbar.
Definition at line 46 of file EditorCommand.hh.
Constructor & Destructor Documentation
EditorCommand()
EditorCommand::EditorCommand (std::string name, wxWindow * parent = NULL)
The Constructor.
Definition at line 42 of file EditorCommand.cc.
                                                             :
    GUICommand(name, parent),
    view_(NULL) {
}
~EditorCommand()
EditorCommand::~EditorCommand () virtual
The Destructor.
Definition at line 53 of file EditorCommand.cc.
{
}
Member Function Documentation
icon()
string EditorCommand::icon () const virtual
Returns path to the icon of the command to be used on the toolbar.
Returns
Base class implementation returns default icon's path.
Implements GUICommand.
Reimplemented in AboutCmd, AddFUFromHDBCmd, AddIUFromHDBCmd, AddRFFromHDBCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, UndoCmd, VerifyMachineCmd, ZoomInCmd, and ZoomOutCmd.
Definition at line 87 of file EditorCommand.cc.
{
    return ProDeConstants::CMD_ICON_DEFAULT;
}
References ProDeConstants::CMD_ICON_DEFAULT.
isEnabled()
bool EditorCommand::isEnabled () virtual
Returns true if command is currently executable, otherwise false.
Base class implementation returns always false.
Returns
True if command is currently executable, otherwise false.
Implements GUICommand.
Reimplemented in AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Definition at line 100 of file EditorCommand.cc.
{
    return false;
}
setView()
void EditorCommand::setView (wxView * view)
Sets the MDFView of the command.
Parameters
view MDFView to be assigned for the command.
Definition at line 65 of file EditorCommand.cc.
{
    view_ = view;
}
References view(), and view_.
Referenced by MainFrame::onCommandEvent(), SelectTool::onMouseEvent(), and MainFrame::onUpdateUI().
view()
wxView * EditorCommand::view () const
Returns MDFView of the command.
Returns
MDFView of the command.
Definition at line 76 of file EditorCommand.cc.
{
    return view_;
}
References view_.
Referenced by AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddFUFromHDBCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddIUFromHDBCmd::Do(), AddRFCmd::Do(), AddRFFromHDBCmd::Do(), AddSocketCmd::Do(), BlocksConnectICCmd::Do(), CallExplorerPluginCmd::Do(), CopyComponentCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditConnectionsCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), FitHeightCmd::Do(), FitWidthCmd::Do(), FitWindowCmd::Do(), FullyConnectBussesCmd::Do(), ImplementMachineCmd::Do(), ModifyComponentCmd::Do(), PasteComponentCmd::Do(), PrintCmd::Do(), ProDeExportCmd::Do(), RedoCmd::Do(), SelectCmd::Do(), ToggleUnitDetailsCmd::Do(), UndoCmd::Do(), VerifyMachineCmd::Do(), VLIWConnectICCmd::Do(), ZoomInCmd::Do(), ZoomOutCmd::Do(), ToggleUnitDetailsCmd::isChecked(), BlocksConnectICCmd::isEnabled(), FullyConnectBussesCmd::isEnabled(), ProDeExportCmd::isEnabled(), RedoCmd::isEnabled(), UndoCmd::isEnabled(), VLIWConnectICCmd::isEnabled(), and setView().
Member Data Documentation
view_
wxView* EditorCommand::view_ private
The view assigned for the command.
Definition at line 58 of file EditorCommand.hh.
Referenced by setView(), and view().
The documentation for this class was generated from the following files:
EditorCommand.hh
EditorCommand.cc