OpenASIP: CostEstimationDataDialog Class Reference
CostEstimationDataDialog Class Reference
#include <CostEstimationDataDialog.hh>
Public Member Functions
CostEstimationDataDialog (wxWindow *parent, wxWindowID id, HDB::HDBManager &hdb, RowID pluginID, RowID dataID)
virtual ~CostEstimationDataDialog ()
Private Types
enum {
ID_ENTRY_TYPE = 10000 , ID_ENTRY_ID , ID_NAME , ID_VALUE ,
ID_TEXT , ID_LINE
}
widget IDs
Private Member Functions
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
void onEntryTypeSelection (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
HDB::HDBManager & hdb_
HDB Containing the data.
RowID pluginID_
ID of the data's parent plugin.
RowID dataID_
ID of the data to modify, or -1 if new data is being added.
wxChoice * typeChoice_
Entry reference type choice widget.
wxChoice * idChoice_
Entry reference id choice widget.
wxString name_
Name of the data.
wxString value_
Value of the data.
Static Private Attributes
static const wxString ENTRY_TYPE_NONE = _T("None")
static const wxString ENTRY_TYPE_FU = _T("FU")
static const wxString ENTRY_TYPE_RF = _T("RF")
static const wxString ENTRY_TYPE_BUS = _T("Bus")
static const wxString ENTRY_TYPE_SOCKET = _T("Socket")
Detailed Description
Dialog for adding and modifying cost function plugin data.
Definition at line 46 of file CostEstimationDataDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
widget IDs
Enumerator
ID_ENTRY_TYPE
ID_ENTRY_ID
ID_NAME
ID_VALUE
ID_TEXT
ID_LINE
Definition at line 62 of file CostEstimationDataDialog.hh.
         {
        ID_ENTRY_TYPE = 10000,
        ID_ENTRY_ID,
        ID_NAME,
        ID_VALUE,
        ID_TEXT,
        ID_LINE
    };
Constructor & Destructor Documentation
CostEstimationDataDialog()
CostEstimationDataDialog::CostEstimationDataDialog (wxWindow * parent, wxWindowID id, HDB::HDBManager & hdb, RowID pluginID, RowID dataID)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog.
hdb HDBManager where the data is added/modified.
dataID ID of the cost data to modify or -1 if a new data is being added.
Definition at line 63 of file CostEstimationDataDialog.cc.
                 :
    wxDialog(parent, id, _T("Cost Estimation Data")),
    hdb_(hdb), pluginID_(pluginID), dataID_(dataID) {
    createContents(this, true, true);
    typeChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_ENTRY_TYPE));
    idChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_ENTRY_ID));
    typeChoice_->Append(ENTRY_TYPE_NONE);
    typeChoice_->Append(ENTRY_TYPE_FU);
    typeChoice_->Append(ENTRY_TYPE_RF);
    typeChoice_->Append(ENTRY_TYPE_BUS);
    typeChoice_->Append(ENTRY_TYPE_SOCKET);
    FindWindow(ID_NAME)->SetValidator(wxGenericValidator(&name_));
    FindWindow(ID_VALUE)->SetValidator(wxGenericValidator(&value_));
    if (dataID_ >= 0) {
        typeChoice_->Disable();
        idChoice_->Disable();
    }
}
~CostEstimationDataDialog()
CostEstimationDataDialog::~CostEstimationDataDialog () virtual
The Destructor.
Definition at line 93 of file CostEstimationDataDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * CostEstimationDataDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 239 of file CostEstimationDataDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Entry type:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxChoice *item3 = new wxChoice( parent, ID_ENTRY_TYPE, wxDefaultPosition, wxSize(100,-1), 0, strs3, 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_TEXT, wxT("Entry ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_ENTRY_ID, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item1->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Value:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item8, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item9 = new wxTextCtrl( parent, ID_VALUE, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item1->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item10 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item10, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item12 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item13 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item11, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ENTRY_ID, ID_ENTRY_TYPE, ID_LINE, ID_NAME, ID_TEXT, and ID_VALUE.
onEntryTypeSelection()
void CostEstimationDataDialog::onEntryTypeSelection (wxCommandEvent & event) private
Event handler for the entry type choicer selections.
Definition at line 137 of file CostEstimationDataDialog.cc.
{
    idChoice_->Clear();
    if (typeChoice_->GetStringSelection() == ENTRY_TYPE_FU) {
        // Append FU entry IDs to the entry id choicer
        const std::set<RowID> fuIDs = hdb_.fuEntryIDs();
        std::set<RowID>::const_iterator iter = fuIDs.begin();
        for (; iter != fuIDs.end(); iter++) {
            idChoice_->Append(WxConversion::toWxString(*iter));
        }
    } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_RF) {
        // Append RF entry IDs to the entry id choicer
        const std::set<RowID> rfIDs = hdb_.rfEntryIDs();
        std::set<RowID>::const_iterator iter = rfIDs.begin();
        for (; iter != rfIDs.end(); iter++) {
            idChoice_->Append(WxConversion::toWxString(*iter));
        }
    } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_BUS) {
        // Append FU entry IDs to the entry id choicer
        const std::set<RowID> busIDs = hdb_.busEntryIDs();
        std::set<RowID>::const_iterator iter = busIDs.begin();
        for (; iter != busIDs.end(); iter++) {
            idChoice_->Append(WxConversion::toWxString(*iter));
        }
    } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_SOCKET) {
        // Append FU entry IDs to the entry id choicer
        const std::set<RowID> socketIDs = hdb_.socketEntryIDs();
        std::set<RowID>::const_iterator iter = socketIDs.begin();
        for (; iter != socketIDs.end(); iter++) {
            idChoice_->Append(WxConversion::toWxString(*iter));
        }
    } else {
        idChoice_->Disable();
        return;
    }
    idChoice_->Enable();
    idChoice_->SetSelection(0);
}
References HDB::HDBManager::busEntryIDs(), ENTRY_TYPE_BUS, ENTRY_TYPE_FU, ENTRY_TYPE_RF, ENTRY_TYPE_SOCKET, HDB::HDBManager::fuEntryIDs(), hdb_, idChoice_, HDB::HDBManager::rfEntryIDs(), HDB::HDBManager::socketEntryIDs(), WxConversion::toWxString(), and typeChoice_.
Referenced by TransferDataToWindow().
onOK()
void CostEstimationDataDialog::onOK (wxCommandEvent & event) private
Event handler for the ok-button.
Definition at line 183 of file CostEstimationDataDialog.cc.
{
     TransferDataFromWindow();
     if (name_.IsEmpty()) {
             wxString message(_T("Data name not set."));
             ErrorDialog dialog(this, message);
             dialog.ShowModal();
             return;
     }
     CostEstimationData data;
     data.setPluginID(pluginID_);
     data.setName(WxConversion::toString(name_));
     DataObject value(WxConversion::toString(value_));
     data.setValue(value);
     std::string idStr =
         WxConversion::toString(idChoice_->GetStringSelection());
     if (typeChoice_->GetStringSelection() != ENTRY_TYPE_NONE) {
         if (idStr == "") {
             wxString message(_T("Invalid entry reference."));
             ErrorDialog dialog(this, message);
             dialog.ShowModal();
             return;
         }
         RowID id = Conversion::toInt(idStr);
         if (typeChoice_->GetStringSelection() == ENTRY_TYPE_FU) {
             data.setFUReference(id);
         } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_RF) {
             data.setRFReference(id);
         } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_BUS) {
             data.setBusReference(id);
         } else if (typeChoice_->GetStringSelection() == ENTRY_TYPE_SOCKET) {
             data.setSocketReference(id);
         }
     }
     if (dataID_ >= 0) {
         hdb_.modifyCostEstimationData(dataID_, data);
     } else {
         hdb_.addCostEstimationData(data);
     }
     EndModal(wxID_OK);
}
References HDB::HDBManager::addCostEstimationData(), dataID_, ENTRY_TYPE_BUS, ENTRY_TYPE_FU, ENTRY_TYPE_NONE, ENTRY_TYPE_RF, ENTRY_TYPE_SOCKET, hdb_, idChoice_, HDB::HDBManager::modifyCostEstimationData(), name_, pluginID_, CostEstimationData::setBusReference(), CostEstimationData::setFUReference(), CostEstimationData::setName(), CostEstimationData::setPluginID(), CostEstimationData::setRFReference(), CostEstimationData::setSocketReference(), CostEstimationData::setValue(), Conversion::toInt(), WxConversion::toString(), typeChoice_, and value_.
TransferDataToWindow()
bool CostEstimationDataDialog::TransferDataToWindow () private virtual
Transfers data to the dialog widgets.
Returns
True, if the data was succesfully transferred.
Definition at line 102 of file CostEstimationDataDialog.cc.
{
    if (dataID_ >= 0) {
        const CostEstimationData data = hdb_.costEstimationData(dataID_);
        name_ = WxConversion::toWxString(data.name());
        value_ = WxConversion::toWxString(data.value().stringValue());
        if (data.hasFUReference()) {
            typeChoice_->SetStringSelection(ENTRY_TYPE_FU);
            idChoice_->Append(WxConversion::toWxString(data.fuReference()));
        } else if (data.hasRFReference()) {
            typeChoice_->SetStringSelection(ENTRY_TYPE_RF);
            idChoice_->Append(WxConversion::toWxString(data.rfReference()));
        } else if (data.hasBusReference()) {
            typeChoice_->SetStringSelection(ENTRY_TYPE_BUS);
            idChoice_->Append(WxConversion::toWxString(data.busReference()));
        } else if (data.hasSocketReference()) {
            typeChoice_->SetStringSelection(ENTRY_TYPE_SOCKET);
            idChoice_->Append(
                WxConversion::toWxString(data.socketReference()));
        }
        idChoice_->SetSelection(0);
    } else {
        typeChoice_->SetSelection(0);
        wxCommandEvent dummy;
        onEntryTypeSelection(dummy);
    }
    return wxDialog::TransferDataToWindow();
}
References CostEstimationData::busReference(), HDB::HDBManager::costEstimationData(), dataID_, dummy, ENTRY_TYPE_BUS, ENTRY_TYPE_FU, ENTRY_TYPE_RF, ENTRY_TYPE_SOCKET, CostEstimationData::fuReference(), CostEstimationData::hasBusReference(), CostEstimationData::hasFUReference(), CostEstimationData::hasRFReference(), CostEstimationData::hasSocketReference(), hdb_, idChoice_, CostEstimationData::name(), name_, onEntryTypeSelection(), CostEstimationData::rfReference(), CostEstimationData::socketReference(), DataObject::stringValue(), WxConversion::toWxString(), typeChoice_, CostEstimationData::value(), and value_.
Member Data Documentation
dataID_
RowID CostEstimationDataDialog::dataID_ private
ID of the data to modify, or -1 if new data is being added.
Definition at line 76 of file CostEstimationDataDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
ENTRY_TYPE_BUS
const wxString CostEstimationDataDialog::ENTRY_TYPE_BUS = _T("Bus") static private
Definition at line 89 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
ENTRY_TYPE_FU
const wxString CostEstimationDataDialog::ENTRY_TYPE_FU = _T("FU") static private
Definition at line 87 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
ENTRY_TYPE_NONE
const wxString CostEstimationDataDialog::ENTRY_TYPE_NONE = _T("None") static private
Definition at line 86 of file CostEstimationDataDialog.hh.
Referenced by onOK().
ENTRY_TYPE_RF
const wxString CostEstimationDataDialog::ENTRY_TYPE_RF = _T("RF") static private
Definition at line 88 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
ENTRY_TYPE_SOCKET
const wxString CostEstimationDataDialog::ENTRY_TYPE_SOCKET = _T("Socket") static private
Definition at line 90 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
hdb_
HDB::HDBManager& CostEstimationDataDialog::hdb_ private
HDB Containing the data.
Definition at line 72 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
idChoice_
wxChoice* CostEstimationDataDialog::idChoice_ private
Entry reference id choice widget.
Definition at line 80 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
name_
wxString CostEstimationDataDialog::name_ private
Name of the data.
Definition at line 82 of file CostEstimationDataDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
pluginID_
RowID CostEstimationDataDialog::pluginID_ private
ID of the data's parent plugin.
Definition at line 74 of file CostEstimationDataDialog.hh.
Referenced by onOK().
typeChoice_
wxChoice* CostEstimationDataDialog::typeChoice_ private
Entry reference type choice widget.
Definition at line 78 of file CostEstimationDataDialog.hh.
Referenced by onEntryTypeSelection(), onOK(), and TransferDataToWindow().
value_
wxString CostEstimationDataDialog::value_ private
Value of the data.
Definition at line 84 of file CostEstimationDataDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
CostEstimationDataDialog.hh
CostEstimationDataDialog.cc