OpenASIP: IndexBound Class Reference
IndexBound Class Reference
#include <IndexBound.hh>
Public Member Functions
IndexBound (unsigned int startIndex, unsigned int endIndex)
IndexBound (unsigned int startIndex, unsigned int endIndex, int limmWidth, int limmLeftIndex, int limmRightIndex)
~IndexBound ()
unsigned int slotStartIndex () const
unsigned int slotEndIndex () const
void incrStartIndex (unsigned int increment)
void incrEndIndex (unsigned int increment)
bool isLimmEncoded () const
int limmWidth () const
int limmLeftIndex () const
int limmRightIndex () const
Private Member Functions
IndexBound ()
Private Attributes
unsigned int slotStartIndex_
Start index of the moveslot in instruction.
unsigned int slotEndIndex_
End index of the moveslot in instruction.
bool usesLimm_
Is address encoded in long immediate.
int limmWidth_
Width of the long immediate chunk in this moveslot.
int limmValueLeftBitIndex_
Index of the left most bit (MSB) of the value to be encoded in this slot.
int limmValueRightBitIndex_
Index of the right most bit (LSB) of the value to be encoded in this slot.
Detailed Description
Class for storing index information needed for fixing instruction addresses in InstructionBitVector
Definition at line 40 of file IndexBound.hh.
Constructor & Destructor Documentation
IndexBound() [1/3]
IndexBound::IndexBound (unsigned int startIndex, unsigned int endIndex)
Constructor for moveslot bound indices
Definition at line 38 of file IndexBound.cc.
                                                                    :
    slotStartIndex_(startIndex), slotEndIndex_(endIndex), usesLimm_(false),
    limmWidth_(0), limmValueLeftBitIndex_(0), limmValueRightBitIndex_(0) {
}
IndexBound() [2/3]
IndexBound::IndexBound (unsigned int startIndex, unsigned int endIndex, int limmWidth, int limmLeftIndex, int limmRightIndex)
Constructor for moveslot bounds and limm slot bound indices
Definition at line 46 of file IndexBound.cc.
                       :
    slotStartIndex_(startIndex), slotEndIndex_(endIndex), usesLimm_(true),
    limmWidth_(limmWidth), limmValueLeftBitIndex_(limmLeftIndex),
    limmValueRightBitIndex_(limmRightIndex) {
}
~IndexBound()
IndexBound::~IndexBound ()
The destructor.
Definition at line 60 of file IndexBound.cc.
{
}
IndexBound() [3/3]
IndexBound::IndexBound () private
Member Function Documentation
incrEndIndex()
void IndexBound::incrEndIndex (unsigned int increment)
Increment end bit index.
Useful for converting the move slot index to absolute position inside the instruction bit stream
Parameters
increment Value to be added to the end index
Definition at line 109 of file IndexBound.cc.
{
    slotEndIndex_ += increment;
}
References slotEndIndex_.
incrStartIndex()
void IndexBound::incrStartIndex (unsigned int increment)
Increment start bit index.
Useful for converting the move slot index to absolute position inside the instruction bit stream.
Parameters
increment Value to be added to the start index
Definition at line 95 of file IndexBound.cc.
{
    slotStartIndex_ += increment;
}
References slotStartIndex_.
isLimmEncoded()
bool IndexBound::isLimmEncoded () const
Is long immediate encoding utilized in this move slot
Returns
Is long immediate utilized in this move slot
Definition at line 120 of file IndexBound.cc.
{
    return usesLimm_;
}
References usesLimm_.
limmLeftIndex()
int IndexBound::limmLeftIndex () const
Query the leftmost (MSB) index of the long immediate value in this slot
This tells the leftmost bit of the long immediate value this slot is going to encode, not the position of the limm slot inside the instruction. Notice that the indexing starts from zero.
Returns
Leftmost bit of the LIMM value this slot is encoding
Definition at line 146 of file IndexBound.cc.
{
    return limmValueLeftBitIndex_;
}
References limmValueLeftBitIndex_.
Referenced by InstructionBitVector::fixBits().
limmRightIndex()
int IndexBound::limmRightIndex () const
Query the rightmost (LSB) index of the long immediate value in this slot
This tells the rightmost bit of the long immediate value this slot is going to encode, not the position of the limm slot inside the instruction. Notice that the indexing starts from zero.
Returns
Rightmost bit of the LIMM value this slot is encoding
Definition at line 161 of file IndexBound.cc.
{
    return limmValueRightBitIndex_;
}
References limmValueRightBitIndex_.
Referenced by InstructionBitVector::fixBits().
limmWidth()
int IndexBound::limmWidth () const
Query the width of the limm slot
Returns
Width of the limm slot. 0 if limm is not used
Definition at line 131 of file IndexBound.cc.
{
    return limmWidth_;
}
References limmWidth_.
Referenced by InstructionBitVector::fixBits().
slotEndIndex()
unsigned int IndexBound::slotEndIndex () const
Move slot end index
Returns
End bit index of the move slot
Definition at line 81 of file IndexBound.cc.
{
    return slotEndIndex_;
}
References slotEndIndex_.
Referenced by InstructionBitVector::addIndexBoundsForReference(), and InstructionBitVector::fixBits().
slotStartIndex()
unsigned int IndexBound::slotStartIndex () const
Move slot start index
Returns
Starting bit index of the move slot
Definition at line 70 of file IndexBound.cc.
{
    return slotStartIndex_;
}
References slotStartIndex_.
Referenced by InstructionBitVector::addIndexBoundsForReference(), and InstructionBitVector::fixBits().
Member Data Documentation
limmValueLeftBitIndex_
int IndexBound::limmValueLeftBitIndex_ private
Index of the left most bit (MSB) of the value to be encoded in this slot.
Definition at line 83 of file IndexBound.hh.
Referenced by limmLeftIndex().
limmValueRightBitIndex_
int IndexBound::limmValueRightBitIndex_ private
Index of the right most bit (LSB) of the value to be encoded in this slot.
Definition at line 86 of file IndexBound.hh.
Referenced by limmRightIndex().
limmWidth_
int IndexBound::limmWidth_ private
Width of the long immediate chunk in this moveslot.
Definition at line 80 of file IndexBound.hh.
Referenced by limmWidth().
slotEndIndex_
unsigned int IndexBound::slotEndIndex_ private
End index of the moveslot in instruction.
Definition at line 76 of file IndexBound.hh.
Referenced by incrEndIndex(), and slotEndIndex().
slotStartIndex_
unsigned int IndexBound::slotStartIndex_ private
Start index of the moveslot in instruction.
Definition at line 74 of file IndexBound.hh.
Referenced by incrStartIndex(), and slotStartIndex().
usesLimm_
bool IndexBound::usesLimm_ private
Is address encoded in long immediate.
Definition at line 78 of file IndexBound.hh.
Referenced by isLimmEncoded().
The documentation for this class was generated from the following files:
IndexBound.hh
IndexBound.cc