OpenASIP: ImmediateSlotField Class Reference
ImmediateSlotField Class Reference
#include <ImmediateSlotField.hh>
Public Member Functions
ImmediateSlotField (const std::string &name, int width, BinaryEncoding &parent)
ImmediateSlotField (const ObjectState *state, BinaryEncoding &parent)
virtual ~ImmediateSlotField ()
BinaryEncoding * parent () const
std::string name () const
void setName (const std::string &name)
virtual int childFieldCount () const
virtual int width () const
void setWidth (int width)
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
virtual InstructionField & childField (int position) const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_IMMEDIATE_SLOT_FIELD
ObjectState name for immediate slot field.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the immediate slot.
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for the width of the field.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Attributes
std::string name_
Name of the immediate slot.
int width_
The bit width of the field.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
ImmediateSlotField represents a dedicated immediate slot in TTA instruction.
Definition at line 44 of file ImmediateSlotField.hh.
Constructor & Destructor Documentation
ImmediateSlotField() [1/2]
ImmediateSlotField::ImmediateSlotField (const std::string & name, int width, BinaryEncoding & parent)
The constructor.
Parameters
name Name of the immediate slot programmed by this field.
width Bit width of the field. @parent The parent binary encoding map.
Exceptions
OutOfRange If the bit width is smaller than 1.
ObjectAlreadyExists If the parent binary encoding already has an immediate slot with the given name.
Definition at line 57 of file ImmediateSlotField.cc.
    : InstructionField(&parent), name_(name), width_(width) {
    if (width < 1) {
        const string procName = "ImmediateSlotField::ImmediateSlotField";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    setParent(NULL);
    parent.addImmediateSlot(*this);
    setParent(&parent);
}
References BinaryEncoding::addImmediateSlot(), parent(), InstructionField::setParent(), and width().
ImmediateSlotField() [2/2]
ImmediateSlotField::ImmediateSlotField (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 79 of file ImmediateSlotField.cc.
    : InstructionField(state, &parent), name_(""), width_(0) {
    loadState(state);
    setParent(NULL);
    parent.addImmediateSlot(*this);
    setParent(&parent);
}
References BinaryEncoding::addImmediateSlot(), loadState(), parent(), and InstructionField::setParent().
~ImmediateSlotField()
ImmediateSlotField::~ImmediateSlotField () virtual
The destructor.
Definition at line 91 of file ImmediateSlotField.cc.
{
    BinaryEncoding* parent = this->parent();
    assert(parent != NULL);
    setParent(NULL);
    parent->removeImmediateSlot(*this);
}
References assert, parent(), BinaryEncoding::removeImmediateSlot(), and InstructionField::setParent().
Member Function Documentation
childFieldCount()
int ImmediateSlotField::childFieldCount () const virtual
Returns 0 always since immediate slot does not have any child fields.
Returns
0.
Implements InstructionField.
Definition at line 156 of file ImmediateSlotField.cc.
{
    return 0;
}
loadState()
void ImmediateSlotField::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Definition at line 210 of file ImmediateSlotField.cc.
{
    const string procName = "ImmediateSlotField::loadState";
    if (state->name() != OSNAME_IMMEDIATE_SLOT_FIELD) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    InstructionField::loadState(state);
    try {
        setName(state->stringAttribute(OSKEY_NAME));
        setWidth(state->intAttribute(OSKEY_WIDTH));
    } catch (const Exception&) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References ObjectState::intAttribute(), InstructionField::loadState(), ObjectState::name(), OSKEY_NAME, OSKEY_WIDTH, OSNAME_IMMEDIATE_SLOT_FIELD, setName(), setWidth(), and ObjectState::stringAttribute().
Referenced by ImmediateSlotField().
name()
std::string ImmediateSlotField::name () const
Returns the name of the immediate slot programmed by this field.
Returns
The name of the immediate slot.
Definition at line 123 of file ImmediateSlotField.cc.
{
    return name_;
}
References name_.
Referenced by CodeCompressorPlugin::addBitsForImmediateSlot(), BinaryEncoding::addImmediateSlot(), BinaryEncoding::hasImmediateSlot(), BinaryEncoding::immediateSlot(), printInstructionLayout(), saveState(), setName(), DefaultDecoderGenerator::writeImmediateSlotSignals(), and DefaultDecoderGenerator::writeInstructionDismembering().
parent()
BinaryEncoding * ImmediateSlotField::parent () const
Returns the parent binary encoding map.
Returns
The parent binary encoding map.
Definition at line 105 of file ImmediateSlotField.cc.
{
    InstructionField* parent = InstructionField::parent();
    if (parent == NULL) {
        return NULL;
    } else {
        BinaryEncoding* bemParent = dynamic_cast<BinaryEncoding*>(parent);
        assert(bemParent != NULL);
        return bemParent;
    }
}
References assert, parent(), and InstructionField::parent().
Referenced by BinaryEncoding::addImmediateSlot(), ImmediateSlotField(), ImmediateSlotField(), parent(), BinaryEncoding::removeImmediateSlot(), setName(), and ~ImmediateSlotField().
saveState()
ObjectState * ImmediateSlotField::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from InstructionField.
Definition at line 193 of file ImmediateSlotField.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_IMMEDIATE_SLOT_FIELD);
    state->setAttribute(OSKEY_NAME, name());
    state->setAttribute(OSKEY_WIDTH, width());
    return state;
}
References name(), OSKEY_NAME, OSKEY_WIDTH, OSNAME_IMMEDIATE_SLOT_FIELD, InstructionField::saveState(), ObjectState::setAttribute(), ObjectState::setName(), and width().
Referenced by BinaryEncoding::saveState().
setName()
void ImmediateSlotField::setName (const std::string & name)
Sets the name of the immediate slot programmed by this field.
Parameters
name The name.
Exceptions
ObjectAlreadyExists If the parent binary encoding has an immediate slot field for the given immediate slot already.
Definition at line 137 of file ImmediateSlotField.cc.
{
    if (name == this->name()) {
        return;
    }
    if (parent()->hasImmediateSlot(name)) {
        const string procName = "ImmediateSlotField::setName";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        name_ = name;
    }
}
References name(), name_, and parent().
Referenced by loadState().
setWidth()
void ImmediateSlotField::setWidth (int width)
Sets the bit width of the field.
Parameters
width The new bit width.
Exceptions
OutOfRange If the given width is smaller than 1.
Definition at line 179 of file ImmediateSlotField.cc.
{
    if (width < 1) {
        const string procName = "ImmediateSlotField::setWidth";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    width_ = width;
}
References width(), and width_.
Referenced by loadState().
width()
int ImmediateSlotField::width () const virtual
Returns the bit width of the field.
Returns
The bit width.
Implements InstructionField.
Definition at line 167 of file ImmediateSlotField.cc.
{
    return width_;
}
References width_.
Referenced by CodeCompressorPlugin::addBitsForImmediateSlot(), CodeCompressorPlugin::bemInstructionBits(), BEMValidator::checkImmediateSlot(), ImmediateSlotField(), printInstructionLayout(), saveState(), setWidth(), BinaryEncoding::width(), DefaultDecoderGenerator::writeImmediateSlotSignals(), and DefaultDecoderGenerator::writeInstructionDismembering().
Member Data Documentation
name_
std::string ImmediateSlotField::name_ private
Name of the immediate slot.
Definition at line 71 of file ImmediateSlotField.hh.
Referenced by name(), and setName().
OSKEY_NAME
const std::string ImmediateSlotField::OSKEY_NAME = "name" static
ObjectState attribute key for the name of the immediate slot.
Definition at line 65 of file ImmediateSlotField.hh.
Referenced by BEMSerializer::immediateSlotToFile(), BEMSerializer::immediateSlotToOM(), loadState(), and saveState().
OSKEY_WIDTH
const std::string ImmediateSlotField::OSKEY_WIDTH = "width" static
ObjectState attribute key for the width of the field.
Definition at line 67 of file ImmediateSlotField.hh.
Referenced by BEMSerializer::immediateSlotToFile(), BEMSerializer::immediateSlotToOM(), loadState(), and saveState().
OSNAME_IMMEDIATE_SLOT_FIELD
const std::string ImmediateSlotField::OSNAME_IMMEDIATE_SLOT_FIELD static
Initial value:
=
    "imm_slot_field"
ObjectState name for immediate slot field.
Definition at line 63 of file ImmediateSlotField.hh.
Referenced by BEMSerializer::convertToFileFormat(), BEMSerializer::immediateSlotToOM(), BinaryEncoding::loadState(), loadState(), and saveState().
width_
int ImmediateSlotField::width_ private
The bit width of the field.
Definition at line 73 of file ImmediateSlotField.hh.
Referenced by setWidth(), and width().
The documentation for this class was generated from the following files:
ImmediateSlotField.hh
ImmediateSlotField.cc