OpenASIP: TPEF::RelocSection Class Reference
TPEF::RelocSection Class Reference
#include <RelocSection.hh>
Public Member Functions
virtual ~RelocSection ()
virtual SectionType type () const
Section * referencedSection () const
void setReferencedSection (Section *section)
void setReferencedSection (const ReferenceManager::SafePointer *section)
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
RelocSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * refSection_
Section whose elements are being relocated by relocations of this section.
Static Private Attributes
static RelocSection proto_
Prototype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Relocation table section.
Definition at line 47 of file RelocSection.hh.
Constructor & Destructor Documentation
~RelocSection()
TPEF::RelocSection::~RelocSection () virtual
Destructor.
Definition at line 64 of file RelocSection.cc.
{
}
RelocSection()
TPEF::RelocSection::RelocSection (bool init) protected
Constructor.
Parameters
init True if registeration is wanted.
Definition at line 49 of file RelocSection.cc.
                                    :
    Section(), refSection_(&SafePointer::null) {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagVLen();
    unsetFlagNoBits();
    setStartingAddress(0);
}
References TPEF::Section::registerSection(), TPEF::Section::setStartingAddress(), TPEF::Section::unsetFlagNoBits(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
clone()
Section * TPEF::RelocSection::clone () const protected virtual
Creates an instance of class.
Returns
Newly created section.
Implements TPEF::Section.
Definition at line 83 of file RelocSection.cc.
{
    return new RelocSection(false);
}
referencedSection()
Section * TPEF::RelocSection::referencedSection () const
Referenced by TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::findOrCreateRelocationSection(), CodeCompressorPlugin::initializeRelocations(), TPEF::AOutRelocationSectionReader::readData(), ProgramImageGenerator::relocTarget(), and TPEFDumper::section().
setReferencedSection() [1/2]
void TPEF::RelocSection::setReferencedSection (const ReferenceManager::SafePointer * section)
setReferencedSection() [2/2]
void TPEF::RelocSection::setReferencedSection (Section * section)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::findOrCreateRelocationSection(), and TPEF::AOutReader::readData().
type()
Section::SectionType TPEF::RelocSection::type () const virtual
Returns section's type.
Returns
Type of section.
Implements TPEF::Section.
Definition at line 73 of file RelocSection.cc.
{
    return ST_RELOC;
}
References TPEF::Section::ST_RELOC.
Member Data Documentation
proto_
RelocSection TPEF::RelocSection::proto_ static private
Prototype instance of section.
Definition at line 64 of file RelocSection.hh.
refSection_
const ReferenceManager::SafePointer* TPEF::RelocSection::refSection_ private
Section whose elements are being relocated by relocations of this section.
Definition at line 67 of file RelocSection.hh.
The documentation for this class was generated from the following files:
RelocSection.hh
RelocSection.cc