OpenASIP: ProDeBridgeEditPolicy Class Reference
ProDeBridgeEditPolicy Class Reference
#include <ProDeBridgeEditPolicy.hh>
Public Member Functions
ProDeBridgeEditPolicy ()
virtual ~ProDeBridgeEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ProDeBridgeEditPolicy & operator= (ProDeBridgeEditPolicy &old)
Assignment not allowed.
ProDeBridgeEditPolicy (ProDeBridgeEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a bridge EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports. the Request.
Definition at line 49 of file ProDeBridgeEditPolicy.hh.
Constructor & Destructor Documentation
ProDeBridgeEditPolicy() [1/2]
ProDeBridgeEditPolicy::ProDeBridgeEditPolicy ()
The Constructor.
Definition at line 52 of file ProDeBridgeEditPolicy.cc.
                                            : EditPolicy() {
}
~ProDeBridgeEditPolicy()
ProDeBridgeEditPolicy::~ProDeBridgeEditPolicy () virtual
The Destructor.
Definition at line 58 of file ProDeBridgeEditPolicy.cc.
{
}
ProDeBridgeEditPolicy() [2/2]
ProDeBridgeEditPolicy::ProDeBridgeEditPolicy (ProDeBridgeEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeBridgeEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 101 of file ProDeBridgeEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
    type == Request::DELETE_REQUEST ||
        type == Request::STATUS_REQUEST) {
    return true;
    } else {
    return false;
    }
}
References Request::DELETE_REQUEST, Request::MODIFY_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProDeBridgeEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 68 of file ProDeBridgeEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifyBridgeCmd* modifyCmd = new ModifyBridgeCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteBridgeCmd* deleteCmd = new DeleteBridgeCmd(host_);
        return deleteCmd;
    } else if (type == Request::STATUS_REQUEST) {
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        Bridge* bridge = dynamic_cast<Bridge*>(host_->model());
        format fmt = generator->text(ProDeTextGenerator::STATUS_BRIDGE);
        fmt % bridge->name();
        SetStatusTextCmd*  statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else {
    return NULL;
    }
}
References Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), ProDeTextGenerator::STATUS_BRIDGE, Request::STATUS_REQUEST, Texts::TextGenerator::text(), and Request::type().
operator=()
ProDeBridgeEditPolicy & ProDeBridgeEditPolicy::operator= (ProDeBridgeEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeBridgeEditPolicy.hh
ProDeBridgeEditPolicy.cc