OpenASIP: PSocketResource Class Reference
PSocketResource Class Reference
#include <PSocketResource.hh>
Public Member Functions
virtual ~PSocketResource ()
PSocketResource (const std::string &name, unsigned int initiationInterval=0)
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
void clear () override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual bool operator< (const SchedulingResource &other) const
virtual void setMaxCycle (unsigned int)
Protected Types
typedef std::map< int, std::set< MoveNode * > > ResourceRecordType
Protected Attributes
ResourceRecordType resourceRecord_
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Private Member Functions
PSocketResource (const PSocketResource &)
PSocketResource & operator= (const PSocketResource &)
Additional Inherited Members
Protected Member Functions inherited from SchedulingResource
virtual bool validateDependentGroups ()
virtual bool validateRelatedGroups ()
Detailed Description
An interface for scheduling resources of Resource Model.
The derived class PSocketResource represents a combined resource of a FU/RF port and a socket that connects it to a bus.
Definition at line 48 of file PSocketResource.hh.
Member Typedef Documentation
ResourceRecordType
typedef std::map<int, std::set<MoveNode*> > PSocketResource::ResourceRecordType protected
Definition at line 61 of file PSocketResource.hh.
Constructor & Destructor Documentation
~PSocketResource()
PSocketResource::~PSocketResource () virtual
Empty constructor
Definition at line 52 of file PSocketResource.cc.
{}
PSocketResource() [1/2]
PSocketResource::PSocketResource (const std::string & name, unsigned int initiationInterval = 0)
Constructor defining name of resource
Parameters
name Name of resource
Definition at line 46 of file PSocketResource.cc.
                                                                                       :
    SchedulingResource(name, initiationInterval) {}
PSocketResource() [2/2]
PSocketResource::PSocketResource (const PSocketResource &) private
Member Function Documentation
assign()
void PSocketResource::assign (const int cycle, MoveNode & mn) override virtual
Assign resource to given node for given cycle.
Parameters
cycle Cycle to assign
node MoveNode to assign
Exceptions
In case PSocket can not be assigned
Note
Exception is internal error, resource should be tested with canAssign() before assign() is called.
Implements SchedulingResource.
Reimplemented in OutputPSocketResource.
Definition at line 105 of file PSocketResource.cc.
{
    resourceRecord_[instructionIndex(cycle)].insert(&mn);
    increaseUseCount();
    return;
}
References SchedulingResource::increaseUseCount(), SchedulingResource::instructionIndex(), and resourceRecord_.
Referenced by OutputPSocketResource::assign().
canAssign()
bool PSocketResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Return true if resource can be assigned for given resource in given cycle.
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Implements SchedulingResource.
Reimplemented in InputPSocketResource, and OutputPSocketResource.
Definition at line 139 of file PSocketResource.cc.
{
    ResourceRecordType::const_iterator iter = resourceRecord_.find(cycle);
    if (iter != resourceRecord_.end()) {
        const std::set<MoveNode*>& movesInCycle = iter->second;
        for (std::set<MoveNode*>::const_iterator i = movesInCycle.begin();
             i != movesInCycle.end(); i++) {
            MoveNode* mn = *i;
#ifdef NO_OVERCOMMIT
            return false;
#else
            if (node.move().isUnconditional() ||
                mn->move().isUnconditional()) {
                return false;
            }
            if (!node.move().guard().guard().isOpposite(
                    mn->move().guard().guard())) {
                return false;
            }
#endif
        }
    }
    return true;
}
References TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), TTAMachine::Guard::isOpposite(), TTAProgram::Move::isUnconditional(), MoveNode::move(), and resourceRecord_.
clear()
void PSocketResource::clear () override virtual
Clears bookkeeping of the scheduling resource.
After this call the state of the resource should be identical to a newly-created and initialized resource.
Reimplemented from SchedulingResource.
Definition at line 171 of file PSocketResource.cc.
                       {
    SchedulingResource::clear();
    resourceRecord_.clear();
}
References SchedulingResource::clear(), and resourceRecord_.
Referenced by OutputPSocketResource::clear().
isAvailable()
bool PSocketResource::isAvailable (const int cycle) const override virtual
Test if resource PSocketResource is available
Parameters
cycle Cycle which to test
Returns
True if p-socket is available in cycle
Implements SchedulingResource.
Reimplemented in OutputPSocketResource.
Definition at line 80 of file PSocketResource.cc.
{
    ResourceRecordType::const_iterator iter =
        resourceRecord_.find(instructionIndex(cycle));
    if (iter != resourceRecord_.end() && iter->second.size() > 0) {
        const std::set<MoveNode*>& movesInCycle = iter->second;
        for (std::set<MoveNode*>::const_iterator i = movesInCycle.begin();
             i != movesInCycle.end(); i++) {
            if ((*i)->move().isUnconditional()) {
                return false;
            }
        }
    }
    return true;
}
References SchedulingResource::instructionIndex(), and resourceRecord_.
isInUse()
bool PSocketResource::isInUse (const int cycle) const override virtual
Test if resource PSocketResource is used in given cycle
The PSocket is inUse if it is read from or written to at least once.
Parameters
cycle Cycle which to test
Returns
True if p-socket is already used in cycle
Implements SchedulingResource.
Definition at line 64 of file PSocketResource.cc.
{
    ResourceRecordType::const_iterator iter =
        resourceRecord_.find(instructionIndex(cycle));
    if (iter != resourceRecord_.end() && iter->second.size() > 0) {
        return true;
    }
    return false;
}
References SchedulingResource::instructionIndex(), and resourceRecord_.
Referenced by unassign().
operator=()
PSocketResource & PSocketResource::operator= (const PSocketResource &) private
unassign()
void PSocketResource::unassign (const int cycle, MoveNode & mn) override virtual
Unassign resource from given node for given cycle.
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
Exceptions
In case the PSocket was not assigned before.
Implements SchedulingResource.
Reimplemented in OutputPSocketResource.
Definition at line 120 of file PSocketResource.cc.
{
    if (isInUse(cycle)) {
        resourceRecord_[instructionIndex(cycle)].erase(&mn);
        decreaseUseCount();
        return;
    }
    std::string msg = "PSocket was not assigned so it can not be unassigned!";
    throw InvalidData(__FILE__, __LINE__, __func__, msg);
}
References __func__, SchedulingResource::decreaseUseCount(), SchedulingResource::instructionIndex(), isInUse(), and resourceRecord_.
Referenced by OutputPSocketResource::unassign().
Member Data Documentation
resourceRecord_
ResourceRecordType PSocketResource::resourceRecord_ protected
Definition at line 63 of file PSocketResource.hh.
Referenced by assign(), InputPSocketResource::canAssign(), OutputPSocketResource::canAssign(), canAssign(), clear(), isAvailable(), isInUse(), OutputPSocketResource::operator<(), and unassign().
The documentation for this class was generated from the following files:
PSocketResource.hh
PSocketResource.cc