OpenASIP: CFGStatistics Class Reference
CFGStatistics Class Reference
#include <CFGStatistics.hh>
Public Member Functions
CFGStatistics ()
virtual ~CFGStatistics ()
virtual int normalBBCount () const
virtual int maxMoveCount () const
virtual int maxImmediateCount () const
virtual int maxInstructionCount () const
virtual int maxBypassedCount () const
virtual void setNormalBBCount (int)
virtual void setMaxMoveCount (int)
virtual void setMaxImmediateCount (int)
virtual void setMaxInstructionCount (int)
virtual void setMaxBypassedCount (int)
Public Member Functions inherited from TTAProgram::BasicBlockStatistics
BasicBlockStatistics ()
virtual ~BasicBlockStatistics ()
virtual int moveCount () const
virtual int immediateCount () const
virtual int instructionCount () const
virtual int bypassedCount () const
virtual void setMoveCount (int)
virtual void setImmediateCount (int)
virtual void setInstructionCount (int)
virtual void setBypassedCount (int)
Private Attributes
int normalBBCount_
int maxMoveCount_
int maxImmediateCount_
int maxInstructionCount_
int maxBypassCount_
Detailed Description
Represents statistics about single control flow graph. Count of BB, sum of moves, immediates, instructions and bypasses as well as largest basic block and immediates, instructions and bypassed in it.
Definition at line 44 of file CFGStatistics.hh.
Constructor & Destructor Documentation
CFGStatistics()
CFGStatistics::CFGStatistics ()
Constructor, creates statistics structure with zero content.
Definition at line 38 of file CFGStatistics.cc.
                             :
    BasicBlockStatistics(),
    normalBBCount_(0),
    maxMoveCount_(0),
    maxImmediateCount_(0),
    maxInstructionCount_(0),
    maxBypassCount_(0) {
}
~CFGStatistics()
CFGStatistics::~CFGStatistics () virtual
To remove compile warning.
Definition at line 50 of file CFGStatistics.cc.
{
}
Member Function Documentation
maxBypassedCount()
int CFGStatistics::maxBypassedCount () const virtual
Returns bypassed move count from statistics object for largest BB.
Returns
count of bypassed moves stored in object
Definition at line 82 of file CFGStatistics.cc.
{
    return maxBypassCount_;
}
References maxBypassCount_.
Referenced by ControlFlowGraph::printStatistics().
maxImmediateCount()
int CFGStatistics::maxImmediateCount () const virtual
Returns immediate count from statistics object for largest BB.
Returns
count of immediates stored in object
Definition at line 66 of file CFGStatistics.cc.
{
    return maxImmediateCount_;
}
References maxImmediateCount_.
Referenced by ControlFlowGraph::printStatistics().
maxInstructionCount()
int CFGStatistics::maxInstructionCount () const virtual
Returns instruction count from statistics object for largest BB.
Returns
count of instructions stored in object
Definition at line 74 of file CFGStatistics.cc.
{
    return maxInstructionCount_;
}
References maxInstructionCount_.
Referenced by ControlFlowGraph::printStatistics().
maxMoveCount()
int CFGStatistics::maxMoveCount () const virtual
Returns maximum move count from statistics object.
Returns
count of moves of largest BB
Definition at line 58 of file CFGStatistics.cc.
{
    return maxMoveCount_;
}
References maxMoveCount_.
Referenced by ControlFlowGraph::printStatistics().
normalBBCount()
int CFGStatistics::normalBBCount () const virtual
Returns the number of basic blocks in procedure.
Definition at line 90 of file CFGStatistics.cc.
{
    return normalBBCount_;
}
References normalBBCount_.
Referenced by ControlFlowGraph::printStatistics().
setMaxBypassedCount()
void CFGStatistics::setMaxBypassedCount (int count) virtual
Sets the bypassed move count in statistic object.
Parameters
count number of bypassed moves to store in object
Definition at line 128 of file CFGStatistics.cc.
{
    maxBypassCount_ = count;
}
References maxBypassCount_.
Referenced by ControlFlowGraph::statistics().
setMaxImmediateCount()
void CFGStatistics::setMaxImmediateCount (int count) virtual
Sets the immediate count in statistic object.
Parameters
count number of immediates to store in object
Definition at line 109 of file CFGStatistics.cc.
{
    maxImmediateCount_ = count;
}
References maxImmediateCount_.
Referenced by ControlFlowGraph::statistics().
setMaxInstructionCount()
void CFGStatistics::setMaxInstructionCount (int count) virtual
Sets the instruction count in statistic object.
Parameters
count number of instructions to store in object
Definition at line 119 of file CFGStatistics.cc.
{
    maxInstructionCount_ = count;
}
References maxInstructionCount_.
Referenced by ControlFlowGraph::statistics().
setMaxMoveCount()
void CFGStatistics::setMaxMoveCount (int count) virtual
Sets the move count in statistic object.
Parameters
count number of moves to store in object
Definition at line 99 of file CFGStatistics.cc.
{
    maxMoveCount_ = count;
}
References maxMoveCount_.
Referenced by ControlFlowGraph::statistics().
setNormalBBCount()
void CFGStatistics::setNormalBBCount (int count) virtual
Sets count of basic blocks in procedure into statistics object.
Parameters
count number of basic blocks in procedure.
Definition at line 138 of file CFGStatistics.cc.
{
    normalBBCount_ = count;
}
References normalBBCount_.
Referenced by ControlFlowGraph::statistics().
Member Data Documentation
maxBypassCount_
int CFGStatistics::maxBypassCount_ private
Definition at line 64 of file CFGStatistics.hh.
Referenced by maxBypassedCount(), and setMaxBypassedCount().
maxImmediateCount_
int CFGStatistics::maxImmediateCount_ private
Definition at line 62 of file CFGStatistics.hh.
Referenced by maxImmediateCount(), and setMaxImmediateCount().
maxInstructionCount_
int CFGStatistics::maxInstructionCount_ private
Definition at line 63 of file CFGStatistics.hh.
Referenced by maxInstructionCount(), and setMaxInstructionCount().
maxMoveCount_
int CFGStatistics::maxMoveCount_ private
Definition at line 61 of file CFGStatistics.hh.
Referenced by maxMoveCount(), and setMaxMoveCount().
normalBBCount_
int CFGStatistics::normalBBCount_ private
Definition at line 60 of file CFGStatistics.hh.
Referenced by normalBBCount(), and setNormalBBCount().
The documentation for this class was generated from the following files:
CFGStatistics.hh
CFGStatistics.cc