OpenASIP: ImmediateAnalyzer Class Reference
ImmediateAnalyzer Class Reference
#include <ImmediateAnalyzer.hh>
Public Member Functions
ImmediateAnalyzer ()=default
virtual ~ImmediateAnalyzer ()=default
Static Public Member Functions
static ImmInfo * analyze (const TTAMachine::Machine &mach)
Static Private Member Functions
static void analyzeImmediateCapabilitiesForFU (const TTAMachine::FunctionUnit &fu, ImmInfo &result)
static void analyzeImmediateCapabilitiesForOperation (const TTAMachine::HWOperation &hwop, ImmInfo &result)
Detailed Description
Definition at line 50 of file ImmediateAnalyzer.hh.
Constructor & Destructor Documentation
ImmediateAnalyzer()
ImmediateAnalyzer::ImmediateAnalyzer () default
~ImmediateAnalyzer()
virtual ImmediateAnalyzer::~ImmediateAnalyzer () virtual default
Member Function Documentation
analyze()
ImmInfo * ImmediateAnalyzer::analyze (const TTAMachine::Machine & mach) static
Collects short immediate capabilities of the machine.
Parameters
mach The machine.
Definition at line 60 of file ImmediateAnalyzer.cc.
{
    std::unique_ptr<ImmInfo> result(new ImmInfo);
    for (const FunctionUnit* fu : mach.functionUnitNavigator()) {
        analyzeImmediateCapabilitiesForFU(*fu, *result);
    }
    analyzeImmediateCapabilitiesForFU(*mach.controlUnit(), *result);
    // ^ todo: fix this. operations of CU are not getting included in analysis.
    //todo: remove duplicates (entries with identical (key, value pairs)).
    return result.release();
}
References analyzeImmediateCapabilitiesForFU(), TTAMachine::Machine::controlUnit(), and TTAMachine::Machine::functionUnitNavigator().
Referenced by TDGen::TDGen().
analyzeImmediateCapabilitiesForFU()
void ImmediateAnalyzer::analyzeImmediateCapabilitiesForFU (const TTAMachine::FunctionUnit & fu, ImmInfo & result) static private
Collects short immediate capabilities for each operation in the FU.
Parameters
fu The function unit.
result The short immediate analysis result object where the capabilities are inserted into.
Definition at line 85 of file ImmediateAnalyzer.cc.
{
    for (int i = 0; i < fu.operationCount(); i++) {
        HWOperation& hwop = *fu.operation(i);
        analyzeImmediateCapabilitiesForOperation(hwop, result);
    }
}
References analyzeImmediateCapabilitiesForOperation(), TTAMachine::FunctionUnit::operation(), and TTAMachine::FunctionUnit::operationCount().
Referenced by analyze().
analyzeImmediateCapabilitiesForOperation()
void ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation (const TTAMachine::HWOperation & hwop, ImmInfo & result) static private
Collects immediate transport capabilities for the operation.
Parameters
hwop The operation.
result The short immediate analysis result object where the capabilities are inserted into.
Definition at line 103 of file ImmediateAnalyzer.cc.
{
    using std::make_pair;
    for (int i = 0; i < hwop.operandCount(); i++) {
        assert(hwop.port(i+1) != nullptr);
        const FUPort& boundPort = *hwop.port(i+1);
    const Machine& mach = *boundPort.parentUnit()->machine();
        std::set<const TTAMachine::Bus*> connectedBuses =
            MachineConnectivityCheck::connectedSourceBuses(boundPort);
        for (const Bus* bus : connectedBuses) {
            if (bus->immediateWidth() < 1) {
                continue;
            }
            result.insert(
                make_pair(
                    make_pair(TCEString::toUpper(hwop.name()), i+1),
                    ImmInfoValue(bus->immediateWidth(), bus->signExtends())));
        }
        for (const ImmediateUnit* iu : mach.immediateUnitNavigator()) {
            if (MachineConnectivityCheck::isConnected(*iu, boundPort)) {
                for (auto& it : mach.instructionTemplateNavigator()) {
                    int supportedWidth = it->supportedWidth(*iu);
                    if (supportedWidth < 1) {
                        continue;
                    }
                    result.insert(
                        make_pair(
                            make_pair(TCEString::toUpper(hwop.name()), i+1),
                            ImmInfoValue(supportedWidth, iu->signExtends())));
                }
            }
        }
    }
}
References assert, MachineConnectivityCheck::connectedSourceBuses(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), MachineConnectivityCheck::isConnected(), TTAMachine::Component::machine(), TTAMachine::HWOperation::name(), TTAMachine::HWOperation::operandCount(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::HWOperation::port(), and TCEString::toUpper().
Referenced by analyzeImmediateCapabilitiesForFU().
The documentation for this class was generated from the following files:
ImmediateAnalyzer.hh
ImmediateAnalyzer.cc