OpenASIP: FUArchitectureDialog Class Reference
FUArchitectureDialog Class Reference
#include <FUArchitectureDialog.hh>
Public Member Functions
FUArchitectureDialog (wxWindow *parent, wxWindowID id, HDB::FUArchitecture &arch)
virtual ~FUArchitectureDialog ()
Private Types
enum { ID_PARAM_WIDTH_LIST = 10000 , ID_GUARD_SUPPORT_LIST , ID_LINE }
Widget IDs.
Private Member Functions
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void update ()
Private Attributes
HDB::FUArchitecture & arch_
wxCheckListBox * paramWidthList_
wxCheckListBox * guardSupportList_
Detailed Description
Dialog for defining FU architecture paramters to HDB.
Definition at line 46 of file FUArchitectureDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_PARAM_WIDTH_LIST
ID_GUARD_SUPPORT_LIST
ID_LINE
Definition at line 58 of file FUArchitectureDialog.hh.
         {
        ID_PARAM_WIDTH_LIST = 10000,
        ID_GUARD_SUPPORT_LIST,
        ID_LINE
    };
Constructor & Destructor Documentation
FUArchitectureDialog()
FUArchitectureDialog::FUArchitectureDialog (wxWindow * parent, wxWindowID id, HDB::FUArchitecture & arch)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog.
fu Function unit to parametrize.
Definition at line 51 of file FUArchitectureDialog.cc.
                                                              :
    wxDialog(parent, id, _T("Function unit architecture.")),
    arch_(arch) {
        createContents(this, true, true);
        paramWidthList_ =
            dynamic_cast<wxCheckListBox*>(FindWindow(ID_PARAM_WIDTH_LIST));
        guardSupportList_ =
            dynamic_cast<wxCheckListBox*>(FindWindow(ID_GUARD_SUPPORT_LIST));
        update();
}
~FUArchitectureDialog()
FUArchitectureDialog::~FUArchitectureDialog () virtual
The Destructor.
Definition at line 70 of file FUArchitectureDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FUArchitectureDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 118 of file FUArchitectureDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Parametrized width:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    wxWindow *item4 = new wxCheckListBox(parent, ID_PARAM_WIDTH_LIST, wxDefaultPosition, wxSize(200, 240));
    wxASSERT( item4 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticBox *item6 = new wxStaticBox( parent, -1, wxT("Guard support:") );
    wxStaticBoxSizer *item5 = new wxStaticBoxSizer( item6, wxVERTICAL );
    wxWindow *item7 = new wxCheckListBox(parent, ID_GUARD_SUPPORT_LIST, wxDefaultPosition, wxSize(200, 240));
    wxASSERT( item7 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item8 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item8, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_GUARD_SUPPORT_LIST, ID_LINE, and ID_PARAM_WIDTH_LIST.
onOK()
void FUArchitectureDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 99 of file FUArchitectureDialog.cc.
{
    const TTAMachine::FunctionUnit& fu = arch_.architecture();
    for (int i = 0; i < fu.portCount(); i++) {
        std::string port = fu.port(i)->name();
        if (paramWidthList_->IsChecked(i)) {
            arch_.setParameterizedWidth(port);
        }
        if (guardSupportList_->IsChecked(i)) {
            arch_.setGuardSupport(port);
        }
    }
    EndModal(wxID_OK);
}
References arch_, HDB::FUArchitecture::architecture(), guardSupportList_, TTAMachine::Port::name(), paramWidthList_, TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), HDB::FUArchitecture::setGuardSupport(), and HDB::FUArchitecture::setParameterizedWidth().
update()
void FUArchitectureDialog::update () private
Updates the dialog list widgets.
Definition at line 78 of file FUArchitectureDialog.cc.
{
    paramWidthList_->Clear();
    guardSupportList_->Clear();
    const TTAMachine::FunctionUnit& fu = arch_.architecture();
    for (int i = 0; i < fu.portCount(); i++) {
        std::string port = fu.port(i)->name();
        paramWidthList_->Append(WxConversion::toWxString(port));
        guardSupportList_->Append(WxConversion::toWxString(port));
        if (arch_.hasParameterizedWidth(port)) {
            paramWidthList_->Check(i);
        }
        if (arch_.hasGuardSupport(port)) {
            guardSupportList_->Check(i);
        }
    }
}
References arch_, HDB::FUArchitecture::architecture(), guardSupportList_, HDB::FUArchitecture::hasGuardSupport(), HDB::FUArchitecture::hasParameterizedWidth(), TTAMachine::Port::name(), paramWidthList_, TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), and WxConversion::toWxString().
Member Data Documentation
arch_
HDB::FUArchitecture& FUArchitectureDialog::arch_ private
Definition at line 64 of file FUArchitectureDialog.hh.
Referenced by onOK(), and update().
guardSupportList_
wxCheckListBox* FUArchitectureDialog::guardSupportList_ private
Definition at line 67 of file FUArchitectureDialog.hh.
Referenced by onOK(), and update().
paramWidthList_
wxCheckListBox* FUArchitectureDialog::paramWidthList_ private
Definition at line 66 of file FUArchitectureDialog.hh.
Referenced by onOK(), and update().
The documentation for this class was generated from the following files:
FUArchitectureDialog.hh
FUArchitectureDialog.cc