OpenASIP: InfoStatsCommand Class Reference
InfoStatsCommand Class Reference
Public Member Functions
InfoStatsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoStatsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info stats". The following sub-commands are supported: "executed_operations", "register_reads" and "register_writes"
Definition at line 1120 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoStatsCommand()
InfoStatsCommand::InfoStatsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 1125 of file InfoCommand.cc.
                                                               :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoStatsCommand()
virtual InfoStatsCommand::~InfoStatsCommand () inline virtual
Destructor.
Definition at line 1132 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoStatsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info stats" command.
Parameters
arguments Arguments to the command, including the command.
Returns
true in case execution was successful.
Implements SimControlLanguageSubCommand.
Definition at line 1141 of file InfoCommand.cc.
{
        if (!parent().checkSimulationEnded() &&
            !parent().checkSimulationInitialized() &&
            !parent().checkSimulationStopped() &&
            !parent().simulatorFrontend().isSimulationRunning()) {
            return false;
        }
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 1, 1)) {
            return false;
        }
        const std::string command =
            StringTools::stringToLower(arguments[2].stringValue());
        const UtilizationStats& stats =
            parent().simulatorFrontend().utilizationStatistics();
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        ClockCycleCount totalOperationExecutions = 0;
        ClockCycleCount totalRegisterReads = 0;
        ClockCycleCount totalRegisterWrites = 0;
        const TTAMachine::Machine::FunctionUnitNavigator& fuNav =
            mach.functionUnitNavigator();
        const TTAMachine::Machine::RegisterFileNavigator& rfNav =
                mach.registerFileNavigator();
        if (command == "executed_operations") {
            for (int i = 0; i <= fuNav.count(); ++i) {
                TTAMachine::FunctionUnit* fu = NULL;
                if (i < fuNav.count())
                    fu = fuNav.item(i);
                else
                    fu = mach.controlUnit();
                assert(fu != NULL);
                for (int j = 0; j < fu->operationCount(); ++j) {
                    const TTAMachine::HWOperation* op = fu->operation(j);
                    assert (op != NULL);
                    totalOperationExecutions += stats.operationExecutions(
                    fu->name(), StringTools::stringToUpper(op->name()));
                }
            }
            parent().interpreter()->setResult(
                   static_cast<double>(totalOperationExecutions));
            return true;
        } else if (command == "register_reads") {
            for (int i = 0; i < rfNav.count(); ++i) {
                TTAMachine::RegisterFile* rf = rfNav.item(i);
                assert(rf != NULL);
                int lastReg = 0;
                lastReg = rf->numberOfRegisters() - 1;
                for (int reg = 0; reg <= lastReg; ++reg) {
                    totalRegisterReads += stats.registerReads(rf->name(), reg);
                }
            }
            parent().interpreter()->setResult(
                   static_cast<double>(totalRegisterReads));
            return true;
        } else if (command == "register_writes") {
            for (int i = 0; i < rfNav.count(); ++i) {
                TTAMachine::RegisterFile* rf = rfNav.item(i);
                assert(rf != NULL);
                int lastReg = 0;
                lastReg = rf->numberOfRegisters() - 1;
                for (int reg = 0; reg <= lastReg; ++reg) {
                    totalRegisterWrites += stats.registerWrites(rf->name(), reg);
                }
            }
            parent().interpreter()->setResult(
                   static_cast<double>(totalRegisterWrites));
            return true;
        } else {
            parent().interpreter()->setError(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_UNKNOWN_SUBCOMMAND).str());
            return false;
        }
    }
References assert, TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), CustomCommand::interpreter(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), UtilizationStats::operationExecutions(), SimControlLanguageSubCommand::parent(), TTAMachine::Machine::registerFileNavigator(), UtilizationStats::registerReads(), UtilizationStats::registerWrites(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), StringTools::stringToLower(), StringTools::stringToUpper(), SimulatorToolbox::textGenerator(), Texts::TXT_UNKNOWN_SUBCOMMAND, and SimulatorFrontend::utilizationStatistics().
The documentation for this class was generated from the following file:
InfoCommand.cc