OpenASIP: ProximBusDetailsCmd Class Reference
ProximBusDetailsCmd Class Reference
#include <ProximBusDetailsCmd.hh>
Public Member Functions
ProximBusDetailsCmd (const TTAMachine::Bus &bus)
virtual ~ProximBusDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::Bus & bus_
Bus to display.
Detailed Description
Command for displaying bus details in the machine window component details pane.
Definition at line 46 of file ProximBusDetailsCmd.hh.
Constructor & Destructor Documentation
ProximBusDetailsCmd()
ProximBusDetailsCmd::ProximBusDetailsCmd (const TTAMachine::Bus & bus)
The Constructor.
Parameters
bus Bus to display.
Definition at line 53 of file ProximBusDetailsCmd.cc.
                                                                 :
    ComponentCommand(), bus_(bus) {
}
~ProximBusDetailsCmd()
ProximBusDetailsCmd::~ProximBusDetailsCmd () virtual
The Destructor.
Definition at line 61 of file ProximBusDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximBusDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 68 of file ProximBusDetailsCmd.cc.
{
    string busName = bus_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    MachineState& machineState = ProximToolbox::frontend()->machineState();
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_BUS_LABEL);
    machineWin->appendDetails(busName + "\n\n");
    // Append registers to the details widget.
    const BusState& busState = machineState.busState(busName);
    int busValue = busState.value().sIntWordValue();
    machineWin->appendDetails(ProximConstants::MACH_WIN_BUS_VALUE_LABEL);
    machineWin->appendDetails(Conversion::toString(busValue) + "\n");
    // Append utlization statistics.
    ClockCycleCount writes = stats.busWrites(busName);
    machineWin->appendUtilizationData(
        ProximConstants::MACH_WIN_BUS_WRITES_LABEL);
    machineWin->appendUtilizationData(Conversion::toString(writes));
    ClockCycleCount cycles = ProximToolbox::frontend()->cycleCount();
    double percent = 0;
    if (cycles > 0) {
        percent = (100.0 * writes) / cycles;
    }
    machineWin->appendUtilizationData(
        " (" + Conversion::toString(percent) + "%)");
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximMachineStateWindow::appendUtilizationData(), bus_, MachineState::busState(), UtilizationStats::busWrites(), SimulatorFrontend::cycleCount(), ProximToolbox::frontend(), ProximConstants::MACH_WIN_BUS_LABEL, ProximConstants::MACH_WIN_BUS_VALUE_LABEL, ProximConstants::MACH_WIN_BUS_WRITES_LABEL, SimulatorFrontend::machineState(), ProximToolbox::machineStateWindow(), TTAMachine::Component::name(), SimValue::sIntWordValue(), Conversion::toString(), SimulatorFrontend::utilizationStatistics(), and RegisterState::value().
Member Data Documentation
bus_
const TTAMachine::Bus& ProximBusDetailsCmd::bus_ private
Bus to display.
Definition at line 53 of file ProximBusDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximBusDetailsCmd.hh
ProximBusDetailsCmd.cc