OpenASIP: TTAMachine::ControlUnit Class Reference
TTAMachine::ControlUnit Class Reference
#include <ControlUnit.hh>
Public Member Functions
ControlUnit (const std::string &name, int delaySlots, int globalGuardLatency)
ControlUnit (const ObjectState *state)
virtual ~ControlUnit ()
virtual ControlUnit * copy () const
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
int delaySlots () const
void setDelaySlots (int delaySlots)
int globalGuardLatency () const
void setGlobalGuardLatency (int latency)
int specialRegisterPortCount () const
bool hasSpecialRegisterPort (const std::string &name) const
SpecialRegisterPort * specialRegisterPort (int index) const
SpecialRegisterPort * specialRegisterPort (const std::string &name) const
void setReturnAddressPort (const SpecialRegisterPort &port)
void unsetReturnAddressPort ()
bool hasReturnAddressPort () const
SpecialRegisterPort * returnAddressPort () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::FunctionUnit
FunctionUnit (const std::string &name)
FunctionUnit (const ObjectState *state)
virtual ~FunctionUnit ()
virtual void setName (const std::string &name)
virtual BaseFUPort * port (const std::string &name) const
virtual BaseFUPort * port (int index) const
virtual int operationPortCount () const
virtual bool hasOperationPort (const std::string &name) const
virtual FUPort * operationPort (const std::string &name) const
virtual FUPort * operationPort (int index) const
virtual BaseFUPort * triggerPort () const
virtual void addOperation (HWOperation &operation)
virtual void deleteOperation (HWOperation &operation)
virtual bool hasOperation (const std::string &name) const
virtual bool hasOperationLowercase (const std::string &name) const
virtual HWOperation * operation (const std::string &name) const
virtual HWOperation * operationLowercase (const std::string &name) const
virtual HWOperation * operation (int index) const
virtual int operationCount () const
virtual void operationNames (TCETools::CIStringSet &opNames) const
virtual int maxLatency () const
virtual void addPipelineElement (PipelineElement &element)
virtual void deletePipelineElement (PipelineElement &element)
virtual int pipelineElementCount () const
virtual PipelineElement * pipelineElement (int index) const
virtual bool hasPipelineElement (const std::string &name) const
virtual PipelineElement * pipelineElement (const std::string &name) const
virtual AddressSpace * addressSpace () const
virtual void setAddressSpace (AddressSpace *as)
virtual bool hasAddressSpace () const
virtual void cleanup (const std::string &resource)
virtual bool isArchitectureEqual (const FunctionUnit *fu, const bool checkPortWidths=true) const
bool needsConflictDetection () const
virtual int orderNumber () const
virtual void setOrderNumber (int)
Public Member Functions inherited from TTAMachine::Unit
virtual ~Unit ()
virtual bool hasPort (const std::string &name) const
virtual int portCount () const
virtual int outputPortCount (bool countBidir=false) const
virtual int inputPortCount (bool countBidir=false) const
virtual int bidirPortCount () const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_CONTROL_UNIT = "control_unit"
ObjectState name for ControlUnit.
static const std::string OSKEY_DELAY_SLOTS = "d_slots"
ObjectState attribute key for the number of delay slots.
static const std::string OSKEY_GUARD_LATENCY = "g_latency"
ObjectState attribute key for the global guard latency.
static const std::string OSKEY_RA_PORT = "ra_port"
ObjectState attribute key for the name of the return address port.
Static Public Attributes inherited from TTAMachine::FunctionUnit
static const std::string OSNAME_FU = "fu"
ObjectState name for function unit.
static const std::string OSKEY_AS = "as"
ObjectState attribute key for name of the address space.
static const std::string OSKEY_ORDER_NUMBER = "order_no"
ObjectState attribute key for FU order number name.
Static Public Attributes inherited from TTAMachine::Unit
static const std::string OSNAME_UNIT = "unit"
ObjectState name for Unit.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Protected Member Functions
virtual void removePort (Port &port)
Protected Member Functions inherited from TTAMachine::FunctionUnit
void unsetMachineDerived ()
Protected Member Functions inherited from TTAMachine::Unit
Unit (const std::string &name)
Unit (const ObjectState *state)
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Member Functions
void loadStateWithoutReferences (const ObjectState *state)
Static Private Member Functions
static bool hasLocalGuardLatencyOfZero (const Machine &machine)
Private Attributes
int delaySlots_
Number of delay instruction slots on the transport pipeline.
int globalGuardLatency_
The global guard latency.
SpecialRegisterPort * raPort_
The return address port.
Detailed Description
Represents the global control unit in the machine.
Definition at line 50 of file ControlUnit.hh.
Constructor & Destructor Documentation
ControlUnit() [1/2]
TTAMachine::ControlUnit::ControlUnit (const std::string & name, int delaySlots, int globalGuardLatency)
Constructor.
Parameters
name Name of the control unit.
delaySlots Number of delay instruction slots of the transport pipeline.
globalGuardLatency The global guard latency.
Exceptions
OutOfRange If some of the given values is out of valid range.
InvalidName If the given name is not a valid component name.
Definition at line 61 of file ControlUnit.cc.
    : FunctionUnit(name),
      delaySlots_(delaySlots),
      globalGuardLatency_(0),
      raPort_(NULL) {
    setDelaySlots(delaySlots);
    setGlobalGuardLatency(globalGuardLatency);
}
References delaySlots(), globalGuardLatency(), setDelaySlots(), and setGlobalGuardLatency().
ControlUnit() [2/2]
TTAMachine::ControlUnit::ControlUnit (const ObjectState * state)
Constructor.
Loads the state of the control unit from the given ObjectState instance. Does not load references to other components.
Parameters
state The ObjectState instance from which the name is taken.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 81 of file ControlUnit.cc.
    : FunctionUnit(state),
      delaySlots_(0),
      globalGuardLatency_(0),
      raPort_(NULL) {
    loadStateWithoutReferences(state);
}
References loadStateWithoutReferences().
~ControlUnit()
TTAMachine::ControlUnit::~ControlUnit () virtual
Destructor.
Definition at line 92 of file ControlUnit.cc.
{
    unsetMachine();
}
References unsetMachine().
Member Function Documentation
copy()
ControlUnit * TTAMachine::ControlUnit::copy () const virtual
Copies the instance.
Current FunctionUnit state is copied to a new FunctionUnit object.
Returns
Copy of the instance.
Reimplemented from TTAMachine::FunctionUnit.
Definition at line 105 of file ControlUnit.cc.
{
    return new ControlUnit(saveState());
}
References saveState().
Referenced by ADFCombiner::addFunctionUnits().
delaySlots()
int TTAMachine::ControlUnit::delaySlots () const
Referenced by MachineStateBuilder::buildMachineState(), ControlUnit(), ProcedurePass::copyCfgToProcedure(), BasicBlockPass::copyRMToBB(), BasicBlockPass::executeDDGPass(), CopyingDelaySlotFiller::fillDelaySlots(), CompiledSimCodeGenerator::findBasicBlocks(), ControlFlowGraph::findNextIndex(), TTASimulationController::findProgramExitPoints(), ControlFlowGraph::findRelJumpDistance(), ProGe::ProGeUI::generateIDF(), BF2ScheduleFront::getPreferredLimits(), ProcedureTransferTracker::handleEvent(), CompiledSimCodeGenerator::handleJump(), CopyingDelaySlotFiller::initialize(), ScheduleEstimator::maximumSizeOfBB(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), setDelaySlots(), DataDependenceGraph::setMachine(), SimpleIfConverter::SimpleIfConverter(), GCUDialog::TransferDataToWindow(), DefaultDecoderGenerator::verifyCompatibility(), and DefaultICDecoderGenerator::verifyCompatibility().
globalGuardLatency()
int TTAMachine::ControlUnit::globalGuardLatency () const
Referenced by MachineStateBuilder::buildMachineState(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), ControlUnit(), TTAProgram::Move::guardLatency(), BFOptimization::jumpGuardAvailableCycle(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadMachine(), TTAMachine::RegisterGuard::loadState(), MachineInfo::longestGuardLatency(), CompiledSimCodeGenerator::maxLatency(), TTAMachine::RegisterGuard::RegisterGuard(), SequentialScheduler::scheduleMove(), TTAMachine::RegisterFile::setGuardLatency(), setMachine(), GCUDialog::TransferDataToWindow(), and DefaultDecoderGenerator::verifyCompatibility().
hasLocalGuardLatencyOfZero()
bool TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero (const Machine & machine) static private
Tells whether the given machine has a guard that reads a register with local guard latency of zero.
Parameters
machine The machine.
Returns
True if the machine has the guard, otherwise false.
Definition at line 411 of file ControlUnit.cc.
{
    Machine::BusNavigator busNav = machine.busNavigator();
    for (int i = 0; i < busNav.count(); i++) {
        Bus* bus = busNav.item(i);
        for (int i = 0; i < bus->guardCount(); i++) {
            Guard* guard = bus->guard(i);
            RegisterGuard* regGuard =
                dynamic_cast<RegisterGuard*>(guard);
            if (regGuard != NULL) {
                const RegisterFile* rf = regGuard->registerFile();
                if (rf->guardLatency() == 0) {
                    return true;
                }
            }
        }
    }
    return false;
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::RegisterFile::guardLatency(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), and TTAMachine::RegisterGuard::registerFile().
Referenced by setGlobalGuardLatency(), and setMachine().
hasReturnAddressPort()
bool TTAMachine::ControlUnit::hasReturnAddressPort () const
Tells whether the control unit has a return address port.
Returns
True if a return address port exists, otherwise false.
Definition at line 295 of file ControlUnit.cc.
{
    return raPort_ != NULL;
}
References raPort_.
Referenced by DefaultICGenerator::addICToNetlist(), MachineStateBuilder::buildMachineState(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), MachineValidator::checkReturnAddressPort(), TTAProgram::TPEFProgramFactory::findPort(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), ProGe::ProcessorGenerator::iMemAddressWidth(), saveState(), GCUDialog::updateRAPortChoice(), and DefaultDecoderGenerator::writeControlRegisterMappings().
hasSpecialRegisterPort()
bool TTAMachine::ControlUnit::hasSpecialRegisterPort (const std::string & name) const
Tells whether the control unit has a special register port of the given name.
Returns
True if the control unit has the port, otherwise false.
Definition at line 197 of file ControlUnit.cc.
{
    return hasPort(name) && !hasOperationPort(name);
}
References TTAMachine::FunctionUnit::hasOperationPort(), TTAMachine::Unit::hasPort(), and TTAMachine::Component::name().
Referenced by GCUDialog::onEditPort(), and GCUDialog::updatePortList().
loadState()
void TTAMachine::ControlUnit::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance invalid or if connections to other machine parts cannot be made.
Reimplemented from TTAMachine::FunctionUnit.
Definition at line 351 of file ControlUnit.cc.
{
    FunctionUnit::loadState(state);
    loadStateWithoutReferences(state);
}
References TTAMachine::FunctionUnit::loadState(), and loadStateWithoutReferences().
Referenced by TTAMachine::Machine::loadState(), GCUDialog::onAddOperation(), and GCUDialog::onEditOperation().
loadStateWithoutReferences()
void TTAMachine::ControlUnit::loadStateWithoutReferences (const ObjectState * state) private
Loads the state of the control unit without references to other components.
Parameters
state The ObjectState instance from which the state is loaded.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 380 of file ControlUnit.cc.
{
    const string procName = "ControlUnit::loadStateWithoutReferences";
    if (state->name() != OSNAME_CONTROL_UNIT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        setDelaySlots(state->intAttribute(OSKEY_DELAY_SLOTS));
        setGlobalGuardLatency(state->intAttribute(OSKEY_GUARD_LATENCY));
        if (state->hasAttribute(OSKEY_RA_PORT)) {
            string portName = state->stringAttribute(OSKEY_RA_PORT);
            setReturnAddressPort(*specialRegisterPort(portName));
        } else {
            unsetReturnAddressPort();
        }
    } catch (Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
}
References Exception::errorMessage(), ObjectState::hasAttribute(), ObjectState::intAttribute(), ObjectState::name(), OSKEY_DELAY_SLOTS, OSKEY_GUARD_LATENCY, OSKEY_RA_PORT, OSNAME_CONTROL_UNIT, setDelaySlots(), setGlobalGuardLatency(), setReturnAddressPort(), specialRegisterPort(), ObjectState::stringAttribute(), and unsetReturnAddressPort().
Referenced by ControlUnit(), and loadState().
removePort()
void TTAMachine::ControlUnit::removePort (Port & port) protected virtual
Removes the given port from the control unit and unsets the binding of return address port if necessary.
Parameters
port The port to be removed.
Reimplemented from TTAMachine::Unit.
Definition at line 363 of file ControlUnit.cc.
{
    if (&port == raPort_) {
        unsetReturnAddressPort();
    }
    FunctionUnit::removePort(port);
}
References TTAMachine::FunctionUnit::port(), raPort_, TTAMachine::Unit::removePort(), and unsetReturnAddressPort().
returnAddressPort()
SpecialRegisterPort * TTAMachine::ControlUnit::returnAddressPort () const
Returns the return address port.
Returns
The return address port.
Exceptions
InstanceNotFound If there is no return address port.
Definition at line 307 of file ControlUnit.cc.
{
    if (raPort_ != NULL) {
        return raPort_;
    } else {
        const string procName = "ControlUnit::returnAddressPort";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
}
References raPort_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), ProGe::NetlistGenerator::addGCUToNetlist(), DefaultICGenerator::addICToNetlist(), ProGe::RV32MicroCodeGenerator::addIPorts(), ProGe::RV32MicroCodeGenerator::addUJPorts(), InputFUBroker::assign(), OutputFUBroker::assign(), MachineStateBuilder::buildMachineState(), MachineConnectivityCheck::busConnectedToDestination(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), DefaultDecoderGenerator::completeDecoderBlock(), TTAProgram::CodeGenerator::createTerminalFUPort(), TTAProgram::TPEFProgramFactory::findPort(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), CopyingDelaySlotFiller::getMove(), CallsToJumps::handleControlFlowGraph(), ProGe::ProcessorGenerator::iMemAddressWidth(), MachineConnectivityCheck::raConnected(), ProGe::ProGeUI::readImemParameters(), CompiledSimSymbolGenerator::returnAddressSymbol(), saveState(), SimulatorFrontend::state(), GCUDialog::updateRAPortChoice(), and DefaultDecoderGenerator::writeControlRegisterMappings().
saveState()
ObjectState * TTAMachine::ControlUnit::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from TTAMachine::FunctionUnit.
Definition at line 322 of file ControlUnit.cc.
{
    ObjectState* cUnit = FunctionUnit::saveState();
    cUnit->setName(OSNAME_CONTROL_UNIT);
    // set delay slots
    cUnit->setAttribute(OSKEY_DELAY_SLOTS, delaySlots_);
    // set global guard latency
    cUnit->setAttribute(OSKEY_GUARD_LATENCY, globalGuardLatency_);
    // set return address port
    if (hasReturnAddressPort()) {
        cUnit->setAttribute(OSKEY_RA_PORT, returnAddressPort()->name());
    }
    return cUnit;
}
References delaySlots_, globalGuardLatency_, hasReturnAddressPort(), TTAMachine::Component::name(), OSKEY_DELAY_SLOTS, OSKEY_GUARD_LATENCY, OSKEY_RA_PORT, OSNAME_CONTROL_UNIT, returnAddressPort(), TTAMachine::FunctionUnit::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by copy(), GCUDialog::onAddOperation(), GCUDialog::onEditOperation(), and TTAMachine::Machine::saveState().
setDelaySlots()
void TTAMachine::ControlUnit::setDelaySlots (int delaySlots)
Definition at line 145 of file ControlUnit.cc.
{
    if (delaySlots < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    delaySlots_ = delaySlots;
}
References __func__, delaySlots(), and delaySlots_.
Referenced by ControlUnit(), loadStateWithoutReferences(), and GCUDialog::onOK().
setGlobalGuardLatency()
void TTAMachine::ControlUnit::setGlobalGuardLatency (int latency)
Sets the global guard latency.
Parameters
latency The new latency.
Exceptions
OutOfRange If the given latency is negative.
Definition at line 159 of file ControlUnit.cc.
{
    if (latency < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    // if latency is zero, there must not be a guard term that reads a
    // registr of a register file with local guard latency of zero
    if (latency == 0 && isRegistered()) {
        if (hasLocalGuardLatencyOfZero(*machine())) {
            MOMTextGenerator textGen;
            boost::format text = textGen.text(
                MOMTextGenerator::TXT_INVALID_GUARD_LATENCY);
            throw OutOfRange(
                __FILE__, __LINE__, __func__, text.str());
        }
    }
    globalGuardLatency_ = latency;
}
References __func__, globalGuardLatency_, hasLocalGuardLatencyOfZero(), TTAMachine::Component::isRegistered(), TTAMachine::Component::machine(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_INVALID_GUARD_LATENCY.
Referenced by ControlUnit(), loadStateWithoutReferences(), GCUDialog::onOK(), TTAMachine::RegisterFile::setGuardLatency(), and setMachine().
setMachine()
void TTAMachine::ControlUnit::setMachine (Machine & mach) virtual
Attaches the control unit to machine.
Parameters
mach The machine.
Exceptions
ComponentAlreadyExists If the given machine already has a global control unit.
Reimplemented from TTAMachine::Unit.
Definition at line 119 of file ControlUnit.cc.
{
    // if global guard latency is zero, there cannot be a register guard
    // that reads a register of local guard latency zero
    if (globalGuardLatency() == 0 && hasLocalGuardLatencyOfZero(mach)) {
        setGlobalGuardLatency(1);
    }
    internalSetMachine(mach);
    mach.setGlobalControl(*this);
}
References globalGuardLatency(), hasLocalGuardLatencyOfZero(), TTAMachine::Component::internalSetMachine(), TTAMachine::Machine::setGlobalControl(), and setGlobalGuardLatency().
Referenced by AddGCUCmd::Do(), PasteComponentCmd::Do(), and TTAMachine::Machine::setGlobalControl().
setReturnAddressPort()
void TTAMachine::ControlUnit::setReturnAddressPort (const SpecialRegisterPort & port)
Binds the given port to return address port.
If there is another port bound to return address port already, unbinds it.
Parameters
port The port to be bound.
Exceptions
IllegalRegistration If the given port is not a port of this control unit.
Definition at line 271 of file ControlUnit.cc.
{
    if (port.parentUnit() != this) {
        const string procName = "ControlUnit::setReturnAddressPort";
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    raPort_ = const_cast<SpecialRegisterPort*>(&port);
}
References TTAMachine::BaseFUPort::parentUnit(), TTAMachine::FunctionUnit::port(), and raPort_.
Referenced by BlocksGCU::BlocksGCU(), UniversalMachine::construct(), AddGCUCmd::Do(), CostEstimator::ICDecoderEstimatorPlugin::generateControlUnit(), loadStateWithoutReferences(), and GCUDialog::onRAPortChoice().
specialRegisterPort() [1/2]
SpecialRegisterPort * TTAMachine::ControlUnit::specialRegisterPort (const std::string & name) const
Returns a special register port by the given name.
Parameters
name Name of the port.
Returns
A special register port.
Exceptions
InstanceNotFound If a special register port does not exist by the given name.
Definition at line 245 of file ControlUnit.cc.
{
    const string procName = "ControlUnit::specialRegisterPort";
    if (!hasPort(name)) {
        throw InstanceNotFound(
            __FILE__, __LINE__, procName, "Port not found: " + name);
    }
    Port* port = this->port(name);
    SpecialRegisterPort* srPort = dynamic_cast<SpecialRegisterPort*>(port);
    if (srPort == NULL) {
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    return srPort;
}
References TTAMachine::Unit::hasPort(), TTAMachine::Component::name(), and TTAMachine::FunctionUnit::port().
specialRegisterPort() [2/2]
SpecialRegisterPort * TTAMachine::ControlUnit::specialRegisterPort (int index) const
Returns a special register port by the given index.
Parameters
index The index.
Returns
A special register port.
Exceptions
OutOfRange If the given index is less than 0 or greater or equal to the number of special register ports.
Definition at line 211 of file ControlUnit.cc.
{
    const string procName = "ControlUnit::specialRegisterPort";
    if (index < 0) {
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    int portCount = this->portCount();
    int srPortCount(-1);
    for (int i = 0; i < portCount; i++) {
        BaseFUPort* port = this->port(i);
        SpecialRegisterPort* srPort =
            dynamic_cast<SpecialRegisterPort*>(port);
        if (srPort != NULL) {
            srPortCount++;
            if (srPortCount == index) {
                return srPort;
            }
        }
    }
    throw OutOfRange(__FILE__, __LINE__, procName);
}
References TTAMachine::FunctionUnit::port(), and TTAMachine::Unit::portCount().
Referenced by FullyConnectedCheck::check(), FullyConnectedCheck::connectControlUnit(), GCUFactory::createEditPart(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), loadStateWithoutReferences(), GCUDialog::onEditPort(), GCUDialog::onRAPortChoice(), and GCUDialog::updateRAPortChoice().
specialRegisterPortCount()
int TTAMachine::ControlUnit::specialRegisterPortCount () const
Returns the number of special register ports in the control unit.
Returns
The number of special register ports.
Definition at line 185 of file ControlUnit.cc.
{
    return portCount() - operationPortCount();
}
References TTAMachine::FunctionUnit::operationPortCount(), and TTAMachine::Unit::portCount().
Referenced by FullyConnectedCheck::check(), FullyConnectedCheck::connectControlUnit(), GCUFactory::createEditPart(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), and GCUDialog::updateRAPortChoice().
unsetMachine()
void TTAMachine::ControlUnit::unsetMachine () virtual
Detaches the control unit from machine.
Reimplemented from TTAMachine::FunctionUnit.
Definition at line 134 of file ControlUnit.cc.
{
    if (!isRegistered()) {
        return;
    } else {
        Machine* mach = machine();
        unsetMachineDerived();
        mach->unsetGlobalControl();
    }
}
References TTAMachine::Component::isRegistered(), TTAMachine::Component::machine(), TTAMachine::Machine::unsetGlobalControl(), and TTAMachine::FunctionUnit::unsetMachineDerived().
Referenced by TTAMachine::Machine::unsetGlobalControl(), and ~ControlUnit().
unsetReturnAddressPort()
void TTAMachine::ControlUnit::unsetReturnAddressPort ()
Unbinds the return address port if one exists.
Definition at line 284 of file ControlUnit.cc.
{
    raPort_ = NULL;
}
References raPort_.
Referenced by loadStateWithoutReferences(), GCUDialog::onRAPortChoice(), and removePort().
Member Data Documentation
delaySlots_
int TTAMachine::ControlUnit::delaySlots_ private
Number of delay instruction slots on the transport pipeline.
Definition at line 98 of file ControlUnit.hh.
Referenced by saveState(), and setDelaySlots().
globalGuardLatency_
int TTAMachine::ControlUnit::globalGuardLatency_ private
The global guard latency.
Definition at line 101 of file ControlUnit.hh.
Referenced by saveState(), and setGlobalGuardLatency().
OSKEY_DELAY_SLOTS
const string TTAMachine::ControlUnit::OSKEY_DELAY_SLOTS = "d_slots" static
ObjectState attribute key for the number of delay slots.
Definition at line 84 of file ControlUnit.hh.
Referenced by ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), loadStateWithoutReferences(), and saveState().
OSKEY_GUARD_LATENCY
const string TTAMachine::ControlUnit::OSKEY_GUARD_LATENCY = "g_latency" static
ObjectState attribute key for the global guard latency.
Definition at line 86 of file ControlUnit.hh.
Referenced by ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), loadStateWithoutReferences(), and saveState().
OSKEY_RA_PORT
const string TTAMachine::ControlUnit::OSKEY_RA_PORT = "ra_port" static
ObjectState attribute key for the name of the return address port.
Definition at line 88 of file ControlUnit.hh.
Referenced by ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), loadStateWithoutReferences(), and saveState().
OSNAME_CONTROL_UNIT
const string TTAMachine::ControlUnit::OSNAME_CONTROL_UNIT = "control_unit" static
ObjectState name for ControlUnit.
Definition at line 82 of file ControlUnit.hh.
Referenced by ADFSerializer::controlUnitToMachine(), ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), TTAMachine::Machine::loadState(), loadStateWithoutReferences(), and saveState().
raPort_
SpecialRegisterPort* TTAMachine::ControlUnit::raPort_ private
The return address port.
Definition at line 103 of file ControlUnit.hh.
Referenced by hasReturnAddressPort(), removePort(), returnAddressPort(), setReturnAddressPort(), and unsetReturnAddressPort().
The documentation for this class was generated from the following files:
ControlUnit.hh
ControlUnit.cc