OpenASIP: CmdAdvanceClock Class Reference
CmdAdvanceClock Class Reference
#include <TestOsal.hh>
Public Member Functions
CmdAdvanceClock ()
CmdAdvanceClock (const CmdAdvanceClock &cmd)
virtual ~CmdAdvanceClock ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Advances clock by one cycle.
Definition at line 195 of file TestOsal.hh.
Constructor & Destructor Documentation
CmdAdvanceClock() [1/2]
CmdAdvanceClock::CmdAdvanceClock ()
Constructor.
Definition at line 840 of file TestOsal.cc.
                                 : CustomCommand("advanceclock") {
}
CmdAdvanceClock() [2/2]
CmdAdvanceClock::CmdAdvanceClock (const CmdAdvanceClock & cmd) explicit
Copy constructor.
Parameters
cmd Command to be copied.
Definition at line 848 of file TestOsal.cc.
                                                           :
    CustomCommand(cmd) {
}
~CmdAdvanceClock()
CmdAdvanceClock::~CmdAdvanceClock () virtual
Destructor.
Definition at line 855 of file TestOsal.cc.
{
}
Member Function Documentation
execute()
bool CmdAdvanceClock::execute (const std::vector< DataObject > & arguments) virtual
Executes the command.
Parameters
arguments Arguments for the command.
Returns
True if execution is successful.
Exceptions
NumberFormatException If DataObject conversion fails.
Implements CustomCommand.
Definition at line 866 of file TestOsal.cc.
{
    ScriptInterpreter* scriptInterp = interpreter();
    OsalInterpreter* interp = dynamic_cast<OsalInterpreter*>(scriptInterp);
    assert(interp != NULL);
    DataObject* result = new DataObject();
    if (arguments.size() != 1) {
        result->setString("wrong number of arguments");
        interp->setResult(result);
        return false;
    }
    TesterContext& context =
        *(dynamic_cast<TesterContext*>(&interp->context()));
    Memory& memory = context.operationContext().memory();
    memory.advanceClock();
    context.operationContext().advanceClock();
    result->setString("");
    interp->setResult(result);
    return true;
}
References Memory::advanceClock(), assert, CustomCommand::context(), SimpleScriptInterpreter::context(), CustomCommand::interpreter(), ScriptInterpreter::setResult(), and DataObject::setString().
helpText()
string CmdAdvanceClock::helpText () const virtual
Returns the help text of the command.
Returns
The help text.
Implements CustomCommand.
Definition at line 896 of file TestOsal.cc.
{
    return "Advances clock per one cycle";
}
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc