OpenASIP: SelectTool Class Reference
SelectTool Class Reference
#include <SelectTool.hh>
Public Member Functions
SelectTool (ChildFrame *frame, MDFView *view)
virtual ~SelectTool ()
virtual void activate ()
virtual void deactivate ()
virtual void onMouseEvent (wxMouseEvent &event, wxDC &dc)
virtual Figure * figure ()
Public Member Functions inherited from MachineCanvasTool
virtual ~MachineCanvasTool ()
Private Types
enum {
ID_CONTEXT_MODIFY = 11000 , ID_CONTEXT_DELETE , ID_CONTEXT_COPY , ID_CONTEXT_CUT ,
ID_ADD_SUBMENU
}
IDs for the context menu items.
Private Member Functions
void leftClick (EditPart *part)
void popContextMenu (EditPart *part, int x, int y)
wxMenu * createDefaultMenu ()
Private Attributes
ChildFrame * frame_
Parent frame of the Canvas.
MDFView * view_
View displayed on the Canvas.
bool active_
Tells if the tool is active or not.
SelectionFigure * figure_
Selection figure;.
Additional Inherited Members
Protected Member Functions inherited from MachineCanvasTool
MachineCanvasTool (MachineCanvas *canvas)
Protected Attributes inherited from MachineCanvasTool
MachineCanvas * canvas_
Machine canvas where the tool is used.
Detailed Description
Tool for selecting components in the canvas.
Definition at line 47 of file SelectTool.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
IDs for the context menu items.
Enumerator
ID_CONTEXT_MODIFY
ID_CONTEXT_DELETE
ID_CONTEXT_COPY
ID_CONTEXT_CUT
ID_ADD_SUBMENU
Definition at line 70 of file SelectTool.hh.
         {
    ID_CONTEXT_MODIFY = 11000,
    ID_CONTEXT_DELETE,
    ID_CONTEXT_COPY,
    ID_CONTEXT_CUT,
    ID_ADD_SUBMENU
    };
Constructor & Destructor Documentation
SelectTool()
SelectTool::SelectTool (ChildFrame * frame, MDFView * view)
The Constructor.
Definition at line 58 of file SelectTool.cc.
                                     :
    MachineCanvasTool(view->canvas()),
    frame_(frame),
    view_(view),
    active_(false) {
    figure_ = new SelectionFigure(NULL);
}
References figure_.
~SelectTool()
SelectTool::~SelectTool () virtual
The Destructor.
Definition at line 72 of file SelectTool.cc.
{
    delete figure_;
}
References figure_.
Member Function Documentation
activate()
void SelectTool::activate () virtual
Activates the tool.
Implements MachineCanvasTool.
Definition at line 81 of file SelectTool.cc.
                     {
    active_ = true;
}
References active_.
createDefaultMenu()
wxMenu * SelectTool::createDefaultMenu () private
Returns a popup menu to be used as a default context menu on the canvas.
Definition at line 238 of file SelectTool.cc.
{
    wxMenu* popupMenu = new wxMenu();
    CommandRegistry* registry = wxGetApp().commandRegistry();
    popupMenu->Append(ProDeConstants::COMMAND_UNDO, _T("&Undo"));
    popupMenu->Append(ProDeConstants::COMMAND_REDO, _T("&Redo"));
    popupMenu->Append(ProDeConstants::COMMAND_PASTE, _T("&Paste"));
    popupMenu->Enable(ProDeConstants::COMMAND_UNDO,
              registry->isEnabled(ProDeConstants::CMD_NAME_UNDO));
    popupMenu->Enable(ProDeConstants::COMMAND_REDO,
              registry->isEnabled(ProDeConstants::CMD_NAME_REDO));
    popupMenu->Enable(ProDeConstants::COMMAND_PASTE,
              registry->isEnabled(ProDeConstants::CMD_NAME_PASTE));
    popupMenu->AppendSeparator();
    wxMenu* addSubMenu = new wxMenu;
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_FU,
               _T("&Function Unit..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_RF,
               _T("&Register File..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_BUS,
               _T("&Transport Bus..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_SOCKET,
               _T("&Socket..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_BRIDGE,
               _T("&Bridge..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_IU,
               _T("&Immediate Unit..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_GCU,
               _T("&Global Control Unit..."));
    addSubMenu->Append(ProDeConstants::COMMAND_ADD_AS,
               _T("&Address Space..."));
    popupMenu->Append(ID_ADD_SUBMENU, _T("&Add"), addSubMenu);
    popupMenu->Append(ProDeConstants::COMMAND_EDIT_CONNECTIONS,
              _T("Edit &Connections"));
    popupMenu->Append(ProDeConstants::COMMAND_SELECT,
              _T("&Select"));
    popupMenu->AppendSeparator();
    popupMenu->Append(ProDeConstants::COMMAND_VERIFY_MACHINE,
              _T("&Verify"));
    return popupMenu;
}
References ProDeConstants::CMD_NAME_PASTE, ProDeConstants::CMD_NAME_REDO, ProDeConstants::CMD_NAME_UNDO, ProDeConstants::COMMAND_ADD_AS, ProDeConstants::COMMAND_ADD_BRIDGE, ProDeConstants::COMMAND_ADD_BUS, ProDeConstants::COMMAND_ADD_FU, ProDeConstants::COMMAND_ADD_GCU, ProDeConstants::COMMAND_ADD_IU, ProDeConstants::COMMAND_ADD_RF, ProDeConstants::COMMAND_ADD_SOCKET, ProDeConstants::COMMAND_EDIT_CONNECTIONS, ProDeConstants::COMMAND_PASTE, ProDeConstants::COMMAND_REDO, ProDeConstants::COMMAND_SELECT, ProDeConstants::COMMAND_UNDO, ProDeConstants::COMMAND_VERIFY_MACHINE, ID_ADD_SUBMENU, and CommandRegistry::isEnabled().
Referenced by popContextMenu().
deactivate()
void SelectTool::deactivate () virtual
Deactivates the tool.
Implements MachineCanvasTool.
Definition at line 90 of file SelectTool.cc.
                       {
    active_ = false;
}
References active_.
figure()
Figure * SelectTool::figure () virtual
Returns figure of the selection.
Returns
Figure of the selection.
Reimplemented from MachineCanvasTool.
Definition at line 100 of file SelectTool.cc.
                   {
    return NULL;
}
leftClick()
void SelectTool::leftClick (EditPart * part) private
Selects Component at cursor position, if there is a selectable EditPart at the coordinates.
Parameters
part Component to select.
Definition at line 173 of file SelectTool.cc.
{
    if (part != NULL && part->selectable()) {
        canvas_->select(part);
        figure_->setSelection(part->figure());
    } else {
    canvas_->clearSelection();
    }
}
References MachineCanvasTool::canvas_, MachineCanvas::clearSelection(), EditPart::figure(), figure_, MachineCanvas::select(), EditPart::selectable(), and SelectionFigure::setSelection().
Referenced by onMouseEvent().
onMouseEvent()
void SelectTool::onMouseEvent (wxMouseEvent & event, wxDC & dc) virtual
Handles mouse events on the Canvas.
Parameters
event Mouse event to handle.
dc Device context.
Implements MachineCanvasTool.
Definition at line 111 of file SelectTool.cc.
{
    if (!active_) {
        return;
    }
    // Get event position and translate "raw" coordinates to logical ones.
    wxPoint position = event.GetPosition();
    int x = position.x;
    int y = position.y;
    long logicalX = dc.DeviceToLogicalX(position.x);
    long logicalY = dc.DeviceToLogicalY(position.y);
    // Check if there is an EditPart at the cursor position.
    EditPart* part = canvas_->findEditPart(logicalX, logicalY);
    // If an EditPart was found at the cursor position, get name of the
    // Component related to the EditPart.
    string status = "";
    Request* request = new Request(Request::STATUS_REQUEST);
    if (part != NULL && part->canHandle(request)) {
        ComponentCommand* command = part->performRequest(request);
        if (command != NULL) {
            if(!command->Do())
                frame_->setStatus(_T(""));
        }
    } else {
        frame_->setStatus(_T(""));
    }
    // If left mouse button was released, select the EditPart at cursor
    // position. (if there is a selectable EditPart)
    if (event.LeftUp()) {
    leftClick(part);
    }
    if (event.RightDown()) {
    // select component
    leftClick(part);
    // popup context menu
    popContextMenu(part, x, y);
    }
    // left mouse button double click executes ModifyComponentCmd
    if (event.ButtonDClick(1)) {
    ModifyComponentCmd* command = new ModifyComponentCmd();
    command->setParentWindow(frame_);
    command->setView(view_);
    command->Do();
    }
    wxGetApp().mainFrame()->updateUI();
}
References active_, EditPart::canHandle(), MachineCanvasTool::canvas_, ModifyComponentCmd::Do(), ComponentCommand::Do(), MachineCanvas::findEditPart(), frame_, leftClick(), EditPart::performRequest(), popContextMenu(), GUICommand::setParentWindow(), ChildFrame::setStatus(), EditorCommand::setView(), Request::STATUS_REQUEST, and view_.
popContextMenu()
void SelectTool::popContextMenu (EditPart * part, int x, int y) private
Pops a context menu for the EditPart at the coordinates;
Parameters
part Context component.
x X-coordinate for the menu.
y Y-coordinate for the menu.
Definition at line 191 of file SelectTool.cc.
{
    wxMenu* contextMenu = NULL;
    if (part == NULL) {
    contextMenu = createDefaultMenu();
    } else {
    CommandRegistry* registry = wxGetApp().commandRegistry();
    contextMenu = new wxMenu();
    contextMenu->Append(ProDeConstants::COMMAND_COPY,
                _T("&Copy"));
    contextMenu->Append(ProDeConstants::COMMAND_CUT,
                _T("Cu&t"));
    contextMenu->AppendSeparator();
    contextMenu->Append(ProDeConstants::COMMAND_MODIFY_COMP,
                _T("&Modify..."));
    contextMenu->Append(ProDeConstants::COMMAND_DELETE_COMP,
                _T("&Delete"));
    contextMenu->Enable(
        ProDeConstants::COMMAND_COPY,
        registry->isEnabled(ProDeConstants::CMD_NAME_COPY));
    contextMenu->Enable(
            ProDeConstants::COMMAND_CUT,
            registry->isEnabled(ProDeConstants::CMD_NAME_CUT));
        contextMenu->Enable(
            ProDeConstants::COMMAND_MODIFY_COMP,
            registry->isEnabled(ProDeConstants::CMD_NAME_MODIFY_COMP));
        contextMenu->Enable(
            ProDeConstants::COMMAND_DELETE_COMP,
            registry->isEnabled(ProDeConstants::CMD_NAME_MODIFY_COMP));
    }
    view_->canvas()->PopupMenu(contextMenu, wxPoint(x,y));
}
References MDFView::canvas(), ProDeConstants::CMD_NAME_COPY, ProDeConstants::CMD_NAME_CUT, ProDeConstants::CMD_NAME_MODIFY_COMP, ProDeConstants::COMMAND_COPY, ProDeConstants::COMMAND_CUT, ProDeConstants::COMMAND_DELETE_COMP, ProDeConstants::COMMAND_MODIFY_COMP, createDefaultMenu(), CommandRegistry::isEnabled(), and view_.
Referenced by onMouseEvent().
Member Data Documentation
active_
bool SelectTool::active_ private
Tells if the tool is active or not.
Definition at line 65 of file SelectTool.hh.
Referenced by activate(), deactivate(), and onMouseEvent().
figure_
SelectionFigure* SelectTool::figure_ private
Selection figure;.
Definition at line 67 of file SelectTool.hh.
Referenced by leftClick(), SelectTool(), and ~SelectTool().
frame_
ChildFrame* SelectTool::frame_ private
Parent frame of the Canvas.
Definition at line 61 of file SelectTool.hh.
Referenced by onMouseEvent().
view_
MDFView* SelectTool::view_ private
View displayed on the Canvas.
Definition at line 63 of file SelectTool.hh.
Referenced by onMouseEvent(), and popContextMenu().
The documentation for this class was generated from the following files:
SelectTool.hh
SelectTool.cc