OpenASIP: DisassemblyFUPort Class Reference
DisassemblyFUPort Class Reference
#include <DisassemblyFUPort.hh>
Public Member Functions
DisassemblyFUPort (std::string fuName, std::string port)
virtual ~DisassemblyFUPort ()
virtual std::string toString () const
Public Member Functions inherited from DisassemblyElement
virtual ~DisassemblyElement ()
Private Attributes
std::string fuName_
Name of the function unit.
std::string port_
Name of the function unit port.
Additional Inherited Members
Protected Member Functions inherited from DisassemblyElement
DisassemblyElement ()
Detailed Description
Represents a function unit port in the disassembler.
Definition at line 41 of file DisassemblyFUPort.hh.
Constructor & Destructor Documentation
DisassemblyFUPort()
DisassemblyFUPort::DisassemblyFUPort (std::string fuName, std::string port)
The constructor.
Parameters
fuName Name of the function unit.
port Name of the function unit port.
Definition at line 41 of file DisassemblyFUPort.cc.
                                                                    :
    DisassemblyElement(),
    fuName_(fuName),
    port_(port) {
}
~DisassemblyFUPort()
DisassemblyFUPort::~DisassemblyFUPort () virtual
The destructor.
Definition at line 51 of file DisassemblyFUPort.cc.
{
}
Member Function Documentation
toString()
std::string DisassemblyFUPort::toString () const virtual
Returns disassembly of the function unit port.
Returns
Disassembly of the function unit port as a string.
Implements DisassemblyElement.
Definition at line 61 of file DisassemblyFUPort.cc.
{
    return fuName_ + "." + port_;
}
References fuName_, and port_.
Referenced by SimulatorFrontend::compareState(), InfoPortsCommand::execute(), and TTAProgram::TerminalFUPort::toString().
Member Data Documentation
fuName_
std::string DisassemblyFUPort::fuName_ private
Name of the function unit.
Definition at line 48 of file DisassemblyFUPort.hh.
Referenced by toString().
port_
std::string DisassemblyFUPort::port_ private
Name of the function unit port.
Definition at line 50 of file DisassemblyFUPort.hh.
Referenced by toString().
The documentation for this class was generated from the following files:
DisassemblyFUPort.hh
DisassemblyFUPort.cc