OpenASIP: ComponentCommand Class Reference
ComponentCommand Class Reference abstract
#include <ComponentCommand.hh>
Public Member Functions
ComponentCommand ()
virtual ~ComponentCommand ()
virtual bool Do ()=0
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
wxWindow * parentWindow_
Parent window of the command.
Detailed Description
Base class for the commands created by component EditPolicies.
Setting the parent window allows command to popup dialogs.
Definition at line 46 of file ComponentCommand.hh.
Constructor & Destructor Documentation
ComponentCommand()
ComponentCommand::ComponentCommand ()
The Constructor.
Definition at line 38 of file ComponentCommand.cc.
                                  : parentWindow_(NULL) {
}
~ComponentCommand()
ComponentCommand::~ComponentCommand () virtual
The Destructor.
Definition at line 45 of file ComponentCommand.cc.
{
}
Member Function Documentation
Do()
virtual bool ComponentCommand::Do () pure virtual
Implemented in ProximBusDetailsCmd, ProximComponentStatusCmd, ProximFUDetailsCmd, ProximFUPortDetailsCmd, ProximIUDetailsCmd, ProximRFDetailsCmd, ProximSetMachineWinStatusCmd, ProximShowPortsCmd, ProximShowRegistersCmd, ProximSocketDetailsCmd, CopyComponent, DeleteBridgeCmd, DeleteBusCmd, DeleteFUCmd, DeleteGCUCmd, DeleteIUCmd, DeletePortCmd, DeleteRFCmd, DeleteSegmentCmd, DeleteSocketCmd, ModifyBridgeCmd, ModifyBusCmd, ModifyFUCmd, ModifyFUPortCmd, ModifyGCUCmd, ModifyIUCmd, ModifyIUPortCmd, ModifyRFCmd, ModifyRFPortCmd, ModifySocketCmd, ModifySRPortCmd, SetStatusTextCmd, SocketBusConnCmd, and SocketPortConnCmd.
Referenced by CopyComponentCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), ModifyComponentCmd::Do(), ConnectTool::leftClick(), ProximMachineCanvasTool::onMouseEvent(), SelectTool::onMouseEvent(), ProximMachineStateWindow::onSimulationStop(), and ConnectTool::updateStatusline().
parentWindow()
wxWindow * ComponentCommand::parentWindow ()
Returns the parent window for the dialogs created by this command.
Returns
The parent window for the dialogs created by this command.
Definition at line 66 of file ComponentCommand.cc.
{
    return parentWindow_;
}
References parentWindow_.
Referenced by ModifyBridgeCmd::Do(), ModifyBusCmd::Do(), ModifyFUCmd::Do(), ModifyFUPortCmd::Do(), ModifyGCUCmd::Do(), ModifyIUCmd::Do(), ModifyIUPortCmd::Do(), ModifyRFCmd::Do(), ModifyRFPortCmd::Do(), ModifySocketCmd::Do(), and ModifySRPortCmd::Do().
setParentWindow()
void ComponentCommand::setParentWindow (wxWindow * window)
Sets a parent window for the dialogs created by this command.
Parameters
window A parent window for the dialogs.
Definition at line 55 of file ComponentCommand.cc.
{
    parentWindow_ = window;
}
References parentWindow_.
Referenced by CopyComponentCmd::Do(), CutComponentCmd::Do(), ModifyComponentCmd::Do(), and ProximMachineCanvasTool::onMouseEvent().
Member Data Documentation
parentWindow_
wxWindow* ComponentCommand::parentWindow_ private
Parent window of the command.
Definition at line 58 of file ComponentCommand.hh.
Referenced by parentWindow(), and setParentWindow().
The documentation for this class was generated from the following files:
ComponentCommand.hh
ComponentCommand.cc