OpenASIP: ProGeCmdLineOptions Class Reference
ProGeCmdLineOptions Class Reference
#include <ProGeCmdLineOptions.hh>
Public Member Functions
ProGeCmdLineOptions ()
virtual ~ProGeCmdLineOptions ()
std::string processorToGenerate () const
std::string bemFile () const
std::string idfFile () const
std::string hdl () const
std::string outputDirectory () const
std::string sharedOutputDirectory () const
std::string pluginParametersQuery () const
bool generateTestbench () const
std::string mode () const
std::string integratorName () const
std::string imemType () const
std::string dmemType () const
int clockFrequency () const
std::string tpefName () const
std::string entityName () const
bool useAbsolutePaths () const
bool listAvailableIntegrators () const
std::string deviceFamilyName () const
std::string deviceName () const
std::string simulationRuntime () const
bool forceOutputDirectory () const
bool asyncReset () const
bool syncReset () const
std::vector< std::string > commaSeparatedList (const std::string argumentName) const
std::vector< std::string > hdbList () const
std::vector< std::string > rfIcGateList () const
std::vector< std::string > fuIcGateList () const
std::vector< std::pair< std::string, std::string > > icdArgList () const
bool preferHDLGeneration () const
bool resetAllRegisters () const
std::vector< std::string > fuBackRegistered () const
std::vector< std::string > fuFrontRegistered () const
std::vector< std::string > fuMiddleRegistered () const
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line options for the command line interface of ProGe (generateprocessor).
Definition at line 43 of file ProGeCmdLineOptions.hh.
Constructor & Destructor Documentation
ProGeCmdLineOptions()
ProGeCmdLineOptions::ProGeCmdLineOptions ()
The constructor.
Definition at line 77 of file ProGeCmdLineOptions.cc.
                                         :
    CmdLineOptions("") {
    StringCmdLineOptionParser* bemFile = new StringCmdLineOptionParser(
        BEM_PARAM_NAME, "The BEM file", "b");
    addOption(bemFile);
    StringCmdLineOptionParser* idfFile = new StringCmdLineOptionParser(
        IDF_PARAM_NAME, "The IDF file", "i");
    addOption(idfFile);
    StringCmdLineOptionParser* hdlParam = new StringCmdLineOptionParser(
        HDL_PARAM_NAME, "The HDL to generate. 'vhdl' = VHDL", "l");
    addOption(hdlParam);
    StringCmdLineOptionParser* outputDirectory =
        new StringCmdLineOptionParser(
            OUTPUTDIR_PARAM_NAME, "The output directory", "o");
    addOption(outputDirectory);
    StringCmdLineOptionParser* sharedOutputDirectory =
        new StringCmdLineOptionParser(
            SHARED_OUTPUTDIR_PARAM_NAME,
            "The directory for HDL files that are potentially shared between "
            "multiple generated processors.", "s");
    addOption(sharedOutputDirectory);
    StringCmdLineOptionParser* pluginParameters =
        new StringCmdLineOptionParser(
            PLUGIN_PARAMETERS_PARAM_NAME, "List plugin parameters for an "
            "IC/Decoder generator plugin file.", "u");
    addOption(pluginParameters);
    StringCmdLineOptionParser* integratorName =
        new StringCmdLineOptionParser(
            INTEGRATOR_NAME, "Select the target for platform integration.",
            "g");
    addOption(integratorName);
    StringCmdLineOptionParser* imemType = new StringCmdLineOptionParser(
        IMEM_TYPE,
        "Instruction memory type. Available types depends on "
        "the platform integrator. Types are 'vhdl_array', 'onchip', "
        "'sram', 'dram' and 'none'.",
        "f");
    addOption(imemType);
    StringCmdLineOptionParser* dmemType =
        new StringCmdLineOptionParser(
            DMEM_TYPE, "Data memory type. Available types depends on the "
            "platform integrator. Types are 'vhdl_array', 'onchip', 'sram',"
            " 'dram' and 'none'", "d");
    addOption(dmemType);
    IntegerCmdLineOptionParser* fmax =
        new IntegerCmdLineOptionParser(
            CLK_FREQUENCY, "Defines the target clock frequency.", "c");
    addOption(fmax);
    StringCmdLineOptionParser* programName =
        new StringCmdLineOptionParser(
            TPEF_NAME, "Name of tpef program.", "p");
    addOption(programName);
    StringCmdLineOptionParser* entityName = new StringCmdLineOptionParser(
        ENTITY_NAME,
        "String to use to make the generated VHDL entities unique. This "
        "is also used in the name of the top level entity platform "
        "integrator creates. Default is 'tta0' for the core, thus "
        "'tta0_toplevel' for the platform integrator top level "
        "component.",
        "e");
    addOption(entityName);
    BoolCmdLineOptionParser* useAbsolutePaths =
        new BoolCmdLineOptionParser(
            USE_ABSOLUTE_PATHS, "Use absolute paths in generated platform "
            "integrator files.", "a");
    addOption(useAbsolutePaths);
    BoolCmdLineOptionParser* generateTestbench =
        new BoolCmdLineOptionParser(
            GENERATE_TESTBENCH, "Generate testbench.", "t");
    addOption(generateTestbench);
    BoolCmdLineOptionParser* listIntegrators =
        new BoolCmdLineOptionParser(
            LIST_INTEGRATORS, "List available integrators and information "
            "about them.", "n");
    addOption(listIntegrators);
    StringCmdLineOptionParser* deviceFamilyName =
        new StringCmdLineOptionParser(
            DEVICE_FAMILY,
            "Set FPGA device family for integration. Stand-alone integrators "
            "may ignore this parameter. Example: \"Stratix II\" or "
            "Stratix\\ II", "m");
    addOption(deviceFamilyName);
    StringCmdLineOptionParser* deviceName = new StringCmdLineOptionParser(
        DEVICE_NAME,
        "Set FPGA device family for integration. Stand-alone integrators "
        "may ignore this parameter. Example: \"xc7z020clg400-1\"");
    addOption(deviceName);
    IntegerCmdLineOptionParser* simTime = new IntegerCmdLineOptionParser(
        SIMULATION_RUNTIME,
        "The runtime of the simulation in nanoseconds. Default: 52390 ns",
        "r");
    addOption(simTime);
    BoolCmdLineOptionParser* forceOutput = new BoolCmdLineOptionParser(
        FORCE_OUTPUT, "Forces output writing into existing directory.", "F");
    addOption(forceOutput);
    BoolCmdLineOptionParser* syncReset = new BoolCmdLineOptionParser(
        SYNC_RESET, "Generate Synchronous reset (default async).");
    addOption(syncReset);
    StringCmdLineOptionParser* hdbList = new StringCmdLineOptionParser(
        HDB_LIST, "Comma separated list of HDBs for automated generation.",
        "h");
    addOption(hdbList);
    StringCmdLineOptionParser* icdArgList = new StringCmdLineOptionParser(
        ICD_ARG_LIST,
        "Comma separated list of IC decoder plugin arguments "
        "for automated generation.");
    addOption(icdArgList);
    BoolCmdLineOptionParser* preferGen = new BoolCmdLineOptionParser(
        PREFER_GEN,
        "Prefer HDL generation over existing HDB implementations.");
    addOption(preferGen);
    BoolCmdLineOptionParser* resetAll = new BoolCmdLineOptionParser(
        DONT_RESET_ALL,
        "Doesn't reset unnecessary registers (default false).");
    addOption(resetAll);
    StringCmdLineOptionParser* rfIcGateList = new StringCmdLineOptionParser(
        RF_ICGATE_LIST, "Comma separated list of RFs to IC-Gate.");
    addOption(rfIcGateList);
    StringCmdLineOptionParser* fuIcGateList = new StringCmdLineOptionParser(
        FU_ICGATE_LIST, "Comma separated list of FUs to IC-Gate.");
    addOption(fuIcGateList);
    StringCmdLineOptionParser* fuBackRegList = new StringCmdLineOptionParser(
        FU_BACKREGISTER_LIST,
        "Comma separated list of FUs to back-register.");
    addOption(fuBackRegList);
    StringCmdLineOptionParser* fuFrontRegList = new StringCmdLineOptionParser(
        FU_FRONTREGISTER_LIST,
        "Comma separated list of FUs to front-register.");
    addOption(fuFrontRegList);
    StringCmdLineOptionParser* fuMiddleRegList =
        new StringCmdLineOptionParser(
            FU_MIDDLEREGISTER_LIST,
            "Comma separated list of FUs to middle-register.");
    addOption(fuMiddleRegList);
}
References CmdLineParser::addOption(), BEM_PARAM_NAME, bemFile(), CLK_FREQUENCY, DEVICE_FAMILY, DEVICE_NAME, deviceFamilyName(), deviceName(), DMEM_TYPE, dmemType(), DONT_RESET_ALL, ENTITY_NAME, entityName(), FORCE_OUTPUT, FU_BACKREGISTER_LIST, FU_FRONTREGISTER_LIST, FU_ICGATE_LIST, FU_MIDDLEREGISTER_LIST, fuIcGateList(), GENERATE_TESTBENCH, generateTestbench(), HDB_LIST, hdbList(), HDL_PARAM_NAME, ICD_ARG_LIST, icdArgList(), IDF_PARAM_NAME, idfFile(), IMEM_TYPE, imemType(), INTEGRATOR_NAME, integratorName(), LIST_INTEGRATORS, OUTPUTDIR_PARAM_NAME, outputDirectory(), PLUGIN_PARAMETERS_PARAM_NAME, PREFER_GEN, RF_ICGATE_LIST, rfIcGateList(), SHARED_OUTPUTDIR_PARAM_NAME, sharedOutputDirectory(), SIMULATION_RUNTIME, SYNC_RESET, syncReset(), TPEF_NAME, USE_ABSOLUTE_PATHS, and useAbsolutePaths().
~ProGeCmdLineOptions()
ProGeCmdLineOptions::~ProGeCmdLineOptions () virtual
The destructor.
Definition at line 246 of file ProGeCmdLineOptions.cc.
{
}
Member Function Documentation
asyncReset()
bool ProGeCmdLineOptions::asyncReset () const
Returns true if asynchronous reset.
Definition at line 436 of file ProGeCmdLineOptions.cc.
{
    return !findOption(SYNC_RESET)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SYNC_RESET.
bemFile()
std::string ProGeCmdLineOptions::bemFile () const
Returns the given BEM file.
Returns
The name of the file.
Definition at line 267 of file ProGeCmdLineOptions.cc.
{
    return findOption(BEM_PARAM_NAME)->String();
}
References BEM_PARAM_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
clockFrequency()
int ProGeCmdLineOptions::clockFrequency () const
Definition at line 345 of file ProGeCmdLineOptions.cc.
{
    int freq = 0;
    if (findOption(CLK_FREQUENCY)->isDefined()) {
        freq = findOption(CLK_FREQUENCY)->integer();
    }
    return freq;
}
References CLK_FREQUENCY, CmdLineParser::findOption(), and CmdLineOptionParser::integer().
commaSeparatedList()
std::vector< std::string > ProGeCmdLineOptions::commaSeparatedList (const std::string argumentName) const
Helper for arguments with comma-separated arguments
Definition at line 444 of file ProGeCmdLineOptions.cc.
{
    std::vector<std::string> list;
    std::string str;
    if (findOption(argumentName)->isDefined()) {
        str = findOption(argumentName)->String();
    }
    std::stringstream ss(str);
    while (ss.good()) {
        std::string sub;
        std::getline(ss, sub, ',');
        if (sub.size() > 1) {
            list.emplace_back(sub);
        }
    }
    return list;
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and sub.
Referenced by fuBackRegistered(), fuFrontRegistered(), fuIcGateList(), fuMiddleRegistered(), hdbList(), icdArgList(), and rfIcGateList().
deviceFamilyName()
std::string ProGeCmdLineOptions::deviceFamilyName () const
Definition at line 382 of file ProGeCmdLineOptions.cc.
{
    string deviceFamily = "";
    if (findOption(DEVICE_FAMILY)->isDefined()) {
        deviceFamily = findOption(DEVICE_FAMILY)->String();
    }
    return deviceFamily;
}
References DEVICE_FAMILY, CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
deviceName()
std::string ProGeCmdLineOptions::deviceName () const
Definition at line 391 of file ProGeCmdLineOptions.cc.
{
    string devicePart = "";
    if (findOption(DEVICE_NAME)->isDefined()) {
        devicePart = findOption(DEVICE_NAME)->String();
    }
    return devicePart;
}
References DEVICE_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
dmemType()
std::string ProGeCmdLineOptions::dmemType () const
Definition at line 339 of file ProGeCmdLineOptions.cc.
{
    return findOption(DMEM_TYPE)->String();
}
References DMEM_TYPE, CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
entityName()
std::string ProGeCmdLineOptions::entityName () const
Definition at line 362 of file ProGeCmdLineOptions.cc.
{
    return findOption(ENTITY_NAME)->String();
}
References ENTITY_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
forceOutputDirectory()
bool ProGeCmdLineOptions::forceOutputDirectory () const
Returns true if ProGe is allowed to write the processor files to an existing directory.
Definition at line 420 of file ProGeCmdLineOptions.cc.
{
    return findOption(FORCE_OUTPUT)->isFlagOn();
}
References CmdLineParser::findOption(), FORCE_OUTPUT, and CmdLineOptionParser::isFlagOn().
fuBackRegistered()
std::vector< std::string > ProGeCmdLineOptions::fuBackRegistered () const
Definition at line 508 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(FU_BACKREGISTER_LIST);
}
References commaSeparatedList(), and FU_BACKREGISTER_LIST.
fuFrontRegistered()
std::vector< std::string > ProGeCmdLineOptions::fuFrontRegistered () const
Definition at line 513 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(FU_FRONTREGISTER_LIST);
}
References commaSeparatedList(), and FU_FRONTREGISTER_LIST.
fuIcGateList()
std::vector< std::string > ProGeCmdLineOptions::fuIcGateList () const
Return list of FUs to IC-Gate.
Definition at line 503 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(FU_ICGATE_LIST);
}
References commaSeparatedList(), and FU_ICGATE_LIST.
Referenced by ProGeCmdLineOptions().
fuMiddleRegistered()
std::vector< std::string > ProGeCmdLineOptions::fuMiddleRegistered () const
Definition at line 518 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(FU_MIDDLEREGISTER_LIST);
}
References commaSeparatedList(), and FU_MIDDLEREGISTER_LIST.
generateTestbench()
bool ProGeCmdLineOptions::generateTestbench () const
Definition at line 372 of file ProGeCmdLineOptions.cc.
{
    return findOption(GENERATE_TESTBENCH)->isFlagOn();
}
References CmdLineParser::findOption(), GENERATE_TESTBENCH, and CmdLineOptionParser::isFlagOn().
Referenced by ProGeCmdLineOptions().
hdbList()
std::vector< std::string > ProGeCmdLineOptions::hdbList () const
Return list of HDBs.
Definition at line 466 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(HDB_LIST);
}
References commaSeparatedList(), and HDB_LIST.
Referenced by ProGeCmdLineOptions().
hdl()
std::string ProGeCmdLineOptions::hdl () const
Returns the given HDL parameter.
Returns
The HDL parameter.
Definition at line 289 of file ProGeCmdLineOptions.cc.
{
    return findOption(HDL_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), HDL_PARAM_NAME, and CmdLineOptionParser::String().
icdArgList()
std::vector< std::pair< std::string, std::string > > ProGeCmdLineOptions::icdArgList () const
Return list of option/argument pairs for ICDecoder plugin
Definition at line 482 of file ProGeCmdLineOptions.cc.
{
    auto raw_pairs = commaSeparatedList(ICD_ARG_LIST);
    std::vector<std::pair<std::string, std::string>> parsed_pairs;
    for (std::string key_val_pair : raw_pairs) {
        if (key_val_pair.size() > 1) {
            std::stringstream kvp(key_val_pair);
            std::string key;
            std::string value;
            std::getline(kvp, key, ':');
            std::getline(kvp, value, ':');
            parsed_pairs.emplace_back(key, value);
        }
    }
    return parsed_pairs;
}
References commaSeparatedList(), and ICD_ARG_LIST.
Referenced by ProGeCmdLineOptions().
idfFile()
std::string ProGeCmdLineOptions::idfFile () const
Returns the given IDF file.
Returns
The name of the file.
Definition at line 278 of file ProGeCmdLineOptions.cc.
{
    return findOption(IDF_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), IDF_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
imemType()
std::string ProGeCmdLineOptions::imemType () const
Definition at line 333 of file ProGeCmdLineOptions.cc.
{
    return findOption(IMEM_TYPE)->String();
}
References CmdLineParser::findOption(), IMEM_TYPE, and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
integratorName()
std::string ProGeCmdLineOptions::integratorName () const
Definition at line 327 of file ProGeCmdLineOptions.cc.
{
    return findOption(INTEGRATOR_NAME)->String();
}
References CmdLineParser::findOption(), INTEGRATOR_NAME, and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
listAvailableIntegrators()
bool ProGeCmdLineOptions::listAvailableIntegrators () const
Definition at line 377 of file ProGeCmdLineOptions.cc.
{
    return findOption(LIST_INTEGRATORS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and LIST_INTEGRATORS.
mode()
std::string ProGeCmdLineOptions::mode () const
outputDirectory()
std::string ProGeCmdLineOptions::outputDirectory () const
Returns the given output directory.
Returns
The given output directory.
Definition at line 300 of file ProGeCmdLineOptions.cc.
{
    return findOption(OUTPUTDIR_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), OUTPUTDIR_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
pluginParametersQuery()
std::string ProGeCmdLineOptions::pluginParametersQuery () const
Returns the IC/decoder generator plugin parameter list query.
Returns
The plugin parameter query.
Definition at line 321 of file ProGeCmdLineOptions.cc.
{
    return findOption(PLUGIN_PARAMETERS_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), PLUGIN_PARAMETERS_PARAM_NAME, and CmdLineOptionParser::String().
preferHDLGeneration()
bool ProGeCmdLineOptions::preferHDLGeneration () const
Returns true if preferring HDL Generation.
Definition at line 526 of file ProGeCmdLineOptions.cc.
{
    return findOption(PREFER_GEN)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and PREFER_GEN.
printHelp()
void ProGeCmdLineOptions::printHelp () const virtual
Prints help of the application.
Reimplemented from CmdLineOptions.
Definition at line 552 of file ProGeCmdLineOptions.cc.
{
    printVersion();
    cout << "Usage: generateprocessor [options] <processor>" << endl
         << "where <processor> means either an ADF or PCF file." << endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void ProGeCmdLineOptions::printVersion () const virtual
Prints the version of the application.
Implements CmdLineOptions.
Definition at line 542 of file ProGeCmdLineOptions.cc.
{
    std::cout << "generateprocessor - OpenASIP Processor Generator "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
processorToGenerate()
std::string ProGeCmdLineOptions::processorToGenerate () const
Returns the ADF or PCF file given as last argument.
Returns
The name of the file.
Definition at line 256 of file ProGeCmdLineOptions.cc.
{
    return argument(numberOfArguments());
}
References CmdLineParser::argument(), and CmdLineParser::numberOfArguments().
resetAllRegisters()
bool ProGeCmdLineOptions::resetAllRegisters () const
Returns true if all registers should be reseted.
Definition at line 534 of file ProGeCmdLineOptions.cc.
{
    return !findOption(DONT_RESET_ALL)->isFlagOn();
}
References DONT_RESET_ALL, CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
rfIcGateList()
std::vector< std::string > ProGeCmdLineOptions::rfIcGateList () const
Return list of RFs to IC-Gate.
Definition at line 474 of file ProGeCmdLineOptions.cc.
{
    return commaSeparatedList(RF_ICGATE_LIST);
}
References commaSeparatedList(), and RF_ICGATE_LIST.
Referenced by ProGeCmdLineOptions().
sharedOutputDirectory()
std::string ProGeCmdLineOptions::sharedOutputDirectory () const
Returns the given output directory.
Returns
The given output directory.
Definition at line 310 of file ProGeCmdLineOptions.cc.
{
    return findOption(SHARED_OUTPUTDIR_PARAM_NAME)->String();
}
References CmdLineParser::findOption(), SHARED_OUTPUTDIR_PARAM_NAME, and CmdLineOptionParser::String().
Referenced by ProGeCmdLineOptions().
simulationRuntime()
std::string ProGeCmdLineOptions::simulationRuntime () const
Gets the HDL simulation time from Cmd line options. If none given, the legacy MAGICAL RUNTIME CONSTANT value 52390ns will be used.
Definition at line 404 of file ProGeCmdLineOptions.cc.
{
    int simTime = 52390;
    if (findOption(SIMULATION_RUNTIME)->isDefined()) {
        simTime = findOption(SIMULATION_RUNTIME)->integer();
    }
    std::ostringstream s;
    s << simTime;
    return s.str();
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and SIMULATION_RUNTIME.
syncReset()
bool ProGeCmdLineOptions::syncReset () const
Returns true if synchronous reset.
Definition at line 428 of file ProGeCmdLineOptions.cc.
{
    return findOption(SYNC_RESET)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and SYNC_RESET.
Referenced by ProGeCmdLineOptions().
tpefName()
std::string ProGeCmdLineOptions::tpefName () const
Definition at line 356 of file ProGeCmdLineOptions.cc.
{
    return findOption(TPEF_NAME)->String();
}
References CmdLineParser::findOption(), CmdLineOptionParser::String(), and TPEF_NAME.
useAbsolutePaths()
bool ProGeCmdLineOptions::useAbsolutePaths () const
Definition at line 367 of file ProGeCmdLineOptions.cc.
{
    return findOption(USE_ABSOLUTE_PATHS)->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and USE_ABSOLUTE_PATHS.
Referenced by ProGeCmdLineOptions().
The documentation for this class was generated from the following files:
ProGeCmdLineOptions.hh
ProGeCmdLineOptions.cc