OpenASIP: CommandsCommand Class Reference
CommandsCommand Class Reference
#include <CommandsCommand.hh>
Public Member Functions
CommandsCommand ()
virtual ~CommandsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "commands" command of the Simulator Control Language.
Definition at line 47 of file CommandsCommand.hh.
Constructor & Destructor Documentation
CommandsCommand()
CommandsCommand::CommandsCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 52 of file CommandsCommand.cc.
                                 :
    SimControlLanguageCommand("commands") {
}
~CommandsCommand()
CommandsCommand::~CommandsCommand () virtual
Destructor.
Does nothing.
Definition at line 61 of file CommandsCommand.cc.
{
}
Member Function Documentation
execute()
bool CommandsCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "commands" command.
Displays the given count of entries in the command history log.
Parameters
arguments The count of entries to be printed.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 75 of file CommandsCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 0, 1)) {
        return false;
    }
    std::size_t commandCount = 10;
    if (arguments.size() == 2) {
        if  (!checkPositiveIntegerArgument(arguments[1])) {
            return false;
        }
        commandCount = arguments[1].integerValue();
    }
    commandCount = std::min(
        commandCount, interpreter()->lineReader()->inputsInHistory());
    for (int i = commandCount - 1; i >= 0; --i) {
        outputStream()
            << StringTools::trim(
                interpreter()->lineReader()->inputHistoryEntry(i))
            << std::endl;
    }
    return true;
}
References CustomCommand::checkArgumentCount(), CustomCommand::checkPositiveIntegerArgument(), CustomCommand::interpreter(), SimControlLanguageCommand::outputStream(), and StringTools::trim().
helpText()
std::string CommandsCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 109 of file CommandsCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_COMMANDS).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_COMMANDS.
The documentation for this class was generated from the following files:
CommandsCommand.hh
CommandsCommand.cc