OpenASIP: UnsignedIntegerCmdLineOptionParser Class Reference
UnsignedIntegerCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
UnsignedIntegerCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~UnsignedIntegerCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual unsigned unsignedInteger (int index=0) const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual std::string String (int index=0) const
virtual double real () const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
virtual int listSize () const
Private Member Functions
UnsignedIntegerCmdLineOptionParser (const UnsignedIntegerCmdLineOptionParser &)
Copying not allowed.
UnsignedIntegerCmdLineOptionParser & operator= (const UnsignedIntegerCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
unsigned value_
The value of option.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
Models an option that has an unsigned integer value.
Definition at line 147 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
UnsignedIntegerCmdLineOptionParser() [1/2]
UnsignedIntegerCmdLineOptionParser::UnsignedIntegerCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 269 of file CmdLineOptionParser.cc.
                     :
    CmdLineOptionParser(name, desc, alias), value_(0) {
}
~UnsignedIntegerCmdLineOptionParser()
UnsignedIntegerCmdLineOptionParser::~UnsignedIntegerCmdLineOptionParser () virtual
Destructor.
Definition at line 279 of file CmdLineOptionParser.cc.
{
}
UnsignedIntegerCmdLineOptionParser() [2/2]
UnsignedIntegerCmdLineOptionParser::UnsignedIntegerCmdLineOptionParser (const UnsignedIntegerCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * UnsignedIntegerCmdLineOptionParser::copy () const virtual
Implements CmdLineOptionParser.
Definition at line 283 of file CmdLineOptionParser.cc.
{
    UnsignedIntegerOptionValue* copy = new UnsignedIntegerOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
operator=()
UnsignedIntegerCmdLineOptionParser & UnsignedIntegerCmdLineOptionParser::operator= (const UnsignedIntegerCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool UnsignedIntegerCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the unsigned integer option value.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine If the arguments of option are erronous.
Implements CmdLineOptionParser.
Definition at line 297 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for unsigned integer option";
        string method = "UnsignedIntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    if (arguments == "") {
        string msg = "Missing value for unsigned integer option.";
        string method = "UnsignedIntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    istringstream istream(arguments);
    if((!(istream >> value_)) || istream.peek() != EOF) {
        string msg = "Format of " + longName() + " option value was wrong: "
            + arguments;
        string method = "unsignedIntegerCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    setDefined();
    return true;
}
References CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and value_.
unsignedInteger()
unsigned UnsignedIntegerCmdLineOptionParser::unsignedInteger (int index = 0) const virtual
Returns the value of the unsigned integer option.
Parameters
index This must be zero for usigned integer option.
Returns
The value of usigned integer option.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 331 of file CmdLineOptionParser.cc.
{
    assert(index == 0);
    return value_;
}
References assert, and value_.
Member Data Documentation
value_
unsigned UnsignedIntegerCmdLineOptionParser::value_ private
The value of option.
Definition at line 169 of file CmdLineOptionParser.hh.
Referenced by copy(), parseValue(), and unsignedInteger().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc