OpenASIP: llvm::TCEStubTargetMachine Class Reference
llvm::TCEStubTargetMachine Class Reference
#include <TCEStubTargetMachine.hh>
Public Member Functions
TCEStubTargetMachine (const Target &T, const Triple &TT, const llvm::StringRef &CPU, const llvm::StringRef &FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
virtual ~TCEStubTargetMachine ()
const TCEStubSubTarget * getSubtargetImpl () const
const TCEStubSubTarget * getSubtargetImpl (const Function &) const override
Public Member Functions inherited from llvm::TCEBaseTargetMachine
TCEBaseTargetMachine (const Target &T, const Triple &TT, const llvm::StringRef &CPU, const llvm::StringRef &FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
virtual void setTTAMach (const TTAMachine::Machine *mach)
Protected Attributes
std::unique_ptr< TargetLoweringObjectFile > TLOF
TCEStubSubTarget * ST
Additional Inherited Members
Public Attributes inherited from llvm::TCEBaseTargetMachine
const TTAMachine::Machine * ttaMach_
Detailed Description
TargetStub for middle end optimizations. (for loopvectorizer initially)
Definition at line 102 of file TCEStubTargetMachine.hh.
Constructor & Destructor Documentation
TCEStubTargetMachine()
TCEStubTargetMachine::TCEStubTargetMachine (const Target & T, const Triple & TT, const llvm::StringRef & CPU, const llvm::StringRef & FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
Definition at line 134 of file TCEStubTargetMachine.cc.
                              :
    TCEBaseTargetMachine(T, TT, CPU, FS, Options,
                         RM?*RM:Reloc::Model::Static,
                         CM?*CM:CodeModel::Small, OL),
    // Note: Reloc::Model does not have "Default" named member. "Static" is ok?
    // Note: CodeModel does not have "Default" named member. "Small" is ok?
    TLOF(new TargetLoweringObjectFileELF) {
//    TLOF(new TargetLoweringObjectFile) {
    ST = new TCEStubSubTarget(TT, CPU, FS, *this);
    // For autovectorization to work we need to set target machine information:
    auto* option = static_cast<llvm::cl::opt<std::string>*>(
        llvm::cl::getRegisteredOptions().lookup("adf"));
    const std::string adfName = option->getValue();
    ADFSerializer serializer;
    if (adfName == "") {
        const std::string msg = "ADF not passed to opt,"
                                "make sure it is included in oacc";
        throw CompileError(__FILE__, __LINE__, __func__, msg);
    }
    serializer.setSourceFile(adfName);
    // Create and set TTAMachine
    TTAMachine::Machine* targetTTAMachine = serializer.readMachine();
    setTTAMach(targetTTAMachine);
}
References __func__, ADFSerializer::readMachine(), XMLSerializer::setSourceFile(), llvm::TCEBaseTargetMachine::setTTAMach(), and ST.
~TCEStubTargetMachine()
TCEStubTargetMachine::~TCEStubTargetMachine () virtual
Definition at line 170 of file TCEStubTargetMachine.cc.
{}
Member Function Documentation
getSubtargetImpl() [1/2]
const TCEStubSubTarget * llvm::TCEStubTargetMachine::getSubtargetImpl () const inline
Definition at line 124 of file TCEStubTargetMachine.hh.
{
            return ST;
        }
References ST.
getSubtargetImpl() [2/2]
const TCEStubSubTarget * llvm::TCEStubTargetMachine::getSubtargetImpl (const Function &) const inline override
Definition at line 127 of file TCEStubTargetMachine.hh.
{
            return ST;
        }
References ST.
Member Data Documentation
ST
TCEStubSubTarget* llvm::TCEStubTargetMachine::ST protected
Definition at line 105 of file TCEStubTargetMachine.hh.
Referenced by getSubtargetImpl(), getSubtargetImpl(), and TCEStubTargetMachine().
TLOF
std::unique_ptr<TargetLoweringObjectFile> llvm::TCEStubTargetMachine::TLOF protected
Definition at line 104 of file TCEStubTargetMachine.hh.
The documentation for this class was generated from the following files:
TCEStubTargetMachine.hh
TCEStubTargetMachine.cc