OpenASIP: GCUState Class Reference
GCUState Class Reference
#include <GCUState.hh>
Public Member Functions
GCUState (int latency, int nww, int cuDelaySlots, int instructionAddressIncrement=1)
virtual ~GCUState ()
InstructionAddress & programCounter ()
SimValue & returnAddressRegister ()
void setProgramCounter (const InstructionAddress &value)
void setReturnAddress (const InstructionAddress &value)
void setReturnAddress ()
virtual void advanceClock ()
virtual void reset ()
this is called at (re)initialization of the simulation
virtual OperationContext & context ()
Public Member Functions inherited from FUState
FUState ()
FUState (const TCEString &name)
virtual ~FUState ()
void setTriggered ()
void setOperation (Operation &operation)
void setOperation (Operation &operation, OperationExecutor &executor)
bool isIdle ()
virtual void endClock ()
virtual void addInputPortState (PortState &port)
virtual void addOutputPortState (PortState &port)
virtual void addOperationExecutor (OperationExecutor &opExec, Operation &op)
virtual void setOperationSimulator (DetailedOperationSimulator &sim)
virtual void replaceOperationExecutor (Operation &op, OperationExecutor *newExecutor)
virtual OperationExecutor * executor (Operation &op)
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Private Member Functions
GCUState (const GCUState &)
Copying not allowed.
GCUState & operator= (const GCUState &)
Assignment not allowed.
Private Attributes
int naturalWordWidth_
Natural word width as minimum addressable units.
SimValue returnAddressRegister_
The return address register.
InstructionAddress programCounter_
Program counter.
InstructionAddress newProgramCounter_
In case an control flow operation is pending, this variable contains the program counter value that should be updated when the control stage counter goes down.
int latency_
The delay of the control flow operations to take place.
int branchDelayCycles_
The delay of branch operations in the pipeline, as opposed to this unit.
bool operationPending_
If this this is true, there's a control flow operation pending.
int operationPendingTime_
This indicates how many cycles the operation has been pending, when this reaches the latency, the PC is updated with the new value.
OperationContext operationContext_
The operation context for this FU.
int instructionAddressIncrement_ = 1
The increment to instruction address to retrieve next instruction.
Additional Inherited Members
Protected Attributes inherited from FUState
bool idle_
The idle status of the FU. The derived classes should alway set this to true when possible to avoid unnecessary advanceClock() and endClock() calls.
Detailed Description
Models the global control unit state.
Definition at line 46 of file GCUState.hh.
Constructor & Destructor Documentation
GCUState() [1/2]
GCUState::GCUState (int latency, int nww, int cuDelaySlots, int instructionAddressIncrement = 1)
Constructor.
Parameters
latency Latency of the unit.
nww Natural word width as MAUs.
lock Global lock signal.
Definition at line 49 of file GCUState.cc.
                                     :
    naturalWordWidth_(nww), returnAddressRegister_(64),
    latency_(latency),
    branchDelayCycles_(cuDelaySlots),
    operationContext_(
        NULL, programCounter_, returnAddressRegister_,
        branchDelayCycles_),
        instructionAddressIncrement_(instructionAddressIncrement) {
    reset();
}
References reset().
~GCUState()
GCUState::~GCUState () virtual
Destructor.
Definition at line 76 of file GCUState.cc.
                    {
}
GCUState() [2/2]
GCUState::GCUState (const GCUState &) private
Copying not allowed.
Member Function Documentation
advanceClock()
void GCUState::advanceClock () virtual
Handles the actions when clock is advanced.
The value of program counter is updated. Pipeline is advanced.
Reimplemented from FUState.
Definition at line 98 of file GCUState.cc.
                       {
    // For call and jump operations
    if (operationPending_) {
        operationPendingTime_--;
    }
    if (operationPending_ && operationPendingTime_ <= 0) {
        programCounter_ = newProgramCounter_;
        operationPending_ = false;
    }
    // Special handling for Loop Buffer Setup operation
    if (!context().isEmpty()) {
        idle_ = false;
        context().advanceClock();
    } else {
        idle_ = !operationPending_;
    }
}
References OperationContext::advanceClock(), context(), FUState::idle_, newProgramCounter_, operationPending_, operationPendingTime_, and programCounter_.
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
context()
OperationContext & GCUState::context () virtual
Returns the operation context.
This is basically a "template method" to allow differently initialized OperationContext-classes in FUState subclasses.
Returns
The operation context for the FU.
Reimplemented from FUState.
Definition at line 88 of file GCUState.cc.
                  {
    return operationContext_;
}
References operationContext_.
Referenced by advanceClock().
operator=()
GCUState & GCUState::operator= (const GCUState &) private
Assignment not allowed.
programCounter()
InstructionAddress & GCUState::programCounter ()
Referenced by OTASimulationController::advanceMachineCycle(), OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
reset()
void GCUState::reset () virtual
this is called at (re)initialization of the simulation
Reimplemented from FUState.
Definition at line 65 of file GCUState.cc.
                {
    programCounter_ = 0;
    returnAddressRegister_ = 0;
    newProgramCounter_ = 0;
    operationPending_ = false;
    operationPendingTime_ = 0;
}
References newProgramCounter_, operationPending_, operationPendingTime_, programCounter_, and returnAddressRegister_.
Referenced by GCUState().
returnAddressRegister()
SimValue & GCUState::returnAddressRegister ()
Referenced by MachineStateBuilder::buildMachineState().
setProgramCounter()
void GCUState::setProgramCounter (const InstructionAddress & value)
Referenced by TransportPipeline::startOperation().
setReturnAddress() [1/2]
void GCUState::setReturnAddress ()
setReturnAddress() [2/2]
void GCUState::setReturnAddress (const InstructionAddress & value)
Referenced by TransportPipeline::startOperation().
Member Data Documentation
branchDelayCycles_
int GCUState::branchDelayCycles_ private
The delay of branch operations in the pipeline, as opposed to this unit.
Definition at line 85 of file GCUState.hh.
instructionAddressIncrement_
int GCUState::instructionAddressIncrement_ = 1 private
The increment to instruction address to retrieve next instruction.
Definition at line 95 of file GCUState.hh.
latency_
int GCUState::latency_ private
The delay of the control flow operations to take place.
Definition at line 83 of file GCUState.hh.
naturalWordWidth_
int GCUState::naturalWordWidth_ private
Natural word width as minimum addressable units.
Definition at line 73 of file GCUState.hh.
newProgramCounter_
InstructionAddress GCUState::newProgramCounter_ private
In case an control flow operation is pending, this variable contains the program counter value that should be updated when the control stage counter goes down.
Definition at line 81 of file GCUState.hh.
Referenced by advanceClock(), and reset().
operationContext_
OperationContext GCUState::operationContext_ private
The operation context for this FU.
Definition at line 93 of file GCUState.hh.
Referenced by context().
operationPending_
bool GCUState::operationPending_ private
If this this is true, there's a control flow operation pending.
Definition at line 87 of file GCUState.hh.
Referenced by advanceClock(), and reset().
operationPendingTime_
int GCUState::operationPendingTime_ private
This indicates how many cycles the operation has been pending, when this reaches the latency, the PC is updated with the new value.
Definition at line 91 of file GCUState.hh.
Referenced by advanceClock(), and reset().
programCounter_
InstructionAddress GCUState::programCounter_ private
Program counter.
Definition at line 77 of file GCUState.hh.
Referenced by advanceClock(), and reset().
returnAddressRegister_
SimValue GCUState::returnAddressRegister_ private
The return address register.
Definition at line 75 of file GCUState.hh.
Referenced by reset().
The documentation for this class was generated from the following files:
GCUState.hh
GCUState.cc