OpenASIP: TPEF::TPEFSectionReader Class Reference
TPEF::TPEFSectionReader Class Reference
#include <TPEFSectionReader.hh>
Classes
struct Header
Public Member Functions
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Protected Member Functions
TPEFSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual Section::SectionType type () const =0
Returns type (TPEF) section which actual section reader reads.
virtual void finalize (Section *section) const
Static Protected Member Functions
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Private Member Functions
TPEFSectionReader (const TPEFSectionReader &)
Static Private Attributes
static Header header_
Stores values that are needed in actual SectionReader classes.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Detailed Description
Abstract base class for all TPEFSectionReaders.
Class implements default definitions of virtual methods declared in SectionReader class and reading headers of TPEF sections.
Definition at line 48 of file TPEFSectionReader.hh.
Constructor & Destructor Documentation
~TPEFSectionReader()
TPEF::TPEFSectionReader::~TPEFSectionReader () virtual
Destructor
Definition at line 56 of file TPEFSectionReader.cc.
{
}
TPEFSectionReader() [1/2]
TPEF::TPEFSectionReader::TPEFSectionReader () protected
Constructor
Definition at line 50 of file TPEFSectionReader.cc.
                                     : SectionReader() {
}
TPEFSectionReader() [2/2]
TPEF::TPEFSectionReader::TPEFSectionReader (const TPEFSectionReader &) private
Member Function Documentation
header()
const TPEFSectionReader::Header & TPEF::TPEFSectionReader::header () static protected
Returns headers of section that we are currently reading.
Returns
Headers of section that we are currently reading.
Definition at line 174 of file TPEFSectionReader.cc.
{
    return header_;
}
References header_.
Referenced by TPEF::TPEFASpaceSectionReader::readData(), TPEF::TPEFCodeSectionReader::readData(), TPEF::TPEFDataSectionReader::readData(), TPEF::TPEFDebugSectionReader::readData(), TPEF::TPEFLineNumSectionReader::readData(), TPEF::TPEFRelocSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), and TPEF::TPEFUDataSectionReader::readData().
parent()
BinaryReader * TPEF::TPEFSectionReader::parent () const protected virtual
Returns binary reader instance which uses TPEFSectionReader classes.
Returns
Binary reader which uses TPEFSectionReader classes.
Implements TPEF::SectionReader.
Definition at line 65 of file TPEFSectionReader.cc.
{
    return TPEFReader::instance();
}
References TPEF::TPEFReader::instance().
Referenced by TPEF::TPEFRelocSectionReader::finalize(), TPEF::TPEFASpaceSectionReader::readData(), TPEF::TPEFCodeSectionReader::readData(), TPEF::TPEFDataSectionReader::readData(), TPEF::TPEFRelocSectionReader::readData(), readData(), and TPEF::TPEFUDataSectionReader::readData().
readData()
void TPEF::TPEFSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Base implementation for all TPEF section readers. Reads and keeps section header data for later use by concrete section readers. Header data is accessed by readData methods of subclasses.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Implements TPEF::SectionReader.
Reimplemented in TPEF::TPEFASpaceSectionReader, TPEF::TPEFCodeSectionReader, TPEF::TPEFDataSectionReader, TPEF::TPEFDebugSectionReader, TPEF::TPEFLineNumSectionReader, TPEF::TPEFRelocSectionReader, TPEF::TPEFResourceSectionReader, TPEF::TPEFStringSectionReader, TPEF::TPEFSymbolSectionReader, and TPEF::TPEFUDataSectionReader.
Definition at line 86 of file TPEFSectionReader.cc.
{
    TPEFReader* tpefReader = dynamic_cast<TPEFReader*>(parent());
    FileOffset startOffset = stream.readPosition();
    stream.setReadPosition(startOffset + TPEFHeaders::SH_FLAGS);
    Byte sectionFlags = stream.readByte();
    // if section vLen flag is not equal to the read value
    if(section->vLen() != ((sectionFlags & Section::SF_VLEN) != 0)) {
        throw UnexpectedValue(
            __FILE__, __LINE__, __func__,
            "read SF_VLEN flag doesn't match for section");
    }
    section->setFlags(sectionFlags);
    stream.setReadPosition(startOffset + TPEFHeaders::SH_ADDR);
    section->setStartingAddress(stream.readWord());
    stream.setReadPosition(startOffset + TPEFHeaders::SH_LINK);
    header_.linkId = stream.readHalfWord();
    SectionKey linkKey(header_.linkId);
    section->setLink(CREATE_SAFEPOINTER(linkKey));
    // set address space reference
    stream.setReadPosition(startOffset + TPEFHeaders::SH_ASPACE);
    Byte aSpaceIndex = stream.readByte();
    SectionIndexKey aSpaceKey(tpefReader->aSpaceId(), aSpaceIndex);
    section->setASpace(CREATE_SAFEPOINTER(aSpaceKey));
    // set name
    stream.setReadPosition(startOffset + TPEFHeaders::SH_NAME);
    Word sectionOffsetOfName = stream.readWord();
    if (tpefReader->strTableId() != 0) {
        SectionOffsetKey nameKey(tpefReader->strTableId(),
                                 sectionOffsetOfName);
        section->setName(CREATE_SAFEPOINTER(nameKey));
    } else {
        section->setName(&SafePointer::null);
    }
    // add section key for new section
    stream.setReadPosition(startOffset + TPEFHeaders::SH_ID);
    header_.sectionId = stream.readHalfWord();
    SectionKey sectionKey(header_.sectionId);
    SafePointer::addObjectReference(sectionKey, section);
    stream.setReadPosition(startOffset + TPEFHeaders::SH_INFO);
    readInfo(stream, section);
    stream.setReadPosition(startOffset + TPEFHeaders::SH_ENTSIZE);
    header_.elementSize = stream.readWord();
    // read offset of section body
    stream.setReadPosition(startOffset + TPEFHeaders::SH_OFFSET);
    header_.bodyOffset = stream.readWord();
    stream.setReadPosition(startOffset + TPEFHeaders::SH_SIZE);
    header_.bodyLength = stream.readWord();
    // actual class does reading of section body
    stream.setReadPosition(header_.bodyOffset);
}
References __func__, TPEF::ReferenceManager::SafePointer::addObjectReference(), TPEF::TPEFReader::aSpaceId(), TPEF::TPEFSectionReader::Header::bodyLength, TPEF::TPEFSectionReader::Header::bodyOffset, TPEF::TPEFSectionReader::Header::elementSize, header_, TPEF::TPEFSectionReader::Header::linkId, TPEF::ReferenceManager::SafePointer::null, parent(), TPEF::BinaryStream::readByte(), TPEF::BinaryStream::readHalfWord(), readInfo(), TPEF::BinaryStream::readPosition(), TPEF::BinaryStream::readWord(), TPEF::TPEFSectionReader::Header::sectionId, TPEF::Section::setASpace(), TPEF::Section::setFlags(), TPEF::Section::setLink(), TPEF::Section::setName(), TPEF::BinaryStream::setReadPosition(), TPEF::Section::setStartingAddress(), TPEF::Section::SF_VLEN, TPEF::TPEFHeaders::SH_ADDR, TPEF::TPEFHeaders::SH_ASPACE, TPEF::TPEFHeaders::SH_ENTSIZE, TPEF::TPEFHeaders::SH_FLAGS, TPEF::TPEFHeaders::SH_ID, TPEF::TPEFHeaders::SH_INFO, TPEF::TPEFHeaders::SH_LINK, TPEF::TPEFHeaders::SH_NAME, TPEF::TPEFHeaders::SH_OFFSET, TPEF::TPEFHeaders::SH_SIZE, TPEF::TPEFReader::strTableId(), and TPEF::Section::vLen().
Referenced by TPEF::TPEFASpaceSectionReader::readData(), TPEF::TPEFCodeSectionReader::readData(), TPEF::TPEFDataSectionReader::readData(), TPEF::TPEFDebugSectionReader::readData(), TPEF::TPEFLineNumSectionReader::readData(), TPEF::TPEFRelocSectionReader::readData(), TPEF::TPEFResourceSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), TPEF::TPEFSymbolSectionReader::readData(), and TPEF::TPEFUDataSectionReader::readData().
readInfo()
void TPEF::TPEFSectionReader::readInfo (BinaryStream & stream, Section * sect) const protected virtual
Reads info field of section header.
Read position of stream will be moved 4 bytes forward.
Parameters
stream Stream where from info word is read.
Reimplemented in TPEF::TPEFCodeSectionReader, TPEF::TPEFLineNumSectionReader, and TPEF::TPEFRelocSectionReader.
Definition at line 162 of file TPEFSectionReader.cc.
{
    // move four bytes forward by default
    stream.readWord();
}
References TPEF::BinaryStream::readWord().
Referenced by readData().
Member Data Documentation
header_
TPEFSectionReader::Header TPEF::TPEFSectionReader::header_ static private
Stores values that are needed in actual SectionReader classes.
Definition at line 79 of file TPEFSectionReader.hh.
Referenced by header(), and readData().
The documentation for this class was generated from the following files:
TPEFSectionReader.hh
TPEFSectionReader.cc