OpenASIP: ProximLROutputBuffer Class Reference
ProximLROutputBuffer Class Reference
#include <ProximLineReader.hh>
Public Member Functions
ProximLROutputBuffer (ProximLineReader *lineReader)
virtual ~ProximLROutputBuffer ()
Protected Member Functions
int overflow (int)
int sync ()
Private Member Functions
void flushBuffer ()
Private Attributes
ProximLineReader * lineReader_
const unsigned int BUFFER_SIZE
Detailed Description
Stream buffer for the ProximLROutputStream.
This streambuffer converts the stream output to SimulatorEvents when the buffer cotnetnts is flushed.
Definition at line 116 of file ProximLineReader.hh.
Constructor & Destructor Documentation
ProximLROutputBuffer()
ProximLROutputBuffer::ProximLROutputBuffer (ProximLineReader * lineReader)
The Constructor.
Parameters
lineReader ProximLineReader used for output.
Definition at line 223 of file ProximLineReader.cc.
                                                                      :
    std::streambuf(),
    lineReader_(lineReader),
    BUFFER_SIZE(1024)  {
    char* ptr = new char[BUFFER_SIZE];
    setp(ptr, ptr + BUFFER_SIZE);
    setg(0, 0, 0);
}
References BUFFER_SIZE.
~ProximLROutputBuffer()
ProximLROutputBuffer::~ProximLROutputBuffer () virtual
The Destructor.
Definition at line 237 of file ProximLineReader.cc.
{
    sync();
}
References sync().
Member Function Documentation
flushBuffer()
void ProximLROutputBuffer::flushBuffer () private
Sends the buffer contents to the linereader.
Definition at line 279 of file ProximLineReader.cc.
{
    if (pbase() != pptr()) {
        // Buffer is not empty.
        int len = pptr() - pbase();
        char* buffer = new char[len+1];
        strncpy(buffer, pbase(), len);
        buffer[len] = '\0';
        lineReader_->output(std::string(buffer));
        setp(pbase(), epptr());
        delete[] buffer;
    }
}
References lineReader_, and ProximLineReader::output().
Referenced by overflow(), and sync().
overflow()
int ProximLROutputBuffer::overflow (int c) protected
Puts a character at current put position.
This function is called in case there is no room in the buffer to perform the output operation.
Definition at line 248 of file ProximLineReader.cc.
{
    flushBuffer();
    if (c != EOF) {
        if(pbase() == epptr()) {
            // The buffer length is zero, character is sent directly to the
            // linereader.
            lineReader_->output(std::string("") + (char)c);
        } else {
            // Append char to the flushed buffer.
            sputc(c);
        }
    }
    return 0;
}
References flushBuffer(), lineReader_, and ProximLineReader::output().
sync()
int ProximLROutputBuffer::sync () protected
Synchronizes the streambuffer by flushing buffer contents to the linereader.
Definition at line 269 of file ProximLineReader.cc.
{
    flushBuffer();
    return 0;
}
References flushBuffer().
Referenced by ~ProximLROutputBuffer().
Member Data Documentation
BUFFER_SIZE
const unsigned int ProximLROutputBuffer::BUFFER_SIZE private
Definition at line 126 of file ProximLineReader.hh.
Referenced by ProximLROutputBuffer().
lineReader_
ProximLineReader* ProximLROutputBuffer::lineReader_ private
Definition at line 125 of file ProximLineReader.hh.
Referenced by flushBuffer(), and overflow().
The documentation for this class was generated from the following files:
ProximLineReader.hh
ProximLineReader.cc