OpenASIP: SocketBusConnCmd Class Reference
SocketBusConnCmd Class Reference
#include <SocketBusConnCmd.hh>
Public Member Functions
SocketBusConnCmd (TTAMachine::Socket *socket, TTAMachine::Segment *segment)
virtual ~SocketBusConnCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
TTAMachine::Socket * socket_
Socket to connect.
TTAMachine::Segment * segment_
Bus segment to connect.
Detailed Description
Command for connecting/disconencting sockets to bus segments.
Definition at line 43 of file SocketBusConnCmd.hh.
Constructor & Destructor Documentation
SocketBusConnCmd()
SocketBusConnCmd::SocketBusConnCmd (TTAMachine::Socket * socket, TTAMachine::Segment * segment)
The Constructor.
Parameters
segment Segment to connect/disconnect.
socket Socket to connect/disconnect.
Definition at line 52 of file SocketBusConnCmd.cc.
                                                                  :
    ComponentCommand(),
    socket_(socket), segment_(segment) {
}
~SocketBusConnCmd()
SocketBusConnCmd::~SocketBusConnCmd () virtual
The Destructor.
Definition at line 61 of file SocketBusConnCmd.cc.
{
}
Member Function Documentation
Do()
bool SocketBusConnCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 71 of file SocketBusConnCmd.cc.
                     {
    if (socket_->isConnectedTo(*segment_)) {
        try {
            socket_->detachBus(*segment_);
        } catch (Exception& e) {
            return false;
        }
    } else {
        try {
            // If there was no direction before for this socket, let's
            // try to figure out a better guess for it after connected
            // to a port.
            bool resetDirection =
              socket_->direction() == Socket::UNKNOWN;
            socket_->attachBus(*segment_);
            if (resetDirection && socket_->portCount() > 0) {
              if (FUPort *port = dynamic_cast<FUPort*>(socket_->port(0))) {
                TTAMachine::FunctionUnit* FUnit =
                  dynamic_cast<FunctionUnit*>(port->parentUnit());
                for (int i = 0; i < FUnit->operationCount(); ++i) {
                  HWOperation* hwOp = FUnit->operation(i);
                  if (!hwOp->isBound(*port)) continue;
                  int operandId = hwOp->io(*port);
                  OperationPool opPool;
                  Operation& osalOp = opPool.operation(hwOp->name().c_str());
                  if (osalOp.isNull()) break;
                  if (osalOp.operand(operandId).isInput())
                    socket_->setDirection(Socket::INPUT);
                  else
                    socket_->setDirection(Socket::OUTPUT);
                  break;
                }
              } else if (RFPort* port =
                         dynamic_cast<RFPort*>(socket_->port(0))) {
                // RF ports have no other direction clue but the naming, which
                // is often 'rd' or 'wr'. rd is for a port that is _used for_
                // reading data (thus OUTPUT). This is probably a better guess
                // than always assuming one or another.
                if (port->name().size() > 0 && port->name()[0] == 'r')
                  socket_->setDirection(Socket::OUTPUT);
                else
                  socket_->setDirection(Socket::INPUT);
              }
            }
            // HERE.
        } catch (Exception& e) {
            return false;
        }
    }
    return true;
}
References TTAMachine::Socket::attachBus(), TTAMachine::Socket::detachBus(), TTAMachine::Socket::direction(), TTAMachine::Socket::INPUT, TTAMachine::HWOperation::io(), TTAMachine::HWOperation::isBound(), TTAMachine::Socket::isConnectedTo(), Operand::isInput(), Operation::isNull(), TTAMachine::HWOperation::name(), Operation::operand(), OperationPool::operation(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::Socket::OUTPUT, TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), segment_, TTAMachine::Socket::setDirection(), socket_, and TTAMachine::Socket::UNKNOWN.
Member Data Documentation
segment_
TTAMachine::Segment* SocketBusConnCmd::segment_ private
Bus segment to connect.
Definition at line 55 of file SocketBusConnCmd.hh.
Referenced by Do().
socket_
TTAMachine::Socket* SocketBusConnCmd::socket_ private
Socket to connect.
Definition at line 53 of file SocketBusConnCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
SocketBusConnCmd.hh
SocketBusConnCmd.cc