OpenASIP: LongImmediateRegisterState Class Reference
LongImmediateRegisterState Class Reference
#include <LongImmediateRegisterState.hh>
Public Member Functions
LongImmediateRegisterState (LongImmediateUnitState *parent, int index, int width, bool signExtend)
virtual ~LongImmediateRegisterState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Private Member Functions
LongImmediateRegisterState (const LongImmediateRegisterState &)
Copying not allowed.
LongImmediateRegisterState & operator= (const LongImmediateRegisterState &)
Assignment not allowed.
Private Attributes
LongImmediateUnitState * parent_
Parent unit of the register state.
int index_
Index of the register.
int width_
The bit width of the register (needed only while extending).
bool signExtend_
True in case the written values should be sign extended.
Detailed Description
Represents a register of a long immediate unit.
Definition at line 47 of file LongImmediateRegisterState.hh.
Constructor & Destructor Documentation
LongImmediateRegisterState() [1/2]
LongImmediateRegisterState::LongImmediateRegisterState (LongImmediateUnitState * parent, int index, int width, bool signExtend)
Constructor.
Parameters
parent Parent unit of the register.
index Index of the register.
width The bit width of the register.
signExtend True in case written value should be sign extended (default is zero extension).
Definition at line 49 of file LongImmediateRegisterState.cc.
                                                                           :
    StateData(), parent_(parent), index_(index), width_(width),
    signExtend_(signExtend) {
}
~LongImmediateRegisterState()
LongImmediateRegisterState::~LongImmediateRegisterState () virtual
Destructor.
Definition at line 58 of file LongImmediateRegisterState.cc.
{
}
LongImmediateRegisterState() [2/2]
LongImmediateRegisterState::LongImmediateRegisterState (const LongImmediateRegisterState &) private
Copying not allowed.
Member Function Documentation
operator=()
LongImmediateRegisterState & LongImmediateRegisterState::operator= (const LongImmediateRegisterState &) private
Assignment not allowed.
setValue()
void LongImmediateRegisterState::setValue (const SimValue & value) virtual
Sets the value of the register.
Also extends the value if it's narrower than the register width.
Parameters
value New value.
Implements WritableState.
Definition at line 69 of file LongImmediateRegisterState.cc.
{
    // The value is extended in case it's smaller than WORD_BITWIDTH,
    // which is the width of (int) otherwise we won't extend, as it's
    // probably a double. In the future when we support 64 bit or larger
    // integers, this check is not needed.
    if (value.width() < width_) {
        SimValue newValue(width_);
        int ext = width_ - value.width();
        if (signExtend_) {
            SLongWord toBeExtended = value.sLongWordValue();
            newValue = ((long)(toBeExtended << ext) >> ext);
        } else {
            // @todo: this might not be needed, we could assume the top bits
            // to be zero already
            ULongWord toBeExtended = value.uLongWordValue();
            newValue = ((toBeExtended << ext) >> ext);
        }
        parent_->setRegisterValue(index_, newValue);
    } else {
        parent_->setRegisterValue(index_, value);
    }
}
References index_, parent_, LongImmediateUnitState::setRegisterValue(), signExtend_, SimValue::sLongWordValue(), SimValue::uLongWordValue(), value(), SimValue::width(), and width_.
Referenced by LongImmUpdateAction::execute().
value()
const SimValue & LongImmediateRegisterState::value () const virtual
Returns the register value.
Returns
Register value.
Implements ReadableState.
Definition at line 99 of file LongImmediateRegisterState.cc.
{
    return parent_->registerValue(index_);
}
References index_, parent_, and LongImmediateUnitState::registerValue().
Referenced by ProximRegisterWindow::loadImmediateUnit(), and setValue().
Member Data Documentation
index_
int LongImmediateRegisterState::index_ private
Index of the register.
Definition at line 68 of file LongImmediateRegisterState.hh.
Referenced by setValue(), and value().
parent_
LongImmediateUnitState* LongImmediateRegisterState::parent_ private
Parent unit of the register state.
Definition at line 66 of file LongImmediateRegisterState.hh.
Referenced by setValue(), and value().
signExtend_
bool LongImmediateRegisterState::signExtend_ private
True in case the written values should be sign extended.
Definition at line 72 of file LongImmediateRegisterState.hh.
Referenced by setValue().
width_
int LongImmediateRegisterState::width_ private
The bit width of the register (needed only while extending).
Definition at line 70 of file LongImmediateRegisterState.hh.
Referenced by setValue().
The documentation for this class was generated from the following files:
LongImmediateRegisterState.hh
LongImmediateRegisterState.cc