OpenASIP: StringCmdLineOptionParser Class Reference
StringCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
StringCmdLineOptionParser (std::string name, std::string desc, std::string alias="")
virtual ~StringCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual std::string String (int index=0) const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual unsigned unsignedInteger (int index=0) const
virtual double real () const
virtual bool isFlagOn () const
virtual bool isFlagOff () const
virtual int listSize () const
Private Member Functions
StringCmdLineOptionParser (const StringCmdLineOptionParser &)
Copying not allowed.
StringCmdLineOptionParser & operator= (const StringCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
std::string value_
The value of the option.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that has a string as a value.
Definition at line 180 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
StringCmdLineOptionParser() [1/2]
StringCmdLineOptionParser::StringCmdLineOptionParser (std::string name, std::string desc, std::string alias = "")
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 347 of file CmdLineOptionParser.cc.
                     : CmdLineOptionParser(name, desc, alias), value_("") {
}
~StringCmdLineOptionParser()
StringCmdLineOptionParser::~StringCmdLineOptionParser () virtual
Destructor.
Definition at line 356 of file CmdLineOptionParser.cc.
{
}
StringCmdLineOptionParser() [2/2]
StringCmdLineOptionParser::StringCmdLineOptionParser (const StringCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * StringCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memery reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 368 of file CmdLineOptionParser.cc.
{
    StringOptionValue* copy = new StringOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
operator=()
StringCmdLineOptionParser & StringCmdLineOptionParser::operator= (const StringCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool StringCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of option.
Parameters
arguments The arguments of option.
prefix The prefix of option.
Returns
True when parsing is ready.
Exceptions
IllegalCommandLine Not thrown.
Implements CmdLineOptionParser.
Definition at line 382 of file CmdLineOptionParser.cc.
{
    if (prefix != "") {
        string msg = "Illegal prefix for string option";
        string method = "StringCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    if (arguments == "") {
        string msg = "Missing value for string option.";
        string method = "StringCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    value_ = arguments;
    setDefined();
    return true;
}
References CmdLineOptionParser::setDefined(), and value_.
String()
string StringCmdLineOptionParser::String (int index = 0) const virtual
This implementation should be never called.
Returns
Nothing.
Exceptions
WrongSubclass Called for a wrong subclass.
Reimplemented from CmdLineOptionParser.
Definition at line 403 of file CmdLineOptionParser.cc.
{
    assert(index == 0);
    return value_;
}
References assert, and value_.
Member Data Documentation
value_
std::string StringCmdLineOptionParser::value_ private
The value of the option.
Definition at line 200 of file CmdLineOptionParser.hh.
Referenced by copy(), parseValue(), and String().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc