OpenASIP: SimpleResourceManager Class Reference
SimpleResourceManager Class Reference
#include <SimpleResourceManager.hh>
Public Member Functions
virtual bool canAssign (int cycle, MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const override
virtual bool canTransportImmediate (const MoveNode &node, const TTAMachine::Bus *preAssignedBus=NULL) const
virtual void assign (int cycle, MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) override
virtual void unassign (MoveNode &node) override
virtual int earliestCycle (MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const override
virtual int earliestCycle (int cycle, MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const override
virtual int latestCycle (MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const override
virtual int latestCycle (int cycle, MoveNode &node, const TTAMachine::Bus *bus=NULL, const TTAMachine::FunctionUnit *srcFU=NULL, const TTAMachine::FunctionUnit *dstFU=NULL, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const override
virtual bool hasGuard (const MoveNode &node) const
virtual TTAProgram::Instruction * instruction (int cycle) const override
virtual bool supportsExternalAssignments () const override
virtual int largestCycle () const override
virtual int smallestCycle () const override
virtual void loseInstructionOwnership (int cycle)
virtual std::shared_ptr< TTAProgram::TerminalImmediate > immediateValue (const MoveNode &)
virtual int immediateWriteCycle (const MoveNode &) const
virtual bool isTemplateAvailable (int, std::shared_ptr< TTAProgram::Immediate >) const
virtual unsigned int resourceCount () const
virtual void print (std::ostream &target) const
virtual std::string toString () const
virtual unsigned initiationInterval () const
virtual void clearOldResources ()
void setDDG (const DataDependenceGraph *ddg)
void setCFG (const ControlFlowGraph *cfg)
void setBBN (const BasicBlockNode *bbn)
void setMaxCycle (unsigned int maxCycle)
int maxCycle ()
unsigned int instructionIndex (unsigned int) const
Public Member Functions inherited from ResourceManager
ResourceManager (const TTAMachine::Machine &machine)
virtual ~ResourceManager ()
const TTAMachine::Machine & machine () const
Static Public Member Functions
static SimpleResourceManager * createRM (const TTAMachine::Machine &machine, unsigned int ii=0)
static void disposeRM (SimpleResourceManager *rm, bool allowReuse=true)
Private Member Functions
SimpleResourceManager (const TTAMachine::Machine &machine, unsigned int ii=0)
virtual ~SimpleResourceManager ()
void clear ()
Clears all bookkeeping done by this RM. The RM can then be reused for different BB.
void buildResourceModel (const TTAMachine::Machine &machine)
Private Attributes
SimpleBrokerDirector * director_
Resource manager's broker director.
AssignmentPlan plan_
Resource assignment plan.
ResourceBuildDirector buildDirector_
Resource build director.
unsigned int initiationInterval_
unsigned int maxCycle_
unsigned int resources
Static Private Attributes
static std::map< const TTAMachine::Machine *, std::map< int, std::list< SimpleResourceManager * > > > rmPool_
Detailed Description
A simple resource manager.
Definition at line 58 of file SimpleResourceManager.hh.
Constructor & Destructor Documentation
SimpleResourceManager()
SimpleResourceManager::SimpleResourceManager (const TTAMachine::Machine & machine, unsigned int ii = 0) private
Constructor.
Parameters
machine Target machine, ii Initiation interval.
Definition at line 58 of file SimpleResourceManager.cc.
                                                      :
    ResourceManager(machine), director_(NULL),  initiationInterval_(ii),
    maxCycle_(INT_MAX-1) {
    buildResourceModel(machine);
}
References buildResourceModel(), and ResourceManager::machine().
~SimpleResourceManager()
SimpleResourceManager::~SimpleResourceManager () private virtual
Destructor.
Definition at line 162 of file SimpleResourceManager.cc.
{
    delete director_;
}
References director_.
Member Function Documentation
assign()
void SimpleResourceManager::assign (int cycle, MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) override virtual
Assign all resources needed by a given node starting from given cycle, and place the node in that cycle.
The manager keeps any pre-existing assignment and verifies that assigned resource is available. For all unassigned parts of the node, the resource manager looks for and then assigns the necessary resources. If the node is not fully assigned after the invocation of this operation, it means the assignment attempt failed.
Parameters
cycle Cycle.
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Exceptions
InvalidData exception if given node is already placed in a cycle different from given cycle.
Implements ResourceManager.
Definition at line 221 of file SimpleResourceManager.cc.
{
#ifdef DEBUG_RM
    Application::logStream() << "\tAssign: " << cycle << " " <<
        node.toString() << std::endl;
#endif
    director_->assign(
    cycle, node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
#ifdef DEBUG_RM
    Application::logStream() << "\tAssign: " << cycle << " " <<
        node.toString() << " OK!" << std::endl;
#endif
}
References SimpleBrokerDirector::assign(), director_, Application::logStream(), and MoveNode::toString().
Referenced by BFOptimization::assign(), BFOptimization::assignCopyToPrologEpilog(), BFOptimization::canAssign(), BFDRELoop::operator()(), BFSchedulePreLoopShared::operator()(), BFAssignToBody::operator()(), BFPostpassLoopDRE::operator()(), BFUnscheduleFromBody::returnOriginal(), BFOptimization::rmEC(), BFOptimization::rmLC(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), and BasicBlockScheduler::tryToDelayOperands().
buildResourceModel()
void SimpleResourceManager::buildResourceModel (const TTAMachine::Machine & machine) private
Creates brokers and builds resource model.
Definition at line 111 of file SimpleResourceManager.cc.
{
    // instantiate brokers
    std::vector<ResourceBroker*> brokers;
    InputFUBroker* ifb =
        new InputFUBroker("InputFUBroker", initiationInterval_);
    OutputFUBroker* ofb =
        new OutputFUBroker("OutputFUBroker", initiationInterval_);
    brokers.push_back(ifb);
    brokers.push_back(ofb);
    brokers.push_back(new ExecutionPipelineBroker(
                          "ExecutionPipelineBroker", initiationInterval_));
    InputPSocketBroker* ipsb = new InputPSocketBroker(
        "InputPSocketBroker", *ifb, initiationInterval_);
    brokers.push_back(ipsb);
    brokers.push_back(new IUBroker("IUBroker", this, initiationInterval_));
    OutputPSocketBroker* opsb = new OutputPSocketBroker(
        "OutputPSocketBroker", *ofb, this, initiationInterval_);
    brokers.push_back(opsb);
    BusBroker* bb = new BusBroker(
        "BusBroker", *ipsb, *opsb, machine,
        initiationInterval_);
    brokers.push_back(bb);
    brokers.push_back(
        new ITemplateBroker(
            "ITemplateBroker", *bb, this, initiationInterval_));
    ipsb->setBusBroker(*bb);
    opsb->setBusBroker(*bb);
    // build resource model and assignment plan
    for (unsigned int i = 0; i < brokers.size(); i++) {
        brokers[i]->setInitiationInterval(initiationInterval_);
        buildDirector_.addBroker(*brokers[i]);
        plan_.insertBroker(*brokers[i]);
    }
    resources = brokers.size();
    buildDirector_.build(machine);
    director_ = new SimpleBrokerDirector(machine, plan_, initiationInterval_);
}
References ResourceBuildDirector::addBroker(), ResourceBuildDirector::build(), buildDirector_, director_, initiationInterval_, AssignmentPlan::insertBroker(), ResourceManager::machine(), plan_, resources, InputPSocketBroker::setBusBroker(), and OutputPSocketBroker::setBusBroker().
Referenced by SimpleResourceManager().
canAssign()
bool SimpleResourceManager::canAssign (int cycle, MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const override virtual
Return true if given node can be assigned without resource conflicts in given cycle.
For those parts of the node that have been already assigned to a resource, the manager simply keeps the assignment and verifies that the resource is available. For those parts that are not yet assigned, the resource manager looks for any compatible resource that could be assigned.
Parameters
cycle Cycle.
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Returns
True if given node can be assigned without resource conflicts in given cycle, false otherwise.
Implements ResourceManager.
Definition at line 186 of file SimpleResourceManager.cc.
{
#ifdef DEBUG_RM
    Application::logStream() << "\tCanAssign: " << cycle << " " <<
        node.toString() << std::endl;
#endif
    return director_->canAssign(
    cycle, node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
}
References SimpleBrokerDirector::canAssign(), director_, Application::logStream(), and MoveNode::toString().
Referenced by BFOptimization::canAssign(), BFOptimization::rmEC(), and BFOptimization::rmLC().
canTransportImmediate()
bool SimpleResourceManager::canTransportImmediate (const MoveNode & node, const TTAMachine::Bus * preassignedBus = NULL) const virtual
Tests if immediate of MoveNode can be transported by any of buses of present machine.
Parameters
node MoveNode that contains immediate that we test
bus if non-null, only check immediate from that bus
Returns
true if the immediate in node can be transported by some bus
Definition at line 411 of file SimpleResourceManager.cc.
{
    return director_->canTransportImmediate(node, preassignedBus);
}
References SimpleBrokerDirector::canTransportImmediate(), and director_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), OutputPSocketBroker::isAlreadyAssigned(), OutputPSocketBroker::isApplicable(), IUBroker::isApplicable(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), and BasicBlockScheduler::scheduleMove().
clear()
void SimpleResourceManager::clear () private
Clears all bookkeeping done by this RM. The RM can then be reused for different BB.
Clears a resource manager so that it can be reused for different BB.
After this call the state of the RM should be identical to a new RM.
Definition at line 619 of file SimpleResourceManager.cc.
{
    director_->clearOldResources();
    buildDirector_.clear();
    director_->clear();
    setDDG(NULL);
    setCFG(NULL);
    setBBN(NULL);
}
References buildDirector_, ResourceBuildDirector::clear(), SimpleBrokerDirector::clear(), SimpleBrokerDirector::clearOldResources(), director_, setBBN(), setCFG(), and setDDG().
Referenced by disposeRM(), and BF2Scheduler::scheduleDDG().
clearOldResources()
void SimpleResourceManager::clearOldResources () virtual
Clears bookkeeping which is needed for unassigning previously assigned moves. After this call these cannot be unassigned, but new moves which are assigned after this call can still be unassigned.
Definition at line 610 of file SimpleResourceManager.cc.
{
    director_->clearOldResources();
}
References SimpleBrokerDirector::clearOldResources(), and director_.
Referenced by BBSchedulerController::executeDDGPass().
createRM()
SimpleResourceManager * SimpleResourceManager::createRM (const TTAMachine::Machine & machine, unsigned int ii = 0) static
Factory method for creating resource managers.
Checks a RM pool if a recyclable RM is found for same machine with same II, if found gives that. If not found, creates a new RM.
Definition at line 73 of file SimpleResourceManager.cc.
{
    std::map<int, std::list< SimpleResourceManager*> >& pool =
        rmPool_[&machine];
    std::list<SimpleResourceManager*>& iipool = pool[ii];
    if (iipool.empty()) {
        return new SimpleResourceManager(machine,ii);
    } else {
        SimpleResourceManager* rm = iipool.back();
        iipool.pop_back();
        return rm;
    }
}
References ResourceManager::machine(), and rmPool_.
Referenced by BasicBlockPass::executeDDGPass(), BBSchedulerController::executeDDGPass(), and SequentialScheduler::handleBasicBlock().
disposeRM()
void SimpleResourceManager::disposeRM (SimpleResourceManager * rm, bool allowReuse = true) static
Definition at line 92 of file SimpleResourceManager.cc.
{
    if (rm == NULL) return;
    if (allowReuse) {
        std::map<int, std::list< SimpleResourceManager*> >& pool =
            rmPool_[&rm->machine()];
        pool[rm->initiationInterval()].push_back(rm);
        rm->clear();
    } else {
        delete rm;
        ExecutionPipelineResourceTable::finalize();
    }
}
References clear(), ExecutionPipelineResourceTable::finalize(), initiationInterval(), ResourceManager::machine(), and rmPool_.
Referenced by BasicBlockPass::executeDDGPass(), BBSchedulerController::executeDDGPass(), CopyingDelaySlotFiller::fillDelaySlots(), CopyingDelaySlotFiller::finishBB(), and SequentialScheduler::handleBasicBlock().
earliestCycle() [1/2]
int SimpleResourceManager::earliestCycle (int cycle, MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const override virtual
Return the earliest cycle starting from the given cycle in which required resources can be assigned to given node.
If the node is partially assigned, the manager keeps existing assignments. This means that a client can apply arbitrary constraints to resource allocation.
Parameters
cycle Cycle to start from.
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Returns
The earliest cycle starting from the given cycle in which required resources can be assigned to given node. Returns -1 if assignment is not possible.
Implements ResourceManager.
Definition at line 313 of file SimpleResourceManager.cc.
{
    int ec = director_->earliestCycle(
        cycle, node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
#ifdef DEBUG_RM
    Application::logStream() << "\tEC: " << cycle << " " << node.toString()
                             << std::endl;
    Application::logStream() << "\t\tEC result is: " << ec << std::endl;
#endif
    return ec;
}
References director_, SimpleBrokerDirector::earliestCycle(), Application::logStream(), and MoveNode::toString().
earliestCycle() [2/2]
int SimpleResourceManager::earliestCycle (MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const override virtual
Return the earliest cycle in the scope where all required resources can be assigned to the given node.
If the node is partially assigned, the manager keeps existing assignments. This means that a client can apply arbitrary constraints to resource allocation.
Parameters
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Returns
The earliest cycle in the scope where all required resources can be assigned to the given node. -1 if assignment is not possible
Implements ResourceManager.
Definition at line 278 of file SimpleResourceManager.cc.
{
    int ec =  director_->earliestCycle(
        node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
#ifdef DEBUG_RM
    Application::logStream() << "\tEC:" << node.toString() << std::endl;
    Application::logStream() << "\t\tEC result is: " << ec << std::endl;
#endif
    return ec;
}
References director_, SimpleBrokerDirector::earliestCycle(), Application::logStream(), and MoveNode::toString().
Referenced by BFOptimization::rmEC(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), and BasicBlockScheduler::scheduleOperandWrites().
hasGuard()
bool SimpleResourceManager::hasGuard (const MoveNode & node) const virtual
Tests if any of a buses of machine supports guard needed by a node. Should always return true! Otherwise, scheduler generated code for different machine.
Parameters
node MoveNode to test
Returns
true if any of buses supports guard needed by node, or if move is not conditional.
Definition at line 426 of file SimpleResourceManager.cc.
{
    return director_->hasGuard(node);
}
References director_, and SimpleBrokerDirector::hasGuard().
immediateValue()
std::shared_ptr< TTAProgram::TerminalImmediate > SimpleResourceManager::immediateValue (const MoveNode & node) virtual
Finds the original terminal with value of immediate.
Parameters
node node with immediate register source
Returns
terminal with immediate value
Definition at line 509 of file SimpleResourceManager.cc.
{
    return director_->immediateValue(node);
}
References director_, and SimpleBrokerDirector::immediateValue().
Referenced by ITemplateBroker::assign().
immediateWriteCycle()
int SimpleResourceManager::immediateWriteCycle (const MoveNode & node) const virtual
Finds cycle in which the immediate that is read by node is written.
Parameters
node with source immediate register
Returns
cycle in which immediate is written to register
Definition at line 520 of file SimpleResourceManager.cc.
{
    return director_->immediateWriteCycle(node);
}
References director_, and SimpleBrokerDirector::immediateWriteCycle().
Referenced by ITemplateBroker::assign(), BFShareOperandLate::operator()(), BFShareOperandWithScheduled::operator()(), BFUnscheduleFromBody::unscheduleOriginal(), and BFUnscheduleMove::unscheduleOriginal().
initiationInterval()
virtual unsigned SimpleResourceManager::initiationInterval () const inline virtual
Definition at line 135 of file SimpleResourceManager.hh.
{return initiationInterval_;}
References initiationInterval_.
Referenced by LoopPrologAndEpilogBuilder::addPrologFromRM(), LoopPrologAndEpilogBuilder::build(), BasicBlockPass::copyRMToBB(), disposeRM(), BUBasicBlockScheduler::findBypassDestinations(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BFSchedulePreLoopShared::operator()(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), BasicBlockScheduler::tryToSwitchInputs(), and BUBasicBlockScheduler::tryToSwitchInputs().
instruction()
TTAProgram::Instruction * SimpleResourceManager::instruction (int cycle) const override virtual
Returns instruction that holds a moves for given cycle and has correct template set.
The instruction ownedship stays in the resource manager until loseInstructionOwnership() is called.
Parameters
cycle Cycle for which to get instruction
Returns
the Instruction with moves and template assigned
Note
This method should be called when whole scope is scheduled
Implements ResourceManager.
Definition at line 442 of file SimpleResourceManager.cc.
{
    return director_->instruction(cycle);
}
References director_, and SimpleBrokerDirector::instruction().
Referenced by LoopPrologAndEpilogBuilder::addEpilogFromRM(), ResourceConstraintAnalyzer::analyzeMoveNode(), BFOptimization::assignCopyToPrologEpilog(), LoopPrologAndEpilogBuilder::build(), BasicBlockPass::copyRMToBB(), BasicBlockScheduler::handleRemovedResultMoves(), BFShareOperandsLate::operator()(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), and BFShareOperandLate::revert().
instructionIndex()
unsigned int SimpleResourceManager::instructionIndex (unsigned int cycle) const
Return the instruction index corresponding to cycle.
If modulo scheduling is not used (ie. initiation interval is 0), then index is equal to cycle.
Parameters
cycle Cycle to get instruction index.
Returns
Return the instruction index for cycle.
Definition at line 534 of file SimpleResourceManager.cc.
{
    if (initiationInterval_ != 0) {
        return cycle % initiationInterval_;
    } else {
        return cycle;
    }
}
References initiationInterval_.
Referenced by BFShareOperandsLate::operator()().
isTemplateAvailable()
bool SimpleResourceManager::isTemplateAvailable (int defCycle, std::shared_ptr< TTAProgram::Immediate > immediate) const virtual
Definition at line 543 of file SimpleResourceManager.cc.
{
    return director_->isTemplateAvailable(defCycle, immediate);
}
References director_, and SimpleBrokerDirector::isTemplateAvailable().
Referenced by IUBroker::allAvailableResources(), and IUBroker::assign().
largestCycle()
int SimpleResourceManager::largestCycle () const override virtual
Returns largest cycle known to be used by any of the resources.
Returns
Largest cycle resource manager assigned any resource to.
Implements ResourceManager.
Definition at line 463 of file SimpleResourceManager.cc.
{
#ifdef DEBUG_RM
    Application::logStream() << "\tLargestC." << std::endl;
    int lc = director_->largestCycle();
    Application::logStream() << "\tLargestC got: " << lc << std::endl;
    return lc;
#else
    return director_->largestCycle();
#endif
}
References director_, SimpleBrokerDirector::largestCycle(), and Application::logStream().
Referenced by LoopPrologAndEpilogBuilder::addEpilogFromRM(), BFOptimization::assignCopyToPrologEpilog(), BasicBlockPass::copyRMToBB(), BF2Scheduler::handleDDG(), BUBasicBlockScheduler::handleDDG(), DDGPass::handleDDG(), BasicBlockScheduler::handleDDG(), SequentialScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), and BasicBlockScheduler::scheduleOperation().
latestCycle() [1/2]
int SimpleResourceManager::latestCycle (int cycle, MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const override virtual
Return the latest cycle starting from the given cycle in which required resources can be assigned to given node.
If the node is partially assigned, the manager keeps existing assignments. This means that a client can apply arbitrary constraints to resource allocation.
Parameters
cycle Cycle to start from.
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Returns
The latest cycle starting from the given cycle in which required resources can be assigned to given node. -1 if assignment is not possible.
Implements ResourceManager.
Definition at line 384 of file SimpleResourceManager.cc.
{
    int lc = director_->latestCycle(
        cycle, node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
#ifdef DEBUG_RM
    Application::logStream() << "\tLC: " << cycle << " " << node.toString()
        << std::endl;
    Application::logStream() << "\t\tLC result is: " << lc << std::endl;
#endif
    return lc;
}
References director_, SimpleBrokerDirector::latestCycle(), Application::logStream(), and MoveNode::toString().
latestCycle() [2/2]
int SimpleResourceManager::latestCycle (MoveNode & node, const TTAMachine::Bus * bus = NULL, const TTAMachine::FunctionUnit * srcFU = NULL, const TTAMachine::FunctionUnit * dstFU = NULL, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const override virtual
Return the latest cycle in the scope where all required resources can be assigned to the given node.
If the node is partially assigned, the manager keeps existing assignments. This means that a client can apply arbitrary constraints to resource allocation.
Parameters
node Node.
bus if not null, bus that has to be used.
srcFU if not null, srcFu that has to be used.
dstFU if not null, dstFU that has to be used.
immWriteCycle if not -1 and src is imm, write cycle of limm.
Returns
The latest cycle in the scope where all required resources can be assigned to the given node. -1 if assignment is not possible. INT_MAX if there is no upper boundary for assignment.
Implements ResourceManager.
Definition at line 349 of file SimpleResourceManager.cc.
{
    int lc = director_->latestCycle(
        node, bus, srcFU, dstFU, immWriteCycle, immu, immRegIndex);
#ifdef DEBUG_RM
    Application::logStream() << "\tLC: " << node.toString() << std::endl;
    Application::logStream() << "\t\tLC result is: " << lc << std::endl;
#endif
    return lc;
}
References director_, SimpleBrokerDirector::latestCycle(), Application::logStream(), and MoveNode::toString().
Referenced by BFSchedulePreLoopShared::operator()(), BFRemoveGuardsFromSuccs::operator()(), BFOptimization::rmLC(), BUBasicBlockScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleOperandWrites(), and BasicBlockScheduler::tryToDelayOperands().
loseInstructionOwnership()
void SimpleResourceManager::loseInstructionOwnership (int cycle) virtual
Transfer the instruction ownership away from this object,
If this method is called, resource manager does not delete it's instructions when it it destroyed.
Definition at line 498 of file SimpleResourceManager.cc.
{
    director_->loseInstructionOwnership(cycle);
}
References director_, and SimpleBrokerDirector::loseInstructionOwnership().
Referenced by LoopPrologAndEpilogBuilder::addEpilogFromRM(), and BasicBlockPass::copyRMToBB().
maxCycle()
int SimpleResourceManager::maxCycle () inline
Definition at line 142 of file SimpleResourceManager.hh.
{ return maxCycle_; }
References maxCycle_.
Referenced by setMaxCycle().
print()
void SimpleResourceManager::print (std::ostream & target) const virtual
Print the contents of resource manager.
Parameters
stream target stream where to print
Definition at line 566 of file SimpleResourceManager.cc.
{
    if (initiationInterval_ == 0) {
        buildDirector_.print(target, 10);
    } else {
        buildDirector_.print(target, initiationInterval_);
    }
}
References buildDirector_, initiationInterval_, and ResourceBuildDirector::print().
resourceCount()
unsigned int SimpleResourceManager::resourceCount () const virtual
Return the total number of resources.
Returns
Return the total number of resources.
Definition at line 556 of file SimpleResourceManager.cc.
{
    return resources;
}
References resources.
setBBN()
void SimpleResourceManager::setBBN (const BasicBlockNode * bbn)
Definition at line 639 of file SimpleResourceManager.cc.
{
    director_->setBBN(bbn);
}
References director_, and SimpleBrokerDirector::setBBN().
Referenced by clear(), and BBSchedulerController::executeDDGPass().
setCFG()
void SimpleResourceManager::setCFG (const ControlFlowGraph * cfg)
Definition at line 634 of file SimpleResourceManager.cc.
{
    director_->setCFG(cfg);
}
References director_, and SimpleBrokerDirector::setCFG().
Referenced by clear(), and BBSchedulerController::executeDDGPass().
setDDG()
void SimpleResourceManager::setDDG (const DataDependenceGraph * ddg)
Definition at line 629 of file SimpleResourceManager.cc.
{
    director_->setDDG(ddg);
}
References director_, and SimpleBrokerDirector::setDDG().
Referenced by clear(), BBSchedulerController::executeDDGPass(), and BF2Scheduler::handleLoopDDG().
setMaxCycle()
void SimpleResourceManager::setMaxCycle (unsigned int maxCycle)
Definition at line 647 of file SimpleResourceManager.cc.
{
    director_->setMaxCycle(maxCycle);
    maxCycle_ = maxCycle;
}
References director_, maxCycle(), maxCycle_, and SimpleBrokerDirector::setMaxCycle().
Referenced by CopyingDelaySlotFiller::addResourceManager(), BUBasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), and BF2Scheduler::scheduleDDG().
smallestCycle()
int SimpleResourceManager::smallestCycle () const override virtual
Returns smallest cycle known to be used by any of the resources.
Returns
Smallest cycle resource manager assigned any resource to.
Implements ResourceManager.
Definition at line 480 of file SimpleResourceManager.cc.
{
#ifdef DEBUG_RM
    Application::logStream() << "\tSC." << std::endl;
    int sc = director_->smallestCycle();
    Application::logStream() << "\tSC got: " << sc << std::endl;
    return sc;
#else
    return director_->smallestCycle();
#endif
}
References director_, Application::logStream(), and SimpleBrokerDirector::smallestCycle().
Referenced by LoopPrologAndEpilogBuilder::addPrologFromRM(), BFOptimization::assignCopyToPrologEpilog(), LoopPrologAndEpilogBuilder::build(), CopyingDelaySlotFiller::collectMoves(), BasicBlockPass::copyRMToBB(), BasicBlockPass::executeDDGPass(), CopyingDelaySlotFiller::fillDelaySlots(), BF2Scheduler::handleDDG(), BUBasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BF2ScheduleFront::scheduleFrontFromMove(), BUBasicBlockScheduler::scheduleOperation(), and CopyingDelaySlotFiller::tryToFillSlots().
supportsExternalAssignments()
bool SimpleResourceManager::supportsExternalAssignments () const override virtual
Defines if Resource Manager implementation supports node with resources pre assigned by clients.
Returns
For SimpleResourceManager allways false.
Implements ResourceManager.
Definition at line 453 of file SimpleResourceManager.cc.
{
    return director_->supportsExternalAssignments();
}
References director_, and SimpleBrokerDirector::supportsExternalAssignments().
toString()
std::string SimpleResourceManager::toString () const virtual
Print the contents of resource manager.
Returns
Return string containing the resource table.
Definition at line 582 of file SimpleResourceManager.cc.
{
    std::stringstream temp;
    if (initiationInterval_ == 0) {
        buildDirector_.print(temp, 10);
    } else {
        buildDirector_.print(temp, initiationInterval_);
    }
    std::string target = "";
    std::string result = "";
    while (getline(temp, target)) {
        // read temp to target
        target += "\n";
        result += target;
    };
    return result;
}
References buildDirector_, initiationInterval_, and ResourceBuildDirector::print().
unassign()
void SimpleResourceManager::unassign (MoveNode & node) override virtual
Free all resource assignments of the given node.
If the node is only partially assigned, the resource manager ignores those parts of the node that are already unassigned.
Parameters
node Node to unassign.
Exceptions
InvalidData If the given node is not placed in any cycle. Assigned but not placed nodes are not considered by the resource manager.
Implements ResourceManager.
Definition at line 252 of file SimpleResourceManager.cc.
{
#ifdef DEBUG_RM
    Application::logStream() << "\tUnAssign: " << node.toString() << std::endl;
#endif
    director_->unassign(node);
}
References director_, Application::logStream(), MoveNode::toString(), and SimpleBrokerDirector::unassign().
Referenced by BFOptimization::canAssign(), BFOptimization::rmEC(), BFOptimization::rmLC(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::tryToDelayOperands(), BFOptimization::unassign(), BFOptimization::unassignCopyFromPrologEpilog(), CopyingDelaySlotFiller::unassignTempAssigns(), BFDRELoop::undoOnlyMe(), BFSchedulePreLoopShared::undoOnlyMe(), BFAssignToBody::undoOnlyMe(), BFPostpassLoopDRE::undoOnlyMe(), BasicBlockScheduler::unschedule(), SequentialScheduler::unschedule(), and BFUnscheduleFromBody::unscheduleOriginal().
Member Data Documentation
buildDirector_
ResourceBuildDirector SimpleResourceManager::buildDirector_ private
Resource build director.
Definition at line 160 of file SimpleResourceManager.hh.
Referenced by buildResourceModel(), clear(), print(), and toString().
director_
SimpleBrokerDirector* SimpleResourceManager::director_ private
Resource manager's broker director.
Definition at line 156 of file SimpleResourceManager.hh.
Referenced by assign(), buildResourceModel(), canAssign(), canTransportImmediate(), clear(), clearOldResources(), earliestCycle(), earliestCycle(), hasGuard(), immediateValue(), immediateWriteCycle(), instruction(), isTemplateAvailable(), largestCycle(), latestCycle(), latestCycle(), loseInstructionOwnership(), setBBN(), setCFG(), setDDG(), setMaxCycle(), smallestCycle(), supportsExternalAssignments(), unassign(), and ~SimpleResourceManager().
initiationInterval_
unsigned int SimpleResourceManager::initiationInterval_ private
Definition at line 162 of file SimpleResourceManager.hh.
Referenced by buildResourceModel(), initiationInterval(), instructionIndex(), print(), and toString().
maxCycle_
unsigned int SimpleResourceManager::maxCycle_ private
Definition at line 163 of file SimpleResourceManager.hh.
Referenced by maxCycle(), and setMaxCycle().
plan_
AssignmentPlan SimpleResourceManager::plan_ private
Resource assignment plan.
Definition at line 158 of file SimpleResourceManager.hh.
Referenced by buildResourceModel().
resources
unsigned int SimpleResourceManager::resources private
Definition at line 165 of file SimpleResourceManager.hh.
Referenced by buildResourceModel(), and resourceCount().
rmPool_
std::map< const TTAMachine::Machine *, std::map< int, std::list< SimpleResourceManager * > > > SimpleResourceManager::rmPool_ static private
Definition at line 169 of file SimpleResourceManager.hh.
Referenced by createRM(), and disposeRM().
The documentation for this class was generated from the following files:
SimpleResourceManager.hh
SimpleResourceManager.cc