OpenASIP: HDBEditorAboutCmd Class Reference
HDBEditorAboutCmd Class Reference
#include <HDBEditorAboutCmd.hh>
Public Member Functions
HDBEditorAboutCmd ()
virtual ~HDBEditorAboutCmd ()
virtual bool Do ()
virtual int id () const
virtual HDBEditorAboutCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for displaying HDBEditor about dialog.
Definition at line 42 of file HDBEditorAboutCmd.hh.
Constructor & Destructor Documentation
HDBEditorAboutCmd()
HDBEditorAboutCmd::HDBEditorAboutCmd ()
The Constructor.
Definition at line 41 of file HDBEditorAboutCmd.cc.
                                    :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ABOUT, NULL) {
}
Referenced by create().
~HDBEditorAboutCmd()
HDBEditorAboutCmd::~HDBEditorAboutCmd () virtual
The Destructor.
Definition at line 49 of file HDBEditorAboutCmd.cc.
{
}
Member Function Documentation
create()
HDBEditorAboutCmd * HDBEditorAboutCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 91 of file HDBEditorAboutCmd.cc.
{
    return new HDBEditorAboutCmd();
}
References HDBEditorAboutCmd().
Do()
bool HDBEditorAboutCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 57 of file HDBEditorAboutCmd.cc.
                      {
    assert(parentWindow() != NULL);
    HDBEditorAboutDialog dialog(parentWindow());
    dialog.ShowModal();
    return true;
}
References assert, and GUICommand::parentWindow().
icon()
std::string HDBEditorAboutCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 71 of file HDBEditorAboutCmd.cc.
{
    return "about.png";
}
id()
int HDBEditorAboutCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 80 of file HDBEditorAboutCmd.cc.
{
    return HDBEditorConstants::COMMAND_ABOUT;
}
References HDBEditorConstants::COMMAND_ABOUT.
isEnabled()
bool HDBEditorAboutCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 102 of file HDBEditorAboutCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
HDBEditorAboutCmd.hh
HDBEditorAboutCmd.cc