OpenASIP: DeleteComponentCmd Class Reference
DeleteComponentCmd Class Reference
#include <DeleteComponentCmd.hh>
Public Member Functions
DeleteComponentCmd ()
virtual bool Do ()
virtual int id () const
virtual DeleteComponentCmd * create () const
virtual std::string shortName () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for deleting components from the Machine.
Definition at line 43 of file DeleteComponentCmd.hh.
Constructor & Destructor Documentation
DeleteComponentCmd()
DeleteComponentCmd::DeleteComponentCmd ()
The Constructor.
Definition at line 48 of file DeleteComponentCmd.cc.
                                      :
    EditorCommand(ProDeConstants::CMD_NAME_DELETE_COMP) {
}
Referenced by create().
Member Function Documentation
create()
DeleteComponentCmd * DeleteComponentCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 116 of file DeleteComponentCmd.cc.
{
    return new DeleteComponentCmd();
}
References DeleteComponentCmd().
Do()
bool DeleteComponentCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 61 of file DeleteComponentCmd.cc.
                       {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    // send delete request to the selected EditPart
    Request* deleteRequest = new Request(Request::DELETE_REQUEST);
    EditPart* selected = dynamic_cast<MDFView*>(view())->selection();
    if (selected == NULL) {
    return false;
    }
    ComponentCommand* command = selected->performRequest(deleteRequest);
    // execute the returned command
    if (command == NULL) {
    return false;
    } else {
    Model* model = dynamic_cast<MDFDocument*>(
        wxGetApp().docManager()->GetCurrentDocument())->getModel();
    model->pushToStack();
        dynamic_cast<MDFView*>(view())->clearSelection();
        bool result = command->Do();
    if (result) {
        // Model was modified.
        model->notifyObservers();
    } else {
        // Command was cancelled.
        model->popFromStack();
    }
    return result;
    }
}
References assert, Request::DELETE_REQUEST, ComponentCommand::Do(), Model::notifyObservers(), GUICommand::parentWindow(), EditPart::performRequest(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string DeleteComponentCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 137 of file DeleteComponentCmd.cc.
{
    return ProDeConstants::CMD_ICON_DELETE_COMP;
}
References ProDeConstants::CMD_ICON_DELETE_COMP.
id()
int DeleteComponentCmd::id () const virtual
Returns command identifier of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 105 of file DeleteComponentCmd.cc.
{
    return ProDeConstants::COMMAND_DELETE_COMP;
}
References ProDeConstants::COMMAND_DELETE_COMP.
isEnabled()
bool DeleteComponentCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a block is selected, and the block can handle a delete request.
Returns
True, if a deletable block is selected.
Reimplemented from EditorCommand.
Definition at line 152 of file DeleteComponentCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    MDFView* mdfView = dynamic_cast<MDFView*>(manager->GetCurrentView());
    if (mdfView == NULL) {
    return false;
    }
    Request* deleteRequest = new Request(Request::DELETE_REQUEST);
    if (mdfView->selection() == NULL ||
        !mdfView->selection()->canHandle(deleteRequest)) {
    return false;
    }
    delete deleteRequest;
    return true;
}
References EditPart::canHandle(), Request::DELETE_REQUEST, and MDFView::selection().
shortName()
string DeleteComponentCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 127 of file DeleteComponentCmd.cc.
{
    return ProDeConstants::CMD_SNAME_DELETE_COMP;
}
References ProDeConstants::CMD_SNAME_DELETE_COMP.
The documentation for this class was generated from the following files:
DeleteComponentCmd.hh
DeleteComponentCmd.cc