OpenASIP: ResourceManager Class Reference
ResourceManager Class Reference abstract
#include <ResourceManager.hh>
Public Member Functions
ResourceManager (const TTAMachine::Machine &machine)
virtual ~ResourceManager ()
virtual bool canAssign (int cycle, MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const =0
virtual void assign (int cycle, MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)=0
virtual void unassign (MoveNode &node)=0
virtual int earliestCycle (MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const =0
virtual int earliestCycle (int cycle, MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const =0
virtual int latestCycle (MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const =0
virtual int latestCycle (int cycle, MoveNode &node, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, int immWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1) const =0
virtual bool supportsExternalAssignments () const =0
virtual int largestCycle () const =0
virtual int smallestCycle () const =0
const TTAMachine::Machine & machine () const
virtual TTAProgram::Instruction * instruction (int cycle) const =0
Private Attributes
const TTAMachine::Machine * machine_
Target machine.
Detailed Description
Base interface for resource managers.
Definition at line 53 of file ResourceManager.hh.
Constructor & Destructor Documentation
ResourceManager()
ResourceManager::ResourceManager (const TTAMachine::Machine & machine)
Constructor.
Parameters
machine Target machine to be managed by the resource manager.
Definition at line 40 of file ResourceManager.cc.
                                                                :
    machine_(&machine) {
}
~ResourceManager()
ResourceManager::~ResourceManager () virtual
Destructor.
Definition at line 47 of file ResourceManager.cc.
{
}
Member Function Documentation
assign()
virtual void ResourceManager::assign (int cycle, MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
Referenced by CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), CycleLookBackSoftwareBypasser::removeBypass(), CopyingDelaySlotFiller::tryToAssignNodes(), and CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp().
canAssign()
virtual bool ResourceManager::canAssign (int cycle, MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
Referenced by CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), CycleLookBackSoftwareBypasser::removeBypass(), CopyingDelaySlotFiller::tryToAssignNodes(), and CopyingDelaySlotFiller::tryToAssignOtherMovesOfOp().
earliestCycle() [1/2]
virtual int ResourceManager::earliestCycle (int cycle, MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
earliestCycle() [2/2]
virtual int ResourceManager::earliestCycle (MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
Referenced by CycleLookBackSoftwareBypasser::bypass(), and CycleLookBackSoftwareBypasser::bypassNode().
instruction()
virtual TTAProgram::Instruction * ResourceManager::instruction (int cycle) const pure virtual
Implemented in SimpleBrokerDirector, and SimpleResourceManager.
Referenced by CopyingDelaySlotFiller::tryToAssignNodes().
largestCycle()
virtual int ResourceManager::largestCycle () const pure virtual
Implemented in SimpleBrokerDirector, and SimpleResourceManager.
latestCycle() [1/2]
virtual int ResourceManager::latestCycle (int cycle, MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
latestCycle() [2/2]
virtual int ResourceManager::latestCycle (MoveNode & node, const TTAMachine::Bus * bus = nullptr, const TTAMachine::FunctionUnit * srcFU = nullptr, const TTAMachine::FunctionUnit * dstFU = nullptr, int immWriteCycle = -1, const TTAMachine::ImmediateUnit * immu = nullptr, int immRegIndex = -1) const pure virtual
Implemented in SimpleResourceManager, and SimpleBrokerDirector.
machine()
const TTAMachine::Machine & ResourceManager::machine () const
Return the target machine managed by the resource manager.
Returns
The target machine managed by the resource manager.
Definition at line 56 of file ResourceManager.cc.
{
    return *machine_;
}
References machine_.
Referenced by LoopPrologAndEpilogBuilder::addPrologFromRM(), SimpleResourceManager::buildResourceModel(), SoftwareBypasser::bypass(), SimpleResourceManager::createRM(), SimpleResourceManager::disposeRM(), ITemplateBroker::findITemplates(), SoftwareBypasser::removeBypass(), SoftwareBypasser::removeDeadResults(), and SimpleResourceManager::SimpleResourceManager().
smallestCycle()
virtual int ResourceManager::smallestCycle () const pure virtual
Implemented in SimpleBrokerDirector, and SimpleResourceManager.
supportsExternalAssignments()
virtual bool ResourceManager::supportsExternalAssignments () const pure virtual
Implemented in SimpleBrokerDirector, and SimpleResourceManager.
unassign()
virtual void ResourceManager::unassign (MoveNode & node) pure virtual
Implemented in SimpleBrokerDirector, and SimpleResourceManager.
Referenced by CycleLookBackSoftwareBypasser::bypass(), CycleLookBackSoftwareBypasser::bypassNode(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), and CopyingDelaySlotFiller::tryToAssignNodes().
Member Data Documentation
machine_
const TTAMachine::Machine* ResourceManager::machine_ private
Target machine.
Definition at line 114 of file ResourceManager.hh.
Referenced by machine().
The documentation for this class was generated from the following files:
ResourceManager.hh
ResourceManager.cc