OpenASIP: BusState Class Reference
BusState Class Reference
#include <BusState.hh>
Public Member Functions
BusState (int width)
virtual ~BusState ()
virtual void setValue (const SimValue &value)
void setValueInlined (const SimValue &value)
void clear ()
void setSquashed (bool isSquashed)
bool isSquashed () const
int width () const
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
virtual const SimValue & value () const
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Private Member Functions
BusState (const BusState &)
Copying not allowed.
BusState & operator= (const BusState &)
Assignment not allowed.
Private Attributes
std::string name_
Name of the bus.
int width_
Width of the bus.
bool squashed_
True in case this bus was squashed the last time a move was executed in this bus.
Additional Inherited Members
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Models the state of the bus.
Definition at line 48 of file BusState.hh.
Constructor & Destructor Documentation
BusState() [1/2]
BusState::BusState (int width)
Constructor.
Parameters
width Bit width of the bus.
Definition at line 50 of file BusState.cc.
                            :
    RegisterState(width), squashed_(false) {
}
~BusState()
BusState::~BusState () virtual
Destructor.
Definition at line 57 of file BusState.cc.
                    {
}
BusState() [2/2]
BusState::BusState (const BusState &) private
Copying not allowed.
Member Function Documentation
clear()
void BusState::clear ()
isSquashed()
bool BusState::isSquashed () const
Returns true if the last executed move scheduled to this bus was squashed.
Parameters
isSquashed True in case this bus was squashed.
Definition at line 88 of file BusState.cc.
{
    return squashed_;
}
References squashed_.
Referenced by BusTracker::handleEvent(), and setSquashed().
operator=()
BusState & BusState::operator= (const BusState &) private
Assignment not allowed.
setSquashed()
void BusState::setSquashed (bool isSquashed)
Sets whether the last executed move scheduled to this bus was squashed.
Parameters
isSquashed True in case this bus was squashed.
Definition at line 78 of file BusState.cc.
{
    squashed_ = isSquashed;
}
References isSquashed(), and squashed_.
Referenced by ExecutableMove::evaluateGuard().
setValue()
void BusState::setValue (const SimValue & value) virtual
Sets the value of the bus.
Does not extend the value.
Parameters
value New value.
Reimplemented from RegisterState.
Reimplemented in NullBusState.
Definition at line 68 of file BusState.cc.
{
    RegisterState::setValue(value);
}
References RegisterState::setValue(), and RegisterState::value().
setValueInlined()
void BusState::setValueInlined (const SimValue & value)
Referenced by ExecutableMove::executeRead().
width()
int BusState::width () const
Returns width of the modeled bus.
Definition at line 96 of file BusState.cc.
                      {
    return value().width();
}
References RegisterState::value(), and SimValue::width().
Referenced by BusTracker::handleEvent().
Member Data Documentation
name_
std::string BusState::name_ private
Name of the bus.
Definition at line 70 of file BusState.hh.
squashed_
bool BusState::squashed_ private
True in case this bus was squashed the last time a move was executed in this bus.
Definition at line 75 of file BusState.hh.
Referenced by isSquashed(), and setSquashed().
width_
int BusState::width_ private
Width of the bus.
Definition at line 72 of file BusState.hh.
The documentation for this class was generated from the following files:
BusState.hh
BusState.cc