OpenASIP: OSEdMainFrame Class Reference
OSEdMainFrame Class Reference
#include <OSEdMainFrame.hh>
Public Member Functions
OSEdMainFrame (const wxString &title, const wxPoint &pos, const wxSize &size)
virtual ~OSEdMainFrame ()
OSEdTreeView * treeView () const
CommandRegistry * registry () const
OSEdInformer * informer () const
wxStatusBar * statusBar () const
void updateMenuBar ()
void onCommandEvent (wxCommandEvent &event)
Private Member Functions
OSEdMainFrame (const OSEdMainFrame &)
Copying not allowed.
OSEdMainFrame & operator= (const OSEdMainFrame &)
Assignment not allowed.
Private Attributes
CommandRegistry * registry_
Command registry.
OSEdTreeView * treeView_
Tree view.
OSEdInformer * informer_
Informs listener classes for events that occurs.
wxStatusBar * statusBar_
Status bar of the main window.
Detailed Description
Main window of the application.
Contains a splitted window for showing data and a menu bar for executing actions.
Definition at line 49 of file OSEdMainFrame.hh.
Constructor & Destructor Documentation
OSEdMainFrame() [1/2]
OSEdMainFrame::OSEdMainFrame (const wxString & title, const wxPoint & pos, const wxSize & size)
Constructor.
Parameters
title Window title.
pos Window position.
size Window size.
Definition at line 82 of file OSEdMainFrame.cc.
                        : wxFrame((wxFrame *)NULL, -1, title, pos, size),
                          registry_(NULL), treeView_(NULL), informer_(NULL) {
    wxImage::AddHandler(new wxPNGHandler);
    // set logo
    string logoPath =
        Environment::bitmapsDirPath(
            WxConversion::toString(OSEdConstants::APPLICATION_NAME));
    logoPath += FileSystem::DIRECTORY_SEPARATOR +
        OSEdConstants::LOGO_NAME;
    wxBitmap bmp;
    bmp.LoadFile(WxConversion::toWxString(logoPath), wxBITMAP_TYPE_PNG);
    wxIcon logo;
    logo.CopyFromBitmap(bmp);
    SetIcon(logo);
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    // create default menu bar
    wxMenu* menu = new wxMenu;
    format fmt = texts.text(OSEdTextGenerator::TXT_MENU_OPTIONS);
    menu->Append(
        OSEdConstants::CMD_OPTIONS, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_QUIT);
    menu->Append(OSEdConstants::CMD_QUIT, WxConversion::toWxString(fmt.str()));
    wxMenuBar* menuBar = new wxMenuBar;
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_FILE);
    menuBar->Append(menu, WxConversion::toWxString(fmt.str()));
    menu = new wxMenu;
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_ADD_OPERATION);
    menu->Append(
        OSEdConstants::CMD_ADD_OPERATION, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_REMOVE_OPERATION);
    menu->Append(
        OSEdConstants::CMD_REMOVE_OPERATION,
        WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_ADD_MODULE);
    menu->Append(
        OSEdConstants::CMD_ADD_MODULE, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_REMOVE_MODULE);
    menu->Append(
        OSEdConstants::CMD_REMOVE_MODULE, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_MODIFY_PROPERTIES);
    menu->Append(
        OSEdConstants::CMD_PROPERTIES, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_MODIFY_BEHAVIOR);
    menu->Append(
        OSEdConstants::CMD_MODIFY_BEHAVIOR,
        WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_BUILD);
    menu->Append(
        OSEdConstants::CMD_BUILD, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_BUILD_ALL);
    menu->Append(
        OSEdConstants::CMD_BUILD_ALL, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_SIMULATE);
    menu->Append(
        OSEdConstants::CMD_SIMULATE, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_MEMORY);
    menu->Append(
        OSEdConstants::CMD_MEMORY, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_TOOLS);
    menuBar->Append(menu, WxConversion::toWxString(fmt.str()));
    menu = new wxMenu;
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_USER_MANUAL);
    menu->Append(
        UserManualCmd::COMMAND_ID, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_ABOUT);
    menu->Append(
        OSEdConstants::CMD_ABOUT, WxConversion::toWxString(fmt.str()));
    fmt = texts.text(OSEdTextGenerator::TXT_MENU_HELP);
    menuBar->Append(menu, WxConversion::toWxString(fmt.str()));
    SetMenuBar(menuBar);
    statusBar_ = CreateStatusBar();
    // add all custom commands to command registry
    registry_ = new CommandRegistry();
    registry_->addCommand(new OSEdQuitCmd());
    registry_->addCommand(new OSEdAboutCmd());
    registry_->addCommand(new OSEdPropertiesCmd());
    registry_->addCommand(new OSEdAddModuleCmd());
    registry_->addCommand(new OSEdAddOperationCmd());
    registry_->addCommand(new OSEdSimulateCmd());
    registry_->addCommand(new OSEdOptionsCmd());
    registry_->addCommand(new OSEdBuildCmd());
    registry_->addCommand(new OSEdBuildAllCmd());
    registry_->addCommand(new UserManualCmd());
    registry_->addCommand(new OSEdRemoveModuleCmd());
    registry_->addCommand(new OSEdModifyBehaviorCmd());
    registry_->addCommand(new OSEdRemoveOperationCmd());
    registry_->addCommand(new OSEdMemoryCmd());
    // create splitted window
    wxSplitterWindow* splitter = new wxSplitterWindow(
        this, -1, wxPoint(0, 0), wxSize(900, 500), wxSP_3D);
    OSEdInfoView* infoView = new OSEdInfoView(splitter);
    treeView_ = new OSEdTreeView(splitter, infoView);
    splitter->SplitVertically(treeView_, infoView);
    informer_ = new OSEdInformer();
}
References OSEdConstants::APPLICATION_NAME, Environment::bitmapsDirPath(), OSEdConstants::CMD_ABOUT, OSEdConstants::CMD_ADD_MODULE, OSEdConstants::CMD_ADD_OPERATION, OSEdConstants::CMD_BUILD, OSEdConstants::CMD_BUILD_ALL, OSEdConstants::CMD_MEMORY, OSEdConstants::CMD_MODIFY_BEHAVIOR, OSEdConstants::CMD_OPTIONS, OSEdConstants::CMD_PROPERTIES, OSEdConstants::CMD_QUIT, OSEdConstants::CMD_REMOVE_MODULE, OSEdConstants::CMD_REMOVE_OPERATION, OSEdConstants::CMD_SIMULATE, UserManualCmd::COMMAND_ID, FileSystem::DIRECTORY_SEPARATOR, OSEdTextGenerator::instance(), OSEdConstants::LOGO_NAME, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), OSEdTextGenerator::TXT_MENU_ABOUT, OSEdTextGenerator::TXT_MENU_ADD_MODULE, OSEdTextGenerator::TXT_MENU_ADD_OPERATION, OSEdTextGenerator::TXT_MENU_BUILD, OSEdTextGenerator::TXT_MENU_BUILD_ALL, OSEdTextGenerator::TXT_MENU_FILE, OSEdTextGenerator::TXT_MENU_HELP, OSEdTextGenerator::TXT_MENU_MEMORY, OSEdTextGenerator::TXT_MENU_MODIFY_BEHAVIOR, OSEdTextGenerator::TXT_MENU_MODIFY_PROPERTIES, OSEdTextGenerator::TXT_MENU_OPTIONS, OSEdTextGenerator::TXT_MENU_QUIT, OSEdTextGenerator::TXT_MENU_REMOVE_MODULE, OSEdTextGenerator::TXT_MENU_REMOVE_OPERATION, OSEdTextGenerator::TXT_MENU_SIMULATE, OSEdTextGenerator::TXT_MENU_TOOLS, and OSEdTextGenerator::TXT_MENU_USER_MANUAL.
~OSEdMainFrame()
OSEdMainFrame::~OSEdMainFrame () virtual
Destructor.
Definition at line 208 of file OSEdMainFrame.cc.
{
    delete registry_;
    registry_ = NULL;
    delete informer_;
    informer_ = NULL;
}
References informer_, and registry_.
OSEdMainFrame() [2/2]
OSEdMainFrame::OSEdMainFrame (const OSEdMainFrame &) private
Copying not allowed.
Member Function Documentation
informer()
OSEdInformer * OSEdMainFrame::informer () const
Returns informer instance.
Returns
The informer instance.
Definition at line 261 of file OSEdMainFrame.cc.
{
    return informer_;
}
References informer_.
onCommandEvent()
void OSEdMainFrame::onCommandEvent (wxCommandEvent & event)
Handles menu events.
Parameters
event Event to be handled.
Definition at line 221 of file OSEdMainFrame.cc.
{
    GUICommand* command = registry_->createCommand(event.GetId());
    if (command == NULL) {
        OSEdTextGenerator& texts = OSEdTextGenerator::instance();
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_HANDLER);
        ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
        dialog.ShowModal();
        return;
    }
    command->setParentWindow(this);
    command->Do();
    delete command;
}
References CommandRegistry::createCommand(), GUICommand::Do(), OSEdTextGenerator::instance(), registry_, GUICommand::setParentWindow(), Texts::TextGenerator::text(), WxConversion::toWxString(), and OSEdTextGenerator::TXT_ERROR_NO_HANDLER.
operator=()
OSEdMainFrame & OSEdMainFrame::operator= (const OSEdMainFrame &) private
Assignment not allowed.
registry()
CommandRegistry * OSEdMainFrame::registry () const
Returns the command registry.
Returns
the command registry.
Definition at line 251 of file OSEdMainFrame.cc.
{
    return registry_;
}
References registry_.
Referenced by OSEdTreeView::onItemClicked().
statusBar()
wxStatusBar * OSEdMainFrame::statusBar () const
Returns status bar of the frame.
Returns
Status bar.
Definition at line 271 of file OSEdMainFrame.cc.
{
    return statusBar_;
}
References statusBar_.
Referenced by OSEdInfoView::onDropDownMenu(), OSEdTreeView::onDropDownMenu(), OSEdTreeView::onItemSelected(), and OSEdInfoView::onSelection().
treeView()
OSEdTreeView * OSEdMainFrame::treeView () const
Returns pointer to the tree view.
Returns
Pointer to the tree view.
Definition at line 241 of file OSEdMainFrame.cc.
{
    return treeView_;
}
References treeView_.
Referenced by OSEdAddModuleCmd::Do(), OSEdAddOperationCmd::Do(), OSEdPropertiesCmd::Do(), OSEdSimulateCmd::Do(), OSEdBuildCmd::isEnabled(), and OSEd::OnInit().
updateMenuBar()
void OSEdMainFrame::updateMenuBar ()
Updates the menu bar disabled/enabled states.
Definition at line 279 of file OSEdMainFrame.cc.
{
    wxMenuBar* menubar = GetMenuBar();
    GUICommand* command = registry_->firstCommand();
    while (command != NULL) {
        if (menubar->FindItem(command->id()) != NULL) {
            if (command->isEnabled()) {
                menubar->Enable(command->id(), true);
            } else {
                menubar->Enable(command->id(), false);
            }
        }
        command = registry_->nextCommand();
    }
}
References CommandRegistry::firstCommand(), GUICommand::id(), GUICommand::isEnabled(), CommandRegistry::nextCommand(), and registry_.
Referenced by OSEd::OnInit(), and OSEdInfoView::onSelection().
Member Data Documentation
informer_
OSEdInformer* OSEdMainFrame::informer_ private
Informs listener classes for events that occurs.
Definition at line 77 of file OSEdMainFrame.hh.
Referenced by informer(), and ~OSEdMainFrame().
registry_
CommandRegistry* OSEdMainFrame::registry_ private
Command registry.
Definition at line 73 of file OSEdMainFrame.hh.
Referenced by onCommandEvent(), registry(), updateMenuBar(), and ~OSEdMainFrame().
statusBar_
wxStatusBar* OSEdMainFrame::statusBar_ private
Status bar of the main window.
Definition at line 79 of file OSEdMainFrame.hh.
Referenced by statusBar().
treeView_
OSEdTreeView* OSEdMainFrame::treeView_ private
Tree view.
Definition at line 75 of file OSEdMainFrame.hh.
Referenced by treeView().
The documentation for this class was generated from the following files:
OSEdMainFrame.hh
OSEdMainFrame.cc