OpenASIP: TTAProgram::Label Class Reference
TTAProgram::Label Class Reference
#include <Label.hh>
Public Member Functions
virtual ~Label ()
std::string name () const
virtual Address address () const
const Scope & scope () const
void setAddress (Address address)
Protected Member Functions
Label ()
Label (const std::string &name, Address address, const Scope &scope)
void setName (const std::string &name)
void setScope (const Scope &scope)
Private Attributes
std::string name_
Name of the label.
Address address_
Address of the location corresponding to this label.
const Scope * scope_
Owning scope of the label.
Detailed Description
Marks locations of code or data area of the program.
Labels are owned by scopes. Scopes do not provide methods to add new labels, because the labels are automatically registered to a scope by their constructor: a label cannot exist without its scope.
A label must have a unique name within the owning scope. It does not matter if there are other labels with the same name in outer scopes, because the inner scope has precedence. As a result, all labels in global scope must have a unique name.
Definition at line 55 of file Label.hh.
Constructor & Destructor Documentation
~Label()
TTAProgram::Label::~Label () virtual
The destructor.
Definition at line 65 of file Label.cc.
              {
}
Label() [1/2]
TTAProgram::Label::Label () protected
Definition at line 46 of file Label.cc.
            : address_(Address(0, NullAddressSpace::instance())) {
}
Label() [2/2]
TTAProgram::Label::Label (const std::string & name, Address address, const Scope & scope) protected
The constructor.
Registers this label to the owning scope.
Parameters
name Name of the label. Must be unique within the owning scope.
address The address of the location corresponding to this label.
scope The innermost scope that contains this label.
Definition at line 58 of file Label.cc.
                                                                      :
    name_(name), address_(address), scope_(&scope) {
}
Member Function Documentation
address()
Address TTAProgram::Label::address () const virtual
Returns the address of the location corresponding to this label.
Returns
The address of the location corresponding to this label.
Reimplemented in TTAProgram::CodeLabel.
Definition at line 84 of file Label.cc.
                     {
    return address_;
}
References address_.
Referenced by TTAProgram::Program::convertSymbolRef(), TTAProgram::GlobalScope::copyAndRelocate(), TTAProgram::ProgramWriter::createBinary(), SymbolAddressCommand::execute(), SimControlLanguageCommand::parseDataAddressExpression(), setAddress(), and TTAProgram::GlobalScope::setDataLabelAddressSpace().
name()
string TTAProgram::Label::name () const
Returns the name of this label.
Returns
The name of this label.
Definition at line 74 of file Label.cc.
                  {
    return name_;
}
References name_.
Referenced by TTAProgram::Scope::addCodeLabel(), TTAProgram::Scope::addDataLabel(), TTAProgram::CodeLabel::CodeLabel(), TTAProgram::Program::convertSymbolRef(), TTAProgram::GlobalScope::copyAndRelocate(), TTAProgram::ProgramWriter::createBinary(), POMDisassembler::label(), DisassemblyGridTable::loadProgram(), TTAProgram::GlobalScope::setDataLabelAddressSpace(), and setName().
scope()
const Scope & TTAProgram::Label::scope () const
Returns the innermost scope that contains this label.
Returns
The innermost scope that contains this label.
Definition at line 94 of file Label.cc.
                   {
    return *scope_;
}
References scope_.
Referenced by setScope().
setAddress()
void TTAProgram::Label::setAddress (Address address)
Sets the address of the location corresponding to this label.
Definition at line 110 of file Label.cc.
{
    address_ = address;
}
References address(), and address_.
Referenced by TTAProgram::CodeLabel::CodeLabel(), and TTAProgram::CodeLabel::CodeLabel().
setName()
void TTAProgram::Label::setName (const std::string & name) protected
Sets the name of this label.
Definition at line 102 of file Label.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by TTAProgram::CodeLabel::CodeLabel(), and TTAProgram::CodeLabel::CodeLabel().
setScope()
void TTAProgram::Label::setScope (const Scope & scope) protected
Sets the innermost scope that contains this label.
Definition at line 118 of file Label.cc.
{
    scope_ = &scope;
}
References scope(), and scope_.
Referenced by TTAProgram::CodeLabel::CodeLabel(), and TTAProgram::CodeLabel::CodeLabel().
Member Data Documentation
address_
Address TTAProgram::Label::address_ private
Address of the location corresponding to this label.
Definition at line 75 of file Label.hh.
Referenced by address(), and setAddress().
name_
std::string TTAProgram::Label::name_ private
Name of the label.
Definition at line 73 of file Label.hh.
Referenced by name(), and setName().
scope_
const Scope* TTAProgram::Label::scope_ private
Owning scope of the label.
Definition at line 77 of file Label.hh.
Referenced by scope(), and setScope().
The documentation for this class was generated from the following files:
Label.hh
Label.cc