OpenASIP: AddressSpaceCheck Class Reference
AddressSpaceCheck Class Reference
#include <AddressSpaceCheck.hh>
Public Member Functions
AddressSpaceCheck (OperationPool &operationPool)
virtual ~AddressSpaceCheck ()
virtual bool check (const TTAMachine::Machine &mach, MachineCheckResults &results) const
Public Member Functions inherited from MachineCheck
virtual std::string shortDescription () const
virtual std::string description () const
virtual bool canFix (const TTAMachine::Machine &mach) const
virtual std::string fix (TTAMachine::Machine &mach) const
virtual ~MachineCheck ()
Private Attributes
OperationPool & operationPool_
Additional Inherited Members
Protected Member Functions inherited from MachineCheck
MachineCheck (const std::string &shortDesc_)
Detailed Description
MachineCheck to check if the FUs' operations access memory and there is a memory address space available for them.
Definition at line 50 of file AddressSpaceCheck.hh.
Constructor & Destructor Documentation
AddressSpaceCheck()
AddressSpaceCheck::AddressSpaceCheck (OperationPool & operationPool)
The constructor.
Parameters
operationPool operation pool to search the operations for
Definition at line 51 of file AddressSpaceCheck.cc.
                                                                 :
    MachineCheck("Address space check."),
    operationPool_(operationPool) {
}
~AddressSpaceCheck()
AddressSpaceCheck::~AddressSpaceCheck () virtual
The destructor.
Definition at line 59 of file AddressSpaceCheck.cc.
{
}
Member Function Documentation
check()
bool AddressSpaceCheck::check (const TTAMachine::Machine & mach, MachineCheckResults & results) const virtual
Checks that if the FUs' operations access memory, there is a memory address space available for them.
Parameters
mach Machine to be checked.
results Check results.
Returns
True if the check passed
Implements MachineCheck.
Definition at line 71 of file AddressSpaceCheck.cc.
{
    Machine::FunctionUnitNavigator FUs = mach.functionUnitNavigator();
    for (int i = 0; i < FUs.count(); i++) {
        FunctionUnit* unit = FUs.item(i);
        if (unit->addressSpace() != NULL) {
            continue;
        }
        for (int j = 0; j < unit->operationCount(); ++j) {
            Operation& op =
                operationPool_.operation(unit->operation(j)->name().c_str());
            // skip any Nulloperations because the check is done elsewhere
            if (&op == &NullOperation::instance()) {
                continue;
            }
            if (op.usesMemory() && unit->addressSpace() == NULL) {
                results.addError(*this,
                    std::string("operation ") + op.name() + " accesses memory" +
                    " but the memory address space was not set.");
                return false;
            }
        }
    } // end for all FUs
    return true;
}
References MachineCheckResults::addError(), TTAMachine::FunctionUnit::addressSpace(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), NullOperation::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::HWOperation::name(), Operation::name(), OperationPool::operation(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), operationPool_, and Operation::usesMemory().
Referenced by MachineStateBuilder::buildMachineState().
Member Data Documentation
operationPool_
OperationPool& AddressSpaceCheck::operationPool_ private
Definition at line 59 of file AddressSpaceCheck.hh.
Referenced by check().
The documentation for this class was generated from the following files:
AddressSpaceCheck.hh
AddressSpaceCheck.cc