OpenASIP: BFRemoveGuard Class Reference
BFRemoveGuard Class Reference
#include <BFRemoveGuard.hh>
Public Member Functions
BFRemoveGuard (BF2Scheduler &sched, MoveNode &mn)
bool operator() () override
void undoOnlyMe () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & mn_
TTAProgram::MoveGuard * guard_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 51 of file BFRemoveGuard.hh.
Constructor & Destructor Documentation
BFRemoveGuard()
BFRemoveGuard::BFRemoveGuard (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 53 of file BFRemoveGuard.hh.
                                           :
        BFOptimization(sched), mn_(mn) {}
Member Function Documentation
operator()()
bool BFRemoveGuard::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 42 of file BFRemoveGuard.cc.
{
    assert(!mn_.move().isUnconditional());
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tRemoving guard from move: "
              << mn_.toString() << std::endl;
#endif
    // remove the guard edges from the ddg
    auto inEdges = ddg().inEdges(mn_);
    for (auto e: inEdges) {
        if (e->guardUse() && !e->isFalseDep()) {
            runPreChild(new BFRemoveEdge(sched_, ddg().tailNode(*e), mn_,*e));
        }
    }
    auto outEdges = ddg().outEdges(mn_);
    for (auto e: outEdges) {
        if (e->guardUse() &&
            e->dependenceType() == DataDependenceEdge::DEP_WAR) {
            runPreChild(new BFRemoveEdge(sched_, mn_,ddg().headNode(*e), *e));
        }
    }
    guard_ = mn_.move().guard().copy();
    mn_.move().setGuard(NULL);
    return true;
}
References assert, TTAProgram::MoveGuard::copy(), BFOptimization::ddg(), DataDependenceEdge::DEP_WAR, TTAProgram::Move::guard(), guard_, BoostGraph< GraphNode, GraphEdge >::inEdges(), TTAProgram::Move::isUnconditional(), mn_, MoveNode::move(), BoostGraph< GraphNode, GraphEdge >::outEdges(), Reversible::runPreChild(), BFOptimization::sched_, TTAProgram::Move::setGuard(), and MoveNode::toString().
undoOnlyMe()
void BFRemoveGuard::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 69 of file BFRemoveGuard.cc.
{
    mn_.move().setGuard(guard_);
}
References guard_, mn_, MoveNode::move(), and TTAProgram::Move::setGuard().
Member Data Documentation
guard_
TTAProgram::MoveGuard* BFRemoveGuard::guard_ private
Definition at line 60 of file BFRemoveGuard.hh.
Referenced by operator()(), and undoOnlyMe().
mn_
MoveNode& BFRemoveGuard::mn_ private
Definition at line 59 of file BFRemoveGuard.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFRemoveGuard.hh
BFRemoveGuard.cc