OpenASIP: NullSimValue Class Reference
NullSimValue Class Reference
#include <SimValue.hh>
Static Public Member Functions
static SimValue & instance ()
Private Member Functions
NullSimValue ()
Static Private Attributes
static SimValue instance_
Detailed Description
Singleton class that is used to represent a null SimValue.
All methods cause program abort with an error log message.
Definition at line 237 of file SimValue.hh.
Constructor & Destructor Documentation
NullSimValue()
NullSimValue::NullSimValue () private
Member Function Documentation
instance()
SimValue & NullSimValue::instance () static
Returns an instance of NullSimValue class (singleton).
Returns
Singleton instance of NullSimValue class.
Definition at line 1642 of file SimValue.cc.
                       {
    return instance_;
}
References instance_.
Referenced by ExecutionTrace::addBusActivity(), MachineStateBuilder::addPortToFU(), MachineStateBuilder::addPortToFU(), POMDisassembler::createInlineImmediate(), FixedRegisters::floatArgumentRegister(), FixedRegisters::floatReturnValue(), FixedRegisters::integerArgumentRegister(), FixedRegisters::integerReturnValue(), NullLongImmediateUnitState::registerValue(), FixedRegisters::stackPointer(), SimulationInfoDialog::updateList(), NullBusState::value(), NullPortState::value(), NullRegisterState::value(), and TTAProgram::TerminalSymbolReference::value().
Member Data Documentation
instance_
SimValue NullSimValue::instance_ static private
Definition at line 244 of file SimValue.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
SimValue.hh
SimValue.cc