OpenASIP: MoveNodeGroup Class Reference
MoveNodeGroup Class Reference
#include <MoveNodeGroup.hh>
Public Member Functions
MoveNodeGroup ()
MoveNodeGroup (const DataDependenceGraph &ddg)
virtual ~MoveNodeGroup ()
void addNode (MoveNode &node)
int earliestCycle (bool assumeBypassing=false) const
int latestCycle () const
int maxSinkDistance () const
int maxSourceDistance () const
int nodeCount () const
MoveNode & node (int index) const
bool isPlaced () const
bool isScheduled () const
std::string toString () const
bool isAlive () const
void setProgramOperationPtr (ProgramOperationPtr op)
in case this MNG contains strictly the nodes of a single operation, it can be set and queried with these methods
bool isOperation () const
ProgramOperationPtr programOperationPtr () const
bool writesJumpGuard () const
Private Attributes
std::vector< MoveNode * > nodes_
const DataDependenceGraph * ddg_
The data dependence graph the moves in this group belong to (optional).
ProgramOperationPtr operation_
in case this MNG contains strictly the nodes of a single operation this can be set to point to it (optional)
Detailed Description
Class which contains group of moves which are to be scheduled.
Definition at line 48 of file MoveNodeGroup.hh.
Constructor & Destructor Documentation
MoveNodeGroup() [1/2]
MoveNodeGroup::MoveNodeGroup ()
Constructor.
Definition at line 45 of file MoveNodeGroup.cc.
                             : ddg_(NULL) {
}
MoveNodeGroup() [2/2]
MoveNodeGroup::MoveNodeGroup (const DataDependenceGraph & ddg)
Constructor.
Parameters
ddg The data dependence graph the moves in the group belong to.
Definition at line 53 of file MoveNodeGroup.cc.
                                                           :
    ddg_(&ddg) {
}
~MoveNodeGroup()
MoveNodeGroup::~MoveNodeGroup () virtual
Destructor.
Definition at line 61 of file MoveNodeGroup.cc.
{
}
Member Function Documentation
addNode()
void MoveNodeGroup::addNode (MoveNode & node)
Adds a node to the MoveNodeGroup.
Parameters
node The MoveNode being added to the group.
Definition at line 70 of file MoveNodeGroup.cc.
{
    nodes_.push_back(&node);
}
References node(), and nodes_.
Referenced by MoveNodeGroupBuilder::build(), BasicBlockScheduler::handleLoopDDG(), BUMoveNodeSelector::mightBeReady(), and CriticalPathBBMoveNodeSelector::mightBeReady().
earliestCycle()
int MoveNodeGroup::earliestCycle (bool assumeBypassing = false) const
Calculates the earliest cycle in which dependences make it possible to try schedule the leader node.
In case the MoveNodeGroup is not (known) to be part of a DDG, or at least one of the predecessors of the MoveNodeGroup are unscheduled, this function returns INT_MAX. If the node is a root node, the function returns 0.
Todo:
What is the "leader node", in general, in an unassigned operation?
Parameters
assumeBypassing If set to true, assume we can software bypass all inputs from the original source.
Returns
The earliest possible cycle all nodes could be scheduled according to their precedences.
Definition at line 103 of file MoveNodeGroup.cc.
{
    if (ddg_ == NULL)
        return INT_MAX;
    int cycle = 0;
    // check the predecessors of all nodes in the MoveNodeGroup
    for (std::size_t i = 0; i < nodes_.size(); ++i) {
        MoveNode& node = *nodes_.at(i);
        int nodeCycle =
            ddg_->earliestCycle(
                node, UINT_MAX, false, false, false, false, false,
                assumeBypassing);
        Application::logStream() << "EC " << nodeCycle << " for "
                                 << node.toString() << std::endl;
        // the result read moves have unscheduled predecessors in case
        // the operand moves are not yet scheduled, ignore that
        if (nodeCycle == INT_MAX) {
            if (!node.isSourceOperation()) {
                return INT_MAX;
            }
        } else {
            cycle = std::max(nodeCycle, cycle);
        }
    }
    return cycle;
}
References ddg_, DataDependenceGraph::earliestCycle(), MoveNode::isSourceOperation(), Application::logStream(), node(), nodes_, and MoveNode::toString().
isAlive()
bool MoveNodeGroup::isAlive () const
Returns true if all moves in the move group are alive.
An empty MoveNodeGroup is considered always alive.
Returns
True if scheduled.
Definition at line 190 of file MoveNodeGroup.cc.
{
    if (ddg_ != NULL) {
        for (std::size_t i = 0; i < nodes_.size(); ++i) {
            if (!ddg_->hasNode(*nodes_.at(i))) {
                return false;
            }
        }
    }
    return true;
}
References ddg_, BoostGraph< GraphNode, GraphEdge >::hasNode(), and nodes_.
Referenced by BUMoveNodeSelector::candidates(), and CriticalPathBBMoveNodeSelector::candidates().
isOperation()
bool MoveNodeGroup::isOperation () const inline
Definition at line 74 of file MoveNodeGroup.hh.
{ return operation_ != NULL; }
References operation_.
Referenced by LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), and toString().
isPlaced()
bool MoveNodeGroup::isPlaced () const
Definition at line 173 of file MoveNodeGroup.cc.
{
    for (std::size_t i = 0; i < nodes_.size(); ++i) {
        if (!nodes_.at(i)->isPlaced())
            return false;
    }
    return true;
}
References nodes_.
isScheduled()
bool MoveNodeGroup::isScheduled () const
Returns true if all moves in the move group have been scheduled.
An empty MoveNodeGroup is considered always scheduled.
Returns
True if scheduled.
Definition at line 164 of file MoveNodeGroup.cc.
{
    for (std::size_t i = 0; i < nodes_.size(); ++i) {
        if (!nodes_.at(i)->isScheduled())
            return false;
    }
    return true;
}
References nodes_.
Referenced by BUMoveNodeSelector::candidates(), CriticalPathBBMoveNodeSelector::candidates(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), RLPriorityNodeId::operator()(), RLPriorityCriticalPath::operator()(), and RLBUPriorityCriticalPath::operator()().
latestCycle()
int MoveNodeGroup::latestCycle () const
Calculates the last cycle in which dependences make it possible to try schedule the leader node.
Returns
The earliest possible cycle
Definition at line 81 of file MoveNodeGroup.cc.
{
    abortWithError("Not yet implemented");
    return 0;
}
References abortWithError.
maxSinkDistance()
int MoveNodeGroup::maxSinkDistance () const
Returns the maximum distance from any movenode in the group to any sink.
Calling this may cause forever loop if the DDG has loops.
Returns
maximum distance from any movenode in the group to any sink.
Definition at line 209 of file MoveNodeGroup.cc.
{
    if (ddg_ == NULL) {
        return 0;
    }
    int maxSD = 0;
    for (int i = 0; i < nodeCount(); i++) {
        int sinkDistance = ddg_->maxSinkDistance(node(i));
        maxSD = std::max (maxSD, sinkDistance);
    }
    return maxSD;
}
References ddg_, BoostGraph< GraphNode, GraphEdge >::maxSinkDistance(), node(), and nodeCount().
Referenced by RLPriorityCriticalPath::operator()(), and RLBUPriorityCriticalPath::operator()().
maxSourceDistance()
int MoveNodeGroup::maxSourceDistance () const
Returns the maximum distance from any source node to any movenode in the group.
Calling this may cause forever loop if the DDG has loops.
Returns
maximum distance from any source node to any node in the group.
Definition at line 230 of file MoveNodeGroup.cc.
{
    if (ddg_ == NULL) {
        return 0;
    }
    int maxSD = 0;
    for (int i = 0; i < nodeCount(); i++) {
        int sourceDistance = ddg_->maxSourceDistance(node(i));
        maxSD = std::max (maxSD, sourceDistance);
    }
    return maxSD;
}
References ddg_, BoostGraph< GraphNode, GraphEdge >::maxSourceDistance(), node(), and nodeCount().
Referenced by RLBUPriorityCriticalPath::operator()().
node()
MoveNode & MoveNodeGroup::node (int index) const
Returns one MoveNode contained in this group.
Parameters
index The index of node which to return
Returns
The node being returned.
Definition at line 152 of file MoveNodeGroup.cc.
{
    return *nodes_.at(index);
}
References nodes_.
Referenced by addNode(), LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), CycleLookBackSoftwareBypasser::bypass(), earliestCycle(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BUMoveNodeSelector::isReadyToBeScheduled(), maxSinkDistance(), maxSourceDistance(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), BasicBlockScheduler::notifyScheduled(), RLPriorityNodeId::operator()(), RLPriorityCriticalPath::operator()(), RLBUPriorityCriticalPath::operator()(), CycleLookBackSoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), BF2Scheduler::scheduleDDG(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), SequentialScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), toString(), BasicBlockScheduler::tryToDelayOperands(), and SequentialMoveNodeSelector::~SequentialMoveNodeSelector().
nodeCount()
int MoveNodeGroup::nodeCount () const
Returns the number of movenodes in the group
Returns
The number of nodes.
Definition at line 140 of file MoveNodeGroup.cc.
{
    return nodes_.size();
}
References nodes_.
Referenced by MoveNodeGroupBuilder::build(), LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), CycleLookBackSoftwareBypasser::bypass(), SoftwareBypasser::bypass(), SequentialScheduler::handleBasicBlock(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BUMoveNodeSelector::isReadyToBeScheduled(), maxSinkDistance(), maxSourceDistance(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), BUMoveNodeSelector::mightBeReady(), BasicBlockScheduler::notifyScheduled(), CycleLookBackSoftwareBypasser::removeBypass(), SoftwareBypasser::removeBypass(), CycleLookBackSoftwareBypasser::removeDeadResults(), SoftwareBypasser::removeDeadResults(), BF2Scheduler::scheduleDDG(), BasicBlockScheduler::scheduleOperandWrites(), SequentialScheduler::scheduleOperandWrites(), BUBasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), SequentialScheduler::scheduleOperation(), SequentialScheduler::scheduleResultReads(), BasicBlockScheduler::scheduleResultReads(), BUBasicBlockScheduler::scheduleResultReads(), toString(), BasicBlockScheduler::tryToDelayOperands(), and SequentialMoveNodeSelector::~SequentialMoveNodeSelector().
programOperationPtr()
ProgramOperationPtr MoveNodeGroup::programOperationPtr () const inline
Definition at line 75 of file MoveNodeGroup.hh.
{ return operation_; }
References operation_.
Referenced by LLVMTCEDataDependenceGraphBuilder::buildLocalDDG(), ResourceConstraintAnalyzer::memoryBoundScheduleResourceUsage(), and toString().
setProgramOperationPtr()
void MoveNodeGroup::setProgramOperationPtr (ProgramOperationPtr op) inline
in case this MNG contains strictly the nodes of a single operation, it can be set and queried with these methods
Definition at line 73 of file MoveNodeGroup.hh.
{ operation_ = op; }
References operation_.
Referenced by MoveNodeGroupBuilder::build().
toString()
std::string MoveNodeGroup::toString () const
Returns the disassembly of moves in NodeGroup as a string.
Returns
string with disasembly of NodeGroup moves.
Definition at line 248 of file MoveNodeGroup.cc.
{
    std::string result = "";
    for (int i = 0; i < nodeCount(); i++) {
        result += node(i).toString() + " ; ";
    }
    if (isOperation()) {
        result += "[PO: " + programOperationPtr()->toString() + "] ";
    }
    return result;
}
References isOperation(), node(), nodeCount(), programOperationPtr(), and MoveNode::toString().
Referenced by MoveNodeGroupBuilder::build(), BasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), and SequentialScheduler::scheduleOperation().
writesJumpGuard()
bool MoveNodeGroup::writesJumpGuard () const
Definition at line 260 of file MoveNodeGroup.cc.
{
    if (ddg_ == nullptr) return false;
    for (auto n: nodes_) {
        if (!ddg_->hasNode(*n)) continue;
        DataDependenceGraph::EdgeSet outEdges = ddg_->outEdges(*n);
        for (auto e: outEdges) {
            if (e->guardUse() && e->edgeReason() == DataDependenceEdge::EDGE_REGISTER &&
                !e->isFalseDep() && !e->headPseudo() && !e->tailPseudo()) {
                MoveNode& head = ddg_->headNode(*e);
                if (head.isMove() && head.move().isControlFlowMove()) {
                    return true;
                }
            }
        }
    }
    return false;
}
References ddg_, DataDependenceEdge::EDGE_REGISTER, BoostGraph< GraphNode, GraphEdge >::hasNode(), BoostGraph< GraphNode, GraphEdge >::headNode(), TTAProgram::Move::isControlFlowMove(), MoveNode::isMove(), MoveNode::move(), nodes_, and BoostGraph< GraphNode, GraphEdge >::outEdges().
Referenced by RLBUPriorityCriticalPath::operator()().
Member Data Documentation
ddg_
const DataDependenceGraph* MoveNodeGroup::ddg_ private
The data dependence graph the moves in this group belong to (optional).
Definition at line 82 of file MoveNodeGroup.hh.
Referenced by earliestCycle(), isAlive(), maxSinkDistance(), maxSourceDistance(), and writesJumpGuard().
nodes_
std::vector<MoveNode*> MoveNodeGroup::nodes_ private
Definition at line 79 of file MoveNodeGroup.hh.
Referenced by addNode(), earliestCycle(), isAlive(), isPlaced(), isScheduled(), node(), nodeCount(), and writesJumpGuard().
operation_
ProgramOperationPtr MoveNodeGroup::operation_ private
in case this MNG contains strictly the nodes of a single operation this can be set to point to it (optional)
Definition at line 85 of file MoveNodeGroup.hh.
Referenced by isOperation(), programOperationPtr(), and setProgramOperationPtr().
The documentation for this class was generated from the following files:
MoveNodeGroup.hh
MoveNodeGroup.cc