OpenASIP: TTAMachine::ResourceVector Class Reference
TTAMachine::ResourceVector Class Reference
#include <ResourceVector.hh>
Public Types
typedef std::set< std::string > ResourceSet
Resources are stored in a set as strings. Normal pipeline resource usages are prefixed with "res:", port usages with "port:".
Public Member Functions
ResourceVector ()
ResourceVector (const TTAMachine::ExecutionPipeline &pipeline)
virtual ~ResourceVector ()
const ResourceSet & resourcesUsedAtCycle (unsigned cycle) const
std::size_t width () const
std::string toString () const
virtual bool conflictsWith (const ResourceVector &other, unsigned cycle) const
virtual void mergeWith (const ResourceVector &other, unsigned cycle)
virtual void shiftLeft ()
virtual void clear ()
virtual bool operator== (const ResourceVector &rightHand) const
Private Types
typedef std::deque< ResourceSet > ResourceUsageIndex
Each resource usage is stored as a string.
Private Attributes
ResourceUsageIndex resources_
The storage for the resource usages.
Detailed Description
Represents a resource vector used in building the states in case of an function unit FSA.
Definition at line 53 of file ResourceVector.hh.
Member Typedef Documentation
ResourceSet
typedef std::set<std::string> TTAMachine::ResourceVector::ResourceSet
Resources are stored in a set as strings. Normal pipeline resource usages are prefixed with "res:", port usages with "port:".
Definition at line 57 of file ResourceVector.hh.
ResourceUsageIndex
typedef std::deque<ResourceSet> TTAMachine::ResourceVector::ResourceUsageIndex private
Each resource usage is stored as a string.
Definition at line 82 of file ResourceVector.hh.
Constructor & Destructor Documentation
ResourceVector() [1/2]
TTAMachine::ResourceVector::ResourceVector () inline
Definition at line 59 of file ResourceVector.hh.
{};
ResourceVector() [2/2]
TTAMachine::ResourceVector::ResourceVector (const TTAMachine::ExecutionPipeline & pipeline)
Constructor.
Builds the resource vector out of MOM ExecutionPipeline.
Parameters
pipeline The ExecutionPipeline to build the resource vector for.
Definition at line 52 of file ResourceVector.cc.
{
    resources_.resize(pipeline.latency(), ResourceSet());
    for (int i = 0; i < pipeline.latency(); ++i) {
        TTAMachine::ExecutionPipeline::ResourceSet resourceUsages =
            pipeline.resourceUsages(i);
        TTAMachine::ExecutionPipeline::ResourceSet::const_iterator res =
            resourceUsages.begin();
        while (res != resourceUsages.end()) {
            resources_.at(i).insert(std::string("res:") + (*res)->name());
            ++res;
        }
        TTAMachine::ExecutionPipeline::OperandSet readOperands =
            pipeline.readOperands(i);
        TTAMachine::ExecutionPipeline::OperandSet writtenOperands =
            pipeline.writtenOperands(i);
        TTAMachine::ExecutionPipeline::OperandSet::const_iterator op =
            readOperands.begin();
        while (op != readOperands.end()) {
            const TTAMachine::FUPort* fuPort =
                pipeline.parentOperation()->port(*op);
                resources_.at(i).insert(
                    std::string("port:") + fuPort->bindingString());
            ++op;
        }
        op = writtenOperands.begin();
        while (op != writtenOperands.end()) {
            const TTAMachine::FUPort* fuPort =
                pipeline.parentOperation()->port(*op);
                resources_.at(i).insert(
                    std::string("port:") + fuPort->bindingString());
            ++op;
        }
    }
}
References TTAMachine::FUPort::bindingString(), TTAMachine::ExecutionPipeline::latency(), TTAMachine::ExecutionPipeline::parentOperation(), TTAMachine::HWOperation::port(), TTAMachine::ExecutionPipeline::readOperands(), resources_, TTAMachine::ExecutionPipeline::resourceUsages(), and TTAMachine::ExecutionPipeline::writtenOperands().
~ResourceVector()
TTAMachine::ResourceVector::~ResourceVector () virtual
Destructor.
Definition at line 93 of file ResourceVector.cc.
{
}
Member Function Documentation
clear()
void TTAMachine::ResourceVector::clear () virtual
Clears the resource vector.
Result is an empty resource vector with no columns
Definition at line 220 of file ResourceVector.cc.
                      {
    resources_.clear();
}
References resources_.
Referenced by ResourceVectorFUResourceConflictDetector::reset().
conflictsWith()
bool TTAMachine::ResourceVector::conflictsWith (const ResourceVector & other, unsigned cycle) const virtual
Returns true if the given resource vector has conflicting resource usages when issued after given count of cycles.
Parameters
other The another resource vector.
cycle The count of cycles after which the operation is issued.
Returns
True iff there is a conflict.
Definition at line 154 of file ResourceVector.cc.
          {
    for (std::size_t c = cycle; c < resources_.size(); ++c) {
        if (other.width() <= c - cycle)
            return false;
        ResourceSet conflictingResources;
        const ResourceSet& thisResources = resources_.at(c);
        const ResourceSet& otherResources =
            other.resourcesUsedAtCycle(c - cycle);
        if (thisResources.size() == 0 || otherResources.size() == 0)
            return false;
        // check if any of the resources in another resource set is
        // found in the another
        ResourceSet::const_iterator i = thisResources.begin();
        while (i != thisResources.end()) {
            if (otherResources.find(*i) != otherResources.end())
                return true;
            ++i;
        }
    }
    return false;
}
References resources_, resourcesUsedAtCycle(), and width().
Referenced by ResourceVectorFUResourceConflictDetector::issueOperation().
mergeWith()
void TTAMachine::ResourceVector::mergeWith (const ResourceVector & other, unsigned cycle) virtual
Merges the resource vector with the given resource vector starting from the given cycle.
This method is used for producing the composite vector for simulation. The resulting resource vector is "stretched" in case there are no enough cycle elements in to contain the merged elements.
Parameters
other The another resource vector.
cycle The count of cycles after which the operation is issued.
Definition at line 194 of file ResourceVector.cc.
{
    resources_.resize(std::max(resources_.size(), cycle + other.width()));
    for (std::size_t i = 0; i < other.width(); ++i) {
        const ResourceSet& otherResources = other.resourcesUsedAtCycle(i);
        resources_[cycle + i].insert(
            otherResources.begin(), otherResources.end());
    }
}
References resources_, resourcesUsedAtCycle(), and width().
Referenced by ResourceVectorFUResourceConflictDetector::issueOperation().
operator==()
bool TTAMachine::ResourceVector::operator== (const ResourceVector & rightHand) const virtual
Compares two ResourceVectors.
Parameters
rightHand Right hand operand.
Returns
True is the two vectors match false otherwise.
Definition at line 232 of file ResourceVector.cc.
{
    if (toString() != rightHand.toString()) {
        return false;
    }
    return true;
}
References toString().
resourcesUsedAtCycle()
const ResourceVector::ResourceSet & TTAMachine::ResourceVector::resourcesUsedAtCycle (unsigned cycle) const
Returns the set that contains the resources used at the given cycle.
Parameters
cycle The cycle.
Returns
The set of resources.
Exceptions
OutOfRange If the cycle is out of range.
Definition at line 104 of file ResourceVector.cc.
{
    if (cycle > resources_.size())
        throw OutOfRange(__FILE__, __LINE__, __func__);
    return resources_.at(cycle);
}
References __func__, and resources_.
Referenced by conflictsWith(), and mergeWith().
shiftLeft()
void TTAMachine::ResourceVector::shiftLeft () virtual
Shifts the resource vector one step left, i.e., deletes the first column.
Definition at line 209 of file ResourceVector.cc.
{
    if (resources_.size() > 0)
        resources_.pop_front();
}
References resources_.
Referenced by ResourceVectorFUResourceConflictDetector::advanceCycle().
toString()
std::string TTAMachine::ResourceVector::toString () const
Returns a textual description of the resource vector.
Returns
A string describing the vector.
Definition at line 116 of file ResourceVector.cc.
{
    std::string theString = "";
    for (unsigned cycle = 0; cycle < resources_.size(); ++cycle) {
        theString += std::string("[") + Conversion::toString(cycle) + ":{";
        const ResourceSet& resSet = resources_.at(cycle);
        for (ResourceSet::const_iterator i = resSet.begin();
             i != resSet.end();) {
            theString += *i;
            ++i;
            if (i != resSet.end())
                theString += ",";
        }
        theString += "}]";
    }
    return theString;
}
References resources_, and Conversion::toString().
Referenced by operator==().
width()
std::size_t TTAMachine::ResourceVector::width () const
Returns the width of the resource vector.
Returns
The width.
Definition at line 141 of file ResourceVector.cc.
{
    return resources_.size();
}
References resources_.
Referenced by conflictsWith(), mergeWith(), and TTAMachine::ResourceVectorSet::ResourceVectorSet().
Member Data Documentation
resources_
ResourceUsageIndex TTAMachine::ResourceVector::resources_ private
The storage for the resource usages.
Definition at line 84 of file ResourceVector.hh.
Referenced by clear(), conflictsWith(), mergeWith(), resourcesUsedAtCycle(), ResourceVector(), shiftLeft(), toString(), and width().
The documentation for this class was generated from the following files:
ResourceVector.hh
ResourceVector.cc