OpenASIP: IDF::FUGenerated Class Reference
IDF::FUGenerated Class Reference
#include <FUGenerated.hh>
Classes
struct DAGOperation
struct Info
Public Member Functions
FUGenerated ()=default
FUGenerated (const std::string &name)
virtual ~FUGenerated ()=default
void loadState (const ObjectState *state) override
ObjectState * saveState () const override
std::string name () const
void name (const std::string &newName)
std::vector< Info > & operations ()
const std::vector< std::string > & dagOperations () const
const std::vector< Info > & operations () const
void addOperation (const Info &op)
void addOperation (const DAGOperation &op)
const std::vector< std::string > & options () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Attributes
std::string name_
std::vector< Info > operations_
std::vector< std::string > dagOperations_
std::vector< std::string > options_
Detailed Description
Definition at line 41 of file FUGenerated.hh.
Constructor & Destructor Documentation
FUGenerated() [1/2]
IDF::FUGenerated::FUGenerated () default
FUGenerated() [2/2]
IDF::FUGenerated::FUGenerated (const std::string & name)
Definition at line 45 of file FUGenerated.cc.
: name_(name) {}
~FUGenerated()
virtual IDF::FUGenerated::~FUGenerated () virtual default
Member Function Documentation
addOperation() [1/2]
void IDF::FUGenerated::addOperation (const DAGOperation & op)
Definition at line 133 of file FUGenerated.cc.
{
    dagOperations_.emplace_back(op.operationName);
    for (auto&& subop : op.suboperations) {
        operations_.emplace_back(subop);
    }
}
References dagOperations_, IDF::FUGenerated::DAGOperation::operationName, operations_, and IDF::FUGenerated::DAGOperation::suboperations.
addOperation() [2/2]
void IDF::FUGenerated::addOperation (const Info & op)
Definition at line 128 of file FUGenerated.cc.
{
    operations_.emplace_back(op);
}
References operations_.
Referenced by ProGeTools::checkForGeneratableFU(), and Automagic::checkForGeneratableFU().
dagOperations()
const std::vector< std::string > & IDF::FUGenerated::dagOperations () const
Definition at line 123 of file FUGenerated.cc.
{
    return dagOperations_;
}
References dagOperations_.
loadState()
void IDF::FUGenerated::loadState (const ObjectState * state) override virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState object from which (and the children of which) the state is loaded.
Implements Serializable.
Definition at line 48 of file FUGenerated.cc.
{
    name_ = state->stringAttribute(ATTRIB_NAME);
    for (int i = state->childCount() - 1; i >= 0; --i) {
        ObjectState* child = state->child(i);
        if (child->name() == TAG_OPERATION) {
            std::string opName = child->stringAttribute(ATTRIB_NAME);
            std::string hdbFile =
                child->childByName(TAG_HDBFILE)->stringValue();
            int id = child->childByName(TAG_OPERATION_ID)->intValue();
            int latency = 0;
            if (child->hasChild(TAG_OPERATION_LATENCY)) {
                latency =
                    child->childByName(TAG_OPERATION_LATENCY)->intValue();
            }
            Info info = {opName, hdbFile, id, latency};
            operations_.emplace_back(info);
        } else if (child->name() == TAG_OPTION) {
            options_.emplace_back(child->stringValue());
        }
    }
}
References IDF::ATTRIB_NAME, ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), ObjectState::hasChild(), ObjectState::intValue(), ObjectState::name(), name_, operations_, options_, ObjectState::stringAttribute(), ObjectState::stringValue(), IDF::TAG_HDBFILE, IDF::TAG_OPERATION, IDF::TAG_OPERATION_ID, IDF::TAG_OPERATION_LATENCY, and IDF::TAG_OPTION.
Referenced by IDF::MachineImplementation::loadState().
name() [1/2]
std::string IDF::FUGenerated::name () const
Definition at line 103 of file FUGenerated.cc.
{
    return name_;
}
References name_.
Referenced by ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), ProGeTools::checkForGeneratableFU(), Automagic::checkForGeneratableFU(), FUGen::createFUHeaderComment(), FUGen::createShadowRegisters(), and ProGe::ProGeUI::generateIDF().
name() [2/2]
void IDF::FUGenerated::name (const std::string & newName)
Definition at line 108 of file FUGenerated.cc.
{
    name_ = newName;
}
References name_.
operations() [1/2]
std::vector< FUGenerated::Info > & IDF::FUGenerated::operations ()
Definition at line 113 of file FUGenerated.cc.
{
    return operations_;
}
References operations_.
Referenced by FUGen::createImplementationFiles(), and FUGen::parseOperations().
operations() [2/2]
const std::vector< FUGenerated::Info > & IDF::FUGenerated::operations () const
Definition at line 118 of file FUGenerated.cc.
{
    return operations_;
}
References operations_.
options()
const std::vector< std::string > & IDF::FUGenerated::options () const
Definition at line 141 of file FUGenerated.cc.
{
    return options_;
}
References options_.
saveState()
ObjectState * IDF::FUGenerated::saveState () const override virtual
Saves the objects state into an ObjectState object and maybe its child objects.
Returns
The root of the ObjectState tree created.
Implements Serializable.
Definition at line 73 of file FUGenerated.cc.
{
    ObjectState* state = new ObjectState(TAG_FUGENERATE);
    state->setAttribute(ATTRIB_NAME, name_);
    for (const auto operation : operations_) {
        ObjectState* opState = new ObjectState(TAG_OPERATION);
        opState->setAttribute(ATTRIB_NAME, operation.operationName);
        ObjectState* hdbState = new ObjectState(TAG_HDBFILE);
        hdbState->setValue(operation.hdb);
        ObjectState* idState = new ObjectState(TAG_OPERATION_ID);
        idState->setValue(operation.id);
        ObjectState* latencyState = new ObjectState(TAG_OPERATION_LATENCY);
        latencyState->setValue(operation.latency);
        opState->addChild(hdbState);
        opState->addChild(idState);
        opState->addChild(latencyState);
        state->addChild(opState);
    }
    for (const auto option : options_) {
        ObjectState* opState = new ObjectState(TAG_OPTION);
        opState->setValue(option);
        state->addChild(opState);
    }
    return state;
}
References ObjectState::addChild(), IDF::ATTRIB_NAME, name_, operations_, options_, ObjectState::setAttribute(), ObjectState::setValue(), IDF::TAG_FUGENERATE, IDF::TAG_HDBFILE, IDF::TAG_OPERATION, IDF::TAG_OPERATION_ID, IDF::TAG_OPERATION_LATENCY, and IDF::TAG_OPTION.
Member Data Documentation
dagOperations_
std::vector<std::string> IDF::FUGenerated::dagOperations_ private
Definition at line 74 of file FUGenerated.hh.
Referenced by addOperation(), and dagOperations().
name_
std::string IDF::FUGenerated::name_ private
Definition at line 72 of file FUGenerated.hh.
Referenced by loadState(), name(), name(), and saveState().
operations_
std::vector<Info> IDF::FUGenerated::operations_ private
Definition at line 73 of file FUGenerated.hh.
Referenced by addOperation(), addOperation(), loadState(), operations(), operations(), and saveState().
options_
std::vector<std::string> IDF::FUGenerated::options_ private
Definition at line 75 of file FUGenerated.hh.
Referenced by loadState(), options(), and saveState().
The documentation for this class was generated from the following files:
FUGenerated.hh
FUGenerated.cc