OpenASIP: SimulatorCLI Class Reference
SimulatorCLI Class Reference
#include <SimulatorCLI.hh>
Public Member Functions
SimulatorCLI ()=delete
SimulatorCLI (SimulatorFrontend &frontend)
virtual ~SimulatorCLI ()
virtual void run ()
virtual void interpreteAndPrintResults (const TCEString &scriptString)
SimulatorInterpreter & interpreter ()
Protected Attributes
SimulatorFrontend & simFront_
SimulatorInterpreterContext * context_
LineReader * reader_
SimulatorInterpreter * interpreter_
SimulatorCmdLineOptions * options_
RuntimeErrorReporter * errorReporter_
Detailed Description
Command Line Interface for controlling the simulation engine using the simulator control scripting language (tcl).
Definition at line 48 of file SimulatorCLI.hh.
Constructor & Destructor Documentation
SimulatorCLI() [1/2]
SimulatorCLI::SimulatorCLI () delete
SimulatorCLI() [2/2]
SimulatorCLI::SimulatorCLI (SimulatorFrontend & frontend)
Parameters
simulatorInterpreter Use the given interpreter instead of default one. Takes ownership of the object.
Catch runtime errors and print them out to the simulator console.
Definition at line 121 of file SimulatorCLI.cc.
                                                      :
    simFront_(frontend),
    context_(new SimulatorInterpreterContext(frontend)),
    reader_(LineReaderFactory::lineReader()) {
    assert(reader_ != NULL);
    reader_->initialize(SIM_COMMAND_PROMPT);
    reader_->setInputHistoryLog(SIM_DEFAULT_COMMAND_LOG);
    options_ = NULL;
    if (Application::cmdLineOptions() != NULL) {
        options_ = dynamic_cast<SimulatorCmdLineOptions*>(
            Application::cmdLineOptions());
    }
    if (frontend.isCompiledSimulation()) {
        interpreter_ =
            new CompiledSimInterpreter(
                Application::argc(), Application::argv(),
                *context_, *reader_);
    } else {
        interpreter_ =
            new SimulatorInterpreter(
                Application::argc(), Application::argv(),
                *context_, *reader_);
    }
    /// Catch runtime errors and print them out to the simulator console.
    errorReporter_ = new RuntimeErrorReporter(simFront_);
}
References Application::argc(), Application::argv(), assert, Application::cmdLineOptions(), context_, errorReporter_, LineReader::initialize(), interpreter_, SimulatorFrontend::isCompiledSimulation(), options_, reader_, LineReader::setInputHistoryLog(), SIM_COMMAND_PROMPT, SIM_DEFAULT_COMMAND_LOG, and simFront_.
~SimulatorCLI()
SimulatorCLI::~SimulatorCLI () virtual
Definition at line 153 of file SimulatorCLI.cc.
{
    delete reader_;
    reader_ = NULL;
    delete interpreter_;
    interpreter_ = NULL;
    delete context_;
    context_ = NULL;
    delete errorReporter_;
    errorReporter_ = NULL;
}
References context_, errorReporter_, interpreter_, and reader_.
Member Function Documentation
interpreteAndPrintResults()
void SimulatorCLI::interpreteAndPrintResults (const TCEString & scriptString) virtual
Executes the given script string in the script interpreter and prints out possible results.
Parameters
interpreter Interpreter to use.
scriptString Script string to execute.
Definition at line 176 of file SimulatorCLI.cc.
{
    interpreter_->interpret(scriptString);
    if (interpreter_->result().size() > 0)
        std::cout << interpreter_->result() << std::endl;
}
References TclInterpreter::interpret(), interpreter_, and ScriptInterpreter::result().
Referenced by main().
interpreter()
SimulatorInterpreter & SimulatorCLI::interpreter () inline
Definition at line 58 of file SimulatorCLI.hh.
{ return *interpreter_; }
References interpreter_.
Referenced by main().
run()
void SimulatorCLI::run () virtual
Runs the interpreter loop.
Inputs a line of script from the user, processes it and prints out the results.
Definition at line 189 of file SimulatorCLI.cc.
                  {
    while (!interpreter_->isQuitCommandGiven()) {
        std::string command = "";
        try {
            command = reader_->readLine();
        } catch (const EndOfFile&) {
            // execute the actual interpreter quit command in case user
            // pressed ctrl-d or the input file ended, to make sure
            // all uninitialization routines are executed correctly
            interpreter_->interpret(SIM_INTERP_QUIT_COMMAND);
            std::cout << interpreter_->result() << std::endl;
            break;
        }
        command = StringTools::trim(command);
        if (command == "") {
            continue;
        }
        interpreter_->interpret(command);
        if (interpreter_->result().size() > 0)
            std::cout << interpreter_->result() << std::endl;
    }
}
References TclInterpreter::interpret(), interpreter_, SimulatorInterpreter::isQuitCommandGiven(), reader_, LineReader::readLine(), ScriptInterpreter::result(), SIM_INTERP_QUIT_COMMAND, and StringTools::trim().
Referenced by main().
Member Data Documentation
context_
SimulatorInterpreterContext* SimulatorCLI::context_ protected
Definition at line 61 of file SimulatorCLI.hh.
Referenced by SimulatorCLI(), and ~SimulatorCLI().
errorReporter_
RuntimeErrorReporter* SimulatorCLI::errorReporter_ protected
Definition at line 65 of file SimulatorCLI.hh.
Referenced by SimulatorCLI(), and ~SimulatorCLI().
interpreter_
SimulatorInterpreter* SimulatorCLI::interpreter_ protected
Definition at line 63 of file SimulatorCLI.hh.
Referenced by interpreteAndPrintResults(), interpreter(), run(), SimulatorCLI(), TTASimulatorCLI::TTASimulatorCLI(), and ~SimulatorCLI().
options_
SimulatorCmdLineOptions* SimulatorCLI::options_ protected
Definition at line 64 of file SimulatorCLI.hh.
Referenced by SimulatorCLI().
reader_
LineReader* SimulatorCLI::reader_ protected
Definition at line 62 of file SimulatorCLI.hh.
Referenced by run(), SimulatorCLI(), and ~SimulatorCLI().
simFront_
SimulatorFrontend& SimulatorCLI::simFront_ protected
Definition at line 60 of file SimulatorCLI.hh.
Referenced by SimulatorCLI().
The documentation for this class was generated from the following files:
SimulatorCLI.hh
SimulatorCLI.cc