OpenASIP: NullRegisterFileState Class Reference
NullRegisterFileState Class Reference
#include <RegisterFileState.hh>
Public Member Functions
virtual ~NullRegisterFileState ()
virtual RegisterState & registerState (int index)
Public Member Functions inherited from RegisterFileState
RegisterFileState (int size, int width, bool zeroRegister=false)
virtual ~RegisterFileState ()
virtual std::size_t registerCount () const
Static Public Member Functions
static NullRegisterFileState & instance ()
Private Member Functions
NullRegisterFileState ()
NullRegisterFileState (const NullRegisterFileState &)
Copying not allowed.
NullRegisterFileState & operator= (const NullRegisterFileState &)
Assignment not allowed.
Static Private Attributes
static NullRegisterFileState * instance_ = NULL
Unique instance of NullRegisterFileState.
Detailed Description
Models non-existing RegisterFileState.
Definition at line 78 of file RegisterFileState.hh.
Constructor & Destructor Documentation
~NullRegisterFileState()
NullRegisterFileState::~NullRegisterFileState () virtual
Destructor.
Definition at line 127 of file RegisterFileState.cc.
{
}
NullRegisterFileState() [1/2]
NullRegisterFileState::NullRegisterFileState () private
Constructor.
Definition at line 121 of file RegisterFileState.cc.
                                             : RegisterFileState(0, 0) {
}
Referenced by instance().
NullRegisterFileState() [2/2]
NullRegisterFileState::NullRegisterFileState (const NullRegisterFileState &) private
Copying not allowed.
Member Function Documentation
instance()
NullRegisterFileState & NullRegisterFileState::instance () static
Returns the instance of NullRegisterFileState.
Returns
The instance of NullRegisterFileState.
Definition at line 111 of file RegisterFileState.cc.
{
    if (instance_ == NULL) {
        instance_ = new NullRegisterFileState();
    }
    return *instance_;
}
References instance_, and NullRegisterFileState().
Referenced by MachineStateBuilder::buildMachineState(), RFTestbenchGenerator::createStimulus(), SimProgramBuilder::processBidirTerminal(), and MachineState::registerFileState().
operator=()
NullRegisterFileState & NullRegisterFileState::operator= (const NullRegisterFileState &) private
Assignment not allowed.
registerState()
RegisterState & NullRegisterFileState::registerState (int index) virtual
Aborts the program with error message.
Returns
Never returns.
Exceptions
OutOfRange Never throws.
Reimplemented from RegisterFileState.
Definition at line 137 of file RegisterFileState.cc.
{
    Application::abortWithError("registerState()");
    return NullRegisterState::instance();
}
References NullRegisterState::instance().
Member Data Documentation
instance_
NullRegisterFileState * NullRegisterFileState::instance_ = NULL static private
Unique instance of NullRegisterFileState.
Definition at line 94 of file RegisterFileState.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
RegisterFileState.hh
RegisterFileState.cc