OpenASIP: OperationModule Class Reference
OperationModule Class Reference
#include <OperationModule.hh>
Public Member Functions
OperationModule (const std::string &name, const std::string &path)
OperationModule (const OperationModule &om)
virtual ~OperationModule ()
OperationModule & operator= (const OperationModule &om)
virtual std::string name () const
virtual bool definesBehavior () const
virtual std::string behaviorModule () const
virtual std::string propertiesModule () const
virtual bool hasBehaviorSource () const
virtual std::string behaviorSourceModule () const
Private Member Functions
std::string propertyFileName () const
std::string behaviorFileName () const
std::string behaviorSourceFileName () const
Private Attributes
std::string path_
The path of the module.
std::string name_
The name of the module.
Static Private Attributes
static const std::string PROPERTY_FILE_EXTENSION = ".opp"
File extension of operation property file.
static const std::string BEHAVIOR_FILE_EXTENSION = ".opb"
File extension of operation behavior file.
static const std::string BEHAVIOR_SOURCE_FILE_EXTENSION = ".cc"
File extension of operation behavior source file.
Detailed Description
Class that represents the name and the path of external files where Operation definitions are stored.
Definition at line 46 of file OperationModule.hh.
Constructor & Destructor Documentation
OperationModule() [1/2]
OperationModule::OperationModule (const std::string & name, const std::string & path)
Constructor.
Parameters
name The name of the module.
path The path of the module.
Definition at line 54 of file OperationModule.cc.
                           : path_(path), name_(name) {
}
OperationModule() [2/2]
OperationModule::OperationModule (const OperationModule & om)
Copy constructor.
Parameters
om The module to be copied.
Definition at line 64 of file OperationModule.cc.
{
    name_ = om.name();
    path_ = FileSystem::directoryOfPath(om.propertiesModule());
}
References FileSystem::directoryOfPath(), name(), name_, path_, and propertiesModule().
~OperationModule()
OperationModule::~OperationModule () virtual
Destructor.
Definition at line 72 of file OperationModule.cc.
{
}
Member Function Documentation
behaviorFileName()
std::string OperationModule::behaviorFileName () const private
Returns the name of the behavior file name.
Returns
The name of the behavior file name.
Definition at line 170 of file OperationModule.cc.
{
    return name_ + BEHAVIOR_FILE_EXTENSION;
}
References BEHAVIOR_FILE_EXTENSION, and name_.
Referenced by behaviorModule(), and definesBehavior().
behaviorModule()
string OperationModule::behaviorModule () const virtual
Returns the name of the behavior module.
Returns
The name of the behavior module.
Exceptions
FileNotFound If behavior module is not found.
Reimplemented in NullOperationModule.
Definition at line 105 of file OperationModule.cc.
{
    if (!definesBehavior()) {
        std::string method = "OperationModule::behaviorModule()";
        std::string msg = "Behavior file not found: " + behaviorFileName();
        throw FileNotFound(__FILE__, __LINE__, method, msg);
    }
    return path_ + FileSystem::DIRECTORY_SEPARATOR + behaviorFileName();
}
References behaviorFileName(), definesBehavior(), FileSystem::DIRECTORY_SEPARATOR, and path_.
behaviorSourceFileName()
std::string OperationModule::behaviorSourceFileName () const private
Returns the name of the code file.
Returns
The name of the code file.
Definition at line 190 of file OperationModule.cc.
{
    return name_ + BEHAVIOR_SOURCE_FILE_EXTENSION;
}
References BEHAVIOR_SOURCE_FILE_EXTENSION, and name_.
Referenced by behaviorSourceModule(), and hasBehaviorSource().
behaviorSourceModule()
string OperationModule::behaviorSourceModule () const virtual
Returns the name of the behavior source code file.
Returns
The name of the behavior source code file.
Exceptions
FileNotFound If behavior source file not found.
Reimplemented in NullOperationModule.
Definition at line 144 of file OperationModule.cc.
{
    if (!hasBehaviorSource()) {
        std::string method = "OperationModule::behaviorSourceModule()";
        std::string msg = "Behavior source file not found.";
        throw FileNotFound(__FILE__, __LINE__, method, msg);
    }
    return path_ + FileSystem::DIRECTORY_SEPARATOR + behaviorSourceFileName();
}
References behaviorSourceFileName(), FileSystem::DIRECTORY_SEPARATOR, hasBehaviorSource(), and path_.
Referenced by OperationPropertyDialog::onOpen().
definesBehavior()
bool OperationModule::definesBehavior () const virtual
Checks whether OperationModule has behavior definition file.
Returns
True if OperationModule has behavior definition file.
Reimplemented in NullOperationModule.
Definition at line 93 of file OperationModule.cc.
{
    return (FileSystem::fileExists(
                path_ + FileSystem::DIRECTORY_SEPARATOR + behaviorFileName()));
}
References behaviorFileName(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and path_.
Referenced by behaviorModule().
hasBehaviorSource()
bool OperationModule::hasBehaviorSource () const virtual
Checks whether module has behavior source file.
Returns
True if module has behavior source file.
Reimplemented in NullOperationModule.
Definition at line 131 of file OperationModule.cc.
{
    return (FileSystem::fileExists(
                path_ + FileSystem::DIRECTORY_SEPARATOR +
                behaviorSourceFileName()));
}
References behaviorSourceFileName(), FileSystem::DIRECTORY_SEPARATOR, FileSystem::fileExists(), and path_.
Referenced by behaviorSourceModule(), OperationPropertyDialog::createContents(), OperationPropertyDialog::onOpen(), and OperationPropertyDialog::setBehaviorLabel().
name()
std::string OperationModule::name () const virtual
Returns the name of the module.
Returns
The name of the module.
Reimplemented in NullOperationModule.
Definition at line 160 of file OperationModule.cc.
{
    return name_;
}
References name_.
Referenced by OSEdTreeView::constructTree(), OperationContainer::module(), OperationModule(), operator=(), and OperationPropertyDialog::updateOperation().
operator=()
OperationModule & OperationModule::operator= (const OperationModule & om)
Assignment operator.
Parameters
om Module to be assigned.
Definition at line 81 of file OperationModule.cc.
{
    name_ = om.name();
    path_ = FileSystem::directoryOfPath(om.propertiesModule());
    return *this;
}
References FileSystem::directoryOfPath(), name(), name_, path_, and propertiesModule().
propertiesModule()
string OperationModule::propertiesModule () const virtual
Returns the name of the properties module.
Returns
The name of the properties module.
Reimplemented in NullOperationModule.
Definition at line 121 of file OperationModule.cc.
{
    return path_ + FileSystem::DIRECTORY_SEPARATOR + propertyFileName();
}
References FileSystem::DIRECTORY_SEPARATOR, path_, and propertyFileName().
Referenced by OSEdTreeView::constructTree(), OperationIndex::effectiveOperation(), OperationPropertyLoader::loadModule(), OperationPropertyLoader::loadOperationProperties(), OperationPropertyDialog::onOpen(), OperationContainer::operation(), OperationIndex::operationCount(), OperationModule(), OperationIndex::operationName(), operator=(), OperationIndex::readOperations(), OperationIndex::refreshModule(), and OperationIndex::removeModule().
propertyFileName()
std::string OperationModule::propertyFileName () const private
Returns the name of the properties file.
Returns
The name of the properties file.
Definition at line 180 of file OperationModule.cc.
{
    return name_ + PROPERTY_FILE_EXTENSION;
}
References name_, and PROPERTY_FILE_EXTENSION.
Referenced by propertiesModule().
Member Data Documentation
BEHAVIOR_FILE_EXTENSION
const string OperationModule::BEHAVIOR_FILE_EXTENSION = ".opb" static private
File extension of operation behavior file.
Behavior file extension.
Definition at line 70 of file OperationModule.hh.
Referenced by behaviorFileName().
BEHAVIOR_SOURCE_FILE_EXTENSION
const string OperationModule::BEHAVIOR_SOURCE_FILE_EXTENSION = ".cc" static private
File extension of operation behavior source file.
Source file extension.
Definition at line 72 of file OperationModule.hh.
Referenced by behaviorSourceFileName().
name_
std::string OperationModule::name_ private
The name of the module.
Definition at line 77 of file OperationModule.hh.
Referenced by behaviorFileName(), behaviorSourceFileName(), name(), OperationModule(), operator=(), and propertyFileName().
path_
std::string OperationModule::path_ private
The path of the module.
Definition at line 75 of file OperationModule.hh.
Referenced by behaviorModule(), behaviorSourceModule(), definesBehavior(), hasBehaviorSource(), OperationModule(), operator=(), and propertiesModule().
PROPERTY_FILE_EXTENSION
const string OperationModule::PROPERTY_FILE_EXTENSION = ".opp" static private
File extension of operation property file.
Property file extension.
Definition at line 68 of file OperationModule.hh.
Referenced by propertyFileName().
The documentation for this class was generated from the following files:
OperationModule.hh
OperationModule.cc