OpenASIP: EditPart Class Reference
EditPart Class Reference
#include <EditPart.hh>
Public Member Functions
EditPart ()
virtual ~EditPart ()
void putGarbage (std::set< EditPart * > &trashbag)
EditPart * parent () const
void setParent (EditPart *parent)
TTAMachine::MachinePart * model () const
void setModel (TTAMachine::MachinePart *model)
Figure * figure () const
void setFigure (Figure *figure)
EditPart * find (wxPoint point)
EditPart * find (const TTAMachine::MachinePart *model)
EditPart * findNearest (wxPoint point, const EditPart *exclude=NULL)
int findInRange (wxPoint point, float radius, std::vector< EditPart * > &found)
bool hasEditPartRecursive (const EditPart *part) const
bool selectable () const
bool selected () const
void setSelectable (bool selectable)
void setSelected (bool select)
void installEditPolicy (EditPolicy *editpolicy)
void addChild (EditPart *child)
int childCount () const
EditPart * child (unsigned int index) const
ComponentCommand * performRequest (Request *request) const
bool canHandle (Request *request) const
Protected Attributes
EditPart * parent_
Parent of this EditPart.
Figure * figure_
Figure of this EditPart.
TTAMachine::MachinePart * model_
Machine component corresponding to this EditPart.
bool selectable_
Tells whether the EditPart is selectable or not.
bool selected_
Tells whether the EditPart is selected or not.
bool garbageCollected_
Helper member to prevent improper deletion.
std::vector< EditPolicy * > editPolicies_
List of supported EditPolicies.
std::vector< EditPart * > children_
List of children EditParts.
Private Member Functions
EditPart & operator= (EditPart &old)
Assignment not allowed.
EditPart (EditPart &old)
Copying not allowed.
Static Private Member Functions
static float distance (wxPoint p, wxRect r)
Detailed Description
Connects a model object to a graphical object on the canvas.
An EditPart receives Requests generated by user actions and converts them to possible changes in the model (Commands) using its EditPolicies. EditParts can contain other EditParts as children. Every EditPart has a Figure.
Definition at line 60 of file EditPart.hh.
Constructor & Destructor Documentation
EditPart() [1/2]
EditPart::EditPart ()
The Constructor.
Definition at line 60 of file EditPart.cc.
                   :
                parent_(NULL), figure_(NULL), model_(NULL), selectable_(
                    false), selected_(false), garbageCollected_(false) {
}
~EditPart()
EditPart::~EditPart () virtual
The Destructor.
Note
Do not destruct this object elsewhere than in the RootEditPart destructor! Children "garbage" should be collected before and EditPart is deleted.
Definition at line 72 of file EditPart.cc.
                    {
    assert(garbageCollected_);
    for (unsigned int i = 0; i < editPolicies_.size(); i++) {
        delete editPolicies_[i];
    }
    editPolicies_.clear();
    delete figure_;
}
References assert, editPolicies_, figure_, and garbageCollected_.
EditPart() [2/2]
EditPart::EditPart (EditPart & old) private
Copying not allowed.
Member Function Documentation
addChild()
void EditPart::addChild (EditPart * child)
Adds an EditPart as a child.
Parameters
child The new child to be added.
Definition at line 260 of file EditPart.cc.
{
    if (child != NULL && !ContainerTools::containsValue(children_, child)) {
        assert(figure_ != NULL);
        figure_->addChild(child->figure());
        children_.push_back(child);
    }
}
References Figure::addChild(), assert, child(), children_, ContainerTools::containsValue(), figure(), and figure_.
Referenced by UnitPortFactory::addSocket(), MachineEditPartFactory::createBiDirBridge(), MachineEditPartFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), MachineEditPartFactory::getBusChains(), MachineEditPartFactory::getSockets(), and MachineEditPartFactory::getUnits().
canHandle()
bool EditPart::canHandle (Request * request) const
Tells whether this EditPart can handle a certain type of Request.
Parameters
request The Request to be asked if it can be handled.
Returns
true if an EditPolicy supporting the given Request is installed to this EditPart, false otherwise.
Definition at line 316 of file EditPart.cc.
{
    vector<EditPolicy*>::const_iterator i = editPolicies_.begin();
    for (; i != editPolicies_.end(); i++) {
        if ((*i)->canHandle(request)) {
            return true;
        }
    }
    return false;
}
References editPolicies_.
Referenced by CopyComponentCmd::isEnabled(), CutComponentCmd::isEnabled(), DeleteComponentCmd::isEnabled(), ModifyComponentCmd::isEnabled(), ConnectTool::leftClick(), ProximMachineCanvasTool::onMouseEvent(), ConnectTool::onMouseEvent(), SelectTool::onMouseEvent(), ProximMachineStateWindow::onSimulationStop(), and ConnectTool::updateStatusline().
child()
EditPart * EditPart::child (unsigned int index) const
Referenced by addChild(), DeleteBridgeCmd::Do(), and ModifyBridgeCmd::Do().
childCount()
int EditPart::childCount () const
Referenced by UnitPortFactory::createEditPart(), DeleteBridgeCmd::Do(), and ModifyBridgeCmd::Do().
distance()
float EditPart::distance (wxPoint p, wxRect r) static private
Calculates distance between a point and a rectangle.
Parameters
p Position.
r Rectangle.
Returns
Distance between point and rectangle. Zero if the point is in the rectangle.
Definition at line 335 of file EditPart.cc.
{
    float xr = 0;
    float yr = 0;
    float xp = static_cast<float>(p.x);
    float yp = static_cast<float>(p.y);
    xr = static_cast<float>(max(min(p.x, r.GetRight()), r.GetLeft()));
    yr = static_cast<float>(max(min(p.y, r.GetBottom()), r.GetTop()));
    float dist = sqrt((xr - xp) * (xr - xp) + (yr - yp) * (yr - yp));
    return dist;
}
Referenced by findInRange(), and findNearest().
figure()
Figure * EditPart::figure () const
Referenced by addChild(), MachineCanvas::addMove(), MachineCanvas::clearHighlights(), ConnectTool::figure(), findNearest(), MachineCanvas::getFigureSize(), MachineCanvas::highlight(), SelectTool::leftClick(), MachineCanvas::OnDraw(), ConnectionEditPart::setSource(), ConnectionEditPart::setTarget(), and MachineCanvas::updateMachine().
find() [1/2]
EditPart * EditPart::find (const TTAMachine::MachinePart * model)
Finds an EditPart which corresponds given machine component.
Parameters
model Machine component to find.
Returns
EditPart of the machine component, or NULL if the component was not found.
Definition at line 134 of file EditPart.cc.
{
    if (model == model_) {
        return this;
    }
    EditPart* found = NULL;
    // Check if the component is child of this edit part.
    for (unsigned int i = 0; i < children_.size(); i++) {
        found = children_[i]->find(model);
        if (found != NULL) {
            return found;
        }
    }
    return NULL;
}
References children_, find(), model(), and model_.
find() [2/2]
EditPart * EditPart::find (wxPoint point)
Finds an EditPart whose Figure is located in the given point.
Parameters
point Point in which to find an EditPart.
Returns
EditPart whose Figure is located in point or NULL if none found.
Definition at line 102 of file EditPart.cc.
{
    EditPart* found = NULL;
    // first check if a child is in point
    for (unsigned int i = 0; i < children_.size(); i++) {
        found = children_[i]->find(point);
        if (found != NULL) {
            return found;
        }
    }
    // if no children were in located in the point, check self
#if wxCHECK_VERSION(2, 8, 0)
    if (selectable_ && figure_->virtualBounds().Contains(point)) {
#else
    if (selectable_ && figure_->virtualBounds().Inside(point)) {
#endif
        return this;
    } else {
        return NULL;
    }
}
References children_, figure_, find(), selectable_, and Figure::virtualBounds().
Referenced by find(), find(), MachineCanvas::findEditPart(), MachineCanvas::findEditPart(), and MachineCanvas::highlight().
findInRange()
int EditPart::findInRange (wxPoint point, float radius, std::vector< EditPart * > & found)
Recursively looks for selectable EditParts including self that are in range around given coordinates.
Parameters
point Position for the search.
radius Search range.
found Found EditParts are collected to this.
Returns
Number of found EditParts.
Definition at line 219 of file EditPart.cc.
{
    int totalFound = 0;
    for (unsigned int i = 0; i < children_.size(); i++) {
        totalFound += children_[i]->findInRange(point, radius, found);
    }
    if (!selectable_) {
        return totalFound;
    }
    if (distance(point, figure_->virtualBounds()) < radius) {
        found.push_back(this);
        return totalFound + 1;
    }
    return totalFound;
}
References children_, distance(), figure_, findInRange(), selectable_, and Figure::virtualBounds().
Referenced by MachineCanvas::findEditPartsInRange(), and findInRange().
findNearest()
EditPart * EditPart::findNearest (wxPoint point, const EditPart * exclude = NULL)
Finds an EditPart whose Figure is nearest to the given point or first found EditPart whose figure contains the given point.
Parameters
point Point in which to find the nearest EditPart.
exclude An EditPart which is not included in the search.
Returns
EditPart if the search found one. Otherwise returns NULL.
Definition at line 162 of file EditPart.cc.
{
    EditPart* found = NULL;
    EditPart* lastFound = NULL;
    int lastDist = std::numeric_limits<int>::max();
    for (unsigned int i = 0; i < children_.size(); i++) {
        found = children_[i]->findNearest(point, exclude);
        if (found != NULL) {
            wxRect foundRect = found->figure()->virtualBounds();
#if wxCHECK_VERSION(2, 8, 0)
            if (foundRect.Contains(point)) {
#else
            if (foundRect.Inside(point)) {
#endif
                assert(found->selectable());
                return found;
            }
            if (distance(point, foundRect) < lastDist) {
                lastFound = found;
                lastDist = distance(point, foundRect);
            }
        }
    }
    if (!selectable_ || this == exclude) {
        return lastFound;
    }
    // Check if this part's figure is closer to given point or
    // contains the point.
#if wxCHECK_VERSION(2, 8, 0)
    if(figure_->virtualBounds().Contains(point)) {
#else
    if (figure_->virtualBounds().Inside(point)) {
#endif
        return this;
    } else {
        if (distance(point, figure_->virtualBounds()) < lastDist) {
            return this;
        } else {
            return lastFound;
        }
    }
}
References assert, children_, distance(), figure(), figure_, findNearest(), selectable(), selectable_, and Figure::virtualBounds().
Referenced by findNearest().
hasEditPartRecursive()
bool EditPart::hasEditPartRecursive (const EditPart * part) const
Looks for given EditPart recursively.
Parameters
part EditPart to look up.
Returns
True if tree has given EditPart.
Definition at line 274 of file EditPart.cc.
{
    if (part == this) {
        return true;
    }
    for (unsigned int i = 0; i < children_.size(); i++) {
        if (children_.at(i)->hasEditPartRecursive(part)) {
            return true;
        }
    }
    return false;
}
References children_.
Referenced by MachineCanvas::hasEditPart().
installEditPolicy()
void EditPart::installEditPolicy (EditPolicy * editpolicy)
Installs a new EditPolicy.
Parameters
editpolicy The EditPolicy to be installed.
Note
Only one EditPolicy per Request type should be installed. If two or more EditPolicies are able to handle one type of Request, it is not defined, which EditPolicy will be chosen.
Definition at line 247 of file EditPart.cc.
{
    if (editpolicy->host() == NULL) {
        editpolicy->setHost(this);
    }
    editPolicies_.push_back(editpolicy);
}
References editPolicies_, EditPolicy::host(), and EditPolicy::setHost().
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), SocketFactory::createEditPart(), and UnitPortFactory::createEditPart().
model()
TTAMachine::MachinePart * EditPart::model () const
Referenced by ProximPortEditPolicy::canHandle(), ProDePortEditPolicy::canHandle(), ProDeSegmentEditPolicy::canHandle(), ProDeSocketEditPolicy::canHandle(), MachineEditPartFactory::createBiDirBridge(), ProDePortEditPolicy::createConnectCmd(), ProDeSegmentEditPolicy::createConnectCmd(), ProDeSocketEditPolicy::createConnectCmd(), ProximSetMachineWinStatusCmd::Do(), ProximShowPortsCmd::Do(), ProximShowRegistersCmd::Do(), CopyComponent::Do(), DeleteBridgeCmd::Do(), DeleteBusCmd::Do(), DeleteFUCmd::Do(), DeleteGCUCmd::Do(), DeleteIUCmd::Do(), DeletePortCmd::Do(), DeleteRFCmd::Do(), DeleteSegmentCmd::Do(), DeleteSocketCmd::Do(), ModifyBridgeCmd::Do(), ModifyBusCmd::Do(), ModifyFUCmd::Do(), ModifyFUPortCmd::Do(), ModifyGCUCmd::Do(), ModifyIUCmd::Do(), ModifyIUPortCmd::Do(), ModifyRFCmd::Do(), ModifyRFPortCmd::Do(), ModifySocketCmd::Do(), ModifySRPortCmd::Do(), ConnectTool::figure(), find(), ProximBusEditPolicy::getCommand(), ProximFUEditPolicy::getCommand(), ProximIUEditPolicy::getCommand(), ProximPortEditPolicy::getCommand(), ProximRFEditPolicy::getCommand(), ProximSocketEditPolicy::getCommand(), ProDeBridgeEditPolicy::getCommand(), ProDeBusEditPolicy::getCommand(), ProDeFUEditPolicy::getCommand(), ProDeGCUEditPolicy::getCommand(), ProDeIUEditPolicy::getCommand(), ProDePortEditPolicy::getCommand(), ProDeRFEditPolicy::getCommand(), ProDeSegmentEditPolicy::getCommand(), ProDeSocketEditPolicy::getCommand(), ProximMachineStateWindow::onSimulationStop(), and MachineCanvas::select().
operator=()
EditPart & EditPart::operator= (EditPart & old) private
Assignment not allowed.
parent()
EditPart * EditPart::parent () const
Referenced by ProDeSegmentEditPolicy::getCommand(), and MachineCanvas::select().
performRequest()
ComponentCommand * EditPart::performRequest (Request * request) const
If an EditPolicy supporting the given Request is installed to this EditPart, a corresponding Command will be returned or NULL if no EditPolicies supporting the Request is found.
Parameters
request The Request to be performed.
Returns
A command corresponding to the given Request, if an EditPolicy supporting it is installed, NULL otherwise.
Definition at line 297 of file EditPart.cc.
{
    vector<EditPolicy*>::const_iterator i = editPolicies_.begin();
    for (; i != editPolicies_.end(); i++) {
        ComponentCommand* command = (*i)->getCommand(request);
        if (command != NULL) {
            return command;
        }
    }
    return NULL;
}
References editPolicies_.
Referenced by CopyComponentCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), ModifyComponentCmd::Do(), ConnectTool::leftClick(), ProximMachineCanvasTool::onMouseEvent(), SelectTool::onMouseEvent(), ProximMachineStateWindow::onSimulationStop(), and ConnectTool::updateStatusline().
putGarbage()
void EditPart::putGarbage (std::set< EditPart * > & trashbag)
Puts all children and this EditPart to the trashbag.
Parameters
trashbag The trashbag.
Definition at line 87 of file EditPart.cc.
{
    for (unsigned i = 0; i < children_.size(); i++) {
        children_[i]->putGarbage(trashbag);
    }
    trashbag.insert(this);
    garbageCollected_ = true;
}
References children_, and garbageCollected_.
Referenced by RootEditPart::collectTrash().
selectable()
bool EditPart::selectable () const
Referenced by findNearest(), and SelectTool::leftClick().
selected()
bool EditPart::selected () const
setFigure()
void EditPart::setFigure (Figure * figure)
Referenced by MachineEditPartFactory::createBiDirBridge(), SocketBusConnFactory::createConnection(), SocketPortConnFactory::createConnection(), MachineEditPartFactory::createEditPart(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), SocketFactory::createEditPart(), UnitPortFactory::createEditPart(), MachineEditPartFactory::getBusChains(), MachineEditPartFactory::getSockets(), and MachineEditPartFactory::getUnits().
setModel()
void EditPart::setModel (TTAMachine::MachinePart * model)
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), SocketFactory::createEditPart(), UnitPortFactory::createEditPart(), and ModifyBridgeCmd::Do().
setParent()
void EditPart::setParent (EditPart * parent)
Referenced by BusFactory::createEditPart().
setSelectable()
void EditPart::setSelectable (bool selectable)
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SocketFactory::createEditPart(), and UnitPortFactory::createEditPart().
setSelected()
void EditPart::setSelected (bool select)
Referenced by MachineCanvas::clearSelection(), and MachineCanvas::select().
Member Data Documentation
children_
std::vector<EditPart*> EditPart::children_ protected
List of children EditParts.
Definition at line 107 of file EditPart.hh.
Referenced by addChild(), find(), find(), findInRange(), findNearest(), hasEditPartRecursive(), and putGarbage().
editPolicies_
std::vector<EditPolicy*> EditPart::editPolicies_ protected
List of supported EditPolicies.
Definition at line 105 of file EditPart.hh.
Referenced by canHandle(), installEditPolicy(), performRequest(), and ~EditPart().
figure_
Figure* EditPart::figure_ protected
Figure of this EditPart.
Definition at line 93 of file EditPart.hh.
Referenced by addChild(), find(), findInRange(), findNearest(), ConnectionEditPart::setSource(), ConnectionEditPart::setTarget(), and ~EditPart().
garbageCollected_
bool EditPart::garbageCollected_ protected
Helper member to prevent improper deletion.
Definition at line 102 of file EditPart.hh.
Referenced by RootEditPart::collectTrash(), putGarbage(), RootEditPart::setContents(), and ~EditPart().
model_
TTAMachine::MachinePart* EditPart::model_ protected
Machine component corresponding to this EditPart.
Definition at line 95 of file EditPart.hh.
Referenced by find().
parent_
EditPart* EditPart::parent_ protected
Parent of this EditPart.
Definition at line 91 of file EditPart.hh.
selectable_
bool EditPart::selectable_ protected
Tells whether the EditPart is selectable or not.
Definition at line 97 of file EditPart.hh.
Referenced by find(), findInRange(), and findNearest().
selected_
bool EditPart::selected_ protected
Tells whether the EditPart is selected or not.
Definition at line 99 of file EditPart.hh.
The documentation for this class was generated from the following files:
EditPart.hh
EditPart.cc