OpenASIP: HDB::ExternalPort Class Reference
HDB::ExternalPort Class Reference
#include <ExternalPort.hh>
Public Member Functions
ExternalPort (const std::string &name, Direction direction, const std::string &widthFormula, const std::string &description)
virtual ~ExternalPort ()
void setName (const std::string &name)
std::string name () const
void setDirection (Direction direction)
Direction direction () const
void setWidthFormula (const std::string &widthFormula)
std::string widthFormula () const
void setDescription (const std::string &description)
std::string description () const
bool setParameterDependency (const std::string &parameter)
bool unsetParameterDependency (const std::string &parameter)
int parameterDependencyCount () const
std::string parameterDependency (int index) const
Private Types
typedef std::vector< std::string > ParameterTable
Typedef for string vector.
Private Attributes
std::string name_
Name of the port.
Direction direction_
Direction of the port.
std::string widthFormula_
The formula for the width of the port.
std::string description_
Description of the port.
ParameterTable parameterDeps_
Detailed Description
Represents base class for a non-architectural port of an implementation in HDB.
Definition at line 48 of file ExternalPort.hh.
Member Typedef Documentation
ParameterTable
typedef std::vector<std::string> HDB::ExternalPort::ParameterTable private
Typedef for string vector.
Definition at line 73 of file ExternalPort.hh.
Constructor & Destructor Documentation
ExternalPort()
HDB::ExternalPort::ExternalPort (const std::string & name, Direction direction, const std::string & widthFormula, const std::string & description)
The constructor.
Registers the port automatically to the given FUImplementation instance.
Parameters
name Name of the port.
direction Direction of the port.
widthFormula The formula for the width of the port.
description Description of the port.
parent The parent FUImplementation instance.
Definition at line 49 of file ExternalPort.cc.
                                  :
    name_(name), direction_(direction), widthFormula_(widthFormula),
    description_(description) {
}
~ExternalPort()
HDB::ExternalPort::~ExternalPort () virtual
The destructor.
Definition at line 63 of file ExternalPort.cc.
{
}
Member Function Documentation
description()
std::string HDB::ExternalPort::description () const
Returns the description of the port.
Returns
The description.
Definition at line 150 of file ExternalPort.cc.
{
    return description_;
}
References description_.
Referenced by HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), HDBToHtml::rfImplToHtml(), and setDescription().
direction()
Direction HDB::ExternalPort::direction () const
Returns the direction of the port.
Returns
The direction of the port.
Definition at line 106 of file ExternalPort.cc.
{
    return direction_;
}
References direction_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), HDBToHtml::rfImplToHtml(), and setDirection().
name()
std::string HDB::ExternalPort::name () const
Returns the name of the port.
Returns
The name of the port.
Definition at line 84 of file ExternalPort.cc.
{
    return name_;
}
References name_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addFUExternalPortsToImplementation(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFExternalPortsToImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), HDBToHtml::rfImplToHtml(), setName(), RFImplementationDialog::update(), and FUImplementationDialog::update().
parameterDependency()
std::string HDB::ExternalPort::parameterDependency (int index) const
Returns name of a parameter the port is dependent on.
Parameters
index Determines which parameter is returned.
Returns
The name of the parameter.
Exceptions
OutOfRange If the index is negative or not smaller than the number of parameters the port is dependent on.
Definition at line 203 of file ExternalPort.cc.
{
    if (index < 0 || index >= parameterDependencyCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return parameterDeps_[index];
}
References __func__, parameterDependencyCount(), and parameterDeps_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), and HDBToHtml::rfImplToHtml().
parameterDependencyCount()
int HDB::ExternalPort::parameterDependencyCount () const
Returns the number of parameters the port is dependent on.
Returns
The number of parameters.
Definition at line 189 of file ExternalPort.cc.
{
    return parameterDeps_.size();
}
References parameterDeps_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), parameterDependency(), and HDBToHtml::rfImplToHtml().
setDescription()
void HDB::ExternalPort::setDescription (const std::string & description)
Sets description of the port.
Parameters
description The new description.
Definition at line 139 of file ExternalPort.cc.
{
    description_ = description;
}
References description(), and description_.
Referenced by FUExternalPortDialog::onOK(), and RFExternalPortDialog::onOK().
setDirection()
void HDB::ExternalPort::setDirection (Direction direction)
Sets the direction of the port.
Parameters
direction The new direction.
Definition at line 95 of file ExternalPort.cc.
{
    direction_ = direction;
}
References direction(), and direction_.
Referenced by FUExternalPortDialog::onOK(), and RFExternalPortDialog::onOK().
setName()
void HDB::ExternalPort::setName (const std::string & name)
Sets the name of the port.
Parameters
name Name of the port.
Definition at line 73 of file ExternalPort.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by FUExternalPortDialog::onOK(), and RFExternalPortDialog::onOK().
setParameterDependency()
bool HDB::ExternalPort::setParameterDependency (const std::string & parameter)
Sets a parameter dependency for the port.
Parameters
parameter Name of the parameter the port is dependent on.
Returns
True if parameter dependency was added, false if already existed.
Definition at line 162 of file ExternalPort.cc.
{
    if (!ContainerTools::containsValue(parameterDeps_, parameter)) {
        parameterDeps_.push_back(parameter);
        return true;
    }
    return false;
}
References ContainerTools::containsValue(), and parameterDeps_.
Referenced by HDB::HDBManager::addFUExternalPortsToImplementation(), HDB::HDBManager::addRFExternalPortsToImplementation(), FUImplementationDialog::onEditParameter(), RFImplementationDialog::onEditParameter(), FUExternalPortDialog::onOK(), RFExternalPortDialog::onOK(), FUImplementationDialog::onParameterActivation(), and RFImplementationDialog::onParameterActivation().
setWidthFormula()
void HDB::ExternalPort::setWidthFormula (const std::string & widthFormula)
Sets the width formula of the port.
Parameters
widthFormula The new width formula.
Definition at line 117 of file ExternalPort.cc.
{
    widthFormula_ = widthFormula;
}
References widthFormula(), and widthFormula_.
Referenced by FUExternalPortDialog::onOK(), and RFExternalPortDialog::onOK().
unsetParameterDependency()
bool HDB::ExternalPort::unsetParameterDependency (const std::string & parameter)
Unsets the dependency of the given parameter.
Parameters
parameter The parameter.
Returns
True if parameter dependency was removed, false if it didn't exist.
Definition at line 178 of file ExternalPort.cc.
{
    return ContainerTools::removeValueIfExists(parameterDeps_, parameter);
}
References parameterDeps_, and ContainerTools::removeValueIfExists().
Referenced by FUImplementationDialog::onDeleteParameter(), RFImplementationDialog::onDeleteParameter(), FUImplementationDialog::onEditParameter(), RFImplementationDialog::onEditParameter(), FUExternalPortDialog::onOK(), RFExternalPortDialog::onOK(), FUImplementationDialog::onParameterActivation(), and RFImplementationDialog::onParameterActivation().
widthFormula()
std::string HDB::ExternalPort::widthFormula () const
Returns the formula for the width of the port.
Returns
The formula.
Definition at line 128 of file ExternalPort.cc.
{
    return widthFormula_;
}
References widthFormula_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addRFImplementation(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUExternalPortDialog::initialize(), RFExternalPortDialog::initialize(), HDBToHtml::rfImplToHtml(), and setWidthFormula().
Member Data Documentation
description_
std::string HDB::ExternalPort::description_ private
Description of the port.
Definition at line 82 of file ExternalPort.hh.
Referenced by description(), and setDescription().
direction_
Direction HDB::ExternalPort::direction_ private
Direction of the port.
Definition at line 78 of file ExternalPort.hh.
Referenced by direction(), and setDirection().
name_
std::string HDB::ExternalPort::name_ private
Name of the port.
Definition at line 76 of file ExternalPort.hh.
Referenced by name(), and setName().
parameterDeps_
ParameterTable HDB::ExternalPort::parameterDeps_ private
Definition at line 83 of file ExternalPort.hh.
Referenced by parameterDependency(), parameterDependencyCount(), setParameterDependency(), and unsetParameterDependency().
widthFormula_
std::string HDB::ExternalPort::widthFormula_ private
The formula for the width of the port.
Definition at line 80 of file ExternalPort.hh.
Referenced by setWidthFormula(), and widthFormula().
The documentation for this class was generated from the following files:
ExternalPort.hh
ExternalPort.cc