OpenASIP: TTAProgram::Address Class Reference
TTAProgram::Address Class Reference
#include <Address.hh>
Public Member Functions
Address (InstructionAddress location, const TTAMachine::AddressSpace &space)
~Address ()
InstructionAddress location () const
const TTAMachine::AddressSpace & space () const
bool operator== (const Address &other) const
bool operator!= (const Address &other) const
bool operator< (const Address &addr) const
Private Attributes
InstructionAddress location_
The location identified by the address.
const TTAMachine::AddressSpace * space_
The address space of the address.
Detailed Description
An address in the target memory system of the TTA program.
An address is a number that identifies a location in an address space. An address can point to a location of data memory, instruction memory or unified memory.
Definition at line 51 of file Address.hh.
Constructor & Destructor Documentation
Address()
TTAProgram::Address::Address (InstructionAddress location, const TTAMachine::AddressSpace & space)
~Address()
TTAProgram::Address::~Address ()
Member Function Documentation
location()
InstructionAddress TTAProgram::Address::location () const
Referenced by TTAProgram::DataMemory::addDataDefinition(), StaticProgramAnalyzer::addProgram(), TTAProgram::Instruction::address(), TTAProgram::CodeSnippet::address(), TTAProgram::Procedure::address(), TTAProgram::TPEFProgramFactory::build(), SimProgramBuilder::build(), SimulationStatistics::calculate(), CompiledSimUtilizationStats::calculate(), POMValidator::checkCompiledSimulatability(), POMValidator::checkConnectivity(), POMValidator::checkLongImmediates(), POMValidator::checkSimulatability(), TTAProgram::Scope::codeLabel(), TTAProgram::Scope::codeLabelCount(), ControlFlowGraph::computeLeadersFromJumpSuccessors(), ControlFlowGraph::computeLeadersFromRefManager(), ControlFlowGraph::computeLeadersFromRelocations(), TTAProgram::Program::convertSymbolRef(), TTAProgram::BasicBlock::copy(), TTAProgram::Procedure::copy(), TTAProgram::GlobalScope::copyAndRelocate(), ProcedurePass::copyCfgToProcedure(), TTAProgram::Program::copyDataMemoriesFrom(), TTAProgram::Program::copyFrom(), SequentialScheduler::createBasicBlocks(), ControlFlowGraph::createBBEdges(), TTAProgram::ProgramWriter::createBinary(), ControlFlowGraph::createBlock(), TTAProgram::ProgramWriter::createCodeSection(), ControlFlowGraph::createControlFlowEdge(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), ControlFlowGraph::createJumps(), TTAProgram::ProgramWriter::createRelocSections(), SimulatorFrontend::currentProcedure(), TTAProgram::DataMemory::dataDefinition(), TTAProgram::DataMemory::dataDefinitionsEnd(), TTAProgram::Scope::dataLabel(), TTAProgram::Scope::dataLabelCount(), POMDisassembler::destinationLabels(), ControlFlowGraph::directJump(), ProgramDependenceGraph::disassemble(), POMDisassembler::disassemble(), SimulatorFrontend::disassembleInstruction(), POMDisassembler::disassembleProcedure(), POMDisassembler::disassembleProgram(), TTAProgram::CodeSnippet::endAddress(), TTAProgram::TerminalAddress::equals(), DesignSpaceExplorer::evaluate(), DisassembleCommand::execute(), SymbolAddressCommand::execute(), TTAProgram::Program::finalize(), ControlFlowGraph::findNextIndex(), TTASimulationController::findProgramExitPoints(), TTAProgram::ProgramWriter::findSection(), SimulatorFrontend::finishSimulation(), TTAProgram::Program::fixInstructionReferences(), CompiledSimCodeGenerator::generateInstruction(), DisassemblyGridTable::GetNumberRows(), TTAProgram::GlobalScope::globalCodeLabel(), TTAProgram::GlobalScope::globalCodeLabelCount(), TTAProgram::GlobalScope::globalDataLabel(), TTAProgram::GlobalScope::globalDataLabelCount(), ProcedureTransferTracker::handleEvent(), RFAccessTracker::handleEvent(), AbsoluteToRelativeJumps::handleProcedure(), ControlFlowGraph::indirectJump(), SimulatorFrontend::initializeDataMemories(), TTAProgram::CodeSnippet::instructionAt(), TTAProgram::Program::instructionCount(), DisassemblyGridTable::loadProgram(), main(), TTAProgram::DataDefinition::MAU(), CompiledSimulation::moveExecutionCount(), TTAProgram::Program::moveProcedure(), TTAProgram::Program::nextInstruction(), TTAProgram::CodeSnippet::nextInstruction(), SimControlLanguageCommand::parseInstructionAddressExpression(), TTAProgram::CodeSnippet::previousInstruction(), POMDisassembler::printAddress(), SimulatorFrontend::programLocationDescription(), TTAProgram::Procedure::remove(), TTAProgram::Program::removeProcedure(), TTAProgram::Program::replaceUniversalAddressSpaces(), CompiledSimController::reset(), TTAProgram::DataMemory::setAddressSpace(), TTAProgram::GlobalScope::setDataLabelAddressSpace(), SimControlLanguageCommand::setMemoryAddress(), TTAProgram::Program::setStartAddress(), POMDisassembler::startAddress(), DisasmTopCountAttrProvider::updateTopCountTable(), TTAProgram::InstructionReferenceManager::validate(), and TTAProgram::TerminalBasicBlockReference::value().
operator!=()
bool TTAProgram::Address::operator!= (const Address & other) const
Definition at line 46 of file Address.cc.
{
    return !this->operator==(other);
}
References operator==().
operator<()
bool TTAProgram::Address::operator< (const Address & addr) const inline
Definition at line 63 of file Address.hh.
{
        if (location_ < addr.location_) return true;
        if (location_ > addr.location_) return false;
        // The location is equal.
        if (space_ < addr.space_) return true;
        return false;
    }
References location_, and space_.
operator==()
bool TTAProgram::Address::operator== (const Address & other) const
Definition at line 40 of file Address.cc.
{
    return this->location_ == other.location_
        && *this->space_ == *other.space_;
}
References location_, and space_.
Referenced by operator!=().
space()
const TTAMachine::AddressSpace & TTAProgram::Address::space () const
Referenced by TTAProgram::CodeSnippet::address(), TTAProgram::Procedure::address(), TTAProgram::TPEFProgramFactory::build(), TTAProgram::Scope::codeLabel(), TTAProgram::Scope::codeLabelCount(), TTAProgram::Procedure::copy(), TTAProgram::Program::copyFrom(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::ProgramWriter::createRelocSections(), TTAProgram::DataDefinition::DataDefinition(), TTAProgram::DataDefinition::DataDefinition(), TTAProgram::Scope::dataLabel(), TTAProgram::Scope::dataLabelCount(), TTAProgram::CodeSnippet::endAddress(), TTAProgram::TerminalAddress::equals(), TTAProgram::Program::finalize(), TTAProgram::ProgramWriter::findSection(), TTAProgram::GlobalScope::globalCodeLabel(), TTAProgram::GlobalScope::globalCodeLabelCount(), TTAProgram::GlobalScope::globalDataLabel(), TTAProgram::GlobalScope::globalDataLabelCount(), SimulatorFrontend::initializeDataMemories(), TTAProgram::DataDefinition::MAU(), TTAProgram::Program::moveProcedure(), TTAProgram::Program::replaceUniversalAddressSpaces(), SimControlLanguageCommand::setMemoryAddress(), and TTAProgram::Program::targetProcessor().
Member Data Documentation
location_
InstructionAddress TTAProgram::Address::location_ private
The location identified by the address.
Definition at line 76 of file Address.hh.
Referenced by operator<(), and operator==().
space_
const TTAMachine::AddressSpace* TTAProgram::Address::space_ private
The address space of the address.
Definition at line 78 of file Address.hh.
Referenced by operator<(), and operator==().
The documentation for this class was generated from the following files:
Address.hh
Address.cc