OpenASIP: TesterContext Class Reference
TesterContext Class Reference
#include <TestOsal.hh>
Public Member Functions
TesterContext ()
virtual ~TesterContext ()
void stop ()
bool cont () const
OperationContext & operationContext ()
std::string outputFormat () const
void setOutputFormat (std::string outputFormat)
std::string toOutputFormat (SimValue *value)
InstructionAddress & programCounter ()
SimValue & returnAddress ()
SimValue & syscallHandler ()
SimValue & syscallNumber ()
Public Member Functions inherited from InterpreterContext
InterpreterContext ()
virtual ~InterpreterContext ()
Private Attributes
bool continue_
Flag indicating whether program can continue or not.
SimValue returnAddressStorage_
InstructionAddress programCounterStorage_
InstructionAddress irfStartStorage_
int branchDelayCycles_
std::string outputFormat_
Indicates which output format is used currently.
OperationContext opContext_
The operation context shared with all operations invoked in the application.
Detailed Description
Operation context for the program.
Definition at line 212 of file TestOsal.hh.
Constructor & Destructor Documentation
TesterContext()
TesterContext::TesterContext ()
Constructor.
Definition at line 412 of file TestOsal.cc.
                             :
    InterpreterContext(), continue_(true), programCounterStorage_(0),
    irfStartStorage_(0), branchDelayCycles_(3),
    outputFormat_(CmdOutput::OUTPUT_FORMAT_INT_SIGNED),
    opContext_(NULL, programCounterStorage_, returnAddressStorage_,
               branchDelayCycles_) {
}
~TesterContext()
TesterContext::~TesterContext () virtual
Destructor.
Definition at line 424 of file TestOsal.cc.
{
}
Member Function Documentation
cont()
bool TesterContext::cont () const
Return true, if program can continue, false otherwise.
Returns
True if program can continue, false otherwise.
Definition at line 441 of file TestOsal.cc.
{
    return continue_;
}
References continue_.
Referenced by main().
operationContext()
OperationContext & TesterContext::operationContext ()
Returns the operation context shared with all operations invoked in the application.
Returns
The operations context shared with all operations invoked in the application.
Definition at line 453 of file TestOsal.cc.
{
    return opContext_;
}
References opContext_.
Referenced by main(), and OsalInterpreter::operation().
outputFormat()
string TesterContext::outputFormat () const
Returns the output format currently in use.
Returns
The output format currently in use.
Definition at line 463 of file TestOsal.cc.
{
    return outputFormat_;
}
References outputFormat_.
Referenced by setOutputFormat().
programCounter()
InstructionAddress & TesterContext::programCounter ()
Returns the program counter as SimValue.
Returns
Program counter as SimValue.
Definition at line 527 of file TestOsal.cc.
{
    return opContext_.programCounter();
}
References opContext_, and OperationContext::programCounter().
returnAddress()
SimValue & TesterContext::returnAddress ()
Returns the return address as SimValue.
Returns
Return address as SimValue.
Definition at line 537 of file TestOsal.cc.
{
    return opContext_.returnAddress();
}
References opContext_, and OperationContext::returnAddress().
setOutputFormat()
void TesterContext::setOutputFormat (std::string outputFormat)
Sets the output format to be used in the future.
Parameters
The output format to be used in the future.
Definition at line 473 of file TestOsal.cc.
{
    outputFormat_ = outputFormat;
}
References outputFormat(), and outputFormat_.
stop()
void TesterContext::stop ()
Sets the continue_ flag off.
Definition at line 431 of file TestOsal.cc.
                    {
    continue_ = false;
}
References continue_.
Referenced by CmdQuit::execute().
syscallHandler()
SimValue & TesterContext::syscallHandler ()
syscallNumber()
SimValue & TesterContext::syscallNumber ()
toOutputFormat()
string TesterContext::toOutputFormat (SimValue * value)
Converts given SimValue to output string.
Parameters
value Value to be converted.
Returns
The value of SimValue as a string.
Definition at line 484 of file TestOsal.cc.
{
    string output = "";
    // If output format is in hex or the value is wider than 64 bits
    // convert the SimValue to hex using the full
    // width of the value. This means that leading zeroes are included in
    // the output result (e.g. 32 bit value 0x15 = 0x00000015).
    if (outputFormat_ == CmdOutput::OUTPUT_FORMAT_HEX ||
        value->width() > 64) {
        output = value->hexValue();
    } else if (outputFormat_ == CmdOutput::OUTPUT_FORMAT_INT_SIGNED ||
               outputFormat_ == CmdOutput::OUTPUT_FORMAT_LONG_SIGNED) {
        output = Conversion::toString(value->sLongWordValue());
    } else if(outputFormat_ == CmdOutput::OUTPUT_FORMAT_INT_UNSIGNED ||
              outputFormat_ == CmdOutput::OUTPUT_FORMAT_LONG_UNSIGNED) {
        output = Conversion::toString(value->uLongWordValue());
    } else if(outputFormat_ == CmdOutput::OUTPUT_FORMAT_DOUBLE) {
        DoubleWord doubleWord = value->doubleWordValue();
        output = Conversion::toString(doubleWord);
    } else if(outputFormat_ == CmdOutput::OUTPUT_FORMAT_FLOAT) {
        FloatWord floatWord = value->floatWordValue();
        output = Conversion::toString(floatWord);
    } else if(outputFormat_ == CmdOutput::OUTPUT_FORMAT_HALF) {
        HalfFloatWord halfFloatWord = value->halfFloatWordValue();
        output = Conversion::toString(FloatWord(float(halfFloatWord)));
    } else if(outputFormat_ == CmdOutput::OUTPUT_FORMAT_BIN) {
        output = value->binaryValue();
        output += 'b';
    }
    return output;
}
References SimValue::binaryValue(), SimValue::doubleWordValue(), SimValue::floatWordValue(), SimValue::halfFloatWordValue(), SimValue::hexValue(), CmdOutput::OUTPUT_FORMAT_BIN, CmdOutput::OUTPUT_FORMAT_DOUBLE, CmdOutput::OUTPUT_FORMAT_FLOAT, CmdOutput::OUTPUT_FORMAT_HALF, CmdOutput::OUTPUT_FORMAT_HEX, CmdOutput::OUTPUT_FORMAT_INT_SIGNED, CmdOutput::OUTPUT_FORMAT_INT_UNSIGNED, CmdOutput::OUTPUT_FORMAT_LONG_SIGNED, CmdOutput::OUTPUT_FORMAT_LONG_UNSIGNED, outputFormat_, SimValue::sLongWordValue(), Conversion::toString(), SimValue::uLongWordValue(), and SimValue::width().
Member Data Documentation
branchDelayCycles_
int TesterContext::branchDelayCycles_ private
Definition at line 234 of file TestOsal.hh.
continue_
bool TesterContext::continue_ private
Flag indicating whether program can continue or not.
Definition at line 230 of file TestOsal.hh.
Referenced by cont(), and stop().
irfStartStorage_
InstructionAddress TesterContext::irfStartStorage_ private
Definition at line 233 of file TestOsal.hh.
opContext_
OperationContext TesterContext::opContext_ private
The operation context shared with all operations invoked in the application.
Definition at line 239 of file TestOsal.hh.
Referenced by operationContext(), programCounter(), and returnAddress().
outputFormat_
std::string TesterContext::outputFormat_ private
Indicates which output format is used currently.
Definition at line 236 of file TestOsal.hh.
Referenced by outputFormat(), setOutputFormat(), and toOutputFormat().
programCounterStorage_
InstructionAddress TesterContext::programCounterStorage_ private
Definition at line 232 of file TestOsal.hh.
returnAddressStorage_
SimValue TesterContext::returnAddressStorage_ private
Definition at line 231 of file TestOsal.hh.
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc