OpenASIP: ProximResumeCmd Class Reference
ProximResumeCmd Class Reference
#include <ProximResumeCmd.hh>
Public Member Functions
ProximResumeCmd ()
virtual ~ProximResumeCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximResumeCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Attributes
SimulatorFrontend * simulator_
Detailed Description
Command for resuming simulation in Proxim until the simulation is finished or a breakpoint is reacehed.
Definition at line 44 of file ProximResumeCmd.hh.
Constructor & Destructor Documentation
ProximResumeCmd()
ProximResumeCmd::ProximResumeCmd ()
The Constructor.
Definition at line 42 of file ProximResumeCmd.cc.
                                :
    GUICommand(ProximConstants::COMMAND_NAME_RESUME, NULL) {
    simulator_ = wxGetApp().simulation()->frontend();
}
References simulator_.
Referenced by create().
~ProximResumeCmd()
ProximResumeCmd::~ProximResumeCmd () virtual
The Destructor.
Definition at line 51 of file ProximResumeCmd.cc.
{
}
Member Function Documentation
create()
ProximResumeCmd * ProximResumeCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 91 of file ProximResumeCmd.cc.
{
    return new ProximResumeCmd();
}
References ProximResumeCmd().
Do()
bool ProximResumeCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 59 of file ProximResumeCmd.cc.
                    {
    wxGetApp().simulation()->lineReader().input("resume");
    return true;
}
icon()
std::string ProximResumeCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 71 of file ProximResumeCmd.cc.
{
    return "resume.png";
}
id()
int ProximResumeCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 80 of file ProximResumeCmd.cc.
{
    return ProximConstants::COMMAND_RESUME;
}
References ProximConstants::COMMAND_RESUME.
isEnabled()
bool ProximResumeCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
True if the simulation is stopped but not finished.
Implements GUICommand.
Definition at line 102 of file ProximResumeCmd.cc.
{
    if (simulator_ != NULL && simulator_->isSimulationStopped()) {
    return true;
    } else {
    return false;
    }
}
References SimulatorFrontend::isSimulationStopped(), and simulator_.
Member Data Documentation
simulator_
SimulatorFrontend* ProximResumeCmd::simulator_ private
Definition at line 55 of file ProximResumeCmd.hh.
Referenced by isEnabled(), and ProximResumeCmd().
The documentation for this class was generated from the following files:
ProximResumeCmd.hh
ProximResumeCmd.cc