OpenASIP: SoftwareBypasser Class Reference
SoftwareBypasser Class Reference abstract
#include <SoftwareBypasser.hh>
Public Member Functions
SoftwareBypasser ()
virtual ~SoftwareBypasser ()
virtual int bypass (MoveNodeGroup &candidates, DataDependenceGraph &ddg, ResourceManager &rm, bool bypassTrigger)=0
virtual int bypassNode (MoveNode &moveNode, int &lastOperandCycle, DataDependenceGraph &ddg, ResourceManager &rm)=0
virtual void removeBypass (MoveNodeGroup &candidates, DataDependenceGraph &ddg, ResourceManager &rm)=0
virtual void removeBypass (MoveNode &moveNode, DataDependenceGraph &ddg, ResourceManager &rm, bool restoreSource=true)=0
virtual int removeDeadResults (MoveNodeGroup &candidates, DataDependenceGraph &ddg, ResourceManager &rm, std::set< std::pair< TTAProgram::Move *, int > > &removedMoves)=0
virtual void setSelector (MoveNodeSelector *selector)
virtual void clearCaches (DataDependenceGraph &ddg, bool removeDeadResults)=0
int bypassCount ()
int deadResultCount ()
Protected Attributes
int bypassCount_
int deadResultCount_
Detailed Description
Classes that implement this interface are able to software bypass moves.
Definition at line 52 of file SoftwareBypasser.hh.
Constructor & Destructor Documentation
SoftwareBypasser()
SoftwareBypasser::SoftwareBypasser ()
Empty constructor.
Definition at line 42 of file SoftwareBypasser.cc.
                                   : bypassCount_(0), deadResultCount_(0){
}
~SoftwareBypasser()
SoftwareBypasser::~SoftwareBypasser () virtual
Empty destructor.
Definition at line 48 of file SoftwareBypasser.cc.
{
}
Member Function Documentation
bypass()
int SoftwareBypasser::bypass (MoveNodeGroup & candidates, DataDependenceGraph & ddg, ResourceManager & rm, bool bypassTrigger) pure virtual
Apply software bypassing to as many moves in the given MoveNodeGroup as possible.
The given DDG can be used to inspect whether software bypassing is possible.
Parameters
candidates The moves to which apply software bypassing, if possible.
ddg The data dependence grap in which the movenodes belong to.
rm The resource manager which is used to check for resource availability.
bypassTrigger whether to bypass the trigger or not.
Returns
The count of bypassed moves.
Implemented in CycleLookBackSoftwareBypasser.
Definition at line 65 of file SoftwareBypasser.cc.
            {
    // use the arguments just to avoid compiler warnings with strict flags
    candidates.nodeCount();
    ddg.nodeCount();
    rm.machine();
    return 0;
}
References ResourceManager::machine(), MoveNodeGroup::nodeCount(), and BoostGraph< GraphNode, GraphEdge >::nodeCount().
Referenced by BasicBlockScheduler::scheduleOperation().
bypassCount()
int SoftwareBypasser::bypassCount () inline
Definition at line 89 of file SoftwareBypasser.hh.
{ return bypassCount_; }
References bypassCount_.
bypassNode()
virtual int SoftwareBypasser::bypassNode (MoveNode & moveNode, int & lastOperandCycle, DataDependenceGraph & ddg, ResourceManager & rm) pure virtual
Implemented in CycleLookBackSoftwareBypasser.
Referenced by BasicBlockScheduler::handleDDG().
clearCaches()
virtual void SoftwareBypasser::clearCaches (DataDependenceGraph & ddg, bool removeDeadResults) pure virtual
Implemented in CycleLookBackSoftwareBypasser.
Referenced by BasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleLoopDDG(), and BasicBlockScheduler::unscheduleAllNodes().
deadResultCount()
int SoftwareBypasser::deadResultCount () inline
Definition at line 90 of file SoftwareBypasser.hh.
{ return deadResultCount_; }
References deadResultCount_.
removeBypass() [1/2]
virtual void SoftwareBypasser::removeBypass (MoveNode & moveNode, DataDependenceGraph & ddg, ResourceManager & rm, bool restoreSource = true) pure virtual
Implemented in CycleLookBackSoftwareBypasser.
removeBypass() [2/2]
void SoftwareBypasser::removeBypass (MoveNodeGroup & candidates, DataDependenceGraph & ddg, ResourceManager & rm) pure virtual
Remove software bypassing from as many moves in the given MoveNodeGroup as possible.
Parameters
candidates The moves from which to remove software bypassing, if possible.
ddg The data dependence grap in which the movenodes belong to.
rm The resource manager which is used to check for resource availability.
Implemented in CycleLookBackSoftwareBypasser.
Definition at line 89 of file SoftwareBypasser.cc.
{
    // use the arguments just to avoid compiler warnings with strict flags
    candidates.nodeCount();
    ddg.nodeCount();
    rm.machine();
    return;
}
References ResourceManager::machine(), MoveNodeGroup::nodeCount(), and BoostGraph< GraphNode, GraphEdge >::nodeCount().
Referenced by BasicBlockScheduler::handleDDG(), BasicBlockScheduler::scheduleOperation(), and BasicBlockScheduler::unscheduleAllNodes().
removeDeadResults()
int SoftwareBypasser::removeDeadResults (MoveNodeGroup & candidates, DataDependenceGraph & ddg, ResourceManager & rm, std::set< std::pair< TTAProgram::Move *, int > > & removedMoves) pure virtual
Remove dead result moves for each bypassed move of given MoveNodeGroup if possible. That is, no other result reads of result exists. This assumes that result moves in MoveNodeGroup are also scheduled.
Parameters
candidates The moves for which remove dead result writes
ddg The data dependence grap in which the movenodes belong to.
rm The resource manager which is used to check for resource availability.
removedMoves The dead result eliminated moves and their original cycles, to allow rescheduling of moves that were previously resource (RF write port usually) constrained by the removed moves.
Returns
number of dead results killed
Implemented in CycleLookBackSoftwareBypasser.
Definition at line 116 of file SoftwareBypasser.cc.
{
    // use the arguments just to avoid compiler warnings with strict flags
    candidates.nodeCount();
    ddg.nodeCount();
    rm.machine();
    removedMoves.begin();
    return 0;
}
References ResourceManager::machine(), MoveNodeGroup::nodeCount(), and BoostGraph< GraphNode, GraphEdge >::nodeCount().
Referenced by BasicBlockScheduler::handleDDG(), and BasicBlockScheduler::scheduleOperation().
setSelector()
void SoftwareBypasser::setSelector (MoveNodeSelector * selector) virtual
Reimplemented in CycleLookBackSoftwareBypasser.
Definition at line 143 of file SoftwareBypasser.cc.
{
}
Referenced by BasicBlockScheduler::handleDDG(), and BasicBlockScheduler::handleLoopDDG().
Member Data Documentation
bypassCount_
int SoftwareBypasser::bypassCount_ protected
Definition at line 92 of file SoftwareBypasser.hh.
Referenced by bypassCount().
deadResultCount_
int SoftwareBypasser::deadResultCount_ protected
Definition at line 93 of file SoftwareBypasser.hh.
Referenced by deadResultCount().
The documentation for this class was generated from the following files:
SoftwareBypasser.hh
SoftwareBypasser.cc