OpenASIP: AssocTools Class Reference
AssocTools Class Reference
#include <AssocTools.hh>
Static Public Member Functions
template<typename ContainerType >
static void deleteAllItems (ContainerType &aMap)
template<typename ContainerType >
static void deleteAllValues (ContainerType &aMap)
template<typename ContainerType , typename KeyType >
static bool containsKey (const ContainerType &aContainer, const KeyType &aKey)
template<typename ContainerType >
static void difference (const ContainerType &firstContainer, const ContainerType &secondContainer, ContainerType &difference)
template<typename ContainerType1 , typename ContainerType2 >
static std::set< std::pair< typename ContainerType1::value_type, typename ContainerType2::value_type > > pairs (ContainerType1 &firstContainer, ContainerType2 &secondContainer)
template<typename Comparator , typename ContainerType1 , typename ContainerType2 >
static std::set< std::pair< typename ContainerType1::value_type, typename ContainerType2::value_type >, Comparator > pairs (ContainerType1 &firstContainer, ContainerType2 &secondContainer)
template<typename ContainerType >
static void append (const ContainerType &src, ContainerType &dest)
Detailed Description
Definition at line 43 of file AssocTools.hh.
Member Function Documentation
append()
template<typename ContainerType > static void AssocTools::append (const ContainerType & src, ContainerType & dest) static
Referenced by BF2ScheduleFront::appendBypassSources(), RegisterRenamer::findPartiallyUsedRegistersAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersBeforeCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFBeforeCycle(), ControlFlowGraph::findReachableNodes(), CopyingDelaySlotFiller::tryToFillSlots(), DataDependenceGraphBuilder::updateMemAndFuAliveAfter(), and DataDependenceGraphBuilder::updatePreceedingRegistersUsedAfter().
containsKey()
template<typename ContainerType , typename KeyType > static bool AssocTools::containsKey (const ContainerType & aContainer, const KeyType & aKey) static
Referenced by CostDatabaseRegistry::addCostDatabase(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), HDB::HDBRegistry::addHDB(), BEMGenerator::addLongImmDstRegisterFields(), BEMGenerator::addPortCodes(), InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), llvm::LLVMTCEIRBuilder::buildTCECFG(), MachineConnectivityCheck::busConnectedToAnyFU(), BEMValidator::checkLImmDstRegisterFields(), TTAMachine::ExecutionPipeline::checkOperandAvailability(), TTAMachine::ExecutionPipeline::checkResourceAvailability(), CopyingDelaySlotFiller::collectMoves(), ProgramDependenceGraph::compareSiblings(), ControlDependenceGraph::compareSiblings(), ProGe::Netlist::connect(), ProGe::Netlist::connectGroupByName(), ControlFlowGraph::copyToLLVMMachineFunction(), CostDatabaseRegistry::costDatabase(), RegisterQuantityCheck::countIntRegisters(), TTAMachine::Unit::deleteOtherPorts(), ResourceConstraintAnalyzer::dumpGraphWithStats(), MoveNodeDuplicator::duplicateMove(), MoveNodeDuplicator::duplicateMoveNode(), MoveNodeDuplicator::duplicateProgramOperationPtr(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeLongImmediate(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), ControlFlowGraph::findReachableNodes(), RegisterCopyAdder::findTempRegisters(), ControlFlowGraph::findUnreachableNodes(), TTAMachine::ExecutionPipeline::firstCycleWithoutOperandUse(), TTAMachine::ExecutionPipeline::firstCycleWithoutResource(), TTAMachine::ExecutionPipeline::firstCycleWithoutResource(), CompiledSimCodeGenerator::generateInstruction(), CopyingDelaySlotFiller::getMove(), CopyingDelaySlotFiller::getMoveNode(), CopyingDelaySlotFiller::getProgramOperationPtr(), MachineConnectivityCheck::hasConditionalMoves(), CostDatabaseRegistry::hasCostDatabase(), HDB::FUArchitecture::hasGuardSupport(), HDB::HDBRegistry::hasHDB(), TTAMachine::AddressSpace::hasNumericalId(), HDB::FUArchitecture::hasParameterizedWidth(), DataDependenceGraph::hasRegWaw(), HDB::HDBRegistry::hdb(), RegisterRenamer::initialize(), CodeCompressorPlugin::initializeRelocations(), TPEF::ReferenceManager::SafePointer::isAlive(), ProGe::BlockSourceCopier::isCopied(), FalseAliasAnalyzer::isEnabled(), llvm::LLVMTCEIRBuilder::isHotFunction(), TTAMachine::ExecutionPipeline::isOperandRead(), TTAMachine::ExecutionPipeline::isOperandWritten(), MachineConnectivityCheck::isPortApplicableToWidths(), TTAMachine::ExecutionPipeline::isResourceUsed(), TTAMachine::ExecutionPipeline::latency(), HDB::HDBRegistry::loadFromSearchPaths(), ProgramDependenceGraph::moveDDGedges(), ProximDisassemblyWindow::onMappedMenuCommand(), BFPushMoveUp2::operator()(), ProgramDependenceGraph::SubgraphTypeTest< NodeSetType, GraphType >::operator()(), DataDependenceGraph::otherSuccessorsScheduled(), ProGe::PortFactory::registerPort(), ProGe::PortFactory::registerPortGroup(), RegisterRenamer::registersOfRFs(), TTAMachine::ResourceVectorSet::resourceVector(), TTAMachine::Bridge::setFirstOfChain(), DataDependenceGraph::setMachine(), TTAMachine::AddressSpace::setNumericalIds(), TTAMachine::ExecutionPipeline::slack(), CodeCompressorPlugin::startsAtBeginningOfMAU(), MachineConnectivityCheck::tempRegisterFiles(), ProGe::VHDLNetlistWriter::writeComponentDeclarations(), ProGe::VerilogNetlistWriter::writeSignalAssignments(), and ProGe::VHDLNetlistWriter::writeSignalAssignments().
deleteAllItems()
template<typename ContainerType > static void AssocTools::deleteAllItems (ContainerType & aMap) static
Referenced by TPEF::ReferenceManager::SafePointer::cleanupKeyTables(), CopyingDelaySlotFiller::finalizeProcedure(), AssignmentPlan::~AssignmentPlan(), and TTAMachine::Socket::~Socket().
deleteAllValues()
template<typename ContainerType > static void AssocTools::deleteAllValues (ContainerType & aMap) static
Referenced by OperationPoolPimpl::cleanupCache(), SimpleBrokerDirector::clearOldResources(), DataDependenceGraphBuilder::createMemAndFUstateDeps(), DataDependenceGraphBuilder::createRegisterDeps(), DataDependenceGraphBuilder::searchRegisterDeaths(), CostDatabaseRegistry::~CostDatabaseRegistry(), FUFiniteStateAutomaton::~FUFiniteStateAutomaton(), HDB::HDBRegistry::~HDBRegistry(), OperationIndex::~OperationIndex(), ProgramOperation::~ProgramOperation(), and TTAMachine::ResourceVectorSet::~ResourceVectorSet().
difference()
template<typename ContainerType > static void AssocTools::difference (const ContainerType & firstContainer, const ContainerType & secondContainer, ContainerType & difference) static
Referenced by HDB::HDBManager::areCompatiblePipelines(), and HDB::FUArchitecture::operator==().
pairs() [1/2]
template<typename ContainerType1 , typename ContainerType2 > static std::set< std::pair< typename ContainerType1::value_type, typename ContainerType2::value_type > > AssocTools::pairs (ContainerType1 & firstContainer, ContainerType2 & secondContainer) static
pairs() [2/2]
template<typename Comparator , typename ContainerType1 , typename ContainerType2 > static std::set< std::pair< typename ContainerType1::value_type, typename ContainerType2::value_type >, Comparator > AssocTools::pairs (ContainerType1 & firstContainer, ContainerType2 & secondContainer) static
The documentation for this class was generated from the following file:
AssocTools.hh