OpenASIP: OsalInterpreter Class Reference
OsalInterpreter Class Reference
#include <TestOsal.hh>
Public Member Functions
OsalInterpreter ()
virtual ~OsalInterpreter ()
Operation & operation (const std::string &name)
Public Member Functions inherited from SimpleScriptInterpreter
SimpleScriptInterpreter ()
virtual ~SimpleScriptInterpreter ()
virtual void initialize (int argc, char *argv[], InterpreterContext *context, LineReader *reader)
virtual void setVariableToInterpreter (const std::string &name, const DataObject &value)
virtual DataObject variable (const std::string &name)
virtual bool interpret (const std::string &commandLine)
virtual void setResultToInterpreter (const DataObject &value)
virtual InterpreterContext & context () const
Public Member Functions inherited from ScriptInterpreter
ScriptInterpreter ()
virtual ~ScriptInterpreter ()
virtual void addCustomCommand (CustomCommand *command)
virtual void removeCustomCommand (const std::string &commandName)
virtual CustomCommand * customCommand (const std::string &commandName)
virtual void setResult (DataObject *result)
virtual void setResult (const std::string &result)
virtual void setResult (int result)
virtual void setResult (double result)
virtual std::string result ()
virtual void setError (bool state)
virtual void setError (std::string errorMessage)
virtual bool error () const
virtual void setVariable (const std::string &interpreterVariableName, const std::string &value)
virtual void setVariable (const std::string &interpreterVariableName, int value)
virtual std::string variableStringValue (const std::string &interpreterVariableName)
virtual int variableIntegerValue (const std::string &interpreterVariableName)
virtual bool processScriptFile (const std::string &scriptFileName)
virtual void finalize ()
virtual void setLineReader (LineReader *reader)
virtual LineReader * lineReader () const
std::vector< std::string > customCommandsSortedByName ()
Private Attributes
OperationPool * pool_
Used to load operations.
Operation * operation_
Last loaded operation.
Additional Inherited Members
Protected Member Functions inherited from SimpleScriptInterpreter
virtual void addCustomCommandToInterpreter (const CustomCommand &command)
virtual void removeCustomCommandFromInterpreter (const CustomCommand &command)
Detailed Description
Interpreter for test_osal.
Definition at line 249 of file TestOsal.hh.
Constructor & Destructor Documentation
OsalInterpreter()
OsalInterpreter::OsalInterpreter ()
Constructor.
Definition at line 369 of file TestOsal.cc.
                                 : SimpleScriptInterpreter() {
    pool_ = new OperationPool();
    operation_ = &NullOperation::instance();
}
References NullOperation::instance(), operation_, and pool_.
~OsalInterpreter()
OsalInterpreter::~OsalInterpreter () virtual
Destructor.
Definition at line 377 of file TestOsal.cc.
{
    delete pool_;
}
References pool_.
Member Function Documentation
operation()
Operation & OsalInterpreter::operation (const std::string & name)
Loads an operation and return a reference to it.
Parameters
name The name of the operation.
Returns
The reference to operation.
Definition at line 388 of file TestOsal.cc.
{
    if (operation_ == &NullOperation::instance() ||
        operation_->name() != name) {
        operation_ = &(pool_->operation(name.c_str()));
    }
    TesterContext& testCont = *dynamic_cast<TesterContext*>(&context());
    OperationContext& opContext = testCont.operationContext();
    if (operation_ != &NullOperation::instance()) {
        OperationBehavior& beh = operation_->behavior();
        beh.createState(opContext);
    }
    return *operation_;
}
References Operation::behavior(), SimpleScriptInterpreter::context(), OperationBehavior::createState(), NullOperation::instance(), Operation::name(), OperationPool::operation(), operation_, TesterContext::operationContext(), and pool_.
Referenced by CmdTrigger::execute(), and CmdReset::execute().
Member Data Documentation
operation_
Operation* OsalInterpreter::operation_ private
Last loaded operation.
Definition at line 260 of file TestOsal.hh.
Referenced by operation(), and OsalInterpreter().
pool_
OperationPool* OsalInterpreter::pool_ private
Used to load operations.
Definition at line 258 of file TestOsal.hh.
Referenced by operation(), OsalInterpreter(), and ~OsalInterpreter().
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc