OpenASIP: EditTemplatesCmd Class Reference
EditTemplatesCmd Class Reference
#include <EditTemplatesCmd.hh>
Public Member Functions
EditTemplatesCmd ()
virtual ~EditTemplatesCmd ()
virtual bool Do ()
virtual int id () const
virtual EditTemplatesCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for editing instruction templates.
Opens a TemplateListDialog which lists instruction templates in the machine.
Definition at line 43 of file EditTemplatesCmd.hh.
Constructor & Destructor Documentation
EditTemplatesCmd()
EditTemplatesCmd::EditTemplatesCmd ()
The Constructor.
Definition at line 52 of file EditTemplatesCmd.cc.
                                  :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_TEMPLATES) {
}
Referenced by create().
~EditTemplatesCmd()
EditTemplatesCmd::~EditTemplatesCmd () virtual
The Destructor.
Definition at line 60 of file EditTemplatesCmd.cc.
{}
Member Function Documentation
create()
EditTemplatesCmd * EditTemplatesCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
A new instance of this command.
Implements GUICommand.
Definition at line 109 of file EditTemplatesCmd.cc.
{
    return new EditTemplatesCmd();
}
References EditTemplatesCmd().
Do()
bool EditTemplatesCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 69 of file EditTemplatesCmd.cc.
                     {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    TemplateListDialog dialog(parentWindow(), model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, templates are not modified.
    model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string EditTemplatesCmd::icon () const virtual
Returns path to the command's icon file.
Returns
path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 121 of file EditTemplatesCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_TEMPLATES;
}
References ProDeConstants::CMD_ICON_EDIT_TEMPLATES.
id()
int EditTemplatesCmd::id () const virtual
Returns id of this command.
Returns
Id of this command.
Implements GUICommand.
Definition at line 98 of file EditTemplatesCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_TEMPLATES;
}
References ProDeConstants::COMMAND_EDIT_TEMPLATES.
isEnabled()
bool EditTemplatesCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 145 of file EditTemplatesCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string EditTemplatesCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short version of the command name.
Reimplemented from GUICommand.
Definition at line 132 of file EditTemplatesCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_TEMPLATES;
}
References ProDeConstants::CMD_SNAME_EDIT_TEMPLATES.
The documentation for this class was generated from the following files:
EditTemplatesCmd.hh
EditTemplatesCmd.cc