OpenASIP: VerifyMachineCmd Class Reference
VerifyMachineCmd Class Reference
#include <VerifyMachineCmd.hh>
Public Member Functions
VerifyMachineCmd ()
virtual ~VerifyMachineCmd ()
virtual bool Do ()
virtual int id () const
virtual VerifyMachineCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
wxCommand for editing connections.
Definition at line 42 of file VerifyMachineCmd.hh.
Constructor & Destructor Documentation
VerifyMachineCmd()
VerifyMachineCmd::VerifyMachineCmd ()
The Constructor.
Definition at line 47 of file VerifyMachineCmd.cc.
                                  :
    EditorCommand(ProDeConstants::CMD_NAME_VERIFY_MACHINE) {
}
Referenced by create().
~VerifyMachineCmd()
VerifyMachineCmd::~VerifyMachineCmd () virtual
The Destructor.
Definition at line 56 of file VerifyMachineCmd.cc.
{}
Member Function Documentation
create()
VerifyMachineCmd * VerifyMachineCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 93 of file VerifyMachineCmd.cc.
{
    return new VerifyMachineCmd();
}
References VerifyMachineCmd().
Do()
bool VerifyMachineCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file VerifyMachineCmd.cc.
                     {
    wxString errorMessages;
    const TTAMachine::Machine* machine = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel()->getMachine();
    ValidateMachineDialog dialog(parentWindow(), *machine);
    dialog.ShowModal();
    return true;
}
References machine, GUICommand::parentWindow(), and EditorCommand::view().
icon()
string VerifyMachineCmd::icon () const virtual
Returns path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 103 of file VerifyMachineCmd.cc.
{
    return ProDeConstants::CMD_ICON_VERIFY_MACHINE;
}
References ProDeConstants::CMD_ICON_VERIFY_MACHINE.
id()
int VerifyMachineCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 84 of file VerifyMachineCmd.cc.
{
    return ProDeConstants::COMMAND_VERIFY_MACHINE;
}
References ProDeConstants::COMMAND_VERIFY_MACHINE.
isEnabled()
bool VerifyMachineCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 125 of file VerifyMachineCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string VerifyMachineCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 112 of file VerifyMachineCmd.cc.
{
    return ProDeConstants::CMD_SNAME_VERIFY_MACHINE;
}
References ProDeConstants::CMD_SNAME_VERIFY_MACHINE.
The documentation for this class was generated from the following files:
VerifyMachineCmd.hh
VerifyMachineCmd.cc