OpenASIP: DataObject Class Reference
DataObject Class Reference
#include <DataObject.hh>
Public Types
enum OrigType {
TYPE_INT , TYPE_STRING , TYPE_DOUBLE , TYPE_FLOAT ,
TYPE_NULL , TYPE_NOTYPE
}
Public Member Functions
DataObject ()
DataObject (int value)
DataObject (SLongWord value)
DataObject (double value)
DataObject (const std::string value)
virtual ~DataObject ()
virtual int integerValue () const
virtual void setInteger (int value)
virtual void setLong (SLongWord value)
virtual SLongWord longValue () const
virtual std::string stringValue () const
virtual void setString (std::string value)
virtual double doubleValue () const
virtual void setDouble (double value)
virtual float floatValue () const
virtual void setFloat (float value)
virtual bool boolValue () const
virtual void setBool (bool value)
virtual bool isNull () const
virtual void setNull ()
virtual bool operator!= (const DataObject &object) const
Protected Member Functions
OrigType type () const
bool intFresh () const
bool stringFresh () const
bool doubleFresh () const
bool floatFresh () const
Private Attributes
OrigType type_
The type of value in which DataObject was last assigned.
bool intFresh_
Flag indicating that the value of integer is up-to-date.
bool stringFresh_
Flag indicating that the value of string is up-to-date.
bool doubleFresh_
Flag indicating that the value of double is up-to-date.
bool floatFresh_
Flag indicating that the value of float is up-to-date.
SLongWord intValue_
Value as integer.
std::string stringValue_
Value as string.
double doubleValue_
Value as double.
float floatValue_
Value as float.
Detailed Description
Class that represents data in different formats.
Data can be represented as a string, integer, double, or float. The idea behind the data object is to cache the conversion results and to minimize conversions. The DataObject's value can be null, it is indicated with isNull() returning true. This should not be confused with NullDataObject, which is just there to indicate a DataObject reference which is null (a null reference, compares to a null pointer).
Definition at line 50 of file DataObject.hh.
Member Enumeration Documentation
OrigType
enum DataObject::OrigType
Models the type with which DataObject was originally initialized.
Enumerator
TYPE_INT
TYPE_STRING
TYPE_DOUBLE
TYPE_FLOAT
TYPE_NULL
TYPE_NOTYPE
Definition at line 56 of file DataObject.hh.
                  {
        TYPE_INT,
        TYPE_STRING,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_NULL,
        TYPE_NOTYPE
    };
Constructor & Destructor Documentation
DataObject() [1/5]
DataObject::DataObject ()
Constructor.
Creates an DataObject which represents an empty string.
Definition at line 46 of file DataObject.cc.
                       :
    type_(TYPE_STRING), intFresh_(false), stringFresh_(true),
    doubleFresh_(false), floatFresh_(false), intValue_(0), stringValue_(""),
    doubleValue_(0), floatValue_(0) {
}
DataObject() [2/5]
DataObject::DataObject (int value) explicit
Constructor for integer data.
Parameters
value Value as integer.
Definition at line 57 of file DataObject.cc.
{
    setInteger(value);
}
References setInteger().
DataObject() [3/5]
DataObject::DataObject (SLongWord value) explicit
Constructor for integer data.
Parameters
value Value as integer.
Definition at line 66 of file DataObject.cc.
{
    setLong(value);
}
References setLong().
DataObject() [4/5]
DataObject::DataObject (double value) explicit
Constructor for double data.
Parameters
value Value as double.
Definition at line 75 of file DataObject.cc.
{
    setDouble(value);
}
References setDouble().
DataObject() [5/5]
DataObject::DataObject (const std::string value) explicit
Constructor for string data.
Parameters
value Value as string.
Definition at line 84 of file DataObject.cc.
{
    setString(value);
}
References setString().
~DataObject()
DataObject::~DataObject () virtual
Destructor.
Definition at line 91 of file DataObject.cc.
{
}
Member Function Documentation
boolValue()
bool DataObject::boolValue () const virtual
Returns the bool value of DataObject.
The conversion is done from the original data type. The NULL value is represented as "false".
Returns
The bool value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Definition at line 470 of file DataObject.cc.
{
    if (type_ == TYPE_STRING) {
        std::string strValue = StringTools::stringToLower(stringValue());
        if (strValue == "true") {
            return true;
        } else if (strValue == "false") {
            return false;
        }
    } else if (type_ == TYPE_NULL) {
        return false;
    }
    return integerValue();
}
References integerValue(), StringTools::stringToLower(), stringValue(), type_, TYPE_NULL, and TYPE_STRING.
Referenced by HDB::HDBManager::addOperationPipelinesToFUArchitecture(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), HDB::HDBManager::createImplementationOfRF(), and HDB::HDBManager::rfArchitectureByID().
doubleFresh()
bool DataObject::doubleFresh () const protected
doubleValue()
double DataObject::doubleValue () const virtual
Returns the double value of DataObject.
If double value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to 0.0.
Returns
The double value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented in NullDataObject.
Definition at line 386 of file DataObject.cc.
{
    if (doubleFresh_) {
        return doubleValue_;
    } else {
        switch (type_) {
        case TYPE_STRING:
            doubleValue_ = Conversion::toDouble(stringValue_);
            break;
        case TYPE_INT:
            doubleValue_ = Conversion::toDouble(intValue_);
            break;
        case TYPE_FLOAT:
            doubleValue_ = Conversion::toDouble(floatValue_);
            break;
        case TYPE_NOTYPE: {
            string method = "DataObject::doubleValue()";
            string message = "DataObject not initialized.";
            throw NumberFormatException(__FILE__, __LINE__, method, message);
            break;
        }
        case TYPE_NULL:
            doubleValue_ = 0.0;
            break;
        default:
            break;
        }
        doubleFresh_ = true;
        return doubleValue_;
    }
}
References doubleFresh_, doubleValue_, floatValue_, intValue_, stringValue_, Conversion::toDouble(), type_, TYPE_FLOAT, TYPE_INT, TYPE_NOTYPE, TYPE_NULL, and TYPE_STRING.
Referenced by DSDBManager::applicationCostEstimatesByConf(), CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), CustomCommand::checkDoubleArgument(), DSDBManager::cycleCount(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::delayOfSocket(), DSDBManager::energyEstimate(), StrictMatchRFEstimator::estimateArea(), StrictMatchFUEstimator::estimateArea(), StrictMatchRFEstimator::estimateEnergy(), StrictMatchFUEstimator::estimateEnergy(), DefaultICDecoderEstimator::estimateICArea(), StrictMatchRFEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimateMaximumComputationDelay(), StrictMatchFUEstimator::estimatePortReadDelay(), StrictMatchRFEstimator::estimatePortReadDelay(), StrictMatchFUEstimator::estimatePortWriteDelay(), StrictMatchRFEstimator::estimatePortWriteDelay(), and DSDBManager::longestPathDelayEstimate().
floatFresh()
bool DataObject::floatFresh () const protected
floatValue()
float DataObject::floatValue () const virtual
Returns the float value of DataObject.
If float value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to 0.0.
Returns
The float value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented in NullDataObject.
Definition at line 428 of file DataObject.cc.
{
    if (floatFresh_) {
        return floatValue_;
    } else {
        switch (type_) {
        case TYPE_STRING:
            floatValue_ = Conversion::toFloat(stringValue_);
            break;
        case TYPE_INT:
            floatValue_ = Conversion::toFloat(intValue_);
            break;
        case TYPE_DOUBLE:
            floatValue_ = Conversion::toFloat(doubleValue_);
            break;
        case TYPE_NOTYPE: {
            string method = "DataObject::floatValue()";
            string message = "DataObject not initialized.";
            throw NumberFormatException(__FILE__, __LINE__, method, message);
            break;
        }
        case TYPE_NULL:
            floatValue_ = 0.0;
            break;
        default:
            break;
        }
        floatFresh_ = true;
        return floatValue_;
    }
}
References doubleValue_, floatFresh_, floatValue_, intValue_, stringValue_, Conversion::toFloat(), type_, TYPE_DOUBLE, TYPE_INT, TYPE_NOTYPE, TYPE_NULL, and TYPE_STRING.
integerValue()
int DataObject::integerValue () const virtual
Returns the integer value of DataObject.
If integer value is not available, the conversion is done from the original value type. Note that a NULL DataObject is converted to 0.
Returns
The integer value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented in NullDataObject.
Definition at line 204 of file DataObject.cc.
{
    if (intFresh_) {
        return intValue_;
    } else {
        try {
            switch (type_) {
            case TYPE_STRING:
                intValue_ = Conversion::toInt(stringValue_);
                break;
            case TYPE_DOUBLE:
                intValue_ = Conversion::toInt(doubleValue_);
                break;
            case TYPE_FLOAT:
                intValue_ = Conversion::toInt(floatValue_);
                break;
            case TYPE_NOTYPE: {
                string method = "DataObject::integerValue()";
                string message = "DataObject not initialized.";
                throw NumberFormatException(
                    __FILE__, __LINE__, method, message);
                break;
            }
            case TYPE_NULL:
                intValue_ = 0;
                break;
            default:
                break;
            }
        } catch (const NumberFormatException&) {
            // it can be an unsigned int, let's try to convert to
            // unsigned int first
            switch (type_) {
            case TYPE_STRING:
                intValue_ = Conversion::toUnsignedInt(stringValue_);
                break;
            case TYPE_DOUBLE:
                intValue_ = Conversion::toUnsignedInt(doubleValue_);
                break;
            case TYPE_FLOAT:
                intValue_ = Conversion::toUnsignedInt(floatValue_);
                break;
            case TYPE_NOTYPE: {
                string method = "DataObject::integerValue()";
                string message = "DataObject not initialized.";
                throw NumberFormatException(
                    __FILE__, __LINE__, method, message);
                break;
            }
            default:
                break;
            }
        }
        intFresh_ = true;
        return intValue_;
    }
}
References doubleValue_, floatValue_, intFresh_, intValue_, stringValue_, Conversion::toInt(), Conversion::toUnsignedInt(), type_, TYPE_DOUBLE, TYPE_FLOAT, TYPE_NOTYPE, TYPE_NULL, and TYPE_STRING.
Referenced by HDB::HDBManager::addOpcodesToImplementation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), InstructionExecution::address(), DSDBManager::applicationCostEstimatesByConf(), DSDBManager::applicationCount(), DSDBManager::applicationIDs(), DSDBManager::archConfigurationIDs(), DSDBManager::architectureId(), DSDBManager::architectureIDs(), DSDBManager::areaEstimate(), boolValue(), CostDatabase::buildBuses(), CostDatabase::buildSockets(), HDB::HDBManager::busCostEstimationDataIDs(), HDB::HDBManager::busEntryIDs(), CustomCommand::checkIntegerArgument(), CustomCommand::checkPositiveIntegerArgument(), CustomCommand::checkUnsignedIntegerArgument(), DSDBManager::configuration(), DSDBManager::configurationId(), DSDBManager::configurationIDs(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::costEstimationDataIDs(), HDB::HDBManager::costFunctionPluginByID(), HDB::HDBManager::costFunctionPluginDataIDs(), HDB::HDBManager::costFunctionPluginIDs(), HDB::HDBManager::createCostFunctionOfFU(), HDB::HDBManager::createCostFunctionOfRF(), HDB::HDBManager::createImplementationOfFU(), HDB::HDBManager::createImplementationOfRF(), InstructionExecution::cycle(), DefaultICDecoderEstimator::delayOfSocket(), HDB::HDBManager::fuArchitectureID(), HDB::HDBManager::fuArchitectureIDs(), HDB::HDBManager::fuArchitectureIDsByOperationSet(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuCostEstimationDataIDs(), HDB::HDBManager::fuEntriesByArchitecture(), HDB::HDBManager::fuEntryIDOfImplementation(), HDB::HDBManager::fuEntryIDs(), HDB::HDBManager::OperationImplementationByID(), HDB::HDBManager::OperationImplementationIDs(), HDB::HDBManager::OperationImplementationResourceIDs(), DSDBManager::paretoSetConnectivityAndCycles(), HDB::HDBManager::removeBusEntry(), HDB::HDBManager::removeFUEntry(), HDB::HDBManager::removeOperationImplementation(), HDB::HDBManager::removeOperationImplementationResource(), HDB::HDBManager::removeRFEntry(), HDB::HDBManager::removeSocketEntry(), HDB::HDBManager::resolveArchitecturePort(), HDB::HDBManager::rfArchitectureByID(), HDB::HDBManager::rfArchitectureID(), HDB::HDBManager::rfArchitectureIDs(), HDB::HDBManager::rfByEntryID(), HDB::HDBManager::rfCostEstimationDataIDs(), HDB::HDBManager::rfEntriesByArchitecture(), HDB::HDBManager::rfEntryIDOfImplementation(), HDB::HDBManager::rfEntryIDs(), SQLiteConnection::rowCountInTable(), HDB::HDBManager::socketCostEstimationDataIDs(), HDB::HDBManager::socketEntryIDs(), SQLiteConnection::tableExistsInDB(), ScriptInterpreter::variableIntegerValue(), and SQLiteConnection::version().
intFresh()
bool DataObject::intFresh () const protected
isNull()
bool DataObject::isNull () const virtual
Returns true in case the object represents a NULL value.
Returns
True in case the object's value is NULL.
Reimplemented in NullDataObject.
Definition at line 491 of file DataObject.cc.
{
    return type_ == TYPE_NULL;
}
References type_, and TYPE_NULL.
Referenced by HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), DSDBManager::configuration(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::createCostFunctionOfFU(), HDB::HDBManager::createCostFunctionOfRF(), HDB::HDBManager::fuArchitectureID(), HDB::HDBManager::fuByEntryID(), HDB::HDBManager::fuEntryHasArchitecture(), HDB::HDBManager::rfArchitectureByID(), HDB::HDBManager::rfArchitectureID(), HDB::HDBManager::rfByEntryID(), and HDB::HDBManager::rfEntryHasArchitecture().
longValue()
SLongWord DataObject::longValue () const virtual
Returns the (long) integer value of DataObject.
If integer value is not available, the conversion is done from the original value type. Note that a NULL DataObject is converted to 0.
Returns
The integer value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented in NullDataObject.
Definition at line 273 of file DataObject.cc.
{
    if (intFresh_) {
        return intValue_;
    } else {
        try {
            switch (type_) {
            case TYPE_STRING:
                intValue_ = Conversion::toLong(stringValue_);
                break;
            case TYPE_DOUBLE:
                intValue_ = Conversion::toLong(doubleValue_);
                break;
            case TYPE_FLOAT:
                intValue_ = Conversion::toLong(floatValue_);
                break;
            case TYPE_NOTYPE: {
                string method = "DataObject::integerValue()";
                string message = "DataObject not initialized.";
                throw NumberFormatException(
                    __FILE__, __LINE__, method, message);
                break;
            }
            case TYPE_NULL:
                intValue_ = 0;
                break;
            default:
                break;
            }
        } catch (const NumberFormatException&) {
            // it can be an unsigned int, let's try to convert to
            // unsigned int first
            switch (type_) {
            case TYPE_STRING:
                intValue_ = Conversion::toUnsignedLong(stringValue_);
                break;
            case TYPE_DOUBLE:
                intValue_ = Conversion::toUnsignedLong(doubleValue_);
                break;
            case TYPE_FLOAT:
                intValue_ = Conversion::toUnsignedLong(floatValue_);
                break;
            case TYPE_NOTYPE: {
                string method = "DataObject::integerValue()";
                string message = "DataObject not initialized.";
                throw NumberFormatException(
                    __FILE__, __LINE__, method, message);
                break;
            }
            default:
                break;
            }
        }
        intFresh_ = true;
        return intValue_;
    }
}
References doubleValue_, floatValue_, intFresh_, intValue_, stringValue_, Conversion::toLong(), Conversion::toUnsignedLong(), type_, TYPE_DOUBLE, TYPE_FLOAT, TYPE_NOTYPE, TYPE_NULL, and TYPE_STRING.
operator!=()
bool DataObject::operator!= (const DataObject & object) const virtual
Tests the inequality of two DataObjects.
Parameters
object The object this object is compared to.
Returns
True if the two objects are inequal.
Exceptions
NumberFormatException If conversion fails.
Definition at line 503 of file DataObject.cc.
{
    if (object.type_ != type_)
        return true;
    if (type_ == TYPE_NULL)
        return false; // the type_ is the value as itself
    string value1 = stringValue();
    string value2 = object.stringValue();
    return value1 != value2;
}
References stringValue(), type_, and TYPE_NULL.
setBool()
void DataObject::setBool (bool value) virtual
Sets the bool value of DataObject.
Parameters
value The bool value of DataObject.
Definition at line 175 of file DataObject.cc.
{
    setInteger(value);
}
References setInteger().
setDouble()
void DataObject::setDouble (double value) virtual
Sets the double value of DataObject.
Parameters
value The double value of DataObject.
Reimplemented in NullDataObject.
Definition at line 145 of file DataObject.cc.
{
    type_ = TYPE_DOUBLE;
    doubleFresh_ = true;
    intFresh_ = false;
    stringFresh_ = false;
    floatFresh_ = false;
    doubleValue_ = value;
}
References doubleFresh_, doubleValue_, floatFresh_, intFresh_, stringFresh_, type_, and TYPE_DOUBLE.
Referenced by DataObject(), and ScriptInterpreter::setResult().
setFloat()
void DataObject::setFloat (float value) virtual
Sets the float value of DataObject.
Parameters
value The float value of DataObject.
Reimplemented in NullDataObject.
Definition at line 160 of file DataObject.cc.
{
    type_ = TYPE_FLOAT;
    floatFresh_ = true;
    intFresh_ = false;
    stringFresh_ = false;
    doubleFresh_ = false;
    floatValue_ = value;
}
References doubleFresh_, floatFresh_, floatValue_, intFresh_, stringFresh_, type_, and TYPE_FLOAT.
setInteger()
void DataObject::setInteger (int value) virtual
Sets the integer value of DataObject.
Parameters
value The integer value.
Reimplemented in NullDataObject.
Definition at line 115 of file DataObject.cc.
{
    type_ = TYPE_INT;
    intFresh_ = true;
    stringFresh_ = false;
    doubleFresh_ = false;
    floatFresh_ = false;
    intValue_ = value;
}
References doubleFresh_, floatFresh_, intFresh_, intValue_, stringFresh_, type_, and TYPE_INT.
Referenced by DataObject(), setBool(), ScriptInterpreter::setResult(), and ScriptInterpreter::setVariable().
setLong()
void DataObject::setLong (SLongWord value) virtual
Sets the integer value of DataObject.
Parameters
value The integer value.
Reimplemented in NullDataObject.
Definition at line 100 of file DataObject.cc.
{
    type_ = TYPE_INT;
    intFresh_ = true;
    stringFresh_ = false;
    doubleFresh_ = false;
    floatFresh_ = false;
    intValue_ = value;
}
References doubleFresh_, floatFresh_, intFresh_, intValue_, stringFresh_, type_, and TYPE_INT.
Referenced by DataObject().
setNull()
void DataObject::setNull () virtual
Sets the DataObject to null.
Reimplemented in NullDataObject.
Definition at line 184 of file DataObject.cc.
                    {
    type_ = TYPE_NULL;
    intFresh_ = true;
    intValue_ = 0;
    stringFresh_ = true;
    stringValue_ = "";
}
References intFresh_, intValue_, stringFresh_, stringValue_, type_, and TYPE_NULL.
Referenced by SQLiteQueryResult::next().
setString()
void DataObject::setString (std::string value) virtual
Sets the string value of DataObject.
Parameters
value The string value.
Reimplemented in NullDataObject.
Definition at line 130 of file DataObject.cc.
{
    type_ = TYPE_STRING;
    stringFresh_ = true;
    intFresh_ = false;
    doubleFresh_ = false;
    floatFresh_ = false;
    stringValue_ = value;
}
References doubleFresh_, floatFresh_, intFresh_, stringFresh_, stringValue_, type_, and TYPE_STRING.
Referenced by CustomCommand::checkArgumentCount(), CustomCommand::checkDoubleArgument(), CustomCommand::checkIntegerArgument(), CustomCommand::checkPositiveIntegerArgument(), SimControlLanguageCommand::checkSimulationEnded(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationNotAlreadyRunning(), SimControlLanguageCommand::checkSimulationStopped(), CustomCommand::checkUnsignedIntegerArgument(), DataObject(), Script::execute(), CmdHelp::execute(), ConfCommand::execute(), HelpCommand::execute(), MachCommand::execute(), MemDumpCommand::execute(), ProgCommand::execute(), SettingCommand::execute(), CmdTrigger::execute(), CmdReset::execute(), CmdQuit::execute(), CmdOutput::execute(), CmdRegister::execute(), CmdMem::execute(), CmdAdvanceClock::execute(), SimpleScriptInterpreter::interpret(), SQLiteQueryResult::next(), SimControlLanguageCommand::setErrorMessage(), ScriptInterpreter::setResult(), ScriptInterpreter::setVariable(), TclInterpreter::tclObjToDataObject(), DefaultICDecoderEstimator::valueFromKeyValuePairString(), and SimpleScriptInterpreter::variable().
stringFresh()
bool DataObject::stringFresh () const protected
stringValue()
string DataObject::stringValue () const virtual
Returns the string value of DataObject.
If string value is not available, the conversion is done from the original data type. Note that a NULL DataObject is converted to an empty string.
Returns
The string value of DataObject.
Exceptions
NumberFormatException If conversion fails or if DataObject is not initialized.
Reimplemented in NullDataObject.
Definition at line 344 of file DataObject.cc.
{
    if (stringFresh_) {
        return stringValue_;
    } else {
        switch (type_) {
        case TYPE_INT:
            stringValue_ = Conversion::toString(intValue_);
            break;
        case TYPE_DOUBLE:
            stringValue_ = Conversion::toString(doubleValue_);
            break;
        case TYPE_FLOAT:
            stringValue_ = Conversion::toString(floatValue_);
            break;
        case TYPE_NOTYPE: {
            string method = "DataObject::stringValue()";
            string message = "DataObject not initialized.";
            throw NumberFormatException(__FILE__, __LINE__, method, message);
            break;
        }
        case TYPE_NULL:
            stringValue_ = "";
            break;
        default:
            break;
        }
        stringFresh_ = true;
        return stringValue_;
    }
}
References doubleValue_, floatValue_, intValue_, stringFresh_, stringValue_, Conversion::toString(), type_, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NOTYPE, and TYPE_NULL.
Referenced by HDB::HDBManager::addBlockImplementationFiles(), HDB::HDBManager::addBlockImplementationFiles(), HDB::HDBManager::addCostEstimationData(), HDB::HDBManager::addDataPortsToImplementation(), HDB::HDBManager::addDataPortsToImplementation(), HDB::HDBManager::addFUExternalPortsToImplementation(), HDB::HDBManager::addFUImplementation(), HDB::HDBManager::addFUParametersToImplementation(), HDB::HDBManager::addOpcodesToImplementation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), HDB::HDBManager::addRFExternalPortsToImplementation(), HDB::HDBManager::addRFParametersToImplementation(), DSDBManager::applicationCostEstimatesByConf(), DSDBManager::applicationPath(), DSDBManager::architectureString(), HDB::HDBManager::blockSourceFile(), boolValue(), HDBToHtml::busEntryToHtml(), CustomCommand::checkUnsignedIntegerArgument(), ConditionScript::conditionOk(), HDB::HDBManager::costEstimationData(), HDB::HDBManager::costFunctionPluginByID(), HDBToHtml::costFunctionPluginToHtml(), HDB::HDBManager::createCostFunctionOfFU(), HDB::HDBManager::createCostFunctionOfRF(), HDB::HDBManager::createImplementationOfFU(), HDB::HDBManager::createImplementationOfRF(), DefaultICDecoderEstimator::delayOfBus(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::delayOfSocket(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), MemDumpCommand::execute(), HDBToHtml::fuEntryToHtml(), HDBToHtml::fuImplToHtml(), HDB::HDBManager::hasColumn(), DSDBManager::implementationString(), HDB::HDBManager::modifyCostEstimationData(), HDB::HDBManager::OperationImplementationByID(), HDB::HDBManager::OperationImplementationResourceByID(), operator!=(), HDB::HDBManager::resolveArchitecturePort(), ScriptInterpreter::result(), HDBToHtml::rfEntryToHtml(), HDBToHtml::rfImplToHtml(), SimpleScriptInterpreter::setVariableToInterpreter(), TclInterpreter::setVariableToInterpreter(), HDBToHtml::socketEntryToHtml(), CostEstimationDataDialog::TransferDataToWindow(), CostFunctionPluginDialog::TransferDataToWindow(), and ScriptInterpreter::variableStringValue().
type()
OrigType DataObject::type () const protected
Member Data Documentation
doubleFresh_
bool DataObject::doubleFresh_ mutable private
Flag indicating that the value of double is up-to-date.
Definition at line 110 of file DataObject.hh.
Referenced by doubleValue(), setDouble(), setFloat(), setInteger(), setLong(), and setString().
doubleValue_
double DataObject::doubleValue_ mutable private
Value as double.
Definition at line 118 of file DataObject.hh.
Referenced by doubleValue(), floatValue(), integerValue(), longValue(), setDouble(), and stringValue().
floatFresh_
bool DataObject::floatFresh_ mutable private
Flag indicating that the value of float is up-to-date.
Definition at line 112 of file DataObject.hh.
Referenced by floatValue(), setDouble(), setFloat(), setInteger(), setLong(), and setString().
floatValue_
float DataObject::floatValue_ mutable private
Value as float.
Definition at line 120 of file DataObject.hh.
Referenced by doubleValue(), floatValue(), integerValue(), longValue(), setFloat(), and stringValue().
intFresh_
bool DataObject::intFresh_ mutable private
Flag indicating that the value of integer is up-to-date.
Definition at line 106 of file DataObject.hh.
Referenced by integerValue(), longValue(), setDouble(), setFloat(), setInteger(), setLong(), setNull(), and setString().
intValue_
SLongWord DataObject::intValue_ mutable private
Value as integer.
Definition at line 114 of file DataObject.hh.
Referenced by doubleValue(), floatValue(), integerValue(), longValue(), setInteger(), setLong(), setNull(), and stringValue().
stringFresh_
bool DataObject::stringFresh_ mutable private
Flag indicating that the value of string is up-to-date.
Definition at line 108 of file DataObject.hh.
Referenced by setDouble(), setFloat(), setInteger(), setLong(), setNull(), setString(), and stringValue().
stringValue_
std::string DataObject::stringValue_ mutable private
Value as string.
Definition at line 116 of file DataObject.hh.
Referenced by doubleValue(), floatValue(), integerValue(), longValue(), setNull(), setString(), and stringValue().
type_
OrigType DataObject::type_ private
The type of value in which DataObject was last assigned.
Definition at line 104 of file DataObject.hh.
Referenced by boolValue(), doubleValue(), floatValue(), integerValue(), isNull(), longValue(), operator!=(), setDouble(), setFloat(), setInteger(), setLong(), setNull(), setString(), and stringValue().
The documentation for this class was generated from the following files:
DataObject.hh
DataObject.cc