OpenASIP: PortCode Class Reference
PortCode Class Reference
#include <PortCode.hh>
Public Member Functions
virtual ~PortCode ()
std::string unitName () const
bool hasEncoding () const
unsigned int encoding () const
unsigned int extraBits () const
int width () const
int encodingWidth () const
int indexWidth () const
void setMaxIndex (unsigned regIndex)
bool isMaxIndexSet () const
unsigned maxIndex () const
SocketCodeTable * parent () const
virtual ObjectState * saveState () const
Static Public Attributes
static const std::string OSNAME_PORT_CODE = "port_code"
ObjectState name for PortCode.
static const std::string OSKEY_UNIT_NAME = "unit_name"
ObjectState attribute key for the name of the unit.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_INDEX_WIDTH = "index_width"
ObjectState attribute key for the widht of register index.
static const std::string OSKEY_MAX_INDEX = "max-index"
ObjectState attribute key for the max-index attribute.
Protected Member Functions
PortCode (const std::string &unitName, unsigned int encoding, unsigned int extraBits, int indexWidth)
PortCode (const std::string &unitName, int indexWidth)
PortCode (const ObjectState *state)
void setParent (SocketCodeTable *parent)
Private Attributes
std::string unitName_
Name of the unit.
unsigned int encoding_
The encoding.
unsigned int extraBits_
The number of extra bits in the encoding.
int indexWidth_
The width of the register index in the port code.
bool hasEncoding_
Tells whether the port code has an encoding.
SocketCodeTable * parent_
The parent socket code table.
unsigned maxRegIndex_
In case this is set to non-zero, the whole width of the index field is not used because the number of register indices is not an exponent of two. This allow sharing the field with other values.
Detailed Description
Base class for FUPortCode, RFPortCode and IUPortCode.
Definition at line 45 of file PortCode.hh.
Constructor & Destructor Documentation
~PortCode()
PortCode::~PortCode () virtual
The destructor.
Definition at line 130 of file PortCode.cc.
                    {
}
PortCode() [1/3]
PortCode::PortCode (const std::string & unitName, unsigned int encoding, unsigned int extraBits, int indexWidth) protected
The constructor.
Creates a port code with port ID.
Parameters
unitName Name of the unit.
encoding The encoding.
extraBits The number of extra bits in the encoding.
indexWidth The width of the register index.
Exceptions
OutOfRange If the some of the given values is negative.
Definition at line 56 of file PortCode.cc.
    : unitName_(unitName),
      encoding_(encoding),
      extraBits_(extraBits),
      indexWidth_(indexWidth),
      hasEncoding_(true),
      parent_(NULL),
      maxRegIndex_(0) {
    if (indexWidth_ < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
}
References __func__, and indexWidth_.
PortCode() [2/3]
PortCode::PortCode (const std::string & unitName, int indexWidth) protected
The constructor.
Creates a port code without port ID.
Parameters
unitName Name of the unit.
indexWidth The width of the register index.
Exceptions
OutOfRange If the some of the given values is negative.
Definition at line 80 of file PortCode.cc.
    : unitName_(unitName),
      encoding_(0),
      extraBits_(0),
      indexWidth_(indexWidth),
      hasEncoding_(false),
      parent_(NULL),
      maxRegIndex_(0) {
    if (indexWidth_ < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
}
References __func__, and indexWidth_.
PortCode() [3/3]
PortCode::PortCode (const ObjectState * state) protected
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is erroneous.
Definition at line 102 of file PortCode.cc.
    : unitName_(""),
      encoding_(0),
      extraBits_(0),
      indexWidth_(0),
      hasEncoding_(false),
      parent_(NULL),
      maxRegIndex_(0) {
    try {
        unitName_ = state->stringAttribute(OSKEY_UNIT_NAME);
        if (state->hasAttribute(OSKEY_MAX_INDEX))
            maxRegIndex_ = state->intAttribute(OSKEY_MAX_INDEX);
        if (state->hasAttribute(OSKEY_ENCODING)) {
            encoding_ = state->intAttribute(OSKEY_ENCODING);
            extraBits_ = state->intAttribute(OSKEY_EXTRA_BITS);
            hasEncoding_ = true;
        }
        if (state->hasAttribute(OSKEY_INDEX_WIDTH)) {
            indexWidth_ = state->intAttribute(OSKEY_INDEX_WIDTH);
        }
    } catch (const Exception&) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, __func__);
    }
}
References __func__, encoding_, extraBits_, ObjectState::hasAttribute(), hasEncoding_, indexWidth_, ObjectState::intAttribute(), maxRegIndex_, OSKEY_ENCODING, OSKEY_EXTRA_BITS, OSKEY_INDEX_WIDTH, OSKEY_MAX_INDEX, OSKEY_UNIT_NAME, ObjectState::stringAttribute(), and unitName_.
Member Function Documentation
encoding()
unsigned int PortCode::encoding () const
Returns the encoding.
Returns
The encoding.
Exceptions
NotAvailable If the port code does not have an encoding (port ID).
Definition at line 164 of file PortCode.cc.
{
    if (!hasEncoding()) {
        throw NotAvailable(__FILE__, __LINE__, __func__);
    }
    return encoding_;
}
References __func__, encoding_, and hasEncoding().
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::addIUPortCode(), SocketCodeTable::addRFPortCode(), BEMTester::canAddPortEncoding(), BEMTester::conflictsWithSocketTableEncodings(), CodeCompressorPlugin::encodeFUTerminal(), portCodeBits(), DefaultDecoderGenerator::portCodeCondition(), saveState(), CodeCompressorPlugin::socketCodeBits(), width(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
encodingWidth()
int PortCode::encodingWidth () const
Returns the width of the encoding (port ID).
Returns
The width of the encoding.
Definition at line 204 of file PortCode.cc.
{
    return width() - indexWidth();
}
References indexWidth(), and width().
Referenced by BEMTester::canAddPortEncoding(), BEMTester::conflictsWithSocketTableEncodings(), portCodeBits(), DefaultDecoderGenerator::portCodeCondition(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
extraBits()
unsigned int PortCode::extraBits () const
Returns the number of extra bits in the encoding.
Returns
The number of extra bits.
Definition at line 177 of file PortCode.cc.
{
    return extraBits_;
}
References extraBits_.
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::addIUPortCode(), SocketCodeTable::addRFPortCode(), BEMTester::canAddPortEncoding(), saveState(), and width().
hasEncoding()
bool PortCode::hasEncoding () const
Tells whether the port code has an encoding (port ID).
Returns
True if the port code has an encoding, otherwise false.
Definition at line 151 of file PortCode.cc.
{
    return hasEncoding_;
}
References hasEncoding_.
Referenced by SocketCodeTable::addIUPortCode(), SocketCodeTable::addRFPortCode(), encoding(), portCodeBits(), saveState(), CodeCompressorPlugin::socketCodeBits(), width(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
indexWidth()
int PortCode::indexWidth () const
Returns the width of the register index (opcode).
Returns
The width of the register index.
Definition at line 215 of file PortCode.cc.
{
    return indexWidth_;
}
References indexWidth_.
Referenced by BEMTester::conflictsWithSocketTableEncodings(), encodingWidth(), portCodeBits(), DefaultDecoderGenerator::portCodeCondition(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), saveState(), CodeCompressorPlugin::socketCodeBits(), width(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
isMaxIndexSet()
bool PortCode::isMaxIndexSet () const inline
Definition at line 59 of file PortCode.hh.
{ return maxRegIndex_ != 0; }
References maxRegIndex_.
maxIndex()
unsigned PortCode::maxIndex () const inline
Definition at line 60 of file PortCode.hh.
{ return maxRegIndex_; }
References maxRegIndex_.
parent()
SocketCodeTable * PortCode::parent () const
Returns the parent socket code table.
Returns
The parent socket code table.
Definition at line 226 of file PortCode.cc.
                       {
    return parent_;
}
References parent_.
Referenced by SocketCodeTable::addIUPortCode(), SocketCodeTable::addRFPortCode(), FUPortCode::FUPortCode(), FUPortCode::FUPortCode(), FUPortCode::FUPortCode(), IUPortCode::IUPortCode(), IUPortCode::IUPortCode(), IUPortCode::IUPortCode(), portCodeBits(), SocketCodeTable::removeFUPortCode(), SocketCodeTable::removeIUPortCode(), SocketCodeTable::removeRFPortCode(), RFPortCode::RFPortCode(), RFPortCode::RFPortCode(), RFPortCode::RFPortCode(), setParent(), FUPortCode::~FUPortCode(), IUPortCode::~IUPortCode(), and RFPortCode::~RFPortCode().
saveState()
ObjectState * PortCode::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented in FUPortCode, IUPortCode, and RFPortCode.
Definition at line 237 of file PortCode.cc.
{
    ObjectState* state = new ObjectState(OSNAME_PORT_CODE);
    state->setAttribute(OSKEY_UNIT_NAME, unitName());
    if (hasEncoding()) {
        state->setAttribute(OSKEY_ENCODING, encoding());
        state->setAttribute(OSKEY_EXTRA_BITS, extraBits());
    }
    if (maxRegIndex_ != 0) state->setAttribute(OSKEY_MAX_INDEX, maxRegIndex_);
    state->setAttribute(OSKEY_INDEX_WIDTH, indexWidth());
    return state;
}
References encoding(), extraBits(), hasEncoding(), indexWidth(), maxRegIndex_, OSKEY_ENCODING, OSKEY_EXTRA_BITS, OSKEY_INDEX_WIDTH, OSKEY_MAX_INDEX, OSKEY_UNIT_NAME, OSNAME_PORT_CODE, ObjectState::setAttribute(), and unitName().
Referenced by FUPortCode::saveState(), IUPortCode::saveState(), and RFPortCode::saveState().
setMaxIndex()
void PortCode::setMaxIndex (unsigned regIndex) inline
Definition at line 58 of file PortCode.hh.
{ maxRegIndex_ = regIndex; }
References maxRegIndex_.
setParent()
void PortCode::setParent (SocketCodeTable * parent) protected
Sets the parent socket code table pointer.
Parameters
parent The parent pointer.
Definition at line 256 of file PortCode.cc.
{
    parent_ = parent;
}
References parent(), and parent_.
Referenced by FUPortCode::FUPortCode(), FUPortCode::FUPortCode(), FUPortCode::FUPortCode(), IUPortCode::IUPortCode(), IUPortCode::IUPortCode(), IUPortCode::IUPortCode(), RFPortCode::RFPortCode(), RFPortCode::RFPortCode(), RFPortCode::RFPortCode(), FUPortCode::~FUPortCode(), IUPortCode::~IUPortCode(), and RFPortCode::~RFPortCode().
unitName()
std::string PortCode::unitName () const
Returns the name of the unit.
Returns
The name of the unit.
Definition at line 140 of file PortCode.cc.
{
    return unitName_;
}
References unitName_.
Referenced by SocketCodeTable::addFUPortCode(), SocketCodeTable::addIUPortCode(), SocketCodeTable::addRFPortCode(), SocketCodeTable::fuPortCode(), SocketCodeTable::fuPortCode(), SocketCodeTable::iuPortCode(), portCodeDescription(), portCodeDescription(), portCodeDescription(), SocketCodeTable::rfPortCode(), and saveState().
width()
int PortCode::width () const
Returns the width of the whole port code (portID + opcode).
Returns
The width.
Definition at line 188 of file PortCode.cc.
                      {
    if (hasEncoding()) {
        return MathTools::bitLength(encoding()) + extraBits() +
            indexWidth();
    } else {
        return indexWidth();
    }
}
References MathTools::bitLength(), encoding(), extraBits(), hasEncoding(), and indexWidth().
Referenced by encodingWidth(), SocketCodeTable::maxCodeWidth(), portCodeBits(), and CodeCompressorPlugin::socketCodeBits().
Member Data Documentation
encoding_
unsigned int PortCode::encoding_ private
The encoding.
Definition at line 91 of file PortCode.hh.
Referenced by encoding(), and PortCode().
extraBits_
unsigned int PortCode::extraBits_ private
The number of extra bits in the encoding.
Definition at line 93 of file PortCode.hh.
Referenced by extraBits(), and PortCode().
hasEncoding_
bool PortCode::hasEncoding_ private
Tells whether the port code has an encoding.
Definition at line 97 of file PortCode.hh.
Referenced by hasEncoding(), and PortCode().
indexWidth_
int PortCode::indexWidth_ private
The width of the register index in the port code.
Definition at line 95 of file PortCode.hh.
Referenced by indexWidth(), PortCode(), PortCode(), and PortCode().
maxRegIndex_
unsigned PortCode::maxRegIndex_ private
In case this is set to non-zero, the whole width of the index field is not used because the number of register indices is not an exponent of two. This allow sharing the field with other values.
Definition at line 104 of file PortCode.hh.
Referenced by isMaxIndexSet(), maxIndex(), PortCode(), saveState(), and setMaxIndex().
OSKEY_ENCODING
const std::string PortCode::OSKEY_ENCODING = "encoding" static
ObjectState attribute key for the encoding.
Definition at line 71 of file PortCode.hh.
Referenced by PortCode(), BEMSerializer::readRegisterFilePortCode(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSKEY_EXTRA_BITS
const std::string PortCode::OSKEY_EXTRA_BITS = "extra_bits" static
ObjectState attribute key for the number of extra bits.
Definition at line 73 of file PortCode.hh.
Referenced by PortCode(), BEMSerializer::readRegisterFilePortCode(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSKEY_INDEX_WIDTH
const std::string PortCode::OSKEY_INDEX_WIDTH = "index_width" static
ObjectState attribute key for the widht of register index.
Definition at line 75 of file PortCode.hh.
Referenced by PortCode(), BEMSerializer::readRegisterFilePortCode(), saveState(), and BEMSerializer::socketCodeTableToFile().
OSKEY_MAX_INDEX
const std::string PortCode::OSKEY_MAX_INDEX = "max-index" static
ObjectState attribute key for the max-index attribute.
Definition at line 77 of file PortCode.hh.
Referenced by PortCode(), saveState(), and BEMSerializer::socketCodeTableToFile().
OSKEY_UNIT_NAME
const std::string PortCode::OSKEY_UNIT_NAME = "unit_name" static
ObjectState attribute key for the name of the unit.
Definition at line 69 of file PortCode.hh.
Referenced by PortCode(), BEMSerializer::readRegisterFilePortCode(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSNAME_PORT_CODE
const std::string PortCode::OSNAME_PORT_CODE = "port_code" static
ObjectState name for PortCode.
Definition at line 67 of file PortCode.hh.
Referenced by saveState().
parent_
SocketCodeTable* PortCode::parent_ private
The parent socket code table.
Definition at line 99 of file PortCode.hh.
Referenced by parent(), and setParent().
unitName_
std::string PortCode::unitName_ private
Name of the unit.
Definition at line 89 of file PortCode.hh.
Referenced by PortCode(), and unitName().
The documentation for this class was generated from the following files:
PortCode.hh
PortCode.cc