OpenASIP: ToggleUnitDetailsCmd Class Reference
ToggleUnitDetailsCmd Class Reference
#include <ToggleUnitDetailsCmd.hh>
Public Member Functions
ToggleUnitDetailsCmd ()
virtual ~ToggleUnitDetailsCmd ()
virtual bool Do ()
virtual int id () const
virtual ToggleUnitDetailsCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
virtual bool isChecked () const
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for toggling unit info string visibility in the canvas.
Definition at line 41 of file ToggleUnitDetailsCmd.hh.
Constructor & Destructor Documentation
ToggleUnitDetailsCmd()
ToggleUnitDetailsCmd::ToggleUnitDetailsCmd ()
The Constructor.
Definition at line 48 of file ToggleUnitDetailsCmd.cc.
                                           :
    EditorCommand(ProDeConstants::CMD_NAME_TOGGLE_UNIT_DETAILS) {
}
Referenced by create().
~ToggleUnitDetailsCmd()
ToggleUnitDetailsCmd::~ToggleUnitDetailsCmd () virtual
The Destructor.
Definition at line 57 of file ToggleUnitDetailsCmd.cc.
{
}
Member Function Documentation
create()
ToggleUnitDetailsCmd * ToggleUnitDetailsCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 116 of file ToggleUnitDetailsCmd.cc.
{
    return new ToggleUnitDetailsCmd();
}
References ToggleUnitDetailsCmd().
Do()
bool ToggleUnitDetailsCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file ToggleUnitDetailsCmd.cc.
{
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    OptionValue& option = canvas->options().optionValue(
        MachineCanvasOptions::SHOW_UNIT_INFO_STRING);
    option.setBoolValue(!option.isFlagOn());
    canvas->updateMachine();
    return true;
}
References MDFView::canvas(), OptionValue::isFlagOn(), MachineCanvas::options(), Options::optionValue(), OptionValue::setBoolValue(), MachineCanvasOptions::SHOW_UNIT_INFO_STRING, MachineCanvas::updateMachine(), and EditorCommand::view().
id()
int ToggleUnitDetailsCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 105 of file ToggleUnitDetailsCmd.cc.
{
    return ProDeConstants::COMMAND_TOGGLE_UNIT_DETAILS;
}
References ProDeConstants::COMMAND_TOGGLE_UNIT_DETAILS.
isChecked()
bool ToggleUnitDetailsCmd::isChecked () const virtual
Returns state of the check-item related to this command.
Returns
true, if the command check item is checked.
Reimplemented from GUICommand.
Definition at line 83 of file ToggleUnitDetailsCmd.cc.
{
    MDFView* mView = dynamic_cast<MDFView*>(view());
    if (mView == NULL) {
        return false;
    }
    MachineCanvas* canvas = mView->canvas();
    if (canvas == NULL) {
        return false;
    }
    OptionValue& option = canvas->options().optionValue(
        MachineCanvasOptions::SHOW_UNIT_INFO_STRING);
    return option.isFlagOn();
}
References MDFView::canvas(), OptionValue::isFlagOn(), MachineCanvas::options(), Options::optionValue(), MachineCanvasOptions::SHOW_UNIT_INFO_STRING, and EditorCommand::view().
isEnabled()
bool ToggleUnitDetailsCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 140 of file ToggleUnitDetailsCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string ToggleUnitDetailsCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 127 of file ToggleUnitDetailsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_TOGGLE_UNIT_DETAILS;
}
References ProDeConstants::CMD_SNAME_TOGGLE_UNIT_DETAILS.
The documentation for this class was generated from the following files:
ToggleUnitDetailsCmd.hh
ToggleUnitDetailsCmd.cc