OpenASIP: AsmCmdLineOptions Class Reference
AsmCmdLineOptions Class Reference
Public Member Functions
AsmCmdLineOptions ()
std::string outputFile ()
bool printWarnings ()
void printVersion () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Commandline options.
Definition at line 52 of file tceasm.cc.
Constructor & Destructor Documentation
AsmCmdLineOptions()
AsmCmdLineOptions::AsmCmdLineOptions () inline
Definition at line 54 of file tceasm.cc.
                        :
        CmdLineOptions("Usage: tceasm [options] adffile assemblerfile") {
        StringCmdLineOptionParser* outputFile =
            new StringCmdLineOptionParser("outputfile", "Name of the output file.", "o");
        addOption(outputFile);
        BoolCmdLineOptionParser* quietMode =
            new BoolCmdLineOptionParser("quiet", "Don't print warnings.", "q");
        addOption(quietMode);
    }
References CmdLineParser::addOption(), and outputFile().
Member Function Documentation
outputFile()
std::string AsmCmdLineOptions::outputFile () inline
Definition at line 68 of file tceasm.cc.
{
        return findOption("outputfile")->String();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by AsmCmdLineOptions().
printVersion()
void AsmCmdLineOptions::printVersion () const inline virtual
Implements CmdLineOptions.
Definition at line 76 of file tceasm.cc.
{
        std::cout << "tceasm - OpenASIP TTA parallel assembler "
                  << Application::TCEVersionString()
                  << std::endl;
    }
References Application::TCEVersionString().
printWarnings()
bool AsmCmdLineOptions::printWarnings () inline
Definition at line 72 of file tceasm.cc.
{
        return findOption("quiet")->isFlagOff();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOff().
The documentation for this class was generated from the following file:
tceasm.cc