OpenASIP: TTAMachine::Guard Class Reference
TTAMachine::Guard Class Reference abstract
#include <Guard.hh>
Public Member Functions
virtual ~Guard ()
virtual Bus * parentBus () const
virtual void setParentBus (Bus *parentBus)
virtual bool isEqual (const Guard &guard) const =0
virtual bool isInverted () const
virtual bool isMoreRestrictive (const Guard &guard) const
virtual bool isLessRestrictive (const Guard &guard) const
virtual bool isOpposite (const Guard &guard) const =0
virtual bool isDisjoint (const Guard &guard) const
virtual void copyTo (Bus &parentBus) const =0
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_GUARD = "guard"
ObjectState name for guard.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for inverted feature.
Protected Member Functions
Guard (bool inverted, Bus *parentBus)
Guard (const ObjectState *state, Bus &parentBus)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Attributes
bool inverted_
Indicated whether the condition term is inverted.
Bus * parent_
The parent bus of the guard.
Detailed Description
Guard expression representing an execution predicate.
Evaluates to true (execute) or false (don't execute). This is a base class for real Guards.
Definition at line 55 of file Guard.hh.
Constructor & Destructor Documentation
~Guard()
TTAMachine::Guard::~Guard () virtual
Destructor.
Definition at line 90 of file Guard.cc.
              {
    Bus* parent = parent_;
    parent_ = NULL;
    if (parent) {
        parent->removeGuard(*this);
    }
}
References parent_, and TTAMachine::Bus::removeGuard().
Guard() [1/2]
TTAMachine::Guard::Guard (bool inverted, Bus * parentBus) protected
Constructor.
Parameters
inverted Indicates whether the condition term is inverted.
parentBus Parent bus component of the guard.
Definition at line 64 of file Guard.cc.
                                          :
    inverted_(inverted), parent_(parentBus) {
    // parentBus.addGuard() cannot be called here because isEqual method
    // does not work until the whole
    // (RegisterGuard/PortGuard/UnconditionalGuard) is instantiated
}
Guard() [2/2]
TTAMachine::Guard::Guard (const ObjectState * state, Bus & parentBus) protected
Constructor.
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance from which the state is loaded.
parentBus Parent bus of the guard.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 83 of file Guard.cc.
                                                     : parent_(&parentBus) {
    loadState(state);
}
References loadState().
Member Function Documentation
copyTo()
virtual void TTAMachine::Guard::copyTo (Bus & parentBus) const pure virtual
Implemented in TTAMachine::PortGuard, TTAMachine::RegisterGuard, and TTAMachine::UnconditionalGuard.
Referenced by TTAMachine::Bus::copyGuardsTo(), and PasteComponentCmd::Do().
isDisjoint()
bool TTAMachine::Guard::isDisjoint (const Guard & guard) const virtual
Checks whether this guard and given one are disjoint.
The guards are disjoint if neither is the exact subset of the other.
Parameters
guard The guard to compare.
Returns
True if the guards are disjoint, otherwise false.
Definition at line 138 of file Guard.cc.
{
    return !isEqual(guard);
}
References isEqual().
isEqual()
virtual bool TTAMachine::Guard::isEqual (const Guard & guard) const pure virtual
Implemented in TTAMachine::PortGuard, TTAMachine::RegisterGuard, and TTAMachine::UnconditionalGuard.
Referenced by BusBroker::allAvailableResources(), BusBroker::assign(), BusBroker::canTransportImmediate(), DataDependenceGraph::guardsAllowBypass(), BusBroker::hasGuard(), TTAMachine::Bus::isArchitectureEqual(), BusBroker::isAvailable(), isDisjoint(), DataDependenceGraph::isNotAvoidable(), and PostpassOperandSharer::tryRemoveOperandWrite().
isInverted()
virtual bool TTAMachine::Guard::isInverted () const virtual
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMValidator::checkGuardField(), TTAMachine::PortGuard::copyTo(), TTAMachine::RegisterGuard::copyTo(), TTAMachine::UnconditionalGuard::copyTo(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::ProgramWriter::createCodeSection(), llvm::LLVMTCEBuilder::createGuard(), TTAProgram::CodeGenerator::createInverseGuard(), ProgramDependenceGraph::createJump(), findBooleanGuard(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), TTAProgram::TPEFProgramFactory::findGuard(), RegisterRenamer::findGuardRegisters(), CompiledSimCodeGenerator::generateGuardCondition(), MachineConnectivityCheck::hasBothGuards(), TTAMachine::PortGuard::isEqual(), TTAMachine::RegisterGuard::isEqual(), TTAMachine::UnconditionalGuard::isEqual(), TTAProgram::MoveGuard::isInverted(), TTAMachine::PortGuard::isOpposite(), TTAMachine::RegisterGuard::isOpposite(), ListCompareFunction(), RFGuardDialog::onOK(), BusDialog::onUnconditionalGuard(), BFLateBypassGuard::operator()(), BFEarlyGuardBypass::operator()(), SimProgramBuilder::processMove(), MachineResourceManager::registerFileIndexReference(), RegisterRenamer::renameLiveRange(), MachineResourceManager::rFPortOrFUIndexReference(), BFRenameLiveRange::setGuard(), SimpleIfConverter::successors(), MachineInfo::supportsPortGuardedJump(), BusDialog::updateGuardLists(), and DefaultDecoderGenerator::writeSquashSignalSubstitution().
isLessRestrictive()
bool TTAMachine::Guard::isLessRestrictive (const Guard & guard) const virtual
Checks whether this guard is less restrictive than the given one.
This method is meant for complex (two-term) guards but they are not supported yet, so returns always false.
Parameters
guard The guard to compare.
Returns
False.
Definition at line 124 of file Guard.cc.
{
    return false;
}
isMoreRestrictive()
bool TTAMachine::Guard::isMoreRestrictive (const Guard & guard) const virtual
Checks whether this guard is more restrictive than the given one.
This method is meant for complex (two-term) guards but they are not supported yet, so returns always false.
Parameters
guard The guard to compare.
Returns
False.
Definition at line 109 of file Guard.cc.
{
    return false;
}
isOpposite()
virtual bool TTAMachine::Guard::isOpposite (const Guard & guard) const pure virtual
Implemented in TTAMachine::UnconditionalGuard, TTAMachine::PortGuard, and TTAMachine::RegisterGuard.
Referenced by InputPSocketResource::canAssign(), OutputPSocketResource::canAssign(), PSocketResource::canAssign(), ExecutionPipelineResource::exclusiveMoves(), DataDependenceGraph::isNotAvoidable(), and PostpassOperandSharer::tryRemoveOperandWrite().
loadState()
void TTAMachine::Guard::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState is invalid.
Implements Serializable.
Reimplemented in TTAMachine::PortGuard, TTAMachine::RegisterGuard, and TTAMachine::UnconditionalGuard.
Definition at line 164 of file Guard.cc.
{
    try {
        inverted_ = state->intAttribute(OSKEY_INVERTED);
    } catch (Exception& e) {
        string procName = "Guard::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName,
            e.errorMessage());
    }
}
References Exception::errorMessage(), ObjectState::intAttribute(), inverted_, and OSKEY_INVERTED.
Referenced by Guard(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), and TTAMachine::UnconditionalGuard::loadState().
parentBus()
virtual Bus * TTAMachine::Guard::parentBus () const virtual
Referenced by SimpleIfConverter::canConvert(), ProgrammabilityValidator::checkBooleanRegister(), TTAMachine::PortGuard::copyTo(), TTAMachine::RegisterGuard::copyTo(), TTAMachine::UnconditionalGuard::copyTo(), TTAProgram::CodeGenerator::createInverseGuard(), RegisterRenamer::findGuardRegisters(), ProgrammabilityValidator::findRegisterGuard(), TTAProgram::Move::guardLatency(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), BFScheduleExact::operator()(), TTAMachine::PortGuard::PortGuard(), TTAMachine::PortGuard::PortGuard(), TTAMachine::RegisterGuard::RegisterGuard(), TTAMachine::RegisterGuard::RegisterGuard(), TTAMachine::Bus::removeGuard(), RegisterRenamer::renameLiveRange(), BFRenameLiveRange::setGuard(), setParentBus(), TTAMachine::UnconditionalGuard::UnconditionalGuard(), and TTAMachine::UnconditionalGuard::UnconditionalGuard().
saveState()
ObjectState * TTAMachine::Guard::saveState () const virtual
Saves the state of the object to an ObjectState object.
Returns
The newly created ObjectState object.
Implements Serializable.
Reimplemented in TTAMachine::PortGuard, TTAMachine::RegisterGuard, and TTAMachine::UnconditionalGuard.
Definition at line 149 of file Guard.cc.
                       {
    ObjectState* state = new ObjectState(OSNAME_GUARD);
    state->setAttribute(OSKEY_INVERTED, inverted_);
    return state;
}
References inverted_, OSKEY_INVERTED, OSNAME_GUARD, and ObjectState::setAttribute().
Referenced by TTAMachine::Bus::saveState(), TTAMachine::PortGuard::saveState(), TTAMachine::RegisterGuard::saveState(), and TTAMachine::UnconditionalGuard::saveState().
setParentBus()
virtual void TTAMachine::Guard::setParentBus (Bus * parentBus) inline virtual
Definition at line 60 of file Guard.hh.
{
        parent_ = parentBus;
    }
References parent_, and parentBus().
Member Data Documentation
inverted_
bool TTAMachine::Guard::inverted_ private
Indicated whether the condition term is inverted.
Definition at line 85 of file Guard.hh.
Referenced by loadState(), and saveState().
OSKEY_INVERTED
const string TTAMachine::Guard::OSKEY_INVERTED = "inverted" static
ObjectState attribute key for inverted feature.
Definition at line 77 of file Guard.hh.
Referenced by ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), loadState(), and saveState().
OSNAME_GUARD
const string TTAMachine::Guard::OSNAME_GUARD = "guard" static
ObjectState name for guard.
Definition at line 75 of file Guard.hh.
Referenced by saveState().
parent_
Bus* TTAMachine::Guard::parent_ private
The parent bus of the guard.
Definition at line 87 of file Guard.hh.
Referenced by setParentBus(), and ~Guard().
The documentation for this class was generated from the following files:
Guard.hh
Guard.cc