OpenASIP: TPEF::TPEFRelocSectionWriter Class Reference
TPEF::TPEFRelocSectionWriter Class Reference
#include <TPEFRelocSectionWriter.hh>
Protected Member Functions
TPEFRelocSectionWriter ()
virtual ~TPEFRelocSectionWriter ()
virtual Section::SectionType type () const
virtual void actualWriteData (BinaryStream &stream, const Section *section) const
virtual Word elementSize (const Section *section) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void createKeys (const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFRelocSectionWriter (const TPEFRelocSectionWriter &)
Copying not allowed.
TPEFRelocSectionWriter operator= (const TPEFRelocSectionWriter &)
Assignment not allowed.
Static Private Attributes
static const TPEFRelocSectionWriter instance_
An unique instance of class.
static const Word elementSize_ = 12
The fixed size of reloc element.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes TPEF relocation section to stream.
Definition at line 47 of file TPEFRelocSectionWriter.hh.
Constructor & Destructor Documentation
TPEFRelocSectionWriter() [1/2]
TPEF::TPEFRelocSectionWriter::TPEFRelocSectionWriter () protected
Construction.
Registers itself to SectionWriter.
Definition at line 69 of file TPEFRelocSectionWriter.cc.
                                               : TPEFSectionWriter() {
    registerSectionWriter(this);
}
References TPEF::SectionWriter::registerSectionWriter().
~TPEFRelocSectionWriter()
TPEF::TPEFRelocSectionWriter::~TPEFRelocSectionWriter () protected virtual
Destructor.
Definition at line 76 of file TPEFRelocSectionWriter.cc.
{
}
TPEFRelocSectionWriter() [2/2]
TPEF::TPEFRelocSectionWriter::TPEFRelocSectionWriter (const TPEFRelocSectionWriter &) private
Copying not allowed.
Member Function Documentation
actualWriteData()
void TPEF::TPEFRelocSectionWriter::actualWriteData (BinaryStream & stream, const Section * section) const protected virtual
Writes relocation section in to stream.
Parameters
stream The stream where to write.
section The section to be written.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 96 of file TPEFRelocSectionWriter.cc.
{
    FileOffset startOffset = stream.writePosition();
    // file offset to data of section
    SafePointer::addObjectReference(
        FileOffsetKey(startOffset), section->element(0));
    const RelocSection *rSection =
        dynamic_cast<const RelocSection*>(section);
    assert(rSection != NULL);
    for (Word i = 0; i < section->elementCount(); i++) {
        RelocElement* rElem =
            dynamic_cast<RelocElement*>(section->element(i));
        assert(rElem != NULL);
        // r_offset
        if (rElem->location() != NULL) {
            SectionOffsetReplacer sReplacer(rElem->location());
            sReplacer.resolve();
        } else {
            bool locationOfRelocationMustBeSet = false;
            assert(locationOfRelocationMustBeSet);
        }
        // r_symbol
        if (rElem->symbol() != NULL) {
            SectionIndexReplacer indexReplacer(rElem->symbol(), sizeof(Word));
            indexReplacer.resolve();
        } else {
            bool symbolFieldOfRelocationMustBeSet = false;
            assert(symbolFieldOfRelocationMustBeSet);
        }
        // r_type
        Byte rType = 0;
        // chunked bit on if necessary.
        if (rElem->chunked()) {
            rType = rType | TPEFHeaders::STF_CHUNK;
        }
        // and relocation type
        rType = rType | static_cast<Byte>(rElem->type());
        stream.writeByte(rType);
        // r_asp
        SectionIndexReplacer indexReplacer(rElem->aSpace(), sizeof(Byte));
        indexReplacer.resolve();
        // r_size bit width of the value of element referred by location
        stream.writeByte(rElem->size());
        // r_bitpos for chunked relocations
        stream.writeByte(rElem->bitOffset());
    }
    SectionSizeReplacer::setSize(section,
                                 stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), TPEF::RelocElement::aSpace(), assert, TPEF::RelocElement::bitOffset(), TPEF::RelocElement::chunked(), TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::RelocElement::location(), TPEF::ValueReplacer::resolve(), TPEF::SectionSizeReplacer::setSize(), TPEF::RelocElement::size(), TPEF::TPEFHeaders::STF_CHUNK, TPEF::RelocElement::symbol(), TPEF::RelocElement::type(), TPEF::BinaryStream::writeByte(), and TPEF::BinaryStream::writePosition().
elementSize()
Word TPEF::TPEFRelocSectionWriter::elementSize (const Section * section) const protected virtual
Returns size of element.
Parameters
section Section that is written.
Returns
Size of element of this section.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 169 of file TPEFRelocSectionWriter.cc.
{
    return elementSize_;
}
References elementSize_.
operator=()
TPEFRelocSectionWriter TPEF::TPEFRelocSectionWriter::operator= (const TPEFRelocSectionWriter &) private
Assignment not allowed.
type()
Section::SectionType TPEF::TPEFRelocSectionWriter::type () const protected virtual
Returns the type of the section this writer can write.
Returns
The type of section this writer can write.
Implements TPEF::TPEFSectionWriter.
Definition at line 85 of file TPEFRelocSectionWriter.cc.
{
    return Section::ST_RELOC;
}
References TPEF::Section::ST_RELOC.
writeInfo()
void TPEF::TPEFRelocSectionWriter::writeInfo (BinaryStream & stream, const Section * sect) const protected virtual
Writes Info field of section header.
Parameters
stream The stream where to write.
sect Section to write.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 180 of file TPEFRelocSectionWriter.cc.
{
    const Section* refSection =
        dynamic_cast<const RelocSection*>(sect)->referencedSection();
    SectionIdReplacer idReplacer(refSection);
    idReplacer.resolve();
    stream.writeHalfWord(0);
}
References TPEF::ValueReplacer::resolve(), and TPEF::BinaryStream::writeHalfWord().
Member Data Documentation
elementSize_
const Word TPEF::TPEFRelocSectionWriter::elementSize_ = 12 static private
The fixed size of reloc element.
Definition at line 71 of file TPEFRelocSectionWriter.hh.
Referenced by elementSize().
instance_
const TPEFRelocSectionWriter TPEF::TPEFRelocSectionWriter::instance_ static private
An unique instance of class.
Definition at line 69 of file TPEFRelocSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFRelocSectionWriter.hh
TPEFRelocSectionWriter.cc