OpenASIP: OutputFUResource Class Reference
OutputFUResource Class Reference
#include <OutputFUResource.hh>
Public Member Functions
virtual ~OutputFUResource ()
OutputFUResource (const std::string &name, int opCount, int nopSlotWeight)
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual bool canAssign (const int cycle, const MoveNode &node, const TTAMachine::Port &resultPort) const
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
virtual bool isOutputFUResource () const override
Public Member Functions inherited from FUResource
FUResource (const std::string &name, int operationCount, int nopSlotWeight, unsigned int initiationInterval=0)
virtual ~FUResource ()
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual bool operator< (const SchedulingResource &other) const override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Member Functions
OutputFUResource (const OutputFUResource &)
OutputFUResource & operator= (const OutputFUResource &)
Additional Inherited Members
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model The derived class OutputFUResource
Definition at line 53 of file OutputFUResource.hh.
Constructor & Destructor Documentation
~OutputFUResource()
OutputFUResource::~OutputFUResource () virtual
Empty destructor
Definition at line 56 of file OutputFUResource.cc.
{}
OutputFUResource() [1/2]
OutputFUResource::OutputFUResource (const std::string & name, int opCount, int nopSlotWeight)
Constructor with resource name
Parameters
name Name of resource
Definition at line 49 of file OutputFUResource.cc.
                       :
    FUResource(name, opCount, nopSlotWeight) {}
OutputFUResource() [2/2]
OutputFUResource::OutputFUResource (const OutputFUResource &) private
Member Function Documentation
assign()
void OutputFUResource::assign (const int cycle, MoveNode & node) override virtual
Assign resource to given node for given cycle.
There is actually nothing assigned here, only test that the OutputPSocket of given FU can be assigned.
Parameters
cycle Cycle to assign
node MoveNode assigned
Reimplemented from FUResource.
Definition at line 78 of file OutputFUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource()) {
                SchedulingResource* res = &dependentResource(i, j);
                ExecutionPipelineResource* epRes =
                    dynamic_cast<ExecutionPipelineResource*>(res);
                epRes->assignSource(cycle, node);
                increaseUseCount();
                return;
            }
        }
    }
}
References ExecutionPipelineResource::assignSource(), SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::increaseUseCount(), and SchedulingResource::isExecutionPipelineResource().
Referenced by OutputFUBroker::assign().
canAssign() [1/2]
bool OutputFUResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Not to be used, aborts!
Use version with third OutputPSocket operand!
Reimplemented from FUResource.
Definition at line 64 of file OutputFUResource.cc.
{
    abortWithError("Wrong method. Use canAssign with PSocket!");
    return false;
}
References abortWithError.
Referenced by OutputFUBroker::allAvailableResources().
canAssign() [2/2]
bool OutputFUResource::canAssign (const int cycle, const MoveNode & node, const TTAMachine::Port & resultPort) const virtual
Return true if resource can be assigned for given node in given cycle
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Definition at line 128 of file OutputFUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource()) {
                SchedulingResource* res = &dependentResource(i, j);
                ExecutionPipelineResource* epRes =
                    dynamic_cast<ExecutionPipelineResource*>(res);
                if (!epRes->canAssignSource(cycle, node, resultPort)){
                    return false;
                }
            }
        }
    }
    return true;
}
References ExecutionPipelineResource::canAssignSource(), SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), and SchedulingResource::isExecutionPipelineResource().
isOutputFUResource()
bool OutputFUResource::isOutputFUResource () const override virtual
Allways return true
Returns
true
Reimplemented from SchedulingResource.
Definition at line 153 of file OutputFUResource.cc.
{
    return true;
}
operator=()
OutputFUResource & OutputFUResource::operator= (const OutputFUResource &) private
unassign()
void OutputFUResource::unassign (const int cycle, MoveNode & node) override virtual
Unassign resource from given node for given cycle.
It only tests that OutputPSocket to be unassigned is connected to given FU.
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
Reimplemented from FUResource.
Definition at line 103 of file OutputFUResource.cc.
                    {
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource()) {
                SchedulingResource* res = &dependentResource(i, j);
                ExecutionPipelineResource* epRes =
                    dynamic_cast<ExecutionPipelineResource*>(res);
                epRes->unassignSource(cycle, node);
                decreaseUseCount();
                return;
            }
        }
    }
}
References SchedulingResource::decreaseUseCount(), SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isExecutionPipelineResource(), and ExecutionPipelineResource::unassignSource().
Referenced by OutputFUBroker::unassign().
validateDependentGroups()
bool OutputFUResource::validateDependentGroups () override protected virtual
Tests if all referred resources in dependent groups are of proper types
Returns
true If all resources in dependent groups are input or output PSockets or ExecutionPipeline
Reimplemented from SchedulingResource.
Definition at line 164 of file OutputFUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (!(dependentResource(i, j).isInputPSocketResource() ||
                dependentResource(i, j).isOutputPSocketResource() ||
                dependentResource(i, j).isExecutionPipelineResource())) {
                return false;
            }
        }
    }
    return true;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isExecutionPipelineResource(), SchedulingResource::isInputPSocketResource(), and SchedulingResource::isOutputPSocketResource().
validateRelatedGroups()
bool OutputFUResource::validateRelatedGroups () override protected virtual
Tests if related resource groups are empty
Returns
true If all resources in related resource groups are empty
Reimplemented from SchedulingResource.
Definition at line 183 of file OutputFUResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        if (relatedResourceCount(i) > 0) {
            return false;
        }
    }
    return true;
}
References SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
The documentation for this class was generated from the following files:
OutputFUResource.hh
OutputFUResource.cc