OpenASIP: ProximOptionsCmd Class Reference
ProximOptionsCmd Class Reference
#include <ProximOptionsCmd.hh>
Public Member Functions
ProximOptionsCmd ()
virtual ~ProximOptionsCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximOptionsCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for editing Proxim options.
Creates and shows ProximOptionsDialog.
Definition at line 43 of file ProximOptionsCmd.hh.
Constructor & Destructor Documentation
ProximOptionsCmd()
ProximOptionsCmd::ProximOptionsCmd ()
The Constructor.
Definition at line 46 of file ProximOptionsCmd.cc.
                                  :
    GUICommand(ProximConstants::COMMAND_NAME_EDIT_OPTIONS, NULL) {
}
Referenced by create().
~ProximOptionsCmd()
ProximOptionsCmd::~ProximOptionsCmd () virtual
The Destructor.
Definition at line 55 of file ProximOptionsCmd.cc.
{
}
Member Function Documentation
create()
ProximOptionsCmd * ProximOptionsCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 97 of file ProximOptionsCmd.cc.
{
    return new ProximOptionsCmd();
}
References ProximOptionsCmd().
Do()
bool ProximOptionsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file ProximOptionsCmd.cc.
                     {
    OptionsDialog dialog(
        parentWindow(), wxGetApp().options(), wxGetApp().commandRegistry());
    if (dialog.ShowModal() == wxID_OK) {
        if (wxGetApp().options().toolbarVisibility()) {
            ProximToolbox::mainFrame()->createToolbar();
        }
        ProximToolbox::mainFrame()->createMenubar();
    }
    return true;
}
References ProximMainFrame::createMenubar(), ProximMainFrame::createToolbar(), ProximToolbox::mainFrame(), options, and GUICommand::parentWindow().
icon()
string ProximOptionsCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Implements GUICommand.
Definition at line 108 of file ProximOptionsCmd.cc.
{
    return "options.png";
}
id()
int ProximOptionsCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 86 of file ProximOptionsCmd.cc.
{
    return ProximConstants::COMMAND_EDIT_OPTIONS;
}
References ProximConstants::COMMAND_EDIT_OPTIONS.
isEnabled()
bool ProximOptionsCmd::isEnabled () virtual
This command is always executable.
Returns
Always true.
Implements GUICommand.
Definition at line 119 of file ProximOptionsCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximOptionsCmd.hh
ProximOptionsCmd.cc