OpenASIP: MinimalOpSet Class Reference
MinimalOpSet Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Minimal opset checker and fixer plugin.")
MinimalOpSet ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual bool requiresApplication () const
virtual std::vector< RowID > explore (const RowID &configurationID, const unsigned int &)
void readParameters ()
bool createConfig (const std::string &adf, const std::string &idf, DSDBManager &dsdb, DSDBManager::MachineConfiguration &conf)
Private Attributes
std::string adf_
name of the adf file to evaluate
std::string idf_
name of the idf file to evaluate
bool printMissingOps_
print missing ops
Static Private Attributes
static const std::string adfPN_
static const std::string idfPN_
static const std::string printMissingOpsPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that checks that given config or adf meets minimal opset requirements stated by minimal machine adf or user given reference adf.
Supported parameters:
Definition at line 58 of file MinimalOpSet.cc.
Constructor & Destructor Documentation
MinimalOpSet()
MinimalOpSet::MinimalOpSet () inline private
Definition at line 61 of file MinimalOpSet.cc.
                  : DesignSpaceExplorerPlugin(),
        adf_(""),
        idf_(""),
        printMissingOps_(false) {
        // compulsory parameters
        // no compulsory parameters
        // parameters that have a default value
        addParameter(adfPN_, STRING, false, adf_);
        addParameter(idfPN_, STRING, false, idf_);
        addParameter(printMissingOpsPN_, BOOL, false,
            Conversion::toString(printMissingOps_));
    }
References DesignSpaceExplorerPlugin::addParameter(), adf_, adfPN_, BOOL, idf_, idfPN_, printMissingOps_, printMissingOpsPN_, STRING, and Conversion::toString().
Member Function Documentation
createConfig()
bool MinimalOpSet::createConfig (const std::string & adf, const std::string & idf, DSDBManager & dsdb, DSDBManager::MachineConfiguration & conf) inline private
Load adf and idf from files and store to given dsdb and config.
Parameters
adf Path of architecture definition file.
idf Path of implementation definition file.
dsdb Database where to store adf and idf.
conf Configuration for adf/idf ids.
Returns
True if creating config succeeded, else false.
Definition at line 219 of file MinimalOpSet.cc.
{
        assert(adf != "");
        IDF::MachineImplementation* idfo = NULL;
        TTAMachine::Machine* mach = NULL;
        try {
            if (adf != "") {
                mach = TTAMachine::Machine::loadFromADF(adf);
                conf.architectureID = dsdb.addArchitecture(*mach);
            } else {
                return false;
            }
            if (idf != "") {
                idfo = IDF::MachineImplementation::loadFromIDF(idf);
                conf.implementationID =
                    dsdb.addImplementation(*idfo, 0,0);
                conf.hasImplementation = true;
            } else {
                conf.hasImplementation = false;
            }
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error loading the adf/idf." << std::endl;
            verboseLog(msg.str());
            return false;
        }
        return true;
    }
References DSDBManager::addArchitecture(), DSDBManager::addImplementation(), DSDBManager::MachineConfiguration::architectureID, assert, DSDBManager::MachineConfiguration::hasImplementation, DSDBManager::MachineConfiguration::implementationID, TTAMachine::Machine::loadFromADF(), IDF::MachineImplementation::loadFromIDF(), and verboseLog.
Referenced by explore().
explore()
virtual std::vector< RowID > MinimalOpSet::explore (const RowID & configurationID, const unsigned int &) inline private virtual
Explorer plugin that checks that given config or adf meets minimal opset requirements stated by minimal machine adf or user given reference adf.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 87 of file MinimalOpSet.cc.
{
        readParameters();
        std::vector<RowID> result;
        MinimalOpSetCheck minimalOpSetCheck = MinimalOpSetCheck();
        // make params for adf and idf, so no configuration needed
        if (configurationID == 0 && adf_ == "") {
            std::ostringstream msg(std::ostringstream::out);
            msg << "No configuration nor adf defined. Use -s <confID> to "
                << "define the configuration to be optimized or give adf "
                << "as plugin parameter." << std::endl;
            verboseLog(msg.str());
            return result;
        }
        DSDBManager& dsdb = db();
        DSDBManager::MachineConfiguration conf;
        conf.architectureID = -1;
        conf.hasImplementation = false;
        // load adf/idf from file if no configuration was given
        if (configurationID == 0) {
            if (!createConfig(adf_, idf_, dsdb, conf)) {
               return result;
            }
        } else {
            // if starting configuration given load it
            conf = dsdb.configuration(configurationID);
        }
        // load machine from configuration
        // TODO: load machine from file is adf_ is specified.
        Machine* mach = NULL;
        try {
            mach = dsdb.architecture(conf.architectureID);
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << e.errorMessage() << std::endl;
            verboseLog(msg.str());
            return result;
        }
        // check minimal opset and print missing ops
        if (printMissingOps_) {
            std::vector<std::string> missingOps;
            minimalOpSetCheck.missingOperations(*mach, missingOps);
            if (missingOps.empty()) {
                std::cout << "MinimalOpSet: Configuration/machine has all"
                          << " the operations in the minimal opset already."
                          << std::endl;
                return result;
            }
            for (unsigned int i = 0; i < missingOps.size(); ++i) {
                std::cout << missingOps.at(i) + " : operation is missing."
                          << std::endl;
            }
        }
        // add FUs to the machine, so that it has all the operations in the
        // minimal opset
        try {
            minimalOpSetCheck.fix(*mach);
        } catch (const InvalidData& e) {
            verboseLog("MinimalOpSet: Configuration/machine has all the"
                    "operations in the minimal opset already.")
            return result;
        }
        // create the result config
        DSDBManager::MachineConfiguration newConf;
        newConf.architectureID = dsdb.addArchitecture(*mach);
        newConf.hasImplementation = false;
        // if old config had implementation create a new one for new config
        if (conf.hasImplementation) {
            createImplementation(newConf, newConf);
        }
        CostEstimates estimates;
        bool estimate = (newConf.hasImplementation ? true : false);
        try {
            if (!evaluate(newConf, estimates, estimate)) {
                debugLog(std::string("Evaluate failed."));
                return result;
            }
        } catch (const Exception& e) {
            debugLog(std::string("Error in Evaluate plugin: ")
                    + e.errorMessage() + std::string(" ")
                    + e.errorMessageStack());
            return result;
        }
        RowID newConfID = addConfToDSDB(newConf);
        if (newConfID != 0) {
                result.push_back(newConfID);
        }
        return result;
    }
References DSDBManager::addArchitecture(), DesignSpaceExplorer::addConfToDSDB(), adf_, DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, DSDBManager::configuration(), createConfig(), DesignSpaceExplorer::createImplementation(), DesignSpaceExplorer::db(), debugLog, Exception::errorMessage(), Exception::errorMessageStack(), DesignSpaceExplorer::evaluate(), MinimalOpSetCheck::fix(), DSDBManager::MachineConfiguration::hasImplementation, idf_, MinimalOpSetCheck::missingOperations(), printMissingOps_, readParameters(), and verboseLog.
PLUGIN_DESCRIPTION()
MinimalOpSet::PLUGIN_DESCRIPTION ("Minimal opset checker and fixer plugin.") private
producesArchitecture()
virtual bool MinimalOpSet::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 77 of file MinimalOpSet.cc.
{ return false; }
readParameters()
void MinimalOpSet::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 203 of file MinimalOpSet.cc.
{
        readCompulsoryParameter(adfPN_, adf_);
        readCompulsoryParameter(idfPN_, idf_);
        readCompulsoryParameter(printMissingOpsPN_, printMissingOps_);
    }
References adf_, adfPN_, idf_, idfPN_, printMissingOps_, printMissingOpsPN_, and DesignSpaceExplorerPlugin::readCompulsoryParameter().
Referenced by explore().
requiresApplication()
virtual bool MinimalOpSet::requiresApplication () const inline private virtual
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 80 of file MinimalOpSet.cc.
{ return false; }
requiresHDB()
virtual bool MinimalOpSet::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 78 of file MinimalOpSet.cc.
{ return false; }
requiresSimulationData()
virtual bool MinimalOpSet::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 79 of file MinimalOpSet.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool MinimalOpSet::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 76 of file MinimalOpSet.cc.
{ return false; }
Member Data Documentation
adf_
std::string MinimalOpSet::adf_ private
name of the adf file to evaluate
Definition at line 194 of file MinimalOpSet.cc.
Referenced by explore(), MinimalOpSet(), and readParameters().
adfPN_
const std::string MinimalOpSet::adfPN_ static private
Definition at line 188 of file MinimalOpSet.cc.
Referenced by MinimalOpSet(), and readParameters().
idf_
std::string MinimalOpSet::idf_ private
name of the idf file to evaluate
Definition at line 196 of file MinimalOpSet.cc.
Referenced by explore(), MinimalOpSet(), and readParameters().
idfPN_
const std::string MinimalOpSet::idfPN_ static private
Definition at line 189 of file MinimalOpSet.cc.
Referenced by MinimalOpSet(), and readParameters().
printMissingOps_
bool MinimalOpSet::printMissingOps_ private
print missing ops
Definition at line 198 of file MinimalOpSet.cc.
Referenced by explore(), MinimalOpSet(), and readParameters().
printMissingOpsPN_
const std::string MinimalOpSet::printMissingOpsPN_ static private
Definition at line 190 of file MinimalOpSet.cc.
Referenced by MinimalOpSet(), and readParameters().
The documentation for this class was generated from the following file:
MinimalOpSet.cc