OpenASIP: FindWindow Class Reference
FindWindow Class Reference
#include <FindWindow.hh>
Public Member Functions
FindWindow (ProximMainFrame *parent, int id)
virtual ~FindWindow ()
virtual void reset ()
Private Types
enum {
ID_OP_INPUT , ID_MATCH_CASE , ID_INFO_LABEL , ID_FIND_PREV ,
ID_FIND_NEXT
}
Widget IDs.
Private Member Functions
void onInputText (wxCommandEvent &event)
void onFindPrev (wxCommandEvent &event)
void onFindNext (wxCommandEvent &event)
bool find (std::string searchString)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
wxTextCtrl * opInput_
wxCheckBox * matchCase_
wxStaticText * infoLabel_
wxButton * findPrevBtn_
wxButton * findNextBtn_
std::vector< int > matchedLines
List of code linenumbers where serached text was found.
int matchedIndex
Currently displayed codeline index in matchedLines.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Window for searching text patterns in disassembly instructions.
Definition at line 49 of file FindWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_OP_INPUT
ID_MATCH_CASE
ID_INFO_LABEL
ID_FIND_PREV
ID_FIND_NEXT
Definition at line 75 of file FindWindow.hh.
         {
        ID_OP_INPUT,
        ID_MATCH_CASE,
        ID_INFO_LABEL,
        ID_FIND_PREV,
        ID_FIND_NEXT,
    };
Constructor & Destructor Documentation
FindWindow()
FindWindow::FindWindow (ProximMainFrame * parent, int id)
Definition at line 57 of file FindWindow.cc.
                                                     :
    ProximSimulatorWindow(parent, id) {
    createContents(this, true, true);
    opInput_->SetFocus();
    matchCase_->SetValue(false);
    findPrevBtn_->Disable();
    findNextBtn_->Disable();
}
~FindWindow()
FindWindow::~FindWindow () virtual
Definition at line 68 of file FindWindow.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FindWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 211 of file FindWindow.cc.
{
    wxBoxSizer *mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    opInput_ = new wxTextCtrl(parent, ID_OP_INPUT, wxT(""),
        wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    mainSizer->Add(opInput_, 0, wxALL|wxEXPAND, 5);
    matchCase_ = new wxCheckBox(parent, ID_MATCH_CASE, wxT("Case sensitive"),
        wxDefaultPosition, wxDefaultSize);
    mainSizer->Add(matchCase_, 0, wxALL|wxEXPAND, 5);
    infoLabel_ = new wxStaticText(parent, ID_INFO_LABEL, wxT(""),
        wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    mainSizer->Add(infoLabel_, 0, wxALL|wxEXPAND, 5);
    findPrevBtn_ = new wxButton(parent, ID_FIND_PREV, wxT("Previous"),
        wxDefaultPosition, wxDefaultSize, 0);
    findNextBtn_ = new wxButton(parent, ID_FIND_NEXT, wxT("Find next"),
        wxDefaultPosition, wxDefaultSize, 0);
    buttonSizer->Add(findPrevBtn_, 0, wxALL, 5);
    buttonSizer->Add(findNextBtn_, 0, wxALL, 5);
    mainSizer->Add(buttonSizer, 0, wxALIGN_CENTER|wxALL, 5);
    if (set_sizer) {
        parent->SetSizer(mainSizer);
        if (call_fit) {
            mainSizer->SetSizeHints(parent);
        }
    }
    return mainSizer;
}
References findNextBtn_, findPrevBtn_, ID_FIND_NEXT, ID_FIND_PREV, ID_INFO_LABEL, ID_MATCH_CASE, ID_OP_INPUT, infoLabel_, matchCase_, and opInput_.
find()
bool FindWindow::find (std::string searchString) private
Definition at line 169 of file FindWindow.cc.
{
    const TTAProgram::Program& program = ProximToolbox::program();
    std::size_t found;
    matchedIndex = 0;
    matchedLines.clear();
    for (int i = 0; i < program.instructionCount(); i++) {
        const TTAProgram::Instruction& instruction = program.instructionAt(i);
        std::string instrString = "";
        for (int j = 0; j < instruction.moveCount(); j++) {
            const TTAProgram::Move& move = instruction.move(j);
            instrString += move.toString();
        }
        // remove spaces in instruction and search pattern
        instrString.erase(remove_if(instrString.begin(), instrString.end(),
            isspace), instrString.end());
        pattern.erase(remove_if(pattern.begin(), pattern.end(),
            isspace), pattern.end());
        // case insensitive search
        if (!matchCase_->IsChecked()) {
            std::transform(instrString.begin(), instrString.end(),
                instrString.begin(), ::tolower);
            std::transform(pattern.begin(), pattern.end(), pattern.begin(),
                ::tolower);
        }
        found = instrString.find(pattern);
        if (found != std::string::npos) {
            matchedLines.push_back(i);
        }
    }
    return matchedLines.size() > 0;
}
References matchCase_, matchedIndex, matchedLines, TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), program, ProximToolbox::program(), and TTAProgram::Move::toString().
Referenced by onInputText().
onFindNext()
void FindWindow::onFindNext (wxCommandEvent & event) private
Definition at line 142 of file FindWindow.cc.
{
    int matchedSize = matchedLines.size();
    if (matchedSize == 0) {
        return;
    }
    if (matchedIndex == matchedSize - 1) {
        matchedIndex = 0;
    } else {
        matchedIndex++;
    }
    // update label
    infoLabel_->SetLabel(WxConversion::toWxString(matchedIndex+1) + wxT(" of ") +
        WxConversion::toWxString(matchedSize) + wxT(" matched lines"));
    ProximToolbox::disassemblyWindow()->showAddress(matchedLines[matchedIndex]);
}
References ProximToolbox::disassemblyWindow(), infoLabel_, matchedIndex, matchedLines, ProximDisassemblyWindow::showAddress(), and WxConversion::toWxString().
onFindPrev()
void FindWindow::onFindPrev (wxCommandEvent & event) private
Definition at line 120 of file FindWindow.cc.
{
    int matchedSize = matchedLines.size();
    if (matchedSize == 0) {
        return;
    }
    if (matchedIndex == 0) {
        matchedIndex = matchedSize - 1;
    } else {
        matchedIndex--;
    }
    infoLabel_->SetLabel(WxConversion::toWxString(matchedIndex+1) + wxT(" of ") +
        WxConversion::toWxString(matchedSize) + wxT(" matched lines"));
    ProximToolbox::disassemblyWindow()->showAddress(matchedLines[matchedIndex]);
}
References ProximToolbox::disassemblyWindow(), infoLabel_, matchedIndex, matchedLines, ProximDisassemblyWindow::showAddress(), and WxConversion::toWxString().
onInputText()
void FindWindow::onInputText (wxCommandEvent & event) private
Called when the input text changes or match case checkbox changes state.
Definition at line 84 of file FindWindow.cc.
{
    wxString inputwxString = opInput_->GetValue();
    if (inputwxString.Length() > 2) {
        std::string pattern = WxConversion::toString(inputwxString);
        bool found = find(pattern);
        if (found) {
            findPrevBtn_->Enable();
            findNextBtn_->Enable();
            int total = matchedLines.size();
            // update label
            infoLabel_->SetLabel(wxT("1 of ") + WxConversion::toWxString(total)+
                wxT(" matched lines"));
            // jump to first matched line
            ProximToolbox::disassemblyWindow()->showAddress(matchedLines[0]);
            return;
        } else {
            infoLabel_->SetLabel(wxT("Pattern not found"));
            return;
        }
    }
    infoLabel_->SetLabel(wxT(""));
    findPrevBtn_->Disable();
    findNextBtn_->Disable();
}
References ProximToolbox::disassemblyWindow(), find(), findNextBtn_, findPrevBtn_, infoLabel_, matchedLines, opInput_, ProximDisassemblyWindow::showAddress(), WxConversion::toString(), and WxConversion::toWxString().
reset()
void FindWindow::reset () virtual
Called when the simulator program, memory and machine models are reset.
Reimplemented from ProximSimulatorWindow.
Definition at line 76 of file FindWindow.cc.
                  {
    // Do nothing.
}
Member Data Documentation
findNextBtn_
wxButton* FindWindow::findNextBtn_ private
Definition at line 67 of file FindWindow.hh.
Referenced by createContents(), and onInputText().
findPrevBtn_
wxButton* FindWindow::findPrevBtn_ private
Definition at line 66 of file FindWindow.hh.
Referenced by createContents(), and onInputText().
infoLabel_
wxStaticText* FindWindow::infoLabel_ private
Definition at line 65 of file FindWindow.hh.
Referenced by createContents(), onFindNext(), onFindPrev(), and onInputText().
matchCase_
wxCheckBox* FindWindow::matchCase_ private
Definition at line 64 of file FindWindow.hh.
Referenced by createContents(), and find().
matchedIndex
int FindWindow::matchedIndex private
Currently displayed codeline index in matchedLines.
Definition at line 72 of file FindWindow.hh.
Referenced by find(), onFindNext(), and onFindPrev().
matchedLines
std::vector<int> FindWindow::matchedLines private
List of code linenumbers where serached text was found.
Definition at line 70 of file FindWindow.hh.
Referenced by find(), onFindNext(), onFindPrev(), and onInputText().
opInput_
wxTextCtrl* FindWindow::opInput_ private
Definition at line 63 of file FindWindow.hh.
Referenced by createContents(), and onInputText().
The documentation for this class was generated from the following files:
FindWindow.hh
FindWindow.cc