OpenASIP: TTAMachine::ImmediateSlot Class Reference
TTAMachine::ImmediateSlot Class Reference
#include <ImmediateSlot.hh>
Public Member Functions
ImmediateSlot (const std::string &name, Machine &parent)
ImmediateSlot (const ObjectState *state, Machine &parent)
virtual ~ImmediateSlot ()
int width () const
virtual void setMachine (Machine &machine)
virtual void unsetMachine ()
virtual void setName (const std::string &name)
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_IMMEDIATE_SLOT = "immediate_slot"
ObjectState name for ImmediateSlot.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Immediate slot is a machine component and represents a dedicated long immediate field in the TTA instruction.
Definition at line 44 of file ImmediateSlot.hh.
Constructor & Destructor Documentation
ImmediateSlot() [1/2]
TTAMachine::ImmediateSlot::ImmediateSlot (const std::string & name, Machine & parent)
The constructor.
Parameters
name Name of the immediate slot.
parent The parent machine.
Exceptions
InvalidName If the given name is not a valid component name.
ComponentAlreadyExists If the machine already contains a bus or immediate slot with the same name.
Definition at line 57 of file ImmediateSlot.cc.
    : Component(name) {
    setMachine(parent);
}
References setMachine().
ImmediateSlot() [2/2]
TTAMachine::ImmediateSlot::ImmediateSlot (const ObjectState * state, Machine & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent machine.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ComponentAlreadyExists If the machine already contains a bus or immediate slot with the same name.
Definition at line 75 of file ImmediateSlot.cc.
    : Component(state) {
    const string procName = "ImmediateSlot::ImmediateSlot";
    if (parent.busNavigator().hasItem(name())) {
        MOMTextGenerator textGenerator;
        format text = textGenerator.text(
            MOMTextGenerator::TXT_BUS_AND_IMM_SLOT_WITH_SAME_NAME);
        text % name();
        throw ComponentAlreadyExists(
            __FILE__, __LINE__, procName, text.str());
    }
    if (parent.immediateSlotNavigator().hasItem(name())) {
        MOMTextGenerator textGenerator;
        format text = textGenerator.text(
            MOMTextGenerator::TXT_IMM_SLOT_EXISTS_BY_SAME_NAME);
        text % name();
        throw ComponentAlreadyExists(
            __FILE__, __LINE__, procName, text.str());
    }
    setMachine(parent);
    loadState(state);
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateSlotNavigator(), loadState(), TTAMachine::Component::name(), setMachine(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_BUS_AND_IMM_SLOT_WITH_SAME_NAME, and MOMTextGenerator::TXT_IMM_SLOT_EXISTS_BY_SAME_NAME.
~ImmediateSlot()
TTAMachine::ImmediateSlot::~ImmediateSlot () virtual
The destructor.
Definition at line 103 of file ImmediateSlot.cc.
{
    unsetMachine();
}
References unsetMachine().
Member Function Documentation
loadState()
void TTAMachine::ImmediateSlot::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs when loading the state.
Reimplemented from TTAMachine::Component.
Definition at line 214 of file ImmediateSlot.cc.
{
    if (state->name() != OSNAME_IMMEDIATE_SLOT) {
        const string procName = "ImmediateSlot::loadState";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Component::loadState(state);
}
References TTAMachine::Component::loadState(), ObjectState::name(), and OSNAME_IMMEDIATE_SLOT.
Referenced by ImmediateSlot().
saveState()
ObjectState * TTAMachine::ImmediateSlot::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from TTAMachine::Component.
Definition at line 199 of file ImmediateSlot.cc.
{
    ObjectState* state = Component::saveState();
    state->setName(OSNAME_IMMEDIATE_SLOT);
    return state;
}
References OSNAME_IMMEDIATE_SLOT, TTAMachine::Component::saveState(), and ObjectState::setName().
setMachine()
void TTAMachine::ImmediateSlot::setMachine (Machine & machine) virtual
Registers the immediate slot to a machine.
Parameters
mach Machine to which the immediate slot is going to be registered.
Exceptions
ComponentAlreadyExists If the given machine already has another immediate slot or bus by the same name.
Implements TTAMachine::Component.
Definition at line 142 of file ImmediateSlot.cc.
{
    machine.addImmediateSlot(*this);
    internalSetMachine(machine);
}
References TTAMachine::Machine::addImmediateSlot(), TTAMachine::Component::internalSetMachine(), and TTAMachine::Component::machine().
Referenced by ImmediateSlot(), and ImmediateSlot().
setName()
void TTAMachine::ImmediateSlot::setName (const std::string & name) virtual
Sets the name of the immediate slot.
Parameters
name The new name.
Exceptions
ComponentAlreadyExists If the machine already contains an immediate slot or bus with the same name.
InvalidName If the given name is not a valid component name.
Reimplemented from TTAMachine::Component.
Definition at line 178 of file ImmediateSlot.cc.
{
    if (name == this->name()) {
        return;
    }
    Machine* mach = machine();
    if (mach->immediateSlotNavigator().hasItem(name) ||
        mach->busNavigator().hasItem(name)) {
        const string procName = "ImmediateSlot::setName";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
unsetMachine()
void TTAMachine::ImmediateSlot::unsetMachine () virtual
Removes registration of the immediate slot from its current machine.
Implements TTAMachine::Component.
Definition at line 151 of file ImmediateSlot.cc.
{
    assert(machine() != NULL);
    Machine* mach = machine();
    // delete the template slots that use this slot
    Machine::InstructionTemplateNavigator itNav =
        mach->instructionTemplateNavigator();
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        iTemp->removeSlot(name());
    }
    internalUnsetMachine();
    mach->deleteImmediateSlot(*this);
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::deleteImmediateSlot(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Component::internalUnsetMachine(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::InstructionTemplate::removeSlot().
Referenced by ~ImmediateSlot().
width()
int TTAMachine::ImmediateSlot::width () const
Returns the bit width of the immediate slot.
The bit width is determined by the instruction templates which use the immediate slot.
Returns
The bit width of the immediate slot.
Definition at line 117 of file ImmediateSlot.cc.
{
    int width = 0;
    Machine::InstructionTemplateNavigator itNav =
        machine()->instructionTemplateNavigator();
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        if (iTemp->supportedWidth(name()) > width) {
            width = iTemp->supportedWidth(name());
        }
    }
    return width;
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), TTAMachine::InstructionTemplate::supportedWidth(), and width().
Referenced by BEMGenerator::addTopLevelFields(), BEMValidator::checkImmediateSlot(), and width().
Member Data Documentation
OSNAME_IMMEDIATE_SLOT
const std::string TTAMachine::ImmediateSlot::OSNAME_IMMEDIATE_SLOT = "immediate_slot" static
ObjectState name for ImmediateSlot.
Definition at line 60 of file ImmediateSlot.hh.
Referenced by ADFSerializer::convertToMDFFormat(), ADFSerializer::immediateSlotToMachine(), loadState(), TTAMachine::Machine::loadState(), and saveState().
The documentation for this class was generated from the following files:
ImmediateSlot.hh
ImmediateSlot.cc