OpenASIP: MemoryDialog Class Reference
MemoryDialog Class Reference
#include <MemoryDialog.hh>
Public Member Functions
MemoryDialog (wxWindow *window)
virtual ~MemoryDialog ()
virtual void handleEvent (OSEdInformer::EventId event)
Public Member Functions inherited from OSEdListener
OSEdListener ()
virtual ~OSEdListener ()
Private Types
enum { ID_BUTTON_CLOSE = 1000 , ID_CONTROL_MEMORY }
Private Member Functions
MemoryDialog (const MemoryDialog &)
Copying not allowed.
MemoryDialog & operator= (const MemoryDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *window, bool call_fit, bool set_sizer)
void setTexts ()
void onClose (wxCommandEvent &)
Private Attributes
MemoryControl * memoryWindow_
Memory control of the dialog.
Detailed Description
Dialog for monitoring the contents of the memory.
Definition at line 51 of file MemoryDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_BUTTON_CLOSE
ID_CONTROL_MEMORY
Definition at line 71 of file MemoryDialog.hh.
         {
        ID_BUTTON_CLOSE = 1000,
        ID_CONTROL_MEMORY
    };
Constructor & Destructor Documentation
MemoryDialog() [1/2]
MemoryDialog::MemoryDialog (wxWindow * window)
Constructor.
Parameters
window Parent window.
Definition at line 58 of file MemoryDialog.cc.
                                           :
    wxDialog(window, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_MEMORY),
             wxDefaultSize, wxRESIZE_BORDER) {
    createContents(this, true, true);
    setTexts();
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->registerListener(OSEdInformer::EVENT_MEMORY, this);
}
References OSEdInformer::EVENT_MEMORY, and OSEdInformer::registerListener().
~MemoryDialog()
MemoryDialog::~MemoryDialog () virtual
Destructor.
Definition at line 73 of file MemoryDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_MEMORY, point);
}
References DialogPosition::DIALOG_MEMORY, and DialogPosition::setPosition().
MemoryDialog() [2/2]
MemoryDialog::MemoryDialog (const MemoryDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * MemoryDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the MemoryDialog.
Parameters
parent Parent window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 130 of file MemoryDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    memoryWindow_ = new MemoryControl(
        parent, &OperationContainer::memory(), MemoryDialog::ID_CONTROL_MEMORY);
    item0->Add(memoryWindow_, 1, wxGROW|wxALL, 5);
    wxButton *item1 = new wxButton( parent, ID_BUTTON_CLOSE, wxT("Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BUTTON_CLOSE, ID_CONTROL_MEMORY, OperationContainer::memory(), and memoryWindow_.
handleEvent()
void MemoryDialog::handleEvent (OSEdInformer::EventId event) virtual
Handles event when the contents of the memory might have changed.
Implements OSEdListener.
Definition at line 111 of file MemoryDialog.cc.
{
    switch(event) {
    case OSEdInformer::EVENT_MEMORY:
        memoryWindow_->updateView();
        break;
    default:
        break;
    }
}
References OSEdInformer::EVENT_MEMORY, memoryWindow_, and MemoryControl::updateView().
onClose()
void MemoryDialog::onClose (wxCommandEvent &) private
Handles the event when dialog is closed.
Definition at line 101 of file MemoryDialog.cc.
{
    OSEdInformer* informer = wxGetApp().mainFrame()->informer();
    informer->unregisterListener(OSEdInformer::EVENT_MEMORY, this);
    Close();
}
References OSEdInformer::EVENT_MEMORY, and OSEdInformer::unregisterListener().
operator=()
MemoryDialog & MemoryDialog::operator= (const MemoryDialog &) private
Assignment not allowed.
setTexts()
void MemoryDialog::setTexts () private
Set texts to widgets.
Definition at line 84 of file MemoryDialog.cc.
                       {
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt = osedText.text(OSEdTextGenerator::TXT_MEMORY_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_CLOSE),
                          OSEdTextGenerator::TXT_BUTTON_CLOSE);
}
References ID_BUTTON_CLOSE, OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_BUTTON_CLOSE, and OSEdTextGenerator::TXT_MEMORY_DIALOG_TITLE.
Member Data Documentation
memoryWindow_
MemoryControl* MemoryDialog::memoryWindow_ private
Memory control of the dialog.
Definition at line 77 of file MemoryDialog.hh.
Referenced by createContents(), and handleEvent().
The documentation for this class was generated from the following files:
MemoryDialog.hh
MemoryDialog.cc