OpenASIP: BusTracker Class Reference
BusTracker Class Reference
#include <BusTracker.hh>
Public Member Functions
BusTracker (SimulatorFrontend &frontend, std::ostream *traceStream)
BusTracker (SimulatorFrontend &frontend, std::ostream &traceStream)
virtual ~BusTracker ()
virtual void handleEvent ()
Public Member Functions inherited from Listener
Listener ()
virtual ~Listener ()
virtual void handleEvent (int event)
Private Attributes
SimulatorFrontend & frontend_
the simulator frontend used to access simulation data
bool ownsTraceStream_
std::ostream * traceStream_
Static Private Attributes
static const int COLUMN_WIDTH
static const std::string COLUMN_SEPARATOR = ","
Detailed Description
Tracks the bus activity.
Stores bus data as hexadecimal numbers in a bus trace file in CSV format.
Definition at line 53 of file BusTracker.hh.
Constructor & Destructor Documentation
BusTracker() [1/2]
BusTracker::BusTracker (SimulatorFrontend & frontend, std::ostream * traceStream)
Constructor.
Parameters
frontend The SimulationFrontend which is used to access simulation data.
traceStream Output stream where the trace data is written to. Takes ownership of the stream.
Definition at line 63 of file BusTracker.cc.
                             :
    Listener(), frontend_(frontend),ownsTraceStream_(true),
    traceStream_(traceStream) {
    // write the trace data at the end of simulation clock cycle
    frontend.eventHandler().registerListener(
        SimulationEventHandler::SE_CYCLE_END, this);
}
References SimulatorFrontend::eventHandler(), Informer::registerListener(), and SimulationEventHandler::SE_CYCLE_END.
BusTracker() [2/2]
BusTracker::BusTracker (SimulatorFrontend & frontend, std::ostream & traceStream)
Constructor.
Parameters
frontend The SimulationFrontend which is used to access simulation data.
traceStream Output stream where the trace data is written to.
Definition at line 80 of file BusTracker.cc.
    : Listener(), frontend_(frontend),ownsTraceStream_(false),
      traceStream_(&traceStream) {
    frontend.eventHandler().registerListener(
            SimulationEventHandler::SE_CYCLE_END, this);
}
References SimulatorFrontend::eventHandler(), Informer::registerListener(), and SimulationEventHandler::SE_CYCLE_END.
~BusTracker()
BusTracker::~BusTracker () virtual
Destructor.
Definition at line 92 of file BusTracker.cc.
{
    frontend_.eventHandler().unregisterListener(
        SimulationEventHandler::SE_CYCLE_END, this);
    traceStream_->flush();
    if (ownsTraceStream_) {
        delete traceStream_;
    }
}
References SimulatorFrontend::eventHandler(), frontend_, ownsTraceStream_, SimulationEventHandler::SE_CYCLE_END, traceStream_, and Informer::unregisterListener().
Member Function Documentation
handleEvent()
void BusTracker::handleEvent () virtual
Writes bus trace data to the trace stream.
If any error happens while writing the data, aborts program with an error message.
Reimplemented from Listener.
Definition at line 108 of file BusTracker.cc.
{
    TTAMachine::Machine::BusNavigator navigator =
        frontend_.machine().busNavigator();
    *traceStream_ << frontend_.cycleCount();
    for (int i = 0; i < navigator.count(); ++i) {
        const std::string busName = navigator.item(i)->name();
        BusState& bus = frontend_.machineState(0).busState(busName);
        int columnWidth = (bus.width()+3)/4;
        *traceStream_ << COLUMN_SEPARATOR;
        if (!bus.isSquashed()) {
            *traceStream_ << bus.value().hexValue(true);
        } else {
            // Squashed values are displayed as zeros.
            *traceStream_ << std::string(columnWidth, '0');
        }
    }
    *traceStream_ << "\n";
}
References TTAMachine::Machine::busNavigator(), MachineState::busState(), COLUMN_SEPARATOR, TTAMachine::Machine::Navigator< ComponentType >::count(), SimulatorFrontend::cycleCount(), frontend_, SimValue::hexValue(), BusState::isSquashed(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), SimulatorFrontend::machineState(), traceStream_, RegisterState::value(), and BusState::width().
Member Data Documentation
COLUMN_SEPARATOR
const std::string BusTracker::COLUMN_SEPARATOR = "," static private
Definition at line 67 of file BusTracker.hh.
Referenced by handleEvent().
COLUMN_WIDTH
const int BusTracker::COLUMN_WIDTH static private
Definition at line 66 of file BusTracker.hh.
frontend_
SimulatorFrontend& BusTracker::frontend_ private
the simulator frontend used to access simulation data
Definition at line 69 of file BusTracker.hh.
Referenced by handleEvent(), and ~BusTracker().
ownsTraceStream_
bool BusTracker::ownsTraceStream_ private
Definition at line 70 of file BusTracker.hh.
Referenced by ~BusTracker().
traceStream_
std::ostream* BusTracker::traceStream_ private
Definition at line 71 of file BusTracker.hh.
Referenced by handleEvent(), and ~BusTracker().
The documentation for this class was generated from the following files:
BusTracker.hh
BusTracker.cc