OpenASIP: IDF::NullUnitImplementationLocation Class Reference
IDF::NullUnitImplementationLocation Class Reference
#include <NullUnitImplementationLocation.hh>
Public Member Functions
virtual std::string hdbFile () const
virtual int id () const
virtual std::string unitName () const
virtual void setParent (MachineImplementation &parent)
Public Member Functions inherited from IDF::UnitImplementationLocation
UnitImplementationLocation (const std::string &hdbFile, int id, const std::string &unitName)
UnitImplementationLocation (const ObjectState *state)
virtual ~UnitImplementationLocation ()
std::string hdbFileOriginal () const
virtual void setID (int id)
virtual void setHDBFile (std::string file)
void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static NullUnitImplementationLocation & instance ()
Protected Member Functions
NullUnitImplementationLocation ()
virtual ~NullUnitImplementationLocation ()
Static Private Attributes
static NullUnitImplementationLocation instance_
Additional Inherited Members
Static Public Attributes inherited from IDF::UnitImplementationLocation
static const std::string OSNAME_UNIT_IMPLEMENTATION
ObjectState name for unit implementation.
static const std::string OSKEY_HDB_FILE = "hdb_file"
ObjectState attribute key for the name of the HDB file.
static const std::string OSKEY_ID = "id"
ObjectState attribute key for the entry ID.
static const std::string OSKEY_UNIT_NAME = "unit_name"
Objectstate attribute key for the name of the unit.
Detailed Description
Indicates what implementation of a unit is used.
A null class that indicates of unset location of implementation or no implementation available.
Definition at line 47 of file NullUnitImplementationLocation.hh.
Constructor & Destructor Documentation
NullUnitImplementationLocation()
IDF::NullUnitImplementationLocation::NullUnitImplementationLocation () protected
The constructor.
Definition at line 47 of file NullUnitImplementationLocation.cc.
                                                               :
    UnitImplementationLocation("", 0, "") {
}
~NullUnitImplementationLocation()
IDF::NullUnitImplementationLocation::~NullUnitImplementationLocation () protected virtual
The destructor.
Definition at line 55 of file NullUnitImplementationLocation.cc.
{
}
Member Function Documentation
hdbFile()
std::string IDF::NullUnitImplementationLocation::hdbFile () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from IDF::UnitImplementationLocation.
Definition at line 76 of file NullUnitImplementationLocation.cc.
{
    abortWithError("NullUnitImplementationLocation::hdbFile");
    return "";
}
References abortWithError.
id()
int IDF::NullUnitImplementationLocation::id () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from IDF::UnitImplementationLocation.
Definition at line 87 of file NullUnitImplementationLocation.cc.
{
    abortWithError("NullUnitImplementationLocation::id");
    return 0;
}
References abortWithError.
instance()
NullUnitImplementationLocation & IDF::NullUnitImplementationLocation::instance () static
Returns the only instance of NullUnitImplementationLocation.
Returns
The instance.
Definition at line 65 of file NullUnitImplementationLocation.cc.
{
    return instance_;
}
References instance_.
Referenced by CostEstimator::Estimator::longestPath(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), and CostEstimator::Estimator::totalEnergyOfRegisterFiles().
setParent()
void IDF::NullUnitImplementationLocation::setParent (MachineImplementation & parent) virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from IDF::UnitImplementationLocation.
Definition at line 111 of file NullUnitImplementationLocation.cc.
{
    abortWithError("NullUnitImplementationLocation::setParent");
}
References abortWithError.
unitName()
std::string IDF::NullUnitImplementationLocation::unitName () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from IDF::UnitImplementationLocation.
Definition at line 99 of file NullUnitImplementationLocation.cc.
{
    abortWithError("NullUnitImplementationLocation::unitName");
    return "";
}
References abortWithError.
Member Data Documentation
instance_
NullUnitImplementationLocation IDF::NullUnitImplementationLocation::instance_ static private
Definition at line 62 of file NullUnitImplementationLocation.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullUnitImplementationLocation.hh
NullUnitImplementationLocation.cc