OpenASIP: EditPartFactory Class Reference
EditPartFactory Class Reference
#include <EditPartFactory.hh>
Public Member Functions
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)=0
Returns an EditPart that corresponds to a Machine component.
Protected Member Functions
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes
static std::vector< EditPart * > created_
Container for already created EditParts.
Private Member Functions
EditPartFactory & operator= (EditPartFactory &old)
Assignment not allowed.
EditPartFactory (EditPartFactory &old)
Copying not allowed.
Detailed Description
Abstract base class for EditPart factories that create appropriate EditParts from Machine components.
Definition at line 48 of file EditPartFactory.hh.
Constructor & Destructor Documentation
~EditPartFactory()
EditPartFactory::~EditPartFactory () virtual
The Destructor.
Definition at line 57 of file EditPartFactory.cc.
{
    // erase data of already created EditParts
    created_.clear();
    SequenceTools::deleteAllItems(factories_);
}
References created_, SequenceTools::deleteAllItems(), and factories_.
EditPartFactory() [1/2]
EditPartFactory::EditPartFactory (EditPolicyFactory & editPolicyFactory) protected
The Constructor.
Definition at line 49 of file EditPartFactory.cc.
                                                                    :
    Factory(),
    editPolicyFactory_(editPolicyFactory) {
}
EditPartFactory() [2/2]
EditPartFactory::EditPartFactory (EditPartFactory & old) private
Copying not allowed.
Member Function Documentation
checkCache()
EditPart * EditPartFactory::checkCache (const TTAMachine::MachinePart * component) const protected
Checks if an EditPart of the given component has already been created and returns it.
Parameters
component A machine component to check.
Returns
An EditPart of the given machine component if such has already been created, NULL otherwise.
Definition at line 72 of file EditPartFactory.cc.
{
    // check if an EditPart has already been created of the component
    vector<EditPart*>::const_iterator i = created_.begin();
    for (; i != created_.end(); i++) {
        if ((*i)->model() == component) {
            return *i;
        }
    }
    return NULL;
}
References created_.
Referenced by BusFactory::createEditPart(), MachineEditPartFactory::createEditPart(), and SocketFactory::createEditPart().
operator=()
EditPartFactory & EditPartFactory::operator= (EditPartFactory & old) private
Assignment not allowed.
registerFactory()
void EditPartFactory::registerFactory (Factory * factory)
Referenced by BridgeFactory::BridgeFactory(), BusFactory::BusFactory(), FUFactory::FUFactory(), GCUFactory::GCUFactory(), IUFactory::IUFactory(), MachineEditPartFactory::MachineEditPartFactory(), RFFactory::RFFactory(), SegmentFactory::SegmentFactory(), and UnitPortFactory::UnitPortFactory().
writeToCache()
void EditPartFactory::writeToCache (EditPart * editPart) protected
Inserts an EditPart to the EditPart cache.
Parameters
editPart The EditPart to insert.
Definition at line 89 of file EditPartFactory.cc.
{
    created_.push_back(editPart);
}
References created_.
Referenced by BusFactory::createEditPart(), MachineEditPartFactory::createEditPart(), and SocketFactory::createEditPart().
Member Data Documentation
created_
vector< EditPart * > EditPartFactory::created_ static protected
Container for already created EditParts.
Definition at line 62 of file EditPartFactory.hh.
Referenced by checkCache(), writeToCache(), and ~EditPartFactory().
editPolicyFactory_
EditPolicyFactory& EditPartFactory::editPolicyFactory_ protected
Factory which creates edit policies for edit parts.
Definition at line 64 of file EditPartFactory.hh.
Referenced by MachineEditPartFactory::createBiDirBridge(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), SocketFactory::createEditPart(), and UnitPortFactory::createEditPart().
factories_
std::vector<Factory*> EditPartFactory::factories_ protected
Registered factories.
Definition at line 60 of file EditPartFactory.hh.
Referenced by UnitPortFactory::addSocket(), BridgeFactory::createEditPart(), BusFactory::createEditPart(), FUFactory::createEditPart(), GCUFactory::createEditPart(), IUFactory::createEditPart(), MachineEditPartFactory::createEditPart(), RFFactory::createEditPart(), SegmentFactory::createEditPart(), and ~EditPartFactory().
The documentation for this class was generated from the following files:
EditPartFactory.hh
EditPartFactory.cc