OpenASIP: SocketBusConnFigure Class Reference
SocketBusConnFigure Class Reference
#include <SocketBusConnFigure.hh>
Public Member Functions
SocketBusConnFigure ()
virtual ~SocketBusConnFigure ()
Public Member Functions inherited from ConnectionFigure
virtual ~ConnectionFigure ()
void setSource (Figure *figure)
void setTarget (Figure *figure)
Figure * source () const
Figure * target () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
virtual void drawConnection (wxDC *dc)
virtual void layoutSelf (wxDC *dc)
Protected Member Functions inherited from ConnectionFigure
ConnectionFigure ()
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutChildren (wxDC *)
Private Member Functions
SocketBusConnFigure & operator= (SocketBusConnFigure &old)
Assignment not allowed.
SocketBusConnFigure (SocketBusConnFigure &old)
Copying not allowed.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(0, 0, 0)
Default colour for the figure.
Additional Inherited Members
Protected Attributes inherited from ConnectionFigure
Figure * source_
Source of connection.
Figure * target_
Target of connection.
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a socket-to-bus connection.
Definition at line 46 of file SocketBusConnFigure.hh.
Constructor & Destructor Documentation
SocketBusConnFigure() [1/2]
SocketBusConnFigure::SocketBusConnFigure ()
The Constructor.
Definition at line 45 of file SocketBusConnFigure.cc.
                                        : ConnectionFigure() {
}
~SocketBusConnFigure()
SocketBusConnFigure::~SocketBusConnFigure () virtual
The Destructor.
Definition at line 51 of file SocketBusConnFigure.cc.
{
}
SocketBusConnFigure() [2/2]
SocketBusConnFigure::SocketBusConnFigure (SocketBusConnFigure & old) private
Copying not allowed.
Member Function Documentation
drawConnection()
void SocketBusConnFigure::drawConnection (wxDC * dc) protected virtual
Draws the connection's Figure on the give device context.
Definition at line 74 of file SocketBusConnFigure.cc.
{
    int xOffset = source_->bounds().GetWidth()/2;
    int yOffset = target_->bounds().GetHeight()/2;
    // assumes that socket is always "source"
    dc->DrawCircle(source_->location().x + xOffset,
           target_->location().y + yOffset,
           size_.GetWidth()/2);
}
References Figure::bounds(), Figure::location(), Figure::size_, ConnectionFigure::source_, and ConnectionFigure::target_.
Referenced by drawSelf(), and SocketBusConnToolFigure::drawSelf().
drawSelf()
void SocketBusConnFigure::drawSelf (wxDC * dc) protected virtual
Draws the connection's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from Figure.
Reimplemented in SocketBusConnToolFigure.
Definition at line 60 of file SocketBusConnFigure.cc.
{
    assert(source_ != NULL && target_ != NULL);
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    wxBrush brush = wxBrush(DEFAULT_COLOUR, wxSOLID);
    dc->SetPen(pen);
    dc->SetBrush(brush);
    drawConnection(dc);
}
References assert, DEFAULT_COLOUR, drawConnection(), ConnectionFigure::source_, and ConnectionFigure::target_.
layoutSelf()
void SocketBusConnFigure::layoutSelf (wxDC * dc) protected virtual
Sets the figure's bounds.
Reimplemented from Figure.
Definition at line 90 of file SocketBusConnFigure.cc.
{
    setLocation(
        wxPoint(
            source_->location().x,
            target_->location().y +
            (target_->bounds().GetHeight()/2) -
            (MachineCanvasLayoutConstraints::SOCKET_WIDTH / 2)));
    int size = std::max(std::min(source_->bounds().GetWidth(),
                                 (MachineCanvasLayoutConstraints::BUS_SPACE)),
                        (MachineCanvasLayoutConstraints::SOCKET_WIDTH));
    setWidth(size);
    setHeight(size);
}
References Figure::bounds(), MachineCanvasLayoutConstraints::BUS_SPACE, Figure::location(), Figure::setHeight(), Figure::setLocation(), Figure::setWidth(), MachineCanvasLayoutConstraints::SOCKET_WIDTH, ConnectionFigure::source_, and ConnectionFigure::target_.
operator=()
SocketBusConnFigure & SocketBusConnFigure::operator= (SocketBusConnFigure & old) private
Assignment not allowed.
Member Data Documentation
DEFAULT_COLOUR
const wxColour SocketBusConnFigure::DEFAULT_COLOUR = wxColour(0, 0, 0) static private
Default colour for the figure.
Definition at line 63 of file SocketBusConnFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
SocketBusConnFigure.hh
SocketBusConnFigure.cc