OpenASIP: POMValidatorResults Class Reference
POMValidatorResults Class Reference
#include <POMValidatorResults.hh>
Public Types
typedef std::pair< POMValidator::ErrorCode, std::string > Error
Public Member Functions
POMValidatorResults ()
virtual ~POMValidatorResults ()
int errorCount () const
Error error (int index) const
void addError (POMValidator::ErrorCode code, const std::string &errorMsg)
Private Attributes
std::vector< Error > errors_
Vector storing the errors.
Detailed Description
Class for storing POMValidator results.
Definition at line 45 of file POMValidatorResults.hh.
Member Typedef Documentation
Error
typedef std::pair<POMValidator::ErrorCode, std::string> POMValidatorResults::Error
Definition at line 47 of file POMValidatorResults.hh.
Constructor & Destructor Documentation
POMValidatorResults()
POMValidatorResults::POMValidatorResults ()
The constructor.
Definition at line 38 of file POMValidatorResults.cc.
{
}
~POMValidatorResults()
POMValidatorResults::~POMValidatorResults () virtual
The destructor.
Definition at line 45 of file POMValidatorResults.cc.
{
}
Member Function Documentation
addError()
void POMValidatorResults::addError (POMValidator::ErrorCode code, const std::string & errorMsg)
Adds an error to the results.
Parameters
code The error code.
errorMsg The error message.
Definition at line 84 of file POMValidatorResults.cc.
{
    Error error(code, errorMsg);
    errors_.push_back(error);
}
References error(), and errors_.
Referenced by POMValidator::checkCompiledSimulatability(), POMValidator::checkConnectivity(), POMValidator::checkLongImmediates(), and POMValidator::checkSimulatability().
error()
POMValidatorResults::Error POMValidatorResults::error (int index) const
Returns an error by the given index.
Parameters
index The index.
Returns
The error.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 69 of file POMValidatorResults.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return errors_[index];
}
References __func__, errorCount(), and errors_.
Referenced by addError().
errorCount()
int POMValidatorResults::errorCount () const
Returns the number of errors.
Returns
The number of errors.
Definition at line 55 of file POMValidatorResults.cc.
{
    return errors_.size();
}
References errors_.
Referenced by error().
Member Data Documentation
errors_
std::vector<Error> POMValidatorResults::errors_ private
Vector storing the errors.
Definition at line 59 of file POMValidatorResults.hh.
Referenced by addError(), error(), and errorCount().
The documentation for this class was generated from the following files:
POMValidatorResults.hh
POMValidatorResults.cc