OpenASIP: BFUnscheduleFromBody Class Reference
BFUnscheduleFromBody Class Reference
#include <BFUnscheduleFromBody.hh>
Public Member Functions
BFUnscheduleFromBody (BF2Scheduler &sched, MoveNode &mn)
void unscheduleOriginal ()
void undoOnlyMe () override
bool operator() () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
void returnOriginal ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes
MoveNode & mn_
int oldCycle_
const TTAMachine::Bus * oldBus_
int oldImmWriteCycle_
const TTAMachine::FunctionUnit * dstFU_
const TTAMachine::FunctionUnit * srcFU_
const TTAMachine::ImmediateUnit * immu_
int immRegIndex_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes
static int recurseCounter_ = 0
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Detailed Description
Definition at line 48 of file BFUnscheduleFromBody.hh.
Constructor & Destructor Documentation
BFUnscheduleFromBody()
BFUnscheduleFromBody::BFUnscheduleFromBody (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 51 of file BFUnscheduleFromBody.hh.
                                           :
        BFOptimization(sched), mn_(mn),
        oldImmWriteCycle_(-1), dstFU_(NULL),
        srcFU_(NULL), immu_(NULL), immRegIndex_(-1) {}
Member Function Documentation
operator()()
bool BFUnscheduleFromBody::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 144 of file BFUnscheduleFromBody.cc.
{
    unscheduleOriginal();
    return true;
}
References unscheduleOriginal().
returnOriginal()
void BFUnscheduleFromBody::returnOriginal () protected
Definition at line 96 of file BFUnscheduleFromBody.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\treturning original: " <<mn_.toString()<<" current bus: "
              << mn_.move().bus().name() << " old bus: " << oldBus_->name()
              << " cycle: " << oldCycle_ << std::endl;
#endif
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    if (!rm().canAssign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_,
                        oldImmWriteCycle_, immu_, immRegIndex_)) {
        std::cerr << "Cannot return to old cycle: " << mn_.toString()
                  << " cycle: " << oldCycle_  << std::endl;
        if (mn_.isDestinationOperation()) {
            std::cerr << "dstPO: " << mn_.destinationOperation().toString()
                      << std::endl;
        }
        if (mn_.isSourceOperation()) {
            std::cerr << "srcPO: " << mn_.sourceOperation().toString()
                      << std::endl;
        }
        std::cerr << "Original bus: " << oldBus_->name() << std::endl;
        ddg().writeToDotFile("cannot_return_old_cycle.dot");
        TTAProgram::Instruction* ins = rm().instruction(oldCycle_);
        for (int i = 0; i < ins->moveCount(); i++) {
            std::cerr << "\t" << POMDisassembler::disassemble(ins->move(i))
                      << " bus: " << ins->move(i).bus().name()
                      << std::endl;
        }
        std::cerr << "ins contains " << ins->immediateCount()
                  << " immediates." << std::endl;
        assert(false);
    }
#endif
    rm().assign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_,
       oldImmWriteCycle_, immu_, immRegIndex_);
}
References assert, SimpleResourceManager::assign(), TTAProgram::Move::bus(), BFOptimization::canAssign(), BFOptimization::ddg(), MoveNode::destinationOperation(), POMDisassembler::disassemble(), dstFU_, TTAProgram::Instruction::immediateCount(), immRegIndex_, immu_, SimpleResourceManager::instruction(), MoveNode::isDestinationOperation(), MoveNode::isSourceOperation(), mn_, MoveNode::move(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), TTAMachine::Component::name(), oldBus_, oldCycle_, oldImmWriteCycle_, recurseCounter_, BFOptimization::rm(), MoveNode::sourceOperation(), srcFU_, MoveNode::toString(), ProgramOperation::toString(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Referenced by undoOnlyMe().
undoOnlyMe()
void BFUnscheduleFromBody::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 136 of file BFUnscheduleFromBody.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "BFUnscheudleMove undo" << std::endl;
#endif
    returnOriginal();
}
References returnOriginal().
unscheduleOriginal()
void BFUnscheduleFromBody::unscheduleOriginal ()
Definition at line 48 of file BFUnscheduleFromBody.cc.
{
    oldCycle_ = mn_.cycle();
    oldBus_ = &mn_.move().bus();
    if (mn_.isSourceOperation()) {
        srcFU_ = &mn_.move().source().functionUnit();
    }
    if (mn_.isDestinationOperation()) {
        dstFU_ = &mn_.move().destination().functionUnit();
    }
    if (mn_.move().source().isImmediateRegister()) {
        oldImmWriteCycle_ = rm().immediateWriteCycle(mn_);
        immRegIndex_ = mn_.move().source().index();
        immu_ = &mn_.move().source().immediateUnit();
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\tUnscheduling original: " << mn_.toString()
              << " bus: " << oldBus_->name() << std::endl;
#endif
    rm().unassign(mn_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    if (!rm().canAssign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_,
                   oldImmWriteCycle_)) {
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tCannot assign to old cycle: " << mn_.toString()
                  << " old cycle: " << oldCycle_ << std::endl;
        ddg().writeToDotFile("cannot_assign_old_cycle.dot");
        if (mn_.isSourceOperation()) {
            std::cerr << "\t\twhole src PO: "
                      << mn_.sourceOperation().toString() << std::endl;
        }
        if (mn_.isDestinationOperation()) {
            std::cerr << "\t\twhole dst PO: "
                      << mn_.destinationOperation().toString() << std::endl;
        }
        assert(false);
    }
#endif
}
References assert, TTAProgram::Move::bus(), BFOptimization::canAssign(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), MoveNode::destinationOperation(), dstFU_, TTAProgram::Terminal::functionUnit(), TTAProgram::Terminal::immediateUnit(), SimpleResourceManager::immediateWriteCycle(), immRegIndex_, immu_, TTAProgram::Terminal::index(), MoveNode::isDestinationOperation(), TTAProgram::Terminal::isImmediateRegister(), MoveNode::isSourceOperation(), mn_, MoveNode::move(), TTAMachine::Component::name(), oldBus_, oldCycle_, oldImmWriteCycle_, recurseCounter_, BFOptimization::rm(), TTAProgram::Move::source(), MoveNode::sourceOperation(), srcFU_, MoveNode::toString(), ProgramOperation::toString(), SimpleResourceManager::unassign(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Referenced by operator()().
Member Data Documentation
dstFU_
const TTAMachine::FunctionUnit* BFUnscheduleFromBody::dstFU_ protected
Definition at line 65 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
immRegIndex_
int BFUnscheduleFromBody::immRegIndex_ protected
Definition at line 68 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
immu_
const TTAMachine::ImmediateUnit* BFUnscheduleFromBody::immu_ protected
Definition at line 67 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
mn_
MoveNode& BFUnscheduleFromBody::mn_ protected
Definition at line 61 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
oldBus_
const TTAMachine::Bus* BFUnscheduleFromBody::oldBus_ protected
Definition at line 63 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
oldCycle_
int BFUnscheduleFromBody::oldCycle_ protected
Definition at line 62 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
oldImmWriteCycle_
int BFUnscheduleFromBody::oldImmWriteCycle_ protected
Definition at line 64 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
recurseCounter_
int BFUnscheduleFromBody::recurseCounter_ = 0 static protected
Definition at line 69 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
srcFU_
const TTAMachine::FunctionUnit* BFUnscheduleFromBody::srcFU_ protected
Definition at line 66 of file BFUnscheduleFromBody.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
The documentation for this class was generated from the following files:
BFUnscheduleFromBody.hh
BFUnscheduleFromBody.cc