OpenASIP: ProGe::GlobalPackage Class Reference
ProGe::GlobalPackage Class Reference
#include <GlobalPackage.hh>
Public Member Functions
GlobalPackage ()=delete
GlobalPackage (const std::string &entityName)
virtual ~GlobalPackage ()
const std::string name () const
const std::string fetchBlockAddressWidth () const
const std::string fetchBlockDataWidth () const
const std::string fetchBlockMAUWidth () const
const std::string instructionDataWidth () const
Private Attributes
std::string entityName_
The entity name.
Detailed Description
Definition at line 45 of file GlobalPackage.hh.
Constructor & Destructor Documentation
GlobalPackage() [1/2]
ProGe::GlobalPackage::GlobalPackage () delete
GlobalPackage() [2/2]
ProGe::GlobalPackage::GlobalPackage (const std::string & entityName)
Definition at line 38 of file GlobalPackage.cc.
    : entityName_(entityName) {}
~GlobalPackage()
ProGe::GlobalPackage::~GlobalPackage () virtual
Definition at line 41 of file GlobalPackage.cc.
{}
Member Function Documentation
fetchBlockAddressWidth()
const std::string ProGe::GlobalPackage::fetchBlockAddressWidth () const
Returns name of the constant that defines address width of instruction block visible outside the core.
Definition at line 56 of file GlobalPackage.cc.
{
    return "IMEMADDRWIDTH";
}
Referenced by ProGe::ProcessorWrapperBlock::addInstructionMemory().
fetchBlockDataWidth()
const std::string ProGe::GlobalPackage::fetchBlockDataWidth () const
Returns name of the constant that defines instruction block width visible outside the core.
Definition at line 65 of file GlobalPackage.cc.
{
    return "IMEMDATAWIDTH";
}
Referenced by ProGe::ProcessorWrapperBlock::addInstructionMemory().
fetchBlockMAUWidth()
const std::string ProGe::GlobalPackage::fetchBlockMAUWidth () const
Returns name of the constant that defines instruction block width in MAUs.
Definition at line 73 of file GlobalPackage.cc.
{
    return "IMEMWIDTHINMAUS";
}
instructionDataWidth()
const std::string ProGe::GlobalPackage::instructionDataWidth () const
Return name of the constant that defines raw width of instruction.
Definition at line 81 of file GlobalPackage.cc.
{
    return "INSTRUCTIONWIDTH";
}
name()
const std::string ProGe::GlobalPackage::name () const
Return name of this package.
Definition at line 47 of file GlobalPackage.cc.
{
    return entityName_ + "_globals";
}
References entityName_.
Referenced by ProGe::ProcessorWrapperBlock::ProcessorWrapperBlock().
Member Data Documentation
entityName_
std::string ProGe::GlobalPackage::entityName_ private
The entity name.
Definition at line 70 of file GlobalPackage.hh.
Referenced by name().
The documentation for this class was generated from the following files:
GlobalPackage.hh
GlobalPackage.cc