OpenASIP: TCEString Class Reference
TCEString Class Reference
#include <TCEString.hh>
Classes
struct ICLess
Public Member Functions
TCEString ()
TCEString (const char *text)
TCEString (const std::string &text)
TCEString (const char c)
virtual ~TCEString ()
TCEString & replaceString (const std::string &old, const std::string &newString)
bool startsWith (const std::string &str) const
bool endsWith (const std::string &str) const
bool ciEqual (const TCEString &other) const
std::vector< TCEString > split (const std::string &delim) const
TCEString & appendIf (bool expression, stringCRef ifTrue)
TCEString lower () const
TCEString upper () const
TCEString capitalize () const
TCEString operator+ (int val) const
TCEString operator+ (char c) const
TCEString & operator<< (const TCEString &rhs)
TCEString & operator<< (const char *rhs)
TCEString & operator<< (const int rhs)
Static Public Member Functions
static TCEString toUpper (const TCEString &str, const std::locale &loc=std::locale())
static std::string toUpper (const std::string &str, const std::locale &loc=std::locale())
static TCEString & toUpper (TCEString &str, const std::locale &loc=std::locale())
static std::string & toUpper (std::string &str, const std::locale &loc=std::locale())
static std::string toLower (const std::string &str, const std::locale &loc=std::locale())
static std::string & appendToNonEmpty (std::string &toAppend, stringCRef appender)
static std::string appendToNonEmpty (stringCRef toAppend, stringCRef appender)
static std::string applyIf (bool expression, stringCRef ifTrue, stringCRef ifFalse)
static std::string applyIf (bool expression, stringCRef ifTrue)
template<typename IntegerType >
static std::string & appendInteger (std::string &toAppend, const IntegerType &appender)
template<typename IntegerType >
static std::string appendInteger (stringCRef toAppend, const IntegerType &appender)
template<typename IterableContainer >
static std::string makeString (const IterableContainer &container, const std::string &separator=", ")
static unsigned replace (std::string &str, const std::string &oldPattern, const std::string &newPattern)
static std::string filterDigits (const std::string &str)
static std::string intToHexString (int num)
static std::string unsignedToHexString (unsigned num)
Detailed Description
A simple wrapper around std::string to make forward declarations possible.
Also provides additional string helpers.
Definition at line 53 of file TCEString.hh.
Constructor & Destructor Documentation
TCEString() [1/4]
TCEString::TCEString ()
Definition at line 40 of file TCEString.cc.
                     : std::string() {
}
Referenced by operator+(), operator+(), and operator<<().
TCEString() [2/4]
TCEString::TCEString (const char * text)
Definition at line 43 of file TCEString.cc.
                                     : std::string(text) {
}
TCEString() [3/4]
TCEString::TCEString (const std::string & text)
Definition at line 46 of file TCEString.cc.
                                          : std::string(text) {
}
TCEString() [4/4]
TCEString::TCEString (const char c)
Definition at line 49 of file TCEString.cc.
                                 : std::string(std::string("") + c) {
}
~TCEString()
TCEString::~TCEString () virtual
Definition at line 52 of file TCEString.cc.
                      {
}
Member Function Documentation
appendIf()
TCEString & TCEString::appendIf (bool expression, stringCRef ifTrue)
Definition at line 119 of file TCEString.cc.
{
    if (expression) {
        append(ifTrue);
    }
    return *this;
}
appendInteger() [1/2]
template<typename IntegerType > static std::string & TCEString::appendInteger (std::string & toAppend, const IntegerType & appender) static
appendInteger() [2/2]
template<typename IntegerType > static std::string TCEString::appendInteger (stringCRef toAppend, const IntegerType & appender) static
appendToNonEmpty() [1/2]
std::string & TCEString::appendToNonEmpty (std::string & toAppend, stringCRef appender) static
Appends a string if the target string is not empty.
Parameters
toAppend The target string.
appender The string to append with.
Returns
Reference to original possibly appended with appender.
Definition at line 201 of file TCEString.cc.
{
    if (!toAppend.empty()) {
        return toAppend += appender;
    } else {
        return toAppend;
    }
}
Referenced by appendToNonEmpty(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
appendToNonEmpty() [2/2]
std::string TCEString::appendToNonEmpty (stringCRef toAppend, stringCRef appender) static
Returns string of target string appended with another string if the target string is not empty.
Parameters
toAppend The target string.
appender The string to append with.
Returns
String initialized with toAppend and possibly appended with appender.
Definition at line 219 of file TCEString.cc.
{
    std::string tmp(toAppend);
    return appendToNonEmpty(tmp, appender);
}
References appendToNonEmpty().
applyIf() [1/2]
std::string TCEString::applyIf (bool expression, stringCRef ifTrue) static
Returns string if "expression" is true. Otherwise return empty string.
Definition at line 241 of file TCEString.cc.
{
   return applyIf(expression, ifTrue, "");
}
References applyIf().
applyIf() [2/2]
std::string TCEString::applyIf (bool expression, stringCRef ifTrue, stringCRef ifFalse) static
Returns first string if "expression" is true. Otherwise return second.
Definition at line 229 of file TCEString.cc.
{
    if (expression) {
        return ifTrue;
    } else {
        return ifFalse;
    }
}
Referenced by applyIf(), and ProGe::NetlistVisualization::printBlockTree().
capitalize()
TCEString TCEString::capitalize () const
Return a copy of the string with its first character in upper case and the rest in lower case.
Definition at line 106 of file TCEString.cc.
{
    if (size() == 0) return "";
    if (size() == 1) return upper();
    return StringTools::stringToUpper(substr(0, 1)) +
        StringTools::stringToLower(substr(1, size() - 1));
}
References StringTools::stringToLower(), StringTools::stringToUpper(), and upper().
ciEqual()
bool TCEString::ciEqual (const TCEString & other) const
Returns true if two strings are equal if the case is not taken into account.
Parameters
a A string.
b Another string.
Returns
True if strings equal case-insensitively.
Definition at line 63 of file TCEString.cc.
{
    unsigned int len = length();
    if (len != other.length()) return false;
    for (unsigned int i = 0; i < len; i++) {
        if (tolower((*this)[i]) != tolower(other[i])) {
            return false;
        }
    }
    return true;
}
Referenced by OperationIndex::effectiveOperation(), ControlFlowGraph::findLLVMTargetInstrDesc(), OperationIndex::moduleOf(), and OperationDAGSelector::CaseInsensitiveCmp::operator()().
endsWith()
bool TCEString::endsWith (const std::string & str) const
Referenced by VectorLSGenerator::createVectorLSU(), ProGe::VerilogNetlistWriter::genericMapStringValue(), ProGe::VHDLNetlistWriter::genericMapStringValue(), ProGe::VerilogNetlistWriter::writeGenericDeclaration(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), and SOPCBuilderFileGenerator::writeGenerics().
filterDigits()
std::string TCEString::filterDigits (const std::string & str) static
Returns string in which all non-digit characters have been removed.
Definition at line 278 of file TCEString.cc.
{
    std::string result;
    result.reserve(str.size());
    for (auto c : str) {
        if (std::isdigit(c)) result += c;
    }
    return result;
}
intToHexString()
std::string TCEString::intToHexString (int num) static
Definition at line 288 of file TCEString.cc.
{
    std::stringstream ss;
    ss << "0x" << std::hex << std::uppercase << num;
    return ss.str();
}
Referenced by RISCVTDGen::decimalsToHex().
lower()
TCEString TCEString::lower () const
Turns the string to lowercase.
Definition at line 78 of file TCEString.cc.
                       {
    return StringTools::stringToLower(*this);
}
References StringTools::stringToLower().
Referenced by ProGe::NetlistGenerator::checkInstanceName(), IPXactModel::extractModelParam(), OTAOperationDialog::onOperationFilterChange(), OperationPoolPimpl::operation(), TCEString::ICLess::operator()(), TCETools::CaseInsensitiveCmp::operator()(), OTAOperationDialog::TransferDataToWindow(), ProGe::VerilogNetlistWriter::writeGenericDeclaration(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), SOPCBuilderFileGenerator::writeGenerics(), ProGe::VerilogNetlistWriter::writePortMappings(), and ProGe::VHDLNetlistWriter::writePortMappings().
makeString()
template<typename IterableContainer > static std::string TCEString::makeString (const IterableContainer & container, const std::string & separator = ", ") static
Referenced by ProGe::ProcessorGenerator::checkIULatencies(), and DefaultDecoderGenerator::verifyCompatibility().
operator+() [1/2]
TCEString TCEString::operator+ (char c) const
Definition at line 151 of file TCEString.cc.
{
    return *this + TCEString(c);
}
References TCEString().
operator+() [2/2]
TCEString TCEString::operator+ (int val) const
Definition at line 146 of file TCEString.cc.
{
    return TCEString(*this) += Conversion::toString(val);
}
References TCEString(), and Conversion::toString().
operator<<() [1/3]
TCEString & TCEString::operator<< (const char * rhs)
Definition at line 133 of file TCEString.cc.
{
    *this += TCEString(rhs);
    return *this;
}
References TCEString().
operator<<() [2/3]
TCEString & TCEString::operator<< (const int rhs)
Definition at line 139 of file TCEString.cc.
{
    *this += Conversion::toString(rhs);
    return *this;
}
References Conversion::toString().
operator<<() [3/3]
TCEString & TCEString::operator<< (const TCEString & rhs)
Definition at line 127 of file TCEString.cc.
{
    *this += rhs;
    return *this;
}
replace()
unsigned TCEString::replace (std::string & str, const std::string & oldPattern, const std::string & newPattern) static
Replaces all occurrences of oldPattern in str with newPattern.
Returns
Number of made replacements.
Definition at line 251 of file TCEString.cc.
{
    unsigned replacementCount = 0;
    std::string::size_type location = str.find(oldPattern);
    while (location != std::string::npos) {
        str.replace(
            str.begin() + location,
            str.begin() + location + oldPattern.length(),
            newPattern.c_str());
        replacementCount++;
        // Avoid infinite recursion if replacing with a string
        // that also contains the searched string. This happens
        // when escaping reserved characters such as '_' -> '\\_'.
        location = str.find(oldPattern, location + newPattern.length());
    }
    return replacementCount;
}
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), replaceString(), and OperationDAGDialog::updateDAG().
replaceString()
TCEString & TCEString::replaceString (const std::string & old, const std::string & newString)
Replaces all occurrences of string 'old' with 'newString'
Definition at line 94 of file TCEString.cc.
{
    TCEString::replace(*this, old, newString);
    return *this;
}
References replace().
Referenced by IDF::MachineImplementation::checkImplFile(), IDF::MachineImplementation::decompressorFile(), DataDependenceGraph::dotString(), HDLTemplateInstantiator::fillPlaceholders(), getPasmPacket(), IDF::UnitImplementationLocation::hdbFile(), IDF::MachineImplementation::icDecoderHDB(), IDF::MachineImplementation::icDecoderPluginFile(), HDLTemplateInstantiator::instantiateTemplateFile(), IDF::MachineImplementation::isLibraryImplFile(), main(), printLatexFunctionUnitDescription(), and RISCVTDGen::transformTCEPattern().
split()
std::vector< TCEString > TCEString::split (const std::string & delim) const
Definition at line 114 of file TCEString.cc.
{
    return StringTools::chopString(*this, delim);
}
References StringTools::chopString().
Referenced by ControlFlowGraph::buildMBBFromBB(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), main(), PRegionMarkerAnalyzer::parsePregionID(), HDLGenerator::Module::set_header(), and TestApplication::TestApplication().
startsWith()
bool TCEString::startsWith (const std::string & str) const
Referenced by ControlFlowGraph::buildMBBFromBB(), VectorLSGenerator::createVectorLSU(), llvm::LLVMTCEBuilder::emitSpecialInlineAsm(), ProGe::VerilogNetlistWriter::genericMapStringValue(), ProGe::VHDLNetlistWriter::genericMapStringValue(), llvm::LLVMTCEIRBuilder::isExplicitReturn(), PRegionMarkerAnalyzer::isPregionEndMarker(), PRegionMarkerAnalyzer::isPregionStartMarker(), Environment::longHDBPath(), MachineInfo::maxMemoryAlignment(), Environment::shortHDBPath(), ProGe::VerilogNetlistWriter::writeGenericDeclaration(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), and SOPCBuilderFileGenerator::writeGenerics().
toLower()
std::string TCEString::toLower (const std::string & str, const std::locale & loc = std::locale()) static
Definition at line 184 of file TCEString.cc.
{
    std::string result(str);
    for (size_t i = 0; i < result.size(); i++) {
        result.at(i) = std::tolower(result.at(i), loc);
    }
    return result;
}
toUpper() [1/4]
std::string TCEString::toUpper (const std::string & str, const std::locale & loc = std::locale()) static
Definition at line 162 of file TCEString.cc.
{
    std::string newStr(str);
    return toUpper(newStr, loc);
}
References toUpper().
toUpper() [2/4]
TCEString TCEString::toUpper (const TCEString & str, const std::locale & loc = std::locale()) static
Definition at line 156 of file TCEString.cc.
{
    TCEString newStr(str);
    return toUpper(newStr, loc);
}
References toUpper().
Referenced by ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), toUpper(), and toUpper().
toUpper() [3/4]
std::string & TCEString::toUpper (std::string & str, const std::locale & loc = std::locale()) static
Definition at line 176 of file TCEString.cc.
{
    for (size_t i = 0; i < str.size(); i++) {
        str.at(i) = std::toupper(str.at(i), loc);
    }
    return str;
}
toUpper() [4/4]
TCEString & TCEString::toUpper (TCEString & str, const std::locale & loc = std::locale()) static
Definition at line 168 of file TCEString.cc.
{
    for (size_t i = 0; i < str.size(); i++) {
        str.at(i) = std::toupper(str.at(i), loc);
    }
    return str;
}
unsignedToHexString()
std::string TCEString::unsignedToHexString (unsigned num) static
Definition at line 295 of file TCEString.cc.
{
    std::stringstream ss;
    ss << "0x" << std::hex << std::uppercase << num;
    return ss.str();
}
Referenced by RISCVTDGen::decimalsToHex().
upper()
TCEString TCEString::upper () const
Turns the string to uppercase.
Definition at line 86 of file TCEString.cc.
                       {
    return StringTools::stringToUpper(*this);
}
References StringTools::stringToUpper().
Referenced by IPXactModel::addModelParamsObject(), capitalize(), Operation::isBaseOffsetMemOperation(), ImmInfo::key(), ImmInfo::key(), MIDDGNode::osalOperationName(), MachineInfo::supportsOperation(), RISCVTDGen::writeInstructionDeclaration(), TDGen::writeOperationDefs(), RISCVTDGen::writePatternDefinition(), and TDGen::writePortGuardedJumpDefPair().
The documentation for this class was generated from the following files:
TCEString.hh
TCEString.cc