OpenASIP: FUValidator Class Reference
FUValidator Class Reference
#include <FUValidator.hh>
Static Public Member Functions
static void checkOperandBindings (const TTAMachine::FunctionUnit &fu, MachineValidatorResults &results)
static void checkOperations (const TTAMachine::FunctionUnit &fu, MachineValidatorResults &results)
Private Member Functions
FUValidator ()
Detailed Description
Validator for function units.
Definition at line 45 of file FUValidator.hh.
Constructor & Destructor Documentation
FUValidator()
FUValidator::FUValidator () private
Member Function Documentation
checkOperandBindings()
void FUValidator::checkOperandBindings (const TTAMachine::FunctionUnit & fu, MachineValidatorResults & results) static
Checks that the operands used in the operations of the given FU are bound to some port.
Parameters
fu The function unit.
results Results of the validation are added to the given instance.
Definition at line 54 of file FUValidator.cc.
{
    for (int i = 0; i < fu.operationCount(); i++) {
        HWOperation* operation = fu.operation(i);
        ExecutionPipeline* pLine = operation->pipeline();
        ExecutionPipeline::OperandSet usedOperands;
        for (int i = 0; i < pLine->latency(); i++) {
            ExecutionPipeline::OperandSet readOperands =
                pLine->readOperands(i);
            ExecutionPipeline::OperandSet writtenOperands =
                pLine->writtenOperands(i);
            usedOperands.insert(
                readOperands.begin(), readOperands.end());
            usedOperands.insert(
                writtenOperands.begin(), writtenOperands.end());
        }
        for (ExecutionPipeline::OperandSet::const_iterator iter =
                 usedOperands.begin();
             iter != usedOperands.end(); iter++) {
            int io = *iter;
            FUPort* port = operation->port(io);
            if (port == NULL) {
                boost::format errorMsg(
                    "IO number %1% is not bound to any port in "
                    "operation %2% in FU %3%.");
                errorMsg % io % operation->name() % fu.name();
                results.addError(
                    MachineValidator::USED_IO_NOT_BOUND, errorMsg.str());
            }
        }
    }
}
References MachineValidatorResults::addError(), TTAMachine::ExecutionPipeline::latency(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::HWOperation::pipeline(), TTAMachine::HWOperation::port(), TTAMachine::ExecutionPipeline::readOperands(), MachineValidator::USED_IO_NOT_BOUND, and TTAMachine::ExecutionPipeline::writtenOperands().
Referenced by HDB::HDBManager::addFUArchitecture(), and MachineValidator::checkOperandBindings().
checkOperations()
void FUValidator::checkOperations (const TTAMachine::FunctionUnit & fu, MachineValidatorResults & results) static
Checks that the FU has at least one operation which is valid, i.e. has at least one triggering input port
Parameters
fu The function unit.
results Results of the validation are added to the given instance.
Definition at line 100 of file FUValidator.cc.
{
    for (int i = 0; i < fu.operationCount(); i++) {
        HWOperation* operation = fu.operation(i);
        ExecutionPipeline* pLine = operation->pipeline();
        ExecutionPipeline::OperandSet usedOperands;
        for (int i = 0; i < pLine->latency(); i++) {
            ExecutionPipeline::OperandSet readOperands =
                pLine->readOperands(i);
            for (ExecutionPipeline::OperandSet::const_iterator iter =
                    readOperands.begin(); iter != readOperands.end(); iter++) {
                FUPort* port = operation->port(*iter);
                if (port != NULL && port->isTriggering()) {
                    return;
                }
            }
        }
    }
    boost::format errorMsg("FU %1% has no valid operations.");
    errorMsg % fu.name();
    results.addError(MachineValidator::FU_NO_VALID_OPERATIONS, errorMsg.str());
}
References MachineValidatorResults::addError(), MachineValidator::FU_NO_VALID_OPERATIONS, TTAMachine::FUPort::isTriggering(), TTAMachine::ExecutionPipeline::latency(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::HWOperation::pipeline(), TTAMachine::HWOperation::port(), and TTAMachine::ExecutionPipeline::readOperands().
Referenced by HDB::HDBManager::addFUArchitecture().
The documentation for this class was generated from the following files:
FUValidator.hh
FUValidator.cc