OpenASIP: LowerIntrinsics Class Reference
LowerIntrinsics Class Reference
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runOnBasicBlock (BasicBlock &BB)
Private Member Functions
bool doInitialization (Module &M)
bool doFinalization (Module &M)
Private Attributes
std::set< unsigned > replace_
List of intrinsics to replace.
IntrinsicLowering * iLowering_
TargetData * td_
Detailed Description
Definition at line 68 of file LowerIntrinsics.cc.
Member Function Documentation
doFinalization()
bool LowerIntrinsics::doFinalization (Module & M) private
Definition at line 120 of file LowerIntrinsics.cc.
{
    if (iLowering_ != NULL) {
        delete iLowering_;
        iLowering_ = NULL;
    }
    if (td_ != NULL) {
        delete td_;
        td_ = NULL;
    }
    return true;
}
References iLowering_, and td_.
Referenced by run().
doInitialization()
bool LowerIntrinsics::doInitialization (Module & M) private
Definition at line 101 of file LowerIntrinsics.cc.
{
    // Initialize list of intrinsics to lower.
    replace_.insert(Intrinsic::get_rounding);
    replace_.insert(Intrinsic::ceil);
    replace_.insert(Intrinsic::floor);
    replace_.insert(Intrinsic::round);
    replace_.insert(Intrinsic::exp2);
    replace_.insert(Intrinsic::memcpy);
    replace_.insert(Intrinsic::memset);
    replace_.insert(Intrinsic::memmove);
    assert(iLowering_ == NULL && td_ == NULL);
    td_ = new TargetData(&M);
    iLowering_ = new IntrinsicLowering(*td_);
    return true;
}
References assert, iLowering_, replace_, TargetData, and td_.
Referenced by run().
run()
PreservedAnalyses LowerIntrinsics::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 87 of file LowerIntrinsics.cc.
{
    //errs() << F.getName() << "\n";
  Module *parentModule = F.getParent();
  doInitialization(*parentModule);
  for (BasicBlock &BB : F) {
      runOnBasicBlock(BB);
  }
  doFinalization(*parentModule);
  return PreservedAnalyses::all();
}
References doFinalization(), doInitialization(), and runOnBasicBlock().
runOnBasicBlock()
bool LowerIntrinsics::runOnBasicBlock (BasicBlock & BB)
Definition at line 134 of file LowerIntrinsics.cc.
{
    bool changed = true;
    while (changed)  {
        changed = false;
        for (BasicBlock::iterator I = BB.begin(), E = BB.end(); I != E; ++I) {
            CallInst* ci = dyn_cast<CallInst>(&(*I));
            if (ci != NULL && ci->arg_size() != 0) {
                Function* callee = ci->getCalledFunction();
                if (callee != NULL && callee->isIntrinsic() &&
                    replace_.find(callee->getIntrinsicID()) != replace_.end()) {
                    if (callee->getIntrinsicID() == Intrinsic::get_rounding) {
                        // Replace GET_ROUNDING intrinsic with the actual
                        // constant value to avoid stupid  "if (1 == 0)"
                        // code even with full optimizations.
                        I->replaceAllUsesWith(
                            ConstantInt::get(
                                Type::getInt32Ty(BB.getContext()), 0, true));
                        I->eraseFromParent();
                        changed = true;
                        break;
                    } else {
                        iLowering_->LowerIntrinsicCall(ci);
                        changed = true;
                        break;
                    }
                }
            }
        }
    }
    return true;
}
References iLowering_, and replace_.
Referenced by run().
Member Data Documentation
iLowering_
IntrinsicLowering* LowerIntrinsics::iLowering_ private
Definition at line 83 of file LowerIntrinsics.cc.
Referenced by doFinalization(), doInitialization(), and runOnBasicBlock().
replace_
std::set<unsigned> LowerIntrinsics::replace_ private
List of intrinsics to replace.
Definition at line 82 of file LowerIntrinsics.cc.
Referenced by doInitialization(), and runOnBasicBlock().
td_
TargetData* LowerIntrinsics::td_ private
Definition at line 84 of file LowerIntrinsics.cc.
Referenced by doFinalization(), and doInitialization().
The documentation for this class was generated from the following file:
LowerIntrinsics.cc