OpenASIP: BFPostpassBypass Class Reference
BFPostpassBypass Class Reference
#include <BFPostpassBypass.hh>
Public Member Functions
BFPostpassBypass (BF2Scheduler &sched, MoveNode &src, MoveNode &dst, bool loopBypass)
bool operator() () override
void undoOnlyMe () override
bool dred () const
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & src_
MoveNode & dst_
bool dred_
bool loopBypass_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 42 of file BFPostpassBypass.hh.
Constructor & Destructor Documentation
BFPostpassBypass()
BFPostpassBypass::BFPostpassBypass (BF2Scheduler & sched, MoveNode & src, MoveNode & dst, bool loopBypass) inline
Definition at line 44 of file BFPostpassBypass.hh.
                                      :
        BFOptimization(sched), src_(src), dst_(dst), dred_(false),
        loopBypass_(loopBypass) {}
Member Function Documentation
dred()
bool BFPostpassBypass::dred () const inline
Definition at line 52 of file BFPostpassBypass.hh.
{ return dred_; }
References dred_.
operator()()
bool BFPostpassBypass::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 51 of file BFPostpassBypass.cc.
{
    assert(dst_.isScheduled());
    assert(src_.isScheduled());
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    static int counter = 0;
    static int counter2 = 0;
#endif
    int originalCycle = dst_.cycle();
    int srcCycle = src_.cycle();
    if (loopBypass_ && originalCycle >= (int)ii()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "too late cycle for loop bypass" << std::endl;
#endif
        return false;
    }
    const TTAMachine::FunctionUnit* ssfu = src_.isSourceOperation() ?
        &src_.move().source().functionUnit() : nullptr;
    const TTAMachine::FunctionUnit* ddfu = dst_.isDestinationOperation() ?
        &dst_.move().destination().functionUnit() : nullptr;
    if (!loopBypass_) {
        runPreChild(new BFUnscheduleMove(sched_, dst_));
    } else {
        runPreChild(new BFUnscheduleFromBody(sched_, dst_));
    }
    runPreChild(new BFUnscheduleMove(sched_, src_));
    if (!runPreChild(
            new BFMergeAndKeepUser(sched_, src_, dst_, loopBypass_))) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "merge and keep fail." << src_.toString()
                  << " and " << dst_.toString() << std::endl;
#endif
        undoAndRemovePreChildren();
        return false;
    }
    dred_ = runPostChild(new BFPostpassDRE(sched_, src_));
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tTried ordinary dre: " << dred_ << std::endl;
#endif
    if (loopBypass_ && !dred_) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tsrccycle: " << srcCycle << std::endl;
#endif
        if (srcCycle >= (int)ii()) {
            dred_ = runPostChild(
                new BFPostpassLoopDRE(sched_, src_, srcCycle));
        } else {
            if (ddg().latestCycle(src_) >= (signed)ii()) {
                dred_ = runPostChild(
                    new BFPostpassLoopDRE(sched_, src_, ii()));
            }
        }
    }
    // TODO: try to DRE here
    if (!dred_) {
        // if returning the old fails, abort everything
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tundoing unscheduling of src" << std::endl;
#endif
        // if not dre, return the result
        if (!runPostChild(
                new BFScheduleExact(sched_, src_, srcCycle, false, ssfu))) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "Scheduling back src:" << src_.toString()
                      << " to cycle: " << srcCycle
                      << " after post-pass bypass move failed" << std::endl;
            ddg().writeToDotFile("postpass_fail1.dot");
#endif
            undo();
            return false;
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tundid unscheduling of src" << std::endl;
#endif
    }
    BFOptimization* schedDst = NULL;
    if (dst_.move().isControlFlowMove() ||
        (ii() != 0 &&
         static_cast<DataDependenceGraph*>(ddg().rootGraph())->
         writesJumpGuard(dst_))) {
        if (!loopBypass_) {
            schedDst = new BFScheduleExact(
                sched_, dst_, originalCycle, false);
        } else {
            schedDst = new BFAssignToBody(
                sched_, dst_, originalCycle, ssfu, ddfu);
        }
    } else {
        if (!loopBypass_) {
            schedDst = new BFScheduleExact(
                sched_, dst_, originalCycle, false);
        } else {
            schedDst = new BFAssignToBody(
                sched_, dst_, originalCycle, ssfu, ddfu);
        }
    }
    if (!runPostChild(schedDst)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\tScheduling post-pass bypassed move failed:"
                  <<  dst_.toString() << "cycle: " << originalCycle
                  << std::endl;
        ddg().writeToDotFile("postpass_fail2.dot");
#endif
        undo();
        return false;
    }
    return true;
}
References assert, MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), dred_, dst_, TTAProgram::Terminal::functionUnit(), BFOptimization::ii(), TTAProgram::Move::isControlFlowMove(), MoveNode::isDestinationOperation(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), loopBypass_, MoveNode::move(), Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, TTAProgram::Move::source(), src_, MoveNode::toString(), Reversible::undo(), Reversible::undoAndRemovePreChildren(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
undoOnlyMe()
void BFPostpassBypass::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 174 of file BFPostpassBypass.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "isloopbypass?" << loopBypass_ << std::endl;
    std::cerr << "\t\t\tPerforming unmerge user of: "
              << src_.toString() << " and: " << dst_.toString()
              << std::endl;
#endif
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tPerformed unmerge user of: "
              << src_.toString() << " and: " << dst_.toString()
              << std::endl;
#endif
}
References dst_, loopBypass_, src_, and MoveNode::toString().
Member Data Documentation
dred_
bool BFPostpassBypass::dred_ private
Definition at line 56 of file BFPostpassBypass.hh.
Referenced by dred(), and operator()().
dst_
MoveNode& BFPostpassBypass::dst_ private
Definition at line 55 of file BFPostpassBypass.hh.
Referenced by operator()(), and undoOnlyMe().
loopBypass_
bool BFPostpassBypass::loopBypass_ private
Definition at line 57 of file BFPostpassBypass.hh.
Referenced by operator()(), and undoOnlyMe().
src_
MoveNode& BFPostpassBypass::src_ private
Definition at line 54 of file BFPostpassBypass.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFPostpassBypass.hh
BFPostpassBypass.cc