OpenASIP: OutputOperandDialog Class Reference
OutputOperandDialog Class Reference
#include <OutputOperandDialog.hh>
Public Member Functions
OutputOperandDialog (wxWindow *window, Operand *operand, int index)
virtual ~OutputOperandDialog ()
Private Types
enum {
ID_MEM_DATA , ID_OPERATION_OUTPUT_TYPES , ID_ELEMENT_WIDTH , ID_ELEMENT_COUNT ,
ID_TEXT_WIDTH , ID_TEXT_COUNT
}
Private Member Functions
OutputOperandDialog (const OutputOperandDialog &)
Copying not allowed.
OutputOperandDialog & operator= (const OutputOperandDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *window, bool call_fit, bool set_sizer)
void onOk (wxCommandEvent &event)
void onType (wxCommandEvent &event)
void onElementWidth (wxSpinEvent &event)
void onElementCount (wxCommandEvent &event)
void updateTypes ()
void updateElementWidths ()
void updateElementCounts ()
void setTexts ()
Private Attributes
Operand * operand_
Operand to be modified.
bool memData_
Flag indicating whether operand is memory data or not.
int index_
Index of the operand.
wxChoice * outputTypesComboBox_
Choice box for operation input types.
wxSpinCtrl * elementWidthSpinCtrl_
Spin ctrl for operand element width.
wxChoice * elementCountChoice_
Choice box for operand element count.
int type_
Current operand type in choice box.
int elemWidth_
Current element width in choice box.
int elemCount_
Current element count in choice box.
std::vector< std::string > outputTypes_
Output types.
operandList operandTypes_
Detailed Description
Class for adding or modifying output operands.
Definition at line 49 of file OutputOperandDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Component ids.
Enumerator
ID_MEM_DATA
Memory data choice.
ID_OPERATION_OUTPUT_TYPES
Output Type ComboBox.
ID_ELEMENT_WIDTH
ID_ELEMENT_COUNT
ID_TEXT_WIDTH
ID_TEXT_COUNT
Definition at line 74 of file OutputOperandDialog.hh.
         {
        ID_MEM_DATA,           ///< Memory data choice.
        ID_OPERATION_OUTPUT_TYPES, ///< Output Type ComboBox
        ID_ELEMENT_WIDTH,
        ID_ELEMENT_COUNT,
        ID_TEXT_WIDTH,
        ID_TEXT_COUNT
    };
Constructor & Destructor Documentation
OutputOperandDialog() [1/2]
OutputOperandDialog::OutputOperandDialog (wxWindow * parent, Operand * operand, int index)
Constructor.
Parameters
parent Parent window.
operand Operand to be added or modified.
index Index of the operand.
Definition at line 66 of file OutputOperandDialog.cc.
               :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_OUTPUT_OPERAND)),
    operand_(operand), memData_(false), index_(index) {
    memData_ = operand_->isMemoryData();
    createContents(this, true, true);
    outputTypesComboBox_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_OPERATION_OUTPUT_TYPES));
    elementWidthSpinCtrl_ =
        dynamic_cast<wxSpinCtrl*>(FindWindow(ID_ELEMENT_WIDTH));
    elementCountChoice_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_ELEMENT_COUNT));
    FindWindow(ID_MEM_DATA)->SetValidator(wxGenericValidator(&memData_));
    outputTypes_.push_back(Operand::SINT_WORD_STRING);
    outputTypes_.push_back(Operand::UINT_WORD_STRING);
    outputTypes_.push_back(Operand::FLOAT_WORD_STRING);
    outputTypes_.push_back(Operand::DOUBLE_WORD_STRING);
    outputTypes_.push_back(Operand::HALF_FLOAT_WORD_STRING);
    outputTypes_.push_back(Operand::BOOL_STRING);
    outputTypes_.push_back(Operand::RAW_DATA_STRING);
    outputTypes_.push_back(Operand::SLONG_WORD_STRING);
    outputTypes_.push_back(Operand::ULONG_WORD_STRING);
    operandTypes_.insert(operandPair(0, Operand::SINT_WORD));
    operandTypes_.insert(operandPair(1, Operand::UINT_WORD));
    operandTypes_.insert(operandPair(2, Operand::FLOAT_WORD));
    operandTypes_.insert(operandPair(3, Operand::DOUBLE_WORD));
    operandTypes_.insert(operandPair(4, Operand::HALF_FLOAT_WORD));
    operandTypes_.insert(operandPair(5, Operand::BOOL));
    operandTypes_.insert(operandPair(6, Operand::RAW_DATA));
    operandTypes_.insert(operandPair(7, Operand::SLONG_WORD));
    operandTypes_.insert(operandPair(8, Operand::ULONG_WORD));
    FindWindow(wxID_OK)->SetFocus();
    type_ = operand_->type();
    elemWidth_ = operand_->elementWidth();
    elemCount_ = operand_->elementCount();
    updateTypes();
    updateElementWidths();
    updateElementCounts();
    setTexts();
}
References Operand::BOOL, Operand::BOOL_STRING, Operand::DOUBLE_WORD, Operand::DOUBLE_WORD_STRING, Operand::FLOAT_WORD, Operand::FLOAT_WORD_STRING, Operand::HALF_FLOAT_WORD, Operand::HALF_FLOAT_WORD_STRING, Operand::RAW_DATA, Operand::RAW_DATA_STRING, Operand::SINT_WORD, Operand::SINT_WORD_STRING, Operand::SLONG_WORD, Operand::SLONG_WORD_STRING, Operand::UINT_WORD, Operand::UINT_WORD_STRING, Operand::ULONG_WORD, and Operand::ULONG_WORD_STRING.
~OutputOperandDialog()
OutputOperandDialog::~OutputOperandDialog () virtual
Destructor.
Definition at line 123 of file OutputOperandDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_OUTPUT_OPERAND, point);
}
References DialogPosition::DIALOG_OUTPUT_OPERAND, and DialogPosition::setPosition().
OutputOperandDialog() [2/2]
OutputOperandDialog::OutputOperandDialog (const OutputOperandDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * OutputOperandDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
NOTE! This function was generated by wxDesigner. This is why it may be ugly.
Parameters
parent Parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Returns
The created sizer.
Definition at line 347 of file OutputOperandDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *item1 = new wxBoxSizer(wxHORIZONTAL);
    wxString strs9[] =
        {
            wxT("id: 1")
        };
    // Choice for input operand types
    wxChoice *itemOutputTypes = new wxChoice(parent, ID_OPERATION_OUTPUT_TYPES, wxDefaultPosition, wxSize(100,-1), 1, strs9);
    item1->Add(itemOutputTypes, 0, wxALIGN_CENTER|wxALL, 5);
    wxStaticText *itemTextWidth = new wxStaticText(parent, ID_TEXT_WIDTH, wxT("Element width:"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(itemTextWidth, 0, wxALIGN_CENTER|wxALL, 5);
    wxSpinCtrl *itemElemWidth = new wxSpinCtrl(parent, ID_ELEMENT_WIDTH, wxT(""), wxDefaultPosition, wxSize(-1,-1), 1);
    item1->Add(itemElemWidth, 0, wxALIGN_CENTER|wxALL, 5);
    wxStaticText *itemTextCount = new wxStaticText(parent, ID_TEXT_COUNT, wxT("Element count:"), wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(itemTextCount, 0, wxALIGN_CENTER|wxALL, 5);
    wxChoice *itemElemCount = new wxChoice(parent, ID_ELEMENT_COUNT, wxDefaultPosition, wxSize(70,-1), 1, strs9);
    item1->Add(itemElemCount, 0, wxALIGN_CENTER|wxALL, 5);
    wxBoxSizer *item1b = new wxBoxSizer(wxHORIZONTAL);
    wxCheckBox *item3 = new wxCheckBox(parent, ID_MEM_DATA, wxT("Memory data"), wxDefaultPosition, wxDefaultSize, 0);
    item1b->Add(item3, 0, wxALIGN_CENTER|wxALL, 5);
    item0->Add(item1, 0, wxALIGN_CENTER|wxALL, 5);
    item0->Add(item1b, 0, wxALIGN_CENTER|wxALL, 5);
    wxBoxSizer *item4 = new wxBoxSizer(wxHORIZONTAL);
    wxButton *item5 = new wxButton(parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0);
    item4->Add(item5, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *item6 = new wxButton(parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
    item4->Add(item6, 0, wxALIGN_CENTER|wxALL, 5);
    item0->Add(item4, 0, wxALIGN_CENTER|wxALL, 5);
    if (set_sizer)
    {
        parent->SetSizer(item0);
        if (call_fit)
            item0->SetSizeHints(parent);
    }
    return item0;
}
References ID_ELEMENT_COUNT, ID_ELEMENT_WIDTH, ID_MEM_DATA, ID_OPERATION_OUTPUT_TYPES, ID_TEXT_COUNT, and ID_TEXT_WIDTH.
onElementCount()
void OutputOperandDialog::onElementCount (wxCommandEvent & event) private
Event handler for element count choice box.
Definition at line 159 of file OutputOperandDialog.cc.
{
    // get the current choice box value and convert it to integer
    int index = elementCountChoice_->GetSelection();
    wxString number = elementCountChoice_->GetString(index);
    long value;
    if(!number.ToLong(&value)) {
        elemCount_ = 1;
        return;
    }
    // save current choice
    elemCount_ = static_cast<int>(value);
    // update spin ctrl range
    updateElementWidths();
}
References elemCount_, elementCountChoice_, and updateElementWidths().
onElementWidth()
void OutputOperandDialog::onElementWidth (wxSpinEvent & event) private
Event handler for element width spin ctrl.
Definition at line 149 of file OutputOperandDialog.cc.
{
    elemWidth_ = elementWidthSpinCtrl_->GetValue();
    // update choice box list cells
    updateElementCounts();
}
References elementWidthSpinCtrl_, elemWidth_, and updateElementCounts().
onOk()
void OutputOperandDialog::onOk (wxCommandEvent & event) private
Handles the event when OK button is pushed.
Definition at line 279 of file OutputOperandDialog.cc.
{
    TransferDataFromWindow();
    ObjectState* root = new ObjectState("");
    root->setAttribute(Operand::OPRND_ID, operand_->index());
    int selected = outputTypesComboBox_->GetSelection();
    Operand::OperandType type = operandTypes_[selected];
    switch(type)
    {
        case Operand::SINT_WORD:
            root->setAttribute(Operand::OPRND_TYPE, Operand::SINT_WORD_STRING);
            break;
        case Operand::UINT_WORD:
            root->setAttribute(Operand::OPRND_TYPE, Operand::UINT_WORD_STRING);
            break;
        case Operand::FLOAT_WORD:
            root->setAttribute(Operand::OPRND_TYPE, Operand::FLOAT_WORD_STRING);
            break;
        case Operand::DOUBLE_WORD:
            root->setAttribute(Operand::OPRND_TYPE, Operand::DOUBLE_WORD_STRING);
            break;
        case Operand::HALF_FLOAT_WORD:
            root->setAttribute(
                Operand::OPRND_TYPE, Operand::HALF_FLOAT_WORD_STRING);
            break;
        case Operand::BOOL:
            root->setAttribute(Operand::OPRND_TYPE, Operand::BOOL_STRING);
            break;
        case Operand::RAW_DATA:
            root->setAttribute(Operand::OPRND_TYPE, Operand::RAW_DATA_STRING);
            break;
        case Operand::SLONG_WORD:
            root->setAttribute(
                Operand::OPRND_TYPE, Operand::SLONG_WORD_STRING);
            break;
        case Operand::ULONG_WORD:
            root->setAttribute(
                Operand::OPRND_TYPE, Operand::ULONG_WORD_STRING);
            break;
        default:
            root->setAttribute(Operand::OPRND_TYPE, Operand::SINT_WORD_STRING);
            break;
    }
    root->setAttribute(Operand::OPRND_ELEM_WIDTH, elemWidth_);
    root->setAttribute(Operand::OPRND_ELEM_COUNT, elemCount_);
    root->setAttribute(Operand::OPRND_MEM_ADDRESS, false);
    root->setAttribute(Operand::OPRND_MEM_DATA, memData_);
    operand_->loadState(root);
    delete root;
    EndModal(wxID_OK);
}
References Operand::BOOL, Operand::BOOL_STRING, Operand::DOUBLE_WORD, Operand::DOUBLE_WORD_STRING, elemCount_, elemWidth_, Operand::FLOAT_WORD, Operand::FLOAT_WORD_STRING, Operand::HALF_FLOAT_WORD, Operand::HALF_FLOAT_WORD_STRING, Operand::index(), Operand::loadState(), memData_, operand_, operandTypes_, Operand::OPRND_ELEM_COUNT, Operand::OPRND_ELEM_WIDTH, Operand::OPRND_ID, Operand::OPRND_MEM_ADDRESS, Operand::OPRND_MEM_DATA, Operand::OPRND_TYPE, outputTypesComboBox_, Operand::RAW_DATA, Operand::RAW_DATA_STRING, ObjectState::setAttribute(), Operand::SINT_WORD, Operand::SINT_WORD_STRING, Operand::SLONG_WORD, Operand::SLONG_WORD_STRING, Operand::UINT_WORD, Operand::UINT_WORD_STRING, Operand::ULONG_WORD, and Operand::ULONG_WORD_STRING.
onType()
void OutputOperandDialog::onType (wxCommandEvent & event) private
Event handler for operand type choice box.
Definition at line 134 of file OutputOperandDialog.cc.
{
    type_ = outputTypesComboBox_->GetSelection();
    Operand::OperandType operType = static_cast<Operand::OperandType>(type_);
    elemWidth_ = Operand::defaultElementWidth(operType);
    elemCount_ = 1;
    updateElementWidths();
    updateElementCounts();
}
References Operand::defaultElementWidth(), elemCount_, elemWidth_, outputTypesComboBox_, type_, updateElementCounts(), and updateElementWidths().
operator=()
OutputOperandDialog & OutputOperandDialog::operator= (const OutputOperandDialog &) private
Assignment not allowed.
setTexts()
void OutputOperandDialog::setTexts () private
Set texts to widgets.
Definition at line 252 of file OutputOperandDialog.cc.
{
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // title
    format fmt =
        osedText.text(OSEdTextGenerator::TXT_OUTPUT_OPERAND_DIALOG_TITLE);
    fmt % index_;
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(&guiText, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    // check boxes
    WidgetTools::setLabel(&osedText, FindWindow(ID_MEM_DATA),
                          OSEdTextGenerator::TXT_CHECKBOX_MEM_DATA);
}
References ID_MEM_DATA, index_, GUITextGenerator::instance(), OSEdTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_OK, OSEdTextGenerator::TXT_CHECKBOX_MEM_DATA, and OSEdTextGenerator::TXT_OUTPUT_OPERAND_DIALOG_TITLE.
updateElementCounts()
void OutputOperandDialog::updateElementCounts () private
Updates the element count choice box list.
Definition at line 230 of file OutputOperandDialog.cc.
{
    elementCountChoice_->Clear();
    // update the list so that only shorter or equal than SIMD_WORD_WIDTH
    // width*count combinations are listed
    int elemCount = 1;
    int elemCountIndex = 0;
    while (elemCount*elemWidth_ <= SIMD_WORD_WIDTH) {
        if (elemCount < elemCount_) {
            ++elemCountIndex;
        }
        elementCountChoice_->Append(WxConversion::toWxString(elemCount));
        elemCount *= 2;
    }
    elementCountChoice_->SetSelection(elemCountIndex);
}
References elemCount_, elementCountChoice_, elemWidth_, SIMD_WORD_WIDTH, and WxConversion::toWxString().
Referenced by onElementWidth(), and onType().
updateElementWidths()
void OutputOperandDialog::updateElementWidths () private
Updates the element width choice box list.
Definition at line 196 of file OutputOperandDialog.cc.
{
    Operand::OperandType operType = static_cast<Operand::OperandType>(type_);
    if (operType == Operand::RAW_DATA) {
        // element width for raw data can be arbitrary up to the max width
        int elemWidth = 1;
        int lastValidWidth = 1;
        while (elemCount_*elemWidth <= SIMD_WORD_WIDTH) {
            lastValidWidth = elemWidth;
            elemWidth *= 2;
        }
        // degrade current element width if it is too big
        if (elemWidth_ > lastValidWidth) {
            elemWidth_ = lastValidWidth;
        }
        elementWidthSpinCtrl_->SetRange(1, lastValidWidth);
        elementWidthSpinCtrl_->SetValue(elemWidth_);
    } else if (operType == Operand::SINT_WORD || operType == Operand::UINT_WORD) {
        // element width for integers is 8 to 32
        elementWidthSpinCtrl_->SetRange(8, 32);
        elementWidthSpinCtrl_->SetValue(elemWidth_);
    } else {
        // element width for other types is their default type width
        elementWidthSpinCtrl_->SetRange(elemWidth_, elemWidth_);
        elementWidthSpinCtrl_->SetValue(elemWidth_);
    }
}
References elemCount_, elementWidthSpinCtrl_, elemWidth_, Operand::RAW_DATA, SIMD_WORD_WIDTH, Operand::SINT_WORD, type_, and Operand::UINT_WORD.
Referenced by onElementCount(), and onType().
updateTypes()
void OutputOperandDialog::updateTypes () private
Updates the type lists.
Definition at line 179 of file OutputOperandDialog.cc.
{
    outputTypesComboBox_->Clear();
    for (unsigned int i = 0; i < outputTypes_.size(); i++) {
        wxString oper = WxConversion::toWxString(outputTypes_.at(i));
        outputTypesComboBox_->Append(oper);
    }
    outputTypesComboBox_->SetSelection(type_);
}
References outputTypes_, outputTypesComboBox_, WxConversion::toWxString(), and type_.
Member Data Documentation
elemCount_
int OutputOperandDialog::elemCount_ private
Current element count in choice box.
Definition at line 100 of file OutputOperandDialog.hh.
Referenced by onElementCount(), onOk(), onType(), updateElementCounts(), and updateElementWidths().
elementCountChoice_
wxChoice* OutputOperandDialog::elementCountChoice_ private
Choice box for operand element count.
Definition at line 94 of file OutputOperandDialog.hh.
Referenced by onElementCount(), and updateElementCounts().
elementWidthSpinCtrl_
wxSpinCtrl* OutputOperandDialog::elementWidthSpinCtrl_ private
Spin ctrl for operand element width.
Definition at line 92 of file OutputOperandDialog.hh.
Referenced by onElementWidth(), and updateElementWidths().
elemWidth_
int OutputOperandDialog::elemWidth_ private
Current element width in choice box.
Definition at line 98 of file OutputOperandDialog.hh.
Referenced by onElementWidth(), onOk(), onType(), updateElementCounts(), and updateElementWidths().
index_
int OutputOperandDialog::index_ private
Index of the operand.
Definition at line 88 of file OutputOperandDialog.hh.
Referenced by setTexts().
memData_
bool OutputOperandDialog::memData_ private
Flag indicating whether operand is memory data or not.
Definition at line 86 of file OutputOperandDialog.hh.
Referenced by onOk().
operand_
Operand* OutputOperandDialog::operand_ private
Operand to be modified.
Definition at line 84 of file OutputOperandDialog.hh.
Referenced by onOk().
operandTypes_
operandList OutputOperandDialog::operandTypes_ private
Definition at line 104 of file OutputOperandDialog.hh.
Referenced by onOk().
outputTypes_
std::vector<std::string> OutputOperandDialog::outputTypes_ private
Output types.
Definition at line 103 of file OutputOperandDialog.hh.
Referenced by updateTypes().
outputTypesComboBox_
wxChoice* OutputOperandDialog::outputTypesComboBox_ private
Choice box for operation input types.
Definition at line 90 of file OutputOperandDialog.hh.
Referenced by onOk(), onType(), and updateTypes().
type_
int OutputOperandDialog::type_ private
Current operand type in choice box.
Definition at line 96 of file OutputOperandDialog.hh.
Referenced by onType(), updateElementWidths(), and updateTypes().
The documentation for this class was generated from the following files:
OutputOperandDialog.hh
OutputOperandDialog.cc