OpenASIP: InfoFunitsCommand Class Reference
InfoFunitsCommand Class Reference
Public Member Functions
InfoFunitsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoFunitsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info funits".
Definition at line 665 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoFunitsCommand()
InfoFunitsCommand::InfoFunitsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 670 of file InfoCommand.cc.
                                                                :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoFunitsCommand()
virtual InfoFunitsCommand::~InfoFunitsCommand () inline virtual
Destructor.
Definition at line 677 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoFunitsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info funits" command.
"info funits" prints the names of all the function units in the machine.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 689 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 0, 0)) {
            return false;
        }
        if (!parent().checkMachineLoaded()) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        const TTAMachine::Machine::FunctionUnitNavigator& nav =
            mach.functionUnitNavigator();
        std::string result = "";
        bool isFirst = true;
        for (int i = 0; i < nav.count(); ++i) {
            if (!isFirst)
                result += "\n";
            result += nav.item(i)->name();
            isFirst = false;
        }
        result += "\n" + mach.controlUnit()->name();
        parent().interpreter()->setResult(result);
        return true;
    }
References TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), CustomCommand::interpreter(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::Component::name(), SimControlLanguageSubCommand::parent(), ScriptInterpreter::setResult(), and SimControlLanguageCommand::simulatorFrontend().
The documentation for this class was generated from the following file:
InfoCommand.cc