OpenASIP: ValidateMachineDialog Class Reference
ValidateMachineDialog Class Reference
#include <ValidateMachineDialog.hh>
Public Member Functions
ValidateMachineDialog (wxWindow *parent, const TTAMachine::Machine &machine)
~ValidateMachineDialog ()
Private Types
enum {
ID_VALIDATE = 10000 , ID_CLOSE , ID_RESULTS , ID_LINE ,
ID_CHECK_ANSI_C , ID_CHECK_GLOBAL_CONN_REGISTER
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onValidate (wxCommandEvent &event)
void onClose (wxCommandEvent &event)
void onCheck (wxCommandEvent &event)
Private Attributes
const TTAMachine::Machine & machine_
Machine to be validated.
wxHtmlWindow * resultsWindow_
HTML-widget for validation result texts.
wxCheckBox * checkAnsiC_
wxCheckBox * checkGlobalConnReg_
Detailed Description
Dialog for listing and editing address spaces of the machine.
Definition at line 47 of file ValidateMachineDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_VALIDATE
ID_CLOSE
ID_RESULTS
ID_LINE
ID_CHECK_ANSI_C
ID_CHECK_GLOBAL_CONN_REGISTER
Definition at line 68 of file ValidateMachineDialog.hh.
         {
        ID_VALIDATE = 10000,
        ID_CLOSE,
        ID_RESULTS,
        ID_LINE,
        ID_CHECK_ANSI_C,
        ID_CHECK_GLOBAL_CONN_REGISTER
    };
Constructor & Destructor Documentation
ValidateMachineDialog()
ValidateMachineDialog::ValidateMachineDialog (wxWindow * parent, const TTAMachine::Machine & machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Machine containing the address spaces.
Definition at line 59 of file ValidateMachineDialog.cc.
                                     :
    wxDialog(parent, -1, _T("Validate Machine"), wxDefaultPosition),
    machine_(machine) {
    createContents(this, true, true);
    checkAnsiC_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_CHECK_ANSI_C));
    checkGlobalConnReg_ = dynamic_cast<wxCheckBox*>(
        FindWindow(ID_CHECK_GLOBAL_CONN_REGISTER));
    FindWindow(ID_VALIDATE)->Disable();
    // Global connection register check in ProgrammabilityValidator
    // doesn't work for arbitrary machines yet. The global
    // connection register checkbox is therefore disabled.
    // Following disable-call can be removed when the
    // ProgrammabilityValiadtor works for all machines.
    //FindWindow(ID_CHECK_GLOBAL_CONN_REGISTER)->Disable();
}
~ValidateMachineDialog()
ValidateMachineDialog::~ValidateMachineDialog ()
The Destructor.
Definition at line 85 of file ValidateMachineDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ValidateMachineDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 181 of file ValidateMachineDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Validate:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    wxCheckBox *item4 = new wxCheckBox( parent, ID_CHECK_ANSI_C, wxT("Check for operations needed to support ANSI C."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALL, 5 );
    wxCheckBox *item5 = new wxCheckBox( parent, ID_CHECK_GLOBAL_CONN_REGISTER, wxT("Check for global connection register."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALL, 5 );
    wxButton *item6 = new wxButton( parent, ID_VALIDATE, wxT("Validate"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item8 = new wxStaticBox( parent, -1, wxT("Results:") );
    wxStaticBoxSizer *item7 = new wxStaticBoxSizer( item8, wxVERTICAL );
    resultsWindow_ = new wxHtmlWindow(parent, ID_RESULTS, wxDefaultPosition, wxSize(250, 250));
    wxWindow* item9 = resultsWindow_;
    wxASSERT( item9 );
    item7->Add( item9, 0, wxGROW|wxALL, 5 );
    item1->Add( item7, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item10 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item10, 0, wxGROW|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, ID_CLOSE, wxT("Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item11, 0, wxALIGN_RIGHT|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CHECK_ANSI_C, ID_CHECK_GLOBAL_CONN_REGISTER, ID_CLOSE, ID_LINE, ID_RESULTS, ID_VALIDATE, and resultsWindow_.
onCheck()
void ValidateMachineDialog::onCheck (wxCommandEvent & event) private
Event handler for the checkbox check toggles.
Disables the Validate-button if no checkboxes are checked.
Definition at line 95 of file ValidateMachineDialog.cc.
{
    if (checkAnsiC_->IsChecked() ||
        checkGlobalConnReg_->IsChecked()) {
        FindWindow(ID_VALIDATE)->Enable();
    } else {
        FindWindow(ID_VALIDATE)->Disable();
    }
}
References checkAnsiC_, checkGlobalConnReg_, and ID_VALIDATE.
onClose()
void ValidateMachineDialog::onClose (wxCommandEvent & event) private
Event handler for the Close-button.
Closes the dialog.
Definition at line 164 of file ValidateMachineDialog.cc.
{
    Close();
}
onValidate()
void ValidateMachineDialog::onValidate (wxCommandEvent & event) private
Event handler for the Validate-button.
Validates the machine using a ProgrammabilityValidator. Only checks that are selected with the checkboxes are ran.
Definition at line 113 of file ValidateMachineDialog.cc.
{
    bool valid = true;
    wxString resultPage = _T("<html><body><small>");
    std::set<ProgrammabilityValidator::ErrorCode> checks;
    if (checkGlobalConnReg_->IsChecked()) {
        checks.insert(
            ProgrammabilityValidator::GLOBAL_CONNECTION_REGISTER_NOT_FOUND);
        checks.insert(ProgrammabilityValidator::MISSING_CONNECTION);
    }
    if (checkAnsiC_->IsChecked()) {
        checks.insert(
            ProgrammabilityValidator::
            OPERATION_MISSING_FROM_THE_PRIMITIVE_OPERATION_SET);
    }
    assert(!checks.empty());
    try {
        ProgrammabilityValidator validator(machine_);
        ProgrammabilityValidatorResults* results = validator.validate(checks);
        for (int i = 0; i < results->errorCount(); i++) {
            valid = false;
            resultPage.Append(
                WxConversion::toWxString(results->error(i).second));
            resultPage.Append(_T("<hr>"));
        }
        delete results;
        results = NULL;
    } catch (IllegalMachine& e) {
        valid = false;
        resultPage.Append(WxConversion::toWxString(e.errorMessage()));
    }
    if (valid) {
        resultPage.Append(
            _T("<font color=#00c000>Validity checks passed!</font>"));
    }
    resultPage.Append(_T("</small></body></html>"));
    resultsWindow_->SetPage(resultPage);
}
References assert, checkAnsiC_, checkGlobalConnReg_, ProgrammabilityValidatorResults::error(), ProgrammabilityValidatorResults::errorCount(), Exception::errorMessage(), ProgrammabilityValidator::GLOBAL_CONNECTION_REGISTER_NOT_FOUND, machine_, ProgrammabilityValidator::MISSING_CONNECTION, resultsWindow_, WxConversion::toWxString(), and ProgrammabilityValidator::validate().
Member Data Documentation
checkAnsiC_
wxCheckBox* ValidateMachineDialog::checkAnsiC_ private
Definition at line 64 of file ValidateMachineDialog.hh.
Referenced by onCheck(), and onValidate().
checkGlobalConnReg_
wxCheckBox* ValidateMachineDialog::checkGlobalConnReg_ private
Definition at line 65 of file ValidateMachineDialog.hh.
Referenced by onCheck(), and onValidate().
machine_
const TTAMachine::Machine& ValidateMachineDialog::machine_ private
Machine to be validated.
Definition at line 60 of file ValidateMachineDialog.hh.
Referenced by onValidate().
resultsWindow_
wxHtmlWindow* ValidateMachineDialog::resultsWindow_ private
HTML-widget for validation result texts.
Definition at line 62 of file ValidateMachineDialog.hh.
Referenced by createContents(), and onValidate().
The documentation for this class was generated from the following files:
ValidateMachineDialog.hh
ValidateMachineDialog.cc