OpenASIP: EntryKeyField Class Reference
EntryKeyField Class Reference
#include <EntryKeyField.hh>
Public Member Functions
EntryKeyField (EntryKeyData *fieldData, const EntryKeyFieldProperty *type)
virtual ~EntryKeyField ()
EntryKeyField (const EntryKeyField &old)
EntryKeyField & operator= (const EntryKeyField &old)
bool isEqual (const EntryKeyField &field) const
bool isGreater (const EntryKeyField &field) const
bool isSmaller (const EntryKeyField &field) const
double coefficient (const EntryKeyField &field1, const EntryKeyField &field2) const
std::string toString () const
const EntryKeyFieldProperty * type () const
Private Attributes
EntryKeyData * data_
Value of the field.
const EntryKeyFieldProperty * properties_
Type of the field.
Detailed Description
Represents a field containing a value and a type.
Definition at line 45 of file EntryKeyField.hh.
Constructor & Destructor Documentation
EntryKeyField() [1/2]
EntryKeyField::EntryKeyField (EntryKeyData * fieldData, const EntryKeyFieldProperty * type)
Constructor.
Parameters
fieldData Value of the field.
type Type of the field.
Definition at line 44 of file EntryKeyField.cc.
                                      :
    data_(fieldData), properties_(type) {
}
~EntryKeyField()
EntryKeyField::~EntryKeyField () virtual
Destructor.
Deallocates memory reserved for the value of the field.
Definition at line 64 of file EntryKeyField.cc.
{
    assert(data_ != NULL);
    delete data_;
    data_ = NULL;
}
References assert, and data_.
EntryKeyField() [2/2]
EntryKeyField::EntryKeyField (const EntryKeyField & old)
Copy constructor.
Parameters
old A field.
Definition at line 55 of file EntryKeyField.cc.
                                                    :
    data_(old.data_->copy()), properties_(old.properties_) {
}
Member Function Documentation
coefficient()
double EntryKeyField::coefficient (const EntryKeyField & field1, const EntryKeyField & field2) const
Returns the relative position between two fields.
Returns the field's relative position to the first field compared to the second. For example, if this field has value 14, the first field has 10 and the second 20, relative position would be 0.4.
Parameters
field1 First field.
field2 Second field.
Returns
The relative position between two fields.
Definition at line 130 of file EntryKeyField.cc.
{
    return data_->coefficient(field1.data_, field2.data_);
}
References EntryKeyData::coefficient(), and data_.
Referenced by CostDBEntry::CostDBEntry().
isEqual()
bool EntryKeyField::isEqual (const EntryKeyField & field) const
Checks if two fields are equal.
Parameters
field A field.
Returns
True if two integers are equal, otherwise false.
Definition at line 92 of file EntryKeyField.cc.
{
    return data_->isEqual(field.data_);
}
References data_, and EntryKeyData::isEqual().
Referenced by Interpolation::filter(), and Matcher::onlyThisFieldDiffers().
isGreater()
bool EntryKeyField::isGreater (const EntryKeyField & field) const
Checks if this field is greater than another field.
Parameters
field A field.
Returns
True if this field is greater than another field, otherwise false.
Definition at line 103 of file EntryKeyField.cc.
{
    return data_->isGreater(field.data_);
}
References data_, and EntryKeyData::isGreater().
Referenced by Interpolation::filter().
isSmaller()
bool EntryKeyField::isSmaller (const EntryKeyField & field) const
Checks if this field is smaller than another field.
Parameters
field A field.
Returns
True if this field is smaller than another field, otherwise false.
Definition at line 114 of file EntryKeyField.cc.
{
    return data_->isSmaller(field.data_);
}
References data_, and EntryKeyData::isSmaller().
Referenced by Interpolation::filter().
operator=()
EntryKeyField & EntryKeyField::operator= (const EntryKeyField & old)
Assignment operator.
Parameters
old A field.
Returns
A copy of the field.
Definition at line 77 of file EntryKeyField.cc.
{
    if (this != &old) {
    data_ = old.data_->copy();
    properties_ = old.properties_;
    }
    return *this;
}
References EntryKeyData::copy(), data_, and properties_.
toString()
std::string EntryKeyField::toString () const
Returns value of the field as a string.
Returns
Value of the field as a string.
Definition at line 143 of file EntryKeyField.cc.
{
    return data_->toString();
}
References data_, and EntryKeyData::toString().
type()
const EntryKeyFieldProperty * EntryKeyField::type () const
Referenced by CostDBEntryKey::addField(), CostDBEntry::CostDBEntry(), Matcher::onlyThisFieldDiffers(), and CostDBEntryKey::replaceField().
Member Data Documentation
data_
EntryKeyData* EntryKeyField::data_ private
Value of the field.
Definition at line 62 of file EntryKeyField.hh.
Referenced by coefficient(), isEqual(), isGreater(), isSmaller(), operator=(), toString(), and ~EntryKeyField().
properties_
const EntryKeyFieldProperty* EntryKeyField::properties_ private
Type of the field.
Definition at line 64 of file EntryKeyField.hh.
Referenced by operator=().
The documentation for this class was generated from the following files:
EntryKeyField.hh
EntryKeyField.cc