OpenASIP: ArrayImageWriter Class Reference
ArrayImageWriter Class Reference
#include <ArrayImageWriter.hh>
Public Member Functions
ArrayImageWriter (const BitVector &bits, int rowLength)
virtual ~ArrayImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Writes the bit image with ASCII 1's and 0's such that each line is enveloped by " marks. Can be used to initialize an VHDL array, for example.
Definition at line 43 of file ArrayImageWriter.hh.
Constructor & Destructor Documentation
ArrayImageWriter()
ArrayImageWriter::ArrayImageWriter (const BitVector & bits, int rowLength)
The constructor.
Parameters
bits The bits to write.
rowLength Length of the rows to write.
Definition at line 45 of file ArrayImageWriter.cc.
                                                                       :
    AsciiImageWriter(bits, rowLength) {
}
~ArrayImageWriter()
ArrayImageWriter::~ArrayImageWriter () virtual
The destructor.
Definition at line 53 of file ArrayImageWriter.cc.
{
}
Member Function Documentation
writeImage()
void ArrayImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given stream.
Parameters
stream The stream to write.
Reimplemented from AsciiImageWriter.
Reimplemented in ArrayProgramImageWriter, VhdlImageWriter, and VhdlProgramImageWriter.
Definition at line 63 of file ArrayImageWriter.cc.
{
    int lineCount =
        static_cast<int>(
            ceil(static_cast<double>(bits().size()) / rowLength()));
    for (int line = 1; line < lineCount; line++) {
        stream << "\"";
        writeSequence(stream, rowLength());
        stream << "\"," << std::endl;
    }
    stream << "\"";
    bool padRemainingBits = true;
    writeSequence(stream, rowLength(), padRemainingBits);
    stream << "\"";
}
References AsciiImageWriter::bits(), AsciiImageWriter::rowLength(), and AsciiImageWriter::writeSequence().
Referenced by VhdlImageWriter::writeImage().
The documentation for this class was generated from the following files:
ArrayImageWriter.hh
ArrayImageWriter.cc