OpenASIP: BusChainFigure Class Reference
BusChainFigure Class Reference
#include <BusChainFigure.hh>
Public Member Functions
BusChainFigure ()
virtual ~BusChainFigure ()
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutChildren (wxDC *)
virtual void drawSelf (wxDC *)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
Private Member Functions
BusChainFigure & operator= (BusChainFigure &old)
Assignment not allowed.
BusChainFigure (BusChainFigure &old)
Copying not allowed.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(255, 150, 150)
Default colour for the figure.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a bus chain.
Definition at line 47 of file BusChainFigure.hh.
Constructor & Destructor Documentation
BusChainFigure() [1/2]
BusChainFigure::BusChainFigure ()
The Constructor.
Definition at line 48 of file BusChainFigure.cc.
                              : Figure() {
    minSize_ = wxSize(
    MachineCanvasLayoutConstraints::BUS_MIN_WIDTH,
    MachineCanvasLayoutConstraints::BUS_MIN_HEIGHT);
    size_ = minSize_;
}
References MachineCanvasLayoutConstraints::BUS_MIN_HEIGHT, MachineCanvasLayoutConstraints::BUS_MIN_WIDTH, Figure::minSize_, and Figure::size_.
~BusChainFigure()
BusChainFigure::~BusChainFigure () virtual
The Destructor.
Definition at line 58 of file BusChainFigure.cc.
{
}
BusChainFigure() [2/2]
BusChainFigure::BusChainFigure (BusChainFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void BusChainFigure::drawSelf (wxDC * dc) protected virtual
Fills the background of the bus chain with a solid color.
Parameters
dc The device context.
Reimplemented from Figure.
Definition at line 102 of file BusChainFigure.cc.
{
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    dc->SetPen(pen);
    wxBrush brush = wxBrush(DEFAULT_COLOUR, wxSOLID);
    dc->SetBrush(brush);
    dc->DrawRectangle(location_.x, location_.y, size_.GetWidth(),
                      size_.GetHeight());
}
References DEFAULT_COLOUR, Figure::location_, and Figure::size_.
layoutChildren()
void BusChainFigure::layoutChildren (wxDC * dc) protected virtual
Lays out the segments in a column, spaced evenly.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 67 of file BusChainFigure.cc.
{
    int height = MachineCanvasLayoutConstraints::BRIDGE_SPACE;
    int y = location_.y + MachineCanvasLayoutConstraints::BRIDGE_SPACE;
    int x = location_.x;
    for(unsigned int i = 0; i < children_.size(); i++) {
        children_[i]->setLocation(wxPoint(x, y));
    children_[i]->setWidth(size_.GetWidth());
    // set bridge direction
    BridgeFigure* br = dynamic_cast<BridgeFigure*>(children_[i]);
    if (br != NULL && br->direction() != BridgeFigure::DIR_BIDIR &&
        br->target() == children_[i-1]) {
        br->setDirection(BridgeFigure::DIR_LEFT);
    }
    children_[i]->layout(dc);
        y += children_[i]->bounds().GetHeight() +
        MachineCanvasLayoutConstraints::BRIDGE_SPACE;
    height += children_[i]->bounds().GetHeight() +
        MachineCanvasLayoutConstraints::BRIDGE_SPACE;
    }
    size_.SetHeight(height);
}
References MachineCanvasLayoutConstraints::BRIDGE_SPACE, Figure::children_, BridgeFigure::DIR_BIDIR, BridgeFigure::DIR_LEFT, BridgeFigure::direction(), Figure::location_, BridgeFigure::setDirection(), Figure::size_, and ConnectionFigure::target().
operator=()
BusChainFigure & BusChainFigure::operator= (BusChainFigure & old) private
Assignment not allowed.
Member Data Documentation
DEFAULT_COLOUR
const wxColour BusChainFigure::DEFAULT_COLOUR = wxColour(255, 150, 150) static private
Default colour for the figure.
Definition at line 63 of file BusChainFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
BusChainFigure.hh
BusChainFigure.cc