OpenASIP: BFUnscheduleMove Class Reference
BFUnscheduleMove Class Reference
#include <BFUnscheduleMove.hh>
Public Member Functions
BFUnscheduleMove (BF2Scheduler &sched, MoveNode &mn)
void unscheduleOriginal ()
void undoOnlyMe ()
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
void returnOriginal ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes
MoveNode & mn_
int oldCycle_
const TTAMachine::Bus * oldBus_
const TTAMachine::Bus * prologBus_
int oldImmWriteCycle_
int prologImmWriteCycle_
const TTAMachine::FunctionUnit * dstFU_
const TTAMachine::FunctionUnit * srcFU_
const TTAMachine::ImmediateUnit * immu_
int immRegIndex_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes
static int recurseCounter_ = 0
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Detailed Description
Definition at line 48 of file BFUnscheduleMove.hh.
Constructor & Destructor Documentation
BFUnscheduleMove()
BFUnscheduleMove::BFUnscheduleMove (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 51 of file BFUnscheduleMove.hh.
                                           :
        BFOptimization(sched), mn_(mn), prologBus_(NULL),
        oldImmWriteCycle_(-1), prologImmWriteCycle_(-1), dstFU_(NULL),
        srcFU_(NULL), immu_(NULL), immRegIndex_(-1) {}
Member Function Documentation
operator()()
bool BFUnscheduleMove::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 152 of file BFUnscheduleMove.cc.
{
    unscheduleOriginal();
    return true;
}
References unscheduleOriginal().
returnOriginal()
void BFUnscheduleMove::returnOriginal () protected
Definition at line 107 of file BFUnscheduleMove.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\treturning original: " << mn_.toString() << " current bus: "
              << mn_.move().bus().name() << " old bus: " << oldBus_->name()
              << " cycle: " << oldCycle_ << std::endl;
#endif
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    if (!canAssign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_, prologBus_,
                   oldImmWriteCycle_, prologImmWriteCycle_, immu_,
                   immRegIndex_, true)) {
        std::cerr << "Cannot return to old cycle: " << mn_.toString() << " cycle: " << oldCycle_  << std::endl;
        if (mn_.isDestinationOperation()) {
            std::cerr << "dstPO: " << mn_.destinationOperation().toString() << std::endl;
        }
        if (mn_.isSourceOperation()) {
            std::cerr << "srcPO: " << mn_.sourceOperation().toString() << std::endl;
        }
        std::cerr << "Original bus: " << oldBus_->name() << std::endl;
        ddg().writeToDotFile("cannot_return_old_cycle.dot");
        TTAProgram::Instruction* ins = rm().instruction(oldCycle_);
        for (int i = 0; i < ins->moveCount(); i++) {
            std::cerr << "\t" << POMDisassembler::disassemble(ins->move(i))
                      << " bus: " << ins->move(i).bus().name()
                      << std::endl;
        }
        std::cerr << "ins contains " << ins->immediateCount() << " immediates." << std::endl;
        assert(false);
    }
#endif
    assign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_, prologBus_,
       oldImmWriteCycle_, prologImmWriteCycle_, immu_, immRegIndex_);
}
References assert, BFOptimization::assign(), TTAProgram::Move::bus(), BFOptimization::canAssign(), BFOptimization::ddg(), MoveNode::destinationOperation(), POMDisassembler::disassemble(), dstFU_, TTAProgram::Instruction::immediateCount(), immRegIndex_, immu_, SimpleResourceManager::instruction(), MoveNode::isDestinationOperation(), MoveNode::isSourceOperation(), mn_, MoveNode::move(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), TTAMachine::Component::name(), oldBus_, oldCycle_, oldImmWriteCycle_, prologBus_, prologImmWriteCycle_, recurseCounter_, BFOptimization::rm(), MoveNode::sourceOperation(), srcFU_, MoveNode::toString(), ProgramOperation::toString(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Referenced by BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), BFRescheduleMove::undoOnlyMe(), and undoOnlyMe().
undoOnlyMe()
void BFUnscheduleMove::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 144 of file BFUnscheduleMove.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "BFUnscheudleMove undo" << std::endl;
#endif
    returnOriginal();
}
References returnOriginal().
unscheduleOriginal()
void BFUnscheduleMove::unscheduleOriginal ()
Definition at line 47 of file BFUnscheduleMove.cc.
{
    oldCycle_ = mn_.cycle();
    oldBus_ = &mn_.move().bus();
    if (mn_.isSourceOperation()) {
        srcFU_ = &mn_.move().source().functionUnit();
    }
    if (mn_.isDestinationOperation()) {
        dstFU_ = &mn_.move().destination().functionUnit();
    }
    if (mn_.move().source().isImmediateRegister()) {
        oldImmWriteCycle_ = rm().immediateWriteCycle(mn_);
        immRegIndex_ = mn_.move().source().index();
        immu_ = &mn_.move().source().immediateUnit();
    }
    MoveNode* prologMN = ii() ?  duplicator().getMoveNode(mn_) : NULL;
    if (prologMN != NULL) {
        prologBus_ = &prologMN->move().bus();
        if (prologMN->move().source().isImmediateRegister()) {
            prologImmWriteCycle_ = prologRM()->immediateWriteCycle(*prologMN);
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tProlog move: " << prologMN->toString() << std::endl;
        std::cerr << "\t\t\t\tBFUnscheduleMove Saving prolog bus: " << prologBus_->name() << " cycle: " << oldCycle_ << std::endl;
#endif
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\tUnscheduling original: " << mn_.toString() << " bus: " << oldBus_->name() << std::endl;
#endif
    unassign(mn_, false);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    if (!canAssign(oldCycle_, mn_, oldBus_, srcFU_, dstFU_, prologBus_,
                   oldImmWriteCycle_, prologImmWriteCycle_)) {
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tCannot assign to old cycle: " << mn_.toString()
                  << " old cycle: " << oldCycle_ << std::endl;
        ddg().writeToDotFile("cannot_assign_old_cycle.dot");
        if (mn_.isSourceOperation()) {
            std::cerr << "\t\twhole src PO: " << mn_.sourceOperation().toString()
                      << std::endl;
        }
        if (mn_.isDestinationOperation()) {
            std::cerr << "\t\twhole dst PO: " << mn_.destinationOperation().toString()
                      << std::endl;
        }
        assert(false);
    }
#endif
}
References assert, TTAProgram::Move::bus(), BFOptimization::canAssign(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), MoveNode::destinationOperation(), dstFU_, BFOptimization::duplicator(), TTAProgram::Terminal::functionUnit(), MoveNodeDuplicator::getMoveNode(), BFOptimization::ii(), TTAProgram::Terminal::immediateUnit(), SimpleResourceManager::immediateWriteCycle(), immRegIndex_, immu_, TTAProgram::Terminal::index(), MoveNode::isDestinationOperation(), TTAProgram::Terminal::isImmediateRegister(), MoveNode::isSourceOperation(), mn_, MoveNode::move(), TTAMachine::Component::name(), oldBus_, oldCycle_, oldImmWriteCycle_, prologBus_, prologImmWriteCycle_, BFOptimization::prologRM(), recurseCounter_, BFOptimization::rm(), TTAProgram::Move::source(), MoveNode::sourceOperation(), srcFU_, MoveNode::toString(), ProgramOperation::toString(), BFOptimization::unassign(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Referenced by BFPushAntidepDown::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), and operator()().
Member Data Documentation
dstFU_
const TTAMachine::FunctionUnit* BFUnscheduleMove::dstFU_ protected
Definition at line 67 of file BFUnscheduleMove.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
immRegIndex_
int BFUnscheduleMove::immRegIndex_ protected
Definition at line 70 of file BFUnscheduleMove.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
immu_
const TTAMachine::ImmediateUnit* BFUnscheduleMove::immu_ protected
Definition at line 69 of file BFUnscheduleMove.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
mn_
MoveNode& BFUnscheduleMove::mn_ protected
Definition at line 61 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), BFPushMoveUp::operator()(), BFPushMoveUp2::operator()(), returnOriginal(), BFRescheduleMove::undoOnlyMe(), and unscheduleOriginal().
oldBus_
const TTAMachine::Bus* BFUnscheduleMove::oldBus_ protected
Definition at line 63 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), returnOriginal(), BFRescheduleMove::undoOnlyMe(), and unscheduleOriginal().
oldCycle_
int BFUnscheduleMove::oldCycle_ protected
Definition at line 62 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), returnOriginal(), BFRescheduleMove::undoOnlyMe(), and unscheduleOriginal().
oldImmWriteCycle_
int BFUnscheduleMove::oldImmWriteCycle_ protected
Definition at line 65 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), returnOriginal(), and unscheduleOriginal().
prologBus_
const TTAMachine::Bus* BFUnscheduleMove::prologBus_ protected
Definition at line 64 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), returnOriginal(), and unscheduleOriginal().
prologImmWriteCycle_
int BFUnscheduleMove::prologImmWriteCycle_ protected
Definition at line 66 of file BFUnscheduleMove.hh.
Referenced by BFPushAntidepDown::operator()(), returnOriginal(), and unscheduleOriginal().
recurseCounter_
int BFUnscheduleMove::recurseCounter_ = 0 static protected
Definition at line 71 of file BFUnscheduleMove.hh.
Referenced by BFPushMoveUp::operator()(), returnOriginal(), BFRescheduleMove::undoOnlyMe(), and unscheduleOriginal().
srcFU_
const TTAMachine::FunctionUnit* BFUnscheduleMove::srcFU_ protected
Definition at line 68 of file BFUnscheduleMove.hh.
Referenced by returnOriginal(), and unscheduleOriginal().
The documentation for this class was generated from the following files:
BFUnscheduleMove.hh
BFUnscheduleMove.cc