OpenASIP: SimpleICOptimizer Class Reference
SimpleICOptimizer Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Optimizes the IC of the given configuration")
SimpleICOptimizer ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual bool requiresApplication () const
virtual std::vector< RowID > explore (const RowID &startPointConfigurationID, const unsigned int &)
void readParameters ()
void removeAllConnections (TTAMachine::Machine &mach)
bool fixIntRegisters (TTAMachine::Machine &mach)
void addConnections (TTAMachine::Machine &mach, Program &prog)
Private Attributes
std::string tpef_
name of the tpef file
bool addOnly_
can we remove connections
bool evaluateResult_
evaluate the result(s)
bool preserveMinimalOpset_
respect minimal opset when removing connections
Static Private Attributes
static const std::string tpefPN_
static const std::string tpefDefaultPN_
static const std::string addOnlyPN_
static const std::string evaluatePN_
static const std::string preserveMinOpsPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that optimizes the interconnection network of the given configuration by removing the connections that are not used in the parallel program.
Definition at line 79 of file SimpleICOptimizer.cc.
Constructor & Destructor Documentation
SimpleICOptimizer()
SimpleICOptimizer::SimpleICOptimizer () inline private
Definition at line 82 of file SimpleICOptimizer.cc.
                       : DesignSpaceExplorerPlugin(),
        tpef_(""),
        addOnly_(false),
        evaluateResult_(true),
        preserveMinimalOpset_(true) {
        // compulsory parameters
        // none
        // parameters that have a default value
        addParameter(tpefPN_, STRING, false, "");
        addParameter(addOnlyPN_, BOOL, false,
                Conversion::toString(addOnly_));
        addParameter(evaluatePN_, BOOL, false,
                Conversion::toString(evaluateResult_));
        addParameter(preserveMinOpsPN_, BOOL, false,
                Conversion::toString(preserveMinimalOpset_));
    }
References addOnly_, addOnlyPN_, DesignSpaceExplorerPlugin::addParameter(), BOOL, evaluatePN_, evaluateResult_, preserveMinimalOpset_, preserveMinOpsPN_, STRING, Conversion::toString(), and tpefPN_.
Member Function Documentation
addConnections()
void SimpleICOptimizer::addConnections (TTAMachine::Machine & mach, Program & prog) inline private
Adds connections used in the program to the given machine.
Connections to add are determined by procedure instructions in application domains programs.
Parameters
mach Machine where the connections are added.
prog Scheduled program where the used connections are searched.
Definition at line 423 of file SimpleICOptimizer.cc.
{
        Machine::SocketNavigator socketNav = mach.socketNavigator();
        Machine::BusNavigator busNav = mach.busNavigator();
        // go through every procedure in the program
        for (int i = 0; i < prog.procedureCount(); i++) {
            Procedure& procedure = prog.procedure(i);
            // go through every instruction
            for (int j = 0; j < procedure.instructionCount(); j++) {
                Instruction& instruction = procedure.instructionAtIndex(j);
                // check all moves and add connection from source to bus and
                // bus to destination
                for (int m = 0; m < instruction.moveCount(); m++) {
                    Move& move = instruction.move(m);
                    std::string busName = move.bus().name();
                    std::string sourceName = "";
                    try {
                        sourceName = move.sourceSocket().name();
                    } catch (const WrongSubclass&) {
                        // source was an immediate, no error
                        assert(move.source().isImmediate());
                    }
                    std::string destinationName =
                        move.destinationSocket().name();
                    Bus* bus = busNav.item(busName);
                    // connect the source socket to the bus
                    if (sourceName != "") {
                        Socket* socket = socketNav.item(sourceName);
                        for (int s = 0; s < bus->segmentCount(); s++) {
                            if (!socket->isConnectedTo(*bus->segment(s))) {
                                socket->attachBus(*bus->segment(s));
                                // socket direction is lost when the
                                // connections were removed
                                socket->setDirection(Socket::OUTPUT);
                            }
                        }
                    }
                    Socket* socket = socketNav.item(destinationName);
                    for (int s = 0; s < bus->segmentCount(); s++) {
                        if (!socket->isConnectedTo(*bus->segment(s))) {
                            socket->attachBus(*bus->segment(s));
                            // socket direction is lost when the
                            // connections were removed
                            socket->setDirection(Socket::INPUT);
                        }
                    }
                }
            }
        }
    }
References assert, TTAMachine::Socket::attachBus(), TTAProgram::Move::bus(), TTAMachine::Machine::busNavigator(), TTAProgram::Move::destinationSocket(), TTAMachine::Socket::INPUT, TTAProgram::CodeSnippet::instructionAtIndex(), TTAProgram::CodeSnippet::instructionCount(), TTAMachine::Socket::isConnectedTo(), TTAProgram::Terminal::isImmediate(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), TTAMachine::Component::name(), TTAMachine::Socket::OUTPUT, TTAProgram::Program::procedure(), TTAProgram::Program::procedureCount(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), TTAMachine::Socket::setDirection(), TTAMachine::Machine::socketNavigator(), TTAProgram::Move::source(), and TTAProgram::Move::sourceSocket().
Referenced by explore().
explore()
virtual std::vector< RowID > SimpleICOptimizer::explore (const RowID & startPointConfigurationID, const unsigned int &) inline private virtual
Optimizes the IC of the given configuration by removing not used connections.
First removes connections and then adds them by looking all application domains programs instructions and their moves. Needs the start point configuration to get the architecture which connections are optimized.
Supported parameters:
tpef, name of the scheduled program file, no default value.
add_only, if parameter is set the connections of the given configuration won't be emptied, just added new ones, not set as default.
Parameters
startPointConfigurationID Configuration to optimize.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 125 of file SimpleICOptimizer.cc.
{
        std::vector<RowID> result;
        readParameters();
        try {
            DSDBManager& dsdb = db();
            DSDBManager::MachineConfiguration conf =
                dsdb.configuration(startPointConfigurationID);
            // loads starting configuration
            Machine* origMach = NULL;
            Machine* mach = NULL;
            try {
                origMach = dsdb.architecture(conf.architectureID);
                mach = dsdb.architecture(conf.architectureID);
            } catch (const Exception& e) {
                std::ostringstream msg(std::ostringstream::out);
                msg << e.errorMessage() << std::endl;
                verboseLog(msg.str());
                return result;
            }
            if (!addOnly_) {
                removeAllConnections(*mach);
            }
            // if no scheduled programs given
            Program* program = NULL;
            if (tpef_ == "") {
                //SchedulerFrontend scheduler;
                try {
                    std::set<RowID> appIDs = dsdb.applicationIDs();
                    std::set<RowID>::const_iterator iter = appIDs.begin();
                    if (iter == appIDs.end()) {
                        // no applications, nothing can be done
                        return result;
                    }
                    for (; iter != appIDs.end(); iter++) {
                        TestApplication testApp(dsdb.applicationPath(*iter));
                        program = DesignSpaceExplorer::schedule(
                                testApp.applicationPath(), *origMach);
                        if (program == NULL) {
                            std::string msg = "SimpleICOptimizer: Schedule "
                                "failed for program: " +
                                testApp.applicationPath();
                            verboseLogC(msg, 1)
                            return result;
                        }
                        addConnections(*mach, *program);
                    }
                } catch (const Exception& e) {
                    std::ostringstream msg(std::ostringstream::out);
                    msg << e.errorMessageStack() << std::endl;
                    verboseLog(msg.str());
                    delete mach;
                    mach = NULL;
                    return result;
                }
            } else {
                try {
                    program = Program::loadFromTPEF(tpef_, *origMach);
                    addConnections(*mach, *program);
                } catch (const Exception& e) {
                    std::ostringstream msg(std::ostringstream::out);
                    msg << "Error while loading the program in "
                        << "SimpleICOptimizer:" << endl
                        << e.errorMessage() << endl;
                    verboseLog(msg.str());
                    return result;
                }
            }
            DSDBManager::MachineConfiguration tempConf;
            try {
                tempConf.architectureID = dsdb.addArchitecture(*mach);
                tempConf.hasImplementation = false;
            } catch (const RelationalDBException& e) {
                std::ostringstream msg(std::ostringstream::out);
                msg << "Error while adding ADF to the dsdb. "
                    << "ADF probably too big." << endl;
                verboseLog(msg.str());
                return result;
            }
            // add config to database to pass it to
            // RemoveUnconnectedComponents plugin
            RowID tempConfID = dsdb.addConfiguration(tempConf);
            // remove unconnected components with RemoveUnconnectedComponents
            // plugin
            DesignSpaceExplorerPlugin* removeUnconnected =
                DesignSpaceExplorer::loadExplorerPlugin(
                    "RemoveUnconnectedComponents", &db());
            // parameters for RemoveUnconnectedComponents plugin
            removeUnconnected->giveParameter("allow_remove", "true");
            std::vector<RowID> cleanedTempConfIDs =
                removeUnconnected->explore(tempConfID);
            delete removeUnconnected;
            removeUnconnected = NULL;
            if (cleanedTempConfIDs.size() < 1) {
                std::string errorMsg = "SimpleICOptimizer plugin: "
                    "RemoveUnconnectedComponents plugin failed to produce"
                    "result.";
                verboseLogC(errorMsg, 2)
                return result;
            }
            DSDBManager::MachineConfiguration newConf =
                dsdb.configuration(cleanedTempConfIDs.at(0));
            // if original machine had enough int registers, check and
            // possibly try to fix the new machine
            RegisterQuantityCheck RFCheck;
            if (RFCheck.checkIntRegs(*origMach)) {
                Machine* cleanedMach =
                    dsdb.architecture(newConf.architectureID);
                if (fixIntRegisters(*cleanedMach)) {
                    // replace newConf machine with the fixed one
                    newConf.architectureID =
                        dsdb.addArchitecture(*cleanedMach);
                }
            }
            // create implementation for newConf if orginal config had one
            if (conf.hasImplementation && !newConf.hasImplementation) {
                createImplementation(newConf, newConf);
            } else {
                newConf.hasImplementation = false;
            }
            // evaluate and save new config id as result
            CostEstimates estimates;
            if (evaluateResult_) {
                // evaluate the new config
               bool estimate = newConf.hasImplementation;
                if (evaluate(newConf, estimates, estimate)) {
                    RowID confID = dsdb.addConfiguration(newConf);
                    result.push_back(confID);
                } else {
                    // cannot evaluate
                    std::ostringstream msg(std::ostringstream::out);
                    msg << "SimpleICOptimizer plugin couldn't evaluate "
                        << "generated config - nothing done." << endl;
                    verboseLog(msg.str());
                    return result;
                }
            } else {
                RowID confID = dsdb.addConfiguration(newConf);
                result.push_back(confID);
            }
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while using SimpleICOptimizer:" << endl
                << e.errorMessage() << endl;
            verboseLog(msg.str());
            return result;
        }
        return result;
    }
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), addConnections(), addOnly_, DSDBManager::applicationIDs(), TestApplication::applicationPath(), DSDBManager::applicationPath(), DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, RegisterQuantityCheck::checkIntRegs(), DSDBManager::configuration(), DesignSpaceExplorer::createImplementation(), DesignSpaceExplorer::db(), Exception::errorMessage(), Exception::errorMessageStack(), DesignSpaceExplorer::evaluate(), evaluateResult_, DesignSpaceExplorerPlugin::explore(), fixIntRegisters(), DesignSpaceExplorerPlugin::giveParameter(), DSDBManager::MachineConfiguration::hasImplementation, DesignSpaceExplorer::loadExplorerPlugin(), TTAProgram::Program::loadFromTPEF(), program, readParameters(), removeAllConnections(), DesignSpaceExplorer::schedule(), tpef_, verboseLog, and verboseLogC.
fixIntRegisters()
bool SimpleICOptimizer::fixIntRegisters (TTAMachine::Machine & mach) inline private
Checks that produced machine is still usable
Parameters
mach Machine where the connections are added.
Returns
True if something done to the machine given as parameter.
Definition at line 398 of file SimpleICOptimizer.cc.
{
        // check that that machine has enough int registers and fix if needed
        // and can be fixed
        RegisterQuantityCheck RFCheck;
        if (!RFCheck.checkIntRegs(mach) && RFCheck.canFixIntRegs(mach)) {
            if (!RFCheck.fixIntRegs(mach)) {
                verboseLog("Failed to add missing integer registers to the"
                        "machine.");
                return false;
            } else {
                return true;
            }
        }
        return false;
    }
References RegisterQuantityCheck::canFixIntRegs(), RegisterQuantityCheck::checkIntRegs(), RegisterQuantityCheck::fixIntRegs(), and verboseLog.
Referenced by explore().
PLUGIN_DESCRIPTION()
SimpleICOptimizer::PLUGIN_DESCRIPTION ("Optimizes the IC of the given configuration") private
producesArchitecture()
virtual bool SimpleICOptimizer::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 102 of file SimpleICOptimizer.cc.
{ return true; }
readParameters()
void SimpleICOptimizer::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 314 of file SimpleICOptimizer.cc.
{
        readOptionalParameter(tpefPN_, tpef_);
        readOptionalParameter(addOnlyPN_, addOnly_);
        readOptionalParameter(evaluatePN_, evaluateResult_);
        readOptionalParameter(preserveMinOpsPN_, preserveMinimalOpset_);
    }
References addOnly_, addOnlyPN_, evaluatePN_, evaluateResult_, preserveMinimalOpset_, preserveMinOpsPN_, DesignSpaceExplorerPlugin::readOptionalParameter(), tpef_, and tpefPN_.
Referenced by explore().
removeAllConnections()
void SimpleICOptimizer::removeAllConnections (TTAMachine::Machine & mach) inline private
Removes all socket-bus connection from the given machine.
Parameters
mach Machine which connections are removed.
Definition at line 327 of file SimpleICOptimizer.cc.
{
        Machine::SocketNavigator socketNav = mach.socketNavigator();
        Machine::BusNavigator busNav = mach.busNavigator();
        RegisterQuantityCheck RFCheck;
        MinimalOpSetCheck minimalOpSetCheck = MinimalOpSetCheck();
        if (!preserveMinimalOpset_) {
            for (int i = 0; i < socketNav.count(); i++) {
                Socket* socket = socketNav.item(i);
                for (int bus = 0; bus < busNav.count(); bus++) {
                    socket->detachBus(*busNav.item(bus));
                }
            }
        } else {
            // remove connections only if connected minimal opset preserved.
            for (int i = 0; i < socketNav.count(); i++) {
                Socket* socket = socketNav.item(i);
                std::set<std::string> ignoreFUNames;
                std::set<std::string> ignoreRFNames;
                // check all ports connected to the socket
                for (int si = 0; si < socket->portCount(); ++si) {
                    Port* port = socket->port(si);
                    if (dynamic_cast<FUPort*>(port)) {
                        ignoreFUNames.insert(port->parentUnit()->name());
                    } else if (dynamic_cast<RFPort*>(port)) {
                        ignoreRFNames.insert(port->parentUnit()->name());
                    }
                }
                // TODO: refactor below
                // TODO: add test that same FU/RF is not checked multiple
                // times in situations where there are more than one socket
                // connected to the same FU/RF, do this by storing unit names
                // and the verdict if connections can be removed as a pair to
                // a map
                if (!ignoreFUNames.empty()) {
                    if (minimalOpSetCheck.checkWithIgnore(mach, ignoreFUNames)) {
                        if (!ignoreRFNames.empty()) {
                            if (RFCheck.checkWithIgnore(mach, ignoreRFNames))
{
                                for (int bus = 0; bus < busNav.count(); bus++)
{
                                    socket->detachBus(*busNav.item(bus));
                                }
                            }
                        } else {
                            for (int bus = 0; bus < busNav.count(); bus++) {
                                socket->detachBus(*busNav.item(bus));
                            }
                        }
                    }
                } else if (!ignoreRFNames.empty()) {
                    if (RFCheck.checkWithIgnore(mach, ignoreRFNames)) {
                        for (int bus = 0; bus < busNav.count(); bus++) {
                            socket->detachBus(*busNav.item(bus));
                        }
                    }
                } else {
                    for (int bus = 0; bus < busNav.count(); bus++) {
                        socket->detachBus(*busNav.item(bus));
                    }
                }
            }
        }
    }
References TTAMachine::Machine::busNavigator(), RegisterQuantityCheck::checkWithIgnore(), MinimalOpSetCheck::checkWithIgnore(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Socket::detachBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), preserveMinimalOpset_, and TTAMachine::Machine::socketNavigator().
Referenced by explore().
requiresApplication()
virtual bool SimpleICOptimizer::requiresApplication () const inline private virtual
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 105 of file SimpleICOptimizer.cc.
{ return false; }
requiresHDB()
virtual bool SimpleICOptimizer::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 103 of file SimpleICOptimizer.cc.
{ return false; }
requiresSimulationData()
virtual bool SimpleICOptimizer::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 104 of file SimpleICOptimizer.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool SimpleICOptimizer::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 101 of file SimpleICOptimizer.cc.
{ return true; }
Member Data Documentation
addOnly_
bool SimpleICOptimizer::addOnly_ private
can we remove connections
Definition at line 304 of file SimpleICOptimizer.cc.
Referenced by explore(), readParameters(), and SimpleICOptimizer().
addOnlyPN_
const std::string SimpleICOptimizer::addOnlyPN_ static private
Definition at line 297 of file SimpleICOptimizer.cc.
Referenced by readParameters(), and SimpleICOptimizer().
evaluatePN_
const std::string SimpleICOptimizer::evaluatePN_ static private
Definition at line 298 of file SimpleICOptimizer.cc.
Referenced by readParameters(), and SimpleICOptimizer().
evaluateResult_
bool SimpleICOptimizer::evaluateResult_ private
evaluate the result(s)
Definition at line 306 of file SimpleICOptimizer.cc.
Referenced by explore(), readParameters(), and SimpleICOptimizer().
preserveMinimalOpset_
bool SimpleICOptimizer::preserveMinimalOpset_ private
respect minimal opset when removing connections
Definition at line 308 of file SimpleICOptimizer.cc.
Referenced by readParameters(), removeAllConnections(), and SimpleICOptimizer().
preserveMinOpsPN_
const std::string SimpleICOptimizer::preserveMinOpsPN_ static private
Definition at line 299 of file SimpleICOptimizer.cc.
Referenced by readParameters(), and SimpleICOptimizer().
tpef_
std::string SimpleICOptimizer::tpef_ private
name of the tpef file
Definition at line 302 of file SimpleICOptimizer.cc.
Referenced by explore(), and readParameters().
tpefDefaultPN_
const std::string SimpleICOptimizer::tpefDefaultPN_ static private
Definition at line 296 of file SimpleICOptimizer.cc.
tpefPN_
const std::string SimpleICOptimizer::tpefPN_ static private
Definition at line 295 of file SimpleICOptimizer.cc.
Referenced by readParameters(), and SimpleICOptimizer().
The documentation for this class was generated from the following file:
SimpleICOptimizer.cc