OpenASIP: IDF::UnitImplementationLocation Class Reference
IDF::UnitImplementationLocation Class Reference
#include <UnitImplementationLocation.hh>
Public Member Functions
UnitImplementationLocation (const std::string &hdbFile, int id, const std::string &unitName)
UnitImplementationLocation (const ObjectState *state)
virtual ~UnitImplementationLocation ()
virtual std::string hdbFile () const
std::string hdbFileOriginal () const
virtual int id () const
virtual std::string unitName () const
virtual void setParent (MachineImplementation &parent)
virtual void setID (int id)
virtual void setHDBFile (std::string file)
void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_UNIT_IMPLEMENTATION
ObjectState name for unit implementation.
static const std::string OSKEY_HDB_FILE = "hdb_file"
ObjectState attribute key for the name of the HDB file.
static const std::string OSKEY_ID = "id"
ObjectState attribute key for the entry ID.
static const std::string OSKEY_UNIT_NAME = "unit_name"
Objectstate attribute key for the name of the unit.
Private Attributes
std::string hdbFile_
Name of the HDB file.
int id_
Entry ID in the HDB.
std::string unitName_
Name of the unit in ADF.
MachineImplementation * parent_
The parent MachineImplementation instance.
Detailed Description
Indicates what implementation of a unit is used.
Refers to an entry in an HDB.
Definition at line 48 of file UnitImplementationLocation.hh.
Constructor & Destructor Documentation
UnitImplementationLocation() [1/2]
IDF::UnitImplementationLocation::UnitImplementationLocation (const std::string & hdbFile, int id, const std::string & unitName)
The constructor.
Parameters
hdbFile The database that contains the implementation.
id ID of the RF or FU entry in the database.
unitName Name of the corresponding unit in ADF.
Definition at line 60 of file UnitImplementationLocation.cc.
                               :
    hdbFile_(hdbFile), id_(id), unitName_(unitName), parent_(NULL) {
}
UnitImplementationLocation() [2/2]
IDF::UnitImplementationLocation::UnitImplementationLocation (const ObjectState * state)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
this is used by NullFUImplementationLocation
Definition at line 77 of file UnitImplementationLocation.cc.
    : hdbFile_(""), id_(0), unitName_(""), parent_(NULL) {
    /// this is used by NullFUImplementationLocation
    if (state == NULL)
        return;
    loadState(state);
}
References loadState().
~UnitImplementationLocation()
IDF::UnitImplementationLocation::~UnitImplementationLocation () virtual
The destructor.
Definition at line 88 of file UnitImplementationLocation.cc.
{
}
Member Function Documentation
hdbFile()
std::string IDF::UnitImplementationLocation::hdbFile () const virtual
Returns the absolute path to the HDB file.
Returns
Absolute path to the HDB file.
Exceptions
FileNotFound If the HDB file is not found in the search paths.
Reimplemented in IDF::NullUnitImplementationLocation.
Definition at line 99 of file UnitImplementationLocation.cc.
{
    vector<string> paths = Environment::hdbPaths();
    if (parent_) {
        paths.insert(
            paths.begin(), FileSystem::directoryOfPath(parent_->sourceIDF()));
    }
    TCEString expandedPath(hdbFile_);
    expandedPath.replaceString("tce:", "");
    expandedPath = FileSystem::expandTilde(expandedPath);
    return FileSystem::findFileInSearchPaths(paths, expandedPath);
}
References FileSystem::directoryOfPath(), FileSystem::expandTilde(), FileSystem::findFileInSearchPaths(), hdbFile_, Environment::hdbPaths(), parent_, TCEString::replaceString(), and IDF::MachineImplementation::sourceIDF().
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::ProcessorGenerator::checkIULatencies(), ProGe::BlockSourceCopier::copyShared(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), CostEstimator::Estimator::functionUnitArea(), CostEstimator::Estimator::functionUnitEnergy(), CostEstimator::Estimator::functionUnitMaximumComputationDelay(), CostEstimator::Estimator::functionUnitPortReadDelay(), CostEstimator::Estimator::functionUnitPortWriteDelay(), ProGeTestBenchGenerator::generate(), ProGe::ProGeUI::generateIDF(), ProGeScriptGenerator::getBlockOrder(), PlatformIntegrator::loadFUExternalPorts(), IDF::MachineImplementation::makeHDBPathRelative(), CostEstimator::Estimator::registerFileArea(), CostEstimator::Estimator::registerFileEnergy(), CostEstimator::Estimator::registerFileMaximumComputationDelay(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), testUnits(), ProcessorImplementationWindow::updateFUList(), ProcessorImplementationWindow::updateImplementationLists(), and ProcessorImplementationWindow::updateRFList().
hdbFileOriginal()
std::string IDF::UnitImplementationLocation::hdbFileOriginal () const
Returns the path to the file, which was defined in IDF.
Returns
Path to the HDB in IDF file.
Definition at line 117 of file UnitImplementationLocation.cc.
{
    return hdbFile_;
}
References hdbFile_.
Referenced by IDF::MachineImplementation::checkImplFiles().
id()
int IDF::UnitImplementationLocation::id () const virtual
Returns the entry ID in HDB.
Returns
The entry ID.
Reimplemented in IDF::NullUnitImplementationLocation.
Definition at line 127 of file UnitImplementationLocation.cc.
{
    return id_;
}
References id_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::ProcessorGenerator::checkIULatencies(), ProGe::BlockSourceCopier::copyShared(), AutoSelectImplementationsDialog::findFUImplementations(), AutoSelectImplementationsDialog::findIUImplementations(), AutoSelectImplementationsDialog::findRFImplementations(), CostEstimator::Estimator::fuCostFunctionPluginOfImplementation(), ProGeTestBenchGenerator::generate(), ProGe::ProGeUI::generateIDF(), PlatformIntegrator::loadFUExternalPorts(), CostEstimator::Estimator::rfCostFunctionPluginOfImplementation(), setID(), testUnits(), ProcessorImplementationWindow::updateFUList(), ProcessorImplementationWindow::updateImplementationLists(), and ProcessorImplementationWindow::updateRFList().
loadState()
void IDF::UnitImplementationLocation::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance.
Implements Serializable.
Definition at line 164 of file UnitImplementationLocation.cc.
{
    const string procName = "UnitImplementationLocation::loadState";
    if (state->name() != OSNAME_UNIT_IMPLEMENTATION) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        hdbFile_ = state->stringAttribute(OSKEY_HDB_FILE);
        id_ = state->intAttribute(OSKEY_ID);
        unitName_ = state->stringAttribute(OSKEY_UNIT_NAME);
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References Exception::errorMessage(), hdbFile_, id_, ObjectState::intAttribute(), ObjectState::name(), OSKEY_HDB_FILE, OSKEY_ID, OSKEY_UNIT_NAME, OSNAME_UNIT_IMPLEMENTATION, ObjectState::stringAttribute(), and unitName_.
Referenced by UnitImplementationLocation().
saveState()
ObjectState * IDF::UnitImplementationLocation::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Implements Serializable.
Definition at line 187 of file UnitImplementationLocation.cc.
{
    ObjectState* state = new ObjectState(OSNAME_UNIT_IMPLEMENTATION);
    state->setAttribute(OSKEY_HDB_FILE, hdbFile_);
    state->setAttribute(OSKEY_ID, id());
    state->setAttribute(OSKEY_UNIT_NAME, unitName());
    return state;
}
References hdbFile_, OSKEY_HDB_FILE, OSKEY_ID, OSKEY_UNIT_NAME, OSNAME_UNIT_IMPLEMENTATION, ObjectState::setAttribute(), and unitName().
Referenced by IDF::MachineImplementation::saveState(), ComponentImplementationSelector::selectFUs(), ComponentImplementationSelector::selectIUs(), and ComponentImplementationSelector::selectRFs().
setHDBFile()
void IDF::UnitImplementationLocation::setHDBFile (std::string file) virtual
Sets the absolute path to the HDB file.
Parameters
file Absolute path to the HDB file.
Definition at line 201 of file UnitImplementationLocation.cc.
{
    hdbFile_ = file;
}
References hdbFile_.
Referenced by ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), IDF::MachineImplementation::checkImplFiles(), BlockImplementationDialog::doOK(), and IDF::MachineImplementation::makeHDBPathRelative().
setID()
void IDF::UnitImplementationLocation::setID (int id) virtual
Sets the entry ID in HDB.
Definition at line 210 of file UnitImplementationLocation.cc.
{
    id_ = id;
}
References id(), and id_.
Referenced by ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), and BlockImplementationDialog::doOK().
setParent()
void IDF::UnitImplementationLocation::setParent (MachineImplementation & parent) virtual
Sets the parent of the object.
Parameters
parent The parent MachineImplementation instance.
Exceptions
InvalidData If the parent is already set.
Reimplemented in IDF::NullUnitImplementationLocation.
Definition at line 150 of file UnitImplementationLocation.cc.
{
    if (parent_ != NULL) {
        throw InvalidData(__FILE__, __LINE__, __func__);
    }
    parent_ = &parent;
}
References __func__, and parent_.
unitName()
std::string IDF::UnitImplementationLocation::unitName () const virtual
Returns the name of the unit in ADF.
Returns
The name of the unit.
Reimplemented in IDF::NullUnitImplementationLocation.
Definition at line 138 of file UnitImplementationLocation.cc.
{
    return unitName_;
}
References unitName_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addIUToNetlist(), ProGe::NetlistGenerator::addRFToNetlist(), IDFValidator::checkFUImplementations(), IDFValidator::checkIUImplementations(), IDFValidator::checkRFImplementations(), AutoSelectImplementationsDialog::onFind(), IDFValidator::removeUnknownImplementations(), and saveState().
Member Data Documentation
hdbFile_
std::string IDF::UnitImplementationLocation::hdbFile_ private
Name of the HDB file.
Definition at line 81 of file UnitImplementationLocation.hh.
Referenced by hdbFile(), hdbFileOriginal(), loadState(), saveState(), and setHDBFile().
id_
int IDF::UnitImplementationLocation::id_ private
Entry ID in the HDB.
Definition at line 83 of file UnitImplementationLocation.hh.
Referenced by id(), loadState(), and setID().
OSKEY_HDB_FILE
const string IDF::UnitImplementationLocation::OSKEY_HDB_FILE = "hdb_file" static
ObjectState attribute key for the name of the HDB file.
Definition at line 73 of file UnitImplementationLocation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_ID
const string IDF::UnitImplementationLocation::OSKEY_ID = "id" static
ObjectState attribute key for the entry ID.
Definition at line 75 of file UnitImplementationLocation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSKEY_UNIT_NAME
const string IDF::UnitImplementationLocation::OSKEY_UNIT_NAME = "unit_name" static
Objectstate attribute key for the name of the unit.
Definition at line 77 of file UnitImplementationLocation.hh.
Referenced by IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
OSNAME_UNIT_IMPLEMENTATION
const string IDF::UnitImplementationLocation::OSNAME_UNIT_IMPLEMENTATION static
Initial value:
=
    "unit_implementation"
ObjectState name for unit implementation.
Definition at line 71 of file UnitImplementationLocation.hh.
Referenced by IDF::IDFSerializer::convertToOMFormat(), loadState(), and saveState().
parent_
MachineImplementation* IDF::UnitImplementationLocation::parent_ private
The parent MachineImplementation instance.
Definition at line 87 of file UnitImplementationLocation.hh.
Referenced by hdbFile(), and setParent().
unitName_
std::string IDF::UnitImplementationLocation::unitName_ private
Name of the unit in ADF.
Definition at line 85 of file UnitImplementationLocation.hh.
Referenced by loadState(), and unitName().
The documentation for this class was generated from the following files:
UnitImplementationLocation.hh
UnitImplementationLocation.cc