OpenASIP: ProDeBusOrderDialog Class Reference
ProDeBusOrderDialog Class Reference
#include <ProDeBusOrderDialog.hh>
Public Member Functions
ProDeBusOrderDialog (wxWindow *parent, TTAMachine::Machine &machine)
virtual ~ProDeBusOrderDialog ()
Private Types
enum { ID_UP = 10000 , ID_DOWN , ID_LINE , ID_LIST }
Private Member Functions
void onUp (wxCommandEvent &event)
void onDown (wxCommandEvent &event)
void onBusSelectionChanged (wxListEvent &event)
void updateBusList ()
int selectedBus () const
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
TTAMachine::Machine & machine_
Machine containing the buses to sort.
wxListCtrl * list_
List widget for the buses.
Detailed Description
Dialog for modifying order of transport buses in a machine.
Definition at line 48 of file ProDeBusOrderDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_UP
ID_DOWN
ID_LINE
ID_LIST
Definition at line 61 of file ProDeBusOrderDialog.hh.
         {
        ID_UP = 10000,
        ID_DOWN,
        ID_LINE,
        ID_LIST
    };
Constructor & Destructor Documentation
ProDeBusOrderDialog()
ProDeBusOrderDialog::ProDeBusOrderDialog (wxWindow * parent, TTAMachine::Machine & machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Machine containing the buses to order.
Definition at line 53 of file ProDeBusOrderDialog.cc.
                                                  :
    wxDialog(parent, -1, _T("Transport Bus Order"), wxDefaultPosition),
    machine_(machine) {
    createContents(this, true, true);
    list_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    list_->InsertColumn(0, _T("index"), wxLIST_FORMAT_LEFT, 50);
    list_->InsertColumn(1, _T("bus"), wxLIST_FORMAT_LEFT, 180);
    // Disable conditional buttons.
    FindWindow(ID_UP)->Disable();
    FindWindow(ID_DOWN)->Disable();
    updateBusList();
}
~ProDeBusOrderDialog()
ProDeBusOrderDialog::~ProDeBusOrderDialog () virtual
The Destructor.
Definition at line 75 of file ProDeBusOrderDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ProDeBusOrderDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Definition at line 192 of file ProDeBusOrderDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxListCtrl *item2 = new wxListCtrl( parent, ID_LIST, wxDefaultPosition, wxSize(250,300), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item3 = new wxBoxSizer( wxVERTICAL );
    wxButton *item4 = new wxButton( parent, ID_UP, wxT("&Up"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item5 = new wxButton( parent, ID_DOWN, wxT("&Down"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item3, 0, wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item6 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item6, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item8 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item7, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DOWN, ID_LINE, ID_LIST, and ID_UP.
onBusSelectionChanged()
void ProDeBusOrderDialog::onBusSelectionChanged (wxListEvent & event) private
Enables and disables Up/Down buttons according to bus selection.
Definition at line 149 of file ProDeBusOrderDialog.cc.
{
    const TTAMachine::Machine::BusNavigator& navigator =
        machine_.busNavigator();
    int selection = selectedBus();
    if (selection < 0) {
        FindWindow(ID_UP)->Disable();
        FindWindow(ID_DOWN)->Disable();
        return;
    }
    if (selection > 0) {
        FindWindow(ID_UP)->Enable();
    } else {
        FindWindow(ID_UP)->Disable();
    }
    if (selection < (navigator.count() - 1)) {
        FindWindow(ID_DOWN)->Enable();
    } else {
        FindWindow(ID_DOWN)->Disable();
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), ID_DOWN, ID_UP, machine_, and selectedBus().
onDown()
void ProDeBusOrderDialog::onDown (wxCommandEvent & event) private
Moves the selected bus one position down (increases the index by one).
Definition at line 124 of file ProDeBusOrderDialog.cc.
{
    const TTAMachine::Machine::BusNavigator& navigator =
        machine_.busNavigator();
    int position = selectedBus();
    if (position >= (navigator.count() - 1)) {
        return;
    }
    machine_.setBusPosition(*navigator.item(position), position + 1);
    updateBusList();
    // Reselect the moved bus.
    list_->SetItemState(
        position + 1, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
    list_->EnsureVisible(position + 1);
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), list_, machine_, selectedBus(), TTAMachine::Machine::setBusPosition(), and updateBusList().
onUp()
void ProDeBusOrderDialog::onUp (wxCommandEvent & event) private
Moves the selected bus one position up (decreases the index by one).
Definition at line 99 of file ProDeBusOrderDialog.cc.
{
    const TTAMachine::Machine::BusNavigator& navigator =
        machine_.busNavigator();
    int position = selectedBus();
    if (position <= 0) {
        return;
    }
    machine_.setBusPosition(*navigator.item(position), position - 1);
    updateBusList();
    // Reselect the moved bus.
    list_->SetItemState(
        position - 1, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
    list_->EnsureVisible(position - 1);
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), list_, machine_, selectedBus(), TTAMachine::Machine::setBusPosition(), and updateBusList().
selectedBus()
int ProDeBusOrderDialog::selectedBus () const private
Returns index of the selected bus, or -1 if no bs is selected.
Returns
Index of bus selected in the bus list.
Definition at line 181 of file ProDeBusOrderDialog.cc.
{
    int item = -1;
    item = list_->GetNextItem(item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    return item;
}
References list_.
Referenced by onBusSelectionChanged(), onDown(), and onUp().
updateBusList()
void ProDeBusOrderDialog::updateBusList () private
Updates the bus list order.
Definition at line 83 of file ProDeBusOrderDialog.cc.
{
    list_->DeleteAllItems();
    const TTAMachine::Machine::BusNavigator& navigator =
        machine_.busNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        std::string busName = navigator.item(i)->name();
        list_->InsertItem(i, WxConversion::toWxString(i));
        list_->SetItem(i, 1, WxConversion::toWxString(busName));
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), list_, machine_, and WxConversion::toWxString().
Referenced by onDown(), and onUp().
Member Data Documentation
list_
wxListCtrl* ProDeBusOrderDialog::list_ private
List widget for the buses.
Definition at line 71 of file ProDeBusOrderDialog.hh.
Referenced by onDown(), onUp(), selectedBus(), and updateBusList().
machine_
TTAMachine::Machine& ProDeBusOrderDialog::machine_ private
Machine containing the buses to sort.
Definition at line 69 of file ProDeBusOrderDialog.hh.
Referenced by onBusSelectionChanged(), onDown(), onUp(), and updateBusList().
The documentation for this class was generated from the following files:
ProDeBusOrderDialog.hh
ProDeBusOrderDialog.cc