OpenASIP: IPXactAddressSpace Class Reference
IPXactAddressSpace Class Reference
#include <IPXactAddressSpace.hh>
Public Member Functions
IPXactAddressSpace (const TCEString &name, int range, int memLocationWidth, int mauWidth)
IPXactAddressSpace (const MemInfo &memory)
TCEString name () const
int memRange () const
int memLocationWidth () const
int mauWidth () const
Private Member Functions
IPXactAddressSpace ()
Private Attributes
TCEString name_
int range_
int memLocationWidth_
int mauWidth_
Detailed Description
Definition at line 38 of file IPXactAddressSpace.hh.
Constructor & Destructor Documentation
IPXactAddressSpace() [1/3]
IPXactAddressSpace::IPXactAddressSpace (const TCEString & name, int range, int memLocationWidth, int mauWidth)
Definition at line 34 of file IPXactAddressSpace.cc.
                 :
    name_(name), range_(range), memLocationWidth_(memLocationWidth),
    mauWidth_(mauWidth) {
}
IPXactAddressSpace() [2/3]
IPXactAddressSpace::IPXactAddressSpace (const MemInfo & memory)
Definition at line 43 of file IPXactAddressSpace.cc.
                                                           :
    name_(memory.asName), range_(1 << memory.asAddrw),
    memLocationWidth_(memory.mauWidth*memory.widthInMaus),
    mauWidth_(memory.mauWidth) {
}
IPXactAddressSpace() [3/3]
IPXactAddressSpace::IPXactAddressSpace () private
Member Function Documentation
mauWidth()
int IPXactAddressSpace::mauWidth () const
Definition at line 69 of file IPXactAddressSpace.cc.
{
    return mauWidth_;
}
References mauWidth_.
Referenced by IPXactModel::addAddressSpaceObject().
memLocationWidth()
int IPXactAddressSpace::memLocationWidth () const
Definition at line 63 of file IPXactAddressSpace.cc.
{
    return memLocationWidth_;
}
References memLocationWidth_.
Referenced by IPXactModel::addAddressSpaceObject().
memRange()
int IPXactAddressSpace::memRange () const
Definition at line 57 of file IPXactAddressSpace.cc.
{
    return range_;
}
References range_.
Referenced by IPXactModel::addAddressSpaceObject().
name()
TCEString IPXactAddressSpace::name () const
Definition at line 51 of file IPXactAddressSpace.cc.
{
    return name_;
}
References name_.
Referenced by IPXactModel::addAddressSpaceObject().
Member Data Documentation
mauWidth_
int IPXactAddressSpace::mauWidth_ private
Definition at line 67 of file IPXactAddressSpace.hh.
Referenced by mauWidth().
memLocationWidth_
int IPXactAddressSpace::memLocationWidth_ private
Definition at line 66 of file IPXactAddressSpace.hh.
Referenced by memLocationWidth().
name_
TCEString IPXactAddressSpace::name_ private
Definition at line 64 of file IPXactAddressSpace.hh.
Referenced by name().
range_
int IPXactAddressSpace::range_ private
Definition at line 65 of file IPXactAddressSpace.hh.
Referenced by memRange().
The documentation for this class was generated from the following files:
IPXactAddressSpace.hh
IPXactAddressSpace.cc