OpenASIP: SimulatorInterpreter Class Reference
SimulatorInterpreter Class Reference
#include <SimulatorInterpreter.hh>
Public Member Functions
SimulatorInterpreter (int argc, char *argv[], SimulatorInterpreterContext &context, LineReader &reader)
virtual ~SimulatorInterpreter ()
bool isQuitCommandGiven () const
void setQuitCommandGiven ()
Public Member Functions inherited from TclInterpreter
TclInterpreter ()
virtual ~TclInterpreter ()
virtual void initialize (int argc, char *argv[], InterpreterContext *context, LineReader *reader)
virtual void setVariableToInterpreter (const std::string &name, const DataObject &value)
virtual DataObject variable (const std::string &name)
virtual bool interpret (const std::string &commandLine)
virtual void setResultToInterpreter (const DataObject &value)
virtual bool processScriptFile (const std::string &scriptFileName)
virtual InterpreterContext & context () const
Public Member Functions inherited from ScriptInterpreter
ScriptInterpreter ()
virtual ~ScriptInterpreter ()
virtual void addCustomCommand (CustomCommand *command)
virtual void removeCustomCommand (const std::string &commandName)
virtual CustomCommand * customCommand (const std::string &commandName)
virtual void setResult (DataObject *result)
virtual void setResult (const std::string &result)
virtual void setResult (int result)
virtual void setResult (double result)
virtual std::string result ()
virtual void setError (bool state)
virtual void setError (std::string errorMessage)
virtual bool error () const
virtual void setVariable (const std::string &interpreterVariableName, const std::string &value)
virtual void setVariable (const std::string &interpreterVariableName, int value)
virtual std::string variableStringValue (const std::string &interpreterVariableName)
virtual int variableIntegerValue (const std::string &interpreterVariableName)
virtual void finalize ()
virtual void setLineReader (LineReader *reader)
virtual LineReader * lineReader () const
std::vector< std::string > customCommandsSortedByName ()
Private Attributes
bool quitted_
Additional Inherited Members
Static Public Member Functions inherited from TclInterpreter
static DataObject tclObjToDataObject (Tcl_Obj *object)
static Tcl_Obj * dataObjectToTclObj (const DataObject &object)
static int customCommandRedirector (ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
Protected Member Functions inherited from TclInterpreter
virtual void addCustomCommandToInterpreter (const CustomCommand &command)
virtual void removeCustomCommandFromInterpreter (const CustomCommand &command)
Detailed Description
Implementation of the interpreter for the Simulator Control Language.
Uses TCL as the base interpreter class and adds the custom commands of the Simulator Control Language to it.
Definition at line 49 of file SimulatorInterpreter.hh.
Constructor & Destructor Documentation
SimulatorInterpreter()
SimulatorInterpreter::SimulatorInterpreter (int argc, char * argv[], SimulatorInterpreterContext & context, LineReader & reader)
Constructor.
Initializes the interpreter. argc and argv variables are set to be visible as interpreter variables.
Parameters
argc The number of command line arguments.
argv The command line arguments.
context The context data for the interpreter.
reader LineReader used by the interpreter.
Definition at line 76 of file SimulatorInterpreter.cc.
                        : TclInterpreter(), quitted_(false) {
    initialize(argc, argv, &context, &reader);
    addCustomCommand(new HelpCommand());
    addCustomCommand(new ProgCommand());
    addCustomCommand(new MachCommand());
    addCustomCommand(new ConfCommand());
    addCustomCommand(new QuitCommand("quit"));
    addCustomCommand(new QuitCommand("exit"));
    addCustomCommand(new RunCommand());
    addCustomCommand(new StepiCommand());
    addCustomCommand(new DisassembleCommand());
    addCustomCommand(new UntilCommand());
    addCustomCommand(new SettingCommand());
    addCustomCommand(new ResumeCommand());
    addCustomCommand(new InfoCommand(
        context.simulatorFrontend().isCompiledSimulation()));
    addCustomCommand(new BPCommand());
    addCustomCommand(new TBPCommand());
    addCustomCommand(new ConditionCommand());
    addCustomCommand(new IgnoreCommand());
    addCustomCommand(new DeleteBPCommand());
    addCustomCommand(new EnableBPCommand());
    addCustomCommand(new DisableBPCommand());
    addCustomCommand(new NextiCommand());
    addCustomCommand(new KillCommand());
    addCustomCommand(new MemDumpCommand());
    addCustomCommand(new MemWriteCommand());
    addCustomCommand(new WatchCommand());
    addCustomCommand(new CommandsCommand());
    addCustomCommand(new SymbolAddressCommand());
    addCustomCommand(new BackTraceCommand());
    context.simulatorFrontend().setOutputStream(lineReader()->outputStream());
}
References ScriptInterpreter::addCustomCommand(), TclInterpreter::context(), TclInterpreter::initialize(), and ScriptInterpreter::lineReader().
~SimulatorInterpreter()
SimulatorInterpreter::~SimulatorInterpreter () virtual
Destructor.
Finalizes the internal structures of the interpreter.
Definition at line 123 of file SimulatorInterpreter.cc.
{
    finalize();
}
References ScriptInterpreter::finalize().
Member Function Documentation
isQuitCommandGiven()
bool SimulatorInterpreter::isQuitCommandGiven () const
Returns true in case interpreter has received the quit command.
Parameters
True if quite command has been given.
Definition at line 134 of file SimulatorInterpreter.cc.
{
    return quitted_;
}
References quitted_.
Referenced by SimulatorCLI::run(), and DesignSpaceExplorer::simulate().
setQuitCommandGiven()
void SimulatorInterpreter::setQuitCommandGiven ()
Sets the quit command to be given.
Definition at line 142 of file SimulatorInterpreter.cc.
{
    quitted_ = true;
}
References quitted_.
Member Data Documentation
quitted_
bool SimulatorInterpreter::quitted_ private
Definition at line 62 of file SimulatorInterpreter.hh.
Referenced by isQuitCommandGiven(), and setQuitCommandGiven().
The documentation for this class was generated from the following files:
SimulatorInterpreter.hh
SimulatorInterpreter.cc