OpenASIP: MoveNodeUse Class Reference
MoveNodeUse Class Reference
#include <MoveNodeUse.hh>
Public Types
enum BBRelation { INTRA_BB = 0 , INTER_BB = 1 , LOOP = 3 }
Public Member Functions
MoveNodeUse ()
MoveNodeUse (const MoveNode &mn, bool guard=false, bool ra=false, bool pseudo=false, BBRelation bbRelation=INTRA_BB)
MoveNodeUse (const MoveNodeUse &mnu, BBRelation newBBRelation)
bool operator< (const MoveNodeUse &other) const
const MoveNode * mn () const
bool guard () const
bool ra () const
bool pseudo () const
bool loop () const
bool interBB () const
BBRelation bbRelation () const
Private Attributes
const MoveNode * mn_
bool guard_
bool ra_
bool pseudo_
BBRelation bbRelation_
Detailed Description
Definition at line 20 of file MoveNodeUse.hh.
Member Enumeration Documentation
BBRelation
enum MoveNodeUse::BBRelation
Enumerator
INTRA_BB
INTER_BB
LOOP
Definition at line 23 of file MoveNodeUse.hh.
                    {
        INTRA_BB = 0,
        INTER_BB = 1,
        LOOP = 3
    };
Constructor & Destructor Documentation
MoveNodeUse() [1/3]
MoveNodeUse::MoveNodeUse () inline
Definition at line 29 of file MoveNodeUse.hh.
: mn_(NULL) {} //because STL sucks. always = after this.
MoveNodeUse() [2/3]
MoveNodeUse::MoveNodeUse (const MoveNode & mn, bool guard = false, bool ra = false, bool pseudo = false, BBRelation bbRelation = INTRA_BB) inline
Definition at line 30 of file MoveNodeUse.hh.
                                                               :
        mn_(&mn), guard_(guard), ra_(ra), pseudo_(pseudo), bbRelation_(bbRelation) {}
MoveNodeUse() [3/3]
MoveNodeUse::MoveNodeUse (const MoveNodeUse & mnu, BBRelation newBBRelation) inline
Member Function Documentation
bbRelation()
BBRelation MoveNodeUse::bbRelation () const inline
Definition at line 45 of file MoveNodeUse.hh.
{ return bbRelation_; }
References bbRelation_.
Referenced by DataDependenceGraphBuilder::checkAndCreateMemDep().
guard()
bool MoveNodeUse::guard () const inline
Definition at line 40 of file MoveNodeUse.hh.
{ return guard_; }
References guard_.
Referenced by DataDependenceGraphBuilder::earlierWritesWithSameGuard(), DataDependenceGraphBuilder::hasEarlierWriteWithSameGuard(), DataDependenceGraphBuilder::processRegUse(), DataDependenceGraph::updateRegUse(), and DataDependenceGraph::updateRegWrite().
interBB()
bool MoveNodeUse::interBB () const inline
Definition at line 44 of file MoveNodeUse.hh.
{ return bbRelation_ > INTRA_BB; }
References bbRelation_, and INTRA_BB.
loop()
bool MoveNodeUse::loop () const inline
Definition at line 43 of file MoveNodeUse.hh.
{ return bbRelation_ == LOOP; }
References bbRelation_, and LOOP.
Referenced by LiveRangeData::appendMoveNodeUse(), DataDependenceGraphBuilder::checkAndCreateMemDep(), DataDependenceGraph::updateRegUse(), and DataDependenceGraph::updateRegWrite().
mn()
const MoveNode * MoveNodeUse::mn () const inline
Definition at line 39 of file MoveNodeUse.hh.
{ return mn_; }
References mn_.
Referenced by DataDependenceGraphBuilder::checkAndCreateMemAntideps(), DataDependenceGraphBuilder::checkAndCreateMemDep(), DataDependenceGraphBuilder::createRegisterAntideps(), DataDependenceGraphBuilder::earlierWritesWithSameGuard(), DataDependenceGraphBuilder::hasEarlierMemWriteToSameAddressWithSameGuard(), DataDependenceGraphBuilder::hasEarlierWriteWithSameGuard(), DataDependenceGraph::hasRegWaw(), DataDependenceGraphBuilder::memoryCategory(), DataDependenceGraphBuilder::processMemWrite(), DataDependenceGraphBuilder::processRegUse(), DataDependenceGraphBuilder::processRegWrite(), RegisterRenamer::updateAntiEdgesFromLRTo(), DataDependenceGraph::updateRegUse(), and DataDependenceGraph::updateRegWrite().
operator<()
bool MoveNodeUse::operator< (const MoveNodeUse & other) const inline
pseudo()
bool MoveNodeUse::pseudo () const inline
Definition at line 42 of file MoveNodeUse.hh.
{ return pseudo_; }
References pseudo_.
Referenced by DataDependenceGraphBuilder::checkAndCreateMemDep(), DataDependenceGraphBuilder::createRegisterAntideps(), DataDependenceGraphBuilder::processRegUse(), RegisterRenamer::updateAntiEdgesFromLRTo(), DataDependenceGraph::updateRegUse(), and DataDependenceGraph::updateRegWrite().
ra()
bool MoveNodeUse::ra () const inline
Definition at line 41 of file MoveNodeUse.hh.
{ return ra_; }
References ra_.
Referenced by DataDependenceGraphBuilder::createRegisterAntideps(), DataDependenceGraphBuilder::processRegUse(), DataDependenceGraph::updateRegUse(), and DataDependenceGraph::updateRegWrite().
Member Data Documentation
bbRelation_
BBRelation MoveNodeUse::bbRelation_ private
Definition at line 51 of file MoveNodeUse.hh.
Referenced by bbRelation(), interBB(), and loop().
guard_
bool MoveNodeUse::guard_ private
Definition at line 48 of file MoveNodeUse.hh.
Referenced by guard().
mn_
const MoveNode* MoveNodeUse::mn_ private
Definition at line 47 of file MoveNodeUse.hh.
Referenced by mn().
pseudo_
bool MoveNodeUse::pseudo_ private
Definition at line 50 of file MoveNodeUse.hh.
Referenced by pseudo().
ra_
bool MoveNodeUse::ra_ private
Definition at line 49 of file MoveNodeUse.hh.
Referenced by ra().
The documentation for this class was generated from the following file:
MoveNodeUse.hh