OpenASIP: Bin2nProgramImageWriter Class Reference
Bin2nProgramImageWriter Class Reference
#include <Bin2nProgramImageWriter.hh>
Public Member Functions
Bin2nProgramImageWriter (const InstructionBitVector &bits)
virtual ~Bin2nProgramImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from Bin2nImageWriter
Bin2nImageWriter (const BitVector &bits, int rowLength)
virtual ~Bin2nImageWriter ()
const BitVector & bits () const
void writeSequence (std::ostream &stream, unsigned int length) const
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Detailed Description
Writes the program image as binary 1's and 0's to the stream. Pads from the left to the nearest multiple of 2 and reverses the byte endianness. Used for programming FPGA with Jupyter through AlmaIF
Definition at line 45 of file Bin2nProgramImageWriter.hh.
Constructor & Destructor Documentation
Bin2nProgramImageWriter()
Bin2nProgramImageWriter::Bin2nProgramImageWriter (const InstructionBitVector & bits)
The constructor.
Parameters
bits The program bits to be written.
Definition at line 44 of file Bin2nProgramImageWriter.cc.
                                                                                 :
    Bin2nImageWriter(bits, 0) {
}
~Bin2nProgramImageWriter()
Bin2nProgramImageWriter::~Bin2nProgramImageWriter () virtual
The destructor.
Definition at line 51 of file Bin2nProgramImageWriter.cc.
{
}
Member Function Documentation
writeImage()
void Bin2nProgramImageWriter::writeImage (std::ostream & stream) const virtual
Writes the program image to the given output stream.
Parameters
stream The output stream.
Reimplemented from Bin2nImageWriter.
Definition at line 60 of file Bin2nProgramImageWriter.cc.
{
    const BitVector& bits = this->bits();
    const InstructionBitVector* programBits =
        dynamic_cast<const InstructionBitVector*>(&bits);
    unsigned int previousBoundary(0);
    // Loop through all insctruction boundaries (missing last instruction)
    for (unsigned int i = 1; i < programBits->instructionCount(); i++) {
        unsigned int instructionBoundary =
        programBits->instructionStartingPoint(i);
        writeSequence(stream, instructionBoundary - previousBoundary);
        previousBoundary = instructionBoundary;
    }
    // Write last instruction from remaining bits
    writeSequence(stream, bits.size() - previousBoundary);
}
References Bin2nImageWriter::bits(), InstructionBitVector::instructionCount(), InstructionBitVector::instructionStartingPoint(), and Bin2nImageWriter::writeSequence().
The documentation for this class was generated from the following files:
Bin2nProgramImageWriter.hh
Bin2nProgramImageWriter.cc