OpenASIP: HexImageWriter Class Reference
HexImageWriter Class Reference
#include <HexImageWriter.hh>
Public Member Functions
HexImageWriter (const BitVector &bits, int rowLength)
virtual ~HexImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from AsciiImageWriter
AsciiImageWriter (const BitVector &bits, int rowLength)
virtual ~AsciiImageWriter ()
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Additional Inherited Members
Protected Member Functions inherited from AsciiImageWriter
const BitVector & bits () const
int rowLength () const
void writeSequence (std::ostream &stream, int length, bool padEnd=false) const
void writeHexSequence (std::ostream &stream, int length, bool padEnd=false) const
Detailed Description
Writes the bit image in HEX format. It's used for both ASIC and FPGA memory models
Definition at line 46 of file HexImageWriter.hh.
Constructor & Destructor Documentation
HexImageWriter()
HexImageWriter::HexImageWriter (const BitVector & bits, int rowLength)
The constructor.
Parameters
bits The bits to write.
rowLength Length of the rows to write.
Definition at line 51 of file HexImageWriter.cc.
                                                                   :
    AsciiImageWriter(bits, rowLength) {
}
~HexImageWriter()
HexImageWriter::~HexImageWriter () virtual
The destructor.
Definition at line 58 of file HexImageWriter.cc.
{
}
Member Function Documentation
writeImage()
void HexImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given stream.
Parameters
stream The stream to write.
Reimplemented from AsciiImageWriter.
Definition at line 68 of file HexImageWriter.cc.
{
    const int lineCount =  static_cast<int>(
        ceil(static_cast<double>(bits().size()) / rowLength()));
    const int nibbleCount = static_cast<int>(
        ceil(static_cast<double>(rowLength() / 4)));
    if (lineCount == 0) {
        stream << std::hex << std::setfill('0')
               << std::setw(nibbleCount) << 0 << std::endl;
    } else {
        bool padEndings = false;
        for (int i = 0; i < lineCount; ++i) {
            writeHexSequence(stream, rowLength(), padEndings);
            stream << endl;
        }
    }
}
References AsciiImageWriter::bits(), AsciiImageWriter::rowLength(), and AsciiImageWriter::writeHexSequence().
The documentation for this class was generated from the following files:
HexImageWriter.hh
HexImageWriter.cc