OpenASIP: IUPortCode Class Reference
IUPortCode Class Reference
#include <IUPortCode.hh>
Public Member Functions
IUPortCode (const std::string &immediateUnit, unsigned int encoding, unsigned int extraBits, int indexWidth, SocketCodeTable &parent)
IUPortCode (const std::string &immediateUnit, int indexWidth, SocketCodeTable &parent)
IUPortCode (const ObjectState *state, SocketCodeTable &parent)
virtual ~IUPortCode ()
virtual ObjectState * saveState () const
Public Member Functions inherited from PortCode
virtual ~PortCode ()
std::string unitName () const
bool hasEncoding () const
unsigned int encoding () const
unsigned int extraBits () const
int width () const
int encodingWidth () const
int indexWidth () const
void setMaxIndex (unsigned regIndex)
bool isMaxIndexSet () const
unsigned maxIndex () const
SocketCodeTable * parent () const
Static Public Attributes
static const std::string OSNAME_IU_PORT_CODE = "iu_port_code"
ObjectState name for RF port code.
Static Public Attributes inherited from PortCode
static const std::string OSNAME_PORT_CODE = "port_code"
ObjectState name for PortCode.
static const std::string OSKEY_UNIT_NAME = "unit_name"
ObjectState attribute key for the name of the unit.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_INDEX_WIDTH = "index_width"
ObjectState attribute key for the widht of register index.
static const std::string OSKEY_MAX_INDEX = "max-index"
ObjectState attribute key for the max-index attribute.
Additional Inherited Members
Protected Member Functions inherited from PortCode
PortCode (const std::string &unitName, unsigned int encoding, unsigned int extraBits, int indexWidth)
PortCode (const std::string &unitName, int indexWidth)
PortCode (const ObjectState *state)
void setParent (SocketCodeTable *parent)
Detailed Description
IUPortCode defined a binary encoding for an immediate unit port.
Definition at line 41 of file IUPortCode.hh.
Constructor & Destructor Documentation
IUPortCode() [1/3]
IUPortCode::IUPortCode (const std::string & immediateUnit, unsigned int encoding, unsigned int extraBits, int indexWidth, SocketCodeTable & parent)
The constructor.
Registers the created instance to the given socket code table automatically.
Parameters
immediateUnit Name of the immediate unit.
encoding The encoding for the register file port.
extraBits The number of extra zero bits in the encoding.
indexWidth The number of bits reserved for the register index.
parent The parent socket code table.
Exceptions
ObjectAlreadyExists If the socket code table has an encoding defined for the same port already, or if the encoding is ambiguous with another encoding in the same socket code table.
OutOfRange If some of the given values is out of range.
Definition at line 60 of file IUPortCode.cc.
    : PortCode(immediateUnit, encoding, extraBits, indexWidth) {
    setParent(NULL);
    parent.addIUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addIUPortCode(), PortCode::parent(), and PortCode::setParent().
IUPortCode() [2/3]
IUPortCode::IUPortCode (const std::string & immediateUnit, int indexWidth, SocketCodeTable & parent)
The constructor.
Creates an IU port code without port encoding. That is, the port code consists of mere register index. This is useful if the parent socket code table does not contain other port codes. Registers the created instance to the given socket code table automatically.
Parameters
immediateUnit Name of the immediate unit.
indexWidth The number of bits reserved for the register index.
parent The parent socket code table.
Exceptions
ObjectAlreadyExists If the socket code table has an encoding defined for the same port already, or if the encoding is ambiguous with another encoding in the same socket code table.
OutOfRange If some of the given values is out of range.
Definition at line 86 of file IUPortCode.cc.
    : PortCode(immediateUnit, indexWidth) {
    setParent(NULL);
    parent.addIUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addIUPortCode(), PortCode::parent(), and PortCode::setParent().
IUPortCode() [3/3]
IUPortCode::IUPortCode (const ObjectState * state, SocketCodeTable & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the socket code table has an encoding defined for the same port already, or if the encoding is ambiguous with another encoding in the same socket code table.
Definition at line 108 of file IUPortCode.cc.
    : PortCode(state) {
    if (state->name() != OSNAME_IU_PORT_CODE) {
    const string procName = "IUPortCode::IUPortCode";
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    setParent(NULL);
    parent.addIUPortCode(*this);
    setParent(&parent);
}
References SocketCodeTable::addIUPortCode(), ObjectState::name(), OSNAME_IU_PORT_CODE, PortCode::parent(), and PortCode::setParent().
~IUPortCode()
IUPortCode::~IUPortCode () virtual
The destructor.
Definition at line 123 of file IUPortCode.cc.
{
    SocketCodeTable* parent = this->parent();
    setParent(NULL);
    parent->removeIUPortCode(*this);
}
References PortCode::parent(), SocketCodeTable::removeIUPortCode(), and PortCode::setParent().
Member Function Documentation
saveState()
ObjectState * IUPortCode::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from PortCode.
Definition at line 136 of file IUPortCode.cc.
{
    ObjectState* state = PortCode::saveState();
    state->setName(OSNAME_IU_PORT_CODE);
    return state;
}
References OSNAME_IU_PORT_CODE, PortCode::saveState(), and ObjectState::setName().
Referenced by SocketCodeTable::saveState().
Member Data Documentation
OSNAME_IU_PORT_CODE
const std::string IUPortCode::OSNAME_IU_PORT_CODE = "iu_port_code" static
ObjectState name for RF port code.
Definition at line 55 of file IUPortCode.hh.
Referenced by IUPortCode(), SocketCodeTable::loadState(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
The documentation for this class was generated from the following files:
IUPortCode.hh
IUPortCode.cc