OpenASIP: StopPointManager Class Reference
StopPointManager Class Reference
#include <StopPointManager.hh>
Public Member Functions
StopPointManager (TTASimulationController &controller, SimulationEventHandler &eventHandler)
virtual ~StopPointManager ()
unsigned int add (const StopPoint &stopPoint)
void deleteStopPoint (unsigned int handle)
void deleteAll ()
void enable (unsigned int handle)
void enableAll ()
void enableOnceAndDelete (unsigned int handle)
void enableOnceAndDisable (unsigned int handle)
void disable (unsigned int handle)
void disableAll ()
const StopPoint & stopPointWithHandleConst (unsigned int handle) const
unsigned int stopPointHandle (unsigned int index)
unsigned int stopPointCount ()
void setIgnore (unsigned int handle, unsigned int count)
void setCondition (unsigned int handle, const ConditionScript &condition)
void removeCondition (unsigned int handle)
unsigned int stopCausingStopPoint (unsigned int index) const
unsigned int stopCausingStopPointCount () const
void handleEvent ()
Public Member Functions inherited from Listener
Listener ()
virtual ~Listener ()
virtual void handleEvent (int event)
Private Types
typedef std::map< unsigned int, StopPoint * > StopPointIndex
The breakpoint storage.
typedef std::vector< unsigned int > HandleContainer
The handle storage.
Private Member Functions
StopPoint * findStopPoint (unsigned int handle)
Private Attributes
StopPointIndex stopPoints_
The stop points.
HandleContainer handles_
The stop point handles.
unsigned int handleCount_
Represents the next free handle.
ClockCycleCount lastStopCycle_
The clock cycle in which simulation was stopped last.
TTASimulationController & controller_
The simulation controller to use to stop the simulation.
SimulationEventHandler & eventHandler_
The event handler to use to register stop points to.
Detailed Description
Keeps book of user-set simulation stop points.
Definition at line 50 of file StopPointManager.hh.
Member Typedef Documentation
HandleContainer
typedef std::vector<unsigned int> StopPointManager::HandleContainer private
The handle storage.
Definition at line 88 of file StopPointManager.hh.
StopPointIndex
typedef std::map<unsigned int, StopPoint*> StopPointManager::StopPointIndex private
The breakpoint storage.
Definition at line 86 of file StopPointManager.hh.
Constructor & Destructor Documentation
StopPointManager()
StopPointManager::StopPointManager (TTASimulationController & controller, SimulationEventHandler & eventHandler)
Constructor.
Parameters
controller The simulation controller the stop points should use to stop the simulation.
Definition at line 56 of file StopPointManager.cc.
                                          :
    handleCount_(0), lastStopCycle_(0), controller_(controller),
    eventHandler_(eventHandler) {
}
~StopPointManager()
StopPointManager::~StopPointManager () virtual
Destructor.
Definition at line 67 of file StopPointManager.cc.
{
    MapTools::deleteAllValues(stopPoints_);
}
References MapTools::deleteAllValues(), and stopPoints_.
Member Function Documentation
add()
unsigned int StopPointManager::add (const StopPoint & stopPoint)
Function that adds a new stop point.
Copies the given stop point.
Parameters
stopPoint The stop point to be added.
Returns
Handle for the added stop point.
Definition at line 81 of file StopPointManager.cc.
{
    StopPoint* toAdd = stopPoint.copy();
    ++handleCount_;
    stopPoints_.insert(make_pair(handleCount_, toAdd));
    handles_.push_back(handleCount_);
    toAdd->setEnabled(true);
    if (stopPoints_.size() == 1) {
        // this is the first added stop point, enable event
        // listening
        eventHandler_.registerListener(
            SimulationEventHandler::SE_NEW_INSTRUCTION, this);
    }
    return handleCount_;
}
References StopPoint::copy(), eventHandler_, handleCount_, handles_, Informer::registerListener(), SimulationEventHandler::SE_NEW_INSTRUCTION, StopPoint::setEnabled(), and stopPoints_.
Referenced by BPCommand::execute(), TBPCommand::execute(), and WatchCommand::execute().
deleteAll()
void StopPointManager::deleteAll ()
Removes all stop points.
Definition at line 136 of file StopPointManager.cc.
{
    while (handles_.size() > 0) {
        deleteStopPoint(handles_.at(0));
    }
}
References deleteStopPoint(), and handles_.
Referenced by DeleteBPCommand::execute().
deleteStopPoint()
void StopPointManager::deleteStopPoint (unsigned int handle)
Remove a stop point by the given handle.
Parameters
handle The handle of the stop point to be removed.
Definition at line 108 of file StopPointManager.cc.
{
    StopPoint* stopPoint = findStopPoint(handle);
    StopPointIndex::iterator findResult = stopPoints_.find(handle);
    stopPoints_.erase(findResult);
    for (HandleContainer::iterator i = handles_.begin(); i != handles_.end();
         i++) {
        if ((*i) == handle) {
            handles_.erase(i);
            break;
        }
    }
    delete stopPoint;
    stopPoint = NULL;
    if (stopPoints_.size() == 0) {
        // this was the last stop point, disable event listening
        eventHandler_.unregisterListener(
            SimulationEventHandler::SE_NEW_INSTRUCTION, this);
    }
}
References eventHandler_, findStopPoint(), handles_, SimulationEventHandler::SE_NEW_INSTRUCTION, stopPoints_, and Informer::unregisterListener().
Referenced by deleteAll(), DeleteBPCommand::execute(), handleEvent(), ProximBreakpointWindow::onDeleteBreakpoint(), and ProximBreakpointWindow::onDeleteWatch().
disable()
void StopPointManager::disable (unsigned int handle)
Disables the stop point by the given handle.
Parameters
handle The handle for the stop point.
Definition at line 200 of file StopPointManager.cc.
{
    findStopPoint(handle)->setEnabled(false);
}
References findStopPoint(), and StopPoint::setEnabled().
Referenced by disableAll(), and DisableBPCommand::execute().
disableAll()
void StopPointManager::disableAll ()
Disables all stop oints.
Definition at line 208 of file StopPointManager.cc.
{
    for (unsigned int i = 0; i < handles_.size(); i++) {
        disable(handles_.at(i));
    }
}
References disable(), and handles_.
enable()
void StopPointManager::enable (unsigned int handle)
Enables the stop point by the given handle.
Parameters
handle The handle to identify the stop point.
Definition at line 149 of file StopPointManager.cc.
{
    findStopPoint(handle)->setEnabled(true);
}
References findStopPoint(), and StopPoint::setEnabled().
Referenced by enableAll(), and EnableBPCommand::execute().
enableAll()
void StopPointManager::enableAll ()
Enables all stop points.
Definition at line 157 of file StopPointManager.cc.
{
    for (unsigned int i = 0; i < handles_.size(); i++) {
        enable(handles_.at(i));
    }
}
References enable(), and handles_.
enableOnceAndDelete()
void StopPointManager::enableOnceAndDelete (unsigned int handle)
Enables the stop point by the given handle and sets it to be deleted after being triggered.
Parameters
handle The handle for the stop point.
Exceptions
InstanceNotFound if the given handle cannot be found.
Definition at line 172 of file StopPointManager.cc.
{
    StopPoint* stopPoint = findStopPoint(handle);
    stopPoint->setEnabled(true);
    stopPoint->setDeletedAfterTriggered(true);
}
References findStopPoint(), StopPoint::setDeletedAfterTriggered(), and StopPoint::setEnabled().
Referenced by EnableBPCommand::execute().
enableOnceAndDisable()
void StopPointManager::enableOnceAndDisable (unsigned int handle)
Enables the stop point by the given handle and sets it to be disabled after being triggered.
Parameters
handle The handle for the stop point.
Exceptions
InstanceNotFound if the given handle cannot be found.
Definition at line 187 of file StopPointManager.cc.
{
    StopPoint* stopPoint = findStopPoint(handle);
    stopPoint->setEnabled(true);
    stopPoint->setDisabledAfterTriggered(true);
}
References findStopPoint(), StopPoint::setDisabledAfterTriggered(), and StopPoint::setEnabled().
Referenced by EnableBPCommand::execute().
findStopPoint()
StopPoint * StopPointManager::findStopPoint (unsigned int handle) private
Tries to find a stop point by the given handle. If no such stop point is found, throws an exception.
Parameters
handle The handle for the stop point.
Exceptions
InstanceNotFound If no stop point with given handle is found.
Todo:
textgenerator, to be displayed in the UI.
Definition at line 320 of file StopPointManager.cc.
{
    StopPointIndex::iterator containerEnd = stopPoints_.end();
    StopPointIndex::iterator findResult = stopPoints_.find(handle);
    if (findResult == containerEnd) {
        /// @todo textgenerator, to be displayed in the UI.
        string msg = "No stop point found by the given handle.";
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    } else {
        return findResult->second;
    }
}
References __func__, and stopPoints_.
Referenced by deleteStopPoint(), disable(), enable(), enableOnceAndDelete(), enableOnceAndDisable(), removeCondition(), setCondition(), and setIgnore().
handleEvent()
void StopPointManager::handleEvent () virtual
Stops simulation if there is at least one stop point requesting it.
Receives SE_NEW_INSTRUCTION events.
Reimplemented from Listener.
Definition at line 388 of file StopPointManager.cc.
{
    // find all the stop points watching the new instruction address
    StopPointIndex::iterator i = stopPoints_.begin();
    HandleContainer toBeDeletedStopPoints;
    while (i != stopPoints_.end()) {
        StopPoint& stopPoint = *(*i).second;
        const int handle = (*i).first;
        if (stopPoint.isEnabled() && stopPoint.isTriggered()) {
            // we found a stop point that is triggered at this clock cycle
            if (stopPoint.ignoreCount() == 0 && stopPoint.isConditionOK()) {
                controller_.prepareToStop(SRE_BREAKPOINT);
                lastStopCycle_ = controller_.clockCount();
                if (stopPoint.isDisabledAfterTriggered()) {
                    stopPoint.setEnabled(false);
                }
                if (stopPoint.isDeletedAfterTriggered()) {
                    toBeDeletedStopPoints.push_back(handle);
                }
            } else if (stopPoint.isConditionOK()) {
                // decrease the ignore count only if the (possible) condition
                // of the breakpoint is also true
                stopPoint.decreaseIgnoreCount();
            }
        }
        ++i;
    }
    // delete stop points that wanted to be deleted after triggered
    for (size_t i = 0; i < toBeDeletedStopPoints.size(); ++i) {
        deleteStopPoint(toBeDeletedStopPoints[i]);
    }
}
References TTASimulationController::clockCount(), controller_, StopPoint::decreaseIgnoreCount(), deleteStopPoint(), StopPoint::ignoreCount(), StopPoint::isConditionOK(), StopPoint::isDeletedAfterTriggered(), StopPoint::isDisabledAfterTriggered(), StopPoint::isEnabled(), StopPoint::isTriggered(), lastStopCycle_, TTASimulationController::prepareToStop(), StopPoint::setEnabled(), SRE_BREAKPOINT, and stopPoints_.
removeCondition()
void StopPointManager::removeCondition (unsigned int handle)
Removes the condition of triggering of the stop point by the given handle.
Parameters
handle The handle for the stop point.
Exceptions
InstanceNotFound If no stop point with given handle is found.
Definition at line 308 of file StopPointManager.cc.
{
    findStopPoint(handle)->removeCondition();
}
References findStopPoint(), and StopPoint::removeCondition().
Referenced by ConditionCommand::execute().
setCondition()
void StopPointManager::setCondition (unsigned int handle, const ConditionScript & condition)
Sets the condition of triggering for the stop point by the given handle.
Parameters
handle The handle for the stop point.
condition The condition to be used to determine if the stop point should be fired.
Exceptions
InstanceNotFound If no stop point with given handle is found.
Definition at line 296 of file StopPointManager.cc.
{
    findStopPoint(handle)->setCondition(condition);
}
References findStopPoint(), and StopPoint::setCondition().
Referenced by ConditionCommand::execute().
setIgnore()
void StopPointManager::setIgnore (unsigned int handle, unsigned int count)
Sets the number of times the stop point by the given handle should not be triggered when the condition is met.
Parameters
handle The handle for the stop point.
count The number of times the stop point should be ignored.
Exceptions
InstanceNotFound If no stop point with given handle is found.
Definition at line 283 of file StopPointManager.cc.
{
    findStopPoint(handle)->setIgnoreCount(count);
}
References findStopPoint(), and StopPoint::setIgnoreCount().
Referenced by IgnoreCommand::execute().
stopCausingStopPoint()
unsigned int StopPointManager::stopCausingStopPoint (unsigned int index) const
Returns the handle of a stop causing stop point with given index in the container of stop causing stop points.
Stop causing stop point is a stop point that caused the latest stop of simulator.
Parameters
index Index of the stop point in the container.
Returns
the handle of the stop point.
Exceptions
OutOfRange
Definition at line 345 of file StopPointManager.cc.
{
    unsigned int count = 0;
    for (StopPointIndex::const_iterator i = stopPoints_.begin();
         i != stopPoints_.end(); ++i) {
        if ((*i).second->isTriggered()) {
            if (count == index)
                return (*i).first;
            ++count;
        }
    }
    throw OutOfRange(
        __FILE__, __LINE__, __func__, "Stop point index out of range.");
}
References __func__, and stopPoints_.
Referenced by SimControlLanguageCommand::printStopReasons().
stopCausingStopPointCount()
unsigned int StopPointManager::stopCausingStopPointCount () const
Returns the count of stop causing stop points.
Stop causing stop point is a stop point that caused the latest stop of simulator.
Returns
the count of stop points.
Definition at line 368 of file StopPointManager.cc.
{
    if (lastStopCycle_ != controller_.clockCount()) {
        return 0;
    }
    std::size_t count = 0;
    for (StopPointIndex::const_iterator i = stopPoints_.begin();
         i != stopPoints_.end(); ++i) {
        if ((*i).second->isTriggered())
            ++count;
    }
    return count;
}
References TTASimulationController::clockCount(), controller_, lastStopCycle_, and stopPoints_.
Referenced by SimControlLanguageCommand::printStopReasons().
stopPointCount()
unsigned int StopPointManager::stopPointCount ()
Returns the current number of stop points in the manager.
Can be used to access all stop points in the manager.
Returns
The number of stop points in the manager.
Definition at line 269 of file StopPointManager.cc.
{
    return handles_.size();
}
References handles_.
Referenced by InfoBreakpointsCommand::execute(), ProximDisassemblyGridTable::GetValue(), ProximDisassemblyWindow::onRightClick(), ProximBreakpointWindow::refreshStopPoints(), and stopPointHandle().
stopPointHandle()
unsigned int StopPointManager::stopPointHandle (unsigned int index)
Returns the handle of the stop point by the given index.
The index is not a direct index to the container used to store stop points, but more just a way to go through all of the stop points in the manager. A stop point may not have the same index every call.
All of the stop points can be accessed by going through the stop points with the indices between 0 and stopPointCount - 1, inclusive. The stop points are in no particular order.
Parameters
index The index.
Returns
A Copy of the stop point by the given index.
Exceptions
OutOfRange If there is no stop point by the given index.
Todo:
textgenerator, to be displayed in the UI.
Definition at line 231 of file StopPointManager.cc.
{
    if (index < stopPointCount()) {
        return handles_.at(index);
    } else {
        /// @todo textgenerator, to be displayed in the UI.
        string msg = "No stop point found by the given index.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, handles_, and stopPointCount().
Referenced by InfoBreakpointsCommand::execute(), ProximDisassemblyGridTable::GetValue(), ProximDisassemblyWindow::onRightClick(), and ProximBreakpointWindow::refreshStopPoints().
stopPointWithHandleConst()
const StopPoint & StopPointManager::stopPointWithHandleConst (unsigned int handle) const
Returns the stop point with the given handle.
Parameters
handle The handle.
Returns
Stop point with the given handle,
Exceptions
InstanceNotFound If there is no stop point with the given handle.
Todo:
textgenerator, to be displayed in the UI.
Definition at line 248 of file StopPointManager.cc.
{
    StopPointIndex::const_iterator containerEnd = stopPoints_.end();
    StopPointIndex::const_iterator findResult = stopPoints_.find(handle);
    if (findResult == containerEnd) {
        /// @todo textgenerator, to be displayed in the UI.
        std::string msg = "No stop point found by the given handle.";
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    } else {
        return *findResult->second;
    }
}
References __func__, and stopPoints_.
Referenced by ConditionCommand::execute(), IgnoreCommand::execute(), ProximDisassemblyGridTable::GetValue(), ProximBreakpointWindow::onBreakpointLookup(), ProximDisassemblyWindow::onRightClick(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::printStopReasons(), ProximBreakpointWindow::refreshStopPoints(), BreakpointPropertiesDialog::TransferDataToWindow(), WatchPropertiesDialog::TransferDataToWindow(), and SimControlLanguageCommand::verifyBreakpointHandles().
Member Data Documentation
controller_
TTASimulationController& StopPointManager::controller_ private
The simulation controller to use to stop the simulation.
Definition at line 101 of file StopPointManager.hh.
Referenced by handleEvent(), and stopCausingStopPointCount().
eventHandler_
SimulationEventHandler& StopPointManager::eventHandler_ private
The event handler to use to register stop points to.
Definition at line 103 of file StopPointManager.hh.
Referenced by add(), and deleteStopPoint().
handleCount_
unsigned int StopPointManager::handleCount_ private
Represents the next free handle.
Definition at line 97 of file StopPointManager.hh.
Referenced by add().
handles_
HandleContainer StopPointManager::handles_ private
The stop point handles.
Definition at line 95 of file StopPointManager.hh.
Referenced by add(), deleteAll(), deleteStopPoint(), disableAll(), enableAll(), stopPointCount(), and stopPointHandle().
lastStopCycle_
ClockCycleCount StopPointManager::lastStopCycle_ private
The clock cycle in which simulation was stopped last.
Definition at line 99 of file StopPointManager.hh.
Referenced by handleEvent(), and stopCausingStopPointCount().
stopPoints_
StopPointIndex StopPointManager::stopPoints_ private
The stop points.
Definition at line 93 of file StopPointManager.hh.
Referenced by add(), deleteStopPoint(), findStopPoint(), handleEvent(), stopCausingStopPoint(), stopCausingStopPointCount(), stopPointWithHandleConst(), and ~StopPointManager().
The documentation for this class was generated from the following files:
StopPointManager.hh
StopPointManager.cc