OpenASIP: UniversalFUPort Class Reference
UniversalFUPort Class Reference
#include <UniversalFUPort.hh>
Public Member Functions
UniversalFUPort (const std::string &name, int width, UniversalFunctionUnit &parent, bool isTriggering, bool setsOpcode)
virtual ~UniversalFUPort ()
virtual void setName (const std::string &name)
virtual void setWidth (int width)
virtual void setTriggering (bool triggers)
virtual void setOpcodeSetting (bool setsOpcode)
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::FUPort
FUPort (const std::string &name, int width, FunctionUnit &parent, bool triggers, bool setsOpcode, bool noRegister=false)
FUPort (const ObjectState *state, Unit &parent)
virtual ~FUPort ()
virtual bool isTriggering () const
virtual bool isOpcodeSetting () const
void setTriggering (bool triggers)
virtual ObjectState * saveState () const
std::string bindingString () const
void updateBindingString () const
bool isArchitectureEqual (FUPort *port)
bool noRegister () const
void setNoRegister (bool noRegister)
Public Member Functions inherited from TTAMachine::BaseFUPort
virtual ~BaseFUPort ()
FunctionUnit * parentUnit () const
virtual int width () const
void setWidth (int width)
Public Member Functions inherited from TTAMachine::Port
Port (const std::string &name, Unit &parentUnit)
Port (const ObjectState *state, Unit &parentUnit)
virtual ~Port ()
virtual std::string name () const
virtual void attachSocket (Socket &socket)
virtual void detachSocket (Socket &socket)
virtual void detachAllSockets ()
Unit * parentUnit () const
virtual Socket * inputSocket () const
virtual Socket * outputSocket () const
virtual Socket * unconnectedSocket (int index) const
virtual int socketCount () const
virtual bool isConnectedTo (const Socket &socket) const
virtual bool isOutput () const
virtual bool isInput () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Additional Inherited Members
Static Public Attributes inherited from TTAMachine::FUPort
static const std::string OSNAME_FUPORT = "fu_port"
ObjectState name for FUPort.
static const std::string OSKEY_TRIGGERING = "triggering"
ObjectState attribute key for triggering feature.
static const std::string OSKEY_OPCODE_SETTING = "oc_setting"
ObjectState attribute key for operand code setting feature.
static const std::string OSKEY_NO_REGISTER = "no_register"
ObjectState attribute key for noRegister setting feature.
Static Public Attributes inherited from TTAMachine::BaseFUPort
static const std::string OSKEY_WIDTH = "width"
ObjectState attribute key for bit width of the port.
Static Public Attributes inherited from TTAMachine::Port
static const std::string OSNAME_PORT = "port"
ObjectState name for Port.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_FIRST_SOCKET = "1_socket"
ObjectState attribute key for the name of the connected socket.
static const std::string OSKEY_SECOND_SOCKET = "2_socket"
ObjectState attribute key for the name of the other connected socket.
Protected Member Functions inherited from TTAMachine::FUPort
FUPort (const std::string &name, int width, FunctionUnit &parent, bool triggers, bool setsOpcode, bool noRegister, bool dummy)
Protected Member Functions inherited from TTAMachine::BaseFUPort
BaseFUPort (const std::string &name, int width, FunctionUnit &parent)
BaseFUPort (const ObjectState *state, Unit &parent)
Protected Member Functions inherited from TTAMachine::Port
Port (const std::string &name, FunctionUnit &parentUnit)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
UniversalFUPort class represents a port of UniversalFunctionUnit. The port is similar to normal FUPort but there can be several operation code setting UniversalFUPorts in UniversalFunctionUnit. UniversalFUPort is a fixed port. Its properties cannot be changes after it is created.
Definition at line 47 of file UniversalFUPort.hh.
Constructor & Destructor Documentation
UniversalFUPort()
UniversalFUPort::UniversalFUPort (const std::string & name, int width, UniversalFunctionUnit & parent, bool isTriggering, bool setsOpcode)
The constructor.
Parameters
name Name of the port.
width Bit width of the port.
parent The function unit to which the port belongs.
isTriggering If true, writing (or reading) this port starts the execution of a new operation.
setsOpcode If true, writing (or reading) this port selects the operation to be executed. Opcode-setting ports must be triggering.
Exceptions
ComponentAlreadyExists If the function unit already has another port by the same name.
OutOfRange If the given bit width is less or equal to zero.
IllegalParameters If setsOpcode argument is true and isTriggering false.
InvalidName If the given name is not a valid component name.
Definition at line 56 of file UniversalFUPort.cc.
    : FUPort(name, width, parent, isTriggering, setsOpcode, true, true) {}
~UniversalFUPort()
UniversalFUPort::~UniversalFUPort () virtual
The destructor.
Definition at line 64 of file UniversalFUPort.cc.
{
}
Member Function Documentation
loadState()
void UniversalFUPort::loadState (const ObjectState * state) virtual
Aborts the program. It is not allowed to load the state of UniversalFUPort from an ObjectState tree. DO NOT CALL THIS METDOD!
Parameters
state Never used.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::FUPort.
Definition at line 139 of file UniversalFUPort.cc.
{
    const string procName = "UniversalFUPort::loadState";
    const string errorMsg =
        "Tried to load state of UniversalFUPort from an ObjectState tree!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
setName()
void UniversalFUPort::setName (const std::string & name) virtual
Aborts the program. It is not allowed to set the name of UniversalFUPort. DO NOT CALL THIS METHOD!
Parameters
name Never used.
Exceptions
ComponentAlreadyExists Never thrown.
InvalidName Never thrown.
Reimplemented from TTAMachine::Port.
Definition at line 77 of file UniversalFUPort.cc.
{
    const string procName = "UniversalFUPort::setName";
    const string errorMsg = "Tried to set the name of UniversalFUPort!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
setOpcodeSetting()
void UniversalFUPort::setOpcodeSetting (bool setsOpcode) virtual
Aborts the program. It is not allowed to set the operation code setting property of UniversalFUPort. DO NOT CALL THIS METHOD!
Parameters
setsOpcode Never used.
Exceptions
ComponentAlreadyExists Never thrown.
Definition at line 123 of file UniversalFUPort.cc.
{
    const string procName = "UniversalFUPort::setOpcodeSetting";
    const string errorMsg = "Tried to set the operation code setting "
        "property of UniversalFUPort!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
setTriggering()
void UniversalFUPort::setTriggering (bool triggers) virtual
Aborts the program. It is not allowed to modify UniversalFUPort. DO NOT CALL THIS METHOD!
Parameters
triggers Never used.
Definition at line 106 of file UniversalFUPort.cc.
{
    const string procName = "UniversalFUPort::setTriggering";
    const string errorMsg =
        "Tried to set the triggering property of UniversalFUPort!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
setWidth()
void UniversalFUPort::setWidth (int width) virtual
Aborts the program. It is not allowed to set the width of UniversalFUPort. DO NOT CALL THIS METHOD!
Parameters
width Never used.
Exceptions
OutOfRange Never thrown.
Definition at line 92 of file UniversalFUPort.cc.
{
    const string procName = "UniversalFUPort::setWidth";
    const string errorMsg = "Tried to set width of UniversalFUPort!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
The documentation for this class was generated from the following files:
UniversalFUPort.hh
UniversalFUPort.cc