OpenASIP: TPEF::FileOffsetReplacer Class Reference
TPEF::FileOffsetReplacer Class Reference
#include <FileOffsetReplacer.hh>
Public Member Functions
FileOffsetReplacer (const SafePointable *obj)
virtual ~FileOffsetReplacer ()
Public Member Functions inherited from TPEF::ValueReplacer
void resolve ()
Protected Member Functions
virtual bool tryToReplace ()
virtual ValueReplacer * clone ()
Protected Member Functions inherited from TPEF::ValueReplacer
ValueReplacer (const SafePointable *obj)
ValueReplacer (const ValueReplacer &replacer)
virtual ~ValueReplacer ()
const SafePointable * reference () const
unsigned int streamPosition () const
Private Member Functions
FileOffsetReplacer (const FileOffsetReplacer &replacer)
FileOffsetReplacer operator= (const FileOffsetReplacer &)
Additional Inherited Members
Static Public Member Functions inherited from TPEF::ValueReplacer
static void finalize ()
static void initialize (BinaryStream &stream)
Static Protected Member Functions inherited from TPEF::ValueReplacer
static BinaryStream & stream ()
Detailed Description
Replaces object reference with file offset. File offset key must be stored in reference manager for that object whose file offset is written.
Definition at line 48 of file FileOffsetReplacer.hh.
Constructor & Destructor Documentation
FileOffsetReplacer() [1/2]
TPEF::FileOffsetReplacer::FileOffsetReplacer (const SafePointable * obj)
Constructor.
Definition at line 46 of file FileOffsetReplacer.cc.
                                                               :
    ValueReplacer(obj) {
}
~FileOffsetReplacer()
TPEF::FileOffsetReplacer::~FileOffsetReplacer () virtual
Destructor.
Definition at line 60 of file FileOffsetReplacer.cc.
{
}
FileOffsetReplacer() [2/2]
TPEF::FileOffsetReplacer::FileOffsetReplacer (const FileOffsetReplacer & replacer) private
Copy constructor.
Definition at line 53 of file FileOffsetReplacer.cc.
                                        : ValueReplacer(replacer) {
}
Member Function Documentation
clone()
ValueReplacer * TPEF::FileOffsetReplacer::clone () protected virtual
Creates dynamically allocated copy of replacer.
Returns
Dynamically allocated copy of replacer.
Implements TPEF::ValueReplacer.
Definition at line 90 of file FileOffsetReplacer.cc.
{
    return new FileOffsetReplacer(*this);
}
operator=()
FileOffsetReplacer TPEF::FileOffsetReplacer::operator= (const FileOffsetReplacer &) private
tryToReplace()
bool TPEF::FileOffsetReplacer::tryToReplace () protected virtual
Tries to do replacement in to the stream.
Returns
True if replacement were done.
Implements TPEF::ValueReplacer.
Definition at line 69 of file FileOffsetReplacer.cc.
{
    try {
        FileOffsetKey key =
            SafePointer::fileOffsetKeyFor(reference());
        stream().setWritePosition(streamPosition());
        stream().writeWord(key.fileOffset());
        return true;
    } catch (KeyNotFound& e) {
        stream().writeWord(0);
        return false;
    }
}
References TPEF::ReferenceManager::FileOffsetKey::fileOffset(), TPEF::ReferenceManager::SafePointer::fileOffsetKeyFor(), TPEF::ValueReplacer::reference(), TPEF::BinaryStream::setWritePosition(), TPEF::ValueReplacer::stream(), TPEF::ValueReplacer::streamPosition(), and TPEF::BinaryStream::writeWord().
The documentation for this class was generated from the following files:
FileOffsetReplacer.hh
FileOffsetReplacer.cc