OpenASIP: BusDialog Class Reference
BusDialog Class Reference
#include <BusDialog.hh>
Public Member Functions
BusDialog (wxWindow *parent, TTAMachine::Bus *bus)
virtual ~BusDialog ()
Private Types
enum {
ID_BUS_NAME = 10000 , ID_BUS_WIDTH , ID_SI_WIDTH , ID_SI_EXTENSION ,
ID_TRUE_GUARD , ID_FALSE_GUARD , ID_SEGMENT_LIST , ID_SEGMENT_NAME ,
ID_SEGMENT_UP , ID_SEGMENT_DOWN , ID_ADD_SEGMENT , ID_DELETE_SEGMENT ,
ID_RF_GUARD_LIST , ID_ADD_RF_GUARD , ID_EDIT_RF_GUARD , ID_DELETE_RF_GUARD ,
ID_FU_GUARD_LIST , ID_ADD_FU_GUARD , ID_EDIT_FU_GUARD , ID_DELETE_FU_GUARD ,
ID_HELP , ID_LABEL_BUS_NAME , ID_LABEL_BUS_WIDTH , ID_LABEL_WIDTH ,
ID_LABEL_SI_WIDTH , ID_LABEL_SEGMENT_NAME
}
enumerated IDs for dialog controls
Private Member Functions
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &)
void onHelp (wxCommandEvent &event)
void onBusName (wxCommandEvent &)
void onAddSegment (wxCommandEvent &)
void onSegmentName (wxCommandEvent &)
void onSegmentSelection (wxListEvent &)
void onSegmentRightClick (wxListEvent &event)
void onDeleteSegment (wxCommandEvent &)
void onSegmentUp (wxCommandEvent &)
void onSegmentDown (wxCommandEvent &)
void setTexts ()
void onRFGuardSelection (wxListEvent &)
void onAddRFGuard (wxCommandEvent &)
void onDeleteRFGuard (wxCommandEvent &)
void onEditRFGuard (wxCommandEvent &)
void onFUGuardSelection (wxListEvent &)
void onAddFUGuard (wxCommandEvent &)
void onDeleteFUGuard (wxCommandEvent &)
void onEditFUGuard (wxCommandEvent &)
void onUnconditionalGuard (wxCommandEvent &)
void onWidth (wxSpinEvent &)
void updateSegmentList ()
void updateGuardLists ()
void onRFGuardRightClick (wxListEvent &event)
void onActivateRFGuard (wxListEvent &event)
void onFUGuardRightClick (wxListEvent &event)
void onActivateFUGuard (wxListEvent &event)
TTAMachine::Segment * selectedSegment () const
TTAMachine::RegisterGuard * selectedRFGuard () const
TTAMachine::PortGuard * selectedFUGuard () const
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
TTAMachine::Bus * bus_
Transport Bus to edit.
wxString name_
Name of the bus.
int width_
Width of the bus.
int immWidth_
Short immediate width.
wxString newSegName_
Name for a new segment.
wxListCtrl * segList_
List widget for the segment list.
wxCheckBox * alwaysTrueGuard_
Check box for always true unconditional guard.
wxCheckBox * alwaysFalseGuard_
Check box for always false unconditional guard.
wxRadioBox * immediateExtensionBox_
Radio box for immediate extension.
wxListCtrl * rfGuardList_
Register file guard list control.
wxListCtrl * fuGuardList_
Function unit port guard list control.
wxStaticBoxSizer * busSizer_
Static boxsizer for the bus properties.
wxStaticBoxSizer * siSizer_
Static boxsizer for the short immediate properties.
wxStaticBoxSizer * registerGuardSizer_
Static boxsizer for the register guard properties.
wxStaticBoxSizer * portGuardSizer_
Static boxsizer for the port guard properties.
wxStaticBoxSizer * segmentSizer_
Static boxsizer for the segment properties.
vector< TTAMachine::RegisterGuard * > registerGuards_
list of register guards
vector< TTAMachine::PortGuard * > portGuards_
list of port guards
Detailed Description
Dialog for querying transport bus parameters from the user.
Definition at line 54 of file BusDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for dialog controls
Enumerator
ID_BUS_NAME
ID_BUS_WIDTH
ID_SI_WIDTH
ID_SI_EXTENSION
ID_TRUE_GUARD
ID_FALSE_GUARD
ID_SEGMENT_LIST
ID_SEGMENT_NAME
ID_SEGMENT_UP
ID_SEGMENT_DOWN
ID_ADD_SEGMENT
ID_DELETE_SEGMENT
ID_RF_GUARD_LIST
ID_ADD_RF_GUARD
ID_EDIT_RF_GUARD
ID_DELETE_RF_GUARD
ID_FU_GUARD_LIST
ID_ADD_FU_GUARD
ID_EDIT_FU_GUARD
ID_DELETE_FU_GUARD
ID_HELP
ID_LABEL_BUS_NAME
ID_LABEL_BUS_WIDTH
ID_LABEL_WIDTH
ID_LABEL_SI_WIDTH
ID_LABEL_SEGMENT_NAME
Definition at line 138 of file BusDialog.hh.
         {
        ID_BUS_NAME = 10000,
        ID_BUS_WIDTH,
        ID_SI_WIDTH,
        ID_SI_EXTENSION,
        ID_TRUE_GUARD,
        ID_FALSE_GUARD,
        ID_SEGMENT_LIST,
        ID_SEGMENT_NAME,
        ID_SEGMENT_UP,
        ID_SEGMENT_DOWN,
        ID_ADD_SEGMENT,
        ID_DELETE_SEGMENT,
        ID_RF_GUARD_LIST,
        ID_ADD_RF_GUARD,
        ID_EDIT_RF_GUARD,
        ID_DELETE_RF_GUARD,
        ID_FU_GUARD_LIST,
        ID_ADD_FU_GUARD,
        ID_EDIT_FU_GUARD,
        ID_DELETE_FU_GUARD,
        ID_HELP,
        ID_LABEL_BUS_NAME,
        ID_LABEL_BUS_WIDTH,
        ID_LABEL_WIDTH,
        ID_LABEL_SI_WIDTH,
        ID_LABEL_SEGMENT_NAME
    };
Constructor & Destructor Documentation
BusDialog()
BusDialog::BusDialog (wxWindow * parent, TTAMachine::Bus * bus)
The Constructor.
Parameters
parent Parent window of the dialog.
bus Transport bus to be modified with the dialog.
Definition at line 122 of file BusDialog.cc.
             :
    wxDialog(parent, -1, _T(""), wxDefaultPosition, wxSize(300, 300)),
    bus_(bus),
    name_(_T("")),
    width_(ModelConstants::DEFAULT_WIDTH),
    immWidth_(ModelConstants::DEFAULT_WIDTH),
    newSegName_(_T("")),
    alwaysTrueGuard_(NULL),
    alwaysFalseGuard_(NULL),
    immediateExtensionBox_(NULL),
    rfGuardList_(NULL),
    fuGuardList_(NULL) {
    createContents(this, true, true);
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_ADD_SEGMENT)->Disable();
    FindWindow(ID_DELETE_SEGMENT)->Disable();
    FindWindow(ID_SEGMENT_UP)->Disable();
    FindWindow(ID_SEGMENT_DOWN)->Disable();
    FindWindow(ID_EDIT_RF_GUARD)->Disable();
    FindWindow(ID_DELETE_RF_GUARD)->Disable();
    FindWindow(ID_EDIT_FU_GUARD)->Disable();
    FindWindow(ID_DELETE_FU_GUARD)->Disable();
    rfGuardList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_RF_GUARD_LIST));
    fuGuardList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_FU_GUARD_LIST));
    segList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_SEGMENT_LIST));
    immediateExtensionBox_ =
        dynamic_cast<wxRadioBox*>(FindWindow(ID_SI_EXTENSION));
    alwaysTrueGuard_ =
        dynamic_cast<wxCheckBox*>(FindWindow(ID_TRUE_GUARD));
    alwaysFalseGuard_ =
        dynamic_cast<wxCheckBox*>(FindWindow(ID_FALSE_GUARD));
    FindWindow(ID_BUS_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_SEGMENT_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &newSegName_));
    FindWindow(ID_BUS_WIDTH)->SetValidator(wxGenericValidator(&width_));
    FindWindow(ID_SI_WIDTH)->SetValidator(wxGenericValidator(&immWidth_));
    // set widget texts
    setTexts();
    TransferDataToWindow();
    FindWindow(ID_BUS_NAME)->SetFocus();
    // Editing segments is unsupported feature => hide segment ui
    segmentSizer_->Show(false);
    GetSizer()->SetSizeHints(this);
}
~BusDialog()
BusDialog::~BusDialog () virtual
The Destructor.
Definition at line 184 of file BusDialog.cc.
                      {
}
Member Function Documentation
createContents()
wxSizer * BusDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner. Don't modify manually, all chnages will be lost if the code is regenerated.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 1178 of file BusDialog.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 2, 0, 0 );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Bus:") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );
    busSizer_ = item2;
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_BUS_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_BUS_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item8 = new wxStaticText( parent, ID_LABEL_BUS_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item9 = new wxSpinCtrl( parent, ID_BUS_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 1024, 1 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item7, 0, wxGROW|wxALL, 5 );
    item0->Add( item2, 0, wxGROW|wxALL, 5 );
    //item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item11 = new wxStaticBox( parent, -1, wxT("Short Immediate:") );
    wxStaticBoxSizer *item10 = new wxStaticBoxSizer( item11, wxVERTICAL );
    siSizer_ = item10;
    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item13 = new wxStaticText( parent, ID_LABEL_SI_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item14 = new wxSpinCtrl( parent, ID_SI_WIDTH, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 1000, 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    item10->Add( item12, 0, wxGROW|wxALL, 5 );
    wxString strs15[] =
    {
        wxT("Zero"),
        wxT("Sign")
    };
    wxRadioBox *item15 = new wxRadioBox( parent, ID_SI_EXTENSION, wxT("Extension"), wxDefaultPosition, wxDefaultSize, 2, strs15, 1, wxRA_SPECIFY_ROWS );
    item10->Add( item15, 0, wxALL, 5 );
    item0->Add( item10, 0, wxGROW|wxALL, 5 );
    //item1->Add( item10, 0, wxGROW|wxALL, 5 );
    wxCheckBox *item16 = new wxCheckBox( parent, ID_TRUE_GUARD, wxT("Always true guard"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item16, 0, wxALL, 5 );
    wxCheckBox *item17 = new wxCheckBox( parent, ID_FALSE_GUARD, wxT("Always false guard"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item17, 0, wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item19 = new wxStaticBox( parent, -1, wxT("Segements:") );
    wxStaticBoxSizer *item18 = new wxStaticBoxSizer( item19, wxVERTICAL );
    segmentSizer_ = item18;
    wxListCtrl *item20 = new wxListCtrl( parent, ID_SEGMENT_LIST, wxDefaultPosition, wxSize(300,160), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item22 = new wxStaticText( parent, ID_LABEL_SEGMENT_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item23 = new wxTextCtrl( parent, ID_SEGMENT_NAME, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item24 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item25 = new wxButton( parent, ID_SEGMENT_UP, wxT("Up"), wxDefaultPosition, wxSize(40,-1), 0 );
    item24->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item26 = new wxButton( parent, ID_SEGMENT_DOWN, wxT("Down"), wxDefaultPosition, wxSize(50,-1), 0 );
    item24->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    item21->Add( item24, 0, wxALL, 5 );
    item18->Add( item21, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item27 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item28 = new wxButton( parent, ID_ADD_SEGMENT, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );
    item27->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item29 = new wxButton( parent, ID_DELETE_SEGMENT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );
    item18->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item18, 0, wxALL, 5 );
    wxStaticBox *item31 = new wxStaticBox( parent, -1, wxT("Register File Guards:") );
    wxStaticBoxSizer *item30 = new wxStaticBoxSizer( item31, wxVERTICAL );
    registerGuardSizer_ = item30;
    wxListCtrl *item32 = new wxListCtrl( parent, ID_RF_GUARD_LIST, wxDefaultPosition, wxSize(300,120), wxLC_REPORT|wxSUNKEN_BORDER );
    item30->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item33 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item34 = new wxButton( parent, ID_ADD_RF_GUARD, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item33->Add( item34, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item35 = new wxButton( parent, ID_EDIT_RF_GUARD, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item35->Enable( false );
    item33->Add( item35, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item36 = new wxButton( parent, ID_DELETE_RF_GUARD, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item36->Enable( false );
    item33->Add( item36, 0, wxALIGN_CENTER|wxALL, 5 );
    item30->Add( item33, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item30, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item38 = new wxStaticBox( parent, -1, wxT("Function Unit Guards") );
    wxStaticBoxSizer *item37 = new wxStaticBoxSizer( item38, wxVERTICAL );
    portGuardSizer_ = item37;
    wxListCtrl *item39 = new wxListCtrl( parent, ID_FU_GUARD_LIST, wxDefaultPosition, wxSize(300,120), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item37->Add( item39, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item40 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item41 = new wxButton( parent, ID_ADD_FU_GUARD, wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item40->Add( item41, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item42 = new wxButton( parent, ID_EDIT_FU_GUARD, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item42->Enable( false );
    item40->Add( item42, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item43 = new wxButton( parent, ID_DELETE_FU_GUARD, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item43->Enable( false );
    item40->Add( item43, 0, wxALIGN_CENTER|wxALL, 5 );
    item37->Add( item40, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item37, 0, wxGROW|wxALL, 5 );
    wxButton *item44 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item44, 0, wxALL, 5 );
    wxBoxSizer *item45 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item46 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item45->Add( item46, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item47 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item45->Add( item47, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item45, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References busSizer_, ID_ADD_FU_GUARD, ID_ADD_RF_GUARD, ID_ADD_SEGMENT, ID_BUS_NAME, ID_BUS_WIDTH, ID_DELETE_FU_GUARD, ID_DELETE_RF_GUARD, ID_DELETE_SEGMENT, ID_EDIT_FU_GUARD, ID_EDIT_RF_GUARD, ID_FALSE_GUARD, ID_FU_GUARD_LIST, ID_HELP, ID_LABEL_BUS_NAME, ID_LABEL_BUS_WIDTH, ID_LABEL_SEGMENT_NAME, ID_LABEL_SI_WIDTH, ID_RF_GUARD_LIST, ID_SEGMENT_DOWN, ID_SEGMENT_LIST, ID_SEGMENT_NAME, ID_SEGMENT_UP, ID_SI_EXTENSION, ID_SI_WIDTH, ID_TRUE_GUARD, portGuardSizer_, registerGuardSizer_, segmentSizer_, and siSizer_.
onActivateFUGuard()
void BusDialog::onActivateFUGuard (wxListEvent & event) private
Handles left mouse button double clicks on the FUGuard list.
Definition at line 1160 of file BusDialog.cc.
{
    wxCommandEvent dummy;
    onEditFUGuard(dummy);
}
References dummy, and onEditFUGuard().
onActivateRFGuard()
void BusDialog::onActivateRFGuard (wxListEvent & event) private
Handles left mouse button double clicks on the RFGuard list.
Definition at line 1123 of file BusDialog.cc.
{
    wxCommandEvent dummy;
    onEditRFGuard(dummy);
}
References dummy, and onEditRFGuard().
onAddFUGuard()
void BusDialog::onAddFUGuard (wxCommandEvent &) private
Creates and shows an empty function unit port guard dialog for adding function unit port guards.
Definition at line 998 of file BusDialog.cc.
{
    Machine::FunctionUnitNavigator navigator =
        bus_->machine()->functionUnitNavigator();
    bool portExists = false;
    for (int i = 0; i < navigator.count(); i++) {
        if (navigator.item(i)->portCount() > 0) {
            portExists = true;
            break;
        }
    }
    if (!portExists) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_CANNOT_FU_GUARD);
        InformationDialog dialog(
            this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
        return;
    }
    FUGuardDialog dialog(this, bus_);
    dialog.ShowModal();
    updateGuardLists();
}
References bus_, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), ProDeTextGenerator::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeTextGenerator::MSG_ERROR_CANNOT_FU_GUARD, Texts::TextGenerator::text(), WxConversion::toWxString(), and updateGuardLists().
onAddRFGuard()
void BusDialog::onAddRFGuard (wxCommandEvent &) private
Creates and shows a register file guard dialog for adding register file guards.
Definition at line 898 of file BusDialog.cc.
{
    Machine::RegisterFileNavigator navigator =
        bus_->machine()->registerFileNavigator();
    if (navigator.count() < 1) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_CANNOT_RF_GUARD);
        InformationDialog dialog(this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
        return;
    }
    RFGuardDialog dialog(this, bus_);
    dialog.ShowModal();
    updateGuardLists();
}
References bus_, TTAMachine::Machine::Navigator< ComponentType >::count(), ProDeTextGenerator::instance(), TTAMachine::Component::machine(), ProDeTextGenerator::MSG_ERROR_CANNOT_RF_GUARD, TTAMachine::Machine::registerFileNavigator(), Texts::TextGenerator::text(), WxConversion::toWxString(), and updateGuardLists().
onAddSegment()
void BusDialog::onAddSegment (wxCommandEvent &) private
Adds a new segment to the segment list.
Definition at line 567 of file BusDialog.cc.
{
    if (!TransferDataFromWindow()) {
        return;
    }
    assert(newSegName_ != _T(""));
    string trimmedName =
        WxConversion::toString(newSegName_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Check that the new segment's name is unique among the segments of
    // the bus.
    if (bus_->hasSegment(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        format component =
            prodeTexts->text(ProDeTextGenerator::COMP_A_SEGMENT);
        format bus = prodeTexts->text(ProDeTextGenerator::COMP_BUS);
        message % trimmedName % component.str() % bus.str();
        component = prodeTexts->text(ProDeTextGenerator::COMP_SEGMENT);
        message % component.str();
        WarningDialog dialog(this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
        return;
    }
    new Segment(trimmedName, *bus_);
    updateSegmentList();
    // clear the segment name control
    dynamic_cast<wxTextCtrl*>(
        FindWindow(ID_SEGMENT_NAME))->SetValue(_T(""));
}
References assert, bus_, ProDeTextGenerator::COMP_A_SEGMENT, ProDeTextGenerator::COMP_BUS, ProDeTextGenerator::COMP_SEGMENT, TTAMachine::Bus::hasSegment(), ID_SEGMENT_NAME, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, newSegName_, Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), and updateSegmentList().
onBusName()
void BusDialog::onBusName (wxCommandEvent &) private
Enables and disables OK button based on input in the bus name widget.
Definition at line 617 of file BusDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onDeleteFUGuard()
void BusDialog::onDeleteFUGuard (wxCommandEvent &) private
Deletes selected function unit port guards from the function unit port guards list.
Definition at line 1032 of file BusDialog.cc.
{
    delete selectedFUGuard();
    updateGuardLists();
    wxListEvent dummy;
    onFUGuardSelection(dummy);
}
References dummy, onFUGuardSelection(), selectedFUGuard(), and updateGuardLists().
onDeleteRFGuard()
void BusDialog::onDeleteRFGuard (wxCommandEvent &) private
Deletes selected register file guards from the register file guards list.
Definition at line 922 of file BusDialog.cc.
{
    long item = -1;
    // loop selected guards and delete them
    for (int i = 0; i < rfGuardList_->GetSelectedItemCount(); ++i) {
        item = rfGuardList_->GetNextItem(
            item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
        assert (item < static_cast<int>(registerGuards_.size()));
        // retrieve item data (guard pointer) that is bound with the item
        if (item >= 0) {
            long itemData = rfGuardList_->GetItemData(item);
            RegisterGuard* rfGuard = (RegisterGuard*)itemData;
            if (rfGuard != NULL) {
                delete rfGuard;
                rfGuard = NULL;
            }
        }
    }
    updateGuardLists();
    wxListEvent dummy;
    onRFGuardSelection(dummy);
    return;
}
References assert, dummy, onRFGuardSelection(), registerGuards_, rfGuardList_, and updateGuardLists().
onDeleteSegment()
void BusDialog::onDeleteSegment (wxCommandEvent &) private
Deletes the selected segment from the bus.
The Segments before and after the deleted segments are connected to each other.
Definition at line 735 of file BusDialog.cc.
{
    Segment* selected = selectedSegment();
    assert(selected != NULL);
    delete selected;
    updateSegmentList();
    wxListEvent dummy;
    onSegmentSelection(dummy);
}
References assert, dummy, onSegmentSelection(), selectedSegment(), and updateSegmentList().
onEditFUGuard()
void BusDialog::onEditFUGuard (wxCommandEvent &) private
Handles the 'Edit FUGuard' button event.
Opens a FUGuardDialog with the selected guard's attributes set.
Definition at line 1047 of file BusDialog.cc.
{
    PortGuard* guard = selectedFUGuard();
    if (guard == NULL) {
        // No guard selected.
        return;
    }
    FUGuardDialog dialog(this, bus_, guard);
    dialog.ShowModal();
    updateGuardLists();
}
References bus_, selectedFUGuard(), and updateGuardLists().
Referenced by onActivateFUGuard().
onEditRFGuard()
void BusDialog::onEditRFGuard (wxCommandEvent &) private
Handles the 'Edit RFGuard' button event.
Opens a RFGuardDialog with the selected guard's attributes set.
Definition at line 958 of file BusDialog.cc.
{
    RegisterGuard* guard = selectedRFGuard();
    if (guard == NULL) {
        // No guard selected.
        return;
    }
    RFGuardDialog dialog(this, bus_, guard);
    dialog.ShowModal();
    updateGuardLists();
}
References bus_, selectedRFGuard(), and updateGuardLists().
Referenced by onActivateRFGuard().
onFUGuardRightClick()
void BusDialog::onFUGuardRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed on the FU guard list.
Parameters
event Information about right mouse click event.
Definition at line 1136 of file BusDialog.cc.
{
    fuGuardList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_FU_GUARD, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_FU_GUARD, WxConversion::toWxString(button.str()));
    fuGuardList_->PopupMenu(contextMenu, event.GetPoint());
}
References fuGuardList_, ID_DELETE_FU_GUARD, ID_EDIT_FU_GUARD, ProDeTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onFUGuardSelection()
void BusDialog::onFUGuardSelection (wxListEvent &) private
Disables and enables Edit and Delete buttons under the register file guard list.
If a guard is selected, buttons are enabled. If no guard is selected the buttons will be disabled.
Definition at line 1081 of file BusDialog.cc.
{
    if (fuGuardList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_FU_GUARD)->Disable();
        FindWindow(ID_EDIT_FU_GUARD)->Disable();
        return;
    }
    FindWindow(ID_DELETE_FU_GUARD)->Enable();
    FindWindow(ID_EDIT_FU_GUARD)->Enable();
}
References fuGuardList_, ID_DELETE_FU_GUARD, and ID_EDIT_FU_GUARD.
Referenced by onDeleteFUGuard().
onHelp()
void BusDialog::onHelp (wxCommandEvent & event) private
onOK()
void BusDialog::onOK (wxCommandEvent &) private
Validates input in the controls, and updates the Bus object.
Definition at line 797 of file BusDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    // Check that the machine doesn't contain instruction templates with
    // slots that are wider than the new bus width.
    Machine::InstructionTemplateNavigator navigator =
        bus_->machine()->instructionTemplateNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        int slotWidth = navigator.item(i)->supportedWidth(bus_->name());
        if (slotWidth != 0 && slotWidth > width_) {
            ProDeTextGenerator* generator =
                ProDeTextGenerator::instance();
            format message = generator->text(
                ProDeTextGenerator::MSG_ERROR_BUS_IT_SLOT_WIDTH);
            message % navigator.item(i)->name();
            message % slotWidth;
            InformationDialog dialog(
                this, WxConversion::toWxString(message.str()));
            dialog.ShowModal();
            return;
        }
    }
    // Check the name validity.
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Check that the new name is not reserved.
    if (trimmedName != bus_->name()) {
        const Machine::BusNavigator busNavigator =
        bus_->machine()->busNavigator();
    if (busNavigator.hasItem(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
        prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        message % trimmedName;
        message % prodeTexts->text(ProDeTextGenerator::COMP_A_BUS).str();
        message % prodeTexts->text(ProDeTextGenerator::COMP_MACHINE).str();
        message % prodeTexts->text(ProDeTextGenerator::COMP_BUS).str();
        WarningDialog warning(
        this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Immediate slots share namespace with busses, check that an immediate
    // slot with the same name does not exist.
        const Machine::ImmediateSlotNavigator immSlotNavigator =
        bus_->machine()->immediateSlotNavigator();
    if (immSlotNavigator.hasItem(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
        prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        message % trimmedName;
        message % prodeTexts->text(
        ProDeTextGenerator::COMP_AN_IMM_SLOT).str();
        message % prodeTexts->text(ProDeTextGenerator::COMP_MACHINE).str();
        message % prodeTexts->text(ProDeTextGenerator::COMP_BUS).str();
        WarningDialog warning(
        this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    }
    bus_->setWidth(width_);
    bus_->setImmediateWidth(immWidth_);
    bus_->setName(trimmedName);
    if (immediateExtensionBox_->GetStringSelection().IsSameAs(
            ProDeConstants::EXTENSION_ZERO)) {
        bus_->setZeroExtends();
    } else {
        bus_->setSignExtends();
    }
    EndModal(wxID_OK);
}
References bus_, TTAMachine::Machine::busNavigator(), ProDeTextGenerator::COMP_A_BUS, ProDeTextGenerator::COMP_AN_IMM_SLOT, ProDeTextGenerator::COMP_BUS, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::count(), ProDeConstants::EXTENSION_ZERO, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), immediateExtensionBox_, TTAMachine::Machine::immediateSlotNavigator(), immWidth_, ProDeTextGenerator::instance(), TTAMachine::Machine::instructionTemplateNavigator(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeTextGenerator::MSG_ERROR_BUS_IT_SLOT_WIDTH, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, TTAMachine::Bus::setImmediateWidth(), TTAMachine::Bus::setName(), TTAMachine::Bus::setSignExtends(), TTAMachine::Bus::setWidth(), TTAMachine::Bus::setZeroExtends(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), and width_.
onRFGuardRightClick()
void BusDialog::onRFGuardRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed on the register file guard list.
Parameters
event Information about right mouse click event.
Definition at line 1099 of file BusDialog.cc.
{
    rfGuardList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_RF_GUARD, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_RF_GUARD, WxConversion::toWxString(button.str()));
    rfGuardList_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_RF_GUARD, ID_EDIT_RF_GUARD, ProDeTextGenerator::instance(), rfGuardList_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onRFGuardSelection()
void BusDialog::onRFGuardSelection (wxListEvent &) private
Disables and enables Edit and Delete buttons under the register file guard list.
If a guard is selected, buttons are enabled. If no guard is selected the buttons will be disabled.
Definition at line 978 of file BusDialog.cc.
{
    if (rfGuardList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_EDIT_RF_GUARD)->Disable();
    } else {
        FindWindow(ID_EDIT_RF_GUARD)->Enable();
    }
    if (rfGuardList_->GetSelectedItemCount() < 1) {
        FindWindow(ID_DELETE_RF_GUARD)->Disable();
    } else {
        FindWindow(ID_DELETE_RF_GUARD)->Enable();
    }
}
References ID_DELETE_RF_GUARD, ID_EDIT_RF_GUARD, and rfGuardList_.
Referenced by onDeleteRFGuard().
onSegmentDown()
void BusDialog::onSegmentDown (wxCommandEvent &) private
Moves selected segment one position down in the segment chain.
Definition at line 775 of file BusDialog.cc.
{
    Segment* selected = selectedSegment();
    assert (selected != NULL);
    if (!selected->hasDestinationSegment()) {
        // Selected segment was first in the chain, do nothing.
        return;
    }
    selected->moveAfter(*(selected->destinationSegment()));
    updateSegmentList();
    // set the moved segment as selected
    long i = segList_->FindItem(0, WxConversion::toWxString(selected->name()));
    segList_->SetItemState(i,wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
}
References assert, TTAMachine::Segment::destinationSegment(), TTAMachine::Segment::hasDestinationSegment(), TTAMachine::Segment::moveAfter(), TTAMachine::Segment::name(), segList_, selectedSegment(), WxConversion::toWxString(), and updateSegmentList().
onSegmentName()
void BusDialog::onSegmentName (wxCommandEvent &) private
Enables and disables add segment button based on input in the segment name widget.
Definition at line 676 of file BusDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = newSegName_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(ID_ADD_SEGMENT)->Disable();
    } else {
        FindWindow(ID_ADD_SEGMENT)->Enable();
    }
}
References assert, ID_ADD_SEGMENT, and newSegName_.
onSegmentRightClick()
void BusDialog::onSegmentRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed.
Parameters
event Information about right mouse click event.
Definition at line 712 of file BusDialog.cc.
{
    segList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                           wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_SEGMENT, WxConversion::toWxString(button.str()));
    segList_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_SEGMENT, ProDeTextGenerator::instance(), segList_, Texts::TextGenerator::text(), WxConversion::toWxString(), and ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE.
onSegmentSelection()
void BusDialog::onSegmentSelection (wxListEvent &) private
Disables segment deletion and move buttons if no segment is selected.
Definition at line 693 of file BusDialog.cc.
{
    if (segList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_SEGMENT)->Disable();
        FindWindow(ID_SEGMENT_UP)->Disable();
        FindWindow(ID_SEGMENT_DOWN)->Disable();
        return;
    }
    FindWindow(ID_DELETE_SEGMENT)->Enable();
    FindWindow(ID_SEGMENT_UP)->Enable();
    FindWindow(ID_SEGMENT_DOWN)->Enable();
}
References ID_DELETE_SEGMENT, ID_SEGMENT_DOWN, ID_SEGMENT_UP, and segList_.
Referenced by onDeleteSegment().
onSegmentUp()
void BusDialog::onSegmentUp (wxCommandEvent &) private
Moves selected segment one position up in the segment chain.
Definition at line 752 of file BusDialog.cc.
{
    Segment* selected = selectedSegment();
    assert (selected != NULL);
    if (!selected->hasSourceSegment()) {
        // Selected segment was first in the chain, do nothing.
        return;
    }
    selected->moveBefore(*(selected->sourceSegment()));
    updateSegmentList();
    // set the moved segment as selected
    long i = segList_->FindItem(0, WxConversion::toWxString(selected->name()));
    segList_->SetItemState(i,wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
}
References assert, TTAMachine::Segment::hasSourceSegment(), TTAMachine::Segment::moveBefore(), TTAMachine::Segment::name(), segList_, selectedSegment(), TTAMachine::Segment::sourceSegment(), WxConversion::toWxString(), and updateSegmentList().
onUnconditionalGuard()
void BusDialog::onUnconditionalGuard (wxCommandEvent & event) private
Handles the unconditional guard deletion/creation when true/false guard checkbox values are toggled.
Definition at line 635 of file BusDialog.cc.
{
    bool inverted = false;
    wxCheckBox* checkbox = alwaysTrueGuard_;
    if (event.GetId() == ID_FALSE_GUARD) {
        inverted = true;
        checkbox = alwaysFalseGuard_;
    }
    if (!checkbox->GetValue()) {
        for (int i = 0; i < bus_->guardCount(); i++) {
            Guard* guard = bus_->guard(i);
            UnconditionalGuard* unCondGuard =
                dynamic_cast<UnconditionalGuard*>(guard);
            if (unCondGuard != NULL &&
                unCondGuard->isInverted() == inverted) {
                delete unCondGuard;
            }
        }
    } else {
        try {
            new UnconditionalGuard(inverted, *bus_);
        } catch (Exception& e) {
            ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
            format text = prodeTexts->text(ProDeTextGenerator::MSG_ERROR);
            wxString message = WxConversion::toWxString(text.str());
            message.Append(WxConversion::toWxString(e.errorMessage()));
            ErrorDialog dialog(this, message);
            dialog.ShowModal();
            return;
        }
    }
}
References alwaysFalseGuard_, alwaysTrueGuard_, bus_, Exception::errorMessage(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), ID_FALSE_GUARD, ProDeTextGenerator::instance(), TTAMachine::Guard::isInverted(), ProDeTextGenerator::MSG_ERROR, Texts::TextGenerator::text(), and WxConversion::toWxString().
onWidth()
void BusDialog::onWidth (wxSpinEvent &) private
Sets the immediate width range when the bus width is modified.
Definition at line 1063 of file BusDialog.cc.
{
    wxSpinCtrl* width = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_BUS_WIDTH));
    wxSpinCtrl* siWidth = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_SI_WIDTH));
    if (siWidth->GetValue() > width->GetValue()) {
        siWidth->SetValue(width->GetValue());
    }
    siWidth->SetRange(0, width->GetValue());
}
References ID_BUS_WIDTH, and ID_SI_WIDTH.
Referenced by TransferDataToWindow().
selectedFUGuard()
PortGuard * BusDialog::selectedFUGuard () const private
Returns pointer to the selected fu port guard.
Returns
NULL if no port guard is selected.
Definition at line 522 of file BusDialog.cc.
{
    long item = -1;
    item = fuGuardList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    assert (item < int(portGuards_.size()));
    return portGuards_[item];
}
References assert, fuGuardList_, and portGuards_.
Referenced by onDeleteFUGuard(), and onEditFUGuard().
selectedRFGuard()
RegisterGuard * BusDialog::selectedRFGuard () const private
Returns pointer to the selected register file guard.
Returns
NULL if no register guard is selected.
Definition at line 543 of file BusDialog.cc.
{
    long item = -1;
    item = rfGuardList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    assert (item < int(registerGuards_.size()));
    long itemData = rfGuardList_->GetItemData(item);
    RegisterGuard* rfGuard = (RegisterGuard*)itemData;
    assert (rfGuard != NULL);
    return rfGuard;
}
References assert, registerGuards_, and rfGuardList_.
Referenced by onEditRFGuard().
selectedSegment()
Segment * BusDialog::selectedSegment () const private
Returns pointer to the selected segment.
Returns NULL if no segment is selected.
Definition at line 501 of file BusDialog.cc.
{
    // search the selected segment in the segment list widget
    Segment* selected = NULL;
    for (int i = 0; i < segList_->GetItemCount(); i++) {
        // search selected list item
        if (segList_->GetItemState(i, wxLIST_STATE_SELECTED) != 0) {
            string name = WxConversion::toString(segList_->GetItemText(i));
            selected = bus_->segment(name);
        }
    }
    return selected;
}
References bus_, segList_, TTAMachine::Bus::segment(), and WxConversion::toString().
Referenced by onDeleteSegment(), onSegmentDown(), and onSegmentUp().
setTexts()
void BusDialog::setTexts () private
Definition at line 192 of file BusDialog.cc.
                    {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_BUS_DIALOG_TITLE);
    string title = fmt.str();
    SetTitle(WxConversion::toWxString(title));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_SEGMENT),
                          GUITextGenerator::TXT_BUTTON_ADD);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_SEGMENT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_SEGMENT_UP),
                          ProDeTextGenerator::TXT_BUTTON_UP);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_SEGMENT_DOWN),
                          ProDeTextGenerator::TXT_BUTTON_DOWN);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_RF_GUARD),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_RF_GUARD),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_RF_GUARD),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_FU_GUARD),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_FU_GUARD),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_FU_GUARD),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_BUS_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_BUS_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_SEGMENT_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_SI_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_SI_EXTENSION),
                          ProDeTextGenerator::TXT_LABEL_EXTENSION);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_TRUE_GUARD),
                          ProDeTextGenerator::TXT_LABEL_TRUE_GUARD);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_FALSE_GUARD),
                          ProDeTextGenerator::TXT_LABEL_FALSE_GUARD);
    // Radio button labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO);
    immediateExtensionBox_->SetString(0, WxConversion::toWxString(fmt.str()));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN);
    immediateExtensionBox_->SetString(1, WxConversion::toWxString(fmt.str()));
    // box sizer labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_BUS_BUS_BOX);
    string label = fmt.str();
    WidgetTools::setWidgetLabel(busSizer_, label);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_BUS_SEGMENTS_BOX);
    label = fmt.str();
    WidgetTools::setWidgetLabel(segmentSizer_, label);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_BUS_SI_BOX);
    label = fmt.str();
    WidgetTools::setWidgetLabel(siSizer_, label);
    fmt = prodeTexts->
        text(ProDeTextGenerator::TXT_BUS_REGISTER_GUARD_BOX);
    label = fmt.str();
    WidgetTools::setWidgetLabel(registerGuardSizer_, label);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_BUS_PORT_GUARD_BOX);
    label = fmt.str();
    WidgetTools::setWidgetLabel(portGuardSizer_, label);
    // Create segment list columns.
    wxListCtrl* segmentList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_SEGMENT_LIST));
    wxListCtrl* rfGuardList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_RF_GUARD_LIST));
    wxListCtrl* fuGuardList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_FU_GUARD_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_INVERTED);
    string invLabel = fmt.str();
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    string nameLabel = fmt.str();
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_INDEX);
    string indexLabel = fmt.str();
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_PORT);
    string portLabel = fmt.str();
    segmentList->InsertColumn(0, WxConversion::toWxString(nameLabel),
                              wxLIST_FORMAT_LEFT, 280);
    rfGuardList->InsertColumn(0, WxConversion::toWxString(nameLabel),
                              wxLIST_FORMAT_LEFT, 170);
    rfGuardList->InsertColumn(1, WxConversion::toWxString(indexLabel),
                              wxLIST_FORMAT_LEFT, 70);
    rfGuardList->InsertColumn(2, WxConversion::toWxString(invLabel),
                              wxLIST_FORMAT_LEFT, 40);
    fuGuardList->InsertColumn(0, WxConversion::toWxString(invLabel),
                              wxLIST_FORMAT_LEFT, 40);
    fuGuardList->InsertColumn(1, WxConversion::toWxString(nameLabel),
                              wxLIST_FORMAT_LEFT, 170);
    fuGuardList->InsertColumn(2, WxConversion::toWxString(portLabel),
                              wxLIST_FORMAT_LEFT, 70);
}
References busSizer_, ID_ADD_FU_GUARD, ID_ADD_RF_GUARD, ID_ADD_SEGMENT, ID_DELETE_FU_GUARD, ID_DELETE_RF_GUARD, ID_DELETE_SEGMENT, ID_EDIT_FU_GUARD, ID_EDIT_RF_GUARD, ID_FALSE_GUARD, ID_FU_GUARD_LIST, ID_HELP, ID_LABEL_BUS_NAME, ID_LABEL_BUS_WIDTH, ID_LABEL_SEGMENT_NAME, ID_LABEL_SI_WIDTH, ID_RF_GUARD_LIST, ID_SEGMENT_DOWN, ID_SEGMENT_LIST, ID_SEGMENT_UP, ID_SI_EXTENSION, ID_TRUE_GUARD, immediateExtensionBox_, GUITextGenerator::instance(), ProDeTextGenerator::instance(), portGuardSizer_, registerGuardSizer_, segmentSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), siSizer_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_BUS_BUS_BOX, ProDeTextGenerator::TXT_BUS_DIALOG_TITLE, ProDeTextGenerator::TXT_BUS_PORT_GUARD_BOX, ProDeTextGenerator::TXT_BUS_REGISTER_GUARD_BOX, ProDeTextGenerator::TXT_BUS_SEGMENTS_BOX, ProDeTextGenerator::TXT_BUS_SI_BOX, GUITextGenerator::TXT_BUTTON_ADD, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, ProDeTextGenerator::TXT_BUTTON_DOWN, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_BUTTON_UP, ProDeTextGenerator::TXT_COLUMN_INDEX, ProDeTextGenerator::TXT_COLUMN_INVERTED, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_PORT, ProDeTextGenerator::TXT_LABEL_EXTENSION, ProDeTextGenerator::TXT_LABEL_FALSE_GUARD, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_TRUE_GUARD, ProDeTextGenerator::TXT_LABEL_WIDTH, ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN, and ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO.
TransferDataToWindow()
bool BusDialog::TransferDataToWindow () private virtual
Transfers the data from the bus model to the dialog controls.
Returns
false, if an error occured in the transfer.
Definition at line 337 of file BusDialog.cc.
{
    name_ = WxConversion::toWxString(bus_->name());
    width_ = bus_->width();
    immWidth_ = bus_->immediateWidth();
    // set extension
    if (bus_->signExtends()) {
        immediateExtensionBox_->SetStringSelection(
            ProDeConstants::EXTENSION_SIGN);
    } else {
        immediateExtensionBox_->SetStringSelection(
            ProDeConstants::EXTENSION_ZERO);
    }
    updateGuardLists();
    updateSegmentList();
    // wxWidgets GTK1 version seems to bug with spincontrol validators.
    // The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_BUS_WIDTH))->SetValue(width_);
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_SI_WIDTH))->SetValue(immWidth_);
    wxSpinEvent dummy;
    onWidth(dummy);
    return wxWindow::TransferDataToWindow();
}
References bus_, dummy, ProDeConstants::EXTENSION_SIGN, ProDeConstants::EXTENSION_ZERO, ID_BUS_WIDTH, ID_SI_WIDTH, immediateExtensionBox_, TTAMachine::Bus::immediateWidth(), immWidth_, TTAMachine::Component::name(), name_, onWidth(), TTAMachine::Bus::signExtends(), WxConversion::toWxString(), updateGuardLists(), updateSegmentList(), TTAMachine::Bus::width(), and width_.
updateGuardLists()
void BusDialog::updateGuardLists () private
Updates the guard lists.
Definition at line 412 of file BusDialog.cc.
{
    assert (rfGuardList_ != NULL);
    assert (fuGuardList_ != NULL);
    rfGuardList_->DeleteAllItems();
    fuGuardList_->DeleteAllItems();
    registerGuards_.clear();
    portGuards_.clear();
    alwaysTrueGuard_->SetValue(false);
    alwaysFalseGuard_->SetValue(false);
    // add guards
    for (int i = 0; i < bus_->guardCount(); i++) {
        Guard* guard = bus_->guard(i);
        UnconditionalGuard* unCondGuard =
            dynamic_cast<UnconditionalGuard*>(guard);
        RegisterGuard* rfGuard = dynamic_cast<RegisterGuard*>(guard);
        PortGuard* fuGuard = dynamic_cast<PortGuard*>(guard);
        if (unCondGuard != NULL) {
            // unconditional guard
            if (unCondGuard->isInverted()) {
                alwaysFalseGuard_->SetValue(true);
            } else {
                alwaysTrueGuard_->SetValue(true);
            }
        } else if(rfGuard != NULL) {
            // register guard
            int index = registerGuards_.size();
            registerGuards_.push_back(rfGuard);
            string name = rfGuard->registerFile()->name();
            int rfIndex = rfGuard->registerIndex();
            rfGuardList_->InsertItem(index, WxConversion::toWxString(name));
            rfGuardList_->SetItem(index, 1, WxConversion::toWxString(rfIndex));
            if (rfGuard->isInverted()) {
                rfGuardList_->SetItem(index, 2, _T("*"));
            } else {
                rfGuardList_->SetItem(index, 2, _T(" "));
            }
            // bind pointer to the guard as item data for future reference
            rfGuardList_->SetItemData(index, (long)rfGuard);
        } else if(fuGuard != NULL) {
            // port guard
            int index = portGuards_.size();
            portGuards_.push_back(fuGuard);
            if (fuGuard->isInverted()) {
                fuGuardList_->InsertItem(index, _T("*"));
            } else {
                fuGuardList_->InsertItem(index, _T(" "));
            }
            string name = fuGuard->port()->parentUnit()->name();
            fuGuardList_->SetItem(index, 1, WxConversion::toWxString(name));
            name = fuGuard->port()->name();
            fuGuardList_->SetItem(index, 2, WxConversion::toWxString(name));
        }
    }
    // sort guard list with given function, data parameter is not needed
    rfGuardList_->SortItems(ListCompareFunction, static_cast<long>(0));
}
References alwaysFalseGuard_, alwaysTrueGuard_, assert, bus_, fuGuardList_, TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::Guard::isInverted(), ListCompareFunction(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), portGuards_, TTAMachine::RegisterGuard::registerFile(), registerGuards_, TTAMachine::RegisterGuard::registerIndex(), rfGuardList_, and WxConversion::toWxString().
Referenced by onAddFUGuard(), onAddRFGuard(), onDeleteFUGuard(), onDeleteRFGuard(), onEditFUGuard(), onEditRFGuard(), and TransferDataToWindow().
updateSegmentList()
void BusDialog::updateSegmentList () private
Updates the segment list control.
Definition at line 486 of file BusDialog.cc.
{
    segList_->DeleteAllItems();
    for (int i = bus_->segmentCount()-1;i > -1;i--) {
        string segmentName = bus_->segment(i)->name();
        segList_->InsertItem(0, WxConversion::toWxString(segmentName));
    }
}
References bus_, TTAMachine::Segment::name(), segList_, TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), and WxConversion::toWxString().
Referenced by onAddSegment(), onDeleteSegment(), onSegmentDown(), onSegmentUp(), and TransferDataToWindow().
Member Data Documentation
alwaysFalseGuard_
wxCheckBox* BusDialog::alwaysFalseGuard_ private
Check box for always false unconditional guard.
Definition at line 112 of file BusDialog.hh.
Referenced by onUnconditionalGuard(), and updateGuardLists().
alwaysTrueGuard_
wxCheckBox* BusDialog::alwaysTrueGuard_ private
Check box for always true unconditional guard.
Definition at line 110 of file BusDialog.hh.
Referenced by onUnconditionalGuard(), and updateGuardLists().
bus_
TTAMachine::Bus* BusDialog::bus_ private
Transport Bus to edit.
Definition at line 97 of file BusDialog.hh.
Referenced by onAddFUGuard(), onAddRFGuard(), onAddSegment(), onEditFUGuard(), onEditRFGuard(), onOK(), onUnconditionalGuard(), selectedSegment(), TransferDataToWindow(), updateGuardLists(), and updateSegmentList().
busSizer_
wxStaticBoxSizer* BusDialog::busSizer_ private
Static boxsizer for the bus properties.
Definition at line 121 of file BusDialog.hh.
Referenced by createContents(), and setTexts().
fuGuardList_
wxListCtrl* BusDialog::fuGuardList_ private
Function unit port guard list control.
Definition at line 118 of file BusDialog.hh.
Referenced by onFUGuardRightClick(), onFUGuardSelection(), selectedFUGuard(), and updateGuardLists().
immediateExtensionBox_
wxRadioBox* BusDialog::immediateExtensionBox_ private
Radio box for immediate extension.
Definition at line 114 of file BusDialog.hh.
Referenced by onOK(), setTexts(), and TransferDataToWindow().
immWidth_
int BusDialog::immWidth_ private
Short immediate width.
Definition at line 103 of file BusDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
name_
wxString BusDialog::name_ private
Name of the bus.
Definition at line 99 of file BusDialog.hh.
Referenced by onBusName(), onOK(), and TransferDataToWindow().
newSegName_
wxString BusDialog::newSegName_ private
Name for a new segment.
Definition at line 105 of file BusDialog.hh.
Referenced by onAddSegment(), and onSegmentName().
portGuards_
vector<TTAMachine::PortGuard*> BusDialog::portGuards_ private
list of port guards
Definition at line 135 of file BusDialog.hh.
Referenced by selectedFUGuard(), and updateGuardLists().
portGuardSizer_
wxStaticBoxSizer* BusDialog::portGuardSizer_ private
Static boxsizer for the port guard properties.
Definition at line 127 of file BusDialog.hh.
Referenced by createContents(), and setTexts().
registerGuards_
vector<TTAMachine::RegisterGuard*> BusDialog::registerGuards_ private
list of register guards
Definition at line 133 of file BusDialog.hh.
Referenced by onDeleteRFGuard(), selectedRFGuard(), and updateGuardLists().
registerGuardSizer_
wxStaticBoxSizer* BusDialog::registerGuardSizer_ private
Static boxsizer for the register guard properties.
Definition at line 125 of file BusDialog.hh.
Referenced by createContents(), and setTexts().
rfGuardList_
wxListCtrl* BusDialog::rfGuardList_ private
Register file guard list control.
Definition at line 116 of file BusDialog.hh.
Referenced by onDeleteRFGuard(), onRFGuardRightClick(), onRFGuardSelection(), selectedRFGuard(), and updateGuardLists().
segList_
wxListCtrl* BusDialog::segList_ private
List widget for the segment list.
Definition at line 108 of file BusDialog.hh.
Referenced by onSegmentDown(), onSegmentRightClick(), onSegmentSelection(), onSegmentUp(), selectedSegment(), and updateSegmentList().
segmentSizer_
wxStaticBoxSizer* BusDialog::segmentSizer_ private
Static boxsizer for the segment properties.
Definition at line 129 of file BusDialog.hh.
Referenced by createContents(), and setTexts().
siSizer_
wxStaticBoxSizer* BusDialog::siSizer_ private
Static boxsizer for the short immediate properties.
Definition at line 123 of file BusDialog.hh.
Referenced by createContents(), and setTexts().
width_
int BusDialog::width_ private
Width of the bus.
Definition at line 101 of file BusDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
BusDialog.hh
BusDialog.cc