OpenASIP: llvm::TCETargetMachine Class Reference
llvm::TCETargetMachine Class Reference
#include <TCETargetMachine.hh>
Public Member Functions
TCETargetMachine (const Target &T, const Triple &TTriple, const llvm::StringRef &CPU, const llvm::StringRef &FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
virtual ~TCETargetMachine ()
virtual void setTargetMachinePlugin (TCETargetMachinePlugin &plugin, TTAMachine::Machine &target)
virtual TCETargetMachinePlugin & targetPlugin () const
virtual void setEmulationModule (Module *mod)
virtual void setTTAMach (const TTAMachine::Machine *mach) override
virtual const TTAMachine::Machine & ttaMachine () const
virtual const TCESubtarget * getSubtargetImpl () const
virtual const TargetSubtargetInfo * getSubtargetImpl (const Function &) const override
virtual const TargetInstrInfo * getInstrInfo () const
virtual const TargetRegisterInfo * getRegisterInfo () const
virtual const DataLayout * getDataLayout () const
virtual const TargetFrameLowering * getFrameLowering () const
virtual TargetLowering * getTargetLowering () const
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM) override
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
std::string operationName (unsigned opc) const
bool validStackAccessOperation (const std::string &opName) const
bool hasOperation (TCEString operationName) const
std::string rfName (unsigned dwarfRegNum) const
unsigned registerIndex (unsigned dwarfRegNum) const
std::string registerName (unsigned dwarfRegNum) const
unsigned llvmRegisterId (const TCEString &ttaRegister)
TTAMachine::Machine * createMachine ()
std::string dataASName ()
unsigned raPortDRegNum () const
void loadPlugin ()
unsigned spDRegNum () const
unsigned opcode (TCEString operationName) const
int getMinOpcode (llvm::SDNode *n)
int getMinuOpcode (llvm::SDNode *n)
int getMaxOpcode (llvm::SDNode *n)
int getMaxuOpcode (llvm::SDNode *n)
int getAddOpcode (const llvm::EVT &vt) const
int getShlOpcode (const llvm::EVT &vt) const
int getIorOpcode (const llvm::EVT &vt) const
void setStackAlignment (unsigned align)
unsigned stackAlignment () const
bool has8bitLoads () const
bool has16bitLoads () const
int bitness () const
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * missingOperations ()
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * promotedOperations ()
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * customLegalizedOperations ()
int64_t smallestImmValue () const
uint64_t largestImmValue () const
bool canEncodeAsMOVI (const llvm::MVT &vt, int64_t val) const
bool canEncodeAsMOVF (const llvm::APFloat &fp) const
bool canMaterializeConstant (const ConstantInt &ci) const
int getLoadOpcode (int asid, int align, const llvm::EVT &vt) const
Public Member Functions inherited from llvm::TCEBaseTargetMachine
TCEBaseTargetMachine (const Target &T, const Triple &TT, const llvm::StringRef &CPU, const llvm::StringRef &FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Public Attributes
Module * emulationModule_
Public Attributes inherited from llvm::TCEBaseTargetMachine
const TTAMachine::Machine * ttaMach_
Private Member Functions
void calculateSupportedImmediates ()
Private Attributes
TCETargetMachinePlugin * plugin_
PluginTools * pluginTool_
std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > missingOps_
llvm::ISD opcode list of operations that have to be expanded.
std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > promotedOps_
std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > customLegalizedOps_
int64_t smallestImm_ = std::numeric_limits<int64_t>::max()
uint64_t largestImm_ = std::numeric_limits<int64_t>::min()
int SupportedFPImmWidth_ = std::numeric_limits<int>::min()
unsigned stackAlignment_
Detailed Description
TCE Universal machine target description.
Definition at line 106 of file TCETargetMachine.hh.
Constructor & Destructor Documentation
TCETargetMachine()
TCETargetMachine::TCETargetMachine (const Target & T, const Triple & TTriple, const llvm::StringRef & CPU, const llvm::StringRef & FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
Definition at line 148 of file TCETargetMachine.cc.
                                                                                    :
    #else
    std::optional<Reloc::Model> RM, std::optional<CodeModel::Model> CM, CodeGenOpt::Level OL, bool) :
    #endif
    TCEBaseTargetMachine(T, TTriple, CPU, FS, Options,
                         RM?*RM:Reloc::Model::Static, CM?*CM:CodeModel::Small, OL),
    // Note: Reloc::Model does not have "Default" named member. "Static" is ok?
    // Note: CodeModel does not have "Default" named member. "Small" is ok?
    plugin_(NULL), pluginTool_(NULL) {
}
~TCETargetMachine()
TCETargetMachine::~TCETargetMachine () virtual
The Destructor.
Definition at line 167 of file TCETargetMachine.cc.
{
    if (pluginTool_ != NULL) {
        delete pluginTool_;
        pluginTool_ = NULL;
    }
}
References pluginTool_.
Member Function Documentation
bitness()
int llvm::TCETargetMachine::bitness () const inline
Definition at line 298 of file TCETargetMachine.hh.
{
            return plugin_->is64bit() ? 64 : 32;
        }
References llvm::TCETargetMachinePlugin::is64bit(), and plugin_.
calculateSupportedImmediates()
void TCETargetMachine::calculateSupportedImmediates () private
Definition at line 400 of file TCETargetMachine.cc.
{
    using MCC = MachineConnectivityCheck;
    // FIX ME: All 32 bit regs are assumed to be RF-connected.
    std::pair<int64_t, uint64_t> moveImm{
        std::numeric_limits<int64_t>::max(),
        std::numeric_limits<uint64_t>::min() };
    assert(ttaMach_);
    for (auto& rf : ttaMach_->registerFileNavigator()) {
        if (rf->width() != 32) continue;
        for (auto& bus : ttaMach_->busNavigator()) {
            if (!MCC::busConnectedToRF(*bus, *rf)
                || bus->immediateWidth() == 0) {
                continue;
            }
            if (bus->immediateWidth() >= 32) {
                moveImm.first = -(1ll << (32-1));
                moveImm.second = (1ll << 32)-1;
                break;
            } else {
                std::pair<int64_t, uint64_t> imm =
                    MathTools::bitsToIntegerRange<int64_t, uint64_t>(
                        bus->immediateWidth(),
                        bus->signExtends());
                moveImm.first = std::min(moveImm.first, imm.first);
                moveImm.second = std::max(moveImm.second, imm.second);
            }
        }
    }
    for (auto& iu : ttaMach_->immediateUnitNavigator()) {
        for (auto& it : ttaMach_->instructionTemplateNavigator()) {
            int supportedWidth = it->supportedWidth(*iu);
            if (supportedWidth >= 32) {
                moveImm.first = -(1ll << (32-1));
                moveImm.second = (1ll << 32)-1;
                break;
            } else {
                std::pair<int64_t, uint64_t> imm =
                    MathTools::bitsToIntegerRange<int64_t, uint64_t>(
                        supportedWidth, iu->signExtends());
                moveImm.first = std::min(moveImm.first, imm.first);
                moveImm.second = std::max(moveImm.second, imm.second);
            }
        }
    }
    smallestImm_ = moveImm.first;
    largestImm_ = moveImm.second;
    for (auto* rf : ttaMach_->registerFileNavigator()) {
        if (!MCC::rfConnected(*rf)) continue;
        SupportedFPImmWidth_ = std::max(
            SupportedFPImmWidth_,
            ImmInfo::registerImmediateLoadWidth(*rf, false));
    }
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), largestImm_, TTAMachine::Machine::registerFileNavigator(), ImmInfo::registerImmediateLoadWidth(), smallestImm_, SupportedFPImmWidth_, and llvm::TCEBaseTargetMachine::ttaMach_.
Referenced by setTTAMach().
canEncodeAsMOVF()
bool TCETargetMachine::canEncodeAsMOVF (const llvm::APFloat & fp) const
Returns true if the floating point value can be encoded as immediate to register.
Definition at line 393 of file TCETargetMachine.cc.
{
    int fpBitWidth = static_cast<int>(
        llvm::APFloat::getSizeInBits(fp.getSemantics()));
    return fpBitWidth <= SupportedFPImmWidth_;
}
References SupportedFPImmWidth_.
Referenced by llvm::TCETargetLowering::isFPImmLegal().
canEncodeAsMOVI()
bool TCETargetMachine::canEncodeAsMOVI (const llvm::MVT & vt, int64_t val) const
Returns true if the value can be encoded as immediate to register.
Definition at line 370 of file TCETargetMachine.cc.
{
    // setTargetMachinePlugin() calls calculateSupportedImmediateLimits.
    assert(ttaMach_ && "setTargetMachinePlugin() was not called");
    switch (vt.SimpleTy) {
        case MVT::i1:
            return (1 <= largestImm_);
        case MVT::i8:
        case MVT::i16:
        case MVT::i32:
        case MVT::i64:
            return smallestImm_ == INT64_MIN || largestImm_ == UINT64_MAX ||
                ((int64_t)smallestImm_ <= val &&
                (val < 0 || val <= (int64_t)largestImm_));
        default: assert(false && "Not implemented or supported.");
    }
    return false;
}
References assert, largestImm_, smallestImm_, and llvm::TCEBaseTargetMachine::ttaMach_.
Referenced by llvm::TCETargetLowering::canEncodeImmediate(), and llvm::TCETargetLowering::LowerBuildVector().
canMaterializeConstant()
bool llvm::TCETargetMachine::canMaterializeConstant (const ConstantInt & ci) const inline
Definition at line 325 of file TCETargetMachine.hh.
{
            return plugin_->canMaterializeConstant(ci);
        }
References llvm::TCETargetMachinePlugin::canMaterializeConstant(), and plugin_.
Referenced by llvm::TCETargetLowering::canEncodeImmediate().
createMachine()
TTAMachine::Machine * TCETargetMachine::createMachine ()
Creates a TTAMachine::Machine object of the target architecture.
Definition at line 311 of file TCETargetMachine.cc.
{
    LLVMTCECmdLineOptions* options =
        dynamic_cast<LLVMTCECmdLineOptions*>(Application::cmdLineOptions());
    assert(options->isMachineFileDefined() && "ADF not defined");
    assert(options->machineFile() != "" && "ADF not defined");
    ADFSerializer serializer;
    serializer.setSourceFile(options->machineFile());
    return serializer.readMachine();
}
References assert, Application::cmdLineOptions(), options, ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
createPassConfig()
TargetPassConfig * TCETargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Definition at line 356 of file TCETargetMachine.cc.
{
    TCEPassConfig *tpc;
    tpc =  new TCEPassConfig(this, PM, plugin_);
    // TODO: is this false by default if not set?
    // false seems to give slightly better performance than true.
    tpc->setEnableTailMerge(false);
    return tpc;
}
References plugin_.
customLegalizedOperations()
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * TCETargetMachine::customLegalizedOperations ()
Returns list of llvm::ISD SelectionDAG opcodes for operations that are not supported in the target architecture but will be custom-selected.
Definition at line 351 of file TCETargetMachine.cc.
{
    return &customLegalizedOps_;
}
References customLegalizedOps_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
dataASName()
std::string llvm::TCETargetMachine::dataASName () inline
Definition at line 231 of file TCETargetMachine.hh.
{
            return plugin_->dataASName();
        }
References llvm::TCETargetMachinePlugin::dataASName(), and plugin_.
getAddOpcode()
int llvm::TCETargetMachine::getAddOpcode (const llvm::EVT & vt) const inline
Definition at line 265 of file TCETargetMachine.hh.
{
            return plugin_->getAddOpcode(vt);
        }
References llvm::TCETargetMachinePlugin::getAddOpcode(), and plugin_.
getDataLayout()
virtual const DataLayout * llvm::TCETargetMachine::getDataLayout () const inline virtual
Definition at line 166 of file TCETargetMachine.hh.
{
            return plugin_->getDataLayout();
        }
References llvm::TCETargetMachinePlugin::getDataLayout(), and plugin_.
getFrameLowering()
virtual const TargetFrameLowering * llvm::TCETargetMachine::getFrameLowering () const inline virtual
Definition at line 170 of file TCETargetMachine.hh.
{
            return plugin_->getFrameLowering();
        }
References llvm::TCETargetMachinePlugin::getFrameLowering(), and plugin_.
getInstrInfo()
virtual const TargetInstrInfo * llvm::TCETargetMachine::getInstrInfo () const inline virtual
Definition at line 158 of file TCETargetMachine.hh.
{
            return plugin_->getInstrInfo();
        }
References llvm::TCETargetMachinePlugin::getInstrInfo(), and plugin_.
getIorOpcode()
int llvm::TCETargetMachine::getIorOpcode (const llvm::EVT & vt) const inline
Definition at line 273 of file TCETargetMachine.hh.
{
            return plugin_->getIorOpcode(vt);
        }
References llvm::TCETargetMachinePlugin::getIorOpcode(), and plugin_.
getLoadOpcode()
int TCETargetMachine::getLoadOpcode (int asid, int align, const llvm::EVT & vt) const
Definition at line 467 of file TCETargetMachine.cc.
{
    int laneCount = vt.getVectorElementCount().getKnownMinValue();
    int laneSize = vt.getScalarSizeInBits();
    int vecSize = laneCount * laneSize;
    TCEString relaxedName = "LD"; relaxedName << laneSize << "X" << laneCount;
    TCEString strictName = "LD"; strictName << vecSize;
    bool allowStrict = vecSize <= align;
    auto fuNav = ttaMach_->functionUnitNavigator();
    bool found = false;
    for (int i = 0; i < fuNav.count(); i++) {
        auto fu =  fuNav.item(i);
        if (fu->hasOperation(relaxedName) && fu->hasAddressSpace()) {
            auto as = fu->addressSpace();
            if (as->hasNumericalId(asid)) {
                found = true;
                break;
            }
        }
        if (allowStrict) {
            if (fu->hasOperation(strictName) && fu->hasAddressSpace()) {
                auto as = fu->addressSpace();
                if (as->hasNumericalId(asid)) {
                    found = true;
                    break;
                }
            }
        }
    }
    return found ? plugin_->getLoadOpcode(vt) : -1;
}
References TTAMachine::Machine::functionUnitNavigator(), llvm::TCETargetMachinePlugin::getLoadOpcode(), TTAMachine::Machine::Navigator< ComponentType >::item(), plugin_, and llvm::TCEBaseTargetMachine::ttaMach_.
getMaxOpcode()
int llvm::TCETargetMachine::getMaxOpcode (llvm::SDNode * n) inline
Definition at line 257 of file TCETargetMachine.hh.
{
            return plugin_->getMaxOpcode(n);
        }
References llvm::TCETargetMachinePlugin::getMaxOpcode(), and plugin_.
Referenced by TCEDAGToDAGISel::Select().
getMaxuOpcode()
int llvm::TCETargetMachine::getMaxuOpcode (llvm::SDNode * n) inline
Definition at line 261 of file TCETargetMachine.hh.
{
            return plugin_->getMaxuOpcode(n);
        }
References llvm::TCETargetMachinePlugin::getMaxuOpcode(), and plugin_.
Referenced by TCEDAGToDAGISel::Select().
getMinOpcode()
int llvm::TCETargetMachine::getMinOpcode (llvm::SDNode * n) inline
Definition at line 249 of file TCETargetMachine.hh.
{
            return plugin_->getMinOpcode(n);
        }
References llvm::TCETargetMachinePlugin::getMinOpcode(), and plugin_.
Referenced by TCEDAGToDAGISel::Select().
getMinuOpcode()
int llvm::TCETargetMachine::getMinuOpcode (llvm::SDNode * n) inline
Definition at line 253 of file TCETargetMachine.hh.
{
            return plugin_->getMinuOpcode(n);
        }
References llvm::TCETargetMachinePlugin::getMinuOpcode(), and plugin_.
Referenced by TCEDAGToDAGISel::Select().
getRegisterInfo()
virtual const TargetRegisterInfo * llvm::TCETargetMachine::getRegisterInfo () const inline virtual
Definition at line 162 of file TCETargetMachine.hh.
{
            return plugin_->getRegisterInfo();
        }
References llvm::TCETargetMachinePlugin::getRegisterInfo(), and plugin_.
getShlOpcode()
int llvm::TCETargetMachine::getShlOpcode (const llvm::EVT & vt) const inline
Definition at line 269 of file TCETargetMachine.hh.
{
            return plugin_->getShlOpcode(vt);
        }
References llvm::TCETargetMachinePlugin::getShlOpcode(), and plugin_.
getSubtargetImpl() [1/2]
virtual const TCESubtarget * llvm::TCETargetMachine::getSubtargetImpl () const inline virtual
Definition at line 148 of file TCETargetMachine.hh.
{
            // compiler does not know it's derived without the plugin,
            // but this class cannow include the plugin.
            return reinterpret_cast<const TCESubtarget*>(plugin_->getSubtarget());
        }
References llvm::TCETargetMachinePlugin::getSubtarget(), and plugin_.
getSubtargetImpl() [2/2]
virtual const TargetSubtargetInfo * llvm::TCETargetMachine::getSubtargetImpl (const Function &) const inline override virtual
Definition at line 154 of file TCETargetMachine.hh.
{
            return plugin_->getSubtarget();
        }
References llvm::TCETargetMachinePlugin::getSubtarget(), and plugin_.
getTargetLowering()
virtual TargetLowering * llvm::TCETargetMachine::getTargetLowering () const inline virtual
Definition at line 173 of file TCETargetMachine.hh.
{
            return plugin_->getTargetLowering();
        }
References llvm::TCETargetMachinePlugin::getTargetLowering(), and plugin_.
getTargetTransformInfo()
TargetTransformInfo llvm::TCETargetMachine::getTargetTransformInfo (const Function & F) const inline override
Definition at line 187 of file TCETargetMachine.hh.
{
            return plugin_->getTargetTransformInfo(F);
        }
References llvm::TCETargetMachinePlugin::getTargetTransformInfo(), and plugin_.
has16bitLoads()
bool llvm::TCETargetMachine::has16bitLoads () const inline
Definition at line 294 of file TCETargetMachine.hh.
{
            return plugin_->has16bitLoads();
        }
References llvm::TCETargetMachinePlugin::has16bitLoads(), and plugin_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
has8bitLoads()
bool llvm::TCETargetMachine::has8bitLoads () const inline
Definition at line 290 of file TCETargetMachine.hh.
{
            return plugin_->has8bitLoads();
        }
References llvm::TCETargetMachinePlugin::has8bitLoads(), and plugin_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
hasOperation()
bool llvm::TCETargetMachine::hasOperation (TCEString operationName) const inline
Definition at line 204 of file TCETargetMachine.hh.
{
            return plugin_->hasOperation(operationName);
        }
References llvm::TCETargetMachinePlugin::hasOperation(), operationName(), and plugin_.
Referenced by llvm::TCERegisterInfo::eliminateFrameIndex(), llvm::TCETargetLowering::LowerBuildVector(), and llvm::TCETargetLowering::LowerShift().
largestImmValue()
uint64_t llvm::TCETargetMachine::largestImmValue () const inline
Definition at line 318 of file TCETargetMachine.hh.
{
            assert(ttaMach_ && "setTargetMachinePlugin() was not called");
            return largestImm_;
        }
References assert, largestImm_, and llvm::TCEBaseTargetMachine::ttaMach_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
llvmRegisterId()
unsigned llvm::TCETargetMachine::llvmRegisterId (const TCEString & ttaRegister) inline
Definition at line 225 of file TCETargetMachine.hh.
{
            return plugin_->llvmRegisterId(ttaRegister);
        }
References llvm::TCETargetMachinePlugin::llvmRegisterId(), and plugin_.
Referenced by llvm::TCETargetLowering::getRegForInlineAsmConstraint().
loadPlugin()
void llvm::TCETargetMachine::loadPlugin ()
missingOperations()
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * TCETargetMachine::missingOperations ()
Returns list of llvm::ISD SelectionDAG opcodes for operations that are not supported in the target architecture.
The returned operations have to be expanded to emulation function calls or emulation patterns in TCETargetLowering.
Definition at line 330 of file TCETargetMachine.cc.
{
    return &missingOps_;
}
References missingOps_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
opcode()
unsigned llvm::TCETargetMachine::opcode (TCEString operationName) const inline
Definition at line 245 of file TCETargetMachine.hh.
{
            return plugin_->opcode(operationName);
        }
References llvm::TCETargetMachinePlugin::opcode(), operationName(), and plugin_.
Referenced by llvm::TCERegisterInfo::eliminateFrameIndex().
operationName()
std::string llvm::TCETargetMachine::operationName (unsigned opc) const inline
Definition at line 192 of file TCETargetMachine.hh.
{
            return plugin_->operationName(opc);
        }
References llvm::TCETargetMachinePlugin::operationName(), and plugin_.
Referenced by llvm::TCERegisterInfo::eliminateFrameIndex(), hasOperation(), opcode(), osalInputIndex(), and ConstantTransformer::runOnMachineFunction().
promotedOperations()
const std::set< std::pair< unsigned, llvm::MVT::SimpleValueType > > * TCETargetMachine::promotedOperations ()
Returns list of llvm::ISD SelectionDAG opcodes for operations that are not supported in the target architecture but will be promoted.
The returned operations have to be promoted to emulation function calls or emulation patterns in TCETargetLowering.
Definition at line 342 of file TCETargetMachine.cc.
{
    return &promotedOps_;
}
References promotedOps_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
raPortDRegNum()
unsigned llvm::TCETargetMachine::raPortDRegNum () const inline
Definition at line 235 of file TCETargetMachine.hh.
{
            return plugin_->raPortDRegNum();
        }
References plugin_, and llvm::TCETargetMachinePlugin::raPortDRegNum().
registerIndex()
unsigned llvm::TCETargetMachine::registerIndex (unsigned dwarfRegNum) const inline
Definition at line 212 of file TCETargetMachine.hh.
{
            return plugin_->registerIndex(dwarfRegNum);
        }
References plugin_, and llvm::TCETargetMachinePlugin::registerIndex().
Referenced by llvm::LLVMTCEBuilder::emitWriteSP(), and registerName().
registerName()
std::string llvm::TCETargetMachine::registerName (unsigned dwarfRegNum) const inline
Returns full name of the register.
Definition at line 220 of file TCETargetMachine.hh.
{
            return rfName(dwarfRegNum) + "."
                + std::to_string(registerIndex(dwarfRegNum));
        }
References registerIndex(), and rfName().
Referenced by llvm::LLVMTCEBuilder::emitInlineAsm(), InlineAsmParser::registerName(), and InlineAsmParser::substituteAsmString().
rfName()
std::string llvm::TCETargetMachine::rfName (unsigned dwarfRegNum) const inline
Definition at line 208 of file TCETargetMachine.hh.
{
            return plugin_->rfName(dwarfRegNum);
        }
References plugin_, and llvm::TCETargetMachinePlugin::rfName().
Referenced by llvm::LLVMTCEBuilder::emitWriteSP(), llvm::TCETargetLowering::hasI1RegisterClass(), and registerName().
setEmulationModule()
virtual void llvm::TCETargetMachine::setEmulationModule (Module * mod) inline virtual
Definition at line 131 of file TCETargetMachine.hh.
{
            emulationModule_ = mod;
        }
References emulationModule_.
Referenced by LLVMBackend::compile().
setStackAlignment()
void llvm::TCETargetMachine::setStackAlignment (unsigned align) inline
Definition at line 277 of file TCETargetMachine.hh.
{
            stackAlignment_ = align;
        }
References stackAlignment_.
Referenced by LLVMBackend::compile().
setTargetMachinePlugin()
void TCETargetMachine::setTargetMachinePlugin (TCETargetMachinePlugin & plugin, TTAMachine::Machine & target) virtual
Definition at line 175 of file TCETargetMachine.cc.
{
    setTTAMach(&target);
    plugin_ = &plugin;
    missingOps_.clear();
    promotedOps_.clear();
    MVT::SimpleValueType defType = plugin_->getDefaultType();
    if (!plugin_->hasSDIV()) missingOps_.insert(std::make_pair(llvm::ISD::SDIV, defType));
    if (!plugin_->hasUDIV()) missingOps_.insert(std::make_pair(llvm::ISD::UDIV, defType));
    if (!plugin_->hasSREM()) missingOps_.insert(std::make_pair(llvm::ISD::SREM, defType));
    if (!plugin_->hasUREM()) missingOps_.insert(std::make_pair(llvm::ISD::UREM, defType));
    if (!plugin_->hasMUL()) missingOps_.insert(std::make_pair(llvm::ISD::MUL, defType));
    if (!plugin_->hasROTL()) missingOps_.insert(std::make_pair(llvm::ISD::ROTL, defType));
    if (!plugin_->hasROTR()) missingOps_.insert(std::make_pair(llvm::ISD::ROTR, defType));
    if (!plugin_->hasSHL()) customLegalizedOps_.insert(std::make_pair(llvm::ISD::SHL, MVT::i32));
    if (!plugin_->hasSHR()) customLegalizedOps_.insert(std::make_pair(llvm::ISD::SRA, MVT::i32));
    if (!plugin_->hasSHRU()) customLegalizedOps_.insert(std::make_pair(llvm::ISD::SRL, MVT::i32));
    if (!plugin_->hasSXHW()) missingOps_.insert(
        std::make_pair(llvm::ISD::SIGN_EXTEND_INREG, MVT::i16));
    if (!plugin_->hasSXQW()) missingOps_.insert(
        std::make_pair(llvm::ISD::SIGN_EXTEND_INREG, MVT::i8));
    if (!plugin_->hasSQRTF()) {
        missingOps_.insert(std::make_pair(llvm::ISD::FSQRT, MVT::f32));
    }
    // register machine to plugin
    plugin_->registerTargetMachine(*this);
    initAsmInfo();
    // Set data layout with correct stack alignment.
    unsigned alignBits = MachineInfo::maxMemoryAlignment(target) * 8;
    TCEString dataLayoutStr("");
    if (plugin_->isLittleEndian()) {
        dataLayoutStr += target.is64bit() ? "e-p:64:64:64" : "e-p:32:32:32";
    } else {
        dataLayoutStr += "E-p:32:32:32";
    }
    dataLayoutStr += "-a0:0:" + Conversion::toString(alignBits);
    if (target.is64bit()) {
        dataLayoutStr += "-i1:8:64";
        dataLayoutStr += "-i8:8:64";
        dataLayoutStr += "-i16:16:64";
        dataLayoutStr += "-i32:32:64";
        dataLayoutStr += "-i64:64:64";
        dataLayoutStr += "-f16:16:64";
        dataLayoutStr += "-f32:32:64";
    } else {
        dataLayoutStr += "-i1:8:8";
        dataLayoutStr += "-i8:8:32";
        dataLayoutStr += "-i16:16:32";
        dataLayoutStr += "-i32:32:32";
        dataLayoutStr += "-i64:64:64";
        dataLayoutStr += "-f16:16:16";
        dataLayoutStr += "-f32:32:32";
    }
    dataLayoutStr += "-f64:64:64";
    dataLayoutStr += "-v64:64:64";
    dataLayoutStr += "-v128:128:128";
    dataLayoutStr += "-v256:256:256";
    dataLayoutStr += "-v512:512:512";
    dataLayoutStr += "-v1024:1024:1024";
#if LLVM_HAS_CUSTOM_VECTOR_EXTENSION == 2
    dataLayoutStr += "-v2048:2048:2048";
    dataLayoutStr += "-v4096:4096:4096";
#endif
    DataLayout* dl = plugin_->getDataLayout();
    dl->reset(dataLayoutStr.c_str());
}
References customLegalizedOps_, llvm::TCETargetMachinePlugin::getDataLayout(), llvm::TCETargetMachinePlugin::getDefaultType(), llvm::TCETargetMachinePlugin::hasMUL(), llvm::TCETargetMachinePlugin::hasROTL(), llvm::TCETargetMachinePlugin::hasROTR(), llvm::TCETargetMachinePlugin::hasSDIV(), llvm::TCETargetMachinePlugin::hasSHL(), llvm::TCETargetMachinePlugin::hasSHR(), llvm::TCETargetMachinePlugin::hasSHRU(), llvm::TCETargetMachinePlugin::hasSQRTF(), llvm::TCETargetMachinePlugin::hasSREM(), llvm::TCETargetMachinePlugin::hasSXHW(), llvm::TCETargetMachinePlugin::hasSXQW(), llvm::TCETargetMachinePlugin::hasUDIV(), llvm::TCETargetMachinePlugin::hasUREM(), TTAMachine::Machine::is64bit(), llvm::TCETargetMachinePlugin::isLittleEndian(), MachineInfo::maxMemoryAlignment(), missingOps_, plugin_, promotedOps_, llvm::TCETargetMachinePlugin::registerTargetMachine(), setTTAMach(), and Conversion::toString().
Referenced by LLVMBackend::compile().
setTTAMach()
virtual void llvm::TCETargetMachine::setTTAMach (const TTAMachine::Machine * mach) inline override virtual
Reimplemented from llvm::TCEBaseTargetMachine.
Definition at line 135 of file TCETargetMachine.hh.
{
            TCEBaseTargetMachine::setTTAMach(mach);
            calculateSupportedImmediates();
        }
References calculateSupportedImmediates(), and llvm::TCEBaseTargetMachine::setTTAMach().
Referenced by setTargetMachinePlugin().
smallestImmValue()
int64_t llvm::TCETargetMachine::smallestImmValue () const inline
Definition at line 314 of file TCETargetMachine.hh.
{
            assert(ttaMach_ && "setTargetMachinePlugin() was not called");
            return smallestImm_;
        }
References assert, smallestImm_, and llvm::TCEBaseTargetMachine::ttaMach_.
spDRegNum()
unsigned llvm::TCETargetMachine::spDRegNum () const inline
Definition at line 241 of file TCETargetMachine.hh.
{
            return plugin_->spDRegNum();
        }
References plugin_, and llvm::TCETargetMachinePlugin::spDRegNum().
Referenced by llvm::LLVMTCEBuilder::emitWriteSP().
stackAlignment()
unsigned llvm::TCETargetMachine::stackAlignment () const inline
Definition at line 281 of file TCETargetMachine.hh.
{
            if (stackAlignment_ == 0) {
                std::cerr << "ZERO STACK ALIGN\n";
                abort();
            }
            assert(stackAlignment_ > 0);
            return stackAlignment_;
        }
References assert, and stackAlignment_.
Referenced by llvm::LLVMTCEBuilder::emitSPInitialization(), llvm::LLVMTCEBuilder::initDataSections(), llvm::TCETargetLowering::LowerCall(), llvm::TCETargetLowering::LowerFormalArguments(), and llvm::GeneratedTCEPlugin::registerTargetMachine().
targetPlugin()
virtual TCETargetMachinePlugin & llvm::TCETargetMachine::targetPlugin () const inline virtual
Definition at line 124 of file TCETargetMachine.hh.
{ return *plugin_; }
References plugin_.
Referenced by ConstantTransformer::runOnMachineFunction().
ttaMachine()
virtual const TTAMachine::Machine & llvm::TCETargetMachine::ttaMachine () const inline virtual
Definition at line 141 of file TCETargetMachine.hh.
{
            return *ttaMach_;
        }
References llvm::TCEBaseTargetMachine::ttaMach_.
Referenced by InlineAsmParser::parse(), and llvm::TCETargetLowering::TCETargetLowering().
validStackAccessOperation()
bool llvm::TCETargetMachine::validStackAccessOperation (const std::string & opName) const inline
Returns true if LLVM opcode if valid for stack variable accesses.
Definition at line 200 of file TCETargetMachine.hh.
{
            return plugin_->validStackAccessOperation(opName);
        }
References plugin_, and llvm::TCETargetMachinePlugin::validStackAccessOperation().
Referenced by llvm::TCERegisterInfo::eliminateFrameIndex().
Member Data Documentation
customLegalizedOps_
std::set<std::pair<unsigned, llvm::MVT::SimpleValueType> > llvm::TCETargetMachine::customLegalizedOps_ private
Definition at line 339 of file TCETargetMachine.hh.
Referenced by customLegalizedOperations(), and setTargetMachinePlugin().
emulationModule_
Module* llvm::TCETargetMachine::emulationModule_
These two parameter passing should be rethought... maybe TTAMach can be avoided by changing pass to use plugin_ instead.
Definition at line 130 of file TCETargetMachine.hh.
Referenced by setEmulationModule().
largestImm_
uint64_t llvm::TCETargetMachine::largestImm_ = std::numeric_limits<int64_t>::min() private
Definition at line 344 of file TCETargetMachine.hh.
Referenced by calculateSupportedImmediates(), canEncodeAsMOVI(), and largestImmValue().
missingOps_
std::set<std::pair<unsigned, llvm::MVT::SimpleValueType> > llvm::TCETargetMachine::missingOps_ private
llvm::ISD opcode list of operations that have to be expanded.
Definition at line 337 of file TCETargetMachine.hh.
Referenced by missingOperations(), and setTargetMachinePlugin().
plugin_
TCETargetMachinePlugin* llvm::TCETargetMachine::plugin_ private
Definition at line 334 of file TCETargetMachine.hh.
Referenced by bitness(), canMaterializeConstant(), createPassConfig(), dataASName(), getAddOpcode(), getDataLayout(), getFrameLowering(), getInstrInfo(), getIorOpcode(), getLoadOpcode(), getMaxOpcode(), getMaxuOpcode(), getMinOpcode(), getMinuOpcode(), getRegisterInfo(), getShlOpcode(), getSubtargetImpl(), getSubtargetImpl(), getTargetLowering(), getTargetTransformInfo(), has16bitLoads(), has8bitLoads(), hasOperation(), llvmRegisterId(), opcode(), operationName(), raPortDRegNum(), registerIndex(), rfName(), setTargetMachinePlugin(), spDRegNum(), targetPlugin(), and validStackAccessOperation().
pluginTool_
PluginTools* llvm::TCETargetMachine::pluginTool_ private
Definition at line 335 of file TCETargetMachine.hh.
Referenced by ~TCETargetMachine().
promotedOps_
std::set<std::pair<unsigned, llvm::MVT::SimpleValueType> > llvm::TCETargetMachine::promotedOps_ private
Definition at line 338 of file TCETargetMachine.hh.
Referenced by promotedOperations(), and setTargetMachinePlugin().
smallestImm_
int64_t llvm::TCETargetMachine::smallestImm_ = std::numeric_limits<int64_t>::max() private
Definition at line 343 of file TCETargetMachine.hh.
Referenced by calculateSupportedImmediates(), canEncodeAsMOVI(), and smallestImmValue().
stackAlignment_
unsigned llvm::TCETargetMachine::stackAlignment_ private
Definition at line 348 of file TCETargetMachine.hh.
Referenced by setStackAlignment(), and stackAlignment().
SupportedFPImmWidth_
int llvm::TCETargetMachine::SupportedFPImmWidth_ = std::numeric_limits<int>::min() private
Definition at line 345 of file TCETargetMachine.hh.
Referenced by calculateSupportedImmediates(), and canEncodeAsMOVF().
The documentation for this class was generated from the following files:
TCETargetMachine.hh
TCETargetMachine.cc