OpenASIP: BFRegCopy Class Reference
BFRegCopy Class Reference abstract
#include <BFRegCopy.hh>
Public Member Functions
BFRegCopy (BF2Scheduler &sched, MoveNode &mn, int lc)
bool operator() ()
MoveNode * getRegCopy ()
void undoOnlyMe ()
void undoDDG ()
void createAntidepsForReg (MoveNode &firstMove, MoveNode &lastMove, const TTAMachine::RegisterFile &rf, int index, TCEString regName, BasicBlockNode &bbn, bool loopScheduling)
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
virtual bool splitMove (BasicBlockNode &bbn)=0
virtual void undoSplit ()=0
MoveNode * createRegCopy (bool after)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes
MoveNode & mn_
MoveNode * regCopy_
int lc_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 47 of file BFRegCopy.hh.
Constructor & Destructor Documentation
BFRegCopy()
BFRegCopy::BFRegCopy (BF2Scheduler & sched, MoveNode & mn, int lc) inline
Definition at line 49 of file BFRegCopy.hh.
                                                         :
        BFOptimization(sched), mn_(mn), lc_(lc) {}
Member Function Documentation
createAntidepsForReg()
void BFRegCopy::createAntidepsForReg (MoveNode & firstMove, MoveNode & lastMove, const TTAMachine::RegisterFile & rf, int index, TCEString regName, BasicBlockNode & bbn, bool loopScheduling)
Definition at line 99 of file BFRegCopy.cc.
{
    DataDependenceGraph::NodeSet firstScheduledDefs0 =
        ddg().firstScheduledRegisterWrites(rf, index);
    MoveNode* lastScheduledKill0 =
        ddg().lastScheduledRegisterKill(rf, index);
    for (auto i: firstScheduledDefs0) {
        if (!ddg().exclusingGuards(*i, useMove)) {
            DataDependenceEdge* war =
                new DataDependenceEdge(
                    DataDependenceEdge::EDGE_REGISTER,
                    DataDependenceEdge::DEP_WAR, regName);
            runPostChild(new BFConnectNodes(sched_, useMove, *i, war));
        }
        if (!ddg().exclusingGuards(*i, defMove)) {
            DataDependenceEdge* waw =
                new DataDependenceEdge(
                    DataDependenceEdge::EDGE_REGISTER,
                    DataDependenceEdge::DEP_WAW, regName);
            runPostChild(new BFConnectNodes(sched_, defMove, *i, waw));
        }
    }
    if (loopScheduling) {
        DataDependenceGraph::NodeSet lastScheduledReads0 =
            ddg().lastScheduledRegisterReads(rf, index);
        for (auto i: lastScheduledReads0) {
            if (!ddg().exclusingGuards(*i, defMove)) {
                DataDependenceEdge* war =
                    new DataDependenceEdge(
                        DataDependenceEdge::EDGE_REGISTER,
                        DataDependenceEdge::DEP_WAR, regName,
                        false, false, false, false, 1);
                runPostChild(new BFConnectNodes(sched_, *i, defMove, war));
            }
        }
        DataDependenceGraph::NodeSet lastScheduledDefs0 =
            ddg().lastScheduledRegisterWrites(rf, index);
        for (auto i: lastScheduledDefs0) {
            if (!ddg().exclusingGuards(*i, defMove)) {
                DataDependenceEdge* waw =
                    new DataDependenceEdge(
                        DataDependenceEdge::EDGE_REGISTER,
                        DataDependenceEdge::DEP_WAW, regName,
                        false, false, false, false, 1);
                runPostChild(new BFConnectNodes(sched_, *i, defMove, waw));
            }
        }
    }
    if (bbn.basicBlock().liveRangeData_ != NULL) {
        if (lastScheduledKill0 == NULL) {
            LiveRangeData::MoveNodeUseSet& lastWrites0 =
                bbn.basicBlock().liveRangeData_->regDefines_[regName];
            runPostChild(new BFInsertLiveRangeUse(
                             sched_, lastWrites0, MoveNodeUse(defMove)));
            LiveRangeData::MoveNodeUseSet& lastReads0 =
                    bbn.basicBlock().liveRangeData_->regLastUses_[regName];
                runPostChild(new BFInsertLiveRangeUse(
                                 sched_, lastReads0, MoveNodeUse(useMove)));
        }
        // last write, for WaW defs
        LiveRangeData::MoveNodeUseSet& firstDefs =
            bbn.basicBlock().liveRangeData_->regFirstDefines_[regName];
        if (useMove.move().isUnconditional()) {
            LiveRangeData::MoveNodeUseSet& firstReads =
                bbn.basicBlock().liveRangeData_->regFirstUses_[regName];
            runPostChild(new BFClearLiveRangeUse(sched_, firstReads));
            runPostChild(new BFClearLiveRangeUse(sched_, firstDefs));
            // TODO: what about updating the kill bookkeeping?
        }
        runPostChild(
            new BFInsertLiveRangeUse(
                sched_, firstDefs, MoveNodeUse(defMove)));
    }
}
References BasicBlockNode::basicBlock(), BFOptimization::ddg(), DataDependenceEdge::DEP_WAR, DataDependenceEdge::DEP_WAW, DataDependenceEdge::EDGE_REGISTER, DataDependenceGraph::exclusingGuards(), DataDependenceGraph::firstScheduledRegisterWrites(), TTAProgram::Move::isUnconditional(), DataDependenceGraph::lastScheduledRegisterKill(), DataDependenceGraph::lastScheduledRegisterReads(), DataDependenceGraph::lastScheduledRegisterWrites(), TTAProgram::BasicBlock::liveRangeData_, MoveNode::move(), LiveRangeData::regDefines_, LiveRangeData::regFirstDefines_, LiveRangeData::regFirstUses_, LiveRangeData::regLastUses_, Reversible::runPostChild(), and BFOptimization::sched_.
Referenced by BFRegCopyAfter::splitMove(), and BFRegCopyBefore::splitMove().
createRegCopy()
MoveNode * BFRegCopy::createRegCopy (bool after) protected
getRegCopy()
MoveNode * BFRegCopy::getRegCopy () inline
Definition at line 52 of file BFRegCopy.hh.
{ return regCopy_; }
References regCopy_.
Referenced by BFScheduleBU::operator()(), and BFScheduleExact::operator()().
operator()()
bool BFRegCopy::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 52 of file BFRegCopy.cc.
                      {
    if (mn_.move().isReturn()) {
        TTAProgram::ProgramAnnotation annotation(
            TTAProgram::ProgramAnnotation::ANN_STACKFRAME_PROCEDURE_RETURN);
        mn_.move().setAnnotation(annotation);
    }
    TTAProgram::ProgramAnnotation connMoveAnnotation(
        TTAProgram::ProgramAnnotation::ANN_CONNECTIVITY_MOVE);
    auto copyMove = mn_.move().copy();
    regCopy_ = new MoveNode(copyMove);
    BasicBlockNode& bbn = ddg().getBasicBlockNode(mn_);
    ddg().addNode(*regCopy_,bbn);
    copyMove->addAnnotation(connMoveAnnotation);
    if (splitMove(bbn)) {
        return true;
    }
    else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "Regcopy creation failing.." << std::endl;
#endif
        undoDDG();
        return false;
    }
}
References DataDependenceGraph::addNode(), TTAProgram::ProgramAnnotation::ANN_CONNECTIVITY_MOVE, TTAProgram::ProgramAnnotation::ANN_STACKFRAME_PROCEDURE_RETURN, TTAProgram::Move::copy(), BFOptimization::ddg(), DataDependenceGraph::getBasicBlockNode(), TTAProgram::Move::isReturn(), mn_, MoveNode::move(), regCopy_, TTAProgram::AnnotatedInstructionElement::setAnnotation(), splitMove(), and undoDDG().
splitMove()
virtual bool BFRegCopy::splitMove (BasicBlockNode & bbn) protected pure virtual
Implemented in BFCopyRegWithOp, BFRegCopyAfter, and BFRegCopyBefore.
Referenced by operator()().
undoDDG()
void BFRegCopy::undoDDG ()
Definition at line 86 of file BFRegCopy.cc.
{
    assert(!regCopy_->isScheduled());
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tUndid merge for copy for: " << mn_.toString()
              << " reg copy: " << regCopy_->toString() << std::endl;
#endif
    ddg().removeNode(*regCopy_);
    sched_.deletingNode(regCopy_);
    delete regCopy_;
}
References assert, BFOptimization::ddg(), BF2Scheduler::deletingNode(), MoveNode::isScheduled(), mn_, regCopy_, DataDependenceGraph::removeNode(), BFOptimization::sched_, and MoveNode::toString().
Referenced by operator()(), and undoOnlyMe().
undoOnlyMe()
void BFRegCopy::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 81 of file BFRegCopy.cc.
{
    undoSplit();
    undoDDG();
}
References undoDDG(), and undoSplit().
undoSplit()
virtual void BFRegCopy::undoSplit () protected pure virtual
Implemented in BFCopyRegWithOp, BFRegCopyAfter, and BFRegCopyBefore.
Referenced by undoOnlyMe().
Member Data Documentation
lc_
int BFRegCopy::lc_ protected
Definition at line 71 of file BFRegCopy.hh.
Referenced by BFRegCopyAfter::splitMove().
mn_
MoveNode& BFRegCopy::mn_ protected
Definition at line 69 of file BFRegCopy.hh.
Referenced by operator()(), BFCopyRegWithOp::splitMove(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), undoDDG(), BFCopyRegWithOp::undoSplit(), BFRegCopyAfter::undoSplit(), and BFRegCopyBefore::undoSplit().
regCopy_
MoveNode* BFRegCopy::regCopy_ protected
Definition at line 70 of file BFRegCopy.hh.
Referenced by getRegCopy(), operator()(), BFCopyRegWithOp::splitMove(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), undoDDG(), BFCopyRegWithOp::undoSplit(), BFRegCopyAfter::undoSplit(), and BFRegCopyBefore::undoSplit().
The documentation for this class was generated from the following files:
BFRegCopy.hh
BFRegCopy.cc