OpenASIP: OpcodeSettingVirtualInputPortState Class Reference
OpcodeSettingVirtualInputPortState Class Reference
#include <OpcodeSettingVirtualInputPortState.hh>
Public Member Functions
OpcodeSettingVirtualInputPortState (Operation &operation, OperationExecutor &executor, FUState &parent, InputPortState &real)
OpcodeSettingVirtualInputPortState (Operation &operation, FUState &parent, InputPortState &real)
virtual ~OpcodeSettingVirtualInputPortState ()
virtual void setValue (const SimValue &value)
virtual const SimValue & value () const
InputPortState * realPort () const
Public Member Functions inherited from InputPortState
InputPortState (FUState &parent, int width)
InputPortState (FUState &parent, SimValue &registerToUse)
virtual ~InputPortState ()
Public Member Functions inherited from PortState
PortState (FUState &parent, int width)
PortState (FUState &parent, SimValue &sharedRegister)
virtual ~PortState ()
virtual FUState & parent () const
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Private Member Functions
OpcodeSettingVirtualInputPortState (const OpcodeSettingVirtualInputPortState &)
Copying not allowed.
OpcodeSettingVirtualInputPortState & operator= (const OpcodeSettingVirtualInputPortState &)
Assignment not allowed.
Private Attributes
Operation & operation_
Operation of the port.
OperationExecutor * executor_
Operation executor used to execute the operation in the target FU, this is an optimization to avoid searching for the executor every time the operation is triggered.
InputPortState & real_
Real input port.
Additional Inherited Members
Protected Attributes inherited from PortState
FUState * parent_
Parent of the port.
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Operation setting input port state.
Port is virtual, that is it doesn't model real input port state. It has a pointer to the real port in which value is really set.
Definition at line 51 of file OpcodeSettingVirtualInputPortState.hh.
Constructor & Destructor Documentation
OpcodeSettingVirtualInputPortState() [1/3]
OpcodeSettingVirtualInputPortState::OpcodeSettingVirtualInputPortState (Operation & operation, OperationExecutor & executor, FUState & parent, InputPortState & real)
Constructor.
Parameters
Operation Operation of the port.
executor OperationExecutor to use to execute the operation when it's triggered.
parent Parent function unit.
real The real port in which this port belongs to.
Definition at line 68 of file OpcodeSettingVirtualInputPortState.cc.
                          :
    InputPortState(parent, real.value().width()),
    operation_(operation), executor_(&executor),
    real_(real) {
}
OpcodeSettingVirtualInputPortState() [2/3]
OpcodeSettingVirtualInputPortState::OpcodeSettingVirtualInputPortState (Operation & operation, FUState & parent, InputPortState & real)
Constructor.
Parameters
Operation Operation of the port.
parent Parent function unit.
real The real port in which this port belongs to.
Definition at line 50 of file OpcodeSettingVirtualInputPortState.cc.
                          :
    InputPortState(parent, real.value().width()),
    operation_(operation), executor_(NULL),
    real_(real) {
}
~OpcodeSettingVirtualInputPortState()
OpcodeSettingVirtualInputPortState::~OpcodeSettingVirtualInputPortState () virtual
Destructor.
Definition at line 82 of file OpcodeSettingVirtualInputPortState.cc.
{
}
OpcodeSettingVirtualInputPortState() [3/3]
OpcodeSettingVirtualInputPortState::OpcodeSettingVirtualInputPortState (const OpcodeSettingVirtualInputPortState &) private
Copying not allowed.
Member Function Documentation
operator=()
OpcodeSettingVirtualInputPortState & OpcodeSettingVirtualInputPortState::operator= (const OpcodeSettingVirtualInputPortState &) private
Assignment not allowed.
realPort()
InputPortState * OpcodeSettingVirtualInputPortState::realPort () const
Returns the real port.
Returns
The real port.
Definition at line 116 of file OpcodeSettingVirtualInputPortState.cc.
{
    return &real_;
}
References real_.
setValue()
void OpcodeSettingVirtualInputPortState::setValue (const SimValue & value) virtual
Sets the value of the port and sets operation to function unit.
Reimplemented from RegisterState.
Definition at line 89 of file OpcodeSettingVirtualInputPortState.cc.
{
    if (executor_ != NULL) {
        parent_->setOperation(operation_, *executor_);
    } else {
        parent_->setOperation(operation_);
    }
    parent_->setTriggered();
    real_.setValue(value);
}
References executor_, operation_, PortState::parent_, real_, FUState::setOperation(), FUState::setTriggered(), RegisterState::setValue(), and value().
value()
const SimValue & OpcodeSettingVirtualInputPortState::value () const virtual
Returns the value of the parent port.
Returns
The value of the parent port.
Reimplemented from RegisterState.
Definition at line 106 of file OpcodeSettingVirtualInputPortState.cc.
{
    return real_.value();
}
References real_, and RegisterState::value().
Referenced by setValue().
Member Data Documentation
executor_
OperationExecutor* OpcodeSettingVirtualInputPortState::executor_ private
Operation executor used to execute the operation in the target FU, this is an optimization to avoid searching for the executor every time the operation is triggered.
Definition at line 83 of file OpcodeSettingVirtualInputPortState.hh.
Referenced by setValue().
operation_
Operation& OpcodeSettingVirtualInputPortState::operation_ private
Operation of the port.
Definition at line 79 of file OpcodeSettingVirtualInputPortState.hh.
Referenced by setValue().
real_
InputPortState& OpcodeSettingVirtualInputPortState::real_ private
Real input port.
Definition at line 85 of file OpcodeSettingVirtualInputPortState.hh.
Referenced by realPort(), setValue(), and value().
The documentation for this class was generated from the following files:
OpcodeSettingVirtualInputPortState.hh
OpcodeSettingVirtualInputPortState.cc