OpenASIP: SocketCodeTable Class Reference
SocketCodeTable Class Reference
#include <SocketCodeTable.hh>
Public Member Functions
SocketCodeTable (const std::string &name, BinaryEncoding &parent)
SocketCodeTable (const ObjectState *state, BinaryEncoding &parent)
virtual ~SocketCodeTable ()
BinaryEncoding * parent () const
std::string name () const
void setName (const std::string &name)
void setExtraBits (int bits)
int extraBits () const
int width () const
int maxCodeWidth () const
void addFUPortCode (FUPortCode &code)
void removeFUPortCode (FUPortCode &code)
int fuPortCodeCount () const
FUPortCode & fuPortCode (int index) const
bool hasFUPortCode (const std::string &fu, const std::string &port) const
bool hasFUPortCode (const std::string &fu, const std::string &port, const std::string &operation) const
FUPortCode & fuPortCode (const std::string &fu, const std::string &port) const
FUPortCode & fuPortCode (const std::string &fu, const std::string &port, const std::string &operation) const
void addRFPortCode (RFPortCode &code)
void removeRFPortCode (RFPortCode &code)
int rfPortCodeCount () const
RFPortCode & rfPortCode (int index) const
bool hasRFPortCode (const std::string &regFile) const
RFPortCode & rfPortCode (const std::string &regFile) const
void addIUPortCode (IUPortCode &code)
void removeIUPortCode (IUPortCode &code)
int iuPortCodeCount () const
IUPortCode & iuPortCode (int index) const
bool hasIUPortCode (const std::string &immediateUnit) const
IUPortCode & iuPortCode (const std::string &immediateUnit) const
int portCodeCount () const
PortCode & portCode (int index) const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_SOCKET_CODE_TABLE = "sc_table"
ObjectState name for socket code table.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for name of the table.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Private Types
typedef std::vector< FUPortCode * > FUPortCodeTable
Container type for FU port codes.
typedef std::vector< RFPortCode * > RFPortCodeTable
Container type for RF port codes.
typedef std::vector< IUPortCode * > IUPortCodeTable
Container type for IU port codes.
Private Member Functions
void removeReferences (SlotField &field) const
bool hasParentSCTable (const std::string &name) const
void deleteRFPortCodes ()
void deleteFUPortCodes ()
void deleteIUPortCodes ()
bool hasRFOrIUPortCodeWithoutEncoding () const
bool containsPortCode () const
Private Attributes
BinaryEncoding * parent_
The parent binary encoding map.
std::string name_
Name of the table.
FUPortCodeTable fuPortCodes_
FU port codes.
RFPortCodeTable rfPortCodes_
RF port codes.
IUPortCodeTable iuPortCodes_
IU port codes.
int extraBits_
The number of extra bits.
Detailed Description
If a socket is attached to several ports, each port is identified by a different control code. This control code forms the variable part of the socket encoding and is defined by SocketCodeTable class.
The SocketCodeTable class contains objects that represent port control codes, namely FUPortCode, RFPortCode and IUPortCode. Because a single SocketCodeTable instance is shared by several socket encodings, it is not owned by SocketEncoding objects. Instead, socket code tables are owned by BinaryEncoding class, which provides methods to access and handle them.
Port codes consists of one or two parts: port ID and/or register index. Port IDs are aligned to the left end of the field and register indices to the right end. That is, if port ID + register index do not take all the bits of the width reserved for the table, there are unused bits between port ID and register index.
Definition at line 68 of file SocketCodeTable.hh.
Member Typedef Documentation
FUPortCodeTable
typedef std::vector<FUPortCode*> SocketCodeTable::FUPortCodeTable private
Container type for FU port codes.
Definition at line 129 of file SocketCodeTable.hh.
IUPortCodeTable
typedef std::vector<IUPortCode*> SocketCodeTable::IUPortCodeTable private
Container type for IU port codes.
Definition at line 133 of file SocketCodeTable.hh.
RFPortCodeTable
typedef std::vector<RFPortCode*> SocketCodeTable::RFPortCodeTable private
Container type for RF port codes.
Definition at line 131 of file SocketCodeTable.hh.
Constructor & Destructor Documentation
SocketCodeTable() [1/2]
SocketCodeTable::SocketCodeTable (const std::string & name, BinaryEncoding & parent)
The constructor.
Creates a code table and registers it to a binary encoding map.
Parameters
name Name of the table.
parent The encoding map.
Exceptions
ObjectAlreadyExists If the parent encoding map already contains a socket code table with the same name.
Definition at line 68 of file SocketCodeTable.cc.
    : parent_(NULL), name_(name), extraBits_(0) {
    parent.addSocketCodeTable(*this);
    parent_ = &parent;
}
References BinaryEncoding::addSocketCodeTable(), parent(), and parent_.
SocketCodeTable() [2/2]
SocketCodeTable::SocketCodeTable (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the table from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent binary encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 85 of file SocketCodeTable.cc.
    : parent_(&parent), name_(""), extraBits_(0) {
    loadState(state);
    parent_ = NULL;
    parent.addSocketCodeTable(*this);
    parent_ = &parent;
}
References BinaryEncoding::addSocketCodeTable(), loadState(), parent(), and parent_.
~SocketCodeTable()
SocketCodeTable::~SocketCodeTable () virtual
The destructor.
Removes the all the references to the socket code table from socket encodings.
Definition at line 100 of file SocketCodeTable.cc.
{
    BinaryEncoding* parent = this->parent();
    for (int i = 0; i < parent->moveSlotCount(); i++) {
    MoveSlot& slot = parent->moveSlot(i);
    SlotField& src = slot.sourceField();
    removeReferences(src);
    SlotField& dst = slot.destinationField();
    removeReferences(dst);
    }
    deleteRFPortCodes();
    deleteFUPortCodes();
    deleteIUPortCodes();
    parent_ = NULL;
    parent->removeSocketCodeTable(*this);
}
References deleteFUPortCodes(), deleteIUPortCodes(), deleteRFPortCodes(), MoveSlot::destinationField(), BinaryEncoding::moveSlot(), BinaryEncoding::moveSlotCount(), parent(), parent_, removeReferences(), BinaryEncoding::removeSocketCodeTable(), and MoveSlot::sourceField().
Member Function Documentation
addFUPortCode()
void SocketCodeTable::addFUPortCode (FUPortCode & code)
Adds the given control code that identifies a port of a function unit.
This method is to be called from the constructor of FUPortCode class.
Parameters
code The code to be added.
Exceptions
ObjectAlreadyExists If the port is already encoded in this table or if the encoding is ambiguous with other encodings in the socket code table.
Definition at line 249 of file SocketCodeTable.cc.
{
    const string procName = "SocketCodeTable::addFUPortCode";
    if (hasRFOrIUPortCodeWithoutEncoding()) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (!BEMTester::canAddPortEncoding(
        *this, code.encoding(), code.extraBits())) {
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (code.hasOperation()) {
    if (hasFUPortCode(
        code.unitName(), code.portName(), code.operationName())) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    } else {
    if (hasFUPortCode(code.unitName(), code.portName())) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    }
    fuPortCodes_.push_back(&code);
}
References BEMTester::canAddPortEncoding(), PortCode::encoding(), PortCode::extraBits(), fuPortCodes_, hasFUPortCode(), FUPortCode::hasOperation(), hasRFOrIUPortCodeWithoutEncoding(), FUPortCode::operationName(), FUPortCode::portName(), and PortCode::unitName().
Referenced by FUPortCode::FUPortCode(), FUPortCode::FUPortCode(), and FUPortCode::FUPortCode().
addIUPortCode()
void SocketCodeTable::addIUPortCode (IUPortCode & code)
Adds a control code that identifies an immediate unit.
In fact, the control code identifies a IU port, but which port is irrelevant, since all ports are identical and each must be attached to a different socket. This method is to be called from the constructor of IUPortCode class.
Parameters
code The control code to be added.
Exceptions
ObjectAlreadyExists If the register file is already encoded in this table or if the encoding is ambiguous with another encoding in the socket code table.
Definition at line 544 of file SocketCodeTable.cc.
{
    assert(code.parent() == NULL);
    const string procName = "SocketCodeTable::addIUPortCode";
    if (!code.hasEncoding() && containsPortCode()) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (code.hasEncoding()) {
        if (!BEMTester::canAddPortEncoding(
                *this, code.encoding(), code.extraBits())) {
            throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
        }
    }
    if (hasIUPortCode(code.unitName())) {
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    iuPortCodes_.push_back(&code);
}
References assert, BEMTester::canAddPortEncoding(), containsPortCode(), PortCode::encoding(), PortCode::extraBits(), PortCode::hasEncoding(), hasIUPortCode(), iuPortCodes_, PortCode::parent(), and PortCode::unitName().
Referenced by IUPortCode::IUPortCode(), IUPortCode::IUPortCode(), and IUPortCode::IUPortCode().
addRFPortCode()
void SocketCodeTable::addRFPortCode (RFPortCode & code)
Adds a control code that identifies a register file.
In fact, the control code identifies a RF port, but which port is irrelevant, since all ports are identical and each must be attached to a different socket. This method is to be called from the constructor of RFPortCode class.
Parameters
code The control code to be added.
Exceptions
ObjectAlreadyExists If the register file is already encoded in this table or if the encoding is ambiguous with another encoding in the socket code table.
Definition at line 428 of file SocketCodeTable.cc.
{
    assert(code.parent() == NULL);
    const string procName = "SocketCodeTable::addRFPortCode";
    if (!code.hasEncoding() && containsPortCode()) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (code.hasEncoding()) {
        if (!BEMTester::canAddPortEncoding(
                *this, code.encoding(), code.extraBits())) {
            throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
        }
    }
    if (hasRFPortCode(code.unitName())) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    rfPortCodes_.push_back(&code);
}
References assert, BEMTester::canAddPortEncoding(), containsPortCode(), PortCode::encoding(), PortCode::extraBits(), PortCode::hasEncoding(), hasRFPortCode(), PortCode::parent(), rfPortCodes_, and PortCode::unitName().
Referenced by RFPortCode::RFPortCode(), RFPortCode::RFPortCode(), and RFPortCode::RFPortCode().
containsPortCode()
bool SocketCodeTable::containsPortCode () const private
Tells whether the socket code table contains at least one port code.
Returns
True if the table contains at least one port code, otherwise false.
Definition at line 833 of file SocketCodeTable.cc.
{
    if (fuPortCodeCount() != 0 || rfPortCodeCount() != 0 ||
        iuPortCodeCount() != 0) {
        return true;
    } else {
        return false;
    }
}
References fuPortCodeCount(), iuPortCodeCount(), and rfPortCodeCount().
Referenced by addIUPortCode(), and addRFPortCode().
deleteFUPortCodes()
void SocketCodeTable::deleteFUPortCodes () private
Deletes all the FU port codes from the table.
Definition at line 793 of file SocketCodeTable.cc.
{
    SequenceTools::deleteAllItems(fuPortCodes_);
}
References SequenceTools::deleteAllItems(), and fuPortCodes_.
Referenced by loadState(), and ~SocketCodeTable().
deleteIUPortCodes()
void SocketCodeTable::deleteIUPortCodes () private
Deletes all the IU port codes from the table.
Definition at line 802 of file SocketCodeTable.cc.
{
    SequenceTools::deleteAllItems(iuPortCodes_);
}
References SequenceTools::deleteAllItems(), and iuPortCodes_.
Referenced by loadState(), and ~SocketCodeTable().
deleteRFPortCodes()
void SocketCodeTable::deleteRFPortCodes () private
Deletes all the RF port codes from the table.
Definition at line 784 of file SocketCodeTable.cc.
{
    SequenceTools::deleteAllItems(rfPortCodes_);
}
References SequenceTools::deleteAllItems(), and rfPortCodes_.
Referenced by loadState(), and ~SocketCodeTable().
extraBits()
int SocketCodeTable::extraBits () const
Returns the number of extra bits.
Returns
The number of extra bits.
Definition at line 189 of file SocketCodeTable.cc.
{
    return extraBits_;
}
References extraBits_.
Referenced by saveState(), and width().
fuPortCode() [1/3]
FUPortCode & SocketCodeTable::fuPortCode (const std::string & fu, const std::string & port) const
Returns the code for the given port of the given function unit.
Returns a NullFUPortCode instance if the requested code is not found.
Parameters
fu Name of the function unit.
port Name of the port.
Returns
The control code for the requested port.
Definition at line 365 of file SocketCodeTable.cc.
{
    int codes = fuPortCodeCount();
    for (int i = 0; i < codes; i++) {
    FUPortCode& code = fuPortCode(i);
    if (code.unitName() == fu && code.portName() == port &&
        !code.hasOperation()) {
        return code;
    }
    }
    return NullFUPortCode::instance();
}
References fuPortCode(), fuPortCodeCount(), FUPortCode::hasOperation(), NullFUPortCode::instance(), FUPortCode::portName(), and PortCode::unitName().
fuPortCode() [2/3]
FUPortCode & SocketCodeTable::fuPortCode (const std::string & fu, const std::string & port, const std::string & operation) const
Returns the code that identifies the given operation and the port that carries it.
Returns a NullFUPortCode instance if the requested code is not found.
Parameters
fu Name of the function unit.
port Name of the port.
operation Name of the operation.
Returns
The control code for the requested port.
Definition at line 394 of file SocketCodeTable.cc.
{
    int codes = fuPortCodeCount();
    for (int i = 0; i < codes; i++) {
    FUPortCode& code = fuPortCode(i);
    if (code.unitName() == fu && code.portName() == port &&
        code.hasOperation() &&
            StringTools::ciEqual(code.operationName(), operation)) {
            return code;
        }
    }
    return NullFUPortCode::instance();
}
References StringTools::ciEqual(), fuPortCode(), fuPortCodeCount(), FUPortCode::hasOperation(), NullFUPortCode::instance(), FUPortCode::operationName(), FUPortCode::portName(), and PortCode::unitName().
fuPortCode() [3/3]
FUPortCode & SocketCodeTable::fuPortCode (int index) const
Returns the FU port code stored at the given position in the table.
Parameters
index The position.
Exceptions
OutOfRange If the index is negative or not smaller than the number of FU port codes in the table.
Definition at line 308 of file SocketCodeTable.cc.
{
    if (index < 0 || index >= fuPortCodeCount()) {
    const string procName = "SocketCodeTable::fuPortCode";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *fuPortCodes_[index];
}
References fuPortCodeCount(), and fuPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), CodeCompressorPlugin::encodeFUTerminal(), fuPortCode(), fuPortCode(), hasFUPortCode(), hasFUPortCode(), maxCodeWidth(), portCode(), printSlotFieldEncodings(), saveState(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), and DefaultDecoderGenerator::writeControlRulesOfFUOutputPort().
fuPortCodeCount()
int SocketCodeTable::fuPortCodeCount () const
Returns the number of FU port codes in this table.
Returns
The number of FU port codes.
Definition at line 295 of file SocketCodeTable.cc.
{
    return fuPortCodes_.size();
}
References fuPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), containsPortCode(), fuPortCode(), fuPortCode(), fuPortCode(), maxCodeWidth(), portCode(), portCodeCount(), printSlotFieldEncodings(), and saveState().
hasFUPortCode() [1/2]
bool SocketCodeTable::hasFUPortCode (const std::string & fu, const std::string & port) const
Tells whether the table has a control code for the port of the function unit.
Parameters
fu Name of the function unit.
port Name of the port.
Returns
True if the table has the control code, otherwise false.
Definition at line 326 of file SocketCodeTable.cc.
{
    FUPortCode& code = fuPortCode(fu, port);
    return &code != &NullFUPortCode::instance();
}
References fuPortCode(), and NullFUPortCode::instance().
Referenced by addFUPortCode(), BEMValidator::checkSocketCodeTable(), and CodeCompressorPlugin::encodeFUTerminal().
hasFUPortCode() [2/2]
bool SocketCodeTable::hasFUPortCode (const std::string & fu, const std::string & port, const std::string & operation) const
Tells whether the table has a control code that identifies the given operation and the port that carries it.
Parameters
fu Name of the function unit.
port Name of the port.
operation Name of the operation.
Returns
True if the table has the control code, otherwise false.
Definition at line 345 of file SocketCodeTable.cc.
{
    FUPortCode& code = fuPortCode(fu, port, operation);
    return &code != &NullFUPortCode::instance();
}
References fuPortCode(), and NullFUPortCode::instance().
hasIUPortCode()
bool SocketCodeTable::hasIUPortCode (const std::string & immediateUnit) const
Tells whether the socket code table contains a control code for the given immediate unit.
Parameters
immediateUnit Name of the immediate unit.
Returns
True If the socket code table contains the control code, otherwise false.
Definition at line 618 of file SocketCodeTable.cc.
{
    return &iuPortCode(immediateUnit) != &NullIUPortCode::instance();
}
References NullIUPortCode::instance(), and iuPortCode().
Referenced by addIUPortCode(), BEMValidator::checkSocketCodeTable(), and CodeCompressorPlugin::encodeIUTerminal().
hasParentSCTable()
bool SocketCodeTable::hasParentSCTable (const std::string & name) const private
Tells whether the parent binary encoding table has a socket code table with the given name.
Parameters
name The name.
Returns
True if the parent has a socket code table with the given name, otherwise false.
Definition at line 768 of file SocketCodeTable.cc.
{
    BinaryEncoding* parent = this->parent();
    for (int i = 0; i < parent->socketCodeTableCount(); i++) {
        SocketCodeTable& table = parent->socketCodeTable(i);
        if (table.name() == name) {
            return true;
        }
    }
    return false;
}
References name(), parent(), BinaryEncoding::socketCodeTable(), and BinaryEncoding::socketCodeTableCount().
Referenced by setName().
hasRFOrIUPortCodeWithoutEncoding()
bool SocketCodeTable::hasRFOrIUPortCodeWithoutEncoding () const private
Tells whether the socket code table contains a RF or IU port code without port encoding.
Returns
True If the socket code table contains a RF or IU port code without port encoding, otherwise false.
Definition at line 815 of file SocketCodeTable.cc.
{
    if (rfPortCodeCount() == 1 && !rfPortCode(0).hasEncoding()) {
        return true;
    }
    if (iuPortCodeCount() == 1 && !iuPortCode(0).hasEncoding()) {
        return true;
    }
    return false;
}
References iuPortCode(), iuPortCodeCount(), rfPortCode(), and rfPortCodeCount().
Referenced by addFUPortCode().
hasRFPortCode()
bool SocketCodeTable::hasRFPortCode (const std::string & regFile) const
Tells whether the socket code table contains a control code for the given register file.
Parameters
regFile Name of the register file.
Returns
True If the socket code table contains the control code, otherwise false.
Definition at line 502 of file SocketCodeTable.cc.
{
    return &rfPortCode(regFile) != &NullRFPortCode::instance();
}
References NullRFPortCode::instance(), and rfPortCode().
Referenced by addRFPortCode(), BEMValidator::checkSocketCodeTable(), and CodeCompressorPlugin::encodeRFTerminal().
iuPortCode() [1/2]
IUPortCode & SocketCodeTable::iuPortCode (const std::string & immediateUnit) const
Returns the code for the given immediate unit.
Returns a NullIUPortCode instance if there is no code for the given register file in the table.
Parameters
immediateUnit Name of the immediate unit.
Definition at line 632 of file SocketCodeTable.cc.
{
    int codes = iuPortCodeCount();
    for (int i = 0; i < codes; i++) {
    IUPortCode& code = iuPortCode(i);
    if (code.unitName() == immediateUnit) {
        return code;
    }
    }
    return NullIUPortCode::instance();
}
References NullIUPortCode::instance(), iuPortCode(), iuPortCodeCount(), and PortCode::unitName().
iuPortCode() [2/2]
IUPortCode & SocketCodeTable::iuPortCode (int index) const
Returns the IU code stored at the given position.
Parameters
index The position.
Exceptions
OutOfRange If the index is negative or not smaller than the number of IU codes in this table.
Definition at line 600 of file SocketCodeTable.cc.
{
    if (index < 0 || index >= iuPortCodeCount()) {
        const string procName = "SocketCodeTable::iuPortCode";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *iuPortCodes_[index];
}
References iuPortCodeCount(), and iuPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), CodeCompressorPlugin::encodeIUTerminal(), hasIUPortCode(), hasRFOrIUPortCodeWithoutEncoding(), iuPortCode(), maxCodeWidth(), portCode(), printSlotFieldEncodings(), saveState(), and DefaultDecoderGenerator::writeControlRulesOfRFReadPort().
iuPortCodeCount()
int SocketCodeTable::iuPortCodeCount () const
Returns the number of immediate unit sources or destinations encoded in this table.
Returns
The number of immediate unit sources or destinations.
Definition at line 587 of file SocketCodeTable.cc.
{
    return iuPortCodes_.size();
}
References iuPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), containsPortCode(), hasRFOrIUPortCodeWithoutEncoding(), iuPortCode(), iuPortCode(), maxCodeWidth(), portCodeCount(), printSlotFieldEncodings(), and saveState().
loadState()
void SocketCodeTable::loadState (const ObjectState * state) virtual
Loads the state of the socket code table from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Definition at line 685 of file SocketCodeTable.cc.
{
    deleteFUPortCodes();
    deleteRFPortCodes();
    deleteIUPortCodes();
    try {
        setName(state->stringAttribute(OSKEY_NAME));
        setExtraBits(state->intAttribute(OSKEY_EXTRA_BITS));
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == FUPortCode::OSNAME_FU_PORT_CODE) {
                new FUPortCode(child, *this);
            } else if (child->name() == RFPortCode::OSNAME_RF_PORT_CODE) {
                new RFPortCode(child, *this);
            } else if (child->name() == IUPortCode::OSNAME_IU_PORT_CODE) {
                new IUPortCode(child, *this);
            }
        }
    } catch (const Exception& exception) {
        const string procName = "SocketCodeTable::loadState";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References ObjectState::child(), ObjectState::childCount(), deleteFUPortCodes(), deleteIUPortCodes(), deleteRFPortCodes(), ObjectState::intAttribute(), ObjectState::name(), OSKEY_EXTRA_BITS, OSKEY_NAME, FUPortCode::OSNAME_FU_PORT_CODE, IUPortCode::OSNAME_IU_PORT_CODE, RFPortCode::OSNAME_RF_PORT_CODE, setExtraBits(), setName(), and ObjectState::stringAttribute().
Referenced by SocketCodeTable().
maxCodeWidth()
int SocketCodeTable::maxCodeWidth () const
Returns the bit width of the longest control code.
This does not account the extra bits of the socket table.
Returns
The bit width.
Definition at line 212 of file SocketCodeTable.cc.
{
    int width(0);
    for (int i = 0; i < fuPortCodeCount(); i++) {
        FUPortCode& code = fuPortCode(i);
        if (width < code.width()) {
            width = code.width();
        }
    }
    for (int i = 0; i < rfPortCodeCount(); i++) {
        RFPortCode& code = rfPortCode(i);
        if (width < code.width()) {
            width = code.width();
        }
    }
    for (int i = 0; i < iuPortCodeCount(); i++) {
        IUPortCode& code = iuPortCode(i);
        if (width < code.width()) {
            width = code.width();
        }
    }
    return width;
}
References fuPortCode(), fuPortCodeCount(), iuPortCode(), iuPortCodeCount(), rfPortCode(), rfPortCodeCount(), PortCode::width(), and width().
Referenced by width().
name()
std::string SocketCodeTable::name () const
Returns the name of the socket code table.
Returns
The name.
Definition at line 137 of file SocketCodeTable.cc.
{
    return name_;
}
References name_.
Referenced by BinaryEncoding::addSocketCodeTable(), hasParentSCTable(), BinaryEncoding::hasSocketCodeTable(), saveState(), setName(), and BinaryEncoding::socketCodeTable().
parent()
BinaryEncoding * SocketCodeTable::parent () const
Returns the parent binary encoding map.
Returns
The parent binary encoding map.
Definition at line 126 of file SocketCodeTable.cc.
{
    return parent_;
}
References parent_.
Referenced by BinaryEncoding::addSocketCodeTable(), hasParentSCTable(), BinaryEncoding::removeSocketCodeTable(), SocketCodeTable(), SocketCodeTable(), and ~SocketCodeTable().
portCode()
PortCode & SocketCodeTable::portCode (int index) const
Returns the port code stored at the given position.
The possible kinds of port codes are FUPortCode, RFPortCode and IUPortCode.
Parameters
index The position.
Exceptions
OutOfRange If the index is negative or not smaller than the number of portCodeCount().
Definition at line 662 of file SocketCodeTable.cc.
{
    if (index < 0 || index >= portCodeCount()) {
        THROW_EXCEPTION(OutOfRange, "The given index is out of bounds. ");
    }
    if (index < fuPortCodeCount()) {
        return fuPortCode(index);
    } else if (index < fuPortCodeCount() + rfPortCodeCount()) {
        return rfPortCode(index - fuPortCodeCount());
    } else {
        return iuPortCode(index - fuPortCodeCount() - rfPortCodeCount());
    }
}
References fuPortCode(), fuPortCodeCount(), iuPortCode(), portCodeCount(), rfPortCode(), rfPortCodeCount(), and THROW_EXCEPTION.
Referenced by BEMTester::conflictsWithSocketTableEncodings().
portCodeCount()
int SocketCodeTable::portCodeCount () const
Returns count of all types of port codes defined in the socket table.
Definition at line 648 of file SocketCodeTable.cc.
{
    return fuPortCodeCount() + rfPortCodeCount() + iuPortCodeCount();
}
References fuPortCodeCount(), iuPortCodeCount(), and rfPortCodeCount().
Referenced by BEMTester::conflictsWithSocketTableEncodings(), and portCode().
removeFUPortCode()
void SocketCodeTable::removeFUPortCode (FUPortCode & code)
Removes the given FU port code from the socket code table.
This method is to be called from the destructor of FUPortCode class.
Parameters
code The code to be removed.
Definition at line 283 of file SocketCodeTable.cc.
{
    assert(code.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(fuPortCodes_, &code));
}
References assert, fuPortCodes_, PortCode::parent(), and ContainerTools::removeValueIfExists().
Referenced by FUPortCode::~FUPortCode().
removeIUPortCode()
void SocketCodeTable::removeIUPortCode (IUPortCode & code)
Removes the given IU port code.
This method is to be called from the destructor of IUPortCode.
Parameters
code The code to be removed.
Definition at line 574 of file SocketCodeTable.cc.
{
    assert(code.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(iuPortCodes_, &code));
}
References assert, iuPortCodes_, PortCode::parent(), and ContainerTools::removeValueIfExists().
Referenced by IUPortCode::~IUPortCode().
removeReferences()
void SocketCodeTable::removeReferences (SlotField & field) const private
Removes all the references to this socket code table from the socket encodings of the given slot field.
Definition at line 749 of file SocketCodeTable.cc.
{
    for (int i = 0; i < field.socketEncodingCount(); i++) {
        SocketEncoding& encoding = field.socketEncoding(i);
        if (&encoding.socketCodes() == this) {
            encoding.unsetSocketCodes();
        }
    }
}
References SocketEncoding::socketCodes(), SlotField::socketEncoding(), SlotField::socketEncodingCount(), and SocketEncoding::unsetSocketCodes().
Referenced by ~SocketCodeTable().
removeRFPortCode()
void SocketCodeTable::removeRFPortCode (RFPortCode & code)
Removes the given RF port code.
This method is to be called from the destructor of RFPortCode.
Parameters
code The code to be removed.
Definition at line 458 of file SocketCodeTable.cc.
{
    assert(code.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(rfPortCodes_, &code));
}
References assert, PortCode::parent(), ContainerTools::removeValueIfExists(), and rfPortCodes_.
Referenced by RFPortCode::~RFPortCode().
rfPortCode() [1/2]
RFPortCode & SocketCodeTable::rfPortCode (const std::string & regFile) const
Returns the code for the given register file.
Returns a NullRFPortCode instance if there is no code for the given register file in the table.
Parameters
regFile Name of the register file.
Definition at line 516 of file SocketCodeTable.cc.
{
    int codes = rfPortCodeCount();
    for (int i = 0; i < codes; i++) {
    RFPortCode& code = rfPortCode(i);
    if (code.unitName() == regFile) {
        return code;
    }
    }
    return NullRFPortCode::instance();
}
References NullRFPortCode::instance(), rfPortCode(), rfPortCodeCount(), and PortCode::unitName().
rfPortCode() [2/2]
RFPortCode & SocketCodeTable::rfPortCode (int index) const
Returns the RF code stored at the given position.
Parameters
index The position.
Exceptions
OutOfRange If the index is negative or not smaller than the number of RF codes in this table.
Definition at line 484 of file SocketCodeTable.cc.
{
    if (index < 0 || index >= rfPortCodeCount()) {
    const string procName = "SocketCodeTable::rfPortCode";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *rfPortCodes_[index];
}
References rfPortCodeCount(), and rfPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), CodeCompressorPlugin::encodeRFTerminal(), hasRFOrIUPortCodeWithoutEncoding(), hasRFPortCode(), maxCodeWidth(), portCode(), printSlotFieldEncodings(), rfPortCode(), saveState(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
rfPortCodeCount()
int SocketCodeTable::rfPortCodeCount () const
Returns the number of register file sources or destinations encoded in this table.
Returns
The number of register file sources or destinations.
Definition at line 471 of file SocketCodeTable.cc.
{
    return rfPortCodes_.size();
}
References rfPortCodes_.
Referenced by BEMTester::canAddPortEncoding(), containsPortCode(), hasRFOrIUPortCodeWithoutEncoding(), maxCodeWidth(), portCode(), portCodeCount(), printSlotFieldEncodings(), rfPortCode(), rfPortCode(), and saveState().
saveState()
ObjectState * SocketCodeTable::saveState () const virtual
Saves the state of the socket code table to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 716 of file SocketCodeTable.cc.
{
    ObjectState* state = new ObjectState(OSNAME_SOCKET_CODE_TABLE);
    state->setAttribute(OSKEY_NAME, name());
    state->setAttribute(OSKEY_EXTRA_BITS, extraBits());
    // add FU port codes
    for (int i = 0; i < fuPortCodeCount(); i++) {
        FUPortCode& code = fuPortCode(i);
        state->addChild(code.saveState());
    }
    // add RF port codes
    for (int i = 0; i < rfPortCodeCount(); i++) {
        RFPortCode& code = rfPortCode(i);
        state->addChild(code.saveState());
    }
    // add IU port codes
    for (int i = 0; i < iuPortCodeCount(); i++) {
        IUPortCode& code = iuPortCode(i);
        state->addChild(code.saveState());
    }
    return state;
}
References ObjectState::addChild(), extraBits(), fuPortCode(), fuPortCodeCount(), iuPortCode(), iuPortCodeCount(), name(), OSKEY_EXTRA_BITS, OSKEY_NAME, OSNAME_SOCKET_CODE_TABLE, rfPortCode(), rfPortCodeCount(), FUPortCode::saveState(), IUPortCode::saveState(), RFPortCode::saveState(), and ObjectState::setAttribute().
Referenced by BinaryEncoding::saveState().
setExtraBits()
void SocketCodeTable::setExtraBits (int bits)
Sets the number of extra zero bits for the table.
The bit width of the table can be forced longer than necessary by defining some number of extra zero bits that always exists in the right end of the table field.
Parameters
bits The number of extra zero bits.
Exceptions
OutOfRange If the given number is negative.
Definition at line 174 of file SocketCodeTable.cc.
{
    if (bits < 0) {
    const string procName = "SocketCodeTable::setExtraBits";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    extraBits_ = bits;
}
References extraBits_.
Referenced by loadState().
setName()
void SocketCodeTable::setName (const std::string & name)
Sets new name for the socket code table.
Parameters
name The new name.
Exceptions
ObjectAlreadyExists If the parent binary encoding map already has a socket code table with the same name.
Definition at line 150 of file SocketCodeTable.cc.
{
    if (name == this->name()) {
    return ;
    }
    if (hasParentSCTable(name)) {
    const string procName = "SocketCodeTable::setName";
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    name_ = name;
}
References hasParentSCTable(), name(), and name_.
Referenced by loadState().
width()
int SocketCodeTable::width () const
Returns the bit width of the control codes in the table.
Returns
The bit width.
Definition at line 200 of file SocketCodeTable.cc.
{
    return maxCodeWidth() + extraBits();
}
References extraBits(), and maxCodeWidth().
Referenced by BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeFUTerminal(), maxCodeWidth(), portCodeBits(), printSlotFieldEncodings(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), CodeCompressorPlugin::socketCodeBits(), SocketEncoding::socketCodePosition(), BEMGenerator::socketCodeWidthsForBus(), and SocketEncoding::width().
Member Data Documentation
extraBits_
int SocketCodeTable::extraBits_ private
The number of extra bits.
Definition at line 154 of file SocketCodeTable.hh.
Referenced by extraBits(), and setExtraBits().
fuPortCodes_
FUPortCodeTable SocketCodeTable::fuPortCodes_ private
FU port codes.
Definition at line 148 of file SocketCodeTable.hh.
Referenced by addFUPortCode(), deleteFUPortCodes(), fuPortCode(), fuPortCodeCount(), and removeFUPortCode().
iuPortCodes_
IUPortCodeTable SocketCodeTable::iuPortCodes_ private
IU port codes.
Definition at line 152 of file SocketCodeTable.hh.
Referenced by addIUPortCode(), deleteIUPortCodes(), iuPortCode(), iuPortCodeCount(), and removeIUPortCode().
name_
std::string SocketCodeTable::name_ private
Name of the table.
Definition at line 146 of file SocketCodeTable.hh.
Referenced by name(), and setName().
OSKEY_EXTRA_BITS
const std::string SocketCodeTable::OSKEY_EXTRA_BITS = "extra_bits" static
ObjectState attribute key for the number of extra bits.
Definition at line 125 of file SocketCodeTable.hh.
Referenced by loadState(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSKEY_NAME
const std::string SocketCodeTable::OSKEY_NAME = "name" static
ObjectState attribute key for name of the table.
Definition at line 123 of file SocketCodeTable.hh.
Referenced by loadState(), saveState(), BEMSerializer::socketCodeTableToFile(), and BEMSerializer::socketCodeTableToOM().
OSNAME_SOCKET_CODE_TABLE
const std::string SocketCodeTable::OSNAME_SOCKET_CODE_TABLE = "sc_table" static
ObjectState name for socket code table.
Definition at line 121 of file SocketCodeTable.hh.
Referenced by BEMSerializer::convertToFileFormat(), BinaryEncoding::loadState(), saveState(), and BEMSerializer::socketCodeTableToOM().
parent_
BinaryEncoding* SocketCodeTable::parent_ private
The parent binary encoding map.
Definition at line 144 of file SocketCodeTable.hh.
Referenced by parent(), SocketCodeTable(), SocketCodeTable(), and ~SocketCodeTable().
rfPortCodes_
RFPortCodeTable SocketCodeTable::rfPortCodes_ private
RF port codes.
Definition at line 150 of file SocketCodeTable.hh.
Referenced by addRFPortCode(), deleteRFPortCodes(), removeRFPortCode(), rfPortCode(), and rfPortCodeCount().
The documentation for this class was generated from the following files:
SocketCodeTable.hh
SocketCodeTable.cc