OpenASIP: ProgrammabilityValidatorResults Class Reference
ProgrammabilityValidatorResults Class Reference
#include <ProgrammabilityValidatorResults.hh>
Public Types
typedef std::pair< ProgrammabilityValidator::ErrorCode, std::string > Error
Typedef for an error (error code + error message).
Public Member Functions
ProgrammabilityValidatorResults ()
virtual ~ProgrammabilityValidatorResults ()
int errorCount () const
Error error (int index) const
void addError (ProgrammabilityValidator::ErrorCode code, const std::string &errorMsg)
Private Types
typedef std::vector< Error > ErrorTable
Typedef for vector of errors.
Private Attributes
ErrorTable errors_
Contains the errors.
Detailed Description
This class bundles up the results of ProgrammabilityValidator.
Definition at line 46 of file ProgrammabilityValidatorResults.hh.
Member Typedef Documentation
Error
typedef std::pair<ProgrammabilityValidator::ErrorCode, std::string> ProgrammabilityValidatorResults::Error
Typedef for an error (error code + error message).
Definition at line 50 of file ProgrammabilityValidatorResults.hh.
ErrorTable
typedef std::vector<Error> ProgrammabilityValidatorResults::ErrorTable private
Typedef for vector of errors.
Definition at line 64 of file ProgrammabilityValidatorResults.hh.
Constructor & Destructor Documentation
ProgrammabilityValidatorResults()
ProgrammabilityValidatorResults::ProgrammabilityValidatorResults ()
The constructor.
Definition at line 39 of file ProgrammabilityValidatorResults.cc.
{
}
~ProgrammabilityValidatorResults()
ProgrammabilityValidatorResults::~ProgrammabilityValidatorResults () virtual
The destructor.
Definition at line 46 of file ProgrammabilityValidatorResults.cc.
{
}
Member Function Documentation
addError()
void ProgrammabilityValidatorResults::addError (ProgrammabilityValidator::ErrorCode code, const std::string & errorMsg)
Adds an error to the results.
Parameters
code The error code.
errorMsg The error message.
Definition at line 85 of file ProgrammabilityValidatorResults.cc.
{
    Error error(code, errorMsg);
    errors_.push_back(error);
}
References error(), and errors_.
Referenced by ProgrammabilityValidator::checkBooleanRegister(), ProgrammabilityValidator::checkPrimitiveSet(), ProgrammabilityValidator::profile(), ProgrammabilityValidator::validate(), and ProgrammabilityValidator::validate().
error()
ProgrammabilityValidatorResults::Error ProgrammabilityValidatorResults::error (int index) const
Returns an error by the given index.
Parameters
index The index.
Returns
The error.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 70 of file ProgrammabilityValidatorResults.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return errors_[index];
}
References __func__, errorCount(), and errors_.
Referenced by addError(), main(), and ValidateMachineDialog::onValidate().
errorCount()
int ProgrammabilityValidatorResults::errorCount () const
Returns the number of errors.
Returns
The number of errors.
Definition at line 56 of file ProgrammabilityValidatorResults.cc.
{
    return errors_.size();
}
References errors_.
Referenced by error(), main(), and ValidateMachineDialog::onValidate().
Member Data Documentation
errors_
ErrorTable ProgrammabilityValidatorResults::errors_ private
Contains the errors.
Definition at line 67 of file ProgrammabilityValidatorResults.hh.
Referenced by addError(), error(), and errorCount().
The documentation for this class was generated from the following files:
ProgrammabilityValidatorResults.hh
ProgrammabilityValidatorResults.cc