OpenASIP: BFShareOperandsLate Class Reference
BFShareOperandsLate Class Reference
#include <BFShareOperandsLate.hh>
Public Member Functions
BFShareOperandsLate (BF2Scheduler &sched, MoveNode &mn)
virtual bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
virtual void undoOnlyMe ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Private Attributes
MoveNode & mn_
int operandShareDistance_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 42 of file BFShareOperandsLate.hh.
Constructor & Destructor Documentation
BFShareOperandsLate()
BFShareOperandsLate::BFShareOperandsLate (BF2Scheduler & sched, MoveNode & mn)
Definition at line 49 of file BFShareOperandsLate.cc.
                                                                          :
    BFOptimization(sched), mn_(mn), operandShareDistance_(6) {
    SchedulerCmdLineOptions* opts =
        dynamic_cast<SchedulerCmdLineOptions*>(Application::cmdLineOptions());
    if (opts != NULL) {
        if (opts->operandShareDistance() > -1) {
            operandShareDistance_ = opts->operandShareDistance();
        }
    }
}
References Application::cmdLineOptions(), SchedulerCmdLineOptions::operandShareDistance(), and operandShareDistance_.
Member Function Documentation
operator()()
bool BFShareOperandsLate::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 62 of file BFShareOperandsLate.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tTrying share operands late for: " << mn_.toString()
              << std::endl;
#endif
    TTAProgram::Move& currMove = mn_.move();
    TTAProgram::Terminal& currDest = currMove.destination();
    TTAProgram::Terminal& currSrc = currMove.source();
    if (currSrc.isImmediateRegister() ||
        currSrc.isFUPort()) {
        // lets not analyze yet when data in these change
        return false;
    }
    if (!currDest.isFUPort() ||
        currDest.isTriggering() ||
        currDest.isOpcodeSetting()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tdest not operand port" << std::endl;
#endif
        return false;
    }
//    TTAMachine::RegisterFile* guardRF = NULL;
//    int guardIndex = -1;
//    bool guardInverted = false;
    if (!currMove.isUnconditional()) {
        return false;
        /*
        TTAMachine::Guard& guard = move.guard().guard();
        RegisterGuard* rg = dynamic_cast<TTAMachine::RegisterGuard*>(&guard);
        if (rg) {
            guardRF = rg->registerFile();
            guardIndex = rg->registerIndex();
            guardInverted = rg->isInverted();
        }
        */
    }
    int cycle = mn_.cycle();
    unsigned int idx = rm().instructionIndex(cycle);
    unsigned int limit = ii() ? std::min(ii(), idx+operandShareDistance_) :
        std::min((unsigned)rm().largestCycle()+1, idx+operandShareDistance_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tidx: " << idx << " limit:" << limit << std::endl;
#endif
    for (unsigned int i = idx; i < limit; i++) {
        const TTAProgram::Instruction& ins = *rm().instruction(i);
        for (int j = 0; j < ins.moveCount(); j++) {
            const TTAProgram::Move& laterMove = ins.move(j);
            const TTAProgram::Terminal& laterDest = laterMove.destination();
            if (&laterMove == &currMove) {
                continue;
            }
            if (!laterDest.equals(currDest)) {
                continue;
            }
            const TTAProgram::Terminal& laterSrc = laterMove.source();
            if (laterSrc.equals(currSrc)) {
                MoveNode& laterNode = ddg().nodeOfMove(laterMove);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\t\t\tOriginal scheduled move: " << mn_.toString()
                          << std::endl;
                std::cerr << "\t\t\t\tLate op sharing Could remove later move: "
                          << laterNode.toString() << std::endl;
#endif
                BFShareOperandLate* bfsol =
                    new BFShareOperandLate(sched_,laterNode, mn_);
                return runPostChild(bfsol);
            } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\t\tAnother move overwrites my dest"
                          << ddg().nodeOfMove(laterMove).toString() << std::endl;
#endif
                return false;
            }
        }
        for (int j = 0; j < ins.moveCount(); j++) {
            TTAProgram::Move& laterMove = ins.move(j);
            TTAProgram::Terminal& laterDest = laterMove.destination();
            // src is overwritten here
            if (laterDest.equals(currSrc)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\t\tOverwrites src: " <<
                    ddg().nodeOfMove(laterMove).toString() << std::endl;
#endif
                return false;
            }
        }
    }
    return false;
}
References MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), TTAProgram::Terminal::equals(), BFOptimization::ii(), SimpleResourceManager::instruction(), SimpleResourceManager::instructionIndex(), TTAProgram::Terminal::isFUPort(), TTAProgram::Terminal::isImmediateRegister(), TTAProgram::Terminal::isOpcodeSetting(), TTAProgram::Terminal::isTriggering(), TTAProgram::Move::isUnconditional(), mn_, MoveNode::move(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), DataDependenceGraph::nodeOfMove(), operandShareDistance_, BFOptimization::rm(), Reversible::runPostChild(), BFOptimization::sched_, TTAProgram::Move::source(), and MoveNode::toString().
undoOnlyMe()
void BFShareOperandsLate::undoOnlyMe () protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 157 of file BFShareOperandsLate.cc.
{
}
Member Data Documentation
mn_
MoveNode& BFShareOperandsLate::mn_ private
Definition at line 49 of file BFShareOperandsLate.hh.
Referenced by operator()().
operandShareDistance_
int BFShareOperandsLate::operandShareDistance_ private
Definition at line 50 of file BFShareOperandsLate.hh.
Referenced by BFShareOperandsLate(), and operator()().
The documentation for this class was generated from the following files:
BFShareOperandsLate.hh
BFShareOperandsLate.cc