OpenASIP: ProximShowPortsCmd Class Reference
ProximShowPortsCmd Class Reference
#include <ProximShowPortsCmd.hh>
Public Member Functions
ProximShowPortsCmd (EditPart *part)
virtual ~ProximShowPortsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * part_
Detailed Description
Command for opening a function unit window displaying port state of a function unit.
Definition at line 45 of file ProximShowPortsCmd.hh.
Constructor & Destructor Documentation
ProximShowPortsCmd()
ProximShowPortsCmd::ProximShowPortsCmd (EditPart * part)
The Constructor.
Definition at line 42 of file ProximShowPortsCmd.cc.
                    :
    ComponentCommand(),
    part_(part) {
}
~ProximShowPortsCmd()
ProximShowPortsCmd::~ProximShowPortsCmd () virtual
The Destructor.
Definition at line 53 of file ProximShowPortsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximShowPortsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 64 of file ProximShowPortsCmd.cc.
                       {
    std::string fuName =
        dynamic_cast<TTAMachine::Component*>(part_->model())->name();
    ProximPortWindow* portWin =
        new ProximPortWindow(ProximToolbox::mainFrame(), -1);
    ProximToolbox::addFramedWindow(
        portWin, _T("Ports"), false, wxSize(270, 200));
    portWin->GetParent()->SetSize(270, 300);
    portWin->showFunctionUnit(fuName);
    return true;
}
References ProximToolbox::addFramedWindow(), ProximToolbox::mainFrame(), EditPart::model(), part_, and ProximPortWindow::showFunctionUnit().
Member Data Documentation
part_
EditPart* ProximShowPortsCmd::part_ private
Definition at line 52 of file ProximShowPortsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximShowPortsCmd.hh
ProximShowPortsCmd.cc