OpenASIP: CostEstimator::ICDecoderEstimatorPlugin Class Reference
CostEstimator::ICDecoderEstimatorPlugin Class Reference
#include <ICDecoderEstimatorPlugin.hh>
Public Member Functions
ICDecoderEstimatorPlugin (const std::string &name)
virtual ~ICDecoderEstimatorPlugin ()
virtual bool estimateICDelayOfPath (HDB::HDBRegistry &hdbRegistry, const TransportPath &path, const IDF::MachineImplementation &machineImplementation, const IDF::SocketImplementationLocation &sourceSocketImplementation, const IDF::BusImplementationLocation &busImplementation, const IDF::SocketImplementationLocation &destinationSocketImplementation, DelayInNanoSeconds &delay)
virtual bool estimateICArea (HDB::HDBRegistry &hdbRegistry, const TTAMachine::Machine &machine, const IDF::MachineImplementation &machineImplementation, AreaInGates &area)
virtual bool estimateICEnergy (HDB::HDBRegistry &hdbRegistry, const TTAMachine::Machine &machine, const IDF::MachineImplementation &machineImplementation, const TTAProgram::Program &program, const ExecutionTrace &traceDB, EnergyInMilliJoules &energy)
virtual TTAMachine::ControlUnit * generateControlUnit ()
Public Member Functions inherited from CostEstimator::CostEstimationPlugin
CostEstimationPlugin (const std::string &name)
virtual ~CostEstimationPlugin ()
virtual std::string name () const
virtual std::string description () const
Additional Inherited Members
Protected Attributes inherited from CostEstimator::CostEstimationPlugin
std::string name_
the name of the plugin class in the HDB; used to identify cost data
Detailed Description
Base class for plugins that are able to estimate costs of a IC and decoder combination.
Definition at line 64 of file ICDecoderEstimatorPlugin.hh.
Constructor & Destructor Documentation
ICDecoderEstimatorPlugin()
CostEstimator::ICDecoderEstimatorPlugin::ICDecoderEstimatorPlugin (const std::string & name)
Constructor.
Parameters
name The name of the cost estimation plugin in the HDB.
dataSource The HDB that stores the cost estimation data of the plugin. This reference can also be used to add new data, in case required by the algorithm.
Definition at line 49 of file ICDecoderEstimatorPlugin.cc.
                           :
    CostEstimationPlugin(name) {
}
~ICDecoderEstimatorPlugin()
CostEstimator::ICDecoderEstimatorPlugin::~ICDecoderEstimatorPlugin () virtual
Destructor.
Definition at line 57 of file ICDecoderEstimatorPlugin.cc.
{
}
Member Function Documentation
estimateICArea()
bool CostEstimator::ICDecoderEstimatorPlugin::estimateICArea (HDB::HDBRegistry & hdbRegistry, const TTAMachine::Machine & machine, const IDF::MachineImplementation & machineImplementation, AreaInGates & area) virtual
Estimates the area of the IC of the given machine.
Parameters
hdbRegistry The registry for accessing HDBs.
machine Architecture of the machine.
machineImplementation The implementation of the machine.
area The calculated area should be stored in this argument.
Returns
True in case the area can be estimated, false if it cannot.
Reimplemented in DefaultICDecoderEstimator.
Definition at line 102 of file ICDecoderEstimatorPlugin.cc.
                  {
    return false;
}
Referenced by CostEstimator::Estimator::icArea().
estimateICDelayOfPath()
bool CostEstimator::ICDecoderEstimatorPlugin::estimateICDelayOfPath (HDB::HDBRegistry & hdbRegistry, const TransportPath & path, const IDF::MachineImplementation & machineImplementation, const IDF::SocketImplementationLocation & sourceSocketImplementation, const IDF::BusImplementationLocation & busImplementation, const IDF::SocketImplementationLocation & destinationSocketImplementation, DelayInNanoSeconds & delay) virtual
Estimates the delay of the given path in the interconnection network.
The estimated path starts from source socket and traverses through a bus to a target socket. The delay caused by reading and writing from ports are not included in this value. The default implementation returns false to signal that the estimation functionality is not implemented by the plugin.
Parameters
hdbRegistry The registry for accessing HDBs.
path The path.
machineImplementation The implementation of the machine.
sourceSocketImplementation The implementation identification of the source socket.
busImplementation The implementation identification of the bus.
destinationSocketImplementation The implementation identification of the destination socket.
delay The calculated delay should be stored in this argument.
Returns
True in case the delay can be estimated, false if it cannot.
Reimplemented in DefaultICDecoderEstimator.
Definition at line 80 of file ICDecoderEstimatorPlugin.cc.
{
    return false;
}
Referenced by CostEstimator::Estimator::estimateSocketToSocketDelayOfPath().
estimateICEnergy()
bool CostEstimator::ICDecoderEstimatorPlugin::estimateICEnergy (HDB::HDBRegistry & hdbRegistry, const TTAMachine::Machine & machine, const IDF::MachineImplementation & machineImplementation, const TTAProgram::Program & program, const ExecutionTrace & traceDB, EnergyInMilliJoules & energy) virtual
Estimates the energy consumed by the IC of the given machine by running the given program.
Parameters
hdbRegistry The registry for accessing HDBs.
machine Architecture of the processor.
machineImplementation Implementation defintions of the processor.
traceDB The simulation trace database obtained from running the program.
energy The calculated energy should be stored in this argument.
Returns
True in case energy can be estimated, false if it cannot.
Reimplemented in DefaultICDecoderEstimator.
Definition at line 124 of file ICDecoderEstimatorPlugin.cc.
{
    return false;
}
Referenced by CostEstimator::Estimator::icEnergy().
generateControlUnit()
TTAMachine::ControlUnit * CostEstimator::ICDecoderEstimatorPlugin::generateControlUnit () virtual
Generates a control unit.
Returns
The control unit.
Definition at line 141 of file ICDecoderEstimatorPlugin.cc.
{
    const std::string RA_PORT_NAME = "ra";
    const std::string OP_PORT_NAME = "pc";
    const std::string OPNAME_JUMP = "jump";
    const std::string OPNAME_CALL = "call";
    const std::string COMP_DEFAULT_NAME_GCU = "gcu";
    // Add default ports.
    TTAMachine::ControlUnit* gcu = new TTAMachine::ControlUnit(
        COMP_DEFAULT_NAME_GCU, 3, 1);
    TTAMachine::FUPort* opPort =
        new TTAMachine::FUPort(OP_PORT_NAME, 32, *gcu, true, true);
    TTAMachine::SpecialRegisterPort* raPort =
        new TTAMachine::SpecialRegisterPort(RA_PORT_NAME, 32, *gcu);
    gcu->setReturnAddressPort(*raPort);
    // Add default operations.
    TTAMachine::HWOperation* jump =
        new TTAMachine::HWOperation(OPNAME_JUMP, *gcu);
    jump->bindPort(1, *opPort);
    jump->pipeline()->addPortRead(1, 0, 1);
    TTAMachine::HWOperation* call =
        new TTAMachine::HWOperation(OPNAME_CALL, *gcu);
    call->bindPort(1, *opPort);
    call->pipeline()->addPortRead(1, 0, 1);
    return gcu;
}
References TTAMachine::ExecutionPipeline::addPortRead(), TTAMachine::HWOperation::bindPort(), TTAMachine::HWOperation::pipeline(), and TTAMachine::ControlUnit::setReturnAddressPort().
The documentation for this class was generated from the following files:
ICDecoderEstimatorPlugin.hh
ICDecoderEstimatorPlugin.cc