OpenASIP: ProDeGCUEditPolicy Class Reference
ProDeGCUEditPolicy Class Reference
#include <ProDeGCUEditPolicy.hh>
Public Member Functions
ProDeGCUEditPolicy ()
virtual ~ProDeGCUEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ProDeGCUEditPolicy & operator= (ProDeGCUEditPolicy &old)
Assignment not allowed.
ProDeGCUEditPolicy (ProDeGCUEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a GCU EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports the Request.
Definition at line 50 of file ProDeGCUEditPolicy.hh.
Constructor & Destructor Documentation
ProDeGCUEditPolicy() [1/2]
ProDeGCUEditPolicy::ProDeGCUEditPolicy ()
The Constructor.
Definition at line 55 of file ProDeGCUEditPolicy.cc.
                                      : EditPolicy() {
}
~ProDeGCUEditPolicy()
ProDeGCUEditPolicy::~ProDeGCUEditPolicy () virtual
The Destructor.
Definition at line 61 of file ProDeGCUEditPolicy.cc.
{
}
ProDeGCUEditPolicy() [2/2]
ProDeGCUEditPolicy::ProDeGCUEditPolicy (ProDeGCUEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeGCUEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 108 of file ProDeGCUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
    type == Request::DELETE_REQUEST ||
        type == Request::COPY_REQUEST) {
    return true;
    } else {
    return false;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, Request::MODIFY_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProDeGCUEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 71 of file ProDeGCUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifyGCUCmd* modifyCmd = new ModifyGCUCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteGCUCmd* deleteCmd = new DeleteGCUCmd(host_);
        return deleteCmd;
    } else if (type == Request::COPY_REQUEST) {
        CopyComponent* copyCmd = new CopyComponent(host_);
        return copyCmd;
    } else if (type == Request::STATUS_REQUEST) {
        ControlUnit* gcu = dynamic_cast<ControlUnit*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_GCU);
        fmt % gcu->name();
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else {
    return NULL;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), ProDeTextGenerator::STATUS_GCU, Request::STATUS_REQUEST, Texts::TextGenerator::text(), and Request::type().
operator=()
ProDeGCUEditPolicy & ProDeGCUEditPolicy::operator= (ProDeGCUEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeGCUEditPolicy.hh
ProDeGCUEditPolicy.cc