OpenASIP: BoolCmdLineOptionParser Class Reference
BoolCmdLineOptionParser Class Reference
#include <CmdLineOptionParser.hh>
Public Member Functions
BoolCmdLineOptionParser (std::string name, std::string desc, std::string alias="", bool hidden=false)
virtual ~BoolCmdLineOptionParser ()
virtual OptionValue * copy () const
virtual bool parseValue (std::string arguments, std::string prefix)
virtual bool isFlagOn () const
virtual bool isFlagOff () const
Public Member Functions inherited from CmdLineOptionParser
CmdLineOptionParser (std::string name, std::string desc, std::string alias, bool hidden=false)
virtual ~CmdLineOptionParser ()
std::string longName () const
std::string shortName () const
std::string description () const
bool isHidden ()
bool isDefined ()
virtual int integer (int index=0) const
virtual unsigned unsignedInteger (int index=0) const
virtual std::string String (int index=0) const
virtual double real () const
virtual int listSize () const
Private Member Functions
BoolCmdLineOptionParser (const BoolCmdLineOptionParser &)
Copying not allowed.
BoolCmdLineOptionParser & operator= (const BoolCmdLineOptionParser &)
Assignment not allowed.
Private Attributes
bool value_
The value of option.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptionParser
void setDefined ()
Detailed Description
CmdLineOptionParser that has a boolean value.
This option is also called 'flag'.
Definition at line 278 of file CmdLineOptionParser.hh.
Constructor & Destructor Documentation
BoolCmdLineOptionParser() [1/2]
BoolCmdLineOptionParser::BoolCmdLineOptionParser (std::string name, std::string desc, std::string alias = "", bool hidden = false)
Constructor.
Parameters
name The name of the option.
desc The description of the option.
alias The short name of the option.
Definition at line 591 of file CmdLineOptionParser.cc.
                 :
    CmdLineOptionParser(name, desc, alias, hidden), value_(false) {
}
~BoolCmdLineOptionParser()
BoolCmdLineOptionParser::~BoolCmdLineOptionParser () virtual
Destructor.
Definition at line 602 of file CmdLineOptionParser.cc.
{
}
BoolCmdLineOptionParser() [2/2]
BoolCmdLineOptionParser::BoolCmdLineOptionParser (const BoolCmdLineOptionParser &) private
Copying not allowed.
Member Function Documentation
copy()
OptionValue * BoolCmdLineOptionParser::copy () const virtual
Copies the option value into a OptionValue object.
Client is responsible of deallocating the memeory reserved for the returned object.
Returns
A copy of the option value.
Implements CmdLineOptionParser.
Definition at line 614 of file CmdLineOptionParser.cc.
{
    BoolOptionValue* copy = new BoolOptionValue(value_);
    return copy;
}
References copy(), and value_.
Referenced by copy().
isFlagOff()
bool BoolCmdLineOptionParser::isFlagOff () const virtual
Returns true if the flag is not set.
Returns
Inverse of the boolean flag.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 666 of file CmdLineOptionParser.cc.
{
    return !value_;
}
References value_.
isFlagOn()
bool BoolCmdLineOptionParser::isFlagOn () const virtual
Returns true if the flag is set.
Returns
The boolean flag value.
Exceptions
WrongSubclass Is never thrown by this function.
Reimplemented from CmdLineOptionParser.
Definition at line 655 of file CmdLineOptionParser.cc.
{
    return value_;
}
References value_.
operator=()
BoolCmdLineOptionParser & BoolCmdLineOptionParser::operator= (const BoolCmdLineOptionParser &) private
Assignment not allowed.
parseValue()
bool BoolCmdLineOptionParser::parseValue (std::string arguments, std::string prefix) virtual
Parses the value of option.
Parameters
arguments The arguments for option.
prefix The prefix of option.
Returns
True if parsing is ready, otherwise false.
Exceptions
IllegalCommandLine If the prefix or arguments are invalid.
Implements CmdLineOptionParser.
Definition at line 628 of file CmdLineOptionParser.cc.
{
    if (prefix == "no-") {
        value_ = false;
    } else if (prefix == "") {
        value_ = true;
    } else {
        string msg = "Illegal prefix for boolean option " + longName() +
            ": " + prefix;
        string method = "BoolCmdLineOptionParser::parseValue()";
        throw IllegalCommandLine(__FILE__, __LINE__, method, msg);
    }
    if (arguments != "") {
        return false;
    } else {
        setDefined();
        return true;
    }
}
References CmdLineOptionParser::longName(), CmdLineOptionParser::setDefined(), and value_.
Member Data Documentation
value_
bool BoolCmdLineOptionParser::value_ private
The value of option.
Definition at line 300 of file CmdLineOptionParser.hh.
Referenced by copy(), isFlagOff(), isFlagOn(), and parseValue().
The documentation for this class was generated from the following files:
CmdLineOptionParser.hh
CmdLineOptionParser.cc