OpenASIP: DisassemblyGridTable Class Reference
DisassemblyGridTable Class Reference
#include <DisassemblyGridTable.hh>
Public Member Functions
DisassemblyGridTable ()
virtual ~DisassemblyGridTable ()
virtual int GetNumberRows ()
virtual int GetNumberCols ()
virtual bool IsEmptyCell (int row, int col)
virtual wxString GetValue (int row, int col)
virtual wxString GetRowLabelValue (int row)
virtual wxString GetColLabelValue (int col)
virtual void SetValue (int row, int col, const wxString &value)
virtual bool CanHaveAttributes ()
int rowOfAddress (Word address)
Word addressOfRow (int row)
void loadProgram (const TTAProgram::Program &program)
Protected Attributes
const TTAProgram::Program * program_
Program loaded in the table.
Private Types
typedef std::multimap< int, std::string > LabelMap
Type for the labels multimap.
Private Attributes
POMDisassembler * disassembler_
Disassembler for generating instruction disassemblies.
LabelMap labels_
Program labels.
Detailed Description
Grid table class which allows wxGrid to display disassembly of a tta program by disassembling only the currently visible instructions. Purpose of the 'lazy' disasembling is to conserve memory and processing time when the program is very large.
Definition at line 54 of file DisassemblyGridTable.hh.
Member Typedef Documentation
LabelMap
typedef std::multimap<int, std::string> DisassemblyGridTable::LabelMap private
Type for the labels multimap.
Definition at line 77 of file DisassemblyGridTable.hh.
Constructor & Destructor Documentation
DisassemblyGridTable()
DisassemblyGridTable::DisassemblyGridTable ()
The Constructor.
Definition at line 55 of file DisassemblyGridTable.cc.
                                          :
    wxGridTableBase(), program_(NULL), disassembler_(NULL) {
}
~DisassemblyGridTable()
DisassemblyGridTable::~DisassemblyGridTable () virtual
The Destructor.
Definition at line 64 of file DisassemblyGridTable.cc.
{
    if (disassembler_ != NULL) {
        delete disassembler_;
    }
}
References disassembler_.
Member Function Documentation
addressOfRow()
Word DisassemblyGridTable::addressOfRow (int row)
Returns address of the instruction on a row.
Parameters
row Row of the instruction.
Returns
Address of the instruction.
Definition at line 254 of file DisassemblyGridTable.cc.
{
    return (Word)row;
}
Referenced by ProximDisassemblyGridTable::GetAttr(), ProximDisassemblyWindow::onRightClick(), ProximDisassemblyWindow::onRunUntil(), ProximDisassemblyWindow::onSetBreakpoint(), and ProximDisassemblyWindow::onSetTempBp().
CanHaveAttributes()
bool DisassemblyGridTable::CanHaveAttributes () virtual
Returns true if the grid cells can have attributes.
Returns
Always true.
Definition at line 204 of file DisassemblyGridTable.cc.
{
    return true;
}
GetColLabelValue()
wxString DisassemblyGridTable::GetColLabelValue (int col) virtual
Returns column label of a grid column.
Parameters
col Column number.
Returns
Label for the grid column.
Reimplemented in ProximDisassemblyGridTable.
Definition at line 180 of file DisassemblyGridTable.cc.
{
    int busCount = program_->targetProcessor().busNavigator().count();
    if (col > 0 && col < (busCount + 1)) {
        const TTAMachine::Machine::BusNavigator& navigator =
            program_->targetProcessor().busNavigator();
        string label = Conversion::toString(col - 1);
        label += ": ";
        label += navigator.item(col - 1)->name();
        return WxConversion::toWxString(label);
    } else {
        return _T("");
    }
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), program_, TTAProgram::Program::targetProcessor(), Conversion::toString(), and WxConversion::toWxString().
Referenced by ProximDisassemblyGridTable::GetColLabelValue().
GetNumberCols()
int DisassemblyGridTable::GetNumberCols () virtual
Returns column count of the grid.
Returns
Number of coulmns in the table.
Reimplemented in ProximDisassemblyGridTable.
Definition at line 92 of file DisassemblyGridTable.cc.
{
    int busCount = program_->targetProcessor().busNavigator().count();
    int immSlotCount =
        program_->targetProcessor().immediateSlotNavigator().count();
    return busCount + immSlotCount + 1;
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateSlotNavigator(), program_, and TTAProgram::Program::targetProcessor().
Referenced by ProximDisassemblyGridTable::GetNumberCols().
GetNumberRows()
int DisassemblyGridTable::GetNumberRows () virtual
Returns row count of the grid.
The row count is limited to MAX_ROWS due to limtiations of wxGrid.
Returns
Number of rows in the table.
Reimplemented in ProximDisassemblyGridTable.
Definition at line 79 of file DisassemblyGridTable.cc.
{
    Word firstAddress = program_->firstInstruction().address().location();
    Word lastAddress = program_->lastInstruction().address().location();
    return lastAddress - firstAddress + 1;
}
References TTAProgram::Instruction::address(), TTAProgram::Program::firstInstruction(), TTAProgram::Program::lastInstruction(), TTAProgram::Address::location(), and program_.
Referenced by ProximDisassemblyGridTable::GetNumberRows().
GetRowLabelValue()
wxString DisassemblyGridTable::GetRowLabelValue (int row) virtual
Returns row label of a grid row.
Parameters
row Row number.
Returns
Label for the grid row.
Definition at line 168 of file DisassemblyGridTable.cc.
{
    return WxConversion::toWxString(row);
}
References WxConversion::toWxString().
GetValue()
wxString DisassemblyGridTable::GetValue (int row, int col) virtual
Returns cell value as a wxString.
Parameters
row Row of the cell.
col Column of the cell.
Returns
Cell contents as a wxString.
Reimplemented in ProximDisassemblyGridTable.
Definition at line 121 of file DisassemblyGridTable.cc.
{
    int busCount = program_->targetProcessor().busNavigator().count();
    if (col == 0) {
        wxString labels = WxConversion::toWxString("");
        std::pair<LabelMap::iterator, LabelMap::iterator> range =
            labels_.equal_range(row);
        LabelMap::iterator firstEqual = range.first;
        LabelMap::iterator lastEqual = range.second;
        while (firstEqual != lastEqual) {
                labels += WxConversion::toWxString(firstEqual->second)
                       + WxConversion::toWxString(" ");
                firstEqual++;
            }
            return labels;
    } else if (col > 0) {
        Word address = (Word) row;
        DisassemblyInstruction* disassembly =
            disassembler_->createInstruction(address);
        wxString disasm;
        if (col < (busCount + 1)) {
            disasm = WxConversion::toWxString(
                disassembly->move(col - 1).toString());
        } else {
            int immCount = static_cast<int>(disassembly->longImmediateCount());
            if (col < (busCount + 1 + immCount)) {
                disasm = WxConversion::toWxString(
                    disassembly->longImmediate(col - 1 - busCount).toString());
            }
        }
        delete disassembly;
        return disasm;
    }
    return _T("");
}
References TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), POMDisassembler::createInstruction(), disassembler_, labels_, DisassemblyInstruction::longImmediate(), DisassemblyInstruction::longImmediateCount(), DisassemblyInstruction::move(), program_, TTAProgram::Program::targetProcessor(), DisassemblyImmediateAssignment::toString(), DisassemblyInstructionSlot::toString(), and WxConversion::toWxString().
Referenced by ProximDisassemblyGridTable::GetValue().
IsEmptyCell()
bool DisassemblyGridTable::IsEmptyCell (int row, int col) virtual
Returns true, if the given cell is empty, false otherwise.
Parameters
row Row of the cell.
col Column of the cell.
Returns
True, if the column is empty.
Definition at line 108 of file DisassemblyGridTable.cc.
{
    return false;
}
loadProgram()
void DisassemblyGridTable::loadProgram (const TTAProgram::Program & program)
Loads a new program in the grid table.
Parameters
program Program to load.
Definition at line 224 of file DisassemblyGridTable.cc.
{
    program_ = &program;
    if (disassembler_ != NULL) {
        delete disassembler_;
    }
    disassembler_ = new POMDisassembler(program);
    labels_.clear();
    const GlobalScope& gScope = program_->globalScopeConst();
    int labelCount = gScope.globalCodeLabelCount();
    for (int i = 0; i < labelCount; i++) {
        const CodeLabel& codeLabel = gScope.globalCodeLabel(i);
        unsigned address = codeLabel.address().location();
        std::string label = codeLabel.name();
        labels_.insert(std::pair<unsigned, string>(address, label));
    }
}
References TTAProgram::CodeLabel::address(), disassembler_, TTAProgram::GlobalScope::globalCodeLabel(), TTAProgram::GlobalScope::globalCodeLabelCount(), TTAProgram::Program::globalScopeConst(), labels_, TTAProgram::Address::location(), TTAProgram::Label::name(), program, and program_.
Referenced by ProximDisassemblyWindow::loadProgram().
rowOfAddress()
int DisassemblyGridTable::rowOfAddress (Word address)
Returns row of the instruction with given address.
Parameters
address Address of the instruction.
Returns
Row of the instruction.
Definition at line 266 of file DisassemblyGridTable.cc.
{
    return (int)address;
}
Referenced by ProximDisassemblyWindow::showAddress().
SetValue()
void DisassemblyGridTable::SetValue (int row, int col, const wxString & value) virtual
Not implemented, use setCellValue() instead.
Definition at line 213 of file DisassemblyGridTable.cc.
{
    // Do nothing.
}
Member Data Documentation
disassembler_
POMDisassembler* DisassemblyGridTable::disassembler_ private
Disassembler for generating instruction disassemblies.
Definition at line 74 of file DisassemblyGridTable.hh.
Referenced by GetValue(), loadProgram(), and ~DisassemblyGridTable().
labels_
LabelMap DisassemblyGridTable::labels_ private
Program labels.
Definition at line 80 of file DisassemblyGridTable.hh.
Referenced by GetValue(), and loadProgram().
program_
const TTAProgram::Program* DisassemblyGridTable::program_ protected
Program loaded in the table.
Definition at line 71 of file DisassemblyGridTable.hh.
Referenced by GetColLabelValue(), GetNumberCols(), GetNumberRows(), GetValue(), and loadProgram().
The documentation for this class was generated from the following files:
DisassemblyGridTable.hh
DisassemblyGridTable.cc