OpenASIP: InfoCommand Class Reference
InfoCommand Class Reference
#include <InfoCommand.hh>
Public Member Functions
InfoCommand (bool isCompiledSimulation=false)
virtual ~InfoCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Protected Types
typedef std::map< std::string, SimControlLanguageSubCommand * > SubCommandMap
container type for subcommands indexed by name
Protected Attributes
SubCommandMap subCommands_
storage for subcommands
bool isCompiledSimulation_
Is it a compiled simulation?
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "info" command of the Simulator Control Language.
Definition at line 48 of file InfoCommand.hh.
Member Typedef Documentation
SubCommandMap
typedef std::map<std::string, SimControlLanguageSubCommand*> InfoCommand::SubCommandMap protected
container type for subcommands indexed by name
Definition at line 57 of file InfoCommand.hh.
Constructor & Destructor Documentation
InfoCommand()
InfoCommand::InfoCommand (bool isCompiledSimulation = false)
Constructor.
Sets the name of the command to the base class.
Definition at line 1415 of file InfoCommand.cc.
                                                  :
    SimControlLanguageCommand("info"),
    isCompiledSimulation_(isCompiledSimulation) {
    if (!isCompiledSimulation_) {
        subCommands_["breakpoints"] = new InfoBreakpointsCommand(*this);
        subCommands_["busses"] = new InfoBussesCommand(*this);
        subCommands_["segments"] = new InfoSegmentsCommand(*this);
    }
    subCommands_["stats"] = new InfoStatsCommand(*this);
    subCommands_["registers"] = new InfoRegistersCommand(*this);
    subCommands_["proc"] = new InfoProcCommand(*this);
    subCommands_["program"] = new InfoProgramCommand(*this);
    subCommands_["watches"] = new InfoBreakpointsCommand(*this);
    subCommands_["regfiles"] = new InfoRegFilesCommand(*this);
    subCommands_["iunits"] = new InfoIunitsCommand(*this);
    subCommands_["funits"] = new InfoFunitsCommand(*this);
    subCommands_["ports"] = new InfoPortsCommand(*this);
    subCommands_["immediates"] = new InfoImmediatesCommand(*this);
}
References isCompiledSimulation_, and subCommands_.
~InfoCommand()
InfoCommand::~InfoCommand () virtual
Destructor.
Definition at line 1440 of file InfoCommand.cc.
{
    MapTools::deleteAllValues(subCommands_);
}
References MapTools::deleteAllValues(), and subCommands_.
Member Function Documentation
execute()
bool InfoCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "info" command.
Provides various information of the simulation.
Parameters
arguments Subcommand and possible arguments to the subcommand.
Returns
Always true if arguments are valid.
Implements CustomCommand.
Definition at line 1453 of file InfoCommand.cc.
{
    assert(interpreter() != NULL);
    // "info" as such does not do anything, a subcommand is required.
    if (!checkArgumentCount(arguments.size() - 1, 1, INT_MAX)) {
        return false;
    }
    SubCommandMap::iterator subCommandPosition =
        subCommands_.find(
            StringTools::stringToLower(arguments.at(1).stringValue()));
    if (subCommandPosition == subCommands_.end()) {
        interpreter()->setError(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_UNKNOWN_SUBCOMMAND).str());
        return false;
    }
    assert((*subCommandPosition).second != NULL);
    SimControlLanguageSubCommand& subCommand = *((*subCommandPosition).second);
    return subCommand.execute(arguments);
}
References assert, CustomCommand::checkArgumentCount(), SimControlLanguageSubCommand::execute(), CustomCommand::interpreter(), ScriptInterpreter::setError(), StringTools::stringToLower(), subCommands_, SimulatorToolbox::textGenerator(), and Texts::TXT_UNKNOWN_SUBCOMMAND.
helpText()
std::string InfoCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Implements CustomCommand.
Definition at line 1485 of file InfoCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_INFO).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_INFO.
Member Data Documentation
isCompiledSimulation_
bool InfoCommand::isCompiledSimulation_ protected
Is it a compiled simulation?
Definition at line 62 of file InfoCommand.hh.
Referenced by InfoCommand().
subCommands_
SubCommandMap InfoCommand::subCommands_ protected
storage for subcommands
Definition at line 59 of file InfoCommand.hh.
Referenced by execute(), InfoCommand(), and ~InfoCommand().
The documentation for this class was generated from the following files:
InfoCommand.hh
InfoCommand.cc