OpenASIP: DeleteBridgeCmd Class Reference
DeleteBridgeCmd Class Reference
#include <DeleteBridgeCmd.hh>
Public Member Functions
DeleteBridgeCmd (EditPart *editPart)
virtual ~DeleteBridgeCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * editPart_
Bridge to delete.
Detailed Description
Command for deleting bridges from the Machine.
Definition at line 44 of file DeleteBridgeCmd.hh.
Constructor & Destructor Documentation
DeleteBridgeCmd()
DeleteBridgeCmd::DeleteBridgeCmd (EditPart * editPart)
The Constructor.
Parameters
editPart Bridge to delete.
Definition at line 46 of file DeleteBridgeCmd.cc.
                                                  :
    ComponentCommand(),
    editPart_(editPart) {
}
~DeleteBridgeCmd()
DeleteBridgeCmd::~DeleteBridgeCmd () virtual
The Destructor.
Definition at line 55 of file DeleteBridgeCmd.cc.
{
}
Member Function Documentation
Do()
bool DeleteBridgeCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 65 of file DeleteBridgeCmd.cc.
                    {
    if (editPart_->childCount() == 0) {
        Bridge* bridge = dynamic_cast<Bridge*>(editPart_->model());
        assert (bridge != NULL);
    delete bridge;
        bridge = NULL;
    } else {
        // bidirectional bridge
        assert(editPart_->childCount() == 2);
        // delete bridges of both direction
        for (int i = 0; i < editPart_->childCount(); i++) {
            Bridge* bridge =
                dynamic_cast<Bridge*>(editPart_->child(i)->model());
            assert (bridge != NULL);
        delete bridge;
            bridge = NULL;
        }
    }
    return true;
}
References assert, EditPart::child(), EditPart::childCount(), editPart_, and EditPart::model().
Member Data Documentation
editPart_
EditPart* DeleteBridgeCmd::editPart_ private
Bridge to delete.
Definition at line 52 of file DeleteBridgeCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
DeleteBridgeCmd.hh
DeleteBridgeCmd.cc