OpenASIP: TTAMachine::Segment Class Reference
TTAMachine::Segment Class Reference
#include <Segment.hh>
Public Member Functions
Segment (const std::string &name, Bus &parent)
Segment (const ObjectState *state, Bus &parent)
~Segment ()
void setName (const std::string &name)
std::string name () const
void attachSocket (Socket &socket)
void detachSocket (Socket &socket)
void detachAllSockets ()
bool isConnectedTo (const Socket &socket) const
const Connection & connection (const Socket &socket) const
Socket * connection (int index) const
int connectionCount () const
Bus * parentBus () const
void moveBefore (Segment &segment)
void moveAfter (Segment &segment)
bool hasSourceSegment () const
bool hasDestinationSegment () const
Segment * sourceSegment () const
Segment * destinationSegment () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_SEGMENT = "segment"
ObjectState name for Segment.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for segment name.
static const std::string OSKEY_DESTINATION = "destination"
ObjectState attribute key for destination segment name.
Private Types
typedef std::vector< const Connection * > ConnectionTable
Vector of Connection pointers.
Private Member Functions
void loadStateWithoutReferences (const ObjectState *state)
void removeConnection (const Connection *connection)
Private Attributes
std::string name_
Name of the segment.
Bus * parent_
The parent bus.
Segment * sourceSegment_
Source segment.
Segment * destinationSegment_
Destination segment.
ConnectionTable connections_
Contains all the connections to sockets.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents a segment of a bus.
Definition at line 54 of file Segment.hh.
Member Typedef Documentation
ConnectionTable
typedef std::vector<const Connection*> TTAMachine::Segment::ConnectionTable private
Vector of Connection pointers.
Definition at line 95 of file Segment.hh.
Constructor & Destructor Documentation
Segment() [1/2]
TTAMachine::Segment::Segment (const std::string & name, Bus & parent)
Constructor.
The segment is appended at the end of the segment chain of its parent bus.
Parameters
name Name of the segment.
parent The bus this segment belongs to (parent bus).
Exceptions
ComponentAlreadyExists If a segment with the same name already exists in the same segment chain.
InvalidName If the given name is not a valid component name.
Definition at line 70 of file Segment.cc.
    : name_(name),
      parent_(NULL),
      sourceSegment_(NULL),
      destinationSegment_(NULL) {
    if (!MachineTester::isValidComponentName(name)) {
        const string procName = "Segment::Segment";
        throw InvalidName(__FILE__, __LINE__, procName);
    }
    parent.addSegment(*this);
    parent_ = &parent;
    for (int i = 0; i < parent.segmentCount(); i++) {
        Segment* segment = parent.segment(i);
        if (segment->destinationSegment_ == NULL && segment != this) {
            segment->destinationSegment_ = this;
            sourceSegment_ = segment;
            break;
        }
    }
}
References TTAMachine::Bus::addSegment(), destinationSegment_, MachineTester::isValidComponentName(), name(), parent_, TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), and sourceSegment_.
Segment() [2/2]
TTAMachine::Segment::Segment (const ObjectState * state, Bus & parent)
Constructor.
Creates a skeleton segment with name only. This method should be called by Bus::loadStateWithoutReferences only. Do not use this constructor.
Parameters
state The ObjectState instance from which the name is loaded.
parent The bus this segment belongs to (parent bus).
Exceptions
ComponentAlreadyExists If a segment with the same name already exists in the given parent bus.
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 106 of file Segment.cc.
    : name_(""),
      parent_(NULL),
      sourceSegment_(NULL),
      destinationSegment_(NULL) {
    loadStateWithoutReferences(state);
    parent.addSegment(*this);
    parent_ = &parent;
}
References TTAMachine::Bus::addSegment(), loadStateWithoutReferences(), and parent_.
~Segment()
TTAMachine::Segment::~Segment ()
Destructor.
Detaches all the sockets before destruction.
Definition at line 121 of file Segment.cc.
                  {
    Bus* parentBus = parent_;
    parent_ = NULL;
    parentBus->removeSegment(*this);
    detachAllSockets();
    if (sourceSegment_ != NULL) {
        sourceSegment_->destinationSegment_ = destinationSegment_;
    }
    if (destinationSegment_ != NULL) {
        destinationSegment_->sourceSegment_ = sourceSegment_;
    }
}
References destinationSegment_, detachAllSockets(), parent_, parentBus(), TTAMachine::Bus::removeSegment(), and sourceSegment_.
Member Function Documentation
attachSocket()
void TTAMachine::Segment::attachSocket (Socket & socket)
Connects a socket to the segment.
Parameters
socket Socket to be connected.
Exceptions
IllegalRegistration If socket and segment do not belong to the same machine.
IllegalConnectivity If the connection would violate a connectivity constraint.
Definition at line 180 of file Segment.cc.
{
    parentBus()->ensureRegistration(socket);
    if (socket.isConnectedTo(*this)) {
        if (!isConnectedTo(socket)) {
            const Connection* conn = &(socket.connection(*this));
            connections_.push_back(conn);
        } else {
            MachineTester& tester = parentBus()->machine()->machineTester();
            assert(!tester.canConnect(socket, *this));
            MachineTestReporter reporter;
            string errorMsg =
                reporter.socketSegmentConnectionError(socket, *this, tester);
            string procName = "Segment::attachSocket";
            throw IllegalConnectivity(
                __FILE__, __LINE__, procName, errorMsg);
        }
    } else {
        socket.attachBus(*this);
    }
}
References assert, TTAMachine::Socket::attachBus(), MachineTester::canConnect(), TTAMachine::Socket::connection(), connections_, TTAMachine::Component::ensureRegistration(), TTAMachine::Socket::isConnectedTo(), isConnectedTo(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), parentBus(), and MachineTestReporter::socketSegmentConnectionError().
Referenced by TTAMachine::Socket::attachBus(), BlocksConnectIC::explore(), and VLIWConnectIC::explore().
connection() [1/2]
const Connection & TTAMachine::Segment::connection (const Socket & socket) const
Returns the Connection object which joins this segment and the given socket.
The connection must exist before calling this method. This method is not intended for clients. Do not use this method.
Parameters
socket Socket which is attached to this segment.
Returns
Connection object which joins the socket and the segment.
Definition at line 250 of file Segment.cc.
{
    ConnectionTable::const_iterator iter = connections_.begin();
    while (iter != connections_.end()) {
        if ((*iter)->socket() == &socket) {
            return **iter;
        } else {
            iter++;
        }
    }
    assert(false);
    // this return statement is only to avoid warning in Solaris environment
    return **iter;
}
References assert, and connections_.
Referenced by BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), SegmentFactory::createEditPart(), detachSocket(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::inputSockets(), BEMValidator::needsSourceField(), DefaultICGenerator::outputSockets(), removeConnection(), BusBroker::setupResourceLinks(), BEMGenerator::socket(), BEMGenerator::socketCount(), ConnectionSweeper::sweepBypasses(), and ConnectionSweeper::sweepRFs().
connection() [2/2]
Socket * TTAMachine::Segment::connection (int index) const
Returns the connected socket by the given index.
The index must be greater or equal to 0 and less than the number of socket connections.
Parameters
index Index.
Returns
The connected socket by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 300 of file Segment.cc.
{
    if (index < 0 || index >= connectionCount()) {
        string procName = "Segment::connection";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return connections_[index]->socket();
}
References connectionCount(), and connections_.
connectionCount()
int TTAMachine::Segment::connectionCount () const
Referenced by BusBroker::buildResources(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), connection(), SegmentFactory::createEditPart(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::inputSockets(), DefaultICGenerator::isBusConnected(), CostEstimator::Estimator::longestPath(), BEMValidator::needsSourceField(), DefaultICGenerator::outputSockets(), BusBroker::setupResourceLinks(), BEMGenerator::socket(), BEMGenerator::socketCount(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), and MachineConnectivityCheck::totalConnectionCount().
destinationSegment()
Segment * TTAMachine::Segment::destinationSegment () const
Referenced by BusDialog::onSegmentDown(), and TTAMachine::Bus::segment().
detachAllSockets()
void TTAMachine::Segment::detachAllSockets ()
Detaches all the sockets attached to the segment.
Definition at line 229 of file Segment.cc.
{
    ConnectionTable::iterator iter = connections_.begin();
    while (iter != connections_.end()) {
        Socket* socket = (*iter)->socket();
        detachSocket(*socket); // removes the socket from connections_
        iter = connections_.begin();
    }
}
References connections_, and detachSocket().
Referenced by loadState(), and ~Segment().
detachSocket()
void TTAMachine::Segment::detachSocket (Socket & socket)
Detaches socket from the segment.
Parameters
socket Socket which is detached.
Exceptions
InstanceNotFound If the segment is not attached to the given socket.
Definition at line 210 of file Segment.cc.
{
    if (!isConnectedTo(socket)) {
        string procName = "Segment::detachSocket";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    const Connection& conn = connection(socket);
    removeConnection(&conn);
    if (socket.isConnectedTo(*this)) {
        socket.detachBus(*this);
        delete &conn;
    }
}
References connection(), TTAMachine::Socket::detachBus(), TTAMachine::Socket::isConnectedTo(), isConnectedTo(), and removeConnection().
Referenced by detachAllSockets(), TTAMachine::Socket::detachBus(), and ConnectionSweeper::removeConnection().
hasDestinationSegment()
bool TTAMachine::Segment::hasDestinationSegment () const
Returns true if the segment has a destination segment, otherwise false.
Returns
True if the segment has a destination segment, otherwise false.
Definition at line 399 of file Segment.cc.
{
    return (destinationSegment_ != NULL);
}
References destinationSegment_.
Referenced by BusDialog::onSegmentDown().
hasSourceSegment()
bool TTAMachine::Segment::hasSourceSegment () const
Returns true if the segment has a source segment, otherwise false.
Returns
True if the segment has a source segment, otherwise false.
Definition at line 388 of file Segment.cc.
{
    return (sourceSegment_ != NULL);
}
References sourceSegment_.
Referenced by BusDialog::onSegmentUp(), and TTAMachine::Bus::segment().
isConnectedTo()
bool TTAMachine::Segment::isConnectedTo (const Socket & socket) const
Checks whether the segment is connected to the given socket.
Parameters
socket Socket.
Returns
True if connected, otherwise false.
Definition at line 274 of file Segment.cc.
{
    ConnectionTable::const_iterator iter = connections_.begin();
    while (iter != connections_.end()) {
        if ((*iter)->socket() == &socket) {
            return true;
        } else {
            iter++;
        }
    }
    return false;
}
References connections_.
Referenced by TTAMachine::Socket::attachBus(), attachSocket(), TTAMachine::Socket::detachBus(), detachSocket(), BlocksConnectIC::explore(), and TTAMachine::Connection::~Connection().
loadState()
void TTAMachine::Segment::loadState (const ObjectState * state) virtual
Loads the state of the segment from the given ObjectState instance.
Loads only name of the segment. Does not load connections to sockets. The destination of the segment and the order the segments in the chain is set later, in Bus::loadState.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the parent bus has a segment with the same name that is assigned to this segment or if the ObjectState tree is invalid.
Implements Serializable.
Definition at line 448 of file Segment.cc.
{
    string procName = "Segment::loadState";
    MOMTextGenerator textGenerator;
    if (state->name() != OSNAME_SEGMENT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    detachAllSockets();
    loadStateWithoutReferences(state);
}
References detachAllSockets(), loadStateWithoutReferences(), ObjectState::name(), and OSNAME_SEGMENT.
Referenced by TTAMachine::Bus::loadState().
loadStateWithoutReferences()
void TTAMachine::Segment::loadStateWithoutReferences (const ObjectState * state) private
Loads the state of the object from the given ObjectState instance without references to other machine parts.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 469 of file Segment.cc.
{
    const string procName = "Segment::loadStateWithoutReferences";
    if (state->name() != OSNAME_SEGMENT) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        string name = state->stringAttribute(OSKEY_NAME);
        if (!MachineTester::isValidComponentName(name)) {
            throw InvalidName(__FILE__, __LINE__, procName);
        }
        if (parent_ != NULL && parent_->hasSegment(name) &&
            this->name() != name) {
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
        }
        name_ = name;
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References Exception::errorMessage(), TTAMachine::Bus::hasSegment(), MachineTester::isValidComponentName(), name(), ObjectState::name(), name_, OSKEY_NAME, OSNAME_SEGMENT, parent_, and ObjectState::stringAttribute().
Referenced by loadState(), and Segment().
moveAfter()
void TTAMachine::Segment::moveAfter (Segment & segment)
Moves the segment behind the given segment in the segment chain.
The successor of this segment will become the successor of the current predecessor of this segment. The current successor of the given segment will become the successor the this segment.
Parameters
segment The segment behind of which the segment is moved.
Exceptions
IllegalRegistration If the given segment is in different bus than this segment.
Definition at line 357 of file Segment.cc.
{
    if (parentBus() != segment.parentBus()) {
        string procName = "Segment::moveAfter";
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    // detach from chain
    if (destinationSegment_ != NULL) {
        destinationSegment_->sourceSegment_ = sourceSegment_;
    }
    if (sourceSegment_ != NULL) {
        sourceSegment_->destinationSegment_ = destinationSegment_;
    }
    // attach to new position
    if (segment.destinationSegment_ != NULL) {
        segment.destinationSegment_->sourceSegment_ = this;
    }
    sourceSegment_ = &segment;
    destinationSegment_ = segment.destinationSegment_;
    segment.destinationSegment_ = this;
}
References destinationSegment_, parentBus(), and sourceSegment_.
Referenced by BusDialog::onSegmentDown().
moveBefore()
void TTAMachine::Segment::moveBefore (Segment & segment)
Moves the segment to the front of the given segment in the segment chain.
The successor of this segment will become the successor of the current predecessor of this segment. The current predecessor of the given segment will become the predecessor of this segment.
Parameters
segment The segment in front of which the segment is moved.
Exceptions
IllegalRegistration If the given segment is in different bus than this segment.
Definition at line 320 of file Segment.cc.
{
    if (parentBus() != segment.parentBus()) {
        string procName = "Segment::moveBefore";
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    // detach from chain
    if (destinationSegment_ != NULL) {
        destinationSegment_->sourceSegment_ = sourceSegment_;
    }
    if (sourceSegment_ != NULL) {
        sourceSegment_->destinationSegment_ = destinationSegment_;
    }
    // attach to new position
    if (segment.sourceSegment_ != NULL) {
        segment.sourceSegment_->destinationSegment_ = this;
    }
    sourceSegment_ = segment.sourceSegment_;
    destinationSegment_ = &segment;
    segment.sourceSegment_ = this;
}
References destinationSegment_, parentBus(), and sourceSegment_.
Referenced by TTAMachine::Bus::adjustSegmentChain(), and BusDialog::onSegmentUp().
name()
std::string TTAMachine::Segment::name () const
Referenced by TTAMachine::Bus::addSegment(), TTAMachine::Bus::adjustSegmentChain(), ADFCombiner::createBus(), InfoBussesCommand::execute(), ProDeSegmentEditPolicy::getCommand(), loadStateWithoutReferences(), BusDialog::onSegmentDown(), BusDialog::onSegmentUp(), ProgrammabilityValidator::printConnection(), saveState(), Segment(), setName(), MachineTestReporter::socketSegmentConnectionError(), SocketDialog::updateConnected(), and BusDialog::updateSegmentList().
parentBus()
Bus * TTAMachine::Segment::parentBus () const
Referenced by ProgrammabilityValidator::addConnectionToProgram(), TTAMachine::Bus::addSegment(), MachineConnectivityCheck::appendConnectedDestinationBuses(), MachineConnectivityCheck::appendConnectedSourceBuses(), TTAMachine::Socket::attachBus(), attachSocket(), MachineConnectivityCheck::busConnectedToPort(), MachineTester::canConnect(), ProDeSocketEditPolicy::canHandle(), MachineConnectivityCheck::canWriteAllImmediates(), DefaultDecoderGenerator::connectedBuses(), BlocksTranslator::CreateConnection(), SegmentFactory::createEditPart(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), ProgrammabilityValidator::findRegisterGuard(), ProximBusEditPolicy::getCommand(), moveAfter(), moveBefore(), ProgrammabilityValidator::printConnection(), ConnectionSweeper::removeConnection(), TTAMachine::Bus::removeSegment(), setName(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), DefaultICDecoderEstimator::socketParameters(), MachineTestReporter::socketSegmentConnectionError(), SocketDialog::updateConnected(), DefaultICGenerator::writeInterconnectionNetwork(), and ~Segment().
removeConnection()
void TTAMachine::Segment::removeConnection (const Connection * connection) private
Removes connection from the connection table.
Parameters
connection Connection to be removed.
Definition at line 410 of file Segment.cc.
{
    ContainerTools::removeValueIfExists(connections_, connection);
}
References connection(), connections_, and ContainerTools::removeValueIfExists().
Referenced by detachSocket().
saveState()
ObjectState * TTAMachine::Segment::saveState () const virtual
Saves the contents of the segment to an ObjectState object.
Returns
The created ObjectState object.
Implements Serializable.
Definition at line 421 of file Segment.cc.
{
    ObjectState* segmentState = new ObjectState(OSNAME_SEGMENT);
    segmentState->setAttribute(OSKEY_NAME, name());
    if (destinationSegment_ != NULL) {
        segmentState->setAttribute(
            OSKEY_DESTINATION, destinationSegment_->name());
    }
    return segmentState;
}
References destinationSegment_, name(), OSKEY_DESTINATION, OSKEY_NAME, OSNAME_SEGMENT, and ObjectState::setAttribute().
Referenced by TTAMachine::Bus::saveState().
setName()
void TTAMachine::Segment::setName (const std::string & name)
Sets the name of the segment.
Parameters
name Name of the segment.
Exceptions
ComponentAlreadyExists If a segment with the given name already exists in the segment chain of the parent bus.
InvalidName If the given name is not a valid component name.
Definition at line 148 of file Segment.cc.
{
    if (name == this->name()) {
        return;
    }
    const string procName = "Segment::setName";
    if (!MachineTester::isValidComponentName(name)) {
        throw InvalidName(__FILE__, __LINE__, procName);
    }
    Bus* parent = parentBus();
    for (int i = 0; i < parent->segmentCount(); i++) {
        Segment* segment = parent->segment(i);
        if (segment->name() == name) {
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        }
    }
    name_ = name;
}
References MachineTester::isValidComponentName(), name(), name_, parentBus(), TTAMachine::Bus::segment(), and TTAMachine::Bus::segmentCount().
sourceSegment()
Segment * TTAMachine::Segment::sourceSegment () const
Referenced by BusDialog::onSegmentUp().
Member Data Documentation
connections_
ConnectionTable TTAMachine::Segment::connections_ private
Contains all the connections to sockets.
Definition at line 109 of file Segment.hh.
Referenced by attachSocket(), connection(), connection(), detachAllSockets(), isConnectedTo(), and removeConnection().
destinationSegment_
Segment* TTAMachine::Segment::destinationSegment_ private
Destination segment.
Definition at line 107 of file Segment.hh.
Referenced by hasDestinationSegment(), moveAfter(), moveBefore(), saveState(), Segment(), and ~Segment().
name_
std::string TTAMachine::Segment::name_ private
Name of the segment.
Definition at line 101 of file Segment.hh.
Referenced by loadStateWithoutReferences(), and setName().
OSKEY_DESTINATION
const string TTAMachine::Segment::OSKEY_DESTINATION = "destination" static
ObjectState attribute key for destination segment name.
Definition at line 91 of file Segment.hh.
Referenced by TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), and saveState().
OSKEY_NAME
const string TTAMachine::Segment::OSKEY_NAME = "name" static
ObjectState attribute key for segment name.
Definition at line 89 of file Segment.hh.
Referenced by TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Bus::loadState(), TTAMachine::Bus::loadStateWithoutReferences(), loadStateWithoutReferences(), and saveState().
OSNAME_SEGMENT
const string TTAMachine::Segment::OSNAME_SEGMENT = "segment" static
ObjectState name for Segment.
Definition at line 87 of file Segment.hh.
Referenced by TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Bus::loadState(), loadState(), TTAMachine::Bus::loadStateWithoutReferences(), loadStateWithoutReferences(), and saveState().
parent_
Bus* TTAMachine::Segment::parent_ private
The parent bus.
Definition at line 103 of file Segment.hh.
Referenced by loadStateWithoutReferences(), Segment(), Segment(), and ~Segment().
sourceSegment_
Segment* TTAMachine::Segment::sourceSegment_ private
Source segment.
Definition at line 105 of file Segment.hh.
Referenced by hasSourceSegment(), moveAfter(), moveBefore(), Segment(), and ~Segment().
The documentation for this class was generated from the following files:
Segment.hh
Segment.cc