OpenASIP: Options Class Reference
Options Class Reference
#include <Options.hh>
Public Member Functions
Options ()
virtual ~Options ()
void addOptionValue (const string &name, OptionValue *option)
OptionValue & optionValue (const string &name, int index=0)
int valueCount (const string &name)
Private Attributes
map< string, vector< OptionValue * > > options_
Detailed Description
Generic container of option values.
Definition at line 51 of file Options.hh.
Constructor & Destructor Documentation
Options()
Options::Options ()
Constructor.
Definition at line 51 of file Options.cc.
                 {
}
~Options()
Options::~Options () virtual
Destructor.
Definition at line 57 of file Options.cc.
                  {
    std::map<string, vector<OptionValue*> >::iterator i = options_.begin();
    vector<OptionValue*>::iterator j;
    for (; i != options_.end(); i++) {
        j = (*i).second.begin();
    for (; j != (*i).second.end(); j++) {
        delete (*j);
    }
    (*i).second.clear();
    }
    options_.clear();
}
References options_.
Member Function Documentation
addOptionValue()
void Options::addOptionValue (const string & name, OptionValue * option)
Adds one option value to given option.
Parameters
name Name of the option.
option Value of the option.
Exceptions
TypeMismatch If new value's type differ the old ones.
Definition at line 78 of file Options.cc.
{
    try {
        vector<OptionValue*> values;
        values = MapTools::valueForKey<vector<OptionValue*> >(options_, name);
        OptionValue& other = *values.at(0);
        // check that new value is same type that old ones
        if (typeid(*option) == typeid(other)) {
            values.push_back(option);
            options_.erase(name);
            options_.insert(pair<string, vector<OptionValue*> >(name, values));
        } else {
            string procName = "Options::addOptionValue";
            string errorMsg =
                "Type of new OptionValue differs from the type of old values";
            throw TypeMismatch(__FILE__, __LINE__, procName, errorMsg);
        }
    } catch (KeyNotFound& e) {
        vector<OptionValue*> values;
        values.push_back(option);
        options_.insert(pair<string, vector<OptionValue*> >(name, values));
    }
}
References MapTools::keyForValue(), and options_.
Referenced by MachineCanvasOptions::MachineCanvasOptions().
optionValue()
OptionValue & Options::optionValue (const string & name, int index = 0)
Returns optionValue of the given option.
The index must be given between 0 and the option count where 0 is the latest value.
Parameters
name Name of the option.
index Index for lists of options.
Returns
The optionValue of an option.
Exceptions
OutOfRange The index is out of range of values.
KeyNotFound No option with given name.
Definition at line 115 of file Options.cc.
{
    if (index < 0 || index > valueCount(name) - 1) {
    string procName = "OptionValue::optionValue";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    vector<OptionValue*> values;
    values = MapTools::valueForKey<vector<OptionValue*> >(options_,name);
    return *values[values.size() - index - 1];
}
References MapTools::keyForValue(), options_, and valueCount().
Referenced by ToggleUnitDetailsCmd::Do(), UnitFigure::drawSelf(), ToggleUnitDetailsCmd::isChecked(), UnitFigure::layoutSelf(), ProximMachineStateWindow::onToggleUnitInfo(), and ProximMachineStateWindow::onUpdateUIEvent().
valueCount()
int Options::valueCount (const string & name)
Returns the count of optionValues of an option.
Parameters
name Name of the option.
Returns
Number of values for the option.
Exceptions
KeyNotFound No option with given name.
Definition at line 134 of file Options.cc.
{
    vector<OptionValue*> values;
    try {
    values = MapTools::valueForKey<vector<OptionValue*> >(options_,name);
    } catch (KeyNotFound& e) {
    string procName = "OptionValue::valueCount";
    throw KeyNotFound(__FILE__, __LINE__, procName);
    }
    return values.size();
}
References MapTools::keyForValue(), and options_.
Referenced by optionValue().
Member Data Documentation
options_
map<string, vector<OptionValue*> > Options::options_ private
Definition at line 62 of file Options.hh.
Referenced by addOptionValue(), optionValue(), valueCount(), and ~Options().
The documentation for this class was generated from the following files:
Options.hh
Options.cc