OpenASIP: TTAMachine::Port Class Reference
TTAMachine::Port Class Reference abstract
#include <Port.hh>
Classes
struct PairComparator
Public Member Functions
Port (const std::string &name, Unit &parentUnit)
Port (const ObjectState *state, Unit &parentUnit)
virtual ~Port ()
virtual std::string name () const
virtual void setName (const std::string &name)
virtual int width () const =0
virtual void attachSocket (Socket &socket)
virtual void detachSocket (Socket &socket)
virtual void detachAllSockets ()
Unit * parentUnit () const
virtual Socket * inputSocket () const
virtual Socket * outputSocket () const
virtual Socket * unconnectedSocket (int index) const
virtual int socketCount () const
virtual bool isConnectedTo (const Socket &socket) const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
virtual bool isOutput () const
virtual bool isInput () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_PORT = "port"
ObjectState name for Port.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the port.
static const std::string OSKEY_FIRST_SOCKET = "1_socket"
ObjectState attribute key for the name of the connected socket.
static const std::string OSKEY_SECOND_SOCKET = "2_socket"
ObjectState attribute key for the name of the other connected socket.
Protected Member Functions
Port (const std::string &name, FunctionUnit &parentUnit)
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Private Member Functions
Port (const Port &)
Copying forbidden.
Port & operator= (const Port &)
Assingment forbidden.
void loadStateWithoutReferences (const ObjectState *state)
void attachSocket (const std::string &socketName)
Private Attributes
std::string name_
Name of the port.
Unit * parentUnit_
Parent unit.
Socket * socket1_
Connection to the first socket.
Socket * socket2_
Connection to the second socket.
Detailed Description
Represents a port between function units and sockets.
Definition at line 54 of file Port.hh.
Constructor & Destructor Documentation
Port() [1/4]
TTAMachine::Port::Port (const std::string & name, Unit & parentUnit)
Constructor.
Parameters
name Name of the port.
parentUnit Unit to which the port is connected.
Exceptions
ComponentAlreadyExists If the parent unit already has another port by the same name.
InvalidName If the given name is not a valid name for a component.
Definition at line 67 of file Port.cc.
    : SubComponent(),
      name_(name),
      parentUnit_(NULL),
      socket1_(NULL),
      socket2_(NULL) {
    if (!MachineTester::isValidComponentName(name)) {
        const string procName = "Port::Port";
        throw InvalidName(__FILE__, __LINE__, procName);
    }
    parentUnit.addPort(*this);
    parentUnit_ = &parentUnit;
}
References TTAMachine::Unit::addPort(), MachineTester::isValidComponentName(), name(), parentUnit(), and parentUnit_.
Port() [2/4]
TTAMachine::Port::Port (const ObjectState * state, Unit & parentUnit)
Constructor.
Loads its state from the given ObjectState instance but does not create connections to sockets.
Parameters
state The ObjectState instance.
parentUnit The unit which contains the port.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 93 of file Port.cc.
    : SubComponent(),
      name_(""),
      parentUnit_(NULL),
      socket1_(NULL),
      socket2_(NULL) {
    loadStateWithoutReferences(state);
    try {
        parentUnit.addPort(*this);
    } catch (const ComponentAlreadyExists&) {
        const string procName = "Port::Port";
        MOMTextGenerator textGenerator;
        format errorMsg = textGenerator.text(
            MOMTextGenerator::TXT_PORT_EXISTS_BY_NAME);
        errorMsg % name() % parentUnit.name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    }
    parentUnit_ = &parentUnit;
}
References TTAMachine::Unit::addPort(), loadStateWithoutReferences(), TTAMachine::Component::name(), name(), parentUnit(), parentUnit_, Texts::TextGenerator::text(), and MOMTextGenerator::TXT_PORT_EXISTS_BY_NAME.
~Port()
TTAMachine::Port::~Port () virtual
Destructor.
Definition at line 117 of file Port.cc.
            {
    Unit* parent = parentUnit_;
    parentUnit_ = NULL;
    assert(parent != NULL);
    parent->removePort(*this);
    if (socket1_ != NULL) {
        detachSocket(*socket1_);
    }
    if (socket2_ != NULL) {
        detachSocket(*socket2_);
    }
}
References assert, detachSocket(), parentUnit_, TTAMachine::Unit::removePort(), socket1_, and socket2_.
Port() [3/4]
TTAMachine::Port::Port (const std::string & name, FunctionUnit & parentUnit) protected
Port() [4/4]
TTAMachine::Port::Port (const Port &) private
Copying forbidden.
Member Function Documentation
attachSocket() [1/2]
void TTAMachine::Port::attachSocket (const std::string & socketName) private
Attaches the socket by the given name to the port.
The given socket must be registered to the same machine as the parent unit.
Parameters
socketName Name of the socket to be attached.
Exceptions
InstanceNotFound If the given socket is not found from the machine.
IllegalRegistration If the parent unit is not registered to a machine.
ComponentAlreadyExists If a socket by the given name is already attached.
IllegalConnectivity If the socket cannot be attached because of connectivity reasons.
Definition at line 516 of file Port.cc.
{
    const string procName = "Socket::attachSocket";
    Machine* mach = parentUnit()->machine();
    if (mach == NULL) {
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    Machine::SocketNavigator socketNav = mach->socketNavigator();
    Socket* socket = socketNav.item(socketName);
    attachSocket(*socket);
}
References attachSocket(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), parentUnit(), and TTAMachine::Machine::socketNavigator().
attachSocket() [2/2]
void TTAMachine::Port::attachSocket (Socket & socket) virtual
Attaches a socket to this port.
NOTE! If the parent unit is a register file, attaching a socket may affect to the maximum simultaneous reads of the register file.
Parameters
socket Socket to be attached.
Exceptions
IllegalRegistration If the port and socket are not in the same machine.
ComponentAlreadyExists If the given socket is already attached.
IllegalConnectivity If the socket cannot be attached because of connectivity reasons.
Definition at line 191 of file Port.cc.
{
    parentUnit()->ensureRegistration(socket);
    string procName = "Port::attachSocket";
    MachineTester& tester = parentUnit()->machine()->machineTester();
    if (!tester.canConnect(socket, *this)) {
        if (tester.connectionExists()) {
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            string errorMsg = MachineTestReporter::
                socketPortConnectionError(socket, *this, tester);
            throw IllegalConnectivity(
                __FILE__, __LINE__, procName, errorMsg);
        }
    }
    if (socket1_ == NULL) {
        socket1_ = &socket;
    } else if (socket2_ == NULL) {
        socket2_ = &socket;
    } else {
        assert(false);
    }
    // bookeeping of Socket internal state - private Socket operation
    // reserved solely to Port class!
    socket.attachPort(*this);
    // sanity check
    if (socket2_ != NULL) {
        assert(socket1_->direction() == Socket::UNKNOWN ||
               socket1_->direction() != socket2_->direction());
    }
}
References assert, TTAMachine::Socket::attachPort(), MachineTester::canConnect(), MachineTester::connectionExists(), TTAMachine::Socket::direction(), TTAMachine::Component::ensureRegistration(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), parentUnit(), socket1_, socket2_, MachineTestReporter::socketPortConnectionError(), and TTAMachine::Socket::UNKNOWN.
Referenced by attachSocket(), BlocksFU::BlocksFU(), BlocksGCU::BlocksGCU(), BlocksIMM::BlocksIMM(), BlocksRF::BlocksRF(), RemoveUnconnectedComponents::checkFUPorts(), RemoveUnconnectedComponents::checkRFPorts(), FullyConnectedCheck::connectFUPort(), FullyConnectedCheck::connectIUPort(), ADFCombiner::connectPorts(), FullyConnectedCheck::connectRFPort(), FullyConnectedCheck::connectSpecialRegisterPort(), ADFCombiner::connectVectorLSU(), UniversalMachine::construct(), ADFCombiner::createPortsAndSockets(), SocketPortConnCmd::Do(), UniversalFunctionUnit::ensureInputPorts(), UniversalFunctionUnit::ensureOutputPorts(), VLIWConnectIC::explore(), loadState(), FUPortDialog::onCancel(), RFPortDialog::onCancel(), SRPortDialog::onCancel(), IUPortDialog::onOK(), FUPortDialog::onSocketChoice(), RFPortDialog::onSocketChoice(), SRPortDialog::onSocketChoice(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), and SRPortDialog::updateSockets().
detachAllSockets()
void TTAMachine::Port::detachAllSockets () virtual
Detaches all the sockets connected to the port.
NOTE! If the parent unit is a register file, detaching sockets may affect to the maximum simultaneous reads of the register file.
Definition at line 536 of file Port.cc.
                       {
    if (socket1_ != NULL) {
        socket1_->detachPort(*this);
        socket1_ = NULL;
    }
    if (socket2_ != NULL) {
        socket2_->detachPort(*this);
        socket2_ = NULL;
    }
}
References TTAMachine::Socket::detachPort(), socket1_, and socket2_.
Referenced by loadState(), FUPortDialog::onCancel(), RFPortDialog::onCancel(), SRPortDialog::onCancel(), IUPortDialog::onOK(), FUPortDialog::onSocketChoice(), RFPortDialog::onSocketChoice(), SRPortDialog::onSocketChoice(), and TTAMachine::Unit::unsetMachine().
detachSocket()
void TTAMachine::Port::detachSocket (Socket & socket) virtual
Detaches a socket from this port.
NOTE! If the parent unit is a register file, detaching a socket may affect to the maximum simultaneous reads of the register file.
Parameters
socket Socket to be detached.
Exceptions
InstanceNotFound If the given socket is not connected to the port.
Definition at line 237 of file Port.cc.
{
    if (socket1_ == &socket) {
        socket1_ = NULL;
    } else if (socket2_ == &socket) {
        socket2_ = NULL;
    } else {
        string procName = "Port::detachSocket";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    // bookeeping of Socket internal state - private Socket operation
    // reserved solely to Port class!
    socket.detachPort(*this);
}
References TTAMachine::Socket::detachPort(), socket1_, and socket2_.
Referenced by SocketPortConnCmd::Do(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), and ~Port().
inputSocket()
Socket * TTAMachine::Port::inputSocket () const virtual
Returns the input socket of the port.
If the port does not have input socket (socket whose direction is Socket::INPUT), returns NULL.
Returns
Input socket of the port.
Definition at line 261 of file Port.cc.
{
    if (socket1_ != NULL && socket1_->direction() == Socket::INPUT) {
        return socket1_;
    } else if (socket2_ != NULL && socket2_->direction() == Socket::INPUT) {
        return socket2_;
    } else {
        return NULL;
    }
}
References TTAMachine::Socket::direction(), TTAMachine::Socket::INPUT, socket1_, and socket2_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), MachineStateBuilder::addPortToFU(), BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), InputPSocketBroker::allAvailableResources(), MachineConnectivityCheck::appendConnectedSourceBuses(), InputPSocketBroker::assign(), MachineConnectivityCheck::busConnectedToPort(), MachineTester::canConnect(), MachineConnectivityCheck::canWriteAllImmediates(), OperationBindingCheck::check(), POMValidator::checkConnectivity(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectPorts(), ProGe::RV32MicroCodeGenerator::connectRF(), UnitPortFactory::createEditPart(), OpsetDialog::createOperation(), ADFCombiner::createPortsAndSockets(), TTAProgram::Move::destinationSocket(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), UniversalFunctionUnit::ensureInputPorts(), ProgrammabilityValidator::findConnections(), TTAMachine::RegisterFile::firstWritePort(), FullyConnectedCheck::fix(), MachineConnectivityCheck::fromRfConnected(), InputPSocketBroker::isAlreadyAssigned(), BusBroker::isAvailable(), MachineConnectivityCheck::isConnected(), MachineConnectivityCheck::isConnected(), isInput(), MachineTester::legalPortConnections(), MachineAnalysis::MachineAnalysis(), MachineConnectivityCheck::needsRegisterCopiesDueImmediateOperands(), BlockImplementationDialog::onHDBSelection(), SmartHWOperation::port(), ProgrammabilityValidator::printConnection(), MachineResourceManager::registerFileIndexReference(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), MachineResourceManager::rFPortOrFUIndexReference(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), MachineConnectivityCheck::toRfConnected(), InputPSocketBroker::unassign(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), DefaultDecoderGenerator::writeControlRulesOfRFWritePort(), DefaultDecoderGenerator::writeFUCntrlSignals(), and DefaultDecoderGenerator::writeRulesForDestinationControlSignals().
isConnectedTo()
bool TTAMachine::Port::isConnectedTo (const Socket & socket) const virtual
Checks whether the port is connected to the given socket.
Parameters
socket The socket.
Returns
True if the port is connected to the socket, otherwise false.
Definition at line 393 of file Port.cc.
{
    return (socket1_ == &socket || socket2_ == &socket);
}
References socket1_, and socket2_.
Referenced by MachineTester::canConnect(), ProDePortEditPolicy::canHandle(), ProDeSocketEditPolicy::canHandle(), ADFCombiner::connectVectorLSU(), SocketPortConnCmd::Do(), and ConnectTool::figure().
isInput()
bool TTAMachine::Port::isInput () const virtual
Returns true if this port can be used to read data from bus to the unit.
Returns
True if input port.
Definition at line 298 of file Port.cc.
                    {
    return inputSocket() != NULL;
}
References inputSocket().
Referenced by ProGe::RV32MicroCodeGenerator::addBPorts(), RegisterCopyAdder::addConnectionRegisterCopies(), ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addSPorts(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), TTAMachine::Unit::bidirPortCount(), RFPortCheck::check(), DefaultDecoderGenerator::completeDecoderBlock(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), FUGen::createMandatoryPorts(), FUGen::createShadowRegisters(), TTAProgram::CodeGenerator::createTerminalRegister(), MachineConnectivityCheck::findWritePorts(), CompiledSimCodeGenerator::generateTriggerCode(), TTAMachine::Unit::inputPortCount(), ProGe::NetlistGenerator::netlistPort(), TTAMachine::HWOperation::numberOfInputs(), TTAMachine::Unit::outputPortCount(), PlatformIntegrator::readLsuParameters(), TTAMachine::RegisterFile::updateMaxReadsAndWrites(), and DefaultDecoderGenerator::writeControlRegisterMappings().
isOutput()
bool TTAMachine::Port::isOutput () const virtual
Returns true if this port can be used to write data from unit to bus.
Returns
True if output port.
Definition at line 308 of file Port.cc.
                     {
    return outputSocket() != NULL;
}
References outputSocket().
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), ProGe::NetlistGenerator::addGCUToNetlist(), ProGe::RV32MicroCodeGenerator::addIPorts(), ProGe::RV32MicroCodeGenerator::addR1RPorts(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addUJPorts(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), TTAMachine::Unit::bidirPortCount(), FUGen::checkForValidity(), SimulatorFrontend::compareState(), RegisterCopyAdder::countAndAddConnectionRegisterCopiesToRR(), llvm::LLVMTCEBuilder::createTerminalRegister(), TTAProgram::CodeGenerator::createTerminalRegister(), llvm::LLVMTCEBuilder::emitSPInitialization(), MachineConnectivityCheck::findPossibleSourcePorts(), MachineConnectivityCheck::findReadPorts(), CompiledSimCodeGenerator::fuOutputPorts(), CompiledSimCodeGenerator::generateTriggerCode(), getOutputPort(), CompiledSimCodeGenerator::handleOperationWithoutDag(), TTAMachine::Unit::inputPortCount(), ProGe::NetlistGenerator::netlistPort(), TTAMachine::HWOperation::numberOfOutputs(), TTAMachine::Unit::outputPortCount(), FUGen::parseOperations(), TTAMachine::RegisterFile::updateMaxReadsAndWrites(), and DefaultDecoderGenerator::writeRFCntrlSignals().
loadState()
void TTAMachine::Port::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the parent unit has a port by the same name as the coming name of this unit or if loading the references to sockets fails.
Implements Serializable.
Reimplemented in TTAMachine::BaseFUPort, TTAMachine::FUPort, TTAMachine::RFPort, TTAMachine::SpecialRegisterPort, and UniversalFUPort.
Definition at line 459 of file Port.cc.
{
    const string procName = "Port::loadState";
    detachAllSockets();
    loadStateWithoutReferences(state);
    string socketName = "";
    MOMTextGenerator textGenerator;
    try {
        if (state->hasAttribute(OSKEY_FIRST_SOCKET)) {
            socketName = state->stringAttribute(OSKEY_FIRST_SOCKET);
            attachSocket(socketName);
        }
        if (state->hasAttribute(OSKEY_SECOND_SOCKET)) {
            socketName = state->stringAttribute(OSKEY_SECOND_SOCKET);
            attachSocket(socketName);
        }
    } catch (const InstanceNotFound&) {
        format errorMsg = textGenerator.text(
            MOMTextGenerator::TXT_PORT_REF_LOAD_ERR_SOCKET);
        errorMsg % socketName % name() % parentUnit()->name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    } catch (const IllegalRegistration&) {
        format errorMsg = textGenerator.text(
            MOMTextGenerator::TXT_PORT_REF_LOAD_ERR_SOCKET);
        errorMsg % socketName % name() % parentUnit()->name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    } catch (const ComponentAlreadyExists&) {
        format errorMsg = textGenerator.text(
            MOMTextGenerator::TXT_PORT_EXISTS_BY_NAME);
        errorMsg % name() % parentUnit()->name();
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, errorMsg.str());
    } catch (const IllegalConnectivity& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References attachSocket(), detachAllSockets(), Exception::errorMessage(), ObjectState::hasAttribute(), loadStateWithoutReferences(), TTAMachine::Component::name(), name(), OSKEY_FIRST_SOCKET, OSKEY_SECOND_SOCKET, parentUnit(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_PORT_EXISTS_BY_NAME, and MOMTextGenerator::TXT_PORT_REF_LOAD_ERR_SOCKET.
Referenced by TTAMachine::BaseFUPort::loadState(), TTAMachine::RFPort::loadState(), and TTAMachine::Unit::loadState().
loadStateWithoutReferences()
void TTAMachine::Port::loadStateWithoutReferences (const ObjectState * state) private
Loads its state from the given ObjectState instance but does not create connections to sockets.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 434 of file Port.cc.
{
    const string procName = "Port::loadStateWithoutReferences";
    try {
        string name = state->stringAttribute(OSKEY_NAME);
        if (!MachineTester::isValidComponentName(name)) {
            throw InvalidName(__FILE__, __LINE__, procName);
        }
        name_ = name;
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References Exception::errorMessage(), MachineTester::isValidComponentName(), name(), name_, OSKEY_NAME, and ObjectState::stringAttribute().
Referenced by loadState(), and Port().
name()
std::string TTAMachine::Port::name () const virtual
Returns the name of the port.
Returns
Name of the port.
Definition at line 141 of file Port.cc.
                 {
    return name_;
}
References name_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), HDB::HDBManager::addFUArchitecture(), ProGe::NetlistGenerator::addGCUToNetlist(), TTAMachine::Unit::addPort(), BEMGenerator::addPortCodes(), MachineStateBuilder::addPortToFU(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), BusBroker::allAvailableResources(), MachineStateBuilder::bindPortsToOperands(), CostDatabase::buildFunctionUnits(), MachineStateBuilder::buildMachineState(), UtilizationStats::calculateForInstruction(), FullyConnectedCheck::check(), POMValidator::checkConnectivity(), BEMValidator::checkGuardField(), ExecutionPipelineResource::checkOperandAllowed(), BEMValidator::checkSocketCodeTable(), SimulatorFrontend::compareState(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::connectVectorLSU(), TTAProgram::ProgramWriter::createCodeSection(), UnitPortFactory::createEditPart(), POMDisassembler::createFUPort(), POMDisassembler::createGuard(), FUGen::createMandatoryPorts(), ADFCombiner::createPortsAndSockets(), FUGen::createShadowRegisters(), TTAMachine::Unit::deleteOtherPorts(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), AddFUImplementationCmd::Do(), CodeCompressorPlugin::encodeFUTerminal(), InterpolatingFUEstimator::estimatePortReadDelay(), InterpolatingRFEstimator::estimatePortReadDelay(), InterpolatingFUEstimator::estimatePortWriteDelay(), InterpolatingRFEstimator::estimatePortWriteDelay(), InfoPortsCommand::execute(), BlocksConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), DefaultDecoderGenerator::findGuard(), SimulatorFrontend::findPort(), HDBToHtml::fuArchToHtml(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), CostEstimator::Estimator::functionUnitPortReadDelay(), CostEstimator::Estimator::functionUnitPortWriteDelay(), CompiledSimCodeGenerator::generateAddFUResult(), ProximPortEditPolicy::getCommand(), ProDePortEditPolicy::getCommand(), getOutputPort(), DefaultDecoderGenerator::guardPortName(), TTAMachine::HWOperation::io(), BusBroker::isAvailable(), HDB::HDBManager::isMatchingArchitecture(), TTAMachine::HWOperation::loadState(), loadState(), TTAMachine::FUPort::loadStateWithoutReferences(), loadStateWithoutReferences(), CostEstimator::Estimator::longestPath(), main(), ProGe::NetlistGenerator::netlistPort(), GCUDialog::onEditPort(), AddWatchDialog::onFUChoice(), FUGuardDialog::onFUChoice(), FUArchitectureDialog::onOK(), FUPortDialog::onOK(), IUPortDialog::onOK(), RFPortDialog::onOK(), SRPortDialog::onOK(), OperationDialog::onOperandSelection(), ExecutionPipelineResource::operandAllowedAtCycle(), operandBindingsString(), ExecutionPipelineResource::operandOverwritten(), HDB::FUArchitecture::operator==(), FUTestbenchGenerator::parseFuPorts(), FUGen::parseOperations(), Port(), Port(), TTAMachine::PortGuard::PortGuard(), CompiledSimSymbolGenerator::portSymbol(), BF2Scheduler::preAllocateFunctionUnits(), SimProgramBuilder::processBidirTerminal(), CostEstimator::Estimator::registerFilePortReadDelay(), CostEstimator::Estimator::registerFilePortWriteDelay(), BF2Scheduler::releasePortForOp(), HDB::HDBManager::resolveArchitecturePort(), MachineResourceManager::rFPortOrFUIndexReference(), TTAMachine::PortGuard::saveState(), saveState(), FUGen::scheduleOperations(), setName(), MachineTestReporter::socketDirectionSettingError(), MachineTestReporter::socketPortConnectionError(), MachineTestReporter::socketSegmentConnectionError(), SimulatorFrontend::state(), ProGe::RV32MicroCodeGenerator::throwInputPortError(), ProGe::RV32MicroCodeGenerator::throwOutputPortError(), ProGe::RV32MicroCodeGenerator::throwTriggeringPortError(), FUGuardDialog::TransferDataToWindow(), FUPortDialog::TransferDataToWindow(), IUPortDialog::TransferDataToWindow(), RFPortDialog::TransferDataToWindow(), SRPortDialog::TransferDataToWindow(), ProximPortWindow::update(), FUArchitectureDialog::update(), BusDialog::updateGuardLists(), OperationDialog::updateOperandList(), FUDialog::updatePortList(), GCUDialog::updatePortList(), IUDialog::updatePortList(), RFDialog::updatePortList(), GCUDialog::updateRAPortChoice(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), DefaultDecoderGenerator::writeControlRulesOfRFWritePort(), DefaultDecoderGenerator::writeFUCntrlSignals(), DefaultDecoderGenerator::writeRFCntrlSignals(), and DefaultDecoderGenerator::writeRFSRAMDecodingProcess().
operator=()
Port & TTAMachine::Port::operator= (const Port &) private
Assingment forbidden.
outputSocket()
Socket * TTAMachine::Port::outputSocket () const virtual
Returns the output socket of the port.
If the port does not have output socket (socket whose direction is Socket::OUTPUT), returns NULL.
Returns
Output socket of the port.
Definition at line 281 of file Port.cc.
{
    if (socket1_ != NULL && socket1_->direction() == Socket::OUTPUT) {
        return socket1_;
    } else if (socket2_ != NULL &&
               socket2_->direction() == Socket::OUTPUT) {
        return socket2_;
    } else {
        return NULL;
    }
}
References TTAMachine::Socket::direction(), TTAMachine::Socket::OUTPUT, socket1_, and socket2_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), MachineStateBuilder::addPortToFU(), BusBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), MachineConnectivityCheck::appendConnectedDestinationBuses(), OutputFUBroker::assign(), OutputPSocketBroker::assign(), MachineTester::canConnect(), OperationBindingCheck::check(), POMValidator::checkConnectivity(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectPorts(), ProGe::RV32MicroCodeGenerator::connectRF(), UnitPortFactory::createEditPart(), OpsetDialog::createOperation(), ADFCombiner::createPortsAndSockets(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), UniversalFunctionUnit::ensureOutputPorts(), VLIWConnectIC::explore(), ProgrammabilityValidator::findConnections(), TTAMachine::RegisterFile::firstReadPort(), FullyConnectedCheck::fix(), MachineConnectivityCheck::fromRfConnected(), MachineConnectivityCheck::immBits(), OutputPSocketBroker::isAlreadyAssigned(), OutputPSocketBroker::isAnyResourceAvailable(), BusBroker::isAvailable(), MachineConnectivityCheck::isConnected(), MachineConnectivityCheck::isConnected(), isOutput(), MachineTester::legalPortConnections(), MachineAnalysis::MachineAnalysis(), BlockImplementationDialog::onHDBSelection(), SmartHWOperation::port(), ProgrammabilityValidator::printConnection(), MachineResourceManager::registerFileIndexReference(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), ComponentImplementationSelector::rfImplementations(), MachineResourceManager::rFPortOrFUIndexReference(), ExecutionPipelineBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), TTAProgram::Move::sourceSocket(), MachineConnectivityCheck::toRfConnected(), FUGuardDialog::TransferDataToWindow(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), DefaultDecoderGenerator::writeRFCntrlSignals(), DefaultDecoderGenerator::writeRFSRAMDecodingProcess(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
parentUnit()
Unit * TTAMachine::Port::parentUnit () const
Referenced by CodeCompressorPlugin::addBitsForGuardField(), RegisterCopyAdder::addConnectionRegisterCopies(), RegisterCopyAdder::addConnectionRegisterCopiesImmediate(), ProgrammabilityValidator::addConnectionToProgram(), ProgrammabilityValidator::addDirectConnection(), ProgrammabilityValidator::addGlobalRegisterConnection(), TTAMachine::Unit::addPort(), BEMGenerator::addPortCodes(), BusBroker::allAvailableResources(), InputPSocketBroker::assign(), OutputPSocketBroker::assign(), attachSocket(), attachSocket(), MachineConnectivityCheck::busConnectedToDestination(), OutputPSocketResource::canAssign(), MachineTester::canConnect(), ProDeSocketEditPolicy::canHandle(), MachineConnectivityCheck::canWriteAllImmediates(), POMValidator::checkConnectivity(), BEMValidator::checkSocketCodeTable(), TTAMachine::FUPort::cleanupGuards(), TTAMachine::FUPort::cleanupOperandBindings(), TTAProgram::TPEFProgramFactory::createInstruction(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), MachineConnectivityCheck::findRoutes(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), BF2Scheduler::getDstUnit(), ProgramOperation::hwopFromOutMove(), BusBroker::isAvailable(), MachineConnectivityCheck::isPortApplicableToWidths(), MachineTester::legalPortConnections(), loadState(), TTAMachine::FUPort::loadStateWithoutReferences(), CostEstimator::Estimator::longestPath(), main(), BEMValidator::needsSocketCodeTable(), ProGe::NetlistGenerator::netlistPort(), IUPortDialog::onOK(), RFPortDialog::onOK(), RFPortDialog::onSocketChoice(), ProgramOperation::outputIndexFromGuard(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::RFPort::parentUnit(), ExecutionPipelineResource::poConflictsWithInputPort(), Port(), Port(), CompiledSimSymbolGenerator::portSymbol(), ProgrammabilityValidator::printConnection(), SimProgramBuilder::processBidirTerminal(), SimpleICOptimizer::removeAllConnections(), TTAMachine::Unit::removePort(), RegisterRenamer::renameLiveRange(), TTAProgram::TPEFProgramFactory::resolveSocketAllocations(), setName(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), MachineTestReporter::socketDirectionSettingError(), MachineTestReporter::socketPortConnectionError(), MachineTestReporter::socketSegmentConnectionError(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), TTAProgram::ProgramWriter::terminalResource(), IUPortDialog::updateSocket(), and RFPortDialog::updateSockets().
saveState()
ObjectState * TTAMachine::Port::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Reimplemented in TTAMachine::BaseFUPort, TTAMachine::FUPort, TTAMachine::RFPort, and TTAMachine::SpecialRegisterPort.
Definition at line 404 of file Port.cc.
                      {
    ObjectState* port = new ObjectState(OSNAME_PORT);
    port->setAttribute(OSKEY_NAME, name());
    // set first socket
    if (socket1_ != NULL) {
        port->setAttribute(OSKEY_FIRST_SOCKET, socket1_->name());
    } else if (socket2_ != NULL) {
        port->setAttribute(OSKEY_FIRST_SOCKET, socket2_->name());
    }
    // set second socket
    if (socket1_ != NULL && socket2_ != NULL) {
        port->setAttribute(OSKEY_SECOND_SOCKET, socket2_->name());
    }
    return port;
}
References TTAMachine::Component::name(), name(), OSKEY_FIRST_SOCKET, OSKEY_NAME, OSKEY_SECOND_SOCKET, OSNAME_PORT, ObjectState::setAttribute(), socket1_, and socket2_.
Referenced by TTAMachine::BaseFUPort::saveState(), TTAMachine::RFPort::saveState(), and TTAMachine::Unit::saveState().
setName()
void TTAMachine::Port::setName (const std::string & name) virtual
Sets the name of the port.
Parameters
name The new name.
Exceptions
ComponentAlreadyExists If a port with the given name already exists in the same unit.
InvalidName If the given name is not a valid component name.
Reimplemented in UniversalFUPort.
Definition at line 155 of file Port.cc.
{
    if (name == this->name()) {
        return;
    }
    const string procName = "Port::setName";
    if (!MachineTester::isValidComponentName(name)) {
        throw InvalidName(__FILE__, __LINE__, procName);
    }
    Unit* parent = this->parentUnit();
    for (int i = 0; i < parent->portCount(); i++) {
        Port* port = parent->port(i);
        if (port->name() == name) {
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        }
    }
    name_ = name;
}
References MachineTester::isValidComponentName(), name(), name_, parentUnit(), TTAMachine::Unit::port(), and TTAMachine::Unit::portCount().
Referenced by AddFUFromHDBDialog::onAdd(), FUPortDialog::onOK(), IUPortDialog::onOK(), RFPortDialog::onOK(), and SRPortDialog::onOK().
socketCount()
int TTAMachine::Port::socketCount () const virtual
Returns the number of sockets attached to the port.
Returns
The number of sockets.
Definition at line 375 of file Port.cc.
{
    if (socket1_ != NULL && socket2_ != NULL) {
        return 2;
    } else if (socket1_ != NULL || socket2_ != NULL) {
        return 1;
    } else {
        return 0;
    }
}
References socket1_, and socket2_.
Referenced by MachineTester::canConnect(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), MachineValidator::checkFUConnections(), RemoveUnconnectedComponents::checkFUPorts(), RemoveUnconnectedComponents::checkRFPorts(), FullyConnectedCheck::connectControlUnit(), ADFCombiner::connectVectorLSU(), FullyConnectedCheck::fix(), RemoveUnconnectedComponents::removeUnconnectedFUs(), and unconnectedSocket().
unconnectedSocket()
Socket * TTAMachine::Port::unconnectedSocket (int index) const virtual
Returns the first or the second unconnected socket attached to this port. If there is no such socket, returns NULL.
Parameters
index The index which indicates which of the unconnected sockets is returned. If there is only one unconnected socket, the index value 0 returns it and value 1 returns NULL.
Returns
The unconnected socket by the given index.
Exceptions
OutOfRange If the given index is not 0 or 1.
Definition at line 323 of file Port.cc.
{
    const string procName = "Port::unconnectedSocket";
    if (index < 0 || index > 1) {
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    if (socketCount() == 0) {
        return NULL;
    } else if (socketCount() == 1) {
        if (index == 1) {
            return NULL;
        } else if (socket1_ != NULL && socket1_->segmentCount() == 0) {
            return socket1_;
        } else if (socket2_ != NULL && socket2_->segmentCount() == 0) {
            return socket2_;
        } else {
            return NULL;
        }
    } else if (socketCount() == 2) {
        if (index == 0) {
            if (socket1_->segmentCount() == 0) {
                return socket1_;
            } else if (socket2_->segmentCount() == 0) {
                return socket2_;
            } else {
                return NULL;
            }
        } else {
            if (socket2_->segmentCount() == 0) {
                return socket2_;
            } else {
                return NULL;
            }
        }
    } else {
        string errorMsg = "Too many sockets attached to a port.";
        Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
        Application::abortProgram();
        // this return statement is just to avoid compilation warning in some
        // environments.
        return NULL;
    }
}
References Application::abortProgram(), TTAMachine::Socket::segmentCount(), socket1_, socket2_, socketCount(), and Application::writeToErrorLog().
Referenced by MachineTester::canConnect(), ADFCombiner::connectPorts(), and UnitPortFactory::createEditPart().
width()
virtual int TTAMachine::Port::width () const pure virtual
Implemented in TTAMachine::BaseFUPort, and TTAMachine::RFPort.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), ProGe::NetlistGenerator::addGCUToNetlist(), DefaultICDecoderEstimator::busParameters(), BusResource::canAssign(), MachineConnectivityCheck::canWriteAllImmediates(), UnitPortFactory::createEditPart(), llvm::LLVMTCEBuilder::createMove(), DefaultICDecoderGenerator::dataPortWidth(), llvm::LLVMTCEBuilder::emitMove(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), MachineResourceManager::functionUnitPortResource(), CompiledSimCodeGenerator::generateInstruction(), DefaultICGenerator::inputSocketDataPortWidth(), DefaultICGenerator::maxOutputSocketDataPortWidth(), DefaultICGenerator::outputSocketDataPortWidth(), SimProgramBuilder::processMove(), MachineResourceManager::rFPortOrFUIndexReference(), DefaultICDecoderEstimator::socketParameters(), MachineConnectivityCheck::toRfConnected(), and DefaultICGenerator::writeInterconnectionNetwork().
Member Data Documentation
name_
std::string TTAMachine::Port::name_ private
Name of the port.
Definition at line 107 of file Port.hh.
Referenced by loadStateWithoutReferences(), name(), and setName().
OSKEY_FIRST_SOCKET
const string TTAMachine::Port::OSKEY_FIRST_SOCKET = "1_socket" static
ObjectState attribute key for the name of the connected socket.
Definition at line 84 of file Port.hh.
Referenced by loadState(), ADFSerializer::machineFUPort(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfPort(), and saveState().
OSKEY_NAME
const string TTAMachine::Port::OSKEY_NAME = "name" static
ObjectState attribute key for the name of the port.
Definition at line 82 of file Port.hh.
Referenced by TTAMachine::Unit::loadState(), loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), ADFSerializer::machineFUPort(), ADFSerializer::mdfPort(), TTAMachine::Unit::portNames(), and saveState().
OSKEY_SECOND_SOCKET
const string TTAMachine::Port::OSKEY_SECOND_SOCKET = "2_socket" static
ObjectState attribute key for the name of the other connected socket.
Definition at line 86 of file Port.hh.
Referenced by loadState(), ADFSerializer::machineFUPort(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfPort(), and saveState().
OSNAME_PORT
const string TTAMachine::Port::OSNAME_PORT = "port" static
ObjectState name for Port.
Definition at line 80 of file Port.hh.
Referenced by saveState().
parentUnit_
Unit* TTAMachine::Port::parentUnit_ private
Parent unit.
Definition at line 109 of file Port.hh.
Referenced by Port(), Port(), and ~Port().
socket1_
Socket* TTAMachine::Port::socket1_ private
Connection to the first socket.
Definition at line 111 of file Port.hh.
Referenced by attachSocket(), detachAllSockets(), detachSocket(), inputSocket(), isConnectedTo(), outputSocket(), saveState(), socketCount(), unconnectedSocket(), and ~Port().
socket2_
Socket* TTAMachine::Port::socket2_ private
Connection to the second socket.
Definition at line 113 of file Port.hh.
Referenced by attachSocket(), detachAllSockets(), detachSocket(), inputSocket(), isConnectedTo(), outputSocket(), saveState(), socketCount(), unconnectedSocket(), and ~Port().
The documentation for this class was generated from the following files:
Port.hh
Port.cc