OpenASIP: AddFUEntryCmd Class Reference
AddFUEntryCmd Class Reference
#include <AddFUEntryCmd.hh>
Public Member Functions
AddFUEntryCmd ()
virtual ~AddFUEntryCmd ()
virtual bool Do ()
virtual int id () const
virtual AddFUEntryCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new FU entries to a HDB.
Definition at line 41 of file AddFUEntryCmd.hh.
Constructor & Destructor Documentation
AddFUEntryCmd()
AddFUEntryCmd::AddFUEntryCmd ()
The Constructor.
Definition at line 45 of file AddFUEntryCmd.cc.
                             :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_FU_ENTRY, NULL) {
}
Referenced by create().
~AddFUEntryCmd()
AddFUEntryCmd::~AddFUEntryCmd () virtual
The Destructor.
Definition at line 53 of file AddFUEntryCmd.cc.
{
}
Member Function Documentation
create()
AddFUEntryCmd * AddFUEntryCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 102 of file AddFUEntryCmd.cc.
{
    return new AddFUEntryCmd();
}
References AddFUEntryCmd().
Do()
bool AddFUEntryCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file AddFUEntryCmd.cc.
                  {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    RowID id = manager->addFUEntry();
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectFUEntry(id);
    return true;
}
References HDB::HDBManager::addFUEntry().
icon()
std::string AddFUEntryCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 81 of file AddFUEntryCmd.cc.
{
    return "";
}
id()
int AddFUEntryCmd::id () const virtual
Returns command id.
Returns
Command identifier.
Implements GUICommand.
Definition at line 91 of file AddFUEntryCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_FU_ENTRY;
}
References HDBEditorConstants::COMMAND_ADD_FU_ENTRY.
isEnabled()
bool AddFUEntryCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 113 of file AddFUEntryCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddFUEntryCmd.hh
AddFUEntryCmd.cc