OpenASIP: OSEdRemoveModuleCmd Class Reference
OSEdRemoveModuleCmd Class Reference
#include <OSEdRemoveModuleCmd.hh>
Public Member Functions
OSEdRemoveModuleCmd ()
virtual ~OSEdRemoveModuleCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdRemoveModuleCmd (const OSEdRemoveModuleCmd &)
Copying not allowed.
OSEdRemoveModuleCmd & operator= (const OSEdRemoveModuleCmd &)
Assignment not allowed.
Detailed Description
Command for removing a module.
Definition at line 43 of file OSEdRemoveModuleCmd.hh.
Constructor & Destructor Documentation
OSEdRemoveModuleCmd() [1/2]
OSEdRemoveModuleCmd::OSEdRemoveModuleCmd ()
Constructor.
Definition at line 58 of file OSEdRemoveModuleCmd.cc.
                                         :
    GUICommand(OSEdConstants::CMD_NAME_REMOVE_MODULE, NULL) {
}
Referenced by create().
~OSEdRemoveModuleCmd()
OSEdRemoveModuleCmd::~OSEdRemoveModuleCmd () virtual
Destructor.
Definition at line 65 of file OSEdRemoveModuleCmd.cc.
{
}
OSEdRemoveModuleCmd() [2/2]
OSEdRemoveModuleCmd::OSEdRemoveModuleCmd (const OSEdRemoveModuleCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdRemoveModuleCmd::create () const virtual
Returns a new command.
Returns
A new command.
Implements GUICommand.
Definition at line 84 of file OSEdRemoveModuleCmd.cc.
{
    return new OSEdRemoveModuleCmd();
}
References OSEdRemoveModuleCmd().
Do()
bool OSEdRemoveModuleCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 94 of file OSEdRemoveModuleCmd.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    string modName = treeView->selectedModule();
    wxTreeItemId modId = treeView->selectedModuleId();
    string path = treeView->pathOfModule(modId);
    OperationModule& module = OperationContainer::module(path, modName);
    format fmt = texts.text(OSEdTextGenerator::TXT_QUESTION_REMOVE_MODULE);
    fmt % modName;
    ConfirmDialog dialog(parentWindow(), WxConversion::toWxString(fmt.str()));
    if (dialog.ShowModal() == wxID_YES) {
        bool removed =
            FileSystem::removeFileOrDirectory(module.propertiesModule());
        assert(removed == true);
        if (module.hasBehaviorSource()) {
            fmt = texts.text(
                OSEdTextGenerator::TXT_QUESTION_REMOVE_BEHAVIOR_FILE);
            fmt % FileSystem::fileOfPath(module.behaviorSourceModule());
            wxString confText = WxConversion::toWxString(fmt.str());
            ConfirmDialog confirm(parentWindow(), confText);
            if (confirm.ShowModal() == wxID_YES) {
                FileSystem::removeFileOrDirectory(module.behaviorSourceModule());
            }
        }
        if (module.definesBehavior()) {
            FileSystem::removeFileOrDirectory(module.behaviorModule());
        }
        OperationIndex& index = OperationContainer::operationIndex();
        index.removeModule(path, modName);
        treeView->removeItem(modId);
        treeView->infoView()->moduleView(path);
    }
    return true;
}
References assert, FileSystem::fileOfPath(), OSEdTreeView::infoView(), OSEdTextGenerator::instance(), OSEdInfoView::moduleView(), OperationContainer::operationIndex(), GUICommand::parentWindow(), OSEdTreeView::pathOfModule(), FileSystem::removeFileOrDirectory(), OSEdTreeView::removeItem(), OperationIndex::removeModule(), OSEdTreeView::selectedModule(), OSEdTreeView::selectedModuleId(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_QUESTION_REMOVE_BEHAVIOR_FILE, and OSEdTextGenerator::TXT_QUESTION_REMOVE_MODULE.
icon()
string OSEdRemoveModuleCmd::icon () const virtual
Returns icon path.
Returns
Empty string (no icons used).
Implements GUICommand.
Definition at line 169 of file OSEdRemoveModuleCmd.cc.
{
    return "";
}
id()
int OSEdRemoveModuleCmd::id () const virtual
Returns the id of the command.
Returns
Id of the command.
Implements GUICommand.
Definition at line 74 of file OSEdRemoveModuleCmd.cc.
{
    return OSEdConstants::CMD_REMOVE_MODULE;
}
References OSEdConstants::CMD_REMOVE_MODULE.
isEnabled()
bool OSEdRemoveModuleCmd::isEnabled () virtual
Returns true if command is enabled.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 145 of file OSEdRemoveModuleCmd.cc.
{
    OSEdTreeView* treeView = wxGetApp().mainFrame()->treeView();
    if (treeView->isModuleSelected()) {
        wxTreeItemId modId = treeView->selectedModuleId();
        string path = treeView->pathOfModule(modId);
        if (path != "") {
            return FileSystem::fileIsWritable(path);
        } else {
            return false;
        }
    } else {
        return false;
    }
    assert(false);
    return false;
}
References assert, FileSystem::fileIsWritable(), OSEdTreeView::isModuleSelected(), OSEdTreeView::pathOfModule(), and OSEdTreeView::selectedModuleId().
operator=()
OSEdRemoveModuleCmd & OSEdRemoveModuleCmd::operator= (const OSEdRemoveModuleCmd &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
OSEdRemoveModuleCmd.hh
OSEdRemoveModuleCmd.cc