OpenASIP: InstructionFormat Class Reference
InstructionFormat Class Reference
#include <InstructionFormat.hh>
Public Member Functions
InstructionFormat (const std::string &name, BinaryEncoding &parent)
InstructionFormat (const ObjectState *state, BinaryEncoding &parent)
~InstructionFormat ()
InstructionField * parent () const
std::string name () const
void setName (const std::string &name)
void addEncoding (OperationTriggeredEncoding &encoding)
void addOperation (std::string op, int encoding)
int operationCount () const
std::string operationAtIndex (const int index) const
bool hasOperation (const std::string &op) const
int encoding (const std::string &op) const
virtual int childFieldCount () const
virtual int width () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_INSTRUCTION_FORMAT = "ota-format"
static const std::string OSKEY_INSTRUCTION_FORMAT_NAME = "name"
static const std::string OSKEY_OTA_OPERATION_NAME
static const std::string OSKEY_OPERATION_NAME = "name"
static const std::string OSKEY_OPERATION_ENCODING_NAME
Private Attributes
std::string name_
BinaryEncoding * parent_
std::vector< OperationTriggeredEncoding * > encodings_
std::map< std::string, int > operations_
Detailed Description
Definition at line 46 of file InstructionFormat.hh.
Constructor & Destructor Documentation
InstructionFormat() [1/2]
InstructionFormat::InstructionFormat (const std::string & name, BinaryEncoding & parent)
The constructor.
Adds the instruction format to the parent binary encoding automatically.
Parameters
name Name of the instruction format.
parent The parent BinaryEncoding.
Definition at line 60 of file InstructionFormat.cc.
    : name_(name), parent_(NULL) {
    parent.addInstructionFormat(*this);
    parent_ = &parent;
}
References parent(), and parent_.
InstructionFormat() [2/2]
InstructionFormat::InstructionFormat (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the instruction format from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent binary encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 78 of file InstructionFormat.cc.
    : parent_(NULL) {
    parent.addInstructionFormat(*this);
    parent_ = &parent;
    loadState(state);
}
References loadState(), parent(), and parent_.
~InstructionFormat()
InstructionFormat::~InstructionFormat ()
The destructor
Definition at line 91 of file InstructionFormat.cc.
{
    /*
    for (unsigned int i = 0; i < encodings_.size(); i++) {
        delete encodings_.at(i);
    }*/
}
Member Function Documentation
addEncoding()
void InstructionFormat::addEncoding (OperationTriggeredEncoding & encoding)
Adds an operation triggered move slot to the instruction format
Parameters
encoding The operation triggered move slot to be addeed
Exceptions
ObjectAlreadyExists If the slot has already been added to the instruction format.
Definition at line 139 of file InstructionFormat.cc.
{
    if (!VectorTools::containsValue(encodings_, &encoding)) {
        encodings_.push_back(&encoding);
    } else {
        const std::string procName = "InstructionFormat::addEncoding";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
}
References VectorTools::containsValue(), encoding(), and encodings_.
Referenced by OperationTriggeredEncoding::OperationTriggeredEncoding(), and OperationTriggeredEncoding::OperationTriggeredEncoding().
addOperation()
void InstructionFormat::addOperation (std::string op, int encoding)
Adds an operation to the instruction format
Parameters
op Operation name
encoding Encoding of the operation
Exceptions
ObjectAlreadyExists If the slot has already been added to the instruction format.
Definition at line 158 of file InstructionFormat.cc.
{
    if (!MapTools::containsKey(operations_, op)) {
        operations_.insert({op, encoding});
    } else {
        const std::string procName = "InstructionFormat::addOperation";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
}
References MapTools::containsKey(), encoding(), and operations_.
Referenced by BEMGenerator::addRiscvFormat(), and loadState().
childFieldCount()
int InstructionFormat::childFieldCount () const virtual
Returns the number of operation triggered encodings.
Returns
The number of child fields.
Definition at line 174 of file InstructionFormat.cc.
{
    return encodings_.size();
}
References encodings_.
encoding()
int InstructionFormat::encoding (const std::string & op) const
Definition at line 212 of file InstructionFormat.cc.
{
    assert(MapTools::containsKey(operations_, op));
    return operations_.at(op);
}
References assert, MapTools::containsKey(), and operations_.
Referenced by addEncoding(), addOperation(), llvm::LLVMTCERISCVIntrinsicsLowering::constructEncoding(), RISCVTDGen::findCustomOps(), and ProGe::RV32MicroCodeGenerator::initializeOperations().
hasOperation()
bool InstructionFormat::hasOperation (const std::string & op) const
Definition at line 104 of file InstructionFormat.cc.
{
    return MapTools::containsKey(operations_, op);
}
References MapTools::containsKey(), and operations_.
Referenced by llvm::LLVMTCERISCVIntrinsicsLowering::findOperationName().
loadState()
void InstructionFormat::loadState (const ObjectState * state) virtual
Loads the state of the instruction format from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Definition at line 226 of file InstructionFormat.cc.
{
    ObjectState* newState = new ObjectState(*state);
    try {
        setName(newState->stringAttribute(OSKEY_INSTRUCTION_FORMAT_NAME));
        for (int i = 0; i < newState->childCount(); i++) {
            ObjectState* child = newState->child(i);
            if (child->name() ==
                OperationTriggeredEncoding::OSNAME_OTA_ENCODING) {
                new OperationTriggeredEncoding(child, *this);
            } else if (child->name() == OSKEY_OTA_OPERATION_NAME) {
                addOperation(
                    child->stringAttribute(OSKEY_OPERATION_NAME),
                    child->intAttribute(OSKEY_OPERATION_ENCODING_NAME));
            }
        }
    } catch (const Exception& exception) {
        const std::string procName = "InstructionFormat::loadState";
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References addOperation(), ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::intAttribute(), ObjectState::name(), OSKEY_INSTRUCTION_FORMAT_NAME, OSKEY_OPERATION_ENCODING_NAME, OSKEY_OPERATION_NAME, OSKEY_OTA_OPERATION_NAME, OperationTriggeredEncoding::OSNAME_OTA_ENCODING, setName(), and ObjectState::stringAttribute().
Referenced by InstructionFormat().
name()
std::string InstructionFormat::name () const
Returns the name of the instruction format.
Returns
The name of the instruction format
Definition at line 115 of file InstructionFormat.cc.
{
    return name_;
}
References name_.
Referenced by BinaryEncoding::addInstructionFormat(), llvm::LLVMTCERISCVIntrinsicsLowering::findRFormat(), ProGe::RV32MicroCodeGenerator::initializeOperations(), BinaryEncoding::instructionFormat(), and setName().
operationAtIndex()
std::string InstructionFormat::operationAtIndex (const int index) const
Definition at line 200 of file InstructionFormat.cc.
{
    if (index > operationCount() - 1) {
        const std::string msg = "Operation index out of range.";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    auto it = operations_.begin();
    std::advance(it, index);
    return it->first;
}
References __func__, operationCount(), and operations_.
Referenced by RISCVTDGen::findCustomOps(), and ProGe::RV32MicroCodeGenerator::initializeOperations().
operationCount()
int InstructionFormat::operationCount () const
Definition at line 195 of file InstructionFormat.cc.
{
    return operations_.size();
}
References operations_.
Referenced by RISCVTDGen::findCustomOps(), ProGe::RV32MicroCodeGenerator::initializeOperations(), and operationAtIndex().
parent()
InstructionField * InstructionFormat::parent () const
Definition at line 99 of file InstructionFormat.cc.
{
    return static_cast<InstructionField*>(parent_);
}
References parent_.
Referenced by BinaryEncoding::addInstructionFormat(), InstructionFormat(), InstructionFormat(), and BinaryEncoding::removeInstructionFormat().
saveState()
ObjectState * InstructionFormat::saveState () const virtual
Saves the state of the instruction format to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 255 of file InstructionFormat.cc.
{
    ObjectState* state = new ObjectState(OSNAME_INSTRUCTION_FORMAT);
    state->setAttribute(OSKEY_INSTRUCTION_FORMAT_NAME, name_);
    for (unsigned int i = 0; i < encodings_.size(); i++) {
        OperationTriggeredEncoding* it = encodings_.at(i);
        ObjectState* obj = it->saveState();
        state->addChild(obj);
    }
    for (auto const& val : operations_) {
        ObjectState* obj = new ObjectState(OSKEY_OTA_OPERATION_NAME);
        obj->setAttribute(OSKEY_OPERATION_NAME, val.first);
        obj->setAttribute(OSKEY_OPERATION_ENCODING_NAME, val.second);
        state->addChild(obj);
    }
    return state;
}
References ObjectState::addChild(), encodings_, name_, operations_, OSKEY_INSTRUCTION_FORMAT_NAME, OSKEY_OPERATION_ENCODING_NAME, OSKEY_OPERATION_NAME, OSKEY_OTA_OPERATION_NAME, OSNAME_INSTRUCTION_FORMAT, OperationTriggeredEncoding::saveState(), and ObjectState::setAttribute().
setName()
void InstructionFormat::setName (const std::string & name)
Sets the name of the instruction format.
Parameters
name The name of the instruction format.
Definition at line 126 of file InstructionFormat.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by loadState().
width()
int InstructionFormat::width () const virtual
Returns the bit width of the instruction format.
Returns
Bit width of the instruction format.
Definition at line 185 of file InstructionFormat.cc.
{
    int width = 0;
    for (unsigned int i = 0; i < encodings_.size(); i++) {
        OperationTriggeredEncoding* slot = encodings_.at(i);
        width += slot->width();
    }
    return width;
}
References encodings_, width(), and OperationTriggeredEncoding::width().
Referenced by width().
Member Data Documentation
encodings_
std::vector<OperationTriggeredEncoding*> InstructionFormat::encodings_ private
Definition at line 90 of file InstructionFormat.hh.
Referenced by addEncoding(), childFieldCount(), saveState(), and width().
name_
std::string InstructionFormat::name_ private
Definition at line 87 of file InstructionFormat.hh.
Referenced by name(), saveState(), and setName().
operations_
std::map<std::string, int> InstructionFormat::operations_ private
Definition at line 91 of file InstructionFormat.hh.
Referenced by addOperation(), encoding(), hasOperation(), operationAtIndex(), operationCount(), and saveState().
OSKEY_INSTRUCTION_FORMAT_NAME
const std::string InstructionFormat::OSKEY_INSTRUCTION_FORMAT_NAME = "name" static
Definition at line 79 of file InstructionFormat.hh.
Referenced by loadState(), and saveState().
OSKEY_OPERATION_ENCODING_NAME
const std::string InstructionFormat::OSKEY_OPERATION_ENCODING_NAME static
Initial value:
=
    "encoding"
Definition at line 82 of file InstructionFormat.hh.
Referenced by loadState(), and saveState().
OSKEY_OPERATION_NAME
const std::string InstructionFormat::OSKEY_OPERATION_NAME = "name" static
Definition at line 81 of file InstructionFormat.hh.
Referenced by loadState(), and saveState().
OSKEY_OTA_OPERATION_NAME
const std::string InstructionFormat::OSKEY_OTA_OPERATION_NAME static
Initial value:
=
    "ota-operation"
Definition at line 80 of file InstructionFormat.hh.
Referenced by loadState(), and saveState().
OSNAME_INSTRUCTION_FORMAT
const std::string InstructionFormat::OSNAME_INSTRUCTION_FORMAT = "ota-format" static
Definition at line 78 of file InstructionFormat.hh.
Referenced by BEMSerializer::convertToFileFormat(), and saveState().
parent_
BinaryEncoding* InstructionFormat::parent_ private
Definition at line 88 of file InstructionFormat.hh.
Referenced by InstructionFormat(), InstructionFormat(), and parent().
The documentation for this class was generated from the following files:
InstructionFormat.hh
InstructionFormat.cc