OpenASIP: InnerLoopFinder::InnerLoopInfo Class Reference
InnerLoopFinder::InnerLoopInfo Class Reference
#include <InnerLoopFinder.hh>
Public Member Functions
InnerLoopInfo ()
InnerLoopInfo (int tripCount)
int tripCount () const
bool isTripCountKnown () const
Private Attributes
int tripCount_
Detailed Description
Definition at line 32 of file InnerLoopFinder.hh.
Constructor & Destructor Documentation
InnerLoopInfo() [1/2]
InnerLoopFinder::InnerLoopInfo::InnerLoopInfo () inline
Definition at line 34 of file InnerLoopFinder.hh.
: tripCount_(0) {}
InnerLoopInfo() [2/2]
InnerLoopFinder::InnerLoopInfo::InnerLoopInfo (int tripCount) inline
Definition at line 35 of file InnerLoopFinder.hh.
{ tripCount_ = tripCount; }
References tripCount(), and tripCount_.
Member Function Documentation
isTripCountKnown()
bool InnerLoopFinder::InnerLoopInfo::isTripCountKnown () const inline
Definition at line 37 of file InnerLoopFinder.hh.
{ return tripCount_ > 0; }
References tripCount_.
Referenced by llvm::LLVMTCEIRBuilder::buildTCECFG().
tripCount()
int InnerLoopFinder::InnerLoopInfo::tripCount () const inline
Definition at line 36 of file InnerLoopFinder.hh.
{ return tripCount_; }
References tripCount_.
Referenced by llvm::LLVMTCEIRBuilder::buildTCECFG(), and InnerLoopInfo().
Member Data Documentation
tripCount_
int InnerLoopFinder::InnerLoopInfo::tripCount_ private
Definition at line 39 of file InnerLoopFinder.hh.
Referenced by InnerLoopInfo(), isTripCountKnown(), and tripCount().
The documentation for this class was generated from the following file:
InnerLoopFinder.hh