OpenASIP: DisasmExecPercentageAttrProvider Class Reference
DisasmExecPercentageAttrProvider Class Reference
#include <DisasmExecPercentageAttrProvider.hh>
Public Member Functions
DisasmExecPercentageAttrProvider (const TracedSimulatorFrontend &simulator)
virtual ~DisasmExecPercentageAttrProvider ()
virtual wxGridCellAttr * moveCellAttr (InstructionAddress address, int move)
Public Member Functions inherited from ProximDisasmAttrProvider
ProximDisasmAttrProvider ()
virtual ~ProximDisasmAttrProvider ()
virtual void update ()
Private Attributes
const TracedSimulatorFrontend & simulator_
Detailed Description
Proxim disassembly attribute provider, which highlights moves based on execution count ratio to the simulated cycle count.
Definition at line 44 of file DisasmExecPercentageAttrProvider.hh.
Constructor & Destructor Documentation
DisasmExecPercentageAttrProvider()
DisasmExecPercentageAttrProvider::DisasmExecPercentageAttrProvider (const TracedSimulatorFrontend & simulator)
The Constructor.
Parameters
simulator Simulator frontend for accessing instructions and execution counts.
Definition at line 49 of file DisasmExecPercentageAttrProvider.cc.
                                             :
    ProximDisasmAttrProvider(), simulator_(simulator) {
}
~DisasmExecPercentageAttrProvider()
DisasmExecPercentageAttrProvider::~DisasmExecPercentageAttrProvider () virtual
The Destructor.
Definition at line 58 of file DisasmExecPercentageAttrProvider.cc.
{
}
Member Function Documentation
moveCellAttr()
wxGridCellAttr * DisasmExecPercentageAttrProvider::moveCellAttr (InstructionAddress address, int move) virtual
Returns grid cell attributes for cell with given move.
Parameters
address Address of the cell's instruction.
Implements ProximDisasmAttrProvider.
Definition at line 68 of file DisasmExecPercentageAttrProvider.cc.
{
    assert(simulator_.isProgramLoaded());
    wxGridCellAttr* attr = new wxGridCellAttr();
    const ExecutableInstruction& ins =
        simulator_.executableInstructionAt(address);
    const TTAProgram::Program& program = simulator_.program();
    const TTAMachine::Machine::BusNavigator& nav =
        program.targetProcessor().busNavigator();
    assert(move >= 0);
    if (move >= nav.count()) {
        // No highlight for immediate slots.
        return attr;
    }
    const TTAMachine::Bus* moveBus = nav.item(move);
    const TTAProgram::Instruction& instruction =
        program.instructionAt(address);
    // Search for the correct move index in the instruction.
    // TTAProgram::Instruction doesn't contain nops and the move indexing
    // differs from the busNavigator and disassembly grid indexing.
    int index = 0;
    for (; index < instruction.moveCount(); index++) {
        if (moveBus == &instruction.move(index).bus()) {
            break;
        }
    }
    ClockCycleCount executions = 0;
    if (index < instruction.moveCount()) {
        executions = ins.moveExecutionCount(index);
    }
    if (executions > 0) {
        ClockCycleCount cycles = simulator_.cycleCount();
        int colour = static_cast<int>(
            5 * 255 * sin((executions / cycles) * 0.5 * 3.1415926));
        if (colour > 255) colour = 255;
        attr->SetBackgroundColour(
            wxColour(255, 255 - colour, 255 - colour));
    } else {
        // Gray background colour for moves that are not executed at all.
        attr->SetBackgroundColour(wxColour(220, 220, 220));
    }
    return attr;
}
References assert, TTAProgram::Move::bus(), TTAMachine::Machine::Navigator< ComponentType >::count(), SimulatorFrontend::cycleCount(), SimulatorFrontend::executableInstructionAt(), SimulatorFrontend::isProgramLoaded(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAProgram::Instruction::move(), TTAProgram::Instruction::moveCount(), ExecutableInstruction::moveExecutionCount(), program, SimulatorFrontend::program(), and simulator_.
Member Data Documentation
simulator_
const TracedSimulatorFrontend& DisasmExecPercentageAttrProvider::simulator_ private
Definition at line 52 of file DisasmExecPercentageAttrProvider.hh.
Referenced by moveCellAttr().
The documentation for this class was generated from the following files:
DisasmExecPercentageAttrProvider.hh
DisasmExecPercentageAttrProvider.cc