OpenASIP: AddressSpacesDialog Class Reference
AddressSpacesDialog Class Reference
#include <AddressSpacesDialog.hh>
Public Member Functions
AddressSpacesDialog (wxWindow *parent, TTAMachine::Machine *machine)
~AddressSpacesDialog ()
Private Types
enum {
ID_ADD = 10000 , ID_EDIT , ID_HELP , ID_DELETE ,
ID_LIST , ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
TTAMachine::AddressSpace * selectedAS ()
void updateASList ()
void onAdd (wxCommandEvent &event)
void onActivateAS (wxListEvent &event)
void onEdit (wxCommandEvent &event)
void onDelete (wxCommandEvent &event)
void onASSelection (wxListEvent &event)
void onASRightClick (wxListEvent &event)
void setTexts ()
Private Attributes
TTAMachine::Machine * machine_
Machine containing the address spaces to list.
wxListCtrl * asList_
List control for listing the address spaces.
Detailed Description
Dialog for listing and editing address spaces of the machine.
Definition at line 48 of file AddressSpacesDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_ADD
ID_EDIT
ID_HELP
ID_DELETE
ID_LIST
ID_LINE
Definition at line 71 of file AddressSpacesDialog.hh.
         {
        ID_ADD = 10000,
        ID_EDIT,
        ID_HELP,
        ID_DELETE,
        ID_LIST,
        ID_LINE
    };
Constructor & Destructor Documentation
AddressSpacesDialog()
AddressSpacesDialog::AddressSpacesDialog (wxWindow * parent, TTAMachine::Machine * machine)
The Constructor.
Parameters
parent Parent window of the dialog.
machine Machine containing the address spaces.
Definition at line 81 of file AddressSpacesDialog.cc.
                     :
    wxDialog(parent, -1, _T(""), wxDefaultPosition, wxSize(400,300)),
    machine_(machine) {
    createContents(this, true, true);
    asList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    FindWindow(ID_EDIT)->Disable();
    FindWindow(ID_DELETE)->Disable();
    // set texts to widgets
    setTexts();
    updateASList();
}
~AddressSpacesDialog()
AddressSpacesDialog::~AddressSpacesDialog ()
The Destructor.
Definition at line 104 of file AddressSpacesDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * AddressSpacesDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 352 of file AddressSpacesDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_LIST, wxDefaultPosition, wxSize(400,200), wxLC_REPORT|wxLC_SINGLE_SEL );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxGridSizer *item2 = new wxGridSizer( 3, 0, 0 );
    wxButton *item3 = new wxButton( parent, ID_ADD, wxT("&Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_EDIT, wxT("&Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item5 = new wxButton( parent, ID_DELETE, wxT("&Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxGROW, 5 );
    wxStaticLine *item6 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item6, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item7 = new wxGridSizer( 2, 0, 0 );
    wxButton *item8 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALL, 5 );
    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item7->Add( item9, 0, wxALL, 5 );
    item0->Add( item7, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD, ID_DELETE, ID_EDIT, ID_HELP, ID_LINE, and ID_LIST.
onActivateAS()
void AddressSpacesDialog::onActivateAS (wxListEvent & event) private
Handles left mouse button double click on the address space list.
Opens the clicked address space in an AddressSpaceDialog.
Definition at line 233 of file AddressSpacesDialog.cc.
{
    wxCommandEvent dummy;
    onEdit(dummy);
}
References dummy, and onEdit().
onAdd()
void AddressSpacesDialog::onAdd (wxCommandEvent & event) private
Creates and shows an address space dialog with default values set for adding an address space.
Definition at line 194 of file AddressSpacesDialog.cc.
{
    // Generate name for the new AS.
    Machine::AddressSpaceNavigator navigator =
        machine_->addressSpaceNavigator();
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_AS +
        Conversion::toString(i);
    while (navigator.hasItem(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_AS +
            Conversion::toString(i);
        i++;
    }
    AddressSpace* newAS =
    new AddressSpace(newName,
             ModelConstants::DEFAULT_AS_MAU_WIDTH,
             ModelConstants::DEFAULT_AS_MIN_ADDRESS,
             ModelConstants::DEFAULT_AS_MAX_ADDRESS,
             *machine_);
    AddressSpaceDialog dialog(this, machine_, newAS);
    if (dialog.ShowModal() == wxID_OK) {
    updateASList();
    } else {
    // The dialog was cancelled.
    delete newAS;
    }
}
References TTAMachine::Machine::addressSpaceNavigator(), ProDeConstants::COMP_NEW_NAME_PREFIX_AS, ModelConstants::DEFAULT_AS_MAU_WIDTH, ModelConstants::DEFAULT_AS_MAX_ADDRESS, ModelConstants::DEFAULT_AS_MIN_ADDRESS, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), machine_, Conversion::toString(), and updateASList().
onASRightClick()
void AddressSpacesDialog::onASRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button is pressed on the list.
Parameters
event Information about right mouse click event.
Definition at line 320 of file AddressSpacesDialog.cc.
{
    asList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                          wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE, WxConversion::toWxString(button.str()));
    asList_->PopupMenu(contextMenu, event.GetPoint());
}
References asList_, ID_DELETE, ID_EDIT, ProDeTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onASSelection()
void AddressSpacesDialog::onASSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the address space list.
If an address space is selected, buttons are enabled. If no address space is selected the buttons will be disabled.
Definition at line 280 of file AddressSpacesDialog.cc.
{
    if (asList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE)->Disable();
        FindWindow(ID_EDIT)->Disable();
        return;
    }
    FindWindow(ID_DELETE)->Enable();
    FindWindow(ID_EDIT)->Enable();
}
References asList_, ID_DELETE, and ID_EDIT.
onDelete()
void AddressSpacesDialog::onDelete (wxCommandEvent & event) private
Handles the 'Delete' button event.
Deletes the selected address space.
Definition at line 267 of file AddressSpacesDialog.cc.
{
    delete selectedAS();
    updateASList();
}
References selectedAS(), and updateASList().
onEdit()
void AddressSpacesDialog::onEdit (wxCommandEvent & event) private
Handles the 'Edit' button event.
Opens an AddressSpaceDialog with the selected address space's attributes set.
Definition at line 246 of file AddressSpacesDialog.cc.
{
    AddressSpace* selected = selectedAS();
    if (selected == NULL) {
        // No address space selected.
        return;
    }
    AddressSpaceDialog dialog(this, machine_, selectedAS());
    dialog.ShowModal();
    updateASList();
}
References machine_, selectedAS(), and updateASList().
Referenced by onActivateAS().
selectedAS()
AddressSpace * AddressSpacesDialog::selectedAS () private
Returns pointer to the AddressSpace, which is selected on the list.
Returns
The selected address space, or NULL if no address space is selected.
Definition at line 166 of file AddressSpacesDialog.cc.
{
    long item = -1;
    item = asList_->GetNextItem(
    item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
    return NULL;
    }
    string asName = WxConversion::toString(asList_->GetItemText(item));
    Machine::AddressSpaceNavigator navigator =
    machine_->addressSpaceNavigator();
    if (!navigator.hasItem(asName)) {
        return NULL;
    }
    return navigator.item(asName);
}
References TTAMachine::Machine::addressSpaceNavigator(), asList_, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, and WxConversion::toString().
Referenced by onDelete(), and onEdit().
setTexts()
void AddressSpacesDialog::setTexts () private
Sets texts for widgets.
Definition at line 112 of file AddressSpacesDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_ADDRESS_SPACES_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    // Create address space list column.
    wxListCtrl* portList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_LIST));
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    portList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_MAU);
    portList->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 40);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_MIN_ADDRESS);
    portList->InsertColumn(2, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 90);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_MAX_ADDRESS);
    portList->InsertColumn(3, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 90);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_BIT_WIDTH);
    portList->InsertColumn(4, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 80);
}
References ID_ADD, ID_DELETE, ID_EDIT, ID_HELP, ID_LIST, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_ADDRESS_SPACES_DIALOG_TITLE, GUITextGenerator::TXT_BUTTON_ADD_DIALOG, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_BIT_WIDTH, ProDeTextGenerator::TXT_COLUMN_MAU, ProDeTextGenerator::TXT_COLUMN_MAX_ADDRESS, ProDeTextGenerator::TXT_COLUMN_MIN_ADDRESS, and ProDeTextGenerator::TXT_COLUMN_NAME.
updateASList()
void AddressSpacesDialog::updateASList () private
Updates the address space list.
Definition at line 295 of file AddressSpacesDialog.cc.
{
    Machine::AddressSpaceNavigator asNavigator =
    machine_->addressSpaceNavigator();
    asList_->DeleteAllItems();
    for (int i = 0; i < asNavigator.count(); i++) {
        AddressSpace* as = asNavigator.item(i);
        int bitWidth = MathTools::requiredBits(as->end());
        asList_->InsertItem(i, WxConversion::toWxString(as->name()));
        asList_->SetItem(i, 1, WxConversion::toWxString(as->width()));
        asList_->SetItem(i, 2, WxConversion::toWxString(as->start()));
        asList_->SetItem(i, 3, WxConversion::toWxString(as->end()));
        asList_->SetItem(i, 4, WxConversion::toWxString(bitWidth));
    }
}
References TTAMachine::Machine::addressSpaceNavigator(), asList_, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::AddressSpace::end(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), MathTools::requiredBits(), TTAMachine::AddressSpace::start(), WxConversion::toWxString(), and TTAMachine::AddressSpace::width().
Referenced by onAdd(), onDelete(), and onEdit().
Member Data Documentation
asList_
wxListCtrl* AddressSpacesDialog::asList_ private
List control for listing the address spaces.
Definition at line 68 of file AddressSpacesDialog.hh.
Referenced by onASRightClick(), onASSelection(), selectedAS(), and updateASList().
machine_
TTAMachine::Machine* AddressSpacesDialog::machine_ private
Machine containing the address spaces to list.
Definition at line 66 of file AddressSpacesDialog.hh.
Referenced by onAdd(), onEdit(), selectedAS(), and updateASList().
The documentation for this class was generated from the following files:
AddressSpacesDialog.hh
AddressSpacesDialog.cc