OpenASIP: RFPortDialog Class Reference
RFPortDialog Class Reference
#include <RFPortDialog.hh>
Public Member Functions
RFPortDialog (wxWindow *parent, TTAMachine::Port *port)
virtual ~RFPortDialog ()
Private Types
enum { ID_NAME = 10000 , ID_INPUT_SOCKET , ID_OUTPUT_SOCKET , ID_HELP }
enumerated IDs for the port controls
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void onSocketChoice (wxCommandEvent &event)
void updateSockets ()
void setTexts ()
Private Attributes
TTAMachine::Port * port_
Port to modify.
wxString name_
Name of the port.
wxChoice * inputSocketChoice_
Input socket choice control.
wxChoice * outputSocketChoice_
Output socket choice control.
TTAMachine::Socket * oldInput_
Original input socket of the port.
TTAMachine::Socket * oldOutput_
Original output socket of the port.
Detailed Description
Dialog for querying register file port parameters from the user.
Definition at line 44 of file RFPortDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for the port controls
Enumerator
ID_NAME
ID_INPUT_SOCKET
ID_OUTPUT_SOCKET
ID_HELP
Definition at line 74 of file RFPortDialog.hh.
         {
    ID_NAME = 10000,
    ID_INPUT_SOCKET,
    ID_OUTPUT_SOCKET,
    ID_HELP
    };
Constructor & Destructor Documentation
RFPortDialog()
RFPortDialog::RFPortDialog (wxWindow * parent, TTAMachine::Port * port)
The Constructor.
Parameters
parent Parent window of the dialog.
port Port to modify.
Definition at line 71 of file RFPortDialog.cc.
               :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    port_(port),
    name_(_T("")),
    inputSocketChoice_(NULL),
    outputSocketChoice_(NULL) {
    oldInput_ = port_->inputSocket();
    oldOutput_ = port_->outputSocket();
    createContents(this, true, true);
    FindWindow(wxID_OK)->Disable();
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
~RFPortDialog()
RFPortDialog::~RFPortDialog () virtual
The Destructor.
Definition at line 94 of file RFPortDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * RFPortDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window. Initially generated with wxDesigner, the code will be cleaned up later.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 340 of file RFPortDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    // name element
    wxStaticText *item2 =
    new wxStaticText( parent, -1, wxT("Name:"),
              wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 =
    new wxTextCtrl(parent, ID_NAME, wxT(""), wxDefaultPosition,
               wxSize(160,-1), 0,
                       wxTextValidator(wxFILTER_ASCII, &name_) );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    // input socket element
    wxStaticText *item4 =
    new wxStaticText(parent, -1, wxT("Input Socket:"),
             wxDefaultPosition, wxDefaultSize, 0);
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    inputSocketChoice_ =
    new wxChoice(parent, ID_INPUT_SOCKET, wxDefaultPosition,
             wxSize(100,-1), 0, strs5, 0);
    item1->Add( inputSocketChoice_, 0,
                wxGROW|wxALL, 5 );
    // output socket element
    wxStaticText *item6 =
    new wxStaticText(parent, -1, wxT("Output Socket:"),
             wxDefaultPosition, wxDefaultSize, 0);
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString *strs7 = (wxString*) NULL;
    outputSocketChoice_ =
    new wxChoice(parent, ID_OUTPUT_SOCKET, wxDefaultPosition,
             wxSize(100,-1), 0, strs7, 0);
    item1->Add( outputSocketChoice_, 0,
                wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item8 =
    new wxStaticLine(parent, -1, wxDefaultPosition, wxSize(20,-1),
             wxLI_HORIZONTAL);
    item0->Add( item8, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );
    // buttons
    wxButton *item10 =
    new wxButton(parent, ID_HELP, wxT("&Help"), wxDefaultPosition,
             wxDefaultSize, 0);
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 =
    new wxButton(parent, wxID_OK, wxT("&OK"), wxDefaultPosition,
             wxDefaultSize, 0);
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item12 =
    new wxButton(parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition,
             wxDefaultSize, 0);
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer) {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    return item0;
}
References ID_HELP, ID_INPUT_SOCKET, ID_NAME, ID_OUTPUT_SOCKET, inputSocketChoice_, name_, outputSocketChoice_, and TRUE.
onCancel()
void RFPortDialog::onCancel (wxCommandEvent & event) private
Resets the original output and input sockets for the port and closes the dialog.
Definition at line 198 of file RFPortDialog.cc.
{
    port_->detachAllSockets();
    if (oldInput_ != NULL) {
        port_->attachSocket(*oldInput_);
    }
    if (oldOutput_ != NULL) {
        port_->attachSocket(*oldOutput_);
    }
    EndModal(wxID_CANCEL);
}
References TTAMachine::Port::attachSocket(), TTAMachine::Port::detachAllSockets(), oldInput_, oldOutput_, and port_.
onHelp()
void RFPortDialog::onHelp (wxCommandEvent & event) private
onName()
void RFPortDialog::onName (wxCommandEvent & event) private
Validates input in the controls, and updates the ComponentDescriptor.
Definition at line 318 of file RFPortDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void RFPortDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the port.
Definition at line 135 of file RFPortDialog.cc.
{
    if (!Validate()) {
    return;
    }
    if (!TransferDataFromWindow()) {
    return;
    }
    string trimmedName =
    WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // check whether RF already has a port of tht name.
    if (port_->name() != trimmedName) {
    Unit* rf = port_->parentUnit();
        for (int i = 0; i < rf->portCount(); i++) {
            string name = rf->port(i)->name();
            if (name == WxConversion::toString(name_)) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_port =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_PORT);
                format rf =
                    prodeTexts->text(ProDeTextGenerator::COMP_REGISTER_FILE);
                format port =
                    prodeTexts->text(ProDeTextGenerator::COMP_PORT);
                message % trimmedName % a_port.str() % rf.str() % port.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    port_->setName(trimmedName);
    // update parent RFs max write and read parameters
    RegisterFile* RF = dynamic_cast<RegisterFile*>(port_->parentUnit());
    assert (RF != NULL);
    //RF->updateMaxReadsAndWrites();
    EndModal(wxID_OK);
}
References assert, ProDeTextGenerator::COMP_A_PORT, ProDeTextGenerator::COMP_PORT, ProDeTextGenerator::COMP_REGISTER_FILE, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Port::name(), name_, TTAMachine::Port::parentUnit(), TTAMachine::Unit::port(), port_, TTAMachine::Unit::portCount(), RF, TTAMachine::Port::setName(), Texts::TextGenerator::text(), WxConversion::toString(), and WxConversion::toWxString().
onSocketChoice()
void RFPortDialog::onSocketChoice (wxCommandEvent & event) private
Updates the port object when user changes input/output socket selection.
Definition at line 225 of file RFPortDialog.cc.
{
    port_->detachAllSockets();
    Machine::SocketNavigator navigator =
        port_->parentUnit()->machine()->socketNavigator();
    // set input socket
    string inputSocketName =
        WxConversion::toString(inputSocketChoice_->GetStringSelection());
    if (inputSocketName != WxConversion::toString(ProDeConstants::NONE)) {
        port_->attachSocket(*(navigator.item(inputSocketName)));
    }
    // set output socket
    string outputSocketName =
    WxConversion::toString(outputSocketChoice_->GetStringSelection());
    if (outputSocketName != WxConversion::toString(ProDeConstants::NONE)) {
    port_->attachSocket(*(navigator.item(outputSocketName)));
    }
    updateSockets();
}
References TTAMachine::Port::attachSocket(), TTAMachine::Port::detachAllSockets(), inputSocketChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeConstants::NONE, outputSocketChoice_, TTAMachine::Port::parentUnit(), port_, TTAMachine::Machine::socketNavigator(), WxConversion::toString(), and updateSockets().
setTexts()
void RFPortDialog::setTexts () private
Sets texts for widgets.
Definition at line 101 of file RFPortDialog.cc.
                       {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_RF_PORT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_INPUT_SOCKET),
                          ProDeTextGenerator::TXT_LABEL_INPUT_SOCKET);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_OUTPUT_SOCKET),
                          ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET);
}
References ID_HELP, ID_INPUT_SOCKET, ID_NAME, ID_OUTPUT_SOCKET, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_LABEL_INPUT_SOCKET, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET, and ProDeTextGenerator::TXT_RF_PORT_DIALOG_TITLE.
TransferDataToWindow()
bool RFPortDialog::TransferDataToWindow () private virtual
Transfers data from the port object to the dialog widgets.
Returns
False, if an error occured in the transfer.
Definition at line 215 of file RFPortDialog.cc.
{
    name_ = WxConversion::toWxString(port_->name());
    updateSockets();
    return wxWindow::TransferDataToWindow();
}
References TTAMachine::Port::name(), name_, port_, WxConversion::toWxString(), and updateSockets().
updateSockets()
void RFPortDialog::updateSockets () private
Updates input and output socket choicers.
Definition at line 250 of file RFPortDialog.cc.
{
    inputSocketChoice_->Clear();
    inputSocketChoice_->Append(ProDeConstants::NONE);
    outputSocketChoice_->Clear();
    outputSocketChoice_->Append(ProDeConstants::NONE);
    MachineTester tester(*(port_->parentUnit()->machine()));
    // Add ports to the choicers
    Machine::SocketNavigator navigator =
    port_->parentUnit()->machine()->socketNavigator();
    for (int i = 0; i < navigator.count(); i++) {
    Socket* socket = navigator.item(i);
    wxString socketName = WxConversion::toWxString(socket->name());
    // Add available input sockets.
    Socket* input = port_->inputSocket();
    if (input != NULL) {
        port_->detachSocket(*input);
    }
    bool legal = tester.canConnect(*socket, *port_);
        if (legal && socket->direction() == Socket::INPUT) {
        inputSocketChoice_->Append(socketName);
    }
    if (input != NULL) {
        port_->attachSocket(*input);
    }
    // Add available output sockets.
    Socket* output = port_->outputSocket();
    if (output != NULL) {
        port_->detachSocket(*output);
    }
        legal = tester.canConnect(*socket, *port_);
    if (legal && socket->direction() == Socket::OUTPUT) {
        outputSocketChoice_->Append(socketName);
    }
    if (output != NULL) {
        port_->attachSocket(*output);
    }
    // ignore sockets with unknown direction
    }
    // set input socket choice
    if (port_->inputSocket() == NULL) {
    inputSocketChoice_->SetStringSelection(ProDeConstants::NONE);
    } else {
    wxString socketName =
        WxConversion::toWxString(port_->inputSocket()->name());
    inputSocketChoice_->SetStringSelection(socketName);
    }
    // set output socket choice
    if (port_->outputSocket() == NULL) {
    outputSocketChoice_->SetStringSelection(ProDeConstants::NONE);
    } else {
    wxString socketName =
        WxConversion::toWxString(port_->outputSocket()->name());
    outputSocketChoice_->SetStringSelection(socketName);
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Port::detachSocket(), TTAMachine::Socket::direction(), TTAMachine::Socket::INPUT, TTAMachine::Port::inputSocket(), inputSocketChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ProDeConstants::NONE, TTAMachine::Socket::OUTPUT, TTAMachine::Port::outputSocket(), outputSocketChoice_, TTAMachine::Port::parentUnit(), port_, TTAMachine::Machine::socketNavigator(), and WxConversion::toWxString().
Referenced by onSocketChoice(), and TransferDataToWindow().
Member Data Documentation
inputSocketChoice_
wxChoice* RFPortDialog::inputSocketChoice_ private
Input socket choice control.
Definition at line 65 of file RFPortDialog.hh.
Referenced by createContents(), onSocketChoice(), and updateSockets().
name_
wxString RFPortDialog::name_ private
Name of the port.
Definition at line 63 of file RFPortDialog.hh.
Referenced by createContents(), onName(), onOK(), and TransferDataToWindow().
oldInput_
TTAMachine::Socket* RFPortDialog::oldInput_ private
Original input socket of the port.
Definition at line 69 of file RFPortDialog.hh.
Referenced by onCancel().
oldOutput_
TTAMachine::Socket* RFPortDialog::oldOutput_ private
Original output socket of the port.
Definition at line 71 of file RFPortDialog.hh.
Referenced by onCancel().
outputSocketChoice_
wxChoice* RFPortDialog::outputSocketChoice_ private
Output socket choice control.
Definition at line 67 of file RFPortDialog.hh.
Referenced by createContents(), onSocketChoice(), and updateSockets().
port_
TTAMachine::Port* RFPortDialog::port_ private
Port to modify.
Definition at line 61 of file RFPortDialog.hh.
Referenced by onCancel(), onOK(), onSocketChoice(), TransferDataToWindow(), and updateSockets().
The documentation for this class was generated from the following files:
RFPortDialog.hh
RFPortDialog.cc