OpenASIP: ProximIUDetailsCmd Class Reference
ProximIUDetailsCmd Class Reference
#include <ProximIUDetailsCmd.hh>
Public Member Functions
ProximIUDetailsCmd (const TTAMachine::ImmediateUnit &iu)
virtual ~ProximIUDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::ImmediateUnit & iu_
Immediate unit to display.
Detailed Description
Command for displaying immediate unit details in the machine window component details pane.
Definition at line 46 of file ProximIUDetailsCmd.hh.
Constructor & Destructor Documentation
ProximIUDetailsCmd()
ProximIUDetailsCmd::ProximIUDetailsCmd (const TTAMachine::ImmediateUnit & iu)
The Constructor.
Parameters
iu Immediate unit to display.
Definition at line 53 of file ProximIUDetailsCmd.cc.
                                                                        :
    ComponentCommand(), iu_(iu) {
}
~ProximIUDetailsCmd()
ProximIUDetailsCmd::~ProximIUDetailsCmd () virtual
The Destructor.
Definition at line 61 of file ProximIUDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximIUDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 68 of file ProximIUDetailsCmd.cc.
                       {
    string iuName = iu_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    MachineState& machineState = ProximToolbox::frontend()->machineState();
    const UtilizationStats& stats =
        ProximToolbox::frontend()->utilizationStatistics();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_IU_LABEL);
    machineWin->appendDetails(iuName + "\n\n");
    // Append registers to the details widget.
    machineWin->appendDetails(
        ProximConstants::MACH_WIN_IMMEDIATES_TITLE + "\n");
    LongImmediateUnitState& iuState =
        machineState.longImmediateUnitState(iuName);
    for (int i = 0; i < iuState.immediateRegisterCount(); i++) {
        machineWin->appendDetails("  " + Conversion::toString(i) + ":\t");
        int immValue = iuState.registerValue(i).sIntWordValue();
        machineWin->appendDetails(Conversion::toString(immValue) + "\n");
    }
    // Append register access statistics to the utilization widget.
    machineWin->appendUtilizationData("Register access statistics:\n\n");
    int usedRegCount = 0;
    for (int i = 0; i < iuState.immediateRegisterCount(); i++) {
        ClockCycleCount reads = stats.registerReads(iuName, i);
        ClockCycleCount writes = stats.registerWrites(iuName, i);
        if (reads > 0 || writes > 0) {
            usedRegCount++;
        }
        machineWin->appendUtilizationData(
            Conversion::toString(i) +  + ":  " +
            Conversion::toString(reads) + " reads, " +
            Conversion::toString(writes) + " writes.\n");
    }
    machineWin->appendUtilizationData(
        "\nTotal of " + Conversion::toString(usedRegCount) +
        " registers used.");
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximMachineStateWindow::appendUtilizationData(), ProximToolbox::frontend(), LongImmediateUnitState::immediateRegisterCount(), iu_, MachineState::longImmediateUnitState(), ProximConstants::MACH_WIN_IMMEDIATES_TITLE, ProximConstants::MACH_WIN_IU_LABEL, SimulatorFrontend::machineState(), ProximToolbox::machineStateWindow(), TTAMachine::Component::name(), UtilizationStats::registerReads(), LongImmediateUnitState::registerValue(), UtilizationStats::registerWrites(), SimValue::sIntWordValue(), Conversion::toString(), and SimulatorFrontend::utilizationStatistics().
Member Data Documentation
iu_
const TTAMachine::ImmediateUnit& ProximIUDetailsCmd::iu_ private
Immediate unit to display.
Definition at line 53 of file ProximIUDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximIUDetailsCmd.hh
ProximIUDetailsCmd.cc