OpenASIP: EntryKeyData Class Reference
EntryKeyData Class Reference abstract
#include <EntryKeyData.hh>
Public Member Functions
EntryKeyData ()
virtual ~EntryKeyData ()
virtual EntryKeyData * copy () const =0
Copies data.
virtual bool isEqual (const EntryKeyData *) const =0
Checks if two data are equal.
virtual bool isGreater (const EntryKeyData *) const =0
Checks if this data is greater than another data.
virtual bool isSmaller (const EntryKeyData *) const =0
Checks if this data is smaller than another data.
virtual double coefficient (const EntryKeyData *, const EntryKeyData *) const =0
Returns the relative position between two data.
virtual std::string toString () const =0
Converts the data into a string.
Private Member Functions
EntryKeyData (const EntryKeyData &)
Copying not allowed.
EntryKeyData & operator= (const EntryKeyData &)
Assignment not allowed.
Detailed Description
Interface for the data of the entry field.
Definition at line 53 of file EntryKeyData.hh.
Constructor & Destructor Documentation
EntryKeyData() [1/2]
EntryKeyData::EntryKeyData ()
Default constructor.
Definition at line 57 of file EntryKeyData.cc.
{
}
~EntryKeyData()
EntryKeyData::~EntryKeyData () virtual
Destructor.
Definition at line 63 of file EntryKeyData.cc.
{
}
EntryKeyData() [2/2]
EntryKeyData::EntryKeyData (const EntryKeyData &) private
Copying not allowed.
Member Function Documentation
coefficient()
virtual double EntryKeyData::coefficient (const EntryKeyData * , const EntryKeyData *) const pure virtual
Returns the relative position between two data.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::coefficient().
copy()
virtual EntryKeyData * EntryKeyData::copy () const pure virtual
Copies data.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::operator=().
isEqual()
virtual bool EntryKeyData::isEqual (const EntryKeyData *) const pure virtual
Checks if two data are equal.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::isEqual().
isGreater()
virtual bool EntryKeyData::isGreater (const EntryKeyData *) const pure virtual
Checks if this data is greater than another data.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::isGreater().
isSmaller()
virtual bool EntryKeyData::isSmaller (const EntryKeyData *) const pure virtual
Checks if this data is smaller than another data.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::isSmaller().
operator=()
EntryKeyData & EntryKeyData::operator= (const EntryKeyData &) private
Assignment not allowed.
toString()
virtual std::string EntryKeyData::toString () const pure virtual
Converts the data into a string.
Implemented in EntryKeyDataInt, EntryKeyDataDouble, EntryKeyDataOperationSet, EntryKeyDataBool, and EntryKeyDataFunctionUnit.
Referenced by EntryKeyField::toString().
The documentation for this class was generated from the following files:
EntryKeyData.hh
EntryKeyData.cc