OpenASIP: MachineEditPartFactory Class Reference
MachineEditPartFactory Class Reference
#include <MachineEditPartFactory.hh>
Public Member Functions
MachineEditPartFactory (EditPolicyFactory &editPolicyFactory)
virtual ~MachineEditPartFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
EditPart * createEditPart (TTAMachine::Machine *machine)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
MachineEditPartFactory & operator= (MachineEditPartFactory &old)
Assignment not allowed.
MachineEditPartFactory (MachineEditPartFactory &old)
Copying not allowed.
EditPart * getUnits (TTAMachine::Machine *machine)
EditPart * getSockets (TTAMachine::Machine *machine)
EditPart * getBusChains (TTAMachine::Machine *machine)
ConnectionEditPart * createBiDirBridge (ConnectionEditPart *bridge, TTAMachine::Bridge *opposite)
void findConnectedBridges (ConnectionEditPart *&bridgeEditPart, ConnectionEditPart *&biDirBridge, std::vector< TTAMachine::Bridge * > &bridges, TTAMachine::Bus *bus)
bool connected (const TTAMachine::Bridge *bridge, const TTAMachine::Bus *bus1, const TTAMachine::Bus *bus2)
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating EditParts from any Machine component or the Machine itself.
Definition at line 55 of file MachineEditPartFactory.hh.
Constructor & Destructor Documentation
MachineEditPartFactory() [1/2]
MachineEditPartFactory::MachineEditPartFactory (EditPolicyFactory & editPolicyFactory) explicit
The Constructor.
Definition at line 73 of file MachineEditPartFactory.cc.
                                          :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new GCUFactory(editPolicyFactory));
    registerFactory(new FUFactory(editPolicyFactory));
    registerFactory(new IUFactory(editPolicyFactory));
    registerFactory(new RFFactory(editPolicyFactory));
    registerFactory(new BridgeFactory(editPolicyFactory));
    registerFactory(new SocketFactory(editPolicyFactory));
    registerFactory(new BusFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~MachineEditPartFactory()
MachineEditPartFactory::~MachineEditPartFactory () virtual
The Destructor.
Definition at line 90 of file MachineEditPartFactory.cc.
{
}
MachineEditPartFactory() [2/2]
MachineEditPartFactory::MachineEditPartFactory (MachineEditPartFactory & old) private
Copying not allowed.
Member Function Documentation
connected()
bool MachineEditPartFactory::connected (const TTAMachine::Bridge * bridge, const TTAMachine::Bus * bus1, const TTAMachine::Bus * bus2) private
Tells whether a bridge is connected to two specific buses.
Parameters
bridge The bridge.
bus1 One bus.
bus2 The other bus.
Returns
True if the bridge is connected to the buses, false otherwise.
Definition at line 415 of file MachineEditPartFactory.cc.
                     {
    return (bridge->sourceBus() == bus1 &&
    bridge->destinationBus() == bus2) ||
    (bridge->destinationBus() == bus1 &&
    bridge->sourceBus() == bus2);
}
References TTAMachine::Bridge::destinationBus(), and TTAMachine::Bridge::sourceBus().
Referenced by findConnectedBridges().
createBiDirBridge()
ConnectionEditPart * MachineEditPartFactory::createBiDirBridge (ConnectionEditPart * bridge, TTAMachine::Bridge * opposite) private
Creates an EditPart for a bidirectional bridge.
Parameters
bridge EditPart representing one of the bridges.
opposite The opposite bridge.
Returns
EditPart for the bidirectional bridge.
Definition at line 340 of file MachineEditPartFactory.cc.
                      {
    ConnectionEditPart* biDirBridge = new ConnectionEditPart();
    biDirBridge->setSelectable(true);
    BidirBridgeFigure* fig = new BidirBridgeFigure();
    fig->setDirection(BridgeFigure::DIR_BIDIR);
    biDirBridge->setFigure(fig);
    EditPart* oppositeBridge = createEditPart(opposite);
    bridge->setSelectable(false);
    oppositeBridge->setSelectable(false);
    biDirBridge->setModel(bridge->model());
    biDirBridge->setSource(bridge->source());
    biDirBridge->setTarget(bridge->target());
    biDirBridge->installEditPolicy(
    editPolicyFactory_.createBridgeEditPolicy());
    biDirBridge->addChild(bridge);
    biDirBridge->addChild(oppositeBridge);
    return biDirBridge;
}
References EditPart::addChild(), EditPolicyFactory::createBridgeEditPolicy(), createEditPart(), BridgeFigure::DIR_BIDIR, EditPartFactory::editPolicyFactory_, EditPart::installEditPolicy(), EditPart::model(), BridgeFigure::setDirection(), EditPart::setFigure(), EditPart::setModel(), EditPart::setSelectable(), ConnectionEditPart::setSource(), ConnectionEditPart::setTarget(), ConnectionEditPart::source(), and ConnectionEditPart::target().
Referenced by findConnectedBridges().
createEditPart() [1/2]
EditPart * MachineEditPartFactory::createEditPart (TTAMachine::Machine * machine)
Overloaded implementation for creating the contents EditPart from the machine.
Parameters
machine Machine to create the EditPart from.
Returns
The created contents EditPart corresponding to the machine.
Definition at line 130 of file MachineEditPartFactory.cc.
{
    EditPart* contents = new EditPart();
    contents->setFigure(new ContentsFigure());
    contents->addChild(getUnits(machine));
    contents->addChild(getSockets(machine));
    contents->addChild(getBusChains(machine));
    return contents;
}
References EditPart::addChild(), getBusChains(), getSockets(), getUnits(), machine, and EditPart::setFigure().
createEditPart() [2/2]
EditPart * MachineEditPartFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Delegates to registered factories to create the EditPart.
Parameters
component Component of which to create the corresponding EditPart.
Returns
NULL if none of the factories can create the EditPart.
Implements Factory.
Definition at line 101 of file MachineEditPartFactory.cc.
{
    EditPart* ep = EditPartFactory::checkCache(component);
    if (ep != NULL) {
    return ep;
    }
    vector<Factory*>::const_iterator i = factories_.begin();
    for (; i != factories_.end(); i++) {
    ep = (*i)->createEditPart(component);
    if (ep != NULL) {
        EditPartFactory::writeToCache(ep);
        return ep;
    }
    }
    return NULL;
}
References EditPartFactory::checkCache(), EditPartFactory::factories_, and EditPartFactory::writeToCache().
Referenced by createBiDirBridge(), findConnectedBridges(), getBusChains(), getSockets(), getUnits(), and MachineCanvas::updateMachine().
findConnectedBridges()
void MachineEditPartFactory::findConnectedBridges (ConnectionEditPart *& bridgeEditPart, ConnectionEditPart *& biDirBridge, std::vector< TTAMachine::Bridge * > & bridges, TTAMachine::Bus * bus) private
Finds and returns the bridge or bridges that are connected to a bus.
Parameters
bridgeEditPart Where to store one bridge, no change if no bridge found.
biDirBridge Where to store the other bridge, no change if no other bridge found.
bridges Which bridges to search.
bus Bus to which the searched bridges should be connected.
Definition at line 377 of file MachineEditPartFactory.cc.
              {
    unsigned int j = 0;
    while (j < bridges.size()) {
    if (connected(bridges[j], bus, bus->nextBus())) {
        bridgeEditPart = dynamic_cast<ConnectionEditPart*>(
        createEditPart(bridges[j]));
        break;
    }
    j++;
    }
    // check if the bridge is bidirectional
    j++;
    while (j < bridges.size()) {
    if (connected(bridges[j], bus, bus->nextBus())) {
        biDirBridge =
        createBiDirBridge(bridgeEditPart, bridges[j]);
        break;
    }
    j++;
    }
}
References connected(), createBiDirBridge(), createEditPart(), and TTAMachine::Bus::nextBus().
Referenced by getBusChains().
getBusChains()
EditPart * MachineEditPartFactory::getBusChains (TTAMachine::Machine * machine) private
Navigates through the machine and creates a bus container EditPart.
Returns a NULL pointer if there are no buses in the given machine.
Parameters
machine Machine to navigate through.
Returns
An EditPart containing EditParts for all the buses and bus chains in the given machine or NULL if there aren't any.
Definition at line 239 of file MachineEditPartFactory.cc.
{
    Machine::BusNavigator busNav = machine->busNavigator();
    EditPart* busContainer = NULL;
    if (busNav.count() > 0) {
    set<Bus*> sorted;
    busContainer = new EditPart();
    busContainer->setFigure(new BusContainerFigure());
    vector<Bus*> buses;
    for (int i = 0; i < busNav.count(); i++) {
        buses.push_back(busNav.item(i));
    }
    // get bridges
    Machine::BridgeNavigator bridgeNav = machine->bridgeNavigator();
    vector<Bridge*> bridges;
    for (int i = 0; i < bridgeNav.count(); i++) {
        bridges.push_back(bridgeNav.item(i));
    }
    // sort the bus chains
    for (unsigned int i = 0; i < buses.size(); i++) {
        if (!ContainerTools::containsValue(sorted, buses[i])) {
        sorted.insert(buses[i]);
        Bus* first = buses[i];
        // browse to the beginning of the chain
        while (first->hasPreviousBus()) {
            first = first->previousBus();
        }
        // start adding buses to the chain
        if (first->hasNextBus()) {
            EditPart* busChain = new EditPart();
            busChain->setFigure(new BusChainFigure());
            while (true) {
            sorted.insert(first);
            // find also the bridge(s) in between
            ConnectionEditPart* bridgeEditPart = NULL;
            ConnectionEditPart* biDirBridge = NULL;
            if (first->hasNextBus()) {
                findConnectedBridges(
                bridgeEditPart, biDirBridge, bridges, first);
            }
            // add the bus and the following bridge to the chain
            EditPart* nextEditPart = createEditPart(first);
            assert(nextEditPart != NULL);
            busChain->addChild(nextEditPart);
            if (biDirBridge != NULL) {
                busChain->addChild(biDirBridge);
            } else if (bridgeEditPart != NULL) {
                busChain->addChild(bridgeEditPart);
            }
            if (first->hasNextBus()) {
                first = first->nextBus();
            } else {
                break;
            }
            }
            busContainer->addChild(busChain);
        } else {
            // add a single bus
            EditPart* busEditPart = createEditPart(buses[i]);
            assert(busEditPart != NULL);
            busContainer->addChild(busEditPart);
        }
        }
    }
    }
    return busContainer;
}
References EditPart::addChild(), assert, TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::busNavigator(), ContainerTools::containsValue(), TTAMachine::Machine::Navigator< ComponentType >::count(), createEditPart(), findConnectedBridges(), TTAMachine::Bus::hasNextBus(), TTAMachine::Bus::hasPreviousBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, TTAMachine::Bus::nextBus(), TTAMachine::Bus::previousBus(), and EditPart::setFigure().
Referenced by createEditPart().
getSockets()
EditPart * MachineEditPartFactory::getSockets (TTAMachine::Machine * machine) private
Navigates through the machine and creates a socket container EditPart.
Returns a NULL pointer if there are no sockets in the given machine.
Parameters
machine Machine to navigate through.
Returns
An EditPart containing EditParts for all the sockets in the given machine or NULL if there aren't any.
Definition at line 208 of file MachineEditPartFactory.cc.
{
    Machine::SocketNavigator socketNav = machine->socketNavigator();
    EditPart* sockets = NULL;
    if (socketNav.count() > 0) {
    sockets = new EditPart();
    sockets->setFigure(new SocketContainerFigure());
    for (int i = 0; i < socketNav.count(); i++) {
        Socket* socket = socketNav.item(i);
        EditPart* ep = createEditPart(socket);
        assert(ep != NULL);
        sockets->addChild(ep);
    }
    }
    return sockets;
}
References EditPart::addChild(), assert, TTAMachine::Machine::Navigator< ComponentType >::count(), createEditPart(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, EditPart::setFigure(), and TTAMachine::Machine::socketNavigator().
Referenced by createEditPart().
getUnits()
EditPart * MachineEditPartFactory::getUnits (TTAMachine::Machine * machine) private
Navigates through the machine and creates a unit container EditPart.
Returns a NULL pointer if there are no units in the given machine.
Parameters
machine Machine to navigate through.
Returns
An EditPart containing EditParts for all the units in the given machine or NULL if there aren't any.
Definition at line 152 of file MachineEditPartFactory.cc.
{
    Machine::FunctionUnitNavigator fuNav = machine->functionUnitNavigator();
    Machine::RegisterFileNavigator rfNav = machine->registerFileNavigator();
    Machine::ImmediateUnitNavigator iuNav = machine->immediateUnitNavigator();
    ControlUnit* gcu = machine->controlUnit();
    EditPart* units = NULL;
    if (fuNav.count() > 0 || rfNav.count() > 0 || iuNav.count() > 0 ||
    gcu != NULL) {
    units = new EditPart();
    units->setFigure(new UnitContainerFigure());
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit* fu = fuNav.item(i);
        EditPart* ep = createEditPart(fu);
        assert(ep != NULL);
        units->addChild(ep);
    }
    for (int i = 0; i < rfNav.count(); i++) {
        RegisterFile* rf = rfNav.item(i);
        EditPart* ep = createEditPart(rf);
        assert(ep != NULL);
        units->addChild(ep);
    }
    for (int i = 0; i < iuNav.count(); i++) {
        ImmediateUnit* iu = iuNav.item(i);
        EditPart* ep = createEditPart(iu);
        assert(ep != NULL);
        units->addChild(ep);
    }
    if (gcu != NULL) {
        EditPart* ep = createEditPart(gcu);
        assert(ep != NULL);
        units->addChild(ep);
    }
    }
    return units;
}
References EditPart::addChild(), assert, TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), createEditPart(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, TTAMachine::Machine::registerFileNavigator(), and EditPart::setFigure().
Referenced by createEditPart().
operator=()
MachineEditPartFactory & MachineEditPartFactory::operator= (MachineEditPartFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
MachineEditPartFactory.hh
MachineEditPartFactory.cc