OpenASIP: GuardField Class Reference
GuardField Class Reference
#include <GuardField.hh>
Public Member Functions
GuardField (MoveSlot &parent)
GuardField (const ObjectState *state, MoveSlot &parent)
virtual ~GuardField ()
MoveSlot * parent () const
void addGuardEncoding (GPRGuardEncoding &encoding)
void removeGuardEncoding (GPRGuardEncoding &encoding)
void addGuardEncoding (FUGuardEncoding &encoding)
void removeGuardEncoding (FUGuardEncoding &encoding)
void addGuardEncoding (UnconditionalGuardEncoding &encoding)
void removeUnconditionalGuardEncoding (UnconditionalGuardEncoding &encoding)
int gprGuardEncodingCount () const
GPRGuardEncoding & gprGuardEncoding (int index) const
bool hasGPRGuardEncoding (const std::string &regFile, int index, bool inverted) const
GPRGuardEncoding & gprGuardEncoding (const std::string &regFile, int index, bool inverted) const
int fuGuardEncodingCount () const
FUGuardEncoding & fuGuardEncoding (int index) const
bool hasFUGuardEncoding (const std::string &fu, const std::string &port, bool inverted) const
FUGuardEncoding & fuGuardEncoding (const std::string &fu, const std::string &port, bool inverted) const
bool hasUnconditionalGuardEncoding (bool inverted) const
UnconditionalGuardEncoding & unconditionalGuardEncoding (bool inverted) const
virtual int childFieldCount () const
virtual InstructionField & childField (int) const
virtual int width () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_GUARD_FIELD = "guard_field"
ObjectState name for guard field.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Types
typedef std::vector< GPRGuardEncoding * > GPRGuardTable
A container type for GPR guard encodings.
typedef std::vector< FUGuardEncoding * > FUGuardTable
A container type for FU guard encodings.
Private Member Functions
void deleteGPRGuardEncodings ()
void deleteFUGuardEncodings ()
void deleteUnconditionalGuardEncodings ()
bool isAssigned (unsigned int encoding) const
Private Attributes
GPRGuardTable gprGuards_
GPR guard encodings.
FUGuardTable fuGuards_
FU guard encodings.
UnconditionalGuardEncoding * alwaysTrue_
Unconditional guard encoding for always-true expression.
UnconditionalGuardEncoding * alwaysFalse_
Unconditional guard encoding for always-false expression.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
GuardField class represents the guard field of the move slot.
The guard field defines the guard expressions that control whether a data transport is completed or cancelled. A GuardField instance contains the control codes that identify the guard expressions supported by a given move slot. GuardField is an instruction field, hence it is derived from class InstructionField. GuardField instances cannot exist alone; they belong to a move slot and are registered to a MoveSlot object at construction time.
Definition at line 55 of file GuardField.hh.
Member Typedef Documentation
FUGuardTable
typedef std::vector<FUGuardEncoding*> GuardField::FUGuardTable private
A container type for FU guard encodings.
Definition at line 105 of file GuardField.hh.
GPRGuardTable
typedef std::vector<GPRGuardEncoding*> GuardField::GPRGuardTable private
A container type for GPR guard encodings.
Definition at line 103 of file GuardField.hh.
Constructor & Destructor Documentation
GuardField() [1/2]
GuardField::GuardField (MoveSlot & parent)
The constructor.
Registers the guard field to the parent move slot automatically.
Parameters
parent The parent move slot.
Exceptions
ObjectAlreadyExists If the parent move slot has a guard field already.
Definition at line 60 of file GuardField.cc.
    : InstructionField(&parent), alwaysTrue_(NULL), alwaysFalse_(NULL) {
    setParent(NULL);
    parent.setGuardField(*this);
    setParent(&parent);
    // update the relative position of the field
    int position(0);
    if (parent.hasSourceField()) {
    position++;
    }
    if (parent.hasDestinationField()) {
    position++;
    }
    InstructionField::setRelativePosition(position);
}
References MoveSlot::hasDestinationField(), MoveSlot::hasSourceField(), parent(), MoveSlot::setGuardField(), InstructionField::setParent(), and InstructionField::setRelativePosition().
GuardField() [2/2]
GuardField::GuardField (const ObjectState * state, MoveSlot & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent move slot.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the parent move slot has a guard field already.
Definition at line 89 of file GuardField.cc.
    : InstructionField(state, &parent), alwaysTrue_(NULL), alwaysFalse_(NULL) {
    loadState(state);
    setParent(NULL);
    parent.setGuardField(*this);
    setParent(&parent);
}
References loadState(), parent(), MoveSlot::setGuardField(), and InstructionField::setParent().
~GuardField()
GuardField::~GuardField () virtual
The destructor.
Definition at line 100 of file GuardField.cc.
{
    deleteGPRGuardEncodings();
    deleteFUGuardEncodings();
    deleteUnconditionalGuardEncodings();
    MoveSlot* oldParent = parent();
    setParent(NULL);
    assert(oldParent != NULL);
    oldParent->unsetGuardField();
}
References assert, deleteFUGuardEncodings(), deleteGPRGuardEncodings(), deleteUnconditionalGuardEncodings(), parent(), InstructionField::setParent(), and MoveSlot::unsetGuardField().
Member Function Documentation
addGuardEncoding() [1/3]
void GuardField::addGuardEncoding (FUGuardEncoding & encoding)
Adds a guard expression and its encoding to the set of expressions supported by this guard field.
This method is to be called from the constructor of FUGuardEncoding.
Parameters
encoding The encoding to be added.
Exceptions
ObjectAlreadyExists If the guard field already contains a guard encoding for the same guard expression or if the encoding is already assigned to another guard expression.
Definition at line 183 of file GuardField.cc.
{
    // verify that this is called from GPRGuardEncoding constructor
    assert(encoding.parent() == NULL);
    if (hasFUGuardEncoding(
        encoding.functionUnit(), encoding.port(),
        encoding.isGuardInverted()) || isAssigned(encoding.encoding())) {
    const string procName = "GuardField::addGuardEncoding";
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    fuGuards_.push_back(&encoding);
}
References assert, GuardEncoding::encoding(), fuGuards_, FUGuardEncoding::functionUnit(), hasFUGuardEncoding(), isAssigned(), GuardEncoding::isGuardInverted(), GuardEncoding::parent(), and FUGuardEncoding::port().
addGuardEncoding() [2/3]
void GuardField::addGuardEncoding (GPRGuardEncoding & encoding)
Adds a guard expression and its encoding to the set of expressions supported by this guard field.
This method is to be called from the constructor GPRGuardEncoding.
Parameters
encoding The encoding to be added.
Exceptions
ObjectAlreadyExists If the guard field already contains a guard encoding for the same guard expression or if the given encoding is already assigned.
Definition at line 141 of file GuardField.cc.
{
    // verify that this is called from GPRGuardEncoding constructor
    assert(encoding.parent() == NULL);
    if (hasGPRGuardEncoding(
        encoding.registerFile(), encoding.registerIndex(),
        encoding.isGuardInverted()) || isAssigned(encoding.encoding())) {
    const string procName = "GuardField::addGuardEncoding";
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    gprGuards_.push_back(&encoding);
}
References assert, GuardEncoding::encoding(), gprGuards_, hasGPRGuardEncoding(), isAssigned(), GuardEncoding::isGuardInverted(), GuardEncoding::parent(), GPRGuardEncoding::registerFile(), and GPRGuardEncoding::registerIndex().
Referenced by FUGuardEncoding::FUGuardEncoding(), FUGuardEncoding::FUGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), and UnconditionalGuardEncoding::UnconditionalGuardEncoding().
addGuardEncoding() [3/3]
void GuardField::addGuardEncoding (UnconditionalGuardEncoding & encoding)
Adds a guard expression and its encoding to the set of expressions supported by this guard field.
This method is to be called from the constructor of UnconditionalGuardEncoding.
Parameters
encoding The encoding to be added.
Exceptions
ObjectAlreadyExists If the guard field already contains an encoding for the same unconditional guard expression or if the encoding is already assigned to another guard expression.
Definition at line 226 of file GuardField.cc.
{
    // verify that this is called from UnconditionalGuardEncoding constructor
    assert(encoding.parent() == NULL);
    if (hasUnconditionalGuardEncoding(encoding.isGuardInverted()) ||
        isAssigned(encoding.encoding())) {
        const string procName = "GuardField::addGuardEncoding";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (encoding.isGuardInverted()) {
        alwaysFalse_ = &encoding;
    } else {
        alwaysTrue_ = &encoding;
    }
}
References alwaysFalse_, alwaysTrue_, assert, GuardEncoding::encoding(), hasUnconditionalGuardEncoding(), isAssigned(), GuardEncoding::isGuardInverted(), and GuardEncoding::parent().
childField()
InstructionField & GuardField::childField (int) const virtual
Always throws OutOfRange exception since guard field does not have any child fields.
Returns
Never returns.
Exceptions
OutOfRange Always thrown.
Reimplemented from InstructionField.
Definition at line 522 of file GuardField.cc.
{
    const string procName = "GuardField::childField";
    throw OutOfRange(__FILE__, __LINE__, procName);
}
childFieldCount()
int GuardField::childFieldCount () const virtual
Always returns 0 because guard field does not have any child fields.
Returns
0.
Implements InstructionField.
Definition at line 509 of file GuardField.cc.
{
    return 0;
}
deleteFUGuardEncodings()
void GuardField::deleteFUGuardEncodings () private
Deletes all the function unit port guard encodings from the guard field.
Definition at line 664 of file GuardField.cc.
{
    SequenceTools::deleteAllItems(fuGuards_);
}
References SequenceTools::deleteAllItems(), and fuGuards_.
Referenced by loadState(), and ~GuardField().
deleteGPRGuardEncodings()
void GuardField::deleteGPRGuardEncodings () private
Deletes all the register guard encodings from the guard field.
Definition at line 655 of file GuardField.cc.
{
    SequenceTools::deleteAllItems(gprGuards_);
}
References SequenceTools::deleteAllItems(), and gprGuards_.
Referenced by loadState(), and ~GuardField().
deleteUnconditionalGuardEncodings()
void GuardField::deleteUnconditionalGuardEncodings () private
Deletes the unconditional guard encodings from the guard field.
Definition at line 673 of file GuardField.cc.
{
    if (hasUnconditionalGuardEncoding(true)) {
        delete alwaysFalse_;
        alwaysFalse_ = NULL;
    }
    if (hasUnconditionalGuardEncoding(false)) {
        delete alwaysTrue_;
        alwaysTrue_ = NULL;
    }
}
References alwaysFalse_, alwaysTrue_, and hasUnconditionalGuardEncoding().
Referenced by ~GuardField().
fuGuardEncoding() [1/2]
FUGuardEncoding & GuardField::fuGuardEncoding (const std::string & fu, const std::string & port, bool inverted) const
Returns the FUGuardEncoding for the given guard expression.
The expression is identified by a function unit output port (FU name and port name) and by the "invert" flag. Returns a NullFUGuardEncoding instance if there is no such guard.
Parameters
fu Name of the function unit.
port Name of the port.
inverted The "invert" flag.
Returns
FUGuardEncoding of the given guard expression.
Definition at line 443 of file GuardField.cc.
{
    for (FUGuardTable::const_iterator iter = fuGuards_.begin();
     iter != fuGuards_.end(); iter++) {
    FUGuardEncoding* encoding = *iter;
    if (encoding->functionUnit() == fu &&
        encoding->port() == port &&
        encoding->isGuardInverted() == inverted) {
        return *encoding;
    }
    }
    return NullFUGuardEncoding::instance();
}
References fuGuards_, FUGuardEncoding::functionUnit(), NullFUGuardEncoding::instance(), GuardEncoding::isGuardInverted(), and FUGuardEncoding::port().
fuGuardEncoding() [2/2]
FUGuardEncoding & GuardField::fuGuardEncoding (int index) const
Returns the FUGuardEncoding at the given position.
Parameters
index The position.
Returns
The FU guard encoding.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of FU guard encodings.
Definition at line 387 of file GuardField.cc.
{
    if (index < 0 || index >= fuGuardEncodingCount()) {
    const string procName = "GuardField::fuGuardEncoding";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *fuGuards_[index];
}
References fuGuardEncodingCount(), and fuGuards_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMTester::conflictsWithGuardEncoding(), isAssigned(), printGuardFieldEncodings(), saveState(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
fuGuardEncodingCount()
int GuardField::fuGuardEncodingCount () const
Returns the number of guard expressions with function unit output term that are encoded in this field.
Returns
The number of guard expressions.
Definition at line 373 of file GuardField.cc.
{
    return fuGuards_.size();
}
References fuGuards_.
Referenced by BEMTester::conflictsWithGuardEncoding(), fuGuardEncoding(), isAssigned(), printGuardFieldEncodings(), saveState(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
gprGuardEncoding() [1/2]
GPRGuardEncoding & GuardField::gprGuardEncoding (const std::string & regFile, int index, bool inverted) const
Returns the GPRGuardEncoding for the given guard expression.
The expression is identified by a general purpose register (register file name and register index) and by the "invert" flag. Returns a NullGPRGuardEncoding instance if there is no such guard.
Parameters
regFile Name of the register file.
index The register index.
inverted The "invert" flag.
Returns
GPRGuardEncoding of the given guard expression.
Definition at line 346 of file GuardField.cc.
{
    for (GPRGuardTable::const_iterator iter = gprGuards_.begin();
     iter != gprGuards_.end(); iter++) {
    GPRGuardEncoding* encoding = *iter;
    if (encoding->registerFile() == regFile &&
        encoding->registerIndex() == index &&
        encoding->isGuardInverted() == inverted) {
        return *encoding;
    }
    }
    return NullGPRGuardEncoding::instance();
}
References gprGuards_, NullGPRGuardEncoding::instance(), GuardEncoding::isGuardInverted(), GPRGuardEncoding::registerFile(), and GPRGuardEncoding::registerIndex().
gprGuardEncoding() [2/2]
GPRGuardEncoding & GuardField::gprGuardEncoding (int index) const
Returns the GPRGuardEncoding at the given position.
Parameters
index The position.
Returns
The GPR guard encoding.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of GPR guard encodings.
Definition at line 290 of file GuardField.cc.
{
    if (index < 0 || index >= gprGuardEncodingCount()) {
    const string procName = "GuardField::gprGuardEncoding";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *gprGuards_[index];
}
References gprGuardEncodingCount(), and gprGuards_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMTester::conflictsWithGuardEncoding(), isAssigned(), printGuardFieldEncodings(), saveState(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
gprGuardEncodingCount()
int GuardField::gprGuardEncodingCount () const
Returns the number of guard expressions with general purpose register term that are encoded in this field.
Returns
The number of guard expressions.
Definition at line 276 of file GuardField.cc.
{
    return gprGuards_.size();
}
References gprGuards_.
Referenced by BEMTester::conflictsWithGuardEncoding(), gprGuardEncoding(), isAssigned(), printGuardFieldEncodings(), saveState(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
hasFUGuardEncoding()
bool GuardField::hasFUGuardEncoding (const std::string & fu, const std::string & port, bool inverted) const
Tells whether the guard field has an encoding for the given guard expression.
The expression is identified by a function unit output port (FU name and port name) and by the "invert" flag.
Parameters
fu Name of the function unit.
port Name of the port.
inverted The "invert" flag.
Returns
True if the guard field has an encoding for the given guard expression, otherwise false.
Definition at line 410 of file GuardField.cc.
{
    for (FUGuardTable::const_iterator iter = fuGuards_.begin();
     iter != fuGuards_.end(); iter++) {
    FUGuardEncoding* encoding = *iter;
    if (encoding->functionUnit() == fu &&
        encoding->port() == port &&
        encoding->isGuardInverted() == inverted) {
        return true;
    }
    }
    return false;
}
References fuGuards_, FUGuardEncoding::functionUnit(), GuardEncoding::isGuardInverted(), and FUGuardEncoding::port().
Referenced by addGuardEncoding(), and BEMValidator::checkGuardField().
hasGPRGuardEncoding()
bool GuardField::hasGPRGuardEncoding (const std::string & regFile, int index, bool inverted) const
Tells whether the guard field has an encoding for the given guard expression.
The expression is identified by a general purpose register (register file name and register index) and by the "invert" flag.
Parameters
regFile Name of the register file.
index The register index.
inverted The "invert" flag.
Returns
True if the guard field has an encoding for the given guard expression, otherwise false.
Definition at line 313 of file GuardField.cc.
{
    for (GPRGuardTable::const_iterator iter = gprGuards_.begin();
     iter != gprGuards_.end(); iter++) {
    GPRGuardEncoding* encoding = *iter;
    if (encoding->registerFile() == regFile &&
        encoding->registerIndex() == index &&
        encoding->isGuardInverted() == inverted) {
        return true;
    }
    }
    return false;
}
References gprGuards_, GuardEncoding::isGuardInverted(), GPRGuardEncoding::registerFile(), and GPRGuardEncoding::registerIndex().
Referenced by addGuardEncoding(), and BEMValidator::checkGuardField().
hasUnconditionalGuardEncoding()
bool GuardField::hasUnconditionalGuardEncoding (bool inverted) const
Tells whether the guard field has an encoding for unconditional guard.
Parameters
inverted The "invert" flag.
Returns
True if there is an encoding for unconditional guard, otherwise false.
Definition at line 471 of file GuardField.cc.
{
    if (inverted) {
        return alwaysFalse_ != NULL;
    } else {
        return alwaysTrue_ != NULL;
    }
}
References alwaysFalse_, and alwaysTrue_.
Referenced by addGuardEncoding(), BEMValidator::checkGuardField(), BEMTester::conflictsWithGuardEncoding(), deleteUnconditionalGuardEncodings(), CodeCompressorPlugin::encodeNOP(), isAssigned(), printGuardFieldEncodings(), removeUnconditionalGuardEncoding(), saveState(), unconditionalGuardEncoding(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
isAssigned()
bool GuardField::isAssigned (unsigned int encoding) const private
Tells whether the given encoding is assigned to a guard expression.
Parameters
encoding The encoding.
Returns
True if the encoding is assigned, otherwise false.
Definition at line 692 of file GuardField.cc.
{
    int fuGuards = fuGuardEncodingCount();
    int rfGuards = gprGuardEncodingCount();
    for (int i = 0; i < fuGuards; i++) {
    FUGuardEncoding& guard = fuGuardEncoding(i);
    if (guard.encoding() == encoding) {
        return true;
    }
    }
    for (int i = 0; i < rfGuards; i++) {
    GPRGuardEncoding& guard = gprGuardEncoding(i);
    if (guard.encoding() == encoding) {
        return true;
    }
    }
    if (hasUnconditionalGuardEncoding(false)) {
        if (unconditionalGuardEncoding(false).encoding() == encoding) {
            return true;
        }
    }
    if (hasUnconditionalGuardEncoding(true)) {
        if (unconditionalGuardEncoding(true).encoding() == encoding) {
            return true;
        }
    }
    return false;
}
References GuardEncoding::encoding(), fuGuardEncoding(), fuGuardEncodingCount(), gprGuardEncoding(), gprGuardEncodingCount(), hasUnconditionalGuardEncoding(), and unconditionalGuardEncoding().
Referenced by addGuardEncoding(), addGuardEncoding(), and addGuardEncoding().
loadState()
void GuardField::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Definition at line 585 of file GuardField.cc.
{
    const string procName = "GuardField::loadState";
    if (state->name() != OSNAME_GUARD_FIELD) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    deleteGPRGuardEncodings();
    deleteFUGuardEncodings();
    InstructionField::loadState(state);
    try {
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == FUGuardEncoding::OSNAME_FU_GUARD_ENCODING) {
        new FUGuardEncoding(child, *this);
        } else if (child->name() ==
               GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING) {
        new GPRGuardEncoding(child, *this);
        } else if (child->name() ==
                       UnconditionalGuardEncoding::
                       OSNAME_UNCONDITIONAL_GUARD_ENCODING) {
                new UnconditionalGuardEncoding(child, *this);
            }
    }
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References ObjectState::child(), ObjectState::childCount(), deleteFUGuardEncodings(), deleteGPRGuardEncodings(), Exception::errorMessage(), InstructionField::loadState(), ObjectState::name(), FUGuardEncoding::OSNAME_FU_GUARD_ENCODING, GPRGuardEncoding::OSNAME_GPR_GUARD_ENCODING, and OSNAME_GUARD_FIELD.
Referenced by GuardField().
parent()
MoveSlot * GuardField::parent () const
Returns the parent move slot.
Returns
The parent move slot.
Definition at line 117 of file GuardField.cc.
{
    InstructionField* parent = InstructionField::parent();
    if (parent == NULL) {
    return NULL;
    } else {
    MoveSlot* slot = dynamic_cast<MoveSlot*>(parent);
    assert(slot != NULL);
    return slot;
    }
}
References assert, parent(), and InstructionField::parent().
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMGenerator::addEncodings(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), GuardField(), GuardField(), parent(), MoveSlot::setGuardField(), and ~GuardField().
removeGuardEncoding() [1/2]
void GuardField::removeGuardEncoding (FUGuardEncoding & encoding)
Removes the given guard encoding.
This method is to be called from the destructor of FUGuardField.
Parameters
encoding The encoding to be removed.
Definition at line 205 of file GuardField.cc.
{
    // verify that this is called from GPRGuardEncoding destructor
    assert(encoding.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(fuGuards_, &encoding));
}
References assert, fuGuards_, GuardEncoding::parent(), and ContainerTools::removeValueIfExists().
removeGuardEncoding() [2/2]
void GuardField::removeGuardEncoding (GPRGuardEncoding & encoding)
Removes the given guard encoding.
This method is to be called from the destructor of GPRGuardField.
Parameters
encoding The encoding to be removed.
Definition at line 163 of file GuardField.cc.
{
    // verify that this is called from GPRGuardEncoding destructor
    assert(encoding.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(gprGuards_, &encoding));
}
References assert, gprGuards_, GuardEncoding::parent(), and ContainerTools::removeValueIfExists().
Referenced by FUGuardEncoding::~FUGuardEncoding(), and GPRGuardEncoding::~GPRGuardEncoding().
removeUnconditionalGuardEncoding()
void GuardField::removeUnconditionalGuardEncoding (UnconditionalGuardEncoding & encoding)
Removes the encoding for unconditional guard.
This method is to be called from the destructor of UnconditionalGuardEncoding class.
Parameters
encoding The encoding to be removed.
Definition at line 252 of file GuardField.cc.
{
    assert(hasUnconditionalGuardEncoding(encoding.isGuardInverted()));
    assert(
        &unconditionalGuardEncoding(encoding.isGuardInverted()) ==
        &encoding);
    assert(encoding.parent() == NULL);
    if (encoding.isGuardInverted()) {
        alwaysFalse_ = NULL;
    } else {
        alwaysTrue_ = NULL;
    }
}
References alwaysFalse_, alwaysTrue_, assert, hasUnconditionalGuardEncoding(), GuardEncoding::isGuardInverted(), GuardEncoding::parent(), and unconditionalGuardEncoding().
Referenced by UnconditionalGuardEncoding::~UnconditionalGuardEncoding().
saveState()
ObjectState * GuardField::saveState () const virtual
Saves the state of the guard field to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from InstructionField.
Definition at line 622 of file GuardField.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_GUARD_FIELD);
    // add GPR guard encodings
    for (int i = 0; i < gprGuardEncodingCount(); i++) {
    GPRGuardEncoding& enc = gprGuardEncoding(i);
    state->addChild(enc.saveState());
    }
    // add FU guard encodings
    for (int i = 0; i < fuGuardEncodingCount(); i++) {
    FUGuardEncoding& enc = fuGuardEncoding(i);
    state->addChild(enc.saveState());
    }
    // add unconditional guard encodings
    if (hasUnconditionalGuardEncoding(true)) {
        state->addChild(unconditionalGuardEncoding(true).saveState());
    }
    if (hasUnconditionalGuardEncoding(false)) {
        state->addChild(unconditionalGuardEncoding(false).saveState());
    }
    return state;
}
References ObjectState::addChild(), fuGuardEncoding(), fuGuardEncodingCount(), gprGuardEncoding(), gprGuardEncodingCount(), hasUnconditionalGuardEncoding(), OSNAME_GUARD_FIELD, FUGuardEncoding::saveState(), GPRGuardEncoding::saveState(), saveState(), InstructionField::saveState(), ObjectState::setName(), and unconditionalGuardEncoding().
Referenced by saveState().
unconditionalGuardEncoding()
UnconditionalGuardEncoding & GuardField::unconditionalGuardEncoding (bool inverted) const
Returns the unconditional guard encoding.
Returns NullUnconditionalGuardEncoding instance if there is no encoding for unconditional guard.
Parameters
inverted The "invert" flag.
Returns
The unconditional guard encoding.
Definition at line 490 of file GuardField.cc.
{
    if (hasUnconditionalGuardEncoding(inverted)) {
        if (inverted) {
            return *alwaysFalse_;
        } else {
            return *alwaysTrue_;
        }
    } else {
        return NullUnconditionalGuardEncoding::instance();
    }
}
References alwaysFalse_, alwaysTrue_, hasUnconditionalGuardEncoding(), and NullUnconditionalGuardEncoding::instance().
Referenced by BEMTester::conflictsWithGuardEncoding(), CodeCompressorPlugin::encodeNOP(), isAssigned(), printGuardFieldEncodings(), removeUnconditionalGuardEncoding(), saveState(), width(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
width()
int GuardField::width () const virtual
Returns the bit width of the guard field.
Returns
Bit width of the field.
Implements InstructionField.
Definition at line 533 of file GuardField.cc.
{
    int gprGuards = gprGuardEncodingCount();
    int fuGuards = fuGuardEncodingCount();
    int width(0);
    for (int i = 0; i < gprGuards; i++) {
    GPRGuardEncoding& encoding = gprGuardEncoding(i);
    int requiredBits = MathTools::bitLength(encoding.encoding());
    if (requiredBits > width) {
        width = requiredBits;
    }
    }
    for (int i = 0; i < fuGuards; i++) {
    FUGuardEncoding& encoding = fuGuardEncoding(i);
    int requiredBits = MathTools::bitLength(encoding.encoding());
    if (requiredBits > width) {
        width = requiredBits;
    }
    }
    if (hasUnconditionalGuardEncoding(true)) {
        UnconditionalGuardEncoding& encoding = unconditionalGuardEncoding(
            true);
        int requiredBits = MathTools::bitLength(encoding.encoding());
        if (requiredBits > width) {
            width = requiredBits;
        }
    }
    if (hasUnconditionalGuardEncoding(false)) {
        UnconditionalGuardEncoding& encoding = unconditionalGuardEncoding(
            false);
        int requiredBits = MathTools::bitLength(encoding.encoding());
        if (requiredBits > width) {
            width = requiredBits;
        }
    }
    return width + extraBits();
}
References MathTools::bitLength(), GuardEncoding::encoding(), InstructionField::extraBits(), fuGuardEncoding(), fuGuardEncodingCount(), gprGuardEncoding(), gprGuardEncodingCount(), hasUnconditionalGuardEncoding(), unconditionalGuardEncoding(), and width().
Referenced by CodeCompressorPlugin::addBitsForGuardField(), BEMTester::canAddComponentPriorityEncoding(), BEMTester::conflictsWithGuardEncoding(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), printGuardFieldEncodings(), printMoveSlotLayout(), width(), MoveSlot::width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
Member Data Documentation
alwaysFalse_
UnconditionalGuardEncoding* GuardField::alwaysFalse_ private
Unconditional guard encoding for always-false expression.
Definition at line 119 of file GuardField.hh.
Referenced by addGuardEncoding(), deleteUnconditionalGuardEncodings(), hasUnconditionalGuardEncoding(), removeUnconditionalGuardEncoding(), and unconditionalGuardEncoding().
alwaysTrue_
UnconditionalGuardEncoding* GuardField::alwaysTrue_ private
Unconditional guard encoding for always-true expression.
Definition at line 117 of file GuardField.hh.
Referenced by addGuardEncoding(), deleteUnconditionalGuardEncodings(), hasUnconditionalGuardEncoding(), removeUnconditionalGuardEncoding(), and unconditionalGuardEncoding().
fuGuards_
FUGuardTable GuardField::fuGuards_ private
FU guard encodings.
Definition at line 115 of file GuardField.hh.
Referenced by addGuardEncoding(), deleteFUGuardEncodings(), fuGuardEncoding(), fuGuardEncoding(), fuGuardEncodingCount(), hasFUGuardEncoding(), and removeGuardEncoding().
gprGuards_
GPRGuardTable GuardField::gprGuards_ private
GPR guard encodings.
Definition at line 113 of file GuardField.hh.
Referenced by addGuardEncoding(), deleteGPRGuardEncodings(), gprGuardEncoding(), gprGuardEncoding(), gprGuardEncodingCount(), hasGPRGuardEncoding(), and removeGuardEncoding().
OSNAME_GUARD_FIELD
const std::string GuardField::OSNAME_GUARD_FIELD = "guard_field" static
ObjectState name for guard field.
Definition at line 99 of file GuardField.hh.
Referenced by BEMSerializer::guardFieldToOM(), loadState(), MoveSlot::loadState(), BEMSerializer::moveSlotToFile(), and saveState().
The documentation for this class was generated from the following files:
GuardField.hh
GuardField.cc