OpenASIP: FUBroker Class Reference
FUBroker Class Reference
#include <FUBroker.hh>
Public Member Functions
FUBroker (std::string name, unsigned int initiationInterval=0)
virtual ~FUBroker ()
Public Member Functions inherited from ResourceBroker
ResourceBroker (std::string, unsigned int initiationInterval=0)
virtual ~ResourceBroker ()
virtual bool isAnyResourceAvailable (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual SchedulingResource & availableResource (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual SchedulingResourceSet allAvailableResources (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual bool isAvailable (SchedulingResource &des, const MoveNode &node, int cycle, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const
virtual int earliestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const =0
virtual int latestCycle (int cycle, const MoveNode &node, const TTAMachine::Bus *bus, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU, int immWriteCycle, const TTAMachine::ImmediateUnit *immu, int immRegIndex) const =0
virtual bool isAlreadyAssigned (int cycle, const MoveNode &node, const TTAMachine::Bus *preassignedBus) const =0
virtual bool isApplicable (const MoveNode &node, const TTAMachine::Bus *preassignedBus) const =0
virtual void assign (int cycle, MoveNode &node, SchedulingResource &res, int immWriteCycle, int immRegIndex)=0
virtual void unassign (MoveNode &node)=0
virtual void buildResources (const TTAMachine::Machine &target)=0
virtual void setupResourceLinks (const ResourceMapper &mapper)=0
SchedulingResource * resourceOf (const TTAMachine::MachinePart &mp) const
virtual const TTAMachine::MachinePart & machinePartOf (const SchedulingResource &r) const
bool hasResourceOf (const TTAMachine::MachinePart &mp) const
bool hasResource (const SchedulingResource &r) const
int resourceCount () const
virtual bool isBusBroker () const
virtual bool isITemplateBroker () const
virtual bool isIUBroker () const
virtual bool isExecutionPipelineBroker () const
void validateResources () const
virtual std::string brokerName () const
void resources (ResourceSet &contents)
virtual void setInitiationInterval (unsigned int cycles)
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Protected Member Functions
std::pair< bool, const TTAMachine::FunctionUnit * > findDstFUOfMove (const MoveNode &node, const TTAMachine::FunctionUnit *resFU, DataDependenceGraph::NodeSet &processedInputNodes) const
std::pair< bool, const TTAMachine::FunctionUnit * > findFUOfPO (ProgramOperation &po, const TTAMachine::FunctionUnit *resFU) const
Protected Member Functions inherited from ResourceBroker
void setResourceMapper (const ResourceMapper &mapper)
const ResourceMapper & resourceMapper () const
unsigned int instructionIndex (unsigned int) const
void addResource (const TTAMachine::MachinePart &mp, SchedulingResource *res)
Additional Inherited Members
Public Types inherited from ResourceBroker
typedef std::set< SchedulingResource * > ResourceSet
Protected Types inherited from ResourceBroker
typedef std::map< const TTAMachine::MachinePart *, SchedulingResource *, TTAMachine::MachinePart::Comparator > ResourceMap
typedef std::map< const MoveNode *, SchedulingResource *, MoveNode::Comparator > MoveResMap
Protected Attributes inherited from ResourceBroker
unsigned int initiationInterval_
ResourceMap resMap_
const ResourceMapper * resourceMapper_
MoveResMap assignedResources_
std::string brokerName_
Detailed Description
Input function unit broker.
Definition at line 49 of file FUBroker.hh.
Constructor & Destructor Documentation
FUBroker()
FUBroker::FUBroker (std::string name, unsigned int initiationInterval = 0) inline
Definition at line 51 of file FUBroker.hh.
                                                                  :
        ResourceBroker(name, initiationInterval) {}
~FUBroker()
virtual FUBroker::~FUBroker () inline virtual
Definition at line 53 of file FUBroker.hh.
{}
Member Function Documentation
findDstFUOfMove()
std::pair< bool, const TTAMachine::FunctionUnit * > FUBroker::findDstFUOfMove (const MoveNode & node, const TTAMachine::FunctionUnit * resFU, DataDependenceGraph::NodeSet & processedInputNodes) const protected
Definition at line 37 of file FUBroker.cc.
{
    // already processed this once. do not do it twice
    if (processedInputNodes.count(const_cast<MoveNode*>(&node))) {
        return std::make_pair(true, resFU);
    }
    processedInputNodes.insert(const_cast<MoveNode*>(&node));
    const TTAProgram::Move& move = node.move();
    const TTAProgram::Terminal& dst = move.destination();
    if (!dst.isFUPort()) {
        throw InvalidData(
            __FILE__, __LINE__, __func__,
            "Output move does not have FU source!");
    }
    const TTAMachine::FunctionUnit& fu = dst.functionUnit();
    if (hasResourceOf(fu)) {
        if (resFU == NULL) {
            resFU = &fu;
        } else {
            if (resFU != &fu) {
                return std::make_pair(false, resFU);
                // illegal/empty
            }
        }
    }
    for (unsigned int i = 0; i < node.destinationOperationCount(); i++) {
        ProgramOperation& po = node.destinationOperation(i);
        auto a = findFUOfPO(po, resFU);
        if (a.first) {
            resFU = a.second;
        } else {
            return a;
        }
    }
    return std::make_pair(true, resFU);
}
References __func__, TTAProgram::Move::destination(), MoveNode::destinationOperation(), MoveNode::destinationOperationCount(), findFUOfPO(), TTAProgram::Terminal::functionUnit(), ResourceBroker::hasResourceOf(), TTAProgram::Terminal::isFUPort(), and MoveNode::move().
Referenced by InputFUBroker::allAvailableResources().
findFUOfPO()
std::pair< bool, const TTAMachine::FunctionUnit * > FUBroker::findFUOfPO (ProgramOperation & po, const TTAMachine::FunctionUnit * resFU) const protected
Definition at line 77 of file FUBroker.cc.
{
    const TTAMachine::FunctionUnit* fu = po.scheduledFU();
    // did not find anything. use default or return not found.
    if (fu == nullptr) {
        if (resFU && !po.isLegalFU(*resFU)) {
            return std::make_pair(false, resFU);
        }
        return std::make_pair(true, resFU);
    }
    // illegal annotations?
    if (!po.isLegalFU(*fu)) {
        return std::make_pair(false, resFU);
    }
    assert(hasResourceOf(*fu));
    // did find something, but it's different than default
    if (fu != resFU) {
        if (resFU == nullptr) {
            // default was null, use then one found
            return std::make_pair(true, fu);
        } else {
            // default not null. conflict! return not found.
            return std::make_pair(false, resFU);
        }
    }
    // fu and resfu are the same? ok!
    return std::make_pair(true,fu);
}
References assert, ResourceBroker::hasResourceOf(), ProgramOperation::isLegalFU(), and ProgramOperation::scheduledFU().
Referenced by OutputFUBroker::allAvailableResources(), and findDstFUOfMove().
The documentation for this class was generated from the following files:
FUBroker.hh
FUBroker.cc