OpenASIP: SettingCommand Class Reference
SettingCommand Class Reference
#include <SettingCommand.hh>
Classes
class SimulatorSetting
Public Member Functions
SettingCommand ()
virtual ~SettingCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Protected Types
typedef std::map< std::string, SimulatorSetting * > SettingMap
container for simulator settings indexed by name
Protected Attributes
SettingMap settings_
storage for simulator settings
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "setting" command of the Simulator Control Language.
Definition at line 51 of file SettingCommand.hh.
Member Typedef Documentation
SettingMap
typedef std::map<std::string, SimulatorSetting*> SettingCommand::SettingMap protected
container for simulator settings indexed by name
Definition at line 78 of file SettingCommand.hh.
Constructor & Destructor Documentation
SettingCommand()
SettingCommand::SettingCommand ()
Definition at line 666 of file SettingCommand.cc.
                               :
    SimControlLanguageCommand("setting") {
    settings_["execution_trace"] =
        new TemplatedSimulatorSetting<BooleanSetting, SetExecutionTrace>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_EXECTRACE).str());
    settings_["bus_trace"] =
        new TemplatedSimulatorSetting<BooleanSetting, SetBusTrace>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_BUSTRACE).str());
    settings_["rf_tracking"] =
        new TemplatedSimulatorSetting<BooleanSetting, SetRFTracking>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_RFTRACKING).str());
    settings_["history_filename"] =
        new TemplatedSimulatorSetting<StringSetting, SetHistoryFilename>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_HISTORY_FILENAME).str());
    settings_["history_save"] =
        new TemplatedSimulatorSetting<BooleanSetting, SetHistorySave>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_HISTORY_SAVE).str());
    settings_["history_size"] =
        new TemplatedSimulatorSetting<PositiveIntegerSetting, SetHistorySize>(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_INTERP_SETTING_HISTORY_SIZE).str());
    settings_["procedure_transfer_tracking"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetProcedureTransferTracing>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_PROCEDURE_TRANSFER_TRACKING).
                str());
    settings_["memory_access_tracking"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetMemoryAccessTracking>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_MEMORY_ACCESS_TRACKING).
                str());
    settings_["utilization_data_saving"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetUtilizationSaving>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_UTILIZATION_SAVING).
                str());
    settings_["profile_data_saving"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetProfileSaving>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_PROFILE_SAVING).
                str());
    settings_["fu_conflict_detection"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetFUConflictDetection>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_FU_CONFLICT_DETECTION).
                str());
    settings_["next_instruction_printing"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetNextInstructionPrinting>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_INTERP_SETTING_NEXT_INSTRUCTION_PRINTING).
                str());
    settings_["simulation_time_statistics"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetSimulationTimeStatistics>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_SIMULATION_TIME_STATISTICS).str());
    settings_["simulation_timeout"] =
        new TemplatedSimulatorSetting<
            PositiveIntegerSetting, SetSimulationTimeout>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_SIMULATION_TIMEOUT).str());
    settings_["static_compilation"] =
        new TemplatedSimulatorSetting<
            BooleanSetting, SetStaticCompilation>(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_STATIC_COMPILATION).str());
    settings_["call_history_length"] =
        new TemplatedSimulatorSetting<
            PositiveIntegerSetting, SetCallHistoryLength>(
                "Sets the length of last procedure transfers to save in\n"
                "memory for call trace printing.");
}
References settings_, Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), Texts::TXT_INTERP_SETTING_BUSTRACE, Texts::TXT_INTERP_SETTING_EXECTRACE, Texts::TXT_INTERP_SETTING_FU_CONFLICT_DETECTION, Texts::TXT_INTERP_SETTING_HISTORY_FILENAME, Texts::TXT_INTERP_SETTING_HISTORY_SAVE, Texts::TXT_INTERP_SETTING_HISTORY_SIZE, Texts::TXT_INTERP_SETTING_MEMORY_ACCESS_TRACKING, Texts::TXT_INTERP_SETTING_NEXT_INSTRUCTION_PRINTING, Texts::TXT_INTERP_SETTING_PROCEDURE_TRANSFER_TRACKING, Texts::TXT_INTERP_SETTING_PROFILE_SAVING, Texts::TXT_INTERP_SETTING_RFTRACKING, Texts::TXT_INTERP_SETTING_UTILIZATION_SAVING, Texts::TXT_SIMULATION_TIME_STATISTICS, Texts::TXT_SIMULATION_TIMEOUT, and Texts::TXT_STATIC_COMPILATION.
~SettingCommand()
SettingCommand::~SettingCommand () virtual
Destructor.
Does nothing.
Definition at line 771 of file SettingCommand.cc.
{
    MapTools::deleteAllValues(settings_);
}
References MapTools::deleteAllValues(), and settings_.
Member Function Documentation
execute()
bool SettingCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "setting" command.
Command that allows changing and listing simulator's settings. If no arguments are given, all simulator settings are listed in predefined oreder. If one argument is given, it's expected to be a simulator setting, of which current value is printed. If two arguments are given, the first argument tells the name of the setting to modify, and second argument the new value.
Parameters
arguments Read the comment.
Returns
True in case arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 791 of file SettingCommand.cc.
{
    const int argumentCount = arguments.size() -1;
    if (!checkArgumentCount(argumentCount, 0, 2)) {
        return false;
    }
    // no arguments given, list all the settings and their values,
    // value types and explanations
    if (argumentCount == 0) {
        SettingMap::iterator i = settings_.begin();
        while (i != settings_.end()) {
            outputStream().flags(std::ios_base::left);
            outputStream()
                << std::setw(30) << (*i).first
                << std::setw(20) << (*i).second->valueAsString() << " "
                << (*i).second->description() << std::endl;
            ++i;
        }
        return true;
    }
    SettingMap::iterator settingPosition =
        settings_.find(
            StringTools::stringToLower(arguments.at(1).stringValue()));
    if (settingPosition == settings_.end()) {
        interpreter()->setError(
            SimulatorToolbox::textGenerator().text(
                Texts::TXT_NO_SUCH_SETTING).str());
        return false;
    }
    SimulatorSetting& setting = *((*settingPosition).second);
    // two arguments given, modify the setting
    if (arguments.size() - 1 == 2) {
        try {
            if (!setting.setValue(
                    *dynamic_cast<SimulatorInterpreter*>(interpreter()),
                    simulatorFrontend(), arguments.at(2))) {
                return false;
            }
        } catch (const Exception& e) {
            interpreter()->setError(e.errorMessage());
            return false;
        }
    }
    DataObject* result = new DataObject();
    result->setString(setting.valueAsString());
    interpreter()->setResult(result);
    return true;
}
References CustomCommand::checkArgumentCount(), Exception::errorMessage(), CustomCommand::interpreter(), SimControlLanguageCommand::outputStream(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), DataObject::setString(), settings_, SettingCommand::SimulatorSetting::setValue(), SimControlLanguageCommand::simulatorFrontend(), StringTools::stringToLower(), SimulatorToolbox::textGenerator(), Texts::TXT_NO_SUCH_SETTING, and SettingCommand::SimulatorSetting::valueAsString().
helpText()
std::string SettingCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 855 of file SettingCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_SETTING).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_SETTING.
Member Data Documentation
settings_
SettingMap SettingCommand::settings_ protected
storage for simulator settings
Definition at line 80 of file SettingCommand.hh.
Referenced by CompiledSimSettingCommand::CompiledSimSettingCommand(), execute(), SettingCommand(), and ~SettingCommand().
The documentation for this class was generated from the following files:
SettingCommand.hh
SettingCommand.cc