OpenASIP: UnitPortFigure Class Reference
UnitPortFigure Class Reference
#include <UnitPortFigure.hh>
Public Member Functions
UnitPortFigure (std::string name, int bitWidth)
virtual ~UnitPortFigure ()
std::string name () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutChildren (wxDC *)
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
Private Member Functions
UnitPortFigure & operator= (UnitPortFigure &old)
Assignment not allowed.
UnitPortFigure (UnitPortFigure &old)
Copying not allowed.
Private Attributes
std::string name_
Name of the port.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(0, 0, 0)
Default colour for the figure.
static const wxColour DEFAULT_BG_COLOUR = wxColour(255, 255, 255)
Default background colour for the figure.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a port.
Definition at line 46 of file UnitPortFigure.hh.
Constructor & Destructor Documentation
UnitPortFigure() [1/2]
UnitPortFigure::UnitPortFigure (std::string name, int bitWidth)
The Constructor.
Definition at line 51 of file UnitPortFigure.cc.
                                                          : Figure(), name_(name) {
    size_ = wxSize(std::max(
                       ((MathTools::requiredBits(bitWidth)+(bitWidth/31))<<1)+
                       (MachineCanvasLayoutConstraints::PORT_BASE_WIDTH),
                       MachineCanvasLayoutConstraints::PORT_MIN_WIDTH),
                   MachineCanvasLayoutConstraints::PORT_WIDTH);
}
References MachineCanvasLayoutConstraints::PORT_BASE_WIDTH, MachineCanvasLayoutConstraints::PORT_MIN_WIDTH, MachineCanvasLayoutConstraints::PORT_WIDTH, MathTools::requiredBits(), and Figure::size_.
~UnitPortFigure()
UnitPortFigure::~UnitPortFigure () virtual
The Destructor.
Definition at line 62 of file UnitPortFigure.cc.
{
}
UnitPortFigure() [2/2]
UnitPortFigure::UnitPortFigure (UnitPortFigure & old) private
Copying not allowed.
Member Function Documentation
drawSelf()
void UnitPortFigure::drawSelf (wxDC * dc) protected virtual
Draws the port's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from Figure.
Reimplemented in TriggeringPortFigure.
Definition at line 94 of file UnitPortFigure.cc.
{
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    dc->SetPen(pen);
    wxBrush brush = wxBrush(DEFAULT_BG_COLOUR, wxSOLID);
    if (highlighted_) {
        brush = wxBrush(highlight_, wxSOLID);
    }
    dc->SetBrush(brush);
    dc->DrawRectangle(location_.x, location_.y, size_.GetWidth(),
              size_.GetHeight());
}
References DEFAULT_BG_COLOUR, DEFAULT_COLOUR, Figure::highlight_, Figure::highlighted_, Figure::location_, and Figure::size_.
layoutChildren()
void UnitPortFigure::layoutChildren (wxDC *) protected virtual
Sets the x-coordinate for its child sockets.
Reimplemented from Figure.
Definition at line 69 of file UnitPortFigure.cc.
{
    int socketX = location_.x;
    bool oneSet = false;
    for (unsigned int i = 0; i < children_.size(); i++) {
        children_[i]->setWidth(size_.GetWidth());
        if (!oneSet && !children_[i]->xSet()) {
            children_[i]->setX(location_.x);
            oneSet = true;
            socketX += MachineCanvasLayoutConstraints::SOCKET_WIDTH +
                MachineCanvasLayoutConstraints::SOCKET_MIN_SPACE;
        } else if (children_[i]->location().x == 0) {
            children_[i]->setPreferredX(socketX);
        }
    }
}
References Figure::children_, Figure::location(), Figure::location_, Figure::size_, MachineCanvasLayoutConstraints::SOCKET_MIN_SPACE, MachineCanvasLayoutConstraints::SOCKET_WIDTH, and Figure::xSet().
name()
std::string UnitPortFigure::name () const
Returns name of the port.
Returns
Name of the port.
Definition at line 112 of file UnitPortFigure.cc.
{
    return name_;
}
References name_.
Referenced by UnitFigure::layoutChildren().
operator=()
UnitPortFigure & UnitPortFigure::operator= (UnitPortFigure & old) private
Assignment not allowed.
Member Data Documentation
DEFAULT_BG_COLOUR
const wxColour UnitPortFigure::DEFAULT_BG_COLOUR = wxColour(255, 255, 255) static private
Default background colour for the figure.
Definition at line 65 of file UnitPortFigure.hh.
Referenced by drawSelf().
DEFAULT_COLOUR
const wxColour UnitPortFigure::DEFAULT_COLOUR = wxColour(0, 0, 0) static private
Default colour for the figure.
Definition at line 63 of file UnitPortFigure.hh.
Referenced by drawSelf().
name_
std::string UnitPortFigure::name_ private
Name of the port.
Definition at line 68 of file UnitPortFigure.hh.
Referenced by name().
The documentation for this class was generated from the following files:
UnitPortFigure.hh
UnitPortFigure.cc