OpenASIP: FUResource Class Reference
FUResource Class Reference
#include <FUResource.hh>
Public Member Functions
FUResource (const std::string &name, int operationCount, int nopSlotWeight, unsigned int initiationInterval=0)
virtual ~FUResource ()
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
virtual bool operator< (const SchedulingResource &other) const override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Private Member Functions
FUResource (const FUResource &)
FUResource & operator= (const FUResource &)
Private Attributes
int opCount_
int nopSlotWeight_
Additional Inherited Members
Protected Member Functions inherited from SchedulingResource
virtual bool validateDependentGroups ()
virtual bool validateRelatedGroups ()
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling FU resources of Resource Model
Definition at line 46 of file FUResource.hh.
Constructor & Destructor Documentation
FUResource() [1/2]
FUResource::FUResource (const std::string & name, int opCount, int nopSlotWeight, unsigned int initiationInterval = 0)
Constructor defining resource name
Parameters
name Name of resource
Definition at line 43 of file FUResource.cc.
                                                                           :
    SchedulingResource(name, initiationInterval) , opCount_(opCount),
    nopSlotWeight_(nopSlotWeight) {
}
~FUResource()
FUResource::~FUResource () virtual
Empty destructor
Definition at line 52 of file FUResource.cc.
{}
FUResource() [2/2]
FUResource::FUResource (const FUResource &) private
Member Function Documentation
assign()
void FUResource::assign (const int cycle, MoveNode & node) override virtual
Assign resource to given node for given cycle
Parameters
cycle Cycle to assign
node MoveNode assigned
Implements SchedulingResource.
Reimplemented in InputFUResource, and OutputFUResource.
Definition at line 100 of file FUResource.cc.
{
    // Implemented in derived classes
    abortWithError("assign of FUResource called!");
}
References abortWithError.
canAssign()
bool FUResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Return true if resource can be assigned for given resource in given cycle
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Implements SchedulingResource.
Reimplemented in InputFUResource, and OutputFUResource.
Definition at line 125 of file FUResource.cc.
{
    // Implemented in derived classes
    abortWithError("canAssign of FUResource called!");
    return false;
}
References abortWithError.
isAvailable()
bool FUResource::isAvailable (const int cycle) const override virtual
Test if resource FUResource is available. Not all of the PSocket are inUse.
Parameters
cycle Cycle which to test
Returns
True if FUResource is available in cycle
Implements SchedulingResource.
Reimplemented in InputFUResource.
Definition at line 80 of file FUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isInputPSocketResource() ||
                dependentResource(i, j).isOutputPSocketResource()) {
                if (dependentResource(i, j).isAvailable(cycle)) {
                    return true;
                }
            }
        }
    }
    return false;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isAvailable(), SchedulingResource::isInputPSocketResource(), and SchedulingResource::isOutputPSocketResource().
Referenced by InputFUResource::isAvailable().
isInUse()
bool FUResource::isInUse (const int cycle) const override virtual
Test if resource FUResource is used in given cycle, meaning InputPSocket or OutputPSocket is in use or ExecutionPipeline is inUse.
Parameters
cycle Cycle which to test
Returns
True if FUResource is already used in cycle
Implements SchedulingResource.
Reimplemented in InputFUResource.
Definition at line 62 of file FUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isInUse(cycle)) {
                return true;
            }
        }
    }
    return false;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), and SchedulingResource::isInUse().
Referenced by InputFUResource::isInUse().
operator<()
bool FUResource::operator< (const SchedulingResource & other) const override virtual
Comparison operator.
Favours least used FU's and FU's with less operations.
Reimplemented from SchedulingResource.
Definition at line 136 of file FUResource.cc.
{
    const FUResource *fur = static_cast<const FUResource*>(&other);
    if (fur == NULL) {
        return false;
    }
    if (nopSlotWeight_ < fur->nopSlotWeight_) {
        return true;
    }
    if (nopSlotWeight_ > fur->nopSlotWeight_) {
        return false;
    }
    if (opCount_ < fur->opCount_) {
        return true;
    }
    if (opCount_ > fur->opCount_) {
        return false;
    }
    // favours FU's with connections to less busses.
    int connCount = 0;
    int connCount2 = 0;
    // count the connections.
    for (int i = 0; i < dependentResourceCount(0); i++) {
        SchedulingResource& r = dependentResource(0,i);
        if (dynamic_cast<InputPSocketResource*>(&r)) {
            connCount += r.relatedResourceCount(1);
        } else {
            connCount += r.relatedResourceCount(2);
        }
    }
    for (int i = 0; i < other.dependentResourceCount(0); i++) {
        SchedulingResource& r = other.dependentResource(0,i);
        if (dynamic_cast<InputPSocketResource*>(&r)) {
            connCount2 += r.relatedResourceCount(1);
        } else {
            connCount2 += r.relatedResourceCount(2);
        }
    }
    if (connCount < connCount2) {
        return true;
    }
    if (connCount > connCount2) {
        return false;
    }
    // then use count
    if (useCount() < other.useCount()) {
        return true;
    }
    if (useCount() > other.useCount()) {
        return false;
    }
    return name() < other.name();
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::name(), nopSlotWeight_, opCount_, SchedulingResource::relatedResourceCount(), and SchedulingResource::useCount().
operator=()
FUResource & FUResource::operator= (const FUResource &) private
unassign()
void FUResource::unassign (const int cycle, MoveNode & node) override virtual
Unassign resource from given node for given cycle
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
Implements SchedulingResource.
Reimplemented in InputFUResource, and OutputFUResource.
Definition at line 112 of file FUResource.cc.
{
    // Implemented in derived classes
    abortWithError("unassign of FUResource called!");
}
References abortWithError.
Member Data Documentation
nopSlotWeight_
int FUResource::nopSlotWeight_ private
Definition at line 66 of file FUResource.hh.
Referenced by operator<().
opCount_
int FUResource::opCount_ private
Definition at line 65 of file FUResource.hh.
Referenced by operator<().
The documentation for this class was generated from the following files:
FUResource.hh
FUResource.cc