OpenASIP: AddGCUCmd Class Reference
AddGCUCmd Class Reference
#include <AddGCUCmd.hh>
Public Member Functions
AddGCUCmd ()
virtual bool Do ()
virtual int id () const
virtual AddGCUCmd * create () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Static Private Attributes
static const std::string RA_PORT_NAME = "ra"
Name for the return address port.
static const std::string OP_PORT_NAME = "pc"
Name for the jump/call operand port.
static const std::string OPNAME_JUMP = "jump"
Name string for the jump operation.
static const std::string OPNAME_CALL = "call"
Name string for the call operation.
Detailed Description
Command for adding new global control unit to the Machine.
Displays a global control unit dialog and creates a new global control unit according to the dialog output.
Definition at line 44 of file AddGCUCmd.hh.
Constructor & Destructor Documentation
AddGCUCmd()
AddGCUCmd::AddGCUCmd ()
The Constructor.
Definition at line 66 of file AddGCUCmd.cc.
                     :
    EditorCommand(ProDeConstants::CMD_NAME_ADD_GCU) {
}
Referenced by create().
Member Function Documentation
create()
AddGCUCmd * AddGCUCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 151 of file AddGCUCmd.cc.
{
    return new AddGCUCmd();
}
References AddGCUCmd().
Do()
bool AddGCUCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 78 of file AddGCUCmd.cc.
              {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    // check that the machine doesn't have a global control unit yet
    if (model->getMachine()->controlUnit() != NULL) {
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::MSG_ERROR_ONE_GCU);
        string title = fmt.str();
        wxString message = WxConversion::toWxString(title);
        InformationDialog info(parentWindow(), message);
        info.ShowModal();
        return false;
    }
    model->pushToStack();
    // Add default ports.
    ControlUnit* gcu = new ControlUnit(
        ProDeConstants::COMP_DEFAULT_NAME_GCU, 3, 1);
    FUPort* opPort = new FUPort(OP_PORT_NAME, 32, *gcu, true, true);
    SpecialRegisterPort* raPort =
        new SpecialRegisterPort(RA_PORT_NAME, 32, *gcu);
    gcu->setReturnAddressPort(*raPort);
    // Add default operations.
    HWOperation* jump = new HWOperation(OPNAME_JUMP, *gcu);
    jump->bindPort(1, *opPort);
    jump->pipeline()->addPortRead(1, 0, 1);
    HWOperation* call = new HWOperation(OPNAME_CALL, *gcu);
    call->bindPort(1, *opPort);
    call->pipeline()->addPortRead(1, 0, 1);
    gcu->setMachine(*(model->getMachine()));
    GCUDialog dialog(parentWindow(), gcu);
    if (dialog.ShowModal() == wxID_OK) {
    model->notifyObservers();
    return true;
    } else {
    model->popFromStack();
    return false;
    }
    return false;
}
References TTAMachine::ExecutionPipeline::addPortRead(), assert, TTAMachine::HWOperation::bindPort(), ProDeConstants::COMP_DEFAULT_NAME_GCU, TTAMachine::Machine::controlUnit(), Model::getMachine(), ProDeTextGenerator::instance(), ProDeTextGenerator::MSG_ERROR_ONE_GCU, Model::notifyObservers(), OP_PORT_NAME, OPNAME_CALL, OPNAME_JUMP, GUICommand::parentWindow(), TTAMachine::HWOperation::pipeline(), Model::popFromStack(), Model::pushToStack(), RA_PORT_NAME, TTAMachine::ControlUnit::setMachine(), TTAMachine::ControlUnit::setReturnAddressPort(), Texts::TextGenerator::text(), WxConversion::toWxString(), and EditorCommand::view().
id()
int AddGCUCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 140 of file AddGCUCmd.cc.
                    {
    return ProDeConstants::COMMAND_ADD_GCU;
}
References ProDeConstants::COMMAND_ADD_GCU.
isEnabled()
bool AddGCUCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 176 of file AddGCUCmd.cc.
                     {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
    return true;
    }
    return false;
}
shortName()
string AddGCUCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 163 of file AddGCUCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ADD_GCU;
}
References ProDeConstants::CMD_SNAME_ADD_GCU.
Member Data Documentation
OP_PORT_NAME
const std::string AddGCUCmd::OP_PORT_NAME = "pc" static private
Name for the jump/call operand port.
Definition at line 57 of file AddGCUCmd.hh.
Referenced by Do().
OPNAME_CALL
const std::string AddGCUCmd::OPNAME_CALL = "call" static private
Name string for the call operation.
Definition at line 61 of file AddGCUCmd.hh.
Referenced by Do().
OPNAME_JUMP
const std::string AddGCUCmd::OPNAME_JUMP = "jump" static private
Name string for the jump operation.
Definition at line 59 of file AddGCUCmd.hh.
Referenced by Do().
RA_PORT_NAME
const std::string AddGCUCmd::RA_PORT_NAME = "ra" static private
Name for the return address port.
Definition at line 55 of file AddGCUCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
AddGCUCmd.hh
AddGCUCmd.cc