OpenASIP: ProDeTextGenerator Class Reference
ProDeTextGenerator Class Reference
#include <ProDeTextGenerator.hh>
Public Types
enum {
TXT_LABEL_NAME = Texts::LAST__ , TXT_LABEL_WIDTH , TXT_LABEL_MAU , TXT_LABEL_ADDRESS_SPACE ,
TXT_LABEL_SOCKET , TXT_LABEL_INPUT_SOCKET , TXT_LABEL_OUTPUT_SOCKET , TXT_LABEL_ENABLED ,
TXT_LABEL_TRUE_GUARD , TXT_LABEL_FALSE_GUARD , TXT_LABEL_EXTENSION , TXT_LABEL_TYPE ,
TXT_LABEL_SIZE , TXT_LABEL_MAX_WRITES , TXT_LABEL_MAX_READS , TXT_LABEL_SLOT ,
TXT_LABEL_OTA_OPERATION , TXT_LABEL_DESTINATION , TXT_LABEL_CYCLES , TXT_LABEL_PORT ,
TXT_LABEL_OPERAND , TXT_LABEL_OPCODE_PORT , TXT_LABEL_TRIGGERS , TXT_LABEL_OPPOSITE_BRIDGE ,
TXT_LABEL_INPUT_BUS , TXT_LABEL_OUTPUT_BUS , TXT_LABEL_BIDIRECTIONAL , TXT_LABEL_FU_NAME ,
TXT_LABEL_PORT_NAME , TXT_LABEL_INVERTED , TXT_LABEL_RF_NAME , TXT_LABEL_REGISTER_INDEX ,
TXT_LABEL_UNDO_LEVELS , TXT_LABEL_CONTENTS , TXT_LABEL_DIRECTION , TXT_LABEL_RA_CHOICE ,
TXT_LABEL_GUARD_LATENCY , TXT_LABEL_GLOBAL_GUARD_LATENCY , TXT_LABEL_BUTTON_DELETE , TXT_LABEL_BUTTON_EDIT ,
TXT_BUTTON_ADD_SR_PORT , TXT_BUTTON_ADD_FU_PORT , TXT_RADIO_EXTENSION_ZERO , TXT_RADIO_EXTENSION_SIGN ,
TXT_RADIO_DIRECTION_INPUT , TXT_RADIO_DIRECTION_OUTPUT , TXT_COLUMN_NAME , TXT_COLUMN_COMPULSORY ,
TXT_COLUMN_VALUE , TXT_COLUMN_TYPE , TXT_COLUMN_WIDTH , TXT_COLUMN_MAU ,
TXT_COLUMN_BIT_WIDTH , TXT_COLUMN_INVERTED , TXT_COLUMN_INDEX , TXT_COLUMN_PORT ,
TXT_COLUMN_SLOT , TXT_COLUMN_OTA_OPERATION , TXT_COLUMN_DESTINATION , TXT_COLUMN_OPERAND ,
TXT_COLUMN_TRIGGERS , TXT_COLUMN_COMMAND , TXT_COLUMN_SHORTCUT , TXT_COLUMN_TOOLBAR_BUTTONS ,
TXT_COLUMN_AVAILABLE_COMMANDS , TXT_COLUMN_MIN_ADDRESS , TXT_COLUMN_MAX_ADDRESS , TXT_COLUMN_BUS ,
TXT_COLUMN_SEGMENT , TXT_COLUMN_SRP , TXT_YES , TXT_NO ,
TXT_ALL , TXT_BUTTON_UP , TXT_BUTTON_DOWN , TXT_BUTTON_SHIFT_LEFT ,
TXT_BUTTON_SHIFT_RIGHT , TXT_BUTTON_INSERT , TXT_BUTTON_REMOVE , TXT_BUTTON_ATTACH ,
TXT_BUTTON_DETACH , TXT_GCU_DIALOG_TITLE , TXT_GCU_OPERATIONS_BOX , TXT_GCU_PORTS_BOX ,
TXT_GCU_DELAY_SLOTS , TXT_BUS_DIALOG_TITLE , TXT_BUS_BUS_BOX , TXT_BUS_SEGMENTS_BOX ,
TXT_BUS_SI_BOX , TXT_BUS_REGISTER_GUARD_BOX , TXT_BUS_PORT_GUARD_BOX , TXT_RF_DIALOG_TITLE ,
TXT_RF_PORTS_BOX , TXT_RF_TYPE_NORMAL , TXT_RF_TYPE_VOLATILE , TXT_RF_TYPE_RESERVED ,
TXT_RF_PORT_DIALOG_TITLE , TXT_TEMPLATES_DIALOG_TITLE , TXT_TEMPLATES_TEMPLATES_BOX , TXT_TEMPLATES_SLOTS_BOX ,
TXT_TEMPLATE_SLOT_DIALOG_TITLE , TXT_OTA_FORMATS_DIALOG_TITLE , TXT_OTA_FORMATS_BOX , TXT_OTA_FORMATS_OPERATIONS_BOX ,
TXT_OTA_OPERATION_DIALOG_TITLE , TXT_IMMEDIATE_SLOT_DIALOG_TITLE , TXT_IU_DIALOG_TITLE , TXT_IU_PORTS_BOX ,
TXT_IU_TEMPLATES_BOX , TXT_IU_PORT_DIALOG_TITLE , TXT_OPERATION_DIALOG_TITLE , TXT_OPERATION_USAGE_BOX ,
TXT_OPERATION_RESOURCES_BOX , TXT_OPERATION_OPERANDS_BOX , TXT_FU_DIALOG_TITLE , TXT_FU_PORTS_BOX ,
TXT_FU_OPERATIONS_BOX , TXT_FU_PORT_DIALOG_TITLE , TXT_SR_PORT_DIALOG_TITLE , TXT_BRIDGE_DIALOG_TITLE ,
TXT_FU_GUARD_DIALOG_TITLE , TXT_RF_GUARD_DIALOG_TITLE , TXT_OPTIONS_DIALOG_TITLE , TXT_OPTIONS_ICONS ,
TXT_OPTIONS_TEXT_ICONS , TXT_OPTIONS_TEXT , TXT_ADDRESS_SPACE_DIALOG_TITLE , TXT_ADDRESS_SPACE_MIN_ADDRESS ,
TXT_ADDRESS_SPACE_MAX_ADDRESS , TXT_ADDRESS_SPACES_DIALOG_TITLE , TXT_CALL_EXPLORER_PLUGIN_TITLE , TXT_EDIT_PARAMETER_TITLE ,
TXT_SOCKET_DIALOG_TITLE , TXT_SOCKET_ATTACHED_BOX , TXT_SOCKET_DETACHED_BOX , TXT_ABOUT_DIALOG_TITLE ,
MSG_ERROR , MSG_ERROR_ILLEGAL_NAME , MSG_ERROR_ONE_GCU , MSG_ERROR_CANNOT_BRIDGE ,
MSG_ERROR_CANNOT_RF_GUARD , MSG_ERROR_CANNOT_FU_GUARD , MSG_ERROR_OPCODE_SET , MSG_ERROR_SAME_NAME ,
MSG_ERROR_EMPTY_TEMPLATE , MSG_ERROR_NO_SLOTS_AVAILABLE , MSG_ERROR_NO_IUS_AVAILABLE , MSG_ERROR_BUS_IT_SLOT_WIDTH ,
MSG_ERROR_BRIDGE_NAMES , MSG_ERROR_NO_OPCODE_OPERAND , MSG_ERROR_OPERAND_NUM_RESERVED , MSG_ERROR_CANNOT_ADD ,
MSG_ERROR_CANNOT_REMOVE , MSG_ERROR_PIPELINE_START , MSG_ERROR_MAX_READS , MSG_ERROR_MAX_WRITES ,
MSG_ERROR_GUARD_EXISTS , MSG_ERROR_UNKNOWN_COMMAND_ID , MSG_ERROR_LOADING_FILE , MSG_ERROR_NO_IMMEDIATE_UNITS ,
MSG_ERROR_ID_EXISTS , MSG_WARN_RES_WITHOUT_USAGES , MSG_CONFIRM_OPERAND_DELETION , COMP_MACHINE ,
COMP_A_BUS , COMP_BUS , COMP_A_SEGMENT , COMP_SEGMENT ,
COMP_AN_OPERATION , COMP_OPERATION , COMP_BRIDGE , COMP_A_BRIDGE ,
COMP_RESOURCE , COMP_A_RESOURCE , COMP_FUNCTION_UNIT , COMP_A_FUNCTION_UNIT ,
COMP_GCU , COMP_AN_IMMEDIATE_UNIT , COMP_IMMEDIATE_UNIT , COMP_A_REGISTER_FILE ,
COMP_REGISTER_FILE , COMP_A_PORT , COMP_PORT , COMP_A_TEMPLATE ,
COMP_TEMPLATE , COMP_AN_OTA_FORMAT , COMP_OTA_FORMAT , COMP_RESOURCE_USE ,
COMP_OPERAND_READ , COMP_AN_ADDRESS_SPACE , COMP_ADDRESS_SPACE , COMP_A_SOCKET ,
COMP_SOCKET , COMP_IMM_SLOT , COMP_AN_IMM_SLOT , STATUS_FUNCTION_UNIT ,
STATUS_REGISTER_FILE , STATUS_IMMEDIATE_UNIT , STATUS_GCU , STATUS_BUS ,
STATUS_SEGMENT , STATUS_SOCKET , STATUS_BRIDGE , STATUS_PORT ,
STATUS_FU_PORT
}
Ids for the generated texts.
Static Public Member Functions
static ProDeTextGenerator * instance ()
static void destroy ()
Private Member Functions
ProDeTextGenerator ()
~ProDeTextGenerator ()
Static Private Attributes
static ProDeTextGenerator * instance_ = NULL
Additional Inherited Members
Public Member Functions inherited from Texts::TextGenerator
TextGenerator ()
virtual ~TextGenerator ()
virtual boost::format text (int textId)
virtual void addText (int textId, const std::string &templateString)
virtual void replaceText (int textId, const std::string &newString)
Detailed Description
Provides static texts visible in the ProDe user interface.
The class is implemented using the 'singleton' design pattern. Only one instance of this class is created, and the instance can be accessed using the instance() method. This class only provides ProDe-specific texts. Texts common to all TCE-guis are provided by the GUITextGenerator class.
Definition at line 49 of file ProDeTextGenerator.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Ids for the generated texts.
Enumerator
TXT_LABEL_NAME
Label for component name widget.
TXT_LABEL_WIDTH
Label for bit width widget.
TXT_LABEL_MAU
Label for min. addressable unit.
TXT_LABEL_ADDRESS_SPACE
Label for address spave selector.
TXT_LABEL_SOCKET
Label for socket selection.
TXT_LABEL_INPUT_SOCKET
Label for input socket selector.
TXT_LABEL_OUTPUT_SOCKET
Label for output socket selector.
TXT_LABEL_ENABLED
Label for 'enable' checkbox.
TXT_LABEL_TRUE_GUARD
Label for 'always true guard'.
TXT_LABEL_FALSE_GUARD
Label for 'always false guard'.
TXT_LABEL_EXTENSION
Label for 'extension' radiobox.
TXT_LABEL_TYPE
Label for type widget.
TXT_LABEL_SIZE
Label for size widget.
TXT_LABEL_MAX_WRITES
Label for Max-Writes widget.
TXT_LABEL_MAX_READS
Label for Max-Reads widget.
TXT_LABEL_SLOT
Label for slot widget.
TXT_LABEL_OTA_OPERATION
Label for OTA operation widget.
TXT_LABEL_DESTINATION
Label for destination widget.
TXT_LABEL_CYCLES
Label for cycles widget.
TXT_LABEL_PORT
Label for port widget.
TXT_LABEL_OPERAND
Label for operand widget.
TXT_LABEL_OPCODE_PORT
Label for sets opcode widget.
TXT_LABEL_TRIGGERS
Label for 'triggers' checkbox.
TXT_LABEL_OPPOSITE_BRIDGE
Label for opposite bridge name.
TXT_LABEL_INPUT_BUS
Label for input bus widget.
TXT_LABEL_OUTPUT_BUS
Label for output bus widget.
TXT_LABEL_BIDIRECTIONAL
Label for bidirectional checkbox.
TXT_LABEL_FU_NAME
Label for function unit name.
TXT_LABEL_PORT_NAME
Label for port name.
TXT_LABEL_INVERTED
Label for inverted checkbox.
TXT_LABEL_RF_NAME
Label for register file name.
TXT_LABEL_REGISTER_INDEX
Label for register index widget.
TXT_LABEL_UNDO_LEVELS
Label for undo levels widget.
TXT_LABEL_CONTENTS
Label for contents widget.
TXT_LABEL_DIRECTION
Label for direction widget.
TXT_LABEL_RA_CHOICE
Label for ret.addr. port choicer.
TXT_LABEL_GUARD_LATENCY
Label for guard latency.
TXT_LABEL_GLOBAL_GUARD_LATENCY
Label for global guard latency.
TXT_LABEL_BUTTON_DELETE
Label for &Delete button.
TXT_LABEL_BUTTON_EDIT
Label for &Edit... button.
TXT_BUTTON_ADD_SR_PORT
Label for GCUdlg add FU port btn.
TXT_BUTTON_ADD_FU_PORT
Label for GCUdlg add SR port btn.
TXT_RADIO_EXTENSION_ZERO
Label for 'zero' radio button.
TXT_RADIO_EXTENSION_SIGN
Label for 'sign' radio button.
TXT_RADIO_DIRECTION_INPUT
Label for input radio button.
TXT_RADIO_DIRECTION_OUTPUT
Label for output radio button.
TXT_COLUMN_NAME
Label for name column in a list.
TXT_COLUMN_COMPULSORY
Label for compulsory column in a list.
TXT_COLUMN_VALUE
Label for value column in a list.
TXT_COLUMN_TYPE
Label for type column in a list.
TXT_COLUMN_WIDTH
Label for width column in a list.
TXT_COLUMN_MAU
Label for MAU column in a list.
TXT_COLUMN_BIT_WIDTH
Label for bit width column in a list.
TXT_COLUMN_INVERTED
Label for inv column in a list.
TXT_COLUMN_INDEX
Label for index column in a list.
TXT_COLUMN_PORT
Label for port column in a list.
TXT_COLUMN_SLOT
Label for slot column in a list.
TXT_COLUMN_OTA_OPERATION
Label for OTA operation column in a list.
TXT_COLUMN_DESTINATION
Label for destination column.
TXT_COLUMN_OPERAND
Label for operand column.
TXT_COLUMN_TRIGGERS
Label for T column in a list.
TXT_COLUMN_COMMAND
Label for command column.
TXT_COLUMN_SHORTCUT
Label for shortcut column.
TXT_COLUMN_TOOLBAR_BUTTONS
Label for toolbar buttons column.
TXT_COLUMN_AVAILABLE_COMMANDS
Available commands column.
TXT_COLUMN_MIN_ADDRESS
Label for min-address column.
TXT_COLUMN_MAX_ADDRESS
Label for max-address column.
TXT_COLUMN_BUS
Label for bus column in a list.
TXT_COLUMN_SEGMENT
Label for segment column.
TXT_COLUMN_SRP
Label for sp.reg. port column.
TXT_YES
Text 'yes' in lower case.
TXT_NO
Text 'no' in lower case.
TXT_ALL
Text 'all' in lower case.
TXT_BUTTON_UP
Label for up button.
TXT_BUTTON_DOWN
Label for down button.
TXT_BUTTON_SHIFT_LEFT
Label for << button.
TXT_BUTTON_SHIFT_RIGHT
Label for >> button.
TXT_BUTTON_INSERT
Label for insert button.
TXT_BUTTON_REMOVE
Label for remove button.
TXT_BUTTON_ATTACH
Label for attach button.
TXT_BUTTON_DETACH
Label for detach button.
TXT_GCU_DIALOG_TITLE
GCU Dialog title.
TXT_GCU_OPERATIONS_BOX
GCU Dialog operation box title.
TXT_GCU_PORTS_BOX
Port list box title.
TXT_GCU_DELAY_SLOTS
Delay slots control label.
TXT_BUS_DIALOG_TITLE
Bus Dialog title.
TXT_BUS_BUS_BOX
Bus Dialog bus box title.
TXT_BUS_SEGMENTS_BOX
Segments box title.
TXT_BUS_SI_BOX
Short immediate box title.
TXT_BUS_REGISTER_GUARD_BOX
Register file guards box title.
TXT_BUS_PORT_GUARD_BOX
Function unit guards box title.
TXT_RF_DIALOG_TITLE
Register file Dialog title.
TXT_RF_PORTS_BOX
Ports box title.
TXT_RF_TYPE_NORMAL
Register file type: normal.
TXT_RF_TYPE_VOLATILE
Register file type: volatile.
TXT_RF_TYPE_RESERVED
Register file type: reserved.
TXT_RF_PORT_DIALOG_TITLE
Register file port Dialog title.
TXT_TEMPLATES_DIALOG_TITLE
Templates dialog title.
TXT_TEMPLATES_TEMPLATES_BOX
Instruction Templates bos title.
TXT_TEMPLATES_SLOTS_BOX
Template Slots box title.
TXT_TEMPLATE_SLOT_DIALOG_TITLE
Template Slot dialog title.
TXT_OTA_FORMATS_DIALOG_TITLE
OTA Formats dialog title.
TXT_OTA_FORMATS_BOX
OTA Formats box title.
TXT_OTA_FORMATS_OPERATIONS_BOX
OTA Formats operations dialog title.
TXT_OTA_OPERATION_DIALOG_TITLE
OTA Operations dialog title.
TXT_IMMEDIATE_SLOT_DIALOG_TITLE
Immediate Slot dialog title.
TXT_IU_DIALOG_TITLE
Immediate unit Dialog title.
TXT_IU_PORTS_BOX
Ports box title.
TXT_IU_TEMPLATES_BOX
Templates box title.
TXT_IU_PORT_DIALOG_TITLE
Immediate unit port dialog title.
TXT_OPERATION_DIALOG_TITLE
Operation dialog title.
TXT_OPERATION_USAGE_BOX
Pipeline usage box title.
TXT_OPERATION_RESOURCES_BOX
Pipeline resources box title.
TXT_OPERATION_OPERANDS_BOX
Operands box title.
TXT_FU_DIALOG_TITLE
Function unit dialog title.
TXT_FU_PORTS_BOX
Ports box title.
TXT_FU_OPERATIONS_BOX
Operations box title.
TXT_FU_PORT_DIALOG_TITLE
Function unit port dialog title.
TXT_SR_PORT_DIALOG_TITLE
Special reg. port dialog title.
TXT_BRIDGE_DIALOG_TITLE
Bridge dialog title.
TXT_FU_GUARD_DIALOG_TITLE
Function unit guard dialog title.
TXT_RF_GUARD_DIALOG_TITLE
Register file guard dialog title.
TXT_OPTIONS_DIALOG_TITLE
Options dialog title.
TXT_OPTIONS_ICONS
Icons option for toolbar buttons.
TXT_OPTIONS_TEXT_ICONS
Text&Icons for toolbar buttons.
TXT_OPTIONS_TEXT
Text option for toolbar buttons.
TXT_ADDRESS_SPACE_DIALOG_TITLE
Address space dialog title.
TXT_ADDRESS_SPACE_MIN_ADDRESS
Label for Min-Address box.
TXT_ADDRESS_SPACE_MAX_ADDRESS
Label for Max-Address box.
TXT_ADDRESS_SPACES_DIALOG_TITLE
Address spaces dialog title.
TXT_CALL_EXPLORER_PLUGIN_TITLE
Call Explorer plugin title.
TXT_EDIT_PARAMETER_TITLE
Edit parameter title.
TXT_SOCKET_DIALOG_TITLE
Socket dialog title.
TXT_SOCKET_ATTACHED_BOX
Label for Attached buses box.
TXT_SOCKET_DETACHED_BOX
Label for Detached buses box.
TXT_ABOUT_DIALOG_TITLE
About dialog title.
MSG_ERROR
Text 'Error' and new line.
MSG_ERROR_ILLEGAL_NAME
Error: Illegal component name.
MSG_ERROR_ONE_GCU
Error: Multiple control units.
MSG_ERROR_CANNOT_BRIDGE
Error: Bridge creation impossible.
MSG_ERROR_CANNOT_RF_GUARD
Error: Register file guard.
MSG_ERROR_CANNOT_FU_GUARD
Error: Function unit port guard.
MSG_ERROR_OPCODE_SET
Error: Operation reads the opcode.
MSG_ERROR_SAME_NAME
Error: Same name exists.
MSG_ERROR_EMPTY_TEMPLATE
Error: Two empty templates.
MSG_ERROR_NO_SLOTS_AVAILABLE
Error: No slots available for IT.
MSG_ERROR_NO_IUS_AVAILABLE
Error: No IUs available for IT.
MSG_ERROR_BUS_IT_SLOT_WIDTH
Error: Slot width > bus width.
MSG_ERROR_BRIDGE_NAMES
Error: Opposing brdgs w/same name.
MSG_ERROR_NO_OPCODE_OPERAND
Error: No oprnd for opcode.s.port.
MSG_ERROR_OPERAND_NUM_RESERVED
Error: Operand number reserved.
MSG_ERROR_CANNOT_ADD
Error: Something can't be added.
MSG_ERROR_CANNOT_REMOVE
Error: Something can't be removed.
MSG_ERROR_PIPELINE_START
Error: Pipeline usage start late.
MSG_ERROR_MAX_READS
Error: Max-reads too large.
MSG_ERROR_MAX_WRITES
Error: Max-writes too large.
MSG_ERROR_GUARD_EXISTS
Error: Equal guard exists.
MSG_ERROR_UNKNOWN_COMMAND_ID
Error: Unknown command ID.
MSG_ERROR_LOADING_FILE
Error: File loading failed.
MSG_ERROR_NO_IMMEDIATE_UNITS
Error: No IUs for a template slot.
MSG_ERROR_ID_EXISTS
Error: Conflicting addr. space ID.
MSG_WARN_RES_WITHOUT_USAGES
Warning: Resources without usages.
MSG_CONFIRM_OPERAND_DELETION
Confirm: operand deletion.
COMP_MACHINE
Text for machine description.
COMP_A_BUS
Name for a bus component.
COMP_BUS
Name for bus component.
COMP_A_SEGMENT
Name for a segment component.
COMP_SEGMENT
Name for segment component.
COMP_AN_OPERATION
Name for operation (w/ article).
COMP_OPERATION
Name for operation (w/o article).
COMP_BRIDGE
Name for bridge component.
COMP_A_BRIDGE
Name for bridge (w/ article).
COMP_RESOURCE
Name for resource (w/o article).
COMP_A_RESOURCE
Name for resource (w/ article).
COMP_FUNCTION_UNIT
Name for FU (w/o article).
COMP_A_FUNCTION_UNIT
Name for FU (w/ article).
COMP_GCU
Name for control unit.
COMP_AN_IMMEDIATE_UNIT
Immediate unit (w/ article).
COMP_IMMEDIATE_UNIT
Immediate unit (w/o article).
COMP_A_REGISTER_FILE
Register file (w/ article).
COMP_REGISTER_FILE
Register file (w/o article).
COMP_A_PORT
Name for port (w/ article).
COMP_PORT
Name for port (w/o article).
COMP_A_TEMPLATE
Name for template (w/ article).
COMP_TEMPLATE
Name for template (w/o article).
COMP_AN_OTA_FORMAT
Name for OTA Format (w/ article).
COMP_OTA_FORMAT
Name for OTA Format (w/o article).
COMP_RESOURCE_USE
String for resource use.
COMP_OPERAND_READ
String for operand read.
COMP_AN_ADDRESS_SPACE
Address space (w/ article).
COMP_ADDRESS_SPACE
Address space (w/o article).
COMP_A_SOCKET
Name for socket (w/ article).
COMP_SOCKET
Name for socket (w/o article).
COMP_IMM_SLOT
Name for imm. slot (w/o article).
COMP_AN_IMM_SLOT
Name for imm. slot (w/ article).
STATUS_FUNCTION_UNIT
Status line template for FUs.
STATUS_REGISTER_FILE
Status line template for RFs.
STATUS_IMMEDIATE_UNIT
Status line template for IUs,.
STATUS_GCU
Status line template for GCUs.
STATUS_BUS
Status line template for buses.
STATUS_SEGMENT
Status line template for segments.
STATUS_SOCKET
Status line template for sockets.
STATUS_BRIDGE
Status line template for bridges.
STATUS_PORT
Status line template for ports.
STATUS_FU_PORT
Status line template for FU ports.
Definition at line 55 of file ProDeTextGenerator.hh.
         {
        TXT_LABEL_NAME = Texts::LAST__, ///< Label for component name widget.
        TXT_LABEL_WIDTH,                ///< Label for bit width widget.
    TXT_LABEL_MAU,                  ///< Label for min. addressable unit.
        TXT_LABEL_ADDRESS_SPACE,        ///< Label for address spave selector.
        TXT_LABEL_SOCKET,               ///< Label for socket selection.
        TXT_LABEL_INPUT_SOCKET,         ///< Label for input socket selector.
        TXT_LABEL_OUTPUT_SOCKET,        ///< Label for output socket selector.
        TXT_LABEL_ENABLED,              ///< Label for 'enable' checkbox.
        TXT_LABEL_TRUE_GUARD,           ///< Label for 'always true guard'.
        TXT_LABEL_FALSE_GUARD,          ///< Label for 'always false guard'.
        TXT_LABEL_EXTENSION,            ///< Label for 'extension' radiobox.
        TXT_LABEL_TYPE,                 ///< Label for type widget.
        TXT_LABEL_SIZE,                 ///< Label for size widget.
        TXT_LABEL_MAX_WRITES,           ///< Label for Max-Writes widget.
        TXT_LABEL_MAX_READS,            ///< Label for Max-Reads widget.
        TXT_LABEL_SLOT,                 ///< Label for slot widget.
        TXT_LABEL_OTA_OPERATION,        ///< Label for OTA operation widget.
        TXT_LABEL_DESTINATION,          ///< Label for destination widget.
        TXT_LABEL_CYCLES,               ///< Label for cycles widget.
        TXT_LABEL_PORT,                 ///< Label for port widget.
        TXT_LABEL_OPERAND,              ///< Label for operand widget.
        TXT_LABEL_OPCODE_PORT,          ///< Label for sets opcode widget.
        TXT_LABEL_TRIGGERS,             ///< Label for 'triggers' checkbox.
        TXT_LABEL_OPPOSITE_BRIDGE,      ///< Label for opposite bridge name.
        TXT_LABEL_INPUT_BUS,            ///< Label for input bus widget.
        TXT_LABEL_OUTPUT_BUS,           ///< Label for output bus widget.
        TXT_LABEL_BIDIRECTIONAL,        ///< Label for bidirectional checkbox.
        TXT_LABEL_FU_NAME,              ///< Label for function unit name.
        TXT_LABEL_PORT_NAME,            ///< Label for port name.
        TXT_LABEL_INVERTED,             ///< Label for inverted checkbox.
        TXT_LABEL_RF_NAME,              ///< Label for register file name.
        TXT_LABEL_REGISTER_INDEX,       ///< Label for register index widget.
        TXT_LABEL_UNDO_LEVELS,          ///< Label for undo levels widget.
        TXT_LABEL_CONTENTS,             ///< Label for contents widget.
        TXT_LABEL_DIRECTION,            ///< Label for direction widget.
        TXT_LABEL_RA_CHOICE,            ///< Label for ret.addr. port choicer.
        TXT_LABEL_GUARD_LATENCY,        ///< Label for guard latency.
        TXT_LABEL_GLOBAL_GUARD_LATENCY, ///< Label for global guard latency.
        TXT_LABEL_BUTTON_DELETE,        ///< Label for &Delete button.
        TXT_LABEL_BUTTON_EDIT,          ///< Label for &Edit... button.
    TXT_BUTTON_ADD_SR_PORT,         ///< Label for GCUdlg add FU port btn.
    TXT_BUTTON_ADD_FU_PORT,         ///< Label for GCUdlg add SR port btn.
        TXT_RADIO_EXTENSION_ZERO,       ///< Label for 'zero' radio button.
        TXT_RADIO_EXTENSION_SIGN,       ///< Label for 'sign' radio button.
        TXT_RADIO_DIRECTION_INPUT,      ///< Label for input radio button.
        TXT_RADIO_DIRECTION_OUTPUT,     ///< Label for output radio button.
        TXT_COLUMN_NAME,                ///< Label for name column in a list.
        TXT_COLUMN_COMPULSORY,          ///< Label for compulsory column in a list.
        TXT_COLUMN_VALUE,               ///< Label for value column in a list.
        TXT_COLUMN_TYPE,                ///< Label for type column in a list.
        TXT_COLUMN_WIDTH,               ///< Label for width column in a list.
        TXT_COLUMN_MAU,                 ///< Label for MAU column in a list.
        TXT_COLUMN_BIT_WIDTH,           ///< Label for bit width column in a list.
        TXT_COLUMN_INVERTED,            ///< Label for inv column in a list.
        TXT_COLUMN_INDEX,               ///< Label for index column in a list.
        TXT_COLUMN_PORT,                ///< Label for port column in a list.
        TXT_COLUMN_SLOT,                ///< Label for slot column in a list.
        TXT_COLUMN_OTA_OPERATION,       ///< Label for OTA operation column in a list.
        TXT_COLUMN_DESTINATION,         ///< Label for destination column.
        TXT_COLUMN_OPERAND,             ///< Label for operand column.
        TXT_COLUMN_TRIGGERS,            ///< Label for T column in a list.
        TXT_COLUMN_COMMAND,             ///< Label for command column.
        TXT_COLUMN_SHORTCUT,            ///< Label for shortcut column.
        TXT_COLUMN_TOOLBAR_BUTTONS,     ///< Label for toolbar buttons column.
        TXT_COLUMN_AVAILABLE_COMMANDS,  ///< Available commands column.
        TXT_COLUMN_MIN_ADDRESS,         ///< Label for min-address column.
        TXT_COLUMN_MAX_ADDRESS,         ///< Label for max-address column.
        TXT_COLUMN_BUS,                 ///< Label for bus column in a list.
        TXT_COLUMN_SEGMENT,             ///< Label for segment column.
    TXT_COLUMN_SRP,                 ///< Label for sp.reg. port column.
        TXT_YES,                        ///< Text 'yes' in lower case.
        TXT_NO,                         ///< Text 'no' in lower case.
        TXT_ALL,                        ///< Text 'all' in lower case.
        TXT_BUTTON_UP,                  ///< Label for up button.
        TXT_BUTTON_DOWN,                ///< Label for down button.
        TXT_BUTTON_SHIFT_LEFT,          ///< Label for << button.
        TXT_BUTTON_SHIFT_RIGHT,         ///< Label for >> button.
        TXT_BUTTON_INSERT,              ///< Label for insert button.
        TXT_BUTTON_REMOVE,              ///< Label for remove button.
        TXT_BUTTON_ATTACH,              ///< Label for attach button.
        TXT_BUTTON_DETACH,              ///< Label for detach button.
        TXT_GCU_DIALOG_TITLE,           ///< GCU Dialog title.
        TXT_GCU_OPERATIONS_BOX,         ///< GCU Dialog operation box title.
        TXT_GCU_PORTS_BOX,              ///< Port list box title.
        TXT_GCU_DELAY_SLOTS,            ///< Delay slots control label.
        TXT_BUS_DIALOG_TITLE,           ///< Bus Dialog title.
        TXT_BUS_BUS_BOX,                ///< Bus Dialog bus box title.
        TXT_BUS_SEGMENTS_BOX,           ///< Segments box title.
        TXT_BUS_SI_BOX,                 ///< Short immediate box title.
        TXT_BUS_REGISTER_GUARD_BOX,     ///< Register file guards box title.
        TXT_BUS_PORT_GUARD_BOX,         ///< Function unit guards box title.
        TXT_RF_DIALOG_TITLE,            ///< Register file Dialog title.
        TXT_RF_PORTS_BOX,               ///< Ports box title.
        TXT_RF_TYPE_NORMAL,             ///< Register file type: normal.
        TXT_RF_TYPE_VOLATILE,           ///< Register file type: volatile.
        TXT_RF_TYPE_RESERVED,           ///< Register file type: reserved.
        TXT_RF_PORT_DIALOG_TITLE,       ///< Register file port Dialog title.
        TXT_TEMPLATES_DIALOG_TITLE,     ///< Templates dialog title.
        TXT_TEMPLATES_TEMPLATES_BOX,    ///< Instruction Templates bos title.
        TXT_TEMPLATES_SLOTS_BOX,        ///< Template Slots box title.
        TXT_TEMPLATE_SLOT_DIALOG_TITLE, ///< Template Slot dialog title.
        TXT_OTA_FORMATS_DIALOG_TITLE,   ///< OTA Formats dialog title.
        TXT_OTA_FORMATS_BOX,            ///< OTA Formats box title.
        TXT_OTA_FORMATS_OPERATIONS_BOX, ///< OTA Formats operations dialog title.
        TXT_OTA_OPERATION_DIALOG_TITLE, ///< OTA Operations dialog title.
        TXT_IMMEDIATE_SLOT_DIALOG_TITLE,///< Immediate Slot dialog title.
        TXT_IU_DIALOG_TITLE,            ///< Immediate unit Dialog title.
        TXT_IU_PORTS_BOX,               ///< Ports box title.
        TXT_IU_TEMPLATES_BOX,           ///< Templates box title.
        TXT_IU_PORT_DIALOG_TITLE,       ///< Immediate unit port dialog title.
        TXT_OPERATION_DIALOG_TITLE,     ///< Operation dialog title.
        TXT_OPERATION_USAGE_BOX,        ///< Pipeline usage box title.
        TXT_OPERATION_RESOURCES_BOX,    ///< Pipeline resources box title.
        TXT_OPERATION_OPERANDS_BOX,     ///< Operands box title.
        TXT_FU_DIALOG_TITLE,            ///< Function unit dialog title.
        TXT_FU_PORTS_BOX,               ///< Ports box title.
        TXT_FU_OPERATIONS_BOX,          ///< Operations box title.
        TXT_FU_PORT_DIALOG_TITLE,       ///< Function unit port dialog title.
        TXT_SR_PORT_DIALOG_TITLE,       ///< Special reg. port dialog title.
        TXT_BRIDGE_DIALOG_TITLE,        ///< Bridge dialog title.
        TXT_FU_GUARD_DIALOG_TITLE,      ///< Function unit guard dialog title.
        TXT_RF_GUARD_DIALOG_TITLE,      ///< Register file guard dialog title.
        TXT_OPTIONS_DIALOG_TITLE,       ///< Options dialog title.
        TXT_OPTIONS_ICONS,              ///< Icons option for toolbar buttons.
        TXT_OPTIONS_TEXT_ICONS,         ///< Text&Icons for toolbar buttons.
        TXT_OPTIONS_TEXT,               ///< Text option for toolbar buttons.
        TXT_ADDRESS_SPACE_DIALOG_TITLE, ///< Address space dialog title.
        TXT_ADDRESS_SPACE_MIN_ADDRESS,  ///< Label for Min-Address box.
        TXT_ADDRESS_SPACE_MAX_ADDRESS,  ///< Label for Max-Address box.
        TXT_ADDRESS_SPACES_DIALOG_TITLE,///< Address spaces dialog title.
        TXT_CALL_EXPLORER_PLUGIN_TITLE, ///< Call Explorer plugin title.
        TXT_EDIT_PARAMETER_TITLE,             ///< Edit parameter title.
        TXT_SOCKET_DIALOG_TITLE,        ///< Socket dialog title.
        TXT_SOCKET_ATTACHED_BOX,        ///< Label for Attached buses box.
        TXT_SOCKET_DETACHED_BOX,        ///< Label for Detached buses box.
        TXT_ABOUT_DIALOG_TITLE,         ///< About dialog title.
        MSG_ERROR,                      ///< Text 'Error' and new line.
        MSG_ERROR_ILLEGAL_NAME,         ///< Error: Illegal component name.
        MSG_ERROR_ONE_GCU,              ///< Error: Multiple control units.
        MSG_ERROR_CANNOT_BRIDGE,        ///< Error: Bridge creation impossible.
        MSG_ERROR_CANNOT_RF_GUARD,      ///< Error: Register file guard.
        MSG_ERROR_CANNOT_FU_GUARD,      ///< Error: Function unit port guard.
        MSG_ERROR_OPCODE_SET,           ///< Error: Operation reads the opcode.
        MSG_ERROR_SAME_NAME,            ///< Error: Same name exists.
        MSG_ERROR_EMPTY_TEMPLATE,       ///< Error: Two empty templates.
        MSG_ERROR_NO_SLOTS_AVAILABLE,   ///< Error: No slots available for IT.
        MSG_ERROR_NO_IUS_AVAILABLE,     ///< Error: No IUs available for IT.
        MSG_ERROR_BUS_IT_SLOT_WIDTH,    ///< Error: Slot width > bus width.
        MSG_ERROR_BRIDGE_NAMES,         ///< Error: Opposing brdgs w/same name.
        MSG_ERROR_NO_OPCODE_OPERAND,    ///< Error: No oprnd for opcode.s.port
        MSG_ERROR_OPERAND_NUM_RESERVED, ///< Error: Operand number reserved.
        MSG_ERROR_CANNOT_ADD,           ///< Error: Something can't be added.
        MSG_ERROR_CANNOT_REMOVE,        ///< Error: Something can't be removed.
        MSG_ERROR_PIPELINE_START,       ///< Error: Pipeline usage start late.
        MSG_ERROR_MAX_READS,            ///< Error: Max-reads too large.
        MSG_ERROR_MAX_WRITES,           ///< Error: Max-writes too large.
        MSG_ERROR_GUARD_EXISTS,         ///< Error: Equal guard exists.
        MSG_ERROR_UNKNOWN_COMMAND_ID,   ///< Error: Unknown command ID.
        MSG_ERROR_LOADING_FILE,         ///< Error: File loading failed.
        MSG_ERROR_NO_IMMEDIATE_UNITS,   ///< Error: No IUs for a template slot.
        MSG_ERROR_ID_EXISTS,            ///< Error: Conflicting addr. space ID.
        MSG_WARN_RES_WITHOUT_USAGES,    ///< Warning: Resources without usages
        MSG_CONFIRM_OPERAND_DELETION,   ///< Confirm: operand deletion.
        COMP_MACHINE,                   ///< Text for machine description.
        COMP_A_BUS,                     ///< Name for a bus component.
        COMP_BUS,                       ///< Name for bus component.
        COMP_A_SEGMENT,                 ///< Name for a segment component.
        COMP_SEGMENT,                   ///< Name for segment component.
        COMP_AN_OPERATION,              ///< Name for operation (w/ article).
        COMP_OPERATION,                 ///< Name for operation (w/o article).
        COMP_BRIDGE,                    ///< Name for bridge component.
        COMP_A_BRIDGE,                  ///< Name for bridge (w/ article).
        COMP_RESOURCE,                  ///< Name for resource (w/o article).
        COMP_A_RESOURCE,                ///< Name for resource (w/ article).
        COMP_FUNCTION_UNIT,             ///< Name for FU (w/o article).
        COMP_A_FUNCTION_UNIT,           ///< Name for FU (w/ article).
        COMP_GCU,                       ///< Name for control unit.
        COMP_AN_IMMEDIATE_UNIT,         ///< Immediate unit (w/ article).
        COMP_IMMEDIATE_UNIT,            ///< Immediate unit (w/o article).
        COMP_A_REGISTER_FILE,           ///< Register file (w/ article).
        COMP_REGISTER_FILE,             ///< Register file (w/o article).
        COMP_A_PORT,                    ///< Name for port (w/ article).
        COMP_PORT,                      ///< Name for port (w/o article).
        COMP_A_TEMPLATE,                ///< Name for template (w/ article).
        COMP_TEMPLATE,                  ///< Name for template (w/o article).
        COMP_AN_OTA_FORMAT,             ///< Name for OTA Format (w/ article).
        COMP_OTA_FORMAT,                ///< Name for OTA Format (w/o article).
        COMP_RESOURCE_USE,              ///< String for resource use.
        COMP_OPERAND_READ,              ///< String for operand read.
        COMP_AN_ADDRESS_SPACE,          ///< Address space (w/ article).
        COMP_ADDRESS_SPACE,             ///< Address space (w/o article).
        COMP_A_SOCKET,                  ///< Name for socket (w/ article).
        COMP_SOCKET,                    ///< Name for socket (w/o article).
        COMP_IMM_SLOT,                  ///< Name for imm. slot (w/o article).
        COMP_AN_IMM_SLOT,               ///< Name for imm. slot (w/ article).
        STATUS_FUNCTION_UNIT,           ///< Status line template for FUs.
        STATUS_REGISTER_FILE,           ///< Status line template for RFs.
        STATUS_IMMEDIATE_UNIT,          ///< Status line template for IUs,
        STATUS_GCU,                     ///< Status line template for GCUs.
        STATUS_BUS,                     ///< Status line template for buses.
        STATUS_SEGMENT,                 ///< Status line template for segments.
        STATUS_SOCKET,                  ///< Status line template for sockets.
        STATUS_BRIDGE,                  ///< Status line template for bridges.
        STATUS_PORT,                    ///< Status line template for ports.
        STATUS_FU_PORT                  ///< Status line template for FU ports.
    };
Constructor & Destructor Documentation
ProDeTextGenerator()
ProDeTextGenerator::ProDeTextGenerator () private
The Constructor.
Definition at line 44 of file ProDeTextGenerator.cc.
{
    addText(TXT_LABEL_NAME, "Name:");
    addText(TXT_LABEL_ENABLED, "Enabled");
    addText(TXT_LABEL_WIDTH, "Width:");
    addText(TXT_LABEL_MAU, "Minimum Addressable Unit:");
    addText(TXT_LABEL_TRUE_GUARD, "Always True Guard");
    addText(TXT_LABEL_FALSE_GUARD, "Always False Guard");
    addText(TXT_LABEL_SOCKET, "Socket:");
    addText(TXT_LABEL_INPUT_SOCKET, "Input Socket:");
    addText(TXT_LABEL_OUTPUT_SOCKET, "Output Socket:");
    addText(TXT_LABEL_ADDRESS_SPACE, "Address Space:");
    addText(TXT_LABEL_EXTENSION, "Extension:");
    addText(TXT_LABEL_TYPE, "Type:");
    addText(TXT_LABEL_SIZE, "Size:");
    addText(TXT_LABEL_MAX_WRITES, "Max-Writes:");
    addText(TXT_LABEL_MAX_READS, "Max-Reads:");
    addText(TXT_LABEL_SLOT, "Slot:");
    addText(TXT_LABEL_DESTINATION, "Destination:");
    addText(TXT_LABEL_CYCLES, "Latency:");
    addText(TXT_LABEL_PORT, "Port:");
    addText(TXT_LABEL_OPERAND, "Operand:");
    addText(TXT_LABEL_OPCODE_PORT, "Opcode setting port:");
    addText(TXT_LABEL_TRIGGERS, "Triggers");
    addText(TXT_LABEL_OPPOSITE_BRIDGE, "Opposite Bridge Name:");
    addText(TXT_LABEL_INPUT_BUS, "Input Bus:");
    addText(TXT_LABEL_OUTPUT_BUS, "Output Bus:");
    addText(TXT_LABEL_BIDIRECTIONAL, "Bidirectional");
    addText(TXT_LABEL_FU_NAME, "Function Unit Name:");
    addText(TXT_LABEL_PORT_NAME, "Port Name:");
    addText(TXT_LABEL_INVERTED, "Inverted");
    addText(TXT_LABEL_RF_NAME, "Register File Name:");
    addText(TXT_LABEL_REGISTER_INDEX, "Register Index:");
    addText(TXT_LABEL_UNDO_LEVELS, "Undo Levels:");
    addText(TXT_LABEL_CONTENTS, "Contents:");
    addText(TXT_LABEL_DIRECTION, "Direction:");
    addText(TXT_LABEL_GUARD_LATENCY, "Guard Latency:");
    addText(TXT_LABEL_GLOBAL_GUARD_LATENCY, "Global Guard Latency:");
    addText(TXT_LABEL_BUTTON_DELETE, "&Delete");
    addText(TXT_LABEL_BUTTON_EDIT, "&Edit...");
    addText(TXT_BUTTON_ADD_FU_PORT, "Add operation port...");
    addText(TXT_BUTTON_ADD_SR_PORT, "Add special register port...");
    addText(TXT_RADIO_EXTENSION_ZERO, "Zero");
    addText(TXT_RADIO_EXTENSION_SIGN, "Sign");
    addText(TXT_RADIO_DIRECTION_INPUT, "Input");
    addText(TXT_RADIO_DIRECTION_OUTPUT, "Output");
    addText(TXT_COLUMN_NAME, "Name");
    addText(TXT_COLUMN_COMPULSORY, "Compulsory");
    addText(TXT_COLUMN_VALUE, "Value");
    addText(TXT_COLUMN_TYPE, "Type");
    addText(TXT_COLUMN_WIDTH, "Width");
    addText(TXT_COLUMN_MAU, "MAU");
    addText(TXT_COLUMN_BIT_WIDTH, "Bit Width");
    addText(TXT_COLUMN_INVERTED, "Inv");
    addText(TXT_COLUMN_INDEX, "Index");
    addText(TXT_COLUMN_PORT, "Port");
    addText(TXT_COLUMN_SLOT, "Slot");
    addText(TXT_COLUMN_DESTINATION, "Destination");
    addText(TXT_COLUMN_OPERAND, "Operand");
    addText(TXT_COLUMN_TRIGGERS, "T");
    addText(TXT_COLUMN_COMMAND, "Command");
    addText(TXT_COLUMN_SHORTCUT, "Shortcut");
    addText(TXT_COLUMN_TOOLBAR_BUTTONS, "Toolbar Buttons");
    addText(TXT_COLUMN_AVAILABLE_COMMANDS, "Available Commands");
    addText(TXT_COLUMN_MIN_ADDRESS, "Min-Address");
    addText(TXT_COLUMN_MAX_ADDRESS, "Max-Address");
    addText(TXT_COLUMN_BUS, "Bus");
    addText(TXT_COLUMN_SEGMENT, "Segment");
    addText(TXT_COLUMN_SRP, "SRP");
    addText(TXT_COLUMN_OTA_OPERATION, "Operation");
    addText(TXT_BUTTON_UP, "&Up");
    addText(TXT_BUTTON_DOWN, "&Down");
    addText(TXT_BUTTON_SHIFT_LEFT, "<<");
    addText(TXT_BUTTON_SHIFT_RIGHT, ">>");
    addText(TXT_BUTTON_INSERT, "<- &Insert");
    addText(TXT_BUTTON_REMOVE, "&Remove ->");
    addText(TXT_BUTTON_ATTACH, "&Attach");
    addText(TXT_BUTTON_DETACH, "&Detach");
    addText(TXT_YES, "yes");
    addText(TXT_NO, "no");
    addText(TXT_ALL, "all");
    // Global control unit dialog
    addText(TXT_GCU_DIALOG_TITLE, "Global Control Unit");
    addText(TXT_GCU_OPERATIONS_BOX, "Operations:");
    addText(TXT_GCU_PORTS_BOX, "Ports:");
    addText(TXT_GCU_DELAY_SLOTS, "Delay Slots:");
    // Bus dialog
    addText(TXT_BUS_DIALOG_TITLE, "Bus");
    addText(TXT_BUS_BUS_BOX, "Bus:");
    addText(TXT_BUS_SEGMENTS_BOX, "Segments:");
    addText(TXT_BUS_SI_BOX, "Short Immediate:");
    addText(TXT_BUS_REGISTER_GUARD_BOX, "Register File Guards:");
    addText(TXT_BUS_PORT_GUARD_BOX, "Function Unit Port Guards:");
    // Register file dialog
    addText(TXT_RF_DIALOG_TITLE, "Register File");
    addText(TXT_RF_PORTS_BOX, "Ports:");
    addText(TXT_RF_TYPE_NORMAL, "normal");
    addText(TXT_RF_TYPE_VOLATILE, "volatile");
    addText(TXT_RF_TYPE_RESERVED, "reserved");
    // Register file port dialog
    addText(TXT_RF_PORT_DIALOG_TITLE, "Register File Port");
    // Special register port dialog
    addText(TXT_SR_PORT_DIALOG_TITLE, "Special Register Port");
    // Instruction templates dialog
    addText(TXT_TEMPLATES_DIALOG_TITLE, "Instruction Templates");
    addText(TXT_TEMPLATES_TEMPLATES_BOX, "Instruction Templates:");
    addText(TXT_TEMPLATES_SLOTS_BOX, "Template Slots:");
    // Instruction template slot dialog
    addText(TXT_TEMPLATE_SLOT_DIALOG_TITLE, "Instruction Template Slot");
    // OTA Formats dialog
    addText(TXT_OTA_FORMATS_DIALOG_TITLE, "OTA Formats");
    addText(TXT_OTA_FORMATS_BOX, "OTA Formats:");
    addText(TXT_OTA_FORMATS_OPERATIONS_BOX, "Operations:");
    // OTA Format operation dialog
    addText(TXT_OTA_OPERATION_DIALOG_TITLE, "Operation");
    // Immediate slot dialog
    addText(TXT_IMMEDIATE_SLOT_DIALOG_TITLE, "Immediate Slots");
    // Immediate unit dialog
    addText(TXT_IU_DIALOG_TITLE, "Immediate Unit");
    addText(TXT_IU_PORTS_BOX, "Ports:");
    addText(TXT_IU_TEMPLATES_BOX, "Templates:");
    // Immediate unit port dialog
    addText(TXT_IU_PORT_DIALOG_TITLE, "Immediate Unit Port");
    // Operation dialog
    addText(TXT_OPERATION_DIALOG_TITLE, "Operation");
    addText(TXT_OPERATION_USAGE_BOX, "Operand usage:");
    addText(TXT_OPERATION_RESOURCES_BOX, "Pipeline Resources:");
    addText(TXT_OPERATION_OPERANDS_BOX, "Operands:");
    // Function unit dialog
    addText(TXT_FU_DIALOG_TITLE, "Function Unit");
    addText(TXT_FU_PORTS_BOX, "Ports:");
    addText(TXT_FU_OPERATIONS_BOX, "Operations:");
    // Function unit port dialog
    addText(TXT_FU_PORT_DIALOG_TITLE, "Function Unit Port");
    // Bridge dialog
    addText(TXT_BRIDGE_DIALOG_TITLE, "Bridge");
    // Function unit guard dialog
    addText(TXT_FU_GUARD_DIALOG_TITLE, "Function Unit Guard");
    // Function unit guard dialog
    addText(TXT_RF_GUARD_DIALOG_TITLE, "Register File Guard");
    // Options dialog
    addText(TXT_OPTIONS_DIALOG_TITLE, "Options");
    addText(TXT_OPTIONS_ICONS, "Icons");
    addText(TXT_OPTIONS_TEXT_ICONS, "text & Icons");
    addText(TXT_OPTIONS_TEXT, "Text");
    // Address Space dialog
    addText(TXT_ADDRESS_SPACE_DIALOG_TITLE, "Address Space");
    addText(TXT_ADDRESS_SPACE_MIN_ADDRESS, "Min-Address:");
    addText(TXT_ADDRESS_SPACE_MAX_ADDRESS, "Max-Address:");
    // Address Spaces dialog
    addText(TXT_ADDRESS_SPACES_DIALOG_TITLE, "Address Spaces");
    // Explorer plugin call dialog
    addText(TXT_CALL_EXPLORER_PLUGIN_TITLE, "Call Explorer Plugin");
    // Edit parameter title
    addText(TXT_EDIT_PARAMETER_TITLE, "Edit Parameter");
    // Socket dialog
    addText(TXT_SOCKET_DIALOG_TITLE, "Socket");
    addText(TXT_SOCKET_ATTACHED_BOX, "Attached Buses:");
    addText(TXT_SOCKET_DETACHED_BOX, "Detached Buses:");
    // About dialog
    addText(TXT_ABOUT_DIALOG_TITLE, "About ");
    // Error messages.
    addText(MSG_ERROR_ILLEGAL_NAME,
            "The component name is illegal.\n"
            "Component name must consist of a letter followed by\n"
            "any number of letters, numbers or characters _:");
    addText(MSG_ERROR_ONE_GCU, "Only one Global Control Unit can exist.");
    addText(MSG_ERROR_CANNOT_BRIDGE,
            "Bridge cannot be added since the machine\n"
            "description doesn't contain two buses\n"
            "which could be legally bridged.\n");
    addText(MSG_ERROR_CANNOT_RF_GUARD,
            "Register file guard can't be added, "
            "because there are no register files in the machine.");
    addText(MSG_ERROR_CANNOT_FU_GUARD,
            "Function unit port guard can't be added, "
            "because there are no function unit ports in the machine.");
    addText(MSG_ERROR_OPCODE_SET,
            "The current operation code setting port "
            "is read by an operation at the beginning "
            "of execution. The port cannot be set to "
            "non operation code setting until the "
            "operation is modified.");
    addText(MSG_ERROR_SAME_NAME,
            "The name '%1%' is already name of %2% in the %3%. "
            "Rename the %4%.");
    addText(MSG_ERROR_EMPTY_TEMPLATE,
            "The machine already contains an empty instruction template.\n"
            "Another empty template can't be added until the empty "
            "template is removed or a slot is added to it.");
    addText(MSG_ERROR_NO_SLOTS_AVAILABLE,
            "The instruction template already contains all possible slots.");
    addText(MSG_ERROR_NO_IUS_AVAILABLE,
            "The instruction template already contains a slot for each "
            "destination immediate unit.");
    addText(MSG_ERROR_BUS_IT_SLOT_WIDTH,
            "Instruction template '%1%' contains a slot for this bus with "
            "width of %2%. The width of the bus can't be less than that.");
    addText(MSG_ERROR_BRIDGE_NAMES,
            "Bridge and the opposite bridge can't have the same name.");
    addText(MSG_ERROR_NO_OPCODE_OPERAND,
            "The parent unit of the operation doesn't "
            "have an opcode setting port, or the opcode\n"
            "setting port is not bound to an operand.\n"
            "Resources can't be added to the pipeline.");
    addText(MSG_ERROR_PIPELINE_START,
            "Pipeline usage must start with resource use or\n"
            "operand read on cycle 0-1");
    addText(MSG_ERROR_CANNOT_REMOVE, "The %1% can't be removed.\n");
    addText(MSG_ERROR_CANNOT_ADD, "The %1% can't be added.\n");
    addText(MSG_ERROR_OPERAND_NUM_RESERVED,
            "Number '%1%' is already reserved for an operand.");
    addText(MSG_ERROR, "Error:\n");
    addText(MSG_ERROR_MAX_READS,
            "The max-reads element must contain a nonnegative integer \n"
            "number not greater than the number of ports that can write \n"
            "to a bus.\n");
    addText(MSG_ERROR_MAX_WRITES,
            "The max-writes element must contain a nonnegative integer number \n"
            "not greater than the number of ports that can write to a bus,\n"
            "minus one if only one bidirectional port can read from a bus.");
    addText(MSG_ERROR_GUARD_EXISTS,
            "Bus already has equal guard.");
    addText(MSG_ERROR_UNKNOWN_COMMAND_ID,
            "Unknown command ID in options:\n\n\t %1%");
    addText(MSG_ERROR_LOADING_FILE, "Error loading file '%1%':\n");
    addText(MSG_ERROR_NO_IMMEDIATE_UNITS,
            "There are no immediate units in the machine architecture.\n");
    addText(MSG_ERROR_ID_EXISTS,
            "Conflicting address space ID found! Changes to address space "
            "ID number list were not saved.\n");
    addText(MSG_WARN_RES_WITHOUT_USAGES,
            "Resources without usages found.\n"
            "Removing resource: ");
    addText(MSG_CONFIRM_OPERAND_DELETION,
            "The operand '%1%' is in use. Do you want to clear the operand "
            "reads and writes in addition to deleting the port binding? "
            "Deleting the operand reads and writes will remove the operand "
            "completely.");
    // Components and subcomponents
    addText(COMP_MACHINE, "machine description");
    addText(COMP_A_SEGMENT, "a segment");
    addText(COMP_SEGMENT, "segment");
    addText(COMP_A_BUS, "a transport bus");
    addText(COMP_BUS, "transport bus");
    addText(COMP_AN_OPERATION, "an operation");
    addText(COMP_OPERATION, "operation");
    addText(COMP_BRIDGE, "bridge");
    addText(COMP_A_BRIDGE, "a bridge");
    addText(COMP_RESOURCE, "resource");
    addText(COMP_A_RESOURCE, "a resource");
    addText(COMP_FUNCTION_UNIT, "function unit");
    addText(COMP_A_FUNCTION_UNIT, "a function unit");
    addText(COMP_GCU, "control unit");
    addText(COMP_AN_IMMEDIATE_UNIT, "an immediate unit");
    addText(COMP_IMMEDIATE_UNIT, "immediate unit");
    addText(COMP_A_REGISTER_FILE, "a register file");
    addText(COMP_REGISTER_FILE, "register file");
    addText(COMP_A_PORT, "a port");
    addText(COMP_PORT, "port");
    addText(COMP_A_TEMPLATE, "a template");
    addText(COMP_TEMPLATE, "template");
    addText(COMP_RESOURCE_USE, "resource use");
    addText(COMP_OPERAND_READ, "operand read");
    addText(COMP_AN_ADDRESS_SPACE, "an address space");
    addText(COMP_ADDRESS_SPACE, "address space");
    addText(COMP_A_SOCKET, "a socket");
    addText(COMP_IMM_SLOT, "immediate slot");
    addText(COMP_AN_IMM_SLOT, "an immediate slot");
    addText(COMP_AN_OTA_FORMAT, "an OTA format");
    addText(COMP_OTA_FORMAT, "OTA format");
    // Component status templates for the statusline.
    addText(STATUS_FUNCTION_UNIT, "Function Unit:  name = %1%");
    addText(STATUS_REGISTER_FILE,
            "Register File:  name = %1%,  type = %2%,  size = %3%,  "
            "width = %4%");
    addText(STATUS_IMMEDIATE_UNIT,
            "Immediate Unit:  name = %1%,  size = %2%,  width = %3%,  "
            "extension = %4%");
    addText(STATUS_GCU, "Global Control Unit:  name = %1%");
    addText(STATUS_BUS,
            "Transport Bus:  name = %1%,  width = %2%,  "
            "immediate width = %3%,  immediate extension = %4%");
    addText(STATUS_SEGMENT, "Segment: name = %1%");
    addText(STATUS_SOCKET, "Socket:  name = %1%");
    addText(STATUS_BRIDGE, "Bridge:  name = %1%");
    addText(STATUS_PORT, "Port:  name = %1%");
    addText(STATUS_FU_PORT, "Port:  name = %1%,  width = %2%,  triggers = %3%");
}
References Texts::TextGenerator::addText(), COMP_A_BRIDGE, COMP_A_BUS, COMP_A_FUNCTION_UNIT, COMP_A_PORT, COMP_A_REGISTER_FILE, COMP_A_RESOURCE, COMP_A_SEGMENT, COMP_A_SOCKET, COMP_A_TEMPLATE, COMP_ADDRESS_SPACE, COMP_AN_ADDRESS_SPACE, COMP_AN_IMM_SLOT, COMP_AN_IMMEDIATE_UNIT, COMP_AN_OPERATION, COMP_AN_OTA_FORMAT, COMP_BRIDGE, COMP_BUS, COMP_FUNCTION_UNIT, COMP_GCU, COMP_IMM_SLOT, COMP_IMMEDIATE_UNIT, COMP_MACHINE, COMP_OPERAND_READ, COMP_OPERATION, COMP_OTA_FORMAT, COMP_PORT, COMP_REGISTER_FILE, COMP_RESOURCE, COMP_RESOURCE_USE, COMP_SEGMENT, COMP_TEMPLATE, MSG_CONFIRM_OPERAND_DELETION, MSG_ERROR, MSG_ERROR_BRIDGE_NAMES, MSG_ERROR_BUS_IT_SLOT_WIDTH, MSG_ERROR_CANNOT_ADD, MSG_ERROR_CANNOT_BRIDGE, MSG_ERROR_CANNOT_FU_GUARD, MSG_ERROR_CANNOT_REMOVE, MSG_ERROR_CANNOT_RF_GUARD, MSG_ERROR_EMPTY_TEMPLATE, MSG_ERROR_GUARD_EXISTS, MSG_ERROR_ID_EXISTS, MSG_ERROR_ILLEGAL_NAME, MSG_ERROR_LOADING_FILE, MSG_ERROR_MAX_READS, MSG_ERROR_MAX_WRITES, MSG_ERROR_NO_IMMEDIATE_UNITS, MSG_ERROR_NO_IUS_AVAILABLE, MSG_ERROR_NO_OPCODE_OPERAND, MSG_ERROR_NO_SLOTS_AVAILABLE, MSG_ERROR_ONE_GCU, MSG_ERROR_OPCODE_SET, MSG_ERROR_OPERAND_NUM_RESERVED, MSG_ERROR_PIPELINE_START, MSG_ERROR_SAME_NAME, MSG_ERROR_UNKNOWN_COMMAND_ID, MSG_WARN_RES_WITHOUT_USAGES, STATUS_BRIDGE, STATUS_BUS, STATUS_FU_PORT, STATUS_FUNCTION_UNIT, STATUS_GCU, STATUS_IMMEDIATE_UNIT, STATUS_PORT, STATUS_REGISTER_FILE, STATUS_SEGMENT, STATUS_SOCKET, TXT_ABOUT_DIALOG_TITLE, TXT_ADDRESS_SPACE_DIALOG_TITLE, TXT_ADDRESS_SPACE_MAX_ADDRESS, TXT_ADDRESS_SPACE_MIN_ADDRESS, TXT_ADDRESS_SPACES_DIALOG_TITLE, TXT_ALL, TXT_BRIDGE_DIALOG_TITLE, TXT_BUS_BUS_BOX, TXT_BUS_DIALOG_TITLE, TXT_BUS_PORT_GUARD_BOX, TXT_BUS_REGISTER_GUARD_BOX, TXT_BUS_SEGMENTS_BOX, TXT_BUS_SI_BOX, TXT_BUTTON_ADD_FU_PORT, TXT_BUTTON_ADD_SR_PORT, TXT_BUTTON_ATTACH, TXT_BUTTON_DETACH, TXT_BUTTON_DOWN, TXT_BUTTON_INSERT, TXT_BUTTON_REMOVE, TXT_BUTTON_SHIFT_LEFT, TXT_BUTTON_SHIFT_RIGHT, TXT_BUTTON_UP, TXT_CALL_EXPLORER_PLUGIN_TITLE, TXT_COLUMN_AVAILABLE_COMMANDS, TXT_COLUMN_BIT_WIDTH, TXT_COLUMN_BUS, TXT_COLUMN_COMMAND, TXT_COLUMN_COMPULSORY, TXT_COLUMN_DESTINATION, TXT_COLUMN_INDEX, TXT_COLUMN_INVERTED, TXT_COLUMN_MAU, TXT_COLUMN_MAX_ADDRESS, TXT_COLUMN_MIN_ADDRESS, TXT_COLUMN_NAME, TXT_COLUMN_OPERAND, TXT_COLUMN_OTA_OPERATION, TXT_COLUMN_PORT, TXT_COLUMN_SEGMENT, TXT_COLUMN_SHORTCUT, TXT_COLUMN_SLOT, TXT_COLUMN_SRP, TXT_COLUMN_TOOLBAR_BUTTONS, TXT_COLUMN_TRIGGERS, TXT_COLUMN_TYPE, TXT_COLUMN_VALUE, TXT_COLUMN_WIDTH, TXT_EDIT_PARAMETER_TITLE, TXT_FU_DIALOG_TITLE, TXT_FU_GUARD_DIALOG_TITLE, TXT_FU_OPERATIONS_BOX, TXT_FU_PORT_DIALOG_TITLE, TXT_FU_PORTS_BOX, TXT_GCU_DELAY_SLOTS, TXT_GCU_DIALOG_TITLE, TXT_GCU_OPERATIONS_BOX, TXT_GCU_PORTS_BOX, TXT_IMMEDIATE_SLOT_DIALOG_TITLE, TXT_IU_DIALOG_TITLE, TXT_IU_PORT_DIALOG_TITLE, TXT_IU_PORTS_BOX, TXT_IU_TEMPLATES_BOX, TXT_LABEL_ADDRESS_SPACE, TXT_LABEL_BIDIRECTIONAL, TXT_LABEL_BUTTON_DELETE, TXT_LABEL_BUTTON_EDIT, TXT_LABEL_CONTENTS, TXT_LABEL_CYCLES, TXT_LABEL_DESTINATION, TXT_LABEL_DIRECTION, TXT_LABEL_ENABLED, TXT_LABEL_EXTENSION, TXT_LABEL_FALSE_GUARD, TXT_LABEL_FU_NAME, TXT_LABEL_GLOBAL_GUARD_LATENCY, TXT_LABEL_GUARD_LATENCY, TXT_LABEL_INPUT_BUS, TXT_LABEL_INPUT_SOCKET, TXT_LABEL_INVERTED, TXT_LABEL_MAU, TXT_LABEL_MAX_READS, TXT_LABEL_MAX_WRITES, TXT_LABEL_NAME, TXT_LABEL_OPCODE_PORT, TXT_LABEL_OPERAND, TXT_LABEL_OPPOSITE_BRIDGE, TXT_LABEL_OUTPUT_BUS, TXT_LABEL_OUTPUT_SOCKET, TXT_LABEL_PORT, TXT_LABEL_PORT_NAME, TXT_LABEL_REGISTER_INDEX, TXT_LABEL_RF_NAME, TXT_LABEL_SIZE, TXT_LABEL_SLOT, TXT_LABEL_SOCKET, TXT_LABEL_TRIGGERS, TXT_LABEL_TRUE_GUARD, TXT_LABEL_TYPE, TXT_LABEL_UNDO_LEVELS, TXT_LABEL_WIDTH, TXT_NO, TXT_OPERATION_DIALOG_TITLE, TXT_OPERATION_OPERANDS_BOX, TXT_OPERATION_RESOURCES_BOX, TXT_OPERATION_USAGE_BOX, TXT_OPTIONS_DIALOG_TITLE, TXT_OPTIONS_ICONS, TXT_OPTIONS_TEXT, TXT_OPTIONS_TEXT_ICONS, TXT_OTA_FORMATS_BOX, TXT_OTA_FORMATS_DIALOG_TITLE, TXT_OTA_FORMATS_OPERATIONS_BOX, TXT_OTA_OPERATION_DIALOG_TITLE, TXT_RADIO_DIRECTION_INPUT, TXT_RADIO_DIRECTION_OUTPUT, TXT_RADIO_EXTENSION_SIGN, TXT_RADIO_EXTENSION_ZERO, TXT_RF_DIALOG_TITLE, TXT_RF_GUARD_DIALOG_TITLE, TXT_RF_PORT_DIALOG_TITLE, TXT_RF_PORTS_BOX, TXT_RF_TYPE_NORMAL, TXT_RF_TYPE_RESERVED, TXT_RF_TYPE_VOLATILE, TXT_SOCKET_ATTACHED_BOX, TXT_SOCKET_DETACHED_BOX, TXT_SOCKET_DIALOG_TITLE, TXT_SR_PORT_DIALOG_TITLE, TXT_TEMPLATE_SLOT_DIALOG_TITLE, TXT_TEMPLATES_DIALOG_TITLE, TXT_TEMPLATES_SLOTS_BOX, TXT_TEMPLATES_TEMPLATES_BOX, and TXT_YES.
Referenced by instance().
~ProDeTextGenerator()
ProDeTextGenerator::~ProDeTextGenerator () private
The Destructor.
Definition at line 374 of file ProDeTextGenerator.cc.
{
}
Member Function Documentation
destroy()
void ProDeTextGenerator::destroy () static
Deletes the only instance of this class.
Definition at line 394 of file ProDeTextGenerator.cc.
{
    if (instance_ != NULL) {
    delete instance_;
    instance_ = NULL;
    }
}
References instance_.
Referenced by ProDe::OnExit().
instance()
ProDeTextGenerator * ProDeTextGenerator::instance () static
Returns the only instance of this class.
Definition at line 382 of file ProDeTextGenerator.cc.
{
    if (instance_ == NULL) {
        instance_ = new ProDeTextGenerator();
    }
    return instance_;
}
References instance_, and ProDeTextGenerator().
Referenced by AddBridgeCmd::Do(), AddGCUCmd::Do(), PasteComponentCmd::Do(), ProDeBridgeEditPolicy::getCommand(), ProDeBusEditPolicy::getCommand(), ProDeFUEditPolicy::getCommand(), ProDeGCUEditPolicy::getCommand(), ProDeIUEditPolicy::getCommand(), ProDePortEditPolicy::getCommand(), ProDeRFEditPolicy::getCommand(), ProDeSegmentEditPolicy::getCommand(), ProDeSocketEditPolicy::getCommand(), BusDialog::onAddFUGuard(), OperationDialog::onAddOperand(), OTAFormatListDialog::onAddOTAFormat(), OperationDialog::onAddResource(), BusDialog::onAddRFGuard(), BusDialog::onAddSegment(), ImmediateSlotDialog::onAddSlot(), TemplateListDialog::onAddSlot(), TemplateListDialog::onAddTemplate(), AddressSpacesDialog::onASRightClick(), OperationDialog::onDeleteOperand(), OperationDialog::onDeleteResource(), BusDialog::onFUGuardRightClick(), BridgeDialog::onOK(), BusDialog::onOK(), SocketDialog::onOK(), AddressSpaceDialog::onOK(), FUDialog::onOK(), FUGuardDialog::onOK(), FUPortDialog::onOK(), GCUDialog::onOK(), IUDialog::onOK(), IUPortDialog::onOK(), OperationDialog::onOK(), RFDialog::onOK(), RFGuardDialog::onOK(), RFPortDialog::onOK(), SRPortDialog::onOK(), OperationDialog::onOperandLClick(), FUDialog::onOperationRightClick(), GCUDialog::onOperationRightClick(), FUDialog::onPortRightClick(), GCUDialog::onPortRightClick(), RFDialog::onPortRightClick(), OperationDialog::onResourceLClick(), RFGuardDialog::onRFChoice(), BusDialog::onRFGuardRightClick(), BusDialog::onSegmentRightClick(), BusDialog::onUnconditionalGuard(), MDFDocument::openADF(), GCUDialog::setLabels(), AboutDialog::setTexts(), AddressSpaceDialog::setTexts(), AddressSpacesDialog::setTexts(), BridgeDialog::setTexts(), BusDialog::setTexts(), CallExplorerPluginWindow::setTexts(), EditParameterDialog::setTexts(), FUDialog::setTexts(), FUGuardDialog::setTexts(), FUPortDialog::setTexts(), ImmediateSlotDialog::setTexts(), IUDialog::setTexts(), IUPortDialog::setTexts(), OperationDialog::setTexts(), OTAFormatListDialog::setTexts(), RFDialog::setTexts(), RFGuardDialog::setTexts(), RFPortDialog::setTexts(), SocketDialog::setTexts(), SRPortDialog::setTexts(), TemplateListDialog::setTexts(), TemplateSlotDialog::setTexts(), RFGuardDialog::TransferDataToWindow(), and OperationDialog::warnOnResourcesWithoutUsages().
Member Data Documentation
instance_
ProDeTextGenerator * ProDeTextGenerator::instance_ = NULL static private
Definition at line 300 of file ProDeTextGenerator.hh.
Referenced by destroy(), and instance().
The documentation for this class was generated from the following files:
ProDeTextGenerator.hh
ProDeTextGenerator.cc