OpenASIP: UserManualCmd Class Reference
UserManualCmd Class Reference
#include <UserManualCmd.hh>
Public Member Functions
UserManualCmd ()
virtual ~UserManualCmd ()
virtual bool Do ()
virtual int id () const
virtual UserManualCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Static Public Attributes
static const std::string COMMAND_NAME = "User Manual"
Command name string.
static const std::string COMMAND_SHORT_NAME = "Help"
Short version of the command name string.
static const std::string COMMAND_ICON = "help.png"
Command icon file name.
static const int COMMAND_ID = 30000
Command ID.
Private Member Functions
bool askFromUser ()
Static Private Attributes
static bool mimeTypesManagerInitialized_ = false
Tells if the singleton mime types manager has already been initialized.
Detailed Description
wxCommand for displaying the TCE manual in the system's default PDF viewer.
Definition at line 40 of file UserManualCmd.hh.
Constructor & Destructor Documentation
UserManualCmd()
UserManualCmd::UserManualCmd ()
The Constructor.
Definition at line 60 of file UserManualCmd.cc.
                            :
    GUICommand(COMMAND_NAME, NULL) {
}
Referenced by create().
~UserManualCmd()
UserManualCmd::~UserManualCmd () virtual
The Destructor.
Definition at line 68 of file UserManualCmd.cc.
{}
Member Function Documentation
askFromUser()
bool UserManualCmd::askFromUser () private
Fall back function which is called if a default pdf viewer is not found.
Returns
True, if the user chose a pdf viewer.
Definition at line 216 of file UserManualCmd.cc.
{
    wxString manual = WxConversion::toWxString(Environment::pdfManual());
    wxString extension = manual.AfterLast(_T('.'));
    wxString message = _T("No default PDF viewer found.");
    message.Append(_T("Please select  an executable program to view PDF "));
    message.Append(_T("files with."));
    assert(parentWindow() != NULL);
    ErrorDialog errorDialog(parentWindow(), message);
    errorDialog.ShowModal();
    wxFileDialog execDialog(
        parentWindow(), _T("Choose a pdf viewer executable"), _T(""), _T(""),
        _T("*"), wxOPEN);
    if (execDialog.ShowModal() == wxID_OK) {
        wxString command = execDialog.GetPath();
        command.Append(_T(" "));
        command.Append(manual);
        wxExecute(command);
        return true;
    }
    return false;
}
References assert, GUICommand::parentWindow(), Environment::pdfManual(), and WxConversion::toWxString().
Referenced by Do().
create()
UserManualCmd * UserManualCmd::create () const virtual
Creates and returns a new instance of this command.
Implements GUICommand.
Definition at line 176 of file UserManualCmd.cc.
{
    return new UserManualCmd();
}
References UserManualCmd().
Do()
bool UserManualCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 77 of file UserManualCmd.cc.
                  {
    if (!mimeTypesManagerInitialized_) {
        wxTheMimeTypesManager->Initialize();
        mimeTypesManagerInitialized_ = true;
    }
    wxString manual = WxConversion::toWxString(Environment::pdfManual());
    wxString extension = manual.AfterLast(_T('.'));
    wxFileType* ft =
        wxTheMimeTypesManager->GetFileTypeFromExtension(extension);
    std::string cmdStr;
    wxString cmd;
    if (ft != NULL) {
        cmd = ft->GetOpenCommand(manual);
        delete ft;
        ft = NULL;
        cmdStr = std::string(cmd.ToAscii());
    }
    // Stupid hack for now. For fedora some reason this cmd would end up
    // being 'gimp' which is not very nice PDF reader ;)
    // on ubuntu this could be gv which cannot view PDF's.
    if (!(cmdStr.find("evince") != std::string::npos ||
          cmdStr.find("kpdf") != std::string::npos ||
          cmdStr.find("kghostview") != std::string::npos ||
          cmdStr.find("acroread") != std::string::npos ||
          cmdStr.find("okular") != std::string::npos)) {
        cmdStr = "";
    }
    if (cmdStr == "") {
        // if couldn't get viewer from mime types test if some usual
        // default viewer is found
        std::vector<std::string> viewers;
        viewers.push_back("/usr/bin/evince");
        viewers.push_back("/usr/bin/kpdf");
        viewers.push_back("/usr/bin/kghostview");
        viewers.push_back("/usr/bin/acroread");
        viewers.push_back("/usr/bin/okular");
        for (unsigned int i = 0; i < viewers.size(); ++i) {
            if (FileSystem::fileIsExecutable(viewers.at(i))) {
                wxExecute(
                    wxString::FromAscii(
                        (viewers.at(i) + " ").c_str()) + manual);
                return true;
            }
        }
        // if none of above viewers were found try to find from PATH env
        // variable
        viewers.clear();
        std::string DS = FileSystem::DIRECTORY_SEPARATOR;
        viewers.push_back("evince");
        viewers.push_back("kpdf");
        viewers.push_back("kghostview");
        viewers.push_back("acroread");
        viewers.push_back("okular");
        std::vector<std::string> paths;
        std::string pathsEnv = Environment::environmentVariable("PATH");
        StringTools::chopString(pathsEnv, ":", paths);
        for (unsigned int i = 0; i < paths.size(); ++i) {
            for (unsigned int j = 0; j < viewers.size(); ++j) {
                std::string viewer = paths.at(i) + DS + viewers.at(j);
                if (FileSystem::fileIsExecutable(viewer)) {
                    wxExecute(
                        wxString::FromAscii(
                            (viewers.at(i) + " ").c_str()) + manual);
                    return true;
                }
            }
        }
        // did not find any viewer from path or default locations
        return askFromUser();
    } else {
        wxExecute(cmd);
    }
    return true;
}
References askFromUser(), StringTools::chopString(), FileSystem::DIRECTORY_SEPARATOR, DS, Environment::environmentVariable(), FileSystem::fileIsExecutable(), mimeTypesManagerInitialized_, Environment::pdfManual(), and WxConversion::toWxString().
icon()
string UserManualCmd::icon () const virtual
Returns path to the command's icon file.
Implements GUICommand.
Definition at line 194 of file UserManualCmd.cc.
{
    return COMMAND_ICON;
}
References COMMAND_ICON.
id()
int UserManualCmd::id () const virtual
Returns id of this command.
Implements GUICommand.
Definition at line 167 of file UserManualCmd.cc.
{
    return COMMAND_ID;
}
References COMMAND_ID.
isEnabled()
bool UserManualCmd::isEnabled () virtual
This command is always executable.
Returns
Always true.
Implements GUICommand.
Definition at line 205 of file UserManualCmd.cc.
{
    return true;
}
shortName()
string UserManualCmd::shortName () const virtual
Returns short version of the command name.
Reimplemented from GUICommand.
Definition at line 185 of file UserManualCmd.cc.
{
    return COMMAND_SHORT_NAME;
}
References COMMAND_SHORT_NAME.
Member Data Documentation
COMMAND_ICON
const std::string UserManualCmd::COMMAND_ICON = "help.png" static
Command icon file name.
Definition at line 56 of file UserManualCmd.hh.
Referenced by icon().
COMMAND_ID
const int UserManualCmd::COMMAND_ID = 30000 static
Command ID.
Definition at line 58 of file UserManualCmd.hh.
Referenced by MainFrame::createHelpMenu(), ProximMainFrame::createMenubar(), HDBEditorMainFrame::HDBEditorMainFrame(), id(), and OSEdMainFrame::OSEdMainFrame().
COMMAND_NAME
const std::string UserManualCmd::COMMAND_NAME = "User Manual" static
Command name string.
Definition at line 52 of file UserManualCmd.hh.
Referenced by ProDe::createDefaultOptions().
COMMAND_SHORT_NAME
const std::string UserManualCmd::COMMAND_SHORT_NAME = "Help" static
Short version of the command name string.
Definition at line 54 of file UserManualCmd.hh.
Referenced by shortName().
mimeTypesManagerInitialized_
bool UserManualCmd::mimeTypesManagerInitialized_ = false static private
Tells if the singleton mime types manager has already been initialized.
Definition at line 64 of file UserManualCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
UserManualCmd.hh
UserManualCmd.cc