OpenASIP: DictionaryToolCmdLineOptions Class Reference
DictionaryToolCmdLineOptions Class Reference
Public Member Functions
DictionaryToolCmdLineOptions ()
bool printPrimitive ()
bool printConnections ()
bool printGlobalRegister ()
bool printMissingConnections ()
bool printRFConnections ()
bool doNotPrintErrors ()
bool writeBinary ()
void printVersion () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
DictionaryTool commandline options.
Definition at line 67 of file DictionaryTool.cc.
Constructor & Destructor Documentation
DictionaryToolCmdLineOptions()
DictionaryToolCmdLineOptions::DictionaryToolCmdLineOptions () inline
Definition at line 69 of file DictionaryTool.cc.
                                   :
        CmdLineOptions("Usage: dictionary_tool [options] adffile") {
        BoolCmdLineOptionParser* printPrimitive =
            new BoolCmdLineOptionParser(
                "primitive",
                "Print missing operations from primitive operation set",
                "p");
        addOption(printPrimitive);
        BoolCmdLineOptionParser* printConnections =
            new BoolCmdLineOptionParser("connections",
                                        "Print all connections in adf.",
                                        "c");
        addOption(printConnections);
        BoolCmdLineOptionParser* printGlobalRegister =
            new BoolCmdLineOptionParser(
                "global_register",
                "Print the name of global connection register", "g");
        addOption(printGlobalRegister);
        BoolCmdLineOptionParser* printMissingConnections =
            new BoolCmdLineOptionParser(
                "missing",
                "Print missing connections to connection register",
                "m");
        addOption(printMissingConnections);
        BoolCmdLineOptionParser* printRFConnections =
            new BoolCmdLineOptionParser(
                "reg_connections",
                "Print all connections to the connection register.", "r");
        addOption(printRFConnections);
        BoolCmdLineOptionParser* doNotPrintErrors =
            new BoolCmdLineOptionParser(
                "no_errors",
                "Don't print any error messages.", "e");
        addOption(doNotPrintErrors);
        BoolCmdLineOptionParser* writeBinary =
            new BoolCmdLineOptionParser(
                "binary",
                "Write binary program as output.", "w");
        addOption(writeBinary);
    }
References CmdLineParser::addOption(), doNotPrintErrors(), printConnections(), printGlobalRegister(), printMissingConnections(), printPrimitive(), printRFConnections(), and writeBinary().
Member Function Documentation
doNotPrintErrors()
bool DictionaryToolCmdLineOptions::doNotPrintErrors () inline
Definition at line 144 of file DictionaryTool.cc.
{
        return findOption("no_errors")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printConnections()
bool DictionaryToolCmdLineOptions::printConnections () inline
Definition at line 128 of file DictionaryTool.cc.
{
        return findOption("connections")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printGlobalRegister()
bool DictionaryToolCmdLineOptions::printGlobalRegister () inline
Definition at line 132 of file DictionaryTool.cc.
{
        return findOption("global_register")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printMissingConnections()
bool DictionaryToolCmdLineOptions::printMissingConnections () inline
Definition at line 136 of file DictionaryTool.cc.
{
        return findOption("missing")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printPrimitive()
bool DictionaryToolCmdLineOptions::printPrimitive () inline
Definition at line 124 of file DictionaryTool.cc.
{
        return findOption("primitive")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printRFConnections()
bool DictionaryToolCmdLineOptions::printRFConnections () inline
Definition at line 140 of file DictionaryTool.cc.
{
        return findOption("reg_connections")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
printVersion()
void DictionaryToolCmdLineOptions::printVersion () const inline virtual
Implements CmdLineOptions.
Definition at line 152 of file DictionaryTool.cc.
{
        cout << "dictionary_tool - Dictionary Tool "
             << Application::TCEVersionString() << endl;
    }
References Application::TCEVersionString().
writeBinary()
bool DictionaryToolCmdLineOptions::writeBinary () inline
Definition at line 148 of file DictionaryTool.cc.
                       {
        return findOption("binary")->isFlagOn();
    }
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by DictionaryToolCmdLineOptions().
The documentation for this class was generated from the following file:
DictionaryTool.cc