OpenASIP: AddFUArchFromADFCmd Class Reference
AddFUArchFromADFCmd Class Reference
#include <AddFUArchFromADFCmd.hh>
Public Member Functions
AddFUArchFromADFCmd ()
virtual ~AddFUArchFromADFCmd ()
virtual bool Do ()
virtual int id () const
virtual AddFUArchFromADFCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
AddFUArchFromADFCmd ()
virtual ~AddFUArchFromADFCmd ()
virtual bool Do ()
virtual int id () const
virtual AddFUArchFromADFCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new FU architectures to HDB from an ADF file.
Definition at line 41 of file AddFUArchFromADFCmd.hh.
Constructor & Destructor Documentation
AddFUArchFromADFCmd() [1/2]
AddFUArchFromADFCmd::AddFUArchFromADFCmd ()
The Constructor.
Definition at line 55 of file AddFUArchFromADFCmd.cc.
                                         :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_FU_FROM_ADF, NULL) {
}
Referenced by create().
~AddFUArchFromADFCmd() [1/2]
AddFUArchFromADFCmd::~AddFUArchFromADFCmd () virtual
The Destructor.
Definition at line 63 of file AddFUArchFromADFCmd.cc.
{
}
AddFUArchFromADFCmd() [2/2]
AddFUArchFromADFCmd::AddFUArchFromADFCmd ()
~AddFUArchFromADFCmd() [2/2]
virtual AddFUArchFromADFCmd::~AddFUArchFromADFCmd () virtual
Member Function Documentation
create() [1/2]
AddFUArchFromADFCmd * AddFUArchFromADFCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 193 of file AddFUArchFromADFCmd.cc.
{
    return new AddFUArchFromADFCmd();
}
References AddFUArchFromADFCmd().
create() [2/2]
virtual AddFUArchFromADFCmd * AddFUArchFromADFCmd::create () const virtual
Creates a new GUICommand instance.
Returns
New GUICommand instance.
Implements GUICommand.
Do() [1/2]
bool AddFUArchFromADFCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed.
Implements GUICommand.
Definition at line 72 of file AddFUArchFromADFCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    wxString wildcard = _T("Architecture Definition Files (*.adf)|*.adf");
    wildcard.Append(_T("|All files|*.*"));
    wxFileDialog dialog(
    parentWindow(), _T("Choose a file."), _T(""), _T(""),
    wildcard, wxOPEN);
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    wxString fileName = dialog.GetPath();
    ADFSerializer reader;
    reader.setSourceFile(WxConversion::toString(fileName));
    TTAMachine::Machine* machine = NULL;
    try {
        machine = reader.readMachine();
    } catch (Exception& e) {
        wxString message = _T("Error opening ");
        message.Append(fileName);
        message.Append(_T(":\n\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(parentWindow(), message);
        dialog.ShowModal();
        return false;
    }
    const TTAMachine::Machine::FunctionUnitNavigator& nav =
        machine->functionUnitNavigator();
    if (nav.count() == 0) {
        wxString message = _T("The file ");
        message.Append(fileName);
        message.Append(_T(" doesn't contain any function units."));
        ErrorDialog dialog(parentWindow(), message);
        dialog.ShowModal();
        delete machine;
        return false;
    }
    wxString fus[1000];
    for (int i = 0; i < nav.count(); i++) {
        fus[i] = WxConversion::toWxString(nav.item(i)->name());
    }
    wxSingleChoiceDialog choicer(
        parentWindow(), _T("Choose Function Unit"), _T("Choose Function Unit"),
        nav.count(), fus);
    if (choicer.ShowModal() != wxID_OK) {
        delete machine;
        return false;
    }
    TTAMachine::FunctionUnit* fu = nav.item(choicer.GetSelection());
    fu->unsetMachine();
    delete machine;
    HDB::FUArchitecture fuArch(fu);
    FUArchitectureDialog paramDialog(parentWindow(), -1 , fuArch);
    if (paramDialog.ShowModal() != wxID_OK) {
        return false;
    }
    int id = -1;
    try {
        id = manager->addFUArchitecture(fuArch);
    } catch (Exception& e) {
        wxString message = _T("Erroneous function unit architecture:\n\n");
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(parentWindow(), message);
        dialog.ShowModal();
        return false;
    }
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectFUArchitecture(id);
    return true;
}
References HDB::HDBManager::addFUArchitecture(), TTAMachine::Machine::Navigator< ComponentType >::count(), Exception::errorMessage(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, GUICommand::parentWindow(), ADFSerializer::readMachine(), XMLSerializer::setSourceFile(), WxConversion::toString(), WxConversion::toWxString(), and TTAMachine::FunctionUnit::unsetMachine().
Do() [2/2]
virtual bool AddFUArchFromADFCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
icon() [1/2]
std::string AddFUArchFromADFCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 172 of file AddFUArchFromADFCmd.cc.
{
    return "";
}
icon() [2/2]
virtual std::string AddFUArchFromADFCmd::icon () const virtual
Returns name of the command icon file.
Returns
Name of the command icon file.
Implements GUICommand.
id() [1/2]
int AddFUArchFromADFCmd::id () const virtual
Returns the command id.
Returns
Command identifier.
Implements GUICommand.
Definition at line 182 of file AddFUArchFromADFCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_FU_FROM_ADF;
}
References HDBEditorConstants::COMMAND_ADD_FU_FROM_ADF.
id() [2/2]
virtual int AddFUArchFromADFCmd::id () const virtual
Returns the ID of the command.
Returns
The ID of the command.
Implements GUICommand.
isEnabled() [1/2]
bool AddFUArchFromADFCmd::isEnabled () virtual
Returns true if the command should be enabled in the menu/toolbar.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 204 of file AddFUArchFromADFCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
isEnabled() [2/2]
virtual bool AddFUArchFromADFCmd::isEnabled () virtual
Returns true if the command is executable, false otherwise.
Returns
True, if the command is executable, false otherwise.
Implements GUICommand.
The documentation for this class was generated from the following files:
AddFUArchFromADFCmd.hh
FUArchitectureParametersDialog.hh
AddFUArchFromADFCmd.cc