OpenASIP: GUIOptions Class Reference
GUIOptions Class Reference
#include <GUIOptions.hh>
Public Types
enum ToolbarLayout { TEXT , ICON , BOTH }
Public Member Functions
GUIOptions (std::string name)
GUIOptions (const GUIOptions &old)
GUIOptions (const ObjectState *state)
virtual ~GUIOptions ()
bool hasFileName () const
std::string fileName () const
void setFileName (const std::string &fileName)
virtual void validate () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
bool fullScreen () const
int windowWidth () const
int windowHeight () const
int xPosition () const
int yPosition () const
bool toolbarVisibility () const
ToolbarLayout toolbarLayout () const
void setFullScreen (bool fullScreen)
void setWindowSize (int width, int height)
void setWindowPosition (int x, int y)
void setToolbarVisibility (bool visible)
void setToolbarLayout (ToolbarLayout layout)
void addKeyboardShortcut (KeyboardShortcut *shortcut)
void addToolbarButton (ToolbarButton *button)
void addSeparator (int position)
void deleteKeyboardShortcut (KeyboardShortcut *shortcut)
void deleteToolbarButton (ToolbarButton *button)
void deleteSeparator (int position)
KeyboardShortcut * keyboardShortcut (const std::string commandName) const
KeyboardShortcut * firstShortcut () const
KeyboardShortcut * nextShortcut () const
ToolbarButton * firstToolbarButton () const
ToolbarButton * nextToolbarButton () const
int firstSeparator () const
int nextSeparator () const
void clearModified ()
bool isModified () const
wxToolBar * createToolbar (wxWindow *parent, CommandRegistry &registry, const wxString &iconsPath)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string TOOLBAR_SEPARATOR = "-- separator --"
Toolbar separator name.
static const std::string OSNAME_OPTIONS = "options"
ObjectState name for the options.
static const std::string OSKEY_FULL_SCREEN = "fscreen"
ObjectState attribute key for full screen feature.
static const std::string OSKEY_WINDOW_WIDTH = "wwidth"
ObjectState attribute key for window width.
static const std::string OSKEY_WINDOW_HEIGHT = "wheight"
ObjectState attribute key for window height.
static const std::string OSKEY_X_POS = "xpos"
ObjectState attribute key for window x position.
static const std::string OSKEY_Y_POS = "ypos"
ObjectState attribute key for window y position.
static const std::string OSKEY_TOOLBAR_VISIBILITY = "tbvisib"
ObjectState attribute key for toolbar visibility.
static const std::string OSKEY_TOOLBAR_LAYOUT = "tblayout"
ObjectState attribute key for toolbar layout.
static const std::string OSVALUE_TEXT = "text"
ObjectState attribute value for text layout.
static const std::string OSVALUE_ICON = "icon"
ObjectState attribute value for icon layout.
static const std::string OSVALUE_BOTH = "both"
ObjectState attribute value for text & icon layout.
static const std::string OSNAME_SEPARATOR = "separator"
ObjectState name for separator.
static const std::string OSKEY_POSITION = "pos"
ObjectState attribute key for separator position.
Protected Member Functions
void deleteAllKeyboardShortcuts ()
void deleteAllToolbarButtons ()
Private Types
typedef std::vector< int > SeparatorTable
Table for the toolbar separator positions.
typedef std::vector< KeyboardShortcut * > KSTable
Table for keyboard shortcuts.
typedef std::vector< ToolbarButton * > TBTable
Table for toolbar buttons.
Private Attributes
std::string fileName_
File name assigned to these options.
bool fullScreen_
If true, the application window will open in full screen mode.
int windowWidth_
Default width of the window.
int windowHeight_
Default height of the window.
int xPosition_
Default x position of left side of the application window.
int yPosition_
Default y position of the upper side of the application window.
bool toolbarVisibility_
If true, the toolbar is visible.
ToolbarLayout toolbarLayout_
Layout of the toolbar.
SeparatorTable toolbarSeparators_
Toolbar separators.
KSTable keyboardShortcuts_
Keyboard shortcuts.
TBTable toolbarButtons_
Toolbar buttons.
KSTable::const_iterator ksIter_
Iterator used in firstShortcut and nextShortcut functions.
TBTable::const_iterator tbIter_
Iterator used in firstToolbarButton and nextToolbarButton functions.
SeparatorTable::const_iterator separatorIter_
Iterator used in firstSeparator and nextSeparator functions.
bool modified_
Indicates whether the options are modified or not.
std::string name_
Name of the options.
Detailed Description
Represents the options of a GUI.
Base class for GUI options. This class provides handling of options common to all GUIs. If a GUI needs application specific options, specialized options class can be derived from this class. See design documentation for details. This class implements the Serializable interface because the options are going to be stored in an xml configuration file.
Definition at line 58 of file GUIOptions.hh.
Member Typedef Documentation
KSTable
typedef std::vector<KeyboardShortcut*> GUIOptions::KSTable private
Table for keyboard shortcuts.
Definition at line 164 of file GUIOptions.hh.
SeparatorTable
typedef std::vector<int> GUIOptions::SeparatorTable private
Table for the toolbar separator positions.
Definition at line 162 of file GUIOptions.hh.
TBTable
typedef std::vector<ToolbarButton*> GUIOptions::TBTable private
Table for toolbar buttons.
Definition at line 166 of file GUIOptions.hh.
Member Enumeration Documentation
ToolbarLayout
enum GUIOptions::ToolbarLayout
Layout of the buttons in the toolbar.
Enumerator
TEXT
Buttons contains only text.
ICON
Buttons contains only icon.
BOTH
Buttons contains text and icon.
Definition at line 64 of file GUIOptions.hh.
                       {
        TEXT, ///< Buttons contains only text.
        ICON, ///< Buttons contains only icon.
        BOTH  ///< Buttons contains text and icon.
    };
Constructor & Destructor Documentation
GUIOptions() [1/3]
GUIOptions::GUIOptions (std::string name)
Constructor.
Definition at line 68 of file GUIOptions.cc.
                                     :
    fullScreen_(false),  windowWidth_(400), windowHeight_(400), xPosition_(0),
    yPosition_(0), toolbarVisibility_(false), toolbarLayout_(BOTH),
    modified_(false), name_(name) {
}
GUIOptions() [2/3]
GUIOptions::GUIOptions (const GUIOptions & old)
Copy constructor.
This constructor creates identical options with the given options class.
Definition at line 93 of file GUIOptions.cc.
                                           : Serializable() {
    fullScreen_ = old.fullScreen_;
    windowWidth_ = old.windowWidth_;
    windowHeight_ = old.windowHeight_;
    xPosition_ = old.xPosition_;
    yPosition_ = old.yPosition_;
    toolbarVisibility_ = old.toolbarVisibility_;
    toolbarLayout_ = old.toolbarLayout_;
    toolbarSeparators_ = old.toolbarSeparators_;
    modified_ = old.modified_;
#ifdef KB_SC_EDITING
    // deep copy keyboard shortcuts
    for (KSTable::const_iterator iter = old.keyboardShortcuts_.begin();
         iter != old.keyboardShortcuts_.end(); iter++) {
        keyboardShortcuts_.push_back(new KeyboardShortcut(**iter));
    }
#endif
    // deep copy toolbar buttons
    for (TBTable::const_iterator iter = old.toolbarButtons_.begin();
         iter != old.toolbarButtons_.end(); iter++) {
        toolbarButtons_.push_back(new ToolbarButton(**iter));
    }
}
References fullScreen_, keyboardShortcuts_, modified_, toolbarButtons_, toolbarLayout_, toolbarSeparators_, toolbarVisibility_, windowHeight_, windowWidth_, xPosition_, and yPosition_.
GUIOptions() [3/3]
GUIOptions::GUIOptions (const ObjectState * state)
Constructor.
Loads the state from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Definition at line 84 of file GUIOptions.cc.
                                               : modified_(false) {
    loadState(state);
}
References loadState().
~GUIOptions()
GUIOptions::~GUIOptions () virtual
Destructor.
Definition at line 125 of file GUIOptions.cc.
{
    deleteAllToolbarButtons();
    deleteAllKeyboardShortcuts();
}
References deleteAllKeyboardShortcuts(), and deleteAllToolbarButtons().
Member Function Documentation
addKeyboardShortcut()
void GUIOptions::addKeyboardShortcut (KeyboardShortcut * shortcut)
Adds a keyboard shortcut.
Parameters
shortcut Keyboard shortcut to be added.
Definition at line 280 of file GUIOptions.cc.
{
    keyboardShortcuts_.push_back(shortcut);
    modified_ = true;
}
References keyboardShortcuts_, and modified_.
Referenced by Proxim::createDefaultOptions(), ProDe::createDefaultOptions(), loadState(), and OptionsDialog::writeOptions().
addSeparator()
void GUIOptions::addSeparator (int position)
Adds a separator to the toolbar to the given position.
Parameters
position Number of the slot left side of which the separator is drawn.
Definition at line 305 of file GUIOptions.cc.
{
    toolbarSeparators_.push_back(position);
    modified_ = true;
}
References modified_, and toolbarSeparators_.
Referenced by Proxim::createDefaultOptions(), ProDe::createDefaultOptions(), loadState(), and OptionsDialog::writeOptions().
addToolbarButton()
void GUIOptions::addToolbarButton (ToolbarButton * button)
Adds the given button to the toolbar.
Parameters
button Button to be added.
Definition at line 292 of file GUIOptions.cc.
{
    toolbarButtons_.push_back(button);
    modified_ = true;
}
References modified_, and toolbarButtons_.
Referenced by Proxim::createDefaultOptions(), ProDe::createDefaultOptions(), loadState(), and OptionsDialog::writeOptions().
clearModified()
void GUIOptions::clearModified ()
Clears the modified flag.
The isModified method returns false after calling this method.
Definition at line 502 of file GUIOptions.cc.
{
    modified_ = false;
}
References modified_.
Referenced by Proxim::loadOptions(), and ProDe::OnInit().
createToolbar()
wxToolBar * GUIOptions::createToolbar (wxWindow * parent, CommandRegistry & registry, const wxString & iconsPath)
Creates a toolbar defined in the options.
Parameters
parent Parent window of the created toolbar.
registry Command registry containing the toolbar commands.
iconPath Path of the toolbar icon files.
Returns
A new toolbar corresponding to the one defined in the options.
Definition at line 768 of file GUIOptions.cc.
{
    int layout = toolbarLayout();
    long style = 0;
    // check toolbar layout from options
    if (layout == GUIOptions::BOTH) {
        style = wxTB_HORIZONTAL | wxNO_BORDER | wxTB_TEXT;
    } else if (layout == GUIOptions::ICON) {
        style = wxTB_HORIZONTAL | wxNO_BORDER;
    } else if (layout == GUIOptions::TEXT) {
        style = wxTB_HORIZONTAL | wxNO_BORDER | wxTB_TEXT | wxTB_NOICONS;
    } else {
        assert(false);
    }
    // create a new toolbar
    wxToolBar* toolbar = new wxToolBar(
        parent, -1, wxDefaultPosition, wxDefaultSize, style);
    bool found = true;
    int slot = 0;
    wxBitmap icon;
    // Add buttons and separators for each slot, until a slot without
    // button or separator is found.
    while (found) {
        found = false;
        // check if a toolbar button exists for the slot
        ToolbarButton* tool = firstToolbarButton();
        while (tool != NULL) {
            if (tool->slot() == slot) {
                // button found for the slot, add it
                found = true;
                wxString iconPath = iconsPath;
                iconPath.Append(WxConversion::toWxString(
                                    FileSystem::DIRECTORY_SEPARATOR));
                iconPath.Append(
                    WxConversion::toWxString(
                        registry.commandIcon(tool->action())));
                if (!icon.LoadFile(iconPath, wxBITMAP_TYPE_PNG)) {
                    std::cerr << "Toolbar icon file "
                              << WxConversion::toString(iconPath)
                              << " not found!"
                              << std::endl;
                    icon.Create(32, 32);
                }
                toolbar->AddTool(registry.commandId(tool->action()),
                                  WxConversion::toWxString(
                                  registry.commandShortName(tool->action())),
                                  icon, wxNullBitmap, wxITEM_NORMAL,
                                  WxConversion::toWxString(
                                  tool->action()),
                                  WxConversion::toWxString(
                                  tool->action()));
                found = true;
                // disable button if command is not executable at the moment
                if (!registry.isEnabled(tool->action())) {
                    toolbar->EnableTool(registry.commandId(tool->action()),
                                         false);
                }
            }
            tool = nextToolbarButton();
        }
        // check if a separator exists for the slot
        int separator = firstSeparator();
        while (separator != -1) {
            if (separator == slot) {
                // separator found for the slot, add it
                toolbar->AddSeparator();
                found = true;
            }
            separator = nextSeparator();
        }
        slot++;
    }
    toolbar->Realize();
    return toolbar;
}
References ToolbarButton::action(), assert, BOTH, CommandRegistry::commandIcon(), CommandRegistry::commandId(), CommandRegistry::commandShortName(), FileSystem::DIRECTORY_SEPARATOR, firstSeparator(), firstToolbarButton(), ICON, CommandRegistry::isEnabled(), nextSeparator(), nextToolbarButton(), ToolbarButton::slot(), TEXT, toolbarLayout(), WxConversion::toString(), and WxConversion::toWxString().
deleteAllKeyboardShortcuts()
void GUIOptions::deleteAllKeyboardShortcuts () protected
Deletes all the keyboard shortcuts.
Definition at line 745 of file GUIOptions.cc.
{
    SequenceTools::deleteAllItems(keyboardShortcuts_);
}
References SequenceTools::deleteAllItems(), and keyboardShortcuts_.
Referenced by loadState(), ProDeOptions::loadState(), and ~GUIOptions().
deleteAllToolbarButtons()
void GUIOptions::deleteAllToolbarButtons () protected
Deletes all the toolbar buttons.
Definition at line 754 of file GUIOptions.cc.
{
    SequenceTools::deleteAllItems(toolbarButtons_);
}
References SequenceTools::deleteAllItems(), and toolbarButtons_.
Referenced by loadState(), ProDeOptions::loadState(), and ~GUIOptions().
deleteKeyboardShortcut()
void GUIOptions::deleteKeyboardShortcut (KeyboardShortcut * shortcut)
Deletes the given keyboard shortcut.
Parameters
shortcut The keyboard shortcut to be deleted.
Definition at line 317 of file GUIOptions.cc.
{
    KSTable::iterator iter = keyboardShortcuts_.begin();
    while (iter != keyboardShortcuts_.end()) {
        if (*iter == shortcut) {
            keyboardShortcuts_.erase(iter);
            delete shortcut;
            modified_ = true;
            return;
        }
        iter++;
    }
}
References keyboardShortcuts_, and modified_.
Referenced by OptionsDialog::writeOptions().
deleteSeparator()
void GUIOptions::deleteSeparator (int position)
Deletes a separator from the given position.
Parameters
position The slot position left side of which the separator is deleted.
Definition at line 358 of file GUIOptions.cc.
{
    SeparatorTable::iterator iter = toolbarSeparators_.begin();
    while (iter != toolbarSeparators_.end()) {
        if (*iter == position) {
            toolbarSeparators_.erase(iter);
            modified_ = true;
            return;
        }
        iter++;
    }
}
References modified_, and toolbarSeparators_.
Referenced by OptionsDialog::writeOptions().
deleteToolbarButton()
void GUIOptions::deleteToolbarButton (ToolbarButton * button)
Deletes the given toolbar button.
Parameters
button The toolbar button to be deleted.
Definition at line 337 of file GUIOptions.cc.
{
    TBTable::iterator iter = toolbarButtons_.begin();
    while (iter != toolbarButtons_.end()) {
        if (*iter == button) {
            toolbarButtons_.erase(iter);
            delete button;
            modified_ = true;
            return;
        }
        iter++;
    }
}
References modified_, and toolbarButtons_.
Referenced by OptionsDialog::writeOptions().
fileName()
string GUIOptions::fileName () const
Returns the file name assigned to these options.
Returns
The file name assigned to these options.
Definition at line 621 of file GUIOptions.cc.
{
    return fileName_;
}
References fileName_.
Referenced by setFileName().
firstSeparator()
int GUIOptions::firstSeparator () const
Returns position of the first toolbar separator. Position is the position of the slot left side of which the separator is. If there are no separators, returns -1.
Returns
Position of the first toolbar separator.
Definition at line 468 of file GUIOptions.cc.
{
    separatorIter_ = toolbarSeparators_.begin();
    if (separatorIter_ != toolbarSeparators_.end()) {
        return *separatorIter_;
    } else {
        return -1;
    }
}
References separatorIter_, and toolbarSeparators_.
Referenced by createToolbar(), OptionsDialog::readOptions(), and OptionsDialog::writeOptions().
firstShortcut()
KeyboardShortcut * GUIOptions::firstShortcut () const
Returns the first keyboard shortcut. If there are no keyboard shortcuts, returns null pointer.
Returns
The first keyboard shortcut.
Definition at line 397 of file GUIOptions.cc.
{
    ksIter_ = keyboardShortcuts_.begin();
    if (ksIter_ != keyboardShortcuts_.end()) {
        return *ksIter_;
    } else {
        return NULL;
    }
}
References keyboardShortcuts_, and ksIter_.
Referenced by OptionsDialog::readOptions(), and OptionsDialog::writeOptions().
firstToolbarButton()
ToolbarButton * GUIOptions::firstToolbarButton () const
Returns the first toolbar button. Returns null pointer if there are no toolbar buttons.
Returns
The first toolbar button.
Definition at line 432 of file GUIOptions.cc.
{
    tbIter_ = toolbarButtons_.begin();
    if (tbIter_ != toolbarButtons_.end()) {
        return *tbIter_;
    } else {
        return NULL;
    }
}
References tbIter_, and toolbarButtons_.
Referenced by createToolbar(), OptionsDialog::readOptions(), validate(), and OptionsDialog::writeOptions().
fullScreen()
bool GUIOptions::fullScreen () const
Returns true, if the application window opens in full screen mode as default, otherwise false.
Returns
True, if the application window opens in full screen mode as default, otherwise false.
Definition at line 139 of file GUIOptions.cc.
{
    return fullScreen_;
}
References fullScreen_.
Referenced by setFullScreen().
hasFileName()
bool GUIOptions::hasFileName () const
Checks whether these options has file name assigned.
Returns
True if these options has file name assigned, otherwise false.
Definition at line 607 of file GUIOptions.cc.
{
    if (fileName_ == "") {
        return false;
    }
    return true;
}
References fileName_.
isModified()
bool GUIOptions::isModified () const
Returns true if the options are modified.
Returns
True if the options are modified.
Definition at line 513 of file GUIOptions.cc.
{
    return modified_;
}
References modified_.
keyboardShortcut()
KeyboardShortcut * GUIOptions::keyboardShortcut (const std::string commandName) const
Returns keyboard shortcut for the command with given name.
Parameters
commandName Name of the command to search shortcut for.
Returns
NULL if a shortcut doesn't exist for the command.
Definition at line 377 of file GUIOptions.cc.
{
    KSTable::const_iterator iter = keyboardShortcuts_.begin();
    for (; iter != keyboardShortcuts_.end(); iter++) {
        if ((*iter)->action() == commandName) {
            return *iter;
        }
    }
    return NULL;
}
References keyboardShortcuts_.
loadState()
void GUIOptions::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Implements Serializable.
Reimplemented in ProDeOptions.
Definition at line 645 of file GUIOptions.cc.
{
    const string procName = "GUIOptions::loadState";
    if (state->name() != OSNAME_OPTIONS) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        fullScreen_ = state->intAttribute(OSKEY_FULL_SCREEN);
        windowWidth_ = state->intAttribute(OSKEY_WINDOW_WIDTH);
        windowHeight_ = state->intAttribute(OSKEY_WINDOW_HEIGHT);
        xPosition_ = state->intAttribute(OSKEY_X_POS);
        yPosition_ = state->intAttribute(OSKEY_Y_POS);
        toolbarVisibility_ = state->intAttribute(OSKEY_TOOLBAR_VISIBILITY);
        string layout = state->stringAttribute(OSKEY_TOOLBAR_LAYOUT);
        if (layout == OSVALUE_TEXT) {
            toolbarLayout_ = TEXT;
        } else if (layout == OSVALUE_ICON) {
            toolbarLayout_ = ICON;
        } else if (layout == OSVALUE_BOTH) {
            toolbarLayout_ = BOTH;
        } else {
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
        }
        // get toolbar separators, keyboard shortcuts and toolbar buttons
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == OSNAME_SEPARATOR) {
                addSeparator(child->intAttribute(OSKEY_POSITION));
            } else if (child->name() ==
                       KeyboardShortcut::OSNAME_KEYBOARD_SHORTCUT) {
                addKeyboardShortcut(new KeyboardShortcut(child));
            } else if (child->name() == ToolbarButton::OSNAME_TOOLBAR_BUTTON) {
                addToolbarButton(new ToolbarButton(child));
            } else {
                throw ObjectStateLoadingException(__FILE__, __LINE__,
                                                  procName);
            }
        }
    } catch (...) {
        deleteAllKeyboardShortcuts();
        deleteAllToolbarButtons();
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References addKeyboardShortcut(), addSeparator(), addToolbarButton(), BOTH, ObjectState::child(), ObjectState::childCount(), deleteAllKeyboardShortcuts(), deleteAllToolbarButtons(), fullScreen_, ICON, ObjectState::intAttribute(), ObjectState::name(), OSKEY_FULL_SCREEN, OSKEY_POSITION, OSKEY_TOOLBAR_LAYOUT, OSKEY_TOOLBAR_VISIBILITY, OSKEY_WINDOW_HEIGHT, OSKEY_WINDOW_WIDTH, OSKEY_X_POS, OSKEY_Y_POS, KeyboardShortcut::OSNAME_KEYBOARD_SHORTCUT, OSNAME_OPTIONS, OSNAME_SEPARATOR, ToolbarButton::OSNAME_TOOLBAR_BUTTON, OSVALUE_BOTH, OSVALUE_ICON, OSVALUE_TEXT, ObjectState::stringAttribute(), TEXT, toolbarLayout_, toolbarVisibility_, windowHeight_, windowWidth_, xPosition_, and yPosition_.
Referenced by GUIOptions(), and ProDeOptions::loadState().
nextSeparator()
int GUIOptions::nextSeparator () const
Returns always position of the next toolbar separator. If there are no more separators, returns -1.
Returns
Position of the next toolbar separator.
Definition at line 485 of file GUIOptions.cc.
{
    assert(separatorIter_ != toolbarSeparators_.end());
    separatorIter_++;
    if (separatorIter_ != toolbarSeparators_.end()) {
        return *separatorIter_;
    } else {
        return -1;
    }
}
References assert, separatorIter_, and toolbarSeparators_.
Referenced by createToolbar(), and OptionsDialog::readOptions().
nextShortcut()
KeyboardShortcut * GUIOptions::nextShortcut () const
Returns the always the next keyboard shortcut after firstShortcut has been called. Returns null pointer after the last keyboard shortcut.
Returns
The next keyboard shortcut.
Definition at line 414 of file GUIOptions.cc.
{
    assert(ksIter_ != keyboardShortcuts_.end());
    ksIter_++;
    if (ksIter_ != keyboardShortcuts_.end()) {
        return *ksIter_;
    } else {
        return NULL;
    }
}
References assert, keyboardShortcuts_, and ksIter_.
Referenced by OptionsDialog::readOptions().
nextToolbarButton()
ToolbarButton * GUIOptions::nextToolbarButton () const
Returns always the next toolbar button after the firstToolbarButton has been called.
Returns
The next toolbar button.
Definition at line 449 of file GUIOptions.cc.
{
    assert(tbIter_ != toolbarButtons_.end());
    tbIter_++;
    if (tbIter_ != toolbarButtons_.end()) {
        return *tbIter_;
    } else {
        return NULL;
    }
}
References assert, tbIter_, and toolbarButtons_.
Referenced by createToolbar(), OptionsDialog::readOptions(), and validate().
saveState()
ObjectState * GUIOptions::saveState () const virtual
Creates an ObjectState object and saves the state of the object into it.
Returns
The created ObjectState object.
Implements Serializable.
Reimplemented in ProDeOptions.
Definition at line 700 of file GUIOptions.cc.
{
    ObjectState* state = new ObjectState(OSNAME_OPTIONS);
    state->setAttribute(OSKEY_FULL_SCREEN, fullScreen_);
    state->setAttribute(OSKEY_WINDOW_WIDTH, windowWidth_);
    state->setAttribute(OSKEY_WINDOW_HEIGHT, windowHeight_);
    state->setAttribute(OSKEY_X_POS, xPosition_);
    state->setAttribute(OSKEY_Y_POS, yPosition_);
    state->setAttribute(OSKEY_TOOLBAR_VISIBILITY, toolbarVisibility_);
    if (toolbarLayout_ == TEXT) {
        state->setAttribute(OSKEY_TOOLBAR_LAYOUT, OSVALUE_TEXT);
    } else if (toolbarLayout_ == ICON) {
        state->setAttribute(OSKEY_TOOLBAR_LAYOUT, OSVALUE_ICON);
    } else {
        state->setAttribute(OSKEY_TOOLBAR_LAYOUT, OSVALUE_BOTH);
    }
    // add toolbar separators
    for (int i = 0; i < (int)toolbarSeparators_.size(); i++) {
        ObjectState* separator = new ObjectState(OSNAME_SEPARATOR);
        state->addChild(separator);
        separator->setAttribute(OSKEY_POSITION, toolbarSeparators_[i]);
    }
    // add keyboard shortcuts
    for (int i = 0; i < (int)keyboardShortcuts_.size(); i++) {
        KeyboardShortcut* sc = keyboardShortcuts_[i];
        state->addChild(sc->saveState());
    }
    // add toolbar buttons
    for (int i = 0; i < (int)toolbarButtons_.size(); i++) {
        ToolbarButton* button = toolbarButtons_[i];
        state->addChild(button->saveState());
    }
    return state;
}
References ObjectState::addChild(), fullScreen_, ICON, keyboardShortcuts_, OSKEY_FULL_SCREEN, OSKEY_POSITION, OSKEY_TOOLBAR_LAYOUT, OSKEY_TOOLBAR_VISIBILITY, OSKEY_WINDOW_HEIGHT, OSKEY_WINDOW_WIDTH, OSKEY_X_POS, OSKEY_Y_POS, OSNAME_OPTIONS, OSNAME_SEPARATOR, OSVALUE_BOTH, OSVALUE_ICON, OSVALUE_TEXT, KeyboardShortcut::saveState(), ToolbarButton::saveState(), ObjectState::setAttribute(), TEXT, toolbarButtons_, toolbarLayout_, toolbarSeparators_, toolbarVisibility_, windowHeight_, windowWidth_, xPosition_, and yPosition_.
Referenced by ProDeOptions::saveState().
setFileName()
void GUIOptions::setFileName (const std::string & fileName)
Sets the file name assigned into these options.
Parameters
fileName The file name assigned into these options.
Definition at line 632 of file GUIOptions.cc.
{
    fileName_ = fileName;
}
References fileName(), and fileName_.
Referenced by Proxim::createDefaultOptions(), Proxim::loadOptions(), and ProDe::OnInit().
setFullScreen()
void GUIOptions::setFullScreen (bool fullScreen)
Sets or unsets the default full screen mode of the application window.
Parameters
fullScreen If true, the full screen mode is set, otherwise unset.
Definition at line 216 of file GUIOptions.cc.
{
    fullScreen_ = fullScreen;
    modified_ = true;
}
References fullScreen(), fullScreen_, and modified_.
Referenced by ProDe::createDefaultOptions().
setToolbarLayout()
void GUIOptions::setToolbarLayout (ToolbarLayout layout)
Sets the layout of the toolbar buttons.
Parameters
layout Layout of the toolbar buttons.
Definition at line 268 of file GUIOptions.cc.
{
    toolbarLayout_ = layout;
    modified_ = true;
}
References modified_, and toolbarLayout_.
Referenced by Proxim::createDefaultOptions(), ProDe::createDefaultOptions(), and OptionsDialog::writeOptions().
setToolbarVisibility()
void GUIOptions::setToolbarVisibility (bool visible)
Sets the visibility mode of the toolbar.
Parameters
visible If true, the toolbar is visible, otherwise it is hidden.
Definition at line 256 of file GUIOptions.cc.
{
    toolbarVisibility_ = visible;
    modified_ = true;
}
References modified_, and toolbarVisibility_.
Referenced by Proxim::createDefaultOptions(), and ProDe::createDefaultOptions().
setWindowPosition()
void GUIOptions::setWindowPosition (int x, int y)
Sets the default position of the window.
Parameters
x X-coordinate of left side of the application window.
y Y-coordinate of upper side of the application window.
Definition at line 243 of file GUIOptions.cc.
{
    xPosition_ = x;
    yPosition_ = y;
    modified_ = true;
}
References modified_, xPosition_, and yPosition_.
Referenced by ProDe::createDefaultOptions().
setWindowSize()
void GUIOptions::setWindowSize (int width, int height)
Sets the default application window size.
Parameters
width Pixel width of the window.
height Pixel height of the window.
Definition at line 229 of file GUIOptions.cc.
{
    windowWidth_ = width;
    windowHeight_ = height;
    modified_ = true;
}
References modified_, windowHeight_, and windowWidth_.
Referenced by ProDe::createDefaultOptions().
toolbarLayout()
GUIOptions::ToolbarLayout GUIOptions::toolbarLayout () const
Returns the layout mode of the toolbar.
Returns
Layout mode of the toolbar.
Definition at line 205 of file GUIOptions.cc.
{
    return toolbarLayout_;
}
References toolbarLayout_.
Referenced by createToolbar(), and OptionsDialog::readOptions().
toolbarVisibility()
bool GUIOptions::toolbarVisibility () const
Returns true if the toolbar is visible by default, otherwise false.
Returns
True if the toolbar is visible by default, otherwise false.
Definition at line 194 of file GUIOptions.cc.
{
    return toolbarVisibility_;
}
References toolbarVisibility_.
validate()
void GUIOptions::validate () const virtual
Validates the state of the options.
Checks that there is no gaps in toolbar item positions and no two items at the same position. Additionally checks that there is no same keyboard shortcuts for several actions and no two keyboard shortcuts for the same action.
Exceptions
InvalidData If the options are in invalid state.
Definition at line 529 of file GUIOptions.cc.
{
    const string procName = "GUIOptions::validate";
    int buttons = toolbarButtons_.size();
    int separators = toolbarSeparators_.size();
    // check that there is no gaps in toolbar item positions
    for (int i = 0; i < buttons + separators; i++) {
        bool buttonfound = false;
        bool separatorfound = false;
        ToolbarButton* button = firstToolbarButton();
        while (button != NULL) {
            if (button->slot() == i) {
                if (buttonfound) {
                    string errorMsg = "There is at least two toolbar items ";
                    errorMsg += "at position \'" + Conversion::toString(i) +
                        "\'.";
                    throw InvalidData(__FILE__, __LINE__, procName,
                                        errorMsg);
                }
                buttonfound = true;
            }
            button = nextToolbarButton();
        }
        for (int sepIndex = 0; sepIndex < separators; sepIndex++) {
            if (toolbarSeparators_[sepIndex] == i) {
                if (separatorfound || buttonfound) {
                    string errorMsg = "There is at least two toolbar items ";
                    errorMsg += "at position \'" + Conversion::toString(i) +
                        "\'.";
                    throw InvalidData(__FILE__, __LINE__, procName,
                                        errorMsg);
                }
                separatorfound = true;
            }
        }
        if (!buttonfound && !separatorfound) {
            string errorMsg = "There is no separator or button at slot "
                "position \'" + Conversion::toString(i) + "\'.";
            throw InvalidData(__FILE__, __LINE__, procName, errorMsg);
        }
    }
    // check that there is no same keyboard shortcuts for several actions and
    // no two keyboard shortcuts for same action
    KSTable::const_iterator ksIter = keyboardShortcuts_.begin();
    while (ksIter != keyboardShortcuts_.end()) {
        KeyboardShortcut* observable = *ksIter;
        string action = observable->action();
        KSTable::const_iterator seekerIter = keyboardShortcuts_.begin();
        while (seekerIter != keyboardShortcuts_.end()) {
            KeyboardShortcut* sc = *seekerIter;
            if (action == sc->action() && sc != observable) {
                string errorMsg = "Action \'" + action + "\' is assigned for"
                    + " two or more keyboard shortcuts.";
                throw InvalidData(__FILE__, __LINE__, procName, errorMsg);
            }
            if (observable->equals(*sc) && observable != sc) {
                string errorMsg = "Same keyboard shortcut is used for \'" +
                    observable->action() + "\' and \'" + sc->action() +
                    "\' actions.";
                throw InvalidData(__FILE__, __LINE__, procName, errorMsg);
            }
            seekerIter++;
        }
        ksIter++;
    }
}
References KeyboardShortcut::action(), KeyboardShortcut::equals(), firstToolbarButton(), keyboardShortcuts_, nextToolbarButton(), ToolbarButton::slot(), toolbarButtons_, toolbarSeparators_, and Conversion::toString().
Referenced by Proxim::loadOptions(), and ProDe::OnInit().
windowHeight()
int GUIOptions::windowHeight () const
Returns the default height of the application window.
Returns
The default height of the application window.
Definition at line 161 of file GUIOptions.cc.
{
    return windowHeight_;
}
References windowHeight_.
Referenced by ProDe::OnInit().
windowWidth()
int GUIOptions::windowWidth () const
Returns the default width of the application window.
Returns
The default width of the application window.
Definition at line 150 of file GUIOptions.cc.
{
    return windowWidth_;
}
References windowWidth_.
Referenced by ProDe::OnInit().
xPosition()
int GUIOptions::xPosition () const
Returns the default x position of left side of the application window.
Returns
The default x position of left side of the application window.
Definition at line 172 of file GUIOptions.cc.
{
    return xPosition_;
}
References xPosition_.
Referenced by ProDe::OnInit().
yPosition()
int GUIOptions::yPosition () const
Returns the default y position of upper side of the application window.
Returns
The default y position of upper side of the application window.
Definition at line 183 of file GUIOptions.cc.
{
    return yPosition_;
}
References yPosition_.
Referenced by ProDe::OnInit().
Member Data Documentation
fileName_
std::string GUIOptions::fileName_ private
File name assigned to these options.
Definition at line 169 of file GUIOptions.hh.
Referenced by fileName(), hasFileName(), and setFileName().
fullScreen_
bool GUIOptions::fullScreen_ private
If true, the application window will open in full screen mode.
Definition at line 171 of file GUIOptions.hh.
Referenced by fullScreen(), GUIOptions(), loadState(), saveState(), and setFullScreen().
keyboardShortcuts_
KSTable GUIOptions::keyboardShortcuts_ private
Keyboard shortcuts.
Definition at line 187 of file GUIOptions.hh.
Referenced by addKeyboardShortcut(), deleteAllKeyboardShortcuts(), deleteKeyboardShortcut(), firstShortcut(), GUIOptions(), keyboardShortcut(), nextShortcut(), saveState(), and validate().
ksIter_
KSTable::const_iterator GUIOptions::ksIter_ mutable private
Iterator used in firstShortcut and nextShortcut functions.
Definition at line 192 of file GUIOptions.hh.
Referenced by firstShortcut(), and nextShortcut().
modified_
bool GUIOptions::modified_ private
Indicates whether the options are modified or not.
Definition at line 199 of file GUIOptions.hh.
Referenced by addKeyboardShortcut(), addSeparator(), addToolbarButton(), clearModified(), deleteKeyboardShortcut(), deleteSeparator(), deleteToolbarButton(), GUIOptions(), isModified(), setFullScreen(), setToolbarLayout(), setToolbarVisibility(), setWindowPosition(), and setWindowSize().
name_
std::string GUIOptions::name_ private
Name of the options.
Definition at line 201 of file GUIOptions.hh.
OSKEY_FULL_SCREEN
const string GUIOptions::OSKEY_FULL_SCREEN = "fscreen" static
ObjectState attribute key for full screen feature.
Definition at line 131 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setWindowProperties().
OSKEY_POSITION
const string GUIOptions::OSKEY_POSITION = "pos" static
ObjectState attribute key for separator position.
Definition at line 153 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSKEY_TOOLBAR_LAYOUT
const string GUIOptions::OSKEY_TOOLBAR_LAYOUT = "tblayout" static
ObjectState attribute key for toolbar layout.
Definition at line 143 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSKEY_TOOLBAR_VISIBILITY
const string GUIOptions::OSKEY_TOOLBAR_VISIBILITY = "tbvisib" static
ObjectState attribute key for toolbar visibility.
Definition at line 141 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSKEY_WINDOW_HEIGHT
const string GUIOptions::OSKEY_WINDOW_HEIGHT = "wheight" static
ObjectState attribute key for window height.
Definition at line 135 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setWindowProperties().
OSKEY_WINDOW_WIDTH
const string GUIOptions::OSKEY_WINDOW_WIDTH = "wwidth" static
ObjectState attribute key for window width.
Definition at line 133 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setWindowProperties().
OSKEY_X_POS
const string GUIOptions::OSKEY_X_POS = "xpos" static
ObjectState attribute key for window x position.
Definition at line 137 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setWindowProperties().
OSKEY_Y_POS
const string GUIOptions::OSKEY_Y_POS = "ypos" static
ObjectState attribute key for window y position.
Definition at line 139 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setWindowProperties().
OSNAME_OPTIONS
const string GUIOptions::OSNAME_OPTIONS = "options" static
ObjectState name for the options.
Definition at line 129 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), and saveState().
OSNAME_SEPARATOR
const string GUIOptions::OSNAME_SEPARATOR = "separator" static
ObjectState name for separator.
Definition at line 151 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSVALUE_BOTH
const string GUIOptions::OSVALUE_BOTH = "both" static
ObjectState attribute value for text & icon layout.
Definition at line 149 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToOptionsObjectFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSVALUE_ICON
const string GUIOptions::OSVALUE_ICON = "icon" static
ObjectState attribute value for icon layout.
Definition at line 147 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSVALUE_TEXT
const string GUIOptions::OSVALUE_TEXT = "text" static
ObjectState attribute value for text layout.
Definition at line 145 of file GUIOptions.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
separatorIter_
SeparatorTable::const_iterator GUIOptions::separatorIter_ mutable private
Iterator used in firstSeparator and nextSeparator functions.
Definition at line 196 of file GUIOptions.hh.
Referenced by firstSeparator(), and nextSeparator().
tbIter_
TBTable::const_iterator GUIOptions::tbIter_ mutable private
Iterator used in firstToolbarButton and nextToolbarButton functions.
Definition at line 194 of file GUIOptions.hh.
Referenced by firstToolbarButton(), and nextToolbarButton().
TOOLBAR_SEPARATOR
const string GUIOptions::TOOLBAR_SEPARATOR = "-- separator --" static
Toolbar separator name.
Definition at line 127 of file GUIOptions.hh.
Referenced by OptionsDialog::readOptions(), OptionsDialog::TransferDataToWindow(), and OptionsDialog::writeOptions().
toolbarButtons_
TBTable GUIOptions::toolbarButtons_ private
Toolbar buttons.
Definition at line 189 of file GUIOptions.hh.
Referenced by addToolbarButton(), deleteAllToolbarButtons(), deleteToolbarButton(), firstToolbarButton(), GUIOptions(), nextToolbarButton(), saveState(), and validate().
toolbarLayout_
ToolbarLayout GUIOptions::toolbarLayout_ private
Layout of the toolbar.
Definition at line 183 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setToolbarLayout(), and toolbarLayout().
toolbarSeparators_
SeparatorTable GUIOptions::toolbarSeparators_ private
Toolbar separators.
Definition at line 185 of file GUIOptions.hh.
Referenced by addSeparator(), deleteSeparator(), firstSeparator(), GUIOptions(), nextSeparator(), saveState(), and validate().
toolbarVisibility_
bool GUIOptions::toolbarVisibility_ private
If true, the toolbar is visible.
Definition at line 181 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setToolbarVisibility(), and toolbarVisibility().
windowHeight_
int GUIOptions::windowHeight_ private
Default height of the window.
Definition at line 175 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setWindowSize(), and windowHeight().
windowWidth_
int GUIOptions::windowWidth_ private
Default width of the window.
Definition at line 173 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setWindowSize(), and windowWidth().
xPosition_
int GUIOptions::xPosition_ private
Default x position of left side of the application window.
Definition at line 177 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setWindowPosition(), and xPosition().
yPosition_
int GUIOptions::yPosition_ private
Default y position of the upper side of the application window.
Definition at line 179 of file GUIOptions.hh.
Referenced by GUIOptions(), loadState(), saveState(), setWindowPosition(), and yPosition().
The documentation for this class was generated from the following files:
GUIOptions.hh
GUIOptions.cc