OpenASIP: TPEF::ASpaceSection Class Reference
TPEF::ASpaceSection Class Reference
#include <ASpaceSection.hh>
Public Member Functions
virtual ~ASpaceSection ()
virtual SectionType type () const
bool isUndefined (ASpaceElement *aSpace) const
void setUndefinedASpace (ASpaceElement *aSpace)
ASpaceElement * undefinedASpace () const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
ASpaceSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * undefinedElement_
Undefined address space. This element is not allowed to be removed from section is recognized as special undefined address space.
Static Private Attributes
static ASpaceSection proto_
Prototype instance.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Address space section.
Definition at line 44 of file ASpaceSection.hh.
Constructor & Destructor Documentation
~ASpaceSection()
TPEF::ASpaceSection::~ASpaceSection () virtual
Destructor
Definition at line 63 of file ASpaceSection.cc.
{
}
ASpaceSection()
TPEF::ASpaceSection::ASpaceSection (bool init) protected
Constructor.
Parameters
init true if registeration is wanted
Definition at line 48 of file ASpaceSection.cc.
                                      :
    Section(), undefinedElement_(&SafePointer::null) {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagVLen();
    unsetFlagNoBits();
    setStartingAddress(0);
}
References TPEF::Section::registerSection(), TPEF::Section::setStartingAddress(), TPEF::Section::unsetFlagNoBits(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
clone()
Section * TPEF::ASpaceSection::clone () const protected virtual
Creates an instance of class.
Returns
Newly created section.
Implements TPEF::Section.
Definition at line 82 of file ASpaceSection.cc.
{
    return new ASpaceSection(false);
}
isUndefined()
bool TPEF::ASpaceSection::isUndefined (ASpaceElement * aSpace) const
Checks if the parameter, is undefined address space.
Parameters
aSpace Element to check.
Returns
True, if parameter is the undefined address space.
Definition at line 93 of file ASpaceSection.cc.
{
    assert(aSpace != NULL);
    assert(undefinedElement_ != &SafePointer::null);
    return (undefinedElement_->pointer() == aSpace);
}
References TPEF::Section::aSpace(), assert, TPEF::ReferenceManager::SafePointer::null, TPEF::ReferenceManager::SafePointer::pointer(), and undefinedElement_.
Referenced by TPEFDumper::addressSpaceString(), and TPEF::TPEFRelocSectionReader::finalize().
setUndefinedASpace()
void TPEF::ASpaceSection::setUndefinedASpace (ASpaceElement * aSpace)
Set undefined address space.
This method must be runned, before checking of undefined address space is allowed. If set is runned many times, it overrides earlier setings.
Parameters
aSpace Element to define as undefined address space.
Definition at line 109 of file ASpaceSection.cc.
{
    assert(aSpace != NULL);
    assert(aSpace->MAU() == 0);
    assert(aSpace->align() == 0);
    assert(aSpace->wordSize() == 0);
    undefinedElement_ = SafePointer::replaceReference(
        undefinedElement_, aSpace);
}
References TPEF::ASpaceElement::align(), TPEF::Section::aSpace(), assert, TPEF::ASpaceElement::MAU(), TPEF::ReferenceManager::SafePointer::replaceReference(), undefinedElement_, and TPEF::ASpaceElement::wordSize().
Referenced by TTAProgram::ProgramWriter::createBinary(), TPEF::AOutReader::readData(), TPEF::TPEFASpaceSectionReader::readData(), and MachineResourceManager::undefinedAddressSpace().
type()
Section::SectionType TPEF::ASpaceSection::type () const virtual
Returns sections type.
Returns
type of section.
Implements TPEF::Section.
Definition at line 72 of file ASpaceSection.cc.
{
    return ST_ADDRSP;
}
References TPEF::Section::ST_ADDRSP.
undefinedASpace()
ASpaceElement * TPEF::ASpaceSection::undefinedASpace () const
Returns undefined address space element.
Returns
Undefined address space element.
Definition at line 124 of file ASpaceSection.cc.
{
    return dynamic_cast<ASpaceElement*>(
        undefinedElement_->pointer());
}
References TPEF::ReferenceManager::SafePointer::pointer(), and undefinedElement_.
Referenced by TTAProgram::ProgramWriter::createRelocSections().
Member Data Documentation
proto_
ASpaceSection TPEF::ASpaceSection::proto_ static private
Prototype instance.
Definition at line 62 of file ASpaceSection.hh.
undefinedElement_
const ReferenceManager::SafePointer* TPEF::ASpaceSection::undefinedElement_ private
Undefined address space. This element is not allowed to be removed from section is recognized as special undefined address space.
Definition at line 66 of file ASpaceSection.hh.
Referenced by isUndefined(), setUndefinedASpace(), and undefinedASpace().
The documentation for this class was generated from the following files:
ASpaceSection.hh
ASpaceSection.cc