OpenASIP: TTAMachine::HWOperation Class Reference
TTAMachine::HWOperation Class Reference
#include <HWOperation.hh>
Public Member Functions
HWOperation (const std::string &name, FunctionUnit &parent)
HWOperation (const ObjectState *state, FunctionUnit &parent)
~HWOperation ()
const std::string & name () const
virtual void setName (const std::string &name)
FunctionUnit * parentUnit () const
ExecutionPipeline * pipeline () const
int latency () const
int latency (int output) const
int slack (int input) const
virtual void bindPort (int operand, const FUPort &port)
virtual void unbindPort (const FUPort &port)
int operandCount () const
virtual FUPort * port (int operand) const
bool isBound (const FUPort &port) const
bool isBound (int operand) const
int io (const FUPort &port) const
int numberOfInputs () const
int numberOfOutputs () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_OPERATION = "operation"
ObjectState name for HWOperation.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for name of the operation.
static const std::string OSNAME_OPERAND_BINDING = "binding"
ObjectState name for an operand binding.
static const std::string OSKEY_OPERAND = "operand"
ObjectState attribute key for operand index.
static const std::string OSKEY_PORT = "port"
ObjectState attribute key for port name.
Private Types
typedef std::map< int, const FUPort * > OperandBindingMap
Map for mapping operand indexes to FUPorts.
Private Attributes
std::string name_
Name of the operation.
ExecutionPipeline * pipeline_
Pipeline of the operation.
FunctionUnit * parent_
The parent unit.
OperandBindingMap operandBinding_
Maps operands of operation to particular ports of the parent unit.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents an operation of the function unit.
Definition at line 52 of file HWOperation.hh.
Member Typedef Documentation
OperandBindingMap
typedef std::map<int, const FUPort*> TTAMachine::HWOperation::OperandBindingMap private
Map for mapping operand indexes to FUPorts.
Definition at line 94 of file HWOperation.hh.
Constructor & Destructor Documentation
HWOperation() [1/2]
TTAMachine::HWOperation::HWOperation (const std::string & name, FunctionUnit & parent)
Constructor.
Parameters
name Name of the operation.
parent The parent unit.
Exceptions
ComponentAlreadyExists If there is already an operation by the same name in the given function unit.
InvalidName If the given name is not valid for a component.
Definition at line 67 of file HWOperation.cc.
                                                                 :
    SubComponent(), name_(name), pipeline_(NULL), parent_(NULL) {
    name_ = StringTools::stringToLower(name);
    if (!MachineTester::isValidComponentName(name_)) {
        const string procName = "HWOperation::HWOperation";
        MOMTextGenerator textGen;
        format errorMsg = textGen.text(MOMTextGenerator::TXT_INVALID_NAME);
        errorMsg % name;
        throw InvalidName(__FILE__, __LINE__, procName, errorMsg.str());
    }
    parent.addOperation(*this);
    parent_ = &parent;
    pipeline_ = new ExecutionPipeline(*this);
}
References TTAMachine::FunctionUnit::addOperation(), MachineTester::isValidComponentName(), name(), name_, parent_, pipeline_, StringTools::stringToLower(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_INVALID_NAME.
HWOperation() [2/2]
TTAMachine::HWOperation::HWOperation (const ObjectState * state, FunctionUnit & parent)
Constructor.
Loads the state of the operation from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent unit.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 95 of file HWOperation.cc.
                                                                       :
    SubComponent(), name_(""), pipeline_(NULL), parent_(&parent) {
    const string procName = "HWOperation::HWOperation";
    // set name
    try {
        setName(state->stringAttribute(OSKEY_NAME));
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    parent_ = NULL;
    // register to parent unit
    parent.addOperation(*this);
    parent_ = &parent;
    try {
        loadState(state);
    } catch (const ObjectStateLoadingException& e) {
        if (pipeline_ != NULL) {
            delete pipeline_;
        }
        throw;
    }
}
References TTAMachine::FunctionUnit::addOperation(), Exception::errorMessage(), loadState(), OSKEY_NAME, parent_, pipeline_, setName(), and ObjectState::stringAttribute().
~HWOperation()
TTAMachine::HWOperation::~HWOperation ()
Destructor.
Definition at line 127 of file HWOperation.cc.
{
    delete pipeline_;
    FunctionUnit* parent = parentUnit();
    parent_ = NULL;
    parent->deleteOperation(*this);
}
References TTAMachine::FunctionUnit::deleteOperation(), parent_, parentUnit(), and pipeline_.
Member Function Documentation
bindPort()
void TTAMachine::HWOperation::bindPort (int operand, const FUPort & port) virtual
Binds the given operand of the operation to the given port of the function unit.
If the given operand is already bound to another port, the old binding is replaced with the new one.
Parameters
operand Index of the operand.
port The port.
Exceptions
IllegalRegistration If the given port does not belong to the same function unit as this operation.
ComponentAlreadyExists If the given port is already reserved for another operand.
OutOfRange If the given operand is less than 1.
Reimplemented in SmartHWOperation.
Definition at line 269 of file HWOperation.cc.
{
    const string procName = "HWOperation::bindPort";
    if (operand < 1) {
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    if (port.parentUnit() != parentUnit()) {
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    if (MapTools::containsValue(operandBinding_, &port) &&
        this->HWOperation::port(operand) != &port) {
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    operandBinding_[operand] = &port;
    port.updateBindingString();
}
References MapTools::containsValue(), operandBinding_, TTAMachine::BaseFUPort::parentUnit(), parentUnit(), port(), and TTAMachine::FUPort::updateBindingString().
Referenced by VectorLSGenerator::addOperation(), HDB::HDBManager::addPortsAndBindingsToFUArchitecture(), OpsetDialog::bindPorts(), BlocksLSU::BindPorts(), BlocksALU::BindPorts(), BlocksGCU::BindPorts(), BlocksMUL::BindPorts(), UniversalMachine::construct(), AddGCUCmd::Do(), CostEstimator::ICDecoderEstimatorPlugin::generateControlUnit(), loadState(), OperationDialog::onBindOperand(), and SmartHWOperation::port().
io()
int TTAMachine::HWOperation::io (const FUPort & port) const
Returns the index of the input or output that is bound to the given port.
Parameters
port The port.
Returns
The index of the input or output.
Exceptions
InstanceNotFound If no io is bound to the given port.
Definition at line 364 of file HWOperation.cc.
{
    if (!isBound(port)) {
        const string procName = "HWOperation::operand";
        const string msg = string("The port '") + port.name()
            + "' is not bound to the operation '"
            + name() + "'.";
        throw InstanceNotFound(__FILE__, __LINE__, procName, msg);
    }
    return MapTools::keyForValue<int>(operandBinding_, &port);
}
References isBound(), MapTools::keyForValue(), name(), TTAMachine::Port::name(), operandBinding_, and port().
Referenced by ProgrammabilityValidator::addConnectionToProgram(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createFUPort(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), createTerminalFUPort(), SocketBusConnCmd::Do(), ProGe::NetlistGenerator::findCorrespondingPort(), TTAProgram::TerminalFUPort::findNewOperationIndex(), BasicBlockScheduler::findTriggerFromUnit(), ProgramOperation::findTriggerFromUnit(), MachineResourceManager::functionUnitPortResource(), HDB::HDBManager::isMatchingArchitecture(), ExecutionPipelineResource::nodeOfInputPort(), OperationDialog::onOperandSelection(), MachineInfo::operandFromPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), HDB::FUArchitecture::operator==(), ProgramOperation::outputIndexFromGuard(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::ProgramWriter::terminalResource(), FUPortImplementationDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), FUImplementationDialog::update(), and OperationDialog::updateOperandList().
isBound() [1/2]
bool TTAMachine::HWOperation::isBound (const FUPort & port) const
Checks whether the given port is bound to one of the operands of the operation.
Parameters
port The port.
Returns
True if the port is bound, otherwise false.
Definition at line 338 of file HWOperation.cc.
{
    return MapTools::containsValue(operandBinding_, &port);
}
References MapTools::containsValue(), operandBinding_, and port().
Referenced by HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), VectorLSGenerator::addOperation(), MachineStateBuilder::addPortToFU(), TTAProgram::ProgramWriter::createCodeSection(), SocketBusConnCmd::Do(), ProGe::NetlistGenerator::findCorrespondingPort(), MachineInfo::getBoundPort(), io(), HDB::HDBManager::isMatchingArchitecture(), loadState(), OperationDialog::onOperandSelection(), HDB::FUArchitecture::operator==(), SmartHWOperation::port(), FUPortImplementationDialog::TransferDataToWindow(), FUImplementationDialog::update(), TTAMachine::FUPort::updateBindingString(), and OperationDialog::updateOperandList().
isBound() [2/2]
bool TTAMachine::HWOperation::isBound (int operand) const
Checks whetever the given operand is bound to some port.
Parameters
operand The operand.
Returns
True if bound and otherwise false.
Definition at line 349 of file HWOperation.cc.
{
    if (operand < 1) {
        THROW_EXCEPTION(OutOfRange, "Operand out of range (must be > 0).");
    }
    return MapTools::containsKey(operandBinding_, operand);
}
References MapTools::containsKey(), operandBinding_, and THROW_EXCEPTION.
latency() [1/2]
int TTAMachine::HWOperation::latency () const
Returns the number of cycles used during execution of the operation.
Different results may have different latencies, thus this is the longest latency of any result produced by the operation. After this latency the operation execution has been finished and no results will be produced.
Returns
The latency of the operation.
Definition at line 216 of file HWOperation.cc.
{
    return pipeline_->latency();
}
References TTAMachine::ExecutionPipeline::latency(), and pipeline_.
Referenced by AddFUFromHDBDialog::acceptToList(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), MultiLatencyOperationExecutor::advanceClock(), ControlFlowGraph::buildMBBFromBB(), ExecutionPipelineResource::canAssignSource(), FUGen::checkForValidity(), FullyConnectedCheck::connectFUPort(), FUTestbenchGenerator::createStimulus(), ExecutionPipelineBroker::earliestFromDestination(), ExecutionPipelineBroker::earliestFromSource(), MoveNode::earliestResultReadCycle(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), HDBBrowserWindow::fuArchLabel(), HDBToHtml::fuArchToHtml(), CompiledSimCodeGenerator::generateLoadTrigger(), ProGe::RV32MicroCodeGenerator::generateOperationLatencyLogic(), CompiledSimCodeGenerator::generateTriggerCode(), CompiledSimCodeGenerator::handleOperation(), CompiledSimCodeGenerator::handleOperationWithoutDag(), HDB::HDBManager::isMatchingArchitecture(), DataDependenceEdge::latencySt(), ExecutionPipelineBroker::latestFromDestination(), MoveNode::latestTriggerWriteCycle(), ExecutionPipelineResource::latestTriggerWriteCycle(), AddFUFromHDBDialog::loadHDB(), TTAMachine::FunctionUnit::maxLatency(), MultiLatencyOperationExecutor::MultiLatencyOperationExecutor(), TTAMachine::FunctionUnit::needsConflictDetection(), AddFUFromHDBDialog::onAdd(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), HDB::FUArchitecture::operator==(), FUGen::parseOperations(), HDB::FUArchitecture::portDirection(), BF2ScheduleFront::prefResultCycle(), printLatexFunctionUnitDescription(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultReadyCycle(), DataDependenceEdge::saveState(), BUBasicBlockScheduler::scheduleMove(), DataDependenceGraph::setMachine(), ExecutionPipelineResource::setResultWriten(), MultiLatencyOperationExecutor::startOperation(), ExecutionPipelineResource::testTriggerResult(), FUPortImplementationDialog::TransferDataToWindow(), ExecutionPipelineResource::unsetResultWriten(), and OperationDialog::updateLatency().
latency() [2/2]
int TTAMachine::HWOperation::latency (int output) const
Returns the latency for the given output.
Parameters
output The number of the output.
Returns
The latency for the given output.
Exceptions
IllegalParameters If the given output is not written in the pipeline.
Definition at line 230 of file HWOperation.cc.
{
    return pipeline_->latency(output);
}
References TTAMachine::ExecutionPipeline::latency(), and pipeline_.
loadState()
void TTAMachine::HWOperation::loadState (const ObjectState * state) virtual
Loads the state of the operation from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Reimplemented in SmartHWOperation.
Definition at line 454 of file HWOperation.cc.
{
    const string procName = "HWOperation::loadState";
    if (state->name() != OSNAME_OPERATION) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    MOMTextGenerator textGenerator;
    try {
        setName(state->stringAttribute(OSKEY_NAME));
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    try {
        // load operand binding map
        operandBinding_.clear();
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            if (child->name() == OSNAME_OPERAND_BINDING) {
                int operand = child->intAttribute(OSKEY_OPERAND);
                string portName = child->stringAttribute(OSKEY_PORT);
                if (parentUnit()->hasOperationPort(portName)) {
                    FUPort* port = parentUnit()->operationPort(portName);
                    if (isBound(*port)) {
                        format text = textGenerator.text(
                            MOMTextGenerator::TXT_OPERAND_BOUND_TO_PORT);
                        text % name() % portName % parentUnit()->name();
                        throw ObjectStateLoadingException(
                            __FILE__, __LINE__, procName, text.str());
                    } else if (this->port(operand) != NULL) {
                        format text = textGenerator.text(
                            MOMTextGenerator::TXT_OPERAND_ALREADY_BOUND);
                        text % operand % portName % name() %
                            parentUnit()->name() %
                            this->port(operand)->name();
                        throw ObjectStateLoadingException(
                            __FILE__, __LINE__, procName, text.str());
                    } else {
                        bindPort(operand, *port);
                    }
                } else {
                    format text = textGenerator.text(
                        MOMTextGenerator::TXT_OPERATION_REF_LOAD_ERR_PORT);
                    text % portName % name() % parentUnit()->name();
                    throw ObjectStateLoadingException(
                        __FILE__, __LINE__, procName, text.str());
                }
            }
        }
        // load pipeline
        if (pipeline_ != NULL) {
            delete pipeline_;
        }
        ObjectState* pipelineState = state->childByName(
            ExecutionPipeline::OSNAME_PIPELINE);
        pipeline_ = new ExecutionPipeline(*this);
        pipeline()->loadState(pipelineState);
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, e.errorMessage());
    }
}
References bindPort(), ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), Exception::errorMessage(), ObjectState::intAttribute(), isBound(), TTAMachine::ExecutionPipeline::loadState(), name(), TTAMachine::Component::name(), TTAMachine::Port::name(), ObjectState::name(), operandBinding_, TTAMachine::FunctionUnit::operationPort(), OSKEY_NAME, OSKEY_OPERAND, OSKEY_PORT, OSNAME_OPERAND_BINDING, OSNAME_OPERATION, TTAMachine::ExecutionPipeline::OSNAME_PIPELINE, parentUnit(), pipeline(), pipeline_, port(), setName(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_OPERAND_ALREADY_BOUND, MOMTextGenerator::TXT_OPERAND_BOUND_TO_PORT, and MOMTextGenerator::TXT_OPERATION_REF_LOAD_ERR_PORT.
Referenced by HWOperation().
name()
const string & TTAMachine::HWOperation::name () const
Returns the name of the operation.
Returns
The name of the operation.
Definition at line 141 of file HWOperation.cc.
{
    return name_;
}
References name_.
Referenced by AddFUFromHDBDialog::acceptToList(), HDB::HDBManager::addFUArchitecture(), HDB::HDBManager::addFUImplementation(), TTAMachine::FunctionUnit::addOperation(), BEMGenerator::addPortCodes(), UniversalFunctionUnit::addSupportedOperation(), MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), MachineStateBuilder::bindPortsToOperands(), ControlFlowGraph::buildMBBFromBB(), AddressSpaceCheck::check(), OperationBindingCheck::check(), FUValidator::checkOperandBindings(), BEMValidator::checkSocketCodeTable(), FUFactory::createEditPart(), GCUFactory::createEditPart(), FUGen::createFUHeaderComment(), POMDisassembler::createFUPort(), FUTestbenchGenerator::createStimulus(), ConflictDetectionCodeGenerator::detectConflicts(), ProximFUDetailsCmd::Do(), SocketBusConnCmd::Do(), CodeCompressorPlugin::encodeFUTerminal(), InfoProcCommand::execute(), InfoStatsCommand::execute(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), ProGe::NetlistGenerator::findCorrespondingPort(), AlmaIFIntegrator::findMemories(), TTAProgram::TerminalFUPort::findNewOperationIndex(), SimulatorFrontend::finishSimulation(), HDBBrowserWindow::fuArchLabel(), ComponentImplementationSelector::fuArchsByOpSetWithMinLatency(), HDBToHtml::fuArchToHtml(), HDB::HDBManager::fuEntriesByArchitecture(), FUFiniteStateAutomaton::FUFiniteStateAutomaton(), CompiledSimCodeGenerator::generateConstructorCode(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), CompiledSimCodeGenerator::generateInstruction(), CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateStoreTrigger(), CompiledSimCodeGenerator::generateTriggerCode(), MachineInfo::getOpset(), MachineInfo::getOpset(), CompiledSimCodeGenerator::handleJump(), CompiledSimCodeGenerator::handleOperation(), CompiledSimCodeGenerator::handleOperationWithoutDag(), HWOperation(), llvm::LLVMTCEBuilder::initDataSections(), io(), HDB::HDBManager::isMatchingArchitecture(), TTAMachine::ExecutionPipeline::latency(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), AddFUFromHDBDialog::loadHDB(), TTAMachine::ExecutionPipeline::loadState(), loadState(), MachineInfo::maxMemoryAlignment(), MultiLatencyOperationExecutor::MultiLatencyOperationExecutor(), AddFUFromHDBDialog::onAdd(), FUImplementationDialog::onOK(), FUImplementationDialog::onSetOpcode(), DefaultDecoderGenerator::opcode(), ProGe::NetlistGenerator::opcodePortWidth(), ProGe::NetlistGenerator::opcodePortWidth(), TTAProgram::TPEFResourceUpdater::operand(), operandBindingsString(), MachineInfo::operandFromPort(), MachineConnectivityCheck::operandWidth(), DCMFUResourceConflictDetector::operationID(), ReservationTableFUResourceConflictDetector::operationID(), HDB::FUArchitecture::operator==(), MachineInfo::osalOperation(), PlatformIntegrator::parseDataMemories(), ProgrammabilityValidator::printConnection(), printLatexFunctionUnitDescription(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), saveState(), DataDependenceGraph::setMachine(), setName(), TTAProgram::TerminalFUPort::setOperation(), TTAMachine::ExecutionPipeline::slack(), TTAProgram::TerminalFUPort::TerminalFUPort(), TTAProgram::TerminalFUPort::TerminalFUPort(), EntryKeyDataFunctionUnit::toString(), TTAProgram::TerminalFUPort::toString(), FUPortImplementationDialog::TransferDataToWindow(), OperationDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), FUImplementationDialog::update(), TTAMachine::FUPort::updateBindingString(), FUDialog::updateOperationList(), GCUDialog::updateOperationList(), TDGen::writeBackendCode(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), and TDGen::writeInstrInfo().
numberOfInputs()
int TTAMachine::HWOperation::numberOfInputs () const
Returns the number of input ports tied to the operation
Returns
Number of input ports
Definition at line 384 of file HWOperation.cc.
{
    int inputs = 0;
    for (int i = 1; i < operandCount() + 1; i++) {
        FUPort* p = port(i);
        if (p == NULL) {
            continue;
        } else if (p->isInput()) {
            inputs++;
        }
    }
    return inputs;
}
References TTAMachine::Port::isInput(), operandCount(), and port().
Referenced by UniversalFunctionUnit::addSupportedOperation(), and OTAOperationDialog::TransferDataToWindow().
numberOfOutputs()
int TTAMachine::HWOperation::numberOfOutputs () const
Returns the number of output ports tied to the operation
Returns
Number of output ports
Definition at line 404 of file HWOperation.cc.
{
    int outputs = 0;
    for (int i = 1; i < operandCount() + 1; i++) {
        FUPort* p = port(i);
        if (p == NULL) {
            continue;
        }
        if (p->isOutput()) {
            outputs++;
        }
    }
    return outputs;
}
References TTAMachine::Port::isOutput(), operandCount(), and port().
Referenced by UniversalFunctionUnit::addSupportedOperation(), and OTAOperationDialog::TransferDataToWindow().
operandCount()
int TTAMachine::HWOperation::operandCount () const
Returns number of operands for this operation.
Definition at line 306 of file HWOperation.cc.
{
    return operandBinding_.size();
}
References operandBinding_.
Referenced by ProGe::RV32MicroCodeGenerator::addBPorts(), ProGe::RV32MicroCodeGenerator::addIPorts(), ProGe::RV32MicroCodeGenerator::addR1Ports(), ProGe::RV32MicroCodeGenerator::addR1RPorts(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addSPorts(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), FUGen::checkForValidity(), getOutputPort(), MachineInfo::getPortBindingsOfOperation(), numberOfInputs(), numberOfOutputs(), FUGen::parseOperations(), and FUGen::scheduleOperations().
parentUnit()
FunctionUnit * TTAMachine::HWOperation::parentUnit () const
Returns the parent unit of the operation.
Returns
The parent unit of the operation.
Definition at line 190 of file HWOperation.cc.
{
    return parent_;
}
References parent_.
Referenced by TTAMachine::FunctionUnit::addOperation(), TTAMachine::ExecutionPipeline::addPipelineElement(), bindPort(), ControlFlowGraph::buildMBBFromBB(), TTAMachine::FunctionUnit::deleteOperation(), ConflictDetectionCodeGenerator::detectConflicts(), CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateStoreTrigger(), CompiledSimCodeGenerator::handleOperation(), CompiledSimCodeGenerator::handleOperationWithoutDag(), TTAMachine::ExecutionPipeline::internalRemoveResourceUse(), TTAMachine::ExecutionPipeline::latency(), TTAMachine::ExecutionPipeline::loadState(), loadState(), OperationDialog::onAddResource(), OperationDialog::onBindOperand(), OperationDialog::onOperandSelection(), OperationDialog::onResourceLClick(), DefaultDecoderGenerator::opcode(), TTAProgram::TPEFResourceUpdater::operand(), SmartHWOperation::parentUnit(), TTAMachine::ExecutionPipeline::pipelineElement(), TTAMachine::ExecutionPipeline::removeAllResourceUses(), TTAMachine::ExecutionPipeline::removeResourceUse(), ReservationTable::ReservationTable(), setName(), TTAMachine::ExecutionPipeline::slack(), OperationDialog::updateOperandList(), OperationDialog::updateResourceGrid(), and ~HWOperation().
pipeline()
ExecutionPipeline * TTAMachine::HWOperation::pipeline () const
Returns the pipeline used by this operation.
Returns
The pipeline used by this operation.
Definition at line 201 of file HWOperation.cc.
{
    return pipeline_;
}
References pipeline_.
Referenced by HDB::HDBManager::addFUArchitecture(), VectorLSGenerator::addOperation(), HDB::HDBManager::addOperationPipelinesToFUArchitecture(), MachineStateBuilder::addPortToFU(), OperationBindingCheck::check(), FUValidator::checkOperandBindings(), FUValidator::checkOperations(), TTAMachine::FunctionUnit::cleanup(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectVectorLSU(), UniversalMachine::construct(), BlocksLSU::CreateHWLoadOp(), BlocksALU::CreateHWOp(), BlocksGCU::CreateHWOp(), BlocksMUL::CreateHWOp(), BlocksLSU::CreateHWStoreOp(), OpsetDialog::createOperation(), AddGCUCmd::Do(), llvm::LLVMTCEBuilder::emitOperationMacro(), TTAMachine::ExecutionPipeline::ExecutionPipeline(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), HDBToHtml::fuArchToHtml(), CostEstimator::ICDecoderEstimatorPlugin::generateControlUnit(), HDB::HDBManager::isMatchingArchitecture(), loadState(), AddFUFromHDBDialog::onAdd(), OperationDialog::onDeleteOperand(), OperationDialog::onDeleteResource(), OperationDialog::onOperandLClick(), OperationDialog::onResourceLClick(), HDB::FUArchitecture::operator==(), HDB::FUArchitecture::portDirection(), ReservationTable::ReservationTable(), TTAMachine::ResourceVectorSet::ResourceVectorSet(), SmartHWOperation::SmartHWOperation(), FUPortImplementationDialog::TransferDataToWindow(), OperationDialog::updateOperandList(), OperationDialog::updateResourceGrid(), OperationDialog::updateUsageGrid(), OperationDialog::warnOnResourcesWithoutUsages(), and TTAMachine::PipelineElement::~PipelineElement().
port()
FUPort * TTAMachine::HWOperation::port (int operand) const virtual
Returns the port of the function unit that is bound to the given operand.
Returns NULL if no port is bound to the given operand.
Parameters
operand Index of the operand.
Returns
The port or NULL.
Reimplemented in SmartHWOperation.
Definition at line 320 of file HWOperation.cc.
{
    OperandBindingMap::const_iterator iter = operandBinding_.find(operand);
    if (iter != operandBinding_.end()) {
        return const_cast<FUPort*>((*iter).second);
    } else {
        return NULL;
    }
}
References operandBinding_.
Referenced by ProGe::RV32MicroCodeGenerator::addBPorts(), RegisterCopyAdder::addConnectionRegisterCopies(), ProGe::RV32MicroCodeGenerator::addIPorts(), ProGe::RV32MicroCodeGenerator::addR1Ports(), ProGe::RV32MicroCodeGenerator::addR1RPorts(), ProGe::RV32MicroCodeGenerator::addRPorts(), ProGe::RV32MicroCodeGenerator::addSPorts(), ProGe::RV32MicroCodeGenerator::addUJPorts(), InputFUBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), bindPort(), MachineStateBuilder::bindPortsToOperands(), ControlFlowGraph::buildMBBFromBB(), MachineConnectivityCheck::busConnectedToFU(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), MachineConnectivityCheck::canBypassOpToDst(), OperationBindingCheck::check(), FUGen::checkForValidity(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkJumpAndCallOperandBindings(), FUValidator::checkOperandBindings(), FUValidator::checkOperations(), MachineValidator::checkProgramCounterPort(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), ADFCombiner::connectVectorLSU(), MachineConnectivityCheck::copyOpFUs(), ExecutionPipelineBroker::earliestFromSource(), ProGe::NetlistGenerator::findCorrespondingPort(), TTAProgram::TPEFProgramFactory::findGuard(), SimulatorFrontend::findPort(), TTAProgram::TPEFProgramFactory::findPort(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), HDBToHtml::fuArchToHtml(), ProGeTestBenchGenerator::generate(), CompiledSimCodeGenerator::generateLoadTrigger(), CompiledSimCodeGenerator::generateStoreTrigger(), CompiledSimCodeGenerator::generateTriggerCode(), MachineInfo::getBoundPort(), getOutputPort(), MachineInfo::getPortBindingsOfOperation(), BasicBlockScheduler::getTriggerOperand(), CompiledSimCodeGenerator::handleJump(), CompiledSimCodeGenerator::handleOperationWithoutDag(), ProGe::ProcessorGenerator::iMemAddressWidth(), BFOptimization::immCountPreventsScheduling(), io(), isBound(), HDB::HDBManager::isMatchingArchitecture(), TTAMachine::ExecutionPipeline::isOperandBound(), BF2Scheduler::isTrigger(), ExecutionPipelineBroker::latestFromSource(), loadState(), numberOfInputs(), numberOfOutputs(), OperationDialog::onBindOperand(), OperationDialog::onDeleteOperand(), operandBindingsString(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPort(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::operandTooLate(), BFShareOperands::operator()(), HDB::FUArchitecture::operator==(), SmartHWOperation::otherMandatoryInputsBound(), FUGen::parseOperations(), ExecutionPipelineResource::poConflictsWithInputPort(), SmartHWOperation::port(), BF2Scheduler::preAllocateFunctionUnits(), BF2Scheduler::preAllocateFunctionUnits(), MachineConnectivityCheck::raConnected(), BF2Scheduler::releasePortForOp(), HDB::HDBManager::resolveArchitecturePort(), TTAMachine::ResourceVector::ResourceVector(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultPort(), ExecutionPipelineResource::resultReadyCycle(), MachineResourceManager::rFPortOrFUIndexReference(), BFOptimization::RFReadPortCountPreventsScheduling(), FUGen::scheduleOperations(), ExecutionPipelineResource::setOperandsUsed(), ExecutionPipelineResource::setResultWriten(), ExecutionPipelineResource::testTriggerResult(), ExecutionPipelineResource::triggerAllowedAtCycle(), unbindPort(), ExecutionPipelineResource::unsetOperandsUsed(), ExecutionPipelineResource::unsetResultWriten(), OperationDialog::updateOperandList(), DefaultDecoderGenerator::writeControlRegisterMappings(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
saveState()
ObjectState * TTAMachine::HWOperation::saveState () const virtual
Saves the contents to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Definition at line 424 of file HWOperation.cc.
{
    ObjectState* operation = new ObjectState(OSNAME_OPERATION);
    operation->setAttribute(OSKEY_NAME, name());
    // save operand binding map
    for (OperandBindingMap::const_iterator iter = operandBinding_.begin();
         iter != operandBinding_.end(); iter++) {
        pair<int, const FUPort*> binding = *iter;
        ObjectState* bindingState = new ObjectState(OSNAME_OPERAND_BINDING);
        operation->addChild(bindingState);
        bindingState->setAttribute(OSKEY_OPERAND, binding.first);
        bindingState->setAttribute(OSKEY_PORT, binding.second->name());
    }
    // save pipeline
    operation->addChild(pipeline_->saveState());
    return operation;
}
References ObjectState::addChild(), name(), operandBinding_, OSKEY_NAME, OSKEY_OPERAND, OSKEY_PORT, OSNAME_OPERAND_BINDING, OSNAME_OPERATION, pipeline_, TTAMachine::ExecutionPipeline::saveState(), and ObjectState::setAttribute().
Referenced by TTAMachine::FunctionUnit::saveState().
setName()
void TTAMachine::HWOperation::setName (const std::string & name) virtual
Sets the name of the operation.
Parameters
name The new name.
Exceptions
ComponentAlreadyExists If another operation exists by the same name in the function unit.
InvalidName If the given name is not valid.
Reimplemented in SmartHWOperation.
Definition at line 155 of file HWOperation.cc.
{
    string lowerName = StringTools::stringToLower(name);
    if (lowerName == this->name()) {
        return;
    }
    const string procName = "HWOperation::setName";
    if (parentUnit()->hasOperation(lowerName)) {
        MOMTextGenerator textGenerator;
        format text = textGenerator.text(
            MOMTextGenerator::TXT_OPERATION_EXISTS_BY_SAME_NAME);
        text % name % parentUnit()->name();
        throw ComponentAlreadyExists(
            __FILE__, __LINE__, procName, text.str());
    }
    if (!MachineTester::isValidComponentName(lowerName)) {
        MOMTextGenerator textGen;
        format errorMsg = textGen.text(MOMTextGenerator::TXT_INVALID_NAME);
        errorMsg % lowerName;
        throw InvalidName(__FILE__, __LINE__, procName, errorMsg.str());
    }
    name_ = lowerName;
}
References MachineTester::isValidComponentName(), name(), TTAMachine::Component::name(), name_, parentUnit(), StringTools::stringToLower(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_INVALID_NAME, and MOMTextGenerator::TXT_OPERATION_EXISTS_BY_SAME_NAME.
Referenced by HWOperation(), loadState(), and OperationDialog::onOK().
slack()
int TTAMachine::HWOperation::slack (int input) const
Returns the slack of the given input.
The slack tells how many cycles AFTER the trigger, opcode-setting move is scheduled, can the operand be scheduled (and still affect correctly the result of the operation).
Parameters
input The number of the input.
Returns
The slack of the given input.
Exceptions
IllegalParameters If the given input is not read in the pipeline.
Definition at line 248 of file HWOperation.cc.
{
    return pipeline_->slack(input);
}
References pipeline_, and TTAMachine::ExecutionPipeline::slack().
Referenced by ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandTooLate(), ExecutionPipelineResource::setOperandsUsed(), ExecutionPipelineResource::triggerTooEarly(), and ExecutionPipelineResource::unsetOperandsUsed().
unbindPort()
void TTAMachine::HWOperation::unbindPort (const FUPort & port) virtual
Unbinds the operand bound to the given port.
Parameters
port The port.
Reimplemented in SmartHWOperation.
Definition at line 296 of file HWOperation.cc.
{
    MapTools::removeItemsByValue(operandBinding_, &port);
    port.updateBindingString();
}
References operandBinding_, port(), MapTools::removeItemsByValue(), and TTAMachine::FUPort::updateBindingString().
Referenced by TTAMachine::FUPort::cleanupOperandBindings(), OperationDialog::onBindOperand(), and OperationDialog::onDeleteOperand().
Member Data Documentation
name_
std::string TTAMachine::HWOperation::name_ private
Name of the operation.
Definition at line 97 of file HWOperation.hh.
Referenced by HWOperation(), name(), and setName().
operandBinding_
OperandBindingMap TTAMachine::HWOperation::operandBinding_ private
Maps operands of operation to particular ports of the parent unit.
Definition at line 103 of file HWOperation.hh.
Referenced by bindPort(), io(), isBound(), isBound(), loadState(), operandCount(), port(), saveState(), and unbindPort().
OSKEY_NAME
const string TTAMachine::HWOperation::OSKEY_NAME = "name" static
ObjectState attribute key for name of the operation.
Definition at line 84 of file HWOperation.hh.
Referenced by HWOperation(), loadState(), ADFSerializer::machineOperation(), ADFSerializer::mdfOperation(), and saveState().
OSKEY_OPERAND
const string TTAMachine::HWOperation::OSKEY_OPERAND = "operand" static
ObjectState attribute key for operand index.
Definition at line 88 of file HWOperation.hh.
Referenced by loadState(), ADFSerializer::machineOperation(), ADFSerializer::mdfOperation(), and saveState().
OSKEY_PORT
const string TTAMachine::HWOperation::OSKEY_PORT = "port" static
ObjectState attribute key for port name.
Definition at line 90 of file HWOperation.hh.
Referenced by loadState(), ADFSerializer::machineOperation(), ADFSerializer::mdfOperation(), and saveState().
OSNAME_OPERAND_BINDING
const string TTAMachine::HWOperation::OSNAME_OPERAND_BINDING = "binding" static
ObjectState name for an operand binding.
Definition at line 86 of file HWOperation.hh.
Referenced by loadState(), ADFSerializer::machineOperation(), ADFSerializer::mdfOperation(), and saveState().
OSNAME_OPERATION
const string TTAMachine::HWOperation::OSNAME_OPERATION = "operation" static
ObjectState name for HWOperation.
Definition at line 82 of file HWOperation.hh.
Referenced by ADFSerializer::controlUnitToMDF(), ADFSerializer::functionUnitToMDF(), loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), ADFSerializer::machineOperation(), and saveState().
parent_
FunctionUnit* TTAMachine::HWOperation::parent_ private
The parent unit.
Definition at line 101 of file HWOperation.hh.
Referenced by HWOperation(), HWOperation(), parentUnit(), and ~HWOperation().
pipeline_
ExecutionPipeline* TTAMachine::HWOperation::pipeline_ private
Pipeline of the operation.
Definition at line 99 of file HWOperation.hh.
Referenced by HWOperation(), HWOperation(), latency(), latency(), loadState(), pipeline(), saveState(), slack(), and ~HWOperation().
The documentation for this class was generated from the following files:
HWOperation.hh
HWOperation.cc