OpenASIP: ProximFUEditPolicy Class Reference
ProximFUEditPolicy Class Reference
#include <ProximFUEditPolicy.hh>
Public Member Functions
ProximFUEditPolicy ()
virtual ~ProximFUEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Edit policy for proxim machine window function units.
Definition at line 41 of file ProximFUEditPolicy.hh.
Constructor & Destructor Documentation
ProximFUEditPolicy()
ProximFUEditPolicy::ProximFUEditPolicy ()
The Constructor.
Definition at line 47 of file ProximFUEditPolicy.cc.
                                       :
    EditPolicy() {
}
~ProximFUEditPolicy()
ProximFUEditPolicy::~ProximFUEditPolicy () virtual
The Destructor.
Definition at line 55 of file ProximFUEditPolicy.cc.
{
}
Member Function Documentation
canHandle()
bool ProximFUEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy can handle request of the given type.
Parameters
Request to be handled.
Returns
True, if the editpolicy can handle give request type.
Implements EditPolicy.
Definition at line 65 of file ProximFUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
        type == Request::STATUS_REQUEST ||
        type == Request::DETAILS_REQUEST) {
        return true;
    }
    return false;
}
References Request::DETAILS_REQUEST, Request::MODIFY_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProximFUEditPolicy::getCommand (Request * request) virtual
Returns command correspoding to the request type.
Parameters
request Request to handle.
Returns
NULL, if the request can't be handled.
Implements EditPolicy.
Definition at line 86 of file ProximFUEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        return new ProximShowPortsCmd(host_);
    } else if (type == Request::STATUS_REQUEST) {
        const FunctionUnit* fu = dynamic_cast<const FunctionUnit*>(
            host_->model());
        assert(fu != NULL);
        std::string status = ProximConstants::MACH_WIN_FU_LABEL + fu->name();
        return new ProximComponentStatusCmd(status);
    } else if (type == Request::DETAILS_REQUEST) {
        const FunctionUnit* fu = dynamic_cast<const FunctionUnit*>(
            host_->model());
        assert(fu != NULL);
        return new ProximFUDetailsCmd(*fu);
    }
    return NULL;
}
References assert, Request::DETAILS_REQUEST, EditPolicy::host_, ProximConstants::MACH_WIN_FU_LABEL, EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), Request::STATUS_REQUEST, and Request::type().
The documentation for this class was generated from the following files:
ProximFUEditPolicy.hh
ProximFUEditPolicy.cc