OpenASIP: TPEF::TPEFLineNumSectionReader Class Reference
TPEF::TPEFLineNumSectionReader Class Reference
#include <TPEFLineNumSectionReader.hh>
Protected Member Functions
TPEFLineNumSectionReader ()
virtual ~TPEFLineNumSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFLineNumSectionReader (const TPEFLineNumSectionReader &)
Copying not allowed.
TPEFLineNumSectionReader & operator= (TPEFLineNumSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFLineNumSectionReader proto_
Prototype instance of TPEFLineNumSectionReader to be registered to SectionReader.
static SectionId codeSectionId_ = 0
Identification code of text section which is referenced from currently read section.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads line number section from TPEF binary file.
Definition at line 47 of file TPEFLineNumSectionReader.hh.
Constructor & Destructor Documentation
TPEFLineNumSectionReader() [1/2]
TPEF::TPEFLineNumSectionReader::TPEFLineNumSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 59 of file TPEFLineNumSectionReader.cc.
                                                   : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFLineNumSectionReader()
TPEF::TPEFLineNumSectionReader::~TPEFLineNumSectionReader () protected virtual
Destructor.
Definition at line 66 of file TPEFLineNumSectionReader.cc.
{
}
TPEFLineNumSectionReader() [2/2]
TPEF::TPEFLineNumSectionReader::TPEFLineNumSectionReader (const TPEFLineNumSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFLineNumSectionReader & TPEF::TPEFLineNumSectionReader::operator= (TPEFLineNumSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFLineNumSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read value were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 92 of file TPEFLineNumSectionReader.cc.
{
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    LineNumSection* lineNumSection = dynamic_cast<LineNumSection*>(section);
    assert(lineNumSection != NULL);
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // mark start of first element
        SectionOffset elementStart = header().bodyOffset;
        LineNumProcedure *procedure = NULL;
        while (elementStart + header().elementSize <=
               header().bodyOffset + header().bodyLength) {
            Word elementOffset = stream.readWord();
            HalfWord lineNum = stream.readHalfWord();
            // Let's create new procedure for our line numbers if needed.
            if (lineNum == 0) {
                procedure = new LineNumProcedure();
                SectionIndexKey indexKey(header().linkId, elementOffset);
                if (elementOffset != 0) {
                    procedure->setProcedureSymbol(
                        CREATE_SAFEPOINTER(indexKey));
                }
                section->addElement(procedure);
            } else if (procedure != NULL) {
                LineNumElement *elem = new LineNumElement();
                // where is section id off data section stored
                SectionOffsetKey instrKey(codeSectionId_, elementOffset);
                elem->setInstruction(CREATE_SAFEPOINTER(instrKey));
                elem->setLineNumber(lineNum);
                // add line to last created procedure
                procedure->addLine(elem);
            } else {
                bool sectionShouldNotHaveLineNumbersBeforeProcedure = false;
                assert(sectionShouldNotHaveLineNumbersBeforeProcedure);
            }
            elementStart += header().elementSize;
            stream.setReadPosition(elementStart);
        }
    }
}
References TPEF::Section::addElement(), TPEF::LineNumProcedure::addLine(), assert, TPEF::TPEFSectionReader::Header::bodyOffset, codeSectionId_, TPEF::TPEFSectionReader::Header::elementSize, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::LineNumElement::setInstruction(), TPEF::LineNumElement::setLineNumber(), TPEF::LineNumProcedure::setProcedureSymbol(), and TPEF::BinaryStream::setReadPosition().
readInfo()
void TPEF::TPEFLineNumSectionReader::readInfo (BinaryStream & stream, Section * sect) const protected virtual
Reads info field of section header, which contains the identification code of the code section to which the line number section applies.
Read position of stream will be moved 4 bytes forward.
Parameters
stream Stream where from info word is read.
sect Section whose info field is interpreted.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 160 of file TPEFLineNumSectionReader.cc.
{
    // identification code of referenced section is in first 2 bytes of info
    // field
    codeSectionId_ = stream.readHalfWord();
    if (codeSectionId_ != 0) {
        SectionKey sKey(codeSectionId_);
        dynamic_cast<LineNumSection*>(sect)->setCodeSection(
            CREATE_SAFEPOINTER(sKey));
    } else {
        dynamic_cast<LineNumSection*>(sect)->setCodeSection(
            &SafePointer::null);
    }
    // skip rest 2 of 4 bytes
    stream.readHalfWord();
}
References codeSectionId_, TPEF::ReferenceManager::SafePointer::null, and TPEF::BinaryStream::readHalfWord().
type()
Section::SectionType TPEF::TPEFLineNumSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 75 of file TPEFLineNumSectionReader.cc.
{
    return Section::ST_LINENO;
}
References TPEF::Section::ST_LINENO.
Member Data Documentation
codeSectionId_
SectionId TPEF::TPEFLineNumSectionReader::codeSectionId_ = 0 static private
Identification code of text section which is referenced from currently read section.
Definition at line 65 of file TPEFLineNumSectionReader.hh.
Referenced by readData(), and readInfo().
proto_
TPEFLineNumSectionReader TPEF::TPEFLineNumSectionReader::proto_ static private
Prototype instance of TPEFLineNumSectionReader to be registered to SectionReader.
Definition at line 61 of file TPEFLineNumSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFLineNumSectionReader.hh
TPEFLineNumSectionReader.cc