OpenASIP: BEMViewerCmdLineOptions Class Reference
BEMViewerCmdLineOptions Class Reference
#include <BEMViewerCmdLineOptions.hh>
Public Member Functions
BEMViewerCmdLineOptions ()
virtual ~BEMViewerCmdLineOptions ()
std::string bemFile () const
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line options for viewbem.
Definition at line 41 of file BEMViewerCmdLineOptions.hh.
Constructor & Destructor Documentation
BEMViewerCmdLineOptions()
BEMViewerCmdLineOptions::BEMViewerCmdLineOptions ()
The constructor.
Definition at line 39 of file BEMViewerCmdLineOptions.cc.
                                                 :
    CmdLineOptions("BEM viewer", Application::TCEVersionString()) {
}
~BEMViewerCmdLineOptions()
BEMViewerCmdLineOptions::~BEMViewerCmdLineOptions () virtual
The destructor.
Definition at line 47 of file BEMViewerCmdLineOptions.cc.
{
}
Member Function Documentation
bemFile()
std::string BEMViewerCmdLineOptions::bemFile () const
Returns the given BEM file.
Returns
The BEM file.
Definition at line 57 of file BEMViewerCmdLineOptions.cc.
{
    if (numberOfArguments() < 1) {
        return "";
    } else {
        return argument(1);
    }
}
References CmdLineParser::argument(), and CmdLineParser::numberOfArguments().
printHelp()
void BEMViewerCmdLineOptions::printHelp () const virtual
Prints the help.
Reimplemented from CmdLineOptions.
Definition at line 80 of file BEMViewerCmdLineOptions.cc.
{
    printVersion();
    std::cout << "Usage: viewbem <bemfile>" << std::endl;
}
References printVersion().
printVersion()
void BEMViewerCmdLineOptions::printVersion () const virtual
Prints the version of the application.
Implements CmdLineOptions.
Definition at line 70 of file BEMViewerCmdLineOptions.cc.
{
    std::cout << "viewbem - BEM Viewer "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
The documentation for this class was generated from the following files:
BEMViewerCmdLineOptions.hh
BEMViewerCmdLineOptions.cc