OpenASIP: ContentsFigure Class Reference
ContentsFigure Class Reference
#include <ContentsFigure.hh>
Public Member Functions
ContentsFigure ()
virtual ~ContentsFigure ()
virtual void addChild (Figure *child)
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
virtual void draw (wxDC *dc)
Protected Member Functions inherited from Figure
virtual void drawSelf (wxDC *dc)
void drawChildren (wxDC *dc)
Private Member Functions
ContentsFigure & operator= (ContentsFigure &old)
Assignment not allowed.
ContentsFigure (ContentsFigure &old)
Copying not allowed.
Private Attributes
UnitContainerFigure * units_
Contains all the units.
BusContainerFigure * buses_
Contains all the buses.
SocketContainerFigure * sockets_
Contains all the sockets.
Additional Inherited Members
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a container EditPart for the whole machine.
Definition at line 49 of file ContentsFigure.hh.
Constructor & Destructor Documentation
ContentsFigure() [1/2]
ContentsFigure::ContentsFigure ()
The Constructor.
Definition at line 48 of file ContentsFigure.cc.
                              :
    Figure(), units_(NULL), buses_(NULL), sockets_(NULL) {
}
~ContentsFigure()
ContentsFigure::~ContentsFigure () virtual
The Destructor.
Definition at line 55 of file ContentsFigure.cc.
{
}
ContentsFigure() [2/2]
ContentsFigure::ContentsFigure (ContentsFigure & old) private
Copying not allowed.
Member Function Documentation
addChild()
void ContentsFigure::addChild (Figure * figure) virtual
Overloaded implementation allows only addition of certain types of Figures for layout purposes.
These are UnitContainerFigure, BusContainerFigure and SocketContainerFigure.
Parameters
figure Child figure to add.
Reimplemented from Figure.
Definition at line 68 of file ContentsFigure.cc.
{
    Figure::addChild(figure);
    UnitContainerFigure* units = dynamic_cast<UnitContainerFigure*>(figure);
    if (units != NULL) {
    units_ = units;
    return;
    }
    BusContainerFigure* buses = dynamic_cast<BusContainerFigure*>(figure);
    if (buses != NULL) {
    buses_ = buses;
    return;
    }
    SocketContainerFigure* sockets =
    dynamic_cast<SocketContainerFigure*>(figure);
    if (sockets != NULL) {
    sockets_ = sockets;
    return;
    }
    // added a non supported type of a child figure
    assert(false);
}
References Figure::addChild(), assert, buses_, sockets_, and units_.
draw()
void ContentsFigure::draw (wxDC * dc) protected virtual
Draws figure on a given device context.
Figure::draw() is overridden to enseure that the containers are drawn in the correct order. (sockets over busses)
Parameters
dc Device context to draw figures on.
Reimplemented from Figure.
Definition at line 104 of file ContentsFigure.cc.
{
    if (units_ != NULL) {
        units_->draw(dc);
    }
    if (buses_ != NULL) {
        buses_->draw(dc);
    }
    if (sockets_ != NULL) {
        sockets_->draw(dc);
    }
}
References buses_, Figure::draw(), sockets_, and units_.
layoutChildren()
void ContentsFigure::layoutChildren (wxDC * dc) protected virtual
Lays out the subcontainers.
Parameters
dc Device context.
Reimplemented from Figure.
Definition at line 122 of file ContentsFigure.cc.
{
    int containerX =
    location_.x + MachineCanvasLayoutConstraints::VIEW_LEFT_MARGIN;
    int containerY =
    location_.y + MachineCanvasLayoutConstraints::VIEW_MARGIN;
    // first layout units if there are any
    if (units_ != NULL) {
    units_->setLocation(wxPoint(containerX, containerY));
    units_->layout(dc);
    containerY += units_->bounds().GetHeight() +
        MachineCanvasLayoutConstraints::CONNECTIONS_SPACE;
    }
    // then layout buses
    if (buses_ != NULL) {
    buses_->setLocation(
        wxPoint(containerX,
            containerY + MachineCanvasLayoutConstraints::BUS_SPACE));
    if (units_ != NULL && units_->bounds().GetWidth() >
        MachineCanvasLayoutConstraints::BUS_MIN_WIDTH) {
        buses_->setWidth(units_->bounds().GetWidth());
    } else {
        buses_->setWidth(MachineCanvasLayoutConstraints::BUS_MIN_WIDTH);
    }
    buses_->layout(dc);
    }
    // layout sockets
    if (sockets_ != NULL) {
    sockets_->setLocation(wxPoint(containerX, containerY));
    if (buses_ != NULL) {
        sockets_->setHeight(buses_->bounds().GetHeight() +
                MachineCanvasLayoutConstraints::BUS_SPACE);
        sockets_->setWidth(buses_->bounds().GetWidth() +
                MachineCanvasLayoutConstraints::BUS_SPACE);
    } else if (units_ != NULL) {
        sockets_->setWidth(units_->bounds().GetWidth() +
                   MachineCanvasLayoutConstraints::BUS_SPACE);
    }
    sockets_->layout(dc);
    if (buses_ != NULL) {
        buses_->setWidth(sockets_->bounds().GetWidth());
        buses_->layout(dc);
    }
    }
}
References Figure::bounds(), MachineCanvasLayoutConstraints::BUS_MIN_WIDTH, MachineCanvasLayoutConstraints::BUS_SPACE, buses_, MachineCanvasLayoutConstraints::CONNECTIONS_SPACE, Figure::layout(), Figure::location_, Figure::setHeight(), Figure::setLocation(), Figure::setWidth(), sockets_, units_, MachineCanvasLayoutConstraints::VIEW_LEFT_MARGIN, and MachineCanvasLayoutConstraints::VIEW_MARGIN.
layoutSelf()
void ContentsFigure::layoutSelf (wxDC *) protected virtual
Calculates and sets the size of the container.
Depends on the sizes of the child containers: height will be equal to the size of the unit container plus the height of the socket or the bus container, whichever is higher. Width will be equal to the width of the unit container, or the socket container if it is wider.
Reimplemented from Figure.
Definition at line 191 of file ContentsFigure.cc.
{
    int width = 0;
    int height = 0;
    if (units_ != NULL) {
    width = units_->bounds().GetWidth();
    height = units_->bounds().GetHeight();
    }
    int higher = 0;
    if (sockets_ != NULL) {
    higher = sockets_->bounds().GetHeight();
    if (sockets_->bounds().GetWidth() > width) {
        width = sockets_->bounds().GetWidth();
    }
    }
    if (buses_ != NULL) {
    if (buses_->bounds().GetHeight() > higher) {
        higher = buses_->bounds().GetHeight();
    }
    if (buses_->bounds().GetWidth() > width) {
        width = buses_->bounds().GetWidth();
    }
    }
    height += higher + MachineCanvasLayoutConstraints::VIEW_MARGIN * 2;
    width += MachineCanvasLayoutConstraints::VIEW_MARGIN * 2;
    if (units_ != NULL && (buses_ != NULL || sockets_ != NULL)) {
    height += MachineCanvasLayoutConstraints::CONNECTIONS_SPACE;
    }
    size_.SetWidth(width);
    size_.SetHeight(height);
}
References Figure::bounds(), buses_, MachineCanvasLayoutConstraints::CONNECTIONS_SPACE, Figure::size_, sockets_, units_, and MachineCanvasLayoutConstraints::VIEW_MARGIN.
operator=()
ContentsFigure & ContentsFigure::operator= (ContentsFigure & old) private
Assignment not allowed.
Member Data Documentation
buses_
BusContainerFigure* ContentsFigure::buses_ private
Contains all the buses.
Definition at line 69 of file ContentsFigure.hh.
Referenced by addChild(), draw(), layoutChildren(), and layoutSelf().
sockets_
SocketContainerFigure* ContentsFigure::sockets_ private
Contains all the sockets.
Definition at line 71 of file ContentsFigure.hh.
Referenced by addChild(), draw(), layoutChildren(), and layoutSelf().
units_
UnitContainerFigure* ContentsFigure::units_ private
Contains all the units.
Definition at line 67 of file ContentsFigure.hh.
Referenced by addChild(), draw(), layoutChildren(), and layoutSelf().
The documentation for this class was generated from the following files:
ContentsFigure.hh
ContentsFigure.cc