OpenASIP: WatchPropertiesDialog Class Reference
WatchPropertiesDialog Class Reference
#include <WatchPropertiesDialog.hh>
Public Member Functions
WatchPropertiesDialog (wxWindow *parent, wxWindowID id, StopPointManager &manager, int handle)
~WatchPropertiesDialog ()
Private Types
enum {
ID_LABEL_WATCH = 10000 , ID_LABEL_EXPRESSION , ID_LABEL_CONDITION , ID_LABEL_IGNORE_COUNT ,
ID_WATCH_HANDLE , ID_EXPRESSION , ID_CONDITION , ID_IGNORE_COUNT ,
ID_LINE
}
Widget IDs.
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool call_sizer)
virtual bool TransferDataToWindow ()
void onOK (wxCommandEvent &event)
Private Attributes
StopPointManager & manager_
Stop point manager of the simulator.
int handle_
Handle of the watch to modify.
wxTextCtrl * expressionCtrl_
Text widget for the watch expression script.
wxTextCtrl * conditionCtrl_
Text widget fot the watch condition script.
wxSpinCtrl * ignoreCtrl_
Spin button widget for the watch ignore count.
Detailed Description
Dialog for modifying watchpoint properties.
Definition at line 43 of file WatchPropertiesDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_LABEL_WATCH
ID_LABEL_EXPRESSION
ID_LABEL_CONDITION
ID_LABEL_IGNORE_COUNT
ID_WATCH_HANDLE
ID_EXPRESSION
ID_CONDITION
ID_IGNORE_COUNT
ID_LINE
Definition at line 55 of file WatchPropertiesDialog.hh.
         {
        ID_LABEL_WATCH = 10000,
        ID_LABEL_EXPRESSION,
        ID_LABEL_CONDITION,
        ID_LABEL_IGNORE_COUNT,
        ID_WATCH_HANDLE,
        ID_EXPRESSION,
        ID_CONDITION,
        ID_IGNORE_COUNT,
        ID_LINE
    };
Constructor & Destructor Documentation
WatchPropertiesDialog()
WatchPropertiesDialog::WatchPropertiesDialog (wxWindow * parent, wxWindowID id, StopPointManager & manager, int handle)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog.
manager Stoppoint manager of the simulator.
handle Watch handle.
Definition at line 58 of file WatchPropertiesDialog.cc.
                                                                            :
  wxDialog(parent, id, _T("Watch point properties"), wxDefaultPosition),
    manager_(manager), handle_(handle){
    createContents(this, true, true);
    expressionCtrl_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_EXPRESSION));
    conditionCtrl_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_CONDITION));
    ignoreCtrl_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_IGNORE_COUNT));
}
~WatchPropertiesDialog()
WatchPropertiesDialog::~WatchPropertiesDialog ()
The Destructor.
Definition at line 74 of file WatchPropertiesDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * WatchPropertiesDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Code generated by wxDesgigner. Do not modify manually.
Parameters
parent Parent window of the widgets.
call_fit If true, the dialog is resized to fit the widgets.
set_sizer If true, the created widgets are set as the parent window contents.
Definition at line 156 of file WatchPropertiesDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_WATCH, wxT("Watch:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxStaticText *item3 = new wxStaticText( parent, ID_WATCH_HANDLE, wxT("??????"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_EXPRESSION, wxT("Expression:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_EXPRESSION, wxT(""), wxDefaultPosition, wxSize(400,-1), wxTE_READONLY );
    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_CONDITION, wxT("Condition:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_CONDITION, wxT(""), wxDefaultPosition, wxSize(400,-1), 0 );
    item1->Add( item7, 0, wxGROW|wxALL, 5 );
    wxStaticText *item8 = new wxStaticText( parent, ID_LABEL_IGNORE_COUNT, wxT("Ignore count:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item8, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item9 = new wxSpinCtrl( parent, ID_IGNORE_COUNT, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 0 );
    item1->Add( item9, 0, wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item10 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item10, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item12 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALL, 5 );
    wxButton *item13 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item13, 0, wxALL, 5 );
    item0->Add( item11, 0, wxALIGN_CENTER, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_CONDITION, ID_EXPRESSION, ID_IGNORE_COUNT, ID_LABEL_CONDITION, ID_LABEL_EXPRESSION, ID_LABEL_IGNORE_COUNT, ID_LABEL_WATCH, ID_LINE, and ID_WATCH_HANDLE.
onOK()
void WatchPropertiesDialog::onOK (wxCommandEvent & event) private
Event handler for the OK-button.
Updates the watch properties accordign to the values in the dialog widgets.
Definition at line 113 of file WatchPropertiesDialog.cc.
{
    wxTextCtrl* conditionCtrl =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_CONDITION));
    std::string condition = WxConversion::toString(
        conditionCtrl->GetValue().Trim(true).Trim(false));
    // Test condition script.
    if (condition != "" && !ProximToolbox::testCondition(this, condition)) {
        // Invalid condition script.
        return;
    }
    // Set watch condition script.
    std::string conditionCommand = ProximConstants::SCL_SET_CONDITION +
        " " + Conversion::toString(handle_);
    ProximLineReader& lineReader = ProximToolbox::lineReader();
    lineReader.input(conditionCommand);
    lineReader.input(condition);
    // Set watch ignore count.
    unsigned ignoreCount = ignoreCtrl_->GetValue();
    std::string ignoreCommand = ProximConstants::SCL_SET_IGNORE_COUNT +
        " " + Conversion::toString(handle_) +
        " " + Conversion::toString(ignoreCount);
    lineReader.input(ignoreCommand);
    // Close dialog.
    EndModal(wxID_OK);
}
References handle_, ID_CONDITION, ignoreCtrl_, ProximLineReader::input(), ProximToolbox::lineReader(), ProximConstants::SCL_SET_CONDITION, ProximConstants::SCL_SET_IGNORE_COUNT, ProximToolbox::testCondition(), Conversion::toString(), and WxConversion::toString().
TransferDataToWindow()
bool WatchPropertiesDialog::TransferDataToWindow () private virtual
Initializes watch properties in the dialog widgets.
Returns
True, if the watch properties were succesfully transfered to the dialog widgets.
Definition at line 85 of file WatchPropertiesDialog.cc.
{
    const StopPoint& stoppoint = manager_.stopPointWithHandleConst(handle_);
    const Watch& watch = dynamic_cast<const Watch&>(stoppoint);
    dynamic_cast<wxStaticText*>(FindWindow(ID_WATCH_HANDLE))->SetLabel(
        WxConversion::toWxString(handle_));
    expressionCtrl_->SetValue(
        WxConversion::toWxString(watch.expression().script()[0]));
    if (watch.isConditional()) {
        conditionCtrl_->SetValue(
            WxConversion::toWxString(watch.condition().script()[0]));
    }
    ignoreCtrl_->SetValue(watch.ignoreCount());
    return wxDialog::TransferDataToWindow();
}
References StopPoint::condition(), conditionCtrl_, Watch::expression(), expressionCtrl_, handle_, ID_WATCH_HANDLE, StopPoint::ignoreCount(), ignoreCtrl_, StopPoint::isConditional(), manager_, Script::script(), StopPointManager::stopPointWithHandleConst(), and WxConversion::toWxString().
Member Data Documentation
conditionCtrl_
wxTextCtrl* WatchPropertiesDialog::conditionCtrl_ private
Text widget fot the watch condition script.
Definition at line 76 of file WatchPropertiesDialog.hh.
Referenced by TransferDataToWindow().
expressionCtrl_
wxTextCtrl* WatchPropertiesDialog::expressionCtrl_ private
Text widget for the watch expression script.
Definition at line 74 of file WatchPropertiesDialog.hh.
Referenced by TransferDataToWindow().
handle_
int WatchPropertiesDialog::handle_ private
Handle of the watch to modify.
Definition at line 71 of file WatchPropertiesDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
ignoreCtrl_
wxSpinCtrl* WatchPropertiesDialog::ignoreCtrl_ private
Spin button widget for the watch ignore count.
Definition at line 78 of file WatchPropertiesDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
manager_
StopPointManager& WatchPropertiesDialog::manager_ private
Stop point manager of the simulator.
Definition at line 69 of file WatchPropertiesDialog.hh.
Referenced by TransferDataToWindow().
The documentation for this class was generated from the following files:
WatchPropertiesDialog.hh
WatchPropertiesDialog.cc