OpenASIP: StrictMatchFUEstimator Class Reference
StrictMatchFUEstimator Class Reference
Public Member Functions
StrictMatchFUEstimator (const std::string &name)
virtual ~StrictMatchFUEstimator ()
DESCRIPTION ("Simple FU cost estimator plugin that estimates costs of FUs " "simply by looking up direct matches from HDB. In case there's " "no cost data available for the given FU, it's unable to estimate " "it by using linearization etc.")
bool estimateArea (const TTAMachine::FunctionUnit &, const IDF::FUImplementationLocation &implementation, AreaInGates &area, HDB::HDBManager &hdb)
bool estimatePortWriteDelay (const TTAMachine::FUPort &, const IDF::FUImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimatePortReadDelay (const TTAMachine::FUPort &, const IDF::FUImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimateMaximumComputationDelay (const TTAMachine::FunctionUnit &, const IDF::FUImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
virtual bool estimateEnergy (const TTAMachine::FunctionUnit &fu, const IDF::FUImplementationLocation &implementation, const TTAProgram::Program &, const ExecutionTrace &trace, EnergyInMilliJoules &energy, HDB::HDBManager &hdb)
Public Member Functions inherited from CostEstimator::FUCostEstimationPlugin
FUCostEstimationPlugin (const std::string &name)
virtual ~FUCostEstimationPlugin ()
Public Member Functions inherited from CostEstimator::CostEstimationPlugin
CostEstimationPlugin (const std::string &name)
virtual ~CostEstimationPlugin ()
virtual std::string name () const
virtual std::string description () const
Additional Inherited Members
Protected Attributes inherited from CostEstimator::CostEstimationPlugin
std::string name_
the name of the plugin class in the HDB; used to identify cost data
Detailed Description
Definition at line 46 of file StrictMatchFUEstimator.cc.
Constructor & Destructor Documentation
StrictMatchFUEstimator()
StrictMatchFUEstimator::StrictMatchFUEstimator (const std::string & name) inline
Definition at line 48 of file StrictMatchFUEstimator.cc.
                                                  :
        FUCostEstimationPlugin(name) {
    }
~StrictMatchFUEstimator()
virtual StrictMatchFUEstimator::~StrictMatchFUEstimator () inline virtual
Definition at line 52 of file StrictMatchFUEstimator.cc.
{
    }
Member Function Documentation
DESCRIPTION()
StrictMatchFUEstimator::DESCRIPTION ("Simple FU cost estimator plugin that estimates costs of FUs " "simply by looking up direct matches from HDB. In case there's " "no cost data available for the given FU, it 's unable to estimate " "it by using linearization etc.")
estimateArea()
bool StrictMatchFUEstimator::estimateArea (const TTAMachine::FunctionUnit & , const IDF::FUImplementationLocation & implementation, AreaInGates & area, HDB::HDBManager & hdb) inline virtual
Estimates the function unit's area by fetching cost data named 'area' from HDB.
Reimplemented from CostEstimator::FUCostEstimationPlugin.
Definition at line 67 of file StrictMatchFUEstimator.cc.
{
//#define DEBUG_AREA_ESTIMATION
        try {
            // simply fetch the area data of the FU, if any
            DataObject areaFromDB = hdb.fuCostEstimationData(
                "area", implementation.id(), name_);
            area = areaFromDB.doubleValue();
#ifdef DEBUG_AREA_ESTIMATION
            Application::logStream()
                << fu.name() << " area " << area << std::endl;
#endif
            return true;
        } catch (const KeyNotFound&) {
            // if no area data found, don't even try to estimate the area
            // somehow
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), HDB::HDBManager::fuCostEstimationData(), implementation, Application::logStream(), and CostEstimator::CostEstimationPlugin::name_.
estimateEnergy()
virtual bool StrictMatchFUEstimator::estimateEnergy (const TTAMachine::FunctionUnit & fu, const IDF::FUImplementationLocation & implementation, const TTAProgram::Program & , const ExecutionTrace & trace, EnergyInMilliJoules & energy, HDB::HDBManager & hdb) inline virtual
Estimates the energy consumed by given FU.
Estimate is done by computing the sum of all operation execution energies and FU idle energy. Operation execution energies are stored with entries named 'operation_execution_energy operation_name'. The idle energy is in entry named 'fu_idle_energy'.
Reimplemented from CostEstimator::FUCostEstimationPlugin.
Definition at line 208 of file StrictMatchFUEstimator.cc.
{
//#define DEBUG_ENERGY_ESTIMATION
        energy = 0.0;
        ClockCycleCount cyclesWithFUAccess = 0;
#ifdef DEBUG_ENERGY_ESTIMATION
        Application::logStream()
            << "## function unit " << fu.name() << ": " << std::endl;
#endif
        try {
            ExecutionTrace::FUOperationTriggerCountList* operationTriggers =
                trace.functionUnitOperationTriggerCounts(fu.name());
            for (ExecutionTrace::FUOperationTriggerCountList::
                     const_iterator i = operationTriggers->begin();
                 i != operationTriggers->end(); ++i) {
                const ExecutionTrace::FUOperationTriggerCount& triggerCount =
                    *i;
                const ExecutionTrace::OperationID operation =
                    StringTools::stringToLower(triggerCount.get<0>());
                const ExecutionTrace::OperationTriggerCount count =
                    triggerCount.get<1>();
                const std::string dataName =
                    std::string("operation_execution_energy ") +
                    operation;
                try {
                    DataObject energyFromDB = hdb.fuCostEstimationData(
                        dataName, implementation.id(), name_);
                    EnergyInMilliJoules energyOfAccess =
                        energyFromDB.doubleValue()*count;
#ifdef DEBUG_ENERGY_ESTIMATION
                    Application::logStream()
                        << "## " << operation << " = "
                        << energyFromDB.doubleValue() << " times "
                        << count << " = " << energyOfAccess << std::endl;
#endif
                    energy += energyOfAccess;
                    cyclesWithFUAccess += count;
                } catch (const KeyNotFound&) {
                    // if no data found, don't even try to estimate the energy
                    delete operationTriggers;
                    operationTriggers = NULL;
                    Application::logStream()
                        << "Cost estimation data '" << dataName
                        << "' not found in HDB." << std::endl;
                    return false;
                } catch (const Exception& e) {
                    delete operationTriggers;
                    operationTriggers = NULL;
                    debugLog(e.errorMessage());
                    return false;
                }
            }
            delete operationTriggers;
            operationTriggers = NULL;
        }  catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        // add the cost of FU idling
        const ClockCycleCount idleCycles =
            trace.simulatedCycleCount() - cyclesWithFUAccess;
        const std::string dataName = std::string("fu_idle_energy");
        try {
            DataObject energyFromDB = hdb.fuCostEstimationData(
                dataName, implementation.id(), name_);
            EnergyInMilliJoules idleEnergy =
                energyFromDB.doubleValue()*idleCycles;
#ifdef DEBUG_ENERGY_ESTIMATION
            Application::logStream()
                << "## idle energy " << energyFromDB.doubleValue() << " times "
                << idleCycles << " = " << idleEnergy << std::endl;
#endif
            energy += idleEnergy;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the energy
            Application::logStream()
                        << "Cost estimation data '" << dataName
                        << "' for FU with id " << implementation.id()
                        << " not found in HDB." << std::endl;
            return false;
        } catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        return true;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), HDB::HDBManager::fuCostEstimationData(), ExecutionTrace::functionUnitOperationTriggerCounts(), implementation, Application::logStream(), TTAMachine::Component::name(), CostEstimator::CostEstimationPlugin::name_, ExecutionTrace::simulatedCycleCount(), StringTools::stringToLower(), and trace.
estimateMaximumComputationDelay()
bool StrictMatchFUEstimator::estimateMaximumComputationDelay (const TTAMachine::FunctionUnit & , const IDF::FUImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the function unit maximum computation delay by fetching cost data named 'computation_delay' from HDB.
Reimplemented from CostEstimator::FUCostEstimationPlugin.
Definition at line 172 of file StrictMatchFUEstimator.cc.
{
        try {
            // simply fetch the delay data of the FU port, if any
            DataObject delayFromDB = hdb.fuCostEstimationData(
                "computation_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No computation_delay cost data found for FU "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), HDB::HDBManager::fuCostEstimationData(), implementation, Application::logStream(), and CostEstimator::CostEstimationPlugin::name_.
estimatePortReadDelay()
bool StrictMatchFUEstimator::estimatePortReadDelay (const TTAMachine::FUPort & , const IDF::FUImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the function unit port read delay by fetching cost data named 'output_delay' from HDB.
Assumes that all ports have the same output delay, that is, there is only one 'output_delay' entry for a FU in HDB.
Reimplemented from CostEstimator::FUCostEstimationPlugin.
Definition at line 140 of file StrictMatchFUEstimator.cc.
{
        try {
            // simply fetch the delay data of the FU port, if any
            DataObject delayFromDB = hdb.fuCostEstimationData(
                "output_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No output_delay cost data found for FU "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), HDB::HDBManager::fuCostEstimationData(), implementation, Application::logStream(), and CostEstimator::CostEstimationPlugin::name_.
estimatePortWriteDelay()
bool StrictMatchFUEstimator::estimatePortWriteDelay (const TTAMachine::FUPort & , const IDF::FUImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the function unit port write delay by fetching cost data named 'input_delay' from HDB.
Assumes that all ports have the same input delay, that is, there is only one 'input_delay' entry for a FU in HDB.
Reimplemented from CostEstimator::FUCostEstimationPlugin.
Definition at line 104 of file StrictMatchFUEstimator.cc.
{
        try {
            // simply fetch the delay data of the FU port, if any
            DataObject delayFromDB = hdb.fuCostEstimationData(
                "input_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No input_delay cost data found for FU "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), HDB::HDBManager::fuCostEstimationData(), implementation, Application::logStream(), and CostEstimator::CostEstimationPlugin::name_.
The documentation for this class was generated from the following file:
StrictMatchFUEstimator.cc