OpenASIP: RFImplementationDialog Class Reference
RFImplementationDialog Class Reference
#include <RFImplementationDialog.hh>
Public Member Functions
RFImplementationDialog (wxWindow *parent, wxWindowID id, HDB::RFImplementation &implementation)
virtual ~RFImplementationDialog ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_NAME , ID_LABEL_CLK_PORT , ID_CLK_PORT ,
ID_LABEL_RESET_PORT , ID_RESET_PORT , ID_LABEL_GLOCK_PORT , ID_GLOCK_PORT ,
ID_LABEL_GUARD_PORT , ID_GUARD_PORT , ID_LABEL_SIZE_PARAMETER , ID_SIZE_PARAMETER ,
ID_LABEL_WIDTH_PARAMETER , ID_WIDTH_PARAMETER , ID_LABEL_SAC , ID_SAC ,
ID_PORT_LIST , ID_ADD_PORT , ID_MODIFY_PORT , ID_DELETE_PORT ,
ID_SOURCE_LIST , ID_ADD_SOURCE , ID_DELETE_SOURCE , ID_MOVE_SOURCE_UP ,
ID_MOVE_SOURCE_DOWN , ID_LINE , ID_EXTERNAL_PORT_LIST , ID_ADD_EXTERNAL_PORT ,
ID_EDIT_EXTERNAL_PORT , ID_DELETE_EXTERNAL_PORT , ID_PARAMETER_LIST , ID_EDIT_PARAMETER ,
ID_ADD_PARAMETER , ID_DELETE_PARAMETER , ID_SIZE_CHOICE , ID_WIDTH_CHOICE
}
Window indentifiers for dialog widgets.
enum { RBOX_FALSE = 0 , RBOX_TRUE }
Private Member Functions
void onOK (wxCommandEvent &event)
void update ()
HDB::RFPortImplementation * selectedPort ()
HDB::RFExternalPort * selectedExternalPort ()
HDB::RFImplementation::Parameter selectedParameter ()
void onSACchoise (wxCommandEvent &event)
void onPortSelection (wxListEvent &event)
void onAddPort (wxCommandEvent &event)
void onModifyPort (wxCommandEvent &event)
void onDeletePort (wxCommandEvent &event)
void onExternalPortActivation (wxListEvent &event)
void onExternalPortSelection (wxListEvent &event)
void onAddExternalPort (wxCommandEvent &event)
void onEditExternalPort (wxCommandEvent &event)
void onDeleteExternalPort (wxCommandEvent &event)
void onParameterActivation (wxListEvent &event)
void onParameterSelection (wxListEvent &event)
void onAddParameter (wxCommandEvent &event)
void onEditParameter (wxCommandEvent &event)
void onDeleteParameter (wxCommandEvent &event)
void onSourceFileSelection (wxListEvent &event)
void onAddSourceFile (wxCommandEvent &event)
void onDeleteSourceFile (wxCommandEvent &event)
void onMoveSourceFileUp (wxCommandEvent &)
void onMoveSourceFileDown (wxCommandEvent &)
void onSizeChoice (wxCommandEvent &event)
void onWidthChoice (wxCommandEvent &event)
wxString getWidthParameter ()
wxString getSizeParameter ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
HDB::RFImplementation & implementation_
RF Implementation to modify.
wxListCtrl * portList_
Pointer to the port list widget.
wxListCtrl * sourceList_
Pointer to the source file list widget.
wxListCtrl * externalPortList_
Pointer to the external port list widget.
wxListCtrl * parameterList_
Pointer to the parameter list widget.
wxChoice * sizeChoice_
Pointer to size parameter choice widget.
wxChoice * widthChoice_
Pointer to width parameter choice widget.
wxString name_
wxString clkPort_
wxString rstPort_
wxString gLockPort_
wxString guardPort_
bool sacParam_
Detailed Description
Dialog for editing RF implementations.
Definition at line 45 of file RFImplementationDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Window indentifiers for dialog widgets.
Enumerator
ID_LABEL_NAME
ID_NAME
ID_LABEL_CLK_PORT
ID_CLK_PORT
ID_LABEL_RESET_PORT
ID_RESET_PORT
ID_LABEL_GLOCK_PORT
ID_GLOCK_PORT
ID_LABEL_GUARD_PORT
ID_GUARD_PORT
ID_LABEL_SIZE_PARAMETER
ID_SIZE_PARAMETER
ID_LABEL_WIDTH_PARAMETER
ID_WIDTH_PARAMETER
ID_LABEL_SAC
ID_SAC
ID_PORT_LIST
ID_ADD_PORT
ID_MODIFY_PORT
ID_DELETE_PORT
ID_SOURCE_LIST
ID_ADD_SOURCE
ID_DELETE_SOURCE
ID_MOVE_SOURCE_UP
ID_MOVE_SOURCE_DOWN
ID_LINE
ID_EXTERNAL_PORT_LIST
ID_ADD_EXTERNAL_PORT
ID_EDIT_EXTERNAL_PORT
ID_DELETE_EXTERNAL_PORT
ID_PARAMETER_LIST
ID_EDIT_PARAMETER
ID_ADD_PARAMETER
ID_DELETE_PARAMETER
ID_SIZE_CHOICE
ID_WIDTH_CHOICE
Definition at line 95 of file RFImplementationDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_NAME,
        ID_LABEL_CLK_PORT,
        ID_CLK_PORT,
        ID_LABEL_RESET_PORT,
        ID_RESET_PORT,
        ID_LABEL_GLOCK_PORT,
        ID_GLOCK_PORT,
        ID_LABEL_GUARD_PORT,
        ID_GUARD_PORT,
        ID_LABEL_SIZE_PARAMETER,
        ID_SIZE_PARAMETER,
        ID_LABEL_WIDTH_PARAMETER,
        ID_WIDTH_PARAMETER,
        ID_LABEL_SAC,
        ID_SAC,
        ID_PORT_LIST,
        ID_ADD_PORT,
        ID_MODIFY_PORT,
        ID_DELETE_PORT,
        ID_SOURCE_LIST,
        ID_ADD_SOURCE,
        ID_DELETE_SOURCE,
        ID_MOVE_SOURCE_UP,
        ID_MOVE_SOURCE_DOWN,
        ID_LINE,
        ID_EXTERNAL_PORT_LIST,
        ID_ADD_EXTERNAL_PORT,
        ID_EDIT_EXTERNAL_PORT,
        ID_DELETE_EXTERNAL_PORT,
        ID_PARAMETER_LIST,
        ID_EDIT_PARAMETER,
        ID_ADD_PARAMETER,
        ID_DELETE_PARAMETER,
        ID_SIZE_CHOICE,
        ID_WIDTH_CHOICE
    };
anonymous enum
anonymous enum private
Enumerator
RBOX_FALSE
RBOX_TRUE
Definition at line 135 of file RFImplementationDialog.hh.
         {
        RBOX_FALSE = 0,
        RBOX_TRUE
    };
Constructor & Destructor Documentation
RFImplementationDialog()
RFImplementationDialog::onPortSelection RFImplementationDialog::onSourceFileSelection RFImplementationDialog::onAddExternalPort RFImplementationDialog::onDeleteExternalPort RFImplementationDialog::onExternalPortActivation RFImplementationDialog::onParameterSelection RFImplementationDialog::onParameterSelection RFImplementationDialog::RFImplementationDialog (wxWindow * parent, wxWindowID id, HDB::RFImplementation & implementation)
The Constructor.
Parameters
parent Parent window of the dialog.
id Window identifier for the dialog window.
implementation RF implementation to modify.
Definition at line 125 of file RFImplementationDialog.cc.
                                                     :
                    wxDialog(parent, id, _T("Register File Implementation")),
                    implementation_(implementation) {
    createContents(this, true, true);
    // Initialize list and choice widgets.
    portList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    sourceList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_SOURCE_LIST));
    externalPortList_ = dynamic_cast<wxListCtrl*>(FindWindow(
        ID_EXTERNAL_PORT_LIST));
    parameterList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PARAMETER_LIST));
    sizeChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_SIZE_CHOICE));
    widthChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_WIDTH_CHOICE));
    assert(sizeChoice_);
    assert(widthChoice_);
    portList_->InsertColumn(0, _T("name"), wxLIST_FORMAT_LEFT, 200);
    sourceList_->InsertColumn(0, _T("source file"), wxLIST_FORMAT_LEFT, 260);
    // Add initial size and width parameter choices
    sizeChoice_->SetSelection(sizeChoice_->Append(
        WxConversion::toWxString(implementation_.sizeParameter())));
    widthChoice_->SetSelection(widthChoice_->Append(
        WxConversion::toWxString(implementation_.widthParameter())));
    // Create columns in list widgets.
    externalPortList_->InsertColumn(0, _T("name"), wxLIST_FORMAT_LEFT, 260);
    parameterList_->InsertColumn(0, _T("parameter"), wxLIST_FORMAT_LEFT, 180);
    parameterList_->InsertColumn(1, _T("value"), wxLIST_FORMAT_LEFT, 80);
    // Read string attributes from the RFImplementation object.
    name_ = WxConversion::toWxString(implementation_.moduleName());
    clkPort_ = WxConversion::toWxString(implementation_.clkPort());
    rstPort_ = WxConversion::toWxString(implementation_.rstPort());
    gLockPort_ = WxConversion::toWxString(implementation_.glockPort());
    guardPort_ = WxConversion::toWxString(implementation_.guardPort());
    sacParam_ = implementation_.separateAddressCycleParameter();
    // Set text field validators.
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_CLK_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &clkPort_));
    FindWindow(ID_RESET_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &rstPort_));
    FindWindow(ID_GLOCK_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &gLockPort_));
    FindWindow(ID_GUARD_PORT)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &guardPort_));
    wxRadioBox* rbox = dynamic_cast<wxRadioBox*>(FindWindow(ID_SAC));
    rbox->SetSelection(sacParam_ ? RBOX_TRUE : RBOX_FALSE);
    // Disable conditional buttons initially.
    FindWindow(ID_DELETE_PORT)->Disable();
    FindWindow(ID_MODIFY_PORT)->Disable();
    FindWindow(ID_DELETE_SOURCE)->Disable();
    FindWindow(ID_EDIT_EXTERNAL_PORT)->Disable();
    FindWindow(ID_DELETE_EXTERNAL_PORT)->Disable();
    FindWindow(ID_EDIT_PARAMETER)->Disable();
    FindWindow(ID_DELETE_PARAMETER)->Disable();
    update();
}
References assert, and WxConversion::toWxString().
~RFImplementationDialog()
RFImplementationDialog::~RFImplementationDialog () virtual
The Destructor.
Definition at line 195 of file RFImplementationDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * RFImplementationDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog contents.
Definition at line 860 of file RFImplementationDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME,
        wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""),
        wxDefaultPosition, wxSize(200,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_CLK_PORT,
        wxT("Clock port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_CLK_PORT, wxT(""),
        wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item6, 0, wxGROW|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_RESET_PORT,
        wxT("Reset port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_RESET_PORT, wxT(""),
        wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item8, 0, wxGROW|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_LABEL_GLOCK_PORT,
        wxT("Global lock port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item9, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_GLOCK_PORT, wxT(""),
        wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item10, 0, wxGROW|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_LABEL_GUARD_PORT,
        wxT("Guard port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item11, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_GUARD_PORT, wxT(""),
        wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item12, 0, wxGROW|wxALL, 5 );
    wxStaticText *item13 = new wxStaticText( parent, ID_LABEL_SIZE_PARAMETER,
        wxT("Size parameter:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item13, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxChoice *sizeChoice = new wxChoice(parent, ID_SIZE_CHOICE,
            wxDefaultPosition, wxSize(80,-1), 0, 0, wxCB_SORT);
    item2->Add( sizeChoice, 0, wxGROW|wxALL, 5 );
    wxStaticText *item15 = new wxStaticText( parent, ID_LABEL_WIDTH_PARAMETER,
        wxT("Width parameter:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item15, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxChoice *widthChoice = new wxChoice(parent, ID_WIDTH_CHOICE,
        wxDefaultPosition, wxSize(80,-1), 0, 0, wxCB_SORT);
    item2->Add(widthChoice, 0, wxGROW|wxALL, 5);
    wxStaticText *saclabel = new wxStaticText(parent, ID_LABEL_SAC,
        wxT("Separate address cycle:"), wxDefaultPosition, wxDefaultSize, 0);
    item2->Add(saclabel, 0, wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL | wxALL,
        5);
    wxString choises[2] =
        { wxT("False"), wxT("True") };
    wxRadioBox *sacradiobox = new wxRadioBox(parent, ID_SAC, wxT(""),
        wxDefaultPosition, wxDefaultSize, 2, choises, 0, wxRA_SPECIFY_COLS);
    item2->Add(sacradiobox, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);
    item1->Add( item2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );
    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *item19 = new wxStaticBox( parent, -1, wxT("Ports:") );
    wxStaticBoxSizer *item18 = new wxStaticBoxSizer( item19, wxVERTICAL );
    wxListCtrl *item20 = new wxListCtrl( parent, ID_PORT_LIST,
        wxDefaultPosition, wxSize(220,160), wxLC_REPORT|wxSUNKEN_BORDER );
    item18->Add( item20, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item22 = new wxButton( parent, ID_ADD_PORT,
        wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item23 = new wxButton( parent, ID_MODIFY_PORT,
        wxT("Modify..."), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item24 = new wxButton( parent, ID_DELETE_PORT,
        wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );
    item18->Add( item21, 0, wxALIGN_CENTER, 5 );
    item17->Add( item18, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item26 = new wxStaticBox( parent, -1, wxT("Source files:") );
    wxStaticBoxSizer *item25 = new wxStaticBoxSizer( item26, wxVERTICAL );
    wxFlexGridSizer *item27_1 = new wxFlexGridSizer( 2, 0, 0 );
    wxListCtrl *item27 = new wxListCtrl( parent, ID_SOURCE_LIST,
        wxDefaultPosition, wxSize(300, 150), wxLC_REPORT|wxSUNKEN_BORDER );
    item27_1->Add( item27, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item27_2 = new wxBoxSizer( wxVERTICAL );
    wxButton *item60 = new wxButton( parent, ID_MOVE_SOURCE_UP, wxT(""),
        wxDefaultPosition, wxSize(20, 20), 0 );
    item27_2->Add( item60, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item61 = new wxButton( parent, ID_MOVE_SOURCE_DOWN, wxT(""),
        wxDefaultPosition, wxSize(20, 20), 0 );
    item27_2->Add( item61, 0, wxALIGN_CENTER|wxALL, 5 );
    item27_1->Add( item27_2, 0, wxALIGN_CENTER, 5 );
    item25->Add( item27_1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item28 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item29 = new wxButton( parent, ID_ADD_SOURCE, wxT("Add..."),
        wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item29, 0, wxALL, 5 );
    wxButton *item30 = new wxButton( parent, ID_DELETE_SOURCE, wxT("Delete"),
        wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );
    item25->Add( item28, 0, 0, 5 );
    item17->Add( item25, 0, wxGROW|wxALL, 5 );
    item1->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    // External ports Box //
    wxBoxSizer *extPortAndParamSizer = new wxBoxSizer( wxHORIZONTAL );
    wxStaticBox *extPortBox = new wxStaticBox(parent, -1,
        wxT("External ports:"));
    wxStaticBoxSizer *extPortBoxSizer = new wxStaticBoxSizer(extPortBox,
        wxVERTICAL);
    wxListCtrl *item35 = new wxListCtrl( parent, ID_EXTERNAL_PORT_LIST,
        wxDefaultPosition, wxSize(200,120), wxLC_REPORT|wxSUNKEN_BORDER );
    extPortBoxSizer->Add( item35, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *extPortButtons = new wxBoxSizer( wxHORIZONTAL );
    wxButton *addExtPort = new wxButton( parent, ID_ADD_EXTERNAL_PORT,
        wxT("Add..."), wxDefaultPosition, wxDefaultSize, 0);
    extPortButtons->Add( addExtPort, 0, wxALL, 5 );
    wxButton *editExtPort = new wxButton( parent, ID_EDIT_EXTERNAL_PORT,
        wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0);
    extPortButtons->Add(editExtPort, 0, wxALIGN_CENTER|wxALL, 5);
    wxButton *deleteExtPort = new wxButton( parent, ID_DELETE_EXTERNAL_PORT,
        wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0);
    extPortButtons->Add(deleteExtPort, 0, wxALIGN_CENTER|wxALL, 5);
    extPortBoxSizer->Add(extPortButtons, 0, wxALIGN_CENTER, 5);
    extPortAndParamSizer->Add(extPortBoxSizer, 0,
        wxALL, 5);
    // Parameter box //
    wxStaticBox *paramBox = new wxStaticBox(parent, -1, wxT("Parameters:"));
    wxStaticBoxSizer *paramBoxSizer = new wxStaticBoxSizer(paramBox,
        wxVERTICAL);
    wxListCtrl *item42 = new wxListCtrl( parent, ID_PARAMETER_LIST,
        wxDefaultPosition, wxSize(300,120), wxLC_REPORT|wxSUNKEN_BORDER );
    paramBoxSizer->Add( item42, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item43 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item44 = new wxButton( parent, ID_ADD_PARAMETER, wxT("Add..."),
        wxDefaultPosition, wxDefaultSize, 0 );
    item43->Add( item44, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item45 = new wxButton( parent, ID_EDIT_PARAMETER, wxT("Edit..."),
        wxDefaultPosition, wxDefaultSize, 0 );
    item43->Add( item45, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item46 = new wxButton( parent, ID_DELETE_PARAMETER,
        wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item43->Add( item46, 0, wxALIGN_CENTER|wxALL, 5 );
    paramBoxSizer->Add( item43, 0,
        0, 5 );
    extPortAndParamSizer->Add( paramBoxSizer, 0,
        wxGROW|wxALL, 5 );
    item1 ->Add(extPortAndParamSizer, 0,
        wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item31 = new wxStaticLine( parent, ID_LINE,
        wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item31, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item32 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item33 = new wxButton( parent, wxID_OK, wxT("&OK"),
        wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item33, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item34 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"),
        wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item34, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item32, 0, wxALL, 5);
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints(parent);
    }
    return item0;
}
References ID_ADD_EXTERNAL_PORT, ID_ADD_PARAMETER, ID_ADD_PORT, ID_ADD_SOURCE, ID_CLK_PORT, ID_DELETE_EXTERNAL_PORT, ID_DELETE_PARAMETER, ID_DELETE_PORT, ID_DELETE_SOURCE, ID_EDIT_EXTERNAL_PORT, ID_EDIT_PARAMETER, ID_EXTERNAL_PORT_LIST, ID_GLOCK_PORT, ID_GUARD_PORT, ID_LABEL_CLK_PORT, ID_LABEL_GLOCK_PORT, ID_LABEL_GUARD_PORT, ID_LABEL_NAME, ID_LABEL_RESET_PORT, ID_LABEL_SAC, ID_LABEL_SIZE_PARAMETER, ID_LABEL_WIDTH_PARAMETER, ID_LINE, ID_MODIFY_PORT, ID_MOVE_SOURCE_DOWN, ID_MOVE_SOURCE_UP, ID_NAME, ID_PARAMETER_LIST, ID_PORT_LIST, ID_RESET_PORT, ID_SAC, ID_SIZE_CHOICE, ID_SOURCE_LIST, and ID_WIDTH_CHOICE.
getSizeParameter()
wxString RFImplementationDialog::getSizeParameter () private
Returns name of currently selected size parameter.
Returns
Name of selected item or empty string if there is no valid selection.
Definition at line 800 of file RFImplementationDialog.cc.
{
    return sizeChoice_->GetString(sizeChoice_->GetSelection());
}
References sizeChoice_.
Referenced by onOK(), and update().
getWidthParameter()
wxString RFImplementationDialog::getWidthParameter () private
Returns name of currently selected width parameter.
Returns
Name of selected item or empty string if there is no valid selection.
Definition at line 812 of file RFImplementationDialog.cc.
{
    return widthChoice_->GetString(widthChoice_->GetSelection());
}
References widthChoice_.
Referenced by onOK(), and update().
onAddExternalPort()
void RFImplementationDialog::onAddExternalPort (wxCommandEvent & event) private
Event handler for the add external port button.
Opens a RFExternalPortDialog for adding a new external port.
Definition at line 439 of file RFImplementationDialog.cc.
{
    RFExternalPort* port = new RFExternalPort(
        "", IN, "", "", implementation_);
    RFExternalPortDialog dialog(this, -1, *port, implementation_);
    if (dialog.ShowModal() != wxID_OK) {
        implementation_.deleteExternalPort(port);
        return;
    }
    update();
}
References HDB::RFImplementation::deleteExternalPort(), implementation_, HDB::IN, and update().
onAddParameter()
void RFImplementationDialog::onAddParameter (wxCommandEvent & event) private
Event handler for the add parameter button.
Opens a ImplementationParameterDialog for adding a new parameter.
Definition at line 547 of file RFImplementationDialog.cc.
{
    RFImplementation::Parameter parameter;
    ImplementationParameterDialog dialog(this, -1, parameter);
    bool error = false;
    wxString message = _T("");
    if (dialog.ShowModal() != wxID_OK) {
        return;
    }
    if (error) {
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    try {
        implementation_.addParameter(
            parameter.name, parameter.type, parameter.value);
    } catch (IllegalParameters& e) {
        message = _T("RF implementation already contains ");
        message.Append(_T("a parameter\nwith name '"));
        message.Append(WxConversion::toWxString(parameter.name));
        message.Append(_T("'."));
        error = true;
    }
    if (error) {
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    update();
}
References HDB::RFImplementation::addParameter(), implementation_, HDB::Parameter::name, WxConversion::toWxString(), HDB::Parameter::type, update(), and HDB::Parameter::value.
onAddPort()
void RFImplementationDialog::onAddPort (wxCommandEvent & event) private
Event handler for the add port button.
Opens a RFPortImplementationdialog for adding a new port.
Definition at line 275 of file RFImplementationDialog.cc.
{
    RFPortImplementation* port = new RFPortImplementation("", HDB::IN, "", "",
        "", implementation_);
    RFPortImplementationDialog dialog(this, -1, *port);
    if (dialog.ShowModal() != wxID_OK) {
        implementation_.deletePort(port);
    }
    update();
}
References HDB::RFImplementation::deletePort(), implementation_, HDB::IN, and update().
onAddSourceFile()
void RFImplementationDialog::onAddSourceFile (wxCommandEvent & event) private
Event handler for the add source file button.
Opens a source file dialog for adding a new implementation file to the list.
Definition at line 646 of file RFImplementationDialog.cc.
{
    BlockImplementationFile* file = new BlockImplementationFile("",
        BlockImplementationFile::VHDL);
    BlockImplementationFileDialog dialog(this, -1, *file);
    if (dialog.ShowModal() == wxID_OK) {
        implementation_.addImplementationFile(file);
        update();
    } else {
        delete file;
    }
}
References HDB::HWBlockImplementation::addImplementationFile(), implementation_, update(), and HDB::BlockImplementationFile::VHDL.
onDeleteExternalPort()
void RFImplementationDialog::onDeleteExternalPort (wxCommandEvent & event) private
Event handler for the delete external port button.
Deletes the selected external port.
Definition at line 480 of file RFImplementationDialog.cc.
{
    RFExternalPort* port = selectedExternalPort();
    if (port == NULL) {
        return;
    }
    implementation_.deleteExternalPort(port);
    update();
}
References HDB::RFImplementation::deleteExternalPort(), implementation_, selectedExternalPort(), and update().
onDeleteParameter()
void RFImplementationDialog::onDeleteParameter (wxCommandEvent & event) private
Event handler for the delete parameter button.
Deletes the selected parameter.
Definition at line 624 of file RFImplementationDialog.cc.
{
    RFImplementation::Parameter parameter = selectedParameter();
    implementation_.removeParameter(parameter.name);
    // update external port parameter dependencies
    for (int i = 0; i < implementation_.externalPortCount(); i++) {
        HDB::RFExternalPort& port = implementation_.externalPort(i);
        port.unsetParameterDependency(parameter.name);
    }
    update();
}
References HDB::RFImplementation::externalPort(), HDB::RFImplementation::externalPortCount(), implementation_, HDB::Parameter::name, HDB::RFImplementation::removeParameter(), selectedParameter(), HDB::ExternalPort::unsetParameterDependency(), and update().
onDeletePort()
void RFImplementationDialog::onDeletePort (wxCommandEvent & event) private
Event handler for the delete port button.
Deletes the selected port.
Definition at line 311 of file RFImplementationDialog.cc.
{
    RFPortImplementation* port = selectedPort();
    if (port == NULL) {
        return;
    }
    implementation_.deletePort(port);
    update();
}
References HDB::RFImplementation::deletePort(), implementation_, selectedPort(), and update().
onDeleteSourceFile()
void RFImplementationDialog::onDeleteSourceFile (wxCommandEvent & event) private
Event handler for the delete source file button.
Removes the selected source file.
Definition at line 668 of file RFImplementationDialog.cc.
{
    std::string fileName = WidgetTools::lcStringSelection(sourceList_, 0);
    for (int i = 0; i < implementation_.implementationFileCount(); i++) {
        const HDB::BlockImplementationFile& file = implementation_.file(i);
        if (file.pathToFile() == fileName) {
            implementation_.removeImplementationFile(file);
        }
    }
    update();
}
References HDB::HWBlockImplementation::file(), implementation_, HDB::HWBlockImplementation::implementationFileCount(), WidgetTools::lcStringSelection(), HDB::BlockImplementationFile::pathToFile(), HDB::HWBlockImplementation::removeImplementationFile(), sourceList_, and update().
onEditExternalPort()
void RFImplementationDialog::onEditExternalPort (wxCommandEvent & event) private
Event handler for the edit external port button.
Opens a RFExternalPort for modifying the selected external port.
Definition at line 460 of file RFImplementationDialog.cc.
{
    RFExternalPort* port = selectedExternalPort();
    if (port == NULL) {
        return;
    }
    RFExternalPortDialog dialog(this, -1, *port, implementation_);
    dialog.ShowModal();
    update();
}
References implementation_, selectedExternalPort(), and update().
onEditParameter()
void RFImplementationDialog::onEditParameter (wxCommandEvent & event) private
Event handler for the edit parameter button.
Opens a ImplementationParamaeterDialog for modifying the selected parameter.
Definition at line 594 of file RFImplementationDialog.cc.
{
    FUImplementation::Parameter parameter = selectedParameter();
    std::string oldName = parameter.name;
    ImplementationParameterDialog dialog(this, -1, parameter);
    if (dialog.ShowModal() == wxID_OK) {
        implementation_.removeParameter(oldName);
        implementation_.addParameter(
            parameter.name, parameter.type, parameter.value);
        // update external port parameter dependencies if needed
        for (int i = 0; i < implementation_.externalPortCount(); i++) {
            HDB::RFExternalPort& port = implementation_.externalPort(i);
            if (port.unsetParameterDependency(oldName)) {
                port.setParameterDependency(parameter.name);
            }
        }
    }
    update();
}
References HDB::RFImplementation::addParameter(), HDB::RFImplementation::externalPort(), HDB::RFImplementation::externalPortCount(), implementation_, HDB::Parameter::name, HDB::RFImplementation::removeParameter(), selectedParameter(), HDB::ExternalPort::setParameterDependency(), HDB::Parameter::type, HDB::ExternalPort::unsetParameterDependency(), update(), and HDB::Parameter::value.
onExternalPortActivation()
void RFImplementationDialog::onExternalPortActivation (wxListEvent & event) private
Event handler for the activate external port list item
Opens a RFExternalPort for modifying the selected external port.
Definition at line 407 of file RFImplementationDialog.cc.
{
    RFExternalPort* port = selectedExternalPort();
    assert(port != NULL);
    RFExternalPortDialog dialog(this, -1, *port, implementation_);
    dialog.ShowModal();
    update();
}
References assert, implementation_, selectedExternalPort(), and update().
onExternalPortSelection()
void RFImplementationDialog::onExternalPortSelection (wxListEvent & event) private
Event handler for the external port list selection changes.
Updates edit/delete external port enabeld/disabled states.
Definition at line 423 of file RFImplementationDialog.cc.
{
    if (selectedExternalPort() == NULL) {
        FindWindow(ID_DELETE_EXTERNAL_PORT)->Disable();
        FindWindow(ID_EDIT_EXTERNAL_PORT)->Disable();
    } else {
        FindWindow(ID_DELETE_EXTERNAL_PORT)->Enable();
        FindWindow(ID_EDIT_EXTERNAL_PORT)->Enable();
    }
}
References ID_DELETE_EXTERNAL_PORT, ID_EDIT_EXTERNAL_PORT, and selectedExternalPort().
Referenced by update().
onModifyPort()
void RFImplementationDialog::onModifyPort (wxCommandEvent & event) private
Event handler for the modify port button.
Modifies the selected port.
Definition at line 329 of file RFImplementationDialog.cc.
{
    RFPortImplementation* port = selectedPort();
    if (port == NULL) {
        return;
    }
    RFPortImplementationDialog dialog(this, -1, *port);
    dialog.ShowModal();
    update();
}
References selectedPort(), and update().
onMoveSourceFileDown()
void RFImplementationDialog::onMoveSourceFileDown (wxCommandEvent &) private
Event handler for the move source file down button.
Moves the selected source file down on the files list.
Definition at line 734 of file RFImplementationDialog.cc.
{
    if (implementation_.implementationFileCount() > 1) {
        std::string fileName = WidgetTools::lcStringSelection(sourceList_, 0);
        std::vector<std::string> pathToFileList;
        int originalImplementationFileCount =
                        implementation_.implementationFileCount();
        for (int i = 0; i < originalImplementationFileCount; i++) {
            HDB::BlockImplementationFile& file = implementation_.file(0);
            pathToFileList.push_back(file.pathToFile());
            implementation_.removeImplementationFile(file);
        }
        for (unsigned int i = 0; i < (pathToFileList.size() - 1); i++) {
            if (pathToFileList.at(i) == fileName) {
                pathToFileList.erase(pathToFileList.begin() + i);
                pathToFileList.insert(pathToFileList.begin() + i + 1,
                    fileName);
                break;
            }
        }
        for (unsigned int i = 0; i < pathToFileList.size(); i++) {
            BlockImplementationFile* file = new BlockImplementationFile(
                pathToFileList.at(i), BlockImplementationFile::VHDL);
            implementation_.addImplementationFile(file);
        }
        pathToFileList.clear();
        update();
        for (int i = 0; i < implementation_.implementationFileCount(); i++) {
            if (implementation_.file(i).pathToFile() == fileName) {
                sourceList_->SetItemState(i, wxLIST_STATE_SELECTED,
                    wxLIST_STATE_SELECTED);
            }
        }
    }
}
References HDB::HWBlockImplementation::addImplementationFile(), HDB::HWBlockImplementation::file(), implementation_, HDB::HWBlockImplementation::implementationFileCount(), WidgetTools::lcStringSelection(), HDB::BlockImplementationFile::pathToFile(), HDB::HWBlockImplementation::removeImplementationFile(), sourceList_, update(), and HDB::BlockImplementationFile::VHDL.
onMoveSourceFileUp()
void RFImplementationDialog::onMoveSourceFileUp (wxCommandEvent &) private
Event handler for the move source file up button.
Moves the selected source file up on the files list.
Definition at line 687 of file RFImplementationDialog.cc.
{
    if (implementation_.implementationFileCount() > 1) {
        std::string fileName = WidgetTools::lcStringSelection(sourceList_, 0);
        std::vector<std::string> pathToFileList;
        int originalImplementationFileCount =
                        implementation_.implementationFileCount();
        for (int i = 0; i < originalImplementationFileCount; i++) {
            HDB::BlockImplementationFile& file = implementation_.file(0);
            pathToFileList.push_back(file.pathToFile());
            implementation_.removeImplementationFile(file);
        }
        for (unsigned int i = 1; i < pathToFileList.size(); i++) {
            if (pathToFileList.at(i) == fileName) {
                pathToFileList.erase(pathToFileList.begin() + i);
                pathToFileList.insert(pathToFileList.begin() + i - 1,
                    fileName);
                break;
            }
        }
        for (unsigned int i = 0; i < pathToFileList.size(); i++) {
            BlockImplementationFile* file = new BlockImplementationFile(
                pathToFileList.at(i), BlockImplementationFile::VHDL);
            implementation_.addImplementationFile(file);
        }
        pathToFileList.clear();
        update();
        for (int i = 0; i < implementation_.implementationFileCount(); i++) {
            if (implementation_.file(i).pathToFile() == fileName) {
                sourceList_->SetItemState(i, wxLIST_STATE_SELECTED,
                    wxLIST_STATE_SELECTED);
            }
        }
    }
}
References HDB::HWBlockImplementation::addImplementationFile(), HDB::HWBlockImplementation::file(), implementation_, HDB::HWBlockImplementation::implementationFileCount(), WidgetTools::lcStringSelection(), HDB::BlockImplementationFile::pathToFile(), HDB::HWBlockImplementation::removeImplementationFile(), sourceList_, update(), and HDB::BlockImplementationFile::VHDL.
onOK()
void RFImplementationDialog::onOK (wxCommandEvent & event) private
Event handler for the OK button.
Validates the dialog data and updates the RFImplementation object string attributes.
Definition at line 824 of file RFImplementationDialog.cc.
{
    TransferDataFromWindow();
    name_ = name_.Trim(true).Trim(false);
    clkPort_ = clkPort_.Trim(true).Trim(false);
    rstPort_ = rstPort_.Trim(true).Trim(false);
    gLockPort_ = gLockPort_.Trim(true).Trim(false);
    guardPort_ = guardPort_.Trim(true).Trim(false);
    if (name_.IsEmpty()) {
        wxString message = _T("Name field must not be empty.");
        InformationDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    implementation_.setModuleName(WxConversion::toString(name_));
    implementation_.setClkPort(WxConversion::toString(clkPort_));
    implementation_.setRstPort(WxConversion::toString(rstPort_));
    implementation_.setGlockPort(WxConversion::toString(gLockPort_));
    implementation_.setGuardPort(WxConversion::toString(guardPort_));
    implementation_.setSeparateAddressCycleParameter(sacParam_);
    implementation_.setWidthParameter(
        WxConversion::toString(getWidthParameter()));
    implementation_.setSizeParameter(
        WxConversion::toString(getSizeParameter()));
    EndModal(wxID_OK);
}
References clkPort_, getSizeParameter(), getWidthParameter(), gLockPort_, guardPort_, implementation_, name_, rstPort_, sacParam_, HDB::HWBlockImplementation::setClkPort(), HDB::HWBlockImplementation::setGlockPort(), HDB::RFImplementation::setGuardPort(), HDB::HWBlockImplementation::setModuleName(), HDB::HWBlockImplementation::setRstPort(), HDB::RFImplementation::setSeparateAddressCycleParameter(), HDB::RFImplementation::setSizeParameter(), HDB::RFImplementation::setWidthParameter(), and WxConversion::toString().
onParameterActivation()
void RFImplementationDialog::onParameterActivation (wxListEvent & event) private
Event handler for the parameter list activation.
Opens a RFImplementationParamaeterDialog for modifying the selected parameter.
Definition at line 500 of file RFImplementationDialog.cc.
{
    RFImplementation::Parameter parameter = selectedParameter();
    std::string oldName = parameter.name;
    ImplementationParameterDialog dialog(this, -1, parameter);
    if (dialog.ShowModal() == wxID_OK) {
        implementation_.removeParameter(oldName);
        implementation_.addParameter(
            parameter.name, parameter.type, parameter.value);
        // update external port parameter dependencies if needed
        for (int i = 0; i < implementation_.externalPortCount(); i++) {
            HDB::RFExternalPort& port = implementation_.externalPort(i);
            if (port.unsetParameterDependency(oldName)) {
                port.setParameterDependency(parameter.name);
            }
        }
    }
    update();
}
References HDB::RFImplementation::addParameter(), HDB::RFImplementation::externalPort(), HDB::RFImplementation::externalPortCount(), implementation_, HDB::Parameter::name, HDB::RFImplementation::removeParameter(), selectedParameter(), HDB::ExternalPort::setParameterDependency(), HDB::Parameter::type, HDB::ExternalPort::unsetParameterDependency(), update(), and HDB::Parameter::value.
onParameterSelection()
void RFImplementationDialog::onParameterSelection (wxListEvent & event) private
Event handler for the parameter list selection changes.
Updates edit/delete parameter enabled/disabled states.
Definition at line 530 of file RFImplementationDialog.cc.
{
    if (selectedParameter().name == "") {
        FindWindow(ID_DELETE_PARAMETER)->Disable();
        FindWindow(ID_EDIT_PARAMETER)->Disable();
    } else {
        FindWindow(ID_DELETE_PARAMETER)->Enable();
        FindWindow(ID_EDIT_PARAMETER)->Enable();
    }
}
References ID_DELETE_PARAMETER, ID_EDIT_PARAMETER, and selectedParameter().
Referenced by update().
onPortSelection()
void RFImplementationDialog::onPortSelection (wxListEvent & event) private
Event handler for the port list selection changes.
Updates the delete port button enabled/disabled state.
Definition at line 295 of file RFImplementationDialog.cc.
{
    if (selectedPort() == NULL) {
        FindWindow(ID_DELETE_PORT)->Disable();
        FindWindow(ID_MODIFY_PORT)->Disable();
    } else {
        FindWindow(ID_DELETE_PORT)->Enable();
        FindWindow(ID_MODIFY_PORT)->Enable();
    }
}
References ID_DELETE_PORT, ID_MODIFY_PORT, and selectedPort().
Referenced by update().
onSACchoise()
void RFImplementationDialog::onSACchoise (wxCommandEvent & event) private
Definition at line 264 of file RFImplementationDialog.cc.
{
    assert((event.GetInt() == RBOX_FALSE) || (event.GetInt() == RBOX_TRUE));
    sacParam_ = (event.GetInt() == RBOX_FALSE) ? false : true;
}
References assert, RBOX_FALSE, RBOX_TRUE, and sacParam_.
onSizeChoice()
void RFImplementationDialog::onSizeChoice (wxCommandEvent & event) private
onSourceFileSelection()
void RFImplementationDialog::onSourceFileSelection (wxListEvent & event) private
Event handler for the source file list selection changes.
Updates delete source file button enabeld/disabled states.
Definition at line 781 of file RFImplementationDialog.cc.
{
    if (WidgetTools::lcStringSelection(sourceList_, 0) == "") {
        FindWindow(ID_DELETE_SOURCE)->Disable();
        FindWindow(ID_MOVE_SOURCE_UP)->Disable();
        FindWindow(ID_MOVE_SOURCE_DOWN)->Disable();
    } else {
        FindWindow(ID_DELETE_SOURCE)->Enable();
        FindWindow(ID_MOVE_SOURCE_UP)->Enable();
        FindWindow(ID_MOVE_SOURCE_DOWN)->Enable();
    }
}
References ID_DELETE_SOURCE, ID_MOVE_SOURCE_DOWN, ID_MOVE_SOURCE_UP, WidgetTools::lcStringSelection(), and sourceList_.
onWidthChoice()
void RFImplementationDialog::onWidthChoice (wxCommandEvent & event) private
selectedExternalPort()
HDB::RFExternalPort * RFImplementationDialog::selectedExternalPort () private
Returns pointer to the external port selected in the external port list.
Returns
Selected external port.
Definition at line 368 of file RFImplementationDialog.cc.
{
    long item = -1;
    item = externalPortList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    return &implementation_.externalPort(item);
}
References HDB::RFImplementation::externalPort(), externalPortList_, and implementation_.
Referenced by onDeleteExternalPort(), onEditExternalPort(), onExternalPortActivation(), and onExternalPortSelection().
selectedParameter()
HDB::RFImplementation::Parameter RFImplementationDialog::selectedParameter () private
Returns copy of the selected parameter in the parameter list.
Returns
Selected parameter.
Definition at line 388 of file RFImplementationDialog.cc.
{
    long item = -1;
    item = parameterList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        RFImplementation::Parameter empty = {"", "", ""};
        return empty;
    }
    return implementation_.parameter(item);
}
References implementation_, HDB::RFImplementation::parameter(), and parameterList_.
Referenced by onDeleteParameter(), onEditParameter(), onParameterActivation(), and onParameterSelection().
selectedPort()
HDB::RFPortImplementation * RFImplementationDialog::selectedPort () private
Returns pointer to the port selected in the port list.
Returns
Selected port.
Definition at line 348 of file RFImplementationDialog.cc.
{
    long item = -1;
    item = portList_->GetNextItem(item, wxLIST_NEXT_ALL,
        wxLIST_STATE_SELECTED);
    if (item == -1) {
        return NULL;
    }
    return &implementation_.port(item);
}
References implementation_, HDB::RFImplementation::port(), and portList_.
Referenced by onDeletePort(), onModifyPort(), and onPortSelection().
update()
void RFImplementationDialog::update () private
Definition at line 199 of file RFImplementationDialog.cc.
{
    // Update port list.
    portList_->DeleteAllItems();
    for (int i = 0; i < implementation_.portCount(); i++) {
        wxString portName = WxConversion::toWxString(
            implementation_.port(i).name());
        portList_->InsertItem(i, portName);
    }
    // Update source file list.
    sourceList_->DeleteAllItems();
    for (int i = 0; i < implementation_.implementationFileCount(); i++) {
        wxString fileName = WxConversion::toWxString(
            implementation_.file(i).pathToFile());
        sourceList_->InsertItem(i, fileName);
    }
    if (implementation_.implementationFileCount() != 0) {
        sourceList_->SetColumnWidth(0, wxLIST_AUTOSIZE);
    }
    // Update external port list.
    externalPortList_->DeleteAllItems();
    for (int i = 0; i < implementation_.externalPortCount(); i++) {
        wxString portName = WxConversion::toWxString(
            implementation_.externalPort(i).name());
        externalPortList_->InsertItem(i, portName);
    }
    // Update parameter list.
    parameterList_->DeleteAllItems();
    for (int i = 0; i < implementation_.parameterCount(); i++) {
        const RFImplementation::Parameter parameter =
            implementation_.parameter(i);
        wxString param = WxConversion::toWxString(parameter.type);
        param.Append(_T(": "));
        param.Append(WxConversion::toWxString(parameter.name));
        parameterList_->InsertItem(i, param);
        parameterList_->SetItem(
            i, 1, WxConversion::toWxString(parameter.value));
    }
    // Update width and size parameter choices
    wxString oldWidthChoice = getWidthParameter();
    wxString oldSizeChoice = getSizeParameter();
    widthChoice_->Clear();
    widthChoice_->Append(_T(""));
    sizeChoice_->Clear();
    sizeChoice_->Append(_T(""));
    for (int i = 0; i < implementation_.parameterCount(); i++) {
        const RFImplementation::Parameter parameter =
            implementation_.parameter(i);
        widthChoice_->Append(WxConversion::toWxString(parameter.name));
        sizeChoice_->Append(WxConversion::toWxString(parameter.name));
    }
    widthChoice_->SetSelection(widthChoice_->FindString(oldWidthChoice));
    sizeChoice_->SetSelection(sizeChoice_->FindString(oldSizeChoice));
    wxListEvent dummy;
    onPortSelection(dummy);
    onExternalPortSelection(dummy);
    onParameterSelection(dummy);
}
References dummy, HDB::RFImplementation::externalPort(), HDB::RFImplementation::externalPortCount(), externalPortList_, HDB::HWBlockImplementation::file(), getSizeParameter(), getWidthParameter(), implementation_, HDB::HWBlockImplementation::implementationFileCount(), HDB::ExternalPort::name(), HDB::Parameter::name, HDB::PortImplementation::name(), onExternalPortSelection(), onParameterSelection(), onPortSelection(), HDB::RFImplementation::parameter(), HDB::RFImplementation::parameterCount(), parameterList_, HDB::BlockImplementationFile::pathToFile(), HDB::RFImplementation::port(), HDB::RFImplementation::portCount(), portList_, sizeChoice_, sourceList_, WxConversion::toWxString(), HDB::Parameter::type, HDB::Parameter::value, and widthChoice_.
Referenced by onAddExternalPort(), onAddParameter(), onAddPort(), onAddSourceFile(), onDeleteExternalPort(), onDeleteParameter(), onDeletePort(), onDeleteSourceFile(), onEditExternalPort(), onEditParameter(), onExternalPortActivation(), onModifyPort(), onMoveSourceFileDown(), onMoveSourceFileUp(), and onParameterActivation().
Member Data Documentation
clkPort_
wxString RFImplementationDialog::clkPort_ private
Definition at line 157 of file RFImplementationDialog.hh.
Referenced by onOK().
externalPortList_
wxListCtrl* RFImplementationDialog::externalPortList_ private
Pointer to the external port list widget.
Definition at line 148 of file RFImplementationDialog.hh.
Referenced by selectedExternalPort(), and update().
gLockPort_
wxString RFImplementationDialog::gLockPort_ private
Definition at line 159 of file RFImplementationDialog.hh.
Referenced by onOK().
guardPort_
wxString RFImplementationDialog::guardPort_ private
Definition at line 160 of file RFImplementationDialog.hh.
Referenced by onOK().
implementation_
HDB::RFImplementation& RFImplementationDialog::implementation_ private
RF Implementation to modify.
Definition at line 141 of file RFImplementationDialog.hh.
Referenced by onAddExternalPort(), onAddParameter(), onAddPort(), onAddSourceFile(), onDeleteExternalPort(), onDeleteParameter(), onDeletePort(), onDeleteSourceFile(), onEditExternalPort(), onEditParameter(), onExternalPortActivation(), onMoveSourceFileDown(), onMoveSourceFileUp(), onOK(), onParameterActivation(), selectedExternalPort(), selectedParameter(), selectedPort(), and update().
name_
wxString RFImplementationDialog::name_ private
Definition at line 156 of file RFImplementationDialog.hh.
Referenced by onOK().
parameterList_
wxListCtrl* RFImplementationDialog::parameterList_ private
Pointer to the parameter list widget.
Definition at line 150 of file RFImplementationDialog.hh.
Referenced by selectedParameter(), and update().
portList_
wxListCtrl* RFImplementationDialog::portList_ private
Pointer to the port list widget.
Definition at line 144 of file RFImplementationDialog.hh.
Referenced by selectedPort(), and update().
rstPort_
wxString RFImplementationDialog::rstPort_ private
Definition at line 158 of file RFImplementationDialog.hh.
Referenced by onOK().
sacParam_
bool RFImplementationDialog::sacParam_ private
Definition at line 161 of file RFImplementationDialog.hh.
Referenced by onOK(), and onSACchoise().
sizeChoice_
wxChoice* RFImplementationDialog::sizeChoice_ private
Pointer to size parameter choice widget.
Definition at line 152 of file RFImplementationDialog.hh.
Referenced by getSizeParameter(), and update().
sourceList_
wxListCtrl* RFImplementationDialog::sourceList_ private
Pointer to the source file list widget.
Definition at line 146 of file RFImplementationDialog.hh.
Referenced by onDeleteSourceFile(), onMoveSourceFileDown(), onMoveSourceFileUp(), onSourceFileSelection(), and update().
widthChoice_
wxChoice* RFImplementationDialog::widthChoice_ private
Pointer to width parameter choice widget.
Definition at line 154 of file RFImplementationDialog.hh.
Referenced by getWidthParameter(), and update().
The documentation for this class was generated from the following files:
RFImplementationDialog.hh
RFImplementationDialog.cc