OpenASIP: RawImageWriter Class Reference
RawImageWriter Class Reference
#include <RawImageWriter.hh>
Public Member Functions
RawImageWriter (const BitVector &bits)
virtual ~RawImageWriter ()
virtual void writeImage (std::ostream &stream) const
Public Member Functions inherited from BitImageWriter
virtual ~BitImageWriter ()
Static Private Member Functions
static char character (const BitVector &bits, unsigned int startIndex)
Private Attributes
const BitVector & bits_
The bits to be written.
Detailed Description
Bit image writer that writes a real binary image.
Definition at line 43 of file RawImageWriter.hh.
Constructor & Destructor Documentation
RawImageWriter()
RawImageWriter::RawImageWriter (const BitVector & bits)
The constructor.
Parameters
bits The bits to be written.
Definition at line 41 of file RawImageWriter.cc.
                                                    : bits_(bits) {
}
~RawImageWriter()
RawImageWriter::~RawImageWriter () virtual
The destructor.
Definition at line 48 of file RawImageWriter.cc.
{
}
Member Function Documentation
character()
char RawImageWriter::character (const BitVector & bits, unsigned int startIndex) static private
Returns the byte of the given bit vector that starts at the given index.
Parameters
bits The bit vector.
startIndex The start index.
Returns
The byte.
Definition at line 74 of file RawImageWriter.cc.
{
    unsigned int vectorSize = bits.size();
    char character = 0;
    if (bits[startIndex]) {
        character++;
    }
    for (int i = 1; i < 8; i++) {
        character = character << 1;
        if (startIndex + i < vectorSize && bits[startIndex + i]) {
            character++;
        }
    }
    return character;
}
References character().
Referenced by character(), and writeImage().
writeImage()
void RawImageWriter::writeImage (std::ostream & stream) const virtual
Writes the bit image to the given output stream.
Parameters
stream The output stream.
Implements BitImageWriter.
Definition at line 58 of file RawImageWriter.cc.
{
    unsigned int size = bits_.size();
    for (unsigned int i = 0; i < size; i += 8) {
        stream << character(bits_, i);
    }
}
References bits_, and character().
Member Data Documentation
bits_
const BitVector& RawImageWriter::bits_ private
The bits to be written.
Definition at line 54 of file RawImageWriter.hh.
Referenced by writeImage().
The documentation for this class was generated from the following files:
RawImageWriter.hh
RawImageWriter.cc