OpenASIP: DisassemblyInstructionSlot Class Reference
DisassemblyInstructionSlot Class Reference abstract
#include <DisassemblyInstructionSlot.hh>
Public Member Functions
virtual ~DisassemblyInstructionSlot ()
virtual std::string toString () const =0
DisassemblyAnnotation & annotation (int index) const
void addAnnotation (DisassemblyAnnotation *annotation)
int annotationCount () const
Protected Member Functions
DisassemblyInstructionSlot ()
Private Member Functions
DisassemblyInstructionSlot (const DisassemblyInstructionSlot &)
Copying not allowed.
DisassemblyInstructionSlot & operator= (const DisassemblyInstructionSlot &)
Assignment not allowed.
Private Attributes
std::vector< DisassemblyAnnotation * > annotationes_
Annotationes of move or long immediates.
Detailed Description
An abstract base class for instruction disassembly slots.
Definition at line 43 of file DisassemblyInstructionSlot.hh.
Constructor & Destructor Documentation
~DisassemblyInstructionSlot()
DisassemblyInstructionSlot::~DisassemblyInstructionSlot () virtual
The destructor.
Definition at line 46 of file DisassemblyInstructionSlot.cc.
{
    for (int i = 0; i < annotationCount(); i++) {
        delete &(annotation(i));
    }
    annotationes_.clear();
}
References annotation(), annotationCount(), and annotationes_.
DisassemblyInstructionSlot() [1/2]
DisassemblyInstructionSlot::DisassemblyInstructionSlot () protected
The Constructor.
Definition at line 39 of file DisassemblyInstructionSlot.cc.
{
}
DisassemblyInstructionSlot() [2/2]
DisassemblyInstructionSlot::DisassemblyInstructionSlot (const DisassemblyInstructionSlot &) private
Copying not allowed.
Member Function Documentation
addAnnotation()
void DisassemblyInstructionSlot::addAnnotation (DisassemblyAnnotation * annotation)
Adds an annotation to instruction slot.
Parameters
annotation Annotation to add.
Definition at line 70 of file DisassemblyInstructionSlot.cc.
{
    annotationes_.push_back(annotation);
}
References annotation(), and annotationes_.
Referenced by TPEFDisassembler::createInstruction().
annotation()
DisassemblyAnnotation & DisassemblyInstructionSlot::annotation (int index) const
Returns annotation of requested index.
Parameters
index Index of annotation to return.
Returns
Annotation of requested index.
Definition at line 60 of file DisassemblyInstructionSlot.cc.
{
    return *(annotationes_.at(index));
}
References annotationes_.
Referenced by addAnnotation(), DisassemblyImmediateAssignment::toString(), DisassemblyMove::toString(), and ~DisassemblyInstructionSlot().
annotationCount()
int DisassemblyInstructionSlot::annotationCount () const
Returns the number of annotationes stored for the slot.
Returns
The number of annotationes stored for the slot.
Definition at line 80 of file DisassemblyInstructionSlot.cc.
{
    return static_cast<int>(annotationes_.size());
}
References annotationes_.
Referenced by DisassemblyImmediateAssignment::toString(), DisassemblyMove::toString(), and ~DisassemblyInstructionSlot().
operator=()
DisassemblyInstructionSlot & DisassemblyInstructionSlot::operator= (const DisassemblyInstructionSlot &) private
Assignment not allowed.
toString()
virtual std::string DisassemblyInstructionSlot::toString () const pure virtual
Implemented in DisassemblyImmediateAssignment, DisassemblyMove, and DisassemblyNOP.
Referenced by DisassemblyGridTable::GetValue(), and DisassemblyInstruction::toString().
Member Data Documentation
annotationes_
std::vector<DisassemblyAnnotation*> DisassemblyInstructionSlot::annotationes_ private
Annotationes of move or long immediates.
Definition at line 61 of file DisassemblyInstructionSlot.hh.
Referenced by addAnnotation(), annotation(), annotationCount(), and ~DisassemblyInstructionSlot().
The documentation for this class was generated from the following files:
DisassemblyInstructionSlot.hh
DisassemblyInstructionSlot.cc