OpenASIP: TTAMachine::Bridge Class Reference
TTAMachine::Bridge Class Reference
#include <Bridge.hh>
Public Member Functions
Bridge (const std::string &name, Bus &sourceBus, Bus &destinationBus)
Bridge (const ObjectState *state, Machine &mach)
virtual ~Bridge ()
virtual void setName (const std::string &name)
Bus * sourceBus () const
Bus * destinationBus () const
Bus * previousBus () const
Bus * nextBus () const
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_BRIDGE = "bridge"
ObjectState name for bridge.
static const std::string OSKEY_SOURCE_BUS = "source"
ObjectState attribute key for source bus name.
static const std::string OSKEY_DESTINATION_BUS = "destination"
ObjectState attribute key for destination bus name.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Member Functions
void adjustChainDirection (const Bus &sourceBus, const Bus &destinationBus)
void setSourceAndDestination (Bus &sourceBus, Bus &destination)
Static Private Member Functions
static void setFirstOfChain (const Bus &bus)
Private Attributes
Bus * sourceBus_
Source bus.
Bus * destinationBus_
Destination bus.
bool sourcePrevious_
Indicates which of the buses is previous and next.
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents a bridge in the machine.
Definition at line 51 of file Bridge.hh.
Constructor & Destructor Documentation
Bridge() [1/2]
TTAMachine::Bridge::Bridge (const std::string & name, Bus & sourceBus, Bus & destinationBus)
Constructor.
Parameters
name Name of the bridge.
sourceBus Bus from which the bridge reads data.
destinationBus Bus to which the bridge writes data.
Exceptions
IllegalRegistration If the given source and destination buses are not registered to the same machine.
ComponentAlreadyExists If there is another bridge by the same name in the machine which contains the source and destination buses.
IllegalConnectivity If the bridge cannot be created because it would violate a connectivity constraint.
IllegalParameters If the given buses are the same instance.
InvalidName If the given name is not a valid component name.
Definition at line 74 of file Bridge.cc.
    : Component(name), sourceBus_(NULL), destinationBus_(NULL) {
    const string procName = "Bridge::Bridge";
    if (&sourceBus == &destinationBus) {
        throw IllegalParameters(__FILE__, __LINE__, procName);
    }
    sourceBus.ensureRegistration(destinationBus);
    MachineTester& tester = sourceBus.machine()->machineTester();
    if (!tester.canBridge(sourceBus, destinationBus)) {
        string errorMsg = MachineTestReporter::bridgingError(
            sourceBus, destinationBus, tester);
        throw IllegalConnectivity(__FILE__, __LINE__, procName, errorMsg);
    }
    setMachine(*sourceBus.machine());
    setSourceAndDestination(sourceBus, destinationBus);
}
References MachineTestReporter::bridgingError(), MachineTester::canBridge(), destinationBus(), TTAMachine::Component::ensureRegistration(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), setMachine(), setSourceAndDestination(), and sourceBus().
Bridge() [2/2]
TTAMachine::Bridge::Bridge (const ObjectState * state, Machine & mach)
Constructor.
Creates a skeleton objects with name only. This constructor should be used by Machine::loadState only. Do not use this constructor.
Parameters
state The ObjectState instance.
mach The machine to which the bridge belongs.
Exceptions
ObjectStateLoadingException If the machine already has a bridge by the same name as the coming name of this bridge or if the ObjectState instance is invalid.
Definition at line 107 of file Bridge.cc.
    : Component(state), sourceBus_(NULL), destinationBus_(NULL) {
    Machine::BridgeNavigator bridgeNav = mach.bridgeNavigator();
    if (!bridgeNav.hasItem(name())) {
        setMachine(mach);
    } else {
        MOMTextGenerator textGenerator;
        format errorMsg = textGenerator.text(MOMTextGenerator::
                                             TXT_BRIDGE_EXISTS_BY_SAME_NAME);
        errorMsg % name();
        string procName = "Bridge::Bridge";
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          errorMsg.str());
    }
}
References TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Component::name(), setMachine(), and Texts::TextGenerator::text().
~Bridge()
TTAMachine::Bridge::~Bridge () virtual
Destructor.
Definition at line 127 of file Bridge.cc.
                {
    unsetMachine();
}
References unsetMachine().
Member Function Documentation
adjustChainDirection()
void TTAMachine::Bridge::adjustChainDirection (const Bus & sourceBus, const Bus & destinationBus) private
Adjusts the direction of the bus chain (next/previous).
When two bus chains are joined by a new bridge the direction of the destination side chain may have to be changed to verify that the direction of the new longer chain does not change in the middle of the chain. That is, if the source bus of the new bridge is the last of its chain and the destination bus of the new bridge is also the last, the direction of the destination side chain has to be changed such that the destination bus will become the first bus of its chain.
Parameters
sourceBus The new source side bus.
destinationBus The new destination side bus.
Definition at line 327 of file Bridge.cc.
{
    Machine* mach = sourceBus.machine();
    Machine::BridgeNavigator bridgeNav = mach->bridgeNavigator();
    // if another bridge joining the buses is found, see the direction
    // from that bridge
    for (int i = 0; i < bridgeNav.count(); i++) {
        Bridge* bridge = bridgeNav.item(i);
        if (bridge->sourceBus() == &destinationBus &&
            bridge->destinationBus() == &sourceBus) {
            if (bridge->previousBus() == &sourceBus) {
                sourcePrevious_ = true;
            } else {
                sourcePrevious_ = false;
            }
            return;
        }
    }
    // change the direction of the bus chain containing destinationBus if
    // needed
    if (!sourceBus.hasNextBus()) {
        sourcePrevious_ = true;
        setFirstOfChain(destinationBus);
    } else {
        sourcePrevious_ = false;
        // find the bus that should be the first bus of destination side
        // chain
        const Bus* otherEnd = &destinationBus;
        while (otherEnd->hasNextBus()) {
            otherEnd = otherEnd->nextBus();
        }
        if (otherEnd != &destinationBus) {
            setFirstOfChain(*otherEnd);
        }
    }
}
References TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), destinationBus(), TTAMachine::Bus::hasNextBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Bus::nextBus(), previousBus(), setFirstOfChain(), sourceBus(), and sourcePrevious_.
Referenced by setSourceAndDestination().
destinationBus()
Bus * TTAMachine::Bridge::destinationBus () const
Referenced by adjustChainDirection(), Bridge(), BEMValidator::checkSourceField(), TTAMachine::Bus::clearSourceBridge(), MachineEditPartFactory::connected(), BridgeFactory::createEditPart(), loadState(), setFirstOfChain(), setSourceAndDestination(), TTAMachine::Bus::setSourceBridge(), BEMGenerator::sourceBridge(), and BEMGenerator::sourceBridgeCount().
loadState()
void TTAMachine::Bridge::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
If the bridge is already joining two buses, the function will not work and ObjectStateLoadingException is thrown. This method works only if the bridge was created by the constructor with ObjectState argument.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the machine already a bridge by the same name as the coming name of this bridge or if creating references fails or if the given ObjectState instance is invalid.
Reimplemented from TTAMachine::Component.
Definition at line 264 of file Bridge.cc.
{
    const string procName = "Bridge::loadState";
    if (state->name() != OSNAME_BRIDGE) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    if (sourceBus() != NULL || destinationBus() != NULL) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Component::loadState(state);
    try {
        string sourceBusName = state->stringAttribute(OSKEY_SOURCE_BUS);
        string destinationBusName =
            state->stringAttribute(OSKEY_DESTINATION_BUS);
        assert(isRegistered());
        Machine::BusNavigator busNav = machine()->busNavigator();
        Bus* source;
        Bus* destination;
        try {
            source = busNav.item(sourceBusName);
            destination = busNav.item(destinationBusName);
        } catch (InstanceNotFound& e) {
            MOMTextGenerator textGenerator;
            format errorMsg = textGenerator.text(
                MOMTextGenerator::TXT_BRIDGE_UNKNOWN_SRC_OR_DST);
            errorMsg % name();
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              errorMsg.str());
        }
        MachineTester& tester = machine()->machineTester();
        if (tester.canBridge(*source, *destination)) {
            setSourceAndDestination(*source, *destination);
        } else {
            string errorMsg = MachineTestReporter::bridgingError(
                *source, *destination, tester);
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                              errorMsg);
        }
    } catch(Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
}
References assert, MachineTestReporter::bridgingError(), TTAMachine::Machine::busNavigator(), MachineTester::canBridge(), destinationBus(), Exception::errorMessage(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::loadState(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), TTAMachine::Component::name(), ObjectState::name(), OSKEY_DESTINATION_BUS, OSKEY_SOURCE_BUS, OSNAME_BRIDGE, setSourceAndDestination(), sourceBus(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_BRIDGE_UNKNOWN_SRC_OR_DST.
Referenced by TTAMachine::Machine::loadState().
nextBus()
Bus * TTAMachine::Bridge::nextBus () const
Returns the next bus from location point of view.
Returns
The next bus.
Definition at line 179 of file Bridge.cc.
                      {
    if (sourcePrevious_) {
        return destinationBus_;
    } else {
        return sourceBus_;
    }
}
References destinationBus_, sourceBus_, and sourcePrevious_.
Referenced by TTAMachine::Bus::nextBus(), TTAMachine::Bus::previousBridge(), and setFirstOfChain().
previousBus()
Bus * TTAMachine::Bridge::previousBus () const
Returns the previous bus from location point of view.
Returns
The previous bus.
Definition at line 164 of file Bridge.cc.
{
    if (sourcePrevious_) {
        return sourceBus_;
    } else {
        return destinationBus_;
    }
}
References destinationBus_, sourceBus_, and sourcePrevious_.
Referenced by adjustChainDirection(), TTAMachine::Bus::nextBridge(), and TTAMachine::Bus::previousBus().
saveState()
ObjectState * TTAMachine::Bridge::saveState () const virtual
Saves the contents to an ObjectState object.
Returns
The newly created ObjectState object.
Reimplemented from TTAMachine::Component.
Definition at line 238 of file Bridge.cc.
{
    ObjectState* bridge = Component::saveState();
    bridge->setName(OSNAME_BRIDGE);
    string sourceBusName = sourceBus_->name();
    string destinationBusName = destinationBus_->name();
    bridge->setAttribute(OSKEY_SOURCE_BUS, sourceBusName);
    bridge->setAttribute(OSKEY_DESTINATION_BUS, destinationBusName);
    return bridge;
}
References destinationBus_, TTAMachine::Component::name(), OSKEY_DESTINATION_BUS, OSKEY_SOURCE_BUS, OSNAME_BRIDGE, TTAMachine::Component::saveState(), ObjectState::setAttribute(), ObjectState::setName(), and sourceBus_.
setFirstOfChain()
void TTAMachine::Bridge::setFirstOfChain (const Bus & bus) static private
Sets the given bus to the first bus of the bus chain.
That is, changes the direction of the chain if the given bus is currently the last bus of the chain. The given bus must be at the end of chain.
Parameters
bus The bus to be set to the first bus of the chain.
Definition at line 400 of file Bridge.cc.
{
    assert(!(bus.hasPreviousBus() && bus.hasNextBus()));
    if (bus.hasNextBus()) {
        // if the bus is already the first
        return;
    } else {
        const Bus* observable = &bus;
        // collect the buses of the chain to set
        set<const Bus*> busesInChain;
        busesInChain.insert(observable);
        while (observable->hasPreviousBus()) {
            observable = observable->previousBus();
            busesInChain.insert(observable);
        }
        Machine::BridgeNavigator bridgeNav =
            bus.machine()->bridgeNavigator();
        // change (next/previous) direction of each bridge that is joining
        // a bus in the set
        for (int i = 0; i < bridgeNav.count(); i++) {
            Bridge* bridge = bridgeNav.item(i);
            // Source bus or destination bus is NULL only if the bridge
            // was created from ObjectState. Then calling nextBus() is
            // illegal because sourcePrevious_ member is not initialized.
            if (bridge->sourceBus() != NULL &&
                bridge->destinationBus() != NULL &&
                AssocTools::containsKey(busesInChain, bridge->nextBus())) {
                bridge->sourcePrevious_ = !bridge->sourcePrevious_;
            }
        }
    }
}
References assert, TTAMachine::Machine::bridgeNavigator(), AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), destinationBus(), TTAMachine::Bus::hasNextBus(), TTAMachine::Bus::hasPreviousBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), nextBus(), TTAMachine::Bus::previousBus(), sourceBus(), and sourcePrevious_.
Referenced by adjustChainDirection().
setMachine()
void TTAMachine::Bridge::setMachine (Machine & mach) virtual
Registers the bridge to a machine.
Parameters
mach Machine to which the bridge is going to be registered.
Exceptions
ComponentAlreadyExists If the given machine already has another bridge by the same name.
Implements TTAMachine::Component.
Definition at line 196 of file Bridge.cc.
{
    mach.addBridge(*this);
    internalSetMachine(mach);
}
References TTAMachine::Machine::addBridge(), and TTAMachine::Component::internalSetMachine().
Referenced by Bridge(), and Bridge().
setName()
void TTAMachine::Bridge::setName (const std::string & name) virtual
Sets the name of the bridge.
Parameters
name Name of the bridge.
Exceptions
ComponentAlreadyExists If a bridge with the given name is already in the same machine.
InvalidName If the given name is not a valid component name.
Reimplemented from TTAMachine::Component.
Definition at line 141 of file Bridge.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->bridgeNavigator().hasItem(name)) {
            string procName = "Bridge::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
setSourceAndDestination()
void TTAMachine::Bridge::setSourceAndDestination (Bus & sourceBus, Bus & destinationBus) private
Sets the source and destination buses of the bridge.
The bridge must not have source and destination buses before calling this method.
Parameters
sourceBus The source bus.
destinationBus The destination bus.
Definition at line 379 of file Bridge.cc.
{
    assert(sourceBus_ == NULL && destinationBus_ == NULL);
    assert(!sourceBus.canWrite(destinationBus));
    assert(!destinationBus.canRead(sourceBus));
    adjustChainDirection(sourceBus, destinationBus);
    sourceBus.setDestinationBridge(*this);
    destinationBus.setSourceBridge(*this);
    sourceBus_ = &sourceBus;
    destinationBus_ = &destinationBus;
}
References adjustChainDirection(), assert, TTAMachine::Bus::canRead(), TTAMachine::Bus::canWrite(), destinationBus(), destinationBus_, TTAMachine::Bus::setDestinationBridge(), TTAMachine::Bus::setSourceBridge(), sourceBus(), and sourceBus_.
Referenced by Bridge(), and loadState().
sourceBus()
Bus * TTAMachine::Bridge::sourceBus () const
Referenced by adjustChainDirection(), Bridge(), TTAMachine::Bus::clearDestinationBridge(), MachineEditPartFactory::connected(), BridgeFactory::createEditPart(), loadState(), TTAMachine::Bus::setDestinationBridge(), setFirstOfChain(), and setSourceAndDestination().
unsetMachine()
void TTAMachine::Bridge::unsetMachine () virtual
Removes registration of the bridge from its current machine.
The bridge is deleted because it cannot be unregistered from the machine.
Implements TTAMachine::Component.
Definition at line 207 of file Bridge.cc.
                     {
    assert(machine() != NULL);
    Bus* oldSource = sourceBus_;
    Bus* oldDestination = destinationBus_;
    sourceBus_ = NULL;
    destinationBus_ = NULL;
    if (oldSource != NULL) {
        // may be NULL if loading the state from ObjectState has failed
        oldSource->clearDestinationBridge(*this);
    }
    if (oldDestination != NULL) {
        // may be NULL if loading the state from ObjectState has failed
        oldDestination->clearSourceBridge(*this);
    }
    Machine* mach = machine();
    internalUnsetMachine();
    mach->deleteBridge(*this);
}
References assert, TTAMachine::Bus::clearDestinationBridge(), TTAMachine::Bus::clearSourceBridge(), TTAMachine::Machine::deleteBridge(), destinationBus_, TTAMachine::Component::internalUnsetMachine(), TTAMachine::Component::machine(), and sourceBus_.
Referenced by ~Bridge().
Member Data Documentation
destinationBus_
Bus* TTAMachine::Bridge::destinationBus_ private
Destination bus.
Definition at line 86 of file Bridge.hh.
Referenced by nextBus(), previousBus(), saveState(), setSourceAndDestination(), and unsetMachine().
OSKEY_DESTINATION_BUS
const string TTAMachine::Bridge::OSKEY_DESTINATION_BUS = "destination" static
ObjectState attribute key for destination bus name.
Definition at line 74 of file Bridge.hh.
Referenced by ADFSerializer::bridgeToMachine(), ADFSerializer::bridgeToMDF(), loadState(), and saveState().
OSKEY_SOURCE_BUS
const string TTAMachine::Bridge::OSKEY_SOURCE_BUS = "source" static
ObjectState attribute key for source bus name.
Definition at line 72 of file Bridge.hh.
Referenced by ADFSerializer::bridgeToMachine(), ADFSerializer::bridgeToMDF(), loadState(), and saveState().
OSNAME_BRIDGE
const string TTAMachine::Bridge::OSNAME_BRIDGE = "bridge" static
ObjectState name for bridge.
Definition at line 70 of file Bridge.hh.
Referenced by ADFSerializer::bridgeToMachine(), ADFSerializer::convertToMDFFormat(), loadState(), TTAMachine::Machine::loadState(), and saveState().
sourceBus_
Bus* TTAMachine::Bridge::sourceBus_ private
Source bus.
Definition at line 84 of file Bridge.hh.
Referenced by nextBus(), previousBus(), saveState(), setSourceAndDestination(), and unsetMachine().
sourcePrevious_
bool TTAMachine::Bridge::sourcePrevious_ private
Indicates which of the buses is previous and next.
Definition at line 88 of file Bridge.hh.
Referenced by adjustChainDirection(), nextBus(), previousBus(), and setFirstOfChain().
The documentation for this class was generated from the following files:
Bridge.hh
Bridge.cc