OpenASIP: Model Class Reference
Model Class Reference
#include <Model.hh>
Public Member Functions
Model ()
Model (const std::string &fileName)
~Model ()
TTAMachine::Machine * getMachine ()
void undo ()
void redo ()
bool canUndo ()
bool canRedo ()
void addObserver (ModelObserver *observer)
void notifyObservers (bool modified=true)
void pushToStack ()
void popFromStack (bool modified=false)
void setNotModified ()
bool isModified () const
Private Types
typedef std::vector< ModelObserver * > ObserverTable
Table of model observers.
typedef std::deque< TTAMachine::Machine * > UndoStack
Machine stack for undo functionality.
Private Member Functions
Model (const Model &)
Copying not allowed.
Model & operator= (const Model &)
Assignment not allowed.
Private Attributes
TTAMachine::Machine * machine_
Machine assigned for this Model. Singleton within a Model.
ObserverTable observers_
Model observers.
unsigned undoStackSize_
Maximum size of the undo stack.
UndoStack undoStack_
TTAMachine::Machine * undone_
Undone modification cache for the redo funciton.
bool modified_
Static Private Attributes
static const unsigned int UNDO_STACK_MAX_SIZE
Maximum undo stack size.
Detailed Description
An interface for modifying the Machine Object Model.
Definition at line 50 of file Model.hh.
Member Typedef Documentation
ObserverTable
typedef std::vector<ModelObserver*> Model::ObserverTable private
Table of model observers.
Definition at line 76 of file Model.hh.
UndoStack
typedef std::deque<TTAMachine::Machine*> Model::UndoStack private
Machine stack for undo functionality.
Definition at line 89 of file Model.hh.
Constructor & Destructor Documentation
Model() [1/3]
Model::Model ()
The Constructor.
Definition at line 53 of file Model.cc.
             : machine_(new Machine()), undone_(NULL), modified_(false) {
}
Model() [2/3]
Model::Model (const std::string & fileName)
The Constructor.
Creates model from a specified file.
Parameters
fileName The file name of the machine description to open.
Definition at line 77 of file Model.cc.
                                      : undone_(NULL), modified_(false) {
    // read Machine from fileName and set it to machine_
    ADFSerializer reader;
    reader.setSourceFile(fileName);
    machine_ = reader.readMachine();
}
References machine_, ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
~Model()
Model::~Model ()
The Destructor.
Definition at line 60 of file Model.cc.
              {
    // delete machine object states in the undo stack
    while (undoStack_.size() != 0) {
        Machine* machine = undoStack_.front();
        undoStack_.pop_front();
        delete machine;
    }
}
References machine, and undoStack_.
Model() [3/3]
Model::Model (const Model &) private
Copying not allowed.
Member Function Documentation
addObserver()
void Model::addObserver (ModelObserver * observer)
Adds an observer for this Model.
Parameters
observer The observer to add.
Definition at line 143 of file Model.cc.
{
    observers_.push_back(observer);
}
References observers_.
Referenced by MDFDocument::OnNewDocument(), and MDFDocument::openADF().
canRedo()
bool Model::canRedo ()
Returns true if the last undone command can be redone.
Returns
True, if the last undone command can be redone.
Definition at line 228 of file Model.cc.
               {
    if (undone_ != NULL) {
        return true;
    }
    return false;
}
References undone_.
Referenced by RedoCmd::isEnabled().
canUndo()
bool Model::canUndo ()
Returns true if the undo stack is not empty.
Returns
True, if the undo stack is not empty.
Definition at line 213 of file Model.cc.
               {
    if (undoStack_.size() > 0) {
        return true;
    }
    return false;
}
References undoStack_.
Referenced by UndoCmd::isEnabled().
getMachine()
Machine * Model::getMachine ()
Returns the Machine.
Definition at line 88 of file Model.cc.
                  {
    return machine_;
}
References machine_.
Referenced by AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), FullyConnectBussesCmd::Do(), PasteComponentCmd::Do(), FullyConnectBussesCmd::isEnabled(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), CallExplorerPluginWindow::onRun(), MDFDocument::OnSaveDocument(), and MDFView::OnUpdate().
isModified()
bool Model::isModified () const inline
Definition at line 66 of file Model.hh.
{ return modified_; }
References modified_.
Referenced by MDFDocument::update().
notifyObservers()
void Model::notifyObservers (bool modified = true)
Notifies all observers of this Model to update themselves.
Definition at line 152 of file Model.cc.
{
    if (modified) {
        modified_ = true;
    }
    for (ObserverTable::iterator i = observers_.begin();
         i != observers_.end(); i++) {
        (*i)->update();
    }
}
References modified_, and observers_.
Referenced by AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), BlocksConnectICCmd::Do(), CallExplorerPluginCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), FullyConnectBussesCmd::Do(), ModifyComponentCmd::Do(), PasteComponentCmd::Do(), VLIWConnectICCmd::Do(), ConnectTool::leftClick(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), popFromStack(), and redo().
operator=()
Model & Model::operator= (const Model &) private
Assignment not allowed.
popFromStack()
void Model::popFromStack (bool modified = false)
Replaces the current machine with the one that is in the top of the undo stack.
Definition at line 195 of file Model.cc.
{
    if (machine_ != NULL) {
        delete machine_;
    }
    machine_ = undoStack_.front();
    undoStack_.pop_front();
    notifyObservers(modified);
}
References machine_, notifyObservers(), and undoStack_.
Referenced by AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), BlocksConnectICCmd::Do(), CallExplorerPluginCmd::Do(), DeleteComponentCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), ModifyComponentCmd::Do(), PasteComponentCmd::Do(), VLIWConnectICCmd::Do(), ConnectTool::leftClick(), and undo().
pushToStack()
void Model::pushToStack ()
Pushes the current machine to the undo stack.
Definition at line 167 of file Model.cc.
                   {
    // Redo is not available after modifications, clear redo cache
    if (undone_ != NULL) {
        delete undone_;
        undone_ = NULL;
    }
    // if undo stack size is at maximum, delete oldest machine from the stack
    while (undoStack_.size() > 0 &&
           undoStack_.size() >=
           unsigned(wxGetApp().options()->undoStackSize())) {
        Machine* last = undoStack_.back();
        undoStack_.pop_back();
        delete last;
    }
    // push copy of the current machine to the undo stack
    undoStack_.push_front(new Machine(*machine_));
}
References machine_, options, undone_, and undoStack_.
Referenced by AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddRFCmd::Do(), AddSocketCmd::Do(), BlocksConnectICCmd::Do(), CallExplorerPluginCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), FullyConnectBussesCmd::Do(), ModifyComponentCmd::Do(), PasteComponentCmd::Do(), VLIWConnectICCmd::Do(), ConnectTool::leftClick(), AddFUFromHDBDialog::onAdd(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), and redo().
redo()
void Model::redo ()
Redoes last undoed modification.
Definition at line 118 of file Model.cc.
            {
    assert (undone_ != NULL);
    Machine* undone = undone_;
    undone_ = NULL;
    // push machine to the undo stack before redoing
    pushToStack();
    // replace machine from the redo cache
    if (machine_ != NULL) {
        delete machine_;
    }
    machine_ = undone;
    notifyObservers();
}
References assert, machine_, notifyObservers(), pushToStack(), and undone_.
setNotModified()
void Model::setNotModified () inline
Definition at line 65 of file Model.hh.
{ modified_ = false; }
References modified_.
Referenced by MDFDocument::update().
undo()
void Model::undo ()
Restores Machine to the state before the last modification.
Definition at line 97 of file Model.cc.
            {
    // delete redo cache
    if (undone_ != NULL) {
        delete undone_;
        undone_ = NULL;
    }
    // add machine to the redo cache before undo
    undone_ = new Machine(*machine_);
    // pop last machine from the undo stack and set is as the machine
    // and set machine as modified.
    popFromStack(true);
}
References machine_, popFromStack(), and undone_.
Member Data Documentation
machine_
TTAMachine::Machine* Model::machine_ private
Machine assigned for this Model. Singleton within a Model.
Definition at line 73 of file Model.hh.
Referenced by getMachine(), Model(), popFromStack(), pushToStack(), redo(), and undo().
modified_
bool Model::modified_ private
Definition at line 94 of file Model.hh.
Referenced by isModified(), notifyObservers(), and setNotModified().
observers_
ObserverTable Model::observers_ private
Model observers.
Definition at line 79 of file Model.hh.
Referenced by addObserver(), and notifyObservers().
UNDO_STACK_MAX_SIZE
const unsigned int Model::UNDO_STACK_MAX_SIZE static private
Maximum undo stack size.
Definition at line 70 of file Model.hh.
undone_
TTAMachine::Machine* Model::undone_ private
Undone modification cache for the redo funciton.
Definition at line 92 of file Model.hh.
Referenced by canRedo(), pushToStack(), redo(), and undo().
undoStack_
UndoStack Model::undoStack_ private
Definition at line 90 of file Model.hh.
Referenced by canUndo(), popFromStack(), pushToStack(), and ~Model().
undoStackSize_
unsigned Model::undoStackSize_ private
Maximum size of the undo stack.
Definition at line 87 of file Model.hh.
The documentation for this class was generated from the following files:
Model.hh
Model.cc