OpenASIP: HDB::FUImplementation Class Reference
HDB::FUImplementation Class Reference
#include <FUImplementation.hh>
Public Types
typedef HDB::Parameter Parameter
Parameter of FU implementation.
Public Member Functions
FUImplementation (const std::string &name, const std::string &opcodePort, const std::string &clkPort, const std::string &rstPort, const std::string &glockPort, const std::string &glockReqPort)
virtual ~FUImplementation ()
FUImplementation (const FUImplementation &o)
void setOpcodePort (const std::string &name)
std::string opcodePort () const
void setGlockReqPort (const std::string &name)
std::string glockReqPort () const
void setOpcode (const std::string &operation, int opcode)
void unsetOpcode (const std::string &operation)
int opcodeCount () const
std::string opcodeOperation (int index) const
bool hasOpcode (const std::string &operation) const
int opcode (const std::string &operation) const
int maxOpcodeWidth () const
void addArchitecturePort (FUPortImplementation *port)
void deleteArchitecturePort (FUPortImplementation *port)
void addExternalPort (FUExternalPort *port)
void deleteExternalPort (FUExternalPort *port)
int architecturePortCount () const
int externalPortCount () const
FUPortImplementation & architecturePort (int index) const
FUPortImplementation & portImplementationByArchitectureName (const std::string &architectureName) const
FUExternalPort & externalPort (int index) const
void addParameter (const std::string &name, const std::string &type, const std::string &value)
void removeParameter (const std::string &name)
int parameterCount () const
Parameter parameter (int index) const
bool hasParameter (const std::string &name) const
Public Member Functions inherited from HDB::HWBlockImplementation
HWBlockImplementation (const std::string &moduleName, const std::string &clkPort, const std::string &rstPort, const std::string &glockPort)
HWBlockImplementation (const HWBlockImplementation &b)
virtual ~HWBlockImplementation ()
bool hasID () const
void setID (RowID id)
RowID id () const
void setModuleName (const std::string &name)
std::string moduleName () const
void setClkPort (const std::string &name)
std::string clkPort () const
void setRstPort (const std::string &name)
std::string rstPort () const
void setGlockPort (const std::string &name)
std::string glockPort () const
void addImplementationFile (BlockImplementationFile *file)
void removeImplementationFile (const BlockImplementationFile &file)
int implementationFileCount () const
BlockImplementationFile & file (int index) const
Private Types
typedef std::vector< FUPortImplementation * > PortTable
Vector type for FUPortImplementation.
typedef std::vector< FUExternalPort * > ExternalPortTable
Vector type for FUExternalPort.
typedef std::map< std::string, int > OpcodeMap
Map type for operation codes.
typedef std::vector< Parameter > ParameterTable
Vector type for parameter names.
Private Attributes
std::string opcodePort_
Name of the opcode port.
std::string glockReqPort_
Name of the global lock request port.
PortTable ports_
Contains the architectural ports.
ExternalPortTable externalPorts_
Contains the external ports.
OpcodeMap opcodes_
Contains the operation codes.
ParameterTable parameters_
Contains the parameters.
Detailed Description
Represents the implementation specific properties of an FU in HDB.
Definition at line 53 of file FUImplementation.hh.
Member Typedef Documentation
ExternalPortTable
typedef std::vector<FUExternalPort*> HDB::FUImplementation::ExternalPortTable private
Vector type for FUExternalPort.
Definition at line 112 of file FUImplementation.hh.
OpcodeMap
typedef std::map<std::string, int> HDB::FUImplementation::OpcodeMap private
Map type for operation codes.
Definition at line 114 of file FUImplementation.hh.
Parameter
typedef HDB::Parameter HDB::FUImplementation::Parameter
Parameter of FU implementation.
Definition at line 61 of file FUImplementation.hh.
ParameterTable
typedef std::vector<Parameter> HDB::FUImplementation::ParameterTable private
Vector type for parameter names.
Definition at line 116 of file FUImplementation.hh.
PortTable
typedef std::vector<FUPortImplementation*> HDB::FUImplementation::PortTable private
Vector type for FUPortImplementation.
Definition at line 110 of file FUImplementation.hh.
Constructor & Destructor Documentation
FUImplementation() [1/2]
HDB::FUImplementation::FUImplementation (const std::string & name, const std::string & opcodePort, const std::string & clkPort, const std::string & rstPort, const std::string & glockPort, const std::string & glockReqPort)
The constructor.
Parameters
name Name of the module.
opcodePort Name of the opcode port.
clkPort Name of the clock port.
rstPort Name of the reset port.
glockPort Name of the global lock port.
glockReqPort Name of the global lock request port.
Definition at line 62 of file FUImplementation.cc.
                                   :
    HWBlockImplementation(name, clkPort, rstPort, glockPort),
    opcodePort_(opcodePort), glockReqPort_(glockReqPort) {
}
~FUImplementation()
HDB::FUImplementation::~FUImplementation () virtual
The destructor.
Deletes all the ports.
Definition at line 113 of file FUImplementation.cc.
{
    SequenceTools::deleteAllItems(externalPorts_);
    SequenceTools::deleteAllItems(ports_);
}
References SequenceTools::deleteAllItems(), externalPorts_, and ports_.
FUImplementation() [2/2]
HDB::FUImplementation::FUImplementation (const FUImplementation & original)
Copy constructor.
Parameters
original FUImplementation to copy.
Definition at line 79 of file FUImplementation.cc.
                                                                   :
    HWBlockImplementation(original) {
    opcodePort_ = original.opcodePort_;
    glockReqPort_ = original.glockReqPort_;
    opcodes_ = original.opcodes_;
    parameters_ = original.parameters_;
    // Deep copy architecture ports.
    for (int i = 0; i < original.architecturePortCount(); i++) {
        FUPortImplementation* portCopy =
            new FUPortImplementation(original.architecturePort(i));
        addArchitecturePort(portCopy);
    }
    // Deep copy external ports.
    for (int i = 0; i < original.externalPortCount(); i++) {
        FUExternalPort* portCopy =
            new FUExternalPort(original.externalPort(i));
        addExternalPort(portCopy);
    }
}
References addArchitecturePort(), addExternalPort(), architecturePort(), architecturePortCount(), externalPort(), externalPortCount(), glockReqPort_, opcodePort_, opcodes_, and parameters_.
Member Function Documentation
addArchitecturePort()
void HDB::FUImplementation::addArchitecturePort (FUPortImplementation * port)
Adds the given architectural port.
Parameters
port The port to be added.
Definition at line 274 of file FUImplementation.cc.
{
    ports_.push_back(port);
}
References ports_.
Referenced by FUImplementation(), and HDB::FUPortImplementation::FUPortImplementation().
addExternalPort()
void HDB::FUImplementation::addExternalPort (FUExternalPort * port)
Adds the given external port.
Parameters
port The port to be added.
Definition at line 300 of file FUImplementation.cc.
{
    externalPorts_.push_back(port);
}
References externalPorts_.
Referenced by HDB::FUExternalPort::FUExternalPort(), and FUImplementation().
addParameter()
void HDB::FUImplementation::addParameter (const std::string & name, const std::string & type, const std::string & value)
Adds the given parameter for the implementation.
Parameters
name Name of the parameter.
type Type of the parameter.
value Value of the parameter.
Exceptions
IllegalParameters If the FU implementation contains a parameter with the same name already.
Definition at line 409 of file FUImplementation.cc.
{
    if (hasParameter(name)) {
        throw IllegalParameters(__FILE__, __LINE__, __func__);
    } else {
        Parameter param = {name, type, value};
        parameters_.push_back(param);
    }
}
References __func__, hasParameter(), and parameters_.
Referenced by FUImplementationDialog::onAddParameter(), FUImplementationDialog::onEditParameter(), and FUImplementationDialog::onParameterActivation().
architecturePort()
FUPortImplementation & HDB::FUImplementation::architecturePort (int index) const
Returns the architectural port implementation at the given position.
Parameters
index The position index.
Returns
The port implementation.
Exceptions
OutOfRange If the given index is negative or not smaller the number of architectural ports.
Definition at line 351 of file FUImplementation.cc.
{
    if (index < 0 || index >= architecturePortCount()) {
        const string procName = "FUImplementation::architecturePort";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *ports_[index];
}
References architecturePortCount(), and ports_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), FUTestbenchGenerator::createTbInstantiation(), FUImplementation(), HDBToHtml::fuImplToHtml(), ProGe::NetlistGenerator::isParameterizable(), FUImplementationDialog::onOK(), portImplementationByArchitectureName(), FUImplementationDialog::selectedArchPort(), and FUImplementationDialog::update().
architecturePortCount()
int HDB::FUImplementation::architecturePortCount () const
Returns the number of architectural ports.
Returns
The number of ports.
Definition at line 326 of file FUImplementation.cc.
{
    return ports_.size();
}
References ports_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), architecturePort(), FUTestbenchGenerator::createTbInstantiation(), ImplementationTester::fuHasOnePort(), FUImplementation(), HDBToHtml::fuImplToHtml(), ProGe::NetlistGenerator::isParameterizable(), FUImplementationDialog::onOK(), portImplementationByArchitectureName(), and FUImplementationDialog::update().
deleteArchitecturePort()
void HDB::FUImplementation::deleteArchitecturePort (FUPortImplementation * port)
Deletes the given architectural port.
Parameters
port The port to delete.
Exceptions
InstanceNotFound If the given port is not in this FU implementation.
Definition at line 287 of file FUImplementation.cc.
{
    bool removed = ContainerTools::deleteValueIfExists(ports_, port);
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, ContainerTools::deleteValueIfExists(), and ports_.
deleteExternalPort()
void HDB::FUImplementation::deleteExternalPort (FUExternalPort * port)
Deletes the given external port.
Parameters
port The port to delete.
Exceptions
InstanceNotFound If the given port is not in this FU implementation.
Definition at line 313 of file FUImplementation.cc.
{
    bool removed = ContainerTools::deleteValueIfExists(externalPorts_, port);
    if (!removed) {
        throw InstanceNotFound(__FILE__, __LINE__, __func__);
    }
}
References __func__, ContainerTools::deleteValueIfExists(), and externalPorts_.
Referenced by FUImplementationDialog::onAddExternalPort(), and FUImplementationDialog::onDeleteExternalPort().
externalPort()
FUExternalPort & HDB::FUImplementation::externalPort (int index) const
Returns the external port at the given position.
Parameters
index The position index.
Returns
The port.
Exceptions
OutOfRange If the given index is negative or not smaller the number of external ports.
Definition at line 390 of file FUImplementation.cc.
{
    if (index < 0 || index >= externalPortCount()) {
        const string procName = "FUImplementation::externalPort";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *externalPorts_[index];
}
References externalPortCount(), and externalPorts_.
Referenced by ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), FUImplementation(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUImplementationDialog::onDeleteParameter(), FUImplementationDialog::onEditParameter(), FUImplementationDialog::onParameterActivation(), FUImplementationDialog::selectedExternalPort(), and FUImplementationDialog::update().
externalPortCount()
int HDB::FUImplementation::externalPortCount () const
Returns the number of external ports.
Returns
The number of external ports.
Definition at line 337 of file FUImplementation.cc.
{
    return externalPorts_.size();
}
References externalPorts_.
Referenced by ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), HDB::HDBManager::addFUImplementation(), externalPort(), ImplementationTester::fuHasExternalPorts(), FUImplementation(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUImplementationDialog::onDeleteParameter(), FUImplementationDialog::onEditParameter(), FUImplementationDialog::onParameterActivation(), and FUImplementationDialog::update().
glockReqPort()
std::string HDB::FUImplementation::glockReqPort () const
Returns the name of the global lock request port.
Returns
The name of the global lock request port.
Definition at line 157 of file FUImplementation.cc.
{
    return glockReqPort_;
}
References glockReqPort_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), and HDBToHtml::fuImplToHtml().
hasOpcode()
bool HDB::FUImplementation::hasOpcode (const std::string & operation) const
Tells whether there is an opcode defined for the given operation.
Parameters
operation Name of the operation.
Returns
True if there is an opcode, otherwise false.
Definition at line 227 of file FUImplementation.cc.
{
    string opName = StringTools::stringToUpper(operation);
    return MapTools::containsKey(opcodes_, opName);
}
References MapTools::containsKey(), opcodes_, and StringTools::stringToUpper().
Referenced by HDB::HDBManager::addFUImplementation(), FUImplementationDialog::onOK(), FUImplementationDialog::onOpcodeSelection(), FUImplementationDialog::onSetOpcode(), and FUImplementationDialog::update().
hasParameter()
bool HDB::FUImplementation::hasParameter (const std::string & name) const
Tells whether the implementation has the given parameter.
Parameters
name Name of the parameter.
Returns
True if the implementation has the parameter, otherwise false.
Definition at line 472 of file FUImplementation.cc.
{
    for (ParameterTable::const_iterator iter = parameters_.begin();
         iter != parameters_.end(); iter++) {
        if (iter->name == name) {
            return true;
        }
    }
    return false;
}
References parameters_.
Referenced by addParameter().
maxOpcodeWidth()
int HDB::FUImplementation::maxOpcodeWidth () const
Returns the maximum bitwidth of an opcode in this FU implementation.
The bitwidth is not stored explicitly in HDB, this method is provided only for convenience.
Returns
The maximum bitwidth needed by an opcode in this FU.
Definition at line 257 of file FUImplementation.cc.
{
    int maxFound = 0;
    for (OpcodeMap::const_iterator i = opcodes_.begin(); i != opcodes_.end();
         ++i) {
        maxFound = std::max(MathTools::requiredBits((*i).second), maxFound);
    }
    return maxFound;
}
References opcodes_, and MathTools::requiredBits().
Referenced by FUTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createTbInstantiation().
opcode()
int HDB::FUImplementation::opcode (const std::string & operation) const
Returns the opcode of the given operation.
Parameters
operation The operation.
Returns
The operation code.
Exceptions
KeyNotFound If there is no opcode defined for the given operation.
Definition at line 242 of file FUImplementation.cc.
{
    string opName = StringTools::stringToUpper(operation);
    return MapTools::valueForKey<int>(opcodes_, opName);
}
References MapTools::keyForValue(), opcodes_, and StringTools::stringToUpper().
Referenced by HDB::HDBManager::addFUImplementation(), FUTestbenchGenerator::createStimulusArrays(), HDBToHtml::fuImplToHtml(), FUImplementationDialog::onSetOpcode(), setOpcode(), and FUImplementationDialog::update().
opcodeCount()
int HDB::FUImplementation::opcodeCount () const
Returns the number of opcodes in the FU.
Returns
The number of opcodes.
Definition at line 194 of file FUImplementation.cc.
{
    return opcodes_.size();
}
References opcodes_.
Referenced by HDBToHtml::fuImplToHtml(), and opcodeOperation().
opcodeOperation()
std::string HDB::FUImplementation::opcodeOperation (int index) const
By the given index, returns an operation that has an opcode.
Parameters
index The index.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of opcodes.
Definition at line 207 of file FUImplementation.cc.
{
    if (index < 0 || index >= opcodeCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    OpcodeMap::const_iterator iter = opcodes_.begin();
    for (int i = 0; i < index; i++) {
        iter++;
    }
    return iter->first;
}
References __func__, opcodeCount(), and opcodes_.
Referenced by HDBToHtml::fuImplToHtml().
opcodePort()
std::string HDB::FUImplementation::opcodePort () const
Returns the name of the opcode port.
Returns
The name of the opcode port.
Definition at line 135 of file FUImplementation.cc.
{
    return opcodePort_;
}
References opcodePort_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), FUTestbenchGenerator::createStimulusArrays(), FUTestbenchGenerator::createTbCode(), FUTestbenchGenerator::createTbInstantiation(), and HDBToHtml::fuImplToHtml().
parameter()
FUImplementation::Parameter HDB::FUImplementation::parameter (int index) const
Returns a parameter by the given index.
Parameters
index The index.
Returns
The parameter.
Exceptions
OutOfRange If the index is negative or not smaller than the number of parameters.
Definition at line 457 of file FUImplementation.cc.
{
    if (index < 0 || index >= parameterCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return parameters_[index];
}
References __func__, parameterCount(), and parameters_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUExternalPortDialog::initialize(), FUImplementationDialog::selectedParameter(), and FUImplementationDialog::update().
parameterCount()
int HDB::FUImplementation::parameterCount () const
Returns the number of parameters.
Returns
The number of parameters.
Definition at line 443 of file FUImplementation.cc.
{
    return parameters_.size();
}
References parameters_.
Referenced by HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), HDBToHtml::fuImplToHtml(), ProGeTestBenchGenerator::generate(), FUExternalPortDialog::initialize(), FUExternalPortDialog::onOK(), parameter(), and FUImplementationDialog::update().
portImplementationByArchitectureName()
FUPortImplementation & HDB::FUImplementation::portImplementationByArchitectureName (const std::string & architectureName) const
Returns the implementation of a port for the given port architecture name.
Parameters
architectureName Name of the port in architecture table.
Returns
The port implementation.
Exceptions
InstanceNotFound If no port with the given architecture name is found.
Definition at line 370 of file FUImplementation.cc.
{
    for (int i = 0; i < architecturePortCount(); ++i) {
        if (ports_[i]->architecturePort() == architectureName)
            return *ports_[i];
    }
    throw InstanceNotFound(
        __FILE__, __LINE__, __func__,
        "No port implementation with the given architecture name found.");
}
References __func__, architecturePort(), architecturePortCount(), and ports_.
Referenced by FUTestbenchGenerator::createStimulusArrays(), and FUTestbenchGenerator::createTbCode().
removeParameter()
void HDB::FUImplementation::removeParameter (const std::string & name)
Removes the parameter of the given name.
Parameters
name Name of the parameter.
Definition at line 426 of file FUImplementation.cc.
{
    for (ParameterTable::iterator iter = parameters_.begin();
         iter != parameters_.end(); iter++) {
        if (iter->name == name) {
            parameters_.erase(iter);
            return;
        }
    }
}
References parameters_.
Referenced by FUImplementationDialog::onDeleteParameter(), FUImplementationDialog::onEditParameter(), and FUImplementationDialog::onParameterActivation().
setGlockReqPort()
void HDB::FUImplementation::setGlockReqPort (const std::string & name)
Sets the name of the global lock request port.
Parameters
name Name of the port.
Definition at line 146 of file FUImplementation.cc.
{
    glockReqPort_ = name;
}
References glockReqPort_.
Referenced by FUImplementationDialog::onOK().
setOpcode()
void HDB::FUImplementation::setOpcode (const std::string & operation, int opcode)
Sets operation code for the given operation.
Parameters
operation Name of the operation.
opcode The operation code.
Definition at line 169 of file FUImplementation.cc.
{
    unsetOpcode(operation);
    string opName = StringTools::stringToUpper(operation);
    opcodes_.insert(std::pair<std::string, int>(opName, opcode));
}
References opcode(), opcodes_, StringTools::stringToUpper(), and unsetOpcode().
Referenced by FUImplementationDialog::onSetOpcode(), and FUImplementationDialog::update().
setOpcodePort()
void HDB::FUImplementation::setOpcodePort (const std::string & name)
Sets the name of the opcode port.
Parameters
name Name of the port.
Definition at line 124 of file FUImplementation.cc.
{
    opcodePort_ = name;
}
References opcodePort_.
Referenced by FUImplementationDialog::onOK().
unsetOpcode()
void HDB::FUImplementation::unsetOpcode (const std::string & operation)
Unsets the opcode of the given operation.
Parameters
operation Name of the operation.
Definition at line 182 of file FUImplementation.cc.
{
    string opName = StringTools::stringToUpper(operation);
    opcodes_.erase(opName);
}
References opcodes_, and StringTools::stringToUpper().
Referenced by FUImplementationDialog::onClearOpcode(), and setOpcode().
Member Data Documentation
externalPorts_
ExternalPortTable HDB::FUImplementation::externalPorts_ private
Contains the external ports.
Definition at line 126 of file FUImplementation.hh.
Referenced by addExternalPort(), deleteExternalPort(), externalPort(), externalPortCount(), and ~FUImplementation().
glockReqPort_
std::string HDB::FUImplementation::glockReqPort_ private
Name of the global lock request port.
Definition at line 121 of file FUImplementation.hh.
Referenced by FUImplementation(), glockReqPort(), and setGlockReqPort().
opcodePort_
std::string HDB::FUImplementation::opcodePort_ private
Name of the opcode port.
Definition at line 119 of file FUImplementation.hh.
Referenced by FUImplementation(), opcodePort(), and setOpcodePort().
opcodes_
OpcodeMap HDB::FUImplementation::opcodes_ private
Contains the operation codes.
Definition at line 128 of file FUImplementation.hh.
Referenced by FUImplementation(), hasOpcode(), maxOpcodeWidth(), opcode(), opcodeCount(), opcodeOperation(), setOpcode(), and unsetOpcode().
parameters_
ParameterTable HDB::FUImplementation::parameters_ private
Contains the parameters.
Definition at line 130 of file FUImplementation.hh.
Referenced by addParameter(), FUImplementation(), hasParameter(), parameter(), parameterCount(), and removeParameter().
ports_
PortTable HDB::FUImplementation::ports_ private
Contains the architectural ports.
Definition at line 124 of file FUImplementation.hh.
Referenced by addArchitecturePort(), architecturePort(), architecturePortCount(), deleteArchitecturePort(), portImplementationByArchitectureName(), and ~FUImplementation().
The documentation for this class was generated from the following files:
FUImplementation.hh
FUImplementation.cc