OpenASIP: TDGenerator::RegisterClass Class Reference
TDGenerator::RegisterClass Class Reference
#include <TDGen.hh>
Public Member Functions
RegisterClass (const ValueType &vt, const TCEString &name)
RegisterClass (const RegisterClass &other)
RegisterClass & operator= (const RegisterClass &other)
TCEString name () const
ValueType valueType () const
int alignment () const
std::vector< RegisterInfo > registers () const
RegisterInfo registerInfo (int index) const
size_t numberOfRegisters () const
void addRegisters (const std::vector< RegisterInfo > &registers)
Private Attributes
TCEString name_
RegisterClass name.
ValueType vt_
Value type that is supported by this RegisterClass, e.g. v4i32.
int alignment_
RegisterClass alignment in bits, at least 8.
std::vector< RegisterInfo > registers_
Register file registers that this RegisterClass uses.
Detailed Description
Represents TableGen RegisterClass class.
Definition at line 736 of file TDGen.hh.
Constructor & Destructor Documentation
RegisterClass() [1/2]
RegisterClass::RegisterClass (const ValueType & vt, const TCEString & name)
Constructor.
Parameters
vt ValueType that is supported by the RegisterClass.
name Name of the RegisterClass.
Definition at line 9013 of file TDGen.cc.
    : name_(name), vt_(vt), registers_(std::vector<RegisterInfo>()) {
    if (vt.width() < 8) {
        alignment_ = 8;
    } else {
        alignment_ = vt.width();
    }
}
References alignment_, and TDGenerator::ValueType::width().
RegisterClass() [2/2]
RegisterClass::RegisterClass (const RegisterClass & other)
Copy constructor.
Parameters
other RegisterClass to be copied.
Definition at line 9027 of file TDGen.cc.
    : name_(other.name_),
      vt_(other.vt_),
      alignment_(other.alignment_),
      registers_(other.registers_) {}
Member Function Documentation
addRegisters()
void RegisterClass::addRegisters (const std::vector< RegisterInfo > & registers)
Sets the registers used by this RegisterClass.
Parameters
registers The new registers used by this RegisterClass.
Definition at line 9107 of file TDGen.cc.
{
    registers_.insert(registers_.end(), registers.begin(), registers.end());
}
References registers(), and registers_.
Referenced by TDGen::associateRegistersWithVectorRegisterClasses().
alignment()
int RegisterClass::alignment () const
Returns the RegisterClass's alignment in bits.
Returns
Alignment of RegisterClass in bits.
Definition at line 9074 of file TDGen.cc.
{
    return alignment_;
}
References alignment_.
Referenced by TDGen::writeCallingConv(), and TDGen::writeVectorRegisterClasses().
name()
TCEString RegisterClass::name () const
Returns RegisterClass's name.
Returns
Name of the RegisterClass.
Definition at line 9054 of file TDGen.cc.
{
    return name_;
}
References name_.
Referenced by TDGen::associatedVectorRegisterClass(), TDGen::createSelectPatterns(), TDGen::genGeneratedTCEPlugin_getLoad(), TDGen::genGeneratedTCEPlugin_getStore(), TDGen::genGeneratedTCEPlugin_getVectorImmediateOpcode(), TDGen::genTCEInstrInfoSIMD_copyPhysVectorReg(), TDGen::genTCETargetLoweringSIMD_addVectorRegisterClasses(), TDGen::genTCETargetLoweringSIMD_associatedVectorRegClass(), TDGen::writeVectorBitConversions(), TDGen::writeVectorImmediateWriteDefs(), TDGen::writeVectorRegisterClasses(), TDGen::writeVectorRegisterMoveDefs(), and TDGen::writeVectorTruncStoreDefs().
numberOfRegisters()
size_t RegisterClass::numberOfRegisters () const
Returns how many registers is used by this RegisterClass.
Returns
A number of registers used by this RegisterClass.
Definition at line 9097 of file TDGen.cc.
{
    return registers_.size();
}
References registers_.
Referenced by TDGen::createVectorRVDRegNums(), TDGen::genTCERegisterInfo_setReservedVectorRegs(), TDGen::writeCallingConv(), and TDGen::writeVectorRegisterClasses().
operator=()
RegisterClass & RegisterClass::operator= (const RegisterClass & other)
Value assignment.
Parameters
other RegisterClass to be assigned.
Returns
Reference with the assigned values.
Definition at line 9040 of file TDGen.cc.
{
    this->name_ = other.name_;
    this->vt_ = other.vt_;
    this->alignment_ = other.alignment_;
    this->registers_ = other.registers_;
    return *this;
}
References alignment_, name_, registers_, and vt_.
registerInfo()
RegisterInfo RegisterClass::registerInfo (int index) const
Returns RegisterInfo pointed by the index.
Returns
RegisterInfo pointed by the index.
Definition at line 9084 of file TDGen.cc.
{
    assert(
        index >= static_cast<int>(0) &&
        index < static_cast<int>(registers_.size()));
    return registers_[index];
}
References assert, and registers_.
Referenced by TDGen::createVectorRVDRegNums(), TDGen::genTCERegisterInfo_setReservedVectorRegs(), TDGen::writeCallingConv(), and TDGen::writeVectorRegisterClasses().
registers()
std::vector< RegisterInfo > TDGenerator::RegisterClass::registers () const
Referenced by addRegisters().
valueType()
ValueType RegisterClass::valueType () const
Returns the supported ValueType.
Returns
Supported ValueType.
Definition at line 9064 of file TDGen.cc.
{
    return vt_;
}
References vt_.
Referenced by TDGen::associateRegistersWithVectorRegisterClasses(), TDGen::createSelectPatterns(), TDGen::createVectorRVDRegNums(), TDGen::genGeneratedTCEPlugin_getVectorImmediateOpcode(), TDGen::genTCERegisterInfo_setReservedVectorRegs(), TDGen::genTCETargetLoweringSIMD_addVectorRegisterClasses(), TDGen::writeCallingConv(), TDGen::writeVectorBitConversions(), TDGen::writeVectorImmediateWriteDefs(), TDGen::writeVectorRegisterClasses(), and TDGen::writeVectorRegisterMoveDefs().
Member Data Documentation
alignment_
int TDGenerator::RegisterClass::alignment_ private
RegisterClass alignment in bits, at least 8.
Definition at line 758 of file TDGen.hh.
Referenced by alignment(), operator=(), and RegisterClass().
name_
TCEString TDGenerator::RegisterClass::name_ private
RegisterClass name.
Definition at line 754 of file TDGen.hh.
Referenced by name(), and operator=().
registers_
std::vector<RegisterInfo> TDGenerator::RegisterClass::registers_ private
Register file registers that this RegisterClass uses.
Definition at line 760 of file TDGen.hh.
Referenced by addRegisters(), numberOfRegisters(), operator=(), and registerInfo().
vt_
ValueType TDGenerator::RegisterClass::vt_ private
Value type that is supported by this RegisterClass, e.g. v4i32.
Definition at line 756 of file TDGen.hh.
Referenced by operator=(), and valueType().
The documentation for this class was generated from the following files:
TDGen.hh
TDGen.cc