OpenASIP: PRegionAliasAnalyzer Class Reference
PRegionAliasAnalyzer Class Reference
#include <PRegionAliasAnalyzer.hh>
Private Member Functions
virtual bool isAddressTraceable (DataDependenceGraph &ddg, const ProgramOperation &pop)
virtual AliasingResult analyze (DataDependenceGraph &ddg, const ProgramOperation &pop1, const ProgramOperation &pop2, MoveNodeUse::BBRelation bbInfo)
~PRegionAliasAnalyzer ()
Additional Inherited Members
Public Types inherited from MemoryAliasAnalyzer
enum AliasingResult { ALIAS_FALSE = 0 , ALIAS_TRUE = 1 , ALIAS_UNKNOWN = 2 , ALIAS_PARTIAL = 3 }
Public Member Functions inherited from MemoryAliasAnalyzer
virtual void initProcedure (TTAProgram::Procedure &)
virtual ~MemoryAliasAnalyzer ()
Protected Member Functions inherited from MemoryAliasAnalyzer
AliasingResult compareIndeces (int index1, int index2, const ProgramOperation &pop1, const ProgramOperation &pop2)
Static Protected Member Functions inherited from MemoryAliasAnalyzer
static const MoveNode * addressOperandMove (const ProgramOperation &po)
static TwoPartAddressOperandDetection findTwoPartAddressOperands (const ProgramOperation &po)
static const MoveNode * searchLoopIndexBasedIncrement (DataDependenceGraph &ddg, const MoveNode &mn, long &loopIncrement)
static const MoveNode * findIncrement (const MoveNode &mn, long &increment)
static const MoveNode * detectConstantScale (const MoveNode &mn, int &shiftAmount)
Detailed Description
Definition at line 41 of file PRegionAliasAnalyzer.hh.
Constructor & Destructor Documentation
~PRegionAliasAnalyzer()
PRegionAliasAnalyzer::~PRegionAliasAnalyzer () private
Definition at line 102 of file PRegionAliasAnalyzer.cc.
{}
Member Function Documentation
analyze()
MemoryAliasAnalyzer::AliasingResult PRegionAliasAnalyzer::analyze (DataDependenceGraph & ddg, const ProgramOperation & pop1, const ProgramOperation & pop2, MoveNodeUse::BBRelation bbInfo) private virtual
Implements MemoryAliasAnalyzer.
Definition at line 57 of file PRegionAliasAnalyzer.cc.
{
    const MoveNode *rawSrc1 = addressOperandMove(pop1);
    const MoveNode *rawSrc2 = addressOperandMove(pop2);
    if (rawSrc1 == NULL || rawSrc2 == NULL ||
        !rawSrc1->isMove() || !rawSrc2->isMove()) return ALIAS_UNKNOWN;
    const TTAProgram::Move &m1 = rawSrc1->move();
    const TTAProgram::Move &m2 = rawSrc2->move();
    if (!m1.hasAnnotations(ProgramAnnotation::ANN_PARALLEL_REGION_ID) ||
        !m2.hasAnnotations(ProgramAnnotation::ANN_PARALLEL_REGION_ID))
        return ALIAS_UNKNOWN;
    int pregion1 = m1.annotation(
        0, ProgramAnnotation::ANN_PARALLEL_REGION_ID).intValue();
    int pregion2 = m2.annotation(
        0, ProgramAnnotation::ANN_PARALLEL_REGION_ID).intValue();
    if (pregion1 != pregion2) {
#if 0
        Application::logStream()
            << "### based on PREGION info, removed a memory edge between "
            << m1.toString() << " (" << pregion1 << ") and "
            << m2.toString() << " (" << pregion2 << ")" << std::endl;
        Application::logStream()
            << "### src lines: ";
        if (m1.hasSourceLineNumber())
            Application::logStream()
                << m1.sourceLineNumber() << " ";
        if (m2.hasSourceLineNumber())
            Application::logStream()
                << m2.sourceLineNumber() << " ";
        Application::logStream() << std::endl;
#endif
        return ALIAS_FALSE;
    }
    return ALIAS_UNKNOWN;
}
References MemoryAliasAnalyzer::addressOperandMove(), MemoryAliasAnalyzer::ALIAS_FALSE, MemoryAliasAnalyzer::ALIAS_UNKNOWN, TTAProgram::ProgramAnnotation::ANN_PARALLEL_REGION_ID, TTAProgram::AnnotatedInstructionElement::annotation(), TTAProgram::AnnotatedInstructionElement::hasAnnotations(), TTAProgram::Move::hasSourceLineNumber(), TTAProgram::ProgramAnnotation::intValue(), MoveNode::isMove(), Application::logStream(), MoveNode::move(), TTAProgram::Move::sourceLineNumber(), and TTAProgram::Move::toString().
isAddressTraceable()
bool PRegionAliasAnalyzer::isAddressTraceable (DataDependenceGraph & ddg, const ProgramOperation & pop) private virtual
Checks whether the analyzer knows anything about the address.
ie. if it can return true or false to some query concerning this address.
Returns
true if analyzer can know something about the address.
Implements MemoryAliasAnalyzer.
Definition at line 50 of file PRegionAliasAnalyzer.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
PRegionAliasAnalyzer.hh
PRegionAliasAnalyzer.cc