OpenASIP: BEMGenerator Class Reference
BEMGenerator Class Reference
#include <BEMGenerator.hh>
Public Member Functions
BEMGenerator (const TTAMachine::Machine &machine)
virtual ~BEMGenerator ()
BinaryEncoding * generate ()
Private Types
typedef std::map< const TTAMachine::Socket *, SocketCodeTable * > SCTableMap
Map type for storing Socket - SocketCodeTable pairs.
typedef std::pair< unsigned int, unsigned int > Encoding
Typedef for encoding (first = encoding, second = extra bits).
Private Member Functions
void addLongImmDstRegisterFields (BinaryEncoding &bem) const
void addSocketCodeTables (BinaryEncoding &bem)
void addTopLevelFields (BinaryEncoding &bem) const
void addSubfields (MoveSlot &slot) const
void addEncodings (ImmediateControlField &field) const
void addEncodings (DestinationField &field) const
void addEncodings (SourceField &field) const
void addEncodings (GuardField &field) const
void addRiscvFormat (TTAMachine::OperationTriggeredFormat *format, BinaryEncoding &bem, unsigned &amountOfRCustomOps, unsigned &amountOfR3RCustomOps) const
void addPortCodes (SocketCodeTable &table, const TTAMachine::Socket &socket) const
SocketCodeTable * socketCodeTable (const TTAMachine::Socket &socket) const
SocketCodeTable * suitableSocketCodeTable (const TTAMachine::Socket &socket) const
void assignSocketCodeTable (const TTAMachine::Socket *socket, SocketCodeTable *table)
std::multiset< int > socketCodeWidthsForBus (const TTAMachine::Bus &bus, TTAMachine::Socket::Direction socketDir) const
unsigned int maxLongImmSlotWidth (const MoveSlot &slot) const
Static Private Member Functions
static int socketCount (const TTAMachine::Bus &bus, TTAMachine::Socket::Direction direction)
static TTAMachine::Socket & socket (int index, const TTAMachine::Bus &bus, TTAMachine::Socket::Direction direction)
static bool needsSocketCodeTable (const TTAMachine::Socket &socket)
static bool haveEqualConnections (const TTAMachine::Socket &socket1, const TTAMachine::Socket &socket2)
static int sourceBridgeCount (const TTAMachine::Bus &bus)
static TTAMachine::Bridge & sourceBridge (int index, const TTAMachine::Bus &bus)
static bool hasUnconditionalGuard (const TTAMachine::Bus &bus)
static int requiredIndexWidth (const TTAMachine::BaseRegisterFile &regFile)
static void calculateEncodings (const std::multiset< int > &oppositeFieldWidths, bool leftAlignment, std::multiset< Encoding > &encodings)
static void addExtraBits (std::multiset< Encoding > &encodings, int bitCount)
Private Attributes
const TTAMachine::Machine * machine_
The machine for which the BEM is generated.
SCTableMap scTableMap_
A map which tells which socket code table belongs to a socket.
Detailed Description
Generates a binary encoding map for the given machine.
Definition at line 61 of file BEMGenerator.hh.
Member Typedef Documentation
Encoding
typedef std::pair<unsigned int, unsigned int> BEMGenerator::Encoding private
Typedef for encoding (first = encoding, second = extra bits).
Definition at line 72 of file BEMGenerator.hh.
SCTableMap
typedef std::map<const TTAMachine::Socket*, SocketCodeTable*> BEMGenerator::SCTableMap private
Map type for storing Socket - SocketCodeTable pairs.
Definition at line 70 of file BEMGenerator.hh.
Constructor & Destructor Documentation
BEMGenerator()
BEMGenerator::BEMGenerator (const TTAMachine::Machine & machine)
The constructor.
Parameters
machine The machine for which the binary encoding map will be generated.
Definition at line 86 of file BEMGenerator.cc.
                                                 :
    machine_(&machine) {
}
~BEMGenerator()
BEMGenerator::~BEMGenerator () virtual
The destructor.
Definition at line 94 of file BEMGenerator.cc.
{
}
Member Function Documentation
addEncodings() [1/4]
void BEMGenerator::addEncodings (DestinationField & field) const private
Adds encodings for the given destination field.
Parameters
field The destination field.
Definition at line 603 of file BEMGenerator.cc.
{
    string busName = field.parent()->name();
    Machine::BusNavigator busNav = machine_->busNavigator();
    assert(busNav.hasItem(busName));
    Bus* bus = busNav.item(busName);
    bool createNopField = true;
    for (int i = 0; i < bus->guardCount(); i++) {
    Guard* g = bus->guard(i);
    if (g->isInverted() && dynamic_cast<UnconditionalGuard*>(g) != NULL) {
        createNopField = false;
    }
    }
    int dstSockets = socketCount(*bus, Socket::INPUT);
    if (dstSockets == 0) {
        return;
    }
    multiset<int> socketCodeWidths = socketCodeWidthsForBus(
        *bus, Socket::INPUT);
    // add socket code width for NOP encoding
    if (createNopField) {
        socketCodeWidths.insert(0);
    }
    multiset<Encoding> encodings;
    calculateEncodings(socketCodeWidths, true, encodings);
    set<Socket*> handledSockets;
    multiset<int>::reverse_iterator scIter = socketCodeWidths.rbegin();
    bool nopEncodingSet = false;
    for (multiset<Encoding>::const_iterator encIter = encodings.begin();
         encIter != encodings.end(); encIter++) {
        Encoding enc = *encIter;
        int scWidth = *scIter;
        if (scWidth == 0 && !nopEncodingSet && createNopField) {
            // add NOP encoding
            new NOPEncoding(enc.first, enc.second, field);
            nopEncodingSet = true;
        } else {
            // find socket that has correct socket code width
            for (int i = 0; i < dstSockets; i++) {
                Socket& socket = BEMGenerator::socket(
                    i, *bus, Socket::INPUT);
                SocketCodeTable* scTable = socketCodeTable(socket);
                if (scTable == NULL && scWidth == 0 &&
                    !AssocTools::containsKey(handledSockets, &socket)) {
                    new SocketEncoding(
                        socket.name(), enc.first, enc.second, field);
                    handledSockets.insert(&socket);
                    break;
                } else if (scTable != NULL && scWidth == scTable->width() &&
                           !AssocTools::containsKey(
                               handledSockets, &socket)) {
                    SocketEncoding* socketEnc = new SocketEncoding(
                        socket.name(), enc.first, enc.second, field);
                    socketEnc->setSocketCodes(*scTable);
                    handledSockets.insert(&socket);
                    break;
                }
            }
        }
        scIter++;
    }
}
References assert, TTAMachine::Machine::busNavigator(), calculateEncodings(), AssocTools::containsKey(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Socket::INPUT, TTAMachine::Guard::isInverted(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::Component::name(), SlotField::parent(), SocketEncoding::setSocketCodes(), socket(), socketCodeTable(), socketCodeWidthsForBus(), socketCount(), and SocketCodeTable::width().
addEncodings() [2/4]
void BEMGenerator::addEncodings (GuardField & field) const private
Adds guard encodings to the given guard field.
Parameters
field The guard field.
Definition at line 773 of file BEMGenerator.cc.
{
    string busName = field.parent()->name();
    Machine::BusNavigator busNav = machine_->busNavigator();
    assert(busNav.hasItem(busName));
    Bus* bus = busNav.item(busName);
    int guards = bus->guardCount();
    for (int i = 0; i < guards; i++) {
        Guard* guard = bus->guard(i);
        PortGuard* portGuard = dynamic_cast<PortGuard*>(guard);
        RegisterGuard* regGuard = dynamic_cast<RegisterGuard*>(guard);
        UnconditionalGuard* ucGuard =
            dynamic_cast<UnconditionalGuard*>(guard);
        if (portGuard != NULL) {
            FUPort* port = portGuard->port();
            new FUGuardEncoding(
                port->parentUnit()->name(), port->name(),
                portGuard->isInverted(), i, field);
        } else if (regGuard != NULL) {
            new GPRGuardEncoding(
                regGuard->registerFile()->name(), regGuard->registerIndex(),
                regGuard->isInverted(), i, field);
        } else if (ucGuard != NULL) {
            new UnconditionalGuardEncoding(ucGuard->isInverted(), i, field);
        } else {
            assert(false);
        }
    }
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Guard::isInverted(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::Component::name(), TTAMachine::Port::name(), GuardField::parent(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), TTAMachine::RegisterGuard::registerFile(), and TTAMachine::RegisterGuard::registerIndex().
addEncodings() [3/4]
void BEMGenerator::addEncodings (ImmediateControlField & field) const private
Adds the encoding for instruction templates to the given immediate control field.
Parameters
field The immediate control field.
Definition at line 587 of file BEMGenerator.cc.
{
    Machine::InstructionTemplateNavigator itNav =
        machine_->instructionTemplateNavigator();
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        field.addTemplateEncoding(iTemp->name(), i);
    }
}
References ImmediateControlField::addTemplateEncoding(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, and TTAMachine::Component::name().
Referenced by addSubfields(), and addTopLevelFields().
addEncodings() [4/4]
void BEMGenerator::addEncodings (SourceField & field) const private
Adds encodings for the given source field.
Parameters
field The source field.
Definition at line 676 of file BEMGenerator.cc.
{
    string busName = field.parent()->name();
    Machine::BusNavigator busNav = machine_->busNavigator();
    assert(busNav.hasItem(busName));
    Bus* bus = busNav.item(busName);
    bool createNopField = true;
    for (int i = 0; i < bus->guardCount(); i++) {
    Guard* g = bus->guard(i);
    if (g->isInverted() && dynamic_cast<UnconditionalGuard*>(g) != NULL) {
        createNopField = false;
    }
    }
    int srcSockets = socketCount(*bus, Socket::OUTPUT);
    int srcBridges = sourceBridgeCount(*bus);
    bool shortImmSupport = (bus->immediateWidth() > 0);
    multiset<int> socketCodeWidths = socketCodeWidthsForBus(
        *bus, Socket::OUTPUT);
    for (int i = 0; i < srcBridges; i++) {
        socketCodeWidths.insert(0);
    }
    if (shortImmSupport) {
        socketCodeWidths.insert(bus->immediateWidth());
    }
    // one encoding for NOP
    if (createNopField) {
        socketCodeWidths.insert(0);
    }
    multiset<Encoding> encodings;
    calculateEncodings(socketCodeWidths, true, encodings);
    // set the encodings
    set<Socket*> handledSockets;
    int nextBridge = 0;
    bool nopEncodingSet = false;
    bool immEncodingSet = !shortImmSupport;
    multiset<int>::reverse_iterator scIter = socketCodeWidths.rbegin();
    for (multiset<Encoding>::const_iterator encIter = encodings.begin();
         encIter != encodings.end(); encIter++) {
        Encoding enc = *encIter;
        int scWidth = *scIter;
        if (scWidth == 0 && !nopEncodingSet && createNopField) {
            new NOPEncoding(enc.first, enc.second, field);
            nopEncodingSet = true;
        } else if (!immEncodingSet && scWidth == bus->immediateWidth()) {
            new ImmediateEncoding(
                enc.first, enc.second, bus->immediateWidth(), field);
            immEncodingSet = true;
        } else {
            bool socketFound = false;
            // find the socket that has correct socket code width
            for (int i = 0; i < srcSockets; i++) {
                Socket& socket = BEMGenerator::socket(
                    i, *bus, Socket::OUTPUT);
                SocketCodeTable* scTable = socketCodeTable(socket);
                if (scTable == NULL && scWidth == 0 &&
                    !AssocTools::containsKey(handledSockets, &socket)) {
                    new SocketEncoding(
                        socket.name(), enc.first, enc.second, field);
                    handledSockets.insert(&socket);
                    socketFound = true;
                    break;
                } else if (scTable != NULL && scWidth == scTable->width() &&
                           !AssocTools::containsKey(
                               handledSockets, &socket)) {
                    SocketEncoding* socketEnc = new SocketEncoding(
                        socket.name(), enc.first, enc.second, field);
                    socketEnc->setSocketCodes(*scTable);
                    handledSockets.insert(&socket);
                    socketFound = true;
                    break;
                }
            }
            if (!socketFound) {
                assert(scWidth == 0);
                assert(nextBridge < srcBridges);
                Bridge& bridge = BEMGenerator::sourceBridge(
                    nextBridge, *bus);
                new BridgeEncoding(
                    bridge.name(), enc.first, enc.second, field);
                nextBridge++;
            }
        }
        scIter++;
    }
}
References assert, TTAMachine::Machine::busNavigator(), calculateEncodings(), AssocTools::containsKey(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Bus::immediateWidth(), TTAMachine::Guard::isInverted(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::Component::name(), TTAMachine::Socket::OUTPUT, SlotField::parent(), SocketEncoding::setSocketCodes(), socket(), socketCodeTable(), socketCodeWidthsForBus(), socketCount(), sourceBridge(), sourceBridgeCount(), and SocketCodeTable::width().
addExtraBits()
void BEMGenerator::addExtraBits (std::multiset< Encoding > & encodings, int bitCount) static private
Adds the given number of extra bits to the encodings in the given set.
Parameters
encodings The encodings.
bitLength The number of bits.
Definition at line 1351 of file BEMGenerator.cc.
                  {
    multiset<Encoding> newSet;
    for (multiset<Encoding>::iterator iter = encodings.begin();
         iter != encodings.end(); iter++) {
        unsigned int encoding = iter->first;
        unsigned int extraBits = iter->second;
        extraBits += bitCount;
        newSet.insert(Encoding(encoding, extraBits));
    }
    encodings.clear();
    encodings.insert(newSet.begin(), newSet.end());
}
Referenced by calculateEncodings().
addLongImmDstRegisterFields()
void BEMGenerator::addLongImmDstRegisterFields (BinaryEncoding & bem) const private
Adds the long immediate destination register fields to the given binary encoding map.
Parameters
bem The binary encoding map.
Definition at line 445 of file BEMGenerator.cc.
{
    // check how many fields is needed
    Machine::InstructionTemplateNavigator itNav =
        machine_->instructionTemplateNavigator();
    int fieldCount(0);
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        int thisRequires = 0;
        Machine::ImmediateUnitNavigator iuNav =
            machine_->immediateUnitNavigator();
        for (int i = 0; i < iuNav.count(); i++) {
            ImmediateUnit* iu = iuNav.item(i);
            if (iu->numberOfRegisters() > 1 &&
                iTemp->isOneOfDestinations(*iu)) {
                thisRequires++;
            }
        }
        if (thisRequires > fieldCount) {
            fieldCount = thisRequires;
        }
    }
    // create a vector that contains the required widths of the fields
    Machine::ImmediateUnitNavigator iuNav =
        machine_->immediateUnitNavigator();
    std::vector<int> fieldWidths(fieldCount, 0);
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        // collect the destinations units to a set
        std::set<ImmediateUnit*> dstUnits;
        for (int i = 0; i < iuNav.count(); i++) {
            ImmediateUnit* iu = iuNav.item(i);
            if (iTemp->isOneOfDestinations(*iu)) {
                dstUnits.insert(iu);
            }
        }
        // create a set containing the sizes required by all the destinations
        // of the instruction template
        std::multiset<int> requiredSizes;
        for (set<ImmediateUnit*>::const_iterator iter = dstUnits.begin();
             iter != dstUnits.end(); iter++) {
            ImmediateUnit* iu = *iter;
            if (iu->numberOfRegisters() > 1) {
                requiredSizes.insert(
                    MathTools::bitLength(iu->numberOfRegisters() - 1));
            }
        }
        // increase the values in fieldWidhts if required
        int counter(0);
        for (multiset<int>::const_reverse_iterator iter =
                 requiredSizes.rbegin();
             iter != requiredSizes.rend(); iter++) {
            if (fieldWidths[counter] < *iter) {
                fieldWidths[counter] = *iter;
            }
            counter++;
        }
    }
    // create the fields
    typedef std::pair<InstructionTemplate*, ImmediateUnit*> ImmDstMapping;
    std::set<ImmDstMapping> mappedDestinations;
    for (int i = fieldCount-1; i >= 0; i--) {
        unsigned int fieldWidth = fieldWidths[i];
        LImmDstRegisterField* newField = new LImmDstRegisterField(
            fieldWidth, bem);
        for (int i = 0; i < itNav.count(); i++) {
            InstructionTemplate* iTemp = itNav.item(i);
            for (int i = 0; i < iuNav.count(); i++) {
                ImmediateUnit* iu = iuNav.item(i);
                if (iTemp->isOneOfDestinations(*iu) &&
                    iu->numberOfRegisters() > 1 &&
                    static_cast<unsigned int>(
                        MathTools::bitLength(iu->numberOfRegisters() - 1))
                    <= fieldWidth &&
                    !AssocTools::containsKey(
                        mappedDestinations,
                        ImmDstMapping(iTemp, iu))) {
                    newField->addDestination(iTemp->name(), iu->name());
                    mappedDestinations.insert(ImmDstMapping(iTemp, iu));
                }
            }
        }
    }
}
References LImmDstRegisterField::addDestination(), MathTools::bitLength(), AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::InstructionTemplate::isOneOfDestinations(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), and TTAMachine::BaseRegisterFile::numberOfRegisters().
Referenced by addTopLevelFields().
addPortCodes()
void BEMGenerator::addPortCodes (SocketCodeTable & table, const TTAMachine::Socket & socket) const private
Adds the port codes to the given socket code table.
Parameters
table The socket code table.
socket The socket that will refer to the table.
Definition at line 969 of file BEMGenerator.cc.
{
    // create a set of register index widths for each port code
    multiset<int> indexWidths;
    for (int i = 0; i < socket.portCount(); i++) {
        Port* port = socket.port(i);
        Unit* parentUnit = port->parentUnit();
        BaseRegisterFile* rfParent = dynamic_cast<BaseRegisterFile*>(
            parentUnit);
        FunctionUnit* fuParent = dynamic_cast<FunctionUnit*>(parentUnit);
        if (fuParent != NULL) {
            int encodingsNeeded(0);
            if (dynamic_cast<BaseFUPort*>(port)->isOpcodeSetting() &&
                socket.direction() == Socket::INPUT) {
                encodingsNeeded = fuParent->operationCount();
            } else {
                encodingsNeeded = 1;
            }
            for (int i = 0; i < encodingsNeeded; i++) {
                indexWidths.insert(0);
            }
        } else {
            assert(rfParent != NULL);
            unsigned int indexWidth = requiredIndexWidth(*rfParent);
            indexWidths.insert(indexWidth);
        }
    }
    // calculate port IDs
    multiset<Encoding> encodings;
    calculateEncodings(indexWidths, true, encodings);
    // set the encodings
    if (encodings.size() == 0) {
        assert(socket.portCount() == 1);
        Port* port = socket.port(0);
        ImmediateUnit* iu = dynamic_cast<ImmediateUnit*>(port->parentUnit());
        RegisterFile* rf = dynamic_cast<RegisterFile*>(port->parentUnit());
        assert(iu != NULL || rf != NULL);
        // iu must be first because iu is inherited from rf
        if (iu != NULL) {
            new IUPortCode(iu->name(), requiredIndexWidth(*iu), table);
        } else {
            new RFPortCode(rf->name(), requiredIndexWidth(*rf), table);
        }
    } else {
        set<Port*> handledPorts;
        multiset<int>::const_reverse_iterator indexWidthIter =
            indexWidths.rbegin();
        for (multiset<Encoding>::const_iterator encIter = encodings.begin();
             encIter != encodings.end();) {
            int indexWidth = *indexWidthIter;
            Encoding enc = *encIter;
            for (int portIndex = 0; portIndex < socket.portCount();
                 portIndex++) {
                Port* port = socket.port(portIndex);
                if (AssocTools::containsKey(handledPorts, port)) {
                    continue;
                }
                RegisterFile* rfParent = dynamic_cast<RegisterFile*>(
                    port->parentUnit());
                ImmediateUnit* iuParent = dynamic_cast<ImmediateUnit*>(
                    port->parentUnit());
                FunctionUnit* fuParent = dynamic_cast<FunctionUnit*>(
                    port->parentUnit());
                // iu must be first because iu is inherited from rf
                if (iuParent != NULL) {
                    int reqIndexWidth = requiredIndexWidth(*iuParent);
                    if (reqIndexWidth == indexWidth) {
                        new IUPortCode(
                            iuParent->name(), enc.first, enc.second,
                            reqIndexWidth, table);
                        indexWidthIter++;
                        encIter++;
                        handledPorts.insert(port);
                        break;
                    }
                } else if (rfParent != NULL) {
                    int reqIndexWidth = requiredIndexWidth(*rfParent);
                    if (reqIndexWidth == indexWidth) {
                        new RFPortCode(
                            rfParent->name(), enc.first, enc.second,
                            reqIndexWidth, table);
                        indexWidthIter++;
                        encIter++;
                        handledPorts.insert(port);
                        break;
                    }
                } else {
                    if (indexWidth != 0) {
                        continue;
                    }
                    assert(fuParent != NULL);
                    BaseFUPort* fuPort = dynamic_cast<BaseFUPort*>(port);
                    assert(fuPort != NULL);
                    if (fuPort->isOpcodeSetting()) {
                        // map<operation name, operation index in FU>
                        map<string,int> opcodeSet;
                        assert(*indexWidthIter == 0);
                        // operation indeces are numbered according to the
                        // alphabetical order of opertations
                        for (int opIndex = 0;
                             opIndex < fuParent->operationCount();
                             opIndex++) {
                            opcodeSet.insert(
                                make_pair(
                                    fuParent->operation(opIndex)->name(),
                                    opIndex));
                        }
                        for (map<string,int>::iterator
                                 iter = opcodeSet.begin();
                             iter != opcodeSet.end(); iter++) {
                            Encoding enc = *encIter;
                            HWOperation* operation =
                                fuParent->operation(iter->second);
                            assert(operation->name() == iter->first);
                            new FUPortCode(
                                fuParent->name(), fuPort->name(),
                                operation->name(), enc.first, enc.second,
                                table);
                            indexWidthIter++;
                            encIter++;
                        }
                    } else {
                        new FUPortCode(
                            fuParent->name(), fuPort->name(), enc.first,
                            enc.second, table);
                        indexWidthIter++;
                        encIter++;
                    }
                    handledPorts.insert(port);
                    break;
                }
            }
        }
    }
}
References assert, calculateEncodings(), AssocTools::containsKey(), TTAMachine::Socket::direction(), TTAMachine::Socket::INPUT, TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), requiredIndexWidth(), and socket().
Referenced by addSocketCodeTables().
addRiscvFormat()
void BEMGenerator::addRiscvFormat (TTAMachine::OperationTriggeredFormat * format, BinaryEncoding & bem, unsigned & amountOfRCustomOps, unsigned & amountOfR3RCustomOps) const private
Adds a RISC-V format to the binary encoding map
Parameters
format The operation triggered format
bem The binary encoding
Definition at line 203 of file BEMGenerator.cc.
{
    std::string name = format->name();
    InstructionFormat* instrFormat = new InstructionFormat(name, bem);
    const unsigned OPC_CUSTOM_0 = 0b0001011;
    const unsigned OPC_CUSTOM_1 = 0b0101011;
    if (name == RISCVFields::RISCV_R_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* rs2 =
            new OperationTriggeredEncoding(std::string("rs2"), *instrFormat);
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*rs2, 0, 20, 5);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        new OperationTriggeredField(*opcode, 2, 25, 7);
        // Reserve first few encodings for fixed special case
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVRTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVRTypeOperations.at(op));
            } else {
                unsigned int customEncoding = OPC_CUSTOM_0;
                customEncoding += (amountOfRCustomOps << 7);
                amountOfRCustomOps++;
                // 10 bit encoding for operation
                assert(amountOfRCustomOps < 1024);
                instrFormat->addOperation(op, customEncoding);
            }
        }
    } else if (name == RISCVFields::RISCV_I_TYPE_NAME) {
        // TODO: shift operations use immediate bits for funct code in this
        //  format
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* imm =
            new OperationTriggeredEncoding(std::string("imm"), *instrFormat);
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*imm, 0, 25, 12);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        new OperationTriggeredField(*opcode, 2, 25, 7);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVITypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVITypeOperations.at(op));
            } else {
                assert(false);
            }
        }
    } else if (name == RISCVFields::RISCV_S_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* imm =
            new OperationTriggeredEncoding(std::string("imm"), *instrFormat);
        OperationTriggeredEncoding* rs2 =
            new OperationTriggeredEncoding(std::string("rs2"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*rs2, 0, 20, 5);
        new OperationTriggeredField(*imm, 0, 7, 5);
        new OperationTriggeredField(*imm, 1, 25, 7);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVSTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVSTypeOperations.at(op));
            } else {
                assert(false);
            }
        }
    } else if (name == RISCVFields::RISCV_B_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* imm =
            new OperationTriggeredEncoding(std::string("imm"), *instrFormat);
        OperationTriggeredEncoding* rs2 =
            new OperationTriggeredEncoding(std::string("rs2"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*rs2, 0, 20, 5);
        new OperationTriggeredField(*imm, 0, 8, 4);
        new OperationTriggeredField(*imm, 1, 25, 6);
        new OperationTriggeredField(*imm, 2, 11, 1);
        new OperationTriggeredField(*imm, 3, 31, 1);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVBTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVBTypeOperations.at(op));
            } else {
                assert(false);
            }
        }
    } else if (name == RISCVFields::RISCV_U_TYPE_NAME) {
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        OperationTriggeredEncoding* imm =
            new OperationTriggeredEncoding(std::string("imm"), *instrFormat);
        new OperationTriggeredField(*imm, 0, 12, 20);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVUTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVUTypeOperations.at(op));
            } else {
                assert(false);
            }
        }
    } else if (name == RISCVFields::RISCV_J_TYPE_NAME) {
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        OperationTriggeredEncoding* imm =
            new OperationTriggeredEncoding(std::string("imm"), *instrFormat);
        new OperationTriggeredField(*imm, 0, 20, 10);
        new OperationTriggeredField(*imm, 1, 20, 1);
        new OperationTriggeredField(*imm, 2, 15, 8);
        new OperationTriggeredField(*imm, 3, 31, 1);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVJTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVJTypeOperations.at(op));
            } else {
                assert(false);
            }
        }
        // This is a custom format for unary operations
        // but it still uses R-format with rs2 = x0
    } else if (name == RISCVFields::RISCV_R1R_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        new OperationTriggeredField(*opcode, 2, 25, 7);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            unsigned int customEncoding = OPC_CUSTOM_0;
            customEncoding += (amountOfRCustomOps << 7);
            amountOfRCustomOps++;
            // 10 bit encoding for operation
            assert(amountOfRCustomOps < 1024);
            instrFormat->addOperation(op, customEncoding);
        }
        // unary without output, stdout for example
    } else if (name == RISCVFields::RISCV_R1_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        new OperationTriggeredField(*opcode, 2, 25, 7);
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            unsigned int customEncoding = OPC_CUSTOM_0;
            // Reserve this for printing
            if (TCEString(op).lower() != "stdout") {
                customEncoding += (amountOfRCustomOps << 7);
                amountOfRCustomOps++;
            }
            // 10 bit encoding for operation
            assert(amountOfRCustomOps < 1024);
            instrFormat->addOperation(op, customEncoding);
        }
    } else if (name == RISCVFields::RISCV_R3R_TYPE_NAME) {
        OperationTriggeredEncoding* rs1 =
            new OperationTriggeredEncoding(std::string("rs1"), *instrFormat);
        OperationTriggeredEncoding* rs2 =
            new OperationTriggeredEncoding(std::string("rs2"), *instrFormat);
        OperationTriggeredEncoding* rs3 =
            new OperationTriggeredEncoding(std::string("rs3"), *instrFormat);
        OperationTriggeredEncoding* rd =
            new OperationTriggeredEncoding(std::string("rd"), *instrFormat);
        new OperationTriggeredField(*rs1, 0, 15, 5);
        new OperationTriggeredField(*rs2, 0, 20, 5);
        new OperationTriggeredField(*rs3, 0, 27, 5);
        new OperationTriggeredField(*rd, 0, 7, 5);
        OperationTriggeredEncoding* opcode = new OperationTriggeredEncoding(
            std::string("opcode"), *instrFormat);
        new OperationTriggeredField(*opcode, 0, 0, 7);
        new OperationTriggeredField(*opcode, 1, 12, 3);
        new OperationTriggeredField(*opcode, 2, 25, 2);
        // Reserve first few encodings for fixed special case
        for (int i = 0; i < format->operationCount(); i++) {
            const std::string op = format->operationAtIndex(i);
            if (MapTools::containsKey(RISCVFields::RISCVRTypeOperations, op)) {
                instrFormat->addOperation(op, RISCVFields::RISCVRTypeOperations.at(op));
            } else {
                unsigned int customEncoding = OPC_CUSTOM_1;
                customEncoding += (amountOfR3RCustomOps << 7);
                amountOfR3RCustomOps++;
                assert(amountOfR3RCustomOps < 32);
                instrFormat->addOperation(op, customEncoding);
            }
        }
    }  else {
        // TODO: Throw some meaniningful exception here
        assert(false);
    }
}
References InstructionFormat::addOperation(), assert, MapTools::containsKey(), TTAMachine::Component::name(), TTAMachine::OperationTriggeredFormat::operationAtIndex(), TTAMachine::OperationTriggeredFormat::operationCount(), RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, RISCVFields::RISCV_U_TYPE_NAME, RISCVFields::RISCVBTypeOperations, RISCVFields::RISCVITypeOperations, RISCVFields::RISCVJTypeOperations, RISCVFields::RISCVRTypeOperations, RISCVFields::RISCVSTypeOperations, and RISCVFields::RISCVUTypeOperations.
Referenced by addTopLevelFields().
addSocketCodeTables()
void BEMGenerator::addSocketCodeTables (BinaryEncoding & bem) private
Adds the socket code tables to the given binary encoding map.
Parameters
bem The binary encoding map.
Definition at line 125 of file BEMGenerator.cc.
{
    Machine::SocketNavigator socketNav = machine_->socketNavigator();
    for (int i = 0; i < socketNav.count(); i++) {
        Socket* socket = socketNav.item(i);
        if (needsSocketCodeTable(*socket)) {
            SocketCodeTable* suitable = suitableSocketCodeTable(*socket);
            if (suitable != NULL) {
                assignSocketCodeTable(socket, suitable);
            } else {
                SocketCodeTable* table =
                    new SocketCodeTable(socket->name(), bem);
                addPortCodes(*table, *socket);
                assignSocketCodeTable(socket, table);
            }
        }
    }
}
References addPortCodes(), assignSocketCodeTable(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), needsSocketCodeTable(), socket(), TTAMachine::Machine::socketNavigator(), and suitableSocketCodeTable().
Referenced by generate().
addSubfields()
void BEMGenerator::addSubfields (MoveSlot & slot) const private
Adds subfields to the given move slot.
Parameters
slot The move slot.
Definition at line 544 of file BEMGenerator.cc.
{
    string busName = slot.name();
    Machine::BusNavigator busNav = machine_->busNavigator();
    assert(busNav.hasItem(busName));
    Bus* bus = busNav.item(busName);
    DestinationField* dField = new DestinationField(
        BinaryEncoding::LEFT, slot);
    SourceField* sField = new SourceField(BinaryEncoding::LEFT, slot);
    GuardField* gField = NULL;
    addEncodings(*dField); // destination field
    addEncodings(*sField); // source field
    // we need guard field only if we have >1 guard.
    if (bus->guardCount() > 1) {
        gField = new GuardField(slot);
        addEncodings(*gField); // guard field
    }
    // adds extra bits to guard field (any field is probably ok) if needed.
    // extra bits added so that long immediate fits to the slot.
    int longImmWidth = maxLongImmSlotWidth(slot);
    if (longImmWidth > slot.width()) {
        // if no guard field, create it so that it can be enlarged.
        if (gField == NULL) {
            gField = new GuardField(slot);
            addEncodings(*gField); // guard field
        }
        gField->setExtraBits((longImmWidth - slot.width()) +
            gField->extraBits());
    }
}
References addEncodings(), assert, TTAMachine::Machine::busNavigator(), InstructionField::extraBits(), TTAMachine::Bus::guardCount(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::Navigator< ComponentType >::item(), BinaryEncoding::LEFT, machine_, maxLongImmSlotWidth(), MoveSlot::name(), InstructionField::setExtraBits(), and MoveSlot::width().
Referenced by generate().
addTopLevelFields()
void BEMGenerator::addTopLevelFields (BinaryEncoding & bem) const private
Adds the top-level fields to the given binary encoding map.
Parameters
bem The binary encoding to be modified.
Definition at line 150 of file BEMGenerator.cc.
{
    // add immediate slots
    Machine::ImmediateSlotNavigator isNav =
        machine_->immediateSlotNavigator();
    for (int i = 0; i < isNav.count(); i++) {
        ImmediateSlot* slot = isNav.item(i);
        int width = slot->width();
        if (width > 0) {
            new ImmediateSlotField(slot->name(), width, bem);
        }
    }
    // add move slots
    Machine::BusNavigator busNav = machine_->busNavigator();
    for (int i = 0; i < busNav.count(); i++) {
        Bus* bus = busNav.item(i);
        new MoveSlot(bus->name(), bem);
    }
    // add long immediate destination register fields
    addLongImmDstRegisterFields(bem);
    // add long immediate control field
    Machine::InstructionTemplateNavigator itNav =
        machine_->instructionTemplateNavigator();
    if (itNav.count() > 1) {
        ImmediateControlField* field = new ImmediateControlField(bem);
        addEncodings(*field);
    }
    unsigned amountOfRCustomOps = 0;
    unsigned amountOfR3RCustomOps = 0;
    Machine::OperationTriggeredFormatNavigator fNav =
        machine_->operationTriggeredFormatNavigator();
    // For CVX-IF, make sure these are iterated in the correct order.
    for (int i = 0; i < fNav.count(); i++) {
        OperationTriggeredFormat* fTemp = fNav.item(i);
        addRiscvFormat(fTemp, bem, amountOfRCustomOps, amountOfR3RCustomOps);
    }
}
References addEncodings(), addLongImmDstRegisterFields(), addRiscvFormat(), TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), TTAMachine::Machine::operationTriggeredFormatNavigator(), and TTAMachine::ImmediateSlot::width().
Referenced by generate().
assignSocketCodeTable()
void BEMGenerator::assignSocketCodeTable (const TTAMachine::Socket * socket, SocketCodeTable * table) private
Assigns the given socket code table for the given socket.
Parameters
socket The socket.
table The socket code table.
Definition at line 852 of file BEMGenerator.cc.
{
    assert(!MapTools::containsKey(scTableMap_, socket));
    scTableMap_.insert(pair<const Socket*, SocketCodeTable*>(socket, table));
}
References assert, MapTools::containsKey(), scTableMap_, and socket().
Referenced by addSocketCodeTables().
calculateEncodings()
void BEMGenerator::calculateEncodings (const std::multiset< int > & oppositeFieldWidths, bool alignment, std::multiset< Encoding > & encodings) static private
Calculates unambiguous encodings when the encodings have opposite fields of the given widths.
Minimizes both the total width of the field and the width of the encodings. Currently supports only left aligment of encodings.
Parameters
oppositeFieldWidths Widths of the opposite fields.
alignment Tells whether the encodings are aligned to left (true) or right (false).
encoding The encodings are added here.
Definition at line 1279 of file BEMGenerator.cc.
{
    if (oppositeFieldWidths.size() < 1) {
        return;
    }
    assert(alignment);
    unsigned int remainder = 0;
    unsigned int encodingsLeft = oppositeFieldWidths.size();
    unsigned int prevEncoding = 0;
    unsigned int nextEncoding = 0;
    unsigned int prevOppositeFieldWidth = 0;
    for (multiset<int>::reverse_iterator iter = oppositeFieldWidths.rbegin();
         iter != oppositeFieldWidths.rend(); iter++) {
        unsigned int oppositeFieldWidth = *iter;
        if (iter == oppositeFieldWidths.rbegin()) {
            nextEncoding = 0;
            encodings.insert(Encoding(nextEncoding, 0));
            remainder = 1;
        } else {
            nextEncoding = prevEncoding + 1;
            if (MathTools::bitLength(nextEncoding) >
                MathTools::bitLength(prevEncoding)) {
                addExtraBits(encodings, 1);
                unsigned int setEncodingCount =
                    oppositeFieldWidths.size() - encodingsLeft;
                remainder = (remainder << 1) + setEncodingCount;
            }
            if (oppositeFieldWidth == prevOppositeFieldWidth) {
                encodings.insert(Encoding(nextEncoding, 0));
            } else {
                assert(oppositeFieldWidth < prevOppositeFieldWidth);
                unsigned int freeBits =
                    prevOppositeFieldWidth - oppositeFieldWidth;
                // calculate the number of bits the encoding has to be
                // expanded
                unsigned int expansion = 0;
                while (remainder << expansion < encodingsLeft) {
                    if (expansion < freeBits) {
                        expansion++;
                    } else {
                        break;
                    }
                }
                nextEncoding = nextEncoding << expansion;
                encodings.insert(Encoding(nextEncoding, 0));
                remainder = remainder << expansion;
            }
        }
        prevOppositeFieldWidth = oppositeFieldWidth;
        encodingsLeft--;
        remainder--;
        prevEncoding = nextEncoding;
    }
    assert(encodings.size() == oppositeFieldWidths.size());
}
References addExtraBits(), assert, and MathTools::bitLength().
Referenced by addEncodings(), addEncodings(), and addPortCodes().
generate()
BinaryEncoding * BEMGenerator::generate ()
Generates the binary encoding map.
Returns
The newly created binary encoding map.
Definition at line 104 of file BEMGenerator.cc.
                       {
    BinaryEncoding* bem = new BinaryEncoding();
    addSocketCodeTables(*bem);
    addTopLevelFields(*bem);
    for (int i = 0; i < bem->moveSlotCount(); i++) {
        MoveSlot& slot = bem->moveSlot(i);
         addSubfields(slot);
    }
    return bem;
}
References addSocketCodeTables(), addSubfields(), addTopLevelFields(), BinaryEncoding::moveSlot(), and BinaryEncoding::moveSlotCount().
Referenced by ProGe::ProGeUI::generateProcessor(), initializeMachine(), llvm::LLVMTCERISCVIntrinsicsLowering::LLVMTCERISCVIntrinsicsLowering(), ProcessorImplementationWindow::loadICDecoderPlugin(), RemoteController::loadIMemImage(), main(), GenerateProcessorDialog::onOK(), RISCVTDGen::RISCVTDGen(), and MachineCanvas::updateMachine().
hasUnconditionalGuard()
bool BEMGenerator::hasUnconditionalGuard (const TTAMachine::Bus & bus) static private
Tells whether the given bus has an unconditional guard.
Parameters
bus The bus.
Returns
True if the bus has an unconditional guard, otherwise false.
Definition at line 1238 of file BEMGenerator.cc.
{
    for (int i = 0; i < bus.guardCount(); i++) {
        Guard* guard = bus.guard(i);
        if (dynamic_cast<UnconditionalGuard*>(guard) != NULL) {
            return true;
        }
    }
    return false;
}
References TTAMachine::Bus::guard(), and TTAMachine::Bus::guardCount().
haveEqualConnections()
bool BEMGenerator::haveEqualConnections (const TTAMachine::Socket & socket1, const TTAMachine::Socket & socket2) static private
Checks whether the given sockets have equal port connections.
Parameters
socket1 The first socket.
socket2 The second socket.
Returns
True if the sockets have equal port connections, otherwise false.
Definition at line 1149 of file BEMGenerator.cc.
{
    std::set<Port*> socket1Ports;
    std::set<Port*> socket2Ports;
    for (int i = 0; i < socket1.portCount(); i++) {
        socket1Ports.insert(socket1.port(i));
    }
    for (int i = 0; i < socket2.portCount(); i++) {
        socket2Ports.insert(socket2.port(i));
    }
    if (socket1Ports == socket2Ports) {
        return true;
    } else {
        return false;
    }
}
References TTAMachine::Socket::port(), and TTAMachine::Socket::portCount().
Referenced by suitableSocketCodeTable().
maxLongImmSlotWidth()
unsigned int BEMGenerator::maxLongImmSlotWidth (const MoveSlot & slot) const private
Returns the width of the longest long immediate template being encoded in a slot given as parameter.
Parameters
slot Move slot where to check if it's used to store long immediates.
Returns
Width of the longest long immediate width stored in a move slot.
Definition at line 1377 of file BEMGenerator.cc.
{
    Machine::InstructionTemplateNavigator itNav =
        machine_->instructionTemplateNavigator();
    int maxWidth = 0;
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        for (int i = 0; i < iTemp->slotCount(); ++i) {
            if (slot.name() == iTemp->slot(i)->slot() &&
                maxWidth < iTemp->slot(i)->width()) {
                maxWidth = iTemp->slot(i)->width();
            }
        }
    }
    return maxWidth;
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::TemplateSlot::slot(), TTAMachine::InstructionTemplate::slot(), TTAMachine::InstructionTemplate::slotCount(), and TTAMachine::TemplateSlot::width().
Referenced by addSubfields().
needsSocketCodeTable()
bool BEMGenerator::needsSocketCodeTable (const TTAMachine::Socket & socket) static private
Tells whether the given socket needs a socket code table.
Returns
True if the socket needs a socket code table, otherwise false.
Definition at line 933 of file BEMGenerator.cc.
{
    if (socket.portCount() > 1) {
        return true;
    } else if (socket.portCount() == 1) {
        // socket code table is needed if the port is opcode setting with
        // more than one possible opcode or if the port is a data port of
        // register file with more than one register
        Port* port = socket.port(0);
        FUPort* fuPort = dynamic_cast<FUPort*>(port);
        RFPort* rfPort = dynamic_cast<RFPort*>(port);
        if (fuPort != NULL && fuPort->isOpcodeSetting() &&
            fuPort->parentUnit()->operationCount() > 1) {
            return true;
        } else if (rfPort != NULL &&
                   rfPort->parentUnit()->numberOfRegisters() > 1) {
            return true;
        } else {
            return false;
        }
    } else {
        return false;
    }
}
References TTAMachine::FUPort::isOpcodeSetting(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::RFPort::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), and socket().
Referenced by addSocketCodeTables().
requiredIndexWidth()
int BEMGenerator::requiredIndexWidth (const TTAMachine::BaseRegisterFile & regFile) static private
Returns the number of bits needed to identify a register in the given register file.
Parameters
regFile The register file.
Returns
The number of bits needed for register index.
Definition at line 1257 of file BEMGenerator.cc.
{
    if (regFile.numberOfRegisters() <= 1) {
        return 0;
    } else {
        return MathTools::bitLength(regFile.numberOfRegisters() - 1);
    }
}
References MathTools::bitLength(), and TTAMachine::BaseRegisterFile::numberOfRegisters().
Referenced by addPortCodes().
socket()
Socket & BEMGenerator::socket (int index, const TTAMachine::Bus & bus, TTAMachine::Socket::Direction direction) static private
By the given index, returns a socket that is attached to the given bus and has the given direction.
Parameters
index The index.
bus The bus.
direction Direction of the sockets being returned.
Returns
The socket.
Definition at line 899 of file BEMGenerator.cc.
{
    typedef std::vector<Socket*> SocketTable;
    assert(index >= 0);
    SocketTable connectedSockets;
    for (int i = 0; i < bus.segmentCount(); i++) {
        Segment* segment = bus.segment(i);
        for (int i = 0; i < segment->connectionCount(); i++) {
            Socket* socket = segment->connection(i);
            if (socket->direction() == direction) {
                if (!ContainerTools::containsValue(
                        connectedSockets, socket)) {
                    connectedSockets.push_back(socket);
                }
            }
        }
    }
    assert(connectedSockets.size() > static_cast<size_t>(index));
    return *connectedSockets[index];
}
References assert, TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), ContainerTools::containsValue(), TTAMachine::Socket::direction(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), and socket().
Referenced by addEncodings(), addEncodings(), addPortCodes(), addSocketCodeTables(), assignSocketCodeTable(), needsSocketCodeTable(), socket(), socketCodeTable(), socketCodeWidthsForBus(), socketCount(), and suitableSocketCodeTable().
socketCodeTable()
SocketCodeTable * BEMGenerator::socketCodeTable (const TTAMachine::Socket & socket) const private
Returns the socket code table that is assigned to the given socket.
Parameters
socket The socket.
Returns
The socket code table or NULL if no socket code table is assigned to the given socket.
Definition at line 814 of file BEMGenerator.cc.
{
    if (MapTools::containsKey(scTableMap_, &socket)) {
        return MapTools::valueForKey<SocketCodeTable*>(scTableMap_, &socket);
    } else {
        return NULL;
    }
}
References MapTools::containsKey(), MapTools::keyForValue(), scTableMap_, and socket().
Referenced by addEncodings(), addEncodings(), and socketCodeWidthsForBus().
socketCodeWidthsForBus()
std::multiset< int > BEMGenerator::socketCodeWidthsForBus (const TTAMachine::Bus & bus, TTAMachine::Socket::Direction socketDir) const private
Returns a multiset containing the socket code widths for sockets of the given direction that are connected to the given bus.
Parameters
bus The bus.
socket The direction.
Returns
The multiset.
Definition at line 1121 of file BEMGenerator.cc.
{
    std::multiset<int> socketCodeWidths;
    int socketCount = BEMGenerator::socketCount(bus, socketDir);
    for (int i = 0; i < socketCount; i++) {
        Socket& socket = BEMGenerator::socket(i, bus, socketDir);
        SocketCodeTable* scTable = socketCodeTable(socket);
        if (scTable == NULL) {
            socketCodeWidths.insert(0);
        } else {
            socketCodeWidths.insert(scTable->width());
        }
    }
    return socketCodeWidths;
}
References socket(), socketCodeTable(), socketCount(), and SocketCodeTable::width().
Referenced by addEncodings(), and addEncodings().
socketCount()
int BEMGenerator::socketCount (const TTAMachine::Bus & bus, TTAMachine::Socket::Direction direction) static private
Returns the number of sockets of the given direction connected to the given bus.
Parameters
bus The bus.
direction The direction
Returns
The number of sockets.
Definition at line 870 of file BEMGenerator.cc.
{
    typedef std::set<Socket*> SocketSet;
    SocketSet sockets;
    for (int i = 0; i < bus.segmentCount(); i++) {
        Segment* segment = bus.segment(i);
        for (int i = 0; i < segment->connectionCount(); i++) {
            Socket* socket = segment->connection(i);
            if (socket->direction() == direction) {
                sockets.insert(socket);
            }
        }
    }
    return sockets.size();
}
References TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), TTAMachine::Socket::direction(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), and socket().
Referenced by addEncodings(), addEncodings(), and socketCodeWidthsForBus().
sourceBridge()
Bridge & BEMGenerator::sourceBridge (int index, const TTAMachine::Bus & bus) static private
By the given index returns a source bridge for the given bus.
Parameters
index The index (0 or 1).
bus The bus.
Definition at line 1206 of file BEMGenerator.cc.
{
    Machine* mach = bus.machine();
    assert(mach != NULL);
    Machine::BridgeNavigator bridgeNav = mach->bridgeNavigator();
    int count(0);
    for (int i = 0; i < bridgeNav.count(); i++) {
        Bridge* bridge = bridgeNav.item(i);
        if (bridge->destinationBus() == &bus) {
            if (count == index) {
                return *bridge;
            } else {
                count++;
            }
        }
    }
    assert(false);
    // dummy return
    return *bridgeNav.item(0);
}
References assert, TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bridge::destinationBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), and TTAMachine::Component::machine().
Referenced by addEncodings().
sourceBridgeCount()
int BEMGenerator::sourceBridgeCount (const TTAMachine::Bus & bus) static private
Tells how many source bridges the given bus has.
Parameters
bus The bus.
Returns
The number of source bridges.
Definition at line 1179 of file BEMGenerator.cc.
{
    Machine* mach = bus.machine();
    assert(mach != NULL);
    Machine::BridgeNavigator bridgeNav = mach->bridgeNavigator();
    int count(0);
    for (int i = 0; i < bridgeNav.count(); i++) {
        Bridge* bridge = bridgeNav.item(i);
        if (bridge->destinationBus() == &bus) {
            count++;
        }
    }
    assert(count <= 2);
    return count;
}
References assert, TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bridge::destinationBus(), TTAMachine::Machine::Navigator< ComponentType >::item(), and TTAMachine::Component::machine().
Referenced by addEncodings().
suitableSocketCodeTable()
SocketCodeTable * BEMGenerator::suitableSocketCodeTable (const TTAMachine::Socket & socket) const private
Finds a suitable socket code table from the socket code table map for the given socket.
Returns NULL if there is no suitable socket code table.
Parameters
socket The socket.
Returns
The socket code table or NULL.
Definition at line 833 of file BEMGenerator.cc.
{
    for (SCTableMap::const_iterator iter = scTableMap_.begin();
         iter != scTableMap_.end(); iter++) {
        const Socket* toCheck = (*iter).first;
        if (haveEqualConnections(socket, *toCheck)) {
            return (*iter).second;
        }
    }
    return NULL;
}
References haveEqualConnections(), scTableMap_, and socket().
Referenced by addSocketCodeTables().
Member Data Documentation
machine_
const TTAMachine::Machine* BEMGenerator::machine_ private
The machine for which the BEM is generated.
Definition at line 129 of file BEMGenerator.hh.
Referenced by addEncodings(), addEncodings(), addEncodings(), addEncodings(), addLongImmDstRegisterFields(), addSocketCodeTables(), addSubfields(), addTopLevelFields(), and maxLongImmSlotWidth().
scTableMap_
SCTableMap BEMGenerator::scTableMap_ private
A map which tells which socket code table belongs to a socket.
Definition at line 131 of file BEMGenerator.hh.
Referenced by assignSocketCodeTable(), socketCodeTable(), and suitableSocketCodeTable().
The documentation for this class was generated from the following files:
BEMGenerator.hh
BEMGenerator.cc