OpenASIP: FitWidthCmd Class Reference
FitWidthCmd Class Reference
#include <FitWidthCmd.hh>
Public Member Functions
FitWidthCmd ()
virtual ~FitWidthCmd ()
virtual bool Do ()
virtual int id () const
virtual FitWidthCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for zooming the canvas to fit the window width.
Definition at line 40 of file FitWidthCmd.hh.
Constructor & Destructor Documentation
FitWidthCmd()
FitWidthCmd::FitWidthCmd ()
The Constructor.
Definition at line 47 of file FitWidthCmd.cc.
                        :
    EditorCommand(ProDeConstants::CMD_NAME_ZOOM_FIT_WID) {
}
Referenced by create().
~FitWidthCmd()
FitWidthCmd::~FitWidthCmd () virtual
The Destructor.
Definition at line 56 of file FitWidthCmd.cc.
{
}
Member Function Documentation
create()
FitWidthCmd * FitWidthCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 105 of file FitWidthCmd.cc.
{
    return new FitWidthCmd();
}
References FitWidthCmd().
Do()
bool FitWidthCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 67 of file FitWidthCmd.cc.
                {
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    wxSize figureSize = canvas->getFigureSize();
    wxSize cSize = canvas->GetSize();
    // Decrease zoom factor from maximum until the figure width is smaller
    // than the window width.
    double factor = CanvasConstants::MAX_ZOOM_FACTOR;
    while (cSize.GetWidth() < factor*figureSize.GetWidth()) {
        factor = factor - CanvasConstants::AUTOZOOM_STEP;
    }
    canvas->setZoomFactor(factor);
    return true;
}
References CanvasConstants::AUTOZOOM_STEP, MDFView::canvas(), MachineCanvas::getFigureSize(), CanvasConstants::MAX_ZOOM_FACTOR, MachineCanvas::setZoomFactor(), and EditorCommand::view().
icon()
string FitWidthCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 116 of file FitWidthCmd.cc.
{
    return ProDeConstants::CMD_ICON_ZOOM_FIT_WID;
}
References ProDeConstants::CMD_ICON_ZOOM_FIT_WID.
id()
int FitWidthCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 94 of file FitWidthCmd.cc.
                      {
    return ProDeConstants::COMMAND_ZOOM_FIT_WID;
}
References ProDeConstants::COMMAND_ZOOM_FIT_WID.
isEnabled()
bool FitWidthCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 140 of file FitWidthCmd.cc.
                       {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string FitWidthCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 127 of file FitWidthCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ZOOM_FIT_WID;
}
References ProDeConstants::CMD_SNAME_ZOOM_FIT_WID.
The documentation for this class was generated from the following files:
FitWidthCmd.hh
FitWidthCmd.cc