OpenASIP: HDLGenerator::Parameter Class Reference
HDLGenerator::Parameter Class Reference
#include <HDLGenerator.hh>
Public Member Functions
Parameter (std::string name, int value=-1)
Parameter (std::string name, std::string value)
Width width () final
std::string strValue ()
void declare (std::ostream &stream, Language lang, int level=0)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang, int indent)
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
int value_
std::string strValue_
Detailed Description
Generic/parameter.
Definition at line 216 of file HDLGenerator.hh.
Constructor & Destructor Documentation
Parameter() [1/2]
HDLGenerator::Parameter::Parameter (std::string name, int value = -1) inline
Definition at line 218 of file HDLGenerator.hh.
            : Generatable(name), value_(value) {}
Parameter() [2/2]
HDLGenerator::Parameter::Parameter (std::string name, std::string value) inline
Definition at line 220 of file HDLGenerator.hh.
            : Generatable(name), value_(-1), strValue_(value) {}
Member Function Documentation
declare()
void HDLGenerator::Parameter::declare (std::ostream & stream, Language lang, int level = 0) inline
Definition at line 226 of file HDLGenerator.hh.
{
            stream << StringTools::indent(level);
            if (lang == Language::VHDL) {
                 stream << name() << " : integer";
            } else if (lang == Language::Verilog) {
                stream << "parameter integer " << name();
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References StringTools::indent(), HDLGenerator::Generatable::name(), HDLGenerator::Verilog, and HDLGenerator::VHDL.
strValue()
std::string HDLGenerator::Parameter::strValue () inline
Definition at line 224 of file HDLGenerator.hh.
{ return strValue_; }
References strValue_.
width()
Width HDLGenerator::Parameter::width () inline final virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 223 of file HDLGenerator.hh.
{ return {name(), value_}; }
References HDLGenerator::Generatable::name(), and value_.
Member Data Documentation
strValue_
std::string HDLGenerator::Parameter::strValue_ private
Definition at line 239 of file HDLGenerator.hh.
Referenced by strValue().
value_
int HDLGenerator::Parameter::value_ private
Definition at line 238 of file HDLGenerator.hh.
Referenced by width().
The documentation for this class was generated from the following file:
HDLGenerator.hh