OpenASIP: ProGe::SignalGroup Class Reference
ProGe::SignalGroup Class Reference
#include <SignalGroup.hh>
Public Member Functions
SignalGroup ()
template<typename... SignalT>
SignalGroup (SignalGroupType groupType, SignalT... signals)
virtual ~SignalGroup ()
SignalGroupType type () const
void addSignalType (SignalType signalType)
const std::set< SignalType > definedSignalTypes () const
bool operator== (SignalGroupType signalGroupType) const
Private Attributes
SignalGroupType type_
Signal group type id.
std::set< SignalType > signals_
Signals defined by this group.
Detailed Description
Definition at line 48 of file SignalGroup.hh.
Constructor & Destructor Documentation
SignalGroup() [1/2]
ProGe::SignalGroup::SignalGroup ()
Definition at line 38 of file SignalGroup.cc.
: type_(SignalGroupType::UNDEFINED), signals_() {}
SignalGroup() [2/2]
template<typename... SignalT> ProGe::SignalGroup::SignalGroup (SignalGroupType groupType, SignalT... signals) inline
Definition at line 53 of file SignalGroup.hh.
        : type_(groupType), signals_{signals...} {}
~SignalGroup()
ProGe::SignalGroup::~SignalGroup () virtual
Definition at line 40 of file SignalGroup.cc.
{}
Member Function Documentation
addSignalType()
void ProGe::SignalGroup::addSignalType (SignalType signalType)
Definition at line 48 of file SignalGroup.cc.
{
    signals_.insert(signalType);
}
References signals_.
definedSignalTypes()
const std::set< SignalType > ProGe::SignalGroup::definedSignalTypes () const
Definition at line 53 of file SignalGroup.cc.
{
    return signals_;
}
References signals_.
operator==()
bool ProGe::SignalGroup::operator== (SignalGroupType signalGroupType) const inline
Definition at line 61 of file SignalGroup.hh.
{
        return type() == signalGroupType;
    }
References type().
type()
SignalGroupType ProGe::SignalGroup::type () const
Definition at line 43 of file SignalGroup.cc.
{
    return type_;
}
References type_.
Referenced by operator==(), ProGe::ProcessorWrapperBlock::ProcessorWrapperBlock(), and ProGe::PortFactory::registerPortGroup().
Member Data Documentation
signals_
std::set<SignalType> ProGe::SignalGroup::signals_ private
Signals defined by this group.
Definition at line 71 of file SignalGroup.hh.
Referenced by addSignalType(), and definedSignalTypes().
type_
SignalGroupType ProGe::SignalGroup::type_ private
Signal group type id.
Definition at line 69 of file SignalGroup.hh.
Referenced by type().
The documentation for this class was generated from the following files:
SignalGroup.hh
SignalGroup.cc