OpenASIP: Matcher Class Reference
Matcher Class Reference abstract
#include <Matcher.hh>
Public Member Functions
Matcher (const EntryKeyFieldProperty *type)
virtual ~Matcher ()
virtual void quickFilter (const CostDBEntryKey &searchKey, CostDBTypes::EntryTable &components)=0
virtual void filter (const CostDBEntryKey &, CostDBTypes::EntryTable &)=0
Protected Member Functions
const EntryKeyFieldProperty * fieldType () const
bool onlyThisFieldDiffers (const EntryKeyFieldProperty *type, const CostDBEntry &entry1, const CostDBEntry &entry2) const
Private Member Functions
Matcher (const Matcher &)
Copying not allowed.
Matcher & operator= (const Matcher &)
Assignment not allowed.
Private Attributes
const EntryKeyFieldProperty * fieldType_
Type of the field on which filtering is applied to.
Detailed Description
Interface for searching database entries.
Search is based only on the information of one specific field of the entries. Using the interface for queries requires at first a QuickFilter() call and then a Filter() call.
Definition at line 50 of file Matcher.hh.
Constructor & Destructor Documentation
Matcher() [1/2]
Matcher::Matcher (const EntryKeyFieldProperty * type)
Constructor.
Marks the field type to which a search is aplied.
Parameters
type Type of the field.
Definition at line 44 of file Matcher.cc.
                                                  :
    fieldType_(type) {
}
~Matcher()
Matcher::~Matcher () virtual
Destructor.
Definition at line 51 of file Matcher.cc.
                  {
}
Matcher() [2/2]
Matcher::Matcher (const Matcher &) private
Copying not allowed.
Member Function Documentation
fieldType()
const EntryKeyFieldProperty * Matcher::fieldType () const protected
Referenced by Interpolation::filter(), and ExactMatch::quickFilter().
filter()
virtual void Matcher::filter (const CostDBEntryKey & , CostDBTypes::EntryTable &) pure virtual
Searches for database entries that match the search key.
Implemented in ExactMatch, SelectSet< select, unSelect >, SelectSet<&EntryKeyField::isGreater, &EntryKeyField::isSmaller >, SelectSet<&EntryKeyField::isSmaller, &EntryKeyField::isGreater >, and Interpolation.
onlyThisFieldDiffers()
bool Matcher::onlyThisFieldDiffers (const EntryKeyFieldProperty * type, const CostDBEntry & entry1, const CostDBEntry & entry2) const protected
Checks if only a specific field of two entries is different and all other fields have equal values.
Parameters
type Type of the field.
entry1 An entry.
entry2 An entry.
Returns
True if only one field of two entries is different, otherwise false.
Definition at line 64 of file Matcher.cc.
{
    for (int i = 0; i < entry1.fieldCount(); i++) {
        const EntryKeyField& j = entry1.field(i);
    if (!j.isEqual(entry2.keyFieldOfType(*j.type())) &&
        !(j.type() == type)) {
        return false;
    }
    }
    return true;
}
References CostDBEntry::field(), CostDBEntry::fieldCount(), EntryKeyField::isEqual(), CostDBEntry::keyFieldOfType(), and EntryKeyField::type().
Referenced by Interpolation::filter().
operator=()
Matcher & Matcher::operator= (const Matcher &) private
Assignment not allowed.
quickFilter()
virtual void Matcher::quickFilter (const CostDBEntryKey & searchKey, CostDBTypes::EntryTable & components) pure virtual
Filters out unnecessary entries in linear time.
Parameters
searchKey Search key.
components Entries from which to find. Updated to contain entries that matched the search request.
Implemented in Interpolation, ExactMatch, SelectSet< select, unSelect >, SelectSet<&EntryKeyField::isGreater, &EntryKeyField::isSmaller >, and SelectSet<&EntryKeyField::isSmaller, &EntryKeyField::isGreater >.
Member Data Documentation
fieldType_
const EntryKeyFieldProperty* Matcher::fieldType_ private
Type of the field on which filtering is applied to.
Definition at line 85 of file Matcher.hh.
The documentation for this class was generated from the following files:
Matcher.hh
Matcher.cc