OpenASIP: ProcessorConfigurationFile Class Reference
ProcessorConfigurationFile Class Reference
#include <ProcessorConfigurationFile.hh>
Public Member Functions
ProcessorConfigurationFile (std::istream &inputStream)
virtual ~ProcessorConfigurationFile ()
void setPCFDirectory (const std::string &path)
std::string architectureName ()
unsigned int architectureSize ()
unsigned int architectureModified ()
std::string implementationName ()
unsigned int implementationSize ()
unsigned int implementationModified ()
std::string encodingMapName ()
unsigned int encodingMapSize ()
unsigned int encodingMapModified ()
int errorCount ()
std::string errorString (int index)
bool errors ()
Public Member Functions inherited from ConfigurationFile
ConfigurationFile (bool doChecking=false)
virtual ~ConfigurationFile ()
void load (std::istream &inputStream)
bool hasKey (const std::string &key)
std::string value (const std::string &key, int index=0)
int itemCount (const std::string &key)
int intValue (const std::string &key, int index=0)
float floatValue (const std::string &key, int index=0)
std::string stringValue (const std::string &key, int index=0)
bool booleanValue (const std::string &key, int index=0)
unsigned int timeStampValue (const std::string &key)
Protected Member Functions
virtual bool handleError (int lineNumber, ConfigurationFile::ConfigurationFileError error, const std::string &line)
Protected Member Functions inherited from ConfigurationFile
void addSupportedKey (const std::string &key, ConfigurationValueType type, bool caseSensitive=false)
Private Member Functions
std::string realPath (const std::string &pathInPCF) const
Private Attributes
std::vector< std::string > errors_
std::string pcfDir_
Static Private Attributes
static const std::string ARCHITECTURE = "Architecture"
static const std::string ARCHITECTURE_SIZE = "ArchitectureSize"
static const std::string ARCHITECTURE_MODIFIED
static const std::string ENCODING_MAP = "EncodingMap"
static const std::string ENCODING_MAP_SIZE = "EncodingSize"
static const std::string ENCODING_MAP_MODIFIED
static const std::string IMPLEMENTATION = "Implementation"
static const std::string IMPLEMENTATION_SIZE
static const std::string IMPLEMENTATION_MODIFIED
Additional Inherited Members
Protected Types inherited from ConfigurationFile
enum ConfigurationValueType {
VT_INTEGER , VT_FLOAT , VT_STRING , VT_BOOLEAN ,
VT_READABLE_TIME , VT_UNIX_TIMESTAMP
}
enum ConfigurationFileError { FE_SYNTAX , FE_ILLEGAL_TYPE , FE_UNKNOWN_KEY , FE_MISSING_VALUE }
Detailed Description
Has knowledge of the format of the processor configuration file.
It knows its supported keys and provides shortcut methods for querying the values of the keys.
Definition at line 46 of file ProcessorConfigurationFile.hh.
Constructor & Destructor Documentation
ProcessorConfigurationFile()
ProcessorConfigurationFile::ProcessorConfigurationFile (std::istream & inputStream) explicit
Constructor.
Parameters
inputStream Stream where configuration file is read from.
Definition at line 58 of file ProcessorConfigurationFile.cc.
                             : ConfigurationFile(true), pcfDir_(".") {
    addSupportedKey(ARCHITECTURE, ConfigurationFile::VT_STRING, true);
    addSupportedKey(ARCHITECTURE_SIZE, ConfigurationFile::VT_INTEGER, true);
    addSupportedKey(ARCHITECTURE_MODIFIED, ConfigurationFile::VT_READABLE_TIME,
                    true);
    addSupportedKey(ENCODING_MAP, ConfigurationFile::VT_STRING, true);
    addSupportedKey(ENCODING_MAP_SIZE, ConfigurationFile::VT_INTEGER, true);
    addSupportedKey(ENCODING_MAP_MODIFIED, ConfigurationFile::VT_READABLE_TIME,
                    true);
    addSupportedKey(IMPLEMENTATION, ConfigurationFile::VT_STRING, true);
    addSupportedKey(IMPLEMENTATION_SIZE, ConfigurationFile::VT_INTEGER, true);
    addSupportedKey(IMPLEMENTATION_MODIFIED,
                    ConfigurationFile::VT_READABLE_TIME, true);
    load(inputStream);
}
References ConfigurationFile::addSupportedKey(), ARCHITECTURE, ARCHITECTURE_MODIFIED, ARCHITECTURE_SIZE, ENCODING_MAP, ENCODING_MAP_MODIFIED, ENCODING_MAP_SIZE, IMPLEMENTATION, IMPLEMENTATION_MODIFIED, IMPLEMENTATION_SIZE, ConfigurationFile::load(), ConfigurationFile::VT_INTEGER, ConfigurationFile::VT_READABLE_TIME, and ConfigurationFile::VT_STRING.
~ProcessorConfigurationFile()
ProcessorConfigurationFile::~ProcessorConfigurationFile () virtual
Destructor.
Definition at line 82 of file ProcessorConfigurationFile.cc.
{
}
Member Function Documentation
architectureModified()
unsigned int ProcessorConfigurationFile::architectureModified ()
Returns the timestamp of the architecture modified time.
Returns
Architecture modified timestamp.
Exceptions
KeyNotFound If architecture modified time is not found.
Definition at line 129 of file ProcessorConfigurationFile.cc.
{
    return timeStampValue(ARCHITECTURE_MODIFIED);
}
References ARCHITECTURE_MODIFIED, and ConfigurationFile::timeStampValue().
architectureName()
string ProcessorConfigurationFile::architectureName ()
Returns the name of the architecture.
Returns
The name of the architecture.
Exceptions
KeyNotFound If architecture is not found.
Definition at line 107 of file ProcessorConfigurationFile.cc.
{
    return realPath(value(ARCHITECTURE));
}
References ARCHITECTURE, realPath(), and ConfigurationFile::value().
Referenced by ProGe::ProGeUI::loadProcessorConfiguration(), SimulatorFrontend::loadProcessorConfiguration(), and MDFDocument::openCFG().
architectureSize()
unsigned int ProcessorConfigurationFile::architectureSize ()
Returns the size of the architecture.
Returns
The size of the architecture.
Exceptions
KeyNotFound If architecture size is not found.
Definition at line 118 of file ProcessorConfigurationFile.cc.
{
    return intValue(ARCHITECTURE_SIZE);
}
References ARCHITECTURE_SIZE, and ConfigurationFile::intValue().
encodingMapModified()
unsigned int ProcessorConfigurationFile::encodingMapModified ()
Returns the timestamp of encoding map modified time.
Returns
The timestamp of encoding map modified time.
Exceptions
KeyNotFound If timestamp is not found.
Definition at line 195 of file ProcessorConfigurationFile.cc.
{
    return timeStampValue(ENCODING_MAP_MODIFIED);
}
References ENCODING_MAP_MODIFIED, and ConfigurationFile::timeStampValue().
encodingMapName()
string ProcessorConfigurationFile::encodingMapName ()
Returns the name of the encoding map.
Returns
The name of the encoding map.
Exceptions
KeyNotFound If encoding map is not found.
Definition at line 173 of file ProcessorConfigurationFile.cc.
{
    return realPath(value(ENCODING_MAP));
}
References ENCODING_MAP, realPath(), and ConfigurationFile::value().
Referenced by ProGe::ProGeUI::loadProcessorConfiguration().
encodingMapSize()
unsigned int ProcessorConfigurationFile::encodingMapSize ()
Returns the size of the encoding map.
Returns
The size of the encoding map.
Exceptions
KeyNotFound If encoding map size is not found.
Definition at line 184 of file ProcessorConfigurationFile.cc.
{
    return intValue(ENCODING_MAP_SIZE);
}
References ENCODING_MAP_SIZE, and ConfigurationFile::intValue().
errorCount()
int ProcessorConfigurationFile::errorCount ()
Returns the number of errors.
Returns
The number of errors.
Definition at line 205 of file ProcessorConfigurationFile.cc.
{
    return errors_.size();
}
References errors_.
Referenced by MDFDocument::openCFG().
errors()
bool ProcessorConfigurationFile::errors ()
Returns true if errors were found.
Returns
True if errors were found.
Definition at line 231 of file ProcessorConfigurationFile.cc.
{
    return !errors_.empty();
}
References errors_.
Referenced by MDFDocument::openCFG().
errorString()
string ProcessorConfigurationFile::errorString (int index)
Returns the error string with a given index.
If such error string is not found, returns empty string.
Returns
Error string with a given index.
Definition at line 217 of file ProcessorConfigurationFile.cc.
{
    if (index < 0 || index > static_cast<int>(errors_.size()) - 1) {
        return "";
    }
    return errors_[index];
}
References errors_.
Referenced by handleError(), and MDFDocument::openCFG().
handleError()
bool ProcessorConfigurationFile::handleError (int lineNumber, ConfigurationFile::ConfigurationFileError error, const std::string & line) protected virtual
Handles the errors.
Error string are added in internal data structure.
Parameters
lineNumber The line number.
error The type of the error.
line The line in which error occurred.
Returns
True.
Reimplemented from ConfigurationFile.
Definition at line 246 of file ProcessorConfigurationFile.cc.
{
    string errorString;
    switch (error) {
    case ConfigurationFile::FE_SYNTAX:
        errorString += "Syntax error ";
        break;
    case ConfigurationFile::FE_ILLEGAL_TYPE:
        errorString += "Illegal type error ";
        break;
    case ConfigurationFile::FE_UNKNOWN_KEY:
        errorString += "Unknown key error ";
        break;
    case ConfigurationFile::FE_MISSING_VALUE:
        errorString += "Missing value error ";
        break;
    }
    errorString += "in line " + Conversion::toString(lineNumber) +
        ": " + line;
    errors_.push_back(errorString);
    return true;
}
References errors_, errorString(), ConfigurationFile::FE_ILLEGAL_TYPE, ConfigurationFile::FE_MISSING_VALUE, ConfigurationFile::FE_SYNTAX, ConfigurationFile::FE_UNKNOWN_KEY, and Conversion::toString().
implementationModified()
unsigned int ProcessorConfigurationFile::implementationModified ()
Returns the implementation modified timestamp.
Returns
Timestamp of implementation modified time.
Exceptions
KeyNotFound If implementation modified timestamp is not found.
Definition at line 162 of file ProcessorConfigurationFile.cc.
{
    return timeStampValue(IMPLEMENTATION_MODIFIED);
}
References IMPLEMENTATION_MODIFIED, and ConfigurationFile::timeStampValue().
implementationName()
string ProcessorConfigurationFile::implementationName ()
Returns the name of the implementation.
Returns
The name of the implementation.
Exceptions
KeyNotFound If implementation is not found.
Definition at line 140 of file ProcessorConfigurationFile.cc.
{
    return realPath(value(IMPLEMENTATION));
}
References IMPLEMENTATION, realPath(), and ConfigurationFile::value().
Referenced by ProGe::ProGeUI::loadProcessorConfiguration().
implementationSize()
unsigned int ProcessorConfigurationFile::implementationSize ()
Returns the size of the implementation.
Returns
The size of the implementation.
Exceptions
KeyNotFound If implementation size is not found.
Definition at line 151 of file ProcessorConfigurationFile.cc.
{
    return intValue(IMPLEMENTATION_SIZE);
}
References IMPLEMENTATION_SIZE, and ConfigurationFile::intValue().
realPath()
std::string ProcessorConfigurationFile::realPath (const std::string & pathInPCF) const private
Creates real path to the file referred to in PCF.
The path is constructed assuming the PCF is in the directory set with setPCFDirectory method.
Parameters
pathInPCF The path that reads in the PCF.
Returns
Real path to the file.
Definition at line 284 of file ProcessorConfigurationFile.cc.
{
    if (FileSystem::isAbsolutePath(pathInPCF) || pcfDir_ == "") {
        return pathInPCF;
    } else {
        return pcfDir_ + FileSystem::DIRECTORY_SEPARATOR + pathInPCF;
    }
}
References FileSystem::DIRECTORY_SEPARATOR, FileSystem::isAbsolutePath(), and pcfDir_.
Referenced by architectureName(), encodingMapName(), and implementationName().
setPCFDirectory()
void ProcessorConfigurationFile::setPCFDirectory (const std::string & directory)
Sets the directory of PCF file itself.
Path of the ADF, IDF and BEM files are constructed relative to the PCF directory if a relative path is given in PCF.
Parameters
directory The directory of the PCF file.
Definition at line 95 of file ProcessorConfigurationFile.cc.
{
    pcfDir_ = directory;
}
References pcfDir_.
Referenced by ProGe::ProGeUI::loadProcessorConfiguration(), SimulatorFrontend::loadProcessorConfiguration(), and MDFDocument::openCFG().
Member Data Documentation
ARCHITECTURE
const string ProcessorConfigurationFile::ARCHITECTURE = "Architecture" static private
Definition at line 80 of file ProcessorConfigurationFile.hh.
Referenced by architectureName(), and ProcessorConfigurationFile().
ARCHITECTURE_MODIFIED
const string ProcessorConfigurationFile::ARCHITECTURE_MODIFIED static private
Initial value:
=
"ArchitectureModified"
Definition at line 82 of file ProcessorConfigurationFile.hh.
Referenced by architectureModified(), and ProcessorConfigurationFile().
ARCHITECTURE_SIZE
const string ProcessorConfigurationFile::ARCHITECTURE_SIZE = "ArchitectureSize" static private
Definition at line 81 of file ProcessorConfigurationFile.hh.
Referenced by architectureSize(), and ProcessorConfigurationFile().
ENCODING_MAP
const string ProcessorConfigurationFile::ENCODING_MAP = "EncodingMap" static private
Definition at line 84 of file ProcessorConfigurationFile.hh.
Referenced by encodingMapName(), and ProcessorConfigurationFile().
ENCODING_MAP_MODIFIED
const string ProcessorConfigurationFile::ENCODING_MAP_MODIFIED static private
Initial value:
=
"EncodingModified"
Definition at line 86 of file ProcessorConfigurationFile.hh.
Referenced by encodingMapModified(), and ProcessorConfigurationFile().
ENCODING_MAP_SIZE
const string ProcessorConfigurationFile::ENCODING_MAP_SIZE = "EncodingSize" static private
Definition at line 85 of file ProcessorConfigurationFile.hh.
Referenced by encodingMapSize(), and ProcessorConfigurationFile().
errors_
std::vector<std::string> ProcessorConfigurationFile::errors_ private
Definition at line 92 of file ProcessorConfigurationFile.hh.
Referenced by errorCount(), errors(), errorString(), and handleError().
IMPLEMENTATION
const string ProcessorConfigurationFile::IMPLEMENTATION = "Implementation" static private
Definition at line 88 of file ProcessorConfigurationFile.hh.
Referenced by implementationName(), and ProcessorConfigurationFile().
IMPLEMENTATION_MODIFIED
const string ProcessorConfigurationFile::IMPLEMENTATION_MODIFIED static private
Initial value:
=
"ImplementationModified"
Definition at line 90 of file ProcessorConfigurationFile.hh.
Referenced by implementationModified(), and ProcessorConfigurationFile().
IMPLEMENTATION_SIZE
const string ProcessorConfigurationFile::IMPLEMENTATION_SIZE static private
Initial value:
=
"ImplementationSize"
Definition at line 89 of file ProcessorConfigurationFile.hh.
Referenced by implementationSize(), and ProcessorConfigurationFile().
pcfDir_
std::string ProcessorConfigurationFile::pcfDir_ private
Directory of the PCF file, affects the path returned when ADF, IDF or BEM is requested.
Definition at line 98 of file ProcessorConfigurationFile.hh.
Referenced by realPath(), and setPCFDirectory().
The documentation for this class was generated from the following files:
ProcessorConfigurationFile.hh
ProcessorConfigurationFile.cc