OpenASIP: InstructionExecution Class Reference
InstructionExecution Class Reference
#include <InstructionExecution.hh>
Public Member Functions
InstructionExecution (RelationalDBQueryResult *result)
virtual ~InstructionExecution ()
ClockCycleCount cycle () const
InstructionAddress address () const
void next ()
bool hasNext () const
Private Attributes
RelationalDBQueryResult * result_
int addressColumnIndex_
int cycleColumnIndex_
Detailed Description
Class used to navigate through the list of all execution cycles.
This class is also used to access the data of the pointed record.
Definition at line 45 of file InstructionExecution.hh.
Constructor & Destructor Documentation
InstructionExecution()
InstructionExecution::InstructionExecution (RelationalDBQueryResult * result)
Constructor.
Object is initialized to point to the first record in the record set, if any.
Parameters
result The query result to traverse.
Definition at line 46 of file InstructionExecution.cc.
                                                                          :
    result_(result), addressColumnIndex_(-1), cycleColumnIndex_(-1) {
    cycleColumnIndex_ = result_->column("cycle");
    addressColumnIndex_ = result_->column("address");
    assert(addressColumnIndex_ > -1);
    assert(cycleColumnIndex_ > -1);
    assert(result != NULL);
    if (hasNext()) {
        next();
    }
}
References addressColumnIndex_, assert, RelationalDBQueryResult::column(), cycleColumnIndex_, hasNext(), next(), and result_.
~InstructionExecution()
InstructionExecution::~InstructionExecution () virtual
Destructor.
Definition at line 63 of file InstructionExecution.cc.
{
    delete result_;
    result_ = NULL;
}
References result_.
Member Function Documentation
address()
InstructionAddress InstructionExecution::address () const
Returns the instruction address value of the current record.
Returns
The instruction address value.
Exceptions
NotAvailable If the current record is empty.
Definition at line 91 of file InstructionExecution.cc.
{
    if (&result_->data(addressColumnIndex_) == &NullDataObject::instance()) {
        const std::string errorMsg =
            "Tried to fetch data from an empty result set.";
        throw NotAvailable(__FILE__, __LINE__, __func__, errorMsg);
    }
    return result_->data(addressColumnIndex_).integerValue();
}
References __func__, addressColumnIndex_, RelationalDBQueryResult::data(), NullDataObject::instance(), DataObject::integerValue(), and result_.
cycle()
ClockCycleCount InstructionExecution::cycle () const
Returns the cycle count value of the current record.
Returns
The cycle count.
Exceptions
NotAvailable If the current record is empty.
Definition at line 75 of file InstructionExecution.cc.
{
    if (&result_->data(cycleColumnIndex_) == &NullDataObject::instance()) {
        const std::string errorMsg =
            "Tried to fetch data from an empty result set.";
        throw NotAvailable(__FILE__, __LINE__, __func__, errorMsg);
    }
    return result_->data(cycleColumnIndex_).integerValue();
}
References __func__, cycleColumnIndex_, RelationalDBQueryResult::data(), NullDataObject::instance(), DataObject::integerValue(), and result_.
hasNext()
bool InstructionExecution::hasNext () const
Returns true if there are more results available.
Returns
True if more results available.
Definition at line 119 of file InstructionExecution.cc.
{
    return result_->hasNext();
}
References RelationalDBQueryResult::hasNext(), and result_.
Referenced by InstructionExecution().
next()
void InstructionExecution::next ()
Advances the navigator to the next record in the query result set.
Exceptions
NotAvailable if there is no more results in the set.
Definition at line 106 of file InstructionExecution.cc.
{
    if (!result_->hasNext()) {
        throw NotAvailable(__FILE__, __LINE__, __func__, "No more results.");
    }
    result_->next();
}
References __func__, RelationalDBQueryResult::hasNext(), RelationalDBQueryResult::next(), and result_.
Referenced by InstructionExecution().
Member Data Documentation
addressColumnIndex_
int InstructionExecution::addressColumnIndex_ private
Definition at line 58 of file InstructionExecution.hh.
Referenced by address(), and InstructionExecution().
cycleColumnIndex_
int InstructionExecution::cycleColumnIndex_ private
Definition at line 59 of file InstructionExecution.hh.
Referenced by cycle(), and InstructionExecution().
result_
RelationalDBQueryResult* InstructionExecution::result_ private
Definition at line 57 of file InstructionExecution.hh.
Referenced by address(), cycle(), hasNext(), InstructionExecution(), next(), and ~InstructionExecution().
The documentation for this class was generated from the following files:
InstructionExecution.hh
InstructionExecution.cc