OpenASIP: EPSGenerator Class Reference
EPSGenerator Class Reference
#include <EPSGenerator.hh>
Classes
struct colour
Public Member Functions
EPSGenerator ()
~EPSGenerator ()
void setCreator (std::string creator)
void setTitle (std::string title)
void setLineWidth (unsigned width)
void setFont (unsigned size, std::string fontName="Courier-Bold")
void setLineColour (double r, double g, double b)
void setFillColour (double r, double g, double b)
void setScale (double scale)
void setMargins (unsigned x, unsigned y)
void drawRectangle (int x, int y, unsigned width, unsigned height)
void drawFilledRectangle (int x, int y, unsigned width, unsigned height)
void drawCircle (int x, int y, unsigned radius)
void drawFilledCircle (int x, int y, unsigned radius)
void drawEllipse (int x, int y, unsigned width, unsigned height)
void drawFilledEllipse (int x, int y, unsigned width, unsigned height)
void drawPolygon (const VertexList &vertices)
void drawFilledPolygon (const VertexList &vertices)
void drawText (int x, int y, std::string text)
void drawLine (int llx, int lly, int urx, int ury)
void clearBuffer ()
void writeEPS (std::ostream &stream)
Private Member Functions
EPSGenerator (const EPSGenerator &)
Copying forbidden.
EPSGenerator & operator= (const EPSGenerator &)
Assignment forbidden.
void useLineColour ()
void useFillColour ()
void appendToBounds (int x, int y)
void doDrawEllipse (int x, int y, unsigned width, unsigned height, bool fill)
void drawRectanglePath (int x, int y, unsigned width, unsigned height)
void drawCirclePath (int x, int y, unsigned radius)
void drawPolygonPath (const VertexList &vertices)
Private Attributes
bool hasTitle_
True, if the EPS file has a title.
std::string title_
Title of the EPS file.
std::string creator_
String describing the creator of the document.
std::string creationDate_
String describing the creation date of the EPS file.
std::queue< std::string > buffer_
Buffer for the .eps code to be written.
unsigned lineWidth_
Current width of the lines drawn.
int minX_
Minimum x-coordinate used before scaling & translation.
int minY_
Minimum y-coordinate used before scaling & translation.
int maxX_
Maximum x-coordinate used before scaling & translation.
int maxY_
Maximum y-coordinate used before scaling & translation.
double scale_
Final scaling factor for the eps file.
bool boundsSet_
True, if a point has been added to the bounds.
unsigned xMargin_
Margin to add on the left and right side of the figure in pixels.
unsigned yMargin_
Margin to add on the top and bottom side of the figure in pixels.
colour lineColour_
Current drawing colour for lines.
colour fillColour_
Current colour for filling shape backgrounds.
Static Private Attributes
static const unsigned DEFAULT_MARGIN = 20
Default margin width.
static const std::string FMT_MOVETO = " %1% %2% moveto"
Format string for postscript moveto command.
static const std::string FMT_LINETO = " %1% %2% lineto"
Format string for postscript lineto command.
static const std::string FMT_RLINETO = " %1% %2% rlineto"
Format string for postscript rlineto command.
Detailed Description
EPSGenerator is a tool for drawing vector graphics to an eps file.
The drawing is done into a buffer using various drawing methods. Once the drawing is done, the buffer which contains a valid .eps file can be written to an output stream.
The coordinate system used by EPSGenerator corresponds to the Postscript coordinate system. Origo is in the lower left corner of the image and one pixel corresponds to one 72th of an inch.
Definition at line 54 of file EPSGenerator.hh.
Constructor & Destructor Documentation
EPSGenerator() [1/2]
EPSGenerator::EPSGenerator ()
The Constructor.
Definition at line 51 of file EPSGenerator.cc.
                           :
    hasTitle_(false), title_(""), creator_("TCE EPS Generator"),
    lineWidth_(1), minX_(0), minY_(0), maxX_(0), maxY_(0),
    scale_(1) ,boundsSet_(false), xMargin_(DEFAULT_MARGIN),
    yMargin_(DEFAULT_MARGIN) {
    time_t currentTime;
    time(&currentTime);
    creationDate_ = ctime(&currentTime);
    fillColour_.r = 0;
    fillColour_.g = 0;
    fillColour_.b = 0;
    lineColour_.r = 0;
    lineColour_.g = 0;
    lineColour_.b = 0;
}
References EPSGenerator::colour::b, creationDate_, fillColour_, EPSGenerator::colour::g, lineColour_, and EPSGenerator::colour::r.
~EPSGenerator()
EPSGenerator::~EPSGenerator ()
The Destructor.
Definition at line 73 of file EPSGenerator.cc.
{
    clearBuffer();
}
References clearBuffer().
EPSGenerator() [2/2]
EPSGenerator::EPSGenerator (const EPSGenerator &) private
Copying forbidden.
Member Function Documentation
appendToBounds()
void EPSGenerator::appendToBounds (int x, int y) private
Stretches eps bounds so that the given point is inside the bounds.
Definition at line 81 of file EPSGenerator.cc.
{
    if (boundsSet_) {
        minX_ = (x < minX_) ? x : minX_;
        maxX_ = (x > maxX_) ? x : maxX_;
        minY_ = (y < minY_) ? y : minY_;
        maxY_ = (y > maxY_) ? y : maxY_;
    } else {
        boundsSet_ = true;
        minX_ = x;
        maxX_ = x;
        minY_ = y;
        maxY_ = y;
    }
}
References boundsSet_, maxX_, maxY_, minX_, and minY_.
Referenced by doDrawEllipse(), drawCirclePath(), drawLine(), drawPolygonPath(), and drawRectanglePath().
clearBuffer()
void EPSGenerator::clearBuffer ()
Clears the eps code buffer.
Definition at line 517 of file EPSGenerator.cc.
{
    while(!buffer_.empty()) {
        buffer_.pop();
    }
}
References buffer_.
Referenced by EPSDC::Clear(), and ~EPSGenerator().
doDrawEllipse()
void EPSGenerator::doDrawEllipse (int x, int y, unsigned width, unsigned height, bool fill) private
Writes path of an ellipse outline to the eps buffer.
Parameters
x X-coordinate of the ellipse bounding box lower left corner.
y Y-coordinate of the ellipse bounding box lower left corner.
width Width of the ellipse.
height Height of the ellipse.
fill True, if the ellipse shoud be filled.
Definition at line 348 of file EPSGenerator.cc.
{
    appendToBounds(x + width, y + height);
    appendToBounds(x, y);
    buffer_.push("");
    format fmtScale = format("1 %1% %2% div scale");
    format fmtTranslate = format("%1% %2% translate");
    fmtScale % width % height;
    fmtTranslate % (x + width / 2) % (y + height / 2);
    buffer_.push("gsave");
    buffer_.push(fmtTranslate.str());
    buffer_.push(fmtScale.str());
    std::string fmtEllipse = " 0 0 %4% 2 div 0 360 arc";
    boost::format ellipse = format(fmtEllipse) % x % y % width % height;
    buffer_.push("newpath");
    buffer_.push(ellipse.str());
    if (fill) {
        buffer_.push(" gsave");
        useFillColour();
        buffer_.push(" fill");
        buffer_.push(" grestore");
        useLineColour();
    }
    buffer_.push("stroke");
    buffer_.push("grestore");
}
References appendToBounds(), buffer_, useFillColour(), and useLineColour().
Referenced by drawEllipse(), and drawFilledEllipse().
drawCircle()
void EPSGenerator::drawCircle (int x, int y, unsigned radius)
Draws a circle.
Parameters
x X-coordinate of the circle centre.
y Y-coordinate of the circle centre.
radius Radius of the circle.
Definition at line 262 of file EPSGenerator.cc.
{
    drawCirclePath(x, y, radius);
    buffer_.push("stroke");
}
References buffer_, and drawCirclePath().
Referenced by EPSDC::drawCircle().
drawCirclePath()
void EPSGenerator::drawCirclePath (int x, int y, unsigned radius) private
Writes path of a circle outline to the eps buffer.
Parameters
x X-coordinate of the circle centre.
y Y-coordinate of the circle centre.
radius Radius of the circle.
Definition at line 294 of file EPSGenerator.cc.
{
    appendToBounds(x + radius, y + radius);
    appendToBounds(x - radius, y - radius);
    buffer_.push("");
    std::string fmtCircle = " %1% %2% %3% 0 360 arc";
    boost::format circle = format(fmtCircle) % x % y % radius;
    buffer_.push("newpath");
    buffer_.push(circle.str());
}
References appendToBounds(), and buffer_.
Referenced by drawCircle(), and drawFilledCircle().
drawEllipse()
void EPSGenerator::drawEllipse (int x, int y, unsigned width, unsigned height)
Draws outline of an ellipse.
Parameters
x X-coordinate of the ellipse bounding box lower left corner.
y Y-coordinate of the ellipse bounding box lower left corner.
width Width of the ellipse.
height Height of the ellipse.
Definition at line 318 of file EPSGenerator.cc.
{
    doDrawEllipse(x, y, width, height, false);
}
References doDrawEllipse().
Referenced by EPSDC::DoDrawEllipse().
drawFilledCircle()
void EPSGenerator::drawFilledCircle (int x, int y, unsigned radius)
Draws a circle filled with the fill colour.
Parameters
x X-coordinate of the circle centre.
y Y-coordinate of the circle centre.
radius Radius of the circle.
Definition at line 275 of file EPSGenerator.cc.
{
    drawCirclePath(x, y, radius);
    buffer_.push(" gsave");
    useFillColour();
    buffer_.push(" fill");
    buffer_.push(" grestore");
    useLineColour();
    buffer_.push("stroke");
}
References buffer_, drawCirclePath(), useFillColour(), and useLineColour().
Referenced by EPSDC::drawCircle().
drawFilledEllipse()
void EPSGenerator::drawFilledEllipse (int x, int y, unsigned width, unsigned height)
Draws a filled ellipse.
Parameters
x X-coordinate of the ellipse bounding box lower left corner.
y Y-coordinate of the ellipse bounding box lower left corner.
width Width of the ellipse.
height Height of the ellipse.
Definition at line 332 of file EPSGenerator.cc.
{
    doDrawEllipse(x, y, width, height, true);
}
References doDrawEllipse().
Referenced by EPSDC::DoDrawEllipse().
drawFilledPolygon()
void EPSGenerator::drawFilledPolygon (const VertexList & vertices)
Draws a filled polygon.
Parameters
vertices Vector of at least three coordinate pairs which are the polygon vertices.
Definition at line 206 of file EPSGenerator.cc.
{
    assert(vertices.size() > 2);
    drawPolygonPath(vertices);
    buffer_.push(" gsave");
    useFillColour();
    buffer_.push(" fill");
    buffer_.push(" grestore");
    useLineColour();
    buffer_.push("stroke");
}
References assert, buffer_, drawPolygonPath(), VertexList::size(), useFillColour(), and useLineColour().
Referenced by EPSDC::DoDrawPolygon().
drawFilledRectangle()
void EPSGenerator::drawFilledRectangle (int x, int y, unsigned width, unsigned height)
Draws a rectangle fileld with the fill colour set.
Parameters
x Lower left corner x-coordinate of the rectangle.
y Lower left corner y-coordinate of the rectangle.
width Width of the rectangle.
height Height of the rectangle.
Definition at line 120 of file EPSGenerator.cc.
{
    drawRectanglePath(x, y, width, height);
    buffer_.push(" gsave");
    useFillColour();
    buffer_.push(" fill");
    buffer_.push(" grestore");
    useLineColour();
    buffer_.push("stroke");
}
References buffer_, drawRectanglePath(), useFillColour(), and useLineColour().
Referenced by EPSDC::DoDrawRectangle().
drawLine()
void EPSGenerator::drawLine (int x1, int y1, int x2, int y2)
Draws a line.
Parameters
x1 X-coordinate of the first end point of the line.
y1 Y-coordinate of the first end point of the line.
x2 X-coordinate of the second end point of the line.
y2 Y-coordinate of the second end point of the line.
Definition at line 171 of file EPSGenerator.cc.
{
    appendToBounds(x1, y1);
    appendToBounds(x2, y2);
    format move = format(FMT_MOVETO) % x1 % y1;
    format line = format(FMT_LINETO) % x2 % y2;
    buffer_.push("");
    buffer_.push("newpath");
    buffer_.push(move.str());
    buffer_.push(line.str() );
    buffer_.push("stroke");
}
References appendToBounds(), buffer_, FMT_LINETO, and FMT_MOVETO.
Referenced by EPSDC::DoDrawLine().
drawPolygon()
void EPSGenerator::drawPolygon (const VertexList & vertices)
Draws a polygon outline.
Parameters
vertices Vector of at least three coordinate pairs which are the polygon vertices.
Definition at line 192 of file EPSGenerator.cc.
{
    assert(vertices.size() > 2);
    drawPolygonPath(vertices);
    buffer_.push("stroke");
}
References assert, buffer_, drawPolygonPath(), and VertexList::size().
Referenced by EPSDC::DoDrawPolygon().
drawPolygonPath()
void EPSGenerator::drawPolygonPath (const VertexList & vertices) private
Writes path of a polygon outline to the eps buffer.
Parameters
vertices Vector of at least three coordinate pairs which are the polygon vertices.
Definition at line 225 of file EPSGenerator.cc.
{
    assert(vertices.size() > 2);
    format move(FMT_MOVETO);
    int x = vertices.vertexX(0);
    int y = vertices.vertexY(0);
    appendToBounds(x, y);
    move % x % y;
    buffer_.push("");
    buffer_.push("newpath");
    buffer_.push(move.str());
    for (unsigned i = 1; i < vertices.size(); i++) {
        x = vertices.vertexX(i);
        y = vertices.vertexY(i);
        appendToBounds(x, y);
        format lineto(FMT_LINETO);
        lineto % x % y;
        buffer_.push(lineto.str());
    }
    buffer_.push(" closepath");
}
References appendToBounds(), assert, buffer_, FMT_LINETO, FMT_MOVETO, VertexList::size(), VertexList::vertexX(), and VertexList::vertexY().
Referenced by drawFilledPolygon(), and drawPolygon().
drawRectangle()
void EPSGenerator::drawRectangle (int x, int y, unsigned width, unsigned height)
Draws a rectangle.
Parameters
x Lower left corner x-coordinate of the rectangle.
y Lower left corner y-coordinate of the rectangle.
width Width of the rectangle.
height Height of the rectangle.
Definition at line 106 of file EPSGenerator.cc.
{
    drawRectanglePath(x, y, width, height);
    buffer_.push("stroke");
}
References buffer_, and drawRectanglePath().
Referenced by EPSDC::DoDrawRectangle().
drawRectanglePath()
void EPSGenerator::drawRectanglePath (int x, int y, unsigned width, unsigned height) private
Writes path of a rectangle outline to the eps buffer.
Parameters
x Lower left corner x-coordinate of the rectangle.
y Lower left corner y-coordinate of the rectangle.
width Width of the rectangle.
height Height of the rectangle.
Definition at line 141 of file EPSGenerator.cc.
{
    appendToBounds(x, y);
    appendToBounds(x + width, y + height);
    format move = format(FMT_MOVETO) % x % y;
    format line1 = format(FMT_RLINETO) % width % 0;
    format line2 = format(FMT_RLINETO) % 0 % height;
    format line3 = format(FMT_RLINETO) % (-1 * (int)width) % 0;
    buffer_.push("");
    buffer_.push("newpath");
    buffer_.push(move.str());
    buffer_.push(line1.str());
    buffer_.push(line2.str());
    buffer_.push(line3.str());
    buffer_.push(" closepath");
}
References appendToBounds(), buffer_, FMT_MOVETO, and FMT_RLINETO.
Referenced by drawFilledRectangle(), and drawRectangle().
drawText()
void EPSGenerator::drawText (int x, int y, std::string text)
Draws text to the eps with the current font set with setFont method.
Parameters
x X-coordinate of the text bounds lower left corner.
y Y-coordinate of the text bounds lower left corner.
text Text to draw.
Definition at line 392 of file EPSGenerator.cc.
{
    format fmtMoveTo("%1% %2% moveto");
    format fmtShowText(" (%1%) show");
    fmtMoveTo % x % y;
    fmtShowText % text;
    buffer_.push("");
    buffer_.push(fmtMoveTo.str());
    buffer_.push(fmtShowText.str());
}
References buffer_.
Referenced by EPSDC::DoDrawText().
operator=()
EPSGenerator & EPSGenerator::operator= (const EPSGenerator &) private
Assignment forbidden.
setCreator()
void EPSGenerator::setCreator (std::string creator)
Sets the creator string of the image.
The creator string will be set as the Creator comment of the generated eps file.
Parameters
creator String describing the creator of the eps-file.
Definition at line 415 of file EPSGenerator.cc.
{
    creator_ = creator;
}
References creator_.
Referenced by EPSDC::setCreator().
setFillColour()
void EPSGenerator::setFillColour (double r, double g, double b)
Sets the shape filling colour.
Parameters
r Red component scaled between 0 and 1.
g Green component scaled between 0 and 1.
b Blue component scaled between 0 and 1.
Definition at line 499 of file EPSGenerator.cc.
{
    if (r < 0 || g < 0 || b < 0 || r > 1 || g > 1 || b > 1) {
        std::string error =
            "Colour component values must be between 0 and 1.";
        std::string proc = "EPSGenerator::setFillColour";
        OutOfRange e(__FILE__, __LINE__, proc, error);
        throw e;
    }
    fillColour_.r = r;
    fillColour_.g = g;
    fillColour_.b = b;
}
References EPSGenerator::colour::b, fillColour_, EPSGenerator::colour::g, and EPSGenerator::colour::r.
Referenced by EPSDC::setFillColour().
setFont()
void EPSGenerator::setFont (unsigned size, std::string fontName = "Courier-Bold")
Sets the font face and size.
Parameters
size Font height in pixels.
fontName Name of the font. The name must be valid post script font name.
Definition at line 460 of file EPSGenerator.cc.
{
    format setFont = format("/%2% findfont %1% scalefont setfont");
    setFont % size % fontName;
    buffer_.push("");
    buffer_.push(setFont.str());
}
References buffer_, and setFont().
Referenced by EPSDC::SetFont(), and setFont().
setLineColour()
void EPSGenerator::setLineColour (double r, double g, double b)
Sets the line drawing colour.
Parameters
r Red component scaled between 0 and 1.
g Green component scaled between 0 and 1.
b Blue component scaled between 0 and 1.
Definition at line 475 of file EPSGenerator.cc.
{
    if (r < 0 || g < 0 || b < 0 || r > 1 || g > 1 || b > 1) {
        std::string error =
            "Colour component values must be between 0 and 1.";
        std::string proc = "EPSGenerator::setLineColour";
        OutOfRange e(__FILE__, __LINE__, proc, error);
        throw e;
    }
    lineColour_.r = r;
    lineColour_.g = g;
    lineColour_.b = b;
    useLineColour();
}
References EPSGenerator::colour::b, EPSGenerator::colour::g, lineColour_, EPSGenerator::colour::r, and useLineColour().
Referenced by EPSDC::setLineColour().
setLineWidth()
void EPSGenerator::setLineWidth (unsigned width)
Sets the line width of the shapes that are drawn after this function call.
Parameters
width Width of the lines drawn to the eps.
Definition at line 444 of file EPSGenerator.cc.
{
    lineWidth_ = width;
    buffer_.push("");
    std::string setlinewidth = "%1% setlinewidth";
    buffer_.push(str(format(setlinewidth) % width));
}
References buffer_, and lineWidth_.
Referenced by EPSDC::SetPen().
setMargins()
void EPSGenerator::setMargins (unsigned x, unsigned y)
Sets the eps margins.
Parameters
x Left and right side margin.
y Top and bottom margin.
Definition at line 594 of file EPSGenerator.cc.
{
    xMargin_ = x;
    yMargin_ = y;
}
References xMargin_, and yMargin_.
setScale()
void EPSGenerator::setScale (double scale)
Sets the coordinate system scaling factors for the coordinate axels.
This function sets only the final scaling factor of the image. Only the last scaling factor set before calling writeEPS has effect on the final eps file.
Parameters
scale Scaling factor.
Definition at line 576 of file EPSGenerator.cc.
{
    if (scale < 0) {
        std::string error = "Scaling factor must be greater than zero.";
        std::string proc = "EPSGenerator::setScale";
        OutOfRange e(__FILE__, __LINE__, proc, error);
        throw e;
    }
    scale_ = scale;
}
References scale_.
setTitle()
void EPSGenerator::setTitle (std::string title)
Sets the title of the eps file.
Title string will be set as the title comment of the generated eps file. If the title string is empty, the title comment will be omitted.
Parameters
title Title of the eps file.
Definition at line 428 of file EPSGenerator.cc.
{
    if (title.length() > 0) {
        hasTitle_ = true;
    } else {
        hasTitle_ = false;
    }
    title_ = title;
}
References hasTitle_, and title_.
Referenced by EPSDC::setTitle().
useFillColour()
void EPSGenerator::useFillColour () private
Sets the eps drawing colour to the current filling colour.
Definition at line 614 of file EPSGenerator.cc.
{
    format setColour("%1% %2% %3% setrgbcolor");
    setColour % fillColour_.r % fillColour_.g % fillColour_.b;
    buffer_.push(setColour.str());
}
References EPSGenerator::colour::b, buffer_, fillColour_, EPSGenerator::colour::g, and EPSGenerator::colour::r.
Referenced by doDrawEllipse(), drawFilledCircle(), drawFilledPolygon(), and drawFilledRectangle().
useLineColour()
void EPSGenerator::useLineColour () private
Sets the eps drawing colour to the current line drawing colour.
Definition at line 604 of file EPSGenerator.cc.
{
    format setColour("%1% %2% %3% setrgbcolor");
    setColour % lineColour_.r % lineColour_.g % lineColour_.b;
    buffer_.push(setColour.str());
}
References EPSGenerator::colour::b, buffer_, EPSGenerator::colour::g, lineColour_, and EPSGenerator::colour::r.
Referenced by doDrawEllipse(), drawFilledCircle(), drawFilledPolygon(), drawFilledRectangle(), and setLineColour().
writeEPS()
void EPSGenerator::writeEPS (std::ostream & ostream)
Generates an eps file which contains the graphics client drew.
Parameters
ostream Output stream to write the eps file contents to.
Definition at line 529 of file EPSGenerator.cc.
{
    int w = (int)(scale_*(maxX_ - minX_ + 2 * xMargin_));
    int h = (int)(scale_*(maxY_ - minY_ + 2 * yMargin_));
    // Write eps headers.
    ostream << "%!PS-Adobe-3.0 EPSF-3.0" << endl;
    ostream << "%%BoundingBox: 0 0 " << w << " " << h << " " << endl;
    if (hasTitle_) {
        ostream << "%%Title: (" << title_ << ")" << endl;
    }
    ostream << "%%Creator: " << creator_ << endl;
    ostream << "%%CreationDate: " << creationDate_ << endl;
    ostream << "%%EndComments" << endl;
    // Set scaling factor & translation. The coordinate system is translated
    // so that the minimum x and y coordinates are zero.
    ostream << scale_ << " " << scale_ << " scale" << endl;
    ostream << minX_ * -1 + (int)xMargin_ << " "
            << minY_ * -1 + (int)yMargin_ << " translate" << endl;
    // Write the postscript drawing code from the code buffer to the
    // output stream.
    while (!buffer_.empty()) {
        std::string line = buffer_.front();
        buffer_.pop();
        ostream << line << endl;
    }
    ostream << endl << "showpage" << endl << endl;
    // Write end of file comment.
    ostream << "%%EOF" << endl;
}
References buffer_, creationDate_, creator_, hasTitle_, maxX_, maxY_, minX_, minY_, scale_, title_, xMargin_, and yMargin_.
Referenced by EPSDC::writeToStream().
Member Data Documentation
boundsSet_
bool EPSGenerator::boundsSet_ private
True, if a point has been added to the bounds.
Definition at line 145 of file EPSGenerator.hh.
Referenced by appendToBounds().
buffer_
std::queue<std::string> EPSGenerator::buffer_ private
Buffer for the .eps code to be written.
Definition at line 127 of file EPSGenerator.hh.
Referenced by clearBuffer(), doDrawEllipse(), drawCircle(), drawCirclePath(), drawFilledCircle(), drawFilledPolygon(), drawFilledRectangle(), drawLine(), drawPolygon(), drawPolygonPath(), drawRectangle(), drawRectanglePath(), drawText(), setFont(), setLineWidth(), useFillColour(), useLineColour(), and writeEPS().
creationDate_
std::string EPSGenerator::creationDate_ private
String describing the creation date of the EPS file.
Definition at line 125 of file EPSGenerator.hh.
Referenced by EPSGenerator(), and writeEPS().
creator_
std::string EPSGenerator::creator_ private
String describing the creator of the document.
Definition at line 123 of file EPSGenerator.hh.
Referenced by setCreator(), and writeEPS().
DEFAULT_MARGIN
const unsigned EPSGenerator::DEFAULT_MARGIN = 20 static private
Default margin width.
Definition at line 158 of file EPSGenerator.hh.
fillColour_
colour EPSGenerator::fillColour_ private
Current colour for filling shape backgrounds.
Definition at line 155 of file EPSGenerator.hh.
Referenced by EPSGenerator(), setFillColour(), and useFillColour().
FMT_LINETO
const std::string EPSGenerator::FMT_LINETO = " %1% %2% lineto" static private
Format string for postscript lineto command.
Definition at line 163 of file EPSGenerator.hh.
Referenced by drawLine(), and drawPolygonPath().
FMT_MOVETO
const std::string EPSGenerator::FMT_MOVETO = " %1% %2% moveto" static private
Format string for postscript moveto command.
Definition at line 161 of file EPSGenerator.hh.
Referenced by drawLine(), drawPolygonPath(), and drawRectanglePath().
FMT_RLINETO
const std::string EPSGenerator::FMT_RLINETO = " %1% %2% rlineto" static private
Format string for postscript rlineto command.
Definition at line 165 of file EPSGenerator.hh.
Referenced by drawRectanglePath().
hasTitle_
bool EPSGenerator::hasTitle_ private
True, if the EPS file has a title.
Definition at line 118 of file EPSGenerator.hh.
Referenced by setTitle(), and writeEPS().
lineColour_
colour EPSGenerator::lineColour_ private
Current drawing colour for lines.
Definition at line 153 of file EPSGenerator.hh.
Referenced by EPSGenerator(), setLineColour(), and useLineColour().
lineWidth_
unsigned EPSGenerator::lineWidth_ private
Current width of the lines drawn.
Definition at line 130 of file EPSGenerator.hh.
Referenced by setLineWidth().
maxX_
int EPSGenerator::maxX_ private
Maximum x-coordinate used before scaling & translation.
Definition at line 137 of file EPSGenerator.hh.
Referenced by appendToBounds(), and writeEPS().
maxY_
int EPSGenerator::maxY_ private
Maximum y-coordinate used before scaling & translation.
Definition at line 139 of file EPSGenerator.hh.
Referenced by appendToBounds(), and writeEPS().
minX_
int EPSGenerator::minX_ private
Minimum x-coordinate used before scaling & translation.
Definition at line 133 of file EPSGenerator.hh.
Referenced by appendToBounds(), and writeEPS().
minY_
int EPSGenerator::minY_ private
Minimum y-coordinate used before scaling & translation.
Definition at line 135 of file EPSGenerator.hh.
Referenced by appendToBounds(), and writeEPS().
scale_
double EPSGenerator::scale_ private
Final scaling factor for the eps file.
Definition at line 142 of file EPSGenerator.hh.
Referenced by setScale(), and writeEPS().
title_
std::string EPSGenerator::title_ private
Title of the EPS file.
Definition at line 120 of file EPSGenerator.hh.
Referenced by setTitle(), and writeEPS().
xMargin_
unsigned EPSGenerator::xMargin_ private
Margin to add on the left and right side of the figure in pixels.
Definition at line 148 of file EPSGenerator.hh.
Referenced by setMargins(), and writeEPS().
yMargin_
unsigned EPSGenerator::yMargin_ private
Margin to add on the top and bottom side of the figure in pixels.
Definition at line 150 of file EPSGenerator.hh.
Referenced by setMargins(), and writeEPS().
The documentation for this class was generated from the following files:
EPSGenerator.hh
EPSGenerator.cc