OpenASIP: ZoomInCmd Class Reference
ZoomInCmd Class Reference
#include <ZoomInCmd.hh>
Public Member Functions
ZoomInCmd ()
virtual ~ZoomInCmd ()
virtual bool Do ()
virtual int id () const
virtual ZoomInCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for zooming in the canvas.
Definition at line 40 of file ZoomInCmd.hh.
Constructor & Destructor Documentation
ZoomInCmd()
ZoomInCmd::ZoomInCmd ()
The Constructor.
Definition at line 45 of file ZoomInCmd.cc.
                     : EditorCommand(ProDeConstants::CMD_NAME_ZOOM_IN) {
}
Referenced by create().
~ZoomInCmd()
ZoomInCmd::~ZoomInCmd () virtual
The Destructor.
Definition at line 53 of file ZoomInCmd.cc.
                      {
}
Member Function Documentation
create()
ZoomInCmd * ZoomInCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 90 of file ZoomInCmd.cc.
{
    return new ZoomInCmd();
}
References ZoomInCmd().
Do()
bool ZoomInCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file ZoomInCmd.cc.
              {
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    canvas->zoomIn();
    return true;
}
References MDFView::canvas(), EditorCommand::view(), and MachineCanvas::zoomIn().
icon()
string ZoomInCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 101 of file ZoomInCmd.cc.
                      {
    return ProDeConstants::CMD_ICON_ZOOM_IN;
}
References ProDeConstants::CMD_ICON_ZOOM_IN.
id()
int ZoomInCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 79 of file ZoomInCmd.cc.
                    {
    return ProDeConstants::COMMAND_ZOOM_IN;
}
References ProDeConstants::COMMAND_ZOOM_IN.
isEnabled()
bool ZoomInCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 125 of file ZoomInCmd.cc.
                     {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string ZoomInCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 112 of file ZoomInCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ZOOM_IN;
}
References ProDeConstants::CMD_SNAME_ZOOM_IN.
The documentation for this class was generated from the following files:
ZoomInCmd.hh
ZoomInCmd.cc