OpenASIP: TPEF::ResourceSection Class Reference
TPEF::ResourceSection Class Reference
#include <ResourceSection.hh>
Public Member Functions
virtual ~ResourceSection ()
virtual SectionType type () const
ResourceElement & findResource (ResourceElement::ResourceType aType, HalfWord anId) const
bool hasResource (ResourceElement::ResourceType aType, HalfWord anId) const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
ResourceSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Static Private Attributes
static ResourceSection proto_
Protorype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Prosessor Resource Table section.
Definition at line 47 of file ResourceSection.hh.
Constructor & Destructor Documentation
~ResourceSection()
TPEF::ResourceSection::~ResourceSection () virtual
Destructor.
Definition at line 58 of file ResourceSection.cc.
{
}
ResourceSection()
TPEF::ResourceSection::ResourceSection (bool init) protected
Constructor.
Parameters
init True if instance should register itself to base class.
Definition at line 45 of file ResourceSection.cc.
                                          : Section() {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagNoBits();
    unsetFlagVLen();
    setStartingAddress(0);
}
References TPEF::Section::registerSection(), TPEF::Section::setStartingAddress(), TPEF::Section::unsetFlagNoBits(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
clone()
Section * TPEF::ResourceSection::clone () const protected virtual
Creates an instance of section.
Returns
Newly created section.
Implements TPEF::Section.
Definition at line 77 of file ResourceSection.cc.
{
    return new ResourceSection(false);
}
findResource()
ResourceElement & TPEF::ResourceSection::findResource (ResourceElement::ResourceType aType, HalfWord anId) const
Returns machine resource by id and type.
Todo:
Instance not found exception. After all exceptions are implemented.
Parameters
aType Type of requested resource.
anId Id of resource to find.
Returns
Matching resource.
Definition at line 91 of file ResourceSection.cc.
{
    for (Word i = 0; i < elementCount(); i++) {
        ResourceElement *elem = static_cast<ResourceElement*>(element(i));
        if (elem->type() == aType && elem->id() == anId) {
            return *elem;
        }
    }
    // just to remind about exception to throw.
    std::cerr << "Can't find resource type: " << aType
              << "\tid: " << anId << std::endl;
    assert(false);
    // added throw clause to stop compiler from complaining --Pekka
    throw new int;
}
References assert, TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::ResourceElement::id(), and TPEF::ResourceElement::type().
Referenced by TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createTerminal(), TTAProgram::TPEFProgramFactory::findBus(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), TTAProgram::TPEFProgramFactory::findGuard(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), TTAProgram::TPEFProgramFactory::findRegisterFile(), and TPEF::TPEFTools::resourceName().
hasResource()
bool TPEF::ResourceSection::hasResource (ResourceElement::ResourceType aType, HalfWord anId) const
Checks if queried resource if found from section.
Parameters
aType Type of requested resource.
anId Id of resource to find.
Returns
True if resource was found.
Definition at line 120 of file ResourceSection.cc.
{
    for (Word i = 0; i < elementCount(); i++) {
        ResourceElement *elem = static_cast<ResourceElement*>(element(i));
        if (elem->type() == aType && elem->id() == anId) {
            return true;
        }
    }
    return false;
}
References TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::ResourceElement::id(), and TPEF::ResourceElement::type().
Referenced by TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createTerminal(), TTAProgram::TPEFProgramFactory::findBus(), TTAProgram::TPEFProgramFactory::findGuard(), and TPEF::TPEFTools::resourceName().
type()
Section::SectionType TPEF::ResourceSection::type () const virtual
Returns section's type.
Returns
Type of section.
Implements TPEF::Section.
Definition at line 67 of file ResourceSection.cc.
{
    return ST_MR;
}
References TPEF::Section::ST_MR.
Member Data Documentation
proto_
ResourceSection TPEF::ResourceSection::proto_ static private
Protorype instance of section.
Definition at line 65 of file ResourceSection.hh.
The documentation for this class was generated from the following files:
ResourceSection.hh
ResourceSection.cc