OpenASIP: ToolbarButton Class Reference
ToolbarButton Class Reference
#include <ToolbarButton.hh>
Public Member Functions
ToolbarButton (int slot, const std::string &action)
ToolbarButton (const ObjectState *state)
ToolbarButton (const ToolbarButton &old)
virtual ~ToolbarButton ()
std::string action () const
int slot () const
void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_TOOLBAR_BUTTON = "tbbutton"
ObjectState name for ToolbarButton.
static const std::string OSKEY_SLOT = "slot"
ObjectState attribute key for slot position.
static const std::string OSKEY_ACTION = "action"
ObjectState attribute key for action name.
Private Attributes
int slot_
Number of the slot in which this toolbar button is.
std::string action_
Name of the action performed by this toolbar button.
Detailed Description
This class repsesents a toolbar button. It contains information which action is performed by the button and where the button is placed in the toolbar. This class implements the Serializable interface because toolbar button configurations are serialized in the configuration file.
Definition at line 48 of file ToolbarButton.hh.
Constructor & Destructor Documentation
ToolbarButton() [1/3]
ToolbarButton::ToolbarButton (int slot, const std::string & action)
Constructor.
Parameters
slot Number of the slot in which the button is placed.
action Name of the action performed by the button.
Definition at line 50 of file ToolbarButton.cc.
                             :
    slot_(slot), action_(action) {
}
ToolbarButton() [2/3]
ToolbarButton::ToolbarButton (const ObjectState * state)
Constructor.
Loads the state from the given ObjectsState object.
Definition at line 62 of file ToolbarButton.cc.
{
    loadState(state);
}
References loadState().
ToolbarButton() [3/3]
ToolbarButton::ToolbarButton (const ToolbarButton & old)
Copy constructor.
Definition at line 70 of file ToolbarButton.cc.
                                                    :
    Serializable() {
    slot_ = old.slot_;
    action_ = old.action_;
}
References action_, and slot_.
~ToolbarButton()
ToolbarButton::~ToolbarButton () virtual
Destructor.
Definition at line 80 of file ToolbarButton.cc.
{
}
Member Function Documentation
action()
std::string ToolbarButton::action () const
Returns the name of the action performed by the button.
Returns
Name of the action performed by the button.
Definition at line 90 of file ToolbarButton.cc.
{
    return action_;
}
References action_.
Referenced by GUIOptions::createToolbar(), OptionsDialog::readOptions(), and MainFrame::updateUI().
loadState()
void ToolbarButton::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Implements Serializable.
Definition at line 114 of file ToolbarButton.cc.
{
    string procName = "ToolbarButton::loadState";
    if (state->name() != OSNAME_TOOLBAR_BUTTON) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
        slot_ = state->intAttribute(OSKEY_SLOT);
        action_ = state->stringAttribute(OSKEY_ACTION);
    } catch (...) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References action_, ObjectState::intAttribute(), ObjectState::name(), OSKEY_ACTION, OSKEY_SLOT, OSNAME_TOOLBAR_BUTTON, slot_, and ObjectState::stringAttribute().
Referenced by ToolbarButton().
saveState()
ObjectState * ToolbarButton::saveState () const virtual
Creates an ObjectState object and saves the state of the object into it.
Returns
The created ObjectState object.
Implements Serializable.
Definition at line 135 of file ToolbarButton.cc.
{
    ObjectState* state = new ObjectState(OSNAME_TOOLBAR_BUTTON);
    state->setAttribute(OSKEY_SLOT, slot_);
    state->setAttribute(OSKEY_ACTION, action_);
    return state;
}
References action_, OSKEY_ACTION, OSKEY_SLOT, OSNAME_TOOLBAR_BUTTON, ObjectState::setAttribute(), and slot_.
Referenced by GUIOptions::saveState().
slot()
int ToolbarButton::slot () const
Returns the position of the slot which contains the button.
Returns
Position of the slot which contains the button.
Definition at line 101 of file ToolbarButton.cc.
{
    return slot_;
}
References slot_.
Referenced by GUIOptions::createToolbar(), OptionsDialog::readOptions(), and GUIOptions::validate().
Member Data Documentation
action_
std::string ToolbarButton::action_ private
Name of the action performed by this toolbar button.
Definition at line 72 of file ToolbarButton.hh.
Referenced by action(), loadState(), saveState(), and ToolbarButton().
OSKEY_ACTION
const string ToolbarButton::OSKEY_ACTION = "action" static
ObjectState attribute key for action name.
Definition at line 55 of file ToolbarButton.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSKEY_SLOT
const string ToolbarButton::OSKEY_SLOT = "slot" static
ObjectState attribute key for slot position.
Definition at line 53 of file ToolbarButton.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
OSNAME_TOOLBAR_BUTTON
const string ToolbarButton::OSNAME_TOOLBAR_BUTTON = "tbbutton" static
ObjectState name for ToolbarButton.
Definition at line 51 of file ToolbarButton.hh.
Referenced by GUIOptionsSerializer::convertToConfigFileFormat(), GUIOptions::loadState(), loadState(), saveState(), and GUIOptionsSerializer::setToolbarProperties().
slot_
int ToolbarButton::slot_ private
Number of the slot in which this toolbar button is.
Definition at line 70 of file ToolbarButton.hh.
Referenced by loadState(), saveState(), slot(), and ToolbarButton().
The documentation for this class was generated from the following files:
ToolbarButton.hh
ToolbarButton.cc