OpenASIP: OTAOperationDialog Class Reference
OTAOperationDialog Class Reference
#include <OTAOperationDialog.hh>
Public Member Functions
OTAOperationDialog (wxWindow *parent, TTAMachine::OperationTriggeredFormat *format)
virtual ~OTAOperationDialog ()
Private Types
enum {
ID_LABEL_OTA_OPERATION = 10000 , ID_OTA_OPERATION , ID_LIST , ID_OP_FILTER ,
ID_LINE , ID_OP_FILTER_LABEL
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
virtual bool TransferDataFromWindow ()
void onOK (wxCommandEvent &event)
void onOperationFilterChange (wxCommandEvent &event)
void onSelectOperation (wxCommandEvent &event)
int numberOfInputs () const
int numberOfOutputs () const
bool validFormatName () const
std::set< TCEString > addRISCVBaseOperations (std::set< TCEString > opset) const
Private Attributes
TCEString operation_
Name of the selected operation.
wxListBox * operationList_
Operation list widget.
TCEString opNameFilter_ = ""
A string to filter opset list.
TTAMachine::OperationTriggeredFormat * format_
Detailed Description
Dialog for editing telplate slot properties.
Definition at line 42 of file OTAOperationDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LABEL_OTA_OPERATION
ID_OTA_OPERATION
ID_LIST
ID_OP_FILTER
ID_LINE
ID_OP_FILTER_LABEL
Definition at line 75 of file OTAOperationDialog.hh.
         {
        ID_LABEL_OTA_OPERATION = 10000,
        ID_OTA_OPERATION,
        ID_LIST,
        ID_OP_FILTER,
        ID_LINE,
        ID_OP_FILTER_LABEL
    };
Constructor & Destructor Documentation
OTAOperationDialog()
OTAOperationDialog::OTAOperationDialog (wxWindow * parent, TTAMachine::OperationTriggeredFormat * format)
The Constructor.
Parameters
parent Parent window of the dialog.
format OperationTriggeredFormat format to edit.
operation Operation to edit, NULL if a new operation is being added.
Definition at line 70 of file OTAOperationDialog.cc.
                                                :
    wxDialog(parent, -1, _T("Choose operation"), wxDefaultPosition),
    operation_(""),
    format_(format) {
    createContents(this, true, true);
    operationList_ = dynamic_cast<wxListBox*>(FindWindow(ID_LIST));
    FindWindow(wxID_OK)->Disable();
}
~OTAOperationDialog()
OTAOperationDialog::~OTAOperationDialog () virtual
The Destructor.
Definition at line 86 of file OTAOperationDialog.cc.
{
}
Member Function Documentation
addRISCVBaseOperations()
std::set< TCEString > OTAOperationDialog::addRISCVBaseOperations (std::set< TCEString > opset) const private
Definition at line 141 of file OTAOperationDialog.cc.
{
    std::map<std::string, int> ops;
    if (format_->name() == RISCVFields::RISCV_R_TYPE_NAME) {
        ops = RISCVFields::RISCVRTypeOperations;
    } else if (format_->name() == RISCVFields::RISCV_I_TYPE_NAME) {
        ops = RISCVFields::RISCVITypeOperations;
    } else if (format_->name() == RISCVFields::RISCV_S_TYPE_NAME) {
        ops = RISCVFields::RISCVSTypeOperations;
    } else if (format_->name() == RISCVFields::RISCV_B_TYPE_NAME) {
        ops = RISCVFields::RISCVBTypeOperations;
    } else if (format_->name() == RISCVFields::RISCV_U_TYPE_NAME) {
        ops = RISCVFields::RISCVUTypeOperations;
    } else if (format_->name() == RISCVFields::RISCV_J_TYPE_NAME) {
        ops = RISCVFields::RISCVJTypeOperations;
    }
    for (const auto& op : ops) {
        const std::string opName = op.first;
        if (!opNameFilter_.empty() &&
            opName.find(opNameFilter_) == std::string::npos) {
            continue;
        } else if (format_->hasOperation(opName)) {
            continue;
        } else if (op.first == "lui") {
            opset.insert(opName);
            continue;
        }
        const std::string OAName = RISCVFields::RISCVOperationNameTable.at(opName);
        if (format_->machine()->hasOperation(OAName)) {
            opset.insert(opName);
        }
    }
    return opset;
}
References format_, TTAMachine::OperationTriggeredFormat::hasOperation(), TTAMachine::Machine::hasOperation(), TTAMachine::Component::machine(), TTAMachine::Component::name(), opNameFilter_, RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, RISCVFields::RISCV_U_TYPE_NAME, RISCVFields::RISCVBTypeOperations, RISCVFields::RISCVITypeOperations, RISCVFields::RISCVJTypeOperations, RISCVFields::RISCVOperationNameTable, RISCVFields::RISCVRTypeOperations, RISCVFields::RISCVSTypeOperations, and RISCVFields::RISCVUTypeOperations.
Referenced by TransferDataToWindow().
createContents()
wxSizer * OTAOperationDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Parameters
parent Parent window of the widgets.
Definition at line 289 of file OTAOperationDialog.cc.
{
    wxBoxSizer *mainSizer = new wxBoxSizer(wxVERTICAL);
    // Sizer for leftSizer and rightSizer
    wxBoxSizer *upperSizer = new wxBoxSizer(wxHORIZONTAL);
    // Sizer for oplistbox, filterlabel and filterinput
    wxBoxSizer *leftSizer = new wxBoxSizer(wxVERTICAL);
    // List of operations
    wxListBox *opListBox = new wxListBox(parent, ID_LIST, wxDefaultPosition,
        wxSize(210, 150), 0, NULL, wxLB_SINGLE|wxLB_SORT);
    leftSizer->Add(opListBox, 0, wxEXPAND|wxALL, 5);
    // Sizer for opNameFilterLabel and opNameFilter
    wxBoxSizer *filterSizer = new wxBoxSizer(wxHORIZONTAL);
    // TextLabel "Filter:"
    wxStaticText *opNameFilterLabel = new wxStaticText(parent,
        ID_OP_FILTER_LABEL, wxT("Filter:"), wxDefaultPosition, wxDefaultSize,
        0);
    // Operation filter input
    wxTextCtrl *opNameFilter = new wxTextCtrl(parent, ID_OP_FILTER, wxT(""),
        wxDefaultPosition, wxDefaultSize, 0);
    filterSizer->Add(opNameFilterLabel, 0, 0);
    filterSizer->Add(opNameFilter, 1, wxEXPAND);
    leftSizer->Add(filterSizer, 0, wxEXPAND|wxALL, 5);
    upperSizer->Add(leftSizer, 0, wxALL, 5);
    mainSizer->Add(upperSizer, 1, wxEXPAND);
    // Static line
    wxStaticLine *horisontalLine = new wxStaticLine(parent, ID_LINE,
        wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL);
    mainSizer->Add(horisontalLine, 0, wxEXPAND|wxALL, 5);
    // Sizer for Cancel and OK buttons
    wxBoxSizer *buttonsSizer = new wxBoxSizer(wxHORIZONTAL);
    // Cancel button
    wxButton *cancelButton = new wxButton(parent, wxID_CANCEL, wxT("&Cancel"),
        wxDefaultPosition, wxDefaultSize, 0);
    buttonsSizer->Add(cancelButton, 0, wxALIGN_CENTER|wxALL, 5);
    // OK button
    wxButton *okButton = new wxButton(parent, wxID_OK, wxT("&OK"),
        wxDefaultPosition, wxDefaultSize, 0);
    buttonsSizer->Add(okButton, 0, wxALIGN_CENTER|wxALL, 5);
    mainSizer->Add(buttonsSizer, 0, 0, 5);
    if (set_sizer) {
        parent->SetSizer(mainSizer);
        if (call_fit) {
            mainSizer->SetSizeHints( parent );
        }
    }
    return mainSizer;
}
References ID_LINE, ID_LIST, ID_OP_FILTER, and ID_OP_FILTER_LABEL.
numberOfInputs()
int OTAOperationDialog::numberOfInputs () const private
Definition at line 90 of file OTAOperationDialog.cc.
{
    if (format_->name() == RISCVFields::RISCV_R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_I_TYPE_NAME) {
        return 2;
    }
    if (format_->name() == RISCVFields::RISCV_S_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_B_TYPE_NAME) {
        return 3;
    }
    if (format_->name() == RISCVFields::RISCV_U_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_J_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_R1R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_R1_TYPE_NAME) {
        return 1;
    }
    if (format_->name() == RISCVFields::RISCV_R3R_TYPE_NAME) {
        return 3;
    }
    return 0;
}
References format_, TTAMachine::Component::name(), RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, and RISCVFields::RISCV_U_TYPE_NAME.
Referenced by TransferDataToWindow().
numberOfOutputs()
int OTAOperationDialog::numberOfOutputs () const private
Definition at line 112 of file OTAOperationDialog.cc.
{
    if (format_->name() == RISCVFields::RISCV_R_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_R1R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_I_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_U_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_R3R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_J_TYPE_NAME) {
        return 1;
    }
    return 0;
}
References format_, TTAMachine::Component::name(), RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, and RISCVFields::RISCV_U_TYPE_NAME.
Referenced by TransferDataToWindow().
onOK()
void OTAOperationDialog::onOK (wxCommandEvent & event) private
Event handler for the OK button.
Definition at line 238 of file OTAOperationDialog.cc.
{
    if (operationList_->GetSelection() == wxNOT_FOUND) {
        wxString message = _T("No operation selected.");
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    if (!format_->hasOperation(operation_)) {
        format_->addOperation(operation_);
    }
    TransferDataFromWindow();
    EndModal(wxID_OK);
}
References TTAMachine::OperationTriggeredFormat::addOperation(), format_, TTAMachine::OperationTriggeredFormat::hasOperation(), operation_, operationList_, and TransferDataFromWindow().
onOperationFilterChange()
void OTAOperationDialog::onOperationFilterChange (wxCommandEvent & event) private
Event handler for opset filtering.
Definition at line 270 of file OTAOperationDialog.cc.
{
    std::string pattern(event.GetString().mb_str());
    std::string::iterator it;
    it = std::remove_if(pattern.begin(), pattern.end(), [](const char& c) {
        return c == ' ';
    });
    pattern.erase(it, pattern.end());
    for (auto& c : pattern) c = toupper(c);
    opNameFilter_ = pattern;
    opNameFilter_ = opNameFilter_.lower();
    OTAOperationDialog::TransferDataToWindow();
}
References TCEString::lower(), opNameFilter_, and TransferDataToWindow().
onSelectOperation()
void OTAOperationDialog::onSelectOperation (wxCommandEvent & event) private
Event handler for the operation list selections.
Enables and disables the OK button. Displays operation description and ports count.
Definition at line 259 of file OTAOperationDialog.cc.
{
    FindWindow(wxID_OK)->Enable(operationList_->GetSelection() != wxNOT_FOUND);
    operation_ = WxConversion::toString(operationList_->GetStringSelection());
}
References operation_, operationList_, and WxConversion::toString().
TransferDataFromWindow()
bool OTAOperationDialog::TransferDataFromWindow () private virtual
Reads user choices from the dialog widgets.
Definition at line 229 of file OTAOperationDialog.cc.
{
    operation_ = WxConversion::toString(operationList_->GetStringSelection());
    return true;
}
References operation_, operationList_, and WxConversion::toString().
Referenced by onOK().
TransferDataToWindow()
bool OTAOperationDialog::TransferDataToWindow () private virtual
Transfers data to the opset list.
Definition at line 180 of file OTAOperationDialog.cc.
{
    operationList_->Clear();
    std::set<TCEString> opset;
    if (format_->name() == RISCVFields::RISCV_R_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_R3R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_R1R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_R1_TYPE_NAME) {
        Machine::FunctionUnitNavigator nav =
            format_->machine()->functionUnitNavigator();
        for (int i = 0; i < nav.count(); i++) {
            FunctionUnit* fu = nav.item(i);
            for (int j = 0; j < fu->operationCount(); j++) {
                HWOperation* op = fu->operation(j);
                TCEString opName =op->name();
                opName = opName.lower();
                if (!opNameFilter_.empty() &&
                    opName.find(opNameFilter_) == std::string::npos) {
                    continue;
                } else if (format_->hasOperation(opName)) {
                    continue;
                } else if (op->numberOfInputs() != numberOfInputs()) {
                    continue;
                } else if (op->numberOfOutputs() != numberOfOutputs()) {
                    continue;
                } else if (MapTools::containsValue(
                    RISCVFields::RISCVOperationNameTable, opName)) {
                        continue;
                }
                opset.insert(opName);
            }
        }
    }
    opset = addRISCVBaseOperations(opset);
    for (const auto& opName : opset) {
        operationList_->Append(WxConversion::toWxString(opName));
    }
    return true;
}
References addRISCVBaseOperations(), MapTools::containsValue(), TTAMachine::Machine::Navigator< ComponentType >::count(), format_, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::OperationTriggeredFormat::hasOperation(), TTAMachine::Machine::Navigator< ComponentType >::item(), TCEString::lower(), TTAMachine::Component::machine(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::HWOperation::numberOfInputs(), numberOfInputs(), TTAMachine::HWOperation::numberOfOutputs(), numberOfOutputs(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), operationList_, opNameFilter_, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCVOperationNameTable, and WxConversion::toWxString().
Referenced by onOperationFilterChange().
validFormatName()
bool OTAOperationDialog::validFormatName () const private
Definition at line 125 of file OTAOperationDialog.cc.
{
    if (format_->name() == RISCVFields::RISCV_R_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_R1_TYPE_NAME  ||
        format_->name() == RISCVFields::RISCV_R1R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_R3R_TYPE_NAME ||
        format_->name() == RISCVFields::RISCV_I_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_S_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_B_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_U_TYPE_NAME   ||
        format_->name() == RISCVFields::RISCV_J_TYPE_NAME) {
        return true;
    }
    return false;
}
References format_, TTAMachine::Component::name(), RISCVFields::RISCV_B_TYPE_NAME, RISCVFields::RISCV_I_TYPE_NAME, RISCVFields::RISCV_J_TYPE_NAME, RISCVFields::RISCV_R1_TYPE_NAME, RISCVFields::RISCV_R1R_TYPE_NAME, RISCVFields::RISCV_R3R_TYPE_NAME, RISCVFields::RISCV_R_TYPE_NAME, RISCVFields::RISCV_S_TYPE_NAME, and RISCVFields::RISCV_U_TYPE_NAME.
Member Data Documentation
format_
TTAMachine::OperationTriggeredFormat* OTAOperationDialog::format_ private
Definition at line 72 of file OTAOperationDialog.hh.
Referenced by addRISCVBaseOperations(), numberOfInputs(), numberOfOutputs(), onOK(), TransferDataToWindow(), and validFormatName().
operation_
TCEString OTAOperationDialog::operation_ private
Name of the selected operation.
Definition at line 66 of file OTAOperationDialog.hh.
Referenced by onOK(), onSelectOperation(), and TransferDataFromWindow().
operationList_
wxListBox* OTAOperationDialog::operationList_ private
Operation list widget.
Definition at line 68 of file OTAOperationDialog.hh.
Referenced by onOK(), onSelectOperation(), TransferDataFromWindow(), and TransferDataToWindow().
opNameFilter_
TCEString OTAOperationDialog::opNameFilter_ = "" private
A string to filter opset list.
Definition at line 70 of file OTAOperationDialog.hh.
Referenced by addRISCVBaseOperations(), onOperationFilterChange(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
OTAOperationDialog.hh
OTAOperationDialog.cc