OpenASIP: TPEF::RelocElement Class Reference
TPEF::RelocElement Class Reference
#include <RelocElement.hh>
Public Types
enum RelocType { RT_NOREL = 0x00 , RT_SELF = 0x01 , RT_PAGE = 0x02 , RT_PCREL = 0x03 }
Public Member Functions
RelocElement ()
virtual ~RelocElement ()
RelocType type () const
void setType (RelocType aType)
SectionElement * location () const
void setLocation (SectionElement *aLocation)
void setLocation (const ReferenceManager::SafePointer *aLocation)
SectionElement * destination () const
void setDestination (SectionElement *aDestination)
void setDestination (const ReferenceManager::SafePointer *aDestination)
Byte size () const
void setSize (Byte aSize)
Byte bitOffset () const
void setBitOffset (Byte anOffset)
SymbolElement * symbol () const
void setSymbol (SymbolElement *aSymbol)
void setSymbol (const ReferenceManager::SafePointer *aSymbol)
ASpaceElement * aSpace () const
void setASpace (ASpaceElement *anASpace)
void setASpace (const ReferenceManager::SafePointer *anASpace)
bool chunked () const
void setChunked (bool isChunked)
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
RelocType type_
The type of the relocation.
const ReferenceManager::SafePointer * location_
The element containing location to be relocated.
const ReferenceManager::SafePointer * destination_
The destination element of the location to be relocated.
Byte size_
Bit width of value(or chunk of value) to be relocated.
Byte bitOffset_
Bit offset where in whole value bits of this chunk should be.
const ReferenceManager::SafePointer * symbol_
The symbol of relocation.
const ReferenceManager::SafePointer * aSpace_
The address space of relocated element.
bool chunked_
Does relocation refer to chunked address.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Relocation table entry.
Definition at line 51 of file RelocElement.hh.
Member Enumeration Documentation
RelocType
enum TPEF::RelocElement::RelocType
TPEF relocation types.
Enumerator
RT_NOREL
No relocation.
RT_SELF
Absolute address, relocate relative to address self.
RT_PAGE
Paged address, relocate page offset.
RT_PCREL
PC-relative, relocate only if displacement changes.
Definition at line 56 of file RelocElement.hh.
                   {
        RT_NOREL     = 0x00,   ///< No relocation
        RT_SELF      = 0x01,   ///< Absolute address, relocate relative to
                               ///< address self.
        RT_PAGE      = 0x02,   ///< Paged address, relocate page offset.
        RT_PCREL     = 0x03    ///< PC-relative, relocate only if
                               ///< displacement changes.
    };
Constructor & Destructor Documentation
RelocElement()
TPEF::RelocElement::RelocElement ()
Constructor.
Definition at line 46 of file RelocElement.cc.
                           :
    SectionElement(), type_(RT_NOREL), location_(&SafePointer::null),
    destination_(&SafePointer::null), size_(0), bitOffset_(0),
    symbol_(&SafePointer::null), aSpace_(&SafePointer::null),
    chunked_(false) {
}
~RelocElement()
TPEF::RelocElement::~RelocElement () virtual
Destructor.
Definition at line 56 of file RelocElement.cc.
{
}
Member Function Documentation
aSpace()
ASpaceElement * TPEF::RelocElement::aSpace () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::TPEFProgramFactory::createInstruction(), TTAProgram::TPEFProgramFactory::createTerminal(), TPEF::TPEFRelocSectionReader::finalize(), and TPEFDumper::section().
bitOffset()
Byte TPEF::RelocElement::bitOffset () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData().
chunked()
bool TPEF::RelocElement::chunked () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData().
destination()
SectionElement * TPEF::RelocElement::destination () const
Referenced by TTAProgram::TPEFProgramFactory::createDataMemories(), TPEF::AOutRelocationSectionReader::finalize(), CodeCompressorPlugin::initializeRelocations(), ProgramImageGenerator::relocTarget(), and TPEFDumper::section().
location()
SectionElement * TPEF::RelocElement::location () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createDataMemories(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::TPEFRelocSectionReader::finalize(), TPEF::TPEFTools::hasRelocation(), CodeCompressorPlugin::initializeRelocations(), TPEF::TPEFTools::initRelocationCache(), TPEF::TPEFTools::relocation(), ProgramImageGenerator::relocTarget(), and TPEFDumper::section().
setASpace() [1/2]
void TPEF::RelocElement::setASpace (ASpaceElement * anASpace)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::finalize(), and TPEF::TPEFRelocSectionReader::readData().
setASpace() [2/2]
void TPEF::RelocElement::setASpace (const ReferenceManager::SafePointer * anASpace)
setBitOffset()
void TPEF::RelocElement::setBitOffset (Byte anOffset)
Referenced by TPEF::TPEFRelocSectionReader::readData().
setChunked()
void TPEF::RelocElement::setChunked (bool isChunked)
Referenced by LabelManager::finalize(), and TPEF::TPEFRelocSectionReader::readData().
setDestination() [1/2]
void TPEF::RelocElement::setDestination (const ReferenceManager::SafePointer * aDestination)
setDestination() [2/2]
void TPEF::RelocElement::setDestination (SectionElement * aDestination)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::TPEFRelocSectionReader::finalize(), and TPEF::AOutRelocationSectionReader::initializeRelocElement().
setLocation() [1/2]
void TPEF::RelocElement::setLocation (const ReferenceManager::SafePointer * aLocation)
setLocation() [2/2]
void TPEF::RelocElement::setLocation (SectionElement * aLocation)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::initializeRelocElement(), and TPEF::TPEFRelocSectionReader::readData().
setSize()
void TPEF::RelocElement::setSize (Byte aSize)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::initializeRelocElement(), and TPEF::TPEFRelocSectionReader::readData().
setSymbol() [1/2]
void TPEF::RelocElement::setSymbol (const ReferenceManager::SafePointer * aSymbol)
setSymbol() [2/2]
void TPEF::RelocElement::setSymbol (SymbolElement * aSymbol)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::initializeRelocElement(), and TPEF::TPEFRelocSectionReader::readData().
setType()
void TPEF::RelocElement::setType (RelocType aType)
Referenced by TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::AOutRelocationSectionReader::initializeRelocElement(), and TPEF::TPEFRelocSectionReader::readData().
size()
Byte TPEF::RelocElement::size () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData(), TTAProgram::TPEFProgramFactory::createDataMemories(), TPEF::TPEFRelocSectionReader::finalize(), and TPEFDumper::section().
symbol()
SymbolElement * TPEF::RelocElement::symbol () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData(), and TPEFDumper::section().
type()
RelocType TPEF::RelocElement::type () const
Referenced by TPEF::TPEFRelocSectionWriter::actualWriteData(), TPEF::TPEFRelocSectionReader::finalize(), and TPEFDumper::section().
Member Data Documentation
aSpace_
const ReferenceManager::SafePointer* TPEF::RelocElement::aSpace_ private
The address space of relocated element.
Definition at line 110 of file RelocElement.hh.
bitOffset_
Byte TPEF::RelocElement::bitOffset_ private
Bit offset where in whole value bits of this chunk should be.
Definition at line 106 of file RelocElement.hh.
chunked_
bool TPEF::RelocElement::chunked_ private
Does relocation refer to chunked address.
Definition at line 112 of file RelocElement.hh.
destination_
const ReferenceManager::SafePointer* TPEF::RelocElement::destination_ private
The destination element of the location to be relocated.
Definition at line 102 of file RelocElement.hh.
location_
const ReferenceManager::SafePointer* TPEF::RelocElement::location_ private
The element containing location to be relocated.
Definition at line 100 of file RelocElement.hh.
size_
Byte TPEF::RelocElement::size_ private
Bit width of value(or chunk of value) to be relocated.
Definition at line 104 of file RelocElement.hh.
symbol_
const ReferenceManager::SafePointer* TPEF::RelocElement::symbol_ private
The symbol of relocation.
Definition at line 108 of file RelocElement.hh.
type_
RelocType TPEF::RelocElement::type_ private
The type of the relocation.
Definition at line 98 of file RelocElement.hh.
The documentation for this class was generated from the following files:
RelocElement.hh
RelocElement.cc