OpenASIP: CallExplorerPluginWindow Class Reference
CallExplorerPluginWindow Class Reference
#include <CallExplorerPlugin.hh>
Public Member Functions
CallExplorerPluginWindow (wxWindow *parent, TTAMachine::Machine &machine, Model &model)
virtual ~CallExplorerPluginWindow ()
Private Types
enum {
ID_TEXT = 10000 , ID_PLUGIN_CHOOSER , ID_DESCRIPTION_FIELD , ID_PARAM_LIST ,
ID_EDIT , ID_RUN
}
Private Member Functions
virtual bool TransferDataToWindow ()
void onClose (wxCommandEvent &event)
void onEdit (wxCommandEvent &)
void onRun (wxCommandEvent &event)
void onSelectPlugin (wxCommandEvent &event)
void onParamActivate (wxListEvent &event)
void onParamSelect (wxListEvent &event)
void onParamDeSelect (wxListEvent &event)
void doEdit ()
void updateParameterList ()
void setTexts ()
ExplorerPluginParameter getParam (int paramNum)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
TTAMachine::Machine & machine_
Machine that is being modified.
Model & model_
The model.
wxComboBox * pluginNames_
Plugin names combo box.
wxTextCtrl * pluginDescription_
description text field
wxListCtrl * parameterList_
Parameter list;.
wxButton * editButton
Edit button.
wxButton * runButton
Run button.
int selectedParam_
Selected parameter, or -1.
DesignSpaceExplorer explorer_
std::vector< DesignSpaceExplorerPlugin * > plugins_
DesignSpaceExplorerPlugin * selectedPlugin_
Detailed Description
Explorer plugin call window.
Definition at line 52 of file CallExplorerPlugin.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_TEXT
ID_PLUGIN_CHOOSER
ID_DESCRIPTION_FIELD
ID_PARAM_LIST
ID_EDIT
ID_RUN
Definition at line 98 of file CallExplorerPlugin.hh.
         {
        ID_TEXT = 10000,
        ID_PLUGIN_CHOOSER,
        ID_DESCRIPTION_FIELD,
        ID_PARAM_LIST,
        ID_EDIT,
        ID_RUN
    };
Constructor & Destructor Documentation
CallExplorerPluginWindow()
CallExplorerPluginWindow::CallExplorerPluginWindow (wxWindow * parent, TTAMachine::Machine & machine, Model & model)
The Constructor.
Parameters
parent Parent window of the dialog.
addressSpace The address space to be modified with the dialog.
Definition at line 81 of file CallExplorerPlugin.cc.
                 :
    wxDialog(parent, -1, _T(""), wxDefaultPosition), machine_(machine),
    model_(model),
    selectedParam_(-1),
    selectedPlugin_(0) {
    createContents(this, true, true);
    pluginNames_ =
        dynamic_cast<wxComboBox*>(FindWindow(ID_PLUGIN_CHOOSER));
    pluginDescription_ =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_DESCRIPTION_FIELD));
    parameterList_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_PARAM_LIST));
    editButton =
        dynamic_cast<wxButton*>(FindWindow(ID_EDIT));
    runButton =
        dynamic_cast<wxButton*>(FindWindow(ID_RUN));
    // Get explorer plugin names.
    std::vector<DesignSpaceExplorerPlugin*> plugins = explorer_.getPlugins();
    std::set<string> addedPlugins;
    for (std::size_t i = 0; i < plugins.size(); i++) {
        DesignSpaceExplorerPlugin *plugin = plugins[i];
        if (plugin->producesArchitecture() &&
            !plugin->requiresHDB() &&
            !plugin->requiresSimulationData() &&
            addedPlugins.find(plugin->name()) == addedPlugins.end()) {
            plugins_.push_back(plugin);
            addedPlugins.insert(plugin->name());
        }
    }
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
References DesignSpaceExplorerPlugin::name(), DesignSpaceExplorerPlugin::producesArchitecture(), DesignSpaceExplorerPlugin::requiresHDB(), and DesignSpaceExplorerPlugin::requiresSimulationData().
~CallExplorerPluginWindow()
CallExplorerPluginWindow::~CallExplorerPluginWindow () virtual
The Destructor.
Definition at line 135 of file CallExplorerPlugin.cc.
{
}
Member Function Documentation
createContents()
wxSizer * CallExplorerPluginWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 380 of file CallExplorerPlugin.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    item1->AddGrowableCol( 1 );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Explorer Plugin:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxFIXED_MINSIZE|wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxComboBox *item3 = new wxComboBox( parent, ID_PLUGIN_CHOOSER, wxT(""), wxDefaultPosition, wxDefaultSize, 0, strs3, wxCB_DROPDOWN );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_TEXT, wxT("Plugin Description:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxFIXED_MINSIZE|wxALL, 5 );
    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_DESCRIPTION_FIELD, wxT(""), wxDefaultPosition, wxSize(240,150), wxTE_MULTILINE|wxTE_READONLY );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("Plugin Parameters:"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item6, 0, wxALL, 5 );
    wxListCtrl *item7 = new wxListCtrl( parent, ID_PARAM_LIST, wxDefaultPosition, wxSize(400,200), wxLC_REPORT|wxSUNKEN_BORDER );
    item0->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxGridSizer *item8 = new wxGridSizer( 3, 0, 0 );
    item0->Add( item8, 0, wxGROW, 5 );
    wxGridSizer *item9 = new wxGridSizer( 3, 0, 0 );
    wxButton *item10 = new wxButton( parent, ID_EDIT, wxT("&Edit Parameter..."), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALL, 5 );
    wxButton *item11 = new wxButton( parent, ID_RUN, wxT("&Run Plugin"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item13 = new wxButton( parent, wxID_CLOSE, wxT("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    item9->Add( item12, 0, wxALL, 5 );
    item0->Add( item9, 0, wxGROW, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_DESCRIPTION_FIELD, ID_EDIT, ID_PARAM_LIST, ID_PLUGIN_CHOOSER, ID_RUN, and ID_TEXT.
doEdit()
void CallExplorerPluginWindow::doEdit () private
Starts parameter editor
Definition at line 310 of file CallExplorerPlugin.cc.
{
    if (selectedParam_ == -1) {
        return;
    }
    ExplorerPluginParameter param = getParam(selectedParam_);
    EditParameterDialog diag(this, &param);
    diag.ShowModal();
    selectedPlugin_->giveParameter(param.name(), param.value());
    updateParameterList();
}
References getParam(), DesignSpaceExplorerPlugin::giveParameter(), ExplorerPluginParameter::name(), selectedParam_, selectedPlugin_, updateParameterList(), and ExplorerPluginParameter::value().
Referenced by onEdit(), and onParamActivate().
getParam()
ExplorerPluginParameter CallExplorerPluginWindow::getParam (int paramNum) private
Gets param from param index
Definition at line 354 of file CallExplorerPlugin.cc.
{
    DesignSpaceExplorerPlugin::ParameterMap params = selectedPlugin_->parameters();
    DesignSpaceExplorerPlugin::ParameterMap::iterator it = params.begin();
    for (int i =0; it != params.end(); ++it, ++i) {
        if (i == paramNum) {
            return it->second;
        }
    }
    return ExplorerPluginParameter("", INT, false, "");
}
References INT, DesignSpaceExplorerPlugin::parameters(), and selectedPlugin_.
Referenced by doEdit().
onClose()
void CallExplorerPluginWindow::onClose (wxCommandEvent & event) private
Validates input in the controls, and updates the AddressSpace.
Definition at line 189 of file CallExplorerPlugin.cc.
{
    EndModal(wxID_CANCEL);
}
onEdit()
void CallExplorerPluginWindow::onEdit (wxCommandEvent &) private
Editing selected parameter
Definition at line 197 of file CallExplorerPlugin.cc.
{
    doEdit();
}
References doEdit().
onParamActivate()
void CallExplorerPluginWindow::onParamActivate (wxListEvent & event) private
Parameter was doubleclicked
Definition at line 258 of file CallExplorerPlugin.cc.
{
    selectedParam_ = event.GetIndex();
    doEdit();
}
References doEdit(), and selectedParam_.
onParamDeSelect()
void CallExplorerPluginWindow::onParamDeSelect (wxListEvent & event) private
Parameter was deselected
Definition at line 275 of file CallExplorerPlugin.cc.
{
    selectedParam_ = -1;
}
References selectedParam_.
onParamSelect()
void CallExplorerPluginWindow::onParamSelect (wxListEvent & event) private
Parameter was selected
Definition at line 267 of file CallExplorerPlugin.cc.
{
    selectedParam_ = event.GetIndex();
}
References selectedParam_.
onRun()
void CallExplorerPluginWindow::onRun (wxCommandEvent & event) private
Runs the plugin
Definition at line 206 of file CallExplorerPlugin.cc.
{
    // no plugin selected?
    if (selectedPlugin_ == 0) {
        return;
    }
    // open up a temporary dsdb
    const string dsdbFile = "tmp.dsdb";
    FileSystem::removeFileOrDirectory(dsdbFile);
    DSDBManager* dsdb = DSDBManager::createNew(dsdbFile);
    RowID archID = dsdb->addArchitecture(machine_);
    // no implementation?
    DSDBManager::MachineConfiguration confIn(archID, false, ILLEGAL_ROW_ID);
    RowID confID = dsdb->addConfiguration(confIn);
    // run the plugin
    try {
        selectedPlugin_->setDSDB(*dsdb);
        std::vector<RowID> result = selectedPlugin_->explore(confID, 0);
        // store the new machine
        TTAMachine::Machine& machine =
            *dsdb->architecture(confID+result.size());
        model_.getMachine()->copyFromMachine(machine);
    } catch (KeyNotFound& e) {
        // no new adf created by the plugin. just exit
        InformationDialog diag(
            this, WxConversion::toWxString(e.errorMessage()));
        diag.ShowModal();
        FileSystem::removeFileOrDirectory(dsdbFile);
        EndModal(wxID_CANCEL);
        return;
    } catch (Exception& e) {
        // error in parameters
        InformationDialog diag(
            this, WxConversion::toWxString(e.errorMessage()));
        diag.ShowModal();
        FileSystem::removeFileOrDirectory(dsdbFile);
        return;
    }
    FileSystem::removeFileOrDirectory(dsdbFile);
    EndModal(wxID_OK);
}
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::architecture(), TTAMachine::Machine::copyFromMachine(), DSDBManager::createNew(), Exception::errorMessage(), DesignSpaceExplorerPlugin::explore(), Model::getMachine(), ILLEGAL_ROW_ID, machine, machine_, model_, FileSystem::removeFileOrDirectory(), selectedPlugin_, DesignSpaceExplorer::setDSDB(), and WxConversion::toWxString().
onSelectPlugin()
void CallExplorerPluginWindow::onSelectPlugin (wxCommandEvent & event) private
A plugin was selected
Definition at line 284 of file CallExplorerPlugin.cc.
{
    string pluginName =
        WxConversion::toString(pluginNames_->GetValue());
    // get current plugin
    for (size_t i = 0; i < plugins_.size(); i++) {
        if (plugins_.at(i)->name() == pluginName) {
            selectedPlugin_ = plugins_.at(i);
            break;
        }
    }
    // set description field
    pluginDescription_->Clear();
    pluginDescription_->AppendText(WxConversion::toWxString(
        selectedPlugin_->description()));
    updateParameterList();
}
References DesignSpaceExplorerPlugin::description(), pluginDescription_, pluginNames_, plugins_, selectedPlugin_, WxConversion::toString(), WxConversion::toWxString(), and updateParameterList().
setTexts()
void CallExplorerPluginWindow::setTexts () private
Sets texts for widgets.
Definition at line 143 of file CallExplorerPlugin.cc.
{
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_CALL_EXPLORER_PLUGIN_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // Get explorer plugin names into combo box
    for (size_t i = 0; i < plugins_.size(); ++i) {
        wxString pluginName =  WxConversion::toWxString(plugins_.at(i)->name());
        pluginNames_->Append(pluginName);
    }
    // Set parameter list column titles
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    parameterList_->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_CENTER, 160);
    //fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_COMPULSORY);
    //parameterList_->InsertColumn(1, WxConversion::toWxString(fmt.str()),
    //                       wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_TYPE);
    parameterList_->InsertColumn(2, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 100);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_VALUE);
    parameterList_->InsertColumn(3, WxConversion::toWxString(fmt.str()),
                           wxLIST_FORMAT_LEFT, 160);
}
References ProDeTextGenerator::instance(), parameterList_, pluginNames_, plugins_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_CALL_EXPLORER_PLUGIN_TITLE, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_TYPE, and ProDeTextGenerator::TXT_COLUMN_VALUE.
TransferDataToWindow()
bool CallExplorerPluginWindow::TransferDataToWindow () private virtual
Transfers data from the AddressSpace object to the dialog widgets.
Returns
false, if an error occured in the transfer, true otherwise.
Definition at line 179 of file CallExplorerPlugin.cc.
{
    return wxWindow::TransferDataToWindow();
}
updateParameterList()
void CallExplorerPluginWindow::updateParameterList () private
Updates parameter list
Definition at line 327 of file CallExplorerPlugin.cc.
{
    parameterList_->DeleteAllItems();
    DesignSpaceExplorerPlugin::ParameterMap params = selectedPlugin_->parameters();
    DesignSpaceExplorerPlugin::ParameterMap::iterator it = params.begin();
    for (int i =0; it != params.end(); ++it, ++i) {
        ExplorerPluginParameter parameter = it->second;
        string name = parameter.name();
        string type = parameter.typeAsString();
        string value = parameter.value();
        //string compulsory = parameter.isCompulsory() ? "x" : "";
        parameterList_->InsertItem(i, WxConversion::toWxString(name), 0);
        //parameterList_->SetItem(i, 1, WxConversion::toWxString(compulsory));
        parameterList_->SetItem(i, 1, WxConversion::toWxString(type));
        parameterList_->SetItem(i, 2, WxConversion::toWxString(value));
    }
}
References ExplorerPluginParameter::name(), parameterList_, DesignSpaceExplorerPlugin::parameters(), selectedPlugin_, WxConversion::toWxString(), ExplorerPluginParameter::typeAsString(), and ExplorerPluginParameter::value().
Referenced by doEdit(), and onSelectPlugin().
Member Data Documentation
editButton
wxButton* CallExplorerPluginWindow::editButton private
Edit button.
Definition at line 91 of file CallExplorerPlugin.hh.
explorer_
DesignSpaceExplorer CallExplorerPluginWindow::explorer_ private
Definition at line 107 of file CallExplorerPlugin.hh.
machine_
TTAMachine::Machine& CallExplorerPluginWindow::machine_ private
Machine that is being modified.
Definition at line 80 of file CallExplorerPlugin.hh.
Referenced by onRun().
model_
Model& CallExplorerPluginWindow::model_ private
The model.
Definition at line 82 of file CallExplorerPlugin.hh.
Referenced by onRun().
parameterList_
wxListCtrl* CallExplorerPluginWindow::parameterList_ private
Parameter list;.
Definition at line 89 of file CallExplorerPlugin.hh.
Referenced by setTexts(), and updateParameterList().
pluginDescription_
wxTextCtrl* CallExplorerPluginWindow::pluginDescription_ private
description text field
Definition at line 87 of file CallExplorerPlugin.hh.
Referenced by onSelectPlugin().
pluginNames_
wxComboBox* CallExplorerPluginWindow::pluginNames_ private
Plugin names combo box.
Definition at line 85 of file CallExplorerPlugin.hh.
Referenced by onSelectPlugin(), and setTexts().
plugins_
std::vector<DesignSpaceExplorerPlugin*> CallExplorerPluginWindow::plugins_ private
Definition at line 108 of file CallExplorerPlugin.hh.
Referenced by onSelectPlugin(), and setTexts().
runButton
wxButton* CallExplorerPluginWindow::runButton private
Run button.
Definition at line 93 of file CallExplorerPlugin.hh.
selectedParam_
int CallExplorerPluginWindow::selectedParam_ private
Selected parameter, or -1.
Definition at line 95 of file CallExplorerPlugin.hh.
Referenced by doEdit(), onParamActivate(), onParamDeSelect(), and onParamSelect().
selectedPlugin_
DesignSpaceExplorerPlugin* CallExplorerPluginWindow::selectedPlugin_ private
Definition at line 109 of file CallExplorerPlugin.hh.
Referenced by doEdit(), getParam(), onRun(), onSelectPlugin(), and updateParameterList().
The documentation for this class was generated from the following files:
CallExplorerPlugin.hh
CallExplorerPlugin.cc