OpenASIP: GCUDialog Class Reference
GCUDialog Class Reference
#include <GCUDialog.hh>
Public Member Functions
GCUDialog (wxWindow *parent, TTAMachine::ControlUnit *gcu)
virtual ~GCUDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_TEXT , ID_DELAY_SLOTS , ID_ADDRESS_SPACE ,
ID_OPERATION_LIST , ID_PORT_LIST , ID_RA_CHOICE , ID_OP_CHOICE ,
ID_LINE , ID_ADD_OPERATION , ID_EDIT_OPERATION , ID_DELETE_OPERATION ,
ID_ADD_FU_PORT , ID_ADD_SR_PORT , ID_EDIT_PORT , ID_DELETE_PORT ,
ID_HELP , ID_TEXT_NAME , ID_TEXT_DS , ID_TEXT_AS ,
ID_TEXT_INPUT_SOCKET , ID_TEXT_OUTPUT_SOCKET , ID_TEXT_RA_WIDTH , ID_LABEL_RA_CHOICE ,
ID_LABEL_OP_CHOICE
}
enumerated IDs for dialog controls
Private Member Functions
virtual bool TransferDataToWindow ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void updateAddressSpaceChoice ()
void updateSocketChoicers ()
void updateOperationList ()
void updatePortList ()
void updateRAPortChoice ()
TTAMachine::HWOperation * selectedOperation ()
TTAMachine::BaseFUPort * selectedPort ()
void onName (wxCommandEvent &event)
void onOperationSelection (wxListEvent &event)
void onAddOperation (wxCommandEvent &event)
void onEditOperation (wxCommandEvent &event)
void onDeleteOperation (wxCommandEvent &event)
void onActivateOperation (wxListEvent &event)
void onOperationRightClick (wxListEvent &event)
void onAddFUPort (wxCommandEvent &event)
void onAddSRPort (wxCommandEvent &event)
void onEditPort (wxCommandEvent &event)
void onDeletePort (wxCommandEvent &event)
void onPortSelection (wxListEvent &event)
void onActivatePort (wxListEvent &event)
void onPortRightClick (wxListEvent &event)
void onRAPortChoice (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void setLabels ()
Private Attributes
TTAMachine::ControlUnit * gcu_
The Global Control Unit to be modified with the dialog.
wxString name_
Name of the global control unit.
int delaySlots_
Number of delay slots of the global control unit.
int guardLatency_
Guard latency of the gcu.
wxChoice * addressSpaceChoice_
Address Space choice control.
wxChoice * raPortChoice_
Return address port choice control.
wxListCtrl * operationList_
Operation list widget.
wxListCtrl * portList_
Port list widget.
wxStaticBoxSizer * operationsSizer_
Box sizer for the operations list controls.
wxStaticBoxSizer * portListSizer_
Box sizer for the port list controls.
Detailed Description
Dialog for adding a new Global Control Unit to the Machine and editing existing Global Control Unit attributes.
Definition at line 48 of file GCUDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
enumerated IDs for dialog controls
Enumerator
ID_NAME
ID_TEXT
ID_DELAY_SLOTS
ID_ADDRESS_SPACE
ID_OPERATION_LIST
ID_PORT_LIST
ID_RA_CHOICE
ID_OP_CHOICE
ID_LINE
ID_ADD_OPERATION
ID_EDIT_OPERATION
ID_DELETE_OPERATION
ID_ADD_FU_PORT
ID_ADD_SR_PORT
ID_EDIT_PORT
ID_DELETE_PORT
ID_HELP
ID_TEXT_NAME
ID_TEXT_DS
ID_TEXT_AS
ID_TEXT_INPUT_SOCKET
ID_TEXT_OUTPUT_SOCKET
ID_TEXT_RA_WIDTH
ID_LABEL_RA_CHOICE
ID_LABEL_OP_CHOICE
Definition at line 111 of file GCUDialog.hh.
         {
        ID_NAME = 10000,
        ID_TEXT,
        ID_DELAY_SLOTS,
        //ID_GUARD_LATENCY,
        ID_ADDRESS_SPACE,
        ID_OPERATION_LIST,
        ID_PORT_LIST,
    ID_RA_CHOICE,
    ID_OP_CHOICE,
        ID_LINE,
        ID_ADD_OPERATION,
        ID_EDIT_OPERATION,
        ID_DELETE_OPERATION,
        ID_ADD_FU_PORT,
        ID_ADD_SR_PORT,
        ID_EDIT_PORT,
        ID_DELETE_PORT,
        ID_HELP,
        ID_TEXT_NAME,
        ID_TEXT_DS,
        ID_TEXT_AS,
        ID_TEXT_INPUT_SOCKET,
        ID_TEXT_OUTPUT_SOCKET,
        ID_TEXT_RA_WIDTH,
    ID_LABEL_RA_CHOICE,
    ID_LABEL_OP_CHOICE
        //ID_LABEL_GLOBAL_GUARD_LATENCY
    };
Constructor & Destructor Documentation
GCUDialog()
GCUDialog::GCUDialog (wxWindow * parent, TTAMachine::ControlUnit * gcu)
The Constructor.
Parameters
parent Parent window of the dialog.
gcu The Global Control Unit to be modified with the dialog.
Definition at line 106 of file GCUDialog.cc.
                     :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    gcu_(gcu),
    name_(_T("")),
    delaySlots_(0) {
    // Create dialog contents and set pointers to the dialog controls.
    createContents(this, true, true);
    addressSpaceChoice_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_ADDRESS_SPACE));
    raPortChoice_ =
        dynamic_cast<wxChoice*>(FindWindow(ID_RA_CHOICE));
    operationList_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    portList_ =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_PORT_LIST));
    // Disable conditional controls initially.
    FindWindow(wxID_OK)->Disable();
    FindWindow(ID_EDIT_OPERATION)->Disable();
    FindWindow(ID_DELETE_OPERATION)->Disable();
    FindWindow(ID_EDIT_PORT)->Disable();
    FindWindow(ID_DELETE_PORT)->Disable();
    // set widget labels
    setLabels();
    // Set validators for dialog controls.
    FindWindow(ID_NAME)->SetValidator(
        wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_DELAY_SLOTS)->SetValidator(
        wxGenericValidator(&delaySlots_));
    //FindWindow(ID_GUARD_LATENCY)->SetValidator(
        //wxGenericValidator(&guardLatency_));
    TransferDataToWindow();
}
~GCUDialog()
GCUDialog::~GCUDialog () virtual
The Destructor.
Definition at line 150 of file GCUDialog.cc.
                      {
}
Member Function Documentation
createContents()
wxSizer * GCUDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 840 of file GCUDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item3 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item4 = new wxStaticText( parent, ID_TEXT_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item4, 0, wxALL, 5 );
    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(140,-1), 0 );
    item3->Add( item5, 0, wxGROW|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT_DS, wxT("Delay slots:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item6, 0, wxALL, 5 );
    wxSpinCtrl *item7 = new wxSpinCtrl( parent, ID_DELAY_SLOTS, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 10000, 1 );
    item3->Add( item7, 0, wxGROW|wxALL, 5 );
    // global guard latency currently fixed at 1.
    //wxStaticText *item8 = new wxStaticText( parent, ID_LABEL_GLOBAL_GUARD_LATENCY, wxT("Guard Latency:"), wxDefaultPosition, wxDefaultSize, 0 );
    //item3->Add( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    //wxSpinCtrl *item9 = new wxSpinCtrl( parent, ID_GUARD_LATENCY, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 1000, 0 );
    //item3->Add( item9, 0, wxGROW|wxALL, 5 );
    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT_AS, wxT("Address Space:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item10, 0, wxALL, 5 );
    wxString *strs11 = (wxString*) NULL;
    wxChoice *item11 = new wxChoice( parent, ID_ADDRESS_SPACE, wxDefaultPosition, wxSize(100,-1), 0, strs11, 0 );
    item3->Add( item11, 0, wxGROW|wxALL, 5 );
    item2->Add( item3, 0, wxALL, 5 );
    wxStaticBox *item13 = new wxStaticBox( parent, -1, wxT("Operations:") );
    wxStaticBoxSizer *item12 = new wxStaticBoxSizer( item13, wxVERTICAL );
    operationsSizer_ = item12;
    wxListCtrl *item14 = new wxListCtrl( parent, ID_OPERATION_LIST, wxDefaultPosition, wxSize(300,200), wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item12->Add( item14, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item16 = new wxButton( parent, ID_ADD_OPERATION, wxT("&Add..."), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item17 = new wxButton( parent, ID_EDIT_OPERATION, wxT("&Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item18 = new wxButton( parent, ID_DELETE_OPERATION, wxT("&Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item12->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item12, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxGROW|wxALL, 5 );
    wxStaticBox *item20 = new wxStaticBox( parent, -1, wxT("Ports:") );
    wxStaticBoxSizer *item19 = new wxStaticBoxSizer( item20, wxVERTICAL );
    portListSizer_ = item19;
    wxBoxSizer *item21 = new wxBoxSizer( wxVERTICAL );
    wxListCtrl *item22 = new wxListCtrl( parent, ID_PORT_LIST, wxDefaultPosition, wxSize(300,180), wxLC_REPORT|wxSUNKEN_BORDER );
    item21->Add( item22, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item24 = new wxButton( parent, ID_EDIT_PORT, wxT("Edit..."), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item25 = new wxButton( parent, ID_DELETE_PORT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    item21->Add( item23, 0, 0, 5 );
    wxBoxSizer *item26 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item27 = new wxButton( parent, ID_ADD_FU_PORT, wxT("Add operation port..."), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item28 = new wxButton( parent, ID_ADD_SR_PORT, wxT("Add special register port..."), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );
    item21->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item29 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item21->Add( item29, 0, wxGROW|wxALL, 5 );
    wxFlexGridSizer *item30 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item31 = new wxStaticText( parent, ID_LABEL_RA_CHOICE, wxT("Return address port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item30->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString strs32[] =
    {
        wxT("NONE")
    };
    wxChoice *item32 = new wxChoice( parent, ID_RA_CHOICE, wxDefaultPosition, wxSize(120,-1), 1, strs32, 0 );
    item30->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );
    item21->Add( item30, 0, wxGROW|wxALL, 5 );
    wxStaticLine *item35 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item21->Add( item35, 0, wxGROW|wxALL, 5 );
    item19->Add( item21, 0, wxGROW|wxALL, 5 );
    item1->Add( item19, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item36 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item36, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item37 = new wxGridSizer( 2, 0, 0 );
    wxButton *item38 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item37->Add( item38, 0, wxALL, 5 );
    wxBoxSizer *item39 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item40 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item39->Add( item40, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item41 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item39->Add( item41, 0, wxALIGN_CENTER|wxALL, 5 );
    item37->Add( item39, 0, wxALL, 5 );
    item0->Add( item37, 0, wxGROW|wxLEFT|wxRIGHT, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_FU_PORT, ID_ADD_OPERATION, ID_ADD_SR_PORT, ID_ADDRESS_SPACE, ID_DELAY_SLOTS, ID_DELETE_OPERATION, ID_DELETE_PORT, ID_EDIT_OPERATION, ID_EDIT_PORT, ID_HELP, ID_LABEL_RA_CHOICE, ID_LINE, ID_NAME, ID_OPERATION_LIST, ID_PORT_LIST, ID_RA_CHOICE, ID_TEXT_AS, ID_TEXT_DS, ID_TEXT_NAME, operationsSizer_, and portListSizer_.
onActivateOperation()
void GCUDialog::onActivateOperation (wxListEvent & event) private
Handles left mouse button double clicks on the operation list.
Definition at line 627 of file GCUDialog.cc.
{
    wxCommandEvent dummy;
    onEditOperation(dummy);
}
References dummy, and onEditOperation().
onActivatePort()
void GCUDialog::onActivatePort (wxListEvent & event) private
Handles left mouse button double clicks on the port list.
Definition at line 798 of file GCUDialog.cc.
{
    wxCommandEvent dummy;
    onEditPort(dummy);
}
References dummy, and onEditPort().
onAddFUPort()
void GCUDialog::onAddFUPort (wxCommandEvent & event) private
Creates and shows an empty Function Unit Port Dialog for adding ports.
Definition at line 638 of file GCUDialog.cc.
{
    // Generate name for the new port.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
        Conversion::toString(i);
    while (gcu_->hasPort(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
            Conversion::toString(i);
        i++;
    }
    FUPort* port = new FUPort(
        newName, ModelConstants::DEFAULT_WIDTH, *gcu_, false, false);
    FUPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_CANCEL) {
        // adding port was cancelled
        delete port;
    }
    updatePortList();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_PORT, ModelConstants::DEFAULT_WIDTH, gcu_, TTAMachine::Unit::hasPort(), Conversion::toString(), and updatePortList().
onAddOperation()
void GCUDialog::onAddOperation (wxCommandEvent & event) private
Creates and shows an empty Operation Dialog for adding operations.
Definition at line 483 of file GCUDialog.cc.
{
    ObjectState* gcu = gcu_->saveState();
    // Generate name for the new operation.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION +
        Conversion::toString(i);
    while (gcu_->hasOperation(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION +
            Conversion::toString(i);
        i++;
    }
    HWOperation* operation = new HWOperation(newName, *gcu_);
    OperationDialog dialog(this, operation);
    if (dialog.ShowModal() == wxID_OK) {
        delete gcu;
    } else {
        gcu_->loadState(gcu);
    }
    updateOperationList();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_OPERATION, gcu_, TTAMachine::FunctionUnit::hasOperation(), TTAMachine::ControlUnit::loadState(), TTAMachine::ControlUnit::saveState(), Conversion::toString(), and updateOperationList().
onAddSRPort()
void GCUDialog::onAddSRPort (wxCommandEvent & event) private
Creates and shows an empty Special Register Port Dialog for adding ports.
Definition at line 665 of file GCUDialog.cc.
{
    // Generate name for the new port.
    int i = 1;
    string newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
        Conversion::toString(i);
    while (gcu_->hasPort(newName)) {
        newName = ProDeConstants::COMP_NEW_NAME_PREFIX_PORT +
            Conversion::toString(i);
        i++;
    }
    SpecialRegisterPort* port = new SpecialRegisterPort(
    newName, ModelConstants::DEFAULT_WIDTH, *gcu_);
    SRPortDialog portDialog(this, port);
    if (portDialog.ShowModal() == wxID_CANCEL) {
        // adding port was cancelled
        delete port;
    }
    updatePortList();
    updateRAPortChoice();
}
References ProDeConstants::COMP_NEW_NAME_PREFIX_PORT, ModelConstants::DEFAULT_WIDTH, gcu_, TTAMachine::Unit::hasPort(), Conversion::toString(), updatePortList(), and updateRAPortChoice().
onDeleteOperation()
void GCUDialog::onDeleteOperation (wxCommandEvent & event) private
Deletes selected operation from the operation list.
Definition at line 511 of file GCUDialog.cc.
{
    string name = WidgetTools::lcStringSelection(operationList_, 0);
    if (name == "") {
        return;
    }
    delete gcu_->operation(name);
    updateOperationList();
}
References gcu_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::operation(), operationList_, and updateOperationList().
onDeletePort()
void GCUDialog::onDeletePort (wxCommandEvent & event) private
Deletes selected port from the port list.
Definition at line 694 of file GCUDialog.cc.
{
    Port* selected = selectedPort();
    if (selected == NULL) {
        return;
    }
    delete selected;
    updatePortList();
    updateRAPortChoice();
}
References selectedPort(), updatePortList(), and updateRAPortChoice().
onEditOperation()
void GCUDialog::onEditOperation (wxCommandEvent & event) private
Handles the 'Edit Operation' button event.
Opens a OperationDialog with the selected operation's attributes set.
Definition at line 527 of file GCUDialog.cc.
{
    HWOperation* selected = selectedOperation();
    if (selected == NULL) {
        // No operation selected.
        return;
    }
    ObjectState* gcu = gcu_->saveState();
    OperationDialog dialog(this, selected);
    if (dialog.ShowModal() == wxID_OK) {
        delete gcu;
    } else {
        gcu_->loadState(gcu);
    }
    updateOperationList();
}
References gcu_, TTAMachine::ControlUnit::loadState(), TTAMachine::ControlUnit::saveState(), selectedOperation(), and updateOperationList().
Referenced by onActivateOperation().
onEditPort()
void GCUDialog::onEditPort (wxCommandEvent & event) private
Handles the 'Edit Port' button event.
Opens a FUPortDialog with the selected port set.
Definition at line 727 of file GCUDialog.cc.
{
    BaseFUPort* selected = selectedPort();
    if (selected == NULL) {
        return;
    }
    if (gcu_->hasSpecialRegisterPort(selected->name())) {
    SpecialRegisterPort* port =
        gcu_->specialRegisterPort(selected->name());
    SRPortDialog portDialog(this, port);
    portDialog.ShowModal();
    } else if (gcu_->hasOperationPort(selected->name())) {
    FUPort* port = gcu_->operationPort(selected->name());
    FUPortDialog portDialog(this, port);
    portDialog.ShowModal();
    }
    updatePortList();
    updateRAPortChoice();
}
References gcu_, TTAMachine::FunctionUnit::hasOperationPort(), TTAMachine::ControlUnit::hasSpecialRegisterPort(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operationPort(), selectedPort(), TTAMachine::ControlUnit::specialRegisterPort(), updatePortList(), and updateRAPortChoice().
Referenced by onActivatePort().
onHelp()
void GCUDialog::onHelp (wxCommandEvent & event) private
onName()
void GCUDialog::onName (wxCommandEvent & event) private
Checks whether the name field is empty, and disables OK button of the dialog if it is.
Definition at line 465 of file GCUDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void GCUDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the ControlUnit.
Definition at line 378 of file GCUDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName =
    WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Check that the name is not reserved for another FU.
    if (trimmedName != gcu_->name()) {
        Machine::FunctionUnitNavigator navigator =
            gcu_->machine()->functionUnitNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            FunctionUnit* fu = navigator.item(i);
            if (trimmedName == fu->name()) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_fu =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_FUNCTION_UNIT);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_MACHINE);
                format gcu = prodeTexts->text(ProDeTextGenerator::COMP_GCU);
                message % trimmedName % a_fu.str() % machine.str() % gcu.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    try {
        gcu_->setName(trimmedName);
        gcu_->setDelaySlots(delaySlots_);
        gcu_->setGlobalGuardLatency(guardLatency_);
    } catch (Exception& e) {
        InformationDialog dialog(
            this, WxConversion::toWxString(e.errorMessage()));
        dialog.ShowModal();
        return;
    }
    // set GCU address space
    string asName =
    WxConversion::toString(addressSpaceChoice_->GetStringSelection());
    if (asName != WxConversion::toString(ProDeConstants::NONE)) {
    Machine::AddressSpaceNavigator asNavigator =
        gcu_->machine()->addressSpaceNavigator();
    assert(asNavigator.hasItem(asName));
    AddressSpace* addressSpace = asNavigator.item(asName);
    gcu_->setAddressSpace(addressSpace);
    } else {
    // no address space set
    gcu_->setAddressSpace(NULL);
    }
    EndModal(wxID_OK);
}
References addressSpaceChoice_, TTAMachine::Machine::addressSpaceNavigator(), assert, ProDeTextGenerator::COMP_A_FUNCTION_UNIT, ProDeTextGenerator::COMP_GCU, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::count(), delaySlots_, Exception::errorMessage(), TTAMachine::Machine::functionUnitNavigator(), gcu_, guardLatency_, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Component::name(), name_, ProDeConstants::NONE, TTAMachine::FunctionUnit::setAddressSpace(), TTAMachine::ControlUnit::setDelaySlots(), TTAMachine::ControlUnit::setGlobalGuardLatency(), TTAMachine::FunctionUnit::setName(), Texts::TextGenerator::text(), WxConversion::toString(), and WxConversion::toWxString().
onOperationRightClick()
void GCUDialog::onOperationRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed on the operation list.
Parameters
event Information about right mouse click event.
Definition at line 603 of file GCUDialog.cc.
{
    operationList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                                wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_OPERATION, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_OPERATION, WxConversion::toWxString(button.str()));
    operationList_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_OPERATION, ID_EDIT_OPERATION, ProDeTextGenerator::instance(), operationList_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onOperationSelection()
void GCUDialog::onOperationSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the operation list.
If a operation is selected, buttons are enabled. If no operation is selected the buttons will be disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 570 of file GCUDialog.cc.
{
    if (operationList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_OPERATION)->Disable();
        FindWindow(ID_EDIT_OPERATION)->Disable();
        return;
    }
    FindWindow(ID_DELETE_OPERATION)->Enable();
    FindWindow(ID_EDIT_OPERATION)->Enable();
}
References ID_DELETE_OPERATION, ID_EDIT_OPERATION, and operationList_.
Referenced by updateOperationList().
onPortRightClick()
void GCUDialog::onPortRightClick (wxListEvent & event) private
Opens a pop-up menu when right mouse button was pressed on the port list.
Parameters
event Information about right mouse click event.
Definition at line 774 of file GCUDialog.cc.
{
    portList_->SetItemState(event.GetIndex(), wxLIST_STATE_SELECTED,
                            wxLIST_STATE_SELECTED);
    wxMenu* contextMenu = new wxMenu();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    format button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT);
    contextMenu->Append(
        ID_EDIT_PORT, WxConversion::toWxString(button.str()));
    button = prodeTexts->text(
        ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE);
    contextMenu->Append(
        ID_DELETE_PORT, WxConversion::toWxString(button.str()));
    portList_->PopupMenu(contextMenu, event.GetPoint());
}
References ID_DELETE_PORT, ID_EDIT_PORT, ProDeTextGenerator::instance(), portList_, Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_LABEL_BUTTON_DELETE, and ProDeTextGenerator::TXT_LABEL_BUTTON_EDIT.
onPortSelection()
void GCUDialog::onPortSelection (wxListEvent & event) private
Disables and enables Edit and Delete buttons under the port list.
If a port is selected, buttons are enabled. If no port is selected the buttons will be disabled.
Parameters
event ListEvent, which may have changed the selection.
Definition at line 757 of file GCUDialog.cc.
{
    if (portList_->GetSelectedItemCount() != 1) {
        FindWindow(ID_DELETE_PORT)->Disable();
        FindWindow(ID_EDIT_PORT)->Disable();
        return;
    }
    FindWindow(ID_DELETE_PORT)->Enable();
    FindWindow(ID_EDIT_PORT)->Enable();
}
References ID_DELETE_PORT, ID_EDIT_PORT, and portList_.
Referenced by updatePortList().
onRAPortChoice()
void GCUDialog::onRAPortChoice (wxCommandEvent & event) private
Sets the return address port when return address port choicer selection changes.
Definition at line 809 of file GCUDialog.cc.
{
    if (raPortChoice_->GetStringSelection() == ProDeConstants::NONE) {
    gcu_->unsetReturnAddressPort();
    return;
    }
    string selection =
        WxConversion::toString(raPortChoice_->GetStringSelection());
    SpecialRegisterPort* port = gcu_->specialRegisterPort(selection);
    assert(port != NULL);
    gcu_->setReturnAddressPort(*port);
    updateRAPortChoice();
}
References assert, gcu_, ProDeConstants::NONE, raPortChoice_, TTAMachine::ControlUnit::setReturnAddressPort(), TTAMachine::ControlUnit::specialRegisterPort(), WxConversion::toString(), TTAMachine::ControlUnit::unsetReturnAddressPort(), and updateRAPortChoice().
selectedOperation()
HWOperation * GCUDialog::selectedOperation () private
Returns pointer to the operation, which is selected on the operation list.
Returns
Pointer to the selected operation.
Definition at line 552 of file GCUDialog.cc.
{
    string name = WidgetTools::lcStringSelection(operationList_, 0);
    if (name == "") {
        return NULL;
    }
    return gcu_->operation(name);
}
References gcu_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::operation(), and operationList_.
Referenced by onEditOperation().
selectedPort()
BaseFUPort * GCUDialog::selectedPort () private
Returns a pointer to the port selected in the port list.
Returns
Pointer to the port selected in the port list.
Definition at line 711 of file GCUDialog.cc.
{
    string name = WidgetTools::lcStringSelection(portList_, 2);
    if (name == "") {
        return NULL;
    }
    BaseFUPort* port = gcu_->port(name);
    return port;
}
References gcu_, WidgetTools::lcStringSelection(), TTAMachine::FunctionUnit::port(), and portList_.
Referenced by onDeletePort(), and onEditPort().
setLabels()
void GCUDialog::setLabels () private
Sets the widget labels to texts provided by the GUITextGenerator.
Definition at line 158 of file GCUDialog.cc.
                     {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_GCU_DIALOG_TITLE);
    string title = fmt.str();
    SetTitle(WxConversion::toWxString(title));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_ADD_OPERATION),
                          GUITextGenerator::TXT_BUTTON_ADD_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_OPERATION),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_OPERATION),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_EDIT_PORT),
                          GUITextGenerator::TXT_BUTTON_EDIT_DIALOG);
    WidgetTools::setLabel(generator, FindWindow(ID_DELETE_PORT),
                          GUITextGenerator::TXT_BUTTON_DELETE);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_ADD_FU_PORT),
                          ProDeTextGenerator::TXT_BUTTON_ADD_FU_PORT);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_ADD_SR_PORT),
                          ProDeTextGenerator::TXT_BUTTON_ADD_SR_PORT);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_TEXT_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_TEXT_AS),
                          ProDeTextGenerator::TXT_LABEL_ADDRESS_SPACE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_TEXT_DS),
                          ProDeTextGenerator::TXT_GCU_DELAY_SLOTS);
    //WidgetTools::setLabel(
        //prodeTexts, FindWindow(ID_LABEL_GLOBAL_GUARD_LATENCY),
        //ProDeTextGenerator::TXT_LABEL_GLOBAL_GUARD_LATENCY);
    // box sizer labels
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_GCU_PORTS_BOX);
    WidgetTools::setWidgetLabel(portListSizer_, fmt.str());
    // Create operation list columns.
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    wxListCtrl* operationList =
        dynamic_cast<wxListCtrl*>(FindWindow(ID_OPERATION_LIST));
    operationList->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                                wxLIST_FORMAT_LEFT, 260);
    // Create port list columns.
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_TRIGGERS);
    portList_->InsertColumn(0, WxConversion::toWxString(fmt.str()),
                            wxLIST_FORMAT_CENTER, 30);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_SRP);
    portList_->InsertColumn(1, WxConversion::toWxString(fmt.str()),
                            wxLIST_FORMAT_CENTER, 40);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_NAME);
    portList_->InsertColumn(2, WxConversion::toWxString(fmt.str()),
                            wxLIST_FORMAT_LEFT, 110);
    fmt = prodeTexts->text(ProDeTextGenerator::TXT_COLUMN_WIDTH);
    portList_->InsertColumn(3, WxConversion::toWxString(fmt.str()),
                            wxLIST_FORMAT_LEFT, 110);
}
References ID_ADD_FU_PORT, ID_ADD_OPERATION, ID_ADD_SR_PORT, ID_DELETE_OPERATION, ID_DELETE_PORT, ID_EDIT_OPERATION, ID_EDIT_PORT, ID_HELP, ID_OPERATION_LIST, ID_TEXT_AS, ID_TEXT_DS, ID_TEXT_NAME, GUITextGenerator::instance(), ProDeTextGenerator::instance(), portList_, portListSizer_, WidgetTools::setLabel(), WidgetTools::setWidgetLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_ADD_DIALOG, ProDeTextGenerator::TXT_BUTTON_ADD_FU_PORT, ProDeTextGenerator::TXT_BUTTON_ADD_SR_PORT, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_DELETE, GUITextGenerator::TXT_BUTTON_EDIT_DIALOG, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_COLUMN_NAME, ProDeTextGenerator::TXT_COLUMN_SRP, ProDeTextGenerator::TXT_COLUMN_TRIGGERS, ProDeTextGenerator::TXT_COLUMN_WIDTH, ProDeTextGenerator::TXT_GCU_DELAY_SLOTS, ProDeTextGenerator::TXT_GCU_DIALOG_TITLE, ProDeTextGenerator::TXT_GCU_PORTS_BOX, ProDeTextGenerator::TXT_LABEL_ADDRESS_SPACE, and ProDeTextGenerator::TXT_LABEL_NAME.
TransferDataToWindow()
bool GCUDialog::TransferDataToWindow () private virtual
Transfers data from the GCU object to the dialog widgets.
Returns
false, if an error occured in the transfer.
Definition at line 247 of file GCUDialog.cc.
{
    name_ = WxConversion::toWxString(gcu_->name());
    delaySlots_ = gcu_->delaySlots();
    guardLatency_ = gcu_->globalGuardLatency();
    updateAddressSpaceChoice();
    updateRAPortChoice();
    updatePortList();
    updateOperationList();
    // wxWidgets GTK1 version seems to bug with spincontrol validators.
    // The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(
        FindWindow(ID_DELAY_SLOTS))->SetValue(delaySlots_);
    return wxWindow::TransferDataToWindow();
}
References TTAMachine::ControlUnit::delaySlots(), delaySlots_, gcu_, TTAMachine::ControlUnit::globalGuardLatency(), guardLatency_, ID_DELAY_SLOTS, TTAMachine::Component::name(), name_, WxConversion::toWxString(), updateAddressSpaceChoice(), updateOperationList(), updatePortList(), and updateRAPortChoice().
updateAddressSpaceChoice()
void GCUDialog::updateAddressSpaceChoice () private
Updates 'Address Space' choice control.
Clears all items from the choicer and adds all address spaces plus an item 'NONE' indicating empty selection.
Definition at line 272 of file GCUDialog.cc.
{
    addressSpaceChoice_->Clear();
    addressSpaceChoice_->Append(ProDeConstants::NONE);
    // Put each address space of the Machine to the control.
    Machine::AddressSpaceNavigator navigator =
        gcu_->machine()->addressSpaceNavigator();
    for (int i = 0;i < navigator.count(); i++) {
        AddressSpace* as = navigator.item(i);
        wxString name = WxConversion::toWxString(as->name());
        addressSpaceChoice_->Append(name);
    }
    if (gcu_->addressSpace() != NULL) {
    wxString asName =
        WxConversion::toWxString(gcu_->addressSpace()->name());
    addressSpaceChoice_->SetStringSelection(asName);
    } else {
    addressSpaceChoice_->SetStringSelection(ProDeConstants::NONE);
    }
}
References TTAMachine::FunctionUnit::addressSpace(), addressSpaceChoice_, TTAMachine::Machine::addressSpaceNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), gcu_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ProDeConstants::NONE, and WxConversion::toWxString().
Referenced by TransferDataToWindow().
updateOperationList()
void GCUDialog::updateOperationList () private
Updates the operation list.
Definition at line 585 of file GCUDialog.cc.
{
    operationList_->DeleteAllItems();
    for (int i=0; i < gcu_->operationCount(); i++) {
        wxString name = WxConversion::toWxString(gcu_->operation(i)->name());
        operationList_->InsertItem(0, name);
    }
    wxListEvent dummy;
    onOperationSelection(dummy);
}
References dummy, gcu_, TTAMachine::HWOperation::name(), onOperationSelection(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), operationList_, and WxConversion::toWxString().
Referenced by onAddOperation(), onDeleteOperation(), onEditOperation(), and TransferDataToWindow().
updatePortList()
void GCUDialog::updatePortList () private
Updates 'Ports' list control.
Clears all items from the choicer and adds all ports.
Definition at line 334 of file GCUDialog.cc.
{
    portList_->DeleteAllItems();
    // Current list index is stored in a separate variable because of
    // possible omitting of the return address port.
    int index = 0;
    for (int i = 0; i < gcu_->portCount(); i++) {
        BaseFUPort* port = gcu_->port(i);
        bool triggers = port->isTriggering();
        string width = Conversion::toString(port->width());
        string name = port->name();
        // set asterisk symbol in the "T" column if port triggers
        if (!triggers) {
            portList_->InsertItem(index, _T(""), 0);
        } else {
            portList_->InsertItem(index, _T("*"), 0);
        }
    // set asterisk symbol in the "SRP" column if the port is
    // a special register port
    if (gcu_->hasSpecialRegisterPort(port->name())) {
        portList_->SetItem(index, 1, _T("*"));
    } else {
        portList_->SetItem(index, 1, _T(""));
    }
        portList_->SetItem(index, 2, WxConversion::toWxString(name));
        portList_->SetItem(index, 3, WxConversion::toWxString(width));
        index++;
    }
    wxListEvent dummy;
    onPortSelection(dummy);
}
References dummy, gcu_, TTAMachine::ControlUnit::hasSpecialRegisterPort(), TTAMachine::BaseFUPort::isTriggering(), TTAMachine::Port::name(), onPortSelection(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), portList_, Conversion::toString(), WxConversion::toWxString(), and TTAMachine::BaseFUPort::width().
Referenced by onAddFUPort(), onAddSRPort(), onDeletePort(), onEditPort(), and TransferDataToWindow().
updateRAPortChoice()
void GCUDialog::updateRAPortChoice () private
Updates the Return address port choicer when the return address port choicer selection is changed.
Definition at line 305 of file GCUDialog.cc.
{
    wxString selection = raPortChoice_->GetStringSelection();
    raPortChoice_->Clear();
    raPortChoice_->Append(ProDeConstants::NONE);
    raPortChoice_->SetSelection(0);
    for (int i = 0; i < gcu_->specialRegisterPortCount(); i++) {
    SpecialRegisterPort* port = gcu_->specialRegisterPort(i);
    string portName = port->name();
    raPortChoice_->Append(WxConversion::toWxString(portName));
    if (gcu_->hasReturnAddressPort() &&
        port == gcu_->returnAddressPort()) {
        raPortChoice_->SetStringSelection(
        WxConversion::toWxString(portName));
    }
    }
}
References gcu_, TTAMachine::ControlUnit::hasReturnAddressPort(), TTAMachine::Port::name(), ProDeConstants::NONE, raPortChoice_, TTAMachine::ControlUnit::returnAddressPort(), TTAMachine::ControlUnit::specialRegisterPort(), TTAMachine::ControlUnit::specialRegisterPortCount(), and WxConversion::toWxString().
Referenced by onAddSRPort(), onDeletePort(), onEditPort(), onRAPortChoice(), and TransferDataToWindow().
updateSocketChoicers()
void GCUDialog::updateSocketChoicers () private
Member Data Documentation
addressSpaceChoice_
wxChoice* GCUDialog::addressSpaceChoice_ private
Address Space choice control.
Definition at line 96 of file GCUDialog.hh.
Referenced by onOK(), and updateAddressSpaceChoice().
delaySlots_
int GCUDialog::delaySlots_ private
Number of delay slots of the global control unit.
Definition at line 91 of file GCUDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
gcu_
TTAMachine::ControlUnit* GCUDialog::gcu_ private
The Global Control Unit to be modified with the dialog.
Definition at line 87 of file GCUDialog.hh.
Referenced by onAddFUPort(), onAddOperation(), onAddSRPort(), onDeleteOperation(), onEditOperation(), onEditPort(), onOK(), onRAPortChoice(), selectedOperation(), selectedPort(), TransferDataToWindow(), updateAddressSpaceChoice(), updateOperationList(), updatePortList(), and updateRAPortChoice().
guardLatency_
int GCUDialog::guardLatency_ private
Guard latency of the gcu.
Definition at line 93 of file GCUDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
name_
wxString GCUDialog::name_ private
Name of the global control unit.
Definition at line 89 of file GCUDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
operationList_
wxListCtrl* GCUDialog::operationList_ private
Operation list widget.
Definition at line 101 of file GCUDialog.hh.
Referenced by onDeleteOperation(), onOperationRightClick(), onOperationSelection(), selectedOperation(), and updateOperationList().
operationsSizer_
wxStaticBoxSizer* GCUDialog::operationsSizer_ private
Box sizer for the operations list controls.
Definition at line 106 of file GCUDialog.hh.
Referenced by createContents().
portList_
wxListCtrl* GCUDialog::portList_ private
Port list widget.
Definition at line 103 of file GCUDialog.hh.
Referenced by onPortRightClick(), onPortSelection(), selectedPort(), setLabels(), and updatePortList().
portListSizer_
wxStaticBoxSizer* GCUDialog::portListSizer_ private
Box sizer for the port list controls.
Definition at line 108 of file GCUDialog.hh.
Referenced by createContents(), and setLabels().
raPortChoice_
wxChoice* GCUDialog::raPortChoice_ private
Return address port choice control.
Definition at line 98 of file GCUDialog.hh.
Referenced by onRAPortChoice(), and updateRAPortChoice().
The documentation for this class was generated from the following files:
GCUDialog.hh
GCUDialog.cc