OpenASIP: ResultDialog Class Reference
ResultDialog Class Reference
#include <ResultDialog.hh>
Public Member Functions
ResultDialog (wxWindow *parent, std::vector< std::string > output, const std::string &title, const std::string &module="")
virtual ~ResultDialog ()
Private Types
enum { ID_RESULT , ID_BUTTON_OPEN }
Private Member Functions
ResultDialog (const ResultDialog &)
Copying not allowed.
ResultDialog operator= (const ResultDialog &)
Assignment not allowed.
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void setTexts ()
virtual bool TransferDataToWindow ()
void onOpen (wxCommandEvent &event)
Private Attributes
wxTextCtrl * result_
Result window pointer.
std::vector< std::string > output_
Output of compilation.
std::string module_
Module which was compiled or empty string, if all modules were compiled.
Detailed Description
Dialog that shows operation build results.
Definition at line 44 of file ResultDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_RESULT
ID_BUTTON_OPEN
Definition at line 67 of file ResultDialog.hh.
         {
        ID_RESULT,
        ID_BUTTON_OPEN
    };
Constructor & Destructor Documentation
ResultDialog() [1/2]
ResultDialog::ResultDialog (wxWindow * parent, std::vector< std::string > output, const std::string & title, const std::string & module = "")
Constructor.
Parameters
parent Parent window.
Definition at line 60 of file ResultDialog.cc.
                             :
    wxDialog(parent, -1, _T(""),
             DialogPosition::getPosition(DialogPosition::DIALOG_RESULT),
             wxDefaultSize, wxRESIZE_BORDER),
    output_(output), module_(module) {
    createContents(this, true, true);
    result_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_RESULT));
    result_->SetEditable(false);
    FindWindow(wxID_OK)->SetFocus();
    SetTitle(WxConversion::toWxString(title));
    if (module_ == "") {
        FindWindow(ID_BUTTON_OPEN)->Disable();
    }
    setTexts();
}
References WxConversion::toWxString().
~ResultDialog()
ResultDialog::~ResultDialog () virtual
Destructor.
Definition at line 85 of file ResultDialog.cc.
{
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_RESULT, point);
}
References DialogPosition::DIALOG_RESULT, and DialogPosition::setPosition().
ResultDialog() [2/2]
ResultDialog::ResultDialog (const ResultDialog &) private
Copying not allowed.
Member Function Documentation
createContents()
wxSizer * ResultDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the contents of the dialog.
NOTE! This function was generated by wxDesigner.
Parameters
parent Parent window.
call_fit If true fits the contents inside the dialog.
set_sizer If true, sets the main sizer as contents of dialog.
Returns
The created sizer.
Definition at line 161 of file ResultDialog.cc.
                    {
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxTextCtrl *item1 = new wxTextCtrl( parent, ID_RESULT, wxT(""), wxDefaultPosition, wxSize(400,100), wxTE_MULTILINE );
    item0->Add( item1, 1, wxGROW|wxALL, 5 );
    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item3 = new wxButton( parent, ID_BUTTON_OPEN, wxT("Open"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BUTTON_OPEN, and ID_RESULT.
onOpen()
void ResultDialog::onOpen (wxCommandEvent & event) private
Handles the event when Open button is pushed.
Definition at line 126 of file ResultDialog.cc.
{
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdOptions* options = wxGetApp().options();
    string editor = options->editor();
    if (editor == "") {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_EDITOR);
        ErrorDialog error(this, WxConversion::toWxString(fmt.str()));
        error.ShowModal();
    } else {
        if (FileSystem::fileExists(editor)) {
            string cmd = editor + " " + module_;
            CommandThread* thread = new CommandThread(cmd);
            thread->Create();
            thread->Run();
        } else {
            format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_OPEN);
            fmt % editor;
            ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
            dialog.ShowModal();
        }
    }
}
References FileSystem::fileExists(), OSEdTextGenerator::instance(), module_, options, Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_ERROR_NO_EDITOR, and OSEdTextGenerator::TXT_ERROR_OPEN.
operator=()
ResultDialog ResultDialog::operator= (const ResultDialog &) private
Assignment not allowed.
setTexts()
void ResultDialog::setTexts () private
Set texts to widgets.
Definition at line 96 of file ResultDialog.cc.
                       {
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();
    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_OPEN),
                          OSEdTextGenerator::TXT_BUTTON_OPEN);
}
References ID_BUTTON_OPEN, GUITextGenerator::instance(), OSEdTextGenerator::instance(), WidgetTools::setLabel(), GUITextGenerator::TXT_BUTTON_OK, and OSEdTextGenerator::TXT_BUTTON_OPEN.
TransferDataToWindow()
bool ResultDialog::TransferDataToWindow () private virtual
Transfer data to window.
Returns
True if transfer is successful.
Definition at line 115 of file ResultDialog.cc.
{
    for (size_t i = 0; i < output_.size(); i++) {
        result_->AppendText(WxConversion::toWxString(output_[i]));
    }
    return wxWindow::TransferDataToWindow();
}
References output_, result_, and WxConversion::toWxString().
Member Data Documentation
module_
std::string ResultDialog::module_ private
Module which was compiled or empty string, if all modules were compiled.
Definition at line 78 of file ResultDialog.hh.
Referenced by onOpen().
output_
std::vector<std::string> ResultDialog::output_ private
Output of compilation.
Definition at line 75 of file ResultDialog.hh.
Referenced by TransferDataToWindow().
result_
wxTextCtrl* ResultDialog::result_ private
Result window pointer.
Definition at line 73 of file ResultDialog.hh.
Referenced by TransferDataToWindow().
The documentation for this class was generated from the following files:
ResultDialog.hh
ResultDialog.cc