OpenASIP: IPXactInterface Class Reference
IPXactInterface Class Reference abstract
#include <IPXactInterface.hh>
Public Member Functions
IPXactInterface ()
virtual ~IPXactInterface ()
virtual bool mapPortsToInterface (const ProGe::NetlistBlock &toplevel)=0
virtual TCEString instanceName () const
virtual IPXact::Vlnv busType () const
virtual IPXact::Vlnv busAbstractionType () const
virtual IPXactModel::BusMode busMode () const
virtual const PlatInt::SignalMappingList & interfaceMapping () const
virtual void addSignalMapping (const TCEString &actualSignal, const TCEString &busSignal)
void setInstanceName (const TCEString &name)
Protected Member Functions
void setBusMode (IPXactModel::BusMode mode)
void setBusType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
void setBusAbsType (const TCEString &vendor, const TCEString &library, const TCEString &name, const TCEString &version)
Private Attributes
TCEString instanceName_
Instance Name.
IPXactModel::BusMode busMode_
Bus mode.
IPXact::Vlnv busType_
Vendor,Library,Name,Version of the bus type.
IPXact::Vlnv busAbstractionType_
Vendor,Library,Name,Version of the bus abstraction type.
PlatInt::SignalMappingList interfaceMap_
Mapping of actual port names and interface port names.
Detailed Description
Definition at line 41 of file IPXactInterface.hh.
Constructor & Destructor Documentation
IPXactInterface()
IPXactInterface::IPXactInterface ()
Definition at line 36 of file IPXactInterface.cc.
                                :
    instanceName_(""), busMode_(IPXactModel::INVALID), busType_("","","",""),
    busAbstractionType_("","","",""), interfaceMap_() {
}
~IPXactInterface()
IPXactInterface::~IPXactInterface () virtual
Definition at line 41 of file IPXactInterface.cc.
{
    for (unsigned int i = 0; i < interfaceMap_.size(); i++) {
        delete interfaceMap_.at(i);
    }
}
References interfaceMap_.
Member Function Documentation
addSignalMapping()
void IPXactInterface::addSignalMapping (const TCEString & actualSignal, const TCEString & busSignal) virtual
Definition at line 79 of file IPXactInterface.cc.
{
    SignalMapping* signalMap = new SignalMapping(
        pair<TCEString,TCEString>(actualSignal, busSignal));
    interfaceMap_.push_back(signalMap);
}
References interfaceMap_.
Referenced by IPXactModel::extractPortMap(), IPXactClkInterface::mapPortsToInterface(), IPXactHibiInterface::mapPortsToInterface(), and IPXactResetInterface::mapPortsToInterface().
busAbstractionType()
IPXact::Vlnv IPXactInterface::busAbstractionType () const virtual
Definition at line 60 of file IPXactInterface.cc.
{
    return busAbstractionType_;
}
References busAbstractionType_.
Referenced by IPXactModel::addBusInterfaceObject().
busMode()
IPXactModel::BusMode IPXactInterface::busMode () const virtual
Definition at line 66 of file IPXactInterface.cc.
{
    assert(busMode_ != IPXactModel::INVALID && "Bus mode not set!");
    return busMode_;
}
References assert, busMode_, and IPXactModel::INVALID.
Referenced by IPXactModel::addBusInterfaceObject().
busType()
IPXact::Vlnv IPXactInterface::busType () const virtual
Definition at line 54 of file IPXactInterface.cc.
{
    return busType_;
}
References busType_.
Referenced by IPXactModel::addBusInterfaceObject().
instanceName()
TCEString IPXactInterface::instanceName () const virtual
Definition at line 49 of file IPXactInterface.cc.
{
    return instanceName_;
}
References instanceName_.
Referenced by IPXactModel::addBusInterfaceObject().
interfaceMapping()
const PlatInt::SignalMappingList & IPXactInterface::interfaceMapping () const virtual
Definition at line 73 of file IPXactInterface.cc.
{
    return interfaceMap_;
}
References interfaceMap_.
Referenced by IPXactModel::addBusInterfaceObject(), and IPXactHibiInterface::mapPortsToInterface().
mapPortsToInterface()
virtual bool IPXactInterface::mapPortsToInterface (const ProGe::NetlistBlock & toplevel) pure virtual
Implemented in IPXactClkInterface, IPXactHibiInterface, and IPXactResetInterface.
setBusAbsType()
void IPXactInterface::setBusAbsType (const TCEString & vendor, const TCEString & library, const TCEString & name, const TCEString & version) protected
Definition at line 114 of file IPXactInterface.cc.
{
    busAbstractionType_.vendor = vendor;
    busAbstractionType_.library = library;
    busAbstractionType_.name = name;
    busAbstractionType_.version = version;
}
References busAbstractionType_, IPXact::Vlnv::library, IPXact::Vlnv::name, IPXact::Vlnv::vendor, and IPXact::Vlnv::version.
Referenced by IPXactClkInterface::IPXactClkInterface(), IPXactHibiInterface::IPXactHibiInterface(), and IPXactResetInterface::IPXactResetInterface().
setBusMode()
void IPXactInterface::setBusMode (IPXactModel::BusMode mode) protected
Definition at line 95 of file IPXactInterface.cc.
{
    busMode_ = mode;
}
References busMode_.
Referenced by IPXactClkInterface::IPXactClkInterface(), IPXactHibiInterface::IPXactHibiInterface(), and IPXactResetInterface::IPXactResetInterface().
setBusType()
void IPXactInterface::setBusType (const TCEString & vendor, const TCEString & library, const TCEString & name, const TCEString & version) protected
Definition at line 101 of file IPXactInterface.cc.
{
    busType_.vendor = vendor;
    busType_.library = library;
    busType_.name = name;
    busType_.version = version;
}
References busType_, IPXact::Vlnv::library, IPXact::Vlnv::name, IPXact::Vlnv::vendor, and IPXact::Vlnv::version.
Referenced by IPXactClkInterface::IPXactClkInterface(), IPXactHibiInterface::IPXactHibiInterface(), and IPXactResetInterface::IPXactResetInterface().
setInstanceName()
void IPXactInterface::setInstanceName (const TCEString & name)
Definition at line 89 of file IPXactInterface.cc.
{
    instanceName_ = name;
}
References instanceName_.
Referenced by IPXactHibiInterface::createInstanceName(), IPXactModel::interfaceByType(), IPXactClkInterface::IPXactClkInterface(), IPXactHibiInterface::IPXactHibiInterface(), and IPXactResetInterface::IPXactResetInterface().
Member Data Documentation
busAbstractionType_
IPXact::Vlnv IPXactInterface::busAbstractionType_ private
Vendor,Library,Name,Version of the bus abstraction type.
Definition at line 91 of file IPXactInterface.hh.
Referenced by busAbstractionType(), and setBusAbsType().
busMode_
IPXactModel::BusMode IPXactInterface::busMode_ private
Bus mode.
Definition at line 87 of file IPXactInterface.hh.
Referenced by busMode(), and setBusMode().
busType_
IPXact::Vlnv IPXactInterface::busType_ private
Vendor,Library,Name,Version of the bus type.
Definition at line 89 of file IPXactInterface.hh.
Referenced by busType(), and setBusType().
instanceName_
TCEString IPXactInterface::instanceName_ private
Instance Name.
Definition at line 85 of file IPXactInterface.hh.
Referenced by instanceName(), and setInstanceName().
interfaceMap_
PlatInt::SignalMappingList IPXactInterface::interfaceMap_ private
Mapping of actual port names and interface port names.
Definition at line 93 of file IPXactInterface.hh.
Referenced by addSignalMapping(), interfaceMapping(), and ~IPXactInterface().
The documentation for this class was generated from the following files:
IPXactInterface.hh
IPXactInterface.cc