OpenASIP: OSEdUserManualCmd Class Reference
OSEdUserManualCmd Class Reference
#include <OSEdUserManualCmd.hh>
Public Member Functions
OSEdUserManualCmd ()
virtual ~OSEdUserManualCmd ()
virtual int id () const
virtual GUICommand * create () const
virtual bool Do ()
virtual bool isEnabled ()
virtual std::string icon () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Member Functions
OSEdUserManualCmd (const OSEdUserManualCmd &)
Copying not allowed.
OSEdUserManualCmd & operator= (const OSEdUserManualCmd &)
Assignment not allowed.
std::string userManual () const
Detailed Description
Command for opening user manual browser.
Definition at line 43 of file OSEdUserManualCmd.hh.
Constructor & Destructor Documentation
OSEdUserManualCmd() [1/2]
OSEdUserManualCmd::OSEdUserManualCmd ()
Constructor.
Definition at line 49 of file OSEdUserManualCmd.cc.
                                     :
    GUICommand(OSEdConstants::CMD_NAME_USER_MANUAL, NULL) {
}
Referenced by create().
~OSEdUserManualCmd()
OSEdUserManualCmd::~OSEdUserManualCmd () virtual
Destructor.
Definition at line 56 of file OSEdUserManualCmd.cc.
{
}
OSEdUserManualCmd() [2/2]
OSEdUserManualCmd::OSEdUserManualCmd (const OSEdUserManualCmd &) private
Copying not allowed.
Member Function Documentation
create()
GUICommand * OSEdUserManualCmd::create () const virtual
Creates new command.
Returns
New command.
Implements GUICommand.
Definition at line 75 of file OSEdUserManualCmd.cc.
{
    return new OSEdUserManualCmd();
}
References OSEdUserManualCmd().
Do()
bool OSEdUserManualCmd::Do () virtual
Executes the command.
Returns
True if execution is successful.
Implements GUICommand.
Definition at line 85 of file OSEdUserManualCmd.cc.
                      {
    string manualFile = userManual();
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    format fmt = texts.text(OSEdTextGenerator::TXT_USER_MANUAL_TITLE);
    HelpBrowser* browser = new HelpBrowser(
        WxConversion::toWxString(fmt.str()),
        WxConversion::toWxString(manualFile), wxDefaultPosition,
        wxSize(800, 600));
    browser->Show(true);
    return true;
}
References OSEdTextGenerator::instance(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_USER_MANUAL_TITLE, and userManual().
icon()
string OSEdUserManualCmd::icon () const virtual
Returns the icon path.
Returns
Empty string (icons not used).
Implements GUICommand.
Definition at line 120 of file OSEdUserManualCmd.cc.
{
    return "";
}
id()
int OSEdUserManualCmd::id () const virtual
Returns the id of the command.
Returns
The id of the command.
Implements GUICommand.
Definition at line 65 of file OSEdUserManualCmd.cc.
{
    return OSEdConstants::CMD_USER_MANUAL;
}
References OSEdConstants::CMD_USER_MANUAL.
isEnabled()
bool OSEdUserManualCmd::isEnabled () virtual
Returns true if command is enabled.
Command is enabled when user manual exists.
Returns
True if command is enabled.
Implements GUICommand.
Definition at line 109 of file OSEdUserManualCmd.cc.
{
    string manualFile = userManual();
    return FileSystem::fileExists(manualFile);
}
References FileSystem::fileExists(), and userManual().
operator=()
OSEdUserManualCmd & OSEdUserManualCmd::operator= (const OSEdUserManualCmd &) private
Assignment not allowed.
userManual()
std::string OSEdUserManualCmd::userManual () const private
Returns the user manual location.
Returns
User manual location.
Definition at line 130 of file OSEdUserManualCmd.cc.
{
    return Environment::manDirPath("OSALGUI") +
        FileSystem::DIRECTORY_SEPARATOR + "OSALGUI" +
        FileSystem::DIRECTORY_SEPARATOR + OSEdConstants::USER_MANUAL_NAME;
}
References FileSystem::DIRECTORY_SEPARATOR, Environment::manDirPath(), and OSEdConstants::USER_MANUAL_NAME.
Referenced by Do(), and isEnabled().
The documentation for this class was generated from the following files:
OSEdUserManualCmd.hh
OSEdUserManualCmd.cc