OpenASIP: ProximRuntimeErrorHandler Class Reference
ProximRuntimeErrorHandler Class Reference
#include <ProximRuntimeErrorHandler.hh>
Public Member Functions
ProximRuntimeErrorHandler (SimulatorFrontend &frontend, wxEvtHandler &gui)
~ProximRuntimeErrorHandler ()
virtual void handleEvent ()
Public Member Functions inherited from Listener
Listener ()
virtual ~Listener ()
virtual void handleEvent (int event)
Private Attributes
SimulatorFrontend & frontend_
Simulator frontend to stop when a fatal error occurs.
wxEvtHandler & gui_
GUI to send the simulator events to.
Detailed Description
A class which handles simulation runtime errors in Proxim.
The errors are reported to the GUI using SimulatorEvents, and the simultion is stopped id necessary.
Definition at line 47 of file ProximRuntimeErrorHandler.hh.
Constructor & Destructor Documentation
ProximRuntimeErrorHandler()
ProximRuntimeErrorHandler::ProximRuntimeErrorHandler (SimulatorFrontend & frontend, wxEvtHandler & gui)
The Constructor.
The created error handler is registered automatically as simulator event handler listener.
Parameters
frontend Simulator frontend to stop when a fatal error occurs.
gui GUI to send the error events to.
Definition at line 50 of file ProximRuntimeErrorHandler.cc.
                      :
    Listener(),
    frontend_(frontend),
    gui_(gui) {
    frontend.eventHandler().registerListener(
        SimulationEventHandler::SE_RUNTIME_ERROR, this);
}
References SimulatorFrontend::eventHandler(), Informer::registerListener(), and SimulationEventHandler::SE_RUNTIME_ERROR.
~ProximRuntimeErrorHandler()
ProximRuntimeErrorHandler::~ProximRuntimeErrorHandler ()
The Destructor.
Definition at line 64 of file ProximRuntimeErrorHandler.cc.
{
    frontend_.eventHandler().unregisterListener(
    SimulationEventHandler::SE_RUNTIME_ERROR, this);
}
References SimulatorFrontend::eventHandler(), frontend_, SimulationEventHandler::SE_RUNTIME_ERROR, and Informer::unregisterListener().
Member Function Documentation
handleEvent()
void ProximRuntimeErrorHandler::handleEvent () virtual
Handles simulator runtime errors.
This event handler sends a SimulatorEvent to the GUI when a runtime error occurs. An error message explaining the error is sent as the event string payload. If a fatal error occured, the simulator is stopped.
Reimplemented from Listener.
Definition at line 78 of file ProximRuntimeErrorHandler.cc.
{
    size_t minorErrors = frontend_.programErrorReportCount(
        SimulatorFrontend::RES_MINOR);
    size_t fatalErrors = frontend_.programErrorReportCount(
        SimulatorFrontend::RES_FATAL);
    // Send runtime warning event if minor errors occured.
    if (minorErrors > 0) {
        string message;
        for (size_t i = 0; i < minorErrors; ++i) {
            message += "warning: runtime error: \n";
            message += frontend_.programErrorReport(
                SimulatorFrontend::RES_MINOR, i) + "\n\n";
        }
        SimulatorEvent simEvent(
            SimulatorEvent::EVT_SIMULATOR_RUNTIME_WARNING, message);
        wxPostEvent(&gui_, simEvent);
    }
    // Send runtime error event if fatal errors occured.
    if (fatalErrors > 0) {
        string message;
        for (size_t i = 0; i < fatalErrors; ++i) {
            message += "error: runtime error: \n";
            message +=
                frontend_.programErrorReport(
                    SimulatorFrontend::RES_FATAL, i) + "\n";
        }
        SimulatorEvent simEvent(
            SimulatorEvent::EVT_SIMULATOR_RUNTIME_ERROR, message);
        wxPostEvent(&gui_, simEvent);
        // Stop simulation.
        frontend_.prepareToStop(SRE_RUNTIME_ERROR);
    }
    frontend_.clearProgramErrorReports();
}
References SimulatorFrontend::clearProgramErrorReports(), SimulatorEvent::EVT_SIMULATOR_RUNTIME_ERROR, SimulatorEvent::EVT_SIMULATOR_RUNTIME_WARNING, frontend_, gui_, SimulatorFrontend::prepareToStop(), SimulatorFrontend::programErrorReport(), SimulatorFrontend::programErrorReportCount(), SimulatorFrontend::RES_FATAL, SimulatorFrontend::RES_MINOR, and SRE_RUNTIME_ERROR.
Member Data Documentation
frontend_
SimulatorFrontend& ProximRuntimeErrorHandler::frontend_ private
Simulator frontend to stop when a fatal error occurs.
Definition at line 58 of file ProximRuntimeErrorHandler.hh.
Referenced by handleEvent(), and ~ProximRuntimeErrorHandler().
gui_
wxEvtHandler& ProximRuntimeErrorHandler::gui_ private
GUI to send the simulator events to.
Definition at line 60 of file ProximRuntimeErrorHandler.hh.
Referenced by handleEvent().
The documentation for this class was generated from the following files:
ProximRuntimeErrorHandler.hh
ProximRuntimeErrorHandler.cc