OpenASIP: ProDePortEditPolicy Class Reference
ProDePortEditPolicy Class Reference
#include <ProDePortEditPolicy.hh>
Public Member Functions
ProDePortEditPolicy ()
virtual ~ProDePortEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ComponentCommand * createConnectCmd (Request *request)
ProDePortEditPolicy & operator= (ProDePortEditPolicy &old)
Assignment not allowed.
ProDePortEditPolicy (ProDePortEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a port EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports the Request.
Definition at line 49 of file ProDePortEditPolicy.hh.
Constructor & Destructor Documentation
ProDePortEditPolicy() [1/2]
ProDePortEditPolicy::ProDePortEditPolicy ()
The Constructor.
Definition at line 58 of file ProDePortEditPolicy.cc.
                                        : EditPolicy() {
}
~ProDePortEditPolicy()
ProDePortEditPolicy::~ProDePortEditPolicy () virtual
The Destructor.
Definition at line 64 of file ProDePortEditPolicy.cc.
{
}
ProDePortEditPolicy() [2/2]
ProDePortEditPolicy::ProDePortEditPolicy (ProDePortEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDePortEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 102 of file ProDePortEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::CONNECT_REQUEST) {
        ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
        assert(cr != NULL);
        EditPart* part = cr->part();
        if (part == NULL) {
            // No selection.
            // Port can be selected for connecting, return true.
            return true;
        }
        Socket* socket = dynamic_cast<Socket*>(part->model());
        if (socket == NULL) {
            // Port can be connected only to sockets, return false.
            return false;
        }
        MachineTester tester(*(socket->machine()));
        Port* port = dynamic_cast<Port*>(host_->model());
        if (port->isConnectedTo(*socket) ||
            tester.canConnect(*socket, *port)) {
            return true;
        }
        return false;
    } else if (type == Request::STATUS_REQUEST) {
        return true;
    } else if (type == Request::DELETE_REQUEST) {
        return true;
    } else {
    return false;
    }
}
References assert, MachineTester::canConnect(), Request::CONNECT_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, TTAMachine::Port::isConnectedTo(), TTAMachine::Component::machine(), EditPart::model(), ConnectRequest::part(), Request::STATUS_REQUEST, and Request::type().
Referenced by createConnectCmd().
createConnectCmd()
ComponentCommand * ProDePortEditPolicy::createConnectCmd (Request * request) private
Creates a command which connects the selected component to the requested component.
Parameters
request ConnectionRequest with the target component for the connection.
Returns
Command for connecting the selected and requested components.
Definition at line 145 of file ProDePortEditPolicy.cc.
{
    ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
    assert(cr != NULL);
    EditPart* part = cr->part();
    if (canHandle(request)) {
        Port* port = dynamic_cast<Port*>(host_->model());
        Socket* socket = dynamic_cast<Socket*>(part->model());
        if (port == NULL) {
            return NULL;
        }
        ComponentCommand* cmd = NULL;
        cmd = new SocketPortConnCmd(socket, port);
        return cmd;
    } else {
        return NULL;
    }
}
References assert, canHandle(), EditPolicy::host_, EditPart::model(), and ConnectRequest::part().
Referenced by getCommand().
getCommand()
ComponentCommand * ProDePortEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Note
ConnectCommand is not yet implemented, thus returns always NULL.
Implements EditPolicy.
Definition at line 75 of file ProDePortEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::CONNECT_REQUEST) {
    return createConnectCmd(request);
    } else if (type == Request::STATUS_REQUEST) {
        Port* port = dynamic_cast<Port*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_PORT);
        fmt % port->name();
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeletePortCmd* deleteCmd = new DeletePortCmd(host_);
        return deleteCmd;
    } else {
    return NULL;
    }
}
References Request::CONNECT_REQUEST, createConnectCmd(), Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), TTAMachine::Port::name(), ProDeTextGenerator::STATUS_PORT, Request::STATUS_REQUEST, Texts::TextGenerator::text(), and Request::type().
operator=()
ProDePortEditPolicy & ProDePortEditPolicy::operator= (ProDePortEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDePortEditPolicy.hh
ProDePortEditPolicy.cc