OpenASIP: FullyConnectedCheck Class Reference
FullyConnectedCheck Class Reference
#include <FullyConnectedCheck.hh>
Public Member Functions
FullyConnectedCheck ()
virtual ~FullyConnectedCheck ()
virtual bool check (const TTAMachine::Machine &mach) const
virtual bool check (const TTAMachine::Machine &mach, MachineCheckResults &results) const
virtual bool canFix (const TTAMachine::Machine &mach) const
virtual std::string fix (TTAMachine::Machine &mach) const
void connectFUPort (TTAMachine::FUPort &port) const
void connectSpecialRegisterPort (TTAMachine::SpecialRegisterPort &port) const
void connectControlUnit (TTAMachine::ControlUnit &gcu) const
Public Member Functions inherited from MachineCheck
virtual std::string shortDescription () const
virtual std::string description () const
virtual ~MachineCheck ()
Protected Member Functions
FullyConnectedCheck (const std::string &shortDesc)
Protected Member Functions inherited from MachineCheck
MachineCheck (const std::string &shortDesc_)
Private Member Functions
void connectIUPort (TTAMachine::RFPort &port) const
void connectRFPort (TTAMachine::RFPort &port, TTAMachine::Socket::Direction direction) const
TTAMachine::Socket * createSocket (const TTAMachine::Unit &unit, TTAMachine::Socket::Direction direction) const
void attachSocketToAllBusses (TTAMachine::Socket &socket) const
bool socketAttachedToAllBusses (const TTAMachine::Socket &socket) const
Detailed Description
MachineCheck to check is the machine fully connected.
Definition at line 51 of file FullyConnectedCheck.hh.
Constructor & Destructor Documentation
FullyConnectedCheck() [1/2]
FullyConnectedCheck::FullyConnectedCheck ()
Constructor for using this generic class directly.
Definition at line 52 of file FullyConnectedCheck.cc.
                                         :
    MachineCheck("Fully connected machine check.") {
}
~FullyConnectedCheck()
FullyConnectedCheck::~FullyConnectedCheck () virtual
The destructor.
Definition at line 68 of file FullyConnectedCheck.cc.
{
}
FullyConnectedCheck() [2/2]
FullyConnectedCheck::FullyConnectedCheck (const std::string & shortDesc) protected
Constructor for deriving.
Parameters
shortDesc The short description of the check.
Definition at line 61 of file FullyConnectedCheck.cc.
                                                                  :
    MachineCheck(shortDesc) {
}
Member Function Documentation
attachSocketToAllBusses()
void FullyConnectedCheck::attachSocketToAllBusses (TTAMachine::Socket & socket) const private
Attaches given socket to all possible busses.
Parameters
socket Socket to connect.
Definition at line 552 of file FullyConnectedCheck.cc.
{
    TTAMachine::Machine& machine = *socket.machine();
    MachineTester tester(machine);
    const TTAMachine::Machine::BusNavigator busNav = machine.busNavigator();
    for (int b = 0; b < busNav.count(); b++) {
        // for each bus in the machine
        TTAMachine::Bus& bus = *busNav.item(b);
        for (int seg = 0; seg < bus.segmentCount(); seg++) {
            TTAMachine::Segment& segment = *bus.segment(seg);
            // for each segment in the bus
            if ((!socket.isConnectedTo(segment)) &&
                tester.canConnect(socket, segment)) {
                socket.attachBus(segment);
            }
        }
    }
}
References TTAMachine::Socket::attachBus(), TTAMachine::Machine::busNavigator(), MachineTester::canConnect(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Socket::isConnectedTo(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, TTAMachine::Bus::segment(), and TTAMachine::Bus::segmentCount().
Referenced by createSocket(), and fix().
canFix()
bool FullyConnectedCheck::canFix (const TTAMachine::Machine & mach) const virtual
Returns true if the machine can be fixed to pass the check.
Parameters
mach The machine to be analyzed.
Returns
True if the machine can be fixed to pass the check.
Reimplemented from MachineCheck.
Definition at line 78 of file FullyConnectedCheck.cc.
{
    const TTAMachine::Machine::BridgeNavigator brNav =
        mach.bridgeNavigator();
    const TTAMachine::Machine::BusNavigator busNav =
        mach.busNavigator();
    if (busNav.count() == 0 || brNav.count() > 0) {
        return false;
    }
    return true;
}
References TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::busNavigator(), and TTAMachine::Machine::Navigator< ComponentType >::count().
Referenced by fix(), and FullyConnectBussesCmd::isEnabled().
check() [1/2]
bool FullyConnectedCheck::check (const TTAMachine::Machine & mach) const virtual
Checks is the machine fully connected.
Parameters
mach Machine to be checked.
Returns
True if the machine is fully connected.
Definition at line 99 of file FullyConnectedCheck.cc.
{
    const Machine::SocketNavigator
        socketNav = mach.socketNavigator();
    for (int so = 0; so < socketNav.count(); so++) {
        // for each socket in the machine
        if (!socketAttachedToAllBusses(*socketNav.item(so))) {
            return false;
        }
    }
    // check unconnected FU ports
    const Machine::FunctionUnitNavigator fuNav = mach.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit& fu = *fuNav.item(i);
        for (int p = 0; p < fu.operationPortCount(); p++) {
            FUPort& port = *fu.operationPort(p);
            if (port.socketCount() == 0) {
                return false;
            }
        }
    }
    // check unconnected IU ports
    const Machine::ImmediateUnitNavigator iuNav =
        mach.immediateUnitNavigator();
    for (int i = 0; i < iuNav.count(); i++) {
        ImmediateUnit& iu = *iuNav.item(i);
        for (int p = 0; p < iu.portCount(); p++) {
            RFPort& port = *iu.port(p);
            if (port.socketCount() == 0) {
                return false;
            }
        }
    }
    // check unconnected RF ports
    const Machine::RegisterFileNavigator rfNav = mach.registerFileNavigator();
    for (int i = 0; i < rfNav.count(); i++) {
        RegisterFile& rf = *rfNav.item(i);
        for (int p = 0; p < rf.portCount(); p++) {
            RFPort& port = *rf.port(p);
            if (port.socketCount() == 0) {
                return false;
            }
        }
    }
    ControlUnit* gcu = mach.controlUnit();
    if (gcu != NULL) {
        for (int p = 0; p < gcu->operationPortCount(); p++) {
            FUPort& port = *gcu->operationPort(p);
            if (port.socketCount() == 0) {
                return false;
            }
        }
    }
    return true;
}
References TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), TTAMachine::Machine::registerFileNavigator(), socketAttachedToAllBusses(), TTAMachine::Port::socketCount(), and TTAMachine::Machine::socketNavigator().
Referenced by RegisterQuantityCheck::check(), RegisterQuantityCheck::checkIntRegs(), RegisterQuantityCheck::checkWithIgnore(), RegisterQuantityCheck::checkWithIgnore(), RegisterQuantityCheck::fixIntRegs(), and FullyConnectBussesCmd::isEnabled().
check() [2/2]
bool FullyConnectedCheck::check (const TTAMachine::Machine & mach, MachineCheckResults & results) const virtual
Checks is the machine fully connected and adds errors to results.
Parameters
mach Machine to be checked.
results Check results.
Returns
True if the machine is fully connected.
Implements MachineCheck.
Definition at line 170 of file FullyConnectedCheck.cc.
{
    bool result = true;
    const Machine::SocketNavigator
        socketNav = mach.socketNavigator();
    for (int so = 0; so < socketNav.count(); so++) {
        // for each socket in the machine
        if (!socketAttachedToAllBusses(*socketNav.item(so))) {
            results.addError(
                *this, "All sockets not connected to all busses.");
            result = false;
        }
    }
    // check unconnected FU ports
    const Machine::FunctionUnitNavigator fuNav = mach.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit& fu = *fuNav.item(i);
        for (int p = 0; p < fu.operationPortCount(); p++) {
            FUPort& port = *fu.operationPort(p);
            if (port.socketCount() == 0) {
                results.addError(
                    *this, "FU: '" + fu.name() + "' port '" +
                    port.name() + "' not connected to any socket.");
                result = false;
            }
        }
    }
    // check unconnected IU ports
    const Machine::ImmediateUnitNavigator iuNav =
        mach.immediateUnitNavigator();
    for (int i = 0; i < iuNav.count(); i++) {
        ImmediateUnit& iu = *iuNav.item(i);
        for (int p = 0; p < iu.portCount(); p++) {
            RFPort& port = *iu.port(p);
            if (port.socketCount() == 0) {
                results.addError(
                    *this, "IU: '" + iu.name() + "' port '" +
                    port.name() + "' not connected to any socket.");
                result = false;
            }
        }
    }
    // check unconnected RF ports
    const Machine::RegisterFileNavigator rfNav = mach.registerFileNavigator();
    for (int i = 0; i < rfNav.count(); i++) {
        RegisterFile& rf = *rfNav.item(i);
        for (int p = 0; p < rf.portCount(); p++) {
            RFPort& port = *rf.port(p);
            if (port.socketCount() == 0) {
                results.addError(
                    *this, "RF: '" + rf.name() + "' port '" +
                    port.name() + "' not connected to any socket.");
                result = false;
            }
        }
    }
    ControlUnit* gcu = mach.controlUnit();
    if (gcu != NULL) {
        for (int p = 0; p < gcu->operationPortCount(); p++) {
            FUPort& port = *gcu->operationPort(p);
            if (port.socketCount() == 0) {
                results.addError(
                    *this, "GCU port '" +
                    port.name() + "' not connected to any socket.");
                return false;
            }
        }
        for (int p = 0; p < gcu->specialRegisterPortCount(); p++) {
            SpecialRegisterPort& port = *gcu->specialRegisterPort(p);
            if (port.socketCount() == 0) {
                results.addError(
                    *this, "GCU port '" +
                    port.name() + "' not connected to any socket.");
            }
        }
    }
    return result;
}
References MachineCheckResults::addError(), TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), TTAMachine::Machine::registerFileNavigator(), socketAttachedToAllBusses(), TTAMachine::Port::socketCount(), TTAMachine::Machine::socketNavigator(), TTAMachine::ControlUnit::specialRegisterPort(), and TTAMachine::ControlUnit::specialRegisterPortCount().
connectControlUnit()
void FullyConnectedCheck::connectControlUnit (TTAMachine::ControlUnit & gcu) const
Definition at line 363 of file FullyConnectedCheck.cc.
{
    for (int p = 0; p < gcu.operationPortCount(); p++) {
        FUPort& port = *gcu.operationPort(p);
        if (port.socketCount() == 0) {
            connectFUPort(port);
        }
    }
    for (int p = 0; p < gcu.specialRegisterPortCount(); p++) {
        SpecialRegisterPort& port = *gcu.specialRegisterPort(p);
        if (port.socketCount() == 0) {
            connectSpecialRegisterPort(port);
        }
    }
}
References connectFUPort(), connectSpecialRegisterPort(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::Port::socketCount(), TTAMachine::ControlUnit::specialRegisterPort(), and TTAMachine::ControlUnit::specialRegisterPortCount().
Referenced by ADFCombiner::addFunctionUnits(), and fix().
connectFUPort()
void FullyConnectedCheck::connectFUPort (TTAMachine::FUPort & port) const
Creates socket(s) and connects a FU port to all possible busses.
Parameters
port FU port to connect to busses.
Definition at line 497 of file FullyConnectedCheck.cc.
{
    const FunctionUnit& fu = *port.parentUnit();
    Machine& machine = *fu.machine();
    MachineTester tester(machine);
    const TTAMachine::Machine::BusNavigator busNav = machine.busNavigator();
    const Machine::SocketNavigator socketNav =
        machine.socketNavigator();
    // Operand ports.
    for (int i = 0; i < fu.operationCount(); i++) {
        const HWOperation& operation = *fu.operation(i);
        for (int c = 0; c < operation.latency(); c++) {
            if (port.inputSocket() == NULL &&
                operation.pipeline()->isPortRead(port, c)) {
                Socket* socket = createSocket(fu, Socket::INPUT);
                if (tester.canConnect(*socket, port)) {
                    port.attachSocket(*socket);
                } else {
                    delete socket;
                }
                break;
            }
        }
    }
    // Result ports.
    for (int i = 0; i < fu.operationCount(); i++) {
        const HWOperation& operation = *fu.operation(i);
        for (int c = 0; c < operation.latency(); c++) {
            if (port.outputSocket() == NULL &&
                operation.pipeline()->isPortWritten(port, c)) {
                Socket* socket = createSocket(fu, Socket::OUTPUT);
                if (tester.canConnect(*socket, port)) {
                    port.attachSocket(*socket);
                } else {
                    delete socket;
                }
                break;
            }
        }
    }
}
References TTAMachine::Port::attachSocket(), TTAMachine::Machine::busNavigator(), MachineTester::canConnect(), createSocket(), TTAMachine::Socket::INPUT, TTAMachine::Port::inputSocket(), TTAMachine::ExecutionPipeline::isPortRead(), TTAMachine::ExecutionPipeline::isPortWritten(), TTAMachine::HWOperation::latency(), TTAMachine::Component::machine(), machine, TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::Socket::OUTPUT, TTAMachine::Port::outputSocket(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::HWOperation::pipeline(), and TTAMachine::Machine::socketNavigator().
Referenced by connectControlUnit(), fix(), and MinimalOpSetCheck::fix().
connectIUPort()
void FullyConnectedCheck::connectIUPort (TTAMachine::RFPort & port) const private
Connects an immediate unit port to all possible busses.
Parameters
port Immediate unit port to connect.
Definition at line 383 of file FullyConnectedCheck.cc.
{
    MachineTester tester(*port.parentUnit()->machine());
    Socket* socket = createSocket(*port.parentUnit(), Socket::OUTPUT);
    if (tester.canConnect(*socket, port)) {
        port.attachSocket(*socket);
    } else {
        delete socket;
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), createSocket(), TTAMachine::Component::machine(), TTAMachine::Socket::OUTPUT, and TTAMachine::RFPort::parentUnit().
Referenced by fix().
connectRFPort()
void FullyConnectedCheck::connectRFPort (TTAMachine::RFPort & port, TTAMachine::Socket::Direction direction) const private
Connects a register file port to all possible busses.
Parameters
port Immediate unit port to connect.
Definition at line 430 of file FullyConnectedCheck.cc.
{
    MachineTester tester(*port.parentUnit()->machine());
    const BaseRegisterFile& rf = *port.parentUnit();
    Socket* socket = NULL;
    socket = createSocket(rf, direction);
    if (tester.canConnect(*socket, port)) {
        port.attachSocket(*socket);
    } else {
        delete socket;
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), createSocket(), TTAMachine::Component::machine(), and TTAMachine::RFPort::parentUnit().
Referenced by fix().
connectSpecialRegisterPort()
void FullyConnectedCheck::connectSpecialRegisterPort (TTAMachine::SpecialRegisterPort & port) const
Connects a special register port to all possible busses.
Parameters
port Special register port to connect.
Definition at line 402 of file FullyConnectedCheck.cc.
{
    MachineTester tester(*port.parentUnit()->machine());
    Socket* inSocket = createSocket(*port.parentUnit(), Socket::INPUT);
    Socket* outSocket = createSocket(*port.parentUnit(), Socket::OUTPUT);
    if (tester.canConnect(*inSocket, port)) {
        port.attachSocket(*inSocket);
    } else {
        delete inSocket;
    }
    if (tester.canConnect(*outSocket, port)) {
        port.attachSocket(*outSocket);
    } else {
        delete outSocket;
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), createSocket(), TTAMachine::Socket::INPUT, TTAMachine::Component::machine(), TTAMachine::Socket::OUTPUT, and TTAMachine::BaseFUPort::parentUnit().
Referenced by connectControlUnit().
createSocket()
Socket * FullyConnectedCheck::createSocket (const TTAMachine::Unit & unit, TTAMachine::Socket::Direction direction) const private
Creates a new socket to be attached to an unit.
Parameters
unit Unit whose name is used to generate a name for the socket.
direction Direction of the socket.
Returns
A new socket, attached to all possible busses, but not to a port.
Definition at line 454 of file FullyConnectedCheck.cc.
{
    TTAMachine::Machine& machine = *unit.machine();
    const TTAMachine::Machine::SocketNavigator socketNav =
        machine.socketNavigator();
    int s = 1;
    std::string socketName = unit.name();
    if (direction == Socket::INPUT) {
        socketName = socketName + "_i";
    } else {
        socketName = socketName + "_o";
    }
    while (socketNav.hasItem(
               socketName + Conversion::toString(s))) {
        s++;
    }
    Socket* socket =
        new Socket(socketName + Conversion::toString(s));
    socket->setMachine(machine);
    attachSocketToAllBusses(*socket);
    // direction can be set only if the socket is connected to a segment
    if (socket->segmentCount() > 0) {
        socket->setDirection(direction);
    }
    return socket;
}
References attachSocketToAllBusses(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Socket::INPUT, TTAMachine::Component::machine(), machine, TTAMachine::Component::name(), TTAMachine::Socket::segmentCount(), TTAMachine::Socket::setDirection(), TTAMachine::Socket::setMachine(), TTAMachine::Machine::socketNavigator(), and Conversion::toString().
Referenced by connectFUPort(), connectIUPort(), connectRFPort(), and connectSpecialRegisterPort().
fix()
std::string FullyConnectedCheck::fix (TTAMachine::Machine & mach) const virtual
Fixes the machine to pass the chek if possible.
Parameters
mach Machine to be fixed.
Returns
Returns an empty string.
Exceptions
InvalidData Thows if the machine cannot be fixed.
Reimplemented from MachineCheck.
Definition at line 267 of file FullyConnectedCheck.cc.
{
    if (!canFix(mach)) {
        throw InvalidData(
            __FILE__, __LINE__, __func__,
            "Machines contains no busses or contains bridges.");
    }
    const Machine::SocketNavigator
        socketNav = mach.socketNavigator();
    for (int so = 0; so < socketNav.count(); so++) {
        // for each socket in the machine
        attachSocketToAllBusses(*socketNav.item(so));
    }
    // Connect all unconnected FU ports to newly created sockets.
    const Machine::FunctionUnitNavigator fuNav = mach.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit& fu = *fuNav.item(i);
        for (int p = 0; p < fu.operationPortCount(); p++) {
            FUPort& port = *fu.operationPort(p);
            if (port.socketCount() == 0) {
                connectFUPort(port);
            }
        }
    }
    // Connect all unconnected IU ports to new sockets.
    const Machine::ImmediateUnitNavigator iuNav =
        mach.immediateUnitNavigator();
    for (int i = 0; i < iuNav.count(); i++) {
        ImmediateUnit& iu = *iuNav.item(i);
        for (int p = 0; p < iu.portCount(); p++) {
            RFPort& port = *iu.port(p);
            if (port.socketCount() == 0) {
                connectIUPort(port);
            }
        }
    }
    // Connect all unconnected RF ports to new sockets.
    const Machine::RegisterFileNavigator rfNav = mach.registerFileNavigator();
    for (int i = 0; i < rfNav.count(); i++) {
        RegisterFile& rf = *rfNav.item(i);
        int maxReads = rf.maxReads();
        int maxWrites = rf.maxWrites();
        bool lastWasReadPort = false;
        for (int p = 0; p < rf.portCount(); p++) {
            RFPort& port = *rf.port(p);
            if (port.socketCount() == 0) {
                if (maxReads > 0) {
                    connectRFPort(port, Socket::OUTPUT);
                    maxReads--;
                } else if (maxWrites > 0) {
                    connectRFPort(port, Socket::INPUT);
                    maxWrites--;
                } else {
                    // when maxReads == 0 and maxWrites == 0, connect every other
                    // port as a read port, every other as write
                    if (lastWasReadPort) {
                        connectRFPort(port, Socket::INPUT);
                        lastWasReadPort = false;
                    } else {
                        connectRFPort(port, Socket::OUTPUT);
                        lastWasReadPort = true;
                    }
                }
            }
            else // port connected, check wheter it is input or output
            {
                if (port.inputSocket() != NULL) {
                    maxWrites--;
                } else if (port.outputSocket() != NULL) {
                    maxReads--;
                } else {
                    // port connected, but input and output sockets are null
                    throw InvalidData(
                        __FILE__, __LINE__, __func__,
                        "Port connected to unknown socket.");
                }
            }
        }
    }
    ControlUnit* gcu = mach.controlUnit();
    if (gcu != NULL) {
        connectControlUnit(*gcu);
    }
    return "";
}
References __func__, attachSocketToAllBusses(), canFix(), connectControlUnit(), connectFUPort(), connectIUPort(), connectRFPort(), TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Socket::INPUT, TTAMachine::Port::inputSocket(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::RegisterFile::maxReads(), TTAMachine::RegisterFile::maxWrites(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::Socket::OUTPUT, TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), TTAMachine::Machine::registerFileNavigator(), TTAMachine::Port::socketCount(), and TTAMachine::Machine::socketNavigator().
Referenced by MachineResourceModifier::addBusesByAmount(), FullyConnectBussesCmd::Do(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), MachineResourceModifier::percentualFUIncrease(), and MachineResourceModifier::percentualRegisterIncrease().
socketAttachedToAllBusses()
bool FullyConnectedCheck::socketAttachedToAllBusses (const TTAMachine::Socket & socket) const private
Checks if the given socket is attached to all possible busses.
Parameters
socket Socket to check.
Returns
True if the socket is attached to all possible busses.
Definition at line 581 of file FullyConnectedCheck.cc.
{
    TTAMachine::Machine& machine = *socket.machine();
    MachineTester tester(machine);
    const TTAMachine::Machine::BusNavigator busNav = machine.busNavigator();
    for (int b = 0; b < busNav.count(); b++) {
        // for each bus in the machine
        TTAMachine::Bus& bus = *busNav.item(b);
        for (int seg = 0; seg < bus.segmentCount(); seg++) {
            TTAMachine::Segment& segment = *bus.segment(seg);
            // for each segment in the bus
            if (!socket.isConnectedTo(segment)) {
                if (tester.canConnect(socket, segment)) {
                    return false;
                }
            }
        }
    }
    return true;
}
References TTAMachine::Machine::busNavigator(), MachineTester::canConnect(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Socket::isConnectedTo(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), machine, TTAMachine::Bus::segment(), and TTAMachine::Bus::segmentCount().
Referenced by check(), and check().
The documentation for this class was generated from the following files:
FullyConnectedCheck.hh
FullyConnectedCheck.cc