OpenASIP: BFPushAntidepsDown Class Reference
BFPushAntidepsDown Class Reference
#include <BFPushAntidepsDown.hh>
Public Member Functions
BFPushAntidepsDown (BF2Scheduler &sched, MoveNode &adepSrc, int oldLC, int maxLC)
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & adepSource_
int oldLC_
int maxLC_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 44 of file BFPushAntidepsDown.hh.
Constructor & Destructor Documentation
BFPushAntidepsDown()
BFPushAntidepsDown::BFPushAntidepsDown (BF2Scheduler & sched, MoveNode & adepSrc, int oldLC, int maxLC) inline
Definition at line 46 of file BFPushAntidepsDown.hh.
                                                                  :
    BFOptimization(sched),
    adepSource_(adepSrc), oldLC_(oldLC), maxLC_(maxLC) {}
Member Function Documentation
operator()()
bool BFPushAntidepsDown::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 46 of file BFPushAntidepsDown.cc.
{
    DataDependenceGraph::EdgeSet outEdges = ddg().outEdges(adepSource_);
    int newLC = maxLC_;
    std::list<BFPushAntidepDown*> rescheds;
    for (auto e: outEdges) {
        if ((e->edgeReason() == DataDependenceEdge::EDGE_REGISTER ||
             e->edgeReason() == DataDependenceEdge::EDGE_RA) &&
            e->isFalseDep()) {
            MoveNode& aDepHead = ddg().headNode(*e);
            if (!aDepHead.isScheduled()) {
                continue;
            }
            int cycle = aDepHead.cycle();
            int lat = 1;
            if (e->guardUse()) {
                lat = adepSource_.guardLatency();
            }
            if (cycle + lat > maxLC_) {
                continue;
            }
            int dstLC = ddg().latestCycle(aDepHead);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\tShould rescheduling move at: "
                      << aDepHead.toString() << std::endl;
            std::cerr << "\t\tdstLC: " << dstLC << std::endl;
#endif
            if (dstLC > aDepHead.cycle()) {
                rescheds.push_back(
                    new BFPushAntidepDown(sched_, aDepHead, lat, newLC));
            }
            int curLC = dstLC - lat + 1;
            if (curLC < newLC) {
                newLC = curLC;
            }
        }
    }
    // can we improve the situation at all?
    if (newLC <= oldLC_) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "newLC: " << newLC << " old LC: " << oldLC_ << std::endl;
#endif
        for (std::list<BFPushAntidepDown*>::iterator i = rescheds.begin();
             i != rescheds.end();) {
            BFPushAntidepDown* bfo = *i;
            delete bfo;
            rescheds.erase(i++);
        }
//  assert(rescheds.empty());
        return false;
    } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tCould improve? newLC: " << newLC << std::endl;
#endif
    }
    for (auto i = rescheds.begin(); i != rescheds.end();) {
        BFPushAntidepDown* bfo = *i;
        rescheds.erase(i++);
        runPostChild(bfo);
    }
    return !postChildren_.empty();
}
References adepSource_, MoveNode::cycle(), BFOptimization::ddg(), DataDependenceEdge::EDGE_RA, DataDependenceEdge::EDGE_REGISTER, MoveNode::guardLatency(), BoostGraph< GraphNode, GraphEdge >::headNode(), MoveNode::isScheduled(), DataDependenceGraph::latestCycle(), maxLC_, oldLC_, BoostGraph< GraphNode, GraphEdge >::outEdges(), Reversible::postChildren_, Reversible::runPostChild(), BFOptimization::sched_, and MoveNode::toString().
Member Data Documentation
adepSource_
MoveNode& BFPushAntidepsDown::adepSource_ private
Definition at line 52 of file BFPushAntidepsDown.hh.
Referenced by operator()().
maxLC_
int BFPushAntidepsDown::maxLC_ private
Definition at line 54 of file BFPushAntidepsDown.hh.
Referenced by operator()().
oldLC_
int BFPushAntidepsDown::oldLC_ private
Definition at line 53 of file BFPushAntidepsDown.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPushAntidepsDown.hh
BFPushAntidepsDown.cc