OpenASIP: BFAssignToBody Class Reference
BFAssignToBody Class Reference
#include <BFAssignToBody.hh>
Public Member Functions
BFAssignToBody (BF2Scheduler &sched, MoveNode &mn, int cycle, const TTAMachine::FunctionUnit *srcFU, const TTAMachine::FunctionUnit *dstFU)
bool operator() () override
void undoOnlyMe () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & mn_
int cycle_
const TTAMachine::FunctionUnit * srcFU_
const TTAMachine::FunctionUnit * dstFU_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 42 of file BFAssignToBody.hh.
Constructor & Destructor Documentation
BFAssignToBody()
BFAssignToBody::BFAssignToBody (BF2Scheduler & sched, MoveNode & mn, int cycle, const TTAMachine::FunctionUnit * srcFU, const TTAMachine::FunctionUnit * dstFU) inline
Definition at line 44 of file BFAssignToBody.hh.
                                                        :
        BFOptimization(sched), mn_(mn), cycle_(cycle), srcFU_(srcFU),
        dstFU_(dstFU) {}
Member Function Documentation
operator()()
bool BFAssignToBody::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 41 of file BFAssignToBody.cc.
{
    if (!rm().canAssign(cycle_, mn_, nullptr, srcFU_, dstFU_)) {
        return false;
    }
    rm().assign(cycle_, mn_, nullptr, srcFU_, dstFU_);
    return true;
}
References SimpleResourceManager::assign(), BFOptimization::canAssign(), cycle_, dstFU_, mn_, BFOptimization::rm(), and srcFU_.
undoOnlyMe()
void BFAssignToBody::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 49 of file BFAssignToBody.cc.
{
    rm().unassign(mn_);
}
References mn_, BFOptimization::rm(), and SimpleResourceManager::unassign().
Member Data Documentation
cycle_
int BFAssignToBody::cycle_ private
Definition at line 53 of file BFAssignToBody.hh.
Referenced by operator()().
dstFU_
const TTAMachine::FunctionUnit* BFAssignToBody::dstFU_ private
Definition at line 55 of file BFAssignToBody.hh.
Referenced by operator()().
mn_
MoveNode& BFAssignToBody::mn_ private
Definition at line 52 of file BFAssignToBody.hh.
Referenced by operator()(), and undoOnlyMe().
srcFU_
const TTAMachine::FunctionUnit* BFAssignToBody::srcFU_ private
Definition at line 54 of file BFAssignToBody.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFAssignToBody.hh
BFAssignToBody.cc