OpenASIP: InputPSocketResource Class Reference
InputPSocketResource Class Reference
#include <InputPSocketResource.hh>
Public Member Functions
virtual ~InputPSocketResource ()
InputPSocketResource (const std::string &name, unsigned int initiationInterval=0)
virtual bool isInputPSocketResource () const override
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual bool operator< (const SchedulingResource &other) const override
Public Member Functions inherited from PSocketResource
virtual ~PSocketResource ()
PSocketResource (const std::string &name, unsigned int initiationInterval=0)
virtual bool isInUse (const int cycle) const override
virtual bool isAvailable (const int cycle) const override
virtual void assign (const int cycle, MoveNode &node) override
virtual void unassign (const int cycle, MoveNode &node) override
void clear () override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Member Functions
InputPSocketResource (const InputPSocketResource &)
InputPSocketResource & operator= (const InputPSocketResource &)
Additional Inherited Members
Protected Types inherited from PSocketResource
typedef std::map< int, std::set< MoveNode * > > ResourceRecordType
Protected Attributes inherited from PSocketResource
ResourceRecordType resourceRecord_
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model The derived class InputPSocketResource
Definition at line 47 of file InputPSocketResource.hh.
Constructor & Destructor Documentation
~InputPSocketResource()
InputPSocketResource::~InputPSocketResource () virtual
Empty destructor
Definition at line 50 of file InputPSocketResource.cc.
{}
InputPSocketResource() [1/2]
InputPSocketResource::InputPSocketResource (const std::string & name, unsigned int initiationInterval = 0)
Constructor defining resource name
Parameters
name Name of resource
Definition at line 44 of file InputPSocketResource.cc.
                                                                                                 :
    PSocketResource(name, initiationInterval) {}
InputPSocketResource() [2/2]
InputPSocketResource::InputPSocketResource (const InputPSocketResource &) private
Member Function Documentation
canAssign()
bool InputPSocketResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Return true if resource can be assigned for given resource in given cycle.
Parameters
cycle Cycle to test
node MoveNode to test
Returns
true if node can be assigned to cycle
Reimplemented from PSocketResource.
Definition at line 102 of file InputPSocketResource.cc.
          {
    ResourceRecordType::const_iterator iter = resourceRecord_.find(cycle);
    if (iter != resourceRecord_.end()) {
        std::set<MoveNode*> movesInCycle = iter->second;
        for (std::set<MoveNode*>::iterator it = movesInCycle.begin();
             it != movesInCycle.end(); it++) {
#ifdef NO_OVERCOMMIT
            return false;
#else
            MoveNode* mn = *it;
            if (node.move().isUnconditional() ||
                mn->move().isUnconditional()) {
                return false;
            }
            if (!node.move().guard().guard().isOpposite(
                    mn->move().guard().guard())) {
                return false;
            }
#endif
        }
    }
    return true;
}
References TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), TTAMachine::Guard::isOpposite(), TTAProgram::Move::isUnconditional(), MoveNode::move(), and PSocketResource::resourceRecord_.
Referenced by InputFUResource::canAssign().
isInputPSocketResource()
bool InputPSocketResource::isInputPSocketResource () const override virtual
Allways return true
Returns
true
Reimplemented from SchedulingResource.
Definition at line 57 of file InputPSocketResource.cc.
{
    return true;
}
operator<()
bool InputPSocketResource::operator< (const SchedulingResource & other) const override virtual
Comparison operator.
Favours sockets which have less connections.
Reimplemented from SchedulingResource.
Definition at line 133 of file InputPSocketResource.cc.
{
    const InputPSocketResource *ipsr =
        dynamic_cast<const InputPSocketResource*>(&other);
    if (ipsr == NULL) {
        return false;
    }
    // favour sockets which have connections to busses with fewest connections
    // calculate the connections..
    int connCount = 0;
    int connCount2 = 0;
    for (int i = 0; i < relatedResourceCount(1); i++) {
        SchedulingResource& r = relatedResource(1,i);
        connCount += r.relatedResourceCount(0);
    }
    for (int i = 0; i < other.relatedResourceCount(1); i++) {
        SchedulingResource& r = other.relatedResource(1,i);
        connCount2 += r.relatedResourceCount(0);
    }
    // then the comparison.
    if (connCount < connCount2) {
        return true;
    }
    if (connCount > connCount2) {
        return false;
    }
    // favour sockets with less buses.
    if (relatedResourceCount(1) < ipsr->relatedResourceCount(1)) {
        return true;
    }
    if (relatedResourceCount(1) > ipsr->relatedResourceCount(1)) {
        return false;
    }
    // then use the default use count, name comparison,
    // but in opposite direction, facouring already used
    return other.SchedulingResource::operator<(*this);
}
References SchedulingResource::relatedResource(), and SchedulingResource::relatedResourceCount().
operator=()
InputPSocketResource & InputPSocketResource::operator= (const InputPSocketResource &) private
validateDependentGroups()
bool InputPSocketResource::validateDependentGroups () override protected virtual
Tests if all referred resources in dependent groups are of proper types
Returns
true Allways true, dep. groups are empty
Reimplemented from SchedulingResource.
Definition at line 67 of file InputPSocketResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        if (dependentResourceCount(i) > 0) {
            return false;
        }
    }
    return true;
}
References SchedulingResource::dependentResourceCount(), and SchedulingResource::dependentResourceGroupCount().
validateRelatedGroups()
bool InputPSocketResource::validateRelatedGroups () override protected virtual
Tests if all referred resources in related groups are of proper types
Returns
true If all resources in related groups are Segment or InputFU resources
Reimplemented from SchedulingResource.
Definition at line 83 of file InputPSocketResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        for (int j = 0, count = relatedResourceCount(i); j < count; j++) {
            if (!(relatedResource(i, j).isInputFUResource() ||
                relatedResource(i, j).isBusResource()))
                return false;
        }
    }
    return true;
}
References SchedulingResource::isBusResource(), SchedulingResource::isInputFUResource(), SchedulingResource::relatedResource(), SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
The documentation for this class was generated from the following files:
InputPSocketResource.hh
InputPSocketResource.cc