OpenASIP: HDLGenerator::CodeBlock Class Reference
HDLGenerator::CodeBlock Class Reference
#include <HDLGenerator.hh>
Public Member Functions
CodeBlock ()
template<typename SS >
void append (SS cc)
void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void build ()
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Detailed Description
Code block, i.e., a collection of concurrent statements
Definition at line 877 of file HDLGenerator.hh.
Constructor & Destructor Documentation
CodeBlock()
HDLGenerator::CodeBlock::CodeBlock () inline
Definition at line 879 of file HDLGenerator.hh.
: SequentialStatement("codeBlock") {}
Member Function Documentation
append()
template<typename SS > void HDLGenerator::CodeBlock::append (SS cc) inline
Definition at line 882 of file HDLGenerator.hh.
{
            std::shared_ptr<SequentialStatement> ptr = std::make_shared<SS>(cc);
            pushComponent(ptr);
        }
References HDLGenerator::Generatable::pushComponent().
Referenced by FUGen::buildOperations(), FUGen::createOutputPipeline(), FUGen::createPortPipeline(), and FUGen::prepareSnippet().
hdl()
void HDLGenerator::CodeBlock::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 887 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                implementAll(stream, lang, level);
            } else if (lang == Language::Verilog) {
                implementAll(stream, lang, level);
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References HDLGenerator::Generatable::implementAll(), HDLGenerator::Verilog, and HDLGenerator::VHDL.
The documentation for this class was generated from the following file:
HDLGenerator.hh