OpenASIP: ProGe::GeneratableFUNetlistBlock Class Reference
ProGe::GeneratableFUNetlistBlock Class Reference
#include <GeneratableFUNetlistBlock.hh>
Public Member Functions
GeneratableFUNetlistBlock (const std::string &moduleName, const std::string instanceName, NetlistGenerator &generator)
virtual ~GeneratableFUNetlistBlock ()=default
void addInOperand (TTAMachine::FUPort *port, int id)
void addOutOperand (TTAMachine::FUPort *port)
Public Member Functions inherited from ProGe::NetlistBlock
NetlistBlock (const std::string &moduleName, const std::string &instanceName, BaseNetlistBlock *parent=NULL)
virtual ~NetlistBlock ()
void setParameter (const std::string &name, const std::string &type, const std::string &value)
void removePort (NetlistPort &port)
virtual NetlistPort * port (const std::string &portName, bool partialMatch=true)
NetlistBlock & subBlock (size_t index) override
virtual const NetlistBlock & parentBlock () const override
virtual NetlistBlock & parentBlock () override
NetlistBlock * shallowCopy (const std::string &instanceName) const
virtual void write (const Path &targetBaseDir, HDL targetLang=VHDL) const override
void addParameter (const Parameter &param)
void setParameter (const Parameter &param)
virtual const Parameter & parameter (const std::string &name) const
virtual const Parameter & parameter (size_t index) const
Parameter & parameter (const std::string &name)
NetlistPort * addPort (NetlistPort *port)
void removePort (NetlistPort *port)
virtual size_t portCount () const
virtual const NetlistPort & port (size_t index) const
virtual const NetlistPort * port (const std::string &portName, bool partialMatch=true) const
virtual NetlistPort & port (size_t index)
void addPortGroup (NetlistPortGroup *portGroup)
void addSubBlock (BaseNetlistBlock *subBlock, const std::string &instanceName="")
virtual size_t subBlockCount () const
virtual const Netlist & netlist () const
Netlist & netlist ()
void addPackage (const std::string &packageName)
virtual size_t packageCount () const
virtual const std::string & package (size_t idx) const
Public Member Functions inherited from ProGe::BaseNetlistBlock
BaseNetlistBlock ()
BaseNetlistBlock (BaseNetlistBlock *parent)
BaseNetlistBlock (const std::string &moduleName, const std::string &instanceName, BaseNetlistBlock *parent=nullptr)
virtual ~BaseNetlistBlock ()
const std::string & instanceName () const
void setInstanceName (const std::string &name)
const std::string & moduleName () const
const std::string name () const
virtual const BaseNetlistBlock & subBlock (size_t index) const
virtual bool hasSubBlock (const std::string &instanceName) const
virtual bool isSubBlock (const BaseNetlistBlock &block) const
virtual bool hasParameter (const std::string &name) const
virtual size_t parameterCount () const
virtual std::vector< const NetlistPort * > portsBy (SignalType type) const
virtual const NetlistPort & portBy (SignalType type, size_t index=0) const
virtual bool hasPortsBy (SignalType type) const
virtual size_t portGroupCount () const
virtual const NetlistPortGroup & portGroup (size_t index) const
virtual std::vector< const NetlistPortGroup * > portGroupsBy (SignalGroupType type) const
virtual bool hasParentBlock () const
virtual bool isVirtual () const
virtual void build () override
virtual void connect () override
virtual void finalize () override
virtual void writeSelf (const Path &targetBaseDir, HDL targetLang=VHDL) const
PortContainerType & ports ()
virtual bool isLeaf () const
BaseNetlistBlock * shallowCopy (const std::string &instanceName="") const
Public Member Functions inherited from ProGe::IGenerationPhases
virtual ~IGenerationPhases ()
Private Attributes
NetlistGenerator & generator_
Additional Inherited Members
Public Types inherited from ProGe::BaseNetlistBlock
typedef std::vector< BaseNetlistBlock * > BlockContainerType
typedef std::vector< Parameter > ParameterContainerType
typedef std::vector< NetlistPort * > PortContainerType
typedef std::vector< NetlistPortGroup * > PortGroupContainerType
Protected Member Functions inherited from ProGe::BaseNetlistBlock
Netlist & netlist ()
void setModuleName (const std::string &name)
void addSubBlock (BaseNetlistBlock *subBlock, const std::string &instanceName="")
void deleteSubBlock (BaseNetlistBlock *subBlock)
void removeSubBlock (BaseNetlistBlock *subBlock)
NetlistPort * addPort (NetlistPort *port)
void removePort (NetlistPort *port)
void addPortGroup (NetlistPortGroup *portGroup)
void removePortGroup (NetlistPortGroup *portGroup)
void setParameter (const Parameter &param)
void addParameter (const Parameter &param)
Parameter & parameter (const std::string &name)
NetlistPort * findPort (const std::string &portName, bool recursiveSearch=false, bool partialMatch=true) const
void addPackage (const std::string &packageName)
void connectClocks ()
void connectResets ()
Detailed Description
Definition at line 40 of file GeneratableFUNetlistBlock.hh.
Constructor & Destructor Documentation
GeneratableFUNetlistBlock()
ProGe::GeneratableFUNetlistBlock::GeneratableFUNetlistBlock (const std::string & moduleName, const std::string instanceName, NetlistGenerator & generator) inline
Definition at line 42 of file GeneratableFUNetlistBlock.hh.
            : NetlistBlock(moduleName, instanceName), generator_(generator) {}
~GeneratableFUNetlistBlock()
virtual ProGe::GeneratableFUNetlistBlock::~GeneratableFUNetlistBlock () virtual default
Member Function Documentation
addInOperand()
void ProGe::GeneratableFUNetlistBlock::addInOperand (TTAMachine::FUPort * port, int id) inline
Definition at line 48 of file GeneratableFUNetlistBlock.hh.
{
            (void) id;
            NetlistPort* dataPort =
                new NetlistPort("data_" + port->name() + "_in",
                    std::to_string(port->width()), BIT_VECTOR, IN, *this);
            NetlistPort* loadPort = new NetlistPort(
                "load_" + port->name() + "_in", "1", BIT, IN, *this);
            generator_.mapLoadPort(*dataPort, *loadPort);
            generator_.mapNetlistPort(*port, *dataPort);
        }
References ProGe::BIT, ProGe::BIT_VECTOR, generator_, ProGe::IN, ProGe::NetlistGenerator::mapLoadPort(), ProGe::NetlistGenerator::mapNetlistPort(), ProGe::NetlistPort::name(), and ProGe::NetlistBlock::port().
Referenced by ProGe::NetlistGenerator::addGeneratableFUsToNetlist().
addOutOperand()
void ProGe::GeneratableFUNetlistBlock::addOutOperand (TTAMachine::FUPort * port) inline
Definition at line 58 of file GeneratableFUNetlistBlock.hh.
{
            NetlistPort* dataPort =
                new NetlistPort("data_" + port->name() + "_out",
                    std::to_string(port->width()), BIT_VECTOR, OUT, *this);
            generator_.mapNetlistPort(*port, *dataPort);
        }
References ProGe::BIT_VECTOR, generator_, ProGe::NetlistGenerator::mapNetlistPort(), ProGe::NetlistPort::name(), ProGe::OUT, and ProGe::NetlistBlock::port().
Referenced by ProGe::NetlistGenerator::addGeneratableFUsToNetlist().
Member Data Documentation
generator_
NetlistGenerator& ProGe::GeneratableFUNetlistBlock::generator_ private
Definition at line 66 of file GeneratableFUNetlistBlock.hh.
Referenced by addInOperand(), and addOutOperand().
The documentation for this class was generated from the following file:
GeneratableFUNetlistBlock.hh