OpenASIP: SchedulingResourceSet Class Reference
SchedulingResourceSet Class Reference
#include <SchedulingResource.hh>
Classes
struct less_name
Public Member Functions
SchedulingResourceSet ()
~SchedulingResourceSet ()
void insert (SchedulingResource &resource)
int count () const
SchedulingResource & resource (int index) const
void remove (SchedulingResource &resource)
SchedulingResourceSet & operator= (const SchedulingResourceSet &newSet)
void sort ()
void clear ()
bool hasResource (SchedulingResource &res)
Private Types
typedef std::vector< SchedulingResource * > ResourceList
Private Attributes
ResourceList resources_
Detailed Description
Set of scheduling resources.
Definition at line 161 of file SchedulingResource.hh.
Member Typedef Documentation
ResourceList
typedef std::vector<SchedulingResource*> SchedulingResourceSet::ResourceList private
Definition at line 175 of file SchedulingResource.hh.
Constructor & Destructor Documentation
SchedulingResourceSet()
SchedulingResourceSet::SchedulingResourceSet ()
Constructor.
Definition at line 222 of file SchedulingResource.cc.
{}
~SchedulingResourceSet()
SchedulingResourceSet::~SchedulingResourceSet ()
Destructor.
Definition at line 227 of file SchedulingResource.cc.
{}
Member Function Documentation
clear()
void SchedulingResourceSet::clear ()
Clears the scheduling resource set.
Definition at line 336 of file SchedulingResource.cc.
{
    resources_.clear();
}
References resources_.
Referenced by PendingAssignment::clear(), and operator=().
count()
int SchedulingResourceSet::count () const
Return the number of resources in the set.
Returns
The number of resources in the set.
Definition at line 251 of file SchedulingResource.cc.
{
    return resources_.size();
}
References resources_.
Referenced by BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), BusBroker::availableResource(), ITemplateBroker::instruction(), BusBroker::isAnyResourceAvailable(), PendingAssignment::isAssignmentPossible(), ITemplateBroker::isTemplateAvailable(), operator=(), and PendingAssignment::tryNext().
hasResource()
bool SchedulingResourceSet::hasResource (SchedulingResource & resource)
Tells whether the set has the given resource.
Definition at line 297 of file SchedulingResource.cc.
{
    ResourceList::iterator iter = resources_.begin();
    while (iter != resources_.end()) {
        if ((*iter) == &resource) {
            return true;
        }
        iter++;
    }
    return false;
}
References resource(), and resources_.
insert()
void SchedulingResourceSet::insert (SchedulingResource & resource)
Insert a scheduling resource in the set.
Parameters
resource Resource to insert.
Exceptions
ObjectAlreadyExists if the resource is already in the set.
Definition at line 236 of file SchedulingResource.cc.
{
    if (ContainerTools::containsValue(resources_, &resource)) {
        throw ObjectAlreadyExists(__FILE__, __LINE__, __func__);
    } else {
        resources_.push_back(&resource);
    }
}
References __func__, ContainerTools::containsValue(), resource(), and resources_.
Referenced by BusBroker::allAvailableResources(), InputFUBroker::allAvailableResources(), InputPSocketBroker::allAvailableResources(), OutputFUBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), IUBroker::allAvailableResources(), ITemplateBroker::findITemplates(), and operator=().
operator=()
SchedulingResourceSet & SchedulingResourceSet::operator= (const SchedulingResourceSet & newSet)
Assignment operator.
Parameters
newSet Set to assign resources from.
Returns
This set with newly assigned contents.
Definition at line 315 of file SchedulingResource.cc.
{
    resources_.clear();
    for (int i = 0; i < newSet.count(); i++) {
        insert(newSet.resource(i));
    }
    return *this;
}
References clear(), count(), insert(), resource(), and resources_.
remove()
void SchedulingResourceSet::remove (SchedulingResource & resource)
Remove a resource from the set.
Parameters
resource Scheduling resource to be removed.
Exceptions
KeyNotFound If given resource is not found in the set.
Definition at line 279 of file SchedulingResource.cc.
{
    ResourceList::iterator iter = resources_.begin();
    while (iter != resources_.end()) {
        if ((*iter) == &resource) {
            resources_.erase(iter);
            return;
        }
        iter++;
    }
    string msg = "Resource not found in resource set.";
    throw KeyNotFound(__FILE__, __LINE__, __func__, msg);
}
References __func__, resource(), and resources_.
Referenced by BusBroker::allAvailableResources().
resource()
SchedulingResource & SchedulingResourceSet::resource (int index) const
Return the resource at the given position.
Parameters
index Position of resource.
Returns
The resource at the given position.
Exceptions
OutOfRange If the given position exceeds number of resources.
Definition at line 263 of file SchedulingResource.cc.
{
    if (index < 0 || index >= static_cast<int>(resources_.size())) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    } else {
        return *resources_.at(index);
    }
}
References __func__, and resources_.
Referenced by BusBroker::allAvailableResources(), BusBroker::availableResource(), hasResource(), insert(), ITemplateBroker::instruction(), operator=(), remove(), PendingAssignment::resource(), and PendingAssignment::tryNext().
sort()
void SchedulingResourceSet::sort ()
Sort the content of Scheduling Resource Set by the names of the resources.
Definition at line 328 of file SchedulingResource.cc.
{
    std::sort(resources_.begin(), resources_.end(), less_name());
}
References resources_.
Referenced by ITemplateBroker::findITemplates(), and PendingAssignment::isAssignmentPossible().
Member Data Documentation
resources_
ResourceList SchedulingResourceSet::resources_ private
Definition at line 184 of file SchedulingResource.hh.
Referenced by clear(), count(), hasResource(), insert(), operator=(), remove(), resource(), and sort().
The documentation for this class was generated from the following files:
SchedulingResource.hh
SchedulingResource.cc