OpenASIP: HDLGenerator::Switch Class Reference
HDLGenerator::Switch Class Reference
#include <HDLGenerator.hh>
Public Member Functions
Switch (LHSValue control)
void addCase (Case rhs)
void addCase (DefaultCase rhs)
void build () override
void hdl (std::ostream &stream, Language lang, int level) override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
LHSValue control_
Detailed Description
Switch-case switch.
Definition at line 744 of file HDLGenerator.hh.
Constructor & Destructor Documentation
Switch()
HDLGenerator::Switch::Switch (LHSValue control) inline
Definition at line 746 of file HDLGenerator.hh.
                                 : SequentialStatement("switch"),
                                   control_(control) {}
Member Function Documentation
addCase() [1/2]
void HDLGenerator::Switch::addCase (Case rhs) inline
Definition at line 749 of file HDLGenerator.hh.
{
            addComponent(rhs);
        }
References HDLGenerator::Generatable::addComponent().
Referenced by FUGen::buildOperations().
addCase() [2/2]
void HDLGenerator::Switch::addCase (DefaultCase rhs) inline
Definition at line 753 of file HDLGenerator.hh.
{
            addComponent(rhs);
        }
References HDLGenerator::Generatable::addComponent().
build()
void HDLGenerator::Switch::build () inline override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 757 of file HDLGenerator.hh.
{
            Generatable::build();
            reads(control_);
        }
References HDLGenerator::Generatable::build(), control_, and HDLGenerator::Generatable::reads().
hdl()
void HDLGenerator::Switch::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 762 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                stream << StringTools::indent(level) << "case ";
                control_.hdl(stream, lang);
                stream << " is\n";
                implementAll(stream, lang, level + 1);
                stream << StringTools::indent(level) << "end case;\n";
            } else if (lang == Language::Verilog) {
                stream << StringTools::indent(level) << "case (";
                control_.hdl(stream, lang);
                stream << ")\n";
                implementAll(stream, lang, level + 1);
                stream << StringTools::indent(level) << "endcase\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References control_, HDLGenerator::LHSValue::hdl(), HDLGenerator::Generatable::implementAll(), StringTools::indent(), HDLGenerator::Verilog, and HDLGenerator::VHDL.
Member Data Documentation
control_
LHSValue HDLGenerator::Switch::control_ private
Definition at line 781 of file HDLGenerator.hh.
Referenced by build(), and hdl().
The documentation for this class was generated from the following file:
HDLGenerator.hh