OpenASIP: ProDeOptionsDialog Class Reference
ProDeOptionsDialog Class Reference
#include <ProDeOptionsDialog.hh>
Public Member Functions
ProDeOptionsDialog (wxWindow *parent, ProDeOptions &options, CommandRegistry &registry)
virtual ~ProDeOptionsDialog ()
Public Member Functions inherited from OptionsDialog
OptionsDialog (wxWindow *parent, GUIOptions &options, CommandRegistry &commandRegisry)
virtual ~OptionsDialog ()
Private Types
enum { ID_UNDO_LEVELS , ID_LABEL_UNDO_LEVELS }
Private Member Functions
void readProDeOptions ()
void writeProDeOptions ()
void onOK (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
wxSizer * createGeneralPage (wxWindow *parent, bool callFit, bool set_sizer)
Private Attributes
wxWindow * parent_
parent window of the dialog
ProDeOptions & options_
current editor options
wxSpinCtrl * undoStackSize_
Undo levels.
Additional Inherited Members
Protected Member Functions inherited from OptionsDialog
void addPage (wxPanel *page, const wxString &title)
virtual void readOptions ()
virtual void writeOptions ()
Protected Attributes inherited from OptionsDialog
wxNotebook * notebook_
Notebook containing dialog pages.
Detailed Description
Dialog for editing ProDeOptions.
Definition at line 48 of file ProDeOptionsDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_UNDO_LEVELS
ID_LABEL_UNDO_LEVELS
Definition at line 75 of file ProDeOptionsDialog.hh.
         {
        ID_UNDO_LEVELS,
        ID_LABEL_UNDO_LEVELS
    };
Constructor & Destructor Documentation
ProDeOptionsDialog()
ProDeOptionsDialog::ProDeOptionsDialog (wxWindow * parent, ProDeOptions & options, CommandRegistry & registry)
The Constructor.
Parameters
parent Parent window of the dialog.
options Options to be modified.
Definition at line 62 of file ProDeOptionsDialog.cc.
                                                                       :
    OptionsDialog(parent, options, registry),
    parent_(parent), options_(options) {
    wxPanel* generalPage = new wxPanel(notebook_, -1);
    createGeneralPage(generalPage, true, true);
    addPage(generalPage, _T("General"));
    undoStackSize_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_UNDO_LEVELS));
    readProDeOptions();
}
~ProDeOptionsDialog()
ProDeOptionsDialog::~ProDeOptionsDialog () virtual
The Destructor.
Definition at line 81 of file ProDeOptionsDialog.cc.
{
}
Member Function Documentation
createGeneralPage()
wxSizer * ProDeOptionsDialog::createGeneralPage (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the 'General' page for the dialog.
This function was initially generated by wxDesigner.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 133 of file ProDeOptionsDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxHORIZONTAL );
    item0->Add( 50, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item1 = new wxStaticText( parent, ID_LABEL_UNDO_LEVELS, wxT("Undo levels:"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item2 = new wxSpinCtrl( parent, ID_UNDO_LEVELS, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 100, 0 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_LABEL_UNDO_LEVELS, and ID_UNDO_LEVELS.
onHelp()
void ProDeOptionsDialog::onHelp (wxCommandEvent & event) private
onOK()
void ProDeOptionsDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the options.
Definition at line 106 of file ProDeOptionsDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    writeOptions();
    writeProDeOptions();
    EndModal(wxID_OK);
}
References OptionsDialog::writeOptions(), and writeProDeOptions().
readProDeOptions()
void ProDeOptionsDialog::readProDeOptions () private
Reads the options in options_ to dialog attributes.
Definition at line 88 of file ProDeOptionsDialog.cc.
{
    undoStackSize_->SetValue(options_.undoStackSize());
}
References options_, ProDeOptions::undoStackSize(), and undoStackSize_.
writeProDeOptions()
void ProDeOptionsDialog::writeProDeOptions () private
Writes the options from dialog attributes to the current options object.
Definition at line 97 of file ProDeOptionsDialog.cc.
{
    options_.setUndoStackSize(undoStackSize_->GetValue());
}
References options_, ProDeOptions::setUndoStackSize(), and undoStackSize_.
Referenced by onOK().
Member Data Documentation
options_
ProDeOptions& ProDeOptionsDialog::options_ private
current editor options
Definition at line 69 of file ProDeOptionsDialog.hh.
Referenced by readProDeOptions(), and writeProDeOptions().
parent_
wxWindow* ProDeOptionsDialog::parent_ private
parent window of the dialog
Definition at line 67 of file ProDeOptionsDialog.hh.
undoStackSize_
wxSpinCtrl* ProDeOptionsDialog::undoStackSize_ private
Undo levels.
Definition at line 72 of file ProDeOptionsDialog.hh.
Referenced by readProDeOptions(), and writeProDeOptions().
The documentation for this class was generated from the following files:
ProDeOptionsDialog.hh
ProDeOptionsDialog.cc