OpenASIP: SimpleSimulatorFrontend Class Reference
SimpleSimulatorFrontend Class Reference
#include <SimpleSimulatorFrontend.hh>
Public Member Functions
SimpleSimulatorFrontend (TCEString machineFile, bool useCompiledSimulation=false)
SimpleSimulatorFrontend (TCEString machineFile, TCEString programFile, bool useCompiledSimulation=false, bool useDetailedSimulation=false)
SimpleSimulatorFrontend (const TTAMachine::Machine &machine, const TTAProgram::Program &program)
virtual ~SimpleSimulatorFrontend ()
void step ()
void run ()
void stop ()
uint64_t cycleCount () const
bool isInitialized () const
bool isStopped () const
bool isRunning () const
bool isFinished () const
bool hadRuntimeError () const
virtual void setOperationSimulator (const TCEString &fuName, DetailedOperationSimulator &sim)
MemorySystem & memorySystem ()
void initializeDataMemories (const TTAMachine::AddressSpace *onlyOne=NULL)
void loadProgram (const std::string &fileName)
const TTAMachine::Machine & machine () const
const TTAProgram::Program & program () const
SimulatorFrontend & frontend ()
virtual bool registerEventListener (int event, Listener *listener)
virtual bool unregisterEventListener (int event, Listener *listener)
Private Attributes
SimulatorFrontend * simFront_
Detailed Description
Simplified simulator frontend e.g. for calling from system level simulators without needing to include the huge SimulatorFrontend.hh with lots of include deps.
Definition at line 58 of file SimpleSimulatorFrontend.hh.
Constructor & Destructor Documentation
SimpleSimulatorFrontend() [1/3]
SimpleSimulatorFrontend::SimpleSimulatorFrontend (TCEString machineFile, bool useCompiledSimulation = false)
Definition at line 38 of file SimpleSimulatorFrontend.cc.
{
    simFront_ =
        new SimulatorFrontend(
            useCompiledSimulation ?
            SimulatorFrontend::SIM_COMPILED :
            SimulatorFrontend::SIM_NORMAL);
    simFront_->setZeroFillMemoriesOnReset(false);
    try {
        simFront_->loadMachine(machineFile);
    } catch (Exception& e) {
        std::cerr
            << e.errorMessage() + " in " +
            e.fileName() + ":" +
            e.procedureName() + ":"
            << e.lineNum() << std::endl;
        abort();
    }
}
References Exception::errorMessage(), Exception::fileName(), Exception::lineNum(), SimulatorFrontend::loadMachine(), Exception::procedureName(), SimulatorFrontend::setZeroFillMemoriesOnReset(), SimulatorFrontend::SIM_COMPILED, SimulatorFrontend::SIM_NORMAL, and simFront_.
SimpleSimulatorFrontend() [2/3]
SimpleSimulatorFrontend::SimpleSimulatorFrontend (TCEString machineFile, TCEString programFile, bool useCompiledSimulation = false, bool useDetailedSimulation = false)
Definition at line 58 of file SimpleSimulatorFrontend.cc.
{
    simFront_ =
        new SimulatorFrontend(
            useCompiledSimulation ?
            SimulatorFrontend::SIM_COMPILED :
            SimulatorFrontend::SIM_NORMAL);
    simFront_->setZeroFillMemoriesOnReset(false);
    simFront_->setDetailedSimulation(useDetailedSimulation);
    try {
        simFront_->loadMachine(machineFile);
        simFront_->loadProgram(programFile);
    } catch (Exception& e) {
        std::cerr
            << e.errorMessage() + " in " +
            e.fileName() + ":" +
            e.procedureName() + ":"
            << e.lineNum() << std::endl;
        abort();
    }
}
References Exception::errorMessage(), Exception::fileName(), Exception::lineNum(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadProgram(), Exception::procedureName(), SimulatorFrontend::setDetailedSimulation(), SimulatorFrontend::setZeroFillMemoriesOnReset(), SimulatorFrontend::SIM_COMPILED, SimulatorFrontend::SIM_NORMAL, and simFront_.
SimpleSimulatorFrontend() [3/3]
SimpleSimulatorFrontend::SimpleSimulatorFrontend (const TTAMachine::Machine & machine, const TTAProgram::Program & program)
Definition at line 81 of file SimpleSimulatorFrontend.cc.
{
    simFront_ = new SimulatorFrontend();
    simFront_->setZeroFillMemoriesOnReset(false);
    try {
        simFront_->loadMachine(machine);
        simFront_->loadProgram(program);
    } catch (Exception& e) {
        std::cerr
            << e.errorMessage() + " in " +
            e.fileName() + ":" +
            e.procedureName() + ":"
            << e.lineNum() << std::endl;
        abort();
    }
}
References Exception::errorMessage(), Exception::fileName(), Exception::lineNum(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadProgram(), machine(), Exception::procedureName(), program(), SimulatorFrontend::setZeroFillMemoriesOnReset(), and simFront_.
~SimpleSimulatorFrontend()
SimpleSimulatorFrontend::~SimpleSimulatorFrontend () virtual
Definition at line 100 of file SimpleSimulatorFrontend.cc.
{
    delete simFront_;
}
References simFront_.
Member Function Documentation
cycleCount()
uint64_t SimpleSimulatorFrontend::cycleCount () const
Definition at line 212 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->cycleCount();
}
References SimulatorFrontend::cycleCount(), and simFront_.
frontend()
SimulatorFrontend & SimpleSimulatorFrontend::frontend () inline
Definition at line 93 of file SimpleSimulatorFrontend.hh.
{ return *simFront_; }
References simFront_.
hadRuntimeError()
bool SimpleSimulatorFrontend::hadRuntimeError () const
Definition at line 160 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->stopReasonCount() >= 1 &&
        simFront_->stopReason(0) == SRE_RUNTIME_ERROR;
}
References simFront_, SRE_RUNTIME_ERROR, SimulatorFrontend::stopReason(), and SimulatorFrontend::stopReasonCount().
initializeDataMemories()
void SimpleSimulatorFrontend::initializeDataMemories (const TTAMachine::AddressSpace * onlyOne = NULL)
Definition at line 217 of file SimpleSimulatorFrontend.cc.
{
    simFront_->initializeDataMemories(onlyOne);
}
References SimulatorFrontend::initializeDataMemories(), and simFront_.
isFinished()
bool SimpleSimulatorFrontend::isFinished () const
Definition at line 155 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->hasSimulationEnded();
}
References SimulatorFrontend::hasSimulationEnded(), and simFront_.
isInitialized()
bool SimpleSimulatorFrontend::isInitialized () const
Returns true in case the engine has the machine and the program loaded and is ready to execute, but has not been executed yet.
Definition at line 136 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->isSimulationInitialized();
}
References SimulatorFrontend::isSimulationInitialized(), and simFront_.
isRunning()
bool SimpleSimulatorFrontend::isRunning () const
Definition at line 150 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->isSimulationRunning();
}
References SimulatorFrontend::isSimulationRunning(), and simFront_.
isStopped()
bool SimpleSimulatorFrontend::isStopped () const
Retruns true in case the engine has been initialized and is ready to be stepped.
Definition at line 145 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->isSimulationStopped();
}
References SimulatorFrontend::isSimulationStopped(), and simFront_.
loadProgram()
void SimpleSimulatorFrontend::loadProgram (const std::string & fileName)
Definition at line 127 of file SimpleSimulatorFrontend.cc.
{
    simFront_->loadProgram(fileName);
}
References SimulatorFrontend::loadProgram(), and simFront_.
machine()
const TTAMachine::Machine & SimpleSimulatorFrontend::machine () const
Definition at line 166 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->machine();
}
References SimulatorFrontend::machine(), and simFront_.
Referenced by SimpleSimulatorFrontend().
memorySystem()
MemorySystem & SimpleSimulatorFrontend::memorySystem ()
Definition at line 176 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->memorySystem();
}
References SimulatorFrontend::memorySystem(), and simFront_.
program()
const TTAProgram::Program & SimpleSimulatorFrontend::program () const
Definition at line 171 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->program();
}
References SimulatorFrontend::program(), and simFront_.
Referenced by SimpleSimulatorFrontend().
registerEventListener()
bool SimpleSimulatorFrontend::registerEventListener (int event, Listener * listener) virtual
Definition at line 201 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->eventHandler().registerListener(event, listener);
}
References SimulatorFrontend::eventHandler(), Informer::registerListener(), and simFront_.
run()
void SimpleSimulatorFrontend::run ()
Definition at line 111 of file SimpleSimulatorFrontend.cc.
{
    simFront_->run();
}
References SimulatorFrontend::run(), and simFront_.
setOperationSimulator()
void SimpleSimulatorFrontend::setOperationSimulator (const TCEString & fuName, DetailedOperationSimulator & sim) virtual
Replaces all operation executors in the given FU with the given one.
Definition at line 185 of file SimpleSimulatorFrontend.cc.
{
    try {
        simFront_->machineState().fuState(fuName).
            setOperationSimulator(sim);
    } catch (Exception& e) {
        std::cerr
            << e.errorMessage() + " in " +
            e.fileName() + ":" +
            e.procedureName() + ":"
            << e.lineNum() << std::endl;
        abort();
    }
}
References Exception::errorMessage(), Exception::fileName(), MachineState::fuState(), Exception::lineNum(), SimulatorFrontend::machineState(), Exception::procedureName(), setOperationSimulator(), and simFront_.
Referenced by setOperationSimulator().
step()
void SimpleSimulatorFrontend::step ()
Definition at line 105 of file SimpleSimulatorFrontend.cc.
{
    if (!simFront_->hasSimulationEnded())
        simFront_->step();
}
References SimulatorFrontend::hasSimulationEnded(), simFront_, and SimulatorFrontend::step().
Referenced by TTACore::step().
stop()
void SimpleSimulatorFrontend::stop ()
Stops the current simulation.
This produces the same kind of stop as if the user pressed ctrl-c in the ttasim.
Definition at line 122 of file SimpleSimulatorFrontend.cc.
{
    simFront_->prepareToStop(SRE_USER_REQUESTED);
}
References SimulatorFrontend::prepareToStop(), simFront_, and SRE_USER_REQUESTED.
unregisterEventListener()
bool SimpleSimulatorFrontend::unregisterEventListener (int event, Listener * listener) virtual
Definition at line 206 of file SimpleSimulatorFrontend.cc.
{
    return simFront_->eventHandler().unregisterListener(event, listener);
}
References SimulatorFrontend::eventHandler(), simFront_, and Informer::unregisterListener().
Member Data Documentation
simFront_
SimulatorFrontend* SimpleSimulatorFrontend::simFront_ private
Definition at line 99 of file SimpleSimulatorFrontend.hh.
Referenced by cycleCount(), frontend(), hadRuntimeError(), initializeDataMemories(), isFinished(), isInitialized(), isRunning(), isStopped(), loadProgram(), machine(), memorySystem(), program(), registerEventListener(), run(), setOperationSimulator(), SimpleSimulatorFrontend(), SimpleSimulatorFrontend(), SimpleSimulatorFrontend(), step(), stop(), unregisterEventListener(), and ~SimpleSimulatorFrontend().
The documentation for this class was generated from the following files:
SimpleSimulatorFrontend.hh
SimpleSimulatorFrontend.cc