OpenASIP: GrowMachine Class Reference
GrowMachine Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Adds resources until cycle count doesn't go down anymore.")
GrowMachine ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual std::vector< RowID > explore (const RowID &configurationID, const unsigned int &)
void readParameters ()
bool checkSuperiority (const ClockCycleCount &newCC, const ClockCycleCount &oldCC) const
double calculateImprovement (const ClockCycleCount &newCC, const ClockCycleCount &oldCC) const
Private Attributes
unsigned int superiority_
Percentage value of how much faster schedules are wanted until cycle count optimization is stopped.
Static Private Attributes
static const std::string superiorityPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual bool requiresApplication () const
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that adds resources until cycle count doesn't go down anymore.
Supported parameters:
Definition at line 61 of file GrowMachine.cc.
Constructor & Destructor Documentation
GrowMachine()
GrowMachine::GrowMachine () inline private
Definition at line 64 of file GrowMachine.cc.
                 : DesignSpaceExplorerPlugin(),
        superiority_(10) {
        // compulsory parameters
        // no compulsory parameters
        // parameters that have a default value
        addParameter(superiorityPN_, UINT, false,
                Conversion::toString(superiority_));
    }
References DesignSpaceExplorerPlugin::addParameter(), superiority_, superiorityPN_, Conversion::toString(), and UINT.
Member Function Documentation
calculateImprovement()
double GrowMachine::calculateImprovement (const ClockCycleCount & newCC, const ClockCycleCount & oldCC) const inline private
Calculates the percentage of improvement in cycle count
Parameters
newCC The new minimum cycle count.
oldCC The old minimum cycle count.
Definition at line 300 of file GrowMachine.cc.
{
        return (1.0 -(static_cast<double>(newCC)/oldCC))*100.0;
    }
Referenced by explore().
checkSuperiority()
bool GrowMachine::checkSuperiority (const ClockCycleCount & newCC, const ClockCycleCount & oldCC) const inline private
Checks whether cycle counts have been lowered enough.
Parameters
newCC The new minimum cycle count.
oldCC The old minimum cycle count.
Definition at line 282 of file GrowMachine.cc.
{
        if ((newCC < oldCC) &&
                (((static_cast<double>(superiority_) / 100) * oldCC) <
                 (oldCC - newCC))) {
            return true;
        }
        return false;
    }
References superiority_.
Referenced by explore().
explore()
virtual std::vector< RowID > GrowMachine::explore (const RowID & configurationID, const unsigned int &) inline private virtual
Optimizes the architecture in regards of the cycle count.
Optimizes the architecture by growing it until cycle count doesn't go down anymore.
@TODO: average cycle count lowering, or lowest/largest lowering percentage among apps now it's largest lowering among apps. @TODO: parametrize machine growing, example how many buses to add each step.
Returns
Configurations (including only adf) generated by CycleOptimizer. Best result is at the top of the list.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 95 of file GrowMachine.cc.
{
        std::vector<RowID> result;
        readParameters();
        TTAMachine::Machine* adf = NULL;
        DSDBManager::MachineConfiguration configuration;
        DSDBManager& dsdb = db();
        // get the architecture from the database
        try {
            configuration = dsdb.configuration(configurationID);
            adf = dsdb.architecture(configuration.architectureID);
        } catch (const KeyNotFound& e) {
            debugLog(std::string("Fetching architecture from DSDB failed in "
                     "GrowMachine. ")
                     + e.errorMessage() + std::string(" ")
                     + e.errorMessageStack());
            result.push_back(configurationID);
            delete adf;
            return result;
        }
        // evaluate to get current cycle counts
        DesignSpaceExplorer explorer;
        explorer.setDSDB(dsdb);
        CostEstimates estimates;
        DSDBManager::MachineConfiguration startConf;
        startConf.architectureID = dsdb.addArchitecture(*adf);
        startConf.hasImplementation = false;
        try {
            bool estimate = false;
            if (!explorer.evaluate(startConf, estimates, estimate)) {
                debugLog(std::string("Evaluate failed in GrowMachine."));
                result.push_back(configurationID);
                delete adf;
                adf = NULL;
                return result;
            }
        } catch (const Exception& e) {
            debugLog(std::string("Error in GrowMachine: ")
                    + e.errorMessage() + std::string(" ")
                    + e.errorMessageStack());
            result.push_back(configurationID);
            delete adf;
            adf = NULL;
            return result;
        }
        std::vector<ClockCycleCount> cycleCounts =
            db().cycleCounts(startConf);
        if (cycleCounts.size() < 1) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "GrowMachine error: Couldn't evaluate cycle "
                << "counts for applications, correct_simulation_output"
                << " probably missing." << std::endl;
            verboseLog(msg.str());
            result.push_back(configurationID);
            delete adf;
            adf = NULL;
            return result;
        }
        // all applications minimum cycle count
        ClockCycleCount currentMinCycles = cycleCounts.at(0);
        for (int i = 1; i < (int)cycleCounts.size(); i++) {
            if (cycleCounts.at(i) < currentMinCycles) {
                currentMinCycles = cycleCounts.at(i);
            }
        }
        ClockCycleCount prevMinCycles = 0;
        MachineResourceModifier modifier;
        std::map<ClockCycleCount, RowID> resultMap;
        do {
            prevMinCycles = currentMinCycles;
            try {
                // These parameters passed to the modifier can be changed.
                // They tell how many units of same type are added each time.
                modifier.addBusesByAmount(8, *adf);
                modifier.increaseAllRFsThatDiffersByAmount(1, *adf);
                modifier.increaseAllFUsThatDiffersByAmount(1, *adf);
                // @TODO immediate unit addition
                DSDBManager::MachineConfiguration newConfiguration;
                try {
                    newConfiguration.architectureID = dsdb.addArchitecture(*adf);
                } catch (const RelationalDBException& e) {
                    // Error occurred while adding adf to the dsdb, adf
                    // probably too big
                    break;
                }
                newConfiguration.hasImplementation = false;
                RowID confID = dsdb.addConfiguration(newConfiguration);
                CostEstimates newEstimates;
                // evaluate to get new cycle counts
                if (explorer.evaluate(newConfiguration, newEstimates, false)) {
                    // resets the currentMinCycles
                    std::vector<ClockCycleCount> newCycleCounts =
                        db().cycleCounts(newConfiguration);
                    currentMinCycles = newCycleCounts.at(0);
                    for (int i = 1; i < (int)newCycleCounts.size(); i++) {
                        if (newCycleCounts.at(i) < currentMinCycles) {
                            currentMinCycles = newCycleCounts.at(i);
                        }
                    }
                    if (Application::verboseLevel() > 0) {
                        std::ostringstream msg(std::ostringstream::out);
                        msg << "GrowMachine produced config: "
                            << confID << ", with cycle count: "
                            << currentMinCycles << " ("
                            << calculateImprovement(currentMinCycles,
                                    prevMinCycles)
                            << "% better)";
                        verboseLog(msg.str())
                    }
                    if (checkSuperiority(currentMinCycles, prevMinCycles)) {
                        // only add config if it meets the superiority
                        // requirements regarding clock cycles
                        resultMap[currentMinCycles] = confID;
                    } else {
                        break;
                    }
                } else {
                    // evaluating failed
                    debugLog("GrowMachine: Evaluating config with id: "
                            + Conversion::toString(confID)
                            + " failed. This is probably a bug.");
                    break;
                }
            } catch (const Exception& e) {
                debugLog(std::string("Error in GrowMachine: ")
                        + e.errorMessage() + std::string(" ")
                        + e.errorMessageStack());
                result.push_back(configurationID);
                delete adf;
                adf = NULL;
                return result;
            }
        } while (true);
        std::map<ClockCycleCount, RowID>::const_iterator mapIter =
            resultMap.begin();
        for (; mapIter != resultMap.end(); mapIter++) {
            result.push_back((*mapIter).second);
        }
        if (result.empty()) {
            // if now new configuration created return the old
            verboseLogC("GrowMachine could not generate new configs.", 2)
            result.push_back(configurationID);
        }
        delete adf;
        adf = NULL;
        return result;
    }
References DSDBManager::addArchitecture(), MachineResourceModifier::addBusesByAmount(), DSDBManager::addConfiguration(), DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, calculateImprovement(), checkSuperiority(), DSDBManager::configuration(), DSDBManager::cycleCounts(), DesignSpaceExplorer::db(), debugLog, Exception::errorMessage(), Exception::errorMessageStack(), DesignSpaceExplorer::evaluate(), DSDBManager::MachineConfiguration::hasImplementation, MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), readParameters(), DesignSpaceExplorer::setDSDB(), Conversion::toString(), Application::verboseLevel(), verboseLog, and verboseLogC.
PLUGIN_DESCRIPTION()
GrowMachine::PLUGIN_DESCRIPTION ("Adds resources until cycle count doesn't go down anymore.") private
producesArchitecture()
virtual bool GrowMachine::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 76 of file GrowMachine.cc.
{ return true; }
readParameters()
void GrowMachine::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 270 of file GrowMachine.cc.
{
        // optional parameters
        readOptionalParameter(superiorityPN_, superiority_);
    }
References DesignSpaceExplorerPlugin::readOptionalParameter(), superiority_, and superiorityPN_.
Referenced by explore().
requiresHDB()
virtual bool GrowMachine::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 77 of file GrowMachine.cc.
{ return true; }
requiresSimulationData()
virtual bool GrowMachine::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 78 of file GrowMachine.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool GrowMachine::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 75 of file GrowMachine.cc.
{ return true; }
Member Data Documentation
superiority_
unsigned int GrowMachine::superiority_ private
Percentage value of how much faster schedules are wanted until cycle count optimization is stopped.
Definition at line 265 of file GrowMachine.cc.
Referenced by checkSuperiority(), GrowMachine(), and readParameters().
superiorityPN_
const std::string GrowMachine::superiorityPN_ static private
Definition at line 260 of file GrowMachine.cc.
Referenced by GrowMachine(), and readParameters().
The documentation for this class was generated from the following file:
GrowMachine.cc