OpenASIP: FUPortDialog Class Reference
FUPortDialog Class Reference
#include <FUPortDialog.hh>
Public Member Functions
FUPortDialog (wxWindow *parent, TTAMachine::FUPort *port)
~FUPortDialog ()
Protected Member Functions
virtual bool TransferDataToWindow ()
Private Types
enum {
ID_NAME =10000 , ID_WIDTH , ID_INPUT_SOCKET , ID_OUTPUT_SOCKET ,
ID_TRIGGERS , ID_HELP , ID_LABEL_NAME , ID_LABEL_WIDTH ,
ID_LABEL_INPUT_SOCKET , ID_LABEL_OUTPUT_SOCKET , ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void updateSockets ()
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
void onSocketChoice (wxCommandEvent &event)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &event)
void setTexts ()
Private Attributes
TTAMachine::FUPort * port_
Function unit port to modify.
wxString name_
Name of the port.
int width_
Width of the port.
bool triggers_
Trigger attribute of the port.
wxChoice * inputSocketChoice_
Input socket choice control.
wxChoice * outputSocketChoice_
Output socket choice control.
TTAMachine::Socket * oldInput_
Original input socket of the port.
TTAMachine::Socket * oldOutput_
Original output socket of the port.
Detailed Description
Dialog for querying port parameters from the user.
Definition at line 44 of file FUPortDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NAME
ID_WIDTH
ID_INPUT_SOCKET
ID_OUTPUT_SOCKET
ID_TRIGGERS
ID_HELP
ID_LABEL_NAME
ID_LABEL_WIDTH
ID_LABEL_INPUT_SOCKET
ID_LABEL_OUTPUT_SOCKET
ID_LINE
Definition at line 81 of file FUPortDialog.hh.
         {
        ID_NAME=10000,
        ID_WIDTH,
        ID_INPUT_SOCKET,
        ID_OUTPUT_SOCKET,
        ID_TRIGGERS,
        ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_WIDTH,
        ID_LABEL_INPUT_SOCKET,
        ID_LABEL_OUTPUT_SOCKET,
        ID_LINE
    };
Constructor & Destructor Documentation
FUPortDialog()
FUPortDialog::FUPortDialog (wxWindow * parent, TTAMachine::FUPort * port)
The Constructor.
Parameters
parent Parent window of the dialog.
port Port to modify.
Definition at line 76 of file FUPortDialog.cc.
                 :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    port_(port),
    name_(_T("")),
    width_(ModelConstants::DEFAULT_WIDTH),
    triggers_(false),
    inputSocketChoice_(NULL),
    outputSocketChoice_(NULL) {
    oldInput_ = port_->inputSocket();
    oldOutput_ = port_->outputSocket();
    createContents(this, true, true);
    inputSocketChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_INPUT_SOCKET));
    outputSocketChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_OUTPUT_SOCKET));
    FindWindow(ID_NAME)->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    FindWindow(ID_TRIGGERS)->SetValidator(wxGenericValidator(&triggers_));
    FindWindow(ID_WIDTH)->SetValidator(wxGenericValidator(&width_));
    FindWindow(wxID_OK)->Disable();
    // set texts to widgets
    setTexts();
    TransferDataToWindow();
}
~FUPortDialog()
FUPortDialog::~FUPortDialog ()
The Destructor.
Definition at line 109 of file FUPortDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * FUPortDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window. Initially generated with wxDesigner, the code will be cleaned up later.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 377 of file FUPortDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_WIDTH, wxT("Width:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxSpinCtrl *item5 = new wxSpinCtrl( parent, ID_WIDTH, wxT("1"), wxDefaultPosition, wxSize(-1,-1), 0, 1, 10000, 1 );
    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_LABEL_INPUT_SOCKET, wxT("Input Socket:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString strs7[] =
    {
        wxT("NONE")
    };
    wxChoice *item7 = new wxChoice( parent, ID_INPUT_SOCKET, wxDefaultPosition, wxSize(200,-1), 1, strs7, 0 );
    item1->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item8 = new wxStaticText( parent, ID_LABEL_OUTPUT_SOCKET, wxT("Output Socket:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item8, 0, wxALIGN_RIGHT|wxALL, 5 );
    wxString strs9[] =
    {
        wxT("NONE")
    };
    wxChoice *item9 = new wxChoice( parent, ID_OUTPUT_SOCKET, wxDefaultPosition, wxSize(200,-1), 1, strs9, 0 );
    item1->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );
    wxCheckBox *item11 = new wxCheckBox( parent, ID_TRIGGERS, wxT("Triggers"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item10, 0, wxALL, 5 );
    wxStaticLine *item12 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL );
    item0->Add( item12, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item14 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item15 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item16 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_HELP, ID_INPUT_SOCKET, ID_LABEL_INPUT_SOCKET, ID_LABEL_NAME, ID_LABEL_OUTPUT_SOCKET, ID_LABEL_WIDTH, ID_LINE, ID_NAME, ID_OUTPUT_SOCKET, ID_TRIGGERS, and ID_WIDTH.
onCancel()
void FUPortDialog::onCancel (wxCommandEvent & event) private
Resets the original input and output sockets for the port and closes the dialog.
Definition at line 249 of file FUPortDialog.cc.
{
    port_->detachAllSockets();
    if (oldInput_ != NULL) {
        port_->attachSocket(*oldInput_);
    }
    if (oldOutput_ != NULL) {
        port_->attachSocket(*oldOutput_);
    }
    EndModal(wxID_CANCEL);
}
References TTAMachine::Port::attachSocket(), TTAMachine::Port::detachAllSockets(), oldInput_, oldOutput_, and port_.
onHelp()
void FUPortDialog::onHelp (wxCommandEvent & event) private
onName()
void FUPortDialog::onName (wxCommandEvent & event) private
Disables OK-button if the name field is empty.
Definition at line 354 of file FUPortDialog.cc.
{
    if (!TransferDataFromWindow()) {
        assert(false);
    }
    wxString trimmedName = name_.Trim(false).Trim(true);
    if (trimmedName == _T("")) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References assert, and name_.
onOK()
void FUPortDialog::onOK (wxCommandEvent & event) private
Validates input in the controls, and updates the port object.
Definition at line 265 of file FUPortDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    // check whether FU already has a port of tht name.
    string trimmedName =
        WxConversion::toString(name_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName)) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    if (port_->name() != trimmedName) {
        FunctionUnit* fu = port_->parentUnit();
        for (int i = 0; i < fu->portCount(); i++) {
            string name = fu->port(i)->name();
            if (name == WxConversion::toString(name_)) {
                ProDeTextGenerator* prodeTexts =
                    ProDeTextGenerator::instance();
                format message =
                    prodeTexts->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
                format a_port =
                    prodeTexts->text(ProDeTextGenerator::COMP_A_PORT);
                format machine =
                    prodeTexts->text(ProDeTextGenerator::COMP_FUNCTION_UNIT);
                format port =
                    prodeTexts->text(ProDeTextGenerator::COMP_PORT);
                message % trimmedName % a_port.str() % machine.str() %
                    port.str();
                WarningDialog warning(
                    this, WxConversion::toWxString(message.str()));
                warning.ShowModal();
                return;
            }
        }
    }
    // update attributes
    port_->setName(trimmedName);
    port_->setTriggering(triggers_);
    port_->setWidth(width_);
    EndModal(wxID_OK);
}
References ProDeTextGenerator::COMP_A_PORT, ProDeTextGenerator::COMP_FUNCTION_UNIT, ProDeTextGenerator::COMP_PORT, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), machine, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, TTAMachine::Port::name(), name_, TTAMachine::BaseFUPort::parentUnit(), TTAMachine::FunctionUnit::port(), port_, TTAMachine::Unit::portCount(), TTAMachine::Port::setName(), TTAMachine::FUPort::setTriggering(), TTAMachine::BaseFUPort::setWidth(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), triggers_, and width_.
onSocketChoice()
void FUPortDialog::onSocketChoice (wxCommandEvent & event) private
Updates the port object when user changes input/output socket selection.
Definition at line 328 of file FUPortDialog.cc.
{
    port_->detachAllSockets();
    Machine::SocketNavigator navigator =
        port_->parentUnit()->machine()->socketNavigator();
    // set input socket
    string inputSocketName =
        WxConversion::toString(inputSocketChoice_->GetStringSelection());
    if (inputSocketName != WxConversion::toString(ProDeConstants::NONE)) {
        port_->attachSocket(*(navigator.item(inputSocketName)));
    }
    // set output socket
    string outputSocketName =
        WxConversion::toString(outputSocketChoice_->GetStringSelection());
    if (outputSocketName != WxConversion::toString(ProDeConstants::NONE)) {
        port_->attachSocket(*(navigator.item(outputSocketName)));
    }
    updateSockets();
}
References TTAMachine::Port::attachSocket(), TTAMachine::Port::detachAllSockets(), inputSocketChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), ProDeConstants::NONE, outputSocketChoice_, TTAMachine::BaseFUPort::parentUnit(), port_, TTAMachine::Machine::socketNavigator(), WxConversion::toString(), and updateSockets().
setTexts()
void FUPortDialog::setTexts () private
Sets texts for widgets.
Definition at line 117 of file FUPortDialog.cc.
                       {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_FU_PORT_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_WIDTH),
                          ProDeTextGenerator::TXT_LABEL_WIDTH);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_INPUT_SOCKET),
                          ProDeTextGenerator::TXT_LABEL_INPUT_SOCKET);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_OUTPUT_SOCKET),
                          ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_TRIGGERS),
                          ProDeTextGenerator::TXT_LABEL_TRIGGERS);
}
References ID_HELP, ID_LABEL_INPUT_SOCKET, ID_LABEL_NAME, ID_LABEL_OUTPUT_SOCKET, ID_LABEL_WIDTH, ID_TRIGGERS, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_FU_PORT_DIALOG_TITLE, ProDeTextGenerator::TXT_LABEL_INPUT_SOCKET, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_OUTPUT_SOCKET, ProDeTextGenerator::TXT_LABEL_TRIGGERS, and ProDeTextGenerator::TXT_LABEL_WIDTH.
TransferDataToWindow()
bool FUPortDialog::TransferDataToWindow () protected virtual
Transfers data from the port object to the dialog widgets.
Returns
False, if an error occured in the transfer.
Definition at line 160 of file FUPortDialog.cc.
{
    name_ = WxConversion::toWxString(port_->name());
    width_ = port_->width();
    triggers_ = port_->isTriggering();
    updateSockets();
    // wxWidgets GTK1 version seems to bug with spincontrol and
    // checkbox validators. The widget value has to be set manually.
    dynamic_cast<wxSpinCtrl*>(FindWindow(ID_WIDTH))->SetValue(width_);
    dynamic_cast<wxCheckBox*>(FindWindow(ID_TRIGGERS))->SetValue(triggers_);
    return wxWindow::TransferDataToWindow();
}
References ID_TRIGGERS, ID_WIDTH, TTAMachine::FUPort::isTriggering(), TTAMachine::Port::name(), name_, port_, WxConversion::toWxString(), triggers_, updateSockets(), TTAMachine::BaseFUPort::width(), and width_.
updateSockets()
void FUPortDialog::updateSockets () private
Updates input and output socket choicers.
Definition at line 179 of file FUPortDialog.cc.
{
    inputSocketChoice_->Clear();
    inputSocketChoice_->Append(ProDeConstants::NONE);
    outputSocketChoice_->Clear();
    outputSocketChoice_->Append(ProDeConstants::NONE);
    MachineTester tester(*(port_->parentUnit()->machine()));
    // Add ports to the choicers
    Machine::SocketNavigator navigator =
        port_->parentUnit()->machine()->socketNavigator();
    for (int i = 0; i < navigator.count(); i++) {
        Socket* socket = navigator.item(i);
        wxString socketName = WxConversion::toWxString(socket->name());
        // Add available input sockets.
        Socket* input = port_->inputSocket();
        if (input != NULL) {
            port_->detachSocket(*input);
        }
        bool legal = tester.canConnect(*socket, *port_);
        if (legal && socket->direction() == Socket::INPUT) {
            inputSocketChoice_->Append(socketName);
        }
        if (input != NULL) {
            port_->attachSocket(*input);
        }
        // Add available output sockets.
        Socket* output = port_->outputSocket();
        if (output != NULL) {
            port_->detachSocket(*output);
        }
        legal = tester.canConnect(*socket, *port_);
        if (legal && socket->direction() == Socket::OUTPUT) {
            outputSocketChoice_->Append(socketName);
        }
        if (output != NULL) {
            port_->attachSocket(*output);
        }
        // ignore sockets with unknown direction
    }
    // set input socket choice
    if (port_->inputSocket() == NULL) {
        inputSocketChoice_->SetStringSelection(ProDeConstants::NONE);
    } else {
        wxString socketName =
            WxConversion::toWxString(port_->inputSocket()->name());
        inputSocketChoice_->SetStringSelection(socketName);
    }
    // set output socket choice
    if (port_->outputSocket() == NULL) {
        outputSocketChoice_->SetStringSelection(ProDeConstants::NONE);
    } else {
        wxString socketName =
            WxConversion::toWxString(port_->outputSocket()->name());
        outputSocketChoice_->SetStringSelection(socketName);
    }
}
References TTAMachine::Port::attachSocket(), MachineTester::canConnect(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Port::detachSocket(), TTAMachine::Socket::direction(), TTAMachine::Socket::INPUT, TTAMachine::Port::inputSocket(), inputSocketChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ProDeConstants::NONE, TTAMachine::Socket::OUTPUT, TTAMachine::Port::outputSocket(), outputSocketChoice_, TTAMachine::BaseFUPort::parentUnit(), port_, TTAMachine::Machine::socketNavigator(), and WxConversion::toWxString().
Referenced by onSocketChoice(), and TransferDataToWindow().
Member Data Documentation
inputSocketChoice_
wxChoice* FUPortDialog::inputSocketChoice_ private
Input socket choice control.
Definition at line 72 of file FUPortDialog.hh.
Referenced by onSocketChoice(), and updateSockets().
name_
wxString FUPortDialog::name_ private
Name of the port.
Definition at line 66 of file FUPortDialog.hh.
Referenced by onName(), onOK(), and TransferDataToWindow().
oldInput_
TTAMachine::Socket* FUPortDialog::oldInput_ private
Original input socket of the port.
Definition at line 77 of file FUPortDialog.hh.
Referenced by onCancel().
oldOutput_
TTAMachine::Socket* FUPortDialog::oldOutput_ private
Original output socket of the port.
Definition at line 79 of file FUPortDialog.hh.
Referenced by onCancel().
outputSocketChoice_
wxChoice* FUPortDialog::outputSocketChoice_ private
Output socket choice control.
Definition at line 74 of file FUPortDialog.hh.
Referenced by onSocketChoice(), and updateSockets().
port_
TTAMachine::FUPort* FUPortDialog::port_ private
Function unit port to modify.
Definition at line 64 of file FUPortDialog.hh.
Referenced by onCancel(), onOK(), onSocketChoice(), TransferDataToWindow(), and updateSockets().
triggers_
bool FUPortDialog::triggers_ private
Trigger attribute of the port.
Definition at line 70 of file FUPortDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
width_
int FUPortDialog::width_ private
Width of the port.
Definition at line 68 of file FUPortDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
FUPortDialog.hh
FUPortDialog.cc