OpenASIP: AddWatchDialog Class Reference
AddWatchDialog Class Reference
#include <AddWatchDialog.hh>
Public Member Functions
AddWatchDialog (wxWindow *parent, wxWindowID id, Watch *watch=NULL)
virtual ~AddWatchDialog ()
Private Types
enum {
ID_RB_MEMORY , ID_RB_PORT , ID_RB_REGISTER , ID_RB_EXPRESSION ,
ID_RB_BUS , ID_LABEL_AS , ID_LABEL_UNIT , ID_LABEL_PORT ,
ID_LABEL_RF , ID_LABEL_BUS , ID_LABEL_EXPRESSION , ID_LABEL_CONDITION ,
ID_LABEL_START_ADDRESS , ID_LABEL_END_ADDRESS , ID_LABEL_INDEX , ID_START_ADDRESS ,
ID_END_ADDRESS , ID_BUS_CHOICE , ID_RF_CHOICE , ID_FU_CHOICE ,
ID_PORT_CHOICE , ID_INDEX_CHOICE , ID_EXPRESSION , ID_ADDRESS_SPACE ,
ID_LINE
}
Widget ids.
Private Member Functions
void onWatchTypeChange (wxCommandEvent &event)
void onFUChoice (wxCommandEvent &event)
void onRFChoice (wxCommandEvent &event)
void onASChoice (wxCommandEvent &event)
void initialize ()
void onOK (wxCommandEvent &event)
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Private Attributes
wxChoice * asChoice_
Address space choicer for memory watch.
wxChoice * fuChoice_
Function unit choicer for port watch.
wxChoice * portChoice_
Port choicer for port watch.
wxChoice * rfChoice_
Register file choicer for register watch.
wxChoice * indexChoice_
Register index choicer for register watch.
wxChoice * busChoice_
Bus choicer for bus watch.
wxSpinCtrl * endAddressCtrl_
End adderss widget for memory watch.
wxSpinCtrl * startAddressCtrl_
Start address widget for memory watch.
Detailed Description
Dialog for creating watch points.
Definition at line 43 of file AddWatchDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget ids.
Enumerator
ID_RB_MEMORY
ID_RB_PORT
ID_RB_REGISTER
ID_RB_EXPRESSION
ID_RB_BUS
ID_LABEL_AS
ID_LABEL_UNIT
ID_LABEL_PORT
ID_LABEL_RF
ID_LABEL_BUS
ID_LABEL_EXPRESSION
ID_LABEL_CONDITION
ID_LABEL_START_ADDRESS
ID_LABEL_END_ADDRESS
ID_LABEL_INDEX
ID_START_ADDRESS
ID_END_ADDRESS
ID_BUS_CHOICE
ID_RF_CHOICE
ID_FU_CHOICE
ID_PORT_CHOICE
ID_INDEX_CHOICE
ID_EXPRESSION
ID_ADDRESS_SPACE
ID_LINE
Definition at line 57 of file AddWatchDialog.hh.
         {
        ID_RB_MEMORY,
        ID_RB_PORT,
        ID_RB_REGISTER,
        ID_RB_EXPRESSION,
        ID_RB_BUS,
        ID_LABEL_AS,
        ID_LABEL_UNIT,
        ID_LABEL_PORT,
        ID_LABEL_RF,
        ID_LABEL_BUS,
        ID_LABEL_EXPRESSION,
        ID_LABEL_CONDITION,
        ID_LABEL_START_ADDRESS,
        ID_LABEL_END_ADDRESS,
        ID_LABEL_INDEX,
        ID_START_ADDRESS,
        ID_END_ADDRESS,
        ID_BUS_CHOICE,
        ID_RF_CHOICE,
        ID_FU_CHOICE,
        ID_PORT_CHOICE,
        ID_INDEX_CHOICE,
        ID_EXPRESSION,
        ID_ADDRESS_SPACE,
        ID_LINE
    };
Constructor & Destructor Documentation
AddWatchDialog()
AddWatchDialog::AddWatchDialog (wxWindow * parent, wxWindowID id, Watch * watch = NULL)
The Constructor.
Parameters
parent Parent window of the dialog.
id Dialog identifier.
watch Watch point to edit, or NULL to create a new watch point.
Definition at line 79 of file AddWatchDialog.cc.
                                               :
  wxDialog(parent, id, _T("Watch point"), wxDefaultPosition) {
    createContents(this, true, true);
    // Initialize widget pointers.
    asChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_ADDRESS_SPACE));
    rfChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_RF_CHOICE));
    indexChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_INDEX_CHOICE));
    fuChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_FU_CHOICE));
    portChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_PORT_CHOICE));
    busChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_BUS_CHOICE));
    endAddressCtrl_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_END_ADDRESS));
    startAddressCtrl_ =
        dynamic_cast<wxSpinCtrl*>(FindWindow(ID_START_ADDRESS));
    initialize();
}
~AddWatchDialog()
AddWatchDialog::~AddWatchDialog () virtual
The Destructor.
Definition at line 104 of file AddWatchDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * AddWatchDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Code generated by wxDesigner. Do not modify manually.
Parameters
parent Parent window for the dialog widgets.
call_fit If true, the dialog is resized to fit the widgets.
set_sizer If true, the created widgets are set as the dialog contents.
Definition at line 415 of file AddWatchDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );
    wxRadioButton *item3 = new wxRadioButton( parent, ID_RB_PORT, wxT("Port watch"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALL, 5 );
    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );
    item4->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_UNIT, wxT("Unit:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs6 = (wxString*) NULL;
    wxChoice *item6 = new wxChoice( parent, ID_FU_CHOICE, wxDefaultPosition, wxSize(100,-1), 0, strs6, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_PORT, wxT("Port:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs8 = (wxString*) NULL;
    wxChoice *item8 = new wxChoice( parent, ID_PORT_CHOICE, wxDefaultPosition, wxSize(100,-1), 0, strs8, 0 );
    item4->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxALL, 5 );
    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );
    wxRadioButton *item10 = new wxRadioButton( parent, ID_RB_REGISTER, wxT("Register watch"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALL, 5 );
    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );
    item11->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item12 = new wxStaticText( parent, ID_LABEL_RF, wxT("Register file:"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs13 = (wxString*) NULL;
    wxChoice *item13 = new wxChoice( parent, ID_RF_CHOICE, wxDefaultPosition, wxSize(100,-1), 0, strs13, 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item14 = new wxStaticText( parent, ID_LABEL_INDEX, wxT("Index:"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs15 = (wxString*) NULL;
    wxChoice *item15 = new wxChoice( parent, ID_INDEX_CHOICE, wxDefaultPosition, wxSize(100,-1), 0, strs15, 0 );
    item11->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item9, 0, wxALL, 5 );
    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );
    wxRadioButton *item17 = new wxRadioButton( parent, ID_RB_BUS, wxT("Bus watch"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALL, 5 );
    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );
    item18->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item19 = new wxStaticText( parent, ID_LABEL_BUS, wxT("Bus:"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs20 = (wxString*) NULL;
    wxChoice *item20 = new wxChoice( parent, ID_BUS_CHOICE, wxDefaultPosition, wxSize(100,-1), 0, strs20, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item16, 0, wxALL, 5 );
    wxBoxSizer *item21 = new wxBoxSizer( wxVERTICAL );
    wxRadioButton *item22 = new wxRadioButton( parent, ID_RB_MEMORY, wxT("Memory watch"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALL, 5 );
    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );
    item23->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item24 = new wxStaticText( parent, ID_LABEL_AS, wxT("Address space:"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );
    wxString *strs25 = (wxString*) NULL;
    wxChoice *item25 = new wxChoice( parent, ID_ADDRESS_SPACE, wxDefaultPosition, wxSize(100,-1), 0, strs25, 0 );
    item23->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item26 = new wxStaticText( parent, ID_LABEL_START_ADDRESS, wxT("Start address:"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item27 = new wxSpinCtrl( parent, ID_START_ADDRESS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item23->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item28 = new wxStaticText( parent, ID_LABEL_END_ADDRESS, wxT("End address:"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );
    wxSpinCtrl *item29 = new wxSpinCtrl( parent, ID_END_ADDRESS, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0, 0, 100, 0 );
    item23->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item21, 0, wxALL, 5 );
    wxBoxSizer *item30 = new wxBoxSizer( wxHORIZONTAL );
    wxRadioButton *item31 = new wxRadioButton( parent, ID_RB_EXPRESSION, wxT("Experession:"), wxDefaultPosition, wxDefaultSize, 0 );
    item30->Add( item31, 0, wxALL, 5 );
    wxTextCtrl *item32 = new wxTextCtrl( parent, ID_EXPRESSION, wxT(""), wxDefaultPosition, wxSize(500,-1), 0 );
    item30->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item30, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item33 = new wxBoxSizer( wxVERTICAL );
    wxStaticLine *item34 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item33->Add( item34, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item35 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item36 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item35->Add( item36, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item37 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item35->Add( item37, 0, wxALIGN_CENTER|wxALL, 5 );
    item33->Add( item35, 0, wxALL, 5 );
    item0->Add( item33, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADDRESS_SPACE, ID_BUS_CHOICE, ID_END_ADDRESS, ID_EXPRESSION, ID_FU_CHOICE, ID_INDEX_CHOICE, ID_LABEL_AS, ID_LABEL_BUS, ID_LABEL_END_ADDRESS, ID_LABEL_INDEX, ID_LABEL_PORT, ID_LABEL_RF, ID_LABEL_START_ADDRESS, ID_LABEL_UNIT, ID_LINE, ID_PORT_CHOICE, ID_RB_BUS, ID_RB_EXPRESSION, ID_RB_MEMORY, ID_RB_PORT, ID_RB_REGISTER, ID_RF_CHOICE, and ID_START_ADDRESS.
initialize()
void AddWatchDialog::initialize () private
Initializes the dialog choicer items.
Definition at line 111 of file AddWatchDialog.cc.
{
    Machine machine = ProximToolbox::machine();
    // Address space choicer.
    const Machine::AddressSpaceNavigator asNavigator =
        machine.addressSpaceNavigator();
    for (int i = 0; i < asNavigator.count(); i++) {
        string asName = asNavigator.item(i)->name();
        asChoice_->Append(WxConversion::toWxString(asName));
    }
    // Register file choicer.
    const Machine::RegisterFileNavigator rfNavigator =
        machine.registerFileNavigator();
    for (int i = 0; i < rfNavigator.count(); i++) {
        string rfName = rfNavigator.item(i)->name();
        rfChoice_->Append(WxConversion::toWxString(rfName));
    }
    // Function unit choicer.
    const Machine::FunctionUnitNavigator fuNavigator =
        machine.functionUnitNavigator();
    for (int i = 0; i < fuNavigator.count(); i++) {
        string fuName = fuNavigator.item(i)->name();
        fuChoice_->Append(WxConversion::toWxString(fuName));
    }
    // Bus choicer.
    const Machine::BusNavigator busNavigator = machine.busNavigator();
    for (int i = 0; i < busNavigator.count(); i++) {
        string busName = busNavigator.item(i)->name();
        busChoice_->Append(WxConversion::toWxString(busName));
    }
    wxCommandEvent dummy;
    dummy.SetId(ID_RB_PORT);
    onWatchTypeChange(dummy);
}
References TTAMachine::Machine::addressSpaceNavigator(), asChoice_, busChoice_, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), dummy, fuChoice_, TTAMachine::Machine::functionUnitNavigator(), ID_RB_PORT, TTAMachine::Machine::Navigator< ComponentType >::item(), machine, ProximToolbox::machine(), onWatchTypeChange(), TTAMachine::Machine::registerFileNavigator(), rfChoice_, and WxConversion::toWxString().
onASChoice()
void AddWatchDialog::onASChoice (wxCommandEvent & event) private
Event handler for the address space choicer.
Sets the minimum and maximum start/end address values of the memory watch spin-buttons when the address space selection is changed.
Definition at line 268 of file AddWatchDialog.cc.
{
    string asName =
        WxConversion::toString(asChoice_->GetStringSelection());
    const Machine::AddressSpaceNavigator asNavigator =
        ProximToolbox::machine().addressSpaceNavigator();
    AddressSpace* as = asNavigator.item(asName);
    assert(as != NULL);
    startAddressCtrl_->SetRange(as->start(), as->end());
    endAddressCtrl_->SetRange(as->start(), as->end());
    startAddressCtrl_->SetValue(as->start());
    endAddressCtrl_->SetValue(as->end());
}
References TTAMachine::Machine::addressSpaceNavigator(), asChoice_, assert, TTAMachine::AddressSpace::end(), endAddressCtrl_, TTAMachine::Machine::Navigator< ComponentType >::item(), ProximToolbox::machine(), TTAMachine::AddressSpace::start(), startAddressCtrl_, and WxConversion::toString().
onFUChoice()
void AddWatchDialog::onFUChoice (wxCommandEvent & event) private
Sets the function unit port choicer items when the function unit selection changes.
Definition at line 213 of file AddWatchDialog.cc.
{
    string fuName =
        WxConversion::toString(fuChoice_->GetStringSelection());
    const Machine::FunctionUnitNavigator fuNavigator =
        ProximToolbox::machine().functionUnitNavigator();
    FunctionUnit* fu = fuNavigator.item(fuName);
    assert(fu != NULL);
    // Set the port choicer to contain an item for each of the selected
    // function unit's ports.
    portChoice_->Clear();
    for (int i = 0; i < fu->portCount(); i++) {
        string portName = fu->port(i)->name();
        portChoice_->Append(WxConversion::toWxString(portName));
    }
    portChoice_->SetSelection(0);
}
References assert, fuChoice_, TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), ProximToolbox::machine(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::port(), portChoice_, TTAMachine::Unit::portCount(), WxConversion::toString(), and WxConversion::toWxString().
onOK()
void AddWatchDialog::onOK (wxCommandEvent & event) private
Event handler for the dialog OK-button.
Definition at line 291 of file AddWatchDialog.cc.
{
    string expression;
    // Memory watch.
    if (dynamic_cast<wxRadioButton*>(FindWindow(ID_RB_MEMORY))->GetValue()) {
        string asName =
            WxConversion::toString(asChoice_->GetStringSelection());
        unsigned start = startAddressCtrl_->GetValue();
        unsigned end = endAddressCtrl_->GetValue();
        int count = end - start + 1;
        string startStr = Conversion::toString(start);
        string countStr = Conversion::toString(count);
        if (asName == "") {
            wxString message = _T("Invalid address space.");
            ErrorDialog error(this, message);
            error.ShowModal();
            return;
        }
        if (count < 1) {
            wxString message = _T("The memory watch end address must be\n");
            message.Append(_T("greater than the start address."));
            ErrorDialog error(this, message);
            error.ShowModal();
            return;
        }
        expression = "x " " /a " + asName + " /n " + countStr + " " + startStr;
    }
    // Port Watch.
    if (dynamic_cast<wxRadioButton*>(FindWindow(ID_RB_PORT))->GetValue()) {
        string fuName =
            WxConversion::toString(fuChoice_->GetStringSelection());
        string portName =
            WxConversion::toString(portChoice_->GetStringSelection());
        if (fuName == "" || portName == "") {
            wxString message = _T("Invalid port.");
            ErrorDialog error(this, message);
            error.ShowModal();
            return;
        }
        expression = "info ports " + fuName + " " + portName;
    }
    // Register watch.
    if (dynamic_cast<wxRadioButton*>(FindWindow(ID_RB_REGISTER))->GetValue()) {
        string rfName =
            WxConversion::toString(rfChoice_->GetStringSelection());
        string index = Conversion::toString(indexChoice_->GetSelection());
        if (rfName == "") {
            wxString message = _T("Invalid register.");
            ErrorDialog error(this, message);
            error.ShowModal();
            return;
        }
        expression = "info registers " + rfName + " " + index;
    }
    // Bus watch.
    if (dynamic_cast<wxRadioButton*>(FindWindow(ID_RB_BUS))->GetValue()) {
        string busName =
            WxConversion::toString(busChoice_->GetStringSelection());
        if (busName == "") {
            wxString message = _T("Invalid bus.");
            ErrorDialog error(this, message);
            error.ShowModal();
            return;
        }
        expression = "info segments " + busName;
    }
    // User defined expression watch.
    bool expressionWatch =
        dynamic_cast<wxRadioButton*>(FindWindow(ID_RB_EXPRESSION))->GetValue();
    if (expressionWatch) {
        wxTextCtrl* expressionCtrl =
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_EXPRESSION));
        expression = WxConversion::toString(
            expressionCtrl->GetValue().Trim(true).Trim(false));
    }
    if (expression == "") {
        wxString message = _T("No expression defined for the watch");
        ErrorDialog error(this, message);
        error.ShowModal();
        return;
    }
    // Test expression script.
    if (!ProximToolbox::testExpression(this, expression)) {
        // Invalid expression, error dialog is displayed by the toolbox.
        return;
    }
    ProximLineReader& lineReader = ProximToolbox::lineReader();
    lineReader.input(ProximConstants::SCL_ADD_WATCH);
    lineReader.input(expression);
    EndModal(wxID_OK);
}
References asChoice_, busChoice_, endAddressCtrl_, fuChoice_, ID_EXPRESSION, ID_RB_BUS, ID_RB_EXPRESSION, ID_RB_MEMORY, ID_RB_PORT, ID_RB_REGISTER, indexChoice_, ProximLineReader::input(), ProximToolbox::lineReader(), portChoice_, rfChoice_, ProximConstants::SCL_ADD_WATCH, startAddressCtrl_, ProximToolbox::testExpression(), Conversion::toString(), and WxConversion::toString().
onRFChoice()
void AddWatchDialog::onRFChoice (wxCommandEvent & event) private
Sets the register index choicer items when the register file selection changes.
Definition at line 240 of file AddWatchDialog.cc.
{
    string rfName =
        WxConversion::toString(rfChoice_->GetStringSelection());
    const Machine::RegisterFileNavigator rfNavigator =
        ProximToolbox::machine().registerFileNavigator();
    RegisterFile* rf = rfNavigator.item(rfName);
    assert(rf != NULL);
    // Set the index choicer to contain an item for each of the selected
    // register file's indexes.
    indexChoice_->Clear();
    for (int i = 0; i < rf->numberOfRegisters(); i++) {
        indexChoice_->Append(WxConversion::toWxString(i));
    }
    indexChoice_->SetSelection(0);
}
References assert, indexChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), ProximToolbox::machine(), TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Machine::registerFileNavigator(), rfChoice_, WxConversion::toString(), and WxConversion::toWxString().
onWatchTypeChange()
void AddWatchDialog::onWatchTypeChange (wxCommandEvent & event) private
Disables and enables dialog widgets when the watch type selection changes.
Parameters
event Radio-button event of the watch type changing.
Definition at line 157 of file AddWatchDialog.cc.
{
    // Disable all watch type specific widgets.
    FindWindow(ID_LABEL_AS)->Disable();
    FindWindow(ID_LABEL_UNIT)->Disable();
    FindWindow(ID_LABEL_PORT)->Disable();
    FindWindow(ID_LABEL_RF)->Disable();
    FindWindow(ID_LABEL_BUS)->Disable();
    FindWindow(ID_LABEL_START_ADDRESS)->Disable();
    FindWindow(ID_LABEL_END_ADDRESS)->Disable();
    FindWindow(ID_LABEL_INDEX)->Disable();
    FindWindow(ID_START_ADDRESS)->Disable();
    FindWindow(ID_END_ADDRESS)->Disable();
    FindWindow(ID_BUS_CHOICE)->Disable();
    FindWindow(ID_RF_CHOICE)->Disable();
    FindWindow(ID_FU_CHOICE)->Disable();
    FindWindow(ID_PORT_CHOICE)->Disable();
    FindWindow(ID_INDEX_CHOICE)->Disable();
    FindWindow(ID_EXPRESSION)->Disable();
    FindWindow(ID_ADDRESS_SPACE)->Disable();
    // Enable widgets associated to the selected watch type.
    if (event.GetId() == ID_RB_MEMORY) {
        FindWindow(ID_LABEL_AS)->Enable();
        FindWindow(ID_LABEL_START_ADDRESS)->Enable();
        FindWindow(ID_LABEL_END_ADDRESS)->Enable();
        FindWindow(ID_START_ADDRESS)->Enable();
        FindWindow(ID_END_ADDRESS)->Enable();
    }
    if (event.GetId() == ID_RB_PORT) {
        FindWindow(ID_LABEL_UNIT)->Enable();
        FindWindow(ID_LABEL_PORT)->Enable();
        FindWindow(ID_FU_CHOICE)->Enable();
        FindWindow(ID_PORT_CHOICE)->Enable();
    }
    if (event.GetId() == ID_RB_REGISTER) {
        FindWindow(ID_LABEL_RF)->Enable();
        FindWindow(ID_LABEL_INDEX)->Enable();
        FindWindow(ID_RF_CHOICE)->Enable();
        FindWindow(ID_INDEX_CHOICE)->Enable();
    }
    if (event.GetId() == ID_RB_BUS) {
        FindWindow(ID_LABEL_BUS)->Enable();
        FindWindow(ID_BUS_CHOICE)->Enable();
    }
    if (event.GetId() == ID_RB_EXPRESSION) {
        FindWindow(ID_EXPRESSION)->Enable();
    }
}
References ID_ADDRESS_SPACE, ID_BUS_CHOICE, ID_END_ADDRESS, ID_EXPRESSION, ID_FU_CHOICE, ID_INDEX_CHOICE, ID_LABEL_AS, ID_LABEL_BUS, ID_LABEL_END_ADDRESS, ID_LABEL_INDEX, ID_LABEL_PORT, ID_LABEL_RF, ID_LABEL_START_ADDRESS, ID_LABEL_UNIT, ID_PORT_CHOICE, ID_RB_BUS, ID_RB_EXPRESSION, ID_RB_MEMORY, ID_RB_PORT, ID_RB_REGISTER, ID_RF_CHOICE, and ID_START_ADDRESS.
Referenced by initialize().
Member Data Documentation
asChoice_
wxChoice* AddWatchDialog::asChoice_ private
Address space choicer for memory watch.
Definition at line 88 of file AddWatchDialog.hh.
Referenced by initialize(), onASChoice(), and onOK().
busChoice_
wxChoice* AddWatchDialog::busChoice_ private
Bus choicer for bus watch.
Definition at line 98 of file AddWatchDialog.hh.
Referenced by initialize(), and onOK().
endAddressCtrl_
wxSpinCtrl* AddWatchDialog::endAddressCtrl_ private
End adderss widget for memory watch.
Definition at line 101 of file AddWatchDialog.hh.
Referenced by onASChoice(), and onOK().
fuChoice_
wxChoice* AddWatchDialog::fuChoice_ private
Function unit choicer for port watch.
Definition at line 90 of file AddWatchDialog.hh.
Referenced by initialize(), onFUChoice(), and onOK().
indexChoice_
wxChoice* AddWatchDialog::indexChoice_ private
Register index choicer for register watch.
Definition at line 96 of file AddWatchDialog.hh.
Referenced by onOK(), and onRFChoice().
portChoice_
wxChoice* AddWatchDialog::portChoice_ private
Port choicer for port watch.
Definition at line 92 of file AddWatchDialog.hh.
Referenced by onFUChoice(), and onOK().
rfChoice_
wxChoice* AddWatchDialog::rfChoice_ private
Register file choicer for register watch.
Definition at line 94 of file AddWatchDialog.hh.
Referenced by initialize(), onOK(), and onRFChoice().
startAddressCtrl_
wxSpinCtrl* AddWatchDialog::startAddressCtrl_ private
Start address widget for memory watch.
Definition at line 103 of file AddWatchDialog.hh.
Referenced by onASChoice(), and onOK().
The documentation for this class was generated from the following files:
AddWatchDialog.hh
AddWatchDialog.cc