OpenASIP: TTAMachine::Socket Class Reference
TTAMachine::Socket Class Reference
#include <Socket.hh>
Public Types
enum Direction { INPUT , OUTPUT , UNKNOWN }
Public Member Functions
Socket (const std::string &name)
Socket (const ObjectState *state)
virtual ~Socket ()
virtual void setName (const std::string &name)
void setDirection (Direction direction)
Direction direction () const
void attachBus (Segment &bus)
void detachBus (Segment &bus)
void detachBus (Bus &bus)
int portCount () const
Port * port (int index) const
void detachAllPorts ()
const Connection & connection (const Segment &bus) const
bool isConnectedTo (const Bus &bus) const
bool isConnectedTo (const Segment &bus) const
std::set< Bus * > connectedBuses ()
const std::set< Bus * > connectedBuses () const
int segmentCount () const
Segment * segment (int index) const
bool hasDataPortWidth () const
const std::string & dataPortWidth () const
void setDataPortWidth (const std::string &width)
virtual void setMachine (Machine &mach)
virtual void unsetMachine ()
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
virtual TCEString name () const
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_SOCKET = "socket"
ObjectState name for socket.
static const std::string OSKEY_DIRECTION = "direction"
ObjectState attribute key for socket direction.
static const std::string OSVALUE_INPUT = "input"
ObjectState attribute value for input direction.
static const std::string OSVALUE_OUTPUT = "output"
ObjectState attribute value for output direction.
static const std::string OSVALUE_UNKNOWN = "unknown"
ObjectState attribute value for unknown direction.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Private Types
typedef std::vector< const Connection * > ConnectionTable
Table of Connection pointers.
typedef std::vector< Port * > PortTable
Table of port connections.
Private Member Functions
Socket (const Socket &)
Copying forbidden.
Socket & operator= (const Socket &)
Assingment forbidden.
void removeConnection (const Connection *connection)
void attachPort (Port &port)
void detachPort (const Port &port)
void detachAllBuses ()
Private Attributes
Direction direction_
Direction of the socket.
std::string dataPortWidth_
Dataport width.
ConnectionTable busses_
Contains all connections to busses.
PortTable ports_
Contains all connections to ports.
Friends
class Port
Additional Inherited Members
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents a socket in the TTA processor.
Definition at line 53 of file Socket.hh.
Member Typedef Documentation
ConnectionTable
typedef std::vector<const Connection*> TTAMachine::Socket::ConnectionTable private
Table of Connection pointers.
Definition at line 112 of file Socket.hh.
PortTable
typedef std::vector<Port*> TTAMachine::Socket::PortTable private
Table of port connections.
Definition at line 114 of file Socket.hh.
Member Enumeration Documentation
Direction
enum TTAMachine::Socket::Direction
Direction of data movements in socket.
Enumerator
INPUT
Data goes from bus to port.
OUTPUT
Data goes from port to bus.
UNKNOWN
Unknown direction.
Definition at line 58 of file Socket.hh.
                   {
        INPUT,  ///< Data goes from bus to port.
        OUTPUT, ///< Data goes from port to bus.
        UNKNOWN ///< Unknown direction.
    };
Constructor & Destructor Documentation
Socket() [1/3]
TTAMachine::Socket::Socket (const std::string & name)
Constructor.
Parameters
name Name of the socket.
Exceptions
InvalidName If the given name is not valid for a component.
Definition at line 69 of file Socket.cc.
    : Component(name), direction_(UNKNOWN), dataPortWidth_() {}
Socket() [2/3]
TTAMachine::Socket::Socket (const ObjectState * state)
Constructor.
Loads the state of the socket from the given ObjectState instance but does not create connections to other components.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Definition at line 82 of file Socket.cc.
    : Component(state), direction_(UNKNOWN), dataPortWidth_() {}
~Socket()
TTAMachine::Socket::~Socket () virtual
Destructor.
Definition at line 88 of file Socket.cc.
                {
    unsetMachine();
    AssocTools::deleteAllItems(busses_);
}
References busses_, AssocTools::deleteAllItems(), and unsetMachine().
Socket() [3/3]
TTAMachine::Socket::Socket (const Socket &) private
Copying forbidden.
Member Function Documentation
attachBus()
void TTAMachine::Socket::attachBus (Segment & bus)
Attaches a bus to the socket.
If no bus is currently attached, the direction of the socket is set to Socket::INPUT or Socket::OUTPUT. When possible, the direction is set to Socket::INPUT. Otherwise, it is set to Socket::OUTPUT.
Parameters
bus The segment of a bus being attached.
Exceptions
IllegalRegistration If the bus is not registered to the same machine as the socket.
IllegalConnectivity If the socket is attached to ports in such a way that its direction cannot be either input or output.
Definition at line 166 of file Socket.cc.
{
    const string procName = "Socket::attachBus";
    ensureRegistration(*bus.parentBus());
    MachineTester& tester = machine()->machineTester();
    if (!tester.canConnect(*this, bus)) {
        string errorMsg = MachineTestReporter::socketSegmentConnectionError(
            *this, bus, tester);
        throw IllegalConnectivity(__FILE__, __LINE__, procName, errorMsg);
    }
    if (!bus.isConnectedTo(*this)) {
        const Connection* conn = new Connection(*this, bus);
        busses_.push_back(conn);
        bus.attachSocket(*this);
    } else {
        assert(false);
    }
    // set the direction
    if (direction_ == UNKNOWN) {
        if (tester.canSetDirection(*this, INPUT)) {
            setDirection(INPUT);
        } else if (tester.canSetDirection(*this, OUTPUT)) {
            setDirection(OUTPUT);
        } else {
            string errorMsg = "Direction of the socket cannot be set.";
            Application::writeToErrorLog(
                __FILE__, __LINE__, procName, errorMsg);
            Application::abortProgram();
        }
    }
}
References Application::abortProgram(), assert, TTAMachine::Segment::attachSocket(), busses_, MachineTester::canConnect(), MachineTester::canSetDirection(), direction_, TTAMachine::Component::ensureRegistration(), INPUT, TTAMachine::Segment::isConnectedTo(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), OUTPUT, TTAMachine::Segment::parentBus(), setDirection(), MachineTestReporter::socketSegmentConnectionError(), UNKNOWN, and Application::writeToErrorLog().
Referenced by ADFCombiner::addBuses(), SimpleICOptimizer::addConnections(), TTAMachine::Segment::attachSocket(), FullyConnectedCheck::attachSocketToAllBusses(), BlocksGCU::BlocksGCU(), ADFCombiner::connectVectorLSU(), UniversalMachine::construct(), BlocksTranslator::CreateConnection(), ADFCombiner::createPortsAndSockets(), SocketBusConnCmd::Do(), VLIWConnectIC::explore(), loadState(), and SocketDialog::onAttach().
attachPort()
void TTAMachine::Socket::attachPort (Port & port) private
Notifies the socket that a port has been attached to it.
Private helper method used only by friend class Port.
Parameters
port The port that has been attached to this socket.
Definition at line 618 of file Socket.cc.
{
    ports_.push_back(&port);
}
References port(), and ports_.
Referenced by TTAMachine::Port::attachSocket().
connectedBuses() [1/2]
std::set< Bus * > TTAMachine::Socket::connectedBuses ()
Returns set of buses where the socket is connected to.
Definition at line 368 of file Socket.cc.
                       {
    set<Bus*> result;
    for (const Connection* conn : busses_) {
        result.insert(conn->bus()->parentBus());
    }
    return result;
}
References busses_.
connectedBuses() [2/2]
const std::set< Bus * > TTAMachine::Socket::connectedBuses () const
Returns set of buses where the socket is connected to.
Definition at line 381 of file Socket.cc.
{
    set<Bus*> result;
    for (const Connection* conn : busses_) {
        result.insert(conn->bus()->parentBus());
    }
    return result;
}
References busses_.
connection()
const Connection & TTAMachine::Socket::connection (const Segment & bus) const
Returns the Connection object which connects this socket and the given segment.
This method is not intended for clients. Do not use this method. The connection must exist before calling this function.
Parameters
bus The segment of a bus which is attached to this socket.
Returns
Connection object which joins the socket and the segment.
Definition at line 302 of file Socket.cc.
{
    ConnectionTable::const_iterator iter = busses_.begin();
    while (iter != busses_.end()) {
        if ((*iter)->bus() == &bus) {
            return **iter;
        } else {
            iter++;
        }
    }
    string errorMsg = "The requested Connection object does not exist in "
        "Socket.";
    string procName = "Socket::connection";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
    // this return statement is only to avoid warning in Solaris environment
    return **iter;
}
References Application::abortProgram(), busses_, and Application::writeToErrorLog().
Referenced by TTAMachine::Segment::attachSocket(), detachBus(), and removeConnection().
dataPortWidth()
const std::string & TTAMachine::Socket::dataPortWidth () const
Definition at line 415 of file Socket.cc.
{
    return dataPortWidth_;
}
References dataPortWidth_.
Referenced by DefaultICGenerator::writeInterconnectionNetwork().
detachAllBuses()
void TTAMachine::Socket::detachAllBuses () private
Detaches all the buses from this socket.
Definition at line 640 of file Socket.cc.
                       {
    while (busses_.size() > 0) {
        Segment* bus = busses_[0]->bus();
        detachBus(*bus);
    }
}
References busses_, and detachBus().
Referenced by loadState(), and unsetMachine().
detachAllPorts()
void TTAMachine::Socket::detachAllPorts ()
Detaches all ports from the socket.
Definition at line 278 of file Socket.cc.
                       {
    PortTable::iterator iter = ports_.begin();
    while (iter != ports_.end()) {
        // removes the socket from ports_
        (*iter)->detachSocket(*this);
        iter = ports_.begin();
    }
    ports_.clear();
}
References ports_.
Referenced by unsetMachine().
detachBus() [1/2]
void TTAMachine::Socket::detachBus (Bus & bus)
Detaches all the segments of the given bus from the socket.
If there are no buses connected to the socket after detaching the given bus, the direction of the socket is set to Socket::UNKNOWN. Note that detaching the bus may affect to the value of maximum simultaneous register reads of register files connected to the socket.
Parameters
bus Bus to be detached.
Definition at line 244 of file Socket.cc.
{
    int segments = bus.segmentCount();
    for (int i = 0; i < segments; i++) {
        Segment* segment = bus.segment(i);
        if (isConnectedTo(*segment)) {
            detachBus(*segment);
        }
    }
}
References detachBus(), isConnectedTo(), TTAMachine::Bus::segment(), segment(), and TTAMachine::Bus::segmentCount().
detachBus() [2/2]
void TTAMachine::Socket::detachBus (Segment & bus)
Detaches the given segment of a bus from the socket.
If there are no buses connected to the socket after detaching the given segment, the direction of the socket is set to Socket::UNKNOWN. Note that detaching a segment may affect to the value of maximum simultaneous register reads of register files connected to the socket.
Parameters
bus The segment to be detached.
Exceptions
InstanceNotFound If the given segment is not attached to the socket.
Definition at line 213 of file Socket.cc.
{
    if (!isConnectedTo(bus)) {
        string procName = "Socket::detachBus";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    const Connection& conn = connection(bus);
    removeConnection(&conn);
    if (bus.isConnectedTo(*this)) {
        bus.detachSocket(*this);
        delete &conn;
    }
    // set socket direction to unknown if it has no connections to buses
    if (segmentCount() == 0) {
        direction_ = UNKNOWN;
    }
}
References connection(), TTAMachine::Segment::detachSocket(), direction_, isConnectedTo(), TTAMachine::Segment::isConnectedTo(), removeConnection(), segmentCount(), and UNKNOWN.
Referenced by detachAllBuses(), detachBus(), TTAMachine::Segment::detachSocket(), SocketBusConnCmd::Do(), SocketDialog::onDetach(), SimpleICOptimizer::removeAllConnections(), and TTAMachine::Connection::~Connection().
detachPort()
void TTAMachine::Socket::detachPort (const Port & port) private
Notifies the socket that a port has been detached from it.
Private helper method used only by friend class Port.
Parameters
port The port that has been detached from this socket.
Definition at line 631 of file Socket.cc.
{
    ContainerTools::removeValueIfExists(ports_, &port);
}
References port(), ports_, and ContainerTools::removeValueIfExists().
Referenced by TTAMachine::Port::detachAllSockets(), and TTAMachine::Port::detachSocket().
direction()
Direction TTAMachine::Socket::direction () const
Referenced by DefaultICGenerator::addICToNetlist(), BEMGenerator::addPortCodes(), TTAMachine::Port::attachSocket(), InputPSocketBroker::buildResources(), OutputPSocketBroker::buildResources(), DefaultICGenerator::busAltSignal(), DefaultDecoderGenerator::busCntrlSignalPinOfSocket(), DefaultDecoderGenerator::busControlWidth(), DefaultICDecoderEstimator::busParameters(), MachineTester::canConnect(), MachineTester::canSetDirection(), BEMValidator::checkDestinationField(), BEMValidator::checkSourceField(), DefaultDecoderGenerator::completeDecoderBlock(), SocketFactory::createEditPart(), TTAProgram::TPEFProgramFactory::createInstruction(), DefaultDecoderGenerator::dataControlWidth(), DefaultICDecoderEstimator::delayOfSocket(), SocketBusConnCmd::Do(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::generateSocketsAndMuxes(), TTAMachine::Port::inputSocket(), DefaultICGenerator::inputSocketControlValue(), DefaultICGenerator::inputSocketDataPortWidth(), DefaultICGenerator::inputSockets(), loadState(), DefaultICGenerator::maxOutputSocketDataPortWidth(), DefaultDecoderGenerator::needsBusControl(), DefaultDecoderGenerator::needsDataControl(), BEMValidator::needsSourceField(), TTAMachine::Port::outputSocket(), DefaultICGenerator::outputSocketCntrlPinForSegment(), DefaultICGenerator::outputSocketDataControlValue(), DefaultICGenerator::outputSocketDataPortWidth(), DefaultICGenerator::outputSockets(), setDirection(), BEMGenerator::socket(), BEMGenerator::socketCount(), DefaultICGenerator::socketEntityName(), DefaultICGenerator::socketIsGenerated(), DefaultICDecoderEstimator::socketParameters(), SocketDialog::updateDirection(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), DefaultDecoderGenerator::writeBusControlRulesOfOutputSocket(), DefaultICGenerator::writeInterconnectionNetwork(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
hasDataPortWidth()
bool TTAMachine::Socket::hasDataPortWidth () const
Definition at line 410 of file Socket.cc.
{
    return !dataPortWidth_.empty();
}
References dataPortWidth_.
Referenced by DefaultICGenerator::writeInterconnectionNetwork().
isConnectedTo() [1/2]
bool TTAMachine::Socket::isConnectedTo (const Bus & bus) const
Checks whether the socket is connected to the given bus.
Parameters
bus A bus.
Returns
True if connected, otherwise false.
Definition at line 331 of file Socket.cc.
{
    int segments = bus.segmentCount();
    for (int i = 0; i < segments; i++) {
        if (isConnectedTo(*bus.segment(i))) {
            return true;
        }
    }
    return false;
}
References isConnectedTo(), TTAMachine::Bus::segment(), and TTAMachine::Bus::segmentCount().
Referenced by SimpleICOptimizer::addConnections(), TTAMachine::Segment::attachSocket(), FullyConnectedCheck::attachSocketToAllBusses(), MachineTester::canConnect(), ProDeSegmentEditPolicy::canHandle(), ProDeSocketEditPolicy::canHandle(), POMValidator::checkConnectivity(), ADFCombiner::connectVectorLSU(), TTAProgram::TPEFProgramFactory::createInstruction(), ADFCombiner::createPortsAndSockets(), detachBus(), detachBus(), TTAMachine::Segment::detachSocket(), SocketBusConnCmd::Do(), VLIWConnectIC::explore(), ConnectTool::figure(), isConnectedTo(), ProgrammabilityValidator::listConnections(), MachineResourceManager::registerFileIndexReference(), MachineResourceManager::rFPortOrFUIndexReference(), FullyConnectedCheck::socketAttachedToAllBusses(), and TTAMachine::Connection::~Connection().
isConnectedTo() [2/2]
bool TTAMachine::Socket::isConnectedTo (const Segment & bus) const
Checks whether the socket is connected to the given segment.
Parameters
bus Segment of a bus.
Returns
True if connected, otherwise false.
Definition at line 350 of file Socket.cc.
{
    ConnectionTable::const_iterator iter = busses_.begin();
    while (iter != busses_.end()) {
        if ((*iter)->bus() == &bus) {
            return true;
        } else {
            iter++;
        }
    }
    return false;
}
References busses_.
loadState()
void TTAMachine::Socket::loadState (const ObjectState * state) virtual
Loads its state from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If the machine already has a socket by the same name as the new name of this socket or if the given ObjectState tree is invalid.
Reimplemented from TTAMachine::Component.
Definition at line 502 of file Socket.cc.
{
    string procName = "Socket::loadState";
    MOMTextGenerator textGenerator;
    if (state->name() != OSNAME_SOCKET) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    Component::loadState(state);
    // load connections to busses
    detachAllBuses();
    try {
        for (int childIndex = 0; childIndex < state->childCount();
             childIndex++) {
            ObjectState* child = state->child(childIndex);
            if (child->name() == Connection::OSNAME_CONNECTION) {
                string busName =
                    child->stringAttribute(Connection::OSKEY_BUS);
                string segmentName =
                    child->stringAttribute(Connection::OSKEY_SEGMENT);
                if (!isRegistered()) {
                    format text = textGenerator.text(
                        MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR);
                    text % name();
                    throw ObjectStateLoadingException(
                        __FILE__, __LINE__, procName, text.str());
                }
                Machine::BusNavigator busNav = machine()->busNavigator();
                Bus* bus = NULL;
                Segment* segment = NULL;
                try {
                    bus = busNav.item(busName);
                } catch (InstanceNotFound&) {
                    format text = textGenerator.text(
                        MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR_BUS);
                    text % busName % name();
                    throw ObjectStateLoadingException(
                        __FILE__, __LINE__, procName, text.str());
                }
                try {
                    segment = bus->segment(segmentName);
                } catch (InstanceNotFound&) {
                    format text = textGenerator.text(
                        MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR_SEGMENT);
                    text % name() % segmentName % busName;
                    throw ObjectStateLoadingException(
                        __FILE__, __LINE__, procName, text.str());
                }
                attachBus(*segment);
            } else {
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName);
            }
        }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
    // load direction
    string direction("");
    try {
        direction = state->stringAttribute(OSKEY_DIRECTION);
        if (direction == OSVALUE_INPUT) {
            setDirection(INPUT);
        } else if (direction == OSVALUE_OUTPUT) {
            setDirection(OUTPUT);
        } else if (direction == OSVALUE_UNKNOWN) {
            if (segmentCount() > 0) {
                format text = textGenerator.text(
                    MOMTextGenerator::
                    TXT_UNKNOWN_SOCKET_DIR_AND_SEGMENT_CONN);
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, procName, text.str());
            }
            direction_ = UNKNOWN;
        } else {
            throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
        }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References attachBus(), TTAMachine::Machine::busNavigator(), ObjectState::child(), ObjectState::childCount(), detachAllBuses(), direction(), direction_, Exception::errorMessage(), INPUT, TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::loadState(), TTAMachine::Component::machine(), TTAMachine::Component::name(), ObjectState::name(), TTAMachine::Connection::OSKEY_BUS, OSKEY_DIRECTION, TTAMachine::Connection::OSKEY_SEGMENT, TTAMachine::Connection::OSNAME_CONNECTION, OSNAME_SOCKET, OSVALUE_INPUT, OSVALUE_OUTPUT, OSVALUE_UNKNOWN, OUTPUT, TTAMachine::Bus::segment(), segment(), segmentCount(), setDirection(), ObjectState::stringAttribute(), Texts::TextGenerator::text(), MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR, MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR_BUS, MOMTextGenerator::TXT_SOCKET_REF_LOAD_ERR_SEGMENT, and UNKNOWN.
Referenced by PasteComponentCmd::Do(), TTAMachine::Machine::loadState(), and SocketDialog::onAttach().
operator=()
Socket & TTAMachine::Socket::operator= (const Socket &) private
Assingment forbidden.
port()
Port * TTAMachine::Socket::port (int index) const
Returns a port by the given index.
The given index must be greater or equal to 0 and less than the number of ports attached to the socket.
Parameters
index Index.
Returns
The port found by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 266 of file Socket.cc.
{
    if (index < 0 || index >= portCount()) {
        string procName = "Socket::port";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return ports_[index];
}
References portCount(), and ports_.
Referenced by DefaultICGenerator::addICToNetlist(), BEMGenerator::addPortCodes(), InputPSocketBroker::assign(), OutputPSocketBroker::assign(), attachPort(), DefaultICDecoderEstimator::busParameters(), BEMValidator::checkSocketCodeTable(), TTAProgram::TPEFProgramFactory::createInstruction(), DefaultICDecoderGenerator::dataPortWidth(), detachPort(), SocketBusConnCmd::Do(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), BEMGenerator::haveEqualConnections(), DefaultICGenerator::inputSocketDataPortWidth(), MachineTester::legalPortConnections(), DefaultICGenerator::maxOutputSocketDataPortWidth(), BEMValidator::needsSocketCodeTable(), BEMGenerator::needsSocketCodeTable(), DefaultICGenerator::outputSocketDataControlValue(), DefaultICGenerator::outputSocketDataPortWidth(), SimpleICOptimizer::removeAllConnections(), TTAProgram::TPEFProgramFactory::resolveSocketAllocations(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), DefaultICDecoderEstimator::socketParameters(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), and DefaultICGenerator::writeInterconnectionNetwork().
portCount()
int TTAMachine::Socket::portCount () const
Referenced by DefaultICGenerator::addICToNetlist(), BEMGenerator::addPortCodes(), InputPSocketBroker::assign(), OutputPSocketBroker::assign(), DefaultICDecoderEstimator::busParameters(), BEMValidator::checkDestinationField(), BEMValidator::checkSocketCodeTable(), BEMValidator::checkSourceField(), DefaultDecoderGenerator::completeDecoderBlock(), TTAProgram::TPEFProgramFactory::createInstruction(), DefaultDecoderGenerator::dataControlWidth(), DefaultICDecoderGenerator::dataPortWidth(), SocketBusConnCmd::Do(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), DefaultICGenerator::generateSocketsAndMuxes(), BEMGenerator::haveEqualConnections(), DefaultICGenerator::inputSocketDataPortWidth(), MachineTester::legalPortConnections(), DefaultICGenerator::maxOutputSocketDataPortWidth(), DefaultDecoderGenerator::needsBusControl(), DefaultDecoderGenerator::needsDataControl(), BEMValidator::needsSocketCodeTable(), BEMGenerator::needsSocketCodeTable(), BEMValidator::needsSourceField(), DefaultICGenerator::outputSocketDataControlValue(), DefaultICGenerator::outputSocketDataPortWidth(), port(), SimpleICOptimizer::removeAllConnections(), TTAProgram::TPEFProgramFactory::resolveSocketAllocations(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), DefaultICGenerator::socketEntityName(), DefaultICGenerator::socketIsGenerated(), DefaultICDecoderEstimator::socketParameters(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), and DefaultDecoderGenerator::writeSocketCntrlSignals().
removeConnection()
void TTAMachine::Socket::removeConnection (const Connection * connection) private
Removes a connection from the connection table.
Parameters
connection The connection to be removed.
Definition at line 605 of file Socket.cc.
{
    ContainerTools::removeValueIfExists(busses_, connection);
}
References busses_, connection(), and ContainerTools::removeValueIfExists().
Referenced by detachBus().
saveState()
ObjectState * TTAMachine::Socket::saveState () const virtual
Saves the contents of the socket to an ObjectState object.
Returns
The newly created ObjectState object.
Reimplemented from TTAMachine::Component.
Definition at line 465 of file Socket.cc.
{
    ObjectState* root = Component::saveState();
    root->setName(OSNAME_SOCKET);
    // set direction
    if (direction_ == INPUT) {
        root->setAttribute(OSKEY_DIRECTION, OSVALUE_INPUT);
    } else if (direction_ == OUTPUT) {
        root->setAttribute(OSKEY_DIRECTION, OSVALUE_OUTPUT);
    } else {
        root->setAttribute(OSKEY_DIRECTION, OSVALUE_UNKNOWN);
    }
    // add connections
    ConnectionTable::const_iterator iter = busses_.begin();
    while (iter != busses_.end()) {
        const Connection* conn = *iter;
        ObjectState* bus = conn->saveState();
        root->addChild(bus);
        iter++;
    }
    return root;
}
References ObjectState::addChild(), busses_, direction_, INPUT, OSKEY_DIRECTION, OSNAME_SOCKET, OSVALUE_INPUT, OSVALUE_OUTPUT, OSVALUE_UNKNOWN, OUTPUT, TTAMachine::Connection::saveState(), TTAMachine::Component::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by SocketDialog::onAttach().
segment()
Segment * TTAMachine::Socket::segment (int index) const
By the given index, returns the segment a socket is connected to.
The given index must be greater or equal to 0 and smaller than the number of segments attached to the socket.
Parameters
index The index.
Returns
Segment by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 401 of file Socket.cc.
{
    if (index < 0 || index >= segmentCount()) {
        string procName = "Socket::segment";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return busses_[index]->bus();
}
References busses_, and segmentCount().
Referenced by MachineConnectivityCheck::appendConnectedDestinationBuses(), MachineConnectivityCheck::appendConnectedSourceBuses(), MachineConnectivityCheck::busConnectedToPort(), MachineConnectivityCheck::canWriteAllImmediates(), DefaultDecoderGenerator::connectedBuses(), BlocksTranslator::CreateConnection(), detachBus(), DefaultICGenerator::inputSocketControlValue(), loadState(), DefaultICGenerator::outputSocketCntrlPinForSegment(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), DefaultICDecoderEstimator::socketParameters(), SocketDialog::updateConnected(), and DefaultICGenerator::writeInterconnectionNetwork().
segmentCount()
int TTAMachine::Socket::segmentCount () const
Referenced by DefaultICGenerator::addICToNetlist(), MachineConnectivityCheck::appendConnectedDestinationBuses(), MachineConnectivityCheck::appendConnectedSourceBuses(), MachineConnectivityCheck::busConnectedToPort(), DefaultDecoderGenerator::busControlWidth(), MachineTester::canConnect(), MachineTester::canSetDirection(), MachineConnectivityCheck::canWriteAllImmediates(), DefaultDecoderGenerator::completeDecoderBlock(), DefaultDecoderGenerator::connectedBuses(), BlocksTranslator::CreateConnection(), FullyConnectedCheck::createSocket(), detachBus(), DefaultICGenerator::generateSocketsAndMuxes(), DefaultICGenerator::inputSocketControlValue(), loadState(), DefaultDecoderGenerator::needsBusControl(), DefaultICGenerator::outputSocketCntrlPinForSegment(), segment(), InputPSocketBroker::setupResourceLinks(), OutputPSocketBroker::setupResourceLinks(), DefaultICGenerator::socketEntityName(), DefaultICGenerator::socketIsGenerated(), DefaultICDecoderEstimator::socketParameters(), TTAMachine::Port::unconnectedSocket(), SocketDialog::updateConnected(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), and DefaultDecoderGenerator::writeSocketCntrlSignals().
setDataPortWidth()
void TTAMachine::Socket::setDataPortWidth (const std::string & width)
Definition at line 420 of file Socket.cc.
{
    dataPortWidth_ = width;
}
References dataPortWidth_.
Referenced by DefaultICGenerator::addICToNetlist().
setDirection()
void TTAMachine::Socket::setDirection (Direction direction)
Sets the direction of the socket.
The given direction must be either Socket::INPUT or Socket::OUTPUT.
Parameters
direction The new direction.
Exceptions
IllegalConnectivity If the direction of the port cannot be changed.
Definition at line 130 of file Socket.cc.
{
    const string procName = "Socket::setDirection";
    if (!isRegistered()) {
        MOMTextGenerator textGenerator;
        format text = textGenerator.text(
            MOMTextGenerator::TXT_SET_DIR_SOCKET_NOT_REGISTERED);
        text % name();
        throw IllegalConnectivity(__FILE__, __LINE__, procName, text.str());
    }
    MachineTester& tester = machine()->machineTester();
    if (tester.canSetDirection(*this, direction)) {
        direction_ = direction;
    } else {
        string errorMsg = MachineTestReporter::socketDirectionSettingError(
            *this, direction, tester);
        throw IllegalConnectivity(__FILE__, __LINE__, procName, errorMsg);
    }
}
References MachineTester::canSetDirection(), direction(), direction_, TTAMachine::Component::isRegistered(), TTAMachine::Component::machine(), TTAMachine::Machine::machineTester(), TTAMachine::Component::name(), MachineTestReporter::socketDirectionSettingError(), Texts::TextGenerator::text(), and MOMTextGenerator::TXT_SET_DIR_SOCKET_NOT_REGISTERED.
Referenced by ADFCombiner::addBuses(), SimpleICOptimizer::addConnections(), attachBus(), BlocksGCU::BlocksGCU(), ADFCombiner::connectVectorLSU(), UniversalMachine::construct(), BlocksTranslator::CreateConnection(), ADFCombiner::createPortsAndSockets(), FullyConnectedCheck::createSocket(), SocketBusConnCmd::Do(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), loadState(), and SocketDialog::onDirection().
setMachine()
void TTAMachine::Socket::setMachine (Machine & mach) virtual
Registers the socket to a machine.
Parameters
mach Machine to which the socket is to be registered.
Exceptions
ComponentAlreadyExists If there already is another socket by the same name in the machine.
Implements TTAMachine::Component.
Definition at line 432 of file Socket.cc.
{
    internalSetMachine(mach);
    mach.addSocket(*this);
}
References TTAMachine::Machine::addSocket(), and TTAMachine::Component::internalSetMachine().
Referenced by FullyConnectedCheck::createSocket(), and AddSocketCmd::Do().
setName()
void TTAMachine::Socket::setName (const std::string & name) virtual
Sets the name of the socket.
Parameters
name New name of the socket.
Exceptions
ComponentAlreadyExists If a socket with the given name is already in the same machine.
InvalidName If the given name is not valid for a component.
Reimplemented from TTAMachine::Component.
Definition at line 103 of file Socket.cc.
{
    if (name == this->name()) {
        return;
    }
    if (machine() != NULL) {
        if (machine()->socketNavigator().hasItem(name)) {
            string procName = "Socket::setName";
            throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
        } else {
            Component::setName(name);
        }
    } else {
        Component::setName(name);
    }
}
References TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::Component::setName().
Referenced by SocketDialog::onOK().
unsetMachine()
void TTAMachine::Socket::unsetMachine () virtual
Removes the socket from the machine it is registered to.
Detaches all the busses and ports attached to the socket.
Implements TTAMachine::Component.
Definition at line 443 of file Socket.cc.
                     {
    if (machine() == NULL) {
        return;
    }
    Machine* mach = machine();
    internalUnsetMachine();
    detachAllBuses();
    detachAllPorts();
    mach->removeSocket(*this);
}
References detachAllBuses(), detachAllPorts(), TTAMachine::Component::internalUnsetMachine(), TTAMachine::Component::machine(), and TTAMachine::Machine::removeSocket().
Referenced by ~Socket().
Friends And Related Symbol Documentation
Port
friend class Port friend
Definition at line 136 of file Socket.hh.
Member Data Documentation
busses_
ConnectionTable TTAMachine::Socket::busses_ private
Contains all connections to busses.
Definition at line 131 of file Socket.hh.
Referenced by attachBus(), connectedBuses(), connectedBuses(), connection(), detachAllBuses(), isConnectedTo(), removeConnection(), saveState(), segment(), and ~Socket().
dataPortWidth_
std::string TTAMachine::Socket::dataPortWidth_ private
Dataport width.
Definition at line 129 of file Socket.hh.
Referenced by dataPortWidth(), hasDataPortWidth(), and setDataPortWidth().
direction_
Direction TTAMachine::Socket::direction_ private
Direction of the socket.
Definition at line 127 of file Socket.hh.
Referenced by attachBus(), detachBus(), loadState(), saveState(), and setDirection().
OSKEY_DIRECTION
const string TTAMachine::Socket::OSKEY_DIRECTION = "direction" static
ObjectState attribute key for socket direction.
Definition at line 102 of file Socket.hh.
Referenced by loadState(), saveState(), ADFSerializer::socketToMachine(), and ADFSerializer::socketToMDF().
OSNAME_SOCKET
const string TTAMachine::Socket::OSNAME_SOCKET = "socket" static
ObjectState name for socket.
Definition at line 100 of file Socket.hh.
Referenced by ADFSerializer::convertToMDFFormat(), PasteComponentCmd::Do(), TTAMachine::Machine::loadState(), loadState(), saveState(), and ADFSerializer::socketToMachine().
OSVALUE_INPUT
const string TTAMachine::Socket::OSVALUE_INPUT = "input" static
ObjectState attribute value for input direction.
Definition at line 104 of file Socket.hh.
Referenced by loadState(), saveState(), ADFSerializer::socketToMachine(), and ADFSerializer::socketToMDF().
OSVALUE_OUTPUT
const string TTAMachine::Socket::OSVALUE_OUTPUT = "output" static
ObjectState attribute value for output direction.
Definition at line 106 of file Socket.hh.
Referenced by loadState(), saveState(), ADFSerializer::socketToMachine(), and ADFSerializer::socketToMDF().
OSVALUE_UNKNOWN
const string TTAMachine::Socket::OSVALUE_UNKNOWN = "unknown" static
ObjectState attribute value for unknown direction.
Definition at line 108 of file Socket.hh.
Referenced by loadState(), saveState(), and ADFSerializer::socketToMachine().
ports_
PortTable TTAMachine::Socket::ports_ private
Contains all connections to ports.
Definition at line 133 of file Socket.hh.
Referenced by attachPort(), detachAllPorts(), detachPort(), and port().
The documentation for this class was generated from the following files:
Socket.hh
Socket.cc