OpenASIP: CmdTrigger Class Reference
CmdTrigger Class Reference
#include <TestOsal.hh>
Public Member Functions
CmdTrigger ()
CmdTrigger (const CmdTrigger &cmd)
virtual ~CmdTrigger ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Custom command that executes the trigger command of last loaded operation.
Definition at line 58 of file TestOsal.hh.
Constructor & Destructor Documentation
CmdTrigger() [1/2]
CmdTrigger::CmdTrigger ()
Constructor.
Definition at line 67 of file TestOsal.cc.
                       : CustomCommand("trigger") {
}
CmdTrigger() [2/2]
CmdTrigger::CmdTrigger (const CmdTrigger & cmd) explicit
Copy constructor.
Definition at line 73 of file TestOsal.cc.
                                            : CustomCommand(cmd) {
}
~CmdTrigger()
CmdTrigger::~CmdTrigger () virtual
Destructor.
Definition at line 79 of file TestOsal.cc.
{
}
Member Function Documentation
execute()
bool CmdTrigger::execute (const std::vector< DataObject > & arguments) virtual
Executes the trigger command of an operation.
Parameters
arguments The arguments for the command.
Returns
True if the command is executed succesfully, otherwise false.
Exceptions
NumberFormatException If data object conversion fails.
Implements CustomCommand.
Definition at line 90 of file TestOsal.cc.
{
    ScriptInterpreter* scriptInterp = interpreter();
    OsalInterpreter* interp = dynamic_cast<OsalInterpreter*>(scriptInterp);
    assert(interp != NULL);
    DataObject* obj = new DataObject();
    if (arguments.size() < 2) {
        obj->setString("too few arguments");
        interp->setResult(obj);
        return false;
    }
    string opName = arguments[1].stringValue();
    Operation* op = NULL;
    try {
        op = &interp->operation(opName);
    } catch (const IllegalOperationBehavior& e) {
        // Catch error due to undefined or missing operation behavior.
        obj->setString(e.errorMessage());
        interp->setResult(obj);
        return false;
    }
    if (op == &NullOperation::instance()) {
        obj->setString("unknown operation \"" + opName + "\"");
        interp->setResult(obj);
        return false;
    }
    // remove "trigger" and operation name.
    vector<DataObject> inputs;
    for (size_t i = 2; i < arguments.size(); i++) {
        inputs.push_back(arguments[i]);
    }
    vector<SimValue*> args;
    TesterContext& context = *dynamic_cast<TesterContext*>(&interp->context());
    OperationContext& opContext = context.operationContext();
    string result = "";
    OperationSimulator& simulator = OperationSimulator::instance();
    InstructionAddress oldPC = opContext.programCounter();
    if (!simulator.simulateTrigger(*op, inputs, args, opContext, result)) {
        for (unsigned int i = 0; i < args.size(); i++) {
            delete args[i];
        }
        obj->setString(result);
        interp->setResult(obj);
        return false;
    } else {
        for (int i = 0; i < op->numberOfOutputs(); i++) {
            SimValue* current = args[op->numberOfInputs() + i];
            string output = context.toOutputFormat(current);
            result += output;
            // put blank everywhere else but after the last output
            if (i < op->numberOfOutputs() - 1) {
                result += " ";
            }
        }
    }
    for (unsigned int i = 0; i < args.size(); i++) {
        delete args[i];
    }
    if (opContext.saveReturnAddress()) {
        opContext.returnAddress() = oldPC;
    }
    obj->setString(result);
    interp->setResult(obj);
    return true;
}
References assert, CustomCommand::context(), SimpleScriptInterpreter::context(), Exception::errorMessage(), OperationSimulator::instance(), NullOperation::instance(), CustomCommand::interpreter(), Operation::numberOfInputs(), Operation::numberOfOutputs(), OsalInterpreter::operation(), OperationContext::programCounter(), OperationContext::returnAddress(), OperationContext::saveReturnAddress(), ScriptInterpreter::setResult(), DataObject::setString(), and OperationSimulator::simulateTrigger().
helpText()
string CmdTrigger::helpText () const virtual
Returns the help text of trigger command.
Returns
The help text.
Implements CustomCommand.
Definition at line 175 of file TestOsal.cc.
{
    return "trigger <operation> <operand>...";
}
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc