OpenASIP: ObjectState Class Reference
ObjectState Class Reference
#include <ObjectState.hh>
Classes
struct Attribute
Struct for describing an attribute of the XML element.
Public Member Functions
ObjectState (const std::string &name, ObjectState *parent=NULL)
ObjectState (const ObjectState &old)
~ObjectState ()
ObjectState * parent () const
std::string name () const
void setName (const std::string &name)
void setValue (const std::string &value)
void setValue (int value)
void setValue (double value)
void setValue (bool value)
void setValue (UIntWord value)
std::string stringValue () const
int intValue () const
unsigned int unsignedIntValue () const
double doubleValue () const
bool boolValue () const
int UIntWordValue () const
void setAttribute (const std::string &name, const std::string &value)
void setAttribute (const std::string &name, int value)
void setAttribute (const std::string &name, unsigned int value)
void setAttribute (const std::string &name, double value)
void setAttribute (const std::string &name, bool value)
void setAttribute (const std::string &name, ULongWord value)
int attributeCount () const
Attribute * attribute (int index) const
bool hasAttribute (const std::string &name) const
std::string stringAttribute (const std::string &name) const
int intAttribute (const std::string &name) const
unsigned int unsignedIntAttribute (const std::string &name) const
double doubleAttribute (const std::string &name) const
bool boolAttribute (const std::string &name) const
UIntWord UIntWordAttribute (const std::string &name) const
ULongWord uLongAttribute (const std::string &name) const
bool hasChild (const std::string &name) const
void addChild (ObjectState *child)
void removeChild (ObjectState *child)
void replaceChild (ObjectState *old, ObjectState *newChild)
int childCount () const
ObjectState * childByName (const std::string &name) const
ObjectState * child (int index) const
bool operator!= (const ObjectState &object)
Static Public Member Functions
static void dumpObjectState (const ObjectState &state, std::ostream &output, const std::string &identation="")
Private Types
typedef std::vector< ObjectState * > ChildTable
Table of child ObjectState.
typedef std::vector< Attribute > AttributeTable
Table of attributes.
Private Member Functions
ObjectState & operator= (const ObjectState &old)
Assingment forbidden.
std::string commonErrorMessage () const
Private Attributes
std::string name_
Name of the element.
std::string value_
The value of a leaf element.
ObjectState * parent_
The parent element.
ChildTable children_
The child elements.
AttributeTable attributes_
Contains all the attributes of the element.
Detailed Description
Class ObjectState represents state of an object.
It may contain attribute-value pairs of the object and a main value. It may be used as a node in tree structure or alone. If a class is going to be serialized to a file, it must be able to create an ObjectState object of itself. It must be able to create itself from an ObjectState object too. That is, it must implement the Serializable interface. ObjectState tree is a general structure which can be handled by many different kind of serializers, for example XMLSerializer. Serializers can read a file create an ObjectState tree according to it and they can write a file of a certain format according to a ObjectState tree. ObjectState enables an easy way to serialize an object model to different kinds of file formats.
Definition at line 59 of file ObjectState.hh.
Member Typedef Documentation
AttributeTable
typedef std::vector<Attribute> ObjectState::AttributeTable private
Table of attributes.
Definition at line 127 of file ObjectState.hh.
ChildTable
typedef std::vector<ObjectState*> ObjectState::ChildTable private
Table of child ObjectState.
Definition at line 125 of file ObjectState.hh.
Constructor & Destructor Documentation
ObjectState() [1/2]
ObjectState::ObjectState (const std::string & name, ObjectState * parent = NULL)
Constructor.
Parameters
name Name of the ObjectState.
parent Parent of this object. If non-NULL, this object is added to the parent with addChild().
Definition at line 51 of file ObjectState.cc.
                                                                   :
    name_(name), value_(""), parent_(parent) {
    if (parent != NULL) {
        parent->addChild(this);
    }
}
References addChild(), and parent().
ObjectState() [2/2]
ObjectState::ObjectState (const ObjectState & old)
Copy constructor.
Makes a deep copy.
Parameters
old The ObjectState tree to copy.
Definition at line 65 of file ObjectState.cc.
                                               :
    name_(old.name_), value_(old.value_), parent_(NULL),
    attributes_(old.attributes_) {
    for (int i = 0; i < old.childCount(); i++) {
        ObjectState* newChild = new ObjectState(*old.child(i));
        addChild(newChild);
    }
}
References addChild(), child(), and childCount().
~ObjectState()
ObjectState::~ObjectState ()
Destructor.
Deletes all the children as well and removes itself from the list of child objects of the parent object. That is, the parent object will stay valid.
Definition at line 81 of file ObjectState.cc.
{
    if (parent_ != NULL) {
        bool removed = ContainerTools::removeValueIfExists(
            parent_->children_, this);
        assert(removed);
    }
    SequenceTools::deleteAllItems(children_);
}
References assert, children_, SequenceTools::deleteAllItems(), parent_, and ContainerTools::removeValueIfExists().
Member Function Documentation
addChild()
void ObjectState::addChild (ObjectState * child)
Adds a child object.
Parameters
child ObjectState object to be added as a child.
Definition at line 376 of file ObjectState.cc.
{
    children_.push_back(child);
    child->parent_ = this;
}
References child(), children_, and parent_.
Referenced by IPXactModel::addAddressSpaceObject(), IPXactModel::addBusInterfaceObject(), IPXactModel::addFileObject(), IPXactModel::addModelParamsObject(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), IPXactModel::addSignalObject(), ADFSerializer::bridgeToMDF(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), ProDeOptionsSerializer::convertToConfigFileFormat(), BEMSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMDFFormat(), BEMSerializer::convertToOMFormat(), IDF::IDFSerializer::convertToOMFormat(), OperationSerializer::convertToOperationFormat(), OperationSerializer::convertToXMLFormat(), XMLSerializer::createState(), OSEdAddOperationCmd::Do(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToFile(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::mdfFUPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), ADFSerializer::mdfPort(), ADFSerializer::mdfSRPort(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), ObjectState(), ObjectState(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), InstructionField::reorderSubfields(), TTAMachine::Machine::saveComponentStates(), TTAMachine::ExecutionPipeline::saveOperandUse(), OperationPropertyDialog::saveOperation(), TTAMachine::ExecutionPipeline::saveResourceUse(), IPXactModel::saveState(), GUIOptions::saveState(), BinaryEncoding::saveState(), GuardField::saveState(), ImmediateControlField::saveState(), InstructionFormat::saveState(), LImmDstRegisterField::saveState(), MoveSlot::saveState(), OperationTriggeredEncoding::saveState(), SlotField::saveState(), SocketCodeTable::saveState(), SourceField::saveState(), IDF::MachineImplementation::saveState(), TTAMachine::Bus::saveState(), TTAMachine::FunctionUnit::saveState(), TTAMachine::HWOperation::saveState(), TTAMachine::InstructionTemplate::saveState(), TTAMachine::Machine::saveState(), TTAMachine::OperationTriggeredFormat::saveState(), TTAMachine::Socket::saveState(), TTAMachine::Unit::saveState(), Operand::saveState(), OperationPimpl::saveState(), OSEdOptions::saveState(), IDF::FUGenerated::saveState(), OperationSerializer::setOperandProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), ADFSerializer::socketToMDF(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), InputOperandDialog::updateOperand(), and DataDependenceGraph::writeToXMLFile().
attribute()
ObjectState::Attribute * ObjectState::attribute (int index) const
Returns an attribute by the given index.
The value of index must be greater or equal to 0 and less than the number of attributes.
Parameters
index The index of the requested attribute.
Returns
Attribute by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 228 of file ObjectState.cc.
{
    if (index < 0 || index >= attributeCount()) {
        const string procName = "ObjectState::attribute";
        string errorMsg = commonErrorMessage();
        errorMsg += "Requested attribute by index '";
        errorMsg += Conversion::toString(index);
        errorMsg += "' which is out of range.";
        throw OutOfRange(__FILE__, __LINE__, procName, errorMsg);
    } else {
        return const_cast<Attribute*>(&attributes_[index]);
    }
}
References attributeCount(), attributes_, commonErrorMessage(), and Conversion::toString().
Referenced by XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), and dumpObjectState().
attributeCount()
int ObjectState::attributeCount () const
Referenced by attribute(), XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), and dumpObjectState().
boolAttribute()
bool ObjectState::boolAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
TypeMismatch If the value of the requested attribute can't be converted to bool.
Definition at line 338 of file ObjectState.cc.
{
    string value = stringAttribute(name);
    int intValue;
    try {
        intValue = Conversion::toInt(value);
    } catch (const NumberFormatException&) {
        const string procName = "ObjectState::boolAttribute";
        throw TypeMismatch(__FILE__, __LINE__, procName);
    }
    return intValue;
}
References intValue(), name(), stringAttribute(), and Conversion::toInt().
Referenced by ADFSerializer::addressSpaceToMDF(), ADFSerializer::busToMDF(), ADFSerializer::convertToMDFFormat(), GuardEncoding::GuardEncoding(), BEMSerializer::guardFieldToFile(), TTAMachine::AddressSpace::loadState(), TTAMachine::Machine::loadState(), Operand::loadState(), OperationPimpl::loadState(), TTAMachine::FUPort::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), ADFSerializer::registerFileToMDF(), and OperationSerializer::toXMLFormat().
boolValue()
bool ObjectState::boolValue () const
Referenced by ADFSerializer::addressSpaceToMachine(), and ADFSerializer::registerFileToMachine().
child()
ObjectState * ObjectState::child (int index) const
Returns a child by the given index.
The index must be greater or equal to 0 and less than the number of children.
Parameters
index The index.
Returns
Child by the given index.
Exceptions
OutOfRange If the given index is out of range.
Definition at line 471 of file ObjectState.cc.
{
    if (index < 0 || index >= childCount()) {
        const string procName = "ObjectState::child";
        string errorMsg = commonErrorMessage();
        errorMsg += "Requested child by index '";
        errorMsg += Conversion::toString(index);
        errorMsg += "' which is out of range.";
        throw OutOfRange(__FILE__, __LINE__, procName, errorMsg);
    } else {
        return children_[index];
    }
}
References childCount(), children_, commonErrorMessage(), and Conversion::toString().
Referenced by addChild(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), OSEdTreeView::constructTree(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), BEMSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), BEMSerializer::convertToOMFormat(), IDF::IDFSerializer::convertToOMFormat(), OperationSerializer::convertToOperationFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), OperationSerializer::convertToXMLFormat(), BEMSerializer::convertZeroEncExtraBits(), XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), dumpObjectState(), OperationIndex::effectiveOperation(), IPXactModel::extractAddressSpaces(), IPXactModel::extractBusInterfaces(), IPXactModel::extractFiles(), IPXactModel::extractModelParams(), IPXactModel::extractPortMappings(), IPXactModel::extractSignals(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), ADFSerializer::hasEmptyInstructionTemplate(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), BlocksModel::LoadModelFromXml(), OperationPropertyLoader::loadModule(), GUIOptions::loadState(), BinaryEncoding::loadState(), GuardField::loadState(), ImmediateControlField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), OperationTriggeredEncoding::loadState(), SlotField::loadState(), SocketCodeTable::loadState(), SourceField::loadState(), IDF::MachineImplementation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::Bus::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::OperationTriggeredFormat::loadState(), TTAMachine::Socket::loadState(), TTAMachine::Unit::loadState(), Operand::loadState(), OperationPimpl::loadState(), OSEdOptions::loadState(), IDF::FUGenerated::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), OperationIndex::moduleOf(), ADFSerializer::momTemplateSlot(), ObjectState(), OperationContainer::operation(), OperationIndex::operationName(), operator!=(), TTAMachine::Unit::portNames(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), removeChild(), InstructionField::reorderSubfields(), TTAMachine::ExecutionPipeline::saveOperandUse(), TTAMachine::ExecutionPipeline::saveResourceUse(), OperationSerializer::setOperandProperties(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), ADFSerializer::socketToMDF(), TTAMachine::ExecutionPipeline::sortResourceUsages(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), and OperationPropertyDialog::updateSwapLists().
childByName()
ObjectState * ObjectState::childByName (const std::string & name) const
Returns the child of the requested name.
If there are many children of that name, returns the first of them.
Parameters
name Name of the child.
Returns
First child of the requested name.
Exceptions
InstanceNotFound If the requested child is not found.
Definition at line 443 of file ObjectState.cc.
{
    ChildTable::const_iterator iter = children_.begin();
    while (iter != children_.end()) {
        if ((*iter)->name() == name) {
            return *iter;
        }
        iter++;
    }
    string procName = "ObjectState::childByName";
    string errorMsg = commonErrorMessage();
    errorMsg += "Requested child by name '";
    errorMsg += name;
    errorMsg += "' which doesn't exist.";
    throw InstanceNotFound(__FILE__, __LINE__, procName, errorMsg);
}
References children_, commonErrorMessage(), and name().
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::bridgeToMachine(), ADFSerializer::busToMachine(), ADFSerializer::controlUnitToMachine(), IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), ProDeOptionsSerializer::convertToOptionsObjectFormat(), BEMSerializer::convertZeroEncExtraBits(), IPXactModel::extractAddressSpace(), IPXactModel::extractBusInterface(), IPXactModel::extractFiles(), IPXactModel::extractModelParam(), IPXactModel::extractPortMap(), IPXactModel::extractSignals(), IPXactModel::extractVLNV(), ADFSerializer::functionUnitToMachine(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToOM(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::instructionTemplateToMachine(), BlocksModel::LoadModelFromXml(), IPXactModel::loadState(), BinaryEncoding::loadState(), IDF::MachineImplementation::loadState(), TTAMachine::HWOperation::loadState(), IDF::FUGenerated::loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineSRPort(), ADFSerializer::mdfOperation(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), BEMSerializer::readRegisterFilePortCode(), ADFSerializer::registerFileToMachine(), ADFSerializer::setIUExtensionMode(), GUIOptionsSerializer::setToolbarProperties(), GUIOptionsSerializer::setWindowProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
childCount()
int ObjectState::childCount () const
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), child(), OSEdTreeView::constructTree(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), BEMSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), BEMSerializer::convertToOMFormat(), IDF::IDFSerializer::convertToOMFormat(), OperationSerializer::convertToOperationFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), OperationSerializer::convertToXMLFormat(), BEMSerializer::convertZeroEncExtraBits(), XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), dumpObjectState(), OperationIndex::effectiveOperation(), IPXactModel::extractAddressSpaces(), IPXactModel::extractBusInterfaces(), IPXactModel::extractFiles(), IPXactModel::extractModelParams(), IPXactModel::extractPortMappings(), IPXactModel::extractSignals(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), ADFSerializer::hasEmptyInstructionTemplate(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), BlocksModel::LoadModelFromXml(), OperationPropertyLoader::loadModule(), GUIOptions::loadState(), BinaryEncoding::loadState(), GuardField::loadState(), ImmediateControlField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), OperationTriggeredEncoding::loadState(), SlotField::loadState(), SocketCodeTable::loadState(), SourceField::loadState(), IDF::MachineImplementation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::Bus::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::OperationTriggeredFormat::loadState(), TTAMachine::Socket::loadState(), TTAMachine::Unit::loadState(), Operand::loadState(), OperationPimpl::loadState(), OSEdOptions::loadState(), IDF::FUGenerated::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), OperationIndex::moduleOf(), ADFSerializer::momTemplateSlot(), ObjectState(), OperationContainer::operation(), OperationIndex::operationCount(), TTAMachine::Unit::portNames(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), InstructionField::reorderSubfields(), TTAMachine::ExecutionPipeline::saveOperandUse(), TTAMachine::ExecutionPipeline::saveResourceUse(), OperationSerializer::setOperandProperties(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), ADFSerializer::socketToMDF(), TTAMachine::ExecutionPipeline::sortResourceUsages(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), and OperationPropertyDialog::updateSwapLists().
commonErrorMessage()
std::string ObjectState::commonErrorMessage () const private
Generates a common beginning of error messages.
Returns
The generated error message.
Definition at line 529 of file ObjectState.cc.
{
    string errorMsg = "ObjectState ";
    errorMsg += name();
    errorMsg += ": ";
    return errorMsg;
}
References name().
Referenced by attribute(), child(), childByName(), and stringAttribute().
doubleAttribute()
double ObjectState::doubleAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
NumberFormatException If the value of the requested attribute can't be converted to double.
Definition at line 323 of file ObjectState.cc.
{
    string value = stringAttribute(name);
    return Conversion::toDouble(value);
}
References name(), stringAttribute(), and Conversion::toDouble().
Referenced by BEMSerializer::readState().
doubleValue()
double ObjectState::doubleValue () const
dumpObjectState()
void ObjectState::dumpObjectState (const ObjectState & state, std::ostream & output, const std::string & identation = "") static
Prints object state structure for debug purposes into the stream.
Definition at line 540 of file ObjectState.cc.
{
    using std::cout;
    using std::endl;
    cout << identation << "Name: "<< state.name() << " ";
    if (!state.stringValue().empty()) {
        cout << "Value: " << state.stringValue() << " ";
    }
    cout << endl;
    for (int i = 0; i < state.attributeCount(); i++) {
        cout << identation << "Attr: " << state.attribute(i)->name << " = "
             << state.attribute(i)->value << endl;
    }
    for (int i = 0; i < state.childCount(); i++) {
        dumpObjectState(*state.child(i), output, identation + "  ");
    }
}
References attribute(), attributeCount(), child(), childCount(), dumpObjectState(), ObjectState::Attribute::name, name(), stringValue(), and ObjectState::Attribute::value.
Referenced by dumpObjectState().
hasAttribute()
bool ObjectState::hasAttribute (const std::string & name) const
Returns true if the ObjectState has an attribute with the given name.
Parameters
name Name of the attribute.
Returns
True if the ObjectState has an attribute with the given name.
Definition at line 205 of file ObjectState.cc.
{
    AttributeTable::const_iterator iter = attributes_.begin();
    while (iter != attributes_.end()) {
        if ((*iter).name == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References attributes_, and name().
Referenced by ADFSerializer::addressSpaceToMDF(), TTAMachine::Bus::adjustSegmentChain(), ADFSerializer::busToMDF(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMDFFormat(), BEMSerializer::convertZeroEncExtraBits(), IPXactModel::extractModelParam(), IPXactModel::extractVlnvFromAttr(), ADFSerializer::functionUnitToMDF(), FUPortCode::FUPortCode(), KeyboardShortcut::loadState(), IDF::MachineImplementation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::FunctionUnit::loadState(), TTAMachine::Machine::loadState(), TTAMachine::Port::loadState(), Operand::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::ControlUnit::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), ADFSerializer::machineFUPort(), ADFSerializer::mdfPort(), ADFSerializer::mdfSRPort(), operator!=(), PortCode::PortCode(), BEMSerializer::readState(), ADFSerializer::registerFileToMDF(), InstructionField::reorderSubfields(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), SocketEncoding::SocketEncoding(), ADFSerializer::socketToMDF(), OperationSerializer::toOperation(), and OperationSerializer::toXMLFormat().
hasChild()
bool ObjectState::hasChild (const std::string & name) const
Returns true if there is a child element called the given name.
Returns
True if there is a child element called the given name.
Definition at line 358 of file ObjectState.cc.
{
    ChildTable::const_iterator iter = children_.begin();
    while (iter != children_.end()) {
        if ((*iter)->name() == name) {
            return true;
        }
        iter++;
    }
    return false;
}
References children_, and name().
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), ADFSerializer::addressSpaceToMachine(), TTAMachine::Bus::adjustSegmentChain(), IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), ProDeOptionsSerializer::convertToOptionsObjectFormat(), BEMSerializer::convertZeroEncExtraBits(), IPXactModel::extractAddressSpace(), IPXactModel::extractAddressSpaces(), IPXactModel::extractBusInterface(), IPXactModel::extractBusInterfaces(), IPXactModel::extractBusMode(), IPXactModel::extractFiles(), IPXactModel::extractModelParam(), IPXactModel::extractPortMap(), IPXactModel::extractPortMappings(), IPXactModel::extractSignals(), IPXactModel::extractVLNV(), ADFSerializer::immediateUnitToMachine(), IPXactModel::loadState(), IDF::MachineImplementation::loadState(), IDF::FUGenerated::loadState(), ADFSerializer::machineFUPort(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), BEMSerializer::readRegisterFilePortCode(), ADFSerializer::registerFileToMachine(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), ADFSerializer::socketToMachine(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), and BlocksModel::VerifyXmlStructure().
intAttribute()
int ObjectState::intAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
NumberFormatException If the value of the requested attribute can't be converted to int.
Definition at line 276 of file ObjectState.cc.
{
    string value = stringAttribute(name);
    return Conversion::toInt(value);
}
References name(), stringAttribute(), and Conversion::toInt().
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), TTAMachine::ExecutionPipeline::addResourceUsage(), ADFSerializer::busToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), BEMSerializer::convertZeroEncExtraBits(), Encoding::Encoding(), GPRGuardEncoding::GPRGuardEncoding(), GuardEncoding::GuardEncoding(), BEMSerializer::guardFieldToOM(), ImmediateEncoding::ImmediateEncoding(), ADFSerializer::immediateUnitToMDF(), GUIOptions::loadState(), KeyboardShortcut::loadState(), ToolbarButton::loadState(), ImmediateControlField::loadState(), ImmediateSlotField::loadState(), InstructionField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), OperationTriggeredField::loadState(), SlotField::loadState(), SocketCodeTable::loadState(), IDF::UnitImplementationLocation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::ExecutionPipeline::loadState(), TTAMachine::Guard::loadState(), TTAMachine::RegisterGuard::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::InstructionTemplate::loadState(), Operand::loadState(), OperationPimpl::loadState(), ProDeOptions::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::BaseFUPort::loadStateWithoutReferences(), TTAMachine::BaseRegisterFile::loadStateWithoutReferences(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::ControlUnit::loadStateWithoutReferences(), TTAMachine::FUPort::loadStateWithoutReferences(), TTAMachine::ImmediateUnit::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), ADFSerializer::mdfFUPort(), PortCode::PortCode(), ADFSerializer::registerFileToMDF(), InstructionField::reorderSubfields(), TTAMachine::ExecutionPipeline::saveOperandUse(), TTAMachine::ExecutionPipeline::saveResourceUse(), BEMSerializer::slotFieldToFile(), BEMSerializer::socketCodeTableToFile(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), and OperationPropertyDialog::updateSwapLists().
intValue()
int ObjectState::intValue () const
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), boolAttribute(), BEMSerializer::convertZeroEncExtraBits(), IPXactModel::extractAddressSpace(), IPXactModel::extractSignals(), BinaryEncoding::loadState(), TTAMachine::AddressSpace::loadState(), IDF::FUGenerated::loadState(), OperationSerializer::setOperandProperties(), BEMSerializer::socketCodeTableToOM(), and OperationSerializer::toOperation().
name()
std::string ObjectState::name () const
Referenced by ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), TTAMachine::Bus::adjustSegmentChain(), boolAttribute(), BridgeEncoding::BridgeEncoding(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), childByName(), commonErrorMessage(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), BEMSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), BEMSerializer::convertToOMFormat(), IDF::IDFSerializer::convertToOMFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), BEMSerializer::convertZeroEncExtraBits(), XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), DestinationField::DestinationField(), PasteComponentCmd::Do(), doubleAttribute(), dumpObjectState(), IPXactModel::extractAddressSpace(), IPXactModel::extractAddressSpaces(), IPXactModel::extractBusInterface(), IPXactModel::extractBusInterfaces(), IPXactModel::extractBusMode(), IPXactModel::extractFiles(), IPXactModel::extractModelParam(), IPXactModel::extractModelParams(), IPXactModel::extractPortMap(), IPXactModel::extractPortMappings(), IPXactModel::extractSignals(), IPXactModel::extractVLNV(), IPXactModel::extractVlnvFromAttr(), FUGuardEncoding::FUGuardEncoding(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), FUPortCode::FUPortCode(), GPRGuardEncoding::GPRGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), hasAttribute(), hasChild(), ADFSerializer::hasEmptyInstructionTemplate(), ImmediateEncoding::ImmediateEncoding(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), intAttribute(), IUPortCode::IUPortCode(), GUIOptions::loadState(), KeyboardShortcut::loadState(), ToolbarButton::loadState(), BinaryEncoding::loadState(), GuardField::loadState(), ImmediateControlField::loadState(), ImmediateSlotField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), OperationTriggeredEncoding::loadState(), SlotField::loadState(), SocketCodeTable::loadState(), SourceField::loadState(), IDF::MachineImplementation::loadState(), IDF::UnitImplementationLocation::loadState(), TTAMachine::AddressSpace::loadState(), TTAMachine::Bridge::loadState(), TTAMachine::Bus::loadState(), TTAMachine::ExecutionPipeline::loadState(), TTAMachine::FUPort::loadState(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), TTAMachine::UnconditionalGuard::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::ImmediateSlot::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::OperationTriggeredFormat::loadState(), TTAMachine::RFPort::loadState(), TTAMachine::Segment::loadState(), TTAMachine::Socket::loadState(), TTAMachine::SpecialRegisterPort::loadState(), TTAMachine::Unit::loadState(), Operand::loadState(), OperationPimpl::loadState(), OSEdOptions::loadState(), IDF::FUGenerated::loadState(), TTAMachine::FunctionUnit::loadStateWithoutReferences(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::ControlUnit::loadStateWithoutReferences(), TTAMachine::ImmediateUnit::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), TTAMachine::Segment::loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineSRPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), ADFSerializer::mdfSRPort(), NOPEncoding::NOPEncoding(), operator!=(), BEMSerializer::readRegisterFilePortCode(), ADFSerializer::registerFileToMachine(), RFPortCode::RFPortCode(), TTAMachine::ExecutionPipeline::saveOperandUse(), TTAMachine::ExecutionPipeline::saveResourceUse(), setAttribute(), setAttribute(), setAttribute(), setAttribute(), setAttribute(), setAttribute(), OperationSerializer::setOperandProperties(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), stringAttribute(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), uLongAttribute(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), unsignedIntAttribute(), and OperationPropertyDialog::updateSwapLists().
operator!=()
bool ObjectState::operator!= (const ObjectState & object)
Inequality comparison operator.
Parameters
object Object in which this object is compared to.
Returns
True if objects are inequal, false otherwise.
Definition at line 491 of file ObjectState.cc.
{
    if (name_ != object.name() ||
        value_ != object.stringValue() ||
        children_.size() != static_cast<unsigned int>(object.childCount()) ||
        static_cast<int>(attributes_.size()) != object.attributeCount()) {
        return true;
    }
    for (size_t i = 0; i < attributes_.size(); i++) {
        Attribute attr = attributes_[i];
        if (!object.hasAttribute(attr.name)) {
            return true;
        } else {
            if (attr.value != object.stringAttribute(attr.name)) {
                return true;
            }
        }
    }
    for (size_t i = 0; i < children_.size(); i++) {
        ObjectState& child = *children_[i];
        ObjectState& compare = *object.child(i);
        if (child != compare) {
            return true;
        }
    }
    return false;
}
References attributes_, child(), children_, hasAttribute(), ObjectState::Attribute::name, name(), name_, stringValue(), ObjectState::Attribute::value, and value_.
operator=()
ObjectState & ObjectState::operator= (const ObjectState & old) private
Assingment forbidden.
parent()
ObjectState * ObjectState::parent () const
Referenced by ObjectState(), and replaceChild().
removeChild()
void ObjectState::removeChild (ObjectState * child)
Removes the given child object.
Parameters
child The child object to be removed.
Exceptions
InstanceNotFound If the object does not have the given child object.
Definition at line 389 of file ObjectState.cc.
{
    bool removed = ContainerTools::removeValueIfExists(children_, child);
    if (removed) {
        child->parent_ = NULL;
    } else {
        const string procName = "ObjectState::removeChild";
        throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
}
References child(), children_, parent_, and ContainerTools::removeValueIfExists().
Referenced by InstructionField::reorderSubfields(), and BEMSerializer::sourceFieldToFile().
replaceChild()
void ObjectState::replaceChild (ObjectState * old, ObjectState * newChild)
Replaces a child with a new child.
Parameters
old Child to be replaced.
newChild Child to be added in the place of the old child.
Exceptions
InvalidData If the new child given already has a parent object.
Definition at line 408 of file ObjectState.cc.
{
    if (newChild->parent() != NULL) {
        const string procName = "ObjectState::replaceChild";
        throw InvalidData(__FILE__, __LINE__, procName);
    }
    ChildTable::iterator it = children_.begin();
    while (it != children_.end()) {
        if (*it == old) {
            ObjectState* toBeRemoved = *it;
            ChildTable::iterator pt = it;
            pt++;
            if (pt == children_.end()) {
                children_.push_back(newChild);
            } else {
                children_.insert(pt, newChild);
            }
            newChild->parent_ = this;
            delete toBeRemoved;
            break;
        }
        it++;
    }
}
References children_, parent(), and parent_.
Referenced by OSEdPropertiesCmd::Do().
setAttribute() [1/6]
void ObjectState::setAttribute (const std::string & name, bool value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 192 of file ObjectState.cc.
{
    string valueAsString = Conversion::toString(value);
    setAttribute(name, valueAsString);
}
References name(), setAttribute(), and Conversion::toString().
setAttribute() [2/6]
void ObjectState::setAttribute (const std::string & name, const std::string & value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 100 of file ObjectState.cc.
{
    AttributeTable::iterator iter = attributes_.begin();
    while (iter != attributes_.end()) {
        if ((*iter).name == name) {
            (*iter).value = value;
            return;
        }
        iter++;
    }
    Attribute newAttribute;
    newAttribute.name = name;
    newAttribute.value = value;
    attributes_.push_back(newAttribute);
}
References attributes_, ObjectState::Attribute::name, name(), and ObjectState::Attribute::value.
Referenced by IPXactModel::addBusInterfaceObject(), GUIOptionsSerializer::addKeyboardShortcut(), IPXactModel::addModelParamsObject(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), ADFSerializer::bridgeToMachine(), ADFSerializer::bridgeToMDF(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), ProDeOptionsSerializer::convertToConfigFileFormat(), BEMSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToFileFormat(), ADFSerializer::convertToMDFFormat(), IDF::IDFSerializer::convertToOMFormat(), OperationSerializer::convertToXMLFormat(), BEMSerializer::convertZeroEncExtraBits(), XMLSerializer::createState(), PasteComponentCmd::Do(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToFile(), ADFSerializer::immediateSlotToMachine(), ADFSerializer::immediateSlotToMDF(), BEMSerializer::immediateSlotToOM(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), ADFSerializer::mdfPort(), ADFSerializer::mdfSRPort(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), OutputOperandDialog::onOk(), BEMSerializer::readRegisterFilePortCode(), IDF::IDFSerializer::readState(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), TTAMachine::ExecutionPipeline::saveOperandUse(), OperationPropertyDialog::saveOperation(), TTAMachine::ExecutionPipeline::saveResourceUse(), GUIOptions::saveState(), KeyboardShortcut::saveState(), ToolbarButton::saveState(), BridgeEncoding::saveState(), Encoding::saveState(), FUGuardEncoding::saveState(), FUPortCode::saveState(), GPRGuardEncoding::saveState(), GuardEncoding::saveState(), ImmediateControlField::saveState(), ImmediateEncoding::saveState(), ImmediateSlotField::saveState(), InstructionField::saveState(), InstructionFormat::saveState(), LImmDstRegisterField::saveState(), MoveSlot::saveState(), OperationTriggeredEncoding::saveState(), OperationTriggeredField::saveState(), PortCode::saveState(), SlotField::saveState(), SocketCodeTable::saveState(), SocketEncoding::saveState(), IDF::MachineImplementation::saveState(), IDF::UnitImplementationLocation::saveState(), TTAMachine::AddressSpace::saveState(), TTAMachine::BaseFUPort::saveState(), TTAMachine::BaseRegisterFile::saveState(), TTAMachine::Bridge::saveState(), TTAMachine::Bus::saveState(), TTAMachine::Connection::saveState(), TTAMachine::ControlUnit::saveState(), TTAMachine::FunctionUnit::saveState(), TTAMachine::FUPort::saveState(), TTAMachine::Guard::saveState(), TTAMachine::PortGuard::saveState(), TTAMachine::RegisterGuard::saveState(), TTAMachine::HWOperation::saveState(), TTAMachine::ImmediateUnit::saveState(), TTAMachine::Machine::saveState(), TTAMachine::Component::saveState(), TTAMachine::OperationTriggeredOperand::saveState(), TTAMachine::Port::saveState(), TTAMachine::RegisterFile::saveState(), TTAMachine::Segment::saveState(), TTAMachine::Socket::saveState(), TTAMachine::TemplateSlot::saveState(), Operand::saveState(), OperationPimpl::saveState(), ProDeOptions::saveState(), IDF::FUGenerated::saveState(), setAttribute(), setAttribute(), setAttribute(), setAttribute(), setAttribute(), ADFSerializer::setIUExtensionMode(), OperationSerializer::setOperandProperties(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), ADFSerializer::socketToMDF(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), InputOperandDialog::updateOperand(), and OperationPropertyDialog::updateSwapLists().
setAttribute() [3/6]
void ObjectState::setAttribute (const std::string & name, double value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 176 of file ObjectState.cc.
{
    string valueAsString = Conversion::toString(value);
    setAttribute(name, valueAsString);
}
References name(), setAttribute(), and Conversion::toString().
setAttribute() [4/6]
void ObjectState::setAttribute (const std::string & name, int value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 129 of file ObjectState.cc.
{
    string valueAsString = Conversion::toString(value);
    setAttribute(name, valueAsString);
}
References name(), setAttribute(), and Conversion::toString().
setAttribute() [5/6]
void ObjectState::setAttribute (const std::string & name, ULongWord value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 160 of file ObjectState.cc.
{
    string valueAsString = Conversion::toString(value);
    setAttribute(name, valueAsString);
}
References name(), setAttribute(), and Conversion::toString().
setAttribute() [6/6]
void ObjectState::setAttribute (const std::string & name, unsigned int value)
Sets an attribute.
If there is an attribute called the given name, its value is changed according to the given value. Otherwise a new attribute is created.
Parameters
name Name of the attribute.
value Value of the attribute.
Definition at line 145 of file ObjectState.cc.
{
    string valueAsString = Conversion::toString(value);
    setAttribute(name, valueAsString);
}
References name(), setAttribute(), and Conversion::toString().
setName()
void ObjectState::setName (const std::string & name)
Referenced by ADFSerializer::controlUnitToMDF(), BEMSerializer::destinationFieldToFile(), BEMSerializer::destinationFieldToOM(), OperationPropertyDialog::saveOperation(), BridgeEncoding::saveState(), DestinationField::saveState(), FUGuardEncoding::saveState(), FUPortCode::saveState(), GPRGuardEncoding::saveState(), GuardField::saveState(), ImmediateControlField::saveState(), ImmediateEncoding::saveState(), ImmediateSlotField::saveState(), IUPortCode::saveState(), LImmDstRegisterField::saveState(), MoveSlot::saveState(), NOPEncoding::saveState(), RFPortCode::saveState(), SlotField::saveState(), SocketEncoding::saveState(), SourceField::saveState(), UnconditionalGuardEncoding::saveState(), TTAMachine::BaseRegisterFile::saveState(), TTAMachine::Bridge::saveState(), TTAMachine::Bus::saveState(), TTAMachine::ControlUnit::saveState(), TTAMachine::FunctionUnit::saveState(), TTAMachine::FUPort::saveState(), TTAMachine::PortGuard::saveState(), TTAMachine::RegisterGuard::saveState(), TTAMachine::UnconditionalGuard::saveState(), TTAMachine::ImmediateSlot::saveState(), TTAMachine::ImmediateUnit::saveState(), TTAMachine::InstructionTemplate::saveState(), TTAMachine::OperationTriggeredFormat::saveState(), TTAMachine::RegisterFile::saveState(), TTAMachine::RFPort::saveState(), TTAMachine::Socket::saveState(), TTAMachine::SpecialRegisterPort::saveState(), TTAMachine::Unit::saveState(), DataDependenceEdge::saveState(), BEMSerializer::sourceFieldToFile(), and BEMSerializer::sourceFieldToOM().
setValue() [1/5]
void ObjectState::setValue (bool value)
setValue() [2/5]
void ObjectState::setValue (const std::string & value)
Referenced by IPXactModel::addAddressSpaceObject(), IPXactModel::addBusInterfaceObject(), IPXactModel::addFileObject(), IPXactModel::addModelParamsObject(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), IPXactModel::addSignalObject(), ADFSerializer::bridgeToMDF(), ADFSerializer::busToMDF(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), IDF::IDFSerializer::convertToFileFormat(), BEMSerializer::convertZeroEncExtraBits(), XMLSerializer::createState(), ADFSerializer::functionUnitToMDF(), BEMSerializer::guardFieldToFile(), BEMSerializer::immediateSlotToFile(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMDF(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), ADFSerializer::mdfFUPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), ADFSerializer::mdfPort(), ADFSerializer::mdfSRPort(), BEMSerializer::moveSlotToFile(), ADFSerializer::registerFileToMDF(), OperationPropertyDialog::saveOperation(), IPXactModel::saveState(), BinaryEncoding::saveState(), TTAMachine::AddressSpace::saveState(), TTAMachine::OperationTriggeredFormat::saveState(), OperationPimpl::saveState(), IDF::FUGenerated::saveState(), DataDependenceEdge::saveState(), BEMSerializer::slotFieldToFile(), BEMSerializer::socketCodeTableToFile(), ADFSerializer::socketToMDF(), BEMSerializer::sourceFieldToFile(), OperationSerializer::toXMLFormat(), and DataDependenceGraph::writeToXMLFile().
setValue() [3/5]
void ObjectState::setValue (double value)
setValue() [4/5]
void ObjectState::setValue (int value)
setValue() [5/5]
void ObjectState::setValue (UIntWord value)
stringAttribute()
std::string ObjectState::stringAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
Definition at line 249 of file ObjectState.cc.
{
    AttributeTable::const_iterator iter = attributes_.begin();
    while (iter != attributes_.end()) {
        if ((*iter).name == name) {
            return (*iter).value;
        }
        iter++;
    }
    string procName = "ObjectState::stringAttribute";
    string errorMsg = commonErrorMessage();
    errorMsg += "Requested attribute by name '";
    errorMsg += name;
    errorMsg += "' which doesn't exist.";
    throw KeyNotFound(__FILE__, __LINE__, procName, errorMsg);
}
References attributes_, commonErrorMessage(), name(), and ObjectState::Attribute::value.
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::addressSpaceToMDF(), TTAMachine::Bus::adjustSegmentChain(), boolAttribute(), BridgeEncoding::BridgeEncoding(), ADFSerializer::bridgeToMachine(), ADFSerializer::bridgeToMDF(), ADFSerializer::busToMachine(), ADFSerializer::busToMDF(), TTAMachine::Component::Component(), ADFSerializer::controlUnitToMachine(), ADFSerializer::controlUnitToMDF(), GUIOptionsSerializer::convertToConfigFileFormat(), IDF::IDFSerializer::convertToFileFormat(), IDF::IDFSerializer::convertToOMFormat(), ProDeOptionsSerializer::convertToOptionsObjectFormat(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), doubleAttribute(), OperationIndex::effectiveOperation(), IPXactModel::extractModelParam(), IPXactModel::extractVlnvFromAttr(), FUGuardEncoding::FUGuardEncoding(), ADFSerializer::functionUnitToMachine(), ADFSerializer::functionUnitToMDF(), FUPortCode::FUPortCode(), GPRGuardEncoding::GPRGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), TTAMachine::HWOperation::HWOperation(), BEMSerializer::immediateSlotToFile(), ADFSerializer::immediateSlotToMachine(), ADFSerializer::immediateSlotToMDF(), BEMSerializer::immediateSlotToOM(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::immediateUnitToMDF(), ADFSerializer::instructionTemplateToMachine(), ADFSerializer::instructionTemplateToMDF(), intAttribute(), BlocksModel::LoadModelFromXml(), GUIOptions::loadState(), KeyboardShortcut::loadState(), ToolbarButton::loadState(), ImmediateControlField::loadState(), ImmediateSlotField::loadState(), InstructionField::loadState(), InstructionFormat::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), OperationTriggeredEncoding::loadState(), SocketCodeTable::loadState(), IDF::MachineImplementation::loadState(), IDF::UnitImplementationLocation::loadState(), TTAMachine::Bridge::loadState(), TTAMachine::Bus::loadState(), TTAMachine::ExecutionPipeline::loadState(), TTAMachine::FunctionUnit::loadState(), TTAMachine::PortGuard::loadState(), TTAMachine::RegisterGuard::loadState(), TTAMachine::HWOperation::loadState(), TTAMachine::InstructionTemplate::loadState(), TTAMachine::Machine::loadState(), TTAMachine::Component::loadState(), TTAMachine::OperationTriggeredOperand::loadState(), TTAMachine::Port::loadState(), TTAMachine::Socket::loadState(), TTAMachine::Unit::loadState(), Operand::loadState(), OperationPimpl::loadState(), IDF::FUGenerated::loadState(), TTAMachine::Bus::loadStateWithoutReferences(), TTAMachine::ControlUnit::loadStateWithoutReferences(), TTAMachine::ImmediateUnit::loadStateWithoutReferences(), TTAMachine::Port::loadStateWithoutReferences(), TTAMachine::RegisterFile::loadStateWithoutReferences(), TTAMachine::Segment::loadStateWithoutReferences(), TTAMachine::Unit::loadStateWithoutReferences(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), ADFSerializer::mdfFUPort(), ADFSerializer::mdfOperation(), ADFSerializer::mdfPipeline(), ADFSerializer::mdfPort(), ADFSerializer::mdfSRPort(), OperationIndex::moduleOf(), ADFSerializer::momTemplateSlot(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), OperationContainer::operation(), OperationIndex::operationName(), TTAMachine::OperationTriggeredOperand::OperationTriggeredOperand(), PortCode::PortCode(), TTAMachine::Unit::portNames(), BEMSerializer::readRegisterFilePortCode(), BEMSerializer::readState(), ADFSerializer::registerFileToMachine(), ADFSerializer::registerFileToMDF(), TTAMachine::ExecutionPipeline::saveResourceUse(), GUIOptionsSerializer::setToolbarProperties(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToFile(), BEMSerializer::socketCodeTableToOM(), SocketEncoding::SocketEncoding(), ADFSerializer::socketToMachine(), ADFSerializer::socketToMDF(), BEMSerializer::sourceFieldToFile(), BEMSerializer::sourceFieldToOM(), OperationSerializer::toOperation(), OperationSerializer::toXMLFormat(), uLongAttribute(), and unsignedIntAttribute().
stringValue()
std::string ObjectState::stringValue () const
Referenced by GUIOptionsSerializer::addKeyboardShortcut(), ADFSerializer::addressSpaceToMachine(), ADFSerializer::bridgeToMachine(), ADFSerializer::busToMachine(), ADFSerializer::controlUnitToMachine(), IDF::IDFSerializer::convertToOMFormat(), XMLSerializer::createDOM(), XMLSerializer::createDOMDocument(), dumpObjectState(), IPXactModel::extractAddressSpace(), IPXactModel::extractBusInterface(), IPXactModel::extractFiles(), IPXactModel::extractModelParam(), IPXactModel::extractPortMap(), IPXactModel::extractSignals(), IPXactModel::extractVLNV(), ADFSerializer::functionUnitToMachine(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToOM(), ADFSerializer::immediateUnitToMachine(), ADFSerializer::instructionTemplateToMachine(), BinaryEncoding::loadState(), TTAMachine::OperationTriggeredFormat::loadState(), OperationPimpl::loadState(), OSEdOptions::loadState(), IDF::FUGenerated::loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmTagToOM(), ADFSerializer::machineFUPort(), ADFSerializer::machineOperation(), ADFSerializer::machinePipeline(), ADFSerializer::machineRFPort(), ADFSerializer::machineSRPort(), BEMSerializer::moveSlotToOM(), operator!=(), BEMSerializer::readRegisterFilePortCode(), ADFSerializer::registerFileToMachine(), ADFSerializer::setIUExtensionMode(), GUIOptionsSerializer::setToolbarProperties(), GUIOptionsSerializer::setWindowProperties(), BEMSerializer::slotFieldToOM(), BEMSerializer::socketCodeTableToOM(), ADFSerializer::socketToMachine(), BEMSerializer::sourceFieldToOM(), and OperationSerializer::toOperation().
UIntWordAttribute()
UIntWord ObjectState::UIntWordAttribute (const std::string & name) const
UIntWordValue()
int ObjectState::UIntWordValue () const
uLongAttribute()
ULongWord ObjectState::uLongAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
NumberFormatException If the value of the requested attribute can't be converted to int.
Definition at line 291 of file ObjectState.cc.
{
    string value = stringAttribute(name);
    return Conversion::toUnsignedLong(value);
}
References name(), stringAttribute(), and Conversion::toUnsignedLong().
Referenced by TTAMachine::AddressSpace::loadState().
unsignedIntAttribute()
unsigned int ObjectState::unsignedIntAttribute (const std::string & name) const
Returns the value of the requested attribute.
Parameters
name Name of the attribute.
Returns
Value of the requested attribute.
Exceptions
KeyNotFound If no attribute called the given name is found.
NumberFormatException If the value of the requested attribute can't be converted to unsigned int.
Definition at line 308 of file ObjectState.cc.
{
    string value = stringAttribute(name);
    return Conversion::toUnsignedInt(value);
}
References name(), stringAttribute(), and Conversion::toUnsignedInt().
unsignedIntValue()
unsigned int ObjectState::unsignedIntValue () const
Member Data Documentation
attributes_
AttributeTable ObjectState::attributes_ private
Contains all the attributes of the element.
Definition at line 146 of file ObjectState.hh.
Referenced by attribute(), hasAttribute(), operator!=(), setAttribute(), and stringAttribute().
children_
ChildTable ObjectState::children_ private
The child elements.
Definition at line 143 of file ObjectState.hh.
Referenced by addChild(), child(), childByName(), hasChild(), operator!=(), removeChild(), replaceChild(), and ~ObjectState().
name_
std::string ObjectState::name_ private
Name of the element.
Definition at line 134 of file ObjectState.hh.
Referenced by operator!=().
parent_
ObjectState* ObjectState::parent_ private
The parent element.
Definition at line 140 of file ObjectState.hh.
Referenced by addChild(), removeChild(), replaceChild(), and ~ObjectState().
value_
std::string ObjectState::value_ private
The value of a leaf element.
Definition at line 137 of file ObjectState.hh.
Referenced by operator!=().
The documentation for this class was generated from the following files:
ObjectState.hh
ObjectState.cc