OpenASIP: FUResourceConflictDetector Class Reference
FUResourceConflictDetector Class Reference
#include <FUResourceConflictDetector.hh>
Public Types
typedef int OperationID
Type for identifying operations in the conflict detector interface.
Public Member Functions
FUResourceConflictDetector ()
virtual ~FUResourceConflictDetector ()
virtual bool issueOperation (OperationID id)
virtual void endClock ()
virtual void advanceClock ()
virtual bool advanceCycle ()
virtual bool isIdle ()
virtual void reset ()
virtual OperationID operationID (const TCEString &operationName) const
Public Member Functions inherited from ClockedState
ClockedState ()
virtual ~ClockedState ()
Protected Attributes
OperationIDIndex * operationIndices_
Map for finding indices for operations quickly.
Detailed Description
Interface for classes used for detecting FU resource conflicts.
Definition at line 45 of file FUResourceConflictDetector.hh.
Member Typedef Documentation
OperationID
typedef int FUResourceConflictDetector::OperationID
Type for identifying operations in the conflict detector interface.
Definition at line 49 of file FUResourceConflictDetector.hh.
Constructor & Destructor Documentation
FUResourceConflictDetector()
FUResourceConflictDetector::FUResourceConflictDetector ()
Constructor.
Definition at line 42 of file FUResourceConflictDetector.cc.
                                                       :
    operationIndices_(new OperationIDIndex()) {
    reset();
}
References reset().
~FUResourceConflictDetector()
FUResourceConflictDetector::~FUResourceConflictDetector () virtual
Destructor.
Definition at line 50 of file FUResourceConflictDetector.cc.
{
    delete operationIndices_;
    operationIndices_ = NULL;
}
References operationIndices_.
Member Function Documentation
advanceClock()
void FUResourceConflictDetector::advanceClock () virtual
Simulates a cycle advance and reports a conflict by throwing an exception.
Implements ClockedState.
Definition at line 86 of file FUResourceConflictDetector.cc.
{
    advanceCycle();
}
References advanceCycle().
Referenced by SimulationController::simulateCycle().
advanceCycle()
bool FUResourceConflictDetector::advanceCycle () virtual
Simulates a cycle advance and reports a conflict if detected.
The default implementation always returns true, thus detects no conflicts. This interface is provided for allowing the model to update its state at the point simulation advances to the next cycle.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented in DCMFUResourceConflictDetector, FSAFUResourceConflictDetector, ReservationTableFUResourceConflictDetector, and ResourceVectorFUResourceConflictDetector.
Definition at line 78 of file FUResourceConflictDetector.cc.
{
    return true;
}
Referenced by advanceClock().
endClock()
void FUResourceConflictDetector::endClock () virtual
Called after advanceClock() has been called to all clocked states.
Implements ClockedState.
Definition at line 95 of file FUResourceConflictDetector.cc.
{
}
isIdle()
bool FUResourceConflictDetector::isIdle () virtual
Should return true in case the model needs to receive clock advance calls.
Returns
By default always returns false.
Reimplemented in FSAFUResourceConflictDetector.
Definition at line 104 of file FUResourceConflictDetector.cc.
{
    return false;
}
Referenced by SimulationController::simulateCycle().
issueOperation()
bool FUResourceConflictDetector::issueOperation (OperationID id) virtual
Issues an operation and reports a conflict if detected.
The default implementation always returns true, thus detects no conflicts.
Parameters
id The id of the operation to issue.
Returns
False in case a conflict is detected, otherwise true.
Reimplemented in DCMFUResourceConflictDetector, FSAFUResourceConflictDetector, ReservationTableFUResourceConflictDetector, and ResourceVectorFUResourceConflictDetector.
Definition at line 64 of file FUResourceConflictDetector.cc.
{
    return true;
}
Referenced by ConflictDetectingOperationExecutor::startOperation().
operationID()
FUResourceConflictDetector::OperationID FUResourceConflictDetector::operationID (const TCEString & operationName) const virtual
Returns an operation id for the given operation.
Operation IDs are used in the interface for optimizing the access. This method converts OSAL Operations to operation IDs.
Parameters
operation The OSAL Operation to find ID for.
Returns
The operation ID.
Exceptions
KeyNotFound if the operation of given name couldn't be found
Reimplemented in DCMFUResourceConflictDetector, FSAFUResourceConflictDetector, ReservationTableFUResourceConflictDetector, and ResourceVectorFUResourceConflictDetector.
Definition at line 119 of file FUResourceConflictDetector.cc.
{
    OperationIDIndex::const_iterator i =
        operationIndices_->find(StringTools::stringToLower(operationName));
    if (i == operationIndices_->end())
        throw KeyNotFound(
            __FILE__, __LINE__, __func__, "Operation not found.");
    return (*i).second;
}
References __func__, operationIndices_, and StringTools::stringToLower().
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU().
reset()
void FUResourceConflictDetector::reset () virtual
Sets the state of the detector to its initial state.
This means that the FU state is assumed to be what it is in powerup.
Reimplemented from ClockedState.
Reimplemented in DCMFUResourceConflictDetector, FSAFUResourceConflictDetector, ReservationTableFUResourceConflictDetector, and ResourceVectorFUResourceConflictDetector.
Definition at line 135 of file FUResourceConflictDetector.cc.
{
}
Referenced by FUResourceConflictDetector().
Member Data Documentation
operationIndices_
OperationIDIndex* FUResourceConflictDetector::operationIndices_ protected
Map for finding indices for operations quickly.
Definition at line 68 of file FUResourceConflictDetector.hh.
Referenced by operationID(), and ~FUResourceConflictDetector().
The documentation for this class was generated from the following files:
FUResourceConflictDetector.hh
FUResourceConflictDetector.cc