OpenASIP: ExpressionScript Class Reference
ExpressionScript Class Reference
#include <ExpressionScript.hh>
Public Member Functions
ExpressionScript (ScriptInterpreter *interpreter, std::string scriptLine)
ExpressionScript (ScriptInterpreter *interpreter, std::vector< std::string > &script)
virtual ~ExpressionScript ()
bool resultChanged ()
Public Member Functions inherited from Script
Script (ScriptInterpreter *interpreter, std::string scriptLine)
Script (ScriptInterpreter *interpreter, std::vector< std::string > &script)
virtual ~Script ()
virtual DataObject execute ()
DataObject lastResult ()
virtual std::vector< std::string > script () const
Additional Inherited Members
Protected Attributes inherited from Script
ScriptInterpreter * interpreter_
Interpreter executing the commands.
Detailed Description
ExpressionScript contains a script which changes can be inspected.
Definition at line 44 of file ExpressionScript.hh.
Constructor & Destructor Documentation
ExpressionScript() [1/2]
ExpressionScript::ExpressionScript (ScriptInterpreter * interpreter, std::string scriptLine)
Constructor.
Parameters
interpreter The interpreter for the script.
scriptLine A line of script.
Definition at line 45 of file ExpressionScript.cc.
                          : Script(interpreter, scriptLine) {
}
ExpressionScript() [2/2]
ExpressionScript::ExpressionScript (ScriptInterpreter * interpreter, std::vector< std::string > & script)
Constructor.
Parameters
interpreter The interpreter for the script.
script The script.
Definition at line 56 of file ExpressionScript.cc.
                                  : Script(interpreter, script) {
}
~ExpressionScript()
ExpressionScript::~ExpressionScript () virtual
Destructor.
Definition at line 64 of file ExpressionScript.cc.
{
}
Member Function Documentation
resultChanged()
bool ExpressionScript::resultChanged ()
Returns true, if the result of the script has changed.
Returns
True, if the result of the script has changed, otherwise false.
Exceptions
ScriptExecutionFailure If the execution of the script fails.
NumberFormatException If DataObject operation fails.
Definition at line 75 of file ExpressionScript.cc.
{
    DataObject obj;
    try {
        obj = lastResult();
    } catch (const InvalidData& i) {
        return false;
    }
    DataObject exec = execute();
    interpreter_->setResult("");
    if (obj != exec) {
        return true;
    }
    return false;
}
References Script::execute(), Script::interpreter_, Script::lastResult(), and ScriptInterpreter::setResult().
Referenced by Watch::isTriggered().
The documentation for this class was generated from the following files:
ExpressionScript.hh
ExpressionScript.cc