OpenASIP: ConditionCommand Class Reference
ConditionCommand Class Reference
#include <ConditionCommand.hh>
Public Member Functions
ConditionCommand ()
virtual ~ConditionCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "condition" command of the Simulator Control Language.
Definition at line 47 of file ConditionCommand.hh.
Constructor & Destructor Documentation
ConditionCommand()
ConditionCommand::ConditionCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 52 of file ConditionCommand.cc.
                                   :
    SimControlLanguageCommand("condition") {
}
~ConditionCommand()
ConditionCommand::~ConditionCommand () virtual
Destructor.
Does nothing.
Definition at line 61 of file ConditionCommand.cc.
{
}
Member Function Documentation
execute()
bool ConditionCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "condition" command.
Modifies conditions of breakpoints.
Parameters
arguments The handle of the breakpoint of which condition to modify.
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 75 of file ConditionCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 1, 1)) {
        return false;
    }
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    if (arguments.size() == 2) {
        if  (!checkIntegerArgument(arguments[1])) {
            return false;
        }
        const int breakpointHandle = arguments[1].integerValue();
        try {
            StopPointManager& stopPointManager =
                simulatorFrontend().stopPointManager();
            stopPointManager.stopPointWithHandleConst(breakpointHandle);
            TclConditionScript condition(NULL, "");
            if (!askConditionFromUser(condition)) {
                return false;
            }
            assert(condition.script().size() > 0);
            if (condition.script().at(0) == "1") {
                stopPointManager.removeCondition(breakpointHandle);
            } else {
                stopPointManager.setCondition(breakpointHandle, condition);
            }
            printBreakpointInfo(breakpointHandle);
        } catch (const InstanceNotFound&) {
            interpreter()->setError(
                SimulatorToolbox::textGenerator().text(
                    Texts::TXT_BREAKPOINT_NOT_FOUND).str());
            return false;
        }
    }
    return true;
}
References SimControlLanguageCommand::askConditionFromUser(), assert, CustomCommand::checkArgumentCount(), CustomCommand::checkIntegerArgument(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), CustomCommand::interpreter(), SimControlLanguageCommand::printBreakpointInfo(), StopPointManager::removeCondition(), TclConditionScript::script(), StopPointManager::setCondition(), ScriptInterpreter::setError(), SimControlLanguageCommand::simulatorFrontend(), SimulatorFrontend::stopPointManager(), StopPointManager::stopPointWithHandleConst(), SimulatorToolbox::textGenerator(), and Texts::TXT_BREAKPOINT_NOT_FOUND.
helpText()
std::string ConditionCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 128 of file ConditionCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_CONDITION).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_CONDITION.
The documentation for this class was generated from the following files:
ConditionCommand.hh
ConditionCommand.cc