OpenASIP: ProximOpenProgramCmd Class Reference
ProximOpenProgramCmd Class Reference
#include <ProximOpenProgramCmd.hh>
Public Member Functions
ProximOpenProgramCmd ()
virtual ~ProximOpenProgramCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximOpenProgramCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
virtual std::string shortName () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening program files in the Proxim.
Displays a file dialog for choosing the program file to open.
Definition at line 43 of file ProximOpenProgramCmd.hh.
Constructor & Destructor Documentation
ProximOpenProgramCmd()
ProximOpenProgramCmd::ProximOpenProgramCmd ()
The Constructor.
Definition at line 46 of file ProximOpenProgramCmd.cc.
                                          :
    GUICommand(ProximConstants::COMMAND_NAME_OPEN_PROGRAM, NULL) {
}
Referenced by create().
~ProximOpenProgramCmd()
ProximOpenProgramCmd::~ProximOpenProgramCmd () virtual
The Destructor.
Definition at line 54 of file ProximOpenProgramCmd.cc.
{
}
Member Function Documentation
create()
ProximOpenProgramCmd * ProximOpenProgramCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 111 of file ProximOpenProgramCmd.cc.
{
    return new ProximOpenProgramCmd();
}
References ProximOpenProgramCmd().
Do()
bool ProximOpenProgramCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 62 of file ProximOpenProgramCmd.cc.
{
    assert(parentWindow() != NULL);
    wxString wildcard = _T("TPEF Program Files (*.tpf, *.tpef)|*.tpf;*.tpef");
    wildcard.Append(_T("|All files|*"));
    wxFileDialog dialog(
    parentWindow(), _T("Choose a file."), _T(""), _T(""),
    wildcard, wxOPEN);
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    std::string command;
    std::string file = WxConversion::toString(dialog.GetPath());
    command = ProximConstants::SCL_LOAD_PROGRAM + " \"" + file + "\"";
    wxGetApp().simulation()->lineReader().input(command);
    return true;
}
References assert, GUICommand::parentWindow(), ProximConstants::SCL_LOAD_PROGRAM, and WxConversion::toString().
icon()
std::string ProximOpenProgramCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 91 of file ProximOpenProgramCmd.cc.
{
    return "open_program.png";
}
id()
int ProximOpenProgramCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 100 of file ProximOpenProgramCmd.cc.
{
    return ProximConstants::COMMAND_OPEN_PROGRAM;
}
References ProximConstants::COMMAND_OPEN_PROGRAM.
isEnabled()
bool ProximOpenProgramCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 122 of file ProximOpenProgramCmd.cc.
{
    return true;
}
shortName()
std::string ProximOpenProgramCmd::shortName () const virtual
Returns shortened name of the command for toolbar button text.
Returns
Short version of the command name.
Reimplemented from GUICommand.
Definition at line 133 of file ProximOpenProgramCmd.cc.
{
    return "Program";
}
The documentation for this class was generated from the following files:
ProximOpenProgramCmd.hh
ProximOpenProgramCmd.cc