OpenASIP: ResourceMapper Class Reference
ResourceMapper Class Reference
#include <ResourceMapper.hh>
Public Member Functions
ResourceMapper ()
virtual ~ResourceMapper ()
void addResourceMap (const ResourceBroker &broker)
int resourceCount (const TTAMachine::MachinePart &mp) const
SchedulingResource & resourceOf (const TTAMachine::MachinePart &mp, int index=0) const
Private Attributes
std::vector< const ResourceBroker * > brokers_
Resource brokers.
Detailed Description
Groups together the brokers managed by the resource build director and maps each resource object to corresponding machine parts.
Definition at line 51 of file ResourceMapper.hh.
Constructor & Destructor Documentation
ResourceMapper()
ResourceMapper::ResourceMapper ()
Constructor.
Definition at line 44 of file ResourceMapper.cc.
{
}
~ResourceMapper()
ResourceMapper::~ResourceMapper () virtual
Destructor.
Definition at line 50 of file ResourceMapper.cc.
{
}
Member Function Documentation
addResourceMap()
void ResourceMapper::addResourceMap (const ResourceBroker & broker)
Register broker as one of the elements that contribute to mapping a subset of machine parts to resources.
Parameters
broker Broker to register.
Definition at line 60 of file ResourceMapper.cc.
{
    if (ContainerTools::containsValue(brokers_, &broker)) {
        string msg = "Broker already exists in resource map!";
        throw ObjectAlreadyExists(__FILE__, __LINE__, __func__, msg);
    } else {
        brokers_.push_back(&broker);
    }
}
References __func__, brokers_, and ContainerTools::containsValue().
Referenced by ResourceBuildDirector::build().
resourceCount()
int ResourceMapper::resourceCount (const TTAMachine::MachinePart & mp) const
Return the number of resources that correspond to the given machine part.
Parameters
mp Machine part.
Returns
The number of resources that correspond to the given machine part.
Definition at line 76 of file ResourceMapper.cc.
{
    int count = 0;
    for (unsigned int i = 0; i < brokers_.size(); i++) {
        if (brokers_[i]->hasResourceOf(mp)) {
            count++;
        }
    }
    return count;
}
References brokers_.
Referenced by InputFUBroker::setupResourceLinks(), and OutputFUBroker::setupResourceLinks().
resourceOf()
SchedulingResource & ResourceMapper::resourceOf (const TTAMachine::MachinePart & mp, int index = 0) const
Find the resource object that corresponds to given machine part with index (default 0).
Parameters
mp Machine part to find Scheduling Resource for
index Index of machine part, in case there are several
Returns
The resource object that corresponds to given machine part and index.
Definition at line 96 of file ResourceMapper.cc.
{
    const unsigned int brokerSize = brokers_.size();
    for (unsigned int i = 0; i < brokerSize; i++) {
        SchedulingResource* res = brokers_[i]->resourceOf(mp);
        if (res != NULL) {
            if (index == 0) {
                return *res;
            } else {
                index--;
                continue;
            }
        }
    }
    std::string errMsg = "None of the brokers has resource for part ";
    const TTAMachine::Component * comp =
        dynamic_cast<const TTAMachine::Component*>(&mp);
    const TTAMachine::SubComponent * subcomp =
        dynamic_cast<const TTAMachine::SubComponent*>(&mp);
    if (comp != NULL) {
        errMsg += ": " + comp->name();
    }
    if (subcomp != NULL) {
        errMsg += ", some subcomponent";
    }
    throw KeyNotFound(__FILE__, __LINE__, __func__, errMsg);
}
References __func__, brokers_, and TTAMachine::Component::name().
Referenced by InputFUBroker::allAvailableResources(), ExecutionPipelineBroker::setupResourceLinks(), InputFUBroker::setupResourceLinks(), ITemplateBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), and OutputPSocketBroker::setupResourceLinks().
Member Data Documentation
brokers_
std::vector<const ResourceBroker*> ResourceMapper::brokers_ private
Resource brokers.
Definition at line 63 of file ResourceMapper.hh.
Referenced by addResourceMap(), resourceCount(), and resourceOf().
The documentation for this class was generated from the following files:
ResourceMapper.hh
ResourceMapper.cc