OpenASIP: ReservationTable Class Reference
ReservationTable Class Reference
#include <ReservationTable.hh>
Public Types
typedef int ResourceID
Public Member Functions
ReservationTable (const TTAMachine::FunctionUnit &fu)
ReservationTable (const TTAMachine::HWOperation &operation)
virtual ~ReservationTable ()
void init (const TTAMachine::FunctionUnit &fu)
bool conflictsWith (const ReservationTable &anotherReservationTable, int cycle) const
void issueOperation (ReservationTable &anotherReservationTable)
void advanceCycle ()
bool isReserved (ResourceID resource, int cycle) const
bool conflictsWith (const BitMatrix &another) const
Public Member Functions inherited from BitMatrix
BitMatrix (int width, int height, bool initialValue)
BitMatrix (const BitMatrix &another)
virtual ~BitMatrix ()
bool bitAt (int column, int row) const
void setBit (int column, int row, bool value)
void setAllToZero ()
void setAllToOne ()
void shiftLeft ()
void orWith (const BitMatrix &another)
bool conflictsWith (const BitMatrix &another) const
int rowCount () const
int columnCount () const
std::string toString () const
std::string toDotString () const
bool operator== (const BitMatrix &other) const
bool operator< (const BitMatrix &rightHand) const
Detailed Description
Models pipeline resources using a Conventional Reservation Table (CRT).
An efficient implementation to avoid all kinds of function overheads etc. All simulation operations can be done by calling inline methods.
Definition at line 49 of file ReservationTable.hh.
Member Typedef Documentation
ResourceID
typedef int ReservationTable::ResourceID
Definition at line 52 of file ReservationTable.hh.
Constructor & Destructor Documentation
ReservationTable() [1/2]
ReservationTable::ReservationTable (const TTAMachine::FunctionUnit & fu)
Builds an empty reservation table of given width for the given function unit.
Parameters
fu The function unit of which resources to build the reservation table of.
cycleCount The count of cycle columns.
Definition at line 51 of file ReservationTable.cc.
                                                                   :
    BitMatrix(
        fu.maxLatency(),
        fu.operationPortCount() + fu.pipelineElementCount(),
        false) {
}
ReservationTable() [2/2]
ReservationTable::ReservationTable (const TTAMachine::HWOperation & operation)
Builds a reservation table for the given operation.
Also includes empty resource rows so the reservation table is compatible with the global reservation table for the whole function unit.
Parameters
operation The operation of which resources to use.
Definition at line 66 of file ReservationTable.cc.
                                                                         :
    BitMatrix(
        operation.parentUnit()->maxLatency(),
        operation.parentUnit()->operationPortCount() +
        operation.parentUnit()->pipelineElementCount(), false) {
    const TTAMachine::FunctionUnit& fu = *operation.parentUnit();
    // First resource rows represent the input and output ports of the FU.
    for (int p = 0; p < fu.operationPortCount(); ++p) {
        for (int cycle = 0; cycle < columnCount(); ++cycle) {
            setBit(
                cycle, p, operation.pipeline()->isPortUsed(
                    *fu.operationPort(p), cycle));
        }
    }
    // Rest of the rows are pipeline resources.
    for (int r = 0; r < fu.pipelineElementCount(); ++r) {
        for (int cycle = 0; cycle < columnCount(); ++cycle) {
            setBit(
                cycle, fu.operationPortCount() + r,
                operation.pipeline()->isResourceUsed(
                    fu.pipelineElement(r)->name(), cycle));
        }
    }
}
References BitMatrix::columnCount(), TTAMachine::ExecutionPipeline::isPortUsed(), TTAMachine::ExecutionPipeline::isResourceUsed(), TTAMachine::PipelineElement::name(), TTAMachine::FunctionUnit::operationPort(), TTAMachine::FunctionUnit::operationPortCount(), TTAMachine::HWOperation::parentUnit(), TTAMachine::HWOperation::pipeline(), TTAMachine::FunctionUnit::pipelineElement(), TTAMachine::FunctionUnit::pipelineElementCount(), and BitMatrix::setBit().
~ReservationTable()
ReservationTable::~ReservationTable () virtual
Destructor.
Definition at line 96 of file ReservationTable.cc.
{
}
Member Function Documentation
advanceCycle()
void ReservationTable::advanceCycle ()
conflictsWith() [1/2]
bool BitMatrix::conflictsWith (const BitMatrix & another) const
conflictsWith() [2/2]
bool ReservationTable::conflictsWith (const ReservationTable & anotherReservationTable, int cycle) const
Referenced by CollisionMatrix::CollisionMatrix().
init()
void ReservationTable::init (const TTAMachine::FunctionUnit & fu)
isReserved()
bool ReservationTable::isReserved (ResourceID resource, int cycle) const
issueOperation()
void ReservationTable::issueOperation (ReservationTable & anotherReservationTable)
The documentation for this class was generated from the following files:
ReservationTable.hh
ReservationTable.cc