OpenASIP: OperationDAGSelector::OperationDAGList Class Reference
OperationDAGSelector::OperationDAGList Class Reference
#include <OperationDAGSelector.hh>
Public Member Functions
OperationDAG & smallestNodeCount () const
Detailed Description
STL Container for returning and finding DAGs.
Definition at line 56 of file OperationDAGSelector.hh.
Member Function Documentation
smallestNodeCount()
OperationDAG & OperationDAGSelector::OperationDAGList::smallestNodeCount () const inline
Returns DAG that had least nodes.
Returns
DAG that had least nodes.
Definition at line 64 of file OperationDAGSelector.hh.
{
            if (empty()) {
                return OperationDAG::null;
            }
            OperationDAG* leastNodes = *begin();
            for (std::vector<OperationDAG*>::const_iterator i = begin();
                 i != end(); i++) {
                if ((*i)->nodeCount() < leastNodes->nodeCount()) {
                    leastNodes = *i;
                }
            }
            return *leastNodes;
        }
References BoostGraph< GraphNode, GraphEdge >::nodeCount(), and OperationDAG::null.
Referenced by OperationDAGSelector::createExpandedDAG(), and TDGen::writeInstrInfo().
The documentation for this class was generated from the following file:
OperationDAGSelector.hh