OpenASIP: ProximSimulatorSettingsCmd Class Reference
ProximSimulatorSettingsCmd Class Reference
#include <ProximSimulatorSettingsCmd.hh>
Public Member Functions
ProximSimulatorSettingsCmd ()
virtual ~ProximSimulatorSettingsCmd ()
virtual bool Do ()
virtual bool isEnabled ()
virtual int id () const
virtual std::string icon () const
ProximSimulatorSettingsCmd * create () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening the simulator settings dialog in Proxim.
Definition at line 41 of file ProximSimulatorSettingsCmd.hh.
Constructor & Destructor Documentation
ProximSimulatorSettingsCmd()
ProximSimulatorSettingsCmd::ProximSimulatorSettingsCmd ()
The Constructor.
Definition at line 43 of file ProximSimulatorSettingsCmd.cc.
                                                      :
    GUICommand(ProximConstants::COMMAND_NAME_SIMULATOR_SETTINGS, NULL) {
}
Referenced by create().
~ProximSimulatorSettingsCmd()
ProximSimulatorSettingsCmd::~ProximSimulatorSettingsCmd () virtual
The Destructor.
Definition at line 51 of file ProximSimulatorSettingsCmd.cc.
{
}
Member Function Documentation
create()
ProximSimulatorSettingsCmd * ProximSimulatorSettingsCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 95 of file ProximSimulatorSettingsCmd.cc.
{
    return new ProximSimulatorSettingsCmd();
}
References ProximSimulatorSettingsCmd().
Do()
bool ProximSimulatorSettingsCmd::Do () virtual
Executes the command.
@retutn True, if the command was succesfully executed.
Implements GUICommand.
Definition at line 60 of file ProximSimulatorSettingsCmd.cc.
{
    wxWindow* parent = parentWindow();
    assert(parent != NULL);
    SimulatorFrontend* frontend = ProximToolbox::frontend();
    ProximLineReader& lineReader = ProximToolbox::lineReader();
    SimulatorSettingsDialog dialog(parentWindow(), -1, *frontend, lineReader);
    dialog.ShowModal();
    return true;
}
References assert, ProximToolbox::frontend(), ProximToolbox::lineReader(), and GUICommand::parentWindow().
icon()
std::string ProximSimulatorSettingsCmd::icon () const virtual
Returns path to the icon file for this command.
Implements GUICommand.
Definition at line 84 of file ProximSimulatorSettingsCmd.cc.
{
    return "configure.png";
}
id()
int ProximSimulatorSettingsCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 75 of file ProximSimulatorSettingsCmd.cc.
{
    return ProximConstants::COMMAND_SIMULATOR_SETTINGS;
}
References ProximConstants::COMMAND_SIMULATOR_SETTINGS.
isEnabled()
bool ProximSimulatorSettingsCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 106 of file ProximSimulatorSettingsCmd.cc.
{
    return true;
}
The documentation for this class was generated from the following files:
ProximSimulatorSettingsCmd.hh
ProximSimulatorSettingsCmd.cc