OpenASIP: TPEF::ASpaceElement Class Reference
TPEF::ASpaceElement Class Reference
#include <ASpaceElement.hh>
Public Member Functions
ASpaceElement ()
virtual ~ASpaceElement ()
Byte MAU () const
void setMAU (Byte aMAU)
Byte align () const
void setAlign (Byte aAlign)
Byte wordSize () const
void setWordSize (Byte aWordSize)
void setName (const ReferenceManager::SafePointer *aName)
void setName (Chunk *aName)
Chunk * name () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
Byte mau_
Minimum addressable unit.
Byte align_
Aligment.
Byte wSize_
Word size.
const ReferenceManager::SafePointer * name_
Name.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Address space element. Holds information of single address space.
Definition at line 48 of file ASpaceElement.hh.
Constructor & Destructor Documentation
ASpaceElement()
TPEF::ASpaceElement::ASpaceElement ()
Constructs empty element.
Definition at line 41 of file ASpaceElement.cc.
                             :
  mau_(0), align_(0), wSize_(0),
  name_(&ReferenceManager::SafePointer::null) {
}
~ASpaceElement()
TPEF::ASpaceElement::~ASpaceElement () virtual
Destructor.
Definition at line 50 of file ASpaceElement.cc.
{
}
Member Function Documentation
align()
Byte TPEF::ASpaceElement::align () const
Referenced by TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEFDumper::addressSpaceString(), TPEF::TPEFASpaceSectionReader::readData(), TPEFDumper::section(), TPEF::ASpaceSection::setUndefinedASpace(), and TPEF::TPEFASpaceSectionWriter::writeElement().
MAU()
Byte TPEF::ASpaceElement::MAU () const
Referenced by TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEF::DataSection::addMAU(), TPEFDumper::addressSpaceString(), TTAProgram::ProgramWriter::createDataSections(), TPEF::TPEFDataSectionWriter::elementSize(), TPEF::TPEFUDataSectionWriter::elementSize(), TPEF::TPEFRelocSectionReader::finalize(), TTAProgram::TPEFProgramFactory::findAddressSpace(), TPEF::TPEFASpaceSectionReader::readData(), TPEFDumper::section(), TPEF::ASpaceSection::setUndefinedASpace(), DataSectionCreator::writeDataLineToTPEF(), TPEF::TPEFASpaceSectionWriter::writeElement(), TPEF::DataSection::writeValue(), TPEF::LEDataSection::writeValue(), TPEF::DataSection::writeValue(), and TPEF::LEDataSection::writeValue().
name()
Chunk * TPEF::ASpaceElement::name () const
Referenced by TPEF::TPEFTools::addressSpaceName(), TTAProgram::TPEFProgramFactory::build(), TPEFDumper::section(), ProgramImageGenerator::writeDataSection(), and TPEF::TPEFASpaceSectionWriter::writeElement().
setAlign()
void TPEF::ASpaceElement::setAlign (Byte aAlign)
Referenced by TPEF::AOutReader::readData(), and TPEF::TPEFASpaceSectionReader::readData().
setMAU()
void TPEF::ASpaceElement::setMAU (Byte aMAU)
Referenced by MachineResourceManager::codeAddressSpace(), TTAProgram::ProgramWriter::createASpaceElement(), MachineResourceManager::findDataAddressSpace(), TPEF::AOutReader::readData(), and TPEF::TPEFASpaceSectionReader::readData().
setName() [1/2]
void TPEF::ASpaceElement::setName (Chunk * aName)
setName() [2/2]
void TPEF::ASpaceElement::setName (const ReferenceManager::SafePointer * aName)
Referenced by MachineResourceManager::codeAddressSpace(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::ProgramWriter::createBinary(), MachineResourceManager::findDataAddressSpace(), TPEF::AOutReader::readData(), TPEF::TPEFASpaceSectionReader::readData(), and MachineResourceManager::undefinedAddressSpace().
setWordSize()
void TPEF::ASpaceElement::setWordSize (Byte aWordSize)
Referenced by TPEF::AOutReader::readData(), and TPEF::TPEFASpaceSectionReader::readData().
wordSize()
Byte TPEF::ASpaceElement::wordSize () const
Referenced by TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEFDumper::addressSpaceString(), TPEF::TPEFASpaceSectionReader::readData(), TPEFDumper::section(), TPEF::ASpaceSection::setUndefinedASpace(), and TPEF::TPEFASpaceSectionWriter::writeElement().
Member Data Documentation
align_
Byte TPEF::ASpaceElement::align_ private
Aligment.
Definition at line 70 of file ASpaceElement.hh.
mau_
Byte TPEF::ASpaceElement::mau_ private
Minimum addressable unit.
Definition at line 68 of file ASpaceElement.hh.
name_
const ReferenceManager::SafePointer* TPEF::ASpaceElement::name_ private
Name.
Definition at line 74 of file ASpaceElement.hh.
wSize_
Byte TPEF::ASpaceElement::wSize_ private
Word size.
Definition at line 72 of file ASpaceElement.hh.
The documentation for this class was generated from the following files:
ASpaceElement.hh
ASpaceElement.cc