OpenASIP: BFDRELoop Class Reference
BFDRELoop Class Reference
#include <BFDRELoop.hh>
Public Member Functions
BFDRELoop (BF2Scheduler &sched, MoveNode &mn, int srcCycle)
bool operator() ()
void undoOnlyMe ()
bool dreAllowed ()
Public Member Functions inherited from BFKillNode
BFKillNode (BF2Scheduler &sched, MoveNode &mn)
bool operator() ()
void undoOnlyMe ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
unsigned int srcCycle_
MoveNode * prologMN_
bool createdPrologCopy_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFKillNode
DataDependenceGraph::EdgeSet createdEdges_
MoveNode & mn_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 46 of file BFDRELoop.hh.
Constructor & Destructor Documentation
BFDRELoop()
BFDRELoop::BFDRELoop (BF2Scheduler & sched, MoveNode & mn, int srcCycle) inline
Definition at line 48 of file BFDRELoop.hh.
                                                               :
        BFKillNode(sched, mn), srcCycle_(srcCycle), prologMN_(NULL),
        createdPrologCopy_(false) {}
Member Function Documentation
dreAllowed()
bool BFDRELoop::dreAllowed ()
Definition at line 107 of file BFDRELoop.cc.
{
    DataDependenceGraph::EdgeSet edges = ddg().outEdges(mn_);
    for (auto edge: edges) {
        if (edge->edgeReason() == DataDependenceEdge::EDGE_OPERATION) {
            return false;
        }
        if ((edge->edgeReason() == DataDependenceEdge::EDGE_REGISTER ||
             edge->edgeReason() ==DataDependenceEdge::EDGE_RA) &&
            edge->dependenceType() == DataDependenceEdge::DEP_RAW) {
            return false;
        }
    }
    return true;
}
References BFOptimization::ddg(), DataDependenceEdge::DEP_RAW, DataDependenceEdge::EDGE_OPERATION, DataDependenceEdge::EDGE_RA, DataDependenceEdge::EDGE_REGISTER, BFKillNode::mn_, and BoostGraph< GraphNode, GraphEdge >::outEdges().
Referenced by operator()().
operator()()
bool BFDRELoop::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 46 of file BFDRELoop.cc.
{
    if (!sched_.killDeadResults() || targetMachine().alwaysWriteResults()) {
        return false;
    }
    if (srcCycle_ < ii()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tCannot loop-dre due too early result cycle"
                  << std::endl;
#endif
        return false;
    }
    if (!dreAllowed()) {
        return false;
    }
    // Create a copy to prolog.
    auto a = duplicator().duplicateMoveNode(mn_, true, true);
    prologMN_ = a.first;
    createdPrologCopy_ = a.second;
    int prologCycle = BF2Scheduler::PROLOG_CYCLE_BIAS + srcCycle_;
    if (prologRM()->canAssign(prologCycle, *prologMN_)) {
        prologRM()->assign(prologCycle, *prologMN_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tAssigned loop-bypassed dead result to"
                  << " epilog, cycle:" << prologCycle << std::endl;
#endif
        // TODO: where to add to the epilog DDG?
        createdEdges_ = ddg().copyDepsOver(mn_, true, false);
        ddg().dropNode(mn_);
        sched_.nodeKilled(mn_);
        return true;
    } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tProlog cycle assign fail for loop-dre: "
                  << prologMN_->toString()
                  << " prolog cycle: " << prologCycle << std::endl;
#endif
        if (createdPrologCopy_) {
            duplicator().disposeMoveNode(prologMN_);
        }
        return false;
    }
}
References SimpleResourceManager::assign(), BFOptimization::canAssign(), DataDependenceGraph::copyDepsOver(), BFKillNode::createdEdges_, createdPrologCopy_, BFOptimization::ddg(), MoveNodeDuplicator::disposeMoveNode(), dreAllowed(), BoostGraph< GraphNode, GraphEdge >::dropNode(), MoveNodeDuplicator::duplicateMoveNode(), BFOptimization::duplicator(), BFOptimization::ii(), BF2Scheduler::killDeadResults(), BFKillNode::mn_, BF2Scheduler::nodeKilled(), BF2Scheduler::PROLOG_CYCLE_BIAS, prologMN_, BFOptimization::prologRM(), BFOptimization::sched_, srcCycle_, BFOptimization::targetMachine(), and MoveNode::toString().
undoOnlyMe()
void BFDRELoop::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 93 of file BFDRELoop.cc.
{
    assert(prologRM()!=NULL);
    assert(&mn_ != NULL);
    assert(prologMN_->isScheduled());
    prologRM()->unassign(*prologMN_);
    prologMoves_.erase(&mn_);
    if (createdPrologCopy_) {
        duplicator().disposeMoveNode(prologMN_);
    }
    BFKillNode::undoOnlyMe();
}
References assert, createdPrologCopy_, MoveNodeDuplicator::disposeMoveNode(), BFOptimization::duplicator(), MoveNode::isScheduled(), BFKillNode::mn_, prologMN_, BFOptimization::prologMoves_, BFOptimization::prologRM(), SimpleResourceManager::unassign(), and BFKillNode::undoOnlyMe().
Member Data Documentation
createdPrologCopy_
bool BFDRELoop::createdPrologCopy_ private
Definition at line 57 of file BFDRELoop.hh.
Referenced by operator()(), and undoOnlyMe().
prologMN_
MoveNode* BFDRELoop::prologMN_ private
Definition at line 56 of file BFDRELoop.hh.
Referenced by operator()(), and undoOnlyMe().
srcCycle_
unsigned int BFDRELoop::srcCycle_ private
Definition at line 55 of file BFDRELoop.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFDRELoop.hh
BFDRELoop.cc