OpenASIP: DisassemblyImmediate Class Reference
DisassemblyImmediate Class Reference
#include <DisassemblyImmediate.hh>
Public Member Functions
DisassemblyImmediate (SimValue value, bool signExtend)
virtual ~DisassemblyImmediate ()
virtual std::string toString () const
Public Member Functions inherited from DisassemblyElement
virtual ~DisassemblyElement ()
Private Attributes
SimValue value_
Immediate value.
bool signExtend_
The value is sign extended if set to true.
Additional Inherited Members
Protected Member Functions inherited from DisassemblyElement
DisassemblyElement ()
Detailed Description
Represents an inline immediate value in the disassembler.
Definition at line 42 of file DisassemblyImmediate.hh.
Constructor & Destructor Documentation
DisassemblyImmediate()
DisassemblyImmediate::DisassemblyImmediate (SimValue value, bool signExtend)
The constructor.
Parameters
value Inline immediate value.
Definition at line 42 of file DisassemblyImmediate.cc.
                                                                          :
    DisassemblyElement(),
    value_(value), signExtend_(signExtend) {
}
~DisassemblyImmediate()
DisassemblyImmediate::~DisassemblyImmediate () virtual
The destructor.
Definition at line 51 of file DisassemblyImmediate.cc.
{
}
Member Function Documentation
toString()
std::string DisassemblyImmediate::toString () const virtual
Returns disassembly of the inline immediate value.
Returns
Disassembly of the inline immediate value as a string.
Implements DisassemblyElement.
Definition at line 61 of file DisassemblyImmediate.cc.
{
    if (value_.width() == 0) {
        return "Invalid Immediate";
    }
    // Select the extension mode in the printout depending on the
    // move slots's (bus) extension mode. Wrong extension mode can
    // produce wrong output that cannot be assembled in case
    // of a negative-looking value on a zero extending slot.
    if (signExtend_) {
        TCEString text = Conversion::toString(value_.sLongWordValue());
        return text;
    }
    else {
        TCEString text = Conversion::toString(value_.uLongWordValue());
        return text;
    }
}
References signExtend_, SimValue::sLongWordValue(), Conversion::toString(), SimValue::uLongWordValue(), value_, and SimValue::width().
Referenced by TTAProgram::TerminalImmediate::toString(), and TTAProgram::TerminalLaneIDImmediate::toString().
Member Data Documentation
signExtend_
bool DisassemblyImmediate::signExtend_ private
The value is sign extended if set to true.
Definition at line 51 of file DisassemblyImmediate.hh.
Referenced by toString().
value_
SimValue DisassemblyImmediate::value_ private
Immediate value.
Definition at line 49 of file DisassemblyImmediate.hh.
Referenced by toString().
The documentation for this class was generated from the following files:
DisassemblyImmediate.hh
DisassemblyImmediate.cc