OpenASIP: TPEF::AOutReader::Header Class Reference
TPEF::AOutReader::Header Class Reference
#include <AOutReader.hh>
Classes
struct HeaderRawData
This structure holds the sizes of every section in bytes.
Public Member Functions
Header ()
Header class.
virtual ~Header ()
void setSectionSizeData (Word size)
void setSectionSizeUData (Word size)
void setSectionSizeText (Word size)
void setSectionSizeSymbol (Word size)
void setSectionSizeTextReloc (Word size)
void setSectionSizeDataReloc (Word size)
void setSectionSizeString (Word size)
Word sectionSizeData () const
Word sectionSizeUData () const
Word sectionSizeText () const
Word sectionSizeSymbol () const
Word sectionSizeTextReloc () const
Word sectionSizeDataReloc () const
Word sectionSizeString () const
Private Attributes
struct TPEF::AOutReader::Header::HeaderRawData sizes_
Detailed Description
Stores the data of a.out file header.
Definition at line 157 of file AOutReader.hh.
Constructor & Destructor Documentation
Header()
TPEF::AOutReader::Header::Header ()
Header class.
Constructor
Definition at line 410 of file AOutReader.cc.
{
}
~Header()
TPEF::AOutReader::Header::~Header () virtual
Destructor
Definition at line 417 of file AOutReader.cc.
{
}
Member Function Documentation
sectionSizeData()
Word TPEF::AOutReader::Header::sectionSizeData () const
Referenced by TPEF::AOutReader::readData(), and TPEF::AOutReader::readHeader().
sectionSizeDataReloc()
Word TPEF::AOutReader::Header::sectionSizeDataReloc () const
Referenced by TPEF::AOutReader::readData(), TPEF::AOutRelocationSectionReader::readData(), and TPEF::AOutReader::readHeader().
sectionSizeString()
Word TPEF::AOutReader::Header::sectionSizeString () const
Referenced by TPEF::AOutReader::readData().
sectionSizeSymbol()
Word TPEF::AOutReader::Header::sectionSizeSymbol () const
Referenced by TPEF::AOutReader::readData(), TPEF::AOutSymbolSectionReader::readData(), and TPEF::AOutReader::readHeader().
sectionSizeText()
Word TPEF::AOutReader::Header::sectionSizeText () const
Referenced by TPEF::AOutSymbolSectionReader::initializeSymbol(), TPEF::AOutReader::readData(), TPEF::AOutTextSectionReader::readData(), and TPEF::AOutReader::readHeader().
sectionSizeTextReloc()
Word TPEF::AOutReader::Header::sectionSizeTextReloc () const
Referenced by TPEF::AOutReader::readData(), TPEF::AOutRelocationSectionReader::readData(), and TPEF::AOutReader::readHeader().
sectionSizeUData()
Word TPEF::AOutReader::Header::sectionSizeUData () const
Referenced by TPEF::AOutReader::readData().
setSectionSizeData()
void TPEF::AOutReader::Header::setSectionSizeData (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeDataReloc()
void TPEF::AOutReader::Header::setSectionSizeDataReloc (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeString()
void TPEF::AOutReader::Header::setSectionSizeString (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeSymbol()
void TPEF::AOutReader::Header::setSectionSizeSymbol (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeText()
void TPEF::AOutReader::Header::setSectionSizeText (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeTextReloc()
void TPEF::AOutReader::Header::setSectionSizeTextReloc (Word size)
Referenced by TPEF::AOutReader::readHeader().
setSectionSizeUData()
void TPEF::AOutReader::Header::setSectionSizeUData (Word size)
Referenced by TPEF::AOutReader::readHeader().
Member Data Documentation
sizes_
struct TPEF::AOutReader::Header::HeaderRawData TPEF::AOutReader::Header::sizes_ private
The documentation for this class was generated from the following files:
AOutReader.hh
AOutReader.cc