OpenASIP: ClearDisassemblyHighlightCmd Class Reference
ClearDisassemblyHighlightCmd Class Reference
#include <ClearDisassemblyHighlightCmd.hh>
Public Member Functions
ClearDisassemblyHighlightCmd ()
virtual ~ClearDisassemblyHighlightCmd ()
virtual bool Do ()
virtual int id () const
virtual ClearDisassemblyHighlightCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for clearing disassembly window highlighting mode.
Definition at line 41 of file ClearDisassemblyHighlightCmd.hh.
Constructor & Destructor Documentation
ClearDisassemblyHighlightCmd()
ClearDisassemblyHighlightCmd::ClearDisassemblyHighlightCmd ()
The Constructor.
Definition at line 43 of file ClearDisassemblyHighlightCmd.cc.
                                                          :
    GUICommand("Clear Disassembly highlight", NULL) {
    }
Referenced by create().
~ClearDisassemblyHighlightCmd()
ClearDisassemblyHighlightCmd::~ClearDisassemblyHighlightCmd () virtual
The Destructor.
Definition at line 51 of file ClearDisassemblyHighlightCmd.cc.
{
}
Member Function Documentation
create()
ClearDisassemblyHighlightCmd * ClearDisassemblyHighlightCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 94 of file ClearDisassemblyHighlightCmd.cc.
{
    return new ClearDisassemblyHighlightCmd();
}
References ClearDisassemblyHighlightCmd().
Do()
bool ClearDisassemblyHighlightCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 59 of file ClearDisassemblyHighlightCmd.cc.
{
    ProximDisassemblyWindow* window = ProximToolbox::disassemblyWindow();
    assert(window != NULL);
    window->setMoveAttrProvider(NULL);
    window->Refresh();
    return true;
}
References assert, ProximToolbox::disassemblyWindow(), and ProximDisassemblyWindow::setMoveAttrProvider().
icon()
std::string ClearDisassemblyHighlightCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 74 of file ClearDisassemblyHighlightCmd.cc.
{
    return "clear_console.png";
}
id()
int ClearDisassemblyHighlightCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 83 of file ClearDisassemblyHighlightCmd.cc.
{
    return ProximConstants::COMMAND_CLEAR_DISASSEMBLY_HIGHLIGHT;
}
References ProximConstants::COMMAND_CLEAR_DISASSEMBLY_HIGHLIGHT.
isEnabled()
bool ClearDisassemblyHighlightCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
True if the console window exists.
Implements GUICommand.
Definition at line 105 of file ClearDisassemblyHighlightCmd.cc.
{
    if (ProximToolbox::frontend()->isProgramLoaded()) {
    return true;
    } else {
    return false;
    }
}
References ProximToolbox::frontend().
The documentation for this class was generated from the following files:
ClearDisassemblyHighlightCmd.hh
ClearDisassemblyHighlightCmd.cc