OpenASIP: OSEdTreeView Class Reference
OSEdTreeView Class Reference
#include <OSEdTreeView.hh>
Public Member Functions
OSEdTreeView (wxWindow *parent, OSEdInfoView *infoView)
virtual ~OSEdTreeView ()
Operation * selectedOperation ()
wxTreeItemId selectedOperationId ()
std::string moduleOfOperation (wxTreeItemId id)
wxTreeItemId moduleIdOfOperation (wxTreeItemId id)
std::string pathOfModule (wxTreeItemId id)
wxTreeItemId pathIdOfModule (wxTreeItemId id)
std::string selectedPath ()
wxTreeItemId selectedPathId ()
wxTreeItemId selectedModuleId ()
std::string selectedModule ()
OSEdInfoView * infoView () const
std::vector< std::string > constructTree ()
void addItem (wxTreeItemId parent, std::string item)
void changeText (wxTreeItemId id, const std::string &text)
void removeItem (wxTreeItemId id)
void update ()
bool isPathSelected () const
bool isModuleSelected () const
bool isOperationSelected () const
Private Types
typedef std::map< std::string, wxTreeItemId >::value_type ValType
Value type for the map.
typedef std::map< std::string, wxTreeItemId >::iterator Iter
Iterators for the maps.
typedef std::multimap< std::string, wxTreeItemId >::iterator IterM
Private Member Functions
OSEdTreeView (const OSEdTreeView &)
Copying not allowed.
OSEdTreeView & operator= (const OSEdTreeView &)
Assignment not allowed.
bool isPath (wxTreeItemId id) const
bool isModule (wxTreeItemId id) const
bool isOperation (wxTreeItemId id) const
void onItemClicked (wxTreeEvent &event)
void onDropDownMenu (wxMouseEvent &event)
void onItemSelected (wxTreeEvent &event)
Private Attributes
OSEdInfoView * infoView_
An info window controlled by tree view.
std::map< std::string, wxTreeItemId > paths_
Paths of the operation data base.
std::multimap< std::string, wxTreeItemId > modules_
Modules of the operation data base.
std::multimap< std::string, wxTreeItemId > operations_
Operations of operation data base.
Detailed Description
Models a tree view of the operation data base.
Shows a tree-like structure of search paths, operation modules, and operations.
Definition at line 54 of file OSEdTreeView.hh.
Member Typedef Documentation
Iter
typedef std::map<std::string,wxTreeItemId>::iterator OSEdTreeView::Iter private
Iterators for the maps.
Definition at line 85 of file OSEdTreeView.hh.
IterM
typedef std::multimap<std::string,wxTreeItemId>::iterator OSEdTreeView::IterM private
Definition at line 86 of file OSEdTreeView.hh.
ValType
typedef std::map<std::string,wxTreeItemId>::value_type OSEdTreeView::ValType private
Value type for the map.
Definition at line 83 of file OSEdTreeView.hh.
Constructor & Destructor Documentation
OSEdTreeView() [1/2]
OSEdTreeView::OSEdTreeView (wxWindow * parent, OSEdInfoView * infoView)
Constructor.
Parameters
parent. Parent window.
infoView Info view controlled by tree view.
Definition at line 71 of file OSEdTreeView.cc.
                                                                   :
    wxTreeCtrl(parent, OSEdConstants::CMD_TREE_ITEM), infoView_(infoView) {
}
~OSEdTreeView()
OSEdTreeView::~OSEdTreeView () virtual
Destructor.
Definition at line 78 of file OSEdTreeView.cc.
{
}
OSEdTreeView() [2/2]
OSEdTreeView::OSEdTreeView (const OSEdTreeView &) private
Copying not allowed.
Member Function Documentation
addItem()
void OSEdTreeView::addItem (wxTreeItemId parent, std::string item)
Adds an item to the tree.
Parameters
parent Parent id.
item The item to be added.
Definition at line 573 of file OSEdTreeView.cc.
{
    wxTreeItemId id = AppendItem(parent, WxConversion::toWxString(item));
    if (isPath(parent)) {
        modules_.insert(std::pair<std::string, wxTreeItemId>(item, id));
    } else if (isModule(parent)) {
        operations_.insert(std::pair<std::string, wxTreeItemId>(item, id));
        //operations_[item] = id;
    } else {
        assert(false);
    }
}
References assert, isModule(), isPath(), modules_, operations_, and WxConversion::toWxString().
Referenced by OSEdAddModuleCmd::Do(), and OSEdAddOperationCmd::Do().
changeText()
void OSEdTreeView::changeText (wxTreeItemId id, const std::string & text)
Changes the text of the item.
Parameters
id Id of the item to be changed.
text New label.
Definition at line 592 of file OSEdTreeView.cc.
{
    if (isOperation(id)) {
        string key = MapTools::keyForValue<string>(operations_, id);
        Iter it = operations_.find(key);
        operations_.erase(it);
        operations_.insert(std::pair<std::string, wxTreeItemId>(text, id));
        //operations_[text] = id;
    } else if (isModule(id)) {
        string key = MapTools::keyForValue<string>(modules_, id);
        IterM it = modules_.find(key);
        modules_.erase(it);
        modules_.insert(std::pair<std::string, wxTreeItemId>(text, id));
    } else if (isPath(id)) {
        string key = MapTools::keyForValue<string>(paths_, id);
        Iter it = paths_.find(key);
        paths_.erase(it);
        paths_[text] = id;
    }
    SetItemText(id, WxConversion::toWxString(text));
}
References isModule(), isOperation(), isPath(), MapTools::keyForValue(), modules_, operations_, paths_, and WxConversion::toWxString().
Referenced by OSEdPropertiesCmd::Do().
constructTree()
vector< string > OSEdTreeView::constructTree ()
Constructs the tree structure.
If errors occurs while constructing the tree structure, the error messages are collected and returned.
Returns
Results of erronous modules.
Definition at line 90 of file OSEdTreeView.cc.
{
    vector<string> results;
    OperationIndex& opIndex = OperationContainer::operationIndex();
    OperationSerializer& serializer =
        OperationContainer::operationSerializer();
    wxTreeItemId root = AddRoot(_T("root"));
    vector<string> paths = Environment::osalPaths();
    for (size_t i = 0; i < paths.size(); i++) {
        // add path
        string pathName = paths[i];
        wxTreeItemId path =
            AppendItem(root, WxConversion::toWxString(pathName));
        if (FileSystem::fileExists(pathName)) {
            SetItemBold(path);
        }
        paths_[pathName] = path;
        int modules = 0;
        try {
            modules = opIndex.moduleCount(pathName);
        } catch (const PathNotFound& p) {
            // no modules in this path
            continue;
        }
        for (int j = 0; j < modules; j++) {
            // add module
            OperationModule& mod = opIndex.module(j, pathName);
            wxTreeItemId module =
                AppendItem(path, WxConversion::toWxString(mod.name()));
            modules_.insert(std::pair<std::string, wxTreeItemId>(mod.name(), module));
            int operations = 0;
            // test that operation properties can be loaded
            try {
                operations = opIndex.operationCount(mod);
                serializer.setSourceFile(mod.propertiesModule());
                ObjectState* tree = serializer.readState();
                if (tree->childCount() > 0) {
                    Operation temp("", NullOperationBehavior::instance());
                    temp.loadState(tree->child(0));
                }
                delete tree;
            } catch (const Exception& e) {
                results.push_back(mod.propertiesModule() + ":\n");
                results.push_back(e.errorMessage() + "\n");
                results.push_back("\n");
            }
            for (int k = 0; k < operations; k++) {
                // add operation
                string opName = opIndex.operationName(k, mod);
                wxTreeItemId oper =
                    AppendItem(module, WxConversion::toWxString(opName));
                //operations_[opIndex.operationName(k, mod)] = oper;
                operations_.insert(std::pair<std::string, wxTreeItemId>(opIndex.operationName(k, mod), oper));
            }
            SortChildren(module);
        }
        SortChildren(path);
    }
    infoView_->pathView();
    return results;
}
References ObjectState::child(), ObjectState::childCount(), Exception::errorMessage(), FileSystem::fileExists(), infoView_, NullOperationBehavior::instance(), Operation::loadState(), OperationIndex::module(), OperationIndex::moduleCount(), modules_, OperationModule::name(), OperationIndex::operationCount(), OperationContainer::operationIndex(), OperationIndex::operationName(), operations_, OperationContainer::operationSerializer(), Environment::osalPaths(), paths_, OSEdInfoView::pathView(), OperationModule::propertiesModule(), OperationSerializer::readState(), OperationSerializer::setSourceFile(), and WxConversion::toWxString().
Referenced by OSEd::OnInit().
infoView()
OSEdInfoView * OSEdTreeView::infoView () const
Returns pointer to info view.
Returns
Pointer to info view.
Definition at line 662 of file OSEdTreeView.cc.
{
    return infoView_;
}
References infoView_.
Referenced by OSEdRemoveModuleCmd::Do(), and OSEdRemoveOperationCmd::Do().
isModule()
bool OSEdTreeView::isModule (wxTreeItemId id) const private
Returns true if tree node with given id is a module.
Parameters
id Id of the tree node.
Returns
True if id is a module.
Definition at line 305 of file OSEdTreeView.cc.
{
    return MapTools::containsValue(modules_, id);
}
References MapTools::containsValue(), and modules_.
Referenced by addItem(), changeText(), onDropDownMenu(), onItemSelected(), and removeItem().
isModuleSelected()
bool OSEdTreeView::isModuleSelected () const
Returns true if a module is selected.
Returns
True, if a module is selected.
Definition at line 731 of file OSEdTreeView.cc.
{
    if (MapTools::containsValue(modules_, GetSelection()) ||
        infoView_->selectedModule() != "") {
        return true;
    }
    return false;
}
References MapTools::containsValue(), infoView_, modules_, and OSEdInfoView::selectedModule().
Referenced by OSEdRemoveModuleCmd::isEnabled().
isOperation()
bool OSEdTreeView::isOperation (wxTreeItemId id) const private
Return true if tree node with given id is an operation.
Parameters
id Id of the tree node.
Returns
True if id is an operation.
Definition at line 316 of file OSEdTreeView.cc.
{
    return MapTools::containsValue(operations_, id);
}
References MapTools::containsValue(), and operations_.
Referenced by changeText(), onDropDownMenu(), onItemClicked(), onItemSelected(), and removeItem().
isOperationSelected()
bool OSEdTreeView::isOperationSelected () const
Returns true if an operation is selected.
Returns
True, if an operation is selected.
Definition at line 745 of file OSEdTreeView.cc.
{
    if (MapTools::containsValue(operations_, GetSelection()) ||
        infoView_->selectedOperation() != "") {
        return true;
    }
    return false;
}
References MapTools::containsValue(), infoView_, operations_, and OSEdInfoView::selectedOperation().
Referenced by OSEdModifyBehaviorCmd::isEnabled(), OSEdRemoveOperationCmd::isEnabled(), and OSEdSimulateCmd::isEnabled().
isPath()
bool OSEdTreeView::isPath (wxTreeItemId id) const private
Returns true if tree node with given id is a path.
Parameters
id Id of the tree node.
Returns
True if id is a path.
Definition at line 294 of file OSEdTreeView.cc.
{
    return MapTools::containsValue(paths_, id);
}
References MapTools::containsValue(), and paths_.
Referenced by addItem(), changeText(), onDropDownMenu(), onItemSelected(), and removeItem().
isPathSelected()
bool OSEdTreeView::isPathSelected () const
Returns true if a path is selected.
Returns
True, if a path is selected.
Definition at line 716 of file OSEdTreeView.cc.
{
    if (MapTools::containsValue(paths_, GetSelection()) ||
        infoView_->selectedPath() != "") {
        return true;
    }
    return false;
}
References MapTools::containsValue(), infoView_, paths_, and OSEdInfoView::selectedPath().
moduleIdOfOperation()
wxTreeItemId OSEdTreeView::moduleIdOfOperation (wxTreeItemId id)
Returns the id of the module of the operation with a given id.
Parameters
id The id of the operation.
Returns
The id of the module.
Definition at line 420 of file OSEdTreeView.cc.
{
    return GetItemParent(id);
}
Referenced by OSEdModifyBehaviorCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), OSEdModifyBehaviorCmd::isEnabled(), and OSEdRemoveOperationCmd::isEnabled().
moduleOfOperation()
string OSEdTreeView::moduleOfOperation (wxTreeItemId id)
Returns the module of an operation with a given id.
Parameters
id The id of operation.
Returns
The name of the module.
Definition at line 407 of file OSEdTreeView.cc.
{
    wxTreeItemId modId = GetItemParent(id);
    string moduleName = MapTools::keyForValue<string>(modules_, modId);
    return moduleName;
}
References MapTools::keyForValue(), and modules_.
Referenced by OSEdModifyBehaviorCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), OSEdModifyBehaviorCmd::isEnabled(), and onItemSelected().
onDropDownMenu()
void OSEdTreeView::onDropDownMenu (wxMouseEvent & event) private
Handles the event when right mouse button is clicked.
A different drop down menu is showed, depending on where mouse button is clicked.
Parameters
event Event to be handled.
Definition at line 243 of file OSEdTreeView.cc.
{
    // coordinates of mouse click
    OSEdTextGenerator& text = OSEdTextGenerator::instance();
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    wxPoint pos = event.GetPosition();
    int flags = wxTREE_HITTEST_ONITEMLABEL;
    wxTreeItemId id = HitTest(pos, flags);
    // mouse is not clicked on a tree item
    if (!id.IsOk()) {
        return;
    }
    SelectItem(id);
    DropDownMenu* menu = NULL;
    if (isPath(id)) {
        format fmt = text.text(OSEdTextGenerator::TXT_STATUS_PATH_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        menu = new DropDownMenu(DropDownMenu::MENU_PATH);
        PopupMenu(menu, pos);
    } else if (isModule(id)) {
        format fmt = text.text(OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        menu = new DropDownMenu(DropDownMenu::MENU_MODULE);
        PopupMenu(menu, pos);
    } else if (isOperation(id)) {
        format fmt =
            text.text(OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        menu = new DropDownMenu(DropDownMenu::MENU_OPERATION);
        PopupMenu(menu, pos);
    } else {
        mainFrame->statusBar()->SetStatusText(_T("Cannot open"));
    }
    delete menu;
}
References OSEdTextGenerator::instance(), isModule(), isOperation(), isPath(), DropDownMenu::MENU_MODULE, DropDownMenu::MENU_OPERATION, DropDownMenu::MENU_PATH, OSEdMainFrame::statusBar(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED, OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED, and OSEdTextGenerator::TXT_STATUS_PATH_SELECTED.
onItemClicked()
void OSEdTreeView::onItemClicked (wxTreeEvent & event) private
Handles the event when item is selected on tree by double-clicking with mouse.
Double clicking an operation opens an operation property dialog, where operation properties can be modified.
Parameters
event Event to be handled.
Definition at line 220 of file OSEdTreeView.cc.
{
    wxTreeItemId id = event.GetItem();
    if (isOperation(id)) {
        // operation is clicked, lets open the property dialog
        OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
        CommandRegistry* registry = mainFrame->registry();
        GUICommand* command =
            registry->createCommand(OSEdConstants::CMD_PROPERTIES);
        command->setParentWindow(mainFrame);
        command->Do();
        delete command;
    }
}
References OSEdConstants::CMD_PROPERTIES, CommandRegistry::createCommand(), GUICommand::Do(), isOperation(), OSEdMainFrame::registry(), and GUICommand::setParentWindow().
onItemSelected()
void OSEdTreeView::onItemSelected (wxTreeEvent & event) private
Handles the event when item is selected on tree.
If selected item is a path, path view is shown. If selected item is a module, module view is shown. If selected item is an operation, operation view is shown.
Parameters
event The event to be handled.
Definition at line 171 of file OSEdTreeView.cc.
{
    OSEdMainFrame* mainFrame = wxGetApp().mainFrame();
    OSEdTextGenerator& text = OSEdTextGenerator::instance();
    wxTreeItemId id = event.GetItem();
    if (isPath(id)) {
        string path = MapTools::keyForValue<string>(paths_, id);
        format fmt = text.text(OSEdTextGenerator::TXT_STATUS_PATH_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        infoView_->moduleView(path);
    } else if (isModule(id)) {
        string moduleName = MapTools::keyForValue<string>(modules_, id);
        format fmt = text.text(OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        string pathName = pathOfModule(id);
        infoView_->operationView(pathName, moduleName);
    } else if (isOperation(id)) {
        string opName = MapTools::keyForValue<string>(operations_, id);
        format fmt =
            text.text(OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED);
        mainFrame->statusBar()->
            SetStatusText(WxConversion::toWxString(fmt.str()));
        string modName = moduleOfOperation(id);
        string pathName = pathOfModule(GetItemParent(id));
        infoView_->operationPropertyView(opName, modName, pathName);
    } else {
        mainFrame->statusBar()->SetStatusText(_T(""));
        // root is selected
        infoView_->pathView();
    }
    wxGetApp().mainFrame()->updateMenuBar();
}
References infoView_, OSEdTextGenerator::instance(), isModule(), isOperation(), isPath(), MapTools::keyForValue(), moduleOfOperation(), modules_, OSEdInfoView::moduleView(), OSEdInfoView::operationPropertyView(), operations_, OSEdInfoView::operationView(), pathOfModule(), paths_, OSEdInfoView::pathView(), OSEdMainFrame::statusBar(), Texts::TextGenerator::text(), WxConversion::toWxString(), OSEdTextGenerator::TXT_STATUS_MODULE_SELECTED, OSEdTextGenerator::TXT_STATUS_OPERATION_SELECTED, and OSEdTextGenerator::TXT_STATUS_PATH_SELECTED.
operator=()
OSEdTreeView & OSEdTreeView::operator= (const OSEdTreeView &) private
Assignment not allowed.
pathIdOfModule()
wxTreeItemId OSEdTreeView::pathIdOfModule (wxTreeItemId id)
Returns the id of the path in which module with given id belongs to.
Parameters
id Id of the module.
Returns
The id of the path.
Definition at line 444 of file OSEdTreeView.cc.
{
    return GetItemParent(id);
}
pathOfModule()
string OSEdTreeView::pathOfModule (wxTreeItemId id)
Returns the path of the module with given id.
Parameters
id The id of the module.
Returns
The name of the path.
Definition at line 431 of file OSEdTreeView.cc.
{
    wxTreeItemId pathId = GetItemParent(id);
    std::string path = MapTools::keyForValue<string>(paths_, pathId);
    return path;
}
References MapTools::keyForValue(), and paths_.
Referenced by OSEdAddOperationCmd::Do(), OSEdBuildCmd::Do(), OSEdModifyBehaviorCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveModuleCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), OSEdAddOperationCmd::isEnabled(), OSEdBuildCmd::isEnabled(), OSEdModifyBehaviorCmd::isEnabled(), OSEdRemoveModuleCmd::isEnabled(), OSEdRemoveOperationCmd::isEnabled(), onItemSelected(), and selectedOperation().
removeItem()
void OSEdTreeView::removeItem (wxTreeItemId id)
Removes an item from the tree view.
Collapses the parent and set the parent selected.
Parameters
id The id of the item to be removed.
Definition at line 622 of file OSEdTreeView.cc.
{
    wxTreeItemId parent = GetItemParent(id);
    Collapse(parent);
    SelectItem(parent);
    DeleteChildren(id);
    Delete(id);
    // remove the item from the inner data structure also
    if (isOperation(id)) {
        string key = MapTools::keyForValue<string>(operations_, id);
        Iter it = operations_.find(key);
        operations_.erase(it);
    } else if (isModule(id)) {
        string key = MapTools::keyForValue<string>(modules_, id);
        IterM it = modules_.find(key);
        modules_.erase(it);
        Iter ot = operations_.begin();
        while (ot != operations_.end()) {
            if (GetItemParent((*ot).second) == id) {
                Iter next = ot;
                next++;
                operations_.erase(ot);
                ot = next;
            } else {
                ot++;
            }
        }
    } else if (isPath(id)) {
        // paths can not be erased
        assert(false);
    }
}
References assert, isModule(), isOperation(), isPath(), MapTools::keyForValue(), modules_, and operations_.
Referenced by OSEdRemoveModuleCmd::Do(), and OSEdRemoveOperationCmd::Do().
selectedModule()
string OSEdTreeView::selectedModule ()
Returns the selected module.
If no module is selected, an empty string is returned.
Returns
The selected module or an empty string.
Definition at line 513 of file OSEdTreeView.cc.
{
    IterM it = modules_.begin();
    // first look from the tree view
    while (it != modules_.end()) {
        if (IsSelected((*it).second)) {
            return (*it).first;
        }
        it++;
    }
    // then look from the info view
    string module = infoView_->selectedModule();
    return module;
}
References modules_.
Referenced by OSEdAddOperationCmd::Do(), OSEdBuildCmd::Do(), OSEdRemoveModuleCmd::Do(), OSEdAddOperationCmd::isEnabled(), OSEdBuildCmd::isEnabled(), and selectedOperation().
selectedModuleId()
wxTreeItemId OSEdTreeView::selectedModuleId ()
Returns the id of selected module.
Exceptions
NotAvailable If no module is selected.
Returns
The id of selected module.
Definition at line 537 of file OSEdTreeView.cc.
{
    if (MapTools::containsValue(modules_, GetSelection())) {
        return GetSelection();
    }
    IterM it = modules_.begin();
    // first search the selected module from tree view
    while (it != modules_.end()) {
        if (IsSelected((*it).second)) {
            return (*it).second;
        }
        it++;
    }
    // no module in tree view selected, look from the info view
    string module = infoView_->selectedModule();
    if (module != "") {
        try {
            it = modules_.find(module);
            wxTreeItemId id = it->second;
            return id;
        } catch (const KeyNotFound& k) {
            assert(false);
        }
    }
    throw NotAvailable(__FILE__, __LINE__, __func__);
}
References __func__, assert, MapTools::containsValue(), and modules_.
Referenced by OSEdAddOperationCmd::Do(), OSEdBuildCmd::Do(), OSEdRemoveModuleCmd::Do(), OSEdAddOperationCmd::isEnabled(), OSEdBuildCmd::isEnabled(), OSEdRemoveModuleCmd::isEnabled(), and selectedOperation().
selectedOperation()
Operation * OSEdTreeView::selectedOperation ()
Returns the selected operation.
If no operation is selected, NULL is returned.
Returns
The selected operation.
Definition at line 328 of file OSEdTreeView.cc.
{
    Iter it = operations_.begin();
    string opName = "";
    string modName = "";
    string pathName = "";
    // get the name of the selected operation, its module and its path.
    while(it != operations_.end()) {
        if (IsSelected((*it).second)) {
            opName = (*it).first;
            wxTreeItemId opId = (*it).second;
            wxTreeItemId moduleId = GetItemParent(opId);
            wxTreeItemId pathId = GetItemParent(moduleId);
            modName = WxConversion::toString(GetItemText(moduleId));
            pathName = WxConversion::toString(GetItemText(pathId));
            break;
        }
        it++;
    }
    // if no operation was selected in a tree view, let's look from
    // the info view
    if (opName == "") {
        opName = infoView_->selectedOperation();
        if (opName == "") {
            return NULL;
        } else {
            modName = selectedModule();
            assert(modName != "");
            pathName = pathOfModule(selectedModuleId());
            assert(pathName != "");
        }
    }
    Operation* op = OperationContainer::operation(pathName, modName, opName);
    return op;
}
References assert, infoView_, OperationContainer::operation(), operations_, pathOfModule(), selectedModule(), selectedModuleId(), OSEdInfoView::selectedOperation(), and WxConversion::toString().
Referenced by OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), OSEdPropertiesCmd::isEnabled(), and OSEdSimulateCmd::isEnabled().
selectedOperationId()
wxTreeItemId OSEdTreeView::selectedOperationId ()
Returns the id of selected operation.
Exceptions
NotAvailable If no operation is selected.
Returns
The id of selected operation.
Definition at line 379 of file OSEdTreeView.cc.
{
    Iter it = operations_.begin();
    // first look from the tree view
    while (it != operations_.end()) {
        if (IsSelected((*it).second)) {
            return (*it).second;
        }
        it++;
    }
    string name = infoView_->selectedOperation();
    it = operations_.begin();
    while (it != operations_.end()) {
        if ((*it).first == name) {
            return (*it).second;
        }
        it++;
    }
    throw NotAvailable(__FILE__, __LINE__, __func__);
}
References __func__, infoView_, operations_, and OSEdInfoView::selectedOperation().
Referenced by OSEdModifyBehaviorCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), OSEdModifyBehaviorCmd::isEnabled(), and OSEdRemoveOperationCmd::isEnabled().
selectedPath()
string OSEdTreeView::selectedPath ()
Returns the selected path.
If not path is selected, an empty string is returned.
Returns
The selected path, or an empty string.
Definition at line 456 of file OSEdTreeView.cc.
{
    Iter it = paths_.begin();
    // first look from the tree view
    while (it != paths_.end()) {
        if (IsSelected((*it).second)) {
            return (*it).first;
        }
        it++;
    }
    // then info view
    string path = infoView_->selectedPath();
    return path;
}
References infoView_, paths_, and OSEdInfoView::selectedPath().
Referenced by OSEdAddModuleCmd::Do(), and OSEdAddModuleCmd::isEnabled().
selectedPathId()
wxTreeItemId OSEdTreeView::selectedPathId ()
Returns the id of selected path.
Exceptions
NotAvailable If path is not selected.
Returns
Id of selected path.
Definition at line 480 of file OSEdTreeView.cc.
{
    Iter it = paths_.begin();
    // first look from the tree view
    while (it != paths_.end()) {
        if (IsSelected((*it).second)) {
            return (*it).second;
        }
        it++;
    }
    // then look from the info view
    string path = infoView_->selectedPath();
    if (path != "") {
        try {
            wxTreeItemId id = paths_[path];
            return id;
        } catch (const KeyNotFound& k) {
            assert(false);
        }
    }
    throw NotAvailable(__FILE__, __LINE__, __func__);
}
References __func__, assert, infoView_, paths_, and OSEdInfoView::selectedPath().
Referenced by OSEdAddModuleCmd::Do().
update()
void OSEdTreeView::update ()
Updates the treeview.
Definition at line 670 of file OSEdTreeView.cc.
                     {
    Iter it = paths_.begin();
    while (it != paths_.end()) {
        if (IsSelected((*it).second)) {
            infoView_->moduleView((*it).first);
            return;
        }
        it++;
    }
    IterM itm = modules_.begin();
    while (itm != modules_.end()) {
        if (IsSelected((*itm).second)) {
            wxTreeItemId pathId = GetItemParent((*itm).second);
            string pathName = WxConversion::toString(GetItemText(pathId));
            infoView_->operationView(pathName, (*itm).first);
            return;
        }
        itm++;
    }
    it = operations_.begin();
    while (it != operations_.end()) {
        if (IsSelected((*it).second)) {
            wxTreeItemId modId = GetItemParent((*it).second);
            wxTreeItemId pathId = GetItemParent(modId);
            string modName = WxConversion::toString(GetItemText(modId));
            string pathName = WxConversion::toString(GetItemText(pathId));
            infoView_->operationPropertyView((*it).first, modName, pathName);
            return;
        }
        it++;
    }
    infoView_->pathView();
}
References infoView_, modules_, OSEdInfoView::moduleView(), OSEdInfoView::operationPropertyView(), operations_, OSEdInfoView::operationView(), paths_, OSEdInfoView::pathView(), and WxConversion::toString().
Referenced by OSEdAddModuleCmd::Do(), OSEdAddOperationCmd::Do(), and OSEdPropertiesCmd::Do().
Member Data Documentation
infoView_
OSEdInfoView* OSEdTreeView::infoView_ private
An info window controlled by tree view.
Definition at line 102 of file OSEdTreeView.hh.
Referenced by constructTree(), infoView(), isModuleSelected(), isOperationSelected(), isPathSelected(), onItemSelected(), selectedOperation(), selectedOperationId(), selectedPath(), selectedPathId(), and update().
modules_
std::multimap<std::string, wxTreeItemId> OSEdTreeView::modules_ private
Modules of the operation data base.
Definition at line 106 of file OSEdTreeView.hh.
Referenced by addItem(), changeText(), constructTree(), isModule(), isModuleSelected(), moduleOfOperation(), onItemSelected(), removeItem(), selectedModule(), selectedModuleId(), and update().
operations_
std::multimap<std::string, wxTreeItemId> OSEdTreeView::operations_ private
Operations of operation data base.
Definition at line 108 of file OSEdTreeView.hh.
Referenced by addItem(), changeText(), constructTree(), isOperation(), isOperationSelected(), onItemSelected(), removeItem(), selectedOperation(), selectedOperationId(), and update().
paths_
std::map<std::string, wxTreeItemId> OSEdTreeView::paths_ private
Paths of the operation data base.
Definition at line 104 of file OSEdTreeView.hh.
Referenced by changeText(), constructTree(), isPath(), isPathSelected(), onItemSelected(), pathOfModule(), selectedPath(), selectedPathId(), and update().
The documentation for this class was generated from the following files:
OSEdTreeView.hh
OSEdTreeView.cc