OpenASIP: HDLGenerator::If Class Reference
HDLGenerator::If Class Reference
#include <HDLGenerator.hh>
Public Member Functions
template<typename SS >
If (LHSValue cls, SS ifBlock)
template<typename SS >
void elseIfClause (LHSValue cls, SS ifBlock)
template<typename SS >
void elseClause (SS elseBlock)
virtual void hdl (std::ostream &stream, Language lang, int level) override
void build () override
Public Member Functions inherited from HDLGenerator::SequentialStatement
SequentialStatement (std::string name)
Public Member Functions inherited from HDLGenerator::Generatable
Generatable (std::string name)
virtual ~Generatable ()=default
virtual void reads (const std::string &var)
virtual void reads (const LHSValue &var)
virtual void writes (const std::string &var)
virtual Register & getRegister (const std::string &var)
virtual bool hasOption (const std::string &var)
virtual bool isRegister (const std::string &name)
virtual bool isVariable (const std::string &name)
virtual bool isConstant (const std::string &name)
virtual Width width (const std::string &name)
int integerWidth (const std::string &name)
virtual WireType wireType (const std::string &name)
virtual Width width ()
virtual WireType wireType () const
virtual void hdl (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang)
virtual void implementAll (std::ostream &stream, Language lang, int indent)
template<typename Func >
void forAll (Func func)
template<typename Type , typename Func >
void forAll (Func func)
template<class Type >
bool parentIs ()
template<class Type >
Type * parentType ()
void pushComponent (std::shared_ptr< Generatable > c)
template<class Component >
void addComponent (Component c)
const std::string & name () const noexcept
void setParent (Generatable *parent) noexcept
Generatable * parent () const noexcept
Private Attributes
std::vector< std::pair< LHSValue, std::shared_ptr< SequentialStatement > > > ifBlocks_
std::shared_ptr< SequentialStatement > elseBlock_
Detailed Description
if/elsif/else.
Definition at line 787 of file HDLGenerator.hh.
Constructor & Destructor Documentation
If()
template<typename SS > HDLGenerator::If::If (LHSValue cls, SS ifBlock) inline
Definition at line 790 of file HDLGenerator.hh.
                                     : SequentialStatement("if"),
            elseBlock_(nullptr) {
            std::shared_ptr<SequentialStatement> ptr
                = std::make_shared<SS>(ifBlock);
            ifBlocks_.emplace_back(cls, ptr);
        }
References ifBlocks_.
Member Function Documentation
build()
void HDLGenerator::If::build () inline override virtual
Reimplemented from HDLGenerator::Generatable.
Definition at line 855 of file HDLGenerator.hh.
{
            Generatable::build();
            for (auto&& block : ifBlocks_) {
                reads(block.first);
                block.second->setParent(this);
                block.second->build();
            }
            if (elseBlock_ != nullptr) {
                elseBlock_->setParent(this);
                elseBlock_->build();
            }
        }
References HDLGenerator::Generatable::build(), elseBlock_, ifBlocks_, and HDLGenerator::Generatable::reads().
elseClause()
template<typename SS > void HDLGenerator::If::elseClause (SS elseBlock) inline
Definition at line 805 of file HDLGenerator.hh.
{
            if (elseBlock_) {
                throw std::runtime_error("Cannot to add a second else block.");
            }
            std::shared_ptr<SequentialStatement> ptr
                = std::make_shared<SS>(elseBlock);
            elseBlock_ = ptr;
        }
References elseBlock_.
Referenced by FUGen::createOutputPipeline(), and FUGen::createShadowRegisters().
elseIfClause()
template<typename SS > void HDLGenerator::If::elseIfClause (LHSValue cls, SS ifBlock) inline
Definition at line 798 of file HDLGenerator.hh.
{
            std::shared_ptr<SequentialStatement> ptr
                = std::make_shared<SS>(ifBlock);
            ifBlocks_.emplace_back(cls, ptr);
        }
References ifBlocks_.
Referenced by FUGen::createOutputPipeline().
hdl()
virtual void HDLGenerator::If::hdl (std::ostream & stream, Language lang, int level) inline override virtual
Reimplemented from HDLGenerator::SequentialStatement.
Definition at line 814 of file HDLGenerator.hh.
{
            if (lang == Language::VHDL) {
                for (auto iter = ifBlocks_.begin(); iter != ifBlocks_.end();
                     ++iter) {
                    if (iter == ifBlocks_.begin()) {
                        stream << StringTools::indent(level) << "if ";
                    } else {
                        stream << StringTools::indent(level) << "elsif ";
                    }
                    iter->first.hdl(stream, lang);
                    stream << " then\n";
                    iter->second->hdl(stream, lang, level + 1);
                }
                if (elseBlock_ != nullptr) {
                    stream << StringTools::indent(level) << "else\n";
                    elseBlock_->hdl(stream, lang, level + 1);
                }
                stream << StringTools::indent(level) << "end if;\n";
            } else if (lang == Language::Verilog) {
                for (auto iter = ifBlocks_.begin(); iter != ifBlocks_.end();
                     ++iter) {
                    if (iter == ifBlocks_.begin()) {
                        stream << StringTools::indent(level) << "if ";
                    } else {
                        stream << StringTools::indent(level) << "end else if ";
                    }
                    iter->first.hdl(stream, lang);
                    stream << ") begin\n";
                    iter->second->hdl(stream, lang, level + 1);
                }
                if (elseBlock_ != nullptr) {
                    stream << StringTools::indent(level) << "end else begin\n";
                    elseBlock_->hdl(stream, lang, level + 1);
                }
                stream << StringTools::indent(level) << "end\n";
            } else {
                throw std::runtime_error(__PRETTY_FUNCTION__);
            }
        }
References elseBlock_, ifBlocks_, StringTools::indent(), HDLGenerator::Verilog, and HDLGenerator::VHDL.
Member Data Documentation
elseBlock_
std::shared_ptr<SequentialStatement> HDLGenerator::If::elseBlock_ private
Definition at line 871 of file HDLGenerator.hh.
Referenced by build(), elseClause(), and hdl().
ifBlocks_
std::vector<std::pair<LHSValue,std::shared_ptr<SequentialStatement> > > HDLGenerator::If::ifBlocks_ private
Definition at line 870 of file HDLGenerator.hh.
Referenced by build(), elseIfClause(), hdl(), and If().
The documentation for this class was generated from the following file:
HDLGenerator.hh