OpenASIP: BaseLineReader Class Reference
BaseLineReader Class Reference
#include <BaseLineReader.hh>
Public Member Functions
BaseLineReader (std::istream &iStream=std::cin, std::ostream &oStream=std::cout)
virtual ~BaseLineReader ()
virtual void initialize (std::string defPrompt="", FILE *in=stdin, FILE *out=stdout, FILE *err=stderr)
virtual void setPromptPrinting (bool flag)
virtual std::string readLine (std::string prompt="")
virtual char charQuestion (std::string question, std::string allowedChars, bool caseSensitive=false, char defaultAnswer='\0')
Public Member Functions inherited from LineReader
LineReader (std::istream &iStream=std::cin, std::ostream &oStream=std::cout)
virtual ~LineReader ()
virtual std::ostream & outputStream ()
bool confirmation (std::string question, char defaultAnswer='n', char yesChar='y', char noChar='n')
virtual void setSaveInputHistoryToFile (bool flag)
virtual bool saveInputHistoryToFile () const
virtual void setInputHistoryLog (const std::string &historyFilename)
virtual void setInputHistoryLength (std::size_t length)
virtual size_t inputHistoryMaxLength () const
virtual std::size_t inputsInHistory () const
virtual std::string inputHistoryEntry (std::size_t age) const
Private Member Functions
BaseLineReader (const BaseLineReader &)
Copying not allowed.
BaseLineReader & operator= (const BaseLineReader &)
Assignment not allowed.
void printPrompt () const
Private Attributes
std::string prompt_
Prompt of the reader.
FILE * in_
Input stream.
FILE * out_
Output stream.
FILE * error_
Error stream.
std::istream & iStream_
Input stream.
std::ostream & oStream_
Output stream.
bool promptPrinting_
Prompt printing flag.
Static Private Attributes
static const int MAX_LINE_LENGTH = 256
Additional Inherited Members
Protected Member Functions inherited from LineReader
void setInitialized ()
bool initialized () const
void putInInputHistory (const std::string &inputLine)
Detailed Description
Handles the basic line reading without a use of any fancy libraries.
This LineReader is used only when nothing else is available. This LineReader supports only reading from std::cin and outputing to std::cout.
Definition at line 47 of file BaseLineReader.hh.
Constructor & Destructor Documentation
BaseLineReader() [1/2]
BaseLineReader::BaseLineReader (std::istream & iStream = std::cin, std::ostream & oStream = std::cout)
Constructor.
Definition at line 45 of file BaseLineReader.cc.
                                                                       :
    LineReader(iStream, oStream), iStream_(iStream), oStream_(oStream),
    promptPrinting_(true) {
}
~BaseLineReader()
BaseLineReader::~BaseLineReader () virtual
Destructor.
Definition at line 53 of file BaseLineReader.cc.
{
}
BaseLineReader() [2/2]
BaseLineReader::BaseLineReader (const BaseLineReader &) private
Copying not allowed.
Member Function Documentation
charQuestion()
char BaseLineReader::charQuestion (std::string question, std::string allowedChars, bool caseSensitive = false, char defaultAnswer = '\0') virtual
User is asked a question, and answer is excepted to be one character.
Parameters
question Question to be asked.
allowedChars Chars allowed in answer.
caseSensitive If true answer is treated case sensitive.
defaultAnswer Default answer for the question.
Returns
The answered character.
Exceptions
ObjectNotInitialized If LineReader is not initialized.
Implements LineReader.
Definition at line 132 of file BaseLineReader.cc.
{
    if (!initialized()) {
        std::string method = "BaseLineReader::charQuestion()";
        std::string msg = "LineReader not initialized.";
        throw ObjectNotInitialized(__FILE__, __LINE__, method, msg);
    }
    std::string origPrompt = prompt_;
    prompt_ = question;
    printPrompt();
    char answer;
    if (defaultAnswer == '\0') {
        // default answer not given
        do {
            iStream_ >> answer;
        } while (!StringTools::containsChar(
                     allowedChars, answer, caseSensitive) &&
                 !iStream_.eof() && !iStream_.fail());
        prompt_ = origPrompt;
        return answer;
    } else {
        // default answer given
        iStream_ >> answer;
        if (!StringTools::containsChar(allowedChars, answer, caseSensitive)) {
            prompt_ = origPrompt;
            return defaultAnswer;
        } else {
            prompt_ = origPrompt;
            return answer;
        }
    }
    assert(false);
    return '!';
}
References assert, StringTools::containsChar(), LineReader::initialized(), iStream_, printPrompt(), and prompt_.
initialize()
void BaseLineReader::initialize (std::string prompt = "", FILE * in = stdin, FILE * out = stdout, FILE * err = stderr) virtual
Initializes the reader.
Parameters
prompt Prompt for the reader.
in Input stream. Not used, input is always cin.
out Output stream. Not used, output is always cout.
err Error stream. Not used, error output is always cerr.
Implements LineReader.
Definition at line 65 of file BaseLineReader.cc.
           {
    prompt_ = prompt;
    setInitialized();
}
References prompt_, and LineReader::setInitialized().
Referenced by DesignSpaceExplorer::simulate().
operator=()
BaseLineReader & BaseLineReader::operator= (const BaseLineReader &) private
Assignment not allowed.
printPrompt()
void BaseLineReader::printPrompt () const private
Prints the prompt.
Definition at line 177 of file BaseLineReader.cc.
{
    oStream_ << prompt_;
}
References oStream_, and prompt_.
Referenced by charQuestion(), and readLine().
readLine()
std::string BaseLineReader::readLine (std::string prompt = "") virtual
Reads a line from the input stream.
Parameters
prompt The prompt to be used.
Returns
The read string.
Exceptions
ObjectNotInitialized If LineReader is not initialized.
EndOfFile When end of file mark is received.
Todo:
Implement detection of end-of-file.
Implements LineReader.
Definition at line 96 of file BaseLineReader.cc.
{
    if (!initialized()) {
        std::string msg = "LineReader not initialized.";
        throw ObjectNotInitialized(__FILE__, __LINE__, __func__, msg);
    }
    std::string origPrompt = prompt_;
    prompt_ = prompt;
    if (promptPrinting_)
        printPrompt();
    std::string result;
    getline(iStream_, result);
    prompt_ = origPrompt;
    if (iStream_.eof() || iStream_.fail()) {
        std::string msg =
            "End of file from input stream or input stream in bad state.";
        throw EndOfFile(__FILE__, __LINE__, __func__, msg);
    }
    return result;
}
References __func__, LineReader::initialized(), iStream_, printPrompt(), prompt_, and promptPrinting_.
Referenced by DesignSpaceExplorer::simulate().
setPromptPrinting()
void BaseLineReader::setPromptPrinting (bool flag) virtual
Disables/enables printing of prompt altogether.
Parameters
flag
Definition at line 82 of file BaseLineReader.cc.
{
    promptPrinting_ = flag;
}
References promptPrinting_.
Referenced by DesignSpaceExplorer::simulate().
Member Data Documentation
error_
FILE* BaseLineReader::error_ private
Error stream.
Definition at line 84 of file BaseLineReader.hh.
in_
FILE* BaseLineReader::in_ private
Input stream.
Definition at line 80 of file BaseLineReader.hh.
iStream_
std::istream& BaseLineReader::iStream_ private
Input stream.
Definition at line 86 of file BaseLineReader.hh.
Referenced by charQuestion(), and readLine().
MAX_LINE_LENGTH
const int BaseLineReader::MAX_LINE_LENGTH = 256 static private
Definition at line 75 of file BaseLineReader.hh.
oStream_
std::ostream& BaseLineReader::oStream_ private
Output stream.
Definition at line 88 of file BaseLineReader.hh.
Referenced by printPrompt().
out_
FILE* BaseLineReader::out_ private
Output stream.
Definition at line 82 of file BaseLineReader.hh.
prompt_
std::string BaseLineReader::prompt_ private
Prompt of the reader.
Definition at line 78 of file BaseLineReader.hh.
Referenced by charQuestion(), initialize(), printPrompt(), and readLine().
promptPrinting_
bool BaseLineReader::promptPrinting_ private
Prompt printing flag.
Definition at line 90 of file BaseLineReader.hh.
Referenced by readLine(), and setPromptPrinting().
The documentation for this class was generated from the following files:
BaseLineReader.hh
BaseLineReader.cc