OpenASIP: SchedulingResource Class Reference
SchedulingResource Class Reference abstract
#include <SchedulingResource.hh>
Public Member Functions
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual bool isInUse (const int cycle) const =0
virtual bool isAvailable (const int cycle) const =0
virtual bool canAssign (const int cycle, const MoveNode &node) const =0
virtual void assign (const int cycle, MoveNode &node)=0
virtual void unassign (const int cycle, MoveNode &node)=0
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isInputFUResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual bool operator< (const SchedulingResource &other) const
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups ()
virtual bool validateRelatedGroups ()
Protected Attributes
int initiationInterval_
Private Types
typedef std::vector< SchedulingResource * > SchedulingResourceVector
typedef std::vector< SchedulingResourceVector > SchedulingResourceGroup
typedef std::set< const SchedulingResource * > SchedulingResourceSet
Private Member Functions
SchedulingResource (const SchedulingResource &)
SchedulingResource & operator= (const SchedulingResource &)
Private Attributes
SchedulingResourceGroup relatedResourceGroup_
SchedulingResourceGroup dependentResourceGroup_
std::string name_
SchedulingResourceSet relatedResourceSet_
int useCount_
Friends
class ResourceBroker
Detailed Description
An interface for scheduling resources of Resource Model The base class SchedulingResource
Definition at line 52 of file SchedulingResource.hh.
Member Typedef Documentation
SchedulingResourceGroup
typedef std::vector<SchedulingResourceVector> SchedulingResource::SchedulingResourceGroup private
Definition at line 138 of file SchedulingResource.hh.
SchedulingResourceSet
typedef std::set<const SchedulingResource*> SchedulingResource::SchedulingResourceSet private
Definition at line 151 of file SchedulingResource.hh.
SchedulingResourceVector
typedef std::vector<SchedulingResource*> SchedulingResource::SchedulingResourceVector private
Definition at line 136 of file SchedulingResource.hh.
Constructor & Destructor Documentation
~SchedulingResource()
SchedulingResource::~SchedulingResource () virtual
Destructor.
Definition at line 43 of file SchedulingResource.cc.
{
}
SchedulingResource() [1/2]
SchedulingResource::SchedulingResource (const std::string & name, const unsigned int ii = 0)
Constructor.
Parameters
name Name of resource.
Definition at line 51 of file SchedulingResource.cc.
                                                                                   :
    initiationInterval_(ii), name_(name), useCount_(0) {
}
SchedulingResource() [2/2]
SchedulingResource::SchedulingResource (const SchedulingResource &) private
Member Function Documentation
addToDependentGroup()
void SchedulingResource::addToDependentGroup (const int group, SchedulingResource & resource) virtual
Add resource to group of dependent resources.
Parameters
group Group to which resource add.
resource Resource to add to group.
Definition at line 101 of file SchedulingResource.cc.
{
    if (group >= dependentResourceGroupCount()) {
        dependentResourceGroup_.resize(group+1);
    }
    dependentResourceGroup_.at(group).push_back(&resource);
}
References dependentResourceGroup_, and dependentResourceGroupCount().
Referenced by InputFUBroker::setupResourceLinks(), ITemplateBroker::setupResourceLinks(), and OutputFUBroker::setupResourceLinks().
addToRelatedGroup()
void SchedulingResource::addToRelatedGroup (const int group, SchedulingResource & resource) virtual
Add resource to group of related resources.
Parameters
group Group to which resource add.
resource Resource to add to group.
Definition at line 82 of file SchedulingResource.cc.
{
    relatedResourceSet_.insert(&resource);
    if (group >= relatedResourceGroupCount()) {
        relatedResourceGroup_.resize(group+1);
    }
    relatedResourceGroup_.at(group).push_back(&resource);
}
References relatedResourceGroup_, relatedResourceGroupCount(), and relatedResourceSet_.
Referenced by BusBroker::setupResourceLinks(), ExecutionPipelineBroker::setupResourceLinks(), InputPSocketBroker::setupResourceLinks(), IUBroker::setupResourceLinks(), and OutputPSocketBroker::setupResourceLinks().
assign()
virtual void SchedulingResource::assign (const int cycle, MoveNode & node) pure virtual
Implemented in BusResource, ExecutionPipelineResource, FUResource, InputFUResource, ITemplateResource, IUResource, OutputFUResource, OutputPSocketResource, and PSocketResource.
Referenced by InputPSocketBroker::assign(), and OutputPSocketBroker::assign().
canAssign()
virtual bool SchedulingResource::canAssign (const int cycle, const MoveNode & node) const pure virtual
Implemented in BusResource, ExecutionPipelineResource, FUResource, InputFUResource, InputPSocketResource, ITemplateResource, OutputFUResource, OutputPSocketResource, PSocketResource, and IUResource.
Referenced by InputPSocketBroker::allAvailableResources(), OutputPSocketBroker::allAvailableResources(), ResourceBroker::availableResource(), ResourceBroker::isAnyResourceAvailable(), and OutputPSocketBroker::isAnyResourceAvailable().
clear()
void SchedulingResource::clear () virtual
Clears bookkeeping of the scheduling resource.
After this call the state of the resource should be identical to a newly-created and initialized resource.
Reimplemented in BusResource, ExecutionPipelineResource, ITemplateResource, IUResource, OutputPSocketResource, and PSocketResource.
Definition at line 397 of file SchedulingResource.cc.
{
    useCount_ = 0;
}
References useCount_.
Referenced by BusResource::clear(), ExecutionPipelineResource::clear(), ITemplateResource::clear(), IUResource::clear(), and PSocketResource::clear().
decreaseUseCount()
void SchedulingResource::decreaseUseCount () virtual
Decrease use count of Schedulign Resource by 1
Definition at line 364 of file SchedulingResource.cc.
{
    useCount_--;
}
References useCount_.
Referenced by InputFUResource::unassign(), OutputFUResource::unassign(), and PSocketResource::unassign().
dependentResource()
SchedulingResource & SchedulingResource::dependentResource (const int group, const int index) const virtual
Return dependent resource from group with position.
Parameters
group Group from which to return resource.
index Index of resource in particular group.
Returns
Reference to SchedulingResource [group][index].
Exceptions
OutOfRange When group or index requested does not exist.
Definition at line 158 of file SchedulingResource.cc.
{
    if (group < dependentResourceGroupCount()) {
        if (index < dependentResourceCount(group)) {
            return *dependentResourceGroup_.at(group).at(index);
        } else {
            std::string msg = "Requested dependent resource [";
            msg += Conversion::toString(index);
            msg += "] does not exists";
            msg += " in group [";
            msg += Conversion::toString(group);
            msg += "] of ";
            msg += name();
            msg += ". Group count is: ";
            msg += Conversion::toString(dependentResourceGroupCount());
            msg += ".";
            throw OutOfRange(__FILE__, __LINE__, __func__, msg);
        }
    } else {
        std::string msg = "Requested dependent resource group ";
        msg += Conversion::toString(group);
        msg += " does not exists in ";
        msg += name();
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, dependentResourceCount(), dependentResourceGroup_, dependentResourceGroupCount(), name(), and Conversion::toString().
Referenced by InputFUResource::assign(), OutputFUResource::assign(), InputFUResource::canAssign(), OutputFUResource::canAssign(), hasDependentResource(), FUResource::isAvailable(), InputFUResource::isAvailable(), FUResource::isInUse(), InputFUResource::isInUse(), FUResource::operator<(), InputFUResource::unassign(), OutputFUResource::unassign(), InputFUResource::validateDependentGroups(), ITemplateResource::validateDependentGroups(), and OutputFUResource::validateDependentGroups().
dependentResourceCount()
int SchedulingResource::dependentResourceCount (const int group) const inline
Referenced by InputFUResource::assign(), OutputFUResource::assign(), InputFUResource::canAssign(), OutputFUResource::canAssign(), dependentResource(), hasDependentResource(), FUResource::isAvailable(), InputFUResource::isAvailable(), FUResource::isInUse(), InputFUResource::isInUse(), FUResource::operator<(), InputFUResource::unassign(), OutputFUResource::unassign(), InputFUResource::validateDependentGroups(), InputPSocketResource::validateDependentGroups(), ITemplateResource::validateDependentGroups(), OutputFUResource::validateDependentGroups(), and OutputPSocketResource::validateDependentGroups().
dependentResourceGroupCount()
int SchedulingResource::dependentResourceGroupCount () const virtual
Return number of groups of dependent resources.
Returns
Number of groups of dependent resources.
Definition at line 71 of file SchedulingResource.cc.
{
    return dependentResourceGroup_.size();
}
References dependentResourceGroup_.
Referenced by addToDependentGroup(), InputFUResource::assign(), OutputFUResource::assign(), InputFUResource::canAssign(), OutputFUResource::canAssign(), dependentResource(), hasDependentResource(), FUResource::isAvailable(), InputFUResource::isAvailable(), FUResource::isInUse(), InputFUResource::isInUse(), InputFUResource::unassign(), OutputFUResource::unassign(), InputFUResource::validateDependentGroups(), InputPSocketResource::validateDependentGroups(), ITemplateResource::validateDependentGroups(), OutputFUResource::validateDependentGroups(), and OutputPSocketResource::validateDependentGroups().
hasDependentResource()
bool SchedulingResource::hasDependentResource (const SchedulingResource & sResource) const virtual
Return true if resource contains given dependent resource.
Parameters
sResource Resource to test.
Returns
True if resource contains given dependent resource.
Definition at line 207 of file SchedulingResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount();i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).name() == sResource.name()) {
                return true;
            }
        }
    }
    return false;
}
References dependentResource(), dependentResourceCount(), dependentResourceGroupCount(), and name().
Referenced by InputFUResource::canAssign().
hasRelatedResource()
bool SchedulingResource::hasRelatedResource (const SchedulingResource & sResource) const virtual
Return true if resource contains given related resource.
Parameters
sResource Resource to test.
Returns
True if resource contains given related resource.
Definition at line 194 of file SchedulingResource.cc.
{
    return relatedResourceSet_.find(&sResource) !=
        relatedResourceSet_.end();
}
References relatedResourceSet_.
Referenced by BusResource::canAssign(), and BusResource::isAvailable().
increaseUseCount()
void SchedulingResource::increaseUseCount () virtual
Increases use count of Scheduling Resource by 1
Definition at line 355 of file SchedulingResource.cc.
{
    useCount_++;
}
References useCount_.
Referenced by BusResource::assign(), InputFUResource::assign(), OutputFUResource::assign(), and PSocketResource::assign().
initiationInterval()
int SchedulingResource::initiationInterval () const
Get initiation interval, if ii = 0 then initiation interval is not used.
Returns
initiation interval
Definition at line 385 of file SchedulingResource.cc.
{
    return initiationInterval_;
}
References initiationInterval_.
Referenced by ExecutionPipelineResource::operandAllowedAtCycle(), and ExecutionPipelineResource::resourcesAllowTrigger().
instructionIndex()
int SchedulingResource::instructionIndex (int cycle) const inline
Referenced by ITemplateResource::assign(), BusResource::assign(), OutputPSocketResource::assign(), PSocketResource::assign(), ExecutionPipelineResource::assignDestination(), ExecutionPipelineResource::assignSource(), OutputPSocketResource::canAssign(), IUResource::canAssign(), IUResource::canAssignUse(), ExecutionPipelineResource::checkOperandAllowed(), ExecutionPipelineResource::cyclesOverlap(), IUResource::findAvailable(), ExecutionPipelineResource::hasConflictingResultsOnCycle(), ExecutionPipelineResource::isAvailable(), PSocketResource::isAvailable(), IUResource::isAvailable(), BusResource::isInUse(), ExecutionPipelineResource::isInUse(), ITemplateResource::isInUse(), IUResource::isInUse(), PSocketResource::isInUse(), ExecutionPipelineResource::nextResultCycle(), ExecutionPipelineResource::operandAllowedAtCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::operandPossibleAtCycle(), ExecutionPipelineResource::operandSharePreventsTriggerForScheduledResult(), ExecutionPipelineResource::otherTriggerBeforeMyTrigger(), ExecutionPipelineResource::resourcesAllowTrigger(), ExecutionPipelineResource::resultAllowedAtCycle(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultNotOverWritten(), ExecutionPipelineResource::setOperandUsed(), ExecutionPipelineResource::setResultWriten(), ITemplateResource::unassign(), BusResource::unassign(), OutputPSocketResource::unassign(), PSocketResource::unassign(), ExecutionPipelineResource::unassignDestination(), ExecutionPipelineResource::unassignSource(), ExecutionPipelineResource::unsetOperandUsed(), and ExecutionPipelineResource::unsetResultWriten().
isAvailable()
virtual bool SchedulingResource::isAvailable (const int cycle) const pure virtual
Implemented in BusResource, ExecutionPipelineResource, FUResource, InputFUResource, ITemplateResource, IUResource, OutputPSocketResource, and PSocketResource.
Referenced by ResourceBroker::availableResource(), ResourceBroker::isAnyResourceAvailable(), FUResource::isAvailable(), and InputFUResource::isAvailable().
isBusResource()
virtual bool SchedulingResource::isBusResource () const virtual
Reimplemented in BusResource.
Referenced by ITemplateResource::validateDependentGroups(), ShortImmPSocketResource::validateRelatedGroups(), InputPSocketResource::validateRelatedGroups(), and OutputPSocketResource::validateRelatedGroups().
isExecutionPipelineResource()
virtual bool SchedulingResource::isExecutionPipelineResource () const virtual
Reimplemented in ExecutionPipelineResource.
Referenced by InputFUResource::assign(), OutputFUResource::assign(), InputFUResource::canAssign(), OutputFUResource::canAssign(), InputFUResource::isAvailable(), InputFUResource::isInUse(), InputFUBroker::setupResourceLinks(), OutputFUBroker::setupResourceLinks(), InputFUResource::unassign(), OutputFUResource::unassign(), InputFUResource::validateDependentGroups(), and OutputFUResource::validateDependentGroups().
isInputFUResource()
virtual bool SchedulingResource::isInputFUResource () const virtual
Reimplemented in InputFUResource.
Referenced by InputFUBroker::allAvailableResources(), and InputPSocketResource::validateRelatedGroups().
isInputPSocketResource()
virtual bool SchedulingResource::isInputPSocketResource () const virtual
Reimplemented in InputPSocketResource.
Referenced by BusResource::canAssign(), FUResource::isAvailable(), InputFUResource::validateDependentGroups(), OutputFUResource::validateDependentGroups(), BusResource::validateRelatedGroups(), ExecutionPipelineResource::validateRelatedGroups(), and IUResource::validateRelatedGroups().
isInUse()
virtual bool SchedulingResource::isInUse (const int cycle) const pure virtual
Implemented in BusResource, ExecutionPipelineResource, FUResource, InputFUResource, ITemplateResource, IUResource, and PSocketResource.
Referenced by IUResource::canAssign(), IUResource::canAssignUse(), InputPSocketBroker::isAlreadyAssigned(), ITemplateBroker::isAlreadyAssigned(), OutputPSocketBroker::isAlreadyAssigned(), FUResource::isInUse(), and InputFUResource::isInUse().
isITemplateResource()
virtual bool SchedulingResource::isITemplateResource () const virtual
Reimplemented in ITemplateResource.
Referenced by IUResource::validateRelatedGroups().
isIUResource()
virtual bool SchedulingResource::isIUResource () const virtual
Reimplemented in IUResource.
Referenced by ITemplateResource::validateDependentGroups(), and OutputPSocketResource::validateRelatedGroups().
isOutputFUResource()
virtual bool SchedulingResource::isOutputFUResource () const virtual
Reimplemented in OutputFUResource.
Referenced by OutputPSocketResource::validateRelatedGroups().
isOutputPSocketResource()
virtual bool SchedulingResource::isOutputPSocketResource () const virtual
Reimplemented in OutputPSocketResource.
Referenced by BusResource::canAssign(), IUResource::canAssign(), IUResource::canAssignUse(), FUResource::isAvailable(), InputFUResource::validateDependentGroups(), OutputFUResource::validateDependentGroups(), BusResource::validateRelatedGroups(), and IUResource::validateRelatedGroups().
isSegmentResource()
virtual bool SchedulingResource::isSegmentResource () const virtual
isShortImmPSocketResource()
virtual bool SchedulingResource::isShortImmPSocketResource () const virtual
Reimplemented in ShortImmPSocketResource.
Referenced by BusBroker::findImmResource().
name()
virtual const std::string & SchedulingResource::name () const virtual
Referenced by IUResource::assign(), ExecutionPipelineResource::assignDestination(), InputFUResource::canAssign(), dependentResource(), hasDependentResource(), ResourceBroker::machinePartOf(), FUResource::operator<(), relatedResource(), ExecutionPipelineBroker::setupResourceLinks(), and BusResource::unassign().
operator<()
virtual bool SchedulingResource::operator< (const SchedulingResource & other) const virtual
Reimplemented in BusResource, FUResource, InputPSocketResource, ITemplateResource, and OutputPSocketResource.
Referenced by ITemplateResource::operator<().
operator=()
SchedulingResource & SchedulingResource::operator= (const SchedulingResource &) private
relatedResource()
SchedulingResource & SchedulingResource::relatedResource (const int group, const int index) const virtual
Return related resource from group with position.
Parameters
group Group from which to return resource.
index Index of resource in particular group.
Returns
Reference to SchedulingResource [group][index].
Exceptions
OutOfRange When group or index requested does not exist.
Definition at line 120 of file SchedulingResource.cc.
{
    if (group < relatedResourceGroupCount()) {
        if (index < relatedResourceCount(group)) {
            return *relatedResourceGroup_.at(group).at(index);
        } else {
            std::string msg = "Requested related resource [";
            msg += Conversion::toString(index);
            msg += "] does not exists";
            msg += " in group [";
            msg += Conversion::toString(group);
            msg += "] of ";
            msg += name();
            msg += ". Group count is: ";
            msg += Conversion::toString(relatedResourceGroupCount());
            msg += ".";
            throw OutOfRange(__FILE__, __LINE__, __func__, msg);
        }
    } else {
        std::string msg = "Requested related resource group ";
        msg += Conversion::toString(group);
        msg += " does not exists in ";
        msg += name();
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, name(), relatedResourceCount(), relatedResourceGroup_, relatedResourceGroupCount(), and Conversion::toString().
Referenced by IUResource::canAssign(), IUResource::canAssignUse(), BusBroker::findImmResource(), InputPSocketResource::operator<(), OutputPSocketResource::operator<(), ShortImmPSocketResource::validateRelatedGroups(), BusResource::validateRelatedGroups(), ExecutionPipelineResource::validateRelatedGroups(), InputPSocketResource::validateRelatedGroups(), IUResource::validateRelatedGroups(), and OutputPSocketResource::validateRelatedGroups().
relatedResourceCount()
int SchedulingResource::relatedResourceCount (const int group) const inline
Referenced by IUResource::canAssign(), IUResource::canAssignUse(), BusBroker::findImmResource(), FUResource::operator<(), InputPSocketResource::operator<(), OutputPSocketResource::operator<(), relatedResource(), ShortImmPSocketResource::validateRelatedGroups(), BusResource::validateRelatedGroups(), ExecutionPipelineResource::validateRelatedGroups(), InputFUResource::validateRelatedGroups(), InputPSocketResource::validateRelatedGroups(), ITemplateResource::validateRelatedGroups(), IUResource::validateRelatedGroups(), OutputFUResource::validateRelatedGroups(), and OutputPSocketResource::validateRelatedGroups().
relatedResourceGroupCount()
int SchedulingResource::relatedResourceGroupCount () const virtual
Return number of groups of related resources.
Returns
Number of groups of related resources.
Definition at line 61 of file SchedulingResource.cc.
{
    return relatedResourceGroup_.size();
}
References relatedResourceGroup_.
Referenced by addToRelatedGroup(), IUResource::canAssign(), IUResource::canAssignUse(), relatedResource(), ShortImmPSocketResource::validateRelatedGroups(), BusResource::validateRelatedGroups(), ExecutionPipelineResource::validateRelatedGroups(), InputFUResource::validateRelatedGroups(), InputPSocketResource::validateRelatedGroups(), ITemplateResource::validateRelatedGroups(), IUResource::validateRelatedGroups(), OutputFUResource::validateRelatedGroups(), and OutputPSocketResource::validateRelatedGroups().
setInitiationInterval()
void SchedulingResource::setInitiationInterval (unsigned int ii)
Set initiation interval, if ii = 0 then initiation interval is not used.
Parameters
ii initiation interval
Definition at line 374 of file SchedulingResource.cc.
{
    initiationInterval_ = ii;
}
References initiationInterval_.
setMaxCycle()
virtual void SchedulingResource::setMaxCycle (unsigned int) inline virtual
Reimplemented in ExecutionPipelineResource.
Definition at line 122 of file SchedulingResource.hh.
{};
unassign()
virtual void SchedulingResource::unassign (const int cycle, MoveNode & node) pure virtual
Implemented in BusResource, ExecutionPipelineResource, FUResource, InputFUResource, ITemplateResource, IUResource, OutputFUResource, OutputPSocketResource, and PSocketResource.
Referenced by InputPSocketBroker::unassign(), OutputFUBroker::unassign(), and OutputPSocketBroker::unassign().
useCount()
int SchedulingResource::useCount () const virtual
Returns how many times particular scheduling resource was used
Returns
number of times resource was already used
Definition at line 346 of file SchedulingResource.cc.
{
    return useCount_;
}
References useCount_.
Referenced by FUResource::operator<().
validateDependentGroups()
virtual bool SchedulingResource::validateDependentGroups () protected virtual
Reimplemented in BusResource, ExecutionPipelineResource, InputFUResource, InputPSocketResource, ITemplateResource, IUResource, OutputFUResource, and OutputPSocketResource.
validateRelatedGroups()
virtual bool SchedulingResource::validateRelatedGroups () protected virtual
Reimplemented in ShortImmPSocketResource, BusResource, ExecutionPipelineResource, InputFUResource, InputPSocketResource, ITemplateResource, IUResource, OutputFUResource, and OutputPSocketResource.
Friends And Related Symbol Documentation
ResourceBroker
friend class ResourceBroker friend
Definition at line 118 of file SchedulingResource.hh.
Member Data Documentation
dependentResourceGroup_
SchedulingResourceGroup SchedulingResource::dependentResourceGroup_ private
Definition at line 147 of file SchedulingResource.hh.
Referenced by addToDependentGroup(), dependentResource(), and dependentResourceGroupCount().
initiationInterval_
int SchedulingResource::initiationInterval_ protected
Definition at line 132 of file SchedulingResource.hh.
Referenced by ExecutionPipelineResource::assignSource(), ExecutionPipelineResource::canAssignDestination(), ExecutionPipelineResource::canAssignSource(), ExecutionPipelineResource::highestKnownCycle(), initiationInterval(), ExecutionPipelineResource::latestTriggerWriteCycle(), ExecutionPipelineResource::nextResultCycle(), ExecutionPipelineResource::operandOverwritten(), ExecutionPipelineResource::resultAllowedAtCycle(), ExecutionPipelineResource::resultCausesTriggerBetweenOperandSharing(), ExecutionPipelineResource::resultNotOverWritten(), setInitiationInterval(), ExecutionPipelineResource::testTriggerResult(), ExecutionPipelineResource::unassignDestination(), and ExecutionPipelineResource::unassignSource().
name_
std::string SchedulingResource::name_ private
Definition at line 149 of file SchedulingResource.hh.
relatedResourceGroup_
SchedulingResourceGroup SchedulingResource::relatedResourceGroup_ private
Definition at line 145 of file SchedulingResource.hh.
Referenced by addToRelatedGroup(), relatedResource(), and relatedResourceGroupCount().
relatedResourceSet_
SchedulingResourceSet SchedulingResource::relatedResourceSet_ private
Definition at line 152 of file SchedulingResource.hh.
Referenced by addToRelatedGroup(), and hasRelatedResource().
useCount_
int SchedulingResource::useCount_ private
Definition at line 155 of file SchedulingResource.hh.
Referenced by clear(), decreaseUseCount(), increaseUseCount(), and useCount().
The documentation for this class was generated from the following files:
SchedulingResource.hh
SchedulingResource.cc