OpenASIP: ConnectionSweeper Class Reference
ConnectionSweeper Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Optimizes the IC of the given configuration by removing bus " "connections with least effect to the cycle count first.")
ConnectionSweeper ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual std::vector< RowID > explore (const RowID &startPointConfigurationID, const unsigned int &)
std::list< RowID > sweepRFs (RowID startPointConfigurationID)
std::list< RowID > sweepBypasses (RowID startPointConfigurationID)
void readParameters ()
float averageWorsening (RowID confId)
std::list< RowID > removeAllConnections (std::vector< const TTAMachine::Connection * > connections, const DSDBManager::MachineConfiguration &startConf)
std::list< RowID > removeLeastNecessaryConnections (std::vector< const TTAMachine::Connection * > connections, const DSDBManager::MachineConfiguration &startConf)
void removeConnection (TTAMachine::Machine &mach, const TTAMachine::Connection &connection)
Private Attributes
std::map< RowID, ClockCycleCount > origCycles_
unsigned int maxCcWorseningThreshold_
unsigned int ccWorseningThreshold_
bool allOrNothing_
Static Private Attributes
static const std::string ccWorseningThresholdPN_
static const std::string allOrNothingPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual bool requiresApplication () const
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that optimizes the interconnection network by removing connections with least effect to the cycle count first.
1) Sweeps through the buses in order. 2) For each bus, tries to remove each connection one-by-one, and evaluates the effect to the cycle count. The one with the least effect is removed first. The process is repeated until the minimum cycle count increase crosses an user-defined threshold, or the program becomes unschedulable. Emphasize RF port connections as they tend to get to the longest path due to the register selection logic being in the same path. 3) After that, the next bus is tried similarly, until either all the buses have been optimized this way. 4) The DSDB can be queried with the connection count as the first measure, the cycle count the second with both as small as possible.
Definition at line 95 of file ConnectionSweeper.cc.
Constructor & Destructor Documentation
ConnectionSweeper()
ConnectionSweeper::ConnectionSweeper () inline private
Definition at line 100 of file ConnectionSweeper.cc.
                        : DesignSpaceExplorerPlugin() {
        addParameter(ccWorseningThresholdPN_, UINT, false, "50",
                     "Limit the reduction when the cycle count "
                     "drops more than this limit (%).");
        addParameter(allOrNothingPN_, BOOL, false, "true",
                     "Do not consider single connections. Just try to remove "
                     "all of the bypass or RF connections at once. If fails, "
                     "leave them all. Leads quicker to symmetric reduced "
                     "connectivity machines.");
    }
References DesignSpaceExplorerPlugin::addParameter(), allOrNothingPN_, BOOL, ccWorseningThresholdPN_, and UINT.
Member Function Documentation
averageWorsening()
float ConnectionSweeper::averageWorsening (RowID confId) inline private
Computes the average cycle count worsening for the given processor configuration across all the explored applications.
Definition at line 386 of file ConnectionSweeper.cc.
{
        float worsenings = 0.0f;
        std::set<RowID> appIds = db().applicationIDs();
        for (std::set<RowID>::const_iterator appI = appIds.begin();
             appI != appIds.end(); ++appI) {
            RowID appID = *appI;
            DSDBManager::MachineConfiguration conf =
                db().configuration(confId);
            if (!db().hasCycleCount(appID, conf.architectureID)) {
                continue; /* the evaluation had failed */
            }
            int origCycles = origCycles_[appID];
            int newCycles =
                db().cycleCount(appID, conf.architectureID);
            worsenings += 100.0*(newCycles - origCycles) / origCycles;
        }
        float avgWorsening = worsenings / appIds.size();
        return avgWorsening;
    }
References DSDBManager::applicationIDs(), DSDBManager::MachineConfiguration::architectureID, DSDBManager::configuration(), DSDBManager::cycleCount(), DesignSpaceExplorer::db(), and origCycles_.
Referenced by removeAllConnections(), and removeLeastNecessaryConnections().
explore()
virtual std::vector< RowID > ConnectionSweeper::explore (const RowID & startPointConfigurationID, const unsigned int & maxIter) inline private virtual
Explores the design space from the starting point machine and returns best exploring results as configuration IDs.
Exploring creates new machine configurations (architecture, implementation) that are ordered so that the best results are first in the result vector.
Parameters
startPoint Starting point machine configuration for the plugin.
maxIter Maximum number of design space points the plugin is allowed to explore. Default value for maxIter is zero when the iteration number is not taken into account. In that case the exploration runs indefinetly or stops at a point defined by the algorithm.
Returns
Ordered vector of IDs of the best machine configurations where the target programs can be successfully run. The IDs of the best machine configurations are first in the result vector. Returns an empty vector if does not find any possible machine configurations.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 118 of file ConnectionSweeper.cc.
{
        readParameters();
        DSDBManager& dsdb = db();
        DSDBManager::MachineConfiguration startConf =
            dsdb.configuration(startPointConfigurationID);
        // loads starting configuration
        Machine* origMach = NULL;
        origMach = dsdb.architecture(startConf.architectureID);
        // get cycle counts for the original architecture for each app
        std::set<RowID> appIds = dsdb.applicationIDs();
        for (std::set<RowID>::const_iterator appI = appIds.begin();
             appI != appIds.end(); ++appI) {
            RowID appID = *appI;
            if (!dsdb.hasCycleCount(appID, startConf.architectureID)) {
                CostEstimates estimates;
                bool success = evaluate(startConf, estimates, false);
                if (!success) {
                    throw Exception(
                        __FILE__, __LINE__, __func__,
                        "Could not evaluate the starting point arch.");
                }
            }
            assert(dsdb.hasCycleCount(appID, startConf.architectureID));
            origCycles_[appID] =
                dsdb.cycleCount(appID, startConf.architectureID);
            TCEString s;
            s << "app: " << appID << " original cycles: ";
            s << origCycles_[appID] << " total connections: "
              << MachineConnectivityCheck::totalConnectionCount(*origMach);
            verboseLog(s);
        }
        std::vector<RowID> result;
        // sweep through the buses, the register file connections first
        // start from the biggest allowed worsening threshold to find
        // the machines with minimal connections first
        const int thresholdStep =
            std::max(maxCcWorseningThreshold_ / 4, (unsigned)1);
        for (ccWorseningThreshold_ = maxCcWorseningThreshold_;
             ccWorseningThreshold_ > 0;
             ccWorseningThreshold_ =
                 std::max(0, (int)ccWorseningThreshold_ - thresholdStep)) {
            TCEString s;
            s << "### Testing max worsening threshold "
              << ccWorseningThreshold_ << "% of "
              << maxCcWorseningThreshold_ << "%";
            verboseLog(s);
            s = "### Reducing register file and immediate unit connections.";
            verboseLog(s);
            std::list<RowID> rfSweepResults =
                sweepRFs(startPointConfigurationID);
            if (rfSweepResults.size() == 0) break;
            RowID bestFromRFSweep = rfSweepResults.front();
            result.insert(result.begin(), bestFromRFSweep);
            s = "### Reducing bypass connections.";
            verboseLog(s);
            std::list<RowID> bypassSweepResults =
                sweepBypasses(bestFromRFSweep);
            if (bypassSweepResults.size() == 0) break;
            RowID bestFromBPSweep = rfSweepResults.front();
            result.insert(result.begin(), bestFromBPSweep);
        }
        return result;
    }
References __func__, DSDBManager::applicationIDs(), DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, assert, ccWorseningThreshold_, DSDBManager::configuration(), DSDBManager::cycleCount(), DesignSpaceExplorer::db(), DesignSpaceExplorer::evaluate(), DSDBManager::hasCycleCount(), maxCcWorseningThreshold_, origCycles_, readParameters(), sweepBypasses(), sweepRFs(), MachineConnectivityCheck::totalConnectionCount(), and verboseLog.
PLUGIN_DESCRIPTION()
ConnectionSweeper::PLUGIN_DESCRIPTION ("Optimizes the IC of the given configuration by removing bus " "connections with least effect to the cycle count first.") private
producesArchitecture()
virtual bool ConnectionSweeper::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 113 of file ConnectionSweeper.cc.
{ return true; }
readParameters()
void ConnectionSweeper::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 374 of file ConnectionSweeper.cc.
{
        readOptionalParameter(
            ccWorseningThresholdPN_, maxCcWorseningThreshold_);
        readOptionalParameter(
            allOrNothingPN_, allOrNothing_);
    }
References allOrNothing_, allOrNothingPN_, ccWorseningThresholdPN_, maxCcWorseningThreshold_, and DesignSpaceExplorerPlugin::readOptionalParameter().
Referenced by explore().
removeAllConnections()
std::list< RowID > ConnectionSweeper::removeAllConnections (std::vector< const TTAMachine::Connection * > connections, const DSDBManager::MachineConfiguration & startConf) inline private
Definition at line 408 of file ConnectionSweeper.cc.
{
        std::list<RowID> results;
#if (!defined(HAVE_CXX11) && !defined(HAVE_CXX0X))
        std::auto_ptr<TTAMachine::Machine> currentMachine(
            db().architecture(startConf.architectureID));
#else
        std::unique_ptr<TTAMachine::Machine> currentMachine(
            db().architecture(startConf.architectureID));
#endif
        for (std::vector<const TTAMachine::Connection*>::iterator
                 connI = connections.begin(); connI != connections.end();
             ++connI) {
            const TTAMachine::Connection* conn = *connI;
            removeConnection(*currentMachine, *conn);
        }
        DSDBManager::MachineConfiguration conf;
        conf.architectureID = db().addArchitecture(*currentMachine);
        RowID confId = db().addConfiguration(conf);
        conf = db().configuration(confId);
        CostEstimates estimates;
        bool success = evaluate(conf, estimates, false);
        float worsening = averageWorsening(confId);
        if (success) {
#if (!defined(HAVE_CXX11) && !defined(HAVE_CXX0X))
            std::auto_ptr<TTAMachine::Machine> arch
                (db().architecture(
                    db().configuration(confId).architectureID));
#else
            std::unique_ptr<TTAMachine::Machine> arch
                (db().architecture(
                    db().configuration(confId).architectureID));
#endif
            if (worsening <= ccWorseningThreshold_) {
                results.push_back(confId);
                TCEString s;
                s << "removing all connections was within threshold: #"
                  << confId << " avg worsening: ";
                s << (int)worsening << "% " << " total connections: "
                  << MachineConnectivityCheck::totalConnectionCount(*arch);
                verboseLog(s);
            } else {
                TCEString s;
                s << "removing all connections was not within the "
                  << "threshold: #"
                  << confId << " avg worsening: ";
                s << (int)worsening << "% " << " total connections: "
                  << MachineConnectivityCheck::totalConnectionCount(*arch);
                s << "\n";
                verboseLog(s);
            }
        } else {
            TCEString s;
            s << "removing all connections led to unschedulable program\n";
            verboseLog(s);
        }
        return results;
    }
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::MachineConfiguration::architectureID, averageWorsening(), ccWorseningThreshold_, DSDBManager::configuration(), DesignSpaceExplorer::db(), DesignSpaceExplorer::evaluate(), removeConnection(), MachineConnectivityCheck::totalConnectionCount(), and verboseLog.
Referenced by sweepBypasses(), and sweepRFs().
removeConnection()
void ConnectionSweeper::removeConnection (TTAMachine::Machine & mach, const TTAMachine::Connection & connection) inline private
Definition at line 563 of file ConnectionSweeper.cc.
{
        TTAMachine::Segment& segment =
            *mach.busNavigator().item(connection.bus()->parentBus()->name())->
            segment(0);
        TTAMachine::Socket& socket =
            *mach.socketNavigator().item(connection.socket()->name());
        segment.detachSocket(socket);
    }
References TTAMachine::Connection::bus(), TTAMachine::Machine::busNavigator(), TTAMachine::Segment::detachSocket(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::Segment::parentBus(), TTAMachine::Connection::socket(), and TTAMachine::Machine::socketNavigator().
Referenced by removeAllConnections(), and removeLeastNecessaryConnections().
removeLeastNecessaryConnections()
std::list< RowID > ConnectionSweeper::removeLeastNecessaryConnections (std::vector< const TTAMachine::Connection * > connections, const DSDBManager::MachineConfiguration & startConf) inline private
Removes the connections in the given set that affect the cycle count the least until the worsening threshold is reached or in case the program becomes uncompilable.
Parameters
tryAllFirst Tries to remove all connections first and if it the results fits in the cc threshold, does not try configuration with the listed connections.
Definition at line 484 of file ConnectionSweeper.cc.
{
        std::list<RowID> results;
        DSDBManager::MachineConfiguration bestConf = startConf;
        bool couldRemove = true;
        while (couldRemove) {
            couldRemove = false;
            const TTAMachine::Connection* mostUnneededConn = NULL;
            float bestAvgccWorsening = 100.0;
            TTAMachine::Machine* currentMachine =
                db().architecture(bestConf.architectureID);
            RowID bestConfInThisIteration = -1;
            std::vector<const TTAMachine::Connection*>::iterator unneededPos =
                connections.end();
            // find the least affecting connection removal for this stage
            for (std::vector<const TTAMachine::Connection*>::iterator
                     connI = connections.begin(); connI != connections.end();
                 ++connI) {
                const TTAMachine::Connection* conn = *connI;
                // compute the avgccWorsening
                // check if it's the best found and if it's above the
                // threshold
                TTAMachine::Machine mach = *currentMachine;
                removeConnection(mach, *conn);
                DSDBManager::MachineConfiguration conf;
                conf.architectureID = db().addArchitecture(mach);
                RowID confId = db().addConfiguration(conf);
                bool success = evaluate(db().configuration(confId));
                if (success) {
                    unsigned int avgWorsening =
                        (unsigned)averageWorsening(confId);
                    if (avgWorsening <= ccWorseningThreshold_ &&
                        avgWorsening < bestAvgccWorsening) {
                        mostUnneededConn = conn;
                        bestConfInThisIteration = confId;
                        unneededPos = connI;
                        bestAvgccWorsening = avgWorsening;
                        TCEString s;
                        s << "new config: #" << bestConfInThisIteration
                          << " avg worsening: ";
                        s << (int)bestAvgccWorsening << "% "
                          << " total connections: "
                          << MachineConnectivityCheck::totalConnectionCount(
                              *db().architecture(
                                  db().configuration(confId).architectureID));
                        verboseLog(s);
                    }
                } else {
                    TCEString s;
                    s << "new config: #" << confId << " is unschedulable";
                    verboseLog(s);
                }
            }
            if (mostUnneededConn != NULL) {
                // more connections we remove while staying in the threshold,
                // better the processor gets
                bestConf = db().configuration(bestConfInThisIteration);
                couldRemove = true;
                connections.erase(unneededPos);
                results.push_front(bestConfInThisIteration);
                TCEString s;
                s << "best config from this bus sweep: #"
                  << bestConfInThisIteration << " avg worsening: ";
                s << (int)bestAvgccWorsening << "% " << " total connections: "
                  << MachineConnectivityCheck::totalConnectionCount(
                      *db().architecture(bestConf.architectureID));
                verboseLog(s);
            }
        }
        return results;
    }
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, averageWorsening(), ccWorseningThreshold_, DSDBManager::configuration(), DesignSpaceExplorer::db(), DesignSpaceExplorer::evaluate(), removeConnection(), MachineConnectivityCheck::totalConnectionCount(), and verboseLog.
Referenced by sweepBypasses(), and sweepRFs().
requiresHDB()
virtual bool ConnectionSweeper::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 114 of file ConnectionSweeper.cc.
{ return false; }
requiresSimulationData()
virtual bool ConnectionSweeper::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 115 of file ConnectionSweeper.cc.
{ return true; }
requiresStartingPointArchitecture()
virtual bool ConnectionSweeper::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 112 of file ConnectionSweeper.cc.
{ return true; }
sweepBypasses()
std::list< RowID > ConnectionSweeper::sweepBypasses (RowID startPointConfigurationID) inline private
Sweeps the bypass connections, that is, everything else but the register file and immediate unit connections.
Definition at line 277 of file ConnectionSweeper.cc.
{
        DSDBManager::MachineConfiguration startConf =
            db().configuration(startPointConfigurationID);
        // loads starting configuration
        Machine* mach = db().architecture(startConf.architectureID);
        DSDBManager::MachineConfiguration bestConf = startConf;
        std::list<RowID> result;
        for (int busI = 0; busI < mach->busNavigator().count();
             ++busI) {
            const TTAMachine::Bus& bus = *mach->busNavigator().item(busI);
            verboseLog(TCEString("considering bus ") + bus.name());
            std::vector<const TTAMachine::Connection*> connections;
            const TTAMachine::Segment& seg = *bus.segment(0);
            for (int connI = 0; connI < seg.connectionCount();
                 ++connI) {
                const TTAMachine::Connection& conn =
                    seg.connection(*seg.connection(connI));
                // check if the connection is to an IU or RF
                bool rfConnection = false;
                for (int rfI = 0; rfI < mach->registerFileNavigator().count();
                     ++rfI) {
                    const TTAMachine::RegisterFile& rf =
                        *mach->registerFileNavigator().item(rfI);
                    for (int portI = 0; portI < conn.socket()->portCount();
                         ++portI) {
                        const TTAMachine::Port& port =
                            *conn.socket()->port(portI);
                        if (port.parentUnit() == &rf) {
                            rfConnection = true;
                            break;
                        }
                    }
                }
                for (int iuI = 0;
                     !rfConnection &&
                         iuI < mach->immediateUnitNavigator().count();
                     ++iuI) {
                    const TTAMachine::ImmediateUnit& iu =
                        *mach->immediateUnitNavigator().item(iuI);
                    for (int portI = 0; portI < conn.socket()->portCount();
                         ++portI) {
                        const TTAMachine::Port& port =
                            *conn.socket()->port(portI);
                        if (port.parentUnit() == &iu) {
                            rfConnection = true;
                            break;
                        }
                    }
                }
                if (!rfConnection) connections.push_back(&conn);
            }
            std::list<RowID> newConfs = removeAllConnections(connections, bestConf);
            if (!allOrNothing_ && newConfs.size() == 0) {
                verboseLog("trying the connections one-by-one\n");
                removeLeastNecessaryConnections(connections, bestConf);
            }
            if (newConfs.size() > 0) {
                bestConf = db().configuration(newConfs.front());
                for (std::list<RowID>::reverse_iterator i = newConfs.rbegin();
                     i != newConfs.rend(); ++i) {
                    result.insert(result.begin(), *i);
                }
            }
        }
        return result;
    }
References allOrNothing_, DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, TTAMachine::Machine::busNavigator(), DSDBManager::configuration(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), DesignSpaceExplorer::db(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Machine::registerFileNavigator(), removeAllConnections(), removeLeastNecessaryConnections(), TTAMachine::Bus::segment(), TTAMachine::Connection::socket(), and verboseLog.
Referenced by explore().
sweepRFs()
std::list< RowID > ConnectionSweeper::sweepRFs (RowID startPointConfigurationID) inline private
Sweeps the register file and immediate unit connections.
Definition at line 198 of file ConnectionSweeper.cc.
{
        DSDBManager::MachineConfiguration startConf =
            db().configuration(startPointConfigurationID);
        // loads starting configuration
        Machine* mach = db().architecture(startConf.architectureID);
        DSDBManager::MachineConfiguration bestConf = startConf;
        std::list<RowID> result;
        for (int busI = 0; busI < mach->busNavigator().count();
             ++busI) {
            const TTAMachine::Bus& bus = *mach->busNavigator().item(busI);
            verboseLog(TCEString("considering bus ") + bus.name());
            std::vector<const TTAMachine::Connection*> connections;
            const TTAMachine::Segment& seg = *bus.segment(0);
            for (int rfI = 0; rfI < mach->registerFileNavigator().count();
                 ++rfI) {
                const TTAMachine::RegisterFile& rf =
                    *mach->registerFileNavigator().item(rfI);
                for (int connI = 0; connI < seg.connectionCount();
                     ++connI) {
                    const TTAMachine::Connection& conn =
                        seg.connection(*seg.connection(connI));
                    for (int portI = 0; portI < conn.socket()->portCount();
                         ++portI) {
                        const TTAMachine::Port& port =
                            *conn.socket()->port(portI);
                        if (port.parentUnit() == &rf) {
                            connections.push_back(&conn);
                        }
                    }
                }
            }
            for (int iuI = 0; iuI < mach->immediateUnitNavigator().count();
                 ++iuI) {
                const TTAMachine::ImmediateUnit& iu =
                    *mach->immediateUnitNavigator().item(iuI);
                for (int connI = 0; connI < seg.connectionCount();
                     ++connI) {
                    const TTAMachine::Connection& conn =
                        seg.connection(*seg.connection(connI));
                    for (int portI = 0; portI < conn.socket()->portCount();
                         ++portI) {
                        const TTAMachine::Port& port =
                            *conn.socket()->port(portI);
                        if (port.parentUnit() == &iu) {
                            connections.push_back(&conn);
                        }
                    }
                }
            }
            std::list<RowID> newConfs = removeAllConnections(connections, bestConf);
            if (!allOrNothing_ && newConfs.size() == 0) {
                verboseLog("trying the connections one-by-one\n");
                removeLeastNecessaryConnections(connections, bestConf);
            }
            if (newConfs.size() > 0) {
                bestConf = db().configuration(newConfs.front());
                for (std::list<RowID>::reverse_iterator i = newConfs.rbegin();
                     i != newConfs.rend(); ++i) {
                    result.insert(result.begin(), *i);
                }
            }
        }
        return result;
    }
References allOrNothing_, DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, TTAMachine::Machine::busNavigator(), DSDBManager::configuration(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), DesignSpaceExplorer::db(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::name(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Machine::registerFileNavigator(), removeAllConnections(), removeLeastNecessaryConnections(), TTAMachine::Bus::segment(), TTAMachine::Connection::socket(), and verboseLog.
Referenced by explore().
Member Data Documentation
allOrNothing_
bool ConnectionSweeper::allOrNothing_ private
Definition at line 370 of file ConnectionSweeper.cc.
Referenced by readParameters(), sweepBypasses(), and sweepRFs().
allOrNothingPN_
const std::string ConnectionSweeper::allOrNothingPN_ static private
Definition at line 361 of file ConnectionSweeper.cc.
Referenced by ConnectionSweeper(), and readParameters().
ccWorseningThreshold_
unsigned int ConnectionSweeper::ccWorseningThreshold_ private
Definition at line 366 of file ConnectionSweeper.cc.
Referenced by explore(), removeAllConnections(), and removeLeastNecessaryConnections().
ccWorseningThresholdPN_
const std::string ConnectionSweeper::ccWorseningThresholdPN_ static private
Definition at line 360 of file ConnectionSweeper.cc.
Referenced by ConnectionSweeper(), and readParameters().
maxCcWorseningThreshold_
unsigned int ConnectionSweeper::maxCcWorseningThreshold_ private
Definition at line 364 of file ConnectionSweeper.cc.
Referenced by explore(), and readParameters().
origCycles_
std::map<RowID, ClockCycleCount> ConnectionSweeper::origCycles_ private
Definition at line 358 of file ConnectionSweeper.cc.
Referenced by averageWorsening(), and explore().
The documentation for this class was generated from the following file:
ConnectionSweeper.cc