OpenASIP: EntryKeyProperty Class Reference
EntryKeyProperty Class Reference
#include <EntryKeyProperty.hh>
Public Member Functions
~EntryKeyProperty ()
std::string name () const
EntryKeyFieldProperty * createFieldProperty (std::string field)
EntryKeyFieldProperty * fieldProperty (std::string field) const
Static Public Member Functions
static EntryKeyProperty * create (std::string type)
static EntryKeyProperty * find (std::string type)
static void destroy ()
Protected Member Functions
EntryKeyProperty (std::string propertyName)
Private Types
typedef std::vector< EntryKeyFieldProperty * > FieldPropertyTable
Table of field types.
typedef std::vector< EntryKeyProperty * > EntryPropertyTable
Table of entry types.
Private Member Functions
EntryKeyProperty (const EntryKeyProperty &)
Copying not allowed.
EntryKeyProperty & operator= (const EntryKeyProperty &)
Assignment not allowed.
Private Attributes
std::string name_
Entry type.
FieldPropertyTable entryFields_
Field types of the entry type.
Static Private Attributes
static EntryPropertyTable entryTypes_
All known entry types.
Detailed Description
Represents a type of an CostDBEntryKey which contains types of its fields, that is, EntryKeyFields.
Using the EntryKeyProperty usually includes finding of the specific EntryKeyProperty with Find(). Then the types of EntryKeyProperty's fields can be accessed using FieldProperty(). Creation of the types is done similarly using first Create() and then CreateFieldProperty().
For each CostDBEntryKey an EntryKeyProperty should be assigned.
Definition at line 57 of file EntryKeyProperty.hh.
Member Typedef Documentation
EntryPropertyTable
typedef std::vector<EntryKeyProperty*> EntryKeyProperty::EntryPropertyTable private
Table of entry types.
Definition at line 76 of file EntryKeyProperty.hh.
FieldPropertyTable
typedef std::vector<EntryKeyFieldProperty*> EntryKeyProperty::FieldPropertyTable private
Table of field types.
Definition at line 74 of file EntryKeyProperty.hh.
Constructor & Destructor Documentation
~EntryKeyProperty()
EntryKeyProperty::~EntryKeyProperty ()
Destructor.
Deallocates memory reserved for field types.
Definition at line 59 of file EntryKeyProperty.cc.
{
    for (FieldPropertyTable::iterator i = entryFields_.begin();
         i != entryFields_.end(); i++) {
        assert(*i != NULL);
        delete *i;
        *i = NULL;
    }
}
References assert, and entryFields_.
EntryKeyProperty() [1/2]
EntryKeyProperty::EntryKeyProperty (std::string propertyName) protected
Constructor.
Parameters
propertyName Type of entry.
Definition at line 51 of file EntryKeyProperty.cc.
                                                     : name_(propertyName) {
}
EntryKeyProperty() [2/2]
EntryKeyProperty::EntryKeyProperty (const EntryKeyProperty &) private
Copying not allowed.
Member Function Documentation
create()
EntryKeyProperty * EntryKeyProperty::create (std::string type) static
Creates entry type.
If exists, returns the old one.
Parameters
type Entry type.
Returns
Entry type.
Definition at line 125 of file EntryKeyProperty.cc.
{
    for (EntryPropertyTable::const_iterator i = entryTypes_.begin();
         i != entryTypes_.end(); i++) {
        if ((*i)->name() == type) {
            return (*i);
        }
    }
    EntryKeyProperty* newType = new EntryKeyProperty(type);
    entryTypes_.push_back(newType);
    return newType;
}
References entryTypes_.
Referenced by CostDatabase::CostDatabase().
createFieldProperty()
EntryKeyFieldProperty * EntryKeyProperty::createFieldProperty (std::string field)
Creates field type.
If exists, returns the old one.
Parameters
field Type of field.
Returns
Field type.
Definition at line 79 of file EntryKeyProperty.cc.
{
    for (FieldPropertyTable::const_iterator i = entryFields_.begin();
         i != entryFields_.end(); i++) {
    if ((*i)->name() == field) {
        return (*i);
    }
    }
    EntryKeyFieldProperty* newField = new EntryKeyFieldProperty(field, this);
    entryFields_.push_back(newField);
    return newField;
}
References entryFields_.
Referenced by CostDatabase::CostDatabase().
destroy()
void EntryKeyProperty::destroy () static
Deallocates memory reserved for entry types.
Definition at line 166 of file EntryKeyProperty.cc.
{
    for (EntryPropertyTable::iterator i = entryTypes_.begin();
         i != entryTypes_.end(); i++) {
        assert(*i != NULL);
        delete *i;
        *i = NULL;
    }
    entryTypes_.resize(0);
}
References assert, and entryTypes_.
fieldProperty()
EntryKeyFieldProperty * EntryKeyProperty::fieldProperty (std::string field) const
Finds field type.
If not found, exits.
Parameters
field Field type.
Returns
Field type.
Exceptions
KeyNotFound Requested field was not found.
Definition at line 104 of file EntryKeyProperty.cc.
{
    for (FieldPropertyTable::const_iterator i = entryFields_.begin();
         i != entryFields_.end(); i++) {
        if ((*i)->name() == field) {
            return (*i);
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, "EntryKeyProperty::fieldProperty");
    return NULL; // stupid return statement to make compiler quiet
}
References entryFields_.
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), InterpolatingRFEstimator::createSearch(), InterpolatingFUEstimator::createSearch(), InterpolatingFUEstimator::createSearchTypes(), InterpolatingRFEstimator::createSearchTypes(), and CostDBEntryKey::keyFieldOfType().
find()
EntryKeyProperty * EntryKeyProperty::find (std::string type) static
Finds entry type.
If not found, exits.
Parameters
type Entry type.
Returns
Entry type.
Exceptions
KeyNotFound Requested field was not found.
Definition at line 150 of file EntryKeyProperty.cc.
{
    for (EntryPropertyTable::const_iterator i = entryTypes_.begin();
         i != entryTypes_.end(); i++) {
        if ((*i)->name() == type) {
            return (*i);
        }
    }
    throw KeyNotFound(__FILE__, __LINE__, "EntryKeyProperty::find");
    return NULL; // stupid return statement to make compiler quiet
}
References entryTypes_.
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), InterpolatingFUEstimator::initializeEstimator(), and InterpolatingRFEstimator::initializeEstimator().
name()
std::string EntryKeyProperty::name () const
Referenced by EntryKeyFieldProperty::entryName().
operator=()
EntryKeyProperty & EntryKeyProperty::operator= (const EntryKeyProperty &) private
Assignment not allowed.
Member Data Documentation
entryFields_
FieldPropertyTable EntryKeyProperty::entryFields_ private
Field types of the entry type.
Definition at line 81 of file EntryKeyProperty.hh.
Referenced by createFieldProperty(), fieldProperty(), and ~EntryKeyProperty().
entryTypes_
EntryKeyProperty::EntryPropertyTable EntryKeyProperty::entryTypes_ static private
All known entry types.
Definition at line 84 of file EntryKeyProperty.hh.
Referenced by create(), destroy(), and find().
name_
std::string EntryKeyProperty::name_ private
Entry type.
Definition at line 79 of file EntryKeyProperty.hh.
The documentation for this class was generated from the following files:
EntryKeyProperty.hh
EntryKeyProperty.cc