OpenASIP: MemorySystem Class Reference
MemorySystem Class Reference
#include <MemorySystem.hh>
Public Types
typedef boost::shared_ptr< Memory > MemoryPtr
Public Member Functions
MemorySystem (const TTAMachine::Machine &machine)
virtual ~MemorySystem ()
void addAddressSpace (const TTAMachine::AddressSpace &as, MemoryPtr mem, bool shared=true)
MemoryPtr memory (const TTAMachine::AddressSpace &as)
const MemoryPtr memoryConst (const TTAMachine::AddressSpace &as) const
MemoryPtr memory (const std::string &addressSpaceName)
unsigned int memoryCount () const
MemoryPtr memory (unsigned int i)
const TTAMachine::AddressSpace & addressSpace (unsigned int i)
const TTAMachine::AddressSpace & addressSpace (const std::string &name)
void shareMemoriesWith (MemorySystem &other)
void advanceClockOfLocalMemories ()
void advanceClockOfSharedMemories ()
void resetAllMemories ()
void fillAllMemoriesWithZero ()
void deleteSharedMemories ()
bool hasMemory (const TCEString &aSpaceName) const
Private Types
typedef std::map< const TTAMachine::AddressSpace *, MemoryPtr > MemoryMap
Maps address spaces to memory instances.
typedef std::vector< MemoryPtr > MemoryContainer
Container for memory instances for faster traversal.
Private Member Functions
MemorySystem (const MemorySystem &)
Copying not allowed.
MemorySystem & operator= (const MemorySystem &)
Assignment not allowed.
Private Attributes
const TTAMachine::Machine * machine_
Machine in which MemorySystem belongs to.
MemoryMap memories_
Contains all memories indexed by AddressSpaces.
MemoryContainer memoryList_
List of all the memories for faster traversal.
MemoryContainer sharedMemories_
All memories shared between multiple cores.
MemoryContainer localMemories_
All private/local memories used by a single core only.
MemoryContainer replacedSharedMemories_
Shared memories which have been replaced with a shared memory from another core. Just for garbage removal.
Detailed Description
The collection of memory simulation models seen by a single core.
Definition at line 55 of file MemorySystem.hh.
Member Typedef Documentation
MemoryContainer
typedef std::vector<MemoryPtr> MemorySystem::MemoryContainer private
Container for memory instances for faster traversal.
Definition at line 95 of file MemorySystem.hh.
MemoryMap
typedef std::map<const TTAMachine::AddressSpace*, MemoryPtr> MemorySystem::MemoryMap private
Maps address spaces to memory instances.
Definition at line 92 of file MemorySystem.hh.
MemoryPtr
typedef boost::shared_ptr<Memory> MemorySystem::MemoryPtr
Definition at line 57 of file MemorySystem.hh.
Constructor & Destructor Documentation
MemorySystem() [1/2]
MemorySystem::MemorySystem (const TTAMachine::Machine & machine) explicit
Constructor.
Parameters
machine Machine in which MemorySystem belongs to.
Definition at line 54 of file MemorySystem.cc.
                                                 :
    machine_(&machine) {
}
~MemorySystem()
MemorySystem::~MemorySystem () virtual
Destructor.
Deletes all the Memory instances.
Definition at line 73 of file MemorySystem.cc.
{
    localMemories_.clear();
    replacedSharedMemories_.clear();
}
References localMemories_, and replacedSharedMemories_.
MemorySystem() [2/2]
MemorySystem::MemorySystem (const MemorySystem &) private
Copying not allowed.
Member Function Documentation
addAddressSpace()
void MemorySystem::addAddressSpace (const TTAMachine::AddressSpace & as, MemoryPtr mem, bool shared = true)
Adds AddressSpace and corresponding memory to data structure.
Parameters
as AddressSpace to be added.
mem Memory to be added. Becomes property of the MemorySystem, that is, MemorySystems is responsible for deallocating it.
shared If the given Memory instace is shared by multiple MemorySystems (cores).
Exceptions
IllegalRegistration If the AddressSpace does not belong to the target machine.
Definition at line 90 of file MemorySystem.cc.
{
    Machine::AddressSpaceNavigator nav = machine_->addressSpaceNavigator();
    if (!nav.hasItem(as.name())) {
        string msg = "Address space doesn't belong to the target machine";
        throw IllegalRegistration(__FILE__, __LINE__, __func__, msg);
    }
    memories_[&as] = mem;
    if (shared) {
        sharedMemories_.push_back(mem);
    } else {
        localMemories_.push_back(mem);
    }
    memoryList_.push_back(mem);
}
References __func__, TTAMachine::Machine::addressSpaceNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), localMemories_, machine_, memories_, memoryList_, TTAMachine::Component::name(), and sharedMemories_.
Referenced by SimulatorFrontend::initializeMemorySystem().
addressSpace() [1/2]
const AddressSpace & MemorySystem::addressSpace (const std::string & name)
Returns the address space with the given name.
Parameters
name The name of the address space.
Returns
AddressSpace.
Exceptions
InstanceNotFound if the address space is not found.
Definition at line 286 of file MemorySystem.cc.
{
    MemoryMap::const_iterator iter = memories_.begin();
    while (iter != memories_.end()) {
        if ((*iter).first->name() == name)
            return *((*iter).first);
        ++iter;
    }
    throw InstanceNotFound(
        __FILE__, __LINE__, __func__,
        "Address space with the given name not found.");
}
References __func__, and memories_.
addressSpace() [2/2]
const AddressSpace & MemorySystem::addressSpace (unsigned int i)
Returns the address space of the ith Memory instance in the memory system.
Returns
Address Space of the memory instance.
Exceptions
OutOfRange if i is out of bounds.
Definition at line 261 of file MemorySystem.cc.
{
    if (i > memories_.size() - 1) {
        const string msg =
        "Index out of bounds. Count of memories is " +
        Conversion::toString(memoryCount());
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    unsigned int foundCount = 0;
    MemoryMap::const_iterator iter = memories_.begin();
    while (iter != memories_.end() && foundCount < i) {
        ++iter;
        ++foundCount;
    }
    return *((*iter).first);
}
References __func__, memories_, memoryCount(), and Conversion::toString().
Referenced by MemDumpCommand::execute(), SimulatorFrontend::initializeDataMemories(), ProximMemoryWindow::loadProgramMemory(), ProximMemoryWindow::onASChoice(), and shareMemoriesWith().
advanceClockOfLocalMemories()
void MemorySystem::advanceClockOfLocalMemories ()
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
advanceClockOfSharedMemories()
void MemorySystem::advanceClockOfSharedMemories ()
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
deleteSharedMemories()
void MemorySystem::deleteSharedMemories ()
Deletes all shared memory instances.
Must be called only once for all MemorySystems sharing the memories.
Definition at line 64 of file MemorySystem.cc.
{
    sharedMemories_.clear();
}
References sharedMemories_.
fillAllMemoriesWithZero()
void MemorySystem::fillAllMemoriesWithZero ()
Referenced by SimulatorFrontend::initializeDataMemories().
hasMemory()
bool MemorySystem::hasMemory (const TCEString & aSpaceName) const
Definition at line 109 of file MemorySystem.cc.
{
    MemoryMap::const_iterator iter = memories_.begin();
    while (iter != memories_.end()) {
        const AddressSpace& space = *((*iter).first);
        if (space.name() == aSpaceName) {
            return true;
        }
        ++iter;
    }
    return false;
}
References memories_, and TTAMachine::Component::name().
Referenced by shareMemoriesWith().
memory() [1/3]
MemorySystem::MemoryPtr MemorySystem::memory (const std::string & addressSpaceName)
Returns Memory instance bound to an address space with the given name.
The returned memory instance is writable.
Parameters
addressSpaceName The name of the address space.
Returns
Memory bound to AddressSpace.
Exceptions
InstanceNotFound If no memory is found with the name.
Definition at line 184 of file MemorySystem.cc.
{
    MemoryMap::const_iterator iter = memories_.begin();
    while (iter != memories_.end()) {
        const AddressSpace& space = *((*iter).first);
        MemoryPtr mem = ((*iter).second);
        if (space.name() == addressSpaceName) {
            return mem;
        }
        ++iter;
    }
    string msg = "No memory model found for address space " + addressSpaceName;
    throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
}
References __func__, memories_, and TTAMachine::Component::name().
memory() [2/3]
MemorySystem::MemoryPtr MemorySystem::memory (const TTAMachine::AddressSpace & as)
Returns Memory instance bound to the given AddressSpace.
The returned memory instance is writable.
Parameters
as AddressSpace in which memory is asked.
Returns
Memory bound to AddressSpace.
Exceptions
InstanceNotFound If no memory is bound to the given AddressSpace.
Definition at line 170 of file MemorySystem.cc.
{
    return memory(as.name());
}
References memory(), and TTAMachine::Component::name().
Referenced by MachineStateBuilder::buildMachineState(), CompiledSimulation::FUMemory(), SimulatorFrontend::initializeDataMemories(), SimulatorFrontend::initializeMemorySystem(), ProximMemoryWindow::loadMemory(), memory(), ProximMemoryWindow::onSimulationStop(), SimulatorFrontend::setControllerForMemories(), SimControlLanguageCommand::setMemoryPointer(), and shareMemoriesWith().
memory() [3/3]
MemorySystem::MemoryPtr MemorySystem::memory (unsigned int i)
Returns the ith Memory instance in the memory system.
Returns
The Memory instance.
Exceptions
OutOfRange if i is out of bounds.
Definition at line 237 of file MemorySystem.cc.
{
    if (i > memories_.size() - 1) {
        const string msg =
        "Index out of bounds. Count of memories is " +
        Conversion::toString(memoryCount());
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    unsigned int foundCount = 0;
    MemoryMap::const_iterator iter = memories_.begin();
    while (iter != memories_.end() && foundCount < i) {
        ++iter;
        ++foundCount;
    }
    return ((*iter).second);
}
References __func__, memories_, memoryCount(), and Conversion::toString().
memoryConst()
const MemorySystem::MemoryPtr MemorySystem::memoryConst (const TTAMachine::AddressSpace & as) const
Returns Memory instance bound to the given AddressSpace.
The returned memory instance is read-only.
Parameters
as AddressSpace in which memory is asked.
Returns
Memory bound to AddressSpace.
Exceptions
InstanceNotFound If no memory is bound to the given AddressSpace.
Todo:
These methods need to be changed to compare with the AS attributes not with AS pointer!
Definition at line 211 of file MemorySystem.cc.
{
    MemoryMap::const_iterator iter = memories_.find(&as);
    if (iter == memories_.end()) {
        string msg = "No memory found for address space " + as.name();
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    }
    return ((*iter).second);
}
References __func__, memories_, and TTAMachine::Component::name().
memoryCount()
unsigned int MemorySystem::memoryCount () const
Returns the count of Memory instances in this memory system.
Returns
The count of Memory instances.
Definition at line 226 of file MemorySystem.cc.
{
    return memories_.size();
}
References memories_.
Referenced by addressSpace(), ProximMemoryWindow::loadProgramMemory(), memory(), SimulatorFrontend::setControllerForMemories(), and shareMemoriesWith().
operator=()
MemorySystem & MemorySystem::operator= (const MemorySystem &) private
Assignment not allowed.
resetAllMemories()
void MemorySystem::resetAllMemories ()
Referenced by SimulatorFrontend::initializeDataMemories().
shareMemoriesWith()
void MemorySystem::shareMemoriesWith (MemorySystem & other)
In case two TTA simulation models share memories in an heterogeneous multicore simulation, this method should be called after initializing the simulation frontends between all such pairs to fix the memory model references to point to the same memory model.
The matching is done by the address space name. The shared address space must have the 'shared' attribute set.
@fixme An untested method.
remove the replaced memory as it should not be controlled by this MemorySystem anymore
Definition at line 133 of file MemorySystem.cc.
{
    for (std::size_t i = 0; i < other.memoryCount(); ++i) {
        const AddressSpace& as = other.addressSpace(i);
        if (!as.isShared() || !hasMemory(as.name())) continue;
        Machine::AddressSpaceNavigator nav = machine_->addressSpaceNavigator();
        AddressSpace* thisAS = nav.item(as.name());
        /// remove the replaced memory as it should not be controlled
        /// by this MemorySystem anymore
        memoryList_.erase(
            std::find(
                memoryList_.begin(), memoryList_.end(),
                memories_[thisAS]));
        sharedMemories_.erase(
            std::find(
                sharedMemories_.begin(), sharedMemories_.end(),
                memories_[thisAS]));
        replacedSharedMemories_.push_back(memories_[thisAS]);
        memories_[thisAS] = other.memory(i);
    }
}
References addressSpace(), TTAMachine::Machine::addressSpaceNavigator(), hasMemory(), TTAMachine::AddressSpace::isShared(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, memories_, memory(), memoryCount(), memoryList_, TTAMachine::Component::name(), replacedSharedMemories_, and sharedMemories_.
Member Data Documentation
localMemories_
MemoryContainer MemorySystem::localMemories_ private
All private/local memories used by a single core only.
Definition at line 106 of file MemorySystem.hh.
Referenced by addAddressSpace(), and ~MemorySystem().
machine_
const TTAMachine::Machine* MemorySystem::machine_ private
Machine in which MemorySystem belongs to.
Definition at line 98 of file MemorySystem.hh.
Referenced by addAddressSpace(), and shareMemoriesWith().
memories_
MemoryMap MemorySystem::memories_ private
Contains all memories indexed by AddressSpaces.
Definition at line 100 of file MemorySystem.hh.
Referenced by addAddressSpace(), addressSpace(), addressSpace(), hasMemory(), memory(), memory(), memoryConst(), memoryCount(), and shareMemoriesWith().
memoryList_
MemoryContainer MemorySystem::memoryList_ private
List of all the memories for faster traversal.
Definition at line 102 of file MemorySystem.hh.
Referenced by addAddressSpace(), and shareMemoriesWith().
replacedSharedMemories_
MemoryContainer MemorySystem::replacedSharedMemories_ private
Shared memories which have been replaced with a shared memory from another core. Just for garbage removal.
Definition at line 109 of file MemorySystem.hh.
Referenced by shareMemoriesWith(), and ~MemorySystem().
sharedMemories_
MemoryContainer MemorySystem::sharedMemories_ private
All memories shared between multiple cores.
Definition at line 104 of file MemorySystem.hh.
Referenced by addAddressSpace(), deleteSharedMemories(), and shareMemoriesWith().
The documentation for this class was generated from the following files:
MemorySystem.hh
MemorySystem.cc