OpenASIP: IDFValidator Class Reference
IDFValidator Class Reference
#include <IDFValidator.hh>
Public Member Functions
IDFValidator (const IDF::MachineImplementation &idf, const TTAMachine::Machine &machine)
virtual ~IDFValidator ()
bool validate ()
int errorCount () const
std::string errorMessage (int index) const
Static Public Member Functions
static void removeUnknownImplementations (IDF::MachineImplementation &idf, const TTAMachine::Machine &machine)
Private Types
typedef std::vector< std::string > StringVector
Vector type for string.
Private Member Functions
void checkFUImplementations ()
void checkRFImplementations ()
void checkIUImplementations ()
Private Attributes
const TTAMachine::Machine & machine_
The machine.
const IDF::MachineImplementation & idf_
The implementation definition,.
StringVector errorMessages_
Vector of error messages.
Detailed Description
Validates IDF files.
Definition at line 52 of file IDFValidator.hh.
Member Typedef Documentation
StringVector
typedef std::vector<std::string> IDFValidator::StringVector private
Vector type for string.
Definition at line 69 of file IDFValidator.hh.
Constructor & Destructor Documentation
IDFValidator()
IDFValidator::IDFValidator (const IDF::MachineImplementation & idf, const TTAMachine::Machine & machine)
The constructor.
Definition at line 45 of file IDFValidator.cc.
                                      :
    machine_(machine), idf_(idf) {
}
~IDFValidator()
IDFValidator::~IDFValidator () virtual
The destructor.
Definition at line 55 of file IDFValidator.cc.
{
}
Member Function Documentation
checkFUImplementations()
void IDFValidator::checkFUImplementations () private
Checks that the IDF defines an implementation for each FU in the machine.
If errors are found, error messages are inserted to the vector of error messages.
Definition at line 109 of file IDFValidator.cc.
{
    const Machine::FunctionUnitNavigator fuNav =
        machine_.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        const FunctionUnit* fu = fuNav.item(i);
        if (!idf_.hasFUImplementation(fu->name()) &&
            !idf_.hasFUGeneration(fu->name())) {
            format errorMsg(
                "IDF does not define an implementation for "
                " function unit %1%.");
            errorMsg % fu->name();
            errorMessages_.push_back(errorMsg.str());
        }
    }
    for (int i = 0; i < idf_.fuImplementationCount(); i++) {
        const FUImplementationLocation& fui = idf_.fuImplementation(i);
        if (!fuNav.hasItem(fui.unitName())) {
            format errorMsg(
                "IDF defines implementation for unknown "
                "function unit %1%.");
            errorMsg % fui.unitName();
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), errorMessages_, IDF::MachineImplementation::fuImplementation(), IDF::MachineImplementation::fuImplementationCount(), TTAMachine::Machine::functionUnitNavigator(), IDF::MachineImplementation::hasFUGeneration(), IDF::MachineImplementation::hasFUImplementation(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), idf_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), and IDF::UnitImplementationLocation::unitName().
Referenced by validate().
checkIUImplementations()
void IDFValidator::checkIUImplementations () private
Checks that the IDF defines an implementation for each IU in the machine.
If errors are found, error messages are inserted to the vector of error messages.
Definition at line 185 of file IDFValidator.cc.
{
    const Machine::ImmediateUnitNavigator iuNav =
        machine_.immediateUnitNavigator();
    for (int i = 0; i < iuNav.count(); i++) {
        ImmediateUnit* iu = iuNav.item(i);
        if (!idf_.hasIUImplementation(iu->name())) {
            format errorMsg(
                "IDF does not define an implementation for "
                "immediate unit %1%.");
            errorMsg % iu->name();
            errorMessages_.push_back(errorMsg.str());
        }
    }
    for (int i = 0; i < idf_.iuImplementationCount(); i++) {
        const RFImplementationLocation& iui = idf_.iuImplementation(i);
        if (!iuNav.hasItem(iui.unitName())) {
            format errorMsg(
                "IDF defines implementation for unknown immediate unit %1%.");
            errorMsg % iui.unitName();
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), errorMessages_, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), IDF::MachineImplementation::hasIUImplementation(), idf_, TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), IDF::MachineImplementation::iuImplementation(), IDF::MachineImplementation::iuImplementationCount(), machine_, TTAMachine::Component::name(), and IDF::UnitImplementationLocation::unitName().
Referenced by validate().
checkRFImplementations()
void IDFValidator::checkRFImplementations () private
Checks that the IDF defines an implementation for each RF in the machine.
If errors are found, error messages are inserted to the vector of error messages.
Definition at line 148 of file IDFValidator.cc.
{
    const Machine::RegisterFileNavigator rfNav =
        machine_.registerFileNavigator();
    for (int i = 0; i < rfNav.count(); i++) {
        RegisterFile* rf = rfNav.item(i);
        if (!idf_.hasRFImplementation(rf->name())) {
            format errorMsg(
                "IDF does not define an implementation for "
                "register file %1%.");
            errorMsg % rf->name();
            errorMessages_.push_back(errorMsg.str());
        }
    }
    for (int i = 0; i < idf_.rfImplementationCount(); i++) {
        const RFImplementationLocation& rfi = idf_.rfImplementation(i);
        if (!rfNav.hasItem(rfi.unitName())) {
            format errorMsg(
                "IDF defines implementation for unknown register file %1%.");
            errorMsg % rfi.unitName();
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), errorMessages_, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), IDF::MachineImplementation::hasRFImplementation(), idf_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), TTAMachine::Machine::registerFileNavigator(), IDF::MachineImplementation::rfImplementation(), IDF::MachineImplementation::rfImplementationCount(), and IDF::UnitImplementationLocation::unitName().
Referenced by validate().
errorCount()
int IDFValidator::errorCount () const
Returns the number of errors found in the last validation.
Returns
The error count.
Definition at line 81 of file IDFValidator.cc.
{
    return errorMessages_.size();
}
References errorMessages_.
Referenced by errorMessage(), ProcessorImplementationWindow::onGenerateProcessor(), ProcessorImplementationWindow::onLoadIDF(), validate(), and validateIdf().
errorMessage()
std::string IDFValidator::errorMessage (int index) const
Returns an error message by the given index.
Parameters
index The index.
Exceptions
OutOfRange If the index is negative or not smaller than the number of errors.
Definition at line 94 of file IDFValidator.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    return errorMessages_[index];
}
References __func__, errorCount(), and errorMessages_.
Referenced by ProGe::ProGeUI::generateProcessor(), ProcessorImplementationWindow::onGenerateProcessor(), ProcessorImplementationWindow::onLoadIDF(), and validateIdf().
removeUnknownImplementations()
void IDFValidator::removeUnknownImplementations (IDF::MachineImplementation & idf, const TTAMachine::Machine & machine) static
Static helper function for removing implementations to units that don't exist in the machine.
Parameters
idf IDF to remove extraneous implementations from.
machine Machine to check the IDF against.
Definition at line 223 of file IDFValidator.cc.
{
    const Machine::ImmediateUnitNavigator iuNav =
        machine.immediateUnitNavigator();
    const Machine::RegisterFileNavigator rfNav =
        machine.registerFileNavigator();
    const Machine::FunctionUnitNavigator fuNav =
        machine.functionUnitNavigator();
    for (int i = 0; i < idf.iuImplementationCount(); i++) {
        const RFImplementationLocation& iui = idf.iuImplementation(i);
        if (!iuNav.hasItem(iui.unitName())) {
            idf.removeIUImplementation(iui.unitName());
        }
    }
    for (int i = 0; i < idf.rfImplementationCount(); i++) {
        const RFImplementationLocation& rfi = idf.rfImplementation(i);
        if (!rfNav.hasItem(rfi.unitName())) {
            idf.removeRFImplementation(rfi.unitName());
        }
    }
    for (int i = 0; i < idf.fuImplementationCount(); i++) {
        const FUImplementationLocation& fui = idf.fuImplementation(i);
        if (!fuNav.hasItem(fui.unitName())) {
            idf.removeFUImplementation(fui.unitName());
        }
    }
}
References IDF::MachineImplementation::fuImplementation(), IDF::MachineImplementation::fuImplementationCount(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Machine::immediateUnitNavigator(), IDF::MachineImplementation::iuImplementation(), IDF::MachineImplementation::iuImplementationCount(), machine, TTAMachine::Machine::registerFileNavigator(), IDF::MachineImplementation::removeFUImplementation(), IDF::MachineImplementation::removeIUImplementation(), IDF::MachineImplementation::removeRFImplementation(), IDF::MachineImplementation::rfImplementation(), IDF::MachineImplementation::rfImplementationCount(), and IDF::UnitImplementationLocation::unitName().
Referenced by ProcessorImplementationWindow::onLoadIDF().
validate()
bool IDFValidator::validate ()
Validates the IDF by checking that the IDF has an implementation defined for all the units of the machine.
Returns
True if the IDF is valid, otherwise false.
Definition at line 66 of file IDFValidator.cc.
                       {
    errorMessages_.clear();
    checkFUImplementations();
    checkRFImplementations();
    checkIUImplementations();
    return errorCount() == 0;
}
References checkFUImplementations(), checkIUImplementations(), checkRFImplementations(), errorCount(), and errorMessages_.
Referenced by ProGe::ProGeUI::generateProcessor(), ProcessorImplementationWindow::onGenerateProcessor(), ProcessorImplementationWindow::onLoadIDF(), and validateIdf().
Member Data Documentation
errorMessages_
StringVector IDFValidator::errorMessages_ private
Vector of error messages.
Definition at line 80 of file IDFValidator.hh.
Referenced by checkFUImplementations(), checkIUImplementations(), checkRFImplementations(), errorCount(), errorMessage(), and validate().
idf_
const IDF::MachineImplementation& IDFValidator::idf_ private
The implementation definition,.
Definition at line 78 of file IDFValidator.hh.
Referenced by checkFUImplementations(), checkIUImplementations(), and checkRFImplementations().
machine_
const TTAMachine::Machine& IDFValidator::machine_ private
The machine.
Definition at line 76 of file IDFValidator.hh.
Referenced by checkFUImplementations(), checkIUImplementations(), and checkRFImplementations().
The documentation for this class was generated from the following files:
IDFValidator.hh
IDFValidator.cc