OpenASIP: InputFUResource Class Reference
InputFUResource Class Reference
#include <InputFUResource.hh>
Public Member Functions
virtual ~InputFUResource ()
InputFUResource (const std::string &name, int opCount, int nopSlotWeight, unsigned int initiationInterval=0)
virtual bool canAssign (const int cycle, const MoveNode &node) const override
virtual void assign (const int cycle, MoveNode &node) override
virtual bool isAvailable (const int cycle) const override
virtual bool isInUse (const int cycle) const override
virtual void unassign (const int cycle, MoveNode &node) override
virtual bool canAssign (const int cycle, const MoveNode &node, const InputPSocketResource &pSocket, const bool triggers=false) const
virtual bool isInputFUResource () const override
Public Member Functions inherited from FUResource
FUResource (const std::string &name, int operationCount, int nopSlotWeight, unsigned int initiationInterval=0)
virtual ~FUResource ()
virtual bool operator< (const SchedulingResource &other) const override
Public Member Functions inherited from SchedulingResource
virtual ~SchedulingResource ()
SchedulingResource (const std::string &name, const unsigned int ii=0)
virtual int relatedResourceGroupCount () const
virtual int dependentResourceGroupCount () const
int relatedResourceCount (const int group) const
int dependentResourceCount (const int group) const
virtual void addToRelatedGroup (const int group, SchedulingResource &resource)
virtual void addToDependentGroup (const int group, SchedulingResource &resource)
virtual SchedulingResource & relatedResource (const int group, const int index) const
virtual SchedulingResource & dependentResource (const int group, const int index) const
virtual bool hasRelatedResource (const SchedulingResource &sResource) const
virtual bool hasDependentResource (const SchedulingResource &sResource) const
virtual const std::string & name () const
virtual int useCount () const
virtual void increaseUseCount ()
virtual void decreaseUseCount ()
virtual bool isInputPSocketResource () const
virtual bool isOutputPSocketResource () const
virtual bool isShortImmPSocketResource () const
virtual bool isOutputFUResource () const
virtual bool isExecutionPipelineResource () const
virtual bool isBusResource () const
virtual bool isSegmentResource () const
virtual bool isIUResource () const
virtual bool isITemplateResource () const
int instructionIndex (int cycle) const
void setInitiationInterval (unsigned int ii)
int initiationInterval () const
virtual void clear ()
virtual void setMaxCycle (unsigned int)
Protected Member Functions
virtual bool validateDependentGroups () override
virtual bool validateRelatedGroups () override
Private Member Functions
InputFUResource (const InputFUResource &)
InputFUResource & operator= (const InputFUResource &)
Additional Inherited Members
Protected Attributes inherited from SchedulingResource
int initiationInterval_
Detailed Description
An interface for scheduling resources of Resource Model. The derived class InputFUResource.
Definition at line 49 of file InputFUResource.hh.
Constructor & Destructor Documentation
~InputFUResource()
InputFUResource::~InputFUResource () virtual
Empty destructor
Definition at line 61 of file InputFUResource.cc.
{
}
InputFUResource() [1/2]
InputFUResource::InputFUResource (const std::string & name, int opCount, int nopSlotWeight, unsigned int initiationInterval = 0)
Constructor defining name of resource.
Parameters
name Name of resource
Definition at line 52 of file InputFUResource.cc.
                                     :
    FUResource(name, opCount, nopSlotWeight, initiationInterval) {
}
InputFUResource() [2/2]
InputFUResource::InputFUResource (const InputFUResource &) private
Member Function Documentation
assign()
void InputFUResource::assign (const int cycle, MoveNode & node) override virtual
Assign resource to given node for given cycle as a side effect, assign also execution pipeline for triggering moves.
Parameters
cycle Cycle to assign
node MoveNode assigned
pSocket InputPSocket used for writting operand
Exceptions
In case the assignment is impossible, should have been tested with canAssing first.
Reimplemented from FUResource.
Definition at line 86 of file InputFUResource.cc.
                    {
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource()) {
                SchedulingResource* res = &dependentResource(i, j);
                ExecutionPipelineResource* epRes =
                    dynamic_cast<ExecutionPipelineResource*>(res);
                epRes->assignDestination(cycle, node);
                increaseUseCount();
                return;
            }
        }
    }
    abortWithError("InputFUResource has no execution pipeline registered!");
}
References abortWithError, ExecutionPipelineResource::assignDestination(), SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::increaseUseCount(), and SchedulingResource::isExecutionPipelineResource().
Referenced by InputFUBroker::assign().
canAssign() [1/2]
bool InputFUResource::canAssign (const int cycle, const MoveNode & node) const override virtual
Not to be used, aborts!
Use version with third InputPSocket operand!
Reimplemented from FUResource.
Definition at line 70 of file InputFUResource.cc.
{
    abortWithError("Wrong method. Use canAssign with PSocket!");
    return false;
}
References abortWithError.
Referenced by InputFUBroker::allAvailableResources().
canAssign() [2/2]
bool InputFUResource::canAssign (const int cycle, const MoveNode & node, const InputPSocketResource & pSocket, const bool triggers = false) const virtual
Return true if resource can be assigned for given node in given cycle.
Parameters
cycle Cycle to test
node MoveNode to test
pSocket InputPSocket used for writting operand
Returns
true if node can be assigned to cycle
Exceptions
Internal error, PSocket is not conencted to FU or ExecutionPipeline
Definition at line 144 of file InputFUResource.cc.
{
    if (!hasDependentResource(pSocket)) {
        std::string msg = "InputPSocket ";
        msg += pSocket.name();
        msg += " is not connected to ";
        msg += name();
        msg += "!";
        throw ModuleRunTimeError(__FILE__, __LINE__, __func__, msg);
        return false;
    }
    if (!pSocket.canAssign(cycle, node)) {
        debugLogRM("cannot assign pSocket");
        return false;
    }
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            SchedulingResource& depRes = dependentResource(i, j);
            if (depRes.isExecutionPipelineResource()) {
                ExecutionPipelineResource* epRes =
                    static_cast<ExecutionPipelineResource*>(&depRes);
                if (!(epRes->canAssignDestination(cycle, node, triggers))) {
                    debugLogRM("cannot assign execution pipeline resource");
                    return false;
                } else {
                    return true;
                }
            }
        }
    }
    debugLogRM("could not find a depedent resource I could assign");
    return false;
}
References __func__, InputPSocketResource::canAssign(), ExecutionPipelineResource::canAssignDestination(), debugLogRM, SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::hasDependentResource(), SchedulingResource::isExecutionPipelineResource(), and SchedulingResource::name().
isAvailable()
bool InputFUResource::isAvailable (const int cycle) const override virtual
Test if resource InputFUResource is available.
Not all the PSocket are inUse and there is some operation possible for triggering moves.
Parameters
cycle Cycle which to test
Returns
True if FUResource is available in cycle
Reimplemented from FUResource.
Definition at line 194 of file InputFUResource.cc.
{
    // Test availability of PSockets using parent class
    if (!FUResource::isAvailable(cycle)) {
        return false;
    }
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource() &&
                dependentResource(i, j).isAvailable(cycle)) {
                return true;
            }
        }
    }
    return false;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isAvailable(), FUResource::isAvailable(), and SchedulingResource::isExecutionPipelineResource().
Referenced by InputFUBroker::allAvailableResources().
isInputFUResource()
bool InputFUResource::isInputFUResource () const override virtual
Allways return true
Returns
true
Reimplemented from SchedulingResource.
Definition at line 242 of file InputFUResource.cc.
{
    return true;
}
isInUse()
bool InputFUResource::isInUse (const int cycle) const override virtual
Test if resource InputFUResource is used in given cycle.
True if some of InputPSockets are already used or there is operation already in execution pipeline.
Parameters
cycle Cycle which to test
Returns
True if InputFUResource is already used in cycle
Reimplemented from FUResource.
Definition at line 220 of file InputFUResource.cc.
{
    // Test isInUse of PSockets using parent class
    if (FUResource::isInUse(cycle)) {
        return true;
    }
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource() &&
                dependentResource(i, j).isInUse(cycle)) {
                return true;
            }
        }
    }
    return false;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isExecutionPipelineResource(), SchedulingResource::isInUse(), and FUResource::isInUse().
operator=()
InputFUResource & InputFUResource::operator= (const InputFUResource &) private
unassign()
void InputFUResource::unassign (const int cycle, MoveNode & node) override virtual
Unassign resource from given node for given cycle, for triggering moves also unassign execution pipeline.
Parameters
cycle Cycle to remove assignment from
node MoveNode to remove assignment from
pSocket InputPSocket used for writting operand
Exceptions
In case PSocket is not connected to FU
Reimplemented from FUResource.
Definition at line 115 of file InputFUResource.cc.
                    {
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (dependentResource(i, j).isExecutionPipelineResource()) {
                SchedulingResource* res = &dependentResource(i, j);
                ExecutionPipelineResource* epRes =
                    dynamic_cast<ExecutionPipelineResource*>(res);
                epRes->unassignDestination(cycle, node);
                decreaseUseCount();
                return;
            }
        }
    }
    abortWithError("InputFUResource has no execution pipeline registered!");
}
References abortWithError, SchedulingResource::decreaseUseCount(), SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isExecutionPipelineResource(), and ExecutionPipelineResource::unassignDestination().
Referenced by InputFUBroker::unassign().
validateDependentGroups()
bool InputFUResource::validateDependentGroups () override protected virtual
Tests if all referred resource in dependent groups are of proper types.
Returns
true If all resources in dependent groups are input or output PSockets or executionPipeline
Reimplemented from SchedulingResource.
Definition at line 254 of file InputFUResource.cc.
{
    for (int i = 0; i < dependentResourceGroupCount(); i++) {
        for (int j = 0, count = dependentResourceCount(i); j < count; j++) {
            if (!(dependentResource(i, j).isInputPSocketResource() ||
                dependentResource(i, j).isOutputPSocketResource() ||
                dependentResource(i, j).isExecutionPipelineResource())) {
                return false;
            }
        }
    }
    return true;
}
References SchedulingResource::dependentResource(), SchedulingResource::dependentResourceCount(), SchedulingResource::dependentResourceGroupCount(), SchedulingResource::isExecutionPipelineResource(), SchedulingResource::isInputPSocketResource(), and SchedulingResource::isOutputPSocketResource().
validateRelatedGroups()
bool InputFUResource::validateRelatedGroups () override protected virtual
Tests if related resource groups are empty.
Returns
true If all related resource groups are empty
Reimplemented from SchedulingResource.
Definition at line 274 of file InputFUResource.cc.
{
    for (int i = 0; i < relatedResourceGroupCount(); i++) {
        if (relatedResourceCount(i) > 0) {
            return false;
        }
    }
    return true;
}
References SchedulingResource::relatedResourceCount(), and SchedulingResource::relatedResourceGroupCount().
The documentation for this class was generated from the following files:
InputFUResource.hh
InputFUResource.cc