OpenASIP: IPXactFileGenerator Class Reference
IPXactFileGenerator Class Reference
#include <IPXactFileGenerator.hh>
Public Member Functions
IPXactFileGenerator (TCEString toplevelEntity, const PlatformIntegrator *integrator)
virtual ~IPXactFileGenerator ()
virtual void writeProjectFiles ()
Public Member Functions inherited from ProjectFileGenerator
ProjectFileGenerator (TCEString coreEntity, const PlatformIntegrator *integrator)
virtual ~ProjectFileGenerator ()
void addHdlFile (const TCEString &file)
void addHdlFiles (const std::vector< TCEString > &files)
void addMemInitFile (const TCEString &memInit)
void addSignalMapping (const PlatInt::SignalMapping &mapping)
Private Member Functions
void addBusInterfaces (IPXactModel *model)
void addAddressSpaces (IPXactModel *model)
TCEString outputFileName () const
Private Attributes
IPXactSerializer * ipXactWriter_
Additional Inherited Members
Protected Member Functions inherited from ProjectFileGenerator
const std::vector< TCEString > & hdlFileList () const
const std::vector< TCEString > & memInitFileList () const
const PlatformIntegrator * integrator () const
TCEString coreEntity () const
TCEString toplevelEntity () const
int signalMappingCount () const
const PlatInt::SignalMapping * signalMapping (int index) const
TCEString extractFUName (const TCEString &port, const TCEString &delimiter) const
Detailed Description
Definition at line 43 of file IPXactFileGenerator.hh.
Constructor & Destructor Documentation
IPXactFileGenerator()
IPXactFileGenerator::IPXactFileGenerator (TCEString toplevelEntity, const PlatformIntegrator * integrator)
Definition at line 57 of file IPXactFileGenerator.cc.
                                         :
    ProjectFileGenerator(toplevelEntity, integrator),
    ipXactWriter_(new IPXactSerializer()) {
}
~IPXactFileGenerator()
IPXactFileGenerator::~IPXactFileGenerator () virtual
Definition at line 65 of file IPXactFileGenerator.cc.
{
    delete ipXactWriter_;
}
References ipXactWriter_.
Member Function Documentation
addAddressSpaces()
void IPXactFileGenerator::addAddressSpaces (IPXactModel * model) private
Definition at line 124 of file IPXactFileGenerator.cc.
{
    IPXactAddressSpace* imemAs =
        new IPXactAddressSpace(integrator()->imemInfo());
    model->addAddressSpace(imemAs);
    for (int i = 0; i < integrator()->dmemCount(); i++) {
        IPXactAddressSpace* dmemAs =
            new IPXactAddressSpace(integrator()->dmemInfo(i));
        model->addAddressSpace(dmemAs);
    }
}
References IPXactModel::addAddressSpace(), PlatformIntegrator::dmemCount(), and ProjectFileGenerator::integrator().
Referenced by writeProjectFiles().
addBusInterfaces()
void IPXactFileGenerator::addBusInterfaces (IPXactModel * model) private
Definition at line 102 of file IPXactFileGenerator.cc.
{
    std::vector<IPXactInterface*> interfaces;
    interfaces.push_back(new IPXactClkInterface());
    interfaces.push_back(new IPXactResetInterface());
    interfaces.push_back(new IPXactHibiInterface());
    const NetlistBlock& toplevel = integrator()->toplevelBlock();
    for (unsigned int i = 0; i < interfaces.size(); i++) {
        if (interfaces.at(i)->mapPortsToInterface(toplevel)) {
            // mapping was successful, add interface
            model->addBusInterface(interfaces.at(i));
        } else {
            delete interfaces.at(i);
            interfaces.at(i) = NULL;
        }
    }
}
References IPXactModel::addBusInterface(), ProjectFileGenerator::integrator(), and PlatformIntegrator::toplevelBlock().
Referenced by writeProjectFiles().
outputFileName()
TCEString IPXactFileGenerator::outputFileName () const private
Definition at line 139 of file IPXactFileGenerator.cc.
{
    return "spirit_comp_def_" + toplevelEntity() + ".xml";
}
References ProjectFileGenerator::toplevelEntity().
Referenced by writeProjectFiles().
writeProjectFiles()
void IPXactFileGenerator::writeProjectFiles () virtual
Implements ProjectFileGenerator.
Definition at line 72 of file IPXactFileGenerator.cc.
{
    IPXactModel* ip = new IPXactModel();
    ip->setVLNV(DEF_VENDOR, DEF_LIBRARY, toplevelEntity(), DEF_VERSION);
    const ProGe::NetlistBlock& toplevel = integrator()->toplevelBlock();
    for (size_t i = 0; i < toplevel.portCount(); i++) {
        HDLPort port(toplevel.port(i));
        ip->addSignal(port);
    }
    for (size_t i = 0; i < toplevel.parameterCount(); i++) {
        ip->addParameter(toplevel.parameter(i));
    }
    addBusInterfaces(ip);
    addAddressSpaces(ip);
    ip->setHdlFiles(hdlFileList());
    for (unsigned int i = 0; i < memInitFileList().size(); i++) {
        ip->setFile(memInitFileList().at(i));
    }
    ipXactWriter_->setDestinationFile(outputFileName());
    ipXactWriter_->writeIPXactModel(*ip);
    delete ip;
}
References addAddressSpaces(), addBusInterfaces(), IPXactModel::addParameter(), IPXactModel::addSignal(), DEF_LIBRARY, DEF_VENDOR, DEF_VERSION, ProjectFileGenerator::hdlFileList(), ProjectFileGenerator::integrator(), ipXactWriter_, ProjectFileGenerator::memInitFileList(), outputFileName(), ProGe::NetlistBlock::parameter(), ProGe::BaseNetlistBlock::parameterCount(), ProGe::NetlistBlock::port(), ProGe::NetlistBlock::portCount(), XMLSerializer::setDestinationFile(), IPXactModel::setFile(), IPXactModel::setHdlFiles(), IPXactModel::setVLNV(), PlatformIntegrator::toplevelBlock(), ProjectFileGenerator::toplevelEntity(), and IPXactSerializer::writeIPXactModel().
Member Data Documentation
ipXactWriter_
IPXactSerializer* IPXactFileGenerator::ipXactWriter_ private
Definition at line 61 of file IPXactFileGenerator.hh.
Referenced by writeProjectFiles(), and ~IPXactFileGenerator().
The documentation for this class was generated from the following files:
IPXactFileGenerator.hh
IPXactFileGenerator.cc