OpenASIP: ProximMemoryWindow Class Reference
ProximMemoryWindow Class Reference
#include <ProximMemoryWindow.hh>
Public Member Functions
ProximMemoryWindow (ProximMainFrame *parent, int id)
virtual ~ProximMemoryWindow ()
virtual void reset ()
Private Types
enum {
ID_AS_CHOICE = 10000 , ID_TEXT_AS , ID_TEXT_AS_INFO , ID_TEXT_START_ADDRESS ,
ID_START_ADDRESS , ID_TEXT_DISPLAY , ID_DISPLAY_SIZE_CHOICE , ID_LINE
}
Private Member Functions
void onProgramLoaded (const SimulatorEvent &event)
void onSimulationStop (const SimulatorEvent &event)
void loadProgramMemory ()
void loadMemory (const TTAMachine::AddressSpace &as)
void initialize ()
void onASChoice (wxCommandEvent &event)
void onDisplayRangeChoice (wxCommandEvent &event)
void createContents ()
Private Attributes
MemorySystem * memorySystem_
Memory system to display in teh window.
MemoryControl * memoryControl_
MemoryControl widget which displays the memory contents.
SimulatorFrontend * simulator_
Simulator instance which contains the memory system to display.
wxBoxSizer * sizer_
Toplevel sizer for the window widgets.
wxChoice * asChoice_
Address space choicer widget.
wxStaticBoxSizer * addressRangeSizer_
Sizer for address range widgets.
wxStaticText * asInfoText_
Static text control displaying address space information.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Proxim subwindow which displays memory contents.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 54 of file ProximMemoryWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_AS_CHOICE
ID_TEXT_AS
ID_TEXT_AS_INFO
ID_TEXT_START_ADDRESS
ID_START_ADDRESS
ID_TEXT_DISPLAY
ID_DISPLAY_SIZE_CHOICE
ID_LINE
Definition at line 85 of file ProximMemoryWindow.hh.
         {
        ID_AS_CHOICE = 10000,
        ID_TEXT_AS,
            ID_TEXT_AS_INFO,
        ID_TEXT_START_ADDRESS,
        ID_START_ADDRESS,
        ID_TEXT_DISPLAY,
        ID_DISPLAY_SIZE_CHOICE,
        ID_LINE
    };
Constructor & Destructor Documentation
ProximMemoryWindow()
ProximMemoryWindow::ProximMemoryWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 65 of file ProximMemoryWindow.cc.
                                    :
    ProximSimulatorWindow(parent, id, wxDefaultPosition, wxSize(800,600)),
    memorySystem_(NULL),
    memoryControl_(NULL), asInfoText_(NULL) {
    createContents();
    simulator_ = wxGetApp().simulation()->frontend();
    if (simulator_->isSimulationInitialized() ||
    simulator_->isSimulationStopped() ||
    simulator_->hasSimulationEnded()) {
    loadProgramMemory();
    }
}
~ProximMemoryWindow()
ProximMemoryWindow::~ProximMemoryWindow () virtual
Destructor.
Definition at line 86 of file ProximMemoryWindow.cc.
{
}
Member Function Documentation
createContents()
void ProximMemoryWindow::createContents () private
Creates the window contents.
Definition at line 221 of file ProximMemoryWindow.cc.
{
    sizer_= new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *item1 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticText *item2 = new wxStaticText(
    this, ID_TEXT_AS, wxT("Address space:"),
        wxDefaultPosition, wxDefaultSize, 0);
    item1->Add(item2, 0, wxALIGN_CENTER|wxALL, 5);
    wxString *strs3 = (wxString*) NULL;
    asChoice_ = new wxChoice(
        this, ID_AS_CHOICE, wxDefaultPosition, wxSize(150,-1), 0, strs3, 0);
    item1->Add(asChoice_, 0, wxALIGN_CENTER|wxALL, 5);
    sizer_->Add(item1, 0, wxALIGN_CENTER|wxALL, 5);
    wxStaticLine *item4 = new wxStaticLine(
        this, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL);
    sizer_->Add(item4, 0, wxGROW|wxALL, 5);
    asInfoText_ = new wxStaticText(this, ID_TEXT_AS_INFO, wxT(""));
    sizer_->Add(asInfoText_, 0, wxGROW|wxALL, 5);
    this->SetSizer(sizer_);
    sizer_->SetSizeHints(this);
}
References asChoice_, asInfoText_, ID_AS_CHOICE, ID_LINE, ID_TEXT_AS, ID_TEXT_AS_INFO, and sizer_.
initialize()
void ProximMemoryWindow::initialize () private
loadMemory()
void ProximMemoryWindow::loadMemory (const TTAMachine::AddressSpace & as) private
Loads memory from the given address space to the memory window.
Parameters
as Address space of the memory to load.
Definition at line 96 of file ProximMemoryWindow.cc.
{
    MemorySystem& memorySystem = simulator_->memorySystem();
    MemorySystem::MemoryPtr mem = memorySystem.memory(as);
    if (memoryControl_ == NULL) {
        memoryControl_ =
            new MemoryControl(this, mem.get());
        sizer_->Add(memoryControl_, 1, wxGROW);
        sizer_->Layout();
        Fit();
    } else {
        memoryControl_->setMemory(mem.get());
    }
    wxString asInfo = WxConversion::toWxString(as.name());
    asInfo.Prepend(_T("    "));
    asInfo.Append(_T(":   "));
    asInfo.Append(
        WxConversion::toWxString(Conversion::toHexString(as.start())));
    asInfo.Append(_T(" - "));
    asInfo.Append(
        WxConversion::toWxString(Conversion::toHexString(as.end())));
    asInfo.Append(_T("    MAU: "));
    asInfo.Append(WxConversion::toWxString(as.width()));
    asInfoText_->SetLabel(asInfo);
}
References asInfoText_, TTAMachine::AddressSpace::end(), MemorySystem::memory(), memoryControl_, SimulatorFrontend::memorySystem(), TTAMachine::Component::name(), MemoryControl::setMemory(), simulator_, sizer_, TTAMachine::AddressSpace::start(), Conversion::toHexString(), WxConversion::toWxString(), and TTAMachine::AddressSpace::width().
Referenced by onASChoice().
loadProgramMemory()
void ProximMemoryWindow::loadProgramMemory () private
Initializes simulated memory system in the window.
Definition at line 155 of file ProximMemoryWindow.cc.
{
    asChoice_->Clear();
    MemorySystem& memorySystem = simulator_->memorySystem();
    for (unsigned int i = 0; i < memorySystem.memoryCount(); i++) {
        string asName = memorySystem.addressSpace(i).name();
        asChoice_->Append(WxConversion::toWxString(asName));
    }
    asChoice_->SetSelection(0);
    wxCommandEvent dummy;
    onASChoice(dummy);
}
References MemorySystem::addressSpace(), asChoice_, dummy, MemorySystem::memoryCount(), SimulatorFrontend::memorySystem(), TTAMachine::Component::name(), onASChoice(), simulator_, and WxConversion::toWxString().
Referenced by onProgramLoaded().
onASChoice()
void ProximMemoryWindow::onASChoice (wxCommandEvent & event) private
Event handler for the address space choicer.
Loads the selected address space in the memory control.
Definition at line 175 of file ProximMemoryWindow.cc.
{
    MemorySystem& memorySystem = simulator_->memorySystem();
    const AddressSpace& as =
    memorySystem.addressSpace(asChoice_->GetSelection());
    loadMemory(as);
}
References MemorySystem::addressSpace(), asChoice_, loadMemory(), SimulatorFrontend::memorySystem(), and simulator_.
Referenced by loadProgramMemory().
onDisplayRangeChoice()
void ProximMemoryWindow::onDisplayRangeChoice (wxCommandEvent & event) private
onProgramLoaded()
void ProximMemoryWindow::onProgramLoaded (const SimulatorEvent & event) private
Event handler which is called when a new program is loaded in the simulator.
Definition at line 133 of file ProximMemoryWindow.cc.
{
    loadProgramMemory();
}
References loadProgramMemory().
onSimulationStop()
void ProximMemoryWindow::onSimulationStop (const SimulatorEvent & event) private
Event handler for simulation stop.
Refreshes the memory display.
Definition at line 189 of file ProximMemoryWindow.cc.
{
    memoryControl_->clearHighlights();
    MemorySystem& memorySystem = simulator_->memorySystem();
    MemoryProxy* mem = dynamic_cast<MemoryProxy*>(
        memorySystem.memory(asChoice_->GetSelection()).get());
    if (mem != NULL) {
        unsigned reads = mem->readAccessCount();
        for (unsigned i = 0; i < reads; i++) {
            MemoryProxy::MemoryAccess access = mem->readAccess(i);
            memoryControl_->highlight(
                access.first, access.second, *wxGREEN);
        }
        unsigned writes = mem->writeAccessCount();
        for (unsigned i = 0; i < writes; i++) {
            MemoryProxy::MemoryAccess access = mem->writeAccess(i);
            memoryControl_->highlight(
                access.first, access.second, *wxRED);
        }
    }
    memoryControl_->updateView();
}
References asChoice_, MemoryControl::clearHighlights(), MemoryControl::highlight(), MemorySystem::memory(), memoryControl_, SimulatorFrontend::memorySystem(), MemoryProxy::readAccess(), MemoryProxy::readAccessCount(), simulator_, MemoryControl::updateView(), MemoryProxy::writeAccess(), and MemoryProxy::writeAccessCount().
reset()
void ProximMemoryWindow::reset () virtual
Resets the window when a new program or machine is being loaded in the simulator.
Reimplemented from ProximSimulatorWindow.
Definition at line 142 of file ProximMemoryWindow.cc.
{
    asChoice_->Clear();
    asInfoText_->SetLabel(_T(""));
    if (memoryControl_ != NULL) {
        memoryControl_->Destroy();
        memoryControl_ = NULL;
    }
}
References asChoice_, asInfoText_, and memoryControl_.
Member Data Documentation
addressRangeSizer_
wxStaticBoxSizer* ProximMemoryWindow::addressRangeSizer_ private
Sizer for address range widgets.
Definition at line 80 of file ProximMemoryWindow.hh.
asChoice_
wxChoice* ProximMemoryWindow::asChoice_ private
Address space choicer widget.
Definition at line 78 of file ProximMemoryWindow.hh.
Referenced by createContents(), loadProgramMemory(), onASChoice(), onSimulationStop(), and reset().
asInfoText_
wxStaticText* ProximMemoryWindow::asInfoText_ private
Static text control displaying address space information.
Definition at line 82 of file ProximMemoryWindow.hh.
Referenced by createContents(), loadMemory(), and reset().
memoryControl_
MemoryControl* ProximMemoryWindow::memoryControl_ private
MemoryControl widget which displays the memory contents.
Definition at line 72 of file ProximMemoryWindow.hh.
Referenced by loadMemory(), onSimulationStop(), and reset().
memorySystem_
MemorySystem* ProximMemoryWindow::memorySystem_ private
Memory system to display in teh window.
Definition at line 70 of file ProximMemoryWindow.hh.
simulator_
SimulatorFrontend* ProximMemoryWindow::simulator_ private
Simulator instance which contains the memory system to display.
Definition at line 74 of file ProximMemoryWindow.hh.
Referenced by loadMemory(), loadProgramMemory(), onASChoice(), and onSimulationStop().
sizer_
wxBoxSizer* ProximMemoryWindow::sizer_ private
Toplevel sizer for the window widgets.
Definition at line 76 of file ProximMemoryWindow.hh.
Referenced by createContents(), and loadMemory().
The documentation for this class was generated from the following files:
ProximMemoryWindow.hh
ProximMemoryWindow.cc