OpenASIP: SourceField Class Reference
SourceField Class Reference
#include <SourceField.hh>
Public Member Functions
SourceField (BinaryEncoding::Position componentIDPos, MoveSlot &parent)
SourceField (const ObjectState *state, MoveSlot &parent)
virtual ~SourceField ()
void addBridgeEncoding (BridgeEncoding &encoding)
void removeBridgeEncoding (BridgeEncoding &encoding)
bool hasBridgeEncoding (const std::string &bridge) const
BridgeEncoding & bridgeEncoding (const std::string &bridge) const
int bridgeEncodingCount () const
BridgeEncoding & bridgeEncoding (int index) const
void setImmediateEncoding (ImmediateEncoding &encoding)
void unsetImmediateEncoding ()
bool hasImmediateEncoding () const
ImmediateEncoding & immediateEncoding () const
virtual int width () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from SlotField
virtual ~SlotField ()
MoveSlot * parent () const
void addSocketEncoding (SocketEncoding &encoding)
void removeSocketEncoding (SocketEncoding &encoding)
int socketEncodingCount () const
SocketEncoding & socketEncoding (int index) const
bool hasSocketEncoding (const std::string &socket) const
SocketEncoding & socketEncoding (const std::string &socket) const
void setNoOperationEncoding (NOPEncoding &encoding)
void unsetNoOperationEncoding ()
bool hasNoOperationEncoding () const
NOPEncoding & noOperationEncoding () const
BinaryEncoding::Position componentIDPosition () const
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_SOURCE_FIELD = "source_field"
ObjectState name for source field.
Static Public Attributes inherited from SlotField
static const std::string OSNAME_SLOT_FIELD = "slot_field"
ObjectState name for slot field.
static const std::string OSKEY_COMPONENT_ID_POSITION = "comp_id_pos"
ObjectState attribute key for component ID position.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Types
typedef std::vector< BridgeEncoding * > BridgeEncodingTable
Container type for bridge encodings.
Private Member Functions
void clearBridgeEncodings ()
void clearImmediateEncoding ()
Private Attributes
BridgeEncodingTable bridgeEncodings_
Container for bridge encodings.
ImmediateEncoding * immEncoding_
The immediate encoding.
Additional Inherited Members
Protected Member Functions inherited from SlotField
SlotField (BinaryEncoding::Position componentIDPos, MoveSlot &parent)
SlotField (const ObjectState *state, MoveSlot &parent)
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
SourceField class represents the source field of a move slot.
It is a specialisation of InstructionField class. In addition to socket encodings, a source field may encode an inline immediate or up to two bridge sources.
Definition at line 48 of file SourceField.hh.
Member Typedef Documentation
BridgeEncodingTable
typedef std::vector<BridgeEncoding*> SourceField::BridgeEncodingTable private
Container type for bridge encodings.
Definition at line 78 of file SourceField.hh.
Constructor & Destructor Documentation
SourceField() [1/2]
SourceField::SourceField (BinaryEncoding::Position componentIDPos, MoveSlot & parent)
The constructor.
Creates a source field and registers it into the given move slot.
Parameters
componentIDPos Position of the socket or bridge ID within the source field.
parent The parent move slot.
Exceptions
ObjectAlreadyExists If the given move slot already has a source field.
IllegalParameters If the given component ID position is not the same with other source fields in the binary encoding map.
Definition at line 65 of file SourceField.cc.
    : SlotField(componentIDPos, parent), immEncoding_(NULL) {
    BinaryEncoding* bem = parent.parent();
    for (int i = 0; i < bem->moveSlotCount(); i++) {
    MoveSlot& slot = bem->moveSlot(i);
    if (slot.hasSourceField() &&
        (slot.sourceField().componentIDPosition() != componentIDPos)) {
        const string procName = "SourceField::SourceField";
        throw IllegalParameters(__FILE__, __LINE__, procName);
    } else {
        break;
    }
    }
    setParent(NULL);
    parent.setSourceField(*this);
    setParent(&parent);
}
References SlotField::componentIDPosition(), MoveSlot::hasSourceField(), BinaryEncoding::moveSlot(), BinaryEncoding::moveSlotCount(), MoveSlot::parent(), SlotField::parent(), InstructionField::setParent(), MoveSlot::setSourceField(), and MoveSlot::sourceField().
SourceField() [2/2]
SourceField::SourceField (const ObjectState * state, MoveSlot & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent move slot.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the given move slot already has a source field.
Definition at line 97 of file SourceField.cc.
    : SlotField(state, parent), immEncoding_(NULL) {
    loadState(state);
    setParent(NULL);
    parent.setSourceField(*this);
    setParent(&parent);
}
References loadState(), SlotField::parent(), InstructionField::setParent(), and MoveSlot::setSourceField().
~SourceField()
SourceField::~SourceField () virtual
The destructor.
Definition at line 108 of file SourceField.cc.
{
    clearBridgeEncodings();
    clearImmediateEncoding();
    MoveSlot* parent = this->parent();
    setParent(NULL);
    parent->unsetSourceField();
}
References clearBridgeEncodings(), clearImmediateEncoding(), SlotField::parent(), InstructionField::setParent(), and MoveSlot::unsetSourceField().
Member Function Documentation
addBridgeEncoding()
void SourceField::addBridgeEncoding (BridgeEncoding & encoding)
Adds the given encoding for a bridge to the source field.
This method is to be called from the constructor of BridgeEncoding class.
Parameters
encoding The encoding to be added.
Exceptions
ObjectAlreadyExists If the field already has an encoding for the given bridge or if the encoding is ambiguous with another encoding or if the source field has encodings for two bridges already.
Definition at line 130 of file SourceField.cc.
{
    assert(encoding.parent() == NULL);
    string bridge = encoding.bridgeName();
    const string procName = "SourceField::addBridgeEncoding";
    if (hasBridgeEncoding(bridge) ||
    !BEMTester::canAddComponentEncoding(
        *this, encoding.encoding(), encoding.extraBits()) ||
    bridgeEncodingCount() == 2) {
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    bridgeEncodings_.push_back(&encoding);
}
References assert, bridgeEncodingCount(), bridgeEncodings_, BridgeEncoding::bridgeName(), BEMTester::canAddComponentEncoding(), Encoding::encoding(), Encoding::extraBits(), hasBridgeEncoding(), and BridgeEncoding::parent().
Referenced by BridgeEncoding::BridgeEncoding(), and BridgeEncoding::BridgeEncoding().
bridgeEncoding() [1/2]
BridgeEncoding & SourceField::bridgeEncoding (const std::string & bridge) const
Returns the encoding for the given bridge.
Parameters
bridge Name of the bridge.
Returns
The bridge encoding for the given bridge or NullBridgeEncoding instance if there is no encoding for the given bridge.
Definition at line 191 of file SourceField.cc.
{
    int encodingCount = bridgeEncodingCount();
    for (int i = 0; i < encodingCount; i++) {
        BridgeEncoding& encoding = bridgeEncoding(i);
        if (encoding.bridgeName() == bridge) {
            return encoding;
        }
    }
    return NullBridgeEncoding::instance();
}
References bridgeEncoding(), bridgeEncodingCount(), BridgeEncoding::bridgeName(), and NullBridgeEncoding::instance().
Referenced by bridgeEncoding(), BEMTester::canAddComponentEncoding(), hasBridgeEncoding(), printSourceFieldEncodings(), saveState(), and width().
bridgeEncoding() [2/2]
BridgeEncoding & SourceField::bridgeEncoding (int index) const
Returns the bridge encoding stored at the given position.
Parameters
index The position.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of bridge encodings.
Definition at line 222 of file SourceField.cc.
{
    if (index < 0 || index >= bridgeEncodingCount()) {
    const string procName = "SourceField::bridgeEncoding";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return *bridgeEncodings_[index];
}
References bridgeEncodingCount(), and bridgeEncodings_.
bridgeEncodingCount()
int SourceField::bridgeEncodingCount () const
Returns the number of bridge encodings defined for this source field.
Returns
The number of bridge encodings.
Definition at line 209 of file SourceField.cc.
{
    return bridgeEncodings_.size();
}
References bridgeEncodings_.
Referenced by addBridgeEncoding(), bridgeEncoding(), bridgeEncoding(), BEMTester::canAddComponentEncoding(), hasBridgeEncoding(), printSourceFieldEncodings(), saveState(), and width().
clearBridgeEncodings()
void SourceField::clearBridgeEncodings () private
Clears all the bridge encodings from the source field.
Definition at line 396 of file SourceField.cc.
{
    SequenceTools::deleteAllItems(bridgeEncodings_);
}
References bridgeEncodings_, and SequenceTools::deleteAllItems().
Referenced by loadState(), and ~SourceField().
clearImmediateEncoding()
void SourceField::clearImmediateEncoding () private
Deletes the immediate encoding if one exists.
Definition at line 405 of file SourceField.cc.
{
    if (hasImmediateEncoding()) {
        delete immEncoding_;
    }
}
References hasImmediateEncoding(), and immEncoding_.
Referenced by loadState(), and ~SourceField().
hasBridgeEncoding()
bool SourceField::hasBridgeEncoding (const std::string & bridge) const
Tells whether the source field has an encoding defined for the given bridge.
Parameters
bridge Name of the bridge.
Returns
True if there is an encoding for the given bridge, otherwise false.
Definition at line 169 of file SourceField.cc.
{
    int bridgeEncodings = bridgeEncodingCount();
    for (int i = 0; i < bridgeEncodings; i++) {
    BridgeEncoding& encoding = bridgeEncoding(i);
    if (encoding.bridgeName() == bridge) {
        return true;
    }
    }
    return false;
}
References bridgeEncoding(), bridgeEncodingCount(), and BridgeEncoding::bridgeName().
Referenced by addBridgeEncoding(), and BEMValidator::checkSourceField().
hasImmediateEncoding()
bool SourceField::hasImmediateEncoding () const
Tells whether the source field has an immediate encoding.
Returns
True if the source field has an immediate encoding, otherwise false.
Definition at line 279 of file SourceField.cc.
{
    return immEncoding_ != NULL;
}
References immEncoding_.
Referenced by BEMTester::canAddComponentEncoding(), BEMValidator::checkSourceField(), clearImmediateEncoding(), BEMTester::conflictsWithSourceEncodings(), immediateEncoding(), printSourceFieldEncodings(), saveState(), setImmediateEncoding(), unsetImmediateEncoding(), width(), and DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus().
immediateEncoding()
ImmediateEncoding & SourceField::immediateEncoding () const
Returns the immediate encoding.
Returns NullImmediateEncoding instance if the source field does not have an immediate encoding.
Returns
The immediate encoding.
Definition at line 293 of file SourceField.cc.
{
    if (hasImmediateEncoding()) {
        return *immEncoding_;
    } else {
        return NullImmediateEncoding::instance();
    }
}
References hasImmediateEncoding(), immEncoding_, and NullImmediateEncoding::instance().
Referenced by BEMTester::canAddComponentEncoding(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeImmediateTerminal(), printSourceFieldEncodings(), saveState(), unsetImmediateEncoding(), width(), DefaultDecoderGenerator::writeBusControlRulesOfSImmSocketOfBus(), and DefaultDecoderGenerator::writeSimmDataSignal().
loadState()
void SourceField::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from SlotField.
Definition at line 336 of file SourceField.cc.
{
    const string procName = "SourceField::loadState";
    if (state->name() != OSNAME_SOURCE_FIELD) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    clearBridgeEncodings();
    clearImmediateEncoding();
    SlotField::loadState(state);
    try {
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() == BridgeEncoding::OSNAME_BRIDGE_ENCODING) {
        new BridgeEncoding(child, *this);
        } else if (child->name() ==
                       ImmediateEncoding::OSNAME_IMM_ENCODING) {
                new ImmediateEncoding(child, *this);
            }
        }
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
    // TODO: check that the positions of the encodings match with the
    // ones given in the ObjectState instances
}
References ObjectState::child(), ObjectState::childCount(), clearBridgeEncodings(), clearImmediateEncoding(), Exception::errorMessage(), SlotField::loadState(), ObjectState::name(), BridgeEncoding::OSNAME_BRIDGE_ENCODING, ImmediateEncoding::OSNAME_IMM_ENCODING, and OSNAME_SOURCE_FIELD.
Referenced by SourceField().
removeBridgeEncoding()
void SourceField::removeBridgeEncoding (BridgeEncoding & encoding)
Removes the given bridge encoding from the source field.
This method is to be called from the destructor of BridgeEncoding class.
Parameters
encoding The encoding to be removed.
Definition at line 154 of file SourceField.cc.
{
    assert(encoding.parent() == NULL);
    assert(ContainerTools::removeValueIfExists(bridgeEncodings_, &encoding));
}
References assert, bridgeEncodings_, BridgeEncoding::parent(), and ContainerTools::removeValueIfExists().
Referenced by BridgeEncoding::~BridgeEncoding().
saveState()
ObjectState * SourceField::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from SlotField.
Definition at line 372 of file SourceField.cc.
{
    ObjectState* state = SlotField::saveState();
    state->setName(OSNAME_SOURCE_FIELD);
    // add bridge encodings
    for (int i = 0; i < bridgeEncodingCount(); i++) {
    BridgeEncoding& enc = bridgeEncoding(i);
    state->addChild(enc.saveState());
    }
    // add immediate encoding
    if (hasImmediateEncoding()) {
        state->addChild(immediateEncoding().saveState());
    }
    return state;
}
References ObjectState::addChild(), bridgeEncoding(), bridgeEncodingCount(), hasImmediateEncoding(), immediateEncoding(), OSNAME_SOURCE_FIELD, BridgeEncoding::saveState(), SlotField::saveState(), saveState(), and ObjectState::setName().
Referenced by saveState().
setImmediateEncoding()
void SourceField::setImmediateEncoding (ImmediateEncoding & encoding)
Sets the given encoding for inline immediates.
This method is to be called from the constructor of ImmediateEncoding.
Parameters
encoding The encoding to be set.
Exceptions
ObjectAlreadyExists If the source field has an immediate encoding already or if the given encoding is ambiguous with some socket or bridge encoding.
Definition at line 243 of file SourceField.cc.
{
    assert(encoding.parent() == NULL);
    if (hasImmediateEncoding() ||
        !BEMTester::canAddComponentEncoding(
            *this, encoding.encoding(), encoding.extraBits())) {
        BEMTextGenerator textGen;
        format text = textGen.text(BEMTextGenerator::TXT_ILLEGAL_IMM_ENC);
        text % parent()->name();
        const string procName = "SourceField::setImmediateEncoding";
        throw ObjectAlreadyExists(__FILE__, __LINE__, procName, text.str());
    }
    immEncoding_ = &encoding;
}
References assert, BEMTester::canAddComponentEncoding(), Encoding::encoding(), Encoding::extraBits(), hasImmediateEncoding(), immEncoding_, MoveSlot::name(), ImmediateEncoding::parent(), SlotField::parent(), Texts::TextGenerator::text(), and BEMTextGenerator::TXT_ILLEGAL_IMM_ENC.
Referenced by ImmediateEncoding::ImmediateEncoding(), and ImmediateEncoding::ImmediateEncoding().
unsetImmediateEncoding()
void SourceField::unsetImmediateEncoding ()
Unsets the immediate encoding.
This method is to be called from the destructor of ImmediateEncoding.
Definition at line 265 of file SourceField.cc.
{
    assert(hasImmediateEncoding());
    assert(immediateEncoding().parent() == NULL);
    immEncoding_ = NULL;
}
References assert, hasImmediateEncoding(), immediateEncoding(), immEncoding_, and SlotField::parent().
Referenced by ImmediateEncoding::~ImmediateEncoding().
width()
int SourceField::width () const virtual
Returns the bit width of the source field.
Returns
The bit width.
Reimplemented from SlotField.
Definition at line 308 of file SourceField.cc.
{
    int maxEncodingWidth = SlotField::width() - extraBits();
    for (int i = 0; i < bridgeEncodingCount(); i++) {
    BridgeEncoding& encoding = bridgeEncoding(i);
    if (encoding.width() > maxEncodingWidth) {
        maxEncodingWidth = encoding.width();
    }
    }
    if (hasImmediateEncoding() && immediateEncoding().width() >
        maxEncodingWidth) {
        maxEncodingWidth = immediateEncoding().width();
    }
    return maxEncodingWidth + extraBits();
}
References bridgeEncoding(), bridgeEncodingCount(), InstructionField::extraBits(), hasImmediateEncoding(), immediateEncoding(), Encoding::width(), ImmediateEncoding::width(), SlotField::width(), and width().
Referenced by CodeCompressorPlugin::addBitsForSourceField(), BridgeEncoding::bitPosition(), BEMTester::canAddComponentPriorityEncoding(), CodeCompressorPlugin::encodeImmediateTerminal(), CodeCompressorPlugin::encodeMove(), CodeCompressorPlugin::encodeNOP(), ImmediateEncoding::encodingPosition(), ImmediateEncoding::immediatePosition(), printMoveSlotLayout(), printSourceFieldEncodings(), MoveSlot::width(), width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeMoveFieldSignals().
Member Data Documentation
bridgeEncodings_
BridgeEncodingTable SourceField::bridgeEncodings_ private
Container for bridge encodings.
Definition at line 84 of file SourceField.hh.
Referenced by addBridgeEncoding(), bridgeEncoding(), bridgeEncodingCount(), clearBridgeEncodings(), and removeBridgeEncoding().
immEncoding_
ImmediateEncoding* SourceField::immEncoding_ private
The immediate encoding.
Definition at line 86 of file SourceField.hh.
Referenced by clearImmediateEncoding(), hasImmediateEncoding(), immediateEncoding(), setImmediateEncoding(), and unsetImmediateEncoding().
OSNAME_SOURCE_FIELD
const std::string SourceField::OSNAME_SOURCE_FIELD = "source_field" static
ObjectState name for source field.
Definition at line 74 of file SourceField.hh.
Referenced by MoveSlot::loadState(), loadState(), BEMSerializer::moveSlotToFile(), saveState(), and BEMSerializer::sourceFieldToOM().
The documentation for this class was generated from the following files:
SourceField.hh
SourceField.cc