OpenASIP: ProDeOptionsSerializer Class Reference
ProDeOptionsSerializer Class Reference
#include <ProDeOptionsSerializer.hh>
Public Member Functions
ProDeOptionsSerializer ()
virtual ~ProDeOptionsSerializer ()
Public Member Functions inherited from GUIOptionsSerializer
GUIOptionsSerializer (std::string configurationName)
virtual ~GUIOptionsSerializer ()
void writeState (const ObjectState *optionsState)
ObjectState * readState ()
void writeOptions (const GUIOptions &options)
GUIOptions * readOptions ()
Public Member Functions inherited from XMLSerializer
XMLSerializer ()
virtual ~XMLSerializer ()
void setSourceFile (const std::string &fileName)
void setSourceString (const std::string &source)
void setDestinationFile (const std::string &fileName)
void setDestinationString (std::string &destination)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
void setXMLNamespace (std::string nsUri)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Private Member Functions
ObjectState * convertToConfigFileFormat (const ObjectState *options) const
ObjectState * convertToOptionsObjectFormat (const ObjectState *root) const
ProDeOptionsSerializer (const ProDeOptionsSerializer &)
Copying not allowed.
ProDeOptionsSerializer & operator= (const ProDeOptionsSerializer &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from XMLSerializer
std::string sourceFile () const
Detailed Description
Reads/writes ProDe options from/to an XML file.
Definition at line 43 of file ProDeOptionsSerializer.hh.
Constructor & Destructor Documentation
ProDeOptionsSerializer() [1/2]
ProDeOptionsSerializer::ProDeOptionsSerializer ()
Constructor.
Definition at line 53 of file ProDeOptionsSerializer.cc.
                                               :
    GUIOptionsSerializer(ProDeOptions::CONFIGURATION_NAME) {
}
~ProDeOptionsSerializer()
ProDeOptionsSerializer::~ProDeOptionsSerializer () virtual
Destructor.
Definition at line 61 of file ProDeOptionsSerializer.cc.
{
}
ProDeOptionsSerializer() [2/2]
ProDeOptionsSerializer::ProDeOptionsSerializer (const ProDeOptionsSerializer &) private
Copying not allowed.
Member Function Documentation
convertToConfigFileFormat()
ObjectState * ProDeOptionsSerializer::convertToConfigFileFormat (const ObjectState * options) const private virtual
Converts the given ObjectState tree created by ProDeOptions::saveState to the format of configuration file.
Parameters
options ObjectState tree to be converted.
Returns
The newly created ObjectState tree which matches with configuration file format.
Reimplemented from GUIOptionsSerializer.
Definition at line 74 of file ProDeOptionsSerializer.cc.
{
    ObjectState* root =
        GUIOptionsSerializer::convertToConfigFileFormat(options);
    // add undo stack size
    ObjectState* undoStack = new ObjectState(UNDO);
    root->addChild(undoStack);
    undoStack->setAttribute(
        UNDO_SIZE, options->stringAttribute(
          ProDeOptions::OSKEY_UNDO_STACK_SIZE));
    return root;
}
References ObjectState::addChild(), GUIOptionsSerializer::convertToConfigFileFormat(), options, ProDeOptions::OSKEY_UNDO_STACK_SIZE, ObjectState::setAttribute(), UNDO, and UNDO_SIZE.
convertToOptionsObjectFormat()
ObjectState * ProDeOptionsSerializer::convertToOptionsObjectFormat (const ObjectState * root) const private virtual
Creates a new ObjectState tree which can be given to ProDeOptions constructor. The tree is created according to the given tree which matches with the syntax of the options file.
Parameters
root Root node of the ObjectState tree to be converted.
Reimplemented from GUIOptionsSerializer.
Definition at line 99 of file ProDeOptionsSerializer.cc.
{
    ObjectState* options =
        GUIOptionsSerializer::convertToOptionsObjectFormat(root);
    // set undo stack size
    if (root->hasChild(UNDO)) {
        ObjectState* undo = root->childByName(UNDO);
        options->setAttribute(
            ProDeOptions::OSKEY_UNDO_STACK_SIZE,
            undo->stringAttribute(UNDO_SIZE));
    } else {
        options->setAttribute(
            ProDeOptions::OSKEY_UNDO_STACK_SIZE, DEFAULT_UNDO_SIZE);
    }
    return options;
}
References ObjectState::childByName(), GUIOptionsSerializer::convertToOptionsObjectFormat(), DEFAULT_UNDO_SIZE, ObjectState::hasChild(), options, ProDeOptions::OSKEY_UNDO_STACK_SIZE, ObjectState::stringAttribute(), UNDO, and UNDO_SIZE.
operator=()
ProDeOptionsSerializer & ProDeOptionsSerializer::operator= (const ProDeOptionsSerializer &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeOptionsSerializer.hh
ProDeOptionsSerializer.cc