OpenASIP: ProDeOptions Class Reference
ProDeOptions Class Reference
#include <ProDeOptions.hh>
Public Member Functions
ProDeOptions ()
ProDeOptions (const ObjectState *state)
ProDeOptions (const ProDeOptions &old)
virtual ~ProDeOptions ()
int undoStackSize () const
void setUndoStackSize (int size)
void loadState (const ObjectState *state)
ObjectState * saveState () const
Public Member Functions inherited from GUIOptions
GUIOptions (std::string name)
GUIOptions (const GUIOptions &old)
GUIOptions (const ObjectState *state)
virtual ~GUIOptions ()
bool hasFileName () const
std::string fileName () const
void setFileName (const std::string &fileName)
virtual void validate () const
bool fullScreen () const
int windowWidth () const
int windowHeight () const
int xPosition () const
int yPosition () const
bool toolbarVisibility () const
ToolbarLayout toolbarLayout () const
void setFullScreen (bool fullScreen)
void setWindowSize (int width, int height)
void setWindowPosition (int x, int y)
void setToolbarVisibility (bool visible)
void setToolbarLayout (ToolbarLayout layout)
void addKeyboardShortcut (KeyboardShortcut *shortcut)
void addToolbarButton (ToolbarButton *button)
void addSeparator (int position)
void deleteKeyboardShortcut (KeyboardShortcut *shortcut)
void deleteToolbarButton (ToolbarButton *button)
void deleteSeparator (int position)
KeyboardShortcut * keyboardShortcut (const std::string commandName) const
KeyboardShortcut * firstShortcut () const
KeyboardShortcut * nextShortcut () const
ToolbarButton * firstToolbarButton () const
ToolbarButton * nextToolbarButton () const
int firstSeparator () const
int nextSeparator () const
void clearModified ()
bool isModified () const
wxToolBar * createToolbar (wxWindow *parent, CommandRegistry &registry, const wxString &iconsPath)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string CONFIGURATION_NAME = "prode-configuration"
ObjectState name for ProDeOptions.
static const std::string OSKEY_UNDO_STACK_SIZE = "undosize"
ObjectState attribute key for the size of the undo stack.
Static Public Attributes inherited from GUIOptions
static const std::string TOOLBAR_SEPARATOR = "-- separator --"
Toolbar separator name.
static const std::string OSNAME_OPTIONS = "options"
ObjectState name for the options.
static const std::string OSKEY_FULL_SCREEN = "fscreen"
ObjectState attribute key for full screen feature.
static const std::string OSKEY_WINDOW_WIDTH = "wwidth"
ObjectState attribute key for window width.
static const std::string OSKEY_WINDOW_HEIGHT = "wheight"
ObjectState attribute key for window height.
static const std::string OSKEY_X_POS = "xpos"
ObjectState attribute key for window x position.
static const std::string OSKEY_Y_POS = "ypos"
ObjectState attribute key for window y position.
static const std::string OSKEY_TOOLBAR_VISIBILITY = "tbvisib"
ObjectState attribute key for toolbar visibility.
static const std::string OSKEY_TOOLBAR_LAYOUT = "tblayout"
ObjectState attribute key for toolbar layout.
static const std::string OSVALUE_TEXT = "text"
ObjectState attribute value for text layout.
static const std::string OSVALUE_ICON = "icon"
ObjectState attribute value for icon layout.
static const std::string OSVALUE_BOTH = "both"
ObjectState attribute value for text & icon layout.
static const std::string OSNAME_SEPARATOR = "separator"
ObjectState name for separator.
static const std::string OSKEY_POSITION = "pos"
ObjectState attribute key for separator position.
Private Attributes
int undoStackSize_
Undo stack size.
Additional Inherited Members
Public Types inherited from GUIOptions
enum ToolbarLayout { TEXT , ICON , BOTH }
Protected Member Functions inherited from GUIOptions
void deleteAllKeyboardShortcuts ()
void deleteAllToolbarButtons ()
Detailed Description
Represents the options of the editor.
Definition at line 44 of file ProDeOptions.hh.
Constructor & Destructor Documentation
ProDeOptions() [1/3]
ProDeOptions::ProDeOptions ()
Constructor.
Definition at line 50 of file ProDeOptions.cc.
                           :
    GUIOptions(CONFIGURATION_NAME),
    undoStackSize_(10) {
}
ProDeOptions() [2/3]
ProDeOptions::ProDeOptions (const ObjectState * state)
Constructor.
Loads the state from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Definition at line 65 of file ProDeOptions.cc.
    : GUIOptions(CONFIGURATION_NAME) {
    loadState(state);
}
References loadState().
ProDeOptions() [3/3]
ProDeOptions::ProDeOptions (const ProDeOptions & old)
Copy constructor.
This constructor creates identical options with the given options class.
Definition at line 75 of file ProDeOptions.cc.
                                                  :
    GUIOptions(old) {
    undoStackSize_ = old.undoStackSize_;
}
References undoStackSize_.
~ProDeOptions()
ProDeOptions::~ProDeOptions () virtual
Destructor.
Definition at line 85 of file ProDeOptions.cc.
{
}
Member Function Documentation
loadState()
void ProDeOptions::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState object.
Parameters
state ObjectState from which the state is loaded.
Exceptions
ObjectStateLoadingException If the given ObjectState instance is invalid.
Reimplemented from GUIOptions.
Definition at line 119 of file ProDeOptions.cc.
{
    deleteAllKeyboardShortcuts();
    deleteAllToolbarButtons();
    const string procName = "ProDeOptions::loadState";
    GUIOptions::loadState(state);
    try {
        undoStackSize_ = state->intAttribute(OSKEY_UNDO_STACK_SIZE);
    } catch (...) {
        deleteAllKeyboardShortcuts();
        deleteAllToolbarButtons();
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
}
References GUIOptions::deleteAllKeyboardShortcuts(), GUIOptions::deleteAllToolbarButtons(), ObjectState::intAttribute(), GUIOptions::loadState(), OSKEY_UNDO_STACK_SIZE, and undoStackSize_.
Referenced by ProDeOptions().
saveState()
ObjectState * ProDeOptions::saveState () const virtual
Creates an ObjectState object and saves the state of the object into it.
Returns
The created ObjectState object.
Reimplemented from GUIOptions.
Definition at line 142 of file ProDeOptions.cc.
{
    ObjectState* state = GUIOptions::saveState();
    state->setAttribute(OSKEY_UNDO_STACK_SIZE, undoStackSize_);
    return state;
}
References OSKEY_UNDO_STACK_SIZE, GUIOptions::saveState(), ObjectState::setAttribute(), and undoStackSize_.
setUndoStackSize()
void ProDeOptions::setUndoStackSize (int size)
Sets the size of the undo stack.
Parameters
size The new size.
Definition at line 106 of file ProDeOptions.cc.
{
    undoStackSize_ = size;
}
References undoStackSize_.
Referenced by ProDe::createDefaultOptions(), and ProDeOptionsDialog::writeProDeOptions().
undoStackSize()
int ProDeOptions::undoStackSize () const
Returns the size of the undo stack.
Returns
The size of the undo stack.
Definition at line 95 of file ProDeOptions.cc.
{
    return undoStackSize_;
}
References undoStackSize_.
Referenced by ProDeOptionsDialog::readProDeOptions().
Member Data Documentation
CONFIGURATION_NAME
const string ProDeOptions::CONFIGURATION_NAME = "prode-configuration" static
ObjectState name for ProDeOptions.
Definition at line 59 of file ProDeOptions.hh.
OSKEY_UNDO_STACK_SIZE
const string ProDeOptions::OSKEY_UNDO_STACK_SIZE = "undosize" static
ObjectState attribute key for the size of the undo stack.
Definition at line 61 of file ProDeOptions.hh.
Referenced by ProDeOptionsSerializer::convertToConfigFileFormat(), ProDeOptionsSerializer::convertToOptionsObjectFormat(), loadState(), and saveState().
undoStackSize_
int ProDeOptions::undoStackSize_ private
Undo stack size.
Definition at line 65 of file ProDeOptions.hh.
Referenced by loadState(), ProDeOptions(), saveState(), setUndoStackSize(), and undoStackSize().
The documentation for this class was generated from the following files:
ProDeOptions.hh
ProDeOptions.cc