OpenASIP: Reversible Class Reference
Reversible Class Reference abstract
#include <Reversible.hh>
Public Member Functions
virtual bool operator() ()=0
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Protected Member Functions
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
virtual void undoOnlyMe ()
Protected Attributes
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Private Attributes
int id_
Static Private Attributes
static int idCounter_ = 0
Detailed Description
Definition at line 36 of file Reversible.hh.
Constructor & Destructor Documentation
~Reversible()
Reversible::~Reversible () virtual
Delete the undo information. cannot revert after this
Definition at line 35 of file Reversible.cc.
{
    deleteChildren(postChildren_);
    deleteChildren(preChildren_);
}
References deleteChildren(), postChildren_, and preChildren_.
Reversible()
Reversible::Reversible () inline
Definition at line 44 of file Reversible.hh.
: id_(idCounter_++) {}
Member Function Documentation
deleteChildren()
void Reversible::deleteChildren (std::stack< Reversible * > & children)
Delete children without reverting them. They cannot be reverted after this
Definition at line 42 of file Reversible.cc.
{
    while (!children.empty()) {
        Reversible* child = children.top();
        assert(child != nullptr);
        children.pop();
        delete child;
    }
}
References assert.
Referenced by ~Reversible().
id()
int Reversible::id () inline
Definition at line 43 of file Reversible.hh.
{ return id_; }
References id_.
operator()()
virtual bool Reversible::operator() () pure virtual
This performs the operation. Returns true if success, false if fail.
Implemented in BFClearLiveRangeUse, BFDREEarly, BFDRELate, BFDRELoop, BFDropPreShared, BFEarlyBypasser, BFInsertLiveRangeUse, BFKillNode, BFLateBypass, BFLateBypasses, BFLateBypassGuard, BFPushAntidepDown, BFPushAntidepsDown, BFPushDepsUp, BFPushMoveUp, BFPushMoveUp2, BFRegCopy, BFRemoveLoopChecksAndJump, BFRenameLiveRange, BFRenameSource, BFRescheduleResultClose, BFRescheduleResultsClose, BFRescheduleSuccessorsClose, BFScheduleBU, BFScheduleExact, BFSchedule, BFSchedulePreLoopShared, BFScheduleTD, BFShareOperand, BFShareOperandLate, BFShareOperands, BFShareOperandsLate, BFShareOperandWithScheduled, BFSwapOperands, BFUnscheduleMove, BF2ScheduleFront, BFAssignToBody, BFConnectNodes, BFEarlyBypass, BFEarlyGuardBypass, BFMergeAndKeepUser, BFPostpassBypass, BFPostpassBypasser, BFPostpassDRE, BFPostpassLoopDRE, BFRemoveEdge, BFRemoveGuard, BFRemoveGuardFromSucc, BFRemoveGuardsFromSuccs, BFTryRemoveGuard, BFUnscheduleFromBody, and BFUpdateMoveOnBypass.
runChild() [1/2]
bool Reversible::runChild (Reversible * child, bool pre) protected
Tries to run another Reversible and takes ownership of it.
Parameters
if pre is true, make it a pre-child, if pre is false, make it a post-child.
Returns
true if running child succeeded, false if failed.
Definition at line 151 of file Reversible.cc.
{
    if (pre) {
        return runPreChild(child);
    } else {
        return runPostChild(child);
    }
}
References runPostChild(), and runPreChild().
runChild() [2/2]
bool Reversible::runChild (std::stack< Reversible * > & children, Reversible * child) protected
Tries to run another Reversible and takes ownership of it.
If the running succeeds, makes it a child. If the running fails, deletes it.
Returns
true if running child succeeded, false if failed.
Definition at line 109 of file Reversible.cc.
{
    if ((*child)()) {
        children.push(child);
        return true;
    } else {
        delete child;
        return false;
    }
}
Referenced by runPostChild(), runPreChild(), and BFMergeAndKeepUser::updateEdges().
runPostChild()
bool Reversible::runPostChild (Reversible * postChild) protected
Tries to run another Reversible (after running this).
If the running succeeds, makes it a post-child. If the running fails, deletes it.
Returns
true if running child succeeded, false if failed.
Definition at line 139 of file Reversible.cc.
{
    return runChild(postChildren_, postChild);
}
References postChildren_, and runChild().
Referenced by BFRegCopy::createAntidepsForReg(), BFLateBypass::operator()(), BFLateBypasses::operator()(), BFPushAntidepsDown::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultClose::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFScheduleTD::operator()(), BFShareOperandLate::operator()(), BFShareOperandsLate::operator()(), BFEarlyBypass::operator()(), BFMergeAndKeepUser::operator()(), BFPostpassBypass::operator()(), BFRemoveGuardFromSucc::operator()(), BFRemoveGuardsFromSuccs::operator()(), BFTryRemoveGuard::operator()(), runChild(), BFRegCopyAfter::splitMove(), BFRegCopyBefore::splitMove(), and BFPostpassBypasser::tryBypassNode().
runPreChild()
bool Reversible::runPreChild (Reversible * preChild) protected
Tries to run another Reversible (before running this).
If the running succeeds, makes it a pre-child. If the running fails, deletes it.
Returns
true if running child succeeded, false if failed.
Definition at line 127 of file Reversible.cc.
{
    return runChild(preChildren_, preChild);
}
References preChildren_, and runChild().
Referenced by BF2ScheduleFront::getMoveNodeFromFrontBU(), BFDropPreShared::operator()(), BFEarlyBypasser::operator()(), BFLateBypasses::operator()(), BFPushDepsUp::operator()(), BFPushMoveUp::operator()(), BFRenameSource::operator()(), BFRescheduleResultClose::operator()(), BFRescheduleResultsClose::operator()(), BFRescheduleSuccessorsClose::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFScheduleTD::operator()(), BFShareOperands::operator()(), BFEarlyBypass::operator()(), BFMergeAndKeepUser::operator()(), BFPostpassBypass::operator()(), BFRemoveGuard::operator()(), BFRemoveGuardFromSucc::operator()(), runChild(), BF2ScheduleFront::scheduleMove(), and BF2ScheduleFront::tryToScheduleMoveOuter().
undo()
void Reversible::undo () virtual
Undoes this and all children.
Definition at line 69 of file Reversible.cc.
                 {
    undoAndRemovePostChildren();
    undoOnlyMe();
    undoAndRemovePreChildren();
}
References undoAndRemovePostChildren(), undoAndRemovePreChildren(), and undoOnlyMe().
Referenced by BFLateBypass::operator()(), BFPushMoveUp2::operator()(), BFRescheduleResultClose::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFEarlyBypass::operator()(), BFPostpassBypass::operator()(), BFRemoveGuardFromSucc::operator()(), BFRemoveGuardsFromSuccs::operator()(), BF2Scheduler::revertTopOpt(), BF2ScheduleFront::scheduleFrontFromMove(), undoAndRemoveChildren(), BF2Scheduler::unschedule(), and BFMergeAndKeepUser::updateEdges().
undoAndRemoveChildren()
void Reversible::undoAndRemoveChildren (std::stack< Reversible * > & children) protected
Undoes one stack of children.
Definition at line 55 of file Reversible.cc.
{
    while (!children.empty()) {
        Reversible* child = children.top();
        assert(child != nullptr);
        children.pop();
        child->undo();
        delete child;
    }
}
References assert, and undo().
Referenced by BFPushMoveUp::operator()(), undoAndRemovePostChildren(), undoAndRemovePreChildren(), and BFRescheduleMove::undoOnlyMe().
undoAndRemovePostChildren()
void Reversible::undoAndRemovePostChildren () protected
Recursively calls undo for all children that were performed after this. So these are undoed before this is undoed
Definition at line 89 of file Reversible.cc.
{
    undoAndRemoveChildren(postChildren_);
}
References postChildren_, and undoAndRemoveChildren().
Referenced by BFRegCopyAfter::splitMove(), and undo().
undoAndRemovePreChildren()
void Reversible::undoAndRemovePreChildren () protected
Recursively calls undo for all children that were performed before this. So these are undoed after this is undoed
Definition at line 80 of file Reversible.cc.
{
    undoAndRemoveChildren(preChildren_);
}
References preChildren_, and undoAndRemoveChildren().
Referenced by BFLateBypasses::operator()(), BFPushDepsUp::operator()(), BFScheduleBU::operator()(), BFScheduleExact::operator()(), BFScheduleTD::operator()(), BFPostpassBypass::operator()(), and undo().
undoOnlyMe()
void Reversible::undoOnlyMe () protected virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented in BFClearLiveRangeUse, BFDRELoop, BFDropPreShared, BFInsertLiveRangeUse, BFKillNode, BFLateBypass, BFLateBypassGuard, BFRegCopy, BFRemoveLoopChecksAndJump, BFRescheduleMove, BFScheduleBU, BFScheduleExact, BFScheduleMove, BFSchedulePreLoopShared, BFScheduleTD, BFShareOperand, BFShareOperandLate, BFShareOperands, BFShareOperandsLate, BFShareOperandWithScheduled, BFSwapOperands, BFUnscheduleMove, BF2ScheduleFront, BFAssignToBody, BFConnectNodes, BFEarlyBypass, BFEarlyGuardBypass, BFMergeAndKeepUser, BFPostpassBypass, BFPostpassLoopDRE, BFRemoveEdge, BFRemoveGuard, BFRemoveGuardFromSucc, BFRenameLiveRange, BFUnscheduleFromBody, and BFUpdateMoveOnBypass.
Definition at line 98 of file Reversible.cc.
{}
Referenced by undo().
Member Data Documentation
id_
int Reversible::id_ private
Definition at line 61 of file Reversible.hh.
Referenced by id().
idCounter_
int Reversible::idCounter_ = 0 static private
Definition at line 62 of file Reversible.hh.
postChildren_
std::stack<Reversible*> Reversible::postChildren_ protected
Definition at line 58 of file Reversible.hh.
Referenced by BFLateBypass::operator()(), BFLateBypassGuard::operator()(), BFPushAntidepsDown::operator()(), BFPostpassBypasser::operator()(), BFRemoveGuardsFromSuccs::operator()(), runPostChild(), undoAndRemovePostChildren(), and ~Reversible().
preChildren_
std::stack<Reversible*> Reversible::preChildren_ protected
Definition at line 57 of file Reversible.hh.
Referenced by BFPushDepsUp::operator()(), BFPushMoveUp::operator()(), BFScheduleBU::operator()(), runPreChild(), undoAndRemovePreChildren(), and ~Reversible().
The documentation for this class was generated from the following files:
Reversible.hh
Reversible.cc