OpenASIP: TPEF::BinaryReader Class Reference
TPEF::BinaryReader Class Reference abstract
#include <BinaryReader.hh>
Public Types
typedef unsigned long Length
Public Member Functions
virtual ~BinaryReader ()
Static Public Member Functions
static Binary * readBinary (BinaryStream &stream)
Protected Member Functions
BinaryReader ()
virtual Binary * readData (BinaryStream &stream) const =0
Does actual reading and constructing part.
virtual bool isMyStreamType (BinaryStream &stream) const =0
Checks if given stream can be read with this BinaryReader class.
Static Protected Member Functions
static void registerBinaryReader (BinaryReader *reader)
Private Member Functions
BinaryReader (const BinaryReader &)
Static Private Attributes
static std::set< BinaryReader * > * prototypes_ = NULL
Contains instances of concrete BinaryReaders.
Detailed Description
Abstract base class for each actual BinaryReader class.
Handles registrations and storing of every BinaryReader instance. BinaryReaders implement Singleton design pattern.
Definition at line 51 of file BinaryReader.hh.
Member Typedef Documentation
Length
typedef unsigned long TPEF::BinaryReader::Length
Definition at line 53 of file BinaryReader.hh.
Constructor & Destructor Documentation
~BinaryReader()
TPEF::BinaryReader::~BinaryReader () virtual
Destructor.
Definition at line 64 of file BinaryReader.cc.
{
}
BinaryReader() [1/2]
TPEF::BinaryReader::BinaryReader () protected
Constructor.
Definition at line 58 of file BinaryReader.cc.
{
}
BinaryReader() [2/2]
TPEF::BinaryReader::BinaryReader (const BinaryReader &) private
Member Function Documentation
isMyStreamType()
virtual bool TPEF::BinaryReader::isMyStreamType (BinaryStream & stream) const protected pure virtual
Checks if given stream can be read with this BinaryReader class.
Implemented in TPEF::AOutReader, and TPEF::TPEFReader.
readBinary()
Binary * TPEF::BinaryReader::readBinary (BinaryStream & stream) static
Constructs a Binary object by reading data from the given binary stream.
Looks for the concrete binary reader class that can read the given binary stream. If found, that reader is used to read and construct a Binary object. This method cleans keytables of reference manager so after running this method reference manager contain keys of just read binary file.
Parameters
stream Stream to read binarys data from.
Returns
Binary that was created from the given stream.
Exceptions
InstanceNotFound If instance for reading wasn't found.
UnreachableStream If given stream can't be read.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some read value was out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
UnresolvedReference If there was unresolved references during reading.
Definition at line 88 of file BinaryReader.cc.
{
    if (prototypes_ != NULL) {
        unsigned long startPos = stream.readPosition();
        set<BinaryReader*>::iterator readers = prototypes_->begin();
        // checks if any BinaryReader registered can read this stream
        while (readers != prototypes_->end()) {
            // isMyStreamType should not move stream position.
            assert(stream.readPosition() == startPos);
            if ((*readers)->isMyStreamType(stream)) {
            // isMyStreamtype must leave stream as it was
                assert(stream.readPosition() == startPos);
                SafePointer::cleanupKeyTables();
                Binary *readBinary = (*readers)->readData(stream);
                try {
                    SafePointer::resolve();
                } catch (const UnresolvedReference &e) {
                    std::stringstream newErrorMsg;
                    newErrorMsg
                        << "Error was probably caused by a broken input file."
                        << std::endl
                        << "Unresolved references during reading: ";
                    UnresolvedReference error(
                        __FILE__, __LINE__, __func__,
                        newErrorMsg.str() + e.errorMessage());
                    error.setCause(e);
                    throw error;
                }
                SectionReader::finalizeBinary(readBinary, (*readers));
                try {
                    SafePointer::resolve();
                } catch (const UnresolvedReference &e) {
                    std::stringstream newErrorMsg;
                    newErrorMsg
                        << "Error was probably caused by a broken input file."
                        << std::endl
                        << "Unresolved references during finalization of "
                        << "reading: ";
                    UnresolvedReference error(
                        __FILE__, __LINE__, __func__,
                        newErrorMsg.str() + e.errorMessage());
                    error.setCause(e);
                    throw error;
                }
                // clean up after reading, to avoid abuse of reference manager
                SafePointer::cleanupKeyTables();
                return readBinary;
            }
            readers++;
        }
    }
    throw InstanceNotFound(
            __FILE__, __LINE__, __func__,
            "Cannot find suitable reader implementation for file.");
}
References __func__, assert, TPEF::ReferenceManager::SafePointer::cleanupKeyTables(), Exception::errorMessage(), TPEF::SectionReader::finalizeBinary(), prototypes_, readBinary(), TPEF::BinaryStream::readPosition(), TPEF::ReferenceManager::SafePointer::resolve(), and Exception::setCause().
Referenced by TTAProgram::Program::loadFromTPEF(), TTAProgram::Program::loadFromUnscheduledTPEF(), TTAProgram::Program::loadFromUnscheduledTPEF(), loadInputs(), SimulatorFrontend::loadProgram(), loadTPEF(), main(), and readBinary().
readData()
virtual Binary * TPEF::BinaryReader::readData (BinaryStream & stream) const protected pure virtual
Does actual reading and constructing part.
Implemented in TPEF::AOutReader, and TPEF::TPEFReader.
registerBinaryReader()
void TPEF::BinaryReader::registerBinaryReader (BinaryReader * reader) static protected
Registers a concrete BinaryReader instance for reading a file type.
Parameters
reader Concrete reader to be registred.
Definition at line 165 of file BinaryReader.cc.
{
    if (prototypes_ == NULL) {
        prototypes_ = new set<BinaryReader*>();
    }
    prototypes_->insert(prototypes_->end(),reader);
}
References prototypes_.
Referenced by TPEF::AOutReader::AOutReader(), and TPEF::TPEFReader::TPEFReader().
Member Data Documentation
prototypes_
set< BinaryReader * > * TPEF::BinaryReader::prototypes_ = NULL static private
Contains instances of concrete BinaryReaders.
Definition at line 74 of file BinaryReader.hh.
Referenced by readBinary(), and registerBinaryReader().
The documentation for this class was generated from the following files:
BinaryReader.hh
BinaryReader.cc