OpenASIP: ProximCDCmd Class Reference
ProximCDCmd Class Reference
#include <ProximCDCmd.hh>
Public Member Functions
ProximCDCmd ()
virtual ~ProximCDCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximCDCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for changing the Proxim working directory.
The command displays a directory dialog for choosing a new working directory.
Definition at line 44 of file ProximCDCmd.hh.
Constructor & Destructor Documentation
ProximCDCmd()
ProximCDCmd::ProximCDCmd ()
The Constructor.
Definition at line 43 of file ProximCDCmd.cc.
                        :
    GUICommand("Change Directory", NULL) {
    }
Referenced by create().
~ProximCDCmd()
ProximCDCmd::~ProximCDCmd () virtual
The Destructor.
Definition at line 51 of file ProximCDCmd.cc.
{
}
Member Function Documentation
create()
ProximCDCmd * ProximCDCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 102 of file ProximCDCmd.cc.
{
    return new ProximCDCmd();
}
References ProximCDCmd().
Do()
bool ProximCDCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 59 of file ProximCDCmd.cc.
                {
    assert(parentWindow() != NULL);
    wxDirDialog dialog(parentWindow(), _T("Choose a directory"), wxGetCwd());
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    std::string command =
        "cd \"" + WxConversion::toString(dialog.GetPath()) + "\"";
    wxGetApp().simulation()->lineReader().input(command);
    return true;
}
References assert, GUICommand::parentWindow(), and WxConversion::toString().
icon()
std::string ProximCDCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 82 of file ProximCDCmd.cc.
{
    return "cd.png";
}
id()
int ProximCDCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 91 of file ProximCDCmd.cc.
                      {
    return ProximConstants::COMMAND_CD;
}
References ProximConstants::COMMAND_CD.
isEnabled()
bool ProximCDCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 113 of file ProximCDCmd.cc.
                       {
    return true;
}
The documentation for this class was generated from the following files:
ProximCDCmd.hh
ProximCDCmd.cc