OpenASIP: BEMValidator Class Reference
BEMValidator Class Reference
#include <BEMValidator.hh>
Public Member Functions
BEMValidator (const BinaryEncoding &bem, const TTAMachine::Machine &machine)
~BEMValidator ()
bool validate ()
int errorCount () const
std::string errorMessage (int index) const
int warningCount () const
std::string warningMessage (int index) const
Private Types
typedef std::vector< std::string > StringVector
Vector type for string.
Private Member Functions
void checkMoveSlot (const TTAMachine::Bus &bus)
void checkDestinationField (const TTAMachine::Bus &bus)
void checkSourceField (const TTAMachine::Bus &bus)
void checkGuardField (const TTAMachine::Bus &bus)
void checkSocketCodeTable (const SocketEncoding &socketEnc)
void checkImmediateSlot (const TTAMachine::ImmediateSlot &immSlot)
void checkImmediateControlField ()
void checkLImmDstRegisterFields ()
void checkImemMauWidth (TTAMachine::ControlUnit &gcu)
bool needsSourceField (const MoveSlot &slot) const
bool needsSocketCodeTable (const SocketEncoding &socketEnc) const
Private Attributes
const BinaryEncoding & bem_
The binary encoding map.
const TTAMachine::Machine & machine_
The machine.
StringVector errorMessages_
Contains the error messages.
StringVector warningMessages_
Contains the warning messages.
Detailed Description
Validates binary encoding maps against machines. Checks that the BEM contains all the required information.
Definition at line 57 of file BEMValidator.hh.
Member Typedef Documentation
StringVector
typedef std::vector<std::string> BEMValidator::StringVector private
Vector type for string.
Definition at line 72 of file BEMValidator.hh.
Constructor & Destructor Documentation
BEMValidator()
BEMValidator::BEMValidator (const BinaryEncoding & bem, const TTAMachine::Machine & machine)
The constructor.
Parameters
bem The binary encoding map.
machine The machine.
Definition at line 72 of file BEMValidator.cc.
                                      :
    bem_(bem), machine_(machine) {
}
~BEMValidator()
BEMValidator::~BEMValidator ()
The destructor.
Definition at line 82 of file BEMValidator.cc.
{
}
Member Function Documentation
checkDestinationField()
void BEMValidator::checkDestinationField (const TTAMachine::Bus & bus) private
Checks the destination field of the given bus for errors.
If errors are found, inserts the error messages to the vector of error messages.
Definition at line 317 of file BEMValidator.cc.
{
    MoveSlot& moveSlot = bem_.moveSlot(bus.name());
    // collect the input sockets to a set
    typedef std::set<Socket*> SocketSet;
    SocketSet inputSockets;
    for (int i = 0; i < bus.segmentCount(); i++) {
        Segment* segment = bus.segment(i);
        for (int i = 0; i < segment->connectionCount(); i++) {
            Socket* socket = segment->connection(i);
            if (socket->portCount() > 0 &&
                socket->direction() == Socket::INPUT) {
                inputSockets.insert(socket);
            }
        }
    }
    // check the destination field
    if (inputSockets.size() > 1) {
        if (!moveSlot.hasDestinationField()) {
            format errorMsg(
                "Move slot of bus %1% does not contain destination field.");
            errorMsg % bus.name();
            errorMessages_.push_back(errorMsg.str());
        } else {
            DestinationField& dstField = moveSlot.destinationField();
            for (SocketSet::const_iterator iter = inputSockets.begin();
                 iter != inputSockets.end(); iter++) {
                Socket* socket = *iter;
                if (!dstField.hasSocketEncoding(socket->name())) {
                    format errorMsg(
                        "Destination field of move slot of bus %1% does not"
                        "have an encoding for socket %2%.");
                    errorMsg % bus.name() % socket->name();
                    errorMessages_.push_back(errorMsg.str());
                } else {
                    SocketEncoding& socketEnc = dstField.socketEncoding(
                        socket->name());
                    if (needsSocketCodeTable(socketEnc)) {
                        if (!socketEnc.hasSocketCodes()) {
                            format errorMsg(
                                "Encoding of socket %1% in destination "
                                "field of move slot %2% does not refer to "
                                "any socket code table.");
                            errorMsg % socket->name() % bus.name();
                            errorMessages_.push_back(errorMsg.str());
                        } else {
                            checkSocketCodeTable(socketEnc);
                        }
                    }
                }
            }
        }
    }
}
References bem_, checkSocketCodeTable(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), MoveSlot::destinationField(), TTAMachine::Socket::direction(), errorMessages_, MoveSlot::hasDestinationField(), SocketEncoding::hasSocketCodes(), SlotField::hasSocketEncoding(), TTAMachine::Socket::INPUT, BinaryEncoding::moveSlot(), TTAMachine::Component::name(), needsSocketCodeTable(), TTAMachine::Socket::portCount(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), and SlotField::socketEncoding().
Referenced by checkMoveSlot().
checkGuardField()
void BEMValidator::checkGuardField (const TTAMachine::Bus & bus) private
Checks the guard field of the given bus for errors.
If errors are found, inserts the error messages to the vector of error messages.
Parameters
bus The bus.
Definition at line 385 of file BEMValidator.cc.
{
    MoveSlot& slot = bem_.moveSlot(bus.name());
    if (bus.guardCount() < 2) {
        return;
    } else if (!slot.hasGuardField()) {
        format errorMsg("Move slot %1% does not contain guard field.");
        errorMsg % bus.name();
        errorMessages_.push_back(errorMsg.str());
        return;
    }
    GuardField& grdField = slot.guardField();
    for (int i = 0; i < bus.guardCount(); i++) {
        Guard* guard = bus.guard(i);
        UnconditionalGuard* ucGuard =
            dynamic_cast<UnconditionalGuard*>(guard);
        PortGuard* portGuard = dynamic_cast<PortGuard*>(guard);
        RegisterGuard* regGuard = dynamic_cast<RegisterGuard*>(guard);
        if (ucGuard != NULL &&
            !grdField.hasUnconditionalGuardEncoding(ucGuard->isInverted())) {
            format errorMsg(
                "Guard field of move slot %1% does not have encoding "
                "for always-%2% guard.");
            errorMsg % bus.name();
            if (ucGuard->isInverted()) {
                errorMsg % "false";
            } else {
                errorMsg % "true";
            }
            errorMessages_.push_back(errorMsg.str());
        } else if (portGuard != NULL) {
            FUPort* port = portGuard->port();
            FunctionUnit* fu = port->parentUnit();
            if (!grdField.hasFUGuardEncoding(
                    fu->name(), port->name(), portGuard->isInverted())) {
                format errorMsg(
                    "Guard field of move slot %1% does not have encoding "
                    "for %2% FU port guard of port %3% of FU %4%.");
                errorMsg % bus.name();
                if (portGuard->isInverted()) {
                    errorMsg % "inverted";
                } else {
                    errorMsg % "non-inverted";
                }
                errorMsg % port->name() % fu->name();
                errorMessages_.push_back(errorMsg.str());
            }
        } else if (regGuard != NULL) {
            string regFile = regGuard->registerFile()->name();
            if (!grdField.hasGPRGuardEncoding(
                    regFile, regGuard->registerIndex(),
                    regGuard->isInverted())) {
                format errorMsg(
                    "Guard field of move slot %1% does not have encoding "
                    "for %2% GPR guard of register %3% of register file "
                    "%4%.");
                errorMsg % bus.name();
                if (regGuard->isInverted()) {
                    errorMsg % "inverted";
                } else {
                    errorMsg % "non-inverted";
                }
                errorMsg % regGuard->registerIndex() % regFile;
                errorMessages_.push_back(errorMsg.str());
            }
        }
    }
}
References bem_, errorMessages_, TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), MoveSlot::guardField(), GuardField::hasFUGuardEncoding(), GuardField::hasGPRGuardEncoding(), MoveSlot::hasGuardField(), GuardField::hasUnconditionalGuardEncoding(), TTAMachine::Guard::isInverted(), BinaryEncoding::moveSlot(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), TTAMachine::RegisterGuard::registerFile(), and TTAMachine::RegisterGuard::registerIndex().
Referenced by checkMoveSlot().
checkImemMauWidth()
void BEMValidator::checkImemMauWidth (TTAMachine::ControlUnit & gcu) private
Checks that the instruction memory width (MAU) is greater or equal than the width of one instruction.
Parameters
gcu Global Control Unit of the machine
Definition at line 691 of file BEMValidator.cc.
{
    int imemWidth = 0;
    if (gcu.hasAddressSpace()) {
        imemWidth = gcu.addressSpace()->width();
    } else {
        string errorMsg("GCU does not have an address space");
        errorMessages_.push_back(errorMsg);
    }
    int instructionWidth = bem_.width();
    if (imemWidth < instructionWidth) {
        string warningMsg(
            "Warning: Instruction width is greater than the instruction "
            "memory width.");
        warningMessages_.push_back(warningMsg);
    }
}
References TTAMachine::FunctionUnit::addressSpace(), bem_, errorMessages_, TTAMachine::FunctionUnit::hasAddressSpace(), warningMessages_, TTAMachine::AddressSpace::width(), and BinaryEncoding::width().
checkImmediateControlField()
void BEMValidator::checkImmediateControlField () private
Checks that the BEM contains a valid immediate control field.
If errors are found, inserts the error messages to the vector of error messages.
Definition at line 596 of file BEMValidator.cc.
{
    Machine::InstructionTemplateNavigator iTempNav =
        machine_.instructionTemplateNavigator();
    if (iTempNav.count() > 1) {
        if (!bem_.hasImmediateControlField()) {
            string errorMsg("BEM does not contain immediate control field.");
            errorMessages_.push_back(errorMsg);
        } else {
            ImmediateControlField& field = bem_.immediateControlField();
            for (int i = 0; i < iTempNav.count(); i++) {
                InstructionTemplate* iTemp = iTempNav.item(i);
                if (!field.hasTemplateEncoding(iTemp->name())) {
                    format errorMsg(
                        "Immediate control field does not have encoding "
                        "for instruction template %1%.");
                    errorMsg % iTemp->name();
                    errorMessages_.push_back(errorMsg.str());
                }
            }
        }
    }
}
References bem_, TTAMachine::Machine::Navigator< ComponentType >::count(), errorMessages_, BinaryEncoding::hasImmediateControlField(), ImmediateControlField::hasTemplateEncoding(), BinaryEncoding::immediateControlField(), TTAMachine::Machine::instructionTemplateNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, and TTAMachine::Component::name().
Referenced by validate().
checkImmediateSlot()
void BEMValidator::checkImmediateSlot (const TTAMachine::ImmediateSlot & immSlot) private
Checks that the BEM contains a valid immediate slot field for the given immediate slot.
If errors are found, inserts the error messages to the vector of error messages.
Parameters
immSlot The immediate slot.
Definition at line 568 of file BEMValidator.cc.
{
    if (immSlot.width() == 0) {
        return;
    }
    if (!bem_.hasImmediateSlot(immSlot.name())) {
        format errorMsg(
            "BEM does not contain field for immediate slot %1%.");
        errorMsg % immSlot.name();
        errorMessages_.push_back(errorMsg.str());
    } else {
        ImmediateSlotField& field = bem_.immediateSlot(immSlot.name());
        if (field.width() < immSlot.width()) {
            format errorMsg("Immediate slot %1% is too narrow in BEM.");
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References bem_, errorMessages_, BinaryEncoding::hasImmediateSlot(), BinaryEncoding::immediateSlot(), TTAMachine::Component::name(), ImmediateSlotField::width(), and TTAMachine::ImmediateSlot::width().
Referenced by validate().
checkLImmDstRegisterFields()
void BEMValidator::checkLImmDstRegisterFields () private
Checks that the BEM contains valid long immediate destination register fields.
If errors are found, inserts the error messages to the vector of error messages.
Definition at line 628 of file BEMValidator.cc.
{
    Machine::InstructionTemplateNavigator itNav =
        machine_.instructionTemplateNavigator();
    Machine::ImmediateUnitNavigator iuNav =
        machine_.immediateUnitNavigator();
    for (int i = 0; i < itNav.count(); i++) {
        InstructionTemplate* iTemp = itNav.item(i);
        typedef std::set<std::string> StringSet;
        StringSet iTempDestinations;
        for (int i = 0; i < iuNav.count(); i++) {
            ImmediateUnit* iu = iuNav.item(i);
            if (iTemp->isOneOfDestinations(*iu) &&
                iu->numberOfRegisters() > 1) {
                iTempDestinations.insert(iu->name());
            }
        }
        StringSet destinationsInBEM;
        for (int i = 0; i < bem_.longImmDstRegisterFieldCount(); i++) {
            LImmDstRegisterField& field = bem_.longImmDstRegisterField(i);
            if (field.usedByInstructionTemplate(iTemp->name())) {
                string dstIU = field.immediateUnit(iTemp->name());
                destinationsInBEM.insert(dstIU);
                if (AssocTools::containsKey(iTempDestinations, dstIU)) {
                    ImmediateUnit* iu = iuNav.item(dstIU);
                    int regIndexWidth = MathTools::bitLength(
                        iu->numberOfRegisters() - 1);
                    if (field.width() < regIndexWidth) {
                        format errorMsg(
                            "Long immediate destination register field is "
                            "too narrow for destination %1% in instruction "
                            "template %2%.");
                        errorMsg % dstIU % iTemp->name();
                        errorMessages_.push_back(errorMsg.str());
                    }
                }
            }
        }
        StringSet intersection;
        SetTools::intersection(
            iTempDestinations, destinationsInBEM, intersection);
        if (intersection.size() < iTempDestinations.size()) {
            format errorMsg(
                "Long immediate destination register fields do not "
                "cover all the destinations of instruction template %1%.");
            errorMsg % iTemp->name();
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References bem_, MathTools::bitLength(), AssocTools::containsKey(), TTAMachine::Machine::Navigator< ComponentType >::count(), errorMessages_, LImmDstRegisterField::immediateUnit(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::instructionTemplateNavigator(), SetTools::intersection(), TTAMachine::InstructionTemplate::isOneOfDestinations(), TTAMachine::Machine::Navigator< ComponentType >::item(), BinaryEncoding::longImmDstRegisterField(), BinaryEncoding::longImmDstRegisterFieldCount(), machine_, TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), LImmDstRegisterField::usedByInstructionTemplate(), and LImmDstRegisterField::width().
Referenced by validate().
checkMoveSlot()
void BEMValidator::checkMoveSlot (const TTAMachine::Bus & bus) private
Checks that the move slot for the given bus is valid in BEM.
If errors are found, error messages are inserted to the vector of error messages.
Parameters
bus The bus.
Definition at line 204 of file BEMValidator.cc.
{
    if (!bem_.hasMoveSlot(bus.name())) {
        format errorMsg("BEM does not contain move slot for bus %1%.");
        errorMsg % bus.name();
        errorMessages_.push_back(errorMsg.str());
        return;
    }
    checkSourceField(bus);
    checkDestinationField(bus);
    checkGuardField(bus);
}
References bem_, checkDestinationField(), checkGuardField(), checkSourceField(), errorMessages_, BinaryEncoding::hasMoveSlot(), and TTAMachine::Component::name().
Referenced by validate().
checkSocketCodeTable()
void BEMValidator::checkSocketCodeTable (const SocketEncoding & socketEnc) private
Checks that the socket code table of the given socket encoding is valid.
If errors are found, inserts the error messages to the vector of error messages.
Parameters
socketEnc The socket encoding.
Definition at line 468 of file BEMValidator.cc.
{
    SlotField* slotField = socketEnc.parent();
    bool srcField = (dynamic_cast<SourceField*>(slotField) != NULL);
    string busName = slotField->parent()->name();
    string socketName = socketEnc.socketName();
    assert(socketEnc.hasSocketCodes());
    SocketCodeTable& table = socketEnc.socketCodes();
    Machine::SocketNavigator socketNav = machine_.socketNavigator();
    assert(socketNav.hasItem(socketName));
    Socket* socket = socketNav.item(socketName);
    for (int i = 0; i < socket->portCount(); i++) {
        Port* port = socket->port(i);
        Unit* parentUnit = port->parentUnit();
        FunctionUnit* fu = dynamic_cast<FunctionUnit*>(parentUnit);
        RegisterFile* rf = dynamic_cast<RegisterFile*>(parentUnit);
        ImmediateUnit* iu = dynamic_cast<ImmediateUnit*>(parentUnit);
        if (fu != NULL) {
            BaseFUPort* fuPort = dynamic_cast<BaseFUPort*>(port);
            assert(fuPort != NULL);
            if (fuPort->isOpcodeSetting()) {
                for (int i = 0; i < fu->operationCount(); i++) {
                    HWOperation* operation = fu->operation(i);
                    if (!table.hasFUPortCode(
                            fu->name(), port->name(), operation->name())) {
                        format errorMsg(
                            "Socket code table of socket %1% in %2% field "
                            "of move slot %3% does not contain FU port code "
                            "for operation %4% for port %5% of FU %6%.");
                        errorMsg % socketEnc.socketName();
                        if (srcField) {
                            errorMsg % "source";
                        } else {
                            errorMsg % "destination";
                        }
                        errorMsg % busName % operation->name() %
                            port->name() % fu->name();
                        errorMessages_.push_back(errorMsg.str());
                    }
                }
            } else {
                if (!table.hasFUPortCode(fu->name(), port->name())) {
                    format errorMsg(
                        "Socket code table of socket %1% in %2% field of "
                        "move slot %3% does not contain FU port code for "
                        "port %4% of FU %5%.");
                    errorMsg % socketEnc.socketName();
                    if (srcField) {
                        errorMsg % "source";
                    } else {
                        errorMsg % "destination";
                    }
                    errorMsg % busName % port->name() % fu->name();
                    errorMessages_.push_back(errorMsg.str());
                }
            }
        } else if (rf != NULL && iu == NULL
                              && !table.hasRFPortCode(rf->name())) {
            format errorMsg(
                "Socket code table of socket %1% in %2% field of move "
                "slot %3% does not contain RF port code for RF %4%.");
            errorMsg % socketName;
            if (srcField) {
                errorMsg % "source";
            } else {
                errorMsg % "destination";
            }
            errorMsg % busName % rf->name();
            errorMessages_.push_back(errorMsg.str());
        } else if (iu != NULL && !table.hasIUPortCode(iu->name())) {
            format errorMsg(
                "Socket code table of socket %1% in %2% field of move slot "
                "%3% does not contain IU port code for IU %4%.");
            errorMsg % socketName;
            if (srcField) {
                errorMsg % "source";
            } else {
                errorMsg % "destination";
            }
            errorMsg % busName % iu->name();
            errorMessages_.push_back(errorMsg.str());
        }
    }
}
References assert, errorMessages_, SocketCodeTable::hasFUPortCode(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), SocketCodeTable::hasIUPortCode(), SocketCodeTable::hasRFPortCode(), SocketEncoding::hasSocketCodes(), TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), SlotField::parent(), SocketEncoding::parent(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), SocketEncoding::socketCodes(), SocketEncoding::socketName(), and TTAMachine::Machine::socketNavigator().
Referenced by checkDestinationField(), and checkSourceField().
checkSourceField()
void BEMValidator::checkSourceField (const TTAMachine::Bus & bus) private
Checks the source field of the given bus for errors.
If errors are found, inserts the error messages to the vector of error messages.
Definition at line 226 of file BEMValidator.cc.
{
    MoveSlot& moveSlot = bem_.moveSlot(bus.name());
    // collect the output sockets to a set
    typedef std::set<Socket*> SocketSet;
    SocketSet outputSockets;
    for (int i = 0; i < bus.segmentCount(); i++) {
        Segment* segment = bus.segment(i);
        for (int i = 0; i < segment->connectionCount(); i++) {
            Socket* socket = segment->connection(i);
            if (socket->portCount() > 0 &&
                socket->direction() == Socket::OUTPUT) {
                outputSockets.insert(socket);
            }
        }
    }
    if (needsSourceField(moveSlot)) {
        if (!moveSlot.hasSourceField()) {
            format errorMsg(
                "Move slot of bus %1% does not contain source field.");
            errorMsg % bus.name();
            errorMessages_.push_back(errorMsg.str());
        } else {
            // check the source field for socket encodings
            SourceField& srcField = moveSlot.sourceField();
            for (SocketSet::const_iterator iter = outputSockets.begin();
                 iter != outputSockets.end(); iter++) {
                Socket* socket = *iter;
                if (!srcField.hasSocketEncoding(socket->name())) {
                    format errorMsg(
                        "Source field of move slot of bus %1% does not"
                        "have an encoding for socket %2%.");
                    errorMsg % bus.name() % socket->name();
                    errorMessages_.push_back(errorMsg.str());
                } else {
                    SocketEncoding& socketEnc = srcField.socketEncoding(
                        socket->name());
                    if (needsSocketCodeTable(socketEnc)) {
                        if (!socketEnc.hasSocketCodes()) {
                            format errorMsg(
                                "Encoding of socket %1% in source "
                                "field of move slot %2% does not refer to "
                                "any socket code table.");
                            errorMsg % socket->name() % bus.name();
                            errorMessages_.push_back(errorMsg.str());
                        } else {
                            checkSocketCodeTable(socketEnc);
                        }
                    }
                }
            }
            // check the source field for bridge encodings
            Machine::BridgeNavigator bridgeNav = machine_.bridgeNavigator();
            for (int i = 0; i < bridgeNav.count(); i++) {
                Bridge* bridge = bridgeNav.item(i);
                if (bridge->destinationBus() == &bus &&
                    !moveSlot.sourceField().hasBridgeEncoding(
                        bridge->name())) {
                    format errorMsg(
                        "Source field of bus %1% does not have encoding "
                        "for bridge %2%.");
                    errorMsg % bus.name() % bridge->name();
                    errorMessages_.push_back(errorMsg.str());
                }
            }
            // check the source field for immediate encoding
            if (bus.immediateWidth() > 0 &&
                !srcField.hasImmediateEncoding()) {
                format errorMsg(
                    "Source field of bus %1% does not have an immediate "
                    "encoding.");
                errorMsg % bus.name();
                errorMessages_.push_back(errorMsg.str());
            }
        }
    }
}
References bem_, TTAMachine::Machine::bridgeNavigator(), checkSocketCodeTable(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bridge::destinationBus(), TTAMachine::Socket::direction(), errorMessages_, SourceField::hasBridgeEncoding(), SourceField::hasImmediateEncoding(), SocketEncoding::hasSocketCodes(), SlotField::hasSocketEncoding(), MoveSlot::hasSourceField(), TTAMachine::Bus::immediateWidth(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, BinaryEncoding::moveSlot(), TTAMachine::Component::name(), needsSocketCodeTable(), needsSourceField(), TTAMachine::Socket::OUTPUT, TTAMachine::Socket::portCount(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), SlotField::socketEncoding(), and MoveSlot::sourceField().
Referenced by checkMoveSlot().
errorCount()
int BEMValidator::errorCount () const
Returns the number of errors found.
Returns
The number of errors.
Definition at line 145 of file BEMValidator.cc.
{
    return errorMessages_.size();
}
References errorMessages_.
Referenced by errorMessage(), ProGe::ProGeUI::generateProcessor(), and validate().
errorMessage()
std::string BEMValidator::errorMessage (int index) const
Returns an error message by the given index.
Parameters
index The index.
Returns
The error message by the given index.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 159 of file BEMValidator.cc.
{
    if (index < 0 || index >= errorCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    } else {
        return errorMessages_[index];
    }
}
References __func__, errorCount(), and errorMessages_.
Referenced by ProGe::ProGeUI::generateProcessor().
needsSocketCodeTable()
bool BEMValidator::needsSocketCodeTable (const SocketEncoding & socketEnc) const private
Tells whether the given socket encoding needs a socket code table.
Parameters
socketEnc The socket encoding.
Returns
True if the socket encoding needs a socket code table, otherwise false.
Definition at line 767 of file BEMValidator.cc.
{
    string socketName = socketEnc.socketName();
    Machine::SocketNavigator socketNav = machine_.socketNavigator();
    assert(socketNav.hasItem(socketName));
    Socket* socket = socketNav.item(socketName);
    if (socket->portCount() > 1) {
        return true;
    } else if (socket->portCount() == 0) {
        return false;
    }
    Port* port = socket->port(0);
    Unit* unit = port->parentUnit();
    BaseRegisterFile* rf = dynamic_cast<BaseRegisterFile*>(unit);
    if (rf != NULL && rf->numberOfRegisters() > 1) {
        return true;
    }
    FunctionUnit* fu = dynamic_cast<FunctionUnit*>(unit);
    if (fu != NULL) {
        BaseFUPort* fuPort = dynamic_cast<BaseFUPort*>(port);
        assert(fuPort != NULL);
        if (fuPort->isOpcodeSetting() && fu->operationCount() > 1) {
            return true;
        }
    }
    return false;
}
References assert, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::BaseFUPort::isOpcodeSetting(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::Port::parentUnit(), TTAMachine::Socket::port(), TTAMachine::Socket::portCount(), SocketEncoding::socketName(), and TTAMachine::Machine::socketNavigator().
Referenced by checkDestinationField(), and checkSourceField().
needsSourceField()
bool BEMValidator::needsSourceField (const MoveSlot & slot) const private
Tells whether the given move slot needs source field.
Parameters
slot The move slot.
Returns
True if the move slot needs source field, otherwise false.
Definition at line 716 of file BEMValidator.cc.
{
    string busName = slot.name();
    Machine::BusNavigator busNav = machine_.busNavigator();
    assert(busNav.hasItem(busName));
    Bus* bus = busNav.item(busName);
    // check output sockets
    for (int i = 0; i < bus->segmentCount(); i++) {
        Segment* segment = bus->segment(i);
        for (int i = 0; i < segment->connectionCount(); i++) {
            Socket* socket = segment->connection(i);
            if (socket->portCount() > 0 &&
                socket->direction() == Socket::OUTPUT) {
                return true;
            }
        }
    }
    // check bridges
    if (bus->hasNextBus()) {
        Bus* nextBus = bus->nextBus();
        if (bus->canRead(*nextBus)) {
            return true;
        }
    }
    if (bus->hasPreviousBus()) {
        Bus* prevBus = bus->previousBus();
        if (bus->canRead(*prevBus)) {
            return true;
        }
    }
    // check immediate
    if (bus->immediateWidth() > 0) {
        return true;
    }
    return false;
}
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Bus::canRead(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), TTAMachine::Socket::direction(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Bus::hasNextBus(), TTAMachine::Bus::hasPreviousBus(), TTAMachine::Bus::immediateWidth(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, MoveSlot::name(), TTAMachine::Bus::nextBus(), TTAMachine::Socket::OUTPUT, TTAMachine::Socket::portCount(), TTAMachine::Bus::previousBus(), TTAMachine::Bus::segment(), and TTAMachine::Bus::segmentCount().
Referenced by checkSourceField().
validate()
bool BEMValidator::validate ()
Validates the binary encoding map against the machine.
Updates the error and warning messages that can be queried with {error,warning}Count and {error,warning}Message methods.
Returns
True if the BEM is valid for the machine, otherwise false.
Definition at line 95 of file BEMValidator.cc.
                       {
    errorMessages_.clear();
    // check move slots for each bus
    Machine::BusNavigator busNav = machine_.busNavigator();
    for (int i = 0; i < busNav.count(); i++) {
        Bus* bus = busNav.item(i);
        checkMoveSlot(*bus);
    }
    // check immediate slots
    Machine::ImmediateSlotNavigator immSlotNav =
        machine_.immediateSlotNavigator();
    for (int i = 0; i < immSlotNav.count(); i++) {
        ImmediateSlot* immSlot = immSlotNav.item(i);
        checkImmediateSlot(*immSlot);
    }
    // check immediate control field
    checkImmediateControlField();
    // check long immediate destination register fields
    checkLImmDstRegisterFields();
    TTAMachine::ControlUnit* gcu = machine_.controlUnit();
    if (gcu == NULL) {
        string errorMsg("Error: Couldn't find GCU from machine");
        errorMessages_.push_back(errorMsg);
    } else {
        // no reason to check this as we are generating the
        // instruction memory width according to the instruction
        // width always (instruction indexed imem assumed)
        // checkImemMauWidth(*gcu);
    }
    if (errorCount() == 0) {
        return true;
    } else {
        return false;
    }
}
References TTAMachine::Machine::busNavigator(), checkImmediateControlField(), checkImmediateSlot(), checkLImmDstRegisterFields(), checkMoveSlot(), TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), errorCount(), errorMessages_, TTAMachine::Machine::immediateSlotNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), and machine_.
Referenced by ProGe::ProGeUI::generateProcessor().
warningCount()
int BEMValidator::warningCount () const
Returns the number of warnings found.
Returns
The number of warnings.
Definition at line 173 of file BEMValidator.cc.
{
    return warningMessages_.size();
}
References warningMessages_.
Referenced by ProGe::ProGeUI::generateProcessor(), and warningMessage().
warningMessage()
std::string BEMValidator::warningMessage (int index) const
Returns an warning message by the given index.
Parameters
index The index.
Returns
The warning message by the given index.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of errors.
Definition at line 186 of file BEMValidator.cc.
{
    if (index < 0 || index >= warningCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    } else {
        return warningMessages_[index];
    }
}
References __func__, warningCount(), and warningMessages_.
Referenced by ProGe::ProGeUI::generateProcessor().
Member Data Documentation
bem_
const BinaryEncoding& BEMValidator::bem_ private
The binary encoding map.
Definition at line 88 of file BEMValidator.hh.
Referenced by checkDestinationField(), checkGuardField(), checkImemMauWidth(), checkImmediateControlField(), checkImmediateSlot(), checkLImmDstRegisterFields(), checkMoveSlot(), and checkSourceField().
errorMessages_
StringVector BEMValidator::errorMessages_ private
Contains the error messages.
Definition at line 93 of file BEMValidator.hh.
Referenced by checkDestinationField(), checkGuardField(), checkImemMauWidth(), checkImmediateControlField(), checkImmediateSlot(), checkLImmDstRegisterFields(), checkMoveSlot(), checkSocketCodeTable(), checkSourceField(), errorCount(), errorMessage(), and validate().
machine_
const TTAMachine::Machine& BEMValidator::machine_ private
The machine.
Definition at line 90 of file BEMValidator.hh.
Referenced by checkImmediateControlField(), checkLImmDstRegisterFields(), checkSocketCodeTable(), checkSourceField(), needsSocketCodeTable(), needsSourceField(), and validate().
warningMessages_
StringVector BEMValidator::warningMessages_ private
Contains the warning messages.
Definition at line 95 of file BEMValidator.hh.
Referenced by checkImemMauWidth(), warningCount(), and warningMessage().
The documentation for this class was generated from the following files:
BEMValidator.hh
BEMValidator.cc