OpenASIP: AboutDialog Class Reference
AboutDialog Class Reference
#include <AboutDialog.hh>
Public Member Functions
AboutDialog (wxWindow *parent)
virtual ~AboutDialog ()
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void setTexts ()
Detailed Description
Dialog with editor logo, name, version and copyright information.
Definition at line 18 of file AboutDialog.hh.
Constructor & Destructor Documentation
AboutDialog()
AboutDialog::AboutDialog (wxWindow * parent)
The Constructor.
Parameters
parent Parent window of the dialog.
Definition at line 52 of file AboutDialog.cc.
                                        :
    wxDialog(parent, -1, _T(""), wxDefaultPosition) {
    createContents(this, true, true);
    // set widget texts
    setTexts();
}
References createContents(), and setTexts().
~AboutDialog()
AboutDialog::~AboutDialog () virtual
The Destructor.
Definition at line 64 of file AboutDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * AboutDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window. Initially generated with wxDesigner, the code will be cleaned up later.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 98 of file AboutDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBitmap logo;
    wxString filename = WxConversion::toWxString(
         ProDe::bitmapsDirPath() + ProDeConstants::EDITOR_LOGO_PATH);
    logo.LoadFile(filename, wxBITMAP_TYPE_PNG);
    wxStaticBitmap* dialogLogo = new wxStaticBitmap(parent, -1, logo);
    item0->Add(dialogLogo, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item3 = new wxBoxSizer( wxVERTICAL );
    wxStaticText *item4 =
    new wxStaticText(parent, -1, ProDeConstants::EDITOR_NAME,
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 =
    new wxStaticText(parent, -1, _T("OpenASIP ") +
                   WxConversion::toWxString(VERSION),
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item6 =
    new wxStaticText(parent, -1,
             ProDeConstants::EDITOR_COPYRIGHT_TEXT,
             wxDefaultPosition, wxDefaultSize, 0);
    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item7 =
    new wxStaticLine(parent, -1, wxDefaultPosition,
             wxSize(20,-1), wxLI_HORIZONTAL);
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxButton *item8 =
    new wxButton(parent, wxID_OK, wxT("&OK"), wxDefaultPosition,
             wxDefaultSize, 0);
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer) {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    return item0;
}
References ProDe::bitmapsDirPath(), ProDeConstants::EDITOR_COPYRIGHT_TEXT, ProDeConstants::EDITOR_LOGO_PATH, ProDeConstants::EDITOR_NAME, WxConversion::toWxString(), and TRUE.
Referenced by AboutDialog().
setTexts()
void AboutDialog::setTexts () private
Sets texts for widgets.
Definition at line 72 of file AboutDialog.cc.
                      {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_ABOUT_DIALOG_TITLE);
    string title = fmt.str();
    title.append(WxConversion::toString(ProDeConstants::EDITOR_NAME));
    SetTitle(WxConversion::toWxString(title));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
}
References ProDeConstants::EDITOR_NAME, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), ProDeTextGenerator::TXT_ABOUT_DIALOG_TITLE, and GUITextGenerator::TXT_BUTTON_OK.
Referenced by AboutDialog().
The documentation for this class was generated from the following files:
AboutDialog.hh
AboutDialog.cc