OpenASIP: InstructionField Class Reference
InstructionField Class Reference abstract
#include <InstructionField.hh>
Public Member Functions
virtual ~InstructionField ()
InstructionField * parent () const
virtual int childFieldCount () const =0
virtual InstructionField & childField (int position) const
virtual int width () const =0
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Protected Member Functions
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions
static void reorderSubfields (ObjectState *state)
Private Attributes
int relativePos_
Indicates the relative position of the field.
int extraBits_
The number of extra bits.
InstructionField * parent_
The parent instruction field.
Detailed Description
InstructionField is an abstract base class that represents the properties common to all types of bit fields of the TTA instruction word.
Definition at line 43 of file InstructionField.hh.
Constructor & Destructor Documentation
~InstructionField()
InstructionField::~InstructionField () virtual
The destructor.
Definition at line 88 of file InstructionField.cc.
{
}
InstructionField() [1/2]
InstructionField::InstructionField (InstructionField * parent) protected
The constructor.
Parameters
relativePosition Relative position of the instruction field within its parent field.
parent The parent instruction field.
Definition at line 56 of file InstructionField.cc.
                                                           :
    relativePos_(0), extraBits_(0), parent_(parent) {
    if (parent != NULL) {
        relativePos_ = parent->childFieldCount();
    }
}
References childFieldCount(), parent(), and relativePos_.
InstructionField() [2/2]
InstructionField::InstructionField (const ObjectState * state, InstructionField * parent) protected
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent instruction field.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 75 of file InstructionField.cc.
    : relativePos_(0), extraBits_(0), parent_(parent) {
    if (parent != NULL) {
        relativePos_ = parent->childFieldCount();
    }
    loadState(state);
}
References childFieldCount(), loadState(), parent(), and relativePos_.
Member Function Documentation
bitPosition()
int InstructionField::bitPosition () const
Returns the bit-accurate position of the field within its parent field.
Returns
The position.
Definition at line 132 of file InstructionField.cc.
{
    InstructionField* parent = this->parent();
    if (parent == NULL) {
        return 0;
    }
    int position(0);
    for (int i = 0; i < relativePosition(); i++) {
        InstructionField& childField = parent->childField(i);
        position += childField.width();
    }
    return position;
}
References childField(), parent(), relativePosition(), and width().
Referenced by BEMTester::canAddComponentPriorityEncoding(), BEMTester::fieldsOverlap(), ProGe::RV32MicroCodeGenerator::findBusWidths(), printImmediateControlField(), printLImmDstRegisterField(), printMoveSlot(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeInstructionTemplateProcedures().
childField()
InstructionField & InstructionField::childField (int position) const virtual
Returns the child field which has the given relative position within the instruction field.
This base class implementation just checks whether the given position is out of range and throw the exception if necessary.
Parameters
position The position.
Exceptions
OutOfRange If the position is negative or not smaller than the number of child fields.
Reimplemented in BinaryEncoding, MoveSlot, NullInstructionField, SlotField, GuardField, and ImmediateControlField.
Definition at line 117 of file InstructionField.cc.
{
    if (position < 0 || position >= childFieldCount()) {
        const string procName = "InstructionField::childField";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    return NullInstructionField::instance();
}
References childFieldCount(), and NullInstructionField::instance().
Referenced by bitPosition(), MoveSlot::childField(), and setRelativePosition().
childFieldCount()
virtual int InstructionField::childFieldCount () const pure virtual
Returns the number of (immediate) child fields within the instruction field.
Implemented in BinaryEncoding, GuardField, ImmediateControlField, ImmediateSlotField, LImmDstRegisterField, MoveSlot, NullInstructionField, and SlotField.
Referenced by childField(), InstructionField(), InstructionField(), and setRelativePosition().
extraBits()
int InstructionField::extraBits () const
Returns the number of extra bits in the field.
Returns
The number of extra bits.
Definition at line 229 of file InstructionField.cc.
{
    return extraBits_;
}
References extraBits_.
Referenced by BEMGenerator::addSubfields(), BridgeEncoding::bitPosition(), NOPEncoding::bitPosition(), ImmediateEncoding::encodingPosition(), ImmediateEncoding::immediatePosition(), printGuardFieldEncodings(), printImmediateControlField(), printSlotFieldEncodings(), printSourceFieldEncodings(), saveState(), SocketEncoding::socketCodePosition(), SocketEncoding::socketIDPosition(), GuardField::width(), ImmediateControlField::width(), SlotField::width(), SourceField::width(), and BinaryEncoding::width().
loadState()
void InstructionField::loadState (const ObjectState * state) virtual
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Implements Serializable.
Reimplemented in BinaryEncoding, GuardField, ImmediateControlField, ImmediateSlotField, LImmDstRegisterField, MoveSlot, SlotField, and SourceField.
Definition at line 242 of file InstructionField.cc.
{
    const string procName = "InstructionField::loadState";
    try {
        setExtraBits(state->intAttribute(OSKEY_EXTRA_BITS));
            if (relativePosition() != state->intAttribute(OSKEY_POSITION)) {
                format errorMsg(
                    "Invalid relative position %1%. Should be %2%.");
                errorMsg % state->stringAttribute(OSKEY_POSITION) %
                    relativePosition();
                throw ObjectStateLoadingException(
                    __FILE__, __LINE__, __func__, errorMsg.str());
            }
    } catch (const Exception& exception) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References __func__, Exception::errorMessage(), ObjectState::intAttribute(), OSKEY_EXTRA_BITS, OSKEY_POSITION, relativePosition(), setExtraBits(), and ObjectState::stringAttribute().
Referenced by InstructionField(), GuardField::loadState(), ImmediateControlField::loadState(), ImmediateSlotField::loadState(), LImmDstRegisterField::loadState(), MoveSlot::loadState(), and SlotField::loadState().
parent()
InstructionField * InstructionField::parent () const
Returns the parent instruction field.
Returns NULL if the field has no parent field (BinaryEncoding).
Returns
The parent instruction field.
Definition at line 100 of file InstructionField.cc.
{
    return parent_;
}
References parent_.
Referenced by bitPosition(), InstructionField(), InstructionField(), GuardField::parent(), ImmediateControlField::parent(), ImmediateSlotField::parent(), LImmDstRegisterField::parent(), MoveSlot::parent(), SlotField::parent(), setParent(), setRelativePosition(), and BinaryEncoding::unsetImmediateControlField().
relativePosition()
int InstructionField::relativePosition () const
Returns the relative position of the field compared to sibling fields.
If the field is the rightmost field, returns 0. The leftmost field returns the number of sibling fields - 1.
Returns
The relative position.
Definition at line 160 of file InstructionField.cc.
{
    return relativePos_;
}
References relativePos_.
Referenced by bitPosition(), BinaryEncoding::childField(), MoveSlot::childField(), loadState(), ImmediateControlField::saveState(), saveState(), and setRelativePosition().
reorderSubfields()
void InstructionField::reorderSubfields (ObjectState * state) static protected
Sorts the child ObjectState instances of the given ObjectState instance such that they are returned by child(index) method in the correct order.
The correct order means that at first the rightmost subfield is returned and then the next to left and so on.
Parameters
state The ObjectState instance.
Definition at line 297 of file InstructionField.cc.
{
    typedef list<ObjectState*> OSList;
    OSList list;
    for (int i = 0; i < state->childCount();) {
        ObjectState* child = state->child(i);
        if (child->hasAttribute(InstructionField::OSKEY_POSITION)) {
            state->removeChild(child);
            int position = child->intAttribute(
                InstructionField::OSKEY_POSITION);
            // insert the object to the list at correct position
            bool inserted = false;
            for (OSList::iterator iter = list.begin(); iter != list.end();
                 iter++) {
                ObjectState* item = *iter;
                int itemPosition = item->intAttribute(
                    InstructionField::OSKEY_POSITION);
                if (itemPosition > position) {
                    list.insert(iter, child);
                    inserted = true;
                    break;
                }
            }
            if (!inserted) {
                list.push_back(child);
            }
        } else {
            i++;
        }
    }
    // add the sub fields again in the correct order
    for (OSList::const_iterator iter = list.begin(); iter != list.end();
         iter++) {
        ObjectState* child = *iter;
        state->addChild(child);
    }
}
References ObjectState::addChild(), ObjectState::child(), ObjectState::childCount(), ObjectState::hasAttribute(), ObjectState::intAttribute(), OSKEY_POSITION, and ObjectState::removeChild().
Referenced by BinaryEncoding::loadState(), and MoveSlot::loadState().
saveState()
ObjectState * InstructionField::saveState () const virtual
Saves the state of the object to an ObjectState tree.
Returns
The newly created ObjectState tree.
Implements Serializable.
Reimplemented in BinaryEncoding, DestinationField, GuardField, ImmediateControlField, ImmediateSlotField, LImmDstRegisterField, MoveSlot, SlotField, and SourceField.
Definition at line 268 of file InstructionField.cc.
{
    ObjectState* state = new ObjectState(OSNAME_INSTRUCTION_FIELD);
    state->setAttribute(OSKEY_EXTRA_BITS, extraBits());
    state->setAttribute(OSKEY_POSITION, relativePosition());
    return state;
}
References extraBits(), OSKEY_EXTRA_BITS, OSKEY_POSITION, OSNAME_INSTRUCTION_FIELD, relativePosition(), and ObjectState::setAttribute().
Referenced by GuardField::saveState(), ImmediateControlField::saveState(), ImmediateSlotField::saveState(), LImmDstRegisterField::saveState(), MoveSlot::saveState(), and SlotField::saveState().
setExtraBits()
void InstructionField::setExtraBits (int bits)
Sets the number of extra (zero) bits to the field.
The field can be forced longer than necessary by defining some number of extra bits. In practice, there will be the given amount of zeros always in the MSB end of the field.
Parameters
bits The number of extra bits.
Exceptions
OutOfRange If the given number is negative.
Definition at line 214 of file InstructionField.cc.
{
    if (bits < 0) {
        const string procName = "InstructionField::setExtraBits";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    extraBits_ = bits;
}
References extraBits_.
Referenced by BEMGenerator::addSubfields(), and loadState().
setParent()
void InstructionField::setParent (InstructionField * parent) protected
Sets the parent instruction field.
Parameters
parent The parent field.
Definition at line 282 of file InstructionField.cc.
{
    parent_ = parent;
}
References parent(), and parent_.
Referenced by DestinationField::DestinationField(), DestinationField::DestinationField(), GuardField::GuardField(), GuardField::GuardField(), ImmediateControlField::ImmediateControlField(), ImmediateControlField::ImmediateControlField(), ImmediateSlotField::ImmediateSlotField(), ImmediateSlotField::ImmediateSlotField(), LImmDstRegisterField::LImmDstRegisterField(), LImmDstRegisterField::LImmDstRegisterField(), MoveSlot::MoveSlot(), MoveSlot::MoveSlot(), SourceField::SourceField(), SourceField::SourceField(), DestinationField::~DestinationField(), GuardField::~GuardField(), ImmediateControlField::~ImmediateControlField(), ImmediateSlotField::~ImmediateSlotField(), LImmDstRegisterField::~LImmDstRegisterField(), MoveSlot::~MoveSlot(), and SourceField::~SourceField().
setRelativePosition()
void InstructionField::setRelativePosition (int position) virtual
Sets a new relative position for the field.
Parameters
position The new relative position.
Exceptions
OutOfRange If the given position is negative.
Definition at line 172 of file InstructionField.cc.
{
    if (position < 0 || position >= parent()->childFieldCount()) {
        const string procName = "InstructionField::setRelativePosition";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    InstructionField& fieldToMove = parent()->childField(position);
    relativePos_ = position;
    int childFields = parent()->childFieldCount();
    int emptyPosition(-1);
    for (int i = 0; i < childFields; i++) {
        if (&parent()->childField(i) == &NullInstructionField::instance()) {
            emptyPosition = i;
            break;
        }
    }
    if (emptyPosition != -1) {
        if (emptyPosition < fieldToMove.relativePosition()) {
            fieldToMove.
            setRelativePosition(fieldToMove.relativePosition() - 1);
        } else if (emptyPosition > fieldToMove.relativePosition()) {
            fieldToMove.
            setRelativePosition(fieldToMove.relativePosition() + 1);
        } else {
            assert(false);
        }
    }
}
References assert, childField(), childFieldCount(), NullInstructionField::instance(), parent(), relativePos_, relativePosition(), and setRelativePosition().
Referenced by GuardField::GuardField(), and setRelativePosition().
width()
virtual int InstructionField::width () const pure virtual
Returns the bit width of the field.
Implemented in BinaryEncoding, GuardField, ImmediateControlField, ImmediateSlotField, LImmDstRegisterField, MoveSlot, NullInstructionField, SlotField, and SourceField.
Referenced by bitPosition(), BEMTester::fieldsOverlap(), and printInstructionLayout().
Member Data Documentation
extraBits_
int InstructionField::extraBits_ private
The number of extra bits.
Definition at line 90 of file InstructionField.hh.
Referenced by extraBits(), and setExtraBits().
OSKEY_EXTRA_BITS
const std::string InstructionField::OSKEY_EXTRA_BITS = "extra_bits" static
ObjectState attribute key for the number of extra bits.
Definition at line 75 of file InstructionField.hh.
Referenced by BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToOM(), loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), saveState(), BEMSerializer::slotFieldToFile(), and BEMSerializer::slotFieldToOM().
OSKEY_POSITION
const std::string InstructionField::OSKEY_POSITION = "position" static
ObjectState attribute key for the relative position of the field.
Definition at line 77 of file InstructionField.hh.
Referenced by BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), BEMSerializer::immediateSlotToFile(), BEMSerializer::immediateSlotToOM(), loadState(), BEMSerializer::longImmDstRegFieldToOM(), BEMSerializer::longImmDstRegisterFieldToFile(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), BEMSerializer::moveSlotToFile(), BEMSerializer::moveSlotToOM(), reorderSubfields(), ImmediateControlField::saveState(), saveState(), BEMSerializer::slotFieldToFile(), and BEMSerializer::slotFieldToOM().
OSNAME_INSTRUCTION_FIELD
const std::string InstructionField::OSNAME_INSTRUCTION_FIELD = "instr_field" static
ObjectState name for instruction field.
Definition at line 73 of file InstructionField.hh.
Referenced by saveState().
parent_
InstructionField* InstructionField::parent_ private
The parent instruction field.
Definition at line 92 of file InstructionField.hh.
Referenced by parent(), and setParent().
relativePos_
int InstructionField::relativePos_ private
Indicates the relative position of the field.
Definition at line 88 of file InstructionField.hh.
Referenced by InstructionField(), InstructionField(), relativePosition(), and setRelativePosition().
The documentation for this class was generated from the following files:
InstructionField.hh
InstructionField.cc