OpenASIP: FUGuardEncoding Class Reference
FUGuardEncoding Class Reference
#include <FUGuardEncoding.hh>
Public Member Functions
FUGuardEncoding (const std::string &fu, const std::string &port, bool inverted, unsigned int encoding, GuardField &parent)
FUGuardEncoding (const ObjectState *state, GuardField &parent)
virtual ~FUGuardEncoding ()
std::string functionUnit () const
std::string port () const
virtual ObjectState * saveState () const
Public Member Functions inherited from GuardEncoding
virtual ~GuardEncoding ()
GuardField * parent () const
bool isGuardInverted () const
unsigned int encoding () const
Static Public Attributes
static const std::string OSNAME_FU_GUARD_ENCODING = "fu_guard_enc"
ObjectState name for FU guard encoding.
static const std::string OSKEY_FU_NAME = "fu_name"
ObjectState attribute key for the name of the function unit.
static const std::string OSKEY_PORT_NAME = "port_name"
ObjectState attribute key for the name of the port.
Static Public Attributes inherited from GuardEncoding
static const std::string OSNAME_GUARD_ENCODING = "guard_encoding"
ObjectState name for guard encoding.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for invert flag.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for encoding.
Private Attributes
std::string functionUnit_
Name of the function unit.
std::string port_
Name of the port.
Additional Inherited Members
Protected Member Functions inherited from GuardEncoding
GuardEncoding (bool inverted, unsigned int encoding)
GuardEncoding (const ObjectState *state)
void setParent (GuardField *parent)
Detailed Description
The FUGuardEncoding class maps a guard expression with FU output port term to a control code.
Instances of this class are always registered to a guard field.
Definition at line 47 of file FUGuardEncoding.hh.
Constructor & Destructor Documentation
FUGuardEncoding() [1/2]
FUGuardEncoding::FUGuardEncoding (const std::string & fu, const std::string & port, bool inverted, unsigned int encoding, GuardField & parent)
The constructor.
Creates a guard encoding and registers it into the given guard field. The guard expression is identified by the name of function unit and port, and the "invert" flag, all given as parameters.
Parameters
fu Name of the function unit.
port Name of the port.
inverted The "invert" flag.
encoding The control code of the guard expression.
parent The parent guard field.
Exceptions
ObjectAlreadyExists If the guard expression is already encoded in the parent field, or if the given control code is already assigned to another guard expression.
Definition at line 62 of file FUGuardEncoding.cc.
    : GuardEncoding(inverted, encoding), functionUnit_(fu), port_(port) {
    parent.addGuardEncoding(*this);
    setParent(&parent);
}
References GuardField::addGuardEncoding(), GuardEncoding::parent(), and GuardEncoding::setParent().
FUGuardEncoding() [2/2]
FUGuardEncoding::FUGuardEncoding (const ObjectState * state, GuardField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent guard field.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the guard expression if already encoded in the parent field, or if the given control code is already assigned to another guard expression.
Definition at line 84 of file FUGuardEncoding.cc.
    : GuardEncoding(state), functionUnit_(""), port_("") {
    const string procName = "FUGuardEncoding::FUGuardEncoding";
    if (state->name() != OSNAME_FU_GUARD_ENCODING) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
    functionUnit_ = state->stringAttribute(OSKEY_FU_NAME);
    port_ = state->stringAttribute(OSKEY_PORT_NAME);
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
    parent.addGuardEncoding(*this);
    setParent(&parent);
}
References GuardField::addGuardEncoding(), Exception::errorMessage(), functionUnit_, ObjectState::name(), OSKEY_FU_NAME, OSKEY_PORT_NAME, OSNAME_FU_GUARD_ENCODING, GuardEncoding::parent(), port_, GuardEncoding::setParent(), and ObjectState::stringAttribute().
~FUGuardEncoding()
FUGuardEncoding::~FUGuardEncoding () virtual
The destructor.
Definition at line 107 of file FUGuardEncoding.cc.
{
    GuardField* parent = this->parent();
    setParent(NULL);
    parent->removeGuardEncoding(*this);
}
References GuardEncoding::parent(), GuardField::removeGuardEncoding(), and GuardEncoding::setParent().
Member Function Documentation
functionUnit()
std::string FUGuardEncoding::functionUnit () const
Returns the name of the function unit that contains the port of this guard expression.
Returns
The name of the function unit.
Definition at line 121 of file FUGuardEncoding.cc.
{
    return functionUnit_;
}
References functionUnit_.
Referenced by GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), GuardField::fuGuardEncoding(), GuardField::hasFUGuardEncoding(), printGuardFieldEncodings(), and saveState().
port()
std::string FUGuardEncoding::port () const
Returns the name of the FU port of this guard expression.
Returns
The name of the FU port.
Definition at line 132 of file FUGuardEncoding.cc.
{
    return port_;
}
References port_.
Referenced by GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), GuardField::fuGuardEncoding(), GuardField::hasFUGuardEncoding(), printGuardFieldEncodings(), and saveState().
saveState()
ObjectState * FUGuardEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from GuardEncoding.
Definition at line 143 of file FUGuardEncoding.cc.
{
    ObjectState* state = GuardEncoding::saveState();
    state->setName(OSNAME_FU_GUARD_ENCODING);
    state->setAttribute(OSKEY_FU_NAME, functionUnit());
    state->setAttribute(OSKEY_PORT_NAME, port());
    return state;
}
References functionUnit(), OSKEY_FU_NAME, OSKEY_PORT_NAME, OSNAME_FU_GUARD_ENCODING, port(), GuardEncoding::saveState(), ObjectState::setAttribute(), and ObjectState::setName().
Referenced by GuardField::saveState().
Member Data Documentation
functionUnit_
std::string FUGuardEncoding::functionUnit_ private
Name of the function unit.
Definition at line 69 of file FUGuardEncoding.hh.
Referenced by FUGuardEncoding(), and functionUnit().
OSKEY_FU_NAME
const std::string FUGuardEncoding::OSKEY_FU_NAME = "fu_name" static
ObjectState attribute key for the name of the function unit.
Definition at line 63 of file FUGuardEncoding.hh.
Referenced by FUGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSKEY_PORT_NAME
const std::string FUGuardEncoding::OSKEY_PORT_NAME = "port_name" static
ObjectState attribute key for the name of the port.
Definition at line 65 of file FUGuardEncoding.hh.
Referenced by FUGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSNAME_FU_GUARD_ENCODING
const std::string FUGuardEncoding::OSNAME_FU_GUARD_ENCODING = "fu_guard_enc" static
ObjectState name for FU guard encoding.
Definition at line 61 of file FUGuardEncoding.hh.
Referenced by FUGuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), GuardField::loadState(), and saveState().
port_
std::string FUGuardEncoding::port_ private
Name of the port.
Definition at line 71 of file FUGuardEncoding.hh.
Referenced by FUGuardEncoding(), and port().
The documentation for this class was generated from the following files:
FUGuardEncoding.hh
FUGuardEncoding.cc