OpenASIP: TPEF::TPEFDebugSectionWriter Class Reference
TPEF::TPEFDebugSectionWriter Class Reference
#include <TPEFDebugSectionWriter.hh>
Protected Member Functions
TPEFDebugSectionWriter ()
virtual ~TPEFDebugSectionWriter ()
virtual Section::SectionType type () const
virtual void createKeys (const Section *sect) const
virtual void actualWriteData (BinaryStream &stream, const Section *section) const
virtual Word elementSize (const Section *section) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFDebugSectionWriter (const TPEFDebugSectionWriter &)
Copying not allowed.
TPEFDebugSectionWriter operator= (const TPEFDebugSectionWriter &)
Assignment not allowed.
Static Private Attributes
static const TPEFDebugSectionWriter instance_
A unique instance of this class.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes TPEF symbol table to stream.
Definition at line 46 of file TPEFDebugSectionWriter.hh.
Constructor & Destructor Documentation
TPEFDebugSectionWriter() [1/2]
TPEF::TPEFDebugSectionWriter::TPEFDebugSectionWriter () protected
Constructor.
Registers itself to SectionWriter.
Definition at line 62 of file TPEFDebugSectionWriter.cc.
                                               : TPEFSectionWriter() {
    registerSectionWriter(this);
}
References TPEF::SectionWriter::registerSectionWriter().
~TPEFDebugSectionWriter()
TPEF::TPEFDebugSectionWriter::~TPEFDebugSectionWriter () protected virtual
Destructor.
Definition at line 69 of file TPEFDebugSectionWriter.cc.
{
}
TPEFDebugSectionWriter() [2/2]
TPEF::TPEFDebugSectionWriter::TPEFDebugSectionWriter (const TPEFDebugSectionWriter &) private
Copying not allowed.
Member Function Documentation
actualWriteData()
void TPEF::TPEFDebugSectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected virtual
Writes the data of the section in to stream.
Parameters
stream The stream to be written to.
sect The section to be written.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 89 of file TPEFDebugSectionWriter.cc.
{
    FileOffset startOffset = stream.writePosition();
    // file offset to data of section
    SafePointer::addObjectReference(
        FileOffsetKey(startOffset), sect->element(0));
    for (Word i = 0; i < sect->elementCount(); i++) {
        DebugElement* elem = dynamic_cast<DebugElement*>(sect->element(i));
        assert(elem != NULL);
        // write type
        stream.writeHalfWord(static_cast<HalfWord>(elem->type()));
        // debug string
        assert(elem->debugString() != NULL);
        SectionOffsetReplacer sOffReplacer(elem->debugString());
        sOffReplacer.resolve();
        // write variable data
        stream.writeWord(elem->length());
        for (unsigned int j = 0; j < elem->length(); j++) {
            stream.writeByte(elem->byte(j));
        }
    }
    SectionSizeReplacer::setSize(sect, stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::DebugElement::byte(), TPEF::DebugElement::debugString(), TPEF::Section::element(), TPEF::Section::elementCount(), TPEF::DebugElement::length(), TPEF::ValueReplacer::resolve(), TPEF::SectionSizeReplacer::setSize(), TPEF::DebugElement::type(), TPEF::BinaryStream::writeByte(), TPEF::BinaryStream::writeHalfWord(), TPEF::BinaryStream::writePosition(), and TPEF::BinaryStream::writeWord().
createKeys()
void TPEF::TPEFDebugSectionWriter::createKeys (const Section * sect) const protected virtual
Creates needed keys for section if noBits flag is set.
Parameters
sect Section which for keys will be created.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 138 of file TPEFDebugSectionWriter.cc.
{
    SectionSizeReplacer::setSize(sect, 0x0);
}
References TPEF::SectionSizeReplacer::setSize().
elementSize()
Word TPEF::TPEFDebugSectionWriter::elementSize (const Section * section) const protected virtual
Returns the fixed size length of section elements.
Returns
The fixed size length of section elements.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 128 of file TPEFDebugSectionWriter.cc.
{
    return 0;
}
operator=()
TPEFDebugSectionWriter TPEF::TPEFDebugSectionWriter::operator= (const TPEFDebugSectionWriter &) private
Assignment not allowed.
type()
Section::SectionType TPEF::TPEFDebugSectionWriter::type () const protected virtual
Returns the section type this writer can write.
Returns
The section type writer can write.
Implements TPEF::TPEFSectionWriter.
Definition at line 78 of file TPEFDebugSectionWriter.cc.
{
    return Section::ST_DEBUG;
}
References TPEF::Section::ST_DEBUG.
Member Data Documentation
instance_
const TPEFDebugSectionWriter TPEF::TPEFDebugSectionWriter::instance_ static private
A unique instance of this class.
Definition at line 68 of file TPEFDebugSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFDebugSectionWriter.hh
TPEFDebugSectionWriter.cc