OpenASIP: DataDependenceEdge Class Reference
DataDependenceEdge Class Reference
#include <DataDependenceEdge.hh>
Public Types
enum DependenceType {
DEP_UNKNOWN = 0 , DEP_RAW = 1 , DEP_WAR = 2 , DEP_WAW = 3 ,
DEP_TRIGGER = 4
}
enum EdgeReason {
EDGE_REGISTER , EDGE_MEMORY , EDGE_FUSTATE , EDGE_OPERATION ,
EDGE_RA
}
Public Member Functions
DataDependenceEdge (EdgeReason edgereason, DependenceType deptype, TCEString data, bool guard=false, bool certainAlias=false, bool tailPseudo=false, bool headPseudo=false, int loop=0)
DataDependenceEdge (EdgeReason edgereason, DependenceType deptype, bool guard=false, bool certainAlias=false, bool tailPseudo=false, bool headPseudo=false, int loop=0)
DataDependenceEdge (const DataDependenceEdge &other)
DataDependenceEdge (const DataDependenceEdge &other, bool invertLoop)
virtual ~DataDependenceEdge ()
TCEString toString () const
TCEString toString (MoveNode &tail) const
ObjectState * saveState (const MoveNode &tail, const MoveNode &head)
DependenceType dependenceType () const
EdgeReason edgeReason () const
bool isFalseDep () const
bool guardUse () const
bool certainAlias () const
bool tailPseudo () const
bool headPseudo () const
bool isBackEdge () const
int loopDepth () const
bool isGPREdge () const
bool isRegisterOrRA () const
bool isWAW () const
bool isRAW () const
const TCEString data () const
bool operator== (const DataDependenceEdge &other) const
void setData (const TCEString &newData)
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual GraphEdge * clone () const
virtual ~GraphEdge ()
virtual int edgeID () const
virtual TCEString dotString () const
int weight () const
void setWeight (int w)
Static Public Member Functions
static void printStats (std::ostream &out)
Static Public Attributes
static int regAntidepCount_ = 0
Private Types
enum EdgePropertyFlags { EPF_GUARD = 1 << 0 , EPF_CERTAIN_ALIAS = 1 << 1 , EPF_TAIL_PSEUDO = 1 << 2 , EPF_HEAD_PSEUDO = 1 << 3 }
Private Member Functions
TCEString depTypeSt () const
TCEString edgeReasonSt () const
TCEString guardSt () const
TCEString pseudoSt () const
TCEString latencySt (MoveNode &node) const
Private Attributes
unsigned char dependenceType_
unsigned char edgeReason_
unsigned char edgeProperties_
unsigned char loopEdge_
char * data_
Detailed Description
Definition at line 43 of file DataDependenceEdge.hh.
Member Enumeration Documentation
DependenceType
enum DataDependenceEdge::DependenceType
Enumerator
DEP_UNKNOWN
DEP_RAW
DEP_WAR
DEP_WAW
DEP_TRIGGER
Definition at line 45 of file DataDependenceEdge.hh.
{
        DEP_UNKNOWN = 0,
        DEP_RAW     = 1,
        DEP_WAR     = 2,
        DEP_WAW     = 3,
        DEP_TRIGGER = 4};
EdgePropertyFlags
enum DataDependenceEdge::EdgePropertyFlags private
Enumerator
EPF_GUARD
EPF_CERTAIN_ALIAS
EPF_TAIL_PSEUDO
EPF_HEAD_PSEUDO
Definition at line 169 of file DataDependenceEdge.hh.
{
        EPF_GUARD = 1 << 0,
        EPF_CERTAIN_ALIAS = 1 << 1,
        EPF_TAIL_PSEUDO = 1 << 2,
        EPF_HEAD_PSEUDO = 1 << 3
    };
EdgeReason
enum DataDependenceEdge::EdgeReason
Enumerator
EDGE_REGISTER
EDGE_MEMORY
EDGE_FUSTATE
EDGE_OPERATION
EDGE_RA
Definition at line 52 of file DataDependenceEdge.hh.
                    {
        EDGE_REGISTER,
        EDGE_MEMORY,
        EDGE_FUSTATE,
        EDGE_OPERATION,
        EDGE_RA};
Constructor & Destructor Documentation
DataDependenceEdge() [1/4]
DataDependenceEdge::DataDependenceEdge (EdgeReason edgereason, DependenceType deptype, TCEString data, bool guard = false, bool certainAlias = false, bool tailPs = false, bool headPs = false, int loopEdge = 0)
Constructor.
Parameters
edgereason which kind of data caused this dependence, is it register, memory, operation, ra etc.
deptype whether this is real dependence(raw), antidependence(war) or output dependence(waw)
data some data about the dependence, for example reg name.
guard if this dependence is a guard use.
certainAlias if this memory dep is a known to always alias.
tailPS whether the tail of the dep is a pseudo data usage
headPS whether the head of the dep is a pseudo data usage
loopEdge loop iteration depth if the dependence goes over a loop
Definition at line 65 of file DataDependenceEdge.cc.
                               :
    dependenceType_(deptype), edgeReason_(edgereason),
    loopEdge_(loopEdge) {
    edgeProperties_ = 0;
    if (guard)
        edgeProperties_ |= EPF_GUARD;
    if (certainAlias)
        edgeProperties_ |= EPF_CERTAIN_ALIAS;
    if (tailPs)
        edgeProperties_ |= EPF_TAIL_PSEUDO;
    if (headPs)
        edgeProperties_ |= EPF_HEAD_PSEUDO;
    assert(loopEdge < UCHAR_MAX);
    loopEdge = (unsigned char)loopEdge_;
    data_ = NULL;
    setData(data);
    if (edgeReason_ == EDGE_REGISTER) {
        assert(data_ != NULL && "Register name required for reg deps");
    }
}
References assert, certainAlias(), data(), data_, EDGE_REGISTER, edgeProperties_, edgeReason_, EPF_CERTAIN_ALIAS, EPF_GUARD, EPF_HEAD_PSEUDO, EPF_TAIL_PSEUDO, loopEdge_, and setData().
DataDependenceEdge() [2/4]
DataDependenceEdge::DataDependenceEdge (EdgeReason edgereason, DependenceType deptype, bool guard = false, bool certainAlias = false, bool tailPs = false, bool headPs = false, int loopEdge = 0)
Constructor.
Parameters
edgereason which kind of data caused this dependence, is it register, memory, operation, ra etc.
deptype whether this is real dependence(raw), antidependence(war) or output dependence(waw)
guard if this dependence is a guard use.
certainAlias if this memory dep is a known to always alias.
tailPS whether the tail of the dep is a pseudo data usage
headPS whether the head of the dep is a pseudo data usage
loopEdge loop iteration depth if the dependence goes over a loop
Definition at line 110 of file DataDependenceEdge.cc.
                  :
    dependenceType_(deptype), edgeReason_(edgereason),
    loopEdge_(loopEdge) {
    edgeProperties_ = 0;
    if (guard)
        edgeProperties_ |= EPF_GUARD;
    if (certainAlias)
        edgeProperties_ |= EPF_CERTAIN_ALIAS;
    if (tailPs)
        edgeProperties_ |= EPF_TAIL_PSEUDO;
    if (headPs)
        edgeProperties_ |= EPF_HEAD_PSEUDO;
    assert(loopEdge < UCHAR_MAX);
    loopEdge = (unsigned char)loopEdge_;
    data_ = NULL;
    if (edgeReason_ == EDGE_REGISTER) {
        assert(0 && "Register name required for reg deps");
    }
}
References assert, certainAlias(), data_, EDGE_REGISTER, edgeProperties_, edgeReason_, EPF_CERTAIN_ALIAS, EPF_GUARD, EPF_HEAD_PSEUDO, EPF_TAIL_PSEUDO, and loopEdge_.
DataDependenceEdge() [3/4]
DataDependenceEdge::DataDependenceEdge (const DataDependenceEdge & other)
Copy constructor.
Because of data_ that needs to be deep copied.
Definition at line 146 of file DataDependenceEdge.cc.
                                                                      :
    GraphEdge() {
    this->dependenceType_ = other.dependenceType_;
    this->edgeReason_ = other.edgeReason_;
    this->edgeProperties_ = other.edgeProperties_;
    this->loopEdge_ = other.loopEdge_;
    if (other.data_ != NULL) {
        data_ = new char[strlen(other.data_)+1];
        strcpy(data_, other.data_);
    } else {
        data_ = NULL;
    }
}
References data_, dependenceType_, edgeProperties_, edgeReason_, and loopEdge_.
DataDependenceEdge() [4/4]
DataDependenceEdge::DataDependenceEdge (const DataDependenceEdge & other, bool invertLoop)
Copy constructor which may modify the loop property
Parameters
other edge to copy @invertLoop whether to invent oop propert 0->1, 1->0
Definition at line 166 of file DataDependenceEdge.cc.
                                                      :
    GraphEdge() {
    this->dependenceType_ = other.dependenceType_;
    this->edgeReason_ = other.edgeReason_;
    this->edgeProperties_ = other.edgeProperties_;
    if (!invertLoop || other.loopEdge_ > 1) {
        this->loopEdge_ = other.loopEdge_;
    } else {
        this->loopEdge_ = !other.loopEdge_;
    }
    if (other.data_ != NULL) {
        data_ = new char[strlen(other.data_)+1];
        strcpy(data_, other.data_);
    } else {
        data_ = NULL;
    }
}
References data_, dependenceType_, edgeProperties_, edgeReason_, and loopEdge_.
~DataDependenceEdge()
virtual DataDependenceEdge::~DataDependenceEdge () inline virtual
Definition at line 75 of file DataDependenceEdge.hh.
{
        delete[] data_;
        data_ = NULL;
    }
References data_.
Member Function Documentation
certainAlias()
bool DataDependenceEdge::certainAlias () const inline
Definition at line 103 of file DataDependenceEdge.hh.
{
        return edgeProperties_ & EPF_CERTAIN_ALIAS;
    }
References edgeProperties_, and EPF_CERTAIN_ALIAS.
Referenced by DataDependenceEdge(), DataDependenceEdge(), DataDependenceGraph::dotString(), edgeReasonSt(), and operator==().
data()
const TCEString DataDependenceEdge::data () const inline
Definition at line 142 of file DataDependenceEdge.hh.
{
        if (data_ == NULL) {
            return TCEString("");
        } else {
            return TCEString(data_);
        }
    }
References data_.
Referenced by DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceEdge(), DataDependenceGraph::destRenamed(), DataDependenceGraph::edgeWeight(), DataDependenceGraph::guardRenamed(), operator==(), LiveRangeData::registersAlive(), DataDependenceGraph::renamedSimpleLiveRange(), DataDependenceGraph::sourceRenamed(), toString(), toString(), and BFMergeAndKeepUser::updateEdges().
dependenceType()
DependenceType DataDependenceEdge::dependenceType () const inline
Definition at line 88 of file DataDependenceEdge.hh.
{
        return static_cast<DependenceType>(dependenceType_);
    }
References dependenceType_.
Referenced by ResourceConstraintAnalyzer::analyzeRegisterAntideps(), CycleLookBackSoftwareBypasser::bypassNode(), BFRemoveLoopChecksAndJump::checkAliveMove(), BFRemoveLoopChecksAndJump::checkAlivePO(), PreOptimizer::checkGuardReversalAllowed(), CopyingDelaySlotFiller::checkIncomingDeps(), DataDependenceGraph::combineNodes(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::destRenamed(), DataDependenceGraph::edgeWeight(), BF2Scheduler::findBypassEdge(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::findLiveRange(), DataDependenceGraph::findLoopIndexInit(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), DataDependenceGraph::guardRawPredecessors(), DataDependenceGraph::guardRenamed(), PreOptimizer::inverseGuardsOfHeads(), DataDependenceGraph::isLoopInvariant(), DataDependenceGraph::mergeAndKeepSource(), ProgramDependenceGraph::moveDDGedges(), DataDependenceGraph::onlyIncomingGuard(), BFRemoveLoopChecksAndJump::operator()(), DataDependenceGraph::queueRawPredecessors(), LiveRangeData::registersAlive(), DataDependenceGraph::regRawPredecessors(), DataDependenceGraph::regRawSuccessors(), DataDependenceGraph::regWarSuccessors(), DataDependenceGraph::regWawSuccessors(), BFRemoveLoopChecksAndJump::removeMoveFromQueue(), BFRemoveLoopChecksAndJump::removePoFromQueue(), DataDependenceGraph::renamedSimpleLiveRange(), DataDependenceGraph::sanityCheck(), DataDependenceGraph::sourceRenamed(), PreOptimizer::tryToOptimizeAddressReg(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), and BFMergeAndKeepUser::updateEdges().
depTypeSt()
TCEString DataDependenceEdge::depTypeSt () const private
Helper method for creating the toString string.
Definition at line 258 of file DataDependenceEdge.cc.
{
    switch (dependenceType_) {
        case DEP_RAW:
            return "_raw";
        case DEP_WAR:
            return "_war";
        case DEP_WAW:
            return "_waw";
        case DEP_UNKNOWN:
        default:
            return "";
    }
}
References DEP_RAW, DEP_UNKNOWN, DEP_WAR, DEP_WAW, and dependenceType_.
Referenced by toString(), and toString().
edgeReason()
EdgeReason DataDependenceEdge::edgeReason () const inline
Definition at line 91 of file DataDependenceEdge.hh.
{
        return static_cast<EdgeReason>(edgeReason_);
    }
References edgeReason_.
Referenced by ResourceConstraintAnalyzer::analyzeRegisterAntideps(), CycleLookBackSoftwareBypasser::bypassNode(), DataDependenceGraph::combineNodes(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::destRenamed(), DataDependenceGraph::dotString(), DataDependenceGraph::edgeWeight(), BF2Scheduler::findBypassEdge(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::findLiveRange(), DataDependenceGraph::findLoopIndexInit(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), DataDependenceGraph::guardRenamed(), isGPREdge(), ExecutionPipelineResource::isLoopBypass(), DataDependenceGraph::isLoopInvariant(), isRegisterOrRA(), ProgramDependenceGraph::moveDDGedges(), DataDependenceGraph::moveFUDependenciesToTrigger(), DataDependenceGraph::queueRawPredecessors(), LiveRangeData::registersAlive(), DataDependenceGraph::regRawPredecessors(), DataDependenceGraph::regRawSuccessors(), DataDependenceGraph::regWarSuccessors(), DataDependenceGraph::regWawSuccessors(), DataDependenceGraph::renamedSimpleLiveRange(), DataDependenceGraph::sanityCheck(), DataDependenceGraph::sourceRenamed(), PreOptimizer::tryToOptimizeAddressReg(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), and BFMergeAndKeepUser::updateEdges().
edgeReasonSt()
TCEString DataDependenceEdge::edgeReasonSt () const private
Helper method for creating the toString string.
Definition at line 235 of file DataDependenceEdge.cc.
{
    switch (edgeReason_) {
        case EDGE_REGISTER:
            return "R";
        case EDGE_MEMORY:
            if (certainAlias())
                return "M_T";
            else
                return "M";
        case EDGE_FUSTATE:
            return "F";
        case EDGE_OPERATION:
            return "O";
        case EDGE_RA:
            return "RA";
    }
    return "BUG";
}
References certainAlias(), EDGE_FUSTATE, EDGE_MEMORY, EDGE_OPERATION, EDGE_RA, EDGE_REGISTER, and edgeReason_.
Referenced by toString(), and toString().
guardSt()
TCEString DataDependenceEdge::guardSt () const private
Helper method for creating the toString string.
Definition at line 276 of file DataDependenceEdge.cc.
{
    return guardUse() ? "_G" : "";
}
References guardUse().
Referenced by toString(), and toString().
guardUse()
bool DataDependenceEdge::guardUse () const inline
Definition at line 100 of file DataDependenceEdge.hh.
{
        return edgeProperties_ & EPF_GUARD;
    }
References edgeProperties_, and EPF_GUARD.
Referenced by CycleLookBackSoftwareBypasser::bypassNode(), PreOptimizer::checkGuardReversalAllowed(), CopyingDelaySlotFiller::checkIncomingDeps(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::destRenamed(), DataDependenceGraph::edgeWeight(), BF2Scheduler::findBypassEdge(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::findLiveRange(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), DataDependenceGraph::guardRawPredecessors(), DataDependenceGraph::guardRenamed(), guardSt(), PreOptimizer::inverseGuardsOfHeads(), DataDependenceGraph::isLoopInvariant(), DataDependenceGraph::mergeAndKeepSource(), DataDependenceGraph::onlyIncomingGuard(), operator==(), DataDependenceGraph::queueRawPredecessors(), DataDependenceGraph::sourceRenamed(), PreOptimizer::tryToOptimizeAddressReg(), and BFMergeAndKeepUser::updateEdges().
headPseudo()
bool DataDependenceEdge::headPseudo () const inline
returns whether the head of the dependence does not directly write/read the data but instead is a control flow move which may cause it to be read/written
Definition at line 115 of file DataDependenceEdge.hh.
{
        return edgeProperties_ & EPF_HEAD_PSEUDO;
    }
References edgeProperties_, and EPF_HEAD_PSEUDO.
Referenced by CycleLookBackSoftwareBypasser::bypassNode(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::destRenamed(), DataDependenceGraph::edgeWeight(), BF2Scheduler::findBypassEdge(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::findLiveRange(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), DataDependenceGraph::guardRenamed(), operator==(), pseudoSt(), DataDependenceGraph::queueRawPredecessors(), LiveRangeData::registersAlive(), DataDependenceGraph::renamedSimpleLiveRange(), and DataDependenceGraph::sourceRenamed().
isBackEdge()
bool DataDependenceEdge::isBackEdge () const inline virtual
Reimplemented from GraphEdge.
Definition at line 118 of file DataDependenceEdge.hh.
{
        return loopEdge_ != 0;
    }
References loopEdge_.
Referenced by CycleLookBackSoftwareBypasser::bypassNode(), DataDependenceGraph::dotString(), DataDependenceGraph::dropBackEdges(), BF2Scheduler::findBypassEdge(), DataDependenceGraph::findBypassSource(), DataDependenceGraph::findLiveRange(), DataDependenceGraph::findLoopIndexInit(), ExecutionPipelineResource::isLoopBypass(), BFEarlyBypasser::operator()(), BFMergeAndKeepUser::operator()(), operator==(), DataDependenceGraph::queueRawPredecessors(), DataDependenceGraph::regRawPredecessors(), BFPostpassBypasser::tryBypassNode(), and PreOptimizer::tryToOptimizeAddressReg().
isFalseDep()
bool DataDependenceEdge::isFalseDep () const inline
Definition at line 95 of file DataDependenceEdge.hh.
{
        return edgeReason_ != EDGE_OPERATION &&
            (dependenceType_ == DEP_WAR || dependenceType_ == DEP_WAW);
    }
References DEP_WAR, DEP_WAW, dependenceType_, EDGE_OPERATION, and edgeReason_.
Referenced by ResourceConstraintAnalyzer::analyzeRegisterAntideps(), DataDependenceGraph::dotString(), and BFMergeAndKeepUser::operator()().
isGPREdge()
bool DataDependenceEdge::isGPREdge () const inline
Definition at line 125 of file DataDependenceEdge.hh.
{
        return edgeReason() == EDGE_REGISTER;
    }
References EDGE_REGISTER, and edgeReason().
isRAW()
bool DataDependenceEdge::isRAW () const inline
Definition at line 138 of file DataDependenceEdge.hh.
                       {
        return dependenceType_ == DEP_RAW;
    }
References DEP_RAW, and dependenceType_.
isRegisterOrRA()
bool DataDependenceEdge::isRegisterOrRA () const inline
Definition at line 129 of file DataDependenceEdge.hh.
{
        return edgeReason() == EDGE_REGISTER ||
            edgeReason() == EDGE_RA;
    }
References EDGE_RA, EDGE_REGISTER, and edgeReason().
isWAW()
bool DataDependenceEdge::isWAW () const inline
Definition at line 134 of file DataDependenceEdge.hh.
                       {
        return dependenceType_ == DEP_WAW;
    }
References DEP_WAW, and dependenceType_.
latencySt()
TCEString DataDependenceEdge::latencySt (MoveNode & node) const private
Helper method for creating the toString string. Finds out the latency of operation dependences.
Definition at line 294 of file DataDependenceEdge.cc.
{
    if (edgeReason_ == EDGE_OPERATION && node.isAssigned()) {
        if (node.move().isTriggering()) {
            TTAProgram::TerminalFUPort &tfu
                = dynamic_cast<TTAProgram::TerminalFUPort&>
                (node.move().destination());
            std::stringstream ss;
            std::string lat;
            ss << tfu.hwOperation()->latency();
            ss >> lat;
            return ":" + lat;
        } else {
            return ":0";
        }
    } else {
        return "";
    }
}
References TTAProgram::Move::destination(), EDGE_OPERATION, edgeReason_, TTAProgram::TerminalFUPort::hwOperation(), MoveNode::isAssigned(), TTAProgram::Move::isTriggering(), TTAMachine::HWOperation::latency(), and MoveNode::move().
Referenced by toString().
loopDepth()
int DataDependenceEdge::loopDepth () const inline
Definition at line 121 of file DataDependenceEdge.hh.
{
        return loopEdge_;
    }
References loopEdge_.
Referenced by ResourceConstraintAnalyzer::analyzeRegisterAntideps(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), and DataDependenceGraph::renamedSimpleLiveRange().
operator==()
bool DataDependenceEdge::operator== (const DataDependenceEdge & other) const
Comparator.
Checks whether the two edges are identical.
Definition at line 319 of file DataDependenceEdge.cc.
{
    return dependenceType_ == other.dependenceType_ &&
        edgeReason_ == other.edgeReason_ &&
        data() == other.data() &&
        guardUse() == other.guardUse() &&
        certainAlias() == other.certainAlias() &&
        tailPseudo() == other.tailPseudo() &&
        headPseudo() == other.headPseudo() &&
        isBackEdge() == other.isBackEdge();
}
References certainAlias(), data(), dependenceType_, edgeReason_, guardUse(), headPseudo(), isBackEdge(), and tailPseudo().
printStats()
void DataDependenceEdge::printStats (std::ostream & out) static
Prints statistics about the created edges to the given output stream.
Definition at line 191 of file DataDependenceEdge.cc.
{
    out << "register anti-dependencies: " << regAntidepCount_ << std::endl;
}
References regAntidepCount_.
pseudoSt()
TCEString DataDependenceEdge::pseudoSt () const private
Helper method for creating the toString string.
Definition at line 284 of file DataDependenceEdge.cc.
{
    return TCEString(tailPseudo() ? "_TP" : "") + (headPseudo() ? "_HP" : "");
}
References headPseudo(), and tailPseudo().
Referenced by toString(), and toString().
saveState()
ObjectState * DataDependenceEdge::saveState (const MoveNode & tail, const MoveNode & head)
State dumping for XML generation.
Parameters
tail source node of the edge
head sink node of the edge
Definition at line 345 of file DataDependenceEdge.cc.
{
    ObjectState* edgeOS = new ObjectState("edge");
    ObjectState* tailOS = new ObjectState("nref", edgeOS);
    ObjectState* headOS = new ObjectState("nref", edgeOS);
    ObjectState* typeOS = new ObjectState("type", edgeOS);
    ObjectState* reasonOS = new ObjectState("reason", edgeOS);
    tailOS->setValue(tail.nodeID());
    headOS->setValue(head.nodeID());
    switch (dependenceType_) {
    case DEP_UNKNOWN:
        typeOS->setName("unknown");
        break;
    case DEP_RAW:
        typeOS->setName("raw");
        break;
    case DEP_WAR:
        typeOS->setName("war");
        break;
    case DEP_WAW:
        typeOS->setName("waw");
        break;
    case DEP_TRIGGER:
        typeOS->setName("trg");
        break;
    }
    switch (edgeReason_) {
    case EDGE_REGISTER:
        reasonOS->setName("reg");
        break;
    case EDGE_MEMORY:
        reasonOS->setName("mem");
        break;
    case EDGE_FUSTATE:
        reasonOS->setName("fu");
        break;
    case EDGE_OPERATION:
        reasonOS->setName("op");
        break;
    case EDGE_RA:
        reasonOS->setName("ra");
        break;
    }
    // Add operation latency information to trigger moves
    if (tail.isMove() && tail.move().isTriggering()) {
        TTAProgram::TerminalFUPort &tfu
            = dynamic_cast<TTAProgram::TerminalFUPort&>
            (tail.move().destination());
        ObjectState* latencyOS = new ObjectState("lat", edgeOS);
        latencyOS->setValue(Conversion::toString(tfu.hwOperation()->latency()));
    }
    if (loopEdge_ != 0) {
        ObjectState* loopEdgeOS = new ObjectState("dist", edgeOS);
        loopEdgeOS->setValue(Conversion::toString(static_cast<int>(loopEdge_)));
    }
    return edgeOS;
}
References DEP_RAW, DEP_TRIGGER, DEP_UNKNOWN, DEP_WAR, DEP_WAW, dependenceType_, TTAProgram::Move::destination(), EDGE_FUSTATE, EDGE_MEMORY, EDGE_OPERATION, EDGE_RA, EDGE_REGISTER, edgeReason_, TTAProgram::TerminalFUPort::hwOperation(), MoveNode::isMove(), TTAProgram::Move::isTriggering(), TTAMachine::HWOperation::latency(), loopEdge_, MoveNode::move(), GraphNode::nodeID(), ObjectState::setName(), ObjectState::setValue(), and Conversion::toString().
Referenced by DataDependenceGraph::writeToXMLFile().
setData()
void DataDependenceEdge::setData (const TCEString & newData)
Definition at line 331 of file DataDependenceEdge.cc.
{
    delete[] data_;
    data_ = new char[newData.length() + 1];
    strncpy(data_, newData.c_str(), newData.length() + 1);
}
References data_.
Referenced by DataDependenceEdge(), DataDependenceGraph::destRenamed(), DataDependenceGraph::guardRenamed(), and DataDependenceGraph::sourceRenamed().
tailPseudo()
bool DataDependenceEdge::tailPseudo () const inline
returns whether the tail of the dependence does not directly write/read the data but instead is a control flow move which may cause it to be read/written
Definition at line 109 of file DataDependenceEdge.hh.
{
        return edgeProperties_ & EPF_TAIL_PSEUDO;
    }
References edgeProperties_, and EPF_TAIL_PSEUDO.
Referenced by DataDependenceGraph::copyDepsOver(), DataDependenceGraph::copyDepsOver(), DataDependenceGraph::destRenamed(), DataDependenceGraph::findLimitingAntidependenceDestination(), DataDependenceGraph::findLimitingAntidependenceSource(), DataDependenceGraph::findLiveRange(), RegisterCopyAdder::fixDDGEdgesInTempReg(), RegisterCopyAdder::fixDDGEdgesInTempRegChain(), RegisterCopyAdder::fixDDGEdgesInTempRegChainImmediate(), DataDependenceGraph::guardRenamed(), operator==(), pseudoSt(), DataDependenceGraph::queueRawPredecessors(), LiveRangeData::registersAlive(), DataDependenceGraph::renamedSimpleLiveRange(), DataDependenceGraph::sourceRenamed(), BasicBlockScheduler::tryToOptimizeWaw(), BUBasicBlockScheduler::tryToOptimizeWaw(), and BFMergeAndKeepUser::updateEdges().
toString() [1/2]
TCEString DataDependenceEdge::toString () const virtual
Returns a textual representation of the edge.
This is used in the generated dot files.
Reimplemented from GraphEdge.
Definition at line 201 of file DataDependenceEdge.cc.
{
    if (loopEdge_ != 0) {
        return TCEString("LOOP:") + Conversion::toString(int(loopEdge_)) + "_" +
            edgeReasonSt() + guardSt() + depTypeSt() + pseudoSt() +
            ':' + data();
    }
    return edgeReasonSt() + guardSt() + depTypeSt() + pseudoSt() + ':' + data();
}
References data(), depTypeSt(), edgeReasonSt(), guardSt(), loopEdge_, pseudoSt(), and Conversion::toString().
Referenced by ResourceConstraintAnalyzer::analyzeRegisterAntideps(), DataDependenceGraph::dotString(), BFRemoveEdge::operator()(), ProgramDependenceEdge::toString(), and BFRemoveEdge::undoOnlyMe().
toString() [2/2]
TCEString DataDependenceEdge::toString (MoveNode & tail) const
Returns a textual representation of the edge.
Parameters
tail the source node of the dependence. Needed for looking up operation latencies in scheduled code.
Todo:
This should be refactored.
This is used in the generated dot files.
Definition at line 221 of file DataDependenceEdge.cc.
{
    if (loopEdge_ !=0) {
        return TCEString("LOOP:") + Conversion::toString(int(loopEdge_)) +
            "_" + edgeReasonSt() + guardSt() + depTypeSt() + pseudoSt() +
            ':' + data() + latencySt(tail);
    }
    return edgeReasonSt() + guardSt() + depTypeSt() + pseudoSt() +
        ':' + data() + latencySt(tail);
}
References data(), depTypeSt(), edgeReasonSt(), guardSt(), latencySt(), loopEdge_, pseudoSt(), and Conversion::toString().
Member Data Documentation
data_
char* DataDependenceEdge::data_ private
Definition at line 181 of file DataDependenceEdge.hh.
Referenced by data(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), setData(), and ~DataDependenceEdge().
dependenceType_
unsigned char DataDependenceEdge::dependenceType_ private
Definition at line 176 of file DataDependenceEdge.hh.
Referenced by DataDependenceEdge(), DataDependenceEdge(), dependenceType(), depTypeSt(), isFalseDep(), isRAW(), isWAW(), operator==(), and saveState().
edgeProperties_
unsigned char DataDependenceEdge::edgeProperties_ private
Definition at line 178 of file DataDependenceEdge.hh.
Referenced by certainAlias(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), guardUse(), headPseudo(), and tailPseudo().
edgeReason_
unsigned char DataDependenceEdge::edgeReason_ private
Definition at line 177 of file DataDependenceEdge.hh.
Referenced by DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), edgeReason(), edgeReasonSt(), isFalseDep(), latencySt(), operator==(), and saveState().
loopEdge_
unsigned char DataDependenceEdge::loopEdge_ private
Definition at line 179 of file DataDependenceEdge.hh.
Referenced by DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), DataDependenceEdge(), isBackEdge(), loopDepth(), saveState(), toString(), and toString().
regAntidepCount_
int DataDependenceEdge::regAntidepCount_ = 0 static
Definition at line 154 of file DataDependenceEdge.hh.
Referenced by printStats().
The documentation for this class was generated from the following files:
DataDependenceEdge.hh
DataDependenceEdge.cc