OpenASIP: AlteraMemGenerator Class Reference
AlteraMemGenerator Class Reference
#include <AlteraMemGenerator.hh>
Public Member Functions
AlteraMemGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator *integrator, std::ostream &warningStream, std::ostream &errorStream)
virtual ~AlteraMemGenerator ()
virtual void addMemory (const ProGe::NetlistBlock &ttaCore, ProGe::NetlistBlock &integratorBlock, int memIndex, int coreId)
Public Member Functions inherited from MemoryGenerator
MemoryGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator *integrator, std::ostream &warningStream, std::ostream &errorStream)
virtual ~MemoryGenerator ()
virtual bool isCompatible (const ProGe::NetlistBlock &ttaCore, int coreId, std::vector< TCEString > &reasons) const
virtual bool generatesComponentHdlFile () const =0
virtual std::vector< TCEString > generateComponentFile (TCEString outputPath)=0
int memoryTotalWidth () const
int memoryMauSize () const
int memoryWidthInMaus () const
int memoryAddrWidth () const
TCEString initializationFile () const
void addLsu (TTAMachine::FunctionUnit &lsuArch, std::vector< std::string > lsuPorts)
Protected Member Functions
std::vector< TCEString > instantiateAlteraTemplate (const TCEString &templateFile, const TCEString &outputPath) const
virtual void addGenerics (ProGe::NetlistBlock &topBlock, const TCEString &addrWidth, const TCEString &dataWidth, int memIndex)
Protected Member Functions inherited from MemoryGenerator
virtual bool checkFuPort (const std::string fuPort, std::vector< TCEString > &reasons) const
virtual void connectPorts (ProGe::NetlistBlock &netlistBlock, const ProGe::NetlistPort &memPort, const ProGe::NetlistPort &corePort, bool inverted, int coreId)
virtual MemoryGenerator::BlockPair createMemoryNetlistBlock (ProGe::NetlistBlock &integratorBlock, int memIndex, int coreId)
const PlatformIntegrator * platformIntegrator () const
std::ostream & warningStream ()
std::ostream & errorStream ()
int portCount () const
const HDLPort * port (int index) const
const HDLPort * portByKeyName (TCEString name) const
TCEString portKeyName (const HDLPort *port) const
void addPort (const TCEString &name, HDLPort *port)
int parameterCount () const
const ProGe::Parameter & parameter (int index) const
void addParameter (const ProGe::Parameter &add)
TCEString ttaCoreName () const
virtual TCEString moduleName () const =0
virtual TCEString instanceName (int coreId, int memIndex) const =0
TCEString memoryIndexString (int coreId, int memIndex) const
TCEString templatePath () const
void instantiateTemplate (const TCEString &inFile, const TCEString &outFile, const TCEString &entity) const
bool hasLSUArchitecture () const
const TTAMachine::FunctionUnit & lsuArchitecture () const
TCEString corePortName (const TCEString &portBaseName, int coreId) const
Static Protected Attributes
static const TCEString INIT_FILE_G = "init_file_g"
static const TCEString DEV_FAMILY_G = "dev_family_g"
static const TCEString ADDRW_G = "addrw_g"
static const TCEString DATAW_G = "dataw_g"
Additional Inherited Members
Protected Types inherited from MemoryGenerator
typedef std::multimap< TCEString, HDLPort * > PortMap
typedef std::pair< ProGe::NetlistBlock *, ProGe::VirtualNetlistBlock * > BlockPair
Detailed Description
Definition at line 43 of file AlteraMemGenerator.hh.
Constructor & Destructor Documentation
AlteraMemGenerator()
AlteraMemGenerator::AlteraMemGenerator (int memMauWidth, int widthInMaus, int addrWidth, TCEString initFile, const PlatformIntegrator * integrator, std::ostream & warningStream, std::ostream & errorStream)
Definition at line 45 of file AlteraMemGenerator.cc.
                            :
    MemoryGenerator(memMauWidth, widthInMaus, addrWidth, initFile,
                    integrator, warningStream, errorStream) {
}
~AlteraMemGenerator()
AlteraMemGenerator::~AlteraMemGenerator () virtual
Definition at line 57 of file AlteraMemGenerator.cc.
{
}
Member Function Documentation
addGenerics()
void AlteraMemGenerator::addGenerics (ProGe::NetlistBlock & topBlock, const TCEString & addrWidth, const TCEString & dataWidth, int memIndex) protected virtual
Definition at line 96 of file AlteraMemGenerator.cc.
                  {
    if (!topBlock.hasParameter(DEV_FAMILY_G)) {
        ProGe::Parameter devFamilyTop =
            {DEV_FAMILY_G, "string", platformIntegrator()->deviceFamily()};
        topBlock.setParameter(devFamilyTop);
    }
    ProGe::Parameter devFamilyComp =
        {DEV_FAMILY_G, "string", DEV_FAMILY_G};
    addParameter(devFamilyComp);
    TCEString initFileGenericTop;
    // coreId is 0 because homogenous multicores share the same memory image
    initFileGenericTop
        << instanceName(0, memIndex) << "_" << INIT_FILE_G;
    ProGe::Parameter initFileParamTop(
        initFileGenericTop, "string", initializationFile());
    topBlock.setParameter(initFileParamTop);
    ProGe::Parameter initFileParamComp(
        INIT_FILE_G, "string", initFileParamTop.name());
    addParameter(initFileParamComp);
    ProGe::Parameter addrw(ADDRW_G,"integer", addrWidth);
    ProGe::Parameter memw(DATAW_G, "integer", dataWidth);
    addParameter(addrw);
    addParameter(memw);
}
References MemoryGenerator::addParameter(), ADDRW_G, DATAW_G, DEV_FAMILY_G, PlatformIntegrator::deviceFamily(), ProGe::BaseNetlistBlock::hasParameter(), INIT_FILE_G, MemoryGenerator::initializationFile(), MemoryGenerator::instanceName(), ProGe::Parameter::name(), MemoryGenerator::platformIntegrator(), and ProGe::NetlistBlock::setParameter().
Referenced by addMemory(), and AlteraOnchipRomGenerator::addMemory().
addMemory()
void AlteraMemGenerator::addMemory (const ProGe::NetlistBlock & ttaCore, ProGe::NetlistBlock & integratorBlock, int memIndex, int coreId) virtual
Reimplemented from MemoryGenerator.
Reimplemented in AlteraOnchipRomGenerator.
Definition at line 81 of file AlteraMemGenerator.cc.
                {
    TCEString addrwGeneric = Conversion::toString(memoryAddrWidth());
    TCEString datawGeneric = Conversion::toString(memoryTotalWidth());
    addGenerics(integratorBlock, addrwGeneric, datawGeneric, memIndex);
    MemoryGenerator::addMemory(ttaCore, integratorBlock, memIndex, coreId);
}
References addGenerics(), MemoryGenerator::addMemory(), MemoryGenerator::memoryAddrWidth(), MemoryGenerator::memoryTotalWidth(), and Conversion::toString().
instantiateAlteraTemplate()
std::vector< TCEString > AlteraMemGenerator::instantiateAlteraTemplate (const TCEString & templateFile, const TCEString & outputPath) const protected
Definition at line 62 of file AlteraMemGenerator.cc.
{
    TCEString inputFile =
        templatePath() << FileSystem::DIRECTORY_SEPARATOR
                       << templateFile;
    TCEString outputFile;
    outputFile << outputPath << FileSystem::DIRECTORY_SEPARATOR
               << moduleName() << ".vhd";
    instantiateTemplate(inputFile, outputFile, ttaCoreName());
    std::vector<TCEString> files;
    files.push_back(outputFile);
    return files;
}
References FileSystem::DIRECTORY_SEPARATOR, MemoryGenerator::instantiateTemplate(), MemoryGenerator::moduleName(), MemoryGenerator::templatePath(), and MemoryGenerator::ttaCoreName().
Referenced by AlteraHibiDpRamGenerator::generateComponentFile(), AlteraOnchipRamGenerator::generateComponentFile(), and AlteraOnchipRomGenerator::generateComponentFile().
Member Data Documentation
ADDRW_G
const TCEString AlteraMemGenerator::ADDRW_G = "addrw_g" static protected
Definition at line 77 of file AlteraMemGenerator.hh.
Referenced by addGenerics(), AlteraHibiDpRamGenerator::AlteraHibiDpRamGenerator(), and AlteraOnchipRamGenerator::AlteraOnchipRamGenerator().
DATAW_G
const TCEString AlteraMemGenerator::DATAW_G = "dataw_g" static protected
Definition at line 78 of file AlteraMemGenerator.hh.
Referenced by addGenerics(), AlteraHibiDpRamGenerator::AlteraHibiDpRamGenerator(), and AlteraOnchipRamGenerator::AlteraOnchipRamGenerator().
DEV_FAMILY_G
const TCEString AlteraMemGenerator::DEV_FAMILY_G = "dev_family_g" static protected
Definition at line 76 of file AlteraMemGenerator.hh.
Referenced by addGenerics().
INIT_FILE_G
const TCEString AlteraMemGenerator::INIT_FILE_G = "init_file_g" static protected
Definition at line 75 of file AlteraMemGenerator.hh.
Referenced by addGenerics().
The documentation for this class was generated from the following files:
AlteraMemGenerator.hh
AlteraMemGenerator.cc