OpenASIP: TPEF::TPEFDataSectionWriter Class Reference
TPEF::TPEFDataSectionWriter Class Reference
#include <TPEFDataSectionWriter.hh>
Protected Member Functions
virtual ~TPEFDataSectionWriter ()
TPEFDataSectionWriter (bool reg=true)
virtual Section::SectionType type () const
virtual void actualWriteData (BinaryStream &stream, const Section *sect) const
virtual Word elementSize (const Section *section) const
Protected Member Functions inherited from TPEF::TPEFSectionWriter
TPEFSectionWriter ()
virtual ~TPEFSectionWriter ()
virtual const BinaryWriter & parent () const
virtual void actualWriteHeader (BinaryStream &stream, const Section *sect) const
virtual void createKeys (const Section *sect) const
virtual void writeSize (BinaryStream &stream, const Section *sect) const
virtual void writeInfo (BinaryStream &stream, const Section *sect) const
virtual SectionId getSectionId () const
Protected Member Functions inherited from TPEF::SectionWriter
SectionWriter ()
virtual ~SectionWriter ()
virtual void finalize (BinaryStream &stream, Section *section) const
Private Member Functions
TPEFDataSectionWriter (const TPEFDataSectionWriter &)
No copies.
TPEFDataSectionWriter operator= (const TPEFDataSectionWriter &)
No copies.
Static Private Attributes
static const TPEFDataSectionWriter instance_
Only existing instance of class.
Additional Inherited Members
Static Public Member Functions inherited from TPEF::SectionWriter
static void writeHeader (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void writeData (BinaryStream &stream, const Section *sect, const BinaryWriter *writer)
static void finalizeBinary (BinaryStream &stream, const Binary *binaryToFinalize, const BinaryWriter *writer)
Static Protected Member Functions inherited from TPEF::SectionWriter
static void registerSectionWriter (const SectionWriter *sWriter)
static SectionId getUniqueSectionId ()
Detailed Description
Writes data section to TPEF stream.
Definition at line 48 of file TPEFDataSectionWriter.hh.
Constructor & Destructor Documentation
~TPEFDataSectionWriter()
TPEF::TPEFDataSectionWriter::~TPEFDataSectionWriter () protected virtual
Destructor.
Definition at line 68 of file TPEFDataSectionWriter.cc.
{
}
TPEFDataSectionWriter() [1/2]
TPEF::TPEFDataSectionWriter::TPEFDataSectionWriter (bool reg = true) protected
Constructor.
Definition at line 59 of file TPEFDataSectionWriter.cc.
                                                     : TPEFSectionWriter() {
    if (reg) {
        registerSectionWriter(this);
    }
}
References TPEF::SectionWriter::registerSectionWriter().
TPEFDataSectionWriter() [2/2]
TPEF::TPEFDataSectionWriter::TPEFDataSectionWriter (const TPEFDataSectionWriter &) private
No copies.
Member Function Documentation
actualWriteData()
void TPEF::TPEFDataSectionWriter::actualWriteData (BinaryStream & stream, const Section * sect) const protected virtual
Writes section's data into stream.
Parameters
stream Stream where to write.
sect Section to be written.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 88 of file TPEFDataSectionWriter.cc.
{
    const DataSection* dSection = dynamic_cast<const DataSection*>(sect);
    assert(dSection != NULL);
    FileOffset startOffset = stream.writePosition();
    SectionOffset sectOffset = 0;
    SectionKey sKey = SafePointer::sectionKeyFor(dSection);
    SectionId id = sKey.sectionId();
    for (; sectOffset < dSection->length(); sectOffset++) {
        Chunk* chunk = NULL;
        try {
            chunk = dSection->chunk(sectOffset);
        } catch (const NotChunkable& n) {
            bool sectionToBeWrittenIsNotChunkable = false;
            assert(sectionToBeWrittenIsNotChunkable);
        }
        // if referenced or first element of section
        if (SafePointer::isReferenced(chunk)) {
            SafePointer::addObjectReference(
                SectionOffsetKey(id, sectOffset), chunk);
        }
        stream.writeByte(dSection->byte(chunk));
    }
    // needed for writing section header
    SafePointer::addObjectReference(
        FileOffsetKey(startOffset), dSection->chunk(0));
    SectionSizeReplacer::setSize(
        dSection, stream.writePosition() - startOffset);
}
References TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::DataSection::byte(), TPEF::RawSection::chunk(), TPEF::ReferenceManager::SafePointer::isReferenced(), TPEF::DataSection::length(), TPEF::ReferenceManager::SectionKey::sectionId(), TPEF::ReferenceManager::SafePointer::sectionKeyFor(), TPEF::SectionSizeReplacer::setSize(), TPEF::BinaryStream::writeByte(), and TPEF::BinaryStream::writePosition().
elementSize()
Word TPEF::TPEFDataSectionWriter::elementSize (const Section * section) const protected virtual
Returns the fixed size of section elements, in this case smallest amount of bytes that is needed to store one MAU of address space.
Parameters
section Section which is written.
Returns
Size of uninitialized data element in bytes.
Reimplemented from TPEF::TPEFSectionWriter.
Definition at line 138 of file TPEFDataSectionWriter.cc.
{
    return static_cast<Word>(
        ceil(static_cast<double>(section->aSpace()->MAU()) /
             static_cast<double>(BYTE_BITWIDTH)));
}
References TPEF::Section::aSpace(), BYTE_BITWIDTH, and TPEF::ASpaceElement::MAU().
operator=()
TPEFDataSectionWriter TPEF::TPEFDataSectionWriter::operator= (const TPEFDataSectionWriter &) private
No copies.
type()
Section::SectionType TPEF::TPEFDataSectionWriter::type () const protected virtual
Returns section type which for writer is implemented.
Returns
Section type which of section that class can write.
Implements TPEF::TPEFSectionWriter.
Reimplemented in TPEF::TPEFLEDataSectionWriter.
Definition at line 77 of file TPEFDataSectionWriter.cc.
{
    return Section::ST_DATA;
}
References TPEF::Section::ST_DATA.
Member Data Documentation
instance_
const TPEFDataSectionWriter TPEF::TPEFDataSectionWriter::instance_ static private
Only existing instance of class.
Definition at line 68 of file TPEFDataSectionWriter.hh.
The documentation for this class was generated from the following files:
TPEFDataSectionWriter.hh
TPEFDataSectionWriter.cc