OpenASIP: NullInstructionField Class Reference
NullInstructionField Class Reference
#include <NullInstructionField.hh>
Public Member Functions
virtual int childFieldCount () const
virtual InstructionField & childField (int position) const
virtual int width () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static NullInstructionField & instance ()
Private Member Functions
NullInstructionField ()
virtual ~NullInstructionField ()
Static Private Attributes
static NullInstructionField instance_
The only instance.
Additional Inherited Members
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
A null version of instruction field.
Definition at line 41 of file NullInstructionField.hh.
Constructor & Destructor Documentation
NullInstructionField()
NullInstructionField::NullInstructionField () private
The constructor.
Definition at line 45 of file NullInstructionField.cc.
                                           : InstructionField(NULL) {
}
~NullInstructionField()
NullInstructionField::~NullInstructionField () private virtual
The destructor.
Definition at line 52 of file NullInstructionField.cc.
{
}
Member Function Documentation
childField()
InstructionField & NullInstructionField::childField (int position) const virtual
Always throws OutOfRange exception.
Returns
Never returns.
Exceptions
OutOfRange Always thrown.
Reimplemented from InstructionField.
Definition at line 85 of file NullInstructionField.cc.
{
    const string procName = "NullInstructionField::childField";
    throw OutOfRange(__FILE__, __LINE__, procName);
}
childFieldCount()
int NullInstructionField::childFieldCount () const virtual
Always returns 0.
Returns
0.
Implements InstructionField.
Definition at line 73 of file NullInstructionField.cc.
{
    return 0;
}
instance()
NullInstructionField & NullInstructionField::instance () static
Returns the only instance of NullInstructionField.
Returns
The only instance of NullInstructionField.
Definition at line 62 of file NullInstructionField.cc.
{
    return instance_;
}
References instance_.
Referenced by BinaryEncoding::childField(), InstructionField::childField(), MoveSlot::childField(), and InstructionField::setRelativePosition().
width()
int NullInstructionField::width () const virtual
Always returns 0.
Returns
0.
Implements InstructionField.
Definition at line 96 of file NullInstructionField.cc.
{
    return 0;
}
Member Data Documentation
instance_
NullInstructionField NullInstructionField::instance_ static private
The only instance.
Definition at line 54 of file NullInstructionField.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullInstructionField.hh
NullInstructionField.cc