OpenASIP: HDB::RFArchitecture Class Reference
HDB::RFArchitecture Class Reference
#include <RFArchitecture.hh>
Public Member Functions
RFArchitecture (int readPorts, int writePorts, int bidirPorts, int maxReads, int maxWrites, int latency, bool guardSupport, int guardLatency=0, bool zeroRegister=false)
RFArchitecture (const TTAMachine::RegisterFile *rf)
RFArchitecture (const TTAMachine::BaseRegisterFile *rf)
RFArchitecture (const TTAMachine::ImmediateUnit *rf)
virtual ~RFArchitecture ()
bool hasParameterizedWidth () const
bool hasParameterizedSize () const
void setWidth (int width)
void setSize (int size)
int size () const
int width () const
void setReadPortCount (int portCount)
int readPortCount () const
void setWritePortCount (int portCount)
int writePortCount () const
void setBidirPortCount (int portCount)
int bidirPortCount () const
void setMaxReads (int maxReads)
int maxReads () const
void setMaxWrites (int maxWrites)
int maxWrites () const
void setLatency (int latency)
int latency () const
void setGuardSupport (bool supported)
bool hasGuardSupport () const
void setZeroRegister (bool zeroRegister)
bool zeroRegister () const
int guardLatency () const
bool operator== (const RFArchitecture &rightHand) const
Public Member Functions inherited from HWBlockArchitecture
virtual ~HWBlockArchitecture ()
bool hasID () const
void setID (RowID id)
RowID id () const
Private Attributes
int readPorts_
Number of read ports.
int writePorts_
Number of write ports.
int bidirPorts_
Number of bidir ports.
int maxReads_
Maximum number of simultaneous reads.
int maxWrites_
Maximum number of ports that can read a register in the same cycle in which another port writes the same register.
int latency_
The latency.
bool guardSupport_
The guard support.
int width_
Width of the register file.
int size_
Size of the register file.
int guardLatency_
Guard latency.
bool zeroRegister_
Zero register.
Additional Inherited Members
Protected Member Functions inherited from HWBlockArchitecture
HWBlockArchitecture ()
Detailed Description
Represents the architecture of an RF in HDB.
Definition at line 50 of file RFArchitecture.hh.
Constructor & Destructor Documentation
RFArchitecture() [1/4]
HDB::RFArchitecture::RFArchitecture (int readPorts, int writePorts, int bidirPorts, int maxReads, int maxWrites, int latency, bool guardSupport, int guardLatency = 0, bool zeroRegister = false)
The constructor.
Creates an architecture that has parameterized width and size. To set fixed size or width, use setWidth or setSize method.
Parameters
readPorts The number of read ports.
writePorts The number of write ports.
bidirPorts The number of bidirectional ports.
maxReads The maximum number of simultaneous reads.
maxWrites The maximum number of simultaneous writes.
latency Latency of the register file.
guardSupport Tells whether the RF architecture supports guards.
guardLatency Latency between writing a register and updating the value of guard port.
zeroRegister Tells whether RF architecture has a zero register.
Exceptions
OutOfRange If some of the arguments is out of range.
Definition at line 63 of file RFArchitecture.cc.
    : readPorts_(readPorts),
      writePorts_(writePorts),
      bidirPorts_(bidirPorts),
      maxReads_(maxReads),
      maxWrites_(maxWrites),
      latency_(latency),
      guardSupport_(guardSupport),
      width_(0),
      size_(0),
      guardLatency_(guardLatency),
      zeroRegister_(zeroRegister) {
    if (readPorts < 0 || writePorts < 0 || bidirPorts < 0 || maxReads < 0 ||
        maxWrites < 0 || latency < 0 || guardLatency < 0) {
        const string procName = "RFArchitecture::RFArchitecture";
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
}
References guardLatency(), latency(), maxReads(), and maxWrites().
RFArchitecture() [2/4]
HDB::RFArchitecture::RFArchitecture (const TTAMachine::RegisterFile * rf)
Builds RFArchitecture from RegisterFile*.
Parameters
rf RegisterFile*.
Definition at line 90 of file RFArchitecture.cc.
{
    int readPorts = 0;
    int writePorts = 0;
    int bidirPorts = 0;
    for (int i = 0; i < rf->portCount(); i++) {
        TTAMachine::Socket* input = rf->port(i)->inputSocket();
        TTAMachine::Socket* output = rf->port(i)->outputSocket();
        if (input != NULL && output != NULL) {
            bidirPorts++;
        } else if (input != NULL) {
            readPorts++;
        } else if (output != NULL) {
            writePorts++;
        }
    }
    bool guardSupport = false;
    if (rf->isRegistered()) {
        TTAMachine::Machine::BusNavigator navigator =
            rf->machine()->busNavigator();
        for (int i = 0; i < navigator.count(); i++) {
            TTAMachine::Bus* bus = navigator.item(i);
            for (int n = 0; n < bus->guardCount(); n++) {
                TTAMachine::Guard* guard = bus->guard(n);
                TTAMachine::RegisterGuard* registerGuard =
                    dynamic_cast<TTAMachine::RegisterGuard*>(guard);
                if (registerGuard != NULL) {
                    if (registerGuard->registerFile() == rf) {
                        guardSupport = true;
                    }
                }
            }
        }
    }
    readPorts_ = readPorts;
    writePorts_ = writePorts;
    bidirPorts_ = bidirPorts;
    maxReads_ = rf->maxReads();
    maxWrites_ = rf->maxWrites();
    latency_ = 1;
    guardSupport_ = guardSupport;
    width_ = rf->width();
    size_ = rf->numberOfRegisters();
    guardLatency_ = rf->guardLatency();
}
References bidirPorts_, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::RegisterFile::guardLatency(), guardLatency_, guardSupport_, TTAMachine::Port::inputSocket(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), latency_, TTAMachine::Component::machine(), TTAMachine::RegisterFile::maxReads(), maxReads_, TTAMachine::RegisterFile::maxWrites(), maxWrites_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), readPorts_, TTAMachine::RegisterGuard::registerFile(), size_, TTAMachine::BaseRegisterFile::width(), width_, and writePorts_.
RFArchitecture() [3/4]
HDB::RFArchitecture::RFArchitecture (const TTAMachine::BaseRegisterFile * baseRF)
Builds RFArchitecture from BaseRegisterFile*.
Parameters
baseRF BaseRegisterfile*.
Definition at line 177 of file RFArchitecture.cc.
{
    const TTAMachine::ImmediateUnit* imm =
        dynamic_cast<const TTAMachine::ImmediateUnit*>(baseRF);
    const TTAMachine::RegisterFile* rf =
        dynamic_cast<const TTAMachine::RegisterFile*>(baseRF);
    if (imm != NULL) {
        int readPorts = 0;
        int writePorts = 0;
        int bidirPorts = 0;
        for (int i = 0; i < imm->portCount(); i++) {
            TTAMachine::Socket* input = imm->port(i)->inputSocket();
            TTAMachine::Socket* output = imm->port(i)->outputSocket();
            if (input != NULL && output != NULL) {
                bidirPorts++;
            } else if (input != NULL) {
                readPorts++;
            } else if (output != NULL) {
                writePorts++;
            }
        }
        // immediate unit has no MaxReadWrite, no MaxReads and no guard support
        readPorts_ = readPorts;
        writePorts_ = writePorts;
        bidirPorts_ = bidirPorts;
        maxReads_ = 0;
        maxWrites_ = 0;
        latency_ = 1;
        guardSupport_ = false;
        width_ = imm->width();
        size_ = imm->numberOfRegisters();
        guardLatency_ = 0;
    }
    if (rf != NULL) {
        int readPorts = 0;
        int writePorts = 0;
        int bidirPorts = 0;
        for (int i = 0; i < rf->portCount(); i++) {
            TTAMachine::Socket* input = rf->port(i)->inputSocket();
            TTAMachine::Socket* output = rf->port(i)->outputSocket();
            if (input != NULL && output != NULL) {
                bidirPorts++;
            } else if (input != NULL) {
                readPorts++;
            } else if (output != NULL) {
                writePorts++;
            }
        }
        bool guardSupport = false;
        if (rf->isRegistered()) {
            TTAMachine::Machine::BusNavigator navigator =
                rf->machine()->busNavigator();
            for (int i = 0; i < navigator.count(); i++) {
                TTAMachine::Bus* bus = navigator.item(i);
                for (int n = 0; n < bus->guardCount(); n++) {
                    TTAMachine::Guard* guard = bus->guard(n);
                    TTAMachine::RegisterGuard* registerGuard =
                        dynamic_cast<TTAMachine::RegisterGuard*>(guard);
                    if (registerGuard != NULL) {
                        if (registerGuard->registerFile() == rf) {
                            guardSupport = true;
                        }
                    }
                }
            }
        }
        readPorts_ = readPorts;
        writePorts_ = writePorts;
        bidirPorts_ = bidirPorts;
        maxReads_ = rf->maxReads();
        maxWrites_ = rf->maxWrites();
        latency_ = 1;
        guardSupport_ = guardSupport;
        width_ = rf->width();
        size_ = rf->numberOfRegisters();
        guardLatency_ = rf->guardLatency();
    }
}
References bidirPorts_, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), TTAMachine::RegisterFile::guardLatency(), guardLatency_, guardSupport_, TTAMachine::Port::inputSocket(), TTAMachine::Component::isRegistered(), TTAMachine::Machine::Navigator< ComponentType >::item(), latency_, TTAMachine::Component::machine(), TTAMachine::RegisterFile::maxReads(), maxReads_, TTAMachine::RegisterFile::maxWrites(), maxWrites_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), readPorts_, TTAMachine::RegisterGuard::registerFile(), size_, TTAMachine::BaseRegisterFile::width(), width_, and writePorts_.
RFArchitecture() [4/4]
HDB::RFArchitecture::RFArchitecture (const TTAMachine::ImmediateUnit * imm)
Builds RFArchitecture from ImmediateUnit*.
Parameters
imm ImmediateUnit*.
Definition at line 142 of file RFArchitecture.cc.
{
    int readPorts = 0;
    int writePorts = 0;
    int bidirPorts = 0;
    for (int i = 0; i < imm->portCount(); i++) {
        TTAMachine::Socket* input = imm->port(i)->inputSocket();
        TTAMachine::Socket* output = imm->port(i)->outputSocket();
        if (input != NULL && output != NULL) {
            bidirPorts++;
        } else if (input != NULL) {
            readPorts++;
        } else if (output != NULL) {
            writePorts++;
        }
    }
    // immediate unit has no MaxReadWrite, no MaxReads and no guard support
    readPorts_ = readPorts;
    writePorts_ = writePorts;
    bidirPorts_ = bidirPorts;
    maxReads_ = 0;
    maxWrites_ = 0;
    latency_ = 1;
    guardSupport_ = false;
    width_ = imm->width();
    size_ = imm->numberOfRegisters();
    guardLatency_ = 0;
}
References bidirPorts_, guardLatency_, guardSupport_, TTAMachine::Port::inputSocket(), latency_, maxReads_, maxWrites_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Port::outputSocket(), TTAMachine::BaseRegisterFile::port(), TTAMachine::Unit::portCount(), readPorts_, size_, TTAMachine::BaseRegisterFile::width(), width_, and writePorts_.
~RFArchitecture()
HDB::RFArchitecture::~RFArchitecture () virtual
The destructor.
Definition at line 261 of file RFArchitecture.cc.
{
}
Member Function Documentation
bidirPortCount()
int HDB::RFArchitecture::bidirPortCount () const
Returns the number of bidirectional ports.
Returns
The number of bidirectional ports.
Definition at line 422 of file RFArchitecture.cc.
{
    return bidirPorts_;
}
References bidirPorts_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), InterpolatingRFEstimator::createSearch(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddRFFromHDBDialog::onAdd(), operator==(), and HDBToHtml::rfArchToHtml().
guardLatency()
int HDB::RFArchitecture::guardLatency () const
Returns the guard latency.
Returns
The guard latency.
Definition at line 551 of file RFArchitecture.cc.
{
    return guardLatency_;
}
References guardLatency_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), RFTestbenchGenerator::createMachineState(), InterpolatingRFEstimator::createSearch(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), operator==(), RFArchitecture(), and HDBToHtml::rfArchToHtml().
hasGuardSupport()
bool HDB::RFArchitecture::hasGuardSupport () const
Tells whether the RF supports guards.
Returns
True if the RF supports guards, otherwise false.
Definition at line 519 of file RFArchitecture.cc.
{
    return guardSupport_;
}
References guardSupport_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), InterpolatingRFEstimator::createSearch(), operator==(), and HDBToHtml::rfArchToHtml().
hasParameterizedSize()
bool HDB::RFArchitecture::hasParameterizedSize () const
Tells whether the RF has parameterized size.
Returns
True if the RF has parameterized size, otherwise false.
Definition at line 282 of file RFArchitecture.cc.
{
    return size_ == 0;
}
References size_.
Referenced by HDB::HDBManager::addRFArchitecture(), RFTestbenchGenerator::createMachineState(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), BlockImplementationDialog::onHDBSelection(), operator==(), HDBToHtml::rfArchToHtml(), and size().
hasParameterizedWidth()
bool HDB::RFArchitecture::hasParameterizedWidth () const
Tells whether the RF has parameterized width.
Returns
True if the RF has parameterized width, otherwise false.
Definition at line 271 of file RFArchitecture.cc.
{
    return width_ == 0;
}
References width_.
Referenced by HDB::HDBManager::addRFArchitecture(), RFTestbenchGenerator::createMachineState(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), BlockImplementationDialog::onHDBSelection(), operator==(), HDBToHtml::rfArchToHtml(), and width().
latency()
int HDB::RFArchitecture::latency () const
Returns the latency of the register file.
Returns
The latency of the register file.
Definition at line 497 of file RFArchitecture.cc.
{
    return latency_;
}
References latency_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), ProGe::ProcessorGenerator::checkIULatencies(), InterpolatingRFEstimator::createSearch(), RFTestbenchGenerator::createStimulus(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), operator==(), RFArchitecture(), HDBToHtml::rfArchToHtml(), and setLatency().
maxReads()
int HDB::RFArchitecture::maxReads () const
Returns the maximum number of simultaneous reads.
Returns
The maximum number of simultaneous reads.
Definition at line 447 of file RFArchitecture.cc.
{
    return maxReads_;
}
References maxReads_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), RFTestbenchGenerator::createMachineState(), InterpolatingRFEstimator::createSearch(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), operator==(), RFArchitecture(), HDBToHtml::rfArchToHtml(), and setMaxReads().
maxWrites()
int HDB::RFArchitecture::maxWrites () const
Returns the maximum number of simultaneous writes.
Returns
The maximum number of simultaneous writes.
Definition at line 472 of file RFArchitecture.cc.
{
    return maxWrites_;
}
References maxWrites_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), RFTestbenchGenerator::createMachineState(), InterpolatingRFEstimator::createSearch(), AddRFFromHDBDialog::loadHDB(), AddRFFromHDBDialog::onAdd(), operator==(), RFArchitecture(), HDBToHtml::rfArchToHtml(), and setMaxWrites().
operator==()
bool HDB::RFArchitecture::operator== (const RFArchitecture & rightHand) const
Checks whether the given RF has a mathing architecture with the given RF architecture instance.
Parameters
rightHand Right hand operand.
Returns
True if the architectures match, otherwise false.
Definition at line 564 of file RFArchitecture.cc.
{
    if (rightHand.readPortCount() != readPortCount()) {
        return false;
    }
    if (rightHand.writePortCount() != writePortCount()) {
        return false;
    }
    if (rightHand.bidirPortCount() != bidirPortCount()) {
        return false;
    }
    if (rightHand.maxReads() != maxReads()) {
        return false;
    }
    if (rightHand.maxWrites() != maxWrites()) {
        return false;
    }
    if (rightHand.latency() != latency()) {
        return false;
    }
    if (rightHand.hasGuardSupport() != hasGuardSupport()) {
        return false;
    }
    if (rightHand.guardLatency() != guardLatency()) {
        return false;
    }
    if (rightHand.hasParameterizedSize() != hasParameterizedSize()) {
        return false;
    }
    if (!hasParameterizedSize()) {
        if (rightHand.size() != size()) {
            return false;
        }
    }
    if (rightHand.hasParameterizedWidth() != hasParameterizedWidth()) {
        return false;
    }
    if (!hasParameterizedWidth()) {
        if (rightHand.width() != width()) {
            return false;
        }
    }
    return true;
}
References bidirPortCount(), guardLatency(), hasGuardSupport(), hasParameterizedSize(), hasParameterizedWidth(), latency(), maxReads(), maxWrites(), readPortCount(), size(), width(), and writePortCount().
readPortCount()
int HDB::RFArchitecture::readPortCount () const
Returns the number of read ports.
Returns
The number of read ports.
Definition at line 372 of file RFArchitecture.cc.
{
    return readPorts_;
}
References readPorts_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), InterpolatingRFEstimator::createSearch(), RFTestbenchGenerator::createStimulus(), RFTestbenchGenerator::createTbCode(), RFTestbenchGenerator::createTbInstantiation(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), operator==(), and HDBToHtml::rfArchToHtml().
setBidirPortCount()
void HDB::RFArchitecture::setBidirPortCount (int portCount)
Sets the number of bidirectional ports.
Parameters
portCount The number of bidirectional ports.
Exceptions
OutOfRange If the given port count is negative.
Definition at line 409 of file RFArchitecture.cc.
{
    if (portCount < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    bidirPorts_ = portCount;
}
References __func__, and bidirPorts_.
Referenced by RFArchitectureDialog::onOK().
setGuardSupport()
void HDB::RFArchitecture::setGuardSupport (bool supported)
Sets the guard support of the register file.
Parameters
supported True if supported, otherwise false.
Definition at line 508 of file RFArchitecture.cc.
{
    guardSupport_ = supported;
}
References guardSupport_.
Referenced by RFArchitectureDialog::onOK().
setLatency()
void HDB::RFArchitecture::setLatency (int latency)
Sets the latency of the register file.
Parameters
latency The new latency.
Exceptions
OutOfRange If the given latency is smaller than 1.
Definition at line 484 of file RFArchitecture.cc.
{
    if (latency < 1) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    latency_ = latency;
}
References __func__, latency(), and latency_.
Referenced by RFArchitectureDialog::onOK().
setMaxReads()
void HDB::RFArchitecture::setMaxReads (int maxReads)
Sets the maximum number of simultaneous reads.
Parameters
maxReads The new value.
Exceptions
OutOfRange If the given value is negative.
Definition at line 434 of file RFArchitecture.cc.
{
    if (maxReads < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    maxReads_ = maxReads;
}
References __func__, maxReads(), and maxReads_.
Referenced by RFArchitectureDialog::onOK().
setMaxWrites()
void HDB::RFArchitecture::setMaxWrites (int maxWrites)
Sets the maximum number of simultaneous writes.
Parameters
maxWrites The new value.
Exceptions
OutOfRange If the given value is negative.
Definition at line 459 of file RFArchitecture.cc.
{
    if (maxWrites < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    maxWrites_ = maxWrites;
}
References __func__, maxWrites(), and maxWrites_.
Referenced by RFArchitectureDialog::onOK().
setReadPortCount()
void HDB::RFArchitecture::setReadPortCount (int portCount)
Sets the number of read ports.
Parameters
portCount The number of read ports.
Exceptions
OutOfRange If the given port count is negative.
Definition at line 359 of file RFArchitecture.cc.
{
    if (portCount < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    readPorts_ = portCount;
}
References __func__, and readPorts_.
Referenced by RFArchitectureDialog::onOK().
setSize()
void HDB::RFArchitecture::setSize (int size)
Sets the size of the register file.
Parameters
size The new size.
Exceptions
OutOfRange If the size is less than 1.
Definition at line 310 of file RFArchitecture.cc.
{
    if (size < 1) {
        const string procName = "RFArchitecture::setSize";
        throw OutOfRange(__FILE__, __LINE__, procName);
    } else {
        size_ = size;
    }
}
References size(), and size_.
Referenced by RFTestbenchGenerator::createMachineState(), RFArchitectureDialog::onOK(), and HDB::HDBManager::rfArchitectureByID().
setWidth()
void HDB::RFArchitecture::setWidth (int width)
Sets the width of the register file.
Parameters
width The new width.
Exceptions
OutOfRange If the width is less than 1.
Definition at line 294 of file RFArchitecture.cc.
{
    if (width < 1) {
        const string procName = "RFArchitecture::setWidth";
        throw OutOfRange(__FILE__, __LINE__, procName);
    } else {
        width_ = width;
    }
}
References width(), and width_.
Referenced by RFTestbenchGenerator::createMachineState(), RFArchitectureDialog::onOK(), and HDB::HDBManager::rfArchitectureByID().
setWritePortCount()
void HDB::RFArchitecture::setWritePortCount (int portCount)
Sets the number of write ports.
Parameters
portCount The number of write ports.
Exceptions
OutOfRange If the given port count is smaller than 1.
Definition at line 384 of file RFArchitecture.cc.
{
    if (portCount < 0) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    writePorts_ = portCount;
}
References __func__, and writePorts_.
Referenced by RFArchitectureDialog::onOK().
setZeroRegister()
void HDB::RFArchitecture::setZeroRegister (bool zeroRegister)
Sets the zero register flag of the register file
Parameters
zeroRegister True if has a zero register, otherwise false
Definition at line 530 of file RFArchitecture.cc.
{
    zeroRegister_ = zeroRegister;
}
References zeroRegister(), and zeroRegister_.
Referenced by RFArchitectureDialog::onOK().
size()
int HDB::RFArchitecture::size () const
Returns the size of the register file.
Returns
The size of the register file.
Exceptions
NotAvailable If the size is parameterized.
Definition at line 326 of file RFArchitecture.cc.
{
    if (hasParameterizedSize()) {
        const string procName = "RFArchitecture::size";
        throw NotAvailable(__FILE__, __LINE__, procName);
    } else {
        return size_;
    }
}
References hasParameterizedSize(), and size_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), RFTestbenchGenerator::createMachineState(), InterpolatingRFEstimator::createSearch(), RFTestbenchGenerator::createStimulus(), RFTestbenchGenerator::createTbInstantiation(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), RFTestbenchGenerator::opcodePortWidth(), operator==(), HDBToHtml::rfArchToHtml(), and setSize().
width()
int HDB::RFArchitecture::width () const
Returns the width of the register file.
Returns
The width of the register file.
Exceptions
NotAvailable If the width of the register file is parameterized.
Definition at line 343 of file RFArchitecture.cc.
{
    if (hasParameterizedWidth()) {
        const string procName = "RFArchitecture::width";
        throw NotAvailable(__FILE__, __LINE__, procName);
    } else {
        return width_;
    }
}
References hasParameterizedWidth(), and width_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), RFTestbenchGenerator::createMachineState(), InterpolatingRFEstimator::createSearch(), RFTestbenchGenerator::createStimulus(), RFTestbenchGenerator::createStimulusArrays(), RFTestbenchGenerator::createTbInstantiation(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddIUFromHDBDialog::onAdd(), AddRFFromHDBDialog::onAdd(), operator==(), HDBToHtml::rfArchToHtml(), and setWidth().
writePortCount()
int HDB::RFArchitecture::writePortCount () const
Returns the number of write ports.
Returns
The number of write ports.
Definition at line 397 of file RFArchitecture.cc.
{
    return writePorts_;
}
References writePorts_.
Referenced by HDB::HDBManager::addRFArchitecture(), CostDatabase::buildRegisterFiles(), ImplementationTester::canTestRF(), InterpolatingRFEstimator::createSearch(), RFTestbenchGenerator::createStimulus(), RFTestbenchGenerator::createTbCode(), RFTestbenchGenerator::createTbInstantiation(), AddRFFromHDBDialog::loadHDB(), AddIUFromHDBDialog::loadHDB(), AddRFFromHDBDialog::onAdd(), operator==(), and HDBToHtml::rfArchToHtml().
zeroRegister()
bool HDB::RFArchitecture::zeroRegister () const
Tells whether the RF has a zero register
Returns
True if RF has a zero register
Definition at line 541 of file RFArchitecture.cc.
{
    return zeroRegister_;
}
References zeroRegister_.
Referenced by HDB::HDBManager::addRFArchitecture(), RFTestbenchGenerator::createMachineState(), AddRFFromHDBDialog::onAdd(), HDBToHtml::rfArchToHtml(), and setZeroRegister().
Member Data Documentation
bidirPorts_
int HDB::RFArchitecture::bidirPorts_ private
Number of bidir ports.
Definition at line 104 of file RFArchitecture.hh.
Referenced by bidirPortCount(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setBidirPortCount().
guardLatency_
int HDB::RFArchitecture::guardLatency_ private
Guard latency.
Definition at line 119 of file RFArchitecture.hh.
Referenced by guardLatency(), RFArchitecture(), RFArchitecture(), and RFArchitecture().
guardSupport_
bool HDB::RFArchitecture::guardSupport_ private
The guard support.
Definition at line 113 of file RFArchitecture.hh.
Referenced by hasGuardSupport(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setGuardSupport().
latency_
int HDB::RFArchitecture::latency_ private
The latency.
Definition at line 111 of file RFArchitecture.hh.
Referenced by latency(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setLatency().
maxReads_
int HDB::RFArchitecture::maxReads_ private
Maximum number of simultaneous reads.
Definition at line 106 of file RFArchitecture.hh.
Referenced by maxReads(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setMaxReads().
maxWrites_
int HDB::RFArchitecture::maxWrites_ private
Maximum number of ports that can read a register in the same cycle in which another port writes the same register.
Definition at line 109 of file RFArchitecture.hh.
Referenced by maxWrites(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setMaxWrites().
readPorts_
int HDB::RFArchitecture::readPorts_ private
Number of read ports.
Definition at line 100 of file RFArchitecture.hh.
Referenced by readPortCount(), RFArchitecture(), RFArchitecture(), RFArchitecture(), and setReadPortCount().
size_
int HDB::RFArchitecture::size_ private
Size of the register file.
Definition at line 117 of file RFArchitecture.hh.
Referenced by hasParameterizedSize(), RFArchitecture(), RFArchitecture(), RFArchitecture(), setSize(), and size().
width_
int HDB::RFArchitecture::width_ private
Width of the register file.
Definition at line 115 of file RFArchitecture.hh.
Referenced by hasParameterizedWidth(), RFArchitecture(), RFArchitecture(), RFArchitecture(), setWidth(), and width().
writePorts_
int HDB::RFArchitecture::writePorts_ private
Number of write ports.
Definition at line 102 of file RFArchitecture.hh.
Referenced by RFArchitecture(), RFArchitecture(), RFArchitecture(), setWritePortCount(), and writePortCount().
zeroRegister_
bool HDB::RFArchitecture::zeroRegister_ private
Zero register.
Definition at line 121 of file RFArchitecture.hh.
Referenced by setZeroRegister(), and zeroRegister().
The documentation for this class was generated from the following files:
RFArchitecture.hh
RFArchitecture.cc