OpenASIP: HighlightExecPercentageCmd Class Reference
HighlightExecPercentageCmd Class Reference
#include <HighlightExecPercentageCmd.hh>
Public Member Functions
HighlightExecPercentageCmd ()
virtual ~HighlightExecPercentageCmd ()
virtual bool Do ()
virtual int id () const
virtual HighlightExecPercentageCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for highlighting move execution counts in the disassembly window.
Definition at line 41 of file HighlightExecPercentageCmd.hh.
Constructor & Destructor Documentation
HighlightExecPercentageCmd()
HighlightExecPercentageCmd::HighlightExecPercentageCmd ()
The Constructor.
Definition at line 44 of file HighlightExecPercentageCmd.cc.
                                                      :
    GUICommand("Highlight Execution Percentage", NULL) {
    }
Referenced by create().
~HighlightExecPercentageCmd()
HighlightExecPercentageCmd::~HighlightExecPercentageCmd () virtual
The Destructor.
Definition at line 52 of file HighlightExecPercentageCmd.cc.
{
}
Member Function Documentation
create()
HighlightExecPercentageCmd * HighlightExecPercentageCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 97 of file HighlightExecPercentageCmd.cc.
{
    return new HighlightExecPercentageCmd();
}
References HighlightExecPercentageCmd().
Do()
bool HighlightExecPercentageCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file HighlightExecPercentageCmd.cc.
{
    ProximDisassemblyWindow* window = ProximToolbox::disassemblyWindow();
    assert(window != NULL);
    DisasmExecPercentageAttrProvider* attrProvider =
        new DisasmExecPercentageAttrProvider(*ProximToolbox::frontend());
    window->setMoveAttrProvider(attrProvider);
    window->Refresh();
    return true;
}
References assert, ProximToolbox::disassemblyWindow(), ProximToolbox::frontend(), and ProximDisassemblyWindow::setMoveAttrProvider().
icon()
std::string HighlightExecPercentageCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 77 of file HighlightExecPercentageCmd.cc.
{
    return "clear_console.png";
}
id()
int HighlightExecPercentageCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 86 of file HighlightExecPercentageCmd.cc.
{
    return ProximConstants::COMMAND_HIGHLIGHT_EXEC_PERCENTAGE;
}
References ProximConstants::COMMAND_HIGHLIGHT_EXEC_PERCENTAGE.
isEnabled()
bool HighlightExecPercentageCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
True if the console window exists.
Implements GUICommand.
Definition at line 108 of file HighlightExecPercentageCmd.cc.
{
    if (ProximToolbox::frontend()->isProgramLoaded()) {
    return true;
    } else {
    return false;
    }
}
References ProximToolbox::frontend().
The documentation for this class was generated from the following files:
HighlightExecPercentageCmd.hh
HighlightExecPercentageCmd.cc