OpenASIP: TPEF::TPEFUDataSectionReader Class Reference
TPEF::TPEFUDataSectionReader Class Reference
#include <TPEFUDataSectionReader.hh>
Protected Member Functions
TPEFUDataSectionReader ()
virtual ~TPEFUDataSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFUDataSectionReader (const TPEFUDataSectionReader &)
Copying not allowed.
TPEFUDataSectionReader & operator= (TPEFUDataSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFUDataSectionReader proto_
Prototype instance of TPEFUDataSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads uninitialized data section from TPEF binary file.
Definition at line 46 of file TPEFUDataSectionReader.hh.
Constructor & Destructor Documentation
TPEFUDataSectionReader() [1/2]
TPEF::TPEFUDataSectionReader::TPEFUDataSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 54 of file TPEFUDataSectionReader.cc.
                                               : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFUDataSectionReader()
TPEF::TPEFUDataSectionReader::~TPEFUDataSectionReader () protected virtual
Destructor.
Definition at line 61 of file TPEFUDataSectionReader.cc.
{
}
TPEFUDataSectionReader() [2/2]
TPEF::TPEFUDataSectionReader::TPEFUDataSectionReader (const TPEFUDataSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFUDataSectionReader & TPEF::TPEFUDataSectionReader::operator= (TPEFUDataSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFUDataSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 87 of file TPEFUDataSectionReader.cc.
{
    // base classes implementation must be called with these TPEF readers
    TPEFSectionReader::readData(stream, section);
    UDataSection* uDataSection = dynamic_cast<UDataSection*>(section);
    assert(uDataSection != NULL);
    // check that link section is defined properly
    assert(header().linkId == 0);
    dynamic_cast<TPEFReader*>(
        parent())->addSectionSize(section, header().bodyLength);
    uDataSection->setDataLength(header().bodyLength);
}
References assert, TPEF::TPEFSectionReader::Header::bodyLength, TPEF::TPEFSectionReader::header(), TPEF::TPEFSectionReader::parent(), TPEF::TPEFSectionReader::readData(), and TPEF::RawSection::setDataLength().
type()
Section::SectionType TPEF::TPEFUDataSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 70 of file TPEFUDataSectionReader.cc.
{
    return Section::ST_UDATA;
}
References TPEF::Section::ST_UDATA.
Member Data Documentation
proto_
TPEFUDataSectionReader TPEF::TPEFUDataSectionReader::proto_ static private
Prototype instance of TPEFUDataSectionReader to be registered to SectionReader.
Definition at line 58 of file TPEFUDataSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFUDataSectionReader.hh
TPEFUDataSectionReader.cc