OpenASIP: BFPostpassLoopDRE Class Reference
BFPostpassLoopDRE Class Reference
#include <BFPostpassLoopDRE.hh>
Public Member Functions
BFPostpassLoopDRE (BF2Scheduler &sched, MoveNode &mn, int srcCycle)
bool operator() () override
void undoOnlyMe () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Member Functions
bool dreAllowed ()
Private Attributes
MoveNode & mn_
MoveNode * prologMN_
int srcCycle_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 46 of file BFPostpassLoopDRE.hh.
Constructor & Destructor Documentation
BFPostpassLoopDRE()
BFPostpassLoopDRE::BFPostpassLoopDRE (BF2Scheduler & sched, MoveNode & mn, int srcCycle) inline
Definition at line 48 of file BFPostpassLoopDRE.hh.
                                                                       :
        BFOptimization(sched), mn_(mn), srcCycle_(srcCycle) {}
Member Function Documentation
dreAllowed()
bool BFPostpassLoopDRE::dreAllowed () private
Definition at line 88 of file BFPostpassLoopDRE.cc.
{
    DataDependenceGraph::EdgeSet edges = ddg().outEdges(mn_);
    for (auto edge: edges) {
        if (edge->edgeReason() == DataDependenceEdge::EDGE_OPERATION) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "DRE not allowed due op edge: "
                      << edge->toString()  << std::endl;
#endif
            return false;
        }
        if ((edge->edgeReason() == DataDependenceEdge::EDGE_REGISTER ||
             edge->edgeReason() ==DataDependenceEdge::EDGE_RA) &&
            edge->dependenceType() == DataDependenceEdge::DEP_RAW) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "DRE not allowed due edge: "
                      << edge->toString()  << std::endl;
#endif
            return false;
        }
    }
    return true;
}
References BFOptimization::ddg(), DataDependenceEdge::DEP_RAW, DataDependenceEdge::EDGE_OPERATION, DataDependenceEdge::EDGE_RA, DataDependenceEdge::EDGE_REGISTER, mn_, and BoostGraph< GraphNode, GraphEdge >::outEdges().
Referenced by operator()().
operator()()
bool BFPostpassLoopDRE::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 54 of file BFPostpassLoopDRE.cc.
{
    if (!sched_.killDeadResults()) {
        return false;
    }
    if (!dreAllowed()) {
        return false;
    }
    // Create a copy to prolog.
    prologMN_ = duplicator().getMoveNode(mn_);
    if (prologMN_ == NULL) {
        return false;
    }
    int prologCycle = BF2Scheduler::PROLOG_CYCLE_BIAS + srcCycle_;
    if (prologRM()->canAssign(prologCycle, *prologMN_)) {
        prologRM()->assign(prologCycle, *prologMN_);
        // then remove
        ddg().copyDepsOver(mn_, true, false);
        ddg().dropNode(mn_);
        sched_.nodeKilled(mn_);
        return true;
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    } else {
        std::cerr << "\t\t\t\tProlog cycle assign fail for loop-dre: "
                  << prologMN_->toString()
                  << " prolog cycle: " << prologCycle << std::endl;
#endif
    }
    return false;
}
References SimpleResourceManager::assign(), BFOptimization::canAssign(), DataDependenceGraph::copyDepsOver(), BFOptimization::ddg(), dreAllowed(), BoostGraph< GraphNode, GraphEdge >::dropNode(), BFOptimization::duplicator(), MoveNodeDuplicator::getMoveNode(), BF2Scheduler::killDeadResults(), mn_, BF2Scheduler::nodeKilled(), BF2Scheduler::PROLOG_CYCLE_BIAS, prologMN_, BFOptimization::prologRM(), BFOptimization::sched_, srcCycle_, and MoveNode::toString().
undoOnlyMe()
void BFPostpassLoopDRE::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 111 of file BFPostpassLoopDRE.cc.
{
    ddg().restoreNodeFromParent(mn_);
    sched_.nodeResurrected(mn_);
    prologRM()->unassign(*prologMN_);
}
References BFOptimization::ddg(), mn_, BF2Scheduler::nodeResurrected(), prologMN_, BFOptimization::prologRM(), BoostGraph< GraphNode, GraphEdge >::restoreNodeFromParent(), BFOptimization::sched_, and SimpleResourceManager::unassign().
Member Data Documentation
mn_
MoveNode& BFPostpassLoopDRE::mn_ private
Definition at line 55 of file BFPostpassLoopDRE.hh.
Referenced by dreAllowed(), operator()(), and undoOnlyMe().
prologMN_
MoveNode* BFPostpassLoopDRE::prologMN_ private
Definition at line 56 of file BFPostpassLoopDRE.hh.
Referenced by operator()(), and undoOnlyMe().
srcCycle_
int BFPostpassLoopDRE::srcCycle_ private
Definition at line 57 of file BFPostpassLoopDRE.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPostpassLoopDRE.hh
BFPostpassLoopDRE.cc