OpenASIP: BFPushMoveUp Class Reference
BFPushMoveUp Class Reference
#include <BFPushMoveUp.hh>
Public Member Functions
BFPushMoveUp (BF2Scheduler &sched, MoveNode &mn, int lc)
bool operator() ()
Public Member Functions inherited from BFRescheduleMove
BFRescheduleMove (BF2Scheduler &sched, MoveNode &mn)
void undoOnlyMe ()
Public Member Functions inherited from BFUnscheduleMove
BFUnscheduleMove (BF2Scheduler &sched, MoveNode &mn)
void unscheduleOriginal ()
void undoOnlyMe ()
bool operator() ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
int lc_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFUnscheduleMove
void returnOriginal ()
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFRescheduleMove
std::stack< Reversible * > midChildren_
Protected Attributes inherited from BFUnscheduleMove
MoveNode & mn_
int oldCycle_
const TTAMachine::Bus * oldBus_
const TTAMachine::Bus * prologBus_
int oldImmWriteCycle_
int prologImmWriteCycle_
const TTAMachine::FunctionUnit * dstFU_
const TTAMachine::FunctionUnit * srcFU_
const TTAMachine::ImmediateUnit * immu_
int immRegIndex_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFUnscheduleMove
static int recurseCounter_ = 0
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 48 of file BFPushMoveUp.hh.
Constructor & Destructor Documentation
BFPushMoveUp()
BFPushMoveUp::BFPushMoveUp (BF2Scheduler & sched, MoveNode & mn, int lc) inline
Definition at line 50 of file BFPushMoveUp.hh.
                                                   :
        BFRescheduleMove(sched,mn), lc_(lc) {}
Member Function Documentation
operator()()
bool BFPushMoveUp::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 47 of file BFPushMoveUp.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    static int dotCount = 0;
#endif
    bool isTrigger = mn_.isDestinationOperation() &&
        mn_.move().destination().isTriggering();
    if (lc_ == -1) {
        std::cerr << "incoming lc -1 on pushmoveup!"  << std::endl;
        assert(false);
    }
    if (mn_.move().isControlFlowMove()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t|TCannot reschedule control flow move!" << std::endl;
#endif
        return false;
    }
    if (&mn_ == sched_.guardWriteNode()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t|TCannot reschedule guard write move!" << std::endl;
#endif
        return false;
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    recurseCounter_++;
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\tPushing move up: " << mn_.toString() << " to cycle: "
              << lc_ << std::endl;
#endif
    // first push operands if I'm trigger?
    if (isTrigger && mn_.destinationOperation().inputMoveCount() > 1) {
        ProgramOperation& dstPO = mn_.destinationOperation();
        for (int i = 0; i < dstPO.inputMoveCount(); i++) {
            MoveNode& input = dstPO.inputMove(i);
            if (input.isScheduled() &&
                !input.move().destination().isTriggering()) {
                if (input.cycle() > lc_) {
                    // TODO: what if this fails??
                    runPreChild(new BFPushMoveUp(sched_, input, lc_));
                }
            }
        }
    }
    unscheduleOriginal();
    int ddgLC = ddg().latestCycle(mn_,ii());
    int ddgEC = ddg().earliestCycle(mn_,ii());
    if (ddgLC == -1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "ddg latest cycle -1 in pushmoveup of:"
                  << mn_.toString() << std::endl;
#endif
        returnOriginal();
        return false;
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\t\tPushing move: " << mn_.toString()
              << " up, ddgLC now: " << ddgLC << std::endl;
#endif
    int lc = std::min(lc_, ddgLC);
    int rmlc = rmLC(lc, mn_);
    if (ddgEC > lc) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tMay need to push predecessors.." << std::endl;
#endif
        BFPushDepsUp* pusher = new BFPushDepsUp(sched_, mn_, lc);
        if ((*pusher)()) {
            midChildren_.push(pusher);
            ddgEC = ddg().earliestCycle(mn_, ii());
            if (ddgEC > lc) {
                std::cerr << "\t\tDDG earliest cycle still too early: "
                          << ddgEC << std::endl;
                ddg().writeToDotFile("ec_still_early.dot");
                assert(false);
            }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
            std::cerr << "\t\tPredecessors pushed ok!" << std::endl;
#endif
//            assert(ddg().earliestCycle(mn_) <= lc);
        } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            for (int i = 0; i < recurseCounter_*2; i++)
                std::cerr << "\t";
            std::cerr << "\t\tDDG ec too late, Need to recursively push more,"
                      << " which failed" << std::endl;
#endif
            delete pusher;
            returnOriginal();
            undoAndRemoveChildren(preChildren_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            recurseCounter_--;
#endif
            return false;
        }
        // TODO: this is buggy. should have back edge
        ddgLC = ddg().latestCycle(mn_,ii());
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tddgLC of " << mn_.toString()
                  << " after pushing preds: " << ddgLC << std::endl;
#endif
        rmlc = rmLC(std::min(lc_, ddgLC), mn_);
    }
    if (rmlc == -1 || rmlc < ddgEC) {
        if (lc < 1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\tlc too small, cannot push again" << std::endl;
#endif
            undoAndRemoveChildren(midChildren_);
            returnOriginal();
            undoAndRemoveChildren(preChildren_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            recurseCounter_--;
#endif
            return false;
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\trmlc problem: " <<rmlc
                  << "ddgec: " << ddgEC << std::endl;
        TCEString dotName("rm_-1_pushup");
        dotName << mn_.nodeID() << "_" << ii() << "_" << dotCount++ << ".dot";
        std::cerr << "Writing dot: " << dotName << std::endl;
        ddg().writeToDotFile(dotName);
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tRM lc -1 when pushing move up, failing:"
                  << mn_.toString() << " target cycle: " << lc_ << std::endl;
        for (int i = 0; i < recurseCounter_*2; i++)
            std::cerr << "\t";
        std::cerr << "\t\tddgLC is: " << ddgLC << std::endl;
//        assert(false);
        std::cerr << "Trying to push preds one more up." << std::endl;
#endif
        BFPushDepsUp* pusher2 = new BFPushDepsUp(sched_, mn_, lc-1);
        bool fail = false;
        if ((*pusher2)()) {
            midChildren_.push(pusher2);
            ddgEC = ddg().earliestCycle(mn_, ii());
            if (ddgEC > lc) {
                std::cerr << "\t\tDDG earliest cycle STILL too early: "
                          << ddgEC << std::endl;
                ddg().writeToDotFile("ec_still_early.dot");
                assert(false);
            }
            ddgLC = ddg().latestCycle(mn_,ii());
            rmlc = rmLC(std::min(lc_, ddgLC), mn_);
            if (rmlc == -1 || rmlc < ddgEC) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "still failing, now giving up" << std::endl;
#endif
                fail = true;
            }
        } else {
            delete pusher2;
            fail = true;
        }
        if (fail) {
            for (int i = 0; i < recurseCounter_*2; i++)
                std::cerr << "\t";
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\tUndoing recursive pushs of predecessors"
                      << std::endl;
#endif
            undoAndRemoveChildren(midChildren_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            for (int i = 0; i < recurseCounter_*2; i++)
                std::cerr << "\t";
            std::cerr << "\t\tReturning the original" << std::endl;
#endif
            BFRescheduleMove::returnOriginal();
            undoAndRemoveChildren(preChildren_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            for (int i = 0; i < recurseCounter_*2; i++)
                std::cerr << "\t";
            std::cerr << "\t\treturned original: "<<mn_.toString()
                      << std::endl;
            recurseCounter_--;
#endif
            return false;
        }
    }
    assign(rmlc, mn_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    for (int i = 0; i < recurseCounter_*2; i++)
        std::cerr << "\t";
    std::cerr << "\tPushed move successfully: " << mn_.toString()
              << std::endl;
    recurseCounter_--;
#endif
    return true;
}
References assert, BFOptimization::assign(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), MoveNode::destinationOperation(), DataDependenceGraph::earliestCycle(), BF2Scheduler::guardWriteNode(), BFOptimization::ii(), ProgramOperation::inputMove(), ProgramOperation::inputMoveCount(), TTAProgram::Move::isControlFlowMove(), MoveNode::isDestinationOperation(), MoveNode::isScheduled(), TTAProgram::Terminal::isTriggering(), DataDependenceGraph::latestCycle(), lc_, BFRescheduleMove::midChildren_, BFUnscheduleMove::mn_, MoveNode::move(), GraphNode::nodeID(), Reversible::preChildren_, BFUnscheduleMove::recurseCounter_, BFUnscheduleMove::returnOriginal(), BFOptimization::rmLC(), Reversible::runPreChild(), BFOptimization::sched_, MoveNode::toString(), Reversible::undoAndRemoveChildren(), BFUnscheduleMove::unscheduleOriginal(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Member Data Documentation
lc_
int BFPushMoveUp::lc_ private
Definition at line 55 of file BFPushMoveUp.hh.
Referenced by operator()().
The documentation for this class was generated from the following files:
BFPushMoveUp.hh
BFPushMoveUp.cc