OpenASIP: ControlFlowEdge Class Reference
ControlFlowEdge Class Reference
#include <ControlFlowEdge.hh>
Public Types
enum CFGEdgePredicate {
CFLOW_EDGE_NORMAL , CFLOW_EDGE_TRUE , CFLOW_EDGE_FALSE , CFLOW_EDGE_LOOP_BREAK ,
CFLOW_EDGE_FAKE
}
enum CFGEdgeType { CFLOW_EDGE_JUMP , CFLOW_EDGE_CALL , CFLOW_EDGE_FALLTHROUGH }
Public Member Functions
ControlFlowEdge (CFGEdgePredicate edgePredicate=CFLOW_EDGE_NORMAL, CFGEdgeType edgeType=CFLOW_EDGE_JUMP)
virtual ~ControlFlowEdge ()
bool isControlFlowEdge () const
bool isNormalEdge () const
bool isTrueEdge () const
bool isFalseEdge () const
bool isCallPassEdge () const
bool isJumpEdge () const
bool isFallThroughEdge () const
bool isLoopBreakEdge () const
bool isBackEdge () const
TCEString toString () const
void setPredicate (CFGEdgePredicate pred)
CFGEdgePredicate edgePredicate () const
CFGEdgeType edgeType ()
void setBackEdge ()
Add property to edge to mark is as back edge - loop edge DO NOT USE unless you know what you are doing!!!
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual GraphEdge * clone () const
virtual ~GraphEdge ()
virtual int edgeID () const
virtual TCEString dotString () const
int weight () const
void setWeight (int w)
Static Public Member Functions
static ControlFlowEdge::CFGEdgePredicate edgePredicateFromMove (const TTAProgram::Move &move)
Private Attributes
CFGEdgePredicate edgePredicate_
CFGEdgeType edgeType_
bool backEdge_
Detailed Description
Edge of the control flow graph (control flow edge). Each edge implies a possible change of execution flow from the source basic block to the target basic block.
Definition at line 50 of file ControlFlowEdge.hh.
Member Enumeration Documentation
CFGEdgePredicate
enum ControlFlowEdge::CFGEdgePredicate
Enumerator
CFLOW_EDGE_NORMAL
CFLOW_EDGE_TRUE
CFLOW_EDGE_FALSE
CFLOW_EDGE_LOOP_BREAK
CFLOW_EDGE_FAKE
Definition at line 52 of file ControlFlowEdge.hh.
{
        CFLOW_EDGE_NORMAL,
        CFLOW_EDGE_TRUE,
        CFLOW_EDGE_FALSE,
        CFLOW_EDGE_LOOP_BREAK,
        CFLOW_EDGE_FAKE
    };
CFGEdgeType
enum ControlFlowEdge::CFGEdgeType
Enumerator
CFLOW_EDGE_JUMP
CFLOW_EDGE_CALL
CFLOW_EDGE_FALLTHROUGH
Definition at line 59 of file ControlFlowEdge.hh.
                     {
        CFLOW_EDGE_JUMP,
        CFLOW_EDGE_CALL,
        CFLOW_EDGE_FALLTHROUGH
    };
Constructor & Destructor Documentation
ControlFlowEdge()
ControlFlowEdge::ControlFlowEdge (CFGEdgePredicate edgePredicate = CFLOW_EDGE_NORMAL, CFGEdgeType edgeType = CFLOW_EDGE_JUMP)
Constructor creates Control Flow Edge of given type
Parameters
edgePredicate The truth value of edge (or normal)
edgeType Define if edge represents jump, if false the it is call
Definition at line 47 of file ControlFlowEdge.cc.
                          :
    edgePredicate_(edgePredicate), edgeType_(edgeType), backEdge_(false) {
}
~ControlFlowEdge()
ControlFlowEdge::~ControlFlowEdge () virtual
Destructor
Definition at line 56 of file ControlFlowEdge.cc.
{ }
Member Function Documentation
edgePredicate()
CFGEdgePredicate ControlFlowEdge::edgePredicate () const inline
Definition at line 83 of file ControlFlowEdge.hh.
{ return edgePredicate_; }
References edgePredicate_.
Referenced by ControlFlowGraph::copyToProcedure(), SimpleIfConverter::detectDiamond(), ControlFlowGraph::findJumpAddress(), LoopPrologAndEpilogBuilder::moveJumpDestination(), ControlFlowGraph::optimizeBBOrdering(), and CopyingDelaySlotFiller::updateFTBBAndCfg().
edgePredicateFromMove()
ControlFlowEdge::CFGEdgePredicate ControlFlowEdge::edgePredicateFromMove (const TTAProgram::Move & move) static
Creates an edge predicate based on the guard of a move
Definition at line 187 of file ControlFlowEdge.cc.
{
    if (move.isUnconditional()) {
        if (move.isTriggering()) {
            Operation& o = move.destination().operation();
            if (o.name() == "BNZ" || o.name() == "IRFJUMPNZ" ||
                o.name() == "BNZ1" || o.name() == "IRFJUMPNZ1") {
                return ControlFlowEdge::CFLOW_EDGE_TRUE;
            }
            if (o.name() == "BZ" || o.name() == "IRFJUMPZ" ||
                o.name() == "BZ1" || o.name() == "IRFJUMPZ1") {
                return ControlFlowEdge::CFLOW_EDGE_FALSE;
            }
        } else {
            Operation& o = move.destination().hintOperation();
            if (&o != &NullOperation::instance()) {
                if (o.name() == "BNZ" || o.name() == "IRFJUMPNZ" ||
                    o.name() == "BNZ1" || o.name() == "IRFJUMPNZ1") {
                    return ControlFlowEdge::CFLOW_EDGE_TRUE;
                }
                if (o.name() == "BZ" || o.name() == "IRFJUMPZ" ||
                    o.name() == "BZ1" || o.name() == "IRFJUMPZ1") {
                    return ControlFlowEdge::CFLOW_EDGE_FALSE;
                }
            }
        }
        return ControlFlowEdge::CFLOW_EDGE_NORMAL;
    }
    TTAProgram::MoveGuard& mg = move.guard();
    return mg.isInverted() ?
        ControlFlowEdge::CFLOW_EDGE_FALSE :
        ControlFlowEdge::CFLOW_EDGE_TRUE;
}
References CFLOW_EDGE_FALSE, CFLOW_EDGE_NORMAL, CFLOW_EDGE_TRUE, TTAProgram::Move::destination(), TTAProgram::Move::guard(), TTAProgram::Terminal::hintOperation(), NullOperation::instance(), TTAProgram::MoveGuard::isInverted(), TTAProgram::Move::isTriggering(), TTAProgram::Move::isUnconditional(), Operation::name(), and TTAProgram::Terminal::operation().
Referenced by ControlFlowGraph::findJumpAddress().
edgeType()
CFGEdgeType ControlFlowEdge::edgeType () inline
Definition at line 84 of file ControlFlowEdge.hh.
{ return edgeType_; }
References edgeType_.
Referenced by SimpleIfConverter::detectDiamond(), and CopyingDelaySlotFiller::updateFTBBAndCfg().
isBackEdge()
bool ControlFlowEdge::isBackEdge () const virtual
Returns true if edge is loop back edge
Returns
True if edge is loop back edge
Reimplemented from GraphEdge.
Definition at line 179 of file ControlFlowEdge.cc.
{
    return backEdge_;
}
References backEdge_.
Referenced by CopyingDelaySlotFiller::collectMoves(), SimpleIfConverter::detectDiamond(), SimpleIfConverter::detectTriangleViaFt(), SimpleIfConverter::detectTriangleViaJump(), CopyingDelaySlotFiller::fillDelaySlots(), ControlFlowGraph::isSingleBBLoop(), ControlFlowGraph::optimizeBBOrdering(), toString(), and SimpleIfConverter::updateCfg().
isCallPassEdge()
bool ControlFlowEdge::isCallPassEdge () const
Returns true if edge represents control flow over the call in code.
Returns
True if edge is split in basic block when call happened.
Definition at line 138 of file ControlFlowEdge.cc.
{
    return edgeType_ == CFLOW_EDGE_CALL;
}
References CFLOW_EDGE_CALL, and edgeType_.
Referenced by CopyingDelaySlotFiller::bbnScheduled(), SimpleIfConverter::detectDiamond(), SimpleIfConverter::detectTriangleViaFt(), CopyingDelaySlotFiller::fillDelaySlots(), CopyingDelaySlotFiller::finishBB(), ControlFlowGraph::optimizeBBOrdering(), and toString().
isControlFlowEdge()
bool ControlFlowEdge::isControlFlowEdge () const
Returns true if object represents ControlFlowEdge.
Returns
True if object is control flow edge
Definition at line 99 of file ControlFlowEdge.cc.
{
    return true;
}
isFallThroughEdge()
bool ControlFlowEdge::isFallThroughEdge () const
Returns true if the edge is representing fall through.
Returns
True if the edge represents fall through.
Definition at line 158 of file ControlFlowEdge.cc.
{
    return edgeType_ == CFLOW_EDGE_FALLTHROUGH;
}
References CFLOW_EDGE_FALLTHROUGH, and edgeType_.
Referenced by LoopPrologAndEpilogBuilder::addEpilogIntoCfg(), CopyingDelaySlotFiller::fillDelaySlots(), Peel2BBLoops::testIf2BBLoop(), and toString().
isFalseEdge()
bool ControlFlowEdge::isFalseEdge () const
Returns true if edge represents conditional control flow that is taken if condition evaluates to false.
Returns
True if edge represents False path
Definition at line 129 of file ControlFlowEdge.cc.
{
    return edgePredicate_ == CFLOW_EDGE_FALSE;
}
References CFLOW_EDGE_FALSE, and edgePredicate_.
Referenced by PreOptimizer::cfgAllowsJumpReversal(), ControlFlowGraph::reverseGuardOnOutEdges(), and toString().
isJumpEdge()
bool ControlFlowEdge::isJumpEdge () const
Returns true if the edge is representing jump.
Returns
True if the edge represents jump.
Definition at line 148 of file ControlFlowEdge.cc.
{
    return edgeType_ == CFLOW_EDGE_JUMP;
}
References CFLOW_EDGE_JUMP, and edgeType_.
Referenced by LoopPrologAndEpilogBuilder::addPrologIntoCfg(), CopyingDelaySlotFiller::areAllJumpPredsFilled(), CopyingDelaySlotFiller::areAllJumpPredsScheduled(), ControlFlowGraph::isSingleBBLoop(), ControlFlowGraph::jumpSuccessor(), and toString().
isLoopBreakEdge()
bool ControlFlowEdge::isLoopBreakEdge () const
Returns true if edge was added to break infinite loop for control dependence computation.
Returns
True if edge was added to break infinite loop
Definition at line 169 of file ControlFlowEdge.cc.
{
    return edgePredicate_ == CFLOW_EDGE_LOOP_BREAK;
}
References CFLOW_EDGE_LOOP_BREAK, and edgePredicate_.
Referenced by toString().
isNormalEdge()
bool ControlFlowEdge::isNormalEdge () const
Returns true if the edge is representing unconditional jump
Returns
True if jump is not guarded
Definition at line 108 of file ControlFlowEdge.cc.
{
    return edgePredicate_ == CFLOW_EDGE_NORMAL;
}
References CFLOW_EDGE_NORMAL, and edgePredicate_.
Referenced by ControlFlowGraph::hasMultipleUnconditionalSuccessors(), ControlFlowGraph::mergeNodes(), and toString().
isTrueEdge()
bool ControlFlowEdge::isTrueEdge () const
Returns true if edge represents conditional control flow that is taken if condition evaluates to true.
Returns
True if edge represents True path
Definition at line 119 of file ControlFlowEdge.cc.
{
    return edgePredicate_ == CFLOW_EDGE_TRUE;
}
References CFLOW_EDGE_TRUE, and edgePredicate_.
Referenced by PreOptimizer::cfgAllowsJumpReversal(), ControlFlowGraph::reverseGuardOnOutEdges(), SimpleIfConverter::successors(), and toString().
setBackEdge()
void ControlFlowEdge::setBackEdge () inline
Add property to edge to mark is as back edge - loop edge DO NOT USE unless you know what you are doing!!!
Definition at line 88 of file ControlFlowEdge.hh.
{ backEdge_ = true;}
References backEdge_.
Referenced by SimpleIfConverter::updateCfg().
setPredicate()
void ControlFlowEdge::setPredicate (CFGEdgePredicate pred) inline
Definition at line 81 of file ControlFlowEdge.hh.
{ edgePredicate_ = pred; }
References edgePredicate_.
Referenced by ControlFlowGraph::mergeNodes(), and ControlFlowGraph::reverseGuardOnOutEdges().
toString()
TCEString ControlFlowEdge::toString () const virtual
Returns type as a string. Helper for graph output to dot file.
Returns
String representing type of edge.
Reimplemented from GraphEdge.
Definition at line 64 of file ControlFlowEdge.cc.
{
    TCEString result = "";
    if (isJumpEdge()) {
        result += "Jump_";
    }
    if (isFallThroughEdge()) {
        result += "FallThrough_";
    }
    if (isCallPassEdge()) {
        result += "CallPass_";
    }
    if (isBackEdge()) {
        result += "BackEdge_";
    }
    if (isNormalEdge()) {
        result += "normal";
    }
    if (isTrueEdge()) {
        result += "true";
    }
    if (isFalseEdge()) {
        result += "false";
    }
    if (isLoopBreakEdge()) {
        result += "break";
    }
    return result;
}
References isBackEdge(), isCallPassEdge(), isFallThroughEdge(), isFalseEdge(), isJumpEdge(), isLoopBreakEdge(), isNormalEdge(), and isTrueEdge().
Referenced by ControlFlowGraph::reverseGuardOnOutEdges().
Member Data Documentation
backEdge_
bool ControlFlowEdge::backEdge_ private
Definition at line 96 of file ControlFlowEdge.hh.
Referenced by isBackEdge(), and setBackEdge().
edgePredicate_
CFGEdgePredicate ControlFlowEdge::edgePredicate_ private
Definition at line 94 of file ControlFlowEdge.hh.
Referenced by edgePredicate(), isFalseEdge(), isLoopBreakEdge(), isNormalEdge(), isTrueEdge(), and setPredicate().
edgeType_
CFGEdgeType ControlFlowEdge::edgeType_ private
Definition at line 95 of file ControlFlowEdge.hh.
Referenced by edgeType(), isCallPassEdge(), isFallThroughEdge(), and isJumpEdge().
The documentation for this class was generated from the following files:
ControlFlowEdge.hh
ControlFlowEdge.cc