OpenASIP: DEFAULT_Compressor Class Reference
DEFAULT_Compressor Class Reference
#include <DefaultCompressor.hh>
Public Member Functions
DEFAULT_Compressor ()
virtual InstructionBitVector * compress (const std::string &programName)
virtual void printDescription (std::ostream &stream)
virtual void generateDecompressor (std::ostream &, TCEString)
Public Member Functions inherited from CodeCompressorPlugin
virtual ~CodeCompressorPlugin ()
void setParameters (ParameterTable parameters)
void setPrograms (std::map< std::string, TPEF::Binary * > &programs)
void setMachine (const TTAMachine::Machine &machine)
void setBEM (const BinaryEncoding &bem)
const BinaryEncoding & binaryEncoding () const
const TTAMachine::Machine & machine () const
unsigned int memoryAddress (const TTAProgram::Instruction &instruction) const
TTAProgram::Program & currentProgram () const
int imemMauWidth () const
InstructionBitVector * bemInstructionBits (const TTAProgram::Instruction &)
Additional Inherited Members
Public Types inherited from CodeCompressorPlugin
typedef std::vector< Parameter > ParameterTable
Table for passing plugin parameters.
Protected Types inherited from CodeCompressorPlugin
typedef std::map< std::string, TPEF::Binary * > TPEFMap
Map type for handling programs.
Protected Member Functions inherited from CodeCompressorPlugin
CodeCompressorPlugin ()
InstructionBitVector * bemBits (const TTAProgram::Program &program)
int moveSlotCount () const
int moveSlotWidth (int index) const
int firstMoveSlotIndex () const
void startNewProgram (const std::string &programName)
void addInstruction (const TTAProgram::Instruction &instruction, InstructionBitVector *bits)
void setInstructionToStartAtBeginningOfMAU (const TTAProgram::Instruction &instruction)
void setAllInstructionsToStartAtBeginningOfMAU ()
InstructionBitVector * programBits () const
bool hasParameter (const std::string &paramName) const
std::string parameterValue (const std::string &paramName) const
void setImemWidth (int mau, int widthInMaus=1)
int numberOfPrograms () const
TPEFMap::const_iterator programElement (int index) const
std::string indentation (int level)
Detailed Description
Definition at line 41 of file DefaultCompressor.hh.
Constructor & Destructor Documentation
DEFAULT_Compressor()
DEFAULT_Compressor::DEFAULT_Compressor () inline
Definition at line 43 of file DefaultCompressor.hh.
: CodeCompressorPlugin() {}
Member Function Documentation
compress()
virtual InstructionBitVector * DEFAULT_Compressor::compress (const std::string & program) inline virtual
Generates bit image of the program.
Returns
The bit image.
Exceptions
InvalidData If the BEM is erroneous.
Implements CodeCompressorPlugin.
Definition at line 46 of file DefaultCompressor.hh.
{
        try {
            startNewProgram(programName);
            setAllInstructionsToStartAtBeginningOfMAU();
            Instruction* instruction = &currentProgram().firstInstruction();
            while (instruction != &NullInstruction::instance()) {
                InstructionBitVector* instructionBits = bemInstructionBits(
                    *instruction);
                addInstruction(*instruction, instructionBits);
                instruction =
                    &currentProgram().nextInstruction(*instruction);
            }
            return programBits();
        } catch (const Exception& e) {
            throw InvalidData(
                __FILE__, __LINE__, __func__, e.errorMessage());
        }
    }
References __func__, CodeCompressorPlugin::addInstruction(), CodeCompressorPlugin::bemInstructionBits(), CodeCompressorPlugin::currentProgram(), Exception::errorMessage(), TTAProgram::Program::firstInstruction(), TTAProgram::Program::nextInstruction(), CodeCompressorPlugin::programBits(), CodeCompressorPlugin::setAllInstructionsToStartAtBeginningOfMAU(), and CodeCompressorPlugin::startNewProgram().
generateDecompressor()
virtual void DEFAULT_Compressor::generateDecompressor (std::ostream & stream, TCEString entityStr) inline virtual
Generates the HDL code of the decompressor block.
Parameters
stream The stream to write.
Implements CodeCompressorPlugin.
Definition at line 72 of file DefaultCompressor.hh.
{}
printDescription()
virtual void DEFAULT_Compressor::printDescription (std::ostream & stream) inline virtual
Prints description of the plugin to the given stream.
Implements CodeCompressorPlugin.
Definition at line 67 of file DefaultCompressor.hh.
{
        stream << "Does not compress instructions at all." << std::endl;
    }
The documentation for this class was generated from the following file:
DefaultCompressor.hh