OpenASIP: EditOTAFormatsCmd Class Reference
EditOTAFormatsCmd Class Reference
#include <EditOTAFormatsCmd.hh>
Public Member Functions
EditOTAFormatsCmd ()
virtual ~EditOTAFormatsCmd ()
virtual bool Do ()
virtual int id () const
virtual EditOTAFormatsCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for editing OTAFormats.
Opens a OTAFormatListDialog which lists OTAFormats in the machine.
Definition at line 43 of file EditOTAFormatsCmd.hh.
Constructor & Destructor Documentation
EditOTAFormatsCmd()
EditOTAFormatsCmd::EditOTAFormatsCmd ()
The Constructor.
Definition at line 51 of file EditOTAFormatsCmd.cc.
    : EditorCommand(ProDeConstants::CMD_NAME_EDIT_OTA_FORMATS) {}
Referenced by create().
~EditOTAFormatsCmd()
EditOTAFormatsCmd::~EditOTAFormatsCmd () virtual
The Destructor.
Definition at line 57 of file EditOTAFormatsCmd.cc.
{}
Member Function Documentation
create()
EditOTAFormatsCmd * EditOTAFormatsCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
A new instance of this command.
Implements GUICommand.
Definition at line 102 of file EditOTAFormatsCmd.cc.
{
    return new EditOTAFormatsCmd();
}
References EditOTAFormatsCmd().
Do()
bool EditOTAFormatsCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 65 of file EditOTAFormatsCmd.cc.
                      {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model =
        dynamic_cast<MDFDocument*>(view()->GetDocument())->getModel();
    model->pushToStack();
    OTAFormatListDialog dialog(parentWindow(), model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
        model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, templates are not modified.
        model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
string EditOTAFormatsCmd::icon () const virtual
Returns path to the command's icon file.
Returns
path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 112 of file EditOTAFormatsCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_OTA_FORMATS;
}
References ProDeConstants::CMD_ICON_EDIT_OTA_FORMATS.
id()
int EditOTAFormatsCmd::id () const virtual
Returns id of this command.
Returns
Id of this command.
Implements GUICommand.
Definition at line 92 of file EditOTAFormatsCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_OTA_FORMATS;
}
References ProDeConstants::COMMAND_EDIT_OTA_FORMATS.
isEnabled()
bool EditOTAFormatsCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 134 of file EditOTAFormatsCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string EditOTAFormatsCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short version of the command name.
Reimplemented from GUICommand.
Definition at line 122 of file EditOTAFormatsCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_OTA_FORMATS;
}
References ProDeConstants::CMD_SNAME_EDIT_OTA_FORMATS.
The documentation for this class was generated from the following files:
EditOTAFormatsCmd.hh
EditOTAFormatsCmd.cc