OpenASIP: DisasmExecCountFrame Class Reference
DisasmExecCountFrame Class Reference
#include <DisasmTopCountAttrProvider.hh>
Public Member Functions
DisasmExecCountFrame (wxWindow *parent, wxWindowID id, const DisasmTopCountAttrProvider::ExecutionCountTable &table)
virtual ~DisasmExecCountFrame ()
void update ()
void addExecCount (unsigned execCount, unsigned start, unsigned end, const wxColour &colour)
Private Member Functions
void onClose (wxCloseEvent &event)
void onSelection (wxListEvent &event)
Private Attributes
wxListCtrl * list_
const DisasmTopCountAttrProvider::ExecutionCountTable & topCountTable_
Detailed Description
Simple list window for displaying list of top execution counts.
Definition at line 85 of file DisasmTopCountAttrProvider.hh.
Constructor & Destructor Documentation
DisasmExecCountFrame()
DisasmExecCountFrame::DisasmExecCountFrame (wxWindow * parent, wxWindowID id, const DisasmTopCountAttrProvider::ExecutionCountTable & topCountTable)
The Constructor.
Parameters
parent Parent window of the miniframe.
id Window identifier for the frame.
topCountTable Table of top execution counts to display.
Definition at line 60 of file DisasmTopCountAttrProvider.cc.
                                                                        :
    wxMiniFrame(parent, id, _T("Top Execution Counts")),
    topCountTable_(topCountTable) {
    wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    list_ = new wxListCtrl(
        this, -1, wxDefaultPosition, wxDefaultSize,
        wxLC_REPORT | wxLC_SINGLE_SEL);
    list_->InsertColumn(0, _T("Exec Count"), wxLIST_FORMAT_LEFT, 100);
    list_->InsertColumn(1, _T("Address range"), wxLIST_FORMAT_LEFT, 200);
    sizer->Add(list_, 1, wxEXPAND|wxALL, 5);
    SetSizer(sizer);
}
~DisasmExecCountFrame()
DisasmExecCountFrame::~DisasmExecCountFrame () virtual
The Destructor.
Definition at line 80 of file DisasmTopCountAttrProvider.cc.
{
}
Member Function Documentation
addExecCount()
void DisasmExecCountFrame::addExecCount (unsigned execCount, unsigned start, unsigned end, const wxColour & colour)
onClose()
void DisasmExecCountFrame::onClose (wxCloseEvent & event) private
onSelection()
void DisasmExecCountFrame::onSelection (wxListEvent & event) private
Event handler for the execution count list selection events.
Selects and shows the start address of the selected range in the disassembly winow.
Parameters
event Selection event to handle.
Definition at line 156 of file DisasmTopCountAttrProvider.cc.
{
    unsigned addr = list_->GetItemData(event.GetIndex());
    ProximDisassemblyWindow& disasmwin = *ProximToolbox::disassemblyWindow();
    disasmwin.showAddress(addr);
}
References ProximToolbox::disassemblyWindow(), list_, and ProximDisassemblyWindow::showAddress().
update()
void DisasmExecCountFrame::update ()
Updates the execution count list.
Definition at line 87 of file DisasmTopCountAttrProvider.cc.
{
    list_->DeleteAllItems();
    DisasmTopCountAttrProvider::ExecutionCountTable::const_iterator iter =
        topCountTable_.begin();
    int pos = topCountTable_.size();
    // Iterate through all entries in the topcount table.
    for (; iter != topCountTable_.end(); iter++) {
        pos--;
        unsigned count = (*iter).first;
        const DisasmTopCountAttrProvider::AddressSet addressSet =
            (*iter).second;
        DisasmTopCountAttrProvider::AddressSet::const_iterator citer =
            addressSet.begin();
        // Iterate through all addresses with the same execution count and
        // combine consecutive addresses to address ranges.
        while (citer != addressSet.end()) {
            unsigned rangeFirst = *citer;
            unsigned rangeLast = *citer;
            while (citer != addressSet.end() && (*citer == rangeLast)) {
                citer++;
                rangeLast++;
            }
            rangeLast--;
            // Add list entry for the address range.
            wxString range = WxConversion::toWxString(rangeFirst);
            if (rangeFirst != rangeLast) {
                range.Append(_T(" - "));
                range.Append(WxConversion::toWxString(rangeLast));
            }
            list_->InsertItem(0, WxConversion::toWxString(count));
            list_->SetItem(0, 1, range);
            list_->SetItemData(0, rangeFirst);
            // Set background color for the list item.
            // TODO: more elegant solution :)
            if (pos < 5) {
                list_->SetItemBackgroundColour(
                    0,  wxColour(255 , pos * 50, 0));
            } else {
                list_->SetItemBackgroundColour(
                    0, wxColour(255 - (2 * (pos * 25 - 128)), 255, 0));
            }
            if (citer != addressSet.end()) {
                citer++;
            }
        }
    }
}
References list_, topCountTable_, and WxConversion::toWxString().
Referenced by DisasmTopCountAttrProvider::update().
Member Data Documentation
list_
wxListCtrl* DisasmExecCountFrame::list_ private
Definition at line 100 of file DisasmTopCountAttrProvider.hh.
Referenced by onSelection(), and update().
topCountTable_
const DisasmTopCountAttrProvider::ExecutionCountTable& DisasmExecCountFrame::topCountTable_ private
Definition at line 101 of file DisasmTopCountAttrProvider.hh.
Referenced by update().
The documentation for this class was generated from the following files:
DisasmTopCountAttrProvider.hh
DisasmTopCountAttrProvider.cc