OpenASIP: ImplementationSelector Class Reference
ImplementationSelector Class Reference
Private Member Functions
PLUGIN_DESCRIPTION ("Creates implementation for the given machine.")
ImplementationSelector ()
virtual bool requiresStartingPointArchitecture () const
virtual bool producesArchitecture () const
virtual bool requiresHDB () const
virtual bool requiresSimulationData () const
virtual bool requiresApplication () const
virtual std::vector< RowID > explore (const RowID &configurationID, const unsigned int &)
void readParameters ()
void setupSelector ()
Private Attributes
ComponentImplementationSelector selector_
Selector used by the plugin.
std::string icDec_
name of the ic decoder plugin for idf
std::string icDecHDB_
name of the hdb used by ic decoder
std::string adf_
name of the adf file if wanted to use idf generation
Static Private Attributes
static const std::string icDecPN_
static const std::string icDecHDBPN_
static const std::string adfPN_
Additional Inherited Members
Public Types inherited from DesignSpaceExplorerPlugin
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions inherited from DesignSpaceExplorerPlugin
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorerPlugin
DesignSpaceExplorerPlugin ()
void checkParameters () const
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Protected Attributes inherited from DesignSpaceExplorerPlugin
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
Detailed Description
Explorer plugin that selects implementations for units in a given adf. Creates a new config with a idf.
Supported parameters:
ic_dec, name of the ic decoder plugin, default is DefaultICDecoder
ic_hdb, name of the HDB that is used in IC estimation, default is asic_130nm_1.5V.hdb
adf, if idf is wanted to generated to some arhitecture, no default value. If adf parameter is given the idf is built.
Definition at line 78 of file ImplementationSelector.cc.
Constructor & Destructor Documentation
ImplementationSelector()
ImplementationSelector::ImplementationSelector () inline private
Definition at line 81 of file ImplementationSelector.cc.
                            : DesignSpaceExplorerPlugin(),
        icDec_("DefaultICDecoder"),
        icDecHDB_("asic_130nm_1.5V.hdb"),
        adf_("") {
        // compulsory parameters
        // no compulsory parameters
        // parameters that have a default value
        addParameter(icDecPN_, STRING, false, icDec_);
        addParameter(icDecHDBPN_, STRING, false, icDecHDB_);
        addParameter(adfPN_, STRING, false, adf_);
    }
References DesignSpaceExplorerPlugin::addParameter(), adf_, adfPN_, icDec_, icDecHDB_, icDecHDBPN_, icDecPN_, and STRING.
Member Function Documentation
explore()
virtual std::vector< RowID > ImplementationSelector::explore (const RowID & startPointConfigurationID, const unsigned int & maxIter) inline private virtual
Explores the design space from the starting point machine and returns best exploring results as configuration IDs.
Exploring creates new machine configurations (architecture, implementation) that are ordered so that the best results are first in the result vector.
Parameters
startPoint Starting point machine configuration for the plugin.
maxIter Maximum number of design space points the plugin is allowed to explore. Default value for maxIter is zero when the iteration number is not taken into account. In that case the exploration runs indefinetly or stops at a point defined by the algorithm.
Returns
Ordered vector of IDs of the best machine configurations where the target programs can be successfully run. The IDs of the best machine configurations are first in the result vector. Returns an empty vector if does not find any possible machine configurations.
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 104 of file ImplementationSelector.cc.
{
        readParameters();
        setupSelector();
        std::vector<RowID> result;
        // check if adf given
        if (configurationID == 0 && adf_ == "") {
            std::ostringstream msg(std::ostringstream::out);
            msg << "No configuration nor adf defined. Use -s <confID> to "
                << "define the configuration to be optimized or give adf "
                << "as plugin parameter." << endl;
            verboseLog(msg.str());
            return result;
        }
        DSDBManager& dsdb = db();
        DSDBManager::MachineConfiguration conf;
        conf.hasImplementation = false;
        TTAMachine::Machine* mach = NULL;
        // load the adf from file or from dsdb
        try {
            if (adf_ != "") {
                mach = TTAMachine::Machine::loadFromADF(adf_);
            } else {
                conf = dsdb.configuration(configurationID);
                mach = dsdb.architecture(conf.architectureID);
            }
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error loading the adf." << std::endl;
            verboseLog(msg.str());
            return result;
        }
        IDF::MachineImplementation* idf = NULL;
        try {
            // building the idf
            idf = selector_.selectComponents(mach, icDec_, icDecHDB_);
        } catch (const Exception& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << e.errorMessage()
                << " " << e.fileName()
                << " " << e.lineNum() << std::endl;
            verboseLog(msg.str());
            return result;
        }
        // create a new configuration
        try {
            conf.architectureID = dsdb.addArchitecture(*mach);
        } catch (const RelationalDBException& e) {
            std::ostringstream msg(std::ostringstream::out);
            msg << "Error while adding ADF to the dsdb. "
                << "ADF probably too big." << endl;
            verboseLog(msg.str());
            return result;
        }
        conf.implementationID = dsdb.addImplementation(*idf, 0, 0);
        conf.hasImplementation = true;
        RowID confID = dsdb.addConfiguration(conf);
        result.push_back(confID);
        return result;
    }
References DSDBManager::addArchitecture(), DSDBManager::addConfiguration(), DSDBManager::addImplementation(), adf_, DSDBManager::architecture(), DSDBManager::MachineConfiguration::architectureID, DSDBManager::configuration(), DesignSpaceExplorer::db(), Exception::errorMessage(), Exception::fileName(), DSDBManager::MachineConfiguration::hasImplementation, icDec_, icDecHDB_, DSDBManager::MachineConfiguration::implementationID, Exception::lineNum(), TTAMachine::Machine::loadFromADF(), readParameters(), ComponentImplementationSelector::selectComponents(), selector_, setupSelector(), and verboseLog.
PLUGIN_DESCRIPTION()
ImplementationSelector::PLUGIN_DESCRIPTION ("Creates implementation for the given machine.") private
producesArchitecture()
virtual bool ImplementationSelector::producesArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 96 of file ImplementationSelector.cc.
{ return false; }
readParameters()
void ImplementationSelector::readParameters () inline private
Reads the parameters given to the plugin.
Definition at line 193 of file ImplementationSelector.cc.
{
        readOptionalParameter(icDecPN_, icDec_);
        readOptionalParameter(icDecHDBPN_, icDecHDB_);
        readOptionalParameter(adfPN_, adf_);
    }
References adf_, adfPN_, icDec_, icDecHDB_, icDecHDBPN_, icDecPN_, and DesignSpaceExplorerPlugin::readOptionalParameter().
Referenced by explore().
requiresApplication()
virtual bool ImplementationSelector::requiresApplication () const inline private virtual
Reimplemented from DesignSpaceExplorerPlugin.
Definition at line 99 of file ImplementationSelector.cc.
{ return false; }
requiresHDB()
virtual bool ImplementationSelector::requiresHDB () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 97 of file ImplementationSelector.cc.
{ return true; }
requiresSimulationData()
virtual bool ImplementationSelector::requiresSimulationData () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 98 of file ImplementationSelector.cc.
{ return false; }
requiresStartingPointArchitecture()
virtual bool ImplementationSelector::requiresStartingPointArchitecture () const inline private virtual
Implements DesignSpaceExplorerPlugin.
Definition at line 95 of file ImplementationSelector.cc.
{ return true; }
setupSelector()
void ImplementationSelector::setupSelector () inline private
Sets up the component implementation selector by adding the HDBs.
Definition at line 203 of file ImplementationSelector.cc.
{
        HDBRegistry& hdbRegistry = HDBRegistry::instance();
        // if HDBRegistry contains no HDBManagers load from default paths
        if (hdbRegistry.hdbCount() == 0) {
            hdbRegistry.loadFromSearchPaths();
        }
        // give all HDBs from registry to the selector to select from
        for (int i = 0; i < hdbRegistry.hdbCount(); i++) {
            HDBManager* hdb = &hdbRegistry.hdb(i);
            selector_.addHDB(*hdb);
        }
    }
References ComponentImplementationSelector::addHDB(), HDB::HDBRegistry::hdb(), HDB::HDBRegistry::hdbCount(), HDB::HDBRegistry::instance(), HDB::HDBRegistry::loadFromSearchPaths(), and selector_.
Referenced by explore().
Member Data Documentation
adf_
std::string ImplementationSelector::adf_ private
name of the adf file if wanted to use idf generation
Definition at line 187 of file ImplementationSelector.cc.
Referenced by explore(), ImplementationSelector(), and readParameters().
adfPN_
const std::string ImplementationSelector::adfPN_ static private
Definition at line 179 of file ImplementationSelector.cc.
Referenced by ImplementationSelector(), and readParameters().
icDec_
std::string ImplementationSelector::icDec_ private
name of the ic decoder plugin for idf
Definition at line 183 of file ImplementationSelector.cc.
Referenced by explore(), ImplementationSelector(), and readParameters().
icDecHDB_
std::string ImplementationSelector::icDecHDB_ private
name of the hdb used by ic decoder
Definition at line 185 of file ImplementationSelector.cc.
Referenced by explore(), ImplementationSelector(), and readParameters().
icDecHDBPN_
const std::string ImplementationSelector::icDecHDBPN_ static private
Definition at line 178 of file ImplementationSelector.cc.
Referenced by ImplementationSelector(), and readParameters().
icDecPN_
const std::string ImplementationSelector::icDecPN_ static private
Definition at line 177 of file ImplementationSelector.cc.
Referenced by ImplementationSelector(), and readParameters().
selector_
ComponentImplementationSelector ImplementationSelector::selector_ private
Selector used by the plugin.
Definition at line 174 of file ImplementationSelector.cc.
Referenced by explore(), and setupSelector().
The documentation for this class was generated from the following file:
ImplementationSelector.cc