OpenASIP: ProDeClipboard Class Reference
ProDeClipboard Class Reference
#include <ProDeClipboard.hh>
Public Member Functions
void setContents (ObjectState *contents, const TTAMachine::Machine *sourceMachine)
ObjectState * copyContents ()
const TTAMachine::Machine * sourceMachine ()
bool isEmpty ()
Static Public Member Functions
static ProDeClipboard * instance ()
static void destroy ()
Private Member Functions
ProDeClipboard ()
~ProDeClipboard ()
Private Attributes
ObjectState * contents_
const TTAMachine::Machine * sourceMachine_
Static Private Attributes
static ProDeClipboard * instance_ = NULL
Detailed Description
A Clipboard class for copying machine components in ProDe.
The clipboard can store one Component. This class is implemented using the 'singleton' design pattern.
Definition at line 47 of file ProDeClipboard.hh.
Constructor & Destructor Documentation
ProDeClipboard()
ProDeClipboard::ProDeClipboard () private
The Constructor.
Definition at line 41 of file ProDeClipboard.cc.
                               : contents_(NULL) {
}
Referenced by instance().
~ProDeClipboard()
ProDeClipboard::~ProDeClipboard () private
The Destructor.
Definition at line 48 of file ProDeClipboard.cc.
{
    if (contents_ != NULL) {
        delete contents_;
        contents_ = NULL;
    }
}
References contents_.
Member Function Documentation
copyContents()
ObjectState * ProDeClipboard::copyContents ()
Returns a copy of the clipboard contents.
Returns
Copy of the cliboard contents.
Definition at line 104 of file ProDeClipboard.cc.
{
    if (contents_ == NULL) {
        return NULL;
    }
    ObjectState* component = new ObjectState(*contents_);
    return component;
}
References contents_.
Referenced by PasteComponentCmd::Do().
destroy()
void ProDeClipboard::destroy () static
Deletes the singleton instance of the clipboard.
Definition at line 74 of file ProDeClipboard.cc.
{
    if (instance_ != NULL) {
        delete instance_;
        instance_ = NULL;
    }
}
References instance_.
Referenced by ProDe::OnExit().
instance()
ProDeClipboard * ProDeClipboard::instance () static
Returns the singleton instance of the clipboard.
Returns
Singleton instance of the clipboard.
Definition at line 62 of file ProDeClipboard.cc.
{
    if (instance_ == NULL) {
        instance_ = new ProDeClipboard();
    }
    return instance_;
}
References instance_, and ProDeClipboard().
Referenced by CopyComponent::Do(), PasteComponentCmd::Do(), and PasteComponentCmd::isEnabled().
isEmpty()
bool ProDeClipboard::isEmpty ()
Returns true if the clipboard is empty.
Returns
true, if the clipboard is empty.
Definition at line 121 of file ProDeClipboard.cc.
{
    if (contents_ == NULL) {
    return true;
    }
    return false;
}
References contents_.
Referenced by PasteComponentCmd::isEnabled().
setContents()
void ProDeClipboard::setContents (ObjectState * component, const TTAMachine::Machine * sourceMachine)
Sets the clipboard contents.
Parameters
component Copied/cut component.
Definition at line 88 of file ProDeClipboard.cc.
{
    if (contents_ != NULL) {
        delete contents_;
    }
    sourceMachine_ = sourceMachine;
    contents_ = component;
}
References contents_, sourceMachine(), and sourceMachine_.
Referenced by CopyComponent::Do().
sourceMachine()
const TTAMachine::Machine * ProDeClipboard::sourceMachine () inline
Definition at line 54 of file ProDeClipboard.hh.
{ return sourceMachine_; }
References sourceMachine_.
Referenced by PasteComponentCmd::Do(), and setContents().
Member Data Documentation
contents_
ObjectState* ProDeClipboard::contents_ private
Definition at line 62 of file ProDeClipboard.hh.
Referenced by copyContents(), isEmpty(), setContents(), and ~ProDeClipboard().
instance_
ProDeClipboard * ProDeClipboard::instance_ = NULL static private
Definition at line 61 of file ProDeClipboard.hh.
Referenced by destroy(), and instance().
sourceMachine_
const TTAMachine::Machine* ProDeClipboard::sourceMachine_ private
Definition at line 63 of file ProDeClipboard.hh.
Referenced by setContents(), and sourceMachine().
The documentation for this class was generated from the following files:
ProDeClipboard.hh
ProDeClipboard.cc