OpenASIP: TPEF::TPEFSymbolSectionReader Class Reference
TPEF::TPEFSymbolSectionReader Class Reference
#include <TPEFSymbolSectionReader.hh>
Protected Member Functions
TPEFSymbolSectionReader ()
virtual ~TPEFSymbolSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFSymbolSectionReader (const TPEFSymbolSectionReader &)
Copying not allowed.
TPEFSymbolSectionReader & operator= (TPEFSymbolSectionReader &)
Assignment not allowed.
SymbolElement * createSymbol (SymbolElement::SymbolType symType, Word aValue, Word aSize, SectionId sectToBelong) const
Static Private Attributes
static const Byte SYMBOL_TYPE_MASK = 0x0F
Mask for getting type of symbol from st_info field of symbol element.
static TPEFSymbolSectionReader proto_
Prototype instance of TPEFSymbolSectionReader to be registered to SectionReader.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads symbol section from TPEF binary file.
Definition at line 47 of file TPEFSymbolSectionReader.hh.
Constructor & Destructor Documentation
TPEFSymbolSectionReader() [1/2]
TPEF::TPEFSymbolSectionReader::TPEFSymbolSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 70 of file TPEFSymbolSectionReader.cc.
                                                 : TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFSymbolSectionReader()
TPEF::TPEFSymbolSectionReader::~TPEFSymbolSectionReader () protected virtual
Destructor.
Definition at line 77 of file TPEFSymbolSectionReader.cc.
{
}
TPEFSymbolSectionReader() [2/2]
TPEF::TPEFSymbolSectionReader::TPEFSymbolSectionReader (const TPEFSymbolSectionReader &) private
Copying not allowed.
Member Function Documentation
createSymbol()
SymbolElement * TPEF::TPEFSymbolSectionReader::createSymbol (SymbolElement::SymbolType symType, Word aValue, Word aSize, SectionId sectToBelong) const private
Creates symbol element.
Parameters
symType Type of symbol to create.
aValue Value of element.
aSize Size of element.
sectToBelong Identification code of the section that contains the element.
Returns
Newly created symbol.
Definition at line 203 of file TPEFSymbolSectionReader.cc.
{
    SymbolElement *elem = NULL;
    // NOTE: check symbols from latest spec and
    // add whole element reading stuff here.
    switch (symType) {
    case SymbolElement::STT_NOTYPE:
        elem = new NoTypeSymElement();
        break;
    case SymbolElement::STT_PROCEDURE:
        elem = new ProcedSymElement();
        /* fall through */
    case SymbolElement::STT_CODE:
        if (elem == NULL) {
            elem = new CodeSymElement();
        }
        if (sectToBelong != 0) {
            SectionOffsetKey sOffKey(sectToBelong, aValue);
            dynamic_cast<CodeSymElement*>
                (elem)->setReference(CREATE_SAFEPOINTER(sOffKey));
            dynamic_cast<CodeSymElement*>
                (elem)->setSize(aSize);
        }
        break;
    case SymbolElement::STT_DATA:
        elem = new DataSymElement();
        if (sectToBelong != 0) {
            SectionOffsetKey sOffKey(sectToBelong, aValue);
            dynamic_cast<DataSymElement*>
                (elem)->setReference(CREATE_SAFEPOINTER(sOffKey));
            dynamic_cast<DataSymElement*>
                (elem)->setSize(aSize);
        }
        break;
    case SymbolElement::STT_SECTION:
        elem = new SectionSymElement();
        dynamic_cast<SectionSymElement*>(elem)->setValue(aValue);
        dynamic_cast<SectionSymElement*>(elem)->setSize(aSize);
        break;
    case SymbolElement::STT_FILE:
        elem = new FileSymElement();
        dynamic_cast<FileSymElement*>(elem)->setValue(aValue);
        break;
    default:
        ;
    }
    return elem;
}
References TPEF::SymbolElement::STT_CODE, TPEF::SymbolElement::STT_DATA, TPEF::SymbolElement::STT_FILE, TPEF::SymbolElement::STT_NOTYPE, TPEF::SymbolElement::STT_PROCEDURE, and TPEF::SymbolElement::STT_SECTION.
Referenced by readData().
operator=()
TPEFSymbolSectionReader & TPEF::TPEFSymbolSectionReader::operator= (TPEFSymbolSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFSymbolSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read value were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 103 of file TPEFSymbolSectionReader.cc.
{
    // base classes implementation must be called with these.
    TPEFSectionReader::readData(stream, section);
    SymbolSection* symbolSection =
        dynamic_cast<SymbolSection*>(section);
    assert(symbolSection != NULL);
    // create indexs' starting from 0 undefined element is checked
    SectionIndex index = 0;
    bool undefSymbolDefined = false;
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // start of first element
        SectionOffset elementStart = header().bodyOffset;
        while (elementStart + header().elementSize <=
               header().bodyOffset + header().bodyLength) {
            SymbolElement *elem = NULL;
            Word nameOffset = stream.readWord();
            Word value = stream.readWord();
            Word size = stream.readWord();
            Byte info = stream.readByte();
            Byte otherField = stream.readByte();
            SectionId sectionToBelong = stream.readHalfWord();
            // lower half byte is type of symbol
            SymbolType typeOfSym =
                static_cast<SymbolType>(info & SYMBOL_TYPE_MASK);
            // upper half byte is binding
            SymbolBinding binding =
                static_cast<SymbolBinding>(info >> (BYTE_BITWIDTH / 2));
            // symbol of right type
            elem = createSymbol(typeOfSym, value, size, sectionToBelong);
            elem->setAbsolute(otherField & TPEFHeaders::STO_ABS);
            elem->setBinding(binding);
            SectionOffsetKey sOffKey(header().linkId, nameOffset);
            elem->setName(CREATE_SAFEPOINTER(sOffKey));
            // section which to symbol belongs
            SectionKey sKey(sectionToBelong);
            elem->setSection(CREATE_SAFEPOINTER(sKey));
            SectionIndexKey sectionIndexKey(header().sectionId, index);
            SafePointer::addObjectReference(sectionIndexKey, elem);
            // check undefined symbol
            if (index == 0) {
                assert(elem->type() == SymbolElement::STT_NOTYPE);
                assert(elem->binding() == SymbolElement::STB_LOCAL);
                assert(elem->absolute() == true);
                assert(nameOffset == 0);
                undefSymbolDefined = true;
            }
            section->addElement(elem);
            elementStart += header().elementSize;
            stream.setReadPosition(elementStart);
            index++;
        }
    }
    // create undefined symbol if not found from table
    // (e.g. if section had nobits flag set)
    if (!undefSymbolDefined) {
        NoTypeSymElement* elem = new NoTypeSymElement();
        elem->setBinding(SymbolElement::STB_LOCAL);
        elem->setAbsolute(true);
        SectionOffsetKey sOffKey(header().linkId, 0);
        elem->setName(CREATE_SAFEPOINTER(sOffKey));
        SectionIndexKey sectionIndexKey(header().sectionId, 0);
        SafePointer::addObjectReference(sectionIndexKey, elem);
        section->addElement(elem);
    }
}
References TPEF::SymbolElement::absolute(), TPEF::Section::addElement(), TPEF::ReferenceManager::SafePointer::addObjectReference(), assert, TPEF::SymbolElement::binding(), TPEF::TPEFSectionReader::Header::bodyOffset, BYTE_BITWIDTH, createSymbol(), TPEF::TPEFSectionReader::Header::elementSize, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::SymbolElement::setAbsolute(), TPEF::SymbolElement::setBinding(), TPEF::SymbolElement::setName(), TPEF::BinaryStream::setReadPosition(), TPEF::SymbolElement::setSection(), TPEF::SymbolElement::STB_LOCAL, TPEF::TPEFHeaders::STO_ABS, TPEF::SymbolElement::STT_NOTYPE, SYMBOL_TYPE_MASK, and TPEF::SymbolElement::type().
type()
Section::SectionType TPEF::TPEFSymbolSectionReader::type () const protected virtual
Returns the type of section it is meant to read.
Returns
The type of section it can read.
Implements TPEF::SectionReader.
Definition at line 86 of file TPEFSymbolSectionReader.cc.
{
    return Section::ST_SYMTAB;
}
References TPEF::Section::ST_SYMTAB.
Member Data Documentation
proto_
TPEFSymbolSectionReader TPEF::TPEFSymbolSectionReader::proto_ static private
Prototype instance of TPEFSymbolSectionReader to be registered to SectionReader.
Definition at line 72 of file TPEFSymbolSectionReader.hh.
SYMBOL_TYPE_MASK
const Byte TPEF::TPEFSymbolSectionReader::SYMBOL_TYPE_MASK = 0x0F static private
Mask for getting type of symbol from st_info field of symbol element.
Definition at line 69 of file TPEFSymbolSectionReader.hh.
Referenced by readData().
The documentation for this class was generated from the following files:
TPEFSymbolSectionReader.hh
TPEFSymbolSectionReader.cc