OpenASIP: ZoomOutCmd Class Reference
ZoomOutCmd Class Reference
#include <ZoomOutCmd.hh>
Public Member Functions
ZoomOutCmd ()
virtual ~ZoomOutCmd ()
virtual bool Do ()
virtual int id () const
virtual ZoomOutCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
EditorCommand for zooming out the canvas.
Definition at line 40 of file ZoomOutCmd.hh.
Constructor & Destructor Documentation
ZoomOutCmd()
ZoomOutCmd::ZoomOutCmd ()
The Constructor.
Definition at line 45 of file ZoomOutCmd.cc.
                      : EditorCommand(ProDeConstants::CMD_NAME_ZOOM_OUT) {
}
Referenced by create().
~ZoomOutCmd()
ZoomOutCmd::~ZoomOutCmd () virtual
The Destructor.
Definition at line 53 of file ZoomOutCmd.cc.
{
}
Member Function Documentation
create()
ZoomOutCmd * ZoomOutCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 90 of file ZoomOutCmd.cc.
{
    return new ZoomOutCmd();
}
References ZoomOutCmd().
Do()
bool ZoomOutCmd::Do () virtual
Executes the command.
Returns
true, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 64 of file ZoomOutCmd.cc.
               {
    MDFView* mView = dynamic_cast<MDFView*>(view());
    MachineCanvas* canvas = mView->canvas();
    canvas->zoomOut();
    return true;
}
References MDFView::canvas(), EditorCommand::view(), and MachineCanvas::zoomOut().
icon()
string ZoomOutCmd::icon () const virtual
Returns path to the command's icon file.
Returns
Full path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 101 of file ZoomOutCmd.cc.
                       {
    return ProDeConstants::CMD_ICON_ZOOM_OUT;
}
References ProDeConstants::CMD_ICON_ZOOM_OUT.
id()
int ZoomOutCmd::id () const virtual
Returns id of this command.
Returns
ID for this command to be used in menus and toolbars.
Implements GUICommand.
Definition at line 79 of file ZoomOutCmd.cc.
                     {
    return ProDeConstants::COMMAND_ZOOM_OUT;
}
References ProDeConstants::COMMAND_ZOOM_OUT.
isEnabled()
bool ZoomOutCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 125 of file ZoomOutCmd.cc.
                      {
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
string ZoomOutCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short name of the command to be used in the toolbar.
Reimplemented from GUICommand.
Definition at line 112 of file ZoomOutCmd.cc.
{
    return ProDeConstants::CMD_SNAME_ZOOM_OUT;
}
References ProDeConstants::CMD_SNAME_ZOOM_OUT.
The documentation for this class was generated from the following files:
ZoomOutCmd.hh
ZoomOutCmd.cc