OpenASIP: ProGe::ICDecoderGeneratorPlugin Class Reference
ProGe::ICDecoderGeneratorPlugin Class Reference abstract
#include <ICDecoderGeneratorPlugin.hh>
Public Member Functions
ICDecoderGeneratorPlugin (const TTAMachine::Machine &machine, const BinaryEncoding &bem, const std::string &description)
virtual ~ICDecoderGeneratorPlugin ()
virtual void completeNetlist (NetlistBlock &netlistBlock, const NetlistGenerator &generator)=0
virtual void generate (HDL language, const std::string &destinationDirectory, const NetlistGenerator &generator, const IDF::MachineImplementation &implementation, const std::string &entityString)=0
virtual std::set< int > requiredRFLatencies (const TTAMachine::ImmediateUnit &iu) const =0
virtual void verifyCompatibility () const =0
virtual void writeGlobalDefinitions (HDL language, std::ostream &pkgStream) const =0
std::string pluginDescription () const
int recognizedParameterCount () const
std::string recognizedParameter (int index) const
std::string parameterDescription (const std::string &paramName) const
void setParameter (const std::string &name, const std::string &value)
const TTAMachine::Machine & machine () const
const BinaryEncoding & bem () const
virtual void readParameters ()=0
Protected Member Functions
void addParameter (const std::string &name, const std::string &description)
bool hasParameterSet (const std::string &name) const
std::string parameterValue (const std::string &name) const
Static Protected Member Functions
static TTAMachine::Socket::Direction convertDirection (HDB::Direction direction)
Private Types
typedef std::map< std::string, std::string > StringMap
Map type for strings.
Private Attributes
const TTAMachine::Machine & machine_
The machine to generate.
const BinaryEncoding & bem_
The binary encoding map.
StringMap parameterValues_
Parameters set.
StringMap parameterDescriptions_
Parameter descriptions.
std::string description_
Description of the plugin.
Detailed Description
Base class for plugins that are able to generate and IC and decoder.
Todo:
Add rest of the methods.
Definition at line 68 of file ICDecoderGeneratorPlugin.hh.
Member Typedef Documentation
StringMap
typedef std::map<std::string, std::string> ProGe::ICDecoderGeneratorPlugin::StringMap private
Map type for strings.
Definition at line 151 of file ICDecoderGeneratorPlugin.hh.
Constructor & Destructor Documentation
ICDecoderGeneratorPlugin()
ProGe::ICDecoderGeneratorPlugin::ICDecoderGeneratorPlugin (const TTAMachine::Machine & machine, const BinaryEncoding & bem, const std::string & description)
Constructor.
Parameters
machine The machine to generate the IC&decoder for.
Definition at line 48 of file ICDecoderGeneratorPlugin.cc.
                                  :
    machine_(machine), bem_(bem), description_(description) {
}
~ICDecoderGeneratorPlugin()
ProGe::ICDecoderGeneratorPlugin::~ICDecoderGeneratorPlugin () virtual
Destructor.
Definition at line 60 of file ICDecoderGeneratorPlugin.cc.
{
}
Member Function Documentation
addParameter()
void ProGe::ICDecoderGeneratorPlugin::addParameter (const std::string & name, const std::string & description) protected
Adds the given parameter to the set of recognized parameters.
Parameters
name Name of the parameter.
description Description of the parameter.
Definition at line 159 of file ICDecoderGeneratorPlugin.cc.
{
    parameterDescriptions_.erase(name);
    parameterDescriptions_.insert(
        std::pair<string, string>(name, description));
}
References parameterDescriptions_.
Referenced by DefaultICDecoderGenerator::DefaultICDecoderGenerator().
bem()
const BinaryEncoding & ProGe::ICDecoderGeneratorPlugin::bem () const
Returns the binary encoding map.
Returns
The binary encoding map.
Definition at line 214 of file ICDecoderGeneratorPlugin.cc.
{
    return bem_;
}
References bem_.
Referenced by DefaultICDecoderGenerator::DefaultICDecoderGenerator(), and DefaultICDecoderGenerator::writeGlobalDefinitions().
completeNetlist()
virtual void ProGe::ICDecoderGeneratorPlugin::completeNetlist (NetlistBlock & netlistBlock, const NetlistGenerator & generator) pure virtual
Completes the given netlist block by adding IC block and completing the decoder block by adding the ports connected to IC. Connects also IC to all the units in the machine.
Parameters
coreBlock The netlist block to complete.
generator The netlist generator which generated the netlist.
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::NetlistGenerator::generate().
convertDirection()
static TTAMachine::Socket::Direction ProGe::ICDecoderGeneratorPlugin::convertDirection (HDB::Direction direction) static protected
generate()
virtual void ProGe::ICDecoderGeneratorPlugin::generate (HDL language, const std::string & destinationDirectory, const NetlistGenerator & generator, const IDF::MachineImplementation & implementation, const std::string & entityString) pure virtual
Generates the interconnection network and instruction decoder to the given destination directory.
Parameters
destinationDirectory The destination directory.
generator The netlist generator that generated the netlist block.
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::ProcessorGenerator::generateProcessor().
hasParameterSet()
bool ProGe::ICDecoderGeneratorPlugin::hasParameterSet (const std::string & name) const protected
Tells whether the plugin has the given parameter set.
Parameters
name Name of the parameter.
Returns
True if the given parameter is set, otherwise false.
Definition at line 176 of file ICDecoderGeneratorPlugin.cc.
{
    return MapTools::containsKey(parameterValues_, name);
}
References MapTools::containsKey(), and parameterValues_.
Referenced by DefaultICDecoderGenerator::busTraceStartingCycle(), DefaultICDecoderGenerator::bypassInstructionRegister(), DefaultICDecoderGenerator::generateBusTrace(), DefaultICDecoderGenerator::generateDebugger(), DefaultICDecoderGenerator::generateLockTrace(), DefaultICDecoderGenerator::generateNoSelfLockingFUs(), DefaultICDecoderGenerator::hasSynchronousReset(), DefaultICDecoderGenerator::lockTraceStartingCycle(), and parameterValue().
machine()
const TTAMachine::Machine & ProGe::ICDecoderGeneratorPlugin::machine () const
Returns the machine.
Returns
The machine.
Definition at line 203 of file ICDecoderGeneratorPlugin.cc.
{
    return machine_;
}
References machine_.
Referenced by DefaultICDecoderGenerator::DefaultICDecoderGenerator().
parameterDescription()
std::string ProGe::ICDecoderGeneratorPlugin::parameterDescription (const std::string & paramName) const
Returns the description of the given parameter.
Parameters
paramName Name of the parameter.
Returns
The description of the parameter.
Exceptions
IllegalParameter If the given parameter is unrecognized.
Definition at line 121 of file ICDecoderGeneratorPlugin.cc.
{
    try {
        return MapTools::valueForKey<string>(
            parameterDescriptions_, paramName);
    } catch (const KeyNotFound& e) {
        throw IllegalParameters(
            __FILE__, __LINE__, __func__, e.errorMessage());
    }
}
References __func__, Exception::errorMessage(), MapTools::keyForValue(), and parameterDescriptions_.
Referenced by ProcessorImplementationWindow::TransferDataToWindow().
parameterValue()
std::string ProGe::ICDecoderGeneratorPlugin::parameterValue (const std::string & name) const protected
Returns the value of the given parameter.
Parameters
name Name of the parameter.
Returns
Value of the parameter.
Exceptions
KeyNotFound If the given parameter is not set.
Definition at line 189 of file ICDecoderGeneratorPlugin.cc.
{
    if (!hasParameterSet(name)) {
        throw KeyNotFound(__FILE__, __LINE__, __func__);
    }
    return MapTools::valueForKey<string>(parameterValues_, name);
}
References __func__, hasParameterSet(), MapTools::keyForValue(), and parameterValues_.
Referenced by DefaultICDecoderGenerator::busTraceStartingCycle(), DefaultICDecoderGenerator::bypassInstructionRegister(), DefaultICDecoderGenerator::generate(), DefaultICDecoderGenerator::generateBusTrace(), DefaultICDecoderGenerator::generateDebugger(), DefaultICDecoderGenerator::generateDebuggerCode(), DefaultICDecoderGenerator::generateLockTrace(), DefaultICDecoderGenerator::generateNoSelfLockingFUs(), DefaultICDecoderGenerator::hasSynchronousReset(), and DefaultICDecoderGenerator::lockTraceStartingCycle().
pluginDescription()
std::string ProGe::ICDecoderGeneratorPlugin::pluginDescription () const
Returns the description of the plugin.
Returns
The description.
Definition at line 70 of file ICDecoderGeneratorPlugin.cc.
{
    return description_;
}
References description_.
Referenced by ProcessorImplementationWindow::TransferDataToWindow().
readParameters()
virtual void ProGe::ICDecoderGeneratorPlugin::readParameters () pure virtual
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::ProGeUI::generateProcessor().
recognizedParameter()
std::string ProGe::ICDecoderGeneratorPlugin::recognizedParameter (int index) const
Returns the name of a recognized parameter by the given index.
Parameters
index The index.
Returns
The name of the parameter.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of recognized parameters.
Definition at line 95 of file ICDecoderGeneratorPlugin.cc.
{
    if (index < 0 || index >= recognizedParameterCount()) {
        throw OutOfRange(__FILE__, __LINE__, __func__);
    }
    int i = 0;
    for (StringMap::const_iterator iter = parameterDescriptions_.begin();
         iter != parameterDescriptions_.end(); iter++) {
        if (i == index) {
            return iter->first;
        }
        i++;
    }
    assert(false);
    return "";
}
References __func__, assert, parameterDescriptions_, and recognizedParameterCount().
Referenced by ProcessorImplementationWindow::onSetParameterValue(), and ProcessorImplementationWindow::TransferDataToWindow().
recognizedParameterCount()
int ProGe::ICDecoderGeneratorPlugin::recognizedParameterCount () const
Returns the number of recognized parameters.
Returns
The number of recognized parameters.
Definition at line 81 of file ICDecoderGeneratorPlugin.cc.
{
    return parameterDescriptions_.size();
}
References parameterDescriptions_.
Referenced by recognizedParameter(), and ProcessorImplementationWindow::TransferDataToWindow().
requiredRFLatencies()
virtual std::set< int > ProGe::ICDecoderGeneratorPlugin::requiredRFLatencies (const TTAMachine::ImmediateUnit & iu) const pure virtual
Returns the set of acceptable latencies of the hardware implementation of the given immediate unit.
Parameters
iu The immediate unit.
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::ProcessorGenerator::checkIULatencies().
setParameter()
void ProGe::ICDecoderGeneratorPlugin::setParameter (const std::string & name, const std::string & value)
Sets the given parameter for the plugin.
Parameters
name Name of the parameter.
value Value of the parameter.
Exceptions
IllegalParameter If the given parameter is unrecognized.
Definition at line 140 of file ICDecoderGeneratorPlugin.cc.
{
    if (!MapTools::containsKey(parameterDescriptions_, name)) {
        string errorMsg = "Unrecognized IC/decoder plugin parameter: " +
            name;
        throw IllegalParameters(__FILE__, __LINE__, __func__, errorMsg);
    }
    parameterValues_.erase(name);
    parameterValues_.insert(std::pair<string, string>(name, value));
}
References __func__, MapTools::containsKey(), parameterDescriptions_, and parameterValues_.
Referenced by ProGe::ProGeUI::generateProcessor().
verifyCompatibility()
virtual void ProGe::ICDecoderGeneratorPlugin::verifyCompatibility () const pure virtual
Verifies that the plugin is compatible with the machine.
Exceptions
InvalidData If the plugin is not compatible with the machine.
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::ProcessorGenerator::generateProcessor().
writeGlobalDefinitions()
virtual void ProGe::ICDecoderGeneratorPlugin::writeGlobalDefinitions (HDL language, std::ostream & pkgStream) const pure virtual
Returns global package definitions in the form of a stream specifically for the variable length instruction architecture.
Parameters
language The HDL to use.
pkgStream The destination stream
Implemented in DefaultICDecoderGenerator.
Referenced by ProGe::ProcessorGenerator::generateGlobalsPackage().
Member Data Documentation
bem_
const BinaryEncoding& ProGe::ICDecoderGeneratorPlugin::bem_ private
The binary encoding map.
Definition at line 156 of file ICDecoderGeneratorPlugin.hh.
Referenced by bem().
description_
std::string ProGe::ICDecoderGeneratorPlugin::description_ private
Description of the plugin.
Definition at line 162 of file ICDecoderGeneratorPlugin.hh.
Referenced by pluginDescription().
machine_
const TTAMachine::Machine& ProGe::ICDecoderGeneratorPlugin::machine_ private
The machine to generate.
Definition at line 154 of file ICDecoderGeneratorPlugin.hh.
Referenced by machine().
parameterDescriptions_
StringMap ProGe::ICDecoderGeneratorPlugin::parameterDescriptions_ private
Parameter descriptions.
Definition at line 160 of file ICDecoderGeneratorPlugin.hh.
Referenced by addParameter(), parameterDescription(), recognizedParameter(), recognizedParameterCount(), and setParameter().
parameterValues_
StringMap ProGe::ICDecoderGeneratorPlugin::parameterValues_ private
Parameters set.
Definition at line 158 of file ICDecoderGeneratorPlugin.hh.
Referenced by hasParameterSet(), parameterValue(), and setParameter().
The documentation for this class was generated from the following files:
ICDecoderGeneratorPlugin.hh
ICDecoderGeneratorPlugin.cc