OpenASIP: ProGe::NetlistWriter Class Reference
ProGe::NetlistWriter Class Reference abstract
#include <NetlistWriter.hh>
Public Member Functions
NetlistWriter (const BaseNetlistBlock &targetBlock)
virtual ~NetlistWriter ()
virtual void write (const std::string &dstDirectory)=0
Protected Member Functions
const BaseNetlistBlock & targetNetlistBlock () const
Private Attributes
const BaseNetlistBlock & netlistBlock_
Netlist block to be written.
Detailed Description
Interface for different block level netlist writers.
Definition at line 47 of file NetlistWriter.hh.
Constructor & Destructor Documentation
NetlistWriter()
ProGe::NetlistWriter::NetlistWriter (const BaseNetlistBlock & netlistBlock)
The constructor.
Parameters
netlist The netlist to be written in some HDL.
Definition at line 46 of file NetlistWriter.cc.
    : netlistBlock_(netlistBlock) {
}
~NetlistWriter()
ProGe::NetlistWriter::~NetlistWriter () virtual
The destructor.
Definition at line 54 of file NetlistWriter.cc.
{
}
Member Function Documentation
targetNetlistBlock()
const BaseNetlistBlock & ProGe::NetlistWriter::targetNetlistBlock () const protected
Returns the netlist.
Returns
The netlist.
Definition at line 64 of file NetlistWriter.cc.
{
    return netlistBlock_;
}
References netlistBlock_.
Referenced by ProGe::VerilogNetlistWriter::netlistParameterPkgName(), ProGe::VHDLNetlistWriter::netlistParameterPkgName(), ProGe::VerilogNetlistWriter::write(), ProGe::VHDLNetlistWriter::write(), ProGe::VerilogNetlistWriter::writeNetlistParameterPackage(), and ProGe::VHDLNetlistWriter::writeNetlistParameterPackage().
write()
virtual void ProGe::NetlistWriter::write (const std::string & dstDirectory) pure virtual
Implemented in ProGe::VerilogNetlistWriter, and ProGe::VHDLNetlistWriter.
Referenced by ProGe::NetlistBlock::write(), and PlatformIntegrator::writeNewToplevel().
Member Data Documentation
netlistBlock_
const BaseNetlistBlock& ProGe::NetlistWriter::netlistBlock_ private
Netlist block to be written.
Definition at line 59 of file NetlistWriter.hh.
Referenced by targetNetlistBlock().
The documentation for this class was generated from the following files:
NetlistWriter.hh
NetlistWriter.cc