OpenASIP: TPEF::CodeSymElement Class Reference
TPEF::CodeSymElement Class Reference
#include <CodeSymElement.hh>
Public Member Functions
CodeSymElement ()
virtual ~CodeSymElement ()
virtual SymbolType type () const
InstructionElement * reference () const
void setReference (InstructionElement *aReference)
void setReference (const ReferenceManager::SafePointer *aReference)
Word size () const
void setSize (Word aSize)
Public Member Functions inherited from TPEF::SymbolElement
SymbolElement ()
virtual ~SymbolElement ()
bool absolute () const
void setAbsolute (bool anAbsoluteness)
SymbolBinding binding () const
void setBinding (SymbolBinding aBinding)
Chunk * name () const
void setName (Chunk *aName)
void setName (const ReferenceManager::SafePointer *aName)
Section * section () const
void setSection (Section *aSect)
void setSection (const ReferenceManager::SafePointer *aSect)
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * reference_
Referred object.
Word size_
Size of referred object in MAUs.
Additional Inherited Members
Public Types inherited from TPEF::SymbolElement
enum SymbolBinding { STB_LOCAL = 0x0 , STB_GLOBAL = 0x1 , STB_WEAK = 0x2 }
Binding types of symbol.
enum SymbolType {
STT_NOTYPE = 0x0 , STT_DATA = 0x1 , STT_CODE = 0x2 , STT_SECTION = 0x3 ,
STT_FILE = 0x4 , STT_PROCEDURE = 0x5
}
Type of symbol element.
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Code symbol.
Definition at line 46 of file CodeSymElement.hh.
Constructor & Destructor Documentation
CodeSymElement()
TPEF::CodeSymElement::CodeSymElement ()
Constructor.
Definition at line 44 of file CodeSymElement.cc.
                               :
    SymbolElement(), reference_(&SafePointer::null),
    size_(0) {
}
~CodeSymElement()
TPEF::CodeSymElement::~CodeSymElement () virtual
Destructor.
Definition at line 52 of file CodeSymElement.cc.
{
}
Member Function Documentation
reference()
InstructionElement * TPEF::CodeSymElement::reference () const
Returns object which element refers.
Returns
object which element refers.
Definition at line 71 of file CodeSymElement.cc.
{
    return dynamic_cast<InstructionElement*>(reference_->pointer());
}
References TPEF::ReferenceManager::SafePointer::pointer(), and reference_.
Referenced by TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutSymbolSectionReader::finalize(), TPEFDumper::section(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), and TPEF::TPEFSymbolSectionWriter::writeValueAndSize().
setReference() [1/2]
void TPEF::CodeSymElement::setReference (const ReferenceManager::SafePointer * aReference)
Sets object which element refers.
Parameters
aReference Object which element refers.
Definition at line 91 of file CodeSymElement.cc.
{
    reference_ = aReference;
}
References reference_.
setReference() [2/2]
void TPEF::CodeSymElement::setReference (InstructionElement * aReference)
Sets object which element refers.
Parameters
aReference Object which element refers.
Definition at line 81 of file CodeSymElement.cc.
{
    reference_ = SafePointer::replaceReference(reference_, aReference);
}
References reference_, and TPEF::ReferenceManager::SafePointer::replaceReference().
Referenced by TTAProgram::ProgramWriter::createBinary(), LabelManager::createSymbolWithReference(), TPEF::AOutSymbolSectionReader::finalize(), TPEF::AOutSymbolSectionReader::initializeSymbol(), and LabelManager::writeProcedureSymbols().
setSize()
void TPEF::CodeSymElement::setSize (Word aSize)
Sets size of referred object in MAUs.
Parameters
aSize of the referred object in MAUs.
Definition at line 112 of file CodeSymElement.cc.
{
    size_ = aSize;
}
References size_.
Referenced by TPEF::AOutSymbolSectionReader::finalize().
size()
Word TPEF::CodeSymElement::size () const
Returns size of the referred object in MAUs.
Returns
Size of the referred object in MAUs.
Definition at line 102 of file CodeSymElement.cc.
{
    return size_;
}
References size_.
Referenced by TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFSymbolSectionWriter::writeValueAndSize().
type()
SymbolElement::SymbolType TPEF::CodeSymElement::type () const virtual
Returns type of the element.
Returns
Type of the element.
Implements TPEF::SymbolElement.
Reimplemented in TPEF::ProcedSymElement.
Definition at line 61 of file CodeSymElement.cc.
{
    return STT_CODE;
}
References TPEF::SymbolElement::STT_CODE.
Member Data Documentation
reference_
const ReferenceManager::SafePointer* TPEF::CodeSymElement::reference_ private
Referred object.
Definition at line 62 of file CodeSymElement.hh.
Referenced by reference(), setReference(), and setReference().
size_
Word TPEF::CodeSymElement::size_ private
Size of referred object in MAUs.
Definition at line 64 of file CodeSymElement.hh.
Referenced by setSize(), and size().
The documentation for this class was generated from the following files:
CodeSymElement.hh
CodeSymElement.cc