OpenASIP: ResumeCommand Class Reference
ResumeCommand Class Reference
#include <ResumeCommand.hh>
Public Member Functions
ResumeCommand ()
virtual ~ResumeCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "resume" command of the Simulator Control Language.
Definition at line 47 of file ResumeCommand.hh.
Constructor & Destructor Documentation
ResumeCommand()
ResumeCommand::ResumeCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 46 of file ResumeCommand.cc.
                             :
    SimControlLanguageCommand("resume") {
}
~ResumeCommand()
ResumeCommand::~ResumeCommand () virtual
Destructor.
Does nothing.
Definition at line 55 of file ResumeCommand.cc.
{
}
Member Function Documentation
execute()
bool ResumeCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "resume" command.
Resume simulation of the program until the simulation is finished or a breakpoint is reached. The optional argument gives the number of times the continue command is repeated, that is, the number of times breakpoints should be ignored.
Parameters
arguments (optional) count of times to repeat in case breakpoints are reached.
Returns
Always true.
Exceptions
NumberFormatException Is never thrown by this command.
Implements CustomCommand.
Definition at line 73 of file ResumeCommand.cc.
{
    // how many times breakpoints should be ignored?
    int repeatCount = 0;
    if (!checkArgumentCount(arguments.size() - 1, 0, 1)) {
        return false;
    } else {
        if (arguments.size() > 1) {
            if  (!checkPositiveIntegerArgument(arguments[1])) {
                return false;
            } else {
                repeatCount = arguments[1].integerValue();
            }
        }
    }
    if (!checkSimulationStopped()) {
        return false;
    }
    int repeats = 0;
    do {
        simulatorFrontend().run();
        ++repeats;
    } while(simulatorFrontend().isSimulationStopped() &&
            repeats < repeatCount);
    printStopInformation();
    return true;
}
References CustomCommand::checkArgumentCount(), CustomCommand::checkPositiveIntegerArgument(), SimControlLanguageCommand::checkSimulationStopped(), SimControlLanguageCommand::printStopInformation(), SimulatorFrontend::run(), and SimControlLanguageCommand::simulatorFrontend().
helpText()
std::string ResumeCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 113 of file ResumeCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_RESUME).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_RESUME.
The documentation for this class was generated from the following files:
ResumeCommand.hh
ResumeCommand.cc