OpenASIP: BFLateBypassGuard Class Reference
BFLateBypassGuard Class Reference
#include <BFLateBypassGuard.hh>
Public Member Functions
BFLateBypassGuard (BF2Scheduler &sched, MoveNode &src, MoveNode &dst, int lc)
virtual bool operator() ()
virtual void undoOnlyMe ()
Public Member Functions inherited from BFLateBypass
BFLateBypass (BF2Scheduler &sched, MoveNode &src, MoveNode &dst, int lc)
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
const TTAMachine::Guard * originalGuard_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFLateBypass
int originalCycle_
MoveNode & src_
MoveNode & dst_
int lc_
const TTAMachine::Bus * originalBus_
const TTAMachine::Bus * prologBus_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 8 of file BFLateBypassGuard.hh.
Constructor & Destructor Documentation
BFLateBypassGuard()
BFLateBypassGuard::BFLateBypassGuard (BF2Scheduler & sched, MoveNode & src, MoveNode & dst, int lc) inline
Definition at line 10 of file BFLateBypassGuard.hh.
                                                                                 :
        BFLateBypass(sched, src, dst, lc) {}
Member Function Documentation
operator()()
bool BFLateBypassGuard::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Reimplemented from BFLateBypass.
Definition at line 19 of file BFLateBypassGuard.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tPerforming late bypass guard: " << dst_.toString() << std::endl;
#endif
    // Only allow guard bypass if it can save clock cycles on guard path.
    if (dst_.cycle() > lc_ + dst_.guardLatency()-1) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tAborting guard bypass due too long guard distance" << std::endl;
#endif
        return false;
    }
    if (!src_.isSourceOperation()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tsrc src not op: "<< src_.toString() << std::endl;
#endif
        return false;
    }
    if (dst_.isSourceOperation()) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\tsrc not constant: " << dst_.toString() << std::endl;
#endif
        return false;
    }
    ProgramOperation &po = src_.sourceOperation();
    const Operation& op = po.operation();
    // TODO: might need set of these for annotations.
    const TTAMachine::FunctionUnit* fu = NULL;
    for (int i = 0; i < po.inputMoveCount(); i++) {
        MoveNode& mn = po.inputMove(i);
        if (mn.isScheduled()) {
            fu = &mn.move().destination().functionUnit();
        }
        // TODO: fu annotations can forbid this?
    }
    for (int i = 0; i < po.outputMoveCount(); i++) {
        MoveNode& mn = po.outputMove(i);
        if (mn.isScheduled()) {
            fu = &mn.move().source().functionUnit();
        }
        // TODO: fu annotations can forbid this?
    }
    if (dst_.move().isUnconditional()) {
        ddg().writeToDotFile("guard_edge_dest_uncond.dot");
    }
    assert(!dst_.move().isUnconditional());
    const TTAMachine::Bus& bus = dst_.move().bus();
    for (int i = 0; i < bus.guardCount(); i++) {
        TTAMachine::Guard* guard = bus.guard(i);
        TTAMachine::PortGuard* pg =
            dynamic_cast<TTAMachine::PortGuard*>(guard);
        if (pg == NULL) {
            continue;
        }
        if (pg->isInverted() != dst_.move().guard().isInverted()) {
            continue;
        }
        const TTAMachine::FUPort* port = pg->port();
        TTAMachine::FunctionUnit* gfu = port->parentUnit();
        if (gfu->hasOperation(op.name()) &&
            po.outputIndexFromGuard(*pg) ==
            src_.move().source().operationIndex() &&
            (fu == NULL || fu == gfu)) {
            if (!po.isLegalFU(*gfu)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\t\tFU: " << gfu->name() << " not allowed for operation: " << po.toString() << std::endl;
#endif
                continue;
            }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
            std::cerr << "\t\t\tFound suitable guard & FU" << std::endl;
#endif
            originalCycle_ = dst_.cycle();
            originalBus_ = &dst_.move().bus();
            originalGuard_ = &dst_.move().guard().guard();
            unassign(dst_, false);
            // TODO: backup old guard.
            dst_.move().setGuard(new TTAProgram::MoveGuard(*guard));
            ddg().guardConverted(src_, dst_);
            BFOptimization* sched = new BFScheduleExact(sched_, dst_, originalCycle_);
            if ((*sched)()) {
                postChildren_.push(sched);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\tGuard conversion ok: " << dst_.toString() << std::endl;
#endif
                return true;
            } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
                std::cerr << "\t\tGuard conversion sched fail.: " << dst_.toString() << std::endl;
#endif
                delete sched;
                ddg().guardRestored(src_, dst_);
                dst_.move().setGuard(new TTAProgram::MoveGuard(*originalGuard_));
                dst_.move().setBus(*originalBus_);
                assert(canAssign(originalCycle_, dst_));
                assign(originalCycle_, dst_);
            }
        }
    }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tDid not find a bus with suitable guard?" << std::endl;
#endif
    return false;
}
References assert, BFOptimization::assign(), TTAProgram::Move::bus(), BFOptimization::canAssign(), MoveNode::cycle(), BFOptimization::ddg(), TTAProgram::Move::destination(), BFLateBypass::dst_, TTAProgram::Terminal::functionUnit(), TTAProgram::Move::guard(), TTAProgram::MoveGuard::guard(), TTAMachine::Bus::guard(), DataDependenceGraph::guardConverted(), TTAMachine::Bus::guardCount(), MoveNode::guardLatency(), DataDependenceGraph::guardRestored(), TTAMachine::FunctionUnit::hasOperation(), ProgramOperation::inputMove(), ProgramOperation::inputMoveCount(), TTAMachine::Guard::isInverted(), TTAProgram::MoveGuard::isInverted(), ProgramOperation::isLegalFU(), MoveNode::isScheduled(), MoveNode::isSourceOperation(), TTAProgram::Move::isUnconditional(), BFLateBypass::lc_, MoveNode::move(), TTAMachine::Component::name(), Operation::name(), ProgramOperation::operation(), TTAProgram::Terminal::operationIndex(), BFLateBypass::originalBus_, BFLateBypass::originalCycle_, originalGuard_, ProgramOperation::outputIndexFromGuard(), ProgramOperation::outputMove(), ProgramOperation::outputMoveCount(), TTAMachine::BaseFUPort::parentUnit(), TTAMachine::PortGuard::port(), Reversible::postChildren_, BFOptimization::sched_, TTAProgram::Move::setBus(), TTAProgram::Move::setGuard(), TTAProgram::Move::source(), MoveNode::sourceOperation(), BFLateBypass::src_, MoveNode::toString(), ProgramOperation::toString(), BFOptimization::unassign(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
undoOnlyMe()
void BFLateBypassGuard::undoOnlyMe () virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from BFLateBypass.
Definition at line 147 of file BFLateBypassGuard.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tUndoing guard conversion: " << dst_.toString() << std::endl;
#endif
    ddg().guardRestored(src_, dst_);
    dst_.move().setGuard(new TTAProgram::MoveGuard(*originalGuard_));
    dst_.move().setBus(*originalBus_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tReassigning move: " << dst_.toString() << " to cycle: "
          << originalCycle_ << " bus: " << originalBus_->name() << std::endl;
#endif
    assert(canAssign(originalCycle_, dst_));
    assign(originalCycle_, dst_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\tReassigned move:" << dst_.toString() << std::endl;
#endif
}
References assert, BFOptimization::assign(), BFOptimization::canAssign(), BFOptimization::ddg(), BFLateBypass::dst_, DataDependenceGraph::guardRestored(), MoveNode::move(), TTAMachine::Component::name(), BFLateBypass::originalBus_, BFLateBypass::originalCycle_, originalGuard_, TTAProgram::Move::setBus(), TTAProgram::Move::setGuard(), BFLateBypass::src_, and MoveNode::toString().
Member Data Documentation
originalGuard_
const TTAMachine::Guard* BFLateBypassGuard::originalGuard_ private
Definition at line 16 of file BFLateBypassGuard.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFLateBypassGuard.hh
BFLateBypassGuard.cc