OpenASIP: SocketEncoding Class Reference
SocketEncoding Class Reference
#include <SocketEncoding.hh>
Public Member Functions
SocketEncoding (const std::string &name, unsigned int encoding, unsigned int extraBits, SlotField &parent)
SocketEncoding (const ObjectState *state, SlotField &parent)
virtual ~SocketEncoding ()
SlotField * parent () const
std::string socketName () const
void setSocketCodes (SocketCodeTable &codeTable)
void unsetSocketCodes ()
bool hasSocketCodes () const
SocketCodeTable & socketCodes () const
int socketCodePosition () const
void setEncoding (unsigned int encoding, unsigned int extraBits)
int socketIDPosition () const
int socketIDWidth () const
virtual int width () const
virtual int bitPosition () const
virtual ObjectState * saveState () const
Public Member Functions inherited from Encoding
virtual ~Encoding ()
InstructionField * parent () const
unsigned int encoding () const
unsigned int extraBits () const
Static Public Attributes
static const std::string OSNAME_SOCKET_ENCODING = "socket_encoding"
ObjectState name for socket encoding.
static const std::string OSKEY_SOCKET_NAME = "socket_name"
ObjectState attribute key for the name of the socket.
static const std::string OSKEY_SC_TABLE = "sc_table"
ObjectState attribute key for the name of the socket code table.
Static Public Attributes inherited from Encoding
static const std::string OSNAME_ENCODING = "encoding"
ObjectState name for Encoding class.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Private Member Functions
void detachFromParent ()
Private Attributes
std::string name_
Name of the socket.
SocketCodeTable * socketCodes_
Socket code table.
Additional Inherited Members
Protected Member Functions inherited from Encoding
Encoding (unsigned int encoding, unsigned int extraBits, InstructionField *parent)
Encoding (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
void setEncoding (unsigned int encoding, unsigned int extraBits)
Detailed Description
The SocketEncoding class models how socket sources or destinations are mapped to control codes.
Sockets have an independent encoding in each source or destination field they appear in. A socket encoding can be more complex than a fixed control code and encode many destinations or sources all reached from the same socket. In this case, the socket encoding contains SocketCodeTable instance.
Definition at line 51 of file SocketEncoding.hh.
Constructor & Destructor Documentation
SocketEncoding() [1/2]
SocketEncoding::SocketEncoding (const std::string & name, unsigned int encoding, unsigned int extraBits, SlotField & parent)
The constructor.
Creates a socket encoding and registers it into the given slot field. The socket is identified by name. The (fixed) part of the socket encoding and the parent slot field are given as parameters.
Parameters
name Name of the socket.
encoding Fixed part of the encoding.
extraBits The number of extra (zero) bits in the encoding.
parent The parent slot field.
Exceptions
ObjectAlreadyExists If the parent slot field already has an encoding for the same socket, or if the given encoding is ambiguous with another encoding in the parent slot field.
Definition at line 66 of file SocketEncoding.cc.
    : Encoding(encoding, extraBits, NULL), name_(name), socketCodes_(NULL) {
    parent.addSocketEncoding(*this);
    setParent(&parent);
}
References SlotField::addSocketEncoding(), parent(), and Encoding::setParent().
SocketEncoding() [2/2]
SocketEncoding::SocketEncoding (const ObjectState * state, SlotField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent slot field.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the parent slot field already has an encoding for the same socket, or if the given encoding is ambiguous with another encoding in the parent slot field.
Definition at line 88 of file SocketEncoding.cc.
    : Encoding(state, &parent), name_(""), socketCodes_(NULL) {
    const string procName = "SocketEncoding::SocketEncoding";
    try {
    name_ = state->stringAttribute(OSKEY_SOCKET_NAME);
    if (state->hasAttribute(OSKEY_SC_TABLE)) {
        string tableName = state->stringAttribute(OSKEY_SC_TABLE);
        BinaryEncoding* bem = parent.parent()->parent();
        if (&bem->socketCodeTable(tableName) ==
        &NullSocketCodeTable::instance()) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName);
        } else {
        setSocketCodes(bem->socketCodeTable(tableName));
        }
    }
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
    setParent(NULL);
    parent.addSocketEncoding(*this);
    setParent(&parent);
}
References SlotField::addSocketEncoding(), Exception::errorMessage(), ObjectState::hasAttribute(), NullSocketCodeTable::instance(), name_, OSKEY_SC_TABLE, OSKEY_SOCKET_NAME, MoveSlot::parent(), SlotField::parent(), parent(), Encoding::setParent(), setSocketCodes(), BinaryEncoding::socketCodeTable(), and ObjectState::stringAttribute().
~SocketEncoding()
SocketEncoding::~SocketEncoding () virtual
The destructor.
Definition at line 119 of file SocketEncoding.cc.
{ detachFromParent(); }
References detachFromParent().
Member Function Documentation
bitPosition()
int SocketEncoding::bitPosition () const virtual
Returns always 0.
Returns
The position.
Implements Encoding.
Definition at line 291 of file SocketEncoding.cc.
{
    return 0;
}
detachFromParent()
void SocketEncoding::detachFromParent () private
Removes itself from the parent slot field.
Definition at line 316 of file SocketEncoding.cc.
{
    if (this->parent() == nullptr) {
        return;
    }
    SlotField* parent = this->parent();
    setParent(nullptr);
    parent->removeSocketEncoding(*this);
}
References parent(), SlotField::removeSocketEncoding(), and Encoding::setParent().
Referenced by setEncoding(), and ~SocketEncoding().
hasSocketCodes()
bool SocketEncoding::hasSocketCodes () const
Tells whether the socket encoding contains a socket code table.
Returns
True if the socket encoding contains a socket code table, otherwise false.
Definition at line 177 of file SocketEncoding.cc.
{
    return socketCodes_ != NULL;
}
References socketCodes_.
Referenced by BEMValidator::checkDestinationField(), BEMValidator::checkSocketCodeTable(), BEMValidator::checkSourceField(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), printSlotFieldEncodings(), saveState(), socketCodes(), width(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
parent()
SlotField * SocketEncoding::parent () const
Returns the parent slot field.
Returns
The parent slot field.
Definition at line 127 of file SocketEncoding.cc.
{
    InstructionField* parent = Encoding::parent();
    if (parent != NULL) {
        SlotField* sField = dynamic_cast<SlotField*>(parent);
        assert(sField != NULL);
        return sField;
    } else {
        return NULL;
    }
}
References assert, Encoding::parent(), and parent().
Referenced by SlotField::addSocketEncoding(), BEMValidator::checkSocketCodeTable(), detachFromParent(), parent(), DefaultDecoderGenerator::portCodeCondition(), SlotField::removeSocketEncoding(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), setEncoding(), socketCodePosition(), SocketEncoding(), SocketEncoding(), socketIDPosition(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
saveState()
ObjectState * SocketEncoding::saveState () const virtual
Saves the state of the socket encoding to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from Encoding.
Definition at line 302 of file SocketEncoding.cc.
{
    ObjectState* state = Encoding::saveState();
    state->setName(OSNAME_SOCKET_ENCODING);
    state->setAttribute(OSKEY_SOCKET_NAME, socketName());
    if (hasSocketCodes()) {
        state->setAttribute(OSKEY_SC_TABLE, socketCodes().name());
    }
    return state;
}
References hasSocketCodes(), OSKEY_SC_TABLE, OSKEY_SOCKET_NAME, OSNAME_SOCKET_ENCODING, Encoding::saveState(), ObjectState::setAttribute(), ObjectState::setName(), socketCodes(), and socketName().
Referenced by SlotField::saveState().
setEncoding()
void SocketEncoding::setEncoding (unsigned int encoding, unsigned int extraBits)
Sets new encoding.
Parameters
encoding The encoding.
extraBits The extrabits of the encoding.
Exceptions
ObjectAlreadyExists If the parent slot field already has an encoding for the same socket, or if the given encoding is ambiguous with another encoding in the parent slot field.
Definition at line 223 of file SocketEncoding.cc.
{
    SlotField* parent = this->parent();
    unsigned int oldEncoding = this->encoding();
    unsigned int oldExtrabits = this->extraBits();
    detachFromParent();
    Encoding::setEncoding(encoding, extraBits);
    try {
        parent->addSocketEncoding(*this);
    } catch (ObjectAlreadyExists& e) {
        Encoding::setEncoding(oldEncoding, oldExtrabits);
        parent->addSocketEncoding(*this);
    }
    setParent(parent);
}
References SlotField::addSocketEncoding(), detachFromParent(), Encoding::encoding(), Encoding::extraBits(), parent(), Encoding::setEncoding(), and Encoding::setParent().
setSocketCodes()
void SocketEncoding::setSocketCodes (SocketCodeTable & codeTable)
Attaches a set of socket codes to the socket encoding.
Parameters
codeTable The socket code table to be attached.
Definition at line 156 of file SocketEncoding.cc.
{
    socketCodes_ = &codeTable;
}
References socketCodes_.
Referenced by BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), and SocketEncoding().
socketCodePosition()
int SocketEncoding::socketCodePosition () const
Returns the position of the socket code within the slot field.
Definition at line 203 of file SocketEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::RIGHT) {
        return parent()->width() - parent()->extraBits() -
               socketCodes().width();
    } else {
        return 0;
    }
}
References InstructionField::extraBits(), parent(), BinaryEncoding::RIGHT, socketCodes(), SlotField::width(), and SocketCodeTable::width().
Referenced by BEMTester::conflictsWithDestinationEncodings(), and BEMTester::conflictsWithSourceEncodings().
socketCodes()
SocketCodeTable & SocketEncoding::socketCodes () const
Returns the socket code table.
Returns a NullSocketCodeTable instance if the socket does not have a socket code table set.
Returns
The socket code table.
Definition at line 191 of file SocketEncoding.cc.
{
    if (!hasSocketCodes()) {
    return NullSocketCodeTable::instance();
    } else {
    return *socketCodes_;
    }
}
References hasSocketCodes(), NullSocketCodeTable::instance(), and socketCodes_.
Referenced by BEMValidator::checkSocketCodeTable(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), printSlotFieldEncodings(), SocketCodeTable::removeReferences(), DefaultDecoderGenerator::rfOpcodeFromSrcOrDstField(), saveState(), socketCodePosition(), width(), DefaultDecoderGenerator::writeControlRulesOfFUInputPort(), DefaultDecoderGenerator::writeControlRulesOfFUOutputPort(), DefaultDecoderGenerator::writeControlRulesOfRFReadPort(), and DefaultDecoderGenerator::writeControlRulesOfRFWritePort().
socketIDPosition()
int SocketEncoding::socketIDPosition () const
Returns the position of the socket ID within the slot field.
The position is always 0 if socket ID is in the right end of the field. However, if socket code is in the right end of the field, the position of the socket ID depends on the bit width of the socket code.
Returns
The position of the socket ID.
Definition at line 249 of file SocketEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::RIGHT) {
        return 0;
    } else {
        return parent()->width() - parent()->extraBits() - socketIDWidth();
    }
}
References InstructionField::extraBits(), parent(), BinaryEncoding::RIGHT, socketIDWidth(), and SlotField::width().
Referenced by BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), DefaultDecoderGenerator::socketEncodingCondition(), and BEMTester::splitEncodingTo().
socketIDWidth()
int SocketEncoding::socketIDWidth () const
Returns the bit width of the fixed part of the socket encoding.
Returns
The bit width.
Definition at line 264 of file SocketEncoding.cc.
{
    return MathTools::bitLength(encoding()) + extraBits();
}
References MathTools::bitLength(), Encoding::encoding(), and Encoding::extraBits().
Referenced by BEMTester::canAddComponentEncoding(), BEMTester::conflictsWithDestinationEncodings(), BEMTester::conflictsWithSourceEncodings(), CodeCompressorPlugin::encodeFUTerminal(), CodeCompressorPlugin::encodeIUTerminal(), CodeCompressorPlugin::encodeRFTerminal(), DefaultDecoderGenerator::portCodeCondition(), printSlotFieldEncodings(), DefaultDecoderGenerator::socketEncodingCondition(), socketIDPosition(), BEMTester::splitEncodingTo(), width(), and DefaultDecoderGenerator::writeControlRulesOfFUInputPort().
socketName()
std::string SocketEncoding::socketName () const
Returns the name of the socket.
Returns
The name of the socket.
Definition at line 145 of file SocketEncoding.cc.
{
    return name_;
}
References name_.
Referenced by SlotField::addSocketEncoding(), BEMValidator::checkSocketCodeTable(), SlotField::hasSocketEncoding(), BEMValidator::needsSocketCodeTable(), printSlotFieldEncodings(), saveState(), and SlotField::socketEncoding().
unsetSocketCodes()
void SocketEncoding::unsetSocketCodes ()
Removes the socket codes from the socket encoding.
Definition at line 165 of file SocketEncoding.cc.
{
    socketCodes_ = NULL;
}
References socketCodes_.
Referenced by SocketCodeTable::removeReferences().
width()
int SocketEncoding::width () const virtual
Returns the number of bits required to encode all the destinations of this socket.
Returns
The number of bits.
Reimplemented from Encoding.
Definition at line 276 of file SocketEncoding.cc.
{
    int width = socketIDWidth();
    if (hasSocketCodes()) {
    width += socketCodes().width();
    }
    return width;
}
References hasSocketCodes(), socketCodes(), socketIDWidth(), SocketCodeTable::width(), and width().
Referenced by printSlotFieldEncodings(), SlotField::width(), and width().
Member Data Documentation
name_
std::string SocketEncoding::name_ private
Name of the socket.
Definition at line 90 of file SocketEncoding.hh.
Referenced by SocketEncoding(), and socketName().
OSKEY_SC_TABLE
const std::string SocketEncoding::OSKEY_SC_TABLE = "sc_table" static
ObjectState attribute key for the name of the socket code table.
Definition at line 83 of file SocketEncoding.hh.
Referenced by saveState(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), and SocketEncoding().
OSKEY_SOCKET_NAME
const std::string SocketEncoding::OSKEY_SOCKET_NAME = "socket_name" static
ObjectState attribute key for the name of the socket.
Definition at line 81 of file SocketEncoding.hh.
Referenced by saveState(), BEMSerializer::slotFieldToFile(), BEMSerializer::slotFieldToOM(), and SocketEncoding().
OSNAME_SOCKET_ENCODING
const std::string SocketEncoding::OSNAME_SOCKET_ENCODING = "socket_encoding" static
ObjectState name for socket encoding.
Definition at line 79 of file SocketEncoding.hh.
Referenced by SlotField::loadState(), saveState(), BEMSerializer::slotFieldToFile(), and BEMSerializer::slotFieldToOM().
socketCodes_
SocketCodeTable* SocketEncoding::socketCodes_ private
Socket code table.
Definition at line 92 of file SocketEncoding.hh.
Referenced by hasSocketCodes(), setSocketCodes(), socketCodes(), and unsetSocketCodes().
The documentation for this class was generated from the following files:
SocketEncoding.hh
SocketEncoding.cc