OpenASIP: InfoBussesCommand Class Reference
InfoBussesCommand Class Reference
Public Member Functions
InfoBussesCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoBussesCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info busses".
Definition at line 413 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoBussesCommand()
InfoBussesCommand::InfoBussesCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 418 of file InfoCommand.cc.
                                                                :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoBussesCommand()
virtual InfoBussesCommand::~InfoBussesCommand () inline virtual
Destructor.
Definition at line 425 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoBussesCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info busses" command.
"info busses" prints information of the busses of the machine.
Parameters
arguments No arguments should be given.
Returns
Always true.
Implements SimControlLanguageSubCommand.
Definition at line 436 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 0, 1)) {
            return false;
        }
        const TTAMachine::Machine& mach =
            parent().simulatorFrontend().machine();
        if (argumentCount == 0) {
            const TTAMachine::Machine::BusNavigator& nav =
                mach.busNavigator();
            std::string result = "";
            bool isFirst = true;
            for (int i = 0; i < nav.count(); ++i) {
                if (!isFirst)
                    result += "\n";
                TTAMachine::Bus* bus = nav.item(i);
                assert(bus != NULL);
                result += bus->name() + ": ";
                bool isFirstSegment = true;
                for (int j = 0; j < bus->segmentCount(); ++j) {
                    if (!isFirstSegment)
                        result += " ";
                    result += bus->segment(j)->name();
                    isFirstSegment = false;
                }
                isFirst = false;
            }
            parent().interpreter()->setResult(result);
            return true;
        } else if (argumentCount == 1) {
            const TTAMachine::Machine::BusNavigator& nav =
                mach.busNavigator();
            const std::string busName = arguments.at(2).stringValue();
            if (!nav.hasItem(busName)) {
                parent().interpreter()->setError(
                    SimulatorToolbox::textGenerator().text(
                        Texts::TXT_BUS_NOT_FOUND).str());
                return false;
            }
            TTAMachine::Bus* bus = nav.item(busName);
            assert(bus != NULL);
            std::string result = "";
            result += bus->name() + ": ";
            bool isFirstSegment = true;
            for (int j = 0; j < bus->segmentCount(); ++j) {
                if (!isFirstSegment)
                    result += " ";
                result += bus->segment(j)->name();
                isFirstSegment = false;
            }
            parent().interpreter()->setResult(result);
            return true;
        }
        return false;
    }
References assert, TTAMachine::Machine::busNavigator(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), CustomCommand::interpreter(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::Component::name(), TTAMachine::Segment::name(), SimControlLanguageSubCommand::parent(), TTAMachine::Bus::segment(), TTAMachine::Bus::segmentCount(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), SimControlLanguageCommand::simulatorFrontend(), SimulatorToolbox::textGenerator(), and Texts::TXT_BUS_NOT_FOUND.
The documentation for this class was generated from the following file:
InfoCommand.cc