OpenASIP: BEMTools Class Reference
BEMTools Class Reference
#include <BEMTools.hh>
Static Public Member Functions
static unsigned encodingWidth (unsigned encoding, unsigned extrabits)
static unsigned extrabits (unsigned encoding, unsigned width)
Detailed Description
Definition at line 40 of file BEMTools.hh.
Member Function Documentation
encodingWidth()
unsigned BEMTools::encodingWidth (unsigned encoding, unsigned extrabits) static
Returns bit width required by the encoding and extrabits combination.
Note
encoding value of zero translates to width of zero.
Definition at line 46 of file BEMTools.cc.
{
    return MathTools::bitLength(encoding) + extrabits;
}
References MathTools::bitLength(), and extrabits().
Referenced by BEMTester::canAddComponentPriorityEncoding().
extrabits()
unsigned BEMTools::extrabits (unsigned encoding, unsigned width) static
Calculates the extra bits (zeroes) of the given encoding.
For example:
*  (encoding, width) = (3, 5) ->  |00011| -> return 3.
*
Parameters
encoding The encoding value.
width The number of bits the encoding occupies. Must be at least or more than required bits needed for the value. Must greater than 0.
Definition at line 64 of file BEMTools.cc.
{
    assert(width >= MathTools::bitLength(encoding));
    assert(width > 0);
    return width - MathTools::bitLength(encoding);
}
References assert, and MathTools::bitLength().
Referenced by encodingWidth().
The documentation for this class was generated from the following files:
BEMTools.hh
BEMTools.cc