OpenASIP: StrictMatchRFEstimator Class Reference
StrictMatchRFEstimator Class Reference
Public Member Functions
StrictMatchRFEstimator (const std::string &name)
virtual ~StrictMatchRFEstimator ()
DESCRIPTION ("Simple RF cost estimator plugin that estimates costs of RFs " "simply by looking up direct matches from HDB. In case there's " "no cost data available for the given RF, it's unable to estimate " "it by using linearization etc.")
bool estimateArea (const TTAMachine::BaseRegisterFile &, const IDF::RFImplementationLocation &implementation, AreaInGates &area, HDB::HDBManager &hdb)
bool estimatePortWriteDelay (const TTAMachine::RFPort &, const IDF::RFImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimatePortReadDelay (const TTAMachine::RFPort &, const IDF::RFImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimateMaximumComputationDelay (const TTAMachine::BaseRegisterFile &, const IDF::RFImplementationLocation &implementation, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimateEnergy (const TTAMachine::BaseRegisterFile &rf, const IDF::RFImplementationLocation &implementation, const TTAProgram::Program &, const ExecutionTrace &trace, EnergyInMilliJoules &energy, HDB::HDBManager &hdb)
Public Member Functions inherited from CostEstimator::RFCostEstimationPlugin
RFCostEstimationPlugin (const std::string &name)
virtual ~RFCostEstimationPlugin ()
Public Member Functions inherited from CostEstimator::CostEstimationPlugin
CostEstimationPlugin (const std::string &name)
virtual ~CostEstimationPlugin ()
virtual std::string name () const
virtual std::string description () const
Additional Inherited Members
Protected Attributes inherited from CostEstimator::CostEstimationPlugin
std::string name_
the name of the plugin class in the HDB; used to identify cost data
Detailed Description
Definition at line 46 of file StrictMatchRFEstimator.cc.
Constructor & Destructor Documentation
StrictMatchRFEstimator()
StrictMatchRFEstimator::StrictMatchRFEstimator (const std::string & name) inline
Definition at line 48 of file StrictMatchRFEstimator.cc.
                                                  :
        RFCostEstimationPlugin(name) {
    }
~StrictMatchRFEstimator()
virtual StrictMatchRFEstimator::~StrictMatchRFEstimator () inline virtual
Definition at line 52 of file StrictMatchRFEstimator.cc.
{
    }
Member Function Documentation
DESCRIPTION()
StrictMatchRFEstimator::DESCRIPTION ("Simple RF cost estimator plugin that estimates costs of RFs " "simply by looking up direct matches from HDB. In case there's " "no cost data available for the given RF, it 's unable to estimate " "it by using linearization etc.")
estimateArea()
bool StrictMatchRFEstimator::estimateArea (const TTAMachine::BaseRegisterFile & , const IDF::RFImplementationLocation & implementation, AreaInGates & area, HDB::HDBManager & hdb) inline virtual
Estimates the register file's area by fetching cost data named 'area' from HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 67 of file StrictMatchRFEstimator.cc.
{
//#define DEBUG_AREA_ESTIMATION
        try {
            // simply fetch the area data of the FU, if any
            DataObject areaFromDB = hdb.rfCostEstimationData(
                "area", implementation.id(), name_);
            area = areaFromDB.doubleValue();
#ifdef DEBUG_AREA_ESTIMATION
            Application::logStream()
                << rf.name() << " area " << area << std::endl;
#endif
            return true;
        } catch (const KeyNotFound&) {
            // if no area data found, don't even try to estimate the area
            // somehow
            Application::logStream() << "No area data found in HDB.";
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), implementation, Application::logStream(), CostEstimator::CostEstimationPlugin::name_, and HDB::HDBManager::rfCostEstimationData().
estimateEnergy()
bool StrictMatchRFEstimator::estimateEnergy (const TTAMachine::BaseRegisterFile & rf, const IDF::RFImplementationLocation & implementation, const TTAProgram::Program & , const ExecutionTrace & trace, EnergyInMilliJoules & energy, HDB::HDBManager & hdb) inline virtual
Estimates the energy consumed by given RF.
Estimate is done by computing the sum of all register file access type energies and RF idle energy. Register file access energies are stored with entries named 'rf_access_energy Nr Nw'. Nr is the number of read accesses, Nw the number of write accesses. For example, 'rf_access_energy 1 3' is the name of entry which tells how much energy is consumed by the RF in case RF is accessed simultaneously once for reading and trice for writing. Idle energy is stored in entry 'rf_idle_energy'.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 230 of file StrictMatchRFEstimator.cc.
{
//#define DEBUG_ENERGY_ESTIMATION
        energy = 0.0;
        ClockCycleCount cyclesWithRFAccess = 0;
#ifdef DEBUG_ENERGY_ESTIMATION
        Application::logStream()
            << "## register file " << rf.name() << ": " << std::endl;
#endif
        try {
            ExecutionTrace::ConcurrentRFAccessCountList* accessList =
                trace.registerFileAccessCounts(rf.name());
            for (ExecutionTrace::ConcurrentRFAccessCountList::
                     const_iterator i = accessList->begin();
                 i != accessList->end(); ++i) {
                const ExecutionTrace::ConcurrentRFAccessCount& accessCount =
                    *i;
                const std::size_t reads = accessCount.get<0>();
                const std::size_t writes = accessCount.get<1>();
                const ClockCycleCount count = accessCount.get<2>();
                const std::string dataName =
                    std::string("rf_access_energy ") +
                    Conversion::toString(reads) + " " +
                    Conversion::toString(writes);
                try {
                    DataObject energyFromDB = hdb.rfCostEstimationData(
                        dataName, implementation.id(), name_);
                    EnergyInMilliJoules energyOfAccess =
                        energyFromDB.doubleValue()*count;
#ifdef DEBUG_ENERGY_ESTIMATION
                    Application::logStream()
                        << "## reads " << accessCount.get<0>() << " "
                        << "writes " << accessCount.get<1>() << " = "
                        << energyFromDB.doubleValue() << " times "
                        << count << " = " << energyOfAccess << std::endl;
#endif
                    energy += energyOfAccess;
                    cyclesWithRFAccess += count;
                } catch (const KeyNotFound&) {
                    // if no data found, don't even try to estimate the area
                    delete accessList;
                    accessList = NULL;
                    Application::logStream()
                        << "Cost estimation data '" << dataName
                        << "' not found in HDB." << std::endl;
                    return false;
                } catch (const Exception& e) {
                    delete accessList;
                    accessList = NULL;
                    debugLog(e.errorMessage());
                    return false;
                }
            }
            delete accessList;
            accessList = NULL;
        } catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        // add the cost of RF idling
        const ClockCycleCount idleCycles =
            trace.simulatedCycleCount() - cyclesWithRFAccess;
        const std::string dataName = std::string("rf_idle_energy");
        try {
            DataObject energyFromDB = hdb.rfCostEstimationData(
                dataName, implementation.id(), name_);
            EnergyInMilliJoules idleEnergy =
                energyFromDB.doubleValue()*idleCycles;
#ifdef DEBUG_ENERGY_ESTIMATION
            Application::logStream()
                << "## idle energy " << energyFromDB.doubleValue() << " times "
                << idleCycles << " = " << idleEnergy << std::endl;
#endif
            energy += idleEnergy;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                        << "Cost estimation data '" << dataName
                        << "' not found in HDB." << std::endl;
            return false;
        } catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        return true;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), implementation, Application::logStream(), TTAMachine::Component::name(), CostEstimator::CostEstimationPlugin::name_, ExecutionTrace::registerFileAccessCounts(), HDB::HDBManager::rfCostEstimationData(), ExecutionTrace::simulatedCycleCount(), Conversion::toString(), and trace.
estimateMaximumComputationDelay()
bool StrictMatchRFEstimator::estimateMaximumComputationDelay (const TTAMachine::BaseRegisterFile & , const IDF::RFImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file maximum computation delay by fetching cost data named 'computation_delay' from HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 186 of file StrictMatchRFEstimator.cc.
{
        try {
            // simply fetch the delay data of the RF, if any
            DataObject delayFromDB = hdb.rfCostEstimationData(
                "computation_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
#ifdef DEBUG_DELAY_ESTIMATION
            Application::logStream()
                << rf.name() << " computation delay " << delay << std::endl;
#endif
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No computation_delay cost data found for RF "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), implementation, Application::logStream(), CostEstimator::CostEstimationPlugin::name_, and HDB::HDBManager::rfCostEstimationData().
estimatePortReadDelay()
bool StrictMatchRFEstimator::estimatePortReadDelay (const TTAMachine::RFPort & , const IDF::RFImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file port read delay by fetching cost data named 'output_delay' from HDB.
Assumes that all ports have the same output delay, that is, there is only one 'output_delay' entry for a RF in HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 149 of file StrictMatchRFEstimator.cc.
{
        try {
            // simply fetch the delay data of the RF port, if any
            DataObject delayFromDB = hdb.rfCostEstimationData(
                "output_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
#ifdef DEBUG_DELAY_ESTIMATION
            Application::logStream()
                << port.name() << " read delay " << delay << std::endl;
#endif
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No output_delay cost data found for RF "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), implementation, Application::logStream(), CostEstimator::CostEstimationPlugin::name_, and HDB::HDBManager::rfCostEstimationData().
estimatePortWriteDelay()
bool StrictMatchRFEstimator::estimatePortWriteDelay (const TTAMachine::RFPort & , const IDF::RFImplementationLocation & implementation, DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file port write delay by fetching cost data named 'input_delay' from HDB.
Assumes that all ports have the same input delay, that is, there is only one 'input_delay' entry for a RF in HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 108 of file StrictMatchRFEstimator.cc.
{
//#define DEBUG_DELAY_ESTIMATION
        try {
            // simply fetch the delay data of the RF port, if any
            DataObject delayFromDB = hdb.rfCostEstimationData(
                "input_delay", implementation.id(), name_);
            delay = delayFromDB.doubleValue();
#ifdef DEBUG_DELAY_ESTIMATION
            Application::logStream()
                << port.name() << " write delay " << delay << std::endl;
#endif
            return true;
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "No input_delay cost data found for RF "
                << implementation.id() << ", plugin " << name_ << std::endl;
            return false;
        } catch (const Exception& e) {
            // for example, if doubleValue() conversion failed, then it's
            // a problem with HDB contents
            debugLog(e.errorMessage());
            return false;
        }
        return false;
    }
References debugLog, DataObject::doubleValue(), Exception::errorMessage(), implementation, Application::logStream(), CostEstimator::CostEstimationPlugin::name_, and HDB::HDBManager::rfCostEstimationData().
The documentation for this class was generated from the following file:
StrictMatchRFEstimator.cc