OpenASIP: TTAMachine::Machine Class Reference
TTAMachine::Machine Class Reference
#include <Machine.hh>
Classes
class ComponentContainer
class Navigator
Public Types
enum Extension { ZERO , SIGN }
typedef Navigator< Bus > BusNavigator
Navigator type for BusNavigator.
typedef Navigator< Socket > SocketNavigator
Navigator type for SocketNavigator.
typedef Navigator< FunctionUnit > FunctionUnitNavigator
Navigator type for FunctionUnitNavigator.
typedef Navigator< AddressSpace > AddressSpaceNavigator
Navigator type for AddressSpaceNavigator.
typedef Navigator< Bridge > BridgeNavigator
Navigator type for BridgeNavigator.
typedef Navigator< ImmediateUnit > ImmediateUnitNavigator
Navigator type for ImmediateUnitNavigator.
typedef Navigator< InstructionTemplate > InstructionTemplateNavigator
Navigator type for InstructionTemplateNavigator.
typedef Navigator< RegisterFile > RegisterFileNavigator
Navigator type for RegisterFileNavigator.
typedef Navigator< ImmediateSlot > ImmediateSlotNavigator
Navigator type for ImmediateSlotNavigator.
typedef Navigator< OperationTriggeredFormat > OperationTriggeredFormatNavigator
Navigator type for OperationTriggeredFormatNavigator.
Public Member Functions
Machine ()
Machine (const Machine &old)
virtual ~Machine ()
virtual bool isUniversalMachine () const
virtual void addBus (Bus &bus)
virtual void addSocket (Socket &socket)
void addUnit (Unit &unit)
virtual void addFunctionUnit (FunctionUnit &unit)
virtual void addImmediateUnit (ImmediateUnit &unit)
virtual void addRegisterFile (RegisterFile &unit)
virtual void addAddressSpace (AddressSpace &as)
virtual void addBridge (Bridge &bridge)
virtual void addInstructionTemplate (InstructionTemplate &instrTempl)
virtual void addOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void addImmediateSlot (ImmediateSlot &slot)
virtual void setGlobalControl (ControlUnit &unit)
virtual void unsetGlobalControl ()
virtual ControlUnit * controlUnit () const
virtual void removeBus (Bus &bus)
virtual void removeSocket (Socket &socket)
virtual void removeUnit (Unit &unit)
virtual void removeFunctionUnit (FunctionUnit &unit)
virtual void removeImmediateUnit (ImmediateUnit &unit)
virtual void removeRegisterFile (RegisterFile &unit)
virtual void deleteBridge (Bridge &bridge)
virtual void deleteInstructionTemplate (InstructionTemplate &instrTempl)
virtual void deleteOperationTriggeredFormat (OperationTriggeredFormat &format)
virtual void deleteImmediateSlot (ImmediateSlot &slot)
virtual void deleteAddressSpace (AddressSpace &as)
void setBusPosition (const Bus &bus, int newPosition)
MachineTester & machineTester () const
bool alwaysWriteResults () const
bool triggerInvalidatesResults () const
bool isFUOrdered () const
void setAlwaysWriteResults (bool)
void setTriggerInvalidatesResults (bool)
void setFUOrdered (bool)
int maximumLatency () const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
virtual void copyFromMachine (Machine &machine)
void writeToADF (const std::string &adfFileName) const
TCEString hash () const
bool hasOperation (const TCEString &opName) const
bool isRISCVMachine () const
virtual BusNavigator busNavigator () const
virtual SocketNavigator socketNavigator () const
virtual FunctionUnitNavigator functionUnitNavigator () const
virtual AddressSpaceNavigator addressSpaceNavigator () const
virtual BridgeNavigator bridgeNavigator () const
virtual ImmediateUnitNavigator immediateUnitNavigator () const
virtual InstructionTemplateNavigator instructionTemplateNavigator () const
virtual RegisterFileNavigator registerFileNavigator () const
virtual ImmediateSlotNavigator immediateSlotNavigator () const
virtual OperationTriggeredFormatNavigator operationTriggeredFormatNavigator () const
bool isLittleEndian () const
void setLittleEndian (bool flag)
bool is64bit () const
void set64bits (bool flag)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static Machine * loadFromADF (const std::string &adfFileName)
Static Public Attributes
static const std::string OSNAME_MACHINE = "machine"
ObjectState name for Machine.
static const std::string OSKEY_ALWAYS_WRITE_BACK_RESULTS = "always-write-back"
ObjectState attribute key for always-write-back-results.
static const std::string OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS = "trigger-invalidates"
ObjectState attribute key for trigger-invalidates-old-results.
static const std::string OSKEY_FUNCTION_UNITS_ORDERED = "fu-ordered"
ObjectState attribute key for function units ordered in order of their sequential presence in ADF.
Private Member Functions
Machine & operator= (const Machine &)
Assignment not allowed.
template<typename ContainerType , typename ComponentType >
void addComponent (ContainerType &container, ComponentType &toAdd)
template<typename ContainerType , typename ComponentType >
void addRegisteredComponent (ContainerType &container, ComponentType &toAdd)
template<typename ContainerType , typename ComponentType >
void removeComponent (ContainerType &container, ComponentType &toRemove)
template<typename ContainerType , typename ComponentType >
void deleteComponent (ContainerType &container, ComponentType &toDelete)
Static Private Member Functions
template<typename ContainerType >
static void saveComponentStates (ContainerType &container, ObjectState *parent)
Private Attributes
ComponentContainer< Bus > busses_
Contains all the busses attached to the machine.
ComponentContainer< Socket > sockets_
Contains all the sockets attached to the machine.
ComponentContainer< InstructionTemplate > instructionTemplates_
Contains all the instruction templates of the machine.
ComponentContainer< RegisterFile > registerFiles_
Contains all the register files of the machine.
ComponentContainer< ImmediateUnit > immediateUnits_
Contains all the immediate units of the machine.
ComponentContainer< FunctionUnit > functionUnits_
Contains all the function units of the machine.
ComponentContainer< AddressSpace > addressSpaces_
Contains all the address spaces of the machine.
ComponentContainer< Bridge > bridges_
Contains all the bridges of the machine.
ComponentContainer< ImmediateSlot > immediateSlots_
Contains all the immediate slots of the machine.
ComponentContainer< OperationTriggeredFormat > operationTriggeredFormats_
Contains all the OTA Formats of the machine.
ControlUnit * controlUnit_
Global control unit.
bool doValidityChecks_
Tells whether to do validity checks or not.
MachineTester * machineTester_
Machine tester for the machine.
DummyMachineTester * dummyMachineTester_
Dummy machine tester for the machine.
const std::string EMPTY_ITEMP_NAME_
bool alwaysWriteResults_
bool triggerInvalidatesResults_
bool fuOrdered_
bool littleEndian_
bool bitness64_
Detailed Description
Represents a complete TTA processor.
Definition at line 73 of file Machine.hh.
Member Typedef Documentation
AddressSpaceNavigator
typedef Navigator<AddressSpace> TTAMachine::Machine::AddressSpaceNavigator
Navigator type for AddressSpaceNavigator.
Definition at line 219 of file Machine.hh.
BridgeNavigator
typedef Navigator<Bridge> TTAMachine::Machine::BridgeNavigator
Navigator type for BridgeNavigator.
Definition at line 221 of file Machine.hh.
BusNavigator
typedef Navigator<Bus> TTAMachine::Machine::BusNavigator
Navigator type for BusNavigator.
Definition at line 213 of file Machine.hh.
FunctionUnitNavigator
typedef Navigator<FunctionUnit> TTAMachine::Machine::FunctionUnitNavigator
Navigator type for FunctionUnitNavigator.
Definition at line 217 of file Machine.hh.
ImmediateSlotNavigator
typedef Navigator<ImmediateSlot> TTAMachine::Machine::ImmediateSlotNavigator
Navigator type for ImmediateSlotNavigator.
Definition at line 229 of file Machine.hh.
ImmediateUnitNavigator
typedef Navigator<ImmediateUnit> TTAMachine::Machine::ImmediateUnitNavigator
Navigator type for ImmediateUnitNavigator.
Definition at line 223 of file Machine.hh.
InstructionTemplateNavigator
typedef Navigator<InstructionTemplate> TTAMachine::Machine::InstructionTemplateNavigator
Navigator type for InstructionTemplateNavigator.
Definition at line 225 of file Machine.hh.
OperationTriggeredFormatNavigator
typedef Navigator<OperationTriggeredFormat> TTAMachine::Machine::OperationTriggeredFormatNavigator
Navigator type for OperationTriggeredFormatNavigator.
Definition at line 232 of file Machine.hh.
RegisterFileNavigator
typedef Navigator<RegisterFile> TTAMachine::Machine::RegisterFileNavigator
Navigator type for RegisterFileNavigator.
Definition at line 227 of file Machine.hh.
SocketNavigator
typedef Navigator<Socket> TTAMachine::Machine::SocketNavigator
Navigator type for SocketNavigator.
Definition at line 215 of file Machine.hh.
Member Enumeration Documentation
Extension
enum TTAMachine::Machine::Extension
Extension mode applied to a number when it is narrower than the place where it is placed e.g. bus.
Enumerator
ZERO
Zero extension.
SIGN
Sign extension.
Definition at line 80 of file Machine.hh.
                   {
        ZERO, ///< Zero extension.
        SIGN  ///< Sign extension.
    };
Constructor & Destructor Documentation
Machine() [1/2]
TTAMachine::Machine::Machine ()
Constructor.
Definition at line 76 of file Machine.cc.
                 :
    controlUnit_(NULL), doValidityChecks_(true),
    machineTester_(new MachineTester(*this)),
    dummyMachineTester_(new DummyMachineTester(*this)),
    EMPTY_ITEMP_NAME_("no_limm"), alwaysWriteResults_(false),
    triggerInvalidatesResults_(false), fuOrdered_(false),
    littleEndian_(true), bitness64_(false) {
    new InstructionTemplate(EMPTY_ITEMP_NAME_, *this);
}
References EMPTY_ITEMP_NAME_.
Machine() [2/2]
TTAMachine::Machine::Machine (const Machine & old)
Copy constructor.
Creates a copy of the given machine.
Parameters
old The machine to be copied.
Definition at line 95 of file Machine.cc.
                                   :
    Serializable(), controlUnit_(NULL), doValidityChecks_(false),
    machineTester_(new MachineTester(*this)),
    dummyMachineTester_(new DummyMachineTester(*this)),
    littleEndian_(old.littleEndian_),
    bitness64_(old.bitness64_) {
    ObjectState* state = old.saveState();
    loadState(state);
    delete state;
    doValidityChecks_ = true;
}
References doValidityChecks_, loadState(), and saveState().
~Machine()
TTAMachine::Machine::~Machine () virtual
Destructor.
Deletes all the components of the machine as well.
Definition at line 114 of file Machine.cc.
                  {
    if (controlUnit_ != NULL) {
        delete controlUnit_;
    }
    delete machineTester_;
    delete dummyMachineTester_;
    // NOTE! other components are deleted in ComponentContainer's destructor
}
References controlUnit_, dummyMachineTester_, and machineTester_.
Member Function Documentation
addAddressSpace()
void TTAMachine::Machine::addAddressSpace (AddressSpace & as) virtual
Adds an address space into the machine.
Parameters
as AddressSpace being added.
Exceptions
ComponentAlreadyExists If an address space by the same name already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 248 of file Machine.cc.
{
    addRegisteredComponent(addressSpaces_, as);
}
References addRegisteredComponent(), and addressSpaces_.
Referenced by UniversalMachine::addAddressSpace(), and TTAMachine::AddressSpace::setMachine().
addBridge()
void TTAMachine::Machine::addBridge (Bridge & bridge) virtual
Adds a bridge into the machine.
This method should be called from Bridge constructor only since bridges are added to machine at construction. Do not call this method.
Parameters
bridge Bridge being added.
Exceptions
ComponentAlreadyExists If a bridge by the same name already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 263 of file Machine.cc.
{
    addRegisteredComponent(bridges_, bridge);
}
References addRegisteredComponent(), and bridges_.
Referenced by TTAMachine::Bridge::setMachine().
addBus()
void TTAMachine::Machine::addBus (Bus & bus) virtual
Adds a bus into the machine.
Parameters
bus Bus being added.
Exceptions
ComponentAlreadyExists If a bus or immediate slot by the same name already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 139 of file Machine.cc.
{
    // check that the name is unique among immediate slots
    if (immediateSlotNavigator().hasItem(bus.name())) {
        const string procName = "Machine::addBus";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    addComponent(busses_, bus);
}
References addComponent(), busses_, immediateSlotNavigator(), and TTAMachine::Component::name().
Referenced by UniversalMachine::addBus(), ADFCombiner::addBuses(), MachineResourceModifier::addBusesByAmount(), BlocksGCU::BlocksGCU(), ADFCombiner::createBus(), BlocksConnectIC::createBus(), VLIWConnectIC::createBus(), BlocksTranslator::CreateConnection(), loadState(), and TTAMachine::Bus::setMachine().
addComponent()
template<typename ContainerType , typename ComponentType > void TTAMachine::Machine::addComponent (ContainerType & container, ComponentType & toAdd) private
Referenced by addBus(), addFunctionUnit(), addImmediateUnit(), addRegisterFile(), and addSocket().
addFunctionUnit()
void TTAMachine::Machine::addFunctionUnit (FunctionUnit & unit) virtual
Adds the given function unit to the machine.
Parameters
unit The function unit to be added.
Exceptions
ComponentAlreadyExists If a function unit by the same name exists already.
IllegalParameters If tried to add control unit with this method.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 202 of file Machine.cc.
{
    const string procName = "Machine::addFunctionUnit";
    if (dynamic_cast<ControlUnit*>(&unit) != NULL) {
        throw IllegalParameters(__FILE__, __LINE__, procName);
    }
    if (controlUnit() != NULL && controlUnit()->name() == unit.name()) {
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    addComponent(functionUnits_, unit);
}
References addComponent(), controlUnit(), functionUnits_, and TTAMachine::Component::name().
Referenced by UniversalMachine::addFunctionUnit(), ADFCombiner::addFunctionUnits(), addUnit(), BlocksFU::BlocksFU(), FUTestbenchGenerator::createMachineState(), VectorLSGenerator::explore(), MinimalOpSetCheck::fix(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), loadState(), AddFUFromHDBDialog::onAdd(), and MachineResourceModifier::percentualFUIncrease().
addImmediateSlot()
void TTAMachine::Machine::addImmediateSlot (ImmediateSlot & slot) virtual
Adds an immediate slot to (instruction of) the machine.
Parameters
slot The immediate slot to be added.
Exceptions
ComponentAlreadyExists If an immediate slot or bus by the same name already exists in the machine.
Definition at line 299 of file Machine.cc.
{
    // check that the name is unique among buses
    if (busNavigator().hasItem(slot.name())) {
        const string procName = "Machine::addImmediateSlot";
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    addRegisteredComponent(immediateSlots_, slot);
}
References addRegisteredComponent(), busNavigator(), immediateSlots_, and TTAMachine::Component::name().
Referenced by TTAMachine::ImmediateSlot::setMachine().
addImmediateUnit()
void TTAMachine::Machine::addImmediateUnit (ImmediateUnit & unit) virtual
Adds the given immediate unit to the machine.
Parameters
unit The immediate unit to be added.
Exceptions
ComponentAlreadyExists If an immediate unit by the same name exists already.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 224 of file Machine.cc.
{
    addComponent(immediateUnits_, unit);
}
References addComponent(), and immediateUnits_.
Referenced by addUnit(), BlocksIMM::BlocksIMM(), loadState(), and AddIUFromHDBDialog::onAdd().
addInstructionTemplate()
void TTAMachine::Machine::addInstructionTemplate (InstructionTemplate & instrTempl) virtual
Adds an instruction template for the machine.
Parameters
instructionTemplate The instruction template to be added.
Exceptions
ComponentAlreadyExists If an instruction template by the same name already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 275 of file Machine.cc.
{
    addRegisteredComponent(instructionTemplates_, instrTempl);
}
References addRegisteredComponent(), and instructionTemplates_.
Referenced by TTAMachine::InstructionTemplate::setMachine().
addOperationTriggeredFormat()
void TTAMachine::Machine::addOperationTriggeredFormat (OperationTriggeredFormat & format) virtual
Adds an OTA format for the machine.
Parameters
OperationTriggeredFormat The OTA format to be added.
Exceptions
ComponentAlreadyExists If an instruction template by the same name already exists in the machine.
Definition at line 287 of file Machine.cc.
{
    addRegisteredComponent(operationTriggeredFormats_, format);
}
References addRegisteredComponent(), and operationTriggeredFormats_.
Referenced by TTAMachine::OperationTriggeredFormat::setMachine().
addRegisteredComponent()
template<typename ContainerType , typename ComponentType > void TTAMachine::Machine::addRegisteredComponent (ContainerType & container, ComponentType & toAdd) private
Referenced by addAddressSpace(), addBridge(), addImmediateSlot(), addInstructionTemplate(), and addOperationTriggeredFormat().
addRegisterFile()
void TTAMachine::Machine::addRegisterFile (RegisterFile & unit) virtual
Adds the given register file to the machine.
Parameters
unit The register file to be added.
Exceptions
ComponentAlreadyExists If a register file by the same name exists already.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 236 of file Machine.cc.
{
    addComponent(registerFiles_, unit);
}
References addComponent(), and registerFiles_.
Referenced by UniversalMachine::addRegisterFile(), ADFCombiner::addRegisterFiles(), ComponentAdder::addRegisterFiles(), addUnit(), BlocksRF::BlocksRF(), RFTestbenchGenerator::createMachineState(), VLIWConnectIC::explore(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), loadState(), AddRFFromHDBDialog::onAdd(), and MachineResourceModifier::percentualRegisterIncrease().
addressSpaceNavigator()
Machine::AddressSpaceNavigator TTAMachine::Machine::addressSpaceNavigator () const virtual
Returns a handle to the address spaces in the machine.
Returns
Handle to the address spaces in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 392 of file Machine.cc.
{
    AddressSpaceNavigator navigator(addressSpaces_);
    return navigator;
}
References addressSpaces_.
Referenced by MemorySystem::addAddressSpace(), ADFCombiner::addAddressSpaces(), ADFCombiner::addFunctionUnits(), TTAMachine::AddressSpace::AddressSpace(), llvm::LLVMTCEBuilder::addressSpaceById(), TTAMachine::NullMachine::addressSpaceNavigator(), TTAProgram::TPEFProgramFactory::build(), UniversalMachine::dataAddressSpace(), MachineInfo::defaultDataAddressSpace(), AddASCmd::Do(), llvm::LLVMTCEBuilder::emitOperationMacro(), InfoProcCommand::execute(), VectorLSGenerator::explore(), CodeSectionCreator::finalize(), TTAProgram::TPEFProgramFactory::findAddressSpace(), MachineResourceManager::findDataAddressSpace(), ProgramImageGenerator::generateDataImage(), llvm::LLVMTCEBuilder::initDataSections(), AddWatchDialog::initialize(), SimulatorFrontend::initializeMemorySystem(), UniversalMachine::instructionAddressSpace(), AddressSpaceDialog::isFreeId(), TTAMachine::FunctionUnit::loadState(), main(), AddressSpacesDialog::onAdd(), AddWatchDialog::onASChoice(), AddressSpaceDialog::onOK(), GCUDialog::onOK(), FUDialog::onSetAddressSpace(), printLatexAddressSpaceDescription(), AddressSpacesDialog::selectedAS(), TTAMachine::AddressSpace::setNumericalIds(), MemorySystem::shareMemoriesWith(), llvm::TCETargetLowering::TCETargetLowering(), FUDialog::updateAddressSpaceChoice(), GCUDialog::updateAddressSpaceChoice(), and AddressSpacesDialog::updateASList().
addSocket()
void TTAMachine::Machine::addSocket (Socket & socket) virtual
Adds a socket into the machine.
Parameters
socket Socket being added.
Exceptions
ComponentAlreadyExists If a socket by the same name already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 157 of file Machine.cc.
{
    addComponent(sockets_, socket);
}
References addComponent(), and sockets_.
Referenced by ADFCombiner::addBuses(), UniversalMachine::addSocket(), BlocksALUPair::BlocksALUPair(), BlocksFU::BlocksFU(), BlocksGCU::BlocksGCU(), BlocksIMM::BlocksIMM(), BlocksLSUPair::BlocksLSUPair(), BlocksMULPair::BlocksMULPair(), BlocksRF::BlocksRF(), ADFCombiner::connectVectorLSU(), ADFCombiner::createPortsAndSockets(), VLIWConnectIC::explore(), loadState(), and TTAMachine::Socket::setMachine().
addUnit()
void TTAMachine::Machine::addUnit (Unit & unit)
Adds a unit into the machine.
Use methods intended to add particular unit types like addFunctionUnit, addRegisterFile and addImmediateUnit if possible. Global control unit must be set using setGlobalControl function.
Parameters
unit Unit being added.
Exceptions
ComponentAlreadyExists If a unit by the same name and type already exists in the machine.
IllegalParameters If ControlUnit is tried to add with this method.
Definition at line 175 of file Machine.cc.
{
    FunctionUnit* fu = dynamic_cast<FunctionUnit*>(&unit);
    ImmediateUnit* iu = dynamic_cast<ImmediateUnit*>(&unit);
    RegisterFile* rf = dynamic_cast<RegisterFile*>(&unit);
    if (fu != NULL) {
        addFunctionUnit(*fu);
    } else if (iu != NULL) {
        addImmediateUnit(*iu);
    } else if (rf != NULL) {
        addRegisterFile(*rf);
    } else {
        const string procName = "Machine::addUnit";
        throw IllegalParameters(__FILE__, __LINE__, procName);
    }
}
References addFunctionUnit(), addImmediateUnit(), and addRegisterFile().
Referenced by TTAMachine::Unit::setMachine().
alwaysWriteResults()
bool TTAMachine::Machine::alwaysWriteResults () const
Returns true if result value always needs to be written to GPR.
Definition at line 948 of file Machine.cc.
{
    return alwaysWriteResults_;
}
References alwaysWriteResults_.
Referenced by CycleLookBackSoftwareBypasser::bypassNode(), and BFLateBypasses::operator()().
bridgeNavigator()
Machine::BridgeNavigator TTAMachine::Machine::bridgeNavigator () const virtual
Returns a handle to the bridges in the machine.
Returns
Handle to the bridges in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 404 of file Machine.cc.
{
    BridgeNavigator navigator(bridges_);
    return navigator;
}
References bridges_.
Referenced by TTAMachine::Bridge::adjustChainDirection(), TTAMachine::Bridge::Bridge(), TTAMachine::NullMachine::bridgeNavigator(), FullyConnectedCheck::canFix(), BEMValidator::checkSourceField(), AddBridgeCmd::Do(), MachineEditPartFactory::getBusChains(), loadState(), BridgeDialog::onOK(), TTAMachine::Bridge::setFirstOfChain(), BEMGenerator::sourceBridge(), BEMGenerator::sourceBridgeCount(), TTAMachine::Bus::unsetMachine(), and DefaultICGenerator::verifyCompatibility().
busNavigator()
Machine::BusNavigator TTAMachine::Machine::busNavigator () const virtual
Returns a handle to the busses in the machine.
Returns
Handle to the busses in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 356 of file Machine.cc.
{
    BusNavigator navigator(busses_);
    return navigator;
}
References busses_.
Referenced by ADFCombiner::addAllGuardsToConnectionBuses(), CodeCompressorPlugin::addBitsForMoveSlot(), ADFCombiner::addBuses(), MachineResourceModifier::addBusesByAmount(), SimpleICOptimizer::addConnections(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), BEMGenerator::addEncodings(), DefaultICGenerator::addICToNetlist(), addImmediateSlot(), TTAMachine::InstructionTemplate::addSlot(), ImmediateGenerator::addSplitInsTemplate(), BEMGenerator::addSubfields(), BEMGenerator::addTopLevelFields(), MachineResourceModifier::analyzeBuses(), ResourceConstraintAnalyzer::analyzeMoveNode(), TDGen::analyzeRegisters(), FullyConnectedCheck::attachSocketToAllBusses(), MachineStateBuilder::buildMachineState(), BusBroker::buildResources(), ITemplateBroker::buildResources(), TTAMachine::NullMachine::busNavigator(), llvm::TCETargetMachine::calculateSupportedImmediates(), MachineInfo::canEncodeImmediateInteger(), FullyConnectedCheck::canFix(), ProgrammabilityValidator::checkBooleanRegister(), RemoveUnconnectedComponents::checkBuses(), TTAMachine::FunctionUnit::cleanupGuards(), TTAMachine::FUPort::cleanupGuards(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), FullyConnectedCheck::connectFUPort(), ADFCombiner::connectRegisterFiles(), ADFCombiner::connectVectorLSU(), BasicBlockPass::copyRMToBB(), BlocksConnectIC::createBus(), VLIWConnectIC::createBus(), TTAProgram::ProgramWriter::createCodeSection(), BlocksTranslator::CreateConnection(), llvm::LLVMTCEBuilder::createGuard(), ProgramDependenceGraph::createJump(), DefaultICGenerator::createSignalsForIC(), BlocksTranslator::Deinitialize(), TTAMachine::RegisterFile::deleteGuards(), AddBridgeCmd::Do(), AddBusCmd::Do(), PasteComponentCmd::Do(), CodeCompressorPlugin::encodeMove(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), InfoBussesCommand::execute(), InfoSegmentsCommand::execute(), InfoProcCommand::execute(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), CostEstimator::Estimator::findAllICPaths(), findBooleanGuard(), TTAProgram::TPEFProgramFactory::findBus(), findBus(), MachineResourceManager::findBusWidth(), ProgrammabilityValidator::findGlobalConnectionRegister(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), RegisterQuantityCheck::findGuardRegisters(), ADFCombiner::findGuards(), MachineConnectivityCheck::findRoutes(), RegisterCopyAdder::findTempRegisters(), SimulatorFrontend::finishSimulation(), ProGe::ProcessorGenerator::generateGlobalsPackage(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProgramImageGenerator::generateProgramImage(), DefaultICGenerator::generateSocketsAndMuxes(), MachineEditPartFactory::getBusChains(), DisassemblyGridTable::GetColLabelValue(), DisassemblyGridTable::GetNumberCols(), DisassemblyGridTable::GetValue(), BusTracker::handleEvent(), MachineConnectivityCheck::hasConditionalMoves(), TTAMachine::ControlUnit::hasLocalGuardLatencyOfZero(), MachineConnectivityCheck::immBits(), TTAMachine::ImmediateSlot::ImmediateSlot(), AlmaIFIntegrator::initAlmaifBlock(), TTAProgram::TPEFResourceUpdater::initCache(), AddWatchDialog::initialize(), MachineResourceManager::initResourceSection(), TTAMachine::RegisterFile::isUsedAsGuard(), ProgrammabilityValidator::listConnections(), TTAMachine::Bridge::loadState(), loadState(), TTAMachine::Socket::loadState(), MachineInfo::longestGuardLatency(), CostEstimator::Estimator::longestPath(), MachineAnalysis::MachineAnalysis(), MachineConnectivityCheck::maxSIMMCount(), MinimizeMachine::minimizeBuses(), BEMValidator::needsSourceField(), ImmediateSlotDialog::onAddSlot(), TemplateListDialog::onAddSlot(), ProDeBusOrderDialog::onBusSelectionChanged(), ProDeBusOrderDialog::onDown(), BridgeDialog::onInputBus(), BridgeDialog::onOK(), BusDialog::onOK(), TemplateSlotDialog::onOK(), ProDeBusOrderDialog::onUp(), TTAMachine::Bus::position(), MachineResourceModifier::reduceBuses(), MachineResourceManager::registerFileIndexReference(), ImmInfo::registerImmediateLoadWidth(), SimpleICOptimizer::removeAllConnections(), MachineResourceModifier::removeBuses(), ConnectionSweeper::removeConnection(), HDB::RFArchitecture::RFArchitecture(), HDB::RFArchitecture::RFArchitecture(), MachineResourceManager::rFPortOrFUIndexReference(), ProGe::RV32MicroCodeGenerator::RV32MicroCodeGenerator(), SocketDialog::segment(), setBusPosition(), TTAMachine::ImmediateSlot::setName(), ProximMachineStateWindow::setUtilizationHighlights(), FullyConnectedCheck::socketAttachedToAllBusses(), MachineInfo::supportsBoolRegisterGuardedJumps(), MachineInfo::supportsPortGuardedJump(), MachineInfo::supportsPortGuardedJumps(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), MachineConnectivityCheck::totalConnectionCount(), TemplateSlotDialog::TransferDataToWindow(), UniversalMachine::universalBus(), TTAMachine::ImmediateUnit::unsetMachine(), BridgeDialog::updateBusChoices(), ProDeBusOrderDialog::updateBusList(), SocketDialog::updateConnected(), TemplateListDialog::updateSlotList(), BEMValidator::validate(), DefaultICGenerator::verifyCompatibility(), DefaultICGenerator::writeBusDumpCode(), DefaultICGenerator::writeBustraceExportCode(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeInstructionTemplateProcedures(), DefaultICGenerator::writeInterconnectionNetwork(), TDGen::writeMoveImmediateDefs(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), DefaultDecoderGenerator::writeSocketCntrlSignals(), DefaultDecoderGenerator::writeSquashSignalGenerationProcesses(), and DefaultDecoderGenerator::writeSquashSignals().
controlUnit()
ControlUnit * TTAMachine::Machine::controlUnit () const virtual
Returns the control unit of the machine.
Returns null pointer if there is no control unit in the machine.
Returns
The control unit of the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 345 of file Machine.cc.
{
    return controlUnit_;
}
References controlUnit_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), addFunctionUnit(), ADFCombiner::addFunctionUnits(), ProGe::NetlistGenerator::addGCUToNetlist(), DefaultICGenerator::addICToNetlist(), ProGe::ProcessorWrapperBlock::addInstructionMemory(), ProGe::RV32MicroCodeGenerator::addIPorts(), ImmediateAnalyzer::analyze(), MachineStateBuilder::buildMachineState(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), OutputFUBroker::buildResources(), MachineConnectivityCheck::busConnectedToAnyFU(), MachineConnectivityCheck::busConnectedToDestination(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), MachineValidator::checkGCUExists(), MachineValidator::checkGCUHasAddressSpace(), MachineValidator::checkIMemAddrWidth(), MachineValidator::checkJumpAndCallOperandBindings(), MachineValidator::checkOperandBindings(), MachineValidator::checkProgramCounterPort(), MachineValidator::checkRAPortHasSameWidthAsPCPort(), MachineValidator::checkReturnAddressPort(), MachineResourceManager::codeAddressSpace(), CompiledSimCodeGenerator::CompiledSimCodeGenerator(), DefaultDecoderGenerator::completeDecoderBlock(), BasicBlockPass::copyRMToBB(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::CodeGenerator::createBreakOperation(), TTAProgram::CodeGenerator::createForLoopBufferInit(), ProgramDependenceGraph::createJump(), TTAProgram::CodeGenerator::createSchedYieldProcedure(), TTAProgram::CodeGenerator::createTerminalFUPort(), TTAProgram::CodeGenerator::createWhileLoopBufferInit(), MachineInfo::defaultDataAddressSpace(), AddGCUCmd::Do(), PasteComponentCmd::Do(), llvm::LLVMTCEBuilder::emitReturn(), ProGe::CUOpcodeGenerator::encodings(), InfoPortsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), BasicBlockPass::executeDDGPass(), CopyingDelaySlotFiller::fillDelaySlots(), CompiledSimCodeGenerator::findBasicBlocks(), ProgrammabilityValidator::findConnections(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), ITemplateBroker::findITemplates(), SimulatorFrontend::findPort(), TTAProgram::TPEFProgramFactory::findPort(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), TTASimulationController::findProgramExitPoints(), ControlFlowGraph::findRelJumpDistance(), BasicBlockScheduler::findTrigger(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), MachineConnectivityCheck::fromRfConnected(), TTAProgram::TPEFResourceUpdater::functionUnit(), TTAProgram::TPEFResourceUpdater::functionUnitPort(), MachineResourceManager::functionUnitPortResource(), CompiledSimulation::FUPortValue(), ProGe::CUOpcodeGenerator::gcuOpcodeWidth(), DefaultICDecoderGenerator::generate(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProGe::ProGeUI::generateIDF(), ProgramImageGenerator::generateProgramImage(), llvm::LLVMTCEBuilder::getHWOperation(), CopyingDelaySlotFiller::getMove(), MachineInfo::getPortBindingsOfOperation(), BF2ScheduleFront::getPreferredLimits(), MachineEditPartFactory::getUnits(), TTAProgram::Move::guardLatency(), CallsToJumps::handleControlFlowGraph(), ProcedureTransferTracker::handleEvent(), AbsoluteToRelativeJumps::handleProcedure(), hasOperation(), ProGe::ProcessorGenerator::iMemAddressWidth(), ProGe::ProcessorGenerator::iMemWidth(), MachineResourceManager::indexResource(), llvm::LLVMTCEBuilder::initDataSections(), CopyingDelaySlotFiller::initialize(), SimulatorFrontend::initializeMemorySystem(), ProGe::NetlistGenerator::instructionMemory(), DefaultICGenerator::isGcuPort(), isInstructionMemory(), BFOptimization::jumpGuardAvailableCycle(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadMachine(), TTAMachine::RegisterGuard::loadState(), loadState(), MachineInfo::longestGuardLatency(), ProGe::LoopBufferBlock::LoopBufferBlock(), main(), ProGe::RV32MicroCodeGenerator::mapFunctionUnit(), ScheduleEstimator::maximumSizeOfBB(), CompiledSimCodeGenerator::maxLatency(), MachineInfo::maxLatency(), DefaultDecoderGenerator::opcode(), DefaultDecoderGenerator::opcodeWidth(), printLatexAddressSpaceDescription(), printLatexFunctionUnitDescription(), ProgrammabilityValidator::ProgrammabilityValidator(), MachineConnectivityCheck::raConnected(), ProGe::ProGeUI::readImemParameters(), TTAMachine::RegisterGuard::RegisterGuard(), ProximPortWindow::reinitialize(), TTAProgram::Program::replaceUniversalAddressSpaces(), MachineConnectivityCheck::requiredImmediateWidth(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), DataDependenceGraph::sanityCheck(), SequentialScheduler::scheduleMove(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), TTAMachine::RegisterFile::setGuardLatency(), CodeCompressorPlugin::setImemWidth(), CodeCompressorPlugin::setMachine(), DataDependenceGraph::setMachine(), SimpleIfConverter::SimpleIfConverter(), SimulatorFrontend::state(), MachineInfo::supportsBoolRegisterGuardedJumps(), MachineInfo::supportsPortGuardedJump(), MachineInfo::supportsPortGuardedJumps(), MachineConnectivityCheck::toRfConnected(), MachineInfo::triggerIndex(), TTAMachine::AddressSpace::unsetMachine(), ProximPortWindow::update(), BEMValidator::validate(), DefaultDecoderGenerator::verifyCompatibility(), DefaultICDecoderGenerator::verifyCompatibility(), TDGen::writeBackendCode(), TDGen::writeCondBranchDefs(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeFUCntrlSignals(), TDGen::writeHWLoopDef(), DefaultICGenerator::writeInterconnectionNetwork(), llvm::LLVMTCEIRBuilder::writeMachineFunction(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
copyFromMachine()
void TTAMachine::Machine::copyFromMachine (Machine & machine) virtual
Copies state from one machine to this machine. (used for object copying).
Parameters
machine machine to copy from
Definition at line 884 of file Machine.cc.
{
    ObjectState* state = machine.saveState();
    loadState(state);
    delete state;
}
References loadState(), machine, and saveState().
Referenced by BlocksConnectICCmd::Do(), VLIWConnectICCmd::Do(), and CallExplorerPluginWindow::onRun().
deleteAddressSpace()
void TTAMachine::Machine::deleteAddressSpace (AddressSpace & as) virtual
Deletes the given address space.
Parameters
as The address space to be deleted.
Exceptions
InstanceNotFound If the machine does not have the given address space.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 623 of file Machine.cc.
{
    deleteComponent(addressSpaces_, as);
}
References addressSpaces_, and deleteComponent().
Referenced by TTAMachine::AddressSpace::unsetMachine().
deleteBridge()
void TTAMachine::Machine::deleteBridge (Bridge & bridge) virtual
Deletes the given bridge.
The machine will stay consistent after deletion.
Parameters
bridge Bridge to be deleted.
Exceptions
InstanceNotFound If the machine does not have the given bridge.
Reimplemented in TTAMachine::NullMachine.
Definition at line 587 of file Machine.cc.
{
    deleteComponent(bridges_, bridge);
}
References bridges_, and deleteComponent().
Referenced by TTAMachine::Bridge::unsetMachine().
deleteComponent()
template<typename ContainerType , typename ComponentType > void TTAMachine::Machine::deleteComponent (ContainerType & container, ComponentType & toDelete) private
Referenced by deleteAddressSpace(), deleteBridge(), deleteImmediateSlot(), deleteInstructionTemplate(), and deleteOperationTriggeredFormat().
deleteImmediateSlot()
void TTAMachine::Machine::deleteImmediateSlot (ImmediateSlot & slot) virtual
Deletes the given immediate slot.
Parameters
slot The immediate slot to be deleted.
Exceptions
InstanceNotFound If the machine does not have the given immediate slot.
Definition at line 635 of file Machine.cc.
{
    deleteComponent(immediateSlots_, slot);
}
References deleteComponent(), and immediateSlots_.
Referenced by TTAMachine::ImmediateSlot::unsetMachine().
deleteInstructionTemplate()
void TTAMachine::Machine::deleteInstructionTemplate (InstructionTemplate & instrTempl) virtual
Deletes the given instruction template.
Parameters
instrTempl The instruction template to be deleted.
Exceptions
InstanceNotFound If the machine does not have the given instruction template.
Reimplemented in TTAMachine::NullMachine.
Definition at line 599 of file Machine.cc.
{
    deleteComponent(instructionTemplates_, instrTempl);
}
References deleteComponent(), and instructionTemplates_.
Referenced by BlocksConnectIC::explore(), VLIWConnectIC::explore(), ImmediateGenerator::removeInsTemplate(), and TTAMachine::InstructionTemplate::unsetMachine().
deleteOperationTriggeredFormat()
void TTAMachine::Machine::deleteOperationTriggeredFormat (OperationTriggeredFormat & format) virtual
Deletes the given instruction template.
Parameters
instrTempl The instruction template to be deleted.
Exceptions
InstanceNotFound If the machine does not have the given instruction template.
Definition at line 611 of file Machine.cc.
{
    deleteComponent(operationTriggeredFormats_, format);
}
References deleteComponent(), and operationTriggeredFormats_.
Referenced by TTAMachine::OperationTriggeredFormat::unsetMachine().
functionUnitNavigator()
Machine::FunctionUnitNavigator TTAMachine::Machine::functionUnitNavigator () const virtual
Returns a handle to the function units in the machine.
Returns
Handle to the function units in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 380 of file Machine.cc.
{
    FunctionUnitNavigator navigator(functionUnits_);
    return navigator;
}
References functionUnits_.
Referenced by llvm::LLVMTCEBuilder::addCandidateLSUAnnotations(), ADFCombiner::addFunctionUnits(), ProGe::NetlistGenerator::addFUToNetlist(), ProGe::NetlistGenerator::addGeneratableFUsToNetlist(), DefaultDecoderGenerator::addGlockPortToDecoder(), DefaultDecoderGenerator::addLockReqPortToDecoder(), ImmediateAnalyzer::analyze(), MachineResourceModifier::analyzeFunctionUnits(), SimulationController::buildFUResourceConflictDetectors(), MachineStateBuilder::buildMachineState(), ControlFlowGraph::buildMBBFromBB(), MinimalOpSetCheck::buildMinimalOpSet(), ExecutionPipelineBroker::buildResources(), InputFUBroker::buildResources(), OutputFUBroker::buildResources(), MachineConnectivityCheck::busConnectedToAnyFU(), MachineConnectivityCheck::canBypassOpToDst(), FullyConnectedCheck::check(), AddressSpaceCheck::check(), FullyConnectedCheck::check(), OperationBindingCheck::check(), MinimalOpSetCheck::check(), MinimalOpSetCheck::check(), MachineValidator::checkFUConnections(), IDFValidator::checkFUImplementations(), RemoveUnconnectedComponents::checkFUPorts(), MachineValidator::checkOperandBindings(), MinimalOpSetCheck::checkWithIgnore(), SimulatorFrontend::compareState(), DefaultDecoderGenerator::completeDecoderBlock(), ConflictDetectionCodeGenerator::ConflictDetectionCodeGenerator(), ADFCombiner::connectVectorLSU(), ADFCombiner::copyGuards(), MachineConnectivityCheck::copyOpFUs(), llvm::LLVMTCEPOMBuilder::createFUTerminal(), AddFUArchFromADFCmd::Do(), AddFUCmd::Do(), PasteComponentCmd::Do(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitOperationMacro(), InfoPortsCommand::execute(), InfoFunitsCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), ProgrammabilityValidator::findConnections(), AutoSelectImplementationsDialog::findFUImplementations(), TTAProgram::TPEFProgramFactory::findFunctionUnit(), findFunctionUnit(), MachineInfo::findLockUnits(), AlmaIFIntegrator::findMemories(), MachineConnectivityCheck::findPossibleDestinationPorts(), MachineConnectivityCheck::findPossibleSourcePorts(), BasicBlockScheduler::findTrigger(), MachineInfo::findWidestOperand(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), MinimalOpSetCheck::fix(), MachineConnectivityCheck::fromRfConnected(), CompiledSimulation::FUMemory(), CompiledSimulation::functionUnit(), TTAMachine::NullMachine::functionUnitNavigator(), MachineResourceManager::functionUnitPortResource(), ProGeTestBenchGenerator::generate(), CompiledSimCodeGenerator::generateConstructorCode(), CompiledSimCodeGenerator::generateFUOutputUpdater(), generateHeader(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProGe::ProGeUI::generateIDF(), getFunctionUnit(), llvm::TCETargetMachine::getLoadOpcode(), MachineInfo::getOpset(), MachineInfo::getPortBindingsOfOperation(), BasicBlockScheduler::getTriggerOperand(), MachineEditPartFactory::getUnits(), DefaultDecoderGenerator::glockPortWidth(), DefaultDecoderGenerator::glockRequestWidth(), ProcessorImplementationWindow::handleSelectFUImplementation(), llvm::LLVMTCEBuilder::hasAmbiguousASpaceRefs(), hasOperation(), MachineResourceModifier::increaseAllFUsThatDiffersByAmount(), MachineResourceManager::indexResource(), TTAProgram::TPEFResourceUpdater::initCache(), llvm::LLVMTCEBuilder::initDataSections(), AddWatchDialog::initialize(), llvm::LLVMTCEIRBuilder::LLVMTCEIRBuilder(), TTAMachine::PortGuard::loadState(), loadState(), CostEstimator::Estimator::longestPath(), MachineAnalysis::MachineAnalysis(), main(), ProGe::RV32MicroCodeGenerator::mapFunctionUnit(), maximumLatency(), CompiledSimCodeGenerator::maxLatency(), MachineInfo::maxLatency(), MachineInfo::maxMemoryAlignment(), MinimizeMachine::minimizeFunctionUnits(), MinimalOpSetCheck::missingOperations(), MachineConnectivityCheck::needRegCopiesDueReadPortConflicts(), MachineConnectivityCheck::needsRegisterCopiesDueImmediateOperands(), AddFUFromHDBDialog::onAdd(), BusDialog::onAddFUGuard(), AddWatchDialog::onFUChoice(), FUDialog::onOK(), GCUDialog::onOK(), PlatformIntegrator::parseDataMemories(), MachineResourceModifier::percentualFUIncrease(), BF2Scheduler::preAllocateFunctionUnitsInner(), printLatexFunctionUnitDescription(), MachineConnectivityCheck::raConnected(), ProximPortWindow::reinitialize(), BF2Scheduler::releasePortForOp(), RemoveUnconnectedComponents::removeUnconnectedFUs(), IDFValidator::removeUnknownImplementations(), ADFCombiner::renameExtraUnits(), RegisterCopyAdder::requiredRegisterCopiesForEachFU(), FUGuardDialog::selectedFU(), ComponentImplementationSelector::selectFUs(), setGlobalControl(), DataDependenceGraph::setMachine(), ProximMachineStateWindow::setUtilizationHighlights(), TDGen::supportedStackAccessOperations(), MachineConnectivityCheck::tempRegisterFiles(), ProGe::TestBenchBlock::TestBenchBlock(), MachineConnectivityCheck::toRfConnected(), CostEstimator::Estimator::totalAreaOfFunctionUnits(), CostEstimator::Estimator::totalEnergyOfFunctionUnits(), FUGuardDialog::TransferDataToWindow(), OTAOperationDialog::TransferDataToWindow(), MachineInfo::triggerIndex(), UniversalMachine::universalFunctionUnit(), TTAMachine::AddressSpace::unsetMachine(), ProximPortWindow::update(), CompiledSimCodeGenerator::updateDeclaredSymbolsList(), ProcessorImplementationWindow::updateImplementationLists(), TDGen::writeBackendCode(), TDGen::writeInstrInfo(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
hash()
TCEString TTAMachine::Machine::hash () const
Returns a hash string of the machine to determine quickly in case two machines are the same.
The hash consists of a 32bit hash of the .adf xml data concat with the .adf data length as a hex string.
Note
The hash string is done based on the ADF XML format, thus does not account for changes that have the different XML output, but in reality are the same architecture (in the point of view of the programmer).
Definition at line 926 of file Machine.cc.
                    {
    ADFSerializer serializer;
    std::string buffer;
    serializer.setDestinationString(buffer);
    serializer.writeMachine(*this);
    boost::hash<std::string> string_hasher;
    size_t h = string_hasher(buffer);
    TCEString hash =
        (Conversion::toHexString(buffer.length())).substr(2);
    hash += "_";
    hash += (Conversion::toHexString(h)).substr(2);
    return hash;
}
References hash(), XMLSerializer::setDestinationString(), Conversion::toHexString(), and ADFSerializer::writeMachine().
Referenced by DSDBManager::addArchitecture(), DSDBManager::architectureId(), and hash().
hasOperation()
bool TTAMachine::Machine::hasOperation (const TCEString & opName) const
Tells whether any FU in the machine has given operation or not
Parameters
opName name of the operation.
Definition at line 1042 of file Machine.cc.
{
    FunctionUnitNavigator fuNav = functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit* fu = fuNav.item(i);
        if (fu->hasOperation(opName)) {
            return true;
        }
    }
    if (controlUnit()->hasOperation(opName)) {
        return true;
    }
    return false;
}
References controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), functionUnitNavigator(), TTAMachine::FunctionUnit::hasOperation(), hasOperation(), and TTAMachine::Machine::Navigator< ComponentType >::item().
Referenced by OTAOperationDialog::addRISCVBaseOperations(), TDGen::create32BitExtLoadPatterns(), TDGen::createBoolAndHalfLoadPatterns(), TDGen::createByteExtLoadPatterns(), TDGen::createShortExtLoadPatterns(), llvm::LLVMTCEBuilder::emitMove(), TDGen::genGeneratedTCEPlugin_getLoad(), hasOperation(), ProGe::RV32MicroCodeGenerator::validateOperations(), DefaultDecoderGenerator::verifyCompatibility(), TDGen::writeInstrInfo(), and TDGen::writeScalarOperationExploitations().
immediateSlotNavigator()
Machine::ImmediateSlotNavigator TTAMachine::Machine::immediateSlotNavigator () const virtual
Returns a handle to the immediate slots in the machine.
Returns
Handle to the immediate slots in the machine.
Definition at line 462 of file Machine.cc.
{
    ImmediateSlotNavigator navigator(immediateSlots_);
    return navigator;
}
References immediateSlots_.
Referenced by addBus(), TTAMachine::InstructionTemplate::addSlot(), BEMGenerator::addTopLevelFields(), DisassemblyGridTable::GetNumberCols(), TTAMachine::ImmediateSlot::ImmediateSlot(), ImmediateSlotDialog::onAddSlot(), TemplateListDialog::onAddSlot(), ImmediateSlotDialog::onDeleteSlot(), BusDialog::onOK(), TemplateSlotDialog::onOK(), TTAMachine::ImmediateSlot::setName(), ImmediateSlotDialog::TransferDataToWindow(), TemplateSlotDialog::TransferDataToWindow(), TemplateListDialog::updateSlotList(), and BEMValidator::validate().
immediateUnitNavigator()
Machine::ImmediateUnitNavigator TTAMachine::Machine::immediateUnitNavigator () const virtual
Returns a handle to the immediate units in the machine.
Returns
Handle to the immediate units in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 416 of file Machine.cc.
{
    ImmediateUnitNavigator navigator(immediateUnits_);
    return navigator;
}
References immediateUnits_.
Referenced by RegisterCopyAdder::addConnectionRegisterCopies(), DefaultDecoderGenerator::addGlockPortToDecoder(), ProGe::NetlistGenerator::addIUToNetlist(), BEMGenerator::addLongImmDstRegisterFields(), ImmediateGenerator::addSplitInsTemplate(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), MachineStateBuilder::buildMachineState(), BusBroker::buildResources(), IUBroker::buildResources(), llvm::TCETargetMachine::calculateSupportedImmediates(), MachineInfo::canEncodeImmediateInteger(), MachineConnectivityCheck::canWriteAllImmediates(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), IDFValidator::checkIUImplementations(), ProGe::ProcessorGenerator::checkIULatencies(), BEMValidator::checkLImmDstRegisterFields(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::connectRegisterFiles(), AddIUCmd::Do(), PasteComponentCmd::Do(), InfoImmediatesCommand::execute(), InfoIunitsCommand::execute(), InfoProcCommand::execute(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), ProgrammabilityValidator::findConnections(), TTAProgram::TPEFProgramFactory::findImmediateUnit(), AutoSelectImplementationsDialog::findIUImplementations(), MachineConnectivityCheck::findPossibleSourcePorts(), FullyConnectedCheck::fix(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProGe::ProGeUI::generateIDF(), MachineEditPartFactory::getUnits(), DefaultDecoderGenerator::glockPortWidth(), ProcessorImplementationWindow::handleSelectIUImplementation(), TTAMachine::NullMachine::immediateUnitNavigator(), CompiledSimulation::immediateUnitRegisterValue(), MachineResourceManager::indexResource(), TTAProgram::TPEFResourceUpdater::initCache(), TTAMachine::InstructionTemplate::loadState(), loadState(), main(), MachineConnectivityCheck::maxLIMMCount(), AddIUFromHDBDialog::onAdd(), TemplateListDialog::onAddSlot(), IUDialog::onOK(), TemplateSlotDialog::onOK(), ImmInfo::registerImmediateLoadWidth(), ProximRegisterWindow::reinitialize(), IDFValidator::removeUnknownImplementations(), ADFCombiner::renameExtraUnits(), ComponentImplementationSelector::selectIUs(), TTAMachine::InstructionTemplate::supportedWidth(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), MachineConnectivityCheck::tempRegisterFiles(), MachineConnectivityCheck::toRfConnected(), TemplateSlotDialog::TransferDataToWindow(), ProximRegisterWindow::update(), ProcessorImplementationWindow::updateImplementationLists(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultDecoderGenerator::writeInstructionTemplateProcedures(), DefaultDecoderGenerator::writeLongImmediateWriteProcess(), TDGen::writeMoveImmediateDefs(), DefaultDecoderGenerator::writeRFCntrlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
instructionTemplateNavigator()
Machine::InstructionTemplateNavigator TTAMachine::Machine::instructionTemplateNavigator () const virtual
Returns a handle to the instruction templates in the machine.
Returns
Handle to the instruction templates in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 428 of file Machine.cc.
{
    InstructionTemplateNavigator navigator(instructionTemplates_);
    return navigator;
}
References instructionTemplates_.
Referenced by CodeCompressorPlugin::addBitsForImmediateSlot(), CodeCompressorPlugin::addBitsForMoveSlot(), BEMGenerator::addEncodings(), BEMGenerator::addLongImmDstRegisterFields(), BEMGenerator::addTopLevelFields(), ImmediateAnalyzer::analyzeImmediateCapabilitiesForOperation(), BusBroker::buildResources(), ITemplateBroker::buildResources(), llvm::TCETargetMachine::calculateSupportedImmediates(), MachineInfo::canEncodeImmediateInteger(), BEMValidator::checkImmediateControlField(), BEMValidator::checkLImmDstRegisterFields(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), MachineResourceModifier::hasSlot(), CodeCompressorPlugin::instructionTemplate(), TTAMachine::NullMachine::instructionTemplateNavigator(), loadState(), BEMGenerator::maxLongImmSlotWidth(), TemplateListDialog::onAddTemplate(), BusDialog::onOK(), ImmediateGenerator::printImmediateTemplates(), MachineResourceModifier::reduceBuses(), ImmInfo::registerImmediateLoadWidth(), MachineResourceModifier::removeBuses(), ImmediateGenerator::removeInsTemplate(), TemplateListDialog::selectedTemplate(), IUBroker::setupResourceLinks(), MachineInfo::templatesUsesSlot(), MachineInfo::templatesUsingSlot(), TemplateListDialog::TransferDataToWindow(), TTAMachine::Bus::unsetMachine(), TTAMachine::ImmediateSlot::unsetMachine(), TTAMachine::ImmediateUnit::unsetMachine(), IUDialog::updateTemplateList(), TTAMachine::ImmediateSlot::width(), DefaultDecoderGenerator::writeLongImmediateWriteProcess(), and TDGen::writeMoveImmediateDefs().
is64bit()
bool TTAMachine::Machine::is64bit () const inline
Definition at line 260 of file Machine.hh.
{ return bitness64_; }
References bitness64_.
Referenced by TDGen::analyzeMachineRegisters(), TDGen::checkRequiredRegisters(), LLVMBackend::compile(), TDGen::constantNodeString(), TDGen::createBoolAndHalfLoadPatterns(), TDGen::createByteExtLoadPatterns(), TDGen::createConstShiftPatterns(), TDGen::createEndiannesQuery(), TTAProgram::CodeGenerator::createForLoopBufferInit(), TDGen::createGetMaxMemoryAlignment(), llvm::LLVMTCEBuilder::createIntDataDefinition(), TDGen::createMinMaxGenerator(), llvm::LLVMTCEBuilder::createMove(), LLVMBackend::createPlugin(), TDGen::createSelectPatterns(), TDGen::createShortExtLoadPatterns(), llvm::LLVMTCEBuilder::createTerminal(), TTAProgram::CodeGenerator::decrementRegisterAddress(), llvm::LLVMTCEBuilder::doFinalization(), llvm::LLVMTCEBuilder::emitInstruction(), llvm::LLVMTCEBuilder::emitMove(), llvm::LLVMTCEBuilder::emitSetjmp(), llvm::LLVMTCEBuilder::emitSPInitialization(), TDGen::emulatingOpNodeLLVMName(), TDGen::genGeneratedTCEPlugin_getLoad(), TDGen::genGeneratedTCEPlugin_getStore(), TDGen::genTCEInstrInfo_copyPhys64bitReg(), TTAProgram::CodeGenerator::incrementRegisterAddress(), TDGen::llvmOperationName(), TDGen::llvmOperationPattern(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadMachine(), TTAProgram::CodeGenerator::loadTerminal(), TDGen::operandChar(), TDGen::operandToString(), TDGen::operationCanBeMatched(), llvm::TCETargetMachine::setTargetMachinePlugin(), TTAProgram::CodeGenerator::storeTerminal(), TDGen::TDGen(), TDGen::write1bitRegisterInfo(), TDGen::write32bitRegisterInfo(), TDGen::write64bitRegisterInfo(), TDGen::writeAddressingModeDefs(), TDGen::writeBackendCode(), TDGen::writeCallingConv(), TDGen::writeCallSeqStart(), TDGen::writeConstShiftPat(), TDGen::writeEmulationPattern(), TDGen::writeGetPointerAdjustmentQuery(), TDGen::writeGuardRegisterClassInfo(), TDGen::writeInstrInfo(), TDGen::writeIntegerImmediateDefs(), TDGen::writeMiscPatterns(), TDGen::writeMoveImmediateDefs(), TDGen::writeOperationDef(), TDGen::writeOperationDefs(), RISCVTDGen::writePatternDefinition(), TDGen::writeRARegisterInfo(), TDGen::writeScalarOperationExploitations(), and TDGen::writeVectorLoadStoreOperationExploitations().
isFUOrdered()
bool TTAMachine::Machine::isFUOrdered () const
Returns true if sequential order of FUs in ADF file is significant.
In certain architectures (Cell SPU) the "relative order" of the function units matters when it comes to accessing same register by multiple operations in the same cycle.
Definition at line 971 of file Machine.cc.
{
    return fuOrdered_;
}
References fuOrdered_.
isLittleEndian()
bool TTAMachine::Machine::isLittleEndian () const inline
Definition at line 258 of file Machine.hh.
{ return littleEndian_; }
References littleEndian_.
Referenced by Assembler::compile(), LLVMBackend::compile(), TTAProgram::ProgramWriter::createBinary(), llvm::LLVMTCEBuilder::createDataDefinition(), TTAProgram::TPEFProgramFactory::createDataMemories(), llvm::LLVMTCEBuilder::createFPDataDefinition(), llvm::LLVMTCEBuilder::createGlobalValueDataDefinition(), llvm::LLVMTCEBuilder::createIntDataDefinition(), LLVMBackend::createPlugin(), llvm::LLVMTCEBuilder::emitDataDef(), llvm::LLVMTCEBuilder::emitSPInitialization(), llvm::LLVMTCEBuilder::initDataSections(), SimulatorFrontend::initializeMemorySystem(), TTAProgram::CodeGenerator::loadTerminal(), llvm::LLVMTCEBuilder::padToAlignment(), InlineAsmParser::parse(), MachineConnectivityCheck::raConnected(), TTAProgram::CodeGenerator::storeTerminal(), MachineDialog::TransferDataToWindow(), and ProgramImageGenerator::writeDataSection().
isRISCVMachine()
bool TTAMachine::Machine::isRISCVMachine () const
Definition at line 1057 of file Machine.cc.
{
    OperationTriggeredFormatNavigator fNav =
        operationTriggeredFormatNavigator();
    int fCount = fNav.count();
    if (fCount == 0) {
        return false;
    }
    const std::vector<std::string> requiredFormats = {
        "riscv_r_type", "riscv_i_type", "riscv_s_type",
        "riscv_b_type", "riscv_u_type", "riscv_j_type"};
    for (const std::string& f : requiredFormats) {
        if (!fNav.hasItem(f)) {
            throw InvalidData(
                __FILE__, __LINE__, __func__,
                TCEString("Missing required instruction format: ") + f);
        }
    }
    return true;
}
References __func__, TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), and operationTriggeredFormatNavigator().
Referenced by ProGe::NetlistGenerator::addGCUToNetlist(), DefaultICGenerator::addICToNetlist(), ProGe::ProcessorWrapperBlock::addInstructionMemory(), DefaultICDecoderGenerator::addInstructioRegisterBypass(), DefaultICDecoderGenerator::completeNetlist(), DefaultICDecoderGenerator::generate(), ProGe::ProcessorGenerator::generateProcessor(), GenerateProcessor::generateProcessor(), CodeCompressorPlugin::setMachine(), DefaultDecoderGenerator::verifyCompatibility(), DefaultDecoderGenerator::writeControlRegisterMappings(), and DefaultICGenerator::writeInterconnectionNetwork().
isUniversalMachine()
bool TTAMachine::Machine::isUniversalMachine () const virtual
Reimplemented in UniversalMachine.
Definition at line 127 of file Machine.cc.
{
    return false;
}
Referenced by POMDisassembler::createFUPort().
loadFromADF()
TTAMachine::Machine * TTAMachine::Machine::loadFromADF (const std::string & adfFileName) static
Loads a Machine from the given ADF file.
Parameters
adfFileName The name of the file to load the ADF from.
Returns
A machine instance.
Exceptions
Exception In case some error occured.
Definition at line 899 of file Machine.cc.
{
    ADFSerializer serializer;
    serializer.setSourceFile(adfFileName);
    return serializer.readMachine();
}
References ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
Referenced by MinimalOpSetCheck::buildMinimalOpSet(), Evaluate::createConfig(), MinimalOpSet::createConfig(), llvm::LLVMTCEPOMBuilder::doInitialization(), ADFCombiner::explore(), ComponentAdder::explore(), ImplementationSelector::explore(), MinimalOpSetCheck::fix(), initializeMachine(), llvm::LLVMTCERISCVIntrinsicsLowering::LLVMTCERISCVIntrinsicsLowering(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), and main().
loadState()
void TTAMachine::Machine::loadState (const ObjectState * state) virtual
Loads the state of the machine from the given ObjectState tree.
Parameters
state Root node of the ObjectState tree.
Exceptions
ObjectStateLoadingException If the given ObjectState tree is invalid.
Implements Serializable.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 728 of file Machine.cc.
{
    string procName = "Machine::loadState";
    if (state->name() != OSNAME_MACHINE) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    // delete all the old components
    busses_.deleteAll();
    sockets_.deleteAll();
    instructionTemplates_.deleteAll();
    registerFiles_.deleteAll();
    immediateUnits_.deleteAll();
    functionUnits_.deleteAll();
    addressSpaces_.deleteAll();
    bridges_.deleteAll();
    immediateSlots_.deleteAll();
    operationTriggeredFormats_.deleteAll();
    if (controlUnit_ != NULL) {
        delete controlUnit_;
        controlUnit_ = NULL;
    }
    Component* toAdd = NULL;
    setAlwaysWriteResults(
        state->hasAttribute(OSKEY_ALWAYS_WRITE_BACK_RESULTS) &&
        state->boolAttribute(OSKEY_ALWAYS_WRITE_BACK_RESULTS));
    setTriggerInvalidatesResults(
        state->hasAttribute(OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS) &&
        state->boolAttribute(OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS));
    setFUOrdered(
        state->hasAttribute(OSKEY_FUNCTION_UNITS_ORDERED) &&
        state->boolAttribute(OSKEY_FUNCTION_UNITS_ORDERED));
    setLittleEndian(
        state->hasAttribute("little-endian") &&
        state->boolAttribute("little-endian"));
    set64bits(
        state->hasAttribute("bitness64") &&
        state->boolAttribute("bitness64"));
    try {
        // create skeletons
        for (int i = 0; i < state->childCount(); i++) {
            toAdd = NULL;
            ObjectState* child = state->child(i);
            if (child->name() == Bus::OSNAME_BUS) {
                Bus* bus = new Bus(child);
                toAdd = bus;
                addBus(*bus);
            } else if (child->name() == Socket::OSNAME_SOCKET) {
                Socket* socket = new Socket(child);
                toAdd = socket;
                addSocket(*socket);
            } else if (child->name() == Bridge::OSNAME_BRIDGE) {
                // bridge is registered automatically
                new Bridge(child, *this);
            } else if (child->name() == AddressSpace::OSNAME_ADDRESS_SPACE) {
                // address space is registered automatically and its state is
                // loaded completely --> no need to call loadState later
                new AddressSpace(child, *this);
            } else if (child->name() == RegisterFile::OSNAME_REGISTER_FILE) {
                RegisterFile* regFile = new RegisterFile(child);
                toAdd = regFile;
                addRegisterFile(*regFile);
            } else if (child->name() == FunctionUnit::OSNAME_FU) {
                FunctionUnit* fu = new FunctionUnit(child);
                toAdd = fu;
                addFunctionUnit(*fu);
            } else if (child->name() ==
                    ImmediateUnit::OSNAME_IMMEDIATE_UNIT) {
                ImmediateUnit* immUnit = new ImmediateUnit(child);
                toAdd = immUnit;
                addImmediateUnit(*immUnit);
            } else if (child->name() == ControlUnit::OSNAME_CONTROL_UNIT) {
                ControlUnit* cUnit = new ControlUnit(child);
                toAdd = cUnit;
                setGlobalControl(*cUnit);
            } else if (child->name() == ImmediateSlot::OSNAME_IMMEDIATE_SLOT) {
                new ImmediateSlot(child, *this);
            }
        }
    } catch (const Exception& e) {
        if (toAdd != NULL) {
            delete toAdd;
        }
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
    // load states of each component
    try {
        for (int i = 0; i < state->childCount(); i++) {
            ObjectState* child = state->child(i);
            string name = child->stringAttribute(Component::OSKEY_NAME);
            if (child->name() == Bus::OSNAME_BUS) {
                BusNavigator busNav = busNavigator();
                Bus* bus = busNav.item(name);
                bus->loadState(child);
            } else if (child->name() == Socket::OSNAME_SOCKET) {
                SocketNavigator socketNav = socketNavigator();
                Socket* socket = socketNav.item(name);
                socket->loadState(child);
            } else if (child->name() == Bridge::OSNAME_BRIDGE) {
                BridgeNavigator bridgeNav = bridgeNavigator();
                Bridge* bridge = bridgeNav.item(name);
                bridge->loadState(child);
            } else if (child->name() == RegisterFile::OSNAME_REGISTER_FILE) {
                RegisterFileNavigator rfNav = registerFileNavigator();
                RegisterFile* rf = rfNav.item(name);
                rf->loadState(child);
            } else if (child->name() == FunctionUnit::OSNAME_FU) {
                FunctionUnitNavigator fuNav = functionUnitNavigator();
                FunctionUnit* fu = fuNav.item(name);
                fu->loadState(child);
            } else if (child->name() ==
                       ImmediateUnit::OSNAME_IMMEDIATE_UNIT) {
                ImmediateUnitNavigator iuNav = immediateUnitNavigator();
                ImmediateUnit* iu = iuNav.item(name);
                iu->loadState(child);
            } else if (child->name() ==
                       ControlUnit::OSNAME_CONTROL_UNIT) {
                ControlUnit* cu = controlUnit();
                cu->loadState(child);
            } else if (child->name() ==
                       InstructionTemplate::OSNAME_INSTRUCTION_TEMPLATE) {
                // instruction template loads its state completely
                new InstructionTemplate(child, *this);
            } else if (
                child->name() == OperationTriggeredFormat::OSNAME_FORMAT) {
                new OperationTriggeredFormat(child, *this);
            }
        }
    } catch (const Exception& e) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName,
                                          e.errorMessage());
    }
    // create an empty instruction template if there is no instruction
    // templates
    InstructionTemplateNavigator itNav = instructionTemplateNavigator();
    if (itNav.count() == 0) {
        new InstructionTemplate(EMPTY_ITEMP_NAME_, *this);
    }
}
References addBus(), addFunctionUnit(), addImmediateUnit(), addRegisterFile(), addressSpaces_, addSocket(), ObjectState::boolAttribute(), bridgeNavigator(), bridges_, busNavigator(), busses_, ObjectState::child(), ObjectState::childCount(), controlUnit(), controlUnit_, TTAMachine::Machine::Navigator< ComponentType >::count(), EMPTY_ITEMP_NAME_, Exception::errorMessage(), functionUnitNavigator(), functionUnits_, ObjectState::hasAttribute(), immediateSlots_, immediateUnitNavigator(), immediateUnits_, instructionTemplateNavigator(), instructionTemplates_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Bridge::loadState(), TTAMachine::Bus::loadState(), TTAMachine::ControlUnit::loadState(), TTAMachine::FunctionUnit::loadState(), TTAMachine::ImmediateUnit::loadState(), TTAMachine::RegisterFile::loadState(), TTAMachine::Socket::loadState(), ObjectState::name(), operationTriggeredFormats_, OSKEY_ALWAYS_WRITE_BACK_RESULTS, OSKEY_FUNCTION_UNITS_ORDERED, TTAMachine::Component::OSKEY_NAME, OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS, TTAMachine::AddressSpace::OSNAME_ADDRESS_SPACE, TTAMachine::Bridge::OSNAME_BRIDGE, TTAMachine::Bus::OSNAME_BUS, TTAMachine::ControlUnit::OSNAME_CONTROL_UNIT, TTAMachine::OperationTriggeredFormat::OSNAME_FORMAT, TTAMachine::FunctionUnit::OSNAME_FU, TTAMachine::ImmediateSlot::OSNAME_IMMEDIATE_SLOT, TTAMachine::ImmediateUnit::OSNAME_IMMEDIATE_UNIT, TTAMachine::InstructionTemplate::OSNAME_INSTRUCTION_TEMPLATE, OSNAME_MACHINE, TTAMachine::RegisterFile::OSNAME_REGISTER_FILE, TTAMachine::Socket::OSNAME_SOCKET, registerFileNavigator(), registerFiles_, set64bits(), setAlwaysWriteResults(), setFUOrdered(), setGlobalControl(), setLittleEndian(), setTriggerInvalidatesResults(), socketNavigator(), sockets_, and ObjectState::stringAttribute().
Referenced by DSDBManager::architecture(), copyFromMachine(), Machine(), MinimizeMachine::minimizeFunctionUnits(), MinimizeMachine::minimizeRegisterFiles(), and ADFSerializer::readMachine().
machineTester()
MachineTester & TTAMachine::Machine::machineTester () const
Returns the machine tester for the machine.
Returns
The machine tester for the machine.
Definition at line 671 of file Machine.cc.
{
    if (doValidityChecks_) {
        return *machineTester_;
    } else {
        return *dummyMachineTester_;
    }
}
References doValidityChecks_, dummyMachineTester_, and machineTester_.
Referenced by TTAMachine::Socket::attachBus(), TTAMachine::Port::attachSocket(), TTAMachine::Segment::attachSocket(), TTAMachine::Bridge::Bridge(), RemoveUnconnectedComponents::checkFUPorts(), RemoveUnconnectedComponents::checkRFPorts(), ControlDependenceGraphPass::handleControlDependenceGraph(), DDGPass::handleDDG(), TTAMachine::Bridge::loadState(), and TTAMachine::Socket::setDirection().
maximumLatency()
int TTAMachine::Machine::maximumLatency () const
Gets the maximum latency of any operation supported by this machine.
Definition at line 1023 of file Machine.cc.
{
    int maxLatency = 0;
    FunctionUnitNavigator fuNav = functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        FunctionUnit* fu = fuNav.item(i);
        int fuLatency = fu->maxLatency();
        if (fuLatency > maxLatency) {
            maxLatency = fuLatency;
        }
    }
    return maxLatency;
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), and TTAMachine::FunctionUnit::maxLatency().
Referenced by BF2ScheduleFront::scheduleFrontFromMove().
operationTriggeredFormatNavigator()
Machine::OperationTriggeredFormatNavigator TTAMachine::Machine::operationTriggeredFormatNavigator () const virtual
Returns a handle to the instruction templates in the machine.
Returns
Handle to the instruction templates in the machine.
Definition at line 439 of file Machine.cc.
{
    OperationTriggeredFormatNavigator navigator(operationTriggeredFormats_);
    return navigator;
}
References operationTriggeredFormats_.
Referenced by BEMGenerator::addTopLevelFields(), isRISCVMachine(), OTAFormatListDialog::onAddOTAFormat(), OTAFormatListDialog::onOTAFormatName(), OTAFormatListDialog::selectedOTAFormat(), and OTAFormatListDialog::TransferDataToWindow().
operator=()
Machine & TTAMachine::Machine::operator= (const Machine &) private
Assignment not allowed.
registerFileNavigator()
Machine::RegisterFileNavigator TTAMachine::Machine::registerFileNavigator () const virtual
Returns a handle to the register files in the machine.
Returns
Handle to the register files in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 450 of file Machine.cc.
{
    RegisterFileNavigator navigator(registerFiles_);
    return navigator;
}
References registerFiles_.
Referenced by DefaultDecoderGenerator::addGlockPortToDecoder(), ADFCombiner::addRegisterFiles(), ComponentAdder::addRegisterFiles(), ProGe::NetlistGenerator::addRFToNetlist(), TDGen::analyzeMachineRegisters(), TDGen::analyzeRegisters(), MachineResourceModifier::analyzeRegisters(), UniversalMachine::booleanRegisterFile(), MachineStateBuilder::buildMachineState(), llvm::TCETargetMachine::calculateSupportedImmediates(), RegisterQuantityCheck::canFixIntRegs(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), RFPortCheck::check(), ProgrammabilityValidator::checkBooleanRegister(), IDFValidator::checkRFImplementations(), RemoveUnconnectedComponents::checkRFPorts(), SimulatorFrontend::compareState(), DefaultDecoderGenerator::completeDecoderBlock(), ADFCombiner::connectRegisterFiles(), ADFCombiner::copyGuards(), RegisterQuantityCheck::countIntRegisters(), llvm::LLVMTCEBuilder::createTerminalRegister(), TTAProgram::CodeGenerator::createTerminalRegister(), AddRFCmd::Do(), PasteComponentCmd::Do(), UniversalMachine::doubleRegisterFile(), llvm::LLVMTCEBuilder::emitLongjmp(), llvm::LLVMTCEBuilder::emitSetjmp(), llvm::LLVMTCEBuilder::emitSPInitialization(), InfoRegFilesCommand::execute(), InfoProcCommand::execute(), InfoStatsCommand::execute(), VLIWConnectIC::explore(), SimulatorFrontend::findBooleanRegister(), findBooleanRegisterFile(), RegisterRenamer::findConnectedRFs(), ProgrammabilityValidator::findConnections(), RegisterRenamer::findFreeRegisters(), ProgrammabilityValidator::findGlobalConnectionRegister(), RegisterRenamer::findPartiallyUsedRegistersAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersBeforeCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFAfterCycle(), RegisterRenamer::findPartiallyUsedRegistersInRFBeforeCycle(), SimulatorFrontend::findRegister(), TTAProgram::TPEFProgramFactory::findRegisterFile(), findRegisterFile(), ProGe::RV32MicroCodeGenerator::findRF(), AutoSelectImplementationsDialog::findRFImplementations(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), RegisterQuantityCheck::fixIntRegs(), CompiledSimCodeGenerator::generateHeaderAndMainCode(), ProGe::ProGeUI::generateIDF(), getRegisterFile(), MachineEditPartFactory::getUnits(), DefaultDecoderGenerator::glockPortWidth(), ProcessorImplementationWindow::handleSelectRFImplementation(), MachineConnectivityCheck::hasConditionalMoves(), MachineResourceModifier::increaseAllRFsThatDiffersByAmount(), MachineResourceManager::indexResource(), TTAProgram::TPEFResourceUpdater::initCache(), RegisterRenamer::initialize(), AddWatchDialog::initialize(), UniversalMachine::integerRegisterFile(), MachineConnectivityCheck::isConnectedToDifferentlyConnectedRFs(), TTAMachine::RegisterGuard::loadState(), loadState(), CostEstimator::Estimator::longestPath(), MachineAnalysis::MachineAnalysis(), main(), MinimizeMachine::minimizeRegisterFiles(), MachineConnectivityCheck::needRegCopiesDueReadPortConflicts(), MachineInfo::numberOfRegisters(), AddRFFromHDBDialog::onAdd(), BusDialog::onAddRFGuard(), RFDialog::onOK(), AddWatchDialog::onRFChoice(), MachineResourceModifier::percentualRegisterIncrease(), llvm::LLVMTCEIRBuilder::registerFileName(), TTAMachine::NullMachine::registerFileNavigator(), CompiledSimulation::registerFileValue(), CompiledSimController::registerFileValue(), SimulationController::registerFileValue(), ProximRegisterWindow::reinitialize(), IDFValidator::removeUnknownImplementations(), ADFCombiner::renameExtraUnits(), BFRenameLiveRange::renameLiveRange(), RegisterRenamer::renameLiveRange(), RFGuardDialog::selectedRF(), ComponentImplementationSelector::selectRFs(), BFRenameLiveRange::setTerminals(), UniversalMachine::specialRegisterFile(), ConnectionSweeper::sweepBypasses(), ConnectionSweeper::sweepRFs(), MachineConnectivityCheck::tempRegisterFiles(), CostEstimator::Estimator::totalAreaOfRegisterFiles(), CostEstimator::Estimator::totalEnergyOfRegisterFiles(), RFGuardDialog::TransferDataToWindow(), ProximRegisterWindow::update(), ProcessorImplementationWindow::updateImplementationLists(), TDGen::writeMoveImmediateDefs(), DefaultDecoderGenerator::writeRFSRAMDecodingProcess(), DefaultDecoderGenerator::writeRulesForDestinationControlSignals(), and DefaultDecoderGenerator::writeRulesForSourceControlSignals().
removeBus()
void TTAMachine::Machine::removeBus (Bus & bus) virtual
Removes bus from the machine.
The machine will stay consistent after removal.
Parameters
bus Bus to be removed.
Exceptions
InstanceNotFound If the machine does not have the given bus.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 477 of file Machine.cc.
{
    removeComponent(busses_, bus);
}
References busses_, and removeComponent().
Referenced by RemoveUnconnectedComponents::checkBuses(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), MachineResourceModifier::reduceBuses(), MachineResourceModifier::removeBuses(), and TTAMachine::Bus::unsetMachine().
removeComponent()
template<typename ContainerType , typename ComponentType > void TTAMachine::Machine::removeComponent (ContainerType & container, ComponentType & toRemove) private
Referenced by removeBus(), removeFunctionUnit(), removeImmediateUnit(), removeRegisterFile(), and removeSocket().
removeFunctionUnit()
void TTAMachine::Machine::removeFunctionUnit (FunctionUnit & unit) virtual
Removes the given function unit from the machine.
Parameters
unit The function unit to be removed.
Exceptions
InstanceNotFound If the given function unit does not belong to the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 530 of file Machine.cc.
{
    removeComponent(functionUnits_, unit);
}
References functionUnits_, and removeComponent().
Referenced by MinimizeMachine::minimizeFunctionUnits(), RemoveUnconnectedComponents::removeUnconnectedFUs(), removeUnit(), and TTAMachine::FunctionUnit::unsetMachine().
removeImmediateUnit()
void TTAMachine::Machine::removeImmediateUnit (ImmediateUnit & unit) virtual
Removes the given immediate unit from the machine.
Parameters
unit The immediate unit to be removed.
Exceptions
InstanceNotFound If the given immediate unit does not belong to the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 542 of file Machine.cc.
{
    removeComponent(immediateUnits_, unit);
}
References immediateUnits_, and removeComponent().
Referenced by removeUnit(), and TTAMachine::ImmediateUnit::unsetMachine().
removeRegisterFile()
void TTAMachine::Machine::removeRegisterFile (RegisterFile & unit) virtual
Removes the given register file from the machine.
Parameters
unit The register file to be removed.
Exceptions
InstanceNotFound If the given register file does not belong to the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 554 of file Machine.cc.
{
    removeComponent(registerFiles_, unit);
}
References registerFiles_, and removeComponent().
Referenced by RemoveUnconnectedComponents::checkRFPorts(), VLIWConnectIC::explore(), MinimizeMachine::minimizeRegisterFiles(), removeUnit(), and TTAMachine::RegisterFile::unsetMachine().
removeSocket()
void TTAMachine::Machine::removeSocket (Socket & socket) virtual
Removes socket from the machine.
The machine will stay consistent after removal.
Parameters
socket Socket to be removed.
Exceptions
InstanceNotFound If the machine does not have the given socket.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 490 of file Machine.cc.
{
    removeComponent(sockets_, socket);
}
References removeComponent(), and sockets_.
Referenced by BlocksConnectIC::explore(), VLIWConnectIC::explore(), MachineResourceModifier::removeNotConnectedSockets(), and TTAMachine::Socket::unsetMachine().
removeUnit()
void TTAMachine::Machine::removeUnit (Unit & unit) virtual
Removes unit from the machine.
The machine will stay consistent after removal. Global control unit must be removed using unsetGlobalControl method.
Parameters
unit Unit to be removed.
Exceptions
InstanceNotFound If the machine does not have the given unit.
IllegalParameters If ControlUnit is tried to remove.
Reimplemented in TTAMachine::NullMachine.
Definition at line 505 of file Machine.cc.
{
    FunctionUnit* fu = dynamic_cast<FunctionUnit*>(&unit);
    ImmediateUnit* iu = dynamic_cast<ImmediateUnit*>(&unit);
    RegisterFile* rf = dynamic_cast<RegisterFile*>(&unit);
    if (fu != NULL) {
        removeFunctionUnit(*fu);
    } else if (iu != NULL) {
        removeImmediateUnit(*iu);
    } else if (rf != NULL) {
        removeRegisterFile(*rf);
    } else {
        const string procName = "Machine::removeUnit";
        throw IllegalParameters(__FILE__, __LINE__, procName);
    }
}
References removeFunctionUnit(), removeImmediateUnit(), and removeRegisterFile().
saveComponentStates()
template<typename ContainerType > void TTAMachine::Machine::saveComponentStates (ContainerType & container, ObjectState * parent) static private
Saves the state of each component in the given container and add the created ObjectStates as children of the given parent ObjectState.
Parameters
container The container.
parent The parent ObjectState.
Definition at line 1012 of file Machine.cc.
{
    for (int i = 0; i < container.count(); i++) {
        Serializable* component = container.item(i);
        parent->addChild(component->saveState());
    }
}
References ObjectState::addChild(), and Serializable::saveState().
Referenced by saveState().
saveState()
ObjectState * TTAMachine::Machine::saveState () const virtual
Saves the machine to ObjectState tree.
Returns
Root of the created ObjectState tree.
Implements Serializable.
Reimplemented in TTAMachine::NullMachine.
Definition at line 686 of file Machine.cc.
{
    ObjectState* rootState = new ObjectState(OSNAME_MACHINE);
    saveComponentStates(busses_, rootState);
    saveComponentStates(sockets_, rootState);
    saveComponentStates(bridges_, rootState);
    saveComponentStates(functionUnits_, rootState);
    saveComponentStates(registerFiles_, rootState);
    saveComponentStates(immediateUnits_, rootState);
    saveComponentStates(addressSpaces_, rootState);
    saveComponentStates(instructionTemplates_, rootState);
    saveComponentStates(immediateSlots_, rootState);
    saveComponentStates(operationTriggeredFormats_, rootState);
    // save global control unit
    if (controlUnit_ != NULL) {
        rootState->addChild(controlUnit_->saveState());
    }
    rootState->setAttribute(
        OSKEY_ALWAYS_WRITE_BACK_RESULTS, alwaysWriteResults_);
    rootState->setAttribute(
        OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS, triggerInvalidatesResults_);
    rootState->setAttribute(
        OSKEY_FUNCTION_UNITS_ORDERED, fuOrdered_);
    rootState->setAttribute("little-endian", littleEndian_);
    rootState->setAttribute("bitness64", bitness64_);
    return rootState;
}
References ObjectState::addChild(), addressSpaces_, alwaysWriteResults_, bitness64_, bridges_, busses_, controlUnit_, functionUnits_, fuOrdered_, immediateSlots_, immediateUnits_, instructionTemplates_, littleEndian_, operationTriggeredFormats_, OSKEY_ALWAYS_WRITE_BACK_RESULTS, OSKEY_FUNCTION_UNITS_ORDERED, OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS, OSNAME_MACHINE, registerFiles_, saveComponentStates(), TTAMachine::ControlUnit::saveState(), ObjectState::setAttribute(), sockets_, and triggerInvalidatesResults_.
Referenced by DSDBManager::addArchitecture(), copyFromMachine(), Machine(), MinimizeMachine::minimizeFunctionUnits(), MinimizeMachine::minimizeRegisterFiles(), and ADFSerializer::writeMachine().
set64bits()
void TTAMachine::Machine::set64bits (bool flag) inline
Definition at line 261 of file Machine.hh.
{ bitness64_ = flag; }
References bitness64_.
Referenced by loadState().
setAlwaysWriteResults()
void TTAMachine::Machine::setAlwaysWriteResults (bool result)
Sets whether or not result must always be written to register.
Definition at line 979 of file Machine.cc.
{
    alwaysWriteResults_ = result;
}
References alwaysWriteResults_.
Referenced by loadState().
setBusPosition()
void TTAMachine::Machine::setBusPosition (const Bus & bus, int newPosition)
Sets new position for the given bus.
Parameters
bus The bus being moved.
newPosition The index of the new position (the first position is 0).
Exceptions
IllagalRegistration If the given bus is not registered to the machine.
OutOfRange If the given position is less than 0 or not smaller than the number of buses in the machine.
Definition at line 651 of file Machine.cc.
{
    const string procName = "Machine::setBusPosition";
    if (bus.machine() != this) {
        throw IllegalRegistration(__FILE__, __LINE__, procName);
    }
    if (newPosition < 0 || newPosition >= busNavigator().count()) {
        throw OutOfRange(__FILE__, __LINE__, procName);
    }
    busses_.moveToPosition(&bus, newPosition);
}
References busNavigator(), busses_, and TTAMachine::Component::machine().
Referenced by ProDeBusOrderDialog::onDown(), and ProDeBusOrderDialog::onUp().
setFUOrdered()
void TTAMachine::Machine::setFUOrdered (bool order)
Definition at line 999 of file Machine.cc.
{
    fuOrdered_ = order;
}
References fuOrdered_.
Referenced by loadState().
setGlobalControl()
void TTAMachine::Machine::setGlobalControl (ControlUnit & unit) virtual
Sets the global control unit for the machine.
Parameters
unit The new global control unit.
Exceptions
ComponentAlreadyExists If a control unit already exists in the machine.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 317 of file Machine.cc.
{
    const string procName = "Machine::setGlobalControl";
    if (controlUnit_ != NULL) {
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    // check that the name is unique among function units
    FunctionUnitNavigator fuNav = functionUnitNavigator();
    if (fuNav.hasItem(unit.name())) {
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    if (unit.machine() == NULL) {
        unit.setMachine(*this);
    } else {
        controlUnit_ = &unit;
    }
}
References controlUnit_, functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::hasItem(), TTAMachine::Component::machine(), TTAMachine::Component::name(), and TTAMachine::ControlUnit::setMachine().
Referenced by ADFCombiner::addFunctionUnits(), BlocksGCU::BlocksGCU(), loadState(), UniversalMachine::setGlobalControl(), and TTAMachine::ControlUnit::setMachine().
setLittleEndian()
void TTAMachine::Machine::setLittleEndian (bool flag) inline
Definition at line 259 of file Machine.hh.
{ littleEndian_ = flag; }
References littleEndian_.
Referenced by BlocksTranslator::BuildTTAModel(), loadState(), and MachineDialog::onOK().
setTriggerInvalidatesResults()
void TTAMachine::Machine::setTriggerInvalidatesResults (bool trigger)
Sets whether triggering invalidates register where result will be stored.
Definition at line 987 of file Machine.cc.
{
    triggerInvalidatesResults_ = trigger;
}
References triggerInvalidatesResults_.
Referenced by loadState().
socketNavigator()
Machine::SocketNavigator TTAMachine::Machine::socketNavigator () const virtual
Returns a handle to the sockets in the machine.
Returns
Handle to the sockets in the machine.
Reimplemented in TTAMachine::NullMachine.
Definition at line 368 of file Machine.cc.
{
    SocketNavigator navigator(sockets_);
    return navigator;
}
References sockets_.
Referenced by ADFCombiner::addBuses(), SimpleICOptimizer::addConnections(), DefaultICGenerator::addICToNetlist(), BEMGenerator::addSocketCodeTables(), TTAMachine::Port::attachSocket(), InputPSocketBroker::buildResources(), OutputPSocketBroker::buildResources(), DefaultICDecoderEstimator::busParameters(), FullyConnectedCheck::check(), FullyConnectedCheck::check(), RemoveUnconnectedComponents::checkBuses(), RemoveUnconnectedComponents::checkFUPorts(), RemoveUnconnectedComponents::checkRFPorts(), BEMValidator::checkSocketCodeTable(), DefaultDecoderGenerator::completeDecoderBlock(), FullyConnectedCheck::connectFUPort(), BlocksTranslator::ConnectInputs(), ADFCombiner::connectPorts(), ADFCombiner::connectVectorLSU(), TTAProgram::TPEFProgramFactory::createInstruction(), ADFCombiner::createPortsAndSockets(), FullyConnectedCheck::createSocket(), AddSocketCmd::Do(), PasteComponentCmd::Do(), UniversalFunctionUnit::ensureInputPorts(), UniversalFunctionUnit::ensureOutputPorts(), DefaultICDecoderEstimator::estimateICArea(), DefaultICDecoderEstimator::estimateICEnergy(), InfoProcCommand::execute(), BlocksConnectIC::explore(), VLIWConnectIC::explore(), SimulatorFrontend::finishSimulation(), FullyConnectedCheck::fix(), DefaultICGenerator::generateSocketsAndMuxes(), MachineEditPartFactory::getSockets(), loadState(), CostEstimator::Estimator::longestPath(), BEMValidator::needsSocketCodeTable(), SocketDialog::onOK(), IUPortDialog::onOK(), FUPortDialog::onSocketChoice(), RFPortDialog::onSocketChoice(), SRPortDialog::onSocketChoice(), SimpleICOptimizer::removeAllConnections(), ConnectionSweeper::removeConnection(), MachineResourceModifier::removeNotConnectedSockets(), RemoveUnconnectedComponents::removeUnconnectedFUs(), ProximMachineStateWindow::setUtilizationHighlights(), TTAMachine::NullMachine::socketNavigator(), IUPortDialog::updateSocket(), FUPortDialog::updateSockets(), RFPortDialog::updateSockets(), SRPortDialog::updateSockets(), DefaultDecoderGenerator::writeControlRegisterMappings(), DefaultICGenerator::writeInterconnectionNetwork(), DefaultDecoderGenerator::writeRulesForSourceControlSignals(), and DefaultDecoderGenerator::writeSocketCntrlSignals().
triggerInvalidatesResults()
bool TTAMachine::Machine::triggerInvalidatesResults () const
Returns true if triggering make content of the register where result will be stored invalid.
Definition at line 958 of file Machine.cc.
{
    return triggerInvalidatesResults_;
}
References triggerInvalidatesResults_.
Referenced by DataDependenceGraph::earliestCycle(), and DataDependenceGraph::latestCycle().
unsetGlobalControl()
void TTAMachine::Machine::unsetGlobalControl () virtual
Removes the global control unit from the machine.
WARNING: The unit is not deleted. You should have a reference to it to be able to delete it later.
Reimplemented in TTAMachine::NullMachine, and UniversalMachine.
Definition at line 565 of file Machine.cc.
{
    if (controlUnit_ == NULL) {
        return;
    } else {
        if (controlUnit_->machine() == NULL) {
            controlUnit_ = NULL;
        } else {
            controlUnit_->unsetMachine();
        }
    }
}
References controlUnit_, TTAMachine::Component::machine(), and TTAMachine::ControlUnit::unsetMachine().
Referenced by TTAMachine::ControlUnit::unsetMachine().
writeToADF()
void TTAMachine::Machine::writeToADF (const std::string & adfFileName) const
Definition at line 907 of file Machine.cc.
{
    ADFSerializer serializer;
    serializer.setDestinationFile(adfFileName);
    serializer.writeMachine(*this);
}
References XMLSerializer::setDestinationFile(), and ADFSerializer::writeMachine().
Referenced by BlocksTranslator::BuildTTAModel().
Member Data Documentation
addressSpaces_
ComponentContainer<AddressSpace> TTAMachine::Machine::addressSpaces_ private
Contains all the address spaces of the machine.
Definition at line 296 of file Machine.hh.
Referenced by addAddressSpace(), addressSpaceNavigator(), deleteAddressSpace(), loadState(), and saveState().
alwaysWriteResults_
bool TTAMachine::Machine::alwaysWriteResults_ private
Definition at line 319 of file Machine.hh.
Referenced by alwaysWriteResults(), saveState(), and setAlwaysWriteResults().
bitness64_
bool TTAMachine::Machine::bitness64_ private
Definition at line 330 of file Machine.hh.
Referenced by is64bit(), saveState(), and set64bits().
bridges_
ComponentContainer<Bridge> TTAMachine::Machine::bridges_ private
Contains all the bridges of the machine.
Definition at line 298 of file Machine.hh.
Referenced by addBridge(), bridgeNavigator(), deleteBridge(), loadState(), and saveState().
busses_
ComponentContainer<Bus> TTAMachine::Machine::busses_ private
Contains all the busses attached to the machine.
Definition at line 284 of file Machine.hh.
Referenced by addBus(), busNavigator(), loadState(), removeBus(), saveState(), and setBusPosition().
controlUnit_
ControlUnit* TTAMachine::Machine::controlUnit_ private
Global control unit.
Definition at line 305 of file Machine.hh.
Referenced by controlUnit(), loadState(), saveState(), setGlobalControl(), unsetGlobalControl(), and ~Machine().
doValidityChecks_
bool TTAMachine::Machine::doValidityChecks_ private
Tells whether to do validity checks or not.
Definition at line 308 of file Machine.hh.
Referenced by Machine(), and machineTester().
dummyMachineTester_
DummyMachineTester* TTAMachine::Machine::dummyMachineTester_ private
Dummy machine tester for the machine.
Definition at line 312 of file Machine.hh.
Referenced by machineTester(), and ~Machine().
EMPTY_ITEMP_NAME_
const std::string TTAMachine::Machine::EMPTY_ITEMP_NAME_ private
Definition at line 315 of file Machine.hh.
Referenced by loadState(), and Machine().
functionUnits_
ComponentContainer<FunctionUnit> TTAMachine::Machine::functionUnits_ private
Contains all the function units of the machine.
Definition at line 294 of file Machine.hh.
Referenced by addFunctionUnit(), functionUnitNavigator(), loadState(), removeFunctionUnit(), and saveState().
fuOrdered_
bool TTAMachine::Machine::fuOrdered_ private
Definition at line 326 of file Machine.hh.
Referenced by isFUOrdered(), saveState(), and setFUOrdered().
immediateSlots_
ComponentContainer<ImmediateSlot> TTAMachine::Machine::immediateSlots_ private
Contains all the immediate slots of the machine.
Definition at line 300 of file Machine.hh.
Referenced by addImmediateSlot(), deleteImmediateSlot(), immediateSlotNavigator(), loadState(), and saveState().
immediateUnits_
ComponentContainer<ImmediateUnit> TTAMachine::Machine::immediateUnits_ private
Contains all the immediate units of the machine.
Definition at line 292 of file Machine.hh.
Referenced by addImmediateUnit(), immediateUnitNavigator(), loadState(), removeImmediateUnit(), and saveState().
instructionTemplates_
ComponentContainer<InstructionTemplate> TTAMachine::Machine::instructionTemplates_ private
Contains all the instruction templates of the machine.
Definition at line 288 of file Machine.hh.
Referenced by addInstructionTemplate(), deleteInstructionTemplate(), instructionTemplateNavigator(), loadState(), and saveState().
littleEndian_
bool TTAMachine::Machine::littleEndian_ private
Definition at line 328 of file Machine.hh.
Referenced by isLittleEndian(), saveState(), and setLittleEndian().
machineTester_
MachineTester* TTAMachine::Machine::machineTester_ private
Machine tester for the machine.
Definition at line 310 of file Machine.hh.
Referenced by machineTester(), and ~Machine().
operationTriggeredFormats_
ComponentContainer<OperationTriggeredFormat> TTAMachine::Machine::operationTriggeredFormats_ private
Contains all the OTA Formats of the machine.
Definition at line 302 of file Machine.hh.
Referenced by addOperationTriggeredFormat(), deleteOperationTriggeredFormat(), loadState(), operationTriggeredFormatNavigator(), and saveState().
OSKEY_ALWAYS_WRITE_BACK_RESULTS
const string TTAMachine::Machine::OSKEY_ALWAYS_WRITE_BACK_RESULTS = "always-write-back" static
ObjectState attribute key for always-write-back-results.
Definition at line 251 of file Machine.hh.
Referenced by ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), loadState(), and saveState().
OSKEY_FUNCTION_UNITS_ORDERED
const string TTAMachine::Machine::OSKEY_FUNCTION_UNITS_ORDERED = "fu-ordered" static
ObjectState attribute key for function units ordered in order of their sequential presence in ADF.
Definition at line 256 of file Machine.hh.
Referenced by ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), loadState(), and saveState().
OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS
const string TTAMachine::Machine::OSKEY_TRIGGER_INVALIDATES_OLD_RESULTS = "trigger-invalidates" static
ObjectState attribute key for trigger-invalidates-old-results.
Definition at line 253 of file Machine.hh.
Referenced by ADFSerializer::convertToMachineFormat(), ADFSerializer::convertToMDFFormat(), loadState(), and saveState().
OSNAME_MACHINE
const string TTAMachine::Machine::OSNAME_MACHINE = "machine" static
ObjectState name for Machine.
Definition at line 249 of file Machine.hh.
Referenced by ADFSerializer::convertToMachineFormat(), loadState(), and saveState().
registerFiles_
ComponentContainer<RegisterFile> TTAMachine::Machine::registerFiles_ private
Contains all the register files of the machine.
Definition at line 290 of file Machine.hh.
Referenced by addRegisterFile(), loadState(), registerFileNavigator(), removeRegisterFile(), and saveState().
sockets_
ComponentContainer<Socket> TTAMachine::Machine::sockets_ private
Contains all the sockets attached to the machine.
Definition at line 286 of file Machine.hh.
Referenced by addSocket(), loadState(), removeSocket(), saveState(), and socketNavigator().
triggerInvalidatesResults_
bool TTAMachine::Machine::triggerInvalidatesResults_ private
Definition at line 322 of file Machine.hh.
Referenced by saveState(), setTriggerInvalidatesResults(), and triggerInvalidatesResults().
The documentation for this class was generated from the following files:
Machine.hh
Machine.cc