OpenASIP: LLVMAliasAnalyzer Class Reference
LLVMAliasAnalyzer Class Reference
#include <LLVMAliasAnalyzer.hh>
Public Member Functions
LLVMAliasAnalyzer ()
virtual bool isAddressTraceable (DataDependenceGraph &ddg, const ProgramOperation &pop)
virtual AliasingResult analyze (DataDependenceGraph &ddg, const ProgramOperation &pop1, const ProgramOperation &pop2, MoveNodeUse::BBRelation bbInfo)
virtual void setLLVMAA (llvm::AliasAnalysis *AA)
~LLVMAliasAnalyzer ()
Public Member Functions inherited from MemoryAliasAnalyzer
virtual void initProcedure (TTAProgram::Procedure &)
virtual ~MemoryAliasAnalyzer ()
Private Attributes
llvm::AliasAnalysis * AA_
Additional Inherited Members
Public Types inherited from MemoryAliasAnalyzer
enum AliasingResult { ALIAS_FALSE = 0 , ALIAS_TRUE = 1 , ALIAS_UNKNOWN = 2 , ALIAS_PARTIAL = 3 }
Protected Member Functions inherited from MemoryAliasAnalyzer
AliasingResult compareIndeces (int index1, int index2, const ProgramOperation &pop1, const ProgramOperation &pop2)
Static Protected Member Functions inherited from MemoryAliasAnalyzer
static const MoveNode * addressOperandMove (const ProgramOperation &po)
static TwoPartAddressOperandDetection findTwoPartAddressOperands (const ProgramOperation &po)
static const MoveNode * searchLoopIndexBasedIncrement (DataDependenceGraph &ddg, const MoveNode &mn, long &loopIncrement)
static const MoveNode * findIncrement (const MoveNode &mn, long &increment)
static const MoveNode * detectConstantScale (const MoveNode &mn, int &shiftAmount)
Detailed Description
Definition at line 54 of file LLVMAliasAnalyzer.hh.
Constructor & Destructor Documentation
LLVMAliasAnalyzer()
LLVMAliasAnalyzer::LLVMAliasAnalyzer ()
Definition at line 68 of file LLVMAliasAnalyzer.cc.
{
    AA_ = NULL;
}
References AA_.
~LLVMAliasAnalyzer()
LLVMAliasAnalyzer::~LLVMAliasAnalyzer ()
Definition at line 161 of file LLVMAliasAnalyzer.cc.
{}
Member Function Documentation
analyze()
MemoryAliasAnalyzer::AliasingResult LLVMAliasAnalyzer::analyze (DataDependenceGraph & ddg, const ProgramOperation & pop1, const ProgramOperation & pop2, MoveNodeUse::BBRelation bbInfo) virtual
Given two program operation, aswer question if memory accesed by those operations aliases.
If both POs access same memory returns true, if is sure the memory is not same, returns false. Returns unknown in case memory accesses may alias, or if there is partial alias.
Implements MemoryAliasAnalyzer.
Definition at line 96 of file LLVMAliasAnalyzer.cc.
{
    if (bbInfo) {
        return ALIAS_UNKNOWN;
    }
    if (!isAddressTraceable(ddg, pop1) ||
        !isAddressTraceable(ddg, pop2) ||
        AA_ == NULL) {
        return ALIAS_UNKNOWN;
    }
    const llvm::MachineInstr* instr1 = pop1.machineInstr();
    const llvm::MachineInstr* instr2 = pop2.machineInstr();
    llvm::MachineInstr::mmo_iterator begin1 =
        instr1->memoperands_begin();
    // Machine instruction could in theory have several memory operands.
    // In practice it is usually just one.
    MemoryAliasAnalyzer::AliasingResult result = ALIAS_UNKNOWN;
    while (begin1 != instr1->memoperands_end()) {
        const llvm::Value* val1 = (*begin1)->getValue();
        uint64_t size1 = (*begin1)->getSize();
        llvm::MachineInstr::mmo_iterator begin2 =
            instr2->memoperands_begin();
        while (begin2 != instr2->memoperands_end()) {
            const llvm::Value* val2 = (*begin2)->getValue();
            uint64_t size2 = (*begin2)->getSize();
            if (val1 && val2) {
                AliasResult res =
                    AA_->alias(val1, size1, val2, size2);
                if (res == MayAlias || res == PartialAlias) {
                    result = ALIAS_UNKNOWN;
                }
                if (res == MustAlias) {
                    result = ALIAS_TRUE;
                }
                if (res == NoAlias) {
                    result = ALIAS_FALSE;
                }
            } else {
                result = ALIAS_UNKNOWN;
            }
            begin2++;
        }
        begin1++;
    }
    return result;
}
References AA_, MemoryAliasAnalyzer::ALIAS_FALSE, MemoryAliasAnalyzer::ALIAS_TRUE, MemoryAliasAnalyzer::ALIAS_UNKNOWN, isAddressTraceable(), ProgramOperation::machineInstr(), MayAlias, MustAlias, NoAlias, and PartialAlias.
isAddressTraceable()
bool LLVMAliasAnalyzer::isAddressTraceable (DataDependenceGraph & ddg, const ProgramOperation & pop) virtual
Checks whether the analyzer knows anything about the address.
ie. if it can return true or false to some query concerning this address.
Returns
true if analyzer can know something about the address.
Implements MemoryAliasAnalyzer.
Definition at line 73 of file LLVMAliasAnalyzer.cc.
{
    // If the ProgramOperation has access to it's originating LLVM MachineInstr
    // and MachineInstr have some memory operands we can try tracing memory
    // accessed.
    const llvm::MachineInstr* instr = po.machineInstr();
    if (instr && !instr->memoperands_empty()) {
        return true;
    } else {
        return false;
    }
}
References ProgramOperation::machineInstr().
Referenced by analyze().
setLLVMAA()
void LLVMAliasAnalyzer::setLLVMAA (llvm::AliasAnalysis * AA) virtual
Sets active Alias Analyzer picked from LLVM.
Definition at line 157 of file LLVMAliasAnalyzer.cc.
{
    AA_ = AA;
}
References AA_.
Referenced by DataDependenceGraphBuilder::build(), and DataDependenceGraphBuilder::build().
Member Data Documentation
AA_
llvm::AliasAnalysis* LLVMAliasAnalyzer::AA_ private
Definition at line 68 of file LLVMAliasAnalyzer.hh.
Referenced by analyze(), LLVMAliasAnalyzer(), and setLLVMAA().
The documentation for this class was generated from the following files:
LLVMAliasAnalyzer.hh
LLVMAliasAnalyzer.cc