OpenASIP: SegmentFactory Class Reference
SegmentFactory Class Reference
#include <SegmentFactory.hh>
Public Member Functions
SegmentFactory (EditPolicyFactory &editPolicyFactory)
virtual ~SegmentFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
SegmentFactory & operator= (SegmentFactory &old)
Assignment not allowed.
SegmentFactory (SegmentFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating segment EditParts corresponding to a given Machine Segment object.
Definition at line 45 of file SegmentFactory.hh.
Constructor & Destructor Documentation
SegmentFactory() [1/2]
SegmentFactory::SegmentFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 53 of file SegmentFactory.cc.
                                                                  :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new SocketFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~SegmentFactory()
SegmentFactory::~SegmentFactory () virtual
The Destructor.
Definition at line 62 of file SegmentFactory.cc.
{
}
SegmentFactory() [2/2]
SegmentFactory::SegmentFactory (SegmentFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * SegmentFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a segment.
Parameters
component Segment of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the Segment class.
Implements Factory.
Definition at line 73 of file SegmentFactory.cc.
{
    Segment* segment = dynamic_cast<Segment*>(component);
    if (segment != NULL) {
        EditPart* segmentEditPart = new EditPart();
        segmentEditPart->setModel(segment);
        SegmentFigure* fig = new SegmentFigure(segment->parentBus()->width());
        segmentEditPart->setFigure(fig);
        SocketBusConnFactory connFactory;
        for (int j = 0; j < segment->connectionCount(); j++) {
            vector<Factory*>::const_iterator i = factories_.begin();
            for (i = factories_.begin(); i != factories_.end(); i++) {
                EditPart* socketEditPart =
                    (*i)->createEditPart((MachinePart*)segment->connection(j));
                if (socketEditPart != NULL) {
                    socketEditPart->addChild(
                        connFactory.createConnection(
                            socketEditPart, segmentEditPart));
                    break;
                }
            }
        }
        EditPolicy* editPolicy = editPolicyFactory_.createSegmentEditPolicy();
        if (editPolicy != NULL) {
            segmentEditPart->installEditPolicy(editPolicy);
        }
        return segmentEditPart;
    } else {
        return NULL;
    }
}
References EditPart::addChild(), TTAMachine::Segment::connection(), TTAMachine::Segment::connectionCount(), SocketBusConnFactory::createConnection(), EditPolicyFactory::createSegmentEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::Segment::parentBus(), EditPart::setFigure(), EditPart::setModel(), and TTAMachine::Bus::width().
operator=()
SegmentFactory & SegmentFactory::operator= (SegmentFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
SegmentFactory.hh
SegmentFactory.cc