OpenASIP: ProximClearConsoleCmd Class Reference
ProximClearConsoleCmd Class Reference
#include <ProximClearConsoleCmd.hh>
Public Member Functions
ProximClearConsoleCmd ()
virtual ~ProximClearConsoleCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximClearConsoleCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for clearing the console window in Proxim.
Definition at line 41 of file ProximClearConsoleCmd.hh.
Constructor & Destructor Documentation
ProximClearConsoleCmd()
ProximClearConsoleCmd::ProximClearConsoleCmd ()
The Constructor.
Definition at line 42 of file ProximClearConsoleCmd.cc.
                                            :
    GUICommand("Clear Console", NULL) {
    }
Referenced by create().
~ProximClearConsoleCmd()
ProximClearConsoleCmd::~ProximClearConsoleCmd () virtual
The Destructor.
Definition at line 50 of file ProximClearConsoleCmd.cc.
{
}
Member Function Documentation
create()
ProximClearConsoleCmd * ProximClearConsoleCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 95 of file ProximClearConsoleCmd.cc.
{
    return new ProximClearConsoleCmd();
}
References ProximClearConsoleCmd().
Do()
bool ProximClearConsoleCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 58 of file ProximClearConsoleCmd.cc.
{
    wxWindow* window = wxGetApp().GetTopWindow()->FindWindow(
        ProximConstants::ID_CONSOLE_WINDOW);
    assert(window != NULL);
    ConsoleWindow* console = dynamic_cast<ConsoleWindow*>(window);
    assert(console != NULL);
    console->clear();
    return true;
}
References assert, ConsoleWindow::clear(), and ProximConstants::ID_CONSOLE_WINDOW.
icon()
std::string ProximClearConsoleCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 75 of file ProximClearConsoleCmd.cc.
{
    return "clear_console.png";
}
id()
int ProximClearConsoleCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 84 of file ProximClearConsoleCmd.cc.
{
    return ProximConstants::COMMAND_CLEAR_CONSOLE;
}
References ProximConstants::COMMAND_CLEAR_CONSOLE.
isEnabled()
bool ProximClearConsoleCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
True if the console window exists.
Implements GUICommand.
Definition at line 106 of file ProximClearConsoleCmd.cc.
{
    wxWindow* window = wxGetApp().GetTopWindow()->FindWindow(
        ProximConstants::ID_CONSOLE_WINDOW);
    if (window == NULL) {
    return false;
    } else {
    return true;
    }
}
References ProximConstants::ID_CONSOLE_WINDOW.
The documentation for this class was generated from the following files:
ProximClearConsoleCmd.hh
ProximClearConsoleCmd.cc