OpenASIP: RFGuardDialog Class Reference
RFGuardDialog Class Reference
#include <RFGuardDialog.hh>
Public Member Functions
RFGuardDialog (wxWindow *parent, TTAMachine::Bus *bus, TTAMachine::RegisterGuard *guard=NULL)
virtual ~RFGuardDialog ()
virtual bool TransferDataToWindow ()
Private Types
enum {
ID_LABEL_NAME = 10000 , ID_RF_NAME , ID_LABEL_INDEX , ID_RF_INDEX ,
ID_INVERTED , ID_HELP , ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
void onRFChoice (wxCommandEvent &event)
void onOK (wxCommandEvent &event)
void onCancel (wxCommandEvent &event)
const TTAMachine::RegisterFile * selectedRF () const
void setTexts ()
Private Attributes
wxChoice * nameChoice_
Choice widget for register file name selection.
wxChoice * indexChoice_
Choice widget for register index selection.
wxCheckBox * invertedBox_
Checkbox widget for the inverted flag.
bool inverted_
Inverted flag of the guard.
bool newInverted_
Modified inverted flag of the guard.
int index_
Register index of the guard.
int newIndex_
Modified register index of the guard.
const TTAMachine::RegisterFile * rf_
Guard register.
TTAMachine::Bus * bus_
Parent bus of the register guard.
bool adding_
True if a new guard is being added, false otherwise.
Detailed Description
Dialog for editing register file guard properties.
Definition at line 46 of file RFGuardDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LABEL_NAME
ID_RF_NAME
ID_LABEL_INDEX
ID_RF_INDEX
ID_INVERTED
ID_HELP
ID_LINE
Definition at line 86 of file RFGuardDialog.hh.
         {
        ID_LABEL_NAME = 10000,
        ID_RF_NAME,
        ID_LABEL_INDEX,
        ID_RF_INDEX,
        ID_INVERTED,
        ID_HELP,
        ID_LINE
    };
Constructor & Destructor Documentation
RFGuardDialog()
RFGuardDialog::RFGuardDialog (wxWindow * parent, TTAMachine::Bus * bus, TTAMachine::RegisterGuard * guard = NULL)
The Constructor.
Parameters
parent Parent window of the dialog.
Definition at line 62 of file RFGuardDialog.cc.
                         :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    inverted_(false),
    newInverted_(false),
    index_(0),
    newIndex_(0),
    rf_(NULL),
    bus_(bus),
    adding_(false) {
    if (guard == NULL) {
        // adding a new guard
        adding_ = true;
        rf_ = bus_->machine()->registerFileNavigator().item(0);
    } else {
        // editing an old guard
        rf_ = guard->registerFile();
        index_ = guard->registerIndex();
        newIndex_ = index_;
        inverted_ = guard->isInverted();
        // The guard is temporarily deleted to simplify legality checks.
        delete guard;
        guard = NULL;
    }
    newInverted_ = inverted_;
    createContents(this, true, true);
    // set pointers to the dialog widgets
    nameChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_RF_NAME));
    indexChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_RF_INDEX));
    invertedBox_ = dynamic_cast<wxCheckBox*>(FindWindow(ID_INVERTED));
    invertedBox_->SetValidator(wxGenericValidator(&newInverted_));
    indexChoice_->SetValidator(wxGenericValidator(&newIndex_));
    // set widget texts.
    setTexts();
}
~RFGuardDialog()
RFGuardDialog::~RFGuardDialog () virtual
The Destructor.
Definition at line 111 of file RFGuardDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * RFGuardDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window.
Code generated with wxDesigner.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 347 of file RFGuardDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxGridSizer *item1 = new wxGridSizer( 2, 0, 0 );
    wxStaticText *item2 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Register File Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALL, 5 );
    wxString *strs3 = (wxString*) NULL;
    wxChoice *item3 = new wxChoice( parent, ID_RF_NAME, wxDefaultPosition, wxSize(100,-1), 0, strs3, 0 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    wxStaticText *item4 = new wxStaticText( parent, ID_LABEL_INDEX, wxT("Register Index:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALL, 5 );
    wxString *strs5 = (wxString*) NULL;
    wxChoice *item5 = new wxChoice( parent, ID_RF_INDEX, wxDefaultPosition, wxSize(100,-1), 0, strs5, 0 );
    item1->Add( item5, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxCheckBox *item6 = new wxCheckBox( parent, ID_INVERTED, wxT("Inverted"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item6, 0, wxALL, 5 );
    wxStaticLine *item7 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item7, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item9 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_HELP, ID_INVERTED, ID_LABEL_INDEX, ID_LABEL_NAME, ID_LINE, ID_RF_INDEX, and ID_RF_NAME.
onCancel()
void RFGuardDialog::onCancel (wxCommandEvent & event) private
Cancels the dialog effects by creating the original register guard.
Closes the dialog.
Definition at line 328 of file RFGuardDialog.cc.
{
    if (adding_ == false) {
        new RegisterGuard(inverted_, *rf_, index_, bus_);
    }
    EndModal(wxID_CANCEL);
}
References adding_, bus_, index_, inverted_, and rf_.
onOK()
void RFGuardDialog::onOK (wxCommandEvent & event) private
Updates the guard object when the OK-button is pressed.
Closes the dialog.
Definition at line 244 of file RFGuardDialog.cc.
{
    TransferDataFromWindow();
    try {
        // get currently selected index and its string representation
        int indexSelection = indexChoice_->GetSelection();
        assert(indexSelection != wxNOT_FOUND);
        wxString choiceText = indexChoice_->GetString(indexSelection);
        // get the string that resembles all indices
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format fmtAll = prodeTexts->text(ProDeTextGenerator::TXT_ALL);
        bool singleGuard = true;
        // check if user has selected all indices
        if (choiceText.IsSameAs(WxConversion::toWxString(fmtAll.str()))) {
            singleGuard = false;
        }
        if (!adding_ || (adding_ && singleGuard)) {
            // add / edit one guard
            new RegisterGuard(newInverted_, *selectedRF(), newIndex_,
                              bus_);
        } else {
            // add new guard for every index
            string rfNameSel = WxConversion::toString(
                            nameChoice_->GetStringSelection());
            // loop all bus guards and mark old guards (if there is any)
            // of the selected register file name to be deleted
            std::vector<RegisterGuard*> toBeDeleted;
            for (int i = 0; i < bus_->guardCount(); ++i) {
                Guard* g = bus_->guard(i);
                RegisterGuard* rfGuard =
                    dynamic_cast<RegisterGuard*>(g);
                if (rfGuard != NULL) {
                    string rfName = rfGuard->registerFile()->name();
                    // if register file names match
                    if (rfName.compare(rfNameSel) == 0) {
                        // if inverted setting is same
                        if (rfGuard->isInverted() == newInverted_) {
                            toBeDeleted.push_back(rfGuard);
                        }
                    }
                }
            }
            // delete old guards
            for (unsigned int i = 0; i < toBeDeleted.size(); ++i) {
                if (toBeDeleted.at(i) != NULL) {
                    delete toBeDeleted.at(i);
                    toBeDeleted.at(i) = NULL;
                }
            }
            // create new guard for every file register's index
            for (int index = 0; index < selectedRF()->numberOfRegisters();
                 ++index) {
                new RegisterGuard(newInverted_, *selectedRF(), index,
                              bus_);
            }
        }
    } catch (ComponentAlreadyExists& e) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_GUARD_EXISTS);
        InformationDialog dialog(
            this, WxConversion::toWxString(message.str()));
        dialog.ShowModal();
        return;
    }
    EndModal(wxID_OK);
}
References adding_, assert, bus_, TTAMachine::Bus::guard(), TTAMachine::Bus::guardCount(), indexChoice_, ProDeTextGenerator::instance(), TTAMachine::Guard::isInverted(), ProDeTextGenerator::MSG_ERROR_GUARD_EXISTS, TTAMachine::Component::name(), nameChoice_, newIndex_, newInverted_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::RegisterGuard::registerFile(), selectedRF(), Texts::TextGenerator::text(), WxConversion::toString(), WxConversion::toWxString(), and ProDeTextGenerator::TXT_ALL.
onRFChoice()
void RFGuardDialog::onRFChoice (wxCommandEvent & event) private
Updates the index choice when the register file selection is changed.
Definition at line 196 of file RFGuardDialog.cc.
{
    int selection = indexChoice_->GetSelection();
    indexChoice_->Clear();
    const RegisterFile* rf = selectedRF();
    for (int i = 0; i < rf->numberOfRegisters(); i++) {
        wxString index = WxConversion::toWxString(i);
        indexChoice_->Append(index);
    }
    // add choice to create guard for every index
    if (adding_) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format fmtAll = prodeTexts->text(ProDeTextGenerator::TXT_ALL);
        indexChoice_->Append(WxConversion::toWxString(fmtAll.str()));
    }
    if (static_cast<int>(indexChoice_->GetCount()) >= selection) {
        indexChoice_->SetSelection(selection);
    } else {
        indexChoice_->SetSelection(0);
    }
}
References adding_, indexChoice_, ProDeTextGenerator::instance(), TTAMachine::BaseRegisterFile::numberOfRegisters(), selectedRF(), Texts::TextGenerator::text(), WxConversion::toWxString(), and ProDeTextGenerator::TXT_ALL.
selectedRF()
const RegisterFile * RFGuardDialog::selectedRF () const private
Returns a pointer to the selected register file.
Returns
Pointer to the selected refister file.
Definition at line 229 of file RFGuardDialog.cc.
{
    string name = WxConversion::toString(nameChoice_->GetStringSelection());
    Machine::RegisterFileNavigator navigator =
        bus_->machine()->registerFileNavigator();
    RegisterFile* rf = navigator.item(name);
    return rf;
}
References bus_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), nameChoice_, TTAMachine::Machine::registerFileNavigator(), and WxConversion::toString().
Referenced by onOK(), onRFChoice(), and TransferDataToWindow().
setTexts()
void RFGuardDialog::setTexts () private
Sets texts for widgets.
Definition at line 119 of file RFGuardDialog.cc.
{
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(
        ProDeTextGenerator::TXT_RF_GUARD_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_RF_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_INDEX),
                          ProDeTextGenerator::TXT_LABEL_REGISTER_INDEX);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_INVERTED),
                          ProDeTextGenerator::TXT_LABEL_INVERTED);
}
References ID_HELP, ID_INVERTED, ID_LABEL_INDEX, ID_LABEL_NAME, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_LABEL_INVERTED, ProDeTextGenerator::TXT_LABEL_REGISTER_INDEX, ProDeTextGenerator::TXT_LABEL_RF_NAME, and ProDeTextGenerator::TXT_RF_GUARD_DIALOG_TITLE.
TransferDataToWindow()
bool RFGuardDialog::TransferDataToWindow () virtual
Transfers data from the Guard object to the dialog widgets.
Returns
true, if the transfer was succesful, false otherwise.
Definition at line 156 of file RFGuardDialog.cc.
{
    nameChoice_->Clear();
    indexChoice_->Clear();
    Machine::RegisterFileNavigator navigator =
        bus_->machine()->registerFileNavigator();
    // set register file name
    for (int i = 0; i < navigator.count(); i++) {
        wxString name = WxConversion::toWxString(navigator.item(i)->name());
        nameChoice_->Append(name);
    }
    nameChoice_->SetStringSelection(WxConversion::toWxString(rf_->name()));
    // set register index
    for (int i = 0; i < selectedRF()->numberOfRegisters(); i++) {
        wxString index = WxConversion::toWxString(i);
        indexChoice_->Append(index);
    }
    // add choice to create guard for every index
    if (adding_) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format fmtAll = prodeTexts->text(ProDeTextGenerator::TXT_ALL);
        indexChoice_->Append(WxConversion::toWxString(fmtAll.str()));
    }
    indexChoice_->SetSelection(newIndex_);
    // set inverted flag
    invertedBox_->SetValue(newInverted_);
    return wxDialog::TransferDataToWindow();
}
References adding_, bus_, TTAMachine::Machine::Navigator< ComponentType >::count(), indexChoice_, ProDeTextGenerator::instance(), invertedBox_, TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::Component::machine(), TTAMachine::Component::name(), nameChoice_, newIndex_, newInverted_, TTAMachine::BaseRegisterFile::numberOfRegisters(), TTAMachine::Machine::registerFileNavigator(), rf_, selectedRF(), Texts::TextGenerator::text(), WxConversion::toWxString(), and ProDeTextGenerator::TXT_ALL.
Member Data Documentation
adding_
bool RFGuardDialog::adding_ private
True if a new guard is being added, false otherwise.
Definition at line 83 of file RFGuardDialog.hh.
Referenced by onCancel(), onOK(), onRFChoice(), and TransferDataToWindow().
bus_
TTAMachine::Bus* RFGuardDialog::bus_ private
Parent bus of the register guard.
Definition at line 81 of file RFGuardDialog.hh.
Referenced by onCancel(), onOK(), selectedRF(), and TransferDataToWindow().
index_
int RFGuardDialog::index_ private
Register index of the guard.
Definition at line 75 of file RFGuardDialog.hh.
Referenced by onCancel().
indexChoice_
wxChoice* RFGuardDialog::indexChoice_ private
Choice widget for register index selection.
Definition at line 66 of file RFGuardDialog.hh.
Referenced by onOK(), onRFChoice(), and TransferDataToWindow().
inverted_
bool RFGuardDialog::inverted_ private
Inverted flag of the guard.
Definition at line 71 of file RFGuardDialog.hh.
Referenced by onCancel().
invertedBox_
wxCheckBox* RFGuardDialog::invertedBox_ private
Checkbox widget for the inverted flag.
Definition at line 68 of file RFGuardDialog.hh.
Referenced by TransferDataToWindow().
nameChoice_
wxChoice* RFGuardDialog::nameChoice_ private
Choice widget for register file name selection.
Definition at line 64 of file RFGuardDialog.hh.
Referenced by onOK(), selectedRF(), and TransferDataToWindow().
newIndex_
int RFGuardDialog::newIndex_ private
Modified register index of the guard.
Definition at line 77 of file RFGuardDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
newInverted_
bool RFGuardDialog::newInverted_ private
Modified inverted flag of the guard.
Definition at line 73 of file RFGuardDialog.hh.
Referenced by onOK(), and TransferDataToWindow().
rf_
const TTAMachine::RegisterFile* RFGuardDialog::rf_ private
Guard register.
Definition at line 79 of file RFGuardDialog.hh.
Referenced by onCancel(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
RFGuardDialog.hh
RFGuardDialog.cc