OpenASIP: EditMachineCmd Class Reference
EditMachineCmd Class Reference
#include <EditMachineCmd.hh>
Public Member Functions
EditMachineCmd ()
virtual ~EditMachineCmd ()
virtual bool Do ()
virtual int id () const
virtual EditMachineCmd * create () const
virtual std::string icon () const
virtual std::string shortName () const
virtual bool isEnabled ()
Public Member Functions inherited from EditorCommand
EditorCommand (std::string name, wxWindow *parent=NULL)
virtual ~EditorCommand ()
void setView (wxView *view)
wxView * view () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Definition at line 39 of file EditMachineCmd.hh.
Constructor & Destructor Documentation
EditMachineCmd()
EditMachineCmd::EditMachineCmd ()
The Constructor.
Definition at line 47 of file EditMachineCmd.cc.
                              :
    EditorCommand(ProDeConstants::CMD_NAME_EDIT_MACHINE) {
}
Referenced by create().
~EditMachineCmd()
EditMachineCmd::~EditMachineCmd () virtual
The Destructor.
Definition at line 55 of file EditMachineCmd.cc.
{
}
Member Function Documentation
create()
EditMachineCmd * EditMachineCmd::create () const virtual
Creates and returns a new instance of this command.
Returns
A new instance of this command.
Implements GUICommand.
Definition at line 105 of file EditMachineCmd.cc.
{
    return new EditMachineCmd();
}
References EditMachineCmd().
Do()
bool EditMachineCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements GUICommand.
Definition at line 66 of file EditMachineCmd.cc.
                   {
    assert(parentWindow() != NULL);
    assert(view() != NULL);
    Model* model = dynamic_cast<MDFDocument*>(
        view()->GetDocument())->getModel();
    model->pushToStack();
    MachineDialog dialog(parentWindow(), *model->getMachine());
    if (dialog.ShowModal() == wxID_OK) {
        model->notifyObservers();
        return true;
    } else {
        // Cancel button was pressed, templates are not modified.
        model->popFromStack();
        return false;
    }
}
References assert, Model::getMachine(), Model::notifyObservers(), GUICommand::parentWindow(), Model::popFromStack(), Model::pushToStack(), and EditorCommand::view().
icon()
std::string EditMachineCmd::icon () const virtual
Returns path to the command's icon file.
Returns
path to the command's icon file.
Reimplemented from EditorCommand.
Definition at line 116 of file EditMachineCmd.cc.
{
    return ProDeConstants::CMD_ICON_EDIT_MACHINE;
}
References ProDeConstants::CMD_ICON_EDIT_MACHINE.
id()
int EditMachineCmd::id () const virtual
Returns id of this command.
Returns
Id of this command.
Implements GUICommand.
Definition at line 94 of file EditMachineCmd.cc.
{
    return ProDeConstants::COMMAND_EDIT_MACHINE;
}
References ProDeConstants::COMMAND_EDIT_MACHINE.
isEnabled()
bool EditMachineCmd::isEnabled () virtual
Returns true when the command is executable, false when not.
This command is executable when a document is open.
Returns
True, if a document is open.
Reimplemented from EditorCommand.
Definition at line 140 of file EditMachineCmd.cc.
{
    wxDocManager* manager = wxGetApp().docManager();
    if (manager->GetCurrentView() != NULL) {
        return true;
    }
    return false;
}
shortName()
std::string EditMachineCmd::shortName () const virtual
Returns short version of the command name.
Returns
Short version of the command name.
Reimplemented from GUICommand.
Definition at line 127 of file EditMachineCmd.cc.
{
    return ProDeConstants::CMD_SNAME_EDIT_MACHINE;
}
References ProDeConstants::CMD_SNAME_EDIT_MACHINE.
The documentation for this class was generated from the following files:
EditMachineCmd.hh
EditMachineCmd.cc