OpenASIP: ProximSetMachineWinStatusCmd Class Reference
ProximSetMachineWinStatusCmd Class Reference
#include <ProximSetMachineWinStatusCmd.hh>
Public Member Functions
ProximSetMachineWinStatusCmd (EditPart *part)
virtual ~ProximSetMachineWinStatusCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
EditPart * part_
Detailed Description
Command for setting the machine window status bar text.
Definition at line 44 of file ProximSetMachineWinStatusCmd.hh.
Constructor & Destructor Documentation
ProximSetMachineWinStatusCmd()
ProximSetMachineWinStatusCmd::ProximSetMachineWinStatusCmd (EditPart * part)
The Constructor.
Definition at line 43 of file ProximSetMachineWinStatusCmd.cc.
                    :
    ComponentCommand(),
    part_(part) {
}
~ProximSetMachineWinStatusCmd()
ProximSetMachineWinStatusCmd::~ProximSetMachineWinStatusCmd () virtual
The Destructor.
Definition at line 54 of file ProximSetMachineWinStatusCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximSetMachineWinStatusCmd::Do () virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implements ComponentCommand.
Definition at line 65 of file ProximSetMachineWinStatusCmd.cc.
{
    ProximMachineStateWindow* machineWindow =
        ProximToolbox::machineStateWindow();
    if (machineWindow == NULL) {
        // Machine Window does not exist.
        return false;
    }
    TTAMachine::Bus* bus = dynamic_cast<Bus*>(part_->model());
    assert(bus != NULL);
    const Program& program = ProximToolbox::program();
    Instruction
}
References assert, ProximToolbox::machineStateWindow(), EditPart::model(), part_, program, and ProximToolbox::program().
Member Data Documentation
part_
EditPart* ProximSetMachineWinStatusCmd::part_ private
Definition at line 51 of file ProximSetMachineWinStatusCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximSetMachineWinStatusCmd.hh
ProximSetMachineWinStatusCmd.cc