OpenASIP: Interpolation Class Reference
Interpolation Class Reference
#include <Interpolation.hh>
Classes
struct Pair
Public Member Functions
Interpolation (const EntryKeyFieldProperty *type)
virtual ~Interpolation ()
void quickFilter (const CostDBEntryKey &, CostDBTypes::EntryTable &)
void filter (const CostDBEntryKey &searchKey, CostDBTypes::EntryTable &components)
Public Member Functions inherited from Matcher
Matcher (const EntryKeyFieldProperty *type)
virtual ~Matcher ()
Private Member Functions
Interpolation (const Interpolation &)
Copying not allowed.
Interpolation & operator= (const Interpolation &)
Assignment not allowed.
Private Attributes
CostDBTypes::EntryTable created_
Entries created during interpolation.
Additional Inherited Members
Protected Member Functions inherited from Matcher
const EntryKeyFieldProperty * fieldType () const
bool onlyThisFieldDiffers (const EntryKeyFieldProperty *type, const CostDBEntry &entry1, const CostDBEntry &entry2) const
Detailed Description
Implementation for searching database entries.
If a value equal to the search key in the requested field is not found, interpolation of the smaller and greater field value is tried.
Definition at line 49 of file Interpolation.hh.
Constructor & Destructor Documentation
Interpolation() [1/2]
Interpolation::Interpolation (const EntryKeyFieldProperty * type)
Constructor.
Parameters
type Type of the field.
Definition at line 46 of file Interpolation.cc.
                                                              :
    Matcher(type) {
}
~Interpolation()
Interpolation::~Interpolation () virtual
Destructor.
Deallocates memory reserved for entries created during interpolation.
Definition at line 55 of file Interpolation.cc.
{
    for (CostDBTypes::EntryTable::iterator i = created_.begin();
         i != created_.end(); i++) {
        assert(*i != NULL);
        delete *i;
        *i = NULL;
    }
}
References assert, and created_.
Interpolation() [2/2]
Interpolation::Interpolation (const Interpolation &) private
Copying not allowed.
Member Function Documentation
filter()
void Interpolation::filter (const CostDBEntryKey & searchKey, CostDBTypes::EntryTable & components) virtual
Searches for database entries.
If a value equal to the search key in the requested field is not found, interpolation of the smaller and greater field value is applied. Only the best matches are returned, i.e. equal match is chosen and no interpolation is done, or if two entries has only the field to which search is applied different, the closer one to the search key is chosen for interpolation.
Parameters
searchKey Search key.
components Entries from which to find. Updated to contain entries that matched the search request.
Exceptions
TypeMismatch Interpolation was requested for field that cannot be interpolated.
KeyNotFound Some CostDBEntryStats have no value caused by missing cost data.
Implements Matcher.
Definition at line 92 of file Interpolation.cc.
{
    vector<Pair> entries;
    EntryKeyField searchField = searchKey.keyFieldOfType(*fieldType());
    for (CostDBTypes::EntryTable::iterator i = components.begin();
         i != components.end(); i++) {
        EntryKeyField field = (*i)->keyFieldOfType(*fieldType());
        bool newPair = true;
        for (vector<Pair>::iterator p = entries.begin();
             p != entries.end(); p++) {
            if ((p->smaller != 0 &&
                 !onlyThisFieldDiffers(fieldType(), *(p->smaller), *(*i))) ||
                (p->greater != 0 &&
                 !onlyThisFieldDiffers(fieldType(), *(p->greater), *(*i)))) {
                continue;
            }
            if (field.isEqual(searchField)) {
                p->smaller = *i;
                p->greater = 0;
            } else if (field.isSmaller(searchField)) {
                if (p->smaller == 0 ||
                    (p->smaller != 0 &&
                     field.isGreater(
                         p->smaller->keyFieldOfType(*fieldType())))) {
                    p->smaller = *i;
                }
            } else {
                if (!(field.isGreater(searchField))) {
                    throw TypeMismatch(__FILE__, __LINE__,
                                       "Interpolation::filter");
                }
                if (p->greater == 0 ||
                    (p->greater != 0 &&
                     field.isSmaller(
                         p->greater->keyFieldOfType(*fieldType())))) {
                    p->greater = *i;
                }
            }
            newPair = false;
            break;
        }
        if (newPair) {
            Pair pair;
            if (field.isEqual(searchField)) {
                pair.smaller = *i;
                pair.greater = 0;
            } else if (field.isSmaller(searchField)) {
                pair.smaller = *i;
                pair.greater = 0;
            } else {
                if (!(field.isGreater(searchField))) {
                    throw TypeMismatch(__FILE__, __LINE__,
                                       "Interpolation::filter");
                }
                pair.greater = *i;
                pair.smaller = 0;
            }
            entries.push_back(pair);
        }
    }
    CostDBTypes::EntryTable filtered;
    for (vector<Pair>::iterator p = entries.begin(); p != entries.end(); p++) {
        if (p->smaller != 0 &&
            p->smaller->keyFieldOfType(*fieldType()).isEqual(searchField)) {
            filtered.push_back(p->smaller);
        } else if (p->smaller != 0 && p->greater != 0) {
            CostDBEntry* newEntry = new CostDBEntry(
                *p->smaller, *p->greater, searchField);
            filtered.push_back(newEntry);
            created_.push_back(newEntry);
        }
    }
    components = filtered;
}
References created_, Matcher::fieldType(), Interpolation::Pair::greater, EntryKeyField::isEqual(), EntryKeyField::isGreater(), EntryKeyField::isSmaller(), CostDBEntryKey::keyFieldOfType(), Matcher::onlyThisFieldDiffers(), and Interpolation::Pair::smaller.
operator=()
Interpolation & Interpolation::operator= (const Interpolation &) private
Assignment not allowed.
quickFilter()
void Interpolation::quickFilter (const CostDBEntryKey & , CostDBTypes::EntryTable &) virtual
Nothing to do since no entry can be removed in linear time.
Implements Matcher.
Definition at line 70 of file Interpolation.cc.
{
}
Member Data Documentation
created_
CostDBTypes::EntryTable Interpolation::created_ private
Entries created during interpolation.
Definition at line 70 of file Interpolation.hh.
Referenced by filter(), and ~Interpolation().
The documentation for this class was generated from the following files:
Interpolation.hh
Interpolation.cc