OpenASIP: TTAProgram::CodeLabel Class Reference
TTAProgram::CodeLabel Class Reference
#include <CodeLabel.hh>
Public Member Functions
CodeLabel (const InstructionReference &ins, std::string name)
CodeLabel (const Procedure &proc)
virtual ~CodeLabel ()
virtual Address address () const
const InstructionReference instructionReference () const
const Procedure & procedure () const
Public Member Functions inherited from TTAProgram::Label
virtual ~Label ()
std::string name () const
const Scope & scope () const
void setAddress (Address address)
Private Attributes
const InstructionReference ins_
Reference to instruction corresponding to this label.
const Procedure * proc_
Procedure corresponding to this label.
Additional Inherited Members
Protected Member Functions inherited from TTAProgram::Label
Label ()
Label (const std::string &name, Address address, const Scope &scope)
void setName (const std::string &name)
void setScope (const Scope &scope)
Detailed Description
A symbolic name that stands for a location in the program.
Definition at line 49 of file CodeLabel.hh.
Constructor & Destructor Documentation
CodeLabel() [1/2]
TTAProgram::CodeLabel::CodeLabel (const InstructionReference & ins, std::string name)
Constructor.
Registers this label to the owning scope.
Parameters
ins Instruction corresponding to this label.
name Name of the label. Must be unique within the owning scope.
Exceptions
IllegalRegistration if the given instruction does not belong to a procedure, or its parent procedure does not belong to a program.
Definition at line 61 of file CodeLabel.cc.
    :
      ins_(ins) {
    proc_ = NULL;
    setName(name);
    setAddress(ins.instruction().address());
    // scope is the global scope for now
    setScope(ins.instruction().parent().parent().globalScope());
}
References TTAProgram::Instruction::address(), TTAProgram::Program::globalScope(), TTAProgram::InstructionReference::instruction(), TTAProgram::Label::name(), TTAProgram::CodeSnippet::parent(), TTAProgram::Instruction::parent(), proc_, TTAProgram::Label::setAddress(), TTAProgram::Label::setName(), and TTAProgram::Label::setScope().
CodeLabel() [2/2]
TTAProgram::CodeLabel::CodeLabel (const Procedure & proc)
An alternative constructor that takes the procedure.
Parameters
proc Procedure corresponding to this label
Exceptions
IllegalRegistration if the given procedure does not belong to a program.
Definition at line 79 of file CodeLabel.cc.
    : ins_(InstructionReference(NULL)), proc_(&proc) {
    setName(proc.name());
    setAddress(proc.startAddress());
    // scope is the global scope for now
    setScope(proc.parent().globalScope());
}
References TTAProgram::Program::globalScope(), TTAProgram::Procedure::name(), TTAProgram::CodeSnippet::parent(), TTAProgram::Label::setAddress(), TTAProgram::Label::setName(), TTAProgram::Label::setScope(), and TTAProgram::CodeSnippet::startAddress().
~CodeLabel()
TTAProgram::CodeLabel::~CodeLabel () virtual
The destructor.
Definition at line 90 of file CodeLabel.cc.
                      {
}
Member Function Documentation
address()
Address TTAProgram::CodeLabel::address () const virtual
Returns the address of the instruction or procedure corresponding to this label.
Returns
The address of the instruction or procedure corresponding to this label.
Reimplemented from TTAProgram::Label.
Definition at line 101 of file CodeLabel.cc.
{
    if (&ins_.instruction() != &NullInstruction::instance()) {
        return ins_.instruction().address();
    } else {
        return proc_->startAddress();
    }
}
References TTAProgram::Instruction::address(), ins_, TTAProgram::NullInstruction::instance(), TTAProgram::InstructionReference::instruction(), proc_, and TTAProgram::CodeSnippet::startAddress().
Referenced by TTAProgram::GlobalScope::copyAndRelocate(), TTAProgram::ProgramWriter::createBinary(), DisassemblyGridTable::loadProgram(), and SimControlLanguageCommand::parseInstructionAddressExpression().
instructionReference()
const InstructionReference TTAProgram::CodeLabel::instructionReference () const
Returns a reference to the instruction corresponding to this label.
Returns
a reference to the instruction corresponding to this label.
Exceptions
IllegalRegistration if the label points to a procedure that has no instructions.
Definition at line 117 of file CodeLabel.cc.
{
    if (&ins_.instruction() != &NullInstruction::instance()) {
        return ins_;
    } else if (proc_->instructionCount() == 0) {
        throw IllegalRegistration(__FILE__, __LINE__);
    } else {
        return proc_->parent().instructionReferenceManager().createReference(proc_->firstInstruction());
    }
}
References TTAProgram::InstructionReferenceManager::createReference(), TTAProgram::CodeSnippet::firstInstruction(), ins_, TTAProgram::NullInstruction::instance(), TTAProgram::InstructionReference::instruction(), TTAProgram::CodeSnippet::instructionCount(), TTAProgram::Program::instructionReferenceManager(), TTAProgram::CodeSnippet::parent(), and proc_.
procedure()
const Procedure & TTAProgram::CodeLabel::procedure () const
Return the procedure that contains this label.
Returns
The procedure that contains this label or the procedure at which this labels points.
Exceptions
IllegalRegistration if the label is not registered in a procedure.
Definition at line 136 of file CodeLabel.cc.
{
    if (proc_ == NULL) {
        const Procedure* proc = dynamic_cast<const Procedure*>(
            &(ins_.instruction().parent()));
        assert(proc != NULL);
        return *proc;
    } else {
        return *proc_;
    }
}
References assert, ins_, TTAProgram::InstructionReference::instruction(), TTAProgram::Instruction::parent(), and proc_.
Member Data Documentation
ins_
const InstructionReference TTAProgram::CodeLabel::ins_ private
Reference to instruction corresponding to this label.
Definition at line 63 of file CodeLabel.hh.
Referenced by address(), instructionReference(), and procedure().
proc_
const Procedure* TTAProgram::CodeLabel::proc_ private
Procedure corresponding to this label.
Definition at line 65 of file CodeLabel.hh.
Referenced by address(), CodeLabel(), instructionReference(), and procedure().
The documentation for this class was generated from the following files:
CodeLabel.hh
CodeLabel.cc