OpenASIP: ProximFUPortDetailsCmd Class Reference
ProximFUPortDetailsCmd Class Reference
#include <ProximFUPortDetailsCmd.hh>
Public Member Functions
ProximFUPortDetailsCmd (const TTAMachine::FUPort &port)
virtual ~ProximFUPortDetailsCmd ()
virtual bool Do ()
Public Member Functions inherited from ComponentCommand
ComponentCommand ()
virtual ~ComponentCommand ()
wxWindow * parentWindow ()
void setParentWindow (wxWindow *window)
Private Attributes
const TTAMachine::FUPort & port_
Function unit port to display.
Detailed Description
Command for displaying function unit port details in the machine state window component details pane.
Definition at line 46 of file ProximFUPortDetailsCmd.hh.
Constructor & Destructor Documentation
ProximFUPortDetailsCmd()
ProximFUPortDetailsCmd::ProximFUPortDetailsCmd (const TTAMachine::FUPort & port)
The Constructor.
Parameters
fu Function unit port to display.
Definition at line 55 of file ProximFUPortDetailsCmd.cc.
                                  :
    ComponentCommand(), port_(port) {
}
~ProximFUPortDetailsCmd()
ProximFUPortDetailsCmd::~ProximFUPortDetailsCmd () virtual
The Destructor.
Definition at line 64 of file ProximFUPortDetailsCmd.cc.
{
}
Member Function Documentation
Do()
bool ProximFUPortDetailsCmd::Do () virtual
Executes the command.
Implements ComponentCommand.
Definition at line 72 of file ProximFUPortDetailsCmd.cc.
{
    string fuName = port_.parentUnit()->name();
    string portName = port_.name();
    ProximMachineStateWindow* machineWin = ProximToolbox::machineStateWindow();
    MachineState& machineState = ProximToolbox::frontend()->machineState();
    // Append component type and name to the details widget.
    machineWin->appendDetails(ProximConstants::MACH_WIN_FU_PORT_LABEL);
    machineWin->appendDetails("\n" + fuName + "." + portName + "\n\n");
    const PortState& portState = machineState.portState(portName, fuName);
    machineWin->appendDetails(
        Conversion::toHexString(portState.value().unsignedValue()) + "\n");
    return true;
}
References ProximMachineStateWindow::appendDetails(), ProximToolbox::frontend(), ProximConstants::MACH_WIN_FU_PORT_LABEL, SimulatorFrontend::machineState(), ProximToolbox::machineStateWindow(), TTAMachine::Component::name(), TTAMachine::Port::name(), TTAMachine::BaseFUPort::parentUnit(), port_, MachineState::portState(), Conversion::toHexString(), SimValue::unsignedValue(), and RegisterState::value().
Member Data Documentation
port_
const TTAMachine::FUPort& ProximFUPortDetailsCmd::port_ private
Function unit port to display.
Definition at line 53 of file ProximFUPortDetailsCmd.hh.
Referenced by Do().
The documentation for this class was generated from the following files:
ProximFUPortDetailsCmd.hh
ProximFUPortDetailsCmd.cc