OpenASIP: AddRFImplementationCmd Class Reference
AddRFImplementationCmd Class Reference
#include <AddRFImplementationCmd.hh>
Public Member Functions
AddRFImplementationCmd ()
virtual ~AddRFImplementationCmd ()
virtual bool Do ()
virtual int id () const
virtual AddRFImplementationCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding implementation of a RF architecture to HDB.
Definition at line 41 of file AddRFImplementationCmd.hh.
Constructor & Destructor Documentation
AddRFImplementationCmd()
AddRFImplementationCmd::AddRFImplementationCmd ()
The Constructor.
Definition at line 49 of file AddRFImplementationCmd.cc.
                                               :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_RF_IMPLEMENTATION, NULL) {
}
Referenced by create().
~AddRFImplementationCmd()
AddRFImplementationCmd::~AddRFImplementationCmd () virtual
The Destructor.
Definition at line 57 of file AddRFImplementationCmd.cc.
{
}
Member Function Documentation
create()
AddRFImplementationCmd * AddRFImplementationCmd::create () const virtual
Creates a new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 144 of file AddRFImplementationCmd.cc.
{
    return new AddRFImplementationCmd();
}
References AddRFImplementationCmd().
Do()
bool AddRFImplementationCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 64 of file AddRFImplementationCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    HDB::RFImplementation* implementation
        = new HDB::RFImplementation("", "", "","", "", "", "");
    HDB::RFEntry* entry = NULL;
    if (browser->isRFEntrySelected()) {
        entry = manager->rfByEntryID(browser->selectedRFEntry());
    } else if (browser->isRFArchitectureSelected()) {
        int id = manager->addRFEntry();
        manager->setArchitectureForRF(id, browser->selectedRFArchitecture());
        entry = manager->rfByEntryID(id);
    } else {
        return false;
    }
    RFImplementationDialog dialog(parentWindow(), -1, *implementation);
    if (dialog.ShowModal() == wxID_OK) {
        try {
            int id =
                manager->addRFImplementation(*implementation, entry->id());
            wxGetApp().mainFrame().update();
            wxGetApp().mainFrame().browser()->selectRFImplementation(id);
        } catch (Exception& e) {
            wxString message = _T("Error:\n");
            message.Append(WxConversion::toWxString(e.errorMessage()));
            message.Append(_T("\n"));
            message.Append(WxConversion::toWxString(e.lineNum()));
             message.Append(_T(": "));
            message.Append(WxConversion::toWxString(e.fileName()));
            ErrorDialog dialog(parentWindow(), message);
            dialog.ShowModal();
            delete entry;
            delete implementation;
            return false;
        }
    } else {
        delete implementation;
    }
    delete entry;
    return true;
}
References HDB::HDBManager::addRFEntry(), HDB::HDBManager::addRFImplementation(), Exception::errorMessage(), Exception::fileName(), HDB::HDBEntry::id(), implementation, HDBBrowserWindow::isRFArchitectureSelected(), HDBBrowserWindow::isRFEntrySelected(), Exception::lineNum(), GUICommand::parentWindow(), HDB::HDBManager::rfByEntryID(), HDBBrowserWindow::selectedRFArchitecture(), HDBBrowserWindow::selectedRFEntry(), HDB::HDBManager::setArchitectureForRF(), and WxConversion::toWxString().
icon()
std::string AddRFImplementationCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 123 of file AddRFImplementationCmd.cc.
{
    return "";
}
id()
int AddRFImplementationCmd::id () const virtual
Returns the command id.
Returns
Command identifier.
Implements GUICommand.
Definition at line 133 of file AddRFImplementationCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION;
}
References HDBEditorConstants::COMMAND_ADD_RF_IMPLEMENTATION.
isEnabled()
bool AddRFImplementationCmd::isEnabled () virtual
Returns true if the command should be enabled in the tool/menubar.
Returns
True if the command is enabled, false if not.
Implements GUICommand.
Definition at line 155 of file AddRFImplementationCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    HDBBrowserWindow* browser = wxGetApp().mainFrame().browser();
    if (browser->isRFArchitectureSelected()) {
        return true;
    } else if (browser->isRFEntrySelected()) {
        HDB::RFEntry* entry = manager->rfByEntryID(browser->selectedRFEntry());
        if (entry->hasArchitecture() && !entry->hasImplementation()) {
            delete entry;
            return true;
        }
        delete entry;
    }
    return false;
}
References HDB::RFEntry::hasArchitecture(), HDB::RFEntry::hasImplementation(), HDBBrowserWindow::isRFArchitectureSelected(), HDBBrowserWindow::isRFEntrySelected(), HDB::HDBManager::rfByEntryID(), and HDBBrowserWindow::selectedRFEntry().
The documentation for this class was generated from the following files:
AddRFImplementationCmd.hh
AddRFImplementationCmd.cc