OpenASIP: NullSocketCodeTable Class Reference
NullSocketCodeTable Class Reference
#include <NullSocketCodeTable.hh>
Static Public Member Functions
static NullSocketCodeTable & instance ()
Private Member Functions
NullSocketCodeTable ()
virtual ~NullSocketCodeTable ()
Static Private Attributes
static NullSocketCodeTable instance_
The only instance.
static BinaryEncoding bem_
The parent binary encoding.
Additional Inherited Members
Public Member Functions inherited from SocketCodeTable
SocketCodeTable (const std::string &name, BinaryEncoding &parent)
SocketCodeTable (const ObjectState *state, BinaryEncoding &parent)
virtual ~SocketCodeTable ()
BinaryEncoding * parent () const
std::string name () const
void setName (const std::string &name)
void setExtraBits (int bits)
int extraBits () const
int width () const
int maxCodeWidth () const
void addFUPortCode (FUPortCode &code)
void removeFUPortCode (FUPortCode &code)
int fuPortCodeCount () const
FUPortCode & fuPortCode (int index) const
bool hasFUPortCode (const std::string &fu, const std::string &port) const
bool hasFUPortCode (const std::string &fu, const std::string &port, const std::string &operation) const
FUPortCode & fuPortCode (const std::string &fu, const std::string &port) const
FUPortCode & fuPortCode (const std::string &fu, const std::string &port, const std::string &operation) const
void addRFPortCode (RFPortCode &code)
void removeRFPortCode (RFPortCode &code)
int rfPortCodeCount () const
RFPortCode & rfPortCode (int index) const
bool hasRFPortCode (const std::string &regFile) const
RFPortCode & rfPortCode (const std::string &regFile) const
void addIUPortCode (IUPortCode &code)
void removeIUPortCode (IUPortCode &code)
int iuPortCodeCount () const
IUPortCode & iuPortCode (int index) const
bool hasIUPortCode (const std::string &immediateUnit) const
IUPortCode & iuPortCode (const std::string &immediateUnit) const
int portCodeCount () const
PortCode & portCode (int index) const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes inherited from SocketCodeTable
static const std::string OSNAME_SOCKET_CODE_TABLE = "sc_table"
ObjectState name for socket code table.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for name of the table.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Detailed Description
A null version of SocketCodeTable class.
Definition at line 41 of file NullSocketCodeTable.hh.
Constructor & Destructor Documentation
NullSocketCodeTable()
NullSocketCodeTable::NullSocketCodeTable () private
The constructor.
Definition at line 42 of file NullSocketCodeTable.cc.
                                         : SocketCodeTable("NULL", bem_) {
}
~NullSocketCodeTable()
NullSocketCodeTable::~NullSocketCodeTable () private virtual
The destructor.
Definition at line 49 of file NullSocketCodeTable.cc.
{
}
Member Function Documentation
instance()
NullSocketCodeTable & NullSocketCodeTable::instance () static
Returns the only instance of NullSocketCodeTable.
Returns
The only instance.
Definition at line 59 of file NullSocketCodeTable.cc.
{
    return instance_;
}
References instance_.
Referenced by SocketEncoding::socketCodes(), BinaryEncoding::socketCodeTable(), and SocketEncoding::SocketEncoding().
Member Data Documentation
bem_
BinaryEncoding NullSocketCodeTable::bem_ static private
The parent binary encoding.
Definition at line 52 of file NullSocketCodeTable.hh.
instance_
NullSocketCodeTable NullSocketCodeTable::instance_ static private
The only instance.
Definition at line 50 of file NullSocketCodeTable.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullSocketCodeTable.hh
NullSocketCodeTable.cc