OpenASIP: CostDBEntryStats Class Reference
CostDBEntryStats Class Reference
#include <CostDBEntryStats.hh>
Public Member Functions
CostDBEntryStats (double areaData, double internalDelayData)
virtual ~CostDBEntryStats ()
CostDBEntryStats (const CostDBEntryStats &stats1, const CostDBEntryStats &stats2, double coefficient)
virtual CostDBEntryStats * copy () const
virtual double area () const
virtual double delay () const
virtual double delayPort (const std::string &port) const
virtual void setDelay (const std::string &port, double delay)
virtual double energyActive () const
virtual double energyIdle () const
virtual double energyOperation (const std::string &name) const
virtual bool hasEnergyOperation (const std::string &name) const
virtual double energyRead () const
virtual double energyWrite () const
virtual double energyReadWrite (int reads, int writes) const
virtual void setEnergyActive (double energy)
virtual void setEnergyIdle (double energy)
virtual void setEnergyOperation (const std::string &name, double energy)
virtual void setEnergyRead (double energy)
virtual void setEnergyWrite (double energy)
virtual void setEnergyReadWrite (int reads, int writes, double energy)
Protected Member Functions
virtual bool hasEnergy (const std::string &key) const
virtual double findEnergy (const std::string &key) const
virtual void addEnergy (const std::string &name, double energy)
virtual bool hasDelay (const std::string &key) const
virtual double findDelay (const std::string &key) const
virtual void addDelay (const std::string &name, double delay)
virtual CostDBEntryStats * createStats () const
Static Protected Attributes
static const std::string ENERGY_ACTIVE = "(active)"
String for active energy.
static const std::string ENERGY_IDLE = "(idle)"
String for idle energy.
static const std::string ENERGY_READ = "(read)"
String for read energy.
static const std::string ENERGY_WRITE = "(write)"
String for write energy.
static const std::string ENERGY_READ_WRITE = "(rd,wr)"
String for reads and writes energy.
Private Types
typedef std::map< const std::string, double > EnergyMap
Map of energies.
typedef std::map< const std::string, double > DelayMap
Map of delays.
Private Member Functions
CostDBEntryStats (const CostDBEntryStats &)
Copying not allowed.
CostDBEntryStats & operator= (const CostDBEntryStats &)
Assignment not allowed.
Private Attributes
double area_
area in gates.
double delay_
delay in nanoseconds.
DelayMap delays_
input and output delays in nanoseconds.
EnergyMap energies_
Energies of one specific type of usage of a resource. Usually the map contains energies for active and idle usage of a resource. However, in case of FUs the active energy does not exist and but energies are defined for each operation.
Detailed Description
Stores area, delay and energy statistics.
Definition at line 46 of file CostDBEntryStats.hh.
Member Typedef Documentation
DelayMap
typedef std::map<const std::string, double> CostDBEntryStats::DelayMap private
Map of delays.
Definition at line 100 of file CostDBEntryStats.hh.
EnergyMap
typedef std::map<const std::string, double> CostDBEntryStats::EnergyMap private
Map of energies.
Definition at line 98 of file CostDBEntryStats.hh.
Constructor & Destructor Documentation
CostDBEntryStats() [1/3]
CostDBEntryStats::CostDBEntryStats (double areaData, double internalDelayData)
Constructor.
Parameters
areaData area.
internalDelayData Components internal delay.
Definition at line 58 of file CostDBEntryStats.cc.
                                                                            :
    area_(areaData), delay_(internalDelayData) {
}
~CostDBEntryStats()
CostDBEntryStats::~CostDBEntryStats () virtual
Destructor.
Definition at line 144 of file CostDBEntryStats.cc.
{
}
CostDBEntryStats() [2/3]
CostDBEntryStats::CostDBEntryStats (const CostDBEntryStats & stats1, const CostDBEntryStats & stats2, double coefficient)
Constructor.
Combines two statistics into one using coefficient as a weighting factor on interpolating the statistics. For example, if weighting factor is 0.4, the first area 100 and the second 200, area of new statistics will be 140. delay and energy will be handled similarly.
Parameters
stats1 First statistics.
stats2 Second statistics.
coefficient Weighting factor.
Exceptions
KeyNotFound Thrown in case that the two statistics won't contain equal keys.
Definition at line 76 of file CostDBEntryStats.cc.
{
    area_  = stats1.area() + coefficient * (stats2.area()  - stats1.area());
    delay_ = stats1.delay() + coefficient * (stats2.delay() - stats1.delay());
    for (EnergyMap::const_iterator i = stats1.energies_.begin();
         i != stats1.energies_.end(); i++) {
        string key = (*i).first;
        double energy1 = (*i).second;
        double energy2 = stats2.findEnergy(key);
        double energy = energy1 + coefficient * (energy2 - energy1);
        addEnergy(key, energy);
    }
    // checks that the energy keys are equal in both statistics
    for (EnergyMap::const_iterator i = stats2.energies_.begin();
         i != stats2.energies_.end(); i++) {
        string key = (*i).first;
        // checks if the energy exist for the key
        stats1.findEnergy(key);
    }
    // check also keys of the other stats
    for (EnergyMap::const_iterator i = stats1.energies_.begin();
         i != stats1.energies_.end(); i++) {
        string key = (*i).first;
        // checks if the energy exist for the key
        stats2.findEnergy(key);
    }
    for (DelayMap::const_iterator i = stats1.delays_.begin();
         i != stats1.delays_.end(); i++) {
        string key = (*i).first;
        double delay1 = (*i).second;
        double delay2 = stats2.findDelay(key);
        double delay = delay1 + coefficient * (delay2 - delay1);
        addDelay(key, delay);
    }
    // checks that the delay keys are equal in both statistics
    for (DelayMap::const_iterator i = stats2.delays_.begin();
         i != stats2.delays_.end(); i++) {
        string key = (*i).first;
        // checks if the delay exist for the key
        stats1.findDelay(key);
    }
    // check also keys of the other stats
    for (DelayMap::const_iterator i = stats1.delays_.begin();
         i != stats1.delays_.end(); i++) {
        string key = (*i).first;
        // checks if the delay exist for the key
        stats2.findDelay(key);
    }
}
References addDelay(), addEnergy(), area(), area_, delay(), delay_, delays_, energies_, findDelay(), and findEnergy().
CostDBEntryStats() [3/3]
CostDBEntryStats::CostDBEntryStats (const CostDBEntryStats &) private
Copying not allowed.
Member Function Documentation
addDelay()
void CostDBEntryStats::addDelay (const std::string & key, double delay) protected virtual
Set the delay of an entry for a given key.
Removes the old value.
Parameters
key The key.
delay The delay of an entry for a given key.
Definition at line 477 of file CostDBEntryStats.cc.
{
    // if old value for delay is found it is removed first
    DelayMap::iterator iter = delays_.find(key);
    if (iter != delays_.end()) {
        delays_.erase(iter);
    }
    std::pair<const std::string, double> delayKey =
        std::pair<const std::string, double>(key, delay);
    delays_.insert(delayKey);
}
References delay(), and delays_.
Referenced by CostDBEntryStats(), and setDelay().
addEnergy()
void CostDBEntryStats::addEnergy (const std::string & key, double energy) protected virtual
Set the energy of an entry for a given key.
Removes the old value.
Parameters
key The key.
energy The energy of an entry for a given key.
Definition at line 413 of file CostDBEntryStats.cc.
{
    // if old value for energy is found it is removed first
    EnergyMap::iterator iter = energies_.find(key);
    if (iter != energies_.end()) {
        energies_.erase(iter);
    }
    std::pair<const std::string, double> energyKey =
        std::pair<const std::string, double>(key, energy);
    energies_.insert(energyKey);
}
References energies_.
Referenced by copy(), CostDBEntryStats(), setEnergyActive(), setEnergyIdle(), CostDBEntryStatsFU::setEnergyOperation(), CostDBEntryStatsRF::setEnergyRead(), CostDBEntryStatsRF::setEnergyReadWrite(), and CostDBEntryStatsRF::setEnergyWrite().
area()
virtual double CostDBEntryStats::area () const virtual
Referenced by CostDBEntryStats(), createStats(), CostDBEntryStatsFU::createStats(), and CostDBEntryStatsRF::createStats().
copy()
CostDBEntryStats * CostDBEntryStats::copy () const virtual
Returns the copy of the statistics.
Returns
Copy of statistics.
Definition at line 153 of file CostDBEntryStats.cc.
{
    CostDBEntryStats* newStats = createStats();
    for (EnergyMap::const_iterator i = energies_.begin();
         i != energies_.end(); i++) {
        newStats->addEnergy((*i).first, (*i).second);
    }
    for (DelayMap::const_iterator i = delays_.begin();
         i != delays_.end(); i++) {
        newStats->setDelay((*i).first, (*i).second);
    }
    return newStats;
}
References addEnergy(), createStats(), delays_, energies_, and setDelay().
Referenced by CostDatabase::insertEntry().
createStats()
CostDBEntryStats * CostDBEntryStats::createStats () const protected virtual
Create correct type of statistics.
Returns
Correct type of statistics.
Reimplemented in CostDBEntryStatsFU, and CostDBEntryStatsRF.
Definition at line 177 of file CostDBEntryStats.cc.
{
    return new CostDBEntryStats(area(), delay());
}
References area(), and delay().
Referenced by copy().
delay()
virtual double CostDBEntryStats::delay () const virtual
Referenced by addDelay(), CostDBEntryStats(), createStats(), CostDBEntryStatsFU::createStats(), CostDBEntryStatsRF::createStats(), and setDelay().
delayPort()
double CostDBEntryStats::delayPort (const std::string & port) const virtual
Returns the delay of given port is usage an an input/output.
Parameters
port The name of the port.
Returns
The delay of an entry when given port is used.
Exceptions
WrongSubclass Never thrown by this function.
KeyNotFound Thrown if delay for given port is not set.
Definition at line 434 of file CostDBEntryStats.cc.
{
    return findDelay(port);
}
References findDelay().
energyActive()
double CostDBEntryStats::energyActive () const virtual
Returns the energy of an entry in an active cycle.
Returns
The energy of an entry in an active cycle.
Exceptions
WrongSubclass Never thrown.
KeyNotFound Thrown if active energy is not set.
Reimplemented in CostDBEntryStatsFU, and CostDBEntryStatsRF.
Definition at line 190 of file CostDBEntryStats.cc.
{
    return findEnergy(ENERGY_ACTIVE);
}
References ENERGY_ACTIVE, and findEnergy().
energyIdle()
double CostDBEntryStats::energyIdle () const virtual
Returns the energy of an entry in an idle cycle.
Returns
The energy of an entry in an idle cycle.
Exceptions
WrongSubclass Never thrown by this function.
KeyNotFound Thrown if idle enrgy is not set.
Definition at line 202 of file CostDBEntryStats.cc.
{
    return findEnergy(ENERGY_IDLE);
}
References ENERGY_IDLE, and findEnergy().
energyOperation()
double CostDBEntryStats::energyOperation (const std::string & name) const virtual
Returns the energy of an entry when given operation is executed.
The function will fail since this class should be used for entries which do not have operation set as a search key.
Parameters
name The name of the operation.
Returns
The energy of an entry when given operation is executed.
Exceptions
WrongSubclass An illegal function was called for this instance.
KeyNotFound No energy matching the string found.
Reimplemented in CostDBEntryStatsFU.
Definition at line 219 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::energyOperation");
    return 0.0; // stupid return statement to make compiler quiet
}
energyRead()
double CostDBEntryStats::energyRead () const virtual
Returns the read energy of an entry.
Returns
The read energy of an entry.
Exceptions
WrongSubclass An illegal function was called for this instance.
KeyNotFound Never thrown by this function.
Reimplemented in CostDBEntryStatsRF.
Definition at line 249 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::energyRead");
    return 0.0; // stupid return statement to make compiler quiet
}
energyReadWrite()
double CostDBEntryStats::energyReadWrite (int reads, int writes) const virtual
Returns the reads and writes energy of an entry.
Parameters
reads The number of simultaneus reads done for the unit.
writes The number of simultaneus writes done for the unit.
Returns
The reads and writes energy of an entry.
Exceptions
WrongSubclass An illegal function was called for this instance.
KeyNotFound Never thrown by this function.
Reimplemented in CostDBEntryStatsRF.
Definition at line 281 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::energyReadsWrites");
    return 0.0; // stupid return statement to make compiler quiet
}
energyWrite()
double CostDBEntryStats::energyWrite () const virtual
Returns the write energy of an entry.
Returns
The write energy of an entry.
Exceptions
WrongSubclass An illegal function was called for this instance.
KeyNotFound Never thrown by this function.
Reimplemented in CostDBEntryStatsRF.
Definition at line 264 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::energyRead");
    return 0.0; // stupid return statement to make compiler quiet
}
findDelay()
double CostDBEntryStats::findDelay (const std::string & key) const protected virtual
Returns the input/output delay of an entry usign given key as an input/output port.
Parameters
key The key.
Returns
The input/output delay using the given port.
Exceptions
KeyNotFound Requested key was not found.
Definition at line 459 of file CostDBEntryStats.cc.
{
    DelayMap::const_iterator i = delays_.find(key);
    if (i == delays_.end()) {
        throw KeyNotFound(__FILE__, __LINE__, "CostDBEntryStats::findDelay");
    }
    return i->second;
}
References delays_.
Referenced by CostDBEntryStats(), and delayPort().
findEnergy()
double CostDBEntryStats::findEnergy (const std::string & key) const protected virtual
Returns the energy of an entry for a given key.
Parameters
key The key.
Returns
The energy of an entry in an active cycle.
Exceptions
KeyNotFound Requested key was not found.
Definition at line 308 of file CostDBEntryStats.cc.
{
    EnergyMap::const_iterator i = energies_.find(key);
    if (i == energies_.end()) {
        throw KeyNotFound(__FILE__, __LINE__, "CostDBEntryStats::findEnergy");
    }
    return i->second;
}
References energies_.
Referenced by CostDBEntryStats(), energyActive(), energyIdle(), CostDBEntryStatsFU::energyOperation(), CostDBEntryStatsRF::energyRead(), CostDBEntryStatsRF::energyReadWrite(), and CostDBEntryStatsRF::energyWrite().
hasDelay()
bool CostDBEntryStats::hasDelay (const std::string & key) const protected virtual
Checks whether the delay exists for a given key.
Parameters
key The key.
Returns
True if delay exists for a given key, otherwise false.
Definition at line 496 of file CostDBEntryStats.cc.
{
    DelayMap::const_iterator i = delays_.find(key);
    return i != delays_.end();
}
References delays_.
hasEnergy()
bool CostDBEntryStats::hasEnergy (const std::string & key) const protected virtual
Checks whether the energy exists for a given key.
Parameters
key The key.
Returns
True if energy exists for a given key, otherwise false.
Definition at line 294 of file CostDBEntryStats.cc.
{
    EnergyMap::const_iterator i = energies_.find(key);
    return i != energies_.end();
}
References energies_.
Referenced by CostDBEntryStatsFU::hasEnergyOperation().
hasEnergyOperation()
bool CostDBEntryStats::hasEnergyOperation (const std::string & name) const virtual
Checks whether the energy exists for the given operation.
Parameters
name name of the operation.
Returns
True if the energy exists for the given operation.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented in CostDBEntryStatsFU.
Definition at line 234 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::hasEnergyOperation");
    return false; // stupid return statement to make compiler quiet
}
operator=()
CostDBEntryStats & CostDBEntryStats::operator= (const CostDBEntryStats &) private
Assignment not allowed.
setDelay()
void CostDBEntryStats::setDelay (const std::string & port, double delay) virtual
Set the delay of an input/output port usage.
Parameters
port Name of the input/output port.
delay The delay of an input/ouput when using the given port.
Exceptions
WrongSubclass Never thrown by this function.
Definition at line 446 of file CostDBEntryStats.cc.
{
    addDelay(port, delay);
}
References addDelay(), and delay().
Referenced by CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), CostDatabase::buildSockets(), and copy().
setEnergyActive()
void CostDBEntryStats::setEnergyActive (double energy) virtual
Set the energy of an entry in an active cycle.
Parameters
energy The energy of an entry in an active cycle.
Exceptions
WrongSubclass Never thrown by this function.
Reimplemented in CostDBEntryStatsFU, and CostDBEntryStatsRF.
Definition at line 323 of file CostDBEntryStats.cc.
{
    EnergyMap::iterator iter = energies_.find(ENERGY_ACTIVE);
    if (iter != energies_.end()) {
        energies_.erase(iter);
    }
    addEnergy(ENERGY_ACTIVE, energy);
}
References addEnergy(), energies_, and ENERGY_ACTIVE.
Referenced by CostDatabase::buildBuses(), and CostDatabase::buildSockets().
setEnergyIdle()
void CostDBEntryStats::setEnergyIdle (double energy) virtual
Set the energy of an entry in an idle cycle.
Parameters
energy The energy of an entry in an idle cycle.
Exceptions
WrongSubclass Never thrown by this function.
Definition at line 338 of file CostDBEntryStats.cc.
{
    EnergyMap::iterator iter = energies_.find(ENERGY_IDLE);
    if (iter != energies_.end()) {
        energies_.erase(iter);
    }
    addEnergy(ENERGY_IDLE, energy);
}
References addEnergy(), energies_, and ENERGY_IDLE.
Referenced by CostDatabase::buildBuses(), CostDatabase::buildFunctionUnits(), CostDatabase::buildRegisterFiles(), and CostDatabase::buildSockets().
setEnergyOperation()
void CostDBEntryStats::setEnergyOperation (const std::string & name, double energy) virtual
Set the energy of an entry when given operation is executed.
The function will fail since this class should be used for entries which do not have operation set as a search key.
Parameters
name name of the operation.
energy The energy of an entry when given operation is executed.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented in CostDBEntryStatsFU.
Definition at line 358 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::setEnergyOperation");
}
setEnergyRead()
void CostDBEntryStats::setEnergyRead (double energy) virtual
Set the read energy of an entry.
Parameters
energy The read energy of an entry.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented in CostDBEntryStatsRF.
Definition at line 371 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::setEnergyRead");
}
setEnergyReadWrite()
void CostDBEntryStats::setEnergyReadWrite (int reads, int writes, double energy) virtual
Set the reads and writes energy of an entry.
Parameters
energy The reads and writes energy of an entry.
reads The number of reads of the unit.
writes The number of writes of the unit.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented in CostDBEntryStatsRF.
Definition at line 399 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::setEnergyReadsWrites");
}
setEnergyWrite()
void CostDBEntryStats::setEnergyWrite (double energy) virtual
Set the write energy of an entry.
Parameters
energy The write energy of an entry.
Exceptions
WrongSubclass An illegal function was called for this instance.
Reimplemented in CostDBEntryStatsRF.
Definition at line 384 of file CostDBEntryStats.cc.
{
    throw WrongSubclass(__FILE__, __LINE__,
                        "CostDBEntryStats::setEnergyWrite");
}
Member Data Documentation
area_
double CostDBEntryStats::area_ private
area in gates.
Definition at line 103 of file CostDBEntryStats.hh.
Referenced by CostDBEntryStats().
delay_
double CostDBEntryStats::delay_ private
delay in nanoseconds.
Definition at line 105 of file CostDBEntryStats.hh.
Referenced by CostDBEntryStats().
delays_
DelayMap CostDBEntryStats::delays_ private
input and output delays in nanoseconds.
Definition at line 107 of file CostDBEntryStats.hh.
Referenced by addDelay(), copy(), CostDBEntryStats(), findDelay(), and hasDelay().
energies_
EnergyMap CostDBEntryStats::energies_ private
Energies of one specific type of usage of a resource. Usually the map contains energies for active and idle usage of a resource. However, in case of FUs the active energy does not exist and but energies are defined for each operation.
Definition at line 112 of file CostDBEntryStats.hh.
Referenced by addEnergy(), copy(), CostDBEntryStats(), findEnergy(), hasEnergy(), setEnergyActive(), and setEnergyIdle().
ENERGY_ACTIVE
const std::string CostDBEntryStats::ENERGY_ACTIVE = "(active)" static protected
String for active energy.
Definition at line 86 of file CostDBEntryStats.hh.
Referenced by energyActive(), and setEnergyActive().
ENERGY_IDLE
const std::string CostDBEntryStats::ENERGY_IDLE = "(idle)" static protected
String for idle energy.
Definition at line 88 of file CostDBEntryStats.hh.
Referenced by energyIdle(), and setEnergyIdle().
ENERGY_READ
const std::string CostDBEntryStats::ENERGY_READ = "(read)" static protected
String for read energy.
Definition at line 90 of file CostDBEntryStats.hh.
Referenced by CostDBEntryStatsRF::energyRead(), and CostDBEntryStatsRF::setEnergyRead().
ENERGY_READ_WRITE
const std::string CostDBEntryStats::ENERGY_READ_WRITE = "(rd,wr)" static protected
String for reads and writes energy.
Definition at line 94 of file CostDBEntryStats.hh.
Referenced by CostDBEntryStatsRF::generateReadWriteString().
ENERGY_WRITE
const std::string CostDBEntryStats::ENERGY_WRITE = "(write)" static protected
String for write energy.
Definition at line 92 of file CostDBEntryStats.hh.
Referenced by CostDBEntryStatsRF::energyWrite(), and CostDBEntryStatsRF::setEnergyWrite().
The documentation for this class was generated from the following files:
CostDBEntryStats.hh
CostDBEntryStats.cc