OpenASIP: TPEF::SectionReader Class Reference
TPEF::SectionReader Class Reference abstract
#include <SectionReader.hh>
Public Types
typedef BinaryReader::Length Length
Public Member Functions
virtual ~SectionReader ()
Static Public Member Functions
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Protected Member Functions
SectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const =0
Does actual reading part for constructing section.
virtual BinaryReader * parent () const =0
Returns binary reader whose sections actual section reader reads.
virtual Section::SectionType type () const =0
Returns type (TPEF) section which actual section reader reads.
virtual void finalize (Section *section) const
Static Protected Member Functions
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Private Types
typedef std::pair< const Section::SectionType, const BinaryReader * > MapKey
Key type for finding values in map of section readers.
typedef std::map< MapKey, const SectionReader * > MapType
Map type that contains instances of registered section readers.
Private Member Functions
SectionReader (const SectionReader &)
Copying is not allowed.
Static Private Attributes
static MapType * prototypes_ = NULL
Contains section readers for all kinds of sections and all kinds of binary formats that are supported.
Detailed Description
Abstract base class for SectionReaders.
Implements user friendly interface for registration and finding concrete SectionReader instances. Defines also interface for reading sections so there is no need to know interface or even type of concrete SectionReaders.
Definition at line 56 of file SectionReader.hh.
Member Typedef Documentation
Length
typedef BinaryReader::Length TPEF::SectionReader::Length
Definition at line 58 of file SectionReader.hh.
MapKey
typedef std::pair<const Section::SectionType, const BinaryReader*> TPEF::SectionReader::MapKey private
Key type for finding values in map of section readers.
Definition at line 94 of file SectionReader.hh.
MapType
typedef std::map<MapKey, const SectionReader*> TPEF::SectionReader::MapType private
Map type that contains instances of registered section readers.
Definition at line 97 of file SectionReader.hh.
Constructor & Destructor Documentation
~SectionReader()
TPEF::SectionReader::~SectionReader () virtual
Destructor
Definition at line 63 of file SectionReader.cc.
{
}
SectionReader() [1/2]
TPEF::SectionReader::SectionReader () protected
Constructor
Definition at line 57 of file SectionReader.cc.
{
}
SectionReader() [2/2]
TPEF::SectionReader::SectionReader (const SectionReader &) private
Copying is not allowed.
Member Function Documentation
finalize()
void TPEF::SectionReader::finalize (Section * section) const protected virtual
Default finalizer method all sections.
Does nothing. This method is runned for every read section after body of every section is read and references are resolved once.
Parameters
section Section to finalize.
Reimplemented in TPEF::AOutRelocationSectionReader, TPEF::AOutSymbolSectionReader, and TPEF::TPEFRelocSectionReader.
Definition at line 169 of file SectionReader.cc.
{
}
Referenced by finalizeBinary().
finalizeBinary()
void TPEF::SectionReader::finalizeBinary (Binary * bin, BinaryReader * reader) static
Finalizes binary whose all data is read and resolved.
Parameters
bin Binary to resolve.
reader Reader which was used for reading.
Definition at line 99 of file SectionReader.cc.
{
    for (Word i = 0; i < bin->sectionCount(); i++) {
        // get section and finalize it
        Section* sect = bin->section(i);
        try {
            const SectionReader* sectionReader =
                findSectionReader(sect->type(), reader);
            sectionReader->finalize(sect);
        } catch (const InstanceNotFound &e) {
            // there is not always reader for every created section
            // and it's ok.
        }
    }
}
References finalize(), findSectionReader(), TPEF::Binary::section(), TPEF::Binary::sectionCount(), and TPEF::Section::type().
Referenced by TPEF::BinaryReader::readBinary().
findSectionReader()
const SectionReader * TPEF::SectionReader::findSectionReader (const Section::SectionType type, const BinaryReader * reader) static protected
Finds SectionReader instance by SectionType and BinaryReader*.
Parameters
type Type of section to find.
reader BinaryReader which requested finding section.
Returns
Instance which can read section.
Exceptions
InstanceNotFound Reader instance was not found.
Definition at line 126 of file SectionReader.cc.
{
    MapKey key(type, reader);
    if (prototypes_ == NULL ||
        !MapTools::containsKey(*prototypes_, key)) {
        throw InstanceNotFound(__FILE__, __LINE__,
                               "SectionReader::findSectionReader");
    }
    return (*prototypes_)[key];
}
References MapTools::containsKey(), prototypes_, and type().
Referenced by finalizeBinary(), and readSection().
parent()
virtual BinaryReader * TPEF::SectionReader::parent () const protected pure virtual
Returns binary reader whose sections actual section reader reads.
Implemented in TPEF::AOutSectionReader, and TPEF::TPEFSectionReader.
Referenced by registerSectionReader().
readData()
virtual void TPEF::SectionReader::readData (BinaryStream & stream, Section * section) const protected pure virtual
Does actual reading part for constructing section.
Implemented in TPEF::AOutDataSectionReader, TPEF::AOutRelocationSectionReader, TPEF::AOutStringSectionReader, TPEF::AOutSymbolSectionReader, TPEF::AOutTextSectionReader, TPEF::TPEFASpaceSectionReader, TPEF::TPEFCodeSectionReader, TPEF::TPEFDataSectionReader, TPEF::TPEFDebugSectionReader, TPEF::TPEFLineNumSectionReader, TPEF::TPEFRelocSectionReader, TPEF::TPEFResourceSectionReader, TPEF::TPEFSectionReader, TPEF::TPEFStringSectionReader, TPEF::TPEFSymbolSectionReader, and TPEF::TPEFUDataSectionReader.
Referenced by readSection().
readSection()
void TPEF::SectionReader::readSection (BinaryStream & stream, Section * section, BinaryReader * reader) static
Reads a section from BinaryStream.
Finds correct concrete SectionReader object for reading section and uses it for reading.
Parameters
stream Stream from which section's data is read.
section Section instance where section elements are stored.
reader BinaryReader* of file type that we try to read.
Exceptions
InstanceNotFound There is no prototype registred for reading.
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read values were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Definition at line 84 of file SectionReader.cc.
{
    const SectionReader* sectionReader =
        findSectionReader(section->type(), reader);
    sectionReader->readData(stream, section);
}
References findSectionReader(), readData(), and TPEF::Section::type().
Referenced by TPEF::TPEFReader::readData().
registerSectionReader()
void TPEF::SectionReader::registerSectionReader (const SectionReader * reader) static protected
Registers SectionReader instance for reading specific section type.
Parameters
reader Instance to register for reading.
Definition at line 145 of file SectionReader.cc.
{
    MapKey key(reader->type(), reader->parent());
    // We can't define a static prototypes_ map, because we cannot guarantee
    // that it is initialized before this method is called.
    if (prototypes_ == NULL) {
        prototypes_ = new MapType();
    }
    assert(!MapTools::containsKey(*prototypes_, key));
    (*prototypes_)[key] = reader;
}
References assert, MapTools::containsKey(), parent(), prototypes_, and type().
Referenced by TPEF::AOutDataSectionReader::AOutDataSectionReader(), TPEF::AOutRelocationSectionReader::AOutRelocationSectionReader(), TPEF::AOutStringSectionReader::AOutStringSectionReader(), TPEF::AOutSymbolSectionReader::AOutSymbolSectionReader(), TPEF::AOutTextSectionReader::AOutTextSectionReader(), TPEF::TPEFASpaceSectionReader::TPEFASpaceSectionReader(), TPEF::TPEFCodeSectionReader::TPEFCodeSectionReader(), TPEF::TPEFDataSectionReader::TPEFDataSectionReader(), TPEF::TPEFDebugSectionReader::TPEFDebugSectionReader(), TPEF::TPEFLEDataSectionReader::TPEFLEDataSectionReader(), TPEF::TPEFLineNumSectionReader::TPEFLineNumSectionReader(), TPEF::TPEFNullSectionReader::TPEFNullSectionReader(), TPEF::TPEFRelocSectionReader::TPEFRelocSectionReader(), TPEF::TPEFResourceSectionReader::TPEFResourceSectionReader(), TPEF::TPEFStringSectionReader::TPEFStringSectionReader(), TPEF::TPEFSymbolSectionReader::TPEFSymbolSectionReader(), and TPEF::TPEFUDataSectionReader::TPEFUDataSectionReader().
type()
virtual Section::SectionType TPEF::SectionReader::type () const protected pure virtual
Returns type (TPEF) section which actual section reader reads.
Implemented in TPEF::AOutDataSectionReader, TPEF::AOutRelocationSectionReader, TPEF::AOutStringSectionReader, TPEF::AOutSymbolSectionReader, TPEF::AOutTextSectionReader, TPEF::TPEFASpaceSectionReader, TPEF::TPEFCodeSectionReader, TPEF::TPEFDataSectionReader, TPEF::TPEFDebugSectionReader, TPEF::TPEFLEDataSectionReader, TPEF::TPEFLineNumSectionReader, TPEF::TPEFNullSectionReader, TPEF::TPEFRelocSectionReader, TPEF::TPEFResourceSectionReader, TPEF::TPEFStringSectionReader, TPEF::TPEFSymbolSectionReader, and TPEF::TPEFUDataSectionReader.
Referenced by findSectionReader(), and registerSectionReader().
Member Data Documentation
prototypes_
SectionReader::MapType * TPEF::SectionReader::prototypes_ = NULL static private
Contains section readers for all kinds of sections and all kinds of binary formats that are supported.
Definition at line 101 of file SectionReader.hh.
Referenced by findSectionReader(), and registerSectionReader().
The documentation for this class was generated from the following files:
SectionReader.hh
SectionReader.cc