OpenASIP: DesignSpaceExplorerPlugin Class Reference
DesignSpaceExplorerPlugin Class Reference abstract
#include <DesignSpaceExplorerPlugin.hh>
Public Types
typedef std::pair< std::string, ExplorerPluginParameter > Parameter
typedef std::map< std::string, ExplorerPluginParameter > ParameterMap
typedef std::map< std::string, ExplorerPluginParameter >::iterator PMIt
typedef std::map< std::string, ExplorerPluginParameter >::const_iterator PMCIt
Public Member Functions
virtual bool requiresStartingPointArchitecture () const =0
virtual bool producesArchitecture () const =0
virtual bool requiresHDB () const =0
virtual bool requiresSimulationData () const =0
virtual bool requiresApplication () const
virtual std::string description () const
void addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory=true, TCEString defaultValue="", TCEString description="")
template<typename T >
void readCompulsoryParameter (const std::string paramName, T &param) const
template<typename T >
void readOptionalParameter (const std::string paramName, T &param) const
template<typename RT >
RT parameterValue (const std::string &paramName) const
Public Member Functions inherited from DesignSpaceExplorer
DesignSpaceExplorer ()
virtual ~DesignSpaceExplorer ()
virtual void setDSDB (DSDBManager &dsdb)
virtual bool evaluate (const DSDBManager::MachineConfiguration &configuration, CostEstimates &results=dummyEstimate_, bool estimate=false)
virtual DSDBManager & db ()
std::vector< DesignSpaceExplorerPlugin * > getPlugins ()
RowID createImplementationAndStore (const DSDBManager::MachineConfiguration &conf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
bool createImplementation (const DSDBManager::MachineConfiguration &conf, DSDBManager::MachineConfiguration &newConf, const double &frequency=0.0, const double &maxArea=0.0, const bool &createEstimates=true, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb")
IDF::MachineImplementation * selectComponents (const TTAMachine::Machine &mach, const double &frequency=0.0, const double &maxArea=0.0, const std::string &icDec="DefaultICDecoder", const std::string &icDecHDB="asic_130nm_1.5V.hdb") const
void createEstimateData (const TTAMachine::Machine &mach, const IDF::MachineImplementation &idf, CostEstimator::AreaInGates &area, CostEstimator::DelayInNanoSeconds &longestPathDelay)
RowID addConfToDSDB (const DSDBManager::MachineConfiguration &conf)
Protected Attributes
std::string pluginName_
the name of the explorer plugin
ParameterMap parameters_
Parameters for the plugin.
pluginName Name of the plugin.
The constructor of the DesignExplorerPlugin class.
Parameters
dsdb Design space data base to be used with the plugin.
virtual ~DesignSpaceExplorerPlugin ()
virtual void giveParameter (const std::string &name, const std::string &value)
virtual std::string name () const
virtual void setPluginName (const std::string &pluginName)
virtual std::vector< RowID > explore (const RowID &startPointConfigurationID, const unsigned int &maxIter=0)
virtual bool hasParameter (const std::string &paramName) const
ParameterMap parameters () const
virtual bool booleanValue (const std::string &parameter) const
DesignSpaceExplorerPlugin ()
void checkParameters () const
Additional Inherited Members
Static Public Member Functions inherited from DesignSpaceExplorer
static DesignSpaceExplorerPlugin * loadExplorerPlugin (const std::string &pluginName, DSDBManager *dsdb=NULL)
Protected Member Functions inherited from DesignSpaceExplorer
TTAProgram::Program * schedule (const std::string applicationFile, TTAMachine::Machine &machine, TCEString paramOptions="-O3")
const ExecutionTrace * simulate (const TTAProgram::Program &program, const TTAMachine::Machine &machine, const TestApplication &testApplication, const ClockCycleCount &maxCycles, ClockCycleCount &runnedCycles, const bool tracing, const bool useCompiledSimulation=false, std::vector< ClockCycleCount > *executionCounts=NULL)
Detailed Description
A base interface for all classes that implement pluggable design space explorer algorithms.
Plugins are allowed to store state data to itself, thus, the plugin instances are not allowed to be "recycled" for multiple uses, but a new instance should be created always.
Definition at line 55 of file DesignSpaceExplorerPlugin.hh.
Member Typedef Documentation
Parameter
typedef std::pair<std::string, ExplorerPluginParameter> DesignSpaceExplorerPlugin::Parameter
Definition at line 67 of file DesignSpaceExplorerPlugin.hh.
ParameterMap
typedef std::map<std::string, ExplorerPluginParameter> DesignSpaceExplorerPlugin::ParameterMap
Definition at line 69 of file DesignSpaceExplorerPlugin.hh.
PMCIt
typedef std::map<std::string,ExplorerPluginParameter>::const_iterator DesignSpaceExplorerPlugin::PMCIt
Definition at line 73 of file DesignSpaceExplorerPlugin.hh.
PMIt
typedef std::map<std::string,ExplorerPluginParameter>::iterator DesignSpaceExplorerPlugin::PMIt
Definition at line 71 of file DesignSpaceExplorerPlugin.hh.
Constructor & Destructor Documentation
~DesignSpaceExplorerPlugin()
DesignSpaceExplorerPlugin::~DesignSpaceExplorerPlugin () virtual
The destructor.
Definition at line 56 of file DesignSpaceExplorerPlugin.cc.
{
}
DesignSpaceExplorerPlugin()
DesignSpaceExplorerPlugin::DesignSpaceExplorerPlugin () protected
Definition at line 48 of file DesignSpaceExplorerPlugin.cc.
                                                    :
    DesignSpaceExplorer() {
}
Member Function Documentation
addParameter()
void DesignSpaceExplorerPlugin::addParameter (TCEString name, ExplorerPluginParameterType type, bool compulsory = true, TCEString defaultValue = "", TCEString description = "") inline
Referenced by ADFCombiner::ADFCombiner(), ComponentAdder::ComponentAdder(), ConnectionSweeper::ConnectionSweeper(), Evaluate::Evaluate(), FrequencySweepExplorer::FrequencySweepExplorer(), GrowMachine::GrowMachine(), ImmediateGenerator::ImmediateGenerator(), ImplementationSelector::ImplementationSelector(), MinimalOpSet::MinimalOpSet(), MinimizeMachine::MinimizeMachine(), RemoveUnconnectedComponents::RemoveUnconnectedComponents(), SimpleICOptimizer::SimpleICOptimizer(), VectorLSGenerator::VectorLSGenerator(), and VLIWConnectIC::VLIWConnectIC().
booleanValue()
bool DesignSpaceExplorerPlugin::booleanValue (const std::string & parameter) const virtual
Returns the boolean value of the given parameter if parameter can be considered as a boolean.
Parameters
parameter The string to be converted to a boolean value
Returns
Boolean value of the parameter
Exceptions
IllegalParameters Given parameter could not be considerer as boolean value
Definition at line 132 of file DesignSpaceExplorerPlugin.cc.
{
    std::string lowCase = StringTools::stringToLower(parameter);
    if (lowCase == "true" || lowCase == "1") {
        return true;
    } else if (lowCase == "false" || lowCase == "0") {
        return false;
    } else {
        throw IllegalParameters(__FILE__, __LINE__, __func__);
    }
}
References __func__, and StringTools::stringToLower().
checkParameters()
void DesignSpaceExplorerPlugin::checkParameters () const protected
Checks that all compulsory parameters are set for the plugin.
Definition at line 147 of file DesignSpaceExplorerPlugin.cc.
{
    for (PMCIt it = parameters_.begin(); it != parameters_.end(); it++) {
        if (it->second.isCompulsory() && !it->second.isSet()) {
            std::string msg = it->second.name() + " parameter is needed.";
            throw IllegalParameters(__FILE__, __LINE__, __func__, msg);
        }
    }
}
References __func__, and parameters_.
Referenced by FrequencySweepExplorer::explore().
description()
virtual std::string DesignSpaceExplorerPlugin::description () const inline virtual
Referenced by CallExplorerPluginWindow::onSelectPlugin(), and printPlugins().
explore()
std::vector< RowID > DesignSpaceExplorerPlugin::explore (const RowID & startPointConfigurationID, const unsigned int & maxIter = 0) virtual
Explores the design space from the starting point machine and returns best exploring results as configuration IDs.
Exploring creates new machine configurations (architecture, implementation) that are ordered so that the best results are first in the result vector.
Parameters
startPoint Starting point machine configuration for the plugin.
maxIter Maximum number of design space points the plugin is allowed to explore. Default value for maxIter is zero when the iteration number is not taken into account. In that case the exploration runs indefinetly or stops at a point defined by the algorithm.
Returns
Ordered vector of IDs of the best machine configurations where the target programs can be successfully run. The IDs of the best machine configurations are first in the result vector. Returns an empty vector if does not find any possible machine configurations.
Reimplemented in ADFCombiner, BlocksConnectIC, ComponentAdder, Evaluate, GrowMachine, ImplementationSelector, MinimalOpSet, MinimizeMachine, RemoveUnconnectedComponents, VectorLSGenerator, VLIWConnectIC, ConnectionSweeper, FrequencySweepExplorer, ImmediateGenerator, and SimpleICOptimizer.
Definition at line 174 of file DesignSpaceExplorerPlugin.cc.
{
    std::vector<RowID> result;
    return result;
}
Referenced by FrequencySweepExplorer::callPlugin(), BlocksConnectICCmd::Do(), VLIWConnectICCmd::Do(), ADFCombiner::explore(), FrequencySweepExplorer::explore(), SimpleICOptimizer::explore(), main(), and CallExplorerPluginWindow::onRun().
giveParameter()
void DesignSpaceExplorerPlugin::giveParameter (const std::string & name, const std::string & value) virtual
Gives a plugin parameter value.
Parameters
name The parameter name.
value The value to be set for the parameter.
Definition at line 89 of file DesignSpaceExplorerPlugin.cc.
{
    PMIt it = parameters_.find(name);
    if (it == parameters_.end()) {
        std::string msg = "Plugin has no parameter named: " + name;
        throw InstanceNotFound(__FILE__, __LINE__, __func__, msg);
    }
    it->second.setValue(value);
}
References __func__, name(), and parameters_.
Referenced by CallExplorerPluginWindow::doEdit(), ADFCombiner::explore(), FrequencySweepExplorer::explore(), SimpleICOptimizer::explore(), and loadPluginParameters().
hasParameter()
bool DesignSpaceExplorerPlugin::hasParameter (const std::string & paramName) const virtual
Tells whether the plugin has the given parameter defined.
Parameters
paramName Name of the parameter.
Returns
True if the given parameter is defined, otherwise false.
Definition at line 106 of file DesignSpaceExplorerPlugin.cc.
{
    return parameters_.find(paramName)->second.isSet();
}
References parameters_.
name()
std::string DesignSpaceExplorerPlugin::name () const virtual
Returns the plugin name.
Returns
The plugin name as a string.
Definition at line 77 of file DesignSpaceExplorerPlugin.cc.
{
    return pluginName_;
}
References pluginName_.
Referenced by ImmediateGenerator::addInsTemplate(), ImmediateGenerator::addSplitInsTemplate(), CallExplorerPluginWindow::CallExplorerPluginWindow(), FrequencySweepExplorer::callPlugin(), ADFCombiner::createPortsAndSockets(), giveParameter(), and ImmediateGenerator::removeInsTemplate().
parameters()
DesignSpaceExplorerPlugin::ParameterMap DesignSpaceExplorerPlugin::parameters () const
Makes a copy of the parameters of the plugin and returns it.
Returns
ParameterMap map of the explorer plugin parameters.
Definition at line 117 of file DesignSpaceExplorerPlugin.cc.
{
    return parameters_;
}
References parameters_.
Referenced by CallExplorerPluginWindow::getParam(), printPluginParamInfo(), and CallExplorerPluginWindow::updateParameterList().
parameterValue()
template<typename RT > RT DesignSpaceExplorerPlugin::parameterValue (const std::string & paramName) const
producesArchitecture()
virtual bool DesignSpaceExplorerPlugin::producesArchitecture () const pure virtual
Implemented in ADFCombiner, BlocksConnectIC, ComponentAdder, ConnectionSweeper, Evaluate, FrequencySweepExplorer, GrowMachine, ImmediateGenerator, ImplementationSelector, MinimalOpSet, MinimizeMachine, RemoveUnconnectedComponents, SimpleICOptimizer, VectorLSGenerator, and VLIWConnectIC.
Referenced by CallExplorerPluginWindow::CallExplorerPluginWindow().
readCompulsoryParameter()
template<typename T > void DesignSpaceExplorerPlugin::readCompulsoryParameter (const std::string paramName, T & param) const
Referenced by FrequencySweepExplorer::readParameters(), ImmediateGenerator::readParameters(), MinimalOpSet::readParameters(), and MinimizeMachine::readParameters().
readOptionalParameter()
template<typename T > void DesignSpaceExplorerPlugin::readOptionalParameter (const std::string paramName, T & param) const
Referenced by ADFCombiner::readParameters(), ComponentAdder::readParameters(), ConnectionSweeper::readParameters(), Evaluate::readParameters(), FrequencySweepExplorer::readParameters(), GrowMachine::readParameters(), ImplementationSelector::readParameters(), MinimizeMachine::readParameters(), RemoveUnconnectedComponents::readParameters(), SimpleICOptimizer::readParameters(), VectorLSGenerator::readParameters(), and VLIWConnectIC::readParameters().
requiresApplication()
virtual bool DesignSpaceExplorerPlugin::requiresApplication () const inline virtual
Reimplemented in ADFCombiner, BlocksConnectIC, ComponentAdder, ImmediateGenerator, ImplementationSelector, MinimalOpSet, RemoveUnconnectedComponents, SimpleICOptimizer, VectorLSGenerator, and VLIWConnectIC.
Definition at line 64 of file DesignSpaceExplorerPlugin.hh.
{ return true; }
Referenced by main().
requiresHDB()
virtual bool DesignSpaceExplorerPlugin::requiresHDB () const pure virtual
Implemented in ADFCombiner, BlocksConnectIC, ComponentAdder, ConnectionSweeper, Evaluate, FrequencySweepExplorer, GrowMachine, ImmediateGenerator, ImplementationSelector, MinimalOpSet, MinimizeMachine, RemoveUnconnectedComponents, SimpleICOptimizer, VectorLSGenerator, and VLIWConnectIC.
Referenced by CallExplorerPluginWindow::CallExplorerPluginWindow().
requiresSimulationData()
virtual bool DesignSpaceExplorerPlugin::requiresSimulationData () const pure virtual
Implemented in ADFCombiner, BlocksConnectIC, ComponentAdder, ConnectionSweeper, Evaluate, FrequencySweepExplorer, GrowMachine, ImmediateGenerator, ImplementationSelector, MinimalOpSet, MinimizeMachine, RemoveUnconnectedComponents, SimpleICOptimizer, VectorLSGenerator, and VLIWConnectIC.
Referenced by CallExplorerPluginWindow::CallExplorerPluginWindow().
requiresStartingPointArchitecture()
virtual bool DesignSpaceExplorerPlugin::requiresStartingPointArchitecture () const pure virtual
Implemented in ADFCombiner, BlocksConnectIC, ComponentAdder, ConnectionSweeper, Evaluate, FrequencySweepExplorer, GrowMachine, ImmediateGenerator, ImplementationSelector, MinimalOpSet, MinimizeMachine, RemoveUnconnectedComponents, SimpleICOptimizer, VectorLSGenerator, and VLIWConnectIC.
Referenced by main().
setPluginName()
void DesignSpaceExplorerPlugin::setPluginName (const std::string & pluginName) virtual
Sets the plugin name.
Parameters
pluginName Name of the plugin.
Definition at line 66 of file DesignSpaceExplorerPlugin.cc.
{
    pluginName_ = pluginName;
}
References pluginName_.
Member Data Documentation
parameters_
ParameterMap DesignSpaceExplorerPlugin::parameters_ protected
Parameters for the plugin.
Definition at line 116 of file DesignSpaceExplorerPlugin.hh.
Referenced by checkParameters(), giveParameter(), hasParameter(), and parameters().
pluginName_
std::string DesignSpaceExplorerPlugin::pluginName_ protected
the name of the explorer plugin
Definition at line 114 of file DesignSpaceExplorerPlugin.hh.
Referenced by name(), and setPluginName().
The documentation for this class was generated from the following files:
DesignSpaceExplorerPlugin.hh
DesignSpaceExplorerPlugin.cc