OpenASIP: TPEF::MoveElement Class Reference
TPEF::MoveElement Class Reference
#include <MoveElement.hh>
Public Types
enum FieldType { MF_NULL , MF_RF , MF_IMM , MF_UNIT }
Public Member Functions
MoveElement ()
virtual ~MoveElement ()
bool isEmpty () const
void setEmpty (bool flag)
HalfWord bus () const
void setBus (HalfWord aBus)
FieldType sourceType () const
void setSourceType (FieldType aType)
HalfWord sourceUnit () const
void setSourceUnit (HalfWord aSourceUnit)
HalfWord sourceIndex () const
void setSourceIndex (HalfWord aSourceIndex)
FieldType destinationType () const
void setDestinationType (FieldType aType)
HalfWord destinationUnit () const
void setDestinationUnit (HalfWord aDestinationUnit)
HalfWord destinationIndex () const
void setDestinationIndex (HalfWord aDestinationIndex)
FieldType guardType () const
void setGuardType (FieldType gType)
HalfWord guardUnit () const
void setGuardUnit (HalfWord aGuardUnit)
HalfWord guardIndex () const
void setGuardIndex (HalfWord aGuardIndex)
bool isGuarded () const
void setGuarded (bool flag)
bool isGuardInverted () const
void setGuardInverted (bool flag)
Public Member Functions inherited from TPEF::InstructionElement
virtual ~InstructionElement ()
bool isMove () const
bool isImmediate () const
bool begin () const
void setBegin (bool isBegin)
InstructionAnnotation * annotation (Word index) const
void addAnnotation (InstructionAnnotation *anAnnotation)
Word annotationCount () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
bool isEmpty_
Empty move bit.
HalfWord bus_
Move bus identifier.
FieldType sourceType_
The type of Move source.
FieldType destinationType_
The type of move destination.
HalfWord sourceUnit_
Move source unit or register file.
HalfWord destinationUnit_
Move destination unit or register file identifier.
HalfWord sourceIndex_
Move source register index.
HalfWord destinationIndex_
Move destination register index.
bool isGuarded_
Move guard enable bit.
bool isGuardInverted_
Move guard inverted bit.
FieldType guardType_
Guard type.
HalfWord guardUnit_
Guard register file / unit identifier.
HalfWord guardIndex_
Guard register index.
Additional Inherited Members
Protected Member Functions inherited from TPEF::InstructionElement
InstructionElement (bool isMove)
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Move instruction.
Definition at line 47 of file MoveElement.hh.
Member Enumeration Documentation
FieldType
enum TPEF::MoveElement::FieldType
Type of resource that is referred by unit / index pair.
Enumerator
MF_NULL
Illegal field.
MF_RF
Register file.
MF_IMM
Immediate.
MF_UNIT
Function unit.
Definition at line 52 of file MoveElement.hh.
                   {
        MF_NULL, ///< Illegal field.
        MF_RF,   ///< Register file.
        MF_IMM,  ///< Immediate.
        MF_UNIT  ///< Function unit.
    };
Constructor & Destructor Documentation
MoveElement()
TPEF::MoveElement::MoveElement ()
Constructor.
Move attributes are initialized to default values.
Definition at line 45 of file MoveElement.cc.
                         :
    InstructionElement(true), isEmpty_(false), bus_(0), sourceType_(MF_NULL),
    destinationType_(MF_NULL), sourceUnit_(0),
    destinationUnit_(0), sourceIndex_(0), destinationIndex_(0),
    isGuarded_(false), isGuardInverted_(false),
    guardType_(MF_NULL), guardUnit_(0),
    guardIndex_(0) {
}
~MoveElement()
TPEF::MoveElement::~MoveElement () virtual
Destructor
Definition at line 57 of file MoveElement.cc.
{
}
Member Function Documentation
bus()
HalfWord TPEF::MoveElement::bus () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), CodeCompressorPlugin::immediateTerminal(), and TPEF::TPEFCodeSectionWriter::writeDataField().
destinationIndex()
HalfWord TPEF::MoveElement::destinationIndex () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFCodeSectionWriter::writeDataField().
destinationType()
FieldType TPEF::MoveElement::destinationType () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFCodeSectionWriter::writeDataField().
destinationUnit()
HalfWord TPEF::MoveElement::destinationUnit () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFCodeSectionWriter::writeDataField().
guardIndex()
HalfWord TPEF::MoveElement::guardIndex () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), and TPEF::TPEFCodeSectionWriter::writeDataField().
guardType()
FieldType TPEF::MoveElement::guardType () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), and TPEF::TPEFCodeSectionWriter::writeDataField().
guardUnit()
HalfWord TPEF::MoveElement::guardUnit () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), and TPEF::TPEFCodeSectionWriter::writeDataField().
isEmpty()
bool TPEF::MoveElement::isEmpty () const
Referenced by TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), TPEF::TPEFCodeSectionWriter::writeAttributeField(), and TPEF::TPEFCodeSectionWriter::writeDataField().
isGuarded()
bool TPEF::MoveElement::isGuarded () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::TPEFCodeSectionWriter::writeAttributeField(), and TPEF::TPEFCodeSectionWriter::writeDataField().
isGuardInverted()
bool TPEF::MoveElement::isGuardInverted () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), and TPEF::TPEFCodeSectionWriter::writeDataField().
setBus()
void TPEF::MoveElement::setBus (HalfWord aBus)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setDestinationIndex()
void TPEF::MoveElement::setDestinationIndex (HalfWord aDestinationIndex)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), TPEF::AOutSymbolSectionReader::finalize(), CodeSectionCreator::finalize(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveDestination().
setDestinationType()
void TPEF::MoveElement::setDestinationType (FieldType aType)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveDestination().
setDestinationUnit()
void TPEF::MoveElement::setDestinationUnit (HalfWord aDestinationUnit)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveDestination().
setEmpty()
void TPEF::MoveElement::setEmpty (bool flag)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), and TPEF::TPEFCodeSectionReader::readData().
setGuarded()
void TPEF::MoveElement::setGuarded (bool flag)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setGuardIndex()
void TPEF::MoveElement::setGuardIndex (HalfWord aGuardIndex)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setGuardInverted()
void TPEF::MoveElement::setGuardInverted (bool flag)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setGuardType()
void TPEF::MoveElement::setGuardType (FieldType gType)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setGuardUnit()
void TPEF::MoveElement::setGuardUnit (HalfWord aGuardUnit)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::readData(), and TPEF::TPEFCodeSectionReader::readData().
setSourceIndex()
void TPEF::MoveElement::setSourceIndex (HalfWord aSourceIndex)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), TPEF::AOutSymbolSectionReader::finalize(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::initializeImmediateMove(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveSource().
setSourceType()
void TPEF::MoveElement::setSourceType (FieldType aType)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::initializeImmediateMove(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveSource().
setSourceUnit()
void TPEF::MoveElement::setSourceUnit (HalfWord aSourceUnit)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::initializeImmediateMove(), TPEF::TPEFCodeSectionReader::readData(), and TPEF::AOutTextSectionReader::updateMoveSource().
sourceIndex()
HalfWord TPEF::MoveElement::sourceIndex () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), CodeCompressorPlugin::immediateTerminal(), and TPEF::TPEFCodeSectionWriter::writeDataField().
sourceType()
FieldType TPEF::MoveElement::sourceType () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), CodeCompressorPlugin::immediateTerminal(), and TPEF::TPEFCodeSectionWriter::writeDataField().
sourceUnit()
HalfWord TPEF::MoveElement::sourceUnit () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TPEF::AOutSymbolSectionReader::finalize(), and TPEF::TPEFCodeSectionWriter::writeDataField().
Member Data Documentation
bus_
HalfWord TPEF::MoveElement::bus_ private
Move bus identifier.
Definition at line 105 of file MoveElement.hh.
destinationIndex_
HalfWord TPEF::MoveElement::destinationIndex_ private
Move destination register index.
Definition at line 117 of file MoveElement.hh.
destinationType_
FieldType TPEF::MoveElement::destinationType_ private
The type of move destination.
Definition at line 109 of file MoveElement.hh.
destinationUnit_
HalfWord TPEF::MoveElement::destinationUnit_ private
Move destination unit or register file identifier.
Definition at line 113 of file MoveElement.hh.
guardIndex_
HalfWord TPEF::MoveElement::guardIndex_ private
Guard register index.
Definition at line 127 of file MoveElement.hh.
guardType_
FieldType TPEF::MoveElement::guardType_ private
Guard type.
Definition at line 123 of file MoveElement.hh.
guardUnit_
HalfWord TPEF::MoveElement::guardUnit_ private
Guard register file / unit identifier.
Definition at line 125 of file MoveElement.hh.
isEmpty_
bool TPEF::MoveElement::isEmpty_ private
Empty move bit.
Definition at line 103 of file MoveElement.hh.
isGuarded_
bool TPEF::MoveElement::isGuarded_ private
Move guard enable bit.
Definition at line 119 of file MoveElement.hh.
isGuardInverted_
bool TPEF::MoveElement::isGuardInverted_ private
Move guard inverted bit.
Definition at line 121 of file MoveElement.hh.
sourceIndex_
HalfWord TPEF::MoveElement::sourceIndex_ private
Move source register index.
Definition at line 115 of file MoveElement.hh.
sourceType_
FieldType TPEF::MoveElement::sourceType_ private
The type of Move source.
Definition at line 107 of file MoveElement.hh.
sourceUnit_
HalfWord TPEF::MoveElement::sourceUnit_ private
Move source unit or register file.
Definition at line 111 of file MoveElement.hh.
The documentation for this class was generated from the following files:
MoveElement.hh
MoveElement.cc