OpenASIP: TTAMachine::PipelineElement Class Reference
TTAMachine::PipelineElement Class Reference
#include <PipelineElement.hh>
Classes
struct Comparator
Public Member Functions
PipelineElement (const std::string &name, FunctionUnit &parentUnit)
virtual ~PipelineElement ()
const std::string & name () const
void setName (const std::string &name)
FunctionUnit * parentUnit () const
Private Attributes
std::string name_
Name of the pipeline element.
FunctionUnit * parent_
The parent unit.
Detailed Description
Represents an resource inside pipeline in function unit.
Definition at line 46 of file PipelineElement.hh.
Constructor & Destructor Documentation
PipelineElement()
TTAMachine::PipelineElement::PipelineElement (const std::string & name, FunctionUnit & parentUnit)
Constructor.
Pipeline elements are created automatically when pipeline of operation is created. Clients should not create pipeline elements.
Parameters
name Name of the pipeline element.
parentUnit The parent unit.
Exceptions
ComponentAlreadyExists If there exists another pipeline element by the same name in the function unit.
InvalidName If the given name is not a valid component name.
Definition at line 54 of file PipelineElement.cc.
    : name_(""), parent_(&parentUnit) {
    setName(name);
    // clear parent pointer to pass the assert in addPipelineElement
    parent_ = NULL;
    parentUnit.addPipelineElement(*this);
    parent_ = &parentUnit;
}
References TTAMachine::FunctionUnit::addPipelineElement(), name(), parent_, parentUnit(), and setName().
~PipelineElement()
TTAMachine::PipelineElement::~PipelineElement () virtual
Destructor.
Definition at line 69 of file PipelineElement.cc.
{
    FunctionUnit* parent = parent_;
    parent_ = NULL;
    parent->deletePipelineElement(*this);
    // remove usages of this resource
    for (int i = 0; i < parent->operationCount(); i++) {
        HWOperation* operation = parent->operation(i);
        ExecutionPipeline* pLine = operation->pipeline();
        pLine->removeResourceUse(name());
    }
}
References TTAMachine::FunctionUnit::deletePipelineElement(), name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), parent_, TTAMachine::HWOperation::pipeline(), and TTAMachine::ExecutionPipeline::removeResourceUse().
Member Function Documentation
name()
const std::string & TTAMachine::PipelineElement::name () const
Referenced by HDB::HDBManager::addFUArchitecture(), TTAMachine::FunctionUnit::addPipelineElement(), ExecutionPipelineResourceTable::ExecutionPipelineResourceTable(), HDBToHtml::fuArchToHtml(), TTAMachine::FunctionUnit::isArchitectureEqual(), HDB::HDBManager::isMatchingArchitecture(), TTAMachine::PipelineElement::Comparator::operator()(), HDB::FUArchitecture::operator==(), PipelineElement(), ReservationTable::ReservationTable(), TTAMachine::ExecutionPipeline::saveResourceUse(), setName(), OperationDialog::updateResourceGrid(), and ~PipelineElement().
parentUnit()
FunctionUnit * TTAMachine::PipelineElement::parentUnit () const
Referenced by TTAMachine::FunctionUnit::addPipelineElement(), TTAMachine::FunctionUnit::deletePipelineElement(), TTAMachine::PipelineElement::Comparator::operator()(), PipelineElement(), and setName().
setName()
void TTAMachine::PipelineElement::setName (const std::string & name)
Sets the name of the pipeline element.
Parameters
name The new name.
Exceptions
ComponentAlreadyExists If another pipeline element exists by the same name in the same function unit.
InvalidName If the given name is not a valid component name.
Definition at line 93 of file PipelineElement.cc.
{
    const string procName = "PipelineElement::setName";
    if (!MachineTester::isValidComponentName(name)) {
        throw InvalidName(__FILE__, __LINE__, procName);
    }
    if (name == this->name()) {
        return;
    }
    if (parentUnit()->hasPipelineElement(name)) {
        throw ComponentAlreadyExists(__FILE__, __LINE__, procName);
    }
    name_ = name;
}
References MachineTester::isValidComponentName(), name(), name_, and parentUnit().
Referenced by PipelineElement().
Member Data Documentation
name_
std::string TTAMachine::PipelineElement::name_ private
Name of the pipeline element.
Definition at line 62 of file PipelineElement.hh.
Referenced by setName().
parent_
FunctionUnit* TTAMachine::PipelineElement::parent_ private
The parent unit.
Definition at line 64 of file PipelineElement.hh.
Referenced by PipelineElement(), and ~PipelineElement().
The documentation for this class was generated from the following files:
PipelineElement.hh
PipelineElement.cc