OpenASIP: NOPEncoding Class Reference
NOPEncoding Class Reference
#include <NOPEncoding.hh>
Public Member Functions
NOPEncoding (unsigned int encoding, unsigned int extraBits, SlotField &parent)
NOPEncoding (const ObjectState *state, SlotField &parent)
virtual ~NOPEncoding ()
SlotField * parent () const
virtual int bitPosition () const
virtual ObjectState * saveState () const
Public Member Functions inherited from Encoding
virtual ~Encoding ()
InstructionField * parent () const
unsigned int encoding () const
unsigned int extraBits () const
virtual int width () const
Static Public Attributes
static const std::string OSNAME_NOP_ENCODING = "nop_encoding"
ObjectState name for NOP encoding.
Static Public Attributes inherited from Encoding
static const std::string OSNAME_ENCODING = "encoding"
ObjectState name for Encoding class.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
Additional Inherited Members
Protected Member Functions inherited from Encoding
Encoding (unsigned int encoding, unsigned int extraBits, InstructionField *parent)
Encoding (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
void setEncoding (unsigned int encoding, unsigned int extraBits)
Detailed Description
Represents the encoding for NOP (no operation) in the source field.
Definition at line 44 of file NOPEncoding.hh.
Constructor & Destructor Documentation
NOPEncoding() [1/2]
NOPEncoding::NOPEncoding (unsigned int encoding, unsigned int extraBits, SlotField & parent)
The constructor.
Registers the encoding automatically to the parent src/dst field.
Parameters
encoding The encoding for inline immediates.
extraBits The number of extra bits in the encoding.
parent The parent src/dst field.
Exceptions
ObjectAlreadyExists If the given parent field has a NOP encoding already or if the encoding is ambiguous with some other encoding in the parent field.
Definition at line 55 of file NOPEncoding.cc.
    : Encoding(encoding, extraBits, NULL) {
    parent.setNoOperationEncoding(*this);
    setParent(&parent);
}
References parent(), SlotField::setNoOperationEncoding(), and Encoding::setParent().
NOPEncoding() [2/2]
NOPEncoding::NOPEncoding (const ObjectState * state, SlotField & parent)
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
parent The parent field.
Exceptions
ObjectAlreadyExists If the given parent field has a NOP encoding already or if the encoding is ambiguous with some other encoding in the parent field.
ObjectStateLoadingException If the given ObjectState instance is erroneous.
Definition at line 76 of file NOPEncoding.cc.
    : Encoding(state, NULL) {
    const string procName = "NOPEncoding::NOPEncoding";
    if (state->name() != OSNAME_NOP_ENCODING) {
        throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    parent.setNoOperationEncoding(*this);
    setParent(&parent);
}
References ObjectState::name(), OSNAME_NOP_ENCODING, parent(), SlotField::setNoOperationEncoding(), and Encoding::setParent().
~NOPEncoding()
NOPEncoding::~NOPEncoding () virtual
The destructor.
Definition at line 91 of file NOPEncoding.cc.
{
    SlotField* oldParent = parent();
    assert(oldParent != NULL);
    setParent(NULL);
    oldParent->unsetNoOperationEncoding();
}
References assert, parent(), Encoding::setParent(), and SlotField::unsetNoOperationEncoding().
Member Function Documentation
bitPosition()
int NOPEncoding::bitPosition () const virtual
Returns the position of the encoding within the source field.
Returns
The position of the encoding.
Implements Encoding.
Definition at line 123 of file NOPEncoding.cc.
{
    if (parent()->componentIDPosition() == BinaryEncoding::LEFT) {
        return parent()->width() - parent()->extraBits() - width();
    } else {
        return 0;
    }
}
References InstructionField::extraBits(), BinaryEncoding::LEFT, parent(), Encoding::width(), and SlotField::width().
parent()
SlotField * NOPEncoding::parent () const
Returns the parent source field.
Returns
The parent.
Definition at line 105 of file NOPEncoding.cc.
{
    InstructionField* parent = Encoding::parent();
    if (parent != NULL) {
        SlotField* sField = dynamic_cast<SlotField*>(parent);
        assert(sField != NULL);
        return sField;
    } else {
        return NULL;
    }
}
References assert, Encoding::parent(), and parent().
Referenced by bitPosition(), NOPEncoding(), NOPEncoding(), parent(), SlotField::setNoOperationEncoding(), and ~NOPEncoding().
saveState()
ObjectState * NOPEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented from Encoding.
Definition at line 138 of file NOPEncoding.cc.
{
    ObjectState* state = Encoding::saveState();
    state->setName(OSNAME_NOP_ENCODING);
    return state;
}
References OSNAME_NOP_ENCODING, Encoding::saveState(), and ObjectState::setName().
Member Data Documentation
OSNAME_NOP_ENCODING
const std::string NOPEncoding::OSNAME_NOP_ENCODING = "nop_encoding" static
ObjectState name for NOP encoding.
Definition at line 57 of file NOPEncoding.hh.
Referenced by SlotField::loadState(), NOPEncoding(), saveState(), BEMSerializer::slotFieldToFile(), and BEMSerializer::slotFieldToOM().
The documentation for this class was generated from the following files:
NOPEncoding.hh
NOPEncoding.cc