OpenASIP: HDBEditor Class Reference
HDBEditor Class Reference
#include <HDBEditor.hh>
Public Member Functions
HDBEditor ()
virtual ~HDBEditor ()
virtual bool OnInit ()
virtual int OnExit ()
HDBEditorMainFrame & mainFrame () const
HDBBrowserWindow * browser () const
Private Member Functions
HDBEditor (const HDBEditor &)
Copying not allowed.
HDBEditor & operator= (const HDBEditor &)
Assignment not allowed.
void createDefaultOptions ()
Private Attributes
HDBEditorMainFrame * mainFrame_
Main window of the application.
Detailed Description
Main class for HDBEditor.
Initializes the application.
Definition at line 48 of file HDBEditor.hh.
Constructor & Destructor Documentation
HDBEditor() [1/2]
HDBEditor::HDBEditor ()
Constructor.
Definition at line 45 of file HDBEditor.cc.
                     : mainFrame_(NULL) {
}
~HDBEditor()
HDBEditor::~HDBEditor () virtual
Destructor.
Definition at line 51 of file HDBEditor.cc.
                      {
}
HDBEditor() [2/2]
HDBEditor::HDBEditor (const HDBEditor &) private
Copying not allowed.
Member Function Documentation
browser()
HDBBrowserWindow * HDBEditor::browser () const
Returns pointer to the browser window of the application main frame.
Returns
Browser window of the mainframe.
Definition at line 135 of file HDBEditor.cc.
{
    return mainFrame_->browser();
}
References HDBEditorMainFrame::browser(), and mainFrame_.
createDefaultOptions()
void HDBEditor::createDefaultOptions () private
mainFrame()
HDBEditorMainFrame & HDBEditor::mainFrame () const
Returns the main frame of the application.
Returns
The main frame of the application.
Definition at line 124 of file HDBEditor.cc.
{
    return *mainFrame_;
}
References mainFrame_.
OnExit()
int HDBEditor::OnExit () virtual
Deletes the application level dynamic objects not handled by wxWindows.
This function is called when application is about to exit.
Returns
0.
Definition at line 113 of file HDBEditor.cc.
                  {
    return 0;
}
OnInit()
bool HDBEditor::OnInit () virtual
Initializes the application.
Creates mainframe as well as reads the configure file.
Returns
True.
Definition at line 62 of file HDBEditor.cc.
                  {
    Application::initialize(argc, WxConversion::toCStringArray(argc, argv));
    mainFrame_ = new HDBEditorMainFrame(_T("HDB Editor"),
                                        wxPoint(50, 50), wxSize(900, 500));
    // parse command line
    static const wxCmdLineEntryDesc cmdLineDesc[] = {
#if wxCHECK_VERSION(3,0,0)
        { wxCMD_LINE_PARAM, "", "", "file", wxCMD_LINE_VAL_STRING,
          wxCMD_LINE_PARAM_OPTIONAL | wxCMD_LINE_PARAM_MULTIPLE },
        { wxCMD_LINE_NONE, "", "", "", wxCMD_LINE_VAL_STRING, 0}
#else
        { wxCMD_LINE_PARAM, _T(""), _T(""), _T("file"), wxCMD_LINE_VAL_STRING,
          wxCMD_LINE_PARAM_OPTIONAL | wxCMD_LINE_PARAM_MULTIPLE },
        { wxCMD_LINE_NONE, _T(""), _T(""), _T(""), wxCMD_LINE_VAL_STRING, 0}
#endif
    };
    wxCmdLineParser parser(cmdLineDesc, argc, argv);
    int parserStatus = parser.Parse();
    if (parserStatus != 0) {
        return false;
    }
    // open documents given in command line
    for (unsigned int i = 0; i < parser.GetParamCount(); i++) {
        wxString file = parser.GetParam(i);
        std::string fileName = WxConversion::toString(file);
        if (!FileSystem::fileExists(fileName)) {
        std::cerr << "File '" << fileName << "' not found." << std::endl;
        } else {
        mainFrame_->setHDB(fileName);
        }
    }
    mainFrame_->Show(true);
    SetTopWindow(mainFrame_);
    return true;
}
References FileSystem::fileExists(), Application::initialize(), mainFrame_, HDBEditorMainFrame::setHDB(), WxConversion::toCStringArray(), and WxConversion::toString().
operator=()
HDBEditor & HDBEditor::operator= (const HDBEditor &) private
Assignment not allowed.
Member Data Documentation
mainFrame_
HDBEditorMainFrame* HDBEditor::mainFrame_ private
Main window of the application.
Definition at line 67 of file HDBEditor.hh.
Referenced by browser(), mainFrame(), and OnInit().
The documentation for this class was generated from the following files:
HDBEditor.hh
HDBEditor.cc