OpenASIP: TPEF::Chunk Class Reference
TPEF::Chunk Class Reference
#include <Chunk.hh>
Public Member Functions
Chunk (SectionOffset offset)
virtual ~Chunk ()
SectionOffset offset () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
SectionOffset offset_
Offset to data where chunk is pointing.
Additional Inherited Members
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Chunk class for representing raw data offset in section.
Definition at line 45 of file Chunk.hh.
Constructor & Destructor Documentation
Chunk()
TPEF::Chunk::Chunk (SectionOffset offset)
Constructor.
Parameters
offset Offset to data where chunk is pointing to.
Definition at line 43 of file Chunk.cc.
                                 :
    SectionElement(), offset_(offset) {
}
~Chunk()
TPEF::Chunk::~Chunk () virtual
Destructor.
Definition at line 50 of file Chunk.cc.
              {
}
Member Function Documentation
offset()
SectionOffset TPEF::Chunk::offset () const
Referenced by TPEF::TPEFSymbolSectionWriter::actualWriteData(), TPEF::RawSection::belongsToSection(), TPEF::DataSection::byte(), TPEF::StringSection::chunk2String(), TPEF::RawSection::chunkToMAUIndex(), TPEF::TPEFUDataSectionWriter::createKeys(), TTAProgram::TPEFProgramFactory::createLabels(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::AOutSymbolSectionReader::readData(), ProgramImageGenerator::relocTarget(), and TPEF::TPEFTools::sectionOfElement().
Member Data Documentation
offset_
SectionOffset TPEF::Chunk::offset_ private
Offset to data where chunk is pointing.
Definition at line 54 of file Chunk.hh.
The documentation for this class was generated from the following files:
Chunk.hh
Chunk.cc