OpenASIP: TPEF::ReferenceManager::SectionIndexKey Class Reference
TPEF::ReferenceManager::SectionIndexKey Class Reference
#include <ReferenceKey.hh>
Public Member Functions
SectionIndexKey (SectionId sectionId, SectionIndex index)
virtual ~SectionIndexKey ()
bool operator== (const SectionIndexKey &other) const
bool operator!= (const SectionIndexKey &other) const
bool operator< (const SectionIndexKey &other) const
SectionId sectionId () const
SectionIndex index () const
Public Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
virtual ~ReferenceKey ()
Private Attributes
SectionId sectionId_
Section Identification code of the section that contains the element this key points to.
SectionIndex index_
Index of the element this key points to.
Additional Inherited Members
Protected Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
ReferenceKey ()
Detailed Description
With this type of key one can identify an object by means of a section identification code and the index of the element in the section.
Definition at line 65 of file ReferenceKey.hh.
Constructor & Destructor Documentation
SectionIndexKey()
TPEF::ReferenceManager::SectionIndexKey::SectionIndexKey (SectionId sectionId, SectionIndex index)
The constructor.
Parameters
sectionId Identification code of the section.
index Index of the element in section.
Definition at line 67 of file ReferenceKey.cc.
                                                                        :
    ReferenceKey(), sectionId_(sectionId), index_(index) {
}
~SectionIndexKey()
TPEF::ReferenceManager::SectionIndexKey::~SectionIndexKey () virtual
The destructor.
Definition at line 74 of file ReferenceKey.cc.
{
}
Member Function Documentation
index()
SectionIndex TPEF::ReferenceManager::SectionIndexKey::index () const
Referenced by TPEF::ReferenceManager::HashFunctions::operator()(), TPEF::ReferenceManager::SafePointer::resolve(), and TPEF::SectionIndexReplacer::tryToReplace().
operator!=()
bool TPEF::ReferenceManager::SectionIndexKey::operator!= (const SectionIndexKey & other) const
operator<()
bool TPEF::ReferenceManager::SectionIndexKey::operator< (const SectionIndexKey & other) const
operator==()
bool TPEF::ReferenceManager::SectionIndexKey::operator== (const SectionIndexKey & other) const
sectionId()
SectionId TPEF::ReferenceManager::SectionIndexKey::sectionId () const
Referenced by TPEF::ReferenceManager::HashFunctions::operator()(), and TPEF::ReferenceManager::SafePointer::resolve().
Member Data Documentation
index_
SectionIndex TPEF::ReferenceManager::SectionIndexKey::index_ private
Index of the element this key points to.
Definition at line 82 of file ReferenceKey.hh.
sectionId_
SectionId TPEF::ReferenceManager::SectionIndexKey::sectionId_ private
Section Identification code of the section that contains the element this key points to.
Definition at line 80 of file ReferenceKey.hh.
The documentation for this class was generated from the following files:
ReferenceKey.hh
ReferenceKey.cc