OpenASIP: BlocksModel Class Reference
BlocksModel Class Reference
#include <BlocksModel.hh>
Classes
struct FunctionalUnit
Public Member Functions
BlocksModel (std::string filename)
Public Attributes
std::list< FunctionalUnit > mFunctionalUnitList
Private Member Functions
void LoadModelFromXml ()
bool VerifyXmlStructure ()
Private Attributes
const std::map< std::string, BlocksTranslator::FU_TYPE > stringToEnum
ObjectState * mdfState_
Detailed Description
Definition at line 55 of file BlocksModel.hh.
Constructor & Destructor Documentation
BlocksModel()
BlocksModel::BlocksModel (std::string filename) inline
Definition at line 82 of file BlocksModel.hh.
{
        XMLSerializer* serializer = new XMLSerializer();
        serializer->setSourceFile(filename);
        mdfState_ = serializer->readState();
        LoadModelFromXml();
    };
References LoadModelFromXml(), mdfState_, XMLSerializer::readState(), and XMLSerializer::setSourceFile().
Member Function Documentation
LoadModelFromXml()
void BlocksModel::LoadModelFromXml () private
Load and parse the Blocks 'architecture.xml'.
Definition at line 44 of file BlocksModel.cc.
{
    // TODO(mm): add check for configuration bits
    if (!VerifyXmlStructure()) return;
    ObjectState* configs = mdfState_->childByName("configuration");
    ObjectState* fuState = configs->childByName("functionalunits");
    for (int i = 0; i < fuState->childCount(); i++) {
        ObjectState* fu = fuState->child(i);
        FunctionalUnit unit = {};
        unit.usesOut0 = false;
        unit.usesOut1 = false;
        string unitTypeString = fu->stringAttribute("type");
        unit.type = stringToEnum.at(unitTypeString);
        unit.name = fu->stringAttribute("name");
        // FU ports
        for (int srcnum = 0; srcnum < fu->childCount(); srcnum++) {
            ObjectState* srcPort = fu->child(srcnum);
            unit.src.push_back(srcPort->stringAttribute("source"));
        }
        mFunctionalUnitList.push_back(unit);  // Add functional unit to list
    }
}
References ObjectState::child(), ObjectState::childByName(), ObjectState::childCount(), mdfState_, mFunctionalUnitList, BlocksModel::FunctionalUnit::name, BlocksModel::FunctionalUnit::src, ObjectState::stringAttribute(), stringToEnum, BlocksModel::FunctionalUnit::type, BlocksModel::FunctionalUnit::usesOut0, BlocksModel::FunctionalUnit::usesOut1, and VerifyXmlStructure().
Referenced by BlocksModel().
VerifyXmlStructure()
bool BlocksModel::VerifyXmlStructure () private
Verify the structure of the 'architecture.xml' file.
Definition at line 74 of file BlocksModel.cc.
{
    return mdfState_->hasChild("configuration") &&
           mdfState_->hasChild("Core");
}
References ObjectState::hasChild(), and mdfState_.
Referenced by LoadModelFromXml().
Member Data Documentation
mdfState_
ObjectState* BlocksModel::mdfState_ private
Definition at line 78 of file BlocksModel.hh.
Referenced by BlocksModel(), LoadModelFromXml(), and VerifyXmlStructure().
mFunctionalUnitList
std::list<FunctionalUnit> BlocksModel::mFunctionalUnitList
Definition at line 88 of file BlocksModel.hh.
Referenced by BlocksTranslator::BuildTTAModel(), and LoadModelFromXml().
stringToEnum
const std::map<std::string, BlocksTranslator::FU_TYPE> BlocksModel::stringToEnum private
Initial value:
{
        {"ID", BlocksTranslator::FU_TYPE::ID},
        {"ABU", BlocksTranslator::FU_TYPE::ABU},
        {"IU", BlocksTranslator::FU_TYPE::IU},
        {"LSU", BlocksTranslator::FU_TYPE::LSU},
        {"ALU", BlocksTranslator::FU_TYPE::ALU},
        {"RF", BlocksTranslator::FU_TYPE::RF},
        {"MUL", BlocksTranslator::FU_TYPE::MUL}}
Definition at line 60 of file BlocksModel.hh.
{
        {"ID", BlocksTranslator::FU_TYPE::ID},
        {"ABU", BlocksTranslator::FU_TYPE::ABU},
        {"IU", BlocksTranslator::FU_TYPE::IU},
        {"LSU", BlocksTranslator::FU_TYPE::LSU},
        {"ALU", BlocksTranslator::FU_TYPE::ALU},
        {"RF", BlocksTranslator::FU_TYPE::RF},
        {"MUL", BlocksTranslator::FU_TYPE::MUL}};
Referenced by LoadModelFromXml().
The documentation for this class was generated from the following files:
BlocksModel.hh
BlocksModel.cc