OpenASIP: SocketPortConnFigure Class Reference
SocketPortConnFigure Class Reference
#include <SocketPortConnFigure.hh>
Public Member Functions
SocketPortConnFigure ()
virtual ~SocketPortConnFigure ()
Public Member Functions inherited from ConnectionFigure
virtual ~ConnectionFigure ()
void setSource (Figure *figure)
void setTarget (Figure *figure)
Figure * source () const
Figure * target () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
virtual void layoutSelf (wxDC *dc)
virtual void drawConnection (wxDC *dc)
Protected Member Functions inherited from ConnectionFigure
ConnectionFigure ()
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutChildren (wxDC *)
Private Member Functions
SocketPortConnFigure & operator= (SocketPortConnFigure &old)
Assignment not allowed.
SocketPortConnFigure (SocketPortConnFigure &old)
Copying not allowed.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(0, 0, 0)
Default colour for the figure.
Additional Inherited Members
Protected Attributes inherited from ConnectionFigure
Figure * source_
Source of connection.
Figure * target_
Target of connection.
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a socket-to-port connection.
Definition at line 46 of file SocketPortConnFigure.hh.
Constructor & Destructor Documentation
SocketPortConnFigure() [1/2]
SocketPortConnFigure::SocketPortConnFigure ()
The Constructor.
Definition at line 45 of file SocketPortConnFigure.cc.
                                          : ConnectionFigure() {
}
~SocketPortConnFigure()
SocketPortConnFigure::~SocketPortConnFigure () virtual
The Destructor.
Definition at line 51 of file SocketPortConnFigure.cc.
{
}
SocketPortConnFigure() [2/2]
SocketPortConnFigure::SocketPortConnFigure (SocketPortConnFigure & old) private
Copying not allowed.
Member Function Documentation
drawConnection()
void SocketPortConnFigure::drawConnection (wxDC * dc) protected virtual
Draws the connection line on the dc.
Definition at line 71 of file SocketPortConnFigure.cc.
{
    int xOffset = source_->bounds().GetWidth() / 2;
    int yOffset = MachineCanvasLayoutConstraints::PORT_WIDTH / 2;
    // assumes that port is always "source"
    dc->DrawLine(source_->location().x + xOffset,
         source_->location().y + yOffset*2,
         target_->location().x + xOffset,
         target_->location().y);
}
References Figure::bounds(), Figure::location(), MachineCanvasLayoutConstraints::PORT_WIDTH, ConnectionFigure::source_, and ConnectionFigure::target_.
Referenced by drawSelf(), and SocketPortConnToolFigure::drawSelf().
drawSelf()
void SocketPortConnFigure::drawSelf (wxDC * dc) protected virtual
Draws the connection's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from Figure.
Reimplemented in SocketPortConnToolFigure.
Definition at line 60 of file SocketPortConnFigure.cc.
{
    assert(source_ != NULL && target_ != NULL);
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    dc->SetPen(pen);
    drawConnection(dc);
}
References assert, DEFAULT_COLOUR, drawConnection(), ConnectionFigure::source_, and ConnectionFigure::target_.
layoutSelf()
void SocketPortConnFigure::layoutSelf (wxDC * dc) protected virtual
Sets the figure's bounds.
Reimplemented from Figure.
Definition at line 86 of file SocketPortConnFigure.cc.
{
    // assumes that port is always "source"
    int yOffset = MachineCanvasLayoutConstraints::PORT_WIDTH / 2;
    int xOffset = source_->bounds().GetWidth() / 2;
    setHeight(target_->location().y - source_->location().y - yOffset*2);
    if(source_->location().x < target_->location().x) {
        setWidth(target_->location().x - source_->location().x + 3);
        setLocation(
            wxPoint(source_->location().x - 1 + xOffset,
                    source_->location().y + yOffset*2));
    } else {
        setWidth(source_->location().x - target_->location().x + 3);
        setLocation(
            wxPoint(target_->location().x - 1 + xOffset,
                    source_->location().y + yOffset*2));
    }
}
References Figure::bounds(), Figure::location(), MachineCanvasLayoutConstraints::PORT_WIDTH, Figure::setHeight(), Figure::setLocation(), Figure::setWidth(), ConnectionFigure::source_, and ConnectionFigure::target_.
operator=()
SocketPortConnFigure & SocketPortConnFigure::operator= (SocketPortConnFigure & old) private
Assignment not allowed.
Member Data Documentation
DEFAULT_COLOUR
const wxColour SocketPortConnFigure::DEFAULT_COLOUR = wxColour(0, 0, 0) static private
Default colour for the figure.
Definition at line 62 of file SocketPortConnFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
SocketPortConnFigure.hh
SocketPortConnFigure.cc