OpenASIP: CmdQuit Class Reference
CmdQuit Class Reference
#include <TestOsal.hh>
Public Member Functions
CmdQuit ()
CmdQuit (const CmdQuit &cmd)
virtual ~CmdQuit ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Detailed Description
Command that quits the execution of the program.
Definition at line 94 of file TestOsal.hh.
Constructor & Destructor Documentation
CmdQuit() [1/2]
CmdQuit::CmdQuit ()
Constructor.
Definition at line 549 of file TestOsal.cc.
                 : CustomCommand("quit") {
}
CmdQuit() [2/2]
CmdQuit::CmdQuit (const CmdQuit & cmd) explicit
Copy constructor.
Parameters
cmd Command to be copied.
Definition at line 557 of file TestOsal.cc.
                                   : CustomCommand(cmd) {
}
~CmdQuit()
CmdQuit::~CmdQuit () virtual
Destructor.
Definition at line 563 of file TestOsal.cc.
                  {
}
Member Function Documentation
execute()
bool CmdQuit::execute (const std::vector< DataObject > & arguments) virtual
Executes the command.
The execution of the quit command will stop the program.
Parameters
arguments Arguments for the command.
Exceptions
NumberFormatException If DataObject conversion fails.
Returns
True if execution is successful, false otherwise.
Implements CustomCommand.
Definition at line 576 of file TestOsal.cc.
{
    ScriptInterpreter* scriptInterp = interpreter();
    OsalInterpreter* interp = dynamic_cast<OsalInterpreter*>(scriptInterp);
    DataObject* result = new DataObject();
    assert(interp != NULL);
    if (arguments.size() != 1) {
        result->setString("wrong number of arguments");
        interp->setResult(result);
    return false;
    }
    InterpreterContext& interpCont = interp->context();
    TesterContext& testCont = *dynamic_cast<TesterContext*>(&interpCont);
    testCont.stop();
    result->setString("");
    interp->setResult(result);
    return true;
}
References assert, SimpleScriptInterpreter::context(), CustomCommand::interpreter(), ScriptInterpreter::setResult(), DataObject::setString(), and TesterContext::stop().
helpText()
string CmdQuit::helpText () const virtual
Returns the help text of the command.
Returns
The help text.
Implements CustomCommand.
Definition at line 602 of file TestOsal.cc.
{
    return "exits the program";
}
The documentation for this class was generated from the following files:
TestOsal.hh
TestOsal.cc