OpenASIP: BuslessExecutableMove Class Reference
BuslessExecutableMove Class Reference
#include <BuslessExecutableMove.hh>
Public Member Functions
BuslessExecutableMove (const ReadableState &src, WritableState &dst)
BuslessExecutableMove (const ReadableState &src, WritableState &dst, const ReadableState &guardReg, bool negated)
BuslessExecutableMove (InlineImmediateValue *immediateSource, WritableState &dst, const ReadableState &guardReg, bool negated)
BuslessExecutableMove (InlineImmediateValue *immediateSource, WritableState &dst)
virtual ~BuslessExecutableMove ()
virtual void executeRead ()
virtual void executeWrite ()
Public Member Functions inherited from ExecutableMove
ExecutableMove (const ReadableState &src, BusState &bus, WritableState &dst)
ExecutableMove (const ReadableState &src, BusState &bus, WritableState &dst, const ReadableState &guardReg, bool negated)
ExecutableMove (InlineImmediateValue *immediateSource, BusState &bus, WritableState &dst, const ReadableState &guardReg, bool negated)
ExecutableMove (InlineImmediateValue *immediateSource, BusState &bus, WritableState &dst)
virtual ~ExecutableMove ()
virtual void evaluateGuard ()
virtual bool squashed () const
ClockCycleCount executionCount () const
void resetExecutionCount ()
Private Member Functions
BuslessExecutableMove (const BuslessExecutableMove &)
Copying not allowed.
BuslessExecutableMove & operator= (const BuslessExecutableMove &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from ExecutableMove
ExecutableMove ()
Protected Attributes inherited from ExecutableMove
const ReadableState * src_
Source of the move.
BusState * bus_
Bus of the move.
WritableState * dst_
Destination of the move.
const ReadableState * guardReg_
Guard of the move.
const bool guarded_
True if this is a guarded move.
const bool negated_
True if guard is inverted.
ClockCycleCount executionCount_
The count of times this move has been fully executed (without squash).
bool squashed_
True in case this move was squashed last time it was executed.
Detailed Description
Represents an interpreted move which does not utilize a transport bus.
Moves that utilize this class include control unit internal moves such as control flow operations (jump, call) with immediate or RA source. This class can be used also for simulating data transports of sequential code, as writing to (the universal) bus is not necessary in that case.
Definition at line 53 of file BuslessExecutableMove.hh.
Constructor & Destructor Documentation
BuslessExecutableMove() [1/5]
BuslessExecutableMove::BuslessExecutableMove (const ReadableState & src, WritableState & dst)
Constructor.
Parameters
src Source of the move.
dst Destination of the move.
Definition at line 45 of file BuslessExecutableMove.cc.
                        :
    ExecutableMove(src, NullBusState::instance(), dst) {
}
BuslessExecutableMove() [2/5]
BuslessExecutableMove::BuslessExecutableMove (const ReadableState & src, WritableState & dst, const ReadableState & guardReg, bool negated)
Constructor.
Parameters
src Source of the move.
bus Bus of the move.
dst Destination of the move.
guardReg Guard register.
negated True if guard is reversed.
Definition at line 60 of file BuslessExecutableMove.cc.
                  :
    ExecutableMove(src, NullBusState::instance(), dst, guardReg, negated) {
}
BuslessExecutableMove() [3/5]
BuslessExecutableMove::BuslessExecutableMove (InlineImmediateValue * immediateSource, WritableState & dst, const ReadableState & guardReg, bool negated)
Constructor.
Used to construct a move that has an inline immediate as the source. The inline immediate becomes property of the created BuslessExecutableMove and is deleted by it.
Parameters
immediateSource The inline immediate source of the move.
bus Bus of the move.
dst Destination of the move.
guardReg Guard register.
negated True if guard is reversed.
Definition at line 81 of file BuslessExecutableMove.cc.
                  :
    ExecutableMove(
        immediateSource, NullBusState::instance(), dst, guardReg, negated) {
}
BuslessExecutableMove() [4/5]
BuslessExecutableMove::BuslessExecutableMove (InlineImmediateValue * immediateSource, WritableState & dst)
Constructor.
Used to construct a move that has an inline immediate as the source. The inline immediate becomes property of the created BuslessExecutableMove and is deleted by it.
Parameters
immediateSource The inline immediate source of the move.
bus Bus of the move.
dst Destination of the move.
guardReg Guard register.
negated True if guard is reversed.
Definition at line 103 of file BuslessExecutableMove.cc.
                        :
    ExecutableMove(immediateSource, NullBusState::instance(), dst) {
}
~BuslessExecutableMove()
BuslessExecutableMove::~BuslessExecutableMove () virtual
Destructor.
Definition at line 113 of file BuslessExecutableMove.cc.
{
}
BuslessExecutableMove() [5/5]
BuslessExecutableMove::BuslessExecutableMove (const BuslessExecutableMove &) private
Copying not allowed.
Member Function Documentation
executeRead()
void BuslessExecutableMove::executeRead () virtual
Does not do anything because value is transferred directly from source to destination without writing to a bus first.
Reimplemented from ExecutableMove.
Definition at line 122 of file BuslessExecutableMove.cc.
{
}
executeWrite()
void BuslessExecutableMove::executeWrite () virtual
Writes the value from source to the destination.
If the move is guarded, the value is written to destination only if guard expression is true.
Reimplemented from ExecutableMove.
Definition at line 132 of file BuslessExecutableMove.cc.
{
    if (guarded_) {
        const SimValue& regValue = guardReg_->value();
        const bool guardTerm = (regValue.sLongWordValue() & 1l) == 1;
        if (!(( guardTerm && !negated_) ||
              (!guardTerm &&  negated_))) {
            // guard expression evaluated to false
            squashed_ = true;
            return;
        }
    }
    squashed_ = false;
    dst_->setValue(src_->value());
    executionCount_++;
}
References ExecutableMove::dst_, ExecutableMove::executionCount_, ExecutableMove::guarded_, ExecutableMove::guardReg_, ExecutableMove::negated_, WritableState::setValue(), SimValue::sLongWordValue(), ExecutableMove::squashed_, ExecutableMove::src_, and ReadableState::value().
operator=()
BuslessExecutableMove & BuslessExecutableMove::operator= (const BuslessExecutableMove &) private
Assignment not allowed.
The documentation for this class was generated from the following files:
BuslessExecutableMove.hh
BuslessExecutableMove.cc