OpenASIP: BFRemoveGuardFromSucc Class Reference
BFRemoveGuardFromSucc Class Reference
#include <BFRemoveGuardFromSucc.hh>
Public Member Functions
BFRemoveGuardFromSucc (BF2Scheduler &sched, MoveNode &succ)
bool operator() () override
void undoOnlyMe () override
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Private Attributes
MoveNode & mn_
TTAProgram::MoveGuard * guard_
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 54 of file BFRemoveGuardFromSucc.hh.
Constructor & Destructor Documentation
BFRemoveGuardFromSucc()
BFRemoveGuardFromSucc::BFRemoveGuardFromSucc (BF2Scheduler & sched, MoveNode & succ) inline
Definition at line 56 of file BFRemoveGuardFromSucc.hh.
                                             :
        BFOptimization(sched), mn_(succ) {}
Member Function Documentation
operator()()
bool BFRemoveGuardFromSucc::operator() () override virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 47 of file BFRemoveGuardFromSucc.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tRemoving guard from succ: " << mn_.toString()
              << std::endl;
#endif
    int cycle = mn_.cycle();
    BFOptimization* unsched = new BFUnscheduleMove(sched_, mn_);
    if (!runPreChild(unsched)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tUnsched failed: " << mn_.toString()
                  << std::endl;
#endif
        return false;
    }
    // Remove the guard edges from the ddg
    auto inEdges = ddg().inEdges(mn_);
    for (auto e: inEdges) {
        if (e->guardUse() && !e->isFalseDep()) {
            runPreChild(new BFRemoveEdge(sched_, ddg().tailNode(*e), mn_,*e));
        }
    }
    auto outEdges = ddg().outEdges(mn_);
    for (auto e: outEdges) {
        if (e->guardUse() &&
            e->dependenceType() == DataDependenceEdge::DEP_WAR) {
            runPreChild(new BFRemoveEdge(sched_, mn_,ddg().headNode(*e), *e));
        }
    }
    // If the prolog move has already been created, update also it
    MoveNode* prologMN = ii() ? duplicator().getMoveNode(mn_) : nullptr;
    if (prologMN != nullptr) {
        prologMN->move().setGuard(NULL);
    }
    guard_ = mn_.move().guard().copy();
    mn_.move().setGuard(NULL);
    BFOptimization* sched = new BFSchedule(sched_, mn_, cycle);
    if (runPostChild(sched)) {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tRe-scheduling ok: " << mn_.toString()
                  << std::endl;
#endif
        return true;
    } else {
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
        std::cerr << "\t\t\t\tRe-scheduling failed, undoing..: "
                  << mn_.toString() << std::endl;
#endif
        undo();
        return false;
    }
}
References TTAProgram::MoveGuard::copy(), MoveNode::cycle(), BFOptimization::ddg(), DataDependenceEdge::DEP_WAR, BFOptimization::duplicator(), MoveNodeDuplicator::getMoveNode(), TTAProgram::Move::guard(), guard_, BFOptimization::ii(), BoostGraph< GraphNode, GraphEdge >::inEdges(), mn_, MoveNode::move(), BoostGraph< GraphNode, GraphEdge >::outEdges(), Reversible::runPostChild(), Reversible::runPreChild(), BFOptimization::sched_, TTAProgram::Move::setGuard(), MoveNode::toString(), and Reversible::undo().
undoOnlyMe()
void BFRemoveGuardFromSucc::undoOnlyMe () override virtual
Undoes the operations done by this class but not children. This method should be overloaded by most derived classes.
Reimplemented from Reversible.
Definition at line 102 of file BFRemoveGuardFromSucc.cc.
{
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tRestoring guard to succ: " << mn_.toString()
              << std::endl;
#endif
    // If the prolog move has already been created, update also it
    MoveNode* prologMN = ii() ? duplicator().getMoveNode(mn_) : nullptr;
    if (prologMN != nullptr) {
        prologMN->move().setGuard(guard_->copy());
    }
    mn_.move().setGuard(guard_);
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tRestored guard to succ: " << mn_.toString()
              << std::endl;
#endif
}
References TTAProgram::MoveGuard::copy(), BFOptimization::duplicator(), MoveNodeDuplicator::getMoveNode(), guard_, BFOptimization::ii(), mn_, MoveNode::move(), TTAProgram::Move::setGuard(), and MoveNode::toString().
Member Data Documentation
guard_
TTAProgram::MoveGuard* BFRemoveGuardFromSucc::guard_ private
Definition at line 63 of file BFRemoveGuardFromSucc.hh.
Referenced by operator()(), and undoOnlyMe().
mn_
MoveNode& BFRemoveGuardFromSucc::mn_ private
Definition at line 62 of file BFRemoveGuardFromSucc.hh.
Referenced by operator()(), and undoOnlyMe().
The documentation for this class was generated from the following files:
BFRemoveGuardFromSucc.hh
BFRemoveGuardFromSucc.cc