OpenASIP: GuardEncoding Class Reference
GuardEncoding Class Reference
#include <GuardEncoding.hh>
Public Member Functions
virtual ~GuardEncoding ()
GuardField * parent () const
bool isGuardInverted () const
unsigned int encoding () const
virtual ObjectState * saveState () const
Static Public Attributes
static const std::string OSNAME_GUARD_ENCODING = "guard_encoding"
ObjectState name for guard encoding.
static const std::string OSKEY_INVERTED = "inverted"
ObjectState attribute key for invert flag.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for encoding.
Protected Member Functions
GuardEncoding (bool inverted, unsigned int encoding)
GuardEncoding (const ObjectState *state)
void setParent (GuardField *parent)
Private Attributes
bool inverted_
The "invert" flag.
unsigned int encoding_
The encoding.
GuardField * parent_
The parent guard field.
Detailed Description
GuardEncoding class captures the properties shared by all types of guard encoding.
Definition at line 45 of file GuardEncoding.hh.
Constructor & Destructor Documentation
~GuardEncoding()
GuardEncoding::~GuardEncoding () virtual
The destructor
Definition at line 80 of file GuardEncoding.cc.
{
}
GuardEncoding() [1/2]
GuardEncoding::GuardEncoding (bool inverted, unsigned int encoding) protected
The constructor.
Parameters
inverted The "invert" flag.
encoding The control code.
Definition at line 51 of file GuardEncoding.cc.
                                                                 :
    inverted_(inverted), encoding_(encoding), parent_(NULL) {
}
GuardEncoding() [2/2]
GuardEncoding::GuardEncoding (const ObjectState * state) protected
The constructor.
Loads the state of the object from the given ObjectState instance.
Parameters
state The ObjectState instance.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Definition at line 65 of file GuardEncoding.cc.
    : inverted_(false), encoding_(0), parent_(NULL) {
    try {
    inverted_ = state->boolAttribute(OSKEY_INVERTED);
    encoding_ = state->intAttribute(OSKEY_ENCODING);
    } catch (const Exception& exception) {
    const string procName = "GuardEncoding::GuardEncoding";
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References ObjectState::boolAttribute(), encoding_, Exception::errorMessage(), ObjectState::intAttribute(), inverted_, OSKEY_ENCODING, and OSKEY_INVERTED.
Member Function Documentation
encoding()
unsigned int GuardEncoding::encoding () const
Returns the control code of the guard expression.
Returns
The control code.
Definition at line 112 of file GuardEncoding.cc.
{
    return encoding_;
}
References encoding_.
Referenced by CodeCompressorPlugin::addBitsForGuardField(), GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), BEMTester::conflictsWithGuardEncoding(), CodeCompressorPlugin::encodeNOP(), GuardField::isAssigned(), printGuardFieldEncodings(), saveState(), GuardField::width(), DefaultDecoderGenerator::writeSquashSignalGenerationProcess(), and DefaultDecoderGenerator::writeSquashSignalSubstitution().
isGuardInverted()
bool GuardEncoding::isGuardInverted () const
Tells whether the guard expression is inverted.
Returns
True if the guard expression is inverted, otherwise false.
Definition at line 101 of file GuardEncoding.cc.
{
    return inverted_;
}
References inverted_.
Referenced by GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), GuardField::fuGuardEncoding(), GuardField::gprGuardEncoding(), GuardField::hasFUGuardEncoding(), GuardField::hasGPRGuardEncoding(), printGuardFieldEncodings(), GuardField::removeUnconditionalGuardEncoding(), and saveState().
parent()
GuardField * GuardEncoding::parent () const
Returns the parent guard field.
Returns
The parent guard field.
Definition at line 90 of file GuardEncoding.cc.
{
    return parent_;
}
References parent_.
Referenced by GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), GuardField::addGuardEncoding(), DefaultDecoderGenerator::findGuard(), DefaultDecoderGenerator::findGuard(), FUGuardEncoding::FUGuardEncoding(), FUGuardEncoding::FUGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), GuardField::removeGuardEncoding(), GuardField::removeGuardEncoding(), GuardField::removeUnconditionalGuardEncoding(), setParent(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), FUGuardEncoding::~FUGuardEncoding(), GPRGuardEncoding::~GPRGuardEncoding(), and UnconditionalGuardEncoding::~UnconditionalGuardEncoding().
saveState()
ObjectState * GuardEncoding::saveState () const virtual
Saves the state of the object to an ObjectState instance.
Returns
The newly created ObjectState instance.
Reimplemented in FUGuardEncoding, GPRGuardEncoding, and UnconditionalGuardEncoding.
Definition at line 123 of file GuardEncoding.cc.
{
    ObjectState* state = new ObjectState(OSNAME_GUARD_ENCODING);
    state->setAttribute(OSKEY_INVERTED, isGuardInverted());
    state->setAttribute(OSKEY_ENCODING, encoding());
    return state;
}
References encoding(), isGuardInverted(), OSKEY_ENCODING, OSKEY_INVERTED, OSNAME_GUARD_ENCODING, and ObjectState::setAttribute().
Referenced by FUGuardEncoding::saveState(), GPRGuardEncoding::saveState(), and UnconditionalGuardEncoding::saveState().
setParent()
void GuardEncoding::setParent (GuardField * parent) protected
Sets the parent pointer.
Parameters
parent The parent.
Definition at line 137 of file GuardEncoding.cc.
{
    parent_ = parent;
}
References parent(), and parent_.
Referenced by FUGuardEncoding::FUGuardEncoding(), FUGuardEncoding::FUGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), GPRGuardEncoding::GPRGuardEncoding(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), UnconditionalGuardEncoding::UnconditionalGuardEncoding(), FUGuardEncoding::~FUGuardEncoding(), GPRGuardEncoding::~GPRGuardEncoding(), and UnconditionalGuardEncoding::~UnconditionalGuardEncoding().
Member Data Documentation
encoding_
unsigned int GuardEncoding::encoding_ private
The encoding.
Definition at line 71 of file GuardEncoding.hh.
Referenced by encoding(), and GuardEncoding().
inverted_
bool GuardEncoding::inverted_ private
The "invert" flag.
Definition at line 69 of file GuardEncoding.hh.
Referenced by GuardEncoding(), and isGuardInverted().
OSKEY_ENCODING
const std::string GuardEncoding::OSKEY_ENCODING = "encoding" static
ObjectState attribute key for encoding.
Definition at line 60 of file GuardEncoding.hh.
Referenced by GuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSKEY_INVERTED
const std::string GuardEncoding::OSKEY_INVERTED = "inverted" static
ObjectState attribute key for invert flag.
Definition at line 58 of file GuardEncoding.hh.
Referenced by GuardEncoding(), BEMSerializer::guardFieldToFile(), BEMSerializer::guardFieldToOM(), and saveState().
OSNAME_GUARD_ENCODING
const std::string GuardEncoding::OSNAME_GUARD_ENCODING = "guard_encoding" static
ObjectState name for guard encoding.
Definition at line 56 of file GuardEncoding.hh.
Referenced by saveState().
parent_
GuardField* GuardEncoding::parent_ private
The parent guard field.
Definition at line 73 of file GuardEncoding.hh.
Referenced by parent(), and setParent().
The documentation for this class was generated from the following files:
GuardEncoding.hh
GuardEncoding.cc