OpenASIP: BuildOpsetOptions Class Reference
BuildOpsetOptions Class Reference
#include <BuildOpset.hh>
Public Member Functions
BuildOpsetOptions ()
virtual ~BuildOpsetOptions ()
virtual void printVersion () const
std::string install () const
std::string sourceDir () const
bool ignore () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual void printHelp () const
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Class that handles options passed to build_opset.
Definition at line 42 of file BuildOpset.hh.
Constructor & Destructor Documentation
BuildOpsetOptions()
BuildOpsetOptions::BuildOpsetOptions ()
Constructor.
Definition at line 62 of file BuildOpset.cc.
                                     :
    CmdLineOptions("Usage: buildopset [options] module_name") {
    TCEString desc;
    desc += "\n\tIgnore the case whereby the source file containing the\n";
    desc += "\toperation behavior model code are not found. By default, the\n";
    desc += "\tOSAL Builder aborts if it cannot build the dynamic module.\n";
    desc += "\tThis option may be used in combination with install option\n";
    desc += "\tto install XML data even if operation behavior definitions\n";
    desc += "\tdo not exist.";
    BoolCmdLineOptionParser* ignore =
     new BoolCmdLineOptionParser("ignore", desc, "b");
    addOption(ignore);
    desc = "\n\tEnter explicit directory where the behavior definition\n";
    desc += "\tsource file to be used is found.\n";
    StringCmdLineOptionParser* sourceDir =
        new StringCmdLineOptionParser("source-dir", desc, "s");
    addOption(sourceDir);
}
References CmdLineParser::addOption(), ignore(), and sourceDir().
~BuildOpsetOptions()
BuildOpsetOptions::~BuildOpsetOptions () virtual
Destructor
Definition at line 86 of file BuildOpset.cc.
{
}
Member Function Documentation
ignore()
bool BuildOpsetOptions::ignore () const
Returns the value of the ignore option.
Returns
The value of the ignore option.
Definition at line 114 of file BuildOpset.cc.
{
    return findOption("ignore")->isFlagOn();
}
References CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
Referenced by BuildOpsetOptions().
install()
std::string BuildOpsetOptions::install () const
printVersion()
void BuildOpsetOptions::printVersion () const virtual
Prints the version of the application.
Implements CmdLineOptions.
Definition at line 93 of file BuildOpset.cc.
{
    cout << "buildopset - Operation behavior module builder "
         << Application::TCEVersionString() << endl;
}
References Application::TCEVersionString().
sourceDir()
string BuildOpsetOptions::sourceDir () const
Returns the value of the source-dir option.
Returns
The value of the source-dir option.
Definition at line 104 of file BuildOpset.cc.
{
    return findOption("source-dir")->String();
}
References CmdLineParser::findOption(), and CmdLineOptionParser::String().
Referenced by BuildOpsetOptions().
The documentation for this class was generated from the following files:
BuildOpset.hh
BuildOpset.cc