OpenASIP: BridgeFigure Class Reference
BridgeFigure Class Reference
#include <BridgeFigure.hh>
Public Types
enum Direction { DIR_RIGHT , DIR_LEFT , DIR_BIDIR }
Direction of the bridge.
Public Member Functions
BridgeFigure ()
virtual ~BridgeFigure ()
void setDirection (BridgeFigure::Direction direction)
Direction direction () const
Public Member Functions inherited from ConnectionFigure
virtual ~ConnectionFigure ()
void setSource (Figure *figure)
void setTarget (Figure *figure)
Figure * source () const
Figure * target () const
Public Member Functions inherited from Figure
Figure ()
virtual ~Figure ()
wxPoint location () const
void setLocation (wxPoint point)
void setX (int x)
void setY (int y)
void setPreferredX (int x)
bool xSet () const
void clearXSetFlag ()
virtual wxRect bounds () const
virtual wxRect virtualBounds () const
void setBounds (wxSize bounds)
void setWidth (int width)
void setHeight (int height)
virtual void addChild (Figure *child)
int childCount () const
Figure * child (int index) const
virtual void layout (wxDC *dc)
virtual void draw (wxDC *dc)
void highlight (const wxColour &colour)
void clearHighlight ()
void setOptions (MachineCanvasOptions *options)
MachineCanvasOptions * options ()
Protected Member Functions
virtual void drawSelf (wxDC *dc)
Protected Member Functions inherited from ConnectionFigure
ConnectionFigure ()
Protected Member Functions inherited from Figure
void drawChildren (wxDC *dc)
virtual void layoutSelf (wxDC *)
virtual void layoutChildren (wxDC *)
Private Member Functions
BridgeFigure & operator= (BridgeFigure &old)
Assignment not allowed.
BridgeFigure (BridgeFigure &old)
Copying not allowed.
Private Attributes
Direction direction_
Direction of the bridge.
Static Private Attributes
static const wxColour DEFAULT_COLOUR = wxColour(0, 0, 0)
Default colour for figure lines.
static const wxColour DEFAULT_BG_COLOUR = wxColour(150, 200, 255)
Default colour for figure background.
Additional Inherited Members
Protected Attributes inherited from ConnectionFigure
Figure * source_
Source of connection.
Figure * target_
Target of connection.
Protected Attributes inherited from Figure
wxPoint location_
Top-left location of the Figure's bounding rectangle.
wxSize size_
wxSize of the Figure's bounding rectangle.
wxSize minSize_
Figure's minimum size.
std::vector< Figure * > children_
Figure's children.
bool xSet_
Tells if x-coordinate has been fixed.
bool laidOut_
Tells whether the Figure and its children have been laid out or not.
bool drawn_
Tells whether the Figure and its children have been drawn or not.
wxColour highlight_
Highlight colour.
bool highlighted_
Tells if the figure is highlighted.
MachineCanvasOptions * options_
Options which are used for customizing figures.
Detailed Description
Figure of a bridge.
Definition at line 46 of file BridgeFigure.hh.
Member Enumeration Documentation
Direction
enum BridgeFigure::Direction
Direction of the bridge.
Enumerator
DIR_RIGHT
DIR_LEFT
DIR_BIDIR
Definition at line 49 of file BridgeFigure.hh.
{DIR_RIGHT, DIR_LEFT, DIR_BIDIR};
Constructor & Destructor Documentation
BridgeFigure() [1/2]
BridgeFigure::BridgeFigure ()
The Constructor.
Definition at line 43 of file BridgeFigure.cc.
                          :
    ConnectionFigure(), direction_(BridgeFigure::DIR_RIGHT) {
    size_ = wxSize(
    MachineCanvasLayoutConstraints::BRIDGE_WIDTH,
    MachineCanvasLayoutConstraints::BRIDGE_HEIGHT);
}
References MachineCanvasLayoutConstraints::BRIDGE_HEIGHT, MachineCanvasLayoutConstraints::BRIDGE_WIDTH, and Figure::size_.
~BridgeFigure()
BridgeFigure::~BridgeFigure () virtual
The Destructor.
Definition at line 53 of file BridgeFigure.cc.
{
}
BridgeFigure() [2/2]
BridgeFigure::BridgeFigure (BridgeFigure & old) private
Copying not allowed.
Member Function Documentation
direction()
Direction BridgeFigure::direction () const
Referenced by BusChainFigure::layoutChildren().
drawSelf()
void BridgeFigure::drawSelf (wxDC * dc) protected virtual
Draws the bridge's Figure on the given device context.
Parameters
dc The device context.
Reimplemented from Figure.
Reimplemented in BidirBridgeFigure.
Definition at line 62 of file BridgeFigure.cc.
{
    wxPen pen = wxPen(DEFAULT_COLOUR, 1, wxSOLID);
    dc->SetPen(pen);
    wxBrush brush = wxBrush(DEFAULT_BG_COLOUR, wxSOLID);
    dc->SetBrush(brush);
    const unsigned int triangleWidth = 200;
    wxPoint trianglePoints[3];
    if (direction_ == DIR_RIGHT) {
    trianglePoints[0] = wxPoint(
        location_.x + size_.GetWidth() / 2 - triangleWidth / 2,
        location_.y );
    trianglePoints[1] = wxPoint(
        trianglePoints[0].x + triangleWidth, location_.y);
    trianglePoints[2] = wxPoint(
        trianglePoints[0].x + triangleWidth / 2,
        location_.y + size_.GetHeight());
    } else {
    trianglePoints[0] = wxPoint(
        location_.x + size_.GetWidth() / 2 - triangleWidth / 2,
        location_.y + size_.GetHeight());
    trianglePoints[1] = wxPoint(
        trianglePoints[0].x + triangleWidth, trianglePoints[0].y);
    trianglePoints[2] = wxPoint(
        location_.x + size_.GetWidth() / 2, location_.y);
    }
    dc->DrawPolygon(3, trianglePoints);
}
References DEFAULT_BG_COLOUR, DEFAULT_COLOUR, DIR_RIGHT, direction_, Figure::location_, and Figure::size_.
operator=()
BridgeFigure & BridgeFigure::operator= (BridgeFigure & old) private
Assignment not allowed.
setDirection()
void BridgeFigure::setDirection (BridgeFigure::Direction direction)
Referenced by MachineEditPartFactory::createBiDirBridge(), BidirBridgeFigure::layoutChildren(), and BusChainFigure::layoutChildren().
Member Data Documentation
DEFAULT_BG_COLOUR
const wxColour BridgeFigure::DEFAULT_BG_COLOUR = wxColour(150, 200, 255) static private
Default colour for figure background.
Definition at line 72 of file BridgeFigure.hh.
Referenced by drawSelf().
DEFAULT_COLOUR
const wxColour BridgeFigure::DEFAULT_COLOUR = wxColour(0, 0, 0) static private
Default colour for figure lines.
Definition at line 70 of file BridgeFigure.hh.
Referenced by drawSelf().
direction_
Direction BridgeFigure::direction_ private
Direction of the bridge.
Definition at line 67 of file BridgeFigure.hh.
Referenced by drawSelf().
The documentation for this class was generated from the following files:
BridgeFigure.hh
BridgeFigure.cc