OpenASIP: ProcessorImplementationWindow Class Reference
ProcessorImplementationWindow Class Reference
#include <ProcessorImplementationWindow.hh>
Public Member Functions
ProcessorImplementationWindow (wxWindow *parent, TTAMachine::Machine &machine, IDF::MachineImplementation &impl)
virtual ~ProcessorImplementationWindow ()
void setDirty (bool dirty=true)
Private Types
enum {
ID_LOAD_IDF , ID_SAVE_IDF , ID_GENERATE_PROCESSOR , ID_FU_LIST ,
ID_IU_LIST , ID_RF_LIST , ID_AUTO_SELECT_IMPL , ID_SELECT_FU_IMPL ,
ID_SELECT_IU_IMPL , ID_SELECT_RF_IMPL , ID_BROWSE_DECOMPRESSOR , ID_BROWSE_IC_DEC_PLUGIN ,
ID_BROWSE_IC_DEC_HDB , ID_DECOMPRESSOR_PATH , ID_IC_DEC_PLUGIN_FILE , ID_IC_DEC_PLUGIN_NAME ,
ID_IC_DEC_PLUGIN_DESC , ID_IC_DEC_HDB_FILE , ID_PARAMETER_LIST , ID_PARAMETER_VALUE ,
ID_SET_VALUE , ID_NOTEBOOK , ID_GENERATE , ID_CLOSE ,
ID_TEXT , ID_LINE
}
Private Member Functions
void onAutoSelectImplementations (wxCommandEvent &event)
void updateImplementationLists ()
void handleSelectRFImplementation (long item)
void onSelectRFImplementation (wxCommandEvent &event)
void onRFSelection (wxListEvent &event)
void onRFActivation (wxListEvent &event)
void updateRFList (const std::string &rfName, int index)
void handleSelectIUImplementation (long item)
void onSelectIUImplementation (wxCommandEvent &event)
void onIUSelection (wxListEvent &event)
void onIUActivation (wxListEvent &event)
void handleSelectFUImplementation (long item)
void onSelectFUImplementation (wxCommandEvent &event)
void onFUSelection (wxListEvent &event)
void onFUActivation (wxListEvent &event)
void updateFUList (const std::string &fuName, int index)
void onSetParameterValue (wxCommandEvent &event)
void onBrowseDecompressor (wxCommandEvent &event)
void onBrowseICDecPlugin (wxCommandEvent &event)
void onBrowseICHDB (wxCommandEvent &event)
void loadICDecoderPlugin (const std::string &pluginName, const std::string &pluginFile)
void onParameterSelection (wxListEvent &event)
virtual bool TransferDataToWindow ()
void onLoadIDF (wxCommandEvent &event)
void onSaveIDF (wxCommandEvent &event)
void onClose (wxCommandEvent &event)
void onGenerateProcessor (wxCommandEvent &event)
void doSaveIDF ()
void checkImplementationFiles ()
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
wxSizer * functionUnitPage (wxWindow *parent, bool call_fit, bool set_sizer=true)
wxSizer * registerFilePage (wxWindow *parent, bool call_fit, bool set_sizer=true)
wxSizer * immediateUnitPage (wxWindow *parent, bool call_fit, bool set_sizer=true)
wxSizer * decompressionPage (wxWindow *parent, bool call_fit, bool set_sizer=true)
wxSizer * icDecoderPluginPage (wxWindow *parent, bool call_fit, bool set_sizer=true)
Private Attributes
TTAMachine::Machine & machine_
Machine that is being generated.
IDF::MachineImplementation & impl_
MachineImplementation object containing the implementation information.
wxListCtrl * fuList_
Pointer to the FU implementation list widget.
wxListCtrl * iuList_
Pointer to the IU implementation list widget.
wxListCtrl * rfList_
Pointer to the RF implementation list widget.
wxListCtrl * parameterList_
Pointer to the ic decoder parameter list widget.
PluginTools pluginTool_
Plugintool for loading IC/Decoder plugins.
ProGe::ICDecoderGeneratorPlugin * plugin_
IC/Decoder plugin of the current machine implementation.
bool dirtyData_
Detailed Description
Processor implementation window.
Definition at line 55 of file ProcessorImplementationWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_LOAD_IDF
ID_SAVE_IDF
ID_GENERATE_PROCESSOR
ID_FU_LIST
ID_IU_LIST
ID_RF_LIST
ID_AUTO_SELECT_IMPL
ID_SELECT_FU_IMPL
ID_SELECT_IU_IMPL
ID_SELECT_RF_IMPL
ID_BROWSE_DECOMPRESSOR
ID_BROWSE_IC_DEC_PLUGIN
ID_BROWSE_IC_DEC_HDB
ID_DECOMPRESSOR_PATH
ID_IC_DEC_PLUGIN_FILE
ID_IC_DEC_PLUGIN_NAME
ID_IC_DEC_PLUGIN_DESC
ID_IC_DEC_HDB_FILE
ID_PARAMETER_LIST
ID_PARAMETER_VALUE
ID_SET_VALUE
ID_NOTEBOOK
ID_GENERATE
ID_CLOSE
ID_TEXT
ID_LINE
Definition at line 137 of file ProcessorImplementationWindow.hh.
         {
        ID_LOAD_IDF,
        ID_SAVE_IDF,
        ID_GENERATE_PROCESSOR,
        ID_FU_LIST,
        ID_IU_LIST,
        ID_RF_LIST,
        ID_AUTO_SELECT_IMPL,
        ID_SELECT_FU_IMPL,
        ID_SELECT_IU_IMPL,
        ID_SELECT_RF_IMPL,
        ID_BROWSE_DECOMPRESSOR,
        ID_BROWSE_IC_DEC_PLUGIN,
        ID_BROWSE_IC_DEC_HDB,
        ID_DECOMPRESSOR_PATH,
        ID_IC_DEC_PLUGIN_FILE,
        ID_IC_DEC_PLUGIN_NAME,
        ID_IC_DEC_PLUGIN_DESC,
        ID_IC_DEC_HDB_FILE,
        ID_PARAMETER_LIST,
        ID_PARAMETER_VALUE,
        ID_SET_VALUE,
        ID_NOTEBOOK,
        ID_GENERATE,
        ID_CLOSE,
        ID_TEXT,
        ID_LINE
    };
Constructor & Destructor Documentation
ProcessorImplementationWindow()
ProcessorImplementationWindow::ProcessorImplementationWindow (wxWindow * parent, TTAMachine::Machine & machine, IDF::MachineImplementation & impl)
Constructor.
Parameters
parent Parent window of the page.
machine Processor architecture.
impl Processor implementation definition.
Definition at line 123 of file ProcessorImplementationWindow.cc.
                                   :
    wxDialog(parent, -1, _T("Processor Implementation"),
             wxDefaultPosition, wxDefaultSize,
             wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    machine_(machine), impl_(impl), plugin_(NULL), dirtyData_(false) {
    createContents(this, true, true);
    SetMinSize(wxSize(600, 500));
    // Plugin name is always fixed, thus disable editing
    dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_PLUGIN_NAME))->
       Enable(false);
    fuList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_FU_LIST));
    rfList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_RF_LIST));
    iuList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_IU_LIST));
    parameterList_ = dynamic_cast<wxListCtrl*>(FindWindow(ID_PARAMETER_LIST));
    // Add FU and RF list columns.
    fuList_->InsertColumn(0, _T("FU"), wxLIST_FORMAT_LEFT, 150);
    fuList_->InsertColumn(1, _T("ID"), wxLIST_FORMAT_LEFT, 40);
    fuList_->InsertColumn(2, _T("HDB"), wxLIST_FORMAT_LEFT, 400);
    rfList_->InsertColumn(0, _T("RF"), wxLIST_FORMAT_LEFT, 150);
    rfList_->InsertColumn(1, _T("ID"), wxLIST_FORMAT_LEFT, 40);
    rfList_->InsertColumn(2, _T("HDB"), wxLIST_FORMAT_LEFT, 400);
    iuList_->InsertColumn(0, _T("IU"), wxLIST_FORMAT_LEFT, 150);
    iuList_->InsertColumn(1, _T("ID"), wxLIST_FORMAT_LEFT, 40);
    iuList_->InsertColumn(2, _T("HDB"), wxLIST_FORMAT_LEFT, 400);
    parameterList_->InsertColumn(0, _T("Name"), wxLIST_FORMAT_LEFT, 150);
    parameterList_->InsertColumn(1, _T("Value"), wxLIST_FORMAT_LEFT, 100);
    parameterList_->InsertColumn(
        2, _T("Description"), wxLIST_FORMAT_LEFT, 300);
    // Disable conditional buttons by default.
    FindWindow(ID_SELECT_RF_IMPL)->Disable();
    FindWindow(ID_SELECT_IU_IMPL)->Disable();
    FindWindow(ID_SELECT_FU_IMPL)->Disable();
    FindWindow(ID_SET_VALUE)->Disable();
    // Load default plugin
    std::string pluginFile = Environment::defaultICDecoderPlugin();
    std::string pluginName = FileSystem::fileNameBody(pluginFile);
    assert(pluginName.length() > 6);
    pluginName = pluginName.substr(0, pluginName.length() - 6);
    loadICDecoderPlugin(pluginName, pluginFile);
}
References assert, Environment::defaultICDecoderPlugin(), and FileSystem::fileNameBody().
~ProcessorImplementationWindow()
ProcessorImplementationWindow::~ProcessorImplementationWindow () virtual
Destructor.
Definition at line 181 of file ProcessorImplementationWindow.cc.
{
}
Member Function Documentation
checkImplementationFiles()
void ProcessorImplementationWindow::checkImplementationFiles () private
Checks if every file path defined in IDF is correct.
If one or more file paths are invalid, warning dialog is shown to user.
Definition at line 993 of file ProcessorImplementationWindow.cc.
{
    size_t missingFileCount;
    size_t alternativesCount;
    // check implementation files, and try to fix paths for unresolved files
    if (impl_.checkImplFiles(missingFileCount, alternativesCount)) {
        // if all the files were located, exit method
        return;
    }
    // every file was not found, get missing files and possible alternatives
    wxString missFileCountStr = WxConversion::toWxString(
        static_cast<int>(missingFileCount));
    wxString altFileCountStr = WxConversion::toWxString(
        static_cast<int>(alternativesCount));
    // form message for the dialog
    wxString message = missFileCountStr;
    message.Append(_T(" file(s) defined in IDF couldn't be located from"));
    message.Append(_T(" absolute paths or under working directory.\n"));
    message.Append(_T("\n"));
    if (alternativesCount > 0) {
        message.Append(altFileCountStr);
        message.Append(_T(" of them were replaced with file(s) found under"));
        message.Append(_T(" the default search paths."));
    } else {
        message.Append(_T("Any alternative file paths couldn't be"));
        message.Append(_T(" located for the missing files."));
    }
    WarningDialog warningDialog(this, message);
    warningDialog.ShowModal();
}
References IDF::MachineImplementation::checkImplFiles(), impl_, and WxConversion::toWxString().
Referenced by onLoadIDF().
createContents()
wxSizer * ProcessorImplementationWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog widgets.
Code geenrated by wxDesigner. Do not modify manually.
Parameters
parent Parent window of the created widget hierarchy.
call_fit Fit parent window size.
set_sizer Set the created top level sizer as the parent win contents.
Definition at line 1039 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxNotebook *item2 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxDefaultSize, 0 );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item1 = new wxNotebookSizer( item2 );
#else
    wxWindow *item1 = item2;
#endif
    wxPanel *item3 = new wxPanel( item2, -1 );
    ProcessorImplementationWindow::registerFilePage( item3, FALSE );
    item2->AddPage( item3, wxT("Register Files") );
    wxPanel *item4 = new wxPanel( item2, -1 );
    ProcessorImplementationWindow::immediateUnitPage( item4, FALSE );
    item2->AddPage( item4, wxT("Immediate Units") );
    wxPanel *item5 = new wxPanel( item2, -1 );
    ProcessorImplementationWindow::functionUnitPage( item5, FALSE );
    item2->AddPage( item5, wxT("Function Units") );
    wxPanel *item6 = new wxPanel( item2, -1 );
    ProcessorImplementationWindow::decompressionPage( item6, FALSE );
    item2->AddPage( item6, wxT("Instruction Compression") );
    wxPanel *item7 = new wxPanel( item2, -1 );
    ProcessorImplementationWindow::icDecoderPluginPage( item7, FALSE );
    item2->AddPage( item7, wxT("IC / Decoder Plugin") );
    item0->Add( item1, 0, wxFIXED_MINSIZE|wxGROW|wxALL, 5 );
    wxStaticLine *item8 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(200,-1), wxLI_HORIZONTAL );
    item0->Add( item8, 0, wxFIXED_MINSIZE|wxGROW|wxALL, 5 );
    wxGridSizer *item9 = new wxGridSizer( 2, 0, 0 );
    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item11 = new wxButton( parent, ID_LOAD_IDF, wxT("Load IDF..."), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxFIXED_MINSIZE|wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxButton *item12 = new wxButton( parent, ID_SAVE_IDF, wxT("Save IDF..."), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxFIXED_MINSIZE|wxALIGN_CENTER|wxALL, 5 );
    wxButton *item13 = new wxButton( parent, ID_GENERATE, wxT("Generate Processor"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxFIXED_MINSIZE|wxALIGN_CENTER|wxALL, 5 );
    item9->Add( item10, 0, wxFIXED_MINSIZE|wxALIGN_CENTER_VERTICAL, 5 );
    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item15 = new wxButton( parent, ID_CLOSE, wxT("Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxFIXED_MINSIZE|wxALIGN_CENTER|wxALL, 5 );
    item9->Add( item14, 0, wxFIXED_MINSIZE|wxALIGN_CENTER_VERTICAL, 5 );
    item0->Add( item9, 0, wxFIXED_MINSIZE|wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References decompressionPage(), FALSE, functionUnitPage(), icDecoderPluginPage(), ID_CLOSE, ID_GENERATE, ID_LINE, ID_LOAD_IDF, ID_NOTEBOOK, ID_SAVE_IDF, immediateUnitPage(), and registerFilePage().
decompressionPage()
wxSizer * ProcessorImplementationWindow::decompressionPage (wxWindow * parent, bool call_fit, bool set_sizer = true) private
Definition at line 1167 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticBox *item2 = new wxStaticBox( parent, -1, wxT("Instruction Decompressor:") );
    wxStaticBoxSizer *item1 = new wxStaticBoxSizer( item2, wxVERTICAL );
    wxFlexGridSizer *item3 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item4 = new wxStaticText( parent, ID_TEXT, wxT("Decompressor block file:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item4, 0, wxALL, 5 );
    item3->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_DECOMPRESSOR_PATH, wxT(""), wxDefaultPosition, wxSize(250,-1), wxTE_READONLY );
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item6 = new wxButton( parent, ID_BROWSE_DECOMPRESSOR, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item3, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BROWSE_DECOMPRESSOR, ID_DECOMPRESSOR_PATH, and ID_TEXT.
Referenced by createContents().
doSaveIDF()
void ProcessorImplementationWindow::doSaveIDF () private
Definition at line 719 of file ProcessorImplementationWindow.cc.
{
    wxString message = _T("Save implementation.");
    wxString defaultDir = _T(".");
    wxDocument* doc = wxGetApp().docManager()->GetCurrentDocument();
    wxString defaultFile;
    if (doc != NULL) {
        defaultFile = doc->GetFilename();
        defaultFile.erase(defaultFile.rfind('.'));
        defaultFile += _T(".idf");
        // set default save location to same where the .adf file is
        string absolutePathToADF = FileSystem::absolutePathOf(
            WxConversion::toString(defaultFile));
        defaultDir = WxConversion::toWxString(
            FileSystem::directoryOfPath(absolutePathToADF));
        defaultFile = WxConversion::toWxString(
            FileSystem::fileOfPath(WxConversion::toString(defaultFile)));
    } else {
        defaultFile = _T(".idf");
    }
    wxString fileTypes = _T("Implementation Definition File (.idf)|*.idf");
    wxFileDialog dialog(
        this, message, defaultDir, defaultFile, fileTypes,
        wxSAVE | wxOVERWRITE_PROMPT);
    if (dialog.ShowModal() == wxID_OK) {
        string path = WxConversion::toString(dialog.GetPath());
        try {
            // Make local and default file paths relative.
            std::vector<string> searchPaths;
            searchPaths.push_back(FileSystem::currentWorkingDir());
            std::vector<string> hdbSearchPaths = Environment::hdbPaths();
            impl_.makeImplFilesRelative(searchPaths);
            IDFSerializer serializer;
            serializer.setDestinationFile(path);
            serializer.writeMachineImplementation(impl_);
            setDirty(false);
        } catch (Exception& e) {
            wxString message = _T("Error writing '");
            message.Append(WxConversion::toWxString(path));
            message.Append(_T("':"));
            message.Append(WxConversion::toWxString(e.errorMessage()));
            ErrorDialog dialog(this, message);
            dialog.ShowModal();
        }
    }
}
References FileSystem::absolutePathOf(), FileSystem::currentWorkingDir(), FileSystem::directoryOfPath(), Exception::errorMessage(), FileSystem::fileOfPath(), Environment::hdbPaths(), impl_, IDF::MachineImplementation::makeImplFilesRelative(), XMLSerializer::setDestinationFile(), setDirty(), WxConversion::toString(), WxConversion::toWxString(), and IDF::IDFSerializer::writeMachineImplementation().
Referenced by onClose(), and onSaveIDF().
functionUnitPage()
wxSizer * ProcessorImplementationWindow::functionUnitPage (wxWindow * parent, bool call_fit, bool set_sizer = true) private
Definition at line 1139 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_FU_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *buttonSizer = new wxBoxSizer( wxHORIZONTAL );
    wxButton *autoSelButton = new wxButton( parent, ID_AUTO_SELECT_IMPL, wxT("Auto Select Implementations"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( autoSelButton, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxButton *item2 = new wxButton( parent, ID_SELECT_FU_IMPL, wxT("Select implementation..."), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    item0->Add( buttonSizer, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_AUTO_SELECT_IMPL, ID_FU_LIST, and ID_SELECT_FU_IMPL.
Referenced by createContents().
handleSelectFUImplementation()
void ProcessorImplementationWindow::handleSelectFUImplementation (long item) private
Handle calling of the implementation selection dialog and it's return value
Definition at line 508 of file ProcessorImplementationWindow.cc.
{
    const FunctionUnit& fu = *machine_.functionUnitNavigator().item(item);
    if (impl_.hasFUImplementation(fu.name())) {
        BlockImplementationDialog dialog(
            this, fu, impl_.fuImplementation(fu.name()));
        if (dialog.ShowModal() == wxID_OK) {
            setDirty();
            updateFUList(fu.name(), item);
        }
    } else {
        UnitImplementationLocation* location =
            new FUImplementationLocation("", -1, fu.name());
        BlockImplementationDialog dialog(this, fu, *location);
        if (dialog.ShowModal() == wxID_OK) {
            impl_.addFUImplementation(location);
            setDirty();
            updateFUList(fu.name(), item);
        } else {
            delete location;
        }
    }
}
References IDF::MachineImplementation::addFUImplementation(), IDF::MachineImplementation::fuImplementation(), TTAMachine::Machine::functionUnitNavigator(), IDF::MachineImplementation::hasFUImplementation(), impl_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), setDirty(), and updateFUList().
Referenced by onFUActivation(), and onSelectFUImplementation().
handleSelectIUImplementation()
void ProcessorImplementationWindow::handleSelectIUImplementation (long item) private
Definition at line 434 of file ProcessorImplementationWindow.cc.
{
    const ImmediateUnit& iu = *machine_.immediateUnitNavigator().item(item);
    if (impl_.hasIUImplementation(iu.name())) {
        BlockImplementationDialog dialog(
            this, iu, impl_.iuImplementation(iu.name()));
        if (dialog.ShowModal() == wxID_OK) {
            setDirty();
        }
    } else {
        UnitImplementationLocation* location =
            new RFImplementationLocation("", -1, iu.name());
        BlockImplementationDialog dialog(this, iu, *location);
        if (dialog.ShowModal() == wxID_OK) {
            impl_.addIUImplementation(location);
            setDirty();
        } else {
            delete location;
        }
    }
    TransferDataToWindow();
}
References IDF::MachineImplementation::addIUImplementation(), IDF::MachineImplementation::hasIUImplementation(), TTAMachine::Machine::immediateUnitNavigator(), impl_, TTAMachine::Machine::Navigator< ComponentType >::item(), IDF::MachineImplementation::iuImplementation(), machine_, TTAMachine::Component::name(), setDirty(), and TransferDataToWindow().
Referenced by onIUActivation(), and onSelectIUImplementation().
handleSelectRFImplementation()
void ProcessorImplementationWindow::handleSelectRFImplementation (long item) private
Call the dialog to select RF implementation and handle the return values of the dialog.
Definition at line 381 of file ProcessorImplementationWindow.cc.
{
    const RegisterFile& rf = *machine_.registerFileNavigator().item(item);
    if (impl_.hasRFImplementation(rf.name())) {
        BlockImplementationDialog dialog(
            this, rf, impl_.rfImplementation(rf.name()));
        if (dialog.ShowModal() == wxID_OK) {
            setDirty();
            updateRFList(rf.name(), item);
        }
    } else {
        UnitImplementationLocation* location =
            new RFImplementationLocation("", -1, rf.name());
        BlockImplementationDialog dialog(this, rf, *location);
        if (dialog.ShowModal() == wxID_OK) {
            impl_.addRFImplementation(location);
            setDirty();
            updateRFList(rf.name(), item);
        } else {
            delete location;
        }
    }
}
References IDF::MachineImplementation::addRFImplementation(), IDF::MachineImplementation::hasRFImplementation(), impl_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, TTAMachine::Component::name(), TTAMachine::Machine::registerFileNavigator(), IDF::MachineImplementation::rfImplementation(), setDirty(), and updateRFList().
Referenced by onRFActivation(), and onSelectRFImplementation().
icDecoderPluginPage()
wxSizer * ProcessorImplementationWindow::icDecoderPluginPage (wxWindow * parent, bool call_fit, bool set_sizer = true) private
Definition at line 1206 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxFlexGridSizer *item1 = new wxFlexGridSizer( 1, 0, 0 );
    item1->AddGrowableCol( 0 );
    item1->AddGrowableRow( 1 );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 3, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Plugin file:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_IC_DEC_PLUGIN_FILE, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item2->Add( item4, 0, wxGROW|wxALL, 5 );
    wxButton *item5 = new wxButton( parent, ID_BROWSE_IC_DEC_PLUGIN, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("HDB file:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item6, 0, wxALL, 5 );
    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_IC_DEC_HDB_FILE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item7, 0, wxGROW|wxALL, 5 );
    wxButton *item8 = new wxButton( parent, ID_BROWSE_IC_DEC_HDB, wxT("Browse..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("Plugin name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item9, 0, wxALL, 5 );
    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_IC_DEC_PLUGIN_NAME, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item2->Add( item10, 0, wxGROW|wxALL, 5 );
    item2->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, wxT("Description:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item11, 0, wxALL, 5 );
    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_IC_DEC_PLUGIN_DESC, wxT(""), wxDefaultPosition, wxSize(320,80), wxTE_MULTILINE|wxTE_READONLY );
    item2->Add( item12, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxFIXED_MINSIZE|wxGROW|wxALL, 5 );
    wxFlexGridSizer *item13 = new wxFlexGridSizer( 1, 0, 0 );
    item13->AddGrowableCol( 0 );
    item13->AddGrowableRow( 1 );
    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("Plugin parameters:"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALL, 5 );
    wxListCtrl *item15 = new wxListCtrl( parent, ID_PARAMETER_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item13->Add( item15, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );
    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT, wxT("New value:"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    wxTextCtrl *item18 = new wxTextCtrl( parent, ID_PARAMETER_VALUE, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item19 = new wxButton( parent, ID_SET_VALUE, wxT("Set"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );
    item13->Add( item16, 0, wxALIGN_CENTER, 5 );
    item1->Add( item13, 0, wxFIXED_MINSIZE|wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BROWSE_IC_DEC_HDB, ID_BROWSE_IC_DEC_PLUGIN, ID_IC_DEC_HDB_FILE, ID_IC_DEC_PLUGIN_DESC, ID_IC_DEC_PLUGIN_FILE, ID_IC_DEC_PLUGIN_NAME, ID_PARAMETER_LIST, ID_PARAMETER_VALUE, ID_SET_VALUE, and ID_TEXT.
Referenced by createContents().
immediateUnitPage()
wxSizer * ProcessorImplementationWindow::immediateUnitPage (wxWindow * parent, bool call_fit, bool set_sizer = true) private
Definition at line 1289 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_IU_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *buttonSizer = new wxBoxSizer( wxHORIZONTAL );
    wxButton *autoSelButton = new wxButton( parent, ID_AUTO_SELECT_IMPL, wxT("Auto Select Implementations"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( autoSelButton, 0, wxALL, 5 );
    wxButton *item2 = new wxButton( parent, ID_SELECT_IU_IMPL, wxT("Select implementation..."), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( item2, 0, wxALL, 5 );
    item0->Add( buttonSizer, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_AUTO_SELECT_IMPL, ID_IU_LIST, and ID_SELECT_IU_IMPL.
Referenced by createContents().
loadICDecoderPlugin()
void ProcessorImplementationWindow::loadICDecoderPlugin (const std::string & pluginName, const std::string & pluginFile) private
Loads an IC/Decoder plugin.
Parameters
pluginName Name of the plugin.
pluginFile Full path to the plugin file.
Definition at line 893 of file ProcessorImplementationWindow.cc.
{
    if (plugin_ != NULL) {
        delete plugin_;
        plugin_ = NULL;
    }
    // initialize the plugin tool
    vector<string> pluginPaths = Environment::icDecoderPluginPaths();
    for (vector<string>::const_iterator iter = pluginPaths.begin();
         iter != pluginPaths.end(); iter++) {
        try {
            pluginTool_.addSearchPath(*iter);
        } catch (const FileNotFound&) {
        }
    }
    try {
        pluginTool_.registerModule(pluginFile);
    } catch (const FileNotFound&) {
        wxString message = _T("Plugin file '");
        message.Append(WxConversion::toWxString(pluginFile));
        message.Append(_T("' doesn't exist"));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    } catch (Exception& e) {
        wxString message = _T("Error loading plugin file '");
        message.Append(WxConversion::toWxString(pluginFile));
        message.Append(_T("':\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    ICDecoderGeneratorPlugin* (*creator)(
        TTAMachine::Machine&, BinaryEncoding&);
    try {
        pluginTool_.importSymbol(
            "create_generator_plugin_" + pluginName, creator, pluginFile);
        BEMGenerator generator(machine_);
        BinaryEncoding* bem = generator.generate();
        plugin_ = creator(machine_, *bem);
        delete bem;
    } catch (Exception& e) {
        wxString message = _T("Error loading plugin '");
        message.Append(WxConversion::toWxString(pluginName));
        message.Append(_T("' from '"));
        message.Append(WxConversion::toWxString(pluginFile));
        message.Append(_T("':\n"));
        message.Append(WxConversion::toWxString(e.errorMessage()));
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    try {
        impl_.setICDecoderPluginFile(pluginFile);
    } catch (FileNotFound& e) {
    }
    impl_.setICDecoderPluginName(pluginName);
    assert(plugin_ != NULL);
    return;
}
References PluginTools::addSearchPath(), assert, Exception::errorMessage(), BEMGenerator::generate(), Environment::icDecoderPluginPaths(), impl_, PluginTools::importSymbol(), machine_, plugin_, pluginTool_, PluginTools::registerModule(), IDF::MachineImplementation::setICDecoderPluginFile(), IDF::MachineImplementation::setICDecoderPluginName(), and WxConversion::toWxString().
Referenced by onBrowseICDecPlugin(), and onLoadIDF().
onAutoSelectImplementations()
void ProcessorImplementationWindow::onAutoSelectImplementations (wxCommandEvent & event) private
Event handler for the automatic implementation selection button.
Definition at line 288 of file ProcessorImplementationWindow.cc.
{
    AutoSelectImplementationsDialog dialog(this, machine_, impl_);
    dialog.ShowModal();
    updateImplementationLists();
}
References impl_, machine_, and updateImplementationLists().
onBrowseDecompressor()
void ProcessorImplementationWindow::onBrowseDecompressor (wxCommandEvent & event) private
Event handler for the decompressor block Browse... button.
Definition at line 785 of file ProcessorImplementationWindow.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a file"), _T(""), _T(""),
        _T("Decompressor block files (*.vhdl;*.vhd)|*.vhdl;*.vhd|"
           "All files|*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    if (dialog.ShowModal() == wxID_OK) {
        setDirty(true);
        string decompressorFile =
            WxConversion::toString(dialog.GetPath());
        impl_.setDecompressorFile(decompressorFile);
    }
    TransferDataToWindow();
}
References impl_, IDF::MachineImplementation::setDecompressorFile(), setDirty(), WxConversion::toString(), and TransferDataToWindow().
onBrowseICDecPlugin()
void ProcessorImplementationWindow::onBrowseICDecPlugin (wxCommandEvent & event) private
Event handler for the ic/decoder plugin Browse... button.
Definition at line 808 of file ProcessorImplementationWindow.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a file"), _T(""), _T(""),
        _T("IC/Decoder plugins (*.so)|*.so|All files|*.*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    if (dialog.ShowModal() == wxID_OK) {
        setDirty(true);
        string pluginFile =
            WxConversion::toString(dialog.GetPath());
        // An ugly way to determine the plugin name which should be the
        // file name minus the "Plugin.so" ending.
        string pluginName = FileSystem::fileOfPath(pluginFile);
        pluginName = FileSystem::fileNameBody(pluginFile);
        if (pluginName.length() < 6 ||
            pluginName.substr(pluginName.length() - 6) != "Plugin") {
            wxString message = _T("Unable to determine plugin name.\n");
            message.Append(_T("Plugin file must be named "));
            message.Append(_T("'<plugin name>Plugin.so'"));
            ErrorDialog dialog(this, message);
            dialog.ShowModal();
            return;
        }
        pluginName = pluginName.substr(0, pluginName.length() - 6);
        loadICDecoderPlugin(pluginName, pluginFile);
        impl_.clearICDecoderParameters();
    }
    TransferDataToWindow();
}
References IDF::MachineImplementation::clearICDecoderParameters(), FileSystem::fileNameBody(), FileSystem::fileOfPath(), impl_, loadICDecoderPlugin(), setDirty(), WxConversion::toString(), and TransferDataToWindow().
onBrowseICHDB()
void ProcessorImplementationWindow::onBrowseICHDB (wxCommandEvent & event) private
Event handler for the ic/ hdb Browse... button.
Definition at line 847 of file ProcessorImplementationWindow.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a file"), _T(""), _T(""),
        _T("HDB Files (*.hdb)|*.hdb|All files|*.*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    if (dialog.ShowModal() == wxID_OK) {
        setDirty(true);
        string hdbFile = WxConversion::toString(dialog.GetPath());
        impl_.setICDecoderHDB(hdbFile);
    }
    TransferDataToWindow();
}
References impl_, setDirty(), IDF::MachineImplementation::setICDecoderHDB(), WxConversion::toString(), and TransferDataToWindow().
onClose()
void ProcessorImplementationWindow::onClose (wxCommandEvent & event) private
Event handler for the Close button.
Definition at line 697 of file ProcessorImplementationWindow.cc.
{
    if (dirtyData_) {
        wxString message = _T("Save before exit?\n");
        wxMessageDialog dialog(this, message, message, wxYES|wxCANCEL|wxNO);
        int rv = dialog.ShowModal();
        switch(rv) {
        case wxID_NO:
            break;
        case wxID_YES:
            doSaveIDF();
            return;
        case wxID_CANCEL:
        default:
            return;
        }
    }
    Close();
}
References dirtyData_, and doSaveIDF().
onFUActivation()
void ProcessorImplementationWindow::onFUActivation (wxListEvent & e) private
Event handler for the FU Select implementation doubleclick.
Definition at line 557 of file ProcessorImplementationWindow.cc.
{
    handleSelectFUImplementation(e.GetIndex());
}
References handleSelectFUImplementation().
onFUSelection()
void ProcessorImplementationWindow::onFUSelection (wxListEvent & event) private
Event handler for the FU list selection changes.
Enables and disables the select FU implementation button.
Definition at line 595 of file ProcessorImplementationWindow.cc.
{
    if (fuList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_SELECT_FU_IMPL)->Enable();
    } else {
        FindWindow(ID_SELECT_FU_IMPL)->Disable();
    }
}
References fuList_, and ID_SELECT_FU_IMPL.
onGenerateProcessor()
void ProcessorImplementationWindow::onGenerateProcessor (wxCommandEvent & event) private
Event handler for the Generate Processor... button.
Definition at line 967 of file ProcessorImplementationWindow.cc.
{
    IDFValidator validator(impl_, machine_);
    if (!validator.validate()) {
        wxString message;
        for (int i = 0; i < validator.errorCount(); i++) {
            message.Append(
                WxConversion::toWxString(validator.errorMessage(i)));
            message.Append(_T("\n"));
        }
        ErrorDialog dialog(this, message);
        dialog.ShowModal();
        return;
    }
    GenerateProcessorDialog dialog(this, machine_, impl_);
    dialog.ShowModal();
}
References IDFValidator::errorCount(), IDFValidator::errorMessage(), impl_, machine_, WxConversion::toWxString(), and IDFValidator::validate().
onIUActivation()
void ProcessorImplementationWindow::onIUActivation (wxListEvent & e) private
Event handler for the IU Select implementation doubleclick.
Definition at line 481 of file ProcessorImplementationWindow.cc.
{
    handleSelectIUImplementation(e.GetIndex());
}
References handleSelectIUImplementation().
onIUSelection()
void ProcessorImplementationWindow::onIUSelection (wxListEvent & event) private
Event handler for the IU list selection changes.
Enables and disables the select IU implementation button.
Definition at line 581 of file ProcessorImplementationWindow.cc.
{
    if (iuList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_SELECT_IU_IMPL)->Enable();
    } else {
        FindWindow(ID_SELECT_IU_IMPL)->Disable();
    }
}
References ID_SELECT_IU_IMPL, and iuList_.
onLoadIDF()
void ProcessorImplementationWindow::onLoadIDF (wxCommandEvent & event) private
Event handler for the Load IDF... button.
Definition at line 621 of file ProcessorImplementationWindow.cc.
{
    wxFileDialog dialog(
        this, _T("Choose a file"), _T(""), _T(""),
        _T("Implemenation Definition Files files (*.idf)|*.idf|All files|*"),
        (wxOPEN | wxFILE_MUST_EXIST));
    if (dialog.ShowModal() == wxID_OK) {
        ObjectState* old =impl_.saveState();
        string idfFile =
            WxConversion::toString(dialog.GetPath());
        IDFSerializer serializer;
        serializer.setSourceFile(idfFile);
        try {
            ObjectState* newIDF = serializer.readState();
            impl_.loadState(newIDF);
            delete newIDF;
        } catch (Exception& e) {
            impl_.loadState(old);
            wxString message = _T("Error reading idf '");
            message.Append(WxConversion::toWxString(idfFile));
            message.Append(_T("':\n"));
            message.Append(WxConversion::toWxString(e.errorMessage()));
            ErrorDialog errorDialog(this, message);
            errorDialog.ShowModal();
            return;
        }
        IDFValidator validator(impl_, machine_);
        if (!validator.validate()) {
            wxString message = _T("Warning:\n");
            for (int i = 0; i < validator.errorCount(); i++) {
                message.Append(
                    WxConversion::toWxString(validator.errorMessage(i)));
                message.Append(_T("\n"));
            }
            WarningDialog warningDialog(this, message);
            warningDialog.ShowModal();
            // Remove implementations of units that doesn't exist in the
            // architecture.
            IDFValidator::removeUnknownImplementations(impl_, machine_);
        }
        // check and possibly correct file paths defined in IDF
        checkImplementationFiles();
        try {
            if (impl_.hasICDecoderPluginName() &&
                impl_.hasICDecoderPluginFile()) {
                loadICDecoderPlugin(
                    impl_.icDecoderPluginName(),
                    impl_.icDecoderPluginFile());
            }
        } catch (Exception& e) {
            wxString msg = _T("Warning: could not load IC decoder plugin!");
            WarningDialog warningDialog(this, msg);
            warningDialog.ShowModal();
        }
        TransferDataToWindow();
        delete old;
    }
}
References checkImplementationFiles(), IDFValidator::errorCount(), Exception::errorMessage(), IDFValidator::errorMessage(), IDF::MachineImplementation::hasICDecoderPluginFile(), IDF::MachineImplementation::hasICDecoderPluginName(), IDF::MachineImplementation::icDecoderPluginFile(), IDF::MachineImplementation::icDecoderPluginName(), impl_, loadICDecoderPlugin(), IDF::MachineImplementation::loadState(), machine_, IDF::IDFSerializer::readState(), IDFValidator::removeUnknownImplementations(), IDF::MachineImplementation::saveState(), XMLSerializer::setSourceFile(), WxConversion::toString(), WxConversion::toWxString(), TransferDataToWindow(), and IDFValidator::validate().
onParameterSelection()
void ProcessorImplementationWindow::onParameterSelection (wxListEvent & event) private
Event handler for the ic/decoder parameter list selection changes.
Enables and disables the set parameter value button.
Definition at line 609 of file ProcessorImplementationWindow.cc.
{
    if (parameterList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_SET_VALUE)->Enable();
    } else {
        FindWindow(ID_SET_VALUE)->Disable();
    }
}
References ID_SET_VALUE, and parameterList_.
onRFActivation()
void ProcessorImplementationWindow::onRFActivation (wxListEvent & e) private
Event handler for the RF Select implementation button.
Definition at line 429 of file ProcessorImplementationWindow.cc.
{
    handleSelectRFImplementation(e.GetIndex());
}
References handleSelectRFImplementation().
onRFSelection()
void ProcessorImplementationWindow::onRFSelection (wxListEvent & event) private
Event handler for the RF list selection changes.
Enables and disables the select RF implementation button.
Definition at line 567 of file ProcessorImplementationWindow.cc.
{
    if (rfList_->GetSelectedItemCount() == 1) {
        FindWindow(ID_SELECT_RF_IMPL)->Enable();
    } else {
        FindWindow(ID_SELECT_RF_IMPL)->Disable();
    }
}
References ID_SELECT_RF_IMPL, and rfList_.
onSaveIDF()
void ProcessorImplementationWindow::onSaveIDF (wxCommandEvent & event) private
Event handler for the Save IDF button.
Definition at line 777 of file ProcessorImplementationWindow.cc.
{
    doSaveIDF();
}
References doSaveIDF().
onSelectFUImplementation()
void ProcessorImplementationWindow::onSelectFUImplementation (wxCommandEvent & event) private
Event handler for the FU Select implementation button.
Definition at line 540 of file ProcessorImplementationWindow.cc.
{
    long item = -1;
    item = fuList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        // No fu selected.
        return;
    }
    handleSelectFUImplementation(item);
}
References fuList_, and handleSelectFUImplementation().
onSelectIUImplementation()
void ProcessorImplementationWindow::onSelectIUImplementation (wxCommandEvent & event) private
Event handler for the IU Select implementation button.
Definition at line 464 of file ProcessorImplementationWindow.cc.
{
    long item = -1;
    item = iuList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        // No iu selected.
        return;
    }
    handleSelectIUImplementation(item);
}
References handleSelectIUImplementation(), and iuList_.
onSelectRFImplementation()
void ProcessorImplementationWindow::onSelectRFImplementation (wxCommandEvent & event) private
Event handler for the RF Select implementation button.
Definition at line 412 of file ProcessorImplementationWindow.cc.
{
    long item = -1;
    item = rfList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        // No rf selected.
        return;
    }
    handleSelectRFImplementation(item);
}
References handleSelectRFImplementation(), and rfList_.
onSetParameterValue()
void ProcessorImplementationWindow::onSetParameterValue (wxCommandEvent & event) private
Event handler for the ic/decoder parameter value setting button.
Definition at line 868 of file ProcessorImplementationWindow.cc.
{
    long item = -1;
    item = parameterList_->GetNextItem(
        item, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item < 0) return;
    wxTextCtrl* valueCtrl = dynamic_cast<wxTextCtrl*>(
        FindWindow(ID_PARAMETER_VALUE));
    std::string name = plugin_->recognizedParameter(item);
    std::string value = WxConversion::toString(valueCtrl->GetValue());
    impl_.setICDecoderParameter(name, value);
    TransferDataToWindow();
}
References ID_PARAMETER_VALUE, impl_, parameterList_, plugin_, ProGe::ICDecoderGeneratorPlugin::recognizedParameter(), IDF::MachineImplementation::setICDecoderParameter(), WxConversion::toString(), and TransferDataToWindow().
registerFilePage()
wxSizer * ProcessorImplementationWindow::registerFilePage (wxWindow * parent, bool call_fit, bool set_sizer = true) private
Definition at line 1111 of file ProcessorImplementationWindow.cc.
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 1, 0, 0 );
    item0->AddGrowableCol( 0 );
    item0->AddGrowableRow( 0 );
    wxListCtrl *item1 = new wxListCtrl( parent, ID_RF_LIST, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER );
    item0->Add( item1, 0, wxGROW|wxALL, 5 );
    wxBoxSizer *buttonSizer = new wxBoxSizer( wxHORIZONTAL );
    wxButton *autoSelButton = new wxButton( parent, ID_AUTO_SELECT_IMPL, wxT("Auto Select Implementations"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( autoSelButton, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    wxButton *item2 = new wxButton( parent, ID_SELECT_RF_IMPL, wxT("Select implementation..."), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    item0->Add( buttonSizer, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_AUTO_SELECT_IMPL, ID_RF_LIST, and ID_SELECT_RF_IMPL.
Referenced by createContents().
setDirty()
void ProcessorImplementationWindow::setDirty (bool dirty = true) inline
Definition at line 63 of file ProcessorImplementationWindow.hh.
{ dirtyData_ = dirty; }
References dirtyData_.
Referenced by doSaveIDF(), handleSelectFUImplementation(), handleSelectIUImplementation(), handleSelectRFImplementation(), onBrowseDecompressor(), onBrowseICDecPlugin(), and onBrowseICHDB().
TransferDataToWindow()
bool ProcessorImplementationWindow::TransferDataToWindow () private virtual
Transfers data from the current MachineImplementation object to the dialog widgets.
Definition at line 189 of file ProcessorImplementationWindow.cc.
{
    updateImplementationLists();
    parameterList_->DeleteAllItems();
    if (impl_.hasICDecoderPluginFile()) {
        try {
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_PLUGIN_FILE))->
                SetValue(WxConversion::toWxString(impl_.icDecoderPluginFile()));
        } catch (FileNotFound& e) {
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_PLUGIN_FILE))->
                SetValue(WxConversion::toWxString("File not found"));
        }
    }
    if (impl_.hasICDecoderPluginName()) {
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_PLUGIN_NAME))->
            SetValue(WxConversion::toWxString(impl_.icDecoderPluginName()));
    }
    if (impl_.hasICDecoderHDB()) {
        try {
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_HDB_FILE))->
                SetValue(WxConversion::toWxString(impl_.icDecoderHDB()));
        } catch (FileNotFound& e) {
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_IC_DEC_HDB_FILE))->
                SetValue(WxConversion::toWxString("File not found"));
        }
    }
    wxTextCtrl* descCtrl = dynamic_cast<wxTextCtrl*>(
        FindWindow(ID_IC_DEC_PLUGIN_DESC));
    // Set IC&decoder generator plugin attributes.
    if (plugin_ != NULL) {
        descCtrl->SetValue(
            WxConversion::toWxString(plugin_->pluginDescription()));
        // IC / Decoder plugin parameters.
        for (int i = 0; i < plugin_->recognizedParameterCount(); i++) {
            string paramName = plugin_->recognizedParameter(i);
            string paramValue =
                impl_.icDecoderParameterValue(plugin_->recognizedParameter(i));
            string paramDesc = plugin_->parameterDescription(paramName);
            parameterList_->InsertItem(i, WxConversion::toWxString(paramName));
            parameterList_->SetItem(
                i, 1, WxConversion::toWxString(paramValue));
            parameterList_->SetItem(
                i, 2, WxConversion::toWxString(paramDesc));
        }
        parameterList_->SetColumnWidth(2, wxLIST_AUTOSIZE);
    } else {
        descCtrl->SetValue(_T("\n   No IC / Decoder plugin loaded."));
    }
    if (impl_.hasDecompressorFile()) {
        try {
            dynamic_cast<wxTextCtrl*>(FindWindow(ID_DECOMPRESSOR_PATH))->
                SetValue(WxConversion::toWxString(impl_.decompressorFile()));
        } catch (FileNotFound& e) {
            wxString message =
                _T("Unable to set decompressor block file:\n");
            WarningDialog dialog(this, message);
            dialog.ShowModal();
        }
    }
    return true;
}
References IDF::MachineImplementation::decompressorFile(), IDF::MachineImplementation::hasDecompressorFile(), IDF::MachineImplementation::hasICDecoderHDB(), IDF::MachineImplementation::hasICDecoderPluginFile(), IDF::MachineImplementation::hasICDecoderPluginName(), IDF::MachineImplementation::icDecoderHDB(), IDF::MachineImplementation::icDecoderParameterValue(), IDF::MachineImplementation::icDecoderPluginFile(), IDF::MachineImplementation::icDecoderPluginName(), ID_DECOMPRESSOR_PATH, ID_IC_DEC_HDB_FILE, ID_IC_DEC_PLUGIN_DESC, ID_IC_DEC_PLUGIN_FILE, ID_IC_DEC_PLUGIN_NAME, impl_, ProGe::ICDecoderGeneratorPlugin::parameterDescription(), parameterList_, plugin_, ProGe::ICDecoderGeneratorPlugin::pluginDescription(), ProGe::ICDecoderGeneratorPlugin::recognizedParameter(), ProGe::ICDecoderGeneratorPlugin::recognizedParameterCount(), WxConversion::toWxString(), and updateImplementationLists().
Referenced by handleSelectIUImplementation(), onBrowseDecompressor(), onBrowseICDecPlugin(), onBrowseICHDB(), onLoadIDF(), and onSetParameterValue().
updateFUList()
void ProcessorImplementationWindow::updateFUList (const std::string & fuName, int index) private
Update the list of FU implementations for single FU
Definition at line 488 of file ProcessorImplementationWindow.cc.
{
    const FUImplementationLocation fuImpl =
        impl_.fuImplementation(fuName);
    string hdb;
    int id = 0;
    try {
        hdb = Environment::shortHDBPath(fuImpl.hdbFile());
        id = fuImpl.id();
    } catch (FileNotFound& e) {
        hdb = "Warning: " + e.errorMessage();
    }
    fuList_->SetItem(index, 1, WxConversion::toWxString(id));
    fuList_->SetItem(index, 2, WxConversion::toWxString(hdb));
}
References Exception::errorMessage(), IDF::MachineImplementation::fuImplementation(), fuList_, IDF::UnitImplementationLocation::hdbFile(), IDF::UnitImplementationLocation::id(), impl_, Environment::shortHDBPath(), and WxConversion::toWxString().
Referenced by handleSelectFUImplementation().
updateImplementationLists()
void ProcessorImplementationWindow::updateImplementationLists () private
Updates the list views on RF, IU and FU pages.
Definition at line 298 of file ProcessorImplementationWindow.cc.
{
    fuList_->DeleteAllItems();
    rfList_->DeleteAllItems();
    iuList_->DeleteAllItems();
    // FU implementation list.
    Machine::FunctionUnitNavigator fuNav =
        machine_.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        string fuName = fuNav.item(i)->name();
        fuList_->InsertItem(i, WxConversion::toWxString(fuName));
        if (impl_.hasFUImplementation(fuName)) {
            const FUImplementationLocation fuImpl =
                impl_.fuImplementation(fuName);
            string hdb;
            int id = 0;
            try {
                hdb = Environment::shortHDBPath(fuImpl.hdbFile());
                id = fuImpl.id();
            } catch (FileNotFound& e) {
                hdb = "Warning: " + e.errorMessage();
            }
            fuList_->SetItem(i, 1, WxConversion::toWxString(id));
            fuList_->SetItem(i, 2, WxConversion::toWxString(hdb));
        }
    }
    // RF implementation list.
    const Machine::RegisterFileNavigator rfNav =
        machine_.registerFileNavigator();
    for (int i = 0; i < rfNav.count(); i++) {
        string rfName = rfNav.item(i)->name();
        rfList_->InsertItem(i, WxConversion::toWxString(rfName));
        if (impl_.hasRFImplementation(rfName)) {
            const RFImplementationLocation rfImpl =
                impl_.rfImplementation(rfName);
            string hdb;
            int id = 0;
            try {
                hdb = Environment::shortHDBPath(rfImpl.hdbFile());
                id = rfImpl.id();
            } catch (FileNotFound& e) {
                hdb = "Warning: " + e.errorMessage();
            }
            rfList_->SetItem(i, 1, WxConversion::toWxString(id));
            rfList_->SetItem(i, 2, WxConversion::toWxString(hdb));
        }
    }
    // IU implementation list.
    const Machine::ImmediateUnitNavigator iuNav =
        machine_.immediateUnitNavigator();
    for (int i = 0; i < iuNav.count(); i++) {
        string iuName = iuNav.item(i)->name();
        iuList_->InsertItem(i, WxConversion::toWxString(iuName));
        if (impl_.hasIUImplementation(iuName)) {
            const RFImplementationLocation iuImpl =
                impl_.iuImplementation(iuName);
            string hdb;
            int id = 0;
            try {
                hdb = Environment::shortHDBPath(iuImpl.hdbFile());
                id = iuImpl.id();
            } catch (FileNotFound& e) {
                hdb = "Warning: " + e.errorMessage();
            }
            iuList_->SetItem(i, 1, WxConversion::toWxString(id));
            iuList_->SetItem(i, 2, WxConversion::toWxString(hdb));
        }
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), Exception::errorMessage(), IDF::MachineImplementation::fuImplementation(), fuList_, TTAMachine::Machine::functionUnitNavigator(), IDF::MachineImplementation::hasFUImplementation(), IDF::MachineImplementation::hasIUImplementation(), IDF::MachineImplementation::hasRFImplementation(), IDF::UnitImplementationLocation::hdbFile(), IDF::UnitImplementationLocation::id(), TTAMachine::Machine::immediateUnitNavigator(), impl_, TTAMachine::Machine::Navigator< ComponentType >::item(), IDF::MachineImplementation::iuImplementation(), iuList_, machine_, TTAMachine::Machine::registerFileNavigator(), IDF::MachineImplementation::rfImplementation(), rfList_, Environment::shortHDBPath(), and WxConversion::toWxString().
Referenced by onAutoSelectImplementations(), and TransferDataToWindow().
updateRFList()
void ProcessorImplementationWindow::updateRFList (const std::string & rfName, int index) private
Update the list of FU implementations for single RF
Definition at line 266 of file ProcessorImplementationWindow.cc.
{
    const RFImplementationLocation rfImpl =
        impl_.rfImplementation(rfName);
    string hdb;
    int id = 0;
    try {
        hdb = Environment::shortHDBPath(rfImpl.hdbFile());
        id = rfImpl.id();
    } catch (FileNotFound& e) {
        hdb = "Warning: " + e.errorMessage();
    }
    rfList_->SetItem(index, 1, WxConversion::toWxString(id));
    rfList_->SetItem(index, 2, WxConversion::toWxString(hdb));
}
References Exception::errorMessage(), IDF::UnitImplementationLocation::hdbFile(), IDF::UnitImplementationLocation::id(), impl_, IDF::MachineImplementation::rfImplementation(), rfList_, Environment::shortHDBPath(), and WxConversion::toWxString().
Referenced by handleSelectRFImplementation().
Member Data Documentation
dirtyData_
bool ProcessorImplementationWindow::dirtyData_ private
Definition at line 166 of file ProcessorImplementationWindow.hh.
Referenced by onClose(), and setDirty().
fuList_
wxListCtrl* ProcessorImplementationWindow::fuList_ private
Pointer to the FU implementation list widget.
Definition at line 123 of file ProcessorImplementationWindow.hh.
Referenced by onFUSelection(), onSelectFUImplementation(), updateFUList(), and updateImplementationLists().
impl_
IDF::MachineImplementation& ProcessorImplementationWindow::impl_ private
MachineImplementation object containing the implementation information.
Definition at line 120 of file ProcessorImplementationWindow.hh.
Referenced by checkImplementationFiles(), doSaveIDF(), handleSelectFUImplementation(), handleSelectIUImplementation(), handleSelectRFImplementation(), loadICDecoderPlugin(), onAutoSelectImplementations(), onBrowseDecompressor(), onBrowseICDecPlugin(), onBrowseICHDB(), onGenerateProcessor(), onLoadIDF(), onSetParameterValue(), TransferDataToWindow(), updateFUList(), updateImplementationLists(), and updateRFList().
iuList_
wxListCtrl* ProcessorImplementationWindow::iuList_ private
Pointer to the IU implementation list widget.
Definition at line 125 of file ProcessorImplementationWindow.hh.
Referenced by onIUSelection(), onSelectIUImplementation(), and updateImplementationLists().
machine_
TTAMachine::Machine& ProcessorImplementationWindow::machine_ private
Machine that is being generated.
Definition at line 118 of file ProcessorImplementationWindow.hh.
Referenced by handleSelectFUImplementation(), handleSelectIUImplementation(), handleSelectRFImplementation(), loadICDecoderPlugin(), onAutoSelectImplementations(), onGenerateProcessor(), onLoadIDF(), and updateImplementationLists().
parameterList_
wxListCtrl* ProcessorImplementationWindow::parameterList_ private
Pointer to the ic decoder parameter list widget.
Definition at line 129 of file ProcessorImplementationWindow.hh.
Referenced by onParameterSelection(), onSetParameterValue(), and TransferDataToWindow().
plugin_
ProGe::ICDecoderGeneratorPlugin* ProcessorImplementationWindow::plugin_ private
IC/Decoder plugin of the current machine implementation.
Definition at line 134 of file ProcessorImplementationWindow.hh.
Referenced by loadICDecoderPlugin(), onSetParameterValue(), and TransferDataToWindow().
pluginTool_
PluginTools ProcessorImplementationWindow::pluginTool_ private
Plugintool for loading IC/Decoder plugins.
Definition at line 132 of file ProcessorImplementationWindow.hh.
Referenced by loadICDecoderPlugin().
rfList_
wxListCtrl* ProcessorImplementationWindow::rfList_ private
Pointer to the RF implementation list widget.
Definition at line 127 of file ProcessorImplementationWindow.hh.
Referenced by onRFSelection(), onSelectRFImplementation(), updateImplementationLists(), and updateRFList().
The documentation for this class was generated from the following files:
ProcessorImplementationWindow.hh
ProcessorImplementationWindow.cc