OpenASIP: TPEF::ReferenceManager::SectionKey Class Reference
TPEF::ReferenceManager::SectionKey Class Reference
#include <ReferenceKey.hh>
Public Member Functions
SectionKey (SectionId sectionId)
virtual ~SectionKey ()
bool operator== (const SectionKey &other) const
bool operator!= (const SectionKey &other) const
bool operator< (const SectionKey &other) const
SectionId sectionId () const
Public Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
virtual ~ReferenceKey ()
Private Attributes
SectionId sectionId_
Identification code of the section that contains the element this key points to.
Additional Inherited Members
Protected Member Functions inherited from TPEF::ReferenceManager::ReferenceKey
ReferenceKey ()
Detailed Description
With this type of key one can identify (section) objects with an arbitrary numeric code that is unique among all objects.
Definition at line 145 of file ReferenceKey.hh.
Constructor & Destructor Documentation
SectionKey()
TPEF::ReferenceManager::SectionKey::SectionKey (SectionId sectionId)
The constructor.
Parameters
sectionId Identification code of the section.
Definition at line 125 of file ReferenceKey.cc.
                                          :
    sectionId_(sectionId) {
}
~SectionKey()
TPEF::ReferenceManager::SectionKey::~SectionKey () virtual
The destructor.
Definition at line 132 of file ReferenceKey.cc.
{
}
Member Function Documentation
operator!=()
bool TPEF::ReferenceManager::SectionKey::operator!= (const SectionKey & other) const
operator<()
bool TPEF::ReferenceManager::SectionKey::operator< (const SectionKey & other) const
operator==()
bool TPEF::ReferenceManager::SectionKey::operator== (const SectionKey & other) const
sectionId()
SectionId TPEF::ReferenceManager::SectionKey::sectionId () const
Referenced by TPEF::TPEFCodeSectionWriter::actualWriteData(), TPEF::TPEFDataSectionWriter::actualWriteData(), TPEF::TPEFStringSectionWriter::actualWriteData(), TPEF::TPEFASpaceSectionWriter::actualWriteData(), TPEF::TPEFSymbolSectionWriter::actualWriteData(), TPEF::TPEFUDataSectionWriter::createKeys(), TPEF::TPEFRelocSectionReader::finalize(), TPEF::ReferenceManager::HashFunctions::operator()(), TPEF::ReferenceManager::SafePointer::resolve(), and TPEF::SectionIdReplacer::tryToReplace().
Member Data Documentation
sectionId_
SectionId TPEF::ReferenceManager::SectionKey::sectionId_ private
Identification code of the section that contains the element this key points to.
Definition at line 160 of file ReferenceKey.hh.
The documentation for this class was generated from the following files:
ReferenceKey.hh
ReferenceKey.cc