OpenASIP: FUFactory Class Reference
FUFactory Class Reference
#include <FUFactory.hh>
Public Member Functions
FUFactory (EditPolicyFactory &editPolicyFactory)
virtual ~FUFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *component)
Public Member Functions inherited from EditPartFactory
virtual ~EditPartFactory ()
void registerFactory (Factory *factory)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
FUFactory & operator= (FUFactory &old)
Assignment not allowed.
FUFactory (FUFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from EditPartFactory
EditPartFactory (EditPolicyFactory &editPolicyFactory)
EditPart * checkCache (const TTAMachine::MachinePart *component) const
void writeToCache (EditPart *editPart)
Protected Member Functions inherited from Factory
Factory ()
Protected Attributes inherited from EditPartFactory
std::vector< Factory * > factories_
Registered factories.
EditPolicyFactory & editPolicyFactory_
Factory which creates edit policies for edit parts.
Static Protected Attributes inherited from EditPartFactory
static std::vector< EditPart * > created_
Container for already created EditParts.
Detailed Description
Factory for creating function unit EditParts corresponding to a given Machine FunctionUnit object.
Definition at line 45 of file FUFactory.hh.
Constructor & Destructor Documentation
FUFactory() [1/2]
FUFactory::FUFactory (EditPolicyFactory & editPolicyFactory)
The Constructor.
Definition at line 53 of file FUFactory.cc.
                                                        :
    EditPartFactory(editPolicyFactory) {
    registerFactory(new UnitPortFactory(editPolicyFactory));
}
References EditPartFactory::registerFactory().
~FUFactory()
FUFactory::~FUFactory () virtual
The Destructor.
Definition at line 63 of file FUFactory.cc.
                      {
}
FUFactory() [2/2]
FUFactory::FUFactory (FUFactory & old) private
Copying not allowed.
Member Function Documentation
createEditPart()
EditPart * FUFactory::createEditPart (TTAMachine::MachinePart * component) virtual
Returns an EditPart corresponding to a function unit.
Parameters
component Function unit of which to create the EditPart.
Returns
NULL if the parameter is not an instance of the FunctionUnit class.
Implements Factory.
Definition at line 75 of file FUFactory.cc.
{
    FunctionUnit* fu = dynamic_cast<FunctionUnit*>(component);
    if (fu != NULL) {
        EditPart* fuEditPart = new EditPart();
        fuEditPart->setModel(fu);
        UnitFigure* fig = new UnitFigure();
        wxString name = WxConversion::toWxString(fu->name());
        name.Prepend(_T("FU: "));
        fig->setName(name);
        fuEditPart->setFigure(fig);
        for (int i = 0; i < fu->portCount(); i++) {
            vector<Factory*>::const_iterator iter;
            for (iter = factories_.begin(); iter != factories_.end(); iter++) {
                EditPart* portEditPart =
                    (*iter)->createEditPart(fu->port(i));
                if (portEditPart != NULL) {
                    fuEditPart->addChild(portEditPart);
                    EditPolicy* editPolicy =
                        editPolicyFactory_.createFUPortEditPolicy();
                    if (editPolicy != NULL) {
                        portEditPart->installEditPolicy(editPolicy);
                    }
                }
            }
        }
        wxString operations = _T("{ ");
        AddressSpace* as = fu->addressSpace();
        if (as != NULL) {
            operations.Append(_T("AS: "));
            operations.Append(
                WxConversion::toWxString(as->name()));
            operations.Append(_T(" Ops:"));
        }
        for (int i = 0; i < fu->operationCount(); i++) {
            if (i > 0) {
                operations.Append(_T(", "));
            }
            operations.Append(
                WxConversion::toWxString(fu->operation(i)->name()));
        }
        operations.Append(_T(" }"));
        fig->setInfo(operations);
        fuEditPart->setSelectable(true);
        EditPolicy* editPolicy = editPolicyFactory_.createFUEditPolicy();
        if (editPolicy != NULL) {
            fuEditPart->installEditPolicy(editPolicy);
        }
        return fuEditPart;
    } else {
        return NULL;
    }
}
References EditPart::addChild(), TTAMachine::FunctionUnit::addressSpace(), EditPolicyFactory::createFUEditPolicy(), EditPolicyFactory::createFUPortEditPolicy(), EditPartFactory::editPolicyFactory_, EditPartFactory::factories_, EditPart::installEditPolicy(), TTAMachine::HWOperation::name(), TTAMachine::Component::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), TTAMachine::FunctionUnit::port(), TTAMachine::Unit::portCount(), EditPart::setFigure(), UnitFigure::setInfo(), EditPart::setModel(), UnitFigure::setName(), EditPart::setSelectable(), and WxConversion::toWxString().
operator=()
FUFactory & FUFactory::operator= (FUFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
FUFactory.hh
FUFactory.cc