OpenASIP: ImmediateControlField Class Reference
ImmediateControlField Class Reference
#include <ImmediateControlField.hh>
Public Member Functions
ImmediateControlField (BinaryEncoding &parent)
ImmediateControlField (const ObjectState *state, BinaryEncoding &parent)
virtual ~ImmediateControlField ()
BinaryEncoding * parent () const
int templateCount () const
std::string instructionTemplate (int index) const
bool hasTemplateEncoding (const std::string &name) const
unsigned int templateEncoding (const std::string &name) const
void addTemplateEncoding (const std::string &name, unsigned int encoding)
void removeTemplateEncoding (const std::string &name)
virtual int width () const
virtual int childFieldCount () const
virtual InstructionField & childField (int) const
virtual void loadState (const ObjectState *state)
virtual ObjectState * saveState () const
Public Member Functions inherited from InstructionField
virtual ~InstructionField ()
InstructionField * parent () const
int bitPosition () const
int relativePosition () const
virtual void setRelativePosition (int position)
void setExtraBits (int bits)
int extraBits () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Attributes
static const std::string OSNAME_IMM_CONTROL_FIELD = "ic_field"
ObjectState name for immediate control field.
static const std::string OSNAME_TEMPLATE_MAP = "temp_map"
ObjectState name for a template mapping.
static const std::string OSKEY_TEMPLATE_NAME = "temp_name"
ObjectState attribute key for the name of the instruction template.
static const std::string OSKEY_ENCODING = "encoding"
ObjectState attribute key for the encoding of the instruction template.
Static Public Attributes inherited from InstructionField
static const std::string OSNAME_INSTRUCTION_FIELD = "instr_field"
ObjectState name for instruction field.
static const std::string OSKEY_EXTRA_BITS = "extra_bits"
ObjectState attribute key for the number of extra bits.
static const std::string OSKEY_POSITION = "position"
ObjectState attribute key for the relative position of the field.
Private Types
typedef std::map< std::string, unsigned int > EncodingMap
A map type for binary encodings.
Private Member Functions
void clearTemplateEncodings ()
Private Attributes
EncodingMap templates_
Binary encodings for instruction templates.
Additional Inherited Members
Protected Member Functions inherited from InstructionField
InstructionField (InstructionField *parent)
InstructionField (const ObjectState *state, InstructionField *parent)
void setParent (InstructionField *parent)
Static Protected Member Functions inherited from InstructionField
static void reorderSubfields (ObjectState *state)
Detailed Description
ImmediateControlField is a specialised InstructionField and represents the field of the TTA instruction that contains the long immediate control tag.
This tag defines the template of the instruction. A TTA instruction template specifies which move slots are used to program data transports and which are used to encode immediate bits. An ImmediateControlField object can never exist alone. It is always registered to a BinaryEncoding object.
Definition at line 57 of file ImmediateControlField.hh.
Member Typedef Documentation
EncodingMap
typedef std::map<std::string, unsigned int> ImmediateControlField::EncodingMap private
A map type for binary encodings.
Definition at line 95 of file ImmediateControlField.hh.
Constructor & Destructor Documentation
ImmediateControlField() [1/2]
ImmediateControlField::ImmediateControlField (BinaryEncoding & parent)
The constructor.
Registers the immediate control field to the parent BinaryEncoding automatically. The field is added as the leftmost field of the TTA instruction.
Parameters
parent The parent encoding map.
Exceptions
ObjectAlreadyExists If the given encoding map has an immediate control field already.
Definition at line 61 of file ImmediateControlField.cc.
    : InstructionField(&parent) {
    setParent(NULL);
    parent.setImmediateControlField(*this);
    setParent(&parent);
}
References parent(), BinaryEncoding::setImmediateControlField(), and InstructionField::setParent().
ImmediateControlField() [2/2]
ImmediateControlField::ImmediateControlField (const ObjectState * state, BinaryEncoding & parent)
The constructor.
Loads the state of the object from the given ObjectState tree.
Parameters
state The ObjectState tree.
parent The parent encoding map.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
ObjectAlreadyExists If the given encoding map has an immediate control field already.
Definition at line 80 of file ImmediateControlField.cc.
    : InstructionField(state, &parent) {
    loadState(state);
    setParent(NULL);
    parent.setImmediateControlField(*this);
    setParent(&parent);
}
References loadState(), parent(), BinaryEncoding::setImmediateControlField(), and InstructionField::setParent().
~ImmediateControlField()
ImmediateControlField::~ImmediateControlField () virtual
The destructor.
Definition at line 92 of file ImmediateControlField.cc.
{
    BinaryEncoding* oldParent = parent();
    assert(oldParent != NULL);
    setParent(NULL);
    oldParent->unsetImmediateControlField();
}
References assert, parent(), InstructionField::setParent(), and BinaryEncoding::unsetImmediateControlField().
Member Function Documentation
addTemplateEncoding()
void ImmediateControlField::addTemplateEncoding (const std::string & name, unsigned int encoding)
Assings the given code to the instruction template identified by the given name.
If the given instruction template has an encoding already, replaces the encoding with the given one.
Parameters
name Name of the instruction template.
encoding The code to be assigned.
Exceptions
ObjectAlreadyExists If the given code is already assigned to another instruction template.
Definition at line 206 of file ImmediateControlField.cc.
{
    if (MapTools::containsValue(templates_, encoding) &&
    MapTools::keyForValue<string>(templates_, encoding) != name) {
    const string procName = "ImmediateControlField::addTemplateEncoding";
    throw ObjectAlreadyExists(__FILE__, __LINE__, procName);
    }
    pair<EncodingMap::iterator, bool> result =
    templates_.insert(pair<string, int>(name, encoding));
    if (!result.second) {
    // if there is a code for the template already
    EncodingMap::iterator iter = templates_.find(name);
    assert(iter != templates_.end());
    iter->second = encoding;
    }
}
References assert, MapTools::containsValue(), MapTools::keyForValue(), and templates_.
Referenced by BEMGenerator::addEncodings(), and loadState().
childField()
InstructionField & ImmediateControlField::childField (int) const virtual
Always throws OutOfRange exception because immediate control field does not have any child fields.
Returns
Never returns.
Exceptions
OutOfRange Always thrown.
Reimplemented from InstructionField.
Definition at line 276 of file ImmediateControlField.cc.
{
    const string procName = "ImmediateControlField::childField";
    throw OutOfRange(__FILE__, __LINE__, procName);
}
childFieldCount()
int ImmediateControlField::childFieldCount () const virtual
Always returns 0.
Returns
0.
Implements InstructionField.
Definition at line 263 of file ImmediateControlField.cc.
{
    return 0;
}
clearTemplateEncodings()
void ImmediateControlField::clearTemplateEncodings () private
Clears all the template encodings from the immediate control field.
Definition at line 346 of file ImmediateControlField.cc.
{
    templates_.clear();
}
References templates_.
Referenced by loadState().
hasTemplateEncoding()
bool ImmediateControlField::hasTemplateEncoding (const std::string & name) const
Tells whether the instruction template with the given name has has a binary encoding in this field.
Parameters
name Name of the instruction template.
Returns
True if the template has a binary encoding, otherwise false.
Definition at line 167 of file ImmediateControlField.cc.
{
    return MapTools::containsKey(templates_, name);
}
References MapTools::containsKey(), and templates_.
Referenced by BEMValidator::checkImmediateControlField(), DefaultDecoderGenerator::instructionTemplateCondition(), and templateEncoding().
instructionTemplate()
std::string ImmediateControlField::instructionTemplate (int index) const
Returns the name of the instruction template encoded in this field at the given position.
Parameters
index The position index.
Exceptions
OutOfRange If the given index is negative or not smaller than the number of encodings of instruction templates.
Definition at line 138 of file ImmediateControlField.cc.
{
    if (index < 0 || index >= templateCount()) {
    const string procName = "ImmediateControlField::instructionTemplate";
    throw OutOfRange(__FILE__, __LINE__, procName);
    }
    int counter(0);
    for (EncodingMap::const_iterator iter = templates_.begin();
     iter != templates_.end(); iter++) {
    if (counter == index) {
        return iter->first;
    } else {
        counter++;
    }
    }
    assert(false);
    return "";
}
References assert, templateCount(), and templates_.
Referenced by BinaryEncoding::longestTemplateExtraBits(), printImmediateControlField(), saveState(), and BinaryEncoding::width().
loadState()
void ImmediateControlField::loadState (const ObjectState * state) virtual
Loads the state of the immediate control field from the given ObjectState tree.
Parameters
state The ObjectState tree.
Exceptions
ObjectStateLoadingException If an error occurs while loading the state.
Reimplemented from InstructionField.
Definition at line 290 of file ImmediateControlField.cc.
{
    clearTemplateEncodings();
    InstructionField::loadState(state);
    const string procName = "ImmediateControlField::loadState";
    if (state->name() != OSNAME_IMM_CONTROL_FIELD) {
    throw ObjectStateLoadingException(__FILE__, __LINE__, procName);
    }
    try {
    for (int i = 0; i < state->childCount(); i++) {
        ObjectState* child = state->child(i);
        if (child->name() != OSNAME_TEMPLATE_MAP) {
        throw ObjectStateLoadingException(
            __FILE__, __LINE__, procName);
        }
        string tempName = child->stringAttribute(OSKEY_TEMPLATE_NAME);
        int encoding = child->intAttribute(OSKEY_ENCODING);
        addTemplateEncoding(tempName, encoding);
    }
    } catch (const Exception& exception) {
    throw ObjectStateLoadingException(
        __FILE__, __LINE__, procName, exception.errorMessage());
    }
}
References addTemplateEncoding(), ObjectState::child(), ObjectState::childCount(), clearTemplateEncodings(), Exception::errorMessage(), ObjectState::intAttribute(), InstructionField::loadState(), ObjectState::name(), OSKEY_ENCODING, OSKEY_TEMPLATE_NAME, OSNAME_IMM_CONTROL_FIELD, OSNAME_TEMPLATE_MAP, and ObjectState::stringAttribute().
Referenced by ImmediateControlField().
parent()
BinaryEncoding * ImmediateControlField::parent () const
Returns the parent encoding map.
Returns
The parent encoding map.
Definition at line 106 of file ImmediateControlField.cc.
{
    InstructionField* parent = InstructionField::parent();
    if (parent == NULL) {
    return NULL;
    } else {
    BinaryEncoding* encoding = dynamic_cast<BinaryEncoding*>(parent);
    assert(encoding != NULL);
    return encoding;
    }
}
References assert, parent(), and InstructionField::parent().
Referenced by ImmediateControlField(), ImmediateControlField(), parent(), BinaryEncoding::setImmediateControlField(), and ~ImmediateControlField().
removeTemplateEncoding()
void ImmediateControlField::removeTemplateEncoding (const std::string & name)
Removes the code of the instruction template with the given name.
Parameters
name Name of the instruction template.
Definition at line 232 of file ImmediateControlField.cc.
{
    templates_.erase(name);
}
References templates_.
saveState()
ObjectState * ImmediateControlField::saveState () const virtual
Saves the state of the immediate control field to an ObjectState tree.
Returns
The newly created ObjectState tree.
Reimplemented from InstructionField.
Definition at line 323 of file ImmediateControlField.cc.
{
    ObjectState* state = InstructionField::saveState();
    state->setName(OSNAME_IMM_CONTROL_FIELD);
    state->setAttribute(OSKEY_POSITION, relativePosition());
    for (int i = 0; i < templateCount(); i++) {
    string temp = instructionTemplate(i);
    int encoding = templateEncoding(temp);
    ObjectState* tempMap = new ObjectState(OSNAME_TEMPLATE_MAP);
    state->addChild(tempMap);
    tempMap->setAttribute(OSKEY_TEMPLATE_NAME, temp);
    tempMap->setAttribute(OSKEY_ENCODING, encoding);
    }
    return state;
}
References ObjectState::addChild(), instructionTemplate(), OSKEY_ENCODING, InstructionField::OSKEY_POSITION, OSKEY_TEMPLATE_NAME, OSNAME_IMM_CONTROL_FIELD, OSNAME_TEMPLATE_MAP, InstructionField::relativePosition(), InstructionField::saveState(), ObjectState::setAttribute(), ObjectState::setName(), templateCount(), and templateEncoding().
templateCount()
int ImmediateControlField::templateCount () const
Returns the number of instruction templates with a binary encoding assigned.
Returns
The number of instruction templates.
Definition at line 124 of file ImmediateControlField.cc.
{
    return templates_.size();
}
References templates_.
Referenced by instructionTemplate(), BinaryEncoding::longestTemplateExtraBits(), printImmediateControlField(), saveState(), and BinaryEncoding::width().
templateEncoding()
unsigned int ImmediateControlField::templateEncoding (const std::string & name) const
Returns the code that identifies the instruction template with the given name.
Parameters
name Name of the instruction template.
Returns
The code that identifies the given instruction template.
Exceptions
InstanceNotFound If the given instruction template does not have a binary encoding in this field.
Definition at line 182 of file ImmediateControlField.cc.
{
    if (!hasTemplateEncoding(name)) {
    const string procName = "ImmediateControlField::templateEncoding";
    throw InstanceNotFound(__FILE__, __LINE__, procName);
    }
    EncodingMap::const_iterator iter = templates_.find(name);
    assert(iter != templates_.end());
    return iter->second;
}
References assert, hasTemplateEncoding(), and templates_.
Referenced by CodeCompressorPlugin::addBitsForICField(), DefaultDecoderGenerator::instructionTemplateCondition(), printImmediateControlField(), saveState(), and DefaultDecoderGenerator::writeSquashSignalGenerationProcess().
width()
int ImmediateControlField::width () const virtual
Returns the bit width of the immediate control field.
Returns
The bit width of the field.
Implements InstructionField.
Definition at line 243 of file ImmediateControlField.cc.
{
    int minWidth(0);
    for (EncodingMap::const_iterator iter = templates_.begin();
     iter != templates_.end(); iter++) {
    int encoding = iter->second;
    int requiredBits = MathTools::bitLength(encoding);
    if (requiredBits > minWidth) {
        minWidth = requiredBits;
    }
    }
    return minWidth + extraBits();
}
References MathTools::bitLength(), InstructionField::extraBits(), and templates_.
Referenced by CodeCompressorPlugin::addBitsForICField(), CodeCompressorPlugin::bemInstructionBits(), CodeCompressorPlugin::firstMoveSlotIndex(), printImmediateControlField(), BinaryEncoding::width(), DefaultDecoderGenerator::writeInstructionDismembering(), and DefaultDecoderGenerator::writeLongImmediateTagSignal().
Member Data Documentation
OSKEY_ENCODING
const std::string ImmediateControlField::OSKEY_ENCODING = "encoding" static
ObjectState attribute key for the encoding of the instruction template.
Definition at line 91 of file ImmediateControlField.hh.
Referenced by loadState(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), and saveState().
OSKEY_TEMPLATE_NAME
const std::string ImmediateControlField::OSKEY_TEMPLATE_NAME = "temp_name" static
ObjectState attribute key for the name of the instruction template.
Definition at line 88 of file ImmediateControlField.hh.
Referenced by loadState(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), and saveState().
OSNAME_IMM_CONTROL_FIELD
const std::string ImmediateControlField::OSNAME_IMM_CONTROL_FIELD = "ic_field" static
ObjectState name for immediate control field.
Definition at line 84 of file ImmediateControlField.hh.
Referenced by BEMSerializer::convertToFileFormat(), BinaryEncoding::loadState(), loadState(), BEMSerializer::longImmTagToOM(), and saveState().
OSNAME_TEMPLATE_MAP
const std::string ImmediateControlField::OSNAME_TEMPLATE_MAP = "temp_map" static
ObjectState name for a template mapping.
Definition at line 86 of file ImmediateControlField.hh.
Referenced by loadState(), BEMSerializer::longImmTagToFile(), BEMSerializer::longImmTagToOM(), and saveState().
templates_
EncodingMap ImmediateControlField::templates_ private
Binary encodings for instruction templates.
Definition at line 100 of file ImmediateControlField.hh.
Referenced by addTemplateEncoding(), clearTemplateEncodings(), hasTemplateEncoding(), instructionTemplate(), removeTemplateEncoding(), templateCount(), templateEncoding(), and width().
The documentation for this class was generated from the following files:
ImmediateControlField.hh
ImmediateControlField.cc