OpenASIP: TriggeringInputPortState Class Reference
TriggeringInputPortState Class Reference
#include <TriggeringInputPortState.hh>
Public Member Functions
TriggeringInputPortState (FUState &parent, int width)
TriggeringInputPortState (FUState &parent, SimValue &sharedRegister)
virtual ~TriggeringInputPortState ()
virtual void setValue (const SimValue &value)
Public Member Functions inherited from InputPortState
InputPortState (FUState &parent, int width)
InputPortState (FUState &parent, SimValue &registerToUse)
virtual ~InputPortState ()
Public Member Functions inherited from PortState
PortState (FUState &parent, int width)
PortState (FUState &parent, SimValue &sharedRegister)
virtual ~PortState ()
virtual FUState & parent () const
Public Member Functions inherited from RegisterState
RegisterState (int width, bool constantZero=false)
RegisterState (SimValue &sharedRegister)
virtual ~RegisterState ()
virtual const SimValue & value () const
Public Member Functions inherited from StateData
StateData ()
virtual ~StateData ()
Public Member Functions inherited from WritableState
WritableState ()
virtual ~WritableState ()
Public Member Functions inherited from ReadableState
ReadableState ()
virtual ~ReadableState ()
Private Member Functions
TriggeringInputPortState (const TriggeringInputPortState &)
Copying not allowed.
TriggeringInputPortState & operator= (const TriggeringInputPortState &)
Assignment not allowed.
Additional Inherited Members
Protected Attributes inherited from PortState
FUState * parent_
Parent of the port.
Protected Attributes inherited from RegisterState
SimValue & value_
Value of the RegisterState.
Detailed Description
Models input port state that triggers operation.
Definition at line 46 of file TriggeringInputPortState.hh.
Constructor & Destructor Documentation
TriggeringInputPortState() [1/3]
TriggeringInputPortState::TriggeringInputPortState (FUState & parent, int width)
Constructor.
Parameters
parent Parent of the port.
width Width of the port.
Definition at line 46 of file TriggeringInputPortState.cc.
               :
    InputPortState(parent, width) {
}
TriggeringInputPortState() [2/3]
TriggeringInputPortState::TriggeringInputPortState (FUState & parent, SimValue & registerToUse)
Constructor for port which uses a shared register.
Parameters
parent Parent of the port.
name Name of the port.
registerToUse The shared register storage.
Definition at line 59 of file TriggeringInputPortState.cc.
                             :
    InputPortState(parent, registerToUse) {
}
~TriggeringInputPortState()
TriggeringInputPortState::~TriggeringInputPortState () virtual
Destructor.
Definition at line 68 of file TriggeringInputPortState.cc.
{
}
TriggeringInputPortState() [3/3]
TriggeringInputPortState::TriggeringInputPortState (const TriggeringInputPortState &) private
Copying not allowed.
Member Function Documentation
operator=()
TriggeringInputPortState & TriggeringInputPortState::operator= (const TriggeringInputPortState &) private
Assignment not allowed.
setValue()
void TriggeringInputPortState::setValue (const SimValue & value) virtual
Sets the value of the port and triggers an operation.
Parameters
value Value to be set.
Reimplemented from RegisterState.
Definition at line 77 of file TriggeringInputPortState.cc.
{
    parent_->setTriggered();
    RegisterState::setValue(value);
}
References PortState::parent_, FUState::setTriggered(), RegisterState::setValue(), and RegisterState::value().
The documentation for this class was generated from the following files:
TriggeringInputPortState.hh
TriggeringInputPortState.cc