OpenASIP: StepiCommand Class Reference
StepiCommand Class Reference
#include <StepiCommand.hh>
Public Member Functions
StepiCommand ()
virtual ~StepiCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
virtual std::string helpText () const
Public Member Functions inherited from SimControlLanguageCommand
SimControlLanguageCommand (const std::string &name)
virtual ~SimControlLanguageCommand ()
SimulatorFrontend & simulatorFrontend ()
const SimulatorFrontend & simulatorFrontendConst ()
virtual void printNextInstruction ()
virtual void printStopInformation ()
virtual void printStopReasons ()
virtual bool printBreakpointInfo (unsigned int breakpointHandle)
virtual void printSimulationTime ()
virtual std::ostream & outputStream ()
bool checkSimulationInitialized ()
bool checkSimulationNotAlreadyRunning ()
bool checkSimulationStopped ()
bool checkSimulationEnded ()
bool checkProgramLoaded ()
bool checkMachineLoaded ()
InstructionAddress parseInstructionAddressExpression (const std::string &expression)
TTAProgram::Address parseDataAddressExpression (const std::string &expression)
bool parseBreakpoint (const std::vector< DataObject > &arguments, Breakpoint &target)
bool askConditionFromUser (TclConditionScript &target)
bool askExpressionFromUser (ExpressionScript &target)
bool verifyBreakpointHandles (const std::vector< DataObject > &arguments, std::size_t startIndex=1)
void setErrorMessage (const TCEString &errorMsg)
Public Member Functions inherited from CustomCommand
CustomCommand (std::string name)
CustomCommand (const CustomCommand &cmd)
virtual ~CustomCommand ()
std::string name () const
void setContext (InterpreterContext *context)
InterpreterContext * context () const
void setInterpreter (ScriptInterpreter *si)
ScriptInterpreter * interpreter () const
bool checkArgumentCount (int argumentCount, int minimum, int maximum)
bool checkIntegerArgument (const DataObject &argument)
bool checkPositiveIntegerArgument (const DataObject &argument)
bool checkUnsignedIntegerArgument (const DataObject &argument)
bool checkDoubleArgument (const DataObject &argument)
Additional Inherited Members
Protected Member Functions inherited from SimControlLanguageCommand
bool setMemoryAddress (const std::string &addressString, std::string &addressSpaceName, std::size_t &memoryAddress)
bool setMemoryPointer (MemorySystem::MemoryPtr &memory, const std::string &addressSpaceName)
Detailed Description
Implementation of the "stepi" command of the Simulator Control Language.
Definition at line 47 of file StepiCommand.hh.
Constructor & Destructor Documentation
StepiCommand()
StepiCommand::StepiCommand ()
Constructor.
Sets the name of the command to the base class.
Definition at line 50 of file StepiCommand.cc.
                           : SimControlLanguageCommand("stepi") {
}
~StepiCommand()
StepiCommand::~StepiCommand () virtual
Destructor.
Does nothing.
Definition at line 58 of file StepiCommand.cc.
{
}
Member Function Documentation
execute()
bool StepiCommand::execute (const std::vector< DataObject > & arguments) virtual
Executes the "stepi" command.
Executes the user defined count of next TTA instruction and returns control back to user.
Parameters
arguments The count of steps (default is one step).
Returns
True in case simulation is initialized and arguments are ok.
Exceptions
NumberFormatException Is never thrown by this command.
Todo:
Use the count for the step.
Implements CustomCommand.
Definition at line 73 of file StepiCommand.cc.
{
    if (!checkArgumentCount(arguments.size() - 1, 0, 1)) {
        return false;
    }
    double stepCount = 1;
    if (arguments.size() == 2) {
        if  (!checkDoubleArgument(arguments[1])) {
            return false;
        }
        stepCount = arguments[1].doubleValue();
    }
    if (!checkSimulationStopped()) {
        if (!checkSimulationInitialized()) {
            return false;
        }
    }
    simulatorFrontend().step(stepCount);
    printNextInstruction();
    printSimulationTime();
    return true;
}
References CustomCommand::checkArgumentCount(), CustomCommand::checkDoubleArgument(), SimControlLanguageCommand::checkSimulationInitialized(), SimControlLanguageCommand::checkSimulationStopped(), SimControlLanguageCommand::printNextInstruction(), SimControlLanguageCommand::printSimulationTime(), SimControlLanguageCommand::simulatorFrontend(), and SimulatorFrontend::step().
helpText()
std::string StepiCommand::helpText () const virtual
Returns the help text for this command.
Help text is searched from SimulatorTextGenerator.
Returns
The help text.
Todo:
Use SimulatorTextGenerator to get the help text.
Implements CustomCommand.
Definition at line 107 of file StepiCommand.cc.
{
    return SimulatorToolbox::textGenerator().text(
        Texts::TXT_INTERP_HELP_STEPI).str();
}
References Texts::TextGenerator::text(), SimulatorToolbox::textGenerator(), and Texts::TXT_INTERP_HELP_STEPI.
The documentation for this class was generated from the following files:
StepiCommand.hh
StepiCommand.cc