OpenASIP: llvm::TCESubtarget Class Reference
llvm::TCESubtarget Class Reference
#include <TCESubtarget.hh>
Public Member Functions
TCESubtarget (TCETargetMachinePlugin *plugin)
std::string pluginFileName ()
virtual bool isLittleEndian () const
virtual bool is64bit () const
const InstrItineraryData * getInstrItineraryData () const override
virtual const TargetInstrInfo * getInstrInfo () const override
virtual const TargetFrameLowering * getFrameLowering () const override
virtual const TargetLowering * getTargetLowering () const override
virtual const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
virtual const TargetRegisterInfo * getRegisterInfo () const override
virtual bool enableMachinePipeliner () const override
Protected Member Functions
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Private Attributes
std::string pluginFile_
TCETargetMachinePlugin * plugin_
InstrItineraryData InstrItins
Detailed Description
Currently there is only one generic universal machine target, so this class doesn't contain any relevant information.
Definition at line 56 of file TCESubtarget.hh.
Constructor & Destructor Documentation
TCESubtarget()
TCESubtarget::TCESubtarget (TCETargetMachinePlugin * plugin)
The Constructor.
Definition at line 69 of file TCESubtarget.cc.
    : TCEGenSubtargetInfo(
          Triple("tce-tut-llvm"), std::string(""), std::string(""),
          std::string("")),
      pluginFile_(BackendPluginFile),
      plugin_(plugin),
      InstrItins(getInstrItineraryForCPU("generic")) {
    assert(InstrItins.Itineraries != nullptr && "IstrItins not initialized");
}
References assert, and InstrItins.
Member Function Documentation
enableMachinePipeliner()
bool TCESubtarget::enableMachinePipeliner () const override virtual
Definition at line 112 of file TCESubtarget.cc.
{
    return false;
}
getFrameLowering()
const TargetFrameLowering * TCESubtarget::getFrameLowering () const override virtual
Definition at line 99 of file TCESubtarget.cc.
{
    return plugin_->getFrameLowering();
}
References llvm::TCETargetMachinePlugin::getFrameLowering(), and plugin_.
getInstrInfo()
const TargetInstrInfo * TCESubtarget::getInstrInfo () const override virtual
Definition at line 91 of file TCESubtarget.cc.
{
    return plugin_->getInstrInfo();
}
References llvm::TCETargetMachinePlugin::getInstrInfo(), and plugin_.
getInstrItineraryData()
const InstrItineraryData * llvm::TCESubtarget::getInstrItineraryData () const inline override
Definition at line 65 of file TCESubtarget.hh.
{
            return &InstrItins;
        }
References InstrItins.
getRegisterInfo()
const TargetRegisterInfo * TCESubtarget::getRegisterInfo () const override virtual
Definition at line 95 of file TCESubtarget.cc.
{
    return plugin_->getRegisterInfo();
}
References llvm::TCETargetMachinePlugin::getRegisterInfo(), and plugin_.
Referenced by llvm::TCETargetLowering::TCETargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * TCESubtarget::getSelectionDAGInfo () const override virtual
Definition at line 107 of file TCESubtarget.cc.
{
    return plugin_->getSelectionDAGInfo();
}
References llvm::TCETargetMachinePlugin::getSelectionDAGInfo(), and plugin_.
getTargetLowering()
const TargetLowering * TCESubtarget::getTargetLowering () const override virtual
Definition at line 103 of file TCESubtarget.cc.
{
    return plugin_->getTargetLowering();
}
References llvm::TCETargetMachinePlugin::getTargetLowering(), and plugin_.
is64bit()
virtual bool llvm::TCESubtarget::is64bit () const inline virtual
Reimplemented in llvm::TCELE64Subtarget.
Definition at line 62 of file TCESubtarget.hh.
{ return false; }
isLittleEndian()
virtual bool llvm::TCESubtarget::isLittleEndian () const inline virtual
Reimplemented in llvm::TCELESubtarget.
Definition at line 60 of file TCESubtarget.hh.
{ return false; };
ParseSubtargetFeatures()
void llvm::TCESubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS) protected
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
pluginFileName()
std::string TCESubtarget::pluginFileName ()
Returns full path of the plugin file name supplied with the -tce-plugin-file parameter.
Returns
plugin file path
Definition at line 87 of file TCESubtarget.cc.
{
    return pluginFile_;
}
References pluginFile_.
Member Data Documentation
InstrItins
InstrItineraryData llvm::TCESubtarget::InstrItins private
Definition at line 87 of file TCESubtarget.hh.
Referenced by getInstrItineraryData(), and TCESubtarget().
plugin_
TCETargetMachinePlugin* llvm::TCESubtarget::plugin_ private
Definition at line 86 of file TCESubtarget.hh.
Referenced by getFrameLowering(), getInstrInfo(), getRegisterInfo(), getSelectionDAGInfo(), and getTargetLowering().
pluginFile_
std::string llvm::TCESubtarget::pluginFile_ private
Definition at line 85 of file TCESubtarget.hh.
Referenced by pluginFileName().
The documentation for this class was generated from the following files:
TCESubtarget.hh
TCESubtarget.cc