OpenASIP: BridgeDialog Class Reference
BridgeDialog Class Reference
#include <BridgeDialog.hh>
Public Member Functions
BridgeDialog (wxWindow *parent, TTAMachine::Bridge *bridge, TTAMachine::Bridge *opposite)
virtual ~BridgeDialog ()
Private Types
enum {
ID_NAME = 10000 , ID_OUTPUT_BUS , ID_INPUT_BUS , ID_OPPOSITE_BRIDGE ,
ID_BIDIRECTIONAL , ID_HELP , ID_LABEL_NAME , ID_LABEL_OPPOSITE_NAME ,
ID_LABEL_INPUT_BUS , ID_LABEL_OUTPUT_BUS , ID_LINE
}
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
virtual bool TransferDataToWindow ()
void setTexts ()
void updateBusChoices ()
void onOK (wxCommandEvent &)
void onCancel (wxCommandEvent &)
void onHelp (wxCommandEvent &event)
void onName (wxCommandEvent &)
void onInputBus (wxCommandEvent &)
void onOutputBus (wxCommandEvent &)
void onBidirectional (wxCommandEvent &)
Private Attributes
TTAMachine::Machine * machine_
Parent machine of the bridge(s).
wxString name_
Name of the bridge.
wxString oppositeName_
Name of the opposite bridge.
wxString inputBus_
Name of the bridge input bus.
wxString outputBus_
Name of the bridge output bus.
wxTextCtrl * oppositeNameCtrl_
Opposite name control.
wxChoice * inputBusChoice_
Input bus choice control.
wxChoice * outputBusChoice_
Output bus choice control.
wxCheckBox * bidirectionalBox_
Indicates whether the bridge is bidirectional.
bool adding_
Indicates whether we are adding a bridge or not.
bool bidirectional_
Indicates whether we are modifying a bidirectional bridge or not.
Detailed Description
Dialog for querying bridge parameters from the user.
Definition at line 46 of file BridgeDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ID_NAME
ID_OUTPUT_BUS
ID_INPUT_BUS
ID_OPPOSITE_BRIDGE
ID_BIDIRECTIONAL
ID_HELP
ID_LABEL_NAME
ID_LABEL_OPPOSITE_NAME
ID_LABEL_INPUT_BUS
ID_LABEL_OUTPUT_BUS
ID_LINE
Definition at line 98 of file BridgeDialog.hh.
         {
        ID_NAME = 10000,
        ID_OUTPUT_BUS,
        ID_INPUT_BUS,
        ID_OPPOSITE_BRIDGE,
        ID_BIDIRECTIONAL,
        ID_HELP,
        ID_LABEL_NAME,
        ID_LABEL_OPPOSITE_NAME,
        ID_LABEL_INPUT_BUS,
        ID_LABEL_OUTPUT_BUS,
        ID_LINE
    };
Constructor & Destructor Documentation
BridgeDialog()
BridgeDialog::BridgeDialog (wxWindow * parent, TTAMachine::Bridge * bridge, TTAMachine::Bridge * opposite)
The Constructor.
Parameters
parent Parent window of the dialog.
bridge Bridge to be modified with the dialog.
opposite Bridge to be modified having the opposite direction compared to bridge.
Definition at line 80 of file BridgeDialog.cc.
                     :
    wxDialog(parent, -1, _T(""), wxDefaultPosition),
    name_(_T("")),
    oppositeName_(_T("")),
    oppositeNameCtrl_(NULL),
    inputBusChoice_(NULL),
    outputBusChoice_(NULL),
    bidirectionalBox_(NULL) {
    assert(bridge != NULL);
    // The canvas tool has to disabled.
    MDFView* view =
        dynamic_cast<MDFView*>(wxGetApp().docManager()->GetCurrentView());
    view->canvas()->tool()->deactivate();
    // initialize the dialog
    createContents(this, true, true);
    FindWindow(wxID_OK)->Disable();
    wxTextCtrl* nameCtrl = dynamic_cast<wxTextCtrl*>(FindWindow(ID_NAME));
    assert(nameCtrl != 0);
    nameCtrl->SetValidator(wxTextValidator(wxFILTER_ASCII, &name_));
    oppositeNameCtrl_ =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_OPPOSITE_BRIDGE));
    assert(oppositeNameCtrl_ != 0);
    oppositeNameCtrl_->SetValidator(wxTextValidator(wxFILTER_ASCII,
                                                    &oppositeName_));
    inputBusChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_INPUT_BUS));
    assert(inputBusChoice_ != NULL);
    outputBusChoice_ = dynamic_cast<wxChoice*>(FindWindow(ID_OUTPUT_BUS));
    assert(outputBusChoice_ != NULL);
    bidirectionalBox_ =
        dynamic_cast<wxCheckBox*>(FindWindow(ID_BIDIRECTIONAL));
    assert(bidirectionalBox_ != NULL);
    // Machine tester is used to check legality of the bridge modifications.
    // The modified bridge has to be deleted. Otherwise it will conflict
    // with the modification legality checks.
    // save bridge information and delete the bridges
    machine_ = bridge->machine();
    inputBus_ = WxConversion::toWxString(bridge->sourceBus()->name());
    outputBus_ = WxConversion::toWxString(bridge->destinationBus()->name());
    name_ = WxConversion::toWxString(bridge->name());
    if (opposite != NULL) {
        bidirectional_ = true;
        oppositeName_ = WxConversion::toWxString(opposite->name());
        assert(opposite->sourceBus() == bridge->destinationBus());
        assert(opposite->destinationBus() == bridge->sourceBus());
        delete opposite;
    } else {
        bidirectional_ = false;
    }
    delete bridge;
    // set widget texts
    setTexts();
    TransferDataToWindow();
}
References assert, MDFView::canvas(), MachineCanvasTool::deactivate(), MachineCanvas::tool(), and WxConversion::toWxString().
~BridgeDialog()
BridgeDialog::~BridgeDialog () virtual
The Destructor.
Definition at line 154 of file BridgeDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * BridgeDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the dialog window contents.
This method was initially generated with wxDesigner, thus the ugly code and too long lines.
Returns
Main sizer of the created contents.
Parameters
parent The dialog window.
call_fit If true, fits the contents inside the dialog.
set_sizer If true, sets the main sizer as dialog contents.
Definition at line 469 of file BridgeDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxFlexGridSizer *item2 = new wxFlexGridSizer( 2, 0, 0 );
    wxStaticText *item3 = new wxStaticText( parent, ID_LABEL_NAME, wxT("Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALL, 5 );
    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_NAME, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item5 = new wxStaticText( parent, ID_LABEL_INPUT_BUS, wxT("Input Bus:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALL, 5 );
    wxString *strs6 = (wxString*) NULL;
    wxChoice *item6 = new wxChoice( parent, ID_INPUT_BUS, wxDefaultPosition, wxSize(100,-1), 0, strs6, 0 );
    item2->Add( item6, 0, wxGROW|wxALL, 5 );
    wxStaticText *item7 = new wxStaticText( parent, ID_LABEL_OUTPUT_BUS, wxT("Output Bus:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALL, 5 );
    wxString *strs8 = (wxString*) NULL;
    wxChoice *item8 = new wxChoice( parent, ID_OUTPUT_BUS, wxDefaultPosition, wxSize(100,-1), 0, strs8, 0 );
    item2->Add( item8, 0, wxGROW|wxALL, 5 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
    wxBoxSizer *item9 = new wxBoxSizer( wxVERTICAL );
    wxCheckBox *item10 = new wxCheckBox( parent, ID_BIDIRECTIONAL, wxT("Bidirectional"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );
    item9->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item11 = new wxStaticText( parent, ID_LABEL_OPPOSITE_NAME, wxT("Opposite Bridge Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxGROW, 15 );
    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_OPPOSITE_BRIDGE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item12, 0, wxGROW|wxALL, 5 );
    item1->Add( item9, 0, wxGROW|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item13 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item13, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item14 = new wxGridSizer( 2, 0, 0 );
    wxButton *item15 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALL, 5 );
    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );
    wxButton *item17 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item18 = new wxButton( parent, wxID_CANCEL, wxT("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );
    item14->Add( item16, 0, wxALL, 5 );
    item0->Add( item14, 0, wxALIGN_CENTER, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_BIDIRECTIONAL, ID_HELP, ID_INPUT_BUS, ID_LABEL_INPUT_BUS, ID_LABEL_NAME, ID_LABEL_OPPOSITE_NAME, ID_LABEL_OUTPUT_BUS, ID_LINE, ID_NAME, ID_OPPOSITE_BRIDGE, and ID_OUTPUT_BUS.
onBidirectional()
void BridgeDialog::onBidirectional (wxCommandEvent &) private
Handles changes in bidirectional control.
When bdirectional is on, the opposite bridge name control is enabled, otherwise it is disabled.
Definition at line 444 of file BridgeDialog.cc.
{
    if (bidirectionalBox_->IsChecked()) {
        oppositeNameCtrl_->Enable();
        bidirectional_ = true;
    } else {
        oppositeNameCtrl_->Disable();
        bidirectional_ = false;
    }
    wxCommandEvent dummy;
    onName(dummy);
}
References bidirectional_, bidirectionalBox_, dummy, onName(), and oppositeNameCtrl_.
onCancel()
void BridgeDialog::onCancel (wxCommandEvent &) private
Definition at line 354 of file BridgeDialog.cc.
{
    MDFView* view =
        dynamic_cast<MDFView*>(wxGetApp().docManager()->GetCurrentView());
    view->canvas()->tool()->activate();
    EndModal(wxID_CANCEL);
}
References MachineCanvasTool::activate(), MDFView::canvas(), and MachineCanvas::tool().
onHelp()
void BridgeDialog::onHelp (wxCommandEvent & event) private
onInputBus()
void BridgeDialog::onInputBus (wxCommandEvent &) private
Handles changes in the input bus control.
Output bus choicer is updated to contain only valid output busses for the selected input bus.
Definition at line 408 of file BridgeDialog.cc.
{
    string outputBus =
        WxConversion::toString(outputBusChoice_->GetStringSelection());
    string inputBus =
        WxConversion::toString(inputBusChoice_->GetStringSelection());
    MachineTester tester(*machine_);
    Machine::BusNavigator navigator = machine_->busNavigator();
    Bus* source = navigator.item(inputBus);
    Bus* destination = navigator.item(outputBus);
    if (!tester.canBridge(*source, *destination)) {
        outputBus = "";
        for (int i=0; i < navigator.count(); i++) {
            if (tester.canBridge(*source, *navigator.item(i))) {
                outputBus = navigator.item(i)->name();
                break;
            }
        }
        assert(outputBus != "");
        outputBus_ = WxConversion::toWxString(outputBus);
    }
    inputBus_ = WxConversion::toWxString(inputBus);
    updateBusChoices();
}
References assert, TTAMachine::Machine::busNavigator(), MachineTester::canBridge(), TTAMachine::Machine::Navigator< ComponentType >::count(), inputBus_, inputBusChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, outputBus_, outputBusChoice_, WxConversion::toString(), WxConversion::toWxString(), and updateBusChoices().
onName()
void BridgeDialog::onName (wxCommandEvent &) private
Checks whether name field is empty and disables OK button of the dialog if it is.
Definition at line 366 of file BridgeDialog.cc.
{
    wxTextCtrl* nameCtrl = dynamic_cast<wxTextCtrl*>(FindWindow(ID_NAME));
    wxTextCtrl* oppNameCtrl =
        dynamic_cast<wxTextCtrl*>(FindWindow(ID_OPPOSITE_BRIDGE));
    wxString name = nameCtrl->GetValue();
    wxString trimmedName = name.Trim(false).Trim(true);
    wxString oppositeName = oppNameCtrl->GetValue();
    wxString trimmedOppositeName = oppositeName.Trim(false).Trim(true);
    if (trimmedName == _T("") ||
        (bidirectional_ && trimmedOppositeName == _T(""))) {
        FindWindow(wxID_OK)->Disable();
    } else {
        FindWindow(wxID_OK)->Enable();
    }
}
References bidirectional_, ID_NAME, and ID_OPPOSITE_BRIDGE.
Referenced by onBidirectional(), and TransferDataToWindow().
onOK()
void BridgeDialog::onOK (wxCommandEvent &) private
Validates input in the controls, and updates the Bridge object.
Definition at line 263 of file BridgeDialog.cc.
{
    if (!Validate()) {
        return;
    }
    if (!TransferDataFromWindow()) {
        return;
    }
    string trimmedName = WxConversion::toString(name_.Trim(false).Trim(true));
    string trimmedOppName =
        WxConversion::toString(oppositeName_.Trim(false).Trim(true));
    // Check the name validity.
    if (!MachineTester::isValidComponentName(trimmedName) ||
        (bidirectional_ &&
         !MachineTester::isValidComponentName(trimmedOppName))) {
        ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
        format message =
            prodeTexts->text(ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME);
        InformationDialog warning(
            this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Check that the opposing bridge names aren't same.
    if (bidirectional_ && trimmedName == trimmedOppName) {
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format message =
            generator->text(ProDeTextGenerator::MSG_ERROR_BRIDGE_NAMES);
        WarningDialog warning(this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    Machine::BridgeNavigator navigator = machine_->bridgeNavigator();
    // Check that the opposite bridge name is not reserved.
    if (bidirectional_ && navigator.hasItem(trimmedOppName)) {
        ProDeTextGenerator* generator =
            ProDeTextGenerator::instance();
        format message =
            generator->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        string component =
            generator->text(ProDeTextGenerator::COMP_A_BRIDGE).str();
        message % trimmedOppName % component;
        WarningDialog warning(this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    // Check that the bridge name is not reserved.
    if (navigator.hasItem(trimmedName)) {
        ProDeTextGenerator* generator =
            ProDeTextGenerator::instance();
        format message =
            generator->text(ProDeTextGenerator::MSG_ERROR_SAME_NAME);
        string acomponent =
            generator->text(ProDeTextGenerator::COMP_A_BRIDGE).str();
        string machine =
            generator->text(ProDeTextGenerator::COMP_MACHINE).str();
        string component =
            generator->text(ProDeTextGenerator::COMP_BRIDGE).str();
        message % trimmedName % acomponent % machine % component;
        WarningDialog warning(this, WxConversion::toWxString(message.str()));
        warning.ShowModal();
        return;
    }
    Machine::BusNavigator busNavigator = machine_->busNavigator();
    MachineTester tester(*machine_);
    Bus* source = busNavigator.item(WxConversion::toString(inputBus_));
    Bus* destination = busNavigator.item(WxConversion::toString(outputBus_));
    // Add the new/modified bridges to the machine.
    new Bridge(trimmedName, *source, *destination);
    if (bidirectional_ && tester.canBridge(*destination, *source)) {
        new Bridge(trimmedOppName, *destination, *source);
    }
    MDFView* view =
        dynamic_cast<MDFView*>(wxGetApp().docManager()->GetCurrentView());
    view->canvas()->tool()->activate();
    EndModal(wxID_OK);
}
References MachineCanvasTool::activate(), bidirectional_, TTAMachine::Machine::bridgeNavigator(), TTAMachine::Machine::busNavigator(), MachineTester::canBridge(), MDFView::canvas(), ProDeTextGenerator::COMP_A_BRIDGE, ProDeTextGenerator::COMP_BRIDGE, ProDeTextGenerator::COMP_MACHINE, TTAMachine::Machine::Navigator< ComponentType >::hasItem(), inputBus_, ProDeTextGenerator::instance(), MachineTester::isValidComponentName(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, machine_, ProDeTextGenerator::MSG_ERROR_BRIDGE_NAMES, ProDeTextGenerator::MSG_ERROR_ILLEGAL_NAME, ProDeTextGenerator::MSG_ERROR_SAME_NAME, name_, oppositeName_, outputBus_, Texts::TextGenerator::text(), MachineCanvas::tool(), WxConversion::toString(), and WxConversion::toWxString().
onOutputBus()
void BridgeDialog::onOutputBus (wxCommandEvent &) private
Handles changes in input bus control.
Checks that input bus is not the same as output bus. If it is the output bus is changed to the previous value of the input bus.
Definition at line 394 of file BridgeDialog.cc.
{
    wxString outputBus = outputBusChoice_->GetStringSelection();
    outputBus_ = outputBus;
    updateBusChoices();
}
References outputBus_, outputBusChoice_, and updateBusChoices().
setTexts()
void BridgeDialog::setTexts () private
Sets texts for widgets.
Definition at line 162 of file BridgeDialog.cc.
                       {
    GUITextGenerator* generator = GUITextGenerator::instance();
    ProDeTextGenerator* prodeTexts = ProDeTextGenerator::instance();
    // Dialog title
    format fmt = prodeTexts->text(ProDeTextGenerator::TXT_BRIDGE_DIALOG_TITLE);
    SetTitle(WxConversion::toWxString(fmt.str()));
    // buttons
    WidgetTools::setLabel(generator, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    WidgetTools::setLabel(generator, FindWindow(wxID_CANCEL),
                          GUITextGenerator::TXT_BUTTON_CANCEL);
    WidgetTools::setLabel(generator, FindWindow(ID_HELP),
                          GUITextGenerator::TXT_BUTTON_HELP);
    // widget labels
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_NAME),
                          ProDeTextGenerator::TXT_LABEL_NAME);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_OPPOSITE_NAME),
                          ProDeTextGenerator::TXT_LABEL_OPPOSITE_BRIDGE);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_LABEL_INPUT_BUS),
                          ProDeTextGenerator::TXT_LABEL_INPUT_BUS);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_OUTPUT_BUS),
                          ProDeTextGenerator::TXT_LABEL_OUTPUT_BUS);
    WidgetTools::setLabel(prodeTexts, FindWindow(ID_BIDIRECTIONAL),
                          ProDeTextGenerator::TXT_LABEL_BIDIRECTIONAL);
}
References ID_BIDIRECTIONAL, ID_HELP, ID_LABEL_INPUT_BUS, ID_LABEL_NAME, ID_LABEL_OPPOSITE_NAME, ID_OUTPUT_BUS, GUITextGenerator::instance(), ProDeTextGenerator::instance(), WidgetTools::setLabel(), Texts::TextGenerator::text(), WxConversion::toWxString(), ProDeTextGenerator::TXT_BRIDGE_DIALOG_TITLE, GUITextGenerator::TXT_BUTTON_CANCEL, GUITextGenerator::TXT_BUTTON_HELP, GUITextGenerator::TXT_BUTTON_OK, ProDeTextGenerator::TXT_LABEL_BIDIRECTIONAL, ProDeTextGenerator::TXT_LABEL_INPUT_BUS, ProDeTextGenerator::TXT_LABEL_NAME, ProDeTextGenerator::TXT_LABEL_OPPOSITE_BRIDGE, and ProDeTextGenerator::TXT_LABEL_OUTPUT_BUS.
TransferDataToWindow()
bool BridgeDialog::TransferDataToWindow () private virtual
Transfers data from the bridge object(s) to the dialog widgets.
Returns
False, if an error occured in the transfer, true otherwise.
Definition at line 203 of file BridgeDialog.cc.
{
   bidirectionalBox_->SetValue(bidirectional_);
    if (bidirectional_) {
        oppositeNameCtrl_->Enable();
    } else {
        oppositeNameCtrl_->Disable();
    }
    updateBusChoices();
    bool transferResult = wxWindow::TransferDataToWindow();
    // Force update of the OK-button enabled/disabled state.
    wxCommandEvent dummy;
    onName(dummy);
    return transferResult;
}
References bidirectional_, bidirectionalBox_, dummy, onName(), oppositeNameCtrl_, and updateBusChoices().
updateBusChoices()
void BridgeDialog::updateBusChoices () private
Updates the bus choicers.
Definition at line 228 of file BridgeDialog.cc.
{
    Machine::BusNavigator navigator = machine_->busNavigator();
    MachineTester tester(*machine_);
    Bus* source = navigator.item(WxConversion::toString(inputBus_));
    // Add input buses which can be bridged.
    inputBusChoice_->Clear();
    for (int i = 0;i < navigator.count(); i++) {
        wxString busName = WxConversion::toWxString(navigator.item(i)->name());
        for (int j = 0;j < navigator.count(); j++) {
            if (tester.canBridge(*navigator.item(i), *navigator.item(j))) {
                inputBusChoice_->Append(busName);
                break;
            }
        }
    }
    inputBusChoice_->SetStringSelection(inputBus_);
    // Add outputbuses which are legal for the current input bus.
    outputBusChoice_->Clear();
    for (int i = 0;i < navigator.count(); i++) {
        wxString busName = WxConversion::toWxString(navigator.item(i)->name());
        if (tester.canBridge(*source, *navigator.item(i))) {
            outputBusChoice_->Append(busName);
        }
    }
    outputBusChoice_->SetStringSelection(outputBus_);
}
References TTAMachine::Machine::busNavigator(), MachineTester::canBridge(), TTAMachine::Machine::Navigator< ComponentType >::count(), inputBus_, inputBusChoice_, TTAMachine::Machine::Navigator< ComponentType >::item(), machine_, outputBus_, outputBusChoice_, WxConversion::toString(), and WxConversion::toWxString().
Referenced by onInputBus(), onOutputBus(), and TransferDataToWindow().
Member Data Documentation
adding_
bool BridgeDialog::adding_ private
Indicates whether we are adding a bridge or not.
Definition at line 93 of file BridgeDialog.hh.
bidirectional_
bool BridgeDialog::bidirectional_ private
Indicates whether we are modifying a bidirectional bridge or not.
Definition at line 95 of file BridgeDialog.hh.
Referenced by onBidirectional(), onName(), onOK(), and TransferDataToWindow().
bidirectionalBox_
wxCheckBox* BridgeDialog::bidirectionalBox_ private
Indicates whether the bridge is bidirectional.
Definition at line 90 of file BridgeDialog.hh.
Referenced by onBidirectional(), and TransferDataToWindow().
inputBus_
wxString BridgeDialog::inputBus_ private
Name of the bridge input bus.
Definition at line 79 of file BridgeDialog.hh.
Referenced by onInputBus(), onOK(), and updateBusChoices().
inputBusChoice_
wxChoice* BridgeDialog::inputBusChoice_ private
Input bus choice control.
Definition at line 86 of file BridgeDialog.hh.
Referenced by onInputBus(), and updateBusChoices().
machine_
TTAMachine::Machine* BridgeDialog::machine_ private
Parent machine of the bridge(s).
Definition at line 72 of file BridgeDialog.hh.
Referenced by onInputBus(), onOK(), and updateBusChoices().
name_
wxString BridgeDialog::name_ private
Name of the bridge.
Definition at line 74 of file BridgeDialog.hh.
Referenced by onOK().
oppositeName_
wxString BridgeDialog::oppositeName_ private
Name of the opposite bridge.
Definition at line 76 of file BridgeDialog.hh.
Referenced by onOK().
oppositeNameCtrl_
wxTextCtrl* BridgeDialog::oppositeNameCtrl_ private
Opposite name control.
Definition at line 84 of file BridgeDialog.hh.
Referenced by onBidirectional(), and TransferDataToWindow().
outputBus_
wxString BridgeDialog::outputBus_ private
Name of the bridge output bus.
Definition at line 81 of file BridgeDialog.hh.
Referenced by onInputBus(), onOK(), onOutputBus(), and updateBusChoices().
outputBusChoice_
wxChoice* BridgeDialog::outputBusChoice_ private
Output bus choice control.
Definition at line 88 of file BridgeDialog.hh.
Referenced by onInputBus(), onOutputBus(), and updateBusChoices().
The documentation for this class was generated from the following files:
BridgeDialog.hh
BridgeDialog.cc