OpenASIP: RemoteController Class Reference
RemoteController Class Reference abstract
#include <RemoteController.hh>
Public Types
typedef MinimumAddressableUnit MAU
Public Types inherited from TTASimulationController
enum SimulationStatus {
STA_INITIALIZING , STA_INITIALIZED , STA_RUNNING , STA_STOPPED ,
STA_FINISHED
}
The states of simulation.
Public Member Functions
RemoteController (SimulatorFrontend &frontend, const TTAMachine::Machine &machine, const TTAProgram::Program &program)
virtual void writeMem (Word address, MAU data, const AddressSpace &)=0
virtual MAU readMem (Word address, const AddressSpace &)=0
virtual void loadIMemImage ()
virtual void writeIMem (const char *data, int size)=0
virtual void step (double count=1)=0
virtual void next (int count=1)=0
virtual void run ()=0
virtual void runUntil (UIntWord address)=0
virtual void reset ()=0
virtual std::string registerFileValue (const std::string &rfName, int registerIndex=-1)=0
virtual SimValue immediateUnitRegisterValue (const std::string &iuName, int index=-1)=0
virtual SimValue FUPortValue (const std::string &fuName, const std::string &portName)=0
virtual InstructionAddress programCounter () const =0
Public Member Functions inherited from TTASimulationController
TTASimulationController (SimulatorFrontend &frontend, const TTAMachine::Machine &machine, const TTAProgram::Program &program)
virtual ~TTASimulationController ()
virtual void prepareToStop (StopReason reason)
virtual unsigned int stopReasonCount () const
virtual StopReason stopReason (unsigned int index) const
virtual SimulationStatus state () const
virtual InstructionAddress lastExecutedInstruction (int coreId=-1) const
virtual ClockCycleCount clockCount () const
virtual MemorySystem & memorySystem (int coreId=-1)
virtual SimulatorFrontend & frontend ()
virtual bool automaticFinishImpossible () const
virtual std::set< InstructionAddress > findProgramExitPoints (const TTAProgram::Program &program, const TTAMachine::Machine &machine) const
Protected Attributes
std::set< InstructionAddress > exitPoints
std::ostringstream imemImage
Protected Attributes inherited from TTASimulationController
SimulatorFrontend & frontend_
Reference to the simulator frontend.
const TTAMachine::Machine & sourceMachine_
The simulated Machine Object Model.
const TTAProgram::Program & program_
Program object model of the simulated program.
bool stopRequested_
Flag indicating that simulation should stop.
StopReasonContainer stopReasons_
The set of reasons the simulation was stopped.
SimulationStatus state_
The current state of the simulation.
ClockCycleCount clockCount_
How many clock cycles have been simulated.
std::vector< InstructionAddress > lastExecutedInstruction_
The address of the last executed instruction.
InstructionAddress initialPC_
The address of the first executed instruction.
bool automaticFinishImpossible_
If this is true, simulation cannot be finished automatically.
InstructionAddress firstIllegalInstructionIndex_
The index of the first illegal instruction in the instruction sequence.
Additional Inherited Members
Protected Types inherited from TTASimulationController
typedef std::set< StopReason > StopReasonContainer
The container type for reasons why simulation stop was requested.
Protected Member Functions inherited from TTASimulationController
TTASimulationController (const TTASimulationController &)
Copying not allowed.
TTASimulationController & operator= (const TTASimulationController &)
Assignment not allowed.
Detailed Description
RemoteController is a "simulation" controller base class for debuggers on hardware implementations.
RemoteController is a base class for the TCE built-in debugger and the custom debugger classes. It adds virtual interfaces to TTASimulationController, that are needed to integrate an FPGA or ASIC to the TCE debugging tools. RemoteController is a interface class, and cannot be instantiated.
Definition at line 48 of file RemoteController.hh.
Member Typedef Documentation
MAU
typedef MinimumAddressableUnit RemoteController::MAU
Definition at line 50 of file RemoteController.hh.
Constructor & Destructor Documentation
RemoteController()
RemoteController::RemoteController (SimulatorFrontend & frontend, const TTAMachine::Machine & machine, const TTAProgram::Program & program)
Definition at line 48 of file RemoteController.cc.
                                          :
        TTASimulationController(frontend, machine, program),
        imemImage(std::ostringstream::binary) {
    exitPoints = findProgramExitPoints(program, machine);
}
References exitPoints, TTASimulationController::findProgramExitPoints(), machine, and program.
Member Function Documentation
FUPortValue()
virtual SimValue RemoteController::FUPortValue (const std::string & fuName, const std::string & portName) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
immediateUnitRegisterValue()
virtual SimValue RemoteController::immediateUnitRegisterValue (const std::string & iuName, int index = -1) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
loadIMemImage()
void RemoteController::loadIMemImage () virtual
Create and load instruction memory image from current program.
This function generates a binary image of the instruction memory, and stores it in cache. It is then written with loadInstructions(), which in turn call the pure virtual writeIMem, that subclasses need to implement.
Definition at line 58 of file RemoteController.cc.
{
    ProgramImageGenerator thePIG;
    BinaryEncoding *theBE;
    TPEF::Binary *binary;
    // TODO. better name from somewhere?
    std::string programName("the program");
    // clear the old image
    imemImage.str("");
    // Binary encoding of the instruction sream
    // TODO: loading of instruction compressors would happen here?
    BEMGenerator theBEMGen(sourceMachine_);
    theBE = theBEMGen.generate();
    TTAProgram::ProgramWriter writer(program_);
    binary = writer.createBinary();
    ProgramImageGenerator::TPEFMap tmap;
    // TODO: have some actual name for this program?
    tmap[programName] = binary;
    thePIG.loadBEM(*theBE);
    thePIG.loadMachine(sourceMachine_);
    thePIG.loadPrograms(tmap);
    // clear the old image
    // put the instructions into imemImage
    thePIG.generateProgramImage(
        programName, imemImage,
        ProgramImageGenerator::BINARY);
    writeIMem(imemImage.str().c_str(), imemImage.str().size());
    delete binary;
    delete theBE;
    return;
}
References ProgramImageGenerator::BINARY, TTAProgram::ProgramWriter::createBinary(), BEMGenerator::generate(), ProgramImageGenerator::generateProgramImage(), imemImage, ProgramImageGenerator::loadBEM(), ProgramImageGenerator::loadMachine(), ProgramImageGenerator::loadPrograms(), TTASimulationController::program_, TTASimulationController::sourceMachine_, and writeIMem().
next()
virtual void RemoteController::next (int count = 1) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
programCounter()
virtual InstructionAddress RemoteController::programCounter () const pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
readMem()
virtual MAU RemoteController::readMem (Word address, const AddressSpace &) pure virtual
Read data from physical memory.
Parameters
address TTA's view of the memory address from which to read @space the address space from which to read the data.
Returns
one MAU of data to write. (TODO: is return value masked or not?)
Implemented in CustomDBGController, and TCEDBGController.
Referenced by RemoteMemory::read().
registerFileValue()
virtual std::string RemoteController::registerFileValue (const std::string & rfName, int registerIndex = -1) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
reset()
virtual void RemoteController::reset () pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
run()
virtual void RemoteController::run () pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
runUntil()
virtual void RemoteController::runUntil (UIntWord address) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
step()
virtual void RemoteController::step (double count = 1) pure virtual
Implements TTASimulationController.
Implemented in CustomDBGController, and TCEDBGController.
writeIMem()
virtual void RemoteController::writeIMem (const char * data, int size) pure virtual
Write to phyical instruction memory.
Parameters
address TTA's view of the memory address to which to write @data buffer of raw data to write to instruction memory @size the size of the data buffer, in bytes
Implemented in CustomDBGController, and TCEDBGController.
Referenced by loadIMemImage().
writeMem()
virtual void RemoteController::writeMem (Word address, MAU data, const AddressSpace &) pure virtual
Write data to physical memory.
Parameters
address TTA's view of the memory address to which to write @data one MAU of data to write. Needs to be masked, if MAU is less than maximum MAU size. @space the address space in which to write the data.
Implemented in CustomDBGController, and TCEDBGController.
Referenced by RemoteMemory::write().
Member Data Documentation
exitPoints
std::set<InstructionAddress> RemoteController::exitPoints protected
Definition at line 120 of file RemoteController.hh.
Referenced by RemoteController().
imemImage
std::ostringstream RemoteController::imemImage protected
Definition at line 121 of file RemoteController.hh.
Referenced by loadIMemImage().
The documentation for this class was generated from the following files:
RemoteController.hh
RemoteController.cc