OpenASIP: MoveNodeSet Class Reference
MoveNodeSet Class Reference
#include <MoveNodeSet.hh>
Public Member Functions
MoveNodeSet ()
int count () const
MoveNode & at (int index)
void addMoveNode (MoveNode &)
void removeMoveNode (MoveNode &)
std::string toString () const
std::vector< MoveNode * >::iterator begin ()
std::vector< MoveNode * >::iterator end ()
Private Attributes
std::vector< MoveNode * > moveNodes_
Detailed Description
Definition at line 41 of file MoveNodeSet.hh.
Constructor & Destructor Documentation
MoveNodeSet()
MoveNodeSet::MoveNodeSet ()
Fairly empty constructor.
Definition at line 38 of file MoveNodeSet.cc.
{
 }
Member Function Documentation
addMoveNode()
void MoveNodeSet::addMoveNode (MoveNode & newMove)
Add MoveNode to the MoveNodeSet
Parameters
newMove New MoveNode to add to set
Definition at line 62 of file MoveNodeSet.cc.
{
    for (std::vector<MoveNode*>::iterator i = moveNodes_.begin();
         i != moveNodes_.end(); i++) {
        if (*i == &newMove) {
            return;  // already in the set. please even play to be a set if named a set
        }
    }
    moveNodes_.push_back(&newMove);
}
References moveNodes_.
Referenced by ProgramOperation::addInputNode(), ProgramOperation::addOutputNode(), SequentialScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperation(), and SequentialScheduler::scheduleOperation().
at()
MoveNode & MoveNodeSet::at (int index) inline
Referenced by MemoryAliasAnalyzer::addressOperandMove(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), BFSwapOperands::BFSwapOperands(), ExecutionPipelineResource::canAssignSource(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), BasicBlockScheduler::findTriggerFromUnit(), StackAliasAnalyzer::getStackOffset(), OffsetAliasAnalyzer::isAddressTraceable(), BF2Scheduler::preAllocateFunctionUnits(), BF2Scheduler::preAllocateFunctionUnits(), BF2Scheduler::reservePreallocatedFUs(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), BF2Scheduler::swapToUntrigger(), and LoopAnalyzer::tryTrackCommonAncestor().
begin()
std::vector< MoveNode * >::iterator MoveNodeSet::begin () inline
Definition at line 51 of file MoveNodeSet.hh.
{ return moveNodes_.begin(); }
References moveNodes_.
Referenced by ExecutionPipelineResource::nodeOfInputPort().
count()
int MoveNodeSet::count () const inline
Referenced by MemoryAliasAnalyzer::addressOperandMove(), LoopAnalyzer::analyze(), OffsetAliasAnalyzer::analyze(), BFSwapOperands::BFSwapOperands(), ExecutionPipelineResource::canAssignSource(), BF2Scheduler::countLoopInvariantValueUsages(), MemoryAliasAnalyzer::detectConstantScale(), LoopAnalyzer::findEndCond(), MemoryAliasAnalyzer::findIncrement(), LoopAnalyzer::findInitAndUpdate(), DataDependenceGraph::findLoopIndexUpdate(), DataDependenceGraph::findLoopLimitAndIndex(), StackAliasAnalyzer::getStackOffset(), OffsetAliasAnalyzer::isAddressTraceable(), BF2Scheduler::preAllocateFunctionUnits(), BF2Scheduler::preAllocateFunctionUnits(), BF2Scheduler::reservePreallocatedFUs(), MemoryAliasAnalyzer::searchLoopIndexBasedIncrement(), BF2Scheduler::swapToUntrigger(), toString(), and LoopAnalyzer::tryTrackCommonAncestor().
end()
std::vector< MoveNode * >::iterator MoveNodeSet::end () inline
Definition at line 52 of file MoveNodeSet.hh.
{ return moveNodes_.end(); }
References moveNodes_.
removeMoveNode()
void MoveNodeSet::removeMoveNode (MoveNode & node)
Definition at line 73 of file MoveNodeSet.cc.
{
    for (std::vector<MoveNode*>::iterator i = moveNodes_.begin();
         i != moveNodes_.end(); i++) {
        if (*i == &node) {
            moveNodes_.erase(i);
            return;
        }
    }
    throw IllegalRegistration(
        __FILE__,__LINE__,__func__,"MoveNode not in MoveNodeSet");
}
References __func__, and moveNodes_.
Referenced by ProgramOperation::removeInputNode(), and ProgramOperation::removeOutputNode().
toString()
std::string MoveNodeSet::toString () const
Returns the disassembly of the moves in the set in a single line.
Returns
the disassembly.
Definition at line 48 of file MoveNodeSet.cc.
{
    std::string disasm = "";
    for (int i = 0; i < count(); ++i) {
        disasm += moveNodes_.at(i)->toString() + " ; ";
    }
    return disasm;
}
References count(), and moveNodes_.
Member Data Documentation
moveNodes_
std::vector<MoveNode*> MoveNodeSet::moveNodes_ private
Definition at line 55 of file MoveNodeSet.hh.
Referenced by addMoveNode(), begin(), end(), removeMoveNode(), and toString().
The documentation for this class was generated from the following files:
MoveNodeSet.hh
MoveNodeSet.cc