OpenASIP: CreateHDBCmdLineOptions Class Reference
CreateHDBCmdLineOptions Class Reference
#include <CreateHDBCmdLineOptions.hh>
Public Member Functions
CreateHDBCmdLineOptions ()
virtual ~CreateHDBCmdLineOptions ()
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Private Member Functions
CreateHDBCmdLineOptions (const CreateHDBCmdLineOptions &)
Copying not allowed.
CreateHDBCmdLineOptions & operator= (const CreateHDBCmdLineOptions &)
Assignment not allowed.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Command line option class for createhdb.
Definition at line 43 of file CreateHDBCmdLineOptions.hh.
Constructor & Destructor Documentation
CreateHDBCmdLineOptions() [1/2]
CreateHDBCmdLineOptions::CreateHDBCmdLineOptions ()
Constructor.
Definition at line 42 of file CreateHDBCmdLineOptions.cc.
                                                 : CmdLineOptions("") {
}
~CreateHDBCmdLineOptions()
CreateHDBCmdLineOptions::~CreateHDBCmdLineOptions () virtual
Destructor.
Definition at line 49 of file CreateHDBCmdLineOptions.cc.
{
}
CreateHDBCmdLineOptions() [2/2]
CreateHDBCmdLineOptions::CreateHDBCmdLineOptions (const CreateHDBCmdLineOptions &) private
Copying not allowed.
Member Function Documentation
operator=()
CreateHDBCmdLineOptions & CreateHDBCmdLineOptions::operator= (const CreateHDBCmdLineOptions &) private
Assignment not allowed.
printHelp()
void CreateHDBCmdLineOptions::printHelp () const virtual
Prints the help menu of the program.
Reimplemented from CmdLineOptions.
Definition at line 65 of file CreateHDBCmdLineOptions.cc.
{
    printVersion();
    std::cout << std::endl
              << "usage: createhdb [target file] "
              << std::endl
              << std::endl
              << "The target file is mandatory."
              << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void CreateHDBCmdLineOptions::printVersion () const virtual
Prints the version of the program.
Implements CmdLineOptions.
Definition at line 56 of file CreateHDBCmdLineOptions.cc.
{
    std::cout << "CreateHDB - OpenASIP Hardware Database (HDB) initializer "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
The documentation for this class was generated from the following files:
CreateHDBCmdLineOptions.hh
CreateHDBCmdLineOptions.cc