OpenASIP: ScheduleEstimator Class Reference
ScheduleEstimator Class Reference
#include <ScheduleEstimator.hh>
Public Member Functions
ScheduleEstimator (InterPassData &data)
virtual void handleControlFlowGraph (ControlFlowGraph &cfg, const TTAMachine::Machine &mach) override
virtual std::string shortDescription () const
Public Member Functions inherited from ControlFlowGraphPass
ControlFlowGraphPass (InterPassData &data)
virtual ~ControlFlowGraphPass ()
void executeBasicBlockPass (ControlFlowGraph &cfg, const TTAMachine::Machine &targetMachine, BasicBlockPass &bbPass)
Public Member Functions inherited from SchedulerPass
SchedulerPass (InterPassData &data)
virtual ~SchedulerPass ()
InterPassData & interPassData ()
virtual std::string longDescription () const
Static Public Member Functions
static int maximumSizeOfBB (TTAProgram::BasicBlock &bb, const TTAMachine::Machine &mach)
Detailed Description
Definition at line 46 of file ScheduleEstimator.hh.
Constructor & Destructor Documentation
ScheduleEstimator()
ScheduleEstimator::ScheduleEstimator (InterPassData & data) inline
Definition at line 49 of file ScheduleEstimator.hh.
: ControlFlowGraphPass(data) {}
Member Function Documentation
handleControlFlowGraph()
void ScheduleEstimator::handleControlFlowGraph (ControlFlowGraph & cfg, const TTAMachine::Machine & targetMachine) override virtual
Handles a single control flow graph.
The pass should work with any kind of control flow graph, it should not assume the CFG represents a whole procedure, for example.
Parameters
cfg The control flow graph to handle.
machine The target machine if any. (NullMachine::instance() if target machine is irrelevant).
Exceptions
In case handling is unsuccesful for any reason (cfg might still get modified).
Reimplemented from ControlFlowGraphPass.
Definition at line 85 of file ScheduleEstimator.cc.
{
    for (int bbIndex = 0; bbIndex < cfg.nodeCount(); ++bbIndex) {
        BasicBlockNode& bbn = cfg.node(bbIndex);
        if (!bbn.isNormalBB()) {
            bbn.setMaximumSize(0);
        } else {
            auto& bb = bbn.basicBlock();
            bbn.setMaximumSize(
                bbn.isScheduled() ?
                bb.instructionCount() - bb.skippedFirstInstructions() :
                maximumSizeOfBB(bb, mach));
        }
    }
}
References BasicBlockNode::basicBlock(), BasicBlockNode::isNormalBB(), BasicBlockNode::isScheduled(), maximumSizeOfBB(), BoostGraph< GraphNode, GraphEdge >::node(), BoostGraph< GraphNode, GraphEdge >::nodeCount(), and BasicBlockNode::setMaximumSize().
Referenced by BBSchedulerController::handleCFGDDG().
maximumSizeOfBB()
int ScheduleEstimator::maximumSizeOfBB (TTAProgram::BasicBlock & bb, const TTAMachine::Machine & mach) static
Definition at line 49 of file ScheduleEstimator.cc.
{
    auto tempRegFiles = MachineConnectivityCheck::tempRegisterFiles(mach);
    int tempRegCount = tempRegFiles.size();
    int size = 0;
    int iCount = bb.instructionCount();
    for (int i = 0; i < iCount; i++) {
        auto& ins = bb[i];
        for (int j = 0; j < ins.moveCount(); j++) {
            size++;
            // temp reg copies may make schedule longer.
            size += tempRegCount;
            auto& m = ins.move(j);
            auto& src = m.source();
            if (m.isControlFlowMove()) {
                size += mach.controlUnit()->delaySlots() + 1;
            }
            if (src.isFUPort() && !src.isRA()) {
                const Operation& o = src.hintOperation();
                TCEString opName = o.name();
                int lat = MachineInfo::maxLatency(mach,opName);
                if (lat > 0) {
                    size += lat-1;
                }
            }
        }
    }
    return size;
}
References TTAMachine::Machine::controlUnit(), TTAMachine::ControlUnit::delaySlots(), TTAProgram::CodeSnippet::instructionCount(), MachineInfo::maxLatency(), Operation::name(), and MachineConnectivityCheck::tempRegisterFiles().
Referenced by handleControlFlowGraph().
shortDescription()
virtual std::string ScheduleEstimator::shortDescription () const inline virtual
A short description of the pass, usually the optimization name, such as "basic block scheduler".
Returns
The description as a string.
Implements SchedulerPass.
Definition at line 58 of file ScheduleEstimator.hh.
{ return "Estimates max schedule length"; }
The documentation for this class was generated from the following files:
ScheduleEstimator.hh
ScheduleEstimator.cc