OpenASIP: ProDeSegmentEditPolicy Class Reference
ProDeSegmentEditPolicy Class Reference
#include <ProDeSegmentEditPolicy.hh>
Public Member Functions
ProDeSegmentEditPolicy ()
virtual ~ProDeSegmentEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ComponentCommand * createConnectCmd (Request *request)
ProDeSegmentEditPolicy & operator= (ProDeSegmentEditPolicy &old)
Assignment not allowed.
ProDeSegmentEditPolicy (ProDeSegmentEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a segment EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports. the Request.
Definition at line 49 of file ProDeSegmentEditPolicy.hh.
Constructor & Destructor Documentation
ProDeSegmentEditPolicy() [1/2]
ProDeSegmentEditPolicy::ProDeSegmentEditPolicy ()
The Constructor.
Definition at line 56 of file ProDeSegmentEditPolicy.cc.
                                              : EditPolicy() {
}
~ProDeSegmentEditPolicy()
ProDeSegmentEditPolicy::~ProDeSegmentEditPolicy () virtual
The Destructor.
Definition at line 62 of file ProDeSegmentEditPolicy.cc.
{
}
ProDeSegmentEditPolicy() [2/2]
ProDeSegmentEditPolicy::ProDeSegmentEditPolicy (ProDeSegmentEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeSegmentEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 104 of file ProDeSegmentEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::CONNECT_REQUEST) {
        ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
        assert(cr != NULL);
        EditPart* part = cr->part();
        if (part == NULL) {
            // No selection.
            // Segment can be selected for connecting, return true.
            return true;
        }
        Socket* socket = dynamic_cast<Socket*>(part->model());
        if (socket == NULL) {
            // Segment can be connected only to sockets, return false.
            return false;
        }
        MachineTester tester(*(socket->machine()));
        Segment* segment = dynamic_cast<Segment*>(host_->model());
        if (socket->isConnectedTo(*segment) ||
            tester.canConnect(*socket, *segment)) {
            return true;
        }
        return false;
    } else if (type == Request::STATUS_REQUEST) {
        return true;
    } else if (type == Request::DELETE_REQUEST) {
        return true;
    } else if (type == Request::MODIFY_REQUEST) {
        return true;
    } else {
        return false;
    }
}
References assert, MachineTester::canConnect(), Request::CONNECT_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, TTAMachine::Socket::isConnectedTo(), TTAMachine::Component::machine(), EditPart::model(), Request::MODIFY_REQUEST, ConnectRequest::part(), Request::STATUS_REQUEST, and Request::type().
Referenced by createConnectCmd().
createConnectCmd()
ComponentCommand * ProDeSegmentEditPolicy::createConnectCmd (Request * request) private
Creates a command which connects the selected component to the requested component.
Parameters
request ConnectionRequest with the target component for the connection.
Returns
Command for connecting the selected and requested components.
Definition at line 148 of file ProDeSegmentEditPolicy.cc.
{
    ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
    assert(cr != NULL);
    EditPart* part = cr->part();
    if (canHandle(request)) {
        Segment* segment = dynamic_cast<Segment*>(host_->model());
        Socket* socket = dynamic_cast<Socket*>(part->model());
        if (socket == NULL) {
            return NULL;
        }
        ComponentCommand* cmd = NULL;
        cmd = new SocketBusConnCmd(socket, segment);
        return cmd;
    } else {
        return NULL;
    }
}
References assert, canHandle(), EditPolicy::host_, EditPart::model(), and ConnectRequest::part().
Referenced by getCommand().
getCommand()
ComponentCommand * ProDeSegmentEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Note
ConnectCommand is not yet implemented, thus returns always NULL.
Implements EditPolicy.
Definition at line 73 of file ProDeSegmentEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::CONNECT_REQUEST) {
        return createConnectCmd(request);
    } else if (type == Request::MODIFY_REQUEST) {
        return new ModifyBusCmd(host_->parent());
    } else if (type == Request::DELETE_REQUEST) {
        return new DeleteSegmentCmd(host_);
    } else if (type == Request::STATUS_REQUEST) {
        // Editing segments is unsupported feature => return empty command
        return NULL;
        Segment* segment = dynamic_cast<Segment*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_SEGMENT);
        fmt % segment->name();
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    }
    return NULL;
}
References Request::CONNECT_REQUEST, createConnectCmd(), Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Segment::name(), EditPart::parent(), Request::STATUS_REQUEST, ProDeTextGenerator::STATUS_SEGMENT, Texts::TextGenerator::text(), and Request::type().
operator=()
ProDeSegmentEditPolicy & ProDeSegmentEditPolicy::operator= (ProDeSegmentEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeSegmentEditPolicy.hh
ProDeSegmentEditPolicy.cc