OpenASIP: TPEF::DataSection Class Reference
TPEF::DataSection Class Reference
#include <DataSection.hh>
Public Member Functions
virtual ~DataSection ()
virtual SectionType type () const
virtual Byte byte (const Chunk *chunk) const
virtual Byte byte (Word offset) const
virtual void addByte (Byte aByte)
virtual MinimumAddressableUnit MAU (Word index) const
virtual void addMAU (MinimumAddressableUnit aMAU)
virtual void writeValue (Word index, Word numOfMAUs, unsigned long value)
virtual void writeValue (Word index, Word numOfMAUs, signed long value)
virtual Word length () const
virtual void setDataLength (Word length)
virtual bool isDataSection () const override
Public Member Functions inherited from TPEF::UDataSection
virtual ~UDataSection ()
Public Member Functions inherited from TPEF::RawSection
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
virtual void assureInSection (SectionOffset offset) const
virtual ~RawSection ()
bool empty () const
virtual void setLengthInMAUs (Word length)
virtual Word lengthInMAUs () const
virtual Word bytesToMAUs (Word byteCount) const
virtual Word MAUsToBytes (Word mauCount) const
virtual Word chunkToMAUIndex (const Chunk *chunk) const
Word referredChunkCount () const
Chunk * referredChunk (Word index) const
bool belongsToSection (const Chunk *chunk) const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
DataSection (bool init)
virtual Section * clone () const
virtual void setByte (Word offset, Byte aByte)
Protected Member Functions inherited from TPEF::UDataSection
UDataSection (bool init)
Protected Member Functions inherited from TPEF::RawSection
RawSection ()
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Attributes
std::vector< Byte > data_
Contains the data of data section.
Static Private Attributes
static DataSection proto_
Prototype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Data section for initialized data.
Derives from uninitialized data section so, this is extension of UDataSection.
Definition at line 52 of file DataSection.hh.
Constructor & Destructor Documentation
~DataSection()
TPEF::DataSection::~DataSection () virtual
Destructor.
Definition at line 64 of file DataSection.cc.
{
}
DataSection()
TPEF::DataSection::DataSection (bool init) protected
Constructor.
Parameters
init true if registeration is wanted
Definition at line 51 of file DataSection.cc.
                                  : UDataSection(false) {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagVLen();
    unsetFlagNoBits();
}
References TPEF::Section::registerSection(), TPEF::Section::unsetFlagNoBits(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
addByte()
void TPEF::DataSection::addByte (Byte aByte) virtual
Adds byte of data into section.
Method copies data that is given in parameter.
Parameters
aByte Byte that will be copied into the section.
Definition at line 200 of file DataSection.cc.
{
    data_.push_back(aByte);
}
References data_.
Referenced by addMAU(), TTAProgram::ProgramWriter::createBinary(), TPEF::AOutDataSectionReader::readData(), TPEF::AOutStringSectionReader::readData(), TPEF::TPEFDataSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), setDataLength(), TPEF::StringSection::string2Chunk(), and MachineResourceManager::stringToChunk().
addMAU()
void TPEF::DataSection::addMAU (MinimumAddressableUnit aMAU) virtual
Adds MAU to the end of section.
Parameters
aMAU MAU that will be copied into the section.
Exceptions
OutOfRange If the given value could not fit to the bit count defined by the address space's MAU width (when interpreted as unsigned or signed integer).
Definition at line 150 of file DataSection.cc.
{
    int mauBits = aSpace()->MAU();
    if (MathTools::requiredBits(aMAU) > mauBits) {
        if (MathTools::requiredBitsSigned(aMAU) > mauBits) {
            throw OutOfRange(
                __FILE__, __LINE__, __func__,
                "The given value does not fit to the MAU of address space.");
        }
    }
    // how many bits are left to last byte
    int modulo = mauBits % BYTE_BITWIDTH;
    // write first bits
    if (modulo != 0) {
        mauBits -= modulo;
        addByte(static_cast<Byte>(aMAU >> mauBits));
    }
    // move shifting to right for the next MAU
    mauBits -= BYTE_BITWIDTH;
    // write the rest
    for (; mauBits >= 0;
         mauBits = mauBits - BYTE_BITWIDTH) {
        addByte(static_cast<Byte>(aMAU >> mauBits));
    }
}
References __func__, addByte(), TPEF::Section::aSpace(), BYTE_BITWIDTH, TPEF::ASpaceElement::MAU(), MathTools::requiredBits(), and MathTools::requiredBitsSigned().
Referenced by TTAProgram::ProgramWriter::createDataSections().
byte() [1/2]
Byte TPEF::DataSection::byte (const Chunk * chunk) const virtual
Returns byte from chunk's offset.
Parameters
chunk Chunk containing offset of data.
Returns
Byte from chunk offset.
Reimplemented from TPEF::UDataSection.
Definition at line 114 of file DataSection.cc.
{
    return data_[chunk->offset()];
}
References TPEF::RawSection::chunk(), data_, and TPEF::Chunk::offset().
Referenced by TPEF::TPEFDataSectionWriter::actualWriteData(), TPEF::TPEFStringSectionWriter::actualWriteData(), TPEF::AOutStringSectionReader::readData(), TPEF::TPEFStringSectionReader::readData(), TPEFDumper::section(), and ProgramImageGenerator::writeDataSection().
byte() [2/2]
Byte TPEF::DataSection::byte (Word offset) const virtual
Returns byte from byte offset.
Parameters
offset Offset of data.
Returns
Byte from offset.
Definition at line 188 of file DataSection.cc.
{
    return data_[offset];
}
References data_.
clone()
Section * TPEF::DataSection::clone () const protected virtual
Creates an instance of DataSection.
Returns
Newly created section.
Reimplemented from TPEF::UDataSection.
Reimplemented in TPEF::LEDataSection, and TPEF::StringSection.
Definition at line 103 of file DataSection.cc.
{
    return new DataSection(false);
}
isDataSection()
virtual bool TPEF::DataSection::isDataSection () const inline override virtual
Reimplemented from TPEF::Section.
Definition at line 71 of file DataSection.hh.
{ return true; }
length()
Word TPEF::DataSection::length () const virtual
Returns the size of the data section in bytes.
Returns
Length of data in bytes.
Reimplemented from TPEF::RawSection.
Definition at line 210 of file DataSection.cc.
{
    return data_.size();
}
References data_.
Referenced by TPEF::TPEFDataSectionWriter::actualWriteData(), TPEF::TPEFStringSectionWriter::actualWriteData(), TPEF::StringSection::chunk2String(), TTAProgram::ProgramWriter::createDataSections(), TPEF::AOutRelocationSectionReader::finalize(), TPEF::AOutReader::readData(), TPEF::AOutStringSectionReader::readData(), TPEFDumper::section(), setDataLength(), TPEF::StringSection::string2Chunk(), and ProgramImageGenerator::writeDataSection().
MAU()
MinimumAddressableUnit TPEF::DataSection::MAU (Word index) const virtual
Returns one MAU from section by gived MAU index.
Parameters
index Index of MAU to return.
Returns
One MAU of data section.
Definition at line 125 of file DataSection.cc.
{
    int byteOffset = MAUsToBytes(index);
    int mauInBytes = MAUsToBytes(1);
    MinimumAddressableUnit retVal = 0;
    // read all the bytes to retval
    for(int i = 0; i < mauInBytes; i++) {
        retVal = (retVal << BYTE_BITWIDTH) |
            static_cast<MinimumAddressableUnit>(byte(byteOffset+i));
    }
    return retVal;
}
References BYTE_BITWIDTH, and TPEF::RawSection::MAUsToBytes().
Referenced by TTAProgram::TPEFProgramFactory::createDataMemories(), TPEF::TPEFRelocSectionReader::finalize(), and TPEFDumper::section().
setByte()
void TPEF::DataSection::setByte (Word offset, Byte aByte) protected virtual
Sets value of one byte of data section.
NOTE: Byte here is tpef file byte. (8bits).
Parameters
offset Offset where to write the byte.
aByte Value to write.
Definition at line 86 of file DataSection.cc.
{
    if (offset >= data_.size()) {
        abortWithError(
            "Can't set byte " +
            Conversion::toString(static_cast<int>(aByte)) +
            " to offset: " + Conversion::toString(offset) +
            "\t data section size: " + Conversion::toString(data_.size()));
    }
    data_[offset] = aByte;
}
References abortWithError, data_, and Conversion::toString().
Referenced by writeValue(), TPEF::LEDataSection::writeValue(), writeValue(), and TPEF::LEDataSection::writeValue().
setDataLength()
void TPEF::DataSection::setDataLength (Word aLength) virtual
Tries to set data length.
Can be used only for making section bigger. Asserts if method is tried to use for making section smaller.
Initializes data with zeros.
Parameters
length Length to which section is expanded.
Reimplemented from TPEF::RawSection.
Definition at line 225 of file DataSection.cc.
{
    assert(length() <= aLength);
    while (length() < aLength) {
        addByte(0);
    }
}
References addByte(), assert, and length().
type()
Section::SectionType TPEF::DataSection::type () const virtual
Returns section's type.
Returns
Type of section.
Reimplemented from TPEF::UDataSection.
Reimplemented in TPEF::LEDataSection, and TPEF::StringSection.
Definition at line 73 of file DataSection.cc.
{
    return ST_DATA;
}
References TPEF::Section::ST_DATA.
writeValue() [1/2]
void TPEF::DataSection::writeValue (Word index, Word numOfMAUs, signed long value) virtual
Writes signed value to data section.
For example, when we call writeValue(0, 4, -3) and MAU is 2bit start of data section will be 11 11 11 01.
MAUs are stored in data section like this: 00000011 000000011 00000011 00000001 (one MAU per byte)
If we call writeValue(0, 4, -3) and MAU is 10bit start of data section will be 1111111111 1111111111 1111111111 1111111101.
However the MAUs are stored in data section like this:
00000011 11111111|00000011 11111111|00000011 11111111|00000011 11111101| MAU1 | MAU2 | MAU3 | MAU4 |
Parameters
index MAU offset to section where to we write value.
numOfMAUs Number of MAUs that we use for storing value.
value Value to write.
Reimplemented in TPEF::LEDataSection.
Definition at line 305 of file DataSection.cc.
{
    int mauInBytes = MAUsToBytes(1);
    MinimumAddressableUnit mauMask =
        static_cast<unsigned int>(-1) >>
        (sizeof(mauMask)*BYTE_BITWIDTH - aSpace()->MAU());
    int shiftCount = 0;
    // start writing from end of area..
    for (int i = numOfMAUs - 1; i >= 0; i--) {
        int byteOffset = MAUsToBytes(index + i);
        MinimumAddressableUnit currentMAU =
            static_cast<MinimumAddressableUnit>(~0);
        if (shiftCount < static_cast<int>(sizeof(value)*BYTE_BITWIDTH)) {
            // I tried math tools... system tests went broken :(
            // ssooo... if it's not broken....
            currentMAU = (value >> shiftCount) & mauMask;
            shiftCount += aSpace()->MAU();
        }
        // write current MAU :)
        for (int j = mauInBytes-1; j >= 0; j--) {
            Byte currentByte = static_cast<Byte>(currentMAU);
            setByte(byteOffset + j,currentByte);
            currentMAU = currentMAU >> BYTE_BITWIDTH;
        }
    }
}
References TPEF::Section::aSpace(), BYTE_BITWIDTH, TPEF::ASpaceElement::MAU(), TPEF::RawSection::MAUsToBytes(), and setByte().
writeValue() [2/2]
void TPEF::DataSection::writeValue (Word index, Word numOfMAUs, unsigned long value) virtual
Writes unsigned value to data section.
Value is aligned to field as normal big endian value least significant bit is stored to last bit of last MAU.
If we call writeValue(0, 4, 3) and MAU is 2bit start of data section will be 00 00 00 11.
However the MAUs are stored in data section like this: 00000000|000000000|00000000|00000011 (one MAU per byte) MAU1 | MAU2 | MAU3 | MAU4
Parameters
index MAU offset to section where to we write value.
numOfMAUs Number of MAUs that we use for storing value.
value Value to write.
Reimplemented in TPEF::LEDataSection.
Definition at line 250 of file DataSection.cc.
{
    int mauInBytes = MAUsToBytes(1);
    MinimumAddressableUnit mauMask =
        static_cast<unsigned int>(-1) >>
        (sizeof(mauMask)*BYTE_BITWIDTH - aSpace()->MAU());
    int shiftCount = 0;
    // start writing from end of area..
    for (int i = numOfMAUs - 1; i >= 0; i--) {
        int byteOffset = MAUsToBytes(index + i);
        MinimumAddressableUnit currentMAU = 0;
        if (shiftCount < static_cast<int>(sizeof(value)*BYTE_BITWIDTH)) {
            // I tried math tools... system tests went broken :(
            // ssooo... if it's not broken....
            currentMAU = (value >> shiftCount) & mauMask;
        }
        shiftCount += aSpace()->MAU();
        // write current MAU :)
        for (int j = mauInBytes-1; j >= 0; j--) {
            Byte currentByte = static_cast<Byte>(currentMAU);
            setByte(byteOffset + j, currentByte);
            currentMAU = currentMAU >> BYTE_BITWIDTH;
        }
    }
}
References TPEF::Section::aSpace(), BYTE_BITWIDTH, TPEF::ASpaceElement::MAU(), TPEF::RawSection::MAUsToBytes(), and setByte().
Referenced by TPEF::AOutRelocationSectionReader::finalize(), and DataSectionCreator::writeDataLineToTPEF().
Member Data Documentation
data_
std::vector<Byte> TPEF::DataSection::data_ private
Contains the data of data section.
Definition at line 83 of file DataSection.hh.
Referenced by addByte(), byte(), byte(), length(), and setByte().
proto_
DataSection TPEF::DataSection::proto_ static private
Prototype instance of section.
Definition at line 80 of file DataSection.hh.
The documentation for this class was generated from the following files:
DataSection.hh
DataSection.cc