OpenASIP: ProDeBusEditPolicy Class Reference
ProDeBusEditPolicy Class Reference
#include <ProDeBusEditPolicy.hh>
Public Member Functions
ProDeBusEditPolicy ()
virtual ~ProDeBusEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ProDeBusEditPolicy & operator= (ProDeBusEditPolicy &old)
Assignment not allowed.
ProDeBusEditPolicy (ProDeBusEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a bus EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports. the Request.
Definition at line 49 of file ProDeBusEditPolicy.hh.
Constructor & Destructor Documentation
ProDeBusEditPolicy() [1/2]
ProDeBusEditPolicy::ProDeBusEditPolicy ()
The Constructor.
Definition at line 57 of file ProDeBusEditPolicy.cc.
                                      : EditPolicy() {
}
~ProDeBusEditPolicy()
ProDeBusEditPolicy::~ProDeBusEditPolicy () virtual
The Destructor.
Definition at line 63 of file ProDeBusEditPolicy.cc.
{
}
ProDeBusEditPolicy() [2/2]
ProDeBusEditPolicy::ProDeBusEditPolicy (ProDeBusEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeBusEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 120 of file ProDeBusEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
        type == Request::DELETE_REQUEST ||
        type == Request::COPY_REQUEST ||
        type == Request::STATUS_REQUEST) {
        return true;
    } else {
        return false;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, Request::MODIFY_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProDeBusEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 73 of file ProDeBusEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifyBusCmd* modifyCmd = new ModifyBusCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteBusCmd* deleteCmd = new DeleteBusCmd(host_);
        return deleteCmd;
    } else if (type == Request::COPY_REQUEST) {
        CopyComponent* copyCmd = new CopyComponent(host_);
        return copyCmd;
    } else if (type == Request::STATUS_REQUEST) {
        Bus* bus = dynamic_cast<Bus*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_BUS);
        string extension = "";
        if (bus->signExtends()) {
            extension = generator->text(
                ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN).str();
        } else {
            extension = generator->text(
                ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO).str();
        }
        fmt % bus->name() % Conversion::toString(bus->width()) %
            Conversion::toString(bus->immediateWidth()) %
            extension;
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else {
        return NULL;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, TTAMachine::Bus::immediateWidth(), ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), TTAMachine::Bus::signExtends(), ProDeTextGenerator::STATUS_BUS, Request::STATUS_REQUEST, Texts::TextGenerator::text(), Conversion::toString(), ProDeTextGenerator::TXT_RADIO_EXTENSION_SIGN, ProDeTextGenerator::TXT_RADIO_EXTENSION_ZERO, Request::type(), and TTAMachine::Bus::width().
operator=()
ProDeBusEditPolicy & ProDeBusEditPolicy::operator= (ProDeBusEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeBusEditPolicy.hh
ProDeBusEditPolicy.cc