OpenASIP: MoveNodeSelector Class Reference
MoveNodeSelector Class Reference abstract
#include <MoveNodeSelector.hh>
Public Member Functions
MoveNodeSelector ()
virtual ~MoveNodeSelector ()
virtual MoveNodeGroup candidates ()=0
virtual void notifyScheduled (MoveNode &node)=0
virtual void mightBeReady (MoveNode &node)=0
Detailed Description
Move node selector is an abstraction to ready operation list in a list scheduler.
MoveNodeSelectors are responsible in maintaining the ready list and updating it according to scheduling progress.
Definition at line 45 of file MoveNodeSelector.hh.
Constructor & Destructor Documentation
MoveNodeSelector()
MoveNodeSelector::MoveNodeSelector ()
Constructor.
Definition at line 39 of file MoveNodeSelector.cc.
{
}
~MoveNodeSelector()
MoveNodeSelector::~MoveNodeSelector () virtual
Destructor.
Definition at line 45 of file MoveNodeSelector.cc.
{
}
Member Function Documentation
candidates()
MoveNodeGroup MoveNodeSelector::candidates () pure virtual
Returns a group of move nodes which should be scheduled next.
By default returns an empty group. A non-empty group is guaranteed to contain at least one unscheduled move, but not all of them necessarily are.
Returns
Move node group.
Implemented in BUMoveNodeSelector, CriticalPathBBMoveNodeSelector, DDGMoveNodeSelector< PQType >, and SequentialMoveNodeSelector.
Definition at line 58 of file MoveNodeSelector.cc.
{
    return MoveNodeGroup();
}
mightBeReady()
void MoveNodeSelector::mightBeReady (MoveNode & node) pure virtual
This should be called by the client when some incoming dependence to a moveNode is removed.
Parameters
node Node which has lost some incoming dependence
Implemented in BUMoveNodeSelector, CriticalPathBBMoveNodeSelector, DDGMoveNodeSelector< PQType >, and SequentialMoveNodeSelector.
Definition at line 82 of file MoveNodeSelector.cc.
{
    assert(false && "Should never be called. Here just to avoid warning.");
}
References assert.
Referenced by CycleLookBackSoftwareBypasser::removeDeadResults(), and RegisterRenamer::renameLiveRange().
notifyScheduled()
void MoveNodeSelector::notifyScheduled (MoveNode & node) pure virtual
This should be called by the client as soon as a MoveNode is scheduled in order to update the internal state of the selector.
Parameters
node The scheduled MoveNode.
Implemented in BUMoveNodeSelector, CriticalPathBBMoveNodeSelector, DDGMoveNodeSelector< PQType >, and SequentialMoveNodeSelector.
Definition at line 70 of file MoveNodeSelector.cc.
{
    assert(false && "Should never be called. Here just to avoid warning.");
}
References assert.
Referenced by BasicBlockScheduler::notifyScheduled().
The documentation for this class was generated from the following files:
MoveNodeSelector.hh
MoveNodeSelector.cc