OpenASIP: MatchType Class Reference
MatchType Class Reference
#include <MatchType.hh>
Public Member Functions
MatchType (const EntryKeyFieldProperty *field, CostDBTypes::TypeOfMatch match)
virtual ~MatchType ()
MatchType (const MatchType &old)
const EntryKeyFieldProperty * fieldType () const
CostDBTypes::TypeOfMatch matchingType () const
bool isEqual (const MatchType &m) const
Private Member Functions
MatchType & operator= (const MatchType &)
Assignment not allowed.
Private Attributes
const EntryKeyFieldProperty * fieldType_
Type of field.
CostDBTypes::TypeOfMatch matchType_
Type of match.
Detailed Description
Represents a type of match for a certain field.
Definition at line 49 of file MatchType.hh.
Constructor & Destructor Documentation
MatchType() [1/2]
MatchType::MatchType (const EntryKeyFieldProperty * field, CostDBTypes::TypeOfMatch match)
Constructor.
Parameters
field Type of field.
match Type of match.
Definition at line 43 of file MatchType.cc.
                                 :
    fieldType_(field), matchType_(match) {
}
~MatchType()
MatchType::~MatchType () virtual
Destructor.
Definition at line 52 of file MatchType.cc.
                      {
}
MatchType() [2/2]
MatchType::MatchType (const MatchType & old)
Copy constructor.
Parameters
old Match type.
Definition at line 60 of file MatchType.cc.
                                         :
    fieldType_(old.fieldType_), matchType_(old.matchType_) {
}
Member Function Documentation
fieldType()
const EntryKeyFieldProperty * MatchType::fieldType () const
Referenced by isEqual().
isEqual()
bool MatchType::isEqual (const MatchType & m) const
Compares if two match types are equal.
Parameters
m A match type.
Returns
True if match types are equal.
Definition at line 71 of file MatchType.cc.
{
    return fieldType() == m.fieldType() && matchingType() == m.matchingType();
}
References fieldType(), and matchingType().
matchingType()
CostDBTypes::TypeOfMatch MatchType::matchingType () const
Referenced by isEqual().
operator=()
MatchType & MatchType::operator= (const MatchType &) private
Assignment not allowed.
Member Data Documentation
fieldType_
const EntryKeyFieldProperty* MatchType::fieldType_ private
Type of field.
Definition at line 63 of file MatchType.hh.
matchType_
CostDBTypes::TypeOfMatch MatchType::matchType_ private
Type of match.
Definition at line 65 of file MatchType.hh.
The documentation for this class was generated from the following files:
MatchType.hh
MatchType.cc