OpenASIP: TPEF::UDataSection Class Reference
TPEF::UDataSection Class Reference
#include <UDataSection.hh>
Public Member Functions
virtual ~UDataSection ()
virtual SectionType type () const
virtual Byte byte (const Chunk *chunk) const
Public Member Functions inherited from TPEF::RawSection
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
virtual void assureInSection (SectionOffset offset) const
virtual ~RawSection ()
bool empty () const
virtual void setLengthInMAUs (Word length)
virtual Word lengthInMAUs () const
virtual void setDataLength (Word length)
virtual Word length () const
virtual Word bytesToMAUs (Word byteCount) const
virtual Word MAUsToBytes (Word mauCount) const
virtual Word chunkToMAUIndex (const Chunk *chunk) const
Word referredChunkCount () const
Chunk * referredChunk (Word index) const
bool belongsToSection (const Chunk *chunk) const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
UDataSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::RawSection
RawSection ()
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Static Private Attributes
static UDataSection proto_
Protorype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Uninitilized data section.
Definition at line 47 of file UDataSection.hh.
Constructor & Destructor Documentation
~UDataSection()
TPEF::UDataSection::~UDataSection () virtual
Destructor.
Definition at line 60 of file UDataSection.cc.
{
}
UDataSection()
TPEF::UDataSection::UDataSection (bool init) protected
Constructor.
Parameters
init True if instance should register itself to base class.
Definition at line 46 of file UDataSection.cc.
                                    : RawSection() {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagVLen();
    setFlagNoBits();
    setStartingAddress(0);
}
References TPEF::Section::registerSection(), TPEF::Section::setFlagNoBits(), TPEF::Section::setStartingAddress(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
byte()
Byte TPEF::UDataSection::byte (const Chunk * chunk) const virtual
Returns byte from section.
In this case section contains only zeros.
Parameters
chunk The chunk in which offset byte is wanted.
Returns
Byte from the offset of the chunk.
Reimplemented in TPEF::DataSection.
Definition at line 92 of file UDataSection.cc.
{
    return 0x00;
}
clone()
Section * TPEF::UDataSection::clone () const protected virtual
Creates an instance of section.
Returns
Newly created section.
Implements TPEF::Section.
Reimplemented in TPEF::DataSection, TPEF::LEDataSection, and TPEF::StringSection.
Definition at line 79 of file UDataSection.cc.
{
    return new UDataSection(false);
}
type()
Section::SectionType TPEF::UDataSection::type () const virtual
Returns section's type.
Returns
Type of section.
Implements TPEF::Section.
Reimplemented in TPEF::DataSection, TPEF::LEDataSection, and TPEF::StringSection.
Definition at line 69 of file UDataSection.cc.
{
    return ST_UDATA;
}
References TPEF::Section::ST_UDATA.
Referenced by TTAProgram::ProgramWriter::createBinary(), and TTAProgram::TPEFProgramFactory::createDataMemories().
Member Data Documentation
proto_
UDataSection TPEF::UDataSection::proto_ static private
Protorype instance of section.
Definition at line 61 of file UDataSection.hh.
The documentation for this class was generated from the following files:
UDataSection.hh
UDataSection.cc