OpenASIP: NullOperationModule Class Reference
NullOperationModule Class Reference
#include <OperationModule.hh>
Public Member Functions
virtual ~NullOperationModule ()
virtual std::string name () const
virtual bool definesBehavior () const
virtual std::string behaviorModule () const
virtual std::string propertiesModule () const
virtual bool hasBehaviorSource () const
virtual std::string behaviorSourceModule () const
Public Member Functions inherited from OperationModule
OperationModule (const std::string &name, const std::string &path)
OperationModule (const OperationModule &om)
virtual ~OperationModule ()
OperationModule & operator= (const OperationModule &om)
Static Public Member Functions
static NullOperationModule & instance ()
Private Member Functions
NullOperationModule ()
NullOperationModule (const NullOperationModule &om)
NullOperationModule & operator= (const NullOperationModule &om)
Static Private Attributes
static NullOperationModule instance_
Unique instance of NullOperationModule.
Detailed Description
Singleton class that is used to represent a null value for operation state.
Definition at line 88 of file OperationModule.hh.
Constructor & Destructor Documentation
~NullOperationModule()
NullOperationModule::~NullOperationModule () virtual
Destructor.
Definition at line 209 of file OperationModule.cc.
{
}
NullOperationModule() [1/2]
NullOperationModule::NullOperationModule () private
Constructor.
Definition at line 203 of file OperationModule.cc.
                                         : OperationModule("<NULL>", "") {
}
NullOperationModule() [2/2]
NullOperationModule::NullOperationModule (const NullOperationModule & om) private
Member Function Documentation
behaviorModule()
string NullOperationModule::behaviorModule () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Exceptions
FileNotFound If behavior module is not found.
Reimplemented from OperationModule.
Definition at line 241 of file OperationModule.cc.
{
    abortWithError("behaviorModule()");
    return "";
}
References abortWithError.
behaviorSourceModule()
string NullOperationModule::behaviorSourceModule () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Exceptions
FileNotFound Doesn't throw.
Reimplemented from OperationModule.
Definition at line 276 of file OperationModule.cc.
{
    abortWithError("behaviorSourceModule()");
    return "";
}
References abortWithError.
definesBehavior()
bool NullOperationModule::definesBehavior () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Reimplemented from OperationModule.
Definition at line 229 of file OperationModule.cc.
{
    abortWithError("definesBehavior()");
    return false;
}
References abortWithError.
hasBehaviorSource()
bool NullOperationModule::hasBehaviorSource () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Reimplemented from OperationModule.
Definition at line 264 of file OperationModule.cc.
{
    abortWithError("hasBehaviorSource()");
    return false;
}
References abortWithError.
instance()
static NullOperationModule & NullOperationModule::instance () static
Referenced by OSEdAddOperationCmd::Do(), OSEdPropertiesCmd::Do(), OperationBehaviorLoader::importBehavior(), OperationContainer::module(), OperationIndex::moduleOf(), OperationIndex::moduleOf(), AddModuleDialog::onOk(), OperationPoolPimpl::operation(), and OperationContainer::operation().
name()
string NullOperationModule::name () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Reimplemented from OperationModule.
Definition at line 218 of file OperationModule.cc.
{
    abortWithError("name()");
    return "";
}
References abortWithError.
operator=()
NullOperationModule & NullOperationModule::operator= (const NullOperationModule & om) private
propertiesModule()
string NullOperationModule::propertiesModule () const virtual
Writes a message to error log and aborts the program.
Returns
Never returns.
Reimplemented from OperationModule.
Definition at line 252 of file OperationModule.cc.
{
    abortWithError("propertiesModule()");
    return "";
}
References abortWithError.
Member Data Documentation
instance_
NullOperationModule NullOperationModule::instance_ static private
Unique instance of NullOperationModule.
Definition at line 108 of file OperationModule.hh.
The documentation for this class was generated from the following files:
OperationModule.hh
OperationModule.cc