OpenASIP: InterpolatingRFEstimator Class Reference
InterpolatingRFEstimator Class Reference
Public Member Functions
InterpolatingRFEstimator (const std::string &name)
virtual ~InterpolatingRFEstimator ()
DESCRIPTION ("RF cost estimator plugin that estimates costs of RFs by generating" "cost database from cost values of HDB and uses interpolation to " "estimate the costs. In case there's no cost data available for the " "given RF the plugin interpolates the estimate if possible.")
bool estimateArea (const TTAMachine::BaseRegisterFile &rf, const IDF::RFImplementationLocation &, AreaInGates &area, HDB::HDBManager &hdb)
bool estimatePortWriteDelay (const TTAMachine::RFPort &port, const IDF::RFImplementationLocation &, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimatePortReadDelay (const TTAMachine::RFPort &port, const IDF::RFImplementationLocation &, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimateMaximumComputationDelay (const TTAMachine::BaseRegisterFile &rf, const IDF::RFImplementationLocation &, DelayInNanoSeconds &delay, HDB::HDBManager &hdb)
bool estimateEnergy (const TTAMachine::BaseRegisterFile &rf, const IDF::RFImplementationLocation &, const TTAProgram::Program &, const ExecutionTrace &trace, EnergyInMilliJoules &energy, HDB::HDBManager &hdb)
Public Member Functions inherited from CostEstimator::RFCostEstimationPlugin
RFCostEstimationPlugin (const std::string &name)
virtual ~RFCostEstimationPlugin ()
Public Member Functions inherited from CostEstimator::CostEstimationPlugin
CostEstimationPlugin (const std::string &name)
virtual ~CostEstimationPlugin ()
virtual std::string name () const
virtual std::string description () const
Private Types
typedef std::map< const EntryKeyProperty *, CostDBTypes::MatchTypeTable > MatchTypeMap
Search type for each entry type.
Private Member Functions
void initializeEstimator (const HDBManager &hdb)
CostDBTypes::EntryTable createSearch (const BaseRegisterFile &rf) const
void createSearchTypes ()
Private Attributes
CostDatabaseRegistry * costDatabaseRegistry_
Registry of cost databases.
CostDatabase * costdb_
Cost database being used.
SearchStrategy * strategy_
Search strategy to be used with the cost database.
EntryKeyProperty * rfileProperty_
Entry key property of register file.
MatchTypeMap searchTypes_
Types of matches used for searching entries from the cost database.
CostDBTypes::MatchTypeTable interpMatchType_
Table of types of match.
Additional Inherited Members
Protected Attributes inherited from CostEstimator::CostEstimationPlugin
std::string name_
the name of the plugin class in the HDB; used to identify cost data
Detailed Description
Definition at line 55 of file InterpolatingRFEstimator.cc.
Member Typedef Documentation
MatchTypeMap
typedef std::map< const EntryKeyProperty*, CostDBTypes::MatchTypeTable> InterpolatingRFEstimator::MatchTypeMap private
Search type for each entry type.
Definition at line 414 of file InterpolatingRFEstimator.cc.
Constructor & Destructor Documentation
InterpolatingRFEstimator()
InterpolatingRFEstimator::InterpolatingRFEstimator (const std::string & name) inline
Definition at line 57 of file InterpolatingRFEstimator.cc.
                                                    :
        RFCostEstimationPlugin(name) {
        costDatabaseRegistry_ = &CostDatabaseRegistry::instance();
    }
References costDatabaseRegistry_, and CostDatabaseRegistry::instance().
~InterpolatingRFEstimator()
virtual InterpolatingRFEstimator::~InterpolatingRFEstimator () inline virtual
Definition at line 62 of file InterpolatingRFEstimator.cc.
{
    }
Member Function Documentation
createSearch()
CostDBTypes::EntryTable InterpolatingRFEstimator::createSearch (const BaseRegisterFile & rf) const inline private
Creates a search to cost database to find entries matching the given register file.
Parameters
rf Register file which matches are searched.
Returns
Returns entries that matched the register file.
Definition at line 444 of file InterpolatingRFEstimator.cc.
{
    CostDBTypes::EntryTable results;
    RFArchitecture rfArch(&rf);
    CostDBEntryKey* searchKey = new CostDBEntryKey(rfileProperty_);
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.size()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_NUM_REGISTERS)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.readPortCount()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_READ_PORTS)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.writePortCount()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_WRITE_PORTS)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.width()),
            rfileProperty_->fieldProperty(CostDBTypes::EKF_BIT_WIDTH)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.latency()),
            rfileProperty_->fieldProperty(CostDBTypes::EKF_LATENCY)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.bidirPortCount()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_BIDIR_PORTS)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.maxReads()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_MAX_READS)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.maxWrites()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_MAX_WRITES)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataBool(rfArch.hasGuardSupport()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_GUARD_SUPPORT)));
    searchKey->addField(
        new EntryKeyField(
            new EntryKeyDataInt(rfArch.guardLatency()),
            rfileProperty_->fieldProperty(
                CostDBTypes::EKF_GUARD_LATENCY)));
    // Perform a database query.
    try {
        results = costdb_->search(*searchKey, interpMatchType_);
    } catch (Exception& e) {
        delete searchKey;
        searchKey = 0;
        throw e;
    }
    delete searchKey;
    searchKey = 0;
    return results;
}
References CostDBEntryKey::addField(), HDB::RFArchitecture::bidirPortCount(), costdb_, CostDBTypes::EKF_BIDIR_PORTS, CostDBTypes::EKF_BIT_WIDTH, CostDBTypes::EKF_GUARD_LATENCY, CostDBTypes::EKF_GUARD_SUPPORT, CostDBTypes::EKF_LATENCY, CostDBTypes::EKF_MAX_READS, CostDBTypes::EKF_MAX_WRITES, CostDBTypes::EKF_NUM_REGISTERS, CostDBTypes::EKF_READ_PORTS, CostDBTypes::EKF_WRITE_PORTS, EntryKeyProperty::fieldProperty(), HDB::RFArchitecture::guardLatency(), HDB::RFArchitecture::hasGuardSupport(), interpMatchType_, HDB::RFArchitecture::latency(), HDB::RFArchitecture::maxReads(), HDB::RFArchitecture::maxWrites(), HDB::RFArchitecture::readPortCount(), rfileProperty_, CostDatabase::search(), HDB::RFArchitecture::size(), HDB::RFArchitecture::width(), and HDB::RFArchitecture::writePortCount().
Referenced by estimateArea(), estimateEnergy(), estimateMaximumComputationDelay(), estimatePortReadDelay(), and estimatePortWriteDelay().
createSearchTypes()
void InterpolatingRFEstimator::createSearchTypes () inline private
Creates types of matches used for searching cost database entries.
Definition at line 516 of file InterpolatingRFEstimator.cc.
{
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_NUM_REGISTERS),
            CostDBTypes::MATCH_INTERPOLATION));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_READ_PORTS),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_WRITE_PORTS),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_BIDIR_PORTS),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_BIT_WIDTH),
            CostDBTypes::MATCH_INTERPOLATION));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_LATENCY),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_MAX_READS),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_MAX_WRITES),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_GUARD_SUPPORT),
            CostDBTypes::MATCH_EXACT));
    interpMatchType_.push_back(
        new MatchType(
            rfileProperty_->fieldProperty(CostDBTypes::EKF_GUARD_LATENCY),
            CostDBTypes::MATCH_EXACT));
}
References CostDBTypes::EKF_BIDIR_PORTS, CostDBTypes::EKF_BIT_WIDTH, CostDBTypes::EKF_GUARD_LATENCY, CostDBTypes::EKF_GUARD_SUPPORT, CostDBTypes::EKF_LATENCY, CostDBTypes::EKF_MAX_READS, CostDBTypes::EKF_MAX_WRITES, CostDBTypes::EKF_NUM_REGISTERS, CostDBTypes::EKF_READ_PORTS, CostDBTypes::EKF_WRITE_PORTS, EntryKeyProperty::fieldProperty(), interpMatchType_, CostDBTypes::MATCH_EXACT, CostDBTypes::MATCH_INTERPOLATION, and rfileProperty_.
Referenced by initializeEstimator().
DESCRIPTION()
InterpolatingRFEstimator::DESCRIPTION ("RF cost estimator plugin that estimates costs of RFs by generating" "cost database from cost values of HDB and uses interpolation to " "estimate the costs. In case there's no cost data available for the " "given RF the plugin interpolates the estimate if possible.")
estimateArea()
bool InterpolatingRFEstimator::estimateArea (const TTAMachine::BaseRegisterFile & rf, const IDF::RFImplementationLocation & , AreaInGates & area, HDB::HDBManager & hdb) inline virtual
Estimates the register file's area by fetching cost data named 'area' from HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 77 of file InterpolatingRFEstimator.cc.
{
//#define DEBUG_AREA_ESTIMATION
        try {
            initializeEstimator(hdb);
            CostDBTypes::EntryTable results = createSearch(rf);
            CostDBTypes::EntryTable::const_iterator i = results.begin();
            area = 0.0;
            // worst case area is returned
            for (;i < results.end(); i++) {
                for (int n = 0; n < (*i)->statisticsCount(); n++) {
                    if (area < (*i)->statistics(n).area()) {
                        area = (*i)->statistics(n).area();
                    }
                }
            }
        } catch (Exception& e) {
#ifdef DEBUG_AREA_ESTIMATION
            std::cout << "Exception: " << e.name() << std::endl
                      << "Error message: " << e.errorMsg() << std::endl
                      << "File: " << e.fileName() << std::endl
                      <<" Line: " e.lineNum() << std::endl;
#endif //DEBUG_AREA_ESTIMATION
            return false;
        }
#ifdef DEBUG_AREA_ESTIMATION
        Application::logStream()
            << rf.name() << " area " << area << std::endl;
#endif //DEBUG_AREA_ESTIMATION
        return true;
    }
References createSearch(), Exception::fileName(), initializeEstimator(), Exception::lineNum(), Application::logStream(), and TTAMachine::Component::name().
estimateEnergy()
bool InterpolatingRFEstimator::estimateEnergy (const TTAMachine::BaseRegisterFile & rf, const IDF::RFImplementationLocation & , const TTAProgram::Program & , const ExecutionTrace & trace, EnergyInMilliJoules & energy, HDB::HDBManager & hdb) inline virtual
Estimates the energy consumed by given RF.
Estimate is done by computing the sum of all register file access type energies and RF idle energy. Register file access energies are stored with entries named 'rf_access_energy Nr Nw'. Nr is the number of read accesses, Nw the number of write accesses. For example, 'rf_access_energy 1 3' is the name of entry which tells how much energy is consumed by the RF in case RF is accessed simultaneously once for reading and trice for writing. Idle energy is stored in entry 'rf_idle_energy'.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 268 of file InterpolatingRFEstimator.cc.
{
//#define DEBUG_ENERGY_ESTIMATION
        energy = 0.0;
        ClockCycleCount cyclesWithRFAccess = 0;
        CostDBTypes::EntryTable results;
        try {
            initializeEstimator(hdb);
            results = createSearch(rf);
#ifdef DEBUG_ENERGY_ESTIMATION
            Application::logStream()
                << "## register file " << rf.name() << ": " << std::endl;
#endif
            ExecutionTrace::ConcurrentRFAccessCountList* accessList =
                trace.registerFileAccessCounts(rf.name());
            for (ExecutionTrace::ConcurrentRFAccessCountList::
                     const_iterator i = accessList->begin();
                 i != accessList->end(); ++i) {
                const ExecutionTrace::ConcurrentRFAccessCount& accessCount =
                    *i;
                const std::size_t reads = accessCount.get<0>();
                const std::size_t writes = accessCount.get<1>();
                const ClockCycleCount count = accessCount.get<2>();
                const std::string dataName =
                    std::string("rf_access_energy ") +
                    Conversion::toString(reads) + " " +
                    Conversion::toString(writes);
                try {
                    CostDBTypes::EntryTable::const_iterator i = results.begin();
                    for (;i < results.end(); i++) {
                        // if there are multilpe reults for the rf access
                        // energy, select the worst case
                        // @todo ensure that multiple result is not a bug
                        EnergyInMilliJoules energyTemp = 0.0;
                        for (int n = 0; n < (*i)->statisticsCount(); n++) {
                            if (((*i)->statistics(n).energyReadWrite(
                                     reads, writes) * count) > energyTemp) {
                                energyTemp =
                                    (*i)->statistics(n).energyReadWrite(
                                        reads, writes) * count;
                            }
#ifdef DEBUG_ENERGY_ESTIMATION
                            if (n > 0) {
                                Application::logStream()
                                    << " NOTE: Multiple register access energy "
                                    << "results found!"
                                    << " "
                                    << (*i)->statistics(n).energyReadWrite(
                                        reads, writes)
                                    << std::endl;
                            }
#endif
                        }
                        energy += energyTemp;
                    }
                    cyclesWithRFAccess += count;
                } catch (const KeyNotFound&) {
                    // if no data found, don't even try to estimate the area
                    delete accessList;
                    accessList = NULL;
                    Application::logStream()
                        << "Cost estimation data '" << dataName
                        << "' not found in HDB." << std::endl;
                    return false;
                } catch (const Exception& e) {
                    delete accessList;
                    accessList = NULL;
                    debugLog(e.errorMessage());
                    return false;
                }
            }
            delete accessList;
            accessList = NULL;
        } catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        // add the cost of RF idling
        const ClockCycleCount idleCycles =
            trace.simulatedCycleCount() - cyclesWithRFAccess;
        const std::string dataName = std::string("rf_idle_energy");
        try {
            CostDBTypes::EntryTable::const_iterator i = results.begin();
            for (;i < results.end(); i++) {
                // if there are multilpe reults for the rf idle energy,
                // select the worst case
                // @todo Ensure that multiple results is not a bug
                EnergyInMilliJoules energyTemp = 0.0;
                for (int n = 0; n < (*i)->statisticsCount(); n++) {
                    if (((*i)->statistics(n).energyIdle() * idleCycles) >
                        energyTemp) {
                        energyTemp =
                            (*i)->statistics(n).energyIdle() * idleCycles;
                    }
#ifdef DEBUG_ENERGY_ESTIMATION
                    if (n > 0) {
                        Application::logStream()
                            << " NOTE: Multiple register idle energy "
                            << "results found!"
                            << " " << (*i)->statistics(n).energyIdle()
                            << std::endl;
                    }
#endif
                }
                energy += energyTemp;
            }
        } catch (const KeyNotFound&) {
            // if no data found, don't even try to estimate the area
            Application::logStream()
                << "Cost estimation data '" << dataName
                << "' not found in HDB." << std::endl;
            return false;
        } catch (const Exception& e) {
            debugLog(e.errorMessage());
            return false;
        }
        return true;
    }
References createSearch(), debugLog, Exception::errorMessage(), initializeEstimator(), Application::logStream(), TTAMachine::Component::name(), ExecutionTrace::registerFileAccessCounts(), ExecutionTrace::simulatedCycleCount(), Conversion::toString(), and trace.
estimateMaximumComputationDelay()
bool InterpolatingRFEstimator::estimateMaximumComputationDelay (const TTAMachine::BaseRegisterFile & rf, const IDF::RFImplementationLocation & , DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file maximum computation delay by fetching cost data named 'computation_delay' from HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 225 of file InterpolatingRFEstimator.cc.
{
//#define DEBUG_DELAY_ESTIMATION
        try {
            initializeEstimator(hdb);
            CostDBTypes::EntryTable results = createSearch(rf);
            CostDBTypes::EntryTable::const_iterator i = results.begin();
            delay = 0.0;
            // the worst case is returned if found multiple results
            for (;i < results.end(); i++) {
                for (int n = 0; n < (*i)->statisticsCount(); n++) {
                    if (delay < (*i)->statistics(n).delay()) {
                        delay = (*i)->statistics(n).delay();
                    }
                }
            }
        } catch (Exception& e) {
            return false;
        }
#ifdef DEBUG_DELAY_ESTIMATION
        Application::logStream() << rf.name()
                                 << " computation delay "
                                 << delay << std::endl;
#endif // DEBUG_DELAY_ESTIMATION
        return true;
    }
References createSearch(), initializeEstimator(), Application::logStream(), and TTAMachine::Component::name().
estimatePortReadDelay()
bool InterpolatingRFEstimator::estimatePortReadDelay (const TTAMachine::RFPort & port, const IDF::RFImplementationLocation & , DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file port read delay by fetching cost data named 'output_delay' from HDB.
Assumes that all ports have the same output delay, that is, there is only one 'output_delay' entry for a RF in HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 175 of file InterpolatingRFEstimator.cc.
{
//#define DEBUG_DELAY_ESTIMATION
        try {
            initializeEstimator(hdb);
            CostDBTypes::EntryTable results = createSearch(*port.parentUnit());
            CostDBTypes::EntryTable::const_iterator i = results.begin();
            delay = 0.0;
            // worst case delay is returned
            for (;i < results.end(); i++) {
                for (int n = 0; n < (*i)->statisticsCount(); n++) {
#ifndef UNIQUE_PORT_DELAY
                    if (delay < (*i)->statistics(n).delayPort("output_delay")) {
                        delay = (*i)->statistics(n).delayPort("output_delay");
                    }
#endif // UNIQUE_PORT_DELAY
#ifdef UNIQUE_PORT_DELAY
                    // this one is used if defferent ports of an unit
                    // can have different delays
                    if (delay < (*i)->statistics(n).delayPort(port.name())) {
                        delay = (*i)->statistics(n).delayPort(port.name());
                    }
#endif // UNIQUE_PORT_DELAY
                }
            }
        } catch (Exception& e) {
#ifdef DEBUG_DELAY_ESTIMATION
            Application::logStream() << "No output_delay data for register "
                                     << "file "
                                     << port.parentUnit()->name()
                                     << " found in HDB." << std::endl;
#endif // DEBUG_DELAY_ESTIMATION
            return false;
        }
#ifdef DEBUG_DELAY_ESTIMATION
        Application::logStream()
            << port.name() << " (port) delay " << delay << std::endl;
#endif // DEBUG_DELAY_ESTIMATION
        return true;
    }
References createSearch(), initializeEstimator(), Application::logStream(), TTAMachine::Component::name(), TTAMachine::Port::name(), and TTAMachine::RFPort::parentUnit().
estimatePortWriteDelay()
bool InterpolatingRFEstimator::estimatePortWriteDelay (const TTAMachine::RFPort & port, const IDF::RFImplementationLocation & , DelayInNanoSeconds & delay, HDB::HDBManager & hdb) inline virtual
Estimates the register file port write delay by fetching cost data named 'input_delay' from HDB.
Assumes that all ports have the same input delay, that is, there is only one 'input_delay' entry for a RF in HDB.
Reimplemented from CostEstimator::RFCostEstimationPlugin.
Definition at line 121 of file InterpolatingRFEstimator.cc.
{
//#define DEBUG_DELAY_ESTIMATION
        try {
            initializeEstimator(hdb);
            CostDBTypes::EntryTable results = createSearch(*port.parentUnit());
            CostDBTypes::EntryTable::const_iterator i = results.begin();
            delay = 0.0;
            // worst case delay is returned
            for (;i < results.end(); i++) {
                for (int n = 0; n < (*i)->statisticsCount(); n++) {
#ifndef UNIQUE_PORT_DELAY
                    if (delay < (*i)->statistics(n).delayPort("input_delay")) {
                        delay = (*i)->statistics(n).delayPort("input_delay");
                    }
#endif // UNIQUE_PORT_DELAY
#ifdef UNIQUE_PORT_DELAY
                    // this one is used if defferent ports of an unit
                    // can have different delays
                    if (delay < (*i)->statistics(n).delayPort(port.name())) {
                        delay = (*i)->statistics(n).delayPort(port.name());
                    }
#endif // UNIQUE_PORT_DELAY
                }
            }
        } catch (Exception& e) {
#ifdef DEBUG_DELAY_ESTIMATION
            Application::logStream() << "No input_delay data for register "
                                     << "file "
                                     << port.parentUnit()->name()
                                     << " found in HDB." << std::endl;
#endif // DEBUG_DELAY_ESTIMATION
            return false;
        }
#ifdef DEBUG_DELAY_ESTIMATION
        Application::logStream()
            << port.name() << " (port) delay " << delay << std::endl;
#endif // DEBUG_DELAY_ESTIMATION
        return true;
    }
References createSearch(), initializeEstimator(), Application::logStream(), TTAMachine::Component::name(), TTAMachine::Port::name(), and TTAMachine::RFPort::parentUnit().
initializeEstimator()
void InterpolatingRFEstimator::initializeEstimator (const HDBManager & hdb) inline private
Initializes the plugin.
Parameters
hdb The HDB to be used in searching entries. Cost database is created in basis of this HDB.
Definition at line 427 of file InterpolatingRFEstimator.cc.
{
    costdb_ = &costDatabaseRegistry_->costDatabase(hdb);
    strategy_ = new FilterSearch();
    costdb_->setSearchStrategy(strategy_);
    rfileProperty_ = EntryKeyProperty::find(CostDBTypes::EK_RFILE);
    createSearchTypes();
}
References CostDatabaseRegistry::costDatabase(), costDatabaseRegistry_, costdb_, createSearchTypes(), CostDBTypes::EK_RFILE, EntryKeyProperty::find(), rfileProperty_, CostDatabase::setSearchStrategy(), and strategy_.
Referenced by estimateArea(), estimateEnergy(), estimateMaximumComputationDelay(), estimatePortReadDelay(), and estimatePortWriteDelay().
Member Data Documentation
costDatabaseRegistry_
CostDatabaseRegistry* InterpolatingRFEstimator::costDatabaseRegistry_ private
Registry of cost databases.
Definition at line 405 of file InterpolatingRFEstimator.cc.
Referenced by initializeEstimator(), and InterpolatingRFEstimator().
costdb_
CostDatabase* InterpolatingRFEstimator::costdb_ private
Cost database being used.
Definition at line 407 of file InterpolatingRFEstimator.cc.
Referenced by createSearch(), and initializeEstimator().
interpMatchType_
CostDBTypes::MatchTypeTable InterpolatingRFEstimator::interpMatchType_ private
Table of types of match.
Definition at line 418 of file InterpolatingRFEstimator.cc.
Referenced by createSearch(), and createSearchTypes().
rfileProperty_
EntryKeyProperty* InterpolatingRFEstimator::rfileProperty_ private
Entry key property of register file.
Definition at line 411 of file InterpolatingRFEstimator.cc.
Referenced by createSearch(), createSearchTypes(), and initializeEstimator().
searchTypes_
MatchTypeMap InterpolatingRFEstimator::searchTypes_ private
Types of matches used for searching entries from the cost database.
Definition at line 416 of file InterpolatingRFEstimator.cc.
strategy_
SearchStrategy* InterpolatingRFEstimator::strategy_ private
Search strategy to be used with the cost database.
Definition at line 409 of file InterpolatingRFEstimator.cc.
Referenced by initializeEstimator().
The documentation for this class was generated from the following file:
InterpolatingRFEstimator.cc