OpenASIP: TPEF::Binary Class Reference
TPEF::Binary Class Reference
#include <Binary.hh>
Public Types
enum FileType {
FT_NULL = 0x00 , FT_OBJSEQ = 0x04 , FT_PURESEQ = 0x05 , FT_LIBSEQ = 0x06 ,
FT_MIXED = 0x09 , FT_PARALLEL = 0x0D
}
enum FileArchitecture { FA_NOARCH = 0x00 , FA_TTA_MOVE = 0x01 , FA_TTA_TUT = 0x02 , FA_TDS_TI = 0x03 }
Public Member Functions
Binary ()
virtual ~Binary ()
void addSection (Section *section)
Section * section (Word index) const
Section * section (Section::SectionType type, Word number) const
Word sectionCount () const
Word sectionCount (Section::SectionType type) const
StringSection * strings () const
void setStrings (StringSection *strTable)
void setStrings (const ReferenceManager::SafePointer *strTable)
FileArchitecture arch () const
void setArch (FileArchitecture arch)
FileType type () const
void setType (FileType type)
void setTPEFVersion (TPEFHeaders::TPEFVersion version)
TPEFHeaders::TPEFVersion TPEFVersion () const
Private Member Functions
Binary (const Binary &)
Binary operator= (const Binary &)
Private Attributes
const ReferenceManager::SafePointer * strings_
Reference to string table of binary.
std::vector< Section * > sections_
Stores sections of binary.
FileType fileType_
Binary's file type. See enumerations for more info.
FileArchitecture fileArch_
Binary's file architecture. See enumerations for more info.
TPEFHeaders::TPEFVersion tpefVersion_
Indicates TPEF format version used.
Detailed Description
Root class of tpef binary representation.
Definition at line 49 of file Binary.hh.
Member Enumeration Documentation
FileArchitecture
enum TPEF::Binary::FileArchitecture
Encodings of program sections.
Enumerator
FA_NOARCH
Illegal/undefined architecture.
FA_TTA_MOVE
Move design framework.
FA_TTA_TUT
New TTA template.
FA_TDS_TI
TTA Design Studio architecture.
Definition at line 67 of file Binary.hh.
{
        FA_NOARCH   = 0x00, ///< Illegal/undefined architecture.
        FA_TTA_MOVE = 0x01, ///< Move design framework.
        FA_TTA_TUT  = 0x02, ///< New TTA template.
        FA_TDS_TI   = 0x03  ///< TTA Design Studio architecture.
    };
FileType
enum TPEF::Binary::FileType
Storing types of TTA code.
Enumerator
FT_NULL
Illegal/undefined type.
FT_OBJSEQ
Sequential TTA object code.
FT_PURESEQ
Sequential TTA code, no unresolved symbols.
FT_LIBSEQ
Collection of sequential object code files for linkage.
FT_MIXED
Partly scheduled code.
FT_PARALLEL
Fully scheduled or mixed code.
Definition at line 54 of file Binary.hh.
                  {
        FT_NULL    = 0x00, ///< Illegal/undefined type.
        FT_OBJSEQ  = 0x04, ///< Sequential TTA object code.
        FT_PURESEQ = 0x05, ///< Sequential TTA code, no unresolved symbols.
        FT_LIBSEQ  = 0x06, ///< Collection of sequential object code files
                           ///< for linkage.
        FT_MIXED   = 0x09, ///< Partly scheduled code.
        FT_PARALLEL = 0x0D ///< Fully scheduled or mixed code.
    };
Constructor & Destructor Documentation
Binary() [1/2]
TPEF::Binary::Binary ()
Constructor.
Definition at line 53 of file Binary.cc.
               :
    strings_(&SafePointer::null), tpefVersion_(TPEFHeaders::TPEF_V2) {
}
~Binary()
TPEF::Binary::~Binary () virtual
Destructor.
Definition at line 60 of file Binary.cc.
                {
    while (sections_.size() != 0) {
        delete sections_[sections_.size() - 1];
        sections_[sections_.size() - 1] = NULL;
        sections_.pop_back();
    }
    SafePointer::cleanup();
}
References TPEF::ReferenceManager::SafePointer::cleanup(), and sections_.
Binary() [2/2]
TPEF::Binary::Binary (const Binary &) private
Member Function Documentation
addSection()
void TPEF::Binary::addSection (Section * section)
Referenced by TTAProgram::ProgramWriter::createBinary(), TTAProgram::ProgramWriter::createDataSections(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), CodeSectionCreator::finalize(), DataSectionCreator::finalize(), LabelManager::findOrCreateRelocationSection(), MachineResourceManager::initResourceSection(), MachineResourceManager::nullSection(), TPEF::AOutReader::readData(), TPEF::TPEFReader::readData(), MachineResourceManager::stringToChunk(), and MachineResourceManager::undefinedAddressSpace().
arch()
FileArchitecture TPEF::Binary::arch () const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), and TPEFDumper::fileHeaders().
operator=()
Binary TPEF::Binary::operator= (const Binary &) private
section() [1/2]
Section * TPEF::Binary::section (Section::SectionType type, Word number) const
section() [2/2]
Section * TPEF::Binary::section (Word index) const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), TTAProgram::TPEFProgramFactory::addProcedures(), TPEF::TPEFTools::addressSpaceName(), TPEFDumper::addressSpaceString(), TPEF::TPEFReader::aSpaceSection(), TTAProgram::TPEFProgramFactory::build(), TTAProgram::ProgramWriter::createASpaceElement(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::ProgramWriter::createDataSections(), TPEFDisassembler::createDisassemblyElement(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createLabels(), TPEFDumper::createLogicalIndexes(), TTAProgram::ProgramWriter::createRelocSections(), LabelManager::finalize(), TPEF::SectionReader::finalizeBinary(), TPEF::SectionWriter::finalizeBinary(), LabelManager::findOrCreateRelocationSection(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), TPEFDumper::findSectionIndex(), TPEF::TPEFTools::hasRelocation(), TPEFDisassembler::initCache(), CodeCompressorPlugin::initializeRelocations(), TPEF::TPEFTools::initRelocationCache(), TPEFDumper::memoryInfo(), TPEF::TPEFTools::relocation(), TPEFDumper::relocationTables(), TPEF::TPEFTools::resourceName(), TPEFDumper::section(), TPEFDumper::sectionHeaders(), TPEF::TPEFReader::sectionOfAddress(), TPEF::TPEFTools::sectionOfElement(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), TPEFDisassembler::startAddress(), and TPEFDumper::symbolTables().
sectionCount() [1/2]
Word TPEF::Binary::sectionCount () const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), TTAProgram::TPEFProgramFactory::addProcedures(), TPEF::TPEFTools::addressSpaceName(), TPEF::TPEFReader::aSpaceSection(), TTAProgram::TPEFProgramFactory::build(), TTAProgram::ProgramWriter::createBinary(), TTAProgram::TPEFProgramFactory::createDataMemories(), TTAProgram::TPEFProgramFactory::createLabels(), TPEFDumper::createLogicalIndexes(), TPEFDumper::fileHeaders(), LabelManager::finalize(), TPEF::SectionReader::finalizeBinary(), TPEF::SectionWriter::finalizeBinary(), LabelManager::findOrCreateRelocationSection(), LabelManager::findRelocationDstSection(), TTAProgram::ProgramWriter::findSection(), LabelManager::findSectionByAddress(), TPEFDumper::findSectionIndex(), TPEF::TPEFTools::hasRelocation(), CodeCompressorPlugin::initializeRelocations(), TPEF::TPEFTools::initRelocationCache(), TPEFDumper::memoryInfo(), TPEF::TPEFReader::readData(), TPEF::TPEFTools::relocation(), TPEFDumper::relocationTables(), TPEF::TPEFTools::resourceName(), TPEFDumper::section(), TPEFDumper::sectionHeaders(), TPEF::TPEFReader::sectionOfAddress(), TPEF::TPEFTools::sectionOfElement(), TTAProgram::TPEFProgramFactory::seekFunctionStartPoints(), and TPEFDumper::symbolTables().
sectionCount() [2/2]
Word TPEF::Binary::sectionCount (Section::SectionType type) const
setArch()
void TPEF::Binary::setArch (FileArchitecture arch)
Referenced by TTAProgram::ProgramWriter::createBinary(), AssemblerParser::finalize(), TPEF::AOutReader::readData(), and TPEF::TPEFReader::readData().
setStrings() [1/2]
void TPEF::Binary::setStrings (const ReferenceManager::SafePointer * strTable)
setStrings() [2/2]
void TPEF::Binary::setStrings (StringSection * strTable)
Referenced by TTAProgram::ProgramWriter::createBinary(), TPEF::AOutReader::readData(), TPEF::TPEFReader::readData(), and MachineResourceManager::stringToChunk().
setTPEFVersion()
void TPEF::Binary::setTPEFVersion (TPEFHeaders::TPEFVersion version)
Referenced by TPEF::TPEFReader::readData().
setType()
void TPEF::Binary::setType (FileType type)
Referenced by TTAProgram::ProgramWriter::createBinary(), AssemblerParser::finalize(), TPEF::AOutReader::readData(), and TPEF::TPEFReader::readData().
strings()
StringSection * TPEF::Binary::strings () const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), TPEFDumper::fileHeaders(), and TPEFDumper::sectionHeader().
TPEFVersion()
TPEFHeaders::TPEFVersion TPEF::Binary::TPEFVersion () const
Referenced by TPEF::TPEFWriter::actualWriteBinary().
type()
FileType TPEF::Binary::type () const
Referenced by TPEF::TPEFWriter::actualWriteBinary(), TTAProgram::TPEFProgramFactory::build(), and TPEFDumper::fileHeaders().
Member Data Documentation
fileArch_
FileArchitecture TPEF::Binary::fileArch_ private
Binary's file architecture. See enumerations for more info.
Definition at line 111 of file Binary.hh.
fileType_
FileType TPEF::Binary::fileType_ private
Binary's file type. See enumerations for more info.
Definition at line 109 of file Binary.hh.
sections_
std::vector<Section*> TPEF::Binary::sections_ private
Stores sections of binary.
Definition at line 106 of file Binary.hh.
Referenced by ~Binary().
strings_
const ReferenceManager::SafePointer* TPEF::Binary::strings_ private
Reference to string table of binary.
Definition at line 103 of file Binary.hh.
tpefVersion_
TPEFHeaders::TPEFVersion TPEF::Binary::tpefVersion_ private
Indicates TPEF format version used.
Definition at line 114 of file Binary.hh.
The documentation for this class was generated from the following files:
Binary.hh
Binary.cc