OpenASIP: SocketPortConnFactory Class Reference
SocketPortConnFactory Class Reference
#include <SocketPortConnFactory.hh>
Public Member Functions
SocketPortConnFactory ()
virtual ~SocketPortConnFactory ()
virtual EditPart * createConnection (EditPart *source, EditPart *target) const
Public Member Functions inherited from ConnectionFactory
ConnectionFactory ()
virtual ~ConnectionFactory ()
virtual EditPart * createEditPart (TTAMachine::MachinePart *)
Public Member Functions inherited from Factory
virtual ~Factory ()
Private Member Functions
SocketPortConnFactory & operator= (SocketPortConnFactory &old)
Assignment not allowed.
SocketPortConnFactory (SocketPortConnFactory &old)
Copying not allowed.
Additional Inherited Members
Protected Member Functions inherited from Factory
Factory ()
Detailed Description
Factory for creating socket-to-port connection EditParts.
Definition at line 44 of file SocketPortConnFactory.hh.
Constructor & Destructor Documentation
SocketPortConnFactory() [1/2]
SocketPortConnFactory::SocketPortConnFactory ()
The Constructor.
Definition at line 46 of file SocketPortConnFactory.cc.
                                            : ConnectionFactory() {
}
~SocketPortConnFactory()
SocketPortConnFactory::~SocketPortConnFactory () virtual
The Destructor.
Definition at line 52 of file SocketPortConnFactory.cc.
{
}
SocketPortConnFactory() [2/2]
SocketPortConnFactory::SocketPortConnFactory (SocketPortConnFactory & old) private
Copying not allowed.
Member Function Documentation
createConnection()
EditPart * SocketPortConnFactory::createConnection (EditPart * port, EditPart * socket) const virtual
Specialized factory function that returns an EditPart corresponding to a socket-port connection.
Note
Source and target distinction does not imply the direction of the connection.
Parameters
port Source (port) of the connection.
socket Target (socket) of the connection.
Returns
An EditPart corresponding to a socket-port connection.
Reimplemented from ConnectionFactory.
Definition at line 66 of file SocketPortConnFactory.cc.
{
    ConnectionEditPart* conn = new ConnectionEditPart();
    SocketPortConnFigure* connFig = new SocketPortConnFigure();
    conn->setFigure(connFig);
    conn->setSource(port);
    conn->setTarget(socket);
    return conn;
}
References EditPart::setFigure(), ConnectionEditPart::setSource(), and ConnectionEditPart::setTarget().
Referenced by UnitPortFactory::addSocket().
operator=()
SocketPortConnFactory & SocketPortConnFactory::operator= (SocketPortConnFactory & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
SocketPortConnFactory.hh
SocketPortConnFactory.cc