OpenASIP: GraphBase< GraphNode, GraphEdge > Class Template Reference
GraphBase< GraphNode, GraphEdge > Class Template Reference abstract
#include <Graph.hh>
Public Types
typedef std::set< GraphNode *, typename GraphNode::Comparator > NodeSet
typedef std::set< GraphEdge *, typename GraphEdge::Comparator > EdgeSet
typedef GraphNode Node
Node type of this graph (possibly, a base class).
typedef GraphEdge Edge
Edge type of this graph (possibly, a base class).
Public Member Functions
GraphBase ()
virtual ~GraphBase ()
virtual int nodeCount () const =0
virtual int edgeCount () const =0
virtual Node & node (const int index) const =0
virtual Edge & edge (const int index) const =0
virtual int outDegree (const Node &node) const =0
virtual int inDegree (const Node &node) const =0
virtual Edge & outEdge (const Node &node, const int index) const =0
virtual Edge & inEdge (const Node &node, const int index) const =0
virtual EdgeSet outEdges (const Node &node) const =0
virtual EdgeSet inEdges (const Node &node) const =0
virtual Node & tailNode (const Edge &edge) const =0
virtual Node & headNode (const Edge &edge) const =0
virtual bool hasEdge (const Node &nTail, const Node &nHead) const =0
virtual EdgeSet connectingEdges (const Node &nTail, const Node &nHead) const =0
virtual TCEString dotString () const
virtual void writeToDotFile (const TCEString &fileName) const
virtual void addNode (Node &node)=0
virtual void removeNode (Node &node)=0
virtual void removeEdge (Edge &e)=0
virtual void connectNodes (const Node &nTail, const Node &nHead, Edge &e)=0
virtual void disconnectNodes (const Node &nTail, const Node &nHead)=0
virtual const TCEString & name () const =0
Protected Member Functions
virtual bool hasNode (const Node &) const =0
Detailed Description
template<typename GraphNode, typename GraphEdge>
class GraphBase< GraphNode, GraphEdge >
Graph base interface shared by all clients within the project.
Templated interface with node and edge types as parameters. If an implementation of this interface deals with multiple types of nodes, all types must share a common base type. Ditto for edges.
Definition at line 51 of file Graph.hh.
Member Typedef Documentation
Edge
template<typename GraphNode , typename GraphEdge > typedef GraphEdge GraphBase< GraphNode, GraphEdge >::Edge
Edge type of this graph (possibly, a base class).
Definition at line 62 of file Graph.hh.
EdgeSet
template<typename GraphNode , typename GraphEdge > typedef std::set<GraphEdge*, typename GraphEdge::Comparator > GraphBase< GraphNode, GraphEdge >::EdgeSet
Definition at line 54 of file Graph.hh.
Node
template<typename GraphNode , typename GraphEdge > typedef GraphNode GraphBase< GraphNode, GraphEdge >::Node
Node type of this graph (possibly, a base class).
Definition at line 60 of file Graph.hh.
NodeSet
template<typename GraphNode , typename GraphEdge > typedef std::set<GraphNode*, typename GraphNode::Comparator > GraphBase< GraphNode, GraphEdge >::NodeSet
Definition at line 53 of file Graph.hh.
Constructor & Destructor Documentation
GraphBase()
template<typename GraphNode , typename GraphEdge > GraphBase< GraphNode, GraphEdge >::GraphBase () inline
Definition at line 56 of file Graph.hh.
{}
~GraphBase()
template<typename GraphNode , typename GraphEdge > virtual GraphBase< GraphNode, GraphEdge >::~GraphBase () inline virtual
Definition at line 57 of file Graph.hh.
{}
Member Function Documentation
addNode()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::addNode (Node & node) pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
connectingEdges()
template<typename GraphNode , typename GraphEdge > virtual EdgeSet GraphBase< GraphNode, GraphEdge >::connectingEdges (const Node & nTail, const Node & nHead) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
connectNodes()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::connectNodes (const Node & nTail, const Node & nHead, Edge & e) pure virtual
disconnectNodes()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::disconnectNodes (const Node & nTail, const Node & nHead) pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
dotString()
template<typename GraphNode , typename GraphEdge > virtual TCEString GraphBase< GraphNode, GraphEdge >::dotString () const virtual
Reimplemented in MachineInstrDDG, and DataDependenceGraph.
edge()
template<typename GraphNode , typename GraphEdge > virtual Edge & GraphBase< GraphNode, GraphEdge >::edge (const int index) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >, BoostGraph< BasicBlockNode, ControlFlowEdge >, BoostGraph< ControlDependenceNode, ControlDependenceEdge >, BoostGraph< MIDDGNode, MIDDGEdge >, BoostGraph< MoveNode, DataDependenceEdge >, BoostGraph< OperationDAGNode, OperationDAGEdge >, and BoostGraph< ProgramDependenceNode, ProgramDependenceEdge >.
edgeCount()
template<typename GraphNode , typename GraphEdge > virtual int GraphBase< GraphNode, GraphEdge >::edgeCount () const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >, BoostGraph< BasicBlockNode, ControlFlowEdge >, BoostGraph< ControlDependenceNode, ControlDependenceEdge >, BoostGraph< MIDDGNode, MIDDGEdge >, BoostGraph< MoveNode, DataDependenceEdge >, BoostGraph< OperationDAGNode, OperationDAGEdge >, and BoostGraph< ProgramDependenceNode, ProgramDependenceEdge >.
hasEdge()
template<typename GraphNode , typename GraphEdge > virtual bool GraphBase< GraphNode, GraphEdge >::hasEdge (const Node & nTail, const Node & nHead) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
hasNode()
template<typename GraphNode , typename GraphEdge > virtual bool GraphBase< GraphNode, GraphEdge >::hasNode (const Node &) const protected pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
headNode()
template<typename GraphNode , typename GraphEdge > virtual Node & GraphBase< GraphNode, GraphEdge >::headNode (const Edge & edge) const pure virtual
inDegree()
template<typename GraphNode , typename GraphEdge > virtual int GraphBase< GraphNode, GraphEdge >::inDegree (const Node & node) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
inEdge()
template<typename GraphNode , typename GraphEdge > virtual Edge & GraphBase< GraphNode, GraphEdge >::inEdge (const Node & node, const int index) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
inEdges()
template<typename GraphNode , typename GraphEdge > virtual EdgeSet GraphBase< GraphNode, GraphEdge >::inEdges (const Node & node) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
name()
template<typename GraphNode , typename GraphEdge > virtual const TCEString & GraphBase< GraphNode, GraphEdge >::name () const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >, BoostGraph< BasicBlockNode, ControlFlowEdge >, BoostGraph< ControlDependenceNode, ControlDependenceEdge >, BoostGraph< MIDDGNode, MIDDGEdge >, BoostGraph< MoveNode, DataDependenceEdge >, BoostGraph< OperationDAGNode, OperationDAGEdge >, and BoostGraph< ProgramDependenceNode, ProgramDependenceEdge >.
node()
template<typename GraphNode , typename GraphEdge > virtual Node & GraphBase< GraphNode, GraphEdge >::node (const int index) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >, BoostGraph< BasicBlockNode, ControlFlowEdge >, BoostGraph< ControlDependenceNode, ControlDependenceEdge >, BoostGraph< MIDDGNode, MIDDGEdge >, BoostGraph< MoveNode, DataDependenceEdge >, BoostGraph< OperationDAGNode, OperationDAGEdge >, and BoostGraph< ProgramDependenceNode, ProgramDependenceEdge >.
nodeCount()
template<typename GraphNode , typename GraphEdge > virtual int GraphBase< GraphNode, GraphEdge >::nodeCount () const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >, BoostGraph< BasicBlockNode, ControlFlowEdge >, BoostGraph< ControlDependenceNode, ControlDependenceEdge >, BoostGraph< MIDDGNode, MIDDGEdge >, BoostGraph< MoveNode, DataDependenceEdge >, BoostGraph< OperationDAGNode, OperationDAGEdge >, and BoostGraph< ProgramDependenceNode, ProgramDependenceEdge >.
outDegree()
template<typename GraphNode , typename GraphEdge > virtual int GraphBase< GraphNode, GraphEdge >::outDegree (const Node & node) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
outEdge()
template<typename GraphNode , typename GraphEdge > virtual Edge & GraphBase< GraphNode, GraphEdge >::outEdge (const Node & node, const int index) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
outEdges()
template<typename GraphNode , typename GraphEdge > virtual EdgeSet GraphBase< GraphNode, GraphEdge >::outEdges (const Node & node) const pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
removeEdge()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::removeEdge (Edge & e) pure virtual
removeNode()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::removeNode (Node & node) pure virtual
Implemented in BoostGraph< GraphNode, GraphEdge >.
tailNode()
template<typename GraphNode , typename GraphEdge > virtual Node & GraphBase< GraphNode, GraphEdge >::tailNode (const Edge & edge) const pure virtual
writeToDotFile()
template<typename GraphNode , typename GraphEdge > virtual void GraphBase< GraphNode, GraphEdge >::writeToDotFile (const TCEString & fileName) const virtual
Referenced by ResourceConstraintAnalyzer::analyze(), LoopAnalyzer::analyze(), ResourceConstraintAnalyzer::analyzeRegisterAntideps(), BFOptimization::assign(), BFOptimization::assignCopyToPrologEpilog(), LLVMTCEDataDependenceGraphBuilder::buildFromCFG(), BUMoveNodeSelector::BUMoveNodeSelector(), BUBasicBlockScheduler::bypassNode(), BUMoveNodeSelector::candidates(), BFOptimization::checkPrologDDG(), llvm::LLVMTCEIRBuilder::compileOptimized(), ProgramDependenceGraph::computeRelations(), DataDependenceGraphBuilder::constructIndividualBB(), ControlFlowGraph::copyToLLVMMachineFunction(), ControlFlowGraph::copyToProcedure(), CriticalPathBBMoveNodeSelector::CriticalPathBBMoveNodeSelector(), CriticalPathBBMoveNodeSelector::CriticalPathBBMoveNodeSelector(), BasicBlockScheduler::ddgSnapshot(), BasicBlockPass::ddgSnapshot(), MoveNodeDuplicator::dumpDDG(), BUBasicBlockScheduler::finalizeSchedule(), BUBasicBlockScheduler::findBypassDestinations(), SimpleIfConverter::handleControlFlowGraph(), BF2Scheduler::handleDDG(), BUBasicBlockScheduler::handleDDG(), BasicBlockScheduler::handleDDG(), BF2Scheduler::handleLoopDDG(), BF2Scheduler::handleLoopDDG(), BasicBlockScheduler::handleLoopDDG(), BUBasicBlockScheduler::handleLoopDDG(), BBSchedulerController::handleProcedure(), BUMoveNodeSelector::initializeReadylist(), DataDependenceGraph::mergeAndKeepAllowed(), CriticalPathBBMoveNodeSelector::notifyScheduled(), BFLateBypassGuard::operator()(), BFPushMoveUp::operator()(), BFScheduleBU::operator()(), BFPostpassBypass::operator()(), ResourceConstraintAnalyzer::optimalScheduleResourceUsage(), ControlFlowGraph::optimizeBBOrdering(), ProgramDependenceGraph::processRegion(), DataDependenceGraphBuilder::processTriggerPO(), DataDependenceGraph::removeRAWEdges(), BFUnscheduleFromBody::returnOriginal(), BFUnscheduleMove::returnOriginal(), ControlFlowGraph::reverseGuardOnOutEdges(), BF2Scheduler::revertBBLiveRangeBookkeepingForDestination(), BF2Scheduler::revertBBLiveRangeBookkeepingForSource(), InstructionPatternAnalyzer::runOnMachineFunction(), ControlFlowGraph::sanitize(), DataDependenceGraph::sanityCheck(), BF2Scheduler::scheduleDDG(), BF2ScheduleFront::scheduleFrontFromMove(), BUBasicBlockScheduler::scheduleInputOperandTempMoves(), BUBasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleMove(), BasicBlockScheduler::scheduleOperandWrites(), BasicBlockScheduler::scheduleOperation(), BUBasicBlockScheduler::scheduleOperation(), BasicBlockScheduler::scheduleRRMove(), BUBasicBlockScheduler::scheduleRRMove(), BUBasicBlockScheduler::scheduleRRTempMoves(), SimpleIfConverter::successors(), BUBasicBlockScheduler::undoBypass(), BFLateBypass::undoOnlyMe(), BFUnscheduleFromBody::unscheduleOriginal(), BFUnscheduleMove::unscheduleOriginal(), OperationDAGDialog::updateDAG(), and llvm::LLVMTCEIRBuilder::writeMachineFunction().
The documentation for this class was generated from the following file:
Graph.hh