OpenASIP: TclInterpreter Class Reference
TclInterpreter Class Reference
#include <TclInterpreter.hh>
Public Member Functions
TclInterpreter ()
virtual ~TclInterpreter ()
virtual void initialize (int argc, char *argv[], InterpreterContext *context, LineReader *reader)
virtual void setVariableToInterpreter (const std::string &name, const DataObject &value)
virtual DataObject variable (const std::string &name)
virtual bool interpret (const std::string &commandLine)
virtual void setResultToInterpreter (const DataObject &value)
virtual bool processScriptFile (const std::string &scriptFileName)
virtual InterpreterContext & context () const
Public Member Functions inherited from ScriptInterpreter
ScriptInterpreter ()
virtual ~ScriptInterpreter ()
virtual void addCustomCommand (CustomCommand *command)
virtual void removeCustomCommand (const std::string &commandName)
virtual CustomCommand * customCommand (const std::string &commandName)
virtual void setResult (DataObject *result)
virtual void setResult (const std::string &result)
virtual void setResult (int result)
virtual void setResult (double result)
virtual std::string result ()
virtual void setError (bool state)
virtual void setError (std::string errorMessage)
virtual bool error () const
virtual void setVariable (const std::string &interpreterVariableName, const std::string &value)
virtual void setVariable (const std::string &interpreterVariableName, int value)
virtual std::string variableStringValue (const std::string &interpreterVariableName)
virtual int variableIntegerValue (const std::string &interpreterVariableName)
virtual void finalize ()
virtual void setLineReader (LineReader *reader)
virtual LineReader * lineReader () const
std::vector< std::string > customCommandsSortedByName ()
Static Public Member Functions
static DataObject tclObjToDataObject (Tcl_Obj *object)
static Tcl_Obj * dataObjectToTclObj (const DataObject &object)
static int customCommandRedirector (ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
Protected Member Functions
virtual void addCustomCommandToInterpreter (const CustomCommand &command)
virtual void removeCustomCommandFromInterpreter (const CustomCommand &command)
Private Member Functions
TclInterpreter (const TclInterpreter &)
Copying not allowed.
TclInterpreter & operator= (const TclInterpreter &)
Assignment not allowed.
Private Attributes
InterpreterContext * context_
Context for interpreter.
Tcl_Interp * interpreter_
Interpreter instance.
Detailed Description
Tcl implementation of ScriptInterpreter.
Tcl (Tool command language) is a very simple programming language. In TCE it is used for command language for Simulator. (Maybe for some other application too.)
Is able to interpret all tcl commands and user defined CustomCommands.
Definition at line 52 of file TclInterpreter.hh.
Constructor & Destructor Documentation
TclInterpreter() [1/2]
TclInterpreter::TclInterpreter ()
Constructor.
Definition at line 49 of file TclInterpreter.cc.
                               :
    ScriptInterpreter(), context_(NULL), interpreter_(NULL) {
}
~TclInterpreter()
TclInterpreter::~TclInterpreter () virtual
Destructor.
Definition at line 56 of file TclInterpreter.cc.
{
    Tcl_DeleteInterp(interpreter_);
}
References interpreter_.
TclInterpreter() [2/2]
TclInterpreter::TclInterpreter (const TclInterpreter &) private
Copying not allowed.
Member Function Documentation
addCustomCommandToInterpreter()
void TclInterpreter::addCustomCommandToInterpreter (const CustomCommand & command) protected virtual
Adds CustomCommand to interpreter.
Parameters
command The command to be added.
Implements ScriptInterpreter.
Definition at line 192 of file TclInterpreter.cc.
{
    char* cName = StringTools::stringToCharPtr(command.name());
    Tcl_CreateObjCommand(
        interpreter_, cName, customCommandRedirector, (ClientData)(&command),
        NULL);
    delete[] cName;
}
References customCommandRedirector(), interpreter_, CustomCommand::name(), and StringTools::stringToCharPtr().
context()
InterpreterContext & TclInterpreter::context () const virtual
Returns the context of the interpreter.
Returns
The context of the interpreter.
Implements ScriptInterpreter.
Definition at line 298 of file TclInterpreter.cc.
{
    return *context_;
}
References context_.
Referenced by initialize(), and SimulatorInterpreter::SimulatorInterpreter().
customCommandRedirector()
int TclInterpreter::customCommandRedirector (ClientData cd, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) static
This handler function is used to handle all CustomCommands.
ClientData field contains CustomCommand to be executed. Tcl_Objs are converted to DataObjects which are then passed to CustomCommand.
Parameters
cd ClientData field.
interp Not used.
objc The number of Tcl_Objs.
objv The Tcl_Objs.
Definition at line 270 of file TclInterpreter.cc.
{
    vector<DataObject> args;
    for (int i = 0; i < objc; i++) {
        DataObject dObj = TclInterpreter::tclObjToDataObject(objv[i]);
        args.push_back(dObj);
    }
    CustomCommand* targetCommand = static_cast<CustomCommand*>(cd);
    assert(cd != NULL);
    if (targetCommand->execute(args)) {
        return TCL_OK;
    }
    return TCL_ERROR;
}
References assert, CustomCommand::execute(), and tclObjToDataObject().
Referenced by addCustomCommandToInterpreter().
dataObjectToTclObj()
Tcl_Obj * TclInterpreter::dataObjectToTclObj (const DataObject & object) static
Converts DataObject to Tcl_Obj.
Parameters
object The object to be converted.
Returns
Tcl_Obj converted from DataObject.
Exceptions
NumberFormatException If conversion fails.
Definition at line 235 of file TclInterpreter.cc.
{
    char* cName = StringTools::stringToCharPtr(object.stringValue());
    Tcl_Obj* obj = Tcl_NewStringObj(cName, -1);
    delete[] cName;
    return obj;
}
References StringTools::stringToCharPtr().
Referenced by setResultToInterpreter().
initialize()
void TclInterpreter::initialize (int argc, char * argv[], InterpreterContext * context, LineReader * reader) virtual
Initializes the interpreter.
Interpreter instance is created, as well as argc and argv variables are set in interpreter.
Parameters
argc The number of command line arguments.
argv The command line arguments.
context The context for interpreter.
reader LineReader for the interpreter.
Implements ScriptInterpreter.
Definition at line 72 of file TclInterpreter.cc.
{
    setLineReader(reader);
    context_ = context;
    interpreter_ = Tcl_CreateInterp();
    if (argc == 0 || argv == NULL) {
    return;
    }
    // argv is set to interpreter
    char* args = Tcl_Merge(argc-1, (char **)argv+1);
    char* argvStr = const_cast<char*>("argv");
    Tcl_SetVar(interpreter_, argvStr, args, TCL_GLOBAL_ONLY);
    ckfree(args);
    // argc is set to interpreter
    string buffer = Conversion::toString(argc-1);
    setVariable("argc", buffer);
    setVariable("argv0", argv[0]);
}
References context(), context_, interpreter_, ScriptInterpreter::setLineReader(), ScriptInterpreter::setVariable(), and Conversion::toString().
Referenced by SimulatorInterpreter::SimulatorInterpreter().
interpret()
bool TclInterpreter::interpret (const std::string & commandLine) virtual
Interprets one command line.
Parameters
commandLine The line to be interpreted.
Returns
True if interpreting is successful, false otherwise.
Todo:
This does not work with nested loops correctly! It stops after it encouters the first line with only "}", thus it stops after the nested loop definition stops.
Implements ScriptInterpreter.
Definition at line 138 of file TclInterpreter.cc.
{
    LineReader* reader = lineReader();
    StringTools::trim(commandLine);
    string command = StringTools::trim(commandLine);
    if (!command.empty() && command.substr(command.length() - 1, 1) == "{" &&
        reader != NULL) {
        // command line ended with '{' so let's wait for more input
        /// @todo This does not work with nested loops correctly!
        /// It stops after it encouters the first line with only "}",
        /// thus it stops after the nested loop definition stops.
        string line = "";
        do {
            line = StringTools::trim(reader->readLine("  "));
            StringTools::trim(line);
            command += "\n" + line;
        } while (!line.empty() && line.substr(line.length() - 1, 1) != "}");
    }
    char* cCommandLine = StringTools::stringToCharPtr(command);
    int code = Tcl_Eval(interpreter_, cCommandLine);
    delete[] cCommandLine;
    Tcl_Obj* object = Tcl_GetObjResult(interpreter_);
    DataObject* dObject = new DataObject(tclObjToDataObject(object));
    setResult(dObject);
    if (code == TCL_OK) {
        setError(false);
        return true;
    } else {
        setError(true);
        return false;
    }
}
References interpreter_, ScriptInterpreter::lineReader(), LineReader::readLine(), ScriptInterpreter::setError(), ScriptInterpreter::setResult(), StringTools::stringToCharPtr(), tclObjToDataObject(), and StringTools::trim().
Referenced by ProximSimulationThread::Entry(), SimulatorCLI::interpreteAndPrintResults(), Proxim::OnInit(), processScriptFile(), SimulatorCLI::run(), and DesignSpaceExplorer::simulate().
operator=()
TclInterpreter & TclInterpreter::operator= (const TclInterpreter &) private
Assignment not allowed.
processScriptFile()
bool TclInterpreter::processScriptFile (const std::string & scriptFileName) virtual
Processes script file.
Parameters
scriptFileName The name of the script file.
Returns
True, if process is successful, false otherwise.
Exceptions
UnreachableStream Don't throw it.
Reimplemented from ScriptInterpreter.
Definition at line 250 of file TclInterpreter.cc.
{
    string command = "source " + scriptFileName;
    if (!interpret(command)) {
        return false;
    }
    return true;
}
References interpret().
Referenced by main(), and TTASimulatorCLI::TTASimulatorCLI().
removeCustomCommandFromInterpreter()
void TclInterpreter::removeCustomCommandFromInterpreter (const CustomCommand & command) protected virtual
Removes custom command from interpreter.
Parameters
command The command to be removed.
Implements ScriptInterpreter.
Definition at line 206 of file TclInterpreter.cc.
{
    char* cName = StringTools::stringToCharPtr(command.name());
    Tcl_DeleteCommand(interpreter_, cName);
    delete[] cName;
}
References interpreter_, CustomCommand::name(), and StringTools::stringToCharPtr().
setResultToInterpreter()
void TclInterpreter::setResultToInterpreter (const DataObject & value) virtual
Sets result to concrete interpreter.
Parameters
value The value to be set.
Exceptions
NumberFormatException If conversion to Tcl_Obj fails.
Implements ScriptInterpreter.
Definition at line 181 of file TclInterpreter.cc.
{
    Tcl_Obj* object = dataObjectToTclObj(value);
    Tcl_SetObjResult(interpreter_, object);
}
References dataObjectToTclObj(), and interpreter_.
setVariableToInterpreter()
void TclInterpreter::setVariableToInterpreter (const std::string & name, const DataObject & value) virtual
Sets a variable for interpreter.
Parameters
name The name of the variable.
value The value for a variable.
Exceptions
NumberFormatException If converting value to string fails.
Implements ScriptInterpreter.
Definition at line 106 of file TclInterpreter.cc.
{
    char* cName = StringTools::stringToCharPtr(name);
    char* cValue = StringTools::stringToCharPtr(value.stringValue());
    Tcl_SetVar(interpreter_, cName, cValue, TCL_GLOBAL_ONLY);
    delete[] cName;
    delete[] cValue;
}
References interpreter_, StringTools::stringToCharPtr(), and DataObject::stringValue().
tclObjToDataObject()
DataObject TclInterpreter::tclObjToDataObject (Tcl_Obj * object) static
Converts Tcl_Obj to DataObject.
Parameters
object The object to be converted.
Returns
DataObject which was converted from Tcl_Obj.
Definition at line 221 of file TclInterpreter.cc.
{
    DataObject dObj;
    dObj.setString(Tcl_GetStringFromObj(object, NULL));
    return dObj;
}
References DataObject::setString().
Referenced by customCommandRedirector(), and interpret().
variable()
DataObject TclInterpreter::variable (const std::string & name) virtual
Returns the DataObject corresponding a certain variable.
Parameters
name The name of the variable.
Returns
The DataObject which holds the value of variable.
Implements ScriptInterpreter.
Definition at line 122 of file TclInterpreter.cc.
{
    DataObject object;
    char* cName = StringTools::stringToCharPtr(name);
    string value = Tcl_GetVar(interpreter_, cName, TCL_GLOBAL_ONLY);
    delete[] cName;
    object.setString(value);
    return object;
}
References interpreter_, and StringTools::stringToCharPtr().
Member Data Documentation
context_
InterpreterContext* TclInterpreter::context_ private
Context for interpreter.
Definition at line 94 of file TclInterpreter.hh.
Referenced by context(), and initialize().
interpreter_
Tcl_Interp* TclInterpreter::interpreter_ private
Interpreter instance.
Definition at line 96 of file TclInterpreter.hh.
Referenced by addCustomCommandToInterpreter(), initialize(), interpret(), removeCustomCommandFromInterpreter(), setResultToInterpreter(), setVariableToInterpreter(), variable(), and ~TclInterpreter().
The documentation for this class was generated from the following files:
TclInterpreter.hh
TclInterpreter.cc