OpenASIP: HDB::PortImplementation Class Reference
HDB::PortImplementation Class Reference
#include <PortImplementation.hh>
Public Member Functions
PortImplementation (const std::string &name, const std::string &loadPort)
virtual ~PortImplementation ()
void setName (const std::string &name)
std::string name () const
void setLoadPort (const std::string &name)
std::string loadPort () const
Private Attributes
std::string name_
Name of the port.
std::string loadPort_
Name of the load enable port.
Detailed Description
Base class for RFPortImplementation and FUPortImplementation.
Definition at line 44 of file PortImplementation.hh.
Constructor & Destructor Documentation
PortImplementation()
HDB::PortImplementation::PortImplementation (const std::string & name, const std::string & loadPort)
The constructor.
Parameters
name Name of the port.
loadPort Name of the load enable port.
Definition at line 43 of file PortImplementation.cc.
                               :
    name_(name), loadPort_(loadPort) {
}
~PortImplementation()
HDB::PortImplementation::~PortImplementation () virtual
The destructor.
Definition at line 53 of file PortImplementation.cc.
{
}
Member Function Documentation
loadPort()
std::string HDB::PortImplementation::loadPort () const
Returns the name of the load enable port.
Returns
The name of the load enable port.
Definition at line 96 of file PortImplementation.cc.
{
    return loadPort_;
}
References loadPort_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), HDB::HDBManager::addRFImplementation(), FUTestbenchGenerator::createStimulusArrays(), FUTestbenchGenerator::createTbInstantiation(), HDBToHtml::fuImplToHtml(), RFTestbenchGenerator::parseRfPorts(), and HDBToHtml::rfImplToHtml().
name()
std::string HDB::PortImplementation::name () const
Returns the name of the port.
Returns
The name of the port.
Definition at line 74 of file PortImplementation.cc.
{
    return name_;
}
References name_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), HDB::HDBManager::addFUImplementation(), ProGe::NetlistGenerator::addFUToNetlist(), HDB::HDBManager::addRFImplementation(), FUTestbenchGenerator::createStimulusArrays(), FUTestbenchGenerator::createTbCode(), FUTestbenchGenerator::createTbInstantiation(), HDBToHtml::fuImplToHtml(), FUImplementationDialog::onOK(), RFTestbenchGenerator::parseRfPorts(), HDBToHtml::rfImplToHtml(), HDB::FUPortImplementation::setArchitecturePort(), HDB::FUPortImplementation::setGuardPort(), setLoadPort(), setName(), HDB::RFPortImplementation::setOpcodePort(), RFImplementationDialog::update(), and FUImplementationDialog::update().
setLoadPort()
void HDB::PortImplementation::setLoadPort (const std::string & name)
Sets the name of the load enable port.
Parameters
name The new name.
Definition at line 85 of file PortImplementation.cc.
{
    loadPort_ = name;
}
References loadPort_, and name().
Referenced by FUPortImplementationDialog::onOK(), and RFPortImplementationDialog::onOK().
setName()
void HDB::PortImplementation::setName (const std::string & name)
Sets the name of the port.
Parameters
name The new name.
Definition at line 63 of file PortImplementation.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by FUPortImplementationDialog::onOK(), and RFPortImplementationDialog::onOK().
Member Data Documentation
loadPort_
std::string HDB::PortImplementation::loadPort_ private
Name of the load enable port.
Definition at line 60 of file PortImplementation.hh.
Referenced by loadPort(), and setLoadPort().
name_
std::string HDB::PortImplementation::name_ private
Name of the port.
Definition at line 58 of file PortImplementation.hh.
Referenced by name(), and setName().
The documentation for this class was generated from the following files:
PortImplementation.hh
PortImplementation.cc