OpenASIP: TPEF::ImmediateElement Class Reference
TPEF::ImmediateElement Class Reference
#include <ImmediateElement.hh>
Public Member Functions
ImmediateElement ()
virtual ~ImmediateElement ()
bool isInline () const
void addByte (Byte aByte)
Byte byte (unsigned int index) const
void setByte (unsigned int index, Byte aValue)
void setWord (Word aValue)
void setSignedWord (SignedWord aValue)
void setSignedLong (SLongWord aValue)
void setULongWord (ULongWord aValue)
Word word () const
LongWord longWord () const
SignedLongWord sLongWord () const
SignedWord signedWord () const
unsigned int length () const
Byte destinationUnit () const
void setDestinationUnit (Byte aDestinationUnit)
Byte destinationIndex () const
void setDestinationIndex (Byte aDestinationIndex)
Public Member Functions inherited from TPEF::InstructionElement
virtual ~InstructionElement ()
bool isMove () const
bool isImmediate () const
bool begin () const
void setBegin (bool isBegin)
InstructionAnnotation * annotation (Word index) const
void addAnnotation (InstructionAnnotation *anAnnotation)
Word annotationCount () const
Public Member Functions inherited from TPEF::SectionElement
virtual ~SectionElement ()
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Private Attributes
std::vector< Byte > value_
Value of immediate.
Byte destinationUnit_
Destination unit of immediate.
Byte destinationIndex_
Destination index of immediate.
Additional Inherited Members
Protected Member Functions inherited from TPEF::InstructionElement
InstructionElement (bool isMove)
Protected Member Functions inherited from TPEF::SectionElement
SectionElement ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Detailed Description
Immediate data element of CodeSection.
Definition at line 49 of file ImmediateElement.hh.
Constructor & Destructor Documentation
ImmediateElement()
TPEF::ImmediateElement::ImmediateElement ()
Constructor.
Definition at line 43 of file ImmediateElement.cc.
                                   :
    InstructionElement(false), destinationUnit_(0), destinationIndex_(0) {
}
~ImmediateElement()
TPEF::ImmediateElement::~ImmediateElement () virtual
Destructor.
Definition at line 50 of file ImmediateElement.cc.
{
}
Member Function Documentation
addByte()
void TPEF::ImmediateElement::addByte (Byte aByte)
Referenced by TPEF::TPEFCodeSectionReader::readData().
byte()
Byte TPEF::ImmediateElement::byte (unsigned int index) const
Referenced by TPEF::TPEFCodeSectionWriter::writeDataField().
destinationIndex()
Byte TPEF::ImmediateElement::destinationIndex () const
Referenced by TTAProgram::TPEFProgramFactory::addProcedures(), TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), CodeCompressorPlugin::immediateTerminal(), and TPEF::TPEFCodeSectionWriter::writeDataField().
destinationUnit()
Byte TPEF::ImmediateElement::destinationUnit () const
Referenced by TTAProgram::TPEFProgramFactory::addProcedures(), TTAProgram::ProgramWriter::createCodeSection(), TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), CodeSectionCreator::finalize(), TTAProgram::TPEFProgramFactory::findInstrTemplate(), CodeCompressorPlugin::programImmediate(), and TPEF::TPEFCodeSectionWriter::writeDataField().
isInline()
bool TPEF::ImmediateElement::isInline () const
Referenced by TTAProgram::TPEFProgramFactory::addProcedures(), TPEFDisassembler::createDisassemblyElement(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createTerminal(), CodeCompressorPlugin::immediateTerminal(), and CodeCompressorPlugin::programImmediate().
length()
unsigned int TPEF::ImmediateElement::length () const
Referenced by TPEF::TPEFRelocSectionReader::finalize(), TPEF::TPEFCodeSectionWriter::writeAttributeField(), and TPEF::TPEFCodeSectionWriter::writeDataField().
longWord()
LongWord TPEF::ImmediateElement::longWord () const
Referenced by TTAProgram::TPEFProgramFactory::createInstruction(), TPEFDisassembler::createInstruction(), TTAProgram::TPEFProgramFactory::createTerminal(), and TTAProgram::TPEFProgramFactory::findInstrTemplate().
setByte()
void TPEF::ImmediateElement::setByte (unsigned int index, Byte aValue)
setDestinationIndex()
void TPEF::ImmediateElement::setDestinationIndex (Byte aDestinationIndex)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::initializeImmediateMove(), and TPEF::TPEFCodeSectionReader::readData().
setDestinationUnit()
void TPEF::ImmediateElement::setDestinationUnit (Byte aDestinationUnit)
Referenced by TTAProgram::ProgramWriter::createCodeSection(), CodeSectionCreator::finalize(), TPEF::AOutTextSectionReader::initializeImmediateMove(), and TPEF::TPEFCodeSectionReader::readData().
setSignedLong()
void TPEF::ImmediateElement::setSignedLong (SLongWord aValue)
Referenced by TTAProgram::ProgramWriter::createCodeSection().
setSignedWord()
void TPEF::ImmediateElement::setSignedWord (SignedWord aValue)
setULongWord()
void TPEF::ImmediateElement::setULongWord (ULongWord aValue)
Referenced by TTAProgram::ProgramWriter::createCodeSection().
setWord()
void TPEF::ImmediateElement::setWord (Word aValue)
Referenced by TPEF::AOutRelocationSectionReader::finalize(), CodeSectionCreator::finalize(), and TPEF::AOutTextSectionReader::initializeImmediateMove().
signedWord()
SignedWord TPEF::ImmediateElement::signedWord () const
sLongWord()
SignedLongWord TPEF::ImmediateElement::sLongWord () const
Referenced by TPEFDisassembler::createDisassemblyElement(), TTAProgram::TPEFProgramFactory::createInstruction(), and TTAProgram::TPEFProgramFactory::findInstrTemplate().
word()
Word TPEF::ImmediateElement::word () const
Referenced by TTAProgram::TPEFProgramFactory::createTerminal(), and TPEF::TPEFRelocSectionReader::finalize().
Member Data Documentation
destinationIndex_
Byte TPEF::ImmediateElement::destinationIndex_ private
Destination index of immediate.
Definition at line 88 of file ImmediateElement.hh.
destinationUnit_
Byte TPEF::ImmediateElement::destinationUnit_ private
Destination unit of immediate.
Definition at line 86 of file ImmediateElement.hh.
value_
std::vector<Byte> TPEF::ImmediateElement::value_ private
Value of immediate.
Definition at line 84 of file ImmediateElement.hh.
The documentation for this class was generated from the following files:
ImmediateElement.hh
ImmediateElement.cc