OpenASIP: ProDeRFEditPolicy Class Reference
ProDeRFEditPolicy Class Reference
#include <ProDeRFEditPolicy.hh>
Public Member Functions
ProDeRFEditPolicy ()
virtual ~ProDeRFEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ProDeRFEditPolicy & operator= (ProDeRFEditPolicy &old)
Assignment not allowed.
ProDeRFEditPolicy (ProDeRFEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a register file EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports the Request.
Definition at line 50 of file ProDeRFEditPolicy.hh.
Constructor & Destructor Documentation
ProDeRFEditPolicy() [1/2]
ProDeRFEditPolicy::ProDeRFEditPolicy ()
The Constructor.
Definition at line 56 of file ProDeRFEditPolicy.cc.
                                    : EditPolicy() {
}
~ProDeRFEditPolicy()
ProDeRFEditPolicy::~ProDeRFEditPolicy () virtual
The Destructor.
Definition at line 62 of file ProDeRFEditPolicy.cc.
{
}
ProDeRFEditPolicy() [2/2]
ProDeRFEditPolicy::ProDeRFEditPolicy (ProDeRFEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeRFEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 128 of file ProDeRFEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
    type == Request::DELETE_REQUEST ||
        type == Request::COPY_REQUEST ||
        type == Request::STATUS_REQUEST) {
    return true;
    } else {
    return false;
    }
}
References Request::COPY_REQUEST, Request::DELETE_REQUEST, Request::MODIFY_REQUEST, Request::STATUS_REQUEST, and Request::type().
getCommand()
ComponentCommand * ProDeRFEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 72 of file ProDeRFEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifyRFCmd* modifyCmd = new ModifyRFCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteRFCmd* deleteCmd = new DeleteRFCmd(host_);
        return deleteCmd;
    } else if (type == Request::COPY_REQUEST) {
        CopyComponent* copyCmd = new CopyComponent(host_);
        return copyCmd;
    } else if (type == Request::STATUS_REQUEST) {
        RegisterFile* rf = dynamic_cast<RegisterFile*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_REGISTER_FILE);
        string type = "";
        if (rf->isNormal()) {
            type = generator->text(
                ProDeTextGenerator::TXT_RF_TYPE_NORMAL).str();
        } else if (rf->isVolatile()) {
            type = generator->text(
                ProDeTextGenerator::TXT_RF_TYPE_VOLATILE).str();
        } else if (rf->isReserved()) {
            type = generator->text(
                ProDeTextGenerator::TXT_RF_TYPE_RESERVED).str();
        } else {
            // unknown rf type
            assert(false);
        }
        fmt % rf->name() % type %
            Conversion::toString(rf->numberOfRegisters()) %
            Conversion::toString(rf->width());
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } else {
    return NULL;
    }
}
References assert, Request::COPY_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), TTAMachine::RegisterFile::isNormal(), TTAMachine::RegisterFile::isReserved(), TTAMachine::RegisterFile::isVolatile(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), TTAMachine::BaseRegisterFile::numberOfRegisters(), ProDeTextGenerator::STATUS_REGISTER_FILE, Request::STATUS_REQUEST, Texts::TextGenerator::text(), Conversion::toString(), ProDeTextGenerator::TXT_RF_TYPE_NORMAL, ProDeTextGenerator::TXT_RF_TYPE_RESERVED, ProDeTextGenerator::TXT_RF_TYPE_VOLATILE, Request::type(), and TTAMachine::BaseRegisterFile::width().
operator=()
ProDeRFEditPolicy & ProDeRFEditPolicy::operator= (ProDeRFEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeRFEditPolicy.hh
ProDeRFEditPolicy.cc