OpenASIP: TPEF::LineNumSection Class Reference
TPEF::LineNumSection Class Reference
#include <LineNumSection.hh>
Public Member Functions
virtual ~LineNumSection ()
virtual SectionType type () const
void setCodeSection (const ReferenceManager::SafePointer *codeSect)
void setCodeSection (CodeSection *codeSect)
CodeSection * codeSection () const
Public Member Functions inherited from TPEF::Section
virtual ~Section ()
virtual bool isChunkable () const
virtual Chunk * chunk (SectionOffset offset) const
bool isProgramSection () const
bool isAuxSection () const
virtual void addElement (SectionElement *element)
virtual void setElement (Word index, SectionElement *element)
SectionElement * element (Word index) const
Word elementCount () const
void setFlagNoBits ()
void unsetFlagNoBits ()
bool noBits () const
bool vLen () const
Byte flags () const
void setFlags (Byte flagByte)
void setStartingAddress (AddressImage address)
AddressImage startingAddress () const
void setLink (const ReferenceManager::SafePointer *aLink)
void setLink (Section *aLink)
Section * link () const
void setASpace (const ReferenceManager::SafePointer *addrSpace)
void setASpace (ASpaceElement *addrSpace)
ASpaceElement * aSpace () const
void setName (const ReferenceManager::SafePointer *sectionName)
void setName (Chunk *sectionName)
Chunk * name () const
virtual bool isDataSection () const
virtual bool isCodeSection () const
Public Member Functions inherited from TPEF::SafePointable
virtual ~SafePointable ()
Protected Member Functions
LineNumSection (bool init)
virtual Section * clone () const
Protected Member Functions inherited from TPEF::Section
Section ()
void setFlagVLen ()
void unsetFlagVLen ()
Protected Member Functions inherited from TPEF::SafePointable
SafePointable ()
Private Attributes
const ReferenceManager::SafePointer * codeSection_
Stores text section which we refer with lines.
Static Private Attributes
static LineNumSection proto_
Protorype instance of section.
Additional Inherited Members
Public Types inherited from TPEF::Section
enum SectionType {
ST_NULL = 0x00 , ST_STRTAB = 0x01 , ST_SYMTAB = 0x02 , ST_DEBUG = 0x03 ,
ST_RELOC = 0x04 , ST_LINENO = 0x05 , ST_NOTE = 0x06 , ST_ADDRSP = 0x07 ,
ST_MR = 0x0A , ST_CODE = 0x81 , ST_DATA = 0x82 , ST_UDATA = 0x83 ,
ST_LEDATA = 0x84 , ST_DUMMY = 0xff
}
enum SectionFlag { SF_VLEN = 0x40 , SF_NOBITS = 0x80 }
Static Public Member Functions inherited from TPEF::Section
static Section * createSection (SectionType type)
static bool isProgramSection (SectionType type)
Static Protected Member Functions inherited from TPEF::Section
static void registerSection (const Section *section)
Detailed Description
Prosessor Line number section.
Definition at line 47 of file LineNumSection.hh.
Constructor & Destructor Documentation
~LineNumSection()
TPEF::LineNumSection::~LineNumSection () virtual
Destructor.
Definition at line 62 of file LineNumSection.cc.
{
}
LineNumSection()
TPEF::LineNumSection::LineNumSection (bool init) protected
Constructor.
Parameters
init True if instance should register itself to base class.
Definition at line 47 of file LineNumSection.cc.
                                        : Section(),
    codeSection_(&SafePointer::null) {
    if (init) {
        Section::registerSection(this);
    }
    unsetFlagNoBits();
    unsetFlagVLen();
    setStartingAddress(0);
}
References TPEF::Section::registerSection(), TPEF::Section::setStartingAddress(), TPEF::Section::unsetFlagNoBits(), and TPEF::Section::unsetFlagVLen().
Member Function Documentation
clone()
Section * TPEF::LineNumSection::clone () const protected virtual
Creates an instance of section.
Returns
Newly created section.
Implements TPEF::Section.
Definition at line 81 of file LineNumSection.cc.
{
    return new LineNumSection(false);
}
codeSection()
CodeSection * TPEF::LineNumSection::codeSection () const
Returns text section which lines are stored in this section.
Returns
Text section which lines are stored in this section.
Definition at line 112 of file LineNumSection.cc.
{
    return dynamic_cast<CodeSection*>(codeSection_->pointer());
}
References codeSection_, and TPEF::ReferenceManager::SafePointer::pointer().
setCodeSection() [1/2]
void TPEF::LineNumSection::setCodeSection (CodeSection * codeSect)
Sets text section which instructions are referred in this section.
Parameters
Section to set.
Definition at line 102 of file LineNumSection.cc.
{
    codeSection_ = SafePointer::replaceReference(codeSection_, codeSect);
}
References codeSection_, and TPEF::ReferenceManager::SafePointer::replaceReference().
setCodeSection() [2/2]
void TPEF::LineNumSection::setCodeSection (const ReferenceManager::SafePointer * codeSect)
Sets text section which instructions are referred in this section.
Parameters
Section to set.
Definition at line 91 of file LineNumSection.cc.
{
    codeSection_ = codeSect;
}
References codeSection_.
type()
Section::SectionType TPEF::LineNumSection::type () const virtual
Returns section's type.
Returns
Type of section.
Implements TPEF::Section.
Definition at line 71 of file LineNumSection.cc.
{
    return ST_LINENO;
}
References TPEF::Section::ST_LINENO.
Member Data Documentation
codeSection_
const ReferenceManager::SafePointer* TPEF::LineNumSection::codeSection_ private
Stores text section which we refer with lines.
Definition at line 63 of file LineNumSection.hh.
Referenced by codeSection(), setCodeSection(), and setCodeSection().
proto_
LineNumSection TPEF::LineNumSection::proto_ static private
Protorype instance of section.
Definition at line 65 of file LineNumSection.hh.
The documentation for this class was generated from the following files:
LineNumSection.hh
LineNumSection.cc