OpenASIP: InfoBreakpointsCommand Class Reference
InfoBreakpointsCommand Class Reference
Public Member Functions
InfoBreakpointsCommand (SimControlLanguageCommand &parentCommand)
virtual ~InfoBreakpointsCommand ()
virtual bool execute (const std::vector< DataObject > &arguments)
Public Member Functions inherited from SimControlLanguageSubCommand
SimControlLanguageSubCommand (SimControlLanguageCommand &parentCommand)
virtual ~SimControlLanguageSubCommand ()
virtual SimControlLanguageCommand & parent ()
Detailed Description
Implementation of "info breakpoints".
Definition at line 1351 of file InfoCommand.cc.
Constructor & Destructor Documentation
InfoBreakpointsCommand()
InfoBreakpointsCommand::InfoBreakpointsCommand (SimControlLanguageCommand & parentCommand) inline
Constructor.
Definition at line 1356 of file InfoCommand.cc.
                                                                     :
        SimControlLanguageSubCommand(parentCommand) {
    }
~InfoBreakpointsCommand()
virtual InfoBreakpointsCommand::~InfoBreakpointsCommand () inline virtual
Destructor.
Definition at line 1363 of file InfoCommand.cc.
{
    }
Member Function Documentation
execute()
virtual bool InfoBreakpointsCommand::execute (const std::vector< DataObject > & arguments) inline virtual
Executes the "info breakpoints" command.
Prints a table of all breakpoints. Each breakpoint is printed in a separate line. If argument is given, only the breakpoint with handle num is printed.
Parameters
arguments Arguments to the command, including the command.
Returns
true in case execution was successful.
Implements SimControlLanguageSubCommand.
Definition at line 1376 of file InfoCommand.cc.
{
        const int argumentCount = arguments.size() - 2;
        if (!parent().checkArgumentCount(argumentCount, 0, 1)) {
            return false;
        }
        if (argumentCount == 1 &&
            !parent().checkPositiveIntegerArgument(arguments[2])) {
            return false;
        }
        if (!parent().checkSimulationEnded() &&
            !parent().checkSimulationStopped() &&
            !parent().checkSimulationInitialized()) {
            return false;
        }
        if (argumentCount == 1) {
            unsigned int breakpointHandle =
                static_cast<unsigned int>(arguments[2].integerValue());
            return parent().printBreakpointInfo(breakpointHandle);
        } else {
            StopPointManager& bpManager =
                parent().simulatorFrontend().stopPointManager();
            for (unsigned int i = 0; i < bpManager.stopPointCount(); ++i) {
                parent().printBreakpointInfo(bpManager.stopPointHandle(i));
            }
            return true;
        }
    }
References SimControlLanguageSubCommand::parent(), SimControlLanguageCommand::printBreakpointInfo(), SimControlLanguageCommand::simulatorFrontend(), StopPointManager::stopPointCount(), StopPointManager::stopPointHandle(), and SimulatorFrontend::stopPointManager().
The documentation for this class was generated from the following file:
InfoCommand.cc