OpenASIP: ProDeSocketEditPolicy Class Reference
ProDeSocketEditPolicy Class Reference
#include <ProDeSocketEditPolicy.hh>
Public Member Functions
ProDeSocketEditPolicy ()
virtual ~ProDeSocketEditPolicy ()
virtual ComponentCommand * getCommand (Request *request)
virtual bool canHandle (Request *request) const
Public Member Functions inherited from EditPolicy
EditPolicy ()
virtual ~EditPolicy ()
EditPart * host () const
void setHost (EditPart *host)
Private Member Functions
ComponentCommand * createConnectCmd (Request *request)
ProDeSocketEditPolicy & operator= (ProDeSocketEditPolicy &old)
Assignment not allowed.
ProDeSocketEditPolicy (ProDeSocketEditPolicy &old)
Copying not allowed.
Additional Inherited Members
Protected Attributes inherited from EditPolicy
EditPart * host_
Host EditPart of this EditPolicy.
Detailed Description
Determines how a socket EditPart acts when a Request is performed on it.
Converts a given Request to a Command if the EditPolicy supports. the Request.
Definition at line 49 of file ProDeSocketEditPolicy.hh.
Constructor & Destructor Documentation
ProDeSocketEditPolicy() [1/2]
ProDeSocketEditPolicy::ProDeSocketEditPolicy ()
The Constructor.
Definition at line 61 of file ProDeSocketEditPolicy.cc.
                                            : EditPolicy() {
}
~ProDeSocketEditPolicy()
ProDeSocketEditPolicy::~ProDeSocketEditPolicy () virtual
The Destructor.
Definition at line 67 of file ProDeSocketEditPolicy.cc.
{
}
ProDeSocketEditPolicy() [2/2]
ProDeSocketEditPolicy::ProDeSocketEditPolicy (ProDeSocketEditPolicy & old) private
Copying not allowed.
Member Function Documentation
canHandle()
bool ProDeSocketEditPolicy::canHandle (Request * request) const virtual
Tells whether this EditPolicy is able to handle a certain type of Request.
Parameters
request Request to be asked if it can be handled.
Returns
True if the Request can be handled, false otherwise.
Implements EditPolicy.
Definition at line 115 of file ProDeSocketEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST ||
    type == Request::DELETE_REQUEST ||
        type == Request::COPY_REQUEST ||
        type == Request::STATUS_REQUEST) {
    return true;
    } else if (type == Request::CONNECT_REQUEST) {
        ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
        assert(cr != NULL);
        EditPart* part = cr->part();
        if (part == NULL) {
            // No selection.
            // Socket can be selected for connecting, return true.
            return true;
        }
        Port* port = dynamic_cast<Port*>(part->model());
        Segment* segment = dynamic_cast<Segment*>(part->model());
        if (port == NULL && segment == NULL) {
            // Socket can be connected only to ports and segments.
            return false;
        }
        MachineTester* tester = NULL;
        if (port != NULL) {
            tester = new MachineTester(*(port->parentUnit()->machine()));
        } else {
            tester = new MachineTester(*(segment->parentBus()->machine()));
        }
        Socket* socket = dynamic_cast<Socket*>(host_->model());
        if ((port != NULL && (
                 port->isConnectedTo(*socket) ||
                 tester->canConnect(*socket, *port))) ||
            (segment != NULL && (
                socket->isConnectedTo(*segment) ||
                tester->canConnect(*socket, *segment)))) {
            delete tester;
            return true;
        }
        delete tester;
        return false;
    } else {
    return false;
    }
}
References assert, MachineTester::canConnect(), Request::CONNECT_REQUEST, Request::COPY_REQUEST, Request::DELETE_REQUEST, EditPolicy::host_, TTAMachine::Socket::isConnectedTo(), TTAMachine::Port::isConnectedTo(), TTAMachine::Component::machine(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Segment::parentBus(), TTAMachine::Port::parentUnit(), ConnectRequest::part(), Request::STATUS_REQUEST, and Request::type().
Referenced by createConnectCmd().
createConnectCmd()
ComponentCommand * ProDeSocketEditPolicy::createConnectCmd (Request * request) private
Creates a command which connects the selected component to the requested component.
Parameters
request ConnectionRequest with the target component for the connection.
Returns
Command for connecting the selected and requested components.
Definition at line 173 of file ProDeSocketEditPolicy.cc.
{
    ConnectRequest* cr = dynamic_cast<ConnectRequest*>(request);
    assert(cr != NULL);
    EditPart* part = cr->part();
    if (canHandle(request)) {
        Port* port = dynamic_cast<Port*>(part->model());
        Segment* segment = dynamic_cast<Segment*>(part->model());
        Socket* socket = dynamic_cast<Socket*>(host_->model());
        if (port == NULL && segment == NULL) {
            return NULL;
        }
        ComponentCommand* cmd = NULL;
        if (port != NULL) {
            cmd = new SocketPortConnCmd(socket, port);
        } else {
            cmd = new SocketBusConnCmd(socket, segment);
        }
        return cmd;
    } else {
        return NULL;
    }
}
References assert, canHandle(), EditPolicy::host_, EditPart::model(), and ConnectRequest::part().
Referenced by getCommand().
getCommand()
ComponentCommand * ProDeSocketEditPolicy::getCommand (Request * request) virtual
Returns the Command corresponding to the type of the Request.
Parameters
request Request to be handled.
Returns
NULL if the Request cannot be handled.
Implements EditPolicy.
Definition at line 77 of file ProDeSocketEditPolicy.cc.
{
    Request::RequestType type = request->type();
    if (type == Request::MODIFY_REQUEST) {
        ModifySocketCmd* modifyCmd = new ModifySocketCmd(host_);
        return modifyCmd;
    } else if (type == Request::DELETE_REQUEST) {
        DeleteSocketCmd* deleteCmd = new DeleteSocketCmd(host_);
        return deleteCmd;
    } else if (type == Request::COPY_REQUEST) {
        CopyComponent* copyCmd = new CopyComponent(host_);
        return copyCmd;
    } else if (type == Request::STATUS_REQUEST) {
        Socket* socket = dynamic_cast<Socket*>(host_->model());
        ProDeTextGenerator* generator = ProDeTextGenerator::instance();
        format fmt = generator->text(ProDeTextGenerator::STATUS_SOCKET);
        fmt % socket->name();
        SetStatusTextCmd* statusCmd = new SetStatusTextCmd(fmt.str());
        return statusCmd;
    } if (type == Request::CONNECT_REQUEST) {
        return createConnectCmd(request);
    } else {
    return NULL;
    }
}
References Request::CONNECT_REQUEST, Request::COPY_REQUEST, createConnectCmd(), Request::DELETE_REQUEST, EditPolicy::host_, ProDeTextGenerator::instance(), EditPart::model(), Request::MODIFY_REQUEST, TTAMachine::Component::name(), Request::STATUS_REQUEST, ProDeTextGenerator::STATUS_SOCKET, Texts::TextGenerator::text(), and Request::type().
operator=()
ProDeSocketEditPolicy & ProDeSocketEditPolicy::operator= (ProDeSocketEditPolicy & old) private
Assignment not allowed.
The documentation for this class was generated from the following files:
ProDeSocketEditPolicy.hh
ProDeSocketEditPolicy.cc