OpenASIP: TTAProgram::Immediate Class Reference
TTAProgram::Immediate Class Reference
#include <Immediate.hh>
Public Member Functions
Immediate (TerminalImmediate *value, Terminal *dst)
virtual ~Immediate ()
const Terminal & destination () const
TerminalImmediate & value () const
void setValue (TerminalImmediate *value)
std::shared_ptr< Immediate > copy () const
Instruction * parent () const
void setParent (Instruction *ins)
Private Member Functions
Immediate (const Immediate &)
Copying not allowed.
Immediate & operator= (const Immediate &)
Assignment not allowed.
Private Attributes
TerminalImmediate * value_
Value of the immediate.
Terminal * dst_
The destination register.
Instruction * parent_
Instruction which contains this immediate.
Detailed Description
Represents the long immediate value and its transport into a dedicated register
Definition at line 54 of file Immediate.hh.
Constructor & Destructor Documentation
Immediate() [1/2]
TTAProgram::Immediate::Immediate (TerminalImmediate * value, Terminal * dst)
The constructor.
Creates a long immediate with the given value. The value specifies, implicitly, also the width of the instruction field(s) where the immediate bits are encoded). The destination register and the set of instruction slots where the immediate bits are encoded are also given as parameters.
The ownership of the destination terminal object will be passed to the immediate.
Parameters
value Value of the immediate.
dst Destination register.
Definition at line 68 of file Immediate.cc.
    : value_(value), dst_(dst), parent_(nullptr) {}
~Immediate()
TTAProgram::Immediate::~Immediate () virtual
The destructor.
Definition at line 74 of file Immediate.cc.
                      {
    if (dst_ != NULL) {
        delete dst_;
        dst_ = NULL;
    }
    if (value_ != NULL) {
        delete value_;
        value_ = NULL;
    }
}
References dst_, and value_.
Immediate() [2/2]
TTAProgram::Immediate::Immediate (const Immediate &) private
Copying not allowed.
Member Function Documentation
copy()
std::shared_ptr< Immediate > TTAProgram::Immediate::copy () const
Makes a copy of the immediate.
The copy is identical, except that it is not registered to the instruction of the original immediate (and therefore, any address it refers to is not meaningful).
Returns
A copy of the immediate.
Definition at line 131 of file Immediate.cc.
                      {
    return std::make_shared<Immediate>(
        dynamic_cast<TerminalImmediate*>(value_->copy()), dst_->copy());
}
References TTAProgram::TerminalImmediate::copy(), TTAProgram::Terminal::copy(), dst_, and value_.
Referenced by LoopPrologAndEpilogBuilder::build(), and TTAProgram::Instruction::copy().
destination()
const Terminal & TTAProgram::Immediate::destination () const
Returns the destination register of this immediate.
Returns
The destination register of this immediate.
Definition at line 92 of file Immediate.cc.
{
    assert(dst_ != NULL);
    return *dst_;
}
References assert, and dst_.
Referenced by CodeCompressorPlugin::addBitsForDstRegisterField(), ITemplateBroker::assign(), CopyingDelaySlotFiller::checkImmediatesAfter(), POMValidator::checkLongImmediates(), CopyingDelaySlotFiller::collectMoves(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createImmediateAssignment(), ControlFlowGraph::createJumps(), CompiledSimCodeGenerator::generateInstruction(), ITemplateBroker::isImmediateInTemplate(), main(), LoopPrologAndEpilogBuilder::optimizeProlog(), SimProgramBuilder::processInstruction(), CodeCompressorPlugin::programImmediate(), CopyingDelaySlotFiller::tryToAssignNodes(), and ITemplateBroker::unassignImmediate().
operator=()
Immediate & TTAProgram::Immediate::operator= (const Immediate &) private
Assignment not allowed.
parent()
Instruction * TTAProgram::Immediate::parent () const inline
Definition at line 67 of file Immediate.hh.
{ return parent_; }
References parent_.
Referenced by ITemplateBroker::assign(), ITemplateBroker::isAlreadyAssigned(), and ITemplateBroker::unassign().
setParent()
void TTAProgram::Immediate::setParent (Instruction * ins) inline
Definition at line 68 of file Immediate.hh.
{ parent_ = ins; }
References parent_.
Referenced by TTAProgram::Instruction::removeImmediate().
setValue()
void TTAProgram::Immediate::setValue (TerminalImmediate * value)
Sets the value of immediate.
Parameters
Value to set for immediate.
Definition at line 114 of file Immediate.cc.
{
    if (value_ != NULL) {
        delete value_;
    }
    value_ = value;
}
References value(), and value_.
Referenced by ITemplateBroker::assign(), ControlFlowGraph::convertBBRefsToInstRefs(), and TTAProgram::Program::convertSymbolRefsToInsRefs().
value()
TerminalImmediate & TTAProgram::Immediate::value () const
Returns the value of this immediate.
Returns
The value of this immediate.
Definition at line 103 of file Immediate.cc.
                       {
    assert(value_ != NULL);
    return *value_;
}
References assert, and value_.
Referenced by ITemplateBroker::assign(), CopyingDelaySlotFiller::checkImmediatesAfter(), POMValidator::checkLongImmediates(), CopyingDelaySlotFiller::collectMoves(), ControlFlowGraph::convertBBRefsToInstRefs(), TTAProgram::Program::convertSymbolRefsToInsRefs(), TTAProgram::ProgramWriter::createCodeSection(), POMDisassembler::createImmediateAssignment(), ControlFlowGraph::createJumps(), CodeCompressorPlugin::encodeLongImmediate(), TTAProgram::Program::fixInstructionReferences(), CompiledSimCodeGenerator::generateInstruction(), ProgramImageGenerator::generateProgramImage(), getInstructionReferenceTerminals(), ITemplateBroker::isImmediateInTemplate(), main(), SimProgramBuilder::processInstruction(), and setValue().
Member Data Documentation
dst_
Terminal* TTAProgram::Immediate::dst_ private
The destination register.
Definition at line 79 of file Immediate.hh.
Referenced by copy(), destination(), and ~Immediate().
parent_
Instruction* TTAProgram::Immediate::parent_ private
Instruction which contains this immediate.
Definition at line 82 of file Immediate.hh.
Referenced by parent(), and setParent().
value_
TerminalImmediate* TTAProgram::Immediate::value_ private
Value of the immediate.
Definition at line 76 of file Immediate.hh.
Referenced by copy(), setValue(), value(), and ~Immediate().
The documentation for this class was generated from the following files:
Immediate.hh
Immediate.cc