OpenASIP: TPEF::TPEFResourceSectionReader Class Reference
TPEF::TPEFResourceSectionReader Class Reference
#include <TPEFResourceSectionReader.hh>
Protected Member Functions
TPEFResourceSectionReader ()
virtual ~TPEFResourceSectionReader ()
virtual void readData (BinaryStream &stream, Section *section) const
virtual Section::SectionType type () const
Protected Member Functions inherited from TPEF::TPEFSectionReader
TPEFSectionReader ()
virtual BinaryReader * parent () const
virtual void readInfo (BinaryStream &stream, Section *sect) const
Protected Member Functions inherited from TPEF::SectionReader
SectionReader ()
virtual void finalize (Section *section) const
Private Member Functions
TPEFResourceSectionReader (const TPEFResourceSectionReader &)
Copying not allowed.
TPEFResourceSectionReader & operator= (TPEFResourceSectionReader &)
Assignment not allowed.
Static Private Attributes
static TPEFResourceSectionReader proto_
Prototype instance to be registered.
Additional Inherited Members
Public Types inherited from TPEF::SectionReader
typedef BinaryReader::Length Length
Public Member Functions inherited from TPEF::TPEFSectionReader
virtual ~TPEFSectionReader ()
Public Member Functions inherited from TPEF::SectionReader
virtual ~SectionReader ()
Static Public Member Functions inherited from TPEF::SectionReader
static void readSection (BinaryStream &stream, Section *section, BinaryReader *reader)
static void finalizeBinary (Binary *binaryToFinalize, BinaryReader *reader)
Static Protected Member Functions inherited from TPEF::TPEFSectionReader
static const Header & header ()
Static Protected Member Functions inherited from TPEF::SectionReader
static const SectionReader * findSectionReader (const Section::SectionType type, const BinaryReader *bReader)
static void registerSectionReader (const SectionReader *sReader)
Detailed Description
Reads Processor Resource Table section from TPEF binary file.
Definition at line 47 of file TPEFResourceSectionReader.hh.
Constructor & Destructor Documentation
TPEFResourceSectionReader() [1/2]
TPEF::TPEFResourceSectionReader::TPEFResourceSectionReader () protected
Constructor.
Registers itself to SectionReader.
Definition at line 58 of file TPEFResourceSectionReader.cc.
                                                     :
    TPEFSectionReader() {
    SectionReader::registerSectionReader(this);
}
References TPEF::SectionReader::registerSectionReader().
~TPEFResourceSectionReader()
TPEF::TPEFResourceSectionReader::~TPEFResourceSectionReader () protected virtual
Destructor.
Definition at line 66 of file TPEFResourceSectionReader.cc.
{
}
TPEFResourceSectionReader() [2/2]
TPEF::TPEFResourceSectionReader::TPEFResourceSectionReader (const TPEFResourceSectionReader &) private
Copying not allowed.
Member Function Documentation
operator=()
TPEFResourceSectionReader & TPEF::TPEFResourceSectionReader::operator= (TPEFResourceSectionReader &) private
Assignment not allowed.
readData()
void TPEF::TPEFResourceSectionReader::readData (BinaryStream & stream, Section * section) const protected virtual
Reads section data from TPEF binary file.
Parameters
stream Stream to be read from.
section Section where the information is to be stored.
Exceptions
UnreachableStream If reading of section fails.
KeyAlreadyExists Key was in use when trying to register object.
EndOfFile If end of file were reached while it shouldn't.
OutOfRange Some of read value were out of range.
WrongSubclass Some class couldn't do what it was asked for.
UnexpectedValue If there was unexpected value when reading.
Reimplemented from TPEF::TPEFSectionReader.
Definition at line 92 of file TPEFResourceSectionReader.cc.
{
    // base classes implementation must be called with these
    TPEFSectionReader::readData(stream, section);
    ResourceSection* resourceSection =
        dynamic_cast<ResourceSection*>(section);
    assert(resourceSection != NULL);
    // check that link section is defined properly
    assert(header().linkId != 0);
    if (!section->noBits()) {
        // store start of first element
        SectionOffset elementStart = header().bodyOffset;
        while (elementStart + header().elementSize <=
               header().bodyOffset + header().bodyLength) {
            ResourceElement *elem = new ResourceElement();
            // TODO: check that OP, SR and PORT share the same id space and
            // don't collide
            elem->setId(stream.readHalfWord());
            elem->setType(
                static_cast<ResourceElement::ResourceType>
                (stream.readByte()));
            SectionOffsetKey
                nameSectOffset(header().linkId, stream.readWord());
            elem->setName(CREATE_SAFEPOINTER(nameSectOffset));
            elem->setInfo(stream.readWord());
            section->addElement(elem);
            elementStart += header().elementSize;
            stream.setReadPosition(elementStart);
        }
    }
}
References TPEF::Section::addElement(), assert, TPEF::TPEFSectionReader::Header::bodyOffset, TPEF::TPEFSectionReader::Header::elementSize, TPEF::TPEFSectionReader::header(), TPEF::Section::noBits(), TPEF::BinaryStream::readByte(), TPEF::TPEFSectionReader::readData(), TPEF::BinaryStream::readHalfWord(), TPEF::BinaryStream::readWord(), TPEF::ResourceElement::setId(), TPEF::ResourceElement::setInfo(), TPEF::ResourceElement::setName(), TPEF::BinaryStream::setReadPosition(), and TPEF::ResourceElement::setType().
type()
Section::SectionType TPEF::TPEFResourceSectionReader::type () const protected virtual
Returns the type of section which reader can read.
Returns
The type of section which reader can read.
Implements TPEF::SectionReader.
Definition at line 75 of file TPEFResourceSectionReader.cc.
{
    return Section::ST_MR;
}
References TPEF::Section::ST_MR.
Member Data Documentation
proto_
TPEFResourceSectionReader TPEF::TPEFResourceSectionReader::proto_ static private
Prototype instance to be registered.
Definition at line 63 of file TPEFResourceSectionReader.hh.
The documentation for this class was generated from the following files:
TPEFResourceSectionReader.hh
TPEFResourceSectionReader.cc