OpenASIP: TTAProgram::InstructionReference Class Reference
TTAProgram::InstructionReference Class Reference
#include <InstructionReference.hh>
Public Member Functions
InstructionReference (InstructionReferenceImpl *impl)
InstructionReference (const InstructionReference &ir)
virtual ~InstructionReference ()
InstructionReference & operator= (const InstructionReference &)
Instruction & instruction () const
bool setImpl (InstructionReferenceImpl *impl)
bool operator== (const InstructionReference &other) const
Private Attributes
InstructionReferenceImpl * impl_
Detailed Description
Represents a reference to an Instruction instance.
The target of the reference can be changed as needed.
Definition at line 49 of file InstructionReference.hh.
Constructor & Destructor Documentation
InstructionReference() [1/2]
TTAProgram::InstructionReference::InstructionReference (InstructionReferenceImpl * impl) explicit
Constructor.
Note
Instruction references should be created using InstructionReferenceManager.
Parameters
ins Referred instruction.
Definition at line 51 of file InstructionReference.cc.
                                                                        :
    impl_(impl) {
    if (impl_ != NULL) {
        impl_->addRef(*this);
    }
}
References TTAProgram::InstructionReferenceImpl::addRef(), and impl_.
InstructionReference() [2/2]
TTAProgram::InstructionReference::InstructionReference (const InstructionReference & ref)
Constructor.
Note
Instruction references should be created using InstructionReferenceManager.
Parameters
ins Referred instruction.
Definition at line 65 of file InstructionReference.cc.
                                                                         :
    impl_(ref.impl_) {
    if (impl_ != NULL) {
        impl_->addRef(*this);
    }
}
References TTAProgram::InstructionReferenceImpl::addRef(), and impl_.
~InstructionReference()
TTAProgram::InstructionReference::~InstructionReference () virtual
Destructor.
Tells the impl that we are no longer pointing to it. It may get also deleted if this was the last reference to it.
Definition at line 103 of file InstructionReference.cc.
{
    if (impl_ != NULL) {
        impl_->removeRef(*this);
    }
}
References impl_, and TTAProgram::InstructionReferenceImpl::removeRef().
Member Function Documentation
instruction()
Instruction & TTAProgram::InstructionReference::instruction () const
Returns the referred instruction.
Returns
Referred instruction.
Definition at line 138 of file InstructionReference.cc.
{
    if (impl_ == NULL) {
        return NullInstruction::instance();
    } else {
        return impl_->instruction();
    }
}
References impl_, TTAProgram::NullInstruction::instance(), and TTAProgram::InstructionReferenceImpl::instruction().
Referenced by TTAProgram::CodeLabel::address(), TTAProgram::TerminalInstructionReference::address(), TTAProgram::CodeLabel::CodeLabel(), ControlFlowGraph::computeLeadersFromJumpSuccessors(), ProcedurePass::copyCfgToProcedure(), ControlFlowGraph::createBBEdges(), ControlFlowGraph::createJumps(), TTAProgram::DataInstructionAddressDef::destinationAddress(), POMDisassembler::disassemble(), TTAProgram::TerminalBasicBlockReference::equals(), TTAProgram::TerminalInstructionReference::equals(), TTAProgram::Program::fixInstructionReferences(), TTAProgram::CodeLabel::instructionReference(), ControlFlowGraph::jumpToBBN(), TTAProgram::CodeLabel::procedure(), and ControlFlowGraph::removeJumpToTarget().
operator=()
InstructionReference & TTAProgram::InstructionReference::operator= (const InstructionReference & ref)
Assignment operator.
Changes this reference to point to another instruction. Only changes this reference, not other references pointing to same instruction.
Definition at line 79 of file InstructionReference.cc.
{
    // if both point to same instruction, no need to do anything.
    if (ref.impl_ != impl_) {
        // stop pointing to old instruction
        if (impl_ != NULL) {
            impl_->removeRef(*this);
        }
        // pointing to new instruction
        impl_ = ref.impl_;
        if (impl_ != NULL) {
            impl_->addRef(*this);
        }
    }
    return *this;
}
References TTAProgram::InstructionReferenceImpl::addRef(), impl_, and TTAProgram::InstructionReferenceImpl::removeRef().
operator==()
bool TTAProgram::InstructionReference::operator== (const InstructionReference & other) const
Definition at line 147 of file InstructionReference.cc.
{
    return impl_ == other.impl_;
}
References impl_.
setImpl()
bool TTAProgram::InstructionReference::setImpl (InstructionReferenceImpl * newImpl)
Sets a new referred instruction.
The InstructionReferenceImpl is a "proxy object" that counts and keeps book of references
Parameters
newImpl New referred instruction.
Returns
true if old impl stays alive, false if it is deleted.
Definition at line 119 of file InstructionReference.cc.
{
    bool staysAlive = true;
    assert(newImpl != impl_);
    if (impl_ != NULL) {
        staysAlive = impl_->removeRef(*this);
    }
    impl_ = newImpl;
    if (impl_ != NULL) {
        impl_->addRef(*this);
    }
    return staysAlive;
}
References TTAProgram::InstructionReferenceImpl::addRef(), assert, impl_, and TTAProgram::InstructionReferenceImpl::removeRef().
Member Data Documentation
impl_
InstructionReferenceImpl* TTAProgram::InstructionReference::impl_ private
Definition at line 64 of file InstructionReference.hh.
Referenced by instruction(), InstructionReference(), InstructionReference(), operator=(), operator==(), setImpl(), and ~InstructionReference().
The documentation for this class was generated from the following files:
InstructionReference.hh
InstructionReference.cc