OpenASIP: NullOperationBehavior Class Reference
NullOperationBehavior Class Reference
#include <OperationBehavior.hh>
Public Member Functions
virtual bool simulateTrigger (SimValue **, OperationContext &context) const
virtual bool lateResult (SimValue **, OperationContext &context) const
Public Member Functions inherited from OperationBehavior
virtual bool areValid (const InputOperandVector &inputs, const OperationContext &context) const
virtual void createState (OperationContext &context) const
virtual void deleteState (OperationContext &context) const
virtual const char * stateName () const
virtual bool canBeSimulated () const
virtual void writeOutput (const char *text) const
OperationBehavior ()
OperationBehavior (const Operation &parent)
virtual ~OperationBehavior ()
Static Public Member Functions
static NullOperationBehavior & instance ()
Protected Member Functions
NullOperationBehavior ()
Static Private Attributes
static NullOperationBehavior instance_
Additional Inherited Members
Public Types inherited from OperationBehavior
typedef std::vector< SimValue > InputOperandVector
Input operand type for areValid()
Protected Attributes inherited from OperationBehavior
const Operation & parent_
Detailed Description
Singleton class to represent an undefined operation behavior.
All methods cause program abort with an error log message.
Definition at line 93 of file OperationBehavior.hh.
Constructor & Destructor Documentation
NullOperationBehavior()
NullOperationBehavior::NullOperationBehavior () inline protected
Definition at line 105 of file OperationBehavior.hh.
{ }
Member Function Documentation
instance()
static NullOperationBehavior & NullOperationBehavior::instance () inline static
Definition at line 95 of file OperationBehavior.hh.
{ return instance_; }
References instance_.
Referenced by NullOperation::behavior(), OSEdTreeView::constructTree(), OperationIndex::effectiveOperation(), RISCVInstructionExecutor::executeInstructionHelper(), OperationPoolPimpl::loadFromLLVM(), OperationContainer::operation(), and OperationPropertyDialog::OperationPropertyDialog().
lateResult()
bool NullOperationBehavior::lateResult (SimValue ** , OperationContext & context) const virtual
Writes an error message to error log and aborts the program.
Parameters
io Not used.
context Not used.
Returns
Never returns.
Definition at line 198 of file OperationBehavior.cc.
{
    abortWithError(ERROR_MESSAGE);
    return true;
}
References abortWithError, and ERROR_MESSAGE.
simulateTrigger()
bool NullOperationBehavior::simulateTrigger (SimValue ** , OperationContext & context) const virtual
Writes an error message to error log and aborts the program.
Parameters
io Not used.
context Not used.
Returns
Never returns.
Implements OperationBehavior.
Definition at line 182 of file OperationBehavior.cc.
{
    abortWithError(ERROR_MESSAGE);
    return true;
}
References abortWithError, and ERROR_MESSAGE.
Member Data Documentation
instance_
NullOperationBehavior NullOperationBehavior::instance_ static private
Definition at line 108 of file OperationBehavior.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
OperationBehavior.hh
OperationBehavior.cc