OpenASIP: IPXactSerializer Class Reference
IPXactSerializer Class Reference
#include <IPXactSerializer.hh>
Public Member Functions
IPXactSerializer ()
virtual ~IPXactSerializer ()
virtual void writeState (const ObjectState *ipXactState)
void writeIPXactModel (const IPXactModel &model)
Public Member Functions inherited from XMLSerializer
XMLSerializer ()
virtual ~XMLSerializer ()
void setSourceFile (const std::string &fileName)
void setSourceString (const std::string &source)
void setDestinationFile (const std::string &fileName)
void setDestinationString (std::string &destination)
void setSchemaFile (const std::string &fileName)
void setUseSchema (bool useSchema)
void setXMLNamespace (std::string nsUri)
Public Member Functions inherited from TCETools::Serializer
virtual ~Serializer ()
Private Member Functions
IPXactSerializer (const IPXactSerializer &)
Copying forbidden.
IPXactSerializer & operator= (const IPXactSerializer &)
Assingment forbidden.
ObjectState * readState ()
Reading is not (yet) implemented.
Static Private Attributes
static const TCEString SPIRIT_NS_URI
Additional Inherited Members
Protected Member Functions inherited from XMLSerializer
std::string sourceFile () const
Detailed Description
Definition at line 40 of file IPXactSerializer.hh.
Constructor & Destructor Documentation
IPXactSerializer() [1/2]
IPXactSerializer::IPXactSerializer ()
Definition at line 40 of file IPXactSerializer.cc.
                                  : XMLSerializer() {
    setUseSchema(false);
}
References XMLSerializer::setUseSchema().
~IPXactSerializer()
IPXactSerializer::~IPXactSerializer () virtual
Definition at line 46 of file IPXactSerializer.cc.
{
}
IPXactSerializer() [2/2]
IPXactSerializer::IPXactSerializer (const IPXactSerializer &) private
Copying forbidden.
Member Function Documentation
operator=()
IPXactSerializer & IPXactSerializer::operator= (const IPXactSerializer &) private
Assingment forbidden.
readState()
ObjectState * IPXactSerializer::readState () private virtual
Reading is not (yet) implemented.
Reimplemented from XMLSerializer.
Definition at line 64 of file IPXactSerializer.cc.
{
    return NULL;
}
writeIPXactModel()
void IPXactSerializer::writeIPXactModel (const IPXactModel & model)
Definition at line 56 of file IPXactSerializer.cc.
{
    ObjectState* omState = model.saveState();
    writeState(omState);
    delete omState;
}
References IPXactModel::saveState(), and writeState().
Referenced by IPXactFileGenerator::writeProjectFiles().
writeState()
void IPXactSerializer::writeState (const ObjectState * state) virtual
Writes the given object state to a file or string.
File is written if a destiantion file is set with setDestinationFile(). String is written if a destination string is set with setDestinationString(). Only the last file/string set will be written.
Reimplemented from XMLSerializer.
Definition at line 50 of file IPXactSerializer.cc.
{
    XMLSerializer::setXMLNamespace(SPIRIT_NS_URI);
    XMLSerializer::writeState(ipXactState);
}
References XMLSerializer::setXMLNamespace(), SPIRIT_NS_URI, and XMLSerializer::writeState().
Referenced by writeIPXactModel().
Member Data Documentation
SPIRIT_NS_URI
const TCEString IPXactSerializer::SPIRIT_NS_URI static private
Initial value:
=
    "http://www.spiritconsortium.org/XMLSchema/SPIRIT/1.5"
Definition at line 59 of file IPXactSerializer.hh.
Referenced by writeState().
The documentation for this class was generated from the following files:
IPXactSerializer.hh
IPXactSerializer.cc