OpenASIP: DisassemblyAnnotation Class Reference
DisassemblyAnnotation Class Reference
#include <DisassemblyAnnotation.hh>
Public Member Functions
DisassemblyAnnotation (Word id, const std::vector< Byte > &payload)
virtual ~DisassemblyAnnotation ()
virtual std::string toString () const
Public Member Functions inherited from DisassemblyElement
virtual ~DisassemblyElement ()
Private Attributes
Word id_
Annotation id.
std::vector< Byte > payload_
Name of the operation.
Additional Inherited Members
Protected Member Functions inherited from DisassemblyElement
DisassemblyElement ()
Detailed Description
Represents an annotation.
Definition at line 44 of file DisassemblyAnnotation.hh.
Constructor & Destructor Documentation
DisassemblyAnnotation()
DisassemblyAnnotation::DisassemblyAnnotation (Word id, const std::vector< Byte > & payload)
Constructor.
Parameters
id Id of the annotation.
payload Data for the annotation.
Definition at line 45 of file DisassemblyAnnotation.cc.
                                            :
    DisassemblyElement(), id_(id), payload_(payload) {
}
~DisassemblyAnnotation()
DisassemblyAnnotation::~DisassemblyAnnotation () virtual
Destructor.
Definition at line 53 of file DisassemblyAnnotation.cc.
{
}
Member Function Documentation
toString()
string DisassemblyAnnotation::toString () const virtual
Returns disassembly of the annotation.
Implements DisassemblyElement.
Definition at line 61 of file DisassemblyAnnotation.cc.
{
    std::stringstream retVal;
    retVal << "{" << std::hex << "0x" << id_;
    for (unsigned int i = 0; i < payload_.size(); i++) {
        retVal << " " << int(payload_[i]);
    }
    retVal << "}";
    return retVal.str();
}
References id_, and payload_.
Referenced by DisassemblyImmediateAssignment::toString(), DisassemblyInstruction::toString(), and DisassemblyMove::toString().
Member Data Documentation
id_
Word DisassemblyAnnotation::id_ private
Annotation id.
Definition at line 52 of file DisassemblyAnnotation.hh.
Referenced by toString().
payload_
std::vector<Byte> DisassemblyAnnotation::payload_ private
Name of the operation.
Definition at line 54 of file DisassemblyAnnotation.hh.
Referenced by toString().
The documentation for this class was generated from the following files:
DisassemblyAnnotation.hh
DisassemblyAnnotation.cc