OpenASIP: SmartHWOperation Class Reference
SmartHWOperation Class Reference
#include <SmartHWOperation.hh>
Public Member Functions
SmartHWOperation (const Operation &operation, UniversalFunctionUnit &parent)
virtual ~SmartHWOperation ()
virtual void setName (const std::string &name)
TTAMachine::FUPort * port (int operand) const
UniversalFunctionUnit * parentUnit () const
virtual void bindPort (int operand, const TTAMachine::FUPort &port)
virtual void unbindPort (const TTAMachine::FUPort &port)
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::HWOperation
HWOperation (const std::string &name, FunctionUnit &parent)
HWOperation (const ObjectState *state, FunctionUnit &parent)
~HWOperation ()
const std::string & name () const
FunctionUnit * parentUnit () const
ExecutionPipeline * pipeline () const
int latency () const
int latency (int output) const
int slack (int input) const
int operandCount () const
bool isBound (const FUPort &port) const
bool isBound (int operand) const
int io (const FUPort &port) const
int numberOfInputs () const
int numberOfOutputs () const
virtual ObjectState * saveState () const
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Member Functions
bool otherMandatoryInputsBound (int operand) const
Private Attributes
const Operation & operation_
The operation represented by this SmartHWOperation instance.
bool is32BitOperation_
Tells whether this operation has 32 bits wide operands.
Additional Inherited Members
Static Public Attributes inherited from TTAMachine::HWOperation
static const std::string OSNAME_OPERATION = "operation"
ObjectState name for HWOperation.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for name of the operation.
static const std::string OSNAME_OPERAND_BINDING = "binding"
ObjectState name for an operand binding.
static const std::string OSKEY_OPERAND = "operand"
ObjectState attribute key for operand index.
static const std::string OSKEY_PORT = "port"
ObjectState attribute key for port name.
Protected Member Functions inherited from TTAMachine::SubComponent
SubComponent ()
virtual ~SubComponent ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
Represents an operation in a function unit. The smart operation automatically creates operand bindings on demand. This kind of operations are used in UniversalFunctionUnit. The last operand requested is bound to the operation code setting port.
Definition at line 47 of file SmartHWOperation.hh.
Constructor & Destructor Documentation
SmartHWOperation()
SmartHWOperation::SmartHWOperation (const Operation & operation, UniversalFunctionUnit & parent)
The constructor.
Creates the pipeline automatically.
Parameters
operation The operation to be constructed.
parent The parent unit of the operation.
Exceptions
ComponentAlreadyExists If there is already an operation by the same name in the given function unit.
InvalidName If the given operation does not have a valid name.
Definition at line 54 of file SmartHWOperation.cc.
    : HWOperation(operation.name(), parent), operation_(operation) {
    is32BitOperation_ =
        UniversalFunctionUnit::is32BitOperation(operation.name());
    int inputs = operation.numberOfInputs();
    int outputs = operation.numberOfOutputs();
    // create pipeline
    ExecutionPipeline* pLine = pipeline();
    for (int operand = 1; operand <= inputs; operand++) {
        pLine->addPortRead(operand, 0, 1);
    }
    for (int operand = inputs + 1; operand <= inputs + outputs; operand++) {
        pLine->addPortWrite(operand, 0, 1);
    }
}
References TTAMachine::ExecutionPipeline::addPortRead(), TTAMachine::ExecutionPipeline::addPortWrite(), UniversalFunctionUnit::is32BitOperation(), is32BitOperation_, Operation::name(), Operation::numberOfInputs(), Operation::numberOfOutputs(), and TTAMachine::HWOperation::pipeline().
~SmartHWOperation()
SmartHWOperation::~SmartHWOperation () virtual
The destructor.
Definition at line 76 of file SmartHWOperation.cc.
{
}
Member Function Documentation
bindPort()
void SmartHWOperation::bindPort (int operand, const TTAMachine::FUPort & port) virtual
Aborts the program. It is not allowed to bind ports manually. DO NOT CALL THIS METHOD!
Parameters
operand Never used.
port Never used.
Exceptions
IllegalRegistration Never thrown.
ComponentAlreadyExists Never thrown.
OutOfRange Never thrown.
Reimplemented from TTAMachine::HWOperation.
Definition at line 205 of file SmartHWOperation.cc.
{
    const string procName = "SmartHWOperation::bindPort";
    const string errorMsg =
        "Tried to bind port of SmartHWOperation manually!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
loadState()
void SmartHWOperation::loadState (const ObjectState * state) virtual
Aborts the program. It is not allowed to load state of SmartHWOperation from an ObjectState tree. DO NOT CALL THIS METHOD!
Parameters
state Never used.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::HWOperation.
Definition at line 237 of file SmartHWOperation.cc.
{
    const string procName = "SmartHWOperation::loadState";
    const string errorMsg =
        "Tried load state of SmartHWOperation from an ObjectState tree!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
otherMandatoryInputsBound()
bool SmartHWOperation::otherMandatoryInputsBound (int operand) const private
Tells whether other input operands except the given one are bound to some port.
Parameters
operand The operand.
Returns
True if other inputs are bound, otherwise false.
Definition at line 253 of file SmartHWOperation.cc.
{
   assert(operand <= operation_.numberOfInputs());
   for (int opIndex = 1; opIndex <= operation_.numberOfInputs();
        opIndex++) {
       if (opIndex == operand) {
           continue;
       } else {
           if (HWOperation::port(opIndex) == NULL) {
               return false;
           }
       }
   }
   return true;
}
References assert, Operation::numberOfInputs(), operation_, and TTAMachine::HWOperation::port().
Referenced by port().
parentUnit()
UniversalFunctionUnit * SmartHWOperation::parentUnit () const
Returns the parent unit of the operation.
Returns
The parent unit.
Definition at line 185 of file SmartHWOperation.cc.
{
    FunctionUnit* parent = HWOperation::parentUnit();
    UniversalFunctionUnit* uFU =
        dynamic_cast<UniversalFunctionUnit*>(parent);
    assert(uFU != NULL);
    return uFU;
}
References assert, and TTAMachine::HWOperation::parentUnit().
Referenced by port().
port()
FUPort * SmartHWOperation::port (int operand) const virtual
Returns the port bound to the given operand. If the given operand is not bound yet, it is automatically bound to a port.
The port to which the operand will be bound depends on the bindings of other operands. Input operands are bound to input ports and output operands to output ports, of course. If all the input operands are bound already except the given one, the given operand will be bound to the operation code setting port.
Parameters
operand The operand.
Returns
The port to which the operand is bound.
Reimplemented from TTAMachine::HWOperation.
Definition at line 110 of file SmartHWOperation.cc.
{
    // if the operand is bound already, just return the port
    if (HWOperation::port(operand) != NULL) {
        return HWOperation::port(operand);
    }
    bool input = true;
    // check whether the operand is input or output operand
    if (operand > operation_.numberOfInputs() +
        operation_.numberOfOutputs()) {
        return NULL;
    } else if (operand > operation_.numberOfInputs()) {
        input = false;
    }
    int bitWidth = is32BitOperation_ ? 32 : 64;
    int portCount = parentUnit()->portCountWithWidth(bitWidth);
    if (input) {
        if (otherMandatoryInputsBound(operand)) {
            // bind to opcode port if other inputs are bound already
            FUPort* opcodePort;
            if (is32BitOperation_) {
                opcodePort =
                    static_cast<FunctionUnit*>(parentUnit())->operationPort(
                        UniversalFunctionUnit::OC_SETTING_PORT_32);
            } else {
                opcodePort =
                    static_cast<FunctionUnit*>(parentUnit())->operationPort(
                        UniversalFunctionUnit::OC_SETTING_PORT_64);
            }
            const_cast<SmartHWOperation*>(this)->
                HWOperation::bindPort(operand, *opcodePort);
            return opcodePort;
        } else {
            // bind to a non-opcode input port otherwise
            for (int i = 0; i < portCount; i++) {
                FUPort& port = parentUnit()->portWithWidth(i, bitWidth);
                if (!isBound(port) && port.inputSocket() != NULL &&
                    !port.isOpcodeSetting()) {
                    const_cast<SmartHWOperation*>(this)->
                        HWOperation::bindPort(operand, port);
                    return &port;
                }
            }
        }
    } else {
        // bind to some output port
        for (int i = 0; i < portCount; i++) {
            FUPort& port = parentUnit()->portWithWidth(i, bitWidth);
            if (!isBound(port) && port.outputSocket() != NULL) {
                const_cast<SmartHWOperation*>(this)->
                    HWOperation::bindPort(operand, port);
                return &port;
            }
        }
    }
    assert(false);
    // dummy return to avoid compilation warning
    return NULL;
}
References assert, TTAMachine::HWOperation::bindPort(), TTAMachine::Port::inputSocket(), is32BitOperation_, TTAMachine::HWOperation::isBound(), TTAMachine::FUPort::isOpcodeSetting(), Operation::numberOfInputs(), Operation::numberOfOutputs(), UniversalFunctionUnit::OC_SETTING_PORT_32, UniversalFunctionUnit::OC_SETTING_PORT_64, operation_, otherMandatoryInputsBound(), TTAMachine::Port::outputSocket(), parentUnit(), TTAMachine::HWOperation::port(), port(), UniversalFunctionUnit::portCountWithWidth(), and UniversalFunctionUnit::portWithWidth().
Referenced by port().
setName()
void SmartHWOperation::setName (const std::string & name) virtual
Aborts the program. It is not allowed to set the name of SmartHWOperation. DO NOT CALL THIS METHOD!
Parameters
name Never used.
Exceptions
ComponentAlreadyExists Never thrown.
InvalidName Never thrown.
Reimplemented from TTAMachine::HWOperation.
Definition at line 89 of file SmartHWOperation.cc.
{
    const string procName = "SmartHWOperation::setName";
    const string errorMsg = "Tried to set name of SmartHWOperation!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
unbindPort()
void SmartHWOperation::unbindPort (const TTAMachine::FUPort & port) virtual
Aborts the program. It is not allowed to unbind ports manually. DO NOT CALL THIS METHOD!
Parameters
port Never used.
Reimplemented from TTAMachine::HWOperation.
Definition at line 220 of file SmartHWOperation.cc.
{
    const string procName = "SmartHWOperation::unbindPort";
    const string errorMsg =
        "Tried unbind port of SmartHWOperation manually!";
    Application::writeToErrorLog(__FILE__, __LINE__, procName, errorMsg);
    Application::abortProgram();
}
References Application::abortProgram(), and Application::writeToErrorLog().
Member Data Documentation
is32BitOperation_
bool SmartHWOperation::is32BitOperation_ private
Tells whether this operation has 32 bits wide operands.
Definition at line 68 of file SmartHWOperation.hh.
Referenced by port(), and SmartHWOperation().
operation_
const Operation& SmartHWOperation::operation_ private
The operation represented by this SmartHWOperation instance.
Definition at line 66 of file SmartHWOperation.hh.
Referenced by otherMandatoryInputsBound(), and port().
The documentation for this class was generated from the following files:
SmartHWOperation.hh
SmartHWOperation.cc