OpenASIP: TestHDBCmdLineOptions Class Reference
TestHDBCmdLineOptions Class Reference
#include <TestHDBCmdLineOptions.hh>
Public Member Functions
TestHDBCmdLineOptions ()
~TestHDBCmdLineOptions ()
bool isFUEntryIDGiven () const
bool isRFEntryIDGiven () const
bool verbose () const
bool leaveDirty () const
int fuEntryID () const
int rfEntryID () const
std::string hdbFile () const
std::string vhdlSim () const
virtual void printVersion () const
virtual void printHelp () const
Public Member Functions inherited from CmdLineOptions
CmdLineOptions (std::string description, std::string version="")
virtual ~CmdLineOptions ()
void parse (char *argv[], int argc)
void parse (std::string argv[], int argc)
void parse (std::vector< std::string > argv)
virtual bool isVerboseSwitchDefined () const
virtual bool isVerboseSpamSwitchDefined () const
Public Member Functions inherited from CmdLineParser
CmdLineParser (std::string description)
virtual ~CmdLineParser ()
virtual void storeOptions (Options &options)
virtual int numberOfArguments () const
virtual std::string argument (int index) const
Static Private Attributes
static const std::string FU_ID_PARAM_NAME = "fuid"
Long name of the FUentryID parameter.
static const std::string RF_ID_PARAM_NAME = "rfid"
Long name of the RFentryID parameter.
static const std::string VERBOSE_PARAM_NAME = "verbose"
Long name of verbose output parameter.
static const std::string DIRTY_PARAM_NAME = "leave-dirty"
Long name of leave dirty parameter.
static const std::string SIM_PARAM_NAME = "simulator"
Long name of VHDL simulator parameter.
Additional Inherited Members
Protected Member Functions inherited from CmdLineOptions
bool optionGiven (std::string key) const
Protected Member Functions inherited from CmdLineParser
void addOption (CmdLineOptionParser *opt)
CmdLineOptionParser * findOption (std::string name) const
bool parseOption (std::string option, std::string &name, std::string &arguments, std::string &prefix, bool &hasArgument) const
bool readPrefix (std::string &option, std::string &prefix, bool &longOption) const
bool isPrefix (std::string name) const
Protected Attributes inherited from CmdLineParser
std::map< std::string, CmdLineOptionParser * > optionLongNames_
Database for holding options with their long names as a key.
std::map< std::string, CmdLineOptionParser * > optionShortNames_
Database for holding options with their short names as a key.
std::vector< std::string > commandLine_
Command line is stored here.
std::vector< std::string > arguments_
Command line arguments are stored here.
std::vector< std::string > prefixes_
Legal prefixes are stored here.
Detailed Description
Definition at line 39 of file TestHDBCmdLineOptions.hh.
Constructor & Destructor Documentation
TestHDBCmdLineOptions()
TestHDBCmdLineOptions::TestHDBCmdLineOptions ()
The constructor.
Definition at line 48 of file TestHDBCmdLineOptions.cc.
                                            : CmdLineOptions("") {
    IntegerCmdLineOptionParser* fuEntryID =
        new IntegerCmdLineOptionParser(
            FU_ID_PARAM_NAME, "Entry id of FU component to be tested. If this"
            " is and RF ID are not defined whole HDB will be tested.", "f");
    addOption(fuEntryID);
    IntegerCmdLineOptionParser* rfEntryID =
        new IntegerCmdLineOptionParser(
            RF_ID_PARAM_NAME, "Entry id of RF component to be tested. If this"
            " is and FU ID are not defined whole HDB will be tested.", "r");
    addOption(rfEntryID);
    BoolCmdLineOptionParser* verbose =
        new BoolCmdLineOptionParser(
            VERBOSE_PARAM_NAME, "Enable verbose output", "v");
    addOption(verbose);
    BoolCmdLineOptionParser* dirty =
        new BoolCmdLineOptionParser(
            DIRTY_PARAM_NAME, "Don't delete created files", "d");
    addOption(dirty);
    StringCmdLineOptionParser* simulator =
        new StringCmdLineOptionParser(
            SIM_PARAM_NAME, "HDL simulator used to simulate testbench. "
            "Accepted values are 'ghdl' and 'modelsim'. Default is ghdl",
            "s");
    addOption(simulator);
}
References CmdLineParser::addOption(), DIRTY_PARAM_NAME, FU_ID_PARAM_NAME, fuEntryID(), RF_ID_PARAM_NAME, rfEntryID(), SIM_PARAM_NAME, verbose(), and VERBOSE_PARAM_NAME.
~TestHDBCmdLineOptions()
TestHDBCmdLineOptions::~TestHDBCmdLineOptions ()
The destructor.
Definition at line 78 of file TestHDBCmdLineOptions.cc.
{
}
Member Function Documentation
fuEntryID()
int TestHDBCmdLineOptions::fuEntryID () const
Returns FU entryID
Returns
The FU entryID
Definition at line 126 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(FU_ID_PARAM_NAME);
    return option->integer();
}
References CmdLineParser::findOption(), FU_ID_PARAM_NAME, and CmdLineOptionParser::integer().
Referenced by TestHDBCmdLineOptions().
hdbFile()
std::string TestHDBCmdLineOptions::hdbFile () const
Returns HDB file name
Returns
The HDB file name
Definition at line 147 of file TestHDBCmdLineOptions.cc.
{
    return argument(numberOfArguments());
}
References CmdLineParser::argument(), and CmdLineParser::numberOfArguments().
isFUEntryIDGiven()
bool TestHDBCmdLineOptions::isFUEntryIDGiven () const
Returns information whether this option was given
Returns
Is FU entryID defined
Definition at line 86 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(FU_ID_PARAM_NAME);
    return option->isDefined();
}
References CmdLineParser::findOption(), FU_ID_PARAM_NAME, and CmdLineOptionParser::isDefined().
isRFEntryIDGiven()
bool TestHDBCmdLineOptions::isRFEntryIDGiven () const
Returns information whether this option was given
Returns
Is RF entryID defined
Definition at line 96 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(RF_ID_PARAM_NAME);
    return option->isDefined();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isDefined(), and RF_ID_PARAM_NAME.
leaveDirty()
bool TestHDBCmdLineOptions::leaveDirty () const
Returns information whether this option was given
Returns
Is leave dirty defined
Definition at line 116 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(DIRTY_PARAM_NAME);
    return option->isFlagOn();
}
References DIRTY_PARAM_NAME, CmdLineParser::findOption(), and CmdLineOptionParser::isFlagOn().
printHelp()
void TestHDBCmdLineOptions::printHelp () const virtual
Prints help of the application.
Reimplemented from CmdLineOptions.
Definition at line 172 of file TestHDBCmdLineOptions.cc.
{
    printVersion();
    std::cout << "Usage: testhdb <options> HDB-file" << std::endl;
    CmdLineOptions::printHelp();
}
References CmdLineOptions::printHelp(), and printVersion().
printVersion()
void TestHDBCmdLineOptions::printVersion () const virtual
Prints the version of the application.
Implements CmdLineOptions.
Definition at line 164 of file TestHDBCmdLineOptions.cc.
{
    std::cout << "testhdb - HDB test utility "
              << Application::TCEVersionString() << std::endl;
}
References Application::TCEVersionString().
Referenced by printHelp().
rfEntryID()
int TestHDBCmdLineOptions::rfEntryID () const
Returns RF entryID
Returns
The RF entryID
Definition at line 136 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(RF_ID_PARAM_NAME);
    return option->integer();
}
References CmdLineParser::findOption(), CmdLineOptionParser::integer(), and RF_ID_PARAM_NAME.
Referenced by TestHDBCmdLineOptions().
verbose()
bool TestHDBCmdLineOptions::verbose () const
Returns information whether this option was given
Returns
Is verbose output defined
Definition at line 106 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(VERBOSE_PARAM_NAME);
    return option->isFlagOn();
}
References CmdLineParser::findOption(), CmdLineOptionParser::isFlagOn(), and VERBOSE_PARAM_NAME.
Referenced by TestHDBCmdLineOptions().
vhdlSim()
std::string TestHDBCmdLineOptions::vhdlSim () const
Returns HDL simulator to be used
Returns
The HDL simulator name
Definition at line 156 of file TestHDBCmdLineOptions.cc.
{
    CmdLineOptionParser* option = findOption(SIM_PARAM_NAME);
    return option->String();
}
References CmdLineParser::findOption(), SIM_PARAM_NAME, and CmdLineOptionParser::String().
Member Data Documentation
DIRTY_PARAM_NAME
const std::string TestHDBCmdLineOptions::DIRTY_PARAM_NAME = "leave-dirty" static private
Long name of leave dirty parameter.
Definition at line 71 of file TestHDBCmdLineOptions.hh.
Referenced by leaveDirty(), and TestHDBCmdLineOptions().
FU_ID_PARAM_NAME
const std::string TestHDBCmdLineOptions::FU_ID_PARAM_NAME = "fuid" static private
Long name of the FUentryID parameter.
Definition at line 65 of file TestHDBCmdLineOptions.hh.
Referenced by fuEntryID(), isFUEntryIDGiven(), and TestHDBCmdLineOptions().
RF_ID_PARAM_NAME
const std::string TestHDBCmdLineOptions::RF_ID_PARAM_NAME = "rfid" static private
Long name of the RFentryID parameter.
Definition at line 67 of file TestHDBCmdLineOptions.hh.
Referenced by isRFEntryIDGiven(), rfEntryID(), and TestHDBCmdLineOptions().
SIM_PARAM_NAME
const std::string TestHDBCmdLineOptions::SIM_PARAM_NAME = "simulator" static private
Long name of VHDL simulator parameter.
Definition at line 73 of file TestHDBCmdLineOptions.hh.
Referenced by TestHDBCmdLineOptions(), and vhdlSim().
VERBOSE_PARAM_NAME
const std::string TestHDBCmdLineOptions::VERBOSE_PARAM_NAME = "verbose" static private
Long name of verbose output parameter.
Definition at line 69 of file TestHDBCmdLineOptions.hh.
Referenced by TestHDBCmdLineOptions(), and verbose().
The documentation for this class was generated from the following files:
TestHDBCmdLineOptions.hh
TestHDBCmdLineOptions.cc