OpenASIP: MDFView Class Reference
MDFView Class Reference
#include <MDFView.hh>
Public Member Functions
MDFView ()
virtual ~MDFView ()
virtual bool OnCreate (wxDocument *doc, long)
virtual bool OnClose (bool deleteWindow)
virtual void OnUpdate (wxView *sender, wxObject *hint)
virtual void OnDraw (wxDC *dc)
void clearSelection ()
EditPart * selection ()
virtual void OnActivateView (bool activate, wxView *activateView, wxView *deactivateView)
virtual void OnChangeFilename ()
virtual wxPrintout * OnCreatePrintout ()
MachineCanvas * canvas () const
Private Member Functions
MDFView (const MDFView &)
Copying forbidden.
MDFView & operator= (const MDFView &)
Assignment forbidden.
Private Attributes
MachineCanvas * canvas_
The window where the figures are drawn.
ChildFrame * frame_
ChildFrame for displaying the view.
Detailed Description
Viewing and editing component of a MDFDocument.
Part of the wxWidgets document/view framework. View of a Machine Object Model consists of EditParts defining the editing behaviour of the model components. For each EditPart in the view exists a figure defining the visualization of the component. The EditParts form a tree hierarchy starting from the top level contents EditPart, which is a child of the RootEditPart. This class also keeps track of the selected EditParts.
Definition at line 59 of file MDFView.hh.
Constructor & Destructor Documentation
MDFView() [1/2]
MDFView::MDFView ()
The Constructor.
Definition at line 60 of file MDFView.cc.
                 :
    wxView(),
    canvas_(NULL),
    frame_(NULL) {
}
~MDFView()
MDFView::~MDFView () virtual
The Destructor.
Definition at line 70 of file MDFView.cc.
                  {
}
MDFView() [2/2]
MDFView::MDFView (const MDFView &) private
Copying forbidden.
Member Function Documentation
canvas()
MachineCanvas * MDFView::canvas () const
Returns pointer to the MachineCanvas of the view.
Returns
MachineCanvas of the view.
Definition at line 229 of file MDFView.cc.
                      {
    return canvas_;
}
References canvas_.
Referenced by BridgeDialog::BridgeDialog(), EditConnectionsCmd::Do(), FitHeightCmd::Do(), FitWidthCmd::Do(), FitWindowCmd::Do(), SelectCmd::Do(), ToggleUnitDetailsCmd::Do(), ZoomInCmd::Do(), ZoomOutCmd::Do(), ToggleUnitDetailsCmd::isChecked(), BridgeDialog::onCancel(), BridgeDialog::onOK(), SelectTool::popContextMenu(), and ConnectTool::rightClick().
clearSelection()
void MDFView::clearSelection ()
Clears the component selection.
Definition at line 182 of file MDFView.cc.
{
    canvas_->clearSelection();
}
References canvas_, and MachineCanvas::clearSelection().
Referenced by EditConnectionsCmd::Do(), SelectCmd::Do(), and ConnectTool::leftClick().
OnActivateView()
void MDFView::OnActivateView (bool activate, wxView * activateView, wxView * deactivateView) virtual
Sets the main frame title when the view is activated.
Definition at line 191 of file MDFView.cc.
{
    if (!activate) {
    wxString title = ProDeConstants::EDITOR_NAME;
        wxGetApp().mainFrame()->SetTitle(title);
        return;
    }
    OnUpdate(NULL, NULL);
    // Update main frame title.
    OnChangeFilename();
    wxGetApp().mainFrame()->updateUI();
}
References ProDeConstants::EDITOR_NAME, OnChangeFilename(), and OnUpdate().
OnChangeFilename()
void MDFView::OnChangeFilename () virtual
Updates the main and child frame titles when the filename changes.
Definition at line 212 of file MDFView.cc.
{
    string path = WxConversion::toString(GetDocument()->GetFilename());
    string filename = FileSystem::fileOfPath(path);
    wxString title = ProDeConstants::EDITOR_NAME;
    title.Append(_T(" - "));
    title.Append(WxConversion::toWxString(filename));
    wxGetApp().mainFrame()->SetTitle(title);
    frame_->SetTitle(WxConversion::toWxString(filename));
}
References ProDeConstants::EDITOR_NAME, FileSystem::fileOfPath(), frame_, WxConversion::toString(), and WxConversion::toWxString().
Referenced by OnActivateView().
OnClose()
bool MDFView::OnClose (bool deleteWindow) virtual
Implements closing behaviour.
Closes the associated document.
Parameters
deleteWindow If true, deletes the frame associated with the view.
Returns
true if the associated document was succesfully closed.
Definition at line 83 of file MDFView.cc.
{
    if (!GetDocument()->Close()) {
      return false;
    }
    Activate(false);
    if (deleteWindow) {
    delete canvas_;
        canvas_ = NULL;
    delete frame_;
        frame_ = NULL;
    }
    return true;
}
References canvas_, and frame_.
OnCreate()
bool MDFView::OnCreate (wxDocument * doc, long) virtual
Creates a ChildFrame and a Canvas for the document when a new view is created.
Parameters
doc Pointer to the document which this view visualizes.
Returns
True if the ChildFrame and the Canvas was succesfully created.
Definition at line 110 of file MDFView.cc.
{
    if (doc == NULL) {
        return false;
    }
    // create a childframe for the view
    wxDocMDIParentFrame* mainFrame = wxGetApp().mainFrame();
    frame_ = new ChildFrame(doc, this, mainFrame);
    SetFrame(frame_);
    frame_->Show(true);
    // create a canvas for the child frame
    canvas_ = new MachineCanvas(frame_, new ProDeEditPolicyFactory(), frame_);
    // create select tool and set it as active tool for the canvas
    SelectTool* selectTool = new SelectTool(frame_, this);
    canvas_->setTool(selectTool);
    Activate(true);
    return true;
}
References canvas_, frame_, and MachineCanvas::setTool().
OnCreatePrintout()
wxPrintout * MDFView::OnCreatePrintout () virtual
Creates printout of the machine figure.
Returns
Printout object of the machine figure for printing.
Definition at line 251 of file MDFView.cc.
{
    return new ADFPrintout(*canvas_, GetDocument()->GetFilename());
}
References canvas_.
OnDraw()
void MDFView::OnDraw (wxDC * dc) virtual
Handles paint events of the view.
Parameters
dc Device context to draw the machine on.
Definition at line 240 of file MDFView.cc.
{
    canvas_->OnDraw(*dc);
}
References canvas_, and MachineCanvas::OnDraw().
OnUpdate()
void MDFView::OnUpdate (wxView * sender, wxObject * hint) virtual
Updates the model visualization.
Parameters
sender View that sent the update request, or NULL if no single view requested the update (for instance, when the document is opened).
hint Unused at the moment but may in future contain application-specific information for making updating more efficient.
Definition at line 144 of file MDFView.cc.
{
    wxDocument* doc = GetDocument();
    assert(doc != NULL);
    MDFDocument* mdfdoc = dynamic_cast<MDFDocument*>(doc);
    assert(mdfdoc != NULL);
    Model* model = mdfdoc->getModel();
    if (model == NULL) {
        // The model is NULL if document opening fails.
        // View is updated even if the document opening fails.
        return;
    }
    Machine* machine = model->getMachine();
    assert(machine != NULL);
    canvas_->setMachine(machine);
}
References assert, canvas_, Model::getMachine(), MDFDocument::getModel(), machine, and MachineCanvas::setMachine().
Referenced by OnActivateView().
operator=()
MDFView & MDFView::operator= (const MDFView &) private
Assignment forbidden.
selection()
EditPart * MDFView::selection ()
Returns selected component of the view.
Returns
Pointer to the selected EditPart.
Definition at line 169 of file MDFView.cc.
                   {
    if (canvas_ != NULL) {
    return canvas_->selection();
    } else {
    return NULL;
    }
}
References canvas_, and MachineCanvas::selection().
Referenced by CopyComponentCmd::isEnabled(), CutComponentCmd::isEnabled(), DeleteComponentCmd::isEnabled(), ModifyComponentCmd::isEnabled(), and ConnectTool::leftClick().
Member Data Documentation
canvas_
MachineCanvas* MDFView::canvas_ private
The window where the figures are drawn.
Definition at line 85 of file MDFView.hh.
Referenced by canvas(), clearSelection(), OnClose(), OnCreate(), OnCreatePrintout(), OnDraw(), OnUpdate(), and selection().
frame_
ChildFrame* MDFView::frame_ private
ChildFrame for displaying the view.
Definition at line 87 of file MDFView.hh.
Referenced by OnChangeFilename(), OnClose(), and OnCreate().
The documentation for this class was generated from the following files:
MDFView.hh
MDFView.cc