OpenASIP: ProximAboutDialog Class Reference
ProximAboutDialog Class Reference
#include <ProximAboutDialog.hh>
Public Member Functions
ProximAboutDialog (wxWindow *parent)
virtual ~ProximAboutDialog ()
Private Types
enum { ID_TEXT_PROGRAM_NAME = 10000 , ID_TEXT_PROGRAM_VERSION , ID_TEXT_PROGRAM_COPYRIGHT , ID_LINE }
Widget IDs.
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
Detailed Description
About dialog for Proxim.
Definition at line 42 of file ProximAboutDialog.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_TEXT_PROGRAM_NAME
ID_TEXT_PROGRAM_VERSION
ID_TEXT_PROGRAM_COPYRIGHT
ID_LINE
Definition at line 51 of file ProximAboutDialog.hh.
         {
    ID_TEXT_PROGRAM_NAME = 10000,
    ID_TEXT_PROGRAM_VERSION,
    ID_TEXT_PROGRAM_COPYRIGHT,
    ID_LINE
    };
Constructor & Destructor Documentation
ProximAboutDialog()
ProximAboutDialog::ProximAboutDialog (wxWindow * parent)
The Constructor.
Parameters
parent Parent window of the dialog.
Definition at line 43 of file ProximAboutDialog.cc.
                                                    :
    wxDialog(parent, -1, _T("About ") + WxConversion::toWxString(ProximConstants::PROXIM_TITLE), wxDefaultPosition) {
    createContents(this, true, true);
    dynamic_cast<wxStaticText*>(FindWindow(ID_TEXT_PROGRAM_VERSION))->SetLabel(
        _T("OpenASIP ") + WxConversion::toWxString(VERSION));
}
References createContents(), ID_TEXT_PROGRAM_VERSION, and WxConversion::toWxString().
~ProximAboutDialog()
ProximAboutDialog::~ProximAboutDialog () virtual
The Destructor.
Definition at line 54 of file ProximAboutDialog.cc.
{
}
Member Function Documentation
createContents()
wxSizer * ProximAboutDialog::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates contents of the dialog window. Code generated by wxDesigner.
Parameters
parent Parent dialog of the contents.
call_fit If true, fits sizer in dialog window.
set_sizer If true, sets sizer as dialog's sizer.
Returns
Top level sizer of the contents.
Definition at line 67 of file ProximAboutDialog.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item1 = new wxStaticText( parent, ID_TEXT_PROGRAM_NAME, WxConversion::toWxString(ProximConstants::PROXIM_TITLE), wxDefaultPosition, wxDefaultSize, 0 );
    item1->SetFont( wxFont( 25, wxROMAN, wxNORMAL, wxNORMAL ) );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT_PROGRAM_VERSION, wxT(VERSION), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );
     wxStaticText *item3 = new wxStaticText( parent, ID_TEXT_PROGRAM_COPYRIGHT, ProximConstants::PROXIM_COPYRIGHT, wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item4 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(200,-1), wxLI_HORIZONTAL );
    item0->Add( item4, 0, wxGROW|wxALL, 5 );
    wxButton *item5 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_LINE, ID_TEXT_PROGRAM_COPYRIGHT, ID_TEXT_PROGRAM_NAME, ID_TEXT_PROGRAM_VERSION, ProximConstants::PROXIM_COPYRIGHT, ProximConstants::PROXIM_TITLE, and WxConversion::toWxString().
Referenced by ProximAboutDialog().
The documentation for this class was generated from the following files:
ProximAboutDialog.hh
ProximAboutDialog.cc