OpenASIP: BFDRELate Class Reference
BFDRELate Class Reference
#include <BFDRELate.hh>
Public Member Functions
BFDRELate (BF2Scheduler &sched, MoveNode &mn)
virtual bool operator() ()
Public Member Functions inherited from BFKillNode
BFKillNode (BF2Scheduler &sched, MoveNode &mn)
bool operator() ()
void undoOnlyMe ()
Public Member Functions inherited from BFOptimization
BFOptimization (BF2Scheduler &sched)
virtual bool isFinishFront ()
virtual void mightBeReady (MoveNode &mn)
Public Member Functions inherited from Reversible
virtual void undo ()
virtual ~Reversible ()
void deleteChildren (std::stack< Reversible * > &children)
int id ()
Reversible ()
Additional Inherited Members
Static Public Member Functions inherited from BFOptimization
static void clearPrologMoves ()
static MoveNode * getSisterTrigger (const MoveNode &mn, const TTAMachine::Machine &mach)
Protected Member Functions inherited from BFOptimization
DataDependenceGraph & ddg ()
DataDependenceGraph * rootDDG ()
const DataDependenceGraph & ddg () const
DataDependenceGraph * prologDDG ()
SimpleResourceManager & rm () const
SimpleResourceManager * prologRM () const
BUMoveNodeSelector & selector ()
const TTAMachine::Machine & targetMachine () const
unsigned int ii () const
MoveNodeDuplicator & duplicator () const
virtual bool assign (int cycle, MoveNode &, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU_=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGuardWriteCycle=false)
virtual void unassign (MoveNode &mn, bool disposePrologCopy=true)
virtual int rmEC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual int rmLC (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1)
virtual bool canAssign (int cycle, MoveNode &mn, const TTAMachine::Bus *bus=nullptr, const TTAMachine::FunctionUnit *srcFU=nullptr, const TTAMachine::FunctionUnit *dstFU=nullptr, const TTAMachine::Bus *prologBus=nullptr, int immWriteCycle=-1, int prologImmWriteCycle=-1, const TTAMachine::ImmediateUnit *immu=nullptr, int immRegIndex=-1, bool ignoreGWN=false)
bool putAlsoToPrologEpilog (int cycle, MoveNode &mn)
void setPrologSrcFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setPrologDstFUAnno (MoveNode &prologMN, MoveNode &loopMN)
void setJumpGuard (MoveNode &mn)
void unsetJumpGuard (MoveNode &mn)
bool needJumpGuard (const MoveNode &mn, int cycle)
int jumpGuardAvailableCycle (const MoveNode &mn)
bool canBeSpeculated (const Operation &op)
bool canBeSpeculated (const MoveNode &mn)
bool usePrologMove (const MoveNode &mn)
bool canBeScheduled (const MoveNode &mn)
const TTAMachine::RegisterFile * RFReadPortCountPreventsScheduling (const MoveNode &mn)
bool immCountPreventsScheduling (const MoveNode &mn)
Protected Member Functions inherited from Reversible
bool runPreChild (Reversible *preChild)
bool runPostChild (Reversible *preChild)
bool runChild (std::stack< Reversible * > &children, Reversible *child)
bool runChild (Reversible *child, bool pre)
void undoAndRemovePreChildren ()
void undoAndRemovePostChildren ()
void undoAndRemoveChildren (std::stack< Reversible * > &children)
Protected Attributes inherited from BFKillNode
DataDependenceGraph::EdgeSet createdEdges_
MoveNode & mn_
Protected Attributes inherited from BFOptimization
BF2Scheduler & sched_
Protected Attributes inherited from Reversible
std::stack< Reversible * > preChildren_
std::stack< Reversible * > postChildren_
Static Protected Attributes inherited from BFOptimization
static std::map< MoveNode *, MoveNode *, MoveNode::Comparator > prologMoves_
Detailed Description
Definition at line 40 of file BFDRELate.hh.
Constructor & Destructor Documentation
BFDRELate()
BFDRELate::BFDRELate (BF2Scheduler & sched, MoveNode & mn) inline
Definition at line 42 of file BFDRELate.hh.
        : BFKillNode(sched, mn) {}
Member Function Documentation
operator()()
bool BFDRELate::operator() () virtual
This performs the operation. Returns true if success, false if fail.
Implements Reversible.
Definition at line 42 of file BFDRELate.cc.
                      {
    if (!sched_.killDeadResults() && !targetMachine().alwaysWriteResults()) {
        return false;
    }
    if (!ddg().resultUsed(mn_)) {
        // Take the predecssors of the dre'd src because their
        // antideps may change
         DataDependenceGraph::NodeSet pred = ddg().predecessors(mn_);
         createdEdges_ =  ddg().copyDepsOver(mn_, true, false);
        assert(!mn_.isScheduled());
        ddg().dropNode(mn_);
        sched_.nodeAndCopyKilled(mn_);
        // now mark antideps sources to be notified
        for (auto n: pred) {
            mightBeReady(*n);
        }
#ifdef DEBUG_BUBBLEFISH_SCHEDULER
    std::cerr << "\t\t\tLate DRE ok: " << mn_.toString() << std::endl;
#endif
        return true;
    } else {
        return false;
    }
}
References assert, DataDependenceGraph::copyDepsOver(), BFKillNode::createdEdges_, BFOptimization::ddg(), BoostGraph< GraphNode, GraphEdge >::dropNode(), MoveNode::isScheduled(), BF2Scheduler::killDeadResults(), BFOptimization::mightBeReady(), BFKillNode::mn_, BF2Scheduler::nodeAndCopyKilled(), BoostGraph< GraphNode, GraphEdge >::predecessors(), BFOptimization::sched_, BFOptimization::targetMachine(), and MoveNode::toString().
The documentation for this class was generated from the following files:
BFDRELate.hh
BFDRELate.cc