OpenASIP: TTAProgram::NullProgram Class Reference
TTAProgram::NullProgram Class Reference
#include <NullProgram.hh>
Public Member Functions
virtual ~NullProgram ()
GlobalScope & globalScope ()
const GlobalScope & globalScopeConst () const
TTAMachine::Machine & targetProcessor () const
Address startAddress () const
Address entryAddress () const
void setEntryAddress (Address address)
void addProcedure (Procedure &proc)
void addInstruction (Instruction &ins)
void relocate (const Procedure &proc, UIntWord howMuch)
Procedure & firstProcedure () const
Procedure & lastProcedure () const
Procedure & nextProcedure (const Procedure &proc) const
int procedureCount () const
Procedure & procedure (int index) const
Procedure & procedure (const std::string &name) const
Instruction & firstInstruction () const
const Instruction & instructionAt (UIntWord address) const
const Instruction & nextInstruction (const Instruction &) const
Instruction & lastInstruction () const
InstructionReferenceManager & instructionReferenceManager ()
Public Member Functions inherited from TTAProgram::Program
Program (const TTAMachine::AddressSpace &space)
Program (const TTAMachine::AddressSpace &space, Address start)
Program (const TTAMachine::AddressSpace &space, Address start, Address entry)
virtual ~Program ()
GlobalScope & globalScope ()
const GlobalScope & globalScopeConst () const
TTAMachine::Machine & targetProcessor () const
UniversalMachine & universalMachine () const
void setUniversalMachine (UniversalMachine *umach)
Address startAddress () const
void setStartAddress (Address start)
Address entryAddress () const
void setEntryAddress (Address address)
void addProcedure (Procedure *proc)
void addInstruction (Instruction *ins)
void moveProcedure (Procedure &proc, int howMuch)
Procedure & firstProcedure () const
Procedure & lastProcedure () const
Procedure & nextProcedure (const Procedure &proc) const
int procedureCount () const
Procedure & procedure (int index) const
Procedure & operator[] (size_t index)
Procedure & procedure (const std::string &name) const
bool hasProcedure (const std::string &name) const
Instruction & firstInstruction () const
Instruction & instructionAt (InstructionAddress address) const
int instructionCount () const
const Move & moveAt (int number) const
int moveCount () const
const Procedure & procedureAtIndex (int index) const
Instruction & nextInstruction (const Instruction &) const
Instruction & lastInstruction () const
InstructionReferenceManager & instructionReferenceManager () const
Program & operator= (const Program &old)
Program * copy () const
void removeProcedure (Procedure &proc)
int dataMemoryCount () const
DataMemory & dataMemory (int index) const
DataMemory & dataMemory (const std::string &aSpaceName) const
void addDataMemory (DataMemory *dataMem)
void replaceUniversalAddressSpaces (const TTAMachine::AddressSpace &space)
InstructionVector instructionVector () const
void link (const TTAProgram::Program &other)
void convertSymbolRefsToInsRefs (bool ignoreUnfoundSymbols=false)
void fixInstructionReferences ()
TCEString toString () const
void finalize ()
bool isFinalized () const
bool isInstructionPerAddress () const
Static Public Member Functions
static NullProgram & instance ()
Static Public Member Functions inherited from TTAProgram::Program
static Program * loadFromUnscheduledTPEF (const std::string &tpefFileName, const TTAMachine::Machine &theMachine)
static Program * loadFromTPEF (const std::string &tpefFileName, const TTAMachine::Machine &theMachine)
static Program * loadFromUnscheduledTPEF (const std::string &tpefFileName)
static void writeToTPEF (const TTAProgram::Program &program, const std::string &tpefFileName)
Protected Member Functions
NullProgram ()
Private Member Functions
NullProgram (const NullProgram &)
Copying not allowed.
NullProgram & operator= (const NullProgram &)
Assignment not allowed.
Static Private Attributes
static NullProgram instance_
Unique instance of NullProgram.
Additional Inherited Members
Public Types inherited from TTAProgram::Program
typedef std::vector< Instruction * > InstructionVector
Vector for instructions.
Detailed Description
A singleton class that represents a null program.
Calling any method causes the program to abort.
Definition at line 45 of file NullProgram.hh.
Constructor & Destructor Documentation
~NullProgram()
TTAProgram::NullProgram::~NullProgram () virtual
The destructor.
Definition at line 63 of file NullProgram.cc.
{
}
NullProgram() [1/2]
TTAProgram::NullProgram::NullProgram () protected
The constructor.
Definition at line 55 of file NullProgram.cc.
                        :
    Program(
        NullAddressSpace::instance(), NullAddress::instance()) {
}
NullProgram() [2/2]
TTAProgram::NullProgram::NullProgram (const NullProgram &) private
Copying not allowed.
Member Function Documentation
addInstruction()
void TTAProgram::NullProgram::addInstruction (Instruction & ins)
Aborts program with error log message.
Exceptions
IllegalRegistration never.
Definition at line 150 of file NullProgram.cc.
{
    abortWithError("addInstruction()");
}
References abortWithError.
addProcedure()
void TTAProgram::NullProgram::addProcedure (Procedure & proc)
Aborts program with error log message.
Exceptions
IllegalRegistration never.
Definition at line 140 of file NullProgram.cc.
{
    abortWithError("addProcedure()");
}
References abortWithError.
entryAddress()
Address TTAProgram::NullProgram::entryAddress () const
Aborts program with error log message.
Returns
A null address.
Definition at line 121 of file NullProgram.cc.
{
    abortWithError("entryAddress()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
firstInstruction()
Instruction & TTAProgram::NullProgram::firstInstruction () const
Aborts program with error log message.
Exceptions
InstanceNotFound never.
Returns
Nothing.
Definition at line 239 of file NullProgram.cc.
{
    abortWithError("firstInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
firstProcedure()
Procedure & TTAProgram::NullProgram::firstProcedure () const
Aborts program with error log message.
Exceptions
InstanceNotFound never.
Returns
Nothing.
Definition at line 169 of file NullProgram.cc.
{
    abortWithError("firstProcedure()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
globalScope()
GlobalScope & TTAProgram::NullProgram::globalScope ()
Aborts program with error log message.
Returns
Nothing.
Definition at line 82 of file NullProgram.cc.
{
    abortWithError("globalScope()");
    return NullGlobalScope::instance();
}
References abortWithError, and TTAProgram::NullGlobalScope::instance().
globalScopeConst()
const GlobalScope & TTAProgram::NullProgram::globalScopeConst () const
Definition at line 88 of file NullProgram.cc.
{
    abortWithError("globalScopeConst()");
    return NullGlobalScope::instance();
}
References abortWithError, and TTAProgram::NullGlobalScope::instance().
instance()
NullProgram & TTAProgram::NullProgram::instance () static
Returns an instance of NullProgram class (singleton).
Returns
Singleton instance of NullProgram class.
Definition at line 72 of file NullProgram.cc.
                      {
    return instance_;
}
References instance_.
Referenced by ProgramGraph::generateProgram(), TTAProgram::CodeSnippet::isInProgram(), loadInputs(), TTAProgram::NullProcedure::parent(), ProximToolbox::program(), SimulatorFrontend::program(), TTAProgram::Program::removeProcedure(), and TTAProgram::CodeSnippet::setParent().
instructionAt()
const Instruction & TTAProgram::NullProgram::instructionAt (UIntWord address) const
Aborts program with error log message.
Returns
A null instruction.
Exceptions
KeyNotFound never.
Definition at line 251 of file NullProgram.cc.
{
    abortWithError("instructionAt()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
instructionReferenceManager()
InstructionReferenceManager & TTAProgram::NullProgram::instructionReferenceManager ()
Aborts program with error log message.
Returns
Nothing.
Definition at line 285 of file NullProgram.cc.
{
    abortWithError("instructionReferenceManager()");
    return NullInstructionReferenceManager::instance();
}
References abortWithError, and TTAProgram::NullInstructionReferenceManager::instance().
lastInstruction()
Instruction & TTAProgram::NullProgram::lastInstruction () const
Aborts program with error log message.
Exceptions
InstanceNotFound never.
Returns
Nothing.
Definition at line 274 of file NullProgram.cc.
{
    abortWithError("lastInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
lastProcedure()
Procedure & TTAProgram::NullProgram::lastProcedure () const
Aborts program with error log message.
Exceptions
InstanceNotFound never.
Returns
Nothing.
Definition at line 181 of file NullProgram.cc.
{
    abortWithError("lastProcedure()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
nextInstruction()
const Instruction & TTAProgram::NullProgram::nextInstruction (const Instruction &) const
Aborts program with error log message.
Returns
A null instruction.
Definition at line 262 of file NullProgram.cc.
{
    abortWithError("nextInstruction()");
    return NullInstruction::instance();
}
References abortWithError, and TTAProgram::NullInstruction::instance().
nextProcedure()
Procedure & TTAProgram::NullProgram::nextProcedure (const Procedure & proc) const
Aborts program with error log message.
Returns
Nothing.
Definition at line 192 of file NullProgram.cc.
{
    abortWithError("nextProcedure()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
operator=()
NullProgram & TTAProgram::NullProgram::operator= (const NullProgram &) private
Assignment not allowed.
procedure() [1/2]
Procedure & TTAProgram::NullProgram::procedure (const std::string & name) const
Aborts program with error log message.
Exceptions
KeyNotFound never.
Returns
Nothing.
Definition at line 227 of file NullProgram.cc.
{
    abortWithError("procedure()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
procedure() [2/2]
Procedure & TTAProgram::NullProgram::procedure (int index) const
Aborts program with error log message.
Returns
a null procedure.
Exceptions
OutOfRange never.
Definition at line 215 of file NullProgram.cc.
{
    abortWithError("addInstruction()");
    return NullProcedure::instance();
}
References abortWithError, and TTAProgram::NullProcedure::instance().
procedureCount()
int TTAProgram::NullProgram::procedureCount () const
Aborts program with error log message.
Returns
-1.
Definition at line 203 of file NullProgram.cc.
{
    abortWithError("addInstruction()");
    return -1;
}
References abortWithError.
relocate()
void TTAProgram::NullProgram::relocate (const Procedure & proc, UIntWord howMuch)
Aborts program with error log message.
Definition at line 158 of file NullProgram.cc.
{
    abortWithError("relocate()");
}
References abortWithError.
setEntryAddress()
void TTAProgram::NullProgram::setEntryAddress (Address address)
Aborts program with error log message.
Definition at line 130 of file NullProgram.cc.
{
    abortWithError("setEntryAddress()");
}
References abortWithError.
startAddress()
Address TTAProgram::NullProgram::startAddress () const
Aborts program with error log message.
Returns
A null address.
Definition at line 110 of file NullProgram.cc.
{
    abortWithError("startAddress()");
    return NullAddress::instance();
}
References abortWithError, and TTAProgram::NullAddress::instance().
targetProcessor()
TTAMachine::Machine & TTAProgram::NullProgram::targetProcessor () const
Aborts program with error log message.
Returns
Nothing
Definition at line 100 of file NullProgram.cc.
{
    abortWithError("targetProcessor()");
    return TTAMachine::NullMachine::instance();
}
References abortWithError, and TTAMachine::NullMachine::instance().
Member Data Documentation
instance_
NullProgram TTAProgram::NullProgram::instance_ static private
Unique instance of NullProgram.
Definition at line 88 of file NullProgram.hh.
Referenced by instance().
The documentation for this class was generated from the following files:
NullProgram.hh
NullProgram.cc