OpenASIP: ProGe::Parameter Class Reference
ProGe::Parameter Class Reference
#include <Parameter.hh>
Public Member Functions
Parameter ()
Parameter (const TCEString &name, const TCEString &type, const TCEString &assignedAndDefaultValue)
Parameter (const TCEString &name, const TCEString &type, const TCEString &assignedValue, const TCEString &defaultValue)
Parameter (const TCEString &name, const TCEString &type, int assignedValue, const TCEString &defaultValue)
Parameter (const TCEString &name, const TCEString &type, const TCEString &nameOfConstant, const TCEString &defaultValue, const TCEString &nameOfPackage)
virtual ~Parameter ()
void set (const TCEString &name, const TCEString &type, const TCEString &value)
void setName (const TCEString &name)
void setType (const TCEString &type)
void setValue (const TCEString &value)
const TCEString & name () const
const TCEString & type () const
const TCEString & value () const
const TCEString & defaultValue () const
bool valueIsSymbol () const
bool valueIsConstant () const
const std::string & packageNameOfConstant () const
Private Attributes
TCEString name_
Name/identifier of the parameter.
TCEString type_
Type of the parameter.
TCEString value_
Assigned value to the parameter as actual value or as reference to another parameter or name of a constant.
TCEString default_
Default value of the parameter if value_ is not set (empty).
TCEString package_
Package reference by name. If non-empty the value_ is treated as name of a constant.
Detailed Description
Class that represents a parameter for netlist objects such as netlist port and netlist block and is used to define port widths and enable/disable properties of blocks. Parameters are may have two different values: assigned and default where assigned value is real value assigned for the parameter and default value is fallback value in case the assigned have is not defined..
From HDL point of view (VHDL, verilog) the assigned value corresponds to the value set for module/entity instantiation's parameter/generic and the default value corresponds to default value for a module's/entity's parameter/generic.
Empty value means that the value is not defined.
Definition at line 62 of file Parameter.hh.
Constructor & Destructor Documentation
Parameter() [1/5]
ProGe::Parameter::Parameter ()
Empty parameter with undefined members.
Definition at line 45 of file Parameter.cc.
    : name_(""), type_(""), value_(""), default_(""), package_("") {}
Parameter() [2/5]
ProGe::Parameter::Parameter (const TCEString & name, const TCEString & type, const TCEString & assignedAndDefaultValue)
Constructs a parameter with both the assigned and default value having the same value.
Parameters
name The name of the parameter
type The type of the parameter given as string
assignedAndDefaultValue The assigned and default value of the parameter.
Definition at line 57 of file Parameter.cc.
    : Parameter(
          name, type, assignedAndDefaultValue, assignedAndDefaultValue) {}
Parameter() [3/5]
ProGe::Parameter::Parameter (const TCEString & name, const TCEString & type, const TCEString & assignedValue, const TCEString & defaultValue)
Constructs a parameter with separate assigned and default value.
Parameters
name The name of the parameter
type The type of the parameter given as string
assignedValue The assigned value of the parameter.
defaultValue The default value of the parameter.
Definition at line 71 of file Parameter.cc.
    : name_(name),
      type_(type),
      value_(assignedValue),
      default_(defaultValue),
      package_("") {}
Parameter() [4/5]
ProGe::Parameter::Parameter (const TCEString & name, const TCEString & type, int assignedValue, const TCEString & defaultValue)
Definition at line 79 of file Parameter.cc.
    : name_(name),
      type_(type),
      value_(""),
      default_(defaultValue),
      package_("") {
    value_ = Conversion::toString(assignedValue);
}
References Conversion::toString(), and value_.
Parameter() [5/5]
ProGe::Parameter::Parameter (const TCEString & name, const TCEString & type, const TCEString & nameOfConstant, const TCEString & defaultValue, const TCEString & nameOfPackage)
Parameters
name The name of the parameter
type The type of the parameter given as string
nameOfConstant The value of the parameter as name to a constant.
defaultValue The default value of the parameter.
nameOfPackage The name of a package where the constant is defined.
Definition at line 97 of file Parameter.cc.
    : name_(name),
      type_(type),
      value_(nameOfConstant),
      default_(defaultValue),
      package_(nameOfPackage) {}
~Parameter()
ProGe::Parameter::~Parameter () virtual
Definition at line 107 of file Parameter.cc.
{}
Member Function Documentation
defaultValue()
const TCEString & ProGe::Parameter::defaultValue () const
Definition at line 148 of file Parameter.cc.
{
    return default_;
}
References default_.
Referenced by ProGe::VerilogNetlistWriter::writeGenericDeclaration(), and ProGe::VHDLNetlistWriter::writeGenericDeclaration().
name()
const TCEString & ProGe::Parameter::name () const
Definition at line 133 of file Parameter.cc.
                      {
    return name_;
}
References name_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), AlteraMemGenerator::addGenerics(), Stratix2SramGenerator::addMemory(), ProGe::BaseNetlistBlock::addParameter(), MemoryGenerator::addParameter(), PlatformIntegrator::copyProgeBlockToNetlist(), ProGe::BaseNetlistBlock::hasParameter(), ProGe::BaseNetlistBlock::parameter(), ProGe::NetlistVisualization::printParameter(), ProGe::NetlistPort::resolveRealWidth(), set(), setName(), ProGe::BaseNetlistBlock::setParameter(), ProGe::Netlist::setParameter(), ProGe::VHDLNetlistWriter::writeComponentDeclarations(), ProGe::VerilogNetlistWriter::writeGenericDeclaration(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), SOPCBuilderFileGenerator::writeGenerics(), ProGe::VerilogNetlistWriter::writeNetlistParameterPackage(), ProGe::VHDLNetlistWriter::writeNetlistParameterPackage(), ProGe::VerilogNetlistWriter::writePortMappings(), and ProGe::VHDLNetlistWriter::writePortMappings().
packageNameOfConstant()
const std::string & ProGe::Parameter::packageNameOfConstant () const
Definition at line 171 of file Parameter.cc.
{
    return package_;
}
References package_.
Referenced by ProGe::BaseNetlistBlock::addParameter().
set()
void ProGe::Parameter::set (const TCEString & name, const TCEString & type, const TCEString & value)
Definition at line 110 of file Parameter.cc.
{
    name_ = name;
    type_ = type;
    value_ = value;
}
References name(), name_, type(), type_, value(), and value_.
setName()
void ProGe::Parameter::setName (const TCEString & name)
Definition at line 118 of file Parameter.cc.
{
    name_ = name;
}
References name(), and name_.
Referenced by IPXactModel::extractModelParam().
setType()
void ProGe::Parameter::setType (const TCEString & type)
Definition at line 123 of file Parameter.cc.
{
    type_ = type;
}
References type(), and type_.
Referenced by IPXactModel::extractModelParam().
setValue()
void ProGe::Parameter::setValue (const TCEString & value)
Definition at line 128 of file Parameter.cc.
{
    value_ = value;
}
References value(), and value_.
Referenced by IPXactModel::extractModelParam(), and XilinxBlockRamGenerator::XilinxBlockRamGenerator().
type()
const TCEString & ProGe::Parameter::type () const
Definition at line 138 of file Parameter.cc.
                      {
    return type_;
}
References type_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), Stratix2SramGenerator::addMemory(), MemoryGenerator::addParameter(), ProGe::NetlistVisualization::printParameter(), set(), ProGe::Netlist::setParameter(), setType(), ProGe::VHDLNetlistWriter::writeComponentDeclarations(), ProGe::VerilogNetlistWriter::writeGenericDeclaration(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), SOPCBuilderFileGenerator::writeGenerics(), ProGe::VHDLNetlistWriter::writeNetlistParameterPackage(), ProGe::VerilogNetlistWriter::writePortMappings(), and ProGe::VHDLNetlistWriter::writePortMappings().
value()
const TCEString & ProGe::Parameter::value () const
Definition at line 143 of file Parameter.cc.
                       {
    return value_;
}
References value_.
Referenced by ProGe::NetlistGenerator::addBaseRFToNetlist(), ProGe::NetlistGenerator::addFUExternalPortsToNetlist(), Stratix2SramGenerator::addMemory(), MemoryGenerator::addParameter(), ProGe::VHDLNetlistWriter::parameterWidthValue(), ProGe::NetlistVisualization::printParameter(), ProGe::NetlistPort::resolveRealWidth(), set(), ProGe::Netlist::setParameter(), setValue(), ProGe::VHDLNetlistWriter::writeGenericDeclaration(), SOPCBuilderFileGenerator::writeGenerics(), ProGe::VerilogNetlistWriter::writeNetlistParameterPackage(), ProGe::VHDLNetlistWriter::writeNetlistParameterPackage(), ProGe::VerilogNetlistWriter::writePortMappings(), and ProGe::VHDLNetlistWriter::writePortMappings().
valueIsConstant()
bool ProGe::Parameter::valueIsConstant () const
Return true is the value is a symbol to a constant that are stored in packages.
Definition at line 166 of file Parameter.cc.
{
    return valueIsSymbol() && !package_.empty();
}
References package_, and valueIsSymbol().
Referenced by ProGe::BaseNetlistBlock::addParameter().
valueIsSymbol()
bool ProGe::Parameter::valueIsSymbol () const
Return true is the value is a symbol therefore the actual value is defined elsewhere. Otherwise, the value is literal.
Definition at line 157 of file Parameter.cc.
{
    return !package_.empty();  // note: placeholder
}
References package_.
Referenced by valueIsConstant().
Member Data Documentation
default_
TCEString ProGe::Parameter::default_ private
Default value of the parameter if value_ is not set (empty).
Definition at line 115 of file Parameter.hh.
Referenced by defaultValue().
name_
TCEString ProGe::Parameter::name_ private
Name/identifier of the parameter.
Definition at line 108 of file Parameter.hh.
Referenced by name(), set(), and setName().
package_
TCEString ProGe::Parameter::package_ private
Package reference by name. If non-empty the value_ is treated as name of a constant.
Definition at line 118 of file Parameter.hh.
Referenced by packageNameOfConstant(), valueIsConstant(), and valueIsSymbol().
type_
TCEString ProGe::Parameter::type_ private
Type of the parameter.
Definition at line 110 of file Parameter.hh.
Referenced by set(), setType(), and type().
value_
TCEString ProGe::Parameter::value_ private
Assigned value to the parameter as actual value or as reference to another parameter or name of a constant.
Definition at line 113 of file Parameter.hh.
Referenced by Parameter(), set(), setValue(), and value().
The documentation for this class was generated from the following files:
Parameter.hh
Parameter.cc