OpenASIP: ProgramDependenceNode Class Reference
ProgramDependenceNode Class Reference
#include <ProgramDependenceNode.hh>
Public Types
enum NodeType {
PDG_NODE_REGION , PDG_NODE_PREDICATE , PDG_NODE_MOVE , PDG_NODE_LOOPENTRY ,
PDG_NODE_LOOPCLOSE
}
typedef std::set< ProgramDependenceNode * > NodesInfo
Public Member Functions
ProgramDependenceNode (NodeType type=PDG_NODE_REGION)
ProgramDependenceNode (ControlDependenceNode &cdgNode, NodeType type=PDG_NODE_REGION)
ProgramDependenceNode (MoveNode &mNode, NodeType type=PDG_NODE_MOVE)
virtual ~ProgramDependenceNode ()
bool isRegionNode () const
bool isPredicateMoveNode () const
bool isMoveNode () const
bool isLoopEntryNode () const
bool isLoopEntryNode (int component) const
bool isLoopCloseNode () const
bool isLastNode () const
void setLoopEntryNode (int component)
void setComponent (int component)
void setLastNode ()
int component () const
MoveNode & moveNode ()
const MoveNode & moveNode () const
ControlDependenceNode & cdgNode ()
const ControlDependenceNode & cdgNode () const
std::string dotString () const
std::string toString () const
const NodesInfo & region ()
const NodesInfo & eec ()
void printRelations () const
BasicBlockNode * newFirstBB ()
void setNewFirstBB (BasicBlockNode *newBB)
std::vector< BasicBlockNode * > leafBlocks ()
void addLeafBlock (BasicBlockNode *newLeaf)
void addLeafBlocks (std::vector< BasicBlockNode * > newLeafs)
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
virtual GraphNode * clone () const
int nodeID () const
Protected Member Functions
void setPredicateMoveNode ()
void addToRegion (ProgramDependenceNode &node)
void addToEEC (ProgramDependenceNode &node)
Private Attributes
MoveNode * mNode_
ControlDependenceNode * cdgNode_
NodeType type_
NodesInfo region_
Stores "region" information for computing serialization information.
NodesInfo eec_
Stores "eec" information for computing serialization information.
int component_
Number of strong component the node belongs to. Node can be part of several strong components so this value have practical meaning only for loop close nodes - close just one loop, and loop entry nodes - marks a component in which node is loop entry. Still can be regular region of larger loop Full list of nodes that belongs to actual components is available in strongComponents_ vector in PDG.
BasicBlockNode * newFirstBB_
First basic block of a subgraph of a region.
std::vector< BasicBlockNode * > leafBlocks_
Vector of basic blocks of a subgraph that do not have outgoing edged and will need to get connected.
bool lastNode_
Indicates that node must be scheduled last between it's siblings because it's subgraph contains close node and it's parent is entry.
Friends
class ProgramDependenceGraph
Detailed Description
Definition at line 43 of file ProgramDependenceNode.hh.
Member Typedef Documentation
NodesInfo
typedef std::set<ProgramDependenceNode*> ProgramDependenceNode::NodesInfo
Definition at line 64 of file ProgramDependenceNode.hh.
Member Enumeration Documentation
NodeType
enum ProgramDependenceNode::NodeType
Enumerator
PDG_NODE_REGION
PDG_NODE_PREDICATE
PDG_NODE_MOVE
PDG_NODE_LOOPENTRY
PDG_NODE_LOOPCLOSE
Definition at line 45 of file ProgramDependenceNode.hh.
                  {
        PDG_NODE_REGION, // Region nodes of PDG
        PDG_NODE_PREDICATE, // Predicate nodes of PDG
        PDG_NODE_MOVE,   // Single statements nodes
        PDG_NODE_LOOPENTRY, // Region that is loop entry node
        PDG_NODE_LOOPCLOSE // Region that is loop entry node
    };
Constructor & Destructor Documentation
ProgramDependenceNode() [1/3]
ProgramDependenceNode::ProgramDependenceNode (NodeType type = PDG_NODE_REGION)
Constructor creating Program Dependence Node which is empty. Does not have related CDG node. For example Loop Close node.
Parameters
type Type of the node
Definition at line 45 of file ProgramDependenceNode.cc.
    : GraphNode(), type_(type), component_(-1), newFirstBB_(NULL),
    lastNode_(false) {
    mNode_ = NULL;
    cdgNode_ = NULL;
}
References cdgNode_, and mNode_.
ProgramDependenceNode() [2/3]
ProgramDependenceNode::ProgramDependenceNode (ControlDependenceNode & cdgNode, NodeType type = PDG_NODE_REGION)
Constructor creating Program Dependence Node from Control Dependence region node.
Parameters
cdgNode node of CDG
type Type of the node
Definition at line 59 of file ProgramDependenceNode.cc.
    : GraphNode(), cdgNode_(&cdgNode), type_(type), component_(-1),
    newFirstBB_(NULL), lastNode_(false) {
    mNode_ = NULL;
}
References mNode_.
ProgramDependenceNode() [3/3]
ProgramDependenceNode::ProgramDependenceNode (MoveNode & mNode, NodeType type = PDG_NODE_MOVE)
Constructor creating Program Dependence Node from Data Dependence node.
Parameters
mNode MoveNode of DDG
type Type of the node
Definition at line 72 of file ProgramDependenceNode.cc.
    : GraphNode(), mNode_(&mNode), type_(type), component_(-1),
    newFirstBB_(NULL), lastNode_(false) {
    cdgNode_ = NULL;
}
References cdgNode_.
~ProgramDependenceNode()
ProgramDependenceNode::~ProgramDependenceNode () virtual
Empty destructor.
Definition at line 83 of file ProgramDependenceNode.cc.
{
    region_.clear();
    eec_.clear();
}
References eec_, and region_.
Member Function Documentation
addLeafBlock()
void ProgramDependenceNode::addLeafBlock (BasicBlockNode * newLeaf) inline
Definition at line 90 of file ProgramDependenceNode.hh.
{
        leafBlocks_.push_back(newLeaf); }
References leafBlocks_.
Referenced by ProgramDependenceGraph::processPredicate(), and ProgramDependenceGraph::processRegion().
addLeafBlocks()
void ProgramDependenceNode::addLeafBlocks (std::vector< BasicBlockNode * > newLeafs) inline
Definition at line 92 of file ProgramDependenceNode.hh.
{
        leafBlocks_.insert(leafBlocks_.end(), newLeafs.begin(), newLeafs.end());
    }
References leafBlocks_.
Referenced by ProgramDependenceGraph::processRegion().
addToEEC()
void ProgramDependenceNode::addToEEC (ProgramDependenceNode & node) protected
Add node to "eec" set for computing serialization information
Parameters
node Node to add to the set
Definition at line 270 of file ProgramDependenceNode.cc.
{
    eec_.insert(&node);
}
References eec_.
Referenced by ProgramDependenceGraph::computeEECInfo().
addToRegion()
void ProgramDependenceNode::addToRegion (ProgramDependenceNode & node) protected
Add node to "region" set for computing serialization information
Parameters
node Node to add to the set
Definition at line 250 of file ProgramDependenceNode.cc.
{
    region_.insert(&node);
}
References region_.
Referenced by ProgramDependenceGraph::computeRegionInfo(), and ProgramDependenceGraph::regionHelper().
cdgNode() [1/2]
ControlDependenceNode & ProgramDependenceNode::cdgNode ()
Returns CDGNode corresponding to given node in CDG.
Returns
CDGNode corresponding to given node in CDG
Definition at line 214 of file ProgramDependenceNode.cc.
{
    if ((type_ == PDG_NODE_REGION
        || type_ == PDG_NODE_LOOPENTRY
        || type_ == PDG_NODE_LOOPCLOSE)
        && cdgNode_ != NULL) {
        return *cdgNode_;
    } else {
        TCEString msg = "ControlNode type does not contain CDGNode in ";
        msg += toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, cdgNode_, PDG_NODE_LOOPCLOSE, PDG_NODE_LOOPENTRY, PDG_NODE_REGION, toString(), and type_.
cdgNode() [2/2]
const ControlDependenceNode & ProgramDependenceNode::cdgNode () const
Returns CDGNode corresponding to given node in CDG as constant.
Returns
CDGNode corresponding to given node in CDG as constant
Definition at line 231 of file ProgramDependenceNode.cc.
{
    if ((type_ == PDG_NODE_REGION
        || type_ == PDG_NODE_LOOPENTRY
        || type_ == PDG_NODE_LOOPCLOSE)
        && cdgNode_ != NULL) {
        return *cdgNode_;
    } else {
        TCEString msg = "ControlNode type does not contain CDGNode in ";
        msg += toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, cdgNode_, PDG_NODE_LOOPCLOSE, PDG_NODE_LOOPENTRY, PDG_NODE_REGION, toString(), and type_.
component()
int ProgramDependenceNode::component () const inline
Definition at line 76 of file ProgramDependenceNode.hh.
{ return component_;}
References component_.
Referenced by isLoopEntryNode(), setComponent(), and setLoopEntryNode().
dotString()
std::string ProgramDependenceNode::dotString () const virtual
Returns content of a node as a string in .dot format.
Returns
string representing content of a node in .dot format
Reimplemented from GraphNode.
Definition at line 140 of file ProgramDependenceNode.cc.
{
    if (isPredicateMoveNode()) {
        return TCEString("label=\"") +
            toString() + "\",shape=box,color=green";
    }
    if (isRegionNode()) {
        return TCEString("label=\"")
            + toString() + "\",shape=box,color=blue";
    }
    if (isMoveNode() && moveNode().isMove() && moveNode().move().isCall()) {
        return TCEString("label=\"")
                    + toString() + "\",shape=box,color=red";
    }
    if (isLoopEntryNode()) {
        return TCEString("label=\"")
            + toString() + "\",shape=box,color=red";
    }
    if (isLoopCloseNode()) {
        return TCEString("label=\"")
            + toString() + "\",shape=box,color=yellow";
    }
    return TCEString("label=\"") + toString() + "\"";
}
References isLoopCloseNode(), isLoopEntryNode(), isMoveNode(), isPredicateMoveNode(), isRegionNode(), moveNode(), and toString().
eec()
const ProgramDependenceNode::NodesInfo & ProgramDependenceNode::eec ()
Returns the "eec" set for given node
Returns
the "eec" set for given node
Definition at line 281 of file ProgramDependenceNode.cc.
{
    return eec_;
}
References eec_.
Referenced by ProgramDependenceGraph::compareSiblings(), and ProgramDependenceGraph::computeEECInfo().
isLastNode()
bool ProgramDependenceNode::isLastNode () const inline
Definition at line 72 of file ProgramDependenceNode.hh.
{ return lastNode_;}
References lastNode_.
Referenced by ProgramDependenceGraph::compareSiblings(), and toString().
isLoopCloseNode()
bool ProgramDependenceNode::isLoopCloseNode () const inline
Definition at line 71 of file ProgramDependenceNode.hh.
{ return type_ == PDG_NODE_LOOPCLOSE;}
References PDG_NODE_LOOPCLOSE, and type_.
Referenced by ProgramDependenceGraph::compareSiblings(), dotString(), ProgramDependenceGraph::regionHelper(), and toString().
isLoopEntryNode() [1/2]
bool ProgramDependenceNode::isLoopEntryNode () const inline
Definition at line 68 of file ProgramDependenceNode.hh.
{ return type_ == PDG_NODE_LOOPENTRY;}
References PDG_NODE_LOOPENTRY, and type_.
Referenced by ProgramDependenceGraph::compareSiblings(), dotString(), ProgramDependenceGraph::processRegion(), ProgramDependenceGraph::regionHelper(), and toString().
isLoopEntryNode() [2/2]
bool ProgramDependenceNode::isLoopEntryNode (int component) const inline
Definition at line 69 of file ProgramDependenceNode.hh.
{
        return type_ == PDG_NODE_LOOPENTRY && component_ == component;}
References component(), component_, PDG_NODE_LOOPENTRY, and type_.
isMoveNode()
bool ProgramDependenceNode::isMoveNode () const inline
Definition at line 67 of file ProgramDependenceNode.hh.
{ return type_ == PDG_NODE_MOVE;}
References PDG_NODE_MOVE, and type_.
Referenced by ProgramDependenceGraph::compareSiblings(), dotString(), ProgramDependenceGraph::processRegion(), and ProgramDependenceGraph::ProgramDependenceGraph().
isPredicateMoveNode()
bool ProgramDependenceNode::isPredicateMoveNode () const inline
Definition at line 66 of file ProgramDependenceNode.hh.
{ return type_ == PDG_NODE_PREDICATE;}
References PDG_NODE_PREDICATE, and type_.
Referenced by ProgramDependenceGraph::compareSiblings(), dotString(), ProgramDependenceGraph::ProgramDependenceGraph(), ProgramDependenceGraph::regionHelper(), and toString().
isRegionNode()
bool ProgramDependenceNode::isRegionNode () const inline
Definition at line 65 of file ProgramDependenceNode.hh.
{ return type_ == PDG_NODE_REGION;}
References PDG_NODE_REGION, and type_.
Referenced by ProgramDependenceGraph::compareSiblings(), dotString(), ProgramDependenceGraph::regionHelper(), and toString().
leafBlocks()
std::vector< BasicBlockNode * > ProgramDependenceNode::leafBlocks () inline
Definition at line 89 of file ProgramDependenceNode.hh.
{ return leafBlocks_;}
References leafBlocks_.
Referenced by ProgramDependenceGraph::processRegion().
moveNode() [1/2]
MoveNode & ProgramDependenceNode::moveNode ()
Returns MoveNode corresponding to given node in DDG.
Returns
MoveNode corresponding to given node in DDG
Definition at line 182 of file ProgramDependenceNode.cc.
{
    if ((type_ == PDG_NODE_MOVE || type_ == PDG_NODE_PREDICATE)
        && mNode_ != NULL) {
        return *mNode_;
    } else {
        TCEString msg = "MoveNode type does not contain move in ";
        msg += toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, mNode_, PDG_NODE_MOVE, PDG_NODE_PREDICATE, toString(), and type_.
Referenced by dotString(), ProgramDependenceGraph::processPredicate(), ProgramDependenceGraph::processRegion(), ProgramDependenceGraph::ProgramDependenceGraph(), and ProgramDependenceGraph::removeGuardedJump().
moveNode() [2/2]
const MoveNode & ProgramDependenceNode::moveNode () const
Returns MoveNode corresponding to given node in DDG as constant.
Returns
MoveNode corresponding to given node in DDG as constant
Definition at line 198 of file ProgramDependenceNode.cc.
{
    if ((type_ == PDG_NODE_MOVE || type_ == PDG_NODE_PREDICATE)
        && mNode_ != NULL) {
        return *mNode_;
    } else {
        TCEString msg = "MoveNode type does not contain move in ";
        msg += toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
}
References __func__, mNode_, PDG_NODE_MOVE, PDG_NODE_PREDICATE, toString(), and type_.
newFirstBB()
BasicBlockNode * ProgramDependenceNode::newFirstBB () inline
Definition at line 87 of file ProgramDependenceNode.hh.
{ return newFirstBB_;}
References newFirstBB_.
Referenced by ProgramDependenceGraph::processRegion().
printRelations()
void ProgramDependenceNode::printRelations () const
Definition at line 297 of file ProgramDependenceNode.cc.
{
    Application::logStream() << "Relations: ";
    for (NodesInfo::const_iterator iter = region_.begin();
        iter != region_.end();
        iter ++) {
        Application::logStream() << (*iter)->toString() << ", ";
    }
    Application::logStream() << std::endl;
    Application::logStream() << "EEC: ";
    for (NodesInfo::const_iterator iter = eec_.begin();
        iter != eec_.end();
        iter ++) {
        Application::logStream() << (*iter)->toString() << ", ";
    }
    Application::logStream() << std::endl;
}
References eec_, Application::logStream(), and region_.
Referenced by ProgramDependenceGraph::processRegion().
region()
const ProgramDependenceNode::NodesInfo & ProgramDependenceNode::region ()
Returns the "region" set for given node
Returns
the "region" set for given node
Definition at line 260 of file ProgramDependenceNode.cc.
{
    return region_;
}
References region_.
Referenced by ProgramDependenceGraph::regionHelper().
setComponent()
void ProgramDependenceNode::setComponent (int component) inline
Definition at line 74 of file ProgramDependenceNode.hh.
{ component_ = component;}
References component(), and component_.
Referenced by ProgramDependenceGraph::detectStrongComponents().
setLastNode()
void ProgramDependenceNode::setLastNode () inline
Definition at line 75 of file ProgramDependenceNode.hh.
{ lastNode_ = true; }
References lastNode_.
Referenced by ProgramDependenceGraph::ProgramDependenceGraph().
setLoopEntryNode()
void ProgramDependenceNode::setLoopEntryNode (int component)
Sets the node to be loop entry node of a given component (loop)
Parameters
component Component of which the node is loop entry node
Definition at line 292 of file ProgramDependenceNode.cc.
{
    type_ = PDG_NODE_LOOPENTRY;
    component_ = component;
}
References component(), component_, PDG_NODE_LOOPENTRY, and type_.
Referenced by ProgramDependenceGraph::detectStrongComponents().
setNewFirstBB()
void ProgramDependenceNode::setNewFirstBB (BasicBlockNode * newBB) inline
Definition at line 88 of file ProgramDependenceNode.hh.
{ newFirstBB_ = newBB;}
References newFirstBB_.
Referenced by ProgramDependenceGraph::processPredicate(), and ProgramDependenceGraph::processRegion().
setPredicateMoveNode()
void ProgramDependenceNode::setPredicateMoveNode () protected
Sets node to be predicate node
Definition at line 168 of file ProgramDependenceNode.cc.
{
    if (type_ != PDG_NODE_MOVE && type_ != PDG_NODE_PREDICATE) {
        TCEString msg = "Trying to create predicate move from Region in ";
        msg += toString() + "!";
        throw InvalidData(__FILE__, __LINE__, __func__, msg);
    }
    type_ = PDG_NODE_PREDICATE;
}
References __func__, PDG_NODE_MOVE, PDG_NODE_PREDICATE, toString(), and type_.
Referenced by ProgramDependenceGraph::removeGuardedJump().
toString()
std::string ProgramDependenceNode::toString () const virtual
Returns content of a node as a string.
Returns
string representing content of a node
Node added during strong components detection to collect edges pointing to loop entry from outside the loop. Do not have cdg equivalent if analysis was done directly on pdg
Loop entry is region node converted during detection of loops Exists in CDG even if loop detection was done on PDG
Node added during strong components detection to collect edges pointing to loop entry from inside the loop. Do not have cdg equivalent if analysis was done directly on pdg
Reimplemented from GraphNode.
Definition at line 93 of file ProgramDependenceNode.cc.
{
    TCEString result;
    if (isRegionNode()) {
        if (cdgNode_ != NULL) {
            result += cdgNode_->toString() + ": " +
                Conversion::toString(nodeID());
        } else {
            /// Node added during strong components detection
            /// to collect edges pointing to loop entry from outside the loop.
            /// Do not have cdg equivalent if analysis was done directly on pdg
            result += "Collect_" +  Conversion::toString(nodeID());
        }
    }
    if (isLoopEntryNode()) {
        /// Loop entry is region node converted during detection of loops
        /// Exists in CDG even if loop detection was done on PDG
        result += "LoopEntry_" + Conversion::toString(nodeID()) +
            ": " + cdgNode_->toString();
    }
    if (isLoopCloseNode()) {
        /// Node added during strong components detection
        /// to collect edges pointing to loop entry from inside the loop.
        /// Do not have cdg equivalent if analysis was done directly on pdg
        if (cdgNode_ != NULL) {
            result += "LoopClose_" + Conversion::toString(nodeID()) +
                ": " + cdgNode_->toString();
        } else {
            result += "LoopClose_" + Conversion::toString(nodeID());
        }
    }
    if (isPredicateMoveNode()) {
        result += "Predicate: " + mNode_->toString() + ": " +
            Conversion::toString(nodeID());
    }
    if (isLastNode()) {
        result += "_LAST";
    }
    if (mNode_ != NULL && !isPredicateMoveNode()) {
        result+= mNode_->toString() + ": " + Conversion::toString(nodeID());
    }
    return result;
}
References cdgNode_, isLastNode(), isLoopCloseNode(), isLoopEntryNode(), isPredicateMoveNode(), isRegionNode(), mNode_, GraphNode::nodeID(), ControlDependenceNode::toString(), MoveNode::toString(), and Conversion::toString().
Referenced by cdgNode(), cdgNode(), ProgramDependenceGraph::computeEECInfo(), ProgramDependenceGraph::detectStrongComponents(), dotString(), moveNode(), moveNode(), ProgramDependenceGraph::processPredicate(), ProgramDependenceGraph::processRegion(), ProgramDependenceGraph::removeGuardedJump(), and setPredicateMoveNode().
Friends And Related Symbol Documentation
ProgramDependenceGraph
friend class ProgramDependenceGraph friend
Definition at line 97 of file ProgramDependenceNode.hh.
Member Data Documentation
cdgNode_
ControlDependenceNode* ProgramDependenceNode::cdgNode_ private
Definition at line 103 of file ProgramDependenceNode.hh.
Referenced by cdgNode(), cdgNode(), ProgramDependenceNode(), ProgramDependenceNode(), and toString().
component_
int ProgramDependenceNode::component_ private
Number of strong component the node belongs to. Node can be part of several strong components so this value have practical meaning only for loop close nodes - close just one loop, and loop entry nodes - marks a component in which node is loop entry. Still can be regular region of larger loop Full list of nodes that belongs to actual components is available in strongComponents_ vector in PDG.
Definition at line 116 of file ProgramDependenceNode.hh.
Referenced by component(), isLoopEntryNode(), setComponent(), and setLoopEntryNode().
eec_
NodesInfo ProgramDependenceNode::eec_ private
Stores "eec" information for computing serialization information.
Definition at line 108 of file ProgramDependenceNode.hh.
Referenced by addToEEC(), eec(), printRelations(), and ~ProgramDependenceNode().
lastNode_
bool ProgramDependenceNode::lastNode_ private
Indicates that node must be scheduled last between it's siblings because it's subgraph contains close node and it's parent is entry.
Definition at line 124 of file ProgramDependenceNode.hh.
Referenced by isLastNode(), and setLastNode().
leafBlocks_
std::vector<BasicBlockNode*> ProgramDependenceNode::leafBlocks_ private
Vector of basic blocks of a subgraph that do not have outgoing edged and will need to get connected.
Definition at line 121 of file ProgramDependenceNode.hh.
Referenced by addLeafBlock(), addLeafBlocks(), and leafBlocks().
mNode_
MoveNode* ProgramDependenceNode::mNode_ private
Definition at line 102 of file ProgramDependenceNode.hh.
Referenced by moveNode(), moveNode(), ProgramDependenceNode(), ProgramDependenceNode(), and toString().
newFirstBB_
BasicBlockNode* ProgramDependenceNode::newFirstBB_ private
First basic block of a subgraph of a region.
Definition at line 118 of file ProgramDependenceNode.hh.
Referenced by newFirstBB(), and setNewFirstBB().
region_
NodesInfo ProgramDependenceNode::region_ private
Stores "region" information for computing serialization information.
Definition at line 106 of file ProgramDependenceNode.hh.
Referenced by addToRegion(), printRelations(), region(), and ~ProgramDependenceNode().
type_
NodeType ProgramDependenceNode::type_ private
Definition at line 104 of file ProgramDependenceNode.hh.
Referenced by cdgNode(), cdgNode(), isLoopCloseNode(), isLoopEntryNode(), isLoopEntryNode(), isMoveNode(), isPredicateMoveNode(), isRegionNode(), moveNode(), moveNode(), setLoopEntryNode(), and setPredicateMoveNode().
The documentation for this class was generated from the following files:
ProgramDependenceNode.hh
ProgramDependenceNode.cc