OpenASIP: AddBusEntryCmd Class Reference
AddBusEntryCmd Class Reference
#include <AddBusEntryCmd.hh>
Public Member Functions
AddBusEntryCmd ()
virtual ~AddBusEntryCmd ()
virtual bool Do ()
virtual int id () const
virtual AddBusEntryCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for adding new bus entries to a HDB.
Definition at line 41 of file AddBusEntryCmd.hh.
Constructor & Destructor Documentation
AddBusEntryCmd()
AddBusEntryCmd::AddBusEntryCmd ()
The Constructor.
Definition at line 45 of file AddBusEntryCmd.cc.
                               :
    GUICommand(HDBEditorConstants::COMMAND_NAME_ADD_BUS_ENTRY, NULL) {
}
Referenced by create().
~AddBusEntryCmd()
AddBusEntryCmd::~AddBusEntryCmd () virtual
The Destructor.
Definition at line 53 of file AddBusEntryCmd.cc.
{
}
Member Function Documentation
create()
AddBusEntryCmd * AddBusEntryCmd::create () const virtual
Creates and returns new instance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 103 of file AddBusEntryCmd.cc.
{
    return new AddBusEntryCmd();
}
References AddBusEntryCmd().
Do()
bool AddBusEntryCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 60 of file AddBusEntryCmd.cc.
                   {
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    RowID id = manager->addBusEntry();
    wxGetApp().mainFrame().update();
    wxGetApp().mainFrame().browser()->selectBusEntry(id);
    return true;
}
References HDB::HDBManager::addBusEntry().
icon()
std::string AddBusEntryCmd::icon () const virtual
Returns name of the command icon file.
Returns
Command icon file name.
Implements GUICommand.
Definition at line 81 of file AddBusEntryCmd.cc.
{
    return "";
}
id()
int AddBusEntryCmd::id () const virtual
Returns command identifier for this command.
Returns
Command identifier of this command.
Implements GUICommand.
Definition at line 92 of file AddBusEntryCmd.cc.
{
    return HDBEditorConstants::COMMAND_ADD_BUS_ENTRY;
}
References HDBEditorConstants::COMMAND_ADD_BUS_ENTRY.
isEnabled()
bool AddBusEntryCmd::isEnabled () virtual
Returns true, if the command should be enabled in the menu/toolbar.
Returns
True, if the command is enabled, false if not.
Implements GUICommand.
Definition at line 114 of file AddBusEntryCmd.cc.
{
    HDB::HDBManager* manager = wxGetApp().mainFrame().hdbManager();
    if (manager == NULL) {
        return false;
    }
    return true;
}
The documentation for this class was generated from the following files:
AddBusEntryCmd.hh
AddBusEntryCmd.cc