OpenASIP: MachineState Class Reference
MachineState Class Reference
#include <MachineState.hh>
Public Member Functions
MachineState ()
virtual ~MachineState ()
void clear ()
GCUState & gcuState ()
BusState & busState (const std::string &name)
FUState & fuState (const std::string &name)
int FUStateCount () const
FUState & fuState (int index)
void advanceClockOfAllFUStates ()
void endClockOfAllFUStates ()
void advanceClockOfAllGuardStates ()
void advanceClockOfAllLongImmediateUnitStates ()
void resetAllFUs ()
void clearBuses ()
PortState & portState (const std::string &portName, const std::string &fuName)
LongImmediateUnitState & longImmediateUnitState (const std::string &name)
RegisterFileState & registerFileState (const std::string &name)
GuardState & guardState (const TTAMachine::Guard &guard)
void addGCUState (GCUState *state)
void addBusState (BusState *state, const std::string &name)
void addFUState (FUState *state, const std::string &name)
void addPortState (PortState *state, const std::string &name, const std::string &fuName)
void addLongImmediateUnitState (LongImmediateUnitState *state, const std::string &name)
void addRegisterFileState (RegisterFileState *state, const std::string &name)
void addGuardState (GuardState *state, const TTAMachine::Guard &guard)
void addOperationExecutor (OperationExecutor *executor)
bool isFinished () const
void setFinished (bool finished=true)
Private Types
typedef std::map< std::string, BusState * > BusContainer
Contains bus states indexed by names.
typedef std::map< std::string, FUState * > FUContainer
Contains function unit states indexed by names.
typedef std::map< std::string, PortState * > PortContainer
Contains port states indexed by names.
typedef std::map< std::string, LongImmediateUnitState * > LongImmediateContainer
Contains long immediate unit states indexed by names.
typedef std::map< std::string, RegisterFileState * > RegisterFileContainer
Contains register file states indexed by names.
typedef std::map< const TTAMachine::Guard *, GuardState * > GuardContainer
Contains guard states indexed by their MOM object.
typedef std::vector< OperationExecutor * > ExecutorContainer
Contains operation executors.
typedef std::vector< BusState * > BusCache
typedef std::vector< FUState * > FUCache
typedef std::vector< PortState * > PortCache
typedef std::vector< LongImmediateUnitState * > LongImmediateUnitCache
typedef std::vector< RegisterFileState * > RegisterFileCache
typedef std::vector< GuardState * > GuardCache
Private Member Functions
MachineState (const MachineState &)
Copying not allowed.
MachineState & operator= (const MachineState &)
Assignment not allowed.
Private Attributes
GCUState * GCUState_
GCU state.
BusContainer busses_
Contains all bus states.
FUContainer FUStates_
Container of function unit states for fast traversal.
PortContainer ports_
Contains all port states.
LongImmediateContainer longImmediates_
Contains all long immediate unit states.
RegisterFileContainer registers_
Contains all register file states.
ExecutorContainer executors_
Contains all operation executors.
GuardContainer guards_
Contains all guard states.
std::size_t fuStateCount_
Count of FUStates added in MachineState (optimization).
BusCache busCache_
FUCache fuCache_
PortCache portCache_
LongImmediateUnitCache longImmediateCache_
RegisterFileCache rfCache_
GuardCache guardCache_
bool finished_
Detailed Description
Root class of machine state model.
Owns all state classes.
Definition at line 61 of file MachineState.hh.
Member Typedef Documentation
BusCache
typedef std::vector<BusState*> MachineState::BusCache private
Definition at line 131 of file MachineState.hh.
BusContainer
typedef std::map<std::string, BusState*> MachineState::BusContainer private
Contains bus states indexed by names.
Definition at line 115 of file MachineState.hh.
ExecutorContainer
typedef std::vector<OperationExecutor*> MachineState::ExecutorContainer private
Contains operation executors.
Definition at line 128 of file MachineState.hh.
FUCache
typedef std::vector<FUState*> MachineState::FUCache private
Definition at line 132 of file MachineState.hh.
FUContainer
typedef std::map<std::string, FUState*> MachineState::FUContainer private
Contains function unit states indexed by names.
Definition at line 117 of file MachineState.hh.
GuardCache
typedef std::vector<GuardState*> MachineState::GuardCache private
Definition at line 136 of file MachineState.hh.
GuardContainer
typedef std::map<const TTAMachine::Guard*, GuardState*> MachineState::GuardContainer private
Contains guard states indexed by their MOM object.
Definition at line 126 of file MachineState.hh.
LongImmediateContainer
typedef std::map<std::string, LongImmediateUnitState*> MachineState::LongImmediateContainer private
Contains long immediate unit states indexed by names.
Definition at line 122 of file MachineState.hh.
LongImmediateUnitCache
typedef std::vector<LongImmediateUnitState*> MachineState::LongImmediateUnitCache private
Definition at line 134 of file MachineState.hh.
PortCache
typedef std::vector<PortState*> MachineState::PortCache private
Definition at line 133 of file MachineState.hh.
PortContainer
typedef std::map<std::string, PortState*> MachineState::PortContainer private
Contains port states indexed by names.
Definition at line 119 of file MachineState.hh.
RegisterFileCache
typedef std::vector<RegisterFileState*> MachineState::RegisterFileCache private
Definition at line 135 of file MachineState.hh.
RegisterFileContainer
typedef std::map<std::string, RegisterFileState*> MachineState::RegisterFileContainer private
Contains register file states indexed by names.
Definition at line 124 of file MachineState.hh.
Constructor & Destructor Documentation
MachineState() [1/2]
MachineState::MachineState ()
Constructor.
Definition at line 61 of file MachineState.cc.
                           :
    GCUState_(NULL), fuStateCount_(0), finished_(false) {
}
~MachineState()
MachineState::~MachineState () virtual
Destructor.
Definition at line 68 of file MachineState.cc.
{
    clear();
}
References clear().
MachineState() [2/2]
MachineState::MachineState (const MachineState &) private
Copying not allowed.
Member Function Documentation
addBusState()
void MachineState::addBusState (BusState * state, const std::string & name)
Adds BusState to machine state.
Parameters
state BusState to be added.
name The name of the BusState.
Definition at line 255 of file MachineState.cc.
{
    busses_[name] = state;
    busCache_.push_back(state);
}
References busCache_, and busses_.
Referenced by MachineStateBuilder::buildMachineState().
addFUState()
void MachineState::addFUState (FUState * state, const std::string & name)
Adds FUState.
Parameters
state FUState to be added.
name The name of the FU in ADF.
Definition at line 267 of file MachineState.cc.
{
    FUStates_[name] = state;
    fuCache_.push_back(state);
}
References fuCache_, and FUStates_.
Referenced by MachineStateBuilder::buildMachineState().
addGCUState()
void MachineState::addGCUState (GCUState * state)
Adds GCUState to machine state.
Parameters
state GCUState to be added.
Definition at line 244 of file MachineState.cc.
{
    GCUState_ = state;
}
References GCUState_.
Referenced by MachineStateBuilder::buildMachineState().
addGuardState()
void MachineState::addGuardState (GuardState * state, const TTAMachine::Guard & guard)
Adds GuardState.
Parameters
state State to be added.
guard The machine object model guard the state represents.
Definition at line 325 of file MachineState.cc.
{
    guards_[&guard] = state;
    guardCache_.push_back(state);
}
References guardCache_, and guards_.
Referenced by MachineStateBuilder::buildMachineState().
addLongImmediateUnitState()
void MachineState::addLongImmediateUnitState (LongImmediateUnitState * state, const std::string & name)
Adds LongImmediateUnitState.
Parameters
state LongImmediateUnitState to be added.
name The name of the state.
Definition at line 295 of file MachineState.cc.
{
    longImmediates_[name] = state;
    longImmediateCache_.push_back(state);
}
References longImmediateCache_, and longImmediates_.
Referenced by MachineStateBuilder::buildMachineState().
addOperationExecutor()
void MachineState::addOperationExecutor (OperationExecutor * executor)
Adds operation executor.
Parameters
executor Operation executor.
Definition at line 339 of file MachineState.cc.
{
    executors_.push_back(executor);
}
References executors_.
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU().
addPortState()
void MachineState::addPortState (PortState * state, const std::string & name, const std::string & fuName)
Adds PortState.
Parameters
state PortState to be added.
name Name of the port in ADF.
fuName Name of the FU of the port in ADF.
Definition at line 280 of file MachineState.cc.
{
    ports_[fuName + "." + StringTools::stringToLower(name)] = state;
    portCache_.push_back(state);
}
References portCache_, ports_, and StringTools::stringToLower().
Referenced by MachineStateBuilder::addPortToFU(), and MachineStateBuilder::addVirtualOpcodeSettingPortsToFU().
addRegisterFileState()
void MachineState::addRegisterFileState (RegisterFileState * state, const std::string & name)
Adds RegisterFileState.
Parameters
state State to be added.
name Name of the state.
Definition at line 310 of file MachineState.cc.
{
    registers_[name] = state;
    rfCache_.push_back(state);
}
References registers_, and rfCache_.
Referenced by MachineStateBuilder::buildMachineState().
advanceClockOfAllFUStates()
void MachineState::advanceClockOfAllFUStates ()
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
advanceClockOfAllGuardStates()
void MachineState::advanceClockOfAllGuardStates ()
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
advanceClockOfAllLongImmediateUnitStates()
void MachineState::advanceClockOfAllLongImmediateUnitStates ()
Referenced by SimulationController::simulateCycle().
busState()
BusState & MachineState::busState (const std::string & name)
Returns bus state with a given name.
If bus state with a given name is not found, return NullBusState.
Parameters
name Name of the bus state.
Returns
Bus state with a given name.
Definition at line 116 of file MachineState.cc.
{
    BusContainer::iterator iter = busses_.find(name);
    if (iter == busses_.end()) {
        return NullBusState::instance();
    }
    return *((*iter).second);
}
References busses_, and NullBusState::instance().
Referenced by ProximBusDetailsCmd::Do(), InfoSegmentsCommand::execute(), BusTracker::handleEvent(), and SimProgramBuilder::processMove().
clear()
void MachineState::clear ()
Reserved memory is freed, containers are emptied.
Definition at line 76 of file MachineState.cc.
                    {
    delete GCUState_;
    GCUState_ = NULL;
    // Clear all caches
    busCache_.clear();
    fuCache_.clear();
    portCache_.clear();
    longImmediateCache_.clear();
    rfCache_.clear();
    guardCache_.clear();
    MapTools::deleteAllValues(busses_);
    MapTools::deleteAllValues(FUStates_);
    MapTools::deleteAllValues(ports_);
    MapTools::deleteAllValues(longImmediates_);
    MapTools::deleteAllValues(registers_);
    MapTools::deleteAllValues(guards_);
    SequenceTools::deleteAllItems(executors_);
}
References busCache_, busses_, SequenceTools::deleteAllItems(), MapTools::deleteAllValues(), executors_, fuCache_, FUStates_, GCUState_, guardCache_, guards_, longImmediateCache_, longImmediates_, portCache_, ports_, registers_, and rfCache_.
Referenced by ~MachineState().
clearBuses()
void MachineState::clearBuses ()
Referenced by OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
endClockOfAllFUStates()
void MachineState::endClockOfAllFUStates ()
Referenced by OTASimulationController::advanceMachineCycle(), and SimulationController::simulateCycle().
fuState() [1/2]
FUState & MachineState::fuState (const std::string & name)
Returns the FUState with a given name.
If FUState is not found, returns NullFUState.
Parameters
name Name of the FUState.
Returns
FUState with a given name.
Definition at line 133 of file MachineState.cc.
{
    FUContainer::iterator iter = FUStates_.find(name);
    if (iter == FUStates_.end()) {
        return NullFUState::instance();
    }
    return *((*iter).second);
}
References FUStates_, and NullFUState::instance().
Referenced by FUTestbenchGenerator::createStimulus(), SimpleSimulatorFrontend::setOperationSimulator(), and SimulationController::SimulationController().
fuState() [2/2]
FUState & MachineState::fuState (int index)
Returns the FUState with a given index.
Parameters
index The index of the FUState.
Returns
The FUState with a given index.
Exceptions
OutOfRange If index is out of range.
Definition at line 149 of file MachineState.cc.
{
    const int count = FUStateCount();
    if (index < 0 || (index > count - 1)) {
        string msg = "FUState index out of range";
        throw OutOfRange(__FILE__, __LINE__, __func__, msg);
    }
    int i = 0;
    FUContainer::iterator iter = FUStates_.begin();
    while (i < index) {
        iter++;
        ++i;
    }
    return *((*iter).second);
}
References __func__, FUStateCount(), and FUStates_.
FUStateCount()
int MachineState::FUStateCount () const
Referenced by fuState(), and SimulationController::SimulationController().
gcuState()
GCUState & MachineState::gcuState ()
Returns the GCUState of the machine state.
Returns
GCUState.
Definition at line 103 of file MachineState.cc.
                       {
    return *GCUState_;
}
References GCUState_.
Referenced by OTASimulationController::advanceMachineCycle(), OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
guardState()
GuardState & MachineState::guardState (const TTAMachine::Guard & guard)
Returns the GuardState associated with the given MOM Guard.
If not found, returns NullGuardState::instace().
Parameters
name The MOM Guard instance.
Returns
GuardState associated with the instance.
Definition at line 230 of file MachineState.cc.
{
    GuardContainer::iterator iter = guards_.find(&guard);
    if (iter == guards_.end()) {
        return NullGuardState::instance();
    }
    return *((*iter).second);
}
References guards_, and NullGuardState::instance().
Referenced by SimProgramBuilder::findGuardModel().
isFinished()
bool MachineState::isFinished () const inline
Definition at line 105 of file MachineState.hh.
{ return finished_; }
References finished_.
Referenced by SimulationController::simulateCycle().
longImmediateUnitState()
LongImmediateUnitState & MachineState::longImmediateUnitState (const std::string & name)
Returns LongImmediateUnitState with a given name.
If LongImmediateUnitState is not found, returns NullLongImmediateUnistState.
Parameters
name The name of the LongImmediateUnitState.
Returns
LongImmediateUnitState with a given name.
Definition at line 196 of file MachineState.cc.
{
    LongImmediateContainer::iterator iter = longImmediates_.find(name);
    if (iter == longImmediates_.end()) {
        return NullLongImmediateUnitState::instance();
    }
    return *((*iter).second);
}
References NullLongImmediateUnitState::instance(), and longImmediates_.
Referenced by ProximIUDetailsCmd::Do(), ProximRegisterWindow::loadImmediateUnit(), SimProgramBuilder::processInstruction(), and SimProgramBuilder::processSourceTerminal().
operator=()
MachineState & MachineState::operator= (const MachineState &) private
Assignment not allowed.
portState()
PortState & MachineState::portState (const std::string & portName, const std::string & fuName)
Returns PortState with a given name.
If PortState is not found, return NullPortState.
Parameters
portName The name of the PortState.
fuName The name of the parent FU of the port.
Returns
PortState with a given name.
Definition at line 175 of file MachineState.cc.
{
    PortContainer::iterator i =
        ports_.find(fuName + "." + StringTools::stringToLower(portName));
    if (i == ports_.end())
        return NullPortState::instance();
    else
        return *(*i).second;
}
References NullPortState::instance(), ports_, and StringTools::stringToLower().
Referenced by MachineStateBuilder::addVirtualOpcodeSettingPortsToFU(), MachineStateBuilder::bindPortsToOperands(), MachineStateBuilder::buildMachineState(), ProximFUDetailsCmd::Do(), ProximFUPortDetailsCmd::Do(), SimulatorFrontend::findPort(), FUTestbenchGenerator::parseFuPorts(), SimProgramBuilder::processBidirTerminal(), FUTestbenchGenerator::readValuesFromOutPorts(), ProximPortWindow::update(), and FUTestbenchGenerator::writeInputPortStimulus().
registerFileState()
RegisterFileState & MachineState::registerFileState (const std::string & name)
Returns RegisterFileState with a given name.
If RegisterFileState is not found, return NullRegisterFileState.
Parameters
name The name of the state.
Returns
RegisterFileState with a given name.
Definition at line 213 of file MachineState.cc.
{
    RegisterFileContainer::iterator iter = registers_.find(name);
    if (iter == registers_.end()) {
        return NullRegisterFileState::instance();
    }
    return *((*iter).second);
}
References NullRegisterFileState::instance(), and registers_.
Referenced by MachineStateBuilder::buildMachineState(), RFTestbenchGenerator::createStimulus(), ProximRFDetailsCmd::Do(), SimulatorFrontend::findBooleanRegister(), SimulatorFrontend::findRegister(), ProximRegisterWindow::loadRegisterFile(), and SimProgramBuilder::processBidirTerminal().
resetAllFUs()
void MachineState::resetAllFUs ()
setFinished()
void MachineState::setFinished (bool finished = true) inline
Definition at line 106 of file MachineState.hh.
{ finished_ = finished; }
References finished_.
Referenced by OTASimulationController::simulateCycle(), and SimulationController::simulateCycle().
Member Data Documentation
busCache_
BusCache MachineState::busCache_ private
Definition at line 158 of file MachineState.hh.
Referenced by addBusState(), and clear().
busses_
BusContainer MachineState::busses_ private
Contains all bus states.
Definition at line 141 of file MachineState.hh.
Referenced by addBusState(), busState(), and clear().
executors_
ExecutorContainer MachineState::executors_ private
Contains all operation executors.
Definition at line 151 of file MachineState.hh.
Referenced by addOperationExecutor(), and clear().
finished_
bool MachineState::finished_ private
Definition at line 167 of file MachineState.hh.
Referenced by isFinished(), and setFinished().
fuCache_
FUCache MachineState::fuCache_ private
Definition at line 159 of file MachineState.hh.
Referenced by addFUState(), and clear().
fuStateCount_
std::size_t MachineState::fuStateCount_ private
Count of FUStates added in MachineState (optimization).
Definition at line 155 of file MachineState.hh.
FUStates_
FUContainer MachineState::FUStates_ private
Container of function unit states for fast traversal.
Definition at line 143 of file MachineState.hh.
Referenced by addFUState(), clear(), fuState(), and fuState().
GCUState_
GCUState* MachineState::GCUState_ private
GCU state.
Definition at line 139 of file MachineState.hh.
Referenced by addGCUState(), clear(), and gcuState().
guardCache_
GuardCache MachineState::guardCache_ private
Definition at line 163 of file MachineState.hh.
Referenced by addGuardState(), and clear().
guards_
GuardContainer MachineState::guards_ private
Contains all guard states.
Definition at line 153 of file MachineState.hh.
Referenced by addGuardState(), clear(), and guardState().
longImmediateCache_
LongImmediateUnitCache MachineState::longImmediateCache_ private
Definition at line 161 of file MachineState.hh.
Referenced by addLongImmediateUnitState(), and clear().
longImmediates_
LongImmediateContainer MachineState::longImmediates_ private
Contains all long immediate unit states.
Definition at line 147 of file MachineState.hh.
Referenced by addLongImmediateUnitState(), clear(), and longImmediateUnitState().
portCache_
PortCache MachineState::portCache_ private
Definition at line 160 of file MachineState.hh.
Referenced by addPortState(), and clear().
ports_
PortContainer MachineState::ports_ private
Contains all port states.
Definition at line 145 of file MachineState.hh.
Referenced by addPortState(), clear(), and portState().
registers_
RegisterFileContainer MachineState::registers_ private
Contains all register file states.
Definition at line 149 of file MachineState.hh.
Referenced by addRegisterFileState(), clear(), and registerFileState().
rfCache_
RegisterFileCache MachineState::rfCache_ private
Definition at line 162 of file MachineState.hh.
Referenced by addRegisterFileState(), and clear().
The documentation for this class was generated from the following files:
MachineState.hh
MachineState.cc