OpenASIP: ProximRegisterWindow Class Reference
ProximRegisterWindow Class Reference
#include <ProximRegisterWindow.hh>
Public Member Functions
ProximRegisterWindow (ProximMainFrame *parent, int id)
virtual ~ProximRegisterWindow ()
void showRegisterFile (const std::string &name)
void showImmediateUnit (const std::string &name)
Public Member Functions inherited from ProximUnitWindow
ProximUnitWindow (ProximMainFrame *parent, int id)
virtual ~ProximUnitWindow ()
Public Member Functions inherited from ProximSimulatorWindow
virtual void reset ()
Private Member Functions
void loadRegisterFile (const TTAMachine::RegisterFile &rf)
void loadImmediateUnit (const TTAMachine::ImmediateUnit &iu)
virtual void reinitialize ()
virtual void update ()
Static Private Attributes
static const std::string RF_PREFIX = "RF: "
Prefix for register files in the unit choicer.
static const std::string IMM_PREFIX = "IMM: "
Prefix for immediate units in the unit choicer.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Protected Attributes inherited from ProximUnitWindow
SimulatorFrontend * simulator_
Simulator instance .
wxChoice * unitChoice_
Unit choicer widget.
wxChoice * modeChoice_
Value display mode choicer widget.
wxListCtrl * valueList_
List widget for the values.
Static Protected Attributes inherited from ProximUnitWindow
static const wxString MODE_INT = _T("Int")
String for the mode choicer integer mode.
static const wxString MODE_UNSIGNED = _T("Unsigned")
String for the mode choicer unsigned integer mode.
static const wxString MODE_HEX = _T("Hex")
String for the mode choicer hexadecimal mode.
static const wxString MODE_BIN = _T("Binary")
String for the mode choicer binary mode.
Detailed Description
Proxim subwindow which displays register values.
This window listens to SimulatorEvents and updates the window contents automatically.
Definition at line 54 of file ProximRegisterWindow.hh.
Constructor & Destructor Documentation
ProximRegisterWindow()
ProximRegisterWindow::ProximRegisterWindow (ProximMainFrame * parent, int id)
Constructor.
Parameters
parent Parent window of the window.
id Window identifier.
Definition at line 73 of file ProximRegisterWindow.cc.
                                    :
    ProximUnitWindow(parent, id) {
    valueList_->InsertColumn(0, _T("Register"), wxLIST_FORMAT_LEFT, 100);
    valueList_->InsertColumn(1, _T("Value"), wxLIST_FORMAT_RIGHT, 120);
    modeChoice_->Disable();
    if (simulator_->isSimulationInitialized() ||
        simulator_->isSimulationStopped() ||
        simulator_->hasSimulationEnded()) {
        reinitialize();
    }
}
References SimulatorFrontend::hasSimulationEnded(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationStopped(), ProximUnitWindow::modeChoice_, reinitialize(), ProximUnitWindow::simulator_, and ProximUnitWindow::valueList_.
~ProximRegisterWindow()
ProximRegisterWindow::~ProximRegisterWindow () virtual
Destructor.
Definition at line 93 of file ProximRegisterWindow.cc.
{
}
Member Function Documentation
loadImmediateUnit()
void ProximRegisterWindow::loadImmediateUnit (const TTAMachine::ImmediateUnit & iu) private
Loads register file registers to the register list.
Parameters
imm Immediate Unit to display.
Definition at line 205 of file ProximRegisterWindow.cc.
{
    valueList_->DeleteAllItems();
    LongImmediateUnitState& immState =
    simulator_->machineState().longImmediateUnitState(imm.name());
    // Append all registers to the register list.
    int row = 0;
    for (int i = 0; i < immState.immediateRegisterCount(); i++) {
    wxString value;
    const LongImmediateRegisterState& state =
            immState.immediateRegister(i);
        wxString mode = modeChoice_->GetStringSelection();
        if (mode == MODE_UNSIGNED) {
        value = WxConversion::toWxString(state.value().unsignedValue());
        } else if (mode == MODE_INT) {
            int intValue = state.value().intValue();
        value = WxConversion::toWxString(intValue);
        } else if (mode == MODE_HEX) {
        value = WxConversion::toWxString(
                Conversion::toHexString(state.value().unsignedValue()));
        } else if (mode == MODE_BIN) {
            int intValue = static_cast<int>(state.value().unsignedValue());
        value = WxConversion::toWxString(
                Conversion::toBinString(intValue));
        }
    DisassemblyRegister r(imm.name(), i);
    valueList_->InsertItem(
        row, WxConversion::toWxString(r.toString()));
    valueList_->SetItem(row, 1, value);
    row++;
    }
}
References LongImmediateUnitState::immediateRegister(), LongImmediateUnitState::immediateRegisterCount(), SimValue::intValue(), MachineState::longImmediateUnitState(), SimulatorFrontend::machineState(), ProximUnitWindow::MODE_BIN, ProximUnitWindow::MODE_HEX, ProximUnitWindow::MODE_INT, ProximUnitWindow::MODE_UNSIGNED, ProximUnitWindow::modeChoice_, TTAMachine::Component::name(), ProximUnitWindow::simulator_, Conversion::toBinString(), Conversion::toHexString(), DisassemblyRegister::toString(), WxConversion::toWxString(), SimValue::unsignedValue(), LongImmediateRegisterState::value(), and ProximUnitWindow::valueList_.
Referenced by update().
loadRegisterFile()
void ProximRegisterWindow::loadRegisterFile (const TTAMachine::RegisterFile & rf) private
Loads register file registers to the register list.
Parameters
rf Register file to display.
Definition at line 161 of file ProximRegisterWindow.cc.
{
    valueList_->DeleteAllItems();
    RegisterFileState& rfState =
    simulator_->machineState().registerFileState(rf.name());
    // Append all registers to the register list.
    int row = 0;
    for (unsigned i = 0; i < rfState.registerCount(); i++) {
    wxString value;
    const RegisterState& state = rfState.registerState(i);
        wxString mode = modeChoice_->GetStringSelection();
        if (mode == MODE_UNSIGNED) {
        value = WxConversion::toWxString(state.value().unsignedValue());
        } else if (mode == MODE_INT) {
            int intValue = state.value().intValue();
        value = WxConversion::toWxString(intValue);
        } else if (mode == MODE_HEX) {
        value = WxConversion::toWxString(
                Conversion::toHexString(state.value().unsignedValue()));
        } else if (mode == MODE_BIN) {
            int intValue = state.value().intValue();
        value = WxConversion::toWxString(
                Conversion::toBinString(intValue));
        }
    DisassemblyRegister r(rf.name(), i);
    valueList_->InsertItem(
        row, WxConversion::toWxString(r.toString()));
    valueList_->SetItem(row, 1, value);
    row++;
    }
}
References SimValue::intValue(), SimulatorFrontend::machineState(), ProximUnitWindow::MODE_BIN, ProximUnitWindow::MODE_HEX, ProximUnitWindow::MODE_INT, ProximUnitWindow::MODE_UNSIGNED, ProximUnitWindow::modeChoice_, TTAMachine::Component::name(), RegisterFileState::registerCount(), MachineState::registerFileState(), RegisterFileState::registerState(), ProximUnitWindow::simulator_, Conversion::toBinString(), Conversion::toHexString(), DisassemblyRegister::toString(), WxConversion::toWxString(), SimValue::unsignedValue(), RegisterState::value(), and ProximUnitWindow::valueList_.
Referenced by update().
reinitialize()
void ProximRegisterWindow::reinitialize () private virtual
Sets the available register file selections in the register file choice.
Reimplemented from ProximUnitWindow.
Definition at line 101 of file ProximRegisterWindow.cc.
{
    unitChoice_->Clear();
    // parallel simulation
    const Machine::RegisterFileNavigator& rfNavigator =
    simulator_->machine().registerFileNavigator();
    for (int i = 0; i < rfNavigator.count(); i++) {
    string rfName = RF_PREFIX + rfNavigator.item(i)->name();
    unitChoice_->Append(WxConversion::toWxString(rfName));
    }
    const Machine::ImmediateUnitNavigator& immNavigator =
    simulator_->machine().immediateUnitNavigator();
    for (int i = 0; i < immNavigator.count(); i++) {
    string rfName = IMM_PREFIX + immNavigator.item(i)->name();
    unitChoice_->Append(WxConversion::toWxString(rfName));
    }
    unitChoice_->SetSelection(0);
    update();
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), IMM_PREFIX, TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), SimulatorFrontend::machine(), TTAMachine::Machine::registerFileNavigator(), RF_PREFIX, ProximUnitWindow::simulator_, WxConversion::toWxString(), ProximUnitWindow::unitChoice_, and update().
Referenced by ProximRegisterWindow().
showImmediateUnit()
void ProximRegisterWindow::showImmediateUnit (const std::string & name)
Sets the immediate unit dipslayed in the window.
Parameters
name Name of the immediate unit.
Definition at line 265 of file ProximRegisterWindow.cc.
{
    unitChoice_->SetStringSelection(
        WxConversion::toWxString(IMM_PREFIX + name));
    update();
}
References IMM_PREFIX, WxConversion::toWxString(), ProximUnitWindow::unitChoice_, and update().
showRegisterFile()
void ProximRegisterWindow::showRegisterFile (const std::string & name)
Sets the registerfile displayed in the window.
Parameters
name Name of the register file.
Definition at line 252 of file ProximRegisterWindow.cc.
{
    unitChoice_->SetStringSelection(
        WxConversion::toWxString(RF_PREFIX + name));
    update();
}
References RF_PREFIX, WxConversion::toWxString(), ProximUnitWindow::unitChoice_, and update().
Referenced by ProximShowRegistersCmd::Do().
update()
void ProximRegisterWindow::update () private virtual
Event handler for the register file choicer.
When the choice selection changes, corresponding register file registers are loaded in the register list.
Reimplemented from ProximUnitWindow.
Definition at line 133 of file ProximRegisterWindow.cc.
{
    int rfIndex = unitChoice_->GetSelection();
    modeChoice_->Disable();
    modeChoice_->Enable();
    // Machine is not a universal machine.
    const Machine::RegisterFileNavigator& rfNavigator =
        simulator_->machine().registerFileNavigator();
    if (rfIndex < rfNavigator.count()) {
        loadRegisterFile(*rfNavigator.item(rfIndex));
    } else {
        const Machine::ImmediateUnitNavigator& immNavigator =
            simulator_->machine().immediateUnitNavigator();
        rfIndex = rfIndex - rfNavigator.count();
        loadImmediateUnit(*immNavigator.item(rfIndex));
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::immediateUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), loadImmediateUnit(), loadRegisterFile(), SimulatorFrontend::machine(), ProximUnitWindow::modeChoice_, TTAMachine::Machine::registerFileNavigator(), ProximUnitWindow::simulator_, and ProximUnitWindow::unitChoice_.
Referenced by reinitialize(), showImmediateUnit(), and showRegisterFile().
Member Data Documentation
IMM_PREFIX
const std::string ProximRegisterWindow::IMM_PREFIX = "IMM: " static private
Prefix for immediate units in the unit choicer.
Definition at line 70 of file ProximRegisterWindow.hh.
Referenced by reinitialize(), and showImmediateUnit().
RF_PREFIX
const std::string ProximRegisterWindow::RF_PREFIX = "RF: " static private
Prefix for register files in the unit choicer.
Definition at line 68 of file ProximRegisterWindow.hh.
Referenced by reinitialize(), and showRegisterFile().
The documentation for this class was generated from the following files:
ProximRegisterWindow.hh
ProximRegisterWindow.cc