OpenASIP: ProximOpenMachineCmd Class Reference
ProximOpenMachineCmd Class Reference
#include <ProximOpenMachineCmd.hh>
Public Member Functions
ProximOpenMachineCmd ()
virtual ~ProximOpenMachineCmd ()
virtual bool Do ()
virtual int id () const
virtual ProximOpenMachineCmd * create () const
virtual std::string icon () const
virtual bool isEnabled ()
virtual std::string shortName () const
Public Member Functions inherited from GUICommand
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual bool isChecked () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Detailed Description
Command for opening a machine desctiption file in Proxim.
The command displays a file dialog for choosing the machine file to open.
Definition at line 43 of file ProximOpenMachineCmd.hh.
Constructor & Destructor Documentation
ProximOpenMachineCmd()
ProximOpenMachineCmd::ProximOpenMachineCmd ()
The Constructor.
Definition at line 48 of file ProximOpenMachineCmd.cc.
                                          :
    GUICommand(ProximConstants::COMMAND_NAME_OPEN_MACHINE, NULL) {
    }
Referenced by create().
~ProximOpenMachineCmd()
ProximOpenMachineCmd::~ProximOpenMachineCmd () virtual
The Destructor.
Definition at line 56 of file ProximOpenMachineCmd.cc.
{
}
Member Function Documentation
create()
ProximOpenMachineCmd * ProximOpenMachineCmd::create () const virtual
Creates and returns a new isntance of this command.
Returns
Newly created instance of this command.
Implements GUICommand.
Definition at line 122 of file ProximOpenMachineCmd.cc.
{
    return new ProximOpenMachineCmd();
}
References ProximOpenMachineCmd().
Do()
bool ProximOpenMachineCmd::Do () virtual
Executes the command.
Implements GUICommand.
Definition at line 64 of file ProximOpenMachineCmd.cc.
{
    assert(parentWindow() != NULL);
    wxString wildcard = _T("Architecture Definition Files (*.adf)|*.adf");
    wildcard.Append(_T("|Processor Configuration Files (*.pcf)|*.pcf"));
    wildcard.Append(_T("|All files|*.*"));
    wxFileDialog dialog(
    parentWindow(), _T("Choose a file."), _T(""), _T(""),
    wildcard, wxOPEN);
    if (dialog.ShowModal() == wxID_CANCEL) {
    return false;
    }
    std::string command;
    std::string file = WxConversion::toString(dialog.GetPath());
    std::string extension = FileSystem::fileExtension(file);
    // Simulator interpreter command is chose according to file extension.
    // Processor configuration files (.pcf), have to be opened using
    // 'conf' command.
    if (extension == ".pcf") {
    command = ProximConstants::SCL_LOAD_CONF + " \"" + file + "\"";
    } else {
    command = ProximConstants::SCL_LOAD_MACHINE + " \"" + file + "\"";
    }
    wxGetApp().simulation()->lineReader().input(command);
    return true;
}
References assert, FileSystem::fileExtension(), GUICommand::parentWindow(), ProximConstants::SCL_LOAD_CONF, ProximConstants::SCL_LOAD_MACHINE, and WxConversion::toString().
icon()
std::string ProximOpenMachineCmd::icon () const virtual
Returns full path to the command icon file.
Returns
Full path to the command icon file.
Implements GUICommand.
Definition at line 102 of file ProximOpenMachineCmd.cc.
{
    return "open_machine.png";
}
id()
int ProximOpenMachineCmd::id () const virtual
Returns ID of this command.
Implements GUICommand.
Definition at line 111 of file ProximOpenMachineCmd.cc.
{
    return ProximConstants::COMMAND_OPEN_MACHINE;
}
References ProximConstants::COMMAND_OPEN_MACHINE.
isEnabled()
bool ProximOpenMachineCmd::isEnabled () virtual
Returns true if the command is enabled, false otherwise.
Returns
Always true.
Implements GUICommand.
Definition at line 133 of file ProximOpenMachineCmd.cc.
{
    return true;
}
shortName()
std::string ProximOpenMachineCmd::shortName () const virtual
Returns shortened name of the command for toolbar button text.
Returns
Short version of the command name.
Reimplemented from GUICommand.
Definition at line 143 of file ProximOpenMachineCmd.cc.
{
    return "Machine";
}
The documentation for this class was generated from the following files:
ProximOpenMachineCmd.hh
ProximOpenMachineCmd.cc