OpenASIP: ProGe::NetlistVisualization Class Reference
ProGe::NetlistVisualization Class Reference
#include <NetlistVisualization.hh>
Public Member Functions
NetlistVisualization ()
virtual ~NetlistVisualization ()
Static Public Member Functions
static void visualizeBlockTree (const BaseNetlistBlock &root, std::ostream &streamOut)
static void listConnections (const BaseNetlistBlock &block, std::ostream &streamOut)
static void listNetlistDescriptors (const BaseNetlistBlock &block, std::ostream &streamOut)
static void listNetlistDescriptors (const Netlist &netlist, std::ostream &streamOut)
static std::string toString (Direction dir)
static std::string portWidthToString (const NetlistPort &port)
Static Private Member Functions
static void printBlockTree (const BaseNetlistBlock &node, std::string prefix, std::ostream &streamOut)
static void printBlock (const BaseNetlistBlock &root, const std::string &prefix, std::ostream &streamOut)
static void printParameter (const Parameter &parameter, const std::string &prefix, std::ostream &streamOut)
static void printPort (const NetlistPort &port, const std::string &prefix, std::ostream &streamOut)
Detailed Description
Definition at line 50 of file NetlistVisualization.hh.
Constructor & Destructor Documentation
NetlistVisualization()
ProGe::NetlistVisualization::NetlistVisualization ()
Definition at line 53 of file NetlistVisualization.cc.
{}
~NetlistVisualization()
ProGe::NetlistVisualization::~NetlistVisualization () virtual
Definition at line 55 of file NetlistVisualization.cc.
{}
Member Function Documentation
listConnections()
void ProGe::NetlistVisualization::listConnections (const BaseNetlistBlock & block, std::ostream & streamOut) static
Definition at line 65 of file NetlistVisualization.cc.
{
    //    typedef boost::graph_traits<Netlist>::edge_iterator EdgeIterator;
    //    typedef std::pair<EdgeIterator, EdgeIterator> EdgePair;
    typedef std::pair<std::string, std::string> PortNamePair;
    typedef std::set<PortNamePair> ConnectionSet;
    ConnectionSet connections;
    //    EdgePair edge_it;
    Netlist::const_iterator edge_it;
    for (edge_it = block.netlist().begin(); edge_it != block.netlist().end();
         edge_it++) {
        const NetlistPort* port_a =
            block.netlist()[boost::source(*edge_it, block.netlist())];
        const NetlistPort* port_b =
            block.netlist()[boost::target(*edge_it, block.netlist())];
        std::string port_a_name(port_a->parentBlock().instanceName());
        port_a_name += ":" + port_a->name();
        std::string port_b_name(port_b->parentBlock().instanceName());
        port_b_name += ":" + port_b->name();
        if (port_a_name < port_b_name) {
            connections.insert(std::make_pair(port_a_name, port_b_name));
        } else {
            connections.insert(std::make_pair(port_b_name, port_a_name));
        }
    }
    ConnectionSet::const_iterator conn_it;
    for (conn_it = connections.begin(); conn_it != connections.end();
         conn_it++) {
        streamOut << conn_it->first << " <-> " << conn_it->second
                  << std::endl;
    }
}
References ProGe::Netlist::begin(), ProGe::Netlist::end(), ProGe::BaseNetlistBlock::instanceName(), ProGe::NetlistPort::name(), ProGe::BaseNetlistBlock::netlist(), and ProGe::NetlistPort::parentBlock().
listNetlistDescriptors() [1/2]
void ProGe::NetlistVisualization::listNetlistDescriptors (const BaseNetlistBlock & block, std::ostream & streamOut) static
Definition at line 103 of file NetlistVisualization.cc.
{
    listNetlistDescriptors(block.netlist(), streamOut);
}
References listNetlistDescriptors(), and ProGe::BaseNetlistBlock::netlist().
Referenced by listNetlistDescriptors().
listNetlistDescriptors() [2/2]
void ProGe::NetlistVisualization::listNetlistDescriptors (const Netlist & netlist, std::ostream & streamOut) static
Definition at line 109 of file NetlistVisualization.cc.
{
    Netlist::const_descriptor_iterator desc_it;
    for (desc_it = netlist.descriptorBegin();
         desc_it != netlist.descriptorEnd(); desc_it++) {
        const NetlistPort* port = desc_it->first;
        const BaseNetlistBlock* parent = &port->parentBlock();
        size_t descriptor = desc_it->second;
        streamOut << parent->instanceName() << ":" << port->name() << ":"
                  << descriptor << std::endl;
    }
}
References ProGe::Netlist::descriptorBegin(), ProGe::Netlist::descriptorEnd(), ProGe::BaseNetlistBlock::instanceName(), ProGe::NetlistPort::name(), and ProGe::NetlistPort::parentBlock().
portWidthToString()
std::string ProGe::NetlistVisualization::portWidthToString (const NetlistPort & port) static
Definition at line 184 of file NetlistVisualization.cc.
{
    if (port.dataType() == BIT) {
        return "1";
    } else if (port.dataType() == BIT_VECTOR) {
        if (port.realWidthAvailable()) {
            return std::string("[") + Conversion::toString(port.realWidth()) +
                   "-1:0]";
        } else {
            return std::string("[") + port.widthFormula() + "-1:0]";
        }
    } else {
        return "N/A";
    }
}
References ProGe::BIT, ProGe::BIT_VECTOR, ProGe::NetlistPort::dataType(), ProGe::NetlistPort::realWidth(), ProGe::NetlistPort::realWidthAvailable(), Conversion::toString(), and ProGe::NetlistPort::widthFormula().
Referenced by printPort().
printBlock()
void ProGe::NetlistVisualization::printBlock (const BaseNetlistBlock & root, const std::string & prefix, std::ostream & streamOut) static private
Definition at line 145 of file NetlistVisualization.cc.
{
    streamOut << prefix << "Blk: " << blockNode.instanceName() << " : "
              << blockNode.moduleName() << std::endl;
}
References ProGe::BaseNetlistBlock::instanceName(), and ProGe::BaseNetlistBlock::moduleName().
Referenced by printBlockTree(), and visualizeBlockTree().
printBlockTree()
void ProGe::NetlistVisualization::printBlockTree (const BaseNetlistBlock & node, std::string prefix, std::ostream & streamOut) static private
Definition at line 123 of file NetlistVisualization.cc.
{
    for (size_t i = 0; i < blockNode.parameterCount(); i++) {
        printParameter(blockNode.parameter(i), prefix + "|- ", streamOut);
    }
    for (size_t i = 0; i < blockNode.portCount(); i++) {
        printPort(blockNode.port(i), prefix + "|- ", streamOut);
    }
    for (size_t i = 0; i < blockNode.subBlockCount(); i++) {
        printBlock(blockNode.subBlock(i), prefix + "+- ", streamOut);
        printBlockTree(
            blockNode.subBlock(i),
            prefix + TCEString::applyIf(
                         i < blockNode.subBlockCount() - 1, "|  ", "   "),
            streamOut);
    }
}
References TCEString::applyIf(), ProGe::BaseNetlistBlock::parameter(), ProGe::BaseNetlistBlock::parameterCount(), ProGe::BaseNetlistBlock::port(), ProGe::BaseNetlistBlock::portCount(), printBlock(), printBlockTree(), printParameter(), printPort(), ProGe::BaseNetlistBlock::subBlock(), and ProGe::BaseNetlistBlock::subBlockCount().
Referenced by printBlockTree(), and visualizeBlockTree().
printParameter()
void ProGe::NetlistVisualization::printParameter (const Parameter & parameter, const std::string & prefix, std::ostream & streamOut) static private
Definition at line 153 of file NetlistVisualization.cc.
{
    streamOut << prefix << "Prm: " << parameter.name() << " : "
              << parameter.type() << " := " << parameter.value() << std::endl;
}
References ProGe::Parameter::name(), ProGe::Parameter::type(), and ProGe::Parameter::value().
Referenced by printBlockTree().
printPort()
void ProGe::NetlistVisualization::printPort (const NetlistPort & port, const std::string & prefix, std::ostream & streamOut) static private
Definition at line 161 of file NetlistVisualization.cc.
{
    streamOut << prefix << "Prt: " << port.name() << " "
              << toString(port.direction()) << " " << portWidthToString(port)
              << std::endl;
}
References ProGe::NetlistPort::direction(), ProGe::NetlistPort::name(), portWidthToString(), and toString().
Referenced by printBlockTree().
toString()
std::string ProGe::NetlistVisualization::toString (Direction dir) static
Definition at line 170 of file NetlistVisualization.cc.
{
    switch (dir) {
        case IN:
            return "in";
        case OUT:
            return "out";
        case BIDIR:
            return "bidir";
        default:
            return "N/A";
    }
}
References ProGe::BIDIR, ProGe::IN, and ProGe::OUT.
Referenced by printPort().
visualizeBlockTree()
void ProGe::NetlistVisualization::visualizeBlockTree (const BaseNetlistBlock & root, std::ostream & streamOut) static
Definition at line 58 of file NetlistVisualization.cc.
{
    printBlock(root, "", streamOut);
    printBlockTree(root, "", streamOut);
}
References printBlock(), and printBlockTree().
Referenced by ProGe::ProcessorGenerator::generateProcessor().
The documentation for this class was generated from the following files:
NetlistVisualization.hh
NetlistVisualization.cc