OpenASIP: GUICommand Class Reference
GUICommand Class Reference abstract
#include <GUICommand.hh>
Inherited by AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, ClearDisassemblyHighlightCmd, CreateHDBCmd, EditorCommand, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, OpenHDBCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, and UserManualCmd.
Public Member Functions
GUICommand (std::string name, wxWindow *parent)
virtual ~GUICommand ()
virtual int id () const =0
virtual GUICommand * create () const =0
virtual bool Do ()=0
virtual bool isEnabled ()=0
virtual std::string icon () const =0
virtual bool isChecked () const
virtual std::string shortName () const
void setParentWindow (wxWindow *view)
wxWindow * parentWindow () const
std::string name () const
Private Attributes
wxWindow * parent_
Parent window of the command.
std::string name_
Name of the command.
Detailed Description
Base class for editor commands, which can be added to menus or toolbar.
Definition at line 43 of file GUICommand.hh.
Constructor & Destructor Documentation
GUICommand()
GUICommand::GUICommand (std::string name, wxWindow * parent = NULL)
The Constructor.
Definition at line 42 of file GUICommand.cc.
                                                              :
    parent_(parent), name_(name) {
}
~GUICommand()
GUICommand::~GUICommand () virtual
The Destructor.
Definition at line 52 of file GUICommand.cc.
{
}
Member Function Documentation
create()
virtual GUICommand * GUICommand::create () const pure virtual
Creates a new GUICommand instance.
Returns
New GUICommand instance.
Implemented in UserManualCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, ClearDisassemblyHighlightCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, CreateHDBCmd, AddFUArchFromADFCmd, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, OpenHDBCmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Referenced by CommandRegistry::createCommand(), and CommandRegistry::createCommand().
Do()
virtual bool GUICommand::Do () pure virtual
Executes the command.
Returns
True, if the command was succesfully executed, false otherwise.
Implemented in UserManualCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, ClearDisassemblyHighlightCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, CreateHDBCmd, AddFUArchFromADFCmd, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, OpenHDBCmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Referenced by QuitCmd::Do(), ProximMainFrame::onClose(), OSEdMainFrame::onCommandEvent(), ProximMainFrame::onCommandEvent(), HDBEditorMainFrame::onCommandEvent(), MainFrame::onCommandEvent(), and OSEdTreeView::onItemClicked().
icon()
virtual std::string GUICommand::icon () const pure virtual
Returns name of the command icon file.
Returns
Name of the command icon file.
Implemented in UserManualCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, ClearDisassemblyHighlightCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, CreateHDBCmd, AddFUArchFromADFCmd, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, OpenHDBCmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, AboutCmd, AddFUFromHDBCmd, AddIUFromHDBCmd, AddRFFromHDBCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditorCommand, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, UndoCmd, VerifyMachineCmd, ZoomInCmd, and ZoomOutCmd.
id()
virtual int GUICommand::id () const pure virtual
Returns the ID of the command.
Returns
The ID of the command.
Implemented in UserManualCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, ClearDisassemblyHighlightCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, CreateHDBCmd, AddFUArchFromADFCmd, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, OpenHDBCmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Referenced by CommandRegistry::commandId(), OptionsDialog::readCommands(), DropDownMenu::updateMenu(), and OSEdMainFrame::updateMenuBar().
isChecked()
bool GUICommand::isChecked () const virtual
Returns true if a checkbox related to the command is checked.
This is meaningful only for toggle-type commands.
Returns
True, if the command feature is toggled on.
Reimplemented in ToggleUnitDetailsCmd.
Definition at line 112 of file GUICommand.cc.
{
    return false;
}
Referenced by MainFrame::onUpdateUI().
isEnabled()
virtual bool GUICommand::isEnabled () pure virtual
Returns true if the command is executable, false otherwise.
Returns
True, if the command is executable, false otherwise.
Implemented in UserManualCmd, OSEdAboutCmd, OSEdAddModuleCmd, OSEdAddOperationCmd, OSEdBuildAllCmd, OSEdBuildCmd, OSEdMemoryCmd, OSEdModifyBehaviorCmd, OSEdOptionsCmd, OSEdPropertiesCmd, OSEdQuitCmd, OSEdRemoveModuleCmd, OSEdRemoveOperationCmd, OSEdSimulateCmd, OSEdUserManualCmd, ClearDisassemblyHighlightCmd, HighlightExecPercentageCmd, HighlightTopExecCountsCmd, ProximAboutCmd, ProximCDCmd, ProximClearConsoleCmd, ProximExecuteFileCmd, ProximFindCmd, ProximKillCmd, ProximNewPortWindowCmd, ProximNewRegisterWindowCmd, ProximNextICmd, ProximOpenMachineCmd, ProximOpenProgramCmd, ProximOptionsCmd, ProximQuitCmd, ProximResumeCmd, ProximRunCmd, ProximSimulatorSettingsCmd, ProximStepICmd, AddBusEntryCmd, AddCostFunctionPluginCmd, AddFUArchFromADFCmd, AddFUEntryCmd, AddFUImplementationCmd, AddOperationImplementationCmd, AddOperationImplementationResourceCmd, AddRFArchitectureCmd, AddRFEntryCmd, AddRFImplementationCmd, AddSocketEntryCmd, CreateHDBCmd, AddFUArchFromADFCmd, HDBEditorAboutCmd, HDBEditorDeleteCmd, HDBEditorModifyCmd, HDBEditorQuitCmd, OpenHDBCmd, SetCostFunctionPluginCmd, SetFUArchitectureCmd, SetRFArchitectureCmd, AboutCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, CopyComponentCmd, CutComponentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditorCommand, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PasteComponentCmd, PrintCmd, PrintPreviewCmd, ProDeExportCmd, QuitCmd, RedoCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, SelectCmd, ToggleUnitDetailsCmd, UndoCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Referenced by ProximMainFrame::onClose(), MainFrame::onCommandEvent(), HDBEditorMainFrame::onUpdateUI(), MainFrame::onUpdateUI(), ProximMainFrame::updateCommand(), DropDownMenu::updateMenu(), and OSEdMainFrame::updateMenuBar().
name()
std::string GUICommand::name () const
Returns name of the command.
Returns
Long name of the command.
Definition at line 99 of file GUICommand.cc.
                       {
    return name_;
}
References name_.
Referenced by OptionsDialog::readCommands().
parentWindow()
wxWindow * GUICommand::parentWindow () const
Returns parent window of the command.
Returns
Parent window of the command.
Definition at line 75 of file GUICommand.cc.
{
    return parent_;
}
References parent_.
Referenced by UserManualCmd::askFromUser(), HDBEditorDeleteCmd::confirmDeletion(), OSEdAboutCmd::Do(), OSEdAddModuleCmd::Do(), OSEdAddOperationCmd::Do(), OSEdBuildAllCmd::Do(), OSEdBuildCmd::Do(), OSEdMemoryCmd::Do(), OSEdModifyBehaviorCmd::Do(), OSEdOptionsCmd::Do(), OSEdPropertiesCmd::Do(), OSEdRemoveModuleCmd::Do(), OSEdRemoveOperationCmd::Do(), OSEdSimulateCmd::Do(), ProximAboutCmd::Do(), ProximCDCmd::Do(), ProximExecuteFileCmd::Do(), ProximFindCmd::Do(), ProximKillCmd::Do(), ProximOpenMachineCmd::Do(), ProximOpenProgramCmd::Do(), ProximOptionsCmd::Do(), ProximQuitCmd::Do(), ProximSimulatorSettingsCmd::Do(), AddCostFunctionPluginCmd::Do(), AddFUArchFromADFCmd::Do(), AddFUImplementationCmd::Do(), AddRFArchitectureCmd::Do(), AddRFImplementationCmd::Do(), CreateHDBCmd::Do(), HDBEditorAboutCmd::Do(), HDBEditorDeleteCmd::Do(), HDBEditorModifyCmd::Do(), OpenHDBCmd::Do(), SetCostFunctionPluginCmd::Do(), SetFUArchitectureCmd::Do(), SetRFArchitectureCmd::Do(), AboutCmd::Do(), AddASCmd::Do(), AddBridgeCmd::Do(), AddBusCmd::Do(), AddFUCmd::Do(), AddFUFromHDBCmd::Do(), AddGCUCmd::Do(), AddIUCmd::Do(), AddIUFromHDBCmd::Do(), AddRFCmd::Do(), AddRFFromHDBCmd::Do(), AddSocketCmd::Do(), CallExplorerPluginCmd::Do(), CopyComponentCmd::Do(), CutComponentCmd::Do(), DeleteComponentCmd::Do(), EditAddressSpacesCmd::Do(), EditBusOrderCmd::Do(), EditImmediateSlotsCmd::Do(), EditMachineCmd::Do(), EditOptionsCmd::Do(), EditOTAFormatsCmd::Do(), EditTemplatesCmd::Do(), ImplementMachineCmd::Do(), ModifyComponentCmd::Do(), PasteComponentCmd::Do(), PrintCmd::Do(), PrintPreviewCmd::Do(), ProDeExportCmd::Do(), QuitCmd::Do(), SaveOptionsCmd::Do(), and VerifyMachineCmd::Do().
setParentWindow()
void GUICommand::setParentWindow (wxWindow * parent)
Sets the parent window of the command.
Window will be used as parent for the dialogs created by this command.
Parameters
parent Parent window for the command dialogs.
Definition at line 64 of file GUICommand.cc.
{
    parent_ = parent;
}
References parent_.
Referenced by ProximMainFrame::onClose(), OSEdMainFrame::onCommandEvent(), ProximMainFrame::onCommandEvent(), HDBEditorMainFrame::onCommandEvent(), MainFrame::onCommandEvent(), OSEdTreeView::onItemClicked(), and SelectTool::onMouseEvent().
shortName()
std::string GUICommand::shortName () const virtual
Returns short version of the command name.
Base class implementation returns the command normal name.
Returns
Short version of the command name.
Reimplemented in UserManualCmd, ProximOpenMachineCmd, ProximOpenProgramCmd, AddASCmd, AddBridgeCmd, AddBusCmd, AddFUCmd, AddFUFromHDBCmd, AddGCUCmd, AddIUCmd, AddIUFromHDBCmd, AddRFCmd, AddRFFromHDBCmd, AddSocketCmd, BlocksConnectICCmd, CallExplorerPluginCmd, CloseDocumentCmd, DeleteComponentCmd, EditAddressSpacesCmd, EditBusOrderCmd, EditConnectionsCmd, EditImmediateSlotsCmd, EditMachineCmd, EditOptionsCmd, EditOTAFormatsCmd, EditTemplatesCmd, FitHeightCmd, FitWidthCmd, FitWindowCmd, FullyConnectBussesCmd, ImplementMachineCmd, ModifyComponentCmd, NewDocumentCmd, OpenDocumentCmd, PrintPreviewCmd, SaveDocumentAsCmd, SaveDocumentCmd, SaveOptionsCmd, ToggleUnitDetailsCmd, VerifyMachineCmd, VLIWConnectICCmd, ZoomInCmd, and ZoomOutCmd.
Definition at line 88 of file GUICommand.cc.
{
    return name_;
}
References name_.
Member Data Documentation
name_
std::string GUICommand::name_ private
Name of the command.
Definition at line 93 of file GUICommand.hh.
Referenced by name(), and shortName().
parent_
wxWindow* GUICommand::parent_ private
Parent window of the command.
Definition at line 91 of file GUICommand.hh.
Referenced by parentWindow(), and setParentWindow().
The documentation for this class was generated from the following files:
GUICommand.hh
GUICommand.cc