OpenASIP: StopPoint Class Reference
StopPoint Class Reference abstract
#include <StopPoint.hh>
Public Member Functions
StopPoint ()
virtual ~StopPoint ()
virtual void setEnabled (bool flag)
virtual bool isEnabled () const
virtual void setDisabledAfterTriggered (bool flag)
virtual bool isDisabledAfterTriggered () const
virtual void setDeletedAfterTriggered (bool flag)
virtual bool isDeletedAfterTriggered () const
virtual void setCondition (const ConditionScript &condition)
virtual void removeCondition ()
virtual const ConditionScript & condition () const
virtual bool isConditional () const
virtual void setIgnoreCount (unsigned int count)
virtual unsigned int ignoreCount () const
virtual bool isConditionOK ()
virtual bool isTriggered () const =0
virtual std::string description () const =0
virtual StopPoint * copy () const =0
virtual void decreaseIgnoreCount ()
Protected Attributes
bool enabled_
Tells whether the breakpoint is enabled or disabled.
bool disabledAfterTriggered_
Tells if the breakpoint is disabled after it is triggered the next time.
bool deletedAfterTriggered_
Tells if the breakpoint is deleted after it is triggered the next time.
bool conditional_
Tells whether the breakpoint is conditional or not.
ConditionScript * condition_
The condition which is used to determine whether the breakpoint should be fired or not.
unsigned int ignoreCount_
The number of times the condition is to be ignored before enabling the breakpoint.
Detailed Description
Represents a stop point in simulation.
StopPointManager uses this class to store information of each stop point of the simulation phase. StopPoint is a parent class for different types of user-set simulation stop conditions (currently breakpoints and watches).
Each StopPoint listens to a simulation event (usually PC advance) and evaluates its stop condition.
Definition at line 53 of file StopPoint.hh.
Constructor & Destructor Documentation
StopPoint()
StopPoint::StopPoint ()
Constructor.
Definition at line 43 of file StopPoint.cc.
                     :
    enabled_(false), disabledAfterTriggered_(false),
    deletedAfterTriggered_(false), conditional_(false), condition_(NULL),
    ignoreCount_(0) {
}
~StopPoint()
StopPoint::~StopPoint () virtual
Destructor.
Definition at line 52 of file StopPoint.cc.
                      {
    delete condition_;
    condition_ = NULL;
}
References condition_.
Member Function Documentation
condition()
const ConditionScript & StopPoint::condition () const virtual
Returns the condition of the stop point.
If breakpoint is unconditional, an empty ConditionScript is returned.
Returns
The condition of the stop point firing.
Definition at line 156 of file StopPoint.cc.
{
    static ConditionScript emptyCondition(NULL, "");
    if (conditional_) {
        return *condition_;
    } else {
        return emptyCondition;
    }
}
References condition_, and conditional_.
Referenced by setCondition(), BreakpointPropertiesDialog::TransferDataToWindow(), and WatchPropertiesDialog::TransferDataToWindow().
copy()
virtual StopPoint * StopPoint::copy () const pure virtual
Implemented in Breakpoint, and Watch.
Referenced by StopPointManager::add().
decreaseIgnoreCount()
void StopPoint::decreaseIgnoreCount () virtual
Decreases the ignore count.
Definition at line 201 of file StopPoint.cc.
{
    if (ignoreCount() > 0) {
        setIgnoreCount(ignoreCount() - 1);
    }
}
References ignoreCount(), and setIgnoreCount().
Referenced by StopPointManager::handleEvent().
description()
std::string StopPoint::description () const pure virtual
Prints the description string of the stop point.
Each subclass overrides this method to construct a descripting string of itself.
Implemented in Breakpoint, and Watch.
Definition at line 239 of file StopPoint.cc.
{
    std::string description = "";
    if (!enabled_)
        description += "is disabled";
    if (disabledAfterTriggered_) {
        if (description != "")
            description += ", ";
        description = "will be disabled after triggered";
    }
    if (deletedAfterTriggered_) {
        if (description != "")
            description += ", ";
        description += "will be deleted after triggered";
    }
    if (ignoreCount_) {
        if (description != "")
            description += ", ";
        description += "will be ignored " +
            Conversion::toString(ignoreCount_) + " time(s)";
    }
    if (conditional_) {
        if (description != "")
            description += ", ";
        description += "has condition '" + condition_->script().at(0) + "'";
    }
    if (description != "")
        description += " ";
    return description;
}
References condition_, conditional_, deletedAfterTriggered_, description(), disabledAfterTriggered_, enabled_, ignoreCount_, Script::script(), and Conversion::toString().
Referenced by Breakpoint::description(), Watch::description(), description(), and SimControlLanguageCommand::printBreakpointInfo().
ignoreCount()
unsigned int StopPoint::ignoreCount () const virtual
Tells the current ignore count, i.e. the number of times the stop point condition is ignored before being fired.
Returns
The ignore count.
Definition at line 193 of file StopPoint.cc.
{
    return ignoreCount_;
}
References ignoreCount_.
Referenced by decreaseIgnoreCount(), StopPointManager::handleEvent(), BreakpointPropertiesDialog::TransferDataToWindow(), and WatchPropertiesDialog::TransferDataToWindow().
isConditional()
bool StopPoint::isConditional () const virtual
Tells whether the stop point is conditional or not.
Returns
'True' if the stop point is conditional, 'false' if it is not.
Definition at line 173 of file StopPoint.cc.
{
    return conditional_;
}
References conditional_.
Referenced by BreakpointPropertiesDialog::TransferDataToWindow(), and WatchPropertiesDialog::TransferDataToWindow().
isConditionOK()
bool StopPoint::isConditionOK () virtual
Tells wheter the condition of the stop point evalutes to true.
If the stop point is not conditional, returns always true.
Returns
'True' if condition is OK, 'false' otherwise.
Definition at line 215 of file StopPoint.cc.
{
    if (conditional_) {
        assert(condition_ != NULL);
        try {
            return condition_->conditionOk();
        } catch (const Exception& e) {
            Application::logStream()
                << "Condition script threw exception: " << e.errorMessage()
                << std::endl;
            return false;
        }
    } else {
        return true;
    }
}
References assert, condition_, conditional_, ConditionScript::conditionOk(), Exception::errorMessage(), and Application::logStream().
Referenced by StopPointManager::handleEvent().
isDeletedAfterTriggered()
bool StopPoint::isDeletedAfterTriggered () const virtual
Tells whether the stop point is deleted after it is triggered (fired) the next time.
Returns
'True' if the stop point is deleted after it is triggered, 'false' if it is not.
Definition at line 119 of file StopPoint.cc.
{
    return deletedAfterTriggered_;
}
References deletedAfterTriggered_.
Referenced by StopPointManager::handleEvent().
isDisabledAfterTriggered()
bool StopPoint::isDisabledAfterTriggered () const virtual
Tells if the stop point is disabled after it is triggered (fired) the next time.
Returns
'True' if the stop oint is disabled after it is triggered, 'false' otherwise.
Definition at line 97 of file StopPoint.cc.
{
    return disabledAfterTriggered_;
}
References disabledAfterTriggered_.
Referenced by StopPointManager::handleEvent().
isEnabled()
bool StopPoint::isEnabled () const virtual
Tells wheter the stop point is enabled or not.
Returns
'True' if the breakpoint is enabled, 'false' if it is disabled.
Definition at line 73 of file StopPoint.cc.
{
    return enabled_;
}
References enabled_.
Referenced by StopPointManager::handleEvent(), ProximDisassemblyWindow::onRightClick(), and ProximBreakpointWindow::refreshStopPoints().
isTriggered()
virtual bool StopPoint::isTriggered () const pure virtual
Implemented in Breakpoint, and Watch.
Referenced by StopPointManager::handleEvent().
removeCondition()
void StopPoint::removeCondition () virtual
Remove the condition of the StopPoint.
The condition is used to determine if the stop point should be fired.
Definition at line 142 of file StopPoint.cc.
{
    conditional_ = false;
    delete condition_;
    condition_ = NULL;
}
References condition_, and conditional_.
Referenced by Breakpoint::copy(), Watch::copy(), SimControlLanguageCommand::parseBreakpoint(), and StopPointManager::removeCondition().
setCondition()
void StopPoint::setCondition (const ConditionScript & condition) virtual
Sets the condition of the StopPoint.
The condition is used to determine if the stop point should be fired.
Parameters
condition The condition to be used as stop point's condition.
Definition at line 131 of file StopPoint.cc.
{
    conditional_ = true;
    condition_ = condition.copy();
}
References condition(), condition_, conditional_, and ConditionScript::copy().
Referenced by Breakpoint::copy(), Watch::copy(), SimControlLanguageCommand::parseBreakpoint(), and StopPointManager::setCondition().
setDeletedAfterTriggered()
void StopPoint::setDeletedAfterTriggered (bool flag) virtual
Makes the stop point to be deleted after it is triggered the next time.
Parameters
flag The new value for this property.
Definition at line 107 of file StopPoint.cc.
{
    deletedAfterTriggered_ = flag;
}
References deletedAfterTriggered_.
Referenced by Breakpoint::copy(), Watch::copy(), StopPointManager::enableOnceAndDelete(), and TBPCommand::execute().
setDisabledAfterTriggered()
void StopPoint::setDisabledAfterTriggered (bool flag) virtual
Sets the stop point to be disabled after it is triggered the next time.
Parameters
flag The new value for this property.
Definition at line 85 of file StopPoint.cc.
{
    disabledAfterTriggered_ = flag;
}
References disabledAfterTriggered_.
Referenced by Breakpoint::copy(), Watch::copy(), and StopPointManager::enableOnceAndDisable().
setEnabled()
void StopPoint::setEnabled (bool flag) virtual
Sets the enabled status of the breakpoint.
Parameters
flag The status.
Definition at line 63 of file StopPoint.cc.
{
    enabled_ = flag;
}
References enabled_.
Referenced by StopPointManager::add(), Breakpoint::copy(), Watch::copy(), StopPointManager::disable(), StopPointManager::enable(), StopPointManager::enableOnceAndDelete(), StopPointManager::enableOnceAndDisable(), and StopPointManager::handleEvent().
setIgnoreCount()
void StopPoint::setIgnoreCount (unsigned int count) virtual
Sets the number of times the condition for firing the stop point is to be disabled before enabling it.
Definition at line 182 of file StopPoint.cc.
{
    ignoreCount_ = count;
}
References ignoreCount_.
Referenced by Breakpoint::copy(), Watch::copy(), decreaseIgnoreCount(), and StopPointManager::setIgnore().
Member Data Documentation
condition_
ConditionScript* StopPoint::condition_ protected
The condition which is used to determine whether the breakpoint should be fired or not.
Definition at line 94 of file StopPoint.hh.
Referenced by condition(), Breakpoint::copy(), Watch::copy(), description(), isConditionOK(), removeCondition(), setCondition(), and ~StopPoint().
conditional_
bool StopPoint::conditional_ protected
Tells whether the breakpoint is conditional or not.
Definition at line 91 of file StopPoint.hh.
Referenced by condition(), Breakpoint::copy(), Watch::copy(), description(), isConditional(), isConditionOK(), removeCondition(), and setCondition().
deletedAfterTriggered_
bool StopPoint::deletedAfterTriggered_ protected
Tells if the breakpoint is deleted after it is triggered the next time.
Definition at line 89 of file StopPoint.hh.
Referenced by Breakpoint::copy(), Watch::copy(), description(), isDeletedAfterTriggered(), and setDeletedAfterTriggered().
disabledAfterTriggered_
bool StopPoint::disabledAfterTriggered_ protected
Tells if the breakpoint is disabled after it is triggered the next time.
Definition at line 87 of file StopPoint.hh.
Referenced by Breakpoint::copy(), Watch::copy(), description(), isDisabledAfterTriggered(), and setDisabledAfterTriggered().
enabled_
bool StopPoint::enabled_ protected
Tells whether the breakpoint is enabled or disabled.
Definition at line 84 of file StopPoint.hh.
Referenced by Breakpoint::copy(), Watch::copy(), description(), isEnabled(), and setEnabled().
ignoreCount_
unsigned int StopPoint::ignoreCount_ protected
The number of times the condition is to be ignored before enabling the breakpoint.
Definition at line 97 of file StopPoint.hh.
Referenced by Breakpoint::copy(), Watch::copy(), description(), ignoreCount(), and setIgnoreCount().
The documentation for this class was generated from the following files:
StopPoint.hh
StopPoint.cc