OpenASIP: ProximBreakpointWindow Class Reference
ProximBreakpointWindow Class Reference
#include <ProximBreakpointWindow.hh>
Public Member Functions
ProximBreakpointWindow (ProximMainFrame *parent, wxWindowID id)
virtual ~ProximBreakpointWindow ()
virtual void reset ()
Private Types
enum {
ID_NOTEBOOK = 10000 , ID_HELP , ID_CLOSE , ID_LINE ,
ID_LOOKUP_BREAKPOINT , ID_BREAKPOINT_PROPERTIES , ID_DELETE_BREAKPOINT , ID_ADD_BREAKPOINT ,
ID_BREAKPOINT_ENABLED , ID_WATCH_PROPERTIES , ID_DELETE_WATCH , ID_ADD_WATCH ,
ID_WATCH_ENABLED , ID_BREAKPOINT_LIST , ID_WATCH_LIST
}
Widget IDs.
Private Member Functions
wxSizer * createContents (wxWindow *parent, bool call_fit, bool set_sizer)
wxSizer * createBreakpointTab (wxWindow *parent, bool call_fit=true, bool set_sizer=true)
wxSizer * createWatchTab (wxWindow *parent, bool call_fit=true, bool set_sizer=true)
void refreshStopPoints ()
void onClose (wxCommandEvent &event)
void onBreakpointsModified (SimulatorEvent &event)
void onDeleteBreakpoint (wxCommandEvent &event)
void onDeleteWatch (wxCommandEvent &event)
void onBreakpointLookup (wxCommandEvent &event)
void onBreakpointProperties (wxCommandEvent &event)
void onBreakpointSelection (wxListEvent &event)
void onAddBreakpoint (wxCommandEvent &event)
void onAddWatch (wxCommandEvent &event)
void onWatchProperties (wxCommandEvent &event)
Private Attributes
wxListCtrl * breakpointList_
List widget for breakpoints.
wxListCtrl * watchList_
List widget for watches.
std::map< unsigned, unsigned > bpListItemHandle_
Map for translating breakpoint list item numbers to stop point handles.
std::map< unsigned, unsigned > watchListItemHandle_
Map for translating watch list item numbers to stop point handles.
Additional Inherited Members
Protected Member Functions inherited from ProximSimulatorWindow
ProximSimulatorWindow (ProximMainFrame *mainFrame, wxWindowID id=-1, wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
virtual ~ProximSimulatorWindow ()
Detailed Description
Proxim window for managing simulation breakpoints and watches.
Definition at line 47 of file ProximBreakpointWindow.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Widget IDs.
Enumerator
ID_NOTEBOOK
ID_HELP
ID_CLOSE
ID_LINE
ID_LOOKUP_BREAKPOINT
ID_BREAKPOINT_PROPERTIES
ID_DELETE_BREAKPOINT
ID_ADD_BREAKPOINT
ID_BREAKPOINT_ENABLED
ID_WATCH_PROPERTIES
ID_DELETE_WATCH
ID_ADD_WATCH
ID_WATCH_ENABLED
ID_BREAKPOINT_LIST
ID_WATCH_LIST
Definition at line 83 of file ProximBreakpointWindow.hh.
         {
        ID_NOTEBOOK = 10000,
        ID_HELP,
        ID_CLOSE,
        ID_LINE,
        ID_LOOKUP_BREAKPOINT,
        ID_BREAKPOINT_PROPERTIES,
        ID_DELETE_BREAKPOINT,
        ID_ADD_BREAKPOINT,
        ID_BREAKPOINT_ENABLED,
        ID_WATCH_PROPERTIES,
        ID_DELETE_WATCH,
        ID_ADD_WATCH,
        ID_WATCH_ENABLED,
        ID_BREAKPOINT_LIST,
        ID_WATCH_LIST
    };
Constructor & Destructor Documentation
ProximBreakpointWindow()
ProximBreakpointWindow::ProximBreakpointWindow (ProximMainFrame * parent, wxWindowID id)
The Constructor.
Parameters
parent Parent window of the frame.
id Window ID.
Definition at line 80 of file ProximBreakpointWindow.cc.
                                           :
    ProximSimulatorWindow(parent, id, wxDefaultPosition, wxDefaultSize, 0),
    breakpointList_(NULL),
    watchList_(NULL) {
    createContents(this, true, true);
    breakpointList_->InsertColumn(0, _T("Handle"), wxLIST_FORMAT_LEFT, 100);
    breakpointList_->InsertColumn(1, _T("Enabled"), wxLIST_FORMAT_CENTER, 80);
    breakpointList_->InsertColumn(2, _T("Address"), wxLIST_FORMAT_LEFT, 300);
    watchList_->InsertColumn(0, _T("Handle"), wxLIST_FORMAT_LEFT, 100);
    watchList_->InsertColumn(1, _T("Enabled"), wxLIST_FORMAT_CENTER, 80);
    watchList_->InsertColumn(2, _T("Expression"), wxLIST_FORMAT_LEFT, 300);
   SimulatorFrontend* simulation = ProximToolbox::frontend();
    if (simulation->isSimulationInitialized() ||
        simulation->isSimulationRunning() ||
        simulation->isSimulationStopped() ||
        simulation->hasSimulationEnded()) {
        refreshStopPoints();
    }
    // Disable conditional buttons initially.
    FindWindow(ID_DELETE_BREAKPOINT)->Disable();
    FindWindow(ID_LOOKUP_BREAKPOINT)->Disable();
    FindWindow(ID_BREAKPOINT_PROPERTIES)->Disable();
    FindWindow(ID_DELETE_WATCH)->Disable();
    FindWindow(ID_BREAKPOINT_ENABLED)->Disable();
    FindWindow(ID_WATCH_ENABLED)->Disable();
    FindWindow(ID_WATCH_PROPERTIES)->Disable();
}
References ProximToolbox::frontend(), SimulatorFrontend::hasSimulationEnded(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationRunning(), and SimulatorFrontend::isSimulationStopped().
~ProximBreakpointWindow()
ProximBreakpointWindow::~ProximBreakpointWindow () virtual
The Destructor.
Definition at line 119 of file ProximBreakpointWindow.cc.
{
}
Member Function Documentation
createBreakpointTab()
wxSizer * ProximBreakpointWindow::createBreakpointTab (wxWindow * parent, bool call_fit = true, bool set_sizer = true) private
Creates the breakpoint tab.
Definition at line 483 of file ProximBreakpointWindow.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );
    wxButton *item3 = new wxButton( parent, ID_BREAKPOINT_PROPERTIES, wxT("Properties..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_LOOKUP_BREAKPOINT, wxT("Lookup"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item5 = new wxButton( parent, ID_DELETE_BREAKPOINT, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    wxCheckBox *item6 = new wxCheckBox( parent, ID_BREAKPOINT_ENABLED, wxT("Enabled"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxALL, 5 );
    breakpointList_ = new wxListCtrl( parent, ID_BREAKPOINT_LIST, wxDefaultPosition, wxSize(400,300), wxLC_REPORT|wxSUNKEN_BORDER );
    item1->Add( breakpointList_, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item8 = new wxButton( parent, ID_ADD_BREAKPOINT, wxT("Add breakpoint..."), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item8, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References breakpointList_, ID_ADD_BREAKPOINT, ID_BREAKPOINT_ENABLED, ID_BREAKPOINT_LIST, ID_BREAKPOINT_PROPERTIES, ID_DELETE_BREAKPOINT, and ID_LOOKUP_BREAKPOINT.
Referenced by createContents().
createContents()
wxSizer * ProximBreakpointWindow::createContents (wxWindow * parent, bool call_fit, bool set_sizer) private
Creates the window contents.
Definition at line 434 of file ProximBreakpointWindow.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxNotebook *item2 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxSize(600,450), 0 );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item1 = new wxNotebookSizer( item2 );
#else
    wxWindow *item1 = item2;
#endif
    wxPanel *item3 = new wxPanel( item2, -1 );
    createBreakpointTab( item3, FALSE );
    item2->AddPage( item3, wxT("Breakpoints") );
    wxPanel *item4 = new wxPanel( item2, -1 );
    createWatchTab( item4, FALSE );
    item2->AddPage( item4, wxT("Watches") );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxStaticLine *item5 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL );
    item0->Add( item5, 0, wxGROW|wxALL, 5 );
    wxGridSizer *item6 = new wxGridSizer( 2, 0, 0 );
    wxButton *item7 = new wxButton( parent, ID_HELP, wxT("&Help"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxALL, 5 );
    wxButton *item8 = new wxButton( parent, ID_CLOSE, wxT("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item8, 0, wxALIGN_RIGHT|wxALL, 5 );
    item0->Add( item6, 0, wxGROW|wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References createBreakpointTab(), createWatchTab(), FALSE, ID_CLOSE, ID_HELP, ID_LINE, and ID_NOTEBOOK.
createWatchTab()
wxSizer * ProximBreakpointWindow::createWatchTab (wxWindow * parent, bool call_fit = true, bool set_sizer = true) private
Creates the watches tab.
Definition at line 528 of file ProximBreakpointWindow.cc.
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );
    wxButton *item3 = new wxButton( parent, ID_WATCH_PROPERTIES, wxT("Properties..."), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item4 = new wxButton( parent, ID_DELETE_WATCH, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );
    wxCheckBox *item5 = new wxCheckBox( parent, ID_WATCH_ENABLED, wxT("Enabled"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );
    item1->Add( item2, 0, wxALL, 5 );
    watchList_ = new wxListCtrl( parent, ID_WATCH_LIST, wxDefaultPosition, wxSize(400,300), wxLC_REPORT|wxSUNKEN_BORDER );
    item1->Add( watchList_, 0, wxALIGN_CENTER|wxALL, 5 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );
    wxButton *item7 = new wxButton( parent, ID_ADD_WATCH, wxT("Add watch..."), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item7, 0, wxALL, 5 );
    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    return item0;
}
References ID_ADD_WATCH, ID_DELETE_WATCH, ID_WATCH_ENABLED, ID_WATCH_LIST, ID_WATCH_PROPERTIES, and watchList_.
Referenced by createContents().
onAddBreakpoint()
void ProximBreakpointWindow::onAddBreakpoint (wxCommandEvent & event) private
Opens a dialog for adding a new breakpoint.
Definition at line 388 of file ProximBreakpointWindow.cc.
{
    SimulatorFrontend* simulation = ProximToolbox::frontend();
    if (simulation->isSimulationInitialized() ||
        simulation->isSimulationRunning() ||
        simulation->isSimulationStopped()) {
        AddBreakpointDialog dialog(this, -1);
        dialog.ShowModal();
    } else {
        wxString message = _T("Simulation not initialized.");
        ErrorDialog error(this, message);
        error.ShowModal();
    }
}
References ProximToolbox::frontend(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationRunning(), and SimulatorFrontend::isSimulationStopped().
onAddWatch()
void ProximBreakpointWindow::onAddWatch (wxCommandEvent & event) private
Opens a dialog for adding a new watch.
Definition at line 409 of file ProximBreakpointWindow.cc.
{
    SimulatorFrontend* simulation = ProximToolbox::frontend();
    if (simulation->isSimulationInitialized() ||
        simulation->isSimulationRunning() ||
        simulation->isSimulationStopped()) {
        AddWatchDialog dialog(this, -1);
        if (dialog.ShowModal() == wxID_OK) {
            refreshStopPoints();
        }
    } else {
        wxString message = _T("Simulation not initialized.");
        ErrorDialog error(this, message);
        error.ShowModal();
    }
}
References ProximToolbox::frontend(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationRunning(), SimulatorFrontend::isSimulationStopped(), and refreshStopPoints().
onBreakpointLookup()
void ProximBreakpointWindow::onBreakpointLookup (wxCommandEvent & event) private
Shows the selected breakpoint location in the program disassembly window.
Definition at line 365 of file ProximBreakpointWindow.cc.
{
    long item = breakpointList_->GetNextItem(
        -1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return;
    }
    StopPointManager& manager =
        wxGetApp().simulation()->frontend()->stopPointManager();
    int handle = bpListItemHandle_[item];
    const Breakpoint& breakpoint = dynamic_cast<const Breakpoint&>(
        manager.stopPointWithHandleConst(handle));
    unsigned address = breakpoint.address();
    ProximToolbox::disassemblyWindow()->showAddress(address);
}
References Breakpoint::address(), bpListItemHandle_, breakpointList_, ProximToolbox::disassemblyWindow(), ProximDisassemblyWindow::showAddress(), and StopPointManager::stopPointWithHandleConst().
onBreakpointProperties()
void ProximBreakpointWindow::onBreakpointProperties (wxCommandEvent & event) private
Opens dialog displaying properties of the selected breakpoint when the Properties-button is pressed.
Definition at line 138 of file ProximBreakpointWindow.cc.
{
    long item = breakpointList_->GetNextItem(
        -1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return;
    }
    StopPointManager& manager =
        wxGetApp().simulation()->frontend()->stopPointManager();
    int handle = bpListItemHandle_[item];
    BreakpointPropertiesDialog dialog(this, manager, handle);
    dialog.ShowModal();
    refreshStopPoints();
}
References bpListItemHandle_, breakpointList_, and refreshStopPoints().
onBreakpointSelection()
void ProximBreakpointWindow::onBreakpointSelection (wxListEvent & event) private
Enables and disables delete buttons for stop points according to stop point list selections.
Definition at line 305 of file ProximBreakpointWindow.cc.
{
    if (breakpointList_->GetSelectedItemCount() > 0) {
        FindWindow(ID_DELETE_BREAKPOINT)->Enable();
        FindWindow(ID_LOOKUP_BREAKPOINT)->Enable();
        FindWindow(ID_BREAKPOINT_PROPERTIES)->Enable();
    } else {
        FindWindow(ID_DELETE_BREAKPOINT)->Disable();
        FindWindow(ID_LOOKUP_BREAKPOINT)->Disable();
        FindWindow(ID_BREAKPOINT_PROPERTIES)->Disable();
    }
    if (watchList_->GetSelectedItemCount() > 0) {
        FindWindow(ID_DELETE_WATCH)->Enable();
        FindWindow(ID_WATCH_PROPERTIES)->Enable();
    } else {
        FindWindow(ID_DELETE_WATCH)->Disable();
        FindWindow(ID_WATCH_PROPERTIES)->Disable();
    }
}
References breakpointList_, ID_BREAKPOINT_PROPERTIES, ID_DELETE_BREAKPOINT, ID_DELETE_WATCH, ID_LOOKUP_BREAKPOINT, ID_WATCH_PROPERTIES, and watchList_.
Referenced by refreshStopPoints().
onBreakpointsModified()
void ProximBreakpointWindow::onBreakpointsModified (SimulatorEvent & event) private
Refreshes the breakpoint list when breakpoints are modified.
Parameters
event Event to handle.
Definition at line 333 of file ProximBreakpointWindow.cc.
{
    refreshStopPoints();
    // Skip event so it's passed to the parent class.
    event.Skip();
}
References refreshStopPoints().
onClose()
void ProximBreakpointWindow::onClose (wxCommandEvent & event) private
Event handler for the close button.
Closes the window.
Definition at line 128 of file ProximBreakpointWindow.cc.
{
    GetParent()->Close();
}
onDeleteBreakpoint()
void ProximBreakpointWindow::onDeleteBreakpoint (wxCommandEvent & event) private
Deletes the breakpoint selected in the breakpoint list.
Definition at line 282 of file ProximBreakpointWindow.cc.
{
    long item = breakpointList_->GetNextItem(
        -1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return;
    }
    StopPointManager& manager =
        wxGetApp().simulation()->frontend()->stopPointManager();
    int handle = bpListItemHandle_[item];
    manager.deleteStopPoint(handle);
    refreshStopPoints();
}
References bpListItemHandle_, breakpointList_, StopPointManager::deleteStopPoint(), and refreshStopPoints().
onDeleteWatch()
void ProximBreakpointWindow::onDeleteWatch (wxCommandEvent & event) private
Deletes the watch selected in the watch list.
Definition at line 344 of file ProximBreakpointWindow.cc.
{
    long item = watchList_->GetNextItem(
        -1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return;
    }
    StopPointManager& manager =
        wxGetApp().simulation()->frontend()->stopPointManager();
    int handle = watchListItemHandle_[item];
    manager.deleteStopPoint(handle);
    refreshStopPoints();
}
References StopPointManager::deleteStopPoint(), refreshStopPoints(), watchList_, and watchListItemHandle_.
onWatchProperties()
void ProximBreakpointWindow::onWatchProperties (wxCommandEvent & event) private
Opens dialog displaying properties of the selected watch when the Properties-button is pressed in the watches tab.
Definition at line 171 of file ProximBreakpointWindow.cc.
{
    long item = watchList_->GetNextItem(
        -1, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED);
    if (item == -1) {
        return;
    }
    StopPointManager& manager =
        wxGetApp().simulation()->frontend()->stopPointManager();
    int handle = watchListItemHandle_[item];
    WatchPropertiesDialog dialog(this, -1, manager, handle);
    dialog.ShowModal();
    refreshStopPoints();
}
References refreshStopPoints(), watchList_, and watchListItemHandle_.
refreshStopPoints()
void ProximBreakpointWindow::refreshStopPoints () private
Updates the lists of breakpoints and watches.
Definition at line 195 of file ProximBreakpointWindow.cc.
{
    breakpointList_->DeleteAllItems();
    watchList_->DeleteAllItems();
    // Clear "list item to handle" mapping.
    bpListItemHandle_.clear();
    watchListItemHandle_.clear();
    SimulatorFrontend* frontend = ProximToolbox::frontend();
    if (frontend == NULL ||
        !(frontend->isSimulationInitialized() ||
          frontend->isSimulationRunning() ||
          frontend->isSimulationStopped() ||
          frontend->hasSimulationEnded())) {
        // Simulation not initiailized.
        return;
    }
    StopPointManager& manager = frontend->stopPointManager();
    int bpRow = 0;
    int watchRow = 0;
    // Add all stoppoints to appropriate lists.
    for (unsigned i = 0; i < manager.stopPointCount(); i++) {
        unsigned handle = manager.stopPointHandle(i);
        const StopPoint* stoppoint =
            &manager.stopPointWithHandleConst(handle);
        // Check if the stoppoint is breakpoint.
        const Breakpoint* breakpoint =
            dynamic_cast<const Breakpoint*>(stoppoint);
        if (breakpoint != NULL) {
            // Stoppoint is breakpoint.
            bpListItemHandle_.insert(
                std::pair<unsigned, unsigned>(bpRow, handle));
            breakpointList_->InsertItem(
                bpRow, WxConversion::toWxString(handle));
            if (breakpoint->isEnabled()) {
                breakpointList_->SetItem(bpRow, 1, _T("X"));
            }
            InstructionAddress address = breakpoint->address();
            breakpointList_->SetItem(
                bpRow, 2, WxConversion::toWxString(address));
            bpRow++;
            continue;
        }
        // Check if the stoppoint is watch.
        const Watch* watch = dynamic_cast<const Watch*>(stoppoint);
        if (watch != NULL) {
            // Stoppoint is watch.
            watchListItemHandle_.insert(
                std::pair<unsigned, unsigned>(watchRow, handle));
            watchList_->InsertItem(0, WxConversion::toWxString(handle));
            if (watch->isEnabled()) {
                watchList_->SetItem(bpRow, 1, _T("X"));
            }
            std::string expression = watch->expression().script()[0];
            watchList_->SetItem(0, 2, WxConversion::toWxString(expression));
            watchRow++;
            continue;
        }
    }
    // Update enabled/disabled state of the dialog buttons.
    wxListEvent dummy;
    onBreakpointSelection(dummy);
}
References Breakpoint::address(), bpListItemHandle_, breakpointList_, dummy, Watch::expression(), ProximToolbox::frontend(), SimulatorFrontend::hasSimulationEnded(), StopPoint::isEnabled(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::isSimulationRunning(), SimulatorFrontend::isSimulationStopped(), onBreakpointSelection(), Script::script(), StopPointManager::stopPointCount(), StopPointManager::stopPointHandle(), SimulatorFrontend::stopPointManager(), StopPointManager::stopPointWithHandleConst(), WxConversion::toWxString(), watchList_, and watchListItemHandle_.
Referenced by onAddWatch(), onBreakpointProperties(), onBreakpointsModified(), onDeleteBreakpoint(), onDeleteWatch(), onWatchProperties(), and reset().
reset()
void ProximBreakpointWindow::reset () virtual
Called when the simulator resets program, machine or memory model.
Reimplemented from ProximSimulatorWindow.
Definition at line 162 of file ProximBreakpointWindow.cc.
{
    refreshStopPoints();
}
References refreshStopPoints().
Member Data Documentation
bpListItemHandle_
std::map<unsigned, unsigned> ProximBreakpointWindow::bpListItemHandle_ private
Map for translating breakpoint list item numbers to stop point handles.
Definition at line 78 of file ProximBreakpointWindow.hh.
Referenced by onBreakpointLookup(), onBreakpointProperties(), onDeleteBreakpoint(), and refreshStopPoints().
breakpointList_
wxListCtrl* ProximBreakpointWindow::breakpointList_ private
List widget for breakpoints.
Definition at line 73 of file ProximBreakpointWindow.hh.
Referenced by createBreakpointTab(), onBreakpointLookup(), onBreakpointProperties(), onBreakpointSelection(), onDeleteBreakpoint(), and refreshStopPoints().
watchList_
wxListCtrl* ProximBreakpointWindow::watchList_ private
List widget for watches.
Definition at line 75 of file ProximBreakpointWindow.hh.
Referenced by createWatchTab(), onBreakpointSelection(), onDeleteWatch(), onWatchProperties(), and refreshStopPoints().
watchListItemHandle_
std::map<unsigned, unsigned> ProximBreakpointWindow::watchListItemHandle_ private
Map for translating watch list item numbers to stop point handles.
Definition at line 80 of file ProximBreakpointWindow.hh.
Referenced by onDeleteWatch(), onWatchProperties(), and refreshStopPoints().
The documentation for this class was generated from the following files:
ProximBreakpointWindow.hh
ProximBreakpointWindow.cc