OpenASIP: TTAMachine::NullInstructionTemplate Class Reference
TTAMachine::NullInstructionTemplate Class Reference
#include <NullInstructionTemplate.hh>
Public Member Functions
virtual TCEString name () const
virtual void setName (const std::string &name)
virtual void addSlot (const std::string &slotName, int width, ImmediateUnit &dstUnit)
virtual void removeSlot (const std::string &slotName)
virtual void removeSlots (const ImmediateUnit &dstUnit)
virtual int slotCount () const
virtual TemplateSlot * slot (int index) const
virtual bool usesSlot (const std::string &slotName) const
virtual bool destinationUsesSlot (const std::string &slotName, const ImmediateUnit &dstUnit) const
virtual int numberOfDestinations () const
virtual bool isOneOfDestinations (const ImmediateUnit &dstUnit) const
virtual ImmediateUnit * destinationOfSlot (const std::string &slotName) const
virtual int numberOfSlots (const ImmediateUnit &dstUnit) const
virtual std::string slotOfDestination (const ImmediateUnit &dstUnit, int index) const
virtual int supportedWidth () const
virtual int supportedWidth (const ImmediateUnit &dstUnit) const
virtual int supportedWidth (const std::string &slotName) const
virtual bool isEmpty () const
virtual void setMachine (Machine &machine)
virtual void unsetMachine ()
virtual Machine * machine () const
virtual void ensureRegistration (const Component &component) const
virtual bool isRegistered () const
virtual ObjectState * saveState () const
virtual void loadState (const ObjectState *state)
Public Member Functions inherited from TTAMachine::InstructionTemplate
InstructionTemplate (const std::string &name, Machine &owner)
InstructionTemplate (const ObjectState *state, Machine &owner)
virtual ~InstructionTemplate ()
TemplateSlot * templateSlot (const std::string &slotName) const
Public Member Functions inherited from TTAMachine::Component
virtual ~Component ()
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Static Public Member Functions
static NullInstructionTemplate & instance ()
Private Member Functions
NullInstructionTemplate ()
virtual ~NullInstructionTemplate ()
Static Private Attributes
static NullInstructionTemplate instance_
The only instance of NullInstructionTemplate.
static Machine machine_
Machine to which the null instruction template is registered.
Additional Inherited Members
Static Public Attributes inherited from TTAMachine::InstructionTemplate
static const std::string OSNAME_INSTRUCTION_TEMPLATE = "i_template"
ObjectState name for instruction template.
Static Public Attributes inherited from TTAMachine::Component
static const std::string OSNAME_COMPONENT = "component"
ObjectState name for component.
static const std::string OSKEY_NAME = "name"
ObjectState attribute key for the name of the component.
Protected Member Functions inherited from TTAMachine::Component
Component (const std::string &name)
Component (const ObjectState *state)
void internalSetMachine (Machine &machine)
void internalUnsetMachine ()
Protected Member Functions inherited from TTAMachine::MachinePart
MachinePart ()
virtual ~MachinePart ()
Detailed Description
A singleton class which represents a null InstructionTemplate.
All the methods abort the program.
Definition at line 45 of file NullInstructionTemplate.hh.
Constructor & Destructor Documentation
NullInstructionTemplate()
TTAMachine::NullInstructionTemplate::NullInstructionTemplate () private
The constructor.
Definition at line 44 of file NullInstructionTemplate.cc.
                                                 :
    InstructionTemplate("NULL", machine_) {
}
~NullInstructionTemplate()
TTAMachine::NullInstructionTemplate::~NullInstructionTemplate () private virtual
The destructor.
Definition at line 52 of file NullInstructionTemplate.cc.
{
}
Member Function Documentation
addSlot()
void TTAMachine::NullInstructionTemplate::addSlot (const std::string & slotName, int width, ImmediateUnit & dstUnit) virtual
Aborts the program with error message.
Exceptions
InstanceNotFound Never thrown.
ComponentAlreadyExists Never thrown.
OutOfRange Never thrown.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 98 of file NullInstructionTemplate.cc.
{
    abortWithError("addSlot()");
}
References abortWithError.
destinationOfSlot()
ImmediateUnit * TTAMachine::NullInstructionTemplate::destinationOfSlot (const std::string & slotName) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 201 of file NullInstructionTemplate.cc.
{
    abortWithError("destinationOfSlot()");
    return NULL;
}
References abortWithError.
destinationUsesSlot()
bool TTAMachine::NullInstructionTemplate::destinationUsesSlot (const std::string & slotName, const ImmediateUnit & dstUnit) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 162 of file NullInstructionTemplate.cc.
{
    abortWithError("destinationUsesSlot()");
    return false;
}
References abortWithError.
ensureRegistration()
void TTAMachine::NullInstructionTemplate::ensureRegistration (const Component & component) const virtual
Aborts the program with error message.
Exceptions
IllegalRegistration Never thrown.
Reimplemented from TTAMachine::Component.
Definition at line 314 of file NullInstructionTemplate.cc.
{
    abortWithError("ensureRegistration()");
}
References abortWithError.
instance()
NullInstructionTemplate & TTAMachine::NullInstructionTemplate::instance () static
Returns the only instance of NullInstructionTemplate.
Returns
The only instance of NullInstructionTemplate.
Definition at line 62 of file NullInstructionTemplate.cc.
{
    return instance_;
}
References instance_.
Referenced by TTAProgram::CodeGenerator::addAnnotatedMoveToProcedure(), ProgrammabilityValidator::addConnectionToProgram(), TTAProgram::Instruction::addImmediate(), TTAProgram::Instruction::addMove(), TTAProgram::CodeGenerator::addMoveToProcedure(), TTAProgram::TPEFProgramFactory::createInstruction(), TTAProgram::CodeGenerator::createSchedYieldProcedure(), POMDisassembler::disassemble(), llvm::LLVMTCEBuilder::emitGlobalXXtructorCalls(), llvm::LLVMTCEBuilder::emitSetjmp(), CallsToJumps::handleControlFlowGraph(), ITemplateBroker::isAlreadyAssigned(), and MoveNode::isAssigned().
isEmpty()
bool TTAMachine::NullInstructionTemplate::isEmpty () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 271 of file NullInstructionTemplate.cc.
{
    abortWithError("isEmpty()");
    return false;
}
References abortWithError.
isOneOfDestinations()
bool TTAMachine::NullInstructionTemplate::isOneOfDestinations (const ImmediateUnit & dstUnit) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 189 of file NullInstructionTemplate.cc.
{
    abortWithError("isOneOfDestinations()");
    return false;
}
References abortWithError.
isRegistered()
bool TTAMachine::NullInstructionTemplate::isRegistered () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 324 of file NullInstructionTemplate.cc.
{
    abortWithError("isRegistered()");
    return false;
}
References abortWithError.
loadState()
void TTAMachine::NullInstructionTemplate::loadState (const ObjectState * state) virtual
Aborts the program with error message.
Exceptions
ObjectStateLoadingException Never thrown.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 347 of file NullInstructionTemplate.cc.
{
    abortWithError("loadState()");
}
References abortWithError.
machine()
Machine * TTAMachine::NullInstructionTemplate::machine () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 302 of file NullInstructionTemplate.cc.
{
    abortWithError("machine()");
    return NULL;
}
References abortWithError.
name()
TCEString TTAMachine::NullInstructionTemplate::name () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::Component.
Definition at line 73 of file NullInstructionTemplate.cc.
{
    abortWithError("name()");
    return "";
}
References abortWithError.
numberOfDestinations()
int TTAMachine::NullInstructionTemplate::numberOfDestinations () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 177 of file NullInstructionTemplate.cc.
{
    abortWithError("numberOfDestinations()");
    return 0;
}
References abortWithError.
numberOfSlots()
int TTAMachine::NullInstructionTemplate::numberOfSlots (const ImmediateUnit & dstUnit) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 212 of file NullInstructionTemplate.cc.
{
    abortWithError("numberOfSlots()");
    return 0;
}
References abortWithError.
removeSlot()
void TTAMachine::NullInstructionTemplate::removeSlot (const std::string & slotName) virtual
Aborts the program with error message.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 106 of file NullInstructionTemplate.cc.
{
    abortWithError("removeSlot()");
}
References abortWithError.
removeSlots()
void TTAMachine::NullInstructionTemplate::removeSlots (const ImmediateUnit & dstUnit) virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 117 of file NullInstructionTemplate.cc.
{
    abortWithError("removeSlots()");
}
References abortWithError.
saveState()
ObjectState * TTAMachine::NullInstructionTemplate::saveState () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 335 of file NullInstructionTemplate.cc.
{
    abortWithError("saveState()");
    return NULL;
}
References abortWithError.
setMachine()
void TTAMachine::NullInstructionTemplate::setMachine (Machine & machine) virtual
Aborts the program with error message.
Exceptions
ComponentAlreadyExists Never thrown.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 283 of file NullInstructionTemplate.cc.
{
    abortWithError("setMachine()");
}
References abortWithError.
setName()
void TTAMachine::NullInstructionTemplate::setName (const std::string & name) virtual
Aborts the program with error message.
Exceptions
ComponentAlreadyExists Never thrown.
InvalidName Never thrown.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 86 of file NullInstructionTemplate.cc.
{
    abortWithError("setName()");
}
References abortWithError.
slot()
TemplateSlot * TTAMachine::NullInstructionTemplate::slot (int index) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 138 of file NullInstructionTemplate.cc.
{
    abortWithError("slot()");
    return NULL;
}
References abortWithError.
slotCount()
int TTAMachine::NullInstructionTemplate::slotCount () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 127 of file NullInstructionTemplate.cc.
{
    abortWithError("slotCount()");
    return -1;
}
References abortWithError.
slotOfDestination()
std::string TTAMachine::NullInstructionTemplate::slotOfDestination (const ImmediateUnit & dstUnit, int index) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 224 of file NullInstructionTemplate.cc.
{
    abortWithError("slotOfDestination()");
    return NULL;
}
References abortWithError.
supportedWidth() [1/3]
int TTAMachine::NullInstructionTemplate::supportedWidth () const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 235 of file NullInstructionTemplate.cc.
{
    abortWithError("supportedWidth()");
    return 0;
}
References abortWithError.
supportedWidth() [2/3]
int TTAMachine::NullInstructionTemplate::supportedWidth (const ImmediateUnit & dstUnit) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 247 of file NullInstructionTemplate.cc.
{
    abortWithError("supportedWidth()");
    return 0;
}
References abortWithError.
supportedWidth() [3/3]
int TTAMachine::NullInstructionTemplate::supportedWidth (const std::string & slotName) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 259 of file NullInstructionTemplate.cc.
{
    abortWithError("supportedWidth()");
    return 0;
}
References abortWithError.
unsetMachine()
void TTAMachine::NullInstructionTemplate::unsetMachine () virtual
Aborts the program with error message.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 291 of file NullInstructionTemplate.cc.
{
    abortWithError("unsetMachine()");
}
References abortWithError.
usesSlot()
bool TTAMachine::NullInstructionTemplate::usesSlot (const std::string & slotName) const virtual
Aborts the program with error message.
Returns
Never returns.
Reimplemented from TTAMachine::InstructionTemplate.
Definition at line 150 of file NullInstructionTemplate.cc.
{
    abortWithError("usesSlot()");
    return false;
}
References abortWithError.
Member Data Documentation
instance_
NullInstructionTemplate TTAMachine::NullInstructionTemplate::instance_ static private
The only instance of NullInstructionTemplate.
Definition at line 93 of file NullInstructionTemplate.hh.
Referenced by instance().
machine_
Machine TTAMachine::NullInstructionTemplate::machine_ static private
Machine to which the null instruction template is registered.
Definition at line 95 of file NullInstructionTemplate.hh.
The documentation for this class was generated from the following files:
NullInstructionTemplate.hh
NullInstructionTemplate.cc