OpenASIP: ConstantTransformer.cc File Reference
ConstantTransformer.cc File Reference
#include "CompilerWarnings.hh"
#include "ConstantTransformer.hh"
#include "MachineInfo.hh"
#include "TCETargetMachine.hh"
#include "OperationPool.hh"
#include "Operation.hh"
#include "Operand.hh"
#include <llvm/CodeGen/MachineFunction.h>
#include <llvm/CodeGen/MachineBasicBlock.h>
#include <llvm/MC/MCInstrInfo.h>
#include <llvm/CodeGen/TargetInstrInfo.h>
#include <llvm/CodeGen/TargetSubtargetInfo.h>
#include <llvm/CodeGen/TargetOpcodes.h>
#include <llvm/CodeGen/MachineInstrBuilder.h>
#include <sstream>
Macros
#define sub "SUB"
Functions
unsigned osalInputIndex (const Operation &operation, const llvm::MachineInstr &instr, unsigned operandId)
Detailed Description
Implementation of ConstantTransformer class.
Author
Pekka Jääskeläinen 2015
Note
reting: red
Definition in file ConstantTransformer.cc.
Macro Definition Documentation
sub
#define sub "SUB"
Definition at line 63 of file ConstantTransformer.cc.
Function Documentation
osalInputIndex()
unsigned osalInputIndex (const Operation & operation, const llvm::MachineInstr & instr, unsigned operandId)
In case the given operandId is an input operand in the MachineInstr, returns the corresponding OSAL operand id (starting from 1), 0 otherwise.
Definition at line 78 of file ConstantTransformer.cc.
{
    const TCETargetMachine& tm =
        dynamic_cast<const TCETargetMachine&>(
            instr.getParent()->getParent()->getTarget());
    TCEString operationName = tm.operationName(instr.getDesc().getOpcode());
    bool hasGuard = operationName[0] == '?' || operationName[0] == '!';
    unsigned osalIndex = 0;
    for (unsigned operandI = 0; operandI < instr.getNumOperands(); ++operandI) {
        const MachineOperand& mo = instr.getOperand(operandI);
        if (hasGuard && operandI == 0) continue;
        // Output or metadata.
        if ((mo.isReg() && (mo.isDef() || mo.isImplicit())) || mo.isMetadata())
            continue;
        ++osalIndex;
        if (operandI == operandId) return osalIndex;
        // LLVM machineinstructions always present the addresses in the
        // base + offset form, thus consume two input operands per one
        // OSAL operand. Skip the offset operand in case the OSAL operation
        // only the takes a single absolute address.
        if (operation.operand(osalIndex).isAddress() &&
            !operation.isBaseOffsetMemOperation()) {
            ++operandI;
        }
    }
    return 0;
}
References Operand::isAddress(), Operation::isBaseOffsetMemOperation(), Operation::operand(), and llvm::TCETargetMachine::operationName().
Referenced by ConstantTransformer::runOnMachineFunction().