OpenASIP: CreateBEM.cc File Reference
CreateBEM.cc File Reference
#include <iostream>
#include <string>
#include "BEMGeneratorCmdLineOptions.hh"
#include "BEMSerializer.hh"
#include "BEMGenerator.hh"
#include "BinaryEncoding.hh"
#include "Machine.hh"
#include "ADFSerializer.hh"
#include "FileSystem.hh"
Functions
static Machine * loadMachine (const std::string &adfFile)
static std::string outputFileName (const std::string &adfFile)
int main (int argc, char *argv[])
Detailed Description
Implements the main function of createbem application which creates a binary encoding map.
Author
Lasse Laasonen 2005 (lasse.laasonen-no.spam-tut.fi)
Note
rating: red
Definition in file CreateBEM.cc.
Function Documentation
loadMachine()
static Machine * loadMachine (const std::string & adfFile) static
Loads the given ADF file and creates a Machine instance from it.
Parameters
adfFile The ADF file.
Returns
The newly created Machine instance.
Exceptions
SerializerException If an error occurs while reading the file.
ObjectStateLoadingException If an error occurs while loading the state of Machine instance.
Definition at line 62 of file CreateBEM.cc.
{
    ADFSerializer serializer;
    serializer.setSourceFile(adfFile);
    return serializer.readMachine();
}
References ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
Referenced by main().
main()
int main (int argc, char * argv[])
The main function.
Definition at line 86 of file CreateBEM.cc.
{
    BEMGeneratorCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& exception) {
        cerr << exception.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    string adfFile = options.adfFile();
    string outputFile = options.outputFile();
    if (adfFile == "") {
        options.printHelp();
        return EXIT_FAILURE;
    }
    Machine* mach = NULL;
    try {
        mach = loadMachine(adfFile);
    } catch (const Exception& e) {
        cerr << "Error while loading machine from adf:" << endl
             << e.fileName() << ", line: " << e.lineNum() << endl
             << e.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    BEMGenerator generator(*mach);
    BinaryEncoding* bem = generator.generate();
    BEMSerializer serializer;
    if (outputFile == "") {
        outputFile = outputFileName(adfFile);
    }
    serializer.setDestinationFile(outputFile);
    serializer.writeBinaryEncoding(*bem);
    delete mach;
    delete bem;
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), Exception::fileName(), BEMGenerator::generate(), Exception::lineNum(), loadMachine(), options, outputFileName(), CmdLineOptions::parse(), MachInfoCmdLineOptions::printHelp(), XMLSerializer::setDestinationFile(), and BEMSerializer::writeBinaryEncoding().
outputFileName()
static std::string outputFileName (const std::string & adfFile) static
Generates the name of the output file from the given ADF file name.
The generated name has same body but .bem suffix.
Parameters
adfFile The name of the ADF file.
Returns
The name of the output file.
Definition at line 77 of file CreateBEM.cc.
{
    string file = FileSystem::fileNameBody(adfFile);
    return file + ".bem";
}
References FileSystem::fileNameBody().
Referenced by main(), and SOPCBuilderFileGenerator::writeProjectFiles().