OpenASIP: CreateHDB.cc File Reference
CreateHDB.cc File Reference
#include "Application.hh"
#include "CreateHDBCmdLineOptions.hh"
#include "HDBManager.hh"
#include "Exception.hh"
#include "FileSystem.hh"
Functions
int main (int argc, char *argv[])
Detailed Description
The command line tool that creates a new HDB.
Author
Pekka Jääskeläinen 2005 (pjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file CreateHDB.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Main function.
Parses the command line and creates a new HDB.
Parameters
argc The command line argument count.
argv The command line arguments (passed to the interpreter).
Returns
The return status.
Definition at line 49 of file CreateHDB.cc.
{
    Application::initialize();
    CreateHDBCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
            return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& i) {
        std::cerr << i.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    if (options.numberOfArguments() != 1) {
        std::cerr << "Illegal number of arguments." << std::endl;
        return EXIT_FAILURE;
    }
    const std::string fileName = options.argument(1);
    if (FileSystem::fileExists(fileName)) {
        std::cerr << "File already exists." << std::endl;
        return EXIT_SUCCESS;
    }
    try {
        HDB::HDBManager::createNew(fileName);
    } catch (const Exception& e) {
        std::cerr << "Error while creating HDB. "
                  << e.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
References CmdLineParser::argument(), HDB::HDBManager::createNew(), Exception::errorMessage(), FileSystem::fileExists(), Application::initialize(), CmdLineParser::numberOfArguments(), options, and CmdLineOptions::parse().