OpenASIP: ExtensionGen.cc File Reference
ExtensionGen.cc File Reference
#include <iostream>
#include <fstream>
#include <set>
#include <assert.h>
#include <boost/format.hpp>
#include "OperationPool.hh"
#include "Operation.hh"
#include "Conversion.hh"
#include "OperationIndex.hh"
#include "Operand.hh"
#include "Machine.hh"
#include "StringTools.hh"
#include "HWOperation.hh"
Functions
std::string operandTypeCString (const Operand &operand)
void generateHeader (std::ostream &stream, const TTAMachine::Machine &machine)
int main (int argc, char *argv[])
Function Documentation
generateHeader()
void generateHeader (std::ostream & stream, const TTAMachine::Machine & machine)
Writes the macros that can be written to the tceoclext.h header file to stdout.
Following macros are produced for all operations found in the given machine (for example, in case of ADDSUB):
#define cl_TCE_ADDSUB #define clADDSUBTCE _TCE_ADDSUB
Thus, it's possible to figure out whether ADDSUB is implemented in the machine using the first define and actually call the ADDSUB with the latter.
Definition at line 86 of file ExtensionGen.cc.
{
    std::set<std::string> opNames;
    const TTAMachine::Machine::FunctionUnitNavigator fuNav =
        machine.functionUnitNavigator();
    for (int i = 0; i < fuNav.count(); i++) {
        const TTAMachine::FunctionUnit* fu = fuNav.item(i);
        for (int o = 0; o < fu->operationCount(); o++) {
            const std::string opName = fu->operation(o)->name();
            opNames.insert(StringTools::stringToUpper(opName));
        }
    }
    stream
        << "// automatically generated by tceoclextgen" << std::endl
        << std::endl;
    for (std::set<std::string>::const_iterator i = opNames.begin();
         i != opNames.end(); ++i) {
        std::string name = (*i);
        stream
            << (boost::format(
                    "#define cl_TCE_%s\n"
                    "#define cl%sTCE _TCE_%s\n\n")
                % name % name % name).str();
    }
}
References TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, TTAMachine::HWOperation::name(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), and StringTools::stringToUpper().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 114 of file ExtensionGen.cc.
{
    if (argc != 2) {
        std::cout << "Usage: tceoclextgen ADF" << std::endl;
        return EXIT_FAILURE;
    }
    try {
        TTAMachine::Machine* machine =
            TTAMachine::Machine::loadFromADF(argv[1]);
        generateHeader(std::cout, *machine);
        delete machine; machine = NULL;
    } catch (const Exception& e) {
        std::cerr << e.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), generateHeader(), TTAMachine::Machine::loadFromADF(), and machine.
operandTypeCString()
std::string operandTypeCString (const Operand & operand)
Generates OpenCL C extension functions and definitions for the (custom) operations in the given ADF.
Author
Pekka Jääskeläinen 2009 (pjaaskel-no.spam-cs.tut.fi)
Note
rating: red Returns a C type string for the given operand type.
Definition at line 53 of file ExtensionGen.cc.
{
    switch (operand.type()) {
    default:
    case Operand::SINT_WORD:
        return "int";
        break;
    case Operand::UINT_WORD:
        return "unsigned";
        break;
    case Operand::FLOAT_WORD:
        return"float";
        break;
    case Operand::DOUBLE_WORD:
        return "double";
        break;
    }
    return "unsigned"; // a good guess ;)
}
References Operand::DOUBLE_WORD, Operand::FLOAT_WORD, Operand::SINT_WORD, Operand::type(), and Operand::UINT_WORD.