OpenASIP: LLVMUtilities.cc File Reference
LLVMUtilities.cc File Reference
#include "LLVMUtilities.hh"
#include "TCEString.hh"
#include "tce_config.h"
#include "CompilerWarnings.hh"
#include <llvm/CodeGen/MachineInstr.h>
#include <llvm/CodeGen/MachineOperand.h>
#include <llvm/IR/DebugLoc.h>
#include <llvm/IR/DebugInfo.h>
Functions
POP_COMPILER_DIAGS std::tuple< std::string, size_t > getSourceLocationInfo (const llvm::MachineInstr &mi)
std::string getSourceLocationString (const llvm::MachineInstr &mi)
AsmOperandMap getInlineAsmOperands (const llvm::MachineInstr &mi)
Detailed Description
Implementations of LLVM utilities.
Author
Henry Linjamäki 2017 (henry.linjamaki-no.spam-tut.fi)
Note
reting: red
Declarations of LLVM utilities.
Author
Henry Linjamäki 2017 (henry.linjamaki-no.spam-tut.fi)
Note
reting: red
Definition in file LLVMUtilities.cc.
Function Documentation
getInlineAsmOperands()
AsmOperandMap getInlineAsmOperands (const llvm::MachineInstr & mi)
Decodes operands of INLINEASM instruction into more manageable struct.
Definition at line 92 of file LLVMUtilities.cc.
{
    using namespace llvm;
    AsmOperandMap result;
    unsigned asmOpdPos = 0;
    unsigned endPos = mi.getNumOperands();
    unsigned i = InlineAsm::MIOp_FirstOperand;
    while (i < endPos) {
        const MachineOperand& mo = mi.getOperand(i);
        if (mo.isMetadata())  {
            i++;
            continue;
        }
        unsigned opdKind = InlineAsm::getKind(mo.getImm());
        unsigned numAsmOpds = InlineAsm::getNumOperandRegisters(mo.getImm());
        unsigned flagOpdBegin = i + 1;
        unsigned flagOpdEnd = flagOpdBegin + numAsmOpds;
        std::vector<const llvm::MachineOperand*> flagOps;
        for (unsigned opdIdx = flagOpdBegin; opdIdx < flagOpdEnd; opdIdx++) {
            flagOps.push_back(&mi.getOperand(opdIdx));
        }
        result.insert({asmOpdPos, std::make_tuple(opdKind, flagOps)});
        i += numAsmOpds + 1;
        asmOpdPos += 1;
    }
    return result;
}
Referenced by InlineAsmParser::addLiveRangeData(), llvm::LLVMTCEBuilder::emitInlineAsm(), and InlineAsmParser::substituteAsmString().
getSourceLocationInfo()
POP_COMPILER_DIAGS std::tuple< std::string, size_t > getSourceLocationInfo (const llvm::MachineInstr & mi)
Extracts source location info from the instruction.
If the instruction does not have debug info returns ("", 0);
Definition at line 54 of file LLVMUtilities.cc.
{
    using namespace llvm;
    DebugLoc dl = mi.getDebugLoc();
    if (!dl) return std::make_tuple("", 0);
    bool hasDebugInfo = false;
    hasDebugInfo = dl.getScope() != NULL;
    if (!hasDebugInfo) return std::make_tuple("", 0);
    size_t sourceLineNumber = 0;
    TCEString sourceFileName = "";
    // inspired from lib/codegen/MachineInstr.cpp
    sourceLineNumber = dl.getLine();
    sourceFileName = static_cast<TCEString>(
        cast<DIScope>(dl.getScope())->getFilename().str());
    return std::make_tuple(sourceFileName, sourceLineNumber);
}
Referenced by InlineAsmParser::addDebugInfoToInlineAsmBB(), llvm::LLVMTCEBuilder::emitInlineAsm(), getSourceLocationString(), and InlineAsmParser::substituteAsmString().
getSourceLocationString()
std::string getSourceLocationString (const llvm::MachineInstr & mi)
Returns source location as "<src-file>:<src-line>: " string if available.
Otherwise return empty string.
Definition at line 78 of file LLVMUtilities.cc.
{
    std::string srcFile;
    unsigned srcLine;
    std::tie(srcFile, srcLine) = getSourceLocationInfo(mi);
    if (!srcFile.empty()) {
        return srcFile + ":" + std::to_string(srcLine) + ": ";
    }
    return "";
}
References getSourceLocationInfo().
Referenced by llvm::LLVMTCEBuilder::emitInlineAsm().