OpenASIP: MachInfo.cc File Reference
MachInfo.cc File Reference
#include "Machine.hh"
#include "ControlUnit.hh"
#include "MachInfoCmdLineOptions.hh"
#include "OperationPool.hh"
#include "HWOperation.hh"
#include "Operation.hh"
#include "Conversion.hh"
#include "FUPort.hh"
#include <iostream>
#include <fstream>
#include <stdlib.h>
Functions
TCEString operandBindingsString (TTAMachine::HWOperation &hwop)
void printLatexFunctionUnitDescription (const TTAMachine::Machine &machine, std::ofstream &output)
void printLatexAddressSpaceDescription (const TTAMachine::Machine &machine, std::ofstream &output)
int main (int argc, char *argv[])
Variables
static MachInfoCmdLineOptions options
Detailed Description
MachInfo tool prints out information of a given processor design, for documentation purposes.
Author
Pekka Jääskeläinen 2014
Definition in file MachInfo.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 198 of file MachInfo.cc.
{
    try {
        options.parse(argv, argc);
    } catch (const ParserStopRequest&) {
        // In case --help was asked, or illegal command line parameters.
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& exception) {
        std::cerr << exception.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    if (options.numberOfArguments() != 1) {
        std::cerr << "Single ADF file required." << std::endl;
        return EXIT_FAILURE;
    }
    TCEString ADFFile = options.argument(1);
    if (options.outputFormat() != "latex") {
        std::cerr << "Unsupported output format." << std::endl;
        return EXIT_FAILURE;
    }
    const TTAMachine::Machine* mach = NULL;
    try {
        mach = TTAMachine::Machine::loadFromADF(ADFFile);
    } catch (const Exception& e) {
        std::cerr << e.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    std::ofstream fuDescOutput;
    std::ofstream asDescOutput;
    try {
        fuDescOutput.open(
            (options.outputFileNameSuffix() + ".fu_table.tex").c_str(),
            std::ios::trunc);
        asDescOutput.open(
            (options.outputFileNameSuffix() + ".as_table.tex").c_str(),
            std::ios::trunc);
    } catch (std::exception& e) {
        std::cerr << e.what() << std::endl;
        return EXIT_FAILURE;
    }
    if (options.outputFormat() == "latex") {
        printLatexFunctionUnitDescription(*mach, fuDescOutput);
        printLatexAddressSpaceDescription(*mach, asDescOutput);
    }
    fuDescOutput.close();
    asDescOutput.close();
    return EXIT_SUCCESS;
}
References CmdLineParser::argument(), Exception::errorMessage(), TTAMachine::Machine::loadFromADF(), CmdLineParser::numberOfArguments(), options, MachInfoCmdLineOptions::outputFileNameSuffix(), MachInfoCmdLineOptions::outputFormat(), CmdLineOptions::parse(), printLatexAddressSpaceDescription(), and printLatexFunctionUnitDescription().
operandBindingsString()
TCEString operandBindingsString (TTAMachine::HWOperation & hwop)
Definition at line 49 of file MachInfo.cc.
{
    OperationPool OSAL;
    Operation* osalOp = &OSAL.operation(hwop.name().c_str());
    if (osalOp == &NullOperation::instance()) {
        return TCEString("");
    }
    TCEString operandBindings = "";
    for (int i = 1; i < osalOp->operandCount() + 1; i++) {
        if (hwop.port(i) == NULL) {
            std::cerr << "Warning: Operand " << i << " of " << hwop.name()
                      << " was not bound to any port." << std::endl;
            continue;
        }
        if (i > 1) {
            operandBindings += ", ";
        }
        operandBindings += Conversion::toString(i) + ": "
            + hwop.port(i)->name();
    }
    return operandBindings;
}
References NullOperation::instance(), TTAMachine::HWOperation::name(), TTAMachine::Port::name(), Operation::operandCount(), OperationPool::operation(), TTAMachine::HWOperation::port(), and Conversion::toString().
Referenced by printLatexFunctionUnitDescription().
printLatexAddressSpaceDescription()
void printLatexAddressSpaceDescription (const TTAMachine::Machine & machine, std::ofstream & output)
Definition at line 149 of file MachInfo.cc.
{
    output << "\\begin{tabular}{|l|l|l|l|l|}" << std::endl;
    output << "\\hline" << std::endl;
    output << "name & start address & end address & width (b) & "
           << "numerical id(s) \\\\"
           << std::endl;
    output << "\\hline" << std::endl;
    TTAMachine::Machine::AddressSpaceNavigator nav =
        machine.addressSpaceNavigator();
    for (int i = 0; i < nav.count(); ++i) {
        TTAMachine::AddressSpace& as = *nav.item(i);
        if (&as == machine.controlUnit()->addressSpace())
            continue;
        output << as.name() << " & " << as.start() << " & " << as.end()
               << " & " << as.width() << " & ";
        std::set<unsigned> ids = as.numericalIds();
        for (std::set<unsigned>::iterator i = ids.begin(), e = ids.end();
            i != e; ++i) {
            output << *i << " ";
        }
        output << "\\\\" << std::endl;
    }
    output << "\\hline" << std::endl;
    output << "\\hline" << std::endl;
    TTAMachine::AddressSpace& as = *machine.controlUnit()->addressSpace();
    output << as.name() << " & " << as.start() << " & " << as.end() << " & "
           << as.width() << " & ";
    std::set<unsigned> ids = as.numericalIds();
    for (std::set<unsigned>::iterator i = ids.begin(), e = ids.end(); i != e;
        ++i) {
        output << *i << " ";
    }
    output << "\\\\" << std::endl;
    output << "\\hline" << std::endl;
    output << "\\end{tabular}" << std::endl;
}
References TTAMachine::FunctionUnit::addressSpace(), TTAMachine::Machine::addressSpaceNavigator(), TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), TTAMachine::AddressSpace::end(), TTAMachine::Machine::Navigator< ComponentType >::item(), machine, TTAMachine::Component::name(), TTAMachine::AddressSpace::numericalIds(), TTAMachine::AddressSpace::start(), and TTAMachine::AddressSpace::width().
Referenced by main().
printLatexFunctionUnitDescription()
void printLatexFunctionUnitDescription (const TTAMachine::Machine & machine, std::ofstream & output)
Definition at line 72 of file MachInfo.cc.
{
    OperationPool OSAL;
    output << "\\begin{longtable}{|l|p{7cm}|p{3.5cm}|}" << std::endl;
    TTAMachine::Machine::FunctionUnitNavigator nav = machine
        .functionUnitNavigator();
    for (int i = 0; i < nav.count(); ++i) {
        TTAMachine::FunctionUnit& fu = *nav.item(i);
        output << "\\hline" << std::endl;
        // TODO: print description here
        TCEString fuDescription;
        if (fu.hasAddressSpace()) {
            fuDescription << " Accesses address space \\textbf{"
                          << fu.addressSpace()->name() << "}.\n";
        }
        output << fu.name() << "\t& \\multicolumn{2}{p{10cm}|}{"
               << fuDescription << "} \\\\" << std::endl;
        output << "\\hline" << std::endl;
        for (int op = 0; op < fu.operationCount(); ++op) {
            TTAMachine::HWOperation& hwop = *fu.operation(op);
            Operation* osalOp = NULL;
            TCEString description;
            TCEString operandBindings;
            if (&OSAL.operation(hwop.name().c_str())
                != &NullOperation::instance()) {
                osalOp = &OSAL.operation(hwop.name().c_str());
                description = osalOp->description();
                operandBindings = operandBindingsString(hwop);
            } else {
                std::cerr << "warning: Could not find OSAL data for operation '"
                          << hwop.name() << "." << std::endl;
            }
            TCEString opname = hwop.name();
            opname = opname.replaceString("_", "\\_");
            operandBindings = operandBindings.replaceString("_", "\\_");
            output << "\\footnotesize{" << opname << " (" << hwop.latency() - 1
                   << ")} & \\footnotesize{" << description
                   << "} & \\footnotesize{" << operandBindings << "}\\\\"
                   << std::endl;
        }
    }
    output << "\\hline" << std::endl;
    output << "\\hline" << std::endl;
    TTAMachine::FunctionUnit& fu = *machine.controlUnit();
    output << fu.name() << "\t & control unit & \t \\\\" << std::endl;
    output << "\\hline" << std::endl;
    for (int op = 0; op < fu.operationCount(); ++op) {
        TTAMachine::HWOperation& hwop = *fu.operation(op);
        Operation* osalOp = NULL;
        TCEString description;
        if (&OSAL.operation(hwop.name().c_str())
            != &NullOperation::instance()) {
            osalOp = &OSAL.operation(hwop.name().c_str());
            description = osalOp->description();
        } else {
            std::cerr << "warning: Could not find OSAL data for operation '"
                      << hwop.name() << "." << std::endl;
        }
        TCEString opname = hwop.name();
        opname = opname.replaceString("_", "\\_");
        output << opname << " (" << hwop.latency() - 1 << ") & \\small{"
               << description << "} & \\\\" << std::endl;
    }
    output << "\\hline" << std::endl;
    output << "\\end{longtable}" << std::endl;
}
References TTAMachine::FunctionUnit::addressSpace(), TTAMachine::Machine::controlUnit(), TTAMachine::Machine::Navigator< ComponentType >::count(), Operation::description(), TTAMachine::Machine::functionUnitNavigator(), TTAMachine::FunctionUnit::hasAddressSpace(), NullOperation::instance(), TTAMachine::Machine::Navigator< ComponentType >::item(), TTAMachine::HWOperation::latency(), machine, TTAMachine::HWOperation::name(), TTAMachine::Component::name(), operandBindingsString(), OperationPool::operation(), TTAMachine::FunctionUnit::operation(), TTAMachine::FunctionUnit::operationCount(), and TCEString::replaceString().
Referenced by main().
Variable Documentation
options
MachInfoCmdLineOptions options static
Definition at line 46 of file MachInfo.cc.
Referenced by ProGe::NetlistGenerator::addIUToNetlist(), GUIOptionsSerializer::addKeyboardShortcut(), llvm::TCEPassConfig::addPreISel(), ProGe::NetlistGenerator::addRFToNetlist(), ProGeTools::checkForGeneratableFU(), Automagic::checkForGeneratableFU(), ProGeTools::checkForSelectableFU(), Automagic::checkForSelectableFU(), ProGeTools::checkForSelectableIU(), Automagic::checkForSelectableIU(), ProGeTools::checkForSelectableRF(), Automagic::checkForSelectableRF(), llvm::LLVMTCEIRBuilder::compileOptimized(), GUIOptionsSerializer::convertToConfigFileFormat(), ProDeOptionsSerializer::convertToConfigFileFormat(), GUIOptionsSerializer::convertToOptionsObjectFormat(), ProDeOptionsSerializer::convertToOptionsObjectFormat(), ProGeTools::createFUGeneratableOperationInfos(), Automagic::createFUGeneratableOperationInfos(), llvm::TCETargetMachine::createMachine(), ProximMainFrame::createToolbar(), MainFrame::createToolbar(), DataDependenceGraphBuilder::DataDependenceGraphBuilder(), OSEdModifyBehaviorCmd::Do(), ProximOptionsCmd::Do(), ProximQuitCmd::Do(), EditOptionsCmd::Do(), QuitCmd::Do(), SaveOptionsCmd::Do(), llvm::TCERegisterInfo::eliminateFrameIndex(), ProGe::NetlistGenerator::generate(), ProGe::ProGeUI::generateIDF(), ProGe::ProcessorGenerator::generateProcessor(), ProGe::ProGeUI::generateProcessor(), GenerateProcessor::generateProcessor(), GenerateProcessor::getOutputDir(), llvm::TCERegisterInfo::getReservedRegs(), BBSchedulerController::handleBasicBlock(), FUGen::implement(), llvm::TCETTIImpl::isHardwareLoopProfitable(), llvm::LLVMTCEScheduler::LLVMTCEScheduler(), loadInputs(), loadPluginParameters(), main(), ProximMainFrame::menuAccelerator(), MainFrame::menuAccelerator(), GenerateProcessorDialog::onOK(), OperationPropertyDialog::onOpen(), ResultDialog::onOpen(), OSEdOptionsDialog::onSave(), MainFrame::onToggleToolbar(), CmdLineParser::parse(), Model::pushToStack(), GUIOptionsSerializer::readOptions(), DesignSpaceExplorer::schedule(), Application::setCmdLineOptions(), ProgramImageGenerator::setDataStartOptions(), GUIOptionsSerializer::setToolbarProperties(), GUIOptionsSerializer::setWindowProperties(), SimpleBrokerDirector::SimpleBrokerDirector(), CmdLineParser::storeOptions(), OSEdOptionsDialog::TransferDataToWindow(), MainFrame::updateUI(), GenerateProcessor::validIntegratorParameters(), GUIOptionsSerializer::writeOptions(), and llvm::LLVMTCEIRBuilder::~LLVMTCEIRBuilder().