OpenASIP: OneCycleOperationExecutor.cc File Reference
OneCycleOperationExecutor.cc File Reference
#include "OneCycleOperationExecutor.hh"
#include "OperationContext.hh"
#include "SimValue.hh"
#include "Operation.hh"
#include "SequenceTools.hh"
#include "PortState.hh"
#include "OperationPool.hh"
#include "SimulatorToolbox.hh"
#include "Application.hh"
Variables
SimValue dummy (32)
a dummy simvalue which is given for operands that are not bound
Detailed Description
Definition of OneCycleOperationExecutor class.
Author
Jussi Nyk채nen 2004 (nykanen-no.spam-cs.tut.fi)
Pekka J채채skel채inen 2005 (pjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file OneCycleOperationExecutor.cc.
Variable Documentation
dummy
SimValue dummy(32) (32)
a dummy simvalue which is given for operands that are not bound
Referenced by BlockImplementationDialog::BlockImplementationDialog(), SQLiteConnection::compileQuery(), llvm::LLVMTCEBuilder::createMBBReference(), llvm::LLVMTCEBuilder::createSymbolReference(), PrintPreviewCmd::Do(), QuitCmd::Do(), SaveDocumentAsCmd::Do(), SaveDocumentCmd::Do(), AddWatchDialog::initialize(), ProximMemoryWindow::loadProgramMemory(), AddressSpacesDialog::onActivateAS(), BusDialog::onActivateFUGuard(), FUDialog::onActivateOperation(), GCUDialog::onActivateOperation(), FUDialog::onActivatePort(), GCUDialog::onActivatePort(), IUDialog::onActivatePort(), RFDialog::onActivatePort(), BusDialog::onActivateRFGuard(), OptionsDialog::onActivateShortcut(), SocketDialog::onAttach(), BridgeDialog::onBidirectional(), AddressSpaceDialog::onBitWidth(), BlockImplementationDialog::onBrowse(), BusDialog::onDeleteFUGuard(), OTAFormatListDialog::onDeleteOTAFormat(), BusDialog::onDeleteRFGuard(), BusDialog::onDeleteSegment(), ImmediateSlotDialog::onDeleteSlot(), TemplateListDialog::onDeleteTemplate(), SocketDialog::onDetach(), AutoSelectImplementationsDialog::onFind(), NumberControl::onModeChoice(), ProximBreakpointWindow::refreshStopPoints(), CostEstimationDataDialog::TransferDataToWindow(), AddressSpaceDialog::TransferDataToWindow(), BridgeDialog::TransferDataToWindow(), BusDialog::TransferDataToWindow(), RFImplementationDialog::update(), FUImplementationDialog::update(), OperationPropertyDialog::updateAffected(), InputOperandDialog::updateList(), SimulateDialog::updateLists(), OperationDialog::updateOperandList(), OperationPropertyDialog::updateOperands(), FUDialog::updateOperationList(), GCUDialog::updateOperationList(), OTAFormatListDialog::updateOperationList(), FUDialog::updatePortList(), GCUDialog::updatePortList(), and TemplateListDialog::updateSlotList().