OpenASIP: InstructionPatternAnalyzer Struct Reference
InstructionPatternAnalyzer Struct Reference
#include <InstructionPatternAnalyzer.hh>
Public Member Functions
InstructionPatternAnalyzer ()
virtual ~InstructionPatternAnalyzer ()
virtual bool runOnMachineFunction (llvm::MachineFunction &F)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 46 of file InstructionPatternAnalyzer.hh.
Constructor & Destructor Documentation
InstructionPatternAnalyzer()
InstructionPatternAnalyzer::InstructionPatternAnalyzer () inline
Definition at line 48 of file InstructionPatternAnalyzer.hh.
: MachineFunctionPass(ID) {}
~InstructionPatternAnalyzer()
virtual InstructionPatternAnalyzer::~InstructionPatternAnalyzer () inline virtual
Definition at line 49 of file InstructionPatternAnalyzer.hh.
{}
Member Function Documentation
runOnMachineFunction()
bool InstructionPatternAnalyzer::runOnMachineFunction (llvm::MachineFunction & F) virtual
Definition at line 44 of file InstructionPatternAnalyzer.cc.
{
    MachineInstrDDG ddg(F);
    ddg.setPrintOnlyCriticalPath(true);
    ddg.writeToDotFile(F.getFunction().getName().str() + ".pre_ra.critical_path.dot");
    ddg.setPrintOnlyCriticalPath(false);
    ddg.computeOptimalSchedule();
    ddg.writeToDotFile(F.getFunction().getName().str() + ".pre_ra.dot");
    return false;
}
References MachineInstrDDG::computeOptimalSchedule(), MachineInstrDDG::setPrintOnlyCriticalPath(), and GraphBase< GraphNode, GraphEdge >::writeToDotFile().
Member Data Documentation
ID
char InstructionPatternAnalyzer::ID = 0 static
Definition at line 47 of file InstructionPatternAnalyzer.hh.
The documentation for this struct was generated from the following files:
InstructionPatternAnalyzer.hh
InstructionPatternAnalyzer.cc