OpenASIP: MIDDGNode Struct Reference
MIDDGNode Struct Reference
#include <MachineInstrDDG.hh>
Public Member Functions
MIDDGNode ()
MIDDGNode (const llvm::MachineInstr &mi, int sequentialAddress)
virtual ~MIDDGNode ()
bool operator< (const MIDDGNode &other) const
bool operator== (const MIDDGNode &other) const
const llvm::MachineInstr * machineInstr () const
int sequentialAddress () const
std::string dotString () const
TCEString osalOperationName () const
void setOptimalCycle (int cycle)
int optimalCycle () const
Public Member Functions inherited from GraphNode
GraphNode (int nodeID)
GraphNode ()
virtual ~GraphNode ()
virtual GraphNode * clone () const
int nodeID () const
virtual std::string toString () const
Private Attributes
const llvm::MachineInstr * mi_
int address_
int optimalCycle_
Detailed Description
Definition at line 58 of file MachineInstrDDG.hh.
Constructor & Destructor Documentation
MIDDGNode() [1/2]
MIDDGNode::MIDDGNode () inline
Definition at line 59 of file MachineInstrDDG.hh.
: GraphNode(), mi_(NULL), address_(-1), optimalCycle_(-1) {}
MIDDGNode() [2/2]
MIDDGNode::MIDDGNode (const llvm::MachineInstr & mi, int sequentialAddress) inline
Definition at line 60 of file MachineInstrDDG.hh.
                                                                 :
        GraphNode(), mi_(&mi), address_(sequentialAddress) {}
~MIDDGNode()
virtual MIDDGNode::~MIDDGNode () inline virtual
Definition at line 63 of file MachineInstrDDG.hh.
{}
Member Function Documentation
dotString()
std::string MIDDGNode::dotString () const virtual
Returns the string that should be placed in the node's properties section in the GraphViz Dot string.
This can be overridden in the derived class to add different properties (e.g., colors, etc.) to different type of nodes. The default implementation only sets the label property.
Returns
String describing the Dot properties of the Node.
Reimplemented from GraphNode.
Definition at line 606 of file MachineInstrDDG.cc.
{
    return (boost::format("label=\"%s\"") % osalOperationName()).str();
}
References osalOperationName().
Referenced by MachineInstrDDG::dotString().
machineInstr()
const llvm::MachineInstr * MIDDGNode::machineInstr () const inline
Definition at line 72 of file MachineInstrDDG.hh.
{ return mi_; }
References mi_.
Referenced by osalOperationName(), and MachineInstrDDG::preceedingNodeUsesOrDefinesReg().
operator<()
bool MIDDGNode::operator< (const MIDDGNode & other) const inline
Definition at line 65 of file MachineInstrDDG.hh.
{
        return other.sequentialAddress() < this->sequentialAddress();
    }
References sequentialAddress().
operator==()
bool MIDDGNode::operator== (const MIDDGNode & other) const inline
Definition at line 68 of file MachineInstrDDG.hh.
{
        return other.mi_ == this->mi_;
    }
References mi_.
optimalCycle()
int MIDDGNode::optimalCycle () const inline
Definition at line 79 of file MachineInstrDDG.hh.
{ return optimalCycle_; }
References optimalCycle_.
osalOperationName()
TCEString MIDDGNode::osalOperationName () const
Try to figure out the name of the instruction opcode in OSAL, if available.
If the operation with the produced name is not found in OSAL, llvm: is prepended to the name string.
Definition at line 566 of file MachineInstrDDG.cc.
{
    const llvm::TargetInstrInfo *TII =
        machineInstr()->getParent()->getParent()->getTarget().
        getSubtargetImpl(
            machineInstr()->getParent()->getParent()->getFunction())->
        getInstrInfo();
    // If it's a custom operation call, try to figure out
    // the called operation name and use it instead as the
    // node label.
    TCEString opName;
    if (mi_->isInlineAsm()) {
        unsigned numDefs = 0;
        while (mi_->getOperand(numDefs).isReg() &&
               mi_->getOperand(numDefs).isDef())
            ++numDefs;
        opName = mi_->getOperand(numDefs).getSymbolName();
    } else {
        opName = TII->getName(mi_->getOpcode()).str();
    }
    // Clean up the operand type string encoded as
    // lower case letter at the end of the string.
    TCEString upper = opName.upper();
    TCEString cleaned;
    for (size_t i = 0; i < opName.size(); ++i) {
        if (upper[i] == opName[i])
            cleaned += opName[i];
        else
            break;
    }
    OperationPool ops;
    Operation& operation = ops.operation(cleaned.c_str());
    if (operation.isNull())
        return TCEString("llvm:") + opName;
    return cleaned;
}
References Operation::isNull(), machineInstr(), mi_, OperationPool::operation(), and TCEString::upper().
Referenced by dotString(), and MachineInstrDDG::dotString().
sequentialAddress()
int MIDDGNode::sequentialAddress () const inline
Definition at line 73 of file MachineInstrDDG.hh.
{ return address_; }
References address_.
Referenced by MachineInstrDDG::assignPhysReg(), MachineInstrDDG::createFalseDepEdge(), and operator<().
setOptimalCycle()
void MIDDGNode::setOptimalCycle (int cycle) inline
Definition at line 78 of file MachineInstrDDG.hh.
{ optimalCycle_ = cycle; }
References optimalCycle_.
Referenced by MachineInstrDDG::computeOptimalSchedule().
Member Data Documentation
address_
int MIDDGNode::address_ private
Definition at line 82 of file MachineInstrDDG.hh.
Referenced by sequentialAddress().
mi_
const llvm::MachineInstr* MIDDGNode::mi_ private
Definition at line 81 of file MachineInstrDDG.hh.
Referenced by machineInstr(), operator==(), and osalOperationName().
optimalCycle_
int MIDDGNode::optimalCycle_ private
Definition at line 83 of file MachineInstrDDG.hh.
Referenced by optimalCycle(), and setOptimalCycle().
The documentation for this struct was generated from the following files:
MachineInstrDDG.hh
MachineInstrDDG.cc