OpenASIP: TTAMachine::PipelineElement::Comparator Struct Reference
TTAMachine::PipelineElement::Comparator Struct Reference
#include <PipelineElement.hh>
Public Member Functions
bool operator() (const PipelineElement *pe1, const PipelineElement *pe2) const
Detailed Description
Definition at line 55 of file PipelineElement.hh.
Member Function Documentation
operator()()
bool TTAMachine::PipelineElement::Comparator::operator() (const PipelineElement * pe1, const PipelineElement * pe2) const
Definition at line 111 of file PipelineElement.cc.
{
    if (pe1 == NULL) {
        return false;
    }
    if (pe2 == NULL) {
        return true;
    }
    if (pe1->name() > pe2->name()) {
        return true;
    }
    if (pe2->name() > pe1->name()) {
        return false;
    }
    if (pe1->parentUnit()->name() > pe2->parentUnit()->name()) {
        return true;
    }
    return false;
}
References TTAMachine::Component::name(), TTAMachine::PipelineElement::name(), and TTAMachine::PipelineElement::parentUnit().
The documentation for this struct was generated from the following files:
PipelineElement.hh
PipelineElement.cc