OpenASIP: MIDDGEdge Struct Reference
MIDDGEdge Struct Reference
#include <MachineInstrDDG.hh>
Public Types
enum DependenceType { DEP_UNKNOWN = 0 , DEP_RAW = 1 , DEP_WAR = 2 , DEP_WAW = 3 }
enum EdgeReason { EDGE_REGISTER , EDGE_MEMORY }
Public Member Functions
MIDDGEdge (unsigned reg)
MIDDGEdge (unsigned reg, DependenceType type)
virtual ~MIDDGEdge ()
TCEString dotString () const
TCEString toString () const
Public Member Functions inherited from GraphEdge
GraphEdge ()
GraphEdge (const GraphEdge &edge)
virtual GraphEdge * clone () const
virtual ~GraphEdge ()
virtual int edgeID () const
virtual bool isBackEdge () const
int weight () const
void setWeight (int w)
Private Member Functions
std::string typeAsString () const
Private Attributes
unsigned reg_
unsigned char dependenceType_
Detailed Description
Definition at line 86 of file MachineInstrDDG.hh.
Member Enumeration Documentation
DependenceType
enum MIDDGEdge::DependenceType
Enumerator
DEP_UNKNOWN
DEP_RAW
DEP_WAR
DEP_WAW
Definition at line 87 of file MachineInstrDDG.hh.
{
        DEP_UNKNOWN = 0,
        DEP_RAW     = 1,
        DEP_WAR     = 2,
        DEP_WAW     = 3};
EdgeReason
enum MIDDGEdge::EdgeReason
Enumerator
EDGE_REGISTER
EDGE_MEMORY
Definition at line 93 of file MachineInstrDDG.hh.
                    {
        EDGE_REGISTER,
        EDGE_MEMORY};
Constructor & Destructor Documentation
MIDDGEdge() [1/2]
MIDDGEdge::MIDDGEdge (unsigned reg) inline
Definition at line 97 of file MachineInstrDDG.hh.
                            :
        GraphEdge(), reg_(reg), dependenceType_(DEP_RAW) {}
MIDDGEdge() [2/2]
MIDDGEdge::MIDDGEdge (unsigned reg, DependenceType type) inline
Definition at line 100 of file MachineInstrDDG.hh.
                                                 :
        GraphEdge(), reg_(reg), dependenceType_(type) {}
~MIDDGEdge()
virtual MIDDGEdge::~MIDDGEdge () inline virtual
Definition at line 104 of file MachineInstrDDG.hh.
{}
Member Function Documentation
dotString()
TCEString MIDDGEdge::dotString () const inline virtual
Returns the string that should be placed in the edge's properties section in the GraphViz Dot string.
This can be overridden in the derived class to add different properties (e.g., colors, etc.) to different type of edges. The default implementation only sets the label property.
Returns
String describing the Dot properties of the edge.
Reimplemented from GraphEdge.
Definition at line 106 of file MachineInstrDDG.hh.
{
        return (boost::format("label=\"%d %s\"") % reg_ % typeAsString()).
            str();
    }
References reg_, and typeAsString().
Referenced by MachineInstrDDG::dotString().
toString()
TCEString MIDDGEdge::toString () const inline virtual
Return the label of the edge as a string.
Used for printing graph in GraphViz .dot file.
Returns
The edge ID as a string
Reimplemented from GraphEdge.
Definition at line 111 of file MachineInstrDDG.hh.
{
        return (boost::format("%d %s") % reg_ % typeAsString()).str();
    }
References reg_, and typeAsString().
typeAsString()
std::string MIDDGEdge::typeAsString () const inline private
Definition at line 117 of file MachineInstrDDG.hh.
{
        std::string type = "unknown";
        if (dependenceType_ == DEP_RAW)
            type = "RaW";
        else if (dependenceType_ == DEP_WAR)
            type = "WaR";
        else if (dependenceType_ == DEP_WAW)
            type = "WaW";
        return type;
    }
References DEP_RAW, DEP_WAR, DEP_WAW, and dependenceType_.
Referenced by dotString(), and toString().
Member Data Documentation
dependenceType_
unsigned char MIDDGEdge::dependenceType_ private
Definition at line 129 of file MachineInstrDDG.hh.
Referenced by typeAsString().
reg_
unsigned MIDDGEdge::reg_ private
Definition at line 128 of file MachineInstrDDG.hh.
Referenced by dotString(), and toString().
The documentation for this struct was generated from the following file:
MachineInstrDDG.hh