OpenASIP: AssemblerParser Struct Reference
AssemblerParser Struct Reference
#include <AssemblerParser.hh>
Classes
struct definition
Public Member Functions
AssemblerParser (TPEF::Binary &aBin, const TTAMachine::Machine &aMach, AssemblyParserDiagnostic *parserDiagnostic, bool codeLinesOnly=false)
AssemblerParser.
bool compile (const std::string &asmCode) const
void finalize (bool littleEndian) const
void cleanup ()
UValue errorLine ()
bool codeLinesOnly () const
Private Attributes
TPEF::Binary & bin_
TPEF where to program is compiled.
MachineResourceManager resourceManager_
Generates string, resource, null and address space sections.
DataSectionCreator dataSectionCreator_
Creates data sections.
CodeSectionCreator codeSectionCreator_
Creates code section.
LabelManager labelManager_
Creates symbol and relocation sections.
ParserTemp parserTemp_
Temp-structure containing most recent parsed tokens.
bool codeLinesOnly_ = false
Controls start symbol of the grammar. False: the default symbol (program) for parsing assembly files. True: 'codeLines' symbol suitable for inline assembly parsing.
Detailed Description
Definition at line 331 of file AssemblerParser.hh.
Constructor & Destructor Documentation
AssemblerParser()
AssemblerParser::AssemblerParser (TPEF::Binary & aBin, const TTAMachine::Machine & aMach, AssemblyParserDiagnostic * parserDiagnostic, bool codeLinesOnly = false)
AssemblerParser.
Grammar constructor.
Parameters
aBin TPEF where to program is compiled.
aMach Machine which for program is compiled.
parent Error message manager of the compiler.
codeLinesOnly If true start symbol for the grammar is 'codeLines'. The option is suitable for inline assembly parsing. Default is false.
Constructor.
Parameters
aBin TPEF object where to create program.
aMach Machine which for program is written.
parserDiagnostic Assembler root class for warning handling.
Definition at line 231 of file AssemblerParser.cc.
                        :
    bin_(aBin),
    resourceManager_(aBin, aMach, parserDiagnostic),
    dataSectionCreator_(resourceManager_, parserDiagnostic),
    codeSectionCreator_(resourceManager_, aMach, parserDiagnostic),
    labelManager_(aBin, resourceManager_, parserDiagnostic),
    codeLinesOnly_(codeLinesOnly) {
}
Member Function Documentation
cleanup()
void AssemblerParser::cleanup ()
Frees all resources allocated by parser.
Definition at line 247 of file AssemblerParser.cc.
{
    dataSectionCreator_.cleanup();
    codeSectionCreator_.cleanup();
    labelManager_.cleanup();
}
References CodeSectionCreator::cleanup(), DataSectionCreator::cleanup(), LabelManager::cleanup(), codeSectionCreator_, dataSectionCreator_, and labelManager_.
Referenced by Assembler::compile().
codeLinesOnly()
bool AssemblerParser::codeLinesOnly () const inline
Definition at line 938 of file AssemblerParser.hh.
{ return codeLinesOnly_; }
References codeLinesOnly_.
Referenced by AssemblerParser::definition< ScannerT >::start().
compile()
bool AssemblerParser::compile (const std::string & asmCode) const
Definition at line 254 of file AssemblerParser.cc.
{
#if BOOST_VERSION >= 103800
    return boost::spirit::classic::parse(asmCode.c_str(), *this).full;
#else
    return boost::spirit::parse(asmCode.c_str(), *this).full;
#endif
}
Referenced by Assembler::compile(), and InlineAsmParser::parse().
errorLine()
UValue AssemblerParser::errorLine ()
Returns line number where parse error happened in assembler file.
Returns
Line number where parse error happened in assembler file.
Definition at line 268 of file AssemblerParser.cc.
{
    return parserTemp_.lineNumber;
}
References ParserTemp::lineNumber, and parserTemp_.
Referenced by Assembler::compile(), and InlineAsmParser::parse().
finalize()
void AssemblerParser::finalize (bool littleEndian) const
Finalizes parsed TPEF.
After calling this successfully parser should contain valid tpef.
Definition at line 278 of file AssemblerParser.cc.
{
    bin_.setArch(Binary::FA_TTA_TUT);
    bin_.setType(Binary::FT_PARALLEL);
    // these must be called in this order to make sure that all label values
    // are resolved before they are used
    dataSectionCreator_.finalize(bin_, labelManager_, littleEndian);
    codeSectionCreator_.finalize(bin_, labelManager_);
    labelManager_.finalize();
}
References bin_, codeSectionCreator_, dataSectionCreator_, TPEF::Binary::FA_TTA_TUT, LabelManager::finalize(), CodeSectionCreator::finalize(), DataSectionCreator::finalize(), TPEF::Binary::FT_PARALLEL, labelManager_, TPEF::Binary::setArch(), and TPEF::Binary::setType().
Referenced by Assembler::compile(), and InlineAsmParser::parse().
Member Data Documentation
bin_
TPEF::Binary& AssemblerParser::bin_ private
TPEF where to program is compiled.
Definition at line 943 of file AssemblerParser.hh.
Referenced by finalize().
codeLinesOnly_
bool AssemblerParser::codeLinesOnly_ = false private
Controls start symbol of the grammar. False: the default symbol (program) for parsing assembly files. True: 'codeLines' symbol suitable for inline assembly parsing.
Definition at line 960 of file AssemblerParser.hh.
Referenced by codeLinesOnly().
codeSectionCreator_
CodeSectionCreator AssemblerParser::codeSectionCreator_ mutable private
Creates code section.
Definition at line 950 of file AssemblerParser.hh.
Referenced by cleanup(), AssemblerParser::definition< ScannerT >::definition(), and finalize().
dataSectionCreator_
DataSectionCreator AssemblerParser::dataSectionCreator_ mutable private
Creates data sections.
Definition at line 948 of file AssemblerParser.hh.
Referenced by cleanup(), AssemblerParser::definition< ScannerT >::definition(), and finalize().
labelManager_
LabelManager AssemblerParser::labelManager_ mutable private
Creates symbol and relocation sections.
Definition at line 952 of file AssemblerParser.hh.
Referenced by cleanup(), AssemblerParser::definition< ScannerT >::definition(), and finalize().
parserTemp_
ParserTemp AssemblerParser::parserTemp_ mutable private
Temp-structure containing most recent parsed tokens.
Definition at line 955 of file AssemblerParser.hh.
Referenced by AssemblerParser::definition< ScannerT >::definition(), and errorLine().
resourceManager_
MachineResourceManager AssemblerParser::resourceManager_ mutable private
Generates string, resource, null and address space sections.
Definition at line 946 of file AssemblerParser.hh.
Referenced by AssemblerParser::definition< ScannerT >::definition().
The documentation for this struct was generated from the following files:
AssemblerParser.hh
AssemblerParser.cc