OpenASIP: TCEStubTargetMachine.cc File Reference
TCEStubTargetMachine.cc File Reference
#include "CompilerWarnings.hh"
#include "tce_config.h"
#include "TCEStubTargetMachine.hh"
#include "ADFSerializer.hh"
#include "TCEStubTargetTransformInfo.hh"
#include "TCEStubSubTarget.hh"
#include <llvm/Target/TargetLoweringObjectFile.h>
#include <llvm/Target/TargetMachine.h>
#include <llvm/CodeGen/Passes.h>
#include <llvm/IR/LegacyPassManager.h>
#include <llvm/Target/TargetOptions.h>
#include <llvm/CodeGen/TargetPassConfig.h>
Functions
void LLVMInitializeTCETargetInfo ()
void LLVMInitializeTCEStubTarget ()
void LLVMInitializeTCEStubTargetMC ()
StringRef getTargetDesc (const Triple &TT)
Variables
StringRef DescriptionStringBE
StringRef DescriptionStringLE
StringRef DescriptionStringLE64
Function Documentation
getTargetDesc()
StringRef getTargetDesc (const Triple & TT)
Definition at line 113 of file TCEStubTargetMachine.cc.
{
    if (TT.getArchName().equals("tce"))
        return DescriptionStringBE;
    else {
        if (TT.getArchName().equals("tcele"))
            return DescriptionStringLE;
        else
            return DescriptionStringLE64;
    }
}
References DescriptionStringBE, DescriptionStringLE, and DescriptionStringLE64.
LLVMInitializeTCEStubTarget()
void LLVMInitializeTCEStubTarget ()
Definition at line 80 of file TCEStubTargetMachine.cc.
{
    // Register the targetmachine impl.
    RegisterTargetMachine<TCEStubTargetMachine> X(TheTCETarget);
    RegisterTargetMachine<TCEStubTargetMachine> Y(TheTCELETarget);
    RegisterTargetMachine<TCEStubTargetMachine> Z(TheTCELE64Target);
}
References llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by TCEPluginInitializer::TCEPluginInitializer().
LLVMInitializeTCEStubTargetMC()
void LLVMInitializeTCEStubTargetMC ()
Definition at line 87 of file TCEStubTargetMachine.cc.
{}
LLVMInitializeTCETargetInfo()
void LLVMInitializeTCETargetInfo ()
Definition at line 67 of file TCEStubTargetMachine.cc.
{
    RegisterTarget<Triple::tce, /*HasJIT=*/false>
        X(TheTCETarget, "tce-tut-llvm", "TCE custom processor",
            "TODO: wonder what this button does");
    RegisterTarget<Triple::tcele, false>
        Y(TheTCELETarget, "tcele-tut-llvm",
            "TCE custom processor (little endian)",
            "TODO: wonder what this button does");
    RegisterTarget<Triple::tcele64, false>
        Z(TheTCELE64Target, "tcele64-tut-llvm", "64-bit TCE custom processor (little endian) ",
          "TODO: wonder what this button does");
}
References llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by LLVMBackend::compile(), and TCEPluginInitializer::TCEPluginInitializer().
Variable Documentation
DescriptionStringBE
StringRef DescriptionStringBE
Initial value:
= "E-p:32:32:32-i1:8:8-i8:8:32-"
    "i16:16:32-i32:32:32-i64:32:32-"
    "f32:32:32-f64:32:32-v64:32:32-"
    "v128:32:32-v256:32:32-v512:32:32-v1024:32:32-a0:0:32-n32"
Definition at line 89 of file TCEStubTargetMachine.cc.
Referenced by getTargetDesc().
DescriptionStringLE
StringRef DescriptionStringLE
Initial value:
= "e-p:32:32:32-i1:8:8-i8:8:32-"
    "i16:16:32-i32:32:32-i64:32:32-"
    "f32:32:32-f64:32:32-v64:64:64-"
    "v128:128:128-v256:256:256-v512:512:512-v1024:1024:1024-a0:0:32-n32"
Definition at line 101 of file TCEStubTargetMachine.cc.
Referenced by getTargetDesc().
DescriptionStringLE64
StringRef DescriptionStringLE64
Initial value:
= "e-p:64:64:64-i1:8:64-i8:8:64-"
    "i16:16:64-i32:32:64-i64:64:64-"
    "f32:32:64-f64:64:64-v64:64:64-"
    "v128:128:128-v256:256:256-v512:512:512-v1024:1024:1024-"
    "v2048:2048:2048-v4096:4096:4096-a0:0:64-n64"
Definition at line 107 of file TCEStubTargetMachine.cc.
Referenced by getTargetDesc().