OpenASIP: TCEStubTargetMachine.hh File Reference
TCEStubTargetMachine.hh File Reference
#include "tce_config.h"
#include "llvm/MC/TargetRegistry.h"
#include <llvm/Target/TargetMachine.h>
#include <llvm/CodeGen/TargetLowering.h>
#include <llvm/Target/TargetLoweringObjectFile.h>
#include <llvm/CodeGen/TargetLoweringObjectFileImpl.h>
#include "TCEStubSubTarget.hh"
Classes
class llvm::TCEBaseTargetMachine
class llvm::TCEStubTargetMachine
Namespaces
namespace TTAMachine
namespace llvm
Macros
#define PICCOPY PIC
#define PIC PICCOPY
Functions
void LLVMInitializeTCETargetInfo ()
void LLVMInitializeTCEStubTarget ()
Variables
Target llvm::TheTCETarget
Target llvm::TheTCELETarget
Target llvm::TheTCELE64Target
Detailed Description
Declaration of TCEStubTargetMachine class.
Author
Ville Korhonen 2015
Definition in file TCEStubTargetMachine.hh.
Macro Definition Documentation
PIC
#define PIC PICCOPY
Definition at line 46 of file TCEStubTargetMachine.hh.
PICCOPY
#define PICCOPY PIC
Definition at line 42 of file TCEStubTargetMachine.hh.
Function Documentation
LLVMInitializeTCEStubTarget()
void LLVMInitializeTCEStubTarget ()
Definition at line 80 of file TCEStubTargetMachine.cc.
{
    // Register the targetmachine impl.
    RegisterTargetMachine<TCEStubTargetMachine> X(TheTCETarget);
    RegisterTargetMachine<TCEStubTargetMachine> Y(TheTCELETarget);
    RegisterTargetMachine<TCEStubTargetMachine> Z(TheTCELE64Target);
}
References llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by TCEPluginInitializer::TCEPluginInitializer().
LLVMInitializeTCETargetInfo()
void LLVMInitializeTCETargetInfo ()
Definition at line 67 of file TCEStubTargetMachine.cc.
{
    RegisterTarget<Triple::tce, /*HasJIT=*/false>
        X(TheTCETarget, "tce-tut-llvm", "TCE custom processor",
            "TODO: wonder what this button does");
    RegisterTarget<Triple::tcele, false>
        Y(TheTCELETarget, "tcele-tut-llvm",
            "TCE custom processor (little endian)",
            "TODO: wonder what this button does");
    RegisterTarget<Triple::tcele64, false>
        Z(TheTCELE64Target, "tcele64-tut-llvm", "64-bit TCE custom processor (little endian) ",
          "TODO: wonder what this button does");
}
References llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by LLVMBackend::compile(), and TCEPluginInitializer::TCEPluginInitializer().