OpenASIP: TCETargetMachine.hh File Reference
TCETargetMachine.hh File Reference
#include <set>
#include "tce_config.h"
#include "CompilerWarnings.hh"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/IR/PassManager.h"
#include "TCEStubTargetMachine.hh"
#include "TCETargetMachinePlugin.hh"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/CodeGen/TargetPassConfig.h"
Classes
class llvm::TCEPassConfig
class llvm::TCETargetMachine
Namespaces
namespace TTAMachine
namespace llvm
Functions
void LLVMInitializeTCETarget ()
Function Documentation
LLVMInitializeTCETarget()
void LLVMInitializeTCETarget ()
Definition at line 121 of file TCETargetMachine.cc.
{
    RegisterTargetMachine<TCETargetMachine> Y(TheTCETarget);
    RegisterTargetMachine<TCETargetMachine> X0(TheTCELE64Target);
    RegisterTargetMachine<TCETargetMachine> X(TheTCELETarget);
    RegisterMCAsmInfo<TCEMCAsmInfo> Z(TheTCETarget);
    RegisterMCAsmInfo<TCEMCAsmInfo> V0(TheTCELE64Target);
    RegisterMCAsmInfo<TCEMCAsmInfo> V(TheTCELETarget);
    TargetRegistry::RegisterMCInstPrinter(TheTCETarget, dummyInstrPrinterCtor);
    TargetRegistry::RegisterMCInstPrinter(
        TheTCELETarget, dummyInstrPrinterCtor);
    TargetRegistry::RegisterMCInstPrinter(
        TheTCELE64Target, dummyInstrPrinterCtor);
}
References dummyInstrPrinterCtor(), llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by LLVMBackend::compile().