OpenASIP: TCETargetMachine.cc File Reference
TCETargetMachine.cc File Reference
#include "CompilerWarnings.hh"
#include "tce_config.h"
#include "llvm/IR/PassManager.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/ADT/APFloat.h"
#include "TCEStubTargetMachine.hh"
#include "TCETargetMachine.hh"
#include "TCEMCAsmInfo.hh"
#include "LLVMPOMBuilder.hh"
#include "PluginTools.hh"
#include "MathTools.hh"
#include "FileSystem.hh"
#include "ADFSerializer.hh"
#include "Conversion.hh"
#include "MachineInfo.hh"
#include "MachineConnectivityCheck.hh"
#include "Machine.hh"
#include "ImmediateAnalyzer.hh"
#include "ImmInfo.hh"
#include <llvm/Transforms/Scalar.h>
#include <iostream>
#include "LLVMTCECmdLineOptions.hh"
Classes
class DummyInstPrinter
Functions
Pass * createLowerMissingInstructionsPass (const TTAMachine::Machine &mach)
Pass * createLinkBitcodePass (Module &inputCode)
Pass * createProgramPartitionerPass (std::string partitioningStrategy)
Pass * createInstructionPatternAnalyzer ()
MCInstPrinter * dummyInstrPrinterCtor (const Triple &, unsigned, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void LLVMInitializeTCETarget ()
Function Documentation
createInstructionPatternAnalyzer()
Pass * createInstructionPatternAnalyzer ()
Definition at line 55 of file InstructionPatternAnalyzer.cc.
{
    return new InstructionPatternAnalyzer();
}
createLinkBitcodePass()
Pass * createLinkBitcodePass (Module & inputCode)
Definition at line 98 of file LinkBitcode.cc.
{
    return new LinkBitcode(input);
}
Referenced by llvm::TCEPassConfig::addPreISel().
createLowerMissingInstructionsPass()
Pass * createLowerMissingInstructionsPass (const TTAMachine::Machine & mach)
Definition at line 147 of file LowerMissingInstructions.cc.
{
    return new LowerMissingInstructions(mach);
}
Referenced by llvm::TCEPassConfig::addPreISel().
createProgramPartitionerPass()
Pass * createProgramPartitionerPass (std::string partitioningStrategy)
dummyInstrPrinterCtor()
MCInstPrinter * dummyInstrPrinterCtor (const Triple & , unsigned , const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 112 of file TCETargetMachine.cc.
{
    return new DummyInstPrinter(MAI, MII, MRI);
}
Referenced by LLVMInitializeTCETarget().
LLVMInitializeTCETarget()
void LLVMInitializeTCETarget ()
Definition at line 121 of file TCETargetMachine.cc.
{
    RegisterTargetMachine<TCETargetMachine> Y(TheTCETarget);
    RegisterTargetMachine<TCETargetMachine> X0(TheTCELE64Target);
    RegisterTargetMachine<TCETargetMachine> X(TheTCELETarget);
    RegisterMCAsmInfo<TCEMCAsmInfo> Z(TheTCETarget);
    RegisterMCAsmInfo<TCEMCAsmInfo> V0(TheTCELE64Target);
    RegisterMCAsmInfo<TCEMCAsmInfo> V(TheTCELETarget);
    TargetRegistry::RegisterMCInstPrinter(TheTCETarget, dummyInstrPrinterCtor);
    TargetRegistry::RegisterMCInstPrinter(
        TheTCELETarget, dummyInstrPrinterCtor);
    TargetRegistry::RegisterMCInstPrinter(
        TheTCELE64Target, dummyInstrPrinterCtor);
}
References dummyInstrPrinterCtor(), llvm::TheTCELE64Target, llvm::TheTCELETarget, llvm::TheTCETarget, and X().
Referenced by LLVMBackend::compile().