OpenASIP: TDGen.cc File Reference
TDGen.cc File Reference
#include <fstream>
#include <algorithm>
#include "TDGen.hh"
#include "Machine.hh"
#include "ADFSerializer.hh"
#include "ControlUnit.hh"
#include "Operation.hh"
#include "HWOperation.hh"
#include "FUPort.hh"
#include "Conversion.hh"
#include "MachineConnectivityCheck.hh"
#include "ImmediateAnalyzer.hh"
#include "ImmInfo.hh"
#include "Bus.hh"
#include "Guard.hh"
#include "StringTools.hh"
#include "OperationPool.hh"
#include "OperationNode.hh"
#include "TerminalNode.hh"
#include "ConstantNode.hh"
#include "OperationDAG.hh"
#include "OperationDAGEdge.hh"
#include "OperationDAGSelector.hh"
#include "TCEString.hh"
#include "Operand.hh"
#include "Application.hh"
#include "LLVMBackend.hh"
#include "MathTools.hh"
#include "tce_config.h"
#include "LLVMTCECmdLineOptions.hh"
#include "MachineInfo.hh"
#include "boost/assign.hpp"
Functions
bool numbersToAscending (const TCEString &lhs, const TCEString &rhs)
char regOperandCharToImmOperandChar (char c)
Variables
static const unsigned REG_RENAMER_PART = 0
Function Documentation
numbersToAscending()
bool numbersToAscending (const TCEString & lhs, const TCEString & rhs)
Custom comparator that orders operation names correctly number-wise.
For instance, in an std::set operation names are ordered followingly: ADD32X16, ADD32X4, ADD32X8, XOR1024, XOR512, XOR64
This function corrects the operation name order to be the following: ADD32X4, ADD32X8, ADD32X16, XOR64, XOR512, XOR1024
Definition at line 292 of file TDGen.cc.
{
    size_t lhsI = lhs.length() - 1;
    size_t rhsI = rhs.length() - 1;
    // Reverse operation name to the position where the last number begins.
    while (lhsI > 0 && std::isdigit(lhs[lhsI])) --lhsI;
    while (rhsI > 0 && std::isdigit(rhs[rhsI])) --rhsI;
    // Make sure both strings contain a number.
    if (lhsI > 0 && lhsI != lhs.length() - 1 && rhsI > 0 &&
        rhsI != rhs.length() - 1) {
        // The string part before the number must match between both names.
        if (lhs.substr(0, lhsI + 1) == rhs.substr(0, rhsI + 1)) {
            // Make the smaller number precede the larger one.
            try {
                int lhsNumber = Conversion::toInt(lhs.substr(lhsI + 1));
                int rhsNumber = Conversion::toInt(rhs.substr(rhsI + 1));
                return lhsNumber < rhsNumber;
            } catch (const NumberFormatException& e) {
                abortWithError(e.errorMessage());
            }
        }
    }
    // Basic comparison for std::string.
    return lhs < rhs;
}
References abortWithError, Exception::errorMessage(), and Conversion::toInt().
regOperandCharToImmOperandChar()
char regOperandCharToImmOperandChar (char c)
Definition at line 4491 of file TDGen.cc.
{
    switch(c) {
    case TDGen::OT_REG_LONG:
        return TDGen::OT_IMM_LONG;
    case TDGen::OT_REG_INT:
        return TDGen::OT_IMM_INT;
    case TDGen::OT_REG_BOOL:
        return TDGen::OT_IMM_BOOL;
    case TDGen::OT_REG_FP:
        return TDGen::OT_IMM_FP;
    case TDGen::OT_REG_HFP:
        return TDGen::OT_IMM_HFP;
    default:
        return 0;
    }
}
References TDGen::OT_IMM_BOOL, TDGen::OT_IMM_FP, TDGen::OT_IMM_HFP, TDGen::OT_IMM_INT, TDGen::OT_IMM_LONG, TDGen::OT_REG_BOOL, TDGen::OT_REG_FP, TDGen::OT_REG_HFP, TDGen::OT_REG_INT, and TDGen::OT_REG_LONG.
Referenced by TDGen::writeOperationDefs().
Variable Documentation
REG_RENAMER_PART
const unsigned REG_RENAMER_PART = 0 static
Definition at line 332 of file TDGen.cc.
Referenced by TDGen::analyzeRegisters().