OpenASIP: TestOsal.cc File Reference
TestOsal.cc File Reference
#include <iostream>
#include "TestOsal.hh"
#include "Operation.hh"
#include "Conversion.hh"
#include "SimValue.hh"
#include "Application.hh"
#include "LineReader.hh"
#include "LineReaderFactory.hh"
#include "CmdHelp.hh"
#include "StringTools.hh"
#include "InterpreterContext.hh"
#include "OperationSimulator.hh"
#include "IdealSRAM.hh"
#include "BaseType.hh"
#include "TCEString.hh"
#include "tce_config.h"
#include "OperationBehavior.hh"
#include "OperationPool.hh"
Functions
void executeCommand (OsalInterpreter &interpreter, string command)
int main (int argc, char *argv[])
Detailed Description
Implementation of test_osal.
Author
Jussi Nyk채nen 2004 (nykanen-no.spam-cs.tut.fi)
Pekka J채채skel채inen 2005 (pjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file TestOsal.cc.
Function Documentation
executeCommand()
void executeCommand (OsalInterpreter & interpreter, string command)
Executes given command with interpreter.
Parameters
interpreter Interpreter which executes the command.
command The command to be executed.
print True, if result is printed.
Definition at line 1039 of file TestOsal.cc.
{
    bool succeeded = interpreter.interpret(command);
    if (interpreter.result() != "") {
        if (!succeeded) {
            cout << "Error: ";
        }
        cout << interpreter.result() << endl;
    }
}
References SimpleScriptInterpreter::interpret(), and ScriptInterpreter::result().
Referenced by main().
main()
int main (int argc, char * argv[])
Main program.
Definition at line 942 of file TestOsal.cc.
{
    OsalCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& i) {
        cerr << i.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    OsalInterpreter interpreter;
    LineReader* reader = LineReaderFactory::lineReader();
    TesterContext context;
    CmdTrigger* trigger = new CmdTrigger();
    CmdHelp* help = new CmdHelp();
    CmdReset* reset = new CmdReset();
    CmdOutput* output = new CmdOutput();
    CmdQuit* quit = new CmdQuit();
    CmdRegister* reg = new CmdRegister();
    CmdMem* mem = new CmdMem();
    CmdAdvanceClock* clock = new CmdAdvanceClock();
    interpreter.initialize(argc, argv, &context, reader);
    interpreter.addCustomCommand(trigger);
    interpreter.addCustomCommand(help);
    interpreter.addCustomCommand(reset);
    interpreter.addCustomCommand(output);
    interpreter.addCustomCommand(quit);
    interpreter.addCustomCommand(reg);
    interpreter.addCustomCommand(mem);
    interpreter.addCustomCommand(clock);
    reader->initialize(">> ");
    // memory is 64k bytes
    // TODO: what endianess
    IdealSRAM* memory = new IdealSRAM(0, 65535, 8, false);
    context.operationContext().setMemory(memory);
    if (options.numberOfArguments() > 0) {
        // batch mode
        string command = "trigger ";
        for (int i = 1; i <= options.numberOfArguments(); i++) {
            string token = options.argument(i);
            if (token.substr(token.size() - 1) == ";") {
                // an end of the command
                command += token.substr(0, token.size() - 1);
                executeCommand(interpreter, command);
                command = "trigger ";
            } else {
                command += token + " ";
            }
        }
        if (command != "") {
        executeCommand(interpreter, command);
        }
    } else {
        // interactive mode
        string command = "";
        InterpreterContext& interpCont = interpreter.context();
        TesterContext& testCont = *dynamic_cast<TesterContext*>(&interpCont);
        while (testCont.cont()) {
            try {
                command = reader->readLine();
            } catch (const EndOfFile&) {
                interpreter.interpret("quit\n");
                break;
            }
            command = StringTools::trim(command);
            if (command == "") {
                continue;
            }
            if (command.find("!") == string::npos) {
                command = "trigger " + command;
            } else {
                command = command.substr(1, command.length());
            }
            executeCommand(interpreter, command);
        }
    }
    delete reader;
    delete memory;
    interpreter.finalize();
    return EXIT_SUCCESS;
}
References ScriptInterpreter::addCustomCommand(), CmdLineParser::argument(), TesterContext::cont(), SimpleScriptInterpreter::context(), Exception::errorMessage(), executeCommand(), ScriptInterpreter::finalize(), SimpleScriptInterpreter::initialize(), LineReader::initialize(), SimpleScriptInterpreter::interpret(), LineReaderFactory::lineReader(), CmdLineParser::numberOfArguments(), TesterContext::operationContext(), options, CmdLineOptions::parse(), LineReader::readLine(), OperationContext::setMemory(), and StringTools::trim().