OpenASIP: TestHDB.cc File Reference
TestHDB.cc File Reference
#include <cstdlib>
#include <iostream>
#include <string>
#include "HDBTester.hh"
#include "TestHDBCmdLineOptions.hh"
Functions
int main (int argc, char *argv[])
Variables
const string GHDL_SIM = "ghdl"
const string VSIM_SIM = "modelsim"
Detailed Description
HDB tester utility program
Author
Otto Esko 2010 (otto.esko-no.spam-tut.fi)
Note
rating: red
Definition in file TestHDB.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 43 of file TestHDB.cc.
{
    TestHDBCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& exception) {
        std::cerr << exception.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    string hdbFile = "";
    if (options.numberOfArguments() < 1) {
        std::cerr << "HDB file was not given" << std::endl;
        options.printHelp();
        return EXIT_FAILURE;
    } else if (options.numberOfArguments() > 1) {
        std::cerr << "Illegal arguments" << std::endl;
        options.printHelp();
        return EXIT_FAILURE;
    } else {
        hdbFile = options.hdbFile();
    }
    string simulator = options.vhdlSim();
    VhdlSim sim = SIM_GHDL;
    if (simulator == VSIM_SIM) {
        sim = SIM_MODELSIM;
    } else if (simulator == GHDL_SIM || simulator.empty()) {
        sim = SIM_GHDL;
    } else {
        std::cerr << "Unknown HDL simulator" << simulator << std::endl;
        options.printHelp();
        return EXIT_FAILURE;
    }
    bool verbose = options.verbose();
    bool leaveDirty = options.leaveDirty();
    HDBTester tester(std::cout, std::cerr, sim, verbose, leaveDirty);
    bool testAll = true;
    if (options.isFUEntryIDGiven()) {
        testAll = false;
        int entryID = options.fuEntryID();
        if (!tester.testOneFU(hdbFile, entryID)) {
            return EXIT_FAILURE;
        }
    }
    if (options.isRFEntryIDGiven()) {
        testAll = false;
        int entryID = options.rfEntryID();
        if (!tester.testOneRF(hdbFile, entryID)) {
            return EXIT_FAILURE;
        }
    }
    if (testAll) {
        if (!tester.testAllEntries(hdbFile)) {
            return EXIT_FAILURE;
        }
    }
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), GHDL_SIM, CmdLineParser::numberOfArguments(), options, CmdLineOptions::parse(), MachInfoCmdLineOptions::printHelp(), SIM_GHDL, SIM_MODELSIM, HDBTester::testAllEntries(), HDBTester::testOneFU(), HDBTester::testOneRF(), and VSIM_SIM.
Variable Documentation
GHDL_SIM
const string GHDL_SIM = "ghdl"
Definition at line 40 of file TestHDB.cc.
Referenced by main().
VSIM_SIM
const string VSIM_SIM = "modelsim"
Definition at line 41 of file TestHDB.cc.
Referenced by main().