OpenASIP: TTASimTandem.cc File Reference
TTASimTandem.cc File Reference
#include <iostream>
#include <algorithm>
#include <boost/format.hpp>
#include "Application.hh"
#include "Machine.hh"
#include "Program.hh"
#include "SimulatorFrontend.hh"
#include "RegisterFile.hh"
#include "SimValue.hh"
#include "POMDisassembler.hh"
#include "DisassemblyFUPort.hh"
#include "Instruction.hh"
#include "Procedure.hh"
Functions
void tandemSimulate (TTAMachine::Machine &machine, TTAProgram::Program &program)
int main (int argc, char *argv[])
Detailed Description
Implementation of a simulator that runs both compiled simulation and the interpretive (debugging) simulation in parallel and compares the execution to detect differences in the simulations, which indicate there's a missimulation bug in one or both of the engines.
Author
Pekka Jääskeläinen 2009 (pjaaskel-no.spam-cs.tut.fi)
Note
rating: red
Definition in file TTASimTandem.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 123 of file TTASimTandem.cc.
{
    Application::initialize();
    if (argc < 3) {
        std::cerr << "usage: ttasim-tandem machine.adf program.tpef";
    }
    try {
        TTAMachine::Machine* machine =
            TTAMachine::Machine::loadFromADF(argv[1]);
        TTAProgram::Program* program =
            TTAProgram::Program::loadFromTPEF(argv[2], *machine);
        tandemSimulate(*machine, *program);
        delete machine; machine = NULL;
        delete program; program = NULL;
    } catch (const Exception& e) {
        std::cerr << e.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), Application::initialize(), TTAMachine::Machine::loadFromADF(), TTAProgram::Program::loadFromTPEF(), machine, program, and tandemSimulate().
tandemSimulate()
void tandemSimulate (TTAMachine::Machine & machine, TTAProgram::Program & program)
Simulates the given program+machine in "tandem" with the two simulation engines.
Definition at line 55 of file TTASimTandem.cc.
{
    // initialize both simulation engines
    SimulatorFrontend interp(SimulatorFrontend::SIM_NORMAL);
    interp.loadMachine(machine);
    interp.loadProgram(program);
    SimulatorFrontend compiled(SimulatorFrontend::SIM_COMPILED);
    // leave the compile simulation engine files at /tmp
    compiled.setCompiledSimulationLeaveDirty(true);
    compiled.loadMachine(machine);
    compiled.loadProgram(program);
    // reduce startup time by using dynamic compilation of the simulation
    // engine
    compiled.setStaticCompilation(false);
    assert(compiled.isSimulationInitialized());
    assert(interp.isSimulationInitialized());
    ClockCycleCount simulatedCycles = 0;
    while (!compiled.hasSimulationEnded()) {
        ClockCycleCount stepping;
        try {
            compiled.step(1);
            // the compiled simulator compiled BB at a time so we need to
            // ask it how many cycle to advance the cycle level interp. engine
            // to get to the same position in the simulation
            stepping =
                compiled.cycleCount() - simulatedCycles;
            interp.step(stepping);
            simulatedCycles += stepping;
        } catch (const Exception& e) {
            std::cerr << "Simulation error: " << e.errorMessage() << std::endl;
            return;
        }
        if (!compiled.compareState(interp, &std::cerr))
            return;
        // print out the cycle count after simulating at least 1M cycles
        if (simulatedCycles / 1000000 > (simulatedCycles - stepping) / 1000000)
            std::cout
                << "simulated " << simulatedCycles << " cycles" << std::endl;
    }
    std::cout
        << "stop reasons:" << std::endl
        << "* compiled engine:" << std::endl;
    for (unsigned i = 0; i < compiled.stopReasonCount(); ++i) {
        std::cout << "** " << compiled.stopReason(i) << std::endl;
    }
    std::cout
        << "* interp. engine:" << std::endl;
    for (unsigned i = 0; i < interp.stopReasonCount(); ++i) {
        std::cout << "** " << interp.stopReason(i) << std::endl;
    }
}
References assert, SimulatorFrontend::compareState(), SimulatorFrontend::cycleCount(), Exception::errorMessage(), SimulatorFrontend::hasSimulationEnded(), SimulatorFrontend::isSimulationInitialized(), SimulatorFrontend::loadMachine(), SimulatorFrontend::loadProgram(), machine, program, SimulatorFrontend::setCompiledSimulationLeaveDirty(), SimulatorFrontend::setStaticCompilation(), SimulatorFrontend::SIM_COMPILED, SimulatorFrontend::SIM_NORMAL, SimulatorFrontend::step(), SimulatorFrontend::stopReason(), and SimulatorFrontend::stopReasonCount().
Referenced by main().