OpenASIP: TTAUnitTester.hh File Reference
TTAUnitTester.hh File Reference
#include <string>
#include "ImplementationTester.hh"
Namespaces
namespace TTAMachine
namespace IDF
Functions
TTAMachine::Machine * readAdf (std::string adfName)
IDF::MachineImplementation * readIdf (std::string idfName)
bool validateIdf (const IDF::MachineImplementation &idf, const TTAMachine::Machine &machine)
bool testUnits (const IDF::MachineImplementation &idf, VhdlSim simulator, bool verbose, bool leaveDirty)
Detailed Description
Declaration of TTAUnitTester utility program
Author
Otto Esko 2010 (otto.esko-no.spam-tut.fi)
Note
rating: red
Definition in file TTAUnitTester.hh.
Function Documentation
readAdf()
TTAMachine::Machine * readAdf (std::string adfName)
Definition at line 116 of file TTAUnitTester.cc.
{
    ADFSerializer reader;
    reader.setSourceFile(adfName);
    TTAMachine::Machine* mach = NULL;
    try {
        mach = reader.readMachine();
    } catch (Exception& e) {
        std::cerr << "Failed to load ADF file " << adfName << ": "
                  << e.errorMessage() << std::endl;
        return NULL;
    }
    return mach;
}
References Exception::errorMessage(), ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
Referenced by main().
readIdf()
IDF::MachineImplementation * readIdf (std::string idfName)
Definition at line 133 of file TTAUnitTester.cc.
{
    IDF::IDFSerializer reader;
    reader.setSourceFile(idfName);
    IDF::MachineImplementation* implementation = NULL;
    try {
        implementation = reader.readMachineImplementation();
    } catch (Exception& e) {
        std::cerr << "Failed to load IDF file " << idfName << ": "
                  << e.errorMessage() << std::endl;
        return NULL;
    }
    return implementation;
}
References Exception::errorMessage(), implementation, IDF::IDFSerializer::readMachineImplementation(), and XMLSerializer::setSourceFile().
Referenced by main().
testUnits()
bool testUnits (const IDF::MachineImplementation & idf, VhdlSim simulator, bool verbose, bool leaveDirty)
Definition at line 167 of file TTAUnitTester.cc.
{
    HDBTester tester(std::cout, std::cerr, simulator, verbose, leaveDirty);
    bool allPassed = true;
    for (int i = 0; i < idf.fuImplementationCount(); i++) {
        IDF::UnitImplementationLocation* unit = &idf.fuImplementation(i);
        string hdb = unit->hdbFile();
        int entryId = unit->id();
        if (!tester.testOneFU(hdb, entryId)) {
            allPassed = false;
        }
    }
    for (int i = 0; i < idf.rfImplementationCount(); i++) {
        IDF::UnitImplementationLocation* unit = &idf.rfImplementation(i);
        string hdb = unit->hdbFile();
        int entryId = unit->id();
        if (!tester.testOneRF(hdb, entryId)) {
            allPassed = false;
        }
    }
    return allPassed;
}
References IDF::MachineImplementation::fuImplementation(), IDF::MachineImplementation::fuImplementationCount(), IDF::UnitImplementationLocation::hdbFile(), IDF::UnitImplementationLocation::id(), IDF::MachineImplementation::rfImplementation(), IDF::MachineImplementation::rfImplementationCount(), HDBTester::testOneFU(), and HDBTester::testOneRF().
Referenced by main().
validateIdf()
bool validateIdf (const IDF::MachineImplementation & idf, const TTAMachine::Machine & machine)
Definition at line 150 of file TTAUnitTester.cc.
{
    IDFValidator validator(idf, machine);
    bool success = validator.validate();
    if (!success) {
        for (int i = 0; i < validator.errorCount(); i++) {
            std::cerr << validator.errorMessage(i) << std::endl;
        }
    }
    return success;
}
References IDFValidator::errorCount(), IDFValidator::errorMessage(), machine, and IDFValidator::validate().
Referenced by main().