OpenASIP: TTAUnitTester.cc File Reference
TTAUnitTester.cc File Reference
#include <cstdlib>
#include <string>
#include <vector>
#include "MachineImplementation.hh"
#include "Machine.hh"
#include "ADFSerializer.hh"
#include "IDFSerializer.hh"
#include "IDFValidator.hh"
#include "TTAUnitTester.hh"
#include "HDBTester.hh"
#include "Exception.hh"
#include "UnitImplementationLocation.hh"
#include "TTAUnitTesterCmdLineOptions.hh"
Functions
int main (int argc, char *argv[])
TTAMachine::Machine * readAdf (std::string adfName)
IDF::MachineImplementation * readIdf (std::string idfName)
bool validateIdf (const IDF::MachineImplementation &idf, const TTAMachine::Machine &machine)
bool testUnits (const IDF::MachineImplementation &idf, VhdlSim simulator, bool verbose, bool leaveDirty)
Detailed Description
Implementation of TTAUnitTester utility program
Author
Otto Esko 2010 (otto.esko-no.spam-tut.fi)
Note
rating: red
Definition in file TTAUnitTester.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 48 of file TTAUnitTester.cc.
{
    TTAUnitTesterCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& exception) {
        std::cerr << exception.errorMessage() << std::endl;
        return EXIT_FAILURE;
    }
    string idfFile = "";
    if (options.numberOfArguments() == 0) {
        std::cerr << "IDF file was not given" << std::endl;
        options.printHelp();
        return EXIT_FAILURE;
    } else if (options.numberOfArguments() > 1) {
        std::cerr << "Illegal arguments" << std::endl;
        options.printHelp();
        return EXIT_FAILURE;
    } else {
        idfFile = options.idfFileName();
    }
    string adfFile = options.adfFileName();
    string sim = options.vhdlSim();
    VhdlSim simulator = SIM_GHDL;
    if (sim == "modelsim") {
        simulator = SIM_MODELSIM;
    } else {
        simulator = SIM_GHDL;
    }
    bool verbose = options.verbose();
    bool leaveDirty = options.leaveDirty();
    IDF::MachineImplementation* idf = readIdf(idfFile);
    if (!idf) {
        return EXIT_FAILURE;
    }
    // validate idf if adf was given
    if (!adfFile.empty()) {
         TTAMachine::Machine* mach = readAdf(adfFile);
        if (!mach) {
            return EXIT_FAILURE;
        }
        if (!validateIdf(*idf, *mach)) {
            delete(mach);
            delete(idf);
            return EXIT_FAILURE;
        }
        delete(mach);
    }
    if (!testUnits(*idf, simulator, verbose, leaveDirty)) {
        delete(idf);
        return EXIT_FAILURE;
    }
    delete(idf);
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), CmdLineParser::numberOfArguments(), options, CmdLineOptions::parse(), MachInfoCmdLineOptions::printHelp(), readAdf(), readIdf(), SIM_GHDL, SIM_MODELSIM, testUnits(), and validateIdf().
readAdf()
TTAMachine::Machine * readAdf (std::string adfName)
Definition at line 116 of file TTAUnitTester.cc.
{
    ADFSerializer reader;
    reader.setSourceFile(adfName);
    TTAMachine::Machine* mach = NULL;
    try {
        mach = reader.readMachine();
    } catch (Exception& e) {
        std::cerr << "Failed to load ADF file " << adfName << ": "
                  << e.errorMessage() << std::endl;
        return NULL;
    }
    return mach;
}
References Exception::errorMessage(), ADFSerializer::readMachine(), and XMLSerializer::setSourceFile().
Referenced by main().
readIdf()
IDF::MachineImplementation * readIdf (std::string idfName)
Definition at line 133 of file TTAUnitTester.cc.
{
    IDF::IDFSerializer reader;
    reader.setSourceFile(idfName);
    IDF::MachineImplementation* implementation = NULL;
    try {
        implementation = reader.readMachineImplementation();
    } catch (Exception& e) {
        std::cerr << "Failed to load IDF file " << idfName << ": "
                  << e.errorMessage() << std::endl;
        return NULL;
    }
    return implementation;
}
References Exception::errorMessage(), implementation, IDF::IDFSerializer::readMachineImplementation(), and XMLSerializer::setSourceFile().
Referenced by main().
testUnits()
bool testUnits (const IDF::MachineImplementation & idf, VhdlSim simulator, bool verbose, bool leaveDirty)
Definition at line 167 of file TTAUnitTester.cc.
{
    HDBTester tester(std::cout, std::cerr, simulator, verbose, leaveDirty);
    bool allPassed = true;
    for (int i = 0; i < idf.fuImplementationCount(); i++) {
        IDF::UnitImplementationLocation* unit = &idf.fuImplementation(i);
        string hdb = unit->hdbFile();
        int entryId = unit->id();
        if (!tester.testOneFU(hdb, entryId)) {
            allPassed = false;
        }
    }
    for (int i = 0; i < idf.rfImplementationCount(); i++) {
        IDF::UnitImplementationLocation* unit = &idf.rfImplementation(i);
        string hdb = unit->hdbFile();
        int entryId = unit->id();
        if (!tester.testOneRF(hdb, entryId)) {
            allPassed = false;
        }
    }
    return allPassed;
}
References IDF::MachineImplementation::fuImplementation(), IDF::MachineImplementation::fuImplementationCount(), IDF::UnitImplementationLocation::hdbFile(), IDF::UnitImplementationLocation::id(), IDF::MachineImplementation::rfImplementation(), IDF::MachineImplementation::rfImplementationCount(), HDBTester::testOneFU(), and HDBTester::testOneRF().
Referenced by main().
validateIdf()
bool validateIdf (const IDF::MachineImplementation & idf, const TTAMachine::Machine & machine)
Definition at line 150 of file TTAUnitTester.cc.
{
    IDFValidator validator(idf, machine);
    bool success = validator.validate();
    if (!success) {
        for (int i = 0; i < validator.errorCount(); i++) {
            std::cerr << validator.errorMessage(i) << std::endl;
        }
    }
    return success;
}
References IDFValidator::errorCount(), IDFValidator::errorMessage(), machine, and IDFValidator::validate().
Referenced by main().