OpenASIP: ViewBEM.cc File Reference
ViewBEM.cc File Reference
#include <iostream>
#include <string>
#include "BEMViewerCmdLineOptions.hh"
#include "BEMSerializer.hh"
#include "BinaryEncoding.hh"
#include "ImmediateControlField.hh"
#include "MoveSlot.hh"
#include "ImmediateSlotField.hh"
#include "LImmDstRegisterField.hh"
#include "GuardField.hh"
#include "DestinationField.hh"
#include "SourceField.hh"
#include "GPRGuardEncoding.hh"
#include "FUGuardEncoding.hh"
#include "UnconditionalGuardEncoding.hh"
#include "ImmediateEncoding.hh"
#include "BridgeEncoding.hh"
#include "NOPEncoding.hh"
#include "SocketEncoding.hh"
#include "SocketCodeTable.hh"
#include "FUPortCode.hh"
#include "RFPortCode.hh"
#include "IUPortCode.hh"
#include "Conversion.hh"
#include "FileSystem.hh"
Functions
static void printBEMInfo (const BinaryEncoding &bem, const std::string &bemFile)
static void printInstructionLayout (const BinaryEncoding &bem)
static void printImmediateControlField (const BinaryEncoding &bem)
static void printLImmDstRegisterField (const LImmDstRegisterField &field)
static void printMoveSlot (const MoveSlot &moveSlot)
static void printMoveSlotLayout (const MoveSlot &moveSlot)
static void printGuardFieldEncodings (const MoveSlot &moveSlot)
static void printSlotFieldEncodings (const SlotField &slotField)
static string portCodeBits (const PortCode &code)
static string portCodeDescription (const RFPortCode &code)
static string portCodeDescription (const IUPortCode &code)
static string portCodeDescription (const FUPortCode &code)
static void printSourceFieldEncodings (const MoveSlot &moveSlot)
static void printDestinationFieldEncodings (const MoveSlot &moveSlot)
static void printSeparator ()
static void printPattern (const std::string &pattern, int times)
int main (int argc, char *argv[])
Detailed Description
Implements the viewbem application which prints out human readable information of given binary encoding map.
Author
Lasse Laasonen 2006 (lasse.laasonen-no.spam-tut.fi)
Note
rating: red
Definition in file ViewBEM.cc.
Function Documentation
main()
int main (int argc, char * argv[])
The main function.
Definition at line 104 of file ViewBEM.cc.
{
    BEMViewerCmdLineOptions options;
    try {
        options.parse(argv, argc);
    } catch (ParserStopRequest const&) {
        return EXIT_SUCCESS;
    } catch (const IllegalCommandLine& e) {
        cerr << e.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    string bemFile = options.bemFile();
    if (bemFile == "") {
        options.printHelp();
        return EXIT_FAILURE;
    }
    BEMSerializer serializer;
    serializer.setSourceFile(bemFile);
    BinaryEncoding* bem;
    try {
        bem = serializer.readBinaryEncoding();
    } catch (const Exception& e) {
        cerr << e.errorMessage() << endl;
        return EXIT_FAILURE;
    }
    printBEMInfo(*bem, bemFile);
    delete bem;
    return EXIT_SUCCESS;
}
References Exception::errorMessage(), options, CmdLineOptions::parse(), printBEMInfo(), MachInfoCmdLineOptions::printHelp(), BEMSerializer::readBinaryEncoding(), and XMLSerializer::setSourceFile().
portCodeBits()
static string portCodeBits (const PortCode & code) static
Returns the bit string of the given port code.
Parameters
code The port code.
Definition at line 506 of file ViewBEM.cc.
{
    string bits;
    if (code.hasEncoding() && code.encodingWidth()) {
        bits += Conversion::toBinary(
            code.encoding(), code.encodingWidth());
    }
    int unusedBits = code.parent()->width() - code.width();
    for (int i = 0; i < unusedBits; i++) {
        bits.append("X");
    }
    for (int i = 0; i < code.indexWidth(); i++) {
        bits.append("R");
    }
    return bits;
}
References PortCode::encoding(), PortCode::encodingWidth(), PortCode::hasEncoding(), PortCode::indexWidth(), PortCode::parent(), Conversion::toBinary(), PortCode::width(), and SocketCodeTable::width().
Referenced by printSlotFieldEncodings().
portCodeDescription() [1/3]
static string portCodeDescription (const FUPortCode & code) static
Returns description of the given port code.
Parameters
code The port code.
Definition at line 551 of file ViewBEM.cc.
{
    string desc = "FU port: " + code.unitName() + ", " + code.portName();
    if (code.hasOperation()) {
        desc.append(", " + code.operationName());
    }
    return desc;
}
References FUPortCode::hasOperation(), FUPortCode::operationName(), FUPortCode::portName(), and PortCode::unitName().
portCodeDescription() [2/3]
static string portCodeDescription (const IUPortCode & code) static
Returns description of the given port code.
Parameters
code The port code.
Definition at line 540 of file ViewBEM.cc.
{
    return "IU: " + code.unitName();
}
References PortCode::unitName().
portCodeDescription() [3/3]
static string portCodeDescription (const RFPortCode & code) static
Returns description of the given port code.
Parameters
code The port code.
Definition at line 529 of file ViewBEM.cc.
{
    return "RF: " + code.unitName();
}
References PortCode::unitName().
Referenced by printSlotFieldEncodings().
printBEMInfo()
static void printBEMInfo (const BinaryEncoding & bem, const std::string & bemFile) static
Prints information of BEM to standard output.
Parameters
bem The BEM.
bemFile Name of the BEM file.
Definition at line 145 of file ViewBEM.cc.
{
    cout << "Binary Encoding Map: " << FileSystem::fileOfPath(bemFile)
         << endl << endl;
    cout << "X = unused bit" << endl;
    cout << "I = immediate bit" << endl;
    cout << "S = socket code bit" << endl;
    cout << "R = register index bit" << endl << endl;
    cout << "Total instruction width: " << bem.width() << endl << endl;
    printInstructionLayout(bem);
    cout << endl;
    printImmediateControlField(bem);
    cout << endl;
    for (int i = 0; i < bem.longImmDstRegisterFieldCount(); i++) {
        LImmDstRegisterField& field = bem.longImmDstRegisterField(i);
        printLImmDstRegisterField(field);
        cout << endl;
    }
    for (int i = 0; i < bem.moveSlotCount(); i++) {
        MoveSlot& slot = bem.moveSlot(i);
        printMoveSlot(slot);
        cout << endl;
    }
}
References FileSystem::fileOfPath(), BinaryEncoding::longImmDstRegisterField(), BinaryEncoding::longImmDstRegisterFieldCount(), BinaryEncoding::moveSlot(), BinaryEncoding::moveSlotCount(), printImmediateControlField(), printInstructionLayout(), printLImmDstRegisterField(), printMoveSlot(), and BinaryEncoding::width().
Referenced by main().
printDestinationFieldEncodings()
static void printDestinationFieldEncodings (const MoveSlot & moveSlot) static
Prints the encodings of the destination field of the given move slot.
Parameters
moveSlot The move slot.
Definition at line 622 of file ViewBEM.cc.
{
    if (!moveSlot.hasDestinationField()) {
        return;
    }
    DestinationField& dstField = moveSlot.destinationField();
    cout << "Destination field encodings:" << endl;
    printSlotFieldEncodings(dstField);
}
References MoveSlot::destinationField(), MoveSlot::hasDestinationField(), and printSlotFieldEncodings().
Referenced by printMoveSlot().
printGuardFieldEncodings()
static void printGuardFieldEncodings (const MoveSlot & moveSlot) static
Prints the encodings of the guard field of the given move slot.
Parameters
moveSlot The move slot.
Definition at line 327 of file ViewBEM.cc.
{
    if (!moveSlot.hasGuardField()) {
        return;
    }
    GuardField& grdField = moveSlot.guardField();
    int encodingWidth = grdField.width() - grdField.extraBits();
    string extraBits;
    for (int i = 0; i < grdField.extraBits(); i++) {
        extraBits.append("X");
    }
    cout << "Guard field encodings:" << endl;
    if (grdField.hasUnconditionalGuardEncoding(false)) {
        UnconditionalGuardEncoding& enc =
            grdField.unconditionalGuardEncoding(false);
        cout << extraBits
             << Conversion::toBinary(enc.encoding(), encodingWidth)
             << " : always-true" << endl;
    }
    if (grdField.hasUnconditionalGuardEncoding(true)) {
        UnconditionalGuardEncoding& enc =
            grdField.unconditionalGuardEncoding(true);
        cout << extraBits
             << Conversion::toBinary(enc.encoding(), encodingWidth)
             << " : always-false" << endl;
    }
    for (int i = 0; i < grdField.gprGuardEncodingCount(); i++) {
        GPRGuardEncoding& enc = grdField.gprGuardEncoding(i);
        cout << extraBits
             << Conversion::toBinary(enc.encoding(), encodingWidth)
             << " : ";
        if (enc.isGuardInverted()) {
            cout << "inverted ";
        } else {
            cout << "non-inverted ";
        }
        cout << "GPR " << enc.registerIndex() << " of RF "
             << enc.registerFile() << endl;
    }
    for (int i = 0; i < grdField.fuGuardEncodingCount(); i++) {
        FUGuardEncoding& enc = grdField.fuGuardEncoding(i);
        cout << extraBits
             << Conversion::toBinary(enc.encoding(), encodingWidth) << " : ";
        if (enc.isGuardInverted()) {
            cout << "inverted ";
        } else {
            cout << "non-inverted ";
        }
        cout << "port " << enc.port() << " of FU " << enc.functionUnit()
             << endl;
    }
}
References GuardEncoding::encoding(), InstructionField::extraBits(), GuardField::fuGuardEncoding(), GuardField::fuGuardEncodingCount(), FUGuardEncoding::functionUnit(), GuardField::gprGuardEncoding(), GuardField::gprGuardEncodingCount(), MoveSlot::guardField(), MoveSlot::hasGuardField(), GuardField::hasUnconditionalGuardEncoding(), GuardEncoding::isGuardInverted(), FUGuardEncoding::port(), GPRGuardEncoding::registerFile(), GPRGuardEncoding::registerIndex(), Conversion::toBinary(), GuardField::unconditionalGuardEncoding(), and GuardField::width().
Referenced by printMoveSlot().
printImmediateControlField()
static void printImmediateControlField (const BinaryEncoding & bem) static
Prints information of immediate control field of the given BEM.
Parameters
bem The BEM.
Definition at line 220 of file ViewBEM.cc.
{
    if (!bem.hasImmediateControlField()) {
        return;
    }
    ImmediateControlField& icField = bem.immediateControlField();
    printSeparator();
    cout << "Immediate Control Field" << endl << endl;
    cout << "Position: " << icField.bitPosition() << endl;
    cout << "Width: " << icField.width() << endl;
    cout << "Encodings:" << endl;
    int encodingWidth = icField.width() - icField.extraBits();
    string extraBits;
    for (int i = 0; i < icField.extraBits(); i++) {
        extraBits.append("X");
    }
    for (int i = 0; i < icField.templateCount(); i++) {
        string iTemp = icField.instructionTemplate(i);
        unsigned int encoding = icField.templateEncoding(iTemp);
        cout << extraBits << Conversion::toBinary(encoding, encodingWidth)
             << " : " << iTemp << endl;
    }
}
References InstructionField::bitPosition(), InstructionField::extraBits(), BinaryEncoding::hasImmediateControlField(), BinaryEncoding::immediateControlField(), ImmediateControlField::instructionTemplate(), printSeparator(), ImmediateControlField::templateCount(), ImmediateControlField::templateEncoding(), Conversion::toBinary(), and ImmediateControlField::width().
Referenced by printBEMInfo().
printInstructionLayout()
static void printInstructionLayout (const BinaryEncoding & bem) static
Prints the instruction layout of the given BEM.
Parameters
bem The BEM.
Definition at line 179 of file ViewBEM.cc.
{
    if (bem.childFieldCount() == 0) {
        return;
    }
    cout << "|";
    for (int i = bem.childFieldCount() - 1; i >= 0; i--) {
        InstructionField& field = bem.childField(i);
        ImmediateControlField* icField =
            dynamic_cast<ImmediateControlField*>(&field);
        MoveSlot* moveSlot = dynamic_cast<MoveSlot*>(&field);
        ImmediateSlotField* immSlot =
            dynamic_cast<ImmediateSlotField*>(&field);
        LImmDstRegisterField* dstRegField =
            dynamic_cast<LImmDstRegisterField*>(&field);
        if (icField != NULL) {
            cout << " limm cntrl: " << field.width();
        } else if (moveSlot != NULL) {
            cout << " move slot " << moveSlot->name() << ": "
                 << moveSlot->width();
        } else if (immSlot != NULL) {
            cout << " limm slot " << immSlot->name() << ": "
                 << immSlot->width();
        } else {
            assert(dstRegField != NULL);
            cout << " dst reg field: " << dstRegField->width();
        }
        cout << " |";
    }
    cout << endl;
}
References assert, BinaryEncoding::childField(), BinaryEncoding::childFieldCount(), ImmediateSlotField::name(), MoveSlot::name(), ImmediateSlotField::width(), LImmDstRegisterField::width(), MoveSlot::width(), and InstructionField::width().
Referenced by printBEMInfo().
printLImmDstRegisterField()
static void printLImmDstRegisterField (const LImmDstRegisterField & field) static
Prints information of the given long immediate destination register field.
Parameters
field The field.
Definition at line 254 of file ViewBEM.cc.
{
    printSeparator();
    cout << "Long Immediate Destination Register Field" << endl << endl;
    cout << "Position: " << field.bitPosition() << endl;
    cout << "Width: " << field.width() << endl << endl;
    cout << "Usage" << endl;
    for (int i = 0; i < field.instructionTemplateCount(); i++) {
        string iTemp = field.instructionTemplate(i);
        string iu = field.immediateUnit(iTemp);
        cout << iTemp << ": " << iu << endl;
    }
}
References InstructionField::bitPosition(), LImmDstRegisterField::immediateUnit(), LImmDstRegisterField::instructionTemplate(), LImmDstRegisterField::instructionTemplateCount(), printSeparator(), and LImmDstRegisterField::width().
Referenced by printBEMInfo().
printMoveSlot()
static void printMoveSlot (const MoveSlot & moveSlot) static
Prints information of the given move slot.
Parameters
moveSlot The move slot.
Definition at line 276 of file ViewBEM.cc.
{
    printSeparator();
    cout << "Move Slot: " << moveSlot.name() << endl << endl;
    cout << "Position: " << moveSlot.bitPosition() << endl;
    cout << "Width: " << moveSlot.width() << endl << endl;
    printMoveSlotLayout(moveSlot);
    cout << endl;
    printGuardFieldEncodings(moveSlot);
    cout << endl;
    printSourceFieldEncodings(moveSlot);
    cout << endl;
    printDestinationFieldEncodings(moveSlot);
}
References InstructionField::bitPosition(), MoveSlot::name(), printDestinationFieldEncodings(), printGuardFieldEncodings(), printMoveSlotLayout(), printSeparator(), printSourceFieldEncodings(), and MoveSlot::width().
Referenced by printBEMInfo().
printMoveSlotLayout()
static void printMoveSlotLayout (const MoveSlot & moveSlot) static
Prints the layout of the given move slot.
Parameters
moveSlot The move slot.
Definition at line 299 of file ViewBEM.cc.
{
    cout << "|";
    for (int i = moveSlot.childFieldCount() - 1; i >= 0; i--) {
        InstructionField& childField = moveSlot.childField(i);
        GuardField* grdField = dynamic_cast<GuardField*>(&childField);
        SourceField* srcField = dynamic_cast<SourceField*>(&childField);
        DestinationField* dstField =
            dynamic_cast<DestinationField*>(&childField);
        if (grdField != NULL) {
            cout << " grd field: " << grdField->width();
        } else if (srcField != NULL) {
            cout << " src field: " << srcField->width();
        } else {
            assert(dstField != NULL);
            cout << " dst field: " << dstField->width();
        }
        cout << " |";
    }
    cout << endl;
}
References assert, MoveSlot::childField(), MoveSlot::childFieldCount(), GuardField::width(), SlotField::width(), and SourceField::width().
Referenced by printMoveSlot().
printPattern()
static void printPattern (const std::string & pattern, int times) static
Prints the given pattern the given times.
Parameters
pattern The pattern.
times Times the pattern is written.
Definition at line 651 of file ViewBEM.cc.
{
    for (int i = 0; i < times; i++) {
        cout << pattern;
    }
}
Referenced by printSlotFieldEncodings(), and printSourceFieldEncodings().
printSeparator()
static void printSeparator () static
Prints the separator.
Definition at line 638 of file ViewBEM.cc.
                 {
    cout << "------------------------------------------------------------"
         << endl;
}
Referenced by printImmediateControlField(), printLImmDstRegisterField(), and printMoveSlot().
printSlotFieldEncodings()
static void printSlotFieldEncodings (const SlotField & slotField) static
Prints the socket and NOP encodings of the given slot field.
Parameters
slotField The source or destination field.
Definition at line 389 of file ViewBEM.cc.
{
    if (slotField.hasNoOperationEncoding()) {
        NOPEncoding& enc = slotField.noOperationEncoding();
        if (slotField.componentIDPosition() == BinaryEncoding::RIGHT) {
            printPattern("X", slotField.width() - enc.width());
            if (enc.width()) {
                cout << Conversion::toBinary(enc.encoding(), enc.width());
            }
        } else {
            printPattern("X", slotField.extraBits());
            if (enc.width()) {
                cout << Conversion::toBinary(enc.encoding(), enc.width());
            }
            printPattern(
                "X",
                slotField.width() - slotField.extraBits() - enc.width());
        }
        cout << " : NOP" << endl;
    }
    for (int i = 0; i < slotField.socketEncodingCount(); i++) {
        SocketEncoding& enc = slotField.socketEncoding(i);
        printPattern("X", slotField.extraBits());
        if (slotField.componentIDPosition() == BinaryEncoding::RIGHT) {
            if (enc.hasSocketCodes()) {
                SocketCodeTable& scTable = enc.socketCodes();
                printPattern("S", scTable.width());
                printPattern(
                    "X",
                    slotField.width() - slotField.extraBits() -
                    scTable.width() - enc.socketIDWidth());
            } else {
                printPattern(
                    "X",
                    slotField.width() - slotField.extraBits() -
                    enc.socketIDWidth());
            }
            if (enc.socketIDWidth()) {
                cout <<
                    Conversion::toBinary(enc.encoding(), enc.socketIDWidth());
            }
        } else {
            if (enc.socketIDWidth()) {
                cout <<
                    Conversion::toBinary(enc.encoding(), enc.socketIDWidth());
            }
            if (enc.hasSocketCodes()) {
                SocketCodeTable& scTable = enc.socketCodes();
                printPattern(
                    "X",
                    slotField.width() - slotField.extraBits() -
                    scTable.width() - enc.socketIDWidth());
                printPattern("S", scTable.width());
            } else {
                printPattern(
                    "X",
                    slotField.width() - slotField.extraBits() - enc.width());
            }
        }
        cout << " : socket " << enc.socketName() << endl;
        if (enc.hasSocketCodes()) {
            SocketCodeTable& scTable = enc.socketCodes();
            if (slotField.componentIDPosition() == BinaryEncoding::RIGHT) {
                for (int i = 0; i < scTable.rfPortCodeCount(); i++) {
                    printPattern(" ", slotField.extraBits());
                    RFPortCode& code = scTable.rfPortCode(i);
                    cout << portCodeBits(code);
                    printPattern(" ", enc.width() - scTable.width());
                    cout << " : " << portCodeDescription(code) << endl;
                }
                for (int i = 0; i < scTable.iuPortCodeCount(); i++) {
                    printPattern(" ", slotField.extraBits());
                    IUPortCode& code = scTable.iuPortCode(i);
                    cout << portCodeBits(code);
                    printPattern(" ", enc.width() - scTable.width());
                    cout << " : " << portCodeDescription(code) << endl;
                }
                for (int i = 0; i < scTable.fuPortCodeCount(); i++) {
                    printPattern(" ", slotField.extraBits());
                    FUPortCode& code = scTable.fuPortCode(i);
                    cout << portCodeBits(code);
                    printPattern(" ", enc.width() - scTable.width());
                    cout << " : " << portCodeDescription(code) << endl;
                }
            } else {
                for (int i = 0; i < scTable.rfPortCodeCount(); i++) {
                    printPattern(" ", slotField.width() - scTable.width());
                    RFPortCode& code = scTable.rfPortCode(i);
                    cout << portCodeBits(code);
                    cout << " : " << portCodeDescription(code) << endl;
                }
                for (int i = 0; i < scTable.iuPortCodeCount(); i++) {
                    printPattern(" ", slotField.width() - scTable.width());
                    IUPortCode& code = scTable.iuPortCode(i);
                    cout << portCodeBits(code);
                    cout << " : " << portCodeDescription(code) << endl;
                }
                for (int i = 0; i < scTable.fuPortCodeCount(); i++) {
                    printPattern(" ", slotField.width() - scTable.width());
                    FUPortCode& code = scTable.fuPortCode(i);
                    cout << portCodeBits(code);
                    cout << " : " << portCodeDescription(code) << endl;
                }
            }
        }
    }
}
References SlotField::componentIDPosition(), Encoding::encoding(), InstructionField::extraBits(), SocketCodeTable::fuPortCode(), SocketCodeTable::fuPortCodeCount(), SlotField::hasNoOperationEncoding(), SocketEncoding::hasSocketCodes(), SocketCodeTable::iuPortCode(), SocketCodeTable::iuPortCodeCount(), SlotField::noOperationEncoding(), portCodeBits(), portCodeDescription(), printPattern(), SocketCodeTable::rfPortCode(), SocketCodeTable::rfPortCodeCount(), BinaryEncoding::RIGHT, SocketEncoding::socketCodes(), SlotField::socketEncoding(), SlotField::socketEncodingCount(), SocketEncoding::socketIDWidth(), SocketEncoding::socketName(), Conversion::toBinary(), Encoding::width(), SlotField::width(), SocketCodeTable::width(), and SocketEncoding::width().
Referenced by printDestinationFieldEncodings(), and printSourceFieldEncodings().
printSourceFieldEncodings()
static void printSourceFieldEncodings (const MoveSlot & moveSlot) static
Prints the encodings of the source field of the given move slot.
Parameters
moveSlot The move slot.
Definition at line 566 of file ViewBEM.cc.
{
    if (!moveSlot.hasSourceField()) {
        return;
    }
    SourceField& srcField = moveSlot.sourceField();
    cout << "Source field encodings:" << endl;
    printSlotFieldEncodings(srcField);
    if (srcField.hasImmediateEncoding()) {
        ImmediateEncoding& enc = srcField.immediateEncoding();
        printPattern("X", srcField.extraBits());
        if (srcField.componentIDPosition() == BinaryEncoding::LEFT) {
            if (enc.encodingWidth()) {
                cout << Conversion::toBinary(
                    enc.encoding(), enc.encodingWidth());
            }
            printPattern(
                "X", srcField.width() - srcField.extraBits() - enc.width());
            printPattern("I", enc.immediateWidth());
        } else {
            printPattern("I", enc.immediateWidth());
            printPattern(
                "X", srcField.width() - srcField.extraBits() - enc.width());
            if (enc.encodingWidth()) {
                cout << Conversion::toBinary(
                    enc.encoding(), enc.encodingWidth());
            }
        }
        cout << " : short immediate" << endl;
    }
    for (int i = 0; i < srcField.bridgeEncodingCount(); i++) {
        BridgeEncoding& enc = srcField.bridgeEncoding(i);
        printPattern("X", srcField.extraBits());
        if (srcField.componentIDPosition() == BinaryEncoding::RIGHT) {
            printPattern(
                "X", srcField.width() - srcField.extraBits() - enc.width());
            cout << Conversion::toBinary(enc.encoding(), enc.width());
        } else {
            cout << Conversion::toBinary(enc.encoding(), enc.width());
            printPattern(
                "X", srcField.width() - srcField.extraBits() - enc.width());
        }
        cout << " : bridge " << enc.bridgeName() << endl;
    }
}
References SourceField::bridgeEncoding(), SourceField::bridgeEncodingCount(), BridgeEncoding::bridgeName(), SlotField::componentIDPosition(), Encoding::encoding(), ImmediateEncoding::encodingWidth(), InstructionField::extraBits(), SourceField::hasImmediateEncoding(), MoveSlot::hasSourceField(), SourceField::immediateEncoding(), ImmediateEncoding::immediateWidth(), BinaryEncoding::LEFT, printPattern(), printSlotFieldEncodings(), BinaryEncoding::RIGHT, MoveSlot::sourceField(), Conversion::toBinary(), Encoding::width(), ImmediateEncoding::width(), and SourceField::width().
Referenced by printMoveSlot().